### ISSUE TITLE
resource disk defintion is ignored on job run

### ISSUE THREAD

**Issue by WizoneDE** [hashicorp/nomad#10009]
added the following params to resources {} within a nomad job:

cpu  = 400
memory = 768
disk = 1024

but only cpu and memory are working. diskMB is showing 0 after parsing the information to run the job. 

When I change the values within the generated information it is be ignored too:

changed cpu (to 300) and diskMB (to 1000)

+/- Resources {
+/- CPU: "400" => "300"
DiskMB: "0"
IOPS: "0"
MemoryMB: "768"
} 

Running Nomad 1.0.2

**Comment by mr-karan** [comment]
`disk` doesn't seem to be listed in the [`resources`](https://www.nomadproject.io/docs/job-specification/resources#resources-stanza) stanza. Did you mean to use [`ephemeral_disk`](https://www.nomadproject.io/docs/job-specification/ephemeral_disk) instead?

**Comment by WizoneDE** [comment]
ephemerial_disk has its own area:

      "EphemeralDisk": {
        "Sticky": false,
        "SizeMB": 300,
        "Migrate": false
      },

job -> group -> task -> resources

this is the generated block of a nomad file:

since there is DiskMB listed it should be able to define?
disk is a accepted param within resources. it looks like it is defined but not using by nomad currently.

"Resources": {
            "CPU": 300,
            "MemoryMB": 768,
            **"DiskMB": 0,**
            "IOPS": 0,
            "Networks": [
              {
                "Mode": "",
                "Device": "",
                "CIDR": "",
                "IP": "",
                "MBits": 1,
                "DNS": null,
                "ReservedPorts": [
                  {
                    "Label": "https",
                    "Value": 8084,
                    "To": 0,
                    "HostNetwork": "default"
                  }
                ],
                "DynamicPorts": null
              }
            ],
            "Devices": null
          },

**Comment by tgross** [comment]
Hi @WizoneDE! The link @mr-karan gave you to the [`resources`](https://www.nomadproject.io/docs/job-specification/resources) block is right. You can specify `cpu`, `memory`, and (with a device plugin) `device`.

**Comment by tgross** [comment]
Looks like this one has been answered. Going to close it out.
