### ISSUE TITLE
filter topology view by node status

### ISSUE THREAD

**Issue by emulanob** [hashicorp/nomad#10002]
### Nomad version
1.0.3

### Operating system and Environment details
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1029-aws x86_64)

### Issue
This is a feature request to add filters to the Topology page, similarly to the Clients page.

In a datacenter with lots of spot instances that get terminated suddenly, the Topology view give a false impression of unused clients hanging in the cluster, when in fact their status is "down", which can be confirmed once clicking on them.

Maybe adding the same set of filters from the Clients page will improve the benefit of that view.

**Comment by khaledabdelaziz** [comment]
I just came here to request this exact feature..
I'd love to have filters under topology page by "Node Class" and "State". Ideally same filters exist under Clients tab.
