### ISSUE TITLE
`nomad plan` nonzero exit on succes

### ISSUE THREAD

**Issue by traceypooh** [hashicorp/nomad#10027]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
v1.0.3

### Operating system and Environment details
macosx/Darwin

### Issue
If it plans and places successfully should exit 0 status like < v1.0 nomad have done

### Reproduction steps
nomad plan example.hcl; echo $?
+ Job: "example"
+ Task Group: "cache" (1 create)
  + Task: "redis" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 example.hcl

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
1

### Job file (if appropriate)
`nomad job init` => example.hcl above

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by traceypooh** [comment]
hmm, i might be wrong on this.  closing since i think it can exit 0 or 1 depending on if job plan would have created a _new_ job or not

**Comment by tgross** [comment]
Hi @traceypooh! Yeah that's right. It's buried a bit in the [`nomad job plan`](https://www.nomadproject.io/docs/commands/job/plan) docs, but:

> Plan will return one of the following exit codes:
> 
> * 0: No allocations created or destroyed.
> * 1: Allocations created or destroyed.
> * 255: Error determining plan results.
