### ISSUE TITLE
hcl2 length() of map issue

### ISSUE THREAD

**Issue by traceypooh** [hashicorp/nomad#10024]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v1.0.3

### Operating system and Environment details
Mac mini

### Issue
job.hcl:34,15-22: Error in function call; Call to function “length” failed: collection must be a list, a map or a tuple.

### Reproduction steps
```
locals {
  nports = "${length({ "a" = "b"})}"
}
```
(see also https://discuss.hashicorp.com/t/hcl2-length-of-map-issue/20911/2 )

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by jrasell** [comment]
Hi @traceypooh and thanks for raising this issue. I can reproduce this locally but have not been able to figure the cause a the moment, so will label accordingly.

**Comment by tgross** [comment]
At first I suspected this was a quoting issue, but it looks like it fails with the same error even without quoting:

```hcl
# map fails
locals {
  nports = length({ "a" = "b" })
}
```

```hcl
# lists work fine
locals {
  nports = length(["a", "b"])
}
```

Suspecting that we actually have an "object" here and not a map, I tried using [`convert`](https://www.nomadproject.io/docs/job-specification/hcl2/functions/conversion/convert):

```hcl
locals {
  nports = length(convert({"a" = "b"}, map(string)))
}
```

And that passes validation. One of the libraries we use is a little picky about [object vs map](https://github.com/zclconf/go-cty/issues/17) but it looks like the documentation could use some improvement as well. I'll open a PR shortly with some doc fixes.

**Comment by traceypooh** [comment]
thanks y'all!

**Comment by traceypooh** [comment]
whoa, @jrasell -- your name kept running through my head and just finally realized where from.  levant!!   😍
