### ISSUE TITLE
driver/raw_exec: driver is not setting environment variables correctly 

### ISSUE THREAD

**Issue by mgenov** [hashicorp/nomad#1002]
I'm starting a Go builded app with raw_exec driver and it looks like that Env variables are not set as expected in Nomad v.0.3.1 

### Nomad version
Nomad v0.3.1

### Operating system and Environment details
OSX and Linux

### Issue

```golang
   path := os.Getenv("PATH")
   io.WriteString(w, fmt.Sprintf("Path: %s", path))
```
This is go code of my app that prints "Path: " after app is running with nomad (i.e path is empty). 

### Job file
```
job "testapp" {
    region = "global"
    datacenters = ["europe"]

    type = "service"
    priority = 50

    update {
        # Stagger updates every 10 seconds
        stagger = "10s"

        # Update a single task at a time
        max_parallel = 1
    }

    group "testapp" {
        count = 1
        # Define a task to run
        task "testapp" {
            driver = "raw_exec"
            
            config {
                command = "myapp"
                args = ["-h", ":8885"]
            }

            artifact {
                # The archive will be extracted before the task is run, making 
                # it easy to ship configurations with your binary.
                source = "https://url/to/myapp"
            }

            resources {
                cpu = 800 # 500 Mhz
                memory = 2048
                disk = 1000
            }
            
            logs {
                max_files = 5
                max_file_size = 10
            }
        }
    }
}
```

**Comment by diptanu** [comment]
@mgenov I see that your job spec doesn't have any environment variables. Are you expecting the environment variables of the shell in which Nomad client to be present in the environment of your task? Also, Nomad 0.3.1 doesn't set the environment variables of the session in which Nomad client is running to the tasks. We have introduces that after Nomad 0.3.1 and will go out in Nomad 0.3.2

For now. you will have to use the env block, to add environment variables to a task. Please look at the `env` key in https://www.nomadproject.io/docs/jobspec/index.html

Nomad 0.3.2 is expected to come out over the next week or two.

**Comment by mgenov** [comment]
Yes, I'm expecting the environment variables of the shell and I don't want to provide any custom environment variables. Currently my configuration options are passed as arguments and apps is starting but it crashing after some operations are executing (normally working when app is not started with nomad) and I'm suspecting that the problem is with the environment. 

Does this means that I have to add PATH and other environments manually to my job ?

**Comment by diptanu** [comment]
@mgenov Yeah right now you will have to add all your environment variables in the job spec. If you can build Nomad from the master and try, you should have all the environment variables from the shell.

**Comment by mgenov** [comment]
Yep, I've found the problem. It's not from the environment, it's from the open files limit. Any idea how can I set the number of max open files with nomad ?

**Comment by diptanu** [comment]
@mgenov This is an operating system property. You will have to play with `ulimit` and the setting would depend on the distribution of Linux you are using.

**Comment by mgenov** [comment]
Thanks.
