### ISSUE TITLE
disable_file_sandbox not recognized

### ISSUE THREAD

**Issue by schemmer** [hashicorp/nomad#10028]
"client unexpected keys disable_file_sandbox "
the above is seen when attempting to start nomad.  Config entry reads as follows:

client {
    enabled = true
    disable_file_sandbox = true
}

nomad version: Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)

**Comment by tgross** [comment]
Hi @schemmer! The config value you want is one of the [`template`](https://www.nomadproject.io/docs/configuration/client#template-parameters) parameters, so you want:

```hcl
client {
  template {
    disable_file_sandbox = false
  }
```

**Comment by schemmer** [comment]
Thank you - my bad - that did the trick!
