### ISSUE TITLE
Docs: Nomad Namespace is incorrectly mentioned as Enterprise only

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#10029]
On the tutorial page https://learn.hashicorp.com/tutorials/nomad/namespaces, Namespace seems to be mentioned as Enterprise only. 

However I believe that's outdated since https://www.nomadproject.io/docs/commands/namespace mentions:

> Namespaces are open source in Nomad 1.0. Namespaces were Enterprise-only when introduced in Nomad 0.7.

**Comment by jrasell** [comment]
Hi @mr-karan and thanks for spotting this, we will get this fixed up as required.

**Comment by tgross** [comment]
Doing some issue cleanup. I can't find the PR that did so because the Learn site got split up a little while back into 2 different (private) repos but looks like this got fixed at some point. Thanks for opening the issue @mr-karan!
