### ISSUE TITLE
Topology no longer shows node names

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#10040]
Nomad 1.03

We just noticed this one this morning, and we only see this behavior on 1 cluster so far.   Right now we see the Topology UI not showing any server names at all.   Other clusters seem fine so we aren't sure what's so "special" about this one :)

<img width="1011" alt="Screen Shot 2021-02-17 at 8 49 28 AM" src="https://user-images.githubusercontent.com/46198537/108213666-4add8380-70fd-11eb-806f-db516f359b93.png">

**Comment by tgross** [comment]
Hi @idrennanvmware I know the topology UI "collapses" some information depending on the density of the cluster... but you said this was only on 1 server within a cluster? The other servers for the same cluster don't collapse the information?

**Comment by backspace** [comment]
Indeed, after there are more than 50 nodes in a cluster the layout is considered [dense](https://github.com/hashicorp/nomad/blob/5bbe53f2228aae11f1e006d4e0dc43f92c0c0da1/ui/app/components/topo-viz.js#L49-L53) and the node names [don’t show anymore](https://github.com/hashicorp/nomad/blob/491bb3bde1716e83b7b5a83cdd7c6e53bcff931e/ui/app/templates/components/topo-viz/node.hbs#L2-L13):

```
  // Once a cluster is large enough, the exact details of a node are
  // typically irrelevant and a waste of space.
  get isDense() {
    return this.args.nodes.length > 50;
  }
```

But differing based on server is puzzling 🤔

**Comment by idrennanvmware** [comment]
Hey team - sorry for any confusion.   What i meant is we have multiple clusters, all with different node counts, but this cluster is the only one we see this on.  I will correct the terminology in the original post.

It does have a high number of nodes though - so the density compression makes sense.

**Comment by DingoEatingFuzz** [comment]
@idrennanvmware Hi! Although it is intentionally behavior, that doesn't mean it's _good_ intentional behavior. I'd like to get you first impressions! 

Noted that without explanation the change was surprising, but now that you know what's going on, does it make sense? The goal was to optimize for density, but not at the expense of clarity.

Also, when in this denser view, nodes in the viz can be clicked and you'll get info in the left-hand panel.

**Comment by idrennanvmware** [comment]
Hi @DingoEatingFuzz 

So, at least the way we use it, we did lose value by not having the node names.   We could still "see" packing over the nodes but it wasn't easily observable which node(s) they were without additional navigation.   IMO, given the choice, I'd rather not have the dense view.   That said, what we have found "missing" from this view is the ability to filter (like the client view) on node names (and partial ones).

Hope this helps, please feel free to ask anything about how/what we're using this for

**Comment by DingoEatingFuzz** [comment]
This definitely helps, thank you 🙂

> please feel free to ask anything about how/what we're using this for

I want to know ALL THE THINGS! In this exact moment, I don't know what to ask, but please know that if you ever feel compelled to blog about how you are using Nomad, I will read it 😄

**Comment by idrennanvmware** [comment]
@DingoEatingFuzz  - a blog entry is definitely on my list.   We've been waiting for the...write time....to do one :)   It's pretty close I think to being a good time.   Will definitely let you all know!
