### ISSUE TITLE
security_opt with seccomp profle not working

### ISSUE THREAD

**Issue by nagireddygatla** [hashicorp/nomad#10060]
I'm still facing this issue, can someone help resolve this.
`Failed to create container configuration for image - xyz: failed to parse security_opt configuration: opening seccomp profile (/local/seccomp.json) failed: open /local/seccomp.json: no such file or directory`

Here is the config:
config { image = "<docker_image_url>" security_opt = [ "seccomp=/local/seccomp.json" ] }

I tried all combinations as below, but still no luck:
1. /local/seccomp.json
2. local/seccomp.json
3. file://local/seccomp.json
4. file:///local/seccomp.json
5. `{\"defaultAction\":\"SCMP_ACT_ERRNO\",\"syscalls\":[{\"name\":\"perf_event_open\",\"action\":\"SCMP_ACT_ALLOW\",\"args\":null}]}`

I can confirm that the file is present in the location - `/local/seccomp.json` within docker container.

**Comment by tgross** [comment]
From https://github.com/hashicorp/nomad/issues/6720#issuecomment-783560860

> Yes I defined the file in my repository, and moved the file from repo to docker container using template stanza. And I can see the seccomp file in this location - /local/seccomp.json if I nomad exec into the container. You mean the seccomp file should be on host instead of container, for nomad to access the seccomp profile json file?

Yes, the file needs to be on the host instead of the container.

**Comment by nagireddygatla** [comment]
Ok got it, the file needs to be on host because having file on docker and getting syscalls access is kind of security hole you think? Is there any particular location that seccomp profile needs to be present on the host?

**Comment by shishir-a412ed** [comment]
@nagireddygatla Like @tgross mentioned, with `docker` driver, even if you want to enable the default seccomp profile, the file must be present on the host. `docker` also provides a default `seccomp` profile (https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) which you can save on your host filesystem and use it.

You can also try to run your container with `containerd-driver` (https://github.com/Roblox/nomad-driver-containerd)
The good thing about `containerd-driver` is, for using the default seccomp profile no file needs to be present on the host, and you can just set `seccomp=true` in your `TaskConfig` to enable the default seccomp profile.

**Comment by tgross** [comment]
> Ok got it, the file needs to be on host because having file on docker and getting syscalls access is kind of security hole you think?

Right.

>  Is there any particular location that seccomp profile needs to be present on the host?

The profile just needs to be readable by `dockerd`, but given that's usually running as `root` that's not normally a problem.

**Comment by nagireddygatla** [comment]
> entioned, with `docker` driver, even if you want to enable the default seccomp profile, the file must be present on the host. `docker` also provides a default `seccomp` profile (https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) which you can save on your host filesystem and use it.
> 
> You can also try to run your container with `containerd-driver` (https://github.com/Roblox/nomad-driver-containerd)
> The good thing about `containerd-driver` is, for using the default seccomp profile no file needs to be present on the host,

Yes I used the profile file from moby repository and modified it for my usage, but I had the file on docker container instead of host. Containerd-driver is not an option for our infra.

**Comment by nagireddygatla** [comment]
> @nagireddygatla Like @tgross mentioned, with `docker` driver, even if you want to enable the default seccomp profile, the file must be present on the host. `docker` also provides a default `seccomp` profile (https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) which you can save on your host filesystem and use it.
> 
> You can also try to run your container with `containerd-driver` (https://github.com/Roblox/nomad-driver-containerd)
> The good thing about `containerd-driver` is, for using the default seccomp profile no file needs to be present on the host, and you can just set `seccomp=true` in your `TaskConfig` to enable the default seccomp profile.

Yes I used the profile file from moby repository and modified it for my usage, but I had the file on docker container instead of host. Containerd-driver is not an option for our infra.

**Comment by nagireddygatla** [comment]
> > Ok got it, the file needs to be on host because having file on docker and getting syscalls access is kind of security hole you think?
> 
> Right.
> 
> > Is there any particular location that seccomp profile needs to be present on the host?
> 
> The profile just needs to be readable by `dockerd`, but given that's usually running as `root` that's not normally a problem.

Ok, got it. Let me reach to systems team, and have this on host and test it. I will close the issue, once I finish my testing if you dont mind.

**Comment by nagireddygatla** [comment]
Few more questions, sorry to bother again. Out of below configs, which one would work for me if the file present on host at this location -> /local/seccomp.json?

1. /local/seccomp.json
2. local/seccomp.json
3. file://local/seccomp.json
4. file:///local/seccomp.json
5. {\"defaultAction\":\"SCMP_ACT_ERRNO\",\"syscalls\":[{\"name\":\"perf_event_open\",\"action\":\"SCMP_ACT_ALLOW\",\"args\":null}]}

Its strange that option 5 also did not work for me, is the json string is not an option now for seccomp? The only option that worked for me is "unconfined".

**Comment by tgross** [comment]
Take a look at the [`security_opt`](https://www.nomadproject.io/docs/drivers/docker#security_opt) docs. We do the API equivalent of passing the string directly to the [`--security-opt`]https://docs.docker.com/engine/reference/run/#security-configuration) flag. Here's an example jobspec that I've successfully tested, assuming the profile file can be found at `/opt/seccomp.json` on the host:

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
        ports = ["db"]
        security_opt = [
          "seccomp=/opt/seccomp.json"
        ]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

Also, the JSON string you have in the post above doesn't seem to be valid -- the Docker container was getting started but immediately failing without anything useful in the `dockerd` logs. You'll want to explore that problem.

**Comment by tgross** [comment]
Ok, looks like this issue was resolved. Going to close it, but feel free to open a new issue if you have more problems.

**Comment by nguyenvulong** [comment]
> 1. /local/seccomp.json
> 2. local/seccomp.json
> 3. file://local/seccomp.json
> 4. file:///local/seccomp.json
> 5. {"defaultAction":"SCMP_ACT_ERRNO","syscalls":[{"name":"perf_event_open","action":"SCMP_ACT_ALLOW","args":null}]}
> 
> Its strange that option 5 also did not work for me, is the json string is not an option now for seccomp? The only option that worked for me is "unconfined".

Was you able to make it work?

I have tried all available suggestions, but


```
security_opt = [
      "seccomp=default.json"
]
```
throws
> docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/9106969acfdc8bd98cd9723cf6f6c386531d8a6c46486d5370af139cebbb4d6a/start: Internal Server Error ("Decoding seccomp profile failed: invalid character 'd' looking for beginning of value")


**and**
 
```
security_opt = [
      "seccomp=file://default.json"
]
```
throws
> docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/f9e09c56ccba0f3dc092cc3541f7fa18e98d5ef907a611e75816d5e8d72bcb9b/start: Internal Server Error ("Decoding seccomp profile failed: invalid character 'i' in literal false (expecting 'a')")


And yes, the only option that worked for me is `unconfined`.
