### ISSUE TITLE
Systemd unit incorrect config

### ISSUE THREAD

**Issue by m1keil** [hashicorp/nomad#10065]
### Nomad version
```
Nomad v1.0.2 (4c1d4fc6a5823ebc8c3e748daec7b4fda3f11037)
```

### Operating system and Environment details
`Ubuntu 20.04.2 LTS`

### Issue
Nomad unit is incorrectly configure and includes `StartLimitIntervalSec` config under [Service] instead of [Unit].
This results in the following error when starting:

```
/usr/lib/systemd/system/./nomad.service:16: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
```

### Reproduction steps
Install Nomad from the official package and start service.

**Comment by shoenig** [comment]
Thanks for reporting, @m1keil !

I'm surprised this got by for so long, looks like this was added in 2018 (around the time the option was renamed from `StartLimitInterval` to `StartLimitIntervalSec` and moved from `Service` to `Unit`)

Ubuntu 18.04
```bash
$ systemd --version | head -n1
systemd 237

$ sudo systemctl daemon-reload 
$ sudo systemctl start test

$ sudo systemd-analyze verify test.service
/etc/systemd/system/./test.service:14: Unknown lvalue 'StartLimitIntervalSec' in section 'Service'
```
