### ISSUE TITLE
telemetry: Prometheus config flag `prometheus_metrics` doesn't alter endpoint behaviour

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#10070]
### Nomad version
`Nomad v1.0.3`

### Issue
When the `telemetry.prometheus_metrics` config value is set to false, calling `/v1/metrics?format=prometheus` still responds 200 OK and with Prometheus formatted data. In accordance with the [documentation](https://www.nomadproject.io/docs/configuration/telemetry#prometheus), I would expect this call to fail. 

### Reproduction steps

Config file:
```hcl
telemetry {
  prometheus_metrics = false
}
```

- run the Nomad agent using `nomad agent -dev -config=<FILE>`
- attempt to use the metrics endpoint using the Prometheus format `curl -sD - -o /dev/null 'localhost:4646/v1/metrics?format=prometheus'` viewing the response headers
- optionally view the response body from the endpoint `curl -s 'localhost:4646/v1/metrics?format=prometheus'`

**Comment by tgross** [comment]
See also https://github.com/hashicorp/nomad/issues/7866
