### ISSUE TITLE
Cannot run example job  'example.nomad'  on OSX as it fails to initialize log driver.

### ISSUE THREAD

**Issue by asanami** [hashicorp/nomad#1008]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.3.1

### Operating system and Environment details
OSX Version 10.9.4

### Issue

When trying to run the 'example.nomad' job example, I get the following error from the nomad agent:
```
Cannot start container d09ad04f59ffdad051a8b526527971d6ad1ed5366264e5767d0e334871d3c7f6: Failed to initialize logging driver: stat /var/folders/r0/_qlzwrp54bd9nwr2dn1jrpm501_ygz/T/plugin080402504: no such file or directory
```

### Reproduction steps

The agent is started as follows:
```
sudo ./nomad agent -dev
```

The job is started as follows:
```
nomad run example.nomad
```

### Nomad Server logs (if appropriate)
```
   2016/03/30 10:35:42 [DEBUG] driver.docker: setting container name to: redis-9e0f7f6d-62a4-5bb3-d41a-84bddd3b9ab4
    2016/03/30 10:35:42 [INFO] driver.docker: created container d09ad04f59ffdad051a8b526527971d6ad1ed5366264e5767d0e334871d3c7f6
    2016/03/30 10:35:43 [ERR] driver.docker: failed to start container d09ad04f59ffdad051a8b526527971d6ad1ed5366264e5767d0e334871d3c7f6: API error (404): Cannot start container d09ad04f59ffdad051a8b526527971d6ad1ed5366264e5767d0e334871d3c7f6: Failed to initialize logging driver: stat /var/folders/r0/_qlzwrp54bd9nwr2dn1jrpm501_ygz/T/plugin080402504: no such file or directory
```

### Job file (if appropriate)

Using the 'example.nomad' job file.

**Comment by diptanu** [comment]
@asanami I am guessing you are using boot2docker or something like that on your Mac to run Nomad? This wouldn't work since we start a syslog server alongside the container to collect logs. 

Can you please use a Linux environment to test Nomad? We have a `Vagrantfile` in the Nomad repo, I think that would be the easiest way for you to test Nomad.

**Comment by catufunwa** [comment]
I'm running into this problem still while using Docker for Mac, not boot2docker. Is there something I need to change for the example job to work?

**Comment by dadgar** [comment]
Hey we do not currently support Docker for Mac/Windows
