### ISSUE TITLE
filesystem docs are unclear: /alloc cannot be mounted like /secrets

### ISSUE THREAD

**Issue by aep** [hashicorp/nomad#10122]
### Nomad version
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Reproduction steps

according to  https://www.nomadproject.io/docs/internals/filesystem
you can change the hardcoded bind mounts to something else. however, this only works with secrets, not with data:

```hcl
driver = "docker"
config {
  mounts = [{
    type     = "bind"
    source   = "alloc"
    target   = "/etc/ceph/"
    readonly = false
    }]  
```
does not work. neither does source="data" and the docs do not contain any hint how this works.

#### Actual Result

```
2021-03-05T15:26:41+01:00  Driver Failure   failed to create container: API error (400): invalid mount config for type "bind": bind source path does not exist: /opt/nomad/alloc/6b06d716-6360-0e08-ac68-499c949751b1/ceph-monitor/alloc
```

note that the path it is trying is relative to the task, not to the alloc. so i'm assuming there's some magic matching here for "secrets" and possibly another magic that isnt documented for /alloc

**Comment by tgross** [comment]
The source path is relative to the task working directory. So there's no magic going on there, just that `alloc` isn't in the task working directory, but in the alloc working directory. That should get cleared up in the docs there for sure.

**Comment by aep** [comment]
aah you're right. secrets is also mounted relative to the task dir,

however the builtin /alloc is relative to the group 

```json
        "HostConfig": {
            "Binds": [
                "/opt/nomad/alloc/8d9b4a51-6982-0f2b-508b-618fbd8fb41c/alloc:/alloc",
                "/opt/nomad/alloc/8d9b4a51-6982-0f2b-508b-618fbd8fb41c/ceph-monitor/local:/local",
                "/opt/nomad/alloc/8d9b4a51-6982-0f2b-508b-618fbd8fb41c/ceph-monitor/secrets:/secrets"
            ],

```

and the docs make it sound like you can rebind this 

```
To work around this limitation, you can use the task driver's mounting capabilities to mount one of the three directories to another location in the task. 
```

so there is actually no functionality to change the bind path?

**Comment by aep** [comment]
```
source   = "../../alloc/data"  
```

works but i'm scared this will accidentally be removed in the future.
is this the intended way of doing it, and if yes should it be in the docs to prevent accidental breaking it?

**Comment by tgross** [comment]
> so there is actually no functionality to change the bind path?

Right. Nomad isn't special-casing this at all; it's just a function of how the source path works for binding.

> is this the intended way of doing it, and if yes should it be in the docs to prevent accidental breaking it?

Yes and yes!

**Comment by tgross** [comment]
Docs updated in #10132 and those will ship to the website once Nomad 1.1.0 goes out. Thanks for opening this issue @aep!
