### ISSUE TITLE
Connect-enabled allocations fail to GC after canary promotion

### ISSUE THREAD

**Issue by splittingred** [hashicorp/nomad#10123]
### Nomad version

```
nomad -v
Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)
```

### Operating system and Environment details

Debian Buster.

### Issue

We are seeing a strange issue where, with large deploys (30+ allocations), health checks for a single allocation of a connect-enabled task not get cleaned up until a GC is run. You can see the allocation getting marked for GC:

```
Mar  5 20:18:52 nomad-client-xxxx nomad[1001]:     2021-03-05T20:18:52.325Z [INFO]  client.gc: marking allocation for GC: alloc_id=51303a0d-5917-ece1-b4c9-562ef42de9e8
```

However, immediately then, the following checks sync and then start failing in Consul:

```
Mar  5 20:18:52 nomad-client-xxxx consul[1004]:     2021-03-05T20:18:52.339Z [INFO]  agent: Synced service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000
Mar  5 20:18:52 nomad-client-xxxx consul[1004]: 2021-03-05T20:18:52.339Z [INFO]  agent: Synced service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000
Mar  5 20:18:52 nomad-client-xxxx consul[1004]:     2021-03-05T20:18:52.376Z [INFO]  agent: Synced service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy
Mar  5 20:18:52 nomad-client-xxxx consul[1004]: 2021-03-05T20:18:52.376Z [INFO]  agent: Synced service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy
Mar  5 20:18:52 nomad-client-xxxx consul[1004]:     2021-03-05T20:18:52.445Z [INFO]  agent: Synced check: check=service:_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy:2
Mar  5 20:18:52 nomad-client-xxxx consul[1004]: 2021-03-05T20:18:52.445Z [INFO]  agent: Synced check: check=service:_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy:2
Mar  5 20:18:52 nomad-client-xxxx consul[1004]:     2021-03-05T20:18:52.953Z [WARN]  agent: Check socket connection failed: check=service:_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy:1 error="dial tcp 127.0.0.1:23705: connect: connection refused"
Mar  5 20:18:52 nomad-client-xxxx consul[1004]:     2021-03-05T20:18:52.953Z [WARN]  agent: Check is now critical: check=service:_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy:1
```

The orphaned health check is still in Consul, in a critical state.

This continues until a GC is run (either system wide, or through `nomad system gc`). Once that happens, the check disappears and the service moves out of critical state:

```
Mar  5 20:45:13 nomad-client-xxxx nomad[1001]:     2021-03-05T20:45:13.749Z [INFO]  client.gc: garbage collecting allocation: alloc_id=51303a0d-5917-ece1-b4c9-562ef42de9e8 reason="forced collection"
Mar  5 20:45:13 nomad-client-xxxx consul[1004]:     2021-03-05T20:45:13.859Z [INFO]  agent: Deregistered service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy
Mar  5 20:45:13 nomad-client-xxxx consul[1004]: 2021-03-05T20:45:13.859Z [INFO]  agent: Deregistered service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000-sidecar-proxy
Mar  5 20:45:14 nomad-client-xxxx consul[1004]:     2021-03-05T20:45:14.142Z [INFO]  agent: Deregistered service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000
Mar  5 20:45:14 nomad-client-xxxx consul[1004]: 2021-03-05T20:45:14.142Z [INFO]  agent: Deregistered service: service=_nomad-task-51303a0d-5917-ece1-b4c9-562ef42de9e8-group-redacted-web-redacted-redacted9000
```

Notes: this does use Canary deployments, which we have some suspicion might be related, as it only occurs sometimes after a canary promotion. We have not seen this in non-canary pipelines. This service in the logs above had 3 canary allocations. Only one allocation orphaned its health check on promotion.

### Reproduction steps

We have not been able to consistently reproduce this.

#### Expected Result

The health check and allocation would clean itself up in GC properly.

#### Actual Result

The allocation+health check stays around until a GC is run.

**Comment by tgross** [comment]
Hi @splittingred! There's a few different processes at play here:

* The service and health checks are registered/deregistered in Consul by the allocation runner's `groupservice_hook`. The specific function that deregisters the services/health check is the [`PostRun`](https://github.com/hashicorp/nomad/blob/v1.1.0/client/allocrunner/groupservice_hook.go#L196-L217), which should be triggered whenever the allocation is stopped.
* The state on the server is garbage collected by `nomad system gc` or `nomad job stop -purge`.
* The allocation state on the client is what you're seeing collected by `client.gc` in the logs. This is independent of the server and only actually happens when the client reaches a threshold.

You mentioned this is only happening with Connect health checks? I don't see anything in the [changelog](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md) for recent releases that specifically addresses this, but I know there were a bunch of Connect-related bug fixes. Given that you haven't been able to reproduce it reliably, it might help us narrow down the behavior if you could provide a (redacted) jobspec that at least does it sometimes.

**Comment by splittingred** [comment]
Hey @tgross! Thanks for the clarifications and detail.

Since upgrading to Nomad 1.0.4, we haven't seen this issue in a couple of months, so I'm going to close this until I can reliably reproduce it and provide you with a JobSpec accordingly. Thanks!
