### ISSUE TITLE
Docs: Nomad vs Kubernetes

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/nomad#10120]
I was just browsing [this page](https://www.nomadproject.io/docs/nomad-vs-kubernetes), which seems to be [this file](https://github.com/hashicorp/nomad/blob/master/website/content/docs/nomad-vs-kubernetes/index.mdx) and I noticed it references Kubernetes as a Docker-specific platform. Just FYI, this will be inaccurate soon. In [December 2020](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) it was announced that Docker will no longer be the container runtime engine for Kubernetes.

**Comment by schmichael** [comment]
Thanks @dak1n1. We should find a better term since Kubernetes has offered other container runtimes for quite some time and is deprecated their Docker runtime support. "Linux container" - while far more generic - is probably a better term.
