### ISSUE TITLE
failed to create cgroup

### ISSUE THREAD

**Issue by wuhao-123456** [hashicorp/nomad#10127]
Nomad version
0.12.2

Operating system and Environment details
CentOS 7.8

Client disk and memory is ok, have a lot of space  
machine have 16 Cores and 32G RAM

when nomad client execute a job，an error occurred 
this is  error message
failed to launch command with executor: rpc error: code = Unknown desc = container_linux.go:349: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/memory/nomad/7db819db-9da2-0995-abf2-0ea0c5d226cb: cannot allocate memory\""

is my  task error？
![error](https://user-images.githubusercontent.com/60963201/110271637-69031900-8003-11eb-9236-10f9e6b69163.jpg)

**Comment by tgross** [comment]
Hi @wuhao-123456! Are you running Nomad as root? See the [user permissions requirements](https://www.nomadproject.io/docs/install/production/requirements#user-permissions).

**Comment by tgross** [comment]
Going to close this one out as unanswered but please feel free to reopen if you have more information.
