### ISSUE TITLE
Nomad Agent Restart causes jobs to restart when job has template stanza referencing Vault

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#10152]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Windows Server 2016
PhotonOS3

### Issue
We have noticed that any time we restart a Nomad Agent, then the Job allocation restarts immediately as well.   This applies to both Windows and Linux nodes.  We started by noticing this on our System jobs so we started to investigate.  As we dug deeper we found that if we restarted Nomad agents then only jobs with the Vault stanza were restarted.

### Reproduction steps
Create a job that has a vault ```with secrets``` usage in the template stanza - then restart the Nomad agent.  Any allocations on that node, that have a job with a template stanza referencing Vault, will be restarted
![image](https://user-images.githubusercontent.com/46198537/110533322-172dc200-80db-11eb-8b24-028ddc1eee45.png)

@tgross  - I am suspicious this behavior may have been introduced with this bug fix: https://github.com/hashicorp/nomad/pull/9636

What are your thoughts?

**Comment by fredwangwang** [comment]
is this related? https://github.com/hashicorp/nomad/pull/9636

**Comment by tgross** [comment]
Hi @idrennanvmware @fredwangwang! Yeah this is expected due to #9636 with dynamic secrets like those from the PKI engine.

From the [Nomad 1.0.2 Upgrade Guide](https://www.nomadproject.io/docs/upgrade/upgrade-specific#nomad-1-0-2):

> **Dynamic secrets trigger template changes on client restart**
>
> Nomad 1.0.2 changed the behavior of template `change_mode` triggers when a client node restarts. In Nomad 1.0.1 and earlier, the first rendering of a template after a client restart would not trigger the `change_mode`. For dynamic secrets such as the Vault PKI secrets engine, this resulted in the secret being updated but not restarting or signalling the task. When the secret's lease expired at some later time, the task workload might fail because of the stale secret. For example, a web server's SSL certificate would be expired and browsers would be unable to connect.
> 
> In Nomad 1.0.2, when a client node is restarted any task with Vault secrets that are generated or have expired will have its `change_mode` triggered. If `change_mode = "restart"` this will result in the task being restarted, to avoid the task failing unexpectedly at some point in the future. This change only impacts tasks using dynamic Vault secrets engines such as PKI, or when secrets are rotated. Secrets that don't change in Vault will not trigger a `change_mode` on client restart.

What's happening is the embedded consul-template is now being told to refresh the secret on start instead of ignoring the running tasks, being unable to refresh, and the task just failing at random in the future (potentially long after the secret has expired in Vault, depending on the secrets backend). This automatically triggers whatever the `change_mode` is.

**Comment by idrennanvmware** [comment]
Thanks @tgross  - looks like we got ourselves wrapped around the axle for no reason here.   We did see 1 job render a template we didn't expect but overall we aren't seeing mass restarts of jobs across the cluster so that's good!

**Comment by tgross** [comment]
It's been a month or so, so 'm going to close this one out, but please feel free to reopen if there's more info! Thanks!

**Comment by idrennanvmware** [comment]
@tgross  - Keeping this one closed BUT we do have some more information around the behavior - the above appears to be a symptom of what we discovered here: https://github.com/hashicorp/nomad/issues/10761
