### ISSUE TITLE
Updating a paramaterized periodic job

### ISSUE THREAD

**Issue by frederikbosch** [hashicorp/nomad#10168]
### Nomad version
Nomad v0.11.0 (5f8fe0afc894d254e4d3baaeaee1c7a70a44fdc6)

### Issue
I have a paramaterized job with a periodic stanza. So with `nomad job dispatch` I create new periodic jobs. This works very well. But when I run `nomad job run.. ` to update this job, only the parent job gets updated. The scheduled children are not updated with the new settings and running the Force Launch button in the UI causes a 501 with the message `rpc error: force launch for job "certbot-renewal" failed: can't force run non-tracked job "certbot-renewal" (default)`.

### Solution
The question is whether this behavior is desired. I think that when the `parameterized` stanza is equal between the updates, the children should be updated too. In my case, I just want to update the version number of my docker image which in this case causes `config { image }`  and `config { args }` to change. When the `parameterized` stanza changes between the updates, it might be blocked and only allowed to update if the user acknowledges that children become *non-tracked*.

**Comment by tgross** [comment]
Hi @frederikbosch! Once a job has been dispatched, it's a unique job with a "pointer" back to the original. Each time a periodic job fires, it creates a unique job with a "pointer" back to the parent.

If I understand the situation here, you're creating a tree of jobs like so:

```
root
├── dispatched1 (periodic job root)
│   ├── periodicT01:00
│   ├── periodicT02:00
│   └── periodicT03:00
├── dispatched2 (periodic job root)
│   ├── periodicT01:00
│   ├── periodicT02:00
│   └── periodicT03:00
└── dispatched3 (periodic job root)
    ├── periodicT01:00
    ├── periodicT02:00
    └── periodicT03:00
```

When you update the root job, only dispatched jobs that start _after_ that update will receive the updated definition. The periodic jobs that get spawned by those dispatched jobs have their job definition owned by the dispatched job.

So in the tree above, if you update `root`, nothing happens. But then when you dispatch `dispatched4`, it will have the new definition for all its periodic jobs.

**Comment by frederikbosch** [comment]
Hi @tgross, if this is intentional, then I guess this issue can be closed, right?

p.s. I see your work on CSI, great!

**Comment by tgross** [comment]
Thanks!
