### ISSUE TITLE
Unable to start nomad client on windows server 2012r2

### ISSUE THREAD

**Issue by shubamraina** [hashicorp/nomad#10178]
Hi,

I am using nomad on linux a Server and Client and these are working fine. Now I need to install nomad on windows server 2012r2 and needs to connect windows as client with the server. I am struggling with the configuration and successful start of the nomad client on windows. As per the official nomad document, Installation is done but I am unable to find the configuration file and configure nomad as client on windows. Can anyone please suggest some steps with the configuration file that can be followed to get this issue resolved.

WindowsOS - Server 2012r2(Datacenter)(Need to make it as nomad client)
Nomad server OS -- Ubuntu16.04LTS

Thanks in advance!

**Comment by notnoop** [comment]
Hi Shubamrian!  Mind if you post the configuration you used and the output of the nomad agent command?

Our docs don't have step-by-step details for setting up Nomad on Windows, and I'll make a note to improve that.  Meanwhile, the high levels steps should be similar to Linux.  You should be able to use the same Linux nomad client configuration files for Windows, with minor changes (e.g. updating data dir path).  You can find our test environment  Windows client at is https://github.com/hashicorp/nomad/blob/v1.0.4/e2e/terraform/config/full-cluster/nomad/client-windows/client-windows.hcl .

For setting up a Nomad as a Windows service, you can check https://learn.hashicorp.com/tutorials/nomad/windows-agent .

If these don't work, please post the config and process output and we can provide better feedback.

**Comment by shubamraina** [comment]
Hi @notnoop 

I have tried configuring the file on windows Client for Nomad but after service is created it is not started while using (sc.exe start "Nomad") command to start.

One Question: Is it mandatory to have consul client(On windows) connected with the Consul Server. OR I Can "Comment Out" the consul configuration part from the configuration file.
If Consul is mandatory, I tried to configure Consul Client(On windows) Where I am trying to configure (Nomad Client) from the official document but unable to configure and start the service.

Here is the Configuration file of Nomad Client:

enable_debug = true

log_level = "debug"

log_file = "C:\\Program Files\\nomad\\nomad.log"

data_dir = "C:\\Program Files\\nomad\\data"

bind_addr = "0.0.0.0"

# Enable the client
client {
  enabled = true

  options {
    # Allow rawexec jobs
    "driver.raw_exec.enable" = "1"
  }
}

consul {
  address = "IP Address of Consul:8500"
}

vault {
  enabled = true
  address = "http://IPAddressofvault:8200"
}

telemetry {
  collection_interval        = "1s"
  disable_hostname           = true
  prometheus_metrics         = true
  publish_allocation_metrics = true
  publish_node_metrics       = true
}


Here is the configuration file of Consul Client on Windows:

@"
datacenter = `"Countryname`"
data_dir = "C:\Hashicorp\Consul\data"
#encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="
#ca_file = "${CONSUL_DIR}/certs/consul-agent-ca.pem"
#cert_file = "${CONSUL_DIR}/certs/dc1-server-consul-0.pem"
#key_file = "${CONSUL_DIR}/certs/dc1-server-consul-0-key.pem"
verify_incoming = true
verify_outgoing = true
verify_server_hostname = true
"@ | Out-File -Encoding ASCII -FilePath "${CONSUL_DIR}/consul.hcl"

I have checked the document https://learn.hashicorp.com/tutorials/consul/deployment-guide  -> For Consul Configuration but stacked at the step 8th of the document.

Thankyou for your time in advance!

**Comment by shubamraina** [comment]
Hi Everyone,

Any update on the above query ?



Thanks&Regards,
Shubam Raina

**Comment by tgross** [comment]
Doing some issue cleanup here...

> One Question: Is it mandatory to have consul client(On windows) connected with the Consul Server. OR I Can "Comment Out" the consul configuration part from the configuration file.

It's not required to use Consul at all for Nomad, but any features that require Consul (like `service` blocks without `provider = "nomad") won't work.
