### ISSUE TITLE
unable to join cgroup

### ISSUE THREAD

**Issue by liuq4360** [hashicorp/nomad#1018]
when i use nomad v0.3.1 to launch java driver for java task , run into the following problem, i run nomad client and server in root user, i don't know that's wrong and how to solve this:
2016/04/01 17:00:02 [ERR] executor: unable to join cgroup: Unit -.scope already exists.

**Comment by dadgar** [comment]
Hmm what OS are you using. Is it using systemd?

**Comment by liuq4360** [comment]
centos7.1 ，no systemd

**Comment by dadgar** [comment]
Does this happen deterministically? Is it a vanilla install of CentOS? do you have cgroups mounted?

**Comment by liuq4360** [comment]
sorry, i don't say clearly, actually, i changed a lot code in the java.go, 
ype JavaDriverConfig struct {
	RunStatus string `mapstructure:"run_status"` //jar or class
	JarPath string   `mapstructure:"jar_path"`
	JvmOpts []string `mapstructure:"jvm_options"`
	Args    []string `mapstructure:"args"`
}

args := []string{}
	if driverConfig.JarPath == "" {
		return nil, fmt.Errorf("jar_path must be specified")
	}

	if driverConfig.RunStatus == "class" { //run java program as class
		// Look for jvm options
		if len(driverConfig.JvmOpts) != 0 {
			d.logger.Printf("[DEBUG] driver.java: found JVM options: %s", driverConfig.JvmOpts)
			args = append(args, driverConfig.JvmOpts...)
		}

		// Build the argument list.
		if len(driverConfig.Args) != 0 {
			args = append(args, driverConfig.Args...)
		}
		args = append(args, driverConfig.JarPath)
	} else {
		// Look for jvm options
		if len(driverConfig.JvmOpts) != 0 {
			d.logger.Printf("[DEBUG] driver.java: found JVM options: %s", driverConfig.JvmOpts)
			args = append(args, driverConfig.JvmOpts...)
		}

		// Build the argument list.
		args = append(args, "-jar", driverConfig.JarPath)
		if len(driverConfig.Args) != 0 {
			args = append(args, driverConfig.Args...)
		}
	}

i want to run java main class program assigned by me, as follows 
java -cp /hadoopecosystem/spark/conf/:/hadoopecosystem/spark/lib/spark-assembly-1.6.0-hadoop2.6.2.jar:/hadoopecosystem/spark/lib/datanucleus-api-jdo-3.2.6.jar:/hadoopecosystem/spark/lib/datanucleus-core-3.2.10.jar:/hadoopecosystem/spark/lib/datanucleus-rdbms-3.2.9.jar:/hadoopecosystem/hadoop/etc/hadoop/ -Xms2g -Xmx2g org.apache.spark.deploy.SparkSubmit --master spark://10.10.2.14:7077 --class cn.whaley.recommend.rankinglist.NewRankingList /script/recommend/helios-rankinglist/jar/RankingList.jar
in this case the problem can happen.

**Comment by dadgar** [comment]
Could you provide the following information:
1) Does this always happen?
2) The full client logs
3) What happens if you run a simple "exec" job such as `/bin/sleep` for 10 seconds

**Comment by liuq4360** [comment]
this aways happens,
when run exec job such as /bin/sleep/ also has this problem,
my job configuration is：
# There can only be a single job definition per file.
# Create a job with ID and Name 'example'
job "echo" {
        datacenters = ["dc1"]
        type = "service"
        constraint {
                attribute = "${attr.kernel.name}"
                value = "linux"
        }
        update {
                stagger = "10s"
                max_parallel = 1
        }

        group "execgroup" {
                task "echo" {
                        driver = "exec"
                        config {
                                command = "echo"
                                args = ["========for exec echo test!========"]
                        }
                        service {
                                name = "${TASKGROUP}-echo"
                                tags = ["global", "echo"]
                                port = "db"
                                check {
                                        name = "alive"
                                        type = "tcp"
                                        interval = "10s"
                                        timeout = "2s"
                                }
                        }
                        resources {
                                cpu = 500 # 500 Mhz
                                memory = 256 # 256MB
                                network {
                                        mbits = 10
                                        port "db" {
                                        }
                                }
                        }
                }
        }
}

the client logs are：
    2016/04/12 16:57:36 [DEBUG] client: updated allocations at index 39 (pulled 1) (filtered 1)
    2016/04/12 16:57:36 [DEBUG] client: allocs: (added 1) (removed 0) (updated 0) (ignore 1)
    2016/04/12 16:57:36 [DEBUG] client: starting task runners for alloc '34c1fdd6-718c-9bfa-8b9e-8a7e3662a3b9'
    2016/04/12 16:57:36 [DEBUG] client: starting task context for 'echo' (alloc '34c1fdd6-718c-9bfa-8b9e-8a7e3662a3b9')
    2016/04/12 16:57:36 [DEBUG] plugin: starting plugin: /usr/local/bin/nomad []string{"/usr/local/bin/nomad", "executor", "/root/hashicorp/nomad/data/alloc/34c1fdd6-718c-9bfa-8b9e-8a7e3662a3b9/echo/echo-executor.out"}
    2016/04/12 16:57:36 [DEBUG] plugin: waiting for RPC address for: /usr/local/bin/nomad
    2016/04/12 16:57:36 [DEBUG] plugin: nomad: 2016/04/12 16:57:36 [DEBUG] plugin: plugin address: unix /tmp/plugin164233452
    2016/04/12 16:57:38 [DEBUG] plugin: /usr/local/bin/nomad: plugin process exited
    2016/04/12 16:57:40 [ERR] client: failed to start task 'echo' for alloc '34c1fdd6-718c-9bfa-8b9e-8a7e3662a3b9': error starting process via the plugin: error entering the plugin process in the cgroup: Unit -.scope already exists.:
    2016/04/12 16:57:40 [INFO] client: Not restarting task: echo for alloc: 34c1fdd6-718c-9bfa-8b9e-8a7e3662a3b9 

    2016/04/12 16:57:40 [DEBUG] client: updated allocations at index 41 (pulled 0) (filtered 2)
    2016/04/12 16:57:40 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 2)

the output in echo-executor.out  as follows：

2016/04/12 16:57:36 [DEBUG] executor: launching command echo ========for exec echo test!========
2016/04/12 16:57:38 [ERR] executor: unable to join cgroup: Unit -.scope already exists.
2016/04/12 16:57:38 [ERR] executor: unable to kill process: 1 error(s) occurred:

* errors while destroying cgroup: 1 error(s) occurred:

* error getting pids: open /sys/fs/cgroup/devices/system.slice/-.scope/cgroup.procs: no such file or directory
2016/04/12 16:57:38 [ERR] executor: error destroying cgroup: errors while destroying cgroup: 1 error(s) occurred:

* error getting pids: open /sys/fs/cgroup/devices/system.slice/-.scope/cgroup.procs: no such file or directory

**Comment by dadgar** [comment]
@liuq4360 Could you build off master and try?

**Comment by liuq4360** [comment]
@dadgar  my nomad v0.3.1 is checkout from github and build by myself

**Comment by dadgar** [comment]
@liuq4360 can you try this binary: https://releases.hashicorp.com/nomad/0.3.2-rc2/

Believe it is fixed

**Comment by liuq4360** [comment]
ok, i try it and see what happens.

**Comment by liuq4360** [comment]
@dadgar  I try 0.3.2-rc2, there is no unable to join cgroup problem when  use exec driver to run echo job.

**Comment by dadgar** [comment]
Nice! Seems it is fixed then!
