### ISSUE TITLE
Nomad install binds to ipv6, not ipv4 address

### ISSUE THREAD

**Issue by jmwilkinson** [hashicorp/nomad#10189]
Version:
```
# nomad -v
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)
```

This is the case on both ubuntu and centos 7:

The [quickstart cli guide](https://learn.hashicorp.com/tutorials/nomad/get-started-run?in=nomad/get-started) has the following command:

```
$ sudo nomad agent -dev -bind 0.0.0.0 -log-level INFO
```

The expectation given the parameters is that the service will match all IPv4 addresses. To match IPv6, the expectation is that `::` would need to be supplied.

However, just looking for that port once the service is running gives us the following:

```
# netstat -lnp | grep 4646
tcp6       0      0 :::4646                 :::*                    LISTEN      5582/nomad
```

And the service then will not accept external IPv4 traffic (which won't, I believe, even reach it)

```
# curl -vvv http://$NOMAD_IP:4646
* Rebuilt URL to: http://x.x.x.x:4646/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 4646 (#0)
> GET / HTTP/1.1
> Host: x.x.x.x:4646
> User-Agent: curl/7.54.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

So this feels like a bug to me, as the expectations that `-bind 0.0.0.0` should result in a bound IPv4 socket. But maybe there's some IPv4-mapped IPv6 stuff going on, but in that case I'd expect the service to be accessible via the IPv4 address externally.

**Comment by jmwilkinson** [comment]
Ok, my particular inability to connect was actually a `firewalld` issue, and I needed to run:

```
firewall-cmd --permanent --zone=public --add-port=4646/tcp
systemctl restart firewalld
```

Though I'm still curious about the tcp6 socket that's getting used. Is that a system-level thing? Or something controlled by nomad?

**Comment by notnoop** [comment]
Interesting. This oddity seems like a general golang peculiarity, where by default golang `net` servers listen to ipv6 addresses and rely on the linux kernel handling ipv4 traffic through ipv4-mapped ipv6 address.  The golang-nuts mailing list fielded a similar question as well: https://groups.google.com/g/golang-nuts/c/F5HE7Eqb6iM .

I have created a simple reproduction using golang's `net.Listen`.  With a simple golang file:

```go
package main

import (
        "io"
        "net"
)

func main() {
        ln, err := net.Listen("tcp", ":7070")
        if err != nil {
                panic(err)
        }
        for {
                conn, err := ln.Accept()
                if err != nil {
                        panic(err)
                }
                go func() {
                        go io.Copy(io.Discard, conn)
                        conn.Write([]byte("HTTP/1.1 200 OK\nContent-Length: 6\n\nHello\n"))
                        conn.Close()
                }()
        }
}
```

I can confirm that `netstat` only reports tcp6 but I can access the server through all ipv4 and ipv6 addresses:

```
vagrant@linux:/tmp/nettest$ go build -o nettest ./nettest.go
vagrant@linux:/tmp/nettest$ ./nettest &
[1] 5108
vagrant@linux:/tmp/nettest$ sudo netstat -lpe | grep 7070
tcp6       0      0 [::]:7070               [::]:*                  LISTEN      vagrant    34888      5108/./nettest
vagrant@linux:/tmp/nettest$ curl http://127.0.0.1:7070/
Hello
vagrant@linux:/tmp/nettest$ curl 'http://[::1]:7070/'
Hello
vagrant@linux:/tmp/nettest$ ipv4=$(ip addr show eth2 | grep 'inet ' | awk '{print $2;}' | cut -d/ -f1)
vagrant@linux:/tmp/nettest$ echo ${ipv4}; curl http://${ipv4}:7070/
10.199.0.200
Hello
vagrant@linux:/tmp/nettest$ ipv6=$(ip addr show eth1 | grep 'inet6 ' | awk '{print $2;}' | cut -d/ -f1)
vagrant@linux:/tmp/nettest$ echo $ipv6; curl -g "http://[${ipv6}%eth1]:7070/"
fe80::a00:27ff:fe2e:a5ca
Hello
```

I'm glad that you have resolved the firewall. I'm closing the issue, but please re-open for any follow up.
