### ISSUE TITLE
networking: add host network interpolation

### ISSUE THREAD

**Issue by AndrewChubatiuk** [hashicorp/nomad#10195]
### Proposal
Add `host_network` interpolation to be able to get host network name from node meta.

### Use-cases
As per #10106 it could be useful to have a `host_network` interpolation in case of using the same job spec for multiple regions with different network configuration 

### Attempted Solutions
It's possible to add multiple `group->port` stanzas with `service->port` interpolation but this configurations is redundant

**Comment by tgross** [comment]
Hi @AndrewChubatiuk sorry about the delay here... I want to make sure that the root problem of https://github.com/hashicorp/nomad/issues/10106 is better understood before we review this.

**Comment by tgross** [comment]
Closed by #10196, which will ship in Nomad 1.1.0
