### ISSUE TITLE
Restricting a certain kind of job to one per node

### ISSUE THREAD

**Issue by lakshitgarg** [hashicorp/nomad#10215]
Hi All. I have certain use case where i want to run one particular kind of job only one per machine. For example , i have a job called SAP automation . Now every time a job which is placed in node class "SAP" is triggered , there shall be only one job per node . 
I was looking for "Set a maximum number of tasks for an agent" but couldn't find a possible solution.

**Comment by tgross** [comment]
Hi @lakshitgarg! You may want to use the [`distinct_hosts`](https://www.nomadproject.io/docs/job-specification/constraint#distinct_hosts) constraint. That would require that you set the job count to the number of expected nodes. Alternately, depending on what the workload is, you may be able to use a [`system`](https://www.nomadproject.io/docs/schedulers#system) job with a constraint for those node classes.

We're also planning on implementing a "system batch" job type (ref https://github.com/hashicorp/nomad/issues/2527), but that isn't going to make it into Nomad 1.1.
