### ISSUE TITLE
Nomad bridge network and docker0 bridge network should be able to talk to each other.

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#10217]
### Proposal
It would be very helpful if containers deployed in 'legacy' networking mode onto the normal docker docker0 bridge interface were able to talk to (the public facing ports of) container groups using 'bridge' networking mode and the nomad bridge interface.

### Use-cases
We have a traditional nomad setup using docker where each container receives an IP address from the docker IP pool and sits on the docker0 network. Inter-host networking is solved outside of docker (we use tinc but other examples would include ubuntu fan networking using fanctrl).

We would like to migrate to using bridge networking where tasks within a group share an 'external' IP from the nomad client subnet range and internally all sit on an isolated 'lo' network. However, these containers sit on the 'nomad' bridge network. We can talk to them from the host but can't talk to them from a container on the docker network (either started via nomad or directly with docker).

### Attempted Solutions
We've tried changing the subnet range used by the nomad client and using firewall rules to allow routing between the 2 bridges but it's not an area of expertise for us.

**Comment by tgross** [comment]
@far-blue there's a [`bridge_network_name`](https://www.nomadproject.io/docs/configuration/client#bridge_network-name) and [`bridge_network_subnet`](https://www.nomadproject.io/docs/configuration/client#bridge_network_subnet) client configuration field that might do the job for you.

I just tried this out with the following client config:

```hcl
client {
  bridge_network_name = "docker0"
  bridge_network_subnet = "172.17.0.1/16"
}
```

Here are my two bridges:

```
$ ip addr
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:47:c6:b0:c6 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:47ff:fec6:b0c6/64 scope link
       valid_lft forever preferred_lft forever
...
5: nomad: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether e2:02:97:1b:c9:ef brd ff:ff:ff:ff:ff:ff
    inet 172.26.64.1/20 brd 172.26.79.255 scope global nomad
       valid_lft forever preferred_lft forever
    inet6 fe80::e002:97ff:fe1b:c9ef/64 scope link
       valid_lft forever preferred_lft forever
```

And then I ran the example job that's generated by `nomad job init -short` and I get the following for the resulting container:

```
$ docker inspect b14 | jq '.[].NetworkSettings.Networks'
{
  "bridge": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": null,
    "NetworkID": "2b664fcaf2469202ff1076afff5d3288c38fb614c7e435b2ac69bea3aa28dba4",
    "EndpointID": "3ceed9421549e06bd1b4b6d4cf292fa07ba1c621dfe8e710ad35995e8c25ecfd",
    "Gateway": "172.17.0.1",
    "IPAddress": "172.17.0.2",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:11:00:02",
    "DriverOpts": null
  }
}
```

Obviously your environment is unique but give that a try and see if it does the job for you.

**Comment by far-blue** [comment]
Oh, that's an interesting idea, sharing the docker0 bridge. Do you know anything about the behaviour of docker and nomad in such a situation? Would nomad try to clean up the docker0 bridge, for instance? Any idea how the iptables rules would interact? And what about use of IP addresses - do nomad and docker both check before trying to assign an IP to make sure it's not in use?

I mean, if it's safe it would be a very elegant solution but it would be good to confirm Nomad's behaviour if possible.

**Comment by tgross** [comment]
Hi @far-blue, my apologies: I wanted to make sure I had a working example for you and it took me a bit to get back to this. It turns out I gave you some bad advice here. I forgot that the default network [`mode = "host"`](https://www.nomadproject.io/docs/job-specification/network#mode), so the config I showed you doesn't get used, and my example was invalid.

Unfortunately it turns out you can't safely reuse that bridge. So we'll need to come up with another way to solve this. It seems like the sort of thing that a Consul Connect gateway is designed to solve (except usually for inter-host traffic), but that seems like overkill. Lemme stew on this a bit and chat with some of my colleagues to see if we can figure out a better answer for you.

---

Here's why you can't reuse the bridge network like that. With the following job that's configured to use bridge networking:

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "httpd" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }
  }
}
```


</details>

I realized we had the wrong subnet config, so that should be:

```hcl
client {
  bridge_network_name = "docker0"
  bridge_network_subnet = "172.17.0.0/16"
}
```

This now uses the CNI code path. Nomad will use files in `/var/lib/cni/networks/nomad` to keep track of which IPs its allocated. This results in the following somewhat odd network config from Docker, as Docker isn't the one handling the networking anymore:

```
$ docker inspect 085 |  jq '.[].NetworkSettings.Networks'
{
  "none": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": null,
    "NetworkID": "69f2e90ad510350a22b6d1d30d142e231042f9a630ff1f1552e6c950d137d5a1",
    "EndpointID": "5b34a8e48fd0da706369982ed5e6fe01e90b5dabd02d2470683bd63ac23851b7",
    "Gateway": "",
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "",
    "DriverOpts": null
  }
}
```

Then we can use `nsenter` to see the IP address:

```
$ sudo nsenter --net=/proc/8029/ns/net
root@linux# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether b6:bb:30:9d:73:6d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

However, if I then try to run a standard Docker container, I end up with the same IP address:

```
$ sudo nsenter --net=/proc/8922/ns/net
root@linux# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Which results in an unworkable iptables setup, and the Docker container won't get any traffic:

```
Chain CNI-FORWARD (1 references)
target     prot opt source               destination
NOMAD-ADMIN  all  --  anywhere             anywhere             /* CNI firewall plugin rules */
ACCEPT     all  --  anywhere             172.17.0.2           ctstate RELATED,ESTABLISHED
ACCEPT     all  --  172.17.0.2           anywhere

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8002
```

**Comment by far-blue** [comment]
Right, yeah, that makes sense but also means re-using the `docker0` network is going to be a non-starter :(

I've poked around a bit and as far as I can tell the basic issue boils down to the fact nothing is responding to ARP requests for IP addresses on the `nomad` network. Without a static route and with no ARP requests being replied to the kernel has no idea how to route packets - hence the 'No route to host' errors. The host node itself has an IP on the `nomad` subnet so can reach the `nomad` network containers, of course. In contrast, I can see ARP responses for containers on the `docker0` network meaning containers on the `nomad` network can 'see' containers on the `docker0` network.

If the `docker0` and `nomad` network interfaces weren't already bridges I'd have suggested shoving them in the same bridge but unfortunately you can't add bridge interfaces to a bridge.

**Comment by tgross** [comment]
I think I'd like to know more about your networking setup, in particular what routing looks like. I was able to get working cross-traffic between containers on `nomad` and `docker0`, with some caveats around the port mapping.

Here are the routes on the host:

```
$ ip route
default via 10.0.2.2 dev eth0 proto dhcp src 10.0.2.15 metric 100
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
10.0.2.2 dev eth0 proto dhcp scope link src 10.0.2.15 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.26.64.0/20 dev nomad proto kernel scope link src 172.26.64.1
```

And the IP addresses, before running any jobs:

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:c5:bc:64 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 85234sec preferred_lft 85234sec
    inet6 fe80::a00:27ff:fec5:bc64/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:92:24:ef:ee brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:92ff:fe24:efee/64 scope link
       valid_lft forever preferred_lft forever
17: nomad: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 42:1c:9a:97:75:6b brd ff:ff:ff:ff:ff:ff
    inet 172.26.64.1/20 brd 172.26.79.255 scope global nomad
       valid_lft forever preferred_lft forever
    inet6 fe80::401c:9aff:fe97:756b/64 scope link
       valid_lft forever preferred_lft forever
```

I run this job with bridge networking:

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "httpd" {
      driver = "docker"

      # this is a debian-based image with curl installed, and we listen
      # on port 8001 just to keep it running as a service
      config {
        image   = "0x74696d/curl:latest"
        command = "nc"
        args    = ["-lvp", "8001"]
        ports   = ["www"]
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }
  }
}
```

</details>

That gives me the following address:

```
Allocation Addresses (mode = "bridge")
Label  Dynamic  Address
*www   yes      10.0.2.15:22916 -> 8001
```

If I look at the IP routes inside the allocation, anything other than this IP is heading to the default route as expected:

```
$ nomad alloc exec abd ip route
default via 172.26.64.1 dev eth0
172.26.64.0/20 dev eth0 scope link  src 172.26.64.3
```


Now run a Docker container on the `docker0` bridge:

```
docker run -d --net=bridge -p 8002:8001 busybox:1 httpd  -v -f -p 8001 -h /var/www
```

And we exec into that container to see its address and IP routes:

```
$ : docker exec -it c8c ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever

$ docker exec -it c8c ip route
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 scope link  src 172.17.0.2
```

I can exec into our Nomad-owned allocation and `curl` the Docker container, albeit on the internal port and not the mapped port:

```
$ nomad alloc exec abd curl 172.17.0.2:8001
<HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD>
<BODY><H1>404 Not Found</H1>
The requested URL was not found
</BODY></HTML>
```

**Comment by far-blue** [comment]
Hi :)

Yes, we have no problems talking to containers on the `docker0` network from a container on the `nomad` network. It's the other way round that doesn't work. Using your example, if you swap over the 2 containers and then curl from the container in the `docker0` network to the `nomad` network container on its `nomad` network IP can you successfully make a connection? When we try we get `No route to host`.

**Comment by tgross** [comment]
Ah, sorry. Ok, well I tested that and... it seems to work to?

Here's my example Nomad job:

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "httpd" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }
  }
}
```

</details>


I run the job, and see its address both from the perspective of Nomad and inside the container:

```
$ nomad alloc status 60c
...
Allocation Addresses (mode = "bridge")
Label  Dynamic  Address
*www   yes      10.0.2.15:26998 -> 8001

$ nomad alloc exec 60c ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether aa:18:b5:72:24:a3 brd ff:ff:ff:ff:ff:ff
    inet 172.26.64.14/20 brd 172.26.79.255 scope global eth0
       valid_lft forever preferred_lft forever

$ nomad alloc exec 60c ip route
default via 172.26.64.1 dev eth0
172.26.64.0/20 dev eth0 scope link  src 172.26.64.14
```


Then I start a Docker container:

```
$ docker run -it --net=bridge --rm 0x74696d/curl:latest /bin/sh
/ # ip addr

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
11: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever

/ # ip route
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 scope link  src 172.17.0.2

/ # curl 10.0.2.15:26998
<html>hello, world</html>/
 ```

Maybe the issue you're having is about routing the Nomad-assigned address on the network more generally? Like, ignoring Docker for the moment are you able to reach the Nomad-assigned address from elsewhere on the network?

**Comment by far-blue** [comment]
Hi :)

Sorry for the delay in replying. After your last example I went ahead and stepped through the process of creating a complete copy of our production environment in miniature on some VMs to try and work out what was happening. Took a little while but I think I've worked out the issue.

Yes, you are absolutely correct - in a clean setup with nomad and docker all the containers can talk to each other just as you'd expect. This is regardless of whether the containers are started in docker or by nomad in the docker0 or nomad bridge networks.

For reference, the problem was caused by the interaction between the docker0 bridge and our underlay network which is tinc. Tinc creates a virtual interface (tap or tun, depending on setup) and we have simply added it as a member of the docker0 bridge network so containers on different hosts can see each other. I can't see any reason why this would be a problem but it looks like tinc is interfering with the forwarding of packets between the docker0 bridge and the nomad bridge.

Having identified this, I've found an alternative way of setting up tinc using iptables forwarding rules instead of adding it to the docker0 bridge and now everything appears (in my test environment) to be working as intended :)

Thank you very much for the time and effort you took to review and help out and I'm sorry it turned out to be my problem, not a generic issue for you guys to consider!

**Comment by tgross** [comment]
Happy to hear you've got it worked out!

**Comment by blmhemu** [comment]
I am sorry to re-open this thread again. But I seem to be facing a similar issue. When I use `mode="bridge"`, the containers cannot do DNS, as I have set my DNS to docker0. But for all other tasks where no mode is specified, it works fine.

## The normal container (no bridge mode)
![image](https://user-images.githubusercontent.com/19410501/136394614-30d0bd05-782c-45d2-a6ef-86e56e0673d9.png)

## Container with bridge mode
![image](https://user-images.githubusercontent.com/19410501/136394825-61a086d7-160b-4fc3-b4b0-1cf048b51ca4.png)

The DNS for both the containers point to the docker interface.
Additionally, if I set dns_servers to say 1.1.1.1, the DNS works fine in both cases.
