### ISSUE TITLE
Better connect-native experience in host network mode

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#10239]
This is a follow up to https://github.com/hashicorp/nomad/pull/8443#discussion_r601721492

Basically what happens currently is that connect native tasks in bridge mode get a consul socket mounted in and `CONSUL_HTTP_ADDR` set accordingly (+ other `CONSUL_*`). in host network mode it only gets the other `CONSUL_*` variables set. Now if consul does not listen on the default port, one has to manually set `CONSUL_HTTP_ADDR`. For consistency reasons (and less surprises in general) I think that the connect hook should also configure the addr in host network mode. @shoenig seems to agree (see previous link).

Now there are two options:

 * Just set `CONSUL_HTTP_ADRR` via nomad to the consul addr it know
 * Remove the conditional mounting that now exists and mount the socket unconditionally (in connect native mode)
 
Now I understand that option two is not really needed because in host network mode there should be a way to reach consul via TCP already (most likely 127.0.0.1:8500), but I am wondering if from a consistency and code complexity quality option two should be preferred… What do you think? I might be able to offer code, but I cannot decide which of the two options is the way to go.

**Comment by tgross** [comment]
I suspect option 1 is the best idea here @apollo13.
