### ISSUE TITLE
Nomad Does Not Respect Consul Healthchecks (New Relic)

### ISSUE THREAD

**Issue by truehhart** [hashicorp/nomad#10238]
### Nomad version
```
$ nomad -version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)
```

### Operating system and Environment details
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

AWS Hosted Nomad/Consul/Vault cluster, all LAN-connected inside a VPC.

### Issue

We have a working job definition, a container that boots up and does it's job. We have a healthcheck for it, available at container:8080 (accessible via a dynamically assigned port).
<img width="1380" alt="112547927-7b839d80-8dcc-11eb-97d1-991071070057" src="https://user-images.githubusercontent.com/66851285/112627618-e8397f00-8e42-11eb-88a3-0ee3885a0d20.png">

That's the only healthcheck we have except the default ones. We also have a canary deployment (1 canary, 10 minutes evaluation, 10 seconds passing minimum, using the "checks" option)

Problems start to arise as soon as we add a .NET New Relic agent inside the dockerfile to track logs, status, etc. Here's the diff between the "working" container and a "non-working" one.
```
+RUN apt-get update && apt-get install -y wget ca-certificates gnupg \
+&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
+&& wget https://download.newrelic.com/548C16BF.gpg \
+&& apt-key add 548C16BF.gpg \
+&& apt-get update \
+&& apt-get install -y newrelic-netcore20-agent
+
+ENV CORECLR_ENABLE_PROFILING=1 \
+CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
+CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
+CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so
```

When we boot the container up - **everything is working as it has been**. Container does it job, logs are showing that everything is fine, **consul healthcheck returns 200**. However, for whatever reason Nomad no longer respects the service status as provided by Consul.
Here's what it looks like inside Nomad:
![112548400-37dd6380-8dcd-11eb-991b-cbc3a899bc55](https://user-images.githubusercontent.com/66851285/112627649-eec7f680-8e42-11eb-97ea-83ee4dce88a3.png)

Just to be **completely clear** - the container is working and feeling great. There are no errors at all, relic is also working as it's supposed to. 

### Troubleshooting steps

We've tried a lot of different things, but only 2 seem to have worked:
1) Removing the api-health check in Nomad job-group-task-service-healthcheck stanza
2) Changing the healthcheck from "checks" to "task_states" in Nomad job-group-update stanza

Judging by what's happening it appears that Nomad is somehow incorrectly reading the "passing" code provided by consul.
Reviewing the logs clearly shows that as soon as container has bootstrapped and initialized - Consul does indeed mark the healthcheck as passing.

### Reproduction steps

1) Have a .NET app running in Docker
2) Have an HTTP healthcheck port in it that returns 200
3) Make sure Nomad job definition includes the Service stanza along with that healthcheck
4) Deploy to Nomad and ensure it's working/passing properly 
5) Add New Relic .NET agent to the container
6) Redeploy, make sure everything is working as it has been + new relic is up and running + healthcheck is still 200
7) ???

#### Expected Result

Everything is working as it has been, since nothing has changed

#### Actual Result

Nomad no longer considers the job healthy

### Job file (if appropriate)

**Full job definition (a terraform template):**

```hcl
job "${environment}-${stage}-${service}"  {
  datacenters = ["${datacenter}"]
  group "${environment}-${stage}" {
    update {
        max_parallel      = 1
        canary            = 1
        health_check      = "checks"
        min_healthy_time  = "10s"
        healthy_deadline  = "2m"
        progress_deadline = "10m"
        auto_revert       = true
        auto_promote      = true
    }
    network{
        port "service" {to = ${service_port}}
        mode = "bridge"
    }
    service {
        name = "${environment}-${stage}-${service}" 
        port = ${service_port}
        check = {
            type = "http"
            name = "api-health"
            port = "service"
            path = "/api/health"
            interval = "10s"
            timeout = "3s"
        }
        connect = {
            sidecar_task {
              resources {
                memory = ${sidecar_memory}
                cpu    = ${sidecar_cpu}
              }
            }
            sidecar_service {}
        }
    }
    task "${environment}-${stage}-${service}" {
      driver = "docker"
      env {
        ...
            ...
                 ...
        NEW_RELIC_LICENSE_KEY          = "${NEW_RELIC_LICENSE_KEY}"
        NEW_RELIC_APP_NAME               = "${environment}-${stage}-${service}"
      }
      template {
        data = <<EOH
${hosts}
        EOH
        destination = "local/etc/hosts"
      }
      config {
        image = "${docker_image}"
        cpu_hard_limit = true
        memory_hard_limit = ${memory_limits}
        auth {
            username = "${artifactory_username}"
            password = "${artifactory_password}"
        }
        ports = ["service"]
        volumes = [
          "local/etc/hosts:/etc/hosts"
        ]
        }
      resources {
        memory = ${memory_limits_soft}
        cpu    = ${cpu_limits}
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

Allocation - **74d6607c-af8b-5d52-085f-0e29807bea57**

[logs.txt](https://github.com/hashicorp/nomad/files/6211573/logs.txt)

**Comment by tgross** [comment]
Hi @truehhart! That's a tricky one for sure. The mechanism by which adding the NewRelic agent could cause this isn't obvious.

Given the message that your seeing "Task not running for min_healthy_time of 10s by deadline", and your healthy deadline of 2min, I'm wondering if adding the NewRelic agent is increasing the time it takes for the application to be "live" such that it's going over that 2min deadline. I've seen some of these monitoring agents do some really cool byte code injection that can slow startup times. I don't know what the characteristic start times for .NET applications is... I know with Java it can sometimes take a while for everything to get warmed up.

Once you've gone over that deadline, Nomad will consider the task unhealthy no matter whether its health checks subsequently pass. The logs you've provided don't include the placement of the task, so I can't check the timings myself. But that'd be the first place I'd want to look.

**Comment by truehhart** [comment]
Hey there @tgross!

Changing the healthy_deadline to 10m from 2m definitely did the trick!
Funnily enough, container took around 2m 5s to fully initialize and for the healthcheck to become available :)

It appears I was quite confused by the healthy_deadline and progress_deadline definitions in the documentation. It's still not clear to me on the exact purpose of the "progress" one, but as long as things work - we are all good!

Thanks for your prompt and helpful support, along with a great product to work with!
Have a good one and please consider this closed :)
