### ISSUE TITLE
hclfmt: not found on arm64

### ISSUE THREAD

**Issue by l1x** [hashicorp/nomad#10240]
### Nomad version

1.0.4

### Operating system and Environment details

Debian 11, arm64 / aarch64 / Raspberry Pi

### Issue

```
sh: 1: hclfmt: not found
in path ./e2e/upgrades/server3.hcl
sh: 1: hclfmt: not found
in path ./e2e/upgrades/client3.hcl
sh: 1: hclfmt: not found
in path ./e2e/upgrades/server1.hcl
sh: 1: hclfmt: not found
in path ./e2e/periodic/input/simple.nomad
sh: 1: hclfmt: not found
```

### Reproduction steps

make dev

#### Expected Result

not fail

#### Actual Result

Missing hclfmt

Is there a way to include hclfmt in the build during bootstrap?

**Comment by tgross** [comment]
Hi @l1x! It's installed during bootstrapping by the `deps` target here: https://github.com/hashicorp/nomad/blob/v1.0.4/GNUmakefile#L97

**Comment by l1x** [comment]
I see! So does this build system assume that I have $GOPATH/bin/ in my $PATH?

**Comment by tgross** [comment]
Yes, although that should probably be documented in the [contributing guide](https://github.com/hashicorp/nomad/tree/main/contributing#developing-without-vagrant) and asserted in the makefile. I'd be happy to review a PR to fix that if you'd like.

**Comment by l1x** [comment]
> Yes, although that should probably be documented in the [contributing guide](https://github.com/hashicorp/nomad/tree/main/contributing#developing-without-vagrant) and asserted in the makefile. I'd be happy to review a PR to fix that if you'd like.

I would be more than happy to contribute. I have two problems building on Raspberry PI / ARM64:
- the GOPATH was not part of my PATH (discussed in this ticket)
- I am not sure why this is in the Makefile
```
pkg/linux_arm/nomad: CC = arm-linux-gnueabihf-gcc-5
pkg/linux_arm64/nomad: CC = aarch64-linux-gnu-gcc-5
```

If I replace it with simply gcc it works.

**Comment by tgross** [comment]
> If I replace it with simply gcc it works.

The cross-compilation in the makefile is set up for our CI environment; so that's likely specific to the build environment and the version of GCC you've got.
