### ISSUE TITLE
Task resources in alloc-status output are unordered

### ISSUE THREAD

**Issue by phinze** [hashicorp/nomad#1025]
### Nomad version

Running master

### Operating system and Environment details

All

### Issue

Looks like the Task Resource list is unsorted - which makes for extra activity on a `watch` of an alloc.

### Reproduction steps

`watch -d nomad alloc-status {{alloc-id}}`

Task resources flop order.

**Comment by dadgar** [comment]
Fixed by da543308f2ceb0837eb3285369e6b32ae42a075a
