### ISSUE TITLE
Nomad scheduling halting

### ISSUE THREAD

**Issue by jonathanrcross** [hashicorp/nomad#10289]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Centos 7
Linux <hostname> 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Issue
We are seeing the Nomad brokers suddenly stop or have blocked evaluations (we think), although we have capacity capable of fulfilling the required constraints asked. Attempting to restart already running services seems to also be blocked. As soon as we restart the leader, scheduling resumes (and allocates) as normal with no changes in the available clients. So this has us thinking since nomad is optimistically concurrent that is certainly a leader related issue but either with the evaluation broker or plan broker, maybe some mutex /lockingissue or the leader is somehow unresponsive but responsive (lots of guesses)? Below are some of the observations we've tracked and will be sending an email with pprofs, leader log and operator debug archive.

### Observations
![Screen Shot 2021-04-02 at 8 45 08 AM](https://user-images.githubusercontent.com/16668441/113416903-44932600-9390-11eb-99b1-ea6bc2baac13.png)
![Screen Shot 2021-04-02 at 8 45 35 AM](https://user-images.githubusercontent.com/16668441/113416906-465ce980-9390-11eb-8ac4-3d59a62ab822.png)
![Screen Shot 2021-04-02 at 8 45 50 AM](https://user-images.githubusercontent.com/16668441/113416913-48bf4380-9390-11eb-8f3b-834a0201e8cf.png)

### Sever configuration
```hcl

autopilot {
  cleanup_dead_servers = true
  last_contact_threshold = "4s"
}

server {
  enabled = true
  bootstrap_expect = 3
  encrypt = "..."
  server_join {
    ...
  }

  node_gc_threshold = "15s"
  job_gc_interval = "1m"
  job_gc_threshold = "30s"

  heartbeat_grace = "15s"
  max_heartbeats_per_second = 45.0
  raft_multiplier = 7
}
```

### Reproduction steps
Unable to reproduce

#### Actual Result
All Jobs are stuck in pending, restarting a job also does not take affect.

**Comment by drewbailey** [comment]
@jonathanrcross Sorry that you are running into this and thank you for the detailed report and logs. 

The team will be taking a look at this and we'll hopefully have a follow up soon.

**Comment by jonathanrcross** [comment]
We're adding the autopilot stanza and updating the raft_protocol to 3. Surprised we didnt do that beforehand, will let you know if we still see the same behavior.

**Comment by drewbailey** [comment]
@jonathanrcross we were able to spend some time looking at the log bundle you sent as well as the graphs you provided.
We have a few follow questions and would like to learn more about your server's network topology as well as why you have tuned the heartbeat parameters and `raft_multiplier` to the values you shared.

The logs you provided show 200+ of the following error log message pairs. Yamux (our connection multiplexer) is configured to have a 30 second keepalive interval so it seems as though there was some form of network degradation  during this time period

```
[ERROR] nomad.rpc: yamux: keepalive failed: i/o deadline reached
[ERROR] nomad.rpc: multiplex_v2 conn accept failed: error="keepalive timeout"
```

We are also wondering if you were scaling up the number of client nodes during this time. The logs additionally show over 3000 uniq `node TTL expired` warnings

**Comment by jonathanrcross** [comment]
Hi @drewbailey and team, thanks for looking all of that over!

We tuned the heartbeat and raft_multipliers after having reach around 3500+ instances in the past, the servers would struggle (outage or potential outage) with rapid changes in instances being added/removed along with scheduling. By loosening the timing we thought it would relieve cpu and network demands at those peaks. We are running on gcp n1-standard-8's for the servers; not having to go a size bigger by using more relaxed timings. Our workloads are quite elastic and on this particular cloud require specific AZ to be placed, so instances are being initialized/removed quite frequently. 

As for the topology each server runs in a different AZ (GCP) within a region. Clients are in the same region and vpc.

Our autoscaler was scaling up at the time in an attempt to catchup to backlog before noticing that nothing was be allocated/placed.

Update from previous message, we haven't run into this issue since adding autopilot. We also increased the server quorum to 5.

**Comment by jonathanrcross** [comment]
Follow up from the autopilot and increasing server quorum size; just ran into the same behavior (took much longer to occur). Since once the first questions you asked was about timings, we'll set those back to the defaults and see if that helps.

**Comment by tgross** [comment]
While working on https://github.com/hashicorp/nomad/pull/13407 for a customer I searched back thru open issues to see if we'd see this before. On the leader `nmd-pool-8-servers-eet0f638-c04n.us-central1` I see the following goroutine:

```
goroutine 338696 [chan receive, 37 minutes]:
github.com/hashicorp/nomad/nomad.(*planner).planApply(0xc000416940)
	github.com/hashicorp/nomad/nomad/plan_apply.go:156 +0x529
created by github.com/hashicorp/nomad/nomad.(*Server).establishLeadership
	github.com/hashicorp/nomad/nomad/leader.go:250 +0x254
```

This exactly matches the behavior we saw on the cluster impacted by #13407, so I would expect this issue will be fixed there as well.
