### ISSUE TITLE
CSI plugin worng health count

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#10297]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Debian 10

### Issue
After rebooting a few nodes I got CSI plugin into the following state:
```
➜  nomad-jobs git:(master) ✗ nomad plugin status -verbose nfs
ID                   = nfs
Provider             = dev.rocketduck.csi.nfs
Version              = 0.2.0
Controllers Healthy  = 1
Controllers Expected = 1
Nodes Healthy        = 2
Nodes Expected       = 3

Allocations
No allocations placed
➜  nomad-jobs git:(master) ✗ nomad job status -namespace storage nfs.node
ID            = nfs.node
Name          = nfs.node
Submit Date   = 2021-04-04T20:28:45+02:00
Type          = system
Priority      = 50
Datacenters   = dc1
Namespace     = storage
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
node        0       0         3        0       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created     Modified
020a3307  42eb20db  node        0        run      running  13h12m ago  13h10m ago
a59ff912  8e100f4b  node        0        run      running  13h12m ago  13h12m ago
e6d594e3  a8efb906  node        0        run      running  13h12m ago  13h12m ago
```

The node jobs and controller are running just fine, but health only sees two as running. I am going to drain the node in question to see if that will make it any better.

**Comment by apollo13** [comment]
Node draining resulted in the wrong status as described in #9810 -- but otherwise it came back fine. Is there any way to debug this once the initial situation (in the first post) is reached? Something I can provide when I run into this next time?

**Comment by tgross** [comment]
Hi @apollo13! 

> Is there any way to debug this once the initial situation (in the first post) is reached? Something I can provide when I run into this next time?

What I'd be interested to see is the client logs for the plugins and the plugin alloc logs (usually the `-stderr` ones, depending on the plugin). In broad strokes, there's two kinds of problems that could be happening: the client could be unable to detect the plugin healthy for some reason, or the server could be miscounting. So having the client-side logs would help determine which is the problem.

Also, this seems like it's effectively a dupe of #9810, just with different results. Any reason you can think of we should keep this one open instead of centralizing the discussion over there?

**Comment by apollo13** [comment]
The plugin is my own and it didn't complain, will try to get the client logs next time.

> Also, this seems like it's effectively a dupe of #9810, just with different results. Any reason you can think of we should keep this one open instead of centralizing the discussion over there?

Not sure if it is actually a dupe, but let's close this one and split out back again later if it turns out to be a different issue.
