### ISSUE TITLE
nomad cli plugin command documentation and operation is confusing, only deals with csi plugins

### ISSUE THREAD

**Issue by tomqwpl** [hashicorp/nomad#10305]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Windows 10

### Issue
The nomad plugin command documentation is confusing, the command only deals with csi plugins.
I'm writing a task plugin and from the documentation naively expected that the CLI plugin command might show me the status, as the documentation indicates it might.
Looking at the actual implementation, it is only implemented to deal with csi plugins. The command takes a "type" argument, but does nothing with it, and there's a comment to say "extend this with other types".

At the least the documentation needs to be updated to reflect that this only applies to CSI plugins.

### Reproduction steps
nomad plugin status my-plugin

#### Expected Result
Status about my plugin

#### Actual Result
Error querying plugin: Unexpected response code: 404 (plugin not found)

**Comment by tgross** [comment]
Hi @tomqwpl! The [`plugin status`](https://www.nomadproject.io/docs/commands/plugin/status) say right at the top:

> The `plugin status` command displays status information for Container Storage Interface (CSI) plugins.

Is there another spot you were looking where you think we're missing that detail?

**Comment by tomqwpl** [comment]
The documentation at https://www.nomadproject.io/docs/commands/plugin is different, doesn't mention anything about that.

In fact I'm somewhat confused about there being two versions of that documentation. On the face of it the link you posted seems to be in the same place on the navigation on the left.

**Comment by tomqwpl** [comment]
Ah. It's the difference between the "overview" and the "status" page. The documentation for status does indeed say it's only about CSI plugins. The CLI command line help doesn't appear to mention anything though.

**Comment by tomqwpl** [comment]
Yes, CLI help output gives no indication it's only to do with CSI plugins.

**Comment by tgross** [comment]
Thanks! Yup, that's confusing for sure. We'll get that fixed. Or if you're up to it, I'd be happy to review a PR for the change.
