### ISSUE TITLE
[feature request] ACL per driver

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/nomad#10315]
### Proposal
Add ability to allow\restrict `submit_job` per specific execution driver, like `exec`, `raw_exec`, `docker`, etc.

### Use-cases
In some cases, we'd like to run `raw_exec` jobs, for example for system logs collections. It would be great if we could grant submit_job ACL to some people without fear that they could run a raw_exec job since only an SRE team, for example, should have that ability.

### Alternative solutions
Maybe it would be easier to restrict it per-namespace, like "raw_exec execution is only allowed in namespace X" - that won't require updating ACLs since they are already namespace-aware.

**Comment by tgross** [comment]
@Oloremo typically this kind of fine-grained access control is the sort of thing we expect people to implement via [Sentinel policies](https://learn.hashicorp.com/tutorials/nomad/sentinel) in the Enterprise product.
