### ISSUE TITLE
[question] How to pass host IP inside container?

### ISSUE THREAD

**Issue by trong** [hashicorp/nomad#1033]
I need to pass IP of host machine inside docker container. How can I do this?

**Comment by dadgar** [comment]
It is already set as an environment variable for you, $NOMAD_HOST_PORT_<label>.

See here for more info: https://www.nomadproject.io/docs/jobspec/environment.html

**Comment by cchatfield** [comment]
That seems to respond with the mapped port of the network. Is there another env variable that passes the nomad host ip?

**Comment by dadgar** [comment]
@cchatfield You can use `${NOMAD_IP_"label"}`

**Comment by cchatfield** [comment]
Another quick followup:

When I use  $NOMAD_HOST_PORT_. in tags for a service definition, I get the mapped port, but when I use it in the ENV section and check the container envs, I see that it is the defined container port and not the host mapped port. Is this a bug?

**Comment by dadgar** [comment]
@cchatfield Can you make an issue for that and post what you are seeing
