### ISSUE TITLE
Nomad Volumes somehow get into a state where they are perpetually locked.

### ISSUE THREAD

**Issue by dkowis** [hashicorp/nomad#10356]
### Nomad version

`Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)`

### Operating system and Environment details
Linux, Ubuntu 20.04

### Issue

I can somehow get into a state where nomad jobs lost their volumes and can never schedule again.
```
nomad-jobs/jobs main > nomad volume status                                                                            1⏎ [4d6ff6c]15.0.1system3.9.02.7.1
Container Storage Interface
ID        Name            Plugin ID  Schedulable  Access Mode
radarr-v  radarr-volume   truenas    true         single-node-writer
sonarr-v  sonarr-volume   truenas    true         single-node-writer
ttrss-ap  ttrss-app       truenas    true         single-node-writer
ttrss-da  ttrss-database  truenas    true         single-node-writer
unifi-co  unifi-config    truenas    true         single-node-writer
nomad-jobs/jobs main > nomad job plan sonarr.nomad
+ Job: "sonarr"
+ Task Group: "sonarr" (1 create)
  + Task: "sonarr" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "sonarr" (failed to place 1 allocation):
    * Constraint "CSI volume sonarr-volume has exhausted its available writer claims": 1 nodes excluded by filter

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 sonarr.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
```

### Reproduction steps

Just run a nomad cluster for a while, using the democratic-csi plugin, and have a service set up and running. Wait for it to freak out, and stop being scheduled. I have no idea why this happens, as other NFS things on that host work fine, so it's probably not a network blip. 

Either way, it's completely unrecoverable. Even after stopping and starting all jobs (including the democratic-csi ones). I had to completely power down the node that the allocation needed to be placed on. 

Then I could `nomad volume detach sonarr-v <nodeid>` and it actually removed that volume's write lock.

I know volumes are in beta, but it's pretty rough, heh.

#### Expected Result

I should have something scheduled.

#### Actual Result

as above, I cannot schedule that job any longer, and

**Comment by shoenig** [comment]
Hi @dkowis, thanks for reporting. This might take some sleuthing before we actually understand what's happening. When you say

> Wait for it to freak out, and stop being scheduled.

do you know why the task is crashing in the first place? Presumably the initial problem is not related to the dangling write lock, but might help understand the context. If it's unrelated, we should be able to reproduce the problem with any crashing task.

**Comment by dkowis** [comment]
Sadly, I don't know why the task is crashing. I'll come back to it, and find out that my app isn't running. And then try to do a stop/start. At that point, usually it's managed to lose track of the volumes, and is unable to schedule any more :(

I'll try real hard to figure this part out, see if I can't catch it happening again.
