### ISSUE TITLE
Nomad UI lacks namespace selection menu

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/nomad#10358]
### Nomad version
`Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)`

### Operating system and Environment details
Centos 7 

### Issue
According to the [Learn guide ](https://learn.hashicorp.com/tutorials/nomad/namespaces#nomad-ui) we should be able to select namespace in the Nomad UI drop-down menu.

I can't see that drop-down menu on my deployment:
![CleanShot 2021-04-12 at 11 16 10](https://user-images.githubusercontent.com/4280480/114379306-8f771f80-9b80-11eb-9851-f8807ec3d5f9.png)

#### Expected Result
A drop-down menu with namespace select to be available in the Nomad UI

**Comment by Oloremo** [comment]
Hm, seems like you need to do a UI refresh(F5) first time you add a namespace.

**Comment by shoenig** [comment]
Thanks for reporting @Oloremo, I'll make sure our UI team takes a look

**Comment by tgross** [comment]
The selector was moved in Nomad 1.1.0-beta and I've just verified its correct operation as part of testing for the release. With ACLs enabled, and authenticated to be able to read both `dev` and `prod` namespaces, but only a `dev` namespace exists:

<img width="337" alt="Screen Shot 2021-05-11 at 11 02 41 AM" src="https://user-images.githubusercontent.com/1409219/117838906-be001d00-b248-11eb-8828-73ef06c73d78.png">

After `nomad namespace apply prod`, the selector is populated without a refresh:

<img width="270" alt="Screen Shot 2021-05-11 at 11 03 27 AM" src="https://user-images.githubusercontent.com/1409219/117838920-c0627700-b248-11eb-95db-acde435c59bd.png">

Going to mark this issue as a 1.1.0 milestone item and close it out.
