### ISSUE TITLE
[feature request] Force(fast) job restart

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/nomad#10391]
### Proposal
It would be great if Nomad would have the ability to do a fast\force restart of the job.

### Use-cases
We need to do a quick restart during the incidents or on the development environment where we don't want to wait for a proper rolling update restart.

### Attempted Solutions
Currently, Nomad can restart job using the ~restart~ update stanza or alloc restart.

The problem with the update stanza is that I want to keep max_parallel small in the majority of the cases, like 1 to do rolling updates. If I'd change max_parallel to Job group count it will help but now I have my job with incorrect configuration and if I change it back - it will trigger restart one more time which is far from perfect.

With alloc restart it's just scary and hard to do programmatically. Seems like there is a lot of issues of restarting allocation with pre\post jobs(#9464 , #9841) and I'm uncertain how Consul Connect envoy side-car will handle that and if I need to do it in a specific order and how to get that order, etc, etc.

**Comment by schmichael** [comment]
Hi @Oloremo,

Thanks for the feedback. What would you expect the behavior of `nomad job restart` to be? Restarting all allocations simultaneously?

While that approach seems scriptable on top of existing APIs/commands, I do see how the bugs you link could cause issues. Please add a :+1: to each of them if you haven't already. We pay attention to Github reactions!

> The problem with the restart stanza ...

This makes me think what you want is a `nomad job run -fast foo.nomad` (or `-force`? or `-skip-deployment`?) to update a job and bypass the `update` stanza's deployment parameters?

**Comment by Oloremo** [comment]
>  bypass the update stanza's deployment parameters?

This.
We could have a job with 100 allocations and `max_parallel = 1` but there are cases when we may need to restart them ASAP.
