### ISSUE TITLE
Variable interpretation not working - what is the new interpretation to get the correct nomad_ip

### ISSUE THREAD

**Issue by lettrung99** [hashicorp/nomad#1039]
Hi,

I have question regarding NOMAD_IP.  In Nomad (v0.2.3), this come freely as an environment variable to the container.  Nomadv(v0.3.0) does not has this.  How do we get this?  Please advise.

on v0.3.0, we do this:
        env {
            NOMAD_IP = "${nomad.ip}"
        }

gives

$ env
NODE_VERSION=5.5.0
HOSTNAME=9fe465e33db8
NOMAD_TASK_DIR=/local
NPM_CONFIG_LOGLEVEL=info
user=node
LS_COLORS=
NOMAD_IP=${nomad.ip}
NOMAD_CPU_LIMIT=500
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/node
NOMAD_ALLOC_DIR=/alloc
NOMAD_MEMORY_LIMIT=256
SHLVL=1
HOME=/home/node
NOMAD_PORT_web=8080
_=/usr/bin/env

**Comment by diptanu** [comment]
@lettrung99 We have `NOMAD_ADDR_task_name` now instead of `NOMAD_IP` since we will support multiple IPs very soon, `NOMAD_IP` won't represent the right information. For example, if you run the `example` nomad job, you will see `NOMAD_ADDR_db=127.0.0.1:6379` as one of the environment variables.
