### ISSUE TITLE
Improve security of vault tokens on nomad servers, by allowing wrapped tokens @ nomad server startup.

### ISSUE THREAD

**Issue by csawyerYumaed** [hashicorp/nomad#10399]
### Proposal

On Nomad server startup, if you are integrated with vault, there are 2 ways to specify the vault token the server will use, via the ENV variable `VAULT_TOKEN` or in the config file via  setting the `token` config endpoint, per the [docs](https://www.nomadproject.io/docs/integrations/vault-integration#retrieving-the-token-role-based-token).

vault {
        enabled = true
        # vault token create -policy nomad-server -period 72h -orphan
        token = "TOKENHERE"
}

Both of these require an unwrapped vault token, which means either 1) the vault token is available via /proc or the vault token is available in the file system.

There are of course things you can do to mitigate this, like put the token in the file, start nomad, then edit the file and take the token back out.  You can do file permissions, etc.  There isn't really anything you can do about /proc leaking the ENV variables that I'm aware of.

But since all of the rest of vault uses wrapped tokens, it would be great if we could create a vault nomad-server token with:

`vault token create -wrap-ttl=5m -policy nomad-server -period 72h -orphan `

and put it in the ENV or config file and forget about it, and not need to worry about the FS or /proc being compromised and getting a nice juicy vault token.

This would improve the security of the nomad servers.

### Use-cases

Improve security of vault tokens on nomad servers by allowing wrapped tokens @ nomad server startup.

### Attempted Solutions

None, there have been 2 issues about this before, neither one really commented on, just closed. 
see: https://github.com/hashicorp/nomad/issues/3522 & https://github.com/hashicorp/nomad/issues/3473

I think in #3522, @dadgar just didn't understand what was being asked, and assumed they were talking about wrapping tokens between nomad server and nomad agents, which of course is already done.  I'm talking about the nomad server accepting wrapped tokens for server startup.

**Comment by notnoop** [comment]
Thanks @csawyerYumaed for the suggestion.  It would be great not to persist secrets to disk indeed. Extra care is needed, as the server may fail to start if the nomad server agent restarts on config updates, as the second unwrapping will fail unexpectedly. We may need to do some design work to improve usability.

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Vault tokens in the Nomad agent configuration. Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. Using Vault tokens in the Nomad configuration will be removed entirely in Nomad 1.9.
