### ISSUE TITLE
CNI service address_mode alloc wrong IP advertised to consul

### ISSUE THREAD

**Issue by archaron** [hashicorp/nomad#10395]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Ubuntu 18.04.5 LTS
Linux  5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Issue
I use the calico CNI plugin with nomad. It runs just fine, IPAM gives me good IP inside docker allocation. I can ping, I can reach service running inside the allocation.

```
#nomad exec 1420af94 ip addr | grep eth0
3: eth0@if167: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default 
    inet 100.127.236.106/32 brd 100.127.236.106 scope global eth0
```

But, when I try to register some service in consul, I have always HOST_IP instead of the real allocation IP address.

Allocation status shows me:
```
Allocation Addresses (mode = "cni/lan")
Label  Dynamic  Address
*http  yes      10.3.1.30:20767 -> 80
```

Consul service has registered  unhealthy service with HOST IP (10.3.1.30) instead of an allocation IP (100.127.236.106)

`_nomad-task-1420af94-147e-63f6-90c1-98d1a86d28ba-group-demo-demo-webapp-demo-http  => 10.3.1.30:80`

I've tried both "to", "static" port modes, but the IP still remains the same.

One time, when I removed anything inside the port definition, it reached working and healthy registered service with dynamic port.
I cannot repeat that anymore.

I cannot understand, why, allocation port mode is always "dynamic: yes", whenever statc=80 (or to=80) set or not.

Can anyone give me a working example with CNI-allocated IP and registered service with allocated IP instead of HOST IP?

### Config
```
job "demo-webapp" {
  datacenters = ["dc1"]
  type = "service"

  group "demo" {
    count = 1

    service {
      address_mode = "alloc"
      port = "http"

      tags = ["demo", "global"]
      meta {
        meta = "demo webapp"
      }

      check {
	name     = "demo-webapp-check"
        type     = "http"
        path     = "/"
        interval = "2s"
        timeout  = "2s"
	address_mode="alloc"
      }
    }

    network {
      mode = "cni/lan"
      port "http" {
       to = 80
      }
    }


    task "server" {

      resources {
          cpu    = 300 # MHz
          memory = 128 # MB
      }

      env {
        PORT    = "${NOMAD_PORT_http}"
        NODE_IP = "${NOMAD_IP_http}"
      }

      driver = "docker"

       config {
        image = "hashicorp/demo-webapp-lb-guide"
        ports = ["http"]
       }
    }
  }
```
### What is expected
Demo web app server running in CNI namespace with IP from the calico pool (100.127.236.64/26 in my example). 
Registered consul service with IP 100.127.236.xxx and port 80.

Nomad alloc status that says (is it wrong thought?):
```
Label  Dynamic  Address
*http    no      100.127.236.xxx:80
```

### What I get
Demo web app server running in CNI namespace with IP from the calico pool (100.127.236.64/26 in my example). 
Registered consul service (unhealthy of course) with IP 10.3.1.30 (HOST IP) and port 80

In port "http" { to: 80 } I have:
```
Allocation Addresses (mode = "cni/lan")
Label  Dynamic  Address
*http  yes      10.3.1.30:20767 -> 80
```

When I change it to port "http" { static: 80 } I have:
```
Allocation Addresses (mode = "cni/lan")
Label  Dynamic  Address
*http  yes      10.3.1.30:80

```
10.3.1.30 - is the HOST IP
Why is it dynamic? I have static in config!

**Comment by nickethier** [comment]
Hey @archaron 

Sorry you ran into this. I think #9895 fixes this if you’re able to test from master. Otherwise it will be in the upcoming 1.1 release.

**Comment by archaron** [comment]
Fixed by install from master sources. Now nomad registers CNI IPs in consul, just as expected.
Thank you!
