### ISSUE TITLE
RPC Connection Error again

### ISSUE THREAD

**Issue by bvanhou** [hashicorp/nomad#10394]
Hey there,
I am troubleshooting an error for my CircleCI client. I believe its an issue with Nomad Client version, however I am unable to figure this out.

### Nomad version
Output from `nomad version`

### Issue:
Nomad Service: 0.9.3
Nomad Client : 0.11.3

Nomad Client Job Logs: 
"duration":20009.289463,"level":"info","msg":"statsd metric","name":"grpc-call","tags":["result:failed","method:/protocol.EventProcessor/taskConfig"],"task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:15Z","type":"timing"}

{"error":"failed to fetch task config: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.251.6.227:8585: i/o timeout\"","level":"warning","msg":"error fetching config, retrying","task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:15Z"}

{"duration":0.054462,"level":"info","msg":"statsd metric","name":"grpc-call","tags":["result:failed","method:/protocol.EventProcessor/taskConfig"],"task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:15Z","type":"timing"}

{"error":"failed to fetch task config: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.251.6.227:8585: i/o timeout\"","level":"warning","msg":"error fetching config, retrying","task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:15Z"}

{"duration":19440.779845,"level":"info","msg":"statsd metric","name":"grpc-call","tags":["result:failed","method:/protocol.EventProcessor/taskConfig"],"task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:36Z","type":"timing"}

{"error":"failed to fetch task config: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.251.6.227:8585: i/o timeout\"","level":"warning","msg":"error fetching config, retrying","task-id":"6075d36de7fe163c7b022d6a-0-build","time":"2021-04-13T17:23:36Z"}

**Comment by notnoop** [comment]
Hi! From the logs, it seems that Nomad has scheduled and launched the service fine, but your service is failing to access the EventProcessor.  I'm afraid it's outside the scope of what we can help here, and I'd recommend reaching out to CircleCI SREs and engineers for debugging your customer setup.

Also, the versions are troublesome. We primarily support Nomad clusters running in the same versions, and recommend a mixed cluster during a cluster upgrade. Running a mixed cluster is troublesome and may lead to unexpected behaviors, specially when the versions aren't close together.

That being said, my hunch seeing the logs is that it's a network security issue where nomad clients workloads are blocked from accessing port 8585 on the CircleCI Server, either through cloud SG or iptables rules that drop packets and manifest as connection timeouts.
