### ISSUE TITLE
Warn when using a client that doesn't match the server version

### ISSUE THREAD

**Issue by g0t4** [hashicorp/nomad#1040]
A few times I've upgrade my server and nodes but forgot to update my local computer's version of nomad. It seems that older versions can still send commands but every once in a while I get pooched. For example, I was using 0.3.0 locally and 0.3.1 on the server, I was trying to test a job with artifacts. No errors came my way, turns out the 0.3.0 client was not passing along the artifact config.

Would it make sense to print a warning message when using a client that doesn't match the server version?

**Comment by drewgonzales360** [comment]
@nickethier I'm looking to get involved with this project. I just tried running a `nomad agent -dev` then downloaded an older nomad to test if this is still an issue. I didn't see any warnings. I'll take a stab at this and ask any questions if I have them :smile:

**Comment by nickethier** [comment]
Awesome @drewgonzales360! Do let us know if you have any questions. I or someone from the Nomad team will be happy to answer.

**Comment by drewgonzales360** [comment]
:wave:  @nickethier, I could some early feedback on my PR. Can you take a :eyes: and let me know if I'm heading the right direction?

**Comment by danishprakash** [comment]
Is this still being worked upon?

**Comment by tgross** [comment]
@danishprakash we've got a PR open https://github.com/hashicorp/nomad/pull/9159 which has iterated on this idea a bit by exposing the server version in the `version` command, so that we're not spamming warnings for operators with slightly mismatched versions.

**Comment by danishprakash** [comment]
My bad @tgross, I just totally missed the linked PR, thanks for the clarification.

**Comment by tgross** [comment]
#9159 has been merged and will ship in the next regular version of Nomad (likely Nomad 1.4.3).
