### ISSUE TITLE
Resources exhausted message misreporting information

### ISSUE THREAD

**Issue by pearkes** [hashicorp/nomad#1041]
### Nomad version

45114d9abdad2e698eb2830231bf77a095e47962

### Operating system and Environment details

3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Issue

With only disk exhausted, an allocation failed to allocate with the falling output:

```
==> Status
Allocation "712ec504" status "failed" (0/12 nodes filtered)
  * Resources exhausted on 12 nodes
  * Class "linux-64bit" exhausted on 12 nodes
  * Dimension "cpu exhausted" exhausted on 4 nodes
  * Dimension "disk exhausted" exhausted on 4 nodes
  * Dimension "memory exhausted" exhausted on 4 nodes
```

It should have only shown disk here.

### Reproduction steps

Request resources beyond the available for disk in a task and run it.

**Comment by dadgar** [comment]
@pearkes Tried to reproduce it and could not? Are you positive that CPU and memory were not exhausted as well?

**Comment by dadgar** [comment]
Closing as this is not reproducible
