### ISSUE TITLE
Option to spread multiple *jobs* across multiple hosts

### ISSUE THREAD

**Issue by sbrl** [hashicorp/nomad#10421]
### Proposal
Add a new option to control the default scheduling algorithm of jobs. This is distinct to the `spread` operator, in that it would affect the placement of jobs, rather than multiple instances of the same job. 

### Use-cases
As a Nomad cluster administrator, I want to ensure that the utilisation each host in my bare-metal cluster is about the same. I have multiple jobs that all have **1 instance each**. The spread operator, while useful, only appears to affect **multiple instances of the same job**.

### Attempted Solutions
I have tried using the `spread` operator in all my jobs like so:

```
# Spread allocations over all nodes
spread {
	attribute =  "${node.unique.name}"
}
```

...but it does not have an effect because I typically only have a 1 allocation per job:

![image](https://user-images.githubusercontent.com/9929737/115577138-0ec0cd80-a2bc-11eb-86da-4c949a264cf2.png)

I have also tried search the documentation for an alternative solution, but it does not appear that the scheduler can be convinced to do what I want here.

I also tried restarting all my jobs too with the `spread` operator added, but it didn't have an effect either.

**Comment by DingoEatingFuzz** [comment]
Hi @sbrl, it is possible to set `spread` at the cluster level, but perhaps the docs are a bit hidden: https://www.nomadproject.io/docs/configuration/server#configuring-scheduler-config

**Comment by sbrl** [comment]
Ah, thanks so much @DingoEatingFuzz! That's very useful. I've enabled it, and it does appear to help somewhat:

![image](https://user-images.githubusercontent.com/9929737/115802039-06f54c00-a3d6-11eb-9eb1-dd58b790cddd.png)

...though there does appear to be an unused node there, which I'd rather avoid, but I suppose this could just be random chance.

I'll close this issue for now, but I'll keep an eye on it and if I encounter further issues I'll re-open and we investigate further.

**Comment by sbrl** [comment]
Hrm, I still seem to be having issues here, @DingoEatingFuzz - I've kept my cluster under observation and I've since restarted the entire cluster, but I'm not seeing much spreading going on:

![Screenshot 2021-05-16 at 02-07-42 Cluster Topology - Nomad](https://user-images.githubusercontent.com/9929737/118382296-dd51ce00-b5eb-11eb-90b9-0977aa52c2b8.png)

I've also verified that all my nomad servers have that option in their config files:

```hcl

server {
	enabled = true
	# We've got 3 servers in the cluster at the moment
	bootstrap_expect = 3
	default_scheduler_config {
		# Use the spread scheduler for jobs
		# Ref https://github.com/hashicorp/nomad/issues/10421#issuecomment-824200934
		scheduler_algorithm = "spread"
	}
}
```

Is there something I'm missing?

**Comment by nickethier** [comment]
Hey @sbrl I think this is still working as expected.

The high level description of what the scheduling algorithm does for node selection is first iterate through a randomized list of nodes until its found 2 that can fit the workload (constraints match, resources fit, etc). It then scores those two nodes and picks the node with the better score. The spread/binpack algorithm affects this score.

This means on smaller sample sizes its entirely possible to observe non uniform spreading due to the randomization.

One thing you can check is that the scheduler is reporting the scheduler_algorithm correctly in the output of the [operator/scheduler api call](https://www.nomadproject.io/api-docs/operator/scheduler)

**Comment by sbrl** [comment]
Ah, thanks for the advice there @nickethier. I tried that HTTP api call, but it looks like it's still using the binpacking scheduler, despite the fact that I've told it to use a different scheduler:

```json 
{
  "SchedulerConfig": {
    "SchedulerAlgorithm": "binpack",
    "PreemptionConfig": {
      "SystemSchedulerEnabled": true,
      "BatchSchedulerEnabled": false,
      "ServiceSchedulerEnabled": false
    },
    "CreateIndex": 5,
    "ModifyIndex": 5
  },
  "Index": 5,
  "LastContact": 0,
  "KnownLeader": true
}
```

**Comment by nickethier** [comment]
I think once the server is bootstrapped you may need to update the configuration through the [API](https://www.nomadproject.io/api-docs/operator/scheduler#update-scheduler-configuration).

Try this:
```
curl -XPUT localhost:4646/v1/operator/scheduler/configuration -d '{ "SchedulerAlgorithm": "spread" }'
```

**Comment by sbrl** [comment]
@nickethier Thanks! That seems to have updated it:

```
$ curl http://nomad.service.mooncarrot.space:4646/v1/operator/scheduler/configuration -sS | jq .
{
  "SchedulerConfig": {
    "SchedulerAlgorithm": "spread",
    "PreemptionConfig": {
      "SystemSchedulerEnabled": false,
      "BatchSchedulerEnabled": false,
      "ServiceSchedulerEnabled": false
    },
    "CreateIndex": 5,
    "ModifyIndex": 614864
  },
  "Index": 614864,
  "LastContact": 0,
  "KnownLeader": true
}
```

The topology is less than perfect though after a full cluster reboot:

![Selection_2021-06-07_21:46:04_001_3a0cdcb](https://user-images.githubusercontent.com/9929737/121085904-64a0f480-c7da-11eb-89be-467060a5aa52.png)

....but it's at least better than before. Closing again for now, but there's more work to be done in this area I think - for example checking more than the first 2 hosts and picking the one with the least amount of stuff running on it
