### ISSUE TITLE
raw_exec driver is failing with: Wait returned exit code 141, signal 13, and error <nil>

### ISSUE THREAD

**Issue by mgenov** [hashicorp/nomad#1042]
### Nomad version
Nomad v0.3.2-dev ('a1996403081101ab952de12b7894a0f2b1716b8f')
Nomad v0.3.1

### Operating system and Environment details
Linux

### Issue
After app is deployed and some traffic goes through it, it is terminated and nomad is restarting it after few minutes. If app is running normally everything is working like a charm. 

```
2016/04/06 14:10:22 [INFO] client: task "tcpproxy-test" for alloc "ff8c8915-08e6-d981-d4d1-c949110e03ed" failed: Wait returned exit code 141, signal 13, and error <nil>
2016/04/06 14:10:22 [INFO] client: Restarting task "tcpproxy-test" for alloc "ff8c8915-08e6-d981-d4d1-c949110e03ed" in 16.672584629s
2016/04/06 14:10:22 [DEBUG] client: updated allocations at index 12378 (pulled 0) (filtered 2)
2016/04/06 14:10:22 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 2)
```

Note that logs stderr and stdout are not containing any crash information. 

### Job
```
job "tcpproxy-test" {
    region = "xxx"
    datacenters = ["yyy"]
    type = "service"
    priority = 50

    update {
        # Stagger updates every 10 seconds
        stagger = "10s"

        # Update a single task at a time
        max_parallel = 1
    }

    group "tcpproxy-test" {
        count = 1
        # Define a task to run
        task "tcpproxy-test" {
            driver = "raw_exec"
            
            config {
                command = "tcpproxy"
                args = ["-h", ":8885", "-l",":2090", "-f", "192.168.0.4:8887"]
            }

            artifact {
                source = "https://someurltotcpproxy"
            }
    
            resources {
                cpu = 500 # 500 Mhz
                memory = 128
                disk = 100
            }
            
            logs {
                max_files = 5
                max_file_size = 10
            }
        }
    }
}
```
Related to #955

**Comment by diptanu** [comment]
@mgenov I have added some more logs now, can you please run your task and tell me what you see in the output of the executor please?

The executor output is located in the task directory. So if you an alloc id: `2840a909` and the task name is `redis`- you should be able to see the executor logs if you do `nomad fs ls 2840a909 redis` and then simply use the `nomad fs cat` command to get the contents of the file.

**Comment by diptanu** [comment]
@mgenov This is fixed now, and will go out with Nomad 0.3.2

**Comment by mgenov** [comment]
Thanks.

**Comment by mgenov** [comment]
btw, it looks that fix is working as expected.
