### ISSUE TITLE
A periodic job is not marked as completed or dead even when all tasks are completed.

### ISSUE THREAD

**Issue by preichenberger** [hashicorp/nomad#1045]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

Nomad v0.3.2-dev ('52edfe3a4e0ae76447c6c69198d7fa955beb748c+CHANGES')

### Operating system and Environment details
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

### Issue

Periodic job's allocation tasks complete(in my case two) and say , but job is still marked as running. Other evaluations are blocked, I believe bacause of this.

Edited output of: test/periodic-1459980000

ID          = test/periodic-1459980000
Name        = test/periodic-1459980000
Type        = batch
Priority    = 50
Datacenters = ops 
Status      = running
Periodic    = false

==> Evaluations
ID        Priority  Triggered By  Status
b3b9c404  50        periodic-job  complete

==> Allocations
ID        Eval ID   Node ID   Task Group                                                                                                                   Desired  Status
a1d5392c  b3b9c404  d5b0db8c  test-backup        run      complete
e60d9a81  b3b9c404  0ce11ae2  test-purge  run      complete

### Reproduction steps

Create a periodic job with tasks, let the tasks complete and see the output.

**Comment by dadgar** [comment]
Fixed by https://github.com/hashicorp/nomad/commit/8039720b10096664870a17bd535a914526db7fbc
