### ISSUE TITLE
Update Task Plugin API docs to reference RemoteTasks

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#10469]
As per https://github.com/hashicorp/nomad/pull/10248#discussion_r622174778 update Task Plugin API docs about `RemoteTasks`.

**Comment by tgross** [comment]
@schmichael should this issue also have been closed by https://www.nomadproject.io/docs/internals/plugins/task-drivers#remote-task-drivershttps://github.com/hashicorp/nomad/pull/10550 ?

**Comment by schmichael** [comment]
Yup! Thanks @tgross
