### ISSUE TITLE
env stanza yields unexpected results with HCL2 variables in dynamic blocks

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#10461]
### Nomad version
Output from `Nomad v1.0.4+ent`

I have a job that utilizes dynamic blocks - in that job I have an `env` stanza like this : 

```
env {
  ... 
  VCENTER_URL  = group.value.vcenter_url
  ...
}
```
Running `nomad run -var-file=staging.vars -output job.nomad | grep VCENTER_URL` on my local machine yields the **correct** results : 

```
$ nomad run -var-file=staging.vars -output job.nomad | grep VCENTER_URL
"VCENTER_URL": "https://foo.bar.baz/sdk",
```

However when the job is placed on a nomad client in our cluster the resulting environment variable is **wrong** : 

```
$ nomad alloc exec <alloc-id> /bin/bash
# env | grep VCENTER_URL
VCENTER_URL=${group.value.vcenter_url}
```

I have also tried :point_down: but it yielded the same (wrong) result.

```
env {
  ... 
  VCENTER_URL  = format("%s", group.value.vcenter_url)
  ...
}
```

All machines run nomad `v1.0.4+ent`.

**However** ... changing the `env` stanza to a `template` stanza yields the **correct** result : 

```
template {
  data = <<EOH
...
VCENTER_URL  = "${group.value.vcenter_url}"
...
EOH
  destination = "secrets/file.env"
  env         = true
}
```

```
$ nomad alloc exec <alloc-id> /bin/bash
# env | grep VCENTER_URL
VCENTER_URL=https://foo.bar.baz/sdk
```

**Comment by tgross** [comment]
Hi @henrikjohansen!

Is the version of Nomad you're using as their CLI the exact same version as the one in your cluster? The rendering of all variables happens in the CLI and then the resulting jobspec is being sent (as JSON) to the server. I'm wondering if there's a difference in the server that's resulting in the two different behaviors you're seeing.

**Comment by henrikjohansen** [comment]
Hey @tgross. 

Yes - the version of the CLI I am using is identical to the version the rest of the cluster is using : 

```
$ nomad server members | awk {'print $7'} 
Build
1.0.4+ent
1.0.4+ent
1.0.4+ent
```

And my local machine : 

```
$ nomad version
Nomad v1.0.4+ent

```

The output of `nomad run -var-file=staging.vars -output job.nomad | grep VCENTER_URL` looks correct so I have no real idea on why I am getting a wrong interpolation on a client node (which btw also runs 1.0.4+ent).

**Comment by tgross** [comment]
Hi @henrikjohansen! I've tried to replicate what you're seeing and I'm having some trouble. Here's a jobspec I've tried:

<details><summary>jobspec</summary>

```hcl
locals {
  hellos = ["hello", "world"]
}

job "example" {
  datacenters = ["dc1"]

  dynamic "group" {

    for_each = local.hellos
    labels   = ["web-${group.value}"]

    content {

      network {
        mode = "bridge"
        port "www" {
          to = 8001
        }
      }

      task "http" {

        driver = "docker"

        env {
          MYVARIABLE = group.value
        }

        config {
          image   = "busybox:1"
          command = "httpd"
          args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
          ports   = ["www"]
        }

        template {
          data        = "<html>${group.value}</html>"
          destination = "local/index.html"
        }

        resources {
          cpu    = 128
          memory = 128
        }
      }
    }
  }

}

```

</details>

When I run that, I get the following:

```
$ nomad job run ./example.nomad
==> Monitoring evaluation "8ef1b857"
    Evaluation triggered by job "example"
==> Monitoring evaluation "8ef1b857"
    Evaluation within deployment: "c3591c3c"
    Allocation "22a4195b" created: node "aac30ef3", group "web-hello"
    Allocation "6fb4c8b4" created: node "aac30ef3", group "web-world"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "8ef1b857" finished with status "complete"

$ nomad alloc exec 22a env | grep MYVARIABLE
MYVARIABLE=hello
```

Can you provide a redacted version of the jobspec that you're trying to submit? Maybe there's something I'm missing in reproduction. Thanks!

**Comment by tgross** [comment]
Without a reproduction I'm going to close this out. Feel free to reopen if you have more information.
