### ISSUE TITLE
Allocation stats API includes resources for dead pre-start tasks

### ISSUE THREAD

**Issue by jches** [hashicorp/nomad#10477]
### Nomad version

v1.0.4

### Operating system and Environment details

Debian 10 (buster)

### Issue

I'm running a rails app using nomad with the docker driver. A prestart task runs rails migrations before the main task for rails starts.

In the UI, the resource utilization graphs show much higher CPU and memory utilization than the either of the main tasks are actually using, because they are including resources used by the prestart `migrations` task, which exited successfully and is no longer running.

Here is a snippet from the CLI illustrating the same:

```
> nomad status $ALLOC_ID
Task "migrations" (prestart) is "dead"
Task Resources
CPU           Memory           Disk     Addresses
3501/100 MHz  197 MiB/300 MiB  300 MiB

Task "nginx" is "running"
Task Resources
CPU        Memory           Disk     Addresses
0/100 MHz  2.3 MiB/300 MiB  300 MiB

Task "rails" is "running"
Task Resources
CPU         Memory           Disk     Addresses
0/1250 MHz  513 MiB/2.0 GiB  300 MiB
```

#### Expected Result

Utilization graphs only include running tasks.

#### Actual Result

Even though both running tasks are essentially idle, the CPU graphs show 240% utilization

**Comment by shoenig** [comment]
Thanks for reporting @jches ! This is actually a known issue (https://github.com/hashicorp/nomad/issues/9725), which we'll work towards getting prioritized. If you don't mind adding a +1 to that original issue, that really helps us get an idea of which bugs need attention. Thanks!

**Comment by jches** [comment]
Cheers @shoenig that does indeed look like the same bug I'm seeing here. Thanks for the redirect!
