### ISSUE TITLE
Nomad doesn't support volume mounts when using Docker Engine installed by Snap store

### ISSUE THREAD

**Issue by luizhfff** [hashicorp/nomad#10473]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

### Issue
Nomad doesn't support volume mounts when using Docker Engine installed through the Snap store

### Reproduction steps
1) Install docker through the Snap store in the node/client
2) Enable volumes and privileged in the node/client Nomad configuration: 
 - client >> plugin "docker" >> 
   - docker.volumes.enabled: true
   - docker.privileged.enabled = true
3) Run a job using the Docker driver and try to mount volumes and use privileged

#### Expected Result
Job successfully executed and volumes mounted properly

#### Actual Result
Job failed and Error message when running ```nomad alloc status <allocId>``` saying Volumes Not Enabled

#### Important
The same job can be executed to a node using the official Docker Engine (https://docs.docker.com/engine/install/ubuntu/)

### Job file (if appropriate)
```
job "jobname" {
  datacenters = ["dcname"]
  group "groupname" {
    constraint {
      attribute = "${node.unique.name}"
      value     = "nodename"
    }
    count = 1
    restart {
      attempts = 5
      delay = "15s"
      mode = "fail"
    }
    update {
      max_parallel     = 1
      min_healthy_time = "30s"
      healthy_deadline = "1m"
    }
    task "taskname" {
      driver = "docker"
      resources {
        memory = 6000
      }
      env {
        DOCKER_USER = "dockeruser"
      }
      template {
        data = <<EOF
{{ with secret "path/SECRETNAME" }}
SECRETNAME="{{ .Data.key }}"
{{ end }}
EOF
        destination = "secrets/vault.env"
        env         = true
      }
      vault {
        policies      = ["nomad-server"]
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
      config {
        image = "imagename"
        network_mode = "host"
        dns_search_domains = ["8.8.8.8" , "4.2.2.4"]
        privileged = true
        devices = [
          {
            host_path = "/dev/dri"
            container_path = "/dev/dri"
          }
        ]
        auth {
          username = "user"
          password = "pass"
        }
        volumes = [
          "/home/user/.ssh:/root/.ssh",
          "/etc/group:/etc/group:ro",
          "/etc/passwd:/etc/passwd:ro",
          "/etc/shadow:/etc/shadow:ro",
          "/etc/sudoers.d:/etc/sudoers.d:ro",
          "/dev:/dev",
          "/etc/timezone:/etc/timezone:ro",
          "/etc/localtime:/etc/localtime:ro",
          "./dev_entrypoint.bash:/root/dev_entrypoint.bash:ro"
        ]
        pid_mode = "host"
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @luizhfff!

When you install Docker via snap, the snap restricts what can be done with Docker. If I look at [snapcraft](https://snapcraft.io/docker) I see the following line:

> This build can only access files in the home directory. 

So I suspect that it's the snap installation that's causing the problem here. We've seen this cause problems for a few other areas having to do with volumes or bind-mounts like https://github.com/hashicorp/nomad/issues/9350 or https://github.com/hashicorp/nomad/issues/8197. 

We might be able to provide some more information if you could let us know what the specific error message you received. The "volumes are not enabled" usually has a bit more information that can help here.

**Comment by tgross** [comment]
I'm going to close this out. Feel free to reopen if you have more information.
