### ISSUE TITLE
Rotate log files at newline boundaries

### ISSUE THREAD

**Issue by sean-** [hashicorp/nomad#1048]
### Issue

See comment: https://github.com/hashicorp/nomad/pull/1047#discussion_r58810636 .  The following needs to happen in `Write()` when the file size has been exhausted.

> This should scan backwards through the buffer for a \n and write/flush everything before that. Whatever comes after that last \n should be moved to the beginning of the buffer and written out on the next write (as long as the line length is less than the buffer length, in which case you need to truncate). This only needs to happen on file rotation, not on write.

**Comment by sean-** [comment]
@diptanu did #1047 fix this issue?  Can this issue be closed?

**Comment by cyrilgdn** [comment]
Any news? 
Our applications logs are in json format and parsed by Logstash but Nomad truncate lines when rotating log files. So these json lines are invalid...

**Comment by a86c6f7964** [comment]
I have the same problem as @cyrilgdn

**Comment by cyrilgdn** [comment]
@diptanu @sean- This issue seems to not be fixed currently. Is it planned for some version?

Thanks!

**Comment by schmichael** [comment]
We don't have it on our roadmap yet, but if someone wants to attempt a PR @sean-'s linked comment covers the desired behavior.

**Comment by lorenzo** [comment]
We are experiencing this as a problem because we log in json format. Is this still out of scope?

**Comment by a86c6f7964** [comment]
Cc: @preetapan
