### ISSUE TITLE
docker-credential-ecr-login returns 'credentials not found in native keychain'

### ISSUE THREAD

**Issue by thijs** [hashicorp/nomad#10480]
### Nomad version
Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)

### Operating system and Environment details
Running in AWS on a Debian based system:
Distributor ID: Debian
Description:    Devuan GNU/Linux 3 (beowulf)
Release:        3
Codename:       beowulf

### Issue
Starting my job fails because docker fails to pull the image from AWS ECR. With some scripting fudgery I finally managed to figure out that docker-credential-ecr-login returns 'credentials not found in native keychain'

### Reproduction steps
Setup nomad and docker as described in the docs.

* in my client.hcl:
```
plugin "docker" {
  config {
    auth {
      config = "/etc/docker-auth.json"
    }
  }
}
```

* /etc/docker-auth.json:
```
{
    "credHelpers": {
        "<id>.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
    }
}
```

#### Expected Result
Nomad has docker pull the image and start the job.

#### Actual Result
Job fails with errors in the log:
```
    2021-04-30T12:22:28.592Z [ERROR] client.alloc_runner.task_runner: running driver failed: 
alloc_id=802ab46c-4672-433c-65ca-cee09a8918cc task=taskname 
error="Failed to find docker auth for 
repo "<id>.dkr.ecr.us-east-1.amazonaws.com/<name>": 
docker-credential-ecr-login with input
 "<id>.dkr.ecr.us-east-1.amazonaws.com/<name>" failed with stderr: exit status 1"
```

### Figuring out the real issue
As one can see from the error log message, that isn't really helpful. So I changed the setup around a little (based on #5527) to run through a helper script.

* /etc/docker-auth.json changed to:
```
{
    "credHelpers": {
        "<id>.dkr.ecr.us-east-1.amazonaws.com": "ecr-custom"
    }
}
```

* added /usr/local/bin/docker-credential-ecr-custom:
```
#!/bin/bash                                                                                                      

env > /tmp/ecrinfo                                                                                               
echo "params: $@" > /tmp/inputs                                                                                  
STDIN=$(cat)                                                                                                     
echo "stdin: ${STDIN}" >> /tmp/inputs                                                                            
                                                                                                                 
RES=$(echo $STDIN | /usr/bin/docker-credential-ecr-login $@)                                                     
                                                                                                                 
echo "res: $RES" >> /tmp/output                                                                                  
                                                                                                                 
echo $RES
```

This netted me the real issue, which was `credentials not found in native keychain`.

### Problem solved, although...

So while I was writing up this issue, I had a thought. The error message kinda triggered me, as I'm running in AWS with policies set on the instance to have access to ECR. So a `native keychain` shouldn't be needed. So maybe the issue is connectivity. I looked at the dump of the environment produced with the custom script and compared that with the env I get on the command line (where running `echo <ECR url> | docker-credential-ecr-login get` actually gives the correct answer). Missing from the env were the settings for the http and https proxies.

And yes, adding those in the custom script made everything work. So the issue was that when run from nomad some env variables were missing.

I decided to post this issue even though I've solved it, for others that might run into the same problem.

### Room for improvement
One thing that can certainly be improved (and I'm not sure if that is for nomad to solve or awslabs who create the helper) is error logging and messages. It took me way too much work just to find out *what* the actual problem was. Not a nice experience and quite a few hours wasted.

**Comment by tgross** [comment]
Hi @thijs! Thanks for the very thorough breakdown of the problem!

> So the issue was that when run from nomad some env variables were missing.

This sounds like it could be worth investigating more. The Docker `ecr-login` doesn't have access to the environment of the job, because the `docker pull` is happening in the context of the Nomad client and not the restricted environment of the allocation. (Or in other words, `ecr-login` can't use the job's environment because the allocation's container doesn't exist yet!) Are you setting those proxy environment variables in the jobspec, or in the Nomad client's systemd unit file?

In any case, I'm in definite agreement that the docs and error messages could be better here.

**Comment by thijs** [comment]
I did what the poster of #5527 did, namely add the needed env vars into `/etc/default/nomad` so that they are picked up by Nomad on startup.

**Comment by tgross** [comment]
Thanks @thijs. I took a look at the code that's responsible for handling those errors in [`drivers/docker/utils.go`](https://github.com/hashicorp/nomad/blob/v1.0.4/drivers/docker/utils.go#L157-L165) and it looks like we could have been doing a better job of surfacing the stderr from the helper here. I've opened https://github.com/hashicorp/nomad/pull/10496 to fix that.
