### ISSUE TITLE
[question]Why need LimitIterator for avoiding scanning *every* possible node

### ISSUE THREAD

**Issue by luxuan** [hashicorp/nomad#1049]
The source code at line 105 in scheduler/stack.go:
```
	// Apply a limit function. This is to avoid scanning *every* possible node.
	s.limit = NewLimitIterator(ctx, s.jobAntiAff, 2)

	// Select the node with the maximum score for placement
	s.maxScore = NewMaxScoreIterator(ctx, s.limit)
```
Supposing the score of nodes are 1, 2, 3, 4, 5...., it means the LimitIterator will  limit the length of searching array to 2, and the MaxScoreIterator will find the best node is node with 2 score? I'm not sure my understanding is corrent?
And sometime, our strategy wants the node with best score to be selected at every scheduling, how I can do?

**Comment by dadgar** [comment]
@luxuan This is for performance reasons when evaluating batch jobs. If you look here the limit is different when running service jobs: https://github.com/hashicorp/nomad/blob/23fc2f89c1c772f358114a4dc75bf8bee873a982/scheduler/stack.go#L120-L132

If you want a more theoretical understanding of why we choose to evaluate two nodes, please see the power of two discussion here: http://www.eecs.berkeley.edu/~keo/publications/sosp13-final17.pdf
