### ISSUE TITLE
Batch jobs scheduled multiple times when node goes down, regardless if drained or just stopped

### ISSUE THREAD

**Issue by g0t4** [hashicorp/nomad#1050]
### Nomad version
Nomad v0.3.1

### Operating system and Environment details
centos 7 3.10.0-327.10.1.el7.x86_64
Docker version 1.10.3, build 20f81dd

### Issue
I have batch jobs with 50 tasks. If i take a node down while it is processing work and then bring a new node up, the work from the node that went down tends to be run multiple times, like up to 50 times, seemingly endlessly. I have to stop the job to get it to stop scheduling new allocations, even as the previous runs complete successfully, that doesn't stop Nomad from continuing to schedule new allocations.

I ran into this issue both by just shutting down a node, and by draining a node. So this seems like an issue in either case.

Is something going wrong with evaluations if a node goes down? 

Shouldn't we be able to lose a node and have the processing eventually move to another machine?

I don't have count set on the tasks, so I don't know why nomad would run multiple occurrences.

### Reproduction steps

Launch a batch job with work running on multiple nodes. Take one node down, bring up a new node in its place. Might not need to bring up a new node, that's just something auto scaling is doing in my situation.

**Comment by g0t4** [comment]
A small discussion was already had here https://groups.google.com/forum/#!searchin/nomad-tool/multiple/nomad-tool/97IHLdr4FX8/c1ujs8DXBgAJ

**Comment by dadgar** [comment]
@g0t4 Could you please share the Nomad server logs of this happening

**Comment by g0t4** [comment]
I was able to reproduce with a generic batch job composed of sleeps, attached is the job file
[repro.hcl.txt](https://github.com/hashicorp/nomad/files/214130/repro.hcl.txt)

Here's a video explaining the steps to reproduce: https://youtu.be/Pm0nQtqQlWk

Hope this helps, let me know if you want anything else. The video includes a dump of the server logs in that example if you want to see those without trying the repro on your end.

**Comment by dadgar** [comment]
@g0t4 just watched the video. That does look like a nasty bug! I will pull down that file tomorrow and try to do the repro. I think one of the differences when I was trying to reproduce it earlier today was that I had a task group with one task and had the count set to ~20, whereas you have each task separately defined.

**Comment by g0t4** [comment]
Glad the video helped! I figured that was easier to explain what was going
on :)

Let me know if I can help with anything else, I'd be happy to test things
when you have updates.

**Comment by dadgar** [comment]
Hey Wes,

Do you want to try this branch and make sure the fix works:
https://github.com/hashicorp/nomad/pull/1086

Thanks,
Alex

**Comment by g0t4** [comment]
Will do, thanks!

**Comment by g0t4** [comment]
Works with my mock job file that I sent you, if I get a chance this week
I'll try to swap this into my test cluster and put real work against it.
How stable is this branch?

**Comment by g0t4** [comment]
Thanks a bunch for fixing this so quickly!

**Comment by dadgar** [comment]
@g0t4 thanks for testing that! I would just wait for 0.3.2-RC which should be out soon!

**Comment by g0t4** [comment]
Fantastic, looking forward to it!
