### ISSUE TITLE
Docs suggest an unsupported high-latency setup

### ISSUE THREAD

**Issue by MikeN123** [hashicorp/nomad#10515]
As requested by @tgross a new issue, which is basically reopening #5697.

The reference architecture seems to suggest you can have 1 cluster/region spanning the whole of the US. As the same time this seems to be an unsupported scenario due to the high latency. See https://learn.hashicorp.com/tutorials/nomad/production-reference-architecture-vm-with-consul

This is very confusing when looking at Nomad for the first time and trying to grasp the relationship between regions and data centers.

----------

It seems this is still in the docs:

> For example, a US Region can include datacenters us-east-1 and us-west-2

versus

> Nomad servers are expected to be able to communicate in high bandwidth, low latency network environments and have below 10 millisecond latencies between cluster members

I really can't see how that is compatible with each other and why this ticket was closed?

_Originally posted by @MikeN123 in https://github.com/hashicorp/nomad/issues/5697#issuecomment-832802618_

**Comment by MikeN123** [comment]
Same on the architecture page at https://www.nomadproject.io/docs/internals/architecture

> For example, you may have a US region with the us-east-1 and us-west-1 datacenters, connected to the EU region with the eu-fr-1 and eu-uk-1 datacenters.

Although FR-UK may just fit in the 10ms maximum latency.

**Comment by tgross** [comment]
Hi @MikeN123! The bit that might be confusing here is that a Nomad `datacenter` is not the same as a Nomad `region`. The Nomad servers within a region need to be close together, whereas the clients (which can be within any `datacenter`) can be fairly far away. 

My colleague @shoenig has opened a PR #10532 for fixes to nomadproject.io with that clarification. Once that gets merged I'll get a fix in to link from that Learn guide to the much better description of `region` and `datacenter` that he's written.

**Comment by tgross** [comment]
Leaving a note to myself that we need a push to `stable-website` before I can open the Learn PR so that we can have the link to the new anchors that we added in https://github.com/hashicorp/nomad/pull/10618

**Comment by tgross** [comment]
I've merged https://github.com/hashicorp/learn/pull/3500 and that'll get published automatically.
