### ISSUE TITLE
UI Exec not working across region

### ISSUE THREAD

**Issue by legege** [hashicorp/nomad#10538]
### Nomad version
Nomad v1.1.0-beta1 (099d2c222208b04878a5528143da0a80b9666f0a)

### Issue

When trying to use Exec for an allocation in another region than the server being used for the UI, a `Connection closed` error is displayed.

### Reproduction steps

1. Setup two Nomad clusters with multi-region configured: call them region A and B
2. Schedule a job in region B
3. Open a browser pointing to UI on a server in region A
4. Open an exec UI for a task allocation in region B.

#### Expected Result

Exec UI should give you a prompt in the task.

```
$ nomad alloc exec -i -t -task main 5d4a58ad /bin/sh
#
```

#### Actual Result

```
$ nomad alloc exec -i -t -task main 5d4a58ad /bin/sh

The connection has closed.
```

### Nomad Server logs

On the region A server:
```
May 07 07:52:05 nomad2.dc1.example.com nomad[2950757]:     2021-05-07T07:52:05.442-0400 [DEBUG] http: request failed: method=GET path=/v1/client/allocation/5d4a58ad-5715-f23d-e43c-029f20079a39/exec?task=main&tty=true&ws_handshake=true&command=%5B%22%2Fbin%2Fsh%22%5D error="Unknown allocation "5d4a58ad-5715-f23d-e43c-029f20079a39"" code=404
```

**Comment by backspace** [comment]
Thanks for letting us know about this! There’s a minor problem with the PR but it’s a good start, I’m looking into this more deeply, but I appreciate the notice of the bug.
