### ISSUE TITLE
Docs: omitting update block seems to enable rolling updates

### ISSUE THREAD

**Issue by MikeN123** [hashicorp/nomad#10542]
### Nomad version

Nomad 1.0.4

### Issue

The docs suggest that omitting an `update` block will disable rolling updates, in two places:

https://www.nomadproject.io/docs/job-specification/job
> Specifies the task's update strategy. When omitted, rolling updates are disabled.

https://www.nomadproject.io/docs/job-specification/update
> If omitted, rolling updates and canaries are disabled.

But if I upload a job without `update` block, the web interface shows the following in the definition:

```
      "Update": {
        "Stagger": 30000000000,
        "MaxParallel": 1,
        "HealthCheck": "checks",
        "MinHealthyTime": 10000000000,
        "HealthyDeadline": 300000000000,
        "ProgressDeadline": 600000000000,
        "AutoRevert": false,
        "AutoPromote": false,
        "Canary": 0
      },
```

This suggests rolling updates are enabled, unless explicitely specifying `max_parallel = 0`. Changing the job also shows this behaviour, without `update` block it replaces instances one-by-one. Specifying `max_parallel = 0` does stop all the jobs first and then starts new jobs.

So I think the documentation is not correct when it comes to omitting the `update` block? Or am I missing something here?

[edit] Sorry for the label, it auto-added that when I clicked through from the bug template and I can't remove it.

**Comment by tgross** [comment]
Hi @MikeN123 thanks for opening this. This looks like an unfortunate terminology drift we never cleaned up; "rolling" was a little more specific to Nomad's internals at one point. If you'd like to submit a PR I'd be happy to review and merge it, otherwise I'll try to get one up shortly. Thanks!
