### ISSUE TITLE
[question] where is the correct location (within the config) for consul.* 

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#1056]
I am confused about the proper use of the consul.* config parameters.

### Nomad version

```
# nomad  version
Nomad v0.3.1
```

### Operating system and Environment details

Ubuntu Linux 14.04 AMD64 on AWS.

### Issue

https://www.nomadproject.io/docs/agent/config.html confusingly states:

> The following is not an exhaustive list of options that can be passed to the Client, but rather the set of options that configure the Client and not the drivers.

..but when I put `consul.address` and `consul.token` into the `client` section of my config, I get: 

```
==> Error loading configuration from /etc/nomad/config.json: Error loading /etc/nomad/config.json: error parsing 'config': 3 error(s) occurred:

* client -> invalid key: consul.address
* client -> invalid key: consul.token
* client -> invalid key: node_id
```

When I move those two parameters out of the `client` section to the root of the config, I get:

```
==> Error loading configuration from /etc/nomad/config.json: Error loading /etc/nomad/config.json: error parsing 'config': 2 error(s) occurred:

* config: invalid key: consul.address
* config: invalid key: consul.token
```

Agent config looks like:

```
{
  "addresses": {
    "http": "10.10.10.10"
  },
  "datacenter": "us-west-2",
  "data_dir": "/var/lib/nomad/tmp/",
  "disable_anonymous_signature": true,
  "disable_update_check": true,
  "enable_debug": false,
  "enable_syslog": true,
  "log_level": "INFO",
  "name": "foobar",
  "region": "us-west-2",
  "syslog_facility": "LOCAL0",
  "client": {
    "consul.address": "consul.service.consul:8500",
    "consul.token": "FOOBAR",
    "servers": [
      "nomad-server.service.consul:4647"
      ],
    "meta": {
      "role": "manage"
    },


    "node_id": "foobar",
    "options": {
      "driver.raw_exec.enable": "1"
    },
    "enabled": true
  }
}
```

When I worked with the nomad server config, I saw similar errors. 

I am confused - How are the `consul.*` parameters intended to be used?

**Comment by iverberk** [comment]
Hi ketzacoatl,

Try putting those parameters in the options block of the client setting. So it would look like this:

```
...
"client": {
...
  "options": {
    "consul.address": "url"
  },
...
```
It is described here: https://www.nomadproject.io/docs/agent/config.html#options_map

**Comment by ketzacoatl** [comment]
OK, I see what that doc is _trying_ to communicate, and that makes sense now. I will find a short but simple way to update the docs with an example here. One last question, is this `options` key available in the `server` block as well?

**Comment by iverberk** [comment]
I don't believe it is available in the server block.

**Comment by ketzacoatl** [comment]
OK, so only clients communicate with consul?

**Comment by iverberk** [comment]
That is correct, in the end they are responsible for actually running the tasks and registering them in Consul. The servers only determine the scheduling.

**Comment by ketzacoatl** [comment]
Later in the day I will update this doc and submit a PR for review.  Thanks for your help!

**Comment by ketzacoatl** [comment]
Is there a reason why `node_id` in the `client` block would fail in a similar way? The docs clearly put `node_id` in the `client` block, but I see:

```
==> Error loading configuration from /etc/nomad/config.json: Error loading /etc/nomad/config.json: error parsing 'config': 1 error(s) occurred:

* client -> invalid key: node_id
```

config looks like:

```
    {
      "addresses": {
        "http": "10.10.10.11"
      },
      "datacenter": "us-west-2",
      "data_dir": "/var/lib/nomad/tmp/",
      "disable_anonymous_signature": true,
      "disable_update_check": true,
      "enable_debug": false,
      "enable_syslog": true,
      "log_level": "INFO",
      "name": "FOOBAR",
      "region": "us-west-2",
      "syslog_facility": "LOCAL0",
      "client": {
        "consul.address": "consul.service.consul:8500",
        "consul.token": "FOOBAR",
        "servers": [
          "nomad-server.service.consul:4647"
          ],
        "meta": {
          "role": "foobar"
        },
        
        
        "node_id": "FOOBAR",
        "options": {
          "driver.raw_exec.enable": "1"
        },
        "enabled": true
      }
    }
```

**Comment by iverberk** [comment]
I believe the node_id parameter should be removed from the documentation as it is no longer specifiable. 
Check https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md at the backwards incompatibilities for 0.3.0

**Comment by ketzacoatl** [comment]
Ah, yes, ok, I'll hit that separately.

**Comment by diptanu** [comment]
@ketzacoatl We are introducing a `consul` block very soon. so that would make configuring consul easier.

**Comment by ketzacoatl** [comment]
SGTM.
