### ISSUE TITLE
Make TLS server name domain configurable

### ISSUE THREAD

**Issue by llchan** [hashicorp/nomad#10562]
### Proposal
Currently the TLS server name domain (i.e. the `nomad` part of `server.global.nomad`) is hardcoded.  We should make this configurable like it is in Consul.

**Comment by drewbailey** [comment]
Hi @llchan thank you for submitting this issue, can you expand on your use a bit more? I'd be interested to hear how you are planning to configure the TLS server name and how you would expect it to be configured. Definitely happy to take this to the larger team for discussion, just want to make sure I have all the details you are looking for first.

**Comment by mikenomitch** [comment]
This isn't high on our priority list and we won't reasonably get to it any time soon. Going to close this out to clean up our open issues. If anybody feels strongly about having this, we wouldn't mind a PR, but again, not a high priority.
