### ISSUE TITLE
Group Networks stanza doesn't handle JSON object for port

### ISSUE THREAD

**Issue by redfive** [hashicorp/nomad#10575]
We use Levant to template our JobSpecs, and do a bunch of processing in JSON before submitting a JSON rendered JobSpec to Nomad. We do several passes that look like:
```
levant render .... | hcltool | jq ...
// and
hcltool <file> | jq ...
```

When defining a single port object in the Group -> Network stanza and then passing it through hcltool to spit out JSON it gets converted to a JSON object. If there are multiple ports it is converted to an array of objects. That part is fine, but Nomad doesn't handle the first case and throws an error.

There error returned is:

```
14:32:11  Error getting job struct: Error parsing job file from nomad-jobs/integration.yml_output/bates.hcl.final: error parsing 'job': 1 error occurred:
14:32:11  	* group: network -> invalid key: to
```

The hcl file snippet:
```
group "bates-pushgateway-group" {
      count = [[.pushgateway.count]]

      network {
        port "pushgateway" { to = 9091 }
      }
```

The json file snippet that gets passed to Nomad:
```
"bates-pushgateway-group": {
            "count": 1,
            "network": {
              "port": {
                "pushgateway": {
                  "to": 9091
                }
              }
            },
```

If I add a second port to the hcl file I get the following JSON:
```
"bates-pushgateway-group": {
            "count": 1,
            "network": {
              "port": [
                {
                  "pushgateway": {
                    "to": 9091
                  }
                },
                {
                  "dummy": {
                    "to": 9999
                  }
                }
              ]
            },
```

Nomad client version: Nomad v0.12.5+ent (99ba9e9ca75b102145db1d040d81306ff40e98e3)
Nomad server version: Nomad v0.12.5+ent (99ba9e9ca75b102145db1d040d81306ff40e98e3)
Levant version: Levant v0.3.0-dev (1996eece)
hcltool version: pyhcl==0.4.4
jq version: jq-1.5-1-a5b5cbe

**Comment by drewbailey** [comment]
@redfive I believe your json processors are incorrectly generating the json for ports. 

Here is an example that works fine

<details>
<summary>redis.json</summary>

```
{
  "job": [
    {
      "example": [
        {
          "datacenters": [
            "dc1"
          ],
          "group": [
            {
              "cache": [
                {
                  "network": [
                    {
                      "port": [
                        {
                          "db": [
                            {
                              "to": 6379
                            }
                          ]
                        },
                        {
                          "grpc": [
                            {
                              "to": 6380
                            }
                          ]
                        }
                      ]
                    }
                  ],
                  "task": [
                    {
                      "redis": [
                        {
                          "config": [
                            {
                              "image": "redis:3.2",
                              "ports": [
                                "db", "grpc"
                              ]
                            }
                          ],
                          "driver": "docker",
                          "resources": [
                            {
                              "cpu": 500,
                              "memory": 256
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

```

</details>

**Comment by redfive** [comment]
Sorry for missing your reply almost a year ago and just a day after my initial filing. 

Is your example not a case of multiple ports defined? Per my original statement that is the case that works. It's the case where just a single port is mapped that is a problem.

**Comment by tgross** [comment]
Hi @redfive! We missed notifications on this because Drew has moved on to another org (hi Drew! 👋 ). 

It looks like the block you've generated for a single port is incorrect. Even if it's just a single port, the shape of the field is still an array, so it needs to be passed as a 1-element array.

So instead of:

```json
"bates-pushgateway-group": {
  "count": 1,
  "network": {
    "port": {
      "pushgateway": {
        "to": 9091
      }
    }
  }
},
```

It should be:

```json
"bates-pushgateway-group": {
  "count": 1,
  "network": {
    "port": [
      {
        "pushgateway": {
          "to": 9091
        }
      }
    ]
  }
},
```

I'm going to close this one out as answered, but please feel free to open a new issue if you run into any new issues!
