### ISSUE TITLE
Expose monitor codebase publicly

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#10595]
### Proposal

Expose [`monitor`](https://github.com/hashicorp/nomad/blob/0af476263b5c6f12a43a069070400e1762ad17c2/command/monitor.go#L57), its properties, and its functions publicly.

### Use-cases

I am attempting to monitor a job submission from job creation => evaluation => deployment => allocs running. This isn't possible with the current API, which is currently internal.

### Attempted Solutions

I can copy-paste the whole file into my project, which isn't sustainable long-term.

Note: Levant basically reimplements this entire functionality.

**Comment by tgross** [comment]
@josegonzalez just for clarity, _only_ the `api` package is considered a supported stable interface. The command line interface is intentionally internal, along with the `monitor` struct inside it.

**Comment by tgross** [comment]
Hi @josegonzalez. Similar to https://github.com/hashicorp/nomad/pull/10594, we're going to close this issue out. We don't intend to surface our internal APIs outside of the `api` package the proto definitions for drivers.
