### ISSUE TITLE
Nomad debug command only captures `default` namespace

### ISSUE THREAD

**Issue by notnoop** [hashicorp/nomad#10622]
The `nomad debug` command only captures info (e.g. jobs/evals/allocs) from the `default` namespace. Ignoring other namespaces henders debugging in Enterprise contexts.

The following code should perform cross-namespace queries: https://github.com/hashicorp/nomad/blob/v1.1.0/command/operator_debug.go#L752-L771 .

**Comment by lgfa29** [comment]
Fixed in #11269
