### ISSUE TITLE
Update nomad server to interpolate meta variables in job spec

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#1063]
In in the job spec, if you try to use a `NOMAD_META_` variable with CPU/memory, or other params that expect an int, you get:

```
# nomad run foo.hcl 
Error parsing job file foo.hcl: error parsing 'job': task: 'redis', resources, network, ports -> 1 error(s) decoding:

* cannot parse 'static' as int: strconv.ParseInt: parsing "${NOMAD_META_REDIS_PORT}": invalid syntax
```

wrapping the var with quotes..

```
            network {
                mbits = 100
                port "redis" {
                    static = "${NOMAD_META_REDIS_PORT}"
                }
            }
```

 does not help:

```
# nomad run foo.hcl
Error parsing job file foo.hcl: error parsing: At 81:30: illegal char
```

As a user learning how to use nomad and the job spec, I am not understanding why the meta variable would be available to part of the job HCL but not elsewhere.

**Comment by diptanu** [comment]
@ketzacoatl Currently most of the interpolation happens on the Nomad client. The scheduler needs to know the static port you are asking for during scheduling so you will need to provide that value in the job spec. Any particular reason why you are specifying the port in the meta and not in the `static` field of the `port` object?

**Comment by ketzacoatl** [comment]
@diptanu, maybe I am not understanding, but it seems https://www.nomadproject.io/docs/jobspec/interpreted.html suggests that one could define a "variable" in the `meta` block like so: 

```
...
    meta {
        VERSION = "v0.3"
    }
```

and reference/use it like: `"VERSION" = "Version ${NOMAD_META_VERSION}"`.

At first, there's little that would suggest a reason why we could not use that for any parameter in the job spec. It sounds like the server needs to be able to interpolate those meta variables as well?

Maybe I am abusing these "meta" parameters, but my intention in using them has been to:
* Consolidate multiple values to a variable, such as, ports, tags, and similar details that may be referenced in more than one place.
* Give devs and ops a single section within the job config (ie the `meta` block) that can be used to set the "variables" used elsewhere in the job spec. Updating that one location is better than multiple updates spread out over the file.

**Comment by diptanu** [comment]
@ketzacoatl Yes you are right, Nomad servers should be able to interpolate variables too. We are going to revamp how we do interpolation shortly, so this should be possible in the future.

**Comment by ketzacoatl** [comment]
SGTM!

**Comment by ketzacoatl** [comment]
I renamed the issue for clarity.

One question: When I use meta to set docker info like:

```
job "foobar" {
    meta {
        ...
        DOCKER_TAG = "master"
        DOCKER_IMG = "foo/bar"
        DOCKER_REG = "https://docker-registry.example.com"
        ...
        task "foobar" {
            driver = "docker"
            config {
                image = "${NOMAD_META_DOCKER_REG}/${NOMAD_META_DOCKER_IMG}:${NOMAD_META_DOCKER_TAG}"
                ...
```

it seems Nomad is unable to interpolate those variables:

```
==> Task "foobar" is "pending"
Recent Events:
Time                   Type            Description
11/04/16 13:52:06 UTC  Restarting      Task restarting in 17.590437461s
11/04/16 13:52:06 UTC  Driver Failure  Failed to pull `${NOMAD_META_DOCKER_REG}/${NOMAD_META_DOCKER_IMG}:${NOMAD_META_DOCKER_TAG}`: API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
11/04/16 13:51:49 UTC  Restarting      Task restarting in 16.427437135s
11/04/16 13:51:49 UTC  Driver Failure  Failed to pull `${NOMAD_META_DOCKER_REG}/${NOMAD_META_DOCKER_IMG}:${NOMAD_META_DOCKER_TAG}`: API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```

Is this the server, or the agent? Eg, is this a manifestation of the same issue or something different?

**Comment by dadgar** [comment]
This will be fixed in Nomad 0.4

**Comment by ketzacoatl** [comment]
Thanks! Looking forward to it :)

**Comment by dadgar** [comment]
Fixed a while ago!

**Comment by michaelw** [comment]
I am trying the original example with nomad v0.5.6, but still hitting the same error:
```
Error getting job struct: Error parsing job file from redis.nomad: error parsing 'job': group: 'master', task: 'redis', resources, network, ports -> 1 error(s) decoding:

* cannot parse 'static' as int: strconv.ParseInt: parsing "${NOMAD_META_REDIS_PORT}": invalid syntax
```

Can you give an example how this should look like?
(Ideally, I'd like to calculate the port by using `<base_port> + ${NOMAD_ALLOC_INDEX}`)

**Comment by hmeine** [comment]
@michaelw Did you find a solution for the `<base_port> + ${NOMAD_ALLOC_INDEX}` idea?  We'd like to do exactly the same thing. However, I can only see documentation and examples for string interpolation. (I am considering trying ports like `"1000${id}"` which could work at least for ids in the range 0…9.)

**Comment by Luca-spopo** [comment]
Any pointers on where in the source code this is dealt with? I am also facing this issue and am ready to poke around and possibly submit a PR.

**Comment by Alexis-De-La-Torre** [comment]
any news on this?
it would be nice to be able to use a named port on the `local_bind_port` of upstream proxies but `local_bind_port = "${NOMAD_HOST_PORT_portname}"` gets you the ` Unsuitable value type; Unsuitable value: a number is required` error

**Comment by ketzacoatl** [comment]
@Alexis-De-La-Torre, it might be good to create a new issue with the exact problem/feature/etc you are looking to see.
