### ISSUE TITLE
IP addresses not detected when using multitple routing tables

### ISSUE THREAD

**Issue by frederikbosch** [hashicorp/nomad#10631]
### Nomad version
0.11

### Operating system and Environment details
Ubuntu 18.04

### Issue
IP addresses not detected. I have three interfaces (ens18, ens19 and ens20), only ens18 has a gateway configured via netplan. The addresses from ens19 and ens20 are configured with manual routes in a different table. Therefore `attr.unique.network.ip-address` is not populated with the addresses from ens19 and ens20. I solved that for now with a meta variable on the client.

**Comment by tgross** [comment]
Hi @frederikbosch! Multi-interface networking was not supported until Nomad 0.12.0 (ref https://github.com/hashicorp/nomad/commit/ad8ced387364162b13baee408c7c5d3b6bfb2a74). Also, as 0.11 no longer receives bug fixes and security updates, I'd strongly recommend upgrading to a more recent version of Nomad.
