### ISSUE TITLE
Using "/" to focus search box does not work in Firefox

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#10646]
Typing "/" in Firefox (german keyboard layout, but that shouldn't make a difference) does not focus the search box but rather brings up Firefox's builtin quick search. See https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search -- I am not sure if there is a good way to override it.

Nomad version is 1.1.0

**Comment by tgross** [comment]
Thanks @apollo13. Can you provide a bit more information about your environment to help us debug this? I wasn't able to confirm this on macOS with Firefox 89.0 with an English/US keyboard layout.

**Comment by apollo13** [comment]
Mhm, Fedora 34 with Firefox 88.0.1 and german keyboard layout. (Works on Github if I hit "shift + 7" which is "/" on german layout)

**Comment by apollo13** [comment]
I can confirm that it works after switching to an english keyboard layout.

**Comment by apollo13** [comment]
I think this could be fixed by changing https://github.com/hashicorp/nomad/blob/main/ui/app/components/global-search/control.js#L27 to use `code == "/"`. Let me check.

**Comment by apollo13** [comment]
I have attached a PR that seems to fix it for me, reviews welcome.
