### ISSUE TITLE
CSI Volume Snapshot List: support secrets in the request

### ISSUE THREAD

**Issue by ggriffiths** [hashicorp/nomad#10640]
### Proposal
CSI List Snapshots supports secrets in the request:
https://github.com/container-storage-interface/spec/blob/master/csi.proto#L1173-L1176

However, when using `nomad volume snapshot list`, there is no way to pass this secret into the request (unless I'm missing something).

A possible solution could be the following workflow:
```
nomad volume snapshot list --secrets=key1=val1,key2=val2
```

This secrets map would be passed down to the CSI driver as mentioned in the CSI spec.

Alternatively, once #7978 is implemented:
```
nomad volume snapshot list --vault-secret=mysecret
```

### Use-cases
For CSI drivers that require a secret for a successful `nomad volume snapshot list`, this would be very helpful.

### Attempted Solutions
n/a - besides altering our CSI driver rules to allow for ListSnapshots without secrets.

I am happy to work on this issue if the above proposal is accepted.

**Comment by tgross** [comment]
Hi @ggriffiths! Yeah, this looks like we just missed this entirely. There's not even a field for it in the RPC endpoint. Will get this fixed.

**Comment by ggriffiths** [comment]
Sound good! I've been looking through the CSI code and can send a PR to add this feature if that would help.

**Comment by tgross** [comment]
I'd be happy to review a PR!
