### ISSUE TITLE
is nomad plan to handle dependency jobs?

### ISSUE THREAD

**Issue by liuq4360** [hashicorp/nomad#1065]
[proposal] i have many jobs have dependency, eg, A depend on B's results, B must finish before A, how to handle this problems, is nomad plan to handle dependency jobs?

**Comment by dadgar** [comment]
It is on our roadmap to be able to specify a DAG (directed acyclic graph) of jobs that Nomad will then execute. In the mean time, this can be built using Nomad APIs.

**Comment by dadgar** [comment]
@liuq4360 It will be a few months at minimum we have some other fun stuff planned ahead of that :)

**Comment by liuq4360** [comment]
thanks, I will always pay attention to nomad.






------------------


刘强








 
 
 
------------------ Original ------------------
