### ISSUE TITLE
Nomad CSI snapshot list: do not shorten snapshot ID

### ISSUE THREAD

**Issue by ggriffiths** [hashicorp/nomad#10660]
### Nomad version
```
[root@ip-70-0-14-127 demo]# nomad version
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)
```

### Operating system and Environment details
CentOS Linux 7 (Core)

### Issue
"nomad volume snapshot delete" is documented to take a snapshot id:
```
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete 
This command takes two arguments: <plugin id> <snapshot id>
For additional help try 'nomad volume snapshot delete -help'
```

However, after trying a few combinations, I noticed the delete only goes through when a snapshot name is provided.

**Update:** After looking into this more, I found that the snapshot id provided in `nomad volume snapshot list` is shortened to  12 characters. I was passing this shortened ID to `nomad volume snapshot delete`, which was not correct. Our snapshot ids are 18 characters. By coincidence, our CSI driver supports deleting snapshots by both name and ID, which explains the deletion succeeding via snapshot name.

Unless I'm missing something, there isn't a way to find the full snapshot id via `nomad volume snapshot list`. Perhaps a `nomad volume snapshot list -json` would be useful here? Similar to `nomad volume status -json`?

### Reproduction steps
An example like the follow could allow users to become confused as to why their snapshots aren't being deleted:
```
[root@ip-70-0-14-127 demo]# nomad volume snapshot create pxvol1 snap2
Snapshot ID   Volume ID     Size    Create Time           Ready?
111599152205  430708984379  10 GiB  1970-01-01T00:00:01Z  true
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
111599152205  430708984379  10 GiB  <none>       true
729104150236  338826921232  10 GiB  <none>       true
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete portworx 111599152205
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
111599152205  430708984379  10 GiB  <none>       true
729104150236  338826921232  10 GiB  <none>       true
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete portworx snap2
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
729104150236  338826921232  10 GiB  <none>       true
```

#### Expected Result

~~`nomad volume snapshot delete` docs and CLI help should reflect that this command takes a snapshot name~~
~~OR~~
~~`nomad volume snapshot delete`  implementation should instead take a snapshot_id as documented~~

`nomad volume snapshot list` should support a `-json` option.

#### Actual Result
~~`nomad volume snapshot delete` only works when a snapshot name is passed.~~

Option is not supported yet

### Job file (if appropriate)
n/a

### Nomad Server logs (if appropriate)
n/a

### Nomad Client logs (if appropriate)
n/a

**Comment by tgross** [comment]
Hi @ggriffiths! 

> After looking into this more, I found that the snapshot id provided in nomad volume snapshot list is shortened to 12 characters. I was passing this shortened ID to nomad volume snapshot delete, which was not correct. Our snapshot ids are 18 characters. By coincidence, our CSI driver supports deleting snapshots by both name and ID, which explains the deletion succeeding via snapshot name.

Yeah this is an unfortunate bug. We typically shorten IDs that come back in the Nomad CLI because it's safe to pass prefixes to Nomad. So for example, an alloc ID might be `c9add7a7-af32-40fd-9ce1-26bb4dae8221` but `nomad alloc status c9add7a7` works fine because our internal datastore allows us to do prefix searches. But the snapshot ID is an _external_ identifier and we have no control over whether the CSI plugin and external storage provider supports prefix searches. So we should not be shortening the snapshot ID. Will fix.

**Comment by ggriffiths** [comment]
Makes sense, I've updated this issue to reflect that fix.

**Comment by tgross** [comment]
This will ship in the next patch version of Nomad. Thanks @ggriffiths!
