### ISSUE TITLE
failures_before_critical does not get updated

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#10678]
### Nomad version
Nomad v1.1.0

### Operating system and Environment details
Ubuntu 18.04

### Issue
When changing [failures_before_critical](https://www.nomadproject.io/docs/job-specification/service#failures_before_critical), Nomad does not show a change in the value, always setting it to 0. I have also tried changing the `meta.uuid` field to force a deployment but the value stays at 0.

### Reproduction steps
Change the `failures_before_critical` value in the health check in the job file below.

#### Expected Result
Value changes as expected

#### Actual Result
Value remains at zero.

### Job file (if appropriate)

```hcl
job "dev-ops-httpbin" {
  meta {
    uuid = "51618dd2-5b10-44b6-8704-78e4d8b5b2e4"
    image_tag = "latest"
  }

  datacenters = ["dev-usw2-dev1"]

  type = "service"

  group "app" {
    count = 1

    network {
      port "http" {
        to = 80
      }
    }

    service {
      name = "${JOB}"
      port = "http"

      check {
        name     = "httpbin-ping"
        type     = "http"
        path     = "/anything"
        interval = "5s"
        timeout  = "2s"
        # TODO: Change this and plan again
        failures_before_critical = 3
      }
    }

    task "dev-ops-httpbin" {
      driver = "docker"

      config {
        image = "kennethreitz/httpbin:${NOMAD_META_image_tag}"
        ports = ["http"]
        force_pull  = true
        dns_servers = ["172.17.0.1"]
      }

      resources {
        cpu    = 100
        memory = 50
      }
    }
  }
}

```

**Comment by scalp42** [comment]
Is there a way to see the check params on Consul API side to actually confirm what's being passed?

**Comment by shoenig** [comment]
Thanks for reporting this, @evandam ! Indeed it looks like we're losing the value set for these somewhere, probably in the round trip from HCL to JSON. 

```
$ nomad job inspect example | jq -r .Job.TaskGroups[0].Services[0].Checks[0].FailuresBeforeCritical
0
```

Just FYI there's a Consul bug around these fields regardless, which probably needs to be fixed before they're useful
https://github.com/hashicorp/consul/pull/10256
