### ISSUE TITLE
Windows Server - process never terminated when sent SIGKILL/CTRL_BREAK_EVENT. It remains running and can only be killed manually.

### ISSUE THREAD

**Issue by tonetechnician** [hashicorp/nomad#10731]
### Nomad version
1.1.0

### Operating system and Environment details

os.name | Microsoft Windows Server 2019 Datacenter
os.signals | SIGKILL,SIGQUIT,SIGTERM,SIGABRT,SIGHUP,SIGFPE,SIGILL,SIGINT,SIGPIPE,SIGSEGV,SIGTRAP,SIGALRM,SIGBUS
os.version | 10.0.17763 Build 17763

### Issue
When running my .exe task with the raw_exec driver, I'm unable to terminate the process. I believe this should be receiving a CTRL_BREAK_EVENT, however the nomad client reports that the os uses regular POSIX signals. I'm unsure if this is correct?

Regardless, it would seem that my .exe is not receiving either the CTRL_BREAK_EVENT nor a forced kill from nomad. The only way for the process to stop is if I manually go into server and run "Stop-Process" or kill via the task manager. Then nomad reports it has been successfully killed. 

### Reproduction steps

Deploy nomad job with the following .exe: [zip for job](https://test-ue-build.s3-eu-west-1.amazonaws.com/WindowsNoEditor.zip)

When stopping the job or trying to push an update, the nomad client hangs on the "Killing" step. I receive the error logged in the last section of this issue. 

#### Expected Result

I expect the application should be terminated, or at the very least, forced killed after the termination doesn't succeed. Neither of these happen and I'm left with a running process. Nomad also reports that this process is still running 

#### Actual Result

The process doesn't exit whatsoever and nomad continues to report it is still running. There is no force kill event sent to the process either. The only way for Nomad to change this state is if I manually go into my server and kill the process with task manager

![image](https://user-images.githubusercontent.com/13471797/121371462-dba2ce00-c93d-11eb-85bd-0f1c77e74a08.png)

### Job file (if appropriate)

```
job "ue-process" {
  datacenters = ["dc1"]

  update {
    stagger      = "30s"
    max_parallel = 1
  }

  group "test-ue" {
    count = 1
    network {
      port "http" {
        static = 7001
      }
    }

    constraint {
      distinct_hosts = true
    }

    task "run-unreal" {
      driver = "raw_exec"
      artifact {
        source      = "test-ue-build.s3-eu-west-1.amazonaws.com/WindowsNoEditor.zip"
        mode        = "dir"
        destination = "local"
      }

      config {
        command = "local/WindowsNoEditor/MyProject2.exe"
        args = ["-RenderOffscreen"]
      }
      resources {
        cpu        = 2000
        memory     = 8000
      }
    }
  }
}
```
### Nomad Client logs (if appropriate)
```
2021-06-09T14:10:49.391Z [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 task=run-unreal backoff=1m20s error="executor Shutdown failed: rpc error: code = Unknown desc = 1 error occurred:
	* process did not exit after 15 seconds
```

**Comment by tgross** [comment]
> When running my .exe task with the raw_exec driver, I'm unable to terminate the process. I believe this should be receiving a CTRL_BREAK_EVENT, however the nomad client reports that the os uses regular POSIX signals. I'm unsure if this is correct?

First we send `CTRL_BREAK`, and then after the grace period we send [`os.Process.Kill`](https://golang.org/pkg/os/#Process.Kill), which on Windows go implements by sending the [`PROCESS_TERMINATE`](https://golang.org/src/os/exec_windows.go#L48) syscall. See [`executor.go#L546-L554`](https://github.com/hashicorp/nomad/blob/v1.1.0/drivers/shared/executor/executor.go#L546-L554) and [`executor_windows.go#L53`](https://github.com/hashicorp/nomad/blob/v1.1.0/drivers/shared/executor/executor_windows.go#L53).

I've got a few follow-up questions:
* Can you explain a bit more what you mean by "the nomad client reports that the os uses regular POSIX signals"?
* Without source code I can't tell, but is your application masking signals to implement graceful shutdown behavior or something similar to that?
* Is that line the only logs related to shutting down the task in the client? It might be helpful to get some of the surrounding context.

**Comment by tonetechnician** [comment]
Thanks for the fast response @tgross! 

In response to your questions:
1. The nomad cluster reports that the client os supports SIGKILL,SIGINT etc.. My expectation is that this would report the windows signals that are used i.e CTRL_BREAK_EVENT/CTRL_CLOSE_EVENT? Or am I misunderstanding something?

os.signals | SIGKILL,SIGQUIT,SIGTERM,SIGABRT,SIGHUP,SIGFPE,SIGILL,SIGINT,SIGPIPE,SIGSEGV,SIGTRAP,SIGALRM,SIGBUS

![image](https://user-images.githubusercontent.com/13471797/121381148-c03bc100-c945-11eb-96c7-f16b512f40fe.png)

2. It's a great question regarding the masking of signals. I will have a closer look through the engine source code as the binary is built using a game engine, so there may be some stuff happening under the hood. When looking I couldn't find anything explicit. Also, I'm able to stop the process using the "Stop-Process" command with no problem. What might be useful for me is to make a simple go application that can run the same commands as listed here and see if the behavior remains. 

Is there potentially another way to run a "Kill process"? I've tried running a sidecar powershell that has an infinite while loop, which should catch the CTRL_BREAK_EVENT and handle the explicit shutting down of the .exe using Stop-Process, however the only issue is the Powershell script doesn't seem to respond to CTRL_BREAK_EVENT the way one would expect and can't catch the signal before exiting. 

3. As far as I can see those are the only logs pertaining to this issue. Here's a less redacted version of the original process. Keep in mind that my in use app has 2 side car processes which exit correctly, then one main process similar to the one I posted in the example in this issue.

```
2021-06-09T14:08:01.951Z [INFO]  client.gc: marking allocation for GC: alloc_id=ac3e2f67-c60f-3b67-9f39-20e961355c54
2021-06-09T14:08:08.014Z [INFO]  client: node registration complete
2021-06-09T14:08:42.978Z [WARN]  client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 task=run-renderer keys=
2021-06-09T14:08:42.979Z [INFO]  client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:local/UE_Instances/1.1.0/SanpshotService.exe Args:[-RenderOffscreen -bootstrap-servers b-1.ranger-1-sandbox.y9sq2j.c10.kafka.us-east-1.amazonaws.com:9092 -schema-registry-url http://schema-registry.local:8081 -topic-hash 10ba915]}"
2021-06-09T14:09:24.413Z [ERROR] client.host_stats: failed to collect disk stats: error="The I/O operation has been aborted because of either a thread exit or an application request."
2021-06-09T14:09:24.686Z [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 driver=raw_exec task_name=mount-gltf-s3 error="rpc error: code = Unavailable desc = transport is closing"
2021-06-09T14:09:24.686Z [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 driver=raw_exec task_name=mount-snapshot-s3 error="rpc error: code = Unavailable desc = transport is closing"
2021-06-09T14:09:44.386Z [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 task=run-renderer backoff=5s error="executor Shutdown failed: rpc error: code = Unknown desc = 1 error occurred:
	* process did not exit after 15 seconds

"
2021-06-09T14:10:09.388Z [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 task=run-renderer backoff=20s error="executor Shutdown failed: rpc error: code = Unknown desc = 1 error occurred:
	* process did not exit after 15 seconds

"
2021-06-09T14:10:49.391Z [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=7150fa41-c12f-1a5d-34ff-cb80ec44a342 task=run-renderer backoff=1m20s error="executor Shutdown failed: rpc error: code = Unknown desc = 1 error occurred:
	* process did not exit after 15 seconds

"
```

**Comment by tgross** [comment]
> os.signals | SIGKILL,SIGQUIT,SIGTERM,SIGABRT,SIGHUP,SIGFPE,SIGILL,SIGINT,SIGPIPE,SIGSEGV,SIGTRAP,SIGALRM,SIGBUS

Ah! That's interesting... that's from our fingerprinting, which is calling out to the `consul-template` library. And they're just returning a hard-coded map of signals (ref [`signals_windows.go`](https://github.com/hashicorp/consul-template/blob/master/signals/signals_windows.go)). That's a little weird because it's not exclusive to `consul-template` and we should probably own that list ourselves.

> Is there potentially another way to explicitly define to nomad how to kill the process? I

There's a configurable [`kill_signal`](https://www.nomadproject.io/docs/job-specification/task#kill_signal) which will get looked up in that same `consul-template` signals map. Windows supports things like `SIGTERM` for posix compatibility but maps them to the underlying implementation.

> Keep in mind that my actual app has 2 side car processes which exit correctly, then one main process similar to the one I posted in the example in this issue

Are the side cars also `raw_exec` processes? If so, that seems like a big clue that there's something specific to the main process shutdown here.

**Comment by tonetechnician** [comment]
Thanks again for the swift reply! 

> Ah! That's interesting... that's from our fingerprinting, which is calling out to the consul-template library. And they're just returning a hard-coded map of signals (ref signals_windows.go). That's a little weird because it's not exclusive to consul-template and we should probably own that list ourselves.

Ah, I think I understand that better. I'm still quite new to nomad + consul so not 100% sure how consul-template fits in. The project I built my project off included consul-template which probably explains why that is there? 

> There's a configurable kill_signal which will get looked up in that same consul-template signals map. Windows supports things like SIGTERM for posix compatibility but maps them to the underlying implementation.

Also good to know. I was unaware that Windows mapped them to their own implementation actually! I found this resource which seems to give a mapping of signals to windows signals. [https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160)

![image](https://user-images.githubusercontent.com/13471797/121387587-13644280-c94b-11eb-98fb-d51bfbab9982.png)

> Are the side cars also raw_exec processes? If so, that seems like a big clue that there's something specific to the main process shutdown here.

Yes they are. You are totally right, it seems like it could be something in the main application preventing these signals from being received. I'm going to dig deeper, but at the moment it's feeling like this isn't so much a bug with nomad as it is with my application. 

Will report back, thanks for the help!

**Comment by tgross** [comment]
> I'm still quite new to nomad + consul so not 100% sure how consul-template fits in. The project I built my project off included consul-template which probably explains why that is there?

My apologies, I wasn't being super clear there. Nomad embeds consul-template as a library to run [`template`](https://www.nomadproject.io/docs/job-specification/template) blocks. But for some reason we _also_ use that map of signals when we fingerprint the client's host, which doesn't have anything to do with consul-template. We're probably using that mapping from consul-template just because it doesn't make a lot of sense for us to copy it into Nomad if we're already embedding consul-template anyways. But it is confusing. In any case, it doesn't look to be involved at all in the problem you're facing.

**Comment by tgross** [comment]
Doing some issue cleanup and I'm going to close this one out. If your investigation finds new information, please feel free to reopen! Thanks!

**Comment by tonetechnician** [comment]
Sorry, I should've closed this! Turns out it was an error in my code :) Thanks for closing!
