### ISSUE TITLE
[docs] How to run blocking query

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#1076]
The docs explain what is blocking query but they don't explain how to run one:

https://www.nomadproject.io/docs/http/#blocking-queries

**Comment by dadgar** [comment]
This is the documentation on how to run one:

```
Any endpoint that supports blocking will also set the HTTP header X-Nomad-Index, a unique identifier representing the current state of the requested resource. On subsequent requests for this resource, the client can set the index query string parameter to the value of X-Nomad-Index, indicating that the client wishes to wait for any changes subsequent to that index.

In addition to index, endpoints that support blocking will also honor a wait parameter specifying a maximum duration for the blocking request. This is limited to 10 minutes. If not set, the wait time defaults to 5 minutes. This value can be specified in the form of "10s" or "5m" (i.e., 10 seconds or 5 minutes, respectively).
```

Please let us know how it may be clarified.

**Comment by sheerun** [comment]
The documentation is about **also** something, and not about blocking query itself. I don't know how to perform blocking query. I just know that I can configure behavior of it with `wait` and set `X-Nomad-Index`. If `X-Nomad-Index` **is** how to run blocking query, please remove "also" from first sentence.

**Comment by dadgar** [comment]
Sure! Will commit this change to master. Thanks!
