### ISSUE TITLE
Fingerprinting Nomad Clients (on restart) on Windows and ESXI hosts can far exceed the heartbeat

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#10761]
### Nomad version
1.0.4

### Operating system and Environment details
Windows 

### Issue
When restarting a Nomad agent on an ESXI host (vSphere) with a Windows VM, it can take over 15 seconds to fingerprint.

Right now we have manipulated the Heartbeat TTL settings to work around this, but it is not ideal.  Unfortunately this issue causes all windows allocations to be "lost" during a Nomad agent restart which then causes other disruptions to our cluster(s)

### Fix
@fredwangwang has submitted a PR to the underlaying library, here https://github.com/shirou/gopsutil/pull/1088 and when/if this is merged we are requesting this get included in the next Nomad refresh

Thanks!

**Comment by tgross** [comment]
Thanks @idrennanvmware. I think the approach to get that fixed in the upstream library is the right one. Marking this as accepted and once that lands we'll get it in the next patch.

**Comment by idrennanvmware** [comment]
@tgross @shoenig  - the above PR just got merged.  woohoo.

**Comment by idrennanvmware** [comment]
Thanks to everyone for making this such a quick process!
