### ISSUE TITLE
Website: Typo in use cases simple container orchestration page

### ISSUE THREAD

**Issue by mylesw42** [hashicorp/nomad#10770]
### Issue

This Nomad “use cases” website page includes an image that contains a typo:

[https://github.com/hashicorp/nomad/blob/main/website/pages/use-cases/simple-container-orchestration.jsx](https://github.com/hashicorp/nomad/blob/main/website/pages/use-cases/simple-container-orchestration.jsx)

Here is the image:

[https://github.com/hashicorp/nomad/blob/main/website/pages/use-cases/img/stateful-workloads.png](https://github.com/hashicorp/nomad/blob/main/website/pages/use-cases/img/stateful-workloads.png)

“postgesql” is a typo, should be “postgresql”.

**Comment by tgross** [comment]
Thanks @mylesw42. We'll get this in front of the folks who own those images.

**Comment by jrasell** [comment]
It also seems there is another typo where "Sorage" should be "Storage" in the CSI section.

**Comment by tgross** [comment]
@jescalan I'm going to close this issue out as it looks like after the big website refresh we no longer have this image. Or at least not anywhere in this repo. 😀  Thanks for opening the issue though @mylesw42!
