### ISSUE TITLE
[docs] How to get output of executed job

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#1077]
The docs are very vague how to get stdout / stderr of executed command.

I assume the preferred method is to run `nomad fs cat ALLOC_ID alloc/logs/default.stdout.0`, but that's only my guess. It would be great to document it for example in examples section of https://www.nomadproject.io/docs/commands/run.html

**Comment by troyswanson** [comment]
Agreed, it seems like the only place this is documented is in the blog:

https://www.hashicorp.com/blog/nomad-0.3.html#logs

**Comment by sethvargo** [comment]
Hey there,

We have added a bunch of documentation to around the nomad logs command and nomad logs syntax: 

- https://www.nomadproject.io/docs/jobops/logs.html
- https://www.nomadproject.io/docs/commands/logs.html

The next version of the docs also includes even more comprehensive guides, so please keep a look out for those with the 0.5 release 😄
