### ISSUE TITLE
CSI: Attempting to mount EBS volume in the wrong AZ

### ISSUE THREAD

**Issue by m1keil** [hashicorp/nomad#10793]
### Nomad version
`Nomad v1.1.1 (7feec97c04de4f8afff54ca9e56d66a61dfbfeb3)`

### Operating system and Environment details
`Ubuntu 20.04.2 LTS`

### Issue
When working with CSI and aws-ebs driver, it seems like one must add the volume's AZ as one of the constraints to the task. 
Otherwise, it's possible the scheduler will try to start the task in the wrong AZ. The error will look something like this:

> failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: rpc error: controller publish: attach volume: controller attach volume: rpc error: controller attach volume: CSI.ControllerAttachVolume: controller plugin returned an internal error, check the plugin allocation logs for more information: rpc error: code = Internal desc = Could not attach volume "vol-xxx" to node "i-xxx": could not attach volume "vol-xxx" to node "i-xxx": InvalidVolume.ZoneMismatch: The volume 'vol-xxx' is not in the same availability zone as instance 'i-xxx' status code: 400, request id: f679dcf5-59f1-4270-9ace-1942df9f18af

I'm not sure if this is a bug or an undocumented issue, however, I wish this was an implicit constraint instead of an excplicit one.

### Reproduction steps

- Have your workloads spread in AWS across 2 or more AZs
- Configure CSI storage volume for a job
- Attempt to schedule it few times

#### Expected Result
Volume's AZ should be added as a constraint to task's group, and the task should be started in the correct AZ to allow mounting.

#### Actual Result
The task might fail to start at times if the scheduler picked the wrong AZ.

**Comment by tgross** [comment]
Hi @m1keil!

Is AZ information exposed by the EBS driver? I'm looking at the docs in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/docs and don't see any reference to AZ at all (which I find surprising!). And they have this issue open https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/760 which says to configure node-affinity in K8s (which would be a constraint in Nomad). This all seems to suggest that the controller that creates the volume needs to be in the same AZ where it's being mounted, which means controller's aren't HA across AZs.

You can get what you want here without any changes in Nomad by deploying your controllers per-AZ, which you'll need to do for HA anyways. So deploy 2 controller allocs per AZ, with a `plugin_id` specific to the AZ (ex. `aws-ebs-us-east-1a`). Then when you create and mount the volumes, you'll use the AZ-specific `plugin_id` for those volumes and all the constraints fall out naturally from there without any additional work on your part.

**Comment by m1keil** [comment]
Thanks, @tgross that makes sense.

It would be really good to have this added to the slightly out of date documentation about CSI.

**Comment by tgross** [comment]
Agreed. I've opened https://github.com/hashicorp/nomad/pull/10798
