### ISSUE TITLE
UI Customization

### ISSUE THREAD

**Issue by khaledabdelaziz** [hashicorp/nomad#10813]
### Proposal

Add a way to customize Nomad UI so users can distinguish between environments easily.
Some suggestions:
1- Parameter to set theme color
2- Parameter to add a custom heading in the top bar (e.g., "UAT Environment")

### Use-cases

This is helpful for UI users whom support multiple environments to easily distinguish between them.

### Attempted Solutions

N/A

**Comment by jrasell** [comment]
Hi @khaledabdelaziz and thanks for the interesting enhancement idea. This will certainly need some further investigation and thought by the UI and Design team as well as updated Nomad configuration options to handle this.

**Comment by israellot** [comment]
This would be super helpful. Voting up

**Comment by mkumar-tc** [comment]
@jrasell This is going to very useful. Are we still pursuing this?

**Comment by mikenomitch** [comment]
Moving this to stage/accepted. At least passing a custom string into the UI to differentiate environments is something we would like to get to.

It isn't a *top* priority for us though, so if anybody wants to take a crack at it, they're more than welcome to. Let us know if you do!

I think the right way to do this would be to pass a value into the [ui config block in the agent config](https://www.nomadproject.io/docs/configuration/ui). Maybe something like "environment_name"? Then that value would be thread through to the UI

* See `nomad/structs/config/ui.go:6` for the config struct to add it to
* See references to "this.system.agent.config.UI" in `ui/app/templates/components/global-header.hbs` for a way to access these values

I'll work with our designer @juliezzhou to add a mockup to this Issue to show where that title could go. If we don't get a mockup on here, feel free to take a crack at it though!

**Comment by zemm** [comment]
Great that this is accepted. I still believe a color at least somewhere would be essential part of this to keep the ergonomics good. Often times one might switch between the environments throughout the day, and you wouldn't read static texts repeatedly nor differentiate them just by glance. There might already be differentiating texts somewhere like in the url, but we still make mistakes sometimes. Color would be noticed by a glance, and release some of the burden from the operator, reducing errors and being a helpful feature.

**Comment by juliezzhou** [comment]
I am thinking to add a tag/badge on the top banner to indicate the environment, here is the screenshot. 
<img width="1036" alt="Screen Shot 2022-08-15 at 1 02 08 PM" src="https://user-images.githubusercontent.com/90711359/184681179-5cf1025c-2ef4-41c4-a05d-23a4d45ae371.png">
 
 I tried filling the color in the entire top bar, which clashes with our brand color scheme, so I made it more subtle. and I think the badge clearly indicate the environment?

**Comment by philrenaud** [comment]
Hi! We've just merged what we hope is a good solution for this.

In a soon-upcoming Nomad release, you'll be able to add the following to your agent config under the `ui` block:

```
  label {
    text             = "Miami Datacenter"
    background_color = "palegreen"
    text_color       = "hotpink"
  }
```

And receive a label both in the UI itself as well as the `<title>` attribute in your browser tabs. 
![image](https://user-images.githubusercontent.com/713991/216456092-89b250fd-5fdb-4efb-9c3b-651e2fb2c417.png)

**Comment by momania** [comment]
Awesome! Will this be replaced across the whole suite at some point, so we can get this feature on Consul, Vault, etc too? Because that would be legendary.

**Comment by mikenomitch** [comment]
@momania, no plans that I know of on the other projects. We kind of did this on a whim since we had some open space before the 1.5 release (stay tuned on that front 😄).

I added a link to this PR on the related Vault issue. Surprisingly, I didn't find a Consul issue, but maybe my GitHub searching was bad.

**Comment by finnstech** [comment]
We are working on this for Vault for an upcoming release. Stay tuned!

**Comment by akamensky** [comment]
Please consider the same for Consul UI.
