### ISSUE TITLE
nomad system gc doesn't take into account command line variables, only environment variables

### ISSUE THREAD

**Issue by KarimJedda** [hashicorp/nomad#10820]
Hi everyone, I just stumbled on what I believe is a little bug :) hope the following helps! I don't know go otherwise I would have tried to submit a PR. 

### Nomad version
Output from `nomad version` (on server, clients, management and local machines)
`Nomad v1.1.1 (7feec97c04de4f8afff54ca9e56d66a61dfbfeb3)`

### Operating system and Environment details

Linux (Ubuntu 20) + tested on remote management server (Ubuntu 18)

### Issue

Following doesn't work:
`nomad system gc -ca-path=nomad-ca.pem -client-cert=nomad-cli-cert.pem -client-key=nomad-cli-key.pem -address=https://control:4646 -token=myepictoken`

Following works:
`NOMAD_ADDR=https://control:4646 NOMAD_CACERT=nomad-ca.pem NOMAD_CLIENT_KEY=nomad-cli-key.pem NOMAD_CLIENT_CERT=nomad-cli-cert.pem NOMAD_TOKEN=myepictoken nomad system gc`

### Reproduction steps

- Spin up a remote nomad cluster.
- Trigger garbage collection from a remote machine without setting the environment variables

#### Expected Result

The expected results refer to the following documentation https://www.nomadproject.io/docs/commands/system/gc#general-options

#### Actual Result

Variables not taken into account, requests are made to http://127.0.0.1:4646 for example when -address is set
`Error running system garbage-collection: Put "http://127.0.0.1:4646/v1/system/gc": dial tcp 127.0.0.1:4646: connect: connection refused`

**Comment by jrasell** [comment]
Hi @KarimJedda and thanks for raising this issue. I have identified the problem and will shortly raise the fix.
