### ISSUE TITLE
failed to set the cpuset cgroup for container when using consul connect

### ISSUE THREAD

**Issue by microadam** [hashicorp/nomad#10837]
### Nomad version
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)

### Operating system and Environment details
Ubuntu 20.04.2 LTS (LXD Container, if that matters...)

Relevant point: nomad client running as root user. Consul running as consul user

### Issue
Fresh installation of a consul and nomad cluster

### Reproduction steps

Run the following job:

```
job "demo-site-staging" {

  update {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    progress_deadline = "10m"
    auto_revert = true
    auto_promote = true
    canary = 1
    stagger = "30s"
  }

  group "demo-site-staging-admin-ingress" {
    count = 1
    network {
      mode = "bridge"
      port "http" {
        to = 8080
      }
    }
    service {
      name = "demo-site-staging-admin-ingress"
      port = "http"

      tags = [
        "traefik.enable=true",
        "traefik.http.routers.demo-site-staging-admin-ingress.rule=Host(`demo-site-staging-admin.test-cluster-01.example.uk`)",
        "traefik.http.routers.demo-site-staging-admin-ingress.tls=true",
        "traefik.http.services.demo-site-staging-admin-ingress.loadbalancer.server.scheme=https",
        "traefik.http.services.demo-site-staging-admin-ingress.loadbalancer.serversTransport=ingress@file",
      ]

      connect {
        gateway {
          proxy {}
          ingress {
            tls {
              enabled = true
            }
            listener {
              port = 8080
              protocol = "tcp"
              service {
                name = "demo-site-staging-admin"
              }
            }
          }
        }
      }
    }
  }

  group "demo-site-staging-admin" {
    count = 1
    network {
      mode = "bridge"
    }

    service {
      name = "demo-site-staging-admin"
      port = "80"

      connect {
        sidecar_service {}
      }
    }

    task "demo-site-staging-admin" {
      driver = "docker"
      config {
        image = "nginx:latest"
      }
      resources {
        cpu = 1000
        memory = 1024
      }
    }
  }
}
```

#### Expected Result

Job should start successfully (I am fairly sure this worked on an older version of nomad. I will see if I can confirm that in a follow up)

#### Actual Result

All envoy containers fail with the error:
```
failed to set the cpuset cgroup for container: failed to write 11249 to cgroup.procs: write /sys/fs/cgroup/cpuset/nomad/shared/cgroup.procs: permission denied
```

### Nomad Client logs (if appropriate)

Relevant lines:

```
Jul 01 16:56:04 hashistack-worker-01 nomad[8550]:     2021-07-01T16:56:04.659Z [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=6cadf1fb-2087-ea23-bf17-afce7a7c47df task=connect-proxy-demo-site-staging-admin error="failed to set the cpuset cgroup for container: failed to write 11869 to cgroup.procs: write /sys/fs/cgroup/cpuset/nomad/shared/cgroup.procs: permission denied"
Jul 01 16:56:04 hashistack-worker-01 nomad[8550]:     2021-07-01T16:56:04.659Z [INFO]  client.alloc_runner.task_runner: not restarting task: alloc_id=6cadf1fb-2087-ea23-bf17-afce7a7c47df task=connect-proxy-demo-site-staging-admin reason="Error was unrecoverable"
Jul 01 16:56:04 hashistack-worker-01 nomad[8550]:     2021-07-01T16:56:04.685Z [WARN]  consul.sync: failed to update services in Consul: error="Unexpected response code: 500 (Unknown service "_nomad-task-6cadf1fb-2087-ea23-bf17-afce7a7c47df-group-demo-site-staging-admin-demo-site-staging-admin-80-sidecar-proxy")"
```

Please let me know if you need any more info!

**Comment by tgross** [comment]
> LXD Container, if that matters...

It probably does. Nomad clients should not be run in containers, as they need to `CAP_SYSADMIN`. It's possible you might have had it working previously with enough LXD knobs turned, that's unfortunately not a use case we test and can reasonable support. See https://www.nomadproject.io/docs/install/production/requirements#linux-capabilities

**Comment by microadam** [comment]
@tgross thanks for the link! I have been using LXD containers for spinning up clusters easily. It had been working well! I have now just downgraded to nomad 1.0.4 and consul 1.9.5 which is the versions I was using until recently, and everything works just fine using the exact same LXD config. So I can only assume some changes in newer versions of nomad / consul are requiring higher privileges! I will try upgrading again and running them a privileged containers and see if that solves things

**Comment by microadam** [comment]
Update: Upgraded consul and nomad to latest versions and running them in a privileged LXD container works just fine! So you are correct in its an LXD permissions issue
