### ISSUE TITLE
metrics don't emit max_memory

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#10838]
We emit the allocated memory for tasks but not the max_memory for oversubscription, which means you can't use the metrics endpoint to track how close you are to OOM when oversubscribed.

cc @angrycub

**Comment by danishprakash** [comment]
@tgross is this something that a new contributor can pick up? would like to work on this.

**Comment by tgross** [comment]
Hi @danishprakash! It should be reasonably approachable. We emit the metrics for allocated memory in [`setGaugeForAllocationStats `](https://github.com/hashicorp/nomad/blob/v1.1.2/client/client.go#L2861) so it should be similar to that. Thanks!

**Comment by danishprakash** [comment]
@tgross thanks for the response. I ran into some issues while running `make test` which looks like something to do with my system. (I followed the instructions over at [contributing](https://github.com/hashicorp/nomad/tree/c4e0355775f37a0ed2420aafaa54e76f371bfe3f/contributing) though). Anyway, I've pushed the changes [here](https://github.com/hashicorp/nomad/compare/main...danishprakash:danish-metrics-max-mem?expand=1), basically just returning `MemoryMaxMB` as part of `ComparableResources` struct and then exporting it as `max_memory` gauge.

**Comment by tgross** [comment]
@danishprakash just wanted to follow-up on this one... the branch you have up looks reasonable to me. If you're interested in opening a PR we could try to get that merged in. I realize it's been a while though, so if you don't have time I'd can pick it up.
