### ISSUE TITLE
Topology view access denied until selecting namespace with at least one job

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/nomad#10830]
### Nomad version

`1.1.2+ent`

### Issue

The topology ui view shows an access denied error if the selected namespace (typically `default` on first access) has no defined jobs. This caused some wild goose chasing through policies. Selecting a namespace on the jobs view, or crafting the URL to contain a namespace where that namespace has at least one job defined then displays the topology view as expected.

### Reproduction steps

- Possibly have namespaces enabled
- Have no jobs running in default namespace
- Try to navigate to the topology view, get access denied error
- Switch to another namespace which does contain a job
- Try to navigate to topology view, now works

#### Expected Result

Access denied error message not displayed if the user does indeed have the right permissions.
Blank topology to be displayed if no jobs are visible to user.

#### Actual Result

Access denied view, suggesting user authenticate with a different token.

**Comment by shoenig** [comment]
Thanks for reporting, @optiz0r ! I'll hand this over to our UI team to look into.

**Comment by ChaiWithJai** [comment]
Should be [resolved](https://github.com/hashicorp/nomad/pull/15244) now.
