### ISSUE TITLE
Nomad server registers service on an agent with the server's own node name?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#1088]
I am not sure if what I am seeing is a bug or misconfiguration.

### Nomad version

```
Nomad v0.3.1
```

### Operating system and Environment details

Ubuntu 14.04, AWS EC2, docker 1.9.1, consul 0.6.3

### Issue

I have nomad running a job/task with redis (by itself), and nomad is configured to publish the task in the consul catalog. When I lookup the service in the catalog using Consul's HTTP API, I get:

```
# curl -s http://localhost:8500/v1/catalog/service/redis
[{"Node":"leaders-i-FOOBAR","Address":"10.10.11.4","ServiceID":"nomad-registered-service-foobar","ServiceName":"redis","ServiceTags":[],"ServiceAddress":"10.10.1.24","ServicePort":10020,"ServiceEnableTagOverride":false,"CreateIndex":102079,"ModifyIndex":102079}]
```

What confuses me here is that I expect "Node" to be the node where the job is running, but the catalog has the "node" for this service as the node that registered the service (nomad server).

The Service Address is correct, matching the node the nomad task is actually running on. I first found this because the Consul UI showed the nomad task as running on the leader (UI says this leader referenced in the catalog above had 4 services while the other leaders have 3).

### Reproduction steps

Run redis:

```
job "redis" {
    # this is required
    datacenters = ["foobar"]
    # job type
    type = "service"
    # Create a redis server using the docker image
    task "redis" {
        driver = "docker"
        config {
            image = "redis"
            port_map {
                redis = 6379
            }
        }
        service {
            name = "redis"
            port = "redis"
            check {
                type = "tcp"
                interval = "30s"
                timeout = "5s"
            }
        }
        resources {
            cpu = 20
            memory = 2048
            network {
                mbits = 100
                port "redis" { }
            }
        }
    }
}
```

`nomad run redis.hcl` - kick back and wait a moment, then ping Consul:

```
[
  {
    "Node": "leaders-i-foobar",
    "Address": "10.10.11.4",
    "ServiceID": "nomad-registered-service-890009e7-68f6-97d9-ac9e-9f0d8fba2478",
    "ServiceName": "redis",
    "ServiceTags": [],
    "ServiceAddress": "10.10.1.24",
    "ServicePort": 10020,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 102079,
    "ModifyIndex": 102079
  }
]
```

So the "ServiceAddress" is correct, but it seems wrong that the Consul UI reports the service as running on the leader..

Also, I am not sure if this is related, or a separate issue.. but it seems worth mentioning.. this might be "nomad service registration is stale".. after I stopped the job, updated the redis job spec, `nomad run redis.hcl` again, and this time:

```
# curl -s http://localhost:8500/v1/catalog/service/redis | jq .
[
  {
    "ModifyIndex": 102079,
    "CreateIndex": 102079,
    "Node": "leaders-i-foobar",
    "Address": "10.10.11.4",
    "ServiceID": "nomad-registered-service-890009e7-68f6-97d9-ac9e-9f0d8fba2478",
    "ServiceName": "redis",
    "ServiceTags": [],
    "ServiceAddress": "10.10.1.24",
    "ServicePort": 10020,
    "ServiceEnableTagOverride": false
  }
]
```

But the allocation port and GUID are different, what consul has is stale:

```
aa708a9d7e7e        redis                                                         "/entrypoint.sh redi   5 minutes ago       Up 5 minutes        10.10.1.24:55981->6379/tcp, 10.10.1.24:55981->6379/udp   redis-66335acf-4f0b-3506-3b34-f351913643c9
```

If I `dig redis.service.consul`, I get the old IP.

I am not sure if you need more info, please let me know if so, and/or how I can best help determine what is an issue in my configuration versus a bug in nomad or consul (ui). Thanks!

**Comment by dadgar** [comment]
@ketzacoatl: The `Node` you see in the catalog is actually the Consul Node you've registered the service on. I take it Nomad is talking directly to a Consul server. Most people run a local agent.

I could not reproduce the second issue you had however. Could you please try on the Nomad 0.3.2-RC that will be coming out soon

**Comment by ketzacoatl** [comment]
Hrm, I thought I had changed that, I will look a little closer at where nomad is told to find consul. And yes, I can test the 0.3.2 RC when that's out.

**Comment by dadgar** [comment]
@ketzacoatl just released the rc: https://releases.hashicorp.com/nomad/0.3.2-rc1/

**Comment by ketzacoatl** [comment]
I confirmed this as a misconfiguration (as described above - the nomad agent config had the consul address as the consul servers, rather than localhost), thanks!
