### ISSUE TITLE
Exposing HTTPS health check: `protocol 'https' not supported for path: /health, must be in: [http http2]`

### ISSUE THREAD

**Issue by gregory112** [hashicorp/nomad#10914]
### Nomad version
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)

Consul v1.10.0
Revision 27de64da7
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### Operating system and Environment details
Ubuntu 20.04

### Issue
I'm trying to do a health check but the health check path is accessible only through HTTPS. In Nomad, using `check` stanza with this configuration works, but the port needs to be exposed completely so Consul can access it.
```
protocol = "https"
tls_skip_verify = true
```

To prevent exposing the port, I know I can use `expose` stanza and expose /api/version. Because Nomad can configure the expose path automatically for me, I also added `expose = true` in `check`.

Is exposing HTTPS supported or not? I understand that proxying HTTPS connection with L7 sidecar proxy may not be possible. However, by setting `expose = true` I receive this error in Consul, which seems to be related.

```
Jul 20 13:27:42 nomad1 consul[90609]: 2021-07-20T13:27:42.610Z [ERROR] agent: failed to sync changes: error="1 error occurred:
Jul 20 13:27:42 nomad1 consul[90609]:         * protocol 'https' not supported for path: /health, must be in: [http http2]
```

This is a development server and so consul is running also in the Nomad host. I also have tried writing my own expose using `http` protocol although the check protocol is `https`.

I also have other services for the same task running to expose other HTTP ports. AFAIK it is not supported for a single service block to multiple port and so I have to spawn multiple Envoy proxies for this service by writing multiple service stanzas, registering my task under many different names in Consul.

Thank you so much for your help.

### Reproduction steps
Enable Consul Connect.
Add a service `check` with `protocol` set to `https` and `expose` set to `true`.

#### Expected Result
I don't know the expected result, I don't know if this is expected, I am quite new to Nomad/Consul integration.

#### Actual Result
The error log above.

**Comment by tgross** [comment]
Hi @gregory112! The error message you've got from Consul suggests that the protocol has been stuffed into the `path` field, which doesn't look right to me, and then you're talking about [`expose`](https://www.nomadproject.io/docs/job-specification/check#expose) but nothing else about the Connect configuration. 

It might be easier for me to figure out what's up with more information. Can you provide the full `service` and `check` block you're using here?

**Comment by tgross** [comment]
Augh, sorry, I was doing some issue cleanup and I just realized this issue was over a year old at this point. Not reasonable of me to assume you'll get back to us now. If you do happen to come back to this, great and we'll be happy to re-open. Apologies for dropping this one.
