### ISSUE TITLE
connection issues with connect native tasks in bridge networking

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#10933]
As pointed out by @apollo13 in https://github.com/hashicorp/nomad/issues/10804#issuecomment-885793340

```
Jul 23 18:31:58 sfo3 nomad[1297]:     2021-07-23T18:31:58.342Z [WARN]  client.alloc_runner.runner_hook: error proxying from Consul: alloc_id=e39dffd5-b719-f4f2-09ee-891e9d96520a error="write unix /opt/nomad/data/alloc/e39dffd5-b719-f4f2-09ee-891e9d96520a/alloc/tmp/consul_http.sock->@: write: broken pipe" dest=127.0.0.1:8501 src_local=/opt/nomad/data/alloc/e39dffd5-b719-f4f2-09ee-891e9d96520a/alloc/tmp/consul_http.sock src_remote=@ bytes=2466
```

~I believe those errors are coming from the `consul_grpc_sock` hook, which I don't think even needs to be present for non-sidecar using connect tasks? Although it's also suspicious there are connection errors...~

JK it's the `consul_http_sock` hook using shared code from the other one.

**Comment by apollo13** [comment]
Hi @shoenig -- I wonder if this is traefik's fault (or can you reproduce this with arbitrary connect native jobs?). If the connect native job were to tear down the connection to the socket mid response etc then this could probably also causes issues like this. It should probably not get logged at `WARN` then.

If really traefik is at fault I wonder why/how because it simply uses the consul SDK :D

**Comment by shoenig** [comment]
I'm fairly sure this is a result of re-using some connection handling bits intended for long-lived gRPC connections between the nomad agent and consul agent, and experiencing disconnects when being used with the Consul HTTP listener instead. 

In a world where everything is easy we'd just proxy the HTTP requests, but that doesn't work when either Consul or the app is expecting to use mTLS. We could just get rid of the log statement since the TCP proxy gets re-created on the next HTTP request anyway, but I want to poke around a bit more and see if I can't manage the proxy lifecycle per request.
