### ISSUE TITLE
Web UI does not show CSI volumes when querying all namespaces

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#10939]
### Nomad version
Output from `nomad version`

### Operating system and Environment details
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)

### Issue
The webui only shows volumes when querying the namespace directly:

![image](https://user-images.githubusercontent.com/81547/126997709-ee4d025e-08b4-482d-8059-56e33d366570.png)

but not via all namespaces:

![image](https://user-images.githubusercontent.com/81547/126997672-6d1ce7ff-448a-4d54-b829-12a14a1a16a9.png)

### Reproduction steps

Toggle the namespace selector between all namespaces and the namespace where the volume is actually registered

**Comment by tgross** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/11724 and shipped in 1.2.4:

<img width="1126" alt="Screen Shot 2022-01-20 at 11 52 08 AM" src="https://user-images.githubusercontent.com/1409219/150384756-37d2463f-3fdf-4b75-be25-47c340402306.png">
