### ISSUE TITLE
[feature request] When querying the HTTP API for a job, add in task group and task status.

### ISSUE THREAD

**Issue by g0t4** [hashicorp/nomad#1093]
Could we get status on a task group and task level when we querying a job? (/v1/job/:id) 

I see allocs/evals as implementation details. I'd prefer to get all of the status of a job in terms of complete/running/queued, especially when it comes to batch jobs.

This would really be helpful to build estimates of the amount of queued work for scaling purposes.

**Comment by dadgar** [comment]
That endpoint returns the job object itself. There exists `/v1/job/:id/allocations` and /v1/job/:id/evaluations` for this purpose. Hopefully with 0.4 we can make the number of pending allocations more obvious.

**Comment by g0t4** [comment]
Sounds good, I'm mashing up pending allocations with past task run times as
a scaling trigger
