### ISSUE TITLE
File System Drivers Tracker AKA Enforce Ephemeral Disk Stanza

### ISSUE THREAD

**Issue by wurosh** [hashicorp/nomad#10937]
### Proposal

File System drivers have been in discussion since at least 2017 as far as I can tell (#2355, #2296).

Though there are understandably other priorities, implementing this feature, even in a non-pluggable way, is quite important in my opinion, as its absence limits use-cases where Nomad would really shine compared to the competition.

Have there been any developments in this area since discussion started?

### Use-cases

Any kind of non-cooperative multi-tenancy. It currently cannot be done with Nomad at all due to this missing feature, as there is no way to prevent disk-space-related noisy-neighbor problems

### Attempted Solutions

The most naive implementation I can think of boils down to implementing a `Volume` interface with `Create` and `Destroy` methods and implementations for XFS, BTRFS, and ZFS, then using it inside [allocdir.createDir](https://github.com/hashicorp/nomad/blob/0af476263b5c6f12a43a069070400e1762ad17c2/client/allocdir/alloc_dir.go#L582) and [allocdir.Destroy](https://github.com/hashicorp/nomad/blob/0af476263b5c6f12a43a069070400e1762ad17c2/client/allocdir/alloc_dir.go#L280).

Of course it would also be nice to report allocation statistics back, and that might be a little less straightforward, but equally achievable.

**Comment by tgross** [comment]
Nomad's support for [Container Storage Interface (CSI)](https://www.nomadproject.io/docs/concepts/plugins/csi) plugins is the way we've tackled this problem. We still have some internal discussions going about dynamic host volumes, but for the sort of "file system driver" discussed here, CSI is the way to go.
