### ISSUE TITLE
Template: Allow rolling restart for restart change_mode

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/nomad#10957]
### Proposal
Currently, `template` stanza won't trigger an `update` stanza if the template needs to be updated, which will lead to an unexpected downtime in some cases.

It was initially requested here: https://github.com/hashicorp/nomad/issues/2202
But that issue was closed, not sure why. I think it should remain open as a feature request unless Hashicorp is against implementing it.

4 years have passed - any changes that will be implemented?

**Comment by tino** [comment]
Let's concentrate the discussion here: https://github.com/hashicorp/nomad/issues/6151

**Comment by tgross** [comment]
Going to close this in lieu of #6151
