### ISSUE TITLE
nomad: plugin process exited

### ISSUE THREAD

**Issue by rajkashikar** [hashicorp/nomad#1095]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.3.1

### Operating system and Environment details
Linux  2.6.32-504.12.2.el6.x86_64
### Issue
Lots of /tmp/plugin* files. client in DEBUG mode shows, services getting registered and deregistered.
### Job file (if appropriate)
job "webserver" {
	datacenters = ["dc1"]
	type = "service"
	task "webserver" {
		driver = "raw_exec"
		config {
		command = "/usr/sbin/apachectl"
		args = ["start"]
			}

		service {
			name = "getwebby"
			port = 80
			check {
				type = "http"
				path = "/server-status"
				interval = 60
				timeout = 5
				}

			}    # Service ends

		resources {
			cpu = 25 # 500 Mhz
			memory = 250# 256MB
			  }

		constraint {
			attribute = "${attr.hostname}"
			value = "capistrano"
			}

			} # Task ends

		}  # Job ends

**Comment by rajkashikar** [comment]
Server config:
[root@eifweb-master]cat nomad.hcl
bind_addr = "171.70.42.104"
datacenter = "dc1"
name = "eifweb-master"
data_dir = "/tmp/nomad"
log_level="DEBUG"
server {
enabled = true
node_gc_threshold = "720h"
bootstrap_expect = "1"
	}
client {
	enabled = true
	options {
	"driver.raw_exec.enable" = "1"

		}
	}


### Client config 
region="global"
datacenter="dc1"
name="capistrano"
bind_addr = "171.70.42.76"
log_level="WARN"
data_dir = "/mnt/nomad1"
enable_syslog = true
syslog_facility="LOCAL6"
disable_update_check = true

client {
	network_interface = "br0"
	enabled = true
	servers = [ "171.70.42.104:4647"]
	options {
	consul.address = "127.0.0.1:8500"
	"driver.raw_exec.enable" = 1
		}
}

**Comment by dadgar** [comment]
Sorry would you mind clarifying the issue and maybe posting logs of the incorrect consul behavior.

**Comment by rajkashikar** [comment]
I am starting a web server via nomad (raw_exec driver). I run both server and clients in debug mode. I see messages on screen that the service gets registered and then quickly de-registered. it never makes to consul service discovery.
Parallely I am running consul with 5 masters. This part has been running for some time with 0.6.3. I am now introducing nomad in the mix.

---Here is the consul config file.. in case needed
{
"disable_update_check" : true,
"domain" : "eifweb",
"datacenter" : "dc1",
"data_dir" : "/tmp/consul",
"leave_on_terminate" : true,
"rejoin_after_leave" : true,
"retry_join" : ["171.70.42.187", "171.70.42.188", "171.70.42.189", "171.68.194.45", "171.68.194.71"],
"start_join" : ["171.70.42.187", "171.70.42.188", "171.70.42.189", "171.68.194.45", "171.68.194.71"]
}

------x-----

---Here is the nomad client log ---At the end of the day I have tons of 0 byte files under /tmp called /tmp/plugin57383*

    2016/04/15 11:33:25 [DEBUG] driver.raw_exec: started process with pid: 1203
    2016/04/15 11:33:25 [INFO] consul: registering service getwebby with consul.
    2016/04/15 11:33:25 [INFO] consul: deregistering service getwebby with consul
    2016/04/15 11:33:25 [DEBUG] plugin: /etc/consul.d/bin/nomad: plugin process exited
    2016/04/15 11:33:25 [INFO] client: task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" completed successfully
    2016/04/15 11:33:25 [INFO] client: Restarting task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" in 16.057416956s
    2016/04/15 11:33:25 [DEBUG] client: updated allocations at index 10307 (pulled 0) (filtered 6)
    2016/04/15 11:33:25 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
    2016/04/15 11:33:41 [DEBUG] plugin: starting plugin: /etc/consul.d/bin/nomad []string{"/etc/consul.d/bin/nomad", "executor", "/mnt/nomad1/alloc/87b7dee9-d60f-007c-cced-1fcf796e4b10/webserver/webserver-executor.out"}
    2016/04/15 11:33:41 [DEBUG] plugin: waiting for RPC address for: /etc/consul.d/bin/nomad
    2016/04/15 11:33:41 [DEBUG] plugin: nomad: 2016/04/15 11:33:41 [DEBUG] plugin: plugin address: unix /tmp/plugin886416460
    2016/04/15 11:33:41 [DEBUG] driver.raw_exec: started process with pid: 1242
    2016/04/15 11:33:41 [INFO] consul: registering service getwebby with consul.
    2016/04/15 11:33:41 [INFO] consul: deregistering service getwebby with consul
    2016/04/15 11:33:41 [DEBUG] plugin: /etc/consul.d/bin/nomad: plugin process exited
    2016/04/15 11:33:41 [INFO] client: task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" completed successfully
    2016/04/15 11:33:41 [INFO] client: Restarting task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" in 18.183101246s
    2016/04/15 11:33:41 [DEBUG] client: updated allocations at index 10308 (pulled 0) (filtered 6)
    2016/04/15 11:33:41 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
    2016/04/15 11:33:59 [DEBUG] plugin: starting plugin: /etc/consul.d/bin/nomad []string{"/etc/consul.d/bin/nomad", "executor", "/mnt/nomad1/alloc/87b7dee9-d60f-007c-cced-1fcf796e4b10/webserver/webserver-executor.out"}
    2016/04/15 11:33:59 [DEBUG] plugin: waiting for RPC address for: /etc/consul.d/bin/nomad
    2016/04/15 11:33:59 [DEBUG] plugin: nomad: 2016/04/15 11:33:59 [DEBUG] plugin: plugin address: unix /tmp/plugin834361568
    2016/04/15 11:33:59 [DEBUG] driver.raw_exec: started process with pid: 1267
    2016/04/15 11:33:59 [INFO] consul: registering service getwebby with consul.
    2016/04/15 11:33:59 [INFO] consul: deregistering service getwebby with consul
    2016/04/15 11:33:59 [DEBUG] plugin: /etc/consul.d/bin/nomad: plugin process exited
    2016/04/15 11:33:59 [INFO] client: task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" completed successfully
    2016/04/15 11:33:59 [INFO] client: Restarting task "webserver" for alloc "87b7dee9-d60f-007c-cced-1fcf796e4b10" in 25.567773409s
    2016/04/15 11:33:59 [DEBUG] client: updated allocations at index 10310 (pulled 0) (filtered 6)
    2016/04/15 11:33:59 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)

**Comment by rajkashikar** [comment]
https://github.com/hashicorp/nomad/labels/waiting-reply

**Comment by dadgar** [comment]
It looks like your task is finishing immediately. When a task starts we register it with Consul and when it finishes we deregister. You can see what is happening with the allocation using:
`nomad alloc-status <alloc-id>`

and look at the logs of the task with: `nomad fs cat <alloc-id> alloc/logs/<task-name>.<stdout/stderr>.0`

However, it is odd that the registration/deregistration happens immediately. Can you try using the newer RC of Nomad: https://releases.hashicorp.com/nomad/0.3.2-rc2/

**Comment by rajkashikar** [comment]
0.3.2-rc2 worked.
