### ISSUE TITLE
`NOMAD_CLI_NO_COLOR` env flag not working

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#10982]
### Nomad version
Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)

### Operating system and Environment details
Not relevant.

### Issue
While working on #10975 I noticed that `NOMAD_CLI_NO_COLOR` does not work at all. Supplying `-no-color` works. `main.go` takes `NOMAD_CLI_NO_COLOR` into account https://github.com/hashicorp/nomad/blob/6d00c688b3cd35e1f9d5c56011910646ad60e340/main.go#L99-L101 to configure the default UI colors. But `nomad plan` uses https://github.com/hashicorp/nomad/blob/6d00c688b3cd35e1f9d5c56011910646ad60e340/command/meta.go#L156-L162 which only cares about flags and not env vars. I am not sure what the best way of fixing is. Ie should the env vars override the flags or should they explicitly checked every time etc?

**Comment by jrasell** [comment]
Thanks for spotting this @apollo13 and taking the time to fill this issue with such detail!
