### ISSUE TITLE
Stopping an allocation seems to reschedule the job, even though rescheduling is disabled for job

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#10993]
### Nomad version

v1.0.9

### Operating system and Environment details

Amazon linux 2

### Issue

When I try to stop a batch job through the interface, it tells me that the job will be rescheduled to another client:

<img width="1158" alt="Screenshot 2021-08-02 at 23 12 27" src="https://user-images.githubusercontent.com/334273/127924915-941ede04-c0dd-4d73-b1d4-59aee2206296.png">

And it also seem to reschedule:

<img width="1187" alt="Screenshot 2021-08-02 at 23 17 49" src="https://user-images.githubusercontent.com/334273/127925096-a9f1022e-d2bc-4d3d-9cee-c0f6fdf7c128.png">

And this happens even though rescheduling is disabled in the task definition, notice that both restart-stanza and reschedule-stanzas are present:

```hcl
job "billetto-staging-console" {
  datacenters = ["<%= template_variables[:datacenter] %>"]

  type = "batch"

  parameterized {
    payload = "forbidden"
    meta_required = ["SLEEP_TTL", "CONTAINER_OWNER"]
  }

  group "group" {
    count = 1

    restart {
      attempts = 0
      mode = "fail"
    }
  
    reschedule {
      attempts = 0
      unlimited = false
    }

    ephemeral_disk {
      size = 300
    }

    task "console" {
      kill_timeout = "30s"
      driver = "docker"

      env {
      <% template_variables[:environment_variables].each do |ek, ev| -%>
        <%= ek %> = "<%= ev %>"
      <% end -%>
      }
    
      user = "root"

      config {
        image = "<%= image_name_and_version %>"

        labels {
          alloc_env = "staging"
        }

        command = "sleep"
        args = ["${NOMAD_META_SLEEP_TTL}"]

      <% if template_variables[:network_mode] -%>
        network_mode = "<%= template_variables[:network_mode] %>"
      <% end -%>
        dns_servers = ["<%= template_variables[:dns] %>"]
      }

      resources {
        cpu    = 1000 # MHz
        memory = 1500 # MB
        network {
          mbits = 10
        }
      }
    }
  }
}
```

### Reproduction steps

- Configure a batch job with disabled rescheduling.
- Try to stop job through interface
- See that the job is rescheduled.

#### Expected Result

- I don't want it to reschedule.

#### Actual Result

- It is rescheduled.

**Comment by kaspergrubbe** [comment]
It seems like using the cli would stop the job and do the correct thing: `nomad job stop <job-id>` I would assume the stop button in the web-interface would do the same thing.

**Comment by lgfa29** [comment]
Hi @kaspergrubbe,

From the screenshots you sent it seems like you are not stopping the job, but rather the allocation. The `reschedule` block is only applied when the allocation _fails_. In your case, through the UI, you manually stopped it, so it didn't fail.

To have stop the job via the UI, make sure you are two levels up in the UI, so `Jobs/billetto-production-console/dispatch-XXXXXXXXXXX-XXXX` in your case.

In there you will see the button that will stop the job, not the allocation:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/775380/130121749-8490dd79-fdc1-4bdc-9a26-b153fbd9785a.png">

I'm going to close this for now, but give it a try and let me know how it goes 🙂
