### ISSUE TITLE
Officially Supported OpenAPI Specification

### ISSUE THREAD

**Issue by ClayMav** [hashicorp/nomad#10998]
### Proposal

I propose a language agnostic Nomad API OpenAPI specification with support for all of the API features, as well as support for the event stream (though that part might have to be done as a hack or modified output files)

Nomad Clients are very sparse, the list covers a small number of the most popular languages, and in some cases (TypeScript), the library is not fully featured.
This rust crate attempted to solve this problem, but it is not possible for it to be consistently feature parity since they are a consumer of your API, not a creator.

### Use-cases

I would like to use a Nomad client in Typescript, look at the list https://www.nomadproject.io/api-docs/libraries-and-sdks, see that hostel is available. Incorporate hostel into my project, then realize in the middle of setting it up that it doesn't support volumes. If there was an OpenAPI specification, I would use a Typescript OpenAPI client generator and create the client.

### Attempted Solutions

I have attempted to use the specification that is supplied by the rust crate linked above, and it worked to some degree, but I had to manually implement the ndjson stream for events, and found the experience overall unsatisfactory.

**Comment by DerekStrickland** [comment]
Hi @ClayMav!  Thanks for being a part of the Nomad community!  I'm a recent hire on the Nomad team, and adding an OpenAPI specification is actually my first assignment! So, great timing on this request. I've got a microframework in place and it's worked so far for 3 endpoints. I'll be knocking out the other endpoints as quickly as I can. I've got a little branch clean-up to do, but once I do, I'll post the link here so you can try it out while it's in process. If you have any interest in helping with the implementation, let me know and I'll walk you through what's involved. At this point, it's just a lot of rote configuration of endpoints and writing unit tests.  It takes about 5 lines of code to configure each endpoint. That said, I'm sure there are edge cases I'm not handling yet and would love to involve you or anyone from the community that is interested in participating.

Regarding the event stream, my plan is actually to use the AsyncAPI specification (based on OpenAPI but for event-based endpoints). I started a spike on that last week, but it's secondary to getting the OpenAPI spec published. If you have any suggestions on an alternative tool to use or any opinions about AsyncAPI, I'd love to hear them. 

Again, thank you for using Nomad, and I'm really excited to be collaborating with you on this!

**Comment by ClayMav** [comment]
I'd be glad to help out, at the very least I can try to help implement the items necessary for my use case if they aren't in yet, and then obviously I can build some client and give it some real world tests. Glad to hear you are working on this!

**Comment by DerekStrickland** [comment]
Great!  I've got a good bit of code that you can use as examples. I've got it staged in this [draft PR](https://github.com/hashicorp/nomad/pull/11003) if you want an early look. I'll write up a CONTRIBUTING.md in the morning and add that to the openapi/spec-generator directory. It would be great if we coordinate on what your use case is so that we don't duplicate effort,  and so I can know what you're using Nomad for.

**Comment by ClayMav** [comment]
My use-case is primarily Nomad volumes and jobs, but I also use event streams. Basically, we are:
1. creating volumes
2. creating jobs with those volumes
3. listening to the event stream until we get the complete allocation
4.  changing some DNS records.

**Comment by DerekStrickland** [comment]
@ClayMav  Our [Nomad OpenAPI](https://github.com/hashicorp/nomad-openapi) repo is now launched.  Let me know if it has what you need.

**Comment by ClayMav** [comment]
I will spend some time getting it going and see how it works for me, thanks so much!

**Comment by lgfa29** [comment]
With [https://github.com/hashicorp/nomad-openapi](https://github.com/hashicorp/nomad-openapi) live (yay @DerekStrickland! 🎉) I'm going to close this issue. 

Any OpenAPI specific issues can be file against that repo.
