### ISSUE TITLE
network bridge mode,Can I use a local mirror for pause-amd64?

### ISSUE THREAD

**Issue by lialzm** [hashicorp/nomad#11014]
my config

```
    network {
      mode = "bridge"
      port "http" {
        to = 80
      }
      port "https" {
        to=443
      }
    }
```

my local image

```
gcr.io/google_containers/pause-amd64                              3.1         da86e6ba6ca1   3 years ago    742kB
```

but i get error,Because i can't access gcr.io

```
failed to setup alloc: pre-run hook "network" failed: failed to create network for alloc: Failed to pull `gcr.io/google_containers/pause-amd64:3.1`: API error (500): Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by jrasell** [comment]
Hi @lialzm; are you able to provide additional details regarding your setup as well as any log messages that could be useful? If the image is locally available where the job is running, the Docker driver should be able to use it without the need to pull it from the remote source.

**Comment by lialzm** [comment]
Hi @jrasell 

this repo is all my config

https://github.com/lialzm/nomad-demo

**Comment by lialzm** [comment]
Because my network is currently inaccessible gcr.io/google_containers/pause-amd64 ,so I use docker save and docker load this image ,but nomad is pull is still

**Comment by Adrien-Luxey** [comment]
I have the same issue using Consul Connect:

> failed to setup alloc: pre-run hook "network" failed: failed to create network for alloc: Failed to pull `gcr.io/google_containers/pause-amd64:3.1`: API error (500): Get "https://gcr.io/v2/": dial tcp [2a00:1450:400c:c06::52]:443: connect: connection refused

On my host or on my server, `curl https://gcr.io` fails with "can't connect, connection refused". Some "Is this site down?" websites consider gcr.io to be down, while others do not.

Still, after a simple change in my web-server config, I can't restart it: all my infrastructure is down.

**Comment by sanjeevkumarraob** [comment]
This needs to be addressed. The image doesn't use the cached image and every time it tries to connect to gcr.io which cannot be connected from a server.
