### ISSUE TITLE
Isolated exec driver + ulimit

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/nomad#1101]
### Nomad version
`Nomad v0.3.2-dev ('45114d9abdad2e698eb2830231bf77a095e47962')`

### Operating system and Environment details
Ubuntu 14.04 LTS on AWS

### Issue
Launching processes using the `exec` driver uses the default ulimit values

### Reproduction steps
1. Set the ulimit for open file handles to a non-default value on the host OS for the user running Nomad.
2. Submit the nomad job given below.
3. Fetch the allocation logs and observe the default file handles limit of 1024.

### Job file

```
job "ulimit-test" {
  datacenters = ["dc1"]
  type = "batch"
  group "ulimit" {
    task "ulimit" {
      driver = "exec"
      config {
        command = "/bin/bash"
        args = ["-c", "whoami; ulimit -a"]
      }
      resources {
      	cpu = 500
      }
    }
  }
}
```

**Comment by dadgar** [comment]
Nomad will not override the OS settings, so the user should be such that it has the proper ulimit set!
