### ISSUE TITLE
Handles leakage on Windows

### ISSUE THREAD

**Issue by a-zagaevskiy** [hashicorp/nomad#11026]
### Nomad version

Nomad v0.10.5

### Operating system and Environment details

Windows 10

### Issue

There is a leakage of process handlers on Windows. The source of leakage is somewhere in the agent process and connected with monitoring of task's logs. After few days of working there were over 2 million opened handlers detected with Process Explorer utility.

### Reproduction steps

Create a simple raw-exec task with activated monitoring of logs and keep it working few days. If you kill "nomad logmon" child processes purposely, the leakage in the agent stops.

Moreover, we've already found a bug within `go-plugin`, which causes this leakage:
https://github.com/hashicorp/go-plugin/blob/master/process_windows.go#L18-L28
Adding a deferred call of `syscall.CloseHandle(h)` fixes the issue.

**Comment by notnoop** [comment]
Wow! Thanks for finding and pointing out the cause of the bug! I'll follow up with go-plugin to ensure the handles get closed, and do some testing to see if there are any other leaks. Thank you so much for reaching out!
