### ISSUE TITLE
webui application banner

### ISSUE THREAD

**Issue by LukeMauldin** [hashicorp/nomad#11039]
### Proposal
Add a configurable application banner text/color in the webui of Nomad.  We run multiple nomad clusters, a "dev/test" cluster and a "production" cluster.  It would be helpful to be able to visually distinguish those clusters for the users so that a user will not accidentally perform an action in production that was meant for test.

### Use-cases
User A has access to the nomad test cluster and the nomad production cluster.  User A opens Nomad production cluster and has saved the access token so it logs in automatically.  User A stops a job in the production cluster thinking they are stopping a job in the test cluster and cause production outage.

### Attempted Solutions
None could be found.

**Comment by lgfa29** [comment]
Thanks for the suggestion @LukeMauldin! This is something that we've heard before and are tracking in #10813.

I'm going to close this one to keep the conversation centralized in one place. Feel free to 👍 and add any comments there.
