### ISSUE TITLE
Go API: Port.Value does not populate when using event.Allocation()

### ISSUE THREAD

**Issue by ClayMav** [hashicorp/nomad#11044]
### Nomad version
1.1.2

### Operating system and Environment details
Nomad running in Debian VM, go api running on MacOS

### Issue
The DynamicPorts Ports have all their "Value" fields turned into 0s when running event.Allocation()
This could be a simple mapstructure misconfiguration or something else.
https://github.com/hashicorp/nomad/blob/499fcebc42f733e7200df30ef9db76074b6c1bbc/api/resources.go#L101

### Reproduction steps
with Nomad go api, listen to event stream
With valid Allocation event (with Dynamic Ports visible through curl)
```
allocation, err := event.Allocation()
if err != nil {
        log.Fatal("Event allocation get failed")
}

log.Println(event.Payload["Allocation"]) // Sees the value
log.Println(allocation.Resources.Networks[0].DynamicPorts) // Value is now 0 in all ports
```

#### Expected Result
Value would be the same as the event Payload value

#### Actual Result
Value is always 0 for all Ports

### Job file (if appropriate)
N/A, all job files that require ports have this.

**Comment by ClayMav** [comment]
I see that the PR is in progress with no updates for a while - any chance this gets done soon?

**Comment by DerekStrickland** [comment]
Hi @ClayMav. I am so sorry that this got delayed.  I'll talk to the team today.  The code change was made in that WIP PR and was manually tested, but automated testing got complicated, I got side-tracked, and well, here we are. I sincerely apologize for that.
