### ISSUE TITLE
Test certs expire soon

### ISSUE THREAD

**Issue by benbuzbee** [hashicorp/nomad#11047]
Just a friendly reminder there are some checked in test certs that expire next month :) May or may not be impactful to your CI

e.g. 
https://github.com/hashicorp/nomad/blob/main/helper/tlsutil/testdata/ca-bad.pem

**Comment by jrasell** [comment]
Hi @benbuzbee and thanks a lot for pointing this out. I feel this would have certainly been a reactionary fix otherwise!
