### ISSUE TITLE
Ceph RBD not working properly on 1.1.3

### ISSUE THREAD

**Issue by henyxia** [hashicorp/nomad#11058]
### Nomad version
`Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)`

### Operating system and Environment details
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ cat /etc/apt/sources.list.d/hashicorp.list # installed from official deb repo
deb https://apt.releases.hashicorp.com buster main
```
Ceph:
```
$ ceph versions |jq .overall
{
  "ceph version 15.2.10 (27917a557cca91e4da407489bbaa64ad4352cc02) octopus (stable)": 6
}
```

### Issue
After upgrading nomad from 1.1.2 to 1.1.3, my storage plugins restarted and stoped working properly.
The controller and the node are still working but no container is able to use its rbd storage anymore.
The plugin's API seems to have an issue with an old job not running anymore.

The volume reports no placed allocations:
```
$ nomad volume status gitea-storage
ID                   = gitea-storage
Name                 = Gitea storage
External ID          = 0001-0024-27b2b208-e7e9-401f-b10e-d56ba367d717-0000000000000018-ad5e8967-e617-11eb-8388-0242ac110003
Plugin ID            = cephrbd
Provider             = rbd.csi.ceph.com
Version              = v3.3.1
Schedulable          = true
Controllers Healthy  = 1
Controllers Expected = 1
Nodes Healthy        = 1
Nodes Expected       = 1
Access Mode          = single-node-writer
Attachment Mode      = file-system
Mount Options        = <none>
Namespace            = default

Allocations
No allocations placed
```
But any attempt to use it (like with a deregister) fails:
```
$ nomad volume deregister gitea-storage
Error deregistering volume: Unexpected response code: 500 (volume in use: gitea-storage)
```

Also, I do not know if this requires a separate issue, but upgrading from `cephcsi` image from version `3.3.1` to `3.4.0` seems impossible as the node job refuse to start.

### Reproduction steps
This part is tricky.
Creating new volumes works properly but none are usable by containers.
Volumes are visible with `rbd list` though.

#### Expected Result
Job start properly and successfully mount the Ceph RBD volume.

#### Actual Result
Container is unable to start and report volume writer exhaustion:
`Constraint CSI volume gitea-storage has exhausted its available writer claims filtered 1 node`

### Job file
[gitea.job.txt](https://github.com/hashicorp/nomad/files/6988922/gitea.job.txt)

### Nomad Server logs
```
2021-08-15T23:17:35.169+0200 [ERROR] nomad.fsm: CSIVolumeDeregister failed: error="volume in use: gitea-storage"
2021-08-15T23:17:35.170+0200 [ERROR] http: request failed: method=DELETE path=/v1/volume/csi/gitea-storage?force=false error="volume in use: gitea-storage" code=500
```

**Comment by gregory112** [comment]
Your issue might be related with this: #10927 ?

**Comment by lgfa29** [comment]
Hi @henyxia, I think @gregory112 is correct and this seems related to #10927.

> Also, I do not know if this requires a separate issue, but upgrading from cephcsi image from version 3.3.1 to 3.4.0 seems impossible as the node job refuse to start.

Yes, please do create a new issue for this. If possible, please include the job file for the CSI plugin and any log message from their allocations.

I will close this one to keep the conversation focused on a single issue, but thank you very much for the report!

**Comment by henyxia** [comment]
Thanks for your responses!
I can confirm the solution proposed in #10927 works properly!
