### ISSUE TITLE
Clarification on `data_dir` in the documentation and/or in the error output

### ISSUE THREAD

**Issue by yaroslav-007** [hashicorp/nomad#11059]
### Proposal
There are two `data_dir` parameters in the documentation. One in server stanza (https://www.nomadproject.io/docs/configuration/server#server-parameters) and one in the general section (https://www.nomadproject.io/docs/configuration#general-parameters).

From my perspective the documentation could make more clear difference between them. Since the one in server stanza is optional and the one in general section is mandatory. For novice user that might be confusing (if he doesn't make difference between agent data and server data for example) and he might think the one in server stanza is enough. He will get error: `==> Must specify data directory` which will not point him that `data_dir` is missing in general section.

**Comment by jrasell** [comment]
Hi @yaroslav-007 and thanks for raising this!
