### ISSUE TITLE
Logfiles are always generated with a '-{timestamp}.log' suffix?

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#11061]
According to the docs ([here](https://www.nomadproject.io/docs/configuration#log_file) and [here](https://www.nomadproject.io/docs/configuration/audit#path)) it should be possible to configure Nomad to output agent logs and audit logs to a **specific** file. This seems to be _slightly_ broken as I only ever see logs being generated with a  `-{timestamp}.log` suffix ?

It **does** respect the file name (see the examples below) ... but it always adds the `-{timestamp}.log` suffix even though this should, according to the [docs](https://www.nomadproject.io/docs/configuration/audit#path),  only happen upon file rotation.

Nomad version is `v1.1.2+ent`.

Configuration of the ordinary agent logs in nomad.hcl :point_down: 

```
# log settings
...
log_file  = "/var/log/nomad.log"
...
```

Configuration of the Enterprise audit logs in nomad.hcl :point_down: 

```  
sink "audit" {
    ...
    path   = "/var/log/nomad_audit.log"
    ...
}
```

The result of this config ...

```
root@xxx:/var/log# ls -alh /var/log/nomad*
-rw-r----- 1 root root 8.3K Aug 18 11:22 /var/log/nomad-1629283904922740456.log
-rw-r----- 1 root root 7.7K Aug 18 11:22 /var/log/nomad-1629285757963036138.log
-rw------- 1 root root 2.1M Aug 18 11:22 /var/log/nomad_audit-1629283907665719584.log
-rw------- 1 root root 1.1M Aug 18 11:42 /var/log/nomad_audit-1629285759194447584.log

```

Likewise, trying to change the file permissions for the audit log file (per these [instructions](https://www.nomadproject.io/docs/configuration/audit#mode)) does not seem to work as the files are **always** created with `0600` - I am not sure if the 2 issues are related but I thought I might as well mention it here.

**Comment by lgfa29** [comment]
Thanks @henrikjohansen. The timestamped files are part of the log rotation process, but if I understand correctly, what you would expect to see is that `log_file` would set the name of the current active log?

So in your example, you would want to see:

```console
root@xxx:/var/log# ls -alh /var/log/nomad*
-rw-r----- 1 root root 8.3K Aug 18 11:22 /var/log/nomad.log
-rw-r----- 1 root root 7.7K Aug 18 11:22 /var/log/nomad-1629285757963036138.log
-rw------- 1 root root 2.1M Aug 18 11:22 /var/log/nomad_audit.log
-rw------- 1 root root 1.1M Aug 18 11:42 /var/log/nomad_audit-1629285759194447584.log
```

**Comment by henrikjohansen** [comment]
Hi @lgfa29. 

Correct - the [audit docs](https://www.nomadproject.io/docs/configuration/audit#path) at least give the impression that this should be the case:


> By default Nomad will use its configured data_dir for a combined path of /data_dir/audit/audit.log. If rotate_bytes or rotate_duration are set file rotation will occur. In this case the filename will be post-fixed with a timestamp "filename-{timestamp}.log"

**Comment by shantanugadgil** [comment]
possibly related to https://github.com/hashicorp/nomad/issues/9582 ?

**Comment by lgfa29** [comment]
Thanks @shantanugadgil! That does seem like the same issue with regards to `log_level`.

@henrikjohansen for audit logs we use [go-eventlogger](https://github.com/hashicorp/go-eventlogger), which is also used by other HashiCorp tools, so a change there could impact them as well. Would you mind opening an issue for the file name format there?

Also, for the file mode, this feature was [recently added](https://github.com/hashicorp/nomad/pull/10916) in `1.1.3+ent`. Would you mind checking using that version instead?

Thanks!
