### ISSUE TITLE
cli: add extra flag to specify timeout/waittime with the new -monitor on run/eval/deployment feature

### ISSUE THREAD

**Issue by 42wim** [hashicorp/nomad#11068]
### Proposal

Add an option to increase the WaitTime in the deployment monitor: https://github.com/hashicorp/nomad/blob/main/command/deployment_status.go#L237

The current implementation in https://github.com/hashicorp/nomad/pull/10661 works fine for CLI / tty but for running in a CI (eg jenkins) this results in printing new data every 2 seconds because they don't support a erase line.

In this kind environment you would only need output when something actually changes, which works fine if we increase the WaitTime. State changes will still be shown immediately when a new index is reached.

### Use-cases

To decrease the output spamming when running in CI environments.

### Attempted Solutions

Works fine in our environment when WaitTime is set to 30 seconds

**Comment by tgross** [comment]
> The current implementation in https://github.com/hashicorp/nomad/pull/10661 works fine for CLI / tty but for running in a CI (eg jenkins) this results in printing new data every 2 seconds because they don't support a erase line.

For environments like Jenkins we should be detecting that there's no tty and then simply not running the monitor. But I suspect Jenkins is doing something janky here, as I seem to recall some weird behaviors around tty's last I ran it (which is admittedly years ago now).

In any case, apologies for not responding to this feature request earlier @42wim. I'll mark it for roadmapping but it's also a fairly small intervention so I'll mark it as a good first issue for new contributors as well.

**Comment by jdockerty** [comment]
@tgross Hopefully this one hasn't been forgotten about :eyes: I've taken a bit of a "work in progress" shot at it in a linked PR.

Any feedback/help is much appreciated for my first contribution to Nomad :blush:

**Comment by tgross** [comment]
Thanks @jdockerty! I've marked the PR so that it gets triaged for review.

**Comment by tgross** [comment]
This has been implemented in https://github.com/hashicorp/nomad/pull/15262, which we'll ship in the next regular version of Nomad (likely 1.4.4)
