### ISSUE TITLE
Add meta field to server config

### ISSUE THREAD

**Issue by billyshambrook** [hashicorp/nomad#1108]
Currently you can add arbitrary metadata to Nomad Clients in the meta field in the client config. Would it be possible to get the same thing in the server config? We have the need to have a long and short format for the region name, and we could put one of these in the meta field. Thanks.

**Comment by dadgar** [comment]
How would you be accessing/using the servers meta data?

**Comment by billyshambrook** [comment]
Ideally through the members endpoint.

**Comment by dadgar** [comment]
Can you describe the use case?

**Comment by billyshambrook** [comment]
Hey @dadgar, our setup has changed and we no longer require this field. Will close this for now and revisit it if our user case changes. Thanks
