### ISSUE TITLE
Expose oom_score_adj on a per-task basis

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#11087]
### Problem
Nomad 1.1 adding [Memory Oversubscription](https://www.nomadproject.io/docs/job-specification/resources#memory-oversubscription) which allows tasks to set a soft and hard limit for their memory usage. When a system's memory is exhausted and a process needs to be oom killed, the higher a process is over its soft limit, the more likely it is to be killed.

However, this logic does not take into account the priorities of the application being run. Just because a task is using more memory does not make it "less valuable" to be running.

#### Proposal: resources.oom_score_adj

Add an `oom_score_adj` field to [`resources`](https://www.nomadproject.io/docs/job-specification/resources) that *only accepts positive values.* A task can mark itself as *more likely* to be OOM killed, but not less likely.

#### Abandoned Idea: Use Priority

It's tempting to make `job.priority` implicitly impact `oom_score_adj` since it is already used by preemption to stop lower priority jobs.

However, this impacts all tasks for a job. You may want a flaky log shipping sidecar to get killed (and restarted) before _anything_ else on a system.

So while implicitly using `priority` might be valuable in the future, allowing users to explicitly demote some tasks is a necessary first step.

**Comment by pkazmierczak** [comment]
With updates to [raw_exec](https://github.com/hashicorp/nomad/pull/23308), [exec2](https://github.com/hashicorp/nomad-driver-exec2/pull/40) and [docker](https://github.com/hashicorp/nomad/pull/23297), I consider this issue closed for now. Should we want to revisit putting this in the `resources` block, we have https://github.com/hashicorp/nomad/pull/23259 as a good starting point.
