### ISSUE TITLE
http   /v1/client/fs/cat/  Invalid method 

### ISSUE THREAD

**Issue by liuq4360** [hashicorp/nomad#1109]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
v.0.3.1

### Operating system and Environment details
centos7.1

### Issue
[question] when i use http /v1/client/fs/cat/  to get job logs, i get "invalid method" respond, but the ls and stat api is ok, i use "nomad fs cat " command can get logs, is there some bugs in the cat http api?
### Nomad Client logs (if appropriate)

    2016/04/19 18:14:37 [ERR] http: Request /v1/client/fs/cat/9e8d8630-ea54-bbd3-5346-2e53e3bb3c0e?path=alloc/logs/pi.stderr.0, error: Invalid method
    2016/04/19 18:14:37 [DEBUG] http: Request /v1/client/fs/cat/9e8d8630-ea54-bbd3-5346-2e53e3bb3c0e?path=alloc/logs/pi.stderr.0 (169.742µs)

**Comment by dadgar** [comment]
Hey sorry the documentation was slightly ahead of the code there! Should be resolved in 0.3.2

**Comment by liuq4360** [comment]
ok，thanks！






------------------


刘强








 
 
 
------------------ Original ------------------
