### ISSUE TITLE
Raw_exec does not shut down child processes on nomad stop

### ISSUE THREAD

**Issue by FRosner** [hashicorp/nomad#1110]
### Problem

I am using the raw_exec driver of nomad to start an application through a shellscript. When I run `nomad stop` it tells me that the job was stopped. However, the process is still running.

After investigating, I saw that the shellscript starts another shellscript (child process). Nomad sends SIGINT to the parent, which has no effect on the child processes.

### Example (without nomad)

- `echo "read" > test.sh`
- `echo "./test.sh" > runtest.sh`
- `chmod +x test.sh`
- `chmod +x runtest.sh`
- `./runtest.sh`
- `ps aux | grep test #get process id`
- `kill -2 <pid of runtest.sh>`
- `???`
- nothing happens

When I use `kill -2 -<pid of runtest.sh>` instead (mind the dash), it works.

### Solution

Can't we send the SIGINT to the process and all its child processes, instead?

**Comment by dadgar** [comment]
Hey thanks for reporting this. We are aware of this but don't quite consider it an issue. Your application should forward the signal to its children. The reason we don't do as you suggested is that it can break applications that use multiple processes. For example a manager process could use the SIGINT to signal to its children to clean-up as part of the exit procedure. If we send it, it does not allow the manager to capture and handle the signal as it sees fit

**Comment by FRosner** [comment]
Thank you @dadgar. I was hoping for a quick and useful answer and I was not disappointed! 💃 

I will take a look if I can make it work.

**Comment by hmalphettes** [comment]
@FRosner my apologies for commenting on this old issue.
Did you manage to make it work?

@dadgar I tried everything I knew and everything I could find.
The only one that will stop the process correctly is exec based:
```
driver = "raw_exec"
config {
  command = "/bin/bash"
  args    = ["-x", "-e", "local/start.sh"]
}
...
template {
        data = <<EOH
#!/bin/bash
exec sleep 123000
EOH
destination   = "local/start.sh"
```

Specifically, I could not make `trap` work when it goes through `nomad stop`:
```
trap "echo 'ok trap was activated' > /tmp/traplog; pkill sleep" SIGINT SIGTERM EXIT
sleep 123000
```
However I would need to run some cleanup script when the job is stopped.

`raw_exec` is a fantastic way to introduce big enterprise to a cluster scheduler without requiring root access, without installing docker and without user namespaces.

I am using https://github.com/indigo-dc/udocker which is good enough to run my containers to do that everything in user space. It seems to survive being run through an exec and receiving a SIGINT.

Would you guys be looking at supporting pre/post hooks as suggested here: https://github.com/hashicorp/nomad/issues/1061

Is there something else I should try?

Many thanks for your help!

**Comment by FRosner** [comment]
I think instead of sleep you should wait for the process @hmalphettes? Otherwise your script will not  exit, will it?

https://github.com/FRosner/nomad-docker-wrapper/blob/6c699b0f8fa0cbee63e59a96b08e1f7bc371ca70/nomad-docker-wrapper#L56

Don't mind the fact that it uses Docker but look at the wait. Anyway this script went  through a lot of iterations and is is far away from working in 100% of the different cases of things crashing, sending signals or anything. But it's the best we have :-D

I apologize if what I am saying doesn't make sense, probably I didn't get your question :( Could you maybe provide both your job file and start script?

**Comment by dadgar** [comment]
@hmalphettes Here you go. Here is an example using trap.

```
job "example" {
  datacenters = ["dc1"]
  type = "batch"
  group "test" {
    task "test" {
      driver = "raw_exec"

      config {
        command = "/bin/bash"
        args = ["local/start.sh"]
      }

       template {
	 data = <<EOH
_term() { 
    echo "Caught SIGINT signal!" 
    kill -TERM "$child" 2>/dev/null
}

trap _term SIGINT
sleep 10000 &

child=$! 
wait "$child"
     EOH
     destination   = "local/start.sh"
       }
    }
  }
}
```

```
$ nomad run example.nomad
==> Monitoring evaluation "13d5fe6d"
    Evaluation triggered by job "example"
    Allocation "7fcf92bc" created: node "01068df2", group "test"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "13d5fe6d" finished with status "complete"

$ nomad stop e
Are you sure you want to stop job "example"? [y/N] y
==> Monitoring evaluation "f7776138"
    Evaluation triggered by job "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "f7776138" finished with status "complete"

$ nomad logs 7f
Caught SIGINT signal!
```

**Comment by hmalphettes** [comment]
@dadgar and @FRosner many thanks to both of you, very much appreciated.
Trying!

**Comment by hmalphettes** [comment]
Works wonderfully @dadgar @FRosner !

`udocker` forks to call `proot` which itself for some of my containers will run some processes in the brackground and some others in the foreground.

To get a `docker stop` like behavior I ended up wrapping `bash` with `setsid` and killing the whole session at once.
 
```
job "example" {
  datacenters = ["dc1"]
  type = "batch"
  group "test" {
    task "test" {
      driver = "raw_exec"

      config {
        command = "/usr/bin/setsid"
        args = ["/bin/bash", "-x", "local/start.sh"]
      }

       template {
	 data = <<EOH
_term() { 
    echo "Caught SIGINT signal!" 
    kill -HUP -$$
}

trap _term SIGINT

# in my case: exec udocker run ... &
sleep 10000 &

child=$! 
wait "$child"
     EOH
     destination   = "local/start.sh"
       }
    }
  }
}
```
Cheers!
