### ISSUE TITLE
Restarting a job via the UI occasionally places job in the wrong region

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/nomad#11104]
### Nomad version
1.0.4

### Operating system and Environment details
Ubuntu 16.04, 18.04, 20

### Issue
We run 3 Nomad clusters, federated together. Occasionally when restarting a job via the UI (stop/start) the job is placed in the wrong region. For example, if the 'default' on loading the UI is "region A", when selecting "region B" from the dropdown and restarting a job, it will be placed in "region A", even if the job definition has the region set to "region B". 

### Reproduction steps
Set up 2 clusters, join them together, repeat steps above.

#### Expected Result
Job to be placed in the proper region

#### Actual Result
Job ending up in a different region

**Comment by lgfa29** [comment]
Hi @benvanstaveren 👋 

I am trying to reproduce the issue, but no luck so far.

Would it be possible to share a sample job file? Do you run the same in both regions?

Thanks!

**Comment by benvanstaveren** [comment]
Bit hard to share a job file at the moment; the thing is this: the job in question has a region defined as "regionA" with 3 datacenters, DC1, DC2, and DC3. This is basically correct. If I stop it in the UI, and then start it again, sometimes the job will appear in the cluster that is in "regionB" - with different datacenters. 

The only thing these nomad clusters have in common is that they share the same Consul cluster (regionA is a legacy setup, regionB is our new setup) - but the configuration is set properly for this (i.e. the old cluster's nodes and servers register in consul as nomad-legacy).

This also only happens when working via the UI.

**Comment by benvanstaveren** [comment]
And here we are nearly 3 years later; this error hasn't occurred since, well, a few years now. I'll close it because, well, it's been ages! :)
