### ISSUE TITLE
UI: Add a view to show all evaluations (blocked or otherwise) to the Nomad UI

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#11122]
### Proposal

Add a view that lists all evaluations (paginated?), with a filter for blocked evaluations. Then click through to an evaluation to show _why_ that evaluation is currently blocked.

### Use-cases

Platform maintainers with thousands of jobs cannot quickly view what evaluations are not being turned into placed allocations. This would allow platform maintainers to have a system-level view as to why certain deployments are not completing.

### Attempted Solutions

The current alternative is to use hashi-ui to list these, but that makes the Nomad UI slightly less compelling for end-users.

**Comment by lgfa29** [comment]
Thank you @josegonzalez, this sounds like a good idea 🙂

**Comment by ChaiWithJai** [comment]
@josegonzalez could we see some screenshots of you using `hashi-ui` to solve this? We're currently thinking through this now and would love to see this.

**Comment by josegonzalez** [comment]
I posted them in our shared slack channel with hashicorp, is that fine?
