### ISSUE TITLE
When executing parameterized job with namespace applied in ui, “Not Found”

### ISSUE THREAD

**Issue by Great-Stone** [hashicorp/nomad#11121]
### Nomad version
Nomad v1.1.4+ent (fbad2c4f1c135306ecd6d9cd794508fbaaf0c4de)

### Operating system and Environment details
Ubuntu 18.04.5 LTS

### Issue
I checked the update to be able to run parameterized jobs in the UI. It works fine in the default namespace, but when you create a custom namespace and run the job in the ui, the “Not Found” page is displayed. When I select all namespaces(*) in the UI and select the corresponding job I can see a list.

### Reproduction steps
I used the following example:
https://github.com/hashicorp/nomad-autoscaler-demos/tree/main/vagrant/dynamic-app-sizing

- Create a "scale" namespace and start a parameterized job.
- When dispatching from UI, "Not Found" page is displayed
- If you select the namespace as all(*) in the Job UI and select the job, the contents are displayed.
- Job created with default namespace is normal

#### Expected Result
When a parameterized job to which the namespace is applied is dispatched from the UI, the job UI to be performed should appear normally.

#### Actual Result
"Not Found" Page

### Job file (if appropriate)

```hcl
job "das-load-test" {
  datacenters = ["hashistack"]
  namespace = "scale"
  type        = "batch"

  parameterized {
    payload       = "optional"
    meta_optional = ["requests", "clients"]
  }

  group "redis-benchmark" {
    task "redis-benchmark" {
      driver = "docker"

      config {
        image   = "redis:6.0"
        command = "redis-benchmark"

        args = [
          "-h",
          "${HOST}",
          "-p",
          "${PORT}",
          "-n",
          "${REQUESTS}",
          "-c",
          "${CLIENTS}",
        ]
      }

      template {
        destination = "secrets/env.txt"
        env         = true

        data = <<EOF
{{ with service "redis-lb" }}{{ with index . 0 -}}
HOST={{.Address}}
PORT={{.Port}}
{{- end }}{{ end }}
REQUESTS={{ or (env "NOMAD_META_requests") "100000" }}
CLIENTS={{  or (env "NOMAD_META_clients") "50" }}
EOF
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
```

**Comment by lgfa29** [comment]
Thank you @Great-Stone.

I have a PR with a fix that will be available in the next release.
