### ISSUE TITLE
Downloading artifact hosted in S3 returns a 403 despite IAM role being properly configured. 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#1113]
### Nomad version
Output from `nomad version`
0.3.1
### Operating system and Environment details
Linux

### Issue
Downloading artifact hosted in S3 returns a 403 despite IAM role being properly configured. 

### Reproduction steps
1. Host a file in a private S3 bucket
2. Configure an EC2 instance with an IAM role that allows getting files from the bucket created in 1.
3. Schedule a nomad job with an artifact pointing to the mentioned file.

**Comment by c4milo** [comment]
I also reported this issue at https://github.com/hashicorp/go-getter/issues/22

**Comment by dadgar** [comment]
@c4milo I just vendored the change so if you build from master we can see if this is resolved 👍

**Comment by c4milo** [comment]
@dadgar works well. Thank you Alex!

**Comment by c4milo** [comment]
@dadgar, I'm seeing this problem again with 0.4.0

**Comment by c4milo** [comment]
To make sure it wasn't my fault, I manually tested using https://github.com/rlmcpherson/s3gof3r and it downloaded the artifacts correctly. However, nomad does not and returns the following: 

![](https://cldup.com/wmp2zdpat6.png)

**Comment by dadgar** [comment]
@c4milo Did anything change on your end since you marked it as closed? We haven't changed go-getter so wondering if there is another underlying bug in that library

**Comment by c4milo** [comment]
@dadgar I haven't changed any of my configurations. I only upgraded nomad to the latest changes in master branch and redeployed it.

**Comment by c4milo** [comment]
oh wait, I think the URL format for artifacts caught me again: 

Instead of: mybucket.s3.amazonaws.com/containers/vault.tar.gz

I kept using https://mybucket.s3.amazonaws.com/containers/vault.tar.gz

**Comment by c4milo** [comment]
I'm closing this one in favor of https://github.com/hashicorp/nomad/issues/1219
