### ISSUE TITLE
jobspec: expose the hcl2 strict config parameter for user toggling

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#11164]
When running plan/run/validate commands on job specification files that use hclv2 rendering, users may wish to pass generic variables files which include variables not used by the job. Currently, Nomad parsing with return an error as override variables must be matched with a variable definition in the job specification file.

Internally, the jobspec2 parsing includes a [strict config parameter](https://github.com/hashicorp/nomad/blob/508c259207522edcb6a6b49c8067049ea49d6097/jobspec2/parse.go#L72) which can defined whether these undefined variable occurrences are treated as an error or a warning. This currently is not exposed to users to change the behaviour, however, should be considered, to cover such use cases. 

Opened as a result of discussion within #11149

**Comment by apollo13** [comment]
Thanks for opening this. I am wondering if changing the default to `strict=false` and not adding a cli option would be an option. More code means more complexity and personally I cannot imagine that people rely on the behavior of `strict=true`. 

If you think simply changing the default is not an option, please let me know how the env variable / cli flag should be named and I'll try to come up with a PR.
