### ISSUE TITLE
Consul Ingress Listener protocols

### ISSUE THREAD

**Issue by sigilion** [hashicorp/nomad#11169]
### Proposal
I believe the protocol list [here](https://github.com/hashicorp/nomad/blob/b2b9013e524ca24802025b017b4bebbdb5afee64/nomad/structs/services.go#L1818 ) is no longer up to date, according to [the consul docs](https://github.com/hashicorp/nomad/blob/b2b9013e524ca24802025b017b4bebbdb5afee64/nomad/structs/services.go#L1818) the protocol can also be "grpc" or "http2"

### Use-cases
Ingress gateways for grpc and http2 connections

**Comment by lgfa29** [comment]
Thanks for the report @sigilion. I've opened a PR to update the list of valid protocols.
