### ISSUE TITLE
LinkSpeed Detection on Windows includes all PowerShell profile output for each interface

### ISSUE THREAD

**Issue by randomchance** [hashicorp/nomad#11171]
### Nomad version
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)

### Operating system and Environment details

WindowsProductName     :  Windows 10 Enterprise 
WindowsCurrentVersion   :  6.3 
WindowsVersion               :  1909 

### Issue

During agent startup (tested using the -dev option) any powershell profile output is included in the string parsed to determine link speed.  
This causes the following:
1. LinkSpeed detection fails. This may be impacting link detection in general, I'm not sure.
2. The startup logs are very cluttered. 
3. Startup is delayed by an additional 8-20 seconds 
4. It's a complicating factor if you are new to Nomad and trying to ensure you have everthing setup correctly.

### Reproduction steps

Add something to your powershell profile that outputs to the host, such as `"User: $env:USERNAME"`

Start Nomad:

```
nomad agent -dev -bind 0.0.0.0 -log-level INFO -network-interface="vEthernet (WiredNetwork)" 
```

> Note that specifiing the network speed has no impact on the result:

```
nomad agent -dev -bind 0.0.0.0 -log-level INFO -network-interface="vEthernet (WiredNetwork)" -network-speed=1024
```

#### Expected Result

Network link speed / interface fingerprint detection works, and doesn't load the powershell profile for each interface.

#### Actual Result

This is logged for each interface - obviously if I didnot have any text output in my Powershell profile this would not be a problem, but you should probably be using the `-NoProfile` option for powershell anyway to cut down on execution time, resources, and environment contamination. 

> Note that the verbose ouput is from me forcing it via `Write-Verbose -Verbose $Text`
```
2021-09-10T17:38:42.654-0400 [WARN] client.fingerprint_mgr.network: couldn't split LinkSpeed output: output="VERBOSE: Importing functions from: ***********.ps1
VERBOSE: Importing functions from: *************.ps1
VERBOSE: Importing functions from: ********.ps1
VERBOSE: Importing functions from: **************.ps1
VERBOSE: Importing functions from: ****************.ps1
VERBOSE: Importing functions from: **************.ps1


User: *******
Computer: *******


1 Gbps"

<Repeat for all 7 interfaces (docker+Hyper-V)>

    2021-09-10T17:38:42.654-0400 [DEBUG] client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: mbits=1000
    2021-09-10T17:38:46.670-0400 [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault period=15s
```

### Nomad Server logs 

I can produce the full logs if needed, but I'll need to actually read and possibly sanitize them before hand so I wanted to be sure it was required first.

**Comment by lgfa29** [comment]
Thank you for the report and for the tip about `-NoProfile` @randomchance 🙂 . 

I have a fix for this in #11183.
