### ISSUE TITLE
Allow specifying a namespace within a CSI volume registration file

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/nomad#11196]
### Proposal
Currently, the only way to specify a CSI Volume's namespace is by adding the `-namespace=` flag in the `nomad volume create` command.

Allowing to specify the namespace within the volume spec file would make the creation of a new CSI volume consistent with submitting a Nomad job as well as prevent accidentally registering a volume in a namespace that differs from the namespace of the job the volume is intended to be used with.

Example:
```
type            = "csi"
id              = "metrics_prometheus"
name            = "metrics_prometheus"
namespace       = "thunderdome"
access_mode     = "single-node-writer"
attachment_mode = "file-system"
plugin_id       = "cinder-csi"

capacity_max = "5G"
capacity_min = "5G"

capability {  
  access_mode     = "single-node-writer"  
  attachment_mode = "file-system"
}

mount_options {
  fs_type = "ext4"
}
```

### Use-cases
Allowing the volume specification to be more declarative and consistent with the jobspecs they are accompanying.  

### Attempted Solutions
N/A

**Comment by DerekStrickland** [comment]
Hi @rigrassm,

Thanks for using Nomad!

I'm currently taking a look into what it will take to implement this. We'll update this issue as more details emerge.

Thanks,

Derek and the Nomad Team

**Comment by tgross** [comment]
Will be fixed in https://github.com/hashicorp/nomad/pull/12400, planned to ship in Nomad 1.3.0. As it turns out, most required plumbing was already done, we just needed to fix one case where it was getting overridden in the RPC handler and the rest was testing and docs.
