### ISSUE TITLE
Option to show url with `nomad ui -authenticate` 

### ISSUE THREAD

**Issue by yaroot** [hashicorp/nomad#11193]
### Proposal

Option to show url with `nomad ui -authenticate` instead of opening it directly in the default browser (like `-show-url` or `-no-open`)

### Use-cases

- I use different browser profiles for different things
- with tmux sometimes it doesn't work (the cli just hangs)

### Attempted Solutions

open the web ui manually and copy/paste the token

**Comment by DerekStrickland** [comment]
Hi @yaroot,

Thanks for using Nomad! 

This does seem like a nice convenience feature.  Do you think this is something you might be willing to submit a PR for?

Thanks,

Derek and the Nomad Team
