### ISSUE TITLE
Wildcard Namespace selector (namespace='*') for CSI Volumes does not return any results

### ISSUE THREAD

**Issue by rigrassm** [hashicorp/nomad#11200]
### Nomad version
```shell
 ➜  nomad version                    
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)
```

### Operating system and Environment details
```shell
 ➜ awk -F'=' '/PRETTY_NAME/ {print $2}' /etc/os-release 
"Ubuntu 20.04.3 LTS"
```
### Issue
The wildcard namespace selector ('*') does not list CSI volumes from all namespaces. It appears to be treating it as a specific namespace as it doesn't return any volumes from any namespace (including the default). This happens both in the Nomad UI as well as from the command line.

```shell
 ➜ nomad volume status -namespace=default
Container Storage Interface
ID                   Name                 Plugin ID   Schedulable  Access Mode
metrics_prometheus   metrics_prometheus   cinder-csi  true         single-node-writer
tf_registry          tf_registry          cinder-csi  true         single-node-writer
tf_registry_mongodb  tf_registry_mongodb  cinder-csi  true         single-node-writer
```

```shell
➜ nomad volume status -namespace=awesomes
Container Storage Interface
ID                Name              Plugin ID   Schedulable  Access Mode
metrics_influxdb  metrics_influxdb  cinder-csi  true         single-node-writer
```

```shell
 ➜ nomad volume status -namespace='*'
Container Storage Interface
No CSI volumes
```
### Reproduction steps

1. Spin up a Nomad Server and Client (With ACL's enabled, have not tested without ACL's).
2. Create an additional Namespace
3. Deploy a CSI plugin
4. Create 2 CSI volumes, one in the default namespace and the other in the created namespace.
5. Run the `nomad volume status` command specifying each namespace separately and notice the volumes appear as expected.
6. Run the `nomad volume status -namespace='*'` command and see that it returns that there are no volumes.

#### Expected Result
The `nomad volume status -namespace='*'` command should output all volumes from all namespaces

#### Actual Result
The `nomad volume status -namespace='*'` does not return any volumes

### Nomad Server logs (if appropriate)
Can provide upon request

### Nomad Client logs (if appropriate)
N/A

### Nomad UI Screenshots
![default-namespace](https://user-images.githubusercontent.com/17223437/133825596-7f611019-a28d-45d8-ada1-82ab2a1a1cc0.png)
![non-default-namespace](https://user-images.githubusercontent.com/17223437/133825595-5ea65cbe-3cd7-4d62-abe6-50715cddeb70.png)
![wildcard-ui](https://user-images.githubusercontent.com/17223437/133825593-504f0bb2-2b1d-4725-ad46-96a8a68920c5.png)

**Comment by lgfa29** [comment]
Hi @rigrassm, thanks for the detailed report. 

This is a known missing feature of the API. The [original work](https://github.com/hashicorp/nomad/pull/8192) to add the `*` namespace was focused on jobs and allocations. #7341 is the issue that involves adding this operator to other endpoints as well. Once this option is available via the API, the UI and CLI can start levering it.

I will close this one to keep the discussion there. Feel free to 👍 that issue or let us know if there's anything missing.
