### ISSUE TITLE
ui: Search box not finding dispatch job

### ISSUE THREAD

**Issue by janet** [hashicorp/nomad#11219]
Hello! 👋  Been loving the dispatch parameterized job and wanted to mention something I noticed in the latest version. Thank you!

### Nomad version
1.1.4+ent

### Operating system and Environment details
AWS

### Issue
When I type in the nomad job id of a dispatched parameterized job, the search bar says "no results found". I am able to navigate to the page with the same parameterized job. In a previous version, `1.0.4+ent`, I was able to put the job id in the search bar and see a result that hyperlinked directly to the job.

### Reproduction steps
1. Dispatch a parameterized job
2. Search for the job by ID by typing it in the Nomad UI search box
3. Search results with "No match"

#### Expected Result
3. Search results with a link to the parameterized job

#### Actual Result
3. Search results with "No match"

**Comment by DerekStrickland** [comment]
Thanks for letting us know about this @janet!  We'll look into this and update you as soon as we can.

**Comment by DerekStrickland** [comment]
Hi @janet ,

I've got a Nomad test agent at 1.1.4+ent running. I've submitted a parameterized job named `template`, then I dispatched it, and when I search I see the following.

![image](https://user-images.githubusercontent.com/1111455/134586218-30b40fe0-11ae-465a-8324-9f3e4957190d.png)


Is this not what you see? Am I testing this correctly? Can you post your job file and the set of CLI commands you are running?

- Derek
