### ISSUE TITLE
nomad agent does not show configured `host_network`

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#11223]
### Nomad version
Nomad v1.1.5 (117a23d2cdf26a1837b21c84f30c8c0f3441e927)

### Operating system and Environment details
Amazon Linux 2

### Issue
From a usability perspective, I couldn't find a way of listing the configured `host_network` on the client machine.
Commands that I have tried (on the machine in question):
* nomad node status -self -verbose
* nomad node status -self -json

none of the above commands contain any clue about the `host_network` named `internal` as shown below

### Reproduction steps

add the following in the client section of the Nomad agent:

```hcl
client {
  ...
  host_network "internal" {
    interface = "lo"
  }
}
```

restart the Nomad agent.

#### Expected Result
The `node status` or  the `node status -verbose` should show the configured `host_network` for the node

#### Actual Result
there is no information if this has been configured correctly or not.

### Job file (if appropriate)
N/A; although the networking works as expected, there is no way to query the information before launching the job.

(job file in any case)

```hcl
job "host_network" {
  type        = "service"
  region      = "myregion"
  datacenters = ["mydc"]

  group "host_network" {
    count = 1

    network {
      port "http" {
        static       = 8080
        to           = 5678
        host_network = "internal"
      }
    }

    task "web" {
      driver = "docker"

      config {
        image          = "hashicorp/http-echo"
        args           = ["-text='hello world'"]
        auth_soft_fail = true

        ports = ["http"]
      }

      resources {
        cpu    = 1024
        memory = 1024
      }
    } # task1
  }   # group
}     # job
```

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

@angrycub  @nickethier

**Comment by DerekStrickland** [comment]
Hi @shantanugadgil,

Thanks for raising this issue and providing configuration and reproduction steps. I'll try to reproduce your use case and update you on what I find.

- @DerekStrickland

**Comment by DerekStrickland** [comment]
Hi @shantanugadgil,

I just want to confirm.  You are asking that this information be added. You are not saying that in some other scenario the information is available, but in you current configuration it is not available. Is that an accurate summary?

-Derek

**Comment by shantanugadgil** [comment]
Yes, I am asking that this information (about the host networks) be *added* to the output.

As far as I tried, I was not able to "query" for the information using the cmd line

**Comment by DerekStrickland** [comment]
ok thanks. I'll relabel this as an enhancement and add to the backlog for consideration then.  Thx!

**Comment by deblasis** [comment]
Hi there,

I am wandering across the various projects looking for issues that I can contribute to. This one seemed like a good fit.

Given the `client` stanza described in the issue, a `nomad node status` returns the extra line:
```
Host Networks   = internal
```

while supplying the `-verbose` flag produces the section:
```
Host Networks
Name      CIDR         Interface
internal  127.0.0.1/8  lo
```

**Comment by shantanugadgil** [comment]
Awesome. If approved, any chance of this making into 1.2.0 GA?

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/11432 and will ship in 1.2.0-rc1.
