### ISSUE TITLE
ui: Show all jobs/storage in every namespace by default

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#11233]
### Proposal

I would like for the default view to select all resources in all namespaces. Users could still select a specific namespace via a dropdown.

### Use-cases

We're in the process of rolling out namespace usage within our infrastructure. Engineers will use the Nomad UI to inspect the state of the world, but their resources may not be in the default namespace - or will be confused with one that does exist in that namespace - and as such they may be confused and interact with the wrong resource.

We already had this issue while working on the functionality with our deploy system. We deployed a nomad job to a new namespace but forgot to switch namespaces in the sidebar, so we couldn't find the job. This also impacted the local cli, but I think that can be done as a separate ticket.

### Attempted Solutions

There isn't really an alternative solution except to click around through the namespace selector and hope you remembered the right namespace for your resource.

**Comment by apollo13** [comment]
I think this can be closed as dupe of https://github.com/hashicorp/nomad/issues/10871 ?

**Comment by josegonzalez** [comment]
Yeah that makes sense. I'll close this and +1 the other.
