### ISSUE TITLE
Struggling to set docker labels

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#1125]
### Nomad version
0.3.2

### Operating system and Environment details
ubuntu 16.04 running in VirtualBox on Mac OS X 10.11.4

### Issue
When I try to define labels on a docker container in the job spec. the job is rejected with an error about the labels syntax.

### Reproduction steps
Define a docker job with a config such as:
```
    config {
      image = "nginx:alpine"
      network_mode = "overlay"
      labels = {
        SERVICE_NAME = "nginx"
      }
```

And when trying to run the job I get:
`* task: 'nginx-task', config -> field "labels" with input [map["SERVICE_NAME":"nginx"]] doesn't seem to be of type map`

I've tried numerous variations including [] instead of {}, with and without the '=' after 'labels', quoting the keys, etc. all with the same error.

**Comment by diptanu** [comment]
cc/ @iverberk

**Comment by iverberk** [comment]
#1126 should resolve this issue. Apologies for the bad user experience!

**Comment by far-blue** [comment]
thanks for a quick fix! I'll try again on the next release :)

**Comment by mclate** [comment]
Sorry for bringing this back, but it doesn't seem to be fixed for json files:
`"labels": {"task":"api"}` gives: 
`* field "labels" with input map["task":"api"] doesn't seem to be of type array`

**Comment by dadgar** [comment]
@mclate: 
```
"labels": [
                                {
                                    "baz": "bam",
                                    "foo": "bar"
                                }
                            ],
```

I believe it is this way due to HCL parsing. Not sure tho
