### ISSUE TITLE
JsonSchema

### ISSUE THREAD

**Issue by blaggacao** [hashicorp/nomad#11298]
### Proposal

- Add official jsonschemata to nomad / etc.
- e.g. make them recoverable from a subcommand for the current version (`nomad jsonschema > nomad.1.14.json`)

### Use-cases

While hcl is great, there are many config mgt languages, such as cue, nix, dhall, jsonnet, etc.

Also jsonschema validators are ubiquitous and easy to couple into a config rendering pipeline.

Some of those config languages even have native support for jsonschema validation with proper error provenance reporting on failure.

### Attempted Solutions

There is only a community provided schema available but it bears the risk of significant drift over a cli rendered output (`nomad jsonschema`).

/cc @manveru

**Comment by lgfa29** [comment]
Hi @blaggacao 👋 

We have an ongoing work to provide OpenAPI specs for the Nomad API: https://github.com/hashicorp/nomad-openapi/blob/main/v1/openapi.yaml

While not 100% compatible with Json Schema, it's the way we're moving towards machine-friendly API definitions, and it would be hard for us to keep two similar workstreams right now. 

I'm going to close this issue, but if you have any specific concerns for the OpenAPI work free free to raise an issue in that repo.

Thanks!
