### ISSUE TITLE
Container name is too long

### ISSUE THREAD

**Issue by trong** [hashicorp/nomad#1129]
I use cAdvisor + InfluxDB + Grafana for monitoring. Screenshot of the small part of dashboard bellow:
<img width="640" alt="long name" src="https://cloud.githubusercontent.com/assets/466842/14812446/f6cac512-0ba5-11e6-9a22-710668af6adc.png">

The best way to do like docker daemon:
 - outside container id: 414671339fe8
 - inside container id: **414671339fe8**c8785111898a8a49974e91e52185016a3a46877d762ed94f3257

It will be looks like:
<img width="636" alt="short name" src="https://cloud.githubusercontent.com/assets/466842/14812447/f6cbd2b8-0ba5-11e6-9ab7-d981106ac534.png">

**Comment by trong** [comment]
kubernetes uses only 5 characters

**Comment by dadgar** [comment]
Can you point at Docker documentation that allows setting different IDs? The ID is currently task-<alloc-id> so that logging and even monitoring system can know the exact source of information. So we will likely be keeping this as is.

**Comment by trong** [comment]
Now, as I think, Nomad generate the name of container like <task name> + GUID. If the name of task is "backend" then the result name will be 44 characters! This useful maybe for some systems, but not for people. If it's really needed for some reasons this long name may be hidden inside Nomad.

For example:

Docker truncated container ID:
```
$ docker ps
CONTAINER ID        IMAGE 
a4f8008b0994        ubuntu
d365b4534f82        ubuntu
```

Docker full ID:
```
$ docker ps --no-trunc
CONTAINER ID        IMAGE 
a4f8008b0994ad690799b5d3f482821712d0cd25e29fa37bb1c3b9f9ef4c466d       ubuntu
d365b4534f82e207c12ffba6706a3355be4db6b80de88f159093b1325ace8303       ubuntu
```

Nomad container name: backend-fa24dfe2-22fc-457f-b926-446a780eb098
Kubernetes container name: backend-785ab

**Comment by dadgar** [comment]
Hey so that is just Docker truncating at the CLI. You reference an inside container ID and outside. Can you please link documentation to this?

I am going to close in the meantime since I believe there is only a single ID and we must treat it as a UUID to avoid conflicts.
