### ISSUE TITLE
[question] exec job doesn't run. What am I missing?

### ISSUE THREAD

**Issue by rajkashikar** [hashicorp/nomad#1130]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.3.2-rc2 ('e6be454154c2296a563a4c2319e49eff1484e839+CHANGES')

Allocation status:
[root@eifweb-master]./nomad alloc-status 0a245fb5-f2cf-41f9-ff44-5a152d9d1e14
ID            = 0a245fb5
Eval ID       = 5c41e418
Name          = sleeping.sleeping[0]
Node ID       = <none>
Job ID        = sleeping
Client Status = failed

==> Status
Allocation "0a245fb5" status "failed" (17/17 nodes filtered)
  * Constraint "${attr.hostname} = solano" filtered 2 nodes
  * Constraint "missing drivers" filtered 15 nodes

### Operating system and Environment details
RHEL 6.6
### Issue
I have 3 nomad masters and about 17 nodes. Most of them have raw_exec drivers, except 1 (solano) which has exec driver.
### Nomad Server logs (if appropriate)
Apr 27 00:50:38 eifweb-master nomad[18696]: http: Request /v1/allocation/0a245fb5-f2cf-41f9-ff44-5a152d9d1e14 (1.57737ms)
Apr 27 00:50:45 eifweb-master nomad[18696]: http: Request /v1/evaluation/5c41e418-0afd-f18a-0f43-d9983b665cd5 (1.473218ms)
Apr 27 00:50:45 eifweb-master nomad[18696]: http: Request /v1/evaluation/5c41e418-0afd-f18a-0f43-d9983b665cd5/allocations (1.192754ms)
Apr 27 00:50:45 eifweb-master nomad[18696]: http: Request /v1/allocation/0a245fb5-f2cf-41f9-ff44-5a152d9d1e14 (1.629497ms)
Apr 27 00:51:01 eifweb-master nomad[18696]: http: Request /v1/jobs (4.810828ms)
Apr 27 00:51:06 eifweb-master nomad[18696]: http: Request /v1/jobs?prefix=sleeping (1.453013ms)
Apr 27 00:51:06 eifweb-master nomad[18696]: http: Request /v1/job/sleeping (1.824251ms)
Apr 27 00:51:06 eifweb-master nomad[18696]: http: Request /v1/job/sleeping/evaluations (3.304101ms)
Apr 27 00:51:06 eifweb-master nomad[18696]: http: Request /v1/job/sleeping/allocations (1.89582ms)
Apr 27 00:51:23 eifweb-master nomad[18696]: http: Request /v1/allocations?prefix=0a245fb5-f2cf-41f9-ff44-5a152d9d1e14 (1.692679ms)
Apr 27 00:51:23 eifweb-master nomad[18696]: http: Request /v1/allocation/0a245fb5-f2cf-41f9-ff44-5a152d9d1e14 (2.125085ms)
Apr 27 00:52:18 eifweb-master nomad[18696]: client: updated allocations at index 4566 (pulled 0) (filtered 0)
Apr 27 00:52:18 eifweb-master nomad[18696]: client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)

### Nomad Client logs (if appropriate)
Apr 27 00:41:28 solano nomad[13529]: driver.docker: using client connection initialized from environment
Apr 27 00:41:28 solano nomad[13529]: client: available drivers []
Apr 27 00:41:28 solano nomad[13529]: client: port not specified, using default port
Apr 27 00:41:28 solano nomad[13529]: client: periodically fingerprinting docker at duration 15s
Apr 27 00:41:28 solano nomad[13529]: client: port not specified, using default port
Apr 27 00:41:28 solano nomad[13529]: client: port not specified, using default port
Apr 27 00:41:28 solano nomad[13529]: client: setting server address list: [sjc-consul1:4647 sjc-consul2:4647 sjc-consul3:4647]
Apr 27 00:41:28 solano nomad[13529]: client: periodically fingerprinting exec at duration 15s
Apr 27 00:41:28 solano nomad[13529]: client: updated allocations at index 4521 (pulled 0) (filtered 0)
Apr 27 00:41:28 solano nomad[13529]: client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
Apr 27 00:41:28 solano nomad[13529]: client: node registration complete
Apr 27 00:41:28 solano nomad[13529]: client: periodically checking for node changes at duration 5s
Apr 27 00:41:29 solano nomad[13529]: client: state updated to ready
Apr 27 00:41:35 solano nomad[13529]: client: state changed, updating node.
Apr 27 00:41:35 solano nomad[13529]: client: node registration complete
Apr 27 00:46:37 solano nomad[13529]: client: updated allocations at index 4521 (pulled 0) (filtered 0)
Apr 27 00:46:37 solano nomad[13529]: client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
Apr 27 00:46:37 solano nomad[13529]: client: updated allocations at index 4566 (pulled 0) (filtered 0)
Apr 27 00:46:37 solano nomad[13529]: client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
Apr 27 00:51:43 solano nomad[13529]: client: updated allocations at index 4566 (pulled 0) (filtered 0)
Apr 27 00:51:43 solano nomad[13529]: client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)

### Job file (if appropriate)
job "sleeping" {
	datacenters = ["sjc"]
	type = "service"
	  task "sleeping" {
		driver = "exec"
		config {
		command = "/bin/sleep"
		args = [ "100000" ]
			}
		resources {
			cpu = 25 # 500 Mhz
			memory = 250# 256MB
			network {
				mbits = 10

					}
			  }
		constraint {
			attribute = "${attr.hostname}"
			value = "solano"
			}

			} # Task ends
		}  # Job ends

**Comment by diptanu** [comment]
@rajkashikar If you look at the client logs the available drivers are empty, and so Nomad isn't able to find any nodes which has the exec driver.

Two questions - a. Are you running Nomad client as root? b. Are the cgroup file system mounted? 
These are the two pre-requisites for running the exec driver.

**Comment by rajkashikar** [comment]
The nomad client is running as root. And Cgroups are mounted. 
The job gets scheduled. (Status is pending though).  A Chrooted environment is created and executor.out says 'executor: launching command /bin/sleep 100000'. But I can't see the process.

----x---- Status of the job
[root@solano]/etc/consul.d/bin/nomad status sleeping
ID          = sleeping
Name        = sleeping
Type        = service
Priority    = 50
Datacenters = sjc
Status      = running
Periodic    = false

==> Evaluations
ID        Priority  Triggered By    Status
dc8cace1  50        job-register    complete
418f21ba  50        job-deregister  complete
6229721e  50        job-register    complete
4b99dafe  50        job-register    complete

==> Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status
728d7efc  dc8cace1  2ef80666  sleeping    run      pending
353eb1b9  4b99dafe  <none>    sleeping    failed   failed

---x---
[root@solano]pwd
/data/nomad_tmpd/alloc/728d7efc-3821-9823-0e7c-e89bfeea0a0f/sleeping
[root@solano]ls
alloc  bin  etc  lib  lib64  local  sbin  sleeping-executor.out  tmp  usr
[root@solano]cat sleeping-executor.out
2016/04/27 10:50:58 [DEBUG] executor: launching command /bin/sleep 100000
[root@solano]

**Comment by rajkashikar** [comment]
It works.. just took time to create the chroot environment.
