### ISSUE TITLE
Nomad Ecosystem - Broken link to Gitlab resources

### ISSUE THREAD

**Issue by CarwynNelson** [hashicorp/nomad#11306]
### Issue

When I visit https://www.nomadproject.io/docs/ecosystem and click on https://www.hashicorp.com/resources/nomad-ci-cd-developer-workflows-and-integrations I get the following error:

![image](https://user-images.githubusercontent.com/3310215/137197362-f9a47b94-430a-44cc-bf1f-abdba97fe144.png)

It looks like this link comes from https://github.com/hashicorp/nomad/blob/main/website/content/docs/ecosystem.mdx

#### Expected Result

I see some documentation related to Gitlab CI and Nomad

#### Actual Result

404 Error page

**Comment by lgfa29** [comment]
Hi @CarwynNelson 👋 

The link is working for me, maybe it was some hiccup with our blog? Could you check if it's broken for you?

**Comment by CarwynNelson** [comment]
All working. Looks like the blog may have had a bit of downtime 😄
