### ISSUE TITLE
[ui] namespace query parameter vanishes when searching and sorting allocation and client tab

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#11327]
### Issue
`namespace` query parameter vanishes when searching or sorting the Job Allocations or Job Clients tables.

### Solution
`refreshModel` differs from passing a query argument to `LinkTo` or passing the query parameter in a `transitionTo` hook because `refreshModel` will ensure that the `model` and `setUpController` hook on the route will be called. Using `refreshModel` is considered to be a full transition and probably why we weren't seeing any of the model hooks we were expecting to be logged.

_But... why are we loosing the query parameter in the first place?_

Our current hunch is resetPagination or searchTerm is triggering a partial transition which we determined is true using the logger.

**What's the difference between partial transitions and full transitions (i.e. `refreshModel`)?**

`refreshModel` triggers `queryParamsDidChange` in the Ember Router which then invokes `Router.refresh`. This creates a map of the pre-existing query parameters - whereas a partial transition does not create a map of the old values, but just computes a set of new values based on what we have defined in our controller.
This is has been brought up by LinkedIn and is listed a Router Bug.

#### My prescription:
Let's use refreshModel but use a combination of Hyrum's Law and the Beyonce rule.
If you like it, you should have put a test on it.
We'll write a test that says that we're depending on this API behavior, if we upgrade Ember and the behavior changes.

#### Resources (Nerd Snipe):
Query Params behavior changes with RouterService when refreshModel is true [#18683](https://github.com/emberjs/ember.js/issues/18683)

pzuraq believes this issue has been ongoing since `3.13`

**Comment by lgfa29** [comment]
Close by #12082
