### ISSUE TITLE
Docker on CentOS 7.1

### ISSUE THREAD

**Issue by saschak094** [hashicorp/nomad#1132]
Hi, 

I am currently working with Nomad on CentOS 7.1 and trying to submit a docker job. 
The commands we use is: 
  -) nomad init
  -) nomad run example.nomad

and we receive the following output:
 
==> Monitoring evaluation "a38036a1"
    Evaluation triggered by job "example"
    Scheduling error for group "cache" (failed to find a node for placement)
    Allocation "46766119" status "failed" (15/15 nodes filtered)
      * Constraint "missing drivers" filtered 15 nodes
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "a38036a1" finished with status "complete"

**Comment by dadgar** [comment]
@saschak094 It looks like none of the Nodes have docker running or are configured in a way that Nomad could not detect the docker engine.
