### ISSUE TITLE
Nomad changes file permissions on template re-render

### ISSUE THREAD

**Issue by heipei** [hashicorp/nomad#11330]
### Nomad version
Nomad v1.1.6

### Operating system and Environment details
Linux, Ubuntu 20.04

### Issue
Nomad seems to change file permissions for some files in local/ when re-rendering one of the template files. Initially, all files in this directory are 644, but after re-rendering a consul template into that dir, only the re-rendered file still retains the 644 perms, the other ones are 700. Since all files are owned by root this makes the other files unreadable by the task running inside the docker container which is not running as root. The other template file had perms=644 specifically, but was nevertheless changed to 700.

### Reproduction steps
Nomad job with two template files into local, volume-mount into docker container, trigger one of the files to be re-rendered.

#### Expected Result
Files retain their original / intended permissions.

#### Actual Result
Files changed to 700 except the re-rendered file.

**Comment by lgfa29** [comment]
Hello from the future 👋 

I cleaning up some stale issue and we haven't had any updates on this one for a while, so I'm going to close it for now. But let me know if this is still a problem and we can reopen it.

Thank you!
