### ISSUE TITLE
pending job to `down` node

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#1133]
### Nomad version
Output from `nomad version`

Server
```
$ nomad -v
Nomad v0.3.1
```

Client
```
$ nomad -v
Nomad v0.3.2
```

### Operating system and Environment details

CoreOS

### Issue

The following dumps illustrate that deployer job is pending "stop" on node `9eebdddd` which went down.  It's my understanding that if a node is dead, a pending "stop" job should immediately result in "complete".  

If the node comes back, nomad won't have the job running so the status of "complete" will match.
Is my assumption here correct?

The main reason this is pertinent for us is that we are utilizing the nomad API to query for job status and action off the aggregate allocations statuses.  Since it is trapped in a "pending" state, it appears (to our tool) that nomad is hung.

```
nomad status deployer
ID          = deployer
Name        = deployer
Type        = system
Priority    = 50
Datacenters = us-east-1a,us-east-1b,us-east-1d
Status      = running
Periodic    = false

==> Evaluations
ID        Priority  Triggered By  Status
34c65e2d  50        job-register  complete
44d7d144  50        job-register  complete
e5408504  50        node-update   complete
9042b4f1  50        node-update   complete
9d08bcef  50        node-update   complete
e13a9317  50        node-update   complete

==> Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status
449b4a2f  34c65e2d  ecff83a7  deploy      run      running
d0c7f127  34c65e2d  d30feba1  deploy      run      failed
9c003c14  44d7d144  d30feba1  deploy      stop     dead
6c91397b  44d7d144  ecff83a7  deploy      stop     dead
484b2ce1  9042b4f1  ecff83a7  deploy      stop     dead
309069aa  9d08bcef  <none>    deploy      failed   failed
0df2a477  9d08bcef  d30feba1  deploy      stop     dead
bc588ef0  9d08bcef  9eebdddd  deploy      stop     pending
847cb5e8  e13a9317  <none>    deploy      failed   failed
adbe9349  e13a9317  200f6cc1  deploy      stop     running
```

```
$ nomad node-status
ID        DC          Name       Class   Drain  Status
ecff83a7  us-east-1d  manager-2  <none>  false  ready
9eebdddd  us-east-1d  manager-2  <none>  false  down
d30feba1  us-east-1b  manager-1  <none>  false  ready
d068e09e  us-east-1b  manager-1  <none>  true   down
200f6cc1  us-east-1a  manager-0  <none>  false  down
```

**Comment by BSick7** [comment]
Small follow-up.  I tried placing node `9eebdddd` into node-drain as an experiment and was unable to cleanse.

**Comment by BSick7** [comment]
I find myself dealing with allocation issues.
It would be helpful if there was a way to manually force-kill an allocation.
Is this out of line with the nomad philosophy?
What is the hashicorp way to deal with these issues?

**Comment by dadgar** [comment]
@BSick7 when a node is down it can not update the client status which is the column you are referring to. Thus the status will stay the same as what it was prior to the node going down. When the node comes back up it will see that the server has marked the allocation as stop and the client will take the correct action.

Also you should update your servers before your clients. You can see our recommended guide here: https://www.nomadproject.io/docs/upgrade/index.html

**Comment by BSick7** [comment]
If a node never comes back, how do we flush its jobs?
Given immutable infrastructure, our notion of "bringing a node back online" usually means we're destroying the node and rebuilding from scratch.

**Comment by dadgar** [comment]
@BSick7 when a client is detected as dead, which will happen between 10 seconds to ~1 minute depending on cluster size, the scheduler will migrate any work that was on that client to another Node.

The Node will then be GC'd from the system several hours later. There is no need for an operator to do anything manually.

**Comment by a86c6f7964** [comment]
> The Node will then be GC'd from the system several hours later. There is no need for an operator to do anything manually.

I have noticed that this GC can take days. Is there any way that this can be sped up? Also I noticed https://github.com/hashicorp/nomad/pull/1410 might help with this ticket. Getting the state to move to `lost` instead of still set as `running`

**Comment by dadgar** [comment]
@a86c6f7964 the node gc threshold is configurable by the user. https://www.nomadproject.io/docs/agent/config.html#node_gc_threshold

Closing this as it has been a while.
