### ISSUE TITLE
[new feature] Long-term storage for results

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#1137]
As far as I understand, nomad discards job results, logs, and related info/meta-data once a job is stopped. Is that correct? Can another system work with nomad to store results, or are there any plans to extend nomad in this way?

**Comment by diptanu** [comment]
Nomad doesn't immediately remove jobs and other objects from the system. There is a GC duration, after which jobs which are in the `dead` state are removed from the system. So you could store the results in another system by polling the Nomad API. 

We have talked in the past about doing an event API where Nomad will push changes related to life-cycle of a job and allocations, etc but so far the community hasn't asked for it and we haven't felt the need for it internally either so it hasn't been prioritized.

**Comment by ketzacoatl** [comment]
OK, thanks for the details.

Here is some info I can offer on my use of nomad. First, I've spent some time working with nomad running simple services, generally "operations helpers" and similar services I want to provide HA for, but that I'm also ok with failing if I don't do it right. Recently, I have been testing more computationally intensive batch processes in nomad, and I am now starting to explore running more critical services, as well as those services and the batch jobs next to each other.

I am thinking about "long-term storage for job/allocation results" in two ways..

1) For my work as an operations engineer, I'd like more insights into what my jobs are doing (stats on allocation and use of resources, success/failure status, allocation failures, etc), and for that to be retained across time. There is opportunity for integration with consul's catalog, as well as standard monitoring/logging practices.

2) The computationally intensive batch jobs I mentioned is the situation where I would be sticking nomad in front of developer/users who could care less about the tool, and just want it to work. As part of providing a platform for their work, I would like to be able to show them a history of the jobs they have run, the success/failure and resource allocation/utilization of those jobs, and similar historical stats and information on previous runs of these computationally intensive batch runs. What they ran, and how they chose to run it, informs what and how they will run future jobs, and they need the info to make these determinations.

I have not thought much about what these would look like, I have only recognized the "hey, nomad doesn't tell me much about what's not running anymore", and that I'd be packaging this up into a UI in some way. I don't mind integrating nomad with another system to provide the full picture, but nomad would need to provide the APIs to do so.

**Comment by dadgar** [comment]
@ketzacoatl That sounds like a great system 👍 

Nomad will only ever keep the set of data it needs to manage the current set of Jobs but it has the GC grace window to enable exactly what you are wanting to do. Essentially you would just long poll the different APIs using blocking queries and store the results in a DB and then it becomes essentially a MVC problem of presenting the data in a useable way.

**Comment by dadgar** [comment]
@ketzacoatl If you have no more questions regarding this can you please close the issue. In the future please prefer the mailing list for questions.

**Comment by ketzacoatl** [comment]
That's a whole lot to figure out, and while I'd like to ask for an example query as you describe, I think I can save you the trouble.

From your reply, I will assume you mean to also imply that you do not intend to ever give Nomad this type of capability, is that true? Does it seem reasonable to consider simply forwarding updates to evaluations/allocations/nodes to a database? Nomad would keep it's current concept of GC and all that, but the database would serve as a simple history that could be used as desired. In my opinion, it would make more sense for the app to push that history to a database, rather than having a separate "collector" poll the app's API and shuffle it over to a database.

**Comment by dadgar** [comment]
You can see the `Blocking Query` section here: https://www.nomadproject.io/docs/http/index.html

It actually isn't as bad as you would think. You long-poll the jobs in the system (https://www.nomadproject.io/docs/http/jobs.html) and then for each one you long poll it for its allocations and then long poll the allocations and then you have all the data.

**Comment by ketzacoatl** [comment]
Yea, last night I parsed the long-polling implementation as:

* make a request on an end point, save the response and the Index
* hit the endpoint in a loop, include the last seen index

It's straight-forward, but non-trivial to figure out. Seems like a good blog post in the future.

I would be interested in your feedback on my proposal to have nomad cc a database to keep history with ease.

**Comment by dadgar** [comment]
Yeah you should definitely write a blog! There is just a lot of extra complexity with that forwarding. How do you deal with DB permissions, protocols, DB unavailability (need to delay GC'ing) etc

**Comment by ketzacoatl** [comment]
I'm not sure I understand the complications you see. Forgive my possible ignorance or naivety, but from my perspective, this seems straight-forward:
* GC like nomad is now, that doesn't need to change. 
* Similar to what nomad does with consul, the admin would provide access to the database  - no reason to deal with permissions (nomad just writes to the db, that's it).
* If the DB is unavailable, write errors to the log and let the admin fix it, don't hold up nomad. If failing hard is what some admins want, there could be a config option to make DB unavailability a fail-hard scenario.

**Comment by ketzacoatl** [comment]
This is flagged with "waiting-reply", which I interpret as you are looking for a reply from me, is that correct? I would be curious what input I could provide to better clarify how this could be a useful feature, and/or reasonable to put in nomad.

**Comment by dadgar** [comment]
Ah sorry, that label stuck around from when you first submitted. It is a good idea but not currently high priority.

**Comment by jippi** [comment]
https://github.com/seatgeek/nomad-firehose could be used as a stop gap for this feature until something native shows up :)

**Comment by jippi** [comment]
Cc @diptanu

**Comment by mikenomitch** [comment]
Given that we can't store this info in Nomad to keep the Raft DB light and we have the [Event Stream](https://learn.hashicorp.com/tutorials/nomad/event-stream?in=nomad/nomad-1-0), I'm going to close this one out!
