### ISSUE TITLE
Call to function “pathexpand” failed: filesystem function disabled

### ISSUE THREAD

**Issue by tomasaberg** [hashicorp/nomad#11376]
### Nomad version
1.1.6

### Operating system and Environment details
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
### Issue
I've started a discussion at the community forum and was asked to create a issue report.
See: https://discuss.hashicorp.com/t/call-to-function-pathexpand-failed-filesystem-function-disabled/30995

The issue I'm having is when I try to download a artifact from my companys GitHub Enterprise and run the job from the Web UI, it will fail with the error: `Call to function “pathexpand” failed: filesystem function disabled`

However, it will work without any issues if I run the same job from CLI

### Reproduction steps
1. Create a job that will check out a private repository
2. Execute it from the Nomads WebUI

#### Expected Result
I would expect that running a job from the WebUI would work the same way as running it from CLI

#### Actual Result
When executing from the WebUI it will fail with `Call to function “pathexpand” failed: filesystem function disabled`

### Job file (if appropriate)
This is the job I have that fails:
```
job "prometheus" {
  datacenters = ["sth"]
  type        = "service"

  group "monitoring" {
    count = 3
    network {
      port  "prometheus" {
        to = 9090
      }
      port  "consul" {
        to = 8500
      }
    }

    task "prometheus" {
      vault {        
        policies = ["policy-kv-secrets"]
        change_mode   = "signal"
        change_signal = "SIGUSR1"
      }
      artifact {
        source      = "git::git@github.myenterprise.corp:yolo/infra"
        destination = "local/repo"
        options {
          sshkey = "${base64encode(file(pathexpand(" ~/.ssh/id_ed25519")))}"
        }
      }
      template {
        source        = "${NOMAD_TASK_DIR}/repo/nomad/artifacts/prometheus/prometheus.yml.tpl"
        destination = "local/prometheus.yml"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }

      driver = "docker"

      config {
        image = "prom/prometheus"
        ports = ["prometheus"]
        volumes = [
          "local/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
        ]
      }
      service {
        name = "prometheus"
        port = "prometheus"
        tags = [
          "urlprefix-/",
          "traefik.enable=true",
          "traefik.http.routers.prometheus.rule=Host(`prometheus.myenterprise.corp`)"
        ]
        check {
          name     = "Prometheus is alive"
          type     = "http"
          path     = "/-/healthy"
          interval = "10s"
          timeout  = "2s"
        } 
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)
`journalctl -xef -u nomad` doesn't reveal anything when trying to run this job.
Please advice how I can provide more relevant logging if needed

### Other
I'm new to Nomad but thanks a lot for your support and Nomad itself, I'm having fun while trying to learn and things are making more sense every day :)

**Comment by tgross** [comment]
Hi @tomasaberg! As @apollo13 has noted we have to disable the file path functions in the web UI to avoid file inclusion from the server. On the command line, HCL2 is being parsed locally (ex. on your laptop), so we don't have the same security issues there. It seems worth us considering some way to work around this in the UI by letting users upload files to some sandbox, but that's going to be a good bit of design effort to make sure we can do that safely.

Generally speaking you'll want to include secrets from Vault, but unfortunately there's no good way to get secrets for artifacts authentication that way. Note that the artifacts are being pulled by the client (so running as `root`), whereas the `template` block is rendering to the task's working directory. (And artifacts are pulled before templates are rendered anyways. See the [filesystem](https://www.nomadproject.io/docs/internals/filesystem#templates-artifacts-and-dispatch-payloads) docs).

But for the specific problem of ssh keys for git artifacts, keep in mind that Nomad is running as a user just like any other process (usually `root`). So if you were already ok with including a ssh key from the file system, you should be able to place that same key at `/root/.ssh/id_ed25519` and then just leave out the `options.sshkey`.

**Comment by tgross** [comment]
It looks like this question has been answered so I'm going to close this issue out.
