### ISSUE TITLE
[question] Does nomad support retrieving git artifacts over SSH? 

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#1138]
https://www.nomadproject.io/docs/jobspec/#artifact_doc points me to https://github.com/hashicorp/go-getter/tree/ef5edd3d8f6f482b775199be2f3734fd20e04d4a#protocol-specific-options-1 where I find more information about go-getter's support for retrieving git repos.

Having read those, I believe Nomad supports retrieving a git repo as an artifact, though I am unsure of the limits, specifically with private repositories. For example, I usually setup private repos to be retrieved over SSH, using a pubkey, and sometimes relying on an entry in the host's or user's `ssh_config`.

How would I setup a nomad job or agent to ensure tasks can clone private git repos as artifacts?

I'd like to update the docs with an example of this.

**Comment by dadgar** [comment]
If you see the docs:

```
Nomad allows downloading http, https, and S3 artifacts. If these artifacts are archives (zip, tar.gz, bz2, etc.), these will be unarchived before the task is started
```

We do not support the git downloader of go-getter.

**Comment by ketzacoatl** [comment]
Thanks for confirming!
