### ISSUE TITLE
Support sidecar upstreams config

### ISSUE THREAD

**Issue by legege** [hashicorp/nomad#11392]
### Proposal
It's currently impossible to set advanced configurations on an upstream sidecar service proxy. The proposal here would be to allow a `config` option, similar to how it's possible directly with Consul:
https://www.consul.io/docs/connect/registration/service-registration#config-1

### Use-cases

1. This would allow the end user to configure proxy-specific features like timeouts or retries for the given upstream. Example:
```
      proxy {
        upstreams {
          destination_name   = "countdash-api"
          local_bind_port    = 8080

          config {
            connect_timeout_ms = 5000
            limits {
              max_connections         = 3
              max_pending_requests    = 4
              max_concurrent_requests = 5
            }
            passive_health_check {
              interval     = "30s"
              max_failures = 10
            }
          }
        }
      }
```

2. It would also allow to use upstream level [escape-hatch](https://www.consul.io/docs/connect/proxies/envoy#envoy_listener_json): `envoy_listener_json` and `envoy_cluster_json`

**Comment by Lord-Y** [comment]
Any news about this issue?

**Comment by DerekStrickland** [comment]
Hi @Lord-Y 

We actually just talked about doing a pass on Consul configuration syncing a couple of hours ago. I've added this issue to the list. Thanks for checking in.  The reminder was timely!

**Comment by kirooshu** [comment]
We would really like to also see this implemented. It is a shame that Nomad is not kept up to date with what Consul implements around the Service Mesh.
