### ISSUE TITLE
Add the 'config' block to the 'upstream' section

### ISSUE THREAD

**Issue by sergeyzoom** [hashicorp/nomad#11412]
Add the 'config' block to the 'upstream' section.

Nomad is unable to take an upstream -> config block right now.

Proxy section.upstream[*].the configuration in the nomad configuration causes the error
"Unsupported block type; Configuration type blocks are not expected here".

Because of this, it is not possible to configure the envoy-proxy more fully in the Mesh system.
(Change the protocol, configure the policy of retrays, etc.)

More details were discussed on the forum
https://discuss.hashicorp.com/t/service-mesh-envoy-upstream-config-blocks-of-type-config-are-not-expected-here/30547

**Comment by sergeyzoom** [comment]
> Hi @sergeyzoom and thanks for raising this issue. We already have #11392 which requests this feature, therefore I will close this issue out and use the existing one. If you could add an additional thumbs up on #11392 that would be great and helps prioritise.

The task is not to add additional functionality to consul, but to resolve the existing one in nomad. Now nomad just doesn't understand the "config" in the "upstream" section.

By the way, if nomad has the same functionality as in consul, the policy of retrays can be configured.

**Comment by jrasell** [comment]
Hi @sergeyzoom. I understand that which is why the linked issue is a Nomad issue to track making this available from the Nomad side. Please let me know if I am missing anything else.
