### ISSUE TITLE
CLI command `nomad job allocs` does not exist

### ISSUE THREAD

**Issue by mircea-c** [hashicorp/nomad#11418]
### Nomad version
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)

### Operating system and Environment details

```
~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

### Issue

The CLI command `nomad job allocs [options] <job>` as seen in the [official documentation](https://www.nomadproject.io/docs/commands/job/allocs), does not seem to exist anymore. 

### Reproduction steps

Run `nomad job allocs example` from the CLI

#### Expected Result

```
ID        Node ID   Task Group  Version  Desired  Status   Created   Modified
c2b4606d  35085106  cache       2        run      running  21s ago   10s ago
c413424b  35085106  cache       2        run      pending  1m8s ago  11s ago
```

#### Actual Result

```
~$ nomad job allocs my-job
Usage: nomad job <subcommand> [options] [args]

  This command groups subcommands for interacting with jobs.

  Run a new job or update an existing job:

      $ nomad job run <path>

  Plan the run of a job to determine what changes would occur:

      $ nomad job plan <path>

  Stop a running job:

      $ nomad job stop <name>

  Examine the status of a running job:

      $ nomad job status <name>

  Please see the individual subcommand help for detailed usage information.

Subcommands:
    deployments       List deployments for a job
    dispatch          Dispatch an instance of a parameterized job
    eval              Force an evaluation for the job
    history           Display all tracked versions of a job
    init              Create an example job file
    inspect           Inspect a submitted job
    periodic          Interact with periodic jobs
    plan              Dry-run a job update to determine its effects
    promote           Promote a job's canaries
    revert            Revert to a prior version of the job
    run               Run a new job or update an existing job
    scale             Change the count of a Nomad job group
    scaling-events    Display the most recent scaling events for a job
    status            Display status information about a job
    stop              Stop a running job
    validate          Checks if a given job specification is valid
```

As seen from the output above, the command does not run and it is also not shown in the list of subcommands that Nomad prints out. If this is the expected behaviour (why?!?!?!), then the documentation should reflect this.

**Comment by tgross** [comment]
Hi @mircea-c! The `nomad job allocs` command was added in Nomad 1.2 (which is beta). You can see the changelog here: https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#120-unreleased. We're working on a "versioned docs" effort to make it so that commands will only show in the docs for the correct versions, but that's what's happened here.

**Comment by mikenomitch** [comment]
Hey @mircea-c - thanks for opening the issue.

@tgross is correct with everything he said. Sorry about the confusion! Hopefully we find a way to get around these docs issues in the future.

I'm going to close out this issue as 1.2 should be out very soon.

**Comment by mircea-c** [comment]
Thank you for the prompt response. I'll wait for 1.2 then (really want to have this command haha)
