### ISSUE TITLE
UI: add name for the job breadcrumbs to help users understand the hierarchy 

### ISSUE THREAD

**Issue by juliezzhou** [hashicorp/nomad#11436]
### Problem
Even with breadcrumb on the job page, it is hard for users to know which page gets to what the user needs

### Proposed Fix
Add name in the breadcrumb to help users to know which page is which, so it is clear to understand the hierarchy, and easier for users to navigate through the job pages.

<img width="583" alt="Screen Shot 2021-11-03 at 3 20 19 PM" src="https://user-images.githubusercontent.com/90711359/140178283-0559e479-bdf2-4ee9-ac05-fcde71618a5b.png">

**Comment by lgfa29** [comment]
Close by #11590
