### ISSUE TITLE
Nomad port-forward capability

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#11443]
### Proposal

Similar to [kubectl port-forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/) it would be nice to have a Nomad equivalent of the same. `port-forward` is sometimes helpful to test/debug your applications when it's not working the way you intended. It allows to access the service locally without exposing anywhere.

### Use-cases
It's a niche use case, but there can be many for `port-forward`. My _niche_ usecase was that I'd deployed a Prometheus instance on Nomad cluster which scrapes the targets from inside the cluster and sends the metric over the wire to a remote VictoriaMetrics cluster. This meant that I never really needed to expose Prometheus UI at all. Until, I needed to debug the config via UI :)

### Attempted Solutions

At this point the only option is to SSH inside the nomad client node and use SSH tunneling to access it on my local machine. This is undesirable, since lot of devs won't have access to the host nodes and only cluster "admins" can do this.

Sidenote: I think implementing this would be similar to [`exec`](https://github.com/hashicorp/nomad/blob/main/client/alloc_endpoint.go#L274) but curious to know more!

**Comment by jrasell** [comment]
Hi @mr-karan and thanks for raising this feature request.

We already have #6925 open which tracks the addition of a Nomad port-forward command and therefore I will close this issue out and use the linked one as the issue to track. If you could add any thumbs up and comments you might have to #6925 that would be appreciated.
