### ISSUE TITLE
Add clickable links in allocation summary

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#11442]
### Proposal

Currently, if you go to the new "Job Status in Client" summary box at the top of a job, you can click on a status and get redirected to a filtered clients tab.

![Screen Shot 2021-11-03 at 6 24 43 PM](https://user-images.githubusercontent.com/2732204/140241739-d998a603-8fdf-437d-bce5-14184acb8acc.png)

(above, I can click "Degraded" and get taken to a new page)

Ideally, a similar behavior would exist on the Allocations summary.

![Screen Shot 2021-11-03 at 6 25 26 PM](https://user-images.githubusercontent.com/2732204/140241806-592aa420-ce7a-49a3-b212-89b7a24be5d2.png)

Here, I should be able to click "Failed" and get taken to a list of failed allocations for this job in the Allocs tab.

(Queued might not be clickable for technical reasons, but that is okay)

### Use-cases

This would provide a consistent and predictable interface and easy way to jump to allocations you care about when troubleshooting a job.

**Comment by juliezzhou** [comment]
Also if we change the status to look like a hyperlink instead of a box is more clear to indicate which one is clickable
<img width="1122" alt="Screen Shot 2021-11-10 at 9 39 12 AM" src="https://user-images.githubusercontent.com/90711359/141134350-d5ada970-b57c-4569-b256-76baed40021f.png">
