### ISSUE TITLE
Just An quenstion About nomad web development

### ISSUE THREAD

**Issue by sheweichun** [hashicorp/nomad#1147]
`[question]` I found HTTP API in your document,so I want to know that  would you develop web ui to manage nomad?  if will, when?

**Comment by iverberk** [comment]
Hi @sheweichun,

There will be a Nomad UI as part of Atlas. The are no further details on an open-source UI for Nomad. 

Also, there is a similar thread already related to Nomad UI, so closing this one. Please see #278 for additional information on this subject.
