### ISSUE TITLE
Calling Stat on a non existent file returns 500 rather than 404

### ISSUE THREAD

**Issue by tomqwpl** [hashicorp/nomad#11480]
### Nomad version
v1.1.4

### Operating system and Environment details
Windows 10

### Issue
I'm trying to test for the existence of a file in an allocation directory.
I call:
```
nomadClient.AllocFS().Stat(alloc, filename)
```

If the file doesn't exist, this returns an error "Unexpected response code: 500".
Internal server error 500 isn't really an expected response to this, a 404 would be more expected.

Note that in general I seem to have to match the text of the error to detect the 404 case elsewhere, rather than there being a specific error type I can test for for example. Matching on the string of the error text feels fragile, but at least matching for a specific string containing 404 would be preferable to a more generic 500.

#### Expected Result
An error I can use to easily detect "not found"

#### Actual Result
An ambiguous error that could mean many things

**Comment by tgross** [comment]
Hi @tomqwpl! Ok, so I followed that code path and it hits the HTTP API, where it [calls the server RPC](https://github.com/hashicorp/nomad/blob/v1.1.4/command/agent/fs_endpoint.go#L117), which [calls the client RPC](https://github.com/hashicorp/nomad/blob/v1.1.4/nomad/client_fs_endpoint.go#L201), which calls into the [alloc dir functions](https://github.com/hashicorp/nomad/blob/v1.1.4/client/allocdir/alloc_dir.go#L402) that calls [os.Stat](https://pkg.go.dev/os#File.Stat) (which is the operating system interface).

What we should be doing is capturing the error from the allocdir package at [`client/fs_endpoint.go#L148-L151`](https://github.com/hashicorp/nomad/blob/v1.1.4/client/fs_endpoint.go#L148-L151) and converting that to a 404 if it's a "path not found" error. There'll also be an interaction with the sandbox check we need to think about.

**Comment by tgross** [comment]
I've shipped a fix as #11482 and that'll ship in the next regular patch version of Nomad.

**Comment by tomqwpl** [comment]
Cool. Thx.
