### ISSUE TITLE
ability to spread tasks in groups within same job

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#11502]
Looks like @daledude filed https://github.com/hashicorp/nomad/issues/6835 with this intent, but it was closed as a bug/doc improvement.  So, this ticket is a feature request to possibly improve how tasks within groups can be spread.

### Proposal
```
job "job1" {
  spread {
    attribute = "$${node.unique.id}"
  }
  group "group1" {
    task "task1" {
    }
  }
  group "group2" {
    task "task2" {
    }
  }
}
```

As of this writing task1 and task2 end up on the same node.  The feature request is to allow some way to spread the tasks across multiple nodes.

### Use-cases
In this situation task1 and task2 should be deployed as the same job, but in order to smooth resource consumption it makes sense to deploy them to different nodes.

**Comment by josh-m-sharpe** [comment]
Also related: https://github.com/hashicorp/nomad/issues/10421

**Comment by jrasell** [comment]
Hi @josh-m-sharpe.

I wonder if this use-case is covered by using either the [spread scheduling algorithm](https://www.nomadproject.io/api-docs/operator/scheduler#scheduleralgorithm-1) or by using [job specification constraints](https://www.nomadproject.io/docs/job-specification/constraint#constraint-stanza) and in particular the [distinct hosts constraint](https://www.nomadproject.io/docs/job-specification/constraint#distinct_hosts).

The distinct hosts constraint can be applied to a minimal job specification as shown below, meaning each group will be placed onto different Nomad clients. It's worth remembering that in situations where the counts of the groups are greater than the number of available nodes, allocations will failed to be placed as the constraint cannot be adhered to.

```hcl
job "example" {
  datacenters = ["dc1"]
  constraint {
    operator  = "distinct_hosts"
    value     = "true"
  }
  group "group1" {
    task "task1" {
      driver = "docker"
      config {
        image = "redis:3.2"
      }
    }
  }
  group "group2" {
    task "task2" {
      driver = "docker"
      config {
        image = "redis:3.2"
      }
    }
  }
}
```

The [spread stanza](https://www.nomadproject.io/docs/job-specification/spread#spread-stanza) doesn't ensure spread constraining like the constraints do, but attempts to provide a way to describe fault tolerance requirements for a job. Your cluster topology would dictate whether spread could be used to achieve the goals you describe. If you're able to share any additional detail on this point, that would be useful.
