### ISSUE TITLE
web-UI:Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by earthaYan** [hashicorp/nomad#11516]
### Nomad version:
Output from `1.1.2`

### Operating system and Environment details
ubuntu Ubuntu18.04
chrome version:65 and 70

### Issue
when I use the lower version chrome browser like chrome 70 to open nomad-ui website,it shows nothing in page ,and display an error **Uncaught ReferenceError: define is not defined**
### Reproduction steps
<img width="950" alt="1637140729(1)" src="https://user-images.githubusercontent.com/25888900/142172437-9c5cac5f-d037-4cdd-9dcd-0acde9535466.png">

#### Expected Result
show the page normally
#### Actual Result
nothing shows in screen

**Comment by lgfa29** [comment]
Hi @earthaYan 👋 

Unfortunately we can't keep support for older browsers with new releases of Nomad. We try not to break things, but we don't make any guarantees to support any specific version other than the latest available at release time.
