### ISSUE TITLE
Support filebase64 function with Noamd

### ISSUE THREAD

**Issue by MatthiasZerau** [hashicorp/nomad#11522]
### Proposal
Please support filebase64 function like it is available for Terraform.

### Use-cases
As part of a job specification, I want to provide the content of a file as base64 encoded value via the `env` stanza.

### Attempted Solutions
I've tried the following:
```
...
task "myTask" {
  ...
  env {
    DATA_BASE64 = base64encode(file(var.data_file))
  }
}
```
As the file is not UTF-8 encoded it fails with following error:
> Error getting job struct: Error parsing job file from exampletask.nomad:
exampletask.nomad:122,56-61: Error in function call; Call to function "file" failed: contents of D:\a\path\to\file.dat are not valid UTF-8; use the filebase64 function to obtain the Base64 encoded contents or the other file functions (e.g. filemd5, filesha256) to obtain file hashing results instead.

(with Nomad 1.1.0)

**Comment by lgfa29** [comment]
Thank you @MatthiasZerau. I think this function does sound useful in some scenarions. I've set this idea for further triaging.

I'm adding the Terraform docs here for reference:
https://www.terraform.io/docs/language/functions/filebase64.html
