### ISSUE TITLE
Host network issue on macOS despite following the FAQ

### ISSUE THREAD

**Issue by iJebus** [hashicorp/nomad#11537]
### Nomad version
`Nomad v1.2.0`

### Operating system and Environment details
```sh
$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224

$ docker --version
Docker version 20.10.10, build b485636
```

### Issue

Despite following the FAQ, I still can't seem to get jobs running on the host network on a macOS host.

### Reproduction steps

```sh
# get ip address
$ ifconfig en0
en0: ...
	inet 192.168.1.102 netmask 0xffffff00 broadcast 192.168.1.255
	...

# start nomad per the FAQ
$ sudo nomad agent -dev -bind=0.0.0.0 -network-interface=en0
==> No configuration files loaded
==> Starting Nomad agent...
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 192.168.1.102:4646; RPC: 192.168.1.102:4647; Serf: 192.168.1.102:4648
            Bind Addrs: HTTP: 0.0.0.0:4646; RPC: 0.0.0.0:4647; Serf: 0.0.0.0:4648
                Client: true
             Log Level: DEBUG
                Region: global (DC: dc1)
                Server: true
               Version: 1.2.0
...

# start consul in another tab, per the FAQ
$ consul agent -dev -client=0.0.0.0 -bind=192.168.1.102
==> Starting Consul agent...
           Version: '1.10.4'
           Node ID: 'f1df76f8-b3f0-4e9d-3d08-f7070ac0c2e0'
         Node name: 'xxx'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 192.168.1.102 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
...

# run the traefik job per tutorial at https://learn.hashicorp.com/tutorials/nomad/load-balancing-traefik
$  nomad run traefik.nomad
==> 2021-11-19T13:19:10+08:00: Monitoring evaluation "749a8d2b"
    2021-11-19T13:19:10+08:00: Evaluation triggered by job "traefik"
==> 2021-11-19T13:19:11+08:00: Monitoring evaluation "749a8d2b"
    2021-11-19T13:19:11+08:00: Evaluation within deployment: "0629b5de"
    2021-11-19T13:19:11+08:00: Allocation "43ef0a2f" created: node "49030f52", group "traefik"
    2021-11-19T13:19:11+08:00: Evaluation status changed: "pending" -> "complete"
==> 2021-11-19T13:19:11+08:00: Evaluation "749a8d2b" finished with status "complete"
==> 2021-11-19T13:19:11+08:00: Monitoring deployment "0629b5de"
  ⠼ Deployment "0629b5de" in progress...

    2021-11-19T13:19:17+08:00
    ID          = 0629b5de
    Job ID      = traefik
    Job Version = 0
    Status      = running
    Description = Deployment is running

    Deployed
    Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
    traefik     1        1       0        0          2021-11-19T13:29:10+08:00
```

#### Expected Result

The job (traefik in this example) running on the host network.

#### Actual Result

The deployment eventually times out. Checking the task logs, I see the below. See the additional debugging section on how I resolve the consul reachability errors.

```log
time="2021-11-19T05:19:11Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2021-11-19T05:19:26Z" level=error msg="error get consul catalog data, Get \"http://127.0.0.1:8500/v1/catalog/services\": dial tcp 127.0.0.1:8500: connect: connection refused" providerName=consulcatalog
time="2021-11-19T05:19:26Z" level=error msg="Provider connection error Get \"http://127.0.0.1:8500/v1/catalog/services\": dial tcp 127.0.0.1:8500: connect: connection refused, retrying in 647.054716ms" providerName=consulcatalog
...
```

```sh
# from host, trying the traefik UI address
$ curl localhost:8081
curl: (7) Failed to connect to localhost port 8081: Connection refused
$ curl 192.168.1.102:8081
curl: (7) Failed to connect to 192.168.1.102 port 8081: Connection refused
```

### Job file (if appropriate)

```hcl2
job "traefik" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "service"

  group "traefik" {
    count = 1

    network {
      port "http" {
        static = 8080
      }

      port "api" {
        static = 8081
      }
    }

    service {
      name = "traefik"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "http"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "traefik" {
      driver = "docker"

      config {
        image        = "traefik:v2.2"
        network_mode = "host"

        volumes = [
          "local/traefik.toml:/etc/traefik/traefik.toml",
        ]
      }

      template {
        data = <<EOF
[entryPoints]
    [entryPoints.http]
    address = ":8080"
    [entryPoints.traefik]
    address = ":8081"

[api]
    dashboard = true
    insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "127.0.0.1:8500"
      scheme  = "http"
EOF

        destination = "local/traefik.toml"
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
```

### Additional debugging

Opening a shell on the traefik container, I see an address that I'm assuming is from the docker VM. Curling the traefik UI from here is successful. Curling the consul via the host IP from here is successful. 

```sh
$ nomad alloc exec -i -t -task traefik 43ef0a2f /bin/sh
/ # ip a
...
2: eth0: ...
    inet 192.168.65.3/24 brd 192.168.65.255 scope global dynamic eth0
...
/ # curl localhost:8081
Moved Permanently/ # 
/ # curl 192.168.1.102:8500
<a href="/ui/">Moved Permanently</a>.

# from host
$ curl 192.168.65.3:8081
curl: (7) Failed to connect to 192.168.65.3 port 8081: Operation timed out
```

Updating traefik.nomad to the below makes the errors in the task logs about not being able to reach consul go away, but traefik still isn't reachable from the host.

```hcl2
...
    [providers.consulCatalog.endpoint]
      address = "192.168.1.102:8500"
      scheme  = "http"
...
```

**Comment by lgfa29** [comment]
Hi @iJebus 👋 

You were able to spot one of the issues, right there in the end. Your Traefik container will need to talk to Consul using your interface IP (`192.168.1.102` in your case) since that's where Consul will be listening. Using `127.0.0.1` will cause it to try to connect to the Docker Desktop VM instead.

Another thing that you are missing are the [port](https://www.nomadproject.io/docs/drivers/docker#ports) assignments to your task, and you also don't need to use `network_mode = "host"` with Docker Desktop.

The final piece is that you will also need to reach Traefik using your IP instead of `localhost`.

Here are the changes required in your job:

```diff
job "traefik" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "service"

  group "traefik" {
    count = 1

    network {
      port "http" {
        static = 8080
      }

      port "api" {
        static = 8081
      }
    }

    service {
      name = "traefik"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "http"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "traefik" {
      driver = "docker"

      config {
        image        = "traefik:v2.2"
-       network_mode = "host"
+       ports = ["http", "api"]

        volumes = [
          "local/traefik.toml:/etc/traefik/traefik.toml",
        ]
      }

      template {
        data = <<EOF
[entryPoints]
    [entryPoints.http]
    address = ":8080"
    [entryPoints.traefik]
    address = ":8081"

[api]
    dashboard = true
    insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
-     address = "127.0.0.1:8500"
+     address = "192.168.1.102:8500" 
      scheme  = "http"
EOF

        destination = "local/traefik.toml"
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
```

With these changes your job should become healthy and you will be able to connect to Traefik on http://192.168.1.102:8081.

Let me know if this still doesn't work for you!

**Comment by iJebus** [comment]
Thanks, traefik is now reachable from the host but traefik can't reach consul, or anything on the host network (`192.168.31.0/24`, I'm on a different network currently but updated the `address` accordingly). Traefik is still registered with consul, but that's occurring via nomad -> consul.

I hope I'm not missing something obvious here... 😅 

```log
# traefik trying and failing to reach consul at the host ip
time="2021-11-25T02:31:43Z" level=error msg="error get consul catalog data, Get \"http://192.168.31.202:8500/v1/catalog/services\": dial tcp 192.168.31.202:8500: i/o timeout" providerName=consulcatalog
time="2021-11-25T02:31:43Z" level=error msg="Provider connection error Get \"http://192.168.31.202:8500/v1/catalog/services\": dial tcp 192.168.31.202:8500: i/o timeout, retrying in 525.746245ms" providerName=consulcatalog
```

**Comment by lgfa29** [comment]
Oh weird, that's the part that you got working before with the host IP, right? 😅

Did you update the Consul command with the new IP as well?

**Comment by iJebus** [comment]
Yeah correct, and I had updated the consul command. That was my first
assumption, that I'd forgotten or made a typo :thinking:

**Comment by lgfa29** [comment]
Sorry for the delay here, I was out of the office last week.

I tried this again and it all worked, here's a screen recording of what I did:
https://asciinema.org/a/trwi5lfn1t8ZAaFInALrVbhIr

And here's the full job that I used to avoid any issues with diffs. I changed the hard coded Consul IP to use a template from Nomad so we're sure that this is not the problem 😄 

```
job "traefik" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "service"

  group "traefik" {
    count = 1

    network {
      port "http" {
        static = 8080
      }

      port "api" {
        static = 8081
      }
    }

    service {
      name = "traefik"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "http"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "traefik" {
      driver = "docker"

      config {
        image = "traefik:v2.2"
        ports = ["http", "api"]

        volumes = [
          "local/traefik.toml:/etc/traefik/traefik.toml",
        ]
      }

      template {
        data = <<EOF
[entryPoints]
    [entryPoints.http]
    address = ":8080"
    [entryPoints.traefik]
    address = ":8081"

[ping]

[api]
    dashboard = true
    insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "{{ env "attr.unique.network.ip-address" }}:8500"
      scheme  = "http"
EOF

        destination = "local/traefik.toml"
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
```

To test connectivity I ran the sample app from our guide as well:
https://learn.hashicorp.com/tutorials/nomad/load-balancing-traefik#create-and-run-a-demo-web-app-job

Which version of Docker and MacOS are you on? And is it a M1 CPU? I'm fairly behind on these, so maybe that's something that changed in newer versions.

**Comment by iJebus** [comment]
So I follow your steps up to starting Traefik using your `traefik.nomad`, but still get the following logs when I inspect the Traefik task.

```log
time="2021-12-14T01:47:08Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2021-12-14T01:47:53Z" level=error msg="error get consul catalog data, Get \"http://192.168.31.202:8500/v1/catalog/services\": dial tcp 192.168.31.202:8500: i/o timeout" providerName=consulcatalog
time="2021-12-14T01:47:53Z" level=error msg="Provider connection error Get \"http://192.168.31.202:8500/v1/catalog/services\": dial tcp 192.168.31.202:8500: i/o timeout, retrying in 662.840213ms" providerName=consulcatalog
```

I was on Big Sur previously, am now on Monterey. Intel CPU.

```text
Monterey 12.0.1 (21A559)
Docker Desktop 4.3.1 (72247)
```

If I get time this week I might test on my Windows desktop and see what happens. The fact it works for you makes me think it's probably something weird in my individual case rather than a broader problem 😅

**Comment by lgfa29** [comment]
I was behind on Docker, but now I'm on 4.3.1 as well and things still work. I will ask other people in the team to try this, maybe it's something in my environment too 🙂

**Comment by iJebus** [comment]
Running through this on my Windows host tonight and it all just worked. 🤷

**Comment by tgross** [comment]
Hi @iJebus! @lgfa29 asked me to take a look at this. Something I ran into is that I had a Vagrant box (VirtualBox VM) running on my host that forwarded port 8500 from my host to the VM. Consul will start up just fine in that circumstance. Nomad will report some debug messages but they're easy to miss. But that prevented traefik from reaching Consul as well. Once I shut down that VM and started over, the reproduction @lgfa29 provided worked for me as well.

Also, just for clarity, did your host's IP change before the run you did in https://github.com/hashicorp/nomad/issues/11537#issuecomment-993095434? Because the IP address that traefik is looking for is different from the one that was reported earlier for interface `en0`. If your IP didn't change, that could be a clue as well.

**Comment by iJebus** [comment]
Yeah I've been working on this inside a work network and a home network so the IP changes, just to make things confusing 😓.

So, I just tested again on macOS and it's **working**. This is with nomad v1.2.3 and consul 1.11.1. I don't really why. It's possible it was IP related but I was generally pretty fussy about making sure to check/update that as I went, or at least I thought so.

Thanks @lgfa29 and @tgross for your time 🚀 💯

**Comment by lgfa29** [comment]
Nice, glad you got it to work now 😄

**Comment by iJebus** [comment]
There has to be something fishy with the home network, it's not working again. Clearly not a nomad problem though. I'll figure it out 😓 😂

**Comment by iJebus** [comment]
Not even the home network, as the Windows host was fine. After too much time spent debugging, I did a factory reset of Docker Desktop on macOS and it's working on the home network 🤷. Before anyone asks, no, there wasn't an overlap in the internal docker network and the home network. Anyway thanks again!

**Comment by lgfa29** [comment]
Since using specific IP addresses is giving you trouble on Mac, you can try using `host.docker.internal` instead. So your Traefik Consul config would look like this:

```toml
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "host.docker.internal:8500"
      scheme  = "http"
```

Or, to avoid special-casing the file to MacOS, you could conditionally set its value based on the client OS (not really tested):

```
{{$consul_addr := env "attr.unique.network.ip-address"}}
{{if eq (env "attr.os.name") "darwin"}}
{{$consul_addr = "host.docker.internal"}}
{{end}}
...
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "{{$consul_addr}}:8500"
      scheme  = "http"
```

See if this works for you.

**Comment by iJebus** [comment]
Sorry for any confusion, it's working perfectly fine on macOS after doing a factory reset on Docker Desktop. So it's closed/resolved. Thanks for reaching out again though.
