### ISSUE TITLE
Provision-A-Nomad-Cluster-in-the-Cloud, Vagrant Build Breaks

### ISSUE THREAD

**Issue by MikaelHashiCorp** [hashicorp/nomad#11536]
### Nomad version
Output from `nomad version`

N/A

### Operating system and Environment details

Ubuntu 18.04.6

### Issue

I am creating a Nomad AWS Cluster following https://github.com/hashicorp/nomad/tree/main/terraform#provision-a-nomad-cluster-in-the-cloud.  After I create the Vagrant staging area and log into it, I get an error running "terraform init":

vagrant@ubuntu-bionic:~/aws/env/us-east$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /home/vagrant/aws/env/us-east/main.tf: At 2:12: Unknown token: 2:12 IDENT var.region

vagrant@ubuntu-bionic:~/aws/env/us-east$ terraform --version
Terraform v0.11.0

Research states:

"...the Unknown token IDENT error can happen when your installed version on your local machine (or in the remote CI/CD server) is 0.11x and your code syntax is on 0.12x and you run a terraform command such as terraform init." (https://stackoverflow.com/questions/59471513/unknown-token-ident-aws-region)

When I update the file https://github.com/MikaelHashiCorp/nomad/blob/1-aws-nomad-cluster/terraform/Vagrantfile with updated Packer and Terraform versions:

PACKERVERSION=1.7.8
TERRAFORMVERSION=1.0.11

That solves the problem.

### Reproduction steps

git clone https://github.com/hashicorp/nomad.git
cd ./nomad/terraform
vagrant up && vagrant ssh
cd /home/vagrant/aws/env/us-east
terraform init

#### Expected Result

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /home/vagrant/aws/env/us-east/main.tf: At 2:12: Unknown token: 2:12 IDENT var.region

#### Actual Result

Terraform has been successfully initialized!

### Nomad Client logs (if appropriate
[Repro Terminal Output.txt](https://github.com/hashicorp/nomad/files/7567247/Repro.Terminal.Output.txt)
)

**Comment by jrasell** [comment]
Hi @MikaelHashiCorp and thanks for the report. I identified the issue that the Terraform syntax used is post-0.12 whereas the installed version of Terraform on the Vagrant machine was 0.11 and therefore incompatible. I have raised #11538 to fix this.
