### ISSUE TITLE
Starting allocations are not being accounted for while scaling

### ISSUE THREAD

**Issue by Rutori** [hashicorp/nomad#11530]
### Nomad version
1.1.5

### Issue
When jobs are being scaled automatically faster than they are being deployed, nomad adds allocations on top of all started allocations, without starting ones

### Reproduction steps
1. Create a service group with small cooldown in scaling policy
2. Make sure that service group will be scaled twice and the second scaling event happens before first deployment finishes 

#### Expected Result
For a group with 3 instances running and 2 starting there should be no new allocations after scaling to target count of 5

#### Actual Result
Nomad places 2 more allocations, and with the total amount of allocations now equal 7 the group count still shows 5 and after two of the four starting allocations will finally start they will instantly finish

**Comment by tgross** [comment]
Reviewing this and https://github.com/hashicorp/nomad-autoscaler/issues/540 I'm going to close out this issue in lieu of the issue in the autoscaler repo, which looks to be the right place for this.
