### ISSUE TITLE
alloc exec /bin/bash kills the running allocation

### ISSUE THREAD

**Issue by bgalvao** [hashicorp/nomad#11552]
### Nomad version
Output from `nomad version`
Nomad v1.1.6

### Operating system and Environment details
kernel x86_64 Linux 5.15.2-arch1-1 (Arch Linux)
Docker 20.10.10

### Issue
Attempting a `nomad alloc exec <alloc-hash> /bin/bash` kills the running allocation.

#### Expected Result
Dropping in the shell safely so I can inspect `$NOMAD*` variables.

#### Actual Result
A killed allocation and a restart.

### Job file (if appropriate)
```HCL
job "mlflow" {
  datacenters = ["dc1"]  # default when running dev mode
  type = "service"

  group "mlflow_group" {
    
    count = 1

    network {
      port "mlflow_ui_port" {}
    }

    task "mlflow" {
      driver = "docker"
      config {
        image = "brnrd0xgmi/mlflow-server"
        ports = ["mlflow_ui_port"]
        entrypoint = ["mlflow", "server"]
        args = [
          "--host", "0.0.0.0",
          "-p", "${NOMAD_PORT_mlflow_ui_port}"
        ]
      }
    }
  }
}

```

Additionally, that docker image was built as
```Dockerfile
FROM python:slim-buster
RUN pip install mlflow==1.21
```

### Nomad UI logs
![image](https://user-images.githubusercontent.com/17158288/142874126-f9f5c905-9009-4bc1-a4d5-84dff179241e.png)

**Comment by rigrassm** [comment]
It looks like when you opened the shell in the allocation it pushed the allocation over the jobs memory limit and was OOM Killed.

Try bumping the tasks memory limit in the job file (defaults to 300M) and see if that helps.

**Comment by jrasell** [comment]
Hi @bgalvao; as @rigrassm points out the task event `Exit Code: 137, Exit Message: "OOM Killed"` indicates opening a shell session within the task has pushed the container over its memory limit resulting in the OOM killer killing the container. I would suggest increasing the memory assignment within the task such that your job specification looks like the following:

```
job "mlflow" {
  datacenters = ["dc1"]  # default when running dev mode
  type = "service"

  group "mlflow_group" {

    count = 1

    network {
      port "mlflow_ui_port" {}
    }

    task "mlflow" {
      driver = "docker"
      config {
        image = "brnrd0xgmi/mlflow-server"
        ports = ["mlflow_ui_port"]
        entrypoint = ["mlflow", "server"]
        args = [
          "--host", "0.0.0.0",
          "-p", "${NOMAD_PORT_mlflow_ui_port}"
        ]
      }
      resources {
        memory = 400
      }
    }
  }
}
```

**Comment by bgalvao** [comment]
thanks :)
