### ISSUE TITLE
bump consul-template

### ISSUE THREAD

**Issue by blaggacao** [hashicorp/nomad#11568]
https://github.com/hashicorp/nomad/blob/e34931628ad6c767a69a4d12c683fad4d1a4aaf3/go.mod#L46

https://github.com/hashicorp/consul-template/pull/1432/commits/bb4e2b087099a2b98d0b462b6eb7ef29132b4326 only is on `v0.26.0`

**Comment by tgross** [comment]
Hi @blaggacao we've got https://github.com/hashicorp/nomad/pull/11472 open already, but we're looking into some minor backwards compatibility issues before merging that.
