### ISSUE TITLE
Allow configuring restart policy for Docker containers

### ISSUE THREAD

**Issue by kberzinch** [hashicorp/nomad#11566]
### Proposal

I would like to be able to configure the [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/) for Docker containers started by Nomad.

### Use-cases

I am running a single node in both client and server mode for a small on-prem deployment. Nginx is running in a Docker container and proxying to Nomad/Consul/other apps based on the Host header. I'm using Consul Template to dynamically generate the Nginx configuration based on Consul service registrations.

When the machine reboots, Nomad tries to signal the Nginx container before it is started (because other apps are registering/deregistering in consul), which fails, and so the job is marked as dead and I have to manually intervene. (This was already reported in #5459.)

This would also be nice to reduce downtime a bit, since the Docker daemon can restart a container faster than Nomad can.

### Attempted Solutions

I am currently using a `raw_exec` post-start task to run `/usr/bin/docker update --restart=always ${NOMAD_JOB_NAME}-${NOMAD_ALLOC_ID}`. This does work, but it adds additional complexity. I also used this for a different job that uses deployments (not Nginx) and ran into #10058.

I looked through the driver documentation and I don't see another way to do this.

**Comment by tgross** [comment]
@kberzinch this is currently handled via the [`restart`](https://www.nomadproject.io/docs/job-specification/restart) block. We don't intend to support handling this via the Docker daemon as well, as that'd create a bunch of new race conditions around task restarts. The bug in #5459 should get fixed, but providing this feature as a workaround will just create a bunch of new issues.

**Comment by kberzinch** [comment]
Fair enough. I do have `restart` configured as well, but it takes a little longer for that to kick in.
