### ISSUE TITLE
`helper` package functions to copy maps/slices encourage unsafe usage

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#11564]
The various generic copy helper functions in the [`helper`](https://github.com/hashicorp/nomad/blob/v1.2.0/helper/funcs.go#L301-L403) package return `nil` if the input is zero-length. This was likely done to save memory by avoiding heap-allocating empty maps and slices (a few pointers each). But this encourages usage where `nil` maps are being passed around and need to be checked _everywhere_ after a copy, or we can hit a panic. See https://github.com/hashicorp/nomad/issues/11563#issuecomment-977929300 for an example.

The functions have a lot of callers, so one approach we might want to consider here is having the `Copy` methods in the `nomad/structs` package use new variants that allocate the empty map.

**Comment by schmichael** [comment]
Fixed by #14139
