### ISSUE TITLE
Nomad client 1.2.x cli does not seem to import variables from file

### ISSUE THREAD

**Issue by johanforssell** [hashicorp/nomad#11560]
### Nomad version
Nomad v1.1.8 (41cda4cfb9589827da3e8759809c8d4014b97663)
Nomad v1.2.0 (0e11f8d5173e78dce23433903d086e3f9dfea7ea)
Nomad v1.2.1 (719c53ac0ebee95d902faafe59a30422a091bc31)

### Operating system and Environment details
macOS Monterey - 12.0.1

### Issue
```
$ > ./nomad-1.1.8 job validate -var-file=../../secrets/se2.secrets.hcl -var-file=../../vars/se2.hcl mongo.nomad                                                                                                             
Job validation successful

$ > ./nomad-1.2.1 job validate -var-file=../../secrets/se2.secrets.hcl -var-file=../../vars/se2.hcl mongo.nomad     
...                                                                                                        
Error getting job struct: Error parsing job file from mongo.nomad:
<nil>: Unset variable "nomad_w3"; A used variable must be set or have a default value; see https://www.nomadproject.io/docs/job-specification/hcl2/variables for details.
<nil>: Unset variable "env"; A used variable must be set or have a default value; see https://www.nomadproject.io/docs/job-specification/hcl2/variables for details.
<nil>: Unset variable "datacenters"; A used variable must be set or have a default value; see https://www.nomadproject.io/docs/job-specification/hcl2/variables for details.
<nil>: Unset variable "nomad_w1"; A used variable must be set or have a default value; see https://www.nomadproject.io/docs/job-specification/hcl2/variables for details.
```

#### Expected Result

Job file is supposed to be validated ok.

#### Actual Result

Nomad 1.2.0 and 1.2.1 no longer validates my job, which 1.1.8 does.

1.2.0 and 1.2.1 complains that the variables defined in external files are not present.

**Comment by jrasell** [comment]
Hi @johanforssell; without knowing exactly what the job and variables files contain, I believe this might be related to the two changes within https://github.com/hashicorp/nomad/pull/11165 and https://github.com/hashicorp/nomad/pull/11284. The first fixed an inconsistency with the way errors where generated when running HCLv2 parsing, the second allows for an escape hatch where this behaviour is not desirable for users.

If you could therefore run your 1.2.1 command using the `-hcl2-strict=false`, it would help identify whether this is a new bug or the result of these changes. If the problem persists, a small redacted reproduction jobspec and variables file would be really useful to help identify the issue.

**Comment by johanforssell** [comment]
I forgot about answering this one!

Adding `-hcl2-strict=false` does indeed solve this issue. Thank you
