### ISSUE TITLE
Documentation still documents no longer supported environment variables

### ISSUE THREAD

**Issue by hmeine** [hashicorp/nomad#11576]
### Nomad version
1.0.4

### Operating system and Environment details
macOS (client) / Linux (server), but that's probably not relevant

### Issue
As far as I can see, specifying `port_map` in a `network` section on the `task/resources` level has been deprecated long ago (since nomad 0.12.0).  Instead, we should specify `ports` in a `network` section on the `group` level. This requires also changing references to `${NOMAD_ADDR_<task>_<label>}` into just `${NOMAD_ADDR_<label>}`.

The issue I see is that https://www.nomadproject.io/docs/runtime/environment still documents the former kind of variables, without any hint that these are only present under certain circumstances. Since conceptually, one associates the ports with certain tasks, and one also still specifies `ports` in the `task/config`, it is not obvious that this cannot work.

### Reproduction steps
Visit https://www.nomadproject.io/docs/runtime/environment, try to run the attached .hcl file.

#### Expected Result
The docs should state that the client task must use `${NOMAD_ADDR_http}` (or the client task should not fail with a missing variable `${NOMAD_ADDR_httpserver_http}`).

#### Actual Result
The client task will fail with
* failed to parse config:
* Unknown variable: There is no variable named "NOMAD_ADDR_server_http".
although the docs seem to suggest that this should work.

### Job file (if appropriate)
```
job "nomad-env-docs-issue" {
    type = "batch"
    datacenters = ["cluster"]
  
    group "test-group" {
        network {
            port "http" {}
        }

        task "server" {
            driver = "docker"
            config {
                image = "python:latest"
                command = "python"
                args = [ "-m", "http.server", "${NOMAD_HOST_PORT_http}" ]
                ports = ["http"]
            }
        }

        task "client" {
            driver = "docker"
            leader = true
            config {
                image = "python:latest"
                command = "curl"
                args = [ "http://${NOMAD_ADDR_httpserver_http}" ]
            }
        }
    }
}
```

**Comment by jrasell** [comment]
Hi @hmeine and thanks for raising this issue. The documentation should certainly be clarified so this is easier to understand from a user perspective.
