### ISSUE TITLE
Documentation incorrectly describes value for volume mount_flags option in job specification

### ISSUE THREAD

**Issue by dcarbone** [hashicorp/nomad#11581]
### Nomad version
`Nomad v1.2.2 (78b8c171a211f967a8b297a88a7e844b3543f2b0)`

### Operating system and Environment details
Not relevant

### Issue
The [mount_flags](https://www.nomadproject.io/docs/job-specification/volume#mount_flags) option within the [mount_options](https://www.nomadproject.io/docs/job-specification/volume#mount_options) section of the [volume](https://www.nomadproject.io/docs/job-specification/volume) block suggests that the value must be a comma-delimited string of values.  In practice, this must be a slice of strings.

### Reproduction steps
1. Attempt to register job using this volume with `mount_flags` defined as comma-delimited string value:
```hcl
job "test-job" {
  group "test-group" {
    volume "test-volume" {
      mount_options {
        mount_flags = "rw,noatime"
      }
    }
  }
}
```

Note: You are able to see this error when attempting to register through the UI even with the above otherwise entirely invalid job spec.

#### Expected Result
Nomad is able to handle `mount_flags` value being a string, as suggested by documentation

#### Actual Result
You will receive an error stating:  `Unsuitable value type; Unsuitable value: list of string required`

### Job file (if appropriate)
```hcl
job "test-job" {
  group "test-group" {
    volume "test-volume" {
      mount_options {
        mount_flags = "rw,noatime"
      }
    }
  }
}
```

When separating it out into `["rw", "noatime"]`, job goes through / shows other relevant errors with job spec file.

**Comment by tgross** [comment]
Thanks @dcarbone! Will be fixed in https://github.com/hashicorp/nomad/pull/11583
