### ISSUE TITLE
improve documentation around monitoring recommendations

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#11597]
We currently have two sections in the operations docs around monitoring. The [Metrics](https://www.nomadproject.io/docs/operations/metrics) is just a reference doc for all the metrics Nomad emits, so we should rename this to **Metrics Reference**. Whereas the [Telemetry](https://www.nomadproject.io/docs/operations/telemetry) docs include the important [KPI](https://www.nomadproject.io/docs/operations/telemetry#key-performance-indicators) section that we want to surface to operators better and give more prescriptive guidance.

Some notes on subsections:
* [Consensus Protocol (Raft)](https://www.nomadproject.io/docs/operations/telemetry#consensus-protocol-raft): we should include recommendations for thresholds and trends to look out for in FSM apply times, raft replication RPC times, "large raft block" warnings, specific network latency metrics, and disk I/O latency metrics.
* [Federated Deployments (Serf)](https://www.nomadproject.io/docs/operations/telemetry#federated-deployments-serf): we should identify infrastructure metrics to monitor (specifically network latency and on which ports).
* [Scheduling](https://www.nomadproject.io/docs/operations/telemetry#scheduling) we should further clarify the specific meaning of "blocked" evaluations and queue depth and provide links to commands the operator can use to debug those evaluations.

**Comment by schmichael** [comment]
We discussed renaming `Telemetry -> Monitoring Nomad` as well and some folks I ran that past approved. Nobody can currently remember what the `Telemetry` page is for. :(

**Comment by tgross** [comment]
Work-in-progress here: https://github.com/hashicorp/nomad/pull/11623
