### ISSUE TITLE
debug level being logged in 1.2.x when log_level is info

### ISSUE THREAD

**Issue by mikehardenize** [hashicorp/nomad#11612]
### Nomad version

Nomad v1.2.2 (78b8c171a211f967a8b297a88a7e844b3543f2b0)

### Operating system and Environment details

Centos 7

### Issue

Since upgrading from 1.1.6 to 1.2.2, nomad has started logging DEBUG level logs, even though I've got `log_level = "INFO"` in my config. I believe this is the same issue as https://github.com/hashicorp/nomad/issues/11594 but I also think that it is an urgent issue which must be fixed before too many people start using it, so I have opened this card.

The reason I think it is important is I'm getting logging entries like:

`[INFO]  agent: 2021/12/03 11:03:18.663823 [DEBUG] (runner) final config: ...etc`

Where the `...etc` contains my raw job file contents. These files can contain information which should never get into logs, e.g db credentials or certificates etc. They do in my case, and I'm sure I'm not the only one. Our logs get shipped off to a third party log aggregator. Now our secrets have been leaked.

Nobody should use 1.2.x until this is fixed...

### Reproduction steps

Use 1.2.2. Set log_level to info. Create a job.

#### Expected Result

No debug logs

#### Actual Result

Debug logs

**Comment by tgross** [comment]
@mikehardenize you've already commented in https://github.com/hashicorp/nomad/issues/11594#issuecomment-985438720 so I'm going to close this as a dupe.
