### ISSUE TITLE
Command `nomad plan` output doesn't contain variables parameters

### ISSUE THREAD

**Issue by Liraim** [hashicorp/nomad#11616]
### Nomad version
Output from `nomad version`

Nomad v1.2.2

### Operating system and Environment details

Tested on MacOS and Windows.

### Issue

Running `nomad plan ...` command with `-var` or `-varfile` arguments doesn't contains this arguments in output (in `To submit the job with version verification run: ` part).

### Reproduction steps

Run valid `nomad plan` with `-var` or `-varfile` arguments and see output.

#### Expected Result

`nomad plan` output contains full `nomad run` command which can be copied and executed without additional actions. 

#### Actual Result

`nomad plan` output contains only partial output so before executing it, you need to manually add missing arguments.

**Comment by jrasell** [comment]
Hi @Liraim and thanks for raising this. The change makes a lot of sense and is something we should certainly include.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/11631 and will ship in the next release.
