### ISSUE TITLE
Learn guide isn't clear that clients must run as root

### ISSUE THREAD

**Issue by david-forster10** [hashicorp/nomad#11618]
### Nomad version
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)

### Operating system and Environment details
Red Hat Enterprise Linux Server 7.9 (Maipo)

### Issue
When running a Nomad Client as the nomad user, I get the following error regarding resource allocation:

Resources exhausted on 3 nodes
Dimension cores exhausted on 3 nodes

When I changed one of the servers to run as root, this error did not occur. When marking that server as inelligible, the error returns for the remaining two servers.

tl;dr Can't use core resource constraints in nomad running as a non-root user.

### Reproduction steps
Create service file that runs the service as the nomad user, as described [here](https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul), try running job that uses core allocation, will fail not being able to allocate. Modify same server / stand up different server as same service file but running as root, job allocation will be successful.

#### Expected Result
Nomad should allocate the job to all available clients (running as root or non-root)

#### Actual Result
Nomad won't allocate the job to any clients running under the nomad user due to resource exhaustion.

### Nomad Service file
```
[Unit]
Description=Nomad
Documentation=https://www.nomadproject.io/docs/

# When using Nomad with Consul it is not necessary to start Consul first. These
# lines start Consul before Nomad as an optimization to avoid Nomad logging
# that Consul is unavailable at startup.
Wants=consul.service
After=consul.service

[Service]
User=nomad
Group=nomad
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d
KillMode=process
KillSignal=SIGINT
LimitNOFILE=65536
LimitNPROC=infinity
Restart=on-failure
RestartSec=2

## Configure unit start rate limiting. Units which are started more than
## *burst* times within an *interval* time span are not permitted to start any
## more. Use  or  (depending on
## systemd version) to configure the checking interval and
## to configure how many starts per interval are allowed. The values in the
## commented lines are defaults.

# StartLimitBurst = 5

## StartLimitIntervalSec is used for systemd versions >= 230
# StartLimitIntervalSec = 10s

## StartLimitInterval is used for systemd versions < 230
# StartLimitInterval = 10s

TasksMax=infinity
OOMScoreAdjust=-1000

[Install]
WantedBy=multi-user.target
```

To run the service as root, I removed the User & Group parameters from the service file.

**Comment by jrasell** [comment]
Hi @david-forster10 and thanks for raising this issue. I believe we should update the documentation here as you pointed out in your final comment to ensure Nomad client's can run correctly.

**Comment by tgross** [comment]
Just a heads up that the installation production requirements have this update already ([ref](https://www.nomadproject.io/docs/install/production/requirements#user-permissions)). Looks like we need to update the Learn Guide.

**Comment by david-forster10** [comment]
Thanks both for the quick response.

**Comment by tgross** [comment]
PR for the Learn Guide is open ([ref](https://github.com/hashicorp/learn/pull/4203) for internal folks) but just as an FYI it usually takes a while for Learn Guide PRs to percolate out to the site. I'll keep this issue open till that ships.

**Comment by tgross** [comment]
https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul#configure-systemd has been updated.
