### ISSUE TITLE
first allocation of new job version does not always get NOMAD_ALLOC_INDEX = 0

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#11628]
### Nomad version
1.1.5

### Operating system and Environment details
Linux

### Issue

Context: In some of our services we rely on `NOMAD_ALLOC_INDEX=0` to perform db migrations, as we assumed that during job upgrade, the first allocation allocated for version n+1 always gets `NOMAD_ALLOC_INDEX=0`. However recently we found that was not the case if the job version change happen at the same time as an instance count change (scaling up).

When both job definition change and scaling up happens, e.g 1 -> 2, apparently Nomad does the scaling operation before rolling upgrade. So the current behavior (as we observed) is:
1. scaling up the instance count with new code to the desired number
2. rolling update any existing alloc to new code

The sequence of behavior is what causes the issue: the scaling operation creates new version with INDEX 1, **not 0**. Since INDEX 0 was supposed to perform the db migration, the new instance never gets the correct schema and eventually fails deployment. 

We were able to get around that by manually scaling count to 2, and then triggered the deployment again.

### Reproduction steps

1. deploy version n with count 1
2. deploy version n+1 with count 2

Watch the NOMAD_ALLOC_INDEX of the first scheduled version n+1 alloc.

#### Expected Result

NOMAD_ALLOC_INDEX for the first newly scheduled alloc should be 0.

#### Actual Result

NOMAD_ALLOC_INDEX is 1.

Also in general would like to ask if NOMAD_ALLOC_INDEX is intended for this purpose? If not could you recommend an alternative solution for guarantee uniqueness in running certain operation in a fleet of allocations?

**Comment by tgross** [comment]
Hi @fredwangwang! No, we don't recommend trying to use `NOMAD_ALLOC_INDEX` as a a "leader assignment", because it's not actually guaranteed to be unique. From the [runtime](https://www.nomadproject.io/docs/runtime/environment) docs:
> The index is unique within a given version of a job, but canaries or failed tasks in a deployment may reuse the index.

We haven't specifically documented that it can potentially skip an index as well, but that's not particular surprising in the face of a new version coming in during a deployment.

> If not could you recommend an alternative solution for guarantee uniqueness in running certain operation in a fleet of allocations?

I've successfully used Consul's compare-and-swap primitive with a TTL as a session lock. See the [Consul Sessions](https://www.consul.io/docs/dynamic-app-config/sessions) docs. Unfortunately Nomad doesn't currently support direct access to the Consul API for tasks, but if you give the task a Consul ACL token it should be possible to do leader-locking this way.

**Comment by fredwangwang** [comment]
Hi @tgross thanks for the reply! 

We are not "strictly" using it as a "leader", since we care less about global uniqueness, really just unique within the same job version (so one instance in every version can initiate db migration). That's why we used NOMAD_ALLOC_INDEX, as the semantics does seem to match what we want... But yeah good to confirm is not officially supported so we can steer away from it.. Kinda curious what is the intended use of this variable tho 🤔

And regarding to using Consul Sessions, do you have a reference implementation? 🙂

**Comment by tgross** [comment]
> Kinda curious what is the intended use of this variable tho

I think the answer to that was "it was there" and we probably regret having it at this point 😁 

> And regarding to using Consul Sessions, do you have a reference implementation?

I asked around about a reference implementation and unfortunately I don't have one handy. A long while back I did some fairly non-Nomad work with this in Python [here](https://github.com/autopilotpattern/mysql/blob/master/bin/manager/discovery.py#L54) (I wouldn't recommend most of the rest of that code at this point, FYI, but the session locking works fine). We're also talking about having some means of doing this kind of thing in core Nomad as well, but that'll be sometime next year.

Thanks for opening this issue @fredwangwang. I'm going to close it out.
