### ISSUE TITLE
Unable to submit a Nomad-produced JSON job

### ISSUE THREAD

**Issue by multani** [hashicorp/nomad#1163]
### Nomad version
```
$ nomad version
Nomad v0.3.2
```

### Operating system and Environment details
Running Nomad from Vagrant using https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile

### Issue
The JSON file produced by ```nomad run -output job.nomad``` can't be feed back to Nomad.

### Reproduction steps
I'm trying to run the following (simplest job definition I was able to make?):
```
vagrant@nomad:~$ cat hello.nomad
job "hello-world-service" {
    datacenters = ["dc1"]

    group "hello" {
        task "hello" {
            driver = "docker"
            config { image = "hello-world" }
            resources {}
        }
    }
}
vagrant@nomad:~$ nomad validate hello.nomad
Job validation successful

vagrant@nomad:~$ nomad run -output hello.nomad > hello.nomad.json
vagrant@nomad:~$ nomad validate hello.nomad.json
Error parsing job file hello.nomad.json: 1 error(s) occurred:

* invalid key: Job


vagrant@nomad:~$ nomad run hello.nomad
==> Monitoring evaluation "a048e608"
    Evaluation triggered by job "hello-world-service"
    Allocation "07d4fef5" modified: node "7f918375", group "hello"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "a048e608" finished with status "complete"

vagrant@nomad:~$ nomad run hello.nomad.json
Error parsing job file hello.nomad.json: 1 error(s) occurred:

* invalid key: Job
```

### Job file
```
job "hello-world-service" {
    datacenters = ["dc1"]

    group "hello" {
        task "hello" {
            driver = "docker"
            config { image = "hello-world" }
            resources {}
        }
    }
}
```

**Comment by multani** [comment]
However, passing the JSON job directly via the HTTP API works correctly, so I guess it's only a validation problem while reading the job definition.

**Comment by dadgar** [comment]
Hey,

`nomad validate` and `nomad run` only operate on HCL jobs and not JSON jobs. Will update the documentation.

Thanks,
Alex

**Comment by multani** [comment]
Oh well, I had some doubts about it, but the documentation and the error message aren't very clear about it.
