### ISSUE TITLE
raw_exec driver can't find binary on Windows

### ISSUE THREAD

**Issue by dg-eparizzi** [hashicorp/nomad#11659]
### Nomad version
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)

### Operating system and Environment details
Windows 10 Enterprise LTSC
Version 1809
OS build 17763.2061

### Issue
Nomad client can't seem to find any binaries. This is running in a single node acting as server and client, installed as a Windows Service and running as "Local System".

### Reproduction steps
Setup a single-node server/client Nomad on Windows 10 running as a Windows Service.
Try to run a binary using the raw_exec driver.

#### Expected Result
Binary is found and process executes.

#### Actual Result
Task fails. Allocation shows the following event:
```
Driver Failure   | failed to launch command with executor: rpc error: code = Unknown desc = binary "C:\\Program Files\\nodejs\\node.exe" could not be found
```

### Job file (if appropriate)
```
variable "service_root_dir" {
  type = string
}

job "logging-system" {
  datacenters = ["dc1"]
  type = "service"

  group "data-logs-to-influxdb" {
    reschedule {
      attempts       = 15
      interval       = "1h"
      delay          = "30s"
      delay_function = "exponential"
      max_delay      = "60s"
      unlimited      = false
    }

    task "data-logs-to-influxdb" {
      driver = "raw_exec"
      config {
        command = "C:\\Program Files\\nodejs\\node.exe"
        args    = ["${var.service_root_dir}\\dist\\apps\\data-logs-to-influxdb\\main.js"]
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
```
2021-12-09T19:40:45.322Z [WARN]  client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=c46de00d-10d0-43dc-6b02-896582f6bf55 task=data-logs-to-influxdb keys=
2021-12-09T19:40:54.304Z [ERROR] client.driver_mgr.raw_exec: destroying executor failed: driver=raw_exec err="rpc error: code = Unknown desc = executor failed to find process: OpenProcess: The parameter is incorrect."
2021-12-09T19:40:54.305Z [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=c46de00d-10d0-43dc-6b02-896582f6bf55 driver=raw_exec task_name=data-logs-to-influxdb error="rpc error: code = Unavailable desc = transport is closing"
```

**Comment by tgross** [comment]
Hi @dg-eparizzi! I've checked and it looks like the path separator escaping you're using should be good ([example from a colleague](https://github.com/lgfa29/hashitalks-brasil-2020/blob/main/cluster/win.nomad#L14)). As a test, what does the following job produce in its allocation logs?

```hcl
job "test" {
  datacenters = ["dc1"]
  group "test" {
    task "test" {
      driver = "raw_exec"
      config {
        command = "powershell"
        args = ["Get-Item", "C:\\Program Files\\nodejs\\node.exe"]
      }
    }
  }
}
```

It might help if you turned on debug logging as well.

**Comment by tgross** [comment]
Ok, I suppose that makes sense because of how powershell wants to quote things. Isn't the `a` mode for "archive"? I don't have a Windows machine in front of me but is that typically how executables look?

**Comment by dg-eparizzi** [comment]
I don't really know, it's just an .exe from the official Node.js installer. I don't see why Nomad would have any problem executing it...

Also, trying to run any powershell script fails.

C:\hello.ps1
```
echo "Hello world"
```

Job definition:
```
job "test" {
  datacenters = ["dc1"]
  group "test" {
    task "test" {
      driver = "raw_exec"
      config {
        command = "powershell"
        args = ["-File", "C:\\hello.ps1"]
      }
    }
  }
}
```

alloc stderr output
```
The argument 'C:\hello.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

I really don't understand how Nomad has such issues trying to run a simple Powershell script. Isn't the raw_exec leveraging the OS execution mechanism?

**Comment by dg-eparizzi** [comment]
I don't really know, it's just an .exe from the official Node.js installer. I don't see why Nomad would have any problem executing it...

Also, trying to run any powershell script fails.

C:\hello.ps1
```
echo "Hello world"
```

Job definition:
```
job "test" {
  datacenters = ["dc1"]
  group "test" {
    task "test" {
      driver = "raw_exec"
      config {
        command = "powershell"
        args = ["-File", "C:\\hello.ps1"]
      }
    }
  }
}
```

alloc stderr output
```
The argument 'C:\hello.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

I really don't understand how Nomad has such issues trying to run a simple Powershell script. Isn't the raw_exec leveraging the OS execution mechanism?

**Comment by tgross** [comment]
> I really don't understand how Nomad has such issues trying to run a simple Powershell script. Isn't the raw_exec leveraging the OS execution mechanism?

Yup. And we test [just that scenario](https://github.com/hashicorp/nomad/blob/main/e2e/metrics/input/factorial_windows.nomad) on the nightly basis in our E2E suite. My colleague @lgfa29 and I looked at his Windows environment and tried launching a job configured like yours and it worked. 

Maybe the service configuration has something we're not accounting for. In our E2E suite we're using [`New-Service`](https://github.com/hashicorp/nomad/blob/main/e2e/terraform/packer/windows-2016-amd64/provision.ps1#L218-L233) to register Nomad as a service. Can you share how you're configuring the service in your environment? It might also be worth testing with the Nomad agent in dev mode (`nomad agent -dev`) to see if we can narrow things down.

**Comment by dg-eparizzi** [comment]
I'm testing this with nomad 1.1.4 installed via Chocolatey which I've just realized it's using NSSM to register it as a Windows Service.

I'm going to try installing latest Nomad version without Chocolatey and using the official documentation to set it up as a Windows service (https://www.nomadproject.io/docs/install/windows-service#register-nomad-with-windows) and I'll get back to you.

Thanks for all the help so far.

**Comment by dg-eparizzi** [comment]
Nope, when running it as a Windows Service with the following config is not able to execute Powershell scripts...

```
data_dir  = "C:\\ProgramData\\nomad\\data\\"

log_file = "C:\\ProgramData\\nomad\\logs\\"
log_rotate_duration = "24h"
log_rotate_max_files = 30

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled       = true
  servers       = ["172.18.0.5"]
}

plugin "raw_exec" {
  config {
    enabled = true
  }
}
```
The alloc stderr logs again
``` 
The argument 'C:\hello.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

**Comment by tgross** [comment]
Ok, because it worked in dev mode that narrows it down to the service environment. I'm going to try to pull in some help from a colleague who has a Windows 10 machine around so we can get some focused debugging on the issue.

**Comment by lgfa29** [comment]
Hi @dg-eparizzi 👋 

I tried your provided example on my machine and it seems to have worked fine:
﻿﻿
![image](https://user-images.githubusercontent.com/775380/145647585-88d2994c-dfbd-4584-8a36-5e8affee2bbd.png)

A few things that have come to mind:

1. Are you running with Administrator privileges? Maybe the user that is running the Nomad process doesn't have access to these files?
2. Do you have multiple clients? If the allocation runs in a client that doesn't the file it will error like this as well.

**Comment by dg-eparizzi** [comment]
Wow, you're totally right. At some point during testing this I've added another client node from another machine and it seems the jobs were being scheduled to run on that client which didn't have the files.

Sorry about that.

**Comment by lgfa29** [comment]
No problem! I'm glad it was a simple fix 😄
