### ISSUE TITLE
nomad doesn't respect task.user config for docker containers

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#11670]
### Nomad version
`1.2.3`

### Operating system and Environment details
amazonlinux2

### Issue
docker installed via `amazon-linux-extras` - v20.10.7

### Reproduction steps

I'm setting user at the task level

```
job "loki" {
  type = "service"
  group "loki" {
    count = 1
    task "loki" {
      driver = "docker"
      user = "loki"
    }
  }
}
```

```
ps aux|grep loki
10001     5847  0.0  1.2 753620 49940 ?        Ssl  21:56   0:00 /usr/bin/loki -config.file local/loki/local-config.yaml
```

#### Expected Result
container would be launched as user loki

#### Actual Result
container launched as user `10001`

The `Loki` user exists on the system and is available to be used:
```
grep loki /etc/passwd
loki:x:1006:1006::/home/loki:/bin/bash
```

### Nomad Server logs (if appropriate)
I haven't found any logs that seem to be relevant.  I've actually found zero logs from nomad that reference launching containers.  I'm happy to provide anything.

**Comment by tgross** [comment]
I'm going to close this issue out because I think we've answered it. But if not, please feel to reopen. Thanks!
