### ISSUE TITLE
[question] Data transfer between server and clients

### ISSUE THREAD

**Issue by michaelimfeld** [hashicorp/nomad#1171]
Hi!

Is it possible to mount 'Volumes' (docker like) on the clients for a specific job when using the `exec` task driver? What is the recommended way of sharing data between server and clients? 
I also wonder if there is a way to use a custom chroot?

Thanks in advance!

**Comment by dadgar** [comment]
Hey Micheal,

1) Currently there is no support for Volumes. This is on our roadmap however. 
2) Would you mind clarifying what you mean? Maybe a use case would be helpful
3) Currently there is not. This is something we would also like to do! 

Thanks,
Alex

**Comment by michaelimfeld** [comment]
I see. I'm trying to use the nodes as build slaves for debian package building. For that I need to be able to copy source packages over to the client, let the client build them and transfer the built packages back to the master.

**Comment by dadgar** [comment]
Ah, I would use the artifact block and download the source code to the slaves. They could then send the built packages to the server via an HTTP server or upload to S3. Something in that vain. Anyways I am going to close this issue. If you have more questions lets move it to the mailing list.

**Comment by michaelimfeld** [comment]
Aight thanks a lot!
