### ISSUE TITLE
artifact key "destination" leads to parse error

### ISSUE THREAD

**Issue by rmmjohann** [hashicorp/nomad#1172]
If filing a bug please include the following:

### Nomad version
Nomad v0.3.1

### Operating system and Environment details
Ubuntu 14.04 LTS

### Issue
If artifact key "destination" will be provided an error occurs when submitting the job:

Error parsing job file nomad/jobs/spark.nomad: error parsing 'job': 1 error(s) occurred:
* group: 'spark-master-group', task: 'spark-master', artifact -> invalid key: destination

```hcl
artifact {
  source = "http://apache.lauf-forum.at/spark/spark-1.6.0/spark-1.6.0-bin-hadoop2.6.tgz"
  destination = "/opt"
}
```

**Comment by dadgar** [comment]
Hey this feature was added to 0.3.2. Please upgrade your Nomad version!

**Comment by rmmjohann** [comment]
thanks for quick reply!
