### ISSUE TITLE
hcl: difference between HCLv1 and HCLv2 when utilising Docker labels

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#11759]
### Nomad version
Tested on main at `578a9a616674aca7cf6d3cd055b81b35504f1f7c`.

### Operating system and Environment details
Reproduced using the Nomad Vagrant machine.

### Issue
The behaviour of setting [Docker driver config labels](https://www.nomadproject.io/docs/drivers/docker#labels) on a job specification seems to differ between HCLv1 and HCLv2. The documentation does not work when utilising HCLv2 parsing; I am unsure at this moment whether this is a documentation bug or a bug in the HCLv2 parsing. The error reports comes from [this Discuss post](https://discuss.hashicorp.com/t/issue-with-docker-labels-having-a-dot/33474); I am unsure if there are other occurrences of this.

### HCLv1
In order to set Docker driver config labels using HCLv1 syntax, the following job can be submitted using the `nomad job run -hcl1 <job_file>`.

```hcl
job "example" {
  datacenters = ["dc1"]
  group "cache" {
    task "redis" {
      driver = "docker"
      config {
        image = "redis:3.2"
        labels { "this.is.a.label.key" = "value" }
      }
    }
  }
}
```

Running this job file when omitting the `hcl1` flag, however, results in an error.
```
Error getting job struct: Failed to parse using HCL 2. Use the HCL 1 parser with `nomad run -hcl1`, or address the following issues:
example.nomad:8,18-19: Argument or block definition required; An argument or block definition is required here.
```

### HCLv2
The following altered jobspec works when submitting the job using the HCLv2 parser.

```hcl
job "example" {
  datacenters = ["dc1"]
  group "cache" {
    task "redis" {
      driver = "docker"
      config {
        image = "redis:3.2"
        labels = { "this.is.a.label.key" = "value" }
      }
    }
  }
}
```

**Comment by schmichael** [comment]
I updated the docs in #24074, so I think we can close this. Let's open a new issue if there's still a problem.
