### ISSUE TITLE
A typos in doc

### ISSUE THREAD

**Issue by liugang-sd** [hashicorp/nomad#11756]
### Nomad version
Output from `nomad version`

### Issue
https://learn.hashicorp.com/tutorials/nomad/access-control-policies?in=nomad/access-control

The word 'course' maybe a typos ,should be 'coarse', please fix it.

**Comment by jrasell** [comment]
Hi @liugang-sd and thanks for spotting this. I have raised a PR against the private repository where this code resides that fixes this typo. I'll keep this issue open until that is merged for visibility.
