### ISSUE TITLE
Please add `nomad fmt` command

### ISSUE THREAD

**Issue by nahsi** [hashicorp/nomad#11757]
Please provide command `fmt` to format nomad jobs analogous to `terraform fmt` and `packer fmt`.

Right now I'm using `hclfmt` from [hcl repo](https://github.com/hashicorp/hcl/tree/main/cmd/hclfmt).

To install it I use this command `go install github.com/hashicorp/hcl/v2/cmd/hclfmt@latest`.

**Comment by jrasell** [comment]
Hi @nahsi and thanks for raising this request. I believe this addition would be very useful!

**Comment by rounakdatta** [comment]
Hi @jrasell @mikenomitch is the `nomad fmt` command expected to be just a usage of `hclfmt` or would we like to re-implement the formatting specifically for the Nomad specification?

**Comment by danishprakash** [comment]
@jrasell I'm not entirely sure but I guess this should involve using `tfexec` to invoke `hclfmt` internally and overwrite the source file? I've seen something similar happen over at `terraform-ls` for terraform fmt. If that sounds like the right direction, I'd like to work on this.

**Comment by mikenomitch** [comment]
Hey @rounakdatta, yeah I think just using `hclfmt` would be fine!

If you base the implementation off of [Packer's code](https://github.com/hashicorp/packer/blob/main/command/fmt.go#L16), that could be a really good starting point if you'd like to contribute.

@danishprakash, I think anything that relies on TF is going to be a no-go from our perspective. While we of course love TF, we don't want that as a hard dependency for Nomad.

**Comment by danishprakash** [comment]
@mikenomitch you're right, I think I thought we could do something similar to how we do it in terraform-ls for the formatting even from the client but I now realize, as the name suggests, `tfexec` is in fact built for executing `terraform` commands. The link you shared from Packer looks more aligned and reasonable. I'd like to give this a shot if no one else has started working on this already. Thanks

**Comment by rounakdatta** [comment]
Alright @mikenomitch , I've started looking into Packer's implementation. It's clear, and I think I'll be able to make some progress tonight/tomorrow. @danishprakash I was willing to try my first Nomad contribution through this issue 🙂

**Comment by danishprakash** [comment]
Sure @rounakdatta, please feel free to take this up!

**Comment by sharmaansh21** [comment]
@rounakdatta Are you working on this ?

**Comment by Trojan295** [comment]
Hello, if there is nobody working on that right now, I would like to implement the `nomad fmt`.

My idea is to implement it like here [hclfmt](https://github.com/hashicorp/hcl/blob/f6abd7d6e0b044a58f14e21f51546407b53247f8/cmd/hclfmt/main.go).

**Comment by mikenomitch** [comment]
Hey @Trojan295, thanks so much for taking this! This will make a lot of people happy.

I think if you try to roughly match [terraform's fmt command](https://developer.hashicorp.com/terraform/cli/commands/fmt) that would be ideal.

So if you have no argument (just `nomad fmt` ) mean "the current directory", and then also read from STDIN with a single dash "-" argument that'd be great. To show help you would enter `nomad fmt -h`.

I don't think it is necessary to add the `-diff` flag on the initial PR.

**Comment by tgross** [comment]
PR is open on this and likely to merge for an early Nomad 1.4.x. I'll track this issue until that's been merged. Thanks, all!
