### ISSUE TITLE
sortable Evaluation and Deployment IDs

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#11779]
We recently added pagination to the Evaluation List and Deployment List APIs, but the pages are by default sorted by-ID and not by-time, whereas by-time is the most useful view over these APIs. Without pagination, the CLI grabs the whole list and sorts by time client-side. 

While thinking about how to improve this (https://github.com/hashicorp/nomad/issues/11742) I realized that evaluations and deployments could use [ULIDs](https://github.com/ulid/spec) which are naturally sorted by time. 

Because the existing IDs are UUIDs, are generated by the RPC server or scheduler, and are relatively short-lived compared to other state store objects, it'd be entirely backwards compatible to introduce ULIDs without worrying about collisions or having to modify the state store schema. 

There are two caveats: 
* We'd need to encode the ULIDs in UUID format because of the existing state store schema. But that's no big deal.
* "Short" evaluation and deployment IDs would be more likely to collide so we'd probably want to show more of the ID in the CLI (enough to get the timestamp with 1sec or even 1min resolution is likely to be enough for prefix matching).

Before proposing this I wanted to examine whether this would have negative impact on the performance of the state store, so I wrote a benchmark exercising this in the [`sortable_ids`](https://github.com/hashicorp/nomad/compare/sortable_ids) branch. When I re-run this benchmark the difference in results are pretty noisy, but I fairly consistently see a _slight_ improvement in insert performance (~5%) without a penalty on iteration performance.

```
$ go test -v ./nomad/state -bench Benchmark_Evals -run X
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/nomad/nomad/state
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
Benchmark_EvalsIDGeneration
Benchmark_EvalsIDGeneration/uuid_insert
Benchmark_EvalsIDGeneration/uuid_insert-8                      5         223683990 ns/op
Benchmark_EvalsIDGeneration/uuid_iterate
Benchmark_EvalsIDGeneration/uuid_iterate-8                  4105            274762 ns/op
Benchmark_EvalsIDGeneration/ulid_insert
Benchmark_EvalsIDGeneration/ulid_insert-8                      5         209742486 ns/op
Benchmark_EvalsIDGeneration/ulid_iterate
Benchmark_EvalsIDGeneration/ulid_iterate-8                  5104            235695 ns/op
PASS
ok      github.com/hashicorp/nomad/nomad/state  8.510s
```

**Comment by tgross** [comment]
Some notes from an internal discussion on this:
* we should benchmark the ID generation itself
* we should see if any of the other products use a ULID library so that we can share libraries across products
* the upgrade path for paginated endpoints won't be totally smooth because the old IDs won't sort correctly. but those will quickly age-out.

**Comment by schmichael** [comment]
> we should benchmark inserting/iterating ULIDs that are spread out over a long period of time to make sure there's no unexpected behavior on the immutable radix library here

To add a bit more detail here: my main concern is that we're switching from a uniformly distributed ID (random) to an ID where the first few bytes will almost always be the same. A pretty extreme switch from an indexing standpoint. We have a pretty good idea of a reasonably "high load" situation for ID generation, so we should be able to benchmark the impact of that on statestore/memdb insertion, iteration, and GC:

- Since deployments are largely limited by Raft, the rate of Deployment ID creation and insertion should never exceed `10s-of-thousands per second`.
- Evaluations are created by [`Job.Register`](https://github.com/hashicorp/nomad/blob/v1.2.2/nomad/job_endpoint.go#L360-L370) and potentially [`Node.Register`](https://github.com/hashicorp/nomad/blob/v1.2.2/nomad/node_endpoint.go#L173-L181) and [`Node.UpdateStatus`](https://github.com/hashicorp/nomad/blob/v1.2.2/nomad/node_endpoint.go#L494-L501), so a poorly behaved Node or Job submitter *could* create Evaluation IDs at a rate only bounded by server CPU time. However, the `10s-of-thousands per second` still seems like a reasonable test case to me as if something more pathological is occurring, the performance of the radix tree is unlikely to be anyone's greatest concern.

So synthesizing 10k insertions per second for a few seconds seems like a good pathological test case. If ULIDs are in the same order of magnitude UUIDs performance I think that's likely good enough to ship. Obviously if ULIDs perform better that's great!

**Comment by apollo13** [comment]
Please share the results of those new benchmarks. While it is true that switching from random to time based is an extreme switch from an indexing standpoint it could also be that it is actually faster since a new entry ends up close to the previous one which might be beneficial for cache usage etc (then again I am just guessing).

**Comment by tgross** [comment]
Ok, so I've reworked the benchmarks so that we have 2 top-level benchmarks, one for iterating over 10k evaluations, and one for inserting 10k evaluations into a state store that already has 10k evaluations. The inserts are each in their own transaction; this is less efficient but matches the production use case where individual RPC calls will write one evaluation at a time.

Within each of those benchmarks we test with:
* UUID
* ULIDs that are spread out over several hours
* ULIDs that are generated extremely close together (within a few milliseconds for the whole set of 10k).

I used the `-benchtime` flag to make sure we're really soaking these to reduce the noise, and ran the benchmarks three times on top of that and got directionally similar results with all three runs.

**Iteration**

ULIDs are slightly faster to iterate over, even more so if they're spread out over several hours. Iterating over closely-spaced ULIDs was ~3% faster than UUIDs, and iterating over spread-out ULIDs was ~9% faster than UUIDs.

Raw data of 3 runs, times in nanoseconds. Note that because these are iterations over 10k evaluations, the characteristic times here are ~20-25 nanoseconds per evaluation.

| UUID   | ULID inserted closely | ULID inserted over hours |
|--------|-----------------------|--------------------------|
| 233474 | 230271                | 215624                   |
| 243227 | 229348                | 216221                   |
| 229838 | 227523                | 208622                   |

<img width="599" alt="Screen Shot 2022-01-06 at 11 23 40 AM" src="https://user-images.githubusercontent.com/1409219/148419027-dc1df2bb-9038-4b14-a454-5f58f426882a.png">

**Insertion**

ULIDs _are_ slower to insert when closely spaced together (good call, @schmichael!) but slighty faster to insert when spread out. Inserting closely spaced ULIDs was ~13% slower than inserting UUIDs. Inserting spread-out ULIDs was ~6% faster than inserting UUIDs.

Raw data of 3 runs, times in nanoseconds. Note that because these are insertions of 10k evaluations, the characteristic times here are ~20-25 microseconds per evaluation and includes transaction overhead.

| UUID      | ULID inserted closely | ULID inserted over hours |
|-----------|-----------------------|--------------------------|
| 224852396 | 253873539             | 207173371                |
| 225827391 | 255754390             | 215606895                |
| 222277185 | 255384533             | 211635326                |

<img width="599" alt="Screen Shot 2022-01-06 at 11 25 37 AM" src="https://user-images.githubusercontent.com/1409219/148419055-67ce65c7-3c33-4e36-8d84-fdaad4e11f51.png">

**Example benchmark run**

```
$ go test -v ./nomad/state -bench Benchmark_SortableIDs -benchtime 10s -run X
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/nomad/nomad/state
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
Benchmark_SortableIDs_Iteration
Benchmark_SortableIDs_Iteration/uuid_iterate
Benchmark_SortableIDs_Iteration/uuid_iterate-8             50836            233474 ns/op
Benchmark_SortableIDs_Iteration/ulid_iterate_inserted_closely
Benchmark_SortableIDs_Iteration/ulid_iterate_inserted_closely-8                    51556            230271 ns/op
Benchmark_SortableIDs_Iteration/ulid_iterate_inserted_over_hours
Benchmark_SortableIDs_Iteration/ulid_iterate_inserted_over_hours-8                 53296            215624 ns/op
Benchmark_SortableIDs_Upserts
Benchmark_SortableIDs_Upserts/uuid_upsert_eval
Benchmark_SortableIDs_Upserts/uuid_upsert_eval-8                                      51         224852396 ns/op
Benchmark_SortableIDs_Upserts/ulid_upsert_eval_closely
Benchmark_SortableIDs_Upserts/ulid_upsert_eval_closely-8                              46         253873539 ns/op
Benchmark_SortableIDs_Upserts/ulid_upsert_eval_over_hours
Benchmark_SortableIDs_Upserts/ulid_upsert_eval_over_hours-8                           56         207173371 ns/op
PASS
ok      github.com/hashicorp/nomad/nomad/state  82.363s
```

**Comment by tgross** [comment]
My tl;dr take on this is that although _very_ tight insertion patterns are going to take a small performance hit on this, that the difference in performance is almost 3 orders of magnitude less than the time it takes to make a raft transaction. Iteration is actually improved, and we get better semantics for sorting. So this feels like a win to me.

**Comment by tgross** [comment]
Actually, one more test to do, which is to have the evaluations generated in-line with the insertion so that we can include the cost of generating the ULID vs the UUID.

**Comment by tgross** [comment]
Ok, I've added two more top-level tests, one that just tests ID generation and one that includes the ID generation in upserting the eval.

**ID generation**

I was surprised to find that ULID generation is quite a bit faster than UUID generation, at least with the libraries chosen here. I tested this on both macOS and Linux (just to make sure I wasn't hitting unexpected vDSO boots), and it was consistent:

```
$  go test -v ./nomad/state -bench Benchmark_SortableIDs_Generation -benchtime 5s -run X
goos: linux
goarch: amd64
pkg: github.com/hashicorp/nomad/nomad/state
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
Benchmark_SortableIDs_Generation
Benchmark_SortableIDs_Generation/generate_ulids
Benchmark_SortableIDs_Generation/generate_ulids-4                    808           7154906 ns/op
Benchmark_SortableIDs_Generation/generate_uuids
Benchmark_SortableIDs_Generation/generate_uuids-4                    222          26813814 ns/op
```

**Create and Upsert**

The final test was to create the evaluations as we were inserting them, just as we would in normal production usage. The differences between each of the three variations is roughly the same as the previous upsert tests. So it's modestly slower for evaluations that are very close together in time. But I think the same conclusion applies in terms of it being worth it.

```
$ go test -v ./nomad/state -bench Benchmark_SortableIDs_CreateAndUpsert -benchtime 10s -run X
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/nomad/nomad/state
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
Benchmark_SortableIDs_CreateAndUpsert
Benchmark_SortableIDs_CreateAndUpsert/uuid_upsert_eval
Benchmark_SortableIDs_CreateAndUpsert/uuid_upsert_eval-8                      43         267865115 ns/op
Benchmark_SortableIDs_CreateAndUpsert/ulid_upsert_eval_closely
Benchmark_SortableIDs_CreateAndUpsert/ulid_upsert_eval_closely-8              40         285587832 ns/op
Benchmark_SortableIDs_CreateAndUpsert/ulid_upsert_eval_over_hours
Benchmark_SortableIDs_CreateAndUpsert/ulid_upsert_eval_over_hours-8                   46         263162762 ns/op
PASS
ok      github.com/hashicorp/nomad/nomad/state  37.610s
```

**Comment by tgross** [comment]
I was reminded we still had this issue open and that there's one unfortunate bit of this, which is that it makes short IDs (8 chars) _much_ less useful and that has ripple-effects throughout the entire CLI.

**Comment by tgross** [comment]
Doing a little issue cleanup. The UX hit and backwards compatibility concerns really make this a non-starter. Interesting experiment, but going to close it out.
