### ISSUE TITLE
Dynamic port too high for Linux

### ISSUE THREAD

**Issue by mooijtech** [hashicorp/nomad#11772]
Nomad gives my task a dynamic port of ```136727``` but this is too high for Linux, the port range is ```1-65535```.
When trying to start my Go HTTP server on this port I get (even when running as sudo):
```
listen tcp: address 136727: invalid port
```

**Comment by mooijtech** [comment]
Actually this is probably my fault because I am parsing the environment variable incorrectly:
```
port, err := strconv.ParseInt(os.Getenv("NOMAD_PORT_http"), 16, 64)
```

**Comment by DerekStrickland** [comment]
Hi @mooijtech 

Were you able to confirm the issue is on your end?  Should we close this issue?

**Comment by mooijtech** [comment]
Hello, my apologies for making an issue too quickly but thanks for your quick response.
The issue was on my end by parsing the int incorrectly, this fixes it:
```
	port, err := strconv.Atoi(os.Getenv("NOMAD_PORT_http"))
```
