### ISSUE TITLE
Nomad keeps restarting the job every 5 minutes when using both vault and consul templates

### ISSUE THREAD

**Issue by paladium** [hashicorp/nomad#11782]
### Nomad version
Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)

### Operating system and Environment details
Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎4/‎2/‎2021
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0
Device name	imusayev-hp
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
### Issue
When I run the job that uses both secrets from Vault and key values from consul, my job keeps restarting every 5 minutes.
### Reproduction steps
Create a new job that utilises both vault and consul data and wait for a few minutes to observe it being restarted.
#### Expected Result
The job only being restarted once there are some changes.
#### Actual Result
The job keeps getting restarted every 5 minutes when there are no changes both in vault or consul.
### Job file (if appropriate)
This is the redacted version of the job file:
```
      vault {
        policies = ["read-only"]
      }
      template {
        data        = "{{ key \"configs/ServiceName/appsettings.json\" }}"
        destination = "Deployment/bin/appsettings.json"
      }
      template {
        data        = "{{ key \"configs/ServiceName/nlog.config\" }}"
        destination = "Deployment/bin/nlog.config"
      }
      template {
        data        = <<EOH
SQLDBOPTIONS__CONNECTIONSTRING="{{with secret "secret/data/database"}}{{.Data.data.connection_string}}{{end}}"
        EOH
        destination = "secrets/file.env"
        env         = true
      }
```
### Nomad Client logs (if appropriate)
```
2022/01/06 17:13:02.021957 [TRACE] vault.read(secret/data/database): non-renewable secret, set sleep for 4m43.323959237s
2022/01/06 17:13:02.022466 [TRACE] (view) vault.read(secret/data/database) marking successful data response
2022/01/06 17:13:02.022466 [TRACE] (view) vault.read(secret/data/database) successful contact, resetting retries
2022/01/06 17:13:02.022466 [TRACE] (view) vault.read(secret/data/database) received data
2022/01/06 17:13:02.022466 [TRACE] (view) vault.read(secret/data/database) starting fetch
2022/01/06 17:13:02.022466 [DEBUG] (runner) receiving dependency vault.read(secret/data/database)
2022/01/06 17:13:02.022466 [DEBUG] (runner) initiating run
2022/01/06 17:13:02.022466 [DEBUG] (runner) checking template 95241dff60a389dcef5706cada2a4bb3
2022/01/06 17:13:02.022466 [DEBUG] (runner) rendering "(dynamic)" => "C:\\Users\\imusayev\\AppData\\Local\\Temp\\NomadClient904772154\\bc1a43e4-a839-9a88-c3e7-01595c20fbc7\\main\\Deployment\\bin\\appsettings.json"
2022/01/06 17:13:02.024996 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\imusayev\\AppData\\Local\\Temp\\NomadClient904772154\\bc1a43e4-a839-9a88-c3e7-01595c20fbc7\\main\\Deployment\\bin\\appsettings.json"
2022/01/06 17:13:02.024996 [DEBUG] (runner) checking template ea994093f0fd31dd782194ca4c67e778
2022/01/06 17:13:02.024996 [DEBUG] (runner) rendering "(dynamic)" => "C:\\Users\\imusayev\\AppData\\Local\\Temp\\NomadClient904772154\\bc1a43e4-a839-9a88-c3e7-01595c20fbc7\\main\\Deployment\\bin\\nlog.config"
2022/01/06 17:13:02.024996 [DEBUG] (runner) checking template 62bc1580343864cbe48934a7c730b363
2022/01/06 17:13:02.024996 [DEBUG] (runner) rendering "(dynamic)" => "C:\\Users\\imusayev\\AppData\\Local\\Temp\\NomadClient904772154\\bc1a43e4-a839-9a88-c3e7-01595c20fbc7\\main\\secrets\\file.env"
2022/01/06 17:13:02.024996 [DEBUG] (runner) diffing and updating dependencies
2022/01/06 17:13:02.024996 [DEBUG] (runner) kv.block(configs/ServiceName/appsettings.json) is still needed
2022/01/06 17:13:02.024996 [DEBUG] (runner) kv.block(configs/ServiceName/nlog.config) is still needed
2022/01/06 17:13:02.024996 [DEBUG] (runner) vault.read(secret/data/database) is still needed
2022/01/06 17:13:02.024996 [DEBUG] (runner) watching 3 dependencies
2022/01/06 17:13:02.024996 [DEBUG] (runner) all templates rendered
```

**Comment by DerekStrickland** [comment]
Hi @paladium 

Looking at the log message let me to these 2 [Vault configuration options](https://www.vaultproject.io/docs/agent/template#non-renewable-secrets). The second specifically calls out DB connection strings. I noticed your config has `{{.Data.data.connection_string}}`.  Also, it appears you are using .NET. 

I am wondering if using this [learn article](https://learn.hashicorp.com/tutorials/vault/dotnet-vault-agent#configure-vault-agent-to-create-application-settings-files) as a guide, and then updating your Vault template stanza with a different render interval for`static_secret_render_interval` would result in different behavior.  If so, then I think we've found the right option to allow you to configure this the way you'd like. If not, let us know, and we can look into it more.

**Comment by paladium** [comment]
Hello, thank you for prompt response. I have used the setting you have mentioned which increases how often the secret is fetched from Vault. I am okay with the value of 5 minutes, since when used on its own without additional consul templates, it silently processes the file and since there are no changes, the job is not restarted. The same situation is observed when I utilise consul key/values on its own without vault secrets. However, when combining both, what ends up happening is vault 5 minute timer renders new secrets and forces consul kv templates to restart the job. I have verified it by setting change_mode to noop for consul key values (appsettings.json and nlog.config) and nomad was rendering files correctly without restarting the job (which should happen since there were no changes in the system). What I would like to know, is the issue of combining both Vault secrets and consul key values something that can be avoided, or is it an expected behaviour?

**Comment by paladium** [comment]
From the code I was able to determine that when the vault timer fires, it actually rerenders all the templates in the job:
https://github.com/hashicorp/consul-template/blob/4ff55381f1c40c8536ce6018cddc6491152c8e91/manager/runner.go#L534
And the piece of code that initiates running for the all the templates, also mentions that it could be triggered by the timer:
https://github.com/hashicorp/consul-template/blob/4ff55381f1c40c8536ce6018cddc6491152c8e91/manager/runner.go#L386
So I suppose that is expected behavior. It can then explain why I did not notice it with only using consul kv or only vault secrets, since they both work perfectly on their own - consul kv checking if new data arrived and vault secrets timer silently checking the file diff and not actually sending the restart signal when there are no changes. I suppose it is not as straightforward to circumvent as I initially thought.

**Comment by paladium** [comment]
Actually, by looking more into the code I found the issue - consul template checks whether the file contents is different from the one received from consul and in our case we were encrypting and removing appsettings.json, which causes nomad to recreate that file and restart the application. After the application started that cycle repeats since the file is already removed and encrypted.

**Comment by DerekStrickland** [comment]
Ahh.  Glad you found it, and thank you for documenting it for the community.
