### ISSUE TITLE
Show node names instead of node ids in nomad status

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#1180]
It will be cool if in nomad status <app> command show node names, now it show node is and it's not very convenient

**Comment by a86c6f7964** [comment]
I wonder if something like --format api (https://docs.docker.com/engine/reference/commandline/ps/#formatting) that docker has would be a good way to accomplish this. So that it would be possible to change how some of the CLI command output information

**Comment by ketzacoatl** [comment]
This generally doesn't matter when things are working ok, but when stuff breaks.. I find myself frequently needing to grab IDs to translate to a node name to do some remote exec in consul - I would love a flag or option to specify node name in the status displays (I'd support that as a default, but maybe others don't like that).

**Comment by salkin** [comment]
This would be great to have, now I often find myself executing two commands to find the real host for a task that is failing or misbehaving.

**Comment by arshjohar** [comment]
We merged a PR that should display Node Name for job status and alloc status commands. Closing this one.
