### ISSUE TITLE
logging with Graylog

### ISSUE THREAD

**Issue by mehdiMj-ir** [hashicorp/nomad#11814]
Hi, Hope 2022 be a good year
### Proposal
---
A Graylog driver for Nomad to ship and sent containers logs to Graylog.

### Use-cases
This will help me to monitor and visualize logs for users without giving Nomad UI access to Developers. (I will keep Nomad to myself😈)  
![gray](https://user-images.githubusercontent.com/20270329/148934481-182fad20-6ab7-40ce-b288-94853866acb8.png)

### Attempted Solutions
I currently install `rsyslog` on my docker containers and then **syslog** push logs to my Graylog server.
But a nice Driver and more logging option would be a great help.

**Comment by tgross** [comment]
Hi @mehdiMj-ir! This falls into the same sort of bucket as https://github.com/hashicorp/nomad/issues/10220 and https://github.com/hashicorp/nomad/issues/9211 to extend Nomad to support some kind of logging plugin (cc @mikenomitch just a heads up that this has come up a few times now). I'm going to keep this issue open for further discussion and roadmapping.

But in the meantime, you mentioned you're using the `docker` task driver. You can use the [`task.config.logging`](https://www.nomadproject.io/docs/drivers/docker#logging) block for those tasks to set any of the configuration options supported by your version of Docker. Taking a quick look at the Docker logging docs it looks like Docker supports [`gelf`](https://docs.docker.com/config/containers/logging/gelf/) natively. So your jobspec would look like this:

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
        ports  = ["db"]

        logging {
          type = "gelf"
          config {
            gelf-address = "udp://localhost:12201"
          }
        }
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by mehdiMj-ir** [comment]
### THANK YOU, VERY VERY MUCH.
I was about to setup `fluentd` as mentioned on [Nomad Docs](https://www.nomadproject.io/docs/drivers/docker#logging) but this make my job so much easier. I even searched and found #688 but those `[option](https://github.com/hashicorp/nomad/issues/688#issuecomment-172666252)` didn't work for me.

**Comment by mikenomitch** [comment]
Hey @mehdiMj-ir thanks for the issue. I am going to close this one out in favor of the more generic https://github.com/hashicorp/nomad/issues/10220 and https://github.com/hashicorp/nomad/issues/9211 - the link to this issue will stick around though so whenever we pick those us we'll be able to include this request for context.

**Comment by Allan-Nava** [comment]
How to send the entire log message from nomad job to graylog?
