### ISSUE TITLE
implicit spread target results in incorrect scoring

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#11823]
### Nomad version
v1.2.3

### Issue
A fairly minor issue but according to the [spread documentation](https://www.nomadproject.io/docs/job-specification/spread#spread-with-target-percentages) providing a percent of 50 for a single DC should lead to half of the allocs being scheduled in that DC. This isn't the case until you specify all of the targets. With a 3 DC dev setup and the following job:
```hcl
job "example" {
  datacenters = ["dc1", "dc2", "dc3"]

  update {
    max_parallel     = 30
    min_healthy_time = "5s"
  }

  spread {
    attribute = node.datacenter

    target "dc1" {
      percent = 50
    }
  }

  group "example" {
    count = 12
    task "example" {
      driver = "docker"
      config {
        image = "alpine"
        args  = [ "tail", "-f", "/dev/null" ]
      }

      resources {
        cpu    = 100
        memory = 64
      }
    }
  }
}
```
The result would be 4 allocations per node, an even spread. According to the docs this should have lead to 6 allocs being placed in dc1 and the remainder in the others:
```sh
$ nomad status example | grep -A100 Allocations | tail -n+3 | sort -k2
736eb996  4c862aa8  example     0        run      running  10s ago  4s ago
c6d637f3  4c862aa8  example     0        run      running  10s ago  4s ago
f5b55722  4c862aa8  example     0        run      running  10s ago  4s ago
47ed2c33  4c862aa8  example     0        run      running  10s ago  5s ago
239c67d4  732bbfb8  example     0        run      running  10s ago  5s ago
b0f6f499  732bbfb8  example     0        run      running  10s ago  5s ago
c915fa61  732bbfb8  example     0        run      running  10s ago  5s ago
cb0f60db  732bbfb8  example     0        run      running  10s ago  5s ago
038f6167  8fb0da83  example     0        run      running  10s ago  1s ago
0c6c2d0a  8fb0da83  example     0        run      running  10s ago  1s ago
87ecb255  8fb0da83  example     0        run      running  10s ago  1s ago
9ad5b804  8fb0da83  example     0        run      running  10s ago  1s ago
```
When I specify the `target` for each dc as follows:
```hcl
job "example" {
  datacenters = ["dc1", "dc2", "dc3"]

  update {
    max_parallel     = 30
    min_healthy_time = "5s"
  }

  spread {
    attribute = node.datacenter

    target "dc1" {
      percent = 50
    }
    target "dc2" {
      percent = 25
    }
    target "dc3" {
      percent = 25
    }
  }

  group "example" {
    count = 12
    task "example" {
      driver = "docker"
      config {
        image = "alpine"
        args  = [ "tail", "-f", "/dev/null" ]
      }

      resources {
        cpu    = 100
        memory = 64
      }
    }
  }
}
```
it works as expected with 6 allocs being placed in dc1, 3 in dc2 and 3 in dc3:
```sh
$ nomad status example | grep -A100 Allocations | tail -n+3 | sort -k2
b40c912e  4c862aa8  example     0        run      running  13s ago  4s ago
c0b56b80  4c862aa8  example     0        run      running  13s ago  4s ago
ce231a0a  4c862aa8  example     0        run      running  13s ago  4s ago
780c2f72  732bbfb8  example     0        run      running  13s ago  4s ago
9f387cea  732bbfb8  example     0        run      running  13s ago  4s ago
d76324f6  732bbfb8  example     0        run      running  13s ago  4s ago
1197ce17  8fb0da83  example     0        run      running  13s ago  5s ago
414805a8  8fb0da83  example     0        run      running  13s ago  5s ago
68c80ee3  8fb0da83  example     0        run      running  13s ago  5s ago
a71df87f  8fb0da83  example     0        run      running  13s ago  5s ago
b3ece220  8fb0da83  example     0        run      running  13s ago  5s ago
ea9ca194  8fb0da83  example     0        run      running  13s ago  5s ago
```

**Comment by mikenomitch** [comment]
I dug into this a bit and am confirmed with @tgross and we have a better idea of the source of the issue.

When we calculate the score for each node, we take the [desiredCount minus the usedCount](https://github.com/hashicorp/nomad/blob/8dff1f758a145db3c12441d9affe0372a6c94e6d/scheduler/spread.go#L181). UsedCount is [calculated separately for every potential value of the target attribute](https://github.com/hashicorp/nomad/blob/8dff1f758a145db3c12441d9affe0372a6c94e6d/scheduler/propertyset.go#LL234C5-L234C5).

The fact that usedCount referenced each specific value means that the implicitTarget count is incorrect (unless there is only one implicit value).

If I've specified only "dc1" to get 50% and "the rest" implicitly get 50%. If I place something on "dc2" then the "usedCount" for "the rest" should bump up to one. Instead what happens is that the usedCount for "dc2" gets bumped, but "dc3" stays at 0. This will over-weight any implicit values during scoring.

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/17195 and backported to the 1.5.x, 1.4.x, and 1.3.x release branches. This will get released in the near future.
