### ISSUE TITLE
Nomad volume deregister prevents deregistration when a volume id is a prefix of another

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/nomad#11846]
### Nomad version
```
# nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)
```

### Issue
When a registered volume whose full ID is a prefix of another volumes ID, the `deregister` command will not deregister the volume and will print a message about multiple prefix matches. This creates a situation where you must first deregister any volumes who's ID is prefixed with the ID of the volume you are trying to deregister.

### Reproduction steps
1) Create 2 volumes with the ID's `test_volume` and `test_volume_1`

```
# cat <<EOF | nomad volume create - 
id        = "test_volume"
name      = "test_volume"
type      = "csi"
plugin_id = "cinder-csi-hashistack"
capacity_min = "1G"
capacity_max = "1G"

capability {
  access_mode = "single-node-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type     = "ext4"
  mount_flags = ["rw", "noatime"]
}
EOF
```
```
# cat <<EOF | nomad volume create - 
id        = "test_volume_1"
name      = "test_volume_1"
type      = "csi"
plugin_id = "cinder-csi-hashistack"
capacity_min = "1G"
capacity_max = "1G"

capability {
  access_mode = "single-node-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type     = "ext4"
  mount_flags = ["rw", "noatime"]
}
EOF
```
2) Run `nomad volume deregister test_volume` and note that the command returns the message `Prefix matched multiple volumes` instead of the success message for deregistering a volume.

```
# nomad volume deregister test_volume 
Prefix matched multiple volumes

ID        Name           Plugin ID              Schedulable  Access Mode
test_vol  test_volume    cinder-csi-hashistack  true         <none>
test_vol  test_volume_1  cinder-csi-hashistack  true         <none>
```
#### Expected Result
Providing a full ID to the deregister command should result in the volume being deregistered

#### Actual Result
The volume is not deregistered and you must first deregister all volumes who's ID is prefixed with the volume ID you are trying to remove.

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A
### Nomad Client logs (if appropriate)
N/A

**Comment by tgross** [comment]
Hi @RickyGrassmuck! I took a quick look and this looks like a bug in the state store (ref [`state_store.go#L2373-L2378`](https://github.com/hashicorp/nomad/blob/v1.2.3/nomad/state/state_store.go#L2373-L2378)), where we're using the ID prefix instead of the ID. Not sure how that happened but should be straightforward to fix. Thanks for opening this issue!

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/11852
