### ISSUE TITLE
Nomad volume deregister command does not output actual volume ID's when a prefix match is found

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/nomad#11847]
### Nomad version
```
# nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)
```

### Issue
When the `volume deregister` command finds multiple volumes with the same prefix, the ID column printed does not contain the actual Volume ID's for the matches it found.

### Reproduction steps
1) Create 2 volumes with the ID's `test_volume` and `test_volume_1`

```
# cat <<EOF | nomad volume create - 
id        = "test_volume"
name      = "test_volume"
type      = "csi"
plugin_id = "cinder-csi-hashistack"
capacity_min = "1G"
capacity_max = "1G"

capability {
  access_mode = "single-node-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type     = "ext4"
  mount_flags = ["rw", "noatime"]
}
EOF
```
```
# cat <<EOF | nomad volume create - 
id        = "test_volume_1"
name      = "test_volume_1"
type      = "csi"
plugin_id = "cinder-csi-hashistack"
capacity_min = "1G"
capacity_max = "1G"

capability {
  access_mode = "single-node-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type     = "ext4"
  mount_flags = ["rw", "noatime"]
}
EOF
```

2) Run `nomad volume deregister test_volume` and note that the Volume ID's for all the returned prefix matches contain the same value(In this test, they all contain the ID `test_vol`.

```
# nomad volume deregister test_volu
Prefix matched multiple volumes

ID        Name           Plugin ID              Schedulable  Access Mode
test_vol  test_volume    cinder-csi-hashistack  true         <none>
test_vol  test_volume_1  cinder-csi-hashistack  true         <none>
```
#### Expected Result
The ID column should output the actual volume ID's

#### Actual Result
The output contains what appears to be a common prefix value for all returned volume id's

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A
### Nomad Client logs (if appropriate)
N/A

**Comment by tgross** [comment]
Hi @RickyGrassmuck! It looks like the formatter at [`volume_status_csi.go#L170`](https://github.com/hashicorp/nomad/blob/v1.2.3/command/volume_status_csi.go#L170) is just truncating the IDs to 8 characters (well, unicode "runes"). We do that for a lot of objects in the list views because they're UUIDs, but obviously that's inappropriate here.

Thanks for opening this issue!

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/11853
