### ISSUE TITLE
Build fails on armv7 FreeBSD with type error.

### ISSUE THREAD

**Issue by clausecker** [hashicorp/nomad#11850]
### Nomad version
1.2.2 with FreeBSD port revision 1 as built from FreeBSD ports.

### Operating system and Environment details
FreeBSD ports.

### Issue
The build fails on armv7 FreeBSD 13 with a type error:

    # github.com/hashicorp/nomad/command/agent
    command/agent/log_file_bsd.go:16:45: cannot use createTime.Nsec (type int32) as type int64 in argument to time.Unix

### Reproduction steps

On an armv7 FreeBSD 13 system, try to build `sysutils/nomad` from the ports collection (or by any other means).

### Fix

I believe the issue is caused by the fields of `syscall.Stat_t.Ctimespec` having different types on different architectures.  To fix this issue, a conversion should suffice.  In file `command/agent/log_file_bsd.go` replace

    return time.Unix(createTime.Sec, createTime.Nsec)

with

    return time.Unix(int64(createTime.Sec), int64(createTime.Nsec))

**Comment by tgross** [comment]
Hi @clausecker! Interestingly, it looks like this is exactly what we did on Linux: [`log_file_linux.go#L15-L16`](https://github.com/hashicorp/nomad/blob/v1.2.3/command/agent/log_file_linux.go#L15-L16). Seems like a straightforward patch. We don't have a ARM7 FreeBSD builder in our CI on PRs... any chance you've verified this patch builds yourself?

**Comment by tgross** [comment]
I've opened https://github.com/hashicorp/nomad/pull/11854 with the patch.

**Comment by clausecker** [comment]
It is difficult for me to test this directly since some dependencies fail:

```
fuz@mochi:/home/fuz/src/nomad$ go build -o nomad.elf                                                      
# github.com/hashicorp/nomad/command/agent/host                                                           
command/agent/host/host.go:25:23: undefined: mountedPaths                         
command/agent/host/unix.go:68:20: invalid operation: d.s.Bavail * uint64(d.s.Bsize) (mismatched types int64 and uint64)                                                                                             
# github.com/docker/docker/pkg/system                                                                     
../../go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200330121334-7f8b4b621b5d+incompatible/pkg/system/mknod.go:12:19: cannot use dev (type int) as type uint64 in argument to unix.Mknod
```

But when I build the patched version from FreeBSD ports with the aforementioned patch applied, it builds just fine.  Currently running the test suite which may take a while.

**Comment by clausecker** [comment]
Okay, my RPi2 did not survive running the testsuite.  But given that it compiles, I suspect this patch does the trick.

**Comment by tgross** [comment]
Ok, cool. This patch will ship in 1.2.4 and be backported two major versions. Thanks again @clausecker!
