### ISSUE TITLE
things that nomad reports to /var/log/messages should be surfaced better

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#11869]
Today, I wrote a bug in *my* codez that attempted to launch a docker image that didn't exist.

This was difficult to track down because nomad didn't surface a relevant error message.  On pushing the new job with this bug and executing `nomad job run ...` the allocations never became healthy.  The command kept attempting to roll new instances, but they all continued to go unhealthy.  

There was no obvious output in the CLI.
Via the web UI, all the allocation logs were 0 bytes.
My application-level log pipeline had nothing in it (but this makes sense because the container didn't exist/launch)

After a good long while, I finally ssh'd into a client box and tailed `/var/log/messages` and found:

```
Jan 17 22:32:08 ip-10-1-21-219 nomad: 2022-01-17T22:32:08.593Z [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=c049c1e5-1493-cf29-cf3e-307b84ce1fe7 task=numbers_puma error="Failed to pull `1234.dkr.ecr.us-west-2.amazonaws.com/ninj[57/5435]
tm:`: API error (404): manifest for 1234.dkr.ecr.us-west-2.amazonaws.com/ninja-amzn2-app:latest not found: manifest unknown: Requested image not found"
```

emphasis **_Requested image not found_**

This log was written by nomad but is seemingly not accessible or obvious from the cli or UI.  It immediately led me to my bug.

**Comment by lgfa29** [comment]
Hi @josh-m-sharpe 👋 

These types of error are often surfaced as allocation events. They can be viewed in the Nomad UI or via the CLI:

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/775380/150231983-d9c454de-1baf-43cf-8223-5f1da0039e7a.png">


```
$ nomad alloc status 0b
ID                  = 0b6dd3d5-3cbf-c699-5ecb-bc4c936c9b31
Eval ID             = 95ad477b
Name                = example.cache[0]
Node ID             = 3a4cc2ee
Node Name           = laoqui-C02YR4X7LVCG
Job ID              = example
Job Version         = 0
Client Status       = pending
Client Description  = No tasks have started
Desired Status      = run
Desired Description = <none>
Created             = 7s ago
Modified            = 6s ago
Deployment ID       = 238e8171
Deployment Health   = unset

Allocation Addresses
Label  Dynamic  Address
*db    yes      127.0.0.1:31214 -> 6379

Task "redis" is "pending"
Task Resources
CPU      Memory   Disk     Addresses
500 MHz  256 MiB  300 MiB

Task Events:
Started At     = N/A
Finished At    = N/A
Total Restarts = 1
Last Restart   = 2022-01-19T17:58:26-05:00

Recent Events:
Time                       Type            Description
2022-01-19T17:58:26-05:00  Restarting      Task restarting in 15.44329949s
2022-01-19T17:58:26-05:00  Driver Failure  Failed to pull `doestexist:4.0`: API error (404): pull access denied for doestexist, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
2022-01-19T17:58:25-05:00  Driver          Downloading image
2022-01-19T17:58:25-05:00  Task Setup      Building Task Directory
2022-01-19T17:58:25-05:00  Received        Task received by client
```

Is this what you are looking for?

**Comment by josh-m-sharpe** [comment]
hi @lgfa29 - thanks for the response.

I recreated the situation.  I didn't know about `nomad alloc status` and this error does appears there.

However it does not show up in the UI.  I do not see a "Recent Events" section (like in your screenshot) at this path: `/ui/allocations/a55ec241-421b-f4af-d1a7-07aa258f1e2a` 

I'm currently running 1.2.3 which I guess is a patch version out of date - lmk If it's the version and I can update and retry.  Thank you!

**Comment by lgfa29** [comment]
This page has been there for a while. From that path you mentioned you will need to go one level deeper, to the task detail, by clicking on the task row in the table:
![image](https://user-images.githubusercontent.com/775380/152441953-ebc9dcc7-d0a9-45b9-9d80-da6bb1369e3c.png)

Then you will see the task events:
![image](https://user-images.githubusercontent.com/775380/152442094-66959252-b691-4c5b-9ed1-f74b5a8938ce.png)

**Comment by tgross** [comment]
Hi folks, looks like this was answered so I'm going to close this one out.
