### ISSUE TITLE
ability to disable swap for exec

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/nomad#1186]
I noticed that the MemorySwap is set to -1 for docker. I usually do not like things to swap, since it causes unnecessary CPU and disk writes. I would rather my service crash if it runs out of memory. Usually I just set the memory and memory swap to the same number. This may be moot, because on CoreOS the swap is disabled so -1 still means that swap is disabled, but I feel like it would be nice to limit it.

**Comment by diptanu** [comment]
We should do this for docker and other exec based drivers.

**Comment by a86c6f7964** [comment]
Any milestone for this?

**Comment by dadgar** [comment]
@a86c6f7964 Hey it is actually implemented for docker. I am going to rename to capture the fact for exec.

**Comment by dadgar** [comment]
Hey swap is disabled on exec on newer versions of Nomad.
