### ISSUE TITLE
docker driver uses real bridge network address in port mapping instead of one specified in bridge.host_binding_ipv4

### ISSUE THREAD

**Issue by narqo** [hashicorp/nomad#1187]
It seems that nomad's docker driver always use real IPv4 address of docker's bridge for port mapping (see [code for docker driver](https://github.com/hashicorp/nomad/blob/6b0757c6c4e5bf1b2e038bfd1494d335cab0b838/client/driver/docker.go#L442-L443)). In my case this leads to undesirable behaviour, as containers are not accessible from the outer world as my server is IPv6-only.

As far as I can see, by default docker binds exposed port to an IP specified in `com.docker.network.bridge.host_binding_ipv4` network address, which is `0.0.0.0` for default bridge (see docker container network docs, https://docs.docker.com/engine/userguide/networking/dockernetworks/).

It'd nice if nomad support `host_binding_ipv4` option as well.

/cc @bogdanov1609
### Nomad version

› nomad version
Nomad v0.3.2
### Operating system and Environment details

Linux, Ubuntu 14.04
### Job file (if appropriate)

```
job "deploy-service" {
  task "service" {
    driver = "docker"
      config {
        network_mode = "bridge"
        image = "my-service"
        port_map {
          api = 14150
        }
      }
      ···
```

**Comment by aluminous** [comment]
Any news on this?

Since this isn't (currently) configurable via nomad, would a reasonable default be to simply respect docker's configuration?

In our case, this also prevents access to any containers started by nomad.

**Comment by dadgar** [comment]
Hey, hopefully will have a chance to look into this soon!

**Comment by schmichael** [comment]
@nickethier can you take a look at this before our next release?

**Comment by nickethier** [comment]
With [multi-interface host networking](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12) I think goal of whats being asked here is now possible. To pick the IP to port map to. Please feel free to open a new issue with updated information if not. Thankyou!
