### ISSUE TITLE
Set CSI_ENDPOINT environment variable

### ISSUE THREAD

**Issue by NomAnor** [hashicorp/nomad#11874]
I'm trying to implement a CSI plugin. I'm using `nomad agent -dev`. For easier development I'm also using the `raw_exec` driver.
It is a bit cumbersome to set the correct socket path. `csi_plugin.mount_dir` seems to only apply to containers not the `raw_exec` driver. I had to look up the path in the debug output, `$DATA_DIR/client/csi/monolith/<plugin_name>/csi.sock`.

The CSI specification states

> The `CSI_ENDPOINT` environment variable SHALL be supplied to the Plugin by the Plugin Supervisor.

For better compatibility with the specification, can nomad set the environment variable? This should make the endpoint specification independent of the task driver (even automatic if plugins use the variable). In a container it would be set to `mount_dir`, for `raw_exec` to the absolute path in the host filesystem.

**Comment by tgross** [comment]
Hi @NomAnor! Yup, that's a miss on our part. Will fix.
