### ISSUE TITLE
Enhance docker task driver, buildFingerprint, to canary a container deployment as a component of the reported healthy state

### ISSUE THREAD

**Issue by hwshadow** [hashicorp/nomad#11888]
https://github.com/hashicorp/nomad/blob/f2a37a0a03045d922b933373e71385b3c615ac63/drivers/docker/fingerprint.go#L86
drivers/docker/fingerprint buildFingerprint() seems to open a connection to the docker daemon and consider the driver healthy if it is able to do so.

Ran into an obscure condition, kernel bug preventing Nomad from successfully deploying a container on an afflicted client node. 
- https://bugzilla.redhat.com/show_bug.cgi?id=1507149 
- https://github.com/opencontainers/runc/issues/2039#issuecomment-740323043
- https://github.com/opencontainers/runc/pull/1921 

During this time, Nomad continued to report the client node as healthy though it was effectively out of commission.  This bug is easy to fix with a kernel upgrade, but was thinking it would be more complete if the drivers could detect like issues and mark the driver as down accordingly?

I could certainly contribute to a PR specifically for detection as it pertains to the docker driver.  
Was wondering if there might be a higher-level solution before I embark down that path?

**Comment by lgfa29** [comment]
Hi @hwshadow 👋 

This is a tricky one 🤔 

Do you know if there's any endpoint in the Docker daemon that would tell if this problem exists? We could maybe check [`/info`](https://docs.docker.com/engine/api/v1.41/#operation/SystemInfo) but I'm not sure this information would be there.

Do you have a way (like a Vagrantfile) to reproduce this problem?

**Comment by hwshadow** [comment]
> Hi @hwshadow 👋
> 
> This is a tricky one 🤔
> 
> Do you know if there's any endpoint in the Docker daemon that would tell if this problem exists? We could maybe check [`/info`](https://docs.docker.com/engine/api/v1.41/#operation/SystemInfo) but I'm not sure this information would be there.
> 
> Do you have a way (like a Vagrantfile) to reproduce this problem?

I can work on a portable reproduction.  
I was not aware of any indication in the /info endpoint, but I will reproduce and attach any relevant output.

Might take me a week or two, but rest assured I will be back :)

**Comment by lgfa29** [comment]
Thank you for the update. I will go ahead and close this for now, but feel free to report back when the problem happens again!
