### ISSUE TITLE
Show pack label on the main jobs view

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad#11886]
### Proposal
It would be great to differentiate between "normal" jobs and jobs created by nomad-pack. Jobs created by nomad-pack already display a little logo when drilling down into the specific jobs, it would be great if this information is available on the main jobs view already.

### Use-cases
Distinguish between "normal" jobs and jobs created by nomad-pack from the main jobs view instead of drilling down into specific jobs

### Attempted Solutions
N/A

**Comment by lgfa29** [comment]
Thanks @attachmentgenie! This is something we've talked about having 🙂

**Comment by angrycub** [comment]
@philrenaud per your request, tagging you in. :D

**Comment by philrenaud** [comment]
Hi @attachmentgenie — work to add the Pack tag on the jobs list page has been completed, and should be included in an upcoming release. Thank you for your patience and for raising this issue!

**Comment by attachmentgenie** [comment]
@philrenaud thanks! cant wait to use this
