### ISSUE TITLE
Wrong link target in UI

### ISSUE THREAD

**Issue by NomAnor** [hashicorp/nomad#11884]
### Nomad version
Nomad v1.2.3

### Issue
The link to the volume on the task site (`ui/allocations/<alloc id>/<task name>`) shows the `volume_mount.volume` name from the task but is also linked to `ui/csi/volumes/<volume_mount.volume>`. 

If the volume id form the volume creation/registration file is not the same, the link gives an error.

The label of the link is correct (the task volume name) but the link target must always use the volume id.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/11896.
