### ISSUE TITLE
Wrong path in staging_target_path and target_path for CSI plugin

### ISSUE THREAD

**Issue by NomAnor** [hashicorp/nomad#11885]
### Nomad version
Nomad v1.2.3

### Issue
I'm trying to implement a CSI plugin. I'm using `nomad agent -dev`. For easier development I'm also using the `raw_exec` driver.

The `staging_target_path` and `target_path` are not correct in the RPC calls if the CSI plugin is run with the `raw_exec` task driver.

According to the CSI spec:
> It MUST be an absolute path in the root filesystem of the process serving this request.

The path seems to take into account the `mount_dir` option which is only correct for containers. For a driver without file system isolation the path should be an absolute path in the node host file system. In my tests it is for example `$DATA_DIR/client/csi/monolith/<plugin_name>/staging/<volume id>/rw-file-system-single-node-writer`

The documentation states that `mount_dir` is required but not setting it does not give me an error when i run my plugin job. It seems to default to `/csi`. Setting it to something else replaces the `/csi` part with its value in the log output below.

### Logs of my CSI plugin
```
DEBUG:lvm_csi.node:Handling NodeStageVolume
volume_id: "Idoxnl-8Sxs-2pkb-3au7-rN1x-p8dP-0tA27L"
staging_target_path: "/csi/staging/registry-data/rw-file-system-single-node-writer"
volume_capability {
  mount {
    fs_type: "ext4"
    mount_flags: "noatime"
  }
  access_mode {
    mode: SINGLE_NODE_WRITER
  }
}

DEBUG:lvm_csi.node:Handling NodePublishVolume
volume_id: "Idoxnl-8Sxs-2pkb-3au7-rN1x-p8dP-0tA27L"
staging_target_path: "/csi/staging/registry-data/rw-file-system-single-node-writer"
target_path: "/csi/per-alloc/7ee42f48-fe86-0ec2-b798-2a752b9bf3e4/registry-data/rw-file-system-single-node-writer"
volume_capability {
  mount {
    fs_type: "ext4"
    mount_flags: "noatime"
  }
  access_mode {
    mode: SINGLE_NODE_WRITER
  }
}
```

**Comment by tgross** [comment]
> The documentation states that `mount_dir` is required but not setting it does not give me an error when i run my plugin job. It seems to default to `/csi`. Setting it to something else replaces the `/csi` part with its value in the log output below.

Hi @NomAnor! This definitely looks like it's out of spec, so marking as accepted for fixing. 

That being said between this issue and https://github.com/hashicorp/nomad/issues/11874 I want to level-set that you're not currently on the "happy path" trying to deploy a plugin as a `raw_exec` job. Most plugins get shipped as OCI-compliant container images (I think that's even a requirement for k8s?), so it's not a path we've really tested at all. Which isn't to say you shouldn't open issues about it! Or even PRs if you're up for it! I'd love to hear about where we're breaking that use case. But as you've probably noticed there's a few other CSI bugs that are burning and my focus at the moment is on fixing those. But we'll get to this!

**Comment by NomAnor** [comment]
I understand. I know that the `raw_exec` driver is propably not tested enough. It was the easiest way to get my plugin running. If I have a working version I will definetly build a container.
