### ISSUE TITLE
Missing Event types on Allocation documentation

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/nomad#1190]
The [allocation page](https://www.nomadproject.io/docs/http/alloc.html) refers to:
> Driver Failure - The task could not be started due to a failure in the driver.
> Started - The task was started; either for the first time or due to a restart.
> Terminated - The task terminated.
> Killed - The task was killed by the user.
> 

It seems the allocation documentation is missing few of all possible [Event types](https://github.com/hashicorp/nomad/blob/29be52f7629f7db087eed10ef5326dc03c4581eb/api/tasks.go):

```
const (
	TaskDriverFailure          = "Driver Failure"
	TaskReceived               = "Received"
	TaskFailedValidation       = "Failed Validation"
	TaskStarted                = "Started"
	TaskTerminated             = "Terminated"
	TaskKilled                 = "Killed"
	TaskRestarting             = "Restarting"
	TaskNotRestarting          = "Not Restarting"
	TaskDownloadingArtifacts   = "Downloading Artifacts"
	TaskArtifactDownloadFailed = "Failed Artifact Download"
)
```

**Comment by dadgar** [comment]
@hgontijo Would love a PR for this 👍
