### ISSUE TITLE
can support registry-mirrors? when use docker

### ISSUE THREAD

**Issue by lialzm** [hashicorp/nomad#11925]
Where I am connecting to docker hub is slow, can nomad support setting registry-mirrors

**Comment by Amier3** [comment]
Hey @lialzm 

Thanks for proposing this, we will definitely look into this. We've experienced similar issues connecting straight to docker hub internally so we understand the frustration 😅

**Comment by apollo13** [comment]
I have put registry mirrors in docker's daemon.json and the seem to get used just fine (I'd have to double check, but I don't see a reason why they should not get used). I am not sure if it makes sense for nomad to duplicate that configuration?

**Comment by lgfa29** [comment]
Hi @lialzm 👋 

@apollo13 is right, Nomad will use the Docker daemon to pull images, so you can customize it to fit your needs. Here's how to set a registry mirror: 
https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon

Give it a try and let us know how it goes 🙂

**Comment by suikast42** [comment]
> Hi @lialzm 👋
> 
> @apollo13 is right, Nomad will use the Docker daemon to pull images, so you can customize it to fit your needs. Here's how to set a registry mirror: https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon
> 
> Give it a try and let us know how it goes 🙂

Can we reopen this issue ? 

The docker daemon can only mirror image pulls releated to docker.io. It's not like containerd so that I can mirror every pull request. 

![image](https://user-images.githubusercontent.com/5046525/192145152-52c045b3-7238-4bcc-b15c-a953b7baa4fc.png)

That is not so feasible in a airgapped ennvironment, isn't it?
