### ISSUE TITLE
Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages

### ISSUE THREAD

**Issue by bert2002** [hashicorp/nomad#11924]
Hi,
didnt know where to place it, but the apt repository is broken

```
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

Many thanks,
bert

**Comment by jrasell** [comment]
Hi @bert2002 and thanks for opening this issue. I have raised this internally and will provide updates here when they are available.

**Comment by jrasell** [comment]
Hi @bert2002, this issue has now been resolved and I have confirmed this via local testing. If you could confirm it is also fixed for you, that would be great.

**Comment by HS-157** [comment]
Hi, I confirm that it's fixe. Thanks for your work !

**Comment by pznamensky** [comment]
Hi @jrasell, sorry for pinging you here.
But the same error for ubuntu 16.04:
```
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_xenial_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```
Should I open a new issue?

**Comment by jrasell** [comment]
Hi @pznamensky yeah if you wouldn't mind, that would be great. I will then pin the issue and raise it internally to get fixed. Thanks!
