### ISSUE TITLE
make the click of `ui.consul.ui_url` open in a new browser TAB

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#11952]
### Proposal
The `ui` stanza was expanded in Nomad 1.2.4 to provide `ui.consul.ui_url` and similar for Vault.
It would be good that the click opens the link in a new browser tab by default rather than in the same window.

### Use-cases
Losing the currently open Nomad UI page makes it a bit annoying :)

### Attempted Solutions
Right-click and "open in new tab" works, but it would nice to have that as the default behavior.

**Comment by jrasell** [comment]
Hi @shantanugadgil, this seems like a reasonable request. I'll label this issue so that the frontend engineering and product design teams can take a look and discuss it further.

**Comment by mikenomitch** [comment]
@juliezzhou and I both think this is a good iddue. I'm going to add this to the unified backlog in To Do and mark as accepted.

I also might just throw a PR up there since it should ideally just be adding a field to those links.
