### ISSUE TITLE
UDP check for service stanza

### ISSUE THREAD

**Issue by gfonseca-tc** [hashicorp/nomad#11953]
### Proposal
A UDP check type for services. 

### Use-cases
Many services listen to UDP and having a way of checking them would be very helpful. 

### Attempted Solutions
As a workaround I'm trying to run in another task a nmap container to check if the port is open and will create an alias to this service check. Still working on that, since Nomad doesn't support this kind of check yet.

**Comment by jrasell** [comment]
Hi @gfonseca-tc and thanks for raising this issue.

Nomad leverages [Consul health checks](https://www.consul.io/docs/discovery/checks#checks) for health checking services as configured within the [service check job spec block](https://www.nomadproject.io/docs/job-specification/service#check-parameters). Consul does not support UDP type checks, so therefore I would suggest an initial step would be to raise an issue against the Consul repository with this request.

Consul does, however, support script checks which could provide you with UDP styled checks for services. I ran a test locally using the job file below, which uses a script check to perform an `nc` command to check whether the UDP port is open. It uses the Consul docker image and performs a check against the Consul DNS interface. This would be my suggested approach for such as requirement. Please let me know what you think.

```hcl
job "consul" {
  datacenters = ["dc1"]

  group "agent" {
    network {
      port "dns" {
        to = 8600
      }
    }

    task "agent" {
      driver = "docker"

      config {
        image = "consul"
        ports = ["dns"]
      }

     service {
        port = "dns"

        check {
          type     = "script"
	  name     = "check_dns_interface"
          command  = "nc"
          args     = ["-z", "-v", "${NOMAD_IP_dns}", "${NOMAD_PORT_dns}"]
	  interval = "60s"
          timeout  = "5s"
        }
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by gfonseca-tc** [comment]
Hey @jrasell , thank you for your answer! I'll follow both your suggestions! I will open an issue in the Consul repo and try something similar to the approach you suggested. My case is a little different because the container I'm using does not have any tool besides the application. I'm trying to create another task, check against it and alias the check for the actual container.

**Comment by Amier3** [comment]
Closing this as this is actively being worked on in the Consul Repo 👍

**Comment by tgross** [comment]
Cross-linking https://github.com/hashicorp/consul/pull/12722

**Comment by shantanugadgil** [comment]
@jrasell wouldn't the above `nc` example need the `-u` parameter?

@tgross would it be ok to revive this issue? now that Consul 1.3.0 has landed with the UDP health check support :fireworks:

**Comment by jrasell** [comment]
@shantanugadgil yes, so it's probably a typo.

I will raise a new request to add support for Consul UDP checks and link to this issue rather than reopen.
