### ISSUE TITLE
ui/exec opens incorrect container when two tasks have the same name

### ISSUE THREAD

**Issue by casdr** [hashicorp/nomad#11994]
### Nomad version
Nomad v1.2.5 (06d912a20ba029c7f4d6b371cd07594cba3ae3cd)

### Operating system and Environment details
Debian 10, 4.19.0-18-amd64

### Issue

I have a job with two groups that contain a task with the same name. When I go to the Exec page in Nomad, and select either one of the tasks, I always enter an allocation of the last task that's defined in the job file.

### Reproduction steps

Create a simple job that contains two different groups, each of which contains one task with the same name. Then go to the Exec page and try to enter the task for the first group defined in the job file (test1 -> httpd).

#### Expected Result

Nomad enters the one of the allocations for the first task in the correct group (test1 -> httpd).

#### Actual Result

Nomad enters the allocation for a task with the same name in the last group defined in the job file (test2 -> httpd).

### Job file (if appropriate)

```
job "duplicate-test" {
  type = "service"

  meta {
    version = "8"
  }

  group "test1" {
    count = 1

    task "httpd" {
      driver = "docker"

      config {
        image = "httpd"
      }
    }
  }

  group "test2" {
    count = 1

    task "httpd" {
      driver = "docker"

      config {
        image = "httpd"
      }
    }
  }
}
```

**Comment by lgfa29** [comment]
Thanks for the report @casdr. I believe this is the same problem described in https://github.com/hashicorp/nomad/issues/10962 so I'm going to close this one. Feel free to add any further information there 🙂

**Comment by casdr** [comment]
@lgfa29 ah, missed that one. Thanks!
