### ISSUE TITLE
UI: namespace not preserved across clicks

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#12022]
### Nomad version

1.2.0

### Operating system and Environment details

Arch Linux, Firefox (`96.0.3 (64-bit)`)

### Issue

In the UI, when I navigate to a certain Allocation (`https://nomad.tld/ui/jobs/vector/vector`) for example, I am able to see the list of running tasks etc normally:

![image](https://user-images.githubusercontent.com/5689132/152914675-d31571d8-243c-43da-a9a3-2f07774ff221.png)

However, when I reload the same page (using F5/Browser refresh button), I see this page:

![image](https://user-images.githubusercontent.com/5689132/152914775-abf48cab-5045-41e6-99fd-cdaa148fdd0d.png)

I noticed this doesn't happen when `?namespace` is in the URL. So:

- `https://nomad.tld/ui/jobs/vector/vector` reload doesn't work
- `https://nomad.tld/ui/jobs/vector/vector?namespace=logging` reload works.

I think the issue is that this `?namespace` is actually stripped off from the part of the URL when navigating inside the jobs.

### Reproduction steps

1. Visit `https://nomad.tld/ui/jobs?namespace=*` which is the default page.
2. Click on any job. For eg: `vector` takes me to: `https://nomad.tld/ui/jobs/vector?namespace=logging`
3. Inside this page, if I click on `Tasks`/`Allocation`, the `?namepsace` is removed from the URL: `https://nomad.tld/ui/jobs/vector/vector` or `https://nomad.tld/ui/allocations/89f9516e-1583-fe6a-6af3-d08dc99147da`
4. Reloading the above URL, it throws 404 (probably trying to find this task/allocation in the `default` namepsace)

#### Expected Result

`?namespace=<>` should be preserved when navigating across different sections of the UI.

#### Actual Result

Since `?namespace` isn't present, reloading the link (or clicking directly without the frontend clicks on the SPA) leads to a 404.

**Comment by ChaiWithJai** [comment]
@Amier3 I'm on it!

**Comment by lgfa29** [comment]
Thanks for the report @mr-karan. We noticed this happening as well (usually when sorting and searching, more details in https://github.com/hashicorp/nomad/issues/11327).

That's why @ChaiWithJai re-factored how namespaces are handled in the UI in #12082, which will be released in Nomad 1.3.0. 

I just checked your reproduction steps in `main` and this problem is fixed, so I'm going to close this one.
