### ISSUE TITLE
Add support for a ignore_timeouts option within check_restart stanza

### ISSUE THREAD

**Issue by axsuul** [hashicorp/nomad#12061]
### Proposal

Add support for `ignore_timeouts` to `check_restart` stanza, similar to `ignore_warnings`. This is so that whenever there's a timeout from the check, it won't count and keep performing the check.

I can envision many scenarios where timeouts should not be treated as failures since the result itself is dubious.

### Use-cases

I have a check for a job that checks for existence of a mile in a NFS mount. If the NFS mount goes offline, then the check will timeout but I don't want that to count as a failure and restart the job, but rather keep trying the check until the NFS mount comes back online. For example

```terraform
check {
  type     = "script"
  command  = "/bin/bash"
  args     = ["test -f /path/to/file"]
  interval = "60s"
  timeout  = "5s"

  check_restart {
    limit = 3
    ignore_timeouts = true
  }
}
```

### Attempted Solutions

I have tried setting a large `timeout = "1h"` but I think there's an opportunity for a better solution here.

**Comment by tgross** [comment]
@axsuul the timeout is fairly fundamental to being able to work correctly in the face of node failures. If you don't want the task to restart, you can set [`check_restart.limit = 0`](https://www.nomadproject.io/docs/job-specification/check_restart#limit). In the scenario you've described here, what's the difference between a timeout and a failure? If you can have your script check treat a "timeout" as a warning (exit code 1), then you could potentially use [`ignore_warnings`](https://www.nomadproject.io/docs/job-specification/check_restart#ignore_warnings) as well.

**Comment by tgross** [comment]
I'm going to close this issue out as we haven't heard back on the clarification and it looks like there's an existing approach to getting the desired results. Please feel free to let us know if you have more thoughts on this! Thanks!
