### ISSUE TITLE
Typo spotted in ACL documents

### ISSUE THREAD

**Issue by liugang-sd** [hashicorp/nomad#12100]
### Nomad version
Output from `nomad version`

### Issue
https://learn.hashicorp.com/tutorials/nomad/access-control-create-policy?in=nomad/access-control
the word 'course' should be 'coarse', there are 3 places.

fix typo.

**Comment by jrasell** [comment]
Hi @liugang-sd and thanks for raising this issue. I have raised a PR against the internal repository which contains this code and will update this ticket once that has been reviewed.
