### ISSUE TITLE
Add a way to make binds not noexec

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad#12119]
### Proposal
Right now bind mounts and the local task dir are mounted into allocs with the noexec flag set.  This precludes the ability to fetch scripts with artifact or add binaries this way.  It would be nice to have a way to either change the options passed to mount to allow things to become executable in the alloc.

### Use-cases
Two use cases come to mind immediately:
  1. Templating out a shell script and then using that in the alloc.
  2. Fetching a binary and injecting it into an environment.

### Attempted Solutions
I'm fairly sure this used to work pre 1.2.6, but I can't confirm that for sure.  I've also tried to bind the executable artifacts with docker binds but those appear to use the same mounts.

I'm 90% sure this used to work at some point and it either changed at some point or my environment was broken in such a way that it was not enforcing mount options.  Try as I might though I haven't been able to prove this claim.

**Comment by lgfa29** [comment]
Hi @the-maldridge 👋 

Would it be possible to provide a sample job of what you are trying to do? You mentioned that it may be the case that this used to work in Nomad, so it would be helpful to have an example of what you used to do.

Thanks!

**Comment by the-maldridge** [comment]
Sure, here's a job file that shows what I am trying to do.  Ultimately this is related to a workaround (hashicorp/vault#12768) where I need to be able to inject a helper into a bunch of different tasks without doing any additional container builds to repack 3rd party artifacts.

```
job "sftpgo" {
  type = "service"
  datacenters = ["US-WEST-2-SFTP"]
  priority = 79

  group "sftp" {
    count = 1
    shutdown_delay = "120s"

    network {
      mode = "bridge"
      port "http" { to = 8080 }
      port "ssh" {
        static = 2222
        to = 2022
      }
    }

    service {
      port = "http"
    }

    task "app" {
      leader = true
      driver = "docker"

      vault {
        policies = [
          "app-sftp",
        ]
      }

      config {
        image = "ghcr.io/drakkan/sftpgo:v2.2.0-alpine"
      }

      resources {
        cpu = 1000
        memory = 1000
      }

      env {
        AWS_SHARED_CREDENTIALS_FILE = "/local/credentials"
        SFTPGO_COMMON__SETSTAT_MODE = "2"
        SFTPGO_DATA_PROVIDER__DRIVER = "mysql"
        SFTPGO_DATA_PROVIDER__HOST = "sftpgo-db.cluster-<redacted>.us-west-2.rds.amazonaws.com"
        SFTPGO_DATA_PROVIDER__PORT = 3306
        SFTPGO_DATA_PROVIDER__NAME = "sftpgo"
        SFTPGO_SFTPD__HOST_KEYS = "/secrets/id_rsa,/secrets/id_ecdsa,/secrets/id_ed25519"
        SFTPGO_TELEMETRY__BIND_ADDRESS=""
        VACH_VAULT_BLOB="/secrets/credentials"
        VAULT_ADDR="http://active.vault.service.consul:8200"
      }

      template {
        data = <<EOF
{{- with secret "secret/sftp/ssh" -}}
{{.Data.ssh_host_rsa_key}}
{{- end -}}
EOF
        destination = "secrets/id_rsa"
      }

      template {
        data = <<EOF
{{- with secret "secret/sftp/ssh" -}}
{{.Data.ssh_host_ed25519_key}}
{{- end -}}
EOF
        destination = "secrets/id_ed25519"
      }

      template {
        data = <<EOF
{{- with secret "secret/sftp/ssh" -}}
{{.Data.ssh_host_ecdsa_key}}
{{- end -}}
EOF
        destination = "secrets/id_ecdsa"
      }

      template {
        data = <<EOF
{{- with secret "db/creds/sftpgo_app" }}
SFTPGO_DATA_PROVIDER__USERNAME = "{{.Data.username}}"
SFTPGO_DATA_PROVIDER__PASSWORD = "{{.Data.password}}"
{{- end }}
EOF
        destination = "secrets/env"
        env = true
      }

      # These two template blocks and the artifact block at the bottom
      # work around a shortcoming in AWS that prevents the system from
      # simply reloading the credentials.  The "preferred" way from
      # AWS's perspective to do this is to stand up a network level
      # proxy that rewrites credentials as though the task were on a
      # bare machine.  This is both 1) more complicated and 2) more
      # costly than just having vault provide the credentials to the
      # task environment.  So we use the binary from the artifact
      # block to convert from the format that vault provides to the
      # format that the AWS Credentials Process is expected to return.
      template {
        data = <<EOF
{{secret "aws/creds/app-sftp" | toJSON}}
EOF
        destination = "secrets/credentials"
        change_mode = "noop"
      }

      template {
        data = <<EOF
[default]
credential_process = /local/vault-aws-credential-helper
EOF
        destination = "local/credentials"
        change_mode = "noop"
      }

      artifact {
        source = "https://github.com/the-maldridge/vault-aws-credential-helper/releases/download/v0.1.1/vault-aws-credential-helper_0.1.1_Linux_x86_64.tar.gz"
      }
    }
  }
}
```

This task deploys just fine, but what doesn't work is actually calling the vault-aws-credential-helper binary.  Because `/local` is mounted with `noexec` this results in permission denied even though the binary has execute permissions.

**Comment by lgfa29** [comment]
Thanks for the example. Maybe I'm still missing something, so apologies in advance 😅, but I'm not able to reproduce the issue. 

I tried to create a minimal reproduction based on the job you shared:

```hcl
job "nomad" {
  datacenters = ["dc1"]
  type        = "batch"

  group "nomad" {
    task "nomad" {
      driver = "docker"

      config {
        image   = "ubuntu:20.04"
        command = "/local/bin/nomad"
        args    = ["--version"]
      }

      artifact {
        source      = "https://releases.hashicorp.com/nomad/1.2.6/nomad_1.2.6_linux_amd64.zip"
        destination = "local/bin"
      }
    }
  }
}
```

And this seems to work. Am I missing something? 😄

**Comment by the-maldridge** [comment]
I don't think you've missed anything, that looks pretty much like what I am doing and vastly simplified.  I am not entirely sure what's gone wrong here, I will run this again and see if I can get more log information out.

**Comment by the-maldridge** [comment]
@lgfa29 thanks for taking a look into this.  I dug deeper into my machines and found the following.  On a machine where things work the nomad binds are setup like so:

```
/dev/nvme1n1p1 /alloc ext4 rw,relatime 0 0
/dev/nvme1n1p1 /local ext4 rw,relatime 0 0
tmpfs /secrets tmpfs rw,noexec,relatime,size=1024k 0 0
```

However on a machine that has the nonworking behavior, the same binds have different configuration:

```
tmpfs /alloc tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0
tmpfs /local tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0
tmpfs /secrets tmpfs rw,noexec,relatime,size=1024k 0 0
```

The version of dockerd is different between the machines, as well as the version of runc, though I am struggling to understand why that would affect things here.

**Comment by the-maldridge** [comment]
So this turned out to be an interesting and somewhat obnoxious problem.  In my environment for complicated reasons beyond the scope of this ticket `/var` is a tmpfs.  This normally doesn't matter because `/var/persist` is an ext4 scratch disk.  However in the case that the scratch disk fails to mount, the mount options will be propagated down from the higher level mount, leading to all the mounts on `/var/persis/nomad` having the noexec parameter.

Since this was not a nomad issue, I will now close this ticket.
