### ISSUE TITLE
nomad node gc question

### ISSUE THREAD

**Issue by sheweichun** [hashicorp/nomad#1215]
`[question]`
### Nomad version
Nomad v0.3.2

### Operating system and Environment details
Linux  3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

  how can I set nomad node gc strategy? after a scheduled job was finished some time,I can't find it,I event don't know whether it works.can I set gc interval longger? where to configure it?

**Comment by diptanu** [comment]
@sheweichun Nomad GCs allocation after four hours. Are you trying to inspect the state of the job after four hours?

**Comment by sheweichun** [comment]
I found in that I can set  node_gc_threshold  in server.hcl,but it didn't working!
My job is running at 4:00am every day,when I came to company,I even didn't know whether they had runned,even I couldn't check their log files

**Comment by dadgar** [comment]
Hey, there may be a bug with the node GC at the moment. I will be looking
into it shortly.

**Comment by dadgar** [comment]
Hey,

Sorry I misread this issue. Nomad stores everything in-memory and as such can not keep an unbounded history of allocations. We have blocking queries which allow you to pull for changes to allocations. This can be used to ingest the state changes and build your own long term storage solution.

This is not something we are tackling right now

**Comment by hgontijo** [comment]
@diptanu is the GC executed every 4 hours the same as [/v1/system/gc](https://www.nomadproject.io/docs/http/system.html) ?
