### ISSUE TITLE
Checks should allow different port than the service port

### ISSUE THREAD

**Issue by flozano** [hashicorp/nomad#1216]
When using consul directly, you can specify full URLs that include a different port than the service port itself. This is not possible when using nomad, or at least I don't see how. 

My components have two ports exposed - a "service" http port and a "private" http port which exposes health-checks and other stuff. I declare both in nomad job file.

I'd rather not expose my health-checks in the same port where I'm serving requests, as it forces me to "firewall" it at the HTTP level somehow.

**Comment by diptanu** [comment]
@flozano Makes sense, we could allow users to override the port in a check definition.

**Comment by flozano** [comment]
Another use-case is that some components expose non-HTTP services in their service port (eg: mqtt), but still have the same common HTTP healthcheck/management interface as any other component in my stack.
