### ISSUE TITLE
Editing an existing job definition deletes expose paths

### ISSUE THREAD

**Issue by jhitt25** [hashicorp/nomad#12174]
### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

### Operating system and Environment details
8 node nomad/consul cluster, 3 control, 5 worker nodes.  All nodes running Nomad 1.2.6, Consul 1.11.3 and Oracle Linux 7.9 with kernel 5.4.17

### Issue
When editing an existing job definition in the UI manually defined expose paths are lost, even if no actual edit is performed.  Simply clicking 'Edit', then 'Plan' and 'Run' will remove existing expose paths.

### Reproduction steps
Run a simple job:
```
job "test-job" {
  datacenters = ["centralus"]
  type        = "service"

  group "test-group" {
    count = 1

    network {
        mode = "bridge"
        port "http-echo" {}
        port "health"  {}
    }

    service {
      name = "test-service"
      port = "8080"

      connect {
        sidecar_service {
          proxy {
            expose {
              path {
                path = "/"
                protocol = "http"
                local_path_port = 8080
                listener_port = "health"
              }
            }
          }
        }
      }
    }

    task "test-task" {
      driver = "docker"
      config {
        image = "hashicorp/http-echo:latest"
        args = [ "-listen=:8080", "-text='expose test'" ]
      }
    }
  }
}
```

If you view the definition, under TaskGroups[0].Services[0].Connect.SidecarService.Proxy you will have:
```
                "Expose": {
                  "Paths": [
                    {
                      "Path": "/",
                      "Protocol": "http",
                      "LocalPathPort": 8080,
                      "ListenerPort": "health"
                    }
                  ]
                },
```
Next, edit the job (there's no need to make any changes), plan, and run.

If you view the definition now, TaskGroups[0].Services[0].Connect.SidecarService.Proxy.Expose will be null.

#### Expected Result
The expose paths will be retained

#### Actual Result
The expose paths are removed

**Comment by jrasell** [comment]
Hi @jhitt25 and thanks for raising this issue.

I have not been able to reproduce this locally using v1.2.6 or current main yet. Could you share the details reported when you perform the plan phase of the reproduction along with any logs from the server?

**Comment by jrasell** [comment]
Hi @jhitt25 and thanks for the updated response. I notice in the file `5_run_request` that the expose section is detailed as expected which suggests the UI is sending the correct request to Nomad.

> nothing showing up in the Nomad logs

So is the UI request making it to the Nomad leader? If so, grabbing all the logs from around the time where you perform action relating to stage 5 would be useful.

**Comment by jhitt25** [comment]
I just re-ran all my steps again while monitoring the nomad logs on all 3 servers.  There is not a single log line during the job manipulation on any of the 3 servers.  I'm only at log_level = "INFO", should i increase it to DEBUG (or some other value?) during this test to get more information?

My UI request initially was not on the leader.  I did re-run all the steps directly against the currently elected leader and the result is identical.  The Expose paths are missing in the final job and there is nothing in the nomad logs during this timeframe.

**Comment by jorgemarey** [comment]
Maybe a duplicated of #11304 ?
