### ISSUE TITLE
Attributes and built-in functions are not working correctly

### ISSUE THREAD

**Issue by nierob** [hashicorp/nomad#12176]
### Nomad version
1.2.5

### Issue
Built in function are not working correctly with "attr.nomad". At least it is a bit confusing and not consistent.

### Reproduction steps
I'm using snippet below as testing env
```hcl
env {
        VAR_1 = "${trimsuffix(attr.nomad.advertise.address, "ss")}"
        VAR_2 = "${trimsuffix("attr.nomad.advertise.address", "ss")}"
        VAR_3 = "${trimsuffix(attr.nomad.advertise.address, "4646")}"
        VAR_4 = "${strrev(attr.nomad.advertise.address)}"
        VAR_5 = trimsuffix("${attr.nomad.advertise.address}", "ss")
        VAR_6 = trimsuffix("${attr.nomad.advertise.address}", "4646")}
...
template {
  data = <<EOF
    {{env "VAR_1"}}
    {{env "VAR_2"}}
    {{env "VAR_3"}}
    {{env "VAR_4"}}
    {{env "VAR_5"}}
    {{env "VAR_6"}}
EOF
```
Produces (I have replaced my public IP manually with 127.0.0.1):
```
    127.0.0.1:4646
    attr.nomad.advertise.addre
    127.0.0.1:4646
    }sserdda.esitrevda.damon.rtta{$
    127.0.0.1:4646
    127.0.0.1:4646
```

The only result I can explain is VAR_2. Everything else is a bit odd. It seems that in most cases function result is just dropped and replaced with the value of attribute, well except VAR_4 which is just funny ;-). Initially I thought that it may be some type conversion issue so I played with `convert(attr.nomad.advertise.address, string)` but it was not helping. I believe that other function like for example replace behave the same. Just to be explicit, I would expect VAR_3 and VAR_6 to produce `127.0.0.1:`

 It looks like the variable evaluation is happening after function call. So for example trim acts on attribute name and finally attribute value is substituted. 

I have failed to see if it is bug in HCL library or in nomad.

**Comment by jrasell** [comment]
Hi @nierob and thanks for raising this issue.

The HCLv2 template functions are executed on job registration within the HTTP agent handler. The interpolation within the env block is conducted on the client where the allocation is placed and utilises basic string substitution. The `trimsuffix` functionality is therefore acting on the string "attr.nomad.advertise.address" and not the IP address because the interpolation happens after the HCLv2 template functions have triggered. This therefore explains the behaviour you are seeing, which is expected.

**Comment by nierob** [comment]
Oh I see. So `trimsuffix(attr.foo, "4646")` -> resolves to `attr.foo` and then it is resolves to its value. And the same happens with strrev but `oof.rtta` is not substituted at the end with a value because it is not recognized as an attribute.

So essentially it is not possible to extract IP from IP:PORT from attribute with this approach. I will have to find another way, then :-) Thanks a lot!
