### ISSUE TITLE
Make the internal vault constraint optional for certain jobs

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/nomad#12188]
### Proposal
A flag/option in the job spec to make the internal vault constraint that is added when vault { } statement is used optional. 

### Use-cases
Over the past few months we have noticed some undesireable behaviour with Nomad and Vault; we have a set of system jobs (web ingress) who use vault to fetch SSL certs stored in the KV store. However, any time Vault is down for any length of time, these system jobs immediately stop. Additionally, these system jobs tend to not be automatically re-evaluated upon the return of vault so we spend an inordinate amount of time re-evaluating things by hand.

Vault has gone down on us once or twice due to network issues, and at this point has more or less turned into a SPOF because it takes down jobs that are still capable of running just fine (until secrets need renewed). It seems to affect system jobs most of all, other regular service jobs don't seem to suffer from it nearly as much. 

These jobs do need Vault to start, but no longer need Vault after they have started - at least, they can live without it for a while. It would therefore be absolutely amazing to be able to tell Nomad that it's okay if Vault isn't present, and leave it to the point where secrets are to be renewed to error out the allocation. 

Whether this takes the form of an option flag in the vault { } stanza or an option in the template (e..g {{ with secret "kv/some/secret" ttl="7d" }} ) where the ttl is explicitly set is left up as an exercise to whoever picks this one up ;) 

### Attempted Solutions
We have switched apps that can be modified to just use an approle login to get to vault directly without Nomad's vault {} stanza, but this is not always possible or desireable.

**Comment by jrasell** [comment]
Hi @benvanstaveren; the Vault constraint is only used during allocation placement to ensure it is not placed on a client which does not have the ability to call Vault. Without this, allocations could be placed on clients where they have no chance of starting. It would not affect the way in which allocations behave when the Vault cluster becomes unavailable.

>  any time Vault is down for any length of time, these system jobs immediately stop

Would you be able to provide client/server log output, task events, or similar details where this happens? It would be useful to understand what exactly is causing these jobs to stop. My initial though is that it will be something to do with the template stanza and therefore consul-template.

**Comment by benvanstaveren** [comment]
I've gone through syslog for one of our agent nodes, and it usually starts with the inability to render templates (we have a few that take data from consul as well); 

`2022-03-01T17:46:03.752Z [WARN]  agent: (view) vault.read(secret/data/ssl/xxxxxxxx/wildcard): vault.read(secret/data/ssl/xxxxxx/wildcard): redirect would cause protocol downgrade (retry attempt 2 after "500ms")`

That repeats for a while - and makes sense because there's obviously no vault available to make the request to. The templates are all set to change_mode = "signal" with a signal of SIGHUP (it's nginx inside the container). They also have an auto_revert = true statement in the update {} stanza in the job. Not sure where that protocol downgrade comes from but assuming it's the loadbalancer in front of our 3 vault instances (lb is set up to only consider the active vault as a target) 

It seems that at the point where the above errors cause a failure, Nomad attempts to revert by recreating the allocation, at which point the vault constraint is obviously not able to be met since the fingerprinter has decided it's not there anymore.

And then we start seeing things like this:

`2022-03-01T17:46:27.660Z [ERROR] client.vault: error deriving token:`

Which also makes sense, considering there is no vault to talk to to derive anything 

Perhaps a way for us to indicate for templates using signal change mode that if an error occurs with fetching data from vault that it's a non-fatal error, and just keep using the existing template, and log the error so it can be picked up by monitoring tools would be a better feature. 

The rationale being I'd rather have a running (but perhaps misconfigured) instance of something than a completely hard down instance. Of course, if such a feature would be implemented, it'd need documenting that it's entirely at your own risk, if it breaks you get to keep both pieces, and so on.

**Comment by jrasell** [comment]
I believe the [client template vault retry](https://www.nomadproject.io/docs/configuration/client#vault_retry) configuration parameter solves the feature you describe. It would allow you to configure your clients to expect extended Vault outages without stopped the allocations. 

> This controls the retry behavior when an error is returned from Vault. Consul Template is highly fault tolerant, meaning it does not exit in the face of failure. Instead, it uses exponential back-off and retry functions to wait for the cluster to become available, as is customary in distributed systems.

**Comment by benvanstaveren** [comment]
Well I'll be bleeped... that does look like it would solve that issue. I wasn't aware those were possible options, this job pretty much went unaltered since Nomad 0.5.x so I have to admit I haven't really kept up to date with the changelogs and new features as much as I should have.

Alright, consider this issue closed I guess :)

**Comment by jrasell** [comment]
That is not a problem @benvanstaveren. It's the first time I have taken a proper look at that parameter. Also happy to see Nomad has been stable for you since an early version!

I'll close out this issue then. If you have any issues with those parameters, please raise another issue so we can take a look into it.
