### ISSUE TITLE
docs: iptables conflicts with firewalld

### ISSUE THREAD

**Issue by ruhrscholz** [hashicorp/nomad#12199]
### Nomad version
`Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)`

### Operating system and Environment details
Rocky Linux 8.5 with Docker CE from the official Docker repo, Nomad v1.2.6 from the Hashicorp repo, and CNI plugins v1.1.0.

### Issue
When setting the network mode of a group (of docker tasks) to "bridge", while incoming connections still work, is not possible for the Docker containers to reach the local network or the internet (from Nomad's `172.26.64.1/20` network). This works when the container is using the "legacy" `docker0` network (using the `172.17.0.1/16` network created by Docker).

### Reproduction steps
Set up Nomad as per the official instructions. Run job provided below. Try to curl/ping/apt update/... any resource outside of other containers, for example just `apt update`.

#### Expected Result
Working internet connectivity for fetching task-related assets and APIs.

#### Actual Result
Container can access the Nomad client (for example its web interface at `http://172.26.64.1:4646`), but no other local or global networks. Thus, DNS fails too. It seems like routing on the Nomad client does not work correctly.

### Job file (if appropriate)

```
job "test" {
    datacenters = ["dc1"]

    group "webservice-cache" {
        network {
            mode = "bridge"
            port "redis" {
                to = 6379
            }
        }
        task "webservice" {
            // network_mode not set as per documentation: https://www.nomadproject.io/docs/drivers/docker#network_mode
            driver = "docker"

            config {
                image = "redis:3.2"
                ports = ["redis"]
            }
        }
    }
}
```

### Nomad Client logs (if appropriate)

(Shortened) output of `ip a`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
6: bond0.20@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:ea:7f:ab:cc:78 brd ff:ff:ff:ff:ff:ff
    inet 10.0.20.2/24 brd 10.0.20.255 scope global dynamic noprefixroute bond0.20
       valid_lft 523sec preferred_lft 523sec
    inet6 fe80::4910:8e19:d1b9:e554/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
9: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:24:b9:97:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:24ff:feb9:97f2/64 scope link 
       valid_lft forever preferred_lft forever
10: nomad: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:58:41:fa:ee:80 brd ff:ff:ff:ff:ff:ff
    inet 172.26.64.1/20 brd 172.26.79.255 scope global nomad
       valid_lft forever preferred_lft forever
    inet6 fe80::c42b:fbff:fe24:dc72/64 scope link 
       valid_lft forever preferred_lft forever
```

(Shortened) output of `ip route`:

```
10.0.20.0/24 dev bond0.20 proto kernel scope link src 10.0.20.2 metric 400 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.26.64.0/20 dev nomad proto kernel scope link src 172.26.64.1 
```

I could also rule out SElinux ~and firewalld~.

**Comment by ruhrscholz** [comment]
This issue has not been reproducible on a newly installed test-setup, so I'll close this and maybe update this issue when I've found the culprit.

**Comment by ruhrscholz** [comment]
As it turns out, the issue does not happen on my Debian test-setup, but is persistently happening in Rocky Linux-based installations. Setups, versions, etc. are identical between those two, as is the network and job configuration.

After some more testing it turns out the underlying issue was in fact firewalld, disabling just didn't help in the first comment because I did not restart docker and nomad afterwards. Now onto searching a proper firewalld setup for this.

**Comment by BirkhoffLee** [comment]
I can verify it is a valid workaround for CentOS 8 Stream:

```
sudo sysctl -w net.ipv4.ip_forward=1
sudo systemctl stop firewalld
sudo systemctl restart docker
sudo systemctl restart nomad
```

**Comment by BirkhoffLee** [comment]
> As it turns out, the issue does not happen on my Debian test-setup, but is persistently happening in Rocky Linux-based installations. Setups, versions, etc. are identical between those two, as is the network and job configuration.
> 
> After some more testing it turns out the underlying issue was in fact firewalld, disabling just didn't help in the first comment because I did not restart docker and nomad afterwards. Now onto searching a proper firewalld setup for this.
> 
> UPDATE: If anyone runs into the same issue, the problem is that even if you allow packet forwarding in the Kernel, it is (by default) not allowed in firewalld. Solution: `firewall-cmd --add-forward` (don't forget to turn that setting `--permanent`).

It seems adding `nomad` network interface to firewalld trusted zone is sufficient to make it work, could you verify?

```
sudo systemctl start firewalld
sudo firewall-cmd --zone=trusted --add-interface=nomad
sudo systemctl restart docker
sudo systemctl restart nomad
```

**Comment by ruhrscholz** [comment]
> 
> It seems adding `nomad` network interface to firewalld trusted zone is sufficient to make it work, could you verify?
> 
> ```
> sudo systemctl start firewalld
> sudo firewall-cmd --zone=trusted --add-interface=nomad
> sudo systemctl restart docker
> sudo systemctl restart nomad
> ```

I can confirm that this works in both the test setup and our prod setup. While this seems to work okay, I wonder if this is the "right" way to do it, as containers do not necessarily have to be trusted (think hosting providers). Also, since as you noted people have had issues with this for a longer time, I'm going to leave this issue open. Whether this is worth a change in the networking scripts or an additional note in the documentation (or neither) is not for me to decide, also maybe someone chimes in with an even "cleaner" solution.

BTW: If you are doing that change on a non-test setup, just restarting the containers/the job is enough, it turns out restarting both services is overkill.

**Comment by tgross** [comment]
Hi @ruhrscholz and @BirkhoffLee! Glad to see you've got this figured out. The underlying issue here is that both Nomad (via CNI and/or `dockerd`) and firewalld are trying to manipulate the packet filtering on the host. The Docker docs on the problem are pretty good (ref https://docs.docker.com/network/iptables/), and we have the additional complication that Nomad's use of CNI for `bridge` networking has its own iptables chain `NOMAD-ADMIN`.

> While this seems to work okay, I wonder if this is the "right" way to do it, as containers do not necessarily have to be trusted (think hosting providers).

It's definitely how I'd have done it. Arguably if you're giving Nomad (or Docker) control over iptables, you trust Nomad already as it's running as root (and by extension the job submitter, as we don't have any specific ACLs on networking). So Nomad should own control over routing for those network namespaces. But if you want coarse-grained host-wide control over outbound connectivity, you could always have firewalld set a rule on the `nomad` bridge interface.

In any case, I think it's definitely worth coming up with some documentation guidance for this kind of thing so I'm going to mark this as a documentation issue. I'd be happy to help shepherd a documentation PR from either of you if you're interested.
