### ISSUE TITLE
Improve documentation about artifact downloading

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#1219]
For instance, one very subtle detail that almost always bites me is that 
instead of specifying the source `mybucket.s3.amazonaws.com/containers/vault.tar.gz` I always do it with the protocol scheme like so: `https://mybucket.s3.amazonaws.com/containers/vault.tar.gz` and nomad fails downloading the artifact from S3 with 403.

**Comment by pshima** [comment]
Closing with https://github.com/hashicorp/nomad/pull/1232

**Comment by c4milo** [comment]
Thank you!

**Comment by diptanu** [comment]
@pshima Let's not close it yet, we might be able to do some validation here in the cli.

**Comment by sethvargo** [comment]
Hi there,

This is done and there are now a ton of examples in both the job file and online documentation. I think it makes sense to push this kind of validation into go-getter if we want to do that validation, but it's also a relatively small win given the massive amount we've invested in documentation. I'm going to close out this issue, but it'll remain searchable for the future humans. 😄
