### ISSUE TITLE
Clean up docker images periodically

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/nomad#122]
It would be nice to remove docker images only after they are unused after X time. This allows minor gaps in time where the image isn't in use, but still cleans up stale images that aren't needed.

**Comment by EvanKrall** [comment]
Perhaps you could use something like https://github.com/yelp/docker-custodian?

**Comment by cbednarski** [comment]
@EvanKrall We have logic to cleanup containers but we don't currently have a way to this on a periodic or delayed basis. Currently containers are purged when a job is terminated.

At some point we may want to introduce a nomad-controlled delay on cleanup so jobs can be rescheduled on the same host as before and not need to re-pull all of the artifacts. This requires a bit of state tracking in Nomad so it can keep accounting of terminated but 

If you want to do this yourself (e.g. using docker-custodian or something else) you can set `docker.cleanup.container` and/or `docker.cleanup.image` in your agent config.

**Comment by davidpelaez** [comment]
I think that some regularly scheduled jobs could allow this to be easily added by the user. Maybe a common job running every day could take care of this. This makes think automatically about how job definition sharing could be useful instead of baked directly into nomad.

**Comment by ketzacoatl** [comment]
Agreed!

**Comment by schmichael** [comment]
Nomad now allows delaying removal of unused images: https://www.nomadproject.io/docs/drivers/docker.html#docker-cleanup-image-delay
