### ISSUE TITLE
nomad fs unable to inspect allocation directories in non-local hosts

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#1222]
### Nomad version
v0.4.0-dev

### Operating system and Environment details
CoreOS stable

### Issue
![](https://cldup.com/0gATvM2IEm.png)

**Comment by dadgar** [comment]
Hey,

You have to set the advertise address of the client's HTTP endpoint.

**Comment by diptanu** [comment]
Also, the client now, must listen on a non-loopback ip. @c4milo Are you just setting the `bind_addr` to `0.0.0.0`?

**Comment by c4milo** [comment]
Yes, I'm setting it to listen on all the network interfaces.

**Comment by c4milo** [comment]
Alex, I was running nomad client from one of the nomad servers.

**Comment by dadgar** [comment]
@c4milo I am not sure I understand your response. The client must set:
 ```
advertise {
   http = <address>
}
```

**Comment by c4milo** [comment]
Oh I understand now, yes, I only had the the advertise block on the servers. I will add it to the clients. Thanks!
