### ISSUE TITLE
Ability to define node tags in Consul and for Nomad to use them as scheduling constraints

### ISSUE THREAD

**Issue by bfgoodrich** [hashicorp/nomad#1228]
Consul [issue #154](https://github.com/hashicorp/consul/issues/154) would allow tags to be defined on nodes in Consul. Nomad could then use those node tags as additional/custom scheduling constraints.

**Comment by dadgar** [comment]
Hey,

Nomad supports adding metadata information to nodes directly. See the `meta` tag here: https://www.nomadproject.io/docs/agent/config.html. Jobs can use these as constraints as well.

I am going to close because we have this capability and the referenced issue is 2 years old.

**Comment by kaspergrubbe** [comment]
This was since moved from the agent, and into the client: https://www.nomadproject.io/docs/configuration/client.html, however, the server does not have any meta-tags: https://www.nomadproject.io/docs/configuration/server.html

**Comment by pySilver** [comment]
@dadgar is there a way to somehow mark a client currently running specific job so I can run another job there? What I'm specifically looking for is the way to determine where is my master db node is currently located, so I can run backup job there.
