### ISSUE TITLE
Missing ability to specify parameters/secrets in CSI CreateSnapshot

### ISSUE THREAD

**Issue by iSchluff** [hashicorp/nomad#12318]
### Proposal

Currently nomad only supports setting the volume name and snapshot name in the snapshot request. 
https://github.com/hashicorp/nomad/blob/154264fcd9276b53ea837664bceefd8b6f217291/command/volume_snapshot_create.go#L100-L103

However some plugins like ceph-csi require additional parameters/secrets to be set for the request to be valid.
https://github.com/ceph/ceph-csi/blob/d357bebbc21895cd8d01bf0f04e2db425b4b95c9/internal/cephfs/store/volumeoptions.go#L147

So nomad cli would need to implement the ability to pass these to be able to make snapshots.

### Use-cases

Ability to create snapshots in ceph-csi and possibly other CSI plugins.

**Comment by tgross** [comment]
Hi @iSchluff! In https://github.com/hashicorp/nomad/pull/10840 we added the ability to use the volume's secrets for creating snapshots (that shipped in Nomad 1.1.3). But I can definitely see wanting to have separate secrets for the delete call vs the create call. Most of the plumbing to do this was reworked in https://github.com/hashicorp/nomad/pull/12144 which will ship in Nomad 1.3.0, so it should be fairly straightforward to allow overriding the volume's secrets in the create request as well.

**Comment by iSchluff** [comment]
Hi @tgross, thanks for your feedback, however I think this would also need to be applied also for parameters.
E.g. for ceph you need to pass in a clusterID parameter with every request.
Optimally these could also be reused from the volume definition, but depending on the plugin it may be necessary to also specify parameters via the cli.

**Comment by tgross** [comment]
I'm starting implementation on this and expect to ship it shortly.

For what it's worth, the Ceph plugin should be using unique keys for each different secret it needs, all of which are passed along. So if there's a different secret for create vs snapshot, the Ceph plugin is supposed to handle that by having a different secret that we can store with the volume:

> CO SHALL permit passing through the required secrets. A CO MAY pass the same secrets to all RPCs, therefore the keys for all unique secrets that an SP expects MUST be unique across all CSI operations.
