### ISSUE TITLE
allow tls version configurations in gateway stanza

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#12349]
### Proposal

Hi! https://github.com/hashicorp/consul/issues/11966 consul added functionality to allow configuration min/max tls versions and cipher suite to use for the ingress listener, however the configuration is not accessible through the nomad gateway stanza. Request to expose corresponding configurations in nomad.

### Use-cases

To allow configure gateway listener tls versions through nomad gateway stanza.

**Comment by lgfa29** [comment]
Thanks for letting us know @fredwangwang. On a quick look I think it makes sense to expose these through Nomad as well.

I put this into our backlog for further triage.
