### ISSUE TITLE
Mechanism for obtaining job version in task environment

### ISSUE THREAD

**Issue by hntrmrrs** [hashicorp/nomad#12343]
### Proposal

Add `NOMAD_JOB_VERSION` to the task environment.

A candidate pull request #12338 has been submitted.

### Use-cases

Currently, there is no trivial way for a task environment to find out the current job version. Without knowledge of the job version, the alloc index may not be unique enough for certain configurations. See discussion here with suggestion by @tgross for a detailed example: https://github.com/hashicorp/nomad/issues/8045#issuecomment-634004128

### Attempted Solutions

It is potentially possible to obtain the job version via the API from within a task, but this requires at least an HTTP library and potentially TLS configuration which may be unsuitable for lightweight tasks.

**Comment by tgross** [comment]
https://github.com/hashicorp/nomad/pull/12338 was closed and the discussion (rightly, I think) landed on not implementing this because job versions get updated for all kinds of out-of-band reasons that then would not show up in the env of a running task.
