### ISSUE TITLE
Consul Connect sidecar not restarting despite failing checks

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#12345]
### Nomad version
`1,2,6`

### Operating system and Environment details
`Linux nomad02 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

`Ubuntu 20.04.4 LTS`

`envoyproxy/envoy:v1.20.1`

### Issue

When for some reason (out of scope for this issue, but it happens regularly; reason unknown), the Consul Connect sidecar task does not work any more - the health checks in Consul for `Connect Sidecar Listening` give out errors (i/o socket timeout), but despite that, nomad is not noticing these checks failing and does not restart the sidecar task.

### Reproduction steps

1. Have a service with consul connect sidecar
2. Have the sidecar fail for some reason (no idea what would cause it) and result in only i/o timeouts
3. This automatically results in the Consul health checks marking `Connect Sidecar Listening` as failed (and thus the entire service instance within Consul as failed)
4. See that Nomad does not restart the task

#### Expected Result

Nomad should restart the sidecar task, if Consul says it failed. 

#### Actual Result

Nomad does not restart the sidecar task; Nomad does not restart anything at the moment and is OK with the instance failing in Consul.

### Job file (if appropriate)
Any job file containing a connect sidecar:

```hcl2
    service {
      name = "my-happy-service"
      connect {
        sidecar_service {}
     }
   }
```

### Nomad Client logs (if appropriate)

No relevant entries were present in the log (log-level `INFO`).

**Comment by lgfa29** [comment]
Hi @EtienneBruines 👋 

Thanks for the report. Would it be possible to collect logs from Nomad in a lower level? You can use the [`nomad monitor`](https://www.nomadproject.io/docs/commands/monitor) to command to downgrade the log level without having to change any configuration.

Also, do you see anything in the Consul logs? Or would you be able to provide screenshots of the Consul UI with the error message?

Thanks!

**Comment by EtienneBruines** [comment]
The Consul UI specifically stated an `i/o timeout` error (while trying to connect to the TCP port that the Consul Connect sidecar was registered at) - manually trying to connect to this port using `curl` also resulted in the same i/o timeout. It then marked the instance of the service (as well as specifically the sidecar) as unhealthy / red. Seems like Consul itself is all working as expected. 

I will do my best to collect logs for a lower level for `nomad` when the issue reappears. (Happened three times over the past week, so shouldn't be too hard.)

**Comment by lgfa29** [comment]
Great, thank you for the extra info.

If you could also collect the sidecard logs and task events when it happens again they will be helpful too.

**Comment by EtienneBruines** [comment]
If it occurs again, this can be re-opened - but for now I'll close since it has not happened since. 

Perhaps updating envoy, consul and/or nomad fixed it at some point.
