### ISSUE TITLE
gRPC and TCP/HTTP listeners can't work together in the same gateway-ingress

### ISSUE THREAD

**Issue by Dgotlieb** [hashicorp/nomad#12356]
Nomad version
v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

Operating system and Environment details
Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: bionic

Issue
When placing gRPC listener and a TCP/HTTP listener in the same `gateway-ingress` an error is thrown

Reproduction steps
Place different listener types under the same gateway-ingress entry

Expected Result
Allow different listener types to be located under the same `gateway-ingress` entry

Actual Result
`Error submitting job: Unexpected response code: 500 (rpc error: Unexpected response code: 500 (service "service-a-http" has protocol "tcp", which does not match defined listener protocol "http"))`

Workaround
Separate the job into 2 groups:
* 1st group for gRPC listeners 
* 2nd group for non-gRPC (TCP/HTTP) listeners 

Job file (before workaround):
``` hcl
job "ingress" {
  type        = "service"
  datacenters = ["dc1"]

  group "ingress" {

    count = 3
    
    network {
      mode = "bridge"

      port "service-a-http" {
        static = 8000
        to     = 8000
      }

      port "service-a-grpc" {
        static = 8001
        to     = 8001
      }
    }

    service {
      name = "ingress"      
      connect {
        gateway {
          proxy {}
          ingress {
            listener {
              port = 8000
              service {
                name = "service-a-http"
              }
            }

             listener {
               port     = 8011
               protocol = "grpc"
               service {
                 name  = "service-a-grpc"
                 hosts = ["*"]
               }
             }
          }
        }
      }
    }
  }
}
```

Job file (after workaround):
``` hcl
job "ingress" {
  type        = "service"
  datacenters = ["dc1"]

  group "ingress" {

    count = 3

    network {
      mode = "bridge"
      port "service-a-http" {
        static = 8000
        to     = 8000
      }
    }

    service {
      name = "ingress"

      connect {
        gateway {
          proxy {}
          ingress {
            listener {
              port = 8000
              service {
                name = "service-a-http"
              }
            }
          }
        }
      }
    }
  }

  group "ingress-grpc" {
    count = 3

    network {
      mode = "bridge"

      port "service-a-grpc" {
        static = 8011
        to     = 8011
      }
    }

    service {
      name = "ingress-grpc"

      connect {
        gateway {
          proxy {}
          ingress {
             listener {
               port     = 8011
               protocol = "grpc"
               service {
                 name  = "service-a-grpc"
                 hosts = ["*"]
               }
             }
          }
        }
      }
    }
  }
}
```

This issue is possibly related to https://github.com/hashicorp/nomad/issues/8647

**Comment by lgfa29** [comment]
Hi @Dgotlieb 👋 

I believe this is a characteristic of Consul. From their [ingress gateway](https://www.consul.io/docs/connect/gateways/ingress-gateway) documentation: 

> For listeners with a [protocol](https://www.consul.io/docs/connect/config-entries/ingress-gateway#protocol) other than `tcp`, multiple services can be specified for a single listener.

So `tcp` listeners must be set on their own.

Would you mind opening an issue in the Consul repo? You can link back to this one.

Thanks!

**Comment by Dgotlieb** [comment]
Hi @lgfa29 😄 
It seems like this issue could be on Consul side (and not Nomad). 
That being said, based on the docs and as you mentioned: 

> `tcp` listeners must be set on their own 

which I think means that I can add multiple services when using a "non-tcp" protocol (in this case `grpc`):
``` hcl
 ...
  ingress {
     listener {
       port     = 8011
       protocol = "grpc"
       service {
         name  = "service-a"
         hosts = ["foo"]
       }
       service {
         name  = "service-b"
         hosts = ["bar"]
       }
     }
...
```

But can't add more than one service when using `tcp` protocol:
``` hcl
 ...
  ingress {
     listener {
       port     = 8011
       protocol = "tcp"
       service {
         name  = "service-a"
       }
       service {
         name  = "service-b"
       }
     }
...
```

My issue is focused on the fact that when using **different** listeners, it works only when they are separated into different (Nomad) groups.


Thanks!

**Comment by Dgotlieb** [comment]
Hi @shoenig,
Sorry for the mistake, this was only a copy-paste mistake 😅 
I can confirm that the issue is happening as described.
I fixed the error text.

**Comment by Dgotlieb** [comment]
OK, after debugging a little more I realized this is 100% related to https://github.com/hashicorp/nomad/issues/8647
The issue is that Nomad can't register non-tcp services, and requires to first define [service-defaults](https://www.consul.io/docs/agent/config-entries/service-defaults.html) externally (via CLI / API) and then register the non-tcp listener via Nomad.
``` bash
$ cat 1.json
```
```json 
{
  "Kind": "service-defaults",
  "Name": "service-a-grpc",
  "Protocol": "grpc"
}
```

``` bash
$ consul config write 1.json
```

This is has nothing to do with the groups separation as I thought, but a Nomad issue nonetheless.
Would be nice to get an update... 

Sorry for the hassle.
Thank you
