### ISSUE TITLE
Driver exec error when call shell - Wait returned exit code 127

### ISSUE THREAD

**Issue by nguyenvantai0201** [hashicorp/nomad#1236]
I try execute sh file from nomad job. My setting and job nomad are bellow. Please help
**server.hcl**
`# Increase log verbosity
log_level = "DEBUG"
 
# Setup data dir
data_dir = "/tmp/serverv1"
 
# Enable the server
server {
    enabled = true
 
    # Self-elect, should be 3 or 5 for production
    bootstrap_expect = 1
}`

**client1.hcl** 
`# Increase log verbosity
log_level = "DEBUG"
 
# Setup data dir
data_dir = "/tmp/client1_v1"
 
# Enable the client
client {
    enabled = true
 
    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
    servers = ["127.0.0.1:4647"]
	options {
        "driver.exec.enable" = "1"
    }
}
 
# Modify our port to avoid a collision with server1
ports {
    http = 5656
}`

**example.nomad**
`task "exam" {
            		driver = "exec"

            		config {
                		command = "/bin/bash"
				args = ["./run.sh"]
            		}

                        resources {
                                cpu = 500 # 500 Mhz
                        }
        }`

**run.sh** 
`#!/bin/bash

mkdir /root/Desktop/example`

**run client1.hcl**

> [root@localhost nomad_v1]# nomad agent -config client1.hcl
    Loaded configuration from client1.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: true
             Log Level: DEBUG
                Region: global (DC: dc1)
                Server: false

==> Nomad agent started! Log data will stream in below:

    2016/06/07 11:04:13 [INFO] client: using state directory /tmp/client1_v1/client
    2016/06/07 11:04:13 [INFO] client: using alloc directory /tmp/client1_v1/alloc
    2016/06/07 11:04:13 [INFO] fingerprint.cgroups: cgroups are available
    2016/06/07 11:04:13 [DEBUG] client: periodically fingerprinting cgroup at duration 15s
    2016/06/07 11:04:13 [DEBUG] client: periodically fingerprinting consul at duration 15s
    2016/06/07 11:04:15 [DEBUG] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
    2016/06/07 11:04:17 [WARN] fingerprint.env_gce: Could not read value for attribute "machine-type"
    2016/06/07 11:04:17 [DEBUG] fingerprint.env_gce: Error querying GCE Metadata URL, skipping
    2016/06/07 11:04:17 [DEBUG] fingerprint.network: Detected interface enp3s0  with IP 10.133.41.37 during fingerprinting
    2016/06/07 11:04:17 [DEBUG] client: applied fingerprints [arch cgroup cpu host memory network nomad storage]
    2016/06/07 11:04:17 [DEBUG] driver.docker: using client connection initialized from environment
    2016/06/07 11:04:17 [DEBUG] driver.exec: exec driver is enabled
    2016/06/07 11:04:17 [DEBUG] client: periodically fingerprinting exec at duration 15s
    2016/06/07 11:04:17 [DEBUG] client: periodically fingerprinting docker at duration 15s
    2016/06/07 11:04:17 [DEBUG] client: available drivers [docker exec java]
    2016/06/07 11:04:17 [INFO] client: setting server address list: [127.0.0.1:4647]
    2016/06/07 11:04:17 [DEBUG] client: updated allocations at index 18 (pulled 0) (filtered 0)
    2016/06/07 11:04:17 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
    2016/06/07 11:04:17 [DEBUG] client: node registration complete
    2016/06/07 11:04:17 [DEBUG] client: periodically checking for node changes at duration 5s
    2016/06/07 11:04:21 [DEBUG] client: state updated to ready
    2016/06/07 11:04:24 [DEBUG] client: state changed, updating node.
    2016/06/07 11:04:24 [DEBUG] client: node registration complete
==> Newer Nomad version available: 0.3.2
    2016/06/07 11:07:25 [DEBUG] client: updated allocations at index 34 (pulled 0) (filtered 0)
    2016/06/07 11:07:25 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
    2016/06/07 11:07:26 [DEBUG] client: updated allocations at index 39 (pulled 1) (filtered 0)
    2016/06/07 11:07:26 [DEBUG] client: allocs: (added 1) (removed 0) (updated 0) (ignore 0)
    2016/06/07 11:07:26 [DEBUG] client: starting task runners for alloc 'f83b2700-5304-8166-220d-060a217e0e83'
    2016/06/07 11:07:26 [DEBUG] client: starting task context for 'exam' (alloc 'f83b2700-5304-8166-220d-060a217e0e83')
    2016/06/07 11:07:26 [DEBUG] plugin: starting plugin: /usr/bin/nomad []string{"/usr/bin/nomad", "executor", "/tmp/client1_v1/alloc/f83b2700-5304-8166-220d-060a217e0e83/exam/exam-executor.out"}
    2016/06/07 11:07:26 [DEBUG] plugin: waiting for RPC address for: /usr/bin/nomad
    2016/06/07 11:07:26 [DEBUG] plugin: nomad: 2016/06/07 11:07:26 [DEBUG] plugin: plugin address: unix /tmp/plugin226655227
    2016/06/07 11:07:26 [DEBUG] client: updated allocations at index 41 (pulled 0) (filtered 1)
    2016/06/07 11:07:26 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 1)
    2016/06/07 11:07:40 [DEBUG] driver.exec: started process via plugin with pid: 14927
    2016/06/07 11:07:40 [INFO] client: task "exam" for alloc "f83b2700-5304-8166-220d-**060a217e0e83" failed: **Wait returned exit code 127, signal 0, and error <nil>****

run example.nomad

> [root@localhost nomad_v1]# nomad run example.nomad
==> Monitoring evaluation "84069282"
    Evaluation triggered by job "example"
    Allocation "73764b15" modified: node "41eae840", group "cache"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "84069282" finished with status "complete

**Comment by dadgar** [comment]
Where is `run.sh`. When using the `exec` driver you need to use the `artifact` block to download the thing you want to execute. We isolate the filesystem of started allocations so your script may not be reachable!

If you run: `nomad fs cat <alloc-id> alloc/logs/exam.stderr.0` you will see that it can't find that script.
