### ISSUE TITLE
Improve logging on Connect proxy error

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#12389]
### Proposal

When there is an error creating the bootstrap configuration for Connect proxy sidecar, the error is not properly surfaced. Currently there is no indication of what happened when Envoy fails to start allocations

### Use-cases

Ideally Nomad could pass this error through to the end user so they could better diagnose and fix the issue.

For instance, an ACL mismatch in Consul and/or notifications on expired Certificates would be logged/surfaced.

### Attempted Solutions

The following code is used to surface the bug in a local Nomad fork:

```
diff --git a/client/allocrunner/taskrunner/envoy_bootstrap_hook.go b/client/allocrunner/taskrunner/envoy_bootstrap_hook.go
index fa9c63a43..494c7398a 100644
--- a/client/allocrunner/taskrunner/envoy_bootstrap_hook.go
+++ b/client/allocrunner/taskrunner/envoy_bootstrap_hook.go
@@ -274,6 +274,7 @@ func (h *envoyBootstrapHook) Prestart(ctx context.Context, req *ifs.TaskPrestart

 	// keep track of latest error returned from exec-ing consul envoy bootstrap
 	var cmdErr error
+	var cmdOut string

 	// Since Consul services are registered asynchronously with this task
 	// hook running, retry until timeout or success.
@@ -323,6 +324,8 @@ func (h *envoyBootstrapHook) Prestart(ctx context.Context, req *ifs.TaskPrestart
 		// fails.
 		_ = os.Remove(bootstrapFilePath)

+		cmdOut = buf.String()
+
 		return true, cmdErr
 	}, exptime.BackoffOptions{
 		MaxSleepTime:   h.envoyBootstrapWaitTime,
@@ -332,7 +335,7 @@ func (h *envoyBootstrapHook) Prestart(ctx context.Context, req *ifs.TaskPrestart
 		// Wrap the last error from Consul and set that as our status.
 		_, recoverable := cmdErr.(*exec.ExitError)
 		return structs.NewRecoverableError(
-			fmt.Errorf("error creating bootstrap configuration for Connect proxy sidecar: %v", cmdErr),
+			fmt.Errorf("error creating bootstrap configuration for Connect proxy sidecar: %v \n %v", cmdErr, cmdOut),
 			recoverable,
 		)
 	}
```

**Comment by gulducat** [comment]
Hi again @mikenomitch :)  I chatted with the team about this some more, and I'm wondering how this sounds to you.

Would it help if we added some documentation describing the process laid out in d47678074bf8ae9ff2da3c91d0729bf03aee8446 and included a link to that doc in the error that gets surfaced as a task event?

So in addition to

> envoy_bootstrap: error creating bootstrap configuration for Connect proxy sidecar: exit status 1

the message presented to the user could include a link like

> envoy_bootstrap: error creating bootstrap configuration for Connect proxy sidecar: exit status 1 -- see: https://developer.hashicorp.com/nomad/docs/integrations/consul-connect#limitations

How does that strike you?

**Comment by mikenomitch** [comment]
@gulducat and I had a chat about this offline. Given that the error messages from Consul aren't great to surface (see above comment). We probably aren't going to add the code change as is.

@gulducat is going to document the steps laid out [here](https://github.com/hashicorp/nomad/commit/d47678074bf8ae9ff2da3c91d0729bf03aee8446) so this will be more avoidable in the future, then we'll close this out.

If an [endpoint is added](https://github.com/hashicorp/consul/issues/9724) for envoy bootstrapping, then we can switch to that and surface that error for an eventual fix.
