### ISSUE TITLE
Add ability to set initial health check status

### ISSUE THREAD

**Issue by rsyabuta** [hashicorp/nomad#1239]
New checks are initially set to "critical" when registered in consul.  It would be nice to have the ability to initially set them to "passing" for certain job types as noted in the consul docs: https://www.consul.io/docs/agent/checks.html.

**Comment by justinwalz** [comment]
We've also noticed this with the `Nomad Client HTTP Check` as clients come online. This ends up triggering alarms based on the failed consul status. Would it be possible to 1) have nomad wait to register itself once healthy or 2) initially set itself as passing (as described above)?

**Comment by dadgar** [comment]
This is available in newer releases: https://www.nomadproject.io/docs/job-specification/service.html#initial_status
