### ISSUE TITLE
Hyphens not allowed in port name when using the nomad api package

### ISSUE THREAD

**Issue by aholyoake-bc** [hashicorp/nomad#12395]
### Nomad version
Nomad v1.1.6 (1da19278dbdb5a356ec7c4f3969194ad5b416824)

Go modules:
```
github.com/hashicorp/nomad v1.1.6
github.com/hashicorp/nomad/api v0.0.0-20220328142823-97dc6875e096
```
### Operating system and Environment details
Debian 10 / MacOS

### Issue
When submitting a job with a dynamic port with hyphens in it directly using the CLI, there is no problem. When parsing using the go library we are presented with
```
Can't parse job file for app sre-test-count-api: error parsing 'job': group: network, ports -\u003e Port label does not conform to naming requirements ^[a-zA-Z0-9_]+$
```
which is a result of this regular expression
https://github.com/hashicorp/nomad/blob/main/jobspec/parse.go#L19

### Reproduction steps

Run the job with `nomad run job.hcl` and then try deserialising it using the nomad api go library.

#### Expected Result
Both setups should allow port labels with hyphens in

#### Actual Result
Only the job submitted with the CLI is successfully submitted to the nomad cluster

### Job file
```
job "sre-test-count-api" {
  region      = "europe"
  datacenters = ["europe-west1"]
  type        = "service"
  group "sre-test-count-api" {
    constraint {
      attribute = "${node.class}"
      value     = "backend-generic"
    }
    network {
      // Exposed Healthcheck ports
      // https://github.com/hashicorp/nomad/issues/7709
      port "healthcheck-sre-test-count-api" {
        to = -1
      }
      mode = "bridge"
      dns {
        servers = ["172.17.0.1"]
      }
    }
    service {
      name = "sre-test-count-api"
      task = "sre-test-count-api"
      port = "9001"
      connect {
        sidecar_service {
        }
      }
      
    }
    task "sre-test-count-api" {
      resources {
        cpu    = 100
        memory = 256
      }

      driver = "docker"
      config {
        image = "hashicorpnomad/counter-api:latest"
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @aholyoake-bc! Can you clarify what you mean by "When parsing using the go library"? Do you mean you're using [`api.ParseHCL`](https://github.com/hashicorp/nomad/blob/v1.1.6/api/jobs.go#L66-L76)?

I just tried doing the following with the jobspec you've provided and it seems to work fine on both Nomad 1.1.6 and `main`:

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"github.com/hashicorp/nomad/api"
)

func main() {

	content, err := ioutil.ReadFile("job.nomad")
	if err != nil {
		log.Fatal(err)
	}

	client, _ := api.NewClient(api.DefaultConfig())
	job, err := client.Jobs().ParseHCL(string(content), false)
	fmt.Println(job)
	fmt.Println(err)
}

```

**Comment by aholyoake-bc** [comment]
Sorry, this was obviously me being lazy. It looks like we're using a deprecated / private endpoint
```
	"github.com/hashicorp/nomad/jobspec"
```
```
	job, err := jobspec.Parse(consulHCLJobReader)
```

**Comment by tgross** [comment]
> I actually don't have an agent / client available to me when I'm running this, so I'm not sure I'm able to use the api package

Yeah, the `github.com/hashicorp/nomad/jobspec` package isn't part of the public API; only the `api` package is. Unfortunately there are plenty of use cases the `api` package can't support, including writing new task drivers! We want at some point to pull out a `sdk` package for the kind of thing you might be doing here, but in the meanwhile we're in this awkward state where you're using internal packages and may need to look at what the rest of the code is doing sometimes.

The `jobspec` package is for HCL1 parsing, and you can see the difference in behavior with `nomad job validate` and the `-hcl1` flag:

```
$ nomad job validate ./job.nomad
Job validation successful

$ nomad job validate -hcl1 ./job.nomad
Error getting job struct: Error parsing job file from ./job.nomad:
error parsing 'job': group: network, ports -> Port label does not conform to naming requirements ^[a-zA-Z0-9_]+$
```

Dashes are allowed in identifiers in the [HCL2 spec](https://github.com/hashicorp/hcl/blob/v2.8.0/hclsyntax/spec.md#identifiers). If I remove the check:

```diff
diff --git a/jobspec/parse_network.go b/jobspec/parse_network.go
index 795f38a3e..4d1b56b80 100644
--- a/jobspec/parse_network.go
+++ b/jobspec/parse_network.go
@@ -86,9 +86,6 @@ func parsePorts(networkObj *ast.ObjectList, nw *api.NetworkResource) error {
                }

                label := port.Keys[0].Token.Value().(string)
-               if !reDynamicPorts.MatchString(label) {
-                       return errPortLabel
-               }
                l := strings.ToLower(label)
                if knownPortLabels[l] {
                        return fmt.Errorf("found a port label collision: %s", label)
```

Then HCL1 parsing works just fine. I did some code archaeology and found this constraint was added all the way back in Nomad 0.2.0 in https://github.com/hashicorp/nomad/commit/87f49c4f7f54e18ca06421a09a835fb0dd07f8ae, but there's no record of why unfortunately. I suspect Consul didn't support dashes in the name at the time or something similar.

In any case, HCL2 is backwards compatible with HCL1 but not all HCL2-valid jobspecs are guaranteed to be backwards compatible with HCL1. So you'll want to use [`jobspec2`](https://github.com/hashicorp/nomad/blob/main/jobspec2/parse.go#L19) for your job parsing needs.

**Comment by aholyoake-bc** [comment]
Thanks Tim, that's very helpful!
