### ISSUE TITLE
nomad server  should members list clients too

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#12441]
### Proposal

On doing `nomad server members`, only the list of `members` in the cluster with role as `server` is listed presently.

Since the nomenclature of the command is `server > members`, the current behaviour is fine, but:

- It would be nice if `members` is made a top level command instead, similar to `consul members`.
- Then, this command can include the list of `clients` inside the cluster, which is helpful.

### Use-cases

I wanted to see a list of clients in my cluster. I am not aware of any CLI command to do this.

### Attempted Solutions

Currently I visited the `/ui/clients` page in UI to find this out. I believe this can be done via an HTTP API also if one needs it programmatically, however for simplicity for cluster operators, a CLI command (which works like how `consul member` works would be nice to have).

**Comment by tgross** [comment]
Hi @mr-karan!

> I wanted to see a list of clients in my cluster. I am not aware of any CLI command to do this.

`nomad node status` gives the list of clients. As you've noticed, `nomad server members` is just for the servers.

**Comment by mr-karan** [comment]
Thanks  @tgross that makes sense.

Feel free to close this.
