### ISSUE TITLE
Documentation: clarify use of 'labels' with dynamic block

### ISSUE THREAD

**Issue by tommyalatalo** [hashicorp/nomad#12681]
### Problem

It's not clear how to use the `labels` argument with HCL2 dynamic blocks when reading the Expressions documentation: https://www.nomadproject.io/docs/job-specification/hcl2/expressions

The docs say that this is optional, but when setting up a  dynamic group for system updates across several nodes like below, the result of a `nomad plan` is `Missing required argument; The argument "labels" is required, but no definition was found.`... but the docs say that the labels are optional.

There needs to be a more complete example for how to use labels, after adding a list of labels I get other errors, each one more confusing than the last since there is no reference to how this should be used.

```
  dynamic "group" {
      for_each = local.targets

      content {
      constraint {
        attribute = "${node.unique.name}"
        value     = group.value
      }

      reschedule {
        attempts  = 0
        unlimited = false
      }

      restart {
        attempts = 0
        mode     = "fail"
      }

      task "update" {
        driver = "raw_exec"
        config {
          command = "/usr/bin/dnf"
          args    = ["update","-y","--security"]
        }
      }
    }
 }
```

**Comment by jrasell** [comment]
Hi @tommyalatalo and thanks for raising this issue. I agree, we should update our documentation to include a more comprehensive dynamic block example.
