### ISSUE TITLE
Sporadic error when loading Job page

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#12724]
### Nomad version

Output from `1.3-beta`

### Operating system and Environment details

MacOS, Firefox

### Issue

When clicking around the UI and into a Job page, occasionally the Job show page throws an error and does not load. Once you reloading the page, it works.

The error displayed (at least when in dev mode):

`Error: Assertion Failed: You made a 'findRecord' request for a 'job' with id '["httpd","prod"]', but the adapter's response did not have any data`

<img width="698" alt="job page error" src="https://user-images.githubusercontent.com/2732204/164341925-4ba98fe5-b7a9-4c03-94c1-61899414763e.png">

### Reproduction steps

Sporadically happening when clicking into a job page from the jobs index.

I will try to find a consistent reproduction and update.

#### Expected Result

The job page loads correctly.

#### Actual Result

The job page fails and throws an error.

**Comment by philrenaud** [comment]
Also noticing this when moving between task groups and allocations.

**Comment by mikenomitch** [comment]
Also, FYI - When I run this with a non-dev build of the UI, the error is "TypeError: t is undefined" in the console, and "Something went wrong." in the UI.

So in case anybody was wondering if these are two distinct errors, they aren't!
