### ISSUE TITLE
Enable setting explicit address on service registrations 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#12722]
One feature request from https://github.com/hashicorp/nomad/issues/12589 is for being able to advertise arbitrary addresses in Nomad services. We can probably do the same for Consul services as well, it's much of the same plumbing.

**Comment by jorgemarey** [comment]
Hi, just to follow on this. Would make sense to allow also setting tagged addresses on services?

Example:

```
    service {
      name = "gateway-mesh-test"
      port = "mesh_wan"

      check {
        name = "gateway-mesh-check-tcp"
        type = "tcp"
        interval = "1m"
        timeout = "15s"
      }

      tagged_addresses {
        wan = "${attr.unique.platform.aws.public-ipv4}:${NOMAD_PORT_mesh_wan}"
      }

      connect {
        gateway {
          mesh {}
          proxy {}
        }
      }
    }
```

**Comment by shoenig** [comment]
I like that idea, @jorgemarey. Do you mind creating a fresh issue so we can track it?

**Comment by jorgemarey** [comment]
Yes, of course. Will also try to make the PR

**Comment by jorgemarey** [comment]
Created in https://github.com/hashicorp/nomad/issues/12950
