### ISSUE TITLE
percentage showing in ui not reflecting in telmetery metrics.

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#12731]
Hello Team,
I am trying to fetch the real-time percentage which is shown in the UI of a nomad in the Prometheus query but I am getting bigger number not sure.
![image](https://user-images.githubusercontent.com/15324013/164469950-ca955f49-30fd-4652-9f69-e390243345f0.png)

Prometheus query:-
`avg((nomad_client_allocs_memory_usage{task="webserver"}-nomad_client_allocs_memory_cache{task="webserver"})/nomad_client_allocs_memory_allocated{task="webserver"} * 100)`

getting output :- **79** instead of **73**
![image](https://user-images.githubusercontent.com/15324013/164470249-12027ea1-14ae-4832-aaec-da45155d61b0.png)

**Comment by thatsk** [comment]
@tgross if you can give some lights on this that would be helpful

**Comment by tgross** [comment]
Hi @thatsk! It looks like the % in the UI is calculated from RSS. See [`allocation-stats-tracker.js#L79-L92`](https://github.com/hashicorp/nomad/blob/v1.2.6/ui/app/utils/classes/allocation-stats-tracker.js#L79-L92). So those prometheus metrics aren't measuring the same thing as the UI and I wouldn't expect them to match up.

**Comment by thatsk** [comment]
Thanks for ref. So is there a way we can calculate same from nomad metrics from Prometheus format which can help for nomad autoscaler to scale the app . Thanks in advance

**Comment by tgross** [comment]
The `nomad.client.allocs.memory.rss` metric is the same metric that's shown in the UI. But your [prometheus](https://www.nomadproject.io/tools/autoscaling/plugins/apm/prometheus) plugin configuration can trigger off of any metric that you'd like. It's up to you to determine what the right metric is to use for your application.

Looks like we've answered the original question though, so I'm going to close this out. Thanks!
