### ISSUE TITLE
Nomad Variables

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#12802]
Nomad will provide **Variables**: an encrypted key-value store to supply workloads with static secrets and configuration data.

Most production Nomad workloads need configuration or secrets. Nomad provides a `template` block to run `consul-template` alongside tasks, but leaves the source of those configuration values up to the operator. Nomad users have several options, but all have disadvantages:
* Vault is the state-of-the-art solution, providing robust security and powerful options like dynamic secrets, transit encryption, etc. But Vault is also complex to learn and deploy.
* Consul KV can be used for storing configuration. If users are already using Consul for service discovery or Connect, there's little additional burden. But Consul KV may not be appropriate for storing secrets.
* Third party tools from cloud providers such as AWS Secrets Manager or Parameter Store don't have good integration with Nomad, and we can't be prescriptive about how they're used.
* Nomad jobspecs can include secrets directly, but these values aren't treated as sensitive by Nomad, and are difficult to rotate if a task is compromised.

Because even very simple applications need secrets, this puts a burden on Nomad operators to also run a Consul and Vault cluster. As with the recent Native Service Discovery feature, we'd like to reduce the cost and complexity of deploying Nomad.

The Variables feature allows users to store secrets at file-like paths in Nomad's state store. The contents of secrets will be encrypted. Users’ access to secrets will be controlled by ACL policies, and workloads will be restricted to have access only to their own secrets. Users will create, read, update, or delete secrets via the command line or in the Nomad web UI.

Future work will allow for interpolating secrets with jobspecs, compare-and-swap primitives for locking, soft deletes, auditing, and more.

**Comment by tgross** [comment]
Variables is ready to ship for Nomad 1.4.0 beta!

**Comment by suikast42** [comment]
I am testing the varibales in nomad version 1.4.cr1 

Is the interplation in job spec implemented in that release ?

**Comment by angrycub** [comment]
Variable interpolation is available via the template block functions in 1.4.0 RC1.  If you should happen to encounter any trouble with it, please let us know via new issues.

**Comment by suikast42** [comment]
> 

Ok I got it.  That works pretty good. 

I found the [blog post](https://www.hashicorp.com/blog/nomad-1-4-adds-nomad-variables-and-updates-service-discovery).

But there are two little bugs.
 env         = trues - >  env         = true
   data        = <<EOH ->    data        = <<EOF
