### ISSUE TITLE
capacity_min in volume definition translates into ceph.quota.max_bytes when using Ceph CSI driver with cephfs

### ISSUE THREAD

**Issue by gregory112** [hashicorp/nomad#12821]
### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)
Ceph CSI v3.5.1

### Operating system and Environment details
Ubuntu 20.04

### Issue
Creating a volume with `capacity_min` will create a CephFS volume but with max bytes quota set to capacity_min.

### Reproduction steps
Deploy Ceph and Ceph CSI plugin `ceph-csi` and create a volume with this definition:

```
id = "test-volume"
name = "test-volume"
type = "csi"
plugin_id = "ceph-csi"
capacity_min = "1G"
capacity_max = "10G"

capability {
  access_mode = "multi-node-multi-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type = "ext4"
  mount_flags = ["noatime"]
}

secrets {
  adminID = "<redacted>"
  adminKey = "<redacted>"
}

parameters {
  clusterID = "<fsid>"
  fsName = "<fs name>"
  mounter = "kernel"
}
```

Create a job that mounts that volume. Fill the volume with data more than 1 GB. You will get an I/O error stating 'disk quota exceeded'.

According to this: [https://docs.ceph.com/en/latest/cephfs/quota/](https://docs.ceph.com/en/latest/cephfs/quota/), CephFS supports the use of quota. It can be retrieved using `getfattr` (install the `attr` package first in Ubuntu), like so:

```
getfattr -n ceph.quota.max_bytes /mount-point
```
To see the attribute I just find the node where Nomad mounts the volume, install `attr` and using `mount` command find where it is mounted in the host. I can then do `getfattr` to see that it does return 1GB:

```
ceph.quota.max_bytes="1000341504"
```

We can probably also do it by executing the command inside the container that mounts it but in my case it was more difficult to install `attr` package there, but the result would probably be the same.

#### Expected Result

Now if capacity_min is removed (I also removed capacity_max) from the volume definition file, the quota is unset and getfattr will complain:

```
ceph.quota.max_bytes: No such attribute
```

I guess the expected result should be max_bytes set to capacity_max and not capacity_min, if they are set.

Thank you.

**Comment by tgross** [comment]
Hi @gregory112! The behavior you're seeing is what I'd expect to see, although I can see how it could be surprising. Ultimately a volume can only have one capacity (ex physical size of a block storage disk, or a quota in the case of CephFS), so `capacity_min` and `capacity_max` are setting _bounds_ on the capacity, and it's up to the plugin to decide what to set the capacity as within that range. If you want to set a specific quota, you should set the `capacity_min` and `capacity_max` to be the same value.

Nomad takes the values for `capacity_min` and `capacity_max` and maps them to `RequiredBytes` and `LimitBytes` for the CSI specification. This happens on the Nomad client (ref [`csi.go#L244-L252`](https://github.com/hashicorp/nomad/blob/v1.2.6/client/structs/csi.go#L244-L252)). The CSI spec on [`CreateVolume`](https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume) says:

```protobuf
// The capacity of the storage space in bytes. To specify an exact size,
// `required_bytes` and `limit_bytes` SHALL be set to the same value. At
// least one of the these fields MUST be specified.
message CapacityRange {
  // Volume MUST be at least this big. This field is OPTIONAL.
  // A value of 0 is equal to an unspecified field value.
  // The value of this field MUST NOT be negative.
  int64 required_bytes = 1;

  // Volume MUST not be bigger than this. This field is OPTIONAL.
  // A value of 0 is equal to an unspecified field value.
  // The value of this field MUST NOT be negative.
  int64 limit_bytes = 2;
}
```

Which we've tried to reflect in our docs on [`capacity_min`](https://www.nomadproject.io/docs/commands/volume/create#capacity_min) and `capacity_max`:

> * `capacity_min` (string: <optional>) - Option for setting the capacity. The volume must be at least this large, in bytes. The storage provider may return a volume that is larger than this value. Accepts human-friendly suffixes such as "100GiB". This field may not be supported by all storage providers.
> * `capacity_max` (string: <optional>) - Option for setting the capacity. The volume must be no more than this large, in bytes. The storage provider may return a volume that is smaller than this value. Accepts human-friendly suffixes such as "100GiB". This field may not be supported by all storage providers.

But I think there's definitely some room to improve the docs here by adding a note that if you want to set a specific capacity that you should set them both to the same value.

**Comment by gregory112** [comment]
Edit: I just got it, well technically you are right, it just picks the smallest size, the capacity min, which is surprising indeed. I guess improvement on documentation could really help.

**Comment by tgross** [comment]
I've opened https://github.com/hashicorp/nomad/pull/12825 with a doc fix. Thanks for opening this issue @gregory112!
