### ISSUE TITLE
Qemu driver port_map doesn't port forward in qemu 

### ISSUE THREAD

**Issue by mvgijssel** [hashicorp/nomad#12833]
### Nomad version
```
❯ nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)
```

### Operating system and Environment details
macOS 12.3 
Ubuntu 20.04.4 LTS

### Issue

I'm currently unable to get qemu driver port forwarding to work, both on macOS and Linux. I'm able to define the `port_map` in the job file, but the settings are not applied to the qemu process.

### Reproduction steps

1. Create `example.nomad` using following template
2. Run using nomad `nomad run example.nomad`
3. Try to SSH to qemu vm using 
  - `ssh localhost -p 2222`
  - `ssh 127.0.0.1 -p 2222`
  - `ssh 192.168.1.15 -p 2222`
 
#### Expected Result

I would expect to be able to connect to the qemu VM using SSH. Looking at https://github.com/hashicorp/nomad/blob/main/drivers/qemu/driver.go#L466-L489 I would expect the qemu process arguments to contain something like `hostfwd=tcp::2222-:22`.

#### Actual Result

Connection refused trying to connect using SSH.

Process argument using `ps aux | grep qemu-` misses the port forward:

**macOS**
```
/usr/local/Cellar/qemu/6.2.0_1/bin/qemu-system-x86_64 -machine type=pc,accel=hvf -name hypervisor.qcow2 -m 1024M -drive file=local/machine.qcow2 -nographic -cdrom local/cidata.iso
```

**Linux**
```
/usr/bin/qemu-system-x86_64 -machine type=pc,accel=kvm -name hypervisor.qcow2 -m 1024M -drive file=local/hypervisor.qcow2 -nographic -cdrom local/cidata.iso -enable-kvm -cpu host
```

### Job file

**example.nomad**
```
job "example" {
  datacenters = ["dc1"]
  type = "service"

  group "test" {
    count = 1

    network {
      port "ssh" {
        static = 2222
      }
    }

    task "virtual" {
      driver = "qemu"

      resources {
        cpu    = 100
        memory = 1024
      }

      config {
        image_path  = "local/machine.qcow2"
        accelerator = "hvf" # or kvm for linux

        port_map {
          ssh = 22
        }

        args = [
          "-cdrom", 
          "local/cidata.iso",
        ]
      }

      artifact {
        source = "http://localhost:8080/machine.qcow2"
      }

      artifact {
        source = "http://localhost:8080/cidata.iso"
      }
    }
  }
}
```

**Comment by mvgijssel** [comment]
The agent configuration being used

```
data_dir  = "/tmp/nomad"

bind_addr = "127.0.0.1"

log_level = "DEBUG"

advertise {
  # Defaults to the first private IP address.
  http = "127.0.0.1"
  rpc  = "127.0.0.1"
  serf = "127.0.0.1"
}

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled       = true
  servers = ["127.0.0.1"]
}
```

**Comment by mvgijssel** [comment]
Just discovered this MR with some changes related to the Qemu driver https://github.com/hashicorp/nomad/pull/10035, which incidentally might solve this.

**Comment by tgross** [comment]
Hi @mvgijssel! This is a bug for sure. We've got https://github.com/hashicorp/nomad/issues/10033 open already, so I'm going to close this as a duplicate. Thanks!
