### ISSUE TITLE
Cannot connect to nomad job (a container, with docker driver) if consul started with multiple private address (docker0) 

### ISSUE THREAD

**Issue by Mandelag** [hashicorp/nomad#12876]
Hi first of all I'm very new to nomad + consul and currently still testing it out...

I've found an issue (but already know how to solve it) and want to report it here.
The issue is, 
 -> cannot connect to docker driver task (container), if there is `docker0` interface (multiple private ip?) when starting consul. 
 -> after solving that (by specifying `-address`), the issue turns to cannot connect to the task (container) from host, it said ~ "no route found to host"
 -> it also causes consul service health check to fail

## Steps to reproduce
My setup is one VM instance 
installed with consul, nomad, and docker.

Let say my IP is 192.168.0.1.

```sh
ip address
# will return 3 interface, local loopback, internal network, docker0 
# since we installed docker (for the docker driver to be enabled in nomad)
# I found this after I've restarted my VM
```

```sh
# this will give error since we have docker0
consul agent -dev -bind 0.0.0.0 -client 192.168.0.1  

# so we can solve it (?) by
consul agent -dev -bind 0.0.0.0 -client 192.168.0.1  -advertise 192.168.0.1

# then we start nomad agent 
nomad agent -dev-connect -consul-address 192.168.0.1:8500 -config /etc/nomad.d/


# then we submit job
# the file attached below
nomad job run redis.nomad

# at this point,
redis-cli -h 192.168.0.1
no route to host

```
...
redis.nomad
```hcl
...
group "redis" {
        network {
            mode = "bridge"
            hostname = "redis"
            port "redis" {
                static = 6379
            }
        }

        service {
            tags = ["redis"]
            port = "redis"
            check {
                type     = "tcp"
                port     = "redis"
                interval = "10s"
                timeout  = "10s"
                check_restart {
                    limit = 3
                    grace = "500s"
                    ignore_warnings = false
                }
            }
        }

        task "redis" {
            driver = "docker"
            config {
                image = "redis:alpine"
                ports = ["redis"]
            }

            resources {
                cpu    = 500 # MHz
                memory = 256 # MB
            }
        }
    }
...

```

I've solved it by 
```sh
# https://stackoverflow.com/questions/40082608/how-to-delete-interface-docker0
ip link delete docker0
```
and re run the step above (by starting consul with one without the `-advertise` flag)

Is this considered a bug or there is something that I miss, but hopefully can help someone who ran both nomad & consul -dev agent  + docker

**Comment by tgross** [comment]
Glad to hear it seems to be working for you @Mandelag. I'm going to close this issue for now but if you end up running into the issue again and can provide `alloc status` outputs for that event, feel free to reopen. Thanks!
