### ISSUE TITLE
task log is hidden/inaccessible/hard-to-find

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#12881]
Steps:
1) Set up a docker job for an image that doesn't exist (presumably other mistakes recreate this situation)
2) Attempt to run job
3) Try to find the real error

The error is hidden under this UI element:
<img width="1191" alt="Allocation_statsd-exporter_statsd-exporter_0__-_Nomad" src="https://user-images.githubusercontent.com/39473/166921449-66bc910c-4b3d-4e18-9381-6ecdadf47ea2.png">

which is this route:
/ui/allocations/4dce572b-6c85-b6b6-acfb-e502a893aa43/statsd-exporter

and it very plainly states: `Failed to pull 'prom/statsd_exporter:v0.22.4'` which is great.  The problem is before I found that I clicked around what I thought was every possible nomad page (and didn't find it) for a solid 10 minutes then ssh'd into the client and tailed /var/log/messages.

**Request:**
Is it possible to make this row more obviously clickable?

**Comment by tgross** [comment]
Hi @josh-m-sharpe! I just tried this out myself and noticed that not only is it not obviously clickable, there's no signaling from hoverstate either. I'll mark this issue for the UI folks to take a look at. Thanks!

**Comment by josh-m-sharpe** [comment]
Oh I def noticed that too.  Thank you!!
