### ISSUE TITLE
Doc page inaccurate regarding task port allocation

### ISSUE THREAD

**Issue by antoineco** [hashicorp/nomad#1292]
##### Nomad version and OS
Nomad v0.4.0-dev ('bc09a0444722617a3a0ee0daa28d24b93d9d3e5b+CHANGES')
Ubuntu 16.04

##### Issue

The procedure to describe port allocations with the Docker task driver seems inaccurate on the related [documentation page](https://github.com/hashicorp/nomad/blob/master/website/source/docs/drivers/docker.html.md#using-the-port-map). The referenced page states something like:
```hcl
task "master" {
    driver = "docker"
    port "http" {}
}
```

which throws the following error:
```
Error parsing job file jenkins.nomad: error parsing 'job': 1 error(s) occurred:
* group: 'jenkins', task: 'master' -> invalid key: port
```

Instead, it seems necessary to wrap `port` allocations within a `resources.network` block, which as a side effect forces the user to set the `mbits` parameter as well:
```
Error validating job: 1 error(s) occurred:
* Task group 1 validation failed: 1 error(s) occurred:
* Task 1 validation failed: 1 error(s) occurred:
* 1 error(s) occurred:
* network resource at index 0 failed: 1 error(s) occurred:
* minimum MBits value is 1; got 0
```

##### Job file

```hcl
job "ci" {
	group "jenkins" {

		task "master" {
			driver = "docker"

			resources {
				network {
					mbits = 100
					port "http" {}
				}
			}

			config {
				image = "jenkins:2.3-alpine"

				port_map {
					http = 8080
				}
			}

			service {
				name = "jenkins"
				tags = ["ci", "master"]
				port = "http"

				check {
					name = "alive"
					type = "tcp"
					interval = "30s"
					timeout = "2s"
				}
			}
		}
	}
}
```

**Comment by dadgar** [comment]
Thanks for reporting!
