### ISSUE TITLE
nomad operator api does not respect scheme in NOMAD_ADDR env var

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/nomad#12923]
### Nomad version

Nomad v1.3.0-rc.1 (31b0a1841cb6d3c7aa64bb2162f50798ba3b3d6e

### Operating system and Environment details

AlmaLinux 8.5

### Issue

The new `nomad operator api` command does not appear to respect the scheme present in the `NOMAD_ADDR` variable when set to `https://`, and sends a plain http request when the parameter given the request path only. When the parameter given is a fully qualified URL (having the shell expand `$NOMAD_ADDR`), then the request is successful

### Reproduction steps

```
$ export NOMAD_ADDR=https://localhost:4646
$ nomad operator api /v1/jobs
Client sent an HTTP request to an HTTPS server.

$ nomad operator api $NOMAD_ADDR/v1/jobs | jq . | head -n 3
[
  {
    "ID": "calibre",
```

#### Expected Result

Scheme should be respected, request should be sent using TLS, and command should print the api call output.

#### Actual Result

Error is raised due to request not being submitted with TLS, and API call is not executed.

### Job file (if appropriate)

N/A

### Nomad Server logs (if appropriate)

N/A

### Nomad Client logs (if appropriate)

N/A

**Comment by tgross** [comment]
Hi @optiz0r! I just verified this works as expected when you have the expected `NOMAD_*` environment variables for the mTLS certificates. The specific error message you get will depend on which variable you're missing. For example:

```
$ export NOMAD_ADDR=https://localhost:4646
$ export NOMAD_CACERT=/my/path/root.crt.pem
$ export NOMAD_CLIENT_CERT=/my/path/cli.crt.pem
$ export NOMAD_CLIENT_KEY=/my/path/cli.key.pem
$ nomad operator api /v1/jobs
[]

$ unset NOMAD_CACERT
$ nomad operator api /v1/jobs
Error performing request: Get "https://localhost:4646/v1/jobs": x509: certificate signed by unknown authority

$ export NOMAD_CACERT=/my/path/root.crt.pem
$ unset NOMAD_CLIENT_CERT
$ nomad operator api /v1/jobs
Error initializing client: Both client cert and client key must be provided

$ unset NOMAD_CLIENT_KEY
$ unset NOMAD_CACERT
$ nomad operator api /v1/jobs
Client sent an HTTP request to an HTTPS server.
```

**Comment by tgross** [comment]
@optiz0r Nomad's CLI only supports mTLS, not server-only TLS. If you're using TLS at all, you need to have the client (CLI) TLS configured as well. Take a look at the [transport security tutoral](https://learn.hashicorp.com/tutorials/nomad/security-enable-tls)

**Comment by optiz0r** [comment]
Hi @tgross,

That's unexpected. How come `nomad operator api ${NOMAD_ADDR}/v1/jobs` works then, if nomad doesn't support server-only TLS? The only difference appears to be whether the URL is provided explicitly on the command line, or via an env var. 

```
ben@whitefall ~> ./nomad operator api https://nomad.service.consul.sihnon.net:4646/v1/jobs
Permission denied
```

(https request was sent as expected. I don't have NOMAD_TOKEN set in my shell, but if I did I would have gotten results like in the first post on this issue).

Since the capability is obviously there, I think it would be really useful if the operator api command respected the scheme.

**Comment by tgross** [comment]
@optiz0r can you drop your entire `env | grep NOMAD_*` (tokens redacted as needed) and the `tls` block for the servers?

**Comment by optiz0r** [comment]
I have no `NOMAD_*` env vars set, except the NOMAD_ADDR one being passed as part of the bash command line shown in my last post.

```
[ben@whitefall ~]$ printenv | grep NOMAD
[ben@whitefall ~]$
```

When I opened the issue, I did have `NOMAD_TOKEN` set appropriately in my environment, I just didn't bother for this re-creation, since it wasn't necessary to demonstrate the behaviour. 

The tls block of the nomad server config is:

```
  "tls": {
    "ca_file": "/etc/pki/nomad/ca.crt",
    "cert_file": "/etc/pki/nomad/server.crt",
    "key_file": "/etc/pki/nomad/server.key",
    "http": true,
    "rpc": true
  },
```

`nomad` commands, e.g. `nomad job run` work with just NOMAD_ADDR and NOMAD_TOKEN set; I do not have any client certificates in use at all.

The `nomad operator api` respects the hostname and port number from `NOMAD_ADDR` but not the scheme when read from env. It respects the scheme, host and port given explicitly as the url parameter. It feels like it should be a very small step to have the env var scheme respected too.

**Comment by chrismo** [comment]
I've run across the same scenario as @optiz0r ... I have a nomad server configured in AWS behind an ALB with an HTTPS cert on it, and all of the nomad CLI works just fine with NOMAD_ADDR set to https://nomad.mydomain.com ... and even `nomad operator api ${NOMAD_ADDR}/v1/jobs` works - but just `nomad operator api -verbose /v1/jobs` shows:

```
> GET http://nomad.mydomain.com/v1/jobs
```

I'm not using any of these vars: NOMAD_CACERT, NOMAD_CLIENT_CERT, NOMAD_CLIENT_KEY.

**Comment by tgross** [comment]
This behavior was fixed by https://github.com/hashicorp/nomad/pull/14635 which is shipping in Nomad 1.4.0. If you have new problems after trying this with Nomad 1.4.0, please open a new issue. Thanks!
