### ISSUE TITLE
Allow setting tagged addresses to services

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#12950]
It would be nice to allow setting tagged addresses on the service registrations. For example:

```
    service {
      name = "gateway-mesh"
      port = "mesh_wan"

      check {
        name = "gateway-mesh-check-tcp"
        type = "tcp"
        interval = "1m"
        timeout = "15s"
      }

      tagged_addresses {
        wan = "${attr.unique.platform.aws.public-ipv4}:${NOMAD_PORT_mesh_wan}"
      }

      connect {
        gateway {
          mesh {}
          proxy {}
        }
      }
    }
```

**Comment by shoenig** [comment]
@DerekStrickland Consul has a distinct concept of `tagged_addresses` that are orthogonal to the `tags` familiar to Nomad

https://www.consul.io/api-docs/agent/service#taggedaddresses

This PR is an extension of https://github.com/hashicorp/nomad/pull/12720 where we enabled setting a custom address on `service.address`, but forgot about Consul's `tagged_addresses`.

**Comment by DerekStrickland** [comment]
@shoenig 

Thanks for that context!

**Comment by lkysow** [comment]
FYI this is needed in some cases for Consul mesh gateway wan federation because Consul uses the wan tagged address to tell other Consul DC's how to reach the local DC. If you throw an LB in front of your gateway then you need to set the tagged address to the LB DNS or IP.
