### ISSUE TITLE
Add config option to avoid task failure on template failure

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#13019]
### Proposal

Currently, when a Nomad task is using a template stanza and that template fails to render because it cannot communicate with an external service, the Nomad agent will retry several times but eventually fail the underlying task. This makes Nomad tasks brittle and can couple Nomad task health to the health of external services like Consul, Vault, or the Nomad Server cluster.

For instance, if Vault goes down for 10 minutes, if Nomad jobs are using secrets in the template stanza, and they retry for 5 minutes, then all of the Nomad tasks for this job will fail. This is particularly bad as the Vault servers might be subject to a thundering herd of Nomad-based requests once they come back up.

Another example is if there are network issues between Nomad clients and servers while Nomad is using native service discovery. If two "edge" clients temporarily lose connection to the Nomad servers, they won't be able to refresh their nomadService information in templates. This should be okay and the clients should continue to run with the data they had on hand. Instead, these edge workloads will be killed. This makes native service discovery very hard to use for edge workloads.

Instead of going down, the Nomad tasks should log warnings, but use stale data. This new configuration value should be added to the [template stanza](https://www.nomadproject.io/docs/job-specification/template) for each task, and configured globally [here](https://www.nomadproject.io/docs/configuration/client#template-parameters) as well.

In the 1.3.X cycle, we should opt in to the new behavior, but we should strongly suggest in the docs & changelog to do so. In 1.4.0, we should switch the default to opt out.

### Use-cases

* Nomad cluster resiliency with Vault
* Nomad cluster resiliency with Consul
* Nomad native service discovery use on flakey/edge connections

**Comment by tgross** [comment]
The existing template runner separates the "first render" behavior from the "steady state" behavior. It might be worth leaving the first render behavior alone (except for #13020's changes) because there's not yet any stale data to use. This means the newly placed task will just hang until the whole deployment gets marked failed. (The allocrunner doesn't currently have a way of handling that behavior gracefully.)
