### ISSUE TITLE
JSON agent logs buffered on startup

### ISSUE THREAD

**Issue by wjordan** [hashicorp/nomad#13015]
### Issue

I recently discovered that the Nomad agent buffers all of its logs on startup until it reaches a certain point in the initialization process: https://github.com/hashicorp/nomad/blob/bab219a8ba38d84cc4641b810339372172ccf00a/command/agent/command.go#L775-L779

This behavior made a recent attempt to debug issues with a slow-loading custom task driver plugin confusing and difficult. I wasn't able to view the logs until after the initialization was completed, and log lines were tagged with incorrect timestamps (reflecting when the buffer was flushed instead of when the log lines were originally recorded).

I couldn't find any mention of this behavior in the documentation, and only figured out what was happening by reading through the source code. (In hindsight, it seems that the `Log data will stream in below` message hints at the buffer being flushed, but this meaning not clear enough from the text alone.)

The original commit introducing this `logGate` / `GatedWriter` (21655765085fad463b25a00fcc6994116b61f3ce) was very early in the project, and there is no commit message or discussion around this behavior, so I still don't understand why this log buffering was implemented in the first place or what purpose it continues to serve. I can't think of any scenario where this kind of buffering behavior would actually be helpful.

Could this buffering behavior be simply removed, or at least made configurable, so that agent logs (including logs generated by task-driver plugins) can be flushed immediately? If there is a reason why this buffering can't or shouldn't be removed, could some additional documentation / comments detailing the reason for this behavior be added to the project?

**Comment by tgross** [comment]
Hi @wjordan! The reasoning behind the buffering is that Nomad's setup involves a bunch of concurrent goroutines all spinning up various bits of work, but the log output is intended to start with the "banner message" once the configuration has been validated. If we didn't buffer, that banner would be interleaved with the rest of the logs.

But obviously that's not a desirable behavior when you're trying to debug the startup itself. It looks like it'd be possible to make this feature configurable in the logging config, as that's read early enough that we could probably set everything up the same way and then just flush the gate right away. I'll mark this for roadmapping, but if you're up for opening a PR for it we'd also be happy to review it I'm sure.

**Comment by wjordan** [comment]
> If we didn't buffer, that banner would be interleaved with the rest of the logs.

Writes to logger implementations are typically protected by mutexes to prevent any such interleaving from occurring. However, one exception is Nomad's use of [`cli`](https://github.com/mitchellh/cli).`BasicUi`, without the [`ConcurrentUi` wrapper](https://github.com/mitchellh/cli/blob/main/ui_concurrent.go) that uses a mutex to make the library concurrency-safe: https://github.com/hashicorp/nomad/blob/be7ec8de3e223e0a944f12274530413ecc723eb0/main.go#L94-L98

Is this the underlying issue you're referring to? In this case, a better solution would be to use the `ConcurrentUi` wrapper to solve the underlying issue of interleaved logs without the undesirable side-effect of having logs buffered on agent startup. I can prepare a PR along these lines if that sounds good.

**Comment by wjordan** [comment]
Ohh, you're not referring to character-level interleaving on an underlying log stream, you're just referring to the ordering of log-lines in the agent startup, which is a very different story.

I was completely confused by what you were saying about the buffering preventing the banner from being interleaved, until I finally discovered through further experimentation that the `log_json = true` setting I have enabled behaves differently from the non-json logging output. Here is what the json log output produces (all of the plugin-setup lines appear before `Nomad agent started`:

```
[...output paused here until agent finishes booting...]

{"@level":"info","@message":"Loaded configuration from [...].hcl","@module":"agent","@timestamp":"2022-05-17T10:04:42.499989-07:00"}
{"@level":"info","@message":"Starting Nomad agent...","@module":"agent","@timestamp":"2022-05-17T10:04:42.500136-07:00"}
{"@level":"info","@message":"detected plugin","@module":"agent","@timestamp":"2022-05-17T10:04:42.502818-07:00","name":"raw_exec","plugin_version":"0.1.0","type":"driver"}
[...]
{"@level":"info","@message":"Nomad agent configuration:\n","@module":"agent","@timestamp":"2022-05-17T10:04:42.566731-07:00"}
[...]
{"@level":"info","@message":"Nomad agent started! Log data will stream in below:\n","@module":"agent","@timestamp":"2022-05-17T10:04:42.566769-07:00"}
```

Here's what the non-json log outputs:
```
==> Loaded configuration from [...].hcl
==> Starting Nomad agent...
[...output paused here until agent finishes booting...]
==> Nomad agent configuration:
[...]
==> Nomad agent started! Log data will stream in below:

    2022-05-17T10:21:03.803-0700 [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    [...]
```

The json case buffers the logs until the agent finishes starting up _and also_ still interleaves the written log lines, so the buffering is doing nothing other than delaying the output.

So one narrow way to fix this issue for json logging would be to just add a `logGate.Flush()` in the same clause that swaps out the UI implementation (which is what causes the logs to be interleaved anyway and makes the buffering useless): https://github.com/hashicorp/nomad/blob/88e8c22b953f0564bb9508db114995d8cbc19e8b/command/agent/command.go#L703-L706

Does this approach sound reasonable?
