### ISSUE TITLE
canary_tags are not shown in ui when instance is canary

### ISSUE THREAD

**Issue by breathe** [hashicorp/nomad#13018]
### Nomad version
Output from `nomad version`

Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

### Operating system and Environment details

aws linux 

### Issue

Spin up a new canary instance with `canary_tags` defined -- I'd expect to see the canary_tags in the ui when navigating to the allocation.

### Reproduction steps

1. spin up canary instance with canary_tags defined2. 
2. navigate to instance deatils in nomad ui3. 
3. observe that tags are shown on page but nothing about the canary_tags

### Expected Result

I'd expect to see the consul `canary_tags` somewhere

#### Actual Result

I see only the regular consul `tags`

### Job file (if appropriate)

```
    service {
      name = "health-check-tool"
      port = "http"

      tags = [
        "traefik.enable=true",
        "traefik.http.services.health_check_tool.loadbalancer.healthcheck.path=/healthCheckAlwaysSuccessTraefik",
        "traefik.http.services.health_check_tool.loadbalancer.healthcheck.interval=10s",
        "traefik.http.routers.deploy_automation_tester.rule=Host(`${var.domain}`)",
        "traefik.http.routers.deploy_automation_tester.tls=true",
        "traefik.http.routers.deploy_automation_tester.entrypoints=https",
        "traefik.http.middlewares.strip_canary_header.headers.customrequestheaders.canary=",
        "traefik.http.routers.deploy_automation_tester.middlewares=strip_canary_header@consulcatalog"
      ]

      canary_tags = [
        "traefik.consulnamesuffix=`canary`",
        "traefik.http.services.health_check_tool_canary.loadbalancer.healthcheck.path=/healthCheckAlwaysSuccessTraefik",
        "traefik.http.services.health_check_tool.loadbalancer.healthcheck.interval=10s",
        "traefik.enable=true",
        "traefik.http.routers.deploy_automation_tester_canary.rule=Host(`${var.domain}`) && Headers(`canary`, `true`)",
        "traefik.http.routers.deploy_automation_tester_canary.tls=true",
        "traefik.http.routers.deploy_automation_tester_canary.entrypoints=https"
      ]

      connect {
        sidecar_service {}
        sidecar_task {
          shutdown_delay = "31s"
          kill_timeout   = "35s"
          resources {
            cpu    = 250 # MHz
            memory = 64  # MB
          }
        }
      }

      check {
        name     = "alive"
        type     = "http"
        path     = "/healthCheckAlwaysSuccessNomad"
        interval = "10s"
        timeout  = "2s"
      }
    }
  }
```

**Comment by DerekStrickland** [comment]
Hi @breathe  Thanks for using Nomad.  Are you saying you used to see these tags and now they don't appear, or are you asking for an enhancement to add them?

**Comment by breathe** [comment]
> Hi @breathe Thanks for using Nomad. Are you saying you used to see these tags and now they don't appear, or are you asking for an enhancement to add them?

I would expect to see the canary_tags shown in the ui on canary instances -- but only the regular non-canary tags are shown.

**Comment by DerekStrickland** [comment]
Thanks for the reply. I will change this from bug to enhancement then since this is maintained in a separate struct field and it doesn't look like the UI ever attempted to show these values.  I'll mark it for roadmap review. I agree it would make a nice quality of life improvement for operators.

**Comment by breathe** [comment]
👍 awesome! That's a nice solution -  thank you!!
