### ISSUE TITLE
UI edit job results in redirect to wrong url to view job

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/nomad#13039]
### Nomad version

Nomad v1.3.0+ent (cb2f0ca3c57391eefcb47cb1150f2688e484a1a8)

(tested in enterprise, but probably behaves the same in oss also)

### Operating system and Environment details

N/A

### Issue

Probably related to #12082 refactoring of URLs for jobs with namespaces. After using UI to edit->plan->run a job, the UI redirects to `/ui/jobs/job?namespace=xx` instead of `ui/jobs/job@namespace`. This then tries to load the job details from the wrong namespace.

The redirect generated at the "run" stage of the UI for job edit needs to be updated to use the new style URLs, or, the ui should respect the `?namespace=xx` parameter in addition to supporting the new `job@namespace` syntax for backward compatibility.

### Reproduction steps

- Edit a job running in a namespace in the UI (ensuring no job with the same name exists in default namespace)
- Plan and run the job
- Observe error page instead of job details

#### Expected Result

After the job is run, UI should redirect back to the correct job.

#### Actual Result

- For a user with no read permissions in the default namespace, this results in a Not Authorized error
- For a user with read permissions in the default namespace, this results in a Not Found error

### Job file (if appropriate)

N/A

### Nomad Server logs (if appropriate)

N/A

### Nomad Client logs (if appropriate)

N/A

**Comment by tgross** [comment]
Thanks for opening this issue @optiz0r! I've flagged it for the UI folks so they can investigate.

**Comment by philrenaud** [comment]
Hi @optiz0r , thanks for raising this issue; we've made a change in #13588 that should fix this, and you should see it in an upcoming release and backported to all nomad 1.3.x versions.
