### ISSUE TITLE
Cannot use dir_mode, file_mode, uid, gid and other smb specific parameters in mount_options

### ISSUE THREAD

**Issue by PinkLolicorn** [hashicorp/nomad#13084]
### Nomad version
Nomad v1.3.0-dev (b5665129cd1fc0a5d5388587685cea74ef09680c+CHANGES)
Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)

### Operating system and Environment details
- Ubuntu 24.02
- [kubernetes-csi/csi-driver-smb](https://github.com/kubernetes-csi/csi-driver-smb)

### Issue

In the search of multi-attach volume I decided to use Samba CSI driver, unfortunately I cannot figure out how to apply `dir_mode`, `file_mode`, `uid`, `gid` which is required to use for third party container or permission denied errors will occur otherwise. I attempted four possible combinations, two resulting in hard error and the other two with seemingly no effects. The `mount_flags` option seemed like the correct one but is throwing some obscure error.

#### Expected Result
> drwxrwxrwx  2 myapp myapp 0 May 20 03:33 mydir

#### Actual Result
> drwxr-xr-x 2 root root    0 May 20 03:33 mydir

### Volume file attempts
```hcl
mount_options {
  fs_type     = "cifs"
  mount_flags = "dir_mode=0777,file_mode=0777,uid=1000,gid=1000,mfsymlinks,cache=strict"
}
```

> Error decoding the volume definition: At 24:17: unknown slice type: *ast.LiteralType

```hcl
mount_options {
  fs_type   = "cifs"
  dir_mode  = 0777
  file_mode = 0777
  uid       = 1000
  gid       = 1000
}
```

> Error decoding the volume definition: 4 errors occurred:
        * invalid key: dir_mode
        * invalid key: file_mode
        * invalid key: uid
        * invalid key: gid

```hcl
parameters {
  dir_mode  = 0777
  file_mode = 0777
  uid       = 1000
  gid       = 1000
}
```

> drwxr-xr-x 2 root root    0 May 20 03:33 mydir

```hcl
secrets {
  username = "xyz"
  password = "xyz"

  dir_mode  = 0777
  file_mode = 0777
  uid       = 1000
  gid       = 1000
}
```

> drwxr-xr-x 2 root root    0 May 20 03:33 mydir

### CSI plugin job

```hcl
job "system-csi-smb" {
  region      = "eu-central"
  datacenters = ["fsn"]
  type        = "system"

  group "plugin" {
    count = 1

    task "node" {
      driver = "docker"

      config {
        image      = "mcr.microsoft.com/k8s/csi/smb-csi:latest"
        privileged = true
        args       = [
          "--endpoint=unix://csi/csi.sock",
          "--nodeid=${attr.unique.hostname}",
          "--logtostderr",
          "-v=5",
        ]
      }

      csi_plugin {
        id        = "smb.csi.k8s.io"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        cpu        = 50
        memory     = 16
        memory_max = 256
      }
    }

    task "controller" {
      driver = "docker"

      config {
        image      = "mcr.microsoft.com/k8s/csi/smb-csi:latest"
        privileged = true
        args       = [
          "--endpoint=unix://csi/csi.sock",
          "--nodeid=${attr.unique.hostname}",
          "--logtostderr",
          "--v=5",
        ]
      }

      csi_plugin {
        id        = "smb.csi.k8s.io"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        cpu        = 50
        memory     = 16
        memory_max = 256
      }
    }
  }
}
```

**Comment by PinkLolicorn** [comment]
> Hi @PinkLolicorn! [`mount_flags`](https://www.nomadproject.io/docs/commands/volume/create#mount_flags) expects a list of strings. So you want something like the following in your volume spec:
> 
> ```terraform
> mount_flags = [
>   "dir_mode=0777", 
>   "file_mode=0777", 
>   "uid=1000", 
>   "gid=1000",
>    "mfsymlinks", 
>   "cache=strict"
> ]
> ```

That makes a ton of sense! Looks like I found partially outdated docs (good hcl example but bad description #13087): https://www.nomadproject.io/docs/commands/volume/register

![image](https://user-images.githubusercontent.com/44551064/169532078-d62a16a0-c8ac-4814-809c-8eb780a940af.png)

It seems like `volume` stanza was updated already:
https://www.nomadproject.io/docs/job-specification/volume

![image](https://user-images.githubusercontent.com/44551064/169532269-288f5db5-6670-46ee-979f-f109d4a023ae.png)

**Comment by tgross** [comment]
Augh, sorry about that! I see the PR you've opened so that'll get merged and fixed shortly. Thanks!

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/13087
