### ISSUE TITLE
Configure new client nodes to be ineligible by default

### ISSUE THREAD

**Issue by wjordan** [hashicorp/nomad#13081]
### Proposal

Add a new `default_ineligible` client configuration that allows new client nodes to be registered as ineligible by default.

### Use-cases

After provisioning servers meant to act as new Nomad Client nodes, it can be helpful to run a few manual checks (occasionally finding bugs in the provisioning process) before allowing new tasks to be scheduled on the new node, and making the newly-created node ineligible by default would simplify this process by preventing any allocations before the node is marked as fully ready.

### Attempted Solutions

There are a couple potential workarounds, each with some slight drawbacks:

- **Don't start the Nomad service at all until the client should be eligible.** This is okay, but removes the Nomad service initialization from the automated provisioning process and prevents us from marking the node eligible through the Nomad API (or CLI/UI) directly, which provides a bit of operational convenience.
- **Use the API (or CLI/UI) to mark the server as ineligible immediately after startup.** Also okay, but leaves open a brief scheduling window so pending tasks might still be immediately scheduled on the node before it gets marked ineligible.

**Comment by jrasell** [comment]
Hi @wjordan and thanks for raising this feature request. This is something that I would certainly like to see added and I believe the community also. https://github.com/hashicorp/nomad/issues/10329 seems like a previous issue requesting the same enhancement. I will therefore mark this as duplicate; please add any +1's or additional comments to the linked issue.
