### ISSUE TITLE
Need for configuration linter

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#13097]
### Proposal

Very recently, I'd burned myself with a bad Nomad agent config stanza and wasted a lot of time trying to get a 3 node cluster. The mistake I did was fairly basic and result of me not RTFM'ing properly:

```hcl
server {
 // ...
}

server_join {
  retry_join = [...]
}
```

The config gets pulled from somewhere, which always had this, but this "bad" config was working on other servers (which resulted in me never actually checking the config properly until a second eye looked at it). Why it worked is because `nomad` was falling back on `consul` for discovering other clients, whereas in this specific cluster we didn't have `consul` (as we were using Nomad 1.3 to try native service discovery features).

### Use-cases

It'll be really good to have a `nomad validate <config.hcl>` command which can return proper errors with exit codes if the config file is invalid. Ideally, `nomad` shouldn't even start if the file is invalid (like `nginx` ?), but maybe to begin with a check and a warning is enough.

**Comment by jrasell** [comment]
Hi @mr-karan and thanks for raising this. We already have https://github.com/hashicorp/nomad/issues/5385 open to track this feature request, therefore I will close this issue as a duplicate. Please add any additional information or thumbs up to the linked issue as this will help prioritisation.
