### ISSUE TITLE
Consider managing deps with something like Godeps

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/nomad#131]
In my attempt to build nomad I had to update the following deps:

```
github.com/fsouza/go-dockerclient
github.com/mitchellh/mapstructure
```

Might be better to manage this with something like Godeps.

**Comment by cbednarski** [comment]
Thanks for the suggestion! Our general philosophy around this is described here https://github.com/hashicorp/terraform/issues/2964

**Comment by peterbourgon** [comment]
The Go universe is coalescing around the GO15VENDOREXPERIMENT method, and early results look promising.

**Comment by kardianos** [comment]
@cbednarski There are several ways to use godep. Primary suggestion is to NOT use godep as a build tool or modifying the GOPATH. Either use godep with import path rewriting or use the vendor folder with GO15VENDOREXPERIMENT=1. 

I would recommend using the vendor folder approach, which godep supports. I think the vendor folder would also fit in with your current workflow reasonably well.

As the author of "govendor" and primary author of go's vendor-spec, I'm trying to understand the best ways to get the word out for go's vendor support, especially now that go1.6 (go tip) has GO15VENDOREXPERIMENT enabled by default. One of the primary benefits of the vendor folder is it has support in the "go" build tool and multiple tools all center around that now. There is potential for the same with "vendor-spec".

**Comment by dadgar** [comment]
Closing as we have yet to decide what we will do and want to wait to see the official vendoring solution brought in Go 1.6

**Comment by kardianos** [comment]
It's the vendor folder. Same as 1.5 under a flag.

**Comment by peterbourgon** [comment]
Strong +1 to just using GO15VENDOREXPERIMENT now.
