### ISSUE TITLE
warn destructive update only when count > 1

### ISSUE THREAD

**Issue by yaroot** [hashicorp/nomad#13116]
### Proposal

Warn destructive update only when count > 1

### Use-cases

Currently nomad cli warns destructive updates for all groups when MaxParallel > task_group.Count, even if the count is 1 or 0. It's more or less the intended behaviour: 1 is always destructive, 0 to deschedule the group.

### Proposed Solutions

I can think of 2 solutions

- compare against current version, warn if the Count has been updated
- disable the warning when `Count < 1` (#13103)

**Comment by jrasell** [comment]
Hi @yaroot that makes sense and thanks for raising a PR. We will get round to reviewing this soon.

**Comment by lgfa29** [comment]
Fixed in #13103, so I'm going to close this one. Thank you once again for the fix @yaroot 🙂
