### ISSUE TITLE
consul/connect: enable setting consul namespace for upstream 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#13121]
In https://github.com/hashicorp/nomad/pull/10235 we added the ability (in nomad-enterprise) to register Consul services via Nomad into non-default Consul namespaces. 

What we didn't do is add the ability to specify to which Consul namespace a Connect service should point at via a Connect upstream.
https://www.nomadproject.io/docs/job-specification/upstreams

Consul upstream docs:
https://www.consul.io/docs/connect/registration/service-registration#upstream-configuration-reference

**Comment by luckymike** [comment]
Can this issue be expanded to support the full set of config options that Consul Connect exposes, e.g. `destination_type`?

**Comment by shoenig** [comment]
Hi @luckymike, I created https://github.com/hashicorp/nomad/issues/13138 for `destination_type` which I can knock out for 1.3.x, and https://github.com/hashicorp/nomad/issues/13139 for supporting admin partitions overall, which is a substantial amount of work that we need to road map.

**Comment by MVJosh** [comment]
Any reason why this was closed? We'd be very interested in seeing this feature implemented

**Comment by tgross** [comment]
@MVJosh as noted by my colleague above, it was split into #13138 and #13139. Please follow those issues if you have interest in the feature.
