### ISSUE TITLE
connect: enable setting destination type in connect upstream 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#13138]
Similar to https://github.com/hashicorp/nomad/issues/13121, add support for setting `destination_type` in a Connect upstream.

**Comment by blake** [comment]
Support for the [`destination_type`](https://developer.hashicorp.com/nomad/docs/job-specification/upstreams#destination_type) argument was added to the `service -> connect -> sidecar_service -> proxy -> upstreams` block in #18430 and released in [Nomad 1.6.2](https://github.com/hashicorp/nomad/releases/tag/v1.6.2).

**Comment by tgross** [comment]
Thanks @blake!
