### ISSUE TITLE
Nomad acl token create should have '-json' option.

### ISSUE THREAD

**Issue by denniseigner** [hashicorp/nomad#13175]
### Proposal

Nomad acl token create (https://www.nomadproject.io/docs/commands/acl/token-create) should have a '-json' option, similar to acl bootstrap command, to format output as JSON string.

### Use-cases

Parsing output from nomad-cli is easier when it is formatted in json.

**Comment by jrasell** [comment]
Hi @denniseigner and thanks for raising this feature request which would certainly be useful!

**Comment by lgfa29** [comment]
Closing this in favour of #15894. Feel free to 👍 and add more comments in that issue. Thank you for the proposal @denniseigner!
