### ISSUE TITLE
allow fingerprinting of classic cpu architecture names

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#13181]
### Proposal
Currently the cpu is fingerprinted using the GOARCH (`amd64`, `arm64`).

Sometimes we need the "traditional" name of the CPU architecture; `i386`, `x86_64`, etc.

This proposal is to allow the Nomad agent to fingerprint the "classic" name for the CPU architecture.

### Use-cases
Software which ship using the classic CPU architecture in their filenames cannot be downloaded using the "inbuilt" variable `${attr.cpu.arch}`.

We need to write custom script (?) code to use `aarch64`, `x86_64` in the download file name depending on `amd64`, `arm64`.

### Attempted Solutions
Currently making do using a custom script and leveraging if/else using the output of `uname -m`

Please note: the name "classic" is what popped into my mind, I am open to any other named being used for this as well.

**Comment by lgfa29** [comment]
Closed by #13182
