### ISSUE TITLE
Tasks with "sidecar = false" and service setup doesn´t get service registered in consul server

### ISSUE THREAD

**Issue by tatototino** [hashicorp/nomad#13203]
### Nomad version
Output from `nomad version`
Nomad v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)

### Operating system and Environment details
Windows 2019 1809

### Issue

I´ve setup a single task with the sidecar - false and a single service script, but the service didn´t´t get registered in consul server.

### Reproduction steps

Setup any service inside a task with sidecard=false and hook=prestart

#### Expected Result

Get the service registered in consul to be available by DNS

#### Actual Result

The service didn´t get registered in consul

**Comment by tgross** [comment]
I'm going to close this issue for now as we don't have the requested information that we'd need to debug. If you do get that info, please feel free to post here and we can re-open the issue. Thanks!
