### ISSUE TITLE
Nomad client resource showing 0 

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#13216]
![image](https://user-images.githubusercontent.com/15324013/171842884-73c00518-f975-4fe5-a650-0ed7dfcd1aea.png)
i am using nomad 1.2.0 and getting resource 0 on client-side and not able to deploy the job from node perspective its working fine.

**Comment by thatsk** [comment]
i am using docker raw_exec and java driver let me know if you need further information,

**Comment by jrasell** [comment]
Hi @thatsk, are you able to provide details of the client CPU, memory, machine type, and the version of cgroups being used?

**Comment by jrasell** [comment]
Hi @thatsk, I am going to close this issue. If you're able to provide the additional information request, please feel free to add this and reopen this issue. I'll pick it back up in this case. Thanks.
