### ISSUE TITLE
APT repo for armhf is behind

### ISSUE THREAD

**Issue by rongcuid** [hashicorp/nomad#13226]
### Nomad version
```
Nomad v0.12.10
```

### Operating system and Environment details

Debian Bullseye, armhf

### Issue

The version of Nomad in the repo is behind. The `arm64` repo contains version `1.3.1`, for instance. Similarly true for Consul.

**Comment by tgross** [comment]
Hi @rongcuid! I think you need to use the package named `arm` for 32-bit builds as of recent versions of Nomad. (Tagging @claire-labry and @lgfa29 on this, as I can't seem to find where the arm7 and armhf Makefile targets got removed from the GNUMakefile)

**Comment by rongcuid** [comment]
@tgross I tried to use `arm` instead of `armhf`, but it does not have the latest version either. Are you referring to the manual install?

Alternatively, is there an APT-Source repository so I can build the deb myself? I can't seem to set up the `deb-src` repo either.

**Comment by tgross** [comment]
> @tgross I tried to use arm instead of armhf, but it does not have the latest version either. Are you referring to the manual install?

No, I was referring to the `arm` repo, but I've got some folks checking on that internally. In the meantime, can you provide the specific apt source you're using?

> Alternatively, is there an APT-Source repository so I can build the deb myself? I can't seem to set up the `deb-src` repo either.

We don't ship an APT-Source repository, only the binary packages (keep in mind some of the packages are not open source, like Nomad Enterprise). You can get the source right from this GitHub repo.

**Comment by rongcuid** [comment]
Currently, I am using:

```
deb [arch=arm] https://apt.releases.hashicorp.com bullseye main
```

**Comment by lgfa29** [comment]
Hi @rongcuid,

could you give us some more details about your environment? Are you running in Raspberry Pi for example? If so, which model.

Thanks!

**Comment by lgfa29** [comment]
@rongcuid I think we found the problem. Would you be able to send us the output of `uname -m` in your environment?

**Comment by rongcuid** [comment]
```
$ uname -m
armv6l
$ dpkg --print-architecture
armhf
```

**Comment by rongcuid** [comment]
It is still not in the repo.

**Comment by lgfa29** [comment]
Hi @rongcuid,

The latest Nomad package is now available in `armhf` builds. Make sure you don't have any `arch` specified in your source file:

```console
root@debian:~# cat /etc/apt/sources.list.d/hashicorp.list
deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bullseye main

root@debian:~# apt search nomad
Sorting... Done
Full Text Search... Done
consul-template/bullseye 0.29.1-1 armhf
  Template rendering, notifier, and supervisor for @hashicorp Consul, Nomad and Vault data.

gnomad2/stable 2.9.6-6 armhf
  Manage a Creative Labs Nomad Jukebox

golang-github-hashicorp-nomad-dev/stable 0.12.10+dfsg1-3 all
  Nomad development libraries

golang-github-sean--seed-dev/stable 0.0~git20170313.e2103e2-3 all
  securely seed Go's random number generator

libnjb-dev/stable 2.2.7~dfsg0-4.1 armhf
  Creative Labs Nomad Jukebox library development files

libnjb-doc/stable 2.2.7~dfsg0-4.1 all
  Creative Labs Nomad Jukebox library documentation

libnjb-tools/stable 2.2.7~dfsg0-4.1 armhf
  Creative Labs Nomad Jukebox library tools

libnjb5/stable 2.2.7~dfsg0-4.1 armhf
  Creative Labs Nomad Jukebox library

nomad/bullseye,now 1.3.2-1 armhf [installed]
  Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.

nomad-driver-lxc/stable 0.3.0-1+b6 armhf
  Nomad LXC driver plugin

nomad-enterprise/bullseye 1.3.2+ent-1 armhf
  Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
```

I'm going to close the issue, but feel free to let us know if it's still not working for you 🙂
