### ISSUE TITLE
auth.ssl should not default to `false`

### ISSUE THREAD

**Issue by timperrett** [hashicorp/nomad#1327]
Docker repositories default to having SSL enabled, and one has to go to many lengths to disable SSL on a docker repository and client. With this in mind, having nomad default to having SSL disabled, seems bizarre? 

Current documentation is here: https://www.nomadproject.io/docs/drivers/docker.html#SSL

**Comment by diptanu** [comment]
Fixed via #1336

**Comment by timperrett** [comment]
@diptanu @dadgar thanks for actioning this so quickly - impressive turnaround!
