### ISSUE TITLE
Nomad Tasks with Restart "delay" should never get into the case of TaskNotRestarting

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/nomad#1328]
The logic https://github.com/hashicorp/nomad/blob/23fc2f89c1c772f358114a4dc75bf8bee873a982/client/restarts.go#L155 that exists for `handleWaitResult` should also be applied to `handleStartError` https://github.com/hashicorp/nomad/blob/23fc2f89c1c772f358114a4dc75bf8bee873a982/client/restarts.go#L134

Also this includes https://github.com/hashicorp/nomad/blob/23fc2f89c1c772f358114a4dc75bf8bee873a982/client/restarts.go#L129 things deemed `ReasonUnrecoverableErrror`. If the policy is set to Restart "delay" instead of "fail" I feel like there should not be anything that is considered `Unrecoverable` unless it is some kind of task definition error.

I am not really able to create a list of unrecoverable errors. Looks like the default for a start error is unrecoverable, and then you specify some as recoverable. Some things that I have seen marked as unrecoverable are 
* unable to find image in registry (`Error while pulling image: Get ******: dial tcp *****: connect: network is unreachable`, certainly recoverable)
* unable to bind to port (again recoverable, especially if it makes it pick a new random port)

**Comment by diptanu** [comment]
@a86c6f7964 Yeah, we could apply the logic of restarting tasks which have exhausted the restart counts within the restart-interval and are failing because of recoverable errors.
