### ISSUE TITLE
[feature] nomad cli list blocked evaluations

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/nomad#1333]
Currently if there is not enough cluster space to place a service job the evaluation goes into a blocked state. If the job is to have multiple service tasks the job itself could have a status of running, but it would just have blocked evaluations. The jobs currently are kind of hard to find, since there status says that everything is running. I had to use the HTTP api and `jq` to find any blocked evaluations.
```
curl -s localhost:4646/v1/evaluations | jq '.[]|select(.Status=="blocked")'
```
It would be nice to be able to identify blocked jobs easier.

**Comment by dadgar** [comment]
So we are going to have a job summary API so you would see that the Job has "Pending" allocations. I think that is better than showing blocked evaluations as that is an implementation detail

**Comment by a86c6f7964** [comment]
ah okay. I see https://github.com/hashicorp/nomad/pull/1218 I guess that is the REST call for the summary. Seems like there already exists `nomad status <JOB_ID>` will that contain more information about pending allocations?

**Comment by dadgar** [comment]
Yeah #1218 was closed because it is going to be implemented in a different way but same goal. Yeah! And potentially when just calling `nomad status` w/o a job

**Comment by a86c6f7964** [comment]
Cool. It would be really nice to be able to call `nomad status` (like you can now) with a prefix and see a summary of all of the jobs that match that prefix (blank prefix meaning everything). Is there a ticket describing any of that functionality that I can weigh in on (and subscribe to) so that I can know when the feature exists. We could close this ticket in favor of that one.

**Comment by dadgar** [comment]
Here you go: https://github.com/hashicorp/nomad/issues/1340
