### ISSUE TITLE
AutoScaling docs are confusing

### ISSUE THREAD

**Issue by Netlims** [hashicorp/nomad#13357]
Hi,

I'm trying to implement AutoScaling on AWS using Nomad and I find the documentation pretty confusing.
For example on the following topic, it's not clear to me where I should define the "target" definition.
https://www.nomadproject.io/tools/autoscaling/plugins/target/aws-asg#agent-configuration-options

It's under "agent configuration" so I guess it should be as part of Nomad agent configuration file (e.g. client.hcl), next to "plugin" and "client" blocks.
But when I do that Nomad fails to run with the following error: "Error loading client.hcl: unexpected keys aws-asg, target”.

I would very help us if the documentation can be clearer on that part.

Thanks

(At this point I still can't manage to set the autoscaling target, so no specific suggestions here)

**Comment by DerekStrickland** [comment]
Hi @Netlims.

Thanks for using Nomad and thanks for posting this here as well as on Discuss. I hope the [examples in the autoscaler demos repo](https://github.com/hashicorp/nomad-autoscaler-demos) get you unstuck. We'll take a look at the docs as soon as we can and see how we can improve the situation.
