### ISSUE TITLE
UI fails to load job when there is @ in job name after job run in nomad 1.3.1-dev

### ISSUE THREAD

**Issue by Davasny** [hashicorp/nomad#13356]
### Nomad version
```
Nomad v1.3.1-dev (19e2e5ce17ec5730138c0dbc7b18d8a23db828f2+CHANGES)
```

### Operating system and Environment details
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Issue
Some time ago I reported issue #12986 which was fixed but on the same version I have problem with planning job via UI. It only ocures when there is `@` sign in job name
![image](https://user-images.githubusercontent.com/25726866/173537341-fb981847-1fc3-4502-9c5b-f55d1f385304.png)

### Reproduction steps
Plan and run nomad job with `@` in name via web ui

#### Expected Result
UI should show normal job status

#### Actual Result
404

### Job file (if appropriate)

```
job "@hello_world" {

  datacenters = ["dc1"]
  type = "service"

  group "app" {
    count = 2

    network {
      port "http" {
        to = 8000
      }
    }


    service {
      name = "webapp"
      tags = ["urlprefix-/", "traefik.enable=true", "traefik.http.routers.http.rule=Path(`/`)"]
      port = "http"

      check {
        name     = "alive"
        type     = "http"
        path     = "/"
        interval = "10s"
        timeout  = "2s"
      }
    }


    restart {
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "fail"
    }

    task "server" {
      driver = "docker"

      config {
        image = "mnomitch/hello_world_server"
        ports = ["http"]
      }

      env {
        MESSAGE = "Hello World!"
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

```
Request URL: https://[redacted]/v1/job/?namespace=hello_world
```

**Comment by DerekStrickland** [comment]
Hi @Davasny 

I'm sorry to hear there are still issues with this use case, but thank you for reporting it!

**Comment by Davasny** [comment]
Hi @philrenaud!

Yes, I can confirm that appending `@default` to the end of url works and fixes the problem

**Comment by philrenaud** [comment]
That's great @Davasny , thanks for letting me know. If there is anyplace in the UI where we're linking to this job without the `@default` / `@<namespace`, please let me know and we will patch that up. Otherwise, I'm going to close this as resolved.

Thanks as always for your contribution to Nomad!
