### ISSUE TITLE
Dispatch payload no longer appears in UI after upgrading from 1.1.4 -> 1.3.1

### ISSUE THREAD

**Issue by kylejmcintyre** [hashicorp/nomad#13360]
### Nomad version
1.3.1

### Operating system and Environment details
Ubuntu 21.04

### Issue

After upgrading from Nomad 1.1.4 -> 1.3.1, the payload box in the UI appears blank whereas it used to contain the input/payload we passed to the dispatch job API:

1.1.4 Behavior
![Screen Shot 2022-06-14 at 10 07 04 AM](https://user-images.githubusercontent.com/4512670/173624387-c533282d-f806-4eda-877f-9bd9f1513540.png)

1.3.1 Behavior
![Screen Shot 2022-06-14 at 10 08 37 AM](https://user-images.githubusercontent.com/4512670/173624648-d41f76ad-3ffc-4caa-8d3f-b1c9176ccc49.png)

As you can see, the payload no longer displays.           

### Reproduction steps

Create a batch/parameterized job definition and invoke it using the dispatch Job API. Then go view the dispatched job beneath the parent job definition.

**Comment by Amier3** [comment]
Hey @kylejmcintyre 

Just letting you know we're aware of this issue and currently working on a fix 👍

**Comment by philrenaud** [comment]
Hi @kylejmcintyre, thanks for raising this issue. The fix in #13473 should bring the Meta and Payload sections back to parameterized child jobs, and is being backported to Nomad 1.3.x releases.

**Comment by kylejmcintyre** [comment]
Thanks! Y'all are top-notch.
