### ISSUE TITLE
[question] Willl Nomad restart a job if the health check of the job fails ? 

### ISSUE THREAD

**Issue by SkyRocknRoll** [hashicorp/nomad#1338]
We use nomad , consul & docker to run our micro services. In each microservice we /status API which gives out 200 if everything works fine otherwise 400. 

Can nomad restart a job if any one of the health check   fails ?

**Comment by dadgar** [comment]
Please prefer the mailing list for questions.

Nomad currently does not restart allocations based on health checks.

**Comment by SkyRocknRoll** [comment]
Thanks! Going forward will use mailing list :)
