### ISSUE TITLE
Secure Variables:  Show warning if duplicate key name is entered in form.

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#13422]
This should not be possible.

![Image](https://user-images.githubusercontent.com/41024828/174392695-94fda26b-25d6-43d5-b4ca-2b254af52d39.png)

**Comment by philrenaud** [comment]
Tackled in https://github.com/hashicorp/nomad/pull/13461/commits/d4b4cb492ae212243cefd3e1a167e6489979dad9
