### ISSUE TITLE
Secure Variables: Handle conflicts on save

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#13420]
Secure variables have a `ModifyIndex` that we expose to the UI. We can use this to inform a user that they're saving a variable that, unbeknownst to them, may have been saved by another user in the time they've had their page open.

There are a few ways this could be tackled:

### UI solution:
- Before attempting to PUT a variable, perform a GET first to see if the modifyIndex of the variable you're about to save matches the one from the server.
- If not, present the user with a notification that there's a conflict, and prompting them to either refresh their page or overwrite anyway

### Server-led solution:
- When a PUT comes in for a variable, and it has a modifyIndex that differs from the payload of the PUT, send back a [409](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) in order to trigger the UI to notify the user / ask if they want to overwrite
- Allow for a `?force=true` header or parameter on PUT that overwrites conflicting variables

cc @angrycub @juliezzhou @mikenomitch @tgross for any suggestions or thoughts on the above ways to handle variable save conflict.

**Comment by mikenomitch** [comment]
Instead of the UI pre-emptively doing a GET before PUT, could we just catch the error from the UI in case of a conflict?

That seems better than a bunch of potentially unnecessary GETs.

**Comment by philrenaud** [comment]
@angrycub I'm not seeing any 409s or similar pop up when I try to save the same variable from competing windows.

Same modify index, different variable keys:

![image](https://user-images.githubusercontent.com/713991/184428533-b8f1a400-f937-4895-9628-a8571688dac0.png)

And return with 200s and different modifyIndexes: 
![image](https://user-images.githubusercontent.com/713991/184428645-9a953f6f-3f44-4bc4-92d1-691ed5be9967.png)


Am I doing something wrong to not see conflict messaging?

**Comment by philrenaud** [comment]
Update: @angrycub very helpfully let me know that I needed a ?cas=<NUM> applied to my PUT in order for this to work. Handling this in https://github.com/hashicorp/nomad/pull/14100

**Comment by philrenaud** [comment]
User gets informed of conflicting variable on save: 
![image](https://user-images.githubusercontent.com/713991/184717838-ee9c762c-8098-46c3-b2b7-1b9a108b4d33.png)
