### ISSUE TITLE
Template - byTag doesn't work for nomadServices

### ISSUE THREAD

**Issue by heapdavid** [hashicorp/nomad#13459]
### Nomad version
`Nomad v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)`

### Operating system and Environment details
Debian 11
### Issue
Firstly, thank you so much for Nomad Service Discovery. I'm trying to create a few small, simple clusters for different projects and it felt like Consul etc was overkill.

I'm looking to create a config file which only includes services which have a specific tag. This was working with Consul using the byTag function. I've tried converting my template stanza from 
```
{{ range $tag, $services := services | byTag }}
```
to
```
{{ range $tag, $services := nomadServices | byTag }}
```

#### Expected Result

Iteration through services and tags as with Consul services

#### Actual Result
```
Template failed: (dynamic): execute: template: :4:42:  executing "" at <byTag>: error calling byTag: byTag: wrong  argument type []*dependency.NomadServicesSnippet
```
### Job file (if appropriate)
The full template section:
```
      template {
        data = <<EOH
{{ range $tag, $services := nomadServices | byTag }}{{ if eq $tag "caddy.enable=true" }}
{{ range $services }}
http://{{ .Name }}-nomad-test.domain.tld {
  reverse_proxy {{ range nomadService .Name }}{{ .Address }}:{{ .Port }} {{ end }}
}
{{ end }}
{{ end }}
{{ end }}
EOH
        destination = "configs/Caddyfile"
        change_mode = "restart"
      }
```

**Comment by shoenig** [comment]
Thanks for reporting @heapdavid! We may have just overlooked this feature when adding Nomad support to `consul-template`.

**Comment by jrasell** [comment]
Hi @heapdavid and apologies on the delay in getting this information out. The `consul-template` dependency was updated as part of the Nomad 1.3.0 release and included the feature that allows this to work. I'll therefore close this issue as complete. If you continue to have problems, please let us know by opening a new issue, or re-opening this one.
