### ISSUE TITLE
Wrong documentation for hcl index function

### ISSUE THREAD

**Issue by wdenbakker** [hashicorp/nomad#13494]
### Nomad version
v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)

### Issue
Documentation for the hcl index function (https://github.com/hashicorp/nomad/blob/main/website/content/docs/job-specification/hcl2/functions/collection/index-fn.mdx) is incorrect. It claims to return the index of an element, but instead returns the element at a index. E.g. `index(["a", "b", "c"], 1)` returns `b` instead of `index(["a", "b", "c"], "b")` returning `1`. See https://pkg.go.dev/github.com/zclconf/go-cty/cty/function/stdlib?utm_source=godoc#Index for the function that is being used.

That being said, a function that does what the documentation currently claims it does would be very useful.

### Reproduction steps
Use `${index(["a", "b", "c"], "b")}` in a job file and run it.

#### Expected Result
Replaces `${index(["a", "b", "c"], "b")}` with `1` in the job.

#### Actual Result
Error in function call; Call to function "index" failed: key for tuple must be number., and 1 other diagnostic(s)

**Comment by jrasell** [comment]
Hi @wdenbakker and thanks for raising this. It does seem both the Nomad and go-cty documentation is incorrect. We will look into fixing this up.
