### ISSUE TITLE
Nomad does not support one-shot jobs

### ISSUE THREAD

**Issue by timperrett** [hashicorp/nomad#1352]
Right now it appears that nomad does not have a way to express the concept of a "one-shot" job. That is, a job that appears on the cluster after submission, does its work, and then goes away forever. There are a range of job-style use cases where this is desirable (for example, running a warmup load generator against a new service deployment, or integration test suite). The fact their is a `periodic` job, implies there is room for something non-periodic too; was this intended / accounted for already?

**Comment by dadgar** [comment]
You can essentially treat batch jobs as one-shot jobs. They will be GC'd after a ~4 hour interval

**Comment by timperrett** [comment]
@dadgar huh. I'm not sure i understand that - can you elaborate a bit more or link to the docs? I had a good look through but didn't notice anything about this. Thanks for the prompt reply!

**Comment by dadgar** [comment]
Sure. So the functionality that you described you would like is achieved with batch jobs. Batch jobs are assumed to be ran to completion, and the scheduler will not reschedule allocations on successful exits. 

Since all jobs garbage collect out of Nomad, if you uniquely name your job, the batch job will run until completion, transition to dead and then be GC'd.

Let me know if I can clarify anything! 

https://www.nomadproject.io/docs/jobspec/schedulers.html

**Comment by timperrett** [comment]
@dadgar We got the part about jobs being removed once terminated; that's an implementation detail for the most part. I think we have answered our own question though: the cron syntax is extended to make use of year, which is not available in a typical unix cron, so one assumes that fully specifying all the fields in the cron expression, we effectively get one-shot jobs. Is that accurate? If so, it would probably be worth updating the docs FWIW, as this was not clear to any of us at this end :-D

**Comment by timperrett** [comment]
@dadgar oh wait, one can just omit the schedule field and it runs immediately - that would make sense.

**Comment by dadgar** [comment]
Ah yes, the `periodic` block is not required! If included it makes your job behave like a cron job.

**Comment by timperrett** [comment]
Thanks for confirmation :-) The docs would certainly benefit from this nugget of information! Cheers

**Comment by dadgar** [comment]
@timperrett 4da45ee4c16a53ce76efb0931458201fdaf301e2
👍
