### ISSUE TITLE
There should be a warning that network_mode = "host" does not work with host_network

### ISSUE THREAD

**Issue by neidiom** [hashicorp/nomad#13543]
I started a Redis docker container that I wanted to run on my private network only

````
      config {
        image = "redis:latest"
        ports = ["redis"]
        command = "/usr/local/bin/redis-server"
        args = ["${NOMAD_ALLOC_DIR}/redis.conf"]
      }
````

````
    network {    
      port "redis" {
        static = 6379
        to = 6379
        host_network = "{{zerotier_network}}"
      }
    }
````

and this work perfectly.

but since I switched my Docker network_mode = "host" stuff stopped working and Redis listens on all interfaces on the host.

There should be a warning, at least a note in the documentation that host_network does not work with         network_mode = "host".

**Comment by DerekStrickland** [comment]
Hi @neidiom,

Thanks for using Nomad and reporting this concern.  If you check out this [documentation](https://www.nomadproject.io/docs/drivers/docker#network_mode), you will find this.

"The default is `bridge` for all operating systems but Windows, which defaults to `nat`. Other networking modes may not work without additional configuration on the host"

I think that speaks to your concern, so I'm going to close this issue. If you disagree, let me know what you think needs improvement.

Thanks!
Derek
