### ISSUE TITLE
Allow specification of a custom job name/prefix for parameterized jobs

### ISSUE THREAD

**Issue by pratheekrebala** [hashicorp/nomad#13594]
### Proposal

Currently, when a parameterized job is dispatched, the jobId of the child job is generated using a fixed template as described here:

https://github.com/hashicorp/nomad/blob/49270ed0013a90ecc5a4ff7e7ede24858372fa30/nomad/structs/structs.go#L5398-L5401

When running many versions of a parameterized job, tracking individual dispatches is hard.

I was wondering if it would be possible to allow specifying a optional "prefix" for an individual dispatch or the ability to specify a child job id as a template in the parent parameterized job. e.g.: `ffmpeg-parameterized/dispatch-{prefix}-uuid`

### Use-cases

This would be helpful when using a parameterized job for multiple different clients or tasks, checking status of jobs either through the UI or through the CLI is difficult. Taking the `ffmpeg` sample task from the docs, this would allow a user to specify which project a specific dispatch might be associated with.

### Attempted Solutions

I am currently using metadata fields to track this but this workflow is hard to use through the CLI and through the UI.

**Comment by tgross** [comment]
Hi @pratheekrebala! Something like this recently came up in an internal discussion and the thing that's somewhat important for a lot of the UX of dispatch jobs is that the names roughly by dispatch time. For small clusters this isn't a big deal but you can imagine that if you had thousands and thousands of dispatches of a job that having the CLI show you an effectively random chunk of them wouldn't be very nice.

That being said, it might be nice as an opt-in feature. It'd have to be a new field in the [`parameterized`](https://www.nomadproject.io/docs/job-specification/parameterized) block. I'll mark this as an enhancement for roadmapping and also a project that might be good for a new contributor who wants to attempt the [jobspec contributing checklist](https://github.com/hashicorp/nomad/blob/main/contributing/checklist-jobspec.md).

**Comment by fumblehool** [comment]
Hi! @tgross 
I've used Nomad and I really Love it!
I would love to work on this if nobody is currently working on this.
Please assign this to me 😄

**Comment by tgross** [comment]
All yours, @fumblehool! Take a look over the contributing guide and once you've made a PR we'll be happy to review it!

**Comment by geovannyAvelar** [comment]
@fumblehool I'm so sorry. I worked on this issue without assignment. I sent a PR yesterday, but don't worry, go ahead and send your PR. You assigned it first so it's all yours.

**Comment by tgross** [comment]
Oops, that happens! How about we review #14631 and maybe pull @fumblehool in for comments if they've already started work?

**Comment by fumblehool** [comment]
No issues @geovannyAvelar.
Fortunately, I was planning to work on the weekend 😅
