### ISSUE TITLE
Nomad schedules work on hosts with docker in a deadlocked state

### ISSUE THREAD

**Issue by gregdurham** [hashicorp/nomad#1359]
### Nomad version

Nomad v0.3.2
### Operating system and Environment details

CentOS Linux release 7.2.1511 (Core)
### Issue

We see that if docker gets into a deadlock state (bug in 1.11.1: https://github.com/docker/docker/issues/22124) nomad continues to attempt to schedule work for these hosts, even so far as causing jobs to be stuck in the pending state waiting to be scheduled on these bad hosts. It seems to me that work should not be scheduled on these and even should pull work to other hosts when in this state. We have since updated our docker to 1.11.2 hopefully resolving this issue. 
### Reproduction steps

Load up a cluster with a good number of tasks and wait, with docker 1.11.0 or 1.11.1.

**Comment by diptanu** [comment]
Thanks for filing the issue. This isn't completely a bug since even in a deadlocked state, if docker responds with the version API call, Nomad will continue to keep the driver in an available state. We will have to modify the fingerprinter take into account the global state across all the spawned up docker drivers in a client.

**Comment by gregdurham** [comment]
Yeah, I think it may be wise to modify that fingerprint, during this issue we were even unable to call `docker ps` due to it hanging.

**Comment by dantoml** [comment]
We now perform much more fingerprinting of the docker driver, validating networks and also pulling client info, which afaik should catch many cases when a docker api is deadlocked. (https://github.com/hashicorp/nomad/blob/a8e9c4aec2d2f272f3a56e682787a9b6e3b27988/drivers/docker/fingerprint.go) 

If this continues to be an issue, please feel free to re-open this issue, or a PR that expands the fingerprint with an API that is definitely broken with bad docker daemons.
