### ISSUE TITLE
consul/connect: enable setting consul namespace for upstream

### ISSUE THREAD

**Issue by MVJosh** [hashicorp/nomad#13611]
As described in #13121, Nomad enterprise doesn't currently provide the ability to specify which Consul namespace a Connect service should point at via a Connect upstream.

Apologies if this is a duplicate, but as far as I can tell no other open issue addresses this specific point.

I believe the previous issue may have been closed by mistake. Several other related issues are referenced, which cover similar but different features:

- #13138 covers setting `destination_type` in connect upstream.
- #13139 covers setting `destination_partition`.
- #13123 covers setting Consul namespace for gateway config entries.

None of the above cover setting `destination_namespace` for _connect upstream_.

**Comment by tgross** [comment]
I'm pretty sure this is entirely covered in the work-to-be done for admin partitions, but that's ok, we'll keep this open.

**Comment by shoenig** [comment]
Yeah sorry @MVJosh, that PR should be in Nomad 1.3.2, which should be shipping in the next few days
