### ISSUE TITLE
Feature Request - artifact {} block at Group level so multiple tasks can access the one artifact file where it is shared

### ISSUE THREAD

**Issue by johnoc2000** [hashicorp/nomad#1368]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:
### Nomad version

0.4.0
### Operating system and Environment details

Windows 10
### Issue

Want to deploy multiple services from one deployment file - If there was an artifact block at group then would not need to download the same file multiple times.

**Comment by momania** [comment]
Can I bump this by adding that even on a job level it would be interesting to be able to specify an artifact.

I have for instance a job with several services divided in some groups, which all use the same logging framework and all use the same log configuration file. 

It would be very nice not having to repeat this artifact for each task definition.

**Comment by nugend** [comment]
Don't know if a further extension is possible or not, but could a hash of the artifacts be taken and actually shared between jobs? We do monolithic deployments (but have individual services within) and it seems a little funny to have to have many copies of the same code on a single node.

**Comment by dadgar** [comment]
@nugend Artifact caching is definitely on the roadmap. However, I would recommend providing the hash of the artifact so that downloads could even be potentially avoided if it exists on the node.

**Comment by nugend** [comment]
@dadgar Sorry, are you saying Nomad is already smart enough to do that? I thought that was just letting the go-getter validate the artifact?

**Comment by dadgar** [comment]
@nugend Nope it doesn't currently do that. The point I was making was for artifact caching to work, Nomad will have to know when it skip downloading the artifact and the hash would allow that.

**Comment by nugend** [comment]
Oh, sure. That's totally reasonable. I just meant that as long as hashes are the same, it's safe to skip storing a duplicate copy.

**Comment by nickethier** [comment]
[Task dependencies](https://www.hashicorp.com/blog/hashicorp-nomad-task-dependencies/), new in 0.11, offer great flexibility in being able to download and manipulate artifacts that can be shared through the alloc directory.

**Comment by fideloper** [comment]
@nickethier Thanks!! 

How would that work exactly? Would one `prestart` task download the artifact and then use it's `config.command` to `mv /local/my-artifact /alloc/data` ?

Something like this?

```
task "artifacts" {
    driver = "docker"

      config {
        image = "something-super-tiny:latest"
        command = "mv"
        args = ["/local/my-artifact", "/alloc/data/"]
      }

    lifecycle {
        hook = "prestart"
        sidebar = false
    }
}

task "main-task" {
    // This would do stuff with the artifact now found in /alloc/data
}
```

**Comment by nickethier** [comment]
Yep! You could even use a template stanza to write out a script to run to make things more readable vs putting it all into the args field.

**Comment by dadgar** [comment]
@fideloper You should also be able to set the destination of the artifact to the `alloc/data` directory so you don't need the move. https://www.nomadproject.io/docs/job-specification/artifact/#destination

**Comment by fideloper** [comment]
That’s be great - I’ll re-test that to make sure but it didn’t seem to work
on 0.11
