### ISSUE TITLE
Consistently sort output of Nomad CLI

### ISSUE THREAD

**Issue by alexiri** [hashicorp/nomad#13711]
### Proposal

The output of `nomad server members` and `nomad node status` is sorted alphabetically by Name, but `nomad operator raft list-peers` does not seem to be sorted, or at least not by Node. I think it would make sense that CLI output is sorted by Name/Node consistently.

### Use-cases

This would make it easier to find a particular node within the output of the CLI.

### Attempted Solutions

`nomad operator raft list-peers | sort` kind of works, but it's not a great solution. :smile:

**Comment by tgross** [comment]
Hi @alexiri! This seems like a nice quality of life improvement that could be added to the formatting code at [`operator_raft_list.go#L85-L97`](https://github.com/hashicorp/nomad/blob/v1.3.2/command/operator_raft_list.go#L85-L97). I'll add this to the roadmap, but I'd also be happy to review a PR if you're interested in giving it a try yourself!

For sake of comparison, here's my local development cluster:

```
$ nomad server members
Name                  Address        Port  Status  Leader  Raft Version  Build      Datacenter  Region
nomad-server0.global  192.168.56.10  4648  alive   false   3             1.3.3-dev  dc1         global
nomad-server1.global  192.168.56.20  4648  alive   true    3             1.3.3-dev  dc1         global
nomad-server2.global  192.168.56.30  4648  alive   false   3             1.3.3-dev  dc1         global

$ nomad operator raft list-peers
Node                  ID                                    Address             State     Voter  RaftProtocol
nomad-server1.global  7590ad0d-ae64-baa9-d5fb-29eb15e02d99  192.168.56.20:4647  leader    true   3
nomad-server0.global  e593252c-cb3c-2ef2-f7d4-5bc5aa84477a  192.168.56.10:4647  follower  true   3
nomad-server2.global  2ad25527-dc71-a8d7-b752-64d0997a275f  192.168.56.30:4647  follower  true   3
```
