### ISSUE TITLE
Global region no longer works in Nomad v0.4.0

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/nomad#1371]
I've just upgraded to 0.4.0 from 0.3.2 but it appears the `global` region no longer works in 0.4.0.

    Error submitting job: Unexpected response code: 500 (No path to region)

I believe this is due to the forwardRegion function which looks up the peers in a region via a map:
https://github.com/hashicorp/nomad/blob/9b6e720fbe5975f82689bc7cba0f1830f470c48a/nomad/rpc.go#L226

Is this a case of an error in the documentation or a backwards incompatible change that I've missed?

**Comment by dadgar** [comment]
Hmm it just worked for me. Can you show the output of `nomad server-members`? A bug was fixed in which we weren't forwarding jobs when submitted from the CLI so I believe it may now be forwarding and you don't have any server in that region

**Comment by grobinson-blockchain** [comment]
Name                            Address     Port  Status  Leader  Protocol  Build  Datacenter    Region
    consul-master-eu-west-1.europe  10.132.0.3  4648  alive   false   2         0.4.0  europe-west1  europe
    consul-master-eu-west-2.europe  10.132.0.4  4648  alive   true    2         0.4.0  europe-west1  europe
    consul-master-eu-west-3.europe  10.132.0.5  4648  alive   false   2         0.4.0  europe-west1  europe

The output from Nomad plan:

    nomad plan /etc/nomad/jobs/charts.hcl
    Error during plan: Unexpected response code: 500 (No path to region)

The logs in `/var/log/syslog`:

    Jun 30 20:41:43 consul-master-eu-west-1 nomad[8274]: 2016/06/30 20:41:43.820677 [WARN] nomad.rpc: RPC request for region 'global', no path found
    Jun 30 20:41:43 consul-master-eu-west-1 nomad[8274]: 2016/06/30 20:41:43 [ERR] http: Request /v1/job/charts/plan?region=global, error: No path to region

The start of the HCL file:

    job "xxx" {
        type = "service"
        region = "global"
        datacenters = ["europe-west1"]

        update {
            stagger = "30s"
            max_parallel = 1
        }

        group "xxx" {

**Comment by dadgar** [comment]
As you can see, all your servers are in the `europe` region. `global` is the default if your server configs do not specify the region, since you did, you will have to update your jobs to target a specific region.

**Comment by grobinson-blockchain** [comment]
@dadgar oh this worked in 0.3.2 - so I was under the impression that if you specified global it would run in any of your regions. Is there a way to make this happen or do you need separate HCL files, each with distinct regions?

**Comment by dadgar** [comment]
Yeah it was a bug that was fixed that we were not properly forwarding regions from the CLI. You will need a separate file for each region. The region is the scheduling domain in Nomad, meaning jobs can not be placed in multiple regions, so jobs must be explicit with what region they are targeting.

**Comment by shantanugadgil** [comment]
Hi, sorry for necromancing this thread, but I am getting this intermittently when dispatching a parameterized job.

I am submitting from my on premise server. The other server is on AWS.
