### ISSUE TITLE
document "Deployments" in the Concepts section

### ISSUE THREAD

**Issue by wimax-grapl** [hashicorp/nomad#13731]
### Proposal

I'd like to see a minimal description of a Deployment on https://www.nomadproject.io/docs/concepts/architecture that compare-contrasts it to, say, an Allocation. 

### Use-cases

My use case is the following: I was trying to reverse-engineer the job-success monitoring that goes on when you `nomad job run`, which was introduced here:
https://github.com/hashicorp/nomad/pull/10661
It relies on the Deployment api, which is not well documented publicly. Or rather, you'll get stuff like ["The /deployment endpoints are used to query for and interact with deployments."](https://www.nomadproject.io/api-docs/deployments), which skirts telling you what concept this represents! 

While it looks like it's a collection of Allocation IDs, I'm genuinely just unsure. 

### Attempted Solutions

this is a documentation request

**Comment by schmichael** [comment]
Great idea! We're hoping to have a little docs sprint soon, and this is on our TODO list.

**Comment by wimax-grapl** [comment]
Glad to hear!

**Comment by tgross** [comment]
Notes from dupe #10581:
> The deployment logic is currently hand-wavy and interactions: canaries, deployment timeouts, node health, etc. Create concept documentation for deployments that contains diagrams showing the state transitions that occur during deployments.

**Comment by tgross** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/14750
