### ISSUE TITLE
Port UI CI tests from Circle into GHA

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#13734]
The UI tests were never ported from Circle to GHA.

These tests need to be migrated to GHA (ideally in a `tests-ui.yaml` config file - independent from `tests-core.yaml`)
https://github.com/hashicorp/nomad/blob/main/.circleci/config.yml#L207

**Comment by tgross** [comment]
Done by @gulducat in https://github.com/hashicorp/nomad/pull/17103
