### ISSUE TITLE
Vagrant build quits with cbednarski/ubuntu-1404 not found

### ISSUE THREAD

**Issue by dimitrovskif** [hashicorp/nomad#1375]
### Nomad version
Using branch aa41a79 (release 0.4.0)

### Operating system and Environment details
* 3.19.0-30-generic #33~14.04.1-Ubuntu x86_64 GNU Linux
* Running Ubuntu Trusty
* Virtualbox 4.3

### Issue

Running `vagrant up` returns:

```bash
Bringing machine 'nomad-server01' up with 'virtualbox' provider...
Bringing machine 'nomad-server02' up with 'virtualbox' provider...
Bringing machine 'nomad-server03' up with 'virtualbox' provider...
Bringing machine 'nomad-client01' up with 'virtualbox' provider...
Bringing machine 'nomad-client02' up with 'virtualbox' provider...
Bringing machine 'nomad-client03' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'cbednarski/ubuntu-1404' could not be found.
```

**Comment by dadgar** [comment]
Are you sure you're machine had internet? 

The box is defined and has not been changed: https://atlas.hashicorp.com/cbednarski/boxes/ubuntu-1404

**Comment by dimitrovskif** [comment]
Updating vagrant fixed the problem. The old version probably did not support atlas boxes.
