### ISSUE TITLE
Documentation of docker driver's hostname key is misleading

### ISSUE THREAD

**Issue by tlaguz** [hashicorp/nomad#13799]
https://www.nomadproject.io/docs/drivers/docker 

> [hostname](https://www.nomadproject.io/docs/drivers/docker#hostname) - (Optional) The hostname to assign to the container. When launching more than one of a task (using count) with this option set, every container the task starts will have the same hostname.

This documentation is misleading. One can create such configuration:
```hcl
  constraint {
    operator  = "distinct_hosts"
    value     = "true"
  }

  group "test" {
    count = 3

    task "test" {
      driver = "docker"

      config {
        .....
        hostname = "${attr.unique.hostname}"
      }
    }
```
and every container will have different hostname: in this case the hostname of its parent node.

Documentation can be understood as if the value of hostname is evaluated once and then used for every task's instance.

**Comment by tgross** [comment]
@tlaguz you're intentionally overriding the behavior with [interpolation](https://www.nomadproject.io/docs/runtime/interpolation), so the behavior is as I'd expect.
