### ISSUE TITLE
[ui] Service Discovery: scaffold /services/:id route (allocations table)

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#13827]
![image](https://user-images.githubusercontent.com/713991/179655193-73cb7ec7-f2df-473b-98de-5b92b8df4062.png)

**Comment by ChaiWithJai** [comment]
Should this be closed? I thought we said that the `services` view won't be implemented for now.

**Comment by philrenaud** [comment]
@ChaiWithJai Yep, still need to do story scaffolding. Blocked by remaining Secure Variables work at the moment.

**Comment by ChaiWithJai** [comment]
OK, no worries! LMK when you plan on doing that story scaffolding.
