### ISSUE TITLE
"nomad server-members" from a client results in 501

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/nomad#1382]
### Nomad version

0.3.2
### Operating system and Environment details

Ubuntu 14.04
### Issue

When I run `nomad server-members` on a server its fine, but when I run it on a client I get the output below:

```
$ nomad server-members
Error querying servers: Unexpected response code: 501 (Invalid method)
```
### Reproduction steps

Run it on a client.
### Nomad Client logs (if appropriate)

```
Jul  2 17:44:22 ip-10-201-101-203 nomad[1313]: http: Request /v1/agent/members, error: Invalid method
```

**Comment by barryw** [comment]
I see this on 0.4.0 as well.

**Comment by SephVelut** [comment]
Also seeing this issue on 0.4.1.

**Comment by vectorhacker** [comment]
I see this on 0.4.1 running on Ubuntu 16.04 x64. Three nomad servers and the client returns 501.

**Comment by vectorhacker** [comment]
Update, nomad clients seem to take jobs just fine, they just can't report the servers they're connected to.

**Comment by yhekma** [comment]
I can confirm this also occurs on debian jessie 64 with nomad 0.4.1

**Comment by dadgar** [comment]
Hey folks we are aware of this issue. Have not yet tackled it. Will update the issue when it is fixed
