### ISSUE TITLE
Allow exec command namespace issue

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/nomad#13833]
Hi there,

When trying to `alloc exec` the namespace must be enforced by default

![image](https://user-images.githubusercontent.com/8832734/179693049-91663e7c-87c8-4abf-8a42-ba2c57361f2b.png)

I'm just posting an image with nomad autoscaler in the default namespace but with you try this command in an another namespace in a CLI, it won't work.
So we should have:
```
nomad alloc exec -namespace default -i -t -task autoscaler a7eb0558 /bin/sh
```
or 
```
nomad alloc exec -namespace anotherNamespace -i -t -task autoscaler a7eb0558 /bin/sh
```

### Nomad version
Output from `Nomad v1.3.2 (bf602974112964e9691729f3f0716ff2bcdb3b44)`

**Comment by angrycub** [comment]
Hey @Lord-Y, I've been looking into this issue and I'm not quite clear on the concern.  The UI demonstrates the command, but with the assumption that your CLI session would have had the NOMAD_NAMESPACE set to match the namespace that it shows in the green area at the top.

Is the issue that the mock nomad exec command in the UI window not copy-and-paste ready for a local terminal session?

**Comment by Lord-Y** [comment]
I can confirm that the actual code is working. I'll close this issue.
