### ISSUE TITLE
nomad fails to determine interface speed on Ubuntu 14.0.3 LTS

### ISSUE THREAD

**Issue by homiak** [hashicorp/nomad#1385]
### Nomad version

Output from `nomad version`
0.4.0
### Operating system and Environment details

Ubuntu LTS 14.0.3
### Issue

Network speed detection fails
### Reproduction steps

Start nomad agent, check the logs 
### Nomad Client logs (if appropriate)

nomad[28018]: fingerprint.network: Unable to parse Speed in output of '/sbin/ethtool eth0'
### Output of the command:

sudo /sbin/ethtool eth0
Settings for eth0:
Link detected: yes

Original question: https://groups.google.com/forum/#!topic/nomad-tool/3TbrUXLaYrI

**Comment by gpaggi** [comment]
@homiak you get to see that error on kvm with virtio-net, which is a para-virtualized driver and doesn't have a link speed. This is the same issue reported for Mesos: https://issues.apache.org/jira/browse/MESOS-4420

**Comment by evan2645** [comment]
same on xenial in ec2 w/ hvm instances, nomad 0.4.1-rc1. master has the same checks so i assume it is also affected. a knob to allow us to define the speed would be a good placeholder for now... are there any suggested workarounds?

**Comment by dadgar** [comment]
Hey Evan,

That knob exists it is network_speed: https://www.nomadproject.io/docs/agent/config.html

**Comment by evan2645** [comment]
sorry, totally missed that

**Comment by dadgar** [comment]
Hey going to close this one since when there is no link speed reported we set a default and allow operators to override. Thanks!
