### ISSUE TITLE
Bug:  Invalid Dates throughout secure variables

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#13853]
Dates are showing up as "Invalid Date" throughout Secure Variables

![Image](https://user-images.githubusercontent.com/41024828/179837209-5870b2b8-b24c-4df1-9d21-48a83ae3a8a9.png)

**Comment by ChaiWithJai** [comment]
[13979](https://github.com/hashicorp/nomad/pull/13979) does not resolve this issue. The issue *I think* lies in the Serializer layer.

**Comment by philrenaud** [comment]
Noting for posterity that this was resolved in #13979
