### ISSUE TITLE
Make distinct_hosts as a variable not working

### ISSUE THREAD

**Issue by panjiang** [hashicorp/nomad#13861]
I want to disable `distinct_hosts` in certain env, but it not working as expected.
- Template
```
job "" {
  constraint {
    operator  = "distinct_hosts"
    value     = var.distinct_hosts
  }
}

variable "distinct_hosts" {
  description = "This job should be scheduled on different hosts"
  type        = string
  default     = "true"
}
```

- Usage
```
distinct_hosts = "false"
```

Then I find the source code, is not reading the value config.

```
func (iter *DistinctHostsIterator) hasDistinctHostsConstraint(constraints []*structs.Constraint) bool {
	for _, con := range constraints {
		if con.Operand == structs.ConstraintDistinctHosts {
			return true
		}
	}

	return false
}
```

**Comment by angrycub** [comment]
@panjiang Thanks for the report. I'm looking into the issue. It appears that in the original jobspec parser in the CLI would filter out cases where the `distinct_hosts` constraint was set to false. This could explain why the feasibility check does not consult the value passed.

However, as you noted, when using jobspec2—the HCL2 version of the jobspec—the value is not being dropped from the parsed JSON and is being incorrectly observed by the feasibility check. This also would appear to impact users who are submitting jobs to the cluster using the JSON-jobspec directly.

I'm still looking into the issue and will add more to the issue as I learn more.
