### ISSUE TITLE
Add officially nfs-csi driver to nomad csi driver plugin list

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#13909]
Hello Team,
https://codeberg.org/in0rdr/nomad-csi-driver-nfs-example
Please add this example as an attachment to support the NFS CSI driver.

**Comment by tgross** [comment]
Hi @thatsk! What are you actually asking for here? Documentation? A section in the `demos/` directory? A Nomad Pack? I'm going to recommend that you submit a PR for whatever you're looking for and we can discuss it there instead.
