### ISSUE TITLE
Incorrect value of NOMAD_HOST_PORT_<label> variable

### ISSUE THREAD

**Issue by ksoftirqd** [hashicorp/nomad#1391]
### Nomad version
Nomad v0.3.2
Ubuntu trusty
docker-engine 1.11.2-0~precise

### Issue
When i try using docker port map feature, both variables NOMAD_PORT_label and NOMAD_HOST_PORT_label within docker container have the same value.

`CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                      NAMES`
`aa1d3bd0d717        redis:latest           "docker-entrypoint.sh"   6 minutes ago       Up 5 minutes        10.1.5.113:20331->6379/tcp, 10.1.5.113:20331->6379/udp   redis-b46241d3-1668-54d6-6667-ce6a4c910d9c`

I expected  NOMAD_PORT_label to be "6379" and NOMAD_HOST_PORT_label to be "20331" in this case. But they all are "6379".

### Reproduction steps

nomad init
nomad run example.nomad

**Comment by Kemicalish** [comment]
I'm getting the same issue but on Nomad v0.4.0 and with a static port instead dynamic one.

static http port is 8010
port_map http port is 8000

and i get 8000 for both NOMAD_PORT_http and NOMAD_HOST_PORT_http.

**Comment by schmichael** [comment]
@Kemicalish This bug was fixed in v0.4.1. Looks like we missed adding it to the changelog, sorry!
