### ISSUE TITLE
[ui] job exec window refresh for jobs in non-default namespaces

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#13921]
### Nomad version
`Nomad v1.3.2 (bf602974112964e9691729f3f0716ff2bcdb3b44)`

### Operating system and Environment details
Ubuntu 22.04 LTS on amd64

### Issue
In the web UI, when refreshing the `Exec` window, it shows a `Not Found` error.

### Reproduction steps
- Open the web UI
- Click `Exec` on an allocation that is in a non-default namespace (important!)
- Refresh the popup (using CMD+R, F5, ...)
- See a nice `Not Found` page.

Notice that F12 / Devtools reports an API request to `/v1/job/my-super-job-name` without the namespace in the URL, resulting in a 404 because that job does not exist in the defualt namespace. 

#### Expected Result
Not a 404. 

#### Actual Result
A 404. 

### Job file (if appropriate)

Any job file with a non-default namespace.

### Nomad Server logs (if appropriate)
Shouldn't be important.

### Nomad Client logs (if appropriate)
Shouldn't be important.

**Comment by tgross** [comment]
Hi @EtienneBruines! I'll flag this issue to get looked at by our UI folks. Thanks!
