### ISSUE TITLE
Support count > 1 for system jobs

### ISSUE THREAD

**Issue by axsuul** [hashicorp/nomad#13936]
### Proposal

Support count > 1  for system jobs so we can always run X number of tasks on each node rather than be limited to just 1.

### Use-cases

 
I use spot instances on Google Cloud and want to always run 2 app servers on these since they only have 2 cores, for example. That makes it easy for me start up more processes by just spawning new spot instances and letting Nomad automatically schedule them. The job would look something like

```terraform
job "rails" {
  type = "system"

  constraint {
    attribute = "${node.class}"
    value = "spot"
  }

  group "rails" {
    # Always keep two processes running per node
    count = 2

    network {
      mode = "bridge"

      port "rails" {
        to = 3000
      }
    }

    service {
      name = "rails"
      port = "3000"

      connect {
        sidecar_service {}
      }
    }

    task "rails" {
      config {
        image = "..."
        ports = ["rails"]
      }
    }
  }
}
```

### Attempted Solutions

I have tried running multiple tasks in a group for a system job but it doesn't appear to work properly for services since only one port gets mapped.

**Comment by tgross** [comment]
@axsuul allocations are the unit of placement, so running multiple tasks in the same group are the way this is typically supposed to work. Can you explain what you mean by "it doesn't appear to work properly for services since only one port gets mapped."? For the job you've shown here, I'd implement that something like the following:

```hcl
ob "rails" {
  type = "system"

  constraint {
    attribute = "${node.class}"
    value = "spot"
  }

  group "rails" {

    network {
      mode = "bridge"

      port "railsA" {
        to = 3000
      }

      port "railsB" {
        to = 3000
      }
    }

    service {
      name = "rails"
      port = "railsA"

      connect {
        sidecar_service {}
      }
    }

    service {
      name = "rails"
      port = "railsB"

      connect {
        sidecar_service {}
      }
    }

    task "railsA" {
      config {
        image = "..."
        ports = ["railsA"]
      }
    }

    task "railsB" {
      config {
        image = "..."
        ports = ["railsB"]
      }
    }


  }
}
```

**Comment by axsuul** [comment]
Thanks @tgross  didn't realize you could have duplicate service names like this. However, I'm having trouble getting this to work with upstreams, for example this is giving me the error `Consul Connect services "rails" and "rails" in group "rails" using same address for upstreams`

```terraform
job "rails" {
  type = "system"

  constraint {
    attribute = "${node.class}"
    value = "spot"
  }

  group "rails" {

    network {
      mode = "bridge"

      port "railsA" {
        to = 3000
      }

      port "railsB" {
        to = 3000
      }
    }

    service {
      name = "rails"
      port = "railsA"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "postgres"
              local_bind_port = 5432
            }
          }
        }
      }
    }

    service {
      name = "rails"
      port = "railsB"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "postgres"
              local_bind_port = 5432
            }
          }
        }
      }
    }

    task "railsA" {
      config {
        image = "..."
        ports = ["railsA"]
      }
    }

    task "railsB" {
      config {
        image = "..."
        ports = ["railsB"]
      }
    }
  }
}
```

Is there a way around this?

**Comment by tgross** [comment]
Those `service` blocks are identical, right? I think you need one for each task?

**Comment by axsuul** [comment]
@tgross Sorry I'm not following. I was mainly going by your example where you have the `service` blocks are the same, just the port is different but I remember recalling that you have to use the hardcoded port number for Consul connect services instead of going by the port alias which is why I have `port = "3000"`. Is that what you're referring to?

**Comment by axsuul** [comment]
Just following up on this, thanks!

**Comment by tgross** [comment]
Hi @axsuul! I was on vacation so I didn't get a chance to follow-up on this. Here's a full jobspec that I've verified runs successfully. Something to note here that because both tasks are in the same group they're in the same network namespace. Therefore, they can't both use the same port inside the namespace.

```hcl
job "rails" {

  datacenters = ["dc1"]

  group "rails" {

    network {
      mode = "bridge"

      port "railsA" {
        to = 3000
      }

      port "railsB" {
        to = 3001
      }
    }

    service {
      name = "rails"
      port = "railsA"

      connect {
        sidecar_service {}
      }
    }

    service {
      name = "rails"
      port = "railsB"

      connect {
        sidecar_service {}
      }
    }

    task "railsA" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "3000", "-h", "/local"]
        ports   = ["railsA"]
      }

      template {
        data        = "<html>hello, world A</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }

    task "railsB" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "3001", "-h", "/local"]
        ports   = ["railsB"]
      }

      template {
        data        = "<html>hello, world B</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }

  }
}

```

**Comment by tgross** [comment]
👋 Haven't heard back on this one in a while and I think it's been answered at this point. Going to close this out.

**Comment by axsuul** [comment]
Thank you Tim, that helped. One other thing to note is that it looks like all upstream ports also need to be unique for Consul Connect.
