### ISSUE TITLE
Bug:  We need to figure out which namespace to check on the `/variables` view to check if a user has access to create a variable at the root level.

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#13949]

**Comment by tgross** [comment]
The symptoms for this look like the `*` namespace constraint is being applied for all views, regardless of depth or whether the namespace selector has been picked. Using the following policy document:

```hcl
namespace "dev" {
  policy = "write"

  secure_variables {
    path   "*" {
      capabilities = ["list", "read", "write", "destroy"]
    }
  }
}

# namespace "*" {
# policy = "read"
#  secure_variables "*" {
#    capabilities = ["list"]
#  }
# }
```

Install this namespace and policy, and create a token for it:

```
nomad namespace apply dev
nomad acl policy apply developer ./developer.hcl
nomad acl token create -name=developer -policy=developer
```

The Variables section won't be available to view at all. If you then uncomment the commented-out section above and run:

```
nomad acl policy apply developer ./developer.hcl
```

The Variables section will be visible for view, but you won't be able to create a variable even if you select the "dev" namespace. I've also tried this having pre-populated the variables via the API and it doesn't look like it's checking against the selected namespace even if I did down into child paths.
