### ISSUE TITLE
Task plugin build issue on Windows

### ISSUE THREAD

**Issue by pnocera** [hashicorp/nomad#13975]
### Nomad version
github.com/hashicorp/nomad v1.3.2

### Operating system and Environment details
Windows 10

### Issue
Build error when trying to build a task plugin on Windows

### Reproduction steps
clone https://github.com/pnocera/nomad-git-plugin

go build

#### Actual Result
build error
```
github.com/hashicorp/nomad/client/lib/fifo
...\github.com\hashicorp\nomad@v1.3.2\client\lib\fifo\fifo_windows.go:98:18: undefined: winio.ListenOnlyPipe
```

https://github.com/hashicorp/nomad/blob/0aef3fc411f5d4f5be6b982447e0d55caf6dda6f/client/lib/fifo/fifo_windows.go#L98

**Comment by shoenig** [comment]
Hi @pnocera, can you try adding a `replace` statement in your go.mod file for `go-winio` like Nomad does?

https://github.com/hashicorp/nomad/blob/main/go.mod#L7

```
replace github.com/Microsoft/go-winio => github.com/endocrimes/go-winio v0.4.13-0.20190628114223-fb47a8b41948
```

**Comment by pnocera** [comment]
Thanks @shoenig it worked.
