### ISSUE TITLE
0.4.0: sloppy vendoring causes FTBFS

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#1397]
Nomad 0.4.0 FTBFS with latest release of Consul (v.0.6.4) because Nomad depends on unreleased snapshot of Consul.
Please coordinate version bump with Consul and vendor only by release tag.

This problem is hindering update of Nomad in [Debian](http://debian.org). :(

See also https://github.com/hashicorp/consul/issues/2000

**Comment by a86c6f7964** [comment]
@onlyjob why does Debian care about internal code build dependencies? the changes that were made in the consul library project were not external API changes, and there is no linked .SO libraries or the such. I have no trouble building 0.4.0 from source because all of the dependencies are explicitly stated in the vendor.js

**Comment by onlyjob** [comment]
> why does Debian care about internal code build dependencies?

Because they are not internal in Debian. We are shipping _reusable_ Golang libraries separately, aiming at stable releases, properly tested on many architectures. In large coherent software repository like Debian's it is not viable to maintain multiple private versions of a library or even simple bugfix would turn into maintenance/backporting nightmare let alone security support.

Arguably vendoring random unreleased snapshot (instead of tagged _stable_ release) is a bad practice that have negative consequences downstream hence I'm suggesting to improve on that.

**Comment by dadgar** [comment]
Hey,

This will be a best effort to vendor tagged releases but we will not delay releases of Nomad by weeks or even months so that we can get a tagged release of one of our dependancies.

**Comment by onlyjob** [comment]
Why would coordination of releases between you own projects would take weeks or months?

Proper vendoring should be done _by tag_ so tools like gopkg.in, getgb.io, gophers, etc. could do their job properly:

 * http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases
 * http://dave.cheney.net/2016/06/26/automatically-fetch-your-projects-dependencies-with-gb

Also please never close bug before addressing the problem: bugs should be closed only once the problem is fixed. FTBFS is still there and closing bug like this smells like denial. :(
