### ISSUE TITLE
[ui] Secure Variables: set up a mirage user with limited Secure Variables permissions

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#14004]
- With lesser path access than the `53cur3-v4r14bl35` mock user
- With some paths having more restricted capabilities, such as list but no write, etc.

**Comment by ChaiWithJai** [comment]
I'd like to pick this ticket up.

**Comment by philrenaud** [comment]
Hey @ChaiWithJai -- this is already tackled as part of the (still in PR) #14020 — https://github.com/hashicorp/nomad/pull/14020/files#diff-9324c2d53e768ef5864ded6a96949549ed255549d8c6446f52bdf01ec3254eaaR73-R109
