### ISSUE TITLE
Nomad doesn't cleanup unix sockets in /tmp when "nomad executor" done

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#1401]
### Nomad version
Nomad v0.4.0

### Operating system and Environment details
Linux ip-172-30-0-126 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Issue
One of our task had errors, so many restarts was be. After fix errors we detect that `/tmp` folder have numerous `plugin*****` files. This is unix domain sockets which was created by nomad, that stay after task creation

**Comment by dadgar** [comment]
Hmm are you sure they are not artifacts of a 0.3.2 version? 0.4 has brought a fix to remove those files and I just tested it and it worked.

**Comment by tantra35** [comment]
Hm, i doeesn't think about this, i will check

**Comment by tantra35** [comment]
Alex you was right, 0.4 cleanup his sockets
