### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [hashicorp/nomad#14024]
### Proposal

Shell completion

### Attempted Solutions

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/nomad/_nomad, it is not quite up to date

If you guys are interested in maintaining it I could PR updated script over, but that would be for zsh only

**Comment by lgfa29** [comment]
Hi @gytis-ivaskevicius 👋 

The `nomad` binary comes with shell completion scripts that can be installed using the [`nomad -autocomplete-install` command](https://www.nomadproject.io/docs/commands#autocomplete). Have you try it, or did you run into issues using it?

**Comment by gytis-ivaskevicius** [comment]
Oh, now that's useful!

Had a bit of an issue due to a lack of .zshrc but it works fine now. Thanks!
