### ISSUE TITLE
Getting started instructions are incorrect for arm64

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#14044]
### Nomad version

```shell
# nomad version
Nomad v0.12.10
```

### Operating system and Environment details

```shell
root@raspberrypi:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@raspberrypi:~# uname -m
aarch64

root@raspberrypi:~# dpkg --print-architecture
arm64
```

### Issue

[Getting started instructions](https://learn.hashicorp.com/tutorials/nomad/get-started-install?in=nomad/get-started) point to amd64 and so installing nomad gets an older version.

### Reproduction steps

1. Install nomad on arm64 as per linux instructions [here](https://learn.hashicorp.com/tutorials/nomad/get-started-install?in=nomad/get-started).
2. Run `nomad version` and get the wrong output.

#### Expected Result

Nomad v1.3.3

#### Actual Result

Nomad v0.12.10

### Job file (if appropriate)

N/A

### Nomad Server logs (if appropriate)

N/A

### Nomad Client logs (if appropriate)

N/A

**Comment by shoenig** [comment]
Thanks for reporting, @josegonzalez!

Just noting this referring to the instructions on https://learn.hashicorp.com/tutorials/nomad/get-started-install?in=nomad/get-started (statically refers to amd64)

... which are different than the downloads page [instructions](https://www.nomadproject.io/downloads?_gl=1*14kto5d*_ga*MTI1MjAwNDE5NS4xNjU5OTY3OTEz*_ga_P7S46ZYEKW*MTY1OTk2NzkxMi4xLjEuMTY1OTk2ODY3Ni4w)

**Comment by shoenig** [comment]
I think these guides are more or less "fixed" by now. The original links are dead (ugh) but the guides that got moved now link to the correct install instructions instead of embedding hard coded instructions.
