### ISSUE TITLE
acl: an ACL token can be created referencing a non-existent ACL policy

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#14058]
### Nomad version
`Nomad v1.3.3 (428b2cd8014c48ee9eae23f02712b7219da16d30)`

### Operating system and Environment details
Tested locally on macOS using a development agent.

### Issue
A Nomad ACL client token can be created referencing a policy that does not exist. This could be a typo or other error which is hard to identify when the create request succeeds without problem. Using the subsequent token results in a permission denied error.

### Reproduction steps
Run a development agent using the following config snippet to ensure ACLs are enabled:
```
acl {
  enabled = true
}
```

Bootstrap the ACL system via the `nomad acl boostrap` command.

Create an ACL token referencing a non-existent ACL policy using the `nomad acl token create -policy=this-doesnt-exist -token=<ROOT_TOKEN>` command.

#### Expected Result
The token creation should fail and explain that the ACL policy does not exist.

#### Actual Result
The token is created successfully.

**Comment by wjnicholson** [comment]
Hi 
> Empty (or absent) policies are treated as a no-op, but allow for policies to be applied to a live token.

This doesn't seem to be the case for event streams. We had a situation with a token with two policies attached, the first with 
```
namespace "will" {
  policy = "write"
}
``` 
and a second with a non-existent policy.

Calling
`curl -vv -sN --header "X-Nomad-Token: ${NOMAD_TOKEN}" "${NOMAD_ADDR}/v1/event/stream?namespace=will&topic=Allocation&topic=Job"`

We expected the call to succeed, but we get back a 500 permission denied error.
Upon recreating a token without the non-existent policy we receive 200 and the event stream.

I believe the code at https://github.com/hashicorp/nomad/blob/main/nomad/stream/event_broker.go#L302 is the issue, in method aclObjFromSnapshotForTokenSecretID. If we cannot find a policy we error eagerly.

**Comment by jrasell** [comment]
Hi @wjnicholson, could you raise this as a separate issue? Although related, the problem you mention seems different from the discussion here and is worthy of its own issue as the behaviour certainly seems wrong.

**Comment by wjnicholson** [comment]
Thanks @jrasell, raised https://github.com/hashicorp/nomad/issues/15493
