### ISSUE TITLE
[ui] TaskGroups and Tasks don't display Variables link.

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#14063]
TaskGroups and Tasks should display a link to Variables when the job is associated to a variable.

This is because `ember-data-model-fragments` don't support relationships. Use the `store` service to query the variable based on `job` and write the conditional logic to check if the job has a parent.

![Image](https://user-images.githubusercontent.com/41024828/183727984-cd0bdabb-b31b-4138-9996-0e7df57ee652.png)

**Comment by philrenaud** [comment]
Just want to verify: this is only buggy when namespaces are present, right? With no namespaces, TaskGroups and Tasks show variables links?

**Comment by philrenaud** [comment]
Resolved in #14072
