### ISSUE TITLE
Nomad fails to reattach containers after restart

### ISSUE THREAD

**Issue by davidsbond** [hashicorp/nomad#14060]
### Nomad version
v1.3.3

### Operating system and Environment details
Linux, arm64

### Issue
I believe I'm experiencing a regression of https://github.com/hashicorp/nomad/issues/5296 in the latest OSS version of nomad. I'm running traefik as a service in my nomad cluster and when I need to perform `systemctl restart nomad.service` I find that nomad is failing to reattach the container and I see failed allocations due to ports already in use. 

To resolve this, I have to access the server directly and kill the traefik instance manually, after this nomad reschedules the container appropriately.

This is running on my homelab, so happy to purposefully break things if it aids in debugging

### Reproduction steps
This seems to not happen 100% of the time I restart a client, but it goes like this:

* Deploy traefik instance with static ports. 
* Restart a client using `systemctl service restart nomad.service`
* When the client starts back up, allocations fail 

#### Expected Result
Nomad reattaches the container of the traefik instance.

#### Actual Result
Nomad does not reattach the container and fails to allocate new instances of traefik

### Job file (if appropriate)
https://github.com/davidsbond/homad/blob/master/terraform/nomad/jobs/networking/traefik.nomad

**Comment by dani** [comment]
Seeing the same behaviour with Nomad 1.3.3 (nodes are AlmaLinux 8.6 with Docker CE 20.10.17). CSI volumes prevents rescheduling (I'm using Linstor CSI). Claims on volumes are lost (most likely because the CSI controllers are restarted too), but as the old tasks are still running, DRBD prevents the resource from being opened again. I have to manually stop the old tasks (with docker stop)

**Comment by tgross** [comment]
Hi folks, yeah this looks like it's most likely related to CSI, as @davidsbond's jobspec has a CSI block. I'm working that problem over in https://github.com/hashicorp/nomad/issues/13028 so I'm going to close this as a dupe. Thanks!
