### ISSUE TITLE
docker: configuration for disabling docker healthchecks 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#14068]
When folks want to run a Docker image that has `HEALTHCHECK` directives baked in the Docker daemon will execute those checks accordingly even though the job-submitter might not want such behavior. 

Expand the docker driver plugin configuration to accept something like `disable_healthchecks`, so that containers are launched with healtchecking disabled. 

Prior art https://github.com/kubernetes/kubernetes/issues/50703

**Comment by mikepea** [comment]
This would be great to see included, we've seen this issue trying to run https://hub.docker.com/r/localstack/localstack as an real world example.
