### ISSUE TITLE
Releases no longer mention Go Version Bumps

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#14126]
### Issue

Nomad releases helpfully used to mention when the Go version changed - this was useful for quickly reproducing any issues one would run into and also for downstream package maintainers of Nomad to know what to use in their packages. Since 1.3.x however, it seems that bumps are no longer mentioned in release notes.

### Reproduction steps

See https://github.com/hashicorp/nomad/releases/tag/v1.3.2, which includes https://github.com/hashicorp/nomad/commit/9fcf933643b30773f0f4112e2ae8dc8c1df33823, but does not mention the bump.

#### Expected Result

Go version bumps are included in changelogs (especially minor bumps)

#### Actual Result

Go version bumps are not included in changelogs

**Comment by jrasell** [comment]
Hi @endocrimes and I agree this is something we should ensure is added to the changelog along with general dependency updates. I will raise a PR to fix the changelog for the most recent releases, and mention this as a reminder internally.

**Comment by endocrimes** [comment]
@jrasell thank you! 💖
