### ISSUE TITLE
website: Wander is missing from Tools list

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#14135]
We added Wander to the [Community Tools list](https://github.com/hashicorp/nomad/pull/13165). However, its currently missing from the static site.

![image](https://user-images.githubusercontent.com/41024828/184927148-15a95610-0793-4f63-8e40-121ec925404f.png)

This could be a bug in how we're reading the `mdx` file because Wander is listed [there](https://github.com/hashicorp/nomad/blob/main/website/content/tools/index.mdx).

**Comment by tgross** [comment]
@lgfa29 I'm going to assign this to you because https://github.com/hashicorp/nomad/pull/13165 was yours. Not sure why it's not showing on the site though. Maybe related to the most recent release?

**Comment by lgfa29** [comment]
I had the backport labels wrong, so the PR didn't land in `release/1.3.x` and `stable-website` was overwritten without it. I found a few more PRs like that and fixed them as well.
