### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by nidhin077** [hashicorp/nomad#14150]
### Nomad version

Nomad v1.3.3 (428b2cd8014c48ee9eae23f02712b7219da16d30)

### Operating system and Environment details
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Issue

I'm trying to run a redis.nomad, but while running the same. The process became stalled after I encountered an error. The error is listed below. I also attempted a different Nomad run, but they all returned the same issue.

* Group "cache" has warnings: 1 error occurred:
	* 1 error occurred:
	* Task "redis": task network resources have been deprecated as of Nomad 0.12.0. Please configure networking via group network block.

### Reproduction steps
Please use the code mentioned in the below link and run the same.

https://github.com/hashicorp/nomad-guides/blob/master/application-deployment/redis/redis.nomad

![image](https://user-images.githubusercontent.com/107123789/185108086-549e7e41-7377-449c-9821-077faeab8086.png)

**Comment by jrasell** [comment]
Hi @nidhin077; could you please provide the job specification your are attempting to run?

It looks like the job specification you are attempting to run includes a [service block](https://www.nomadproject.io/docs/job-specification/service#service-stanza) which is utilising Consul for service discovery, whereas you do not have Consul running to provide this functionality. You could try removing the `service` block or add `provider = nomad ` to it.

**Comment by nidhin077** [comment]
Ok @jrasell, I'm just testing the nomad. Any Docker or Node job files available for sharing?  So I can test the same.

**Comment by jrasell** [comment]
Hi @nidhin077; if you run `nomad job init -short` you will get a job written locally as `example.nomad` which you can use for minimal testing.

**Comment by nidhin077** [comment]
Ok @jrasell

**Comment by jrasell** [comment]
Hi @nidhin077, I will go ahead and close this issue. If you feel you come across another bug, please feel free to open another ticket.
