### ISSUE TITLE
nomad address override does not take user:pass in address string

### ISSUE THREAD

**Issue by olenm** [hashicorp/nomad#1415]
### Nomad version
Nomad v0.4.0

### Operating system and Environment details
mac 10.11.5

### Issue
we use nomad with an nginx front-end with basic auth and nomad address override does not work with basic auth as presumed with a url address input
(kind of relates to https://github.com/hashicorp/nomad/issues/227)

### Reproduction steps
nomad status -address="https://user:pass@example.com" 

```
Error querying jobs: Unexpected response code: 401 (<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
)

```

**Comment by diptanu** [comment]
@olenm We are going to support end to end TLS between Nomad server, client and the cli which should secure the Nomad cluster.

**Comment by diptanu** [comment]
The end to end TLS is going to land in a month so I am closing this ticket. Please let me know if that would solve your use-case?

**Comment by olenm** [comment]
If the TLS implementation includes basic auth in the address-url-param (and/or as env-vars) that would be perfect. (I built locally and am using it as a work around for the time being)
Thanks for the update!

**Comment by BSick7** [comment]
@diptanu This was set to land. Any updates as to whether it will be included in 0.4.1?

**Comment by dadgar** [comment]
@BSick7 waiting for @olenm to update the PR based on feedback

**Comment by BSick7** [comment]
@dadgar sorry, I should have been more specific. I was referring to this comment.

> The end to end TLS is going to land in a month so I am closing this ticket. Please let me know if that would solve your use-case?

**Comment by dadgar** [comment]
@BSick7 Ah! That was never planned for 0.4.x. It will be coming in 0.5.x 👍

**Comment by BSick7** [comment]
Thanks!

**Comment by mlafeldt** [comment]
FYI: https://github.com/hashicorp/nomad/pull/1431, which adds support for -address="https://user:pass@example.com" is already part of 0.4.0.
