### ISSUE TITLE
Constraints operator "is not", "not" and "!=" doesn't work as expected with missing meta tags

### ISSUE THREAD

**Issue by mclate** [hashicorp/nomad#1419]
### Nomad version

`Nomad v0.4.0`
### Operating system and Environment details

Ubuntu 140.4, docker 1.11.2
### Issue

Consider having some nodes with meta `"router" = true` and some that doesn't have that tag.

Having constraints that look like this:

``` json
        "Constraints": [
            {
                "LTarget": "${meta.router}",
                "Operand": "is not",
                "RTarget": "1"
            }
        ]
```

won't start task on any node, while it is expected to be started on nodes that don't have `router = true` meta tag.

Here is nomad task output (i'm having 2 nodes with that tag set and 10 without it and want to start two instances in task group):

```
Task Group "admin":
  * Constraint "${meta.router} is not 1" filtered 8 nodes
  * Constraint "computed class ineligible" filtered 4 nodes
```
### Expected behavior

Nomad should handle missing meta tags and do matching for `is not`, `not` and `!=` against `None` (or `undefined`)

**Comment by mclate** [comment]
Any word on this one?

BTW, in documentation it says `Operator` ([json](https://www.nomadproject.io/docs/jobspec/json.html#Operator), [hcl](https://www.nomadproject.io/docs/jobspec/index.html#operator)), while nomad actually expects `Operand` to be passed.

**Comment by diptanu** [comment]
@mclate I believe we fixed the documentation bug.

**Comment by dadgar** [comment]
What would the behavior be if you did 
```
 {
                "LTarget": "${meta.router}",
                "Operand": "==",
                "RTarget": "${meta.other}"
            }
```

Where neither are defined on the node? I think there are a lot of cases where the behavior is not clear if we support this.

**Comment by dadgar** [comment]
Closing for the mentioned undefined behavior

**Comment by mclate** [comment]
`  * Constraint "${meta.router} == ${meta.other}" filtered 7 nodes`
And no allocations were created.

I'm not quite follow what "undefined behavior" this would lead to. Wouldn't it be the same behaviour as running task with no constraints only for nodes that don't have meta tag i've mentioned?

So, right now, if i don't provide any constraints, task will run on any node. I'm able to say "run only on these nodes", but how would i say "run on any nodes other than these" (without requirement to specify all possible tags on all nodes)? 

Also it's not quite clear what's the difference between `is` and `==` as well as `is not` and `!=`. Looks like they do pretty much the same.

Wonder if it would make sense to use `==`/`!=` for strict matching (where `${meta.key} != 2` would only match nodes that do have `key` and `key` doesn't equal to `2`)  and `is`/`is not` to be used for scenario i've described (where for `is not` we don't care about key presence)

**Comment by dadgar** [comment]
Yeah I understand now. Reopening

**Comment by mclate** [comment]
Guys, am i right assuming that this issue didn't appear in latest release (v.0.5.0)?

**Comment by dadgar** [comment]
@mclate Correct it still hasn't been resolved. I am tentatively going to mark this for 0.6.0

**Comment by marcosnils** [comment]
@dadgar @mclate this hasn't been resolved yet I assume?. Just hit the same issue and I'm force to add a tag to all my nodes so nomad doesn't exclude all of them when using a `!=` operator.

**Comment by dadgar** [comment]
@marcosnils Sorry still hasn't been resolved.
