### ISSUE TITLE
Namespace parameter missing in api documentation for stop job

### ISSUE THREAD

**Issue by dantheoptimist** [hashicorp/nomad#14197]
The api docs for stop job do not reference the namespace parameter https://www.nomadproject.io/api-docs/jobs#stop-a-job

There's a bit of a suggestion from the ACL being at the namespace level, but for clarity and to save time for future users of this API it is probably worth explicitly documenting the namespace parameter for this endpoint.

**Comment by jrasell** [comment]
Hi @dantheoptimist and thanks for raising this issue. I'd agree and also raise that this should also apply to a number of other job API endpoints. I'll take a look into fixing these up.

**Comment by robsonj** [comment]
I just ran into this one also
