### ISSUE TITLE
allow promotion from within 'job run' monitoring

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#14214]
While debugging a community issue (https://github.com/hashicorp/nomad/issues/14200) I noticed that if you `nomad job run` a job with a manual canary promotion, the job monitor will hang because it's awaiting manual promotion. So then you have to open another terminal window, configure your CLI to point to the cluster again, and promote the deployment. It'd be nice if we could do that all in the same workflow.

Example update block:

```hcl
  update {
    max_parallel      = 1
    min_healthy_time  = "30s"
    auto_promote      = false
    canary            = 1
  }
```

Resulting CLI experience, currently:

```
$ nomad job run ./jobs/update-slow.nomad
==> 2022-08-22T11:44:06-04:00: Monitoring evaluation "fe1a5a94"
    2022-08-22T11:44:06-04:00: Evaluation triggered by job "example"
    2022-08-22T11:44:07-04:00: Evaluation within deployment: "1e5e445c"
    2022-08-22T11:44:07-04:00: Allocation "557c3e81" created: node "f63232c1", group "web"
    2022-08-22T11:44:07-04:00: Evaluation status changed: "pending" -> "complete"
==> 2022-08-22T11:44:07-04:00: Evaluation "fe1a5a94" finished with status "complete"
==> 2022-08-22T11:44:07-04:00: Monitoring deployment "1e5e445c"
  ⠏ Deployment "1e5e445c" in progress...

    2022-08-22T11:44:43-04:00
    ID          = 1e5e445c
    Job ID      = example
    Job Version = 1
    Status      = running
    Description = Deployment is running but requires manual promotion

    Deployed
    Task Group  Promoted  Desired  Canaries  Placed  Healthy  Unhealthy  Progress Deadline
    web         false     3        1         1       1        0          2022-08-22T15:54:37Z
```

**Comment by jaybrueder** [comment]
This is a problem I have encountered as well. Would be great if the `run` just finishes, and we could promote the deployment later. Currently, a CI pipeline is triggering the `run`and is then stuck in a loop until someone either runs the `promote` command in a local terminal window OR clicks the promote button in the UI.

We are using `auto_promote` to get around this and therefore lose the advantages of testing the new deployment before it goes live if we don't want to have forever-running CI pipelines.

**Comment by lgfa29** [comment]
Closing this in favour of #15156.

After some internal discussions we agreed that it would be best if:

1. `nomad job run` stops monitoring the deployment when a manual promotion is required.
2. `nomad job run` outputs a message noting the canaries health status and the command users can run to promote them.
3. Command return code will be `0` unless an error happens.
