### ISSUE TITLE
Cross Region Job scheduling

### ISSUE THREAD

**Issue by jshaw86** [hashicorp/nomad#1424]
We would like to be able to schedule in a single request across multiple regions. See the below job spec for an example.

```
{
"Job" : { 
             "Region": ["region1","region2"],
             "ID": 1,
             "Name": 1,
             "Type": "service",
             "Priority": 50,
             "AllAtOnce": False,
             "Datacenters": ["dc1","dc2"],
             "TaskGroups": [
                   { "Name": "event_handler_1",
                     "Count": 3,
                     "Constraints": None,
                     "Tasks": [ { "Name": "event_handler",
                                         "Driver": "exec",
                                         "User": "",
                                         "Config": { "command": "/usr/bin/start.sh" },
                                         "Constraints": None,
                                         "Env": { "HOME": "/usr/lib/service1" },
                                         "Services": [ { "Id": "",
                                                                 "Name": "service1",
                                                                 "Tags": tags,
                                                                 "PortLabel": "http",
                                                                 "Checks": [] } ]
                                       } ]
             }]
           ....
         }
}
```

**Comment by a86c6f7964** [comment]
if there are multiple nomad servers across regions and datacenters do they do raft consensus with each other? I know that in the consul docs, consul only does gossip eventual consistency across datacenters, but I couldn't find anything in the docs for nomad.

**Comment by jshaw86** [comment]
@a86c6f7964 per a conversation I had with @dadgar on irc this is currently not possible. This can be simulated through multiple requests but you would have to make 1 request per region to nomad.

Raft doesn't do cross region consensus, the general rule is single quorum(nomad server cluster) per region, however nomad allows you to define your region however you like. For example if you were to take us-west and us-east in ec2 regions. You may setup a single quorum in us-west that decides for nomad clients in **both** us-west and us-east, **or** you may setup a quorum in us-west that decides for nomad clients in us-west and setup a quorum in us-east that decides for nomad clients in us-east. Furthermore via nomad federation, in the second setup you may request from us-west quorum to schedule something in us-east but the us-west quorum doesn't decide anything in terms of scheduling just acts as a proxy e.g. no raft across region.

**Comment by a86c6f7964** [comment]
Okay. That's what I thought. Seems like there is still a bunch of work for
nomad to talk across quorums then until something like this ticket can be
solved. Or like you said have one quorum run all regions/data centers but
that seems non ideal. I would think that a solution like consuls gossiping
across quorums would be better.

**Comment by margueritepd** [comment]
@jshaw86 Can you please re-open this issue? I have the same request!

**Comment by jshaw86** [comment]
@margueritepd the nomad guys did an onsite with us and explained this was something they weren't going to do so I closed it.

I think there logic was that there federation protocol is stateless (basically a glorified proxy) and this would be adding state.

Ping @dadgar or @schmichael if you want to advocate your case ... I tried :).

**Comment by margueritepd** [comment]
@jshaw86 okie dokie thanks for the explanation!
