### ISSUE TITLE
CPU stats are misleading

### ISSUE THREAD

**Issue by mclate** [hashicorp/nomad#1426]
### Nomad version

`Nomad v.0.4.0`
### Issue

Please correct me if i'm wrong here. When calling any stats endpoints (such as `/v1/client/stats`) it will give you _current_ CPU utilization. While it can give you generic view of what's happening, it can lead to incorrect reading. Here is an example: say, my app was heaviliy using cpu for last 7 seconds and than went idle for next three. If i do readings every 10 seconds, i may see that my app is idling, while in fact it isn't. It just happened so that i polled stats at the wrong time.

The better approach (taken from docker) would be to report number of cpu cycles passed and number of cpu cycles that were used by my application (as two incremental counters). By doing simple math between two measurements one can easily find out how many resources were used by the application at any given time frame.

**Comment by diptanu** [comment]
Hi, we collect stats every second and calculate CPU percentages every time we collect stats, if you can poll the client every second you will get the right stats. Nomad isn't collecting stats only when the stats endpoint is hit, it's continuously collecting data points and you get the last collected data point when you hit the stats end point. Also, you could simply point Nomad client to a statsd server and nomad will report all the stats it is collecting.

If you want to poll at a higher rate for example at `10s` interval, you could ask Nomad client to collect stats at `10s` interval too in which case the cpu percentage calculation would take into consideration that interval and you will get the right result. Look at the `Client Metrics` section here https://www.nomadproject.io/docs/agent/telemetry.html for the configuration key.

Does that help?

**Comment by mclate** [comment]
Hi. Your first statement is exactly what i've described. If i poll data with intervals bigger than one second i'll get misleading information as i will get stats only for *last collected data frame*.

Another issue here is that with this approach i must poll data for all containers with the same interval. This makes impossible to separate more important services from less important ones. So, for some service i might need performance reporting with high granularity (like every second), while for another even 1min intervals would be sufficient. Having only last second will not work. Neither will changing collecting interval that you've mentioned, as it is applied for whole node and not for a specific allocation.
This is also true in case of pushing data to statsd. They'll be pushed every 10 seconds which might be too slow in one case and too much in another.

But the main concern here would be that *last collected data point*.
