### ISSUE TITLE
Java Corretto 17 not detected on Nomad

### ISSUE THREAD

**Issue by vladaman** [hashicorp/nomad#14275]
Fresh install of Nomad did not detect java environment on ubuntu 22.04.

```
java -version
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS, mixed mode, sharing)
```

```
$ nomad version
Nomad v1.3.3 (428b2cd8014c48ee9eae23f02712b7219da16d30)
```

Steps to reproduce:
```
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" --yes
sudo apt-get update && sudo apt-get install nomad
wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.deb
sudo dpkg -i amazon-corretto-17-x64-linux-jdk.deb 
```

**Comment by shoenig** [comment]
Hi @vladaman, can you find out where the `java` command is actually being installed? It might not be included in the default `chroot` if it's being installed somewhere atypical.

I pasted that version output into our java version parser tester `TestDriver_parseJavaVersionOutput` and it seems to work okay.

**Comment by vladaman** [comment]
@shoenig the issue was that nomad was not running under root. Figure it out.
