### ISSUE TITLE
Connection Issue 

### ISSUE THREAD

**Issue by nidhin077** [hashicorp/nomad#14280]
### Nomad version
Nomad v1.3.3 (428b2cd8014c48ee9eae23f02712b7219da16d30)

### Operating system and Environment details
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Issue

I'm attempting to connect a server to Nomad, and I've added the server information to both the client.hcl and server.hcl files. I'm getting an error when I run the command below.

```
------------------------
Error updating server list: Put "http://127.0.0.1:4646/v1/agent/servers?address=10.10.10.15%3A4647": dial tcp 127.0.0.1:4646: connect: connection refused
------------------------
------------------------
Error joining: failed joining: 1 error occurred:
	* Failed to join 10.10.20.114:4648: dial tcp 10.10.20.114:4648: connect: connection refused

------------------------
```

Could you please take a look and let me know, how to connect servers to nomad or how to resolve the same?

**Comment by tgross** [comment]
Hi @nidhin077! 

> I'm getting an error when I run the command below.

I've wrapped the output you provided in a code block for clarity, but you haven't actually said what command you're running. That looks like the logs from a server agent? You'll need to provide your server configuration and logs for us to be able to diagnose further.

**Comment by nidhin077** [comment]
The below command was used to connect the server
nomad node config -update-server 3.83.84.111:4647

I'm actually having trouble connecting the servers, so if you could explain how to do it, that would be helpful.

**Comment by tgross** [comment]
You'll need to provide your server configuration and logs for us to be able to diagnose further.

**Comment by nidhin077** [comment]
Hi @tgross 

This is the server configuration I've been using.

server.hcl 
------------------
server {
  enabled          = true
  bootstrap_expect = 3
}

server {
    server_join {
      retry_join = ["10.10.20.114"]

  }
}



nomad.hcl 
---------------------
# Full configuration options can be found at https://www.nomadproject.io/docs/configuration

data_dir  = "/opt/nomad/data"
bind_addr = "0.0.0.0"

server {
  # license_path is required as of Nomad v1.1.1+
  #license_path = "/opt/nomad/license.hclic"
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled = true
  servers = ["127.0.0.1"]
}

server {

  enabled          = true

  bootstrap_expect = 3



  # This is the IP address of the first server provisioned

  server_join {

    retry_join = ["10.10.20.114:4648"]

  }

}

Please advise me on how to obtain the Nomad's connection log.

**Comment by tgross** [comment]
@nidhin077 you've got what looks like 3 different configurations here and they're mashed together in a way that I can't tell which piece is what without guessing. Help us help you by wrapping your configs in code blocks. 

> Please advise me on how to obtain the Nomad's connection log.

Server and client logs for Nomad will be found in the journal, like every other log on the system.

**Comment by tgross** [comment]
We haven't heard back on this issue with more information, so I'm going to close it out. But if you have the information requested we'll be happy to reopen. Thanks!
