### ISSUE TITLE
no ARM binary?

### ISSUE THREAD

**Issue by nicolai86** [hashicorp/nomad#1430]
The build script explicitly disables the linux/arm target and there are no prebuild arm binary available, even though golang supports (cross-)compilation.

Hashicorp offers ARM binaries eg for consul.
What's stopping us from providing an ARM binary for nomad, too?

Would love to know the reasons and ideally fix this; also, directly compiling on an ARM device produces a working nomad binary, so I'm not sure why they are not available pre-build…

**Comment by diptanu** [comment]
@nicolai86 We could definitely release binaries for the arm platform for supported OSes. I know that we can build the linux binary on arm, but it would need some testing.

**Comment by ranjib** [comment]
set GOARCH to arm and you should be good. I run nomad on raspberry pi 2/3 without any issues.

**Comment by nicolai86** [comment]
@ranjib I can confirm that the binaries seem to work at least supervisial. Compiled v0.4.0 myself and the consul self-bootstrapping worked just fine. Which brought me to my original question :)

**Comment by nicolai86** [comment]
If there's something which needs testing let me know I'd be glad to help out.

**Comment by mongrelion** [comment]
@nicolai86 good initiative. I think having the project compiling under an ARM arch. is a good starting point. I think the next step would be to run the test suite and see if anything comes up.
See the [Developing Nomad](https://github.com/hashicorp/nomad#developing-nomad) section for info on how to do it.

Good luck!

**Comment by nicolai86** [comment]
@mongrelion the current version runs great on ARM. Tested with Scaleway C1 servers - details here https://github.com/nicolai86/scaleway-terraform-demo

I'll take a stab at an automated ARM testrunner within the next week so it's more transparent that ARM works.

**Comment by nicolai86** [comment]
It seems that `make tests` requires a local consul setup:
[nomad.log.txt](https://github.com/hashicorp/nomad/files/383135/nomad.log.txt)

I'm assuming that's why the tests fail. will try again later today to verify…

**Comment by mongrelion** [comment]
@nicolai86 thanks again for looking into this. I'm not familiar with running the tests for Nomad but two things that you should make sure:
1. That you're on the right tag/branch (`0.4.0` sounds reasonable to you?).
2. Check out the [TravisCI config file](https://github.com/hashicorp/nomad/blob/v0.4.0/.travis.yml). There are some tasks that need to be ran before you run the tests. Source of the Makefile [here](https://github.com/hashicorp/nomad/blob/v0.4.0/GNUmakefile)

**Comment by nicolai86** [comment]
Got a working setup /w terraform & scaleway, but 6 errors ATM:

```
--- FAIL: TestTaskRunner_Download_List (27.70s)
--- FAIL: TestJavaDriver_Start_Wait (55.67s)
--- FAIL: TestTaskRunner_Download_List (27.70s)  
--- FAIL: TestTaskRunner_Update (39.21s)
--- FAIL: TestTaskRunner_SimpleRun (27.58s)
--- FAIL: TestTaskRunner_Destroy (29.49s)
```

as far as I understand the logs it seems simple timeout errors -> machine not beefy enough. Looks like `make test` runs some compilation under the hood and a `C1` trips the timeouts. Will report back once I know more…

**Comment by nicolai86** [comment]
Hm, just saw that some tests must fail on ARM since they rely on x86 only tests - e.g. https://github.com/hashicorp/nomad/blob/91a5304d5926f23e299a759e0380120cafde8d85/client/driver/docker_test.go#L55

I think we need to have build tags for this platform e.g. to run the corresponding tests with ARM compatible docker images… probably step 1 on the ARM roadmap . let's see if I can make a PR out of this…

**Comment by nicolai86** [comment]
for the interested, a complete automated testrun for v0.4.0 takes ~1h10m on Scaleway.
Here's a buildlog including all errors:
[out.log.zip](https://github.com/hashicorp/nomad/files/400348/out.log.zip)

**Comment by mongrelion** [comment]
Good progress. Also, sucks that the tests take so long to run on ARM. Maybe you can use qemu or something to try in your local machine? 😃

**Comment by nicolai86** [comment]
just found this: https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

will see if I can use this to run compilation & tests on docker without real ARM hardware... :)

**Comment by diptanu** [comment]
Closing this issue, since we have published an arm binary for Nomad 0.4.1-rc1. Can someone please give it a spin? https://releases.hashicorp.com/nomad/0.4.1-rc1/nomad_0.4.1-rc1_linux_arm.zip

**Comment by nicolai86** [comment]
@diptanu cool! Will give it a spin!

**Comment by ns-cweber** [comment]
It looks like you guys dropped ARM support between [0.5.0-rc1](https://releases.hashicorp.com/nomad/0.5.2-rc1/) and 0.5.2](https://releases.hashicorp.com/nomad/0.5.2/). Is this intentional? I Googled around, but I couldn't find any information; just this page. Please advise.

**Comment by diptanu** [comment]
We didn't drop ARM support, I wasn't able to build it in time for the release. The next release is going to have an ARM binary.

**Comment by mongrelion** [comment]
@diptanu would it be a good idea to automate the creation of the dist files from within TravisCI?
