### ISSUE TITLE
Vault-Nomad-Consul Integration Refinement

### ISSUE THREAD

**Issue by stevenheinze57** [hashicorp/nomad#14328]
Is there a way to integrate Nomad with both Consul and Vault in a way where there is no need for a CONSUL_TOKEN or VAULT_TOKEN. I would then solely need to get my Nomad authentication from the [vault_nomad_secret_role](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/nomad_secret_role) configured in Vault. 

The main reason I am asking this is because looking through a plethora of docs, it seems that even though we can setup Nomad vault approle integration to create tokens for each job submission, there is no way to limit the scope per job/group/task. In a sense, I could give my job all vault policies available, provide it the correct vault token, and there would be no way to prevent my job from getting higher vault access. Both consul and vault tokens seem to act as overrides. 

I imagine there could be some [nomad terraform resources](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs/resources/acl_token) or tokens that have scoped vault policy access. These could then be injected into the job based on job/group/task name... That would prevent any operator or job-submitter from breaking/overriding the job scoped access with any vault or consul token. 

And please correct me if I'm wrong here, I may be getting lost in the weeds with integrating all three services the way I want.

**Comment by tgross** [comment]
Hi @stevenheinze57! 

For Vault, I think you can get most of what you're looking for with the [`vault.create_from_role`](https://www.nomadproject.io/docs/configuration/vault#create_from_role) configuration combined with setting [`vault.policies`](https://www.nomadproject.io/docs/job-specification/vault#policies) on the jobs. If you configure a minimally permissioned role and then add policies to the job to extend that role, you should be able to avoid passing `VAULT_TOKEN` when you submit jobs.

We don't have anything equivalent of that for Consul today.

Something that may interest you is the recently-merged [Workload Identity](https://github.com/hashicorp/nomad/blob/main/website/content/docs/concepts/workload-identity.mdx) concept. In the upcoming Nomad 1.4.0 these signed identities won't be available for anything outside of `template` blocks accessing Nomad variables (see also https://github.com/hashicorp/consul-template/pull/1632). But, without promising any particular roadmap or timeline, we definitely intend to expand these uses in future versions of Nomad.

**Comment by tgross** [comment]
Doing some issue cleanup and I think this one has been answered. I'm going to close it out but please feel free to add additional context and we can reopen if necessary. Thanks!
