### ISSUE TITLE
Consul link in Nomad UI missing after updating to Nomad v1.3.4

### ISSUE THREAD

**Issue by heikkilamarko** [hashicorp/nomad#14331]
### Nomad version

Nomad v1.3.4

### Operating system and Environment details

Microsoft Windows Server 2019 Standard

### Issue

Consul link in Nomad UI top bar is missing after updating to Nomad v1.3.4.

![Screenshot 2022-08-26 at 9 42 22](https://user-images.githubusercontent.com/3757314/186839743-a81e91f4-a454-4e4b-91b4-915b62409b0c.png)

Agent config:

```hcl
ui {
    enabled = true

    consul {
        ui_url = "http://localhost:8500/ui"
    }
}
```

**Comment by tgross** [comment]
Hi @heikkilamarko! I can confirm that I can see the Consul link on Nomad 1.3.3 but not on Nomad 1.3.4. I'll flag this for our UI folks @philrenaud and @ChaiWithJai for triage. Thanks!

**Comment by heikkilamarko** [comment]
For a temporary workaround to this issue, see: https://github.com/hashicorp/nomad/issues/14359#issuecomment-1229115136

**Comment by lgfa29** [comment]
Hi @heikkilamarko 👋 

I have confirmed that this is being cause by the same issue as #14359. Those JavaScript errors prevent the Nomad UI from rendering the custom links.

As I mentioned in that issue, we're planning on having a release with the fix out today so I'm going to close this for now to keep the discussion focused in #14359.

Thank you for the report 🙂
