### ISSUE TITLE
how to run helm charts in nomad?

### ISSUE THREAD

**Issue by unnimona** [hashicorp/nomad#14360]
i want to run helm charts with nomad
i installed nomad and helm charts but helm charts is not detecting nomad nor connecting to it.
please provide command to connect helm charts with nomad 

helm ls -A
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by iluminae** [comment]
helm is kubernetes only. _however_ a very similar technology is called [nomad-pack](https://learn.hashicorp.com/tutorials/nomad/nomad-pack-intro).

**Comment by tgross** [comment]
Hi @unnimona! As @iluminae has mentioned, Helm is for Kubernetes, and Nomad is not in any way based-on or compatible-with Kubernetes. You should definitely check out Nomad Pack!
