### ISSUE TITLE
-hcl1 should imply -hcl2-strict=false

### ISSUE THREAD

**Issue by michalgm** [hashicorp/nomad#14384]
### Nomad version
Nomad v1.3.4+ent

### Operating system and Environment details
Debian 11

### Issue
When running any command that takes the `-hcl1` option, I get this error: 
```
gmichalec@gmichalec:~/work/levantservice$ nomad plan -hcl1 -verbose /tmp/20220829121756/nomad.hcl.final
Invalid job options: cannot parse job file as HCLv1 and HCLv2 strict.
```
the workaround is to include `-hcl2-strict=false`, but this seems redundant and also will break our tooling if not all clients are updated to the nomad version that accepts the `-hcl2-strict` flag.

**Comment by lgfa29** [comment]
Hi @michalgm 👋 

Thanks for the report and I think it makes sense, since this is a required combination of flags.
