### ISSUE TITLE
Add purge button to web ui

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#14411]
### Proposal

It would be great to add the purge button to the web ui, next to the start/stop buttons on the jobs page.

### Use-cases

This would allow for quickly purging a job without needing to find the correct incantation on the cli to perform the action.

### Attempted Solutions

I can do this via the cli, but I would like to provide alternatives to those not as familiar with the cli.

**Comment by jrasell** [comment]
Hi @josegonzalez, this sounds like a really useful idea, thanks for raising the issue.

**Comment by mikenomitch** [comment]
Adding an idea: I think it would make sense in the context of the UI to only show this if the Job is already stopped.

This would add an extra step in purging a job versus purging from the CLI (stop then purge), but it would help avoid accidental purges of jobs.

Also, this would definitely require a confirmation step.
