### ISSUE TITLE
Add client name tooltip to allocation view

### ISSUE THREAD

**Issue by gmichalec-pandora** [hashicorp/nomad#14421]
### Proposal
The new client name tooltips when hovering over the client_id in the allocations tables is very helpful. I'm wondering if it would be possible to add that same functionality to the client_id that appears on the allocation view:
![image](https://user-images.githubusercontent.com/39168929/187729513-dea664c0-7ff1-4916-a019-03f870bf0a98.png)

### Use-cases
When drilled down to a the allocation view, it currently takes extra clicks/context switches to identify what node the allocation is running on.

### Attempted Solutions
We can navigate up a level, or lookup the client name by other means, but again, this requires context switching which can be frustrating when debugging an issue.

**Comment by lgfa29** [comment]
Thanks for the suggestion @gmichalec-pandora. I think this will be helpful as well 🙂
