### ISSUE TITLE
HCL2 length function not taking string?

### ISSUE THREAD

**Issue by xorander00** [hashicorp/nomad#14462]
### Nomad version
v1.3.2

### Operating system and Environment details
FreeBSD 13.1-STABLE

### Issue
HCL2 length() function, [according to the docs](https://www.nomadproject.io/docs/job-specification/hcl2/functions/collection/length), should accept an argument of any of the following types: string, array, map, or tuple.  
It seems to only accept collections though, not a string.  I know I can remove the default assignment and effectively achieve the same thing, but I'd like to solve why length() isn't taking a string. I tried strlen() as well since that's in the Terraform docs and I wondered if Nomad might have a version mismatch with what's in the docs, but nope.

### Reproduction steps
See above snippet.

#### Expected Result
Return numeric length of string.

#### Actual Result
HCL2 semantic error when running `nomad job validate myjob.hcl`. Complains that length() expects a map, array, or tuple.  

```
Error getting job struct: Error parsing job file from ./ports/_job.hcl:
_job.hcl:36,17-24: Error in function call; Call to function "length" failed: collection must be a list, a map or a tuple.
```

### Job file (if appropriate)
```
variable "portsList" {
  description = "Path to file with list of ports"
  type = string
  default = ""
  validation  {
    condition = length(var.portsList) > 0
    error_message = "Path to file containing list of ports is required."
  }
}
```

**Comment by jrasell** [comment]
Hi @xorander00 and thanks for raising this issue. The current length function does indeed only support maps, lists, or tuples. I will raise a change to the documentation for this as well as add a new function to allow for calculating the length of a string.

**Comment by xorander00** [comment]
@jrasell No problem!  
  
I do have a quick question that overlaps with this issue. Is the HCL2 module used in nomad trailing by a few versions? I'm trying to use formatdate() with timestamp() as the 2nd argument (to use the current date/time).  
  
timestamp() is not listed in the Nomad docs, so it's not a surprise that it fails, but I do see it in the packer docs.  I'm trying to use formatdate to set a local variable to a formatted date/time string when an input variable is empty. If timestamp() is not available, then I'm not sure what other function to use for it (if there is one). I could of course render it using go-template at placement time, but I'd prefer this be done during job parsing as the value will always be consistent wherever it is referenced in the job.  
  
Not sure as I'm not familiar with the codebase, but I get the feeling that maybe rebasing and updating the HCL2 implementation used in Nomad might fix a number of these types of potential issues?

**Comment by jrasell** [comment]
Hi @xorander00; merely importing the library is not enough to make the language and function usable. The functions in particular [need to be mapped](https://github.com/hashicorp/nomad/blob/d33f1eac719c848f88de3cfc5606d85800b9ef62/jobspec2/functions.go#L25-L114) for use which means there is potential for differences between implementations.

If you have a use case for adding additional HCL2 functions, I would suggest raising a new feature request so we can correctly track these along with any context you have. If you're interested in trying to raise a PR to add the function, [this PR](https://github.com/hashicorp/nomad/pull/14463) I just raised could serve as a good base for how to do it.
