### ISSUE TITLE
An argument named "provider" is not expected here.

### ISSUE THREAD

**Issue by dotdiego** [hashicorp/nomad#14460]
Hello,

Documentation at [Job Specification/service](https://www.nomadproject.io/docs/job-specification/service) states that a service stanza  in a task can contain a provider with value **consul** or **nomad**.  
However when trying to run a job through the Web UI, i'm getting a generic error :  
`An argument named "provider" is not expected here.`

Are the docs outdated on this topic ?

**Comment by jrasell** [comment]
Hi @dotdiego, could you please let us know which Nomad version you're currently running?

**Comment by jrasell** [comment]
Hi @dotdiego, I am going to close this issue out owing to the additional context needed here. If you are still experiencing this issue, please feel free to re-open it with the Nomad version you are currently running.
