### ISSUE TITLE
Configuration to disable exec from the UI

### ISSUE THREAD

**Issue by jamesdmorgan** [hashicorp/nomad#14470]
### Proposal

Add configuration to disable exec into container functionality from the UI.

It feels like it ought to be disabled by default but I appreciate the functionality has been available for a while now.

### Use-cases
We would like to enable this functionality in our testing environments but disable it in production.

### Attempted Solutions
Its possible via ACLs but it would be much easier via configuration

**Comment by tgross** [comment]
Doing a bit of issue cleanup and saw this was still sitting in "triaging". Because we manage this via ACL policy, it's unlikely we're going to consider managing this via the UI. The UI has grown capabilities around ACL policies, and that's the way to go if that's what you're looking for.
