### ISSUE TITLE
High/Excessive memory consumption on nomad server

### ISSUE THREAD

**Issue by tomqwpl** [hashicorp/nomad#14531]
### Nomad version
v1.3.0

### Operating system and Environment details
Windows

### Issue
I'm seeing what I consider to be excessive memory consumption in nomad. Memory seems to constantly increase as I submit jobs, apparently without end.

Initially I'm wanting to understand whether what I'm seeing is expected or not. Maybe this is how nomad is expected to work, but it feels wrong to me. Certainly if it's going to increase the amount of memory in use for each job I submit, that's going to be a massive problem for us. So some understanding of how nomad uses memory and what it's storing here would be good. 

### Reproduction steps
Single instance of nomad running on my windows machine.
We have an external process that is submitting a couple of jobs every 5 seconds. Once the jobs have completed it pull the logs and "deregisters" the jobs with the purge option. Memory usage in nomad increases constantly. At 1GB reported memory usage I stopped the external process. 

Running garbage collection doesn't have any apparent effect.

If nomad is stopped and restarted, if then takes a really long time to start up again, memory increases up to the level it was before.

In testing elsewhere we have seen memory consumption of 3GB.

I have the output of "operator debug" from my test, and we also have the output from another test where the reported memory usage was 2.5GB. Bulk of the memory is in the go-memdb an go-immutable-radix. This seems easy enough for me to reproduce, so I can take other profile captures if necessary, but I'm not sure what I'm really looking for. I don't know what's in the output from "operator debug", but assuming there's no sensitive information in there, I can supply those (all the jobs I'm running are small dummy  "hello world" ones)

#### Expected Result
More modest memory consumption

#### Actual Result
What I consider high memory consumption.

**Comment by tgross** [comment]
Hi @tomqwpl! Something that might be missing your model here is that Nomad's state store is entirely in-memory. That's the go-immutable-radix you're seeing. The raft logs are persisted to disk, but those are _logs_. The slow startup time is also consistent with a large state store -- the raft logs have to get re-read into the state store memory.

The only thing that seems a little odd here is that garbage collection didn't improve the memory usage. But I suspect what's happening is that you have a large number of Evaluations which are not yet eligible for GC or that the jobs aren't eligible for GC for some reason. You should be able to look in your debug bundle and find out what object is taking up all the memory. It'll be in the `nomad-debug-2022-%M-%D-%HMSZ/interval/0000/` directory. That'll be the first place to look and we can go from there.

**Comment by tomqwpl** [comment]
Thanks @tgross . Yes I can see that I have a very large number of allocations.
If I tweak the garbage collection parameters for evaluations, and make it run the gc more often I can see that the memory usage stays more reasonable. It's still pretty high, but it's not growing.

I notice that there is no "gc threshold" for allocations. How are allocations garbage collected? 

I need to do some more investigations into the other debut output I have got. That had a evaluations.json file that was >1GB in size. From what I can tell from that file though, many of the allocations are more than 1 hour older than the newest ones, indicating that they ought to be eligible for garbage collection, but haven't been collected. 

If I read the documentation correctly, manually running garbage collection, either from "nomad system gc" or through the API, ignores the settings such as "eval_gc_threshold" and deletes anything in the terminal state, regardless of how long the objects have been there, is that right? So it should have an "immediate" effect on the number of evaluations. My only issue with that is that we are running jobs, waiting for them to finish and then pull output from them (logs, events, completion state and so on). If a manual GC is run, that's going to potentially delete jobs before we've had a chance to grab the output, despite the "job_gc_threshold" being, say, 30s. But it gives me a tool to experiment with anyway to see if has an effect.

**Comment by tgross** [comment]
> I notice that there is no "gc threshold" for allocations. How are allocations garbage collected?

Allocations are GC'd _on the server_ in the same GC function as evaluations. An evaluation has to live at least as long as any allocation(s) it creates, otherwise you'd end up with data integrity issues (ex. trying to ask "which eval created this alloc?"). The allocation's threshold is the same index as the evaluation, but based on the allocation's last _modify_ time. Otherwise we'd end up with allocations that live longer than an hour getting GC'd almost immediately on stop. Additionally, for batch jobs, the [GC logic](https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/core_sched.go#L306-L311) also includes ensuring the job associated with the alloc is dead as well.

So depending on whether you're issuing batch or system jobs, you might be seeing evaluations and allocations hanging around longer than expected. But based on what you're telling me I suspect it's that allocations aren't getting GC'd (because they've just stopped) and then the evaluations for those allocs aren't getting GC'd.

The reason I emphasized _on the server_ above is that allocations also get GC'd from clients. That's not driven by the server GC core jobs at all. The client marks terminal allocs as eligible for GC but only cleans them up if there's space pressure (see config values like [`client#gc_disk_usage_threshold`](https://www.nomadproject.io/docs/configuration/client#gc_disk_usage_threshold). An alloc that's GC'd on the server might have recoverable logs on the client still, whereas once the allocs are GC'd on the client, the logs are gone.

> If I read the documentation correctly, manually running garbage collection, either from "nomad system gc" or through the API, ignores the settings such as "eval_gc_threshold" and deletes anything in the terminal state, regardless of how long the objects have been there, is that right?

Correct, with the caveat I noted above that batch allocations (and their evals) don't get GC'd unless their job is also terminal.

> So it should have an "immediate" effect on the number of evaluations.

Where "immediate" == "the server has to process an internal GC evaluation and then batch up raft messages to delete the objects in question", yes. 😀 For common cases this is fairly quick but just keep in mind that if you're running up a few GB worth of evals and allocations, you might end up emitting a few thousand raft messages that need to get replicated to all servers to delete them all. I've recently run into a case where this was surprisingly expensive but that was for on the order of millions of evals.

> My only issue with that is that we are running jobs, waiting for them to finish and then pull output from them (logs, events, completion state and so on).

Because allocations usually linger on the client, it might be better for your use case to have an agent running on the client that ships the logs off, rather than trying to get the logs out of the API. On Linux I've used `filebeat` for this; I'm not sure what the best option on Windows would be.

Another note about your original post:
> Single instance of nomad running on my windows machine.

This sounds like you've got a single instance running as both server and client? That's possible to make work, although obviously not highly-available. But from the standpoint of dealing with resource constraints it's a bit like playing on hard mode. The server doesn't expect to be competing with your workloads for resources, so scheduling is going to be tricky unless you've reserved a big chunk of memory for the server (which can be quite a lot for a busy server, as you've seen!).

**Comment by tomqwpl** [comment]
@tgross Hi, thanks for the detailed information. I'm getting a bit more of an understanding of how it works. 

The "operator debug" output I'm investigating has an evaluations.json file that is too big to view (it's >1GB). This is from an installation where nomad was consuming 3GB memory I think, and had essentially become unresponsive. I don't know how big the machine was on which it was running, perhaps just too small, but it was consuming all the memory on the machine. However, this was an installation that had reportedly had light use, it was just a demo and eval system.

Since the evaluations.json file is too big to sensibly view, I wrote a program to do some basic analysis on it. Partial output is as follows:

```
min create time : 2022-06-09T12:09:52+01:00
max create time : 2022-09-01T17:12:13+01:00
min modify time : 2022-06-09T12:09:52+01:00
max modify time : 2022-09-01T17:12:13+01:00
status frequencies :
     pending 143570
    complete 1310831

triggered by frequencies :
  queued-allocs 2
  node-update 1408817
  job-register 4984
  job-deregister 40598
```

So you can see there are around 1.5 million evaluations (1454401). Vast majority have come from "node-update". What does that imply?

Any thoughts on why the "complete" evaluations haven't been garbage collected? GC parameters would be the nomad defaults. From your earlier comments, and indeed from my local experimentation, evaluations are garbage collected when complete

It then prints out the frequencies of the job IDs encountered. There are a significant number where there are 130,000 or more evaluations for the same job ID. Looking up those jobs in the jobs.json file, they are all marked as pending. There are 145 distinct job IDs referenced in the evaluations. There are 109 jobs in the jobs.json file, 96 of which are marked as "pending".

So this doesn't appear to be a case of submitting a large number of jobs. Something seems to be causing repeated evaluations for the same jobs, but it's unclear what ("node-update").

Any suggestions as to the cause of this, or what I could do to further investigate?

Thanks.

**Comment by tgross** [comment]
The `node-update` evaluations all come from the various [Node RPCs](https://github.com/hashicorp/nomad/blob/main/nomad/node_endpoint.go), so those are going to be from events where the node has updated either new up/down status, or more likely in your case, changes to its available resources as batch jobs have completed.

That does seem like an awful lot of evals though. How many allocations made up those 4984 job registrations? Were the allocations "flappy" at all? That there were 40598 deregister evaluations but 4984 registrations looks weird to me as well... is there an automated process stopping jobs early?

> Any thoughts on why the "complete" evaluations haven't been garbage collected? GC parameters would be the nomad defaults. From your earlier comments, and indeed from my local experimentation, evaluations are garbage collected when complete

It may be that they _are_ being garbage collected, but that's not instantaneous. Deleting stuff from the state store has to pass through the state store, which is a serialized process (for correctness) even if we don't include raft replication. So with 1.5 million evaluations it's entirely possible that it's just taking a while to delete them all. The delete is done in batches of up to 7282.

**Comment by tgross** [comment]
> or more likely in your case, changes to its available resources as batch jobs have completed.

Actually, I just re-read that bit of code and did some local testing here to make sure, and batch jobs completing and freeing resources won't trigger those updates. That suggests there's something triggering a lot of node updates. Either something in the fingerprint is changing or it's got a flaky connection. There's a Client Events section on the UI but it doesn't really get a lot of information. It might be useful to check the client logs to see if there are have been a lot of changes to the client state outside of your workload as well.

**Comment by tomqwpl** [comment]
OK thanks. 
In terms of the jobs, they are all simple task group, single task, generally batch jobs with no restart policy (I literally want to run a single process, nothing more complex than that). 

I'll have to delve into the debug zip we've got and see what else it contains. I looked at the client log, but I wasn't sure what I was looking for. 

When you say "something changing in the fingerprinting", what would you have in mind? All of these tasks would be targetting our own task driver plugin but I don't believe that anything in the fingerprint that that generates would be changing. A flaky connection is possible. I don't exactly know how the machines on which this issue arose were being run, so I don't know exactly. It's something to look out for though, I'll bear that in mind.

**Comment by tgross** [comment]
The fingerprint can be updated by the task driver changing any attributes of the node. But it can also be updated if you have a Consul or Vault client that loses connectivity.

**Comment by tomqwpl** [comment]
The reason I think that I have a bunch of jobs that are "stuck" and not being GCd is these extra evaluations. Looking at the code, the job GC logic looks at all evals associated with a job and checks whether those evals are eligible based on the threshold. Only if all evals are eligible is the job garbage collected. Since there seems to be a new eval created for each of these jobs every couple of minutes, they therefore never become eligible.

**Comment by tgross** [comment]
Thanks @tomqwpl. There seems like enough info here for me to attempt a reproduction. Let me give a go at that and I'll come back with more details or next places to look.

**Comment by tomqwpl** [comment]
Looking at the code, and the fact that we have a custom task driver, my guess is that the most likely reason for these "node update" evaluations is the driver being updated in some way (there are no devices and no csi volumes). From the code (func (c *Client) updateNodeFromDriver) this is a cause of the "state changed, updating node and re-registering" message.

If I look in the nomad ui and look at the drivers for the client, our task driver says "last updated a minute ago" (or 2 minutes ago, never more), where as all the others say "last updated 25 minutes ago" (I restarted nomad about then). Maybe this is expected, and indeed the "state changed, updating node and re-registering" message seems to happen more frequently than every two minutes, but this seems a plausible correlation.

The driver attributes we set in the fingerprint don't change though, which seems to be the only reason that updateNodeFromDriver would cause a "state changed, updating node and re-registering" message. So at the moment I'm unclear whether this is a cause or not. 

Does it work to just nomad in the vscode go debugger? Perhaps I'll try that and see if I can work out what is triggering these evals.

**Comment by tgross** [comment]
My first repro attempt was against a cluster with 3 low-powered servers with 3 nodes. I ran the following script until I saw GC run. Memory never got above ~230MB RSS, and I don't see any `node-update` evals whatsoever.

```bash
#!/bin/bash

while :
do
    echo "submitting 2 jobs..."
    sed "s/JOBID/$(uuid)/" ./batch.nomad | nomad job run -detach -
    sed "s/JOBID/$(uuid)/" ./batch.nomad | nomad job run -detach -

    echo "waiting 5 seconds..."
    sleep 5
    nomad eval list -namespace '*'
done
```

```hcl
job "JOBID" {
  type        = "batch"
  datacenters = ["dc1"]

  group "group" {

    task "task" {

      driver = "raw_exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "echo hello world; sleep 1"]
      }

      resources {
        cpu    = 64
        memory = 64
      }

    }
  }
}
```

> Looking at the code, and the fact that we have a custom task driver, my guess is that the most likely reason for these "node update" evaluations is the driver being updated in some way (there are no devices and no csi volumes). From the code (func (c *Client) updateNodeFromDriver) this is a cause of the "state changed, updating node and re-registering" message.
>
> If I look in the nomad ui and look at the drivers for the client, our task driver says "last updated a minute ago" (or 2 minutes ago, never more), where as all the others say "last updated 25 minutes ago" (I restarted nomad about then). Maybe this is expected, and indeed the "state changed, updating node and re-registering" message seems to happen more frequently than every two minutes, but this seems a plausible correlation.

Oh, yes that seems really plausible. 

> Does it work to just nomad in the vscode go debugger? 

It might, but I'll warn you that attaching a debugger to Nomad is tricky because there are a lot of concurrent goroutines. It might be worth trying to ~add printf~ "instrument" 😁 your task driver to see if you can detect the source of those updates. Any chance that custom task driver is open source?

**Comment by tomqwpl** [comment]
OK, I've tracked it down. When I said "the driver attributes we set in the fingerprint don't change though", turns out that wasn't quite true:
```
updateNodeFromDriverLocked attribute changed: attrName=driver.custom_task_driver.versionTags newVal="v5.0.0,default,v5,v5.0" oldVal="default,v5,v5.0,v5.0.0"
```
This is causing the node update to be prompted.
I will fix that up and see whether that makes a difference to things.

**Comment by tgross** [comment]
> The issue was constructing an attribute value by iterating over a map and concatenating the keys. Map iteration order isn't stable, even if the map doesn't change.

Oof, that's a subtle gotcha! So glad that you've got it figured out!
