### ISSUE TITLE
Update Grafana Dashboards

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#14540]
Hi!

I noticed that this repo contains a [Grafana dashboard](https://github.com/hashicorp/nomad/tree/main/integrations/grafana_dashboards) but that seems outdated based on the current metrics which are exported.

I recently open sourced 3 dashboards (server, client, allocations) and I am happy to contribute the same to upstream: https://github.com/mr-karan/nomad-monitoring

Please let me know if there's an interest for the same to be included in upstream repo or it's fine for this stuff to be community maintained. 

Thanks!

**Comment by DerekStrickland** [comment]
Hi @mr-karan.  Another great resource for the community!  Thanks for sharing.

As you can see, that example dashboard is 5 years old. I don't think we plan to take on maintaining a dashboard. Your work seems like something it would be great to link to from the [tools](https://www.nomadproject.io/tools) page and from the integrations [doc](https://github.com/hashicorp/nomad/tree/main/integrations/grafana_dashboards) you linked previously. I'd suggest opening a PR that adds links your project there.
