### ISSUE TITLE
Add a helper function to NomadVariableItems to get the Items as `map[string]interface{}`

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#14603]
### Proposal

Provide a helper function on `NomadVariableItems` to get the map as a `map[string]interface{}`

### Use-cases

There are several consul-template formatting functions that require that their parameter data to be typed as `map[string]interface{}`. Providing a helper to re-type the NomadVariableItems collection would enable the items to be used with these functions.

### Attempted Solutions

I did a sample of this process by using a roundtrip through JSON to remove the type data so that `toTOML` is provided a `map[string]interface{}`
```
{{ with nomadVar "test" }}{{ .Parent.Items | sprig_toJson | parseJSON | toTOML }}{{end}}
```
> **SIDE NOTE:** I had to use the `sprig_toJson` function rather than CT's because of the same typing issue. CT's `toJSON` function strictly requires the type to be `map[string]interface{}`

**Comment by tgross** [comment]
Closing as this is merged into https://github.com/hashicorp/consul-template/pull/1632 which is shipping in 1.4.0-rc1 already
