### ISSUE TITLE
Server-side restarts of tasks failed on clients

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#1461]
If a task has failed on a client and it could potentially be recoverable on another, the server should replace the task group onto a new node.

**Comment by SephVelut** [comment]
Nomad's deficiencies in handling failed jobs is what's keeping me away right now. I was using Nomad several months ago and just got tired of constantly intervening in the system to resubmit jobs. Would really like to see more proactive policies for Nomad to deal with outside state, which changes and fails constantly.

**Comment by a86c6f7964** [comment]
has there been any thought to putting this on the roadmap, and/or mitigating it some other way. Currently if I shut down a nomad client server let say to upgrade nomad or upgrade the OS then there is a very likely chance that some of the tasks randomly fail when trying to start up on another server. The random failure usually comes from some docker race condition, but be that as it may I would prefer to not have to resubmit my job just because 1 machine failed in order to get all of the tasks running again.

**Comment by dadgar** [comment]
@a86c6f7964 It is something we are hoping to tackle in 0.6.0

**Comment by burdandrei** [comment]
so not 0.7, 0.8?

**Comment by jovandeginste** [comment]
I usually drain servers for maintenance. This obviously doesn't work when a server randomly fails, but for upgrades this seems to work pretty well so far. Then again I don't usually have multi-task taskgroups.

**Comment by SoMuchToGrok** [comment]
Occasionally when I drain a node, some jobs won't be re-allocated and will remain in a "dead" state. Doesn't happen often, but when it does, it quickly becomes a pretty major issue.

Hard to definitively say that I'm running into this exact problem, but it definitely feels that way. Is there any update for this on the roadmap?

**Comment by burdandrei** [comment]
I received even greater experience - I had a job with multiple groups. After node fails i received some groups relocated, and some remain dead.

**Comment by samart** [comment]
per job, it would be nice to set:
task_unreacheable_timeout
task_gone_timeout

If Nomad cannot see that a service task is running (unreacheable) or sees that the task is gone, it should try to schedule it on another host.

**Comment by SoMuchToGrok** [comment]
Any update on this from a roadmap perspective? 

I've experienced node failures in AWS EC2, and this has bitten me a few times now. The desired behavior here is more or less a requirement for a scheduler - node failures are a **guarantee** in the cloud.

**Comment by preetapan** [comment]
@SoMuchToGrok This is landing in Nomad 0.8. You can follow [this branch](https://github.com/hashicorp/nomad/tree/f-server-side-restarts) for details if interested.

**Comment by shantanugadgil** [comment]
I hit similar issues when I upgrade my compute fleet in a serial manner as @a86c6f7964 
Sometimes the Docker daemon fails to respond after the OS packages upgrade.

I hadn't thought of `draining` the node before shutting down Nomad, Consul, Docker and updating the OS packages.

**Comment by dkua** [comment]
@preetapan the branch mentioned doesn't seem to exist anymore and the `0.8` CHANGELOG doesn't seem to include it https://github.com/hashicorp/nomad/blob/b-canary-auto/CHANGELOG.md. Is this no longer on the roadmap/being worked on, I don't see any mention anywhere.

**Comment by preetapan** [comment]
@dkua the changelog mentions it as follows

```
core: Failed tasks are automatically rescheduled according to user specified criteria. For more information on configuration, see the Reshedule Stanza [GH-3981]
```
[Docs for rescheduling](https://github.com/hashicorp/nomad/blob/master/website/source/docs/job-specification/reschedule.html.md)

**Comment by dkua** [comment]
@preetapan ah okay thank you that's great to know gonna let my team know. Didn't notice it at first since the branch-to-follow 404s and #3981 doesn't reference this issue.

**Comment by preetapan** [comment]
This was addressed with [rescheduling](https://www.nomadproject.io/docs/job-specification/reschedule.html) in 0.8.
