### ISSUE TITLE
Send trafic to ingress-gateway

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/nomad#14616]
Hello guys,

I'm opening an issue here as I didn't get any answer from [discuss](https://discuss.hashicorp.com/t/send-trafic-to-ingress-gateway/44054).

I’m using nomad 1.3.5 and consul 1.13.1.
I’m trying to send trafic to consul ingress-gateway deployed in nomad with the following:

```
job "ingress-gateway" {
  region      = "europe-west1"
  datacenters = ["europe-west1"]
  type        = "service"

  update {
    max_parallel     = 1
    health_check     = "task_states"
    min_healthy_time = "15s"
    healthy_deadline = "60s"
    canary           = 1
    auto_revert      = true
    auto_promote     = true
  }

  group "ingress-gateway" {
    count = 1
    network {
      mode = "bridge"
      port "inbound" {
        to = 8080
      }
    }

    service {
      name = "ingress-gateway"
      port = "8080"

      connect {
        gateway {
          proxy {}

          ingress {
            listener {
              port = 8080
              protocol = "http"
              
              service {
                name = "nginx"
                hosts = ["*"]
              }
            }
          }
        }
      }
    }
  }

  group "nginx" {
    count = 1
    network {
      mode = "bridge"
      port "http" {
        to     = 8080
      }
    }

    service {
      name = "nginx"
      port = "8080"

      check {
        expose   = true
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }

      connect {
        sidecar_service {}
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:latest"
        ports = ["http"]

        volumes = [
          "local:/etc/nginx/conf.d",
        ]
      }

      template {
        data = <<EOF
server {
   listen 8080;

   location / {
     add_header Content-Type text/plain;
     return 200 "[host] = $host [http_host] = $http_host";
   }

   location = /health {
     add_header Content-Type text/plain;
     return 200 "OK";
   }
}
EOF

        destination   = "local/default.conf"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
    }
  }

    group "loadbalancer-nginx" {
    count = 1
    network {
      mode = "bridge"
      port "http" {
        static = 9090
        to     = 8080
      }
    }

    service {
      name = "loadbalancer-nginx"
      port = "8080"

      check {
        expose   = true
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "ingress-gateway"
              local_bind_port  = 10000
              local_bind_address = "127.0.0.1"
            }
          }
        }
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:latest"
        ports = ["http"]

        volumes = [
          "local:/etc/nginx/conf.d",
        ]
      }

      template {
        data = <<EOF
server {
   listen 8080;
   error_log  /var/log/nginx/error.log debug;
   server_name _;

   location / {
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_set_header Host $http_host;
     proxy_pass http://127.0.0.1:10000;

     #add_header Content-Type text/plain;
     #return 200 "[host] = $host [http_host] = $http_host";
   }

   location = /health {
     add_header Content-Type text/plain;
     return 200 "OK";
   }
}
EOF

        destination   = "local/default.conf"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
    }
  }
}
```

```
cat >/tmp/consul_service_defaults.hcl<<EOF
> Kind      = "service-defaults"
Name      = "nginx"
Protocol  = "http"
EOF
```

```
consul config write /tmp/consul_service_defaults.hcl
```

```
curl http://127.0.0.1:9090
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.23.1</center>
</body>
</html>
```

From the docker container loadbalancer-nginx here is the curl result:
```
root@db25fea5ae8d:/etc/nginx/conf.d# curl http://127.0.0.1:10000
curl: (56) Recv failure: Connection reset by peer
```

I created ingress-gateway with a dynamic port instead of static in order to have multiple instances.

Why am I having connection reset?
Any help?
I’m supposed to receive an HTTP 200.

**Comment by lgfa29** [comment]
Hi @Lord-Y 👋 

I'm a little confused about your intended goal, so if you could expand a little bit on what your final goal is that will be super helpful!

The way you currently have things setup is not expected to work. Your Nginx load balancer is trying to connect ***to*** the ingress as an upstream. 

```hcl
sidecar_service {
  proxy {
    upstreams {
      destination_name = "ingress-gateway"
      local_bind_port  = 10000
      local_bind_address = "127.0.0.1"
    }
}
```

So what you currently have is this:
![image](https://user-images.githubusercontent.com/775380/191770617-e18c2768-a7c6-418d-a63a-b818076809a9.png)

This is not how the ingress gateway is supposed to work. The requests should go from ***outside*** the mesh and ***into*** the gateway. So I'm assuming you want something like this instead:

![image](https://user-images.githubusercontent.com/775380/191770914-759150bc-939f-4684-921c-a19fa04e79bd.png)

So you are fronting your Ingress Gateway with an Nginx instance. In order to accomplish this, this Nginx should not use service mesh. It's the role of the Ingress Gateway to route traffic from outside the mesh into it. Otherwise you're kind of creating an Ingress Gateway yourself 😅 

One way to accomplish this is to change your file like so:

```diff
@@ -13,7 +13,7 @@ job "ingress-gateway" {

     service {
       name = "ingress-gateway"
-      port = "8080"
+      port = "inbound"

       connect {
         gateway {
@@ -109,27 +109,14 @@ EOF

     service {
       name = "loadbalancer-nginx"
-      port = "8080"
+      port = "http"

       check {
-        expose   = true
         type     = "http"
         path     = "/health"
         interval = "10s"
         timeout  = "2s"
       }
-
-      connect {
-        sidecar_service {
-          proxy {
-            upstreams {
-              destination_name = "ingress-gateway"
-              local_bind_port  = 10000
-              local_bind_address = "127.0.0.1"
-            }
-          }
-        }
-      }
     }

     task "nginx" {
@@ -146,6 +133,12 @@ EOF

       template {
         data = <<EOF
+upstream gw {
+  {{- range service "ingress-gateway"}}
+  server {{.Address}}:{{.Port}};
+  {{- end}}
+}
+
 server {
    listen 8080;
    error_log  /var/log/nginx/error.log debug;
@@ -156,7 +149,7 @@ server {
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
-     proxy_pass http://127.0.0.1:10000;
+     proxy_pass http://gw;

      #add_header Content-Type text/plain;
      #return 200 "[host] = $host [http_host] = $http_host";
```

Now your Nginx loadbalancer is outside the mesh and connecting to the Ingress Gateway using regular service discovery.

But let me know if that's not what you're trying to accomplish 🙂

**Comment by Lord-Y** [comment]
Hi @lgfa29 Thx for your reply. I'm going to explain you my goal.
I have an application deployed in multiple namespaces in nomad.
I barely touch the loadbalancer-nginx configuration.
I wanted to have nth ingresses instance per namespaces and potentially modify his configuration in namespace A but not B.
Based on headers, the `loadbalancer-nginx` will send the trafic to the appropriate `ingress-gateway` via the envoy proxy
Your 1st screenshot is almost accurate.
I thought the `ingress-gateway` could be inside of the box like `nginx` is and then avoiding `upstream gw` code and use directly the envoy proxy port.

I testing your configuration and it's working the way I wanted it.

Thx for your help.

**Comment by lgfa29** [comment]
>  I thought the ingress-gateway could be inside of the box like nginx is and then avoiding upstream gw code and use directly the envoy proxy port.

I think this may be the part that is confusing you. The ingress gateway, by definition, lives at the edge of the mesh. Its goal is to bridge the traffic from outside the mesh into the mesh.

If both `nginx` boxes were inside the mesh, then they can communicate directly through their sidecars and you would have no need for the ingress gateway. You actually be creating your own ingress gateway 😅
