### ISSUE TITLE
docker: cpuset_cpus setting being ignored 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#14626]
It seems setting `cpuset_cpus` in the `config` block of a task using the docker driver has stopped having an effect.

docker api confirms the setting is being set in the docker container config
```
➜ docker inspect 83 | jq -r .[].HostConfig.CpusetCpus
3-5
```

but the `docker-` cgroup is allowed the full set of cores
```
➜ cat /sys/fs/cgroup/nomad.slice/docker-8388dbca54a234b223ec4bf16f62391cf99b0a161c7899c9abca2c23e435631c.scope/cpuset.cpus.effective
0-23
```

as is the nomad managed cgroup from which the values are copied from 
```
➜ cat /sys/fs/cgroup/nomad.slice/0afb22f9-fc1e-a2bf-e07d-3ff543c74f6f.redis.scope/cpuset.cpus.effective 
0-23
```

<details><summary>example job</summary>

```hcl
job "cpuset" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image          = "redis:7"
        ports          = ["db"]
	auth_soft_fail = true
	cpuset_cpus = "3-5"
      }

      resources {
        cpu    = 1000
        memory = 256
      }
    }
  }
}
```
</details>

**Comment by shoenig** [comment]
I believe what's happening is, we added support for `resources.cores` (Apr 2021) after the docker driver config supported `cpuset_cpus`, (Nov 2020) which then stopped behaving as expected because Nomad will always add allocations to a "shared" cpuset managed by Nomad containing all cores that have not yet been reserved.

On systems with cgroups v2 instead of a shared cpuset cgroup, the cpuset bookkeeping for each allocation is unaware of the docker host configuration.

**Comment by shishir-a412ed** [comment]
We are trying to run cockroachDB in NUMA configuration, and the issue we are seeing is Nomad is not respecting `cpuset_cpus` (Nomad docker driver option) and end up using all the cores.

E.g. If we deploy the below nomad job (This is just an example job, not the real job) on a physical node with two NUMA nodes `node0` and `node1` (64 vCPUS) with the following configuration.

```
node0 = 0-15, 32-47
node1 = 16-31, 48-63
```

```
job "cockroachDB-numa" {
  datacenters = ["dc1"]

  group "cockroachDB-numa-group" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "CockroachDB-numa-task" {
      driver = "docker"

      config {
        image = "cockroachdb:latest"
        cpuset_cpus = "0-15,32-47"
        ports = ["db"]
      }

      resources {
        cpu    = 6300
        memory = 4096
      }
    }
  }
}
```

We would expect the workload to only run on NUMA `node0` (0-15, 32-47) however we see that cockroachDB is running on almost all cores. The strange thing is when we run `nproc` inside the container **OR** check the cgroups filesystem, it shows the correct value.

`nproc` shows `32` when I exec into the container and run `nproc`

From the cgroup filesystem

```
$$:/sys/fs/cgroup/cpuset/docker/<container_id># cat cpuset.cpus
0-15,32-47
```

However when we inspect the actual usage through `htop` or `numatop`, it is clearly showing that cockroachDB is consuming all the cores. Attaching a screenshot of `htop` (The real output might be different) just to give an idea.

 
![CockroachDB](https://user-images.githubusercontent.com/4207652/191300416-665e4d2e-3d7b-486f-81bf-6e975ca5d9ff.png)

**Comment by shishir-a412ed** [comment]
@shoenig Just checking if you had a chance to look into this?

**Comment by shoenig** [comment]
As of Nomad 1.7 the `cpuset_cpus` setting in the Docker driver will only emit a warning that setting the value does nothing. It never worked apart from a brief 5 month period in 2021. Instead Nomad 1.7 (Enterprise) supports NUMA aware scheduling natively, which was always a requirement for the end goal of this feature to actually work correctly.
