### ISSUE TITLE
nomad job distinct - strict vs relaxed

### ISSUE THREAD

**Issue by olenm** [hashicorp/nomad#1464]
This is sort of both a bug and feature request.

### Nomad version
`Nomad v0.3.2`

### Operating system and Environment details
CentOS Linux release 7.2.1511 (Core) 

### Issue
Using distinct_hosts=true on a job file with a group-count greater than the number nomad agent servers running causes a set of successful jobs to be created on the nomad agents, and allocations failures for the amount of excess.

It would be great to have the 4th job run on any of the other hosts, preferably by configuration of the distinct_hosts as either strict or relaxed (or another flag)

### Reproduction steps
a 3x group of nomad agents
run a jobfile including attributes: 
```
  constraint { distinct_hosts = true }
  
  group "groupname" {
    count = 4
```

allocations from job id:
```
Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status
[id 1]    [evalid]  [node 1]  groupname   run      running
[id 1]    [evalid]  <none>    groupname   failed   failed
[id 1]    [evalid]  [node 2]  groupname   run      running
[id 1]    [evalid]  [node 3]  groupname   run      running
```

**Comment by dadgar** [comment]
By default we apply a soft spread for task groups in a job so really you can think of distinct host as the strict version
