### ISSUE TITLE
UI making frequent requests with no delay on task groups page

### ISSUE THREAD

**Issue by kyledicesare** [hashicorp/nomad#14644]
### Nomad version
Output from `nomad version`
Nomad v1.3.5 (1359c2580fed080295840fb888e28f0855e42d50)
I've also seen this on Nomad v1.2.12 (ad603b02153700fae06e2487ae2b5a164ffa2c4d)
### Operating system and Environment details
Ubuntu 22.04 (I've also seen this on other versions of Ubuntu)
### Issue
The task groups page is making requests for /v1/job/jobname with no delay between them. I've noticed this only seems to happen if there's a completed alloc on the page.
### Reproduction steps
1. Run `nomad agent -dev -bind=0.0.0.0`
2. Deploy a job (I used the example from the docs) - `nomad job run docs.nomad`
3. Make a change to the job and deploy it again
4. Go to the task group page in the nomad UI (http://ip:4646/ui/jobs/docs@default/example)
#### Expected Result
UI periodically updates with some delay between requests 
#### Actual Result
Thousands of requests within seconds 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/9067432/191618342-0ed6a135-a85c-48e0-a95b-1bff87ca1aa9.png">

### Job file (if appropriate)
[Example job](https://learn.hashicorp.com/tutorials/nomad/jobs-submit)

### Nomad Server logs (if appropriate)
```
    2022-09-21T22:01:07.421Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="124.123µs"
    2022-09-21T22:01:07.427Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="120.276µs"
    2022-09-21T22:01:07.433Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="121.839µs"
    2022-09-21T22:01:07.440Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="106.069µs"
    2022-09-21T22:01:07.448Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="116.078µs"
```

**Comment by philrenaud** [comment]
Thanks for raising this, @kyledicesare — we'll give this a look as soon as possible.

**Comment by ChaiWithJai** [comment]
@philrenaud going to start picking up this investigation on Wednesday of this week.

**Comment by quinndiggitypolymath** [comment]
I am also seeing this behaviour - the following UI pages result in thousands of requests being sent in just a few seconds:
```
https://nomad.example.com/ui/jobs/{{ JOB_NAME }}@default/{{ GROUP_NAME }
https://nomad.example.com/ui/jobs/{{ JOB_NAME }}/{{ GROUP_NAME }
```
