### ISSUE TITLE
Golang API reports Artifact Headers are an invalid key

### ISSUE THREAD

**Issue by jimrazmus** [hashicorp/nomad#14657]
### Nomad version

github.com/hashicorp/nomad v1.3.5
github.com/hashicorp/nomad/api v0.0.0-20220922140200-349501f82584

### Operating system and Environment details

Mac OS 12.5.1

### Issue

Calling jobspec.Parse (github.com/hashicorp/nomad/jobspec) with a job containing an artifact clause with 'headers' fails and reports that 'headers' is an invalid key.

Looking at the parseArtifacts function in the [jobspec.go](https://github.com/hashicorp/nomad/blob/7a8b1368b7bc6cda67a9fb5d942c92806087f4fd/jobspec/parse_task.go#L370) file, we can see that 'headers' is not in the list of valid keys.

### Reproduction steps

Provide the job definition to the jobspec.Parse function.
 
```go
job, err := jobspec.Parse(&buf)
```

#### Expected Result

The job definition should parse successfully and return a *api.Job.

#### Actual Result

Parse returns an error indicating artifact -> invalid key: headers

### Job file

```
job "docs" {
  datacenters = ["dc1"]
  group "example" {
    network {
      port "http" {
        static = "5678"
      }
    }
    task "server" {
      artifact {
        headers {
          User-Agent    = "nomad-[${NOMAD_JOB_ID}]-[${NOMAD_GROUP_NAME}]-[${NOMAD_TASK_NAME}]"
          X-Nomad-Alloc = "${NOMAD_ALLOC_ID}"
        }
        source = "https://example.com/file.txt"
      }
      config {
        image = "hashicorp/http-echo"
        ports = ["http"]
        args = [
          "-listen",
          ":5678",
          "-text",
          "hello world",
        ]
      }
      driver = "docker"
    }
  }
}
```

### Nomad Server logs (if appropriate)

NA

### Nomad Client logs (if appropriate)

NA

**Comment by lgfa29** [comment]
Thanks for report @jimrazmus!

This is also a problem when running `nomad run -hcl1`. For a while we were deciding on how to handle and deprecate HCLv1 parsing, but it was decided to keep support for both for now. This change was probably caught in the middle of that discussion. 

Just as a heads up, the `jobspec` and `jobspec2` packages are not part of the `api` package, so we don't have any breaking change policy around them. That being said, it may be better to use `jobspec2` for parsing jobs unless you _really_ need HCLv1 parsing for some reason.

And thanks for the PR, I will get a fix there soon 🙂
