### ISSUE TITLE
Nomad stagger removes all services for job from Consul at once

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/nomad#1467]
We have a job specification which has a 30 second stagger on all updates:

```
update {
    stagger = "30s"
    max_parallel = 1
}

group "example" {
    count = 3

    task "example" {
        driver = "docker"

        config {
            image = "docker-registry.service.consul:5000/example:latest"
        }

        ...
```

however we're finding that whenever the job file is updated and run with Nomad (via consul-template) (for example, we want to roll-out a new image) all the service definitions are removed from Consul at the same time - the stagger is not enforced. This causes a short 30 second to a minute outage whenever a new image needs to be rolled out.

I'm going to attempt to replicate it on our dev environment and post the logs below.
### Nomad version

0.4.0

**Comment by dadgar** [comment]
I would also be curious if you could give a before and after version of the job file and the `nomad plan` output

**Comment by grobinson-blockchain** [comment]
@dadgar the before and after are identical except for:

        config {
            image = "docker-registry.service.consul:5000/example:latest"
        }

which is updated with a different tag in the docker image (via consul-template). R.E `nomad plan`, there isn't much output, even with the verbose option:

    +/- Job: "example"
    +/- Task Group: "example" (3 in-place update)
      +/- Task: "example" (forces in-place update)

    Scheduler dry-run:
    - All tasks successfully allocated.

    Job Modify Index: 47669
    To submit the job with version verification run:

    nomad run -check-index 47669 /etc/nomad/jobs/example.hcl

**Comment by dadgar** [comment]
@grobinson-blockchain So I am a  bit confused, the second output shows it running as an in-place update but you are saying you are changing the docker image. This should cause create/destroy updates

**Comment by grobinson-blockchain** [comment]
@dadgar sorry, my mistake. Here is the correct output from `nomad plan`:

    +/- Job: "demo"
    +/- Task Group: "demo" (3 create/destroy update)
      +/- Task: "demo" (forces create/destroy update)
        +/- Config {
              dns_servers[0]:         "172.17.0.1"
          +/- image:                  "docker-registry.service.consul:5000/demo:v0.9" => "docker-registry.service.consul:5000/demo:v1.0"
              labels[0][servicename]: "demo"
              port_map[0][http]:      "8080"
        }

    Scheduler dry-run:
    - All tasks successfully allocated.
    - Rolling update, next evaluation will be in 30s.

    Job Modify Index: 81007
    To submit the job with version verification run:

    nomad run -check-index 81007 /etc/nomad/jobs/demo.hcl

    When running the job with the check-index flag, the job will only be run if the
    server side version matches the the job modify index returned. If the index has
    changed, another user has modified the job and the plan's results are
    potentially invalid.

**Comment by avinson** [comment]
@dadgar in a rolling update, does nomad wait for the new service instance to be healthy in consul before proceeding to the next instance? it's not clear from the docs if this is the case but, if not, that's probably the source of this issue.

**Comment by grobinson-blockchain** [comment]
@avinson afaik it does not. When combined with the issue above this means releases of new versions via Nomad cause several minutes of downtime for the entire service.

**Comment by avinson** [comment]
@grobinson-blockchain it might be necessary to implement a blue/green deployment strategy given nomad's current functionality. that is covered in the docs here: https://www.nomadproject.io/docs/jobops/updating.html

**Comment by Nomon** [comment]
If updating them all at once causes several minutes of downtime for count=3, it would indicate that stagger of 30s is nowhere enough for count=3, remember it takes a while to pull the images, the stagger begins counting once the allocation has been placed on the instance, not when the service has started.

**Comment by dadgar** [comment]
Closing this as 0.6.0 changes the way deployments are done and it is no longer stagger based and rather based on checks and task health. This no longer happens. 0.6.0 should be released shortly as it is in the RC phase currently.
