### ISSUE TITLE
Nomad native registry mirroring 

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#14682]
Due to docker can only mirror docker.io and nomad uses for example the image gcr.io/google_containers/pause-amd64, it is not possible to have a 100% air gapped environment with the docker daemon.  

I see a closed [issue](https://github.com/hashicorp/nomad/issues/11925). But IMHO this is critical for airgapped environments. 

![image](https://user-images.githubusercontent.com/5046525/192145438-e9c631c2-f118-4a0c-abfa-7efdfcacd312.png)

**Comment by suikast42** [comment]
I see a infra_image stanza in docker driver stanza. That could be workarround for this.

A stanza like image_mirror could be more helpful imho. With the infra_image you must track the version releases of that image.

**Comment by tgross** [comment]
Hi @suikast42! This is really out of scope for Nomad. If you want to set up a registry mirror you can already do so and point your image names to that, the Docker daemon will happily use that. And you'd need to set up [Authentication](https://www.nomadproject.io/docs/drivers/docker#authentication) as noted in the docs.
