### ISSUE TITLE
"Smarter" job specifications

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#147]
I am not sure if this is within the scope of the project, but I think a use-case like this is pretty common place.

I would like to run something like hdfs on a nomad cluster. Mesos uses schedulers and executors for their frameworks. They have a hdfs framework here: https://github.com/mesosphere/hdfs

Basically I would like to be able to do the following:
- Collocate a namenode, journalnode and zookeeper failover controller on 1 node in the cluster.
- Collocate a standby namenode, journalnode and zookeeper failover controller on another node in the cluster.
- Run a journalnode on another node in the cluster.
- Run datanodes on all other nodes in the cluster.
- Easily scale up and down the number of namenodes, journalnodes and datanodes (along with their collocated components).

There doesn't really appear to be a way to do this in a job specification at the moment, but if we can do something like this, it would be really awesome!

**Comment by armon** [comment]
@F21 This should be specifiable today!

You would group the first set of 3 apps (NN, JN, ZK) in a single "task group". You would run the standby in a second "task group". This ensures those are all co-located together. The other components get their own "task groups" as well.

By default, Nomad applies an anti-affinity to other task groups from the same job to spread them between machines. You can easily scale them up and down by changing the "count" of each task group.

I think the missing piece today is a mandatory anti-affinity to ensure standby and active groups are never co-located, and that is coming.

Hope that helps!

**Comment by F21** [comment]
@armon Would it be possible to set a priority for each task group and set the count to infinity? In the above use-case, I would like to set the standby and active task groups for the name nodes to have a higher priority. Then, I would like to set the datanode task group to have a lower priority and a count of infinity. 

Thus, if new clients are added to the nomad cluster, once the specified amount of name nodes and standby name nodes are launched, data nodes would be automatically launched on the new clients.

**Comment by dancannon** [comment]
@armon Does Nomad attempt to spread tasks between DCs/regions or does it only take into consideration what machine the task has been scheduled on.

I suppose one way to do this would be to create a task per region/DC in a task group but this is not quite as easy to maintain.

**Comment by armon** [comment]
@dancannon Nomad does spread between the datacenters that are specified in the job. A job cannot span multiple regions, so it does not spread between regions.

@F21 You cannot set an infinite count, as that would cause a number of issues. I don't think you even need the complexity the priorities. You can probably just have a single high priority job with the NN and other control nodes, and a separate job with the datanodes.

The goal is to add a "system" scheduler that runs a job on every node. You could use the "system" type job to run a data node with a strict anti-affinity to the nodes running the NN, which would achieve the same result in a much simpler way.

All of this should be possible in the next few releases!

**Comment by F21** [comment]
@armon That sounds great! Looking forward to giving that a spin!

**Comment by dancannon** [comment]
@armon That's great, thank you for getting back to me so quickly.

**Comment by dmayo3** [comment]
Will there be some way of prioritising data affinity for batch scheduling? The kind of workload I'm thinking of would be a continuous stream rather than a single big batch every so often.

**Comment by dadgar** [comment]
`distinct_host` constraint solves the problem raised here.
