### ISSUE TITLE
After rendering the template, the script runs constantly restarts

### ISSUE THREAD

**Issue by Mileshin** [hashicorp/nomad#14734]
Nomad v1.3.5 
I'm trying to set up nginx to reload the config generated from a template:
```
{{- $forbiddenNames := parseJSON `["serviceslanding","webconfigurator"]` -}}
{{ range services -}}
  {{if .Tags | contains "api" -}}
    location /{{ .Name }}/ {
      #proxy_pass http://{{ env `NOMAD_IP_nginxhttp` }}:{{ scratch.Get .Name }}/;
      proxy_pass http://{{ env `NOMAD_IP_nginxhttp` }}:{{ key (print .Name "/http.port") }}/;
      include /etc/nginx/conf.d/proxy.conf;
      proxy_set_header X-Forwarded-Path /{{ .Name }};
   }
  {{- end -}}
{{- end -}}
```
To do this, I set the change_mode = "script" value in the job and add the change_script section.
```
# services
      artifact {
        source      = "http://consul.service.consul:8500/v1/kv/nginx/services.conf.tpl?raw=true"
        ${artifact_headers}
      }
      template {
        source        = "local/services.conf.tpl"
        destination   = "local/services.conf"
        change_mode   = "script"
        change_script  {
          command       = "/usr/sbin/nginx"
          args          = ["-s", "reload"]
          timeout       = "5s"
          fail_on_error = false
        }
      }
```

When the template changes, the script is executed. However, after that it starts to run continuously.

![image](https://user-images.githubusercontent.com/23279846/192826100-82d44744-681f-4245-a5e3-11ec89989d7a.png)

At the same time, the config modification time does not change. This means that the script restarts are not due to a change in the config.

I can't understand why this might be happening. Maybe there are thoughts about this? Maybe I missed something?

Thank you!

**Comment by lgfa29** [comment]
Thanks for the report @Mileshin! 

#14749 should fix this problem by enforcing the [`splay`](https://developer.hashicorp.com/nomad/docs/job-specification/template#splay) timeout value, which defaults to `5s`.

**Comment by Mileshin** [comment]
Thank you very much!
