### ISSUE TITLE
[ui] run an example job via the UI

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#14746]
On the jobs/run route in the UI, give users the same convenience as `nomad job init` gives them from the CLI.

**Comment by ChaiWithJai** [comment]
@philrenaud technically in progress, right? Should we close this because we have the RFC written and larger umbrella ticket:  https://github.com/hashicorp/nomad/issues/15545

**Comment by philrenaud** [comment]
Yep closing in favour of #15545
