### ISSUE TITLE
cluster is in healthy state, but each individual node is reporting different results for `nomad server members`

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#14761]
### Nomad version
Nomad v1.3.5 (1359c2580fed080295840fb888e28f0855e42d50)

### Operating system and Environment details
amazonlnux
3 node cluster
generally healthy state

I just rebooted all the servers (individually).  The cluster never falterd.  I'm not sure if this is related.  The issue may have pre-dated this cluster refresh - but i have no way to tell now.

### Issue
My three nomad servers are reporting different results for `nomad server members` They appear to be showing old, dead servers that are no longer online.

Not only that, they each are showing *different* dead nodes.  The three active nodes, and the leader, are consistent -- hence, the cluster is healthy.  But the old servers don't go away.

This is reflected both on the command line and in the nomad UI.

`nomad system gc` doesn't appear to clean this up.

### Reproduction steps
I'm not sure.  I think these lingering nodes may have predated the cluster refresh - but I honestly can't be sure at this point

#### Expected Result
- the three servers would report the *same* status
- the three servers would report only three active nodes
- `nomad system gc` would remove the dead nodes - and running it once would apply to all three nodes.

#### Actual Result
`nomad server members` pointed at three different server nodes report different result.  same leader though.

```
(03:08 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.11.217:4646 nomad server members
Name                                                  Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
ip-10-30-11-156.eu-central-1.compute.internal.global  10.30.11.156  4648  left    false   3             1.3.5  dc1         global
ip-10-30-11-217.eu-central-1.compute.internal.global  10.30.11.217  4648  alive   false   3             1.3.5  dc1         global
ip-10-30-21-150.eu-central-1.compute.internal.global  10.30.21.150  4648  left    false   3             1.3.5  dc1         global
ip-10-30-21-72.eu-central-1.compute.internal.global   10.30.21.72   4648  alive   true    3             1.3.5  dc1         global
ip-10-30-31-165.eu-central-1.compute.internal.global  10.30.31.165  4648  left    false   3             1.3.5  dc1         global
ip-10-30-31-4.eu-central-1.compute.internal.global    10.30.31.4    4648  alive   false   3             1.3.5  dc1         global
(03:08 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.21.72:4646 nomad server members
Name                                                  Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
ip-10-30-11-217.eu-central-1.compute.internal.global  10.30.11.217  4648  alive   false   3             1.3.5  dc1         global
ip-10-30-21-150.eu-central-1.compute.internal.global  10.30.21.150  4648  left    false   3             1.3.5  dc1         global
ip-10-30-21-72.eu-central-1.compute.internal.global   10.30.21.72   4648  alive   true    3             1.3.5  dc1         global
ip-10-30-31-165.eu-central-1.compute.internal.global  10.30.31.165  4648  left    false   3             1.3.5  dc1         global
ip-10-30-31-4.eu-central-1.compute.internal.global    10.30.31.4    4648  alive   false   3             1.3.5  dc1         global
(03:08 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.31.4:4646 nomad server members
Name                                                  Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
ip-10-30-11-217.eu-central-1.compute.internal.global  10.30.11.217  4648  alive   false   3             1.3.5  dc1         global
ip-10-30-21-72.eu-central-1.compute.internal.global   10.30.21.72   4648  alive   true    3             1.3.5  dc1         global
ip-10-30-31-165.eu-central-1.compute.internal.global  10.30.31.165  4648  left    false   3             1.3.5  dc1         global
ip-10-30-31-4.eu-central-1.compute.internal.global    10.30.31.4    4648  alive   false   3             1.3.5  dc1         global
```

### Nomad Server logs (if appropriate)
none really

### Nomad Client logs (if appropriate)
n/a

**Comment by shoenig** [comment]
I believe `left` servers get removed automatically only if [autopilot](https://www.nomadproject.io/docs/configuration/autopilot#autopilot-stanza) enabled.

You may be able to manually remove them with `nomad server force-leave [options] <node>`, and ensuring the `server_join` configuration is correct on each server.

**Comment by josh-m-sharpe** [comment]
Even if that's true - the inconsistency across servers is still kinda weird, no?

**Comment by josh-m-sharpe** [comment]
Fwiw, force-leave appears to have no effect here:

```
(04:58 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.31.4:4646 nomad server members
Name                                                  Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
ip-10-30-11-217.eu-central-1.compute.internal.global  10.30.11.217  4648  alive   false   3             1.3.5  dc1         global
ip-10-30-21-72.eu-central-1.compute.internal.global   10.30.21.72   4648  alive   true    3             1.3.5  dc1         global
ip-10-30-31-165.eu-central-1.compute.internal.global  10.30.31.165  4648  left    false   3             1.3.5  dc1         global
ip-10-30-31-4.eu-central-1.compute.internal.global    10.30.31.4    4648  alive   false   3             1.3.5  dc1         global
(04:58 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.31.4:4646 nomad server force-leave 10.30.31.165
(04:58 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.31.4:4646 nomad server force-leave ip-10-30-31-165.eu-central-1.compute.internal.global
(04:58 PM) josh@ip-10-30-11-17:~/ctm-deploy (master) NOMAD_ADDR=http://10.30.31.4:4646 nomad server members
Name                                                  Address       Port  Status  Leader  Raft Version  Build  Datacenter  Region
ip-10-30-11-217.eu-central-1.compute.internal.global  10.30.11.217  4648  alive   false   3             1.3.5  dc1         global
ip-10-30-21-72.eu-central-1.compute.internal.global   10.30.21.72   4648  alive   true    3             1.3.5  dc1         global
ip-10-30-31-165.eu-central-1.compute.internal.global  10.30.31.165  4648  left    false   3             1.3.5  dc1         global
ip-10-30-31-4.eu-central-1.compute.internal.global    10.30.31.4    4648  alive   false   3             1.3.5  dc1         global
```

**Comment by tgross** [comment]
Hi @josh-m-sharpe! By way of background, Nomad uses raft to back its consistent state store. But in order for Nomad to put get the raft peers together it uses [serf](https://www.serf.io/), an eventually consistent gossip protocol. Serf isn't necessarily consistent across servers, whereas raft is the fully consistent state you'd expect.

The `nomad server members` command hits a couple different endpoints on the server:
* The [`Status.Members`](https://github.com/hashicorp/nomad/blob/v1.3.5/nomad/status_endpoint.go#L63-L97) RPC gets the list of server members known to _this server's_ serf state.
* The [`Status.Leader`](https://github.com/hashicorp/nomad/blob/v1.3.5/nomad/status_endpoint.go#L25-L41) RPC gets the raft leader, which is shared by all the servers.

So given that background, addressing the expectations you've outlined:

> * `nomad system gc` would remove the dead nodes - and running it once would apply to all three nodes.

The behavior you're seeing around `nomad system gc` is expected: GC only cleans up objects in raft, not in serf. So these servers just aren't part of the data that command covers. The [docs](https://www.nomadproject.io/docs/commands/system/gc) cover the specific objects that get GC'd.

> * the three servers would report the same status
> * the three servers would report only three active nodes

Each server runs its own loop over serf events. (ref [`serf.go#L27-L50`](https://github.com/hashicorp/nomad/blob/v1.3.5/nomad/serf.go#L27-L50)). So different servers having different member lists isn't totally unexpected so long as all the servers (eventually) agree on the up/down status of any member they know about.

Your cluster might have gotten into this state if some of the live servers have already cleaned up (via [`autopilot`](https://www.nomadproject.io/docs/configuration/autopilot#autopilot-stanza) as @shoenig mentioned) one or more of the "left" servers in their local copy. In any case autopilot leaves servers sitting around for quite a while by default (24h I think?) so if you need to clean them up `server force-leave` should do the job.

But I would expect that to get propagated automatically so I'll need to dig into that a bit more into that.

**Comment by josh-m-sharpe** [comment]
Can confirm that as of this morning (2 days later), all three servers are reporting three and only three active servers.  So that's good 👍 

For a tad bit more context - I first noticed this in the Nomad web UI.  We have a load balancer in front of the three nomad servers - which is configured to round robin.  As I was actively rotating the three servers -- (adding 1 to service ; taking 1 out of service) -- and refreshing the page - the list would change unexpectedly.  Some page reloads would have the older servers, others would not.

This was strange an unexpected - and led me to think my cluste refresh was not working correctly. In retrospect, I think it worked fine.  

What I think was happening is the load balancer (configured to roudn robin the clients) was randomly picking a different nomad server and showing whatever it had in serf/raft at the time.

I think(?) this is a common-ish setup.  Maybe?  And as such, maybe nomad should keep this information in sync so that this experience doesn't happen?

**Comment by tgross** [comment]
> What I think was happening is the load balancer (configured to roudn robin the clients) was randomly picking a different nomad server and showing whatever it had in serf/raft at the time.
> 
> I think(?) this is a common-ish setup. Maybe? And as such, maybe nomad should keep this information in sync so that this experience doesn't happen?

That sounds like a likely. I see what you're getting at about how not having serf in sync can be confusing, but it's also not something we can solve directly -- if the information were in sync it'd be in raft in the first place, and not in serf. Serf membership information can't be synchronous.

That being said, this is obviously not a very nice UX. At the very least, making it clear what set of information was eventually consistent could be helpful.

**Comment by josh-m-sharpe** [comment]
Maybe some ideas:

1) a non-leader responded with data from itself rather than polling the cluster or just redirecting to the leader
2) The leader should poll the cluster and compile that information to show in the Nomad UI - thus showing a complete picture of the Nomad cluster, and not a snapshot of the raft/serf protocol happening on that one box.

The 'servers' page is afterall a Nomad interface, Not a raft/serf interface.

**Comment by tgross** [comment]
> The 'servers' page is afterall a Nomad interface, Not a raft/serf interface.

Sure, but it's always a careful balance of exposing a high-level view of the cluster state without obscuring what's really going on under the hood so that operators can discover and fix real problems in the cluster.

It looks like we've got this problem solved for the moment. I'm going to close this issue out but I'll get a discussion going internally about whether we have reasonable options here in terms of UX. Thanks for helping debug this!
