### ISSUE TITLE
Sometimes can't figure out why task deployment does not start

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#14776]
Nomad version 1,4.0 beta

Sometimes if I canche sometinh on the nomad job one task not starts. I see ne allocations no logs. 

After I delete the job and do a nomad system gc then the task comming up..

![image](https://user-images.githubusercontent.com/5046525/193474205-0d9dd6e0-97b6-4537-97d2-8b8d1463a628.png)

**Comment by jrasell** [comment]
Hi @suikast42; are you able to define exactly what `not starts` means here as well as provide some context around what feature request or bug you are reporting?

Sometimes a task may take a while to start as it needs to download the artifact or Docker image to run. You can use `nomad alloc status <alloc_id>` to better understand the situation or navigate to `/ui/allocations/<alloc_id>/<task_name>` within the UI.

**Comment by jrasell** [comment]
Hi @suikast42, as I have heard back from you I am going to close this issue out. If you are still experiencing this issue, please feel free to re-open it with the additional context requested in my previous comment.
