### ISSUE TITLE
Timepoints in x-axis graphs

### ISSUE THREAD

**Issue by wdmeeste1** [hashicorp/nomad#14808]
### Nomad version
1.3.1

### Operating system and Environment details

Ubuntu 20.04

### Issue

In nomad dashboard of a task:

The time x-axis time points are not updated (progressing) in the resouce utilization graphs of CPU and memory while the data itself is updated.

Example:

![image](https://user-images.githubusercontent.com/23402402/194059655-af275ec1-3e27-4e10-9ec0-6e1cd987527a.png)

The time is 14:21 but the x-axis time points are not updated.

#### Expected Result

X-axis time points should be updated

**Comment by tgross** [comment]
Hi @wdmeeste1! That certainly looks like a bug to me. I'm going to mark this for the attention of our web UI experts and they'll follow-up.
