### ISSUE TITLE
UI: services with many tags do not display properly

### ISSUE THREAD

**Issue by gmichalec-pandora** [hashicorp/nomad#14832]
### Nomad version
Nomad v1.4.0+ent (ea16107f7303803f923cfaf96c428b49e1126a2f)

### Operating system and Environment details
Debian 10

### Issue
We have consul services with a fair number of tags. In the UI, when we open the service pane, the tags list does not wrap and continues off the screen

### Reproduction steps
1. Define a service stanza with many tags
2. Open alloc in the ui and click on the service to open the service pane

#### Expected Result
All tags should be readily visible

#### Actual Result

![image](https://user-images.githubusercontent.com/39168929/194403842-687967b1-2606-4a75-8f03-ccbfd28d21ce.png)

**Comment by philrenaud** [comment]
Thanks for the issue @gmichalec-pandora — will get this taken care of right away.

**Comment by philrenaud** [comment]
Hi @gmichalec-pandora  — this is resolved in #14834 and will go out in an upcoming 1.4.x release. Thanks again for bringing it to our attention!

**Comment by gmichalec-pandora** [comment]
wow - what a turnaround! thanks!
