### ISSUE TITLE
ui/clients/id: Allocations arrow back is not rendered.

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#14841]
### Nomad version
1.4.1

### Operating system and Environment details
Google chrome 106.0.5249.91
Firefox

### Issue
Arrow back in allocation table in client view is not visible.

### Reproduction steps
Go to one of the clients in gui and have many allocations. Click the arrow to the right.
![obraz](https://user-images.githubusercontent.com/15679217/194502975-3d07acb4-4265-4df9-aab8-bb2ac8dfed3f.png)
![obraz](https://user-images.githubusercontent.com/15679217/194503138-ac376efd-4675-4616-8616-e78b159dd849.png)
![obraz](https://user-images.githubusercontent.com/15679217/194503047-aa47b15d-0ff0-4c44-bc74-e1e131f4d75e.png)

#### Expected Result
Well, there should be something visible.

#### Actual Result
It's not.

Amazing project, thanks.

**Comment by jrasell** [comment]
Hi @Kamilcuk and thanks for raising this issue. I have been able to reproduce this locally where the back button is not visible but clickable. I'll mark this for our UI engineers can take a look.

Reproduction: used local `nomad agent -dev` command which was then used to run the job specification below. Navigating to the URL `http://localhost:4646/ui/clients/<node_id>` and clicking the right arrow on the allocations table, the back arrow then become invisible but clickable.

```hcl
job "example" {
  datacenters = ["dc1"]
  group "cache" {
    count = 23
    task "redis" {
      driver = "docker"
      config {
        image = "redis:7"
      }
    }
  }
}
```
