### ISSUE TITLE
Kernel parameters using `sysctl` for a Hashicorp Nomad job

### ISSUE THREAD

**Issue by Montana** [hashicorp/nomad#14853]
Hey all,

Nomad says I can set the kernel parameters using `sysctl` for a Docker task like so:

```hcl
config {
  sysctl = {
    "net.core.somaxconn" = "16384"
  }
}
```

This indeed works. But when I tried,

  ```hcl
          sysctl = {
          "net.core.somaxconn" = "16384"
          "net.core.rmem_default" = 134217728
          "net.core.rmem_max" = 134217728
          "net.core.wmem_default" = 134217728
          "net.core.wmem_max" = 134217728
          "vm.max_map_count" = 1000000
        }
```

I'm getting the following error:

```bash
Oct 7 '22 19:30:22 +0530  
Driver Failure  
Failed to start container fa2179c3fbfe0a216e457449cfb72a78e08c0be45f10ba9596004fbfc51e5cac: API error (400):
failed to create shim task: OCI runtime create failed
```
The use case here is trying to run Solana validator as a container in Nomad. Thank you everybody. 

Cheers,
Montana Mendy.

**Comment by jrasell** [comment]
Hi @Montana; that error message is coming from Docker and is quite generic meaning it could be one of a number of issues with the job specification or Docker container itself. Would you be able to post a minimal reproduction example of your job specification, so I could look and test this out locally?

**Comment by jrasell** [comment]
Hi @Montana, as we have not heard back from you I am going to close this issue. If you are still experiencing problems, please re-open this issue or open a new issue with the context request. Thanks.
