### ISSUE TITLE
cleanup: use Go's BasicAuth for parsing Authorization header

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#14874]
In `HTTPServer.parseToken` we have a [custom parser](https://github.com/hashicorp/nomad/blob/v1.4.1/command/agent/http.go#L843) for `Authorization` header. I suspect this pre-dates Go's built in `BasicAuth` helper method(s), and we should look into switching to the standard library implementation.

https://pkg.go.dev/net/http#Request.BasicAuth

**Comment by alessio-perugini** [comment]
:wave: IDK if I misunderstood the issue but I see that we're looking for the `Bearer` token. [rfc6750](https://www.rfc-editor.org/rfc/rfc6750) 
```go
// <Scheme> must be "Bearer"
if strings.ToLower(scheme) == "bearer" {
    // Since Bearer tokens shouldn't contain spaces (rfc6750#section-2.1)
    // "value" is tokenized, only the first item is used
    *token = strings.TrimSpace(strings.Split(value, " ")[0])
}
```
Therefore I suspect the `BasicAuth` is not what we want. Unfortunately, the stdlib doesn't seem to have any helper method for the Bearer authorization. 😢

**Comment by soupdiver** [comment]
I was scrolling through issues with the label `good first issue`.
Is this actually one or just a misunderstanding?

**Comment by shoenig** [comment]
Sorry yeah, I was too optimistic about what the standard lib would do :man_facepalming:
