### ISSUE TITLE
Sorting problem with text filter

### ISSUE THREAD

**Issue by wdmeest** [hashicorp/nomad#14872]
### Nomad version
1.3.1

### Operating system and Environment details

Ubuntu 20.04

### Issue

In nomad dashboard the sorting of the jobs table doesn't work when using a text filter (without text filter it works perfectly).

Example (sort on namespace is not correct):

![image](https://user-images.githubusercontent.com/23402402/195071216-f2bd461c-937d-4fcb-8a88-b4c9bb3a1fd2.png)

The sorting problem is applicable for all columns so not only the namespace column

#### Expected Result
Correct sorting

**Comment by jrasell** [comment]
Hi @wdmeeste1 and thanks for raising this issue. I was able to reproduce this locally with v.1.3.1 and v.1.4.1; I will therefore pass this onto the UI engineers so they can take a look when possible.
