### ISSUE TITLE
Nomad Variables

### ISSUE THREAD

**Issue by Hanmask21** [hashicorp/nomad#14885]
### Nomad version
1.4.1 

### Issue
MISSING NOMAD VAR BLOCK 

The rights are full, but when expanding the task, it cannot find the variable.

`namespace "default" {
  capabilities = ["submit-job","list-jobs","read-job","parse-job","dispatch-job","read-logs"]
   variables {
    path "*" {
      capabilities = ["read"]
    }
  }
}`
<img width="430" alt="image" src="https://user-images.githubusercontent.com/67509466/195429985-e0f1fb79-3d0f-489a-9018-a6708ad54615.png">

**Comment by Hanmask21** [comment]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/67509466/195537945-fb1e8838-4e64-409c-9e04-a484f1cbaa7d.png">

Task used driver podman
Example template:
`template {
        destination = "${NOMAD_SECRETS_DIR}/env.vars"
        env         = true
        data        = <<EOF
{{- with nomadVar "nomad/jobs/registry" -}}
DOCKER_USER = {{.user}}
DOCKER_PASSWORD = {{.password}}
{{- end -}}
EOF
     }`

**Comment by jrasell** [comment]
Hi @Hanmask21 and thanks for the additional information.

In order to make a variable automatically accessible to a job, the variable needs to be written to `nomad/jobs/<jobname>`. In order to scope it down to a task group or group, the path is extended with the relevant name.

In the example you provided, order to make the variable accessible within the job named `job`, the variable would need to be written to `nomad/job/job`. Could you please try updating your variable path, or job name as described and let me know the results?

The [Nomad template docs](https://developer.hashicorp.com/nomad/docs/job-specification/template#nomad-variables) and [variable concept docs](https://developer.hashicorp.com/nomad/docs/concepts/variables) have more information about templates and variables.

**Comment by Hanmask21** [comment]
<img width="201" alt="image" src="https://user-images.githubusercontent.com/67509466/195594193-a6f8e56a-cd0c-4f43-ae50-d1666f39270f.png">
If I want to add global variables that do apply to everyone
 Example in the photo

**Comment by jrasell** [comment]
Hi @Hanmask21, for variables that need to be accessed from multiple jobs you will need to ensure each job gets assigned the correct permissions. The concepts documentation I linked to above goes into detail about how to grant access to shared variable namespaces.

As an example, to provide task `live` within task group `live` and job `job` access to the registry variable path, you could write the following file to your workstation and then run the command `nomad acl policy apply -namespace default -job job -group live -task live job-live-registry-policy ./policy.hcl`.

```
namespace "default" {
  variables {
    path "registry" {
      capabilities = ["read"]
    }
  }
}
```

**Comment by Hanmask21** [comment]
What for? If there are 100 or more work tasks. It will be long and no one will do this, for a large number of tasks

**Comment by Hanmask21** [comment]
As a solution, you can do it the way it's done for vault
<img width="248" alt="image" src="https://user-images.githubusercontent.com/67509466/195600286-3db8f368-3a9c-4fe0-8080-0ce10a77de1c.png">

**Comment by jrasell** [comment]
> What for?

I don't understand what this question is referring to.

> If there are 100 or more work tasks. It will be long and no one will do this, for a large number of tasks.

That's useful feedback and something we will likely discuss internally. That being said, I would expect the creation and control of ACL policies to be controlled by a script or an automated tool like Terraform which would relieve the manual burden.

It's also worth noting the `path` parameter within the ACL policy can contain wildcards and we also have https://github.com/hashicorp/nomad/issues/14764 as an enhancement for the ACL system to make this situation easier in the future.

I am going to close this issue now as I don't believe there is a bug with Nomad variables. If you wish to re-open with any additional information or raise feature requests against Nomad functionality please do so.
