### ISSUE TITLE
[feature] Dynamic configuration of server list

### ISSUE THREAD

**Issue by dedalusj** [hashicorp/nomad#1489]
I am currently trying to setup a nomad cluster on AWS for running batch or HPC style jobs where both servers and clients are inside auto scaling groups.

Specifying a list of servers in the configuration for `start_join`, `retry_join` and `servers` is not very friendly for such dynamic setup. As of version 0.4 Nomad can bootstrap itself using Consul but that simply shifts the problem to setting up a Consul cluster in such dynamic environment.

I would like to propose a third option which is to let user specify an endpoint for fetching the list of server IPs. This would let Nomad servers and clients refresh the list of servers at any moment when required.

I think it would also simplify deployment on AWS since user could have a lambda returning the list of public IPs for the instances in a autoscaling group.

**Comment by jippi** [comment]
if you have a list somewhere, why not have that list i consul and use consul-template to write it out to your configuration?

**Comment by dedalusj** [comment]
First because I don't want to bootstrap a Consul cluster. It's an extra level of complexity that we don't need since we are not doing service discovery.

Second and AWS Lambda could be used to fetch the most updated list of IP for the servers without any extra servers running. In an autoscaling group the IP of the servers could change as EC2 instances go down and come back up again.

Third. Since this is dynamic Nomad could query it at any moment when required without the need to hardcode in the configuration file.

**Comment by dadgar** [comment]
As @jippi has suggested, if you have that endpoint then you can build a simple wrapper that restarts them based on that.

We have decided to solve this problem with Consul and for the vast majority this solution will work seamlessly.
