### ISSUE TITLE
ui: add region identifier to header

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#14893]
When running multiple, unfederated Nomad regions, it can be hard to tell what region you are looking at in the UI without checking additional sources such as the clients page. It could be nice therefore, to have the region identifier you are looking at present within the top panel, potentially alongside the Nomad logo.

**Comment by ChaiWithJai** [comment]
@jrasell Hey buddy! Could you please add a reference image so I can understand the context here?

This may require design exploration, as well.

cc:  @juliezzhou @joshklekamp
