### ISSUE TITLE
Utilise Peering feature with Consul Connect jobs between datacenters

### ISSUE THREAD

**Issue by arion-hjortur-arnthorsson** [hashicorp/nomad#14891]
### Proposal
The newest version of Consul have cluster peering in [beta](https://www.hashicorp.com/blog/consul-1-14-beta-announcing-simplified-service-mesh-deployments)

We would like to use that method to connect workloads in different location via the peering links.

Following the directions [here](https://developer.hashicorp.com/consul/docs/connect/gateways/mesh-gateway/service-to-service-traffic-peers)

We get the following error: "Unsupported argument; An argument named "destination_peer" is not expected here."

### Use-cases
Connect workloads through peerings connection and simplify TLS setup

### Attempted Solutions
Deployed Consul Clusters (v1.13.2 and v1.14.0-beta1) and connected them via peering.
Exported services work fine

**Comment by jrasell** [comment]
Hi @arion-hjortur-arnthorsson and thanks for raising this. The team would need to identify what enhancements and updates are needed to Nomad's Consul integration to be able to use this feature. I'll mark it accordingly.

**Comment by arion-hjortur-arnthorsson** [comment]
The mentioned PR seems to fix the issue we are having.
I very much would like to use peering in Nomad rather than having to port my workloads over to Kubernetes

**Comment by Esity** [comment]
Are there any updates on this one?

**Comment by vvarga007** [comment]
I am waiting on this too. The same feature is needed for the ingress gateway config too.

**Comment by blake** [comment]
The `destination_peer` argument is now supported in the `service -> connect -> sidecar_service -> proxy -> upstreams` block as of [Nomad 1.6.2](https://github.com/hashicorp/nomad/releases/tag/v1.6.2).

**Comment by tgross** [comment]
Thanks @blake!
