### ISSUE TITLE
ephemeral_disk not migrated when stopping and restarting job/alloc

### ISSUE THREAD

**Issue by lostb1t** [hashicorp/nomad#14977]
### Issue

ephemeral_disk not migrated (locally and remote) to new allocation when stopping and starting job/alloc.

It's succesfully migrated to a new allocation when restarting an alloc or redeploying a job. But when stopping and starting an job or allocation as individual steps. The disk is lost.

### Reproduction steps

Stop a job from the UI and then start it again.
or
Stop a allocation from the UI (a new alloc should be auto started)

#### Expected Result

I expect an ephemeral_disk always to be migrated whenever old allocations still exists to migrate from (unless gc't)

#### Actual Result

ephemeral_disk is lost between between start and stop of an job/alloc

### Job file (if appropriate)

```
job "playground" {
  datacenters = ["dc1"]
  type        = "service"

  group "playground" {
    count = 1

    ephemeral_disk {
      migrate = true
      size    = 200
      // sticky  = true
    }

    task "ubuntu" {
      driver = "docker"

      config {
        image = "ubuntu"
        entrypoint = [
          "tail", "-f", "/dev/null",
        ]
      }

      resources {
        cpu    = 300
        memory = 100
      }
    }
  }
}
```

Would be happy to contribute an PR if this is actual unexpected behaviour.

reference to  [#11285](https://github.com/hashicorp/nomad/issues/11285) as docs are unclear on this

**Comment by tgross** [comment]
Hi @sarendsen! What you're seeing is what I'd expect but I can definitely see how it's not obvious and the docs don't help much. 

When an allocation is getting replaced by a new version, the scheduler creates the new Allocation at the same time the old Allocation is getting told to stop. So when the old Allocation is being checked for migrating ephemeral disk, we can see the new Allocation needs to be placed and wait for that to happen.

Whereas when you stop the allocation, we send the instruction to stop. And then, when the Allocation actually stops the client updates the server with that status. That triggers an Evaluation for the scheduler, and the scheduler creates a new Allocation to replace it (if necessary). So by the time that happens, the old Allocation is long gone and we can't do a migration.

I'm not sure it's feasible to solve for this case. If we added a new Evaluation to the stop RPC, the scheduler will still be evaluating the change after the stop has been sent to the client. I do think the documentation around this could be significantly improved however, and I'd be happy to review a PR for it if you'd like.
