### ISSUE TITLE
Filter allocation metrics from statsd metrics

### ISSUE THREAD

**Issue by jshaw86** [hashicorp/nomad#1499]
We would like to have a parameter to toggle off the live allocation metrics and just emit node level metrics to statsd.

Our use case for this is to leverage librato for capacity planning and sending all allocation metrics to librato is costly.

In the future we may like to target specific allocations to emit allocation level metrics out of on a on-demand basis but we could use the command line for those specific cases.

**Comment by diptanu** [comment]
@dadgar had a good idea about making this prefix matched so that the client can publish allocation metrics for certain jobs.

**Comment by jshaw86** [comment]
@diptanu @dadgar yea i think that would work fine.

**Comment by diptanu** [comment]
@jshaw86 For now we have added the tunables `publish_allocation_metrics` and `publish_node_metrics` which will allow you to turn on/off this feature. Nomad Enterprise will support turning off/on metrics for individual or a group of Jobs.
