### ISSUE TITLE
[plugin] Plugin Client does not serialize MountPropagation.

### ISSUE THREAD

**Issue by stswidwinski** [hashicorp/nomad#15014]
### Nomad version
1.4.1

### Operating system and Environment details
Any unix kernel. Centos 8.

### Issue

The exec driver advertises the ability to specify mounts within the configuration:

https://github.com/hashicorp/nomad/blob/v1.4.1/drivers/exec/driver.go#L489

The mounts are defined using the following four properties:

https://github.com/hashicorp/nomad/blob/2aa7e66bdb526e25f59883952d74dad7ea9a014e/plugins/drivers/driver.go#L434-L439

However, the protobuf serialization of the mounts does not respect the mount propagation settings:

https://github.com/hashicorp/nomad/blob/e34fa583f9eade2e77759108cc1b97b33c069e22/plugins/drivers/proto/driver.proto#L557-L567
https://github.com/hashicorp/nomad/blob/e34fa583f9eade2e77759108cc1b97b33c069e22/plugins/drivers/utils.go#L326-L336

Resulting in any mount propagation defaulting to `""` which is translated to `rprivate`:

https://github.com/hashicorp/nomad/blob/e34fa583f9eade2e77759108cc1b97b33c069e22/drivers/shared/executor/executor_linux.go#L812-L835

### Reproduction steps

Attempt to mount anything using the `Mount` configuration and observe that within the private namespace created by `libcontainer` all mounts are `private` independent of the input setting.

#### Expected Result
The mount propagation is respected.

#### Actual Result
The mount propagation is not respected.

### Job file (if appropriate)

**Comment by tgross** [comment]
Hi @stswidwinski! That might also be at the root of https://github.com/hashicorp/nomad-driver-podman/issues/192 Thanks for opening this!

**Comment by lgfa29** [comment]
Closed by #15096
