### ISSUE TITLE
Stop Jobs

### ISSUE THREAD

**Issue by NickJLange** [hashicorp/nomad#15011]
### Proposal
For Periodic Jobs, please allow user-job submissions to report "start" times as well as "stop" times a job. As an example, consider a service which is only up from 05:00 to 22:00 AM Daily. 

### Attempted Solutions
An alternative to the above is to have a "Start" and "stop" job submitted separately - but that requires coordination amongst the scheduler for placement decisions / adds operational risk.

**Comment by schmichael** [comment]
There's an old issue for tracking this here: #1782

Subscribe to it and feel free to add a comment with your specific use case! It's definitely something we'd like to add.
