### ISSUE TITLE
New Task View on Job page alignment seems off

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/nomad#15056]
### Nomad version
```
root@nomad-0:~# nomad version
Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e)
```

### Operating system and Environment details
Ubuntu 20.04

### Issue

When viewing a Job in the UI, the alignment of the new "Task View" for each task under the Recent Allocations table seem to be a bit off. Not sure if this is actually a bug, if not feel free to convert this to a feature request.
![Screen Shot 2022-10-26 at 5 47 50 PM](https://user-images.githubusercontent.com/17223437/198153555-a4db4506-81db-4b78-b062-61d9697f31b6.png)

### Reproduction steps
Run a job with some tasks and open that job in the UI. Ensure the "Show Tasks" option is enabled. 

#### Expected Result
I'm by no means a UI expert so take my suggestion with a grain of salt!

It looks like the tasks were meant to be shown as a hierarchical list, I spent a massive amount of effort to generate the extremely professional rendering of what I would have expected things to look like.
![Screen Shot 2022-10-26 at 6 12 00 PM](https://user-images.githubusercontent.com/17223437/198155879-35ec5fa0-102c-4264-9379-f3466dddcb14.png)

**Comment by lgfa29** [comment]
Thanks for the report @RickyGrassmuck. 

I think this was the original design, but @philrenaud  and @juliezzhou would know better, so I will let them them chime in 🙂
