### ISSUE TITLE
helper package seems to be missing functions from 1.3.4 onwards

### ISSUE THREAD

**Issue by CarbonCollins** [hashicorp/nomad#15074]
### Nomad version
1.3.4 to 1.4.2

### Operating system and Environment details

Go build environment for plugin building

### Issue

From 1.3.4 onwards the `github.com/hashicorp/nomad/helper` go package seems to be missing several helper functions including:

helper.StringToPtr
helper.Int64ToPtr

among a few others and I didn't see a change log entry detailing this change?
have these been accidentally removed or did I just miss a deprecation message?

This also seems to be the case in the go helper package docs here:
https://pkg.go.dev/github.com/hashicorp/nomad@v1.3.3/helper <- the helpers are present
https://pkg.go.dev/github.com/hashicorp/nomad@v1.3.4/helper <- the helpers are no longer present

As some extra info I found this while attempting to debug an issue raised with the USB plugin here: https://gitlab.com/CarbonCollins/nomad-usb-device-plugin/-/issues/29

### Reproduction steps

Within the USB plugin:
1. Update `github.com/hashicorp/nomad` to  `v1.4.2` in the USB plugin dependencies
2. Run `make build` 
3. Get a failed build with several `undefined: helper.StringToPtr` errors

#### Expected Result

When building the USB plugin using `make build` with the latest version of nomad I should get a working build with no other code changes.

#### Actual Result

When building the USB plugin using `make build` with the latest version of nomad as a dependnency I get:

```
# gitlab.com/CarbonCollins/nomad-usb-device-plugin/internal/plugin
internal/plugin/fingerprint.go:217:19: undefined: helper.StringToPtr
internal/plugin/fingerprint.go:220:19: undefined: helper.StringToPtr
internal/plugin/fingerprint.go:223:19: undefined: helper.StringToPtr
internal/plugin/fingerprint.go:226:19: undefined: helper.StringToPtr
internal/plugin/fingerprint.go:229:19: undefined: helper.StringToPtr
internal/plugin/fingerprint.go:234:16: undefined: helper.Int64ToPtr
internal/plugin/fingerprint.go:237:16: undefined: helper.Int64ToPtr
internal/plugin/fingerprint.go:240:16: undefined: helper.Int64ToPtr
internal/plugin/fingerprint.go:243:16: undefined: helper.Int64ToPtr
internal/plugin/fingerprint.go:246:16: undefined: helper.Int64ToPtr
internal/plugin/fingerprint.go:246:16: too many errors
make: *** [GNUmakefile:12: build] Error 2
```

### Job file (if appropriate)

n/a

### Nomad Server logs (if appropriate)

n/a

### Nomad Client logs (if appropriate)

n/a

**Comment by jrasell** [comment]
Hi @CarbonCollins; Nomad v1.3.4 [updated the version of Go used for building to v1.19](https://github.com/hashicorp/nomad/pull/14132). Among a number of features and fixes, this gave Nomad the ability to use [generics](https://go.dev/doc/tutorial/generics) which allowed us to remove the per-type pointer functions for a [generic function](https://github.com/hashicorp/nomad/blob/8c19a1264b385ac948d7d4380af1a8c994708129/helper/pointer/pointer.go#L9-L11).

I think you can either upgrade the tooling used to build the plugin to Go 1.19 and update the function calls to use the new generic function, or create your own helper functions to handle to pointer creation for each type needed. Apologies for causing a little extra work here. While are careful of all code modification, the helper package is not intended to be a general purpose SDK outside the Nomad codebase.

**Comment by jrasell** [comment]
I think the pointer function within the helper package will be very stable and therefore safe to use.
