### ISSUE TITLE
agent syslog always runs at NOTICE level

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#15087]
The rarely-used [`enable_syslog`](https://developer.hashicorp.com/nomad/docs/configuration#enable_syslog) configuration emits Nomad agent logs to a syslog interface. While debugging a problem for an internal user, I noticed that they were only getting high-level logs. When we configure syslog at [`command.go#L478`](https://github.com/hashicorp/nomad/blob/v1.4.2/command/agent/command.go#L478) we set the log-level to NOTICE, which means even if the agent is set to log at debug, only NOTICE-level and below will actually get emitted on the syslog interface.

(Note this is entirely unrelated to any allocation logs, which are covered under other open issues.)

**Comment by sharmaansh21** [comment]
Hi @tgross Could I pick this issue?

**Comment by jrasell** [comment]
Hi @sharmaansh21; we do not have a formal way to assign this issue to you, but we are not currently working on it internally, so please feel free to pick this issue up. If you have any questions, please do not hesitate to reach out to us via this issue. Thanks for showing interest!

**Comment by tgross** [comment]
Fixed by #15625 and will ship in the next regular release of Nomad.
