### ISSUE TITLE
UI: CPU Scale is wrong.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad#15098]
### Nomad version
1.4.2

### Operating system and Environment details
Ubuntu

### Issue
<img width="574" alt="Screenshot 2022-11-01 at 10 12 34 PM" src="https://user-images.githubusercontent.com/19410501/199288619-411fdfde-810d-49de-afe5-161c46698a90.png">

### Reproduction steps
Run a job

#### Expected Result
The scale should be coherent with the tooltip.

**Comment by jrasell** [comment]
Hi @blmhemu and thanks for reporting this. The screenshot does look incorrect, so I will mark this so that the UI engineers can take a deeper look.

**Comment by philrenaud** [comment]
Hi @blmhemu — thanks for raising this issue! It's been fixed as of #15381 , and you should see it in an upcoming Nomad release.
