### ISSUE TITLE
Parsing of df output fails on Linux when filesystem paths are very long

### ISSUE THREAD

**Issue by aldergren** [hashicorp/nomad#151]
I was testing nomad in my Linux environment and I was unable to launch the agent:

    $ nomad agent -dev
     ==> Starting Nomad agent...
     ==> Error starting agent: client setup failed: fingerprinting failed: Failed to parse `df` output; expected at least 4 columns

I checked the output from df, and this happens because df on Linux adds breaks up the output when filesystem paths are very long:

```
$ df -hl
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_local-lv_root
                       69G   21G   45G  33% /
tmpfs                  12G  284K   12G   1% /dev/shm
/dev/sda1             504M   70M  409M  15% /boot
```

It seems this can be fixed by adding the -P (portability) flag to df on Linux. I'll attempt to provide a PR which fixes this.

**Comment by aldergren** [comment]
Also, this behaviour seems to have been [removed](https://github.com/coreutils/coreutils/commit/99679fff629f4a624f4fe7a67335c6e90533afc2) from coreutils/df some time ago -- but it does prevent me from running nomad on a default install of CentOS 6.7. It works fine on CentOS 7.

**Comment by rvm2015** [comment]
+1 This works on CentOS 6 if you use standard partitions instead of LVM (LVM creates the log filenames)
