### ISSUE TITLE
[UI] Add namespace to breadcrumb navigation

### ISSUE THREAD

**Issue by wdmeest** [hashicorp/nomad#15169]
### Proposal

Add namespace name to breadcrumb navigation (or another visible location)

![image](https://user-images.githubusercontent.com/23402402/200304700-dce81126-997c-49e6-a092-9afc7d1f86c0.png)

### Use-cases

We have different jobs with the same name but in a different namespace (example: job "intranet" we have in namespace "testing", "development" and "production"). You open the desired job in the specific namespace, do your stuff and leave the web page open. When returning to the web page (after a certain period of time) for example to restart the allocation, you want to be certain that you are restarting the allocation in the correct namespace, so not accidently restarting the production allocation.

### Attempted Solutions

\

**Comment by tomiles** [comment]
Agreed, once you navigate to the task group level or deeper there is no way to tell what namespace the job is based on the UI, navigating back to the job level.

**Comment by jrasell** [comment]
Hi @wdmeest and thanks for raising this idea that sounds really useful. I'll mark this so that our UI engineers and designers can take a further look.

**Comment by ChaiWithJai** [comment]
Hey, @wdmeest! Thanks for raising this idea. We've started discussion internally regarding how to resolve this issue. We are doing to do our best to find ways to resolve this issue while maintaining the integrity of our design.

Please feel free to join the [conversation](https://github.com/hashicorp/nomad/pull/15261) or file any new tickets for challenges or even tiny papercuts in the UI. We'd love to make your experience with the Nomad UI better!

**Comment by wdmeest** [comment]
@ChaiWithJai  Added a possible solution to the conversation: https://github.com/hashicorp/nomad/pull/15261#issuecomment-1319686548
