### ISSUE TITLE
Nomad Client leaks goroutines.

### ISSUE THREAD

**Issue by stswidwinski** [hashicorp/nomad#15179]
### Nomad version
1.4.2

### Operating system and Environment details
Unix

### Issue
Nomad client leaks goroutines under normal operation, at least 1 goroutine per task. The exact reason why:

1. When one creates a task, one creates a context to await for the exit of the task and write the exit code

https://github.com/hashicorp/nomad/blob/main/plugins/drivers/client.go#L190

This context is never cancelled unless the parent contexts are cancelled or done.

2. The parent contexts are very long lived. The plugin context has the lifetime of the plugin itself:

https://github.com/hashicorp/nomad/blob/main/plugins/drivers/client.go#L32

The other one has the lifetime of... forever

https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/task_runner.go#L623

Because none of them are ever cancelled we leak goroutines. The goroutine leaked is started here:

https://github.com/LK4D4/joincontext/blob/master/context.go#L33

### Reproduction steps

See above. Run any tasks in a tight loop. It is also relatively easy to test by restarting the plugin and observing that all of the goroutines are freed as a result.

**Comment by jrasell** [comment]
Hi @stswidwinski and thanks for raising this issue along with a PR. I see that Seth has assigned himself as reviewer on the PR, therefore I will assign this to him also to complete the loop.

**Comment by shoenig** [comment]
Closed by https://github.com/hashicorp/nomad/pull/15180
