### ISSUE TITLE
Nomad fails to run a container with Docker-CE installed on Windows

### ISSUE THREAD

**Issue by seabopo** [hashicorp/nomad#15181]
### Nomad version
1.4.2 (and several earlier versions)

### Operating system and Environment details
- Windows Server 2019
- Docker CE installed based on the script provided by Microsoft: [Prep Windows for containers](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1)

### Issue
Docker CE doesn't work with Nomad's Windows Task driver (error details below).

Currently there isn't an open-source Container Runtime for Windows supported by Nomad.
Docker Enterprise Edition has been sold to Mirantis and requires licensing for any use. 
Nomad's PodMan and Containerd drivers are not supported on Windows.

Docker CE is still free for use and is supported on Windows Server, so it seems like the logical choice for dev/test scenarios, but it doesn't work with Nomad's Windows Task driver (error details below).

### Reproduction steps

Using the Mirantis Container Runtime (Docker Enterprise) runtime based on [Prep Windows for containers](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1) works as expected, just as the previous Docker Enterprise runtime did.

Using the Docker CE/Moby runtime based on [Prep Windows for containers](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1) does not work as expected, and produces an error when Nomad attempts to run the image.

The image is pulled but the following error occurs:

Time	Type	Description
Nov 07, '22 16:04:39 -0600	Killing	Sent interrupt. Waiting 5s before force killing
Nov 07, '22 16:04:37 -0600	Alloc Unhealthy	Unhealthy because of failed task
Nov 07, '22 16:04:37 -0600	Not Restarting	Error was unrecoverable
**Nov 07, '22 16:04:37 -0600	Driver Failure	failed to create container: API error (400): invalid CapDrop: unknown capability: "CAP_NET_RAW"**
Nov 07, '22 16:03:46 -0600	Driver	Downloading image
Nov 07, '22 16:03:46 -0600	Task Setup	Building Task Directory
Nov 07, '22 16:03:46 -0600	Received	Task received by client

The image is 'seabopo/traefik:nanoserver-1809', which is verified working with the Docker Enterprise runtime installed.

There are also no logs available in the Nomad allocation logs when the Docker CE runtime is installed, but they do appear for the Docker Enterprise (Mirantis Container Runtime) installation.

**Comment by shoenig** [comment]
Hi @seabopo can you help clarify - is the container you are trying to launch a Windows container or Linux container? If the later, are you using WSL 1 or 2?

**Comment by seabopo** [comment]
Oops!, sorry. We are using only Windows Containers.

Thanks!

**Comment by nickwales** [comment]
It appears the change documented here may have had an impact: https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#nomad-1-1-0-rc1-1-0-5-0-12-12

Adding the plugin configuration to the Nomad client to re-add the capabilities as per the snippet allows the job to run.

**Comment by seabopo** [comment]
I’ll give it a try when I can.

It said this as well


This only affects Nomad clients running Linux, with tasks using bridge networking and one of these task drivers, or third-party plugins which relied on the shared Nomad executor library.

Thanks Nick!


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by seabopo** [comment]
Nick provided me the following plugin configuration for the nomad-conf.hcl file which has solved the issue and allows the container to be started by Docker CE on Windows Server 2019. 

Thanks Nick!

```
plugin "docker" {
  config {
    allow_caps = [
      "CHOWN", "DAC_OVERRIDE", "FSETID", "FOWNER", "MKNOD",
      "SETGID", "SETUID", "SETFCAP", "SETPCAP", "NET_BIND_SERVICE",
      "SYS_CHROOT", "KILL", "AUDIT_WRITE", "NET_RAW",
    ]
  }
}
```


The patch notes provided by Nick above state: 

```
This change is limited to docker, exec, and java driver plugins. It does not affect the Nomad server. This only affects Nomad clients running Linux, with tasks using bridge networking and one of these task drivers, or third-party plugins which relied on the shared Nomad executor library.
```
However, we are running in Windows / Host mode. 

We'll have to look at the security implications at some point, but this is an acceptable work around for now. 

Thanks!

**Comment by gulducat** [comment]
Re-opening as we've encountered this issue now too internally, and it's pretty easy to replicate in CI.  It occurred when running our Docker driver tests on newer Windows 2019 (or 2022) CI runners instead of Windows 2016.

Ostensibly it should be fine to "allow" (not drop) these Linux-specific capabilities on Windows, but we'll need to evaluate that more fully before possibly making it the default.

**Comment by dekimsey** [comment]
When we ran into this during #17103 we identified a difference between our docker implementations. Note both tests were executed on Windows 2019:

On CircleCI, docker runtime is provided by Mirantis 19.03.19 (works):
<details>

```
Client: Mirantis Container Runtime
 Version:           19.03.19
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5b7ee53
 Built:             10/28/2021 15:58:14
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.19
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       c6d6911d2e
  Built:            10/28/2021 15:57:13
  OS/Arch:          windows/amd64
  Experimental:     false
```
</details>
 
On GitHub, container runtime provided by Docker CE 23.0.4 (fails):

<details>
```
Client:
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:31:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.24)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:29:12 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```
</details>

**Comment by pkazmierczak** [comment]
Hey @seabopo and others in the thread: a fix for this has just been merged into `main` and will land in the next point release. Thanks for reporting!
