### ISSUE TITLE
Clarify bridge network isolation

### ISSUE THREAD

**Issue by MikeN123** [hashicorp/nomad#15187]
### Proposal

I want to suggest to clarify the documentation on bridge network isolation and/or isolate bridge networks by default.

The [current documentation](https://developer.hashicorp.com/nomad/docs/job-specification/network#network-modes) says:

> When the network stanza is defined with bridge as the networking mode, all tasks in the task group share the same network namespace. [...] Tasks running within a network namespace are not visible to applications outside the namespace on the same host.

But looking at the actual configuration (Nomad latest, Consul latest, Connect enabled, no ACLs) I noticed that:

- All tasks share one bridge under `172.26.64.1/20`
- Forwarding is globally allowed to this bridge, looking at iptables rules I see things like:
```
-A FORWARD -m comment --comment "CNI firewall plugin rules" -j CNI-FORWARD
-A CNI-FORWARD -m comment --comment "CNI firewall plugin admin overrides" -j NOMAD-ADMIN
-A NOMAD-ADMIN -d 172.26.64.0/20 -o nomad -j ACCEPT
```

I was able to connect between tasks on the same host (assuming they bind to `0.0.0.0`) and was able to connect from another machine to the tasks running in a network namespace (assuming they bind to `0.0.0.0` and pointing to the Nomad box as the gateway for the bridge IP range).

This was not really clear from the docs to me and I had expected default firewalling between the bridge network and the outside world to be in place.

Of course, most of this is resolved by binding to `localhost`, or possibly by putting my own firewalling rules in place. But I don't want to break anything.

I think at least the docs could be clarified so it does not suggest that tasks are entirely invisible to applications outside of the namespace, because as long as you know the internal interface IP address of the task it can be reached. Another option would be to actually firewall this from the outside world and between task groups, but I have no idea what the consequences of that would be.

**Comment by jrasell** [comment]
Hi @MikeN123 and thanks for raising this issue with some great context and information. The concepts documentation section could certainly benefit from having a network section which goes into details about each network mode, providing the kind of information you mention.
