### ISSUE TITLE
Issues with Volumes table on the "Storage" page on narrower windows

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/nomad#15207]
### Nomad version
v1.14.2

### Operating system and Environment details
Ubuntu 22.04

### Issue

When the windows `innerWidth` gets narrower than about 1200px, the table body stops resizing with the contents going off screen. Once off-screen, there is no way to scroll the page leaving the information in the table that's off screen inaccessible without widening the window.

Example when width > 1200px
![Screen Shot 2022-11-10 at 1 17 54 PM](https://user-images.githubusercontent.com/17223437/201187069-da08551f-e985-47da-9390-19bb4c132934.png)

Example when width < 1200px
![Screen Shot 2022-11-10 at 1 18 15 PM](https://user-images.githubusercontent.com/17223437/201187221-f325cefd-6027-4d52-9b59-4ad7edfe1e61.png)

### Reproduction steps
1. Add some volumes to a nomad cluster
2. Navigate to the Storage page (with the volumes tab selected)
3. Start resizing your window making it more narrow until the contents start overflowing
  
#### Expected Result
If the contents of the table do have to overflow, the page should at least facilitate horizontal scrolling to bring the overflow into view.

Ideally, it would be nice if at a certain width, the table would rearrange itself to a more vertical layout and possibly have each volume entry become a collapsible item with just the volume name showing until it's clicked where it would expand downward showing the rest of the details.

#### Actual Result
The content flows off screen (with no horizontal scrolling ability) until the window is resized to fit the table again.

**Comment by jrasell** [comment]
Hi @RickyGrassmuck and thanks for raising this issue. I will pass this to our UI engineers for investigation.

**Comment by ChaiWithJai** [comment]
Hey! Should be [resolved](https://github.com/hashicorp/nomad/pull/15246) now.
