### ISSUE TITLE
artifacts automatically extracting

### ISSUE THREAD

**Issue by gmichalec-pandora** [hashicorp/nomad#15226]
### Nomad version
1.4.2

### Operating system and Environment details
debian buster

### Issue
we noticed after upgrading our clients from 1.1.4 -> 1.4.2, that the behavior of the `artifact` stanza changed. In our job, we fetch an tar file. In the old nomad, the tar file would simply be downloaded to the target directory, but it seems that in the new version, the tar is also automatically extracted.
The workaround is to either update the job code to expect an already-extracted tar, or add the following to your artifact stanza:
```
  options {
    archive = false
  }
```

It seems that either the default behavior should be changed to match what was previous, or a note should be added to the upgrade guide.

Thanks!

**Comment by tgross** [comment]
Hi @gmichalec-pandora! This was a bug fixed in Nomad 1.2.4, which you can find in the [changelog](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#124-january-18-2022)

**Comment by tgross** [comment]
Looks like this is resolved, so I'm going to close it out.
