### ISSUE TITLE
allow node drain to block on batch allocs

### ISSUE THREAD

**Issue by dvusboy** [hashicorp/nomad#1523]
It would be useful to support letting `batch` tasks finish when `node-drain` is enabled on a node. This can be handled with a new flag to `nomad node-drain`. When present it would:
- block new allocations to the node
- relocate `service` tasks to other available nodes
- terminate `system` tasks on the node

**Comment by olenm** [comment]
Do you mean to have 3 flags for `node-drain` which would allow the manual triggering of the bullet-points you listed?

**Comment by dvusboy** [comment]
Not really, I believe `node-drain` already does all 3 (I assume it does not "relocate" `system` tasks) actions and also relocate `batch` tasks. I'd like the flag to cause `node-drain` to **only** do these 3 actions, suppressing the relocation of `batch` tasks.

**Comment by stongo** [comment]
Is this being worked on? We are very motivated to add this feature but don't want to duplicate any efforts if this is already a work in progress. If not already in progress, we would most likely be willing to dedicate some engineering time to add this feature.

**Comment by DanToml** [comment]
Hey @dadgar,

I have a WIP patch that implements this feature for our deployment needs - But I'd like some opinions on how best to implement the UI for this in a way that works for the project itself.
How would you best want to expose this to users, only expose draining batch jobs, or also allow waiting for services?

**Comment by dadgar** [comment]
@DanToml Hey! So this is pretty good timing as @schmichael will be working on our next generation node draining strategies as part of Nomad 0.8! I am sure he would love to see your implementation so maybe linking the branch here would be a good start.

**Comment by DanToml** [comment]
@dadgar Hey - The configurable version of our original hack patch is here: https://github.com/circleci/nomad/commit/ddb347a2d37751ee38dff2b2342a8a863039a856

**Comment by DanToml** [comment]
Relatedly - I'm not super sure what drain options make sense, outside of batch/(none|all) - I haven't used the services component of nomad, so I'm not sure of their mechanics.

**Comment by tgross** [comment]
Doing a little bit of issue cleanup and noticed this one has been long-done. From the [`nomad node drain` docs]:
> Allocations for batch and sysbatch jobs will wait until they complete or the drain's deadline is reached, whichever comes first. These allocations will not be replaced.
