### ISSUE TITLE
UI: respect original text case (don't force text-transform: uppercase) on service tags

### ISSUE THREAD

**Issue by Davasny** [hashicorp/nomad#15264]
### Nomad version
Output from `nomad version`

```
Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e)
```

### Operating system and Environment details
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Issue

Nomad UI sets `text-transform: uppercase` on tags when backend send normal values without forcing uppercase.

### Reproduction steps

Run docker-driven job with any tag and go to nomad UI to see tags

![image](https://user-images.githubusercontent.com/25726866/202167547-8636633f-c74f-4c9e-9a7c-f00b5302ac62.png)

#### Expected Result

UI shouldn't force uppercase on tags.

Nomad UI 1.3.5:
![image](https://user-images.githubusercontent.com/25726866/202168629-fdbfca45-5054-40c7-9176-b799ab9e5c35.png)

#### Actual Result

UI forces uppercase on tags

### Job file (if appropriate)

```
job "uppercase_test" {

  datacenters = ["dc1"]
  type = "service"

  group "app" {
    count = 2

    network {
      port "http" {
        to = 8000
      }
    }


    service {
      name = "webapp"
      tags = ["traefik.http.routers.http.rule=Path(`/`)"]
      port = "http"

      check {
        name     = "alive"
        type     = "http"
        path     = "/"
        interval = "10s"
        timeout  = "2s"
      }
    }


    restart {
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "fail"
    }

    task "server" {
      driver = "docker"

      config {
        image = "mnomitch/hello_world_server"
        ports = ["http"]
      }

      env {
        MESSAGE = "Hello World!"
      }
    }
  }
}
```

**Comment by jrasell** [comment]
Hi @Davasny and thanks for raising this issue with great context and a reproduction which I was able to run locally and see the bug you have described. I will pass this over to our UI engineers who will be able to take a closer look.
