### ISSUE TITLE
Java driver: GraalVM not detected

### ISSUE THREAD

**Issue by sycured** [hashicorp/nomad#15270]
### Nomad version
Nomad v1.4.2 (039d70eeef5888164cad05e7ddfd8b6f8220923b)

### Operating system and Environment details
Oracle Linux 9 on Oracle Cloud - AARCH64

### Issue
After installing GraalVM on the system and checked that every users can execute `java -version`, I restarted nomad but it's not detecting it.

### Reproduction steps
1. Nomad running using its user (nomad)
2. Download GraalVM Java 17: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.3.0
3. Install it in `/usr/lib/jvm` like
```bash
[root@node5 jvm]# pwd
/usr/lib/jvm
[root@node5 jvm]# ll
total 4
lrwxrwxrwx.  1 root root   24 Nov 16 18:55 graalvm -> graalvm-ce-java17-22.3.0
drwxr-xr-x. 10 root root 4096 Nov 16 18:55 graalvm-ce-java17-22.3.0
```
4. Create the profile conf: /etc/profile.d/java.sh
```bash
PATH="/usr/lib/jvm/graalvm/bin:$PATH"
```
5. Adding it to alternatives
```bash
alternatives --install /usr/bin/java java /usr/lib/jvm/graalvm/bin/java 0
```
6. Log back as normal user and testing it
```bash
[opc@node5 ~]$ which java
/usr/lib/jvm/graalvm/bin/java
[opc@node5 ~]$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

sudo -u nomad java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```
7. Restart nomad
#### Expected Result
On the webpage, having java Detected Yes

#### Actual Result
java Detected No

**Comment by shoenig** [comment]
Hi @sycured, I believe `/etc/profile.d` is only sourced on user logins; to set it in the context of the Nomad agent you should use something like systemd `Environment` parameters

https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service

Can you give that a try?

**Comment by sycured** [comment]
If I tried running nomad in root and it found java

So, I need to find the correct way to grant nomad some capabilities without running it as root… for example, raw_exec works with nomad user and it's the same for podman in rootless

**Comment by shoenig** [comment]
It should be possible to do that @sycured (although as the issue and docs suggest, _technically_ not supported). One thing that might be useful to do is run a trivial job that just runs the `env` command, so you can exactly see what the environment variables are set to from the perspective of the task runner.

**Comment by tgross** [comment]
I'm going to close this issue as it was resolved by running in a supported configuration. But the `Environment` field in the systemd unit file would certainly be the correct way to solve this as well. If you'd like to contribute to the community's knowledge around what it takes to run as rootless Nomad agents, we'd welcome contributions to #13669.
