### ISSUE TITLE
Fetch Artifacts from consul kv or nomad variables

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#15296]
### Proposal
Nomad artifact stanza accpets currently only an url. It could be very convenient to store a template in a kv store like consul or nomad variable and fetch it from there. This reduce the need of a custom ftp server. 

### Use-cases
Templating huge config files. 

### Attempted Solutions
Use consul and/or nomad as kv for templates like kubernetes ConfigMap

**Comment by jrasell** [comment]
Hi @suikast42; the [template job specification block](https://developer.hashicorp.com/nomad/docs/job-specification/template) does exactly what you're looking for here. It can be used to fetch [variables from Nomad](https://developer.hashicorp.com/nomad/docs/job-specification/template#nomad-variables), [KV entries from Consul](https://developer.hashicorp.com/nomad/docs/job-specification/template#consul-kv), and is backed by [consul-template](https://github.com/hashicorp/consul-template) which has a [large array of functionality available](https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md#templating-language). It also supports templating via [go text/template](https://pkg.go.dev/text/template) syntax.

**Comment by suikast42** [comment]
Thanks for fast response. Ok  I missed that point in the docu. 

This part reads the themplate from a nomad var am I right?  

``` hcl 
template {
  data        = <<EOH
{{ range nomadVarList "path/to/filter" }}
  {{ . }}
{{ end }}
}
EOH
}
´´´

**Comment by jrasell** [comment]
Hi @suikast42, yes that looks correct. I would also suggest taking a read through the [variables concepts documentation](https://developer.hashicorp.com/nomad/docs/concepts/variables) which has great details about accessing variables securely.

**Comment by suikast42** [comment]
I have a lillte issue with the templating in nomad varibales. 

I put a yaml file with the content 

```yml
taskname : ++  env  "NOMAD_TASK_NAME"  ++
```

I expect that the template bvelow renders the env var after allocation. The file is captured an mounted in docker container as expected but the env var is not rendered. 

```hcl
      template {
        change_mode   = "restart"
        destination = "local/test.yml"
        right_delimiter = "++"
        left_delimiter = "++"
        data        = <<EOH
        ++ with nomadVar "{{nomad_job_path}}"  ++
          ++ .test_config++
         ++ end  ++
        EOH
        }
```

This if I template the file from an artifact then it renders the env var. 
Did I miss something ?  

```hcl
           artifact {
             source      = "<my uri>/test.yaml"
             mode= "file"
             destination = "local/test.tpl"
           }
            template {
              change_mode   = "restart"
              right_delimiter = "++"
              left_delimiter = "++"
              source        = "local/test.tpl"
              destination = "local/test.yaml"
            }
```
