### ISSUE TITLE
Nomad should wait with cleaning docker images for faster startup times

### ISSUE THREAD

**Issue by bsphere** [hashicorp/nomad#1530]
### Nomad version

0.4
### Operating system and Environment details

CoreOS stable
### Issue

Nomad removes docker images when tasks are stopped, but in case the task is restarted (e.g. consul-template update), startup times are wait too long because it pulls the images again.

Maybe Nomad can wait for some time before cleaning images to improve startup times.

**Comment by a86c6f7964** [comment]
this could also help with some of the docker race conditions that make cleaning up the images break docker due to docker bugs.

**Comment by diptanu** [comment]
We will most likely solve this when we introduce artifact cache in the Nomad client. Docker containers or any other binaries would be downloaded and removed if available disk space is low and not in use.

Docker images are currently managed by the docker daemon and live in `/var/lib/docker/`(the path is distro specific) and the disk space used by docker images are not accounted under the allocated disk space to a running allocation.

**Comment by dbresson** [comment]
This enhancement will break the ability to update to a new revision of the same image tag.

**Comment by a86c6f7964** [comment]
@dbresson see #639 I think you are mentioning that you would like to be able to restart a service and get a image even though the tag is the same, this is currently not supported, and you should not rely on this behavior. With #639 done then whatever flag is used to notify the client that it should always pull the latest image from the registry would make sure that this issue does not break the behavior you are talking about.

**Comment by dadgar** [comment]
Hey this was fixed in 0.5.5 and made more robust in 0.5.6
