### ISSUE TITLE
Clarification on Nomad's Built-in Service Discovery When Tasks Fail or Get Moved

### ISSUE THREAD

**Issue by victorstewart** [hashicorp/nomad#15336]
going to use Nomad's built in service discovery at the start before it's necessary to run a full Consul cluster.

but had some concerns....

1) imagine a programs crashes, will it be brought up again on the same machine? thus the pre-existing IP provided to its friends would still be correct

2) what if Nomad migrates a program to a different machine, how will the programs that need to connect to it know about the new ip?

obviously with Consul we could just ping it to confirm the target address

**Comment by SamMousa** [comment]
I think the idea is you use a template to inject the current location.
When a rendered template changes you can notify the container: https://developer.hashicorp.com/nomad/docs/job-specification/template#change_mode

**Comment by jrasell** [comment]
Hi @victorstewart.

> imagine a programs crashes, will it be brought up again on the same machine? thus the pre-existing IP provided to its friends would still be correct

If an allocation fails, the replacement allocation will be schedule taking into account any [job specification constraints](https://developer.hashicorp.com/nomad/docs/job-specification/constraint) configured and other factors. The [scheduling concepts page](https://developer.hashicorp.com/nomad/docs/concepts/scheduling) has more information if you're interested.

When using Nomad service discovery, the Nomad client will manage service registrations based on the state of allocations it is running. If an allocation fails and is reschedule on a different client, Nomad will automatically deregister the services for the failed allocation, and register new entries for the new allocation.

> what if Nomad migrates a program to a different machine, how will the programs that need to connect to it know about the new ip?

As @SamMousa points out, the Nomad job specification supports [template blocks](https://developer.hashicorp.com/nomad/docs/job-specification/template) which allow, among other functions, the lookup of [Nomad services](https://developer.hashicorp.com/nomad/docs/job-specification/template#nomad-services). When a service registration entry is changed, the template is re-rendered and a signal sent to your task. Ideally, your application could react to SIGHUP and reload the service registration information as required.

I hope this helps.

**Comment by victorstewart** [comment]
thanks all amazing news! love nomad more by the day.
