### ISSUE TITLE
parse API endpoint returns error: Invalid single-argument block definition

### ISSUE THREAD

**Issue by jrnijboer** [hashicorp/nomad#15386]
### Nomad version
Output from `nomad version`
Nomad v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

### Operating system and Environment details
Linux: ubuntu 

### Issue
I'm trying to convert my nomad job (written in HCL) to JSON so I can submit my job to the create job api endpoint, which only accepts JSON. I can't get this conversion to work and even the sample payload from https://developer.hashicorp.com/nomad/api-docs/jobs#sample-payload-1 does not work. When calling the endpoint I get an error:  _Invalid single-argument block definition; A single-line block definition must end with a closing brace immediately after its single argument definition._

### Reproduction steps
```
# run nomad agent: 
nomad agent -dev

# create payload file:
cat <<EOF > payload.json
{
    "JobHCL": "job \"example\" { type = \"service\" group \"cache\" {} }",
    "Canonicalize": true
}
EOF
# call parse endpoint with payload.json
curl --request POST --data @payload.json  http://localhost:4646/v1/jobs/parse
```
#### Expected Result
Expected result would probably be the job file converted to json. There might be something wrong with the parse endpoint, or the sample payload on the documentation is incorrect. Either way, I can't convert my HCL job to JSON using the API

#### Actual Result
an error: _input.hcl:1,34-39: Invalid single-argument block definition; A single-line block definition must end with a closing brace immediately after its single argument definition._

### Job file (if appropriate)
just following the steps on https://developer.hashicorp.com/nomad/api-docs/jobs#parse-job
Also, here's my actual job, which I can convert to JSON using the nomad binary with ('nomad job run -output example.nomadjob.hcl') but not using the http API.

```
job "example" {
    datacenters = ["dc1"]
    type = "batch"
    namespace = "mynamespace"

    constraint {
        attribute = "${attr.unique.hostname}"
        operator = "regexp"
        value = "docker.+"
    }

    periodic {
        cron = "*/15 * * * *"
        prohibit_overlap = true
        time_zone = "Europe/Amsterdam"
    }

    vault {
        policies = ["my-vault-policy"]
    }

    group "containers" {
        task "runcontainer" {
            driver = "docker"
            config {
                image = "hello-world"
            }

            template {
                data = <<EOD
APPROLE = "{{ key "settings/example/APPROLE" }}"
EOD
                destination = "local/variables.txt"
                env = true
            }

            template {
                data = <<EOD
{{ with secret "secrets/data/myvault" }}
PASSWORD = "{{.Data.data.PASSWORD}}"
{{ end }}
EOD
                destination = "secrets/secrets.txt"
                env = true
            }
        }
    }
}
```

### Nomad logs (if appropriate)
This is the output from the nomad agent, it's running in dev mode so it's client as well as server
_[DEBUG] http: request failed: method=POST path=/v1/jobs/parse error="input.hcl:1,34-39: Invalid single-argument block definition; A single-line block definition must end with a closing brace immediately after its single argument definition." code=400_

**Comment by lgfa29** [comment]
Hi @jrnijboer 👋 

Thanks for the report, I believe this is poor documentation in our part...the example is likely old and only works with the previous HCLv1 parser. The new v2 parser is more strict and requires you to include line breaks (hence the error ` Invalid single-argument block definition`). You can switch parsers using the `HCLv1` argument which...was also undocumented 🤦 

I've opened #15387 to address these problems and also included a handy `jq` command to generate proper JSON payloads:

```bash
jq -Rsc '{ JobHCL: ., Canonicalize: true }' example.nomad > payload.json
```

Here's a preview of the updated docs: https://nomad-git-docs-job-parse-hashicorp.vercel.app/nomad/api-docs/jobs#parse-job

Give this a try and let me know if you're still having problems 🙂

**Comment by jrnijboer** [comment]
Thank you for your reply @lgfa29 , I think I've got it running now and the documentation explains it a lot better now. Also your suggestion for the jq command was very helpful.

This issue can be closed now, have a good weekend 👋
