### ISSUE TITLE
Teplatiing from nomad vairables not works

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#15385]
### Nomad version
v 1.4.3

Create a file test.txt with content

```yaml
# This should be interpolated ->  My task name is ++  env "NOMAD_TASK_NAME"  ++
```

1. Upload this to a ftp server
2. Create a nomad variable with the content of the file 
```shell
 nomad var put -force nomad/jobs/test \
 test_var="$(cat test.txt)"

```

```hcl
   artifact {
     source      = "https://<my ftp server>/test.txt"
     mode= "file"
     destination = "local/ftp.txt"
   }


    template {
      change_mode   = "restart"
      right_delimiter = "++"
      left_delimiter = "++"
      source        = "local/ftp.txt"
      destination = "local/from_ftp.txt" # this is interpolated
    }


      template {
        change_mode   = "restart"
        destination = "local/from_var.txt"  # this is not interpolated
        right_delimiter = "++"
        left_delimiter = "++"
        data        = <<EOH
        ++ with nomadVar "nomad/jobs/test"  ++
           ++ .test_var ++
         ++ end  ++
        EOH
        }
```

**Comment by jrasell** [comment]
Hi @suikast42. The Nomad template block (provided by consul-template) does not recursively render templates which therefore explains the behaviour you are experiencing. Nomad has issue https://github.com/hashicorp/nomad/issues/4470 and consul-template has issue https://github.com/hashicorp/consul-template/issues/1402 tracking the desire for this functionality. Please add a thumbs up to either/both of those issues to show your interest in this functionality.

**Comment by suikast42** [comment]
Thanks. That seems the same behaviuor with kv store in consul right?

**Comment by jrasell** [comment]
> Thanks. That seems the same behaviuor with kv store in consul right?

Yes, it will be the same for any use of the template block.
