### ISSUE TITLE
Allow setting of "datacenter" on CSI volume definitions

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/nomad#15420]
### Proposal
Allow the setting of a "datacenter" property on CSI volume definitions. 

### Use-cases
We currently heavily use Hetzner Cloud, and CSI to mount volumes for various tasks. Hetzner, however, only allows you to mount a volume if it's in the same location (datacenter) as the server it's being mounted to. While you can work around this by setting the appropriate datacenter value in the job spec, this has gone pear-shaped on more than one occasion. If we can set a datacenter value on the CSI volume definition, and if that would behave similar to how host_volumes are checked, that'd be very useful, in my opinion.

### Attempted Solutions
Limit the job to the DC the volume lives in, which is fine when you aren't using nodes across different DC's for redundancy and HA.

**Comment by tgross** [comment]
Hi @benvanstaveren! "Datacenter" as it refers to Nomad nodes doesn't have a good 1:1 match with CSI volumes, because CSI volumes aren't created on specific nodes. Instead, CSI is supposed to handle this sort of thing via [topology requests](https://developer.hashicorp.com/nomad/docs/other-specifications/volume/topology_request).

I'm not all that familiar with the Hetzner Cloud plugin but it looks like it does support topology. They have an open issue https://github.com/hetznercloud/csi-driver/issues/333 where the specific fields they're looking for have changed depending on the version of the plugin you're using, so you'll want to check on that.

**Comment by benvanstaveren** [comment]
Yes, Hetzner's CSI driver does support topology - but I can't for the life of me figure out how to map their topology stuff to the topology_request block in Nomad :/

**Comment by benvanstaveren** [comment]
Okay so I checked the Hetzner CSI driver and they do have that label, but riddle me this (because I can't find it in the documentation); the Hetzner CSI driver has a label "csi.hetzner.cloud/location" that is set to the Hetzner DC where the volume lives (fsn1, hel1, nbg1 - in lowercase). In my setup, my Nomad DC's mirror that except I use FSN1, HEL1, NBG1 - in uppercase. How does Nomad figure out that nodes in FSN1 can only mount volumes where the topology says they're in fsn1? Since there's a case difference, and how does it know to look at that particular label?

**Comment by tgross** [comment]
If the volume was created with a [topology_request](https://developer.hashicorp.com/nomad/docs/other-specifications/volume/topology_request), then when the scheduler checks if a node is feasible for the volume in [feasible.go#L318-L325](https://github.com/hashicorp/nomad/blob/v1.4.3/scheduler/feasible.go#L318-L325) it'll compare the topology against the topology provided by the plugin. The [`MatchFound`](https://github.com/hashicorp/nomad/blob/v1.4.3/nomad/structs/node.go#L64-L75) is a literal equality match, so there's no case coercion.

The tags and their values are determined by the plugin and get stored in Nomad's state when the plugin fingerprints. If you run `nomad plugin status -verbose $plugin_id` you'll see the values it's provided to Nomad.

**Comment by tgross** [comment]
Looks like this has been answered, so I'm going to close this out.
