### ISSUE TITLE
Cross-compiling from Linux for Darwin

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/nomad#1545]
### Nomad version

Nomad v0.4.1-dev
https://github.com/hashicorp/nomad/commit/a9507812033be5f689e17d9902393e8a94590e7b
### Operating system and Environment details

Linux (presumably any linux)
### Issue

Unable to cross-compile for osx:

```
../../hashicorp/nomad/vendor/github.com/mitchellh/go-ps/process.go:31: undefined: processes
../../hashicorp/nomad/vendor/github.com/mitchellh/go-ps/process.go:39: undefined: findProcess
```

For Darwin these only exist  when +build darwin, and cannot be included for linux because they are defined in `../../hashicorp/nomad/vendor/github.com/mitchellh/go-ps/process_darwin.h`

The main interest I have for cross-compiling is that we have the api and nomad/structs package as dependencies (maybe there is a workaround where I could skip the process part?)
### Reproduction steps

Cross-compiling : `GOOS=darwin GOARCH=amd64 go build`

Thanks!

**Comment by dadgar** [comment]
You should open a ticket against that project and cross link it here as that is the package that can't be built.

**Comment by dadgar** [comment]
We just need to vendor this now
