### ISSUE TITLE
support `SO_REUSEPORT` for safe reuse of static ports

### ISSUE THREAD

**Issue by victorstewart** [hashicorp/nomad#15487]
on [https://developer.hashicorp.com/nomad/docs/job-specification/network#host_network](https://developer.hashicorp.com/nomad/docs/job-specification/network#host_network)

it states... 

> Since multiple services cannot share a port, the port must be open in order to place your task.

but this is false: if using host networking, and SO_REUSEPORT, ports can be shared. docker supports this, i assume the containerd plugin as well.

just wanted to confirm Nomad doesn't refuse to start jobs that all use the same static port.

**Comment by victorstewart** [comment]
okay no worries. between now and then i ended up writing my own machine orchestrator, program scheduler and container runtime... just ended up being the path of least resistance for me for many reasons. so i ended up completely sidestepping this issue.

but i do think this is an important feature.

take an array of QUIC programs that use a load balancer to assist connection establishment, then switch to their unique unicast address. all of these servers must run on the public (read: external facing) 443 port for most client firewalls, at whatever waypoint, to reliably allow the UDP traffic through. but this pattern would be impossible in Nomad today.

(not everyone load balances or proxies all traffic through CNI meshes).

best of luck!

**Comment by gulducat** [comment]
Howdy folks!  I have a draft PR #23956 up for this, and I'd love to hear any feedback about whether it would or would not improve the situation for any particular use cases.

Lots of detail in the PR description, but in short: how would being able to specify a port, but ignore collisions, affect your deployments?

```hcl
group "g" {
    network {
        mode = "host"

        port "http" {
            static = 8000
            to     = 8000

            allow_reuse = true # ignore collisions
        }
    }
    task "t" {
        ...
```
