### ISSUE TITLE
Event Streams: A missing ACL policy on token will cause GET /v1/event/stream to fail

### ISSUE THREAD

**Issue by wjnicholson** [hashicorp/nomad#15493]
### Nomad version
Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e)

### Operating system and Environment details

Tested using curl and a nomad server in AWS.

### Issue

Minting a token with a policy in the list that doesn't exist causes GET requests to /v1/event/stream to return a 500 permission denied response, even if there is another policy that should allow the request to pass.

### Reproduction steps

Create token with two policies, one that exists with a default write permission and then another policy name that doesn't exist.
i.e
```
namespace "default" {
  policy = "write"
}
```

Call 
```
curl -vv -sN --header "X-Nomad-Token: ${NOMAD_TOKEN}" "${NOMAD_ADDR}/v1/event/stream?namespace=default&topic=Allocation"
```

#### Expected Result

A 200 response and an event stream.

#### Actual Result

500 response, with body "Permission denied"

Discovered issue by creating tokens with different policy subsets until we accidentally found it was due to a policy that didn't exist.
Mentioned here that it was possible to mint a token without a corresponding policy:
https://github.com/hashicorp/nomad/issues/14058#issuecomment-1342595062

I believe the code at https://github.com/hashicorp/nomad/blob/main/nomad/stream/event_broker.go#L302 is the issue, in method aclObjFromSnapshotForTokenSecretID. If it cannot find a policy it eagerly returns an error. Based on other instances of that method call (e.g https://github.com/hashicorp/nomad/blob/47c2d4ab341a7c8dc1f73e4ca77c2811d1aee02b/nomad/acl.go#L248) it looks like the code should be changed to continue:

```go
		if err != nil {
			return nil, err
		}
		if policy == nil {
			// Ignore policies that don't exist, since they don't grant any
			// more privilege.
			continue
		}
```

Separately - we found it hard to debug this as we could not see the missing policy in `ui/settings/tokens`, as the request for the policy document had failed and we hadn't opened dev tools to check for any errors.

**Comment by tgross** [comment]
Leaving a note here about the open discussion on the PR: https://github.com/hashicorp/nomad/pull/15495#pullrequestreview-1295962292
