### ISSUE TITLE
volume mount propagation mode isn't provided to task

### ISSUE THREAD

**Issue by shumin1027** [hashicorp/nomad#15524]
I have a problem when trying to use [`cvmfs-csi`](https://github.com/cvmfs-contrib/cvmfs-csi) in nomad , the csi plugin works fine,  but it seems that it cannot be automatically mounted in the application container, may be because missing `rslave` or `rshared` in the container mount

Here is the issue: https://github.com/cvmfs-contrib/cvmfs-csi/issues/52

The  `CSI volume` mount needs to support "mount propagation" option，such as: 

[k8s volume mount propagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation)

[docker bind propagation](https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation)

**Comment by tgross** [comment]
Hi @shumin1027! I think this was fixed in https://github.com/hashicorp/nomad/pull/15096, which if I'm reading correctly was released in Nomad 1.4.3. Can you confirm which version of Nomad you're running?

**Comment by shumin1027** [comment]
> Hi @shumin1027! I think this was fixed in #15096, which if I'm reading correctly was released in Nomad 1.4.3. Can you confirm which version of Nomad you're running?

@tgross  The version  is `Nomad v1.4.4-dev` 

I need to set `propagation_mode` when mounting a `CSI volume`, I don't know how to configure, there is also no example configuration given for this in the docs

https://developer.hashicorp.com/nomad/docs/job-specification/volume_mount#volume_mount-parameters
https://developer.hashicorp.com/nomad/docs/other-specifications/volume
https://developer.hashicorp.com/nomad/docs/job-specification/volume

**Comment by shumin1027** [comment]
@tgross  The `PropagationMode` option is not processed when mounting `Host Volume` and `CSI Volume`

`func hostVolumeMountConfigurations`:

https://github.com/hashicorp/nomad/blob/fc4abf24f2e358963fdf3eedd800245068a3832f/client/allocrunner/taskrunner/volume_hook.go#L81-L86

`func prepareCSIVolumes`:
https://github.com/hashicorp/nomad/blob/fc4abf24f2e358963fdf3eedd800245068a3832f/client/allocrunner/taskrunner/volume_hook.go#L172-L179

**Comment by tgross** [comment]
Looking at the code, the example you gave here looks right:

```hcl
volume_mount {
    volume           = "cvmfs"
    destination      = "/cvmfs"
    read_only        = true
    propagation_mode = "rshared"
  }
```

See [`api/tasks.go#L421`](https://github.com/hashicorp/nomad/blob/v1.4.3/api/tasks.go#L421). So the first problem is that we need to fix our documentation to include that. But you're right it looks like it's missing from those bits in the `volume_hook` as well. I'll mark this is a bug to fix, but I won't be able to pick this up again until after the new year.

**Comment by shumin1027** [comment]
@tgross  The correct configuration parameters should be like this，:
```hcl
volume_mount {
    volume           = "cvmfs"
    destination      = "/cvmfs"
    read_only        = true
    propagation_mode = "host-to-task"
  }
```

`propagation_mode` should be filled with `private`  ,`host-to-task` or `bidirectional`

https://github.com/hashicorp/nomad/blob/f45244154288eec153eb4fd5969b66f94e62308e/nomad/structs/volumes.go#L13-L17

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/15626
