### ISSUE TITLE
parse `stale` querystring parameter value as boolean

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#15562]
The [`stale`](https://developer.hashicorp.com/nomad/api-docs#stale) parameter on the Nomad HTTP API determines the consistency mode for query endpoints. If the `stale` flag is set, a request to a follower will be served without being forwarded to the leader. Unfortunately the API server tolerates this flag have a value, but it only _acts_ on the flag being set.

This means a request like `/v1/jobs?stale=false` is treated as a stale query. While the documentation is straightforward on this, it's bad ergonomics and can lead to mistakes. Instead, we should parse any value as a boolean (and keep the existing behavior where if the flag is set without a value, the query is stale). So in other words we want:

| querystring | is stale query? |
|-|-|
| `?stale` | yes |
| `?stale=true` | yes |
| `?stale=false` | no |

**Comment by dttung2905** [comment]
If you don't mind, please allow me to work on this issue.
