### ISSUE TITLE
nomad fs missing in nomad docs

### ISSUE THREAD

**Issue by itatabitovski** [hashicorp/nomad#1557]
nomad fs is missing in the online documentation

https://www.nomadproject.io/docs/commands/index.html

**Comment by diptanu** [comment]
@itatabitovski Sorry, it's fixed. The actual docs are here - https://www.nomadproject.io/docs/commands/fs.html

**Comment by itatabitovski** [comment]
@diptanu  It is still missing in the left side menu. And the Examples are not formatter correctly.
