### ISSUE TITLE
online documentaion of logs command  is not available

### ISSUE THREAD

**Issue by nak3** [hashicorp/nomad#1565]
https://github.com/hashicorp/nomad/blob/master/website/source/docs/commands/logs.html.md.erb should be available on online.

URL (https://www.nomadproject.io/docs/commands/logs.html) is still 404.

**Comment by diptanu** [comment]
This is not deployed, we will push the new website when we release 0.4.1

**Comment by nak3** [comment]
I understand Thank you!
