### ISSUE TITLE
Nomad not renewing Vault database engine token correctly

### ISSUE THREAD

**Issue by altosys** [hashicorp/nomad#15714]
### Nomad version

Nomad v1.4.3

### Operating system and Environment details

Arch Linux

### Issue

I’m having a strange issue where Nomad doesn’t seem to renew a token lease when using the Vault database secrets engine for PostgreSQL. I can see in my task environment that the token is still present:

```
DATABASE_URL=postgres://v-token-24-miniflux-uG3GyFJQXhWqADIblGyl-1672830224:HUbXzLqK-TWjIBr4SXmj@postgres.service.consul/miniflux?sslmode=disable
```

but when I look in postgres the relationship owner has reverted to `miniflux` which is my placeholder user with `nologin` when the service isn’t running:

```
miniflux=# \d
                List of relations
 Schema |       Name        |   Type   |  Owner
--------+-------------------+----------+----------
 public | acme_cache        | table    | miniflux
 public | api_keys          | table    | miniflux
 public | api_keys_id_seq   | sequence | miniflux
 public | categories        | table    | miniflux
 public | categories_id_seq | sequence | miniflux
 public | enclosures        | table    | miniflux
 public | enclosures_id_seq | sequence | miniflux
 public | entries           | table    | miniflux
 public | entries_id_seq    | sequence | miniflux
 public | feed_icons        | table    | miniflux
 public | feeds             | table    | miniflux
 public | feeds_id_seq      | sequence | miniflux
 public | icons             | table    | miniflux
 public | icons_id_seq      | sequence | miniflux
 public | integrations      | table    | miniflux
 public | schema_version    | table    | miniflux
 public | sessions          | table    | miniflux
 public | sessions_id_seq   | sequence | miniflux
 public | user_sessions     | table    | miniflux
 public | users             | table    | miniflux
 public | users_id_seq      | sequence | miniflux
```

If I restart the miniflux service then Vault replaces the owner with the token, but within a few hours it reverts to miniflux again.

### Reproduction steps

I have this vault policy set up for the service:

```
path "postgres/creds/miniflux" {
  capabilities = ["read"]
}
```

and in the job I’m specifying this vault stanza:

```
vault {
  policies = ["miniflux"]
  change_mode = "restart"
}
```

and of course templating the credentials in environment variables:
```
template {
  destination = "secrets/env"
  change_mode = "restart"
  env         = true
  data        = <<-EOH
    {{ with secret "postgres/creds/miniflux" -}}
    DATABASE_URL=postgres://{{ .Data.username }}:{{ .Data.password }}@postgres.service.consul/miniflux?sslmode=disable
    {{- end }}
  EOH
}

```
My nomad servers are configured with these Vault parameters according to the [Vault integration instructions](https://developer.hashicorp.com/nomad/docs/integrations/vault-integration):

```
vault {
  enabled = true
  address = "http://active.vault.service.consul:8200"
  token   = "<token>"
  create_from_role = "nomad-cluster"
}
```

#### Expected Result

Nomad should renew the token lease and restart the container when the vault token is updated, resulting in only momentary downtime during the container restart.

#### Actual Result

Nomad doesn't seem to renew the lease in due time resulting in Vault revoking the dynamic credentials and reverting the database owner in postgres to my placeholder user `miniflux` 

### Nomad Server logs (if appropriate)

```
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.856+0100 [INFO]  agent: (runner) rendered "(dynamic)" => "/opt/nomad/data/alloc/24a10ded-cb1a-d600-6638-99c6a867a6b8/miniflux/secrets/env"
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.857+0100 [INFO]  agent: (runner) stopping
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.857+0100 [INFO]  agent: (runner) creating new runner (dry: false, once: false)
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.857+0100 [INFO]  agent: (runner) received finish
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.857+0100 [INFO]  agent: (runner) creating watcher
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.858+0100 [INFO]  agent: (runner) starting
Jan 04 12:03:44 nas nomad[975273]:     2023-01-04T12:03:44.961+0100 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=e7446c8177098b00d96e4366b69be7dcaee2991fe8637dbcb0c2b48d0867ac2c
Jan 04 12:03:45 nas nomad[975273]:     2023-01-04T12:03:45.140+0100 [INFO]  agent: (runner) rendered "(dynamic)" => "/opt/nomad/data/alloc/24a10ded-cb1a-d600-6638-99c6a867a6b8/miniflux/secrets/env"
Jan 04 12:03:45 nas nomad[975273]:     2023-01-04T12:03:45.276+0100 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=e7446c8177098b00d96e4366b69be7dcaee2991fe8637dbcb0c2b48d0867ac2c
Jan 04 12:03:52 nas nomad[975273]:     2023-01-04T12:03:52.771+0100 [ERROR] nomad.event_broker: failed resolving ACL for secretID, closing subscriptions: error="ACL token not found"
```

The above is quite ambiguous for me, I’m not sure what ACL token the error is referring to.

### Other information

I have had other services using the same Vault engine setup towards Postgres for more than a year and working perfectly, while troubleshooting this issue I've redeployed some of those as well which has resulted in them also having this issue, which leads me to suspect that this might be a systematic issue between Nomad/Vault somehow.

All of these services run with the same Vault configs (same policy rules, db creation/renewal/revoke statements) and same same vault and template stanzas in the job file except for the service names of course. I Terraform all of the Vault resources with for_each over the service names, so I know they are fully identical.

**Comment by nrdxp** [comment]
Just hit this as well. I plan on working around by just doing it manually with the Vault CLI, but that seems silly.

**Comment by tgross** [comment]
Hi @altosys! Sorry about the delay on picking this issue up. The `template` block is implemented with an embedded [`consul-template`](https://github.com/hashicorp/consul-template) which is responsible for doing the lease renewals. Those are the log entries with `agent: (runner)` in the client logs.

What I'd want to do to debug this:
* Look in the client logs for `agent: (runner)` logs around the time of half the TTL. You should see something there.
* Look at the Vault role and ensure that `lease_renewable=true` (ref https://developer.hashicorp.com/vault/docs/secrets/databases#usage)
* Look at Vault's own logs to see if the renewal was attempted but returned an error.

**Comment by tgross** [comment]
Doesn't look like we've heard back on this in a while. I'm going to close it out but feel free to let us know if you have more debugging info.
