### ISSUE TITLE
Add type filter option for packs 

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad#15736]
### Proposal
I would love to be able to filter on the which jobs are packs

![Screenshot from 2023-01-09 23-38-35](https://user-images.githubusercontent.com/163633/211422765-11e3cf70-9310-4234-bacb-a3aa1bd65d7d.png)

### Use-cases
to visually limited what jobs are packs and which arent

### Attempted Solutions
n/a

**Comment by jrasell** [comment]
Hi @attachmentgenie and thanks for raising this. I'll mark this so the Nomad UI engineers can take a further look.
