### ISSUE TITLE
Rerunning the same Job of a single batch task does not trigger a new evaluation

### ISSUE THREAD

**Issue by dvusboy** [hashicorp/nomad#1575]
### Nomad version
`Nomad v0.4.0`

### Operating system and Environment details
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Issue
I have a Job with a single `batch` task that uses `raw_exec` driver and an artifact as the executable to run. There is a dedicated host to run these kind of tasks, so allocations will always land on the same node. The initial attempt failed (but it did not exit with a non-zero exit code, another bug) because of a bug in the artifact. The artifact was fixed and the *same* job is resubmitted with `nomad run`. This second attempt happened after about 2 hrs since the initial failed run, so GC did not happen.

Nomad did not trigger a new allocation on the second attempt. Then I manually trigger a GC with the HTTP API and then a new allocation happens. This is unexpected behavior. Is a user expected to generate a new job name (ID) on every run? Even though the task is essentially identical, in the sense that it is trying to do the same thing.

### Reproduction steps
Host a simple shell script that sleeps for some time and submit a Nomad job that `raw_exec` the script. Then update the script, say, with a different sleep time and rerun the same job spec.

**Comment by dadgar** [comment]
Nomad has to detect a difference in the job being submitted for it to rerun the job. I think the real solution is to have a `nomad run -force` flag that overrides this.

**Comment by dadgar** [comment]
If you agree, I think we should close this issue and open a new one to properly reflect the ask

**Comment by dvusboy** [comment]
I'll file the feature request.
