### ISSUE TITLE
Disk space fingerprint checks the wrong path if alloc_dir is not set

### ISSUE THREAD

**Issue by dbresson** [hashicorp/nomad#1577]
Tested in v0.4.0 and explainable by code in master.

The disk fingerprint checks the AllocDir config, and if it is empty, falls back to the current working directory as the path to fingerprint. This does not match the behavior of the actual allocation directory logic, which defaults to DataDir/alloc.

To reproduce, mount a volume at the data_dir path and leave the alloc_dir setting at default. The disk space of the mounted volume will not be the value reported for disk space available to nomad.

**Comment by dadgar** [comment]
If you feel comfortable, please make a PR for this

**Comment by dbresson** [comment]
@dadgar I don't actually understand why it's happening. The AllocDir defaulting logic appears to be applied to the config well before it gets to storage fingerprinting, so AllocDir should not be empty.

**Comment by nak3** [comment]
I tested this , but I couldn't reproduce it. When `alloc_dir` was not set in client config, `data_dir` of the subdirectory was used, and then, its disk usage of the file path was output.

@dbresson What command/API output are you checking? __Allocated Resources__ in `nomad node-status <ID>`?

**Comment by dbresson** [comment]
Yes, exactly.

**Comment by dbresson** [comment]
Hmm, I can't reproduce it now either. Sorry for the inconvenience.
