### ISSUE TITLE
nomad should not assume all linux hosts use eth0 as the default.

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/nomad#158]
systemd systems do not have eth0. Maybe nomad should detect the default interface based on the default gateway: https://github.com/hashicorp/nomad/blob/master/client/fingerprint/network_unix.go#L38

**Comment by apognu** [comment]
Or maybe allow for a configuration dierctive to set the interface to use. Not everybody wants to use the default gateway.

**Comment by ranjib** [comment]
im running ubuntu 15.04 with systemd and it has eth0. both gateway as well as route introspection can be tricky, i 'll prefer to have a direct config option as @apognu suggested. 
also , ifconfig is fairly old/deprecated, the code should probably use ip instead.

**Comment by dadgar** [comment]
#189 addresses this.
