### ISSUE TITLE
[UI, Example Job Templates] Mirage:  update Mirage config to handle prefix query parameter from API.

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#15824]
Mirage environment looks funky because we're also hitting the `GET /vars` endpoint in the Job Templates View. We'll want to update either the Mirage scenario and/or Mirage config and ensure data on the screen is correct and doesn't impact the Variables view.

![Image](https://user-images.githubusercontent.com/41024828/213536956-154e81d1-29cb-4c8c-9de7-797778b1814b.png)

**Comment by tgross** [comment]
Closed by #15828
