### ISSUE TITLE
[UI, Example Job Templates] Template selections aren't clearing.

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#15825]
Template selections aren't clearing after exiting the view.

This is happening on:

`jobs.run.templates.new`
`jobs.run.templates.index`

![Image](https://user-images.githubusercontent.com/41024828/213537478-1e410b7d-68b4-4720-98f4-6b90509f4dc1.png)

**Comment by tgross** [comment]
Closed by #15827
