### ISSUE TITLE
Nomad install from source documentation is incorrect

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#15831]
Nomad [install from sources documentation ](https://developer.hashicorp.com/nomad/docs/install#from-source) outdated.

```
make dev
==> Formatting HCL
xargs: hclfmt: No such file or directory
make: *** [hclfmt] Error 127
```

**Comment by jrasell** [comment]
Hi @valodzka, `hclfmt` is installed as part of item 2 on that page via `make bootstrap`. Could you confirm you ran this command and still get this error? If so, it would indicate there is something not quite right with your Golang installation which means the installed `hclfmt` command is not being made correctly available.

If your error persists, you could also use the [Vagrant machine](https://github.com/hashicorp/nomad/blob/main/Vagrantfile) in this repository. Bringing up the machine will ensure it is correctly configured for development purposes.

**Comment by valodzka** [comment]
>  Could you confirm you ran this command and still get this error?
Yes, I ran it.

> If so, it would indicate there is something not quite right with your Golang installation which means the installed hclfmt command is not being made correctly available.
I used `brew install go` for installation + set `GOPATH`, nothing more. I guess some some `PATH` configuration also required?

**Comment by jrasell** [comment]
Hi @valodzka, yes in order to use Go binaries installed by the `go install` command you'll need to have the `GOPATH` in your `PATH`. To try this you can run something similar to `export PATH=$PATH:$GOPATH/bin` in a terminal then run the command again. To have this change longer lasting, you'd need to modify your profile.

**Comment by valodzka** [comment]
> order to use Go binaries installed by the go install command you'll need to have the GOPATH in your PATH

Okay, thank you. As someone not working with go daily I this it would be useful to add this to installation docs.
