### ISSUE TITLE
Exec driver is showing cache+RSS in memory usage UI view

### ISSUE THREAD

**Issue by Blefish** [hashicorp/nomad#15830]
### Nomad version
Nomad v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

### Operating system and Environment details
Amazon Linux 2
### Issue
Nomad exec driver seems to be reporting cache+RSS in UI view, causing confusion among operators that memory usage of the application is too high.
### Reproduction steps
Launch an exec driver job that uses an external volume and reads a large file
#### Expected Result
Nomad's memory usage UI view should indicate memory used by the process as seems to be the case with docker driver.
#### Actual Result
Nomad's memory usage UI shows cache+RSS.

UI allocation view
![Screenshot from 2023-01-20 09-07-12](https://user-images.githubusercontent.com/1191779/213637598-98e2b191-bd03-4467-b21d-eac946df13eb.png)

nomad alloc stats <allocation>
![Screenshot from 2023-01-20 09-07-35](https://user-images.githubusercontent.com/1191779/213637607-077a58db-70fc-47ce-9443-199e421f240d.png)

**Comment by shoenig** [comment]
Hi @Blefish, can you post the detected cgroup version? e.g.

```
➜ nomad node status -self -verbose | grep cgroup.version
unique.cgroup.version           = v2
```

**Comment by Blefish** [comment]
Hi, it seems like v1 is currently being detected. Could that be the reason?

```
# nomad node status -self -verbose | grep cgroup.version
unique.cgroup.version                    = v1
```

**Comment by lgfa29** [comment]
Hi @Blefish 👋 

Would you also be able to provide the output of the [`/v1/client/allocation/:alloc_id/stats`](https://developer.hashicorp.com/nomad/api-docs/client#read-allocation-statistics) for the allocation in question?

I think the UI [uses the RSS value as fallback](https://github.com/hashicorp/nomad/blob/v1.4.3/ui/app/utils/classes/allocation-stats-tracker.js#L52-L55), so I want to make sure your API result is non-zero.

Also, is the Nomad agent running as `root`?

Thanks!

**Comment by Blefish** [comment]
Absolutely, not a problem. I took a different allocation, adding the information below.
UI view
![Screenshot from 2023-01-24 09-58-17](https://user-images.githubusercontent.com/1191779/214239531-f110a7e7-4c94-4d0c-974c-07d29005ffb2.png)
`nomad alloc status 53cb923c-8330-fe4b-4d88-91f63dc257f9`
![Screenshot from 2023-01-24 09-59-29](https://user-images.githubusercontent.com/1191779/214239662-df1c13f2-75ba-46c8-a5bf-716d446b8d8f.png)
`curl /v1/client/allocation/53cb923c-8330-fe4b-4d88-91f63dc257f9/stats | jq`
```{
  "ResourceUsage": {
    "MemoryStats": {
      "RSS": 74035200,
      "Cache": 902995968,
      "Swap": 983515136,
      "MappedFile": 0,
      "Usage": 983515136,
      "MaxUsage": 997433344,
      "KernelUsage": 6488064,
      "KernelMaxUsage": 8470528,
      "Measured": [
        "RSS",
        "Cache",
        "Swap",
        "Usage",
        "Max Usage",
        "Kernel Usage",
        "Kernel Max Usage"
      ]
    },
    "CpuStats": {
      "SystemMode": 0,
      "UserMode": 0.9996656738113818,
      "TotalTicks": 20.62405806735794,
      "ThrottledPeriods": 0,
      "ThrottledTime": 0,
      "Percent": 0.9378834955597062,
      "Measured": [
        "System Mode",
        "User Mode",
        "Throttled Periods",
        "Throttled Time",
        "Percent"
      ]
    },
    "DeviceStats": []
  },
  "Tasks": {
    "taskname": {
      "ResourceUsage": {
        "MemoryStats": {
          "RSS": 74035200,
          "Cache": 902995968,
          "Swap": 983515136,
          "MappedFile": 0,
          "Usage": 983515136,
          "MaxUsage": 997433344,
          "KernelUsage": 6488064,
          "KernelMaxUsage": 8470528,
          "Measured": [
            "RSS",
            "Cache",
            "Swap",
            "Usage",
            "Max Usage",
            "Kernel Usage",
            "Kernel Max Usage"
          ]
        },
        "CpuStats": {
          "SystemMode": 0,
          "UserMode": 0.9996656738113818,
          "TotalTicks": 20.62405806735794,
          "ThrottledPeriods": 0,
          "ThrottledTime": 0,
          "Percent": 0.9378834955597062,
          "Measured": [
            "System Mode",
            "User Mode",
            "Throttled Periods",
            "Throttled Time",
            "Percent"
          ]
        },
        "DeviceStats": null
      },
      "Timestamp": 1674547207760584700,
      "Pids": {
        "23947": {
          "MemoryStats": {
            "RSS": 619208704,
            "Cache": 0,
            "Swap": 0,
            "MappedFile": 0,
            "Usage": 0,
            "MaxUsage": 0,
            "KernelUsage": 0,
            "KernelMaxUsage": 0,
            "Measured": [
              "RSS",
              "Swap"
            ]
          },
          "CpuStats": {
            "SystemMode": 0,
            "UserMode": 0.9996659636175891,
            "TotalTicks": 0,
            "ThrottledPeriods": 0,
            "ThrottledTime": 0,
            "Percent": 0.9996659546724126,
            "Measured": [
              "System Mode",
              "User Mode",
              "Percent"
            ]
          },
          "DeviceStats": null
        }
      }
    }
  },
  "Timestamp": 1674547207760584700
}
```

Looks interesting that it is showing swap as roughly 983MB. The host does not have swap enabled, but the exec task uses a volume that is mounted via LVM to the host. A file on that volume is read into the task.

`cat /proc/pid/status`
```
RssAnon:	   72180 kB
RssFile:	  536508 kB
RssShmem:	       0 kB
VmData:	  201920 kB
VmStk:	     228 kB
VmExe:	   25936 kB
VmLib:	    1928 kB
VmPTE:	    1360 kB
VmPMD:	      36 kB
VmSwap:	       0 kB
```
