### ISSUE TITLE
Add client node links from topology page

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#15843]
### Proposal

When viewing the topology page, it might be nice to jump directly to a client node's show page. We should swap out the plain text title of each client node with a link.

### Use-cases

Quickly, figuring out how a client is configured (ie looking at metadata) or viewing all allocations on it more easily.

**Comment by ChaiWithJai** [comment]
@mikenomitch are you saying that you want to turn this into a link?



![Image](https://user-images.githubusercontent.com/41024828/214093657-95ce8d0d-6f13-43fb-8c4e-4375a43ef879.png)

**Comment by mikenomitch** [comment]
@ChaiWithJai yep, that one.

If it doesn't look too funky, I think the blue & underlined text is probably best for people realizing it is clickable. We should probably do a quick check with @juliezzhou to make sure that looks decent before shipping though. If not that, then at least black text that is clickable w/ a pointer on hover.
