### ISSUE TITLE
Can't use Dynamic in docker "config" block

### ISSUE THREAD

**Issue by cilex-ft** [hashicorp/nomad#15850]
Hi,

I can"t figure if I'm reading the doc incorrectly, or if it's too optimistic...

### Nomad version
Nomad v1.4.3, dev version

### Operating system and Environment details
Ubuntu 22.04 minimal, running as a lxc container in a Ubuntu 20

### Issue

Doc about dynamic blocks [states that](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/expressions#dynamic-blocks)

> You can dynamically construct repeatable nested blocks like port using a special dynamic block type, _which is supported anywhere_, example:

(my emphasis)

However I can't use such dynamic bloc in docker Config block, it seems it's not accepted in this context.

When un-commenting the two `mount` blocks below, Nomad behaves as expected. I just can't iterate on a list of mounts, which is un-elegant.

### Reproduction steps

Run `nomad agent -dev -bind 0.0.0.0 -log-level INFO -config /etc/nomad.d/`

Use `dynamic` in a Docker `config` block to define multiple mounts

#### Expected Result

`var/www/html/custom` and `var/www/html/files` should be mounted

#### Actual Result

Log displays:

```
  | 2 errors occurred:
  | \t* failed to parse config: 
  | \t* Invalid label: No argument or block type is named "dynamic".
```

### Job file (if appropriate)

```
variables {
    mount-points = ["custom", "files"]
}

job "test" {
  datacenters = ["dc1"]
  type = "service"

  group "test" {

    task "task" {
      driver = "docker"

      config {
        image    = "nginx/unit:1.29.0-php8.1"

         mount {
             type = "bind"
             source = "/opt/nomad/code/version1"
             target = "/var/www/html"
             readonly = true
         }

         dynamic "mount" {
            for_each = var.mount-points
            content {
              type = "bind"
              source = "/opt/nomad/code/instance/${mount}"
              target = "/var/www/html/${mount}"
             }
         }

#         mount {
#             type = "bind"
#             source = "/opt/nomad/code/instance/custom"
#             target = "/var/www/html/custom"
#         }

#         mount {
#             type = "bind"
#             source = "/opt/nomad/code/instance/files"
#             target = "/var/www/html/files"
#         }

      }
    }
  }
}
```

`/etc/nomad.d/nomad.hcl` defines:

```
plugin "docker" {
    config {
        endpoint = "unix:///var/run/docker.sock"
        volumes {
            enabled      = true
            selinuxlabel = "z"
        }
    }
}
```

**Comment by lgfa29** [comment]
Hi @cilex-ft 👋 

Unfortunately you are correct, `dynamic` blocks are not allowed in certain parts of a job that are opaque to Nomad. One of them, as you pointed out, is a task `config`. This block is passed directly to task drivers as-is so Nomad doesn't have a way to expand these blocks without knowing their schema.

I opened #15857 to update our documentation and clarify this point. Thanks for the report!

**Comment by cilex-ft** [comment]
Thank you

Is there another way to achieve this goal?
