### ISSUE TITLE
Nomad system jobs stuck with endless pending evaluations

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#15858]
### Nomad version
v.1.4.3

### Operating system and Environment details
Fedora29

### Issue
I have a system job called promtail and fabio which is "Type": "system" and they are running on almost all the Nomad clients.

I can’t stop the allocations. After clicking “Stop allocation” or “Stop job” nothing happens and docker containers continue running on nodes. If I log in to the node via ssh and type docker stop promtail-.... then the docker is stopped, however, the job promtail does not schedule new allocations in Nomad. I did nomad job -purge promtail and reposted the job with nomad job run promtail.nomad. However, the job is now “stuck”, and doens’t allocate anything:

![image](https://user-images.githubusercontent.com/15679217/214304176-a83d344b-9424-4313-8f51-ecaeb7845c67.png)

If I do:

```
$ nomad node status | while read -r node _ name _; do echo "$name $(nomad node status "$node" | grep promtail)"; done
```

I still see a lot of promtail allocations running. I can navigate to the machine and do docker stop promtail-.... Stopping the allocation in nomad ui doesn’t do anything - I can click “Stop Alloc” and refresh, and the allocation is still running.

![image](https://user-images.githubusercontent.com/15679217/214304250-d6d81782-d57d-40f4-a5f9-051cd8e8e1a3.png)

I see nothing on Nomad client nodes - as if, the client, didn’t ever receive a message to stop the allocation.

If I stop the docker container, then:

```
sty 21 04:58:39 taskset[17570]:     2023-01-21T04:58:39.813-0500 [INFO]  client.alloc_runner.task_runner: not restarting task: alloc_id=4eeea601-735f-3bf4-0714-3e66b9fa2173 task=promtail reason="Policy allows no restarts"
sty 21 04:58:39 taskset[17570]:     2023-01-21T04:58:39.872-0500 [INFO]  agent: (runner) stopping
sty 21 04:58:39 taskset[17570]:     2023-01-21T04:58:39.873-0500 [INFO]  agent: (runner) received finish
sty 21 04:58:39 taskset[17570]:     2023-01-21T04:58:39.873-0500 [INFO]  client.gc: marking allocation for GC: alloc_id=4eeea601-735f-3bf4-0714-3e66b9fa2173
```

And the allocation becomes “FAILED” in Nomad UI.

This is the same with fabio that is also a system job. However, fabio has restart { attempts = 100 }, and when killing it the client restarts it immediately…

```
$ docker stop fabio-80a297f5-c64c-dcce-ecb2-b9867acb02fb
sty 21 05:00:17 taskset[17570]:     2023-01-21T05:00:17.125-0500 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=80a297f5-c64c-dcce-ecb2-b9867acb02fb task=fabio reason="Restart within policy" delay=15.504839464s
sty 21 05:00:32 taskset[17570]:     2023-01-21T05:00:32.658-0500 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=80a297f5-c64c-dcce-ecb2-b9867acb02fb task=fabio @module=logmon path=/home/STRIKETECH/sysavtbuild/nomad/data/alloc/80a297f5-c64c-dcce-ecb2-b9867acb02fb/alloc/logs/.fabio.stdout.fifo timestamp=2023-01-21T05:00:32.658-0500
sty 21 05:00:32 taskset[17570]:     2023-01-21T05:00:32.658-0500 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=80a297f5-c64c-dcce-ecb2-b9867acb02fb task=fabio @module=logmon path=/home/STRIKETECH/sysavtbuild/nomad/data/alloc/80a297f5-c64c-dcce-ecb2-b9867acb02fb/alloc/logs/.fabio.stderr.fifo timestamp=2023-01-21T05:00:32.658-0500
sty 21 05:00:32 taskset[17570]:     2023-01-21T05:00:32.980-0500 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=09c810d4280d7416e07ad2162b5243c6f9835b9a694d4943da4a626131792595
sty 21 05:00:33 taskset[17570]:     2023-01-21T05:00:33.432-0500 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=09c810d4280d7416e07ad2162b5243c6f9835b9a694d4943da4a626131792595
```

Nomad clients have volume added with directories mounted on host which are mounted on NFS. Yesterday due to maintenance we needed to restart NFS. It may be related, that’s why I’m mentioning it.

In the job listing, all the evaluations are “pending”:

$ nomad status -verbose promtail | grep pending
39cbb197-40f3-2fda-980c-a09b9cdfb333  50        node-update     pending   false
..... 226 more lines ...

Why are they pending? What are they pending for? Listing some evaluation looks like the following:

What can I do to stop all the bogus containers and properly restart system job so it schedules again? How to debug it? What else could be relevant?

```
$ nomad eval list | grep pending | wc -l
31543
$ nomad eval list | grep pending | shuf -n1 | awk '{print $1}' | xargs nomad eval status -json 
{
    "AnnotatePlan": false,
    "BlockedEval": "",
    "ClassEligibility": null,
    "CreateIndex": 1861100,
    "CreateTime": 1674555573521892883,
    "DeploymentID": "",
    "EscapedComputedClass": false,
    "FailedTGAllocs": null,
    "ID": "c0da813f-00ce-61c1-a42a-8d546c5a2ebd",
    "JobID": "promtail2",
    "JobModifyIndex": 0,
    "ModifyIndex": 1861100,
    "ModifyTime": 1674555573521892883,
    "Namespace": "services",
    "NextEval": "",
    "NodeID": "",
    "NodeModifyIndex": 0,
    "PreviousEval": "",
    "Priority": 50,
    "QueuedAllocations": null,
    "QuotaLimitReached": "",
    "RelatedEvals": null,
    "SnapshotIndex": 0,
    "Status": "pending",
    "StatusDescription": "",
    "TriggeredBy": "node-drain",
    "Type": "system",
    "Wait": 0,
    "WaitUntil": null
}
```

### Reproduction steps
It's unclear how to reproduce it. Right now, I started a job called promtail2, and then stopped it. All allocations are still running.

#### Expected Result
Allocations should be stopped. Job should be removed.

#### Actual Result
Job shows as "dead". Allocations are still running.

I also posted on https://discuss.hashicorp.com/t/cant-stop-system-job-docker-containers-job-is-stuck/49164 .

**Comment by tgross** [comment]
Hi @Kamilcuk! To avoid a situation like https://xkcd.com/979/, would you mind leaving a note as to what you discovered that lead you to close this? That'll help the next community member who finds the same thing.

**Comment by Kamilcuk** [comment]
Yup! Working on that...  I discovered there exists a `nomad eval delete` command so I decided to  remove excess of evaluations. I executed:

```
$ nomad operator scheduler set-config -pause-eval-broker=true ; nomad eval delete 39cbb197 ; nomad operator scheduler set-config -pause-eval-brok
er=false                                                                
Scheduler configuration updated!                                                                                                                 
Error deleting evaluations: Unexpected response code: 500 (rpc error: rpc error: failed to lookup eval: eval lookup failed: index error: UUID mus
t be 36 characters)                                                     
Scheduler configuration updated!                                        
```

This command has "unclocked" the evaluations and now all the pending once became completed for some reason. It seems, like "switching" pause-eval-broker was enough, which is suprising behavior.

I do not think that eval-broker was paused, because system jobs were properly _scheduled_ and also many multiple other service and batch type jobs were properly running and stopping for 4 days. Only system jobs weren't killed/stopped properly, but they scheduled fine.
