### ISSUE TITLE
Validation errors when running Nomad as Windows Service

### ISSUE THREAD

**Issue by abudjakov** [hashicorp/nomad#15865]
### Nomad version
1.4.3

### Operating system and Environment details
Microsoft Windows Server 2019 Standard

### Issue
I get the following Validation Errors when I run the job on Nomad running as Windows Service 
Failed Validation  3 errors occurred:
        * failed to parse config:
        * Invalid index: The given key does not identify an element in this collection value.
        * Invalid index: The given key does not identify an element in this collection value.
        
Everything works ok if I run the same job on Nomad running in PowerShell console

### Reproduction steps
Create Nomad service
`sc.exe create Nomad binPath="C:/apps/nomad/nomad.exe agent -config=C:/apps/nomad/server.config" start=auto`

Run the job
```
job "hello" {
    datacenters = ["dc1"]
    type = "batch"

    reschedule {
        attempts    = 0
        unlimited   = false
    }

    group "group" {
        restart {
            attempts = 0
        }
        task "task" {
            driver = "raw_exec"
            config {
                command = "powershell"
                args    = ["python", "${env["PYTHON_PATH"]}/hello.py", "paramA", "paramB"]
            }
        }
    }
}
```

It looks like it can't parse the env variable but it's just an assumption

#### Expected Result
Job is complete 

#### Actual Result
Job is failed 

### Nomad Server logs (if appropriate)
[WARN]  client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=xx  task=task keys=""
[ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=xx task=task
  error=
  | 3 errors occurred:
  | \t* failed to parse config: 
  | \t* Invalid index: The given key does not identify an element in this collection value.
  | \t* Invalid index: The given key does not identify an element in this collection value.

**Comment by lgfa29** [comment]
Hi @abudjakov 👋 

Are you trying to access the `PYTHON_PATH` environment variable? I'm not used to Windows environments much, but have you tried something like:

```
args    = ["python", "$env:PYTHON_PATH/hello.py", "paramA", "paramB"]
```

Currently the HCL parser is reading the `env` object which I believe only holds Nomad-related environment variables. To access your task runtime environment variables you need to write your argument the way you would in an script for example.

**Comment by abudjakov** [comment]
Hi @lgfa29,

Thank you for the suggestion, it's indeed the powershell way of reading env variables: Either `$env:NAME` or `${env:NAME}`
Unfortunately when I try that I get the bellow errors. It doesn't seem it can recognize the variable at all.

That way of supplying the variables `${env["PYTHON_PATH"]}` I found in some Nomad samples and it's working when I run Nomad agent from the console.


Server Logs
```
2023-01-26T11:12:21.664Z [WARN]  client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=60931201-312b-23da-cccc-62fe351bfce4 task=task keys=""
2023-01-26T11:12:21.664Z [INFO]  client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:powershell Args:[$env:PYTHON_PATH/hello.py paramA paramB]}"
2023-01-26T11:12:21.974Z [ERROR] client.driver_mgr.raw_exec: destroying executor failed: driver=raw_exec error="rpc error: code = Unknown desc = executor failed to find process: OpenProcess: The parameter is incorrect."
```

Client Logs
```
At line:1 char:18
+ $env:PYTHON_PATH/hello.py paramA paramB
+                  ~
You must provide a value expression following the '/' operator.
At line:1 char:18
+ $env:PYTHON_PATH/hello.py paramA paramB
+                  ~~~~~~~~
Unexpected token 'hello.py' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression
```

**Comment by abudjakov** [comment]
I've tried other experiments and can see that Nomad Win service doesn't respect any system and user environment variables. 
I can't find python while it's added to `PATH` and accessible from any console,

```
 config {
                command = "powershell"
                args    = ["python", "$env:PYTHON_PATH/hello.py", "paramA", "paramB"]
            }
```

Error
```
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by abudjakov** [comment]
Resolved the issue by adding System env variables instead of User ones.
Sample
```
[System.Environment]::SetEnvironmentVariable('PYTHON_PATH','C:\python\',[System.EnvironmentVariableTarget]::Machine)
```

**Comment by lgfa29** [comment]
I'm glad you were able to fix the problem. Thanks for posting your solution 😄
