### ISSUE TITLE
Add subsections list in the beginning of api docs

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#15866]
### Proposal

Add a legend with links to <h2 sections "Read Job" "List Job Allocations" on the beginning of the api-docs pages. Also consider adding `<details><summary>this is api example</summary><code>{some json}</code></details>` in some places so that code blocks do not take so much vertical space.

The page https://developer.hashicorp.com/nomad/api-docs/jobs is incredibly long. I went to find how to post a new parametrized job. Ctrl+f search is not successful, I do not know what to search for exactly. I have to scroll down the whole page until I find the information. Long code blocks just keep scrolling.

### Use-cases

To find the information faster.

### Attempted Solutions

Ctrl+f but I do not always know what to search for.

**Comment by tgross** [comment]
@Kamilcuk there's an "On This Page" section to the right-hand side of the docs that has exactly what you're looking for, but it gets collapsed if the browser window is not that wide (and on mobile). Let me raise this with @BRKalow (cc'd) and the docs folks.

**Comment by BRKalow** [comment]
Hi there! The current breakpoint to show the page table of contents is 1280px. If you are able, try making your browser window wider than 1279px, like @tgross mentioned.

I'll take this back to the team to see if there are any tweaks we can make here, thanks!

**Comment by Kamilcuk** [comment]
Wow, now I see it, it's on the right! It's great, thx.

**Comment by lgfa29** [comment]
Glad you found what you needed, closing this one now 🙂
