### ISSUE TITLE
Jumping to a Job via the global search does not work

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#15893]
### Nomad version
1.4.3

### Issue

Search for "traefik" in the global search box redirects to `ui/jobs/traefik?namespace=infra` once clicking on the link. This results in a 404. The proper link seems to be: `ui/jobs/traefik@infra`. 

### Reproduction steps

Create  a job in a namespace and try to search for it.

**Comment by lgfa29** [comment]
Thanks for the report @apollo13. I opened #15906 to fix this and some other instances of the same problem that I noticed as well.

**Comment by apollo13** [comment]
Lovely, thanks!
