### ISSUE TITLE
Consul token check for service write permissions, does not consult token's service identities

### ISSUE THREAD

**Issue by mark-rushakoff** [hashicorp/nomad#15902]
### Nomad version

```
$ nomad version
Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e)
```

### Operating system and Environment details

Ubuntu, amd64

### Issue

When submitting a Nomad job that contains a service, using a Consul token that contains a service identity, Nomad does not inspect the Consul token's service identities when determining whether the Consul token has sufficient permissions to submit the job.

### Reproduction steps

I have a Nomad job definition including a service `foo`. On the first pass, before I used a Consul token that was able to write to service foo, the job submission failed as expected: `Error submitting job: Unexpected response code: 500 (job-submitter consul token denied: insufficient Consul ACL permissions to write service "foo")`.

Next, I used a new Consul token that contained the appropriate service identity `foo`, but I received the same error message.

I manually used `consul services register` and confirmed the token was able to register a service `foo`, so this error was particularly confusing.

I started reading through the Nomad code for `(*nomad.consulACLsAPI).CheckPermissions`, and I discovered that the token's roles and policies were consulted, but not the token's service identity.

After I switched to a new token that lacked the service identity but had an explicit policy allowing writes to service `foo`, the job submission completed successfully. (This is an inconvenience, as this requires me to generate policies that are identical to the permissions granted by Consul service identities.)

#### Expected Result

Submitting Nomad jobs respects the Consul token's service identities.

#### Actual Result

Submitting Nomad jobs ignores the Consul token's service identities.

**Comment by shoenig** [comment]
Thanks for the report @mark-rushakoff - indeed when we added the validation it was in the context of Connect, where Nomad generates an SI token on behalf of the job submitter. We never considered the use case of folks using service identity themselves in liu of policies associated with services, but it's a reasonable ask.
