### ISSUE TITLE
The docker driver's dns_servers option is not working

### ISSUE THREAD

**Issue by nicolaevladescu** [hashicorp/nomad#1591]
Hello.

I am running nomad in a digitalocean testing environment with two agents, a server and a client.

On the first droplet i have installed:
* consul agent ( configured as server )
* nomad agent ( configured as server )

On the second i have installed:
* consul agent ( configured as client )
* nomad agent ( configured as client )
* docker-engine
* dnsmasq ( federating only the `.consul` zone to consul's DNS service via the following setting `server=/consul/127.0.0.1#8600` )

On the second droplet i can successfully resolv `nomad.service.consul` and `google.com` with `ping` or `curl` with my nameserver being the local `dnsmasq` service.
```
# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
```
What i want to achieve is to be able to link my two tasks ( and future ) via DNS entries served from consul, not by IP using `NOMAD_IP_*` env as i do now ( see the job file below ).

I could achieve this, only by editing `/etc/default/docker` and adding `DOCKER_OPTS="--dns 172.17.0.1 --dns 8.8.4.4"` using the ip for `docker0` interface as the first DNS server because by default `dnsmasq` binds on all interfaces. And then restarting both docker and nomad.

 Then it worked as i imagined it.

```
# docker exec zookeeper-aa334004-1e7a-64cf-ae6c-74a20691e643 ping nomad.service.consul
PING nomad.service.consul (10.135.7.235) 56(84) bytes of data.
64 bytes from 10.135.7.235: icmp_seq=1 ttl=63 time=1.49 ms
64 bytes from 10.135.7.235: icmp_seq=2 ttl=63 time=0.456 ms
```

```
# docker exec zookeeper-aa334004-1e7a-64cf-ae6c-74a20691e643 ping google.com
PING google.com (172.217.21.78) 56(84) bytes of data.
64 bytes from fra07s31-in-f14.1e100.net (172.217.21.78): icmp_seq=1 ttl=58 time=1.14 ms
64 bytes from fra07s31-in-f14.1e100.net (172.217.21.78): icmp_seq=2 ttl=58 time=0.648 ms
```

### Issue
I wish i had not modified the global docker engine `--dns` directive in `/etc/default/docker` to achieve this.

So either i am using or understanding it wrong, or `dns_servers` does not apply any of the DNS servers in the list to `/etc/resolv.conf` in the container. 

Below you can find the ouput of `docker inspect` of one of the containers showing that only the search domain applied. And outputs of `resolv.conf` and a `ping` from a container. i did not specify any `DOCKER_OPTS` in `/etc/default/docker` when doing the below tests.

```
root@staging-queue-fra1-01:~# docker exec kafka-aa9e2bdf-b51c-a2e6-061a-d2d9613c3180 ping consul.service.consul
ping: bad address 'consul.service.consul'
```
```
docker exec zookeeper-aa334004-1e7a-64cf-ae6c-74a20691e643 cat /etc/resolv.conf
search consul
nameserver 127.0.0.1
```
```
docker inspect kafka-aa9e2bdf-b51c-a2e6-061a-d2d9613c3180 | grep -i -A 3 -B 3 dns
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": [
                "consul"
            ],
            "ExtraHosts": null,
```
### Nomad version
Nomad v0.4.0

### Operating system and Environment details
Ubuntu 14.04.5 LTS, x86_64
Docker 1.12.0, API 1.24 ( Installed via official docker repos  from their docs )

### Job file

```
job "queue" {
    region      = "global"
    datacenters = ["fra1"]
    type        = "service"

    update {
        stagger = "30s"
        max_parallel = 1
    }

    group "zookeeper-kafka" {
        count = 1
        restart {
            interval = "1m"
            attempts = 12
            delay = "3s"
            mode = "delay"
        }
        task "zookeeper" {
            driver = "docker"
            config {
                hostname           = "zookeeper"
                image              = "mesoscloud/zookeeper:3.4.8-ubuntu-14.04"
                dns_servers        = [ "${NOMAD_IP_zookeeper}", "172.17.0.1" ]
                dns_search_domains = [ "consul" ] 
            }
            service {
                name = "zookeeper"
                tags = [ "zookeeper" ]
                port = "zookeeper"
                check {
                    type = "tcp"
                    path = "/"
                    interval = "10s"
                    timeout = "2s"
                }
            }
            env {
                MYID = 1
            }
            logs {
                max_files = 6
                max_file_size = 12
            }
            resources {
                cpu    = 250
                memory = 128

                network {
                    mbits = 100
                    port "zookeeper" {
			            static = 2181
                    }
                }
            }
        }
        task "kafka" {
            driver = "docker"
            config {
                hostname           = "kafka"
                image              = "wurstmeister/kafka"
                dns_servers        = ["${NOMAD_IP_kafka}"]
                dns_search_domains = ["consul"] 
            }
            service {
                name = "kafka"
                tags = [ "kafka" ]
                port = "kafka"
                check {
                    type = "tcp"
                    path = "/"
                    interval = "10s"
                    timeout = "2s"
                }
            }
            env {
                KAFKA_ADVERTISED_HOST_NAME = "${NOMAD_IP_kafka}"
                KAFKA_ADVERTISED_PORT      = "${NOMAD_PORT_kafka}"
                KAFKA_ZOOKEEPER_CONNECT    = "${NOMAD_IP_kafka}:2181"
            }
            logs {
                max_files = 6
                max_file_size = 12
            }
            resources {
                cpu    = 1500
                memory = 2048

                network {
                    mbits = 100
                    port "kafka" {
			            static = 9092
                    }
                }
            }
        }
    }
}
```

**Comment by diptanu** [comment]
@nicolaevladescu Nomad currently doesn't interpolate strings in the `dns_servers` field of driver config so you won't be able to write `${NOMAD_IP_zookeeper}` there. However the ip `172.17.0.1` should have gone into the resolv.conf. Can you share the client logs please? 

I created an `example.nomad` and added the following in the driver config -
`dns_servers = ["172.17.0.1", "172.17.0.2"]` and that resulted in the following resolv.conf in the container -

```
nameserver 172.17.0.1
nameserver 172.17.0.2
```

So I am not sure how to reproduce this.

**Comment by diptanu** [comment]
@nicolaevladescu Oh I think the container you are inspecting is the kafka container, which has only one DNS Server and you want nomad to interpolate the string and add the right value. As I said before, this is something we don't support yet, but is on the roadmap. Marking this as an enhancement.

**Comment by nicolaevladescu** [comment]
Hi @diptanu

Yes, my example was the task with only one item in the list for `dns_servers`, mainly the interpolated `${NOMAD_IP_zookeeper}` .

I can confirm that it is working as expected if you manually populate the list for `dns_servers`.

However, for the time being, i think the documentation should point out that interpolation does not work for this option ( i could be wrong and missed it, might already be specified, please point out if so ) in the docs : https://www.nomadproject.io/docs/drivers/docker.html#dns_servers

**Comment by dadgar** [comment]
We have been taking somewhat of the opposite approach and documenting what can be and not what can't be.

Hopefully, most things can be interpolating in coming releases!
