### ISSUE TITLE
Globally replace "stanza" with "block" when referring to HCL

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#15916]
Nomad is lagging behind Terraform and other HCL-enabled projects by calling `foo { ... }` a "stanza" instead of a "block" in docs.

We should fix that and do a big global search and replace on `stanza -> block`. I can't think of anywhere this would cause backward compatibility issues, but if any are encountered we will have to stop and consider each one.

**Comment by schmichael** [comment]
We should backport this change to ease future backports (thanks to @tgross for pointing this out).

Don't forget tutorials! They live in another repo (thanks to @angrycub for pointing this out).

**Comment by lhaig** [comment]
Tutorial Branch
https://github.com/hashicorp/tutorials/compare/nomad-update-stanza-to-block-in-docs
I can't create a branch for the nomad repository.
