### ISSUE TITLE
[question] Docker volume support - can we expect it any time soon?

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#1592]
One of the big missing pieces with Nomad's Docker support is volumes. I know there's some outstanding issues around host persistent storage and artefacts etc. but with Docker there's a whole ecosystem of volume drivers to leverage - even to the point where Mesos is now natively speaking the volume driver plugin language so it can make use of docker volume drivers natively.

Really all Nomad needs to support is the ability to define volumes for Docker and the ability to constrain allocation based on the availability of a volume (in cases where the volume is a local host mount, for instance). Allocation based on availability of a local host mountpoint could be done via client attributes while the availability of a named docker volume could be done via the driver.docker attribute namespace (e.g. driver.docker.volume.myvol)

It would be great to see docker volume support because at the moment I could only use Nomad for my stateless containers and I would have to manage my stateful containers separately. This is preventing me deploying Nomad into production.

**Comment by dadgar** [comment]
Closing in favor of #150. Please see there for discussion of this issue
