### ISSUE TITLE
Different Nomad schedulers for a single job (task group schedulers)

### ISSUE THREAD

**Issue by Izerrion** [hashicorp/nomad#15925]
Greetings.

I'm not sure if this feature is in Nomad already, but I'm having difficulties creating the following tasks in a single job:
1) service task that spins up and have restart policies if it goes down;
2) script task that finishes with the code 0 and shouldn't be restarted or executed again unless all first task allocations are rebooted.

According to the documentation you can't mix both of these in a single job because these tasks have different deployment logic, hence different Nomad schedulers should be used: 
https://developer.hashicorp.com/nomad/docs/schedulers
1) Service;
2) Batch

Sorry for being silly if I've missed an obvious solution, but as an example I'm trying to deploy redis cluster (x3 nodes) and initialize the cluster. Since the initialization happens as a separate step via command "redis-cli --cluster create ...", it requires additional raw_exec call without any addresses being hardcoded and using native Consul SD. So the job spec looks like this:

```
job "redis-cluster" {
  datacenters = ["test_dc"]
  type = "service"

  constraint {
    attribute = "${node.class}"
    value     = "test"
  }


  group "redis" {
    count = 3

    network {
      port "redis" {
        static = 7001
        to = 7001
      }
      port "gossip" {
        static = 17001
        to = 17001
      }
    }

    update {
      max_parallel      = 1
        min_healthy_time = "2s"
        healthy_deadline = "3m"
        auto_revert      = true
    }

    restart {
      interval          = "5m"
      attempts          = 4
      delay             = "30s"
      mode              = "fail"
    }

    task "redis-cluster" {

    template {
        data        = <<EOH
#!/bin/bash
set -x
echo "yes" | redis-cli --cluster create {{- range service "redis-cluster" }} {{.Address}}:{{.Port}} {{end}} --cluster-replicas 0
EOH
        destination = "local/bootstrap.sh"
        perms       = "755"
        change_mode = "noop"
      }

    template {
        data        = <<EOH
bind 0.0.0.0
port {{ env "NOMAD_PORT_redis"}}
cluster-port {{ env "NOMAD_PORT_gossip"}}
cluster-config-file {{ env "NOMAD_TASK_DIR" }}/nodes.conf
cluster-enabled yes
cluster-node-timeout 5000
appendonly yes
EOH
        destination = "local/redis.conf"
        change_mode = "noop"
      }
      
      driver          = "docker"
      config {

        auth {
          server_address      = "docker.io"
        }

        image         = "redis:7.0.5"
        network_mode  = "bridge"
        ports = ["redis", "gossip"]
        command = "redis-server"
        args    = ["/local/redis.conf"]
        memory_hard_limit = 20000
      }

      resources {
        cpu           = 300
        memory        = 3000
      }

      service {
        name          = "redis-cluster"
        port          = "redis"
        check {
          type     = "tcp"
          port     = "redis"
          interval = "5s"
          timeout  = "2s"
        }
      }
    }
  }

  group "bootstrap-cluster"{

   restart {
      attempts = 0
      mode     = "fail"
    }

    reschedule {
      attempts  = 0
      unlimited = false
    }

    task "bootstrap-cluster" {
  
      driver = "raw_exec"
        
      env {NOMAD_TOKEN = "<my_hardcoded_nomad_token>"}
  
  # Waiting for redis nodes to be deployed first, then bootstrapping the cluster
      config {
        command = "/bin/bash"
        args    = ["-c", "sleep 15 && nomad alloc exec -task redis-cluster -job redis-cluster  /bin/bash /local/bootstrap.sh" ]
      }
      resources {
          cpu    = 50
          memory = 50
      }
    }
  }
}

```

As you can see, I'm obligated to use null restart and reschedule policy to mimic the partial "batch" scheduler behavior. Bootstrap allocation completes without any problem, but it is marked as failed. Moreover, if for some reason all 3 redis nodes will be down and rebooted consequently, this bootstrap script won't be called again to initiate a cluster, unless a whole job will be manually redeployed.  I think multiple schedulers inside group definitions will help this situation.

**Comment by iluminae** [comment]
one solution would be to move your `bootstap-cluster` task to be in the `redis` group along side your `redis-cluster` and use a [lifecycle](https://developer.hashicorp.com/nomad/docs/job-specification/lifecycle) of `{ hook = "poststart", sidecar = false }` to tell it to schedule this task after the redis-cluster has started, and be OK with it exiting.

Then, rewrite the command executed by the `bootstrap-cluster` task to be idempotent. I would write this to drop the `bootstrap.sh` file into the `bootstrap-cluster` task and execute it there. You can make the task only execute on replica 0 by checking the environment variable `NOMAD_ALLOC_INDEX` in your bootstrap.sh scriptlet, and exiting if it is any other. With a correctly written idempotent script that should be unnecessary though!

**Comment by tgross** [comment]
Hi @Izerrion! I think @iluminae has got it right -- that's exactly how I'd recommend doing that sort of thing. One caveat there is that `NOMAD_ALLOC_INDEX` will get reused between deployments (and isn't 100% guaranteed unique even within a deployment if there are canaries or ephemeral disk migrations in play). Another way to mark that the work has been done is to write a key into a Nomad [Variable](https://developer.hashicorp.com/nomad/docs/concepts/variables).

As far as the original request goes, that's not likely going to work out. When a job is submitted, we emit an evaluation for the job and then that evaluation is by definition associated with a single scheduler -- because an evaluation is the unit of work for the scheduler worker. If you want completely separate deployment logic, that's going to be a different job.

**Comment by tgross** [comment]
As noted, this isn't going to be feasible given the way that Nomad is architected, and there are plausible workarounds. I'm going to close this out.
