### ISSUE TITLE
Nomad batch jobs stuck in pending

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#15980]
### Nomad version
v1.4.3

### Operating system and Environment details
Fedora29

### Issue
The jobs are in status=pending. They are not scheduled to nodes, even with nodes doing nothing. 

### Reproduction steps

Generate around 300 JSON job definitions. Every job has a different ID. Jobs are with CPU=1G, Memory=1G and have one group with one task.  Then one by one, post them to my Nomad cluster using Nomad API. _Almost_ all of them will properly schedule. However, few will stay in pending state forever.

#### Expected Result
Weeeell, jobs should run!

#### Actual Result
Jobs are stuck.

![image](https://user-images.githubusercontent.com/15679217/215802666-dc87849f-fb60-4d70-a06a-5ab3469ec1fc.png)

----

Some time ago I posted https://github.com/hashicorp/nomad/issues/15858 and it looks similar - the evaluations are stuck. The evaluations are just pending and pending, and jobs are just pending and pending. I posted jobs statuses and evaluations JSONs below. Can I post anything else to help fix the problem?

Why are evaluations pending? How to unblock them?

I see that 3 evaluations have that Wait=20000000 and one does not. What does `"Wait": 20000000000` in evaluation JSON means? Where does the 20000000000 big number comes from? What units (seconds?) does this number represent.

Could this be caused by bad communication between servers or some other server or servers<->agents communication related problem?

Also, I _can_ unblock the jobs by "bouncing" evaluation broker scheduling with `nomad operator scheduler set-config -pause-eval-broker=true ; nomad operator scheduler set-config -pause-eval-broker=false`. Why does this command unblocks it?

What should I do 

<details><summary>nomad status of jobs</summary>

```
$ nomad status -verbose dist_test.kc_test17.20221103.1005
ID            = dist_test.kc_test17.20221103.1005
Name          = dist_test.kc_test17.20221103.1005
Submit Date   = 2023-01-31T10:01:39-05:00
Type          = batch
Priority      = 50
Datacenters   = ...
Namespace     = ...
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group                         Queued  Starting  Running  Failed  Complete  Lost  Unknown
dist_test.kc_test17.20221103.1005  0       0         0        0       0         0     0

Evaluations
ID                                    Priority  Triggered By    Status    Placement Failures
155b6b3a-b5c2-f065-bcb4-4148f39c9cb1  50        job-register    pending   false
1edce559-9057-588f-7dc8-74e49ca0ad1d  50        job-deregister  complete  false
d89d5d3a-bbd2-fc13-5553-1e78d3154f1c  50        job-deregister  complete  false
8754b0a7-7619-5f9b-aece-e9201f77d115  50        job-register    complete  false

Allocations
No allocations placed
$ nomad status -verbose dist_test.kc_test17.20221103.1033
ID            = dist_test.kc_test17.20221103.1033
Name          = dist_test.kc_test17.20221103.1033
Submit Date   = 2023-01-31T10:01:42-05:00
Type          = batch
Priority      = 50
Datacenters   = ...
Namespace     = ...
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group                         Queued  Starting  Running  Failed  Complete  Lost  Unknown
dist_test.kc_test17.20221103.1033  0       0         0        0       0         0     0

Evaluations
ID                                    Priority  Triggered By    Status    Placement Failures
88f762f1-7fbd-00a3-639f-012263ef49e9  50        job-register    pending   false
03d8e57a-8dce-cfb4-f18c-07cfbac7c436  50        job-deregister  pending   false
808beb5b-9464-ff94-218c-9a937f2276a2  50        job-deregister  complete  false
83201494-cf83-9cfa-8b76-2fd2ea0a1f1f  50        job-register    complete  false

Allocations
No allocations placed
$ nomad status -verbose dist_test.kc_test17.20221103.1007
ID            = dist_test.kc_test17.20221103.1007
Name          = dist_test.kc_test17.20221103.1007
Submit Date   = 2023-01-31T10:01:39-05:00
Type          = batch
Priority      = 50
Datacenters   = ...
Namespace     = ...
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group                         Queued  Starting  Running  Failed  Complete  Lost  Unknown
dist_test.kc_test17.20221103.1007  0       0         0        0       0         0     0

Evaluations
ID                                    Priority  Triggered By    Status    Placement Failures
bc584713-aa6e-e7ef-1baa-0909d548647c  50        job-register    pending   false
f9aad086-0d01-272e-3214-4a42699ffedf  50        job-deregister  complete  false
32ec431a-55fa-bbef-67cb-26e804481ac3  50        job-deregister  complete  false
66017161-6086-2cdc-8a88-dbd4877d54dd  50        job-register    complete  false

Allocations
No allocations placed
```

</details>

<details><summary>nomad eval status -json of evalutions</summary>

```
nomad eval status -json 155b6b3a-b5c2-f065-bcb4-4148f39c9cb1 
{
    "AnnotatePlan": false,
    "BlockedEval": "",
    "ClassEligibility": null,
    "CreateIndex": 2016274,
    "CreateTime": 1675177299181451812,
    "DeploymentID": "",
    "EscapedComputedClass": false,
    "FailedTGAllocs": null,
    "ID": "155b6b3a-b5c2-f065-bcb4-4148f39c9cb1",
    "JobID": "dist_test.kc_test17.20221103.1005",
    "JobModifyIndex": 2016274,
    "ModifyIndex": 2016274,
    "ModifyTime": 1675177299181451812,
    "Namespace": "distributor",
    "NextEval": "",
    "NodeID": "",
    "NodeModifyIndex": 0,
    "PreviousEval": "",
    "Priority": 50,
    "QueuedAllocations": null,
    "QuotaLimitReached": "",
    "RelatedEvals": null,
    "SnapshotIndex": 0,
    "Status": "pending",
    "StatusDescription": "",
    "TriggeredBy": "job-register",
    "Type": "batch",
    "Wait": 20000000000,
    "WaitUntil": null
}
nomad eval status -json bc584713-aa6e-e7ef-1baa-0909d548647c 
{
    "AnnotatePlan": false,
    "BlockedEval": "",
    "ClassEligibility": null,
    "CreateIndex": 2016277,
    "CreateTime": 1675177299461817615,
    "DeploymentID": "",
    "EscapedComputedClass": false,
    "FailedTGAllocs": null,
    "ID": "bc584713-aa6e-e7ef-1baa-0909d548647c",
    "JobID": "dist_test.kc_test17.20221103.1007",
    "JobModifyIndex": 2016277,
    "ModifyIndex": 2016277,
    "ModifyTime": 1675177299461817615,
    "Namespace": "distributor",
    "NextEval": "",
    "NodeID": "",
    "NodeModifyIndex": 0,
    "PreviousEval": "",
    "Priority": 50,
    "QueuedAllocations": null,
    "QuotaLimitReached": "",
    "RelatedEvals": null,
    "SnapshotIndex": 0,
    "Status": "pending",
    "StatusDescription": "",
    "TriggeredBy": "job-register",
    "Type": "batch",
    "Wait": 20000000000,
    "WaitUntil": null
}
nomad eval status -json 88f762f1-7fbd-00a3-639f-012263ef49e9 
{
    "AnnotatePlan": false,
    "BlockedEval": "",
    "ClassEligibility": null,
    "CreateIndex": 2016303,
    "CreateTime": 1675177302630769306,
    "DeploymentID": "",
    "EscapedComputedClass": false,
    "FailedTGAllocs": null,
    "ID": "88f762f1-7fbd-00a3-639f-012263ef49e9",
    "JobID": "dist_test.kc_test17.20221103.1033",
    "JobModifyIndex": 2016303,
    "ModifyIndex": 2016303,
    "ModifyTime": 1675177302630769306,
    "Namespace": "distributor",
    "NextEval": "",
    "NodeID": "",
    "NodeModifyIndex": 0,
    "PreviousEval": "",
    "Priority": 50,
    "QueuedAllocations": null,
    "QuotaLimitReached": "",
    "RelatedEvals": null,
    "SnapshotIndex": 0,
    "Status": "pending",
    "StatusDescription": "",
    "TriggeredBy": "job-register",
    "Type": "batch",
    "Wait": 0,
    "WaitUntil": null
}
nomad eval status -json 03d8e57a-8dce-cfb4-f18c-07cfbac7c436 
{
    "AnnotatePlan": false,
    "BlockedEval": "",
    "ClassEligibility": null,
    "CreateIndex": 2016127,
    "CreateTime": 1675177282745429826,
    "DeploymentID": "",
    "EscapedComputedClass": false,
    "FailedTGAllocs": null,
    "ID": "03d8e57a-8dce-cfb4-f18c-07cfbac7c436",
    "JobID": "dist_test.kc_test17.20221103.1033",
    "JobModifyIndex": 0,
    "ModifyIndex": 2016127,
    "ModifyTime": 1675177282745429826,
    "Namespace": "distributor",
    "NextEval": "",
    "NodeID": "",
    "NodeModifyIndex": 0,
    "PreviousEval": "",
    "Priority": 50,
    "QueuedAllocations": null,
    "QuotaLimitReached": "",
    "RelatedEvals": null,
    "SnapshotIndex": 0,
    "Status": "pending",
    "StatusDescription": "",
    "TriggeredBy": "job-deregister",
    "Type": "batch",
    "Wait": 20000000000,
    "WaitUntil": null
}
```

</details>

**Comment by Kamilcuk** [comment]
I believe, this was related to high number of evaluations or high number of API requests. I still see the issue, however after waiting for long enough time the evaluations are getting scheduled! Would be nice to know how to confirm it? Is it possible to get from Nomad server the "current" evaluation the scheduler is working on, list the queue of evaluations so that I can know what is the order in queue?  Thank you.

**Comment by tgross** [comment]
Hi @Kamilcuk so that `Wait` time is set by the "re-enque delay" in the eval broker. What's happened there is that the scheduler has nack'd the evaluation (the scheduler's plan was rejected) repeatedly. When the eval broker gets a nack for an eval, it re-enqueues it with a compounding delay, starting at 1 second and then waiting 20 sec on the next one, up to 3 times in total.

The reason why "bouncing" the eval broker works is that it flushes its internal state, and all waiters are unblocked in the process. But the evaluations are getting into a waiting state in the first place because the schedulers don't think those evaluations are likely to work until the cluster state settles.

The debug logs will have more information from the plan applier and scheduler.

The usual way that you'll run into the scheduler's plans getting rejected is if you have high ratio of scheduler concurrency to packing on the cluster. The reason for this is that schedulers are optimistically concurrent. Each job has at most one evaluation in flight at a time. At the start of processing an evaluation, the scheduler takes a snapshot of the cluster state. The schedulers create a plan and then submit it to the plan applier, which serializes the plans and checks that each one can be applied. 

Most of the time this is fine -- if Job A needs room for 2 allocations, they're unlikely to collide with the 2 allocations that a different scheduler wants for Job B. But the less room there is on the cluster, the more likely that plans will start to collide with each other -- especially if the jobs all can be placed on the same nodes. If a large set of jobs were "sharded" among different classes of nodes, they'd be less likely to collide.If you plan on running the cluster heavily packed, you might want to slow down the rate at which you're submitting jobs to it to reduce collisions.
