### ISSUE TITLE
☂️ Nomad HCL in UI

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#15982]
[RFC](https://docs.google.com/document/d/1XaludieCDUniGlpFDz8SeaFmYLNz1G5500aZwQRqfYI/edit#)
[Design Mocks](https://www.figma.com/file/Ug0J1mgeNUjUqtgCB3ZeH7/HCL-in-the-UI?node-id=4572%3A2063&t=gCmu837NxE7ZiSm3-0)

UI
- [x] Read-Only Flow in `jobs.job.definition` view
  - [ ] ~~Syntax-Highlighting Logic for `HCL2` in `CodeMirror`~~
  - [X] Toggle Logic to switch between `JSON` and `HCL`
  - [x] #16510
  - [x] Create read-only `Table` for viewing `HCL` env and local variables.
  - [x] #16509
- [x] Edit Flow in `jobs.job.definition` view
  - [ ] ~~Update `JobDiff` component~~
  - [x] #16733
  - [x] #16714
- [x] Tablestakes
  - [x] #16589
  - [x] #16571
  - [X] Update `JobEditor` component API (shared across `jobs.run` and `jobs.job.definition`)

V1 Requests
- [x] #16735
- [x] #16736

API
- [ ] Add `jobspec` field to `Job` struct in REST API (and Raft)
- [ ] Add `variables` field  to `Job` struct in REST API (and Raft) for environment and local variables
- [ ] Update `POST /parse` endpoint to accept variables

CLI
- [ ] `job inspect` includes a flag to return jobspec

**Comment by ChaiWithJai** [comment]
@mikenomitch The [design mocks](https://www.figma.com/file/Ug0J1mgeNUjUqtgCB3ZeH7/HCL-in-the-UI?node-id=4572%3A2063&t=gCmu837NxE7ZiSm3-0) show that users are able to edit HCL variables. However, your document says that should not be included.

Can you take a peak and determine if there's any functionality from that mock that won't be included?

**Comment by ChaiWithJai** [comment]
@mikenomitch Also, just want to confirm that we're scoping this to the `jobs.job.definition` view and we will not be making any changes to:

- Job Dispatch (parent jobs)
- Job Run

**Comment by mikenomitch** [comment]
@ChaiWithJai, sorry if the doc is confusing. What I was saying we shouldn't do in there was let the user edit the HCL jobspec and add a variable in HCL and then have the variable input(s) below automatically react to that or something. We briefly considered something like parsing the jobspec client-side with WASM and then auto-populating rich variable inputs, but that would be so much extra scope for very little value.

The mockups where they are now are accurate in terms of what we want. Just a variable file at the bottom that gets auto-populated with the values from the backend, and then that file gets passed to the parse endpoint which can (with the new changes) handle variables.

**Comment by mikenomitch** [comment]
Re Job Dispatch:

Unless I'm mistaken, parent jobs should behave a lot like regular jobs in this case. I think we'll get that "for free" with these changes. We should test this as part of development.

Re Job Run:

Agreed that this is out of scope. If we happen to have time at the end, maybe we consider adding variable support here, but I don't think it is very high value.

**Comment by ChaiWithJai** [comment]
@mikenomitch so user's will be able to edit variable inputs like this?


![Image](https://user-images.githubusercontent.com/41024828/215846174-09347b44-e96e-454c-9078-a3c2747b0886.png)

We should have a discussion during Thursday's meeting re:  expressions, functions and locals which are available in `HCL` and ensuring these are stored and displayed properly.

**Comment by mikenomitch** [comment]
Yep! - Yeah let's chat in the meeting. I don't think we need all the HCL stuff but variables would be nice and seem pretty doable.

**Comment by juliezzhou** [comment]
Hi 
some small design things that I noticed
1. do we need "run a job" and the description on top
![Screenshot 2023-03-30 at 1 23 45 PM](https://user-images.githubusercontent.com/90711359/228917038-6e173f99-786c-4c0e-9256-24a5dbd9ea3c.png)
2. notice the white space under the tab is quite bigger than other pages
3. should we make the plan button stick to the bottom of the screen, especially for json format, and text editor is quite long, if the user edited something on the top of the file, it will be annoying to scroll thought the whole job spec to click the plan button
![Screenshot 2023-03-30 at 1 24 29 PM](https://user-images.githubusercontent.com/90711359/228917000-edd26be1-bf0d-478f-a97d-d22021f132b6.png)

**Comment by mikenomitch** [comment]
@ChaiWithJai, I just watched your demo vid, some comments:

* Agree with Julie that we shouldn't have the "Run a job" title appear. Especially when you're in read mode, you will probably just be inspecting what's in there. I think we just remove this.
* Job spec is the default right (not full definition)? If not it should be.
* The "Please refer to the Nomad CLI" subtext doesn't really make sense cause the CLI itself won't actually have the var values. (might be on somebody elses computer for instance) I don't think we can really know where to refer the user. Maybe say "Job Variable Values Not Shown" as the title and "This job may have been submitted with values that differ from the defaults. If you plan to submit a change to this job, ensure the proper variable values are provided"
* On that note, we do plan to provide a var input here right? Just not done yet?

**Comment by ChaiWithJai** [comment]
> Agree with Julie that we shouldn't have the "Run a job" title appear. Especially when you're in read mode, you will probably just be inspecting what's in there. I think we just remove this.

Sure.

> Job spec is the default right (not full definition)? If not it should be.

Correct. Defaults to `job spec` if it exists.

> The "Please refer to the Nomad CLI" subtext doesn't really make sense cause the CLI itself won't actually have the var values. (might be on somebody elses computer for instance) I don't think we can really know where to refer the user. Maybe say "Job Variable Values Not Shown" as the title and "This job may have been submitted with values that differ from the defaults. If you plan to submit a change to this job, ensure the proper variable values are provided"

You "Job Variable Values Not Shown" as the title and "This job may have been submitted with values that differ from the defaults. If you plan to submit a change to this job, ensure the proper variable values are provided" I'll cut a ticket for that.

> On that note, we do plan to provide a var input here right? Just not done yet?

Yes, that was just [included](https://github.com/hashicorp/nomad/pull/16734). Styling challenges associated with `CodeMirror` that I can't avoid.

**Comment by ChaiWithJai** [comment]
Add [JSDoc](https://github.com/hashicorp/nomad/pull/16734#discussion_r1153628898) comments.
