### ISSUE TITLE
follow-up: Document requirement for updating hairpin mode on the Nomad bridge.

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#16023]
In PR #15961, We added hairpinMode as an option to Nomad's network bridge. In that PR the question was raised about whether or not the Client node needed to be rebooted or not to allow Nomad to make the change to that interface configuration. Based on the outcomes of this testing, we can then add more explicit documentation to the configuration element.

Proposed additional content:

> When hairpin mode is enabled allocations are able to reach their own IP and port. Changing this value requires a reboot of the client host to take effect.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/19304
