### ISSUE TITLE
Connect Nodes into a Cluster in nomad

### ISSUE THREAD

**Issue by a12556** [hashicorp/nomad#16046]
Hi everyone, 
I am having the following problem:
I have 1 GCP server and 1 AWS server. I implemented Connect Nodes into a Cluster. I want the GCP server to be the server for this cluster. but can't configure properly. Please help me how to do it
here is the error message
![image](https://user-images.githubusercontent.com/54925568/216582715-f7fda883-26f4-4ee2-b26d-eae8eb8c8a4d.png)
and here is the error message on the GCP cluster server:
![image](https://user-images.githubusercontent.com/54925568/216583001-f18acbf2-c2a4-4bb2-949c-0eaebeae859f.png)
and this is my code in AWS client:
[root@ip-172-31-53-117 nomad.d]# cat nomad.hcl 
datacenter = "dc1"
data_dir  = "/opt/nomad/data"
bind_addr = "0.0.0.0"
server {
  enabled          = true
  bootstrap_expect = 1
  server_join {
    retry_join = ["34.173.72.103"]
  }
}

client {
  enabled = true
}
please give me the solution. Thank you !

**Comment by jrasell** [comment]
Hi @a12556, I have a number of questions here which could help diagnose the problem, however, I do not believe this is a bug in Nomad itself.

The AWS config you included shows the agent is running as both server and client, is this expected, and is this the same for the GCP agent?

How are the AWS and GCP accounts linked from a network standpoint and is connectivity from the [required ports](https://developer.hashicorp.com/nomad/docs/concepts/security#network-ports) allowed via all firewalls between the agents?

The error itself which you included the logs for is stating that the agent cannot connect to IP `10.128.0.3` on port `4647`. Is this the correct IP address for the other instance? If so, this seems like a firewall configuration or network routing issue that needs to be resolved.

**Comment by a12556** [comment]
Hello @jrasell ,
Thank you for responding. I will answer your questions as follows:
1- that's the config I'm expecting -> GCP's config is
[root@gcp bootstrap]# cat /etc/nomad.d/nomad.hcl
datacenter = "dc3"
data_dir = "/opt/nomad/data"
bind_addr = "34.173.72.103" # IP public

server {
   enabled = true
   bootstrap_expect = 3

}

client {
   enabled = true

}

consul {
   address = "127.0.0.1:8500"
   auto_advertise = true
   server_auto_join = true
}
2 - I install open port 4646 4647 4648 on agents -> here, do I need to do anything else?
3- 10.128.0.3 is the private IP address of GCP agent-> on the wire, do I need to fix anything?
4- can you give me similar instructions on the situation I am in?
