### ISSUE TITLE
[question] Nomad tasks limit in a region

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/nomad#1608]
As far as Nomad scaling, here's what Armon mentioned in [this](https://www.youtube.com/watch?v=zq654XQANB4) presentation:

> Thousands of regions
> Tens of thousands of clients per region
> Thousands of jobs per region

When it comes to # of tasks per region, is it bounded by the cluster resource availability or there's a maximum number of tasks per region?

**Comment by dadgar** [comment]
The only bound to number of tasks per region is cluster resources! None of those are hard constraints, he was just illustrating the scale Nomad operates at :)

If there is a follow-up, either re-open or use mailing list (which we prefer for questions)
