### ISSUE TITLE
`Learn: Nomad Reference Architecture` link is dead

### ISSUE THREAD

**Issue by iamwacko** [hashicorp/nomad#16101]
The link to the `Learn: Nomad Reference Architecture` tutorial towards the bottom of the README doesn't link to anything that actually exists. See screenshot below.

![image](https://user-images.githubusercontent.com/101361189/217673267-75b15f41-7c4e-43a1-9536-e6bd362d9f70.png)

**Comment by jrasell** [comment]
Hi @iamwacko and thanks for pointing this out. I have raised a PR linked to this issue to fix this.
