### ISSUE TITLE
Nomad Resource limits

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#16119]
nomad job definition have two parameters fpr handling memory limits.

The memory defines the mimiumum need of memory but shuold not define an upper limit. 

I set for grafana agent  64 MB resource quoata. But I got everytime a OOOM Killed 137 error

```hcl
      resources {
          memory = 64 # needs minimum 64 MB
        }
```

The docu says:

![image](https://user-images.githubusercontent.com/5046525/217924828-083d8097-0622-4421-93cb-9db6aa934452.png)

Grafana agent Mem usage:
![image](https://user-images.githubusercontent.com/5046525/217925510-b536465e-2113-4b2e-a1a5-87a73aa9f35e.png)

Nomad UI errors:
![image](https://user-images.githubusercontent.com/5046525/217925783-b6bb2029-f153-4026-908e-7e01c20e92d6.png)

After increasing the memory to 128 the job runs as expected 

![image](https://user-images.githubusercontent.com/5046525/217926320-cd2dc410-8791-4515-bb3e-c50c2a98b9f7.png)

I am using nomad 1.4.3 and docker 20.10.22

**Comment by shoenig** [comment]
Hi @suikast42, 

> The memory defines the mimiumum need of memory but shuold not define an upper limit.

If `memory` is set but `memory_max` is not set, then `memory` is the maximum amount of memory the task is able to use before getting OOM killed.

If `memory` is set and `memory_max` is set, then `memory_max` is the maximum amount of memory the task is able to use before getting OOM killed, *unless* there is memory pressure happening on the system, at which point `memory` becomes the maximum amount of memory the task is able to use before getting OOM killed.

That second option is just exposing the concept of memory oversubscription, made possible by the Linux kernel.

In your case, it seems a simple case of grafana needing more than 64 MB of memory to operate.

**Comment by suikast42** [comment]
Thanks for that clarification. 

> If `memory` is set but `memory_max` is not set, then `memory` is the maximum amount of memory the task is able to use before getting OOM killed.

memory_max is defined as optional in the docu. Thats little confusing. My assumption was that I set the memory as min memory need without an upperbound. So that the workloads can use the max memory available on the node. 

Is a setup such this possible ?

**Comment by jrasell** [comment]
> So that the workloads can use the max memory available on the node.

In order to achieve this, you would need to set the value of `memory_max` to the total available memory on the node where the allocation will be placed. The [memory oversubscription](https://developer.hashicorp.com/nomad/docs/job-specification/resources#memory-oversubscription) page also has some additional details on how this works along with the tutorial you found.

**Comment by suikast42** [comment]
> In order to achieve this, you would need to set the value of `memory_max` to the total available memory on the node where the allocation will be placed. 

Is there a nomad gost atribute like ${attr.cpu.reservablecores}.

This can help to hold thejob file dynamic.

**Comment by shoenig** [comment]
@suikast42 I don't think that would be possible - the `memory_max` needs to be known before the job goes into the scheduler (so it can find a best fit, etc.), which means it can't be dynamic depending on which node the job lands on.

**Comment by suikast42** [comment]
> @suikast42 I don't think that would be possible - the `memory_max` needs to be known before the job goes into the scheduler (so it can find a best fit, etc.), which means it can't be dynamic depending on which node the job lands on.

But [${attr.cpu.reservablecores}](https://developer.hashicorp.com/nomad/docs/runtime/interpolation)  is alredy defined as a host attribute. Where is the diffrence to memory?
