### ISSUE TITLE
☂️ Job Page Redesign

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#16128]
[Figma](https://www.figma.com/file/u0bjC7eDS2eikXMDJoZhYQ/job-show-page-redesign?node-id=5085%3A127012&t=UnExc1OE8N4qMnOJ-0)
[PRD](https://docs.google.com/document/d/1hJyeW585VQGST5BTtIocu6ml8zbceOYpt9-Eq0isv24/edit?usp=sharing)

## Service Jobs
- [x] #16133
  - [x] #16340
  - [x] #17240
- [x] #16350
  - [x] #16512
  - [x] #16961
  - [x] #17191

## System Jobs
- [x] #17036
- [x] #17073
- [x] #17099

## Batch Jobs
- [x] #17139

## Other Job Types
- [x] #17114
- [x] #17242
- [x] #17216

## Status panel, generally:
- [x] #17149
- [x] #16941
- [x] #16821
- [x] #16881
- [x] #16724
- [x] #16802
- [x] #16797
- [ ] Consider refactoring allocation-status-block (and represented-alloc?) into classes per https://github.com/hashicorp/nomad/pull/16766#discussion_r1158921786
- [x] #17159
- [x] #17011
- [ ] #17058
- [x] #17513
- [x] #17523
- [x] #17525
- [x] #17567
- [x] #17627
- [x] #17565
- [x] #17597
- [x] #17643
- [ ] #17683

## Misc:
- [ ] Mirage Deployment simulator
- [ ] Remove obsoleted components (job-client-status-summary)
- [x] #17193
- [x] #17221

## Jobs Index page
- [x] #17283

**Comment by mikenomitch** [comment]
Note: An allocation that is completed and the rescheduled should be marked as rescheduled
