### ISSUE TITLE
Clarification the nomad job cpu limit

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#16135]
When I set cpu in ressource stanza what is the effect ? 

That is not so clear in the docu?

1. Is that a minimum frequency reserved?
2. Is that a max limit as well ?

**Comment by Dup4** [comment]
It looks like `cpu_min` and `cpu_max` are both set by the same parameter.

https://developer.hashicorp.com/nomad/docs/job-specification/resources#resources-parameters

i.e. `cpu` or `cores`.

**Comment by tgross** [comment]
The `cpu` value controls two different values:
* The frequency in Mhz allocated to the task by the scheduler. That is, how much room should the scheduler set aside?
* The resource isolation used by the task driver. What this actually means is dependent on the task driver implementation. For example, for Docker on Linux this value is mapped to CPU shares.
