### ISSUE TITLE
Doucmentation for SSO is missing

### ISSUE THREAD

**Issue by MChorfa** [hashicorp/nomad#16196]
/area Documentation

this page is resulting in a 404 
https://developer.hashicorp.com/nomad/tutorials/single-sign-on

The documentation of Single sign-on and OIDC support is missing. however, is it referenced in the announcement blog https://www.hashicorp.com/blog/nomad-1-5-adds-single-sign-on-and-dynamic-node-metadata.

Thanks

**Comment by tgross** [comment]
Hi @MChorfa! Looks like there was a gap when the announcement blog went out. I'm looking at an internal repo where the tutorials are submitted and it looks like that PR hasn't been merged yet (ref https://github.com/hashicorp/tutorials/pull/1065 for internal folks). It should get merged soon.

@jrasell I'm going to assign this one to you to close out once that PR gets merged.

**Comment by jrasell** [comment]
Hi @tgross and thanks for raising this @MChorfa. I have raised this internally, and will update this issue once I have some information.

**Comment by jrasell** [comment]
Hi @MChorfa, we are just getting the link and tutorial moved, it was placed in the wrong place, so can currently be found here: https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-oidc-vault

I'll let you know once it's moved and in its correct place

**Comment by MChorfa** [comment]
Awesome 🙌 thank you 🙏

**Comment by jrasell** [comment]
Hi @MChorfa this has now been resolved, and the link in the blog post is now the one to use. Thanks again for pointing this out. If you still encounter problems, please re-open this issue and I'll take a look.
