### ISSUE TITLE
Multiple Workload Identities through multiple identity blocks in jobspec

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#16194]
### Proposal

Nomad 1.5 added the [`identity`](https://developer.hashicorp.com/nomad/docs/job-specification/identity) block to jobspecs to expose the workload identity to tasks for use in the [Task API](https://developer.hashicorp.com/nomad/api-docs/task-api).

Nomad should allow _multiple_ `identity` blocks for the same task to allow creating multiple identities with varying permissions for the same task to use.

We could add a `name` field to identities and treat the current `identity {}` block as being named `default`:

```hcl
task "example" {
  identity {
    env = true
  }

  identity "consul" {
    file = true # writes to secrets/consul.nomad_token or similar

    # Alternatively we could add a new parameter for specifying a file name
    file_name = "nomad_consul_token" 
  }
```

Since the Job struct only allows a single identity, we would need a new `AdditionalIdentites` or `AlternativeIdentities` field on it:

```go
type Job struct {
  // ...
  Identity *WorkloadIdentity

  AltIdentities map[string]*WorkloadIdentiy
}
```

Likewise the Allocation struct would need similar treatment:

```go
type Allocation struct {
  // task -> jwt
  SignedIdentities map[string]string `json:"-"`
  SigningKeyID string

  // task -> name -> jwt
  AltIdentities map[string]map[string]*AltIdentity
}

type AltIdentity struct {
  JWT string `json:"-"`
  SigningKeyID string
}
```

Exact structure TBD.

Alternatively we could create "Named Identities" at the *Group* level if a use case arises for sharing identities within an entire alloc. That case seems orthogonal to the one presented here however.

#### UI Proxy

The Task API requires authentication and therefore does not allow anonymous API access like the Agent API does even with ACLs enabled. This complicates cases in which accessing the API with the minimum privilege level possible is desirable: such as proxying Nomad's UI.

A Nomad UI Proxy can use its default workload identity to serve UI assets, but there are a number of APIs the UI expects to be available even to anonymous users:

- /v1/acl/token/self
- /v1/regions
- /v1/namespaces
- /v1/operator/license
- /v1/agent/self
- /v1/acl/auth-methods

Some of these the UI should be able to serve basic functionality without (regions, namespaces, license, agent/self), but others are a bit more complicated for the UI to just stop poking pre-auth:

The `acl/token/self` and `acl/token/anonymous` endpoints are useful for the API to determine whether or not the user is already authenticated. Even when no authentication is sent the Agent API returns a 200 response while the Task API returns a 401. Likewise [`acl/auth-methods`](https://developer.hashicorp.com/nomad/api-docs/acl/auth-methods#list-auth-methods) are useful for SSO flows.

While it would be nice for no APIs to require anonymous access, that does not appear to be realistic.

*Why not use the task's workload identity to "whitelist" these APIs in the proxy's configuration?*

While this may be possible, the proxy itself likely needs more-than-minimal privileges: e.g. reading its TLS certificate and key out of Variables. Reusing this privileged identity for APIs that are intended to be unprivileged is dangerous.

#### Varying Audiences

In the future if you make workload identity's work better as portable JWTs and less like opaque bearer tokens, it will become desirable to create distinct JWTs for distinct audiences. One workload identity may be generated per audience (eg Vault, Consul, an upstream service, etc).

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/18123 and shipped in Nomad 1.7.0
