### ISSUE TITLE
Using CNI IPVlan with Ability to Communicate from Host to Bridged Containers

### ISSUE THREAD

**Issue by valeksyeyev1** [hashicorp/nomad#16244]
### Proposal
Looking to see if it is possible now, or a possible feature request to be able to use a CNI IPVlan network, where all the docker driver tasks can talk to eachother (works fine currently), but also have the ability to have the host network namespace to be able to communicate to the IPVlan network namespace.

### Use-cases
Current use-case is for communication of a non-nomad docker container running on the host network namespace to be able to communicate with an API endpoint of a service running as a docker container inside the IPVlan network namespace of a Nomad task.
Example: 
Docker Task  on IPVlan running a service with an endpoint that exports data.
Docker Logging container running on the host network, wants to scrape an openmetrics endpoint of the above docker driver task.

Currently can't get communication between network namespaces.

### Attempted Solutions
Additional CNI Config with portmap and bridge.

**Comment by tgross** [comment]
Hi @valeksyeyev1! Reading the [`ipvlan`](https://www.cni.dev/plugins/current/main/ipvlan/) CNI plugin docs, this isn't possible on the same network interface:

> ipvlan does not allow virtual interfaces to communicate with the master interface. Therefore the container will not be able to reach the host via ipvlan interface. Be sure to also have container join a network that provides connectivity to the host (e.g. ptp).

If I understand correctly, that's actually a limitation of the kernel's IPVlan interface and not something we can fix directly. So I think what you'll want to do in this case is to set up a second network block with access to the host network.

**Comment by tgross** [comment]
Doing some issue cleanup and I think we've addressed this issue as best we can given the kernel limitations.
