### ISSUE TITLE
Nomad client becomes CPU-bound with 400-500 allocations on cgroups v2

### ISSUE THREAD

**Issue by c3pmark** [hashicorp/nomad#16246]
### Nomad version
Nomad v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

### Operating system and Environment details
AlmaLinux 9.1 on a physical server (512 gb RAM, 56 hyperthreads), kernel `5.14.0-162.12.1.el9_1.x86_64`.  This is a dev/testing environment with a single Nomad client so this server is responsible for every allocation.

### Issue
When many allocations are running (400-500), the Nomad client consumes 100%-150% of a CPU (according to top).  Allocations stay in "pending" for many minutes instead of being started.

I enabled debugging and took a Go profile ([prof.proto.zip](https://github.com/hashicorp/nomad/files/10808459/prof.proto.zip)) and it seems that 90% of CPU time is being spent writing to cgroup files (`cgutil.AddAlloc` ... `cgutil.reconcile` ... `cgroups.WriteFile` ... `syscall.write`).  The system is running with `mitigations=off` (dev/testing server) so I would expect syscall performance to be optimal.  I also did some ad-hoc profiling with `perf` and it accounted more than half of the time in the `nomad agent` process to the kernel function `css_next_descendant_post`, which seems to be used to iterate cgroups.

I disabled cgroups v2 using kernel commandline arguments `systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller` and rebooted.  Using cgroups v1, Nomad was able to start all jobs promptly and stayed around 40% CPU even while rapidly bringing up 400+ allocs.

### Reproduction steps
Run Nomad on a large machine with cgroups v2 enabled, with many allocations frequently starting and stopping.

#### Expected Result
Nomad uses 20-50% of CPU and schedules the allocations promptly.

#### Actual Result
Nomad consumes 100-150% of CPU and schedules allocations slowly.

**Comment by c3pmark** [comment]
I believe [this forum thread](https://discuss.hashicorp.com/t/long-start-times-of-allocations/42091) may be the same issue.  To answer the question asked on that thread, I'm not using `resources.cores` in any tasks - the only resource limits configured are `cpu` and `memory`.

**Comment by shoenig** [comment]
Hi @c3pmark thanks for the report! 

Indeed the way Nomad currently manages the `cpuset` interface on cgroups v2 is inefficient. It came about as an attempt to retrofit the behavior we had with cgroups v1 - where a cpuset contained both the reserved cores for the task _plus_ any unreserved cores, allowing the task to make use of as many cores as possible. The problem stems from the fact that cgroups v2 less suitable for sub-supervisors like Nomad to manage cgroups like that directly - it is tricky at best - if not impossible - to [replicate the desired behavior](https://lwn.net/Articles/923591/) with cgroups v2. Long story short we wrote this O(n^2) hacky code to manually maintain the existing functionality but at the cost you observe here - large task counts crush the kernel with updates to the cgroups managed by Nomad.

We are thinking / discussing internally how to move forward - clearly we need to support higher task counts, but we may need to switch to a CFS model where a task's core reservations are static - meaning those tasks would no longer be able to make use of the dynamically changing unreserved cores set.

Doing so would also make (potential) future NUMA support easier to implement / reason about; where the static cores would belong to a specific memory node and we just wouldn't worry about any dynamic cores.

**Comment by shoenig** [comment]
Should be fixed as of https://github.com/hashicorp/nomad/pull/18371 (Nomad 1.7)
