### ISSUE TITLE
Workload Identity Expiration and Rotation

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#16258]
As of Nomad 1.5.0 Workload Identities are exposed to users but lack expiration or rotation. This makes them only suitable for communicating with Nomad. Using a workload Identity JWT to authenticate between workloads is not possible because:

1. Nomad does not expose the key by which they are signed (e.g. using JWK). See #15614
2. Workload identities lack common fields necessary for basic security such as audience (`aud`) and expiration (`exp`).
3. Nomad does not expose an public API for validating workload identities.

This means the workload identity JWT may only be used as a bearer token for authenticating with the Nomad HTTP API as of Nomad 1.5.0.

## Expiration

Nomad should implement expiration and rotation of workload identities to improve JWT security and fix one of the issues preventing it from being used for authentication outside of Nomad's API.

Rotation will need a `change_mode` similar to [`vault` block's](https://developer.hashicorp.com/nomad/docs/job-specification/vault#change_mode):

```hcl
identity {
  env         = true
  change_mode = "restart"
}
```

| change_mode | env | file | valid |
| - | - | - | - |
| noop | any | any | :heavy_check_mark: |
| signal | true | true | :heavy_check_mark: |
| signal | false | true | :heavy_check_mark: 
| signal | true | false | :no_entry:  |
| signal | false | false | :no_entry: |
| restart | true | true | :heavy_check_mark: |
| restart | true | false | :heavy_check_mark: |
| restart | false | true | :heavy_check_mark: |
| restart | false | false | :no_entry: |

Expiration duration and configuration is TBD.

Service jobs with any identity set but a `change_mode = "noop"` should probably emit a warning during job planning/registration.

**Comment by tgross** [comment]
Shipped in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1)
