### ISSUE TITLE
Unexpected loss of capabilities when using Workload Associated ACL Policies

### ISSUE THREAD

**Issue by aofei** [hashicorp/nomad#16276]
### Nomad version

Nomad v1.5.0-rc.1
BuildDate 2023-02-27T21:58:15Z
Revision d65756c82fb53a977da741ac3319a189e8a3e7bd

### Operating system and Environment details

Linux nomad-bug-16276 https://github.com/hashicorp/nomad/pull/36-Ubuntu SMP Mon Jan 23 21:04:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Issue

https://github.com/hashicorp/nomad/blob/542b23e999b5338cdcfa56bfdae1db9aa834cb3c/website/content/docs/concepts/workload-identity.mdx?plain=1#L46-L52

According to the above docs, I can associate **additional ACL policies** with workload identities. IIUC, by "associate additional ACL policies", it means only associate new ACL policies but not disassociate the existing default ACL policy (or any of its capabilities). So the workload identity should just get more capabilities, not lose some implicitly. But it didn't in my test.

### Reproduction steps

1. Create file `foobar.nomad.hcl`:

```hcl
job "foobar" {
	group "foobar" {
		network {
			port "foobar" {}
		}
		task "foobar" {
			driver = "exec"
			config {
				command = "tail"
				args = ["-f", "/dev/null"]
			}
			service {
				port = "foobar"
				provider = "nomad"
			}
			identity {
				env = true
			}
		}
	}
}
```

2. Create file `foobar-job.policy.hcl`:

```hcl
namespace "default" {
	variables {
		path "foobar/*" {
			capabilities = ["read", "list", "write", "destroy"]
		}
	}
}
```

3. Open terminal tab 1 and execute:

```bash
$ sudo nomad agent -dev -acl-enabled
```

4. Open terminal tab 2 and execute:

```bash
$ nomad acl bootstrap
$ export NOMAD_TOKEN=<The Bootstrap Token>
$ nomad run foobar.nomad.hcl
$ # Wait until the job deploys successfully.
$ nomad alloc exec -job foobar nomad service list
$ # The output should be:
$ # Service Name          Tags
$ # foobar-foobar-foobar  []
$ nomad acl policy apply -namespace default -job foobar foobar-job-policy foobar-job.policy.hcl
$ nomad alloc exec -job foobar nomad service list
$ # The output should be:
$ # Error listing service registrations: Unexpected response code: 403 (Permission denied)
```

**Comment by tgross** [comment]
Hi @aofei I was able to reproduce this. At first glance I thought this might have something to do with our authentication code on the service registration API but I whipped up a quick addition to our unit tests and didn't reproduce there:

```diff
diff --git a/nomad/service_registration_endpoint_test.go b/nomad/service_registration_endpoint_test.go
index 9d198e0cb..8010fdd9e 100644
--- a/nomad/service_registration_endpoint_test.go
+++ b/nomad/service_registration_endpoint_test.go
@@ -5,7 +5,7 @@ import (
        "testing"

        "github.com/hashicorp/go-memdb"
-       "github.com/hashicorp/net-rpc-msgpackrpc"
+       msgpackrpc "github.com/hashicorp/net-rpc-msgpackrpc"
        "github.com/hashicorp/nomad/acl"
        "github.com/hashicorp/nomad/ci"
        "github.com/hashicorp/nomad/nomad/mock"
@@ -888,6 +888,24 @@ func TestServiceRegistration_List(t *testing.T) {

                                signedToken := allocs[0].SignedIdentities["web"]

+                               // Associate an unrelated policy with that identity on the
+                               // platform namespace to ensure it doesn't conflict.
+                               policy := &structs.ACLPolicy{
+                                       Name: "policy-for-identity",
+                                       Rules: mock.NamespacePolicyWithVariables(
+                                               "platform", "", []string{"list-jobs"},
+                                               map[string][]string{
+                                                       "dropbox/*": {"write"},
+                                               }),
+                                       JobACL: &structs.JobACL{
+                                               Namespace: "platform",
+                                               JobID:     job.ID,
+                                       },
+                               }
+                               policy.SetHash()
+                               must.NoError(t, s.State().UpsertACLPolicies(structs.MsgTypeTestSetup, 16,
+                                       []*structs.ACLPolicy{policy}))
+
                                // Generate and upsert some service registrations.
                                services := mock.ServiceRegistrations()
                                require.NoError(t, s.State().UpsertServiceRegistrations(
```

I'll pick this up again tomorrow and see if I can figure it out.

**Comment by aofei** [comment]
There's one other thing I found in testing that I didn't mention because I didn't think it was relevant (I thought maybe I was wrong about using it at all). Somehow the auto-granted `read` and `list` capabilities for `nomad/jobs/` prefixed variables are always there, even if I explicitly deny it like this:

```hcl
namespace "default" {
	variables {
		path "nomad/jobs/*" {
			capabilities = ["deny"]
		}
	}
}
```

The reason why I think it's not normal is because I read this line in the docs:

https://github.com/hashicorp/nomad/blob/f89910d4650c47006838a7b6de17cbacdc62fe1c/website/content/docs/other-specifications/acl-policy.mdx?plain=1#L205

**Comment by tgross** [comment]
Thanks for that extra info @aofei. The next thing I wanted to verify is that the problem wasn't with the new Task API socket, which has some complex logic around pulling down ACL policies. But it looks like that's not the case; in this test I grabbed the Workload Identity token we gave the task and used it directly:

```sh
$ nomad alloc exec a833 env | grep NOMAD_TOKEN
# (copy paste)
$ NOMAD_TOKEN=<redacted> nomad service list
Service Name          Tags
foobar-foobar-foobar  []

$ nomad acl policy apply -namespace default -job foobar foobar-policy policy.hcl
Successfully wrote "foobar-policy" ACL policy!

$ NOMAD_TOKEN=<redacted> nomad service list
Error listing service registrations: Unexpected response code: 403 (Permission denied)
```

So there is a problem in the server-side auth logic and my test above just isn't hitting it. I'll dig into this some more and circle back here shortly.

**Comment by tgross** [comment]
@aofei after a chat with our security folks we've decided the `deny` override problem is going to need to be a security advisory, even if it is a bit of an edge case. So a new issue won't be opened for that immediately as we go through our security process but we'll get a fix out in the next patch.
