### ISSUE TITLE
[feature] systemd-nspawn driver

### ISSUE THREAD

**Issue by juaningan** [hashicorp/nomad#1627]
Have any sense to ask for a systemd-nspawn driver or with raw_exec will be enough?

**Comment by dadgar** [comment]
Hey we will most likely not be merging any more drivers into Nomad core. We will have a plugin system such that new drivers can be created through plugins! Thanks

**Comment by Ashald** [comment]
Although, considering "latest trends" the nspawn driver would've been a nice addition to the core... :(
