### ISSUE TITLE
[UI] "Job Status in Client" panel always shows all zero data when `datacenters = ["*"]`

### ISSUE THREAD

**Issue by aofei** [hashicorp/nomad#16270]
### Nomad version

Nomad v1.5.0-rc.1
BuildDate 2023-02-27T21:58:15Z
Revision d65756c82fb53a977da741ac3319a189e8a3e7bd

### Operating system and Environment details

Linux nomad-bug-16270 #36-Ubuntu SMP Mon Jan 23 21:04:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Issue

![Untitled](https://user-images.githubusercontent.com/5037285/221765887-73f37194-a0e2-4c0d-9c4b-f537fc546dfa.png)

### Job file

```diff
job "foobar" {
	type = "system"
-	datacenters = ["dc1"]
+	datacenters = ["*"]
	group "foobar" {
		task "foobar" {
			driver = "exec"
			config {
				command = "tail"
				args = ["-f", "/dev/null"]
			}
		}
	}
}
```

**Comment by aofei** [comment]
It's just a UI display bug (I think so), `nomad job status foobar` prints expected data.

**Comment by jrasell** [comment]
Hi @aofei and thanks for raising this issue. I have not been able to reproduce this locally, so wondered if you could provide any additional details regarding the steps you took to see this problem?

**Comment by aofei** [comment]
Sorry, I've omitted specific steps since it's easy to reproduce.

### Reproduction steps

1. Open terminal tab 1 and execute:

```bash
$ sudo nomad agent -dev
```

2. Create file `foobar.nomad.hcl`:

```hcl
job "foobar" {
	type = "system"
	datacenters = ["dc1"]
	group "foobar" {
		task "foobar" {
			driver = "exec"
			config {
				command = "tail"
				args = ["-f", "/dev/null"]
			}
		}
	}
}
```

3. Open terminal tab 2 and execute:

```bash
$ nomad run foobar.nomad.hcl
$ # Wait until the job deploys successfully.
$ # Now go to check http://127.0.0.1:4646/ui/jobs/foobar@default.
$ # Everything should work fine at this point.
$ sed -i 's/dc1/*/g' foobar.nomad.hcl
$ nomad run foobar.nomad.hcl
$ # Wait until the job deploys successfully.
$ # Now go to check http://127.0.0.1:4646/ui/jobs/foobar@default.
$ # At this time, the "Job Status in Client" panel should show all zero data.
```

**Comment by aofei** [comment]
OK, I did forget about an important detail in OP. 😓 The `type` of job must be `system` to reproduce this bug.

**Comment by jrasell** [comment]
Hi @aofei and thanks for the additional detail. I was able to reproduce this locally, and it seems this can be triggered by submitting a system job using the datacenter wildcard initially. I'll pass this to our UI engineers to take a better look.
