### ISSUE TITLE
Document default ACL policy for Workload

### ISSUE THREAD

**Issue by aofei** [hashicorp/nomad#16277]
To work around #16276, I dug into the source code to find the default ACL policy for Workload, which took me a while. I was actually curious about the default ACL policy before I encountered #16276. But I'm too lazy to search the code so gave up on figuring it out. So I thought it might be a good idea for people to have a "Workload Default ACL Policy" section in [workload-identity.mdx](https://github.com/hashicorp/nomad/blob/542b23e999b5338cdcfa56bfdae1db9aa834cb3c/website/content/docs/concepts/workload-identity.mdx).

**Comment by tgross** [comment]
Hi @aofei! This is definitely a documentation gap. The default policy isn't a "real" policy but some special exceptions for Variables and Service Registration (those exceptions are the source of https://github.com/hashicorp/nomad/issues/16276 which I'm working on with you). The Variables policy is documented at [Task Access to Variables](https://developer.hashicorp.com/nomad/docs/concepts/variables#task-access-to-variables) but that's neither complete nor the right place to have it. Marking this as a documentation gap to fix.

**Comment by tgross** [comment]
Opened #17245 to get that documentation up.
