### ISSUE TITLE
Limit "resources.cores" does not work after nomad client restart

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#16291]
Hello.
We test `resources.cores` for nomad jobs and found a bug: after nomad client restart, cores limit does not work. 

### Nomad version
Nomad v1.4.2 (039d70eeef5888164cad05e7ddfd8b6f8220923b)

### Operating system and Environment details
Codename:	focal

### Reproduction steps
1. Run job:
```
# job name
job "cpu-loader" {
  region      = "global"
  datacenters = ["dc1"]

  type = "service"

  meta {
      ...
  }

  group "cpu-loader-group" {
    count = 1

    # task
    task "cpu-loader-task" {
      kill_signal = "SIGTERM"
      driver = "docker"

      config {
        image        = "docker-image"
      }

      env {
          ...
      }

      resources {
       memory = 1000
       cores  = 4 
      }
    }
  }
}
```
2. Stop job
3. Restart nomad client
4. Run job again

(for loader we used: https://github.com/vikyd/go-cpu-load )

#### Expected Result
Job used only 4 cores

#### Actual Result
Job used more than 4 core

**Comment by RobloxMatt** [comment]
We've seen something that sounds like this problem as well.  Do you see something like this in your logs?

`client.cpuset.v1: failed to ensure reserved cpuset.cpus interface exists; disable cpuset management: error="mkdir /sys/fs/cgroup/cpuset/nomad/reserved: file exists"`

or

`[WARN]  client.cpuset.v1: failed to ensure reserved cpuset.cpus interface exists; disable cpuset management: error="mkdir /sys/fs/cgroup/cpuset/nomad/reserved: file exists"`

**Comment by shoenig** [comment]
Thanks for the report @TheSpbra1n and for the logs @RobloxMatt, it seems this got broken during a refactoring in https://github.com/hashicorp/nomad/commit/0a3d57f7e4603e264daed73a569ac4369e25163b where we (I) missed the edge case where the cgroup structure is already set on Client initialization. Should only affect machines using cgroups v1.
