### ISSUE TITLE
looking for nomad executable is checking gopath twice

### ISSUE THREAD

**Issue by mgenov** [hashicorp/nomad#163]
The NomadExecutable function is checking twice where executable is in GOPATH instead of checking and the current working directory as comment says. 

```go
      // Check the $GOPATH.
       bin = filepath.Join(os.Getenv("GOPATH"), "bin", nomadExe)
       if _, err := os.Stat(bin); err == nil {
                return bin, nil
       }

      // Check the CWD.
      bin = filepath.Join(os.Getenv("GOPATH"), "bin", nomadExe)
      if _, err := os.Stat(bin); err == nil {
                return bin, nil
      }
```

Could be changed to: 
```go
      // Check the $GOPATH.
       bin = filepath.Join(os.Getenv("GOPATH"), "bin", nomadExe)
       if _, err := os.Stat(bin); err == nil {
                return bin, nil
       }

      // Check the CWD.
      bin = filepath.Join(os.Getenv("PWD"), "bin", nomadExe)
      if _, err := os.Stat(bin); err == nil {
                return bin, nil
      }
```

**Comment by ryanuber** [comment]
Hmm, looks like something that could maybe just be solved by scanning `$PATH` plus the local directory for the nomadExe though I'm not sure about cross-platform in that case. Marking as an enhancement, thanks! /cc @dadgar

**Comment by ryanuber** [comment]
Changed to a bug since we actually aren't scanning the local dir, almost missed that.

**Comment by dadgar** [comment]
Fixed https://github.com/hashicorp/nomad/commit/2351a97776a0a9f534cff340bfe5195713298784
