### ISSUE TITLE
Executing shell scripts in `secrets` directory always gets "Permission denied"

### ISSUE THREAD

**Issue by aofei** [hashicorp/nomad#16308]
### Nomad version

Nomad v1.5.0
BuildDate 2023-03-01T10:11:42Z
Revision fc40c491cacec3d8ec3f2f98cd82b9068a50797c

### Operating system and Environment details

```bash
$ hostnamectl
 Static hostname: dev-machine
       Icon name: computer-vm
         Chassis: vm
      Machine ID: ebe933b74fe25215fc0f3b0be782a241
         Boot ID: 1051fac2caf742699078f5e6c97161b9
  Virtualization: kvm
Operating System: Ubuntu 22.04.2 LTS
          Kernel: Linux 5.15.0-1030-gcp
    Architecture: x86-64
 Hardware Vendor: Google
  Hardware Model: Google Compute Engine
```

### Issue

I keep getting `Permission denied` when executing shell scripts rendered into the `secrets` directory.

### Reproduction steps

1. Create file `foobar.nomad.hcl`:

```hcl
job "foobar" {
	group "foobar" {
		task "foobar" {
			driver = "exec"
			config {
				command = "tail"
				args = ["-f", "/dev/null"]
			}
			template {
				destination = "secrets/hello.sh"
				perms = "777"
				data = <<EOF
#!/bin/sh
echo "Hello, Nomad!"
EOF
			}
		}
	}
}
```

2. Open terminal tab 1 and execute:

```bash
$ sudo nomad agent -dev
```

3. Open terminal tab 2 and execute:

```bash
$ nomad run foobar.nomad.hcl
$ # Wait until the job deploys successfully.
$ nomad alloc exec -job foobar sh
$ /secrets/hello.sh
$ # The output should be:
$ # sh: 1: /secrets/hello.sh: Permission denied
$ sh /secrets/hello.sh
$ # The output should be:
$ # Hello, Nomad!
$ mv /secrets/hello.sh /local
$ /local/hello.sh
$ # The output should be:
$ # Hello, Nomad!
```

### Other things to say

The same error happens with `docker` driver.

I'm not sure if this is a bug or an unsupported feature (given that the `secrets` directory is usually backed by an in-memory filesystem). But GitHub Search failed to find any similar issues for me, so I decided to open this one.

**Comment by tgross** [comment]
Hi @aofei! If you look at the file permissions you'll see that they're being set as expected from `template`:

```sh
$ nomad alloc exec -job foobar /bin/sh
$ ls -lah /secrets
total 13K
drwxrwxrwx  2 nobody nogroup 100 Mar  3 16:23 .
drwxrwxrwx 17 root   root     18 Mar  3 16:23 ..
srw-rw-rw-  1 root   root      0 Mar  3 16:23 api.sock
-rwxrwxrwx  1 root   root     31 Mar  3 16:23 hello.sh
-rw-r--r--  1 root   root      0 Mar  3 16:23 .nomad-mount
$ /secrets/hello.sh
/bin/sh: 4: /secrets/hello.sh: Permission denied
$ whoami
nobody
```

However, the secrets dir `tmpfs` is mounted `noexec` (on Linux). You can see the code for this in [`fs_linux.go`](https://github.com/hashicorp/nomad/blob/v1.5.0/client/allocdir/fs_linux.go#L58)

```
$ mount  | grep secrets
tmpfs on /var/nomad/data/client/51c98578-6268-ae03-3641-090bdfc3ed8b/foobar/secrets type tmpfs (rw,noexec,relatime,size=1024k,inode64)
```

This certainly seems like something we could document better in the [filesystem documentation](https://developer.hashicorp.com/nomad/docs/concepts/filesystem)
