### ISSUE TITLE
Github latest tag does not track the latest release

### ISSUE THREAD

**Issue by Rumbles** [hashicorp/nomad#16310]
### Nomad version
This issue is related to your release process, not nomad itself.

### Issue
With the latest releases on your release page, 1.5.0 has been released, as well as 1.4.5, but it appears that since 1.3.10 was built after those images, it is marked as 'latest' which it is not, would it be possible to change your release process to build the latest release last, or change it so the highest version number is marked as latest?

I ask as we have some automations that find your latest release and created a PR for us to review when there is a new latest release, which is currently offering to downgrade nomad to 1.3.10 for me.

### Reproduction steps
Look at your release page

#### Expected Result
Highest version number should be 'latest'

#### Actual Result
Most recently built version is latest regardless of whether this is the highest version

**Comment by jrasell** [comment]
Hi @Rumbles, thanks for raising this issue. This is something we discussed yesterday and have added to our release process for the next release. I have made the change required to mark 1.5.0 as the latest release. Thanks again!
