### ISSUE TITLE
`nomad fmt` rejects proper HCL syntax

### ISSUE THREAD

**Issue by mohammed90** [hashicorp/nomad#16312]
### Nomad version
```
Nomad v1.5.0
BuildDate 2023-03-01T10:11:42Z
Revision fc40c491cacec3d8ec3f2f98cd82b9068a50797c
```

### Operating system and Environment details
macOS
### Issue
The `nomad fmt` command reports an error on lines without errors, [per the docs](https://developer.hashicorp.com/nomad/docs/configuration/client#options-parameters).
### Reproduction steps
Run `nomad fmt` against a file with the following content:
```
data_dir   = "/nomad/data"
client {
  enabled = true
  options {
    "driver.whitelist" = "docker"
  }
}
```

#### Expected Result
Nothing
#### Actual Result
```
Error: Invalid argument name

  on client.hcl line 10:
  10:     "driver.whitelist" = "docker"

Argument names must not be quoted.
```

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

**Comment by tgross** [comment]
Hi @mohammed90! Just a heads up that I'd only expect `nomad fmt` to work when using non-deprecated HCL2 job specs and config files. This definitely should be better documented (and we really do need to get around to cleaning up those old config values).
