### ISSUE TITLE
ACL token creation fails in a mixed 1.5 + 1.4 environment

### ISSUE THREAD

**Issue by carobme** [hashicorp/nomad#16311]
### Nomad version
Servers:
```
Nomad v1.4.4 (7f29429be12098e0f3a09df959d9272aa0654cba)
```

Cli:
```
Nomad v1.5.0
BuildDate 2023-03-01T10:11:42Z
Revision fc40c491cacec3d8ec3f2f98cd82b9068a50797c
```

### Operating system and Environment details
Servers: AlmaLinux 8
Cli: Ubuntu 22.10

### Issue

Updated to Nomad 1.5 on my laptop (where I usually invoke the cli) this morning. Wanted to create a new ACL token on a cluster that runs 1.4.4. This failed with the error below. Looks like some incompatibility between 1.5 and 1.4 when using the `/v1/acl/token` endpoint to me. Possibly related to https://github.com/hashicorp/nomad/pull/15999?

### Reproduction steps
Just running:

```console
nomad acl token create --name=foo --type=client
```

#### Expected Result
Token gets created successfully.

#### Actual Result
Creating the token fails with 

```console
Error creating token: Unexpected response code: 400 (json: cannot unmarshal string into Go struct field ACLToken.ExpirationTTL of type time.Duration)
```

(The same happens if I specify e.g. `--ttl=1h`.)

### Nomad Server logs (if appropriate)
```
[DEBUG] http: request failed: method=PUT path="/v1/acl/token?namespace=%2A" error="json: cannot unmarshal string into Go struct field ACLToken.ExpirationTTL of type time.Duration" code=400
[DEBUG] http: request complete: method=PUT path="/v1/acl/token?namespace=%2A" duration="364.503µs"    
```

### Nomad Client logs (if appropriate)

**Comment by carobme** [comment]
I guess this is fixed in 1.4.5: https://github.com/hashicorp/nomad/pull/16005

**Comment by jrasell** [comment]
Hi @carobme, yes this should be fixed by the PR you linked. I'll keep this open and assigned it myself; please let us know your results once you've had a chance to test. Thanks!

**Comment by carobme** [comment]
Updated the servers to `1.4.4`: Creating ACL tokens from the `1.5.0` cli works again. Closing the issue. Thanks @jrasell!
