### ISSUE TITLE
Nomad does not mark deployment as successful with dynamic service names

### ISSUE THREAD

**Issue by Blefish** [hashicorp/nomad#16382]
### Nomad version
Output from `nomad version`
Nomad v1.4.5,  v1.5.0
### Operating system and Environment details
Linux Mint 21.1
### Issue
Services with dynamic names never report healthy deployment status, although services are healthy in Consul view. Seems to be occuring after #15822 , could it be that dynamic service name is not being evaluated before validating the service checks?
#### Expected Result
Service healthiness result from Consul is forwarded to Nomad and deployment is successful.
#### Actual Result
Service healthiness is not received by Nomad and deployment is marked as failed after a while.
### Job file (if appropriate)
A service which uses custom name that is dynamically evaluated (NOMAD_GROUP_NAME, NOMAD_JOB_NAME or similar)
```
service {
  name = "${NOMAD_JOB_NAME}"
  port = "grpc"
  check {
    type = "grpc"
    interval = "10s"
    timeout = "5s"
    check_restart {
      limit = 3
      grace = "90s"
      ignore_warnings = false
    }
  }
}
```

**Comment by lgfa29** [comment]
Thanks for the report @Blefish, your analysis was correct and there was a bug in https://github.com/hashicorp/nomad/pull/15822 where were not interpolating service values. I opened https://github.com/hashicorp/nomad/pull/16402 to fix this.
