### ISSUE TITLE
task health check to kill & replace

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/nomad#164]
It would be great to be able to register a task health check in a job definition (a la Consul) that, optionally, could be leveraged by Nomad to kill and replace a failed task.

**Comment by cbednarski** [comment]
This will be included in our consul integration (probably in 0.2).

**Comment by c4milo** [comment]
This would be really nice to have. Are there any updates @cbednarski?

**Comment by abhidrona** [comment]
@cbednarski is this already implemented?

**Comment by dadgar** [comment]
@abhidrona No it is not! Nomad will register services and checks but does not use the state of the checks to restart tasks.

**Comment by stongo** [comment]
I'm not sure what the priority is for this, but IMHO it should be of highest priority.
Using service health checks but no task health checks, Nomad creates a zombie fleet of tasks.
What exactly is the point of having unhealthy jobs non-discoverable but still running?

**Comment by memelet** [comment]
This also is one of the very issues that keep us from switching over from mesos to nomad. (We run nomad in our staging, but can't afford to manually restart tasks in production.)

**Comment by dadgar** [comment]
Closing in favor of https://github.com/hashicorp/nomad/issues/164 given more people have seen that one.

**Comment by c4milo** [comment]
@dadgar this is #164

**Comment by dadgar** [comment]
Fixed reference! My bad!
