### ISSUE TITLE
Clients working behind NAT

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#1640]
Last time I checked nomad had issues running worker nodes behind NAT.

My usecase: I'd like nomad servers to run in the cloud, but nomad clients to run on my machine and execute tasks. This is a model that new docker swarm model allows in docker 1.12, but I'd like to nomad without docker installed (many clouds don't allow it, e.g. because there's missing TUN interface, or cgroups is not available).

Is it currently possible to run worker nodes behind NAT?

Are there plans to support it?

**Comment by dadgar** [comment]
Nomad clients dial the Servers and hold long lived TCP connections so I don't think it would be a problem. We can open if it is

**Comment by sheerun** [comment]
@dadgar Could you test and document network connectivity requirements on https://www.nomadproject.io/docs/cluster/requirements.html ?

**Comment by sheerun** [comment]
@dadgar It seems client need public ip address for `nomad logs` command to work.. So they aren't working properly behind a NAT. Am I wrong? Could nomad implement something like https://github.com/fatedier/frp ?

**Comment by dadgar** [comment]
@sheerun Nomad logs won't work because the CLI is dialing the agent but it is a NATed connection but the client should be able to run tasks just fine. I am going to re-open this issue and use this to track the use case of enabling proxying for the HTTP endpoints.

**Comment by sheerun** [comment]
@dadgar What about RPC?

**Comment by dadgar** [comment]
RPC should work because clients dial the servers not the other way.

**Comment by dadgar** [comment]
Solved by https://github.com/hashicorp/nomad/pull/3892
