### ISSUE TITLE
[question] Recommended approach for accessing docker.sock until we have docker volume support

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#1642]
Until we have general volume support for docker containers I can use the alloc and local mounts plus artifacts for some of my needs but I'm stuck on access to docker.sock so I can run Registrator. 

Anyone got a recommended approach for maybe exposing docker.sock inside the local mountpoint or something?

**Comment by far-blue** [comment]
In case people wonder why I'm using Registrator and not Nomad's service support for Consul see #1124 and #511 :)

**Comment by dadgar** [comment]
If you use raw_exec you should be able to access this. I am going to close as we will not be facilitating access to the docker.sock
