### ISSUE TITLE
[question] how does nomad communicate between server and client in difference  AZ of AWS

### ISSUE THREAD

**Issue by xudawei** [hashicorp/nomad#1643]
### Nomad version
Nomad v0.4.1

### Operating system and Environment details
Centos7 on AWS
### Issue
In the difference AZ , means difference subnet ,  the rpc protocal cannot be used cross the difference subnet. 

How can i do and make the agent works. 
* Maybe i can set one or two nomad server in every subnet. but i think it's not a good idea . 
Beacase there will be more than 7 servers in one region .  it's too much 

### Nomad Client logs (if appropriate)
   Loaded configuration from client.hcl, base.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: true
             Log Level: INFO
                Region: cn-north-1 (DC: dc2)
                Server: false

==> Nomad agent started! Log data will stream in below:

    2016/08/23 15:20:03.579802 [INFO] client: using state directory /opt/nomad/data/client
    2016/08/23 15:20:03.579831 [INFO] client: using alloc directory /opt/nomad/data/alloc
    2016/08/23 15:20:03.579999 [INFO] fingerprint.cgroups: cgroups are available
    2016/08/23 15:20:03.614738 [WARN] fingerprint.network: Unable to parse Speed in output of '/sbin/ethtool eth0'
    2016/08/23 15:20:03.617909 [ERR] client: failed to query for node allocations: RPC failed to server 172.16.0.154:4649: rpc error: failed to get conn: rpc error: lead thread didn't get connection

**Comment by dadgar** [comment]
You can set the `advertise` addresses of the servers to that of an IP that is accessible by all the AZs

https://www.nomadproject.io/docs/agent/config.html#advertise
