### ISSUE TITLE
[question] No statsd allocations metrics 

### ISSUE THREAD

**Issue by jtuthehien** [hashicorp/nomad#1644]
Nomad doesnt seem to output allocations metrics like this keys:
nomad.client.allocs.<Job>.<TaskGroup>.<AllocID>.<Task>.memory.rss	Amount of RSS memory consumed by the task	Bytes	Gauge

Below is snapshot of data sent by nomad
Is there any special configuration needed to enable those

nomad.raft.rpc.appendEntries:0.011216|ms
nomad.nomad.worker.dequeue_eval:501.203644|ms
nomad.nomad.worker.dequeue_eval:501.222229|ms
nomad.raft.rpc.appendEntries:0.008210|ms
nomad.raft.rpc.appendEntries:0.005697|ms
nomad.raft.rpc.processHeartbeat:0.034734|ms
nomad.raft.rpc.appendEntries:0.011049|ms
nomad.staging-nomad1-231.nomad.broker.total_ready:0.000000|g
nomad.staging-nomad1-231.nomad.broker.total_unacked:0.000000|g
nomad.raft.rpc.appendEntries:0.006651|ms
nomad.staging-nomad1-231.nomad.broker.total_blocked:0.000000|g
nomad.staging-nomad1-231.nomad.broker.total_waiting:0.000000|g
nomad.raft.rpc.processHeartbeat:0.027446|ms
nomad.memberlist.gossip:0.016505|ms
nomad.raft.rpc.appendEntries:0.010649|ms
nomad.raft.rpc.appendEntries:0.012540|ms
nomad.raft.rpc.appendEntries:0.007762|ms
nomad.raft.rpc.appendEntries:0.003279|ms
nomad.raft.rpc.processHeartbeat:0.019062|ms
nomad.staging-nomad1-231.runtime.num_goroutines:96.000000|g
nomad.staging-nomad1-231.runtime.alloc_bytes:4005472.000000|g
nomad.staging-nomad1-231.runtime.sys_bytes:21416184.000000|g
nomad.staging-nomad1-231.runtime.malloc_count:818032960.000000|g
nomad.staging-nomad1-231.runtime.free_count:818002560.000000|g
nomad.staging-nomad1-231.runtime.heap_objects:30439.000000|g
nomad.staging-nomad1-231.runtime.total_gc_pause_ns:17225768960.000000|g
nomad.staging-nomad1-231.runtime.total_gc_runs:25802.000000|g
nomad.runtime.gc_pause_ns:451040.000000|ms
nomad.raft.rpc.appendEntries:0.008690|ms
nomad.staging-nomad1-231.nomad.plan.queue_depth:0.000000|g
nomad.staging-nomad1-231.nomad.blocked_evals.total_blocked:0.000000|g
nomad.staging-nomad1-231.nomad.blocked_evals.total_escaped:0.000000|g
nomad.serf.queue.Query:0.000000|ms
nomad.serf.queue.Intent:0.000000|ms
nomad.nomad.worker.dequeue_eval:501.206787|ms
nomad.nomad.worker.dequeue_eval:501.014496|ms
nomad.nomad.rpc.accept_conn:1.000000|c
nomad.raft.rpc.appendEntries:0.031330|ms
nomad.raft.rpc.appendEntries:0.007175|ms
nomad.raft.rpc.processHeartbeat:0.038290|ms
nomad.raft.rpc.appendEntries:0.010528|ms
nomad.nomad.worker.dequeue_eval:501.091522|ms
nomad.nomad.worker.dequeue_eval:501.325989|ms
nomad.raft.rpc.appendEntries:0.011300|ms
nomad.memberlist.gossip:0.018554|ms
nomad.raft.rpc.appendEntries:0.005256|ms
nomad.raft.rpc.processHeartbeat:0.028387|ms
nomad.raft.rpc.appendEntries:0.007294|ms
nomad.serf.queue.Event:0.000000|ms
nomad.raft.rpc.appendEntries:0.010789|ms
nomad.raft.rpc.appendEntries:0.026128|ms
nomad.raft.rpc.appendEntries:0.006995|ms
nomad.raft.rpc.processHeartbeat:0.040673|ms
nomad.nomad.worker.dequeue_eval:501.168793|ms
nomad.nomad.worker.dequeue_eval:501.251221|ms
nomad.raft.rpc.appendEntries:0.008317|ms
nomad.raft.rpc.appendEntries:0.013382|ms
nomad.raft.rpc.appendEntries:0.007554|ms
nomad.raft.rpc.processHeartbeat:0.045136|ms
nomad.nomad.worker.dequeue_eval:500.928101|ms
nomad.nomad.worker.dequeue_eval:501.280914|ms
nomad.raft.rpc.appendEntries:0.009234|ms
nomad.raft.rpc.appendEntries:0.011109|ms
nomad.memberlist.gossip:0.018307|ms
nomad.staging-nomad1-231.nomad.broker.total_ready:0.000000|g
nomad.staging-nomad1-231.nomad.broker.total_unacked:0.000000|g
nomad.staging-nomad1-231.nomad.broker.total_blocked:0.000000|g
nomad.staging-nomad1-231.nomad.broker.total_waiting:0.000000|g
nomad.raft.rpc.appendEntries:0.006532|ms
nomad.raft.rpc.processHeartbeat:0.035618|ms
nomad.raft.rpc.appendEntries:0.008360|ms

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version 0.4.1
Output from `nomad version`

**Comment by diptanu** [comment]
Publishing allocation and host runtime metrics has to be explicitly turned on by setting the `publish_allocation_metrics` and `publish_node_metrics` to `true` in the `telemetry` section of the agent config.
