### ISSUE TITLE
Nomad Deployments disappears

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#16474]
### Nomad version
Nomad v1.5.1
BuildDate 2023-03-10T22:05:57Z
Revision 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7

### Consul version
Consul v1.15.1
Revision 7c04b6a0
Build Date 2023-03-07T20:35:33Z

### Operating system and Environment details
Ubuntu 22.04 In VMWare Worksation 
Single Node Master
Single Node Worker

After booting up the vms the deployment status of nomad job disappears sometimes 

The commad deployment list does not show the deloyment

Expetected screen 

![image](https://user-images.githubusercontent.com/5046525/224955839-47f44a7d-eb75-45b0-a265-3d8787dbf5d9.png)

But got 
![image](https://user-images.githubusercontent.com/5046525/224955983-8bff9285-e2ab-454b-b94c-93400b930f56.png)

**Comment by suikast42** [comment]
If I stop and start the job from the nomad ui then the deloyments shows again

**Comment by philrenaud** [comment]
Hi @suikast42 — the deployments panel is dependent on your job having a property called `latestDeployment`, which is exactly what you'd expect it to be. Deployment objects are garbage collected after a length of time, at which point this panel would stop being shown.

If you click into the "Deployments" tab in your job subnav, so long as you have deployments listed there, you should also see one on your main job index page.

I'm hoping that this isn't a situation where the panel disappears after mere moments — if so please let me know and I'll help investigate this further — and is just normal system garbage collection taking its course.

**Comment by suikast42** [comment]
Thanks for clarification. I have an eye on that ;-)

**Comment by suikast42** [comment]
> Hi @suikast42 — the deployments panel is dependent on your job having a property called `latestDeployment`, which is exactly what you'd expect it to be. Deployment objects are garbage collected after a length of time, at which point this panel would stop being shown.
> 
> If you click into the "Deployments" tab in your job subnav, so long as you have deployments listed there, you should also see one on your main job index page.
> 
> I'm hoping that this isn't a situation where the panel disappears after mere moments — if so please let me know and I'll help investigate this further — and is just normal system garbage collection taking its course.

Nop the deployments tab is empty 
![image](https://user-images.githubusercontent.com/5046525/225562155-e0ca9fa3-f1b3-42d4-bf73-19256f050d02.png)
