### ISSUE TITLE
Private Git artifact download fails after upgrade to v1.5.1

### ISSUE THREAD

**Issue by Zygimantass** [hashicorp/nomad#16493]
### Nomad version
```
Nomad v1.5.1
BuildDate 2023-03-10T22:05:57Z
Revision 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7
```
### Operating system and Environment details
```
Linux nomad-client-05 5.15.0-1022-aws #26~20.04.1-Ubuntu SMP Sat Oct 15 03:22:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
### Issue

Go-getter fails to download artifact from a private Git repo with filesystem isolation disabled or enabled. (in this case, it's disabled)

### Reproduction steps

```
nomad job run repro.nomad
```

#### Expected Result

Go-getter properly downloads the artifact

#### Actual Result

The job fails due to go-getter crashing with exit code 1 because of the denied permissions.

### Job file (if appropriate)

```
job "repro" {
  type        = "service"

  group "repro" {
    count = 1

    volume "data" {
      type = "csi"
      read_only = false
      source = "job-volume"
      access_mode = "single-node-writer"
      attachment_mode = "file-system"
    }

    task "init" {
      driver = "docker"

      volume_mount {
        volume = "data"
        destination = "/opt/data"
        read_only = false
      }

      artifact {
        source = "git::git@github.com:org/repo"
        destination = "local/tmp/data"

        options {
          sshkey = "<base64 encoded ssh key>"
        }
      }

      config {
        image = "busybox:1.28"
        command = "sh"
        args = ["-c", "/tmp/init.sh"]
        volumes = ["local/tmp/data:/tmp/data", "local/tmp/init.sh:/tmp/init.sh"]
      }

      template {
        data = <<EOH
          rm -rf /opt/data/config
          cp -r /tmp/data/config /opt/data/config
        EOH

        perms = "777"
        destination = "local/tmp/init.sh"
      }
      
      resources {
        cpu = 200
        memory = 128
      }

      lifecycle {
        hook = "prestart"
        sidecar = false
      }
    }

    task "job" {
      driver = "docker"

      volume_mount {
        volume = "data"
        destination = "/opt/data/"
        read_only = false
      }

      config {
        image = "nicolaka/netshoot:latest"
        command = "sh"
        args = ["-c", "sleep 10110000"]
      }

      resources {
        cpu    = 200
        memory = 200
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

```
Mar 14 17:49:55 nomad-client-05 nomad[30661]:     2023-03-14T17:49:55.032Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=c4d60ac3-5820-6b88-9a37-d47aa81baade task=init type="Downloading Artifacts" msg="Client is downloading artifacts" failed=false
Mar 14 17:49:55 nomad-client-05 nomad[30661]:     2023-03-14T17:49:55.052Z [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: error downloading 'ssh://git@github.com/org/repo?sshkey=redacted': open /var/nomad/alloc/c4d60ac3-5820-6b88-9a37-d47aa81baade/init/tmp/go-getter1659107024: permission denied"
Mar 14 17:49:55 nomad-client-05 nomad[30661]:     2023-03-14T17:49:55.052Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=c4d60ac3-5820-6b88-9a37-d47aa81baade task=init type="Failed Artifact Download" msg="failed to download artifact \"git::git@github.com:org/repo\": getter subprocess failed: exit status 1" failed=false
Mar 14 17:49:55 nomad-client-05 nomad[30661]:     2023-03-14T17:49:55.054Z [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=c4d60ac3-5820-6b88-9a37-d47aa81baade task=init error="prestart hook \"artifacts\" failed: failed to download artifact \"git::git@github.com:org/repo\": getter subprocess failed: exit status 1"
```

### Nomad client config

```
datacenter = "dc"
data_dir = "/var/nomad"

client {
    enabled = true

    artifact {
      disable_filesystem_isolation = true
    }
}

plugin "docker" {
  config {
    allow_privileged = true
  }
}

advertise {
  http = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}:4646"
  rpc  = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}:4647"
  serf = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}:4648"
}
```

**Comment by shoenig** [comment]
Hi @Zygimantass, what user is Nomad Client running as? 

And can you post the output of 
```
nomad node status -verbose <id>
```

for the `<id>` of the node where the error is occurring?

**Comment by Zygimantass** [comment]
I've downgraded our cluster to v1.4.4, but I can set up a v1.5.1 client for testing tomorrow.

**Comment by wietmann** [comment]
Explicitly adding github SSH host keys to `/etc/ssh/ssh_known_hosts` solved this for me.
It seems that since 1.5.0 artifacts are fetched under non-root user: https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#artifact-download-sandboxing and keys in `/root/.ssh/known_hosts` is not reachable for it.

**Comment by Narmac** [comment]
Is this still active?

I am having the same issue with http artifact as well:

      artifact {
        source      = "http://user:passwd@url.com/uri"
        destination = "local/data-dir"
      }


In Nomad:
     
 `failed to download artifact "http://user:passwed@url.com/uri": getter subprocess failed: exit status 1
 `
 
 in syslog:
 
 `Mar 20 12:05:32 nomad-clientnomad[68488]:     2023-03-20T12:05:32.236-0400 [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: Error creating temporary directory for archive: mkdir /opt/nomad/data/alloc/b45a0e9e-6f57-f77f-033f-df9fd2cc2ea0/Database-Slave/tmp/getter2911867900: permission denied"
Mar 20 12:05:32 nomad-client nomad[68488]: client.artifact: sub-process: OUTPUT="failed to download artifact: Error creating temporary directory for archive: mkdir /opt/nomad/data/alloc/b45a0e9e-6f57-f77f-033f-df9fd2cc2ea0/Database-Slave/tmp/getter2911867900: permission denied"
Mar 20 12:05:32 nomad-client nomad[68488]:     2023-03-20T12:05:32.252-0400 [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=b45a0e9e-6f57-f77f-033f-df9fd2cc2ea0 task=Database-Slave error="prestart hook \"artifacts\" failed: failed to download artifact \"http://user:passwed@url.com/uri": getter subprocess failed: exit status 1"
Mar 20 12:05:32 nomad-client nomad[68488]: client.alloc_runner.task_runner: prestart failed: alloc_id=b45a0e9e-6f57-f77f-033f-df9fd2cc2ea0 task=Database-Slave error="prestart hook \"artifacts\" failed: failed to download artifact \"http://user:passwed@url.com/uri": getter subprocess failed: exit status 1"
`

**Comment by davidlublink** [comment]
I did some testing with @Narmac and we were able to reduce the job needed to reproduce the issue to the following : 


```
job "Bug-16493" {
  group "Test" {
    task "Test" {
      driver = "docker"
      artifact {
        source      = "https://docbox.etsi.org/stq/Open/Binary%20files/5MB.bin"
        destination = "local/data-dir"
      }
      config {
        image = "httpd"
      }
    }
  }
}

```

Binary file is the first binary file I found on google.
httpd because it's a well known image.

The content and image are immaterial to the issue.

**Comment by tgross** [comment]
@davidlublink @Narmac as noted by @shoenig, can you check the ID of the user the Nomad client agent is running as?

**Comment by davidlublink** [comment]
I'm going to say it's running as root.

```
root     3684980  1.2  0.7 1981744 127592 ?      Ssl  Mar14 118:44 /usr/bin/nomad agent -config /etc/nomad.d
```

**Comment by Narmac** [comment]
Hi @tgross  Nomad agent is running as root user:

`(0) root@nomad-client-lab:# sudo ps -ef | grep root | grep nomad
root        5276       1  0 Feb02 ?        02:07:51 /usr/bin/nomad logmon
root        5334       1  0 Feb02 ?        00:00:04 /usr/bin/nomad docker_logger
root      266793 3684980  0 Mar17 ?        00:00:29 /usr/bin/nomad docker_logger
root      267749 3684980  0 Mar17 ?        00:00:29 /usr/bin/nomad docker_logger
root     2136371 3684980  0 10:05 ?        00:00:09 /usr/bin/nomad logmon
root     2136472 3684980  0 10:05 ?        00:00:00 /usr/bin/nomad docker_logger
root     2154245 2145614  0 10:58 pts/0    00:00:00 /usr/bin/grep --color nomad
root     2917505       1  0 Feb14 ?        01:56:58 /usr/bin/nomad logmon
root     2917572       1  0 Feb14 ?        00:00:03 /usr/bin/nomad docker_logger
root     3684980       1  1 Mar14 ?        01:58:44 /usr/bin/nomad agent -config /etc/nomad.d
root     3925163 3684980  0 Mar15 ?        00:20:30 /usr/bin/nomad logmon
root     3927445 3684980  0 Mar15 ?        00:21:26 /usr/bin/nomad logmon
root     3927588 3684980  0 Mar15 ?        00:01:19 /usr/bin/nomad docker_logger
root     3927855 3684980  0 Mar15 ?        00:18:39 /usr/bin/nomad logmon
root     3928011 3684980  0 Mar15 ?        00:00:44 /usr/bin/nomad docker_logger
root     3949581 3684980  0 Mar15 ?        00:21:22 /usr/bin/nomad logmon
root     3949668 3684980  0 Mar15 ?        00:01:59 /usr/bin/nomad docker_logger
root     4070920 3684980  0 Mar16 ?        00:15:58 /usr/bin/nomad logmon
root     4070934 3684980  0 Mar16 ?        00:17:49 /usr/bin/nomad logmon
root     4070947 3684980  0 Mar16 ?        00:15:33 /usr/bin/nomad logmon
root     4071459 3684980  0 Mar16 ?        00:00:34 /usr/bin/nomad docker_logger
root     4072169 3684980  0 Mar16 ?        00:00:34 /usr/bin/nomad docker_logger
root     4072184 3684980  0 Mar16 ?        00:00:34 /usr/bin/nomad docker_logger
root     4095294 3684980  0 Mar16 ?        00:16:16 /usr/bin/nomad logmon
`

**Comment by davidlublink** [comment]
> nomad node status -verbose

```
ID              = 18209379-cbc1-c1c5-6c61-2b98b7ddfaa3
Name            = nomad-client-lab-13
Class           = <none>
DC              = office-dev
Drain           = false
Eligibility     = eligible
Status          = ready
Uptime          = 1123h29m39s




Drivers
Driver    Detected  Healthy  Message   Time
docker    true      true     Healthy   2023-03-14T17:04:58-04:00
exec      true      true     Healthy   2023-03-14T17:02:45-04:00
java      false     false    <none>    2023-03-14T17:02:45-04:00
qemu      false     false    <none>    2023-03-14T17:02:45-04:00
raw_exec  false     false    disabled  2023-03-14T17:02:45-04:00

Allocated Resources
CPU             Memory         Disk
5122/22336 MHz  13 GiB/16 GiB  2.6 GiB/59 GiB

Allocation Resource Utilization
CPU           Memory
59/22336 MHz  4.7 GiB/16 GiB

Host Resource Utilization
CPU            Memory          Disk
470/22336 MHz  4.2 GiB/16 GiB  (/dev/mapper/ubuntu--vg-ubuntu--lv)

Allocations
ID                                    Eval ID                               Node ID                               Task Group                      Version  Desired  Status    Created                    Modified

Attributes
consul.connect                   = true
consul.datacenter                = office-dev
consul.ft.namespaces             = false
consul.grpc                      = -1
consul.revision                  = 7c04b6a0
consul.server                    = false
consul.sku                       = oss
consul.version                   = 1.15.1
cpu.arch                         = amd64
cpu.frequency                    = 2792
cpu.modelname                    = Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
cpu.numcores                     = 8
cpu.reservablecores              = 8
cpu.totalcompute                 = 22336
driver.docker                    = 1
driver.docker.bridge_ip          = 172.17.0.1
driver.docker.os_type            = linux
driver.docker.privileged.enabled = true
driver.docker.runtimes           = io.containerd.runc.v2,io.containerd.runtime.v1.linux,runc
driver.docker.version            = 20.10.21
driver.exec                      = 1
kernel.arch                      = x86_64
kernel.name                      = linux
kernel.version                   = 5.4.0-122-generic
memory.totalbytes                = 16785866752
nomad.bridge.hairpin_mode        = false
nomad.revision                   = 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7
nomad.service_discovery          = true
nomad.version                    = 1.5.1
os.name                          = ubuntu
os.signals                       = SIGCONT,SIGIO,SIGXFSZ,SIGABRT,SIGALRM,SIGQUIT,SIGSEGV,SIGSYS,SIGTERM,SIGBUS,SIGILL,SIGTTIN,SIGUSR2,SIGHUP,SIGPROF,SIGWINCH,SIGFPE,SIGKILL,SIGPIPE,SIGNULL,SIGIOT,SIGSTOP,SIGTRAP,SIGTSTP,SIGTTOU,SIGINT,SIGUSR1,SIGXCPU
os.version                       = 20.04
plugins.cni.version.bandwidth    = v1.1.1
plugins.cni.version.bridge       = v1.1.1
plugins.cni.version.dhcp         = v1.1.1
plugins.cni.version.firewall     = v1.1.1
plugins.cni.version.host-device  = v1.1.1
plugins.cni.version.host-local   = v1.1.1
plugins.cni.version.ipvlan       = v1.1.1
plugins.cni.version.loopback     = v1.1.1
plugins.cni.version.macvlan      = v1.1.1
plugins.cni.version.portmap      = v1.1.1
plugins.cni.version.ptp          = v1.1.1
plugins.cni.version.sbr          = v1.1.1
plugins.cni.version.static       = v1.1.1
plugins.cni.version.tuning       = v1.1.1
plugins.cni.version.vlan         = v1.1.1
plugins.cni.version.vrf          = v1.1.1
unique.cgroup.mountpoint         = /sys/fs/cgroup/systemd
unique.cgroup.version            = v1
unique.storage.bytesfree         = 63735730176
unique.storage.bytestotal        = 209982685184
unique.storage.volume            = /dev/mapper/ubuntu--vg-ubuntu--lv
vault.accessible                 = true

vault.version                    = 1.13.0

Meta
connect.gateway_image     = envoyproxy/envoy:v${NOMAD_envoy_version}
connect.log_level         = info
connect.proxy_concurrency = 1
connect.sidecar_image     = envoyproxy/envoy:v${NOMAD_envoy_version}



```

**Comment by davidlublink** [comment]
@Zygimantass 

Can you upgrade your 1.5.1 node to 1.5.2 please and see if you can still reproduce the error ?

https://github.com/hashicorp/nomad/blob/v1.5.2/CHANGELOG.md

**Comment by tgross** [comment]
Thanks @Narmac !
