### ISSUE TITLE
`nomad login` errors before determining the default auth method type

### ISSUE THREAD

**Issue by xkisu** [hashicorp/nomad#16501]
### Nomad version
`v1.5.0`

### Operating system and Environment details
Ubuntu 22.04.2 LTS

### Issue
The [documentation for the `nomad login` command](https://developer.hashicorp.com/nomad/docs/commands/login#type) and the integration [guide here](https://developer.hashicorp.com/nomad/tutorials/single-sign-on/sso-oidc-vault#authenticate-with-nomad) state that the `type` flag is optional if an admin has configured a default, however this is not the case.

Line [`117` in `login.go`](https://github.com/hashicorp/nomad/blob/1a01e871927284b2c484d7745e1d7df1df6312d8/command/login.go#L117) explicitly rejects any calls to `nomad login` that don't have `OIDC` set as the type:
```go
switch l.authMethodType {
case api.ACLAuthMethodTypeOIDC:
default:
	l.Ui.Error(fmt.Sprintf("Unsupported authentication type %q", l.authMethodType))
	return 1
}
```

There is a check further down for a default auth method, at [line 143](https://github.com/hashicorp/nomad/blob/1a01e871927284b2c484d7745e1d7df1df6312d8/command/login.go#L143) that will set the type to be the type of the default auth method, but that section of the code is never reached because the switch statement above returns an error before it can try to determine the default type.

### Reproduction steps

 1. Register an auth method with Nomad (i.e. following [this guide](https://developer.hashicorp.com/nomad/tutorials/single-sign-on/sso-oidc-vault#authenticate-with-nomad))
 2. Make sure the auth method is set as default (`nomad acl auth-method info vault`)
 3. Try to run `nomad login` without specifying the type, you'll receive an error `Unsupported authentication type ""`

#### Expected Result

It should be selecting the default auth method and using the type from that. These is code defined in the command to do so, but the `switch` statement further up cancels it out before it can try to determine the default.

#### Actual Result

```
Unsupported authentication type ""
```

**Comment by pkazmierczak** [comment]
Hi @xkisu, thanks for pointing out the bug. You are right that the documented and expected behavior doesn't match the implementation, we'll be fixing it promptly.

**Comment by pkazmierczak** [comment]
Hey @xkisu, we just merged a fix and it will be included in the next release. While fixing it, we noticed that `nomad login` doesn't actually need a `-type` flag, since auth method names are unique. Thus the fix removes the flag (although it will not error if the flag is submitted, it will just print a deprecation warning until 1.6.0), and it now correctly respects the `default` auth method if set. 

Once again thanks for catching this!

**Comment by xkisu** [comment]
> Hey @xkisu, we just merged a fix and it will be included in the next release. While fixing it, we noticed that `nomad login` doesn't actually need a `-type` flag, since auth method names are unique. Thus the fix removes the flag (although it will not error if the flag is submitted, it will just print a deprecation warning until 1.6.0), and it now correctly respects the `default` auth method if set.
> 
> Once again thanks for catching this!

Thank you for merging a fix so quickly!
