### ISSUE TITLE
UI enhancements for the upcoming JWT authentication method

### ISSUE THREAD

**Issue by pkazmierczak** [hashicorp/nomad#16521]
Currently, Nomad UI supports logging in via an SSO if an ACL Auth Method is detected in the state store. Unauthenticated users are then presented with the following message: 

![Screenshot 2023-03-16 at 16 27 59](https://user-images.githubusercontent.com/470696/225666394-f908c108-f3c4-4c64-9114-db189ca7760f.png)

And later when then click on either the auth method name or the Nomad ACL Token link, they are redirected to the following:

![Screenshot 2023-03-16 at 16 29 06](https://user-images.githubusercontent.com/470696/225666579-6032debd-53c7-4a49-baa3-66b993fb0f68.png)

We will soon introduce a new auth method type, JWT, that does not require a redirect to a 3rd party provider, and in fact is just a string of characters much like the Nomad ACL Token. I see two possible ways we could address this in the UI:

- Detect if the `type` of an ACL Auth Method is JWT or OIDC, and present a different dialog to the user depending on that, or:
- Detect the shape of the token that is being pasted into the "Secret ID" text field. If it's [JWT-shaped](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-structure), call the `/v1/acl/login` endpoint, if it's not, treat it as a Nomad ACL Token. 

The new [`/acl/login` endpoint](https://github.com/hashicorp/nomad/pull/16519/files#diff-2e5d8c7e3c03765139794b39e34b4603fa658be194dbb1885da8f59f80b079a8R879) will expect an auth method name (just like the OIDC endpoint), and a token.

**Comment by pkazmierczak** [comment]
FYI all the backend code has been reviewed and merged into [a feature branch](https://github.com/hashicorp/nomad/pull/15897); could be useful for testing.

**Comment by philrenaud** [comment]
Resolved by #16625 and #16665
