### ISSUE TITLE
NOMAD_ADDR_* variables incorrect with ipv6

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#16550]
### Env
nomad 1.5.1, linux node with only ipv6 address

### Issue

Nomad env vars have invalid format:
```
NOMAD_HOST_ADDR_http=2a01:4f8:111:1ae1::2:25013
NOMAD_ADDR_http=2a01:4f8:111:1ae1::2:25013
```
#### Expected Result

They should be like this:

```
NOMAD_HOST_ADDR_http=[2a01:4f8:111:1ae1::2]:25013
NOMAD_ADDR_http=[2a01:4f8:111:1ae1::2]:25013
```

#### Related issues

No address for services with IPv6 address in UI:
![image](https://user-images.githubusercontent.com/9821/226107780-5e304193-be2a-4ba2-9552-aab7a7f12781.png)

**Comment by jrasell** [comment]
Hi @valodzka and thanks for raising this issue. This seems like something we should get fixed up both in the frontend and backend.

**Comment by lgfa29** [comment]
I believe the UI problem described has the same root cause as https://github.com/hashicorp/nomad/issues/14654. Refreshing the page should display the service address.
