### ISSUE TITLE
Feature request to make all possible Nomad agent settings dynamic

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#16582]
### Proposal
I would want to propose a feature request, where _all_ node configurations are configured from the server side using API, and very minimal set of configurations are stored on nodes. Right now, deploying even a minimal small change to Nomad agents, requires restarting of _all_ Nomad agents, which regenerates all job templates and can restart jobs. The server side configuration is easier to manage for humans and easier to synchronize, when all the configuration is stored in one place.

### Use-cases
The use case is to simplify the administration of a Nomad cluster. The administrator will not have to execute a long Ansible or Puppet script to deploy a simple change. Additionally, _restarting_ a service is very invasive and always brings some uncertainty if the service will be able to start. Instead, the change can be applied and propagated and inherited by the Nomad on existing and new Nodes. The configuration is also more uniform.

### Attempted Solutions
The solution currently is to have an Ansible script.

**Comment by jrasell** [comment]
Hi @Kamilcuk and thanks for raising this feature request. This seems to tie nicely into the suggestion within #16574 regarding the ability to have servers pass configuration onto client agents. I am therefore going to close this out as a duplicate. If you want to add additional context or use-cases, please feel free to add them to the linked issue.

**Comment by Kamilcuk** [comment]
Thanks, makes sense, that's great!
