### ISSUE TITLE
Fingerprint Windows Build Number

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#16591]
As of Nomad 1.5.1 the Windows version is fingerprinted into 2 attributes, but neither is a useful format:

```
kernel.version                           = 10.0.14393.5501 Build 14393.5501
...
os.version                               = 10.0.14393.5501 Build 14393.5501
```

### Proposal

Include just the build number as a new fingerprinted attribute like:

```
os.build = 14393.5501
```

Such that constraints could treat it like a version number for comparisons.

### Use-cases

Nomad 1.5 added the Task API as a unix socket. Windows only added Unix socket support in **build 17063.** In order to schedule tasks that expect the Task API on a version of Windows with unix socket support, we need to fingerprint the build number distinctly.

**Comment by tgross** [comment]
Done in #17576 which will ship in Nomad 1.6.0
