### ISSUE TITLE
Updating service tags appends instead of replaces in consul

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#1661]
When updating tags from `["foo", "bar"]` to `["foo", "x"]`, `x` will be appended and `bar` won't be removed in consul. So the result is `["foo", "bar", "x"]` instead of `["foo", "x"]`

### Nomad version
0.4 - master (152c11d657c1fec4cbc6857c4218a5fc8121340f)
### Issue
Original submisison:

> Hi, I'm using Nomad 0.4 to run some jobs. Is it expected that when you update a service (Consul) tag, the old tag is not removed but instead appended to the service?

### Reproduction steps

1. Start consul + nomad
2. run example.nomad
3. Change `cache` tag to `cache2` tag
4. run example.nomad
5. Observe tags in consul include both `cache` and `cache2`

**Comment by kyhavlov** [comment]
It looks like this was broken as a result of the consul syncer tests here being skipped: https://github.com/hashicorp/nomad/blob/master/command/agent/consul/syncer_test.go#L133-L183

**Comment by diptanu** [comment]
@kaskavalci Yeah we are aware of the commented tests. We are working towards fixing them.

**Comment by schmichael** [comment]
@kyhavlov Fix should be merged in #1668 and will be included in our next release. Let me know if you continue having problems once that's out.

**Comment by kyhavlov** [comment]
Any plans to cut a 0.4.2? Or will 0.5 be out relatively soon?

**Comment by schmichael** [comment]
@kyhavlov 0.5 should be out in a few weeks. HashiConf is next week and more news about 0.5 will be coming out then.
