### ISSUE TITLE
exec driver no such directory for memory.limit_in_bytes. on Debian 8(jessie)

### ISSUE THREAD

**Issue by csawyerYumaed** [hashicorp/nomad#1664]
Nomad v0.4.1
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie

On Debian 8(jessie) , the memory cgroup is not enabled by default, and you get an error in your nomad alloc-status output:

Recent Events:
Time                   Type                   Description
08/30/16 08:24:50 MST  Not Restarting         Error was unrecoverable
08/30/16 08:24:50 MST  Driver Failure         failed to start task 'fabio' for alloc 'e3eb5566-00a8-0632-81b5-512c55cd2c69': no such directory for memory.limit_in_bytes.
08/30/16 08:24:46 MST  Downloading Artifacts  Client is downloading artifacts
08/30/16 08:24:46 MST  Received               Task received by client

Ideally nomad would notice the memory cgroup is not around and deal with it accordingly -- either error with something useful, or disable memory cgroup limiting.

On Debian 8, to allow cgroup memory limiting:
/etc/default/grub:
GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"
(in my version the quiet was already there, I added:  cgroup_enable=memory swapaccount=1

then run update-grub and reboot, then nomad exec driver jobs should run fine.

So my issue here is either a better error message, or disable memory limiting if the machine doesn't support it/have it enabled like on Debian (8)jessie.

**Comment by artkrz** [comment]
Can confirm adding `cgroup_enable=memory swapaccount=1` to `/etc/default/grub` + reboot solves the problem. I don't think this is really something that should be resolved in Nomad but rather should be mentioned in documentation that on Debian this needs to be added to grub.

**Comment by michabbb** [comment]
this helps to do this right: https://serverfault.com/a/801259/221690

**Comment by prologic** [comment]
How do you do this in a Vagrant VM? Don't tell me I have to use a custom packaged box? :)

**Comment by prologic** [comment]
Using the box from [Vagrantfile](/Vagrantfile) `bento/ubuntu-16.04` probably might help if you're testing things like I am.

**Comment by tgross** [comment]
Going to close this issue out. We've documented the cgroups requirements at https://www.nomadproject.io/docs/drivers/exec#resource-isolation
