### ISSUE TITLE
Missing  package "context"

### ISSUE THREAD

**Issue by duythinht** [hashicorp/nomad#1665]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version 0.4.1
0.4.1

### Operating system and Environment details
Ubuntu 16.04
go 1.6
### Issue
Trying to run nomad as develop, but get go compile error message

### Reproduction steps

$ go get github.com/hashicorp/nomad
$ cd [nomad_folder]
$ make bootstrap
$ make dev

then I get a message:

> --> Running go generate
--> Running go fmt
--> Building nomad
nomad/job_endpoint.go:4:2: cannot find package "context" in any of:
	/home/duythinht/workspace/go/src/github.com/hashicorp/nomad/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/duythinht/workspace/go/src/context (from $GOPATH)
GNUmakefile:30: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by dadgar** [comment]
The minimum version for Nomad is now Go 1.7. Context was introduced into the stdlib in 1.7
