### ISSUE TITLE
Add event lifecycles for job updates

### ISSUE THREAD

**Issue by robzienert** [hashicorp/nomad#167]
Having the ability to have lifecycle events for rolling updates would be a great feature to have, most namely in the shutdown phase in a rolling update. I'd like the ability to subscribe to a signal within an application to perform any cleanup.

Real world example: I have an application that has thousands of persistent connections to it that I want to gracefully drain, prior to completely shutting down the service. Being able to block until it's complete and a signal is sent back to Nomad, or a TTL is elapsed, would be perfect.

**Comment by ryanuber** [comment]
Good idea, sounds like we basically just need to signal the running processes or containers, and then wait for them to complete within a reasonable timeout before doing the hard kill. Marked as an enhancement, thanks!

**Comment by cbednarski** [comment]
Related: https://github.com/hashicorp/nomad/issues/17

**Comment by dadgar** [comment]
This exists. Before killing a task we send `SIGINT` and have `kill_timeout` that is user configurable.
