### ISSUE TITLE
Nomad allocation not distributed evenly

### ISSUE THREAD

**Issue by jtuthehien** [hashicorp/nomad#1673]
Hi
As titled, is there anyway to debug , why nomad doesnt distribute dockers evenly across all client nodes. Currently, we are running 3 nodes cluster, and 1 nodes are exhausted 90% resource while other nodes only use 30%

### Nomad version
Output from `nomad version` 0.4.1

**Comment by dadgar** [comment]
Hey,

Nomad works by using a bin-packing algorithm and not a spread algorithm. This causes Nomad to fill up one node before moving to the next.

Thanks,
Alex
