### ISSUE TITLE
Periodic job executed 3 hours after first try due to node update

### ISSUE THREAD

**Issue by mlafeldt** [hashicorp/nomad#1674]
### Nomad version

0.4.1

### Operating system and Environment details

CoreOS stable 1068.9.0

### Issue

We have a periodic job that runs every hour:

```
$ nomad status reports
ID                   = reports
Name                 = reports
Type                 = batch
Priority             = 50
Datacenters          = eu-west-1
Status               = running
Periodic             = true
Next Periodic Launch = 09/01/16 12:00:00 UTC (6m47s from now)

Previously launched jobs:
ID                           Status
reports/periodic-1472702400  dead
reports/periodic-1472706000  dead
reports/periodic-1472709600  dead
reports/periodic-1472713200  dead
reports/periodic-1472716800  dead
reports/periodic-1472720400  dead
reports/periodic-1472724000  dead
reports/periodic-1472727600  dead
```

We are wondering why this one job invocation was invoked 3 hours after (08:10:26 UTC) the first try (05:00:00 UTC) failed:

```
$ nomad status reports/periodic-1472706000
ID          = reports/periodic-1472706000
Name        = reports/periodic-1472706000
Type        = batch
Priority    = 50
Datacenters = eu-west-1
Status      = dead
Periodic    = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
reports     0       0         0        1       1         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status    Created At
d3107f40  0c90eae6  099799fd  reports     run      complete  09/01/16 08:10:26 UTC
e4e0bd78  f4381aa6  7b288477  reports     run      failed    09/01/16 05:00:00 UTC
```

The original allocation failed due to a problem with Docker, which doesn't really matter for this issue:

```
$ nomad alloc-status e4e0bd78

couldn't retrieve stats (HINT: ensure Client.Advertise.HTTP is set): Get http://10.8.4.159:4646/v1/client/allocation/e4e0bd78-9f62-b87b-0413-b5ef3b70e0e9/stats: dial tcp 10.8.4.159:4646: getsockopt: no route to host
ID            = e4e0bd78
Eval ID       = f4381aa6
Name          = reports/periodic-1472706000.reports[0]
Node ID       = 7b288477
Job ID        = reports/periodic-1472706000
Client Status = failed

Task "reports" is "dead"
Task Resources
CPU      Memory  Disk     IOPS  Addresses
100 MHz  10 MiB  300 MiB  0

Recent Events:
Time                   Type            Description
09/01/16 05:00:02 UTC  Not Restarting  Policy allows no restarts
09/01/16 05:00:02 UTC  Driver Failure  failed to start task 'reports' for alloc 'e4e0bd78-9f62-b87b-0413-b5ef3b70e0e9': Failed to start container 7b9b6f001c851a46598e8254542cbd698cab6570270dcc57c1af1fb42c0feb3b: API error (500): Cannot start container 7b9b6f001c851a46598e8254542cbd698cab6570270dcc57c1af1fb42c0feb3b: [9] System error: read parent: connection reset by peer
09/01/16 05:00:00 UTC  Received        Task received by client
```

I can see that the second evaluation was triggered by a node update:

```
$ nomad eval-status -verbose 0c90eae6
ID                 = 0c90eae6-bd13-a3cf-fc92-ae50ce44c528
Status             = complete
Status Description = complete
Type               = batch
TriggeredBy        = node-update
Node ID            = 7b288477-f66f-28f9-5780-390db815d682
Priority           = 50
Placement Failures = false
Previous Eval      = <none>
Next Eval          = <none>
Blocked Eval       = <none>
```

**Comment by mlafeldt** [comment]
To add to this, here's the list of client nodes:

```
$ nomad node-status
ID        DC         Name                                      Class   Drain  Status
d6eb4b5b  eu-west-1  ip-10-8-4-35.eu-west-1.compute.internal   <none>  false  ready
099799fd  eu-west-1  ip-10-8-3-88.eu-west-1.compute.internal   <none>  false  ready
fa764d8d  eu-west-1  ip-10-8-3-146.eu-west-1.compute.internal  <none>  false  ready
7b288477  eu-west-1  ip-10-8-4-159.eu-west-1.compute.internal  <none>  false  down
7b2a3dbf  eu-west-1  ip-10-8-3-190.eu-west-1.compute.internal  <none>  false  down
3fa5ba67  eu-west-1  ip-10-8-4-236.eu-west-1.compute.internal  <none>  false  down
```

**Comment by mlafeldt** [comment]
To make this more clear: I'm aware that jobs might fail and that we should configure a restart policy to handle failures more gracefully. What I don't get is why Nomad executed the job 3 hours after the failed attempt and what `node-update` actually means in this context?

**Comment by dadgar** [comment]
It looks like the node went down which triggered that evaluation. The scheduler saw that the allocation failed and then made a replacement

**Comment by mlafeldt** [comment]
Yes, sure. The node where the original allocation failed was replaced later at a later point (due to an unrelated rolling update). The question is still why the scheduler decided to run a replacement 3 hours later. FWIW, the periodic job continued to run successfully after 5am. Here's a timeline:

* 04:00 - job succeeded
* 05:00 - job failed
* 06:00 - job succeeded
* 07:00 - job succeeded
* 08:00 - job succeeded
* **08:10 - the failed job from 05:00 was rescheduled**
* 09:00 - job succeeded
* 10:00 - job succeeded

**Comment by dadgar** [comment]
So that instance from 05:00 failed and once the scheduler realized it reran
the instance. It is that the scheduler only got triggered when the node
went down since there aren't server side restarts.

**Comment by mlafeldt** [comment]
I can tell from our logs that the node 7b288477 was being terminated between 08:05 and 08:10.

In other words, this is what happened:

* 05:00 - job failed on node 7b288477
* 06:00 - job succeeded
* 07:00 - job succeeded
* 08:00 - job succeeded
* 08:05 - 08:10 node 7b288477 was terminated
* 08:10 - the failed job from node 7b288477 was rescheduled on node 099799fd
* 09:00 - job succeeded

1. What you're saying is that this is intended behavior? The scheduler realizes that the job failed at 05:00 and restarts it at 08:10 because the node where the allocation happened is terminated (which can happen hour or days later)?

2. I don't understand why the scheduler tries to restart the job in the first place. Restarting is disabled (see log line `Policy allows no restarts`).

**Comment by dadgar** [comment]
For now that is intended behavior. The restart policy currently only covers
restarting locally at the node. There is no notion of cluster wide restart
policies. This all needs to be fleshed out with the server side restarts.

**Comment by mlafeldt** [comment]
OK, this is definitely good to know for production. I guess by configuring a proper restart policy and thus re-running failed jobs immediately on the same node, we can at least minimize the risk of jobs being restarted at any time.
