### ISSUE TITLE
Template restart signal takes too long to propogate

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#16840]
### Nomad version

1.3.1

### Issue

We've a job with 25 allocs, running in `system` mode on 25 different EC2 Instances. The config is templated in the job, which fetches secrets from Vault.

We've observed that on changing secrets in Vault, the `restart` signal to the underlying alloc spreads across a few minutes for 25 allocs. Ideally this shouldn't take more than a few seconds, so wondering if this is configurable and are we missing something here?

### Reproduction steps

- Run a system job with a template file which pulls secrets from Vault
-  Update secrets inside Vault UI
- Wait for a few minutes to see the restart being propagated across all allocs

#### Expected Result

- Restart for all allocs should happen instantly or atleast in a few seconds. 5-7 minutes is too long.

#### Actual Result

- For 24 allocs, we've to wait a few minutes for the underlying alloc to get the restart signal.

### Job file (if appropriate)

Removed the app specific stuff like artifacts etc.

```hcl
job "app" {
  namespace   = "app"
  type = "system"

  vault {
    policies = ["access-app", "access-app-common"]
  }

  constraint {
    attribute = "${meta.ec2_nomad_client_namespace}"
    operator  = "="
    value     = "app"
  }

  meta {
    app_group = "${meta.ec2_nomad_client}"
    client_name = "client-${attr.unique.network.ip-address}"
  }

  group "app-default" {
    network {
      mode = "host"
    }

    restart {
      attempts = 10
      interval = "5m"
      delay    = "15s"
      mode     = "fail"
    }

    task "app" {
      driver = "exec"

      template {
        data = file(abspath("./config/app/config.tpl.toml"))
        destination = "${NOMAD_TASK_DIR}/config.toml"
      }
    }
  }
}
```

This is the first alloc which got the restart signal:

![image](https://user-images.githubusercontent.com/5689132/231138046-f1d37cf5-8480-4215-93b4-d75f41a2b875.png)

This is the last alloc which got the restart signal (**4 minutes apart**):

![image](https://user-images.githubusercontent.com/5689132/231138244-8246f53a-a880-4eb1-b6e7-d18144dca856.png)

Attaching the logs of one particular alloc, in case it helps:

```
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.049+0530 [DEBUG] agent: (runner) receiving dependency vault.read(myapp/data/myapp-common)
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.049+0530 [DEBUG] agent: (runner) initiating run
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.049+0530 [DEBUG] agent: (runner) checking template 986815713a0993e1112779348e7c657f
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.049+0530 [DEBUG] agent: (runner) rendering "(dynamic)" => "/opt/nomad/data/alloc/38837217-44be-ad37-4873-a36ef5fa8ccc/myapp-app/local/config.toml"
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.049+0530 [DEBUG] agent: (runner) checking template 0244705228f257c9d8819a7379a83c05
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) rendering "(dynamic)" => "/opt/nomad/data/alloc/38837217-44be-ad37-4873-a36ef5fa8ccc/myapp-app/local/run-myapp.sh"
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) diffing and updating dependencies
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) vault.read(myapp/data/myapp) is still needed
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) vault.read(myapp/data/myapp-common) is still needed
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) watching 2 dependencies
Apr 11 16:06:50 myapp-app-extraneous-172-31-xx-yyy nomad[941]:     2023-04-11T16:06:50.050+0530 [DEBUG] agent: (runner) all templates rendered
```

**Comment by lgfa29** [comment]
Hi @mr-karan 👋 

Do you know if your changes are somewhat stable or do they happen to flap for a bit until they stabilize? There are a few client configuration that may help you tune the timing parameters of template changes like [`wait`](https://developer.hashicorp.com/nomad/docs/configuration/client#wait).

Would it be possible to get the logs from a client as well? Preferably at a lower log level like `DEBUG` because I think a lot of consul-template logs end up there.

**Comment by tgross** [comment]
This has been open without more info for a while now, but unfortunately it's almost certainly a property of how consul-template watches work. There's no coordination (or control!) in Nomad over how we get updates from Vault via CT. The [`splay`](https://developer.hashicorp.com/nomad/docs/job-specification/template#splay) parameter is the only control we have, and that only impacts within a given template not between allocations.
