### ISSUE TITLE
Envoy TLS BAD CERTIFICATE

### ISSUE THREAD

**Issue by fred-gb** [hashicorp/nomad#16854]
Hi 👋🏻 

### Nomad version
Output from `nomad version`
```
root@sandbox:~# nomad version
Nomad v1.5.3
BuildDate 2023-04-04T20:09:50Z
Revision 434f7a1745c6304d607562daa9a4a635def7153f

root@sandbox:~# consul version
Consul v1.15.2
Revision 5e08e229
Build Date 2023-03-30T17:51:19Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

```

### Operating system and Environment details
Ubuntu 22.04

### Issue
When I launch the `countdash-api` example job, service mesh not working:
```
[2023-04-11 18:54:39.260][1][warning][config] [./source/common/config/grpc_stream.h:201] DeltaAggregatedResources gRPC config stream to local_agent closed since 7554s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
```

### Reproduction steps
Generate Consul certificates chain with ansible (Consul, Vault, Nomad can communicate each others without problems)

`consul.hcl` part:
```
advertise_addr = "127.0.0.1"
bind_addr = "127.0.0.1"
client_addr = "127.0.0.1"

ports = {
  dns = 8600
  grpc = 8502
  grpc_tls = 8503
  http = -1
  https = 8501
  serf_lan = 8301
  serf_wan = 8302
  server = 8300
}

tls = {
  defaults = {
    ca_file = "/etc/ssl/hashistack/hashistack-ca.pem"
    cert_file = "/etc/ssl/hashistack/dc1-server-consul.pem"
    key_file = "/etc/ssl/hashistack/dc1-server-consul.key"
    tls_min_version = "TLSv1_2"
    verify_incoming = true
    verify_outgoing = true
  }

  grpc = {
    verify_incoming = true
  }
```

`nomad.hcl` part:
```
consul {
    address      = "127.0.0.1:8501"
    grpc_address = "127.0.0.1:8503"
    ssl = true
    grpc_ca_file = "/etc/ssl/hashistack/hashistack-ca.pem"
    ca_file = "/etc/ssl/hashistack/hashistack-ca.pem"
    cert_file = "/etc/ssl/hashistack/dc1-server-consul.pem"
    key_file = "/etc/ssl/hashistack/dc1-server-consul.key"
    token = "-------------------------------" 
    server_service_name = "nomad-servers"
    client_service_name = "nomad-clients"
    tags = {}

    auto_advertise = true

    server_auto_join = true
    client_auto_join = true
}
```

`root@sandbox:~# cat /etc/nomad.d/nomad.env`
```
CONSUL_HTTP_SSL=true
CONSUL_CACERT=/etc/ssl/hashistack/hashistack-ca.pem
CONSUL_CLIENT_CERT=/etc/ssl/hashistack/dc1-server-consul.pem
CONSUL_CLIENT_KEY=/etc/ssl/hashistack/dc1-server-consul.key
```

`root@sandbox:~# cat /etc/consul.d/consul.env`
```
CONSUL_HTTP_SSL=true
CONSUL_CACERT=/etc/ssl/hashistack/hashistack-ca.pem
CONSUL_CLIENT_CERT=/etc/ssl/hashistack/dc1-server-consul.pem
CONSUL_CLIENT_KEY=/etc/ssl/hashistack/dc1-server-consul.key
```

### Job file (if appropriate)
`countdash` from: https://developer.hashicorp.com/nomad/tutorials/integrate-consul/consul-service-mesh#run-a-connect-enabled-job

### Consul logs:
```
Apr 11 19:16:29 sandbox consul[6346]: 2023-04-11T19:16:29.271Z [WARN]  agent: Check socket connection failed: check=service:_nomad-task-f9fbf3df-5a1e-aa02-1453-242e9b58d230-group-dashboard-count-dashboard-9002-sidecar-proxy:2 error="dial tcp 192.168.10.140:25784: connect: connection refused"
Apr 11 19:16:29 sandbox consul[6346]: 2023-04-11T19:16:29.272Z [WARN]  agent: Check is now critical: check=service:_nomad-task-f9fbf3df-5a1e-aa02-1453-242e9b58d230-group-dashboard-count-dashboard-9002-sidecar-proxy:2
Apr 11 19:16:30 sandbox consul[6346]: 2023-04-11T19:16:30.671Z [WARN]  agent: Check socket connection failed: check=service:_nomad-task-ed284bbc-90ce-0cc3-6019-3ae607e64b4e-group-api-count-api-9001-sidecar-proxy:2 error="dial tcp 192.168.10.140:25563: connect: connection refused"
Apr 11 19:16:30 sandbox consul[6346]: 2023-04-11T19:16:30.671Z [WARN]  agent: Check is now critical: check=service:_nomad-task-ed284bbc-90ce-0cc3-6019-3ae607e64b4e-group-api-count-api-9001-sidecar-proxy:2
```

In Consul configuration, when I set to:
```
  grpc = {
    verify_incoming = false
  }
```

Service mesh works. But I don't think it was a good solution.

I follow advices of discuss members  but, nothing works. 😢 

I don't know what is good or not now, I tried so many things. 
Does I need to install envoy binary or let Nomad use docker?

I follow this tutorial: https://developer.hashicorp.com/consul/tutorials/developer-mesh/service-mesh-with-envoy-proxy?utm_source=docs. Sames errors.

I create TLS certs with `consul ca create and consul tls cert...`. Not works

I don't know where I did mistake... 😞 

Thanks

**Comment by jrnijboer** [comment]
We are seeing the same error as @fred-gb :
```
[./source/common/config/grpc_stream.h:201] DeltaAggregatedResources gRPC config stream to local_agent closed since 409s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
```

We are also having a fairly similar configuration as @fred-gb, as in the Consul agent uses TLS for HTTP as well as for grpc and with `verify_incoming = true` for both protocols. Our certificates are also created by consul, using the `consul tls` commands. We are using the same CA for http and grpc. The Nomad agent is also configured to send a client certificate and key to the Consul agent. If we switch our Consul agent to `verify_incoming = false` for grpc, everything works again. So maybe Nomad doesn't correctly send it's client certificate and key for grpc, or Consul agent doesn't/can't properly validate the client certificate that the Nomad agent is sending?

Nomad version is 1.4.5 on the clients, version 1.5.3 on the servers
Consul version is 1.5.2

I can send more details or logging if needed, but in this stage I don't know what information is useful. Also, I don't know if this is an issue with Nomad or with Consul. 

I saw that there seems to be a problem when upgrading Consul to 1.5 when using sevice mesh: https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific but I don't see any errors related to some 72hr period.

**Comment by lgfa29** [comment]
Thanks for the report and the details @fred-gb and @jrnijboer.

Would you be able to test in a previous version of Consul to see if the problem is still happens before 1.15?

**Comment by fred-gb** [comment]
Hi!

I downgraded Nomad and Consul:
```
root@sandbox:/usr/bin# nomad --version
Nomad v1.4.8 (e73b15d48fee68418eb08d61bc3de6bcf3fca3c6)
root@sandbox:/usr/bin# consul --version
Consul v1.14.6
Revision 5b529174
Build Date 2023-03-29T22:32:47Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

But... Same problem 😢 

```
[2023-04-18 06:03:05.653][1][warning][config] [./source/common/config/grpc_stream.h:201] DeltaAggregatedResources gRPC config stream to local_agent closed since 107s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
[2023-04-18 06:03:25.886][1][warning][config] [./source/common/config/grpc_stream.h:201] DeltaAggregatedResources gRPC config stream to local_agent closed since 128s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
[2023-04-18 06:03:44.452][1][warning][config] [./source/common/config/grpc_stream.h:201] DeltaAggregatedResources gRPC config stream to local_agent closed since 146s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
```

Thanks

**Comment by JonathanTroyer** [comment]
I am also getting this error with Nomad v1.6.1 and Consul v1.16.1 using a similar configuration (following the [Nomad Deployment Guide](https://developer.hashicorp.com/nomad/tutorials/enterprise/production-deployment-guide-vm-with-consul)). This is preventing us from using TLS with gRPC.

**Comment by sevensolutions** [comment]
I can confirm that, using the same versions like @JonathanTroyer. Took me an hour until i found that issue.

**Comment by kaspergrubbe** [comment]
Did you ever find a solution for this? I think I am hitting the same issue here: https://github.com/hashicorp/nomad/issues/19772

Is TLS with GRPC just not supported?

**Comment by fred-gb** [comment]
No sorry...

**Comment by tgross** [comment]
Hi folks, sorry to say this _is_ currently a Consul limitation, as described in https://github.com/hashicorp/consul/issues/13088.

I've opened a docs PR to make sure there's a warning about this: https://github.com/hashicorp/nomad/pull/19970
