### ISSUE TITLE
[question] Nomad docker use swap

### ISSUE THREAD

**Issue by jtuthehien** [hashicorp/nomad#1687]
Hi.
According to the documentation:

Nomad limits containers' memory usage based on total virtual memory. This means that containers scheduled by Nomad cannot use swap. This is to ensure that a swappy process does not degrade performance for other workloads on the same host.

However, it doesnt seem to be the case. When running out of memory, the docker container is still using the host's swap memory

**Comment by dadgar** [comment]
Hey,

What version of Nomad are you running. There was a bug that was fixed in 0.4.1 (https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md). #1480
