### ISSUE TITLE
[question] nomad run immediately dead

### ISSUE THREAD

**Issue by ynqa** [hashicorp/nomad#1688]
If filing a bug please include the following:

### Nomad version

```sh
$ nomad -v
Nomad v0.3.2
```

### Operating system and Environment details

`CentOS release 6.6 (Final)`

### Issue

If I try `nomad run` a  job name the same as past, the state turns **dead** at once.
I also try it with different job name that was never set on past, and the process completely run.

I also think that service type is related it: every dead case is set type `batch`, but go well on type `service` (I recognize when job with type `service` is run, before process with the same job name is overrode, and re-run)

### Reproduction steps
1. `nomad run` with nomad file that set job name (whatever), and  type `batch`.
2. confirms finished, try again with the same name and type.

**Comment by Saint1991** [comment]
We got the same problem .
We also use the `v0.3.2` in both Nomad server and agents.

Here is our job definition file.
```
job "gatling" {

  datacenters = ["dc"]
  type = "batch"

  group "gatling-kafka" {
    count = 2
    restart {
      attempts = 1
      mode = "fail"
    }
    task "gatling-kafka" {
      driver = "docker"
      config {
        image = "gatling-scenario:latest"
      }
      env {
        KAFKA_BOOTSTRAP_SERVERS = "kafka_server:9092"
        TOPIC = "test"
        THROUGHPUT = 30000     
        DURATION_MINUTES = 12  
      }
      resources {
        cpu = 1000
        memory = 1024
        network {
          mbits = 50
        }
      }
    }
  }
}
```

More detail description of the situation is below.
1. `nomad run ${the file above}`
2. the job status turns to dead with job completion
3. `nomad stop gatling`
4. `nomad run ${the file above}`
5.  the job status immediately turns to dead 

We checked there is enough resource on the nomad agent server and all the node status are "ready"

we also found that the same allocID of the 1st execution is used for the 2nd execution when the problem occurs.
So, I think It may be a bug on the provisioning.

**Comment by dadgar** [comment]
@ynqa Please see the referenced issue that @Saint1991 linked. 

The job name in Nomad is unique, which is why you are seeing the behavior you are. We have opened an issue to allow a force run. I am going to close the issue but if you have any questions or what you are reporting isnt the same we can re-open.
