### ISSUE TITLE
[CLI] - "--wait" option support with Nomad CLI Command - "nomad job run <filename.hcl>"

### ISSUE THREAD

**Issue by SuyashHashiCorp** [hashicorp/nomad#16898]
Hi Team,

The purpose of the wait option is when the service is to type **batch** to wait for the returned code of the execution. If the execution is okay, the CLI will `exit 0` otherwise `exit 1`.

Use Case - we use batch mode when upgrading a database. The wait option will prevent manually getting the status of the job with a new command.

Thanks..!!

**Comment by EtienneBruines** [comment]
Related to https://github.com/hashicorp/nomad/issues/11601

**Comment by lgfa29** [comment]
Thanks for the idea @SuyashHashiCorp. 

I think @EtienneBruines is right, and this does feel like it fits into #11601. There's a difference that this issue is about `job run` of batch jobs, but I think that can be incorporated into #11601, so I will mention this use case there.
