### ISSUE TITLE
[CLI] - indentation option with "nomad fmt" command

### ISSUE THREAD

**Issue by SuyashHashiCorp** [hashicorp/nomad#16897]
Hi,

The feature is for specifying an -indent/-spaces parameter for the "nomad fmt" command.

UseCase like below - 
Let's say a user would like to have the option to indent with 2\4 spaces, s/he would be able to specify something like below: 

**"nomad fmt -indentation=4"** 

and it would indent the jobs accordingly.

Thanks..!!

**Comment by lgfa29** [comment]
Thanks for the idea @SuyashHashiCorp.

`nomad fmt` uses the default HCL formatter, which is highly opinionated to ensure consistency across files. This formatter follows the [HCL standard of using two spaces](https://github.com/hashicorp/hcl/issues/212#issuecomment-330655720), so we can't make this configurable. 

Even if there was an option it would deviate from the standards used in other HCL files, which is not something we would like to have just in Nomad so I'm going to close this one, but thanks for the suggestion 🙂
