### ISSUE TITLE
Add more documentation about how nomad and consul works together

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#169]
There are some bits here and there in the docs talking about how consul can be used for service discovery, however it's unclear how it all fits together.

There should be more information regarding this, and perhaps an example cluster where nomad and consul is set up in tandem.

**Comment by zrml** [comment]
+ 1

**Comment by sielaq** [comment]
I suspect they do not work together yet, but it would be awesome to not to use registartor for that.
+1

**Comment by ryanuber** [comment]
This integration is in the works and should be functional soon! We will definitely include detailed documentation on the specifics.

**Comment by bhameyie** [comment]
+1

**Comment by djsly** [comment]
:+1:

**Comment by defender** [comment]
+1

**Comment by raykrueger** [comment]
:+1: Definitely interested in this.

**Comment by Dahs81** [comment]
:+1:

**Comment by maxenglander** [comment]
:+1:

**Comment by defender** [comment]
+1

**Comment by adamveld12** [comment]
:+1:

**Comment by zanedeg** [comment]
+1

**Comment by marcelocorreia** [comment]
+1

**Comment by c4milo** [comment]
I'm very much looking forward to having this.

**Comment by dadgar** [comment]
Here you guys go: https://www.nomadproject.io/docs/jobspec/servicediscovery.html

**Comment by F21** [comment]
@dadgar Are there still any plans to let nomad manage consul?

**Comment by dadgar** [comment]
@F21: Not in the sense that we will have the Nomad client download or even launch Consul during startup. Instead we will be advocating the usage of a System job that schedules Consul on every node. We will hopefully be able to write a tutorial on this in the near future.

**Comment by F21** [comment]
@dadgar In the case of running consul as a system job, would consul be in a docker container (with host networking) or would consul be run using exec?

**Comment by ketzacoatl** [comment]
I think the docs are clear @F21: it's up to the operator to make that all work - and depending on the details in your setup, either _could_ work.

**Comment by dadgar** [comment]
@F21: Yeah it will depend on your use case. If you are doing script based health checks then possibly with a `raw_exec`. If you aren't then docker or exec would both work but with docker you would have to set up networking correctly.

**Comment by sielaq** [comment]
I have created small playground,
so you have all pieces (Scheduler/ServiceDiscover/Proxy-LoadBalancer)  in one box
https://github.com/eBayClassifiedsGroup/KomPaaS
enjoy

**Comment by netroby** [comment]
+1

**Comment by borice** [comment]
The documentation explaining how Nomad and Consul work together still sucks.  Specifically, how you get a nomad service to be found by a different service that depends on it (and get the address and port number that nomad allocated, etc)

These pages need to be improved to explain this, and include examples:
https://www.nomadproject.io/docs/service-discovery/index.html
https://www.nomadproject.io/docs/job-specification/service.html

**Comment by c4milo** [comment]
@borice if you already know, I'm sure we would all appreciate a PR from you improving the docs :)

**Comment by borice** [comment]
@c4milo i don't already know... i was trying to learn, but hit a dead end.
It's all trial-and-error for me now.

**Comment by borice** [comment]
For completeness, I'm trying to understand the following:

I have a nomad service running a mongodb docker container on a random port assigned by nomad.
I have a separate nomad service running an app (perhaps on a different nomad node in the nomad cluster), which needs to be told where the mongodb lives to be able to connect to it.  

How do I tell the app in its "service" stanza about the mongodb service? (host and port)

**Comment by c4milo** [comment]
@borice try what's documented in https://github.com/hashicorp/consul-template#service

**Comment by sielaq** [comment]
@borice you have few choices:
1. use proxy/LB thats gonna expose you the static port or domain  (https://github.com/eBay/Fabio)
2. your app can talk to consul directly to get ports (many libraries are available)
3. you can start app with consul-template as suggested by @c4milo 
4. or you can simply use consul DNS to resolve it, in you startup script.
  for example (assuming that you have `consul` as a domain, and you have DNS configured with consul):
  `PORT=$(dig +short SRV mongo-1.service.consul | cut -d \  -f3)`
  assuming that you don't have DNS configured with consul, and consul IP is 192.168.1.1:
  `PORT=$(dig +short  @192.168.1.1 -p 8600  SRV mongo-1.service.consul | cut -d \  -f3)`

but options 3. and 4. are not optimal - whenever your DB gonna be restarted -  a different port gonna be chosen
so your app would have to be restarted 
if you enforce a static port in nomad  - this might work - and thats the desired solution.

If you still prefer to have random ports in nomad's workers option 1.would be the best:
1. you'r app is agnostic from consul
2. you always have a specific static port on LB (or domain - depends how you gonna balance: layer 4 or 7 - you can choose it in Fabio) 
so in worst case scenario, your app just need to reconnect.
