### ISSUE TITLE
ARM: allocation fails

### ISSUE THREAD

**Issue by nicolai86** [hashicorp/nomad#1693]
### Nomad version
0.4.1, official ARM binary 

### Operating system and Environment details
Ubuntu 16.04, running on Scaleway C1 ARM instances

### Issue
Cannot allocate jobs:

2016/09/07 20:43:15.772811 [WARN] client: failed to build task directories: user: Lookup requires cgo

### Reproduction steps
1. Start Scaleway C1 ARM server
2. install nomad (see https://github.com/nicolai86/scaleway-terraform-demo/blob/f8ac33c2ae499501ce94eb4520ea82b1475bfca0/modules/nomad/scripts/install.sh for terraform install script)
3. try to run any allocation - will always fail

As a side note: a self compiled version of nomad 0.4.0 worked just fine. Maybe an issue in which environment the arm binary was build.

### Nomad Client logs (if appropriate)

**Comment by dadgar** [comment]
Hey,

Sorry we must have made a mistake when we built the official binaries. Will make sure to get them right for 0.5

**Comment by nicolai86** [comment]
❤️
