### ISSUE TITLE
SIGSEGV on nomad plan

### ISSUE THREAD

**Issue by pschichtel** [hashicorp/nomad#16939]
### Nomad version
Nomad v1.5.3

### Operating system and Environment details

Archlinux (Stable), up to date

### Issue

While the nomad plan command generally works, it crashes with a SIGSEGV at the end, bash -x output:

```
+ nomad job plan --diff=false example.nomad
Scheduler dry-run:
- All tasks successfully allocated.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55de36ab6a93]

goroutine 1 [running]:
github.com/hashicorp/nomad/command.getExitCode(...)
	/build/nomad/src/nomad/command/job_plan.go:394
github.com/hashicorp/nomad/command.(*JobPlanCommand).outputPlannedJob(0xc0005c0700, 0xc0006029c0?, 0xc000220d20, 0xb0?, 0x13?)
	/build/nomad/src/nomad/command/job_plan.go:327 +0x2f3
github.com/hashicorp/nomad/command.(*JobPlanCommand).Run(0xc0005c0700, {0xc0000520d0, 0x2, 0x2})
	/build/nomad/src/nomad/command/job_plan.go:265 +0xcb0
github.com/mitchellh/cli.(*CLI).Run(0xc000a25e00)
	/build/nomad/src/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.Run({0xc0000520b0, 0x4, 0x4})
	/build/nomad/src/nomad/main.go:107 +0x28a
main.main()
	/build/nomad/src/nomad/main.go:77 +0x4e
+ exit_code=2
+ '[' 2 == 1 ']'
+ echo 'Job planning failed: 2'
Job planning failed: 2
+ exit 2
```

The plan did indeed happen, but apparently it crashed when trying to determine the exit code.

### Reproduction steps

1. setup local single-node consul
2. setup local single-node nomad
3. write simple job file
4. run `nomad plan job.nomad`

#### Expected Result

Program exits normally

#### Actual Result

Program crashes with aforementioned SIGSEGV.

**Comment by lgfa29** [comment]
Thank you for the report @pschichtel!

This is the result of a new check added in 1.5 that did not expect the `-diff=false` to behave the way it currently does. I opened https://github.com/hashicorp/nomad/pull/16944 with a fix for this problem.

In the meantime if you can avoid the panic by removing `-diff=false`. It's not an ideal solution, but it's a possible workaround until the fix is released.

**Comment by pschichtel** [comment]
@lgfa29 thanks for the quick fix. I've seen the change has also been backported. Is there a patch release on the horizon?

**Comment by lgfa29** [comment]
No specific date, but we should have a new release out soon 🙂
