### ISSUE TITLE
Scaling of system jobs

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#16963]
I know the issue sounds weird.

The nomad docu says

> The system scheduler is used to register jobs that should be run on **all clients that meet the job's constraints**. The system scheduler is also invoked when clients join the cluster or transition into the ready state. This means that all registered system jobs will be re-evaluated and their tasks will be placed on the newly available nodes if the constraints are met. 

But the command  for example is able to scale the traefik  job up and down.  And the deployment state is hanging inifite.
```shell
nomad job scale ingress traefik 3
```

![image](https://user-images.githubusercontent.com/5046525/233811567-e12c4a6f-bcbb-4cf5-8a8b-0fac2ca89a5e.png)

The only option is to exexute nomad deployment fail command. 

I can understand this werid behoivur of nomad the scale command executed on a system job.

Isn't it better to deny the scale command for not scaleable job types ?

### Nomad version
Nomad v1.5.1
BuildDate 2023-03-10T22:05:57Z
Revision 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7

**Comment by jrasell** [comment]
Hi @suikast42 and thanks for raising this issue.

> Isn't it better to deny the scale command for not scaleable job types ?

Yes I totally agree; Nomad should return an error when a user attempts to scale a job whose type is system.

**Comment by shantanugadgil** [comment]
counterpoint: why is this a bug? the issue occurs only when there are listening ports involved and scaling > 1 fails.

ref: https://github.com/hashicorp/nomad/issues/12064

**Comment by jrasell** [comment]
> counterpoint: why is this a bug? the issue occurs only when there are listening ports involved and scaling > 1 fails.
> 
> ref: #12064

Hey @shantanugadgil; system jobs should only run one allocation per client that matches any constraints. This bug allowed scaling so that > 1 allocation of the same task group could be run on the same client.

**Comment by bsftshantanu** [comment]
Right, so my request was that instead of _completely disallowing_ scaling, could you allow scaling between [0-1] inclusive for `system` jobs? :pray:

**Comment by shantanugadgil** [comment]
Right, so my request was that instead of _completely disallowing_ scaling, could you allow scaling between [0-1] inclusive for `system` jobs? :pray:
