### ISSUE TITLE
[question] Consul KV Path per Task

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/nomad#1696]
Is there a way to use any of the runtime environment variables of Nomad to uniquely identify a path in Consul for storing the values (this path should be accessible across different containers launched as part of the same job)
From the docs, I couldn't really identify an environment variable than can identify the job. The only workaround was to define an additional `env` in the job specification

**Comment by dadgar** [comment]
@vrenjith Please prefer the Gitter or mailing list for questions.

These may be useful to you:
```
"NOMAD_ALLOC_ID=940b77d7-f830-1a35-edc2-0a96526fcd49"
"NOMAD_ALLOC_NAME=example.cache[0]"
```

The allocation ID is unique per task group and the alloc name has the following format `<job>.<task_group>[<instance>]`.

And as you mentioned, you can inject any other variable that may be of use to you

**Comment by vrenjith** [comment]
Thanks @dadgar
