### ISSUE TITLE
Unable to decode payload from event stream

### ISSUE THREAD

**Issue by dwinshipIdentifi** [hashicorp/nomad#16985]
### Nomad version
Output from 1.3.0

### Operating system and Environment details
Windows Server 2019

### Issue
When attempting to decode the payload in the event stream it is failing. I tried even using an online base64 decoder and I'm still unable to fully decode the payload

### Reproduction steps
Attempt to decode the job payload from the event stream using UTF-8 from BASE64 decoding

#### Expected Result
Payload should decode correctly without missing data and extra characters

#### Actual Result
Missing data and additional characters in the decoded string

**Comment by dwinshipIdentifi** [comment]
Found the bug! We were not encoding properly.

**Comment by dwinshipIdentifi** [comment]
To replicate this call the /dispatch and include a base64 encoded payload in the body. Then find the job in the event stream and compare the payload output.

Example: Submitted payload -  "aGVsbG8="
Event stream payload - "BRBoZWxsbw=="

**Comment by shoenig** [comment]
I had to dig through the code to realize this, but I believe what's happening is the Job Event JSON object is actually a base64 encoding of **snappy compression** data of the original bytes.

A simple example

First we need `snappytool`

```
go install github.com/golang/snappy/cmd/snappytool@latest
```

Create a dispatch job
<details><summary>payload.hcl</summary>

```hcl
job "payload" {

  type = "batch"

  parameterized {
    payload = "required"
  }

  group "group" {
    task "task" {
      driver = "raw_exec"

      config {
        command = "cat"
        args = ["${NOMAD_TASK_DIR}/payload.txt"]
      }

      dispatch_payload {
        file = "payload.txt"
      }

      resources {
        cpu    = 10
        memory = 32
      }
    }
  }
}
```
</details>

Register the dispatch job

```
nomad job run payload.hcl
```

Dispatch the dispatch job

```
nomad job dispatch payload - <<< 'this is a payload'
```

Find one of our payloads

```
# just grab one
nomad operator api /v1/event/stream?topic=Job | jq .Events[].Payload.Job.Payload 2>/dev/null
```

Try to base64 decode it (not quite what we expect, and is more obvious with longer input)

```
echo EkR0aGlzIGlzIGEgcGF5bG9hZAo= | base64 -d
Dthis is a payload
```

This time also decompress it

```
echo EkR0aGlzIGlzIGEgcGF5bG9hZAo= | base64 -d | snappytool -d
this is a payload
```



So, if your original payload was base64 encoded already before sending to `job dispatch`, you'd need to add another base64 decode on the end.

**Comment by dwinshipIdentifi** [comment]
Is there way to disable the snappytool compression step? We are writing a Dotnet microservice so I don't have access to snappytool to decompress it.

**Comment by shoenig** [comment]
I don't believe there's a way to disable the snappy compression; it's there to protect Nomad's raft store from being bloated / overwhelmed as much as we can.

Google's docs for snappy mention some library options for .NET languages which may be useful
https://google.github.io/snappy/

**Comment by dwinshipIdentifi** [comment]
Unfortunately a lot of those projects are dead. I'll have to find another way to get the data. Well at least now I know what the problem is. 

Thanks for the help.

**Comment by dwinshipIdentifi** [comment]
In case anyone else finds this issue. I was able to find a package that is still supported.

https://www.nuget.org/packages/IronSnappy/

 string encodedString = "EkR0aGlzIGlzIGEgcGF5bG9hZAo=";
byte[] data = Convert.FromBase64String(encodedString);
byte[] uncompressed = Snappy.Decode(data);
string decodeString = Encoding.UTF8.GetString(uncompressed);
Console.WriteLine(decodeString);
