### ISSUE TITLE
Helm Chart for Nomad - future availability ?

### ISSUE THREAD

**Issue by WitoldSlawko** [hashicorp/nomad#16980]
Hello.

I was searching over the Hashicorp's content and overall internet, and was not able to find the kubernetes helm chart for Nomad. Also from https://helm.releases.hashicorp.com/, seems that it's missing...

Therefore I would like to ask, are you planning to bring it on to community? Sadly I cannot see it on Nomad roadmap, but still rooting and hoping it will come one day...

Can you please at least let me know if you plan to make it happen?

cheers,
Witold

**Comment by shoenig** [comment]
Ah I see, yeah I could see the use case for running Nomad Server agents on a k8s cluster, if that's something that already exists in your environment. But yeah, the Helm chart for that simply doesn't exist (we currently don't even publish Docker images for Nomad agents, even if it could be useful just for Server agents). Maybe in the future, but it currently isn't something on any internal roadmap.

**Comment by WitoldSlawko** [comment]
I get it. No worries, then I will either build it myself or simplify it by going into ASG. 
Anyways thank you for response. I will close this issue now. Cheers.

**Comment by williamoliveira** [comment]
> Hi @WitoldSlawko, Nomad and k8s are [both task orchestrators](https://developer.hashicorp.com/nomad/docs/nomad-vs-kubernetes) - the notion of using a Helm chart to deploy Nomad on a k8s cluster seems odd, at best. We'd be interested in hearing more about your use case, but it's very unlikely there will ever be an official Helm chart for Nomad.

I run I my tools (gitlab, teleport, awx, consul) on kubernetes, Nomad would be a new tool I will use to orchestrate a subset of services that really doesnt fit kubernetes. Is that really too odd?

**Comment by ivzhh** [comment]
> I run I my tools (gitlab, teleport, awx, consul) on kubernetes, Nomad would be a new tool I will use to orchestrate a subset of services that really doesnt fit kubernetes. Is that really too odd?

It is odd for production use (large size licensed users) and it is reasonable for the hobby use. The ROI is bad for hashicorp to invest resource on it while most licensed users use this as an option to migrate their codebase. This is a feature for community-driven project.
