### ISSUE TITLE
fingerprinting: ifconfig regex fails 

### ISSUE THREAD

**Issue by apognu** [hashicorp/nomad#170]
Hi,

The ifconfig version that comes with net-tools 2.10-alpha (on Arch) breaks the regex used in network_unix.go.

```
$ ifconfig eth0
lan: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
    inet 192.168.0.64  netmask 255.255.0.0  broadcast 192.168.255.255
    ...
$  ifconfig --version
net-tools 2.10-alpha
```

Is there any compatibility reason not to use iproute2 for IP management (are there any distros out there where it's not available?)?

As for #158, maybe we could add a configuration directive to bypass automatic detection?

Regards,

**Comment by cbednarski** [comment]
@apognu Is this still an issue since #189 has been merged? If so can you clarify what still needs to be addressed?

**Comment by dadgar** [comment]
We don't use the regex anymore so closing.
