### ISSUE TITLE
breaking change should be documetned

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#17000]
artifact: enable inheriting environment variables from client https://github.com/hashicorp/nomad/pull/15514

regarding the above commit, we were relying on the client to pass credentials to the getter subprocess. After upgrading to nomad 1.5.3 our testing clusters start to fail to fetch artifacts, despite seeing no breaking change related to this aspect.

Open an issue since the orignal pr above is locked, just for some awareness, since a nice change could have very realistic downstream effect, thats all :) 

still, thanks for the continuous improvements to the product! That is the reason keeping us wanting to upgrade :D

**Comment by shoenig** [comment]
Thanks for the suggestin @fredwangwang! I've created https://github.com/hashicorp/nomad/pull/17005 to add breaking change entries to the 1.5.0 release in the CHANGELOG.md file, as well as added an Environment section to the `artifact` job-specification docs. 

The changes were originally noted in the [Nomad 1.5.0 upgrade notes](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#nomad-1-5-0), but it's easy to miss those, especially so long after the release.
