### ISSUE TITLE
ui: display roles in token page

### ISSUE THREAD

**Issue by the-nando** [hashicorp/nomad#17019]
After completing the login, the OIDC flow redirects to `/ui/settings/tokens` which displays some information about the granted token:
![Untitled](https://user-images.githubusercontent.com/89834752/235099998-792a2ea1-e9a0-4328-b8a3-e0d56be6ba7c.png)

### Proposal
It would be great to also display which roles the token has assigned, alongside the policies, if any.

### Use-cases
It is currently confusing to our users to be displayed only an empty list of policies when using roles.

### Attempted Solutions
None yet.

**Comment by jrasell** [comment]
Hi @the-nando and thanks for raising this issue. This is something we absolutely want to have available in the UI and therefore I'll pass this over to our UI engineering team.

**Comment by philrenaud** [comment]
Hi @the-nando — just noting that this issue will be resolved by https://github.com/hashicorp/nomad/pull/18346 . Look for it in a release soon!

**Comment by philrenaud** [comment]
Hi @the-nando — this and some other role-related UI improvements are made in #17770 .
