### ISSUE TITLE
Documentation - Wrong file specified for sshkey in git artifact example

### ISSUE THREAD

**Issue by plasmastorm** [hashicorp/nomad#17027]
In the second example of the [Artifact Block > Download using Git](https://developer.hashicorp.com/nomad/docs/job-specification/artifact#download-using-git) section the `ssh_known_hosts` file is shown instead of the private SSH key used to connect to the git repository.

Rather than
```
    sshkey = "${base64encode(file("/etc/ssh/ssh_known_hosts"))}"
```
I would have expected it to be something like
```
    sshkey = "${base64encode(file("/path/to/privatekey"))}"
```

**Comment by jrasell** [comment]
Hi @plasmastorm and thanks for raising this issue. I have raised a PR to fix this piece of documentation.
