### ISSUE TITLE
CPU resource calculation is wrong

### ISSUE THREAD

**Issue by xytis** [hashicorp/nomad#1703]
### Nomad version
Nomad v0.4.0

### Issue

Tested on several servers:
1. 24vCPU, each around 2800MHz
2. 24vCPU, each around 2700MHz
3. 24vCPU, each around 2200MHz

Expected CPU resource:
1. 67200
2. 64800
3. 52800

Nomad measured CPU (nomad node-status -self):
1. 44784
2. 64776 (correct in terms of rounding error)
3. 30864

This bug is caused by using [runtime.NumCPU()](https://github.com/hashicorp/nomad/blob/5905a7046a52e3709376e4c78852daeb08853589/helper/stats/cpu.go#L23) which according to documentation returns "NumCPU returns the number of logical CPUs usable by the current process."

### Possible solution

helper/stats/cpu.go should use `len(cpu.Info())` as a metric for understanding how many cores a system has. In addition it would be great if nomad made 'less strict guess' about hardware CPU capacities, since most of linux kernels are quite good at scheduling work.

**Comment by xytis** [comment]
I considered actually performing a sum on 'cpu.Info()' fields instead of multiplying first found core speed by core count. It would avoid issues with multi-cpu machines, but it still would make computational mistake when cpuinfo returns not maximum cpu speed, but current. That is possible and due to kernel settings cpu's may be working in slower pace until some load threshold is reached (https://www.kernel.org/doc/Documentation/cpu-freq/governors.txt)

**Comment by dadgar** [comment]
Left a comment on your PR, as to why this may not be an issue any more

**Comment by dvusboy** [comment]
@xytis Do you expect `runtime.NumCPU()` to be different from `len(cpu.Info())`? It that by way of [cpusets](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)? That said, from the perspective of a Nomad agent, that kind of restriction is unlikely, right?

**Comment by xytis** [comment]
@dvusboy, You are correct, the restriction is unlikely. My initial problem was not CPU count, but MHz calculation, and indeed it is fixed on nomad master. Closing this.
