### ISSUE TITLE
Canceled evaluation provide circular or wrong debug information.

### ISSUE THREAD

**Issue by stswidwinski** [hashicorp/nomad#17070]
### Nomad version
Built off tip

### Operating system and Environment details
Unix

### Issue
When an evaluation is canceled, it produces confusing or wrong debug information. In particular:
```
$ nomad eval status  -namespace '*' -json 81235e65
{
    [...]
    "CreateIndex": 6445487,
    "CreateTime": 1682965847060638834,
    [...]
    "ModifyIndex": 6445493,
    "ModifyTime": 1682965847060638834,
    [...]
    "Status": "canceled",
    "StatusDescription": "evaluation \"81235e65-7e71-9595-0a34-00674bff2b75\" successful",
    [...]
}
```
There are a few interesting points:

1. `CreateIndex` and `ModifyIndex` are different but `CreateTime` and `ModifyTime` are the same. In practice the times should be 30  seconds apart.
2. `StatusDescription` reports the successful evaluation as the same evaluation which is canceled. This is not the intended information.

I will submit a proposed patch to fix these fields below.

**Comment by jrasell** [comment]
Hi @stswidwinski thanks for raising this issue and the corresponding PR. We will take a look into this shortly.

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/17071 which will ship in the next release of Nomad 1.5.x, with backports to 1.4.x and 1.3.x.
