### ISSUE TITLE
nomad v1.5.4: Missing allocation log files on upgrade

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#17076]
### Nomad version
Nomad v1.5.4
BuildDate 2023-05-02T23:21:16Z
Revision f716d6b04845c88b87c04b0cbd9e377b829b96d7

### Operating system and Environment details
Ubuntu 22.04.2 LTS on amd64

### Issue
No logs are being collected.

The logs show (per task): 
```
[DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=3b4e72d3-93b1-ed04-089d-0cf23fbd3034 task=nginx
```

### Reproduction steps
Upgrade to v1.5.4

#### Expected Result
Logs to be collected by default. Possibly https://github.com/hashicorp/nomad/pull/16962 is related?

#### Actual Result
No logs are created. 

![Screenshot_20230504_082941](https://user-images.githubusercontent.com/3962174/236127246-e74aa1e1-883b-4bdb-9c94-7c29195c397b.png)

### Job file (if appropriate)

The example job file.

### Nomad Server logs (if appropriate)
Probably not related.

### Nomad Client logs (if appropriate)
```
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.374Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=2c7e7f09-200a-d22a-eb8c-6766a1c0b8b7 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.375Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=3915ef58-2f67-522d-5770-356bf5461d19 task=connect-proxy-q-ide
ntity
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=681885c2-f68f-f198-9df7-04eda5f53309 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=868df8b7-f3b8-6283-7eb9-a875c7eedb21 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=c5718f77-41bc-7489-7d96-9c93c37b9d12 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=55676ad0-bcce-daa4-50d1-bc2ccbbff359 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=5986469e-1c7b-ebdf-8a79-70b45f3d434c task=connect-proxy-q-gat
eway--manager
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=ab8a341b-27d1-b810-3b1e-2c53ff62a2d1 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.390Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=e7be8f63-1629-267a-a1e9-98c9b1301fd4 task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=3c7bc88d-5464-0806-24ab-0f897946a80d task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.391Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=6725cdb3-1a92-8276-fc70-1b2965a4c47f task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=79cc6364-925a-f062-6151-27f215733903 task=connect-proxy-maria
db-galera-replication-01
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.392Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=83726460-c3b1-372f-3e3d-df365ad373cb task=sync
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.393Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=b2d91190-3354-c4d9-8cd6-22a909e2bae4 task=connect-proxy-q-ots
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=9408e26f-f2bd-81c3-b3fd-c2a22520d25b task=filebeat
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=a0031a7e-8a5a-346e-6a16-b46f859ae243 task=sync
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=2c7e7f09-200a-d22a-eb8c-6766a1c0b8b7 task=sync
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=3915ef58-2f67-522d-5770-356bf5461d19 task=nginx
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=3915ef58-2f67-522d-5770-356bf5461d19 task=backend
May 04 06:11:56 hashivault02-ham nomad[1289]:     2023-05-04T06:11:56.376Z [DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=681885c2-f68f-f198-9df7-04eda5f53309 task=sync
```

**Comment by jrasell** [comment]
Hi @EtienneBruines and thanks for raising this issue. I have been able to reproduce this locally using the steps detailed below; we will look into this as a priority.

1. Start a Nomad v1.5.3 agent using `nomad agent -config=<path>` and the following config:
```
log_level = "DEBUG"
data_dir  = "/tmp/nomad-dev-cluster/server1"

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled = true
}
```

2. Generate and register the example job using the command `nomad job init -short && nomad job run example.nomad.hcl`.

3. Stop the Nomad agent, and start it again using the v1.5.4 binary.

4. View the agent logs and observe the line similar to `[DEBUG] client.alloc_runner.task_runner.task_hook: log collection is disabled by task: alloc_id=dea90cf9-35e5-6369-e5cf-a7cd3647f120 task=redis`

5. Inspect the registered job and view the tasks log config:
```
"LogConfig": {
    "Enabled": false,
    "MaxFileSizeMB": 10,
    "MaxFiles": 10
},
```

**Comment by bfqrst** [comment]
Can confirm. Just upgraded a cluster to `v1.5.4` (server and clients) and all logs are AWOL... That is, if everything is upgraded. I still can see logs from a `v1.5.3` client being orchestrated by a `v1.5.4` server cluster...

**Comment by suikast42** [comment]
Maybe releated to https://github.com/hashicorp/nomad/pull/16962 ?

**Comment by jrasell** [comment]
Hi all, yes as pointed out a couple of times this seems to be related to 16962. I suspect that on upgrade the client is defaulting to false, whereas the intention is that a nil value defaults to true to ensure backwards compatibility. This is being looked into currently by the engineering team and we will post any update to this ticket.

**Comment by tgross** [comment]
Hi folks, sorry about this. I missed the case y'all are hitting here during testing. I've been able to reproduce locally and the sequence of events is:

* When the server restarts for the upgrade, it loads the Job from the Raft snapshot/logs. The jobspec has long since been parsed, so none of the guards around the default value are in play. The empty field value for `Enabled` is the zero value, which is `false`.
* This doesn't impact any _running_ allocation because we don't replace running allocations when either the client or server restart.
* But as soon as any allocation gets rescheduled (ex. you drain all your clients during upgrades), it'll be using the Job that the server has, which has `Enabled = false`.

A workaround that I've just tested is that re-running the job will go thru the guards that set the default value to `Enabled = true`. Unfortunately that's going to be considered a destructive update by the server and your allocations will all get re-deployed. But it looks like that'll correctly restore log collection.

Meanwhile, I'm working on a fix.

**Comment by tgross** [comment]
Draft PR is up here: https://github.com/hashicorp/nomad/pull/17087 Still testing that.

**Comment by tgross** [comment]
Nomad 1.5.5 has shipped. Thanks for your patience on that, folks.

>  Although seeing something strange with template configuration for a log shipper service that gets re-rendered and keeps on restarting (will investigate next week and log a separate case if it doesn't exist).

Hi @freef4ll! For sure open a new bug for that issue if it turns out to be a problem. Thanks!
