### ISSUE TITLE
v1.5.3: TaskGroup Rescheduling not enforced

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#17072]
### Nomad version
Output from `nomad version`
Nomad v1.5.3
### Operating system and Environment details
Amazon Linux 2
### Issue
We have been finding jobs that are not replacing the allocations that have failed as they are scheduled to:
<img width="810" alt="Screen Shot 2023-05-03 at 10 44 10 AM" src="https://user-images.githubusercontent.com/4636740/236001018-6021ce33-1b8c-4d14-9c4b-abef91dcf1be.png">

In the screenshot, you will find a job that has 5 taskgroups of 1 allocation each, but you will notice that only 2 allocations are currently running.

Here is the restart policy for one of those allocations not running:

#### Task Group
```json
"RestartPolicy": {
        "Attempts": 0,
        "Interval": 180000000000,
        "Delay": 1000000000,
        "Mode": "fail"
      }
```
```json
"ReschedulePolicy": {
        "Attempts": 0,
        "Interval": 0,
        "Delay": 15000000000,
        "DelayFunction": "exponential",
        "MaxDelay": 300000000000,
        "Unlimited": true
      }
```
##### Leader Task
```json
"RestartPolicy": {
            "Attempts": 0,
            "Interval": 180000000000,
            "Delay": 1000000000,
            "Mode": "fail"
          }
```
##### Sidecar Task
```json
"RestartPolicy": {
            "Attempts": 0,
            "Interval": 180000000000,
            "Delay": 1000000000,
            "Mode": "fail"
          }
```
##### Connect Proxy Sidecar Task
```json
"RestartPolicy": {
            "Attempts": 0,
            "Interval": 180000000000,
            "Delay": 1000000000,
            "Mode": "fail"
          }
```

With this configuration, my understanding that once the leader task fails, Nomad _should_ be rescheduling the task w/ an exponential backoff from sequential failures starting at 15 seconds with a max of 300 seconds(5 minutes). However, **Nomad is not rescheduling anything**, its as if it thinks the job is in its desired state.

### Reproduction steps
Difficult to reproduce as we run thousands of jobs, and tens of thousands of scheduled tasks, we see this only commonly because we run at this scale.

#### Expected Result
Nomad should be attempting to converge the job state w/ the job definition.

#### Actual Result
Nomad is not rescheduling allocations on task groups, leaving the job in an incomplete state, but does not recognize that it is so.

### Job file (if appropriate)
Too big to paste in for Github, can send over if requested.

**Comment by tgross** [comment]
Hi @djenriquez! The first place I'd want to look at in this case is whether there were any evaluations created when those allocations failed. If you look at `nomad job status -evals :jobid` it'll list the most recent evaluations and whether they had placement failures.

**Comment by djenriquez** [comment]
Thanks for the response @tgross. To verify, we want to do this when we run into the situation right?

Heres the output from a job that had just run into this, unfortunately, we fixed the state before I saw this message:

```bash
nomad job status -evals <REDACTED>-errorwiz
ID            = <REDACTED>-errorwiz
Name          = <REDACTED>-errorwiz
Submit Date   = 2023-05-16T11:52:00-07:00
Type          = service
Priority      = 50
Datacenters   = sandbox
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group                       Queued  Starting  Running  Failed  Complete  Lost  Unknown
<REDACTED>-errorwiz-app                 0       0         1        76      79        3     0
<REDACTED>-errorwiz-error-processor     0       0         1        1368    101       13    0
<REDACTED>-errorwiz-feedback-processor  0       0         1        683     86        2     0

Evaluations
ID        Priority  Triggered By   Status    Placement Failures
b1dbc514  50        node-update    complete  false
b143ae42  50        node-update    complete  false
a01e2464  50        node-drain     complete  false
81be2626  50        queued-allocs  complete  false
3c8a25d9  50        job-register   complete  true
7a8a3e3e  50        job-register   complete  false

Latest Deployment
ID          = d3eac3fa
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group                       Auto Revert  Desired  Placed  Healthy  Unhealthy  Progress Deadline
<REDACTED>-errorwiz-app                 true         1        1       1        0          2023-05-16T19:05:36Z
<REDACTED>-errorwiz-error-processor     false        1        1       1        0          2023-05-16T19:05:06Z
<REDACTED>-errorwiz-feedback-processor  false        1        1       1        0          2023-05-16T19:05:06Z

Allocations
ID        Node ID   Task Group                       Version  Desired  Status    Created     Modified
7ee6bf44  f86d622a  <REDACTED>-errorwiz-error-processor     25       run      running   31m48s ago  28m1s ago
ccd1b74e  07027457  <REDACTED>-errorwiz-error-processor     25       stop     lost      1h28m ago   29m38s ago
11ceaf27  05838614  <REDACTED>-errorwiz-feedback-processor  25       run      running   1h28m ago   1h27m ago
eecc963a  a12a8381  <REDACTED>-errorwiz-app                 25       run      running   1h28m ago   1h25m ago
7e8f7d81  0c46cd77  <REDACTED>-errorwiz-feedback-processor  23       stop     complete  7d3h ago    1h5m ago
```
In this case, the `errorwiz-app` task group was running 0 count and was not being replaced, and the job was stable/not reporting any issues. We had to trigger a change to the job config to get the task group to spawn a new alloc.

**Comment by djenriquez** [comment]
A screenshot from the dev who reported the issue to our internal team, as you'll see, only 2 allocations running: 
<img width="945" alt="Screen Shot 2023-05-16 at 1 25 26 PM" src="https://github.com/hashicorp/nomad/assets/4636740/a807ba3b-82da-4ed1-83e6-718ddc5294e9">

**Comment by tgross** [comment]
Wild! :grinning: So what's weird about that is the `nomad job status -evals :jobid` is showing that there _is_ an allocation of that `errorwiz-app` task group running:

```
Allocations
ID        Node ID   Task Group                       Version  Desired  Status    Created     Modified
...
eecc963a  a12a8381  <REDACTED>-errorwiz-app                 25       run      running   1h28m ago   1h25m ago
```

I think the next question I have is whether the tasks for allocation `eecc963a` are actually running on the client (like, literally shell in and look at Docker or whatever to double-check) and it's not getting reported correctly in the API that feeds that Recent Allocations view, or whether the tasks aren't running but for some reason it hasn't been recorded correctly on the server. The client logs from the node `a12a8381` for that allocation would also be really helpful to figure out what's going on.

**Comment by djenriquez** [comment]
> Wild! 😀 So what's weird about that is the `nomad job status -evals :jobid` is showing that there _is_ an allocation of that `errorwiz-app` task group running:
> 
> ```
> Allocations
> ID        Node ID   Task Group                       Version  Desired  Status    Created     Modified
> ...
> eecc963a  a12a8381  <REDACTED>-errorwiz-app                 25       run      running   1h28m ago   1h25m ago
> ```
> 
> I think the next question I have is whether the tasks for allocation `eecc963a` are actually running on the client (like, literally shell in and look at Docker or whatever to double-check) and it's not getting reported correctly in the API that feeds that Recent Allocations view, or whether the tasks aren't running but for some reason it hasn't been recorded correctly on the server. The client logs from the node `a12a8381` for that allocation would also be really helpful to figure out what's going on.

Ah sorry, my posts have caused confusion -- The `nomad job status -evals :jobid` was a command I ran _AFTER_ we corrected the bad state that the developer reported to us. The screenshot after that was what they sent over asking why "errorwiz-app" wasn't running and why Nomad wasn't doing anything about it.

So chronological order:
1. Dev finds issue and sends screenshot
2. We correct issue by trigger a job config change
3. I see the update on this issue w/ your request to run that command
4. I run the command and report the status

Sorry for the confusion!

**Comment by djenriquez** [comment]
Also, unfortunately we run highly dynamic infrastructure so the node that experienced this issue is no longer around for me to fetch the logs. However, the next time this does happen, I will be sure to run the `nomad job status -evals :jobid` command _AND_ scp over the logs.

**Comment by tgross** [comment]
Ok, we'll be eagerly awaiting more info (yet hoping it doesn't happen again for your sake :grinning: ). When you do that, it might also help to get a `nomad eval status :eval_id` of whatever the most recent eval for the job.

**Comment by djenriquez** [comment]
Hi @tgross, looks like we finally have one we caught:

```
$ nomad job status -evals namespace-redacted-infra
ID            = namespace-redacted-infra
Name          = namespace-redacted-infra
Submit Date   = 2023-07-10T10:48:54-07:00
Type          = service
Priority      = 50
Datacenters   = sandbox
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group                     Queued  Starting  Running  Failed  Complete  Lost  Unknown
namespace-redacted-infra-dynamodb  0       0         0        0       3         0     0
namespace-redacted-infra-firehose  0       0         0        0       3         0     0
namespace-redacted-infra-kinesis   0       0         0        0       4         0     0
namespace-redacted-infra-redis     0       0         0        0       3         0     0
namespace-redacted-infra-s3        0       0         1        0       1         1     0

Evaluations
ID        Priority  Triggered By   Status    Placement Failures
545fde78  50        queued-allocs  complete  false
31edd987  50        queued-allocs  complete  false

Allocations
ID        Node ID   Task Group                     Version  Desired  Status    Created     Modified
15476e1d  4a5cad19  namespace-redacted-infra-firehose  0        run      complete  19h35m ago  16m39s ago
4255ac97  4a5cad19  namespace-redacted-infra-kinesis   0        run      complete  19h35m ago  29m8s ago
565234c8  4a5cad19  namespace-redacted-infra-redis     0        run      complete  19h35m ago  24m17s ago
d0d5dd05  4a5cad19  namespace-redacted-infra-dynamodb  0        run      complete  19h35m ago  23m17s ago
f09aede9  6138c740  namespace-redacted-infra-s3        0        run      running   1d5h ago    1d5h ago
```

As your can see here there are 4 taskgroups that for some reason are just in the complete state, they should be running.

I'll try to keep this job in this state as long as I can (our infra is pretty dynamic), but as of now, its been in this weird state for ~half an hour. I'm confident stopping/starting or redeploying a new job version will correct the issue.

Any other commands I could run to help reveal whats going on here?

**Comment by tgross** [comment]
Sorry for the very long delay in getting back on this. I'm picking this issue up along with https://github.com/hashicorp/nomad/issues/20462 (which is effectively the same thing). Will report back in that issue as I know more.

**Comment by tgross** [comment]
Quick update on this. I've got a working patch at https://github.com/hashicorp/nomad/pull/12319, but there's a lingering issue described in https://github.com/hashicorp/nomad/issues/20462#issuecomment-2142738356 which may be interrelated and I want to make sure I've done my due diligence here before trying to close this out.

**Comment by tgross** [comment]
This issue should be resolved in https://github.com/hashicorp/nomad/pull/12319
