### ISSUE TITLE
deleting namespaces that are in use by allocs or volumes should error

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#17088]
When a namespace is deleted we check that the namespace has no jobs in a terminal state (ref [`namespace_endpoint.go#L194-L221`](https://github.com/hashicorp/nomad/blob/v1.5.4/nomad/namespace_endpoint.go#L194-L221)) but this isn't really enough to ensure data integrity. In practice, users need to hit the [List Allocations API](https://developer.hashicorp.com/nomad/api-docs/allocations#list-allocations) and [List Volumes API](https://developer.hashicorp.com/nomad/api-docs/volumes#list-volumes) and [List Variables API](https://developer.hashicorp.com/nomad/api-docs/variables#list-variables) to ensure that they don't have any lingering objects that reference the namespace. This is particularly painful for ENT users who have quotas that need to get decremented when we GC the allocation.

Namespaces are an important-enough "container" object and ACL scope that it makes sense to ensure that we never delete a namespace with references to it. Although this operation is probably slow, deleting namespaces is going to naturally be run much less frequently than job or allocation updates will happen.

**Comment by josegonzalez** [comment]
I would expect that deleting a namespace would either:

- delete everything in that namespace
- fail because _anything_ is associated with the namespace, with an error stating which objects are there

Either would be more than enough for my use case.
