### ISSUE TITLE
cgroup issue with systemd 226

### ISSUE THREAD

**Issue by apognu** [hashicorp/nomad#171]
Hi,

I'm not sure if this falls under nomad's scope, but it would appear, as referenced in docker/docker#16256, systemd version 226 introduces _init.scope_ into their cgroup FS, and it messes up quite a bit (nomad could not run containrs on my system).

I have not read anywhere what distros nomad means to support, so I assume recent systemd-based ones are part of it.

I understand this may not be nomad's fault and will probably be fixed upstream, but maybe the workaround could be mentionned somewhere in the docs?

Adding the following option to the Docker daemon fixed it for me:
```
--exec-opt native.cgroupdriver=cgroupfs
```

Regards,

**Comment by cbednarski** [comment]
> I have not read anywhere what distros nomad means to support, so I assume recent systemd-based ones are part of it.

I developed the docker integration on Ubuntu 15.04 (which uses `systemd`) but we do not currently support interaction with `systemd`.

We use docker as-is so if docker supports a particular systemd feature, Nomad will support it in that limited capacity. However, our isolation mechanisms for exec do not currently support systemd, so you may have strange compatibility problems if you run both types of workloads on a systemd system.

This is an issue we're aware of and will address but we don't have an immediate timeline for this.

**Comment by dadgar** [comment]
This should be fixed now. If it is still failing we can reopen.
