### ISSUE TITLE
Prefix matched multiple volumes

### ISSUE THREAD

**Issue by SunSparc** [hashicorp/nomad#17132]
### Nomad version
`client v1.5.5`
`server v1.5.3`

### Operating system and Environment details
`macOS Ventura 13.3.1 (a)`

### Issue
```
$ nomad volume status
Container Storage Interface
ID                       Name                     Plugin ID       Schedulable  Access Mode
test-volume              test-volume              cloud-provider  true         <none>
test-volume-development  test-volume-development  cloud-provider  true         single-node-writer
test-volume-production   test-volume-production   cloud-provider  true         single-node-writer

$ nomad volume deregister test-volume
Prefix matched multiple volumes

$ nomad volume detach test-volume fa7d1a0d-9e03-a85b-fd55-a9071c79632f
Prefix matched multiple volumes
```

### Reproduction steps
Create multiple volume, one of which is identified solely by characters which are identical to the "prefix" used on the others.

#### Expected Result
An ID should not be treated as a prefix. I expect to provide an ID and have Nomad recognize it as such.

#### Actual Result
Cannot deregister/detach/delete a volume that has an identifier that matches initial characters of another volume identifier.

#### Related Issues
- https://github.com/hashicorp/nomad/issues/12005
- https://github.com/hashicorp/nomad/issues/11846
- https://github.com/hashicorp/nomad/issues/11847

**Comment by tgross** [comment]
PR in progress here: https://github.com/hashicorp/nomad/pull/23502
