### ISSUE TITLE
windows tasks not starting after upgrade to 1.5.4

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#17131]
### Operating system and Environment details
Windows server 2022

### Issue
Job start fails with:

> Driver Failure | failed to launch command with executor: rpc error: code = Unknown desc = failed to create stdout: The parameter is incorrect.

### Reproduction steps
Simple `raw_exec` job without any special settings.

This is probably related https://github.com/hashicorp/nomad/pull/16962/files#diff-3319d35cf84f1373ae3ebeb8ba7d96d936205b7e4fa3489000949505e6aec0acR72-R73

**Comment by schmichael** [comment]
Please upgrade to Nomad 1.5.5. **Nomad 1.5.4 should not be used.** 1.5.4 contained a bug which implicitly disabled logs on allocations: #17087

That being said, the bug you ran into still exists on Nomad 1.5.5 if you explicitly disable logs with: `logs { disabled = true }`. I #17148 to track that issue.
