### ISSUE TITLE
logs.disabled = true does not work with raw_exec on Windows

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#17148]
Discovered due to #17131

### Nomad version

Nomad 1.5.5 amd64

### Operating system and Environment details

Windows 11 Enterprise
Version: 22H2
OS Build: 22621.1105

### Issue

Using `logs.disabled = true` with a `raw_exec` task on Windows prevents the task from starting with the following task event:

```
Driver Failure: failed to launch command with executor:
rpc error: code = Unknown
desc = failed to create stdout: The parameter is incorrect
```

### Reproduction steps

Short example job with:

```
task "redis" {
  driver = "raw_exec"
  logs { disabled = true }
  config {
    command = "powershell.exe"
    args = ["echo hello; sleep 9000"]
  }
}
```

#### Expected Result

Task runs with empty logs.

#### Actual Result

Task fails to start with driver failure above.

### Nomad Client logs (if appropriate)

Prior to the executor exiting it logs:

> client.driver_mgr.raw_exec.executor.stdio: received EOF, stopping recv loop: alloc_id=... driver=raw_exec task_name=redis err="rpc error: code = Unavailable desc = error reading from server: EOF"

Sorry I can't include full snippets. Trying to copy and paste out of my Windows VM to Chrome on my host causes Chrome to crash and lose all my edits. :disappointed:

**Comment by tgross** [comment]
I've got a draft PR up in https://github.com/hashicorp/nomad/pull/17199 that I think might fix this by using the `io.Discard` instead of the `NUL` device. I need to work up a test before I'll be ready to get that reviewed.
