### ISSUE TITLE
[feature] Allow downloading artifacts from Azure Blob Storage - Private Containers

### ISSUE THREAD

**Issue by mohitarora** [hashicorp/nomad#1716]
Allow Nomad to download artifacts from Azure Blob Storage private containers. 

S3 is already supported, this is a feature request to have same functionality for Azure Blob Storage.

**Comment by dadgar** [comment]
@mohitarora Can you create an issue against go-getter

**Comment by mohitarora** [comment]
Added - https://github.com/hashicorp/go-getter/issues/33
