### ISSUE TITLE
preserve newlines when showing Nomad variables in UI

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#17183]
### Proposal
Preserve the newlines when showing Nomad variables in UI.

How is it now:
![image](https://github.com/hashicorp/nomad/assets/15679217/3bd9bbde-f10f-4d69-adcb-3d7864c33ed5)
![image](https://github.com/hashicorp/nomad/assets/15679217/f89db54b-052c-442f-880a-5b2665999551)

How could it be:
![image](https://github.com/hashicorp/nomad/assets/15679217/28372f4c-8ba5-45b9-8581-fa47b60392f7)

### Use-cases
The use case is any variable that has newlines.

### Attempted Solutions
The attempted solution is to use openstyles chome extension and add a custom style with `code { white-space: pre-wrap; word-wrap: break-word; }`.

Thank you!

**Comment by tgross** [comment]
Hi @Kamilcuk! In the JSON view we'll want to preserve the escaped newlines because otherwise it's not valid JSON. Maybe we could probably unescape the newlines and wrap them in `<p>` or something in the table view? I'll mark this issue so our UI experts see it.

**Comment by Kamilcuk** [comment]
The JSON view is fine. The non-JSON view does not show newlines. It shows one long line.

**Comment by philrenaud** [comment]
Hi @Kamilcuk — we made a fix for this in #17343; it should be released in an upcoming version of Nomad. Thanks for raising it!
