### ISSUE TITLE
Support for AWS AutoScale

### ISSUE THREAD

**Issue by Eyjafjallajokull** [hashicorp/nomad#172]
Hi, just a quick question, because I didn't found info: does Nomad supports Amazon AutoScale?

**Comment by ryanuber** [comment]
@Eyjafjallajokull Nomad doesn't directly interact with AWS in any way currently. However, if you have an AMI with Nomad installed, new client nodes could easily be deployed based on your ASG configuration and join in to an existing Nomad cluster to increase your cluster capacity.
