### ISSUE TITLE
Nomad 0.4.1 not building: GNUmakefile:17: recipe for target 'dev' failed

### ISSUE THREAD

**Issue by Fluxxo** [hashicorp/nomad#1721]
Hi, 

my nomad build 0.4.1 won't build (e.g. make dev). Master builds without a problem.

### Nomad version
v0.4.1

### Operating system and Environment details
Ubuntu 16, golang 1.7

### Issue
Make dev results in: 
--> Running go fmt
--> Running go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/nomad-test

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/nomad/nomad/structs
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:118: undefined: DeriveVaultTokenRequest
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:121: undefined: VaultAccessorsRequest
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:124: undefined: VaultAccessor
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:127: undefined: DeriveVaultTokenResponse
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:274: undefined: LocalDisk
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:277: undefined: Vault

GNUmakefile:17: recipe for target 'dev' failed
make: *** [dev] Error 1

### Reproduction steps
git clone https://github.com/hashicorp/nomad.git
cd nomad
git checkout -b v0.4.1-fix v0.4.1
>> Zu neuem Branch 'v0.4.1-enh' gewechselt (German, meaning: Changed to branch...)
make bootstrap
>>Installing github.com/kardianos/govendor
>>Installing github.com/mitchellh/gox
>>Installing golang.org/x/tools/cmd/cover
>>Installing github.com/axw/gocov/gocov
>>Installing gopkg.in/matm/v1/gocov-html
>>Installing github.com/ugorji/go/codec/codecgen

make dev

--> Running go fmt
--> Running go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/nomad-test

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/nomad/nomad/structs
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:118: undefined: DeriveVaultTokenRequest
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:121: undefined: VaultAccessorsRequest
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:124: undefined: VaultAccessor
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:127: undefined: DeriveVaultTokenResponse
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:274: undefined: LocalDisk
../nomad/nomad/structs/codecgen-pkg-8040.generated.go:277: undefined: Vault

GNUmakefile:17: recipe for target 'dev' failed
make: *** [dev] Error 1

Anyine knows how to fix this? I'm pretty new to go and fixed stuff in master, now want to merge these changed to 0.4.1.

Thanks

**Comment by dadgar** [comment]
Remove any generated files from `nomad/nomad/structs/`. You may have killed a build that left bad generated files (the `make generate` step)

**Comment by dadgar** [comment]
We can re-open if my suggestion didn't fix it
