### ISSUE TITLE
detecting allocation pending status while stuck on template rendering

### ISSUE THREAD

**Issue by mhehle** [hashicorp/nomad#17220]
### Nomad version
Nomad v1.5.5
BuildDate 2023-05-05T12:50:14Z
Revision 3d63bc62b35cbe3f79cdd245d50b61f130ee1a79

### Operating system and Environment details
Linux 6.1.25-1-MANJARO

### Issue
Jobs that reference a non-existent nomad variable, result in a permanent `pending` status.
This is okay so far, the only problem is that this state cannot be clearly identified as a "temporary" scheduling error via the API.

The only hint to the problem is the `DisplayMessage` of the TaskState events of an allocation
`Allocation.TaskStates.{taskName}.Events.[].DisplayMessage`

```json
{
  "Type": "Template",
  "Time": 1684323333593466146,
  "Message": "",
  "DisplayMessage": "Missing: nomad.var.block(notExisting@default.global)",
  "Details": {},
  "FailsTask": false,
  "RestartReason": "",
  "SetupError": "",
  "DriverError": "",
  "ExitCode": 0,
  "Signal": 0,
  "KillTimeout": 0,
  "KillError": "",
  "KillReason": "",
  "StartDelay": 0,
  "DownloadError": "",
  "ValidationError": "",
  "DiskLimit": 0,
  "FailedSibling": "",
  "VaultError": "",
  "TaskSignalReason": "",
  "TaskSignal": "",
  "DriverMessage": "",
  "GenericSource": ""
}
```

### Reproduction steps

1. run the job below 
2. get allocation for the job
`curl http://localhost:4646/v1/job/non-existend-var-example/allocations  `

### Job file (if appropriate)
```hcl
job "non-existend-var-example" {
  type        = "batch"
  datacenters = ["*"]

  group "default" {

    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 0
      mode     = "fail"
    }

    task "main" {
      driver = "docker"
      
      config {
        image   = "alpine:latest"
        command = "sh"
        args = [
          "-c",
          "exit 0"
        ]
      }

      template {
        data = "{{- with nomadVar \"notExisting\" }}{{ . | toJSON}}{{- end }}"
        destination = "local/var.json"
      }
    }
  }
}
```

**Comment by tgross** [comment]
I think this one has been answered, so I'm going to close this issue out.
