### ISSUE TITLE
Reserved ports are listed one by one in node info

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/nomad#1726]
### Nomad version
v0.4.0

### Operating system and Environment details
All

### Issue
When a large range of ports reserved in client configuration of Nomad, `v1/nodes` output becomes extraordinary large. Each port is specified rather than range in json output. Example:

```
"ReservedPorts": [
	{
		"Label": "",
		"Value": 0
	},
	{
		"Label": "",
		"Value": 1
	},
	{
		"Label": "",
		"Value": 2
	},
	{
		"Label": "",
		"Value": 3
	},
	{
		"Label": "",
		"Value": 4
	},
	{
		"Label": "",
		"Value": 5
	},
    ...
```

### Client Configuration
```
"client": {
  "enabled": True,
  "options": {
      "driver.raw_exec.enable": "1"
  },
  "reserved": {
      "reserved_ports": ""0-19999,30000-39999"
  }
}
```

**Comment by dadgar** [comment]
The client configuration is being converted to that. That struct is an internal representation as well.
