### ISSUE TITLE
☂️ Node Pools UI

### ISSUE THREAD

**Issue by ChaiWithJai** [hashicorp/nomad#17286]
### Views
- [ ] #17287
- [ ] #17288
- [ ] #17289
- [ ] #17291
- [ ] #17290

### Abstractions
- [x] #17292
- [ ] #17293
- [ ] #17294
- [ ] #17295

**Comment by ChaiWithJai** [comment]
@lgfa29 what will I need to consider for backwards compatibility here? I'm imagining that older versions of Nomad will not have the Node Pools. But, I'm a little confused because on one hand, the Nomad UI is bound to a specific version of Nomad. But we also have backports.

Should I rely on tagging my PRs in a particular fashion to prevent these commits from being backported?

cc:  @philrenaud

**Comment by philrenaud** [comment]
@ChaiWithJai you'll want to avoid using specific backport labels, but otherwise you're free to base off `main` with no other changes (presuming this feature is intended to go out in the next major release). No changes necessary to avoid backports, they're opt-in.

**Comment by lgfa29** [comment]
Done in https://github.com/hashicorp/nomad/pull/17301
