### ISSUE TITLE
Specify envvars for docker driver

### ISSUE THREAD

**Issue by apognu** [hashicorp/nomad#173]
Is there any way to specify environment variables to be sent with the creation of a Docker container? According to [the doc](https://www.nomadproject.io/docs/drivers/docker.html), it's not.

I know I can add items to the _meta_ specification directive, and it will, as a result, add envvar to my running container, unfortunately those are prefixed with _NOMAD_META__, and developing my application to use those does not seem very agnostic.

Any plans to add an option to specify those?

Regards,

**Comment by dimfeld** [comment]
If you need this right away, a quick-and-dirty solution would be to change `SetMeta` in /client/driver/environment/vars.go to not add the prefix. That said, official support for this would be great.

**Comment by dimfeld** [comment]
@hashicorp-team Not sure if this is on your roadmap but I'd be glad to work on it in my free time over the next few weeks and submit a PR. Seems like it's just a matter of adding another map to the Task structure (named `env` or `environment`, perhaps?) and associated code for parsing from HCL and applying the settings. Any thoughts?

**Comment by apognu** [comment]
I was starting to read the code to do exactly that myself.

**Comment by dimfeld** [comment]
Feel free to take it on if you'd like, but either way is fine with me so long as we don't do duplicate work :)

**Comment by apognu** [comment]
Yeah, almost got something ready to PR, should be ready tonight or tomorrow morning.

**Comment by dimfeld** [comment]
:+1: Cool, sounds great!

**Comment by rvm2015** [comment]
+1 This is critical for pretty much any 12 factor app
