### ISSUE TITLE
Shared volume without enabling voulme in docker driver

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#17304]
### Proposal

Easy way to share  /alloc/data dir.

Similar issue like https://github.com/hashicorp/nomad/issues/9901

### Use-cases

Deployments which needs share a folder for some tasks in the same group (  jenkins setup for example ) can share a folder with following approach :

1. CSI volume 
2. Host volume
3. Enable docker docker volume

Option 1:
Is not an option for some deployment which needs disk perfomance or some teams have not the capacity to maintain a csi driver.

Options 2:
Needs a noma restart and an administor with access to the host machine

Option 3:
This can mount any host path to the container. I think no one want to have this in production environment. Correct me please if I am wrong.  I can't define I root mount dir in volume section of docker driver. 

### Attempted Solutions

The job file below works for my usecase. I don't have enabled the docker volume. 

But the mount path  `../${NOMAD_ALLOC_DIR}/data` looks weird. The env var is resolved to  `/alloc` and nomad resolves every volume wich starts with no / relative to the tasks' alloc dir. And thus ../alloc/data works as I understand. 

A well defined volume or env var for that purpose can be very handy. 

<details>
  <summary>Job file with shared alloc dir without docker volume enabled</summary>
  
  ```hcl
job "sharedVolume" {

  group "grp" {
    #    ephemeral_disk {
    #      migrate = true
    #      size    = 500
    #      sticky  = true
    #    }
    task "a" {
      driver = "docker"

      config {
        image   = "busybox:1.36.1"
        command = "/bin/sh"
        args    = ["-c", "sleep 300"]
        #        volumes = ["../${NOMAD_ALLOC_DIR}/data:/shared/srv"]
        mount {
          type     = "bind"
          source   = "../${NOMAD_ALLOC_DIR}/data"
          target   = "/shared/srv"
          readonly = false
        }
      }

    }

    task "b" {
      driver = "docker"

      config {
        image   = "busybox:1.36.1"
        command = "/bin/sh"
        args    = ["-c", "sleep 300"]
        #        volumes = ["../${NOMAD_ALLOC_DIR}/data:/shared/srv"]
        mount {
          type     = "bind"
          source   = "../${NOMAD_ALLOC_DIR}/data"
          target   = "/shared/srv"
          readonly = false
        }
      }
    }
  }
}
  ```
</details>

**Comment by lgfa29** [comment]
Hi @suikast42 👋 

I don't quite follow the problem here. The allocation directory should already be shared between tasks. For example, here's a sample job that works without having to enable volumes in the Docker task driver config:

```hcl
job "example" {
  group "shared" {
    task "read" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/ash"
        args    = ["${NOMAD_TASK_DIR}/script.sh"]
      }

      template {
        data        = <<EOF
while true; do
  tail -n1 ${NOMAD_ALLOC_DIR}/shared.txt
  sleep 3
done
EOF
        destination = "${NOMAD_TASK_DIR}/script.sh"
      }
    }

    task "write" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/ash"
        args    = ["${NOMAD_TASK_DIR}/script.sh"]
      }

      template {
        data        = <<EOF
while true; do
  echo $(date) >> ${NOMAD_ALLOC_DIR}/shared.txt
  sleep 3
done
EOF
        destination = "${NOMAD_TASK_DIR}/script.sh"
      }
    }
  }
}
```

Is a job like this not working for you?

**Comment by lgfa29** [comment]
Hello from the future 👋 

I cleaning up some stale issue and we haven't had any updates on this one for a while, so I'm going to close it for now. But let me know if this is still a problem and we can reopen it.

Thank you!
