### ISSUE TITLE
graceful restart of non-leader server agent makes active job evaluation segfault

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#17329]
### Nomad version
1.5.6

### Operating system and Environment details
amazonlinux:2

### Issue
A gracefull restart of nomad server during deployment fails the deployment/evaluation. This seems like something nomad is supposed to be resilient against?

In my case I noticed it happening when a non-leader failed.  I tested on the leader as well and the same thing happens

### Reproduction steps
restart/reschedule a job
```
$ nomad job restart -reschedule phonetrac_resque
```

While thats doing it's thing, find a non-leader server and:
```
$sudo systemctl restart nomad
```

#### Expected Result
`nomad job run` would keep working?

#### Actual Result
`nomad job run` does not keep working

### Nomad Server logs (if appropriate)
This error popped up in the leader:
```
May 25 21:13:35 ip-10-20-21-12 nomad: 2023-05-25T21:13:35.561Z [ERROR] nomad.raft: failed to appendEntries to: peer="{Nonvoter 66642905-0f42-910f-a356-13350aaef6d0 10.20.11.253:4647}" error=EOF
```

### Nomad Client logs (if appropriate)

```
==> 2023-05-25T21:13:12Z: Restarting 6 allocations
    2023-05-25T21:13:12Z: Rescheduling allocation "cb67e36b" for group "scheduler"
    2023-05-25T21:13:12Z: Allocation "cb67e36b" replaced by "831b16e2", waiting for "831b16e2" to start running
    2023-05-25T21:13:28Z: Allocation "831b16e2" is "running"
    2023-05-25T21:13:28Z: Rescheduling allocation "28b10d02" for group "scheduler"
    2023-05-25T21:13:28Z: Allocation "28b10d02" replaced by "de204fe4", waiting for "de204fe4" to start running
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x240872a]

goroutine 50 [running]:
github.com/hashicorp/nomad/command.(*JobRestartCommand).monitorReplacementAlloc(0xc000aa4280, {0x34e31d8, 0xc0003bb040}, {0xc000251080?, 0xc0009a3860?}, 0x0?)
        github.com/hashicorp/nomad/command/job_restart.go:1045 +0x60a
created by github.com/hashicorp/nomad/command.(*JobRestartCommand).stopAlloc
        github.com/hashicorp/nomad/command/job_restart.go:951 +0x51c
```

**Comment by lgfa29** [comment]
Hi @josh-m-sharpe 👋 

Thanks for the report. Just to confirm, does the crash only happens in the CLI or does it cause the nomad servers to crash as well? And if that's the case, would you be able to provide the logs from the server that crashed?

If the problem only happens in the CLI I've opened https://github.com/hashicorp/nomad/pull/17346 to fix this.

Thanks!

**Comment by josh-m-sharpe** [comment]
Pretty sure it was just the CLI `restart -reschedule` execution that died.  I'm not 100% sure but I think it left the task/job in a questionable state - as in I don't think it continued on successfully.

The nomad leader stayed online and waited for the non-leader to restart which successfully rejoined the cluster.

**Comment by lgfa29** [comment]
>  I'm not 100% sure but I think it left the task/job in a questionable state - as in I don't think it continued on successfully.

Were you setting any `-batch-size` value? If the crashed happened between batches than, yes, I would expect the following batches to not have been triggered.

This was a compromised we made in https://github.com/hashicorp/nomad/pull/16278 to implement a stateless restart to get something out sooner than a stateful restart that would be able to handle these kind of problems but turned out to be way more complex to implement.
