### ISSUE TITLE
nomad alloc exec proxy

### ISSUE THREAD

**Issue by tyliec** [hashicorp/nomad#17331]
### Nomad version
Output from `nomad version`

```Nomad v1.1.6 (b83d623fb5ff475d5e40df21e9e7a61834071078)```

### Operating system and Environment details

N/A

### Issue

`nomad alloc exec --address` honors the `http_proxy`/`https_proxy` environment variables.

### Reproduction steps

Temporarily set the `http_proxy` environment variables:

```
export http_proxy="https://localhost.nip.io"
```

Run a `nomad alloc exec --address` command and observe it attempting to use the proxy.

#### Expected Result

A way to avoid using the proxy (i.e. `no_proxy`, or some sort of `--noproxy` flag).

**Comment by lgfa29** [comment]
Hi @tyliec 👋 

I don't quite understand the problem here, are you observing that `nomad alloc exec` command is reading these environment variables?

While somewhat common, as far as I can tell the `nomad` CLI has never read them. Do you happen to have anything else in your toolchain that is affecting this?

**Comment by tyliec** [comment]
> Hi @tyliec 👋
> 
> I don't quite understand the problem here, are you observing that `nomad alloc exec` command is reading these environment variables?
> 
> While somewhat common, as far as I can tell the `nomad` CLI has never read them. Do you happen to have anything else in your toolchain that is affecting this?

Yep, the hypothesis is that `nomad alloc exec` makes an API call to the allocations endpoint
https://github.com/hashicorp/nomad/blob/b74712321b28a0defce9886b47590e691efa7a12/api/allocations.go#L59

https://github.com/golang/go/blob/2882786bf4cd779f166e9ced82a4da2ea0f8b1f9/src/net/http/transport.go#L38-L42

This uses Go's `http` standard lib to make the call, and it reads the `http_proxy` env var

**Comment by Kamilcuk** [comment]
This behavior is expected for me. Setting environment variables is the way to set the proxy, and if my nomad server is available via proxy, I will set it with env variables.

If you do not want `.nio.io` to be forwarded with proxy, then _you_ should `export NO_PROXY=nio.io`.

**Comment by lgfa29** [comment]
I would agree with @Kamilcuk here. `HTTP_PROXY` and `NO_PROXY` (and their lowercase counter-parts) have become rather common in other tools, and it's part of the standard library for Go and other languages.

`NO_PROXY` should do what you requested, so I am going to close this one for now, but let us know if you have any other thoughts!
