### ISSUE TITLE
Cannot customize nomad web ui path using nginx reverse proxy

### ISSUE THREAD

**Issue by krishnaprateek6** [hashicorp/nomad#17330]
### Proposal

Need to allow the ability to customize the nomad's web ui path like its enabled in consul. please refer the below url

https://developer.hashicorp.com/consul/docs/agent/config/config-files#ui_config_content_path
### Use-cases

We are using path based routing while vault & consul support it for example http://<url>/ui/vault or http://<url>/ui/consul can we please get the same feature in nomad as well.

**Comment by krishnaprateek6** [comment]
https://github.com/hashicorp/nomad/issues/6410 This issue was opened 3 years ago

**Comment by krishnaprateek6** [comment]
upstream nomad {
    hash $cookie_jsessionid;
    server localhost:4646 weight=50;
  }
  server {
    listen 443;
    ssl on;
    ssl_certificate /config/certs/public.pem;
    ssl_certificate_key /config/certs/private.key;
    location /ui/nomad {
        rewrite /ui/(.*) /$1 break;
        proxy_redirect ~^(http).?(://[^:]+):?\d*/(?!ui)(.*) /ui/$3;
        proxy_redirect ~^/(?!ui)(.*) /ui/$1;

        proxy_pass          http://127.0.0.1:4646;
    }
  }

**Comment by lgfa29** [comment]
Hi @krishnaprateek6 👋 

This issue has been reported in https://github.com/hashicorp/nomad/issues/6413, and I see that you're participating there as well, so I'm going to closet this one as duplicate.

Feel free to 👍 that issue to help us adjust our roadmap.
