### ISSUE TITLE
Sort values fields when editing a variable through the UI

### ISSUE THREAD

**Issue by TrueBrain** [hashicorp/nomad#17336]
### Nomad version
```
Nomad v1.5.5
BuildDate 2023-05-05T12:50:14Z
Revision 3d63bc62b35cbe3f79cdd245d50b61f130ee1a79
```

### Operating system and Environment details
Linux

### Issue
When looking at Nomad Variables, they are in alphabetical order.
But when you press Edit, they are in a seemingly random order.

To make matters a bit worse, every time you hit Save, the order can change.

Needless to say, I might or might not have edited the wrong variables a few times already :D

### Reproduction steps

- Add some variables to a single key.
- Enjoy an alphabetical view when viewing.
- Edit them. Sometimes it still is alphabetical .. but just hit Save a few times and go back.
- Be a bit confused when editing, as the order is already rather unpredictable.

#### Expected Result

I guess the best option would be to have both view alphabetical.

#### Actual Result

![image](https://github.com/hashicorp/nomad/assets/1663690/766f16cc-2b26-40df-a024-9050b4b2da02)
![image](https://github.com/hashicorp/nomad/assets/1663690/54e2826b-4b3c-4f8d-90ab-29a6c612dbb2)

(when looking at the JSON, it is also visible the order has changed; so by the looks, editing always follows the order as in the JSON, where viewing sorts it).

**Comment by lgfa29** [comment]
Thanks for the report @TrueBrain.

I'm guessing this behaviour stems from Go's randomized map key iteration, but the UI should be able to sort them client-side to keep them consistent.

I added this to our roadmap and edited the title a bit to better reflect the request.

Thanks again for the report!

**Comment by philrenaud** [comment]
This was fixed in https://github.com/hashicorp/nomad/pull/18051 — thanks for raising the issue, @TrueBrain !
