### ISSUE TITLE
progress_deadline set to 0 fails to validate

### ISSUE THREAD

**Issue by gorset** [hashicorp/nomad#17335]
Nomad 1.5.6 with #16761 introduces a check for kill_timeout, but fails to consider progress_deadline set to 0.

It fails with

```
Job validation errors:
1 error occurred:
	* Task group some-group validation failed: 1 error occurred:
	* Task some-task has a kill timout (5s) longer than the group's progress deadline (0s)
```

We don't have a kill timeout set, so 5s is the default.

As per documentation, progress_deadline set to 0 has special meaning:

> If the progress_deadline is set to 0, the first allocation to be marked as unhealthy causes the deployment to fail. 

We now have jobs that fails to validate/deploy. Is this a bug, or is progress_deadline set to 0 no longer supported?

**Comment by lgfa29** [comment]
Thanks for the report @gorset.

Unfortunately this is an unexpected regression and I have opened #17342 to fix it. Since this validation is performed at the servers, I can't think of a good workaround for this problem....apologies for the problems it caused.

**Comment by gorset** [comment]
Thank you @lgfa29. Looks good after upgrading to 1.6.1.

**Comment by lgfa29** [comment]
> Is there any chance of a release 1.3.16 that includes this fix...? 🤞

Hi @martinmcnulty 👋 

Normally we wouldn't, as we usually only release n-2 versions and, with 1.6.0 released, the 1.3.x line is deprecated. But the team agrees that this is a particularly bad bug to have around so we'll release a 1.3.16 just with this bug fix.

If all goes well it will be available by end of day today.

**Comment by lgfa29** [comment]
@martinmcnulty v1.3.16 with the fix is now available
https://releases.hashicorp.com/nomad/1.3.16

**Comment by martinmcnulty** [comment]
Many thanks!
