### ISSUE TITLE
Missing apt package for Ubuntu Lunar

### ISSUE THREAD

**Issue by andreafdaf** [hashicorp/nomad#17347]
### Nomad version
any

### Operating system and Environment details
```console
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
$ dpkg --print-architecture
amd64
```

### Issue
No apt package for lunar

### Reproduction steps
Install steps found here: https://developer.hashicorp.com/nomad/docs/install
```console
$ wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
...
$ echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
...
$ sudo apt-get update && sudo apt-get install nomad
Hit:1 https://apt.releases.hashicorp.com lunar InRelease
...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done

No apt package "nomad", but there is a snap with that name.
Try "snap install nomad"

E: Unable to locate package nomad
```

```console
$ sudo apt list nomad
Listing... Done
$ sudo apt list vagrant
Listing... Done
vagrant/lunar,lunar 2.3.4+dfsg-1ubuntu1 all
```

Using `kinetic` everything is fine

#### Expected Result
The package should be there

#### Actual Result
The package isn't there

**Comment by lgfa29** [comment]
Thanks for the report @andreafdaf. I can confirm that I'm not seeing it either. Strangely I can see the package on `arm64`, so there may be something wrong with the APT server. I have asked the team responsible for managing that to take a look and I will keep you updated.

**Comment by lgfa29** [comment]
Packages should be available now, would you mind trying it again?

```console
$ apt list nomad
Listing... Done
nomad/lunar 1.5.6-1 amd64
N: There are 118 additional versions. Please use the '-a' switch to see them.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
```

**Comment by andreafdaf** [comment]
Now I can see it too. Amazing job 🔝

**Comment by lgfa29** [comment]
Great! Thank you for confirming it has been fixed. I'm going to close this issue as complete, but feel free to reach out if you have any other problem 🙂
