### ISSUE TITLE
error occurred while running modprobe args: [ceph]

### ISSUE THREAD

**Issue by clumbo** [hashicorp/nomad#17392]
### Nomad version

1.5.6

### Operating system and Environment details

Proxmox
### Issue
I have a nomad client running in a proxmox LXC container and when trying to run the ceph-csi plugin I can create a controller, nodes and a volume however when trying to mount the volume in a docker container I get the following error

`failed to setup alloc: pre-run hook "csi_hook" failed: node plugin returned an internal error, check the plugin allocation logs for more information: rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]`

#### Expected Result

Mount the volume
#### Actual Result

Doesn't mount the volume

**Comment by tgross** [comment]
@clumbo the log message is saying the CSI plugin itself returned an error and to check the node plugin allocation logs. Can you check the node plugin's allocation logs (you may need to check both stdout and stderr, depending on the plugin) and report back with those?

**Comment by clumbo** [comment]
Thanks @tgross  this is the most relevant thing I can find, I'm still getting up and running with nomad so please forgive my lack of knowledge.

its worth noting I am running in a privileged container and I created the volume with `nomad volume create traefik_data`

```
I0602 11:58:36.737710       1 utils.go:195] ID: 59 GRPC call: /csi.v1.Identity/Probe
I0602 11:58:36.737740       1 utils.go:206] ID: 59 GRPC request: {}
I0602 11:58:36.737753       1 utils.go:212] ID: 59 GRPC response: {}
I0602 11:58:36.739020       1 utils.go:195] ID: 60 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0602 11:58:36.739044       1 utils.go:206] ID: 60 GRPC request: {}
I0602 11:58:36.739095       1 utils.go:212] ID: 60 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":5}}}]}
I0602 11:58:36.765284       1 utils.go:195] ID: 61 GRPC call: /csi.v1.Identity/Probe
I0602 11:58:36.765312       1 utils.go:206] ID: 61 GRPC request: {}
I0602 11:58:36.765325       1 utils.go:212] ID: 61 GRPC response: {}
I0602 11:59:02.652239       1 utils.go:195] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC call: /csi.v1.Node/NodeStageVolume
I0602 11:59:02.652333       1 utils.go:206] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC request: {"secrets":"***stripped***","staging_target_path":"/local/csi/staging/traefik_data/rw-file-system-multi-node-multi-writer","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_context":{"clusterID":"20ea907e-f6a8-49fe-b528-95cae7eaf802","fsName":"nomad","imageFeatures":"layering","pool":"nomad-data","subvolumeName":"csi-vol-bff50437-b90c-433d-9b65-b5cb07b4106e","subvolumePath":"/volumes/csi/csi-vol-bff50437-b90c-433d-9b65-b5cb07b4106e/98d2bc6a-2499-4875-abac-5d02980060d1"},"volume_id":"0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e"}
I0602 11:59:02.655455       1 omap.go:88] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e got omap values: (pool="nomad-metadata", namespace="csi", name="csi.volume.bff50437-b90c-433d-9b65-b5cb07b4106e"): map[csi.imagename:csi-vol-bff50437-b90c-433d-9b65-b5cb07b4106e csi.volname:traefik_data]
I0602 11:59:02.728700       1 volumemounter.go:126] requested mounter: , chosen mounter: kernel
I0602 11:59:02.728745       1 nodeserver.go:293] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e cephfs: mounting volume 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e with Ceph kernel client
I0602 11:59:02.729912       1 cephcmds.go:98] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e an error (exit status 1) occurred while running modprobe args: [ceph]
E0602 11:59:02.729925       1 nodeserver.go:319] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e failed to mount volume 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e: an error (exit status 1) occurred while running modprobe args: [ceph] Check dmesg logs if required.
E0602 11:59:02.729946       1 utils.go:210] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC error: rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]
I0602 11:59:03.141220       1 utils.go:195] ID: 63 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0602 11:59:03.141264       1 utils.go:206] ID: 63 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC request: {"target_path":"/local/csi/per-alloc/7d54d131-2ac4-d031-47fc-14d1ad4e2326/traefik_data/rw-file-system-multi-node-multi-writer","volume_id":"0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e"}
E0602 11:59:03.141284       1 nodeserver.go:543] ID: 63 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e stat failed: stat /local/csi/per-alloc/7d54d131-2ac4-d031-47fc-14d1ad4e2326/traefik_data/rw-file-system-multi-node-multi-writer: no such file or directory
I0602 11:59:03.141289       1 nodeserver.go:547] ID: 63 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e targetPath: /local/csi/per-alloc/7d54d131-2ac4-d031-47fc-14d1ad4e2326/traefik_data/rw-file-system-multi-node-multi-writer has already been deleted
I0602 11:59:03.141299       1 utils.go:212] ID: 63 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC response: {}
I0602 11:59:03.141800       1 utils.go:195] ID: 64 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC call: /csi.v1.Node/NodeUnstageVolume
I0602 11:59:03.141832       1 utils.go:206] ID: 64 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC request: {"staging_target_path":"/local/csi/staging/traefik_data/rw-file-system-multi-node-multi-writer","volume_id":"0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e"}
I0602 11:59:03.141866       1 utils.go:212] ID: 64 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC response: {}
I0602 11:59:06.739597       1 utils.go:195] ID: 65 GRPC call: /csi.v1.Identity/Probe
I0602 11:59:06.739627       1 utils.go:206] ID: 65 GRPC request: {}
I0602 11:59:06.739640       1 utils.go:212] ID: 65 GRPC response: {}
I0602 11:59:06.740081       1 utils.go:195] ID: 66 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0602 11:59:06.740102       1 utils.go:206] ID: 66 GRPC request: {}
I0602 11:59:06.740156       1 utils.go:212] ID: 66 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":5}}}]}
I0602 11:59:06.766363       1 utils.go:195] ID: 67 GRPC call: /csi.v1.Identity/Probe
I0602 11:59:06.766392       1 utils.go:206] ID: 67 GRPC request: {}
I0602 11:59:06.766405       1 utils.go:212] ID: 67 GRPC response: {}
I0602 11:59:36.741450       1 utils.go:195] ID: 68 GRPC call: /csi.v1.Identity/Probe
I0602 11:59:36.741483       1 utils.go:206] ID: 68 GRPC request: {}
I0602 11:59:36.741496       1 utils.go:212] ID: 68 GRPC response: {}
I0602 11:59:36.741704       1 utils.go:195] ID: 69 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0602 11:59:36.741728       1 utils.go:206] ID: 69 GRPC request: {}
I0602 11:59:36.741780       1 utils.go:212] ID: 69 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":5}}}]}
I0602 11:59:36.767232       1 utils.go:195] ID: 70 GRPC call: /csi.v1.Identity/Probe
```

**Comment by tgross** [comment]
Ok, here's are relevant log entries:

> E0602 11:59:02.729925       1 nodeserver.go:319] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e failed to mount volume 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e: an error (exit status 1) occurred while running modprobe args: [ceph] Check dmesg logs if required.
> E0602 11:59:02.729946       1 utils.go:210] ID: 62 Req-ID: 0001-0024-20ea907e-f6a8-49fe-b528-95cae7eaf802-0000000000000003-bff50437-b90c-433d-9b65-b5cb07b4106e GRPC error: rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]

This is ultimately a Ceph plugin error. I'm not a Ceph expert but if I recall correctly there's a `rbd` kernel module you need to have enabled to use Ceph RBD?

**Comment by clumbo** [comment]
So on the host I have them loaded.

I am using the plugin in cephfs mode(ceph module) but rbd looks as though its loaded as well

```
ceph                  524288  1
libceph               507904  2 ceph,rbd
```

Is the container saying it can't find it or is it saying its missing? I guess I'm in need of suggestions for better debugging strategies

**Comment by tgross** [comment]
Keeping in mind that running Nomad clients inside a container is living life on unreasonably hard mode (and very much discouraged). And having the plugin running as a privileged container probably doesn't help if you're running nested containers like this, if the LXC container itself hasn't been given access to most of the host's devices, root filesystem, etc.

Given those caveats, you'll want to dial down into which layer is having the problem:
* The log message says to "check dmesg logs if required". Is there anything there?
* Can you modprobe the module from inside the LXC container at all?
* If not, is the module a loadable in ` /lib/modules/$(uname -r)` and not mounted to the LXC container?
* If so, then try to `nomad alloc exec` into the plugin container and modprobe from there to see if it's something about what the Ceph plugin is doing specifically (and at that point, I'd open an issue upstream if you can otherwise modprobe the module).

**Comment by bazaah** [comment]
This is just my experience, as I also run Nomad in LXD, with Ceph CSI. You cannot run CSI inside LXD _containers_, even privileged ones. There may be some arcane `lxc.raw` overrides you can pass to achieve it, but it _definitely_ doesn't work with any combination of `security.*` config options.

You have to:

1. Use LXD VMs
2. Run Nomad as root inside the VM
3. Manually load the `rbd` and `ceph` modules (e.x via [/etc/modules-load.d](https://www.man7.org/linux/man-pages/man5/modules-load.d.5.html) as it appears even privileged containers cannot load modules themselves.

You can _kinda_ run a Nomad client in a privileged LXD container, but you will hit lots of weird ungoogle-able errors.

**Comment by clumbo** [comment]
Thanks for the help everyone, everything is much clearer now.

**Comment by tgross** [comment]
Thanks for the assist @bazaah. I'm going to close this issue out.
