### ISSUE TITLE
Nomad client fails to start a job

### ISSUE THREAD

**Issue by akamensky** [hashicorp/nomad#17448]
### Nomad version
```
Installed from official RPM repo

Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Operating system and Environment details
```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

$ uname -a
Linux hostname.redacted 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-3.10.0-123.20.1.el7.x86_64 root=/dev/mapper/VolGroup-lv_root ro nomodeset rd_NO_PLYMOUTH rd.lvm.lv=VolGroup/lv_swap vconsole.keymap=us plymouth.enable=0 rd.lvm.lv=VolGroup/lv_root crashkernel=auto vconsole.font=latarcyrheb-sun16 rhgb quiet LANG=en_US.UTF-8 rcu_nocbs=1,3 nohz_full=1,3 intel_pstate=disable

$ cat /etc/nomad.d/nomad.json 
{
  "data_dir": "/data/nomad",
  "bind_addr": "0.0.0.0",
  "datacenter": "perf",
  "region": "hk",
  "server": {
    "enabled": false,
  },
  "client": {
    "enabled": true,
    "chroot_env": {
      "/bin": "/bin",
      "/etc": "/etc",
      "/lib": "/lib",
      "/lib32": "/lib32",
      "/lib64": "/lib64",
      "/run/resolvconf": "/run/resolvconf",
      "/sbin": "/sbin",
      "/usr": "/usr"
    }
  },
  "consul": {
    "server_service_name": "nomad-server",
    "client_service_name": "nomad-client",
    "address": "127.0.0.1:8500",
    "auto_advertise": true,
    "client_auto_join": true,
    "server_auto_join": true
  }
}
```

### Issue
Submitting job fails with:

```
Jun 07 12:48:08 hostname.redacted nomad[7485]: 2023-06-07T12:48:08.590+0800 [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=c6998dae-aa8a-f030-462b-e31aa2db2233 task=sleep type="Driver Failure" msg="failed to launch command with executor: rpc error: code = Unknown desc = unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write \"0\": write /sys/fs/cgroup/memory/nomad/2f4cdd07-1faa-9b22-178c-b5c9b1dadafd/memory.swappiness: invalid argument" failed=false
Jun 07 12:48:08 hostname.redacted nomad[7485]: 2023-06-07T12:48:08.692+0800 [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=c6998dae-aa8a-f030-462b-e31aa2db2233 task=sleep error="failed to launch command with executor: rpc error: code = Unknown desc = unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write \"0\": write /sys/fs/cgroup/memory/nomad/2f4cdd07-1faa-9b22-178c-b5c9b1dadafd/memory.swappiness: invalid argument"
```

### Reproduction steps
* Try to start a job in an env as described above

#### Expected Result
* Job started

#### Actual Result
* Job allocation fails

### Job file (if appropriate)
```
job "hello-world" {
  datacenters = ["perf"]
  group "servers" {
    task "sleep" {
      driver = "exec"
      config {
        command = "sleep"
        args    = ["infinity"]
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
See above

**Comment by shoenig** [comment]
@akamensky can you ensure cgroups are enabled on the node?

https://developer.hashicorp.com/nomad/docs/drivers/exec#resource-isolation

**Comment by akamensky** [comment]
@shoenig cgroups are enabled. As you can see from the logs it fails to set swappiness to 0 in cgroup. If I recall correctly Centos 7 kernel version just doesn't have separate swappiness for cgroup it is inherited from the main namespace.

**Comment by akamensky** [comment]
@shoenig sorry to ping you on this, but do you have any feedback? This is a make or break issue for us as we have to run older systems in our infra. If we have no workaround or fix, then we would have to abandon Nomad.

**Comment by shoenig** [comment]
It might be possible to provide a fix for this. Looking at the libcontainer implementation it should [bypass writing](https://github.com/opencontainers/runc/blob/v1.1.5/libcontainer/cgroups/fs/memory.go#L129-L137) to the swappiness interface file if we pass in a nil `Resources.Swappiness`. Currently we hardcode a Zero value struct [here](https://github.com/hashicorp/nomad/blob/main/drivers/shared/executor/executor_linux.go#L692-L694) indicating swappiness should be disabled.

@akamensky are you able to test out such a fix yourself? We don't have any machines this old in our CI systems.

**Comment by akamensky** [comment]
I would be able to test if you can provide compiled binary or at least a patch and build instructions.

**Comment by shoenig** [comment]
@akamensky The PR https://github.com/hashicorp/nomad/pull/17625 contains a fix I think should work, but like I mentioned we simply don't have kernels that old handy to test with.

Probably the easiest way to check yourself would be to run the test case.
1. Install Go 1.20
2. Install make, git, gcc
3. Clone nomad, checkout branch in the PR
4. cd client/lib/cgutil
5. Run `go test -v -run MaybeDisableMemorySwappiness`
6. The test should **fail** on your older kernel (that implies it's correctly not setting the memory swappiness)

You can also build Nomad yourself
7. export PATH=$PATH:$HOME/go/bin
8. make bootstrap
9. make dev
10. your nomad binary should be in the bin directory

**Comment by akamensky** [comment]
Thanks @shoenig 

I got the code and follow the steps you outlined:

The `MaybeDisableMemorySwappiness` is passing (not failing):

```
# go test -v -run MaybeDisableMemorySwappiness
=== RUN   TestUtil_MaybeDisableMemorySwappiness
=== PAUSE TestUtil_MaybeDisableMemorySwappiness
=== CONT  TestUtil_MaybeDisableMemorySwappiness
--- PASS: TestUtil_MaybeDisableMemorySwappiness (0.00s)
PASS
ok  	github.com/hashicorp/nomad/client/lib/cgutil	0.010s
```

Not sure if this is expected. Next I will build the binary, but I need to hack your `GNUmakefile` as it requires internet connection even if I vendor all dependencies  in, which does not work in our systems as it is secured air-gapped network.

**Comment by akamensky** [comment]
@shoenig I throw together a simple check whether the sys fs path is actually writeable (not specific to control groups):

```golang
package main

import (
	"fmt"
	"io"
	"os"
)

func main() {
	cgOptions := []string{
		"/sys/fs/cgroup/memory/memory.swappiness",
	}

	for _, cgOption := range cgOptions {
		if !isCgOptionExists(cgOption) {
			// if cgroup option does not exist,
			// then nothing to do
			continue
		}

		if _, err := isCgOptionWritable(cgOption); err != nil {
			fmt.Println(cgOption, "is not writable due to:", err.Error())
		} else {
			fmt.Println(cgOption, "ok")
		}
	}
}

func isCgOptionExists(sysFsPath string) bool {
	_, err := os.Stat(sysFsPath)
	if os.IsNotExist(err) {
		return false
	}

	return true
}

func isCgOptionWritable(sysFsPath string) (bool, error) {
	currValue, err := readCgOption(sysFsPath)
	if err != nil {
		return false, err
	}

	err = writeCgOption(sysFsPath, currValue)
	if err != nil {
		return false, err
	}

	return true, nil
}

func readCgOption(sysFsPath string) ([]byte, error) {
	fd, err := os.Open(sysFsPath)
	if err != nil {
		return nil, err
	}
	defer fd.Close()

	return io.ReadAll(fd)
}

func writeCgOption(sysFsPath string, value []byte) error {
	fd, err := os.OpenFile(sysFsPath, os.O_TRUNC|os.O_WRONLY|os.O_SYNC, 0644)
	if err != nil {
		return err
	}
	defer fd.Close()

	_, err = fd.Write(value)
	if err != nil {
		return err
	}

	return nil
}
```

On the kernel in question it produces:

```
[root@redacted ~]# go run main.go 
/sys/fs/cgroup/memory/memory.swappiness is not writable due to: write /sys/fs/cgroup/memory/memory.swappiness: invalid argument
[root@redacted ~]# uname -a
Linux redacted 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

On somewhat newer kernel it produces:

```
[root@redacted ~]# go run main.go 
/sys/fs/cgroup/memory/memory.swappiness ok
[root@redacted ~]# uname -a
Linux redacted 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

On very recent kernel it produces:

```
[root@redacted cgcheck]# go run main.go 
[root@redacted cgcheck]# echo $?
0
[root@redacted cgcheck]# uname -a
Linux redacted 6.2.13-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 26 20:11:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by akamensky** [comment]
Thanks @shoenig I've tested updated patch and it works as expected now. I have not tried any other job configuration options with this, but if I find any issues with those old kernels will report them separately.
