### ISSUE TITLE
Nomad s390 builds support

### ISSUE THREAD

**Issue by Esity** [hashicorp/nomad#17440]
### Proposal
Start building Nomad binaries for S390. I believe there is already a build process for s390 and vault that exists
This is needed for running Hashicorp things on mainframe

### Attempted Solutions
We have a process to manually create builds for s390 but want an official Hashicorp pattern

<img width="794" alt="image" src="https://github.com/hashicorp/nomad/assets/1851830/9f494b6c-3b38-4da5-8be7-f0eab563b961">

**Comment by Esity** [comment]
It's worth noting we can only build OSS and can't leverage enterprise since the code isn't available for manual builds blocking us from moving forward with Nomad/Consul on mainframe for HPC

**Comment by mikenomitch** [comment]
Hey @Esity, we do plan to get around to an unofficial Ent build on this shortly after the 1.6 work has wrapped up. Have to go heads down to get that out for the next several weeks though.

**Comment by mikenomitch** [comment]
We now have s390X builds in the Enterprise releases.

These are still considered unsupported builds, so user-beware if you're running them. We added them only to the Enterprise pipeline since Ent users can't self-compile and we wanted to give these users something. CE users should self-compile.
