### ISSUE TITLE
integration with tilt

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#17459]
https://tilt.dev/
Hello Team, Can we get some insights on this?
https://github.com/tilt-dev/tilt/issues/5571

**Comment by thatsk** [comment]
or is there any alternative for this ?

**Comment by shoenig** [comment]
Hi @thatsk it seems like `tilt` is largely focused on the k8s use case. If they want to integrate with Nomad there is already an [API](https://developer.hashicorp.com/nomad/api-docs) for managing Nomad clusters, and we'd be happy to assist if we can. But beyond that I'm not sure what else can be done from the Nomad side.

**Comment by thatsk** [comment]
what are alternatives for this one based on nomad any idea.?
