### ISSUE TITLE
Networking: support docker --net=host

### ISSUE THREAD

**Issue by zenvdeluca** [hashicorp/nomad#175]
I'd like to spin up my containers with nomad without need of a docker0 bridge, or need of NAT to expose my services.

docker supports --net=host, which spin up the container sharing the host network namespace.
that means containers will bind ports using the host network stack. this should simplify a lot for using in production environments, where we don't want to use overlay networks and rocket sciences.

**Comment by purehyperbole** [comment]
+1, this would be super useful!

**Comment by LordFPL** [comment]
+1 for me too... and for all other docker options :-) (env & volumes essentially in my case)
