### ISSUE TITLE
Please release a 1.5.7 to fix bug introduced in 1.5.6

### ISSUE THREAD

**Issue by thefallentree** [hashicorp/nomad#17512]
1.5.6 release broke job validation, which is fixed by  https://github.com/hashicorp/nomad/pull/17391 , pls release a 1.5.7 soon.

**Comment by thefallentree** [comment]
hello, any plan to release 1.5.7 soon?

**Comment by shoenig** [comment]
Hi @thefallentree unfortunately we cannot spend the resources to cut a new release for every bug fix. If you are a Nomad OSS user, you are of course more than welcome to [build Nomad](https://github.com/hashicorp/nomad/tree/main/contributing#create-a-release-binary) yourself. I believe the next bugfix release is tentatively scheduled for the end of July.

If you are a Nomad ENT customer please reach out to your support contact.
