### ISSUE TITLE
Allocation UI page is missing information when browsed from Job UI page

### ISSUE THREAD

**Issue by atavakoliyext** [hashicorp/nomad#17521]
### Nomad version
v1.3.6

### Operating system and Environment details

* Chrome 113.0.5672.126 (and earlier)

### Issue

When navigating to an allocation's page in the UI from the job's page via the "Recent Allocations" link, the allocation's page is missing information.

Refreshing the page or opening the allocation page's URL in a new tab fixes the issue.

### Reproduction steps

1. For a job that has at least one running alloc, go to its page (e.g. `https://.../ui/jobs/JobName`)
2. Click on one of the running allocs in the Recent Allocations table

#### Expected Result

* The CPU/Memory graphs are non-empty (i.e. show something other than empty graphs & `0 ... / 0 ... Total`)
* The Task Lifecycle Status table is non-empty
* The Tasks/Ports/Services tables appear

#### Actual Result

See screenshot:

<img width="1428" alt="nomad-gh-bugreport-ui" src="https://github.com/hashicorp/nomad/assets/48605613/9dbb4d0d-76d5-4a2a-8797-3f7997b2ed89">

**Comment by philrenaud** [comment]
Hi @atavakoliyext , thank you for raising this. Could you provide me with a few details to help me recreate this bug on my end?
- What's the job type being run here (service? system?)
- Are you logged in with particular ACL policy/role rules applied? If so, could you let me know what your permissions look like?
- Are you seeing any javascript errors on the page? I notice in your screenshot that the keyboard shortcuts (light green letter boxes) are squished to the top left corner of your screen; makes me think that a JS error has taken place before these could be positioned. If there is an error, could you please provide some details for it?

**Comment by atavakoliyext** [comment]
Hi @philrenaud, I appreciate you looking into it.

> What's the job type being run here (service? system?)

This is primarily for service jobs; we haven't had reports of this in system jobs, but we also have comparatively much fewer of those, so there are fewer interactions that would've led to a report

> Are you logged in with particular ACL policy/role rules applied? If so, could you let me know what your permissions look like?

No, we are not logged in with any ACL tokens when this happens. No secret or accessor ID is set in the UI when this happens

> Are you seeing any javascript errors on the page? I notice in your screenshot that the keyboard shortcuts (light green letter boxes) are squished to the top left corner of your screen; makes me think that a JS error has taken place before these could be positioned. If there is an error, could you please provide some details for it?

I'll be sure to check the next time this happens and report back with any inspector errors.

What I can say is that there definitely are some console errors (e.g. a 500 Internal Server error consistently appears on page load against path `/v1/acl/token/self`, and 100+ `chunk.514.007cad389153bda00b8f.js:2412 Error: <rect> attribute width: A negative value is not valid. ("-...px")` error logs are in the console) but **without** this issue manifesting. I'm not sure if this rules anything out, but hopefully it's useful troubleshooting data.

**Comment by philrenaud** [comment]
Got it, and think I've been able to reproduce it! I'll get to work on this asap.

**Comment by philrenaud** [comment]
Thanks for this, @atavakoliyext — I've got a fix up at https://github.com/hashicorp/nomad/pull/17737 that has resolved this problem on my own Nomad UI instance. I'll seek to get this merged as soon as possible.
