### ISSUE TITLE
Option to disable versioning on stop/start operations

### ISSUE THREAD

**Issue by valafon** [hashicorp/nomad#17586]
Hello! I'm using HashiCorp Nomad and I've encountered an issue with versioning when stopping/starting jobs.

When I stop or start a job, Nomad automatically creates a new version of this job. This behavior negatively impacts ability to roll back versions, as every stop/start operation generates a new version, making it challenging to track meaningful changes and perform rollbacks. 

It would be helpful to have the option to disable the creation of new job versions upon stop/start operations. This could potentially be implemented via configuration parameters or server settings. Also, it might be useful to have the option to ignore specific actions - not only stop/start, but such actions as scaling. 

I understand that the current behavior is due to Nomad's architecture and may have certain objectives in mind. However, in my specific case, it's causing difficulties. I would appreciate it if you could consider making changes to this behavior.

**Comment by tgross** [comment]
Hi @valafon! You're right that this is baked-in to Nomad's architecture pretty firmly. Once an object is in the "terminal" state it never returns to a non-terminal state and that's necessary for garbage collection and concurrent requests to be safe.

Just out of curiosity, it looks like you're using stop/start as a kind of "scale to zero" operation?

**Comment by valafon** [comment]
We use stop/start so the job would try to reschedule on other nodes (once we need to move it for resource usage reasons, sometimes we need to do it). When you just restart allocation, it would just start on the same node.

**Comment by valafon** [comment]
> Hi @valafon! You're right that this is baked-in to Nomad's architecture pretty firmly. Once an object is in the "terminal" state it never returns to a non-terminal state and that's necessary for garbage collection and concurrent requests to be safe.
> 
> Just out of curiosity, it looks like you're using stop/start as a kind of "scale to zero" operation?



We use stop/start so the job would try to reschedule on other nodes (once we need to move it for resource usage reasons, sometimes we need to do it). When you just restart allocation, it would just start on the same node.

**Comment by tgross** [comment]
You can use [`nomad alloc stop`](https://developer.hashicorp.com/nomad/docs/commands/alloc/stop) for that. It'll stop the allocation and the scheduler will reschedule it. That's different from [`nomad alloc restart`](https://developer.hashicorp.com/nomad/docs/commands/alloc/restart) which just restarts in-place. You can also use `nomad job restart` with a lot of different options (ref https://developer.hashicorp.com/nomad/docs/commands/job/restart#restart-options) if you want to restart more than one alloc for a job at a time.

**Comment by valafon** [comment]
> You can use [`nomad alloc stop`](https://developer.hashicorp.com/nomad/docs/commands/alloc/stop) for that. It'll stop the allocation and the scheduler will reschedule it. That's different from [`nomad alloc restart`](https://developer.hashicorp.com/nomad/docs/commands/alloc/restart) which just restarts in-place. You can also use `nomad job restart` with a lot of different options (ref https://developer.hashicorp.com/nomad/docs/commands/job/restart#restart-options) if you want to restart more than one alloc for a job at a time.

Specifically in our case, we have tier1 engineers who do stop/start jobs so that they reschedule to another node, via WEB-UI. They do not have access and skills to use CLI. In the WEB-UI, I do not see the buttons for 'restart all tasks with reschedule' for allocation. Only regular restart. :( And stop/start eventually generate new job versions, making it impossible to do a job rollback if they were done several times (as more than 6 versions simply get deleted). Moreover, actually doing a rollback to a version where only stop=true/false was changed is rather meaningless, is it really worth storing this in the versions? Therefore, generally, I suggested, maybe there would be an option to disable saving the stop state at the server level, or at the job definition level.
