### ISSUE TITLE
supporting nested "meta" keys

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1759]
Hi,

It would be nice if it was possible to nest `meta` keys 

```
    meta {
        APP_VERSION = "0"
        APP_ENV = "production"
    }
```

would be nice to be able to do 

```
    meta {
        APP {    
                VERSION = "0"
                ENV = "production"
        }
    }
```

while the example above is kinda bad, my real usage is that I autoscale nomad processes based on different observations (rabbitmq queue length, utilization, time etc) and it would be nice to have these rules in the jobfile itself, rather than in a detached different file 

actual code from my YAML file

```
scale:
  max: 30
  min: 0
  rules:
    - type: queue
      name: builders
      cron: "*/10 * * * *"
      equal: 0
      if: { numprocs: 0 }
    - type: queue
      name: builders
      above: 0
      if: { numprocs: 30 }
```

trying to do it a flat map make it much less readable 

```
meta {
                SCALE_MIN = 0
                SCALE_MAX = 1

                # scale up when busy
                SCALE_RULE_0_TYPE = "queue"
                SCALE_RULE_0_NAME = "builders"
                SCALE_RULE_0_CRON = "*/10 * * * *"
                SCALE_RULE_0_EQUAL = 0
                SCALE_RULE_0_IF = "numprocs = 1"

                # scale down when idle
                SCALE_RULE_1_TYPE = "queue"
                SCALE_RULE_1_NAME = "builders"
                SCALE_RULE_1_ABOVE = 0
                SCALE_RULE_1_IF = "numprocs = 30"
 }
```

something ala this (not HCL expert) would be amazing - maybe flattened internally like `envconsul` does for nested consulkv when exposed to `${meta.*}` 

```
meta {
    scale {
        min = 0
        max = 1
        rule "scale-up" {
            type = "queue"
            name = "builders"
            cron = "*/10 * * * *"
            equal = 0
            if { numprocs = 0 }
        }

        rule "scale-down" {
            type = "queue"
            name = "builders"
            above = 0
            if = { numprocs = 1 }
        }
    }
```

while I'm flexible to the format, having more than 1 level of nesting would make this a lot easier to work with.

My idea was to have it in HCL, throw it through `nomad run -output job.hcl` and read out the scaling rules from the JSON version of the job, change the `count` key for the different groups based on the rules, and then submit it back to nomad if any `count` values changed

For me its not important if it living in `meta` or a specialized nested key structure somewhere, just having the possibility to attach meta-data for external apps into the job file would be immensely useful

**Comment by dadgar** [comment]
Can you just put the whole json blob in a single key. My initial reaction is to not support these nested keys. It adds a decent amount of complexity `map[string]string` to `map[string]interface{}` and reflection to make it work, when users can namespace the keys `level_one.level_two.key`

**Comment by jippi** [comment]
@dadgar I could, but it kinda messes with the indent / readability / syntax highlight ... but given the complexity you describe, maybe heredoc is the best solution on my part for now :)

it's just a think i love from envconsul that i would have loved to see in nomad :)

**Comment by dadgar** [comment]
@jippi Maybe eventually! It is good to think about UX! I am going to close this then as it isn't something we are currently interested in doing! Thanks @jippi
