### ISSUE TITLE
document client-to-client HTTP API consumers

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#17631]
Documentation (https://developer.hashicorp.com/nomad/docs/configuration#advertise):

> The address to advertise for the HTTP interface. This should be reachable by all the nodes from which end users are going to use the Nomad CLI tools.

Based on this one might think that the HTTP interface is only used from CLI tools (or may be libraries). And limit access only to 127.0.0.1 for example.

But actually the api used for client <-> client communication. One case I found that it's required for ephemeral disk migration. There are probably others?

The situation is aggravated by the fact that nomad clients successfully work with such limited settings, they only break in some infrequent cases.

Descriptions in other places are also not very specific  and in combination with above can cause incorrect assumptions https://developer.hashicorp.com/nomad/docs/install/production/requirements
> HTTP API (Default 4646). This is used by clients and servers to serve the HTTP API. TCP only.

Serve the HTTP API, nothing about client <-> client communication.

Same here https://developer.hashicorp.com/nomad/docs/concepts/security#network-ports
> to provide [UI](https://developer.hashicorp.com/nomad/tutorials/web-ui/web-ui-access) and [API](https://developer.hashicorp.com/nomad/api-docs) access to agents.

**Comment by tgross** [comment]
Hi @valodzka! I just did a quick double-check and I'm pretty sure the only client-to-client HTTP request is from that ephemeral disk migration. Fortunately that degrades gracefully (as it's a "best effort" sort of thing). But that's definitely a documentation miss.

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/17779, which will ship the next time the docs site gets pushed.
