### ISSUE TITLE
Tuning job versions retention.

### ISSUE THREAD

**Issue by valafon** [hashicorp/nomad#17635]
At the moment, as far as I can see, primarily 6 versions are stored in Nomad. If you made some changes during the day, more versions are stored, but then it goes back to 6 again. I couldn't find any server documentation for tuning this behavior. I would like to increase both the number of permanently stored job versions and the frequency/parameters of retention. I found an issue on this topic way back in 2018 https://github.com/hashicorp/nomad/issues/4242. The topic creator was told that adding these changes is not difficult, but it seems like no one ever made a feature request for this change. Therefore, I will ask for it. This is very important for a convenient rollback.

Also, there is a problem, when I use nomad cli to show job versions, I see only 6 of them, while there are more at the moment.

**Comment by tgross** [comment]
Hi @valafon! Yes, this is currently hard-coded (ref [`structs.go#L4240-L4246`](https://github.com/hashicorp/nomad/blob/v1.5.6/nomad/structs/structs.go#L4240-L4246)). So it'd be a matter of plumbing a new server configuration field down into where it's consumed in the state store (ref [`state_store.go#L1947-L1967`](https://github.com/hashicorp/nomad/blob/v1.5.6/nomad/state/state_store.go#L1947-L1967))

**Comment by devashishTaneja** [comment]
@tgross I have raised a PR for this issue. Please have a look.

https://github.com/hashicorp/nomad/pull/17939
