### ISSUE TITLE
Nomad does not restart a container with changed arguments

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/nomad#1764]
### Nomad version
Nomad v0.4.1

### Operating system and Environment details
Ubuntu 14.04

### Issue
Given a job that uses docker and args, when args are changed and the job is resubmitted, no action is taken.

### Reproduction steps

Run a job like this (abbreviated): 

```hcl
task "server" {
  driver = "docker"

  config {
    image = "hashicorp/http-echo:0.1.1"
    args  = ["-text", "hello world"]
  }
}
```

Change the value of "-text" to "banana":

```hcl
task "server" {
  driver = "docker"

  config {
    image = "hashicorp/http-echo:0.1.1"
    args  = ["-text", "banana"]
  }
}
```

Save and re-run the job. No action will be taken on the container, even though arguments have changed.

**Comment by sethvargo** [comment]
Even completely stopping the job and re-submitting it does not pick up new arguments.

**Comment by dadgar** [comment]
@sethvargo Works for me? Maybe something wrong with your docker daemon? You can see via nomad plan that it does a create/destroy update

**Comment by sethvargo** [comment]
It only happens on one host, but they are all provisioned exactly the same, at the same time, and the log output is identical 😦

**Comment by dadgar** [comment]
Did nomad create a new allocation.  If so nomad did the right thing and docker daemon is likely at fault

**Comment by sethvargo** [comment]
Yea, it created a new allocation when I submitted the job, but I don't see anything in the logs indicating Nomad tried to stop the container.

**Comment by dadgar** [comment]
If you share the logs I can comment

**Comment by sethvargo** [comment]
Gonna blame docker on this one, since I can't repro.
