### ISSUE TITLE
envconsul-like environment {} clause

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1765]
Hi

Is it planned to bring envconsul like consul-kv monitoring into nomad and restart the process on change(s) ? 

e.g. monitoring two `-prefix` and on changes within those kv, send certain signal / restart process ideally with similar `wait` , `upcase` and `sanitize` options

similar to 

```
consul {
   kv_prefix {
      prefixes = ["/something", "/awesome"]
      wait { min: "3s", max: "6s" }
      upcase = 1
      sanitized = 1
   }
}
```

**Comment by dadgar** [comment]
We don't have plans to first class this but would like to make it possible through life-cycle plugins which we plan to bring in 0.6

**Comment by jippi** [comment]
@dadgar so you have a overview roadmap of which features you got planned for which versions ?

**Comment by dadgar** [comment]
Internally yes, but we do not advertise it publicly since it changes quite often

**Comment by jippi** [comment]
@dadgar I'm not necessarily interesting in feature `x` will be in release `y`, but rather what the features in general is :) I've bet on all hashcorp software since first public releases so far, and never been disappointed :)

**Comment by c4milo** [comment]
I would be interested in sort of an envconsul block configuration similar to the recently introduced template block.

**Comment by sprutner** [comment]
+1

**Comment by samber** [comment]
If I can help you in any way, just le me know !

**Comment by dadgar** [comment]
Just to update this, this will land in 0.6.0!
