### ISSUE TITLE
Vault integration not working 

### ISSUE THREAD

**Issue by tmaior** [hashicorp/nomad#1766]
Hi Guys.

I'm trying to use Nomad with Vault integration (with consul backend) based on the presentation "Securing Applications Using Nomad" from Alex Dadgar: https://www.youtube.com/watch?v=4gAYyAA6h9E

I'm creating the binary from source (master branch) using `make bootstrap`, `make dev`.

When I try to run the job I get the error:  
` * RPC failed to server 10.0.0.232:4647: rpc error: Vault not enabled and Vault policies requested...`
I've tried a lot of different configurations and nothing works.

I even tried to use different branches and I got a different behavior when using the branch: `f-nomad-0.5`. In this case job gives me the error related to the 'env' parameter after the `policies`. It does not recognize the 'env' configuration. If I remove 'env' the job works but the secrets are not available using `nomad fs` in the allocation.

I'm attaching my client and server configuration end also the frontend job.
[frontend.nomad.txt](https://github.com/hashicorp/nomad/files/499345/frontend.nomad.txt)
[client.hcl.txt](https://github.com/hashicorp/nomad/files/499346/client.hcl.txt)
[server.txt](https://github.com/hashicorp/nomad/files/499347/server.txt)

Thanks for the help.

**Comment by dadgar** [comment]
Hey this feature is not yet released so I am going to close the issue but the you need to add the appropriate config to the server and client configs: https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/vault.go#L23

I would build off of master.

**Comment by tmaior** [comment]
Hi @dadgar. Thanks for the quick response.
Can you give me more details about the appropriate config?

The server and client has all the config related to https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/vault.go#L23:

vault {
    address = "https://10.0.0.231:8200"
    token = "6e073f4b-4a6d-1fde-812e-7ff65dd3f4fa"
    allow_unauthenticated = true
    task_token_ttl = "5m"
    enabled = true
    tls_ca_file = "/etc/ssl/cluster/ca.pem"
    tls_ca_path = "/etc/ssl/cluster"
    tls_cert_file = "/etc/ssl/cluster/cert.pem"
    tls_key_file = "/etc/ssl/cluster/key.pem"
    tls_server_name = "vault"
    tls_skip_verify = true
}

**Comment by dadgar** [comment]
With that configuration you are getting an error?

**Comment by tmaior** [comment]
yes: * RPC failed to server 10.0.0.232:4647: rpc error: Vault not enabled and Vault policies requested...

**Comment by tmaior** [comment]
There is nothing on the log that shows error connecting to Vault also.

**Comment by dadgar** [comment]
@tmaior There is a bug in the config parsing. Just add `-vault-enabled -vault-allow-unauthenticated` when starting up Nomad

**Comment by tmaior** [comment]
Thanks a lot for the information @dadgar. 

Now the job works but I get the error: 

Client Description = failed to derive Vault token for allocation "8f48f8ce-20a6-d33b-1828-5b55cabf463e": failed to derive Vault tokens: failed to derive vault tokens: 1 error(s) occurred:
* RPC failed to server 10.0.0.200:4647: rpc error: 1 error(s) occurred:
* failed to create token for task "web": Connection to Vault has not been established. Retry```

Do you know if it is a error related to the connection between Vault and Nomad or if the type of token can't create child tokens.

Thanks for the help.

**Comment by dadgar** [comment]
That is the server saying that it hasn't been able to connect to Vault yet. I would check your server logs and also make sure that you can connect from the Nomad server machines with the config you have

**Comment by tmaior** [comment]
Thanks @dadgar.

The machines from Nomad can connect to Vault server without any problem. Also one thing I notice is that, when I use a invalid Vault address on Nomad config, I get the error:
* Constraint "${attr.vault.version} version >= 0.6.1" filtered 1 nodes

So, it seems that Nomad is able find Vault and check its version (when the address from Vault is correct).
Is is possible that this problem is related to docker?
Do I need Vault client configure inside the container?
Or maybe that the message is related to some configuration in vault?

Thanks

**Comment by dadgar** [comment]
Yeah, Nomad will only place a task that has asked for a vault token on a Node that can talk to vault.

So can you paste your server logs? If the server can't communicate with Vault you should see something like:

`2016/09/29 00:24:48.279574 [WARN] vault: failed to contact Vault API. Retrying in 30s`

Otherwise there should be a successful message, either one of the below: 
```
[DEBUG] vault: not renewing token as it is root
[DEBUG] vault: token lease duration is 30d
```

**Comment by tmaior** [comment]
Thanks @dadgar.

Yes, it seems that you are right, there is a error in server related to Vault:
2016/09/28 20:32:51.040711 [ERR] vault: failed to lookup self token and not retrying: token role name must be set when not using a root token

What does that mean?

**Comment by dadgar** [comment]
Yep so the token that you give the Nomad server has to be created from a role. This is a requirement because that allows child tokens to be periodic. If they were non-periodic the Nomad client could not renew them. 

If you scroll to the bottom of this page: https://www.vaultproject.io/docs/auth/token.html
That is how you create a role. You should give the role access to all the policies that tasks under nomad will need access to

**Comment by tmaior** [comment]
Hi @dadgar. It works. Now I can see the vault_token using nomad fs.

My next issue is about the consul-template integration with nomad. Is it working yet?
I tried to deploy the following job, but nothing seems to happen.

 vault {
           policies = ["policy2"]
}
template {
            data= <<END
{{ with $secret := vault "secrets/secret1" }}
   secret1 valus is: {{ $secret.value }}
{{ end }}
END
           destination = "secrets/showsecrets"
           change_mode = "signal"
           restart_signal = "SIGUSR2"
}

**Comment by dadgar** [comment]
Hey,

That is not in master at all really. I am working on that as we speak.

-Alex

**Comment by tmaior** [comment]
Ok. Thanks @dadgar. If you can, let me know when this is done. I test it.

Thanks for all your huge help.
