### ISSUE TITLE
raw_exec  "flag provided but not defined"

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1770]
Using v0.4.1 and the following job spec (raw_exec) i get `flag provided but not defined`

Running the command by hand works fine

`/usr/local/bin/envconsul -config /etc/envconsul/config.hcl -prefix apps/insights/nomad/click-rollup/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server`

```
    {
      "Name": "click-rollup",
      "Count": 1,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/click-rollup/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server"
            ]
          },
          "Env": {
            "APP_VERSION": "1475",
            "APP_ENV": "production"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "insights.click_rollup",
        "bownty.scale.use_config": "default"
      }
    },
```

yields 

`flag provided but not defined: -config /etc/envconsul/config.hcl -prefix apps/insights/nomad/click-rollup/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server
`

**Comment by iverberk** [comment]
I think you need to split up the arguments:

```
"args": [
"-config", "/etc/envconsul/config.hcl", "-prefix", "apps/insights/nomad/click-rollup/server/env".....
]
```
Otherwise the whole thing is considered a single argument.

**Comment by jippi** [comment]
@iverberk yeah, i ended up doing that, though its super failure prone

imo it should be possible to just pass a `args` string or single-key array with the full string

especially when constructing jobs programatically, where its not clear if its key/value or not in the arguments

**Comment by dadgar** [comment]
@jippi Hey at one point we did do the automatic splitting but it was exceedingly annoying with interpolations and embedded substrings, etc. We feel in this case the explicit approach works best

**Comment by jippi** [comment]
@dadgar would it be possible to have two options then?

if its a string, don't do magic, if its array, do the magic?
