### ISSUE TITLE
Provide a way to restrict access to run privileged Docker containers

### ISSUE THREAD

**Issue by sorenisanerd** [hashicorp/nomad#17701]
### Proposal
Just like `raw_exec` can be restricted on a per-namespace basis, there should be a way to restrict privileged Docker containers on a per-namespace basis.

### Use-cases
* I want to run certain system jobs that require privileged Docker containers (e.g. CSI plugins), but allowing all users in all namespaces to do so would be tantamount to giving everyone root access.

**Comment by tgross** [comment]
Hi @sorenisanerd! Thanks for opening this issue. We've had https://github.com/hashicorp/nomad/issues/6554 open for a while now about this problem. I'm going to close this as a duplicate.
