### ISSUE TITLE
Add metric for MemoryMaxMB parameter

### ISSUE THREAD

**Issue by gautamg795** [hashicorp/nomad#17716]
### Proposal
Add an additional metric `nomad_client_allocs_memory_max_allocated` representing the `MaxMemoryMB` parameter, if specified.

### Use-cases
We already have a `nomad_client_allocs_memory_allocated` metric which reports the memory allocated for a given job, making it easy to calculate an allocation's memory usage relative to the amount of reserved memory. However it'd also be useful to calculate how close an allocation is to being OOM killed because it is hitting the max limit.

### Attempted Solutions
I did not find any metrics which report the `MaxMemoryMB` parameter.

**Comment by lgfa29** [comment]
Hi @gautamg795 👋 

Thanks for the suggestion, I've opened #17938 to add this new metric.
