### ISSUE TITLE
Dependency hashicorp/cronexpr: No machine-readable license and GitHub issues disabled

### ISSUE THREAD

**Issue by luisgerhorst** [hashicorp/nomad#17723]
### Nomad version

`v0.0.0-20230124213148-69fd1a0e4bf7`

### Operating system and Environment details

NA

### Issue

I noticed that for the dependency https://github.com/hashicorp/cronexpr the license (GPL-3.0-only OR Apache-2.0) is not properly recognized by common license checkers (e.g., go-license and GitHub).

Unfortunately, the GitHub issues are disabled for the project and the project it was forked from has been archived.

To fix the issue, the maintainers of cronexpr can simply rename the APLv2 file to LICENSE (or LICENSE-APACHE [1]) and keep the GPLv3 file name or also rename this file to LICENSE-GPL-3.0-only if you prefer (although this file will not be recognized by common go lincense checkers).

### Reproduction steps

NA

#### Expected Result

Licenses should be machine-readable.

#### Actual Result

They are not.

**Comment by shoenig** [comment]
Thanks for pointing that out @luisgerhorst. Currently that repository is locked down good and tight internally, so it may take a few days before I even have permission to make changes.

**Comment by luisgerhorst** [comment]
Thanks @shoenig! Do you think it would be possible to also enable issues for `cronexpr`? (Took me quite some time to find the right way to report this, I first mailed @averche).
