### ISSUE TITLE
API: /jobs/ `JobSummary` key do not reflect actual state

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1773]
Hi,

Using nomad v0.4.1 `/jobs` endpoint I also get a `JobSummary` key like below.

The `JobSummary` don't seem to reflect the current state of the task, e.g. `Queued` has a value of 5, can't find any raw data in any other API response to match this.

The key seem to be undocumented (?) - would it be possible to get clarification on what the `JobSummary` reflect

Thanks! :)

``` json
  {
    "ID": "insights-web",
    "ParentID": "",
    "Name": "insights-web",
    "Type": "system",
    "Priority": 50,
    "Status": "running",
    "StatusDescription": "",
    "JobSummary": {
      "JobID": "insights-web",
      "Summary": {
        "php-fpm": {
          "Queued": 5,
          "Complete": 11,
          "Failed": 0,
          "Running": 3,
          "Starting": 0,
          "Lost": 0
        }
      },
      "CreateIndex": 544301,
      "ModifyIndex": 547489
    },
    "CreateIndex": 544301,
    "ModifyIndex": 550283,
    "JobModifyIndex": 550283
  },
```

**Comment by dadgar** [comment]
Closed by https://github.com/hashicorp/nomad/pull/2163
