### ISSUE TITLE
UI: Text wrap long lines of code and logs and text

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#17749]
### Proposal
I propose to wrap long lines when displaying long code lines, like job definitions and logs, just like you would view them in terminal.

### Use-cases
When job definitions with long lines are rendered in the UI, I have to scroll, scroll, scroll. There is no left-right scrollbar rendered, so I have to select text and move the text left-right with selection, which is unpleasant.

### Attempted Solutions
I use stylus plugin in chrome with:

```
code {
    word-wrap: break-word;
    text-wrap: balance;
}
span {
    word-wrap: break-word;
    text-wrap: balance;
}
.cli-window {
    word-wrap: break-word;
    text-wrap: balance;
}
```

On very long metadata, this also makes the metadata visible in the UI and wrapped instead of replaced with `...` dots.

Thanks for making Nomad!

**Comment by Kamilcuk** [comment]
Great! No. (TBH, I never used the "run a job" in the UI, I even would want to disable it, so users do not have access to it in our env).

I am referring to the job definition page: ui/jobs/public@default/definition
and to allocations logs: ui/allocations/647cabe4-8b56-537f-b9f7-11792560e7a6/public/logs
and the shortcut "View Logs" from the job page.

**Comment by philrenaud** [comment]
Cool, and good suggestions. Let me see what we can do here.

**Comment by philrenaud** [comment]
Hi @Kamilcuk, thanks again for your suggestions here. We've made some chnages in #17754 that I hope will solve the challenge you mentioned here and make the UI a little more pleasant to use.
