### ISSUE TITLE
GC doesn't clean all allocations and evaluations

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1775]
### Nomad version

0.4.1
### Operating system and Environment details

Linux 
### Issue

For some reason my cluster have ended up with allocations and evaluations > 2 months old that never get gc'ed.

The issue seem to be that their origin job no longer exist, and thus they seem orphaned 
### Reproduction steps

N/A
### Example evaluation + allocation

https://gist.github.com/jippi/8543aff4ab43a648c4f93ea7138b8fc5

Worth mentioning that the Allocation JobID ( example ) does not exist. (404 on /v1/job/example) and haven't existed for months.

Feel free to reach out on gitter for any additional data.

Hitting the GC api endpoint does not remove the resources either

**Comment by dadgar** [comment]
This was fixed in 0.5.5: #2432
