### ISSUE TITLE
restart/reschedule links on job index page aren't cleared after job deletion

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#17757]
When a job is purged but you don't leave the job index page, a newly submitted version of the job "remembers" the restart/reschedule indicators (in the UI only) for the previously purged version. This leaves links to an empty allocations list.

To reproduce with the beta build, use the following jobspec.

<details><summary>jobspec</summary>

```hcl
job "bug" {

  reschedule {
    attempts       = 1
    interval       = "24h"
    delay          = "20s"
    delay_function = "constant"
    unlimited      = false
  }

  group "group" {

    restart {
      attempts = 1
      delay = "1s"
      mode  = "fail"
    }

    task "task" {
      driver = "docker"

      config {
        image   = "busybox:1" # "busybox:does-not-exist"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
      }
    }
  }
}
```

</details>

Run the job and wait for it to become healthy. Then switch `image = "busybox:1"` for `image = "busybox:does-not-exist"` and run it again. After a little while we'll see the deployment fail as we'd expect with 1 reschedule and 2 restarts in total.

![failed-as-expected](https://github.com/hashicorp/nomad/assets/1409219/504834a6-39a8-49d3-9770-e7c1cde223dc)

Now stop the job and purge it with `nomad job stop -purge bug`. Run `nomad system gc` for good measure. Do not leave the job index page for the now-purged job! (If you leave the page to go to the job list page first, the bug doesn't happen.)

Fix the job to use `image = "busybox:1"`, and run it again. You'll see that the restart/reschedule indicators are not cleared as we'd expect.

![retry-after-purge-without-refresh](https://github.com/hashicorp/nomad/assets/1409219/d3b20fca-666b-4591-850d-a35e389ede4f)

The links still work but the destination page is empty, because there are no version 1 allocations for this job anymore:

```
$ nomad job status bug
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
db8ed674  5f1a69ac  group       0        run      running  36s ago  26s ago
```

![Screenshot at 2023-06-28 10-28-54](https://github.com/hashicorp/nomad/assets/1409219/ef9a3654-7631-4672-ba4f-ff85edf10826)

**Comment by tgross** [comment]
I thought I'd found a second bug for these links where reschedules were getting marked as restarts, but after some careful testing that turns out to be another case of this bug. If the new version of the job has `restart.attempts = 0` it'll still show those restarts from the previously-purged job and that ends up looking like we marked a reschedule as a restart.

**Comment by philrenaud** [comment]
Working on this and just wanted to say: this bug rules, this bug report rules. Even **switching tabs for a moment** after the purge has taken place will not trigger this bug, because of the background allocs long-polling not staying open when tab is unfocused. Gonna fix this now but really impressed to see it here.
