### ISSUE TITLE
include parent job ID as a Docker container label

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#17751]
### Proposal
Next to the `container.labels.com_hashicorp_nomad_job_id` field that is already being set, have a field that excludes the `/periodic-901283123` suffix for batch jobs.

My feeling tells me the `container.labels.com_hashicorp_nomad_job_name` field would make sense for that (since right now, they have the same value) - but that would break backwards compatibility a bit. 

Any field would suffice. In a lot of cases, I only care about the job name as provided in the `.nomad.hcl` file, and not have to bother with whatever suffixes were added. 

### Use-cases
Logging / filtering / grouping based on that value, while not caring about the timestamp that the batch job.

### Attempted Solutions
In my Elasticsearch I now need to setup an ingest pipeline to remove this `/periodic-*` suffix, because I want to filter on the name of the job (without the timestamp).

**Comment by tgross** [comment]
Hi @EtienneBruines! That seems like a good idea. I'll mark this for roadmapping but it's also small enough that I'll mark it as a good first issue to see if anyone from the community wants to give a try at adding it (they might start looking in [`docker/driver.go`](https://github.com/hashicorp/nomad/blob/main/drivers/docker/driver.go)

**Comment by devashishTaneja** [comment]
@tgross I would like to contribute to this issue.

**Comment by tgross** [comment]
Go for it! Feel free to tag me o the PR and I'll make sure it gets reviewed.

**Comment by devashishTaneja** [comment]
Hi @tgross, @EtienneBruines,

This is my first contribution to Nomad so I am lacking some context. I would appreciate if you could help me with a couple of doubts. So I was able to setup Nomad in my local to start a periodic docker. When I do a _docker inspect_ on the container. I can see the following labels set up by default i.e. _dockerLabelAllocID_ but no _com_hashicorp_nomad_job_id_ label


<img width="814" alt="Screenshot 2023-07-07 at 9 36 31 PM" src="https://github.com/hashicorp/nomad/assets/32792385/a754c239-c430-437a-b484-d28e26177f6c">


But I do see a similar env set (screenshot attached below) so my question is the ask to add a new env or label itself. If labels can you suggest me how these labels are set in the first place. Below is the config file I used to start the periodic docker.


<img width="814" alt="Screenshot 2023-07-07 at 9 36 41 PM" src="https://github.com/hashicorp/nomad/assets/32792385/783406bf-232b-47bb-a392-73fbf10a04a6">



```
job "simple" {
  datacenters = ["dc1"]
  type = "batch"

  periodic {
    cron             = "*/1 * * * *"
    prohibit_overlap = true
  }

  group "simple" {
    task "simple" {
      driver       = "docker"
      kill_timeout = "10m"

      config {
        image   = "hashicorp/http-echo:latest"
        command = "-listen=:8080 -text='hello world'"
        args = [
          "-listen",
          ":3032",
          "-text",
          "Hello, world!",
        ]
      }

      resources {
        cpu    = 100
        memory = 100
      }
    }
  }
}

```

**Comment by EtienneBruines** [comment]
@devashishTaneja Have you configured your Nomad Client to add those labels? e.g.:

```hcl
plugin "docker" {
  config {
    # Extra labels to add to Docker containers. Available options are job_name, job_id, 
    # task_group_name, task_name, namespace, node_name, node_id. Globs are supported (e.g. task*)
    extra_labels = ["job_name", "job_id", "task_name"]
  }
}
```

**Comment by devashishTaneja** [comment]
Thanks for the help @EtienneBruines !! Please review the final label.

<img width="952" alt="Screenshot 2023-07-08 at 12 06 59 AM" src="https://github.com/hashicorp/nomad/assets/32792385/d2d5907c-13e5-4611-aa11-b4b728eb389f">

@tgross I have raised the PR can you please review the PR.
https://github.com/hashicorp/nomad/pull/17843
