### ISSUE TITLE
cli: include job name in output of `nomad job run/restart/other` 

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#17773]
request: 
nomad job run/restart (and others?) should show the name of the job that was passed in:

This it the output of some `nomad job restart foo`
```
==> 2023-06-29T17:20:19Z: Restarting 3 allocations
    2023-06-29T17:20:19Z: Rescheduling allocation "3f1d5735" for group "puma"
    2023-06-29T17:20:20Z: Allocation "3f1d5735" replaced by "404db904", waiting for "404db904" to start running
    2023-06-29T17:21:19Z: Still waiting for allocation "3f1d5735" to be replaced
```
Somewhere in here include the word `foo` because it's the job name

use case:
I bash-scripted multiple 'nomad job restart' runs.  There's no way for me to know how far along it is because the actual job name doesn't appear in the output. 

Seems obviousish to include job name in the output, even in the general case..  "Restarting 3 allocations". yay... allocations of what?  The group name is included in the output - but at least for us that's similar across jobs.

**Comment by lgfa29** [comment]
Hi @josh-m-sharpe 👋 

Normally we would expect the job name to be part of the command input and visible , so also having it in the command output may be a bit redundant, but probably not a bad thing to have.

Another potentially tricky aspect is that, if you're running these commands in parallel, then the lines will be all mixed up. Would you expect to see the job name at every line?

**Comment by josh-m-sharpe** [comment]
Closing this because it can just be solved in the shell script and there are bigger fish
