### ISSUE TITLE
inelligible filter in topology doens't work

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#17772]
![Cluster_Topology_-_Nomad](https://github.com/hashicorp/nomad/assets/39473/78dbd0d4-51cf-4909-b8fc-c97ff3a93899)

![Cluster_Topology_-_Nomad](https://github.com/hashicorp/nomad/assets/39473/df9448a9-b766-4032-9d25-3947e22d9f1c)

**Comment by philrenaud** [comment]
Hi @josh-m-sharpe , thanks for raising this. We will give it a look and see what the fix looks like soon.
