### ISSUE TITLE
Multiple cron specs

### ISSUE THREAD

**Issue by aneustroev** [hashicorp/nomad#17804]
### Proposal
I want to make multiple cron specifications. Sometimes it useful, because impossible to make any time conditions using cron. 

### Use-cases
Some batch job required non linear intervals between runs.
For example

- every day at 6:30  `30 6 * * *`
- every day at 15:00  `0 15 * * *`
- every day at 20:45  `45 20 * * *`

### Attempted Solutions
In source code I see that I can set only one cron string.
Make several periodic jobs is dirty and bad for observability.

**Comment by aneustroev** [comment]
Can you make me a advice, how to implement it feature better?

**Comment by aneustroev** [comment]
https://github.com/hashicorp/nomad/pull/17811

**Comment by aneustroev** [comment]
https://github.com/hashicorp/nomad/pull/17858

**Comment by lgfa29** [comment]
Thanks for the idea and the PR @aneustroev!  I left a review you there 🙂
