### ISSUE TITLE
Downloading Docker image tarball from S3 fails with 403 error with archive=false

### ISSUE THREAD

**Issue by sgerace** [hashicorp/nomad#17807]
### Nomad version
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80

### Operating system and Environment details
Amazon EC2

### Issue
I'm attempting to download a Docker image tarball from a private S3 bucket. I'm running Nomad on an Amazon EC2 instance with a suitable IAM role which allows downloading the file directly using the aws CLI. If I configure the task as follows:

```hcl
task "test-image-task" {
  driver = "docker"

  config {
    image = "test-image:1.0.0"
    load  = "test-image.tar"
  }

  artifact {
    source = "bucket-name.s3.amazonaws.com/test-image.tar"
  }

  resources {
    cpu    = 500
    memory = 1024
  }
}
```

This downloads the file properly, however, it extracts the `test-image.tar` file once downloaded, as described in #12063. This results in an error indicating that the tarball cannot be found:

```
    2023-07-05T17:13:03.336Z [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=11f3ceb1-aa8b-50d5-dbc7-b87bc014bea4 task=test-image-task error="unable to open image archive: open /opt/nomad/data/alloc/11f3ceb1-aa8b-50d5-dbc7-b87bc014bea4/test-image-task/local/test-image.tar: no such file or directory"
```

In this state, Nomad is able to download the file from S3, however, since [go-getter is extracting the archive automatically]( https://github.com/hashicorp/go-getter#unarchiving), the Docker image is unable to be loaded.

However, if I apply the workaround described in #12063, altering the job definition to contain the `archive = false` option as follows:

```hcl
task "test-image-task" {
  driver = "docker"

  config {
    image = "test-image:1.0.0"
    load  = "test-image.tar"
  }

  artifact {
    source = "bucket-name.s3.amazonaws.com/test-image.tar"

    options {
      archive = false
    }
  }

  resources {
    cpu    = 500
    memory = 1024
  }
}
```

The download now fails with the following message:

```
    2023-07-05T17:28:53.793Z [DEBUG] client.artifact: get: source=bucket-name.s3.amazonaws.com/test-image.tar destination=local/
    2023-07-05T17:28:53.932Z [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: AccessDenied: Access Denied"
    2023-07-05T17:28:53.932Z [ERROR] client.artifact: sub-process: OUTPUT="\tstatus code: 403, request id: JDKED5XXXXXXXXXXXX, host id: XXXXXX"
```

It seems like adding the `archive = false` option breaks the S3 authentication somehow.

To ensure that the issue is specific to S3 URLs, I created a presigned URL to the same S3 resource and replaced the artifact source with the `https` presigned URL. With the presigned URL, the artifact is downloaded properly, is not unarchived, and is loaded into Docker successfully.

### Reproduction steps

Attempt to download a Docker image tarball from S3 using IAM role.

#### Expected Result

Artifact should be downloaded with or without the `archive = false` option.

#### Actual Result

Artifact fails to download with 403 error.

**Comment by devashishTaneja** [comment]
@tgross Can I take up this issue?

**Comment by tgross** [comment]
@devashishTaneja you're welcome to. But fair warning we haven't really had a chance to investigation and triage this yet and it's entirely possible there's a bug in the upstream [go-getter](https://github.com/hashicorp/go-getter) library rather than in Nomad.

**Comment by devashishTaneja** [comment]
Understood @tgross

**Comment by sgerace** [comment]
I've been playing with this over the last few days, and I finally found a workaround that may help during investigation. It seems like if I add `mode = "file"` to the artifact definition, the file is now downloaded successfully, even with `archive = false`. In other words, this definition works in my scenario:

```hcl
task "test-image-task" {
  driver = "docker"

  config {
    image = "test-image:1.0.0"
    load  = "test-image.tar"
  }

  artifact {
    source = "bucket-name.s3.amazonaws.com/test-image.tar"
    mode   = "file"

    options {
      archive = false
      filename = "test-image.tar"
    }
  }

  resources {
    cpu    = 500
    memory = 1024
  }
}
```

My current theory is that since the permissions that I've set in S3 allow for getting the object, but nothing else, the 403 I'm seeing may be related to a difference in how go-getter is getting the object under different scenarios. For completeness, the permissions in S3 are equivalent to the following:

```
{
  Action = [
    "s3:GetObject"
  ],
  Effect = "Allow",
  Resource = [
    "arn:aws:s3:::bucket-name/*"
  ]
}
```

Examining the [go-getter S3 code](https://github.com/hashicorp/go-getter/blob/main/get_s3.go), I noticed several places where ListObjects is called before GetObject, this made me wonder if perhaps _without_ the `mode = "file"` flag, it was trying to first query for the object before actually getting it. This might explain the 403 I was seeing when I added `archive = false` if, in that scenario, it causes go-getter to utilize one of the branches where the object is queried first, which it doesn't have permission to do. It still doesn't explain why go-getter would change its behavior in that way due to an option that _should_ [be removed before making the request to S3](https://github.com/hashicorp/go-getter#unarchiving), but hopefully this helps track down the underlying issue.

**Comment by lgfa29** [comment]
Hi everyone 👋 

After some investigation I believe everything is working as expected. If `artifact.mode` is not specified, Nomad will set go getter to use `ClientModeAny`:
https://github.com/hashicorp/nomad/blob/437941816c6b84f4b756f694fe42cb028ff50e65/client/allocrunner/taskrunner/getter/util.go#L76-L85

In this mode, go-getter asks the getter about the appropriate mode to be used:
https://github.com/hashicorp/go-getter/blob/c12e42f9c2a92e05cc134fcc24891b3c190826ec/client.go#L231-L235

The S3 getter then needs to figure out if the given path is a prefix or an exact file, and it does so by first listing all objects in the path:
https://github.com/hashicorp/go-getter/blob/c12e42f9c2a92e05cc134fcc24891b3c190826ec/get_s3.go#L53-L73

If the `file` mode is used explicitly, than this logic is skipped the the S3 getter downloads the object directly:
https://github.com/hashicorp/go-getter/blob/main/get_s3.go#L163-L183

Perhaps one action item would be to update our [docs](https://developer.hashicorp.com/nomad/docs/job-specification/artifact#mode) to better describe this behaviour and the expected permissions requirements?

**Comment by sgerace** [comment]
@lgfa29, I think your suggestion of updating the docs to better describe this behavior would be very helpful. It was really confusing to me why it worked before adding `archive = false` but once added, I started seeing 403 errors. If I had known that in that case an additional S3 permission was required it would have answered a lot of questions.

The only behavior that still feels a bit "bug-like" to me is the fact that the download does work without `archive = false` but doesn't once that is present. After another glance at the code, I'm guessing that this is caused by the existence of a `decompressor` and that the `mode` in this case is set to `ClientModeFile` here:
https://github.com/hashicorp/go-getter/blob/c12e42f9c2a92e05cc134fcc24891b3c190826ec/client.go#L217 

This would then make the query unnecessary since `ClientModeFile` is assumed.

Again, perhaps it isn't really a bug, but just understanding what permissions are required under the various scenarios would be super helpful. Thanks!

**Comment by lgfa29** [comment]
Thinking about this again, one possible change we could make is modify the `S3Getter` `ClientMode()` method to use the [`HeadObject()`](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.HeadObject) operation first since, I assume, it requires fewer privileges. 

If the path _is_ an object than we return `ClientModeFile` without trying to list the bucket, which requires broader permissions.

@devashishTaneja would you be interested in testing this approach?

**Comment by tgross** [comment]
It looks like this is safe to close out.
