### ISSUE TITLE
Cannot Run Docker Driver as non-root user on system with cgroup v2, but this is not reflected in docs

### ISSUE THREAD

**Issue by morethanunpopular** [hashicorp/nomad#17816]
### Nomad version
```
$ nomad -v
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Operating system and Environment details
```
 sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
```

### Issue
Docker driver docs do not accurately reflect behavior around non-root users and cgroups v2. Per this code block in the fingerprint.go file of the docker driver:

```
        // disable if cgv2 && non-root
        if cgutil.UseV2 && !utils.IsUnixRoot() {
                fp.Health = drivers.HealthStateUndetected
                fp.HealthDescription = drivers.DriverRequiresRootMessage
                d.setFingerprintFailure()
                return fp
        }
```

It seems you cannot run the docker driver if Nomad is running as a non-root user _and_ cgroups v2 are in use. This is not detailed in the [Docker Driver ](https://developer.hashicorp.com/nomad/docs/drivers/docker) documentation. The documentation also issues a warning that the Nomad user should be added to the `docker` group:

```
 If you do not run Nomad as root, make sure you add the Nomad user to the Docker group so Nomad can communicate with the Docker daemon.
 ```

As I understand it, this would work on a system using cgroup v1, but not on one using cgroups v2. I would recommend adding a a qualifier to this section of the documentation stipulating that this will only work if the system is using cgroups v1. 

### Reproduction steps
- Fresh Ubuntu 22.04.2 install
- Install Nomad, and configure to run as non root user with access to the Docker socket
- Start nomad, and the docker driver fingerprint will fail with message like:

```
 2023-07-06T15:20:55.693Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=docker health=undetected description="Driver must run as root"
 ```
 
#### Expected Result
Per documentation, ensuring the user has access to the docker socket should enable a Nomad run as a non-root user to run the docker driver.

#### Actual Result
It is not possible to run Docker containers as a non-root Nomad user on systems running Cgroups v2.

**Comment by tgross** [comment]
Hi @morethanunpopular! We probably need to update the Docker driver docs to point out that you'll need to use the insecure configuration of delegating cgroups v2 to an unprivileged user. See [Rootless Nomad Clients](https://developer.hashicorp.com/nomad/docs/install/production/requirements#rootless-nomad-clients) for more details. 

Generally speaking Nomad client agents must be run as root. See [Running an Agent](https://developer.hashicorp.com/nomad/docs/operations/nomad-agent#running-an-agent):

> Note: If you are running Nomad on Linux, you'll need to run client agents as root (or with sudo) so that cpuset accounting and network namespaces work correctly.

**Comment by morethanunpopular** [comment]
@tgross thanks for the quick clarification, and the link to the other doc. I appreciate it!

**Comment by Kamilcuk** [comment]
Hi, this is an issue. We are not using cpuset and network namespaces, nor bridge networks. The docker driver running as a normal user works perfectly fine with cgroupv1. Is there a specific reason for explicitly disabling it with cgroupv2? Is it possible to disable cgroupv2?

**Comment by Kamilcuk** [comment]
The following really simple patch on top v1.6.2 makes it work with our workflows. Bottom line, it's just disabling "cores" support.

```
--- a/drivers/docker/fingerprint.go
+++ b/drivers/docker/fingerprint.go
@@ -91,7 +91,7 @@ func (d *Driver) buildFingerprint() *drivers.Fingerprint {
        }

        // disable if cgv2 && non-root
-       if cgutil.UseV2 && !utils.IsUnixRoot() {
+       if false && cgutil.UseV2 && !utils.IsUnixRoot() {
                fp.Health = drivers.HealthStateUndetected
                fp.HealthDescription = drivers.DriverRequiresRootMessage
                d.setFingerprintFailure()
--- a/drivers/docker/reconcile_cpuset.go
+++ b/drivers/docker/reconcile_cpuset.go
@@ -15,6 +15,7 @@ import (
        "github.com/hashicorp/go-hclog"
        "github.com/hashicorp/nomad/client/lib/cgutil"
        "github.com/hashicorp/nomad/helper"
+       "github.com/hashicorp/nomad/plugins/drivers/utils"
 )

 const (
@@ -57,7 +58,7 @@ func newCpusetFixer(d *Driver) CpusetFixer {
 // Only runs if cgroups.v2 is in use.
 func (cf *cpusetFixer) Start() {
        cf.once.Do(func() {
-               if cgutil.UseV2 {
+               if cgutil.UseV2 && utils.IsUnixRoot() {
                        go cf.loop()
                }
        })


```

**Comment by tgross** [comment]
> This states that in order to use docker, it is required to use delegated cgroups v2. Yet, with cgroups v1 docker driver works completely fine. What is the underlying issue?

It's required to use delegated cgroups to use non-root Nomad with Docker. Delegating cgroups _works_ but is _insecure_ under cgroups v1, which is why we don't support it.

In any case, as noted above running as non-root is unsupported and building support isn't on the near-term roadmap. I'm going to link to this issue from https://github.com/hashicorp/nomad/issues/13669 for discussions on how we might work on this in the future. If you have more comments on this after having read through that issue in detail, I'd suggest you make comments over in #13669.
