### ISSUE TITLE
Docker driver config does not support array-form command.

### ISSUE THREAD

**Issue by jemc** [hashicorp/nomad#1789]
@### Nomad version
Nomad v0.4.1

### Operating system and Environment details
Ubuntu 14.04 (x86_64)

### Issue

When running a task with docker driver, I expected `config.command` to be specified in the array-of-strings format (which docker calls the "exec form").  Instead I see the following error when running `nomad plan my-job.hcl`:

```
* group: 'my-group', task: 'my-task', config -> field "command" with input ["my-cmd" "arg1" "arg2"] doesn't seem to be of type string
```

The array-of-strings format is more explicit in terms of separations between arguments, and avoids many potential problems with string escaping.  Preferring to use this format where possible is generally regarded as [best practice in the Docker community](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/).

I would expect either format to be accepted by Nomad, or at the very least I would expect a clarification in [the documentation for the Docker task driver](https://www.nomadproject.io/docs/drivers/docker.html) that explains what format(s) are accepted.

### Reproduction steps

Try to `nomad run` or `nomad plan` a job that includes a task with `driver = "docker"` and the following `config` field: 
```hcl
command = ["my-cmd", "arg1", "arg2"]
```

**Comment by dadgar** [comment]
The docs do have the fact that there is an args flag: https://www.nomadproject.io/docs/drivers/docker.html#args

This is the same as all other drivers on Nomad. The docs will have better examples soon with 0.5
