### ISSUE TITLE
Unable to start nomad agent on windows

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/nomad#179]
When i try to run nomad.exe on Windows Server 2012 R2 (64bit) I get an error about docker unix sockets.

```
PS C:\Nomad> .\nomad agent -dev
==> Starting Nomad agent...
==> Error starting agent: client setup failed: driver setup failed: Get http://unix.sock/version: dial unix /var/run/docker.sock: socket: An address incompatible with the requested protocol was used.
```

**Comment by ryanuber** [comment]
Hey @justenwalker,

Sorry about that, we noticed a similar issue on Linux, but unfortunately the fix we made didn't also cover Windows. We'll get this fixed!

**Comment by cbednarski** [comment]
This was fixed in  https://github.com/hashicorp/nomad/pull/225
