### ISSUE TITLE
Job Summary can drift from correct value

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#1790]
## Nomad version

0.5.0 dev and 0.4.1
### Issue

Had 100 instances running, but summary reports 157.
### Reproduction steps

Have a simple service job and alternate count from 1 to 50 and do GC's occasionally.

**Comment by jippi** [comment]
I'm seeing the same for `queued` and the other keys

**Comment by dadgar** [comment]
Closed by https://github.com/hashicorp/nomad/pull/2163
