### ISSUE TITLE
Connection reset by peer using Docker containers via sidecar proxy

### ISSUE THREAD

**Issue by zugs1** [hashicorp/nomad#17951]
### Nomad version
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80

### Consul version
Consul v1.16.0
Revision 192df66a
Build Date 2023-06-26T20:07:11Z

### Operating system and Environment details
Debian 11 on Proxmox VM, 4CPU, 16GB RAM, 300GB disk

### Issue
When creating job with Nomad using 4 Docker containers via sidecar proxy for testing my PHP app, they can't communicate properly. I get "Connection reset by peer", then suddenly it works after 3rd or 4th attempt, then again throws "Connection reset by peer".

### Reproduction steps
All tasks run successfully, I exec into Nginx/PHP container that needs to communicate with Redis, MySQL and Elasticsearch containers over sidecar proxy, but I can't connect immediately. Only after several tries. Then again connection brakes.

#### Expected Result
For example, when I do `redis-cli ping`, I expect `PONG` in return.

#### Actual Result
ERROR: Connection reset by peer.

#### Configurations and errors examples
[consul_server_configuration.txt](https://github.com/hashicorp/nomad/files/12052272/consul_server_configuration.txt)
[nomad_server_configuration.txt](https://github.com/hashicorp/nomad/files/12052273/nomad_server_configuration.txt)
[problem_nomad_elastic.txt](https://github.com/hashicorp/nomad/files/12052274/problem_nomad_elastic.txt)
[problem_nomad_percona.txt](https://github.com/hashicorp/nomad/files/12052275/problem_nomad_percona.txt)
[problem_nomad_redis.txt](https://github.com/hashicorp/nomad/files/12052276/problem_nomad_redis.txt)
[test_job.txt](https://github.com/hashicorp/nomad/files/12052277/test_job.txt)

**Comment by zugs1** [comment]
I failed to mention that I am new at this (still learning) and I wanted to test my app for possible scaling solution later, but this is where I'm stuck.

**Comment by nightwolfz** [comment]
Also newbie here, I had the same issue a few days ago. Try replacing all the port labels with numbers

BAD
```
port     = "https"
```

GOOD
```
port     = 8080
```

It seems that envoy proxy parses the job file to get the ports, sees strings instead of integers and gets confuse.

Also, if you got any health checks, hardcode the port there as well (don't depend on it being inherited from the parent stanza)

**Comment by tgross** [comment]
Hi @zugs1! I've reproduced your jobspec here with some of the extraneous details like `restart` blocks or whatever removed for clarity.

<details><summary>jobspec</summary>

```hcl
job "test_job" {

  group "nginx-php" {

    network {
      mode = "bridge"
      port "https" {
        to     = 443
        static = 8443
      }
    }

    task "nginx-php" {
      driver = "docker"
      config {
        image          = "local_registry/nginx-php-custom:latest"
        ports          = ["https"]
        auth_soft_fail = true
        volumes = [
          "/opt/docker/volumes/nginx/html:/var/www/html"
        ]
      }

      resources {
        cpu    = 1000
        memory = 512
      }
    }

    service {
      name         = "nginx-php"
      tags         = ["nginx", "https"]
      port         = "https"
      provider     = "consul"
      address_mode = "alloc"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "percona"
              local_bind_port  = 3306
            }
            upstreams {
              destination_name = "redis"
              local_bind_port  = 6379
            }
            upstreams {
              destination_name = "elastic"
              local_bind_port  = 9200
            }
          }
        }
      }
    }
  }

  group "db" {

    network {
      mode = "bridge"
      port "mysql" {
        to = 3306
      }
    }

    service {
      name         = "percona"
      tags         = ["percona", "mysql", "database"]
      port         = 3306
      provider     = "consul"
      address_mode = "alloc"

      connect {
        sidecar_service {}
      }
    }

    task "percona" {
      driver = "docker"
      config {
        image          = "percona-8.0.32-24-centos:latest"
        ports          = ["mysql"]
        auth_soft_fail = true
        volumes = [
          "/opt/docker/volumes/db/percona_test:/var/lib/mysql",
          "/opt/docker/volumes/db/percona_test_init:/docker-entrypoint-initdb.d"
        ]
      }

      env {
        MYSQL_ROOT_PASSWORD = "************"
        MYSQL_USER          = "percona"
        MYSQL_DATABASE      = "percona"
        MYSQL_ROOT_HOST     = "localhost"
      }

      resources {
        cpu    = 1000
        memory = 512
      }
    }
  }

  group "redis" {

    network {
      mode = "bridge"
      port "redis" {
        to = 6379
      }
    }

    service {
      name         = "redis"
      tags         = ["redis", "cache"]
      port         = 6379
      provider     = "consul"
      address_mode = "alloc"

      connect {
        sidecar_service {}
      }
    }

    task "redis" {
      driver = "docker"
      config {
        image          = "redis:6"
        command        = "redis-server"
        args           = ["--port", "6379", "--save", "\"\"", "--maxmemory", "512mb", "--maxmemory-policy", "volatile-lru", "--protected-mode", "no"]
        ports          = ["redis"]
        auth_soft_fail = true
      }

      resources {
        cpu    = 1000
        memory = 512
      }
    }
  }

  group "elasticsearch" {

    network {
      mode = "bridge"
      port "elastic_api" {
        to = 9200
      }
    }

    service {
      name         = "elastic"
      tags         = ["elasticsearch", "elastic"]
      port         = 9200
      provider     = "consul"
      address_mode = "alloc"

      connect {
        sidecar_service {}
      }
    }

    task "elasticsearch" {
      driver = "docker"
      config {
        image          = "elasticsearch:8.7.1"
        command        = "elasticsearch"
        args           = ["-Ediscovery.type=single-node", "-Expack.security.enabled=false", "-Expack.security.http.ssl.enabled=false"]
        ports          = ["elastic_api"]
        auth_soft_fail = true

        ulimit {
          memlock = "-1"
          nofile  = "65536"
          nproc   = "8192"
        }
      }

      env {
        ES_JAVA_OPTS = "-Xms512m -Xmx1024m"
      }

      resources {
        cpu    = 1000
        memory = 1500
      }
    }
  }

}
```

</details>

@nightwolfz said:
> Try replacing all the port labels with numbers

Whether this is required depends on the `service.address_mode`. For the [`alloc`](https://developer.hashicorp.com/nomad/docs/job-specification/service#alloc) mode that @zugs1 is using:

> The port field may be a numeric port or a port label specified in the same group's network block.


So I don't see anything obviously wrong here, and if there were I'd expect to see networking fail entirely instead of being intermittent. Something that's not in your diagnostics here is whether the workloads in the containers are actually running. You could have a container that's up and then running ElasticSearch (or whatever) in a way that it's flapping and not able to connect.

Can you check the following things:
* Does `nomad alloc status` show events for the upstream tasks?
* Do the Nomad client logs shows anything, particularly around the Envoy sidecar?

**Comment by tgross** [comment]
We didn't get a response to clarifications on this issue and there's no obvious bug, so I'm going to close it out. Please feel free to reopen if you have more information.
