### ISSUE TITLE
server: join semantics are not exposed via configuration

### ISSUE THREAD

**Issue by macb** [hashicorp/nomad#180]
Similar to how consul offers [flags](https://www.consul.io/docs/agent/options.html#_join) and [config file](https://www.consul.io/docs/agent/options.html#start_join) to have a server join the cluster `nomad` doesn't. Was this an intended deviation?

**Comment by ryanuber** [comment]
@macb this was probably just an oversight for the servers. In Nomad the client's don't need to join the gossip pool, so only the server nodes should need these options. We should add them, though. Thanks!

**Comment by ketzacoatl** [comment]
I am really appreciative for the flexibility and simplicity inherent in Consul's leader election, and the lack of the same semantics in Nomad makes deploying Nomad leaders to AWS auto-scaling groups much difficult than Consul. (I would welcome any suggestions - in case I am missing something obvious).

To be more clear: the current setup with Consul makes it possible to easily give Consul an arbitrary list of IPs, and set it up to continually retry/reload/restart until Consul succeeds to elect a leader.

There is a bit of a discussion on these topic on the list: https://groups.google.com/d/msg/nomad-tool/PXH0rQK_7sM/zQMP3mRIDwAJ

**Comment by poll0rz** [comment]
+1

**Comment by dadgar** [comment]
#527 addresses this!

**Comment by ketzacoatl** [comment]
\o/
