### ISSUE TITLE
`job plan` output missing diff on `scaling` block

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#18008]
When a `nomad job plan` results in an update, the diff between the old and new is shown even if the update is an in-place update (one that doesn't replace the allocation). For example, and update to an `update` block looks like this:

```
$ nomad job plan httpd.nomad.hcl
+/- Job: "httpd"
+/- Task Group: "web" (1 in-place update)
  +/- Update {
        AutoPromote:      "false"
        AutoRevert:       "false"
        Canary:           "0"
        HealthCheck:      "checks"
        HealthyDeadline:  "300000000000"
    +/- MaxParallel:      "1" => "2"
        MinHealthyTime:   "30000000000"
        ProgressDeadline: "600000000000"
      }
      Task: "http"
...
```

But when changes are made to the `scaling` block, they're not reported in the diff even though the scheduler correctly identifies an in-place update:

```
$ nomad job plan httpd.nomad.hcl
+/- Job: "httpd"
+/- Task Group: "web" (1 in-place update)
  Task: "http"

...
```

This issue was raised internally and the above outputs are from near the `HEAD` of `main`. Not sure which versions are impacted but likely to be from whenever we first introduced scaling.

**Comment by nvanthao** [comment]
Hi @tgross ,

I would like to work on this bug. Please let me know if you have any concern.

**Comment by lgfa29** [comment]
Hi @nvanthao 👋 

Thank you for the interest! I don't think there's any specific concerns here, and your assessment seems correct. Feel free to work on a PR to fix this and let us know if you need any help 🙂

**Comment by nvanthao** [comment]
Thanks @lgfa29 I'm working on this now and will update us with the PR later.
