### ISSUE TITLE
Nomad doesn't account for distinct CNI address when scheduling tasks with static ports

### ISSUE THREAD

**Issue by deverton** [hashicorp/nomad#18064]
### Nomad version

Nomad 1.5.6

### Operating system and Environment details

Linux using the Cilium CNI plugin.

### Issue

The Nomad scheduler doesn't seem to account for the CNI assigning distinct IPs to an allocation. In this sort of setup, it should be fine to schedule the same task multiple times on the same host as the CNI plugin will allocate a distinct IP meaning that the static port won't collide with the host or other allocations.

May be related to https://github.com/hashicorp/nomad/issues/12256#issuecomment-1091732805

### Reproduction steps

Deploy the below job definition on a cluster running Cilium (or adapt to an equivalent that would assign a unique IP to each allocation).

#### Expected Result

Both tasks come up listening on port 80 on their CNI assigned IP address.

#### Actual Result

```
Dimension network: reserved port collision www=80 exhausted on 1 nodes
```

### Job file (if appropriate)

```hcl
job "sameport" {
  type      = "service"
  namespace = "network"

  constraint {
    attribute = "${attr.plugins.cni.version.cilium-cni}"
    operator  = "is_set"
  }

  group "group1" {

    network {
      mode = "cni/cilium"

      port "www" {
        static = 80
      }
    }

    task "task1" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "${NOMAD_PORT_www}", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = <<EOF
                        <h1>Hello from group1, Nomad!</h1>
                        <ul>
                          <li>Task: {{env "NOMAD_TASK_NAME"}}</li>
                          <li>Group: {{env "NOMAD_GROUP_NAME"}}</li>
                          <li>Job: {{env "NOMAD_JOB_NAME"}}</li>
                          <li>Metadata value for foo: {{env "NOMAD_META_foo"}}</li>
                          <li>Currently running on port: {{env "NOMAD_PORT_www"}}</li>
                        </ul>
                      EOF
        destination = "local/index.html"
      }
    }
  }

  group "group2" {

    network {
      mode = "cni/cilium"

      port "www" {
        static = 80
      }
    }

    task "task2" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "${NOMAD_PORT_www}", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = <<EOF
                        <h1>Hello from group2, Nomad!</h1>
                        <ul>
                          <li>Task: {{env "NOMAD_TASK_NAME"}}</li>
                          <li>Group: {{env "NOMAD_GROUP_NAME"}}</li>
                          <li>Job: {{env "NOMAD_JOB_NAME"}}</li>
                          <li>Metadata value for foo: {{env "NOMAD_META_foo"}}</li>
                          <li>Currently running on port: {{env "NOMAD_PORT_www"}}</li>
                        </ul>
                      EOF
        destination = "local/index.html"
      }
    }
  }
}
```

**Comment by jrasell** [comment]
Hi @deverton and thanks for raising this issue. In the job specification you are using `port.static` in each of the groups which is assigning the same static host port to each allocation. In the event the two allocations are placed on the same client, this will indeed conflict as they are also using the same network mode.

[`port.static` docs](https://developer.hashicorp.com/nomad/docs/job-specification/network#static):
> Specifies the static TCP/UDP port to allocate. If omitted, a dynamic port is chosen. We do not recommend using static ports, except for system or specialized jobs like load balancers.

If the allocations do not require the same static port, I would suggest using dynamic mapped ports which would look similar to that detailed below. Otherwise, it would be possible to ensure each allocation is not placed on the same client, and therefore doesn't conflict by using [job constraints](https://developer.hashicorp.com/nomad/docs/job-specification/constraint).
```
port "www" {
  to = 80
}
```

**Comment by deverton** [comment]
@jrasell it may be a bit of an edge case but in this particular scenario there are no host ports being consumed by the static port declaration. Each allocation is being given a unique IP within the CNI network so there is no contention over the port. Ideally we should be able to place multiple tasks on the same host in this configuration, but as Nomad is not aware of the CNI network, it treats them as consuming host ports.

Setting the port with `to = 80` as you described does work, but even there, Nomad is allocating an unneeded port from the host. It's not aware of the CNI configuration so assumes it needs to portmap from the host.
