### ISSUE TITLE
'default' host_network isn't found when same interface is specified under named host_network

### ISSUE THREAD

**Issue by kevinschoonover** [hashicorp/nomad#18097]
### Nomad version
Output from `nomad version`
```
> nomad version
Nomad v1.6.1
```

### Operating system and Environment details
Debian 11 x86

### Issue
consider the following config.hcl
```hcl
# config.hcl
client {
  network_interface = "tailscale0"

  host_network "tailscale" {
    interface = "tailscale0"
  }

  host_network "public" {
    interface = "wlan0"
  }
}
```

whenever you would schedule the following job 

```hcl
# job.hcl
job "docs" {
  datacenters = ["dc1"]

  group "example" {
    network {
      port "http" {}
    }
    task "server" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo"
        ports = ["http"]
        args = [
          "-listen",
          ":5678",
          "-text",
          "hello world",
        ]
      }
    }
  }
}
```

you would see `* Constraint "missing host network \"default\" for port \"http\"": 1 nodes excluded by filter` because the 'default' host_network alias is being replaces with 'tailscale'.

I submitted https://github.com/hashicorp/nomad/pull/18096 which will properly append the `default` alias. Please let me know if there are any questions or things I can add!

**Comment by tgross** [comment]
Good debugging! I was able to reproduce this on a multi-homed machine and it doesn't repro if any of the elements are missing here, so I think you're on the right track. Review incoming for your PR shortly.
