### ISSUE TITLE
Yeah, docker however is the only driver that requires a service to be running.

### ISSUE THREAD

**Issue by airtonix** [hashicorp/nomad#18124]
Yeah, docker however is the only driver that requires a service to be running.

_Originally posted by @dadgar in https://github.com/hashicorp/nomad/issues/696#issuecomment-228380899_

For now... but what about in future?

**Comment by jrasell** [comment]
Hi @airtonix, I am not sure I understand the question. If it relates to drivers which require running services, then Nomad's task driver plugin subsystem allows anyone to write and use a task driver plugin. If it relates to the slightly obtuse message, then we have https://github.com/hashicorp/nomad/issues/17324 to track improving the UX.

**Comment by airtonix** [comment]
It was merely to highlight that the message should in fact be better and mention Docker.

Not everyone will know that it's the only one or that it blah blah blah.
