### ISSUE TITLE
Documentation misleading around Docker task driver and command/args handling

### ISSUE THREAD

**Issue by donovanmuller** [hashicorp/nomad#1813]
### Nomad version

Nomad v0.4.1

### Operating system and Environment details

Ubuntu 14.04.3 LTS - Vagrant managed VirtualBox instance

### Issue

With regards the Docker task driver.
The documentation mentions that the [`args` option](https://www.nomadproject.io/docs/drivers/docker.html#args) can only be used in conjunction with the [`command` option](https://www.nomadproject.io/docs/drivers/docker.html#command).

>  (Optional) A list of arguments to the optional command. **If no command is present, args are ignored**. References to environment variables or any interpretable Nomad variables will be interpreted before launching the task. For example: ...

However, passing just the `args` option does actually pass the arguments into the container.
See below using the `example.nomad` from invoking `nomad init` and then modifying with another image:

`example.nomad`
```
...
                task "redis" {
                        driver = "docker"
                        config {
                                image = "springcloud/spring-cloud-deployer-spi-test-app:1.0.3.RELEASE"
                                port_map {
                                        db = 8080
                                }
                                args = ["--server.port=8081"]
                        }

                        service {
                                ...
```

after scheduling job with `nomad run example.nomad` and inspecting the container:

```
vagrant@hashistack:~$ docker ps
CONTAINER ID        IMAGE                                                          COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
8762ee4734d8        springcloud/spring-cloud-deployer-spi-test-app:1.0.3.RELEASE   "java -jar /maven/spr"   19 seconds ago      Up 17 seconds       10.0.2.15:37145->8080/tcp, 10.0.2.15:37145->8080/udp   redis-bc501ef9-4cc8-6c2c-b06b-5685aa85bf7c

vagrant@hashistack:~$ docker inspect 8762ee4734d8
[
    {
        "Id": "8762ee4734d8d8284df5308daf48e7656c507567cbb76554db30ba63a5c2c16a",
        "Created": "2016-10-14T12:31:14.812440673Z",
        "Path": "java",
        "Args": [
            "-jar",
            "/maven/spring-cloud-deployer-spi-test-app-1.0.3.RELEASE-exec.jar",
            "--server.port=8081"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16747,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-10-14T12:31:15.229466393Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
...
```

the args (`"--server.port=8081"`) are indeed passed in without specifying the `command` option.

If this is expected, the *documentation* should be updated to reflect the fact that `args` does not have to be used with `command`. The fact that we don't need a `command` is in my opinion a good thing! Please don't "fix" the current behaviour if `args` was not intended to be used without `command` 😄 .

### Job file

```
job "example" {
	region = "vagrant"

	constraint {
		attribute = "${attr.kernel.name}"
		value = "linux"
	}

	update {
		stagger = "10s"
		max_parallel = 1
	}

	group "cache" {
		restart {
			attempts = 10
			interval = "5m"
			delay = "25s"
			mode = "delay"
		}

		task "redis" {
			driver = "docker"

			# Custom image
			config {
				image = "springcloud/spring-cloud-deployer-spi-test-app:1.0.3.RELEASE"
				port_map {
					db = 8080
				}
				args = ["--server.port=8081"]
			}

			service {
				name = "${TASKGROUP}-redis"
				tags = ["global", "cache"]
				port = "db"
				check {
					name = "alive"
					type = "tcp"
					interval = "10s"
					timeout = "2s"
				}
			}

			resources {
				cpu = 500 # 500 MHz
				memory = 256 # 256MB
				network {
					mbits = 10
					port "db" {
					}
				}
			}
		}
	}
}
```

**Comment by dadgar** [comment]
Hey! Yeah it was an error in documentation! Has already been fixed on master: https://github.com/hashicorp/nomad/blob/master/website/source/docs/drivers/docker.html.md

The new docs will come up with Nomad 0.5
