### ISSUE TITLE
datadog telemetry

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1815]
Hi!

It would be nice if nomad could emit telemetry in datadog statsd format ( https://docs.datadoghq.com/guides/dogstatsd/ ) 

example: `users.online:1|c|@0.5|#country:china`

**Comment by jippi** [comment]
Seems like @armon already got DataDog support in the metrics library? 

https://github.com/armon/go-metrics/blob/master/datadog/dogstatsd.go :)

**Comment by tanveergill** [comment]
Hi @jippi,

I tried the datadog telemetry config: https://www.nomadproject.io/docs/agent/configuration/telemetry.html#datadog

With this config I expected the host info to be encoded in dogstatsd tags format for these metrics: https://www.nomadproject.io/docs/agent/telemetry.html#host-metrics). But the metrics seem exactly the same as when using the statsd config.

Can you please help me understand if I am doing something wrong?

This is the config I used for testing:
```
{ "server": {
        "enabled": true,
        "bootstrap_expect": 3
    },
    "telemetry": {
        "statsd_address": "127.0.0.1:8125"
    },
    "datacenter": "netsil-data-center",
    "region": "us-west",
    "data_dir": "/nomad/data/",
    "bind_addr": "0.0.0.0",
    "advertise": {
        "http": "127.0.0.1:4646",
        "rpc": "127.0.0.1:4647",
        "serf": "127.0.0.1:4648"
    },
    "enable_debug": true }
```

nomad version: `0.5.0`

Best,
Tanveer

**Comment by jippi** [comment]
@tanveergill i moved on and did this project instead; https://github.com/seatgeek/statsd-rewrite-proxy

it will take the normal consul/nomad statsd, and rewrite on the fly to statsd metrics as i would expect.. proper tagged metrics seem to be a bit out timeline wise still for hashi projects :)

**Comment by tanveergill** [comment]
thanks @jippi!
