### ISSUE TITLE
[UI] Services with variables in their name don't show properly in the UI

### ISSUE THREAD

**Issue by SamMousa** [hashicorp/nomad#18164]
This issue could be related to: #17109

### Nomad version
v1.6.1

### Operating system and Environment details
Linux

### Issue
I'm using some job files that expose a service with a variable in the name: `${NOMAD_JOB_NAME}`
This works well, the service is exposed in the API and discovery, for example, Traefik works properly.

In the UI however I'm seeing no allocations for the service.
This is the screenshot from inside an allocation (`/ui/alllocations/{uuid}`:
![image](https://github.com/hashicorp/nomad/assets/547021/2363267f-5ab7-4886-a1b0-98c3ee58d524)

Note that this is correct, other than the name which did not get replaced.

However when I go to the job services (`/ui/jobs/{job-name}@{namespace}/services:
![image](https://github.com/hashicorp/nomad/assets/547021/a12277e3-e196-4316-b3f6-4269c82a5b43)

### Reproduction steps
Create a job that exposes a service and use `"${NOMAD_JOB_NAME}"` for the service name.

#### Expected Result
It should properly display in the UI.

#### Actual Result
It doesn't show allocations at the job level.

**Comment by SamMousa** [comment]
Also confirmed that just changing the service name to the literal value of the job name resolves the issue in the UI.

**Comment by schmichael** [comment]
Thanks for the bug report @SamMousa. This is likely due to us interpolating service names on the client, but there's no reason we couldn't interpolate static values such as job name on the server to fix issues like this.

**Comment by lgfa29** [comment]
I think this is a duplicated of #9741, so I'm going to close this one. Feel free to add a 👍 or more comments and details there, or let us know if you think this is a different problem and we can reopen it.

Thanks for the report!
