### ISSUE TITLE
Add idPrefixTemplate parameter to job dispatch API documentation

### ISSUE THREAD

**Issue by mmb** [hashicorp/nomad#18173]
### Proposal
Please add the `idPrefixTemplate` parameter to the API docs at https://developer.hashicorp.com/nomad/api-docs/jobs#dispatch-job. It works fine but you need to read source code to figure out how to use it.

**Comment by jhyx2022** [comment]
> ### Proposal
> Please add the `idPrefixTemplate` parameter to the API docs at https://developer.hashicorp.com/nomad/api-docs/jobs#dispatch-job. It works fine but you need to read source code to figure out how to use it.

can you share how to use it in the API? I thought it's only possible in the CLI.

**Comment by mmb** [comment]
I added the `idPrefixTemplate` field to the  job dispatch request JSON and it did prefix the job with it.

**Comment by jhyx2022** [comment]
> idPrefixTemplate

Thank you!

**Comment by jhyx2022** [comment]
> I added the `idPrefixTemplate` field to the job dispatch request JSON and it did prefix the job with it.

Thank you!

**Comment by lgfa29** [comment]
Oh nice find @mmb. I didn't even know about this option since it's a fairly new community contribution 😄 

I opened #18225 to add this value and also fix some other things in this endpoint.

**Comment by lgfa29** [comment]
Documentation is now updated:
https://developer.hashicorp.com/nomad/api-docs/jobs#idprefixtemplate
