### ISSUE TITLE
[question] Nomad release binary for linux_arm not on consistent location inside .zip?

### ISSUE THREAD

**Issue by mafonso** [hashicorp/nomad#1818]
This is a minor thing but can be annoying when trying to use configuration management tools to deploy to multiple architectures.

The nomad binary for Linux Arm is not located on the root of the released .zip file like for all other architectures but rather on under a `linux_arm` or `linux_arm64` directory. 

Consistency on the binary location would make it easier to use the same generic configuration management code to install to multiple architectures, like is the case with `consul`.

**Comment by dadgar** [comment]
Ah sorry about that. The last time we built it was manually so it was a mess up. Will get it right for the next release 👍
