### ISSUE TITLE
[question] How can I run a background process inside raw_exec command?

### ISSUE THREAD

**Issue by kimh** [hashicorp/nomad#1821]
I want to run a background process in raw_exec command. Here is an example of my config.

```
task "long-running" {
              driver = "raw_exec"

              config {
                command = "bash"
                args = ["-c", "(sleep 5; echo hi) &", "while true; do date; sleep 1; done"]
              }
.....
```

As you can see, I want to run `(sleep 5; echo hi)` in background while `while true; do date; sleep 1; done` keeps running. However, it seems the job finishes once `(sleep 5; echo hi) &` is executed and the loop is never run. Below is an example of log and alloc-status. As you can see, job has been completed right after sleep. Is this possible?

(My final goal is placing timeout for main docker command so that after certain sleep, I can kill the container: `i.g. bash -c "(sleep 3600; docker stop $CONT_ID) & docker start --attach $CONT_ID`)

Thanks!

**logs**

```
➜  picard-services git:(CIRCLE-397) ✗ nomad logs e3566bcf long-running
HI
```

**alloc-status**

```
ID            = e3566bcf
Eval ID       = 433200cd
Name          = long-running.long-running[0]
Node ID       = 33eaa7c1
Job ID        = long-running
Client Status = complete

Task "long-running" is "dead"
Task Resources
CPU     Memory  Disk     IOPS  Addresses
20 MHz  10 MiB  300 MiB  0

Recent Events:
Time                   Type        Description
10/17/16 22:11:54 JST  Terminated  Exit Code: 0
10/17/16 22:11:49 JST  Started     Task started by client
10/17/16 22:11:49 JST  Received    Task received by client
```

### Nomad version
`Nomad v0.4.1`

### Operating system and Environment details
Running on Docker 1.12.

**Comment by jippi** [comment]
@kimh why do you want to run it in the background? if you fork the process, nomad will not handle the process.. I use raw_exec a lot, and letting the process run in foreground is way way easier and more sane.

I would wrap it into a non-inline bash script, will make those things easier :)

**Comment by kimh** [comment]
>  if you fork the process, nomad will not handle the process.

Thanks, I wanted to know if this is the case. Now I have a solution with`timeout` command. It's still inline script but does what I wanted to archive.
