### ISSUE TITLE
Error running docker from inside a nomad-backed container (0.5.0)

### ISSUE THREAD

**Issue by cprenzberg** [hashicorp/nomad#1824]
Hi guys,

In order to try out the volumes and docker driver logging feautures, I decided to give 0.5 a spin. I compiled it from source (master branch)

```
git clone git@github.com:hashicorp/nomad.git
cd nomad
vagrant up
vagrant ssh -c 'make bootstrap && make dev && make bin'
```

This builds a nomad artifact: **nomad-0.5-dev**
If filing a bug please include the following:

### Nomad version

```bash
ubuntu@nomad-client-172-20-4-36:~$ nomad version
Nomad v0.5.0-dev ('f0806dceffd5370494598934205de54cbca57ab0')
```

### Operating system and Environment details
Ubuntu 14.04 on AWS

### Issue

I started the container using a volume mapping of the docker binary from the host into the container....since I would like to build dockers within my docker container. You can see the volume spec below (Job file).

When I get into the container and try to run the docker command, I get the following error:

```bash

root@arangodb:/# docker                                                                                                                                                                            
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
```

Any of the Nomad engineers able to give a hint as to the problem?

Thanks!

### Job file

```hcl

job "arangodb" {

  region = "europe"
  
  datacenters = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  
  type = "service"
  
  constraint {
    attribute = "${attr.kernel.name}"
    value = "linux"
  }
  
  update {
    stagger = "10s"
    
    max_parallel = 1
  }
  
  group "arangodb" {
    count = 3
    
    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }
    
    task "arangodb" {
    
      driver = "docker"
      
      config {
        image = "arangodb:3.0.10"
        
        hostname = "arangodb.service"
        
        port_map {
          db = 8529
        }
        
        logging {
          type = "syslog"
        }
        
        labels {
          foo = "bar"
          zip = "zap"
        }
        
        volumes = [ "/usr/bin/docker:/usr/bin/docker", "/var/run/docker.sock:/var/run/docker.sock" ]
      }
      
      service {
        name = "arangodb"
        tags = ["europe", "graph"]
        port = "db"
        check {
          name = "alive"
          type = "tcp"
          interval = "10s"
          timeout = "2s"
        }
      }
      
      env {
          IAM_ROLE = "arn:aws:iam::123456789012:role/ContainerRoleName"
          ARANGO_NO_AUTH = 1
      }
      
      resources {
        cpu = 300 # Mhz
        memory = 768 # MB
        
        network {
          mbits = 1

          # Request for a dynamic port
          port "db" {
          }
        }
      }
    }
  }
}
```

**Comment by dadgar** [comment]
Looks like docker is dynamically linked and you need those in the docker container.

$ ldd /usr/bin/docker
        linux-vdso.so.1 =>  (0x00007ffee73eb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007eff9586a000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007eff95660000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007eff9529b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007eff95a88000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007eff95097000)

Going to close since not really a Nomad issue. Feel free to use the email list or Gitter for questions
