### ISSUE TITLE
[feature] Evaluations should include a timestamp for created / started / stopped (start / stop)

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1826]
Hi,

Would be nice if evaluations would include a start/stop time (or simply just a time for when it was processed) 

This would also be useful to be have exposed in `/v1/evaluations`

**Comment by dadgar** [comment]
Can you clarify the ask? The allocation has a create time (https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L3103) and also has the task events that mark when it was received by the client, run, stopped, etc. (https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L3088)

If this answers your question would you mind closing the issue.

**Comment by jippi** [comment]
@dadgar i'm a retard, updated to be evaluations instead of allocations :)

**Comment by dadgar** [comment]
Okay going to close in favor of #1772
