### ISSUE TITLE
[documentation] Fix TBD. Insert a link to redis

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18270]
![image](https://github.com/hashicorp/nomad/assets/139780495/ba1f81ae-7768-4027-b196-cc22713c4aa9)

**Comment by lgfa29** [comment]
Thanks for the heads up  @EugenKon. I'm not sure where that was supposed to link to, so I'm checking with the team for more details 😄

**Comment by mikenomitch** [comment]
Hey sorry, this was me a while ago and I intended to write a clustered redis pack and never got around to it. I'll just remove the link in here: https://github.com/hashicorp/nomad-pack-community-registry/pull/156

**Comment by mikenomitch** [comment]
Going to close this out as it's not technically an issue in this repo. @EugenKon, thank you for the catch!
