### ISSUE TITLE
Nomad can't fingerprint ARM64 Ampere (Hetzner Cloud)

### ISSUE THREAD

**Issue by Cottand** [hashicorp/nomad#18272]
### Nomad version
Nomad v1.6.1
### Operating system and Environment details

Hetzner's CAX21 VPS, Linux NixOS 23.05

```
# lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  BIOS Vendor ID:       QEMU
  Model name:           Neoverse-N1
    BIOS Model name:    NotSpecified  CPU @ 2.0GHz
...
```
### Issue

`attrs.cpu.frequency`  not set

### Reproduction steps

Run nomad client on an ARM Ampere processor (in my case I am using Hetzner's CAX21 VPS offering)
and run `nomad node status -verbose -self | grep cpu`.

#### Expected Result

I expected `attrs.cpu.frequency  = 3000` ish (3.0 GHz according to [this article](https://www.tomshardware.com/news/ampere-altra-max-128-core-priced))

So then I expected `attrs.cpu.totalcompute  = 12000`

#### Actual Result

`nomad node status -verbose -self | grep cpu`:
```
cpu.arch                         = arm64
cpu.modelname                    = Neoverse-N1
cpu.numcores                     = 4
cpu.reservablecores              = 4
cpu.totalcompute                 = 1000
```
`cpu.frequency` not set, therefore `cpu.totalcompute` is wrong

**Comment by Cottand** [comment]
For whoever comes bumps into this - it can be mitigated [by setting `cpu_total_compute`](https://developer.hashicorp.com/nomad/docs/configuration/client#cpu_total_compute)

**Comment by Cottand** [comment]
seeing the exact same here https://github.com/hashicorp/nomad/issues/14055#issuecomment-1209352332 - this is possibly a duplicate then

**Comment by lgfa29** [comment]
Thanks for the report @Cottand!

ARM CPU fingerprinting has indeed been tricky for us due a lack of standardization as to where to retrieve this information from. The label `theme/platform-arm` has a few other items discussing similar problems:
https://github.com/hashicorp/nomad/issues?q=label%3Atheme%2Fplatform-arm

Would you mind checking if you have the command `dmidecode` installed and what it outputs? And are you running the Nomad client agent as `root`?

**Comment by Cottand** [comment]
I did not have it installed, but here is the output:
```
#  dmidecode | grep Processor -A21
Processor Information
	Socket Designation: CPU 0
	Type: Central Processor
	Family: Other
	Manufacturer: QEMU
	ID: 00 00 00 00 00 00 00 00
	Version: NotSpecified
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2000 MHz
	Current Speed: 2000 MHz
	Status: Populated, Enabled
	Upgrade: Other
	L1 Cache Handle: Not Provided
	L2 Cache Handle: Not Provided
	L3 Cache Handle: Not Provided
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 4
	Core Enabled: 4
	Thread Count: 1
	Characteristics: None
```
QEMU I guess is expected since I am using a VPS. Not sure if those `2000 MHz` are what I am actually getting ([this source says 2.5 GHz](https://en.wikichip.org/wiki/arm_holdings/microarchitectures/neoverse_n1), [this one 3 GHz](https://www.tomshardware.com/news/ampere-altra-max-128-core-priced) ??) but maybe Hetzner sets a different clock speed...

I was not planning on running it as root but if that helps with the fingerprinting I can do. Would doing that and keeping `dmidecode` help?

**Comment by lgfa29** [comment]
Oh sorry, I just realized that I was looking at code in `main` and forgot we recently [refactored CPU fingerprinting](https://github.com/hashicorp/nomad/pull/18146) to improve situations exactly like this, and that's where `dmidecode` detection was added 🤦 

Before #18146 Nomad would only use the file system to detect CPU information, which as pointed out in the comment you posted, does not work well with ARM.

So the `1000 Mhz` is a default fallback that is coming from here:
https://github.com/hashicorp/nomad/blob/515895c7690cdc72278018dc5dc58aca41204ccc/client/fingerprint/cpu.go#L19-L23

I'm building a custom binary from `main` that include the latest code, would you be able to try it and see if it fixes the problem? The artifacts will be available in this page once the build completes.
https://github.com/hashicorp/nomad/actions/runs/5933203729

**Important note: This is a development binary and show not be used in a production cluster.**

> I was not planning on running it as root but if that helps with the fingerprinting I can do.

Yeah, Nomad clients are expected to run as root:
https://developer.hashicorp.com/nomad/docs/install/production/requirements#user-permissions

**Comment by Cottand** [comment]
@lgfa29 sorry for the late reply - here is what you asked for:
```bash
# ./nomad -version
Nomad v1.6.2-dev
BuildDate 2023-08-21T20:09:24Z
Revision 14a38bee7bc4386e74157f6a99f3db7382d7e6a5+CHANGES

# ./nomad node status -verbose -self | grep cpu
cpu.arch                  = arm64
cpu.frequency.efficiency  = 2000
cpu.frequency.performance = 0
cpu.numcores              = 4
cpu.numcores.efficiency   = 4
cpu.numcores.performance  = 0
cpu.reservablecores       = 4
cpu.totalcompute          = 8000
cpu.usablecompute         = 8000
```

**Comment by lgfa29** [comment]
Thanks for testing the preview binary, it seems like the new code is able to detect `cpu.totalcompute` properly so you won't need to set `cpu_total_compute` manually once the fix is released.

Is this more in line with what you were expecting?

**Comment by Cottand** [comment]
I expected more than 2GHz per core (2.5 or 3) but until I confirm this with Hetzner this is much better yes

**Comment by lgfa29** [comment]
Let us know if you hear anything back. I don't think there's much we can do about it since 2GHz is what's being reported by the OS.

The new CPU fingerprint code will ship on Nomad 1.7.0 so I'm going to close this issue for now, but let us know if you have any other problems!
