### ISSUE TITLE
[documentation] Typo: network.mode -> network_mode

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18276]
It seems you made typo here:
![image](https://github.com/hashicorp/nomad/assets/139780495/64cbbf2a-ff8b-49f4-8674-03b636b8b823)

**Comment by lgfa29** [comment]
Hi @EugenKon 👋 

The text is actually correct, it is referring to the `mode` parameter inside the `network` block:
https://developer.hashicorp.com/nomad/docs/job-specification/network#mode

I've opened  https://github.com/hashicorp/nomad/pull/18277 to clarify this.
