### ISSUE TITLE
[documentation] Provide a link to job placement example

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18282]
### Proposal
This is not clear how to make use this filter

![image](https://github.com/hashicorp/nomad/assets/139780495/a7d1c098-7bca-4d9f-9c28-87cfee71959d)

### Attempted Solutions
It would be nice to understand how to use this option with job placement

**Comment by EugenKon** [comment]
I can not find example and can not understand why my job specification without any constraints are not run by nomad client when `node_class` was configured. I suppose when there is no constraint at `job` then this job could be executed by anyone.

How to reproduce the issue: configure value `node_class` for nomad client.

**Comment by EugenKon** [comment]
Probably `node_class` could be used [here](https://developer.hashicorp.com/nomad/docs/job-specification/constraint), but it is not clear how.

**Comment by lgfa29** [comment]
That's right, `node_class` can be used as attribute in [`affinity`](https://developer.hashicorp.com/nomad/docs/job-specification/affinity) and [`constraint`](https://developer.hashicorp.com/nomad/docs/job-specification/constraint) rules. I've opened #18288 to expand the docs on this.  

Thanks for the report!

**Comment by EugenKon** [comment]
Cool, you are so fast! Until document is fixed, may you @lgfa29 please provide a quick small example here?

**Comment by lgfa29** [comment]
What are you trying to trying to accomplish? 

You can write a `constraint` rule like this in your jobs to restrict allocations to only be placed on clients with a given `node_class`:

```hcl
job "example" {
  constraint {
    attribute = "${node.class}"
    value     = "prod"
  }
  # ...
}
```

But this will not prevent other jobs from running on those clients, it only applies to this specific jobs. If you want to fully restrict a set of clients to run specific jobs then you would need to create a [node pool](https://developer.hashicorp.com/nomad/docs/concepts/node-pools).

Check https://developer.hashicorp.com/nomad/docs/concepts/scheduling/placement for more details on how allocations are placed and how you can adjust the results.

**Comment by EugenKon** [comment]
Thank you for an example.

>What are you trying to trying to accomplish?

I am trying to understand why job was filtered, when job does not have any constraints configured. I just added `node_class` configuration option to the `nomad_client.hcl` configuration file.

**Comment by EugenKon** [comment]
Probably `nomad_client.hcl` should have an option, which restrict this agent to take jobs without explicit constraint.

eg.

nomad_client.hcl
```nomad_client.hcl
 node_class = "prod"
 restrict_class_jobs = "true"   # this will tell nodes for production run only jobs with "prod" constraint configured. Otherwise it is allowed for this node to run any jobs
```

job.nomad.hcl
```
job "example" {
  constraint {
    attribute = "${node.class}"
    value     = "prod"
  }
  # This job could be taken by agent with "prod" node_class
}
```

```
job "example" {
  # Actual behaviour: This job will not be taken by agent with "prod" node_class
  # Expected behaviour: This job will be taken by any agent, because no constraints were configured
}
```

**Comment by lgfa29** [comment]
> # Actual behaviour: This job will not be taken by agent with "prod" node_class

This is not correct, a job that doesn't specify any constraint will not be filtered by node class. If you're seeing nodes being filter from placement then it's likely that something else is causing the placement failure. For example, in https://github.com/hashicorp/nomad/issues/18281 the problem is the missing host volume.

It's really hard to understand the problem you're experiencing without examples, would you be able to provide full reproduction assets, like job files and agent configuration you are using?

**Comment by EugenKon** [comment]
> This is not correct, a job that doesn't specify any constraint will not be filtered by node class

So then I do not know the source of problem. I will post full configuration files next time. Thank you for explanations about these missed parts of documentation.

**Comment by lgfa29** [comment]
Yeah, in general it's better to describe what you're doing and the error you're receiving rather than trying to suggest a fix.

Without proper reproduction steps it's hard to understand the problem and provide help.
