### ISSUE TITLE
[documentation] Clarify 'global' value for `region` in job section

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18283]
### Proposal
![image](https://github.com/hashicorp/nomad/assets/139780495/b6ead88c-f082-4a7e-bebc-0f0d75f45e14)

I configured my nomad clients to use 'my-region'. Bug jobs with 'global' region still are run by those clients. 
It seems like 'global' match anything, eg. '*', but this is not documented.

### Use-cases
Clarify behaviour of configuration vlaues

**Comment by EugenKon** [comment]
Describe like this: https://developer.hashicorp.com/nomad/docs/job-specification/job#datacenters

**Comment by lgfa29** [comment]
The `global` region is the default value used if no region is specified, it doesn't have a special meaning other than being the default.

> I configured my nomad clients to use 'my-region'. Bug jobs with 'global' region still are run by those clients.

Were these clients always in `my-region` or did you change their change after running them without region? If that's the case, it's not recommended to modify an agent region without clearing its state: https://developer.hashicorp.com/nomad/docs/configuration#region

Clients in a region different from the servers are not able to join the cluster. You would see log lines like these:
```
2023-08-22T13:59:36.544-0400 [ERROR] client.rpc: error performing RPC to server: error="rpc error: No path to region" rpc=Node.Register server=127.0.0.1:4647
```

And jobs are not able to register in regions different than the servers, you would receive an error like this:

```console
$ nomad run example.nomad.hcl
Error submitting job: Unexpected response code: 500 (No path to region)
```

**Comment by EugenKon** [comment]
'global' looks special, it would be nice if 'example' string was used for example purpose.

**Comment by lgfa29** [comment]
`global` is not a special value other than being the default if `region` is not specified in the job, and the default value is what we represent in parenthesis throughout our documentation.
