### ISSUE TITLE
[documentation] Add description how to enable consul DNS in Docker containers when consul listens :8600 port

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18305]
### Proposal
I checked [this](https://github.com/hashicorp/nomad/issues/12894#issuecomment-1169488006) solution and it works as expected. It would be nice if this will be added to official documentation [here](https://learn.hashicorp.com/tutorials/consul/dns-forwarding#systemd-resolved-setup)

**Comment by EugenKon** [comment]
Hi, @jrasell . It seems I do not understand your question about Nomad reference link.

**Comment by jrasell** [comment]
@EugenKon the final link in your description points to a Consul tutorial.

> I checked https://github.com/hashicorp/nomad/issues/12894#issuecomment-1169488006 solution and it works as expected. It would be nice if this will be added to official documentation [here](https://learn.hashicorp.com/tutorials/consul/dns-forwarding#systemd-resolved-setup)

**Comment by EugenKon** [comment]
Yes, it does.

**Comment by slonopotamus** [comment]
I believe people just want a clear explanation on how to configure Nomad+Consul so that docker tasks running in Nomad can utilize Consul DNS, regardless of whether it is documented in Nomad or Consul docs.

**Comment by EugenKon** [comment]
Ah, It seems I got. I mess up repositories. This issue should be opened in `hashicorp/consul` repository.

**Comment by EugenKon** [comment]
And I agree with @slonopotamus . People just need a clear description how to utilize Consul DNS for tasks running in Nomad. The link I have posted points to Consul documentation, because that is most close part of documentation to the topic. And it would be nice if that part could be improved.

**Comment by EugenKon** [comment]
My final solution is:
/etc/systemd/resolved.conf.d/dns.conf
```
[Resolve]
DNSSEC=false
DNS=127.0.0.1:8600

DNSStubListener=yes
DNSStubListenerExtra=172.17.42.1

Domains=~consul
```

/etc/docker/daemon.json
```
{
  "bip": "172.17.42.1/16",
  "dns-search": ["our.domain.example.com"],
  "dns": ["172.17.42.1"]
}
```
