### ISSUE TITLE
exec driver should check if a binary is executable to improve user experience

### ISSUE THREAD

**Issue by pearkes** [hashicorp/nomad#1832]
### Nomad version

Nomad v0.4.1
### Operating system and Environment details

```
Linux ip-0-0-0-0 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
### Issue

```
10/17/16 00:40:28 UTC Not Restarting Error was unrecoverable 
10/17/16 00:40:28 UTC Driver Failure failed to start task 'example' for alloc '930dd478-874a-f17f-af58-f0d000dd301d': fork/exec local/example: exec format error 
10/17/16 00:40:16 UTC Downloading Artifacts Client is downloading artifacts 
10/17/16 00:40:16 UTC Received Task received by client
```

It would be awesome if the above error message could be clearer, something like: "The command executable does not have the proper permissions to be executed."
### Reproduction steps
1. Use an artifact that is not executable and run it under exec
2. It should render the above error message
3. `chmod +x` the artifact, re-run
4. It should now start without issue

**Comment by jippi** [comment]
This goes for `raw_exec` too :)

**Comment by dadgar** [comment]
Hey we already do that: https://github.com/hashicorp/nomad/blob/master/client/driver/executor/executor.go#L624-L646

I just confirmed by shipping a non-executable binary and it had the correct behavior. Also the error you are seeing makes me thing you are running a binary that was not compiled for the correct operating system `exec format error`.

Can you confirm?

**Comment by dadgar** [comment]
Going to close as explained by previous comment that we do this already.
