### ISSUE TITLE
[documentation] Provide more informative example

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18331]
### Proposal
[This example](https://mpolinowski.github.io/docs/DevOps/Hashicorp/2022-05-29-hashicorp-nomad-with-nginx-loadbalancer/2022-05-29/) 
```
    task "nginx" {
      driver = "docker"
      config {
        image = "nginx"
        port_map {
          http = 8080
        }
        port_map {
          https = 443
        }
        volumes = [
          "custom/default.conf:/etc/nginx/conf.d/default.conf"
        ]
      }
      template {
        data = <<EOH
          server {
            listen 8080;
            server_name nginx.service.consul;
            location /nginx {
              root /local/data;
            }
          }
        EOH
        destination = "custom/default.conf"
      }
      # consul kv put features/demo 'Consul Rocks!'
     template {
        data = <<EOH
        Nomad Template example (Consul value)
        <br />
        <br />
        {{ if keyExists "features/demo" }}
        Consul Key Value:  {{ key "features/demo" }}
        {{ else }}
          Good morning.
        {{ end }}
        <br />
        <br />
        Node Environment Information:  <br />
        node_id:     {{ env "node.unique.id" }} <br/>
        datacenter:  {{ env "NOMAD_DC" }}
        EOH
        destination = "local/data/nginx/index.html"
      }
```

is more informative in compare to [your example](https://developer.hashicorp.com/nomad/docs/job-specification/template#template-destinations)
```
task "task" {
  driver = "docker"

  config {
    image = "redis:6.0"
    mount {
      type   = "bind"
      source = "local"
      target = "/etc/redis.d"
    }
  }

  template {
    destination = "local/redis.conf"
  }
}
```

### Use-cases
That example describes how to mount one file, for example if container already has that directory and we do not want replace it completely, like that is done in your example.

**Comment by jrasell** [comment]
Hi @EugenKon thanks for raising this issue. My concern with replacing or including the example you provided is that it might be too much for novice/new users to understand. It would be more suited to a guide due to the additional requirements and we already have an [NGINX guide](https://developer.hashicorp.com/nomad/tutorials/load-balancing/load-balancing-nginx) available.

**Comment by jrasell** [comment]
@EugenKon thanks for the clarification, adding additional examples makes sense to me.

**Comment by tgross** [comment]
Doing a little issue cleanup. Looks like this use case is covered by [Template Destinations](https://developer.hashicorp.com/nomad/docs/job-specification/template#template-destinations)
