### ISSUE TITLE
Nomad leaves empty files when mount was unseccessful

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18334]
### Nomad version
# nomad --version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc

### Operating system and Environment details
# uname -a
Linux ip-172-31-29-15 5.19.0-1029-aws #30~22.04.1-Ubuntu SMP Thu Jul 13 17:17:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Issue
When I start nomad task with configure docker driver and mounts and if this start was unsuccessful (for example because of configuration syntax error), then nomad leaves zero sized files in the place of mount.

#### Expected Result
When task is healthy I can cat generated file `cat /data/wi-nginx.1/tmp/nginx/internal`. This is Ok, because file `/opt/nomad/data/alloc/28ae7def-9cd4-81f8-a8c0-c647019c19f1/nginx-task/custom/internal.conf` is mounted and available from target.
But when container was not started, the file `/data/wi-nginx.1/tmp/nginx/internal` should not exist, because container is not alive and file is not mounted.

#### Actual Result
Zero size file `internal` exists

### Job file (if appropriate)

nomad_client

```
  host_volume "vol-nginx" {
    path      = "/data/wi-nginx.1/tmp"
    read_only = false
  }

```

task
```
job "nomad-nginx" {
  datacenters = ["dc1"]
  type = "service"

  group "backend" {
    count = 1

    network {
      # mode = "host"
      port "http" {
        static = 80
        to     = 80
      }
      port "https" {
        static = 443
        to     = 443
      }
      port "status" {
        static = 4876
        to     = 4876
      }
      port "internal" {
        static = 4877
        to     = 4877
      }
    }

    # https://developer.hashicorp.com/nomad/tutorials/stateful-workloads/stateful-workloads-host-volumes#create-the-job-file
    volume "nginx-volume" {
      type      = "host"
      read_only = false
      source    = "vol-nginx"
    }

    task "nginx-task" {
      driver = "docker"

      # https://developer.hashicorp.com/nomad/docs/drivers/docker
      config {
        force_pull = true
        image = "ourrepo/wi-nginx:my-latest"
        ports = ["http", "https", "status", "internal"]

        sysctl = {
            "net.ipv4.ip_local_port_range" = "15000 65000"
            "net.ipv4.tcp_fin_timeout" = 30
            "net.core.somaxconn" = 1024
            "net.ipv4.tcp_max_syn_backlog" = 2048
        }

        volumes = [
          "custom/internal.conf:/tmp/nginx/internal",
          "custom/walk-inside.com.conf:/tmp/nginx/walk-inside.com",
        ]

      }

      volume_mount {
        volume      = "nginx-volume"
        destination = "/tmp"
        read_only   = false
      }

      env {
        SERVICE_80_NAME = "wi-nginx"
        SERVICE_80_ID = 1
      }

      template {
        # source = nginx.tpl
        data = <<CONF
dsfsdf
        CONF
        destination = "custom/internal.conf"
      }

      template {
        data = <<CONF
          F233
        CONF
        destination = "custom/walk-inside.com.conf"
      }


      service {
        tags = ["wi-nginx-service"]
        name = "wi-nginx"
        port = "http"

        provider = "consul"
          check {
            type     = "http"
            path     = "/"
            interval = "5s"
            timeout  = "5s"
            method   = "GET"
          }
      }
    }
  }
}
```

**Comment by EugenKon** [comment]
Also if we mount something inside host volume, then this is not visible on host system. I suppose that that should be visible.

**Comment by apollo13** [comment]
> Also if we mount something inside host volume, then this is not visible on host system. 

You mean you are literally executing "mount" inside the container to put a submount into the host volume? Then it should probably not show up on the host given that the default mount propagations are private iirc.

**Comment by EugenKon** [comment]
@apollo13 , no. I did not execute 'mount' at all. I did via nomad's configuration files like I showed above.

**Comment by tgross** [comment]
What's happening here is that the host `volume_mount` and `volumes` configuration all get written together as a `MountConfig` that we pass to the task driver and then it's up to the Docker what happens. So you're mounting a host volume and mounting files _on top_ of that mount point.

I'm a little surprised this works at all, but if so it's just a quirk of the order in which Docker mounts volumes. This is totally out of Nomad's control, and it seems like a really bad idea for us to try to "clean up" files in a host volume that we don't actually control.

**Comment by EugenKon** [comment]
>I'm a little surprised this works at all,

@tgross I found that solution in Nomad documentation. You should not be surprised :D I just complain that on host system I see zero length files. Yeah, probably that is belongs to Docker.

**Comment by tgross** [comment]
> @tgross I found that solution in Nomad documentation. You should not be surprised :D

:laughing:
