### ISSUE TITLE
DefaultLogConfig should be overridable by Nomad client options

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/nomad#1833]
The defaults are currently hard-coded to 

```
// DefaultLogConfig returns the default LogConfig values.
func DefaultLogConfig() *LogConfig {
    return &LogConfig{
        MaxFiles:      10,
        MaxFileSizeMB: 10,
    }
}
```

it would be nice to be able to override these defaults at the Nomad agent level, rather than having to override them in every job.

Maybe this belongs in a more general "nomad job defaults should be able to be set as client-level defaults" instead, not sure.  It probably makes less sense to have global defaults for things like how many CPU and memory resources jobs need, but for logging, it seems like this should be configurable since the recommendation is to run log forwarders anyway, so would be nice to centralize the logic of how many logs you keep per task.

**Comment by dadgar** [comment]
I don't think it makes sense to have them set at the client because then a job can have different behavior across different hosts.

My current thoughts on this are with ACLs you could apply restrictions and defaults. So you could have an ACL policy that defaults the priority or for example the logging config :)

What do you think

**Comment by holtwilkins** [comment]
Hmm yeah, that could make sense.  So, a job file would say which ACL policy it belongs to like it will with a vault policy, is that the idea?  So, you would say it's using `app-default-ACL` or something, which could have default priority and logging values?

**Comment by dadgar** [comment]
Yep exactly. If you are okay with it I think we can close this issue. It is something that we will be tackling down the line and is much broader than just log config.

**Comment by holtwilkins** [comment]
Alright sure, sounds good.
