### ISSUE TITLE
Nomad setup in two different regions

### ISSUE THREAD

**Issue by sdinakar85** [hashicorp/nomad#1834]
### Nomad version
Nomad v0.3.2

### Operating system and Environment details
Linux version 4.2.0-27-generic (buildd@lcy01-23) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016

### Issue
Created nomad servers to have 2 different regions (say pime-reg and dr-reg), 3 servers in each region, total of 6 servers. Basically we are following `Each DC being its own region approach` . We made sure that each server in one region knows about the servers in other regions by using the param `-retry-join=Server2.prime-reg -retry-join=Server3.prime-reg -retry-join=Server1.dr-reg -retry-join=Server2.dr-reg retry-join=Server3.dr-reg`. By doing this we expected nomad server-members to list all the servers (which it did) and have 2 leaders elected, one in `prime-reg` and the other in `dr-reg` but we saw only one leader elected, it was in `prime-reg`. Is this the expected behaviour? How wan we make sure to have 2 leaders elected across 2 regions , please advise

Output nomad server-members

```
nomad server-members
Name                    Address      Port  Status  Leader  Protocol  Build  Datacenter  Region
mo-XXXX.dr-reg     XXXXXX   4648  alive   false   2         0.3.2  dr          dr-reg
mo-XXXX.dr-reg     XXXXXX  4648  alive   false   2         0.3.2  dr          dr-reg
mo-XXXX.dr-reg     XXXXXX   4648  alive   false   2         0.3.2  dr          dr-reg
mo-XXXX.prime-reg  XXXXX  4648  alive   false   2         0.3.2  primary     prime-reg
mo-XXXX.prime-reg  XXXXX  4648  alive   true    2         0.3.2  primary     prime-reg
mo-XXXX.prime-reg  XXXXX  4648  alive   false   2         0.3.2  primary     prime-reg

```

**Comment by dadgar** [comment]
Hey,

There should be two leaders, one per region. Though from that output it is not possible to see what is happening. I would look at `nomad agent-info` and the logs for the servers in the region without a leader.

**Comment by vrenjith** [comment]
Thanks @dadgar 
So from a configuration side, mentioning all the servers in both regions is the right way to configure nomad, right?

**Comment by dadgar** [comment]
@vrenjith Yes that should work just fine

**Comment by dadgar** [comment]
@vrenjith That should work just fine!

**Comment by sdinakar85** [comment]
@dadgar Thank you for your reply.  Nomad was able to elect 2 leaders after I cleaned up the `data` folder on the servers. Wanted to know what are the exact steps that we need to follow when we have to achieve this scenario of having 2 leaders over 2 regions and a set of clients serving them. Do we have to clean up the `data` folder on clients too?

```
nomad server-members
Name                    Address      Port  Status  Leader  Protocol  Build  Datacenter  Region
mo-0c1236ee3.dr-reg     10.9.47.76   4648  alive   false   2         0.3.2  dr          dr-reg
mo-1a6a606fe.dr-reg     10.9.45.211  4648  alive   true    2         0.3.2  dr          dr-reg
mo-a299a2b48.dr-reg     10.9.45.77   4648  alive   false   2         0.3.2  dr          dr-reg
mo-01f69a85a.prime-reg  10.9.46.251  4648  alive   false   2         0.3.2  primary     prime-reg
mo-0b9b3ac79.prime-reg  10.9.44.229  4648  alive   true    2         0.3.2  primary     prime-reg
mo-a471fa5c0.prime-reg  10.9.46.129  4648  alive   false   2         0.3.2  primary     prime-reg
```

**Comment by dadgar** [comment]
You should bring up the servers with `bootstrap_expect = 3` in the case you will have 3 in each region and then a server join from one region to the other.

Cleaning up the data_dir shouldn't be needed. I am guessing the raft/peers.json file contained peers that it shouldn't have and deleting the `data_dir` fixed it.

**Comment by sdinakar85** [comment]
@dadgar Without the cleanup of `data_dir` i was unable to get this working. The raft/peer.json do not contain any peers other than the same host(I can confirm this, as I had read one of your comments mentioning the same for another issue) .
