### ISSUE TITLE
[cli] Allow "role" updates to tokens

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#18354]
Currently, you can pass in both `-policy` and `-role-name` on `nomad acl token create`, but you can only modify `-policy` when running `nomad acl token update`.

The Nomad CLI should give users the ability to update roles for a given user token.

- [acl_token_create.go](https://github.com/hashicorp/nomad/blob/main/command/acl_token_create.go#L45-L53)
- [acl_token_update.go](https://github.com/hashicorp/nomad/blob/main/command/acl_token_update.go#L38-L40)

**Comment by Kartik1397** [comment]
Hi @philrenaud @jrasell, Can I work on this?

**Comment by jrasell** [comment]
Hi @Kartik1397 of course; although as you're not an internal member I cannot explicitly assign you the issue. If you have any questions, please reach out.

**Comment by Kartik1397** [comment]
Hi @jrasell, I've submitted a pull request to introduce the ACL token update feature. I would greatly appreciate your review and any feedback you might have when you have the chance.

Thank you!

**Comment by 0xMALVEE** [comment]
is this issue fixed already? it's valid and I can take it for my first contribution? 
Or it's not needed.

**Comment by burnerlee** [comment]
@jrasell may I take up this issue and raise a PR?

**Comment by burnerlee** [comment]
@jrasell I've added a PR for the same

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/18532
