### ISSUE TITLE
[documentation] Mention that we can run multiple tasks for one job

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18355]
### Issue

Here https://developer.hashicorp.com/nomad/docs/job-specification was not mentioned that we can configure multiple tasks for one group or multiple groups for one job. Other parts of documentation also does not mention that 'task' could be used multiple times inside group: https://developer.hashicorp.com/nomad/docs/job-specification/task
I found this information useful: https://discuss.hashicorp.com/t/how-to-configue-multitask-job-in-one-file/19466

#### Expected Result
So one `nomad job run XXX` will run multiple services at once.

#### Actual Result
By mistake I configured multiple jobs and run them individually. It's long

**Comment by jrasell** [comment]
Hi @EugenKon, the first link you posted includes the following sentence in the first paragraph which seems to cover what you've requested:

> Each job file has only a single job, however a job may have multiple groups, and each group may have multiple tasks. Groups contain a set of tasks that are co-located on a machine.

**Comment by EugenKon** [comment]
@jrasell weird. You are right. Probably I did not read that, because I just saw a graph:
```
job
  \_ group
        \_ task
```

It would be nice to update it like next:
```
job
  \_ group
  |     \_ task
  |     \_ task
  \_ group
        \_ task
        \_ task
```

**Comment by EugenKon** [comment]
> are co-located on a machine.

Could you please improve this a bit: `are co-located on the same host`
