### ISSUE TITLE
Local SI tokens are created on Nomad leader not on Nomad server on datacenter used for deployment

### ISSUE THREAD

**Issue by pakoselo** [hashicorp/nomad#18458]
### Nomad version
Output from `nomad version`
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc

### Operating system and Environment details
Ubuntu 22.04 on every server/client
Deployed 3 different datacenters, with full service mesh on top of the consul version 1.16.1 and using ACL. It is a federated deployment. Every datacenter has one server and 2 nodes (except one, which has only 1 node and it is on different network, see below), with service mesh gateway deployed on every datacenter. 
dc1: 1 consul server, gateway and nomad server, 2 clients
dc2: 1 consul server, gateway and nomad server, 2 clients
dc3: 1 consul server, gateway and nomad server, 1 client
Servers and gateways are using public and private IPs. Clients are only on private IPs. 
dc1: private addresses consul and nomad server/gateway: 192.168.10.132, nodes: 192.168.10.183, 192.168.10.59
dc2: private addresses consul and nomad server/gateway: 192.168.10.44, nodes: 192.168.10.136, 192.168.10.41
dc3: private addresses consul and nomad server/gateway: 192.168.20.129, node: 192.168.20.186

### Issue
The problem is that after deploying the job (using nomad job run) let's say on the datacenter 1, it will create SI tokens as a local (which is correct), but they are created on the nomad leader (which can be elected on any datacenter). So in case that the leader is from 2nd or 3rd datacenter, the envoy proxies can't start as they are not able to see the SI tokens as they are created as local ones and the service deployment fails. The consul is complaining about "rpc error making call: token does not exist: ACL not found", which is of course correct behavior, but not what I want to achieve. In case that the leader will be elected on the 1st datacenter, everything goes fine, because the envoy proxies will see these tokens and start correctly. 

### Reproduction steps
Deploy 2/3 datacenters in full service mesh scenario on top of the consul and try to deploy any service on the datacenter, which server is not a leader of the nomad servers.

#### Expected Result
The SI tokens will be created as local on the datacenter nomad server, where the job is deployed.

#### Actual Result
The SI tokens are always created on the nomad leader regardless the datacenter to which the job is deployed.

### Job file (if appropriate)

```
job "backend" {
  # choose the one, which has not the nomad leader elected
  datacenters = ["dc1"]

  group "backend1" {
    network {
      mode = "bridge"
      port "http" {
        to = 80
      }
    }
    service {
      name = "whoami1"
      port = "http"
      tags = [
        "traefik.enable=true",
        "traefik.http.routers.whoami1.rule=Host(`whoami1.example.com`)",
        "traefik.http.routers.whoami1.entrypoints=http",
      ]
      connect {
        sidecar_service {
          tags = [
            "traefik.consulcatalog.connect=false",
          ]
        }
      }
    }
    # Note: For increased security the service should only listen on localhost
    # Otherwise it could be reachable from the outside world without going through connect
    task "whoami" {
      driver = "docker"
      config {
        image = "containous/whoami:v1.5.0"
      }
    }
  }
  group "backend2" {
    network {
      mode = "bridge"
      port "http" {
        to = 80
      }
      port "https" {
        to = 443
      }
    }
    service {
      name = "whoami2"
      port = "http"
      tags = [
      tags = [
        "traefik.enable=true",
        "traefik.http.routers.whoami2.rule=Host(`whoami2.example.com`)",
        "traefik.http.routers.whoami2.entrypoints=http, https",
        "traefik.http.routers.whoami2.tls=true",
      ]
      connect {
        sidecar_service {
          tags = [
            "traefik.consulcatalog.connect=false",
          ]
        }
      }
    }

    # Note: For increased security the service should only listen on localhost
    # Otherwise it could be reachable from the outside world without going through connect
    task "whoami" {
      driver = "docker"
      config {
        image = "containous/whoami:v1.5.0"
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

...
Sep 12 07:43:52 node3 nomad[2155341]:     2023-09-12T07:43:52.378Z [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=8b01a1b2-dde2-fb49-ce65-95fe1373b5ec task=connect-proxy-whoami1 error="prestart hook \"envoy_bootstrap\" failed: error creating bootstrap configuration for Connect proxy sidecar: exit status 1; see: <https://www.nomadproject.io/s/envoy-bootsttrap-error>
...

**Comment by tgross** [comment]
Hi @pakoselo! I think I'm having a little trouble following your issue here, and I think there might be some confusion around terminology (not your fault; this is a historically confusing thing):

* A Nomad [region](https://developer.hashicorp.com/nomad/docs/glossary#regions) is a single cluster: the Nomad control plane + a set of Nomad clients assigned to [datacenters](https://developer.hashicorp.com/nomad/docs/glossary#datacenters) in that region. Nomad regions can be federated but each region is a single Raft cluster with one leader.
*  In Consul, each cluster is a "datacenter": the Consul control plane + a set of Consul agents. This is an unfortunate bit of historical confusion between the names.
* Each Nomad region can support one Consul datacenter.

When an allocation starts up, the Nomad client makes a request to one of the Nomad servers, which is forwarded to the region's leader. That leader creates the SI token in the Consul datacenter that the region uses. So I think everything is operating as I'd expect to see it here, but you've got multiple Consul datacenters in a single Nomad region, which won't work.

---

As an aside, this workflow is going to change significantly in Nomad 1.7.0 (by default):
* The client will use the allocation's Workload Identity to authenticate to Consul and get the SI token directly, without going thru the Nomad server.
* With Nomad Enterprise, a Nomad region can support multiple Consul datacenters.
* The existing workflow will be available if the new workflow isn't configured, but it'll go away in Nomad 1.9.0.

**Comment by pakoselo** [comment]
Hi Tim

Thanks for your response. I will try to add more information as I still
think that this workflow is not taking every configuration into account.
I have only one global region in the Nomad federated environment and 1
server in every datacenter. Datacenters for Nomad are the same as for
Consul.
Nomad default configuration:

datacenter = "dc1" #changed for every server and client in the datacenters
region="global"

and Nomad server configuration:
...
server {
    enabled = true
    authoritative_region = "global"
    bootstrap_expect = 3
    server_join {
        retry_join = ["REDACTED", "REDACTED"]
        retry_max = 3
        retry_interval = "15s"
    }
}
...

After starting the cluster One of the Nomad servers became the leader:

nomad server members
Name           Address         Port  Status  Leader  Raft Version  Build
 Datacenter  Region
node1.global   REDACTED  4648  alive   false   3             1.6.1  dc1
global
node-1.global   REDACTED  4648  alive   true    3             1.6.1  dc2
global
nx1.global      REDACTED  4648  alive   false   3             1.6.1  dc3
global

and here lies the problem
if I specify that my job (some backend services) should land on dc1, it
will not be deployed successfully, because the SI tokens are created on the
dc2 as local ones and sidecar proxies deployed on dc1 are not able to see
these tokens. Please see below the snippet, that shows that these tokens
are local and they are created on dc2.



[image: image.png]
Once again thanks for your support

> Best Regards
> Martin Šeleng
> =====================
> Institute of Informatics
> Slovak Academy of Sciences
> Dubravska cesta 9
> 845 07 Bratislava
> Slovak Republic
> Tel: +421 (0)2 5941-1256
> Fax: +421 (0)2 5477-1004
> URL: ikt.ui.sav.sk
> E-mail: ***@***.*** ***@***.***>

**Comment by tgross** [comment]
Nomad servers can technically be assigned to datacenters because the `datacenter` config is a top-level config value, but it doesn't mean anything. In Nomad, datacenters are only used for placing workloads on clients, which means the `datacenter` configuration only means something on Nomad client nodes.

But more importantly:
* Nomad datacenters have no relationship at all with Consul datacenters.
* There can be only _one_ Consul datacenter per Nomad region.

You don't have a valid Consul topology with this Nomad cluster. You should have all your Consul agents in the same datacenter.

**Comment by pakoselo** [comment]
Hi Tim

I do not want to open the ticket and get your point about the datacenters
(in Nomad it's just logical view), except this one: "There can be only *one*
Consul datacenter per Nomad region"
When I look for example on this picture:
https://content.hashicorp.com/api/assets?product=tutorials&version=main&asset=public%2Fimg%2Fnomad%2Fproduction%2Fnomad_fault_tolerance.png
there are 3 Consul datacenters per one Nomad region, so why there must be
one Consul datacenter per one Nomad region?

I had 3 different Consul datacenters connected by full servicemesh
gateways. An I want to have one Nomad region over these datacenters. Isn't
it the saem as in the picture?

Thanks in advance

> Best Regards
> Martin Šeleng
> =====================
> Institute of Informatics
> Slovak Academy of Sciences
> Dubravska cesta 9
> 845 07 Bratislava
> Slovak Republic
> Tel: +421 (0)2 5941-1256
> Fax: +421 (0)2 5477-1004
> URL: ikt.ui.sav.sk
> E-mail: ***@***.*** ***@***.***>

**Comment by tgross** [comment]
That image is unfortunately misleading, but the "datacenter" there is the Nomad datacenter. Notice how the 3 Consul servers shown are a leader and 2 followers, which is a single Consul datacenter. That image doesn't look super familiar to me though... what page is it on? I'd like to get it updated.

**Comment by pakoselo** [comment]
Hi Tim

This is the page (and the image):
https://developer.hashicorp.com/nomad/tutorials/enterprise/production-reference-architecture-vm-with-consul#one-region
So the result is that there is no possibility to create one Nomad region
over different Consul datacenters by using the Nomad wan federation.

And thanks for your patience and help

> Best Regards
> Martin Šeleng
> =====================
> Institute of Informatics
> Slovak Academy of Sciences
> Dubravska cesta 9
> 845 07 Bratislava
> Slovak Republic
> Tel: +421 (0)2 5941-1256
> Fax: +421 (0)2 5477-1004
> URL: ikt.ui.sav.sk
> E-mail: ***@***.*** ***@***.***>
