### ISSUE TITLE
Restarted Job from Web UI shows wrong Job Spec

### ISSUE THREAD

**Issue by sevensolutions** [hashicorp/nomad#18454]
### Nomad version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc

### Operating system and Environment details
Ubuntu 22.04

### Issue
Nomad 1.6 brought us the new feature to show and modify the original job spec from the Web UI.
But it seems there is still a bug when restarting a job.

### Reproduction steps
1. Deploy a simple job from the Web UI (see my example below)
2. Navigate to the "Definition" tab and inspect the Job Spec, it shows HCL.
4. Stop the Job in the Web UI, but do not purge it
6. Re-Start the Job from the Web UI
6. Inspect the "Definition" Tab. It now shows the full JSON, instead of HCL.

Maybe someone forgot to also store the original job spec, when "re"-starting a job?

#### Expected Result
The original Job Spec in the Web UI should always show the original definition. Even after a restart.
If it was HCL on the first job submission, it should stay HCL also after restarts.

#### Actual Result
The original Job Spec is only shown after the first start. After a restart, it's shown as JSON.

### Job file (if appropriate)
```hcl
job "nginx-test" {
  datacenters = ["dc1"]

  group "nginx" {
    count = 1

    network {
      port "http" {
        static = 8080
        to = 80
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx"

        ports = ["http"]
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @sevensolutions! This is the same issue as https://github.com/hashicorp/nomad/issues/17806 which was fixed in https://github.com/hashicorp/nomad/pull/18120. That just missed the Nomad 1.6.1 release, but will go out with the next regular release of Nomad 1.6.x.
