### ISSUE TITLE
Nomad provider: health check does not find network label - invalid port "http": port label not found

### ISSUE THREAD

**Issue by mindaugaszilionis** [hashicorp/nomad#18462]
### Nomad version
1.6.1

Hi there,
Its looks like its some kind of bug, how nomad provider check service healthcheck. I am constantly getting "invalid port "http": port label not found". It worked perfectly with consul provider. Http port is defined in network section and actually works well when i remove check section at all or use "on_update" option as "ignore".
My nomad job stanza looks like 

```
job "tacho-authorization-service" { 
  priority = "100"
  datacenters = ["AZ1","AZ2"]
  type = "service"
  spread {
    attribute = "${node.datacenter}"
    weight    = 100
    target "AZ1" {
      percent = 50
    }
    target "AZ2" {
      percent = 50
    }
  }
  group "tacho-authorization-service-group" {
    count = 1
    constraint {
      distinct_hosts = true
    }
    update {
      max_parallel     = 1
      canary           = 1
      min_healthy_time = "30s"
      progress_deadline = "5m"
      healthy_deadline = "4m"
      auto_revert      = true
      auto_promote     = true
    }

    task "tacho-authorization-service" {
      driver = "docker"
      config {
        image = "our_internal_registry/image:tag"
        hostname = "${NOMAD_IP_http}"
        image_pull_timeout = "5m"
      }

      resources {
        cpu    = 1000 # MHz
        memory = 1024 # MB
        memory_max = 1024 # MB

        network {
          port "http" {}
          port "service_jmx" {
            to = 21260
          }
          port "tacho" {
            static = 9003
            to           = 9003
            host_network = "public"
          }
          port "dcs" {
              static = 12001
              to           = 12001
              host_network = "public"
          }
        }
      }

      service {
        name = "tacho-authorization-service"
        provider = "nomad"
        port     = "service_jmx"
        check {
          type     = "http"
          path     = "/admin/health"
          interval = "10s"
          timeout  = "3s"
        }
        check_restart { 
            limit = 1
            grace = "900s"
        }
        tags = [
          "traefik.enable=true"
        ]
      }
    }

    restart {
      attempts = 1
      interval = "15m"
      mode     = "fail"
    }
    reschedule {
      attempts       = 1
      unlimited      = false
      interval       = "8m"
      delay          = "20s"
      delay_function = "exponential"
    }
  }
}
```

invalid port "http": port label not found
![Screenshot from 2023-09-12 16-39-03](https://github.com/hashicorp/nomad/assets/39596189/3a79d84a-12a8-4d59-8317-ebbbc91a71c3)

**Comment by tgross** [comment]
Hi @mindaugaszilionis! You've got the [`network`](https://developer.hashicorp.com/nomad/docs/job-specification/network) block in the wrong scope. It should be in the `group` scope, not in the `group.task.resources` scope. You almost certainly will want to allocate the port in the driver's `config` block as well (see [allocating ports](https://developer.hashicorp.com/nomad/docs/drivers/docker#allocating-ports)).

A very old version of Nomad (<1.0) supported having the `network` block in that scope, so I suspect we're tolerating that on job submission when we should be returning an error for it. We have some old config structs in the jobspec for it that we intended to remove a while back but haven't got around to it yet.

**Comment by mindaugaszilionis** [comment]
Thank you, it helped. had to change location of restart, meta, reshedule, service block too, also in order health check endpoint to be reachable from outside container - 
add   ports = ["http"] in task-> config section
