### ISSUE TITLE
At least raft config settings are ignored when specified in the configuration.

### ISSUE THREAD

**Issue by stswidwinski** [hashicorp/nomad#18493]
### Nomad version
tip

### Operating system and Environment details
Unix

### Issue

The RAFT configuration knobs are simply ignored within the merging logic of the Nomad Server configuration. As a result the knobs are meaningless and the defaults are always present, despite these settings being advertised as working. In detail:

1. Load config correctly parses the raft settings (https://github.com/hashicorp/nomad/blob/main/command/agent/command.go#L237)
2. The merge logic results in a configuration without the raft settings being respected (https://github.com/hashicorp/nomad/blob/main/command/agent/command.go#L253)
3. Because of the merge not taking into account the raft settings (https://github.com/hashicorp/nomad/blob/main/command/agent/config.go#L1918)

The settings ignored are *at least*:

1. https://developer.hashicorp.com/nomad/docs/configuration/server#raft_snapshot_interval
2. https://developer.hashicorp.com/nomad/docs/configuration/server#raft_snapshot_threshold
3. https://developer.hashicorp.com/nomad/docs/configuration/server#raft_trailing_logs

And likely more.

### Reproduction steps

Start a server with the above settings overridden to a non-default value. Attach `dlv` and inspect the configuration. You will notice that these settings are defaulted and any override ignored.

#### Expected Result

Settings work as advertised.

#### Actual Result

Settings being ignored.

**Comment by jrasell** [comment]
Hi @stswidwinski and thanks for raising this issue with the detail and already linked PR.
