### ISSUE TITLE
Reduce reported precision on Nomad UI page for task

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18507]
### Proposal
![image](https://github.com/hashicorp/nomad/assets/139780495/81216080-eacf-4afc-b92f-8f4717e36c62)

Please print 2m 12s. This is hard to read to long number and it is not relevant, because we do not know exact time when event occur.

**Comment by philrenaud** [comment]
Thanks, @EugenKon — makes perfect sense, will look to fix this soon.
