### ISSUE TITLE
NOMAD_ALLOC_INDEX is 0 on all nodes when using system scheduler.

### ISSUE THREAD

**Issue by siffiejoe** [hashicorp/nomad#1851]
### Nomad version

Nomad v0.4.0
### Operating system and Environment details

```
Linux host01 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
### Issue

Two different nodes get the same allocation index (0) when using the system scheduler.
### Reproduction steps

Create a nomad cluster of at least two nodes, copy the following script onto all nodes as `/tmp/x.sh` and run the job script below.

``` sh
#!/bin/sh

while true; do
  echo "NOMAD_ALLOC_INDEX: $NOMAD_ALLOC_INDEX"
  sleep 1
done
```

All (both in my case) print the same allocation index (i.e. 0).
### Job file (if appropriate)

```
job "xxx" {
    type = "system"

    datacenters = ["dc1"]

    task "x" {
    driver = "raw_exec"
    config {
        command = "/tmp/x.sh"
        args = []
    }
    resources {
        memory = 10
    }
    kill_timeout = 10s
    }
}
```

**Comment by dadgar** [comment]
Hey,

This is currently the desired behavior. The allocation index is used to indicate the instance out of a desired count size. System jobs do not have an explicit count but are based more on the size of a the targeted cluster, making the index less informative.

I'm curious what you have in mind for the index. Further there is an associated cost with making it a monotonically increasing counter (need to store additional meta data) and I am not sure of the benefit.

**Comment by siffiejoe** [comment]
I was trying to use the allocation index to get separate host names for each instance via consul. I need this because the service needs host names/addresses of all nodes that are going to be part of the cluster in advance (zookeeper is the culprit). I also want to wait until all instances are up before I start dependent services, and checking for `zk-N.zookeeper.service.consul` is an easy way to do that.

**Comment by jippi** [comment]
I've been helping @smuthali with zookeeper as well, and he got something working out of that, perhaps drop by the gitter channel and give him a poke? :)

**Comment by dadgar** [comment]
@siffiejoe I think you could accomplish that by using `node.unique.id` or `node.unique.name`.

I am going to close this issue as it is desired behavior. Hope you get the help you need from @jippi and @smuthali

Best,
Alex

**Comment by jippi** [comment]
a hack is to have a docker entrypoint that echo ${NOMAD_ALLOC_INDEX} into the required file :)
