### ISSUE TITLE
Docs don't mention that read-only plugin access is required for ACL volumes

### ISSUE THREAD

**Issue by Zygimantass** [hashicorp/nomad#18527]
### Issue

Documentation does not mention that read-only plugin access `plugin { policy = "read" }` is required for ACL volumes (like it does for UI + node / agent read-only access)

**Comment by lgfa29** [comment]
Hi @Zygimantass 👋 

Would you mind expanding a little bit more on what's missing? If possible with a link to the page and a small description of what's missing.

Thanks!

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/20557
