### ISSUE TITLE
Can not execute command with `alloc exec`

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18548]
### Nomad version
```
$ nomad --version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

### Operating system and Environment details
```
Linux ip-172-31-14-184 6.2.0-1011-aws #11~22.04.1-Ubuntu SMP Mon Aug 21 16:27:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue + Reproduction steps + Actual Result

```
nomad alloc exec -task postgres-task 48a14dcd-63e2-e2d0-d31e-2a3ecd4b9240 psql -h 127.0.0.1 -U postgres
Usage: nomad alloc exec [options] <allocation> <command>
```

It looks like nomad counts psql's `-h` flag as its own, but it should not, because this is already <command>
Details are here: https://discuss.hashicorp.com/t/why-i-can-not-execute-command/58421/3

#### Expected Result

Command should be executed.

PS. Looks like if nomad implement `-c` option, then this will break `nomad alloc exec alloc-id` **`bash -c "..."`**

**Comment by Kamilcuk** [comment]
So just use `nomad alloc exec -task postgres-task -- 48a14dcd-63e2-e2d0-d31e-2a3ecd4b9240 psql -h 127.0.0.1 -U postgres`
