### ISSUE TITLE
Implement `nomad start` command

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18558]
### Proposal
Nomad requires access to source of `.hcl` file. This is Ok for first run. But when I stopped job I could be on any different host. This is possible because I have an access token to do this operation. And on this remote host I do not have access to the source of `.hcl` file so I am not able to start job again. Though I can do this via UI:
![image](https://github.com/hashicorp/nomad/assets/139780495/22b5fa5d-3726-4dca-827d-b927f64a8230)

This is possible, because the source was uploaded to Nomad cluster. I believe I can even start specific version:
![image](https://github.com/hashicorp/nomad/assets/139780495/896e24f3-d0cf-4d85-9902-b90b0de72725)

### Use-cases
This command is helpful when I want to restart some task and do not have an access to the source `.hcl` file for this job.

### Attempted Solutions
`nomad start <job-name> <job-version>`

**Comment by tgross** [comment]
Hi @EugenKon! Nomad job specifications are declarative. So when you stop a Nomad job, that specific version of the job is terminal and can never be "restarted", and this aspect of the design is fundamental to how the evaluations are idempotent over the same state in the scheduler. To "restart" a stopped job, you need to push a new version, for which you need a new job specification.

But it turns out we already have a command for the specific workflow you're looking for: `nomad job revert`. This lets you revert to a specific version of the job. For example, let's run a job:

```
$ nomad job run ./jobs/httpd.nomad
==> 2023-09-26T11:03:16-04:00: Monitoring evaluation "498b5693"
    2023-09-26T11:03:16-04:00: Evaluation triggered by job "httpd"
    2023-09-26T11:03:17-04:00: Evaluation within deployment: "ee1dd5ea"
    2023-09-26T11:03:17-04:00: Allocation "7d1bc302" created: node "15d521b8", group "web"
    2023-09-26T11:03:17-04:00: Evaluation status changed: "pending" -> "complete"
==> 2023-09-26T11:03:17-04:00: Evaluation "498b5693" finished with status "complete"
==> 2023-09-26T11:03:17-04:00: Monitoring deployment "ee1dd5ea"
  ✓ Deployment "ee1dd5ea" successful

    2023-09-26T11:03:30-04:00
    ID          = ee1dd5ea
    Job ID      = httpd
    Job Version = 0
    Status      = successful
    Description = Deployment completed successfully

    Deployed
    Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
    web         1        1       1        0          2023-09-26T11:13:28-04:00
```

Then after running `nomad job stop httpd`, the version for the stopped allocations is 0:

```
$ nomad job status httpd
ID            = httpd
Name          = httpd
Submit Date   = 2023-09-26T11:03:16-04:00
Type          = service
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = dead (stopped)
Periodic      = false
Parameterized = false
...

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
7d1bc302  15d521b8  web         0        stop     complete  29s ago  2s ago
```

But we can see the version of the job itself has incremented:

```
$ nomad job inspect httpd | jq '.Job.Version'
1
```

Now we can revert to that version 0 of the job.

```
$ nomad job revert httpd 0
==> 2023-09-26T11:03:49-04:00: Monitoring evaluation "4aa84179"
    2023-09-26T11:03:49-04:00: Evaluation triggered by job "httpd"
    2023-09-26T11:03:49-04:00: Allocation "0ff02ce8" created: node "15d521b8", group "web"
    2023-09-26T11:03:50-04:00: Evaluation within deployment: "75f981cd"
    2023-09-26T11:03:50-04:00: Evaluation status changed: "pending" -> "complete"
==> 2023-09-26T11:03:50-04:00: Evaluation "4aa84179" finished with status "complete"
==> 2023-09-26T11:03:50-04:00: Monitoring deployment "75f981cd"
  ✓ Deployment "75f981cd" successful

    2023-09-26T11:04:03-04:00
    ID          = 75f981cd
    Job ID      = httpd
    Job Version = 2
    Status      = successful
    Description = Deployment completed successfully

    Deployed
    Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
    web         1        1       1        0          2023-09-26T11:14:01-04:00
```

Note that `0ff02ce8` is a brand new allocation. If we check the job status, we can see that the new allocation is on version 2 of the job:

```
$ nomad job status httpd
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
0ff02ce8  15d521b8  web         2        run      running   40s ago    28s ago
7d1bc302  15d521b8  web         0        stop     complete  1m14s ago  47s ago
```

**Comment by bobobo1618** [comment]
Could this be documented somewhere, such as in the `nomad job stop` docs?

**Comment by tgross** [comment]
@bobobo1618 we're actually implementing `nomad job start` as syntactic sugar on `nomad job revert` over in https://github.com/hashicorp/nomad/pull/24150. That'll cover the docs appropriately.
