### ISSUE TITLE
Nomad UI reports that image was downloaded, but actually it come from cache

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18552]
### Nomad version
```
$ nomad --version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

### Operating system and Environment details
```Ubuntu 22.04```

### Issue

![image](https://github.com/hashicorp/nomad/assets/139780495/565947c2-ba52-400e-8273-1ec31a6b58af)

I have `force_pull = false` configured. Once image was already downloaded, but UI continues to report that it redownloading imange, though it does not, because image was cached.

This makes me ambiguous, because I do not suppose to see behaviour like it was configured with `force_pull = true`. 

### Reproduction steps
Configure your task with `force_pull = false`. 
Start task, stop it and start again.

#### Expected Result
For second start I do not expect to see `Downloading image`

#### Actual Result
![image](https://github.com/hashicorp/nomad/assets/139780495/565947c2-ba52-400e-8273-1ec31a6b58af)

### Proposed resolution
Display `Got image from cache` if it came from cache.

**Comment by tgross** [comment]
@EugenKon to be clear, this is not a UI issue but how the task event gets written. You'd see the same behavior if you checked the `nomad alloc status`.

As for the actual feature request, Nomad doesn't pull Docker images itself. It makes a Docker API request and Docker pulls the image or not, depending on its local cache state. We emit the "Downloading image" even before making the API call (so you can see how long it took) but the API response doesn't tell us whether the image was cached or not.
