### ISSUE TITLE
Add time zone data for Windows

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [hashicorp/nomad#18578]
### Proposal

Due to https://github.com/golang/go/issues/38453, specifying time zone for periodic job is actually broken in Windows, which will promptly fail the periodic job:

https://github.com/hashicorp/nomad/blob/20eadc7b296cc81d2c8c01fb15cb74047633788f/api/jobs.go#L897-L903

### Use-cases

For periodic job.

### Attempted Solutions

Use Local time. 

```hcl
periodic {
  cron             = "@hourly"
  time_zone        = "Local"
}
```

**Comment by wizpresso-steve-cy-fan** [comment]
https://github.com/golang/go/issues/38017

There are two ways to do this.

**Comment by lgfa29** [comment]
Thanks for the report @wizpresso-steve-cy-fan!

I've opened https://github.com/hashicorp/nomad/pull/18676 to add the `timetzdata` build flag on Windows so the time zone data is embedded into the binary.
