### ISSUE TITLE
UI: filtering clients on "ready" displays ineligible hosts

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#18593]
### Nomad version
1.6.2

### Operating system and Environment details
Fedora29

### Issue
/ui/clients?state=%5B"ready"%5D shows also ineligible hosts.

### Reproduction steps
Have some hosts ready and ineligible, and filter in UI for ready.

#### Expected Result
Only ready hosts should be shown when filtering for ready hosts.

#### Actual Result
![image](https://github.com/hashicorp/nomad/assets/15679217/6d06f6ff-0f04-4f6a-912f-945d123482a2)

**Comment by philrenaud** [comment]
Hi @Kamilcuk , thanks for raising this. Looking into it now.
