### ISSUE TITLE
Client CPU incorrectly fingerprinted on M1 Mac

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#18602]
### Nomad version

1.6.3-dev (4895d708b438b42e52fd54a128f9ec4cb6d72277)

NOT on 1.6.2

### Operating system and Environment details

M1 mac

### Issue

When I run `nomad agent -dev`, I see 20 Mhz of CPU. Which is a bit less than I have on my laptop. This is particularly bad since others probably couldn't really do local testing of jobs on it easily.

```
nomad node status -verbose -self  | grep cpu

cpu.arch                  = amd64
cpu.frequency             = 2
cpu.modelname             = VirtualApple @ 2.50GHz
cpu.numcores              = 10
cpu.reservablecores       = 0
cpu.totalcompute          = 20
cpu.usablecompute         = 20
```

### Reproduction steps

Have an m1 mac. Run `nomad agent -dev`. Run `nomad node status -verbose -self  | grep cpu`.

#### Expected Result

Get the right CPU amount.

#### Actual Result

Got 20 Mhz

### "Proof" of 1.6.2 working

```
/Users/mike/.asdf/installs/nomad/1.6.2/bin/nomad node status -verbose -self  | grep cpu
cpu.arch                  = arm64
cpu.frequency.efficiency  = 2064
cpu.frequency.power       = 3228
cpu.modelname             = Apple M1 Pro
cpu.numcores.efficiency   = 2
cpu.numcores.power        = 8
cpu.reservablecores       = 0
cpu.totalcompute          = 29952
```

**Comment by philrenaud** [comment]
Just a ntoe: was able to reproduce this consistently, and the reason was **because I'd installed the AMD version of Go on my M1, instead of the ARM version**. Switching versions corrected this for me.

**Comment by shoenig** [comment]
Should be able to see what version is being used with

```
go env | grep GOARCH
```

If that doesn't say `arm64` (not `amd64`) on an M1/M2 you've got the wrong version of Go
