### ISSUE TITLE
When will it be possible to generate a new page for autoscaler plugins

### ISSUE THREAD

**Issue by wrli20** [hashicorp/nomad#18613]
Hi there,

Two weeks ago, I completed a new autoscaler plugin for Ali Cloud and submitted a [PR](https://github.com/hashicorp/nomad/commit/0329393a28a94c70e5470a9d43b8e2d43caf0759). However, there hasn't been any progress in generating a new page for users to discover, which is crucial for open-source contributors.

**Comment by jrasell** [comment]
Hi @wrli20, I have raised the linked PR to get this onto our live website.
