### ISSUE TITLE
[question] Job env variables are not interpolated

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/nomad#1861]
When submitting a job via the API, variables do not seem to be interpolated per my understanding of the docs here https://www.nomadproject.io/docs/jobspec/interpreted.html

### Nomad version
Nomad v0.4.1

### Operating system and Environment details
Linux 4.2.0-35-generic 14.04 Ubuntu x86_64 x86_64 x86_64 GNU/Linux

### Issue
```
Env: {
  NODE_ID: "${node.unique.id}",
  NODE_CLASS: "${nomad.class}",
  HOST_NAME: "${node.unique.name}",
},
```

### Reproduction steps
Post a job via the API with this environment block.

### Nomad Server logs (if appropriate)
None.

### Nomad Client logs (if appropriate)
None.

**Comment by dadgar** [comment]
Can you post your whole job? It worked for me.

Also `${nomad.class}` is incorrect. Should be `${node.class}`

**Comment by justinwalz** [comment]
Ah, user error. Apologies. Will close... but while I've got you on the line (so to speak) can you please clarify the interpolated variable name for `local-ipv4`?

I've tried
HOST_IP1=${unique.local-ipv4}
HOST_IP2=${unique.network.ip-address}
HOST_IP3=${unique.platform.aws.local-ipv4}
HOST_IP4=${node.unique.local-ipv4}
HOST_IP5=${node.unique.network.ip-address}
HOST_IP6=${node.unique.platform.aws.local-ipv4}

mostly taken from https://github.com/hashicorp/nomad/blob/master/client/fingerprint/env_aws.go

**Comment by justinwalz** [comment]
For those at home, its `attr.unique.platform.aws.local-ipv4`

@dadgar It might just be me, but I feel that doc page could use a little more detail... or at least, a comprehensive list of every key name. Thanks!

**Comment by dadgar** [comment]
@justinwalz Yeah we made some improvements to clarify, when 0.5 comes out the website will get updated!
