### ISSUE TITLE
Multiple Configuration Inputs

### ISSUE THREAD

**Issue by stongo** [hashicorp/nomad#1867]
Currently, Nomad is only fully configurable with configuration files. This does not lend well to modern deployment strategies and is *extremely* limiting.

## Proposed Improvements
* parse environment variables in configuration files
* use Consul's KeyValue store as a source of configuration
* create CLI flags for all configuration options

https://github.com/containous/staert is a great example of creating flexible configuration

**Comment by dadgar** [comment]
Hey thanks for the thought but not something we will be undertaking. You can use a tool like consul-template to handle this and generate the configs dynamically

**Comment by stongo** [comment]
None of these items? Not even parsing environment variables?

**Comment by stongo** [comment]
Using consul-template only addresses one of three items listed. Really closing this so fast?

**Comment by dadgar** [comment]
Didn't mean to be dismissive by closing it quickly, just so happened to see it quickly.

Consul template address 2/3 concerns via:
* https://github.com/hashicorp/consul-template#env
* https://github.com/hashicorp/consul-template#key

As for flags for each configuration option, the standup is that the flags should be used to configure the most common things but not everything. For the less common stuff a configuration file is easiest.

**Comment by stongo** [comment]
consul-template is a bit of a sledge hammer replacement of parsing environment variables in the configuration files IMHO

**Comment by stongo** [comment]
for example, I want to use environment variables for the configuration item `advertise` in nomad agent. how is consul-agent useful for this? in coreos I can pass the environment variable `COREOS_PRIVATE_IPV4`

**Comment by dadgar** [comment]
So there are quite a few tools that allow you to do text substitution with environment variables (sed, awk, ...), you can build your static config and then use one of those to substitute the final value before starting Nomad.

**Comment by gdiazlo** [comment]
see envsubst(1), i use it like cat config.hcl.subst | envsubst > config.hcl, I still prefer to have advertise as a param though
