### ISSUE TITLE
Nomad State in Consul

### ISSUE THREAD

**Issue by stongo** [hashicorp/nomad#1868]
Currently Nomad masters are only able to persist data to disk. Since Consul is already part of the Nomad project, use the Consul KeyValue Store to persist state. This would make deploying HA masters much easier and sane.

**Comment by dadgar** [comment]
Hey,

Nomad uses the same Raft consensus protocol underpinning Consul. This is a key part of the Nomad architecture and allows Nomad to be deployed with no external dependencies. Unlike some of the other schedulers, Nomad can be deployed as a single binary in a HA fashion.

For more details please see: https://www.nomadproject.io/docs/internals/consensus.html.

Further we do not have any requirement that Consul be run to deploy Nomad.

If you have questions about Nomad please see our Gitter channel or mailing list where other user will also be able to help answer questions you may have.

Thanks,
Alex
