### ISSUE TITLE
Nomad Master Discovery in Consul

### ISSUE THREAD

**Issue by stongo** [hashicorp/nomad#1869]
Use Consul to facilitate master discovery instead of requiring hard coding known addresses in the `join` configuration option(s)

**Comment by dadgar** [comment]
Hey! Good suggestion, we thought so too :)

Nomad 0.4 has brought this feature. Please see the documentation:
https://www.nomadproject.io/docs/cluster/bootstrapping.html
https://www.nomadproject.io/docs/agent/config.html#auto_advertise
