### ISSUE TITLE
-client only nodes need a -servers cli flag

### ISSUE THREAD

**Issue by rvm2015** [hashicorp/nomad#187]
There does not appear to be a flag for the command line that is the equivalent of this config option:

    client {
      servers = ["SERVER_IP:4647"]
    }

This would be helpful for inserting this value via an environment file in a SystemD service file. Currently -client can't really be used without a config file without also specifying -server.

**Comment by ryanuber** [comment]
Thanks, this should be pretty straight-forward to add.

**Comment by dadgar** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/191
