### ISSUE TITLE
Parse Environment Variables in Agent Config Files

### ISSUE THREAD

**Issue by stongo** [hashicorp/nomad#1870]
To make deploying nomad easier in containerland, parse environment variables in configuration files

**Comment by stongo** [comment]
it's been suggested I use consul-template instead. but this is not a viable replacement. for example,  the configuration item `advertise` in nomad agent. In coreos I can pass the environment variable `COREOS_PRIVATE_IPV4` as a docker run environment variable to easily set this rather than hardcoding it. using consul-template wouldn't solve this use case. instead I'll have to use `sed` on the config file in a docker container start script to accomplish this.

**Comment by diptanu** [comment]
@stongo We will revamp how we read configuration from HCL files. It's going to come up sometime in the future, but less of a priority right now since we have some higher priority stuff to take care of over the next few months.

**Comment by v-byte-cpu** [comment]
3.5 years passed and no progress ?

**Comment by tgross** [comment]
Shipped in Nomad 1.0 with HCL2.
