### ISSUE TITLE
Periodic Jobs:  Allow to set a "DO NOT RUN" time

### ISSUE THREAD

**Issue by CarelvanHeerden** [hashicorp/nomad#18739]
### Proposal
Add the ability to specify a time period when the job is not allowed to continue to run. 
I.e Cron is 0 0 * * *
Restricted times are: 08:00 to 17:00
If the job is still running at 08:00, it is forced killed. This should also prevent failed jobs to retry during this time

Example
job "docs" {
  periodic {
    cron                           = "*/15 * * * * *"
    restricted_period    = "08:00-17:00"
    prohibit_overlap     = true
  }
}

### Use-cases
Production invasive cron tasks, that are only permitted to run after hours should be prevented from continuing to run and to retry during business hours.

**Comment by tgross** [comment]
A prototype along these lines was built by @mikenomitch in https://github.com/hashicorp/nomad/pull/18456. See also https://github.com/hashicorp/nomad/issues/1782

**Comment by devashishTaneja** [comment]
@tgross Can I take up this enhancement?

**Comment by tgross** [comment]
@devashishTaneja there are still a lot of open design decisions. See @mikenomitch's prototype in https://github.com/hashicorp/nomad/pull/18456, which also has some technical problems that Mike has pointed out like using Nomad Variables to persist the timeout when it should probably be the Nomad client state DB. Realistically I don't think we're ready to take an outside contribution for this feature yet.

**Comment by jrasell** [comment]
Hi @CarelvanHeerden and thanks for raising this issue. I believe the linked PR and issue cover the detail that also encompasses this request, I will therefore close this out. Please feel free to comment on the other issue/pr if you have any additional information you'd like to add.
