### ISSUE TITLE
evals for `max-disconnect-timeout` escape GC

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#18747]
While testing https://github.com/hashicorp/nomad/pull/18701 I ran into a weird bug in evaluation GC for evaluations created for `max-disconnect-timeout`. After purging a job and running `nomad system gc`, I expect to find no more evaluations for the job. But the evaluation for `max-disconnect-timeout` still exists:

```
$ nomad eval list
ID        Priority  Triggered By            Job ID  Namespace  Node ID  Status   Placement Failures
ba6f9a5d  50        max-disconnect-timeout  httpd   default    <none>   pending  false
```

**Comment by lgfa29** [comment]
I think this is a dup of https://github.com/hashicorp/nomad/issues/12809.

(It seems like it's a yearly tradition for us to bump into this problem 😅)

**Comment by tgross** [comment]
Oops, thanks!
