### ISSUE TITLE
Add `go-netaddrs` support to cloud auto-join

### ISSUE THREAD

**Issue by acaloiaro** [hashicorp/nomad#18746]
Now that [go-discover](https://github.com/hashicorp/go-discover/) is considered feature-complete, the cloud providers that it currently supports are permanently locked. Declaring `go-discover`  feature-complete was an important step toward not ballooning 3rd party dependencies in applications that embed it.

However, since `go-discover` is the basis for Nomad's [cloud auto-join](https://developer.hashicorp.com/nomad/tutorials/manage-clusters/clustering#join-nodes-using-cloud-auto-join), cloud auto-join cannot support new providers going forward until `go-discover` is replaced or supplemented with a new solution.

### Proposal

For backward compatibility, I propose that cloud auto-join use [go-netaddrs](https://github.com/hashicorp/go-netaddrs) with a graceful fallback to `go-discover`.

I've proposed the beginning of a solution in https://github.com/hashicorp/nomad/pull/18745

### Use-cases
This supports auto-joining Nomad clusters on cloud providers other than those currently supported by `go-discover`

### Attempted Solutions
As the sole mechanism for cloud auto-join, `go-discover` does not have a fallback mechanism to enable user-supplied cloud providers. Auto-joining Nomad into clusters other than those supported by `go-discover` is currently not possible.

**Comment by jrasell** [comment]
Hi @acaloiaro and thanks for raising this request which sounds like a sensible idea to me. Thanks also for the linked PR, we will try and take a look soon and get some feedback posted.
