### ISSUE TITLE
Environment variables in the volume block don't get evaluated

### ISSUE THREAD

**Issue by peteyako** [hashicorp/nomad#1876]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
5.0-dev (roughly a week ago, so probably source from master 2016-10-20)

### Operating system and Environment details
Red Hat Enterprise Linux Server 7.2 (Maipo)

### Issue

I’d like to be able to create a separate volume mount for each container under a specific task. So I thought I’d do something like this to vary the path

```
config {
   volumes = [“/some/path/volume-${NOMAD_ALLOC_INDEX}:/some/path”]
}

```
it never evaluates the ${NOMAD_ALLOC_INDEX} value, just prints the string verbatim on the file system….. leaving me with a path looking like this:

` “/some/path/volume-${NOMAD_ALLOC_INDEX}” `

instead of 

`“some/path/volume-1”.`

I've tried with other env variables as well. Same result.

### Reproduction steps

- Use the example.nomad job file. 
- Insert the volumes block inside the config block as shown above. 
- Run the job
- Check the path for the volume on the host. 

### Job file (if appropriate)

example.nomad (modified as described above

**Comment by schmichael** [comment]
Made it in before 0.5 RC!
