### ISSUE TITLE
Display all provided variables in UI

### ISSUE THREAD

**Issue by hashworks** [hashicorp/nomad#18805]
### Proposal
The Nomad UI should show all variable values in the UI under `HCL Variable Values`. Currently, it only shows the content of `-var-file` (5d6409bf?), not `NOMAD_VAR_foo` environment variables. AFAIK `-var 'key=value'` isn't shown as well.

![image](https://github.com/hashicorp/nomad/assets/2362091/488bc1b1-7ac8-4fd3-a3b8-69429b7c9bfb)

### Use-cases
When one uses env vars or `-var` instead of a var file it is tedious to edit a Job Definition in the UI, since one has to provide all variable values again. It would be great if all variables are shown.

**Comment by jrasell** [comment]
Hi @hashworks and thanks for raising this issue. It seems variables declared using the `-var` are persisted as expected, however, variables defined as environment variables are not. This is a bug within the CLI which then impacts the UI as a result. I'll add this to our backlog to get fixed up.
