### ISSUE TITLE
nomad service does not handle globbed namespaces.

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad#18831]
### Nomad version

```
$ nomad version
Nomad v1.6.2
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Operating system and Environment details
Void Linux on amd64

### Issue
Calling `nomad service info` with the environment variable `NOMAD_NAMESPACE` set to `*` does not result in the named service being matched at all, even if it is an exact string match.

### Reproduction steps
Try to get info on a service with the namespace set to the wildcard.

#### Expected Result
I expect a search to be performed across all namespaces I have access to and match to happen across the services returned from this set, similar to how other commands work cross-namespace.

#### Actual Result
Nomad reports the service could not be found.

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

**Comment by tgross** [comment]
Done in #18836 and will ship in the upcoming 1.7

**Comment by the-maldridge** [comment]
Wow that was fast!  Thanks for the quick turnaround on this.
