### ISSUE TITLE
bug: cpu.usablecompute is 0 when run as non-root from main branch

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#18871]
### Nomad version
Nomad v1.6.3-dev
BuildDate 2023-10-26T07:43:33Z
Revision 7f62dec473d7a51210d57cdd8b531311c04b35c0

### Operating system and Environment details
AlmaLinux9

### Issue
cpu.usablecompute is 0. No workflow can start, becuase CPU has 0MHz on node.

### Reproduction steps
Run Nomad built from main branch __as non-root user__. Observe cpu.usablecompute.

#### Expected Result
cpu.usablecompute should not be zero. Additionally, I think it would be nice to just fail and exit when cpu.usablecompute is zero.

#### Actual Result
cpu.usablecompute is zero.

**Comment by tgross** [comment]
I'm going to close this issue, because as the docs note in many places, running clients as non-root is unsupported and building support isn't on the near-term roadmap. I'm going to link to this issue from https://github.com/hashicorp/nomad/issues/13669 for discussions on how we might work on this in the future. If you have more comments on this after having read through that issue in detail, I'd suggest you make comments over in #13669.

**Comment by shoenig** [comment]
@Kamilcuk was this on an EC2 instance? If so this is happening because we are no longer maintaining / shipping a huge table of EC2 instance data in Nomad itself. Instead Nomad uses `dmidecode` to find the cpu performance characteristics but that requires root.

You can set the total available compute yourself in client config as a workaround.

```
client {
  cpu_total_compute = 9000
}
```

**Comment by Kamilcuk** [comment]
Hi, thanks for your responses. No, this was on a local installation of AlmaLinux.

**Comment by shoenig** [comment]
Oh interesting, I'd expect even a non-root Nomad to be able to read cpu info from any local install. @Kamilcuk can you post the output of a few commands?

```
ls /sys/devices/system/cpu/cpu0/cpufreq
```

```
cat /proc/cpuinfo | head -n30
```

**Comment by Kamilcuk** [comment]
Hi! Thanks for interest! I got to it, and pulled and compiled revision d98ed87c1b61486c54479947c572f59fdd2e808b, and now I'm getting `cpu.usablecompute | 481536`. I'll post the cpufreq and cpuinfo anyway for reference. Thanks!

```
$ ls /sys/devices/system/cpu/cpu0/cpufreq
affected_cpus  cpuinfo_cur_freq  cpuinfo_transition_latency  scaling_available_frequencies  scaling_driver    scaling_min_freq
bios_limit     cpuinfo_max_freq  freqdomain_cpus             scaling_available_governors    scaling_governor  scaling_setspeed
cpb            cpuinfo_min_freq  related_cpus                scaling_cur_freq               scaling_max_freq  stats
$ cat /proc/cpuinfo | head -n30
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 17
model name      : AMD EPYC 9554 64-Core Processor
stepping        : 1
microcode       : 0xa101135
cpu MHz         : 3750.169
cache size      : 1024 KB
physical id     : 0
siblings        : 64
core id         : 0
cpu cores       : 64
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6200.30
TLB size        : 3584 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 52 bits physical, 57 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor       : 1
vendor_id       : AuthenticAMD
```
