### ISSUE TITLE
[Docs] Template PKI certificate wrongly requires generate_lease on Vault PKI role

### ISSUE THREAD

**Issue by the-nando** [hashicorp/nomad#18893]
The [documentation](https://developer.hashicorp.com/nomad/docs/job-specification/template#pki-certificate) for the use of PKI certificates in a template states that it is required to set `generate_lease: true` on the Vault PKI role in order for Nomad to be able to track the expiry of certificates.
  
According to the `consul-template` [documentation](https://github.com/hashicorp/consul-template/blob/main/examples/vault-pki.md#rendering-pki-certificates-from-vault-with-consul-template) it is not required anymore:
> Note: In previous versions of consul-template generate_lease needed to be set to true (non-default) on the Vault PKI role. Without the lease the automatic certificate renewal wouldn't work properly based on the expiration date of the certificate alone. As of v0.22.0 the certificate expiration details are now also used to monitor the renewal time without needing an associated lease in Vault. If you are issuing a very large number of certificates there may be a performance advantage to not tracking every lease when leaving the default setting of generate_lease set to false.

  
The note requiring the `generate_lease` should be removed from the Nomad docs.

Ref: https://github.com/hashicorp/nomad/blob/76ebb3fe553aaefdd97b65290eb42f5f6fe9c0ba/website/content/docs/job-specification/template.mdx#L635-L639

**Comment by tgross** [comment]
Thanks @the-nando! Fixed by https://github.com/hashicorp/nomad/pull/18895
