### ISSUE TITLE
Java sets max heap size at 25% of instance memory instead of allocated resource memory

### ISSUE THREAD

**Issue by schematis** [hashicorp/nomad#18920]
### Nomad version
1.4.3

### Operating system and Environment details
Amazon Linux 2, OpenJDK 11.0.21

### Issue
By default, Java sets max heap size at 25% available memory and recognizes limits set on containers, which one would expect would apply to nomad tasks. This is not what occurs. Instead Java sets max heap size to 25% of instance memory which causes out of memory issues in the task.

### Reproduction steps

1. Create a simple nomad job with java driver and loading a jar.
2. Exec into task
3. Run `java -XX:+PrintFlagsFinal -version`
4. Search for MaxHeapSize in output

#### Expected Result
MaxHeapSize should be set to 25% of allocated resource memory

#### Actual Result
MaxHeapSize is set to 25% of instance memory

**Comment by shoenig** [comment]
The memory limit is enforced by the `memory.max` cgroup; if the JDK doesn't respect that there isn't much Nomad can do.

Otherwise, you need to set `-Xmx` / `-Xms` to sensible values like in the examples; 

https://developer.hashicorp.com/nomad/docs/drivers/java#task-configuration.
