### ISSUE TITLE
Nomad ACL auth-method MaxTokenTTL configuration increase from 24h to .. example, 7 days?

### ISSUE THREAD

**Issue by dmclf** [hashicorp/nomad#18946]
### Proposal

Currently, the `MaxTokenTTL` for a custom auth-method (ie, oidc) is set to 24h.  
Is it possible to make the `MaxTokenTTL` a bit more customizable for client environments?  
As for a use-case, where there are 6 different Nomad environments, all hooked up to OIDC for SSO purposes, 
and each of these has a 24h timeout, it can be somewhat troublesome if these tokens are only 24 hours.

`example` can `MaxTokenTTL` be increased to perhaps `7 days` ?  
so admins have some flexibility in chosing either 24hours or something a bit longer?  

```
# nomad acl auth-method update -max-token-ttl 48h my-auth-method
Error updating ACL auth method: Unexpected response code: 400 (auth method 0 invalid: 1 error occurred:
	* invalid MaxTokenTTL value '168h0m0s' (should be between 1m0s and 24h0m0s))
```

_Especially as these re-logins break any link you used to navigate to Nomad-UI, and the Nomad-UI itself also has some bugs related to not loading/applying/showing proper elements due to ACL changes. (job-lists being empty, a page-refresh usually fixes that, but those are isolated issues, although related to these short-lived tokens and as such influencing overall UI-user experience)_

_- if the Nomad-UI would have some memory of what entry-link was used before re-directing to login, it would already be more convenient for end-users_
_- and perform a proper ACL refresh automatically, instead of relying on the user to do F5/refresh._

**Comment by jrasell** [comment]
Hi @dmclf; the maximum allowed TTL value can be controlled by the [`acl.token_max_expiration_tll`](https://developer.hashicorp.com/nomad/docs/configuration/acl#token_max_expiration_ttl). This parameter is used to validate the value within an authentication method. I will raise a PR to ensure the docs also detail this.

**Comment by dmclf** [comment]
@jrasell  Ok thanks, sorry I may have missed that one, thanks for the reference.
