### ISSUE TITLE
template source don't accept absolute file path

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1896]
### Nomad version

Nomad v0.5.0-dev ('40d0a4e074b15ee056c5d5cc73d4a338cd19db72')

### Operating system and Environment details

OS X

### Issue

A template with `source` of an absolute path yields the following errror

```
template {
      source = "/opt/deploy/www/frontend/_infrastructure/consul-template/php-fpm.ctmpl"
      destination = "local/php-fpm.conf"
}
```

` "SetupError": "failed to build task's template manager: open /private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/878daa9a-9092-661c-bfd9-86447ba15b40/server/opt/deploy/www/frontend/_infrastructure/consul-template/php-fpm.ctmpl: no such file or directory",
`

### Expected behavior

When a source key start with `/` I would expect to be able to use any file on my host file system, not confined to the server local directory.

**update**

Trying to copy it using `artifacts` stanza doesn't seem to yield a different result

```
artifact {
    source = "/opt/deploy/www/frontend/_infrastructure/consul-template/php-fpm.ctmpl"
    destination = "local/php-fpm.ctmpl"
}

template {
    source = "local/php-fpm.ctmpl"
    destination = "local/php-fpm.conf"
}
```

Yields `failed to build task's template manager: open /private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/ece9192f-1ed8-35c2-9940-92bbe56468dc/server/local/php-fpm.ctmpl: no such file or directory`

Not sure if the `artifact` stanza is executed or not but this is the output from a failed allocation

```
-> find /private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/alloc
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/alloc/data
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/alloc/logs
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/alloc/tmp
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/server
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/server/local
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/server/secrets
/private/var/folders/y4/r82l0ngd2c138r9m0cc55jk00000gp/T/NomadClient033799647/994f6e4a-61d1-6b0b-9784-626528168949/server/tmp
```

No artifact is downloaded, and Nomad complain about a missing template file

Output from the nomad -dev server: https://gist.github.com/jippi/0f83d34263c253813e5fe3f959415991

Sample allocation output: https://gist.github.com/jippi/1ab7564762416deb7ff3a9682a298ff8

If I remove the `template` clause, I get a download artifact error, so seems like its not possible to download templates as artifacts (https://github.com/hashicorp/nomad/pull/1895/files#diff-9286907bd1a85e3f87dd8686f2f12b19R48 docs it should be possible) since the template is started before artifacts is downloaded

**Comment by dadgar** [comment]
By design we don't allow this. Templates should be downloaded using the artifact block. This is consistent with the rest of Nomad.

**Comment by jippi** [comment]
@dadgar consistent to the point that a `volume` can mount anything ? ;) don't see the difference there

**Comment by dadgar** [comment]
Fair enough will put a flag around it
