### ISSUE TITLE
Add descriptive token name when using OIDC tokens

### ISSUE THREAD

**Issue by notheotherben** [hashicorp/nomad#18969]
### Proposal

Currently, when using Nomad's OIDC auth integration, all tokens are issued with the name `OIDC-${authMethod}` (for example, `OIDC-vault`) which makes it difficult for administrators to understand which user a given token belongs to. This contrasts with solutions like the Vault `nomad` mount, which issues tokens using a descriptive name like `vault-${role}-${authMethod}-${subjectName}-${issuanceTimestamp}` making for a much richer degree of admin context.

In an ideal world, it would be possible for us to use a `binding-rule` parameter to specify a name template, leveraging the bind context (`Value` and `List` claims provided by the token). If this were implemented, one might go about creating the binding as follows:

```bash
nomad acl binding-rule create \
    -auth-method=vault \
    -bind-type=management \
    -selector="admin in list.roles" \
    -description="admin -> management token" \
    -token-name="OIDC-vault-{{ value.sub }}-{{ value.username }}-management"
```

I would then expect that, when that appeared in the Nomad UI and/or tokens list, we would observe a token name such as `OIDC-vault-00000000-0000-0000-0000-000000000000-Ben-management`, enabling administrators to understand which user each token belongs to.

Alternatively, an approach which consistently injected the `sub` and `nbf` claim fields into the token name (corresponding to an approximation of the Vault behaviour) would likely address 90% of this requirement without the need to support custom templates and/or requiring users to configure the behaviour (with the notable downside that most OIDC providers use an opaque `sub` value which must be separately looked up to understand which user it corresponds to).

### Use-cases

As an administrator on a Nomad cluster which leverages Vault for access control and token issuance, I would like to be able to review which users have active tokens on the cluster and, in a security response scenario, quickly be able to revoke access for tokens corresponding to a specific user.

### Attempted Solutions

I went looking through the Nomad code base to understand how the token name was determined and found that this is statically set in [`nomad/nomad/acl_endpoint.go#OIDCCompleteAuth`](https://github.com/hashicorp/nomad/blob/0040427c6dce152d1fe20a1b0925141166abb6c9/nomad/acl_endpoint.go#L2768C17-L2768C44) making it impossible for me to adjust this behaviour right now.

Alternative workarounds right now are to continue using the Vault token issuer (which does generate descriptive token names at the cost of a less accessible auth flow for users).

**Comment by jrasell** [comment]
Hi @notheotherben and thanks for raising this issue. I agree having a way to add greater information to the token name would be a very useful addition to the OIDC SSO flow. Considering a user login can match with multiple binding rules, I think any name configuration would probably need to be added to the auth method configuration object.

I'll add this to our roadmap section and mark it for needed a little discussion to correctly identify the UX we would need.

**Comment by notheotherben** [comment]
Thank you @jrasell, I'd be completely happy with that approach and I'mlooking forward to seeing this land (even if just in an interim variant which provides additional hard-coded context).

**Comment by jrasell** [comment]
Closed via which will go out in the next release: https://github.com/hashicorp/nomad/pull/19135
