### ISSUE TITLE
Stopped job versions have the same submit time as the previous version

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#18966]
### Nomad version
Nomad v1.6.3 (but happens also at 1.5.X)

### Issue

When stopping a job, the submit time for that version takes the previous submit time (of the last version), so it appears the job wan't stopped at the time it was, but just after the last change.

### Reproduction steps

1) run job
2) stop job (without purge)

#### Expected Result
The version for the stopped job has the correct time (when the job was set to stop)

#### Actual Result
The stopped job has the submit time of the last previous version

![stop](https://github.com/hashicorp/nomad/assets/6938602/f34707e2-2627-44fb-ac98-6293115349ef)

**Comment by lgfa29** [comment]
Hi @jorgemarey 👋 

Thanks for the report and the PR!

While this seems like a quick fix, it does make me wonder if updating job submit time to the time the job was _stopped_ could be confusing. The fact that stopping a job creates a new job version is already surprising on its own 😅 

I will ask the team for some extra opinions on this and I will let you know once I hear back!
