### ISSUE TITLE
Fedora 39 repo releases missing

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad#19042]
### Operating system and Environment details
Fedora 39

### Issue
<img width="1511" alt="Screenshot 2023-11-09 at 11 22 30 AM" src="https://github.com/hashicorp/nomad/assets/19410501/380d997c-d9fc-4221-8629-bdeee9f36042">

### Reproduction steps
Follow the steps at https://www.hashicorp.com/official-packaging-guide

#### Expected Result
Nomad should install from fedora repo

**Comment by juanvalino** [comment]
Same problem here !

**Comment by tgross** [comment]
Hey folks! The packaging guide linked above does mention that we have support up to Fedora 38. Fedora 39 just came out last week. Right now the process of adding a new version is a bit more manual than we'd like (that's getting worked on too), but you should expect Fedora 39 packages to show up soon-ish. I'll report back here when those are available.

**Comment by tgross** [comment]
Hi folks, packages have been published!
