### ISSUE TITLE
Using kill to kill the Nomad main process, it was found that the Nomad child process did not exit.

### ISSUE THREAD

**Issue by guoh1988** [hashicorp/nomad#19099]
**1.nomad version**
```
nomad --version
Nomad v1.6.2
BuildDate 2023-09-13T16:47:25Z
Revision 73e372ad94033db2ceaf53468b270a31544c23fd
```
**2.Using ps - ef to query Nomad processes**
```
[root@gitlab ~]# ps -ef | grep nomad
root     18812  2014  3 18:12 pts/0    00:00:12 /usr/bin/nomad agent -config /etc/nomad.d
root     19064 18812  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19113 18812  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19124 18812  0 18:14 ?        00:00:00 /usr/bin/nomad executor {"LogFile":"/opt/nomad/data/alloc/c122a83e-9bfe-3cc1-20f6-f7c61591a761/main-app/executor.out","LogLevel":"debug","FSIsolation":true,"CpuTotalTicks":17592}
root     19212 18812  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19224 18812  0 18:14 ?        00:00:00 /usr/bin/nomad executor {"LogFile":"/opt/nomad/data/alloc/cf3ef199-a4fc-7817-1715-968a6d8ea5e1/test-task/executor.out","LogLevel":"debug","FSIsolation":false,"CpuTotalTicks":17592}
```
**3.Using kill to kill the Nomad main process, it was found that the Nomad child process did not exit. Is there a configuration that can be adjusted**
[root@gitlab ~]# ps -ef | grep nomad
root     19064     1  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19113     1  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19124     1  0 18:14 ?        00:00:00 /usr/bin/nomad executor {"LogFile":"/opt/nomad/data/alloc/c122a83e-9bfe-3cc1-20f6-f7c61591a761/main-app/executor.out","LogLevel":"debug","FSIsolation":true,"CpuTotalTicks":17592}
root     19212     1  0 18:14 pts/0    00:00:00 /usr/bin/nomad logmon
root     19224     1  0 18:14 ?        00:00:00 /usr/bin/nomad executor {"LogFile":"/opt/nomad/data/alloc/cf3ef199-a4fc-7817-1715-968a6d8ea5e1/test-task/executor.out","LogLevel":"debug","FSIsolation":false,"CpuTotalTicks":17592}

**Comment by tgross** [comment]
Hi @guoh1988! This is intentional. Those child processes are used to keep the workloads running. This lets you update the Nomad agent in-place without disrupting the running workloads.

**Comment by guoh1988** [comment]
@tgross Is there a configuration to disable this feature if it is not needed

**Comment by tgross** [comment]
You can drain a node before shutting it down. There's also a [`drain_on_shutdown`](https://developer.hashicorp.com/nomad/docs/configuration/client#drain_on_shutdown-block) configuration block on the client config that will cause the client to drain automatically if gracefully shut down.
