### ISSUE TITLE
Workload Identity - Consul integration creates duplicate per-task tokens

### ISSUE THREAD

**Issue by krarey** [hashicorp/nomad#19127]
### Nomad version
Nomad v1.7.0-beta.2
BuildDate 2023-11-15T22:47:41Z
Revision ea3f6cc8798df782cbf82b1c2f55e10b7ca4a419

### Operating system and Environment details
Nomad 1.7.0-beta.2 arm64
Consul 1.17.0 Community Edition arm64
Nomad Workload Identity integration configured per recommended defaults

### Issue
When Nomad workload identity is used to authenticate with Consul, the per-task token used for template rendering is generated twice. Only one of the two tokens is later revoked when the associated allocation is stopped, leading to rapid pollution of the Consul ACL list with unused, infinitely-lived tokens.

**Comment by pkazmierczak** [comment]
Thanks for reporting this, @krarey!
