### ISSUE TITLE
Allow name template when login via auth method

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#19134]
### Proposal
Allow setting a token name template so when someone makes login via a nomad auth method, the token has information about which user belongs to.

Currently, when making a login using JWT the token name is fixed to "JWT-<auth_name>" for every token generated by that auth method. As the token doesn't have any metadata, this has no information about the real user behind that token, when auditing requests it'll be very useful to have that information.

### Possible Solutions

1) provide a configuration option that states which claim to use for building the token name: This would be easier to implement as the user only need to provide the claim to build the token name, but wouldn't be as configurable.
2) allow configuring a token name template: this would allow users to configure the name as they want.

**Comment by jrasell** [comment]
Hi @jorgemarey and thanks for raising this feature request. This is something we would certainly like to support and is already being tracked by https://github.com/hashicorp/nomad/issues/18969. I will therefore close this out as a duplicate.

**Comment by jorgemarey** [comment]
Sorry @jrasell I didn't notice :(
I also made a PR for this. Would you mind taking a look at it?

**Comment by jrasell** [comment]
No need to be sorry. I have assigned the PR to myself for review and will get an initial one done soon. Thanks for raising it; I'm very excited to see this addition and was about to work on it, so perfect timing!
