### ISSUE TITLE
Issue with raw_exec execution context

### ISSUE THREAD

**Issue by AlexRadu92** [hashicorp/nomad#19148]
### Nomad version
Output from `nomad version`
Nomad v1.6.3
BuildDate 2023-10-30T12:58:10Z
Revision e0497bff14378d68cad76a801cc0eba93ce05039
### Operating system and Environment details
Ubuntu 22.04
### Issue

When using the raw_exec driver some actions are not taken as the user running nomad (root in my case). Rather, they are taken with the user running nomad, but not in the correct context, where a the shell / session spawned by nomad with the user (root) does not have access to some files root normally has.

My example is using zfs. I use zfs to administer databases; interacting with nomad I also have a batch job that performs snapshots on a schedule.

When trying to run zfs in the contxt of raw_exec, I get this:

nomad logs -stderr 1b5f8d2b
Failed to initialize the libzfs library.
Failed to initialize the libzfs library.
Failed to initialize the libzfs library.
Failed to initialize the libzfs library.

The one thing that did change here is OS, we switched from ub 20 to ub 22 on this node.
I think this merits some attention, because it looks like this happens because nomad is confused as to what permissions it should have when running certain programs.

Failing a fix for this kind of issue can you please document execution context a bit better? I was able to find a solution for my issue, but a better understanding of what raw_exec does under the hood might help people find fixes faster, when a particular kind of logic / software clashes with what nomad is trying to do.

### Reproduction steps
Created a job to list zfs snapshots:
        command = "/bin/bash"
        args = [ "-c" , "zfs", "list" ]
Returns

I set the execution to a sleep and switched via alloc exec to the allocation's context, when passing zfs to strace this can be seen:
openat(AT_FDCWD, "/dev/zfs", O_RDWR|O_CLOEXEC) = -1 EPERM (Operation not permitted).
The file itself has global perm:
crw-rw-rw- 1 root root 10, 249 Nov 17 16:24 /dev/zfs

More importantly, when executing a su into root and running it again; it works. So this look like' it's a problem with execution context.

#### Expected Result

Nomad's raw_exec driver can interact with the zfs binary on my nodes.

#### Actual Result

Nomad can't run zfs on nodes due to perm / lib load failure caused by permissions

#### Workaround

This can be worked around by using su as an entrypoint. This adds some additional complexity to how args needs to be passed, this will work:
        command = "/usr/bin/su"
        args = ["--login" , "root", "bash" , "-c", "/usr/sbin/zfs list"]
It also has the unfortunate side-effect of removing the execution directory of the task, whereas normally you can call local/my_rendered_script.sh; and this would call something that, e.g. was rendered via template to the local task directory, when using su this will switch you to / as far as execution context is concerned.

This can be worked around by referencing ${NOMAD_TASK_DIR} in the args section.

### Job file (if appropriate)
```job "zfs-tester" {
  datacenters = ["test"]
  priority = 50

  type = "batch"

  constraint {
    attribute = "${meta.application}"
    value     = "my_app"
  }

  constraint {
    attribute = "${meta.environment}"
    value     = "test"
  }

  group "Sample" {

    constraint {
      attribute = "${meta.server_index}"
      value     = "213"
    }

    constraint {
      attribute = "${meta.zone}"
      value     = "DC-zone"
    }

    constraint {
    attribute = "${meta.component}"
    value     = "SomeValue"
    }

    count = "1"

    ephemeral_disk {
      size = "150"
    }

    task "test-snapshot" {
      driver = "raw_exec"

      env {
        "APP"                     = "${meta.application}"
        "COMP"                    = "${meta.component}"
        "DOMAIN"                  = "${meta.domain}"
        "ENVR"                    = "${meta.environment}"

      }
      config {
        command = "/bin/bash"
        args = ["-c" , "zfs list"] # replace with args = ["-c" , "sleep 7200"]  for testing
      }

      resources {
        cpu = 100 # Mhz
        memory = 128 # MB
      }
    }
  }
}
```

**Comment by lgfa29** [comment]
Hi @AlexRadu92 👋 

Looking through the code for the `raw_exec` task driver, it really doesn't seem to be doing anything in terms of isolation.

A few things you could try:

* explicitly specify a [`task.user`](https://developer.hashicorp.com/nomad/docs/job-specification/task#user) value. I think it shouldn't really matter, but worth a test.
* You mentioned a upgrade from Ubuntu 20 to 22. I believe that's when cgroups v2 became the default, so you could try setting the `raw_exec` plugin config [`no_cgroups`](https://developer.hashicorp.com/nomad/docs/drivers/raw_exec#no_cgroups) to `true` or switch your system back to use cgroups v1 to check if this is the problem.

Let us know how these go!

**Comment by AlexRadu92** [comment]
Heya,

Very curious to see if either work.
Thank you for the input! Will get back to you on Monday.

Best regards,
Alex R

**Comment by AlexRadu92** [comment]
Hei!

Sorry for getting back so slow. Two things worked:
1. Setting the raw_exec driver to not use cgroups via nomad agent config.
2. Disabling cgroups v2 wholesale from the guest OS: Added this to /etc/default/grup: GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0" (https://blog.nuvotex.de/ubuntu-22-04-or-21-10-kubernetes-cgroups-v2/amp/ -- guide for anyone facing the same issue)

Since both approaches work I think I'm going to do the way of configuring nomad, but this might be useful to know for other folks.

Thanks for the input, this is likely to save us a bunch of headaches 😃 

Best regards,
Alex R

**Comment by lgfa29** [comment]
No worries, since you have a solution that works for you I'm going to close this one.

Feel free to reach out if you have any other problem!
