### ISSUE TITLE
Errors don't surface to websockets for alloc exec/actions

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#19164]
In https://github.com/hashicorp/nomad/pull/19084#discussion_r1403493542, @pkazmierczak noticed that Permission Denied errors were not being returned to the opened websocket, resulting in a "Complete" state for the action, but no indication that a problem occurred.

Upon investigating, noticed that our exec functionality behaves similarly — we show a "The connection has closed." message int he exec terminal but no further indication that it had anything to do with permissions or otherwise.

The ws.WriteMessage call at https://github.com/hashicorp/nomad/blob/a9d61ea3fd9ecb51d64534b30fe5938024336787/command/agent/alloc_endpoint.go#L652-L653 indicates that we should have a way of returning with the error code, but it seems like the channel is closed before that has the chance to take place.

![image](https://github.com/hashicorp/nomad/assets/713991/5c4cd7db-3990-406c-8e54-b8d17af07182)

**Comment by tgross** [comment]
Indirectly fixed by https://github.com/hashicorp/nomad/pull/28025. Using a token that can read the allocation but not exec:

```
$ nomad alloc status ae4c9079
ID                  = ae4c9079-e88f-be11-2b6f-99fc6f8c06c5
...

$ nomad alloc exec ae4c9079 /bin/sh
failed to exec into task: Permission denied
```
