### ISSUE TITLE
Nomad variable update causes all allocations to restart at the same time.

### ISSUE THREAD

**Issue by atillamas** [hashicorp/nomad#19171]
### Nomad version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc

### Operating system and Environment details
Ubuntu 22.04.3 LTS

### Issue
When updating a native Nomad variable that is used in a template all allocations restarts at the same time causing outage

### Reproduction steps
create a job with a template like this:

```template {
  data = <<-EOF
  [[- with nomadVar "nomad/jobs/test" ]]
    [[- range $k, $v := . ]]
  [[ $k ]]="[[ $v ]]"
      [[- end ]]
  [[- end ]]
  EOF
  destination = "${NOMAD_SECRETS_DIR}/env.vars"
  change_mode = "restart"
  left_delimiter = "[["
  right_delimiter = "]]"
  env         = true
}
```

#### Expected Result
Should restart one allocation at a time when running 3 allocations.

#### Actual Result
restarts all 3 allocations at the same time.

**Comment by lgfa29** [comment]
Hi @atillamas 👋 

Thanks for the report. Coodernating events across allocations is actually a much broader and quite a complex issue. We have https://github.com/hashicorp/nomad/issues/19052 to track this and https://github.com/hashicorp/nomad/issues/10920 describes the problem in the context `template` as well, so I will close this one as a duplicate.

As a potential workaround you can try increasing the [`template.splay`](https://developer.hashicorp.com/nomad/docs/job-specification/template#splay) value to widen the gap of the possible restart events across allocations.
