### ISSUE TITLE
client: failed to query for node allocations: node secret ID does not match after upgrade to 0.5.rc1

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#1928]
### Nomad version
Nomad v0.5.0-rc1 ('a8c8199e413d387021a15d7a1400c8b8372124d6+CHANGES')

### Issue
After upgrade our test enviroment, on all nodes exept one, we see follow in logs:

```
   2016/11/03 16:34:18.474552 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:35:03.189560 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:35:51.811798 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:36:49.784030 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:37:33.321278 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:38:10.828049 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:38:45.615148 [ERR] client: failed to query for node allocations: node secret ID does not match
    2016/11/03 16:39:35.318922 [ERR] client: failed to query for node allocations: node secret ID does not match
```

Perphaps as result of this error we can't make any new allocations. They all stuck in pending state, with alloc-state 500 can't find allocations with id(i write this be memory). In our test enviroment all our servers node act as clients.

After fully restart all test clustrer error seems gone.

Is any recomendations to upgrade nomad to 0.5?

**Comment by tantra35** [comment]
Little addtion may be this helps

In our test enviroment present 6 nodes, all of then is the same as server and as client. When we begin upgrade our cluster nomad leader was on node6, and we upgrade it last. And only on this node we doesn't see logs that we mention above

**Comment by dadgar** [comment]
@tantra35 How did you upgrade? Just kill Nomad, replace the binary and start again? 

Has any one else hit this?

**Comment by tantra35** [comment]
We had symlink 'nomad' -> 'nomad_0.4.1/nomad' so we extract rc to 'nomad_0.5.rc1/nomad' Andrey then change symlink to new binary. Then we restart nomad service(we use upstart) 'restart nomad'. Then same operation we made on all nodes

**Comment by LordFPL** [comment]
Same for me a few ago with a dev version... i do a drain, stop nomad, replace binary, and start nomad. Operation on 4 nodes (3 server and 1 node). If i remember well, node was ok, but all server have the same error in this issue. As it was on a dev cluster, i delete all data_dir...
My first think was about secretid generation... it was like a exchange between nodes was not done, and can't be after upgrade. Can't tell more sorry.

**Comment by dadgar** [comment]
Ah these log are on the server. @LordFPL and @tantra35 did the system stop logging those errors after a minute or two?

This should be transient and stop happening after the clients properly register. It only happens the first time you upgrade a 0.4.1 node to 0.5.0

**Comment by tantra35** [comment]
@dadgar  Hm, i think about this, but in my case this messages writes to log about 3 hours until I did not notice it, when try to place new job and this place was fail(stuck in pending state)

I attach full log from one of our test nodes
[nomad.txt](https://github.com/hashicorp/nomad/files/570055/nomad.txt)

We made upgrade at `2016/11/03 11:57:03` and at `2016/11/03 16:39:35.318922` begin making full restart

**Comment by dadgar** [comment]
@tantra35 Did you have a leader between 11:57:03 and the restart? That would explain a lot of it if you didnt

**Comment by tantra35** [comment]
Yes. I specifically checked this fact

**Comment by dadgar** [comment]
Okay! Thanks! I will try and reproduce

**Comment by tantra35** [comment]
We have follow nodes:

```
server1.global  192.168.30.1    4648  alive   false   2         0.5.0rc1  test        global
server2.global  192.168.30.2    4648  alive   false   2         0.5.0rc1  test        global
server3.global  192.168.30.3    4648  alive   false   2         0.5.0rc1  test        global
server4.global  192.168.30.4    4648  alive   false   2         0.5.0rc1  test        global
server5.global  192.168.30.5    4648  alive   false   2         0.5.0rc1  test        global
server6.global  192.168.30.6    4648  alive   true    2         0.5.0rc1  test        global
social.global   192.168.31.220  4648  alive   false   2         0.5.0rc1  test        global
```

Before upgrade leader was on server6. We upgrade cluster in follow sequnce:
```social.global
server1.global
server2.global
server3.global
server4.global
server5.global```

and at last we upgrade leader server6.global(only this server doesn't have `node secret ID does not match` in his logs), after that leader placed on `server1.global`

**Comment by kak-tus** [comment]
Same for me. I have replaced (drain, stop, replace binary, start) one test node in cluster and have this issue.

**Comment by dadgar** [comment]
@kak-tus Were you running with each node in both server and client mode too? Any logs?

**Comment by dadgar** [comment]
Confirmed that this is happening. Investigating now

**Comment by kak-tus** [comment]
@dadgar Yes, both server and client. As I understand - logs no needed already.
