### ISSUE TITLE
Additional "node" data in /nodes endpoint

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1929]
Hi,

Would love to see the following key exposed in /nodes to be aligned with /members

- `Attributes.nomad.version`

**Comment by jippi** [comment]
Also seem to be missing `datacenter` and `region`, is this not properties of a client?

**Comment by dadgar** [comment]
Hey,

Datacenters is in the nodes response and the region is a function of the region you are querying against so as you said it is inherited. As to not including the attributes list, the goal is to keep the nodes/ stub lightweight since there could be 50,000K nodes in a given region.

**Comment by jippi** [comment]
@dadgar sure thing, exposing `Attributes.nomad.version` is the primary attribute of interest to me, could just be as "build" or similar, having this in the stub is very usable for nomad-ui while doing a rollout of a new version to follow which of them has been upgraded without visiting each and every client :)

**Comment by dadgar** [comment]
Hey, so the attributes block is a pretty heavy object to embed into the stub. For small cluster sizes an additional query isn't a very big deal per node. On larger clusters, the nodes endpoint also supports blocking queries so the node information can be cached.

Let me know if the explanation didn't make sense!

**Comment by jippi** [comment]
@dadgar my point was more to move `Attributes.nomad.version`  out of `Attributes` (or copy it) to a root key, similar to /members so its easier to get an overview of cluster versions in one go, like for members
