### ISSUE TITLE
raft: Failed to make RequestVote RPC to 127.0.0.1:4647: dial tcp 127.0.0.1:4647: connection refused

### ISSUE THREAD

**Issue by darron** [hashicorp/nomad#193]
I've built a small 3 node Terraform server cluster - but am having problems getting it to converge.

The code I used to build it is here: https://github.com/darron/nomad-cluster

I see nodes join:

```
2015/10/02 03:53:09 [DEBUG] memberlist: TCP connection from: 10.232.1.176:36060
2015/10/02 03:53:09 [INFO] serf: EventMemberJoin: ip-10-232-1-176.global 10.232.1.176
2015/10/02 03:53:09 [INFO] nomad: adding server ip-10-232-1-176.global (Addr: 10.232.1.176:4647) (DC: dc1)
2015/10/02 03:53:09 [WARN] raft: Election timeout reached, restarting election
2015/10/02 03:53:09 [INFO] raft: Node at 10.232.28.223:4647 [Candidate] entering Candidate state
2015/10/02 03:53:09 [ERR] raft: Failed to make RequestVote RPC to 127.0.0.1:4647: dial tcp 127.0.0.1:4647: connection refused
2015/10/02 03:53:09 [DEBUG] raft: Votes needed: 2
2015/10/02 03:53:09 [DEBUG] raft: Vote granted. Tally: 1
2015/10/02 03:53:10 [DEBUG] serf: messageJoinType: ip-10-232-1-176.global
2015/10/02 03:53:10 [ERR] worker: failed to dequeue evaluation: No cluster leader
2015/10/02 03:53:10 [WARN] raft: Election timeout reached, restarting election
```

But they never successfully have an election. I also see quite a few of these logs:

```
2015/10/02 03:53:34 [WARN] raft: Remote peer 10.232.1.176:4647 does not have local node 10.232.28.223:4647 as a peer
2015/10/02 03:53:34 [WARN] raft: Remote peer 10.255.14.83:4647 does not have local node 10.232.28.223:4647 as a peer
```

I pulled the config and full logs out of one of the nodes I built - it's posted here:

https://gist.github.com/darron/c961584f373f133464ea

I'm sure I'm missing something - but it seems like there's a couple things going on here. 

Googling hasn't helped - any idea what I'm missing?

**Comment by jmitchell** [comment]
Have you tried stopping all the server agents, deleting each of their `data_dir`s, and starting the agents again? That worked for me.

In my case, on each server `nomad server-members` listed all members as expected. Even so, they weren't successfully coordinating an election. I was also seeing lines like `[WARN] serf: Failed to re-join any previously known node`.

Now that my servers have successfully elected a leader, if I restart all the servers without cleaning the `data_dir`s it still works. The past history in `data_dir`s no longer inhibits leader election. I'm not sure yet what caused the first leader election failure. Could have been all the experimental configuration changes I was making led to a weird state.

**Comment by prashanth5192** [comment]
Yes, Mitchell that definitely helped solving the problem. But everytime I try to do a node-status or submit a job.. the server defaults to look up at by local loopback instead of the bind addr. Do you know how we could solve this issue ?

**Comment by cbednarski** [comment]
@darron Sorry for the delay on responding to this. This is definitely a bug on our side, though I have not had a chance to setup a cluster like yours to debug this yet.

It looks like you are using a non-standard port (4647 vs 4646). Can you curl that port? Does this work with the default port? Do you have network connectivity between nodes on that port? Particularly:

```
2015/10/02 03:53:09 [ERR] raft: Failed to make RequestVote RPC to 127.0.0.1:4647: dial tcp 127.0.0.1:4647: connection refused
```

leads me to believe that Nomad is not actually listening on 4647.

> Yes, Mitchell that definitely helped solving the problem. But everytime I try to do a node-status or submit a job.. the server defaults to look up at by local loopback instead of the bind addr. Do you know how we could solve this issue ?

@prashanth5192 I'm not sure you have the same issue. It sounds to me like your agent is using a non-default configuration and the client is not picking it up. If that's the case can you open a new issue for that, please?

**Comment by i0rek** [comment]
@prashanth5192 I think you are having this problem: https://github.com/hashicorp/nomad/issues/359.

**Comment by yikaus** [comment]
According  raft code https://github.com/hashicorp/raft/blob/master/raft.go 

It failed on askPeer (runCandidate() > electSelf() > askPeer)
>	// For each peer, request a vote
>	for _, peer := range r.peers {
>		askPeer(peer)
>	}

It seems always try 127.0.0.1:4647 as first peer , could it be a issue with setPeer on nomad ?

**Comment by dadgar** [comment]
I am going to close this and update the documentation. When you do a server-join you give <IP:Serf_Port>. 4647 is the default RPC port.

**Comment by wassimsidia** [comment]
How to delete the consul -data-dir ?

**Comment by dadgar** [comment]
@wassimsidia If you are having a Consul outage I suggest looking at this: https://www.consul.io/docs/guides/outage.html

To delete the Consul data dir, you shutdown Consul and `rm -rf <data-dir>`. The data-dir is configured in the config file.
