### ISSUE TITLE
Nomad client reports 0 cpu.usablecompute and cpu.totalcompute in v1.7.0

### ISSUE THREAD

**Issue by L-P** [hashicorp/nomad#19343]
### Nomad version
```
# nomad version
Nomad v1.7.0
BuildDate 2023-12-07T08:28:54Z
Revision e4150e9703f3be6ee2339f0e45ff0801186e022b
```

Downgrading to v1.6.4 fixes the issue.

### Operating system and Environment details
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

# uname -a
Linux  5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
```

Running on AWS EC2 t3.small

### Issue
Client reports `cpu.totalcompute` and `cpu.usablecompute` to be zero. No allocation can succeed.

### Reproduction steps
Run a nomad client, optionally attempt to start a job to see that it fails.

#### Expected Result
Proper values for CPU availability.

#### Actual Result
Zero CPU existing/available.

### Job file (if appropriate)
n/a

### Nomad Server logs (if appropriate)
n/a

### Nomad Client logs (if appropriate)
```
2023-12-07T14:22:14.740Z [DEBUG] client.fingerprint_mgr.cpu: detected CPU model: name="Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz"
2023-12-07T14:22:14.740Z [DEBUG] client.fingerprint_mgr.cpu: detected CPU core count: cores=2
```

**Comment by shoenig** [comment]
Hi @L-P thanks for trying out Nomad 1.7 so quickly :slightly_smiling_face: 

I was able to reproduce just by setting up a Debian 11 in an EC2 instance like you have. The problem is that we stopped shipping the huge EC2 CPU performance data lookup table starting in Nomad 1.7 and instead started relying on using `dmidecode`. The `dmidecode` package is installed out of the box for the standard Ubuntu AMI's, and admittedly that's what we primarily test with.

For debian users you'll have to install the `dmidecode` package manually and then restart the Nomad agent. The "fix" here is just a documentation update and a note in the version upgrade guide.

```
sudo apt install dmidecode
```

e.g.

```
Attributes
cpu.arch                                 = amd64
cpu.frequency                            = 2500
cpu.modelname                            = Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
cpu.numcores                             = 2
cpu.reservablecores                      = 2
cpu.totalcompute                         = 5000
cpu.usablecompute                        = 5000
driver.exec                              = 1
driver.raw_exec                          = 1
kernel.arch                              = x86_64
kernel.name                              = linux
kernel.version                           = 5.10.0-26-cloud-amd64
memory.totalbytes                        = 996999168
nomad.advertise.address                  = 127.0.0.1:4646
nomad.bridge.hairpin_mode                = false
nomad.revision                           = e4150e9703f3be6ee2339f0e45ff0801186e022b
nomad.service_discovery                  = true
nomad.version                            = 1.7.0
numa.node.count                          = 1
numa.node0.cores                         = 0-1
os.cgroups.version                       = 2
os.name                                  = debian
os.signals                               = SIGINT,SIGPROF,SIGSTOP,SIGXCPU,SIGABRT,SIGTERM,SIGXFSZ,SIGALRM,SIGTRAP,SIGTTOU,SIGHUP,SIGSEGV,SIGILL,SIGIOT,SIGPIPE,SIGNULL,SIGIO,SIGTSTP,SIGUSR1,SIGUSR2,SIGCONT,SIGFPE,SIGQUIT,SIGWINCH,SIGBUS,SIGSYS,SIGTTIN,SIGKILL
os.version                               = 11.8
platform.aws.ami-id                      = ami-0aa68a84b74592380
platform.aws.instance-life-cycle         = on-demand
platform.aws.instance-type               = t3.micro
platform.aws.placement.availability-zone = us-east-1d
```

**Comment by L-P** [comment]
> thanks for trying out Nomad 1.7 so quickly 

That's on me for not pinning the version.

I installed `dmidecode` and restarted the service, it works. Thanks.

Instead of making this a doc change, I would suggest adding `dmidecode` as a dependency to the `nomad` package which only requires `openssl` at the moment:
```
# apt show nomad
Package: nomad
Version: 1.7.0-1
Priority: optional
Section:
Maintainer: HashiCorp
Installed-Size: 111 MB
Depends: openssl
```

**Comment by shoenig** [comment]
> Instead of making this a doc change, I would suggest adding dmidecode as a dependency to the nomad package which only requires openssl at the moment:

I totally agree but this would be quite tricky right now - we use a shared infra for building linux packages and it seems `fpm` doesn't have a convenient way of communicating _suggested_ packages, which is what we'd want the `dmidecode` package to be.
