### ISSUE TITLE
trying to stop running container

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1936]
### Nomad version

nomad 0.5-rc1

### Issue

Docker complained about `failed to start task 'server' for alloc 'b103d590-3ca6-b5f3-3f36-7f70c5498900': Failed to purge container 8690b16f5809a935150166a44162c3150bdcda1172de9b2949af783e11fa611a: API error (409): {"message":"You cannot remove a running container 8690b16f5809a935150166a44162c3150bdcda1172de9b2949af783e11fa611a. Stop the container before attempting removal or use -f"}`

### Reproduction steps

N/A

**Comment by dadgar** [comment]
Believe #1938 will fix this too. If you don't hit it in RC2 lets close

**Comment by dadgar** [comment]
@jippi Can we close this one?

**Comment by jippi** [comment]
haven't noticed anything on this, so yes, good job on fixing it :)
