### ISSUE TITLE
Nomad 1.7 and consul tags data type

### ISSUE THREAD

**Issue by ahjohannessen** [hashicorp/nomad#19378]
There seems to be an issue with `tags` data type in consul section in Nomad 1.7. 

I am using `ansible-nomad` that generates this:
```
...
tags = {{ nomad_consul_tags | to_json }}
```
using default value:
```
nomad_consul_tags: {}
```

Nomad 1.6.x and earlier have no issue with that, but 1.7.0 complains about the data type. A workaround is to override that variable with `""`, but that makes 1.6.x complain about the data type.

/cc @tgross

**Comment by tgross** [comment]
@ahjohannessen the `consul` configuration block is now a list of configuration blocks, one for each Consul cluster (to support connecting to multiple Consul clusters in Nomad Enterprise). Our configuration is not part of our published API (it's an unstructured map in the official API client (ref https://github.com/hashicorp/nomad/blob/main/api/agent.go#L447). This will need to get fixed upstream.
