### ISSUE TITLE
Nil dereference after 1.7.1 update

### ISSUE THREAD

**Issue by Cottand** [hashicorp/nomad#19407]
### Nomad version
Output from `nomad version`

```
Nomad v1.7.1
```

### Operating system and Environment details

NixOS 23.05, linux amd64

### Issue
Nil dereference on startup after updating to 1.7.1 (from 1.6.3).

I updated a node running as both client and server in-place. The rest of the cluster is still 1.6.3. If I disable client mode in the node I updated to 1.7.1, the error stops appearing in the logs (but comes back if I enable it again).

### Nomad Client logs (if appropriate)
```
Dec 09 16:43:03 cosmo nomad[79399]:     2023-12-09T16:43:03.145Z [ERROR] worker: error invoking scheduler: worker_id=a35f335f-0040-24b3-e106-f6f1ab7ab5e2 error="failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference"
Dec 09 16:43:03 cosmo nomad[79399]:     2023-12-09T16:43:03.149Z [ERROR] worker.system_sched: processing eval panicked scheduler - please report this as a bug!: eval_id=356fe22e-012b-63a4-f78a-24a0ce1bea6e job_id=seaweedfs-volume namespace=default worker_id=196f7902-25aa-2a11-d6cd-66a89eb370a0 eval_id=356fe22e-012b-63a4-f78a-24a0ce1bea6e error="runtime error: invalid memory address or nil pointer dereference"
Dec 09 16:43:03 cosmo nomad[79399]:   stack_trace=
Dec 09 16:43:03 cosmo nomad[79399]:   | goroutine 83 [running]:
Dec 09 16:43:03 cosmo nomad[79399]:   | runtime/debug.Stack()
Dec 09 16:43:03 cosmo nomad[79399]:   | \truntime/debug/stack.go:24 +0x5e
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58
Dec 09 16:43:03 cosmo nomad[79399]:   | panic({0x2588180?, 0x4798630?})
Dec 09 16:43:03 cosmo nomad[79399]:   | \truntime/panic.go:914 +0x21f
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:252
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00191eaa0)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3177 +0xcc
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc001671030, 0xc001a1e900)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc0006ba3f0)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc0018cc8a0)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/rank.go:808 +0x28
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc001ea6e80, 0xc0007f7d40, 0xc001671790)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc0015d8d80, {0xc0018cc9e0, 0x1, 0x7?})
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc0015d8d80)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb7b
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc0015d8d80)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc001671d80, 0xc001671d70)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc0015d8d80, 0xc00134c300)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0015e4000, 0xc001a66ba0, 0xc00134c300, {0xc002332b70, 0x24})
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/nomad/worker.go:629 +0x353
Dec 09 16:43:03 cosmo nomad[79399]:   | github.com/hashicorp/nomad/nomad.(*Worker).run(0xc0015e4000, 0x12a05f200)
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/nomad/worker.go:458 +0x5a5
Dec 09 16:43:03 cosmo nomad[79399]:   | created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
Dec 09 16:43:03 cosmo nomad[79399]:   | \tgithub.com/hashicorp/nomad/nomad/worker.go:158 +0x59
Dec 09 16:43:03 cosmo nomad[79399]:   
```

### Reproducing the issue

I am not sure what part of the deployment is causing this. If you have some troubleshooting steps I am happy to follow them.

I have only upgraded 1 client in the cluster for fear that other clients will also go down.

**Comment by tgross** [comment]
Thanks for reporting this! That suggests that the bug described in https://github.com/hashicorp/nomad/issues/19372 may not be limited to the unsupported Nomad-in-a-container use case. We're investigating that and will report back.

**Comment by tgross** [comment]
See also https://github.com/hashicorp/nomad/issues/19417, where the bug started happening for this user after they installed `dmidecode` to improve their CPU fingerprinting situation.

**Comment by tgross** [comment]
> I updated a node running as both client and server in-place. The rest of the cluster is still 1.6.3. If I disable client mode in the node I updated to 1.7.1, the error stops appearing in the logs (but comes back if I enable it again).

I think this may be an important clue. If a 1.7.x client fingerprints its topology to a 1.6.x server, and then the 1.6.x server replicates the `Node` struct for that client to a 1.7.x server... there might be an opportunity for things to go wrong there. I'm at the end of my day now but I'll pick up from there tomorrow.

**Comment by roman-vynar** [comment]
I can confirm this too.
When an older client (1.3.5) reports to a newer server (1.7.1) then the server panics out:
```    
2023-12-12T10:55:27.891Z [ERROR] worker.batch_sched: processing eval panicked scheduler - 
please report this as a bug!: eval_id=aca02768-a9a3-87dc-9ca4-229c02d22d77 
job_id=builder11-1e174062f5fdf2 namespace=default worker_id=c264c855-19e5-4492-9420-372d3f294742
 eval_id=aca02768-a9a3-87dc-9ca4-229c02d22d77 
error="runtime error: invalid memory address or nil pointer dereference"
  stack_trace=
  | goroutine 69 [running]:
  | runtime/debug.Stack()
  | \truntime/debug/stack.go:24 +0x5e
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process.func1()
  | \tgithub.com/hashicorp/nomad/scheduler/generic_sched.go:153 +0x58
  | panic({0x2587180?, 0x479aa30?})
  | \truntime/panic.go:914 +0x21f
  | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
  | \tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:252
  | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00235e1e0)
  | \tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3177 +0xcc
  | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc0010e08f0, 0xc000d4e000)
  | \tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36
  | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc001cde2a0)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d
  | github.com/hashicorp/nomad/scheduler.(*JobAntiAffinityIterator).Next(0xc001198c30)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:616 +0x6b
  | github.com/hashicorp/nomad/scheduler.(*NodeReschedulingPenaltyIterator).Next(0xc001b5d920)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:677 +0x28
  | github.com/hashicorp/nomad/scheduler.(*NodeAffinityIterator).Next(0xc001198c80)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:749 +0x30
  | github.com/hashicorp/nomad/scheduler.(*SpreadIterator).Next(0xc001cde310)
  | \tgithub.com/hashicorp/nomad/scheduler/spread.go:131 +0x33
  | github.com/hashicorp/nomad/scheduler.(*PreemptionScoringIterator).Next(0xc000aadaa0)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:844 +0x28
  | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc000aadac0)
```

**Comment by tgross** [comment]
Hi folks! Just wanted to give an update on this and the related set of bugs around panics and fingerprinting (#19407, #19372, #19412). @pkazmierczak @shoenig @lgfa29 and I have been working on trying to get a reproduction of all these issues and they turn out to be interrelated and it depends a bit on your particular environment which one you're going to hit.

Reliable and accurate CPU fingerprinting is highly platform specific. In Nomad 1.7.0 as part of work for NUMA support (and to reduce other problems in our CPU accounting), we introduced a new CPU fingerprinting scheme for Linux, where we go through a series of "scanner" options (ref [`detect_linux.go#L20-L27`](https://github.com/hashicorp/nomad/blob/v1.7.1/client/lib/numalib/detect_linux.go#L20-L27)) of decreasing accuracy until we get a valid CPU topology. Unfortunately there are a lot of platforms where this scanning is still coming up with no valid topology. 

Depending on the shape of your particular environment, you might end up with 0 cpu reported. Or you might hit the code path where the scheduler tries to read the `nil` CPU topology and you get a panic.

Our fix for this is going to be to reintroduce the less accurate pre-1.7.0 fingerprinting as a final fallback for those platforms where we can't make sense of the CPU topology. This means NUMA support won't work in those environments, but largely those platforms appear to be those where NUMA isn't meaningful (ex. containers, hypervisors that cut up a NUMA core between VMs, etc.). 

We're working on the patch for this now and will ship it as soon as its available. Thanks for your help in lots of detailed reports and your patience while we work thru this.

**Comment by Cottand** [comment]
Hi @tgross thanks for the update. Just FYI the above report is for a machine running on a Contabo VPS (so a VM probably, I do not know the hypervisor) but not on a container.

**Comment by tgross** [comment]
Our patches for this issue have landed and will be shipped in Nomad 1.7.2 shortly (likely tomorrow).

**Comment by Cottand** [comment]
I can confirm 1.7.2 fixed this nil panic for my specific issue :tada: thanks!

I would like to add that I would love to see the docs (maybe [this page](https://developer.hashicorp.com/nomad/docs/v1.7.x/concepts/cpu)?) updated with some info on how the fingerprinting works, and what to expect of the accuracy of the scanning options in each environment. For example, is it recommended that I [set `cpu_total_compute`](https://developer.hashicorp.com/nomad/docs/configuration/client#cpu_total_compute) manually on an x64-86 machine running under KVM? etc.

**Comment by tgross** [comment]
Thanks for the update @Cottand! And yeah, agreed we should invest some time in improving the docs here.
