### ISSUE TITLE
namespace: attempting to delete a namespace with attached variables returns 200 OK

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#19414]
### Nomad version
Main at `e551814df5f271a3ad2f69ed4fd812ce2807be84`

### Operating system and Environment details
Reproduced locally on MacOS but does not rely on any OS specific code.

### Issue
The problem looks like a bug in the way the namespace delete RPC validation happens. The handler [checks whether the namespace has non-terminal jobs within](https://github.com/hashicorp/nomad/blob/099ee06a607cea34389f8204b16506d1f24e1afa/nomad/namespace_endpoint.go#L111) it but doesn't check whether the namespace has variables still attached to it.

The RPC handler validation doesn't error, therefore the Raft update message is fired to remove the namespace; this triggers the RPC/HTTP response.

When the Raft message reaches the FSM, we check whether the [namespace has any variables attached](https://github.com/hashicorp/nomad/blob/5e1bbf90fca0a1d7beceba4d99e2a9d70b18e7a1/nomad/state/state_store.go#L6834), which triggers the error in the logs and results in the namespace not being deleted. This bug also seems to be present when attempting to delete a namespace [which still has CSI volumes attached](https://github.com/hashicorp/nomad/blob/5e1bbf90fca0a1d7beceba4d99e2a9d70b18e7a1/nomad/state/state_store.go#L6823).

It's likely we need to duplicate this validation to the RPC handler which will allow us to return correct errors to the external caller.

### Reproduction steps
1. Start a Nomad development agent using `nomad agent -dev`
2. Create a non-default namespace using a command such as `nomad namespace apply jrasell`
3. Create a variable attached to the non-default namespace using the command `echo "abcd1234" | nomad var put -namespace=jrasell secret/foo bar=-`
4. Attempt to delete the namespace using `nomad namespace delete jrasell`

#### Expected Result
The CLI/API should return an error that the namespace could not be deleted because it has attached variables.

#### Actual Result
The CLI/API return successfully:
```
Successfully deleted namespace "jrasell"!
```

The agent logs show an error deleting the namespace:
```
    2023-12-11T07:59:40.627Z [ERROR] nomad.fsm: DeleteNamespaces failed: error="namespace \"jrasell\" contains at least one variable. All variables in namespace must be deleted before it can be deleted"
    2023-12-11T07:59:40.627Z [DEBUG] http: request complete: method=DELETE path=/v1/namespace/jrasell duration="272.75µs"
```

**Comment by tgross** [comment]
See also: https://github.com/hashicorp/nomad/issues/17088
