### ISSUE TITLE
[RFC] new interpolation key: NOMAD_ALLOC_COUNT

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1942]
Hi,

Today we have `NOMAD_ALLOC_INDEX` which is the numeric task "increment" for the current allocation within its group.

It would be nice to have `NOMAD_ALLOC_COUNT` or (`NOMAD_ALLOC_TOTAL`) with the `count` value of the entire task group.

This can be used to interpolate tasks with "expected number of servers", for example Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-gateway.html which have `gateway.expected_nodes` - having this value go out of sync with the group count can be quite a problem recovery wise.

Since it would be a "dynamic" value, if used, it would have to gracefully restart all tasks within the group (desired in the case of ElasticSearch) 

I guess it's a more complex feature request than I initially thought when I wrote this ticket, but I leave it here for consideration and comments

**Comment by dadgar** [comment]
Hey,

Don't remember if I talked to you on Gitter about this but I think we should close the issue and I will explain why.

The count of a job is not a static value and environment variables are. As you mentioned to ensure this value is correct, jobs would have to be restarted. However this is a highly undesirable behavior for jobs that do not have any dependency to other instances of the task group (the vast majority of tasks). I think this is better accomplished by storing the services desired count in a key in consul-template or in a template itself in Nomad. That way the user gets to define the restart behavior and it doesn't affect every task.

I am going to close it but feel free to respond if you disagree.
