### ISSUE TITLE
Documentation: dead links/incorrect links

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/nomad#19456]
In the documentation for vault integration (https://developer.hashicorp.com/nomad/docs/integrations/vault-integration#migrating-to-using-workload-identity-with-vault) there are 2 links referenced that go to the wrong section and basically do not work: 

> Enable [vault.default_identity](https://developer.hashicorp.com/nomad/docs/configuration/consul#default_identity) blocks in your Nomad server agent configurations.
>
> (Optionally) Add [vault.role](https://developer.hashicorp.com/nomad/docs/configuration/consul#role) fields to any Nomad jobs that will not use the default role.

The "consul" section does not have said anchors, and since we're talking about vault integration I'm pretty sure they need to be sent to the vault block(s) docs.

**Comment by lgfa29** [comment]
Thanks for the report @benvanstaveren!

I'm reworking some content on this page so I will make sure to fix this link as well.

**Comment by benvanstaveren** [comment]
Cheers! Maybe also add some documentation on what is supported on the JWT's claim_mappings, right now from the example all I can see is the nomad namespace and job id, and I'd love to be able to get some of the job's metadata into the claim mapping as well, somehow... but it doesn't mention if that's possible or how to go about that :D

**Comment by tgross** [comment]
#19424 has updates on what's available.

>  and I'd love to be able to get some of the job's metadata into the claim mapping as well, somehow... but it doesn't mention if that's possible or how to go about that 

It's not currently possible. We've got https://github.com/hashicorp/nomad/issues/19438 open discussing that. If you'd like to chime in with some motivating use cases, that'd be super helpful!
