### ISSUE TITLE
add ParseFromString function in jobspec package

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/nomad#1950]
I notice there is a  ValidateCommand struct which does most of the work of job validation. But consider the signature of the `Parse` function:

`
func Parse(r io.Reader) (*structs.Job, error)
`

It would be convenient to validate a job in string format rather than a file or a `io.Reader`.

Could you export a function like `ParseFromString` in `jobspec/parse.go`?

**Comment by dadgar** [comment]
Hey,

Could you use this as an alternative? https://golang.org/pkg/strings/#NewReader
