### ISSUE TITLE
/v1/evaluation/:id/allocations gives inconsistent responses

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1951]
### Nomad version

Nomad v0.5.0-rc1 ('a8c8199e413d387021a15d7a1400c8b8372124d6+CHANGES')

### Operating system and Environment details

Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy

Linux version 4.7.6 (root@xxx) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Sun Oct 2 13:15:49 UTC 2016

### Issue

Submitting a job through the API, and right away hitting the `/v1/evaluation/:id/allocations` gives an API response like this ( https://gist.github.com/jippi/1d67a7e2ed924884c69db5e6bca71a72 ) 

That's the first surprise, the job should be a NOOP, i just read it out, changed a `Meta` key and submitted it back to Nomad - there should be zero new allocations, and inspecting the job and its allocation also show 0 changes.

Now for the even weirder, after ~30-60s, hitting the `/v1/evaluation/:id/allocations` endpoint again with the same `EvalID` returns nothing but `[]` (which is what I expected to be returned, since the task for a NOOP after all)

Is it intended behavior that I'm seeing or a bug? it only happens for some of the jobs, and adding a random jitter (0-60s) between submitting the job and reading the eval allocations does not yield any consistent behavior either

**Comment by dadgar** [comment]
Do you have reproduction steps?

**Comment by jippi** [comment]
@dadgar i can try and cook something up, but when i hit the bug, it seemed completely random, different jobs every time :o

**Comment by jippi** [comment]
haven't seen this in a long time, closing
