### ISSUE TITLE
Unable to restart a job with file templates from the UI in 1.6.5

### ISSUE THREAD

**Issue by Tirieru** [hashicorp/nomad#19550]
### Nomad version
1.6.5

### Operating system and Environment details
Ubuntu 22.04.3

### Issue
If a job with a file template is stopped, it can't be started again from the UI.

### Reproduction steps
1. Create a job with a template block where the data parameter comes from a file
2. Run the nomad job
3. Stop the nomad job from the UI
4. Start the job from the UI

#### Expected Result
The job starts.

#### Actual Result
The job doesn't start, and the UI shows the following error:
![image](https://github.com/hashicorp/nomad/assets/11166583/1b3205dd-facf-4609-ac2c-89ed962c7f56)

### Job file
A minimal job example:
```
job "apache" {
  datacenters = ["dc1"]
  type        = "service"

  group "apache" {
    count = 1

    task "apache" {
      driver = "docker"

      config {
        image = "php:8.3.0-apache"
        volumes = [
          "local/index.php:/var/www/html/index.php"
        ]
      }

      template {
        destination = "local/index.php"
        data        = file("./index.php")
        change_mode = "restart"
      }
    }

  }
}
```

This jobs requires an `index.php` file, the following example can be used:
```php
<?php phpinfo(); ?>
```

**Comment by jrasell** [comment]
Hi @Tirieru and thanks for raising this issue.

The [file HCL2 function](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/functions/file/file) is executed by the CLI when you run the `nomad job run` command, meaning this function can only be used with files that are already present on disk on operator host. The Nomad UI does not have the ability to perform this function execution, which means a stopped job using the file function must be re-submitted in the same way the original registration occurred.

**Comment by Tirieru** [comment]
Thank you for your answer @jrasell 

If this is intended behavior, shouldn't it be tagged as a breaking change? This used to be possible before the addition of the UI Jobspec Sources in 1.6.0.  I just tested it on a 1.5.8 cluster and it works the way I expected.

**Comment by ngcmac** [comment]
I'm experience the same behaviour. This is indeed a breaking change. 

Looks like the same problem as: https://github.com/hashicorp/nomad/issues/19648
What about a fallback for the json version of the job when unable to submit the HCL in the UI?
