### ISSUE TITLE
After upgrading from 1.6 to 1.7 receiving  errors on nomad variable jobs

### ISSUE THREAD

**Issue by cberescu** [hashicorp/nomad#19555]
I have looked other the breaking changes but can't find a reason for this to happen. 

### Nomad version
Output from `nomad version`

1.7.2

### Operating system and Environment details
 Ubuntu 20.04.6

### Issue
Receiving  `Missing: nomad.var.block(nomad/jobs@default.global)` when using templates with nomad variables 

Could not find any details  about the error and why it happens. 

I am using in tasks values from the nomad/jobs variable witch  `This variable is accessible by all nomad jobs in this namespace`

**Comment by rismoney** [comment]
I experienced the same issue.  I was able to resolve it, by upgrading the clients first.  I think there is a bug in 1.6.x and prior that prevents proper variable lookup against 1.7+ variables.  Sort of goes against the recommended approach for upgrading, but it worked for me.

**Comment by cberescu** [comment]
Not something that works for me, this error appears both on server and client

**Comment by tgross** [comment]
Hi @cberescu! Sorry about the delayed response, most of us have been out for the holidays. I've been able to reproduce this but the root cause is a little mysterious to me so far. The authentication logic got reworked quite a bit during 1.7.0, but this doesn't appear to be a logic bug. I'm using the following jobspec:

<details><summary>jobspec</summary>

```hcl
job "example" {

  group "web" {

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = <<EOT
<html>
<h1>hello, {{- with nomadVar "nomad/jobs" }}{{ .name }}{{- end -}}</h1>
</html>
        EOT

        destination = "local/test.txt"
      }

      resources {
        cpu    = 100
        memory = 100
      }

    }
  }
}
```

</details>

I deploy this to a Nomad cluster of 1 server and 1 client, running Nomad 1.6.4. I upgrade the server to 1.7.2, and then a few moments later I see the following in the client logs:

> 2024-01-02T09:56:20.232-0500 [ERROR] client.rpc: error performing RPC to server: error="rpc error: msgpack decode error [pos 1164]: invalid byte descriptor for decoding bytes, got: 0xd2" rpc=ACL.WhoAmI server=192.168.1.77:4647
> 2024-01-02T09:56:20.232-0500 [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: msgpack decode error [pos 1164]: invalid byte descriptor for decoding bytes, got: 0xd2" rpc=ACL.WhoAmI server=192.168.1.77:4647
> 2024-01-02T09:56:20.232-0500 [ERROR] http: error authenticating built API request: error="rpc error: msgpack decode error [pos 1164]: invalid byte descriptor for decoding bytes, got: 0xd2" url="/v1/var/nomad/jobs?index=23&namespace=default&stale=&wait=60000ms" method=GET
> 2024-01-02T09:56:20.233-0500 [WARN]  agent: (view) nomad.var.block(nomad/jobs@default.global): Unexpected response code: 500 (Server error authenticating request) (retry attempt 9 after "1m0s")

The error appears to be in deserializing the request from the client! We use a library go-msgpack for serializing the RPC requests between client and server. During development, this happens at runtime. For production builds we do some pre-generation of the serialization code, but I see the same problem with a development build.

Once I upgrade the client to Nomad 1.7.2, everything appears to be ok. I'll continue to investigate and report back here once I know more.

**Comment by cberescu** [comment]
That is correct this is how my logs look like. I am upgrading from 1.6.5 : 

```
815]:     2024-01-02T16:21:07.116+0100 [ERROR] client.rpc: error performing RPC to server: error="rpc error: EOF" rpc=Node.GetClientAllocs server=0.0.0.0:4647
815]:     2024-01-02T16:21:07.178+0100 [ERROR] client.rpc: error performing RPC to server: error="rpc error: failed to get conn: dial tcp 0.0.0.0:4647: connect: connection refused" rpc=Node.GetClientAllocs server=0.0.0.0:4647
815]:     2024-01-02T16:21:07.178+0100 [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: failed to get conn: dial tcp 0.0.0.0:4647: connect: connection refused" rpc=Node.G
815]:     2024-01-02T16:21:07.178+0100 [ERROR] client: error querying node allocations: error="rpc error: failed to get conn: dial tcp 0.0.0.0:4647: connect: connection refused"
815]:     2024-01-02T16:21:24.484+0100 [ERROR] client.rpc: error performing RPC to server: error="rpc error: msgpack decode error [pos 194]: cannot decode signed integer: unrecognized descriptor byte: af/string|bytes" rpc=ACL.WhoAmI serv
815]:     2024-01-02T16:21:24.484+0100 [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: msgpack decode error [pos 194]: cannot decode signed integer: unrecognized descriptor b
815]:     2024-01-02T16:21:24.485+0100 [ERROR] http: error authenticating built API request: error="rpc error: msgpack decode error [pos 194]: cannot decode signed integer: unrecognized descriptor byte: af/string|bytes" url="/v1/var/noma
815]:     2024-01-02T16:21:24.485+0100 [ERROR] agent: (view) nomad.var.block(nomad/jobs/traefik@default.global): Unexpected response code: 500 (Server error authenticating request) (exceeded maximum retries)
```

**Comment by tgross** [comment]
Thanks @cberescu. I just did a `git bisect` from v1.6.5 to v1.7.2, and it looks like the culprit is (somehow) 0e22fc1a0bbf985450b9b85976db5d6d3bca2322 introduced in PR https://github.com/hashicorp/nomad/pull/18123. I know that we'd run into serialization issues around identity blocks for Nomad 1.7.0-beta.1 and this smells similar but it's not clear to me yet what the problem is.

**Comment by tgross** [comment]
Ok @cberescu, we've figured out what happened here. In Nomad 1.7.0, we changed our JWT library to one that was more suitable (to support OIDC work). That changed the signature of one of our RPC methods (`ACL.WhoAmI`) which wasn't originally intended to be sent over the wire, but that was done a while back under separate work in Nomad 1.5.0. Our upgrade testing was heavily focused on Consul templates this cycle, and we unfortunately missed that.

The immediate fix is fairly straightforward and I've got a PR up in https://github.com/hashicorp/nomad/pull/19578, and then I've got a follow-up issue in https://github.com/hashicorp/nomad/issues/19580 to fix the underlying design issue when we next touch this area of the code.

**Comment by cberescu** [comment]
@tgross thanks for the quick reply and fix

**Comment by AAverin** [comment]
Running on 1.7.5 nomad for some of the tasks I still get `Missing: nomad.var.block(nomad/jobs@default.global)` error in the UI. Can't see any other errors being present in logs though.

**Comment by nCrazed** [comment]
Experienced the same error while upgrading clients from 1.6.3 to 1.7.7. Upgrading the server fixed it
