### ISSUE TITLE
batch jobs (with `max_client_disconnect`) starts again after nomad agent is changing eligibility state 

### ISSUE THREAD

**Issue by yaroslav-007** [hashicorp/nomad#19564]
### Nomad version
Tested with v1.5.12 and v1.7.2

### Operating system and Environment details
Tested with linux
### Issue
batch jobs (with `max_client_disconnect`) starts again after nomad agent is changing eligibility state 
### Reproduction steps
1. Run the job below
2. When allocation run and exits, take note on which nomad client it was executed
3. Toggle the eligibility of that nomad client
4. See how new allocation is started (before the time)
5. This is not happening when `max_client_disconnect` is commented
#### Expected Result
Nothing should happen
#### Actual Result
New allocation is started (before the time that is supposed to)
### Job file (if appropriate)
[test-batch.hcl.txt](https://github.com/hashicorp/nomad/files/13786687/test-batch.hcl.txt)

**Comment by Juanadelacuesta** [comment]
This error should be fixed with this [PR](https://github.com/hashicorp/nomad/pull/20181) and will be out on the next release.

**Comment by Juanadelacuesta** [comment]
This error should be fixed with this https://github.com/hashicorp/nomad/pull/20181 and will be out on the next release.

**Comment by Juanadelacuesta** [comment]
Hi @madhur-df! The fix for this bug will come on the next release for versions 1.6 and  1.7 some time in may, I hope this helps!
