### ISSUE TITLE
Lost HCL job spec after upgrade (and service restart?)

### ISSUE THREAD

**Issue by EmilienR** [hashicorp/nomad#19561]
### Nomad version

Previous : 1.6.2
Updated : 1.7.2

### Operating system and Environment details

Rocky 8.9

### Issue

Hi,

After upgrading Nomad servers from 1.6.2 to 1.7.2 we lost all HCL Jobspec. The jobs start but when we try to edit the job definition we are unable to get the HCL formatted spec, only the full JSON is available.

![image](https://github.com/hashicorp/nomad/assets/6389739/29541652-880b-4d86-8b6e-c4b163e675b2)

"A jobspec file was not submitted when this job was run. You can still view and edit the expanded JSON format."

We tried to restore the 1.6.2 cluster backup in a test environnement but we couldn't get the HCL spec, only the JSON one is available...

How can we get back the HCL formatted job spec ?

### Reproduction steps

Upgrade a cluster from 1.6.2 to 1.7.2 or restore a 1.6.2 cluster

**Comment by jrasell** [comment]
Hi @EmilienR and thanks for raising this issue. I have been able to reproduce this locally and will look into raising a PR to fix this.
