### ISSUE TITLE
Incorrect table spacing in Allocations UI

### ISSUE THREAD

**Issue by siegbenn** [hashicorp/nomad#19614]
### Nomad version
Nomad v1.7.2
BuildDate 2023-12-13T19:59:42Z
Revision 64e3dca9274b493e38a49fda3a70fd31d0485b91

### Operating system and Environment details
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Issue
There is incorrect spacing in the Nomad UI Allocations tables when running the agent with -dev.
### Reproduction steps
Install nomad, run $ nomad agent dev, run a job, look at the allocations table.

<img width="1512" alt="Screenshot 2024-01-04 at 5 53 13 PM" src="https://github.com/hashicorp/nomad/assets/2792167/4fb573f8-99ec-4cea-a9ba-e20562ba222f">

**Comment by philrenaud** [comment]
Thanks, @siegbenn - I think i know the source of the problem. Look for an update soon!

**Comment by philrenaud** [comment]
Hi @siegbenn — turns out this has already been fixed via https://github.com/hashicorp/nomad/pull/19505 and should be included in an upcoming release soon. Thanks again for reporting this issue, and let us know if you notice anything else out of place.
