### ISSUE TITLE
Batch/Periodic Job Health Checks

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/nomad#1964]
Hi,

It'd be nice to have consul integration in some capacity for batch jobs. When a batch job fails, exits non-zero, or otherwise, it would be nice to know via a failed consul health check. Alternatively, allowing as a pre/post hook to register/deregister with consul (or hook directly into our monitoring setup) could work too.

Given that all users might not want this, it could either be opt in via job config, opt in via client config, tagged separately in consul, etc...

Thanks!

Reference google group content: https://groups.google.com/forum/#!topic/nomad-tool/3CMJCuOY4GA

### Nomad version
Currently running 0.4.1

### Operating system and Environment details
Ubuntu

### Issue
Feature request: see top.

**Comment by dadgar** [comment]
@justinwalz Is the primary use case around the monitoring system? If so I wonder if the pre/post hook is the better way forward

**Comment by justinwalz** [comment]
Yes - essentially, we'd like better insight into the behavior of our batch and periodic jobs, especially when they fail. Right now we solved it with a wrapper entrypoint that outputs in a format ingestible by our monitoring system, but official support for hooks would definitely be an improvement.

**Comment by dadgar** [comment]
@justinwalz Should we close in favor of https://github.com/hashicorp/nomad/issues/1061 then?

**Comment by justinwalz** [comment]
Eh, maybe. It would help, but the onus would be on each individual user to implement (or use community pre/post hooks) to the the functionality desired. I still think it would be a nice feature provided by nomad to create a failing health check when batch/periodic jobs fail and remove it when they succeed.

The idea is similar to how nomad integrates with consul for services - this aspect of nomad is great and has become a fundamental feature for us.

**Comment by dadgar** [comment]
The thing that is unclear to me is the exact points in which it would be registered/deregistered from Consul.

Is it when the job is submitted it is an unhealthy check and only if completes it goes healthy? In that case when does it get deleted?

Or are you asking about checks per shard (count > 1). If you could add a bit more detail to the request that would be appreciated.

**Comment by justinwalz** [comment]
Case: job doesn't exist => nothing in consul
Case: job stopped (regardless of current status) => nothing in consul
Case: new job first created or currently running => healthy in consul
Case: job (regardless of current status) finished successfully => healthy in consul
Case: job (regardless of current status) finished with an error => unhealthy in consul

This would fit our use case and current monitoring paradigm for services in consul. Anything healthy or running (service, batch, periodic, etc) is in a good state. At any point something is unhealthy (service failing health check, batch job exiting with error) we send alerts / trigger monitors. If we don't care that it failed, we can trigger a stop to clean up state.

**Comment by dadgar** [comment]
@justinwalz In the last two cases who cleans up that health check?

It is an interesting idea but honestly seems like an abuse of Consul. The health checks should be on a running process not as a generic alerting system.

**Comment by justinwalz** [comment]
@dadgar Okay, that's fine. We can probably get this done with pre/post hooks when it is released. I mostly created this issue after you said I should in the google group post, so feel free to close if it is a wont-fix.

**Comment by dadgar** [comment]
@justinwalz Sounds good. Yeah I think I misunderstand on the mailing list. I am going to close this issue for the explained reason! Thanks

**Comment by sepulworld** [comment]
I needed a health check mechanism for periodic jobs as well. I put this together to help out until there is some built in integrations. It might be useful for others. Does some "Deadman Switch" monitoring based upon EPOCH time values. 

https://github.com/sepulworld/deadman-check
