### ISSUE TITLE
Jobs index stub: provide an integer that sums up the counts of all a job's groups

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#19641]
One of the takeaways from the [Job Page Redesign](https://github.com/hashicorp/nomad/issues/16128) was that people really want to know "am I running 100% of the allocations that I asked for?"

We used to grab this number from just one place: when showing a job's deployment: we show the `25` below by [summing the deployment's taskGroups' `count` integers](https://github.com/hashicorp/nomad/blob/a9d61ea3fd9ecb51d64534b30fe5938024336787/ui/app/models/deployment.js#L67):
![image](https://github.com/hashicorp/nomad/assets/713991/be3c8414-adef-4201-9964-18e13e8ef3f6)

This is helpful when we have deployments info, but we don't grab that on a job index page so we [manually sum job.taskGroups[].count](https://github.com/hashicorp/nomad/blob/a9d61ea3fd9ecb51d64534b30fe5938024336787/ui/app/components/job-status/panel/steady.js#L142-L150) ourselves in the front-end.

Well... on the jobs index page, we don't even have `jobs[].taskGroups[]`, so that's out the window.

What I'd like is for that summation to happen on the backend, and be provided back with the jobs at `GET /jobs`, possibly as a property called `desiredAllocationCount` or something.

This would let us do things like provide a [degraded flag](https://github.com/hashicorp/nomad/pull/17599) for jobs when `job.allocs[].countBy('running') < job.desiredAllocationCount` or similar.

This would also help inform the "What % of the dataviz bar should be green vs red" for the status bar that https://github.com/hashicorp/nomad/issues/19339 will enable.

Note: As the front-end totalAllocs() code indicates, this isn't really going to possible for system/sysbatch jobs, and that's okay. We should just get a null back there.

**Comment by gulducat** [comment]
At present we're leaning towards rolling this into the new endpoint in #19339 and using that as the source for all info on the UI jobs index page instead of `/jobs`
