### ISSUE TITLE
allow `memory_max` as `-1` for raw_exec jobs

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#19645]
### Proposal
Allow `memory_max` to be specified as `-1` indicating "no limit". This would help to mimic behavior of agents prior to v1.7.x

### Use-cases
I (and others)  have relied on the fact that `raw_exec` used to run with no memory constraints till now.

But, as now `raw_exec` also enforces cgroup memory limits, it would be good to be able to specify a "don't care" value.

refs: https://github.com/hashicorp/nomad/pull/19596

### Attempted Solutions
As suggested in https://github.com/hashicorp/nomad/issues/19588 tried with a large `memory_max` value to unblock current work loads

**Comment by shoenig** [comment]
Implemented in https://github.com/hashicorp/nomad/pull/19670 (going into 1.7.x, 1.8)
