### ISSUE TITLE
E2E: Consul WI test needs refactoring

### ISSUE THREAD

**Issue by pkazmierczak** [hashicorp/nomad#19698]
I recently [removed](https://github.com/hashicorp/nomad/pull/19697) a broken Consul WI integration test from the E2E suite, because it requires a bigger refactoring. This test fails because we use HCP Consul which won't be able to connect to Nomad's JWKS endpoints over TLS. A solution would be to run Nomad and Consul locally for that test, much like we do in the [consulcompat](https://github.com/hashicorp/nomad/blob/main/e2e/consulcompat/shared_setup_test.go) tests. Ideally we should extract common configuration and setup methods from consulcompat tests into `e2eutil` and rewrite the removed test.

**Comment by gulducat** [comment]
Might be able to expose `/.well-known/*` to public internet for Consul to reach (maybe a Task API proxy job?), but would also require some cloud plumbing to TLSify it, and route traffic appropriately...

**Comment by tgross** [comment]
See also https://github.com/hashicorp/nomad/issues/19250

**Comment by tgross** [comment]
I'm going to close this issue as this was effectively covered by work in https://github.com/hashicorp/nomad/pull/20278. I've still got #19250 open to clean up the remaining Consul E2E tests.
