### ISSUE TITLE
Cpu and mem settings to docker contaienr propagted wrong

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#19736]
If I set the resources  stanza as shown below then the container sees all cpu cores and full worker memory

```hcl
    resources {
        cpu    = 2000
        memory = 8096
        memory_max= 32768
      }
```

If I set the resources  stanza  as shown below then the container sees cpu 2 cores and full worker memory
```hcl
    resources {
        cores    = 2
        memory = 8096
        memory_max= 32768
      }
```

A ab contiainer like timescaledb runs after that setting woth wrong cpu and memory assumptions

Is that a bug or feature ?   😂

### Docker version
`Docker version 24.0.7, build afdd53b`

### Nomad version
`Nomad v1.7.2
BuildDate 2023-12-13T19:59:42Z
Revision 64e3dca9274b493e38a49fda3a70fd31d0485b91`

**Comment by tgross** [comment]
@suikast42 setting `cores = 2` restricts the container to 2 cores. That's what the [`cores`](https://developer.hashicorp.com/nomad/docs/job-specification/resources#cores) setting is for. What were you expecting?

**Comment by suikast42** [comment]
> @suikast42 setting `cores = 2` restricts the container to 2 cores. That's what the [`cores`](https://developer.hashicorp.com/nomad/docs/job-specification/resources#cores) setting is for. What were you expecting?

The cores works as excpeted. 

The cpu   setting on the other not. 

But I found the reason. 

The docker driver documeneation: 

[cpu_hard_limit](https://developer.hashicorp.com/nomad/docs/drivers/docker#cpu_hard_limit) - (Optional) true or false (default). Use hard CPU limiting instead of soft limiting. By default this is false which means soft limiting is used and containers are able to burst above their CPU limit when there is idle capacity.

After setting the cpu_hard_limit to true, the job does not over consume the cpu.
