### ISSUE TITLE
Missing documentation on Consul integration via Migrating to Workload Identities

### ISSUE THREAD

**Issue by jpwarren** [hashicorp/nomad#19747]
The documentation at https://github.com/hashicorp/nomad/blob/main/website/content/docs/configuration/consul.mdx refers to a non-existent part of the page at https://developer.hashicorp.com/nomad/docs/integrations/consul#migrating-to-using-workload-identity-with-consul

It appears the documentation on migrating Nomad's integration with Consul to use Workload Identities has not yet been written.

This makes successful migration somewhat challenging as I'm not especially familiar with the new workload identities concept, and ACL configuration is somewhat complex at the best of times.

**Comment by t-davies** [comment]
Looks like it should actually point here
https://developer.hashicorp.com/nomad/docs/integrations/consul/acl#migrating-to-using-workload-identity-with-consul
