### ISSUE TITLE
feature: allow newlines to be copied to variables values.

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#19759]
### Proposal
I propose to allow newlines to be copied inside variable values in the GUI
Additionally, would be great if the input field would be resizable.

Selecting text like the following and clicking ctrl+c and pasting it into key-value field

```
one line.
seconds line.
third line.
```

removes the newlines.

In other words, I propose the key-value field to be a text area, not input, I think it is here https://github.com/hashicorp/nomad/blob/main/ui/app/components/variable-form.hbs#L130 .

### Use-cases
The use case is to copy ssh private key. It has newlines in it.

### Attempted Solutions
The current solution is to use `jq -Rsa . | pbcopy` to newline and use the JSON editor in gui to paste it.

**Comment by tgross** [comment]
Hi @Kamilcuk I know multi-line variables in the UI were added in https://github.com/hashicorp/nomad/pull/19544 but I'm not sure how that component actually deals with the problem you're describing. I'll mark this for investigation.

**Comment by Kamilcuk** [comment]
Hi, thank you. I am still using nomad 1.6. From the look of the linked issue, I think this can be closed as done.
