### ISSUE TITLE
Cpu limit in mhz not tollereated

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#19758]
### Nomad Version
Nomad v1.7.3
BuildDate 2024-01-15T16:55:40Z
Revision 60ee328f97d19d2d2d9761251b895b06d82eb1a1

I deploy this examplkle job shown below. 

```hcl 
job "highcpu" {

  group "highcpu" {
    count = 1

    network {
      mode = "bridge"
    }


    task "highcpu" {
      driver = "docker"
      #      driver = "containerd-driver"
      config {
        image = "suikast42/cpuload"
        args  = ["stress", "--cpu", "12", "--timeout", "3600s"]
#        args  = ["stress" ,"--verbose", "--timeout 60s","--cpu 1","--io 1", "--vm 1"]
      }

      resources {
#        cores     = 1 --> that works. Load is max on one core
        cpu = 100 # --> All Cpus are on 100%
        memory = 128
      }
    }
  }
}
```

My excapction with cpu = 100 was that the job do not overconsume the cpu. 
This works as expeted with cores settins. 

Is that a Bug or feature ? 

My Cpu usage with cpu = 100

![image](https://github.com/hashicorp/nomad/assets/5046525/39bf1c2e-4a6b-4e02-a81a-9489fd550b1a)

![image](https://github.com/hashicorp/nomad/assets/5046525/a545291e-bb5b-4b6b-b243-143f409c829d)

**Comment by tgross** [comment]
@suikast42 the `resources.cpu` represents the reservation for the scheduler. It's up to the task driver to implement any actual restrictions. On Docker on Linux (and a majority of task drivers on Linux), this is implemented as CPU shares, which is a soft limit. See the [CPU Concepts documentation](https://developer.hashicorp.com/nomad/docs/concepts/cpu#allocating-cpu-resources) for a detailed discussion.

You can change this behavior for the `docker` driver with [`cpu_hard_limit`](https://developer.hashicorp.com/nomad/docs/drivers/docker#cpu_hard_limit).

**Comment by suikast42** [comment]
> @suikast42 the `resources.cpu` represents the reservation for the scheduler. It's up to the task driver to implement any actual restrictions. On Docker on Linux (and a majority of task drivers on Linux), this is implemented as CPU shares, which is a soft limit. See the [CPU Concepts documentation](https://developer.hashicorp.com/nomad/docs/concepts/cpu#allocating-cpu-resources) for a detailed discussion.
> 
> You can change this behavior for the `docker` driver with [`cpu_hard_limit`](https://developer.hashicorp.com/nomad/docs/drivers/docker#cpu_hard_limit).
I got it thanks.

But I can't set this on driver setting for agent,., Only on job level. 
See https://github.com/hashicorp/nomad/issues/19758
