### ISSUE TITLE
docs: duplicate parameter in upstreams spec.

### ISSUE THREAD

**Issue by magic-element** [hashicorp/nomad#19789]
### Nomad version
v1.7.x

### Issue
In the specification of the "upstreams" block, the “config” parameter is duplicated in the description of parameters.
https://developer.hashicorp.com/nomad/docs/job-specification/upstreams

**Comment by lgfa29** [comment]
Thanks for the report @magic-element!

I've opened https://github.com/hashicorp/nomad/pull/19877 to remove the duplicate entry.
