### ISSUE TITLE
sidecar_task support for volume_mount

### ISSUE THREAD

**Issue by mmcquillan** [hashicorp/nomad#19786]
### Proposal

Desire to mount system certificates to enable HTTPS for external services exposed through the Gateway Block (Terminating).

Use case of system certificates configured as a host volume, and exposing natively through a sidecar_task would enable Terminating Gateway CA implementation to be aligned with their current practices outside of the service mesh integration.

Two workarounds in the interim -
1. Custom Envoy Image with certs built into the image.
2. An exec task that copies the system certs to the allocation directory for the Terminating Gateway to read.

**Comment by tgross** [comment]
Draft PR for this is up here: https://github.com/hashicorp/nomad/pull/20575

**Comment by tgross** [comment]
Will ship in Nomad 1.8.0
