### ISSUE TITLE
Envoy proxies always crash after a restart of the host

### ISSUE THREAD

**Issue by avandierast** [hashicorp/nomad#19781]
Hello :)

### Issue

After the restart of an instance, the envoy proxies are crashing.
The error in the log is:
`error initializing configuration '/secrets/envoy_bootstrap.json': Invalid path: /secrets/envoy_bootstrap.json`.
A strong hypothesis is that /secrets is a tmpfs and thus it's wiped when restarting.

The envoy_bootstrap.json is created by nomad directly in the /secrets. It doesn't seem to be possible to change that: https://github.com/hashicorp/nomad/blob/fce30f342c681343fdfe712551736a62efc609e3/client/allocrunner/taskrunner/envoy_bootstrap_hook.go#L272
And the /secrets is always using tmpfs: https://github.com/hashicorp/nomad/blob/fce30f342c681343fdfe712551736a62efc609e3/client/allocdir/fs_linux.go#L63

Is there any way we can bypass this problem ?
We use nomad in a context where there is restarts and it would be great to not have to wait for all proxies to be rescheduled.

It also prevents us from using /secrets to store secret files since it would mean we don't have it anymore after a restart and must reschedule to rebuild it.

### Reproduction steps

Start any job with a consul connect proxy on an instance and restart the instance without draining the node.
It may not work if nomad is in -dev since it may drain the node when stopping.

### Nomad version
```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Operating system and Environment details
Linux 4.18.0-372.9.1.el8.x86_64

Thanks for your help :)

**Comment by schmichael** [comment]
Thanks for the report @avandierast! Should be fixed in the next release.
