### ISSUE TITLE
Incorrect Vault TLS Keys Documented on Website

### ISSUE THREAD

**Issue by bfeeser** [hashicorp/nomad#1981]
### Nomad version
Output from `nomad version`
Nomad v0.5.0-rc2 ('99e5c56e4d0d18c90296fed0650192f7dd7dc66f')

### Operating system and Environment details
N/A

### Issue
- On website, incorrect TLS keys are documented for Vault configuration
- I see that these keys are properly documented [here](https://github.com/hashicorp/nomad/blob/v0.5.0-rc2/website/source/docs/agent/configuration/vault.html.md)

### Reproduction steps
- Go here https://www.nomadproject.io/docs/agent/configuration/vault.html
- See `tls_*_file` keys mentioned; `ca_file`, `key_file`, and `cert_file` are the correct keys

**Comment by dadgar** [comment]
Hey,

I think you filed the issue in-between the RC being released and the website being pushed! The website shows the updated keys. I am going to close, but if I misunderstood please let me know!

Thanks,
Alex
