### ISSUE TITLE
Using `jobspec` to parse config requires all drivers

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/nomad#1982]
Using the `jobspec` package to simply parse a jobspec requires the driver package which requires every built-in driver for validation of the configuration. There is no way to separate _parse_ from _validation_, which is what I need in order to simply send the jobspec to the Nomad API. I don't want any validation.

We have to use a patched jobspec parser in Terraform until this is fixed. :(

**Comment by dadgar** [comment]
This has been fixed since v0.5.5
