### ISSUE TITLE
Support of the environments on Nomad like REGION/DATACENTER

### ISSUE THREAD

**Issue by obenziane2** [hashicorp/nomad#1983]
Does anyone know if nomad supports the definition of an environment like:prod, staging, dev, test, etc.. like you would specify the region or datacenter from the job_file ?  If no, how would you track and control what needs to be deployed across multiple environments ? It sounds like i need to spin up a NOMAD server for each environment ? Also the ability to override the docker tag release is highly recommended , like us we don't use the docker "tag:latest since in order to see what's in there.

Thanks

**Comment by schmichael** [comment]
I responded on the mailing list. Feel free to continue the discussion either place:

<details>
>If you only have a single instance for testing or staging feel free to enable both the client and server on a single node. That - among other things - is what the -dev flag does. Having a single node be a client and server works fine but is discouraged for a variety of performance and reliability reasons in production.
>
>To control where jobs are scheduled use constraints. The node_class is probably the easiest way to say, deploy web services to "web" nodes. However, it's worth noting that having fine grained control over where jobs are scheduled is kind of an antipattern in Nomad. If you define the resources your jobs need in their configuration, Nomad should schedule them fairly optimally.
</details>

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nomad-tool/zf5-yD2UYPU/KhqI_-IuAgAJ

**Comment by dantoml** [comment]
Closing this because it was resolved in the [mailing lists](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nomad-tool/zf5-yD2UYPU/KhqI_-IuAgAJ).

Please don't hesitate to file a new issue or message the list if you have any further problems.
