### ISSUE TITLE
TLS CA create command with name-constraint

### ISSUE THREAD

**Issue by guillaumejchauveau** [hashicorp/nomad#19836]
### Nomad version
Bug occurs on versions 1.6.0, 1.7.[1,2,3].

### Operating system and Environment details
Fedora 39, Rocky Linux 9.

### Issue
Using the CLI command `nomad tls ca create -name-constraint="true" -domain="foo.com"` yields `Please provide the -domain flag if you want to enable custom domain constraints`.
Nomad version 1.5.0 behaves as expected.

### Reproduction steps
Use Nomad version 1.6.0 or 1.7.[1,2,3]. Run the command `nomad tls ca create -name-constraint="true" -domain="foo.com"`.

#### Expected Result
```
==> CA certificate saved to: foo.com-agent-ca.pem
==> CA certificate key saved to: foo.com-agent-ca-key.pem
```

#### Actual Result
```
Please provide the -domain flag if you want to enable custom domain constraints.
```

**Comment by lgfa29** [comment]
Thanks for the report @guillaumejchauveau.

I think the bug was introduced in https://github.com/hashicorp/nomad/pull/17309, where the `-domain` flag is being overwritten unless you specify other customization flags. I've opened https://github.com/hashicorp/nomad/pull/19892 to fix this.
