### ISSUE TITLE
Ctrl+W in Exec in web UI closes the window without prompting

### ISSUE THREAD

**Issue by WxNzEMof** [hashicorp/nomad#19849]
### Nomad version
I don't know because I'm using the web interface and it's not telling.

### Operating system and Environment details
Firefox

### Issue
The Exec feature in the Nomad web interface is very useful. However, one small problem is that Ctrl+W on the web means to close the current tab. I find myself frequently pressing with the intention to delete the last word, but it closes the entire window instead.

If it's not possible to capture the key bind, it would be nice if Nomad asked for confirmation when closing an Exec window that's still connected to a container.

### Reproduction steps
Open Nomad web UI
Open a job
Click Exec
Select a task
Press Enter to run the pre-filled command
Type something
Press Ctrl+W

#### Expected Result
Ideally, delete the last typed word (standard bash behaviour).
Slightly less ideally, make the browser prompt me if I really intend to close the tab.

#### Actual Result
The window closes, losing my session entirely.

### Nomad Client logs (if appropriate)

Thanks!

**Comment by philrenaud** [comment]
Thanks for the request, @WxNzEMof — this seems reasonable and I'll see about implementation.

**Comment by philrenaud** [comment]
Hi @WxNzEMof , we ended up exploring the idea of preserving hot-keys in the terminal emulator here, but found enough corner cases that we decided to go with a warning/prompt before exiting instead. Hopefully this solves your issue well enough, and thanks again for raising this issue!

**Comment by WxNzEMof** [comment]
Thank you !!!
