### ISSUE TITLE
 Memory `MaxUsage` stat misreported for tasks using the docker driver in Linux clients

### ISSUE THREAD

**Issue by rostow** [hashicorp/nomad#19854]
### Nomad version
Nomad v1.6.2
BuildDate 2023-09-13T16:47:25Z
Revision 73e372ad94033db2ceaf53468b270a31544c23fd

### Operating system and Environment details
- Ubuntu 22.04 clients and servers (AWS EC2 both Metal and 32xlarge VMs)
- `cgroups-v2` disabled, so effectively using `cgroups-v1`
- Docker version 24.0.5, build ced0996

### Issue
The memory stat `MaxUsage` seems to be misreported for allocation tasks using the docker driver in Linux clients.

In our case, we are running a job with a main task using the docker driver for which we request 20GB of memory in the job description. We know (from running it locally) that this container uses a maximum of around 6GB of memory. However, in Nomad the `MaxUsage` is reported at around 19-20GB, close to the memory request. We were very skeptical so I launched the job and watched the task stats live from the Nomad UI, and the max memory used was around 5-6GB by looking at the peak of the memory graph, which matches what we observe locally, however, calling `/v1/client/allocation/:allocationId/stats` returns a `MaxUsage` of 19-20GB.

### Reproduction steps
1. Disable `cgroups-v2` in an Ubuntu 22.04 client, (otherwise no MaxUsage will be reported)
1. Run a Nomad job with tasks using the docker driver in a Linux client with Ubuntu version >= 21
1. Observe the stats for the task in the UI during the lifetime of the job and note the maximum amount of memory used (peak in the graph). Alternatively, keep polling the client allocation stats endpoint and record all the samples, getting the max value of the `Usage` memory stat.
1. When the job is done, call the [client allocations stats endpoint](https://developer.hashicorp.com/nomad/api-docs/client#read-allocation-statistics)

#### Expected Result
Memory `MaxUsage` should report a value more or less aligned with the maximum value reported by the memory `Usage` stat across the lifetime of the task.

#### Actual Result
Memory `MaxUsage` reports a much higher value  (3-4x) than what the container actually used /  what was observed in the graph / the max value recorded for the `Usage` stat.

**Comment by lgfa29** [comment]
Hi @rostow 👋 

I have not been able to reproduce this problem. The value reported by Nomad is pulled directly from the Docker API:
https://github.com/hashicorp/nomad/blob/5825cefe5127ada52c1ad9a7e540258e004a1b6e/drivers/docker/util/stats_posix.go#L36-L44

Here are the outputs I get
<details>
<summary>Docker API</summary>

```console
$ curl --unix-socket /Users/$USER/Library/Containers/com.docker.docker/Data/docker.raw.sock 'http:/v1.44/containers/edefa642353c5edf16bba22da520f9c5406e5c777d11d3943284bf390c9915b8/stats?stream=false'  | jq . |

{
  "read": "2024-02-06T22:20:30.839264258Z",
  "preread": "2024-02-06T22:20:29.833290049Z",
  "pids_stats": {
    "current": 5
  },
  "blkio_stats": {
    "io_service_bytes_recursive": [],
    "io_serviced_recursive": [],
    "io_queue_recursive": [],
    "io_service_time_recursive": [],
    "io_wait_time_recursive": [],
    "io_merged_recursive": [],
    "io_time_recursive": [],
    "sectors_recursive": []
  },
  "num_procs": 0,
  "storage_stats": {},
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 1323743666,
      "percpu_usage": [
        151278213,
        34899372,
        85648834,
        116371712,
        110468119,
        151226332,
        196057124,
        216206286,
        127486378,
        134101296
      ],
      "usage_in_kernelmode": 670000000,
      "usage_in_usermode": 640000000
    },
    "system_cpu_usage": 5572550000000,
    "online_cpus": 10,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 1321633084,
      "percpu_usage": [
        151278213,
        34899372,
        85648834,
        114261130,
        110468119,
        151226332,
        196057124,
        216206286,
        127486378,
        134101296
      ],
      "usage_in_kernelmode": 670000000,
      "usage_in_usermode": 640000000
    },
    "system_cpu_usage": 5562570000000,
    "online_cpus": 10,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "memory_stats": {
    "usage": 23543808,
    "max_usage": 24485888,
    "stats": {
      "active_anon": 8400896,
      "active_file": 13123584,
      "cache": 13983744,
      "dirty": 0,
      "hierarchical_memory_limit": 314572800,
      "hierarchical_memsw_limit": 314572800,
      "inactive_anon": 0,
      "inactive_file": 860160,
      "mapped_file": 6828032,
      "pgfault": 2270,
      "pgmajfault": 91,
      "pgpgin": 4486,
      "pgpgout": 576,
      "rss": 8060928,
      "rss_huge": 4194304,
      "total_active_anon": 8400896,
      "total_active_file": 13123584,
      "total_cache": 13983744,
      "total_dirty": 0,
      "total_inactive_anon": 0,
      "total_inactive_file": 860160,
      "total_mapped_file": 6828032,
      "total_pgfault": 2270,
      "total_pgmajfault": 91,
      "total_pgpgin": 4486,
      "total_pgpgout": 576,
      "total_rss": 8060928,
      "total_rss_huge": 4194304,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
    "limit": 314572800
  },
  "name": "/redis-afbada2f-01e4-3776-eb51-fe52c4439e8d",
  "id": "edefa642353c5edf16bba22da520f9c5406e5c777d11d3943284bf390c9915b8",
  "networks": {
    "eth0": {
      "rx_bytes": 1532,
      "rx_packets": 18,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 0,
      "tx_packets": 0,
      "tx_errors": 0,
      "tx_dropped": 0
    }
  }
}
```
</details>

<details>
<summary>Nomad API</summary>

```console
$ nomad operator api /v1/client/allocation/afbada2f-01e4-3776-eb51-fe52c4439e8d/stats | jq .
{
  "ResourceUsage": {
    "CpuStats": {
      "Measured": [
        "Throttled Periods",
        "Throttled Time",
        "Percent"
      ],
      "Percent": 0.2379429287863591,
      "SystemMode": 0.0,
      "ThrottledPeriods": 0,
      "ThrottledTime": 0,
      "TotalTicks": 7.126866603009027,
      "UserMode": 4215.334459389679
    },
    "DeviceStats": [],
    "MemoryStats": {
      "Cache": 13983744,
      "KernelMaxUsage": 0,
      "KernelUsage": 0,
      "MappedFile": 6828032,
      "MaxUsage": 24485888,
      "Measured": [
        "RSS",
        "Cache",
        "Swap",
        "Usage",
        "Max Usage"
      ],
      "RSS": 8060928,
      "Swap": 0,
      "Usage": 23539712
    }
  },
  "Tasks": {
    "redis": {
      "Pids": null,
      "ResourceUsage": {
        "CpuStats": {
          "Measured": [
            "Throttled Periods",
            "Throttled Time",
            "Percent"
          ],
          "Percent": 0.2379429287863591,
          "SystemMode": 0.0,
          "ThrottledPeriods": 0,
          "ThrottledTime": 0,
          "TotalTicks": 7.126866603009027,
          "UserMode": 4215.334459389679
        },
        "DeviceStats": null,
        "MemoryStats": {
          "Cache": 13983744,
          "KernelMaxUsage": 0,
          "KernelUsage": 0,
          "MappedFile": 6828032,
          "MaxUsage": 24485888,
          "Measured": [
            "RSS",
            "Cache",
            "Swap",
            "Usage",
            "Max Usage"
          ],
          "RSS": 8060928,
          "Swap": 0,
          "Usage": 23539712
        }
      },
      "Timestamp": 1707258273514181635
    }
  },
  "Timestamp": 1707258273514181635
}

```
</details>

Do you have multiple tasks in the same allocation? The values reported at the top-level `ResourceUsage` field is the sum of all tasks, while Docker (and the UI if you navigate to a specific task) will show the stats for that specific task.

**Comment by rostow** [comment]
Thanks @lgfa29. We do have several tasks but the value mentioned to be misreported was taken directly from the Task, not the one at the allocation level.

To give more context, we are running [Wine](https://www.winehq.org/) to run Windows applications within the container, so not sure if this might have any repercussions in how Docker API reports the Usage and MaxUsage values.

Could you try to change the requested memory in your job spec to e.g. 10x what the job actually needs? We did this during our tests and the reported MaxUsage value was also higher, in line with the increase, even though the job was the same and it was definitely still using 5-6GB and not 20GB.

**Comment by lgfa29** [comment]
> Could you try to change the requested memory in your job spec to e.g. 10x what the job actually needs?

It doesn't, it actually reports a lower value than my previous test:

```
        "MemoryStats": {
          "Cache": 0,
          "KernelMaxUsage": 0,
          "KernelUsage": 0,
          "MappedFile": 0,
          "MaxUsage": 10833920,
          "Measured": [
            "RSS",
            "Cache",
            "Swap",
            "Usage",
            "Max Usage"
          ],
          "RSS": 8060928,
          "Swap": 0,
          "Usage": 9400320
        }
```

```
  "memory_stats": {
    "usage": 9138176,
    "max_usage": 10833920,
    "stats": {
      "active_anon": 8400896,
      "active_file": 0,
      "cache": 0,
      "dirty": 0,
      "hierarchical_memory_limit": 41943040000,
      "hierarchical_memsw_limit": 41943040000,
      "inactive_anon": 0,
      "inactive_file": 0,
      "mapped_file": 0,
      "pgfault": 2207,
      "pgmajfault": 0,
      "pgpgin": 1070,
      "pgpgout": 552,
      "rss": 8060928,
      "rss_huge": 4194304,
      "total_active_anon": 8400896,
      "total_active_file": 0,
      "total_cache": 0,
      "total_dirty": 0,
      "total_inactive_anon": 0,
      "total_inactive_file": 0,
      "total_mapped_file": 0,
      "total_pgfault": 2207,
      "total_pgmajfault": 0,
      "total_pgpgin": 1070,
      "total_pgpgout": 552,
      "total_rss": 8060928,
      "total_rss_huge": 4194304,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
```

What does the Docker API reports for your job?

**Comment by tgross** [comment]
We weren't able to reproduce this and never heard back after asking for more information. I'm going to close this out for now but feel free to reopen if we learn more.
