### ISSUE TITLE
Nomad agent panics on start up, CPU fingerprinting failure

### ISSUE THREAD

**Issue by BacchusJackson** [hashicorp/nomad#19873]
### Nomad version
Output from `nomad version`

Nomad v1.7.3
BuildDate 2024-01-15T16:55:40Z
Revision 60ee328f97d19d2d2d9761251b895b06d82eb1a1

### Operating system and Environment details

Output from `cat /etc/os-release`

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Output from `cat lscpu`

```
Architecture:         aarch64
Byte Order:           Little Endian
CPU(s):               6
On-line CPU(s) list:  0,3-5
Off-line CPU(s) list: 1,2
Thread(s) per core:   1
Core(s) per socket:   4
Socket(s):            1
Vendor ID:            ARM
Model:                3
Model name:           Cortex-A57
Stepping:             r1p3
CPU max MHz:          2035.2000
CPU min MHz:          345.6000
BogoMIPS:             62.50
L1d cache:            32K
L1i cache:            48K
L2 cache:             2048K
Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32
```

### Issue

sudo nomad agent -config /etc/nomad.d/

==> WARNING: mTLS is not configured - Nomad is not secure without mTLS!
==> Loaded configuration from /etc/nomad.d/nomad.hcl
==> Starting Nomad agent...
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/hashicorp/nomad/client/lib/numalib.(*Topology).insert(...)
        github.com/hashicorp/nomad/client/lib/numalib/topology.go:162
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCores.func1(0x4)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:115 +0x270
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).ForEach(0x2e27498?, 0x4000ad8c90?)
        github.com/hashicorp/nomad/client/lib/idset/idset.go:181 +0x158
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCores(0x3517dd0, 0x4000beb630, 0x2f3b1e0)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:109 +0x128
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).ScanSystem(0x4000ad8df8?, 0x4000beb630)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:60 +0xa8
github.com/hashicorp/nomad/client/lib/numalib.Scan(...)
        github.com/hashicorp/nomad/client/lib/numalib/detect.go:23
github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).initialize(0x4000bf92e0, 0x4000d1a1f0)
        github.com/hashicorp/nomad/client/fingerprint/cpu.go:90 +0x428
github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).Fingerprint(0x4000bf92e0, 0x1b30e80?, 0x4000c33f50)
        github.com/hashicorp/nomad/client/fingerprint/cpu.go:40 +0x24
github.com/hashicorp/nomad/client.(*FingerprintManager).fingerprint(0x4000c05200, {0x3?, 0x35624b0?}, {0x352fa50, 0x4000bf92e0})
        github.com/hashicorp/nomad/client/fingerprint_manager.go:200 +0x11c
github.com/hashicorp/nomad/client.(*FingerprintManager).setupFingerprinters(0x4000c05200, {0x4000c16600?, 0x13, 0x7?})
        github.com/hashicorp/nomad/client/fingerprint_manager.go:143 +0xc4
github.com/hashicorp/nomad/client.(*FingerprintManager).Run(0x4000c05200)
        github.com/hashicorp/nomad/client/fingerprint_manager.go:107 +0x3e0
github.com/hashicorp/nomad/client.NewClient(0x40004ea840, {0x352d038?, 0x4000138160}, 0x4000a38160, {0x3541f20?, 0x400081c000}, 0x400081c008?)
        github.com/hashicorp/nomad/client/client.go:468 +0xdd0
github.com/hashicorp/nomad/command/agent.(*Agent).setupClient(0x400081a000)
        github.com/hashicorp/nomad/command/agent/agent.go:1131 +0x280
github.com/hashicorp/nomad/command/agent.NewAgent(0x40000acfc0, {0x3569608?, 0x40008ae240}, {0x351bf80?, 0x400013d4d0}, 0x40008aa0f0)
        github.com/hashicorp/nomad/command/agent/agent.go:160 +0x1d4
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0x40001cf000, 0x40000acfc0, {0x3569608, 0x40008ae240}, {0x351bf80, 0x400013d4d0}, 0x6f636f7475612d2d?)
        github.com/hashicorp/nomad/command/agent/command.go:619 +0x74
github.com/hashicorp/nomad/command/agent.(*Command).Run(0x40001cf000, {0x40001ee1e0, 0x2, 0x2})
        github.com/hashicorp/nomad/command/agent/command.go:836 +0x534
github.com/mitchellh/cli.(*CLI).Run(0x40000ef400)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x4a8
main.Run({0x40001ee1d0, 0x3, 0x3})
        github.com/hashicorp/nomad/main.go:110 +0x220
main.main()
        github.com/hashicorp/nomad/main.go:80 +0x54

### Reproduction steps

```shell
sudo nomad agent -config /etc/nomad.d/
```

#### Expected Result

Nomad Agent properly fingerprints CPU

#### Actual Result

Panics due to index out of bound error

### Job file (if appropriate)

N/A

### Nomad Server logs (if appropriate)

N/A

### Nomad Client logs (if appropriate)

N/A

**Comment by BacchusJackson** [comment]
Note: This system is non-NUMA

```shell-session
$ numactl --hardware
No NUMA available on this system
```

**Comment by shoenig** [comment]
Hi @BacchusJackson, `18.04.6 LTS` is no longer supported by Canonical and thus no longer supported by Nomad. Can you reproduce on 20.04 or 22.04?

**Comment by lgfa29** [comment]
Hi @BacchusJackson 👋 

I haven't been able to reproduce this yet, but looking at the `lscpu` output you provided there seems to be 6 CPUs, but 2 of them are disabled.

Looking at the error generated (`panic: runtime error: index out of range [4] with length 4`) I'm wondering if Nomad is counting 4 CPUs in total but trying to access them by their CPU index instead of the list index. 

For example, in your case the list of CPUs would be `[0, 3, 4, 5]` because 1 and 2 are offline. If we try to access CPU 4 using the list index 4 it would panic because its actual list index is 2.

Would you be able to bring those two CPUs back online to see if it fixes the problem?

**Comment by BacchusJackson** [comment]
@lgfa29 Thanks for checking on this! I didn't even notice that, I'll try and see if I can get it working.

**Comment by BacchusJackson** [comment]
@lgfa29 That worked! Thank you so much! I've been beating my head against the wall for days trying to figure this out. I really appreciate it.
