### ISSUE TITLE
Unable to bind files as read-only

### ISSUE THREAD

**Issue by Rubonnek** [hashicorp/nomad#19891]
### Nomad version
Nomad v1.7.3

### Operating system and Environment details
Arch Linux

### Issue
Attempting to bind mount files as read only using the `docker` driver will generate an error message claiming the file does not exist error when the file does.

### Reproduction steps
1. Enable volumes for the docker plugin -- in particular I'm using the following configuration:

```hcl
plugin "docker" {
  config {
    allow_runtimes = [ "crun-runtime" ]
    allow_caps = [ "all" ]
    volumes {
      enabled = true
    }
  }
}

```
3. Run the following job:

```hcl
job "check-host-localtime-job" {
  type        = "batch"

  group "check-host-localtime-group" {
    count = 1
    task "check-host-localtime-task" {
      lifecycle {
        hook = "prestart"
        sidecar = false
      }

      driver = "docker"
      config {
        image = "docker.io/library/alpine:latest"
        command = "sh"
        args = [
          "-c",
          "cat /etc/localtime"
        ]
        volumes = [
          "/etc/localtime:/etc/localtime:ro",
        ]
      }
    }
  }
}
```

3. The job should fail.
#### Expected Result
Successful job execution.

#### Actual Result
Error message in the logs:
```
API error (400): failed to create task for container: failed to create shim task: OCI runtime create failed: open mount target `/etc/localtime`: Not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
#### Workaround
Remove `:ro` from `/etc/localtime:/etc/localtime:ro` in the `volumes` list.

**Comment by lgfa29** [comment]
Hi @Rubonnek 👋 

I think this value is passed directly from Nomad to Docker, so I wouldn't expect Nomad to be interfering with this 🤔 

Would you be able to test the same container configuration running directly with Docker?

And could you also try a [`bind` mount](https://developer.hashicorp.com/nomad/docs/drivers/docker#mount) instead of voulmes?

```hcl
job "check-host-localtime-job" {
  type = "batch"

  group "check-host-localtime-group" {
    count = 1
    task "check-host-localtime-task" {
      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      driver = "docker"
      config {
        image   = "docker.io/library/alpine:latest"
        command = "sh"
        args = [
          "-c",
          "cat /etc/localtime"
        ]

        mount {
          type     = "bind"
          target   = "/etc/localtime"
          source   = "/etc/localtime"
          readonly = true
        }
      }
    }
  }
}
```

Let me know how these go!

**Comment by Rubonnek** [comment]
Welp, turns out I had docker configured with `crun` as the default runtime:

`/etc/docker/daemon.json`
```json
{
        "default-runtime": "crun-runtime",
        "runtimes": {
                "crun-runtime": {
                        "path": "/usr/bin/crun"
                }
        }
}
```
And it seems that running `systemctl reload docker` is needed to properly apply that configuration. I never did that and recently I suppose `systemd` did that automatically, and it did so around the same time I installed Nomad v1.7.3 which made me think Nomad was the culprit. This issue is not really related to Nomad, but a misconfiguration on my part -- I'll stick to using the default container runtime (i.e. `containerd`).

Thanks for the quick feedback.
