### ISSUE TITLE
Mistery census for nomad

### ISSUE THREAD

**Issue by vladchu** [hashicorp/nomad#19983]
Hi friends,
Do someone hear something abount census
I want setup boundary for access to nomad job, but can't figure out how do that, in documentation boundary about this topic nothing find
can some one help me with it?

**Comment by shoenig** [comment]
Hi @vladchu, I don't think there's any documentation on using Boundary with Nomad today. Do you have a particular workflow you're trying to do? Also, I'm not sure what you mean here by "census"; that's the name of the license reporting system for Enterprise users. If you've got an Enterprise contract already, you might find going through your Support would be fruitful too.

**Comment by vladchu** [comment]
Thank you for the answer!!!
I was try to find some source to get access to my nomad jobs from boundary and find only this video (https://www.youtube.com/watch?v=i9uoTLlvG4A) at all internet. In video they use census for access, I was thinking I can do this to but can't find information about this service.
Do I understand the right to connect to nomad jobs in my cluster from the boundary I need to have an Enterprise license?

**Comment by vladchu** [comment]
And one more question can I connect to docker at server from boundary? Can't find information about it to

**Comment by tgross** [comment]
Hey @vladchu looking at that video, I believe that's referring to [Shipyard Census](https://www.shipyardapp.com/docs/blueprint-library/census/census-overview/) which is _not_ a HashiCorp product. You'd have to take up questions about how to use that with upstream. I'd recommend you take your Boundary question over to the Boundary repo.
