### ISSUE TITLE
Nomad Job RestartPolicy cannot be disabled

### ISSUE THREAD

**Issue by brucelok** [hashicorp/nomad#20004]
### Nomad version
```
$ ./nomad version
Nomad v1.7.2
BuildDate 2023-12-13T19:59:42Z
Revision 64e3dca9274b493e38a49fda3a70fd31d0485b91
```

### Operating system and Environment details
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
```

### Issue
The restart policy cannot be disabled even it's set the attempts parameter to zero and mode to `fail`.

### Reproduction steps
started up nomad agent -dev
```
$ ./nomad version
Nomad v1.7.2
BuildDate 2023-12-13T19:59:42Z
Revision 64e3dca9274b493e38a49fda3a70fd31d0485b91
$ sudo ./nomad agent -dev -bind 0.0.0.0
```
Start a brand new Redis example job (generated from `nomad job init -short`)  and set the restart `attempts = 0` and `mode = "fail"`
```
restart {
      attempts = 0
      mode = "fail"
    }
```
I killed the container by running redis-cli shutdown inside the container, 
```
$ ./nomad alloc exec -i -t -task redis 24ca07b5 /bin/bash
root@35c0e7761d50:/data# redis-cli shutdown
```

The task was stopped and became `dead` status, then got restarted after about half minutes, I tried three times but still the same.
```
$ ./nomad job status example
ID            = example
Name          = example
Submit Date   = 2024-02-09T11:21:09+11:00
Type          = service
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
cache       0       0         1        2       0         0     0

Latest Deployment
ID          = 243d7f62
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
cache       1        1       1        0          2024-02-09T11:31:20+11:00

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created     Modified
0a25b90f  f97578ff  cache       0        run      running  1m44s ago   1m32s ago
24ca07b5  f97578ff  cache       0        stop     failed   10m36s ago  1m44s ago
ef7df892  f97578ff  cache       0        stop     failed   12m1s ago   10m36s ago
```

#### Expected Result
the task should NOT be restarted, it should be in `dead` status

#### Actual Result
The task was restarted

### Job file (if appropriate)
```
job "example" {
  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }
    restart {
      attempts = 0
      mode = "fail"
    }
    task "redis" {
      driver = "docker"
      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }
      identity {
        env  = true
        file = true
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by brucelok** [comment]
Tested on version `1.7.5`, issue persists
```
# ./nomad version
Nomad v1.7.5
BuildDate 2024-02-13T15:10:13Z
Revision 5f5d4646198d09b8f4f6cb90fb5d50b53fa328b8
```

**Comment by jrasell** [comment]
Hi @brucelok and thanks for raising this issue with the detail to be able to run this quickly locally.

```
$ nomad version
Nomad v1.7.4-dev
BuildDate 2024-01-18T16:52:14Z
Revision fce30f342c681343fdfe712551736a62efc609e3
```

When I run this test locally, I see that Nomad respects the "no restart" job specification parameters. I checked this by querying the status of the allocation that was initially placed which I subsequently stopped Redis on. Could you please check the task events and alloc status on your tests and let me know the outputs?

```
$ nomad alloc status e73473d8
...
Recent Events:
Time                  Type            Description
2024-02-16T08:02:06Z  Not Restarting  Policy allows no restarts
2024-02-16T08:02:06Z  Terminated      Exit Code: 0
2024-02-16T08:01:13Z  Started         Task started by client
2024-02-16T08:01:13Z  Task Setup      Building Task Directory
2024-02-16T08:01:13Z  Received        Task received by client
```

The follow up allocations are placed according to the [reschedule block](https://developer.hashicorp.com/nomad/docs/job-specification/reschedule) and are expected when an allocation has failed and rescheduling has not been disabled. If you wish to also disable this, you can add the snipped below to your job specification.

```
reschedule {
  attempts  = 0
  unlimited = false
}
```

I don't believe there is a bug in the allocation restart handling within Nomad and that what we have seen is rescheduling of failed allocations.

**Comment by brucelok** [comment]
I tried adding both `restart` and `reschedule` blocks to the job definition, and noticed the job didn't restart after the task was killed. it seems it is working
```
    restart {
      attempts = 0
      mode = "fail"
    }
    reschedule {
      attempts  = 0
      unlimited = false
    }
```
Just sharing what I observe: the restart block `attempt=0` only prevent an existing allocation from restarting, but a new allocation still kicks in when the existing one fails. To completely stop a job from restarting, it's required to add both `restart` and `reschedule` blocks as above. I'm thinking there might be some room for improvement in HashiCorp's [documentation](https://developer.hashicorp.com/nomad/docs/job-specification/restart#disabling-restart).
You might probably close this issue if you want, thank you very much!

**Comment by brucelok** [comment]
@jrasell That being said, It looks like I've observed another bug correlated to this.  When I updated a job definition particular on Restart policy, it didn’t take immediate effect. Do you want to file another issue or use this one
