### ISSUE TITLE
Allocations stuck in pending state when Nomad client is stopped despite drain_on_shutdown enabled

### ISSUE THREAD

**Issue by louievandyke** [hashicorp/nomad#20008]
### Nomad version
Output from `nomad version`
V1.6.3 also tested with v1.7.2

### Operating system and Environment details

Linux ip-172-31-23-76 5.15.0-1052-aws #57~20.04.1-Ubuntu SMP Mon Jan 15 17:04:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Issue

Allocations stuck in pending (lost) state when Nomad client is stopped despite drain_on_shutdown enabled

### Reproduction steps

Steps to reproduce the behavior.
Configure the nomad client with leave_on_terminate enabled as well as drain_on_shutdown

```
leave_on_interrupt   = true
leave_on_terminate   = true

client {
  drain_on_shutdown {
    deadline           = "1h"
    force              = false
    ignore_system_jobs = false
  }
}
```

* Run a job ( type=service ) with 'shutdown_delay=”6s”'.
* Stop nomad service in the client “systemctl stop nomad”
* After a few seconds in UI, the allocation will be marked as “lost”.
* In order to allocation to complete, start the nomad service “systemctl start nomad”

#### Expected Result

Nomad should stop the allocation and drain the client completely and not exit with an error code ( 'nomad.service: Main process exited, code=exited, status=1/FAILURE')

#### Actual Result

Allocations stuck in pending state

### Job file (if appropriate)

```
job "example" {

  group "cache" {

    network {
      port "db" {
        to = 6379
      }
    }
    
    task "redis" {
      driver = "docker"
      shutdown_delay = "6s"

      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }

      identity {
        env  = true
        file = true
      }

      resources {
        cpu    = 500
        memory = 256
      }
      service {
        name = "dev"
        port = "db"
      }
    }
  }
}
```

## client drain config

```
leave_on_interrupt   = true
leave_on_terminate   = true

client {
  drain_on_shutdown {
    deadline           = "4m"
    force              = true
    ignore_system_jobs = false
  }
}
```

###  logs 

[logs.log](https://github.com/hashicorp/nomad/files/14315059/logs.log)

[alloc_status.log](https://github.com/hashicorp/nomad/files/14315062/alloc_status.log)

**Comment by tgross** [comment]
@louievandyke given the exit code, this looks like it could be a problem with the `systemd` unit file. It's hard-killing the Nomad service after only 5sec, so the client doesn't get a chance to drain properly. They should be setting a kill timeout on the unit file that gives the client time to drain.

**Comment by suikast42** [comment]
I have the same situation.

I am on nomad 1.7.5 with ubuntu 22.04. I have set    ``` deadline 2m ```  and the systemdb job 
```
# drain_on_shutdown +  30s
TimeoutStopSec=2m30s

KillMode=process
KillSignal=SIGINT
LimitNOFILE=65536
LimitNPROC=infinity
Restart=on-failure
RestartSec=2

```


But if I stop the service with ``` systemctl  stop nomad ``` then the service is stopped in few seconds but nomad is still draining.

**Comment by jrasell** [comment]
Hi @louievandyke and thanks for raising this and as Tim mentioned it looks like in your original test we need to set `TimeoutStopSec` within the systemd service file. I have added this to my local environment and tested and see incorrect behaviour. 

I confirm the systemd service file includes the expect timeout stop parameter.
```
$ systemctl show nomad.service -p TimeoutStopUSec
TimeoutStopUSec=2min 30s
```

The Nomad client logs suggest a permission error when attempting to tell the Nomad servers about it's desire to shutdown and drain.
```
{"@caller":"github.com/hashicorp/nomad/helper/logging/logging.go:28","@level":"info","@message":"Caught signal: interrupt","@module":"agent","@timestamp":"2024-02-19T09:49:23.579225Z"}
{"@caller":"github.com/hashicorp/nomad/helper/logging/logging.go:28","@level":"info","@message":"Gracefully shutting down agent...","@module":"agent","@timestamp":"2024-02-19T09:49:23.579275Z"}
{"@caller":"github.com/hashicorp/nomad/client/rpc.go:119","@level":"error","@message":"error performing RPC to server","@module":"client.rpc","@timestamp":"2024-02-19T09:49:23.580543Z","error":"rpc error: rpc error: Permission denied","rpc":"Node.UpdateDrain","server":{"IP":"192.168.1.112","Port":4647,"Zone":""}}
{"@caller":"github.com/hashicorp/nomad/client/rpc.go:123","@level":"error","@message":"error performing RPC to server which is not safe to automatically retry","@module":"client.rpc","@timestamp":"2024-02-19T09:49:23.580630Z","error":"rpc error: rpc error: Permission denied","rpc":"Node.UpdateDrain","server":{"IP":"192.168.1.112","Port":4647,"Zone":""}}
{"@caller":"github.com/hashicorp/nomad/command/agent/agent.go:1232","@level":"error","@message":"client leave failed","@module":"agent","@timestamp":"2024-02-19T09:49:23.580653Z","error":"rpc error: rpc error: Permission denied"}
{"@caller":"github.com/hashicorp/nomad/command/agent/agent.go:1252","@level":"info","@message":"requesting shutdown","@module":"agent","@timestamp":"2024-02-19T09:49:23.580663Z"}
{"@caller":"github.com/hashicorp/nomad/client/client.go:873","@level":"info","@message":"shutting down","@module":"client","@timestamp":"2024-02-19T09:49:23.580694Z"}
{"@caller":"github.com/hashicorp/nomad/drivers/docker/stats.go:137","@level":"debug","@message":"error collecting stats from container","@module":"client.driver_mgr.docker","@timestamp":"2024-02-19T09:49:23.581177Z","container_id":"a134d09da0f18505ec1a95c90fd49a08ec406b056bf1716ff5cc3be37884bbb1","driver":"docker","error":"context canceled"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:95","@level":"info","@message":"shutting down plugin manager","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.582973Z","plugin-type":"device"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:97","@level":"info","@message":"plugin manager finished","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.583001Z","plugin-type":"device"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:95","@level":"info","@message":"shutting down plugin manager","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.583009Z","plugin-type":"driver"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:97","@level":"info","@message":"plugin manager finished","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.591571Z","plugin-type":"driver"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:95","@level":"info","@message":"shutting down plugin manager","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.591593Z","plugin-type":"csi"}
{"@caller":"github.com/hashicorp/nomad/client/pluginmanager/group.go:97","@level":"info","@message":"plugin manager finished","@module":"client.plugin","@timestamp":"2024-02-19T09:49:23.591607Z","plugin-type":"csi"}
{"@caller":"github.com/hashicorp/nomad/client/servers/manager.go:186","@level":"debug","@message":"shutting down","@module":"client.server_mgr","@timestamp":"2024-02-19T09:49:23.591676Z"}
{"@caller":"github.com/hashicorp/nomad/command/agent/agent.go:1272","@level":"info","@message":"shutdown complete","@module":"agent","@timestamp":"2024-02-19T09:49:23.603661Z"}
{"@caller":"github.com/hashicorp/nomad/command/agent/http.go:350","@level":"debug","@message":"shutting down http server","@module":"http","@timestamp":"2024-02-19T09:49:23.603689Z"}
```

I added some debug information to a build to see if I could identify the problem and while I wasn't able to pinpoint it, it does seem like the request is entering [this switch case](https://github.com/hashicorp/nomad/blob/7f87ede1e27fe6bb4131518bd6be66ec5f80bdf1/nomad/auth/auth.go#L139) and reaching [this return statement](https://github.com/hashicorp/nomad/blob/7f87ede1e27fe6bb4131518bd6be66ec5f80bdf1/nomad/auth/auth.go#L167). This indicates the [`NodeBySecretID` lookup](https://github.com/hashicorp/nomad/blob/7f87ede1e27fe6bb4131518bd6be66ec5f80bdf1/nomad/auth/auth.go#L149) is not finding the node.

@louievandyke could you confirm you still see the behaviour when you set the systemd `TimeoutStopSec` unit file parameter?

**Comment by louievandyke** [comment]
Hey all!    If you add `TimeoutStopSec=` you need to also define an `ExecStop=`, otherwise a s SIGTERM is sent immediately.

> TimeoutStopSec=
> This option serves two purposes. First, it configures the time to wait for each ExecStop= command. If any of them times out, subsequent ExecStop= commands are skipped and the service will be terminated by SIGTERM. If no ExecStop= commands are specified, the service gets the SIGTERM immediately. This default behavior can be changed by the TimeoutStopFailureMode= option. Second, it configures the time to wait for the service itself to stop. If it doesn't terminate in the specified time, it will be forcibly terminated by SIGKILL (see KillMode= in [systemd.kill(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html#)). Takes a unit-less value in seconds, or a time span value such as "5min 20s". Pass "infinity" to disable the timeout logic. Defaults to DefaultTimeoutStopSec= from the manager configuration file (see [systemd-system.conf(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd-system.conf.html#)).

This issue can be closed!  Sorry for the misunderstanding.

**Comment by suikast42** [comment]
> This issue can be closed! Sorry for the misunderstanding.


Ok I am little bit confusing now. 

The solution is to make an entry in sytemd like 
```shell
ExecStop =  nomad node drain -enable -self
```

right? 


Do I need  the   [drain_on_shutdown](https://developer.hashicorp.com/nomad/docs/configuration/client#drain_on_shutdown)  stanza afterwards?

**Comment by louievandyke** [comment]
hi @suikast42 here's an example of my nomad.service file.

The problem was that TimeoutStopSec= will send a SIGTERM immediately if ExecStop is not included in the service file.

```
vagrant@ubuntu-focal:~$ cat /etc/systemd/system/nomad.service
[Unit]
Description="HashiCorp Nomad"
Documentation=https://www.nomadproject.io/
After=consul.service docker.service network-online.target

[Service]
Type=simple
ExecStart=/opt/nomad/bin/nomad agent -config /opt/nomad/config.hcl -data-dir /opt/nomad/data
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -9 $MAINPID
Environment="PATH=/opt/consul/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=2
StartLimitBurst=3
TimeoutSec=300s
LimitNOFILE=infinity
LimitNPROC=infinity
TasksMax=infinity
OOMScoreAdjust=-1000

[Install]
WantedBy=multi-user.target
```

**Comment by suikast42** [comment]
> hi @suikast42 here's an example of my nomad.service file.
> 
> The problem was that TimeoutStopSec= will send a SIGTERM immediately if ExecStop is not included in the service file.
> 
> ```
> vagrant@ubuntu-focal:~$ cat /etc/systemd/system/nomad.service
> [Unit]
> Description="HashiCorp Nomad"
> Documentation=https://www.nomadproject.io/
> After=consul.service docker.service network-online.target
> 
> [Service]
> Type=simple
> ExecStart=/opt/nomad/bin/nomad agent -config /opt/nomad/config.hcl -data-dir /opt/nomad/data
> ExecReload=/bin/kill -HUP $MAINPID
> ExecStop=/bin/kill -9 $MAINPID
> Environment="PATH=/opt/consul/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
> KillMode=process
> KillSignal=SIGINT
> Restart=on-failure
> RestartSec=2
> StartLimitBurst=3
> TimeoutSec=300s
> LimitNOFILE=infinity
> LimitNPROC=infinity
> TasksMax=infinity
> OOMScoreAdjust=-1000
> 
> [Install]
> WantedBy=multi-user.target
> ```

Hmmh If I do so, then nomad will close immediately
