### ISSUE TITLE
Missing commit on stable-website branch

### ISSUE THREAD

**Issue by sevensolutions** [hashicorp/nomad#20030]
### Issue

this is not a bug about nomad but i'am missing a commit on the stable-website branch.
I've submitted PR #19411 which has been backported to the stable-website branch by #19693.

The changes were there for a few weeks but now they're missing and the public documentation link is broken:
https://developer.hashicorp.com/nomad/plugins/drivers/community/nomad-iis

On the main branch, the commit is still available.
https://github.com/hashicorp/nomad/tree/main/website/content/plugins/drivers/community

Is this intended, or maybe a bug in the backporting pipeline?

#### Expected Result

The link should be working again, pointing to the nomad-iis documentation.

#### Actual Result

The link is broken.
The files are missing here:
https://github.com/hashicorp/nomad/tree/stable-website/website/content/plugins/drivers/community

**Comment by jrasell** [comment]
Hi @sevensolutions and thanks for raising this and sorry about what seems to be happening. We will take a look into this and figure out what has gone wrong, and resolve it.

**Comment by sevensolutions** [comment]
Thx, its working again. 👍
