### ISSUE TITLE
Log `docker run ...` commands in debug mode

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20038]
### Proposal
Simplify debugging. It will really help to see actual `docker run ...` commands in case if something goes wrong.

### Use-cases
https://discuss.hashicorp.com/t/how-to-see-underlying-docker-command-for-my-task/63013

### Attempted Solutions
I tried to enable debugging `enable_debug=true`, but it does not help. I saw the option which allows to not delete containers when it exits.

In my case I missed quotes: `POSTGRES_HOST_AUTH_METHOD=trust` and nomad did `trust` string to be a variable `${trust}`. I was really surprised. This behaviour, I suppose, it could lead to security issues. I did not investigate it though.

**Comment by tgross** [comment]
Hi @EugenKon! This is an interesting idea, but one thing that complicates it is that the `docker` driver doesn't do a `docker run` command at all. Instead it calls the [Docker Engine API](https://docs.docker.com/engine/api/) over the Docker daemon's unix domain socket. 

And as you've noted, the environment variables can be sensitive, so logging them would definitely leak secrets, and we avoid that even in debug-level logging.

**Comment by tgross** [comment]
Doing a little issue review and realizing that the specific content being asked for here is already logged at debug.

>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: using client connection initialized from environment: driver=docker
>    2024-04-11T15:31:28.721-0400 [TRACE] client.driver_mgr.docker: binding volumes: driver=docker task_name=http volumes=["/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/alloc:/alloc", "/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/http/local:/local", "/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/http/secrets:/secrets"]
>    2024-04-11T15:31:28.721-0400 [TRACE] client.driver_mgr.docker: no docker log driver provided, defaulting to plugin config: driver=docker task_name=http
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: configured resources: driver=docker task_name=http memory=104857600 memory_reservation=0 cpu_shares=100 cpu_quota=0 cpu_period=0
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: binding directories: driver=docker task_name=http binds="[]string{\"/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/alloc:/alloc\", \"/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/http/local:/local\", \"/run/nomad/dev/data/alloc/1485892f-0e8e-da6a-2723-58e3bda92bc4/http/secrets:/secrets\"}"
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: configuring network mode for task group: driver=docker task_name=http network_mode=container:81cdd1e51a3c8c715aa08b8460c2380e01360d747f3333502c692faecbdce898
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: setting container startup command: driver=docker task_name=http command="httpd -vv -f -p 8001 -h /local"
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: applied labels on the container: driver=docker task_name=http labels="map[com.hashicorp.nomad.alloc_id:1485892f-0e8e-da6a-2723-58e3bda92bc4 com.hashicorp.nomad.job_id:httpd com.hashicorp.nomad.job_name:httpd com.hashicorp.nomad.task_name:http]"
>    2024-04-11T15:31:28.721-0400 [DEBUG] client.driver_mgr.docker: setting container name: driver=docker task_name=http container_name=http-1485892f-0e8e-da6a-2723-58e3bda92bc4
>    2024-04-11T15:31:28.827-0400 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=bb5b32c379e19a9a84a4404e740920aa7f84a2d2dd89c67f753c3d7e0be5699d
>    2024-04-11T15:31:28.871-0400 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=bb5b32c379e19a9a84a4404e740920aa7f84a2d2dd89c67f753c3d7e0be5699d


Given my previous notes above about using the Docker API and not the CLI, I'm going to close this out as not something we want to do.
