### ISSUE TITLE
feature: add multiline template env support

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#20033]
### Proposal
My proposal is to add support for multiline environment variables taken from template arguments.

```
template {
   env = true
   data = <<EOF
VARIABLE="something
something something
not a quoting end \"
this is the end"
EOF
// VARIABLE=$'something\nsomething something\nnot a quoting end "this is the end'
}
```

### Use-cases
The use case it the proposal itself - user wants to have multiline environment variables.

The specific use case I stumbled upon is configuring osixia/docker-phpLDAPadmin project with a multiline PHPLDAPADMIN_LDAP_HOSTS like in here https://github.com/osixia/docker-phpLDAPadmin/issues/28#issuecomment-468641499 .

### Attempted Solutions
A simple solution is to use HCL2 and store the variable value in a file and use:

```
env {
   VARIABLE=file("./VARIABLE.env")
}
```

**Comment by tgross** [comment]
Hi @Kamilcuk! It looks like we rely on https://github.com/hashicorp/go-envparse, which has the following limitation:

> Newlines are always treated as delimiters, so newlines within values _must_ be escaped.

So you should be able to get this behavior by escaping newlines.

**Comment by Kamilcuk** [comment]
Hi, that's great. Thanks

**Comment by Kamilcuk** [comment]
Hi, that's great. Thank you.
