### ISSUE TITLE
[Docs / Clarification] Clarify the relation between prometheus scrape_interval and nomad collection_interval.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad#20055]
I have seen different signals from 3 different places regarding how collection_interval (nomad) and scrape_interval (prometheus) should be related.
* [Metricfire blog](https://www.metricfire.com/blog/monitoring-hashicorp-nomad-with-prometheus-and-grafana/) says prometheus scrape_interval should be greater than nomad collection_interval.
* [Hashicorp tutorial](https://developer.hashicorp.com/nomad/tutorials/manage-clusters/prometheus-metrics) shows an example which is exactly the opposite.
* [Zerodha deployment code](https://github.com/zerodha/nomad-cluster-setup) seem to set them both as equal.

I would be nice if the docs clarified this usage.

**Comment by tgross** [comment]
@blmhemu while obviously we're not responsible for what third parties post on their blogs, I'm pretty sure the Metricfire blog agrees with the tutorial:

> The number of seconds between when Prometheus scrapes the predefined metrics controls the granularity of the time-series database. This gap is defined in the Prometheus configuration file as the scrape_interval parameter, which by default is set to 60 seconds. If you use this parameter, you should set this value to the same as or less than the collection_interval parameter that you set earlier in the nomad.conf.hcl (Nomad config file).

Which makes sense -- there's no reason to scrape more frequently than metrics will actually be updated. Note that the `collection_interval` configures collection intervals regardless of the metrics sink used, so for "push" metrics like `statsd` there's no equivalent scrape interval. I can probably come up with some verbiage for the docs to provide guidance here though.

**Comment by blmhemu** [comment]
Thanks for the clear up. Honestly, I don't see a point configuring different intervals for collection and scraping.

**Comment by tgross** [comment]
It would let you collect fewer data points, which could reduce costs.
