### ISSUE TITLE
Version 0.5.0 rpc error: alloc lookup failed on command nomad logs or alloc-status

### ISSUE THREAD

**Issue by yikaus** [hashicorp/nomad#2006]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Only on v0.5.0
### Operating system and Environment details
Debian8
### Issue
When execute nomad logs or alloc-status command get 

```
nomad logs fabio
Error querying allocation: Unexpected response code: 500 (rpc error: alloc lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0069 'i')
```

However status command is all good 

### Reproduction steps
As above

### Nomad Server logs (if appropriate)
```
Nov 18 00:32:51 ip-172-31-0-25 nomad[787]: 2016/11/18 00:32:51.858783 [ERR] http: Request /v1/allocations?prefix=fabi, error: rpc error: alloc lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0069 'i'
```
### Nomad Client logs (if appropriate)
Error querying allocation: Unexpected response code: 500 (rpc error: alloc lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0069 'i')

### Job file (if appropriate)
NA

**Comment by dadgar** [comment]
Hey `nomad logs` takes an allocation ID. "fabio" is the jobs name. I would run `nomad status fabio` and then get the allocation ID from there and run logs!

Let me know if you have any other questions!

**Comment by yikaus** [comment]
Oops ,I was mixed up with docker command . 
Of course  you have to have a allocation to get the log , all good. 

Thanks 
Kevin
