### ISSUE TITLE
Raft Snapshot restore fails between v1.7.5 and v1.6.2

### ISSUE THREAD

**Issue by thisisjaid** [hashicorp/nomad#20072]
### Nomad version
1.6.2 / 1.7.5

Nomad v1.6.2
BuildDate 2023-09-13T16:47:25Z
Revision 73e372ad94033db2ceaf53468b270a31544c23fd

Nomad v1.7.5
BuildDate 2024-02-13T15:10:13Z
Revision 5f5d4646198d09b8f4f6cb90fb5d50b53fa328b8

### Operating system and Environment details
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1055-aws x86_64)

### Issue
Raft snapshots taken on v1.7.5 with `nomad operator snapshot save` cannot be restored on a clean v1.6.2 cluster with `nomad operator snapshot restore`  as they result in a restore error `Unrecognized snapshot type: [29]` and failing Nomad server daemon as per logs submitted below.

### Reproduction steps
Take a cluster Raft snapshot on v1.7.5 with `nomad operator snapshot save` 
Setup a clean v1.6.2 cluster
Attempt to restore Raft state from snapshot using `nomad operator snapshot save state.snap`  

#### Expected Result
Raft state snapshot is correctly restored

#### Actual Result
Nomad server logs error and broken cluster that fails to load snapshot correctly

### Nomad Server logs (if appropriate)

Mar 05 17:35:17 hashistack-1-stg nomad[39474]: 2024-03-05T17:35:17.409Z [INFO]  snapshot: creating new snapshot: path=/opt/nomad/server/raft/snapshots/5-1978275-1709660117409.tmp
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: {"@level":"info","@message":"copied to local snapshot","@module":"nomad.raft","@timestamp":"2024-03-05T17:35:17.442903Z","bytes":6871289}
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: {"@level":"info","@message":"snapshot restore progress","@module":"nomad.raft","@timestamp":"2024-03-05T17:35:17.517744Z","id":"5-1978275-1709660117409","last-index":1978275,"last-term":5,"percent-complete":"98.95%","read-bytes":6799104,"size-in-bytes":6871289}
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: panic: failed to restore snapshot: failed to restore snapshot 5-1978275-1709660117409: Unrecognized snapshot type: [29]
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: goroutine 12 [running]:
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: github.com/hashicorp/raft.(*Raft).restoreUserSnapshot(0xc0003b1080, 0xc00064c000, {0x362b420, 0xc001efe040})
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/raft.go:1112 +0xd75
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: github.com/hashicorp/raft.(*Raft).leaderLoop(0xc0003b1080)
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/raft.go:814 +0xbc8
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: github.com/hashicorp/raft.(*Raft).runLeader(0xc0003b1080)
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/raft.go:522 +0x432
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: github.com/hashicorp/raft.(*Raft).run(0xc0003b1080)
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/raft.go:150 +0x4a
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: github.com/hashicorp/raft.(*raftState).goFunc.func1()
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/state.go:149 +0x53
Mar 05 17:35:17 hashistack-1-stg nomad[39474]: created by github.com/hashicorp/raft.(*raftState).goFunc in goroutine 1
Mar 05 17:35:17 hashistack-1-stg nomad[39474]:         github.com/hashicorp/raft@v1.5.0/state.go:147 +0x79
Mar 05 17:35:17 hashistack-1-stg systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 05 17:35:17 hashistack-1-stg systemd[1]: nomad.service: Failed with result 'exit-code'.

**Comment by thisisjaid** [comment]
We've done a bit more testing with this and I suspect the issue extends up to v1.7.2 as we've tried downgrading in place a working cluster gradually from v1.7.5 and the cluster fails to start back up until we hit v1.7.3 so I suspect a change breaking backward compatibility in the Raft snapshots was introduced then.

Further logs from these tests (v1.7.5 to v1.7.0-1.7.2) below 

`Mar 05 18:30:32 hashistack-1-stg systemd[1]: Started Nomad.
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: ==> WARNING: mTLS is not configured - Nomad is not secure without mTLS!
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"Loaded configuration from /etc/nomad.d/nomad.hcl","@module":"agent","@timestamp":"2024-03-05T18:30:32.538726Z"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"Starting Nomad agent...","@module":"agent","@timestamp":"2024-03-05T18:30:32.538872Z"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"debug","@message":"issuer not set; OIDC Discovery endpoint for workload identities disabled","@module":"nomad","@timestamp":"2024-03-05T18:30:32.542515Z"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"setting up raft bolt store","@module":"nomad","@timestamp":"2024-03-05T18:30:32.547354Z","no_freelist_sync":false}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"starting restore from snapshot","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.550156Z","id":"4572-1977441-1709633508661","last-index":1977441,"last-term":4572,"size-in-bytes":7065440}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"debug","@message":"starting renewal loop","@module":"nomad.vault","@timestamp":"2024-03-05T18:30:32.572570Z","creation_ttl":2764800000000000}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"debug","@message":"successfully renewed server token","@module":"nomad.vault","@timestamp":"2024-03-05T18:30:32.576857Z"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"successfully renewed token","@module":"nomad.vault","@timestamp":"2024-03-05T18:30:32.576936Z","next_renewal":1382399999960693}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"snapshot restore progress","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.632927Z","id":"4572-1977441-1709633508661","last-index":1977441,"last-term":4572,"percent-complete":"99.17%","read-bytes":7006812,"size-in-bytes":7065440}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"error","@message":"failed to restore snapshot","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.633009Z","error":"Unrecognized snapshot type: [29]","id":"4572-1977441-1709633508661","last-index":1977441,"last-term":4572,"size-in-bytes":7065440}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"starting restore from snapshot","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.633052Z","id":"4562-1969235-1709534292806","last-index":1969235,"last-term":4562,"size-in-bytes":8556857}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"snapshot restore progress","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.748445Z","id":"4562-1969235-1709534292806","last-index":1969235,"last-term":4562,"percent-complete":"99.35%","read-bytes":8501363,"size-in-bytes":8556857}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"error","@message":"failed to restore snapshot","@module":"nomad.raft","@timestamp":"2024-03-05T18:30:32.748542Z","error":"Unrecognized snapshot type: [29]","id":"4562-1969235-1709534292806","last-index":1969235,"last-term":4562,"size-in-bytes":8556857}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"info","@message":"shutting down server","@module":"nomad","@timestamp":"2024-03-05T18:30:32.748613Z"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"error","@message":"failed to start Raft","@module":"nomad","@timestamp":"2024-03-05T18:30:32.748686Z","error":"failed to load any existing snapshots"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"error","@message":"error starting agent","@module":"agent","@timestamp":"2024-03-05T18:30:32.748731Z","error":"server setup failed: Failed to start Raft: failed to load any existing snapshots"}
Mar 05 18:30:32 hashistack-1-stg nomad[13430]: {"@level":"error","@message":"Error starting agent: server setup failed: Failed to start Raft: failed to load any existing snapshots","@module":"agent","@timestamp":"2024-03-05T18:30:32.748758Z"}
Mar 05 18:30:32 hashistack-1-stg systemd[1]: nomad.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 18:30:32 hashistack-1-stg systemd[1]: nomad.service: Failed with result 'exit-code'.
`

**Comment by tgross** [comment]
@thisisjaid just to save you some time here in more testing, what you're doing is unsupported. See the [Upgrade docs](https://developer.hashicorp.com/nomad/docs/upgrade):
> Nomad does not support downgrading at this time. Downgrading clients requires draining allocations and removing the data directory. Downgrading servers safely requires re-provisioning the cluster.

What's happening is that the Raft FSM is reading in a new entry type (a [`JobSubmissionSnapshot`](https://github.com/hashicorp/nomad/blob/7820df53ca2eb0839bb1a3de842a5c8071b9767a/nomad/fsm.go#L68), in this case) that was added in a later version. In order to ensure that the state is identical between Raft nodes, the FSM has to be able to handle all the log entries.
