### ISSUE TITLE
Improve error message about oversubscription

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20089]
### Proposal
```
* Memory oversubscription is not enabled; Task "services.webshot-task" memory_max value will be ignored. Update the Scheduler Configuration to allow oversubscription.
```

It is not clear what and how to change.

### Attempted Solutions
It would be nice if it show the exact name for a file to change and option name.

It is not clear from documentation https://developer.hashicorp.com/nomad/tutorials/advanced-scheduling/memory-oversubscription#enable-memory-oversubscription where to configure the value in subject

**Comment by EugenKon** [comment]
Found the desired option from https://developer.hashicorp.com/nomad/docs/job-specification/resources#memory-oversubscription -> https://developer.hashicorp.com/nomad/api-docs/operator/scheduler#update-scheduler-configuration -> https://developer.hashicorp.com/nomad/docs/configuration/server#server-parameters -> https://developer.hashicorp.com/nomad/docs/configuration/server#bootstrapping-with-a-custom-scheduler-config This was challenging )

It would be much better if error will be like next:
```
... Update `server.default_scheduler_config.memory_oversubscription_enabled` configuration for `nomad/server.hcl` to `true`
```

**Comment by tgross** [comment]
@EugenKon the message is what it is because the cluster administrator can update the scheduler configuration dynamically without changing the configuration file. Also, the server doesn't retain information like where the configuration file is anyways, once the configuration has been parsed.
