### ISSUE TITLE
unclear wildcard matching example in 'ACL policy concepts' tutorial

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20118]
On the page: https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-policies

![image](https://github.com/hashicorp/nomad/assets/139780495/f2af5da5-647f-40a4-b25f-7f8c16494992)

You speak about 'greatest number' but choose the rule where * matched less characters. This is confusing. Please clarify documentation.

**Comment by tgross** [comment]
@EugenKon we chose the rule with the smallest _difference_, which is the greatest _match_. I can see how that wording could be confusing though. We have the same wording in https://developer.hashicorp.com/nomad/docs/other-specifications/acl-policy#namespace-rules and should improve it there as well.
