### ISSUE TITLE
`acl policy info` help text's `usage` section does not describes how to use options

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20117]
### Nomad version
```
Nomad v1.7.5
BuildDate 2024-02-13T15:10:13Z
Revision 5f5d4646198d09b8f4f6cb90fb5d50b53fa328b8
```

### Issue
![image](https://github.com/hashicorp/nomad/assets/139780495/04baf277-02c2-4d65-a675-46ed09742131)

### Reproduction steps
![image](https://github.com/hashicorp/nomad/assets/139780495/99017257-ea52-4443-9fd2-8cf7b1c1e8b4)

Though `nomad acl policy <subcommand> -help` describes how to use `info` subcommand with options

**Comment by tgross** [comment]
Will be fixed by https://github.com/hashicorp/nomad/pull/20138
