### ISSUE TITLE
Ambigious documentation: how to configure nomad server and client agents

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20120]
The [page](https://developer.hashicorp.com/nomad/docs/configuration/consul) has next paragraphs:

![image](https://github.com/hashicorp/nomad/assets/139780495/cebed54a-c82d-44a5-92c8-4cbbd6fef75d)

![image](https://github.com/hashicorp/nomad/assets/139780495/b70615c9-2cf3-4e1b-b1b9-72eeb5d9d8ab)

But in the next section you mix them together:
https://developer.hashicorp.com/nomad/docs/configuration/consul#default

![image](https://github.com/hashicorp/nomad/assets/139780495/2fc39250-b641-4621-bedb-6765b9326c62)

How? Why you mixed them together when you described that each one should be used for one or other purpose?

**Comment by apollo13** [comment]
You are misinterpreting the documentation here. Those two settings are not exclusive. A nomad agent can be a client and a server at the same time. Hence it is valid to set both service names at the same time.

**Comment by EugenKon** [comment]
I propose then the documentation spells is as:

> These parameters would be read by Nomad agent with `server.enabled=true` only.

Or for second picture
> These parameters would be read by Nomad agent with `server.enabled=false` only.


Instead of:
> These parameters should only be defined in the configuration file of Nomad agents with [server.enabled](https://developer.hashicorp.com/nomad/docs/configuration/server#enabled) set to true.

**Comment by tgross** [comment]
@EugenKon the documentation is correct and the settings are not exclusive. Your proposed sentence isn't actually equivalent, because `server.enabled` and `client.enabled` are actually both `false` by default (except in dev mode).
