### ISSUE TITLE
Log error messages when Nomad can not connect to Consul

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20124]
I changed my configuration to enable ACL for consul and nomad **servers**.
I can see these log messages:
```
Mar 12 17:03:26 ip-172-31-21-248 nomad[43017]:     2024-03-12T17:03:26.795Z [DEBUG] consul.sync: sync complete: registered_services=3 deregistered_services=0 registered_checks=3 deregistered_checks=0
Mar 12 17:03:26 ip-172-31-21-248 nomad[43017]: consul.sync: sync complete: registered_services=3 deregistered_services=0 registered_checks=3 deregistered_checks=0
```

But if I by intention change the `consul.token` to the wrong one, I do not see any error messages in the logs regarding this situation.

Log error messages if nomad can not connect to consul and provide documentation with instructions how to debug ACL bootstrapping.

**Comment by EugenKon** [comment]
In Consul log I can find next errors:
```
Mar 12 18:07:24 ip-172-31-9-43 consul[8386]: 2024-03-12T18:07:24.997Z [ERROR] agent.http: Request error: method=GET url=/v1/agent/self from=127.0.0.1:56782 error="ACL not found"
Mar 12 18:07:24 ip-172-31-9-43 consul[8386]: 2024-03-12T18:07:24.997Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/self from=127.0.0.1:56782 latency="106.715µs"
Mar 12 18:07:25 ip-172-31-9-43 consul[8386]: 2024-03-12T18:07:25.999Z [ERROR] agent.http: Request error: method=GET url=/v1/agent/self from=127.0.0.1:56782 error="ACL not found"
Mar 12 18:07:25 ip-172-31-9-43 consul[8386]: 2024-03-12T18:07:25.999Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/self from=127.0.0.1:56782 latency="107.5µs"
```
* From here it is not clear that requests are done from nomad. 
* It is not clear which service was queried. I expect here to see `to=127.0.0.1:8500`
* It is not clear which ACL was not found "17867a09-32a1-110f-a631-9062a384969f"
* No information that the request from nomad with a wrong **token** failed.

Ok. You can not identify which client did request, but from nomad side in debug mode you can generate `requiest-id` and log it, eg. "Request ID XXX to Consul 127.0.0.1:8500 using token YYY Failed" and then on Consule side "Incoming requests-id XXX from 127.0.0.1:34234 failed because token YYY/ACL was not found". This will really help.

**Comment by EugenKon** [comment]
It seems no error messages are on Nomad servers. Because I can see error on the instance with a Nomad Client:
```
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]:   error=
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]:   | 1 error occurred:
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]:   | \t* unable to query service "nomad" from Consul datacenter "dc1": Unexpected response code: 403 (rpc error making call: ACL not found)
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]:   |
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]:
Mar 12 19:23:21 ip-172-31-4-242 nomad[316009]: client: error discovering nomad servers:
                                                 error=
                                                 | 1 error occurred:
                                                 | \t* unable to query service "nomad" from Consul datacenter "dc1": Unexpected response code: 403 (rpc error making call: ACL not found)
                                                 |
```

**Comment by tgross** [comment]
@EugenKon Nomad servers don't connect to Consul unless they're using the legacy workflow for services or they've been configured to use Consul for bootstrapping the cluster. So it might just be that the servers aren't connecting to Consul yet. If you can share your server config we might be able to verify that.
