### ISSUE TITLE
allow `tls13` for `tls_min_version`

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20131]
### Issue

https://developer.hashicorp.com/nomad/docs/configuration/tls

![image](https://github.com/hashicorp/nomad/assets/139780495/6d89cd94-c801-459b-8d6c-2d43dd5e8313)

I see that consul already supports TLS_v1.3: https://developer.hashicorp.com/consul/docs/agent/config/config-files#tlsv1_3
I suppose that Nomad also already supports it, but this was not documented yet

#### Expected Result

Document, that `tls13` already supported.

**Comment by tgross** [comment]
That's not a documentation typo. Nomad's tlsutil package only currently accepts a `tls_min_version` as documented. That seems like an oversight though, so I'm going to rename this issue to cover updating the behavior instead.
