### ISSUE TITLE
[question] Nomad system scheduler des not start job when new client attaches

### ISSUE THREAD

**Issue by jrusiecki** [hashicorp/nomad#2018]
setup is 2 nodes, each: Ubuntu 16.04 + Consul 0.5.2 + Nomad 0.5.0

I have job.nomad starting on every node an nginx web container 
(on job level: type="system", 
 on group level: count=1, constraint on node.class equal "web"
 on task level:driver="docker" ...
)
I tested the following 2 scenarios (each step verified in consul ui to make sure next step is executed when info is propogated onto nomad server node):
_Scenario 1:_
Step 1) start 2 client nodes (1st is on server)
Step 2) docker run - it starts on all nodes available (2 available)
Step 3) Stop all
**Result: PASS :)**
_Scenario 2:_
Step 1) start 1 client node (on server)
Step 2) docker run - it starts on all nodes available (1 available)
Step 3) start 2nd client
Step 4) I expect Nomad server to start my nginx on new node but it does not - **Result FAIL**
Step 5) I re-run : nomad run exactly same job spec - **Result: it runs 2nd node ...**

Maybe it is my job spec or there is a bug?
Maybe u could point me to sample of proper server/client setup or just switch that affects this behavior of **system scheduler** (there is no much in the documentation on it)...

**Comment by jippi** [comment]
hi, can you please paste your job file in full and wrapped in "`` so its formatted nicely? or just gist it :)

**Comment by jrusiecki** [comment]
job: <script src="https://gist.github.com/jrusiecki/7050ab0fde5a9a2f7f215cb887f74c63.js>

svr +client1: <script src="https://gist.github.com/jrusiecki/3f3df502017214a4181b74c10f719138.js"></script>
client 2: <script src="https://gist.github.com/jrusiecki/3d95bd91f038271fd0e9fb00d15cf460.js"></script>

**Comment by jippi** [comment]
uhm, those links and content doesn't look correct to me : )

**Comment by jrusiecki** [comment]
sorry, I can really speak gist, so I've just pasted it now. sorry for a mess ;)

**Comment by dadgar** [comment]
Would you mind running "Scenario 2" and then running `nomad status -evals qbajob` and there should be an evaluation listed with a placement failure. Grab that ID and run `nomad eval-status <ID>` and post the results of all the commands.

**Comment by fireya** [comment]
Hello! I have the same question: I have system job and 8 client nodes. 2 nodes suddenly goes offline and were started after 12 hours. My system job was not restarted on those 2 nodes, after they were started:
`[root@snode4 ~]# nomad status -evals csd
ID          = csd
Name        = csd
Type        = system
Priority    = 50
Datacenters = us-west-1,us-east-1,dc1
Status      = running
Periodic    = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
csd         2       0         6        0       0         2

Evaluations
ID        Priority  Triggered By  Status    Placement Failures
005b3691  50        job-register  complete  false

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status   Created At
11afac03  005b3691  aa02cddc  csd         run      running  12/06/16 17:00:14 MSK
4ce30b72  005b3691  3b1d797a  csd         run      running  12/06/16 17:00:14 MSK
84cca3bc  005b3691  f5114d13  csd         run      running  12/06/16 17:00:14 MSK
8df23692  005b3691  eeede5db  csd         run      running  12/06/16 17:00:14 MSK
90587578  005b3691  7950dd34  csd         run      running  12/06/16 17:00:14 MSK
92485b94  005b3691  3f7809f6  csd         run      running  12/06/16 17:00:14 MSK
[root@snode4 ~]# nomad eval-status 005b3691
ID                 = 005b3691
Status             = complete
Status Description = complete
Type               = system
TriggeredBy        = job-register
Job ID             = csd
Priority           = 50
Placement Failures = false
`

**Comment by jrusiecki** [comment]
Sorry for the delay - I did not get notifications and once I found thereply the test env was unavailable to me. Now I've done several retests and can not re-create failing in scenario 2 - adding nomad clients starts my task just fine. If I find it again, I'll reopen this ticket with all info u requested. Thx a lot

**Comment by dadgar** [comment]
@jrusiecki Thanks! Going to close and as you mentioned we will re-open if it comes up again!
