### ISSUE TITLE
Executor plugin temp file not removed

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#2019]
The plugin file created by the executor is not cleaned up by Nomad. I believe this is a regression.

**Comment by dadgar** [comment]
Confirmed that the plugin file is removed.

**Comment by santisaez** [comment]
We're experiencing the same issue with Nomad v0.5.6, some details:

```
$ nomad version
Nomad v0.5.6

$ ls -l /tmp/plugin* | wc -l
76

$ lsof -n 2> /dev/null | grep '/tmp/plugin' | awk '{ print $10}'| sort | uniq | wc -l
15
```

15 socket files are in use by "nomad_0.5.6 executor" processes, the rest are orphan files.
