### ISSUE TITLE
Web UI exec command doesn't consider namespaces

### ISSUE THREAD

**Issue by dpogorzelski** [hashicorp/nomad#20213]
### Nomad version
1.7.5

### Operating system and Environment details
Debian 12

### Issue
If you navigate, via web UI, to a task in running in a namespace other than `default` and click `Exec`
the proposed command won't work as task's namespace is not considered.
Example:
`nomad alloc exec -i -t -task foobar 11867402 /bin/bash`
instead of
`nomad alloc exec -namespace=dev -i -t -task foobar 11867402 /bin/bash`

![Screenshot 2024-03-25 at 12 15 19](https://github.com/hashicorp/nomad/assets/72764/35c17a13-ed96-43ea-a330-f5931decb718)

**Comment by philrenaud** [comment]
Hi @dpogorzelski, thanks for raising this; seems like a good bug! I'll take a look at what might be causing it soon.
