### ISSUE TITLE
Enable default payload for parametrized job

### ISSUE THREAD

**Issue by yanbin-pan** [hashicorp/nomad#20228]
### Proposal

While the meta of the parametrised job is often useful to provide some easy key/value configuration oftentimes the job requires a JSON file for application configuration. The payload block does that, but there isn't a clear way to provide a default templated JSON block when running the parametrised job such that when dispathing new jobs from the parent, the UI can render this default JSON into the dispatch page UI. Each time this payload needs to be provided explicitly into the payload window.

This would be similar to what setting `meta` key values and default do for the `meta_optional` and `meta_required`.
### Use-cases

This is useful when there is a bigger JSON configuration file that the job requires and needs to be exposed to the UI user when dispatching an instance of the job. This would be useful for Ops teams to provide a location to centralise configuration defaults for applications which do not require Vault or Consul.

```
meta = {
	"data_dir"="s3://bucket-data",
	"image_tag" = "1.0.0",
}

meta_payload = "local_dir/template_config.json"

parameterized {
	payload = "required"
	meta_required = [
        "data_dir",
	"image_tag"
    ]
}
```

**Comment by jrasell** [comment]
Hi @yanbin-pan and thanks for raising this issue. If the templated data passed to each child job is the same, I wonder if we could use any of the existing Nomad features to achieve your goal. Specifically, the [template block](https://developer.hashicorp.com/nomad/docs/job-specification/template) can be used to write or expose configuration options for use within task groups. This can be templated data which is populated from Consul, Vault, or Nomad, or even just flat files which contain certain parameters or substitutions.

If you have an example of what data the payload might included, I can come up with a better example of what this template block would look like. I'd also like to better understand this, so I can see whether a default payload makes more sense over the existing Nomad job specification functionality.

**Comment by yanbin-pan** [comment]
Hi @jrasell Thank you for following up! Yes the child job would have the same templated data, but it could be tweeked in the dispatch job page for each child instance. I have looked into the template block to populate variables from Vault or Consul, however, It would be preferable to keep it separate from either tools as I'm not storing secrets and would like the configuration to be closer to the application code, and be version controlled beside the hcl file, as it is closer to the development team.

My payload is a nested json with numerical, booleans and lists like in this example and could have 100s of parameters.  It would really improve the dev experience if these configs could be templated in the payload so that they are editable from the UI in the dispatch job. This would avoid the tedious process of copy pasting this into the payload window or baking into the Dockerfile.

If you have other ideas how this could be achieved with current blocks I am open to suggestions :)

Thanks!
```
{
    "parameter_a": {
        "values_thresholds_x": [
            -4.0,
            4.0,
            24.0,
            35.0
        ],
        "values_thresholds_y": [
            0.25,
            0.375,
            0.6,
            3.0
        ],
        "values_thresholds_z": [
            3,
            8
        ]
    },
    "parameter_b": {
        "values_thresholds_x": [
            3.0,
            20.0,
            22.0,
            30.0
        ],
        "values_thresholds_y": [
            0.1,
            0.32,
            0.47,
            1.5
        ],
        "values_thresholds_z": [
            4,
            9
        ]
    },
    "parameter_c": {
        "values_thresholds_x": [
            10.0,
            19.5,
            31.0,
            37.0
        ],
    },
   "boolean_a": "true"
}
```

**Comment by jrasell** [comment]
Hi @yanbin-pan and thanks for the additional detail. If I am understanding your use-case correctly, you could embed this payload using the [template block](https://developer.hashicorp.com/nomad/docs/job-specification/template). I tested this locally, and the results can be seen below.

Jobspec:
```
job "gh-20228" {
  type = "batch"

  parameterized {}

  group "gh-20228" {
    task "gh-20228" {
      driver = "docker"

      config {
        image   = "busybox:latest"
        command = "cat"
        args    = ["local/file.json"]
      }

      template {
        data = <<EOH
{
    "parameter_a": {
        "values_thresholds_x": [
            -4.0,
            4.0,
            24.0,
            35.0
        ],
        "values_thresholds_y": [
            0.25,
            0.375,
            0.6,
            3.0
        ],
        "values_thresholds_z": [
            3,
            8
        ]
    },
   "boolean_a": "true"
}
EOH

        destination = "local/file.json"
      }
    }
  }
}
```

The logs of the dispatched job instance:
```
$ nomad logs -f 23cc5f41
{
    "parameter_a": {
        "values_thresholds_x": [
            -4.0,
            4.0,
            24.0,
            35.0
        ],
        "values_thresholds_y": [
            0.25,
            0.375,
            0.6,
            3.0
        ],
        "values_thresholds_z": [
            3,
            8
        ]
    },
   "boolean_a": "true"
}
```

You could also store this JSON within [Nomad variables](https://developer.hashicorp.com/nomad/docs/concepts/variables) if you wanted to store this outside of the job specification, but in Nomad. I feel both these examples and options offer the flexibility needed and I will therefore close this issue out. If you have any further questions, please feel free to reach out.
