### ISSUE TITLE
Completed batch job goes pending again after node goes down due to screen lock

### ISSUE THREAD

**Issue by madhur-df** [hashicorp/nomad#20245]
I have opened a discussion about it in the forum as well: https://discuss.hashicorp.com/t/completed-batch-job-goes-pending-again-after-node-goes-down-due-to-screen-lock/64056

Which has more details including screenshots, etc.

**Comment by tgross** [comment]
Hi @madhur-df! I'm fairly certain that this is the same issue described in https://github.com/hashicorp/nomad/issues/19564, which @Juanadelacuesta is working on. I'm going to close this issue as a duplicate.

As for the screen lock, you _might_ be able to avoid having the client disconnect by running it under `launchd`.
