### ISSUE TITLE
AllocDirStats field missing from api definition of HostStats

### ISSUE THREAD

**Issue by tomqwpl** [hashicorp/nomad#20246]
### Nomad version
This is in git on main as of today.

### Issue
In api/nodes.go there is a definition of HostStats. I believe that this declared what a user of the nomadapi sees as the definition of that struct.
However, in client/hosttast.go there is what I believe is the server side version of this struct. This version has AllocDirStats field in. I can see that AllocDirStats is returned in REST API responses, but the nomadapi version of HostStats doesn't declare that field so it's not available to users of nomadapi.

**Comment by tgross** [comment]
Hi @tomqwpl! Yeah this looks like a bug in `api/nodes.go`. The HTTP server on the client node uses this version: [`client/hoststats/host.go#L25`](https://github.com/hashicorp/nomad/blob/main/client/hoststats/host.go#L25). Most of our structs get defined on the Nomad server under `nomad/structs`, and we have to keep them in sync as part of our development checklist for new fields. But client structs like that one don't have an equivalent checklist, so looks like we missed it.

Easy fix though. We'll get that done.

**Comment by tgross** [comment]
I've got a quick fix up here: https://github.com/hashicorp/nomad/pull/20261

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/20261, which will ship in the next release. Thanks @tomqwpl!

**Comment by tomqwpl** [comment]
@tgross Apologies I didn't get time to create the PR before you got there, since it was a trivial fix I had done locally (albeit I didn't have the test cases)
