### ISSUE TITLE
alloc-dir must be given as an absolute path: got [data_dir]/alloc

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20265]
### Nomad version
```
Nomad v1.7.5
BuildDate 2024-02-13T15:10:13Z
Revision 5f5d4646198d09b8f4f6cb90fb5d50b53fa328b8
```

### Operating system and Environment details
```
uname -a
Linux xxx #16~22.04.1-Ubuntu SMP Wed Mar 13 18:54:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
This configuration does not work:

```
data_dir  = "/opt/nomad/data"
...
client {
  enabled = true
  alloc_dir = "[data_dir]/alloc"
  ...
}
```

Though next configuration for server on different node does:
```
data_dir  = "/opt/nomad/data"
...
server {
  enabled = true
  data_dir = "[data_dir]/server"
  ...
}
```

#### Expected Result
`[data_dir]` inside `client` stanza should be expanded as it was done at `server` section.

#### Actual Result
`[data_dir]` is not expanded.

**Comment by EugenKon** [comment]
Well, it just created: `/[data_dir]` in the root of the file system :D

Though I can find `/opt/nomad/data/checkpoint-signature` file. I think, this is a different bug when `checkpoint-signature` file is created not based on `data_dir` configuration option.

![image](https://github.com/hashicorp/nomad/assets/139780495/cf7d4bea-c57e-4a4f-8510-1076147c3646)

**Comment by jrasell** [comment]
Hi @EugenKon and thanks for raising this issue. The documentation is slightly confusing as it details a string literal whereas it's attempting to show interpolation details. I'll raise a PR to fix-up the documentation shortly.
