### ISSUE TITLE
reserved cores not working without systemd

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#20275]
### Nomad version
1.7.6 enterprise

### Issue
When running Nomad on a non-systemd system with cgroupv2 (unified hierarchy) using the `cores` resource allocation doesn't result in cpuset updates across other docker containers on a node. In https://github.com/hashicorp/nomad/pull/12274 proper support for cgroupv2 was added by introducing a cpuset fixer routine to sync state between the nomad managed cgroup and the one created by docker. However, [the code that starts the fixer](https://github.com/hashicorp/nomad/blob/main/drivers/docker/handle.go#L265) only supports this if docker runs with the cgroup driver set to systemd, see: https://docs.docker.com/reference/cli/dockerd/#configure-cgroup-driver how docker determines defaults.
It would be better if Nomad queries for the used `cgroup driver` through the [docker API](https://pkg.go.dev/github.com/fsouza/go-dockerclient@v1.7.9#Client.Info) to determine which path to write the updated cpuset to. 

### Reproduction steps
Run Nomad on a Linux distro without systemd 

#### Expected Result
When using `cores` resource requests we should be getting reserved cpu cores as [documented here](https://docs.hashicorp.com/nomad/docs/concepts/cpu#allocating-cpu-resources):

_On Linux systems, Nomad supports reserving whole CPU cores specifically for a task. No task will be allowed to run on a CPU core reserved for another task._

#### Actual Result
Containers aren't getting reserved cores.

**Comment by jrasell** [comment]
Hi @ygersie and thanks for raising this along with the PR. I've made a note internally, so that we get around to reviewing the PR in a timely manner.
