### ISSUE TITLE
client: parsing of server IPv6 addresses is inconsistent with docs

### ISSUE THREAD

**Issue by jodersky** [hashicorp/nomad#20310]
### Nomad version

v1.7.6

### Operating system and Environment details

Debian 12

### Issue

When specifying an IPv6 address to connect to a Nomad server, it must be enclosed in brackets *and* include the port, or else the address parsing will not succeed, and the client will remain disconnected.

The [documentation](https://developer.hashicorp.com/nomad/docs/configuration/client#servers) specifically mentions that the port may be omitted, and also does not mention that the address must be given in URL form (i.e. wrapped in brackets for IPv6). This, further with by-default hidden log messages, makes this error quite hard to diagnose.

#### Using raw IPv6 address

```
client {
  enabled = true
  servers = ["2001:db8::1"]
}
log_level = "DEBUG"
```

Log:

>  [DEBUG] client: ignoring server due to resolution error: error="address 2001:db8::1: too many colons in address" server=2001:db8::1

#### Using IPv6 address as in a URL

```
client {
  enabled = true
  servers = ["[2001:db8::1]"]
}
log_level = "DEBUG"
```

Log:
>[DEBUG] client: ignoring server due to resolution error: error="address [[2001:db8::1]]:4647: missing port in address" server=[2001:db8::1]

### Workaround

Specify address as a URL and include port

```
client {
  enabled = true
  servers = ["[2001:db8::1]:4647"]
}
```

**Comment by tgross** [comment]
Hi @jodersky! This is both a bug and a docs issue. I've fixed both in https://github.com/hashicorp/nomad/pull/20324. Thanks!
