### ISSUE TITLE
[question]Not able to allocate resources even after meta constraint is satisfied 

### ISSUE THREAD

**Issue by aditya-cherla** [hashicorp/nomad#2034]
Hi ,

I have setup nomad cluster and have written a example job file which uses raw_exec driver. I am using custom meta as constraints and when I am trying to plan the job , the allocation fails. 

Job: "test-app"

Task Group: "deploy" (2 create)
  Task: "test-app"
Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "deploy" (failed to place 2 allocations):
    * Class "test_app" filtered 2 nodes
    * Constraint "${meta.my_custom_meta} = 4" filtered 2 nodes

Can you please explain why the allocation fails even after the constraint filtered 2 nodes.

Thanks.

**Comment by dadgar** [comment]
Hey meta should be prefixed: `${node.meta.cached_binaries}`. I just noticed the documentation makes the mistake in one of its examples. I will get that fixed!  I am going to close this but if it doesn't resolve your issue please feel free to add to this issue and we will re-open 👍
