### ISSUE TITLE
[question] Detailed Documentation about Task Status and Desired Status

### ISSUE THREAD

**Issue by Smuerdt** [hashicorp/nomad#2039]
Is there somewhere a detailed documentation of the "status" and "desired" status a task can have? And especially how do they affect the task-group and job status?

```
const (
	AllocDesiredStatusRun   = "run"   // Allocation should run
	AllocDesiredStatusStop  = "stop"  // Allocation should stop
	AllocDesiredStatusEvict = "evict" // Allocation should stop, and was evicted
)

const (
	AllocClientStatusPending  = "pending"
	AllocClientStatusRunning  = "running"
	AllocClientStatusComplete = "complete"
	AllocClientStatusFailed   = "failed"
	AllocClientStatusLost     = "lost"
)
```

When I search the codebase I find all possible States but in particular I don't understand the difference between `running` and `complete` or when is a task  `lost` and not `failed`? Is there a correlation between `lost` and `evict`?

Thanks in advance.

**Comment by dadgar** [comment]
Hey I agree we should document this better.

In the mean time to answer your question:

* Desired status is what the schedulers want the allocation to do
* Client status is the emergent state of the allocation
* Running means the tasks are currently running
* Complete means the tasks finished successfully
* Failed means the tasks finished but not successfully (non-zero exit code)
* Lost means the node that was running the tasks has failed or has been partitioned. As such the servers do not know its state.
