### ISSUE TITLE
Unable to filter jobs by Node Pool type in web UI

### ISSUE THREAD

**Issue by jerrykan** [hashicorp/nomad#20407]
### Nomad version
```
Nomad v1.7.6
BuildDate 2024-03-12T07:27:36Z
Revision 594fedbfbc4f0e532b65e8a69b28ff9403eb822e
```

### Operating system and Environment details
Debian 12/bookworm

### Issue
There doesn't seem to be a way to filter jobs based on their Node Pool in the Nomad UI. There is a drop-down list for "Node Pool" but it just displays "No options"

Using the `nomad` command line there are a number of node pools available.
```
# nomad node pool list
Name         Description
all          Node pool with all nodes in the cluster.
default      Default node pool.
legacy-apps  Nodes for legacy apps
worker-apps  <none>
```

### Reproduction steps
Open up the Nomad web UI and click on Jobs to display all jobs. Then click on the "Node Pool" drop-down list.

#### Expected Result
The "Node Pool" drop-down list displays all available node pools

#### Actual Result
No node pools are listed

![nomad_ui_node_pool](https://github.com/hashicorp/nomad/assets/377632/16251aec-a4a9-4f6f-861c-147c555a0bd3)

**Comment by philrenaud** [comment]
Hi @jerrykan , thanks for raising this. We're actually in the middle of a sizeable rework of how we handle the jobs index page, including filtering. Serendipitous timing as today is the Node Pools/Namespaces filtering day. You can follow along with work at https://github.com/hashicorp/nomad/pull/20459/commits or look for a big update to the page in an upcoming release.

**Comment by philrenaud** [comment]
Confirmed that Node Pools are a first-class filter option on the updated jobs page per https://github.com/hashicorp/nomad/pull/20459
