### ISSUE TITLE
[Question] - Update stanza

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2041]
Hi guys,

I wonder, why did you design the ```update``` stanza to be set on job but not on task group ?

The count being on the task group stanza, we would need to be able to set ```max_parallel``` differently depending of the group.

Is it a choice in the design of Nomad ? Am I doing something wrong ?

**Comment by dadgar** [comment]
Hey the reason it is like that is the scheduler operates on the granularity of a job. It makes scheduling decisions for the whole job at once. Would you mind outlining your use case more?

**Comment by samber** [comment]
I am running in the same job, 2 docker tasks, to prepare a load test of my app:
- ~10 containers of Selenium in a task group
- ~1000 containers of Behat (requesting Selenium) in a taskgroup

If I set the ```max_parallel``` parameter to 3, the selenium rolling upgrade will progress normally, but it would be very long to update the whole cluster of Behat containers.

In this case, because it is a load test, I can stop my bench and run it again. But in a less specific way, I think the fields ```count``` and the ```max_parallel``` should be tied each other, inside a task group.

WDYT ?
