### ISSUE TITLE
Upgrade go-getter

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2042]
The version used in 0.5 predates netrc support without which credentials needed to download artifacts must be included in jobspecs.

**Comment by adrianlop** [comment]
hi @schmichael can you review https://github.com/hashicorp/go-getter/pull/34 before upgrading if possible please?
it adds HTTP basic auth

thanks!

**Comment by lnguyen** [comment]
Can we upgrade this to get git support?
