### ISSUE TITLE
Dispatch documentation and API documentation differs about the maximum size of payload

### ISSUE THREAD

**Issue by agarfer1** [hashicorp/nomad#20432]
This page (https://nomadproject.io/docs/commands/job/dispatch/) says:

> The payload has a size limit of 16384 bytes (16KiB).

Whereas the API documentation for Dispatch (https://nomadproject.io/api-docs/jobs/#payload) says:

> [Payload](https://developer.hashicorp.com/nomad/api-docs/jobs#payload) (string: "") - Specifies a base64 encoded string containing the payload. This is limited to 65536 bytes (64KiB).

Related: #7614

**Comment by tgross** [comment]
Hi @agarfer1! Good catch, it's 16KiB. I'll fix the docs.
