### ISSUE TITLE
Basic Auth for "artifact" lacks documentation

### ISSUE THREAD

**Issue by marcusdahlstein** [hashicorp/nomad#2043]
### Nomad version
0.5.0

We have our artifacts located in Artifactory protected with Basic Auth.
Currently there is no documentation how to pass the username and password in the artifact stanza.

If possible it would be great with documentation around it.

relates to 
https://github.com/hashicorp/nomad/issues/2042

**Comment by tgross** [comment]
Fixed (finally!) in https://github.com/hashicorp/nomad/pull/9392 and will ship with the next website push.
