### ISSUE TITLE
Job versions with empty diffs being created when updating a job before it becomes stable in some circumstances

### ISSUE THREAD

**Issue by myszon** [hashicorp/nomad#20497]
### Nomad version
v1.6.3, tip also seems affected

### Operating system and Environment details
Linux

### Issue
When submitting a new version of a job using a wrapper library, I observed that if the job gets resubmitted with no changes before it gets stabilized, a new version is created with an empty diff. This terminates the old allocations created for that version and creates new ones.

If the job is resubmitted repeatedly and the time between resubmissions is shorter than the time to stabilise the job, this will result in an endless loop of creating new versions.

### Issue details
It seems that this only happens if certain fields containing arrays like `Constraints`, `Affinities` or `Spreads` contain an empty list in `Job`, `TaskGroup` or `Task`.

#### Background - Job submission process
Most definitions of functions mentioned here are in `nomad/structs/structs.go`.

When a job is submitted, it seems to go through the following process (these are just the relevant bits for this bug):
1. `Job.Canonicalize` is run on the submitted job
2. In `Job.SpecChanged`, the submitted job is compared against the previous version
  a) The submitted job is copied. The copy function uses `CopySlice...` functions to copy arrays like `Constraints`, `Affinities` or `Spreads`.
  b) Certain ephemeral fields are copied from the previous version of the job into the newly created copy
  c) The newly created copy is compared against the previous version of the job using `reflect.DeepEqual`
3. If there is a difference a new version is created, with the field `Stable` set to false
4. Eventually, the job will be marked as stable in `nomad/state/state_store.go` in `StateStore.updateJobStabilityImpl` which copies the job as part of the process.

#### Bug
It seems that in `Job.Canonicalize` nothing is done to fields like `Constraints`, `Affinities` or `Spreads`. This means that the initial submission of a new version the job will have the same contents of those fields as they are submitted.

However, when the comparison is done to check if the spec changed, the previous version is compared against a copy of the new submitted version. While copying, the `CopySlice...` functions seem to canonicalize empty arrays as nil. This leads to comparing an empty array and nil which are not equal according to `reflect.DeepEqual` if the submitted job had empty arrays in those fields.

This starts working again after the job has been marked as stable because the job is copied as part of that process and future comparisons check two jobs which both have been copied at some point.

### Proposed fix

`Job.SpecChanged` should return true for jobs that are conceptually the same.

There are many possible ways to achieve that goal, I prepared a PR which canonicalizes submitted jobs so that the fields mentioned above are converted to null if they contain just an empty list, similar to how the `Meta` field is canonicalized and the same way these fields were implicitly canonicalized when copying.

### Reproduction steps
1. Submit a job containing an empty array in `Constraints`, `Affinities` or `Spreads` (example below).
6. Check the version of that job (will be 0)
7. Submit a modified version of the job (for example by changing the task name)
8. Check the version of that job (will be 1)
9. Resubmit the last version of the job before it is marked as stable

#### Expected Result
The version of the job is still 1

#### Actual Result
The version of the job is 2 and the diff between job version 1 and 2 in the nomad web ui appears to be empty.

### Job as JSON
```
{
  "ID": "test",
  "Namespace": "default",
  "Datacenters": [
    "test-dc"
  ],
  "Region": "test-region",
  "Constraints": [],
  "Type": "batch",
  "TaskGroups": [
    {
      "Name": "task-group",
      "Count": 1,
      "Tasks": [
        {
          "Name": "test",
          "Driver": "raw_exec",
          "Env": {},
          "Resources": {
            "CPU": 100,
            "MemoryMB": 100,
            "Devices": []
          },
          "Constraints": [],
          "Config": {
            "command": "sleep",
            "args": [
              "inf"
            ]
          },
          "RestartPolicy": {
            "Attempts": 0,
            "Delay": 5000000000,
            "Interval": 5000000000,
            "Mode": "fail"
          },
          "Leader": true,
          "Lifecycle": null,
          "Affinities": []
        }
      ],
      "Constraints": [],
      "ReschedulePolicy": {
        "Attempts": 0,
        "Interval": 86400000000000,
        "Unlimited": false,
        "Delay": 5000000000,
        "DelayFunction": "constant",
        "MaxDelay": null
      },
      "Affinities": []
    }
  ],
  "Meta": {},
  "Affinities": []
}
```

**Comment by jrasell** [comment]
Hi @marvinchin, the Nomad team operates an internal rotation for triaging community issues, so I kindly ask people are not directly pinged. The entire team gets issue updates when comments are posted, which is sufficient.

Thanks @myszon for raising this issue and apologies for the delay in taking a look at this. The Nomad engineering team has been busy focussing on the 1.8 release. If I am understanding correctly, this affects the API only and not the Nomad CLI?

> job using a wrapper library

Could you provide a little more context on what this process looks like? I want to ensure this does not have an impact on how the bug is manifesting.

> nomad/structs/structs.go

This package is not intended to be imported directly via tools, and the [api](https://github.com/hashicorp/nomad/tree/main/api) package should be used instead. I wonder if this also could be contributing to adverse behaviour.

**Comment by myszon** [comment]
I have not tested if I can reproduce this via the Nomad CLI, but I can definitely do so via the HTTP API.

This job is submitted from a library (written in OCaml) which submits it via the HTTP API.

We are not importing any Nomad (or go code for that matter).

The process I describe is what seems to be happening within stock unmodified nomad, our code just sends a request via the HTTP API. I'm obviously not an expert, I might have misunderstood how it works though.

**Comment by jrasell** [comment]
Hi @myszon and thanks for the clarity. I'll move this onto our backlog for further investigation.
