### ISSUE TITLE
Nomad UI should show and make jobs sortable by job create time

### ISSUE THREAD

**Issue by gscho** [hashicorp/nomad#20520]
### Proposal

It would be great if the nomad UI showed the job's creation time and also allowed us to sort on time.

### Use-cases

We run thousands of batch jobs per day on nomad and it would be great if we had an easy way to see the time each job was created without having to click into a job.

### Attempted Solutions

N/A

**Comment by philrenaud** [comment]
Hey @gscho , nice timing. We're close to completion on a [pretty major rework](https://github.com/hashicorp/nomad/pull/20452) of the jobs index page in the UI that:
- Paginates the jobs properly
- Sorts by a job's ModifyIndex, descending, such that they're always ordered by most recent update.

This is a little different than showing Create Time, but that's also not something that we store at job level. (We use Raft Index for consistency instead. There are time events on things like Task events, but that's not a property we'd want to make jobs sortable by for consistency reasons)

I hope the upcoming rework to this page satisfies what you're looking for.

**Comment by philrenaud** [comment]
This should be resolved as part of https://github.com/hashicorp/nomad/pull/20452
