### ISSUE TITLE
Reserved CPU is counted twice

### ISSUE THREAD

**Issue by ostkrok** [hashicorp/nomad#20521]
### Nomad version
Nomad v1.7.5

### Operating system and Environment details
Ubuntu 20.04.4

### Issue

When using the `reserved` block in the nomad client config to set CPU reservation, the reservation is counted twice. We've observed this by watching the metric `nomad_client_unallocated_cpu`, and by jobs no longer being schedulable since upgrading to Nomad 1.7.

We think the issue was introduced in the this PR: https://github.com/hashicorp/nomad/pull/18681/files#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09R3238

From what we can tell the reservation is subtracted both on the line linked above and in the `UsableCompute` function.

### Reproduction steps

Add a `reserved` block to the nomad client config and observe `nomad_client_unallocated_cpu`.

```
 reserved {
        cpu = 1000
    }
``` 

Update the reserved block to this:
```
 reserved {
        cpu = 2000
    }
``` 

Restart nomad

#### Expected Result
The metric `nomad_client_unallocated_cpu` should decrease by 1000

#### Actual Result
The metric `nomad_client_unallocated_cpu` decreases by 2000

**Comment by jrasell** [comment]
Hi @ostkrok and thanks for raising this issue with the details. I have been able to reproduce this locally on a single dev agent with the configuration change you showed. Below are the outputs from the metrics endpoint before and after changing the reserved CPU value. I'll get this onto our roadmap.

```
$ curl -s localhost:4646/v1/metrics | jq '.Gauges | .[] | select(.Name | contains("unallocated.cpu")) '
{
  "Labels": {
    "node_pool": "default",
    "node_status": "ready",
    "node_scheduling_eligibility": "eligible",
    "host": "jrasell-Y7T14T96N0",
    "node_id": "7c21f256-8ceb-40ae-a8d5-d94d12e69d82",
    "datacenter": "dc1",
    "node_class": "none"
  },
  "Name": "nomad.client.unallocated.cpu",
  "Value": 35728
}
```

```
$ curl -s localhost:4646/v1/metrics | jq '.Gauges | .[] | select(.Name | contains("unallocated.cpu")) '
{
  "Labels": {
    "node_id": "bcea7b6e-7776-081b-13a6-73ab11ad1631",
    "datacenter": "dc1",
    "node_class": "none",
    "node_pool": "default",
    "node_status": "ready",
    "node_scheduling_eligibility": "eligible",
    "host": "jrasell-Y7T14T96N0"
  },
  "Name": "nomad.client.unallocated.cpu",
  "Value": 33728
}
```
