### ISSUE TITLE
`force_pull=false` should behave closer to `docker pull` 

### ISSUE THREAD

**Issue by Sftobias** [hashicorp/nomad#20548]
### Proposal
I think [`force_pull=True`](https://developer.hashicorp.com/nomad/docs/drivers/docker#force_pull) option in the Docker driver should behave closer to `docker pull` command. Details below.

#### Current behavior
Nomad version: 1.7.3
There currently exists two workflows:
* `force_pull=False`:  Nomad doesn't pull the image if the image exists locally, unless the tag is `latest`.
* `force_pull=True`: Nomad **always** pull the image (_even if the remote image and the local image are the same!_).

#### Expected behavior
I would expect `force_pull=True` to:
1. check if the image that exists locally,
2. if image exists locally, check if the local and remote images are the same (ie. same hash). 
3. only download image if hash is different, possibily only downloading the layers that have changed (not the whole image)

This is basically the behaviour of the standard `docker pull` command.

### Attempted Solutions
Right now we avoid this issue by:
* using `force_pull=False`
* adding a task that pulls the image on the node before the main task.

```hcl
task "docker-update" {
            
    lifecycle {
        hook = "prestart"
        sidecar = false
    }

    driver = "raw_exec"
    config {
        command = "docker"
    args    = ["pull", "<docker image>"]
    }

}
```

However, this does not prevent images with the `latest` tag from being downloaded in their entirety each time the job is run. Other tags are fine.

**Comment by colinbruner** [comment]
The behavior I expect for _force_ pull what you're describing as "Current behavior". If I specify `force_pull`, I want a new image pulled every time, regardless of what is local.

The behavior you've described as "Expected behavior" to me feels more like "smart_pull" or honestly what should probably be the default pulling behavior when `force_pull=false`. 

Intuitively, if I specify `force` as a directive, I expect something to happen every time - regardless of local state.

**Comment by jrasell** [comment]
Hi @Sftobias and thanks for raising this request; and thanks to @colinbruner for adding your thoughts.

I believe the current `force_pull` behaviour is the correct implementation, whereby specifying this configuration value will always pull the image irregardless of the local clients state. I like the idea of enhancing the current non-force pull behaviour to potentially perform addition check optimisations. The [Docker pull command](https://github.com/docker/cli/blob/6c70360c7938f78918b941afebea01f4e0a11bfa/cli/command/image/trust.go#L172) does more work than the base [Docker API exposes for image creation](https://docs.docker.com/engine/api/v1.45/#tag/Image/operation/ImageBuild) and would therefore require work within the Nomad Docker driver to add layer checking and other items.

I'll mark this for roadmapping and requiring more discussion around implementation details, and change the title slightly. If y'all have anymore thoughts, please feel free to add them.

**Comment by Sftobias** [comment]
Hi @jrasell @colinbruner.

I have been testing more thoroughly and it seems that the `force_pull` option works as proposed, that is, it checks if the most recent image is already present and in this case it does not download it.

The confusion comes from a mechanism that nomad has which [deletes the docker images](https://github.com/hashicorp/nomad/issues/713) once the task that was using them stops, and for that reason it downloaded them again in their entirety.

Sorry for the confusion, I'm going to close this issue now that I've verified how the `force_pull` option actually works.
