### ISSUE TITLE
Nomad binary missing from Ubuntu 24.04 repository

### ISSUE THREAD

**Issue by Yethal** [hashicorp/nomad#20545]
### Nomad version
Output from `nomad version`

### Issue
Repository https://apt.releases.hashicorp.com can be added on Ubuntu 24.04 and contains other Hashicorp tools (Terraform, Packer, Consul Template) but Nomad binary is missing

### Reproduction steps
1. Set up Ubuntu 24.04 system
2. Add Hashicorp repo
3. Run `apt search nomad`

#### Expected Result
Nomad available

#### Actual Result
Nomad unavailable

**Comment by jrasell** [comment]
Hi @Yethal and thanks for raising this issue. I will raise this internally and post any updates in this issue.

**Comment by jrasell** [comment]
Hi @Yethal, this should now be resolved as seen below on my test machine after running `sudo apt-get update`:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

$ sudo apt-cache search ^nomad
nomad-enterprise - Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
nomad - Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
nomad-autoscaler-enterprise - Nomad Autoscaler brings autoscaling to your Nomad workloads.
nomad-autoscaler - Nomad Autoscaler brings autoscaling to your Nomad workloads.
nomad-pack - Nomad Pack is a templating and packaging tool used with HashiCorp Nomad.

```
