### ISSUE TITLE
Add support for consul EnableTagOverride

### ISSUE THREAD

**Issue by brunomacf** [hashicorp/nomad#2057]
It would be great to have this consul option in service stanza to enable dynamic tagging. My use case is with mongo replica set.... i have 3 instances, one with "primary" tag and the other with "secondary" tag, but when the primary goes away a new primary is elected and i would like to see this election reflected on (updated) service tags.

**Comment by nickwales** [comment]
This would be a very nice to have. We rely on this on our platform currently and Nomad would need to support this before we could migrate.

**Comment by nickwales** [comment]
Realized I can update consul tags via running the job again with the required updates to the service section. 

- Initial testing suggests the entire service gets re-registered so health checks go critical temporarily which is probably not ideal.
- I haven't seen instances get restarted but are there any instances where that could happen?

To confirm, my testing so far has been changing the contents of the tags array in the service section and re-running the job: https://www.nomadproject.io/docs/job-specification/service.html#tags
