### ISSUE TITLE
Fails to run a nomad job on a Window 10 (Virtual Machine)

### ISSUE THREAD

**Issue by thfai2000** [hashicorp/nomad#20586]
Hi, I'm not sure if it is a bug or not.

### Nomad version
Output from `nomad version`
```
The parameter is incorrect.
Nomad v1.7.7
BuildDate 2024-04-16T19:26:43Z
Revision 0f34c85ee63f6472bd2db1e2487611f4b176c70c
```

### Operating system and Environment details

It is a **VMware provisioned VM machine.**
OS: Windows 10 Enterprise LTSC 21H2
Processor	Intel(R) Xeon(R) Platinum 8276 CPU @ 2.20GHz   2.19 GHz  (2 processors)
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

### Issue

When I start a very simple job, it fails with errors.

### Reproduction steps
Submit the job.

#### Expected Result
The job can run successfully

#### Actual Result

It show errors about plugin issue.

### Job file (if appropriate)

```
job "fo-component" {


  group "example" {

    task "service-task" {
      artifact {
        source      = "https://github.com/thfai2000/jenkins-pipelines/releases/download/1.0/artifact-1.0.zip"
        destination = "local/app"
      }

      template {
        source        = "local/app/config.xml.tpl"
        destination   = "local/app/config.xml"
      }


      driver = "raw_exec"
      config {
        command = "local/app/bin/Release/net8.0/win-x64/.net.exe"
      }

    }

  }

}
```

### Server Configuration
```
enable_debug = true
log_level = "debug"

data_dir  = "F:\\nomad\\data"
log_file = "F:\\nomad\\logs\\"
bind_addr = "0.0.0.0" # the default


server {
  enabled          = true
  bootstrap_expect = 1

}

client {
  enabled       = true
 options {
    # Allow rawexec jobs
    "driver.raw_exec.enable" = "1"
  }
}
```

### Nomad Server logs (if appropriate)
[nomad.log](https://github.com/hashicorp/nomad/files/15307450/nomad.log)

```
2024-05-14T19:06:46.606+0800 [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=f036a49f-5cb2-b3d1-0670-25017280576c task=service-task type="Task hook failed"
  msg=
  | logmon: Unrecognized remote plugin message: The parameter is incorrect.
  | This usually means
  |   the plugin was not compiled for this architecture,
  |   the plugin is missing dynamic-link libraries necessary to run,
  |   the plugin is not executable by this process due to file permissions, or
  |   the plugin failed to negotiate the initial go-plugin protocol handshake
  | 
  | Additional notes about plugin:
  |   Path: F:\nomad\nomad.exe
  |   Mode: -rw-rw-rw-
  |   PE architecture: amd64 (current architecture: amd64)
   failed=false
2024-05-14T19:06:46.608+0800 [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=f036a49f-5cb2-b3d1-0670-25017280576c task=service-task
  error=
  | prestart hook "logmon" failed: Unrecognized remote plugin message: The parameter is incorrect.
  | This usually means
  |   the plugin was not compiled for this architecture,
  |   the plugin is missing dynamic-link libraries necessary to run,
  |   the plugin is not executable by this process due to file permissions, or
  |   the plugin failed to negotiate the initial go-plugin protocol handshake
  | 
  | Additional notes about plugin:
  |   Path: F:\nomad\nomad.exe
  |   Mode: -rw-rw-rw-
  |   PE architecture: amd64 (current architecture: amd64)
```

### Nomad Client logs (if appropriate)
```
Task hook failed: logmon: Unrecognized remote plugin message: The parameter is incorrect. This usually means the plugin was not compiled for this architecture, the plugin is missing dynamic-link libraries necessary to run, the plugin is not executable by this process due to file permissions, or the plugin failed to negotiate the initial go-plugin protocol handshake Additional notes about plugin: Path: F:\nomad\nomad.exe Mode: -rw-rw-rw- PE architecture: amd64 (current architecture: amd64)
```

**Comment by elisazaroni** [comment]
Same error here, some differences.
- Microsoft Windows Server 2012 R2 Standard
- Nomad 1.16.2
- Error occurs for all commands, same mesages

`logmon: Unrecognized remote plugin message: The parameter is incorrect. This usually means the plugin was not compiled for this architecture, the plugin is missing dynamic-link libraries necessary to run, the plugin is not executable by this process due to file permissions, or the plugin failed to negotiate the initial go-plugin protocol handshake Additional notes about plugin: Path: D:\kaffa\executables\nomad.exe Mode: -rw-rw-rw- PE architecture: amd64 (current architecture: amd64)`

**Comment by angrycub** [comment]
Could you help with some additional information?

The OP mentioned that they were running Nomad in a VMware VM, but didn't identify the base OS or VMware version. Could you share the exact stack that you are running on?  Host OS, Virtualization engine and version, Guest OS, and how you are running Nomad (service or interactive, normal user or administrator) 

I tried reproducing this using Hyper-V and didn't encounter the error, so I'd love to get some more information to help make my reproduction more solid. 

Any extra information you or the original submitter can provide would be greatly appreciated.

**Comment by angrycub** [comment]
One additional question. I notice both you and the OP do not have Nomad in the system disk. Is it by chance running on a disk shared into the instance from the host machine? If not, could you tell me more about how that disk was created and is formatted?
