### ISSUE TITLE
[Improvement]: Nomad jobspec with includes

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2058]
Hey guys, 

It would be awesome to be able to do that:

```hcl
job "hello-world" {
  region = "eu-central-1a"
  datacenters = ["eu-central-1a", "eu-central-1b"]

  type = "service"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  ${include "./*.taskgroups.nomad"}

}
```

or

```hcl
job "hello-world" {
  region = "eu-central-1a"
  datacenters = ["eu-central-1a", "eu-central-1b"]

  type = "service"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "api-v1" {
      count = 1
      task "api" {
        driver = "docker"
        config {
          image = "iadvize/api:1"
        }
      }

      ${include "./api-task.nomad"}
  }

  group "api-v2" {
      count = 10
      task "api" {
        driver = "docker"
        config {
          image = "iadvize/api:2"
        }
      }

      ${include "./api-task.nomad"}
  }
}
```

**Comment by jippi** [comment]
personally i think this will add a lot of complexity to the understanding and usage of the job spec. 

you can totally do something like this today if you use the JSON format, where you inject your own custom `meta.include_file`  key, which can be read and dynamically injected into the raw JSON job spec before sending it to the HTTP API.

```hcl
job "hello-world" {
  region = "eu-central-1a"
  datacenters = ["eu-central-1a", "eu-central-1b"]

  type = "service"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "api-v1" {
      count = 1
      task "api" {
        driver = "docker"
        config {
          image = "iadvize/api:1"
        }
      }

      meta {
         include_file = "./api-task.nomad"
      }
  }

  group "api-v2" {
      count = 10
      task "api" {
        driver = "docker"
        config {
          image = "iadvize/api:2"
        }
      }

      meta {
         include_file = "./api-task.nomad"
      }
  }
}
```

put this spec through `nomad run -output job.hcl` - iterate the output using any JSON parser in any language, detect the `meta` key contains a `include_file` key. Read the file in question and merge the result into the JSON job spec. Submit this job spec to the HTTP API :)

**Comment by smoynes-tc** [comment]
I'm not so sure about the proposed design, but I share the use case.

In my case, I have a large template used to create a configuration file for a task. Including it inline makes the job specification less readable by presenting a big blob of obscure configuration parameters. I think it would be more understandable to store the template in a separate file and including or expanding it prior to submitting it to the HTTP API.

**Comment by lfarnell** [comment]
I do believe that [Levant](https://github.com/jrasell/levant) might be able to help a few of you out with the job templating.
