### ISSUE TITLE
Use CPU MaxSpeed for cpu_total_compute 

### ISSUE THREAD

**Issue by revverse** [hashicorp/nomad#20608]
In old versions of the Nomad  ( before https://github.com/hashicorp/nomad/pull/18146/ ) cpu_total_compute was calculated as a result of CPU max_frequency from file 'cpuinfo_max_freq' in Linux
`	cpuMaxFile     = sysRoot + "/cpu/cpu%d/cpufreq/cpuinfo_max_freq"`
or used BaseSpeed if the cpuMaxFile doesn't exist
In the current version, Nomad always uses BaseSpeed for 'cpu.totalcompute' 
```bash
# cat /sys/devices/system/cpu/cpu1/cpufreq/base_frequency
2000000
# cat /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq
3800000
```
and Client page in Nomad shows:

> cpu.arch 	amd64
> cpu.frequency 	2000
> cpu.modelname 	Intel(R) Xeon(R) Gold 5418Y
> cpu.numcores 	96
> cpu.reservablecores 	96
> cpu.totalcompute 	192000
> cpu.usablecompute 	192000
> 

I'm not an expert in Golang but maybe the main issue in this part of code
```golang
func (c Core) MHz() hw.MHz {
	switch {
	case c.BaseSpeed > 0:
		return c.BaseSpeed
	case c.MaxSpeed > 0:
		return c.MaxSpeed
	}
	return c.GuessSpeed
}
```
When BaseSpeed is set, MaxSpeed will never used 
So I change it to
```golang
func (c Core) MHz() hw.MHz {
	switch {
	case c.MaxSpeed > 0:
		return c.MaxSpeed
	case c.BaseSpeed > 0:
		return c.BaseSpeed
	}
	return c.GuessSpeed
}
```
And Nomad start using MaxSpeed 

> cpu.frequency 	3800

Maybe we should use this behavior as default? 

Commit: https://github.com/revverse/nomad/commit/dedc5ec528aff1d78e0f2c61d9e0085d7557b127
UPD: Affected versions - 1.7.x

**Comment by shoenig** [comment]
Using the "max speed" is nonsensical - Intel and AMD both set this value to a speed that is achievable by a single core maybe for a few milliseconds. In contrast the base speed is highest speed sustainable by all cores indefinitely. 

If you want to override the amount of compute available you can do so using 
https://developer.hashicorp.com/nomad/docs/configuration/client#cpu_total_compute

**Comment by revverse** [comment]
Ok. So, what is the reason to use MaxSpeed in the Nomad codebase? 
Before version 1.7, Nomad used MaxSpeed as default, now you say that is BAD, but there are a lot of places where MaxSpeed is calculated and used. Maybe need just to remove this code?

**Comment by FelipeLopes-systematica** [comment]
This will create a sad surprise for lots of people upgrading their stack, like myself... My EC2 instances were fine and now they aren't anymore. I don't think this should've been closed. It's a huge change that impacts a lot and might break clusters making it impossible to run the same workload.
