### ISSUE TITLE
Incorrect documentation around docker auth

### ISSUE THREAD

**Issue by geekodour** [hashicorp/nomad#20630]
https://developer.hashicorp.com/nomad/docs/v1.6.x/drivers/docker#authentication
mentions the following
```
plugin "docker" {
  config {
    auth {
      helper = "ecr-login"
    }
  }
}
```
while as per
https://github.com/hashicorp/nomad/blob/a3b1810bdbc2be395d2e4035dd8ce45e4b5ce33b/drivers/docker/config.go#L60-L63

it should be
```
plugin "docker" {
    auth {
      helper = "ecr-login"
    }
}
```

**Comment by geekodour** [comment]
In nixos config, it would go file

```
      plugin = {
        docker."auth.helper" = "ecr-login";
      };

```

**Comment by pkazmierczak** [comment]
Hi @geekodour, thanks for filing an issue! I'm afraid the documentation is correct, though, plugin configuration must live within a `config` block. Have a look at the [configSpec](https://github.com/hashicorp/nomad/blob/a3b1810bdbc2be395d2e4035dd8ce45e4b5ce33b/drivers/docker/config.go#L187) structure to better understand how plugin config is parsed.

**Comment by geekodour** [comment]
@pkazmierczak yes you're right, I've updated my previous comment to reflect the same. Apologies for the confusion!

**Comment by geekodour** [comment]
@tgross ^ updated the comment with appropriate config that worked. Think it's an issue already being tracked.
