### ISSUE TITLE
Docker driver Auth interpolation not working

### ISSUE THREAD

**Issue by tmichaud314** [hashicorp/nomad#2064]
### Nomad version
Output from `nomad version`
Nomad v0.5.0

### Operating system and Environment details
Ubuntu 14.04 LTS

### Issue
There is a bug in the docker driver for `auth` configuration that causes it to effectively ignore meta/variables in `auth` config. 

See [PR for the exact details](https://github.com/hashicorp/nomad/pull/2063).

### Reproduction steps
In a Nomad Client configuration file, add:
```
{
  meta {
    "dhusername" = "user"
    "dhpassword" = "pass"
  }
}
```

Or, add the same meta key/values to a job specification at any level (job, group, task).

Then, run a job that specifies a docker-driver task and an `auth` stanza:
```
{
  task "my-service" {
    driver = "docker"
    config {
      image = "my-service"
      auth {
        username = "${NOMAD_META_DHUSERNAME}"
        password = "${NOMAD_META_DHPASSWORD}"
      }
    }
  }
}
```

The resulting interpolated values for `username` and `password` are incorrectly left in their original form, `${NOMAD_META_DHUSERNAME}` and `${NOMAD_META_DHPASSWORD`, respectively.

**Comment by tmichaud314** [comment]
@dadgar We'd like to get this fixed so that jobs can be submitted through the Jobs API without having to encode repository credentials into the docker-driver config.  Was the issue description confusing?

**Comment by dadgar** [comment]
@tmichaud314 Hey nope we will get this in for 0.5.2. 0.5.1 was a bit of a hot-fix release so didn't want to expand its scope. Wanted to get it out as quickly as possible. Now that it is cut we will be able to go through your PR.

Thanks for the patience!

**Comment by dadgar** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/2063
