### ISSUE TITLE
[Improvement] Docker exec from Nomad binary

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2065]
Hi guys,

It would be awesome to add a command in Nomad, to execute some command in a container. (something like ```kubectl exec``` or ```docker exec```).

Unfortunately, this is specific to docker driver. Do you know how we could manage that ?

**Comment by dadgar** [comment]
For now you would have to ssh and then execute the `docker exec` command but this is something interesting to us

**Comment by Dgadavin** [comment]
+1 
I think it will be very usefull

**Comment by chamblin** [comment]
Yes yes yes yes yes

**Comment by margueritepd** [comment]
This would be useful for giving our dev team access to debug from the point of view of their running application without giving them SSH access.

**Comment by aknuds1** [comment]
We could also really use this, as we miss the ability of executing interactive shells within containers running in the cluster. In Kubernetes we would do this with a command like `kubectl exec -ti $POD /bin/bash`.

**Comment by 42wim** [comment]
We had the same issue, so I've build a tool that does this.
It's a sshserver that sits inbetween dev and nomad, you can use plain ssh for commands or use the simple nomadctl wrapper. Authentication via ssh keys.

See https://github.com/42wim/nomadctld for more info

**Comment by margueritepd** [comment]
Any thoughts about the priority of this item / if it would end up on the roadmap any time soon?

**Comment by preetapan** [comment]
@margueritepd building a `nomad exec` capability is on the roadmap for a minor release after 0.9 is out.

**Comment by pchernik** [comment]
Any guesstimates on rough timeline for this feature being implemented?

**Comment by josegonzalez** [comment]
SeatGeek has https://github.com/seatgeek/nomad-helper#attach

**Comment by josegonzalez** [comment]
Actually coming back to this, does [alloc exec](https://www.nomadproject.io/docs/commands/alloc/exec.html) do what we need for this?

**Comment by drewbailey** [comment]
It does indeed, closing! 

https://www.nomadproject.io/docs/commands/alloc/exec.html
