### ISSUE TITLE
Template: use keyOrDefault instead of key_or_default

### ISSUE THREAD

**Issue by gokhansengun** [hashicorp/nomad#2066]
### Details

Nomad v0.5.0
Linux, Ubuntu, 4.4.0-31-generic, x86_64

### Issue

Using the template stanza, deprecated function `key_or_default` is required instead of `keyOrDefault`.

Using a config like below in the template file;

```
global
    maxconn {{keyOrDefault "lbs/maxconn" "1000"}}
```

produces following error

```
Killing task: consul-template: template: template: haproxy.ctmpl:2: function "keyOrDefault" not defined
```

It obviously seems to be related with the packaged consul-template version. Opening this to track for next versions.

**Comment by dadgar** [comment]
Believe we just need to re-vendor consul-template
