### ISSUE TITLE
[Improvement] NOMAD_GROUP_COUNT_INDEX interpolation

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2068]
Hi guys,

It would be awesome to get a NOMAD_GROUP_COUNT_INDEX inside a ```group``` stanza, changing according to the ```count``` field. Something similar to the ```count.index``` of Terraform.

It could be used in the ```service``` stanza, to postfix the name of the service. Ex:
- ```rabbitmq-1```
- ```rabbitmq-2```
- ```rabbitmq-3```

**Comment by dadgar** [comment]
You can use `NOMAD_ALLOC_INDEX` which should accomplish the same thing 👍 

https://www.nomadproject.io/docs/runtime/environment.html

If that is what you need would you mind closing the issue. Thanks!

**Comment by samber** [comment]
Ok, thanks. Closing this issue.
