### ISSUE TITLE
Nomad Client show allocated resources as metric

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#2072]
Adding the following metrics would be useful for determining cluster capacity
"nomad.allocated.memory"
"nomad.allocated.disk"
"nomad.allocated.cpu"

**Comment by Sedward** [comment]
This would be nice! We're measuring what nomad has available for allocations (not 1-1 with the host) and what we've consumed. So maybe a nomad.allocated.memory.total and nomad.allocated.memory.used?

**Comment by dadgar** [comment]
Fixed: https://github.com/hashicorp/nomad/blob/master/client/client.go#L2251-L2282
