### ISSUE TITLE
[Question] Driver constraint not working as expected

### ISSUE THREAD

**Issue by oribaldi** [hashicorp/nomad#2078]
Hello guys,

We are trying to run a job that executes a script (raw_exec driver) that communicates with Docker. Therefore, we want to constraint the job to only those nodes where the docker driver is enabled (${driver.docker} = 1).  However, when adding the constraint

    constraint {
        attribute = "${driver.docker}"
        value     = "1"
    }

the run fails to place an allocation with the reason:
* Constraint "${driver.docker} = 1" filtered 1 nodes

even though the nodes in the cluster have the docker diver. I checked this with the command "nomad node-status -verbose ID", and part of the output is:

driver.docker = 1
driver.docker.version = 1.12.3
driver.docker.volumes.enabled = 1

Is this the expected behavior or is it a bug?

### Nomad version
Nomad v0.5.0

### Operating system and Environment details
Ubuntu 14.04.2 LTS

### Issue
The driver constraint filters nodes that has the driver enabled.

### Expected behavior
The job runs only on the nodes with docker.

### Job

    job "myJob" {
        datacenters = ["dc1"]
        type             = "batch"

        constraint {
            attribute = "${driver.docker}"
            value     = "1"
        }

        group "myJob" {
            task "myTask" {
                driver = "raw_exec"
                artifact {
                    source      = "https://some-site/file"
                    destination = "/tmp/"
                }
                config {
                    command = "/tmp/file"
                }
            }
        }
    }

**Comment by diptanu** [comment]
@oribaldi Please use `attr.driver.docker`. Let me know if that solves the issue?

**Comment by oribaldi** [comment]
@diptanu With that change the run does not fail, but when I check the status of the job I found the following:

ID          = myJob
Name    = myJob
Type      = batch
Priority   = 50
Datacenters = dc1
Status      = pending
Periodic    = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
    myJob       0       0         0        0       0         0

Placement Failure
Task Group "myJob":
  * Constraint "computed class ineligible" filtered 1 nodes
  * Constraint "${driver.docker} = 1" filtered 1 nodes

**Comment by oribaldi** [comment]
Nevermin, it works now. Thanks! You guys should update the documentation :)
