### ISSUE TITLE
easy way to increase/decrease number of group.count

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#208]
for dynamic scaling up and down, instead of writing the full job file and apply it, it would be nice with a "incr" and "decr" api endpoint for just that

**Comment by armon** [comment]
@jippi There isn't currently an API for doing this, but I do like the idea of it! I think it's something we'd like to support in the future.

**Comment by jippi** [comment]
lovely! :)

**Comment by diptanu** [comment]
@jippi You don't want this anymore?

**Comment by jippi** [comment]
@diptanu eventually, sure, right now i skipped my nomad experiments entirely (due to missing UI), so just cleaned up my outstanding tickets :) feel free to re-open if its with having revived

**Comment by dadgar** [comment]
This is a feature I want to see.

**Comment by tantra35** [comment]
Yes it will be cool if this feature apear in the nomad

**Comment by jippi** [comment]
@diptanu @dadgar is this something that is planned near-term? currently having to machine-modify a job file and re-apply it to scale a service is a lot of work vs just hitting an endpoint and let the state update live :)

**Comment by dadgar** [comment]
Hey,

It isn't something we are currently working on but I will see if we can squeeze it in to 0.5.1

**Comment by jippi** [comment]
yay @dadgar !

**Comment by jippi** [comment]
@schmichael 0.8 instead maybe? :P

**Comment by jippi** [comment]
i guess not for 0.8  :D

**Comment by aclowkey** [comment]
I'm looking for a way to do this, without modifying nomad's code.
One approach would be like levant, get job, modify the count, apply job. But the issue I encounter is that the original job file still has the original count, and I don't know how make Nomad ignore it..

**Comment by tgross** [comment]
We shipped the APIs to support this in [0.11.0](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#0110-april-8-2020)
