### ISSUE TITLE
secrets directory is drwxrwxrwx

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#2088]
`Nomad v0.5.1-rc1 ('6099b127fa7267ede63465bb0469e443f21d6343+CHANGES')`
`Linux gocd-agent-d976964b 4.8.12-1.el7.elrepo.x86_64 #1 SMP Fri Dec 2 12:31:53 EST 2016 x86_64 x86_64 x86_64 GNU/Linux`

The `secrets` directory for a task is world readable and writable:

```
# ls -ald /var/lib/nomad/alloc/5a1e6069-2c3b-0e7f-4272-0bc66903fa33{,/agent{,/secrets}}
drwxr-xr-x 4 root   root   4096 Dec  8 03:11 /var/lib/nomad/alloc/5a1e6069-2c3b-0e7f-4272-0bc66903fa33
drwxrwxrwx 5 nobody nobody 4096 Dec  8 03:11 /var/lib/nomad/alloc/5a1e6069-2c3b-0e7f-4272-0bc66903fa33/agent
drwxrwxrwx 3 nobody nobody   80 Dec  8 03:11 /var/lib/nomad/alloc/5a1e6069-2c3b-0e7f-4272-0bc66903fa33/agent/secrets/
# mount | grep 5a1e6069-2c3b-0e7f-4272-0bc66903fa33
tmpfs on /var/lib/nomad/alloc/5a1e6069-2c3b-0e7f-4272-0bc66903fa33/agent/secrets type tmpfs (rw,noexec,relatime,size=1024k)
```

**Comment by dadgar** [comment]
Hey @blalor,

The parent directory is such that non-root users can't access that folder. We get by this by mounting those directories in the case of container based systems and we chroot into the allocation directory on exec. But if you just play with it you will see that unless you are root you can not actually access those directories.

**Comment by blalor** [comment]
Yeah, you're right.  My apologies; temporary failure in Unix-fu.  Thank you!
