### ISSUE TITLE
artifact {} with custom destination does not work as advertised

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2092]
### Nomad version

0.5.1-rc1

### Operating system and Environment details

Linux Debian 7.9

### Issue

Based on the docs

```
artifact {
  source      = "https://example.com/file.txt"
  destination = "/tmp/example.txt"
}
```

should create `/tmp/example.txt`, though adjusting it to my own paths like below, this is not the case

```
artifact {
	source      = "https://xxxx/template/{{PROJECT_NAME}}/{{APP_ENV}}/{{APP_VERSION}}/consul-template/php-fpm.ctmpl"
	destination = "/local/php-fpm.conf"
}
```

It actually created `/server/local/php-fpm.conf/php-fpm.ctmpl` instead. Thus using the `destination` as a directory (ignoring the file part) and putting the file inside the `destination` directory as-named on the  `source` url

**Comment by dadgar** [comment]
Hey destination is relative to the allocation directory. It is not absolute. Please see the documentation: https://www.nomadproject.io/docs/job-specification/artifact.html#destination

Agree that it should do a rename rather than a join.

**Comment by jippi** [comment]
@dadgar know it's "relative" :) the only problem is the destination is really just the directory, so end result is `${destination}/${basename source}` which is very surprising :P

**Comment by dadgar** [comment]
@jippi This isn't really possible with the API of go-getter. It assumes destination is a folder,  just dug into the API. The only way to do this is to introduce a new option in the artifact block `file = true` which would treat it as a file and download it to that file name. Is that desirable? If `file = true` and you download not a file it would error.

**Comment by dadgar** [comment]
Talked in Gitter, but following up. Added better documentation in this commit: 30655ef5578a4b97db32159d92bf3817a1700634

I want to avoid a special flag and until a very compelling case comes up, the docs should suffice.

**Comment by jippi** [comment]
@dadgar seems legit to me ! thank you

**Comment by shantanugadgil** [comment]
I stumbled upon this same issue today.

In my opinion, not able to specify the file name, enforces an artificial constraint on the user.

I had imagined that I would be able to keep various config files together in my S3 bucket, and based on some option, be able to pick any one from the S3 bucket and save it with a common name in the destination.
This was so that my docker could then assume a fixed named for the config file.

Being able to name the destination file seemed obvious to me. Hope this gets implemented.
* Having an extra "file" parameter doesn't seem elegant though.

Regards,
Shantanu

**Comment by jippi** [comment]
Pretty sure this is fixed in next release as go-getter now support file mode :)

**Comment by shantanugadgil** [comment]
FWIW, I am using version `Nomad v0.6.0-rc1 (5187fcfcae50e3dee61e5340eb99805a564b55c3+CHANGES)`

Could you point me to the place where go-getter mentions how to set target as a file ?
I couldn't find any open/closed issue in the go-getter issues section about this. 😢 
https://github.com/hashicorp/go-getter/issues

Regards,
Shantanu

**Comment by jippi** [comment]
I think https://github.com/hashicorp/nomad/pull/2781 is what you are looking for

**Comment by jippi** [comment]
See https://github.com/hashicorp/nomad/pull/2781/files#diff-37b5aa5df3b4c75cad9afbd78b0654bcR55

**Comment by shantanugadgil** [comment]
@jippi Thanks, Got it!
`mode = "file"`

👍 

Regards,
Shantanu
