### ISSUE TITLE
NodeName on telemetry

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#2094]
Hi!

I configured nomad to send metris to statsd. I was expecting the metric to contain the nodename I set on the configuration, but instead the hostname was sent. I saw that is the go-metrics package the one that picks the hostname and set that value on each metric (https://github.com/hashicorp/nomad/blob/master/vendor/github.com/armon/go-metrics/start.go#L48) 

I don't know if it is possible to change that value to use the nodename (or if this makes sense).

I think that just inserting `metricsConf.HostName = config.NodeName`  on https://github.com/hashicorp/nomad/blob/master/command/agent/command.go#L624 should be enought to change the behaviour. 

I could do a PR if you agree with this.

**Comment by dadgar** [comment]
Seems reasonable! We would welcome a PR for this. To be clear it would be a boolean option setting host name to node name

**Comment by jorgemarey** [comment]
Great! I'll do the PR.
