### ISSUE TITLE
nomad scheduled job to a down node

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/nomad#2104]
I have 3 nodes, node0 is down, but when I run `nomad run job` with `count=2` one of the job is scheduled to the down node.

```
nomad node-status
ID        DC   Name   Class   Drain  Status
5a71b96c  dc1  node0  <none>  false   down
04bc929b  dc1  node1  <none>  false  ready
383a0819  dc1  node2  <none>  false  ready
```

after I stop the job, the service registered in consul is not deleted.

```
curl -s http://localhost:8500/v1/catalog/service/myjob | jq .
[
  {
    "ModifyIndex": 5218404,
    "CreateIndex": 5218404,
    "ServiceEnableTagOverride": false,
    "Node": "node0",
    "Address": "10.0.1.247",
    "TaggedAddresses": {
      "wan": "10.0.1.247"
    },
    "ServiceID": "_nomad-executor-187aa03e-cc8b-e18e-cbbc-a00a119a19e3-myjob-myjob",
    "ServiceName": "myjob",
    "ServiceTags": [],
    "ServiceAddress": "10.0.1.247",
    "ServicePort": 27725
  }
]
```

nomad version is v0.4.0, consul version is 0.6.4

**Comment by jippi** [comment]
can you please try with 0.5.1 ? :)

**Comment by waterdudu** [comment]
Thanks @jippi

I updated both nomad servers and clients to version 0.5.1, problem served. But in the nomad log I still saw some strange message about the down node and the down node was still not removed after drain the node.

```
time="2016-12-15T18:16:47.634182437+08:00" level=warning msg="2016/12/15 18:16:47 [WARN] memberlist: Refuting a suspect message (from: node-0)\n"
```

```
ID        DC   Name    Class   Drain  Status
5a71b96c  dc1  node-0  <none>  true   down
04bc929b  dc1  node-1  <none>  false  ready
383a0819  dc1  node-2  <none>  false  ready
```

**Comment by dadgar** [comment]
@waterdudu You may have to manually clean up that state from Consul since it is no longer tracking that. The newer version of Nomad should be more robust with Consul.

The nodes get garbage collected at an interval. Nomad won't schedule to them but you will still see it when interacting with the CLI. You can force a GC immediately by running:

`curl -XPOST http://127.0.0.1:4646/v1/system/gc`.

**Comment by waterdudu** [comment]
After referring to nomad document `https://www.nomadproject.io/docs/http/system.html`, it should be a `PUT` method.

After running `curl -XPUT http://127.0.0.1:4646/v1/system/gc`, the down node disappeared.

Thank you @dadgar
