### ISSUE TITLE
[question] docker -netalias or alternative

### ISSUE THREAD

**Issue by jrusiecki** [hashicorp/nomad#2105]
Nomad 0.5.0, Consul 0.7.1, Docker 1.12
I use docker overlay network between containers. To find other container to connect to I use docker built-in DNS. It allows me to lookup IP of node (e.g. elastic01) by node name. But with nomad name is unpredictable. I've read -netalaist parameter to docker run solves the problem - but HOW to specify -netalias for docker with job specification?

**Comment by diptanu** [comment]
@jrusiecki There is a PR out there which allows users to pass the net alias to the docker daemon. Once that is merged this would be possible.

**Comment by diptanu** [comment]
Fixed by #1980

**Comment by jrusiecki** [comment]
Thx, will try :)
