### ISSUE TITLE
Add tagged metrics support to Nomad "StatsD"

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2110]
Per https://github.com/DataDog/dd-agent/issues/2959 Nomad currently does not emit statsd events in a way that is efficient for datadog - they don't want "tags" in the key, but rather key value pairs

**Comment by kris-runzer** [comment]
I'm running into this issue as well.  I was excited about the datadog telemetry until I actually got to using it :(

**Comment by kris-runzer** [comment]
I'm taking a stab at implementing this.  Had to start go-metrics:  [pull/44](https://github.com/armon/go-metrics/pull/44)

**Comment by jippi** [comment]
Today this can be done using prometheus metrics + telegraf to emit it to both influx and datadog as tagged metrics

**Comment by dadgar** [comment]
This is also supported for DogStatsD as of Nomad 0.7. StatsD doesn't support tags.

**Comment by scalp42** [comment]
@dadgar StatsD does not support tags but you can ask StatsD to disable key sanitization which will allow backend to handle sanitization.

Graphite *does* handle tags.
