### ISSUE TITLE
nomad job pending for too long

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/nomad#2111]
I set count=2 in task group with docker driver, after run nomad run command, I noticed one of the allocations changed status to running in several seconds , but the other one changed status for too long (about 1 minute). 

Here is my job conf.

```
job "simple-server" {
  type = "service"
  datacenters = ["dc1"]
  update {
    stagger = "3s"
    max_parallel = 1
  }
  group "simple-server" {
    count = 2
    task "simple-server" {
      service {
        name = "simple-server"
        port = "http"
      }
      driver = "docker"
      config {
        image = "mydockerregistry.com/simple-server:0.0.1"
        auth {
          server_address = "https://mydockerregistry.com"
          username = "admin"
          password = "admin"
        }
        port_map = {
          http = 40000
        }
      }
      resources {
        cpu = 200
        memory = 100
        network {
          mbits = 1
          port "http" {
          }
        }
      }
    }
  }

}
```
The nomad version is 0.5.1.

When I deploy a new version, the simple-server service is unavailable when scheduling is executing, returning a response code 503 by haproxy. The rolling-update strategy will reduce downtime, but it seems the service may not work well during rolling update.

I feel confused about this, could anyone figure out what the problem is or did I just do something wrong by using this excellent tool?

I use consul-template to update haproxy.cfg.

Here is the conf of consul-template.

```
listen simple-server
    balance roundrobin
    bind *:9982{{range service "simple-server"}}
    server {{.Node}} {{.Address}}:{{.Port}}{{end}}
    option forwardfor
    option httpclose
    option http-server-close
```

Thanks in advance

**Comment by diptanu** [comment]
I have responded to your question on the mailing list. Please free to close this issue if that answers your question.

**Comment by waterdudu** [comment]
Thanks for reply on the mailing list. Will close this issue.
