### ISSUE TITLE
Link to nomad 5.1 linux x64 redirecting to linux_x64_lxc

### ISSUE THREAD

**Issue by ricardoseriani** [hashicorp/nomad#2112]
When I access [download page](https://www.nomadproject.io/downloads.html), the button to download linux x64 version is redirecting to [nomad_0.5.1_linux_amd64_lxc.zip](https://releases.hashicorp.com/nomad/0.5.1/nomad_0.5.1_linux_amd64_lxc.zip) instead of [nomad_0.5.1_linux_amd64.zip](https://releases.hashicorp.com/nomad/0.5.1/nomad_0.5.1_linux_amd64.zip)

**Comment by dadgar** [comment]
The website has been redeployed with the correct links! Thank you for reporting!
