### ISSUE TITLE
Mixing stdout and stderr logs

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2123]
Hi guys,

I use the nomad logs -f <job-name> command pretty often, to display stdout and stderr logs, but I always need to execute it two times. What about:

- nomad logs -stdout: only logs on 1
- nomad logs -stderr: only logs on 2
- nomad logs: logs on 1 and 2

Docker respects this rule.

**Comment by mildred** [comment]
For tailing logs, this might be possible. Just like `tail -f` does. But for past logs, this is more complex. We have no way to order the logs between stdout and stderr. A timestamp might work on most cases but not all, and we do not store it anyway.

Perfect ordering can be made possible but I think you need to allocate a tty for stdout and stderr, a bit more complex than forwarding logs to a file.
