### ISSUE TITLE
Nomad status reports "placement failure" even when job is running ok

### ISSUE THREAD

**Issue by drscre** [hashicorp/nomad#2124]
Nomad v0.5.1

First, I tried do deploy a job with wrong datacenter "nomad-dc1". Nomad gave me Placement Failure as expected.

Then I redeployed the same job, but now with correct datacenter "production". 
Job was successfully launched, but `nomad status` still reports Placement Failure:

```
ID          = test-service-default
Name        = test-service
Type        = service
Priority    = 50
Datacenters = production
Status      = running
Periodic    = false

Summary
Task Group       Queued  Starting  Running  Failed  Complete  Lost
grammar-service  0       0         1        0       0         0

Evaluations
ID        Priority  Triggered By  Status    Placement Failures
55f4cfd3  50        job-register  complete  false
614ce8b7  50        job-register  blocked   N/A - In Progress
08cba1a6  50        job-register  complete  true

Placement Failure
Task Group "test-service":
  * No nodes were eligible for evaluation
  * No nodes are available in datacenter "nomad-dc1"

Allocations
ID        Eval ID   Node ID   Task Group       Desired  Status   Created At
67cea612  55f4cfd3  5d9330ea  test-service  run      running  12/16/16 20:56:13 UTC
```

**Comment by pgporada** [comment]
If you rename the job and try to `nomad run newname.nomad`, do you still get the placement error?

**Comment by drscre** [comment]
No, `nomad status` does not report Placement Failure if I rename a job.

I guess it has something to do with this loop https://github.com/hashicorp/nomad/blob/master/command/status.go#L267
which picks up a failed placement from the past evaluations even if it is no more relevant

**Comment by drscre** [comment]
I added evaluations to the client log. As you can seem, the most recent evaluations 55f4cfd3 was successfull and job is running ok.
But nomad status still seems to consider previous

**Comment by dadgar** [comment]
Hey this is a known bug. It is only a UX issue and won't actually impact your job. Still an issue tho!
