### ISSUE TITLE
Node Events/History

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/nomad#2126]
It'd be nice to have insight into a node's history (both server and client), through something like events (or telemetry). 

Things like a node coming up, down, drain enabled, disabled, status changes, etc. For servers, things like leader changes, alive/dead, suspect dead, build version change, etc.

**Comment by scalp42** [comment]
@diptanu @justinwalz mirroring the events bus from Marathon would be amazing, see https://mesosphere.github.io/marathon/docs/event-bus.html

**Comment by tgross** [comment]
Shipped as the Event Stream feature in [Nomad 1.0.0](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#100-december-8-2020)
