### ISSUE TITLE
[question] How to determine placement errors via API?

### ISSUE THREAD

**Issue by drscre** [hashicorp/nomad#2127]
We are using a custom tool to deploy microservices with Nomad. 
It communicates with nomad via API

What is a correct way to determine placement errors via API?
I guess I need to somehow analyze evaluations.

**Comment by diptanu** [comment]
@drscre Yeah, the evaluations HTTP API will provide you with all the evaluations and you could inspect them to know about placement errors.

Closing the issue, feel free to ask any follow up questions. Usually, the mailing list works better for questions.

**Comment by dadgar** [comment]
Hey @drscre you can see the errors in the example here: https://www.nomadproject.io/docs/http/eval.html

You want to look for `FailedTGAllocs`

**Comment by drscre** [comment]
@dadgar 

But what is the algorithm?
If I just look for a `complete` evaluation with status `FailedTGAllocs` I might get some old, non-relevant evaluations.
How do I determine that this `FailedTGAllocs` evaluation corresponds to the current job state?

**Comment by dadgar** [comment]
@drscre The gist of it is that you want to find the Eval with the greatest `CreateIndex` that has `FailedTGAllocs`. If there is a complete evaluation after that without any `FailedTGAllocs` then there are no placement failures.
