### ISSUE TITLE
Link to changelog docs on the upgrading page and/or the download page.

### ISSUE THREAD

**Issue by csawyerYumaed** [hashicorp/nomad#2129]
This is sort of two issues, but.. not really.  I think overall the Changelog should be easier to access, right now the only way I know of to access the Changelog is thru the github site.

The nomad documentation (https://www.nomadproject.io/docs/index.html) does not include links to the Changelog, It would be very handy if the changelog was available from the docs.

The nomad download page (https://www.nomadproject.io/downloads.html) does not include a link to the changelog for the newest release.  It would be handy if there was a link there.

**Comment by pgporada** [comment]
I created a PR for the Nomad `downloads.html` page, but am not sure what to do about the `docs/index.html` page. The download page is an [erb](http://www.stuartellis.name/articles/erb/) template while the `docs/index.html` is just a markdown file that would have to be manually updated at each release. That's probably a no-go from maintenance alone.

**Comment by dadgar** [comment]
Going to close this as it has been added to the downloads page and is inline with our other tools. Thanks for the report @csawyerYumaed and the PR @pgporada
