### ISSUE TITLE
Don't start the syslog server if an external syslog server is used (enhancement)

### ISSUE THREAD

**Issue by bluen** [hashicorp/nomad#2131]
A syslog (helper) server is started in the [docker driver around line 415](/hashicorp/nomad/blob/master/client/driver/docker.go#L414) even if an external syslog server is configured in the task
```
} else if len(driverConfig.Logging) == 0 || driverConfig.Logging[0].Type == "syslog" {
ss, err := exec.LaunchSyslogServer()
```
I think the `driverConfig.Logging[0].Type == "syslog"` could be removed (or enhanced to also take the configured syslog-address into account).

I usually configure tasks like this
```
logging {
          # log to rsyslogd on the node itself
          type = "syslog",
          config {
            "syslog-address" = "tcp://127.0.0.1:1514",
            "syslog-facility" = "...",
            "tag" = "..."
          }
        }
```
and noticed that a syslog plugin is started anyway for each container, which is unnecessary.

**Comment by tgross** [comment]
Doing a little bit of issue cleanup. We removed the syslog server in 0.9, and there are further improvements planned for log drivers elsewhere.
