### ISSUE TITLE
Nomad 1.7.7 Inconsistent Service Discovery Between UI & CLI

### ISSUE THREAD

**Issue by rahadiangg** [hashicorp/nomad#21339]
### Nomad version
Nomad v1.7.7
BuildDate 2024-04-16T19:26:43Z
Revision 0f34c85ee63f6472bd2db1e2487611f4b176c70c

### Operating system and Environment details
Ubuntu 22.04.4 LTS
ARM64
4 Core 24GB

### Issue
I have nomad job like this:
1. Job A --> 1 Task --> 1 Allocation
2. Job B --> 1 Task --> 3 Allocations

That task registed in service discovery with nomad provider. On the nomad UI that service pointed correctly for each allocation.

<img width="921" alt="Screenshot 2024-05-20 at 20 33 13" src="https://github.com/hashicorp/nomad/assets/15994861/bf7bf7bd-e930-4fec-93a5-bdcc57e0c9db">
<img width="880" alt="Screenshot 2024-05-20 at 20 34 51" src="https://github.com/hashicorp/nomad/assets/15994861/2983497f-f889-4c31-a900-723dc190ebc7">

Hower, Whe I try to check using `nomad service info <name>` command, the result it's not same and inconsistent. 

![2024-05-20_20-38](https://github.com/hashicorp/nomad/assets/15994861/5c1c7d26-605c-4ab4-8ab0-d379b634d3ad)

### Reproduction steps
Deploy 2 different job with registed to nomad provider service discovery

#### Expected Result
1. The result from `nomad service info <name>` command same like in nomad UI
2. Service have pointed to correct allocation

#### Actual Result
1. Result of `nomad service info <name>` command inconsistent. Sometimes show the another allocations.
2. Service have pointed to 3 allocations but there only one running allocation

**Comment by jrasell** [comment]
Hi @rahadiangg and thanks for raising this issue. I previously raised this within https://github.com/hashicorp/nomad/issues/19542, therefore I'll close this out as a duplicate.
