### ISSUE TITLE
[Cli Improvement] 'nomad status' not displaying partial running task group

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2134]
Hi guys,

If one task fail running in a task group, we get different informations between ```nomad status <job-name>``` and ```nomad alloc-status <alloc-id>```. The ```status``` command displays task group as 'running" when at least one task is running. It can be confusing.

Could we add a "Partial running" or "Running task" column on the right of "Running" to show the percentage of running tasks ?

Or in the "allocation" block, replace the "running" label of "Status" column to "partial run" ?

**Comment by cgbaker** [comment]
closing this in favor of https://github.com/hashicorp/nomad/issues/3029
