### ISSUE TITLE
Allow setting Notes on consul health checks

### ISSUE THREAD

**Issue by nicoche** [hashicorp/nomad#21372]
Hey there!

It seems that it's impossible to set the `Notes` field of [Consul health checks](https://pkg.go.dev/github.com/hashicorp/consul/api#AgentServiceCheck) using [Nomad's](https://pkg.go.dev/github.com/hashicorp/nomad/api#ServiceCheck).

Is it expected? If no, can we add it? I'm happy to provide a PR.

**Comment by pkazmierczak** [comment]
Hi @nicoche, thanks for reporting this. It seems we're missing the `Notes` field on our side of the API indeed. Feel free to submit a PR and I'll review it. Thanks!

**Comment by nicoche** [comment]
Hey @pkazmierczak ! I will submit a PR soon, then

**Comment by nicoche** [comment]
Here goes @pkazmierczak: https://github.com/hashicorp/nomad/pull/22397. Let me know if I missed some needed changes
