### ISSUE TITLE
Can't Schedule with meta value

### ISSUE THREAD

**Issue by tviaud** [hashicorp/nomad#2141]
### Nomad version
Nomad v0.5.1

### Operating system and Environment details
Debian Jessie, EC2 instance (All security groups are good)

### Issue
Can't schedule a service job in nomad with a constraint on node meta data.
I have 4 nodes:
- 2 with class=public with a meta= service=API
- 2 with class=data

I can schedule jobs on the nodes with the class data.

When I want to schedule a job with a constraint of class=public and node.meta.service=API, nomad can't schedule it on those nodes.
But I can schedule on those when I only put a constraint of class=public.

The problem seems related to the meta constraint.

### Reproduction steps
nomad plan  nomad.hcl
or
nomad run  nomad.hcl

### Nomad Server logs
Nothing Particular

### Nomad plan output

```
- WARNING: Failed to place all allocations.
  Task Group "API_JOB" (failed to place 1 allocation):
    * Class "public" filtered 2 nodes
    * Class "data" filtered 2 nodes
    * Constraint "${node.meta.service} = API" filtered 2 nodes
    * Constraint "${node.class} = public" filtered 2 nodes
```

### Nomad run output

```
==> Monitoring evaluation "0656edad"
    Evaluation triggered by job "API_JOB"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "0656edad" finished with status "complete" but failed to place all allocations:
    Task Group "API_JOB" (failed to place 1 allocation):
      * Class "data" filtered 2 nodes
      * Class "public" filtered 2 nodes
      * Constraint "${node.class} = public" filtered 2 nodes
      * Constraint "${node.meta.service} = API" filtered 2 nodes
    Evaluation "381bb956" waiting for additional capacity to place remainder
```

### Nomad Client logs
Nothing particular

### Job file

```        constraint {
            attribute = "${node.class}"
            operator  = "="
            value     = "public"
        }

        constraint {
            attribute = "${node.meta.service}"
            operator  = "="
            value     = "EPT"
        }
```

**Comment by akaspin** [comment]
Falled in same issue just today. Docks on site is weird. Squash `node` from interpolations.

```
${node.meta.service} -> ${meta.service}
```

**Comment by dadgar** [comment]
@tviaud As @akaspin mentioned the docs are wrong. We will push a change to the website to fix! Sorry about that!

**Comment by dadgar** [comment]
@tviaud Website updated with fix!
