### ISSUE TITLE
Nomad fs and related doesn't work with NATed client nodes.

### ISSUE THREAD

**Issue by ninoles** [hashicorp/nomad#2145]
### Nomad version
Nomad v0.5.1

### Operating system and Environment details
Windows 10 Pro (but unrelated)

### Issue
Accessing nomad through an NATed address (like in the AWS environment) used the WAN address of the node.

### Reproduction steps
Start a node in AWS and exposed the public address to your local node. Now, try to fs an allocation

```
$ bin/nomad fs -address http://52.23.211.160:4646 -f d4ac3fb9-05f1-b1eb-183b-a7a1fe97ae1f alloc/logs/update.stdout .0
Get http://10.0.2.82:4646/v1/client/fs/stat/d4ac3fb9-05f1-b1eb-183b-a7a1fe97ae1f?path=alloc%2Flogs%2Fupdate.stdout.0: dial tcp 10.0.2.82:4646: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

```

**Comment by ninoles** [comment]
I'm not sure how this should work, since the wan address is usually configured through consul (in the case of AWS it is available however through a node attribute, but I think that's too specific as a solution).

May be a special "used consul translated addressed" option could be used ?

**Comment by diptanu** [comment]
@ninoles I guess you want Nomad CLI to use the public or EIP of nodes? If so please use the advertise address client option to specify the public IP when configuring Nomad client. That should make the CLI use the EIP instead of the private IP.

**Comment by ninoles** [comment]
The tricky part here, is that doing so will make the other node start using the external network for accessing each other (with charged bandwidth, etc.).  At least, that's how I understand this is working.

Right now, since there is no way in nomad to advertise wan address in additional to internal address, I think the best way to achieve what I need is through a bastion host.  In any way, it's probably also more secure this way.

**Comment by ketzacoatl** [comment]
One possibility: if the client can communicate with the nomad servers, have the servers relay log/fs information from the target remote agent.

**Comment by sheerun** [comment]
Related: #1640
