### ISSUE TITLE
Feature request: allow enabling TLS on a different port

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#2146]
When configuring Nomad to use TLS, Nomad CLI is unaware and fails when attempting to use the HTTP API: 

$ nomad status
Error querying jobs: Get http://127.0.0.1:4646/v1/jobs: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

In Consul, one can specify a different port for HTTPS while still allowing access over HTTP from 127.0.0.1. It would be more user friendly if Nomad could do the same.

**Comment by diptanu** [comment]
@c4milo What would be the point of having an HTTP Port when you have enabled TLS on another? As in how would you prevent users to not use TLS over plain http?

**Comment by c4milo** [comment]
I guess, the expectation was that since Nomad is running TLS, I was expecting Nomad CLI to be aware of it and just work, when it's run from a nomad server machine. In any case, it's not a big deal, I can add the extra flags each time.
