### ISSUE TITLE
[question] Periodic tasks

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/nomad#2148]
We have quite a few periodic jobs that seem better suited to be tasks and part of the same job.

I am curious if this has been brought up before? Would you consider making it possible to have periodic to be part of a task rather than a job?

Thanks!

**Comment by jippi** [comment]
I'm not from hashicorp, but due to the way job scheduling is done, mixing scheduling types will most likely be super hard. I've had the same need myself, and ended up having a config file, which generate multiple periodics jobs from a template.

**Comment by pgporada** [comment]
@jippi Can you post an example of what you just described please?

**Comment by dadgar** [comment]
@hoffoo As mentioned by @jippi the type of scheduler effects the whole job and can not be factored to individual groups/tasks. I believe @jippi is suggesting to template the job so that the commonality between them can be shared. This is my suggestion too if you need to run the tasks at different cadences.

Thanks,
Alex

**Comment by blalor** [comment]
I was hoping to implement a periodic task as a way to back up the data from another task in a group.  The intention being that they'd share an allocation directory and the backup task could work at the filesystem level.

**Comment by dadgar** [comment]
@blalor I would just wrap it in a script that acts like a cron

**Comment by nugend** [comment]
I'm actually really curious about why this would be a problem for the scheduler. An allocation would be placed and then nomad would just periodically run the driver, right?

Or does this have to do with how the code for handling periodicity is built such that it couldn't run on the client agents?
