### ISSUE TITLE
Users allowlist

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2158]
> nomad needs a user.whitelist. having to blacklist hundreds of user accounts to satisfy security reqs is a PITA.

 -- from: https://twitter.com/iKryten/status/817129940005122048

Currently nomad allows denylisting running tasks as certain users (such as root). For locking down a system a allowlist is much more succinct and easier to implement correctly.

Nomad should have a user.allowlist setting to allow specifying exactly what users tasks can run as.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/24343
