### ISSUE TITLE
Enabling TLS on nomad removes 'http' tag from consul and does not create 'https' tag.

### ISSUE THREAD

**Issue by xytis** [hashicorp/nomad#2167]
### Nomad version
`Nomad v0.5.2`

### Issue
https://github.com/hashicorp/nomad/blob/0f1e5cbea2024b0087cff8da824037ca519a827c/command/agent/agent.go#L466

Once TLS config is enabled, nomad no longer advertises `http` service to consul.
It is reasonable to expect that nomad would advertise `https` tag instead?

### Reproduction steps
Enable TLS config for nomad

**Comment by dadgar** [comment]
Duplicate of https://github.com/hashicorp/nomad/issues/2167

**Comment by xytis** [comment]
Duplicate of self???

**Comment by dadgar** [comment]
Haha good catch! Copy paste error: https://github.com/hashicorp/nomad/issues/2144
