### ISSUE TITLE
Nomad does not respect rolling update stagger when there are placement failures

### ISSUE THREAD

**Issue by drscre** [hashicorp/nomad#2170]
Nomad v0.5.1

I have a job with a single task group with a single task (a docker container). 
I use rolling update strategy with 30s stagger and 1 max parallel:
```
job "service" {
  update {
    stagger      = "30s"
    max_parallel = 1
  }
  group "service" {
    count = 10
    task "service" {
      driver = "docker"
      config {
        image = "nginx:1.10"
    }
  }
}
```

I try to deploy this job with 10 copies of task group, but only 5 copies fits into the node due to lack of memory.
Nomad deploys 5 copies, queues another 5 and reports placement failure for a job.

Then I update docker image version and try to redeploy the same job, but now with only 3 copies.
```
job "service" {
  ...
  group "service" {
    count = 3 // 3 copies should fit into the node
    task "service" {
     ...
      config {
        image = "nginx:1.11" // new image
    }
  }
}
```

I expected Nomad to stop 2 current jobs and do a rolling update of the other 3, but instead Nomad launches all three new copies at once.

**Comment by dadgar** [comment]
Hey this should be fixed since Nomad 0.6.X with the introduction of deployments.
