### ISSUE TITLE
Support AppRole for Vault Integration - Goal: Grouped Policies

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/nomad#2171]
Currently, Nomad 0.5.x supports Vault via injecting a specific token with a list of policies in the job file. It would be good to use AppRoles to group these common policies together under a specific name.

Essentially, this would mean supporting something like:

```hcl
job "docs" {
  group "example" {
    task "server" {
      vault {
        # Vault App Role Name
        app_role_name = "server_role"

        change_mode   = "signal"
        change_signal = "SIGUSR1"
      }
    }
  }
}
```

And having the Nomad Client authenticate the task using the app role.

Caveat:
- App Roles can be mounted under any arbitrary path.  Might need to add another option in the Nomad Config to specify the mount point?

**Comment by c4milo** [comment]
I would guess this issue also depends on https://github.com/hashicorp/consul-template/issues/744

**Comment by dadgar** [comment]
@c4milo Nomad's Vault integration is actually separate from consul-templates. We just hand CT a token but Nomad does all the heavy lifting of getting it.

**Comment by dadgar** [comment]
@justenwalker Talked to the Vault team a bit and they have some future work that should make default policies possible without AppRole. AppRole is another authentication backend which is less than ideal since Nomad already uses the token backend.

I am going to keep this open but slightly rename the title.

**Comment by chris93111** [comment]
+1 

with vault integration , nomad use auth/token/create , and with metrics of vault the number of customers is falsified

![image](https://user-images.githubusercontent.com/27526373/117484710-c239eb00-af67-11eb-827d-09c4a8393184.png)
![image](https://user-images.githubusercontent.com/27526373/117484771-d67de800-af67-11eb-823f-3f813de8c1a8.png)

**Comment by tgross** [comment]
I'm reviewing open Vault issues following the new Vault workload identity work (ref https://github.com/hashicorp/nomad/issues/15617). We've implemented something roughly similar to what's been proposed here, using signed workload identities to login to Vault and then use roles defined for the auth config. Going to close this issue to tidy up.
