### ISSUE TITLE
Don't require root for Docker

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2178]
As of #2132 root is required for all drivers to use the mount syscall.

Investigate removing that requirement. Hopefully it's as easy as not bothering to bind mount the alloc dir inside Docker task dirs.

**Comment by nugend** [comment]
Shouldn't raw_exec also be excluded from requiring mount privilege?

**Comment by schmichael** [comment]
@nugend You're correct! Fixed in this PR: #2216

**Comment by nugend** [comment]
*whew* thanks. Thought I was going to lose the ability to use Nomad! 😨
