### ISSUE TITLE
API to stop task on the specially node or specially allocID

### ISSUE THREAD

**Issue by xudawei** [hashicorp/nomad#2181]
Have one api for stop the task on specially node or specially alloc-id

In my sight，if i had run a job with service and count equal 3 ， some day i found one of the  task worked  not well . i hope to restart it or stop it , but i don't want to stop job  , because it would be have down time .  how can i kill the wrong task and restart it automaticlly . 

how can i do ?

**Comment by jippi** [comment]
This is not possible today. 

That kind of fine grained job control is planned, but AFAIK not in Q1 2017; hashicorp usually don't share their roadmap. 

What I do today is kill the docker instance or task on the server directly using `docker rm -f` / `docker stop` or simply `kill -9` the process (raw_exec & friends) - which will force nomad to restart the specific task.

**Comment by dadgar** [comment]
@xudawei There currently is not this ability but we would like to bring it. I am going to rename and tag as enhancement

**Comment by xudawei** [comment]
@jippi @dadgar  thank you for your replay .  i got it

**Comment by dradtke** [comment]
This type of thing would be nice for enabling restarts for reasons other than task failure. For example, I'm working on an application that's deployed as a single binary, and when a new version is released, it would be nice to copy the new binary to the server and tell Nomad to restart it, rather than manually `SIGHUP`'ing it.

**Comment by jpialirci** [comment]
Is there status or a timeline for this enhancement?  Thanks!

**Comment by tgross** [comment]
Implemented as `nomad alloc stop` and `nomad alloc restart`
