### ISSUE TITLE
[question] display temporary user and password in the secret directory

### ISSUE THREAD

**Issue by xudawei** [hashicorp/nomad#2182]
I had integrate vault with nomad . but i found it only display a vault token in secret directory.
how can i get temporary some secret info like temporary user and password in secret directory . 
**_Not just Token string_**
Otherwise ,  i need use vault library into source code . it not be commonly. 

Have some ideas ?

**Comment by kak-tus** [comment]
To read data from vault you can use or native consul-template or templating funcional builded into nomad, or vault have HTTP API to get data from it.
I prefer first and second variants.

**Comment by dadgar** [comment]
@xudawei As @kak-tus recommended, using the built in template block makes it very easy: https://www.nomadproject.io/docs/job-specification/template.html

**Comment by dadgar** [comment]
If that helps would you mind closing this issue?

**Comment by xudawei** [comment]
As i knew,  template blocks only support render file from consul . 
But if we used vault , info in the consul was encrypt. How can i use template to get un-encrypt string. 
Can you give me a example?

**Comment by xudawei** [comment]
@dadgar @kak-tus  Do you know what i want to have now?

**Comment by dadgar** [comment]
@xudawei Check out the different abilities of the template block here: https://github.com/hashicorp/consul-template#secret
