### ISSUE TITLE
[Enhancement] Add configuration option to prevent docker port publishing

### ISSUE THREAD

**Issue by etki** [hashicorp/nomad#2189]
### Nomad version
0.5.2

### Issue
Currently Nomad auto-publishes docker service ports, while they may be used for means other than public world interactions and that is not necessary what user wants. In my case, i was trying to build private infrastructure behind filtering reverse proxy, but Nomad forces to specify my docker service ports if i want to perform health checks, then it tries to publish them on private docker network i've spun Nomad on (and that fails).

### Job file
```
job "dadfa995-fb30-4c73-84fc-0e28eb426e31" {
    type = "service"
    group "default" {
        count = 2
        task "server" {
            driver = "docker"
            config {
                image = "nginx"
                port_map {
                    http = 80
                }
            }
            service {
                # I can't specify health check without a port
                port = "http"
                check {
                    type = "http"
                    path = "/v2/_health"
                    interval = "1s"
                    timeout = "2s"
                }
            }
            resources {
                network {
                    mbits = 10
                    # And if i specify port here, it is automatically published, which is not what i want:
                    # Error starting userland proxy: listen tcp 192.168.128.3:32192: bind: cannot assign requested address
                    port "http" {}
                }
            }
        }
    }
}
```

**Comment by diptanu** [comment]
@etki Not quite sure you are asking here. Do you want static ports from Nomad?

**Comment by etki** [comment]
@diptanu sorry for late response and incomprehensible question. There are some edge cases where you'd like to specify port for your docker task (e.g. for service discovery), but would not like nomad to take further actions and try to publish that port.
