### ISSUE TITLE
Provide telemetry about allocated / available resources

### ISSUE THREAD

**Issue by stew** [hashicorp/nomad#2191]
### Nomad version
0.5.2

I'm wanting to collect telemetry about how much of my cluster resources have already been allocated, and I don't see any current telemetry which allows me to figure out stuff like "how much memory does my cluster have unallocated" "how much cpu do I have unallocated" "what is the most amount of unallocated memory on any client currently", which is telemetry I feel like I need in order to know when I should be scaling my cluster up.

**Comment by OferE** [comment]
If i understand correctly, you can calculate it for CPU, Memory and disk space easily by using the following two:
https://www.nomadproject.io/docs/http/client-stats.html
https://www.nomadproject.io/docs/http/client-allocation-stats.html

**Comment by dadgar** [comment]
@stew Are you asking for each client to report its allocated and available resources? You could then aggregate for a cluster wide view

**Comment by stew** [comment]
@dadgar that would be ideal, yeah. Does it make sense?

**Comment by stew** [comment]
@OferE yeah, and you see exactly the stats I'm looking for when you look at the output of `nomad node-status $nodeid`. I just want them to go out through the statsd telemetry which is already wired into our monitoring systems.

**Comment by dadgar** [comment]
@stew Yep I was just clarifying to make sure we add the right thing

**Comment by dadgar** [comment]
@stew Do these stats not work for you: https://github.com/hashicorp/nomad/blob/master/client/client.go#L2147. They don't take into consideration reserved however

**Comment by multani** [comment]
Adding reserved stats would be cool yes!

**Comment by stew** [comment]
@dadgar yeah, I do have multiple ways of getting at that stat that work, I guess the reserved stuff is what I'm really after. I want to build stats to help me figure out when I'm close to expecting allocations to get blocked due to a lack of resources.

**Comment by burdandrei** [comment]
This is what I'm looking for to prevent cluster reservation saturation, maybe AutoScale cluster when less then threshold resources left

**Comment by burdandrei** [comment]
here is more telemetry per task https://github.com/hashicorp/nomad/pull/2330
