### ISSUE TITLE
artifact should be able to calculate disk space "free" inside the 'alloc' subdirectory

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2195]
I have a use case where a task downloads a large file (~1.5 GB) from a local HTTP server.
As multiple jobs could be running on the host, I let it be downloaded inside alloc, rather then an absolute path.

I faced an issue that the task would keep downloading until it could (around 1 GB) and then fail.

Would it be possible to add a disk free check to the artifact downloader before it actually proceeds with a complete download?

What I was thinking was:
* either let the download itself fail if it can successfully determine data size is going to exceed free space.
OR
* allow specifying "disk free required" for the artifact section.

### Nomad version
Output from `nomad version`
v0.5.2

### Operating system and Environment details
Linux: Debian 8

Regards,
Shantanu

**Comment by diptanu** [comment]
We implemented a disk checker in Nomad which killed an allocation the moment the disk space used by the allocation exceeded the allocated disk. But it turned out to be too expensive and so we removed it. We are going to introduce file system drivers and ZFS would be one such file system backend which will allow us to enforce disk quotas from the file system layer. So you won't be able to exceed the allocated disk.

**Comment by diptanu** [comment]
Closed this ticket since this is already on the roadmap. But feel free to ask any questions you might have.

**Comment by dadgar** [comment]
@shantanugadgil I think there is something else causing it to fail. We don't currently do disk enforcement. It is only used by the scheduler to do bin packing.

**Comment by shantanugadgil** [comment]
@dadgar  the machine did have only 1 GB disk space free, there is nothing wrong with Nomad in this case.

The "feature request" was that the disk check could happen before running completely out of disk space and _then_ failing.

@diptanu quotas is not something that I enforce on my servers, a simple is X GB free check would also do.

Thanks! 👍

**Comment by jippi** [comment]
If you just want your nomad client host to not run out of disk space, then https://www.nomadproject.io/docs/agent/configuration/client.html#reserved is maybe what you want?

**Comment by shantanugadgil** [comment]
thanks @jippi I missed the disk parameter in reserved. That will do for now. thanks again! 👍

**Comment by diptanu** [comment]
Well just using the disk quota won't help. Since you are downloading the file as an artifact, Nomad won't know how big the file is and hence things will always fail only when the disk doesn't have enough space.

**Comment by shantanugadgil** [comment]
Well, Nomad (actually http) could definitely know the "Content-Length" of what is was downloading. (of course, as long as the server supplied the information).
This would be of course an enhancement (I had completely missed the "disk" reservation, which I will use now)

In case a user has set the disk size, but the go-getter determines that what is actually going to be downloaded is more, then it could be possibly mark it as failure.

Thoughts?

**Comment by dadgar** [comment]
Yeah if set that could be used. You may want to file an issue with `go-getter` to report the content-length. it won't work for all downloadable sources though
