### ISSUE TITLE
[question] Any plans to support LXD (LXC v2.0+) ?

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2196]
Based on https://www.nomadproject.io/docs/drivers/lxc.html
I see that LXC is supported using templates only.

Are there any plans to add support for the new LXC v2.0 (LXD) method of creating containers?

### Nomad version
Output from `nomad version`
v0.5.2

### Operating system and Environment details
Ubuntu 16.04

Regards,
Shantanu

**Comment by diptanu** [comment]
yeah we will support that in the future.

**Comment by diptanu** [comment]
Some more clarification - We won't support the LXD daemon out of the box in Nomad, since external daemon based drivers have some shortcomings. We will allow users to specify a remote image, which Nomad will copy and use to create the container. This would require no additional templates.

**Comment by shantanugadgil** [comment]
I am not sure, I follow. :(
For LXD, the daemon running is necessary, otherwise a user would not be able to run the "lxc list" types of commands locally (on the node where the task gets assigned).

**Comment by diptanu** [comment]
@shantanugadgil So I am saying you won't need to use the LXD daemon at all. We will support most of the features that LXD supports without using the daemon including image management.

**Comment by shantanugadgil** [comment]
Hi,
Just wondering by when this is planned.

Thanks and Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil What feature are you looking for?

**Comment by shantanugadgil** [comment]
Hi @dadgar ,

Using LXD based workloads in place of dockerized workloads is basically what I am going for.
Typical workloads would be of type "service" and I would hope to register them in Consul similar to the "docker" driver of today.

My specific use is a mix of Consul+Nomad+gobetween (SNI capable proxy), probably better explained here:
https://github.com/yyyar/gobetween/issues/53

* of course, replace the "Docker" with "LXD" 😀 

https://cloud.githubusercontent.com/assets/2508915/24521691/a728e150-15aa-11e7-964b-ac02ecccdc7c.png
https://cloud.githubusercontent.com/assets/2508915/24521698/b6890080-15aa-11e7-9b50-bbd48102cad6.png

Thanks and Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil Unfortunately I do not believe we will be adding a LXD driver. I am a bit confused as to Diptanu's original response to you as well. In the future we would like to have a plugin interface for drivers which would allow the community to create an LXD driver. The reason I don't want to add the LXD driver is that it adds more for the team to support and there hasn't been much adoption of the LXC driver or very much interesting in even LXD in general.

**Comment by shantanugadgil** [comment]
Sorry to read that LXD (https://linuxcontainers.org/lxd/introduction/) won't be supported as a first class object like Docker, but I understand the team pressure part. 👍 

FWIW, there is an _awesome_ Terraform plugin coming along for LXD which I do use
https://github.com/sl1pm4t/terraform-provider-lxd

I guess I'll automate this some other way, thanks anyway!

Cheers,
Shantanu

**Comment by shantanugadgil** [comment]
Reviving an old request for LXD?!

**Comment by schmichael** [comment]
@shantanugadgil While we'd love to see a LXD driver plugin once Nomad 0.9 is released with driver plugin supported, we still have no plans to migrate our existing lxc driver to lxd.

Resources for creating driver plugins will be released with and after the 0.9 release.
