### ISSUE TITLE
keep service registered even after task completes

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2197]
I observed that the health check (and ultimately entire service) gets deregistered once the task (or all tasks) end.

Would it be possible to keep the service registration for some time (configurable) even after the task ends?

_Possibly using Consul's "deregister_critical_service_after" parameter?!?_

The use case is that a script, using a "raw_exec" task, is downloading a disk image and creating a VM.

I want to have the service (that created the vm using a script) stay "green" for some time after its completed successfully, so that that the next step of my deployment process can take over.

Of course, if the task "command" fails (exits non-zero) the service should become "failing" and then deregister after the stipulated time.

### Nomad version
Output from `nomad version`
v0.5.2

### Operating system and Environment details
Debian 8

**Comment by jippi** [comment]
sounds like something that should be handled out of the scope of nomad.. i would be extremely surprised if my service healths in consul did not reflect the absolutely up to date state of my nomad cluster. maybe you could use something out of band like a HTTP request or RabbitMQ message to signal something has completed and it's the next step in the process turn to take over.. maybe even using a consul lock which is released on completion ?

**Comment by diptanu** [comment]
This is something which will be tackled when we do DAGs or Chained Jobs in Nomad.
