### ISSUE TITLE
Configuration: Read Vault Token from a path in the filesystem

### ISSUE THREAD

**Issue by jen20** [hashicorp/nomad#2201]
It would be useful if the [`vault` stanza][vaultstanza] in the Nomad configuration allowed specification of a filesystem path to read a Vault token from. This would allow integration with the Vault Secure Introduction client without having to propagate the value from the file system to the environment.

For example (assuming here the system is configured with the Vault CA as a system root certificate):

```
vault {
    address = "https://vault.service.consul:8200"
    allow_unauthenticated = false
    enabled = true
    token_path = "/secrets/nomad-vault-token"
}
```

```
$ cat /secrets/nomad-vault-token      # obviously this isn't a real token...
ad791be6-dc08-11e6-a85d-0b70500659dd
```

[vaultstanza]: https://www.nomadproject.io/docs/agent/configuration/vault.html

**Comment by rwiggins** [comment]
This would compose well with the new Vault Agent.

**Comment by nathanhruby** [comment]
In case it helps future travelers, [this stack exchange article](https://unix.stackexchange.com/questions/511797/creating-os-environment-variables-using-execstartpre-on-systemd) lists a way to hack this into a systemd EnvironmentFile, which you can use to copy the agent token into the EnvironemtFile right before run.  (Obviously is you have a token added by config management or whatever, just dump it straight into an EnvironmentFile and call it done)

Other options here for vault-agent support:
- make `token` optional, and allow use of [cache+auto-auth token]( https://www.vaultproject.io/docs/agent/caching#using-auto-auth-token)
- help out hashicorp/consul-template#1222

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Vault tokens in the Nomad agent configuration. Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. Using Vault tokens in the Nomad configuration will be removed entirely in Nomad 1.9.
