### ISSUE TITLE
IAM roles for services

### ISSUE THREAD

**Issue by rokka-n** [hashicorp/nomad#2210]
Could somebody help understand if nomad integrates with amazon's IAM service? Maybe using Vault? 

I'd like to have IAM roles assigned to services its launches, kinda the same way ec2 can assign instance profiles.

**Comment by rokka-n** [comment]
I guess RTFM 
https://www.vaultproject.io/docs/secrets/aws

:)

**Comment by dadgar** [comment]
@rokka-n  Did you answer your own question? If so can we close this?

**Comment by djenriquez** [comment]
@dadgar apologies for bringing back an old issue, but I could have sworn this was a pattern supported by Nomad and Vault. However, now that we're looking at implementing this, I don't see an automated integration between Vault's AWS Secrets engine and Nomad.

The goal is as the OP, for Nomad to provide AWS credentials to tasks as they spin up based on a policy defined in Vault.

I was thinking Nomad Job submission --> Vault AWS Secrets Engine --> AWS Keys generated --> Vault returns keys to Nomad --> Nomad supplies credentials to allocations. I swear this was well supported at some time, was I mistaken?

**Comment by salarali** [comment]
I have the same problem. Is there a more automated way for aws secrets engine to interact with nomad jobs?

Each job requires a different IAM role, because they need access to different s3 buckets. Any ideas on how do I support that? The only way I can see right now is just to give the nomad clients access to all those buckets, but that isnt secure at all.

**Comment by tgross** [comment]
@salarali you can put `AWS_*` credentials in Vault (or in a near-future version of Nomad you'll be able to use native Secure Variables https://github.com/hashicorp/nomad/issues/12802). But this is a long-closed issue, so if you'd like to discuss this problem in more detail, I'm going to recommend that you either open a new issue or open a discussion on [Discuss](https://discuss.hashicorp.com/c/nomad/28). Thanks!
