### ISSUE TITLE
Consul ACL Token

### ISSUE THREAD

**Issue by cyrilgdn** [hashicorp/nomad#2214]
Reference: https://groups.google.com/forum/#!topic/nomad-tool/UFDam9U3hrU

Nomad should provide a way to pass a Consul token for services registrations and templates. 

As our Consul KV store is protected with ACL, we currently cannot use template stenza.
(even if it's a very cool feature !)

**Comment by pgporada** [comment]
Same here, our consul is protected by ACLs.

**Comment by shilov** [comment]
+1 seems fairly obvious that there'd be a way to set ACLs, surprised to find it's not the case.

For what it's worth, terraform also lacks support for interacting with Consul ACLs.
Makes me wonder if it was left out on purpose, possibly due to the frequency of changes made to Consul ACLs in recent releases.

**Comment by pznamensky** [comment]
Would be very useful for us too.

**Comment by robloxrob** [comment]
I would like to see this as well. It would help people to default to using a more secure Hashistack environment. We should definitely encourage the use of TLS auth and ACLs to drive using the products with a focus on security.

**Comment by DBuret** [comment]
Same here: consul, nomad, but no vault. how to read consul ACL protected K/V store from nomad jobs in the template stanza?

**Comment by chengchen** [comment]
Any news regarding this issue after several years?
It's just a shame that without this feature we can not achieve a self-contained runtime with the combination of Consul and Nomad (which come from the same company).

**Comment by tgross** [comment]
Nomad supports passing a Consul ACL token which is used for both service registration and template render. (I'm not sure when this was introduced... maybe after this long-open issue was opened?) This token currently needs to be hard-coded in the [`consul.token`](https://www.nomadproject.io/docs/configuration/consul#token) configuration. I've opened https://github.com/hashicorp/nomad/issues/9607 for making this something we could fetch automatically from Vault and renew.
