### ISSUE TITLE
iops exhausted

### ISSUE THREAD

**Issue by vladislav-jomedia** [hashicorp/nomad#2220]
### Nomad version
Nomad v0.5.2
### Operating system and Environment details
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

### Issue
Hello,
I am trying to create test environment with consul+vault+nomad in aws
I've started 4 consul + 4 nomad server + 1 worker nomad nodes
I am able to see client on servers , all services were registered in consul , so all looks good
with **nomad init** I've created a test job file 
when I'm  trying to test it 
```
nomad plan example.nomad
+ Job: "test"
+ Task Group: "cache" (1 create)
  + Task: "redis" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "cache" (failed to place 1 allocation):
    * Resources exhausted on 1 nodes
    * Class "worker" exhausted on 1 nodes
    * Dimension "iops exhausted" exhausted on 1 nodes
```

I think issue can be related to the wrong iops detection on ebs volumes,
 it is shown as negative number -303, in doc it should be range 0-1000
I've tried to change instance type with no luck

```
nomad node-status -self -stats
ID     = 1908825f
Name   = nomad-worker1
Class  = worker
DC     = us-east-1
Drain  = false
Status = ready
Uptime = 53m59s

Allocated Resources
CPU         Memory       Disk         IOPS
0/2200 MHz  0 B/3.4 GiB  0 B/4.7 GiB  0/-303

Allocation Resource Utilization
CPU         Memory
0/2200 MHz  0 B/3.4 GiB

Host Resource Utilization
CPU          Memory           Disk
49/2500 MHz  270 MiB/3.7 GiB  2.4 GiB/7.7 GiB

CPU Stats
CPU    = cpu0
User   = 0.00%
System = 0.00%
Idle   = 98.04%

Memory Stats
Total     = 3.7 GiB
Available = 3.4 GiB
Used      = 270 MiB
Free      = 2.3 GiB

Disk Stats
Device         = /dev/xvda1
MountPoint     = /
Size           = 7.7 GiB
Used           = 2.4 GiB
Available      = 5.0 GiB
Used Percent   = 30.57%
Inodes Percent = 19.31%

Device         = /dev/xvdb
MountPoint     = /mnt
Size           = 3.9 GiB
Used           = 8.1 MiB
Available      = 3.7 GiB
Used Percent   = 0.20%
Inodes Percent = 0.00%
```

### Nomad Server logs (if appropriate)
    2017/01/20 16:32:07.267191 [DEBUG] http: Request /v1/job/test/plan?region=global (2.512711ms)

**Comment by vladislav-jomedia** [comment]
@dadgar may be you can help me with that?
Tx

**Comment by philippeg-playster** [comment]
I'm having a similar issue.

**Comment by dadgar** [comment]
@vladislav-jomedia @philippeg-playster Are you all reserving IOPS? If so can you remove that and try again. We currently do not use the IOPS so I would suggest you don't set it in task resources or the reserved section in nodes.

**Comment by dadgar** [comment]
@vladislav-jomedia Also you should always have odd number of servers. The even server doesn't give you any more fault tolerance. Quorum system can handle (n-1)/2 server failures. So for n=3, that is 1, and for n=4 that is 1 as well, n=5 is 2.

**Comment by vladislav-jomedia** [comment]
Tx for reply, 
I am using the default job created by init , so there is no iops in the config 
In my testing env I've build 1 server and 2 node cluster

**Comment by dadgar** [comment]
@vladislav-jomedia Can you share the client configs?

**Comment by vladislav-jomedia** [comment]
it is working , 
looks like my salt states for config generation were not working well
after I fixed them iops issue went away :) 
Tx for your help

**Comment by dadgar** [comment]
Cool! Closing issue then 👍
