### ISSUE TITLE
[Improvement] Configurable working directory for exec/raw_exec

### ISSUE THREAD

**Issue by dradtke** [hashicorp/nomad#2224]
The `exec` and `raw_exec` drivers should be able to configure the working directory just like the `docker` driver can.

**Comment by dradtke** [comment]
I actually just realized that there may be some security implications with this change, but it could be minimized by disallowing traversal outside of the specified directory. It also wouldn't play the best with the [environment](https://www.nomadproject.io/docs/runtime/environment.html) that's set up for a task, but that may or may not be very important.

**Comment by Ashald** [comment]
IIUC, isn't it's something that can be achieved as

```
config {
        command = "/bin/bash"
        args    = [
                "-c",
                "cd /my/work/dir && exec $@",
                "my-executable"
        ]
      }
```
?

**Comment by kaskavalci** [comment]
This worked for me:

```
"Config": {
    "args": [
        "-c",
        "cd /my/work/dir && my-executable arg1 arg2 ..."
    ],
    "command": "/bin/sh"
}
```

**Comment by srene2795** [comment]
How do we propagate kill signal to the application  when we execute binary like this ?

"Config": {
    "args": [
        "-c",
        "cd /my/work/dir && my-executable arg1 arg2 ..."
    ],
    "command": "/bin/sh"
}

**Comment by dradtke** [comment]
I think you can do that by prefixing your executable with `exec`, e.g.

```json
"Config": {
  "args": ["-c", "cd /my/work/dir && exec my-executable arg1 arg2 ..."],
  "command": "/bin/sh"
}
```

The idea is to have the shell process actually replace itself with your executable, rather than create a separate subprocess.

**Comment by nictan94** [comment]
Is this going to be enhanced in the future? Because certain legacy windows application requires to be run with executing directory = .exe directory

**Comment by pcbl** [comment]
Hi @tgross ,
Me again. :-) 
Out of curiosity, do you know if there are any plan regarding this possibility of setting the Working Directory of the raw_exec driver?

We have a case where we need to set(it is about a legacy application which demands to work on a specific dir)... So far we do alternatives libe `cd "path" && run` , but would be very nice if we would be abble to set it from the driver.

BR
Pedro

**Comment by tgross** [comment]
We don't have it on our "coming soon" roadmap. So beyond that I couldn't really say when to expect this sort of thing. We'd definitely be open to a PR for it though!

**Comment by pcbl** [comment]
All clear. thanks for the heads up!

**Comment by picatz** [comment]
Just ran into this problem today. Would love to have this feature.

**Comment by geniousphp** [comment]
I have the same issue when running a nodejs app, it would be great to have a working directory setting

**Comment by tgross** [comment]
Internal ref: https://hashicorp.atlassian.net/browse/NET-10162
