### ISSUE TITLE
[request] mark an artifact as "temporary"

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2225]
### Nomad version
Output from `nomad version`
v0.5.2

### Operating system and Environment details
Linux: Debian 8 (x86_64)

I am using the 'raw_exec' driver which downloads a large single file as an artifact before the task starts.
For now, I download it into the allocation directory itself.

Would it be possible to mark an artifact as temporary so that *nomad* deletes it if the task succeeds?
I think this could be useful (so that I don't have to write any code to delete the file myself).

* I have tried to search for such an option, but haven't found one.
I also think that nomad cleans up the allocation directory after some time, but I am not sure about that.
Even if it did, I was thinking more of immediate cleanup rather than later.

Thanks and Regards,
Shantanu

**Comment by jippi** [comment]
Nomad will GC the allocation directory within 4h after the task completes, you can also trigger this GC manually using the HTTP API.

**Comment by dadgar** [comment]
@shantanugadgil Nomad v0.5.3 is bring client side garbage collection where it will also detect if it is running out of disk space and delete older allocations.

I think that will solve the need for this. If that seems reasonable lets close this issue?

**Comment by shantanugadgil** [comment]
@jippi thanks!
I guess you mean: https://www.nomadproject.io/docs/http/system.html
(I was looking for per task GC, but I guess the new feature mentioned in 0.5.3 will help)

@dadgar Yes, that should do. Any idea when 0.5.3 is going to be released?

**Comment by shantanugadgil** [comment]
closing this as the expected feature would come in 0.5.3
