### ISSUE TITLE
missing memory usage 

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2240]
### Nomad version
Output from `nomad version`

### Issue

`nomad alloc-status -stats` for a running container show

```
Task Resources
CPU            Memory       Disk  IOPS  Addresses
2800/1500 MHz  0 B/768 MiB  0 B   0
```

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1 (2016-12-30)
```

Docker: `1.13.0-0~debian-jessie` (from their own repo)

`Nomad v0.5.2-rc1 ('6249ad0f71a3d36bf15a019fcde0ed074db5f701+CHANGES')`

Works fine on same nomad version with Docker 1.12.5 on Debian Wheezy (7.9) with kernel 4.7.6

**Comment by schmichael** [comment]
Works on Docker 1.13.0 + Ubuntu 16.04 (xenial), so it might be a very specific kernel+docker mismatch.

**Comment by jippi** [comment]
`docker stats` also returns no RAM usage ,so not nomad issue
