### ISSUE TITLE
[feature] Leader Allocation / Task

### ISSUE THREAD

**Issue by timperrett** [hashicorp/nomad#2241]
Ideally we would like to be able to say that within a task group that a given task is a leader task

Discussed with @dadgar and @diptanu offline.

**Comment by dadgar** [comment]
An example of this is a batch job that has a task group with the batch task and a side car for logging. The main task gets marked as the primary and when it exits the other task is killed.

**Comment by dadgar** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/2308
