### ISSUE TITLE
docs: use `.tfvars` extension in tutorials with -var-file

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#22430]
Here is `.hcl` type of file is used:
https://developer.hashicorp.com/nomad/tutorials/cluster-setup/cluster-setup-overview#explore-the-cloud-directories
![image](https://github.com/hashicorp/nomad/assets/139780495/b705add8-608c-46ae-a363-82d831ada3cd)

But here `.tfvars` file extension is used:
https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files
![image](https://github.com/hashicorp/nomad/assets/139780495/b56404a5-c637-45fd-b2a6-c686b34f3636)

From the documentation it is not clear the difference between two. If they are the same thing, please use one name for it.
Thank you.

**UPD**

What is the difference between `.tf` and `.tfvars` are they processed in the same way? When I should use one or the other extension?

**Comment by tgross** [comment]
@EugenKon as I'm sure you're aware, file extensions don't impact the behavior. We'll update the tutorial.

**Comment by EugenKon** [comment]
@tgross yes, for sure.

From the first sight they are a bit different. Just an example what makes confusion:
One file uses simple syntax:
`.hcl`
```
asdf = asdf
```

The other uses more complex syntax
`.tfvars`
```
variable "asdf" { 
  default = "asdf"
}
```
So this makes to think that they are processed in a different way.

And more. What is the difference between `.tf` and `.tfvars` are they processed in the same way? When I should use one or the other extension?

**Comment by EugenKon** [comment]
Found this answer for my second question: https://spacelift.io/blog/terraform-tfvars#terraformtfvars-vs-variabletf

**Comment by tgross** [comment]
Ok, great! Thanks!

**Comment by EugenKon** [comment]
@tgross But why you closed this ticket? You had said that you you will update the tutorial.

**Comment by tgross** [comment]
They're both HCL syntax and either extension is correct. Nothing to fix and you've figure out whatever your misreading was. At this point, spending time on this kind of misreading is not a good use of our time.
