### ISSUE TITLE
Emit download begin/finished state event for docker images 

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2246]
More than once a day I'm puzzled on why some allocations take forever to get out of "pending", and there is nothing in the state history of a task than "Received"

I'm *guessing* that its downloading a docker image, but no way to actually see what nomad is waiting on... amping on the detail level in the start phase would greatly improve confidence in nomad is working, and not just stuck doing something random

**Comment by schmichael** [comment]
There will be a "downloading" event emitted in nomad 0.5.3!

There's actually one emitted in 0.5.2, but a bug meant it wasn't visible until *after* the download finished.

Fixed in #2165 and originally added in #2054

**Comment by jippi** [comment]
Thats so baws!
