### ISSUE TITLE
Allow stopping a Job tree (Parent + Children)

### ISSUE THREAD

**Issue by kaiserpelagic** [hashicorp/nomad#2263]
### Nomad version
0.5.3-RC1

### Operating system and Environment details
debian

### Issue
I've got a periodic batch job that runs every 15 minutes and is failing to start. In this case it's because the docker image it's trying to pull has been deleted, but I think this will happen if any fatal error occurs during startup. I stopped the master job hoping it would stop all of the periodic instances that are trying and failing to start. It did stop the master job but the instances have persisted.

### Reproduction steps
Launch a periodic batch job that references a docker image that doesn't exists. Let a couple of periodic instances start (they should all fail) and then stop the master job. You'll notice that master job stops properly but the failing period instances persist.

**Comment by dadgar** [comment]
Hey this is by design right now. Children jobs are not touched when exiting the parent. The stop API should allow parameterization to stop the whole job tree however.

I am going to change the title to reflect this
