### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#227]
For production use, authentication so that we can restrict who has access to administrate the cluster is important.

It would be nice to also have some sort of authorization, for example:
- Users can only manage their own jobs.
- Users can only use x amount of resources in the cluster.
- etc

**Comment by dadgar** [comment]
This is something we will do, however are not focusing on currently.

**Comment by rvm2015** [comment]
An interim solution could be to give nomad cli and option to set simple auth, and then stick nginx or something in front of the endpoint doing ssl and authentication (like how private docker registry works).

**Comment by charliedrage** [comment]
@rvm2015 @dadgar 
Would the plan be perhaps to go the same route as Consul with it's encryption? https://www.consul.io/docs/agent/encryption.html

**Comment by davidpelaez** [comment]
@dadgar I understand this in the level of expressiveness suggested by @F21 is not a priority. How about encryption of gossip and raft traffic? I think that would be within the scope of a issue with this title but I want to confirm if it should have it's own issue.

**Comment by dadgar** [comment]
@davidpelaez: Yep that should be its own issue!

**Comment by mortaliorchard** [comment]
For companies which are trying to add authentication (or at least a system that would restrict using specific features), what would you recommend? Many thanks!

**Comment by dadgar** [comment]
@mortaliorchard without Nomad enforcing it you would essentially need the HTTP API to be behind a proxy that enforces your ACLs.

**Comment by mortaliorchard** [comment]
Thanks @dadgar.

**Comment by sheerun** [comment]
@dadgar Ideally nomad would use the same simple authorization scheme as docker or kubernetes - being able to provide single token that is used to deterministically generate both https certificates, key encrypting gossip traffic, and is used for authentication. Currently setting up secure nomad is a chore..

**Comment by rokka-n** [comment]
I like it as well: having token-based auth for the client would make jobs scheduling and cluster management a breeze.

**Comment by k1ng87** [comment]
how has this not been prioritized yet??? Need auth for prod....

**Comment by pznamensky** [comment]
This is the critical issue for me.
Yes, I can tell nomad to bind on 127.0.0.1 and setup a proxy in front of nomad. But solution with HTTP basic auth breaks several commands: https://github.com/hashicorp/nomad/issues/2773
Besides, this doesn't let to start at least docker with `--net=host`, because nomad's API would be reachable inside docker at localhost.

**Comment by dadgar** [comment]
This will be a focus of Nomad 0.7.0!

**Comment by hauleth** [comment]
@dadgar I have found small project [Open Policy Agent](https://github.com/open-policy-agent/opa) which seems like nice idea to manage policies in Nomad. I am not saying that this should be project integrated into Nomad/Hashistack (however that also wouldn't be bad idea), but some ideas are nice.

**Comment by dadgar** [comment]
Hey all! This has landed in Nomad 0.7! https://www.nomadproject.io/guides/acl.html
