### ISSUE TITLE
rkt port mappings broken

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2272]
### Nomad version

0.5.4

### Operating system and Environment details

rkt 1.19.0

### Issue

Nomad generates an invalid port option for rkt.

### Reproduction steps

Run the rkt job below.

### Nomad Client logs (if appropriate)

stderr:
```
run: error setting up stage0: port name "6379" could not be found in any apps
```

### Job file (if appropriate)

```hcl
job "echo" {
  datacenters = ["dc1"]

  group "echo" {
    task "echo" {
      driver = "rkt"

      config {
        image = "docker://redis:3.2"
        port_map {
          db = 6379
        }
      }

      resources {
        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

**Comment by schmichael** [comment]
The issue is that the rkt `--port` command accepts `NAME:PORT` where `NAME` is defined in the image.

Docker images define `NAME`s for all `EXPOSE`d ports as `${PORT}-tcp` (or -udp).

ACI images define their own port `NAME`s

**Comment by schmichael** [comment]
Not a bug, just insufficient docs: https://www.nomadproject.io/docs/drivers/rkt.html#port_map

The port map needs to be:

```hcl
port_map {
    db = "6379-tcp"
}
```

**Comment by holtwilkins** [comment]
Hey @schmichael , I'm on `rkt` version `1.25.0`, and nomad `0.5.5`.  I'm still getting a similar error trying to use a docker image.

`run: error setting up stage0: port name "8000-tcp" could not be found in any apps`.

This job has been working as a docker job, and to convert it, I changed the string from

`image = "https://<Our docker host>/path/to/image:release"` to `image = "docker://<Our docker host>/path/to/image:release"`, and changed `http = 8000` to `http = "8000-tcp"`, and I'm still getting that same behaviour.  Anything change that you know of or do you know how I could troubleshoot this further?

**Comment by schmichael** [comment]
@holtwilkins Does the Dockerfile used to build the image `EXPOSE`s port 8000?

**Comment by schmichael** [comment]
@holtwilkins Verified that this job file properly maps port 6379:

```hcl
job "rktredis" {
  datacenters = ["dc1"]
  group "rktredis" {
    task "rktredis" {
      driver = "rkt"
      config {
        image = "docker://redis:3.2"
        port_map {
          db = "6379-tcp"
        }
      }

      resources {
        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

**Comment by holtwilkins** [comment]
Ah no it didn't.  I explicitly `EXPOSE`d the port, and now it starts fine, thanks @schmichael .  The app doesn't work for some reason, but to figure this out I'll need to go diving through the rkt logs I'm sure.

**Comment by schmichael** [comment]
Glad to help! That bit gets me every time, so I should probably make the
docs even more explicit!

If you switch on DEBUG logging we log the actual rkt command used to start
your app. Very handy to copy & paste out and do some testing on your own.
Although be warned it's a huge command as we setup a lot of envvars.
