### ISSUE TITLE
[feature] Make locale a parameter for periodic stanzas

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#2276]
For applications with global business requirements, some tasks need to be executed shortly after a time passes in a foreign time zone. Time zone offsets for geographical locations change throughout the year, of course, so the correct way to specify these is with locale strings. (I *think* Go supports these with it's native time library?)

Currently, you can work around this by using a wrapper script that sleeps until the correct time and firing hourly or minutely, but it would be very nice to just be able to set it as a parameter.

**Comment by tmichaud314** [comment]
Would it be possible to get this feature before the next DST change in March?
