### ISSUE TITLE
use net.ipv4.ip_local_port_range sysctl for port range selection

### ISSUE THREAD

**Issue by nathwill** [hashicorp/nomad#228]
if available (i.e. "on linux"), it might be nice to follow the `net.ipv4.ip_local_port_range` [sysctl](http://en.tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap6sec70.html) tuning instead of using hard-coded min and max port ranges; it's a good way to set up a contract with the user about keeping that range free of bindings from other non-nomad-managed services that might be installed, and makes for a nice tuneable on high-density machines. 

for background, we have some high-density, high-churn docker-based infra that exposes ~20 ports per container. it hasn't been a problem yet, but as an admin, knowing that docker follows that sysctl when doing port allocations makes it easy to know what our max density on a pure port-availability measure is, and skew it if we need to. it'd be nice if nomad exposed this as a tuneable (directly or by following the sysctl) as well.

**Comment by cbednarski** [comment]
> it's a good way to set up a contract with the user about keeping that range free of bindings from other non-nomad-managed services that might be installed, and makes for a nice tuneable on high-density machines.

We can add configuration for you to specify reserved resources when you setup the agent. For instance, you could block out ports 11500-11600 and reserve 1gb ram for other processes. I think we can also add configuration to specify the port range.

However, in order to make scheduling decisions, perform bin packing, and provide QOS, Nomad assumes it owns the resources on each node in the cluster. If you are running other dynamic workloads on the same nodes as your Nomad client agents you're likely to run into conflicts.

**Comment by nathwill** [comment]
>We can add configuration for you to specify reserved resources when you setup the agent. For instance, you could block out ports 11500-11600 and reserve 1gb ram for other processes. I think we can also add configuration to specify the port range.

if nomad's using the provided system behavior for port range selection, it wouldn't need to write in its own reserved port handling, because the administrator could just use `net.ipv4.ip_local_reserved_ports`.

> However, in order to make scheduling decisions, perform bin packing, and provide QOS, Nomad assumes it owns the resources on each node in the cluster. If you are running other dynamic workloads on the same nodes as your Nomad client agents you're likely to run into conflicts.

i agree. the main point in mentioning the sysctl's was to bring up that "hey, there's a standard way of setting the port range for dynamic port allocations, it might make sense to use it (like docker does)", the rest of my comment was just trying to explain why it had been useful for me to have that clarity and tuneability for our use-case.

i don't know how that all plays into having to support nomad working x-platform, so if you don't think it makes sense in light of nomad's goals, feel free to close this out, it's not a big deal at all, just wanted to see if it had already been considered and discarded for some reason :).

**Comment by cbednarski** [comment]
> if nomad's using the provided system behavior for port range selection, it wouldn't need to write in its own reserved port handling, because the administrator could just use net.ipv4.ip_local_reserved_ports.

Ah, I see. This makes sense! Thanks for clarifying. As you mentioned, using a Nomad-centric config makes it easier for us to support and document behavior on multiple operating systems so for now this is hard-coded and we have not  explored platform-specific ways to configure it. We're certainly open to improving this and I would be happy to review a PR for this feature.

**Comment by dadgar** [comment]
Closing as we do port reservation for binding not making outbound connections. For outbound it isn't an issue as a free port will be chosen and the ports value does not matter
