### ISSUE TITLE
Parameterized job not parameterized

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#2285]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad 0.5.4

### Operating system and Environment details
Ubuntu 16.10
Docker 13

### Issue

Just upgraded to Nomad 0.5.4 and I'm trying to schedule a parameterized job that should run a docker container with an entrypoint.

I set the paramtereized stanza as such:

```
 "Type": "batch",
...
 "ParameterizedJob": {
      "Payload": "forbidden",
      "MetaRequired": [
        "action", "service", "scope"
      ],
      "MetaOptional": []
   }

```

Nomad status:

> Type          = batch
> Priority      = 50
> Datacenters   = dc1
> Status        = running
> Periodic      = false
> Parameterized = false

And trying to dispatch:

> rpc error: rpc: can't find method Job.Dispatch

Is there some bits missing from the documentation i regards to parameterized jobs, or am I doing it wrong? 

### Reproduction steps
Create a json spec batch job:

Add following according to doc:
```
 "ParameterizedJob": {
      "Payload": "forbidden",
      "MetaRequired": [
        "action", "service", "scope"
      ],
      "MetaOptional": []
   }
```

This is not enough for the job to be parameterized it would seem.

### Job file (if appropriate)
```
{
  "job": {
    "Region": "global",
    "ID": "jobid",
     "Name": "jobname",
    "ParentID": "",
    "Type": "batch",
    "Priority": 50,
    "AllAtOnce": false,
    "Datacenters": [
      "pionen"
    ],
    "Constraints": [
      {
        "LTarget": "${node.class}",
        "RTarget": "prod",
        "Operand": "="
      }
    ],
    "Update": {
      "Stagger": 10000000000,
      "MaxParallel": 1
    },
    "TaskGroups": [
      {
        "Name": "prod",
        "Count": 1,
        "Constraints": null,
        "RestartPolicy": {
          "Attempts": 10,
          "Interval": 300000000000,
          "Delay": 25000000000,
          "Mode": "delay"
        },
        "EphemeralDisk": {
          "Sticky": false,
          "SizeMB": 300,
          "Migrate": false
        },
        "Meta": null,
        "Tasks": [
          {
            "Name": "taskName",
            "Driver": "docker",
            "User": "",
            "Config": {
              "image": "docker.domain.com/functionContainer:lastest",
              "network_mode": "host",
              "port_map": [],
              "dns_servers": [
                "10.75.17.183",
                "10.75.17.177"
              ],
              "dns_search_domains": [],
              "logging": [
                {
                  "config": [
                    {
                      "gelf-address": "udp://logging.domain.com:12203"
                    }
                  ],
                  "type": "gelf"
                }
              ],
              "args": [
                "--action=${NOMAD_META_action}",
                "--service=${NOMAD_META_service}",
                "--environment=${NOMAD_META_scope}"
              ]
            },
            "Env": {},
            "Vault": null,
            "Templates": null,
            "Constraints": null,
            "Resources": {
              "CPU": 500,
              "MemoryMB": 1024,
              "IOPS": 0,
              "Networks": [
                {
                  "MBits": 10,
                  "ReservedPorts": [],
                  "DynamicPorts": []
                }
              ]
            },
            "Services": [],
            "Meta": {
            },
            "KillTimeout": 5000000000,
            "LogConfig": {
              "MaxFiles": 5,
              "MaxFileSizeMB": 10
            },
            "Artifacts": []
          }
        ]
      }
    ],
        "ParameterizedJob": {
      "Payload": "forbidden",
      "MetaRequired": [
        "action", "service", "scope"
      ],
      "MetaOptional": [
       ]
    }
  }
}
```

**Comment by schmichael** [comment]
Are you sure you're running Nomad 0.5.4 on all clients and servers?

I'm testing with a similar job file and not seeing that error. I've also run your exact jobfile and it appears with `parameterized = true` in `nomad status` output.

One issue you'll run into is that we uppercase meta vars. So what you have *won't work:*

```json
              "args": [
                "--action=${NOMAD_META_action}",
                "--service=${NOMAD_META_service}",
                "--environment=${NOMAD_META_scope}"
              ]
```

Instead try:

```json
              "args": [
                "--action=${NOMAD_META_ACTION}",
                "--service=${NOMAD_META_SERVICE}",
                "--environment=${NOMAD_META_SCOPE}"
              ]
```

(We regret making meta vars behave that way and will probably support both cases in the future and eventually remove the uppercase form.)

**Comment by rickardrosen** [comment]
Yeah, you are right. For whatever reason one of the nomad server has not been updated.
I only looked at the agent version. My bad.
I'll upgrade the last node, and this will most likely sort things out.
Thanks

**Comment by rickardrosen** [comment]
@schmichael: When testing the job, have you noticed anything weird with meta inputs?

I post the following dispatch to the above job:

```
{
	"Meta": {
		"ACTION": "plan",
		"SERVICE": "s3-dev",
		"ENV": "prod"
	}
}
```

The args are then processed by a command line tool.

However, the variables become available seemingly random on different runs, i.e first run all three parameters are null (according to the bash script in the container), a subsequent run for example ${NOMAD_META_ACTION} is available, but non of the others.

I'm unable to see a pattern, but something is off, either with the parameterization or my job.
