### ISSUE TITLE
Binary not working on ARM

### ISSUE THREAD

**Issue by meyskens** [hashicorp/nomad#2291]
### Operating system and Environment details
Debian Jessie on a Scaleway C1 (armhf)
### Issue
Incompatible binary:
`/usr/local/bin/nomad: No such file or directory`
`/usr/local/bin/nomad: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=af3ac515eb17af858b6fc09ef125eae7241b2e22, not stripped`
### Reproduction steps
1) Download the zip from the site for ARM
2) unzip it
3) open it

**Comment by schmichael** [comment]
It seems we got bit by https://github.com/golang/go/issues/12443

Instead of continuing to fight CGO cross-compiling I'm building a new 32bit ARM binary on a Scaleway.

Sorry for the hassle, but you've prompted me to prepare better testing facilities for our ARM support so the situation should be better going forward.

**Comment by schmichael** [comment]
Fixed in #2297. 0.5.5 is coming out soon, so we're not going to re-post 0.5.4 binaries.

I've attached fixed arm builds from master and v0.5.4 if you don't want to wait for 0.5.5. Sorry for the hassle! I've started testing our ARM builds on Scaleway & Packet.net, so things should be more reliable in the future.
[linux_arm-v0.5.4.gz](https://github.com/hashicorp/nomad/files/767574/linux_arm-v0.5.4.gz)
[linux_arm-a16709ef.gz](https://github.com/hashicorp/nomad/files/767575/linux_arm-a16709ef.gz)

**Comment by bfritz** [comment]
@schmichael Thanks for the ARM TLC!

This change partially fixes the [issue I reported in gitter](https://gitter.im/hashicorp-nomad/Lobby?at=589779bf21d548df2ccc8c50).  No more segfaults with the Arch Linux ARMv7 [build](https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2) on a Raspberry Pi3.

I was hoping to kill [my branch](https://github.com/bfritz/nomad/tree/arch-linux-arm-cross-build) to compile ARM binaries on Arch.  Unfortunately, I'm toying with nomad on Pi Zeros and the binaries from your toolchain still segfault under Arch Linux [ARMv6](https://archlinuxarm.org/platforms/armv6/raspberry-pi) on the Pi Zero.

Not expecting you to make any changes.  Just throwing out a few more data points.  Thanks again!

**Comment by schmichael** [comment]
@bfritz Ah, interesting! I was just discussing with some ARM people at @packethost whether or not to support anything older than ARMv7 as it seems like that's what most distros are targeting now? Go 1.9 will drop support for pre-7 versions as well: https://beta.golang.org/doc/go1.8

I'm new to all the intricacies of the various ARM versions, but I don't see where your branch builds for ARMv6. I only see ARMv7 and aarch64 (ARMv8) toolchains mentioned.

If you tried building without `cgo` it'd be a lot easier to test ARMv5 and ARMv6 support as you wouldn't have to mess with the gcc toolchain at all: https://github.com/golang/go/wiki/GoArm Honestlly I'm not sure what breaks without cgo... The `raw_exec` driver might still work?

**Comment by bfritz** [comment]
@schmichael Yeah, I'm not explicitly targetting v6.  Just a happy coincidence it works.  Building 0.5.4 without cgo also worked on ARMv6.

Far as I know, ARMv6 is pretty rare these days.  I suspect the Raspberry Pi Zero is one few popular boards using it.  Probably not many other people running Nomad on the Pi Zero either.

@dadgar [said on gitter](https://gitter.im/hashicorp-nomad/Lobby?at=5897d407de504908228ef83f):
> user lookup uses cgo and we use that when the user is set and to determine the nobody user

Not sure if that matters for anything I'm doing, so just disabling cgo might be easiest for Pi Zero testing.

**Comment by bfritz** [comment]
Looks like Go 1.9 will still support ARMv6K and better, which includes the the Pi 1 and Pi Zero:

From https://beta.golang.org/doc/go1.8 :
> Go 1.9 will likely require the ARMv6K (as found in the Raspberry Pi 1) or later.

**Comment by sdeoras** [comment]
ARM v6 on Raspberry Pi Zero W: v1.1.0 builds fine for arm v6 by removing the `helper/pluginutils/catalog/register_nvidia_linux.go` and switching off `cgo`. I was able to deploy `raw_exec` workloads.
