### ISSUE TITLE
Build breaking on Linux

### ISSUE THREAD

**Issue by moderation** [hashicorp/nomad#231]
Build from source failing on Linux. Xubuntu 15.04

```
--> Installing build dependencies
--> Building nomad
# github.com/hashicorp/nomad/client/executor
client/executor/exec_linux.go:213: cannot use uint16(resources.IOPS) (type uint16) as type int64 in assignment
# github.com/hashicorp/scada-client
../scada-client/client.go:145: c.client.NumStreams undefined (type *yamux.Session has no field or method NumStreams)
Makefile:34: recipe for target 'test' failed
make: *** [test] Error 1
```

I'm wondering if this is due to the upstream runc change mentioned in https://github.com/hashicorp/nomad/issues/220

**Comment by rvm2015** [comment]
This is still happening with current master:

    $ make test
    --> Installing build dependencies
    --> Building nomad
    # github.com/hashicorp/nomad/client/executor
    client/executor/exec_linux.go:213: cannot use uint16(resources.IOPS) (type uint16) as type int64 in assignment
    make: *** [test] Error 1
    $ make bin
    ==> Getting dependencies...
    # github.com/hashicorp/nomad/client/executor
    client/executor/exec_linux.go:213: cannot use uint16(resources.IOPS) (type uint16) as type int64 in assignment
    make: *** [bin] Error 2
    $

**Comment by dadgar** [comment]
I think you are on an old version of lib container: https://github.com/opencontainers/runc/blob/master/libcontainer/configs/cgroup.go#L61

You can update your dependencies when working with Nomad with: `make updatedeps`

**Comment by rvm2015** [comment]
Looks like that was it, make updatedeps should be added to the README.md as it's not in there.
