### ISSUE TITLE
[question] custom delimeter support for templates

### ISSUE THREAD

**Issue by synthdnb** [hashicorp/nomad#2312]
Hi, I want to create alert templates for [promethus](https://prometheus.io/docs/alerting/rules/) 

But since both uses "{{" "}}" as delimiters, I cannot template this. 

Is there any way to pass options to change delimiters, or print delimiters?

**Comment by sethvargo** [comment]
CT supports this as an option to the template, so I think it's just a matter of adding the corresponding config in Nomad.
