### ISSUE TITLE
[Security] Consul token can be easily fetched by the unprivileged user 

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23167]
### Nomad version
Any

### Operating system and Environment details
The host on AWS Cluster

### Issue
![image](https://github.com/hashicorp/nomad/assets/139780495/77fd8ff6-5cf7-4b7f-9667-3a47d5aa8fca)
The fetched token could be used to create policies to allow `exec` for nomad user.

### Reproduction steps
Follow https://github.com/hashicorp/learn-nomad-cluster-setup/blob/main/shared/data-scripts/user-data-server.sh#L13

Create user on the EC2 instance
SSH into it
Run:
```
curl http://169.254.169.254/latest/user-data
```

#### Expected Result
The 'Consul token' should be visible once to the person who deployed the cluster.

#### Actual Result
The 'Consul token' is visible to any unprivileged user who can SSH into EC2 instance.

**Comment by tgross** [comment]
@EugenKon again, please open issues with that tutorial in that tutorial's repository and not here.
