### ISSUE TITLE
Can not send a configuration privately

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23168]
```
> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are
*not* publicly visible.
```

This is the error I have got:
![image](https://github.com/hashicorp/nomad/assets/139780495/b3b35176-bfb7-4c24-a3e2-f04f8abdf7f8)
https://github.com/hashicorp/nomad/issues/22444#issuecomment-2145579679

**Comment by tgross** [comment]
@EugenKon we already discussed this in the relevant issue. There's nothing I can do about this and in any case we would discuss that in the relevant issue.

**Comment by EugenKon** [comment]
@tgross 
I noticed this address in the template for the new issuer for this repository. If people can not send a configuration privately then this address should be removed from the template, should not?

**Comment by tgross** [comment]
> I noticed this address in the template for the new issuer for this repository. If people can not send a configuration privately then this address should be removed from the template, should not?

The address works just fine for other folks. I don't know what the issue is and I've already asked you to keep any discussion about this in the original issue.
