### ISSUE TITLE
job is still running when desire status is stop

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/nomad#2319]
Here is the nomad job with image version `0.0.1`. I update image version to `0.0.2` and run the job, a new allocation is created, but the status of old allocation is still in `running` - `stop`, which should be `complete` - `stop`. Both of the two services are available, but in different version.

The nomad version is v0.5.1.

![image](https://cloud.githubusercontent.com/assets/1549033/22960782/a854989a-f37b-11e6-9410-7df78dc30568.png)

Here is the job file.

```hcl
job "simple-server" {
  type = "service"
  datacenters = ["dc1"]
  update {
    stagger = "30s"
    max_parallel = 1
  }
  group "simple-server-group" {
    count = 1
    task "simple-server" {
      service {
        name = "simple-server"
        port = "http"
      }
      driver = "docker"
      config {
        image = "registry.example.com/simple-server:0.0.1"
        auth {
          username = "username"
          password = "password"
        }
        port_map = {
          http = 40000
        }
      }
      resources {
        cpu = 200
        memory = 100
        network {
          mbits = 1
          port "http" {
          }
        }
      }
    }
  }
}

```

**Comment by dadgar** [comment]
@waterdudu Hey unfortunately this is not enough information. Can you provide the client logs and the output of `nomad alloc-status 3d42d3b3`. Further this is not necessarily a bug. The task has a grace window to shutdown before it is forced killed.

**Comment by waterdudu** [comment]
Sorry for the late reply.
Unfortunately I stopped the job and ran with version 0.0.2. At this moment, the alloc cannot be found anymore, I should call `nomad alloc-status` to show more information about the job at that time but I didn't. I think that alloc has been removed by nomad. Is there anyway to find it?

**Comment by dadgar** [comment]
@waterdudu No there isn't. Lets close this and if it happens again we can reopen. If it happens again can you grab all the allocation information. Preferably using `nomad alloc-status -json <alloc-id>`
