### ISSUE TITLE
Multiple nomad cli commands fail if there are multiple prefix matches

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#23236]
### Nomad version
Nomad v1.7.8 (but 1.6.x had the same issues)

### Issue
Multiple commands in the CLI fail when there are multiple prefixes - so far I have seen this with :

- `nomad quota status`
- `nomad quota inspect`
- `nomad service info `
- `nomad volume deregister`

.... but I suspect that there may be others.

### Reproduction steps
Create a bunch of similarly named quotas / volumes / services and use the above mentioned commands.

#### Expected Result
The commands should work without giving a "Prefix matched multiple" error

#### Actual Result
The commands fail with a "Prefix matched multiple" error

**Comment by tgross** [comment]
@henrikjohansen can you clarify what you steps you're taking here? That is, suppose we have two quotas `example1` and `example2`. If you `nomad quota status example`, you _should_ get a "prefix matched multiple" error, because there's no way for Nomad to disambiguate these two.

**Comment by henrikjohansen** [comment]
@tgross ... an example with my v1.8.0 test cluster : 

```
$ nomad quota list
Name           Description
default-quota  Limit the shared default namespace
namespace      Limit the shared default namespace
namespace-1    Limit the shared default namespace
namespace-2    Limit the shared default namespace
```
Now, looking at the **namespace** quota fails with : 

```
$ nomad quota status namespace
Prefix matched multiple quotas

Name         Description
namespace    Limit the shared default namespace
namespace-1  Limit the shared default namespace
namespace-2  Limit the shared default namespace
```

**Comment by henrikjohansen** [comment]
As I mentioned other commands have similar issues : 

`nomad service info` seems to be just ... broken (it **always** gives me an error regardless of how specific I am) : 

```
$ nomad service list | grep liverpro 
liverpro-core             []
```
```
$ nomad service info liverpro-core   
Prefix matched multiple services

Service Name              Tags
[... REMOVED ...]
```

`nomad volume deregister` shows the same behavior as `nomad quota status/inspect` demonstrated above - if you have  `volume`, `volume-1` and `volume-2` it will fail on `volume` with "Prefix matched multiple" ...

**Comment by tgross** [comment]
Ok thanks @henrikjohansen. So the problem is when there _is_ an exact match in addition to the multiple prefix matches. That issue was previously reported with CSI volumes https://github.com/hashicorp/nomad/issues/17132, but it looks like it's pervasive.

**Comment by henrikjohansen** [comment]
I just stumbled across #13920 so it might as well be mentioned here.

**Comment by tgross** [comment]
PR in progress here: https://github.com/hashicorp/nomad/pull/23502
