### ISSUE TITLE
[Security] Web interface for Nomad server is publicly available if ACL for Nomad was enabled and there is no connection to Consul yet

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23240]
### Nomad version
v1.8.0

### Operating system and Environment details
uname -a
Linux ip-172-31-9-38 6.5.0-1020-aws #20~22.04.1-Ubuntu SMP Wed May  1 16:10:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Issue

![image](https://github.com/hashicorp/nomad/assets/139780495/97aba97e-31a5-4244-89c3-efb4dc1f455c)
![image](https://github.com/hashicorp/nomad/assets/139780495/0d9ce430-76b7-4083-958d-2223fee3ed12)

### Reproduction steps
Comment bootstrap procedure for Nomad
https://github.com/hashicorp/learn-nomad-cluster-setup/blob/main/shared/data-scripts/user-data-server.sh#L55-L77

#### Expected Result
When ACL is enabled, but bootsrap was not completed yet, the Nomad interface should not be publicly accessable.

#### Actual Result
The web interface for nomad publicly accessible despite on ACL was enabled.

**Comment by tgross** [comment]
@EugenKon the Nomad web UI is available (as in the "shell" of the web will be served), but none of the API endpoints work so there's no content. Consul isn't involved in any way with the Nomad ACL system or the UI, so I'm not sure what you mean by that here.

So addressing you question here:
> When ACL is enabled, but bootsrap was not completed yet, the Nomad interface should not be publicly accessable.

When the Nomad ACL bootstrap is not completed? I can't reproduce that.

**Comment by tgross** [comment]
Looks like this was resolved over in https://github.com/hashicorp/nomad/issues/23251. @EugenKon you've been filing a lot of issues related to cluster setup with that tutorial. I'm going to ask you to please take your issues with that setup to that repository going forward.
