### ISSUE TITLE
HTTP DELETE endpoint succeeds even if job does not exist

### ISSUE THREAD

**Issue by kspaans** [hashicorp/nomad#2326]
### Nomad version

`Nomad v0.4.1`

### Operating system and Environment details

Ubuntu Linux 4.4.0-59-generic running on AWS.

### Issue

Nomad does not check that a job exists before deleting it. The return value from the HTTP DELETE API endpoint is the same for removing jobs that don't exist and jobs that do.

### Reproduction steps

From a client machine in a Nomad cluster run `curl -v -X DELETE localhost:4646/v1/job/does-not-exist` to delete a job. Note that HTTP 200 is returned, even though `curl -v localhost:4646/v1/job/does-not-exist` returns HTTP 404.

**Comment by dadgar** [comment]
Hey I actually reverted the "fix". We are going to keep existing behavior of treating the deregister as idempotent. It gives a way to proverbially kick the scheduler incase it missed anything on the first deregister.
