### ISSUE TITLE
Requests to `/v1/jobs/statuses` with a high index sometimes hang for about 5 minutes

### ISSUE THREAD

**Issue by hashworks** [hashicorp/nomad#23296]
### Nomad version
1.8.0

### Operating system and Environment details
Debian 12, nomad installed from `apt.releases.hashicorp.com` repo.

### Issue

The UI uses the new `/v1/jobs/statuses` endpoint introduced in #20130. Requests with a high `index` GET parameter sometimes hang for about 5 minutes until they return a response. 

### Reproduction steps

The following request responds instantly:
```sh
$ curl -v 'http://<ip>:4646/v1/jobs/statuses?index=100' -H 'X-Nomad-Token: redacted' -o /tmp/index100
Trying <ip>:4646...
* Connected to <ip> (<ip>) port 4646
> GET /v1/jobs/statuses?index=100 HTTP/1.1
> Host: <ip>:4646
> User-Agent: curl/8.8.0
> Accept: */*
> X-Nomad-Token: redacted
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Nomad-Index: 1574676
< X-Nomad-Knownleader: true
< X-Nomad-Lastcontact: 0
< Date: Tue, 11 Jun 2024 09:34:11 GMT
< Transfer-Encoding: chunked
< 
{ [1014 bytes data]
100  4092    0  4092    0     0  71197      0 --:--:-- --:--:-- --:--:-- 71789
* Connection #0 to host <ip> left intact
```

Requests with a high `index` GET parameter often hang for about 5 minutes:
```sh
$ curl -v 'http://<ip>:4646/v1/jobs/statuses?index=1606601' -H 'X-Nomad-Token: redacted' -o /tmp/index1606601
Trying <ip>:4646...
* Connected to <ip> (<ip>) port 4646
> GET /v1/jobs/statuses?index=1606601 HTTP/1.1
> Host: <ip>:4646
> User-Agent: curl/8.8.0
> Accept: */*
> X-Nomad-Token: redacted
> 
* Request completely sent off
  0     0    0     0    0     0      0      0 --:--:--  0:05:14 --:--:--     0
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Nomad-Index: 1574676
< X-Nomad-Knownleader: true
< X-Nomad-Lastcontact: 0
< Date: Tue, 11 Jun 2024 09:38:48 GMT
< Transfer-Encoding: chunked
< 
{ [3470 bytes data]
100  4092    0  4092    0     0     12      0 --:--:--  0:05:14 --:--:--  1128
* Connection #0 to host <ip> left intact
```

As you can see the status code is still 200 OK. The JSON output is valid as well.

#### Expected Result

Requests to `/v1/jobs/statuses` don't hang, regardless to the value of the `index` GET parameter.

#### Actual Result

Some requests just hang in the UI, or run into a timeout if the client or proxy has a lower timeout. This may result in errors shown to the user.

### Nomad Server logs

No error is logged.

**Comment by hashworks** [comment]
Firefox can deal with this, but most reverse proxies won't:
![image](https://github.com/hashicorp/nomad/assets/2362091/301badca-0fad-4dc8-805c-f02ec19851e0)

**Comment by jrasell** [comment]
Hi @hashworks and thanks for raising this issue. The `index` query parameter is part of the Nomad API [blocking query functionality](https://developer.hashicorp.com/nomad/api-docs#blocking-queries).

> When this is provided, the HTTP request will "hang" until a change in the system occurs, or the maximum timeout is reached.

The Nomad UI uses this functionality to live update numerous pages once it has initially loaded the first set of data. If you're using a reverse proxy such as NGINX, you could set the `proxy_read_timeout` value to `310s` which would accommodate Nomad's default `300s` blocking query timeout.

I'll close this issue as it seems Nomad is behaving as expected and documented. Please feel free to reach out if you have any further questions, queries, or problems.

**Comment by hashworks** [comment]
While I find blocking APIs in HTTP a bit strange, but as long as it's working as intended...
