### ISSUE TITLE
[feature] Docker Credential Helper

### ISSUE THREAD

**Issue by bantonj** [hashicorp/nomad#2334]
It would be very useful if nomad supported [Docker Credential Helpers](https://github.com/docker/docker-credential-helpers). It would be especially helpful for Amazon's ECR which only supports logins that last for 12 hours. I made this same feature request to [go-dockerclient](https://github.com/fsouza/go-dockerclient/issues/627#issuecomment-280785399), and it doesn't sound like there is much interest in adding it there.

**Comment by dadgar** [comment]
Hey @bantonj,

How will this help your problem of having to refresh the credentials? This just seems to be a different credential store?

**Comment by bantonj** [comment]
@dadgar This would make the credential store refresh the credentials transparently, while right now I have to have a cron running in the background to keep refreshing the docker login.

**Comment by dadgar** [comment]
@bantonj Cool! Would you mind linking docs and/or examples of this being integrated in other projects?

**Comment by bantonj** [comment]
@dadgar I couldn't find anything in other projects, but [here](https://github.com/docker/docker/blob/8e5769445211f71635432dcdba17d31f2571e52a/cli/config/credentials/native_store.go#L23) is how the docker cli does it. And [here](https://docs.docker.com/engine/reference/commandline/login/#/credentials-store) are the Docker docs regarding credential store helpers.

**Comment by rawler** [comment]
I need this too. I will look into making a patch

**Comment by dadgar** [comment]
Fixed by #2651

**Comment by discobean** [comment]
Thanks @rawler this is a _big_ help and works great!
