### ISSUE TITLE
[improvement][doc] Should add note about docker image repository name

### ISSUE THREAD

**Issue by udomsak** [hashicorp/nomad#2335]
## Driver docker

for docker repository that not use default or private repo ( hub.docker.com ) they must include authentication otherwise  nomad can't start job because they can't find an image. and then report an error  
with 

`
API error (404): {"message":"repository myrepo/myimage not found: does not exist or no pull access"}
`

This can occur even if you have an image on local Nomad still can't find your image. ( not sure this is bug or not :) )

**Comment by dadgar** [comment]
@udomsak Hey thanks for using Nomad and sorry you ran into something confusing. Unfortunately I don't quite follow what you are asking to be improved. Could you maybe link to where was confusing in the docs?

**Comment by udomsak** [comment]
@dadgar  below is my suggestion (  i not well in English ), However  may be bug ?  

image - The Docker image to run. The image may include a tag or custom URL and should include https:// if required. By default it will be fetched from Docker Hub.   **You need to add  authentication if you not use Docker hub. Otherwise Nomad can't see your image**  < - This section my be need to add ( See [ Authentication](url) )  

**_NOTE  If you build image on local and they not store on any remote repository  ( Docker hub , etc. )  Nomad can't  see image._**  <- Add this too. 

 
config {
  image = "https://hub.docker.internal/redis:3.2"
}

or may be 

## FAQ. 

- When i use  docker driver and then run job i found an Error  ` API error (404): {"message":"repository myrepo/myimage not found: does not exist or no pull access"}` what happen ? 

Ans:   Add Authentication in Nomad job  if you not use Docker hub.

**Comment by dadgar** [comment]
Fixed by: 71462bf0b4e0303c48e4c9ff9c7b6a10117d6d33
