### ISSUE TITLE
UI block not working with nomad-pack

### ISSUE THREAD

**Issue by stBlackD** [hashicorp/nomad#23398]
### Nomad version
Nomad v1.8.1
BuildDate 2024-06-19T06:43:57Z
Revision 5022543e4b7b8dcec9df123f86630ae3fdcffbe6

### Issue
IU block is not displayed in the web interface if the job was deployed with nomad-pack
![изображение](https://github.com/hashicorp/nomad/assets/5266226/a285c5d7-e454-4dfa-b9db-ba3a35ac1141)

### Job file (if appropriate)
```
job "[[ var "job_prefix" . ]]-cron-[[ var "job" . ]]" {
	
	region      = [[ var "region" . | quote ]]
	datacenters = [[ var "datacenters" . | toStringList ]]
	[[- end ]]

	type = "batch"
	ui {
		description = [[ var "description" . | quote ]]
	}
	periodic {
	  crons            = [[ var "crontab" . | toStringList ]]
	  prohibit_overlap = true
	  time_zone        = "Europe/Moscow"
	}

	group{}
```

**Comment by tgross** [comment]
@stBlackD which version of Nomad Pack are you using? Only 0.1.2 will support the Nomad API update needed for the `ui` block.
