### ISSUE TITLE
Deprication for `cron` is not documented

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23391]
### Problem
![image](https://github.com/hashicorp/nomad/assets/139780495/92925f91-94ea-4431-a09c-3715bbf3af76)

But the documentation says nothing about this:
![image](https://github.com/hashicorp/nomad/assets/139780495/47b1ac48-4bd9-4cfe-bae9-0160c798aa12)

https://developer.hashicorp.com/nomad/docs/job-specification/periodic#periodic-parameters

**Comment by Antvirf** [comment]
Small fix https://github.com/hashicorp/nomad/pull/23424
