### ISSUE TITLE
Even type should not be 'Terminated' if a task successfully finished

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23403]
### Nomad version
```
Nomad v1.8.0
BuildDate 2024-05-28T17:38:17Z
Revision 28b82e4b2259fae5a62e2ed47395334bea5a24c4
```

### Issue
The successfully finished task shown as 'Terminated'.
![image](https://github.com/hashicorp/nomad/assets/139780495/25813c9b-65be-4dab-912f-64bc526b22e4)

### Reproduction steps
I created "periodic" task and "Force launch" it. It was completed successfully. exit status is 0.

#### Expected Result
The successfully completed task should have 'Finished' status.

#### Actual Result
At the moment it is displayed as 'Terminated'. It looks like the task was killed and not finished successfully.

#### Job file
```
job "reindex-database2" {
  region = "planitar"
  datacenters = ["plntr_dc"]
  type = "batch"

  periodic {
    enabled   = true
    crons     = [ "* * 2 * 1,4,7,11 6L *" ]
    time_zone = "America/Toronto"
    prohibit_overlap = true
  }

  group "db-backup2" {
    task "postgres-backup2" {
      driver = "raw_exec"

      config {
        command = "/bin/bash"
        args    = ["local/script.sh"]
      }

      template {
        destination = "local/script.sh"
        data        = <<-EOH
          set -ex

          echo "YES";
        EOH
      }

      template {
        env         = true
        destination = "secrets/file.env"
        data = <<-EOH
          NOMAD_TOKEN="{{key "nomad_user_token"}}"
        EOH
      }
    }
  }
}

```

**Comment by tgross** [comment]
"Terminated" is the name of the event type. The description tells you why the task was terminated (the workload exited 0). The allocation will be marked Complete, which is what you're looking for here.
