### ISSUE TITLE
UI: cannot close task sidebar if Job was deleted

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23410]
### Nomad version
```
v1.8.0
```

### Issue
![image](https://github.com/hashicorp/nomad/assets/139780495/d5ce54e1-68a0-4f95-9345-a5a00c9fc053)

### Reproduction steps
Open "View logs". Delete the job.

#### Expected Result
I should be able to close the window even if underlying task does not exists already.

#### Actual Result
I am not able to close the window.

**Comment by tgross** [comment]
Hi @EugenKon! I've flagged this for review by our front-end experts.
