### ISSUE TITLE
UI: allow creating global ACL tokens

### ISSUE THREAD

**Issue by Alexsandr-Random** [hashicorp/nomad#23429]
### Nomad version
Output from `nomad version`
Nomad v1.7.3
BuildDate 2024-01-15T16:55:40Z
Revision 60ee328f97d19d2d2d9761251b895b06d82eb1a1

### Operating system and Environment details
Ubuntu 22.04

### Issue
We recently established nomad federation cluster. (with replication and it works!) 
When i try to change client token from non-global to global (because some users should see other cluster) - i see following error:

``` bash
nomad acl token update -global=true -type=client fa6ebc10-a8dd-bfd6-1667-2837b415d631
Error updating token: Unexpected response code: 400 (token 0 invalid: 1 error occurred:
* cannot toggle global mode
```
#### Expected Result
I could switch client mode from non-global to global. 
Or at least **add option into UI (like checkbox) - should token be global or not.** Most tokens created via UI and it`s very inconvenient when you switched to federation recognize that now you could create some tokens only via nomad server cli interaction.   

#### Actual Result
Have not any UI option in FED mode about token global or not. 
Can't switch token type to global via cli - so need to recreate all tokens what should see two clusters.

**Comment by tgross** [comment]
Hi @Alexsandr-Random! The restriction on upgrading from local to global is a restriction of the data model. We replicate write global tokens to the authoritative region and then replicate them to the non-authoritative regions. So if we allowed upgrading the token from local to global, we'd have a token that already exists locally getting copied up to the authoritative region and then conflicting after replication.

However, providing the option in the UI makes plenty of sense! 'm going to re-title this issue and mark it as a UI enhancement for roadmapping.
