### ISSUE TITLE
Allow to download artifacts from the container

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23433]
### Proposal
There is a problem to fetch the template from the container we want to run: https://github.com/hashicorp/nomad/issues/23416#issuecomment-2187367176

### Use-cases
It would be nice to keep the template inside the container which we want to run. Thus, depending on the container we want to run it could be possible to store it own template.

```
      driver = "docker"

      config {
        force_pull = false
        image = "xxx/nginx"
        volumes = [
          "custom/internal.nginx.conf:/tmp/nginx/sites-enabled/site",
        ]
      }

        artifact {
          source      = "docker://some/path/inside/container/nginx.tpl"
          destination = "local/nginx.tpl"
        }

        template {
          source        = "local/nginx.tpl"
          destination   = "custom/internal.nginx.conf"
          change_mode   = "signal"
          change_signal = "SIGHUP"
       }
```

### Attempted Solutions
I was tried to create `pre-start` task which fetches the template and make it available via `/alloc`. But `/alloc` is not mounted into `/opt/nomad/data/<ID>/<task>/alloc` folder for tasks with `docker` driver.

**Comment by tgross** [comment]
@EugenKon the `artifact` and `template` blocks run outside of the task. They currently run in the client's context, but our long-term vision is to have them run as tasks themselves. We can't run things like `template` or `artifact` inside your tasks unless we mount `consul-template` binaries (or something like that) inside the task container. This wouldn't work for anything except Docker containers.

A different way to solve the problem that you've got in https://github.com/hashicorp/nomad/issues/23416#issuecomment-2187367176 is to run `consul-template` as PID1 inside your Nginx container. I'd recommend trying something like that.
