### ISSUE TITLE
Conditional JobSpec Variables for Task Based on Node Architecture

### ISSUE THREAD

**Issue by valafon** [hashicorp/nomad#23509]
We have the following problem - we need to deploy a job in an environment where nodes can be either amd64 or arm64. This isn't an issue when the jobspec doesn't vary by architecture, and the used image is multi-platform. However, as soon as the spec for the task level differs depending on which node Nomad places it on, problems arise.

Specifically, for example, I need to use the NVIDIA runtime on amd64 and runc on arm64. Additionally, I need to mount certain devices on amd64 and different ones on arm64. From what I have read in the documentation, this can be managed at the template level for setting different variables, but parameters like runtime, devices, and other such settings cannot be placed in if blocks depending on the architecture.

Does Nomad have any hidden undocumented features or any workarounds for this?

**Comment by pkazmierczak** [comment]
hi @valafon, I think perhaps you could solve this using [HCL2 expressions](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/expressions)? Although I'm not sure how to capture runtime...

Or could you perhaps use [node pools](https://developer.hashicorp.com/nomad/docs/concepts/node-pools) to segment your estate by CPU architecture, and have job specs target different node pools?

**Comment by valafon** [comment]
> hi @valafon, I think perhaps you could solve this using [HCL2 expressions](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/expressions)? Although I'm not sure how to capture runtime...
> 
> Or could you perhaps use [node pools](https://developer.hashicorp.com/nomad/docs/concepts/node-pools) to segment your estate by CPU architecture, and have job specs target different node pools?

The point is that we have a pool of nodes with amd64 architecture, and we need to add arm64 nodes to them so that the Nomad job can run on any machine in this mixed environment. We have done this before, and it works perfectly if the jobspec fits both architectures equally well, and Docker just pulls a multi-platform image that can run on both. However, we have a new case where some conditions in the jobspec change, specifically runtime = nvidia/runc and the devices block with mounting various files from the host. It seems that expressions are not suitable for solving this problem. Maybe someone in the community has solved this issue, or it would be great if such a feature appeared in future versions.

**Comment by tgross** [comment]
@valafon, the Nomad scheduler needs to know what the resource requirements for a job are (including the devices) before it can place the workload. If the device isn't already defined, the scheduler doesn't know which node has the device, so the scheduler can't place the workload on a node and there's no node architecture to try and interpolate (via either HCL2 or [attribute interpolation](https://developer.hashicorp.com/nomad/docs/runtime/interpolation)). It's a chicken-and-the-egg scenario.

What you might be able to do is to use HCL2 variables (as @pkazmierczak suggested) to effectively have two different versions of the job that get deployed to different nodes. HCL2 has fairly weak conditional support though, so a better workaround might be to use [Nomad Pack](https://github.com/hashicorp/nomad-pack).

**Comment by tgross** [comment]
I also wanted to leave a link to the [HCL2 Parsing Context](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2#hcl-parsing-context) documentation, which should help explain some of the workarounds I've explained above.

Seems like we can close this issue out.
