### ISSUE TITLE
Do not request consul task token when not needed.

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#23519]
### Proposal
Currently, when using workload identities. Every time there's a template a consul token is requested, even if the template doesn't use consul.

Maybe a value could be set on the consul block to set when a task token is needed.

**Comment by tgross** [comment]
Hi @jorgemarey! Yeah, we had to do this for backwards compatibility (because the `consul` block wasn't previously required). We've got https://github.com/hashicorp/nomad/issues/19390 open to cover this in detail, so I'm going to close this as a dupe.

**Comment by jorgemarey** [comment]
Hi @tgross. Sorry I didn't see that issue. Just want to note that maybe there's the case that the end user wants the task to have a consul token but doesn't specify a template.
