### ISSUE TITLE
Nomad Consul Legacy ACL Workflow Failing to Deregister Catalog Services on Job Updates

### ISSUE THREAD

**Issue by natemollica-nm** [hashicorp/nomad#23534]
### Consul Nomad Legacy ACL Workflow Service Deregistrations Failing

> Creating separate Issue for tracking and resolution from original issue #16616 for Nomad + Consul ACL legacy (non-WI) workflow.

_**Product Versioning**_

Consul: `v1.19.0`
Nomad: `v1.8.1`

**_Summary:_** Consul Catalog Service deregistrations fail upon Nomad Job updates despite the Nomad Agent's Consul ACL token being specified due to Consul defaulting to the `anonymous` token.

**_Workaround:_** Configure Consul client agent ACL stanza to include a token attached to a Consul ACL Token Policy that contains the rules below.

```hcl
agent_prefix "" {
  policy = "read"
}
node_prefix "" {
  policy = "read"
}
service_prefix "" {
  policy = "write"
}
key_prefix "" {
  policy = "read"
}
```

Consul Client Agent Configuration Example:

```hcl
      acl {
        enabled = true
        default_policy = "deny"
        down_policy = "extend-cache"
        tokens {
          initial_management = "<my_nomad_client_token_secretID>"
        }
      }
```

**Comment by tgross** [comment]
Internal ref https://hashicorp.atlassian.net/browse/NET-10360

**Comment by tgross** [comment]
As noted in https://github.com/hashicorp/nomad/pull/23800

> Since Consul 1.15 (https://github.com/hashicorp/consul/pull/16097) Consul client agent only uses the agent token to perform [anti-entropy](https://developer.hashicorp.com/consul/docs/architecture/anti-entropy) after you deregister a service via the Agent API. so the Consul client agent must have its own agent token.
