### ISSUE TITLE
UI - Cmd/Ctrl + Click won't correctly open new tabs

### ISSUE THREAD

**Issue by dkyanakiev** [hashicorp/nomad#23544]
### Nomad version
edc56664-71d2-7a63-9574-98f1608a9fdf

### Operating system and Environment details
Nomad v1.8.1
BuildDate 2024-06-19T06:43:57Z
Revision https://github.com/hashicorp/nomad/commit/5022543e4b7b8dcec9df123f86630ae3fdcffbe6

### Issue
In the new version when using the UI, cmd + mouseclick wont correctly open new tabs on the browser. 
It both opens the new tab but also changes your current one. This only happens when interacting with the jobs list, which is basically the updated page. Other tabs/menus don't have this problem

### Reproduction steps
Open the Jobs list on the UI and try to cmd+click any job. You would see both a new tab but also have your current one change

#### Expected Result
Open a new tab with the job selected

#### Actual Result

https://github.com/hashicorp/nomad/assets/31411471/0faf23b4-0734-4407-b79d-aa967c364a7d

**Comment by jrasell** [comment]
Hi @dkyanakiev and thanks for raising this issue with the video. I was able to reproduce this locally on main, therefore I will mark this for roadmapping and pass it over to our UI engineer, who will be best placed to assist.
