### ISSUE TITLE
Add variables text box on job submission page

### ISSUE THREAD

**Issue by sevensolutions** [hashicorp/nomad#23582]
### Proposal
Editing a job from the Web UI already shows a separate textbox to edit the variables. It's called "Edit HCL Variable Values".
It would be great if this textbox would also be shown when submitting a new job.

### Use-cases
- Using jobs with variables
  - Currently, submitting such a job will show an error, if variable values are missing
- Job templates may include variables 

### Attempted Solutions
See proposal.

**Comment by sevensolutions** [comment]
I can try to create a PR for that, i think it should be simple.

**Comment by sevensolutions** [comment]
Oh i think the change is even simpler than i thought...

<img width="1733" alt="image" src="https://github.com/user-attachments/assets/88c25bf9-0c44-43ea-a1e1-bc2d33d37453">

**Comment by jrasell** [comment]
Hi @sevensolutions and thanks for raising this issue and looking into the code implementation. I'll pass this over to our UI engineer, who will be best placed to understand and look into this with you.
