### ISSUE TITLE
How to know Server Fault Tolerance just like Consul web ui shows?

### ISSUE THREAD

**Issue by liukch** [hashicorp/nomad#23598]
### Nomad version
1.7.7

### Operating system and Environment details
```
$ sudo lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### Issue
I want to konw the number of `Server Fault Tolerance` in a Nomad cluster.

My Nomad cluster has three server agents, but there are two scenarios:
- It was originally a five-agent cluster, but now only three agents remain, with `Server Fault Tolerance`  is `0`, any server agent fault will make severe damage.
- It is a three-agent cluster by design, with `Server Fault Tolerance` is `1`, one server agent fault could be recovery automaticly.

The two scenarios represent significantly different levels of cluster health. Is there an intuitive way for me to obtain the `Server Fault Tolerance` status?

But in **Consul web UI** `Cluster Overview` shows this metrics, just like this: 
![image](https://github.com/user-attachments/assets/7f1c536a-7d9d-44b4-9347-9426e74ba598)

Could Nomad add this metrics, or how can I search this value?

**Comment by tgross** [comment]
Hi @liukch! Nomad doesn't expose this in the web UI but it's available in the [Read Health API (for Autopilot)](https://developer.hashicorp.com/nomad/api-docs/operator/autopilot#read-health) as the top-level field `FaultTolerance`.

**Comment by liukch** [comment]
@tgross Get it, Thank you very much. I will close this issue.
