### ISSUE TITLE
Implement CLI/API feature showing actual hostnames where allocation runs.

### ISSUE THREAD

**Issue by zoza1982** [hashicorp/nomad#2359]
Hi, this is a feature request.

Since killing a specific allocation which is part of the same job with multiple instances is not implemented yet  (https://github.com/hashicorp/nomad/issues/2181)   it would be good for purposes of chasing down that bad behaving allocation and killing it manually with kill -9 <pid>  to add ability to both "nomad status <job id> " CLI  and API to show the actual hostname where allocation runs along with other info like Node ID.

**Comment by schmichael** [comment]
In the meantime I took a stab at a curl+jq script to make things a little easier:

```sh
#!/bin/bash
set -e

ids=$(curl -s localhost:4646/v1/allocations | jq  -r ".[] | select(.JobID==\"$1\") | .NodeID")
for id in $ids; do
    curl -s localhost:4646/v1/nodes | jq -r ".[] | select(.ID==\"$id\") | .Name"
done
```

**Comment by zoza1982** [comment]
Thanks! That will work in the meantime!

**Comment by arshjohar** [comment]
We merged a PR that should display Node Name for job status and alloc status commands. Closing this one.
