### ISSUE TITLE
Nomad UI shows failed for jobs that are scaled to 0 

### ISSUE THREAD

**Issue by caiodelgadonew** [hashicorp/nomad#23591]
Hello, 

We have this behavior on nomad when we run `nomad job scale <job> <group> 0` that the job shows as failed.

It would be nice to have a better message for this state instead of Failed, I know the job is not healthy since the service checks cant pass cuz its scaled to zero, but maybe a flag "Downscaled" would be a good thing to have.

Is this on track? are there any plans for it? 

Example situation: 
![CleanShot 2024-07-14 at 12 02 03](https://github.com/user-attachments/assets/52a4aa40-bdf6-4633-82bd-609d3d65551e)

Expected:
![CleanShot 2024-07-14 at 12 10 43](https://github.com/user-attachments/assets/e13eb629-0303-44b5-b91b-5e3b94e35eb1)
or 
![CleanShot 2024-07-14 at 12 13 30](https://github.com/user-attachments/assets/3554c412-7e98-4159-884c-afe5453fff38)

**Comment by tgross** [comment]
@caiodelgadonew in recent versions of the UI we're presenting a sort of "aggregate state" based on the job status and the allocation status. Can you verify that the API is returning `Running` for the job status, and not `Dead`? (That is, what does `nomad job status $myjob` show for the job status?)

**Comment by caiodelgadonew** [comment]
@tgross no, its not returning running, its returning dead. 
I've deployed an example to test 

To reproduce, deploy any job, and then scale the groups to 0
In my example: 
```bash
$ nomad job scale testing-scheduler app 0
$ nomad job scale testing-scheduler app2 0
```

![CleanShot 2024-07-15 at 14 50 15](https://github.com/user-attachments/assets/ce8b4906-73f3-415e-9737-e65804b49a1c)

![CleanShot 2024-07-15 at 14 50 24](https://github.com/user-attachments/assets/96c01013-49c3-4683-b6f5-3f866326dfb0)

**Comment by tgross** [comment]
Ok, thanks. I'd expect a job with all complete allocations to be "dead". We made a lot of changes to provide reasonable "aggregate" statuses in 1.8, but there are an awful lot of corner cases :grin: I'll mark this for roadmapping.

**Comment by caiodelgadonew** [comment]
thanks @tgross , you mean `Running` right?

**Comment by tgross** [comment]
Actually, no. :grinning: The job status is a pretty coarse view of the world and so "dead" just means all allocations are terminal. I could definitely see an argument that this view of the world isn't ideal because it makes the UI design harder, but it's definitely the intended behavior right now. But the UI does want to present a richer "aggregate state" that would account for this case where the job is scaled down.

**Comment by philrenaud** [comment]
I've got a note to make this experience better in the UI. The common way this shows itself is when allocations complete and are garbage-collected, but garbage-collected allocations don't leave the UI with a lot of clues as to whether their absence is a bad thing (`Failed`) or an expected thing (`Dormant` or something).

In this case, a deliberate scale to 0 seems more detectable. I'll see what I can do to give a status less off-putting than `Failed` here.

**Comment by caiodelgadonew** [comment]
Any updates on this @philrenaud  ? :)

**Comment by sevensolutions** [comment]
I'am also playing around with job scaling to implement a scale-to-zero-strategy and came accross this issue.
One important thing for me is, that a job, scaled down to zero, must never be removed by the garbage collector so i can re-scale it up at every time.

**Comment by philrenaud** [comment]
Hi @caiodelgadonew, I've started thinking about a solution to this problem. The current logic for status has something like 

```
    if (failedOrLostAllocs.length >= expectedRunningAllocCount) {
      return { label: 'Failed', state: 'critical' };
```

Which generally works pretty well, except here, where `0` failed allocs is greater than or equal to `0` expected allocs, triggering the Failed state.

As such, in #23829 , I've started putting in a safety valve for exactly this case:

```
    if (expectedRunningAllocCount === 0) {
      return { label: 'Scaled Down', state: 'neutral' };
    }
```

This'll show something like this (3rd job shown):
![image](https://github.com/user-attachments/assets/b6912979-a974-4574-9fb6-ba8487fe7311)

Is this about what you had in mind?

========================

A secondary concern (cc @caiodelgadonew as well) is that these jobs are nevertheless considered `Dead` as far as the scheduling and garbage collection processes go (they are terminal until manual change is made to increase allocation count).

This means that these statuses are at most only temporary: "Scaled Down" is what you'd see until garbage collection takes place / a user runs `nomad system gc` / etc.

We have been exploring some concepts that would create garbage-collection-avoidance permanence (see [Golden Job Versions](https://github.com/hashicorp/nomad/issues/23794)) for example) that might mitigate this in the future, but I wanted to open a dialogue here to indicate the temporary nature of this status as implemented in #23829

**Comment by caiodelgadonew** [comment]
@philrenaud  That "Scaled Down" looks amazing! 
Imho if it could be in a different color (maybe yellow/warning?) would be 10/10

**Comment by sevensolutions** [comment]
@caiodelgadonew i also thought about a different color first, but i think "Scaled down" doesn't neccesarily need to be a warning. It may be intended.

**Comment by caiodelgadonew** [comment]
Yeah, you're correct, I like your idea. :) 

Any plans for shipping it?

**Comment by philrenaud** [comment]
Yep, let me test some edge cases and get it tagged for the next minor release. Thanks for your patience with this!

**Comment by caiodelgadonew** [comment]
Amazing @philrenaud many thanks!!!
