### ISSUE TITLE
Wrong time calculation at WebUI

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23626]
### Nomad version
```
Nomad v1.8.0
BuildDate 2024-05-28T17:38:17Z
Revision 28b82e4b2259fae5a62e2ed47395334bea5a24c4
```

### Operating system and Environment details
`Linux ip-172-31-6-94 6.8.0-1010-aws #10-Ubuntu SMP Thu Jun 13 17:36:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Issue

![image](https://github.com/user-attachments/assets/7b7d0c54-f4f6-4ea7-8232-6796c5fab812)

though the time on the server is:
![image](https://github.com/user-attachments/assets/12b1199c-8a3f-4d19-8884-7b106b8fafeb)

and on the client host where the webui page was opened:
![image](https://github.com/user-attachments/assets/0072dad6-de6f-4869-aac9-4c29c606135b)

#### Expected Result
It should be `11` instead of `10`.

#### Actual Result
It displays 10 and also shows ambiguous `a few second ago` `in a few seconds ago`. It would be nice to display actual time when hovering on a such sentences. How it is done on GitHub, SO etc.

![image](https://github.com/user-attachments/assets/1ef32e44-9006-49f3-b570-16dbed2fe202)

**Comment by EugenKon** [comment]
Afternoon time looks good:
![image](https://github.com/user-attachments/assets/f05a5263-72f5-4cdc-ad4b-0b5b34d7ec2f)

![image](https://github.com/user-attachments/assets/8502024f-91ac-4d5a-9251-8239c1baf324)

**Comment by tgross** [comment]
@EugenKon the `Modified` column shows the time the allocation was last modified (i.e. when it's state changed). That is not the same as the `Created` column. You're correct, those are different times as they should be.

If you have a comparison that shows the output of the API disagreeing with the UI, feel free to supply that here. But I'll close this in the meantime.

**Comment by tgross** [comment]
@EugenKon can you do me a favor and try opening discussions over at Discuss: https://discuss.hashicorp.com/c/nomad/28 before opening bugs from now on? You open quite a lot of "bug reports" that could be better handled in that forum.
