### ISSUE TITLE
`force_pull=true` does not have effect

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23627]
### Nomad version
v1.8.0

### Operating system and Environment details
Ubuntu 24.04

### Issue
I rebuild my underlying image and `nomad plan/run` job. Unfortunately nothing was updated. The current tasks still running the old image.
![image](https://github.com/user-attachments/assets/c78bfee0-514b-4ad2-901a-784fe3144eb3)
![image](https://github.com/user-attachments/assets/c9140918-9adf-4561-a21c-72c95b7fb598)
![image](https://github.com/user-attachments/assets/7f9095c8-65a6-4d29-a01e-37d1786b4920)

### Reproduction steps
1. COnfigure `force_pull=true`
2. Build new images
3. nomad plan/run job

#### Expected Result
Nomad should check new versions of docker image

#### Actual Result
Nothing is checked, tasks still use the old image.

**Comment by tgross** [comment]
@EugenKon that's not what the [`force_pull`](https://developer.hashicorp.com/nomad/docs/drivers/docker#force_pull) flag is for. Here's the docs:

> force_pull - (Optional) true or false (default). Always pull most recent image instead of using existing local image. Should be set to true if repository tags are mutable. If image's tag is latest or omitted, the image will always be pulled regardless of this setting.

Note that this doesn't say anything about forcing tasks to be replaced. The Nomad schedulers, which are running on completely separate machines, have no way of talking to Docker to figure out if the image has been changed. Nor would we want to have evaluation processing change depending on external APIs.
