### ISSUE TITLE
It is not clear the status of a cluster from WebUI

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23634]
### Nomad version
v1.8.0

### Operating system and Environment details
Ubuntu 24.04

### Issue
Everything looks good from a first sight:
![image](https://github.com/user-attachments/assets/ea6a3d7f-c7ea-498e-a98d-82753066cc3c)

But if we scroll a bit lower:
![image](https://github.com/user-attachments/assets/016b6b29-0df3-4a6a-b579-54f3de768c3e)

If we click `view all 23 allocations`
![image](https://github.com/user-attachments/assets/ebad8998-e7a4-47df-9f4c-2903894acc14)

It shows only 2.

### Reproduction steps
Do not know

#### Expected Result
I expect to see tasks with 'Running' Status instead of 'failed' and 'complete'

#### Actual Result
Nomad shows that something is failed, though a cluster and an application is accessable via web and functions well.

**Comment by philrenaud** [comment]
Hey @EugenKon, not a bug but a deliberate design decision. We've opted to show the current state of a job and how that matches up against desired state (based on your task group counts and running allocs). This is the default view labelled "Current" in the buttons on the right. There is also. "Historical" view which will show older allocations if you so desire.

Looking at your last screenshot: it appears that you have selected a status and a job version in the select boxes at the top (guessing you've selected "Status == Failed"). Remove this and you should see all allocations as desired.

**Comment by EugenKon** [comment]
@philrenaud Thanks for answer, but I do not understand nothing. Sorry.

1. Today I opened the same page and can see the 'ruggning' tasks. If you have opted them, why I can see them today?
![image](https://github.com/user-attachments/assets/29fae4a7-ddcd-4280-a4b2-e80686976946)
Why they were not displayed yesterday?

2. About the last screenshot.
I clicked 'view **all** XX allocations'.
![image](https://github.com/user-attachments/assets/f617b5e3-1ccf-4b5b-8656-09590e8a4dd2)
I do not know why filter is active when **all** allocation should be shown.

**Comment by philrenaud** [comment]
> Why they were not displayed yesterday?

This table, on the main job page, shows the most recent 5 allocations for a given job (by `modifyIndex`). So it's likely that the screenshots you see now had an update event more recent than when you posted the issue.

> why filter is active

This link takes you to the allocations page. In the Nomad UI, your status selections are remembered/cached for convenience during your session (if you set a filter and leave the page and come back, the filter remains). A simple refresh undoes this.

The "View all _____ links" might be better titled "Go to the allocations page" but otherwise that's the buggiest behaviour here.

**Comment by EugenKon** [comment]
@philrenaud Should we reopen the issue?

**Comment by philrenaud** [comment]
No, my feeling is the current behaviour (your in-session-set filters should be retained as you move throughout the app) has considerably more benefit than not.

**Comment by EugenKon** [comment]
My filling is that if the link says "Show all" the result should be "Show All". If "keep filter" the way we choose, then the link should be renamed. @tgross May you please review the solution?
