### ISSUE TITLE
"Page not found" error on docs website for "Bootstrapping Clusters" topic

### ISSUE THREAD

**Issue by nborkert** [hashicorp/nomad#2366]
Docs website returns a 404 for [https://www.nomadproject.io/docs/cluster/bootstrapping.html](https://www.nomadproject.io/docs/cluster/bootstrapping.html) the URL for "Bootstrapping Clusters".

**Comment by nborkert** [comment]
The content may have moved to [https://github.com/hashicorp/nomad/blob/master/website/source/guides/cluster/bootstrapping.html.md](https://github.com/hashicorp/nomad/blob/master/website/source/guides/cluster/bootstrapping.html.md)

**Comment by dadgar** [comment]
Closing in favor of https://github.com/hashicorp/nomad/issues/2367
