### ISSUE TITLE
nomad.service lack of User, Group options

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23685]
### Nomad version
```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Issue
https://developer.hashicorp.com/nomad/tutorials/enterprise/production-deployment-guide-vm-with-consul
Documentation recommends to start nomad.service using `nomad` user, but actual Nomad does not have this configuration
![image](https://github.com/user-attachments/assets/7dab0c6d-e270-49e4-81ee-86599578bdf8)

### Reproduction steps
See the screenshot above

#### Expected Result
The `nomad.service` should contain 'User','Group'

#### Actual Result
It does not contain

**Comment by jrasell** [comment]
Hi @EugenKon and thanks for raising this issue. I have raised a linked PR to explicitly set the user:group to root:root.
