### ISSUE TITLE
Provide a way to see the middle of the log

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23692]
### Proposal
![image](https://github.com/user-attachments/assets/f5384ca5-4e7d-4ca2-8b47-d7e11b57320b)

I can view head and tail of the log, but I do not see a way to see the middle of the log. Is it possible?

### Use-cases
It gives the information how the container was started

**Comment by jrasell** [comment]
Hi @EugenKon and thanks for raising this issue. There is no way see the middle of the log file and to even understand where the middle is, the client would need to iterate the entire log counting the lines and then use this value. It would be an expensive operation both computationally and for the network.

The Nomad API [supports setting an offset](https://developer.hashicorp.com/nomad/api-docs/client#offset-3) which is also available via the CLI. I am unsure if this would be useful in the UI thought and would just serve to clutter the display.

> It gives the information how the container was started

Would this information not be at the start of the log file, and therefore available via `Head`?

**Comment by EugenKon** [comment]
Hi, @jrasell 
At this task I want to find which backup was restored. The "tail" does not show this, because this info is somewhere at the beginning, thus I cliked "head", scrolled everything up to the end and saw that output was truncated. So I can not see the backup name: it is not at the beginning and not not at the end of output. It is somewhere in the middle.

> It would be an expensive operation both computationally and for the network.

I do not think it is expensive. This is the same as `tail` and/or `head` you are already used. Something similar to: `tail -n +12 filename | head -n 9` or `sed -n '12,20p' filename` or even `awk 'NR>=12 && NR<=20' filename`.

In the interface could be implemented some buttons to show `next` 1000 lines, or it could be done automatically when scroll is reached the end. Eg. you reached the end query next 1000, you reached the end, query a next 1000 lines and so on.

**Comment by jrasell** [comment]
> It is somewhere in the middle.

This is very ambiguous though and depends entirely on the application logs, how long it's been running, and many other factors. 

> I do not think it is expensive. This is the same as tail and/or head you are already used. Something similar to: tail -n +12 filename | head -n 9 or sed -n '12,20p' filename or even awk 'NR>=12 && NR<=20' filename.

The names are a reference only to the GNU coreutils commands they perform high level functionality similar to and that describe their behaviour. Nomad does not use those commands to perform allocation log streaming from a Nomad client to the Nomad server to your browser. The process is a little more convoluted.

I do think this is a little out of scope for logs processing within the Nomad UI, CLI and API in general. Ideally, if more complex navigation is required, logs should be shipped to an application built and designed for this job. Failing this, the [`nomad alloc fs` command](https://developer.hashicorp.com/nomad/docs/commands/alloc/fs) could be used to fetch the logs, allowing you to use any tool you wish to look through them. A custom [action](https://developer.hashicorp.com/nomad/docs/job-specification/action) could also produce the behaviour you're looking for.
