### ISSUE TITLE
API error (500): invalid volume specification when specifying both volume flag & selinuxlabel

### ISSUE THREAD

**Issue by sijo13** [hashicorp/nomad#23690]
### Nomad version
Nomad v1.7.3
BuildDate 2024-01-15T16:55:40Z
Revision 60ee328f97d19d2d2d9761251b895b06d82eb1a1

### Operating system and Environment details
OS: Rocky Linux release 9.4 (Blue Onyx)

### Issue
When docker [selinux](https://developer.hashicorp.com/nomad/docs/drivers/docker#selinuxlabel)  is specified in client config and a flag is specified when binding volumes(:ro), Docker throws an "Invalid volume specification" error because Nomad appends :ro to :z label which results into below error.

API error (500): invalid volume specification: '/data/nomad/alloc/9f2bfda3-a71e-6258-6be9-d87101b21387/redis/local/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro:z'

### Reproduction steps
1)Client config
```
plugin "docker" {
  config {
    endpoint = "unix:///var/run/docker.sock"
    gc {
      image_delay = "30m"
    }
    volumes {
      selinuxlabel = "z"
    }
  }
}
```
2) Run a Job with volume binding .
```
task "nginx-task" {
      template {
        data        = <<EOH
        <html><body>Hello World</body></html>
        EOH
        destination = "local/html/index.html"
      }
      driver = "docker"
      config {
        image = "nginx:latest"
        ports = ["http"]
        volumes = [
          "local/html:/usr/share/nginx/html:ro"
         ]
```
Also, I am able to run conatiner using below docker command providing both volume flag and selinuxlabel.
`docker run -it --rm -v /root/test/testing.conf:/root/test/testing.conf:ro,z nginx:latest`

#### Expected Result

Job should be running.

#### Actual Result
Job fails with below error
`API error (500): invalid volume specification: '/data/nomad/alloc/9f2bfda3-a71e-6258-6be9-d87101b21387/redis/local/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro:z'`

**Comment by tgross** [comment]
Hi @sijo13! This looks pretty straightforward... when we append the selinux label, we're appending with the `:` regardless of whether there's a mode. See [`driver.go#L784-L796`](https://github.com/hashicorp/nomad/blob/v1.8.2/drivers/docker/driver.go#L784-L796). Fix should be simple, but I've got to dig up a test rig with selinux to verify it works end-to-end before I can confidently say it's fixed :grin:

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/23750
