### ISSUE TITLE
Nomad 1.8.2 arm64 no cpu.usablecompute

### ISSUE THREAD

**Issue by ngcmac** [hashicorp/nomad#23710]
### Nomad version
1.8.2

### Operating system and Environment details
Debian 12 arm64 (AWS EC2)
### Issue

Nomad nodes with version 1.8.2 running in arm64 instances are not reporting correct CPU info.

We upgrade one of our Nomad clusters (3 servers and a few clients) to version 1.8.2 (from 1.6.3). We start to observe unplaced allocations due to not enough CPU. We have an AWS ASG in place managed by Nomad Autoscaler that uses Datadog metrics to increase or decrease the desired number of Nomad nodes, so we strange that suddenly we have no resources available. Looking to nomad.client.unallocated.cpu metric, the available CPU decreased and now shows a negative value after we upgraded the nodes:

![image](https://github.com/user-attachments/assets/44a600f2-b347-4bfe-8a15-3b61ca230177)

Looking into Nomad Ui, we have several nodes not reporting CPU info:

![image](https://github.com/user-attachments/assets/35b7f45f-9f7f-446f-8e4d-fb5bc3c1d5c2)

We verified that only amd64 nodes are correctly reporting cpu.totalcompute and cpu.usablecompute:

![image](https://github.com/user-attachments/assets/32899b78-4bc9-411c-8a00-7b57af599ff9)

This is something introduced in a recent version as Nomad nodes using version 1.6.3 correctly reports CPU info:

![image](https://github.com/user-attachments/assets/aea485b3-2e0d-4eeb-bd8c-855d14d01b69)

As the majority of our nodes are arm64, our cluster is pretty unusable. The autoscaler keeps increasing the number of instances but without CPU information, it's a never ending loop as nomad.client.unallocated.cpu keeps decreasing. We are replacing the nodes with new ones running Nomad version 1.6.3.

### Reproduction steps
Launch a new Nomad node running version 1.8.2 in an arm64 instance

#### Expected Result
The new node joins the cluster, reports correct CPU information (and the available CPU resources increase).

#### Actual Result
The new node joins the cluster, does not report CPU info and the available CPU resources decrease.

**Comment by tgross** [comment]
Hi @ngcmac! Sorry to hear you're running into trouble. 

Can you confirm whether you've got `dmidecode` installed on the hosts (see https://developer.hashicorp.com/nomad/docs/concepts/cpu#virtual-cpu-fingerprinting)? That's something that we needed to leverage as part of a big refactoring of fingerprinting we did in Nomad 1.7.0 to support NUMA. Can you also confirm you're running the Nomad client agent as root?

**Comment by JoaoPPinto** [comment]
Hello @tgross. I've looked into this as @ngcmac is currently out-of-office.

It appears the hosts in question did not have `dmidecode` installed.
After installing the package and upgrading the nodes again to Nomad 1.8.2, everything appears to be working as intended. We see the `cpu.usablecompute` and `cpu.totalcompute` with correct values and scheduling is working as is supposed.

Thank you for your help. I believe this issue can be closed.

**Comment by tgross** [comment]
Great to hear @JoaoPPinto! I think we need to update the installation guide to make sure this is getting surfaced for new users as well.
