### ISSUE TITLE
Consul does not detect state of service correctly if there is no space left on the client EC2 instance

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23727]
Consul version 1.18.2

On the client node we had full disk:
![image](https://github.com/user-attachments/assets/4839d57d-7c7b-4ecd-9550-3f96c1b59098)

The consul server WebUI reports:
![image](https://github.com/user-attachments/assets/e1ac175f-7ee7-4f5f-a52f-907685bdc5e3)

For these checks configured:
```
        check {
          name     = "PostgreSQL Health Check"
          type     = "script"
          command  = "pg_isready"
          args     = [
            "-h", "localhost",
            "-U", "user_api",
            "-d", "userdb"
          ]
          interval = "30s"
          timeout  = "5s"
        }

        check {
          name     = "PostgreSQL SELECT Check"
          type     = "script"
          command  = "psql"
          args     = [
            "-h", "localhost",
            "-U", "user_api",
            "-d", "userdb",
            "-c", "SELECT 1"
          ]
          interval = "30s"
          timeout  = "5s"
        }
```

Nomad client reports that task is alive (the WebUI is opened on Nomad server node, the same as Consul server):
![image](https://github.com/user-attachments/assets/b5553f30-5ea3-466c-b4f5-7dabf04a990b)

The logs of postgres looks fine:
![image](https://github.com/user-attachments/assets/4d98d68a-cfc2-4593-b3fe-a20a01ee2c45)

The similar error to the error reported by Consul WebUI I can see when I tried to go into postgres container:
![image](https://github.com/user-attachments/assets/f086b11f-816a-4ba6-aa95-f32c53d4d4e3)

### Expected behaviour
Consul should not report failed check if it is not able to run actual check. I still can connect to postgres database via IP:port. And it is healthy because its pgdata is mounted to a separate partition.

### Actual behaviour
I believe this issue is some sort similar to https://github.com/hashicorp/consul/issues/21372, because there also the service was alive. Problem was that Consul can not finish required preparations. For that case it is TLS connection was not established, for this case docker does not allow to connect to container, because `pty` is not able to be created.

**Comment by tgross** [comment]
Non-zero exit codes in the script check are a check failure. So this is working as intended.
