### ISSUE TITLE
docs: API examples use `https` URLs

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23722]
### Nomad version
v1.8.2

### Issue
![image](https://github.com/user-attachments/assets/ae55482b-4ec8-4145-8265-c00d0cea32e6)

https://developer.hashicorp.com/nomad/api-docs/system#sample-request
https://developer.hashicorp.com/nomad/api-docs/system#sample-request-1

Now API is available over `http`

### Reproduction steps
See the screenshot above

#### Expected Result
`https` should work, otherwise example should be fixed

#### Actual Result
`https` does not work.

**Comment by tgross** [comment]
@EugenKon TLS should work fine, even for localhost, assuming that you've got the appropriate [`tls`](https://developer.hashicorp.com/nomad/docs/configuration/tls) configuration. Do you have that configured on your agent?

**Comment by tgross** [comment]
The API docs need to show either `http://` or `https://` in the `curl` examples, so no matter which one we pick it's going to be wrong for some users. There's no way around this except to assume that users understand that they should be using whatever their particular cluster is configured for.

**Comment by EugenKon** [comment]
@tgross The examples should relay on the default configuration. By default TLS is not configured thus `http` should be used. I do not remember already the ticket. But the similar situation already happened and community supported my opinion that: `your examples in documentation worth nothing if they could not be run successfully by user`.

Not all users are experienced users. They could not distinguish between `http` and `https` yet. And do not understand errors they got from the commands. Thus having more clear documentation with examples which works is better for your company.
But many times you counted such propositions for improvement as questions and close them. Those are not the questions, I understand what is going on there. If you think they are time wasting for your team I could stop posting this.

@Community: If you believe these changes have matter please support me/convey these thoughts to HashiCorp, so they count them more seriously. Thank you.

Kindly regards.
