### ISSUE TITLE
No error messages at logs for `nomad acl token list` command

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23725]
### Nomad version
```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Operating system and Environment details
```
Linux ip-172-31-1-16 6.8.0-1012-aws #13-Ubuntu SMP Mon Jul 15 13:40:27 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
```
sudo journalctl -fxeu nomad
```
shows no error message when `permission denied` happened.

### Reproduction steps
```
nomad acl token list
```

#### Expected Result
I expect to see something similar to:
![image](https://github.com/user-attachments/assets/350a547a-a85d-45aa-9fc8-71686a4d3baf)

#### Actual Result
No error messages at logs.

**UPD**
I can see logs on nomad client, but I do not see them on nomad server. Both have the same configuration:
```
enable_debug = true
log_level = "WARN"
enable_syslog = true
```

**Comment by tgross** [comment]
@EugenKon the error message you're showing is for a different RPC than the one used by the `nomad acl token list` command. That would be the `ACL.ListTokens` RPC. We don't log Permission denied errors for RPC driven by user requests. You'll need the [`audit`](https://developer.hashicorp.com/nomad/docs/configuration/audit) logging feature in Nomad Enterprise to get that level of granularity.

**Comment by EugenKon** [comment]
@tgross
For the same configuration on server and client I can see log messages on nomad client, but I do not see messages on nomad server:

![image](https://github.com/user-attachments/assets/01034ca9-84bb-47b3-9e32-c34bdcb06633)
