### ISSUE TITLE
Nomad, job status: it should be 'terminated' instead of 'terminal'

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23726]
### Issue
Possible typo in DOC: https://developer.hashicorp.com/nomad/docs/configuration/server#node_gc_threshold
![image](https://github.com/user-attachments/assets/31717f46-2161-4fd2-ba71-d2718b656891)

#### Expected Result/Actual Result

```diff
-a terminal state
+a terminated state
```
I have not found the list of possible statuses of a job. But the most closest official status is `dead`.

**Comment by EugenKon** [comment]
The same:
https://developer.hashicorp.com/nomad/docs/configuration/server#job_gc_interval
![image](https://github.com/user-attachments/assets/21be8048-3733-4665-8df0-d1d156cdce0b)

**Comment by tgross** [comment]
Terminal is correct, referring to the "terminal state". Terminated would also be grammatically correct, but is not what we've chosen to use in Nomad documentation and code.
