### ISSUE TITLE
documentation: how to create a management token

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23724]
### Issue
![image](https://github.com/user-attachments/assets/cd6c405a-da16-4cc1-8ac1-2cfc0d9f2298)

https://developer.hashicorp.com/nomad/api-docs/system#force-gc
https://developer.hashicorp.com/nomad/api-docs#acls. < This document does not mention 'management'

#### Expected Result
It should be clear how to create policy with 'management' capabilities.

#### Actual Result
No description found.

This document also does not describes 'management' ACL: https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-policies#namespace-rules

**Comment by tgross** [comment]
Management tokens are created the same way all tokens are created, via the `nomad acl token create` command. You'll use the [`-type`](https://developer.hashicorp.com/nomad/docs/commands/acl/token/create#type) parameter to create a management token instead of a client token.

**Comment by EugenKon** [comment]
Hey, @tgross. This is not a question this is the report of issue with Nomad documentation. Probably, because you are expert in Nomad, you understand what 'management' means. For me it is not clear what `ACL Required management` means from the documentation links I have provided above. I could not imagine that it refers to a specific **token** creation. They do not have links to `nomad acl token create` command and `-type` option. Looking at ACL I suppose it was https://developer.hashicorp.com/nomad/docs/other-specifications/acl-policy 
Please reopen the issue.

**Comment by EugenKon** [comment]
@tgross
As a proposition: it is much clear to say "Required `management` token" instead of "ACL required `management`". Because ACL is configured via policies, but there is no such thing as `management`. It relates to token creation. And this should be spelled more explicitly.
