### ISSUE TITLE
[question] Tagging Server 

### ISSUE THREAD

**Issue by lshahar** [hashicorp/nomad#2374]
We running nomad on servers self-hosted and we would like to split server types frontend, backend and databases and each type of job should run at specific group. 

I found node variables that related to AWS like (platform.aws.instance-type) but I didn't find any why to do it at self hosted nodes.

Thanks a lot

**Comment by dadgar** [comment]
@itatabitovski Answer works. Another possibility is to create separate DCs for each and then target.

This is a bit of static portioning and you do not really need to do this. Just let the scheduler decide. I am going to close this but if you have question feel free to add them here and in the future the mailing list is preferred for questions.

**Comment by splashx** [comment]
> You should be able to achieve this but configuring node_class and/or user defined metadata on your clients.

That's true but one needs to then scrap the metadata first, assemble the nomad client config and push it to the clients. I can imagine it this way (example):

- Using e.g. terraform, deploy 50 VMs to AWS (or Openstack) - in the .tf files you have custom metadata  `node_class` defined
   - `node_class` is something that defines a group of VMs by some property you can't get via fingerprinting / [built-in nomad Cloud Metadata](https://www.nomadproject.io/docs/job-specification/constraint.html#cloud-metadata): security groups is probably a good property candidate
- You set it up so you end up with the following metadata in the VMs:
   - `node_class: backend` (30 VMs), 
   - `node_class: frontend` (10 VMs) 
   - `node_class: database` (10 VMs)
- Using a configuration tool of choice (e.g. ansible, which can leverage from [dynamic inventory script](http://docs.ansible.com/ansible/latest/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script) ) - the only role of the configuration tool is to deploy nomad client config leveraging the metadata (jinja2 templating)

This is the strategy I could come up with - but now I wonder if there is a better strategy than this @itatabitovski @dadgar?

**Comment by itatabitovski** [comment]
@splashx That sounds about right, you specify class and client metadata in the config.

You can also have auto scaling groups per node class, so you don't have to bring 50 VMs immediately , but have AWS add and remove client nodes when necessary.
