### ISSUE TITLE
Agent Healthcheck

### ISSUE THREAD

**Issue by seeder** [hashicorp/nomad#2375]
### Nomad version
0.5.4

### Operating system and Environment details
docker, linux amd64

This is particularly bad on dynamic environments like docker or the cloud where IPs are assigned dynamically from a pool. 

### Issue

Nomad registered health check in consul is invalid when binding to `0.0.0.0` or `::`

It this case it should be able to use either the advertised address or set it individually.

### Reproduction steps

u

1. se `bind_addr` of `0.0.0.0` or `::`
2. start nomad
3. have a look at failing checks in consul trying to connect to `0.0.0.0` or `::`

**Comment by dadgar** [comment]
Hey, this options exists: https://www.nomadproject.io/docs/agent/configuration/consul.html#checks_use_advertise
