### ISSUE TITLE
UI: terminal allocation from previous job version is updated

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23777]
### Nomad version
```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Operating system and Environment details
```
Linux ip-172-31-10-241 6.8.0-1012-aws #13-Ubuntu SMP Mon Jul 15 13:40:27 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
![image](https://github.com/user-attachments/assets/eefee754-5540-4d65-8e16-28002dcdbf89)

I have task test, but it does not have `redis-db` group. It was deleted sometime ago. But when the task is replanned we still see that Nomad works with not existent `redis-db` group and updates its status.

### Reproduction steps
1. Create job file with `redis-db` group and task
2. nomad plan/run it
3. Rename group and task to `test`
4. nomad plan/run
5. Stop the docker container for test task: `docker stop test-XXXXX`
Nomad will spot that task is not healthy and restart it, but in the same time it will update the status for not existent `redis-db` group

#### Expected Result
The removed task/group should be removed from monitoring by Nomad.

#### Actual Result
The Nomad still works with the removed task/group.

### Job file
```
job "test" {
  type = "service"

  group "test" {
    count = 1

    restart {
      attempts = 5
      delay    = "15s"
      interval = "3m"
      mode     = "delay"
    }

    task "test" {
      driver = "docker"

      config {
        force_pull = true
        image = "xxxx"
     }

      service {
        name = "test"
        tags = ["test"]

        provider = "consul"
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @EugenKon! I wasn't able to reproduce, but I believe this may be specific to the UI.

Some of the behavior you're seeing is expected. Recent previous allocations show up in the Recent Allocations section of this page, including allocations for previous versions of the job. When those old allocations stop, we should see their states updated to `complete`, and then never changed again.

Can you confirm that the old allocations had transitioned to `complete` before you killed any docker tasks?

**Comment by tgross** [comment]
We never heard back on this, so I'm going to close it out for now.
