### ISSUE TITLE
Support docker run healthcheck argument's

### ISSUE THREAD

**Issue by lostb1t** [hashicorp/nomad#23780]
With Nomad adding more standalone functionality (service discovery etc) consul isn't much needed for some cases.

But i do find myself missing the script health check functionality. I could extend docker images but that would mean i have to maintain and update them.

With this request closed #8326 the next best thing is to add support for docker run healthcheck arguments.

reference: https://docs.docker.com/engine/reference/run/#healthchecks

**Comment by tgross** [comment]
@lostb1t the [`check`](https://developer.hashicorp.com/nomad/docs/job-specification/check) block also works with Nomad native services.  We don't want to support Docker-specific health checking when we have health checking with Nomad services already, as that just creates extra maintenance and weird splits in behavior between task drivers. For example, how would users query the status of Docker-specific health checks unless we wire up this extra data in the task driver protocol, which would then be redundant with Nomad native checks.

That being said, it looks like we don't currently support the script and grpc [`type`](https://developer.hashicorp.com/nomad/docs/job-specification/check#type) for the Nomad provider. The script checks especially seem like they'd be both valuable to implement and hard to workaround for users. I'm going to make sure we have an open issue for implementing that.

**Comment by lostb1t** [comment]
yeah im aware, i was specifically talking about script checks. 

Great to hear its going to get an issue for it.
