### ISSUE TITLE
Custom plugin fails to compile on Windows

### ISSUE THREAD

**Issue by kamyar1979** [hashicorp/nomad#23791]
### Nomad version
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
 go version go1.22.6 windows/arm64

### Operating system and Environment details
Windows 11 ARM64

### Issue
Custom plugin fails to compile, Go 1.22.6

### Reproduction steps
1. Get our open source plugin: https://github.com/TibaGroup/nomad-dotnet-driver
2. Remove go.mod and go.sum
3. go mod init github.com/TibaGroup/nomad-dotnet-driver
4. Add following line to go mod: "replace github.com/armon/go-metrics v0.5.3 => github.com/hashicorp/go-metrics v0.5.3"
5. go mod tidy
6. go build -o plugin_directory/nomad-dotnet-driver

#### Expected Result
The binary must be built.

#### Actual Result
github.com/hashicorp/nomad/client/lib/fifo
..\go\pkg\mod\github.com\hashicorp\nomad@v1.8.2\client\lib\fifo\fifo_windows.go:101:18: undefined: winio.ListenOnlyPipe

**Comment by kamyar1979** [comment]
Resvoled: Changed winio.ListenOnlyPipe to winio.ListenPipe
Apparently it is a long time that the function name has changed!

**Comment by pkazmierczak** [comment]
Hey @kamyar1979, thanks for reporting this! Sadly, [we depend on a fork](https://github.com/hashicorp/nomad/issues/11826) of Microsoft/go-winio, so you'll need another line in the go.mod file:
```
replace (
	github.com/Microsoft/go-winio => github.com/endocrimes/go-winio v0.4.13-0.20190628114223-fb47a8b41948
	github.com/armon/go-metrics => github.com/armon/go-metrics v0.0.0-20230509193637-d9ca9af9f1f9
)
```
Let me know if this helps!

**Comment by kamyar1979** [comment]
Thank you! The solution works! It would be better to mention these changes in the documents.
