### ISSUE TITLE
FreeBSD support for plugins

### ISSUE THREAD

**Issue by kamyar1979** [hashicorp/nomad#23790]
### Nomad version
Nomad v1.8.1

### Operating system and Environment details
FreeBSD 14.1, ARM64

### Issue
Custom plugin loading crashes! The plugin works on Mac and Linux. After recompiling on FreeBSD the Nomad service failes to load.

### Reproduction steps
1. Get our open source plugin https://github.com/TibaGroup/nomad-dotnet-driver
2. Compile and copy the binary to plugin dir of nomad
3. Restart Nomad service

#### Expected Result
The dotnet plugin would be healthy on agent dashboard

#### Actual Result
The following error raises:
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe51d30]

goroutine 349 [running]:
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).Slice(0x41135c?)
	github.com/hashicorp/nomad/client/lib/idset/idset.go:126 +0x20
github.com/hashicorp/nomad/plugins/base.nomadTopologyToProto(0xd0bb61e0)
	github.com/hashicorp/nomad/plugins/base/base.go:171 +0x34
github.com/hashicorp/nomad/plugins/base.(*AgentConfig).toProto(0xd0515828)
	github.com/hashicorp/nomad/plugins/base/base.go:96 +0x44
github.com/hashicorp/nomad/plugins/base.(*BasePluginClient).SetConfig(0xd0969820, 0xd0d66210)
	github.com/hashicorp/nomad/plugins/base/client.go:63 +0x2c
github.com/hashicorp/nomad/helper/pluginutils/loader.(*PluginLoader).Dispense(0xd0700810, {0xd0c17966, 0x6}, {0x27c70ef, 0x6}, 0xd0515828, {0x2fa6c50, 0xd0aff800})
	github.com/hashicorp/nomad/helper/pluginutils/loader/loader.go:186 +0x300
github.com/hashicorp/nomad/helper/pluginutils/singleton.(*SingletonLoader).dispense(0x0?, 0xd0809200, {0xd0c17966?, 0x1?}, {0x27c70ef?, 0x479d28?}, 0xd0993380?, {0x2fa6c50?, 0xd0aff800?})
	github.com/hashicorp/nomad/helper/pluginutils/singleton/singleton.go:109 +0x58
created by github.com/hashicorp/nomad/helper/pluginutils/singleton.(*SingletonLoader).getPlugin in goroutine 329
	github.com/hashicorp/nomad/helper/pluginutils/singleton/singleton.go:85 +0x318

**Comment by pkazmierczak** [comment]
Hey @kamyar1979, thanks for reporting the issue and sorry to hear the plugin fails on FreeBSD. Sadly, we do not officially support FreeBSD and while I can't confirm for sure, from the crash message it appears that our new CPU detection/fingerprinting system introduced in 1.7 does not work on FreeBSD. We'd be happy to review PRs that address this, but we won't debug the issue ourselves.

**Comment by kamyar1979** [comment]
Help me fix the problem in a PR! I can do it with a little guidance

**Comment by pkazmierczak** [comment]
hey @kamyar1979, I can't really help you with FreeBSD other than point you to an [area of the code that is likely causing the error](https://github.com/hashicorp/nomad/blob/7cf63326322c92074dab53321c32ddee92627bcd/plugins/base/base.go#L166), but I also see you're running 1.8.1. We had a similar error [reported](https://github.com/hashicorp/nomad/issues/23385) some time ago, and we [fixed it](https://github.com/hashicorp/nomad/pull/23399) in 1.8.2. Perhaps try a newer Nomad version to see if it fixes your issue?

**Comment by kamyar1979** [comment]
Thank you! At first, I tried compiling 1.8.2 and the problem fixed! But I lost the web interface! Then I updated the binary package to 1.8.1.3 and the web interface is up and the plugin works!
