### ISSUE TITLE
extra_claims job ID without periodic suffix for batch jobs

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#23798]
### Proposal
Add a `vault.default_identity.extra_claims` interpolation for the job ID that does not include the `/periodic-1234567` suffix, the same way the `nomad_job_id` does not include it. 

Currently `${job.id}` looks something like this `my-batch-job-name/periodic-1723556632` and I'd like a variable (perhaps `${job.name}`?) that gives me just `my-batch-job-name`

### Use-cases
- Vault integration for batch jobs. Not having the periodic suffix makes it more doable to actually provide secrets/paths in the Vault policy that it can access. 

### Attempted Solutions
- No workaround is available.

Currently available interpolations:

https://github.com/hashicorp/nomad/blob/90d646a2ae696058f04bd634f596052897ec2719/nomad/structs/workload_id.go#L235-L252

Sorry @tgross for not realizing this when the PR was still a PR.

**Comment by tgross** [comment]
:facepalm: That's embarrassing. Will fix.

**Comment by the-nando** [comment]
hey @tgross I've run into this as well unfortunately, in my quest to migrate some clusters to workload identity. Do you know more or less when this bug fix will ship?

**Comment by tgross** [comment]
I've got a PR up with the fix https://github.com/hashicorp/nomad/pull/23817 but I've been on PTO the last couple weeks. Planning on shipping this in the upcoming Nomad 1.4.0.
