### ISSUE TITLE
CSI volumes cannot be displayed in Nomad 1.8 GUI

### ISSUE THREAD

**Issue by thetoothpick** [hashicorp/nomad#23831]
### Nomad version
Nomad 1.8.2

### Issue
When loading the "Storage" page, CSI volumes are initially listed, but clicking on one triggers a 404 error, and the page tries to dynamically load more data, which also triggers 404 errors.

It looks like the UI is trying to call URLs with this pattern:

```
$NOMAD_ADDR/v1/plugin/csi%2Fplugin-name
$NOMAD_ADDR/v1/volume/csi%2Fvolume-name
```

The correct URLs appear to be:

```
$NOMAD_ADDR/v1/plugin/csi/plugin-name
$NOMAD_ADDR/v1/volume/csi/volume-name
```

Note the extraneous `/` URL escaping.

### Reproduction steps
Load https://nomad.url/ui/csi/volumes

#### Expected Result
Volume list is displayed, volume details can be viewed by clicking on a volume.

#### Actual Result
Volume list is displayed momentarily, but soon goes blank (or shows "No Volumes").

![nomad-volume-list](https://github.com/user-attachments/assets/ce0cf6b5-0ffb-445f-a85c-ce3afff2aeef)

Clicking on a volume while it's displayed shows a "Not Found" error.

![nomad-volume-details](https://github.com/user-attachments/assets/811af342-6e94-407f-8509-d9533ecfddd7)

**Comment by tgross** [comment]
Hi @thetoothpick! This should already be fixed in Nomad 1.8.3 by https://github.com/hashicorp/nomad/pull/23625 (I see it on the [changelog](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#183-august-13-2024))

**Comment by thetoothpick** [comment]
@tgross oh great - sorry for the duplicate!

**Comment by 4W5ZeZPMc** [comment]
i have updated to `1.8.3` bug is still occurring

**Comment by 4W5ZeZPMc** [comment]
@tgross can u reopen this issue or should i create a new one?

**Comment by robbiexiong** [comment]
having same issue here. also update to 1.8.3

**Comment by tgross** [comment]
Reopening.
