### ISSUE TITLE
Implement restart mechanism for dependent tasks upon primary task restart

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#23839]
### Proposal

Need the ability to restart secondary tasks if the primary one restarts.

### Use-cases
We are launching several tasks in one group; the first task run a container with a network, and the rest of the tasks are launched within this container's network.
Example spec:

```
job "job1" {

  group "group" {

    task "init" {
      lifecycle {
        hook = "prestart"
        sidecar = true
      }
      config {
        network_mode = "bridge"                 //  <--------------   network create
  
      service {
      }
    }

    task "sidecar" {
      lifecycle {
        sidecar = true
      }
      config {
        network_mode = "container:init-${NOMAD_ALLOC_ID}"    # <------  net from init task
      }
    }

    task "service" {
      lifecycle {
        hook = "poststart"
        sidecar = false
      }

      config {
        network_mode = "container:init-${NOMAD_ALLOC_ID}"    # <------  net from init task
      }
    }

  }
}
```
If, for some reason, the first task restarts (for example, if it's killed by the OOM killer), the rest will continue to operate but will be left without a network.

**Comment by apollo13** [comment]
If you set the mode in the network stanza of the group (https://developer.hashicorp.com/nomad/docs/job-specification/network) to bridge you will achieve what you have?  Can you explain the usecase for what you are trying to do?

**Comment by TheSpbra1n** [comment]
@apollo13 Thank you for the advice!
But it doesn't suit our needs. We are initiating our first container within a separate network, exemplified as "primary_net," using our custom network driver. The configuration is roughly as follows:
```
task "init" {
  driver = "docker"
  config {
    ...
    dns_options = ["timeout:1", "attempts:3"]
    dns_servers = ["${meta.external_ipv6_addr}"]
    advertise_ipv6_address = true
    network_mode = "primary_net"
    sysctl {
      net.ipv6.conf.eth0.accept_ra = "0"
    }
    ...
  }
}
```
I tried allocating these settings at the group level:
```
group "main" {
  network {
    mode = "primary_net"
    dns {
      servers = ["${meta.external_ipv6_addr}"]
      options = ["timeout:1", "attempts:3"]
    }
  }
  ...
}
```
However, this resulted in an error: 
`failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: plugin type="loopback" failed (add): failed to find plugin "loopback" in path [/opt/cni/bin]`

We do not use CNI. Also, it is unclear how to handle the sysctl settings.

**Comment by apollo13** [comment]
Well yes you cannot put arbitrary modes into the group network (your intial example had bridge iirc hence why I suggested it). What you are doing sounds kind of fragile though. Doing that as CNI plugin might actually get that running stable (ymmv).

**Comment by Juanadelacuesta** [comment]
Hi @TheSpbra1n, as @apollo13 mentioned, this setup can fail in multiple ways, is the task crashes or is rescheduled by nomad. You could use an ephemeral side car to take care of networking, or a separate batch job. If you want to keep your setup, using the `poststop` hook in the `lifecycle` stanza of the dependent task can be what you need.

**Comment by TheSpbra1n** [comment]
Ok. We are trying to switch to CNI plugins and abandon our own driver. This task is becoming irrelevant. Thank you!
