### ISSUE TITLE
Nomad client on custom ARM Linux reports 0 cpu.usablecompute

### ISSUE THREAD

**Issue by rahadiangg** [hashicorp/nomad#23840]
### Nomad version
Output from `nomad version`

Nomad v1.8.3
BuildDate 2024-08-13T07:37:30Z
Revision 63b636e5cbaca312cf6ea63e040f445f05f00478

### Operating system and Environment details

Embeded custom linux ARM

### Issue

My team have hundreds (>800) [payment devices](https://www.emperortech.com/products/TicketingSystem/emp5210.html) running in production. Those devices are running custom linux built using [Buildroot](https://gitlab.com/buildroot.org/buildroot/) and flashed/installed by the vendor. Our application is a single binary file running inside those devices, when we need to update our application, we will manually update it (replace the binary). So we think Nomad is a good fit for our use case (edge ​​computing?).

When we first ran the Nomad binary inside those devices, we got an error that Nomad needs to use glibc 2.28. So, we manually built the Nomad binary using glibc 2.24 which is compatible with our devices. The Nomad agent works, but `cpu.usablecompute` is 0. According to this thread #19343, Nomad requires `dmidecode` installed. 

We tried build `dmidecode` for ARM and running it, this is what we got:
![IMG_3070](https://github.com/user-attachments/assets/128c6b51-19cd-4d37-a6d8-c5ed9793d86c)

Is there another way for the Nomad client to be able to load `cpu.usablecompute` without `dmidecode` ?. Detailed information on Nomad clients can be seen below.

#### Nomad Client Information

<details>

```
Allocated Resources
CPU      Memory       Disk
0/0 MHz  0 B/493 MiB  0 B/2.3 GiB

Allocation Resource Utilization
CPU      Memory
0/0 MHz  0 B/493 MiB

error fetching node stats: actual resource usage not present

Allocations
No allocations placed

Attributes
cpu.arch                  = arm
cpu.numcores              = 1
cpu.reservablecores       = 1
cpu.totalcompute          = 0
cpu.usablecompute         = 0
driver.exec               = 1
driver.java               = 1
driver.mock_driver        = 1
driver.raw_exec           = 1
kernel.arch               = armv7l
kernel.name               = linux
kernel.version            = 4.1.0-linux4sam_5.3
memory.totalbytes         = 517001216
nomad.advertise.address   = 10.5.149.65:4646
nomad.revision            = 63b636e5cbaca312cf6ea63e040f445f05f00478+CHANGES
nomad.service_discovery   = true
nomad.version             = 1.8.3
numa.node.count           = 1
numa.node0.cores          = 0
os.name                   = buildroot
os.signals                = SIGHUP,SIGIOT,SIGKILL,SIGSTOP,SIGUSR2,SIGFPE,SIGIO,SIGPROF,SIGQUIT,SIGTTIN,SIGPIPE,SIGTRAP,SIGILL,SIGTERM,SIGTSTP,SIGXCPU,SIGNULL,SIGCONT,SIGINT,SIGSYS,SIGTTOU,SIGUSR1,SIGBUS,SIGSEGV,SIGXFSZ,SIGABRT,SIGALRM,SIGWINCH
os.version                = 2017.05
unique.hostname           = EMP5210
unique.network.ip-address = 10.5.149.65
unique.storage.bytesfree  = 2434502656
unique.storage.bytestotal = 3252125696
unique.storage.volume     = /dev/mmcblk0p3

Meta
connect.gateway_image                           = docker.io/envoyproxy/envoy:v${NOMAD_envoy_version}
connect.log_level                               = info
connect.proxy_concurrency                       = 1
connect.sidecar_image                           = docker.io/envoyproxy/envoy:v${NOMAD_envoy_version}
connect.transparent_proxy.default_outbound_port = 15001
connect.transparent_proxy.default_uid           = 101
```

</details>

**Comment by schmichael** [comment]
> I think we can use [cpu_total_compute](https://developer.hashicorp.com/nomad/docs/configuration/client#cpu_total_compute) on client node configuration ?

Yes, manually setting `cpu_total_compute`  is the recommended workaround. Feel free to reopen this issue if for some reason that does not work.

Given the variety of ARM systems in existence it's very difficult for us to find a cpu fingerprinting solution that works well everywhere. #19468 tracks a related cpu fingerprinting issue, so I'm going to close this one.

**Comment by schmichael** [comment]
Also I just want to say that sounds like a very exciting use case! I hope Nomad serves your purposes well.
