### ISSUE TITLE
some nomad things dont work through reverse proxy

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#23854]
### Nomad version
nomad version
Nomad v1.8.3
BuildDate 2024-08-13T07:37:30Z
Revision 63b636e5cbaca312cf6ea63e040f445f05f00478

### Operating system and Environment details
amazonlinux 2023

### Issue
I'm trying to get nomad working through a reverse proxy.  Seems the direct traffic works but maybe some javascrpt requests are using the wrong host.

### Reproduction steps
Set up a reverse proxy for nomad (have fun).  Load nomad.  View an allocation logs page.  See error.

#### Expected Result
Loggy Logs would load.

#### Actual Result
Loggy Logs don't load.

![Task_vector_logs_-_Nomad](https://github.com/user-attachments/assets/5bd9fba4-3461-4d57-afdb-8c0f908d86f2)

**Comment by philrenaud** [comment]
Hi @josh-m-sharpe , thanks for filing this. Have you had the chance to look at [Configure NGINX reverse proxy](https://developer.hashicorp.com/nomad/tutorials/manage-clusters/reverse-proxy-ui) in our tutorials? It has a few tips specifically related to logs (disabling `proxy_buffering` for example). If you're not using NGINX, some of the principles should still apply.

**Comment by josh-m-sharpe** [comment]
Not sure if that guide really means to add a bogus address or not?
```
advertise {
  http = "internal-ip:9999" # this is definitely bogus.
}
```

Is it supposed to work because I see no change.  The client is still attempting to connect to the ip address.

**Comment by philrenaud** [comment]
I think that part is meant to simulate the "logs won't show up because of inaccess from the reverse proxy". The proxy config options are the more pertinent parts, I think.

**Comment by josh-m-sharpe** [comment]
Thanks for the help!
