### ISSUE TITLE
Parse job endpoint doesn't act on `VariableFlags` parameter

### ISSUE THREAD

**Issue by kyrias** [hashicorp/nomad#23878]
### Nomad version
```
Nomad v1.8.3
```

### Issue

According to [the API documentation](https://developer.hashicorp.com/nomad/api-docs/jobs#parse-job) the parse job endpoint is supposed to take both `Variables` and `VariableFlags` so you can submit the variables in either var-file format or as a structured map.  In practice Nomad currently only actually uses the `Variables` parameter, which is unfortunate since it means that we'll need to serialize our variables to the var file format before submitting them.

### Reproduction steps

- Submit a parse job request with the variables passed in the `VariableFlags` parameter.

#### Expected Result

- Nomad uses the variables passed in.

#### Actual Result

- Nomad silently ignores the variables

**Comment by Juanadelacuesta** [comment]
Hello @kyrias thank you so much for reporting this issue, unfortunately the `VariableFlags` parameter for the pars job endpoint seems to be an error on our documentation and we will work on correcting it. For now, you do need to serialize your variables in order to use this endpoint.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/23909
