### ISSUE TITLE
Nomad does not work on ARM/Rapsberry Pi due to wrong cpu info

### ISSUE THREAD

**Issue by ranjib** [hashicorp/nomad#239]
gopsutil reports ARM processors with empty cores/resources. leading to failure in allocation
https://github.com/shirou/gopsutil/issues/88

**Comment by cbednarski** [comment]
Thanks for opening this. I'm excited about building a NomadPi cluster also!

**Comment by ranjib** [comment]
the cpu frequency issue has been resolved on the upstream gopsutil code. But the total comput capacity is still reported as 0 due to the following code in nomad https://github.com/hashicorp/nomad/blob/c5397b3dc88161c58eb1752001a63dec730f7671/client/fingerprint/cpu.go#L37
for systems that does not have multiple cores (like arm) c.Cores will be 0 always (even with 4 cpu), resulting in total compute capacity as 0. 
i am wondering whats the best solution for this, if number of cores is 0, then should we assume its 1?

**Comment by cbednarski** [comment]
> for systems that does not have multiple cores (like arm) c.Cores will be 0 always (even with 4 cpu), resulting in total compute capacity as 0. 

Every CPU should have at least 1 core. Does `gopsutil` report 0 here? If so I think we should push that fix upstream.

**Comment by ranjib** [comment]
@cbednarski yeah gopsutil reports 0, cause it fetch the number of cores from /proc/cpuinfo, linux on arm does not have that line in cpuinfo. 
by the way, this was the last bug for getting nomad running on pi. i got it working just now :0-) . super happy

**Comment by cbednarski** [comment]
> gopsutil reports 0, cause it fetch the number of cores from /proc/cpuinfo, linux on arm does not have that line in cpuinfo. 

Thanks for clarifying. I think we could work around in this in Nomad but since 0 is not the correct value I would like to take the opportunity to push the fix upstream.

**Comment by ranjib** [comment]
yeah, i'll create an issue to track this on gopsutil.

**Comment by kardianos** [comment]
This should be fixed in gopsutil now.

**Comment by ranjib** [comment]
@kardianos i just tried this 
```go
package main
import(
        "github.com/shirou/gopsutil/cpu"
        "github.com/davecgh/go-spew/spew"
)

func main(){
        info, _ := cpu.CPUInfo()
        spew.Dump(info)
}
```
```
([]cpu.CPUInfoStat) (len=4 cap=4) {
 (cpu.CPUInfoStat) {"cpu":0,"vendor_id":"","family":"","model":"","stepping":0,"physical_id":"","core_id":"0","cores":0,"model_name":"ARMv7 Processor rev 5 (v7l)","mhz":900000,"cache_size":0,"flags":["half","thumb","fastmult","vfp","edsp","neon","vfpv3","tls","vfpv4","idiva","idivt","vfpd32","lpae","evtstrm"]},
 (cpu.CPUInfoStat) {"cpu":1,"vendor_id":"","family":"","model":"","stepping":0,"physical_id":"","core_id":"1","cores":0,"model_name":"ARMv7 Processor rev 5 (v7l)","mhz":900000,"cache_size":0,"flags":["half","thumb","fastmult","vfp","edsp","neon","vfpv3","tls","vfpv4","idiva","idivt","vfpd32","lpae","evtstrm"]},
 (cpu.CPUInfoStat) {"cpu":2,"vendor_id":"","family":"","model":"","stepping":0,"physical_id":"","core_id":"2","cores":0,"model_name":"ARMv7 Processor rev 5 (v7l)","mhz":900000,"cache_size":0,"flags":["half","thumb","fastmult","vfp","edsp","neon","vfpv3","tls","vfpv4","idiva","idivt","vfpd32","lpae","evtstrm"]},
 (cpu.CPUInfoStat) {"cpu":3,"vendor_id":"","family":"","model":"","stepping":0,"physical_id":"","core_id":"3","cores":0,"model_name":"ARMv7 Processor rev 5 (v7l)","mhz":900000,"cache_size":0,"flags":["half","thumb","fastmult","vfp","edsp","neon","vfpv3","tls","vfpv4","idiva","idivt","vfpd32","lpae","evtstrm"]}
}
```
as long as Cores is reported as 0, nomad will fail.

**Comment by kardianos** [comment]
@ranjib I'm sorry, I didn't fully read this issue; I confused it with a previous one. Let me look into that.

**Comment by kardianos** [comment]
@ranjib @cbednarski  There could be a semantic meaning issue here. "gopsutil" on my single socket six core machine will report six processors, each with 6 cores. In nomad/client/fingerprint/cpu.go, this will result in nomad reported 36 total cores. Either nomad needs to count cores differently or gopsutil needs to alter how it reports topology.

Related: https://github.com/shirou/gopsutil/issues/104

**Comment by kardianos** [comment]
@ranjib This is now fixed in gopsutil.

**Comment by ranjib** [comment]
@kardianos :sunflower: i'll take it for a spin tonight and validate. I am maintaining similar patch on my fork now, i'll get rid of that https://github.com/ranjib/nomad/blob/lxc/client/fingerprint/cpu.go#L37
thanks a lot, really appreciate it

**Comment by felipesere** [comment]
@ranjib @kardianos 
Has there been any progress on this?
I'd like to setup a RPi2 cluster in the new year to experiment with different cluster/scheduling tools.

**Comment by kardianos** [comment]
@felipesere As far as I know, this should be fixed per my previous comment.

**Comment by ranjib** [comment]
@felipesere you can run nomad now on raspberry pi. i run a 8 node cluster with full influxdb. grafana. telegraf stack. All necessary changes in gopsutil and rest other projects has been merged. You can find the builds here https://github.com/ranjib/PiChef/releases . It has nomad and few other binaries (goiardi for chef, gypsy for CI etc)
There are still some issues with wrong CPU speed reporting due the averaging logic.. but that should not be a blocker, worst case Pis will repost 4 times more cpu than they can offer
let me know if you need anything
ps. the nomad binary available on my repo is not from master, but from the lxc/systemd branch (its periodically merged with master and supports system & lxc as exec driver). I have tested all of these with ubuntu 15.04
