### ISSUE TITLE
[question] Nomad syslog timestamp

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#2392]
Nomad stamps log messages in the following format: 2017/03/02 06:27:27.521907

We remote syslog, and would like to see the date in ISO format, e.g: 2017-03-02T06:27:27.522Z

Is there anyway to specify the date format used for these messages?

**Comment by itatabitovski** [comment]
Maybe this can be combined with [#2194](https://github.com/hashicorp/nomad/issues/2194)

**Comment by dadgar** [comment]
@itatabitovski Yep good call!
