### ISSUE TITLE
Nomad UI reports that task status is stopped despite on some allocations still are running

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23940]
### Nomad version
v1.8.3

### Operating system and Environment details
```
Ubuntu 24.04
Linux www-nomad-0 6.8.0-1013-aws #14-Ubuntu SMP Thu Jul 25 21:19:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
![image](https://github.com/user-attachments/assets/933efba4-b5b6-4513-bcaa-7eabea82f090)

### Reproduction steps
nomad stop portal

#### Expected Result
during stopping nomad should display 'stoppoing' status and not 'stopped'

#### Actual Result
Nomad displays 'stopped' though some allocations still are running.

**Comment by philrenaud** [comment]
Hi @EugenKon — this is to be expected, provided those allocations are in the process are shutting down. Allocations can be running, pending, failed, lost, or unknown, but there isn't such a concept as "stopping".

**Comment by EugenKon** [comment]
We faced this issue again. This is not good that a cluster does not have any jobs, but still running tasks. This causes a cluster under heavy load whole day, though it should not. All jobs were stopped.
