### ISSUE TITLE
UUIDs are not UUIDs

### ISSUE THREAD

**Issue by brickmonster** [hashicorp/nomad#23978]
### Nomad version
v1.8.3

### Operating system and Environment details
Linux

### Issue
What nomad calls a "UUID" is actually 16 random bytes printed in the format of a UUID.

Examples of them being referred to as UUIDs:
https://developer.hashicorp.com/nomad/api-docs/allocations#alloc_id

https://github.com/hashicorp/nomad/issues/10727#issuecomment-857655552

### Reproduction steps
Try to insert a UUID into a MariaDB UUID column, or paste a UUID into https://www.uuidtools.com/decode
Some allocation UUIDs:
`56bf98c5-305d-7627-3060-69c0c699cd64`
`0e52b18d-a84f-30ee-8217-19736537222c`
Node UUID:
`237aed2a-9380-da26-65ad-a7c95f124750`
Evaluation UUID:
`a4988080-bad0-452a-1aa9-702fa37178db`

#### Expected Result
A consistent variant and version

#### Actual Result
A random variant and version (not specifically the v4 random version)

#### Current Implementation
https://github.com/hashicorp/nomad/blob/a2b19851a262a9ccc0f10019ce80d4eba8201241/helper/uuid/uuid.go#L13
Something more appropriate from java:
https://github.com/openjdk/jdk/blob/64e3a9ee91a6ae939e479a10cfc597e628c571e5/src/java.base/share/classes/java/util/UUID.java#L152

**Comment by shoenig** [comment]
Hi @brickmonster these are not and are not documented as _UUIDv4_ specific UUIDs. Yes they look the same because the format is convenient, but nothing about their use in Nomad is v4 specific or relevant.
