### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [hashicorp/nomad#24004]
### Proposal

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Nomad application as shown [here](https://elest.io/open-source/nomad). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by jrasell** [comment]
Hi @kaiwalyakoparkar and thanks for raising this issue and for pointing us and the community to this Nomad deployment option. I've added a comment to the PR and raised shared this issue internally; I'll post any followup here or directly as detailed with your email. Thanks again.

**Comment by kaiwalyakoparkar** [comment]
Thank you so much @jrasell

**Comment by jrasell** [comment]
Hi @kaiwalyakoparkar; I chatted to people internally and someone will reach out via the email you provided in order to discuss potential collaboration.
