### ISSUE TITLE
Cannot use go templates for job status output

### ISSUE THREAD

**Issue by pgporada** [hashicorp/nomad#24050]
### Nomad version
```
$ nomad version
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Operating system and Environment details
Ubuntu 24.04

### Reproduction steps
Outputting the job status with no flags works as intended.
```
$ nomad job status unbound
ID            = unbound
Name          = unbound
Submit Date   = 2024-08-26T15:12:03Z
Type          = service
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
unbound     0       0         1        10      7         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
6434d73b  91601963  unbound     1        run      running  6h33m ago  6h32m ago
```

Outputting json works too
```
$ nomad job status -json unbound
[
    {
        "Allocations": [
            {
                "ClientDescription": "Tasks are running",
                "ClientStatus": "running",
                "CreateIndex": 54792,
                "CreateTime": 1727102074670516215,
                "DeploymentStatus": {
                    "Canary": false,
                    "Healthy": true,
                    "ModifyIndex": 54798,
                    "Timestamp": "2024-09-23T14:35:00.770167884Z"
                },
                "DesiredDescription": "",
                "DesiredStatus": "run",
...
```

Using the go template flag fails
```
$ nomad job status -t unbound
Both json and template formatting are not allowed
```

#### Expected Result
That's a good question, I was just playing around seeing _what_ I could output without needing to filter with grep or jq.

#### Actual Result
See above in reproduction steps

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

**Comment by tgross** [comment]
Hi @pgporada! Yup, that's working as expected (although we should probably document it). Go template works on the in-memory representation of the objects we're sending, so once we've serialized it to JSON it's no longer "structured" (to the CLI it's now just a string of bytes) and Go templates won't work anymore.

**Comment by pgporada** [comment]
How should that `-t` flag be used then?

**Comment by tgross** [comment]
:facepalm: I'm having a whole morning of reading issue reports too quickly. I blame lack of coffee. You're right, if you're not _also_ using the `-json` flag that `-t` flag should work fine. The bug is here: [`job_status.go#L176`](https://github.com/hashicorp/nomad/blob/main/command/job_status.go#L176). That `true` parameter should instead be `json` to pass the value of the `-json` flag.

That'll let you do Go template evaluations like this, using this weirdly gnarly [`JobJson` object](https://github.com/hashicorp/nomad/blob/v1.8.4/command/job_status.go#L39-L44)

```
$ nomad job status -t '{{ range $job := . }}{{$job.Summary.JobID}}{{end}}' example
```

Fixed in https://github.com/hashicorp/nomad/pull/24054

**Comment by pgporada** [comment]
Cool, thank you! Cheers on ☕
