### ISSUE TITLE
Nomad needs to sanitize the injected env var names

### ISSUE THREAD

**Issue by timperrett** [hashicorp/nomad#2405]
lets say i have a job callled `foo-bar`. Nomad will at runtime inject an env var, `NOMAD_ADDR_foo-bar_whatever`. Given that dashes are not allowed in env vars names, they must be sanitized by nomad for the bash-allowed var syntax.

**Comment by schmichael** [comment]
Attached a binary built from #2406 if you want to test it. NBD

[linux_amd64.zip](https://github.com/hashicorp/nomad/files/823050/linux_amd64.zip)

**Comment by schmichael** [comment]
Missed an env var with that first pass. Got 'em all now.

[linux_amd64.zip](https://github.com/hashicorp/nomad/files/823351/linux_amd64.zip)
