### ISSUE TITLE
UI - Versions - Revert Version improvements

### ISSUE THREAD

**Issue by davidlublink** [hashicorp/nomad#24156]
### Proposal

I propose changing the way the 'Revert Version' function works in the Nomad UI:

![image](https://github.com/user-attachments/assets/bf514e09-0746-4983-9ed8-6b560e521051)

In it's current form, when I click 'Revert Version' it asks for confirmation and submits the changes.

I would like a new button 'Edit this version in the plan UI' where it would take the version selected and drop it into the 'Plan Job' UI. From here, I could make changes to the job before submitting, these changes could include changing the name of the job(thus cloning from an old version ).

### Use-cases

1. I have an older version of a job I want to return to without affecting the running allocations, I press the button give the job a new name and possibly tweak some parameters before submitting
2. I want to run an old version of the job on a different cluster(maybe a testing cluster), if I click this button when I land on the 'Plan Job' page, I can copy the entire content out to the different cluster without having to reconstruct the job manually from the diff and the current version.

### Attempted Solutions

1. Revert to the version I want to investigate
2. Go copy the definition from the definition page
3. Revert the job back to the pre-reverted state in step 1
4. Modify the job in an external editor
5. Submit the job

The issue with this solution is the active allocations might be destroyed as a result of the 'Revert version' and so the operator has to break services to return to this older version.

**Comment by philrenaud** [comment]
Hey @davidlublink, this is a fantastic suggestion. We have [a few changes to the versions page](https://github.com/hashicorp/nomad/pull/24064) coming up soon, and this is a good opportunity to expand on those as well. I'll make a point to dig into this soon.

**Comment by philrenaud** [comment]
Hi @davidlublink , wanted to reach out and thank you again for this suggestion. We added "Clone as new version" and "Clone as new job" options to version blocks on this page, and I hope they satisfy your requirements here.
