### ISSUE TITLE
Update nodes (/v1/nodes) api to take query params

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/nomad#2415]
It'd be helpful to be able to filter nodes received via the API by attributes like NodeClass or Status. A corresponding update to the CLI would also be nice.

https://www.nomadproject.io/docs/http/nodes.html

Thanks, Justin

**Comment by tgross** [comment]
Doing some issue clean up and this one is actually done! [`filter`](https://www.nomadproject.io/api-docs/nodes#filter) expressions shipped for a bunch of the APIs in [Nomad 1.3.0](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#130-may-11-2022)
