### ISSUE TITLE
node name is not deregistered from cluster if instance was terminated

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#24163]
### Nomad version
v1.8.2

### Issue
If node was terminated and the recreated eg. by autoscaling group. The node name is still reserved for already not existing node and prevents a replacement node to start

![image](https://github.com/user-attachments/assets/5a935ea1-e02d-4cfa-b371-ab6dbc92a0bf)

![image](https://github.com/user-attachments/assets/5a1c9f9f-7608-4363-8803-0ea54f8d1417)

### Reproduction steps
I do not know exactly. I just terminate instance and create a new one by tuning "Desired capacity" from 1 to 0 and from 0 to 1 at autoscaling groups.

#### Expected Result
When EC2 instance was terminated and does not exist at the cluster anymore, Nomad/Consul should detect that and remove reservation.

#### Actual Result
The name still reserved for already not existent EC2 instance

#### Additional info
I noticed this strange thing in Consul web UI:
Time to time (around 1min intervarl) I can see this node here:
![image](https://github.com/user-attachments/assets/15953a48-48c2-4486-9898-5e29e65b7c75)
As you can see the interface says that this node does not have "health checks", but actually it has and all are passed:
![image](https://github.com/user-attachments/assets/e659ab1b-7e9c-48e4-af68-f9e484e2572e)

**Comment by EugenKon** [comment]
I repeat experiment with another autoscaling group: worker, by terminating one of the instance.
![image](https://github.com/user-attachments/assets/22ab2100-e38a-4736-98bb-93ebc2276ecf)

I do not see name conflict though the name is still reserved as it is for nomad-www-autoscale
![image](https://github.com/user-attachments/assets/90b3f691-0777-4b8a-b968-09c63682f667)

Here the logs on the new worker instance:
![image](https://github.com/user-attachments/assets/ec8a4da8-eaa1-4b1f-a3e5-93a1b19218b1)

**Comment by EugenKon** [comment]
Just in case want to show that the names are the same:
![image](https://github.com/user-attachments/assets/4a637437-136a-4516-878f-bd8afa0968a1)
![image](https://github.com/user-attachments/assets/1f9aa671-da9b-4d64-bedf-e10754f84ab3)

**Comment by EugenKon** [comment]
Added the second instance with the same name. They do not conflict with each other. See 1 and 2
![image](https://github.com/user-attachments/assets/e8261962-96d2-48aa-b7c3-684e90c094f9)
It would be nice if nomad deregister names for terminated instances.

**Comment by tgross** [comment]
@EugenKon node names must be unique, so as long as the old node exists in state you cannot add a new node with the same name. You can tune the time it takes for the node to be GC'd via [`server.node_gc_threshold`](https://developer.hashicorp.com/nomad/docs/configuration/server#node_gc_threshold). This is working as intended.

**Comment by EugenKon** [comment]
@tgross
Yes, they must be uniq, and nomad should not be able to register the node with the same name `nomad-worker-autoscale` twice.

https://github.com/hashicorp/nomad/issues/24163#issuecomment-2405570491
