### ISSUE TITLE
`Dimension "disk" exhausted` does not resolve when space gets freed, until restart

### ISSUE THREAD

**Issue by nh2** [hashicorp/nomad#24205]
This is a re-open of bug #4563 from 2018 which was closed (why?) but still happens.

### Nomad version

`v1.6.8`

### Operating system and Environment details

NixOS 24.05

### Reproduction steps

* Fill up client's disk.
* Restart nomad, get `Dimension "disk" exhausted on 1 nodes`, no jobs get scheduled on this client.
* Free up the disk space.

#### Expected Result

The `exhausted` should disappear.

#### Actual Result

The `exhausted` stays. Nomad does not notice that the disk got freed, and needs to be manually restarted.

**Comment by Juanadelacuesta** [comment]
Hi @nh2! Thank you for reaching out, unfortunately like you mentioned, the Nomad agent only scans the node on start up, so if the resources, like disk space, are freed midway, it wont be aware of the changes. There is a [issue](https://github.com/hashicorp/nomad/issues/24049) being discussed that could introduce new mechanism for fingerprinting, but for now, it just on sighup. If you feel like this is something you could work on, we invite you to open a PR.
