### ISSUE TITLE
working dir of binary

### ISSUE THREAD

**Issue by feverzsj** [hashicorp/nomad#2420]
Currently the working dir is set at task level. So, exec\raw_exec a binary not directly under the task dir could cause problem. It's kinda counterintuitive.

I can set destination = "" to force the binary location match the task dir, but extra care must be taken to avoid nomad predefined folder/files.

**Comment by feverzsj** [comment]
After verfying the network log, we found the binary failed to locate index.html which is depolyed in the same archive. But, if we manually start the binary extracted by nomad at the same location, everthing just fine.

**Comment by dadgar** [comment]
@feverzsj We will search the task directory, the local directory and the path for a binary right now. The command can also include the path so you can run `command = "local/my-binary"`.

In the future we will allow setting the working directory: https://github.com/hashicorp/nomad/issues/2224
