### ISSUE TITLE
Slow artifact downloads

### ISSUE THREAD

**Issue by zegl** [hashicorp/nomad#2421]
### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu 16.04 LTS

### Issue
Downloading the artifact takes over 60 seconds. A `wget` of the same file from the server is completed in less than 1s.

The file is downloaded from the same machine as the one that runs nomad server (a workaround while waiting for #1897).

Is there any way to speed up the artifact download process?

The output in hashi-ui looks like this:

![](https://i.imgur.com/Il9B9o1.jpg)

### Reproduction steps
nomad plan, nomad run

### Job file (if appropriate)

```
 task "service" {
      driver = "exec"

      artifact {
        source = "http://10.0.30.2/service"
      }
}
```

**Comment by dadgar** [comment]
@zegl Hey,

The artifact downloading should take just as long as curl. The exec driver is actually building an isolated filesystem between "Downloading Artifacts" and "Started". In 0.5.5 we now emit an event to depict what is actually happening 👍
