### ISSUE TITLE
Docker task driver CPU metrics broken in Nomad 1.9.0

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/nomad#24224]
### Nomad version
```
Nomad v1.9.0
BuildDate 2024-10-10T07:13:43Z
Revision 7ad36851ec02f875e0814775ecf1df0229f0a615
```

### Operating system and Environment details
multiple platforms.
`Linux 6.6.40-v8+ aarch64 GNU/Linux`
`Darwin 23.6.0 Darwin Kernel Version 23.6.0 root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020 arm64`

### Issue
The Guage nomad.client.allocs.cpu_total_ticks doesn't show the latest value but a running average?

### Reproduction steps
Run Docker job with an earlier version of Nomad and examine metrics, then update to Nomad 1.9.0 and compare.

#### Expected Result
Similar metrics to the previous version

#### Actual Result

This graph shows the metrics of Nomad 1.8.4 then upgraded to 1.9.0 at 09:00 then restarting services at 11:30 to see to the metrics were broken because of the upgrade.
![metrics-graphs-docker](https://github.com/user-attachments/assets/7cfb9200-6c87-4fcf-b97c-c7f584bec9ea)

**Comment by tristanmorgan** [comment]
probably related to #23966

**Comment by tgross** [comment]
Hi @tristanmorgan! That superficially looks like the bug we fixed during the beta here https://github.com/hashicorp/nomad/pull/24092 but apparently either there's another bug or we missed something in testing. I'll investigate and report back shortly.

**Comment by tgross** [comment]
Hello again, @tristanmorgan! I don't seem to be able to reproduce this bug _quite_ as you've described, but I think the way your metrics are getting presented is obscuring the underlying problem, whihc is that the metrics output has changed significantly for some reason.

I used the following job spec:

<details><summary>jobspec</summary>

```hcl
job "httpd" {

  group "web" {
    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html><div>hello, world</div></html>"
        destination = "${NOMAD_TASK_DIR}/index.html"
      }

      resources {
        cpu    = 100
        memory = 100
      }

    }
  }
}
```

</details>


And then looked up the allocation IP/port and ran `wrk -c 4 -t 4 -d10m "http://10.37.105.17:27473"` to give it some load. Concurrently I ran the following script:

```bash
#!/usr/bin/env bash

METRICS_URL="http://nomad0.local:4646/v1/metrics"

while :
do
      sleep 1
      OUT=$(curl -s "$METRICS_URL")

      ticksval=$(echo "$OUT" | jq -r '.Gauges[] | select(.Name == "nomad.client.allocs.cpu.total_ticks") | select(.Labels.job == "httpd") | .Value')
      countval=$(echo "$OUT" | jq -r '.Counters[] | select(.Name == "nomad.client.allocs.cpu.total_ticks_count") | select(.Labels.job == "httpd") | .Sum')

      echo "total_ticks: $ticksval / total_ticks_count(sum): $countval"
done
```

And here I definitely see the expected variations in the metrics you're looking at:

```
$ ./script.sh
...
total_ticks: 27.963937759399414 / total_ticks_count(sum): 262.1565456390381
total_ticks: 27.963937759399414 / total_ticks_count(sum): 262.1565456390381
total_ticks: 27.963937759399414 / total_ticks_count(sum): 262.1565456390381
total_ticks: 27.963937759399414 / total_ticks_count(sum): 262.1565456390381
total_ticks: 31.898258209228516 / total_ticks_count(sum): 301.2439880371094
total_ticks: 31.898258209228516 / total_ticks_count(sum): 301.2439880371094
total_ticks: 34.619422912597656 / total_ticks_count(sum): 337.17788314819336
total_ticks: 34.619422912597656 / total_ticks_count(sum): 337.17788314819336
total_ticks: 34.619422912597656 / total_ticks_count(sum): 337.17788314819336
...
```

But if I run the exact same workload and script on Nomad 1.8.4, I get completely different _scale_ of metrics output:

```
$ ./script.sh
...
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2319.0009765625 / total_ticks_count(sum): 3778.9722900390625
total_ticks: 2228.9765625 / total_ticks_count(sum): 21538.755126953125
total_ticks: 2228.9765625 / total_ticks_count(sum): 21538.755126953125
total_ticks: 2228.9765625 / total_ticks_count(sum): 21538.755126953125
total_ticks: 2228.9765625 / total_ticks_count(sum): 21538.755126953125
...
```

That doesn't explain why yet, but that gives me a new place to look.

**Comment by tgross** [comment]
Looks like the new client isn't returning any values for `PreCPUStats`, which is the "previous" version of the stats from the Docker API. Presumably that's due to version negotiation with the client, but that also means we need to adjust our CPU calculations to adjust for that. Working on a solution for that next.

**Comment by tgross** [comment]
I've got a draft PR up at https://github.com/hashicorp/nomad/pull/24229 which I've tested manually, but I'd like to figure out how we want to write an automated test to catch this kind of thing in the future.

**Comment by tristanmorgan** [comment]
Sorry I couldn't provide more than "something's broken". I'm glad you could find the cause.

**Comment by tgross** [comment]
The graphs were very helpful! Thanks!
