### ISSUE TITLE
`nomad node pool jobs all` does not return any jobs

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#24222]
### Nomad version
```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Operating system and Environment details
```
uname -a
Linux nomad-consul-server-0-c4cf 6.8.0-1016-aws #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
```
$ nomad node pool list
Name     Description
all      Node pool with all nodes in the cluster.
default  Default node pool.

$ nomad node pool jobs default
ID        Type     Priority  Status   Submit Date
portal    service  50        running  2024-10-15T16:59:27-04:00
postgres  service  50        running  2024-10-15T17:00:13-04:00
redis     service  50        running  2024-10-15T17:00:26-04:00

$ nomad node pool jobs all
No jobs
```
If node pool `all` contains all nodes, then it should list jobs from `default` pool as well.

### Reproduction steps
```
nomad node pool jobs all
```

#### Expected Result
All jobs should be listed.

#### Actual Result
No jobs

**Comment by tgross** [comment]
@EugenKon "all" doesn't refer to "all nodes and jobs", but the special built-in node pool to which all nodes belong. Only jobs explicitly add in the "all" node pool will show up here. See the [Built-in Node Pools](https://developer.hashicorp.com/nomad/docs/concepts/node-pools#built-in-node-pools) docs:

> * [all](https://developer.hashicorp.com/nomad/docs/concepts/node-pools#all): In some situations, it is useful to be able to run a job across all clients in a cluster, regardless of their node pool configuration. For these scenarios the job may use the built-in all node pool which always includes all clients registered in the cluster. Unlike other node pools, the all node pool can only be used in jobs and not in client configuration.
