### ISSUE TITLE
feature request: remove all the nulls from API response.

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#24261]
### Proposal
My idea is to remove all the fields that are null from any JSON responses.

Is there a specific reason these nulls exists? If not, I request to remove them.

### Use-cases
There are a lot of problems with these nulls. They just convey no information. The use case is any time someone receives any response from Nomad API, the nulls can be removed.

For example, a job that has no meta has "Meta" field equal to null, not to an empty dict `{}`. The following python code is invalid:

    jobjson["Meta"].get("mymeta", "default")

you have to write:

    (jobjson["Meta"] or {}).get("mymeta", "default")

For example, when an `/v1/allocation` response has no `"TaskStates"`, it does not have empty `{}` dictionary. It has `"TaskStates": null`. There are nulls everywhere.

### Attempted Solutions

The output of `nomad job run -output` is unreadable and has 73 nulls.
    
    $ nomad job run -output ./docs.nomad.hcl | head
    {
        "Job": {
            "Region": null,
            "Namespace": null,
            "ID": "docs",
            "Name": "docs",
            "Type": null,
            "Priority": null,
            "AllAtOnce": null,
            "Datacenters": [
   $ nomad job run -output ./docs.nomad.hcl | grep -c 'null,'
   73

I have written the following script:

```
#!/usr/bin/env python3
import json, sys
def remove_null(data):
    if isinstance(data, dict):
        return {k: remove_null(v) for k, v in data.items() if v is not None and v != ""}
    elif isinstance(data, list):
        return [remove_null(v) for v in data if v is not None and v != ""]
    return data
atonce=1
if atonce:
    json.dump(remove_null(json.load(sys.stdin)), sys.stdout, separators=(',',':'))
    print()
else:
    for i in sys.stdin:
        json.dump(remove_null(json.loads(i)), sys.stdout, separators=(',',':'))
        print()
```

Now the output is readable. And I can still post this to nomad job run without any loss of information:
  
    $ env -u VAULT_TOKEN nomad job run -output docs.nomad.hcl | ./remove_all_the_nulls.py | jq
    {
      "Job": {
        "ID": "docs",
        "Name": "docs",
        "Datacenters": [
          "dc1"
        ],
        "TaskGroups": [
          {
            "Name": "example",
            "Tasks": [
              {
                "Name": "server",
                "Driver": "docker",
                "User": "",
                "Config": {
                  "args": [
                    "-listen",
                    ":5678",
                    "-text",
                    "hello world"
                  ],
                  "image": "hashicorp/http-echo",
                  "ports": [
                    "http"
                  ]
                },
                "Leader": false,
                "ShutdownDelay": 0,
                "KillSignal": "",
                "Kind": ""
              }
            ],
            "Networks": [
              {
                "Mode": "",
                "Device": "",
                "CIDR": "",
                "IP": "",
                "ReservedPorts": [
                  {
                    "Label": "http",
                    "Value": 5678,
                    "To": 0,
                    "HostNetwork": ""
                  }
                ],
                "Hostname": ""
              }
            ]
          }
        ],
        "Dispatched": false
      }
    }

Some of these still could be removed, i.e. all the `""` and default values. Why "KillSignal" is ""? what does it mean?

From my tests, I captured some output of `/v1/event/stream` and removed all the nulls from it. The output can be reduced by about 16% !!! just by removing all the nulls.

```
$ nomad operator api /v1/event/stream > data.json
^C
$ export LC_ALL=C; post=$(cat data.json | ./remove_all_the_nulls.py); wc --total=never data.json - <<<$post | numfmt --field 1,2,3 --to=si; echo "smaller by $(echo "(1 - $(wc -c <<<$post) / $(wc -c <data.json) ) * 100" | bc -l)%"
    550     63k    4.2M data.json
    550     63k    3.5M -
smaller by 16.18227015899894124300%
```

Thank you.

**Comment by Juanadelacuesta** [comment]
Hi @Kamilcuk! Thank you for bringing this to out attention, we can see your point, but unfortunately making such a change could break backwards compatibility as people might wait for all the fields to be present even if they don't have any value, or nil. A workaround could be to use a tool like `jq` to process Nomad's output: 
```
nomad job run -output job.nomad.hcl | jq 'del(.. | select(. == null))'
```
I hope this is an option for you, feel free to reach back if not.
