### ISSUE TITLE
Implicit CNI constraints are added for jobs not using CNI

### ISSUE THREAD

**Issue by aholyoake-bc** [hashicorp/nomad#24310]
### Nomad version
Nomad server v1.8.4
Nomad clients various <1.5.0

### Operating system and Environment details
Linux 
### Issue
The implicit constraints on CNI added here
https://github.com/hashicorp/nomad/pull/15473
seem to be applied to jobs and clients that are using the docker default bridge network (and not a CNI bridge network). As such we can no longer schedule jobs on old clients after upgrading to v1.8

**Comment by apollo13** [comment]
Well this is documented here: https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#cni-constraints and explicitly asks to update the clients to at least 1.5?

**Comment by aholyoake-bc** [comment]
Yes, looks like it.
Thanks
