### ISSUE TITLE
[docker] "Invalid volume specification" when specifying both volume flags & selinuxlabel

### ISSUE THREAD

**Issue by aluxian** [hashicorp/nomad#2436]
### Nomad version
v0.5.4

### Operating system and Environment details
Alpine v3.5, Linux 4.5.7-std-3, Docker v1.12.6

### Issue
When _docker.volumes.selinuxlabel_ is specified in client config and a flag is also specified when binding volumes, Docker throws an "Invalid volume specification" error because Nomad just appends `:<docker.volumes.selinuxlabel>`to the volume flags instead of replacing them (or letting the volume definition override them).

### Reproduction steps
1. Set a flag in client config:
```
client {
  options {
    "docker.volumes.selinuxlabel" = "z"
  }
}
```

2. Run a job that binds a volume with a custom flag:
```
job "gluster" {
  group "fs" {
    task "server" {
      driver = "docker"
      config {
        volumes = [
          "/sys/fs/cgroup:/sys/fs/cgroup:ro",
        ]
...
```

3. Get error:
```
nomad alloc-status 55a361b9
...
Recent Events:
Time                   Type            Description
03/12/17 18:03:35 UTC  Not Restarting  Error was unrecoverable
03/12/17 18:03:35 UTC  Driver Failure  failed to start task "server" for alloc "55a361b9-0322-1c26-f36f-6ffdd96cd1be": Failed to create container: API error (500): {"message":"Invalid bind mount spec \"/sys/fs/cgroup:/sys/fs/cgroup:ro:z\": Invalid volume specification: '/sys/fs/cgroup:/sys/fs/cgroup:ro:z'"}
03/12/17 18:02:58 UTC  Driver          Downloading image gluster/gluster-centos:latest
03/12/17 18:02:58 UTC  Received        Task received by client
```

### Culprit

This line: https://github.com/hashicorp/nomad/blob/dea5a83ef7ac37b109fc5c97227a6d65df994403/client/driver/docker.go#L718

### Solution

- let flags in the job spec override the selinux flag?
- append the selinux flag to the given ones? (e.g. in my example it would take `ro` and append `z`)

**Comment by schmichael** [comment]
As far as I can tell labels (`z`) and `ro` are exclusive in Docker. You can only use one or the other. I can't find any definitive documentation on the subject, but I can't craft a `docker run --volume ...` line that contains both.

**Comment by aluxian** [comment]
Yeah, I was under the assumption that they are not mutually exclusive. Alright! Thanks for taking a look.

**Comment by schmichael** [comment]
No problem. It was a learning experience for me too. The Docker docs are really unclear.

**Comment by aluxian** [comment]
Yeah, in many aspects, and the interface is a bit hard to navigate :/
