### ISSUE TITLE
[question] Does the agent configuration support hot reloading?

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#2437]
In nomad 0.5.3, the following was introduced:

> vault: Support setting the Vault role to derive tokens from with create_from_role setting [GH-2226]

In our scenario, we are using aws-ec2 auth to acquire a token that nomad can use.  When this expires, it would be nice to hot reload the vault token rather than restarting the agent.

I imagine the restart of the agent would be fine, but I'm concerned that the node leaving will cause shifting of jobs.

**Comment by dadgar** [comment]
0.5.5 will: `server/vault: Vault Client on Server handles SIGHUP to reload configs [GH-2270]`

**Comment by BSick7** [comment]
Thanks @dadgar!
