### ISSUE TITLE
Template: Support Docker Kill as a Signal

### ISSUE THREAD

**Issue by bantonj** [hashicorp/nomad#2438]
When using a consul-template you can send a signal to the task, but it looks like only os.Signals are supported. I see that [go-dockerclient support this](https://github.com/fsouza/go-dockerclient/blob/8844e96b4cd6730ab2daa510a96e232107a2c09c/testing/server_test.go#L760).

**Comment by dadgar** [comment]
@bantonj We use that api: https://github.com/fsouza/go-dockerclient/blob/8844e96b4cd6730ab2daa510a96e232107a2c09c/container.go#L1120
