### ISSUE TITLE
S3 artifacts: Also support non-aws S3-compatible services

### ISSUE THREAD

**Issue by stefreak** [hashicorp/nomad#2444]
### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu

### Issue
Only AWS urls are supported (hardcoded in nomad code). If I force s3 via s3::, expected behaviour for me would be that any URL gets accepted even if it isn't amazon aws.

### Reproduction steps
use s3:: url with alternative S3 provider

**Comment by dadgar** [comment]
Hey can you file and cross link against https://github.com/hashicorp/go-getter

**Comment by stefreak** [comment]
go-getter issue: https://github.com/hashicorp/go-getter/issues/52

**Comment by lfarnell** [comment]
I sent a PR for this: https://github.com/hashicorp/go-getter/pull/68. Any feedback would be great :)
