### ISSUE TITLE
Requirements page for Nomad on the website is missing (404)

### ISSUE THREAD

**Issue by amanjeev** [hashicorp/nomad#2449]
### Nomad version
N/A

### Operating system and Environment details
N/A

### Issue
The Requirements web page is missing from the Nomad website. https://www.nomadproject.io/docs/cluster/requirements.html used to work until yesterday but is missing. The source seems to be present https://github.com/hashicorp/nomad/blob/master/website/source/guides/cluster/requirements.html.md

### Reproduction steps
* Go to https://www.nomadproject.io/docs/cluster/requirements.html
* Error: Page not found

**Comment by sethvargo** [comment]
Hey there,

Thanks for letting us know. Our automated deployed had failed to deploy the cache. That page should now properly redirect to `/guides/cluster/requirements.html`. Sorry about that!
