### ISSUE TITLE
UI shows no difference between versions

### ISSUE THREAD

**Issue by t-davies** [hashicorp/nomad#24504]
### Nomad version
1.9.1+ent

### Operating system and Environment details
Amazon Linux 2023, in AWS

### Issue
Since updating to 1.9.1+ent, the job versions UI shows "No Changes" between all versions. Initially I thought this was affecting versions that existed prior to updating, but it seems to also affect versions deployed after the upgrade too.
![image](https://github.com/user-attachments/assets/7725546e-dba0-4b6b-891e-4d0ed2b3f68c)

#### Expected Result
The UI shows the difference between job versions.

#### Actual Result
The UI shows no difference between job versions.

### Job file (if appropriate)
Applies to all jobs.

**Comment by t-davies** [comment]
Looks like the UI is calling a malformed URL to fetch diffs?
```
/v1/job/[job-id]/versions?namespace=xyz?diffs=true&namespace=xyz
```

**Comment by t-davies** [comment]
My bad, didn't see it earlier but this looks like a duplicate of https://github.com/hashicorp/nomad/issues/24444.

**Comment by philrenaud** [comment]
Yep! Thanks for raising the issue and sorry for the hassle. Look for it in a nomad release soon!
