### ISSUE TITLE
AWS cloud auto-join doesn't work with IPv6 addresses.

### ISSUE THREAD

**Issue by sigmaris** [hashicorp/nomad#24608]
### Nomad version

```
Nomad v1.9.3
BuildDate 2024-11-11T16:35:41Z
Revision d92bf1014886c0ff9f882f4a2691d5ae8ad8131c
```

### Operating system and Environment details

We have Nomad running on Fedora 40 in AWS, in a dual-stack VPC with an AWS-allocated IPv6 block - the Nomad servers and clients are assigned IPv6 addresses and advertise them for http, rpc and serf.

We are not using Consul.

### Issue

We are trying to join clients outside AWS to the server cluster in AWS, using IPv6.

When using the Cloud auto-join feature, and specifying that **go-discover** should use IPv6 addresses, the Nomad clients cannot connect to the servers, as it seems like the format of IPv6 addresses produced by **go-discover** isn't accepted by Nomad.

### Reproduction steps

* Set up a Nomad server cluster in AWS VPC with IPv6 enabled (dual stack)
* Configure the Nomad servers to advertise IPv6 addresses as described in https://developer.hashicorp.com/nomad/docs/operations/ipv6-support.
* Give the Nomad server EC2 instances an identifiable tag e.g. nomad-cluster=something.
* Configure a Nomad client to use Cloud auto-join to find by tag and join the server cluster, using IPv6 addresses, e.g. with this configuration: `retry_join = ["provider=aws region=eu-west-1 addr_type=public_v6 tag_key=nomad-cluster tag_value=something"]`.
* Start the Nomad client.

#### Expected Result

The Nomad client should discover the IPv6 addresses of the servers and connect to them.

#### Actual Result

We see in the client logs (below) that the clients seem to discover the IPv6 addresses OK, but then Nomad does not accept them due to the address format - I believe **go-discover** should be adding square brackets around the addresses before passing them to Nomad:

### Job file (if appropriate)

N/A

### Nomad Client logs (if appropriate)

```
   2024-12-04T18:02:55.473Z [DEBUG] agent.joiner: discover-aws: Found ip addresses: [2a05:d018:1f18:f300:61e0:6696:db81:77b 2a05:d018:1f18:f301:b3f:c4b4:d61f:6a31 2a05:d018:1f18:f301:3631:4790:7b7c:15d1 2a05:d018:1f18:f305:c24d:3416:b527:9cf0 2a05:d018:1f18:f302:8c1b:9a43:3d7a:3d73]
    2024-12-04T18:02:55.473Z [DEBUG] client: ignoring server due to resolution error: error="address 2a05:d018:1f18:f301:b3f:c4b4:d61f:6a31: too many colons in address" server=2a05:d018:1f18:f301:b3f:c4b4:d61f:6a31
    2024-12-04T18:02:55.473Z [DEBUG] client: ignoring server due to resolution error: error="address 2a05:d018:1f18:f300:61e0:6696:db81:77b: too many colons in address" server=2a05:d018:1f18:f300:61e0:6696:db81:77b
    2024-12-04T18:02:55.474Z [DEBUG] client: ignoring server due to resolution error: error="address 2a05:d018:1f18:f301:3631:4790:7b7c:15d1: too many colons in address" server=2a05:d018:1f18:f301:3631:4790:7b7c:15d1
    2024-12-04T18:02:55.474Z [DEBUG] client: ignoring server due to resolution error: error="address 2a05:d018:1f18:f302:8c1b:9a43:3d7a:3d73: too many colons in address" server=2a05:d018:1f18:f302:8c1b:9a43:3d7a:3d73
    2024-12-04T18:02:55.474Z [DEBUG] client: ignoring server due to resolution error: error="address 2a05:d018:1f18:f305:c24d:3416:b527:9cf0: too many colons in address" server=2a05:d018:1f18:f305:c24d:3416:b527:9cf0
    2024-12-04T18:02:55.474Z [WARN]  agent.joiner: join failed:
  error=
  | 5 errors occurred:
  | \t* address 2a05:d018:1f18:f301:b3f:c4b4:d61f:6a31: too many colons in address
  | \t* address 2a05:d018:1f18:f300:61e0:6696:db81:77b: too many colons in address
  | \t* address 2a05:d018:1f18:f301:3631:4790:7b7c:15d1: too many colons in address
  | \t* address 2a05:d018:1f18:f302:8c1b:9a43:3d7a:3d73: too many colons in address
  | \t* address 2a05:d018:1f18:f305:c24d:3416:b527:9cf0: too many colons in address
  |
   retry=30s
```

**Comment by tgross** [comment]
Hi @sigmaris! I traced this down to our [`resolveServer`](https://github.com/hashicorp/nomad/blob/v1.9.3/client/rpc.go#L444-L462) on the client. The function doesn't expect to be receiving IPv6 addresses without brackets... [we even have a test case covering that.](https://github.com/hashicorp/nomad/blob/v1.9.3/client/rpc_test.go#L132-L136).

We could probably fix this upstream in go-discover, but at this point that'd likely be a breaking change for go-discover consumers. Returning `[]string` and not `[]net.Addr` from [`Discover.Addrs()`](https://pkg.go.dev/github.com/hashicorp/go-discover?utm_source=godoc#Discover.Addrs) wasn't an ideal choice. 

What we can do on the Nomad side is preemptively wrap the addresses in `[]` if they can be parsed as IPv6 addresses and don't have a leading `[`. That'll still break if we were to get an unwrapped IPv6 address with a port, but that's just plain ol' malformed and there's not much we can do about that. It doesn't look like we can get that sort of thing from go-discover. I'll work up a patch for this.

The servers use a different code path for joining each other (via the [serf](https://github.com/hashicorp/serf) library). For clarity, you're not using `go-discover` for having the servers discover each other -- they're using the IPv6 address directly?

**Comment by tgross** [comment]
>  That'll still break if we were to get an unwrapped IPv6 address with a port, but that's just plain ol' malformed and there's not much we can do about that.

After some quick hacking on this, I realized that IPv6 shortening via `::` makes it impossible to detect that case... we end up with an IP address like `[2001:db8::1:4647]:4647`. So we might need to do this "closer" to the go-discover interface. I'll hack on this some more and report back next week.

**Comment by sigmaris** [comment]
> The servers use a different code path for joining each other (via the [serf](https://github.com/hashicorp/serf) library). For clarity, you're not using go-discover for having the servers discover each other -- they're using the IPv6 address directly?

We are actually using the same `retry_join = ["provider=aws tag_key=nomad-cluster tag_value=something"]` but *without* the `addr_type=public_v6` part; the servers discover each others' private IPv4 addresses and connect to each other, that part seems to work fine. However, we can't use that method for clients in other cloud providers since the IPv4 addresses are only reachable in the VPC in AWS.

**Comment by tgross** [comment]
Fix is up here: https://github.com/hashicorp/nomad/pull/24649
