### ISSUE TITLE
Periodic jobs continue to be rescheduled even if it fails

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/nomad#2460]
### Nomad version
Nomad v0.5.2

### Operating system and Environment details
Ubuntu 16.04           4.4.0-66-generic #87-Ubuntu
### Issue
I have set my periodic job to prohibit overlap and not run if it fails but it continues to run after failing and there are many periodic jobs running now.

`nomad status my-task`
```
my-task/periodic-1490023200  running
my-task/periodic-1490023500  running
my-task/periodic-1490024100  running
my-task/periodic-1490024700  running
my-task/periodic-1490028000  running
my-task/periodic-1490028300  running
my-task/periodic-1490028600  running
my-task/periodic-1490028900  dead
my-task/periodic-1490029500  dead
```

`nomad status my-task/time`
```
724b11d7  b75254f0  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:09:03 PDT
c619ebbd  d3a3fd60  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:08:51 PDT
21538276  1beb3e90  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:08:38 PDT
499cfd19  823c479f  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:08:24 PDT
88550bec  cd75ad63  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:08:14 PDT
5480f9a4  cd986ef0  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:08:09 PDT
08611be5  3778b23b  25b035ff  my-task-c2ee1822  run      failed  03/20/17 15:07:52 PDT
```

### Reproduction steps
A periodic task that exits non zero. 

### Nomad Client logs (if appropriate)
    2017/03/20 20:05:00.373294 [WARN] client: error fetching stats of task my-task: stats collection hasn't started yet
    2017/03/20 20:05:00.875044 [INFO] client: task "my-task" for alloc "5cca574d-d9ff-7ba7-1712-099271780751" failed: Wait returned exit code 1, signal 0, and error Docker container exited with non-zero exit code: 1
    2017/03/20 20:05:00.875078 [INFO] client: Not restarting task: my-task for alloc: 5cca574d-d9ff-7ba7-1712-099271780751

### Job file (if appropriate)
```
    "Periodic": {
        "Enabled": true, 
        "ProhibitOverlap": true, 
        "Spec": "*/5 * * * *", 
        "SpecType": "cron"
    }, 
```

```
            "RestartPolicy": {
                "Attempts": 0, 
                "Delay": 25000000000, 
                "Interval": 300000000000, 
                "Mode": "fail"
            }, 
```

**Comment by dadgar** [comment]
Hey I just ran a cron that runs every five seconds with a command that fails after 10 seconds and it was behaving correctly:

```
nomad status
ID                           Type   Priority  Status
example                      batch  50        running
example/periodic-1490050150  batch  50        dead
example/periodic-1490050165  batch  50        dead
example/periodic-1490050180  batch  50        running
```

Server skipping:
```
2017/03/20 22:49:20.001530 [DEBUG] nomad.periodic: skipping launch of periodic job "example" because job prohibits overlap
2017/03/20 22:49:20.001582 [DEBUG] nomad.periodic: launching job "example" in 4.998428194s
```

Job File:
```
job "example" {
  datacenters = ["dc1"]
  type = "batch"
  periodic {
  	cron = "*/5 * * * * * *" 
	prohibit_overlap = true
  }
  group "cache" {
    count = 1
     restart {
       mode = "fail"
       attempts = 0
     }

    task "redis" {
      driver = "raw_exec"
      user = "foo"
      config {
        command = "/bin/bash"
        args = ["-c", "sleep 10 && exit 1"]
      }
   
      resources {
        cpu    = 500 # 500 MHz
        memory = 256 # 256MB
        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

Maybe try upgrading to 0.5.5, there were some fixes to the restart policy.

Can you show the status of one of the running ones and its alloc-status?

**Comment by sheldonkwok** [comment]
Sure, if it happens again I'll post the alloc-status. We'll take a look at moving to 0.5.5 as well.

**Comment by dadgar** [comment]
@sheldonkwok Sounds good! I am going to close this issue in the meantime then and we can open with more details 👍
