### ISSUE TITLE
Constraints: Add inverse of `distinct_hosts`

### ISSUE THREAD

**Issue by konnextv** [hashicorp/nomad#24610]
### Proposal
Add an inverse of `distinct_hosts` (`unique_host`?) to make it possible to co-locate task groups on the same node.

### Use-cases
Co-locate tasks on the same node without using a task group. A task group is suboptimal in my case because I have a task with real-time requirements and a change to other tasks in the group would cause it to re-allocate every time.

### Attempted Solutions
Using node meta seems hacky and breaks canary deployments.

Related Hashicorp discussion: https://discuss.hashicorp.com/t/schedule-tasks-on-the-same-node-but-configure-them-independently/71762

**Comment by tgross** [comment]
Hi @konnextv! This has been requested before (albeit with different language): https://github.com/hashicorp/nomad/issues/11066

I'm going to close this as a duplicate and crosslink from that issues.
