### ISSUE TITLE
Stop future allocations when job is deleted

### ISSUE THREAD

**Issue by geekodour** [hashicorp/nomad#24669]
I am unsure why this is not the default behavior, why doe we not cancel all pending and running allocation if the job itself is stopped and purged.

Eg. I have deleted the main job, i have these orphan allocations running around. Why this this even considered? I cannot think of any usecase that this behaviour would be useful.

![image](https://github.com/user-attachments/assets/75800626-a6b3-44e1-87f4-6ac070fc8b7e)

**Comment by geekodour** [comment]
sometimes I get pending values in negatives, i am not sure what's going on.

![image](https://github.com/user-attachments/assets/f099358e-720a-4000-9659-c15c02c1e272)


I am not sure if this is a bug or intended behavior etc so not able to get to the root of it

**Comment by geekodour** [comment]
![image](https://github.com/user-attachments/assets/49c9e7f0-8343-4753-aaa5-30d948d9c092)


Also https://developer.hashicorp.com/nomad/api-docs/jobs#list-job-allocations seems to not work with batch job (it seems)

apologies for dumping all of the issues here, I'll create separate issues later.

**Comment by tgross** [comment]
@geekodour I am unsure why this is not the default behavior, why doe we not cancel all pending and running allocation if the job itself is stopped and purged.

This is the default behavior, although for architectural reasons the allocations will be running on the clients briefly (depending on kill timeouts and the like). But I suspect you're seeing inconsistency in the UI. Can you verify the behavior is the same when hitting the API via the CLI?
