### ISSUE TITLE
In the UI, one job displays the job launches of another

### ISSUE THREAD

**Issue by agarfer1** [hashicorp/nomad#24666]
### Nomad version

Nomad v1.9.3
BuildDate 2024-11-11T16:35:41Z
Revision https://github.com/hashicorp/nomad/commit/d92bf1014886c0ff9f882f4a2691d5ae8ad8131c

### Operating system and Environment details

Ubuntu 24.04 x86-64

### Issue

(This has been happening since the last UI redesign on version 1.7 or 1.8)

job1 has had some job launches of it running, job2 hasn't, when switching from visiting job1 to job2, I can see the job launches of job1 in the list of job2.

### Reproduction steps

Create both jobs (batch and parameterized), launch one instance of job1, and in the same tab visit job2, the job launch of job1 will appear in job2.

#### Expected Result

Each job should only display its own job launches

#### Actual Result

Usually if a job has had no recent job launches, it displays the job launches of the previously visited job.

![image](https://github.com/user-attachments/assets/a82b9c19-1b54-4d38-a9d4-894267e9cb5c)

### Job file (if appropriate)

**#Job1**

```
job "ping1" {
  datacenters = ["*"]
  type        = "batch"
  
  parameterized {
    payload       = "forbidden"
    meta_optional = ["irrelevant"]
  }

  group "ping" {
    task "ping" {
      driver = "raw_exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "ping -c 100 -W 5 192.168.1.1"]
      }
    }
  }
}
```

**#Job2**
```
job "ping2" {
  datacenters = ["*"]
  type        = "batch"
  
  parameterized {
    payload       = "forbidden"
    meta_optional = ["irrelevant"]
  }

  group "ping" {
    task "ping" {
      driver = "raw_exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "ping -c 100 -W 5 192.168.1.1"]
      }
    }
  }
}
```

**Comment by philrenaud** [comment]
Hey @agarfer1, good find. I'll check into this asap.
