### ISSUE TITLE
Conflicting documentation about `disconnect` block

### ISSUE THREAD

**Issue by markasoftware-aqtc** [hashicorp/nomad#24702]
The example here: https://developer.hashicorp.com/nomad/docs/job-specification/disconnect shows the `lost_after` and `stop_after` parameters of the `disconnect` block being used together. However, the documentation for the `lost_after` parameter then says "This setting cannot be used with [stop_after](https://developer.hashicorp.com/nomad/docs/job-specification/disconnect#stop_after).". However, the documentation for `stop_after` says "Setting stop_after shorter than lost_after and replace = false at the same time is not permitted and will cause a validation error, because this would lead to a state where no allocations can be scheduled." which once again implies that `stop_after` and `lost_after` can be used together.

The documentation should be clarified as to whether `stop_after` and `lost_after` can be used together.

**Comment by tgross** [comment]
Hi @markasoftware-aqtc! I just checked the code. The docs are wrong in a couple ways for sure:
* Using `stop_after` and `lost_after` together is definitely invalid. It will return the error "Disconnect cannot be configured with both lost_after and stop_after"
* The `stop_after` field is actually named `stop_on_client_after`!

I suspect the design changed slightly along the way and we missed updating the docs to match. I'll mark this to get fixed.

**Comment by aimeeu** [comment]
@tgross I created an internal ticket for this and will address it this week.

**Comment by aimeeu** [comment]
fix has been published
