### ISSUE TITLE
[documentation] Rolling update mechanism targeting scope

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#2472]
Reading the docs it's unclear whether serial upgrades target task groups, individual tasks or both.

Here both groups and tasks are mentioned:
https://www.nomadproject.io/docs/operating-a-job/update-strategies/rolling-upgrades.html

The jobspec doc however only references tasks:
https://www.nomadproject.io/docs/job-specification/update.html

Reading the first link I get the impression TG is needed for a serial rollout.
The second link implies a rolling upgrade on single group with multiple tasks.

Could the functionallity and scenarios perhaps be clarified somewhat?

**Comment by dadgar** [comment]
Thanks for bringing this to our attention! Fixed via d8936bdafaa5af49fb81be1b5e4ce3d9ed3813c7
