### ISSUE TITLE
Feature request - count variable

### ISSUE THREAD

**Issue by yellowmegaman** [hashicorp/nomad#2499]
Everything's working great.

Can you please add `count` to the env variables? So i can pass desired ( and probably final) amount of tasks to application? 

In my case i'd like to pass count to app and wait for all of them to be up to proceed with internal logic.

Something like `NOMAD_TASK_COUNT`

**Comment by jippi** [comment]
Seem related to https://github.com/hashicorp/nomad/issues/1942

**Comment by jippi** [comment]
The problem is that it's not a fixed number, but highly dynamic, so the number won't update on existing allocations when you scale a group up, leading to wrong env{}

**Comment by yellowmegaman** [comment]
Well, then i'll just stick to templating env variable with same meaning. Thanks!
