### ISSUE TITLE
Support multiple statsite or statsd servers for telemetry

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#250]
I am interested in building a small cli interface to stream telemetry from my nomad agents. It would be wire-compatible with either statsite or statsd.

In such cases, it makes sense to be able to stream telemetry to multiple endpoints, because we might have a statsite or statsd server that actually ships the telemetry data to long-term storage and the cli interface streaming live telemetry to the user.

**Comment by cbednarski** [comment]
Thanks for the suggestion. We currently use statsite for monitoring and ETL separately, but we'd be happy to look at a PR to add this feature.

**Comment by dadgar** [comment]
This is something that can be supported upstream from Nomad. Your CLI could fanout the nomad telemetry to as many servers as you wanted. You could use something like the FanoutSink in this package: https://github.com/armon/go-metrics
