### ISSUE TITLE
[compile] PPC64 architecture

### ISSUE THREAD

**Issue by ngortheone** [hashicorp/nomad#2505]
Hi, am trying to compile nomad for PPC64 architecture and here is what i got
```
➜  nomad git:(103290a) make all
--> Running go generate
codecgen error: error running 'go run codecgen-main-5231.generated.go': exit status 2, console: # github.com/hashicorp/nomad/vendor/github.com/shirou/gopsutil/host
../../vendor/github.com/shirou/gopsutil/host/host_linux.go:141:22: undefined: sizeOfUtmp
../../vendor/github.com/shirou/gopsutil/host/host_linux.go:146:14: undefined: sizeOfUtmp
../../vendor/github.com/shirou/gopsutil/host/host_linux.go:148:9: undefined: utmp

command/agent/fs_endpoint.go:3: running "codecgen": exit status 1
make: *** [generate] Error 1
```

Here is my kernel and CPU info
```
➜  kubernetes git:(fff5156) uname -a
Linux soctb425 3.10.0-514.el7.ppc64 #1 SMP Fri Dec 2 22:53:03 GMT 2016 ppc64 ppc64 ppc64 GNU/Linux

➜  kubernetes git:(fff5156) cat /proc/cpuinfo
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 8
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

timebase	: 512000000
platform	: pSeries
model		: IBM,8284-22A
machine		: CHRP IBM,8284-22A
```

**My QUESTIONS are:**
* Is ppc64 big endian architecture supported? (If not - why? and will it be supported in future?)
* Is there any way to run nomad on PPC64?

**Comment by sean-** [comment]
No ppc isn't supported. If you want it to be supported there are a few dependencies that need to support PPC, including shirou/gopsutils. If you want to see it supported, you'll have to do the leg work to get the upstream vendors to support PPC. Because PPC is a 2nd of 3rd tier architecture, I don't think there will be any time spent on this otherwise.

**Comment by dadgar** [comment]
@ngortheone As mentioned by Sean it looks like there are some upstream libraries that need to be updated. Unfortunately PPC is not an architecture the core team is going to be targeting and as such I am going to close the issue. However, this doesn't mean Nomad can't work on PPC. It will just take some work to get it to build!
