### ISSUE TITLE
Nomad 0.5.6 doesn't work on MacOS Serria (10.12.3)

### ISSUE THREAD

**Issue by SebastianM** [hashicorp/nomad#2518]
### Nomad version
0.5.6

### Operating system and Environment details
MacOS Serria 10.12.3

### Issue

The newest patch release 0.5.6 doesn't work on my mac - when I run the binary, I get this output:

```
➜  Desktop ./nomad-0.5.6 
[1]    2872 killed     ./nomad-0.5.6
```

The previous release 0.5.5 runs fine. What I noticed is that the file size for 0.5.6 is much smaller compared to 0.5.5:

```
➜  Desktop ls -la
-rwxr-xr-x@  1 sebmueller  staff  37766908 14 Mär 13:56 nomad-0.5.5
-rwxr-xr-x@  1 sebmueller  staff  25594244 31 Mär 17:16 nomad-0.5.6
-rw-r--r--@  1 sebmueller  staff  10269922  4 Apr 17:00 nomad_0.5.5_darwin_amd64.zip
-rw-r--r--@  1 sebmueller  staff   7282634  4 Apr 16:47 nomad_0.5.6_darwin_amd64.zip
```

**Comment by dadgar** [comment]
Got bit by https://github.com/golang/go/issues/19734.

I have re-built and pushed that binary with the workaround of `go install -ldflags -s`. Thanks for reporting.
