### ISSUE TITLE
[bug] Nomad doesn't honor NETRC

### ISSUE THREAD

**Issue by Ashald** [hashicorp/nomad#2523]
### Nomad version
`0.5.6`

### Operating system and Environment details
`Centos 7`

`NETRC` environment variable set for the Nomad agent process.

### Issue
Nomad doesn't sue credentials from NETRC.

### Reproduction steps
1) Have a URI protected with basic auth
2) Put credentials into a NETRC file
3) Start Nomad agent with NETRC environment variable pointing to the file
4) Submit a job referencing the protected URI

### Nomad Client logs (if appropriate)
```
2017/04/05 17:16:51.381904 [DEBUG] client: failed to download artifact "https://acme.co/artifactory/my-repo/foobar.zip": bad response code: 401
```

**Comment by Ashald** [comment]
The issue is in `go-getter`: https://github.com/hashicorp/go-getter/pull/58

**Comment by dadgar** [comment]
@Ashald With that PR compiled into Nomad did it work?

**Comment by Ashald** [comment]
Yes

**Comment by dadgar** [comment]
@Ashald Nice I just merged that and will vendor into Nomad! Thanks!

**Comment by Ashald** [comment]
Thanks for quick feedback!
