### ISSUE TITLE
Publish metrics to Prometheus endpoint

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#2528]
A prometheus metrics endpoint for the nomad agents and servers would be great!

Is this something that is on the roadmap?

**Comment by dadgar** [comment]
Yeah it is on the roadmap. The underlying metrics library we use (https://github.com/armon/go-metrics) needs to be enhanced with a tag based API and a way to interact with pull based systems like prometheus

**Comment by Ashald** [comment]
and meantime there is https://github.com/Nomon/nomad-exporter

**Comment by TUIteamup** [comment]
Implemented in 0.7 and improved in 0.7.1

**Comment by dadgar** [comment]
@TUIteamup Thanks for bumping this! We can close this out now as it is implemented!

**Comment by marcosnils** [comment]
hey @dadgar I see that the metrics published in /v1/metrics are not the same as published in /v1/metrics?format=prometheus. I don't see any nomad specific metrics like allocations and stuff like that. Is this intentional and documented somewhere?

The only prometheus metrics I see are the golang specific ones.

**Comment by dadgar** [comment]
@marcosnils You need to enable the prometheus sink: https://www.nomadproject.io/docs/agent/configuration/telemetry.html#prometheus_metrics

**Comment by marcosnils** [comment]
@dadgar thx for the quick response. I was missing the publish_node_metrics, that's why it wasn't working. It feels "strange" though that you see the metrics through the `/v1/metrics` endpoint but you don't see them when you send the `format` param.

**Comment by dadgar** [comment]
@marcosnils We always collect metrics and store a small amount in memory so you can dump it via the CLI so the HTTP endpoint exposes the same source. The other external sinks need to be enabled.

**Comment by marcosnils** [comment]
@dadgar got it. Thx for clarifying
