### ISSUE TITLE
[DOCS] Docs on jobspec differs greatly between HCL and JSON regarding disk resource

### ISSUE THREAD

**Issue by dvusboy** [hashicorp/nomad#2530]
* `ephemeral_disk` stanza is completely missing in the [JSON documentation](https://www.nomadproject.io/docs/http/json-jobs.html).
* `DiskMB` is still listed under [`Resources`](https://www.nomadproject.io/docs/http/json-jobs.html#resources-1) of a `Task`. Whereas, under HCL [`resources`](https://www.nomadproject.io/docs/job-specification/resources.html), there is no mentioning of `disk` resource any more.

Can we please square these discrepancies? I'm getting a bit confused.

**Comment by dadgar** [comment]
Hey just pushed a fix. Thanks for bringing it to our attention. Also as you see discrepancies please feel free to submit a PR.

**Comment by dvusboy** [comment]
Thanks. In this case, I wasn't completely certain which way it should be.
