### ISSUE TITLE
Feature: Allow for specifying TLS host name

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#2539]
This is related to: https://github.com/hashicorp/nomad/commit/7ee2a1515badbdb56be9c8164534154a1d57e076#commitcomment-21699487

### Issue

For now nomad hardcores tls hostname to `server.xxx.nomad`, but in my case it would be useful to set it to something custom, so I can use tls certificate issued by 3rd party on real domain (like Let's encrypt).

Ideally I'd be able to configure nomad like so:

```
tls {
  http = true
  rpc  = true

  ca_file   = "ca.pem"
  cert_file = "nomad.pem"
  key_file  = "nomad-key.pem"

  verify_server_hostname = true
  server_hostname = "example.com"
}
```

or the server hostname would be fetched from certificate itself

Use case: Allow for easy access to nomad master's  HTTP API available under public domain without certificate issues when accessing via browser/curl, and at the same have `verify_server_hostname = true` for nomad agents. I'm fine with generating certificates per-server as let's encrypt makes it really easy.

**Comment by sheerun** [comment]
Alternative:

```
verify_server_domain = true
```

and make nomad read server_hostname from servers array passed to client config, e.g.:

```
lient {
  enabled = true
  servers = ["master1.example.com:4647", "master2.example.com:4647"]
}
```

**Comment by sheerun** [comment]
The second option would be better as I could set domain per-server

**Comment by schmichael** [comment]
Nomad's HTTP endpoint should not be exposed to the public Internet. Perhaps once it's possible to require a client certificate signed by the same CA for HTTP access it would be safe, but then it would be unsafe to use a public CA like Let's Encrypt (because anyone could grab a Let's Encrypt certificate and gain access to your cluster).

For Nomad's RPC endpoint used for intra-cluster communication verifying the hostname of a peer isn't actually useful in Nomad's security model. For example server1.example.com never cares if it's connecting to server2 or server3; only that it's connecting to a Nomad `server` agent in the correct `region`. Hostname based validation loses the role and location based validation.

You can put both `{role}.{region}.nomad` style names and hostnames on certificates to ease making HTTP requests from curl or your own code. Someday we'd like to allow certificate generation with [Vault](https://www.vaultproject.io/), but I don't know if Let's Encrypt will ever make sense. The use cases are just awfully different.

**Comment by sheerun** [comment]
afaik TLD in nomad doesn't perform authentication, just encryption, so it shoudn't matter I use public certificate authority. as for the role-based TLS I can do the same with public certificates `{role}.{regsion}.example.com`

**Comment by sheerun** [comment]
"We use the name to verify roles. We do this so that a compromised Nomad client can not masquerade as a Nomad Server to the whole cluster and have access to privileged data. This is just another defense in depth mechanism."

I think it would be more appropriate to have some TLD to verify against. For example:

```
verify_agent_domains = ["agent.example.com"]
```

then agents would need to issue certificates from `agent.example.com` (role-based) or subdomains like `agent4.agent.example.com` (if someone prefers like me). `{role}.{region}.nomad` seems really opinionated.

**Comment by schmichael** [comment]
You can accomplish what you're suggesting today by putting both `{role}.{region}.nomad` and hostnames on the certificate you use on Nomad agents. That way Nomad nodes will properly authenticate the role and region when communicating over RPC and HTTP clients can properly authenticate the name of the host they're connecting to.

We're considering allowing a configurable TLD to unify the two naming schemes, but it's not functionally different from putting both styles of names on your certificates today.

We're aware the custom naming scheme makes using TLS with the HTTP API awkward and are planning on improving it. For now including multiple names on your certificates is the best option.

**Comment by sheerun** [comment]
The thing is no public certificate authority will put `{role}.{region}.nomad` in the same certificate.

**Comment by schmichael** [comment]
Using a public CA will definitely not be supported before Nomad supports ACLs as using a private CA provides coarse grained access control.

I don't think Let's Encrypt will issue certificates for private servers anyway, and exposing Nomad's APIs to the Internet is not safe.

**Comment by smitjainsj** [comment]
@schmichael  : 
Actually,  I agree to @sheerun  that if we can have argument to provide `domain` name in the cert it self that would be very useful. what is the certificate authority which generates the certs only allow specific domains to be created like `*.example.com` and NOT `*.nomad` . In this case, creating certs from registered CA is not possible. Please correct me if I missed something.

**Comment by schmichael** [comment]
@sheerun's suggestions are viable, but we do not have plans to add that functionality to our mTLS implementation at this time.

I believe the suggestion was meant to solve 2 distinct issues:

1. Generating certs and managing a CA is difficult.
2. Accessing an API with a private-CA-signed cert is difficult.

As for 1: We may go a route similar to Consul where Nomad has [its own builtin CA](https://www.consul.io/docs/connect/ca/consul.html) or can [delegate certificate creation to Vault](https://www.consul.io/docs/connect/ca/vault.html).

As for 2: Using a proxy server with a public cert is recommended (although we should document that and/or probably provide a job file for one). A proxy such as nginx can not only translate from a public certificate on a public address to [a private certificate to the upstream Nomad cluster](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/), but nginx is also designed from the ground up to be exposed to the Internet.

Until we validate Nomad's HTTP server with TLS enabled is safe to expose to the Internet, problem 2 above is best solved with a proxy.
