### ISSUE TITLE
Support for hot-reloads

### ISSUE THREAD

**Issue by hauleth** [hashicorp/nomad#2542]
Currently I am working on app that runs on Erlang BEAM virtual machine. [This VM is known for it good support for hot-reloads](http://erlang.org/doc/reference_manual/code_loading.html) and I am wondering if it is possible to make use of this when scheduling jobs using Nomad? My use case (dynamically create instance for client on demand) suits Nomad perfectly and I would love to see that this cooperation could be even tighter.

**Comment by dadgar** [comment]
Hey you would have to orchestrate this outside of Nomad. Nomad operates in a declarative versioned fashion and as such is not well suited to hot-reloading end applications. It would be cool but is unfortunately a bit out of scope for Nomad! Cool idea tho 👍

**Comment by hauleth** [comment]
In my case it could be "partially" simulated via using script that would look like:

```
#!/bin/sh

# eventual SIGINT handler

otp_app start

while true; do :; done
```

But it seems like a hack and could lead to orphaned processes in case of `SIGKILL`. My proposal would be something like allowing Nomad to watch for 2 different PIDs and/or specifying more complex kill commands that would allow to handle more complex shutdown cases. Ex. allowing to use other signal on upgrade than on termination.

**Comment by dadgar** [comment]
We will eventually allow users to specify the shutdown signal and to send signals to individual tasks. So that could be useful in the future.

**Comment by hauleth** [comment]
What would also be needed that it would be possible to force Nomad to pin running instance to server, so update would be in place. This is needed for our projects as we are handling running voice communications and we cannot disconnect our users during call. Our technology (Erlang) supports hot-reloads but Nomad doesn't. Ideally there could be additional task driver `erlang` which would implement such features.

**Comment by dadgar** [comment]
@hauleth You may want to wrap your Erlang program with an HTTP handler that can accept a new Erlang job and hot-reloads it itself. Nomad will not attempt to support this in any reasonable time-frame.

**Comment by hauleth** [comment]
@dadgar you haven't written Erlang application yet, do you? I highly encourage you, it is real fun and eye opener.

The point is that your "HTTP handler" is written in Erlang and ran in the same VM that your application and you can reload modules while they are handling network connections (ex. http://erlang.org/doc/reference_manual/code_loading.html#id89620 or https://github.com/bitwalker/distillery/blob/master/docs/Upgrades%20and%20Downgrades.md). In our current application workflow proposed by you won't work, as I do not handle HTTP connection which I can finish and then next connection will be made to new application. I am handling live voice communication (like Discord or Skype) and I cannot end them during deploy. I need to switch code while keeping my connection live to the handler (and simultaneously drop as few packages as possible).

I have tried looking into `java` driver and it seems that it want to achieve the same thing. I am not gopher, but from my understanding there is already [method](https://github.com/hashicorp/nomad/blob/11200cdfd2b693f0b99760b078359b348bcc4d71/client/driver/java.go#L384) to achieve in-place upgrades (where as "in-place" I mean code reload, not hot swap).

My main point is that I could probably find a hackish way to achieve what I need using Nomad, however I would need something that would allow me to instruct my jobs to not do hot swap, but instruct them to keep everything in place.
