### ISSUE TITLE
[question] Autoscale strategy

### ISSUE THREAD

**Issue by drscre** [hashicorp/nomad#2558]
We are using Nomad to deploy microservices. 
We would like to automatically scale the number of nodes on which they are running.

Upscaling seems to be fairly simple.  
If the load on some service raises - increase the number of service copies. If they don't fit into existing nodes (placement failure) - launch a new node. 
Is there a way to tell Nomad to evenly distribute services across the nodes after adding a new node to spread the load?

Downscaling is less obvious. 
We can decrease the number of service copies when the load on that service drops. But how can we tell Nomad to repack services tight, so that we can shut down exscessive nodes?

**Comment by dadgar** [comment]
@drscre For questions please prefer the mailing list.

You should detect node with the least allocations on it and mark that node for draining. You can then kill the node once Nomad migrates the allocations off the node.

**Comment by drscre** [comment]
@dadgar Draining will all drain allocations even if they don't fit on remaining nodes.

**Comment by dadgar** [comment]
Ah yeah assuming you don't know whether they will fit it is a bit harder. There currently is no repacking.
