### ISSUE TITLE
[question] specifying Docker Network(s) container is using

### ISSUE THREAD

**Issue by sjwl** [hashicorp/nomad#2561]
Is there a corresponding Docker configuration setting as in Terraform Docker Provider attribute: 

https://www.terraform.io/docs/providers/docker/r/container.html#networks

`networks` - (Optional, set of strings) Id of the networks in which the container is.

**Comment by dadgar** [comment]
Here ya go: https://www.nomadproject.io/docs/drivers/docker.html#network_mode. We do not really have first class support for non-host/bridge networks on docker so Nomad won't orchestrate any other networks for you.

**Comment by sjwl** [comment]
@dadgar thanks so much for the quick response!

I feel `network_mode` is analogous to Terraform Docker Provider's own `network_mode`, is this correct?  If so, then that means there is no equivalent to `networks` for Nomad Docker driver?

[excerpt from Terraform doc]
```
network_mode - (Optional, string) Network mode of the container.

networks - (Optional, set of strings) Id of the networks in which the container is.
```

**Comment by dadgar** [comment]
@sjwl That is correct.
