### ISSUE TITLE
[question] Nomad cluster requirements 

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/nomad#2564]
The Nomad cluster server requirements defined on the official [page](https://www.nomadproject.io/guides/cluster/requirements.html) are 8+ cores, 32 GB+ of memory, 80 GB+.
Based on the architecture described with in-memory database, disk snapshots and high communication between nodes, those numbers makes sense to me.

Now, we have been running a Nomad cluster with 5 servers and 1-250 clients (scale in/out based on the load). This cluster can run a max of 1000 Docker containers or ~800 Nomad batch jobs (this number varies since there job with a one or two tasks each). The servers are m4.xlarge (AWS EC2) with 4 vCPUs, 16 GiB of memory and 40 GiB for the root volume (same used for Nomad data).
Here's the average usage across all servers:
CPU: under 5% and it reached a max of 10% usage.
Memory: ~1.2 GiB.
Disk: ~1.5 GiB.

My question: is our cluster load just lower comparing to what's recommended on the official page and we should just keep with our setup? Could you give some numbers to exemplify what is considered high load cluster as described on the requirements page?

**Comment by dadgar** [comment]
Hey, this has come up with quite a few times so I will update the documentation to clarify. However to answer your question, those suggestions are for very large clusters of thousands of nodes and high scheduling volume. For stable clusters not as much resources are necessary.

So you are more than fine keeping your cluster as is.
