### ISSUE TITLE
JSON API request to create job response with "Job ID hasn't been provided" even when "ID" field is present

### ISSUE THREAD

**Issue by hauleth** [hashicorp/nomad#2567]
### Nomad version

    Nomad v0.5.6

### Operating system and Environment details

    Darwin niuniobook 16.6.0 Darwin Kernel Version 16.6.0: Tue Apr  4 18:01:19 PDT 2017; root:xnu-3789.60.15~4/RELEASE_X86_64 x86_64

### Issue

When I am sending this JSON to `POST /v1/jobs`:

```json
{
  "Job": {
    "Job": {
      "Type": "batch",
      "TaskGroups": [
        {
          "Tasks": [
            {
              "leader": false,
              "User": null,
              "Services": null,
              "Name": "say",
              "Meta": {},
              "Driver": "raw_exec",
              "DispatchPayload": false,
              "Config": {
                "command": "say",
                "args": [
                  "my",
                  "name"
                ]
              },
              "Artifacts": []
            }
          ],
          "Name": "say",
          "Meta": {},
          "Count": 1,
          "Constraints": []
        }
      ],
      "Priority": 50,
      "Payload": null,
      "Name": "sample",
      "Meta": {},
      "ID": "1",
      "Datacenters": [
        "dc1"
      ],
      "Constraints": [],
      "AllAtOnce": false
    }
  }
}
```

In response I get `Job ID hasn't been provided`

### Reproduction steps

HTTPie request:

    http http://localhost:4646/v1/jobs Job:='{"Job":{"Type":"batch","TaskGroups":[{"Tasks":[{"leader":false,"User":null,"Services":null,"Name":"say","Meta":{},"Driver":"raw_exec","DispatchPayload":false,"Config":{"command":"say","args":["my","name"]},"Artifacts":[]}],"Name":"say","Meta":{},"Count":1,"Constraints":[]}],"Priority":50,"Payload":null,"Name":"sample","Meta":{},"ID":"1","Datacenters":["dc1"],"Constraints":[],"AllAtOnce":false}}'

### Nomad Client/Server

Nomad is running with `-dev` flag

    2017/04/18 02:47:41.250151 [DEBUG] worker: ack for evaluation 6eca7b65-abca-4fa2-945d-3981519bcd78
    2017/04/18 02:47:41.250198 [DEBUG] worker: dequeued evaluation 3b3fc765-dd4b-5faa-b19a-f652d48f3d71
    2017/04/18 02:47:41.250235 [DEBUG] sched.core: node GC: scanning before index 0 (24h0m0s)
    2017/04/18 02:47:41.250272 [DEBUG] worker: ack for evaluation 3b3fc765-dd4b-5faa-b19a-f652d48f3d71
    2017/04/18 02:47:42 [DEBUG] memberlist: TCP connection from=127.0.0.1:50821
    2017/04/18 02:47:43.271532 [DEBUG] http: Request /v1/status/peers (2.319553ms)
    2017/04/18 02:47:44.196752 [DEBUG] http: Request /v1/agent/servers (202.564µs)
    2017/04/18 02:47:44.520111 [ERR] http: Request /v1/jobs, error: Job ID hasn't been provided
    2017/04/18 02:47:44.520142 [DEBUG] http: Request /v1/jobs (101.825µs)
    2017/04/18 02:47:52 [DEBUG] memberlist: TCP connection from=127.0.0.1:50830

**Comment by dadgar** [comment]
@hauleth Hey there are two small issues:

1) DispatchPayload is an object and not a boolean. You can just change that to null or delete the line
2) You have wrapped the job one too many times. Remove the outer "Job"

Hope that helps! Btw I ran the job with the changes above and it is accepted 👍
