### ISSUE TITLE
Nomad CLI unaware of TLS. Need dns fqdn resolution in address field for cert validation.

### ISSUE THREAD

**Issue by Cryson** [hashicorp/nomad#2568]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
RHEL 6

### Issue
When TLS is enabled, nomad cli is unaware TLS is enabled and stops working correctly.

root@blah:/# nomad status
Error querying jobs: Get http://127.0.0.1:4646/v1/jobs: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

To get it to work you have to do the following:
nomad status -address=https://127.0.0.1:4646  -tls-skip-verify

Nomad CLI should be aware TLS is enabled and use the https address instead of the http default. This would also need to allow for dns fqdn in the address by default (preferably enable-dns-expose toggle in nomad.conf to expose dns name rather than IP on such commands) instead of IP for certificate validation.

### Reproduction steps
Enable TLS in nomad

**Comment by dadgar** [comment]
Hey,

By default Nomad uses http. You should just export an environment variable to have Nomad use https. `export NOMAD_ADDR=https://127.0.0.1:4646`.

Nomad will load systems CAs but if it isn't there you must specify it (also available as a env var so it can be exported).

**Comment by Cryson** [comment]
That would resolve the issue for the CLI, but the issue remains elsewhere, if you query RPC to pull statistics you will get something similar to the following:

Unable to fetch node stats for blahblahblah (Get http://127.0.0.1:4646/v1/node/02d76028-228e-02bb-4083-3d0385944f4d?region=cloudbolt&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02")

Because nomad isn't exposing dns and there is no way to toggle that.
