### ISSUE TITLE
CAS for Job HTTP API Endpoint

### ISSUE THREAD

**Issue by Ashald** [hashicorp/nomad#2569]
It'd be great if Nomad supported `compare-and-set` paradigm for Job api endpoint. This is very handy when job can be updated by number of external processes.

**Comment by dadgar** [comment]
Hey @Ashald,

We do already have this. I pushed documentation that was missing: https://github.com/hashicorp/nomad/commit/8ad95182a09945cdf2d6797af305d5bbdc1ce7a1

You can also use it via the CLI: `nomad run -check-index=<index>`

Let me know if you need any help using it 👍

**Comment by Ashald** [comment]
Thanks for quick reply! It's great that it's already there - appreciate the doc update!
