### ISSUE TITLE
Error loading CA File: Couldn't parse PEM in

### ISSUE THREAD

**Issue by SubhashishPanda** [hashicorp/nomad#2571]
`I added tls to my nomad cluster following the tutorial on "https://www.nomadproject.io/docs/agent/encryption.html" `
and enabled http and rpc encryption

I copied the following files to a folder:
1) ca.pem
2) ca-key.pem
3) nomad.pem
4) nomad-key.pem

Whenever i issue command 
sudo nomad server-member -ca-cert= "file"

### Nomad v0.5.4 output
ubuntu@ip-172-31-26-98:~$ sudo nomad server-members -ca-cert=./ssl/nomad.pem
Error querying servers: Get http://127.0.0.1:4646/v1/agent/members: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

ubuntu@ip-172-31-26-98:~$ sudo nomad server-members -ca-cert=./ssl/nomad-key.pem
Error initializing client: Error loading CA File: Couldn't parse PEM in: ./ssl/nomad-key.pem

ubuntu@ip-172-31-26-98:~$ sudo nomad server-members -ca-cert=./ssl/ca.pem
Error querying servers: Get http://127.0.0.1:4646/v1/agent/members: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

ubuntu@ip-172-31-26-98:~$ sudo nomad server-members -ca-cert=./ssl/ca-key.pem
Error initializing client: Error loading CA File: Couldn't parse PEM in: ./ssl/ca-key.pem

### Nomad Server configuration 
log_level = "DEBUG"

data_dir = "/tmp/server"

bind_addr ="0.0.0.0"

server {
    enabled = true
    encrypt = "dprJIHoCDTz41vW9nXZteA=="
    # Self-elect, should be 3 or 5 for production
   bootstrap_expect = 2

}
tls {
  http = true
  rpc  = true

  ca_file   = "/home/ubuntu/ssl/ca.pem"
  cert_file = "/home/ubuntu/ssl/nomad.pem"
  key_file  = "/home/ubuntu/ssl/nomad-key.pem"
}

advertise {
  
  http = "35.154.88.43"
  rpc  = "35.154.88.43"
  serf = "35.154.88.43"
}

### Nomad Client configuration
log_level = "DEBUG"
datacenter ="dc1"
data_dir = "/tmp/client"
bind_addr = "0.0.0.0"
client {
    enabled = true
    servers = ["35.154.88.43:4647"]
}
tls{
  http = true
  rpc  = true
  ca_file   = "/home/ubuntu/ssl/ca.pem"
  cert_file = "/home/ubuntu/ssl/nomad.pem"
  key_file  = "/home/ubuntu/ssl/nomad-key.pem"

  verify_server_hostname = true
}
ports {
    http = 5656
}

**Comment by schmichael** [comment]
Since the nomad command line tool doesn't read the configuration file, you need to set environment variables to tell Nomad to use `https` instead of `http`:

```sh
export NOMAD_ADDR=https://127.0.0.1:4646

# You can also set an environment variable for the CA certificate 
export NOMAD_CACERT=/path/to/ca.pem

# The nomad command should now work!
nomad server-members
```

The documentation should really mention this! I'll add it to the page you were referencing: https://www.nomadproject.io/docs/agent/encryption.html

**Comment by SubhashishPanda** [comment]
Thanks @schmichael , that solved the issue
