### ISSUE TITLE
Missing consul keys: no hint in alloc-status

### ISSUE THREAD

**Issue by stefreak** [hashicorp/nomad#2578]
If you reference consul kv keys from the template stanza, nomad will notice if they don't exist yet and the task is pending until the key is there.

This is fine, but alloc-status should inform the user about this fact.

### Nomad version
Output from `nomad version`
`Nomad v0.5.6`

### Operating system and Environment details
Ubuntu 16.04

### Issue
nomad alloc-status should give a hint if nomad is waiting for missing information in consul

### Reproduction steps
template stanza with the following template:
```
 {{ key "this/key/is/missing" }}
```

### Nomad Server logs (if appropriate)
```
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) missing data for 1 dependencies
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) diffing and updating dependencies
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) kv.block(scorecard/lastIncident) is still needed
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) kv.block(scorecard/midonetCountdown) is still needed
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) kv.block(scorecard/toilworkPercent) is still needed
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) kv.block(scorecard/errorbudget) is still needed
Apr 20 11:47:27 nomad-node0 nomad[1209]:     2017/04/20 11:47:27 [DEBUG] (runner) watching 4 dependencies
```

**Comment by dadgar** [comment]
Yep definitely on the roadmap!

**Comment by csawyerYumaed** [comment]
I just got hit by this today. I was like UGH why is my job stuck in pending.... This is the relevant logs from the nomad agent node running the job... so it's not even out on the agent to say anything.
```

    2017/07/19 09:51:50 [INFO] (runner) creating new runner (dry: false, once: false)
    2017/07/19 09:51:50 [INFO] (runner) creating watcher
    2017/07/19 09:51:50 [INFO] (runner) starting
    2017/07/19 09:51:50 [INFO] (runner) initiating run
```

**Comment by stefreak** [comment]
Yeah it seems that it's only logged with debug loglevel.
