### ISSUE TITLE
[question]/[bug] Dropbox link as jar artifact source fails.

### ISSUE THREAD

**Issue by mandeepshetty** [hashicorp/nomad#2581]
### Edit
I replaced the Dropbox link with a link to locally hosted Python webserver and it started working.
Why would Dropbox not work? 
### /Edit

Nomad v0.5.6 on Linux ubuntu 4.9.15-x86_64 Ubuntu 16.04.1 LTS

I'm trying to run a simple Java jar as a task. I've hosted the file on Dropbox. One Nomad agent is running in `sudo -dev` mode.  Consul is running in `sudo -dev` mode as well..
The job file is a modified `nomad init` file.

When [this jobfile](https://gist.github.com/mandeepshetty/4f45a4a8141fd52652b0b34a0de76d45) with the md5 checksum is used, the agent fails to download the jar because of a difference in the checksum. Every time it tries to download the jar, it [computes a different md5](https://gist.github.com/mandeepshetty/633c4ea19f7d6d1673a400088f5eb012#file-agent-log-md5-var-L82). 
Maybe it is not downloading the jar, but the webpage? wget downloads the jar correctly but I did not try with go-getter.

With the checksum removed, as in [this job file](https://gist.github.com/mandeepshetty/88bd8297bacdd7d258b38bfc81d76497), the error is simply that the task exit with exit code 1. There is no output when I run `nomad logs <alloc_id>`

### Steps to reproduce.
1. `sudo consul agent -dev`
2. `sudo nomad agent -dev`
3. `nomad run example.nomad` where exaple.nomad are the linked modified job files for Java.

### Nomad Server logs (if appropriate)
[Changing md5 server logs](https://gist.github.com/mandeepshetty/633c4ea19f7d6d1673a400088f5eb012)

### Job file (if appropriate)
[Job file with artifact checksum](https://gist.github.com/mandeepshetty/4f45a4a8141fd52652b0b34a0de76d45)
[Job file with NO artifact checksum](https://gist.github.com/mandeepshetty/88bd8297bacdd7d258b38bfc81d76497)

**Comment by dadgar** [comment]
Hey you aren't downloading the artifact you are downloading some HTML so the page must be changing a bit with each request. To download the artifact: `https://www.dropbox.com/s/3u7pf5im1mo09wx/main.jar?dl=1`
