### ISSUE TITLE
Nomad unable to connect to Consul over unix sockets

### ISSUE THREAD

**Issue by shilov** [hashicorp/nomad#2594]
Nomad is unable to communicate with consul clients over unix sockets.

### Nomad version
0.5.6

### Operating system and Environment details
MacOS, Debian

### Issue

Nomad can't connect to consul over a unix socket because it does not account for addresses starting with `unix://`

### Reproduction steps

Configure the consul agent to listen for client requests on a unix socket, e.g.: 

     "addresses": {
         "http": "unix:///tmp/consul/consul.sock"
     }

Use the same value in the consul config address for nomad clients.

### Nomad Client logs (if appropriate)

> client.consul: error reaping services in consul: Get http://%2Ftmp%2Fconsul%2F%2Fconsul.sock/v1/agent/services: dial tcp: lookup /tmp/consul/consul.sock: no such host

**Comment by schmichael** [comment]
Confirmed Nomad isn't able to talk to Consul over a Unix socket in 0.5.6. I'll make sure to get it in for 0.6.

**Comment by schmichael** [comment]
Attached is a build with the fix if you're interested in testing.

[linux_amd64-lxc.zip](https://github.com/hashicorp/nomad/files/985026/linux_amd64-lxc.zip)

**Comment by schmichael** [comment]
And the normal 64bit Linux release: 
[linux_amd64.zip](https://github.com/hashicorp/nomad/files/985028/linux_amd64.zip)

**Comment by shilov** [comment]
Confirmed that it's working. Thanks for taking the time to fix this, and for making it easy to test by uploading a dev build.
