### ISSUE TITLE
[question]task-artifact stanza, authenticate with nexus

### ISSUE THREAD

**Issue by parismorali** [hashicorp/nomad#2601]
Getting 401 from nexus when trying to get a artifact.jar for task-artifact in nomad job spec file.
`artifact {
    source = "http://nexus.xyz.com:8081/repository/artifact.jar"
    options {
      checksum = "md5:507a58c53245234512345234"
      user = "username"
      password = "password"
    }
}`

This works fine
` wget --user=username --password=password "http://nexus.xyz.com:8081/repository/artifact.jar"`

How would the artifact stanza allow this kind of spec for retrieving the jar from nexus?

### Nomad version
Nomad v0.5.4

**Comment by dadgar** [comment]
Hey,

I just pushed some docs to make it clearer: https://github.com/hashicorp/go-getter#http-http

What you need to do is:

```
artifact {
  source = "http://username:password@nexus.xyz.com:8081/repository/artifact.jar"
  options {
    checksum = "md5:507a58c53245234512345234"
  }
}
```

**Comment by parismorali** [comment]
Thanks @dadgar.
I tried to PR an update to the doc but I'm guessing not anyone is allowed to create a branch to go-getter.
Would it be possible to also mention that when special characters are in username/password,then these have to be URL encoded.
May not be obvious to everyone.

**Comment by dadgar** [comment]
Sure! I can add that. In the future though, to make a PR you should fork the project and then create a PR from that branch! Only repo members can push branches to the main project!

**Comment by parismorali** [comment]
Makes sense, thanks
