### ISSUE TITLE
[question] how to interpolate values (IP and PORT) of another task within the same group

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2611]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
CentOS 7 / Ubuntu 16.04

### Issue
I have a group with two docker tasks in it; one stunnel (ref: https://www.stunnel.org/index.html) and another my actual webserver.
stunnel: task1
webserver: task2

stunnel needs a config file for an "accept" port and "connect" port.
the "accept" port is where stunnel will accept incoming connections.
the "connect" port is typically a fixed port of the known server process.

When I use Nomad's port mapping and use ephemeral ports, how can I figure out the ephemeral PORT of task2 within the context of task1 ?

Example: within task1 be able to access a value set within task2.

Regards,
Shantanu

**Comment by dadgar** [comment]
Hey,

If you see here: https://www.nomadproject.io/docs/runtime/environment.html

There are the following environment variables that lets you do just that:
```
NOMAD_ADDR_<task>_<label>: The allocated address, given as IP:Port for the given label of other tasks in the same group
NOMAD_PORT_<task>_<label>: The allocated port for the given label of other tasks in the same group
NOMAD_IP_<task>_<label>: The allocated IP address for the given label of other tasks in the same group
```

Hope that helps!

**Comment by shantanugadgil** [comment]
Thank you! Thank you! Thank you! 🙌 
I hope this can be cross linked with the page:
https://www.nomadproject.io/docs/runtime/interpolation.html

Thanks and Regards,
Shantanu
