### ISSUE TITLE
Improvement proposal - expose cluster state to templates

### ISSUE THREAD

**Issue by Nomon** [hashicorp/nomad#2618]
It would be great if the template system would expose some functions for inspecting the nomad cluster state. Similarly to the way it has service,node,key,keyOrDefault etc. functions for inspecting the consul state.

In many cases it is sufficient to know the allocated addresses, resource utilization or allocations, the meta data in the job and the node running it etc. Essentially exposing the same data from remote jobs/tasks/nodes that is currently only available from the node and job being evaluated.

With this in place it would be possible to use the more richer meta system in nomad in templates as an alternative for using the fairly strict tag system or consul kv for communicating data from other jobs where it is sufficient/proper. Also it could be used for discovery, bootstrapping, sizing resources based on other jobs, allow maintaining common meta in a single job and interpolating them to other jobs and so forth.

**Comment by dadgar** [comment]
@nomon I am going to close this as the right place to file this issue is: github.com/hashicorp/consul-template as that is the underlying library that renders the templates! But I like the idea :)
