### ISSUE TITLE
env_aws fingerprinter should not override manually set network_interface

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2619]
A user ran into an issue where they were manually setting a `network_interface` but it was getting overwritten by the `env_aws` fingerprinter because they were in AWS.

We should not overwrite explicit user network configuration.

**Comment by gorset** [comment]
I'm also seeing this problem.

We are running most of our nodes on dedicated hardware with a few nodes in aws, using wireguard for networking. Setting network_interface to wg0 has no effect on the aws nodes, which means that nomad will register services in consul using the aws address.

Is there a good workaround that doesn't involve iptables/ip routing magic, or manual consul registration of the service (in other words, don't use nomad's consul integration for services)?
