### ISSUE TITLE
support --hosts-entry and --hostname options for rkt driver

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#2629]
### Nomad version
Nomad 0.5.6

### Operating system and Environment details
ArchLinux

### Issue
Currently the rkt driver does not support the `--hosts-entry` or `--hostname` options to rkt (as found here: https://coreos.com/rkt/docs/latest/networking/dns.html#etchosts and here: https://coreos.com/rkt/docs/latest/subcommands/run.html#options respectively)

These are important for applications that need to know the name of the box they are running on.

Thanks!

**Comment by onlyjob** [comment]
Being able to set hostname is quite important as some applications need certain hostnames. Definitely worth implementing.

**Comment by tgross** [comment]
Going to close this issue. Our [rkt](https://github.com/hashicorp/nomad-driver-rkt) driver is deprecated and will receive no new features.
