### ISSUE TITLE
Consul & Nomad - Datacenters vs. Regions

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#2630]
We are trying to set up a multi-datacenter configuration of Nomad using Consul cluster as backend.

In one Nomad region we have DC1 which is self-hosted, and DC2 which is one of the AWS regions.

The idea was that a Consul cluster would provide a backend for Nomad per DC, and this seems to hold true until we WAN join the clusters, at which point Nomad merges into a single cluster for the whole region.

During our testing this leads to an issue where dropping one of the DCs leads to complete Nomad raft cluster failure.

The only "proper" solution we have figured out to this design problem is adding a third DC with yet another three node Consul cluster.

Is this "merged" Nomad cluster supposed to take place by design (I have a hard time following the documentation regarding this topic)?

**Comment by rickardrosen** [comment]
Looks like this highlights parts of this issue: #2243

**Comment by dadgar** [comment]
Hey Rick,

You should just mark the two separate clusters as being different regions and then they won't automatically join but will rather federate.
