### ISSUE TITLE
[question] forwarding nomad logs to central log

### ISSUE THREAD

**Issue by lshahar** [hashicorp/nomad#2631]
We start implementing nomad at our infra and we need to collect the logs that arrived to nomad (from containers) and the logs that written by nomad to our  central logs.

Today we collecting the logs that made by containers by https://github.com/digital-wonderland/docker-logstash-forwarder.

There is anyway to do it? 

Thanks,
Shahar

**Comment by itatabitovski** [comment]
This questions is maybe more suited for the google groups.
https://groups.google.com/forum/#!forum/nomad-tool

Couple of options I can think of:

Option 1:
A docker specific way would be within the docker task to configure logging and use some of the docker supported logging drivers.

https://www.nomadproject.io/docs/drivers/docker.html#logging
https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers

Option: 2
You can also use sidecar (filebeat or similar) container that will ship files from the alloc/logs directory and it will run in the same group as you main task.

Option 3:
You can also run filebeat or similar on the host and ship logs from all allocations on that host /var/lib/nomad/allocs/*/alloc/logs/*.std*.

**Comment by dadgar** [comment]
Hey @lshahar ,

@itatabitovski did a great job covering the possibilities. I am going to close the issue as the question has been answered but feel free to post any followups. Also please prefer the mailing list for questions.
