### ISSUE TITLE
[question] How to make Nomad FIPS 140-2 compliant?

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#2639]
### Nomad version
0.5.6

### Operating system and Environment details
CentOS 7

### Issue
I have searched a lot and concluded that HashiCorp tools are not FIPS 140-2 compliant. (yet?)
* I have been searching for FIPS compliance in the other repos as well; Consul/Vault

The only reference of 140-2 I found was a call out by @sethvargo
https://groups.google.com/forum/#!searchin/consul-tool/fips%7Csort:relevance/consul-tool/0uqAFhuvgKw/A8WFax85AQAJ

So, the query is:
Is Nomad FIPS 140-2 compliant (I assume not) and how to make it so?

This is of course with the intent of using this in AWS GovCloud.
* I will also be cross-posting this for Consul

Thanks and Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil I don't believe that applies to Nomad. Nomad is not a cryptographic module. Further we are not targeting FIPS compliance at this point so I will bet closing this issue.

**Comment by shantanugadgil** [comment]
Thanks for the quick reply!

Regards,
Shantanu
