### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by rogeralsing** [hashicorp/nomad#2641]
I'm unable to figure out how to use dynamic port allocations and inform my service what port was assigned.

e.g. if I have a config section such as:

```
service {
    name = "myservice"
    tags = []
    port = "http"
}
resources {
    network {
        port "http" {}
    }
}
```

I can see in consul that the service have a dynamic port assigned.
but how do I make my app aware of this port?

Before Nomad, I used to make the app itself allocate a dynamic port and then report that into Consul.
Can I access the port via env vars or is there any other not super intrusive way to make the app aware?

**Comment by stefreak** [comment]
If you use the docker driver you can listen on any port you like inside the container and then tell nomad how to map the ports:

```
    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:latest"
        port_map {
          http = 80
        }
      }
```

**Comment by rogeralsing** [comment]
But what if I am not using the Docker driver?
As there is a feature to assign dynamic ports, there ought to be a feature how to know what port was assigned, no?

**Comment by stefreak** [comment]
https://www.nomadproject.io/docs/job-specification/network.html#port-parameters

`${NOMAD_PORT_foo}`

**Comment by rogeralsing** [comment]
Ah awesome! thanks
