### ISSUE TITLE
[questiton] can can deploy replication apps, like mysql replication or mongodb cluster

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#2642]
How to write replication jobs

**Comment by dadgar** [comment]
@linuxgood1230 It is hard to answer that question in a generic way as it highly depends on the system. However my overall suggestion would be to use the [service stanza](https://www.nomadproject.io/docs/job-specification/service.html) to register instances into Consul. This will give you a discovery mechanism. You can then use the [template stanza](https://www.nomadproject.io/docs/job-specification/template.html) to load dynamic configs based on the registered IPs of the instances, etc.

If you have to manually pick a leader, using Consul locks is also a highly convenient tool! Hope all this has helped! In the future, for questions please prefer the mailing list and check out the Gitter room! Hopefully community members can also help out!
