### ISSUE TITLE
Make a pre-comiled arm64 build

### ISSUE THREAD

**Issue by Knight1** [hashicorp/nomad#2643]
### Nomad version
Nomad v0.6.0-dev (b9bd1b0e95d032330c83ca32bb432adc26d40b9d)

### Operating system and Environment details
Ubuntu 16.10 / arm64

### Issue
There is only a pre-compiled arm version for Nomad available the arm64/aarch64 versions is missing. I was able to build it with go 1.8.1 without any errors on a Thunder X.

### Fix
Please make a pre-compiled arm64 version from Nomad available unter the download section.

**Comment by Knight1** [comment]
Consul fixed it with this commit: https://github.com/hashicorp/consul/commit/437222fbe7231189213977d164a00dc1310f88c3

Vault with this: https://github.com/hashicorp/vault/commit/7bce60290f2103365c4fedd9e28fbb28c0930fa1

**Comment by dadgar** [comment]
@Knight1 Would welcome a PR for this.

**Comment by schmichael** [comment]
arm64 builds are available!
