### ISSUE TITLE
nomad stop and nomad run doesn't restart job

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/nomad#2653]
We have a service that calls the Nomad HTTP API to restart jobs (i.e. for when there is a resource leak in a service).

This service, written in Golang, uses the Nomad API to stop/start the job, emulating `nomad stop` followed with `nomad run` as run from the command line.

    var job *nomad.Job

    // code to initialize the job var is here

    info, _, err := e.nomad.Jobs().Info(app, nil)
    if err != nil {
        if !strings.Contains(err.Error(), "404") {
            return err
        }
    }

    // some code uses info var here

    if info != nil {
        // Stop the service to force a restart
        _, _, err = e.nomad.Jobs().Deregister(app, nil)
        if err != nil {
            return err
        }
    }

    _, _, err = e.nomad.Jobs().Register(job, nil)
    if err != nil {
        return err
    }

    return nil

However, we've found that when calling `Deregister` and `Register` in quick succession Nomad doesn't stop the job, yet it updates the indexes.

before running the code:

        "CreateIndex": 564507,
        "JobModifyIndex": 564507,
        "ModifyIndex": 564507

after running the code:

        "CreateIndex": 564515,
        "JobModifyIndex": 564515,
        "ModifyIndex": 564515

However, `nomad status` shows the old allocation. No new allocations are created, and the old allocation is not stopped.

**Comment by dadgar** [comment]
@grobinson-blockchain When the job was stopped/submitted again so quickly, the scheduler didn't get invoked in the mean time so when it looked at the cluster, all the required allocations were there. I would get the eval ID returned by the deregister and block on it entering the complete state before re-registering the job.

**Comment by grobinson-blockchain** [comment]
This works! Thanks @dadgar
