### ISSUE TITLE
duplicate internal ip on multiple docker containers

### ISSUE THREAD

**Issue by virmis** [hashicorp/nomad#2656]
### Nomad version
Nomad v0.5.4

### Docker version
Docker version 1.12.1, build 23cf638

### Operating system and Environment details
CentOS Linux release 7.3.1611

### Issue
We have ~100 containers on docker host. We found that some docker containers gets the same IP addresses:
docker inspect -f '{{.NetworkSettings.Networks.nomad.IPAddress}}' ff8fd29d71b7
172.18.0.7
docker inspect -f '{{.NetworkSettings.Networks.nomad.IPAddress}}' 989b31199fea
172.18.0.7

docker inspect -f '{{.NetworkSettings.Networks.nomad.IPAddress}}' ee843ed991ae
172.18.0.8
docker inspect -f '{{.NetworkSettings.Networks.nomad.IPAddress}}' 45f8b4355332
172.18.0.8

Container delete and start does not help. Containers remain with the same internal duplicated IP's.

What information I can provide to help you reproduce and fix this issue?

**Comment by thatsk** [comment]
How do you define the containers across the cluster

**Comment by xytis** [comment]
This incident was reached on nomad cluster with:
97 jobs
1002 tasks
14 clients
5 servers

The containers are launched by nomad jobs with docker driver.

Can you specify what you meant by 'container definition' ?

**Comment by xytis** [comment]
Example job taken by random from currently running ones: https://gist.github.com/xytis/eca0b97587ed06dd01b727c7ea525328

**Comment by dadgar** [comment]
@virmis Could you provide the output of `curl http://127.0.0.1:4646/v1/allocation/<alloc-id>` of the allocations that are on the same machine that have conflicting IPs?

**Comment by dadgar** [comment]
Actually just looked at your job file, you aren't use host/bridge networking so this is probably a problem of the docker network. It is assigning duplicate IPs to containers. Are you using DHCP or something to yield IPs?

**Comment by xytis** [comment]
Are the IP's given out by docker? Not by nomad? How do you keep the ip/port pair stable during alloc restarts?

We are using named 'bridge' network. (hence 'nomad')

**Comment by dadgar** [comment]
@xytis With bridge or host we manage it. The scheduler will assign an IP for the task and we will map to the container. But when using a different network it is being handled by docker not Nomad: https://gist.github.com/xytis/eca0b97587ed06dd01b727c7ea525328#file-example-job-json-L35

**Comment by xytis** [comment]
```
[xytis@docker-01 ~]$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
695c544c91f2        bridge              bridge              local
581da5f13d67        host                host                local
e4aa999a1c32        nomad               bridge              local
```

**Comment by dadgar** [comment]
@xytis Seems like a docker problem to me. Docker handles assigning an IP from that network. We only map that to the appropriate host IP:Ports. And I am assuming if you look at the allocations of the conflicting tasks that Nomad has picked different ports for the different allocations

**Comment by dadgar** [comment]
I would file an issue against Docker. @xytis What is the nomad error that gets reported.

**Comment by xytis** [comment]
@dadgar, ports are different for allocations with conflicting ip addresses. I will escalate this to docker, I think directly to libnetwork.

Nomad does not report any errors.

**Comment by dadgar** [comment]
@xytis As in the task will start running?

**Comment by xytis** [comment]
Yes, the task is marked 'running'. Allocations are all ok too. Nomad senses no problem with this situation. (If not for consul checks we would have missed it too)

**Comment by dadgar** [comment]
@xytis Cool! Thanks for following up. I would cross-link the docker issue here so other can find it but am going to close the issue here. We can re-open as we get new info or something points it at being a Nomad issue. Thanks!
