### ISSUE TITLE
Node ID breaks tutorial

### ISSUE THREAD

**Issue by benmoss** [hashicorp/nomad#2661]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
Ubuntu 16.04 LTS, the box downloaded by [the Vagrantfile](https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile) from the tutorial.

### Issue
As far as I can tell, the new-ish Node ID code breaks the tutorial [here](https://www.nomadproject.io/intro/getting-started/cluster.html).

The two node clients I start up in the Vagrant image have the same Node ID:
```
    2017/05/21 03:02:51.025159 [INFO] client: Node ID "637aeea9-75d6-4d9e-beab-9f5696c2dba7"
```

And so the second one gets this error:
```
* RPC failed to server 127.0.0.1:4647: rpc error: node secret ID does not match. Not registering node.
    2017/05/21 03:11:24.012773 [DEBUG] client: RPC failed to server 127.0.0.1:4647: rpc error: node secret ID does not match
    2017/05/21 03:11:24.012835 [DEBUG] client: re-registering node as there was a secret ID mismatch: 1 error(s) occurred:
```

### Reproduction steps
Start the Vagrant box. Start a Nomad cluster with the server.hcl, client1.hcl and client2.hcl files in the tutorial. See that client2 fails to start.

**Comment by benmoss** [comment]
I had to manually modify `/tmp/client2/client/client-id` and change it to a different UUID and that fixed it.

**Comment by jonatanblue** [comment]
I'm still seeing this, even with `no_host_uuid = true` in both client files and `Nomad v0.5.6`. Same workaround as @benmoss suggested, create new UUID and write to client2-id:

```
uuidgen | perl -pe 'chomp if eof' > /tmp/client2/client/client-id
```

**Comment by benmoss** [comment]
@jonatanblue did you set `no_host_uuid` to true before ever starting the clients? if you set it after you've already started it, it will still use the value in the filesystem.

**Comment by shantanugadgil** [comment]
@jonatanblue 
A quicker method (I think) for getting random uuid:
`cat /proc/sys/kernel/random/uuid`
