### ISSUE TITLE
Add sections related to Vault and Consul integration in the tutorials

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#2666]
Opening this issue for tracking purposes, feel free to close this if it already exists or feel it's not needed. Recently I had some of my team members go through the Nomad tutorial and they found it very approachable however the tutorial ends with clustering. 

Can we extend it to Vault and Consul as well before we move on to Clustering? I think having people run Vault and Consul in dev move and showing how Nomad works with them would be fabulous!

Also, @dadgar I finally played with the vault integration -- good work :)

**Comment by dadgar** [comment]
@diptanu I think that may be a little advanced for the getting started. I think we need guide sections for these that can deep dive!

**Comment by chandy** [comment]
I agree with @diptanu and think the demo at https://github.com/hashicorp/nomad/tree/master/demo/vagrant could bring up a VM with all 3 installed and ready to play with as a start.

**Comment by dadgar** [comment]
@chandy What I was envisioning would be reusing that VM but at the end of the getting started to link to some more advanced guides that could use that VM. So you could do a guide on using Vault, etc.

**Comment by nickethier** [comment]
Closing this with all the new work on the learn site: https://learn.hashicorp.com/nomad
