### ISSUE TITLE
[question] Is there any plans to support a native vmware esx driver to launch VMs from Nomad?

### ISSUE THREAD

**Issue by jbpadgett** [hashicorp/nomad#2688]
[question] Is there any plans to support a native vmware esx driver to launch VMs from Nomad?
I see there is a QEMU driver currently, but I was hoping to not need nested virtualization of QEMU on a VM on top of ESX if I could get it.  Having a driver support VM launching from Nomad on ESX natively would be nice if you have it in your backlog.

**Comment by dadgar** [comment]
Hey we currently do not have any plans to do so! It maybe possible to do by creating a new driver if you would like to look into it. I am going to close since the issue isn't tracking any planned work! Thanks!

**Comment by shantanugadgil** [comment]
I know I am replying on an old thread, but has there been any internal/community discussion for a "native" binary to run on ESXi hosts? This can then be used to VM related stuff.

There seems to have been a few questions on the Google group relating to the same.

**Comment by tgross** [comment]
@shantanugadgil we're not planning on implementing this sort of thing ourselves. However, this sort of project would be a perfect fit for the [task driver plugin](https://www.nomadproject.io/docs/internals/plugins/task-drivers.html) concept introduced in 0.9.

**Comment by shantanugadgil** [comment]
@tgross sure, thanks. but last I remember the binary would start and then exit as it couldn't fingerprint the OS due to various reasons (it can't detect the flavor of *nix, etc.). Even if the binary were to start fine, something could be hacked around using `raw_exec`.
