### ISSUE TITLE
Nomad trunk tries to execute '/sbin/ip route' which fails on CoreOS

### ISSUE THREAD

**Issue by kmalec** [hashicorp/nomad#2696]
### Nomad version
Output from `nomad version`
`Nomad v0.6.0-dev (67cd5154bb0add222f1d4dc56283ff9f47a5ec8f+CHANGES)`

### Operating system and Environment details
`Container Linux by CoreOS stable (1353.8.0)`

### Issue
Nomad in 0.6 branch tries to execute `/sbin/ip route` during startup, which fails on CoreOS, because they have iproute2 in `/usr/bin/ip`.
This doesn't happen on 0.5.6; apparently recent change to use github.com/hashicorp/go-sockaddr

### Reproduction steps
Compile nomad from trunk and try to run:
`nomad agent -server -data-dir /data/nomad-server/data/ -config /data/nomad-server/config/ -region eu-west -dc eu-west-1`

### Nomad Server logs (if appropriate)
```
Jun 07 19:32:01 ip-10-249-200-172 systemd[1]: Started Nomad server.
Jun 07 19:32:01 ip-10-249-200-172 nomad[22507]: No configuration loaded from /data/nomad-server/config
Jun 07 19:32:01 ip-10-249-200-172 nomad[22507]: ==> Failed to parse HTTP advertise address: Unable to parse default advertise address: Unable to parse address template "{{ GetPrivateIP }}": unable to execute sockaddr input "{{ GetPrivateIP }}": template: sockaddr.Parse:1:3: executing "sockaddr.Parse" at <GetPrivateIP>: error calling GetPrivateIP: fork/exec /sbin/ip: no such file or directory
Jun 07 19:32:01 ip-10-249-200-172 systemd[1]: nomad-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 19:32:01 ip-10-249-200-172 systemd[1]: nomad-server.service: Unit entered failed state.
Jun 07 19:32:01 ip-10-249-200-172 systemd[1]: nomad-server.service: Failed with result 'exit-code'.
Jun 07 19:32:06 ip-10-249-200-172 systemd[1]: nomad-server.service: Service hold-off time over, scheduling restart.
Jun 07 19:32:06 ip-10-249-200-172 systemd[1]: Stopped Nomad server.
```
### Nomad Client logs (if appropriate)
N/A
### Job file (if appropriate)
N/A

**Comment by dadgar** [comment]
@kmalec Can you file and cross link an issue against that project.

**Comment by kmalec** [comment]
Did that. Recompiled Nomad with changing that path to `/usr/bin/ip` for extra CoreOS build, works (as expected).
