### ISSUE TITLE
Fix Nomad server health check

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2701]
I think I caused a regression in #2467 -- from gitter:

> git blame points to your commit 77d9b417c1a18320f4cd7606c47700fbac3f2199  apparently before that change, servers did /v1/status/peers and clients /v1/agent/servers, but it got consolidated into /v1/agent/servers, which seems to be implemented in client only - so consul server health checks will fail on trunk
> would it make sense to just switch the URI back to /v1/status/peers, as that seems to be a "generic" status check endpoint?

**Comment by shilov** [comment]
Can confirm this is causing "Nomad Client HTTP Check" to fail for nomad agents running in server mode.

As implied, changing `/v1/agent/servers` to `/v1/status/peers` in `command/agent/agent.go` fixes the issue.
