### ISSUE TITLE
Give templates access to task meta data

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#2703]
### Nomad version
Output from `nomad version`
0.5.6

### Operating system and Environment details
Arch Linux

### Issue
The docs stipulate that templates have access to node meta via the following format:
{{ env "meta.node_meta_key" }}

however it does not seem like the templates get access to *task* meta data as described here:
https://www.nomadproject.io/docs/job-specification/meta.html

Allowing the templates to access this would allow for various values to be set in the task dynamically, and then passed into the template.   

A workaround for this is to set the value that you want into an environment variable:

``` 
  meta {
      app_name = "org-api"
   }
# set some environment variables (otherwise we cant get task meta data into the template yet)
      env {
        APP_NAME = "${meta.app_name}"
      }
      # turn it into the correct config
      template {
        source = "local/org-api-jmx.yml.tmpl"
        destination = "local/jmx.yml"
        change_mode = "restart"
      }
```

and then use the standard `env` syntax in the tempalate:
```
{{ env "APP_NAME" }}
```

This works, but is very ugly, and feels like it shouldn't be needed.

**Comment by dansteen** [comment]
On looking into this further,  it turns out that the ENV workaround that I presented above does not work.   It looks like task meta data isn't able to be interpolated anywhere in the job so the values just show up as the literal string "${meta.app_name}". 

It would be great if we could use these values in the job in general.

**Comment by schmichael** [comment]
As of 0.5.3 you can access task and task group metadata via their environment variable form:

```hcl
  meta {
      app_name = "org-api"
   }
```

...can be accessed in templates as:

```
app_name = {{ env "NOMAD_META_app_name" }}
```

Closing this for now, but please feel free to reopen if you have a way we can improve the documentation or implementation.

Sorry for the slow response!
