### ISSUE TITLE
Allow change_mode on a template to restart the *job* in addition to just the *task*

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#2705]
Hey!  Great work on Nomad.  It's really an amazing solution.  I did have a quick question (or request).  

Currently,   the `change_mode` setting on templates will restart the task that the template is configured on.   Unfortunately, this can mean that *all* allocations of that task are restarted in an uncontrolled fashion when consul data changes.   Granted the `splay` value is available to ensure that things don't restart all at once, but it would be nice to be able to manage these restarts better. 
  
If instead (or as an additional option) it triggered a restart of the whole job the restart could be handled according to whatever heuristics were set for the job as a whole.

This becomes increasingly important once the "back pressure" feature is added in to consul.   The intent there is to prevent a deploy from continuing if an allocation "up the chain" has failed.   If `change_mode` just triggers a restart of the task, we again wind up with a situation where a single change to a config can result in the whole application becoming unavailable.   

As a note,  I currently work around this by having a set of "deploy" nomad jobs that trigger nomad jobs to start the actual applications.  These "deploy" jobs monitor the config values, and trigger a restart of the actual application jobs when they detect a change.  This works, but is conceptually difficult in debugging scenarios.

Thanks so much!

**Comment by dadgar** [comment]
Hey @dansteen,

Thanks for the great write up and glad you are enjoying Nomad. Unfortunately there is no coordination between various templates and as such an orchestrated restart isn't quite possible.

Your workaround is the best solution as you will get the update block to take effect and in 0.6.0 the update block will use allocation health and health checks as gating so it could save you from an outage.

Thanks!
