### ISSUE TITLE
Please add node.region as node variable + client region in output of node-status

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/nomad#2708]
It would be helpful to have the client's region available in the job file as ${node.region}, same way ${node.datacenter} is already available.
We would use it for some url templating where we built the url based on the region name.
Furthermore would it be possible to output the clients' region when running `nomad node-status [-verbose]`?

Thanks!

**Comment by schmichael** [comment]
Added in #2507 to fix #2183 and will be released in v0.6.

**Comment by gpaggi** [comment]
Thanks a lot @schmichael!
