### ISSUE TITLE
Wrong task count(their number differs from that specified in job file)

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#2712]
### Nomad version
Nomad v0.6.0-dev (52ffc01972a1babf0ece579e3de42a9e0c7bf8e6+CHANGES)

our changes is very simple fix for https://github.com/hashicorp/nomad/issues/2701. there we simple change  `/v1/agent/servers` to `/v1/status/peers` in `command/agent/agent.go`, bacouse before see tons of messages like this 

```
2017/06/14 06:53:36.042059 [ERR] http: Request /v1/agent/servers, error: Invalid method
2017/06/14 06:53:46.043747 [ERR] http: Request /v1/agent/servers, error: Invalid method
2017/06/14 06:53:56.045311 [ERR] http: Request /v1/agent/servers, error: Invalid method
2017/06/14 06:54:06.046904 [ERR] http: Request /v1/agent/servers, error: Invalid method
```

we noticed that one of jobs have wrong number of task, here is it `nomad inspec`

```
root@social:/home/nomad# nomad inspect tftpdboot | less
{
    "Job": {
        "AllAtOnce": false,
        "Constraints": [
            {
                "LTarget": "",
                "Operand": "distinct_hosts",
                "RTarget": ""
            },
            {
                "LTarget": "${attr.kernel.name}",
                "Operand": "=",
                "RTarget": "linux"
            }
        ],
        "CreateIndex": 686829,
        "Datacenters": [
            "test"
        ],
        "ID": "tftpdboot",
        "JobModifyIndex": 907226,
        "Meta": null,
        "ModifyIndex": 907226,
        "Name": "tftpdboot",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 70,
        "Region": "global",
        "Stable": false,
        "Status": "running",
        "StatusDescription": "",
        "Stop": false,
        "TaskGroups": [
            {
                "Constraints": null,
                "Count": 2,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "Meta": null,
                "Name": "tftpdboot",
                "RestartPolicy": {
                    "Attempts": 2,
                    "Delay": 15000000000,
                    "Interval": 60000000000,
                    "Mode": "delay"
                },
```

but we see follow job status:

```
root@social:/home/nomad# nomad status tftpdboot
ID            = tftpdboot
Name          = tftpdboot
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
tftpdboot   0       0         3        0       4         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status    Created At
47ec4103  f5c8ab84  41b521c8  tftpdboot   run      running   06/16/17 16:15:56 MSK
2c010836  cb0093a1  fe387298  tftpdboot   run      running   06/16/17 16:15:46 MSK
e6f5779e  f15e8006  84eafa18  tftpdboot   run      running   06/16/17 16:15:36 MSK
```

But expected only 2 allocations

**Comment by tantra35** [comment]
also if we change configuration of job for exmaple memory limit for allocation, all 3 allocations will accept this changes and will restart, so seems that nomad server inproperly think about number of needed allocs

**Comment by tantra35** [comment]
Its seems that is the same as #2710

**Comment by tantra35** [comment]
Here is our nomad eval-status:

Allocations changed sinence my last post so i must attach current allocations map:

```
root@social:/home/ruslan# nomad status tftp
ID            = tftpdboot
Name          = tftpdboot
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
tftpdboot   0       0         3        0       5         1

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status   Created At
5da258d9  92231054  a6026d01  tftpdboot   run      running  06/16/17 16:45:06 MSK
48727141  55a7c4b3  f7381e81  tftpdboot   run      running  06/16/17 16:32:23 MSK
47ec4103  f5c8ab84  41b521c8  tftpdboot   run      running  06/16/17 16:15:56 MSK
```

root@social:/home/ruslan# nomad eval-status 92231054
ID                 = 92231054
Status             = complete
Status Description = complete
Type               = service
TriggeredBy        = node-update
Node ID            = 84eafa18-fb37-de49-9bad-87d227e36580
Priority           = 70
Placement Failures = false
```

```
root@social:/home/ruslan# nomad eval-status 55a7c4b3
ID                 = 55a7c4b3
Status             = complete
Status Description = complete
Type               = service
TriggeredBy        = node-update
Node ID            = fe387298-a312-9560-4803-32d7f03039c6
Priority           = 70
Placement Failures = false
```
```
root@social:/home/ruslan# nomad eval-status f5c8ab84
ID                 = f5c8ab84
Status             = complete
Status Description = complete
Type               = service
TriggeredBy        = rolling-update
Job ID             = tftpdboot
Priority           = 70
Placement Failures = false
```

**Comment by dadgar** [comment]
Closing in favor of https://github.com/hashicorp/nomad/issues/2511

**Comment by dadgar** [comment]
Hey sorry you ran into this. We haven't quite been able to reproduce this so any more hints would be appreciated but obviously it is hard to tell what happened.

As for fixing this, Nomad 0.6.0 is largely redoing the way reconciliation happens in the scheduler. So I believe this will be fixed in 0.6.0! I'd like to keep https://github.com/hashicorp/nomad/issues/2511 open till 0.6.0 and then see if there are any more reports of this with the new version!

Thanks,
Alex

**Comment by tantra35** [comment]
Hm in my case this happens on Nomad v0.6.0-dev

**Comment by dadgar** [comment]
@tantra35 The new scheduler code is in a separate branch! Hasn't been merged into master
