### ISSUE TITLE
Improvement: allow to bind custom address when using port mapping

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#2726]
We are using dual-stack: IPv4 and IPv6 on our servers.
We've created nomad job and started docker container with `bridge` network and port mapping. And we were disappointed when observed that docker mapped port only on single IP address.
Something like:
192.168.122.176:39432->8111/tcp, 192.168.122.176:39432->8111/udp
In nomad's logs we can see:
    2017/06/22 16:22:08.807788 [DEBUG] driver.docker: allocated port 192.168.122.176:39432 -> 8111 (mapped)
    2017/06/22 16:22:08.807808 [DEBUG] driver.docker: exposed port 8111
Or the same but with IPv6 address.
Is it possible to publish ports on specific multiple IPs or interfaces?
It would be great if it would be possible to configure host's IP or interfaces to publish ports on.

**Comment by dadgar** [comment]
Hey @pznamensky,

I am going to close this issue in favor of https://github.com/hashicorp/nomad/issues/646 which tracks the need to be able to support multiple host networks.

While you can't currently bind to multiple, you can select which interface to bind via https://www.nomadproject.io/docs/agent/configuration/client.html#network_interface
