### ISSUE TITLE
[Question] Nomad Class Usage to Filter Nodes

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/nomad#2727]
Nomad allows to filter the nodes that are chosen to do a placement by adding class constraints. We have a situation were some set of nodes should be exclusively used by for those jobs that comes with a specific constraint. We can achieve the first part by adding the class constraint to those jobs. 

The question is, the jobs that comes **without** any specification can also get scheduled in those nodes which we want to avoid. Suggestions?

**Comment by schmichael** [comment]
You'll have to schedule other jobs with an opposite constraint:

```hcl
      constraint {
        attribute = "${node.class}"
        operator  = "!="
        value     = "specialClass"
      }
```

**Comment by dadgar** [comment]
Hey @vrenjith,

For the time being I would suggest creating a new DC and adding those nodes to that DC. Then you can run jobs that target that DC which will keep them exclusive. Going to close the issue but feel free to add followup questions!
