### ISSUE TITLE
Document upgrade procedure

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#273]
The upgrade procedure for nomad should be documented, so that it's clear what exact steps should be taken to upgrade a nomad cluster.

Since consul is going to be used for discovery and load balancing, it would also be very useful to provide any special procedures for updating a consul cluster when it is being used with a nomad cluster.

Duplicate / Closes #562

**Comment by cbednarski** [comment]
Thanks for opening an issue. Consul has its own upgrade docs [here](https://www.consul.io/docs/upgrading.html).

We will add an upgrade doc for Nomad. I would also encourage you to read the release notes for each project before upgrading.

**Comment by dadgar** [comment]
This exists now: https://www.nomadproject.io/docs/upgrade/index.html
