### ISSUE TITLE
running vault with nomad which uses vault

### ISSUE THREAD

**Issue by aep** [hashicorp/nomad#2731]
currently it isn't possible to run vault within nomad, because nomad requires vault working.

````
2017/06/23 12:28:30.423134 [INFO] client: Restarting task "vault" for alloc "9986de91-21b9-360b-408b-4cc9a92c5b24" in 17.271128897s
2017/06/23 12:28:39.562350 [WARN] vault: failed to contact Vault API. Retrying in 30s: Get http://vault.service.consul:8200/v1/sys/init: dial tcp: lookup vault.service.consul on 172.17.0.1:53: no such host
````

this may be related to #2689 
there's really no reason to contact vault, if no vault stanzas are in the job configuration

**Comment by dadgar** [comment]
Hey,

Firstly, I would highly recommend you do not go down this route. Services like Consul, Nomad and Vault should be all run on their own machines as they are core infrastructure pieces.

Secondly, it should be possible to do as you are asking (although unrecommended). The approach I would take is to set up your Nomad job and get Vault running and configured.

Then add the vault config to the servers and either restart them or SIGHUP them and they will load the settings.

The log message you are seeing is the server trying to validate the token you gave it and ensure that the configs are properly setup. However it is not contacting Vault for job submissions if there is no vault stanza.

Hope that helps!

**Comment by victorstewart** [comment]
@dadgar say one did do this... could the vault server then be updated through normal nomad update procedures and the nomad cluster's connection with it would heal after vault was running again?
