### ISSUE TITLE
Improvement: multiple key's prefixes in templates like in envconsul

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#2751]
Recently @schmichael implemented envconsul-like support https://github.com/hashicorp/nomad/pull/2654. But as mentioned in closed #1765 it would be great to support multiple prefixes.
We are using multiple prefixes in envconsul when executing some applications. And it is very convenient.
Didn't you think about adding ability to merge keys from multiple prefixes in nomad's template?

**Comment by dadgar** [comment]
Hey this can be achieved already:

```
       template {
         data          = <<EOF
{{ range ls "foo/" }}
{{ .Key }}={{ .Value }}{{ end }}
         EOF
         destination   = "local/file.yml"
         env = true
       }
```

**Comment by pznamensky** [comment]
Indeed keys from multiple prefixes are merged.
@dadgar, thanks!
```
       template {
         data          = <<EOF
{{ range ls "global/" }}
{{ .Key }}={{ .Value }}{{ end }}
{{ range ls "app/appname" }}
{{ .Key }}={{ .Value }}{{ end }}
         EOF
         destination   = "local/file.yml"
         env = true
       }
```
