### ISSUE TITLE
interpolation does not work for destination in artifact stanza

### ISSUE THREAD

**Issue by svd23** [hashicorp/nomad#2752]
### Nomad version
Nomad v0.5.6
### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)
### Issue
interpolation does not work in artifact { destination = "***destination***" } stanza

### Reproduction steps

create job with example from "[Job file section](#Job-file)"

[`nomad validate` and `nomad run` executes with no errors](#Nomad-Server-logs). 

[`nomad status -verbose example` shows that download has been completed and task started](#Nomad-Client-logs)
but as you can see from logs, task is terminated because, in my case, start script expected to be in ***/tmp/example-job/start.sh***

Checking content of allocation on node that was assigned to run a task:

```
ls your_nomad_allocation_dir

...
...
drwxr-xr-x   3 root   root      17 Jun 28 13:08 ${NOMAD_META_DESTINATION_DIR}
...
```

### Nomad Server logs

```
$ nomad validate example.nomad
Job validation successful
```
### Nomad Client logs
```
06/28/17 13:08:44 PDT  Restarting             Task restarting in 27.305774574s
06/28/17 13:08:44 PDT  Terminated             Exit Code: 1
06/28/17 13:08:44 PDT  Started                Task started by client
06/28/17 13:08:26 PDT  Downloading Artifacts  Client is downloading artifacts
```
### Job file
```
job "example" {
.....
  meta {
     DESTINATION_DIR = "/tmp/example-job"
     SOURCE_URL = "https://example_url/example.tar.gz"
  }
....
  task "task" {
....
     artifact {
        source = "${NOMAD_META_SOURCE_URL}"
        destination = "${NOMAD_META_DESTINATION_DIR}"
     }
.....
}
```

**Comment by Fuco1** [comment]
Please reopen this issue, I see no reason why this shouldn't work.
