### ISSUE TITLE
Improvement to raw_exec

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#276]
Hi!

Would be nice if `raw_exec` could support a `user` directive, executing the command with the `uid` / `username` with `sudo` or something similar

If nomad runs as root, this UNIX user account will be used as the account which runs the program. If nomad can’t switch to the specified user, the program will not be started.

This issue + #208 are basically the only piece missing for a full replacement of supervisord in a much more scalable way

**Comment by cbednarski** [comment]
This existed in an earlier version of the driver. I might be able to resurrect the code.

**Comment by achanda** [comment]
This one? https://github.com/hashicorp/nomad/commit/cdd065cb07155e6f54166ad727d87c577ab78268

**Comment by jippi** [comment]
Okay, so its just missing from `raw_exec` ?

**Comment by cbednarski** [comment]
@achanda That's the one! @jippi We changed how that mechanism works in exec to use a cgroup instead of a user.

**Comment by cbednarski** [comment]
@achanda Initially `RunAs` was part of the executor interface and we would try to drop to `nobody`. This is no longer the case so I think this probably needs to be an option on the `raw_exec` driver config.
