### ISSUE TITLE
HTTP endpoint to tail job logs, stdout, and stderr 

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#277]
Would be a nice addition for easy debugging

I realise non-nomad version of this would be to pipe everything to syslog or similar, but it requires a few more moving parts

**Comment by cbednarski** [comment]
@jippi Thanks for the suggestion. We would like to support this because it is a super convenient way to debug things on a small cluster. In a large scale environment we recommend using centralized logging.

**Comment by rvm2015** [comment]
+1 Having the ability to shove this output somewhere (like logspout with docker) for 12 factor apps would be nice.

**Comment by rvm2015** [comment]
+1 It would be highly preferable to me that whatever format gets used is compatible with logstash. I'm currently using logspout -> syslog -> logstash but being able to remove the logspout step would be helpful. I'm not fond of sidecar docker instances ex. Kubernetes.

**Comment by fernandezvara** [comment]
I would point to heka, since the docker log input allows to get all the logs with a simple configuration setting.

http://hekad.readthedocs.org/en/v0.10.0b1/config/inputs/docker_log.html

If you don't like to get the container name as log source, you can add any information you need from the environment variables.  (Adding a name_from_env_var, like 'TASK_NAME' will return the value if found instead of the container name).

That way you have a centralized log easily without over configuration.

Hope this helps.

**Comment by cbednarski** [comment]
From #475

> Currently it seems there is no way to view the out put of a job other than using docker logs (if you are scheduling docker) on a individual container. it would be awesome if the logs were made available via a stream or something, this would also make for a useful ui feature in that you can see your jobs get allocated and see there output, perhaps even see the logs of all of the instances of a task in the same stream just tag for each instance.

**Comment by cbednarski** [comment]
> +1 On a side note, having the ability to shove this output somewhere in the job definition (like logspout with docker) for 12 factor apps would be nice.

@rvm2015 Our expectation is that you will have a log shipping agent setup on the host, or co-scheduled in your task group. Can you give us some specific examples of configuration you need to specify that is currently not available in Nomad?

**Comment by Supernomad** [comment]
@cbednarski I cannot speak for @rvm2015 however a simple use case for this would be getting the logs for said shipping agent without having to go to a node that is somewhere on your cluster to get them.

Also there are a lot of times where logs coming  out of stdout/stderr or much different than the ones coming out via log files. This can be invaluable when trying to debug why an application seemingly inexplicably died.

**Comment by diptanu** [comment]
@Supernomad Our logging feature, coming with Nomad 0.3 will allow you to stream logs and view the file system of an allocation with Nomad cli. You won't need to go to a Node to stream logs out of the tasks running on allocations in that Node.

The UX is going to be something like this -

```
nomad logs <allod-id> <task-name> --stdout --follow
nomad alloc-fs-list <alloc-id> /path/to/dir/
nomad alloc-fs-cat <alloc-id> /path/to/file
nomad alloc-fs-stat <alloc-id> /path/to/file
```
Hope this works for you?

**Comment by Supernomad** [comment]
@diptanu That will work perfectly, but I have two questions. First would there be a way to get the logs from all active allocations? Also, is there any kind of timeline on 0.3?

**Comment by diptanu** [comment]
@Supernomad Yes, you can get logs from all allocations which are still present on the nomad clients. 

And regarding 0.3, very soon! We are getting into the crunch mode to get the release out.

**Comment by sheerun** [comment]
@diptanu I'd prefer --follow flag to be added to `fs cat` instead to stream logs in custom locations as well.

**Comment by jrg72** [comment]
Would there be any possibility this could be added to nomad? I'm trying to debug a particularly difficult issue with the Rkt driver and it would be very helpful to have this output while trying to determine if the problem is the ACI or the driver. Thank you.

**Comment by dadgar** [comment]
Still on the roadmap! But won't be in 0.4.0

**Comment by type0lang** [comment]
+1. here i have a failed task with 0 stderr or stdout
> nomad logs -stderr e3e3d705 
>

**Comment by dadgar** [comment]
Ah this is actually done! `/v1/client/fs/logs`.

@type0lang You may have that if it never produce logs because it failed to start (see `nomad alloc-status`) or the allocation may have been garbage collected

**Comment by sheerun** [comment]
@dadgar Ideally `nomad logs` would allow streaming any file, not only stderr / stdout. Sometimes logs are written in separate files, and sometimes we'd like to stream results / progress.

**Comment by dadgar** [comment]
You can do that using nomad fs command. If you do -f it will follow the
file.
