### ISSUE TITLE
[FEATURE]: Vault auto discover

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/nomad#2778]
Hi,

I was looking for something like the Nomad feature of finding its peers through Consul but for the Vault nodes... something like:

```
consul {
  ...
  vault_auto_discover = "true"
  vault_service_name = "vault"
}
```

This way we could use Consul service discovery to find the advertised Vault nodes and Nomad would use that info to connect to Vault.

**Comment by dadgar** [comment]
Hey,

Glad you are using both the integrations! Is there any reason you can't just use the DNS based lookup?

`vault.service.consul:8500?`

**Comment by danlsgiga** [comment]
Hi @dadgar, thanks for the quick follow up.

So, yeah... our main DNS servers do not forward queries to Consul if looking for *.consul so, doing a lookup for vault.service.consul fails since it is using our corporate DNS instead of the local consul DNS server. We basically only use the consul DNS locally on each node but AFAIK there's no setting to specify a different DNS server for nomad to use. If that's possible (and I looked for that) that would be enough for my usecase since Nomad will be able to query consul DNS for the vault.service.consul address successfully.

**Comment by SoMuchToGrok** [comment]
dnsmasq should do the job. More detail [here](https://www.consul.io/docs/guides/forwarding.html#dnsmasq-setup).

Example conf
```
server=/consul/127.0.0.1#8600
```

**Comment by dadgar** [comment]
@SoMuchToGrok Thanks for finding the docs!

@danlsgiga Your corporate DNS doesn't need to forward the queries to Consul. You use dnsmasq to have the local Consul agent handle the DNS request.

**Comment by danlsgiga** [comment]
Actually, good idea! I know dnsmasq but didn't think about it. Thanks for the doc references and for the fast response.
