### ISSUE TITLE
HTTP UI like consul-ui

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#278]
Much like consul-ui, it would be nice with a nomad-ui project to visually access and modify jobs etc

Until Nomad has it's own native UI, [jippi/hashi-ui](https://github.com/jippi/hashi-ui/releases) provides a Nomad and Consul UI

**Comment by defender** [comment]
+1

**Comment by hankerepo** [comment]
That would be perfect.  I support to many point and clickers to get this to fly without it.

**Comment by sielaq** [comment]
+1
something that looks like marathon UI

**Comment by rvm2015** [comment]
+1

**Comment by jeffbaier** [comment]
+1

**Comment by trevorgray** [comment]
+1

**Comment by a1017** [comment]
+1

**Comment by spinx** [comment]
+1

**Comment by iamthemuffinman** [comment]
+1

**Comment by zanedeg** [comment]
+1

**Comment by joonas-fi** [comment]
+1

**Comment by ketzacoatl** [comment]
At least from my limited perspective, this seems like an obvious big win. @dadgar, I would be interested in what brainstorming is needed for this?

The reasons why I am particularly interested: 1) Consul's UI was a major sell for me any my team evaluating Consul and etcd 2) when Nomad has a UI, devs who have a difficult time with the CLI can still be effective (important when comparing mesos/etc to nomad).

**Comment by erSitzt** [comment]
+1

**Comment by poll0rz** [comment]
+1

**Comment by eveld** [comment]
I think that if Nomad were to have a UI it should be a lot more useful than the UI of Mesos/Marathon, as they are lacking. 

I would like to be able to filter/search my tasks, see their history/logs, easily see how the tasks are spread and why my task ended up on a certain node. When everything is working fine the Marathon and Mesos UIs are fine, but if something with your job goes wrong or not according to plan it's a terrible tool for figuring out what went wrong.

**Comment by RVN-BR** [comment]
Is this somewhat similar to Rancher (which does have a UI)?  I'm currently evaluating several different options for docker running/orchestration... apologies if I'm off the ball...

**Comment by jippi** [comment]
@RVN-BR I love the rancher UI, or tutum.co - would love to see that for nomad, paid or free :)

**Comment by RVN-BR** [comment]
Agreed... There are so many great prjects "almost there"... if nomad (or xxx project) would join with rancher (or yyy project) and we had "less" optiosn, but better software it would be so much better for the community :(

**Comment by sielaq** [comment]
to be honest, most important from UI, should be:
* scaling (up/down)
* healthy status of services, 
* and deployment progress.
Additionally: on fly changes like add/remove tag/checks, history of deployment, flapping detection, etc..

The rest stuff, like creating new service (which is important) but shouldn't be priority 
since ideally, all stuff should be done automatically, and in repeatable way - were UI is not for.

**Comment by spinx** [comment]
Is this on the roadmap @dadgar?

Does it need to be Ember as for Consul ? I'd love to contribute and this is something where I and probably a lot of others can.

**Comment by dadgar** [comment]
Hey guys,

There will be a Nomad UI and it will be through [Atlas](https://atlas.hashicorp.com). This is being actively worked on. We will not be merging any HTTP UI code into this repo because we do not want to duplicate efforts and maintenance across two different web UIs.

**Comment by dadgar** [comment]
Re-opening this as it is a good medium for the community to give feedback and influence the features that should be in the Atlas UI.

**Comment by iverberk** [comment]
@dadgar does this mean that the Hashicorp developed Nomad UI will only be available for paying Atlas customers and won't be open sourced as a separate component or within the Nomad repository like the Consul UI?

**Comment by spinx** [comment]
I don't mind paying but I will just say this regarding the UI: Mesosphere guys are very, very smart building a stunning UI on top of their DCOS product. It's important.

**Comment by dadgar** [comment]
@iverberk: The Atlas UI will not be open-sourced. The pricing/availability of the Nomad UI has yet to be decided. There will be additional Nomad features in Atlas that will be paid, but it has not been decided if the UI is one of them.

@spinx: I agree that a UI is an important addition and a great way to interact with a scheduler.

**Comment by wagnersza** [comment]
+1

**Comment by ephemeral** [comment]
+1

**Comment by jacktuck** [comment]
Any roadmap or timeframe for the UI?

**Comment by tugbabodrumlu** [comment]
I am wondering it as well.

**Comment by dadgar** [comment]
I would expect some time in Q1 2016.

**Comment by gimlids** [comment]
+1! Mesos/Chronos has that nice UI for cron-like jobs...

**Comment by Supernomad** [comment]
+1

**Comment by nickvth** [comment]
+1

**Comment by tugbabodrumlu** [comment]
I have tried it two or three weeks ago, but couldn't make it work properly.

**Comment by orofarne** [comment]
+1

**Comment by kabennett** [comment]
+1

**Comment by graemedavidson** [comment]
+1

**Comment by bogdanov1609** [comment]
+1

**Comment by o6uoq** [comment]
+1

**Comment by JesusIslam** [comment]
+1

**Comment by charleslieferando** [comment]
+1

**Comment by chuyskywalker** [comment]
In addition to [nomad-web-ui](https://github.com/mikespokefire/nomad-web-ui) _(which I also could not get to work, even after untangling to multiple layers of unspoken dependencies...)_ I found [nomad-ui](https://github.com/eveld/nomad-ui) which looks like an experiment that didn't go anywhere.

Thus I hacked up [a quick, basic nomad ui](https://hub.docker.com/r/chuyskywalker/nomad-ui/) because I just wanted a way to easily view the cluster status.

**Comment by sielaq** [comment]
@chuyskywalker I have just added it for my playground https://github.com/eBayClassifiedsGroup/KomPaaS

**Comment by iverberk** [comment]
I've been working on a Nomad user interface over the last couple of weeks. I think I have a MVP that is ready for testing. Information can be found here: https://github.com/iverberk/nomad-ui

It provides a real-time view of the Nomad cluster, everything is updated immediately when things change. It allows you to inspect events, pending jobs, logs, etc. from the user interface. I'm sure there are still bugs somewhere and feature requests, but just open an issue on the repo and I'll try to fix it asap. I would love it if more people could contribute and maintain this with me. Things still on the roadmap are: realtime streaming of logs (with the new endpoint), creating jobs from the UI, start/stop jobs, resource graphs, maybe implement a server-side component instead of a pure webapp, etc.

Hope you like it!

**Comment by iamthemuffinman** [comment]
@iverberk That looks really good! Nice job!

**Comment by ketzacoatl** [comment]
beautiful work @iverberk, I'll take it for a spin this week! /me very excited

**Comment by themalkolm** [comment]
@iverberk nice one!

**Comment by tlvenn** [comment]
@dadgar is there any update on the Atlas UI for nomad ?

**Comment by dadgar** [comment]
It is being designed as we speak but public beta won't be for a while

On Wed, Aug 3, 2016 at 10:22 AM, Christian Meunier <notifications@github.com

**Comment by OferE** [comment]
+1

**Comment by jippi** [comment]
For those tracking this issue, https://github.com/iverberk/nomad-ui are coming along nicely.. more or less `API`-complete in terms of navigation and insights. 

It works super well on mobile as well.

We distribute it in Docker and Go binaries, and currently support `>= 0.4.0` of nomad.

I personally use it in production, so I'm committed to keeping the development active on the project. 

Take it for a spin and come by our gitter channel for a chat https://gitter.im/nomad-ui/Lobby

**Comment by mseravalli** [comment]
+1

**Comment by sielaq** [comment]
I have added both external UI (uyskywalker and iverberk)
to my playground [KomPaaS](https://github.com/eBayClassifiedsGroup/KomPaaS)
one is on port 80 2nd on 3000

**Comment by gvenka008c** [comment]
+1. This is a definitely needed feature and Hashicorp should consider making it as a open source. Else we would see most organization going with Mesos / Kubernetes.

**Comment by jippi** [comment]
Just an update on the nomad-ui project.

I've taken over the development of the project and moved it to https://github.com/jippi/hashi-ui

The project has been completely rewritten and got a new interface which (imo) makes it very efficient and fast to work with.

I've uploaded some screenshots of the new UI here; https://github.com/jippi/hashi-ui/blob/master/SCREENSHOTS.md 

Thanks!

**Comment by iamthemuffinman** [comment]
@jippi Did @iverberk stop working on it or something? Just curious.

**Comment by jippi** [comment]
@iamthemuffinman yeah, `hashi-ui` are nomad-ui (it will also redirect on GitHub) - please see https://github.com/jippi/hashi-ui/releases/tag/v0.5.2 :)

**Comment by jippi** [comment]
Just shipped 0.5.4 of hashi-ui which include live client resource view: https://github.com/jippi/hashi-ui/releases/tag/v0.5.4 :)

**Comment by OferE** [comment]
@jippi thanks a lot for making this happen. The ui looks very nice. it is very helpful to have such UI. the resource view is an important addition.

**Comment by eikenb** [comment]
I'm glad there is a 3rd party project as my concern with Atlas is that it breaks the one tool for one job unix-y model of the hashicorp tools. I'd like to see multiple UIs that work together, like the tools themselves, not one all encompassing dashboard which seems like it would be useless unless you use all the tools.

**Comment by jippi** [comment]
There has been tons of releases and enhancements to [hashi-ui](https://github.com/jippi/hashi-ui/releases) over the last 6 months too ! :) 

Really looking forward to see the real native nomad ui at some point too..the WIP looks sweet, been shamelessly copying some good ides!

**Comment by ashmckenzie** [comment]
nomad 0.7 beta now includes a sweet UI :)

**Comment by DingoEatingFuzz** [comment]
The Nomad UI is now in master at [/ui](https://github.com/hashicorp/nomad/tree/master/ui).

See screenshots here: https://www.nomadproject.io/guides/ui.html
