### ISSUE TITLE
github homepage link to download binaries of Nomad is broken

### ISSUE THREAD

**Issue by richard-mauri** [hashicorp/nomad#281]
https://github.com/hashicorp/nomad/blob/master/website/source/docs/install/index.html.md
broken downloads link: https://github.com/hashicorp/nomad/blob/master/downloads.html

What is the recommended url to the latest nomad binaries for Linux?
Thanks

**Comment by sethvargo** [comment]
https://nomadproject.io/downloads.html

**Comment by sethvargo** [comment]
Hey @richard-mauri 

The link is not broken, it's not designed to be viewed on GitHub. The project site is nomadproject.io and you can download the binaries from there :smile:
