### ISSUE TITLE
Allow percent for update -> max_parallel rolling upgrade

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2810]
On top of a normal `update -> max_parallel` static value

```hcl
update {
  max_parallel     = 3
  min_healthy_time = "30s"
  healthy_deadline = "2m"
}
```

It would be nice to have `update -> max_parallel` as a percent of the Task Group count 

```hcl
update {
  max_parallel     = "10%"
  min_healthy_time = "30s"
  healthy_deadline = "2m"
}
```

Slightly refs #2806

**Comment by djenriquez** [comment]
+1, any updates on this?

**Comment by joshuawscott** [comment]
I usually do something like
```
   max_parallel = max(floor(var.count * 0.5), 1)
```

where var.count is the count of the task groups.
