### ISSUE TITLE
Consul installation error when running Nomad in Vagrant

### ISSUE THREAD

**Issue by lucj** [hashicorp/nomad#2812]
### Nomad version
0.5.6

### Operating system and Environment details
Mac OS 10.12.2 / Virtualbox 5.1.6

### Issue

Error raised during Consul installation

```
==> default: Processing triggers for systemd (229-4ubuntu17) ...
==> default: Processing triggers for ureadahead (0.100.0-19) ...
==> default: Installing Consul...
==> default: bash: scripts/install_consul.sh: No such file or directory
==> default: install:
==> default: cannot stat '/opt/nomad/demo/vagrant/consul.service'
==> default: : No such file or directory
==> default: Failed to execute operation: No such file or directory
==> default: Failed to start consul.service: Unit consul.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Reproduction steps

Running ```vagrant up``` with [this Vagrantfile](https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile) as detailed in the [getting started page](https://www.nomadproject.io/intro/getting-started/install.html).

**Comment by lucj** [comment]
I have clone the repo and used this [Vagrantfile](https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile) in place of the default one (the one which involves 6 nodes).
I just changed the following line so it has the required *scripts* folder containing the script to install Consul.
```
config.vm.synced_folder '.', '/opt/nomad'
```

**Comment by schmichael** [comment]
I accidently changed the demo vagrantfile to only work when run from a cloned repo which is *not* the intended use. I'll get it fixed. Thanks for the bug report!
