### ISSUE TITLE
Nomad 0.6.0-rc1 release doesn't follow standard Hashicorp release structure

### ISSUE THREAD

**Issue by jvrplmlmn** [hashicorp/nomad#2814]
### Nomad version

0.6.0-rc1

### Operating system and Environment details

Linux amd64

### Issue

The zip file containing the Nomad `0.6.0-rc1` binary doesn't follow the same structure as the `0.5.6`. This breaks the automated download, unarchive and installation method that I've been using for Nomad. For reference, I also use the same method for Consul and Consul-template, where the zip files only contain the binary.

### Reproduction steps

`0.6.0-rc1`

```bash
$ wget https://releases.hashicorp.com/nomad/0.6.0-rc1/nomad_0.6.0-rc1_linux_amd64.zip
$ unzip nomad_0.6.0-rc1_linux_amd64.zip
Archive:  nomad_0.6.0-rc1_linux_amd64.zip
   creating: linux_amd64/
  inflating: linux_amd64/nomad
```

compared with `0.5.6`:

```bash
$ wget https://releases.hashicorp.com/nomad/0.5.6/nomad_0.5.6_linux_amd64.zip
$ unzip nomad_0.5.6_linux_amd64.zip
Archive:  nomad_0.5.6_linux_amd64.zip
  inflating: nomad
```

**Comment by dadgar** [comment]
Should be fixed! Sorry about that folks! That is what I get for deviating from the release script :(
