### ISSUE TITLE
Nomad 0.6.0-rc1: Panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mlehner616** [hashicorp/nomad#2820]
Gist attached

### Nomad version
Nomad v0.6.0-rc1 (5187fcfcae50e3dee61e5340eb99805a564b55c3+CHANGES)

### Operating system and Environment details
Amazon Linux 4.9.32-15.41.amzn1.x86_64

### Issue
Received the following crash while editing job, specifically, increasing/decreasing task group counts, on one server. Bringing up that failed server then resulted in a cascading failure of all other nomad servers. I was modifying the job quickly (likely before a previous evaluation had completed). There now appears to be a stuck evaluation or corrupt state and attempting to bring up all nomad servers fails with the same error.

### Nomad Server logs
https://gist.github.com/mlehner616/9e5fde395612f8ce82f942baf083e1fb

```
panic: runtime error: slice bounds out of range

goroutine 44 [running]:
github.com/hashicorp/nomad/scheduler.(*allocReconciler).computeGroup(0xc4203365b0, 0xc4204b5ee0, 0x11, 0xc4204a6420, 0xc4204a63f0)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/reconcile.go:393 +0x1592
github.com/hashicorp/nomad/scheduler.(*allocReconciler).Compute(0xc4203365b0, 0xc4206a4f00)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/reconcile.go:182 +0x1f1
github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computeJobAllocs(0xc4202225a0, 0xc420500180, 0xc421161c00)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:391 +0x3cc
github.com/hashicorp/nomad/scheduler.(*GenericScheduler).process(0xc4202225a0, 0xc420029800, 0xc4208de610, 0x7f379e424000)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:230 +0x53e
github.com/hashicorp/nomad/scheduler.(*GenericScheduler).(github.com/hashicorp/nomad/scheduler.process)-fm(0x64692e7865646e69, 0x0, 0x10)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:131 +0x2a
github.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc420b0be60, 0xc420b0be70, 0xc, 0xffffffffffffff01)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/util.go:268 +0x42
github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process(0xc4202225a0, 0xc4205db200, 0xc420480190, 0x1b3ec80)
	/opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:131 +0x2a0
github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc42045f680, 0xc4205db200, 0xc42032d5c0, 0x24, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/worker.go:291 +0x46d
github.com/hashicorp/nomad/nomad.(*Worker).run(0xc42045f680)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/worker.go:127 +0x127
created by github.com/hashicorp/nomad/nomad.NewWorker
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/worker.go:82 +0x126
```

**Comment by dadgar** [comment]
@mlehner616 What exactly do you mean on one server? Did you have a constraint pinning it to a specific client? Could you share the job file and reproduction steps if possible!

**Comment by dadgar** [comment]
@mlehner616 Did you have an update block on the job that caused the panic?

**Comment by mlehner616** [comment]
I have since rebuilt the cluster and have been unable to get the servers to crash again, despite trying. However, I did get the nomad client agents to crash using basically the same method. This happened as I was playing around with #2819. So the most information I have right now on reproducing this would be to constantly up and down the job count. The two values I was messing with were `max_parallel` and `count`. I was using hashi-ui to do things in quick succession like re-evaluate, flap the job count, increase and decrease the count, etc.

The job definitely had an update block (it seems like it's required, no?):

here's the resulting job after a consul-template run in CI process. I was modifying the job in place in hashi-ui after the initial evaluation.
```
job "example1" {
  datacenters = ["qa"]
  type = "service"
  constraint {
    attribute = "${node.class}"
    value     = "qa-infrastructure-cluster"
  }
  update {
    stagger = "5s"
    max_parallel = 1
  }
  meta {
    CI_COMMIT_REF_SLUG = "project-branch-name"
  }
  group "example1" {
    count = 6
    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }
    task "example1" {
      driver = "docker"
      env {
        NODE_ENV = "qa"
      }
      config {
        image = "1234567890.dkr.ecr.us-west-2.amazonaws.com/example1"
        # command = ""
        port_map {
          web = 3000
        }
      }
      resources {
        cpu    = 100 # 500 MHz
        memory = 256 # 256MB
        network {
          mbits = 1
          port "web" {}
        }
      }
      service {
        name = "example1"
        tags = ["qa", "example1"]
        port = "web"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

**Comment by mlehner616** [comment]
@dadgar also by one server I mean "nomad cluster server (scheduler)" crashed, not the nomad client nodes.

Here's my basic setup:
- 3 nomad cluster server (schedulers)
  - 1 of these failed originally, then the failure cascaded to all nodes soon after leader election started when the original failed server was restarted
- 3 nomad client nodes (docker hosts)
