### ISSUE TITLE
using cli registers a health check

### ISSUE THREAD

**Issue by aep** [hashicorp/nomad#2824]
when using nomad over ssh forwards
```
ssh  -L4646:nomad:4646 -L8500:consul:8500  bastion.mycloud
nomad status
```

nomad will register a service with address=127.0.0.1, which of course fails.

**Comment by schmichael** [comment]
I'm not sure I understand what's going on.

Does running `nomad status` register a health check in Consul? I'm unable to reproduce that and it should absolutely never happen.

**Comment by aep** [comment]
Correct. Every invoke will register a new health check.

This only happens when the machine that is being used as forward does run consul but not nomad. I.e. the nomad status cli client reaches both nomad and consul at localhost, although they.are really at different hosts each.

**Comment by schmichael** [comment]
What version of Nomad are you using?

**Comment by aep** [comment]
Master from 2 weeks ago. (Sorry on a smartphone atm)

**Comment by schmichael** [comment]
I'm unable to reproduce this and can't find anywhere on master where the `nomad status` code path communicates with Consul. I ran master with tcpdump/wireshark running and no traffic occurred on port 8500.

Perhaps there are some other details I'm missing?

**Comment by aep** [comment]
I'll try to verify that myself with Wireshark when I get to it. Possibly my assessment of the situation is incorrect and the healthcheck is registered elsewhere. Any ideas how to trace it would be welcome.

**Comment by dadgar** [comment]
Going to close in the mean time as there is no code path that would exercise this. @aep I would suggest just bringing up a new dev instance of nomad and consul and seeing that it wouldn't register a check!
