### ISSUE TITLE
Agent always detect node IOPS to 0

### ISSUE THREAD

**Issue by mildred** [hashicorp/nomad#2825]
When starting a nomad agent on a node, it detects the available IOPS on that node to 0. it doesn't seem there is a way to override that.

Either you should allow the nomad agent to override the detected IOPS available (you kave a `-network-speed` option to override the network speed) and document it, or you should remove the IOPS information from the documentation.

**Comment by jippi** [comment]
It's a documentation issue.. IOPS can be configured inside the client{} stanza on the nomad client (see [the source](https://github.com/hashicorp/nomad/blob/880ba14a96e8f2d0ab0583f5a6d08e98ac8998a0/command/agent/config.go#L429)]

**Comment by mildred** [comment]
Isn't the location you linked in the source code a configuration option about reserved resources ? https://www.nomadproject.io/docs/agent/configuration/client.html#reserved

> reserved (Reserved: nil) - Specifies that Nomad should reserve a portion of the node's resources from receiving tasks. This can be used to target a certain capacity usage for the node. For example, 20% of the node's CPU could be reserved to target a CPU utilization of 80%.

**Comment by jippi** [comment]
You are right @mildred - sorry :)

**Comment by schmichael** [comment]
Right now specifying IOPS in a job only affects `exec` jobs. For those it is used to directly set the `blkio.weight` cgroup: https://www.kernel.org/doc/Documentation/cgroup-v1/blkio-controller.txt

That cgroup only accepts a weight from 10-1000, so there's nothing to detect or set for the client.

It should become a more portable IOP provisioning system in the future, but it's use is limited today. Sorry for the confusion! Our docs definitely don't explain it correctly!

**Comment by schmichael** [comment]
Oops, but I neglected to notice that the scheduler treats IOPS as an absolute resource. So your bug is valid, and there's more to it than I originally suspected! Reopening.

**Comment by Miserlou** [comment]
>:[

It's been more than a year and the docs are still lying about this, is there anywhere to submit PRs to fix mistruthful docs?

**Comment by schmichael** [comment]
> is there anywhere to submit PRs to fix mistruthful docs?

Yes! You can submit a PR against [our entire website](http://nomadproject.io) as its located in the `website/` subdirectory: https://github.com/hashicorp/nomad/tree/master/website

The readme covers building/testing locally.
