### ISSUE TITLE
Nomad crashes when serialized state is partially removed

### ISSUE THREAD

**Issue by davidbirdsong** [hashicorp/nomad#283]
apologies if this was already reported. i looked and didn't find something similar.

this is after stopping nomad, wiping it's data dir, and attempting to start again:

```
=> /data/log/circusd/nomad-agent.stderr.log <==
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x516462]

goroutine 11 [running]:
github.com/hashicorp/nomad/nomad/structs.(*Allocation).TerminalStatus(0x0, 0xd37a00)
	/tmp/tmp_nomad/src/github.com/hashicorp/nomad/nomad/structs/structs.go:1126 +0x112
github.com/hashicorp/nomad/client.(*AllocRunner).Run(0xc82000cdc0)
	/tmp/tmp_nomad/src/github.com/hashicorp/nomad/client/alloc_runner.go:268 +0xa8
created by github.com/hashicorp/nomad/client.(*Client).restoreState
	/tmp/tmp_nomad/src/github.com/hashicorp/nomad/client/client.go:342 +0xbe7
```

nomad version: b83afeb889c3 (built from source)

After throwing a few panics and print statements around, `r.alloc` is nil here:
https://github.com/hashicorp/nomad/blob/master/client/alloc_runner.go#L267

but not here:
https://github.com/hashicorp/nomad/blob/master/client/client.go#L330

...I presume another goroutine?

**Comment by cbednarski** [comment]
Thanks for the report! I'm not familiar with the bootstrapping process but I don't think Nomad expects partial tampering with its internal state. We will probably need to do a `bootstrap-unless-exists` process.

For now if you remove all of the nomad directories you should be able to do a fresh run on the same node. This is what we do with the `-dev` flag.

**Comment by davidbirdsong** [comment]
ah, so to say I wiped the data dir is not entirely true. i wiped it of files not subdirectories. wiping all subdirectories helps.

thanks for the clarification.

**Comment by dadgar** [comment]
Closing as this is expected behavior. Can't partially tamper with the saved state.
