### ISSUE TITLE
Nomad fails to identify Vault renewal error as fatal

### ISSUE THREAD

**Issue by wlonkly** [hashicorp/nomad#2832]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
Ubuntu 16.06 (Xenial), Vault v0.6.4

### Issue
When issued a nonrenewable token, Nomad client fails to recognize the Vault error as fatal, and continues trying to renew the token.

This may be as simple as [this code](https://github.com/hashicorp/nomad/blob/87474b7c37ee3c20d666e78318a42ffc5366c179/client/vaultclient/vaultclient.go#L443-L450) not matching "lease is not renewable"? ie, it handles [this vault error condition](https://github.com/hashicorp/vault/blob/fafa9377f71a868b00ab3e9cf8168393f381e197/vault/expiration.go#L1012) but not [this one](https://github.com/hashicorp/vault/blob/fafa9377f71a868b00ab3e9cf8168393f381e197/vault/expiration.go#L1018).).

### Reproduction steps
1. Accidentally configure Vault's token role policy to issue nonrenewable tokens:
```-- root@stg-vault-app02:~ # vault read /auth/token/roles/clustermgr
Key                	Value
---                	-----
[...]
renewable          	false
```
2. Run a Nomad job which integrates with Vault
3. Wait for the Nomad client to attempt to renew the token lease

### Nomad Client logs (if appropriate)
```
Jul 13 20:53:36 stg-clustermgr-client30 nomad[1333]:     2017/07/13 20:53:36.804127 [ERR] client.vault: renewal of lease or token failed due to a non-fatal error. Retrying at 2017-07-13 20:53:49.804110836 +0000 UTC: failed to renew the vault token: Error making API request.
Jul 13 20:53:36 stg-clustermgr-client30 nomad[1333]: URL: PUT https://vault.query.consul:8200/v1/auth/token/renew-self
Jul 13 20:53:36 stg-clustermgr-client30 nomad[1333]: Code: 400. Errors:
Jul 13 20:53:36 stg-clustermgr-client30 nomad[1333]: * lease is not renewable
```

**Comment by dadgar** [comment]
Thanks for the great report. Will look into it 👍
