### ISSUE TITLE
nomad dev mode and boot2docker on OS X. Docker.endpoint doesn't seem to work

### ISSUE THREAD

**Issue by djsly** [hashicorp/nomad#284]
Hello. 

I saw that in master a new patch was done to rely on the DOCKER_* env var to connect to docker. 

In the meantime, what's the best approach to make it work with boot2docker. 

I tried creating a .hcl config file with 
'''
docker.endpoint = "tcp://host:port"
'''

My docker ps command works 
My sudo -E docker ps also works. 

When I do sudo -E nomad agent -dev I only get the exec and Java drivers.

**Comment by cbednarski** [comment]
@djsly `-dev` will not read a config file so currently there is not a way to do this. You can run without `-dev`, run on linux, build from master, or wait until the 0.2 release which will fix the `-dev` case. Sorry about that!

**Comment by djsly** [comment]
Thanks for this quick response. 
I got confused since at first my config file had syntax error and nomad bailed out saying invalid config. 
Maybe a warning should be printed out saying that -config will be ignored while the -dev is used ?  (All ignored flags actually)
I temember reading that with the -dev flag no other flags where needed but it was not cleared that they would be ignored. :)




Sent from Outlook on iPhone 




On Wed, Oct 14, 2015 at 4:57 PM -0700, "Chris Bednarski" <notifications@github.com> wrote:












@djsly -dev will not read a config file so currently there is not a way to do this. You can run without -dev, run on linux, build from master, or wait until the 0.2 release which will fix the -dev case. Sorry about that!
