### ISSUE TITLE
[Questtion] Can we modify and effect template on the fly?

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#2843]
### Nomad version
Nomad v0.5.6

### Questtion
When modify the template, I want  to manual/auto  trigger update the my process config template.
Now I must restart nomad, this will generate new template id. But my raw exec process will also restart. It will disconnect my production client connect.

Can we modify and effect  template on fly?

**Comment by dadgar** [comment]
Hey,

As I answered on the mailing list, the new template can be pushed with a `nomad run` of the job. The changes to the template are not done in-place and will result in a new allocation so it is not currently possible.
