### ISSUE TITLE
Scheduler not respecting rolling update

### ISSUE THREAD

**Issue by armon** [hashicorp/nomad#285]
See this mailing list post for context: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nomad-tool/CUhE_pFpAE4/cdT1CWezBgAJ

----

Summary:

When a job specification is updated with a change to both the container version and the count, the changes are applied immediately. I presume this happens because the change to count can be applied immediately, and supersedes the version rollout stagger preference. We would expect the container version to be applied as a rolling update to the running jobs.

These should be applied as independent deltas to the cluster state. Also, we should consider order of operations when _decreasing_ the cluster size and changing the version, and also what happens if an existing update is already rolling.

@cbednarski

**Comment by diptanu** [comment]
This should be fixed now.

**Comment by jsoriano** [comment]
It works great now for the "happy case", when the tasks start fine. But it still leaves all the tasks as dead if they fail to start. It'd be nice if it could revert the update if any of the updated tasks die (or cannot start) during the process.
And it'd be even nicer to support some kind of healthchecks that have to be passed before continue with the update :)
Are these features planned?

**Comment by diptanu** [comment]
@jsoriano Yes these are planned for future releases, it should be possible to keep tasks running if the update fails while doing a rolling deploy. I am creating a new ticket to track those enhancements to rollig deploy.

**Comment by diptanu** [comment]
Created #317 to track enhancements to rolling update.

**Comment by jsoriano** [comment]
Great, thanks!
