### ISSUE TITLE
[question] How to translate docker run statement to docker driver config

### ISSUE THREAD

**Issue by napolenli** [hashicorp/nomad#2869]
Hi, @dadgar 

Thanks for solving the mysql issue, for now it can start and run stably. As what I mentioned, I have been investigating nomad for my company, and trying to start our in-house app, the status with nomad status app_name shows running, and docker ps indeed shows running container, however, it keeps restarting, and the log content is limited.

### Nomad version
Nomad v0.5.6

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)

### Issue
How to start in-house app with nomad and docker as driver.

### Reproduction steps

> docker run -d \
  --name app_name \
  --net=host \
  --hostname=`hostname` \
  -e "ENV_VAR_1=ENV_VAL_1" \
  -e "ENV_VAR_2=ENV_VAL_2" \
  -e "ENV_VAR_3=ENV_VAL_3" \
  -v "$COMPANY_HOME:/folder" \
  $IMAGE_PATH:$TAG

I want to translate this to nomad config.

### Nomad Server logs (if appropriate)
Confidential

### Nomad Client logs (if appropriate)
Confidential

### Job file (if appropriate)
Company file, confidential...

**Comment by napolenli** [comment]
Since the app is springboot app, it just keeps showing starting the app, and container keeps restarting.

**Comment by napolenli** [comment]
Follow up on this question, I would like to map port 8190 to 8190 from container to public outside world, how should I do that? Thanks!

**Comment by napolenli** [comment]
@dadgar Hi, sorry for bothering you, but would you like to assist me on this question? Since I really want to finish the investigation of this problem this week.

If it can solve our problems well, we would like to purchase the enterprise version of some hashicorp products, currently we are using consul. I am working for Mobike Inc.

Thanks,
William

**Comment by shantanugadgil** [comment]
@napolenli 
jfyi ... https://www.hashicorp.com/products/nomad/
there seems to be a 'contact' button there for Enterprise inquiries. 😄   

About the ports:
https://www.nomadproject.io/docs/drivers/docker.html#allocating-ports

Environment Variables:
https://www.nomadproject.io/docs/job-specification/env.html

Note: The documentation can be a bit confusing at times as the "exact thing you are looking for" sometimes is on another page. 😀 
_I wish there was a "view this as a single page" option to the docs so I could search for a particular term all over the docs._

_Oh, and welcome to the wonderful world of Nomad, Happy exploring!_ 👍 

Cheers,
Shantanu

**Comment by napolenli** [comment]
Hi, @shantanugadgil , thank you for the response, I will take a look at the documentation first, and see whether I can solve the problems or not, will let you know if I have future questions. Definitely would like to use hashicorp products, actually did some experiments with packer in my previous company with VM initialization. Enjoyed it!

Best regards,
William

**Comment by napolenli** [comment]
Hi, @shantanugadgil , thank you for the docs, but I didn't find anything about port mapping in this doc, it is just saying that I can setup the internal port for the instance, however, I can not designate the port exposed to outside service. For example, I want to expose 6379 as 6379/6379, instead of some random port number allocated by nomad as 23323/6379.

Thanks!
William

**Comment by pieterbreed** [comment]
Hi William,

You need one of these to declare the port on the host _statically_:

```
      resources {
        network {
          port choosename {
            static = "6379"
          }
        }
      }
```

The in the docker driver section, you map the outside, statically declared port, to the internal port:

```
  task "servicename" {
    driver = "docker"
    config {
      port_map {
        choosename = 6379
      }
    }
  }
```

Please close the issue before you close the browser tab :-)

**Comment by dadgar** [comment]
Hey @napolenli 

To convert the docker run you gave would look like: 

```
task "app_name" {
  driver = "docker"
  config {
    image = "image:tag"
    network_mode = "host"
    hostname = "hostname"
    volumes = ["COMPANY_HOME:/folder"]
  }

  env {
      "env_var_1" = "env_value_1"
       ...
  }
}
```

You however can not set the name of the container as we automatically set it to ensure uniqueness across the host. You can find documentation for each of the settings here: https://nomadproject.io/docs/drivers/docker.html

I am going to close this issue but feel free to post a followup. I would prefer if you posted questions to the mailing list in the future! Glad you are enjoying HashiCorp products 👍

**Comment by napolenli** [comment]
Thank you so much, @dadgar @pieterbreed , the mysql container exposed with 3306 right now, however, still need help for in-house app deployment, talked with John and Donald yesterday, and my company is panning one corporation with HashiCorp. Thanks! But still I will ask questions here. :)
