### ISSUE TITLE
cli deployed overview wrong during canary

### ISSUE THREAD

**Issue by hsmade** [hashicorp/nomad#2871]
### Nomad version
Nomad v0.6.0-rc1 (eac3f49d1b8216b60b4d9357d04c82a9a7748acb)

### Operating system and Environment details
The repo's vagrant

### Issue
`Deployed` overview when waiting for promotion of canary task(s), only counts the canary for places/health/unhealthy
This is quite misleading as it seems like the original tasks have suddenly disappeared (they still show as running under `allocations` though.

### Reproduction steps
nomad init
set count to 3 and update to:

    update {
      stagger = "10s"
      max_parallel = 1
      health_check = "checks"
      auto_revert = true
      canary = 1
    }

Now run the example, change the docker image version to something else and run the job again.
Output of `nomad status example` is now:

    ID            = example
    Name          = example
    Submit Date   = 07/20/17 08:11:46 UTC
    Type          = service
    Priority      = 50
    Datacenters   = dc1
    Status        = running
    Periodic      = false
    Parameterized = false

    Summary
    Task Group  Queued  Starting  Running  Failed  Complete  Lost
    cache       0       0         4        0       3         0

    Latest Deployment
    ID          = 996b965d
    Status      = running
    Description = Deployment is running but requires promotion

    Deployed
    Task Group  Auto Revert  Desired  Canaries  Promoted  Placed  Healthy  Unhealthy
    cache       true         3        1         false     1       1        0

    Allocations
    ID        Node ID   Task Group  Version  Desired  Status    Created At
    965d26b2  c922735c  cache       2        run      running   07/20/17 08:11:46 UTC
    66c938bb  c922735c  cache       1        run      running   07/20/17 08:08:32 UTC
    2a8fbefc  c922735c  cache       1        run      running   07/20/17 08:08:19 UTC
    e6b5c092  c922735c  cache       1        run      running   07/20/17 08:04:09 UTC

I would expect the placed and healthy to be 4 here.

**Comment by dadgar** [comment]
Hey,

It is actually showing the desired output. The deployment is going to create 3 allocations and it has created 1 of them and that one is healthy. The allocations from an older deployment aren't considered. You could view the status of those by running `nomad deployment status <id>`
