### ISSUE TITLE
Nomad doesn't bump version on rc2 binary

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#2882]
When we download binary it `nomad version` is still rc1

**Comment by shantanugadgil** [comment]
same here

**Comment by dadgar** [comment]
Should be fixed.

**Comment by shantanugadgil** [comment]
@dadgar  not a biggie, but the download from releases still has the following in the version:

```
./nomad version
Nomad v0.6.0-rc1 (6e315f945d4f8db6725e21b9b16cc9bb44ada974+CHANGES)
```

I downloaded on 3 different machines using wget.

Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil Hey! It was just the CDN cacheing :(

Tho the only thing that was different between the binaries was the version! So even that version would have been fine 👍
