### ISSUE TITLE
Failed/left agents never deregister from Consul

### ISSUE THREAD

**Issue by mlehner616** [hashicorp/nomad#2891]
### Nomad version
nomad 0.6.0rc2 (Nomad was doing this since at least 0.5.6 or before)

### Reproduction steps
Terminate a nomad agent node (client or server), or run `nomad server-force-leave`

### Issue
When a nomad agent (client or server) "fails, leaves, or most likely scaled in" it never deregisters from Consul due to some HTTP health checks remain incorrectly passing although the serf health check is failing as expected. What seems strange about this is that the IPs listed in the Consul check don't even have listening instances after the scale-in event. This behavior only appears to affect Nomad which is what leads me to believe it's in an issue with the way nomad registers with Consul.

Manual curl run from healthy consul server which times out as expected
```
[user@qa-consul-0d2b38c891e622c31 ~]$ curl http://192.177.177.212:4646/v1/status/peers
curl: (7) Failed to connect to 192.177.177.212 port 4646: Connection timed out
```

Actual Consul status screenshots
<img width="800" alt="screen shot 2017-07-23 at 9 16 05 am" src="https://user-images.githubusercontent.com/689476/28501050-465461c8-6f88-11e7-8083-d058a1ccfb85.png">

<img width="778" alt="screen shot 2017-07-23 at 9 17 00 am" src="https://user-images.githubusercontent.com/689476/28501051-51b517ec-6f88-11e7-8927-4e4ab84ad1f2.png">

**Comment by schmichael** [comment]
Thanks for the report! The agent isn't getting deregistered on shutdown, but I do see the checks failing as expected:

<details>

```json
[
    {
        "Name": "Nomad Server Serf Check",
        "Output": "dial tcp 0.0.0.0:4648: getsockopt: connection refused",
        "ServiceID": "_nomad-server-nomad-serf",
        "ServiceName": "nomad",
        "ServiceTags": [
            "serf"
        ],
        "Status": "critical"
    },
    {
        "Name": "Nomad Server RPC Check",
        "Output": "dial tcp 0.0.0.0:4647: getsockopt: connection refused",
        "ServiceID": "_nomad-server-nomad-rpc",
        "ServiceName": "nomad",
        "ServiceTags": [
            "rpc"
        ],
        "Status": "critical"
    },
    {
        "Name": "Nomad Server HTTP Check",
        "Output": "Get http://0.0.0.0:4646/v1/status/peers: dial tcp 0.0.0.0:4646: getsockopt: connection refused",
        "ServiceID": "_nomad-server-nomad-http",
        "ServiceName": "nomad",
        "ServiceTags": [
            "http"
        ],
        "Status": "critical"
    }
]
```

</details>
