### ISSUE TITLE
Nomad 0.6.0-rc1 nodes crashing on a load test

### ISSUE THREAD

**Issue by sprutner** [hashicorp/nomad#2893]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
`Nomad v0.6.0-rc1 (5187fcfcae50e3dee61e5340eb99805a564b55c3+CHANGES)`
### Operating system and Environment details
`Ubuntu 16.04 LTS`
### Issue
We hit our nodes with high load to drop the memory to near zero on the nodes and trigger scale-out of ASG. then we posted a 100 container job spec for the service, and it was delivering fine with zero errors.

I went to change an env variable and was getting all sorts of errors below. It was still serving requests OK but I seem to have lost control of the jobs. The ASG scaled down and it was running nearly out of memory. When I tried to change the job spec I was hit with lots of different errors depending on which instance the ELB routed me to. Sometimes I could get the server-members but it seemed like the majority of server-members did not want to respond.

For the first 15 minutes it still had a healthy appearing cluster After about 15 minutes now there is only one server-member, the cluster has destroyed itself. It seems like there was a restart loop on one of the server-members and this cascaded into crashing other server-members leading to a bunch of restart loops...It seems to get exponentially worse, now there is no cluster-leader.

API Side:
`rpc error: EOF`
`rpc error: failed to get conn: dial tcp 10.104.20.31:4647: getsockopt: connection refused`
or simply 'no response'

CLI Side:
`$ nomad server-members
Error determining leaders: Get http://nomad.credodev.dev/v1/status/leader?region=global: EOF`

or

`Error determining leaders: Unexpected response code: 500 (rpc error: failed to get conn: dial tcp 10.104.20.214:4647: getsockopt: connection refused)`

or

`Error determining leaders: Unexpected response code: 500 (rpc error: failed to get conn: dial tcp 10.104.21.74:4647: getsockopt: connection refused)`

See gist of logs below for what was happening on server side.

### Nomad Server logs (if appropriate)
https://gist.github.com/sprutner/270583dc97a50d53493a3b6ab5722e3c

### Nomad Client logs (if appropriate)
https://gist.github.com/sprutner/e22e250a70b061974f148f86302b5854

**Comment by dadgar** [comment]
@sprutner Looks like you hit a panic fixed in 0.6.0-rc2.

**Comment by sprutner** [comment]
Ah okay, I figured as much. I will roll an update.

**Comment by dadgar** [comment]
Sweet! @sprutner I am going to close this but please hammer rc2 👍 Thanks for reporting!!
