### ISSUE TITLE
Support runtime resource usage metrics in Docker for Windows

### ISSUE THREAD

**Issue by cstavro** [hashicorp/nomad#2897]
Nomad currently assumes the Docker stats it retrieves are coming from Linux. When running under Windows however, the metrics are somewhat different and at the moment Nomad just ignores them.

Nomad should collect these metrics and make them available via the allocation stats view as well as output the metrics to the telemetry endpoint so that it can be leveraged externally to Nomad.

Relevant links:
- https://github.com/moby/moby/pull/25737
  - This is the PR that adds stats support to Docker for Windows
- https://github.com/fsouza/go-dockerclient/pull/663
  - This PR adds support for the Windows metrics into the underlying docker-lib that Nomad is using
- https://technet.microsoft.com/en-us/library/ff382715.aspx
- https://docs.docker.com/engine/admin/runmetrics/#metrics-from-cgroups-memory-cpu-block-io

**Comment by schmichael** [comment]
Thanks for the report. This won't make it into 0.6, but hopefully we'll be able to add it soon!
