### ISSUE TITLE
[Improvement] global logging options for docker driver

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#2904]
Hi,
In the current implementation there is no simple way to ship logs with additional information like task, group or job names to the central server.
Available options were described here: https://github.com/hashicorp/nomad/issues/2631#issuecomment-300473671
The most flexible and in fact the only option for central logging is configuring logging per task.
In this case your must configure log options for each tasks.
It's not very easy to keep it in sync with lots of tasks.
I guess it would be much easier to customize logging behavior in the global config.
Something like:
```
client {
  options {
    "docker.logging.syslog.syslog-address" = "tcp://syslog.server:514"
    "docker.logging.syslog.tag" = "{{.ImageName}}/{{.Name}}"
  }
}
```

Another option is to implement log forwarding from built-in syslog server to remote or local server with adding tag that contains task/group/job name.

**Comment by Xopherus** [comment]
Is this not possible now with https://www.nomadproject.io/docs/drivers/docker.html#logging ?

```hcl
config {
  logging {
    type = "syslog"
    config {
      syslog-address: "udp://1.2.3.4:1111"
      tag = "{{.ImageName}}/{{.Name}}"
    }
  }
}
```
I assume this would work!

As an aside, one kind of annoying thing (at least for my use case) is that docker names are a combination of task + uuid. It would be great to either add job + group to the docker name, or have an additional tag that could be added at container creation. It's pretty common for task names to be common across jobs, which can make it difficult to filter.

**Comment by eigengrau** [comment]
@Xopherus it looks like this only works when specified in each job individually. It would be preferable if Docker logging options could be set globally (at least as defaults) for all tasks in the agent configuration.

**Comment by gaspo53** [comment]
Hi. Yes, Driver's global configs (and overriden by each stanza) would be really really useful. Is this on the Nomad roadmap?

**Comment by bjornicus** [comment]
it looks to me like the global docker settings are applied as default, and merged with settings in the job definition.  I have:

`$ cat /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "raw-logs" : true,
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  }
}`

and my job definition has 
`        logging {
          type = "json-file"
          config {
            tag = "app.web-unified"
          }
        }
`

and when I do docker inspect of the container on the host machine I get:
`
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "10",
                    "max-size": "10m",
                    "tag": "app.dashboard"
                }
            },
`

perhaps that just needs to be mentioned in the docs? Or maybe some users don't have the option to customize the docker daemon config, but if you do this appears to be a workable approach.

**Comment by apollo13** [comment]
Hi all, I think I fixed this as part of https://github.com/hashicorp/nomad/pull/10156 -- can you verify and if that is true close this issue?

**Comment by tgross** [comment]
Yup, thanks @apollo13!
