### ISSUE TITLE
Build Issue - path of codecgen

### ISSUE THREAD

**Issue by ethandrower** [hashicorp/nomad#2912]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Not installed,  attempting current version

### Operating system and Environment details
.virtualenv)root@mark-vm:/usr/local/go/bin/src/github.com/hashicorp/nomad# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

### Issue
Errors trying to build from the repo.  Please see steps below.

### Reproduction steps
.virtualenv)root@mark-vm:/usr/local/go/bin/src/github.com/hashicorp/nomad# make bootstrap
Installing github.com/kardianos/govendor
Installing github.com/mitchellh/gox
Installing golang.org/x/tools/cmd/cover
Installing github.com/axw/gocov/gocov
Installing gopkg.in/matm/v1/gocov-html
Installing github.com/ugorji/go/codec/codecgen
Installing github.com/hashicorp/vault (test dependency)
(.virtualenv)root@mark-vm:/usr/local/go/bin/src/github.com/hashicorp/nomad# make dev
--> Running go fmt
--> Running go generate
command/agent/fs_endpoint.go:3: running "codecgen": exec: "codecgen": executable file not found in $PATH
nomad/structs/structs_codegen.go:3: running "codecgen": exec: "codecgen": executable file not found in $PATH
make: *** [generate] Error 1

Any ideas?  Tried adding manually to path.

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin/src/github.com/ugorji/go/codec/codecgen:/usr/local/go/bin/src/github.com/ugorji/go/codec:

**Comment by dadgar** [comment]
Hey @ethandrower,

Sorry I won't be able to give to great of advice but you do just need it in the path. By default it is installed under $GOPATH/bin. This is how go binaries get installed by default so it is worth just adding that to your path and then sourcing your bashrc/profile/etc and trying again!

Good luck!
