### ISSUE TITLE
job post by http got json error

### ISSUE THREAD

**Issue by zsluedem** [hashicorp/nomad#2925]
### Nomad version
Output from `Nomad v0.6.0`

### Operating system and Environment details
mac os
### Issue
I run the nomad with consul
below is the start conf
`
bind_addr = "0.0.0.0" # the default

data_dir  = "/datapath/nomad"

advertise {
  http = "0.0.0.0"
}

server {
  enabled          = true
  bootstrap_expect = 3
}

client {
  enabled       = true
  network_speed = 10
  options {
    "driver.raw_exec.enable" = "1"
  }
}
`

when i try to post a job from the doc https://www.nomadproject.io/api/json-jobs.html,i got the http error.

status code:400
content: json: cannot unmarshal string into Go value of type api.JobRegisterRequest

**Comment by dadgar** [comment]
@zsluedem Sorry you ran into that. I just made this PR https://github.com/hashicorp/nomad/pull/2926 to make the example job submittable.

Previously it was just trying to show many of the possible fields but would not be submittable. This PR makes the job submittable and gives an example of how. Let me know if that resolves this for you and we can close the issue?

**Comment by zsluedem** [comment]
@dadgar thanks!!
I wonder what is wrong with this json.

**Comment by zsluedem** [comment]
I think you should put the submittable example in https://www.nomadproject.io/api/jobs.html on `/v1/jobs` `POST method` `sample payload`

**Comment by zsluedem** [comment]
i pull a request to add then sample doc #2931

**Comment by dadgar** [comment]
@zsluedem Can we close this out now that we have improved the docs?

**Comment by zsluedem** [comment]
@dadgar yeah~!forgot to do that
