### ISSUE TITLE
[question] Is there a hashicorp maintained docker image for nomad?

### ISSUE THREAD

**Issue by jason-riddle** [hashicorp/nomad#2930]
It would compliment the consul and vault docker images nicely for doing things like demos or integration testing.

**Comment by dadgar** [comment]
Hey @jason-riddle,

There is no official image for running Nomad in a container. We actually do not advise doing this in general with Nomad. It would be akin to running the Docker Engine in a docker container as Nomad clients actually manipulate many of the same isolation primitives as Docker.

We need access to the host and elevated permissions so there are few advantages to running in a container and many downsides.

Thanks!
