### ISSUE TITLE
Support configurable addresses in Nomad services

### ISSUE THREAD

**Issue by dradtke** [hashicorp/nomad#2941]
### Nomad version
Output from `nomad version`: **0.6.0**

### Issue

The `service` stanza supports defining [address_mode](https://www.nomadproject.io/docs/job-specification/service.html#address_mode), but in certain cases the address itself needs to be set manually. In particular, it's not possible to define a service that advertises itself on `eth1` instead of `eth0`, which appears to be a requirement when developing in a Vagrant cluster.

### Reproduction steps

For context, here is the output of `ip addr` on one of the boxes in my cluster, which runs a dedicated service:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:25:12:db brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe25:12db/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:36:b1:e9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.23/24 brd 192.168.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe36:b1e9/64 scope link
       valid_lft forever preferred_lft forever
```

Since Nomad picks the first available private IP for service advertisement, `eth0` (10.0.2.15) is chosen to advertise my service. However, that IP is not accessible by other machines in the cluster, presumably because of its [requirement as NAT](https://github.com/mitchellh/vagrant/issues/2093), though I'm not sure if that's the case. It is pingable, but any attempt to access an HTTP service results in a "connection refused" error, even after disabling the firewall. `eth1` (192.168.0.23), which is a defined public IP in my Vagrantfile, however, works flawlessly.

This type of thing is configurable for the Nomad agent itself using [go-sockaddr/template](https://godoc.org/github.com/hashicorp/go-sockaddr/template); in this specific case, I would like the ability to define my service like this:

```
service {
    port = "http"
    address = "{{ GetInterfaceIP `eth1` }}"
}
```

which would make the service advertise itself on `eth1`.

While I think this feature would be generally useful, an alternative fix for my particular use case would be to get `eth0` to work as a service address, but I'm not sure if that's something that's doable with Vagrant.

**Comment by schmichael** [comment]
Setting this in your client configuration should get the behavior you're looking for:

```hcl
client {
  network_interface = "eth1"
}
```

Our long term solution is going to be network plugins which will be able to define what IP address to advertise similar to the `address_mode = driver` added in Nomad 0.6. We want to avoid specifying host interfaces in job files as much as possible as it hurts portability of a job across hosts. The network plugin should be able to report the proper address to advertise.

**Comment by dradtke** [comment]
Great, that worked! For anyone who's curious, in order to get communication working for both the service and the Nomad agent, I ended up using this as my solution:

```hcl
advertise {
        http = "{{ GetInterfaceIP `eth1` }}"
        rpc = "{{ GetInterfaceIP `eth1` }}"
        serf = "{{ GetInterfaceIP `eth1` }}"
}

client {
        enabled = true
        network_interface = "eth1"
}
```

Without `network_interface`, the service advertised the wrong address, and without the `advertise` block, the Nomad agent itself advertised the wrong address. With both of these set, everything works as expected.

**Comment by winduptoy** [comment]
@dradke I've configured my nomad agent exactly as you describe, but my `network_interface` is a virtual interface for a VPN rather than a physical interface. When running a job I get "network resources exhausted for node" from nomad. Did you happen to run into that in your scenario?

**Comment by c4milo** [comment]
@schmichael `network_interface` doesn't seem to be working for me in 0.8.3.

**Comment by GoingFast** [comment]
same. had to put `address_mode = "driver"` to the service
