### ISSUE TITLE
Improve logging for unhealthy allocations

### ISSUE THREAD

**Issue by publysher** [hashicorp/nomad#2944]
Nomad 0.6

While trying out the new deployment features, I'm running into failures due to unhealthy allocations. However, when I query Consul myself, it reports all services as healthy. 

Turning on debug logging for both the Nomad client and the server is not helping me much. I'm getting a lot of 

```
client.alloc_watcher: continuing since all checks (want 1; got 0) haven't been registered for alloc "e82c4dec-64a7-231e-d829-74026965f4ec"
```

messages in my Nomad client, and that's it. 

It would be nice to know

* the IDs of the failing health checks
* the reason this check is regarded as failing 
* in case of HTTP endpoints: the exact endpoint that is being called

**Comment by dadgar** [comment]
Hey,

That message means that the check hasn't even been registered in Consul yet. You should take a look at `nomad alloc-status` to see if the task has been started? You may want to consider increasing the health deadline.

**Comment by aroca** [comment]
Hey Armon!

I kinda had this same issue. I had a typo in the service check port so the check was unhealthy. I fixed that and make a plan and then a run. As you mentioned, the allocation never happened but the service check in Consul was registered and Healthy.
The only thing i saw was 

```Latest Deployment
ID          = cdfd4c05
Status      = failed
Description = Failed due to unhealthy allocations
```

and 

```Deployed
Task Group  Desired  Placed  Healthy  Unhealthy
search      1        1       0        1
```

I stopped the Job.. then run it, and it was allocated perfect.

Cheers!

**Comment by filip-vt** [comment]
improved visibility on _why_ an allocation gets "Failed due to unhealthy allocations" would be really helpful

**Comment by ao10** [comment]
> improved visibility on _why_ an allocation gets "Failed due to unhealthy allocations" would be really helpful

Still would like to see this

**Comment by bplunkert** [comment]
I would also like to see this. Port in tcp service check is open, Nomad provides no details why the allocation is failed. I can only assume it is due to a service check but there are no details provided.

**Comment by echan00** [comment]
same here, no idea why my deployment is failing
