### ISSUE TITLE
nomad agent -dev fails on Windows

### ISSUE THREAD

**Issue by ChrisHines** [hashicorp/nomad#295]
OS: Windows Server 2012 R2 Standard
ARCH: amd64

```
C:\>nomad version
Nomad v0.1.2

C:\>nomad agent -dev
==> Starting Nomad agent...
2015/10/16 13:02:05 [ERR] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
==> Error starting agent: client setup failed: driver setup failed: Get http://unix.sock/version: dial unix /var/run/docker.sock: socket: An address incompatible with the requested protocol was used.
```

**Comment by dadgar** [comment]
PR #225 should fix that issue. This has not made it into one of our pre-compiled binaries however. Let me know if it still doesn't work on HEAD.

**Comment by ChrisHines** [comment]
Yes, I am just getting started with the pre-compiled binaries and didn't see a previous issue about this.

I won't be able to test HEAD until I get Nomad building from source.

**Comment by ChrisHines** [comment]
I have built nomad from source:

```
C:\gopath>go get -u github.com/hashicorp/nomad

C:\gopath\src\github.com\hashicorp\nomad>git describe --always
v0.1.2-173-g29ce6e0
```

After copying the resulting binary to the server it still doesn't work, but it gives a different error now:

```
D:\nomad>nomad agent -dev
==> Starting Nomad agent...
2015/10/16 15:37:22 [ERR] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
==> Error starting agent: client setup failed: driver setup failed: Get http://127.0.0.1:2375/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**Comment by cbednarski** [comment]
@ChrisHines When the driver fails to fingerprint it should simply deactivate. This failure scenario seems to be happening a bit differently on Windows. We'll get this fixed up. Thanks for the report!
