### ISSUE TITLE
[question] Internal Communication In B/W Container

### ISSUE THREAD

**Issue by mqasim1983** [hashicorp/nomad#2967]
Hi,

I have 2 containers running on port 80 (I know nomad expose random port outside) and from Fabio using urlprefix the traffic is routing properly but from container A I can not using curl -I http:container-B/.
I know I can expose a static port for both containers. is it possible the communication in b/w containers stays on port 80.

Thanks

**Comment by schmichael** [comment]
Hi @mqasim1983,

If you're using Consul to advertise your services and their random ports, containers can look up one another's IP and port in Consul via the [HTTP API](https://www.consul.io/api/catalog.html#list-nodes-for-service) or [DNS SRV records](https://www.consul.io/docs/agent/dns.html#service-lookups).

You can also use [static ports](https://www.nomadproject.io/docs/job-specification/network.html#static) to make things easier. Although for both to listen on port 80 they'd need to get scheduled on different nodes.

There are various overlay networks - such as weave - which provide each container with their own IP so they can communicate over port 80, but there are other complexities involved in using an overlay network.

**Comment by schmichael** [comment]
Closed but feel free to reopen if I didn't answer your question!
