### ISSUE TITLE
[docs] Placement information is missing from task stanza

### ISSUE THREAD

**Issue by dvusboy** [hashicorp/nomad#2970]
### Nomad version
N/A
Current documentation available at https://www.nomadproject.io/docs/index.html

### Operating system and Environment details
N/A

### Issue
The [`task` stanza documentation](https://www.nomadproject.io/docs/job-specification/task.html) does not have any `Placement` information. I was reading on the `job` stanza documentation when I noticed the [`job Parameters section](https://www.nomadproject.io/docs/job-specification/job.html#job-parameters) does not contain `task`, but the snippet above does.

BTW, if `task` can be placed under `job` directly, does it *not* support `restart`?

**Comment by dadgar** [comment]
Thanks for filing @dvusboy.

If you embed the task in the job, you can only use the defaults for fields that are settable in the group.
