### ISSUE TITLE
[docs] /v1/node/:id/allocations is not documented

### ISSUE THREAD

**Issue by koikonom** [hashicorp/nomad#2978]
I noticed that the nomad CLI client makes a call to /v1/node/:id/allocations when a user passes `-allocs` as a parameter to `nomad node-status` (see https://github.com/hashicorp/nomad/blob/master/api/nodes.go#L57).

This endpoint is not documented in https://www.nomadproject.io/api/nodes.html and I think it should be.

**Comment by dadgar** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/2980
