### ISSUE TITLE
No longer able to restrict ports nomad uses for services

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#2981]
### Nomad version
Nomad 0.6.0

### Issue

We used to be able to restrict the port list that nomad will run services on via the "reserved" keyword see here - https://github.com/hashicorp/nomad/issues/1087.  Unfortunately, that config seems to be gone, leaving us without any way to do this.   The trouble comes when I need to open ports to the world for a service, but don't want to open the full range of possible ports on a machine due to other services running on it.   

Thanks!

**Comment by dadgar** [comment]
@dansteen Sorry I am not quite following. I don't think anything has changed that would have let you do it before and not now? What exactly are you referring to? The reserved field is still there: https://www.nomadproject.io/docs/agent/configuration/client.html#reserved

**Comment by dansteen** [comment]
Hi @dadgar ,

Thanks for the reply!   My understanding was that I could reserve cpu, disk space, and network bandwidth with that config.   Can I also reserve ports using that?  What would the config look like?

Thanks!

**Comment by dansteen** [comment]
Oh!  whoops.  Looks like it gives examples a bit further down.  Sorry about that. Thanks!
