### ISSUE TITLE
[Improvement] Add ability to honor certificate revocation list when `verify_https_client` is enabled

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#2996]
It would be great to have an ability to manage clients certificates.
And traditional method for this case is certificate revocation.
For now there is no way to manage user's certificate. In fact current implementation is like a "master-password" that you can't change.

**Comment by dadgar** [comment]
Hey @pznamensky,

Nomad 0.7 will be bring ACLs and you will be able to revoke tokens. This is the approach we will be recommending. mTLS on the HTTP is in my opinion a work around until ACLs.

Thanks,
Alex
