### ISSUE TITLE
documentation error on interpolations page

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#2997]
Hi!

The documentation page here https://www.nomadproject.io/docs/runtime/interpolation.html#node-variables- says that the following variables are available:
```
attr.platform.aws.ami-id
attr.platform.aws.instance-type
```
This should be:
```
attr.unique.platform.aws.ami-id
attr.unique.platform.aws.instance-type
```

Thanks!

**Comment by dadgar** [comment]
Hey closing this as https://github.com/hashicorp/nomad/pull/2999 fixes the ami-id and instance-type is actually not unique.

Thanks @dansteen
