### ISSUE TITLE
Resource constraints for exec

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/nomad#30]
On Linux we can use cgroups to constrain resource usage. There is initial support and documentation for this feature in the Docker driver, but we should extend it to other drivers.

Questions:
- Is there a good cgroups library for go? If not we can use the `cg*` tools but will need to note that they are an external dependency that must be installed on the system in advance.

Docs:
- [x] [Linux](https://www.kernel.org/doc/Documentation/cgroups/cgroups.txt)
- [ ] [Darwin](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/setrlimit.2.html)
- [ ] [BSD](https://www.freebsd.org/doc/handbook/security-resourcelimits.html)
- [ ] [Windows](https://technet.microsoft.com/en-us/library/hh997019.aspx)

/cc @catsby

**Comment by zrml** [comment]
https://github.com/jeffbmartinez/docker/blob/master/cgroups/cgroups.go  maybe??

this one https://github.com/vbatts/go-cgroup is just a C lib wrapper.
or
how about opencontainers/runc ?
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/cgroups.go

HTH

**Comment by zrml** [comment]
jsut saw this simple one
https://github.com/s-kostyaev/go-cgroup/blob/master/cgroup.go

**Comment by nathwill** [comment]
[systemd-run](http://www.freedesktop.org/software/systemd/man/systemd-run.html) is probably a good way to provide resource-control for the exec driver as well, used like `systemd-run -p BlockIOWeight=10 updatedb`

**Comment by cbednarski** [comment]
Linux has been implemented using `runc` since Nomad 0.1. We'll be looking at ways to do this for other operating systems going forward.

**Comment by nathwill** [comment]
:+1:

**Comment by ChrisHines** [comment]
I am not sure the Windows information linked to above is the best approach for Nomad. Have you considered using [Job Objects](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684161(v=vs.85).aspx)? I think that API may be a better fit.

**Comment by cbednarski** [comment]
@ChrisHines Thanks for the tip! This looks great. I'm a complete novice at win32, unfortunately, but I'll do some reading about this.

**Comment by ChrisHines** [comment]
@cbednarski I may be able to help out here, once I'm more up to speed with the Nomad code base. I have written (in Go) a service similar to the nomad client for our current cluster manager that we run in a mixed Windows/Linux cluster. We are evaluating Nomad as a replacement down the road and are prepared to contribute code to help it meet our needs.

So far I have not used JobObjects for resource limits or reporting (our current system doesn't model such things well), but I have used them effectively for reliably killing entire process trees spawned by a task.

**Comment by dadgar** [comment]
@ChrisHines contributions are always welcome :)

**Comment by rore** [comment]
@ChrisHines Was there any progress in applying resource constraints on Windows? We're considering Nomad on Windows and this will be a real improvement.

**Comment by ChrisHines** [comment]
No I did not get time to work on that, and unfortunately I am no longer in a position to work on it any time soon.

**Comment by diptanu** [comment]
Closing this issue in favor of opening platform specific issues.

**Comment by rore** [comment]
@diptanu Is there a new issue about this? Couldn't find any.

**Comment by diptanu** [comment]
@rore I had asked someone to open a ticket to track the work around supporting resource isolation using the exec driver on Windows. I might work on the FreeBSD platform when I get time and if there is enough demand for that from the community. Darwin is probably never getting support for exec driver since there is not enough demand and use case.

**Comment by rore** [comment]
Thanks. We are looking for Windows support so will be happy to see it included :-)
