### ISSUE TITLE
nomad alloc-status typo

### ISSUE THREAD

**Issue by rvm2015** [hashicorp/nomad#301]
Usage: nomad alloc-stauts [options] <allocation> <--alloc-stauts insead of alloc-status, master as of a few minutes ago

    AC02MK0LSFD58:~ rvm2015$ nomad alloc-status
    Usage: nomad alloc-stauts [options] <allocation> <--alloc-stauts insead of alloc-status

      Display information about existing allocations. This command can
      be used to inspect the current status of all allocation,
      including its running status, metadata, and verbose failure
      messages reported by internal subsystems.

**Comment by F21** [comment]
Master looks fine to me: https://github.com/hashicorp/nomad/blob/master/command/alloc_status.go#L14

**Comment by dadgar** [comment]
Thanks for filling this. Closing as it is fix on head
