### ISSUE TITLE
nomad node-status <node id> should show capabilities and cpu/memory max/available

### ISSUE THREAD

**Issue by rvm2015** [hashicorp/nomad#303]
Related to #302 it would be helpful when trying to troubleshoot bugs and setup issues if there was an easy way to see node capabilities and resource availability. Sometimes it's hard to tell if something is failing to allocate because there is an actual problem or if nomad is simply not seeing some resources it actually does have available.

**Comment by achanda** [comment]
I'd prefer a new `nomad node-show <id>` command. Showing resources in `node-status` might be a little cluttered.

**Comment by feliksik** [comment]
This makes sense not only for troubleshooting,  but also to build a monitoring/status listing or graphical frontend that shows the cluster utilization. Compare the DCOS overview page,  which shows CPU/mem utilization in partial circles.
