### ISSUE TITLE
[bug/question] LC_ALL set to C on executors when using raw driver

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#3036]
Not sure if this intentional or a golang thing or what. It's breaking a script that assumes stdout is UTF-8 encoded. I can work around it, but I don't really expect the executor to work this way without a reason.

### Nomad version
Nomad v0.6.0

### Operating system and Environment details
3.10.0-327.36.3.el7.x86_64

### Issue
The nomad executor has the following environment variables set in addition to the ones set on the agent
```
LC_ALL=C
NOMAD_PLUGIN_MAGIC_COOKIE=e4327c2e01eabfd75a8a67adb114fb34a757d57eee7728d857a8cec6e91a7255
PLUGIN_MIN_PORT=14000
PLUGIN_MAX_PORT=14512
```

LC_ALL being set that way breaks a script I'm using which normally assumes UTF-8. I can override if necessary, just wondering if this is intentional or not.

### Reproduction steps
Reproduced with the following nomad job:
```
job "lc-wat" {
  region = "integ"
  datacenters = ["dc1"]
  type = "batch"
  task "wtf" {
    driver = "raw_exec"
    config {
      command = "bash"
      args = ["-c","echo $LC_ALL"]
      }
    }
  }
```

### Nomad Client logs (if appropriate)
Output is "C"

**Comment by dadgar** [comment]
@nugend Is it an environment variable that you are starting Nomad with. The env-vars are passed through from the host. You can restrict that using either a white or black list: https://www.nomadproject.io/docs/agent/configuration/client.html#quot-env-blacklist-quot-

**Comment by nugend** [comment]
@dadgar Nope.

```
bash-4.2$ pgrep -f ".*nomad agent.*"
10844
bash-4.2$ ps -fp 10844
UID        PID  PPID  C STIME TTY          TIME CMD
REDACTED+ 10844 10839  5 Aug07 ?        10:41:45 nomad agent -data-dir /REDACTED/data/nomad -config /REDACTED/cfg/hosts/REDACTED/nomad
bash-4.2$ pgrep -f ".*nomad agent.*" | xargs -L1 -I{} bash -c "cat /proc/{}/environ | tr '\0' '\n' | grep LC_ALL"
bash-4.2$ pgrep -f ".*nomad executor.*" | xargs -L1 -I{} bash -c "cat /proc/{}/environ | tr '\0' '\n' | grep LC_ALL"
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
LC_ALL=C
bash-4.2$
```

**Comment by nugend** [comment]
I'm going to try using the blacklist now though. I'm definitely *not* setting that anywhere though.

**Comment by nugend** [comment]
Setting the blacklist does prevent the environment variable from propagating to the executor's subprocess, but the variable remains set on the executor itself.

**Comment by nugend** [comment]
@schmichael identified that this is being caused by https://github.com/hashicorp/nomad/blob/b90980bd7d8bd9478ae5595873cee71936d113a8/vendor/github.com/shirou/gopsutil/internal/common/common_linux.go#L12

I'll file a report upstream.

**Comment by dadgar** [comment]
@nugend If it prevents it from propagating to the actual task, isn't that enough?

**Comment by nugend** [comment]
Well, sure. It's fine as a workaround as long as upstream gets it fixed. If they come back with a can't/won't, then I guess you should add it to the default blacklist (and you never have a problem with something assuming a Unicode locale).

**Comment by nugend** [comment]
@schmichael Change was accepted upstream

**Comment by dadgar** [comment]
Thanks for the report and helping out @nugend 👍
