### ISSUE TITLE
Nomad log spam from Consul

### ISSUE THREAD

**Issue by gehzumteufel** [hashicorp/nomad#3040]
### Nomad version
Nomad v0.6.0 (but we had this same problem on the 0.5.x series)

### Operating system and Environment details
Centos 7.3

### Issue
Consul is hitting an endpoint that seems to always result in an `invalid method` error that spams the logs

### Reproduction steps
1. Install nomad server and client and consul
2. Watch the nomad log fill with the below log error.

### Nomad Server logs (if appropriate)
`[ERR] http: Request /v1/agent/servers, error: Invalid method`

### Nomad Client logs (if appropriate)
n/a

### Job file (if appropriate)
n/a

We're on 0.9.0 for Consul but we were on 0.7.2 before and was seeing this then too.

**Comment by dadgar** [comment]
How are you running Nomad? Is it running both the server and client on the same machine? Could you show your Nomad agent config?

**Comment by gehzumteufel** [comment]
We aren't running server and client on the same machine. We use the Puppet module at https://forge.puppet.com/dudemcbacon/nomad to sort the installation but it pulls the HashiCorp precompiled binary release.

Here's the config.json for the server:

```json
{
  "advertise": {
    "http": "10.0.0.4:4646",
    "rpc": "10.0.0.4:4647",
    "serf": "10.0.0.4:4648"
  },
  "bind_addr": "0.0.0.0",
  "consul": {
    "address": "127.0.0.1:8500"
  },
  "data_dir": "/var/lib/nomad",
  "datacenter": "datacenter_name",
  "log_level": "INFO",
  "region": "region_name",
  "server": {
    "bootstrap_expect": 1,
    "enabled": true
  },
  "telemetry": {
    "statsite_address": "metrics_address"
  },
  "tls": {
    "ca_file": "/etc/nomad/nomad.ca.crt",
    "cert_file": "/etc/nomad/nomad.crt",
    "http": true,
    "key_file": "/etc/nomad/nomad.key",
    "rpc": true
  }
}
```

And the agent:

```json
{
  "advertise": {
    "http": "10.0.0.5:4646",
    "rpc": "10.0.0.5:4647"
  },
  "bind_addr": "0.0.0.0",
  "client": {
    "enabled": true,
    "options": {
      "docker.cleanup.image": false
    },
    "reserved": {
      "cpu": 2000,
      "memory": 768
    },
    "servers": [
      "10.0.0.4:4647"
    ]
  },
  "consul": {
    "address": "10.0.0.4:8500"
  },
  "data_dir": "/data/nomad",
  "datacenter": "datacenter_name",
  "log_level": "INFO",
  "region": "region_name",
  "tls": {
    "ca_file": "/etc/nomad/nomad.ca.crt",
    "cert_file": "/etc/nomad/nomad.crt",
    "http": true,
    "key_file": "/etc/nomad/nomad.key",
    "rpc": true,
    "verify_server_hostname": false
  }
}
```

The only thing I've done to these configs is ran them through `jq` to make them easier to read and replaced our company specific info around addresses, regions, and datacenter names.

**Comment by dadgar** [comment]
Can you output `curl localhost:8500/v1/agent/checks | jq .`

**Comment by dadgar** [comment]
You should also be running a Consul agent on the same node as the clients.

**Comment by gehzumteufel** [comment]
```json
curl -s localhost:8500/v1/agent/checks | jq .
{
  "023f2012cba08c71edbef36814ad5f4722621b17": {
    "Node": "server_node",
    "CheckID": "023f2012cba08c71edbef36814ad5f4722621b17",
    "Name": "Nomad Client HTTP Check",
    "Status": "critical",
    "Notes": "",
    "Output": "HTTP GET https://0.0.0.0:4646/v1/agent/servers: 501 Not Implemented Output: Invalid method",
    "ServiceID": "_nomad-client-nomad-client-http",
    "ServiceName": "nomad-client",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  },
  "1cd33e4eeebcb8286d83a93fdc2d4b071a572183": {
    "Node": "server_node",
    "CheckID": "1cd33e4eeebcb8286d83a93fdc2d4b071a572183",
    "Name": "Nomad Server Serf Check",
    "Status": "passing",
    "Notes": "",
    "Output": "TCP connect 0.0.0.0:4648: Success",
    "ServiceID": "_nomad-server-nomad-serf",
    "ServiceName": "nomad",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  },
  "2ec4946c94a5127113067f4cde72dab778ef383a": {
    "Node": "server_node",
    "CheckID": "2ec4946c94a5127113067f4cde72dab778ef383a",
    "Name": "Nomad Server RPC Check",
    "Status": "passing",
    "Notes": "",
    "Output": "TCP connect 0.0.0.0:4647: Success",
    "ServiceID": "_nomad-server-nomad-rpc",
    "ServiceName": "nomad",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  },
  "4da04645c0e138a6e66cee6d33d57db520393aa2": {
    "Node": "server_node",
    "CheckID": "4da04645c0e138a6e66cee6d33d57db520393aa2",
    "Name": "Nomad Server HTTP Check",
    "Status": "passing",
    "Notes": "",
    "Output": "HTTP GET https://0.0.0.0:4646/v1/status/peers: 200 OK Output: [\"10.0.0.4:4647\"]",
    "ServiceID": "_nomad-server-nomad-http",
    "ServiceName": "nomad",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
}
```
I replaced the node with `server_node` since it contains info about our environment.

As for the Consul agent on client nodes, I don't think we were aware of this but it hasn't affected anything negatively for us that we have seen. Will look into adding it though.

**Comment by dadgar** [comment]
Okay I see the issue. So you have two options. One is that you set https://www.nomadproject.io/docs/agent/configuration/consul.html#checks_use_advertise. The other is that you run a Consul agent along side the Nomad agent. The latter is the one I'd recommend. You generally want a Consul agent on all hosts that are using Consul.

Hope that helps!

**Comment by gehzumteufel** [comment]
Great thanks! Appreciate the help.
