### ISSUE TITLE
[question] Nomad logs rotate behaviour

### ISSUE THREAD

**Issue by jesusvazquez** [hashicorp/nomad#3046]
### Nomad version

```
$ nomad version
Nomad v0.5.6
```

### Operating system and Environment details
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

### Issue || Question

We're having an unexpected behaviour in our nomad log files. Our application is logging everything through stdout into its allocation directory.  The config is set by default  this means that according to [nomad logs configuration](https://www.nomadproject.io/docs/job-specification/logs.html) `max_files` is 10 and `max_file_size` is 10mb.

If we check the allocation directory we see the following:
```
$ ls -lih
total 13M
1449634 -rw-r--r-- 1 nomad nomad    0 Aug 16 15:28 auth.stderr.0
1449632 -rw-r--r-- 1 nomad nomad  10M Aug 17 06:02 auth.stdout.0
1441854 -rw-r--r-- 1 nomad nomad 2.4M Aug 17 09:21 auth.stdout.1
```

In this case the application has been running a few hours and the first file has reached 10 MB, therefore nomad is rotating the file and it starts to write in `auth.stdout.1`. Notice that `auth.stdout.1` has a newer date so we can confirm that nomad is writing into that file.

My question is if this is the expected behaviour. What I would expect is that nomad always write to `auth.stdout.0` and when the rotation process comes in it changes the files but maintains the inode pointing to `auth.stdout.0`.

If this is the expected behaviour I would like to know what should I expect when we reach the 10th file set in the `max_files` limit. 
 - Is it going to truncate `auth.stdout.0`and start writing into that file?
 - Is it going to truncate `auth.stdout.9` and will continue writing into that file?
 - Is there anything else I'm missing?

Thank you for your time.

**Comment by schmichael** [comment]
> Is it going to truncate `auth.stdout.0` and start writing into that file?

No. It will remove that file when `max_files` is reached.

> Is it going to truncate auth.stdout.9 and will continue writing into that file?

No. It will remove that file when `max_files` is reached at which point it will be writing to `auth.stdout.19`.

Nomad logging writes to a file until the max size is reached, and then starts writing to a new file. The index only ever increases and old files are removed when `max_files` is reached.

The docs contain some more detail: https://www.nomadproject.io/docs/job-specification/logs.html

**Comment by shantanugadgil** [comment]
@schmichael 
I guess `19` (nineteen) is a typo ?!
Should it be `10` (ten) ?

Regards,
Shantanu

**Comment by schmichael** [comment]
@shantanugadgil No if `max_files=10` then `auth.stdout.9` will not be removed until the current file is `auth.stdout.19`.

**Comment by jesusvazquez** [comment]
Thanks for your quick response.
