### ISSUE TITLE
request for percentage of CPU/RAM/NETWORK

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#3049]
### Nomad version
0.6.0

### Operating system and Environment details
CentOS 7.3+/Ubuntu 16.04

### Issue
Would it be possible to specify the cpu/memory/network limits as a percentage value?
I think this would be helpful if/when I need to relocate services from one machine to another and not have to fiddle with the nomad job files, when possibly upgrading/downgrading the machine.

The use case is very specific, wherein I  huddle specific services on specific machines using `node.class` constraint.
In my case, I use MySQL dockers.

Regards,
Shantanu

**Comment by schmichael** [comment]
Hi @shantanugadgil,

Nomad is going to require absolute values for resources for the foreseeable future. Percentages are very problematic when there are multiple machine types a job may be scheduled on. We try to discourage forcing jobs to certain machines as much as possible as it makes it harder for the scheduler to make optimal use of your cluster resources.
