### ISSUE TITLE
Question: Docker Strategy, Scheduling, asymetric clusters

### ISSUE THREAD

**Issue by vbichov** [hashicorp/nomad#305]
Hello,
Nomad is looking very promising, however it also appears to be at a very early stage.
A few questions about the road map:
* Will there be other strategies aside from "pack"? such as spread?
* Will global scheduling be supported?
* Will it be possible to run tasks that require "orchestration" that is, the transfer of data from one node to the other? such as an IP address of a leader etc.

Thank you.

**Comment by dadgar** [comment]
Hey! I will try to answer these questions. Also feel free to post in the nomad-tool google group.

1. Nomad applies an anti-affinity to placing task groups on the same machine. So it naturally tries to spread load across the cluster.
2. PR #287 adds support for global scheduling. A full-up PR will be coming soon that invokes an evaluation on node joins to complete the global scheduling picture.
3. Yes there will be. We will be adding support for Consul by 0.2. This will allow you to do the service discovery you are describing.

Let me know if you still have questions!

**Comment by chuyskywalker** [comment]
Sorry to dredge up old threads, but seemed most appropriate after searching...

> Nomad applies an anti-affinity to placing task groups on the same machine. So it naturally tries to spread load across the cluster.

@dadgar - is that still true today? I'm finding that, in my 3 node cluster, nearly all my containers are scheduled in just two of the nodes. The third rarely, if ever, gets jobs. It does get my `system"`jobs, but rarely the `service` type.

**Comment by dadgar** [comment]
Jobs themselves do not get that spread behavior. This is only for task groups in the same job. We actually try to bin-pack nodes which is why you see the behavior you are
