### ISSUE TITLE
[question] allow limiting number of tasks per node

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#3050]
### Nomad version
0.6.0

### Operating system and Environment details
CentOS 7.3+/Ubuntu 16.04

### Issue
Would it be possible to limit the number of tasks (docker/raw_exec) per Nomad agent (client) node?
I imagine this could be a `client` setting per driver type ?!

Regards,
Shantanu Gadgil

**Comment by shantanugadgil** [comment]
Hi, I just realized that this has already been requested in #2756 (pt. 3).
This can be closed, I think. (unless this is required for tracking this specific change).

Thank and Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil I will keep it open here since that one is a bit buried. I am curious as to your use case however? Why do you need to limit the number of allocations on a client?

**Comment by shantanugadgil** [comment]
In our test environment we have a need of MySQL (simulating AWS RDS)
My plan was to group the MySQL dockers on machine of a `node.class` named `storage`.
Only the `storage` machines have access to the NAS storage where the actual MySQL data is stored.

In such a scenario, I would like to control how many containers/tasks start on a single machine.

It is actually related to #3049, where I hope to get an even spread among the tasks running on a single machine.
(This is because after N numbers of task, MYSQL system performance degrades as per our usage of the MYSQL DB)

As percentages cannot be specified, I thought of count as a limiting parameter.

As a side effect, I thought it could benefit other task types as well.

Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil Then I am curious why can you not just reserve some space on the storage node such that so many containers can not fit?

**Comment by shantanugadgil** [comment]
@dadgar space? There is no problem with respect to disk space on the storage.
Based on _our_ MySQL usage pattern, if we start having too many MySQL tasks (docker containers) on a single machine, the performance degrades, due to CPU usage.

That is as far as my use case is concerned.

What I wonder is, if a generic "limit" feature like this could _possibly_ be useful for `exec`/`raw_exec` types of workloads ?!?

**Comment by dadgar** [comment]
I am suggesting reserving CPU so that the servers do not degrade to that point: https://www.nomadproject.io/docs/agent/configuration/client.html#reserved-resources.

For now I am actually going to close this issue. I do not want many ways to do something and it seems odd to artificially cap the number of tasks when it isn't based on actual resource demand on the node. If I put 3 hello world apps vs 3 production apps, that is very different but not captured by a plain limit.
