### ISSUE TITLE
auto_revert tries to revert to non-existant versions after job purge

### ISSUE THREAD

**Issue by clinta** [hashicorp/nomad#3052]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
v0.6.0

### Operating system and Environment details
Ubuntu 16.04

### Issue

Create a job with `auto_revert` set to true. Run several different deployments with this job. In my case the latest successful deployment was job version 195. Then delete this job with `nomad stop -purge`. Run this job again with a successful deployment, which is deployment 0. Push a deployment that will fail which will be deployment 1. When the deployment fails `nomad deployment list` will show `Failed due to unhealthy allocations - rolling back to job version 195`. Nomad should try to roll back to version 0, but something is not being reset with `nomad stop -purge`.

**Comment by dadgar** [comment]
@clinta Thanks for reporting! Fun bug! Fix was changing a variable from `job` -> `j`... :(

Should be fixed in 0.6.1
