### ISSUE TITLE
Support `-json` option for cli command `nomad status`

### ISSUE THREAD

**Issue by robwdux** [hashicorp/nomad#3055]
### Nomad version
0.6.0

### Issue
Feature request: support `-json` option for cli `nomad status`

this option is currently supported for other cli commands. It would be useful to monitor latest deployments via `nomad status -json <app> | jq ...`

Even better would be future support of a yet to be developed slack plugin for reporting failed deployments.

https://github.com/hashicorp/terraform/issues/15187

**Comment by dadgar** [comment]
Hey the reason `nomad status` doesn't have that is that it is stitching together multiple API calls to form that. 

You can see the latest deployment for a job using:

```
$ nomad job deployments -latest -json example
{
    "CreateIndex": 89,
    "ID": "0c9a4ecf-f8e9-c38e-bdb2-8e833d732665",
    "JobCreateIndex": 87,
    "JobID": "example",
    "JobModifyIndex": 88,
    "JobVersion": 0,
    "ModifyIndex": 103,
    "Status": "successful",
    "StatusDescription": "Deployment completed successfully",
    "TaskGroups": {
        "cache": {
            "AutoRevert": true,
            "DesiredCanaries": 0,
            "DesiredTotal": 3,
            "HealthyAllocs": 3,
            "PlacedAllocs": 3,
            "PlacedCanaries": null,
            "Promoted": false,
            "UnhealthyAllocs": 0
        }
    }
}
```

**Comment by robwdux** [comment]
thank you
