### ISSUE TITLE
job specification with less than the minimum required CPU gives an unhelpful error

### ISSUE THREAD

**Issue by ranjib** [hashicorp/nomad#306]
the failure seems to come from runc cgroups/fs manager code. the client os is running under systemd. Im still browsing through the code, will update the issue if i get any more data 
```
* Failed to join spawn-daemon to the cgroup (config => &{Name:a224b4a3-df28-27b4-1f6a-d44667e9de4f Parent: AllowAllDevices:true AllowedDevices:[] DeniedDevices:[] Memory:0 MemoryReservation:0 MemorySwap:0 KernelMemory:0 CpuShares:1 CpuQuota:0 CpuPeriod:0 CpuRtRuntime:0 CpuRtPeriod:0 CpusetCpus: CpusetMems: BlkioWeight:0 BlkioLeafWeight:0 BlkioWeightDevice:[] BlkioThrottleReadBpsDevice:[] BlkioThrottleWriteBpsDevice:[] BlkioThrottleReadIOPSDevice:[] BlkioThrottleWriteIOPSDevice:[] Freezer: HugetlbLimit:[] Slice: OomKillDisable:false MemorySwappiness:0 NetPrioIfpriomap:[] NetClsClassid:}): The minimum allowed cpu-shares is 2
```

----

This error appears when a job specification is configured with less than 200mhz in CPU shares. We should change this to validate at the run step so the nomad client can report the problem, instead of waiting for the exec to fail.

@cbednarski

**Comment by dadgar** [comment]
Hey the output got cut-off but it appears that the CPU resources may have been set too low? I am getting this from the end of the error message: "The minimum allowed cpu-shares is "

**Comment by dadgar** [comment]
6e01e1c should not return an error message if my suspicion is correct.

**Comment by ranjib** [comment]
@dadgar sorry, updated the error.im checking why the number of cpus is less than 2, it should be 4. may be some bug on gopsutil

**Comment by ranjib** [comment]
@dadgar it was my mistake to specify cpu share 1 MHz on the job config. setting that to 200 fixed it. sorry for the false alarm

**Comment by cbednarski** [comment]
We should probably give a different error message when we validate the task.

**Comment by cbednarski** [comment]
@dadgar Clarified that this is specific to the cgroups implementation, and as such we don't have a good way to validate before submitting the job. We may be able to improve this later on.
