### ISSUE TITLE
Batch job not starting on all nodes

### ISSUE THREAD

**Issue by yellowmegaman** [hashicorp/nomad#3084]
### Nomad version
Nomad v0.5.6 / Nomad v0.6.0

### Operating system and Environment details
debian stable/ubuntu 16

### Issue
Running batch job on 4 node cluster results in batch job being run only on one node

### Reproduction steps
Using example batch from nomad docs https://www.nomadproject.io/docs/job-specification/job.html
start it, get only one allocation

### Job file - one from the docs, replaced `uptime` with `hostname` and changed datacenter to `bbb`
```
job "docs" {
  datacenters = ["bbb"]

  type = "batch"

  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "example" {
    task "hostname" {
      driver = "exec"
      config {
        command = "hostname"
      }

      resources {
        cpu = 20
      }
    }
  }
}
```

#### nomad node-status -verbose
```
$ nomad node-status -verbose
ID                                    DC   Name         Class   Drain  Status
19900745-f070-cc75-69c8-bdd89c08f976  bbb  bbb-bbb-003  <none>  false  ready
58054a9c-1f19-37dd-419d-f04e2cafb2e2  bbb  bbb-bbb-001  <none>  false  ready
91934f9f-2e78-3e19-7502-18f2948b5c0b  bbb  bbb-bbb-002  <none>  false  ready
aa912874-41cc-26c9-b4a6-9e8b789b53d4  bbb  bbb-bbb-004  <none>  false  ready
```
#### nomad server-members -detailed
```
$ nomad server-members -detailed
Name                Address       Port  Tags
bbb-bbb-001.global  172.31.1.133  4648  mvn=1,build=0.6.0,port=4647,expect=4,role=nomad,region=global,dc=bbb,vsn=1
bbb-bbb-002.global  172.31.15.29  4648  port=4647,expect=4,role=nomad,region=global,dc=bbb,vsn=1,mvn=1,build=0.6.0
bbb-bbb-003.global  172.31.5.42   4648  mvn=1,build=0.6.0,port=4647,expect=4,role=nomad,region=global,dc=bbb,vsn=1
bbb-bbb-004.global  172.31.14.64  4648  vsn=1,mvn=1,build=0.6.0,port=4647,expect=4,role=nomad,region=global,dc=bbb
```

#### nomad plan
```
$ nomad plan nomad_docs_batch_example 
+ Job: "docs"
+ Task Group: "example" (1 create)
  + Task: "hostname" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.

Job Modify Index: 0
To submit the job with version verification run:

nomad run -check-index 0 nomad_docs_batch_example

When running the job with the check-index flag, the job will only be run if the
server side version matches the job modify index returned. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
```

#### nomad run
```
$ nomad run nomad_docs_batch_example 
==> Monitoring evaluation "e421edd4"
    Evaluation triggered by job "docs"
    Allocation "c1724b68" created: node "aa912874", group "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "e421edd4" finished with status "complete"
```

#### nomad status
```
$ nomad status docs
ID            = docs
Name          = docs
Submit Date   = 08/23/17 14:06:35 UTC
Type          = batch
Priority      = 50
Datacenters   = bbb
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
example     0       0         0        0       1         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created At
c1724b68  aa912874  example     0        run      complete  08/23/17 14:06:35 UTC
````

#### nomad logs
```
$ nomad logs -job docs
bbb-bbb-004
```

#### nomad alloc-status
```
$ nomad alloc-status c1724b68
ID                  = c1724b68
Eval ID             = e421edd4
Name                = docs.example[0]
Node ID             = aa912874
Job ID              = docs
Job Version         = 0
Client Status       = complete
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created At          = 08/23/17 14:06:35 UTC

Task "hostname" is "dead"
Task Resources
CPU     Memory  Disk     IOPS  Addresses
20 MHz  10 MiB  300 MiB  0     

Task Events:
Started At     = 08/23/17 14:06:42 UTC
Finished At    = 08/23/17 14:06:42 UTC
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                   Type        Description
08/23/17 14:06:42 UTC  Terminated  Exit Code: 0
08/23/17 14:06:42 UTC  Started     Task started by client
08/23/17 14:06:35 UTC  Task Setup  Building Task Directory
08/23/17 14:06:35 UTC  Received    Task received by client
```

As it is said in the docs, batch job should start on all nodes as long as constraints are ok.

If i change type `batch` -> `system`, everything is correct.

```
$ nomad plan nomad_docs_batch_example 
+ Job: "docs"
+ Task Group: "example" (4 create)
  + Task: "hostname" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.
```

Please tell me that i'm wrong somewhere here.

P.S. If i specify `group` that is already used, it correctly places allocation on same node with service from that group, but again, only one.

**Comment by dadgar** [comment]
@yellowmegaman Hey, batch and system jobs do not target all nodes. There is a count parameter on task groups that tells Nomad how many instances you want it to run: https://www.nomadproject.io/docs/job-specification/group.html#count.

Constraints are used to filter eligible nodes. It does not mean that every node that matches the constraint will run the job. Hope that all make sense!

**Comment by yellowmegaman** [comment]
@dadgar Thanks a lot for the info. I think docs should be changed then, because it is said like this:
```
This example job executes the uptime command across all Nomad clients in the fleet, as long as those machines are running Linux.
```
I perfectly understand that nomad is a scheduler, not an automation tool, but if we can run batch jobs, i honestly don't see why i can trigger N jobs with constraints, but not `please run on host a,b, and d`

**Comment by jippi** [comment]
what you can do is count your `clients` from the API, and submit the batch job with `distinct_host` `constraint{}`and then submit the batch job with that client count as the task group count :)

**Comment by yellowmegaman** [comment]
@jippi that's what i'm doing now) but probably will move this logic to app containers any way.

If i'm in situation when i need to (for example) perform special backup, and want to run script on all hosts where specific application is deployed, it\s much easier to trust nomad to find those nodes, then finding them via anything else outside cluster. Or really put all logic in the app.

**Comment by dadgar** [comment]
@yellowmegaman That is confusing. I will update the docs! Thanks for pointing that out!

**Comment by yellowmegaman** [comment]
@dadgar thank you for quick response!
