### ISSUE TITLE
[question] Setting default logging driver for all containers

### ISSUE THREAD

**Issue by Cryson** [hashicorp/nomad#3088]
### Nomad version
Nomad v0.6.0

### Operating system and Environment details
CentOS 7.3

### Issue
I cannot find where to set the default logging driver for all containers that are spun up. I do see in the task stanza that I can set such settings. But I don't want to do that for 50+ container .nomad files, it'd be nice if I could set a "default" somewhere so when containers are spun up instead of syslog(which is default), they would use splunk with all of my preconfigured information. However I do not see that exist?

I did see some post stating to add a /etc/docker/daemon.json for dockerd, however, from what I have seen nomad executes containers with docker-containerd, not dockerd. So that daemon.json is pointless.

**Comment by dadgar** [comment]
Hey @Cryson at the time there is no way to do this. I recommend using a templating tool to help with that for the time being.
