### ISSUE TITLE
raw_exec driver: task failed with: wait: no child processes 

### ISSUE THREAD

**Issue by feliksik** [hashicorp/nomad#309]
I am running commands with the raw_exec driver (great that this is there, by the way). 

Inspecting the allocation result with 'nomad alloc-status <id>', sometimes gives me: 
ClientDescription = {"vm":{"Status":"dead","Description":"task failed with: task exited with error"}}

This is ok, in this case, as the bash script I run fails. But sometimes the alloc-status gives: 
ClientDescription = {"vm":{"Status":"dead","Description":"task failed with: wait: no child processes"}}

I speculate: might this be a race condition, where the OS still spawning the child process, but the `func (h *rawExecHandle) run()` in raw_exec.go is already calling h.proc.Wait() before the process is actually properly registered as child? 

I am running https://github.com/hashicorp/nomad/tree/60eda624ec85e64490723ceab4c2c1c81ab85c95 , Linux 4.2.0-16-generic #19-Ubuntu SMP

**Comment by dadgar** [comment]
Should be fixed by executor updates and driver refactors.
