### ISSUE TITLE
Hyphens no longer allowed in job names when using the CLI

### ISSUE THREAD

**Issue by dsolsona** [hashicorp/nomad#3118]
### Nomad version
Nomad v0.6.2

### Operating system and Environment details
Linux 4.9.0-0.bpo.2-amd64 

### Issue

I just upgraded one of our Nomad clusters and I'm seeing issues with jobs that contain a hyphen, for example

```
~# nomad status channel-service
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Input (without hyphens) must be even length)"
```

This same command works in Nomad 0.6.0

**Comment by pkrolikowski** [comment]
@dsolsona use `nomad job status channel-service` instead

**Comment by hynek** [comment]
It seems like `nomad status` is now more general purpose (will guess the type of the status you're interested in) but is a bit too trigger-happy in thinking something is an UUID (I guess just looks for hyphens? :)).
