### ISSUE TITLE
Nomad 0.6.2 binary without .exe extension

### ISSUE THREAD

**Issue by mbp** [hashicorp/nomad#3123]
When downloading Nomad from https://releases.hashicorp.com/nomad/0.6.2/nomad_0.6.2_windows_amd64.zip

The zip contains a file `nomad` with no `.exe` extension. Renaming it works fine.

The 0.6.0 zip file contained `nomad.exe`.

**Comment by dadgar** [comment]
Long term fix: https://github.com/hashicorp/nomad/pull/3124

**Comment by ninoles** [comment]
Just want to know:
- First, the releases binary in the windows_amd64 0.6.2 archive seems to be a x32 executable.
- Second, the binary in 0.6.1 and 0.6.2 on windows seems to deadlock somewhere.  I cannot even make it print its version.  0.6.0 works fine.

**Comment by dadgar** [comment]
0.6.2 is re-uploaded. I would suggest running 0.6.3 as it fixes some CLI bugs.

@ninoles I just ran on Windows 2016 Server and it brought up the agent correctly and version/etc worked.
