### ISSUE TITLE
nomad status <LONG_JOBID> hits go-memdb's limitation UUID have 36 characters

### ISSUE THREAD

**Issue by nak3** [hashicorp/nomad#3134]
### Nomad version
Output from `nomad version`

~~~
$ nomad version
Nomad v0.6.3-dev
~~~

commit: aa9bb3316fbe13201eac9a03f943612b2d6f00ca

### Operating system and Environment details

- OS: Linux (Fedora 26)

### Issue

- When job ID has more than 36 characters, it hits [go-memdb's limitation](https://github.com/hashicorp/go-memdb/blob/e889dc5b880d6619aa3ccc653d802ae172c0904c/index.go#L395)

#### 1. create job with ${LONG_JOBID} > 36.

(eg.)
~~~
$ nomad status
ID                                                                      Type     Priority  Status   Submit Date
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  service  50        pending  08/30/17 19:14:47 JST
~~~

#### 2. run nomad status ${LONG_JOBID} and gets following error

~~~
$ nomad status aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Invalid UUID length. UUID have 36 characters; got 70)"
~~~

### Additional info

- After `nomad status` started using `/v1/search` endpoint, this issue was included. Previously `nomad status` used `/v1/jobs/prefix` with GET(`client.query`), and it was no problem. So, `nomad job status <LONG_JOB_ID>` could be a workaround for this issue.

- More than 36 characters sounds crazy, but spark job automatically often assign such long job ID.

~~~
$ spark-submit   --class org.apache.spark.examples.JavaSparkPi   --master nomad   --deploy-mode cluster   --conf spark.executor.instances=4   --conf spark.nomad.sparkDistribution=https://s3.amazonaws.com/nomad-spark/spark-2.1.0-bin-nomad.tgz   https://s3.amazonaws.com/nomad-spark/spark-examples_2.11-2.1.0-SNAPSHOT.jar 100

$ nomad status
ID                                                              Type     Priority  Status   Submit Date
org.apache.spark.examples.JavaSparkPi-2017-08-30T07:51:04.567Z  batch    40        pending  08/30/17 16:51:05 JST

$ nomad status org.apache.spark.examples.JavaSparkPi-2017-08-30T07:51:04.567Z
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Invalid UUID length. UUID have 36 characters; got 58)"
~~~

**Comment by dadgar** [comment]
Hey in the meantime please use `nomad job status`. This will be fixed in 0.6.3. Thanks for the report!
