### ISSUE TITLE
[schedule] How to check cluster resource used?

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#3143]
How to check cluster resource used?
example:

resource    nodes memory memory-used disk disk-used
cpu             10       1000G    200G(20%)     1P   1P(100%)

**Comment by skyrocknroll** [comment]
You can get lot of metrics including cluster utilization if you configure telemetry https://www.nomadproject.io/docs/agent/telemetry.html

**Comment by dadgar** [comment]
Hey @linuxgood1230,

You can manually aggregate using the existing APIs by query each node and its allocations and summing up to determine the free space. There is no API at the moment to do this for you. It has been requested here: https://github.com/hashicorp/nomad/issues/1175 so I will be closing this as it is a duplicate.
