### ISSUE TITLE
job status on cli doesn't work

### ISSUE THREAD

**Issue by MorphBonehunter** [hashicorp/nomad#3144]
### Nomad version
Output from `nomad version`
`Nomad v0.6.2`

### Operating system and Environment details
Using precompiled binary on Arch Linux

### Issue
Can not show job status on cli.

### Reproduction steps
I can get the overall status:
```
nomad status
ID                              Type            Priority  Status   Submit Date
pricetrend                      batch/periodic  50        running  08/31/17 08:27:16 CEST
pricetrend/periodic-1504161000  batch           50        dead     08/31/17 08:30:00 CEST
pricetrend/periodic-1504161900  batch           50        dead     08/31/17 08:45:00 CEST
pricetrend/periodic-1504162800  batch           50        dead     08/31/17 09:00:00 CEST
```
But if i want to show the "master" job:
```
nomad status pricetrend
Multiple matches found for id "pricetrend"
```
If i want to show the status of the periodic job:
```
nomad status pricetrend/periodic-1504161000
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Input (without hyphens) must be even length)"
```
Also the status of the periodic jobs are all "dead", but the completed successfully except the second one (i've used hashi-ui to look at this). Is this the desired state? I thought the successfull jobs should be "completed" or something and only the failed should "dead"?

BTW: The docs seems to be not up to date in the topic "Inspecting State" as they say:
```
Evaluation Status:
If we issue the status command with the -evals flag, we could see there is an outstanding evaluation for this hypothetical job.
```
But the `nomad status` hasn't sich an switch:
```
nomad status -evals pricetrend
...
Error parsing arguments: "flag provided but not defined: -evals"
```

### Nomad Server logs (if appropriate)
```
Aug 31 09:08:28 pandora nomad[621]:     2017/08/31 09:08:28.167979 [ERR] http: Request /v1/search, error: alloc lookup failed: index error: Input (without hyphens) must be even length
```

### Job file (if appropriate)
```
job "pricetrend" {
  datacenters = ["hive"]
  type = "batch"
  periodic {
    cron             = "*/15 * * * * *"
    prohibit_overlap = true
    time_zone        = "Europe/Berlin"
  }
  group "pricetrend" {
    count = 1
    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }
    task "instant-gaming" {
      driver = "raw_exec"
      config {
        command = "/home/daniel/repos/underverse/tools/ig_pricetrend/ig_pricetrend.py"
      }
      resources {
        network {
          mbits = 10
        }
      }
    }
  }
}
```

**Comment by pznamensky** [comment]
Already fixed: https://github.com/hashicorp/nomad/issues/3117

**Comment by MorphBonehunter** [comment]
@pznamensky thanks for pointing me to that (i realy have to check closed issues not only the open ones).
So maybe you can help with my other question why the job state is marked dead (or point me to the docs where the states are explained as i couldn't find it) but runs successfully:
```
ID            = pricetrend/periodic-1504164600
Name          = pricetrend/periodic-1504164600
Submit Date   = 08/31/17 09:30:00 CEST
Type          = batch
Priority      = 50
Datacenters   = hive
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
pricetrend  0       0         0        0       1         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created At
1730fdeb  395a1d99  pricetrend  0        run      complete  08/31/17 09:30:00 CEST
```

**Comment by dadgar** [comment]
Hey @MorphBonehunter,

"dead" is just the terminal state of the job, it transitions from pending to running to dead. Your allocation is marked as complete which means it ran successfully!

Going to close as this is a duplicate!

**Comment by MorphBonehunter** [comment]
@dadgar thanks for your explantation.
