### ISSUE TITLE
Track available disk space in Nomad clients

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3151]
Nomad currently has a static storage fingerprinter which runs only once the client starts up. Over time if disk resources are leaked or get acquired by system services the scheduler isn't aware. This results in placing allocations on nodes where disk isn't available causing allocations to crash.

**Comment by tgross** [comment]
Nomad used to schedule disk resources but not enforce it. This scheduling was later removed (except for `ephermeral_disk`). This issue can be closed.
