### ISSUE TITLE
Cannot change job type from system to service

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#3152]
### Nomad version
0.6.2

### Operating system and Environment details
debian for servers and clients
archlinux for cli

### Issue
When modifying a job, and changing the type from "system" to "service",  I get the following error:

```
Error submitting job: Unexpected response code: 500 (3 error(s) occurred:

* RPC failed to server 10.1.200.16:4647: rpc error: cannot update job from type "system" to "service"
* RPC failed to server 10.1.200.13:4647: rpc error: rpc error: cannot update job from type "system" to "service"
* RPC failed to server 10.1.99.123:4647: rpc error: rpc error: cannot update job from type "system" to "service")
```

This is true even when the job is in the `stopped` state.  
Forcing a garbage collection with:
```
curl -X PUT $NOMAD_ADDR/v1/system/gc
```

allows a new version of the job to be inserted.

**Comment by dadgar** [comment]
@dansteen This is not a bug. It is by design. Different schedulers handle the system and service/batch schedulers so you are not allowed to change the job type as that could lead to undesired behavior. 

Just stop the job with a purge before changing the type. `nomad stop -purge <job>`
