### ISSUE TITLE
nomad symlink handling

### ISSUE THREAD

**Issue by michaelw** [hashicorp/nomad#3154]
### Nomad version
Nomad v0.6.0

### Operating system and Environment details
MacOS 10.12.5 (16F73)

### Issue
On the following directory tree:
```
tick
├── boom
│   └── example.nomad
└── tock
    └── boom -> ../../tick/boom
```
I am getting this error running `nomad plan example.nomad` (in `tick/tock/boom`):

```
Error getting job struct: Error getting jobfile from "example.nomad": source path error: stat /tmp/tick/tick/boom/example.nomad: no such file or directory
```

### Reproduction steps
```sh
mkdir -p tick/{tock,boom}
ln -s ../../tick/boom tick/tock
cd tick/tock/boom
nomad init
nomad plan example.nomad
```

**Comment by dadgar** [comment]
Bug is actually in go-getter: https://github.com/hashicorp/go-getter/blob/master/detect_file.go#L35

Will work to get the fix upstreamed.
