### ISSUE TITLE
Add task driver for .NET Core applications

### ISSUE THREAD

**Issue by ArmedGuy** [hashicorp/nomad#3161]
Hi, I am not sure if this is the correct forum to introduce such an idea, but posting here nevertheless.

~~We have a few Citrix XenServer clusters @ Luleå Academic Computer Society at the Luleå University of Technology in Sweden, and we wish to get started with Nomad and utilize resources in these clusters for tasks.~~

~~I have looked around and there doesn't seem to be any support for Citrix XenServer (or any plans for support?).~~

We are a group of students and engineers that have decided to take upon us the task of implementing a first version for a task driver for .NET Core applications, as part of a course in Software Engineering at the university.
I figured I would open an issue so that you people are aware, and might point us in the right direction if we have questions etc.

Regards,
Johan Jatko
Student/Engineer @ Luleå Academic Computer Society

**Comment by ArmedGuy** [comment]
After getting a hang of the project structure we are starting to wonder if this goal is achievable?
The nomad client would run on XenServer's dom0 VM, and would therefore report both dom0:s CPUs and RAM available. (Which is far less than what a node has).
It seems to be possible to override CPU and network reporting, but not RAM.
I would presume that the correct way to utilize cluster resources is to spin up virtual machines that fill up the compute nodes, and run nomad on those instead.

As we are still in need for a project for our course, we are pivoting our idea to implement a task driver for dotnet core, which will be similar to the Java driver.
Editing first post to reflect this.

**Comment by shantanugadgil** [comment]
hi @ArmedGuy 
in case you are exploring a new driver for Nomad, may I suggest LXD?
https://linuxcontainers.org/
https://linuxcontainers.org/lxd/news/

Nomad doesn't have first class support for LXD (yet, I hope)
ref: https://github.com/hashicorp/nomad/issues/2196

Now that LXD 2.17 has differential image download, it is quite "competitive" with Docker for people arguing about download sizes.

For now, there is a **Terraform** plugin though, which folks use actively.
Terraform plugin for LXD: https://github.com/sl1pm4t/terraform-provider-lxd

**Packer** recently added support (very basic) to build LXD images:
https://www.packer.io/docs/builders/lxd.html

For now I am using the Terraform plugin and Terraform's `null_resource` with ssh connections to do pre/post install actions.

Having first-class support for LXD with Nomad would be a great addition to Nomad's capabilities
(considering there is no "orchestration" software for LXD yet)

There is one similar to Docker Compose: (weird coincidence with the name, I think)
http://lxd-nomad.readthedocs.io/en/latest/

If you get an LXD driver working, I can definitely help to test this on my LXD based setups for test/qa.

Thanks and Regards,
Shantanu

**Comment by dadgar** [comment]
Hey just want to let you know that Nomad will be working towards drivers as plugins and as such we will not be upstreaming any new drivers for the time being. All for the effort but want it to be known that for the mean time this will have to live as a fork.

**Comment by dadgar** [comment]
@ArmedGuy I am actually going to close this since it won't be going into Nomad. Please feel free to post questions here though and we'd love to help out and make Nomad work for you!

**Comment by ArmedGuy** [comment]
Okay, that is understandable. Has there been any thought into the design of such a plugin system, and anywhere where one can read about discussions regarding it?

**Comment by shoryavj** [comment]
Is there any update on task drivers for .NET core applications?

**Comment by rkttu** [comment]
@dadgar I came across this thread while investigating the material to use Nomad in a Windows container deployment. .NET Core (.NET 5) basically runs as a separate virtual machine just like Java. I have the same curiosity as @ArmedGuy.

And besides .NET, As far as I know there are a number of technologies based on this model. (E.g. runtimes in languages such as Python, Ruby, etc.)

I understood that all runtimes other than Java are advised to use the Docker driver. However, I am also curious about the design reason why a separate driver is provided for Java.

**Comment by tgross** [comment]
@rkttu this issue was closed in 2017, it's really better to open a new issue if you have new questions. Or better yet, start a conversation on [Discuss](https://discuss.hashicorp.com/c/nomad/28)
