### ISSUE TITLE
Nomad docker driver requires drive share on windows.

### ISSUE THREAD

**Issue by krjensen** [hashicorp/nomad#3176]
Hi,

If i use the default nginx docker container in native docer "docker run nginx" everything works, but if i schedule the same container in nomod, it fails because it requires "drive share". Im not able to enable drive share in docker on my windows machine, and things should work without.

job
```
job "nginx" {
  datacenters = ["dc1"]
  group "nginx" {
    task "nginx" {
      driver = "docker"
      config {
        image = "nginx"
      }
    }
  }
}
```

OS: Windows 10
nomad: v0.6.2
dcoker: version 17.06.2-ce, build cec0b72

**Comment by dadgar** [comment]
@krjensen Can you run the docker container doing a volume mount or would that require drive sharing as well? Nomad automatically volume mounts certain directories, so if that is the case, drive share capability will be a requirement to using Nomad and Docker on Windows.

**Comment by krjensen** [comment]
So after I created this ticket I actually got drive share to work but now I'm stock on another issue, where path is wrong when you run a Linux container on windows. This issue is already reported but not solved. I think we can close this one and say that Drive Share is a requirement for nomad. Agree?

**Comment by dadgar** [comment]
Agree. @krjensen Would love a PR adding documentation to the docker driver page! I am going to close this one out! Thank you!
