### ISSUE TITLE
Nomad cli client has no easy to use library (bindings for server REST API)

### ISSUE THREAD

**Issue by feliksik** [hashicorp/nomad#318]
In trying to programatically (in Go) schedule jobs at the nomad server, I am creating a Job struct and trying to schedule it. This means I am basically trying to reimplement large parts of the `Run(args []string) int ` method in https://github.com/hashicorp/nomad/blob/master/command/run.go . 

However, this is not so easy to me. I have to validate the job, convert the Job to an ApiJob with `apiJob, err := convertJob(job)`, create a Config, create a Client, and then run the job with `client.Jobs().Register(apiJob, nil)`. That is still fine... but when I want to monitor the job, I have to implement a cli.Ui , and then... discover that all monitor functionality in the `command` package is private. 

Of course I can do API calls directly, but as Nomad itself is implemented in Go, we would be duplicating a lot of functionality. So, appreciating this is an early state project, my questions are: 
* do you intend to provide user-friendly library functionality to schedule jobs? 
* would it make sense to offer this for the monitoring as well?

**Comment by dadgar** [comment]
Maybe I am misunderstanding but couldn't you use the HTTP API? https://www.nomadproject.io/docs/http/job.html

**Comment by feliksik** [comment]
Sure that's possible, but I think often language specific libraries are built on top of that API, right? Allowing people to use a thin library instead of doing the HTTP calls. Does that make sense? 

I will happily use the REST api,  if that is your advice. I just think I will eventually be implementing the bespoke library,  so want to check your opinion!

**Comment by dadgar** [comment]
Ah okay! Thanks for clarifying!

The community is more than welcome to maintain language specific wrapper libraries for interfacing with the Nomad HTTP API but for the foreseeable future we will not be maintaining one.

I am going to go ahead and close this bug. If there are any more concerns let me know!

**Comment by feliksik** [comment]
Perfect,  thanks @dadgar!
