### ISSUE TITLE
Allow service checks to check against the same ip:port as service registers

### ISSUE THREAD

**Issue by ArmedGuy** [hashicorp/nomad#3180]
### Nomad version
0.6.2

### Operating system and Environment details
Debian servers with Docker driver, and a separate network for container traffic.
Running Consul for service discovery.

### Issue
When a service registers with address_mode = "driver", I would expect the checks to check against this internal ip:port. Instead it registers the service with internal IP but runs checks towards host ip:port?

I am aware that the documentation also states this, but I am wondering why?
The sensible thing would be to run the check towards the ip:port the service registers as, to allow for other network configurations.
Are there any design decisions for this, or simply a feature not yet implemented?

Regards, Johan

**Comment by dadgar** [comment]
Hey @ArmedGuy,

The feature is largely for people running software defined networks where the IP to be advertised is with the SDN's subdomain and is not routable outside of that. However the Consul agent can't run checks within that domain, so you run against the host ip port which is mapped into the container. So this feature is actually working as desired and documented! Hope all that made sense!
