### ISSUE TITLE
syslog forwarding stopped working with Nomad v0.6.3-rc1

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#3182]
Upgrading the client agent to version `Nomad v0.6.3-rc1` makes syslog forwarding to a central server stop working.
It works fine with `Nomad v0.6.2`

### Nomad version
Server: Nomad v0.6.3-rc1

Agent:
Nomad v0.6.3-rc1
Nomad v0.6.2

### Operating system and Environment details
CentOS 7 (with latest updates)

### Issue
Upgrading the Nomad agent on the client machine to version `v0.6.3-rc1` makes syslog forwarding to a central server stop working.

### Reproduction steps
update agent to `Nomad v0.6.3-rc1`; stop and start the job.
(you'll see that the logs don't appear on the central server)

replace the agent version with `Nomad v0.6.2`; stop and start the job.
(you'll see that the logs appear on the central server)

### Nomad Server logs (if appropriate)
???

### Nomad Client logs (if appropriate)
???

### Job file (if appropriate)
relevant config section:

```
...
config {
  logging {
    type = "syslog"

    config = {
      syslog-address = "tcp://local-logs.example.com:10514"
      tag            = "my_task_tag"
    }
  }
...
```

Regards,
Shantanu

**Comment by dadgar** [comment]
Seems like the offender: https://github.com/hashicorp/nomad/pull/3135. Needs investigation
