### ISSUE TITLE
Vendor folder contains reference to github.com/Sirupsen/logrus 

### ISSUE THREAD

**Issue by darren-west** [hashicorp/nomad#3183]
### Nomad version
Latest

### Issue
The vendor folder for nomad contains a reference to an old version of docker.This contains a reference to the wrongly formed github.com/Sirupsen/logrus (notice the capital letter).

I know this is not directly a nomad issue but it causes problems with vendoring. They have updated their references in this commit:
https://github.com/moby/moby/commit/1009e6a40b295187e038b67e184e9c0384d95538#diff-a4fc1e1d5b15b8ca02007ccf9f2f6aa8

To see more information on the problem its on the README of https://github.com/Sirupsen/logrus

To quote:
"Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.
"

**Comment by dantoml** [comment]
Nomad now only refers to `github.com/sirupsen/logrus`, rather than `github.com/Sirupsen/logrus`. Thanks!
