### ISSUE TITLE
[question] Why does template need destination in env mode?

### ISSUE THREAD

**Issue by arianvp** [hashicorp/nomad#3189]
In https://www.nomadproject.io/docs/job-specification/template.html#environment-variables

it says if `env = true` the template will be treated as an `EnvironmentFile` for the job. 

Two questions:

1. the `env` stanza now seems redundant, as it has everything that `template` has https://www.nomadproject.io/docs/job-specification/env.html.  Why do we have two? The only reason is, that templates can read from `consul` and `vault` right?

2.  Why does the `template` stanza have a `destination` when `env = true`? This makes no sense to me. We're not using or inspecting the resulting file; We just use the template for environment variables.

**Comment by dadgar** [comment]
Hey,

The fact that there is a file is an implementation detail. We are using consul-template under the hood and parse the resulting file. The template block should only be used when necessary as it is has runtime implications where the env stanza is very light weight and static.
