### ISSUE TITLE
Job specification idea for canary releases, when consul comes in

### ISSUE THREAD

**Issue by sielaq** [hashicorp/nomad#320]
Probably you have think already about canary releases (AKA a/b testing) and consul integration,
but it would be cool, to have possibility
to name service in consul agnostic from nomad name.
So in the end it would be possible to handle with canaries releases like:
```
job "application_stable" {
...
   env {
         CONSUL_SERVICE_NAME = "application"
    }
}
job "application_canary" {
...
   env {
         CONSUL_SERVICE_NAME = "application"
    }
}
```
and if some LB/router ([traefik](https://github.com/EmileVauge/traefik)/[Fabio](https://github.com/eBay/Fabio)) was connected to consul,
you would reach both versions under same service like:
```
# curl application.service.consul/ping
pong from application_stable
# curl application.service.consul/ping
pong from application_canary
```

**Comment by cbednarski** [comment]
@sielaq Thanks for the suggestion. In the past I have used blue-green deploys and achieved this by creating mirrored environments suffixed with `-blue` and `-green` respectively and merging the config back and forth with a script. I think we can fairly easily support what you've described to allow jobs to share a key or other identifier in Consul.

In addition to what you've described, we would (eventually) like to support this by way of rolling deploys with a health checking component. In this case Nomad would validate the health check to decide whether to proceed with the roll out or roll _back_ if there is a problem applying the new version to your infrastructure.

**Comment by dadgar** [comment]
We now have the `service` block which lets you register consul services and we support blue/green blocks by allowing task groups to have counts of 0 so you can fully scale down your canary.
