### ISSUE TITLE
nomad agent -dev should not explicitly bind to localhost

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#3200]
Because `nomad agent -dev` explicitly binds and advertises `localhost`, all services registered with Consul will have their address set to `localhost`. So out of the box service discovery is broken for our `example.nomad` job file as it will advertise `localhost` but only listen on a private IP address.

As of 0.6 Nomad should choose the proper bind and advertise addresses by default, so there's no need for `DevMode` to explicitly restrict them to localhost.

This minimalist config file illustrates how dev mode *should* work:

```hcl

log_level = "DEBUG"
enable_debug = true
datacenter = "dc1"
data_dir = "/tmp/nomad-devagent"

name = "nomad-devagent"

client {
  enabled = true
  servers = ["127.0.0.1:4647"]
  options = {
    "driver.raw_exec.enable" = "1"
  }
}

server {
  enabled          = true
  bootstrap_expect = 1
  num_schedulers   = 1
}
```

**Comment by Matvey-Kuk** [comment]
+1

**Comment by schmichael** [comment]
Came back to this, and I don't remember what the problem is. Tried running `example.nomad` with Nomad 0.6.0 and 0.6.3 and service discovery just worked. Nomad binds to localhost as does the dynamic port assigned to the example redis job. Both Consul health checks and clients using Consul to discover the address of redis are able to find...

> So out of the box service discovery is broken for our example.nomad job file as it will advertise localhost but only listen on a private IP address.

Not sure what I saw that made me think redis will "only listen on a private IP address" but the dynamic port assigned to appears to be properly bound on localhost.

Please reopen if you remember what the issue is! :smile:
