### ISSUE TITLE
[Question] Running System Job in Server Nodes

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/nomad#3208]
We have the scenario where we need to run a process on every node in the cluster (including servers and clients). Do we have a way to achieve this?

**Comment by dadgar** [comment]
You could run the servers with a client on them.

```
datacenter = "server-dc"

server {
  enabled = true
}

client {
   enabled = true
}
```

I would recommend setting them in a unique dc so that your jobs would only be placed on the servers in very specific cases. You should avoid running jobs on the server in all most all production cases.
