### ISSUE TITLE
Windows Docker containers always advertise Docker IP regardless of `address_mode`

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#3218]
### Nomad version
Nomad v0.6.3 

### Operating system and Environment details
Windows Server 2016 

Output from `docker version`
Client:                                                                                                                         
 Version:      17.06.1-ee-2                                                                                                     
 API version:  1.30                                                                                                             
 Go version:   go1.8.3                                                                                                          
 Git commit:   8e43158                                                                                                          
 Built:        Wed Aug 23 21:16:53 2017                                                                                         
 OS/Arch:      windows/amd64                                                                                                    

Server:                                                                                                                         
 Version:      17.06.1-ee-2                                                                                                     
 API version:  1.30 (minimum version 1.24)                                                                                      
 Go version:   go1.8.3                                                                                                          
 Git commit:   8e43158                                                                                                          
 Built:        Wed Aug 23 21:25:53 2017                                                                                         
 OS/Arch:      windows/amd64                                                                                                    
 Experimental: false                                                                                                            

### Issue
When running a Docker container, the Docker IP address is advertised rather than the bound address.  

### Reproduction steps
Run the attached job in a Nomad cluster with a Windows host.

### Job file (if appropriate)
[example.nomad.txt](https://github.com/hashicorp/nomad/files/1304582/example.nomad.txt)

There is also a gist https://gist.github.com/angrycub/12fe330391f2a74d558a410f5531a8c0 with the Dockerfile that I used to make the sample container.

**Comment by angrycub** [comment]
Adding the network_interface attribute to the client stanza of the configuration allowed to the node to properly advertise this host address.   I am still exploring the edges around this solution though.  It was observed that TCP based health checks would fail when configured this way.

**Comment by kyle-crumpton** [comment]
One thing to note with regards to the service stanza (may or may not be related to this ticket) - 

On Windows using the Docker Driver, when we specify the network_interface in the client config, it uses the container's IP to register instead of the host's IP address when registering the service in Consul. Setting address mode to "host" seems to fix this, but I'm not sure this is the desired default behavior for address_mode.

**Comment by dadgar** [comment]
@kyle-crumpton What network_mode are you using when you see this behavior? The driver should use the host IP when the network mode is "host" or "bridge", if something other than that it attempts to use the container IP by default since this is likely the user using a SDN.

**Comment by dadgar** [comment]
@kyle-crumpton What network_mode are you using when you see this behavior? The driver should use the host IP when the network mode is "host" or "bridge", if something other than that it attempts to use the container IP by default since this is likely the user using a SDN.

**Comment by dadgar** [comment]
@angrycub Is this still a bug? I am not clear what the issue is at this point.

**Comment by angrycub** [comment]
@dadgar... I'd like to keep it open, but no longer than this week, while I do some very specific reproduction work with Azure nodes; however, I believe that the current guidance of using `network-interface` is going to stand and we will need to create additional documentation about any potential impacts to Consul health-checks, etc.

**Comment by kyle-crumpton** [comment]
@dadgar I'm not specifically setting network_mode, so it should be defaulting to NAT. I didn't have any luck changing it to host, or bridge. The only thing that made a difference was setting the network_interface in the client configuration to the actual device (in my case Ethernet 5). 

From my perspective the issue may be documentation based. I have tested this in 0.7 beta as well with the same results. Basically if you don't set "network_interface" to the name of the device, nomad creates the container using the container IP, and not the host IP. 
So doing: 
`nomad alloc-status $ALLOC_ID` will actually show the container's IP, which is not resolvable external to host. This doesn't work for us as we are using the Fabio Load Balancer. 
Setting the network_interface in the client configuration to "Ethernet 5" causes the alloc-status to show the proper IP address of the host, making it resolvable by Fabio, but the service check registers using the container's IP in consul's service registration. Setting 
`address_mode = host` fixes this, but according to the documentation on address_mode, it should default to "auto" which should "behave the same as host". So I think one issue is that the default behavior of address_mode is incorrect (for Windows). 
It may be worth noting too, that my team member was able to duplicate the behavior in GCE.

**Comment by schmichael** [comment]
To be clear the expected behavior is:

- `address_mode = "host"` - Nomad advertise IP (`127.0.0.1` for `nomad agent -dev`)
- `address_mode = "driver"` - Docker _bridge_ IP
- No address mode == host

What I see is:

- `address_mode = "host"` - private host IP
- `address_mode = "driver"` - Docker _NAT_ IP
- No address mode - Same as *driver*

So 2 funny things are happening!

The first is simple: On Windows Docker's default network mode is `nat` -- on Linux it's `bridge`. Our autodetection logic sees `nat` as a custom network plugin and defaults to it. That's why no address mode uses the *driver* address instead of the host.

The second is confusing: why does host mode use the private host IP when nomad itself advertises 127.0.0.1?

**Comment by dadgar** [comment]
@schmichael Advertise address is determined separately from `network_interface`. The "host" address is the result of the address determined by fingerprint/network.go
