### ISSUE TITLE
[question] dynamic group count / miss group count

### ISSUE THREAD

**Issue by alxark** [hashicorp/nomad#3243]
Hello. I'm facing following problem: i need to deploy job with several groups by i don't want to change count of group instances and use it from current environment. This happens because i'm using hashi-ui to control number of group instances. Is there any way to skip count from group definition? I think it might be better to add options like count_min and count_max

**Comment by schmichael** [comment]
I'm not sure I understand your question. Where would you like to omit `count`? The scheduler must know how many instances of a group to place, so I'm not sure what you're hoping to accomplish.

**Comment by jippi** [comment]
Think the question is to submit a job to an already running job and omit the task group count.  If it's omitted in a update clause, nomad would take the existing running job task group count and copy those values into the new inbound job before submitting it for scheduler. 

Basically inheriting the existing job task group count instead of using the value from the submitted job

**Comment by schmichael** [comment]
Thanks @jippi! That makes complete sense.

Right now (as of 0.7.0-beta1) you would need to read the job, copy the `count`, and then submit the job (preferably with a `-check-index`).

Obviously that's cumbersome and error prone, so in the future we intend to allow templating job files. The templating language will have a function to use the existing count value for job updates.

Follow #1185 to know when job templating is added!

**Comment by alxark** [comment]
Is there any easy way to read current group count? For example:
```
nomad status <JOBNAME> <GROUPNAME> count
```
 Currently i'm using consul template to generate job files during CI process and i need to store count in consul for different env's

**Comment by schmichael** [comment]
`jq` is my preferred tool for getting values like this from the command line:

```sh
# With the CLI
nomad inspect example | jq .Job.TaskGroups[0].Count

# With a web request (note there's no top-level Job key)
curl -s localhost:4646/v1/job/example | jq .TaskGroups[0].Count
```

**Comment by aclowkey** [comment]
It's kind of odd that we have to do the interpolations.
In Terraform GCP, when you don't specify instance group size, the value is simply ignored, and the existing group size remains and it's not force to be 1 like in Nomad.

I would expect the same behavior in Nomad, omitting the `count` should mean: don't manage the count.
