### ISSUE TITLE
Deployment objects are not garbage collected 

### ISSUE THREAD

**Issue by wuub** [hashicorp/nomad#3244]
### Nomad version
0.6.3

### Issue
As mentioned in #3157, during normal use the number of objects returned by `nomad deployment list` increases without any apparent bound.  

### Reproduction steps
1. Use nomad cluster for a while.
2. 
```bash 
$ nomad deployment list | wc -l            
1224
```
3. Cry.

While I do not see any performance or stability hit as of now, I'm starting to get interested in knowing where we will start to observe some kind of cluster degradation? never? in 5 minutes? 2K/10K/100K/1M/10M deployments?

**Comment by hsmade** [comment]
I have 100K deployments, and pulling on the API causes about 100MB of data...

**Comment by dadgar** [comment]
Can you all share a sample deployment that won’t gc

**Comment by wuub** [comment]
@dadgar are you sure gc for deployments is implemented? Because AFAICT all out ours are just piling up,  and there's nothing special about them, super simple update block 99% with single max_parallel statement.

**Comment by dadgar** [comment]
Yes it is implemented. The deployments won't be garbage collected when there is a running allocation referencing it.

**Comment by wuub** [comment]
That's interesting :). I'll try to see if any of our job specs trigger this on a dev cluster.

Is the GC event driver and triggers immediately after the last allocation is removed, or do I have to wait for periodic clean-up?

**Comment by dadgar** [comment]
You would have to wait for a periodic clean up or you can run `curl -XPUT http://127.0.0.1:4646/v1/system/gc`

**Comment by jippi** [comment]
in hashi-ui thats is also a button under `system` :)

**Comment by wuub** [comment]
Thanks. I'll try to investigate deeper first thing tomorrow morning.

**Comment by wuub** [comment]
Soooo. I sent `curl -XPUT $NOMAD_ADDR/v1/system/gc to our prod cluster, and deployments list shrunk significantly (~1500 -> 159)  (cc: @hsmade) 

BUT. 

Any reason why GC is not running on it's own?

**Comment by dadgar** [comment]
@wuub That is the bug :( the loop creating the GC jobs wasn't doing it for the deployments. Will get a fix soon!

@hsmade Can you run the force and check it clears a bunch of your deployments?

**Comment by wuub** [comment]
Great news :) thank you @dadgar

**Comment by hsmade** [comment]
@dadgar it does, clean out when forcing GC, thx!

**Comment by dadgar** [comment]
@hsmade Sweet! Thanks both of you! Will be fixed in 0.7!

**Comment by hsmade** [comment]
BTW.. A note on the huge data transfer I saw. This was mainly caused by us configuring the reserved ports (20000-32000) because of a misunderstanding of the docs (fixed the docs since then). If you have 64 clients, and each of the produces about 1MB of data for just the port reservations, that adds up :)

**Comment by dadgar** [comment]
@hsmade Yeah that is definitely something we are aware of and would like to make a simple two integers for a range rather than materializing each port!

**Comment by hsmade** [comment]
hehe, yes :)
Luckily, I don't actually need it. So that was a simple(ish) fix. Apart from the rolling restart :P (Which works great, I can just restart my cluster without influencing / stopping my containers. Kudos for that!!)
