### ISSUE TITLE
Vendored gziphandler dependency breaks nomad logs 0.7.0-dev

### ISSUE THREAD

**Issue by heimweh** [hashicorp/nomad#3246]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.7.0-dev

### Operating system and Environment details
Ubuntu 16.04.3 LTS

### Issue
Unable to view/tail logs. Printing out the error from `dec.Decode(&frame)` reveals: Got an error: `invalid character '\x1f' looking for beginning of value` -
 https://github.com/hashicorp/nomad/blob/master/api/fs.go#L277. Checking out the `v0.6.3` version of `gziphandler` in the `v0.7.0` branch fixes the issue, but is probably not the ideal solution, didn't dig further than that. I guess this might also affect other parts of nomad.

### Reproduction steps
1. `git checkout master && git pull`
2. `make pkg/linux_amd64/nomad`
3. `cp pkg/linux_amd64/nomad /usr/local/bin/nomad`
4. `systemctl restart nomad.service`
5. `nomad logs -f <id>` shows up empty.
6. Add error logging to the `dec.Decode` call, the error above will show up.
7. `git checkout v0.6.3 -- vendor/github.com/NYTimes/gziphandler/`
8. `make pkg/linux_amd64/nomad`
9. `cp pkg/linux_amd64/nomad /usr/local/bin/nomad`
10. `systemctl restart nomad.service`
11. `nomad logs -f <id>` works

**Comment by dadgar** [comment]
@heimweh Thanks! It was a bug in the upstream vendor library!

**Comment by heimweh** [comment]
Huge thanks @dadgar for resolving this so quickly! :)
