### ISSUE TITLE
CLI Support for Force Periodic

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#3251]
As mentioned in the PR for the Force Periodic API: https://github.com/hashicorp/nomad/pull/668

**Comment by mlehner616** [comment]
Any timeline for this? I think I can get by with the API endpoint but it would be nice to be able to fire off jobs via the CLI for consistency.

**Comment by alexiri** [comment]
I'd love to have this as well. Is it planned at some point?

**Comment by vlasorokin** [comment]
+1, will appreciate this very much. Any timeline?

**Comment by nickethier** [comment]
Hey folks, no timeline specifically but do leave a :+1: and encourage others who want this to do so as well. We do look at issue reactions when planning out releases. Thanks for your patience!
