### ISSUE TITLE
logs by job ID/allocation ID returns Unexpected response code: 500

### ISSUE THREAD

**Issue by ashmckenzie** [hashicorp/nomad#3254]
### Nomad version
`Nomad v0.7.0-beta1`, also applicable to `Nomad v0.6.3`

### Operating system and Environment details
macOS 10.12.6 (16G29)
Docker Version 17.09.0-ce-rc2-mac29 (19275), Channel: edge, 967c7199b8

### Issue

When attempting to access the logs for an allocation, the following error appears:

`Error reading file: Unexpected response code: 500 (log entry for task "server" and log type "stdout" not found)`

I believe it's related to Docker on Mac because if I change the driver to `raw_exec` I can access logs with no issue.

### Reproduction steps

1. Take Job file below and save as `docs.nomad`
1. `./nomad run docs.nomad`
1. `./nomad status docs` and grab allocation ID
1. `./nomad logs -f <allocation ID>`
1. Should see error

### Nomad Server logs (if appropriate)

```
    2017/09/20 13:36:48.710068 [DEBUG] http: Request /v1/allocations?prefix=3dde7d57 (1.142338ms)
    2017/09/20 13:36:48.712955 [DEBUG] http: Request /v1/allocation/3dde7d57-8e41-ba7e-3bf2-4cc2b1d1d263 (526.535µs)
    2017/09/20 13:36:48.715112 [DEBUG] http: Request /v1/node/a0ecef1a-5b34-da33-e0a9-67a3feea094a (497.161µs)
    2017/09/20 13:36:48.810449 [ERR] http: Request /v1/client/fs/logs/3dde7d57-8e41-ba7e-3bf2-4cc2b1d1d263?follow=true&offset=0&origin=start&region=global&task=server&type=stdout, error: log entry for task "server" and log type "stdout" not found
    2017/09/20 13:36:48.810546 [DEBUG] http: Request /v1/client/fs/logs/3dde7d57-8e41-ba7e-3bf2-4cc2b1d1d263?follow=true&offset=0&origin=start&region=global&task=server&type=stdout (1.014373ms)
    2017/09/20 13:36:49.189425 [DEBUG] http: Request /v1/agent/servers (86.143µs)
```

### Job file (if appropriate)

```
job "docs" {
  datacenters = ["dc1"]

  group "example" {
    task "server" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo"
        args = [
          "-listen", ":5678",
          "-text", "hello world",
        ]
      }

      resources {
        network {
          mbits = 10
          port "http" {
            static = "5678"
          }
        }
      }
    }
  }
}
```

**Comment by ashmckenzie** [comment]
Also, the `alloc/logs` dir is empty:

```
$ ./nomad fs 3dde7d57
Mode        Size   Modified Time          Name
drwxrwxrwx  170 B  09/20/17 13:36:24 CDT  alloc/
drwxrwxrwx  204 B  09/20/17 13:36:25 CDT  server/

$ ./nomad fs 3dde7d57 alloc/
Mode        Size  Modified Time          Name
drwxrwxrwx  68 B  09/20/17 13:36:24 CDT  data/
drwxrwxrwx  68 B  09/20/17 13:36:24 CDT  logs/
drwxrwxrwx  68 B  09/20/17 13:36:24 CDT  tmp/

$ ./nomad fs 3dde7d57 alloc/logs
Mode  Size  Modified Time  Name
```

**Comment by schmichael** [comment]
Unfortunately logs don't work with Docker for Mac: https://www.nomadproject.io/docs/drivers/docker.html#docker-for-mac-caveats

**Comment by ashmckenzie** [comment]
Ah dang, thanks and apologies for not digging further :(  Doesn't look like it's easy either to detect Docker running as Docker for Mac to be able to show a warning, bummer :(
