### ISSUE TITLE
[question] [security] Anyone who can submit Nomad jobs has access to all secrets

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad#3255]
Hi, a question about Nomad/Vault's security model:

Lets say we have vault and nomad integrated, with an AWS backend set up, with some nomad policy (policy 'Y') for AWS that allows, say, s3 access to some bucket, and the nomad-server role has the ability to read from policy Y (i.e. nomad can spawn containers that have been injected with new AWS tokens that allow access to that bucket.)

Now. does this mean that any user 'X' who is able to submit jobs to nomad will have the ability to access that bucket? That is, 'X' can write a new job 'Z', say, consisting of some base alpine container, and specify that this job should inject tokens from policy Y, and then can ssh into that container and make AWS api calls into the bucket.

What I'm looking for is some ability to restrict which users can submit certain jobs. I.e.  user X should have to provide a vault-token that has read access to policy Y *in order to submit job Z*.

Is there some way to accomplish this?

**Comment by dadgar** [comment]
@ryanmickler You simply have to set this: https://www.nomadproject.io/docs/agent/configuration/vault.html#allow_unauthenticated to false.

When you do so, Nomad will only accept the job from the user if they present a Vault token with appropriate permissions.

**Comment by ryanmickler** [comment]
Ahh, brilliant, thanks so much.

I thought there would be a neat solution.
