### ISSUE TITLE
Prevent fully qualified URLs in check paths

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#3273]
### Nomad version

`Nomad v0.6.3`

### Issue

HTTP checks can specify absolute URLs to query remote services. This overwrites the `port` and `proto` parameters.

The docs specify the intended behavior that only relative URLs are accepted. The current behavior is an unintentional side-effect of the underlying Go stdlib function we call: https://golang.org/pkg/net/url/#URL.ResolveReference

### Job file (if appropriate)

```
job "echo" {
  datacenters = ["dc1"]
    task "caddy" {
      driver = "raw_exec"
      config {
        command = "caddy"
        args    = ["-port", "${NOMAD_PORT_db}"]
      }

      resources {
        cpu    = 200
        memory = 256
        network {
          mbits = 10
          port "db" {}
        }
      }

      service {
        name = "caddy"
        port = "db"
        check {
          type = "http"
          path = "https://google.com"
          timeout = "2s"
          interval = "3s"
        }
      }

    }
}
```

**Comment by dbresson** [comment]
This wasn't actually fixed by the PR. It relies on IsAbs, which just checks the scheme.

You can still override the ip/port like so:

`job "echo" {
  datacenters = ["dc1"]
    task "caddy" {
      driver = "raw_exec"
      config {
        command = "caddy"
        args    = ["-port", "${NOMAD_PORT_db}"]
      }

      resources {
        cpu    = 200
        memory = 256
        network {
          mbits = 10
          port "db" {}
        }
      }

      service {
        name = "caddy"
        port = "db"
        check {
          type = "http"
          path = "//google.com/"
          timeout = "2s"
          interval = "3s"
        }
      }

    }
}`
