### ISSUE TITLE
Remove API duplicates of nomad/structs and remove the compose api.

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#329]
The api package has copies of the nomad structs used everywhere else. We should just remove them (example https://github.com/hashicorp/nomad/blob/fd3dccead257b42110e58543e8f39ecafe34e21d/api/jobs.go#L111) and also the compose helpers (https://github.com/hashicorp/nomad/blob/master/api/compose_test.go)

**Comment by Raffo** [comment]
@dadgar Can you explain what needs to be done here? It's not really clear to me.

**Comment by dadgar** [comment]
You will notice that the two packages duplicate all structs returned by the HTTP API. I linked an example. So the task is really to make the API layer return structs defined in nomad/structs 

[nomad/structs package](https://github.com/hashicorp/nomad/blob/fd3dccead257b42110e58543e8f39ecafe34e21d/nomad/structs/structs.go#L733)
[api package](https://github.com/hashicorp/nomad/blob/fd3dccead257b42110e58543e8f39ecafe34e21d/api/jobs.go#L111)

**Comment by Raffo** [comment]
@dadgar Could this be what you want? https://github.com/Raffo/nomad/commit/65aaad3a38269338d5786c4db65abc2e24948525 
If so, I could update my fork with the newer commits from master and submit a PR.

**Comment by dadgar** [comment]
@Raffo: Yes that is exactly what I wanted! I left a few comments on your commit. The command (cli) package would probably have to be updated too!

**Comment by Raffo** [comment]
@dadgar I'll have a look at your comments tomorrow and I'll try to address them. After that, should I update my fork from upstream? I guess there are many new commits and I have no idea if the merge will be painful... tell me what you prefer.

**Comment by dadgar** [comment]
@Raffo: Yeah exactly, I would rebase your branch and then create a PR.

**Comment by dadgar** [comment]
@Raffo: we actually decided to keep the duplicates as a compatibility layer in case the two ever diverge. I really appreciate the effort!

**Comment by Raffo** [comment]
Well, it was fun anyways :-)
