### ISSUE TITLE
There is no consul CLI config option

### ISSUE THREAD

**Issue by flybd5** [hashicorp/nomad#3304]
### Nomad version
All

### Issue
There is a way to config the info to connect to a consul client from an hcl file but not from the command line. I checked in commands.go and nothing.

**Comment by dadgar** [comment]
PRs for this would definitely be welcome. Could look at the Vault flags for guidance.

**Comment by flybd5** [comment]
PR?

**Comment by dadgar** [comment]
Git jargon for "pull request".

**Comment by jrasell** [comment]
@dadgar I can take this one if you want? I assume its everything listed [here](https://www.nomadproject.io/docs/agent/configuration/consul.html) to go as a CLI flag?

**Comment by flybd5** [comment]
I would also suggest a cross-check to make sure all config file options can be done in CLI and vice-versa.

**Comment by dadgar** [comment]
@flybd5 We don't aim to have full parity with the config file. Just the most common options should be available as flags.

**Comment by flybd5** [comment]
I think you should. Some people like to use config files but others prefer to set up things on the command line exclusively. When setting up systemctl definition files I prefer for the config to be self-contained using the CLI.

**Comment by shantanugadgil** [comment]
@flybd5 
I would sort-of disagree, I tend to use only the single "config directory" parameter, so that I can happily tweak the config files within the config directory.

These becomes very easy in a system where some sort of configuration management system like SALT/Ansible/(even Packer) is used to deploy Consul/Nomad.

Cheers,
Shantanu

**Comment by flybd5** [comment]
@shantanugadgil The point is that there is no justification to force the developer to accept one viewpoint over another. It also looks unprofessional to offer one option, but do a half-a** job of the other. The issue of config management is not relevant because you can manage systemctl files just as well as you can manage config files. Config management tools don't care about the content of the files.
