### ISSUE TITLE
[feature-request] Allow batch-system jobs

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad#3337]
I've been looking for a way to perform a once off `exec` task on each nomad client with a certain tag.

This seems to fit under both the 'system' and 'batch' job types.

It is 'System', because i want to use something like
```
        constraint {
            attribute = "${node.class}"
            value     = "worker"
        }
```
to have it run on every 'worker' node. and its also 'batch', because I only want it to run once, and I don't want to provide `count = X`, and not have it continually restarting once the task is complete.

Is there a way to do this?

**Comment by schmichael** [comment]
There isn't a way to do this currently (although you may be able to get `system` jobs to work by carefully adjusting your `restart` stanza settings).

Mind sharing a use case? We get this request from time-to-time, but I believe most people solve it using existing configuration management solutions.

**Comment by ryanmickler** [comment]
My use case is to run a small bash script on the client which pulls a java binary from a local server onto the nomad client, so that it can be referenced locally during the execution of a spark-nomad job. I occasionally want to be able to trigger this process through nomad.

**Comment by schmichael** [comment]
Can you add an `artifact` stanza to your spark-nomad job template? https://www.nomadproject.io/guides/spark/customizing.html#using-a-custom-job-template

**Comment by ryanmickler** [comment]
Ah! this might work. Does the `artifact` stanza do version checking?

**Comment by schmichael** [comment]
Sadly no, artifacts are only downloaded when an allocation is started on the client node.

**Comment by ryanmickler** [comment]
But more generally, I was probably going to be doing a few more things in the script, say, block some services (.e.g the spark executor) while these binaries are updating.. I might even want to update the spark binaries themselves...

**Comment by ryanmickler** [comment]
I was thinking about suggesting that it could be an option to run a batch job with `count = -1` which would indicate to run on all clients that match the constraints.
but this seems to perhaps be a bit confusing.

**Comment by schmichael** [comment]
I just realized there's already an issue tracking this. Feel free to add your use case and/or idea as a comment: https://github.com/hashicorp/nomad/issues/2527

**Comment by ryanmickler** [comment]
Oh great, i had a look and i didn't see it. thanks for your time!

**Comment by analytically** [comment]
Another usecase: downloading large binaries (>400mb, raw_exec) to be used by other tasks.

**Comment by prologic** [comment]
Another use-case we have (_if this feature existed_) would be to distributed via artefacts a docker image to all nomad clients and run a dummy `/bin/true` as the command. The reason we do it this way is we use nomad and artefacts as the source-of-truth for what versions of a package we run in a cluster by inspecting all running jobs and their configured artefacts. Supporting a system-wide batch job would allow us to be consistent in how we distribute, run and keep track of what we're running in any given cluster without having to rely on another tool just to distribute one thing.
