### ISSUE TITLE
Add a user-agent field on http health checks

### ISSUE THREAD

**Issue by dreh23** [hashicorp/nomad#3341]
I am using minio s3 in a nomad/consul cluster. Minio needs a user-agent header for an unauthorized request, otherwise reply will always be 403. I would need to handcraft request - better would be to have a field for a user-agent header.
See https://github.com/minio/minio/issues/5010

**Comment by jippi** [comment]
You can use the [header stanza](https://www.nomadproject.io/docs/job-specification/service.html#header-stanza)?

**Comment by schmichael** [comment]
@jippi's suggestion to use the `header` stanza should allow setting a user agent. Feel free to reopen if it doesn't!
