### ISSUE TITLE
/alloc dir not shared between tasks after restart of a task

### ISSUE THREAD

**Issue by hsmade** [hashicorp/nomad#3349]
Nomad version: 0.6.0

Given a 2 task job (1 group), I noticed that when one of the tasks gets restarted because it exited, the /alloc is no longer shared between the 2 tasks. The restarted task get's a new alloc dir.

    $ sudo docker inspect 2fa2541e2580 |grep -B1 '"Destination": "/alloc"'
                "Source": "/var/lib/nomad/alloc/70ee2222-d35c-9936-2792-e5308878fca9/alloc",
                "Destination": "/alloc",
    $ sudo docker inspect 3cdd42723be0 |grep -B1 '"Destination": "/alloc"'
                "Source": "/var/lib/nomad/alloc/bb799654-96de-7b80-13a6-0898e6f9bd4a/alloc",
                "Destination": "/alloc",

In here, my backend got restarted and got a new /alloc dir.
Stripped down hcl:

    job "myjob" {
      type = "system"
      region = "global"
      datacenters = ["dc1"]
      update {
       max_parallel = 0
        stagger      = "1s"
      }
    
      group "mygroup" {
        restart {
          attempts = 60
          delay    = "1s"
          interval = "1m"
          mode     = "delay"
        }
    
        task "backend" {
          driver = "docker"
          config {
            image = "some_docker_image"
            network_mode = "host"
           }
    
          resources {
            network {
                mbits = 1
            }
            cpu = 40
            memory = 128
          }
        }
        task "frontend" {
          driver = "docker"
          leader = true
          config {
            image = "nginx"
            network_mode = "host"
          }
    
          resources {
            cpu = 40
            memory = 32
            network {
              mbits = 1
              port "http" { static = 1234}
            }
          }
        }
      }
    }

**Comment by schmichael** [comment]
The docker command output you pasted shows 2 different allocations. If a task failed it would be restarted in place and not have a different allocation ID. Since `/alloc` directories are per-allocation, that explains why those two docker containers do not share an `/alloc` directory.

If Nomad started a new allocation it should have stopped all tasks in the old allocation, so if you're seeing both allocations running simultaneously there may be a bug.

Can you include the output of the following?

```sh
nomad alloc-status 70ee2222-d35c-9936-2792-e5308878fca9
nomad alloc-status bb799654-96de-7b80-13a6-0898e6f9bd4a
nomad status myjob
```

**Comment by hsmade** [comment]
I'll try to reproduce this, thanks!

**Comment by hsmade** [comment]
Can't reproduce. Closing
