### ISSUE TITLE
[question] How to advertise serf with NAT ip

### ISSUE THREAD

**Issue by krjensen** [hashicorp/nomad#3354]
I have 4 environments and they all have a Consul and a Nomad cluster

Looks like this

**ENV1**
*Server1*
ip: 192.168.1.11
nat: 10.70.1.11

*Server2*
ip: 192.168.1.12
nat: 10.70.1.12

*Server3*
ip: 192.168.1.13
nat: 10.70.1.13

**ENV2**
*Server1*
ip: 192.168.2.11
nat: 10.70.2.11

*Server2*
ip: 192.168.2.12
nat: 10.70.2.12

*Server3*
ip: 192.168.2.13
nat: 10.70.2.13

**ENV3**
*Server1*
ip: 192.168.3.11
nat: 10.70.3.11

*Server2*
ip: 192.168.3.12 
nat: 10.70.3.12

*Server3*
ip: 192.168.3.13
nat: 10.70.3.13

Alle servers are deployed in a virtual network and only the 10.70.0.0/16 is shared. But inside a network you are not able to access address that are NAT to the same network; So if you connect to 192.168.1.10 in ENV1, you cannot access 10.70.1.0/24 but you can access 10.70.2.0/24 and 10.70.2.0/24.

Here is my nomad server config:
```
datacenter = "${datacenter}"
data_dir   = "/var/nomad/"

server {
    enabled = true
    bootstrap_expect = 3
}

advertise {
    serf= "$PUBLIC_IP:4648"
}

telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
}

consul {
  address = "$PRIVATE_IP:8500"
}
```

As you can se I advertise the public ip, to be able to join ENV1, 2 and 3, but this do not work, since Nomad inside of my env, starts to use the 10.70.0.0/16 address.

In consul this is solved by using `retry_join: 192.x.x.x` and `retry_join_wan: 10.70.0.0`, but I do not have the same options in Nomad?

Hope you get what i'm trying to do here

**Comment by schmichael** [comment]
Unfortunately Nomad doesn't have the LAN vs WAN addressing functionality of Consul yet. Follow this issue to find out when it's added: #1484

In the meantime I'm afraid you'll have to allow serf connectivity between 10.70.x.x environments (possibly through a VPN).
