### ISSUE TITLE
Allow multiple jobs per job-file

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#3378]
Currently nomad artifically restricts job file to contain only one job and results in following if multiple jobs are specified: `'job': only one 'job' block allowed`.

I like the idea of keeping all my jobs in one file, why such limitation? Could you relax it?

**Comment by dadgar** [comment]
Hey we don't have any plans to do that. We like the mapping of one job to one job file and as we add interpolations `nomad run -var job.priority=80 foo.nomad` this logic would become more complex to implement.
