### ISSUE TITLE
Clarify units of docker.cleanup.image.delay in documentation

### ISSUE THREAD

**Issue by zstyblik** [hashicorp/nomad#3391]
Hello,

please, would it be possible to clarify units of `docker.cleanup.image.delay` in [documentation](https://www.nomadproject.io/docs/drivers/docker.html#docker-cleanup-image-delay)?

> A time duration that defaults to 3m. The delay controls how long Nomad will wait between an image being unused and deleting it.

Is it 3 minutes or 3 months? What if I want delay to be in months? In other words, something like ``docker.cleanup.image.delay is specified in minutes'' would be nice and sufficient.

Thank you.

**Comment by dadgar** [comment]
Closing with 1826d05d5! Thanks!

**Comment by zstyblik** [comment]
Thank you :)
