### ISSUE TITLE
acl bootstrap does not seem to find acl-bootstrap-reset file

### ISSUE THREAD

**Issue by zverocool** [hashicorp/nomad#3405]
### Nomad version
Nomad v0.7.0-beta1

### Operating system and Environment details
RHEL7 

### Issue
I am trying to reset ACL bootstrap token, and i am unable to do so. It looks like Nomad is not able to locate the file in the data dir.
It's also confusing to see if its `data-dir/acl-bootstrap-reset` or `data-dir/server/acl-bootstrap-reset` Documentation says `data-dir/server/` , but the code says https://github.com/hashicorp/nomad/blob/master/nomad/acl_endpoint.go#L417

So i have tried both ways... no luck.

### Reproduction steps
    # cat /etc/nomad/config/default.hcl
    data_dir = "/etc/nomad/data"

    [root@server1 data]# pwd
    /etc/nomad/data
    [root@server1 data]# ll
    total 8
    -rw-r--r--. 1 root root   5 Oct 17 14:53 acl-bootstrap-reset
    -rw-r--r--. 1 root root 394 Oct 17 12:14 checkpoint-signature
    drwx------. 4 root root  77 Oct 17 15:10 server

    [root@server1 server]# pwd
    /etc/nomad/data/server
    [root@server1 server]# ll
    total 8
    -rw-r--r--. 1 root root  5 Oct 17 15:10 acl-bootstrap-reset
    drwxr-xr-x. 3 root root 56 Oct 17 12:14 raft
    drwxr-xr-x. 2 root root 22 Oct 17 12:14 serf
    -rw-------. 1 root root 28 Oct 17 12:14 serf.keyring

    # nomad acl bootstrap
    Error bootstrapping: Unexpected response code: 500 (rpc error: ACL bootstrap already done (reset index: 42139))

### Nomad Server logs (if appropriate)
    Oct 17 15:16:05 server1 nomad[31977]: 2017/10/17 15:16:05.863717 [ERR] http: Request /v1/acl/bootstrap, error: rpc error: ACL bootstrap already done (reset index: 42139)
    Oct 17 15:16:05 server1 nomad[31977]: http: Request /v1/acl/bootstrap, error: rpc error: ACL bootstrap already done (reset index: 42139)

**Comment by dadgar** [comment]
@zverocool Are you putting the `reset index` into the file. It worked for me:

```
$ nomad acl bootstrap
Error bootstrapping: Unexpected response code: 500 (ACL bootstrap already done (reset index: 12))

$ echo "12" > /tmp/server1/server/acl-bootstrap-reset

$ nomad acl bootstrap
Accessor ID  = 4835c10f-b350-87b7-852d-926e4d11de0a
Secret ID    = d1f623eb-8951-78ba-d645-17e346ba5700
Name         = Bootstrap Token
Type         = management
Global       = true
Policies     = n/a
Create Time  = 2017-10-17 21:22:05.061745392 +0000 UTC
Create Index = 14
Modify Index = 14
```

**Comment by zverocool** [comment]
Alright taking a break away from this gave me some ideas.... and I was able to figure out what was the problem.

`acl-bootstrap-reset` file needs to be created on the current Leader node, upgrading the documentation with this will greatly help out people in the future, but other than that works as designed. 

    [root@server1 ~]# nomad acl bootstrap
    Error bootstrapping: Unexpected response code: 500 (rpc error: ACL bootstrap already done (reset index: 42139))
    [root@server1 ~]# echo "12" > /etc/nomad/data/server/acl-bootstrap-reset
    [root@server1 ~]# nomad acl bootstrap
    Error bootstrapping: Unexpected response code: 500 (rpc error: ACL bootstrap already done (reset index: 42139))
    [root@server1 ~]# nomad server-members
    Name           Address         Port  Status  Leader  Protocol  Build        Datacenter  Region
    server1.US  10.17.19.245    4648  alive   false   2         0.7.0-beta1  EST         US
    server2.US  10.17.16.43     4648  alive   false   2         0.7.0-beta1  EST         US
    server3.US  172.18.153.143  4648  alive   true    2         0.7.0-beta1  EST         US
    [root@server1 ~]# echo $NOMAD_TOKEN
    5fa414c2-b744-bb48-c639-9a3deb2f9a04


    ssh server3
    [root@server3 ~]# echo "12" > /etc/nomad/data/server/acl-bootstrap-reset
    [root@server3 ~]# nomad acl bootstrap
    Error bootstrapping: Unexpected response code: 500 (Invalid bootstrap reset index (specified 12, reset index: 42139))
    [root@server3 ~]# exit

    ssh server1
    [root@server1 ~]# nomad acl bootstrap
    Error bootstrapping: Unexpected response code: 500 (rpc error: Invalid bootstrap reset index (specified 12, reset index: 42139))

Note I know i am setting invalid reset index, since I wanted to see the different error message.

**Comment by dadgar** [comment]
@zverocool Good call! Will update the documentation! Thanks for the quick follow up!

**Comment by dadgar** [comment]
Improved docs 0bf7c1f5c

**Comment by xerxes95** [comment]
How can I determine the Nomad leader without the ACL token? I get an error when I try:

$ ssh $SERVER
$ cd $NOMAD_INSTALL_DIR
$ ./nomad server members
Error querying servers: Unexpected response code: 403 (Permission denied)

Is there a way to determine the leader without the ACL token? I'm getting permission denied when I try to find the leader.

Background: I am getting a slightly different error when I try to bootstrap the ACL system, 
`$ curl $SERVER:4646/v1/acl/bootstrap
Invalid bootstrap reset index (specified 48, reset index: 49)`

I have created a file named `acl-bootstrap-reset` in the runtime directory on ALL my servers in the cluster, with the text `49` on the first line. However, I continue to get the above error.

My only other thought is that I might need to put 49 on **only** the Nomad leader, rather than all the Nomad servers.
