### ISSUE TITLE
[ISSUE] Nomad 0.7.0 not respecting the anonymous namespace policy capabilities

### ISSUE THREAD

**Issue by Cryson** [hashicorp/nomad#3409]
### Nomad version
Nomad v0.7.0-beta1

### Operating system and Environment details
Red Hat Enterprise Linux Server release 7.4 (Maipo)

### Issue

I am adding the below configuration to the anonymous policy in nomad:

```
{
    "Name": "anonymous",
    "Description": "Allow read-only access for anonymous requests",
    "Rules": "
        namespace \"default\" {
            policy = \"read\"
            capabilities = [\"list-jobs\"]
        }
    "
}
```

When I add that to the anonymous token, from the documentation here (https://www.nomadproject.io/guides/acl.html#set-an-anonymous-policy-optional-) the default namespace should only be allowing me to query the /v1/jobs endpoint.

The issue is I can still query the /v1/job/<job name> endpoint as well, even though I have not specified the `read-job` capability (https://www.nomadproject.io/guides/acl.html#read-job)

### Reproduction steps

Create an anonymous policy with the above configuration and you'll still be able to hit /v1/job/<job name>, as well as other various endpoints even though `list-jobs` is the only capability specified.

### Why we need to fix this

We need to have a way to be able to specify endpoints and their anonymous capabilities. I believe the best way to do this is similar to how vault does it by allowing the following type of stanza in our policies:

```
path "v1/jobs" {
  policy = "read"
  capabilities = ["list-jobs"]
}
path "v1/job" {
  policy = "deny"
}
```

**Comment by dadgar** [comment]
@Cryson Since you have `policy = read`, you are giving the anonymous policy "read-job" as well: https://www.nomadproject.io/guides/acl.html#read-1

If you look right below the linked section you will see that we document the merging behavior:

> When both the policy short hand and a capabilities list are provided, the capabilities are merged:

**Comment by Cryson** [comment]
@dadgar So if I remove the `policy = read` and I only have the following: 
```
{
    "Name": "anonymous",
    "Description": "Allow read-only access for anonymous requests",
    "Rules": "
        namespace \"default\" {
            policy = \"read\"
            capabilities = [\"list-jobs\"]
        }
    "
}
```

I can hit the /v1/jobs endpoint and get the list of jobs, however, if I do /v1/job/jobname I still get the json data for that as well even though I am not specifying `read-job`. When I should not be able to do that, correct me if I am wrong.

**Comment by dadgar** [comment]
@Cryson It worked for me:

```
nomad acl policy apply -token=b37560b7-4ca1-d154-3530-a82cffe71d61 anonymous anonymous.hcl
Successfully wrote "anonymous" ACL policy!
$ nomad job status
ID       Type     Priority  Status   Submit Date
example  service  50        running  10/18/17 10:57:17 PDT
$ nomad job status example
Error querying job: Unexpected response code: 403 (Permission denied)
```

Where that policy file has:

```
namespace "default" {
  capabilities = ["list-jobs"]
}
```

**Comment by Cryson** [comment]
@dadgar Could you provide your anonymous.hcl. I'm curious about the layout of the file and would like to compare.

**Comment by dadgar** [comment]
@Cryson It is actually what I placed above. 

Just put this into a file `anonymous.hcl`: 
```
namespace "default" {
  capabilities = ["list-jobs"]
}
```

And then run: `nomad acl policy apply -token=<management token> anonymous anonymous.hcl`

**Comment by Cryson** [comment]
So I am following your steps, but my results are different. See below:
```
[root@XXXXX ~]# nomad acl policy apply -token=$NOMAD_TOKEN anonymous /etc/nomad/config/anonymous_token.hcl
Successfully wrote "anonymous" ACL policy!
[root@XXXXXXX ~]# curl -s http://127.0.0.1:4646/v1/acl/policy/anonymous -H "X-Nomad-Token: ${NOMAD_TOKEN}" | jq
{
  "Name": "anonymous",
  "Description": "",
  "Rules": "namespace \"default\" {\n  capabilities = [\"list-jobs\"]\n}\n",
  "Hash": "zJYGQth2nxrd+Ss6C9ziv2F5FMfPPigNKp6Hro3W/IY=",
  "CreateIndex": 83284,
  "ModifyIndex": 86428
}
[root@XXXXX ~]# nomad job status statsd
ID            = statsd
Name          = statsd
Submit Date   = 10/16/17 10:36:03 EDT
Type          = service
Priority      = 50
```

**Comment by dadgar** [comment]
Are you unsetting your environment variable when querying for the job status?
```
$ unset NOMAD_TOKEN
$ nomad job status statsd
```

You may just be querying with your root token?

**Comment by Cryson** [comment]
@dadgar So I removed the token and `nomad job status jobname` I get permission denied. However if I hit the api `curl -s http://localhost:4646/v1/job/jobname` I still get the json back. Is that expected behavior? I figured the policy should stop me from curling to the endpoint and getting json back.

**Comment by dadgar** [comment]
Hey @Cryson 

The beta didn't have full ACL coverage on all endpoints. On master it is working properly:

```
$ curl http://127.0.0.1:4646/v1/jobs?pretty=true
[
    {
        "CreateIndex": 9,
        "ID": "example",
        "JobModifyIndex": 9,
        "JobSummary": {
            "Children": {
                "Dead": 0,
                "Pending": 0,
                "Running": 0
            },
            "CreateIndex": 9,
            "JobID": "example",
            "ModifyIndex": 19,
            "Namespace": "default",
            "Summary": {
                "cache": {
                    "Complete": 0,
                    "Failed": 0,
                    "Lost": 0,
                    "Queued": 0,
                    "Running": 1,
                    "Starting": 0
                }
            }
        },
        "ModifyIndex": 16,
        "Name": "example",
        "ParameterizedJob": false,
        "ParentID": "",
        "Periodic": false,
        "Priority": 50,
        "Status": "running",
        "StatusDescription": "",
        "Stop": false,
        "SubmitTime": 1508389288642057000,
        "Type": "service"
    }
]

$  curl http://127.0.0.1:4646/v1/job/example
Permission denied
```

There will be an RC out very shortly that has full coverage! Thanks for reporting! 👍
