### ISSUE TITLE
Nomad interpolation docs have typos

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/nomad#3418]
Nomad [environment variables](http://localhost:4567/docs/runtime/interpolation.html#environment-variables-) docs has variables with missing underscores which is misleading. I have attached a screenshot below.

![image](https://user-images.githubusercontent.com/4024506/31758868-0762d15e-b464-11e7-9f3f-42d42c067868.png)

For example, `NOMAD_PORT<task><label>` should be `NOMAD_PORT_<task>_<label>`. The html templates are written correctly [here](https://github.com/hashicorp/nomad/blob/master/website/source/docs/runtime/_envvars.html.md.erb#L117) but the rendering isn't working as expected.

**Comment by schmichael** [comment]
Yikes! Thanks for pointing that out!

**Comment by anubhavmishra** [comment]
np!
