### ISSUE TITLE
[SDK/enhancement] allow providing http.Client when creating api.Client

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#3422]
As part of my hashi-ui tweaks, i've hit a case where i need to tweak the connection timeout (`DialContext{Timeout}`) of the `http.Client` and be able to control a few other params

Currently this property is private to the api package, making it impossible to inject a client with the required config changes

**Comment by tgross** [comment]
Doing a little tidying up. This was done in https://github.com/hashicorp/nomad/pull/5275 which shipped with 0.9
