### ISSUE TITLE
[question] No alloctions on nomad run, with the desired change ignore 1

### ISSUE THREAD

**Issue by venugopalanAG** [hashicorp/nomad#3442]
Allocation is ignored after evaluation the nomad file 

`Desired Changes for "company": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)`
 
### Nomad version
Output from `Nomad v0.6.3`

### Operating system and Environment details
`Ubuntu Xenial`

### Nomad Logs
group count = 1
```
2017/10/25 08:09:05.285172 [DEBUG] http: Request /v1/jobs (8.698768ms)
    2017/10/25 08:09:05.285314 [DEBUG] worker: dequeued evaluation cb06042b-0cfb-a542-7190-5cae91160d8a
    2017/10/25 08:09:05.310278 [DEBUG] http: Request /v1/status/peers (1.031298ms)
    2017/10/25 08:09:05.385741 [DEBUG] sched: <Eval 'cb06042b-0cfb-a542-7190-5cae91160d8a' JobID: 'company-revenue-periodic-process'>: Total changes: (place 0) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "company": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)
    2017/10/25 08:09:05.385762 [DEBUG] sched: <Eval 'cb06042b-0cfb-a542-7190-5cae91160d8a' JobID: 'company-revenue-periodic-process'>: setting status to complete
    2017/10/25 08:09:05.406034 [DEBUG] worker: updated evaluation <Eval 'cb06042b-0cfb-a542-7190-5cae91160d8a' JobID: 'company-revenue-periodic-process'>
    2017/10/25 08:09:05.406992 [DEBUG] worker: ack for evaluation cb06042b-0cfb-a542-7190-5cae91160d8a
    2017/10/25 08:09:06.294116 [DEBUG] http: Request /v1/evaluation/cb06042b-0cfb-a542-7190-5cae91160d8a (1.14317ms)
    2017/10/25 08:09:09 [DEBUG] memberlist: TCP connection from=10.20.61.4:59599
```

**Comment by schmichael** [comment]
Could you share your job file or at least what you're changing in it? What does `nomad plan ...` output for the job you're submitting?

Using the [evaluation API](https://www.nomadproject.io/api/evaluations.html#read-evaluation) is useful if an evaulation is blocked, but since it completed successfully it probably isn't useful.

**Comment by dadgar** [comment]
@venugopalanAG Just to be clear, this may be the correct behavior. If the allocation is running and there is nothing to do the scheduler will ignore the allocation.

**Comment by venugopalanAG** [comment]
@dadgar Just to clarify, if allocation is running the `place/inplace` should be 1,right?
In my case, no job is in running state,state of it is dead 
`Total changes: (place 0) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "company": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)`

@schmichael It happened few time for the batch jobs ,I can't able to figure out the pattern.
But after make changes like changing group name it got fixed

**Comment by dadgar** [comment]
@venugopalanAG That is the changes the scheduler wants to make. So the scheduler did not want to make any changes. If you batch job finished, Nomad won't rerun it when you run the job unless you change the job name or something about the job. I am going to close this for now as it seems like there is no bug.
