### ISSUE TITLE
API for purging nodes

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3444]
We need an API to purge nodes on the servers. The use case is we run Nomad on bare metal machines and sometimes when the machine fails because of hardware issues and is fixed by data-center operators we have to re-image the machine and have them join back in. The machines have the same host name and IP addresses so re-registration with servers fail because of mismatch in secret IDs.

I am thinking an API to purging the node in the server should help in this case. The security side of things are handled in our case by secure introduction of the machines(can't go into the details but a machine can't simply appear in the DC or join a cluster).

@dadgar want to weigh in your thoughts? I can work on the implementation since we need this right away.

**Comment by dadgar** [comment]
@diptanu I am not opposed to the method, I think it can reuse the existing Node.Deregister RPC. As for your immediate problem, what version of Nomad are you running? If you have cleared the data_dir, the node should come back with a new (node_id, secret_id) pair and re-registartion should work. We don't use the host based uuid by default anymore. You can force this by setting this: https://www.nomadproject.io/docs/agent/configuration/client.html#no_host_uuid

**Comment by diptanu** [comment]
@dadgar Sounds good, I will get started on that API. We are on 0.5.6 + some code for the ipv6 fixes, the team is going to roll out a new version when 0.7 comes out.
