### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#3456]
`Nomad v0.6.2`
`Ubuntu 16.04 x64`

Sometimes when nomad starts the container. He gives him the port that is busy with an outbound connection. 

I found the solution: shrink ephemeral port range ( https://github.com/hashicorp/nomad/pull/2856/files ), but I have no way to change it.

Can we set  a range of ports to nomad config ?

**Comment by angrycub** [comment]
While we don't have provisions for changing Nomad's range, the operating system can be tuned to prevent overlap.  See https://www.nomadproject.io/guides/cluster/requirements.html#ports-used for more details.    I'll mark this resolved, but please comment back if I did not fully understand your issue.
