### ISSUE TITLE
Nomad shows node as "ready" even though it is down (and nomad knows it's down) 

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#3458]
### Nomad version
Nomad v0.6.3

### Operating system and Environment details
debian

### Issue

I have a number of nomad client boxes that were shut down. However, nomad still shows the node as being in the "ready" state when I do a nomad node-status. However, when I list the allocations on the node, they show as being `lost` with a message `alloc is lost since its node is down`.   Clearly nomad knows the node is down, but is not registering it as such.  It is also trying to create new allocations on those nodes which causes all sorts of problems (I have put them in `drain` state so that things can keep working).

Note that this is very similar to #3072 .  However, in that case we tracked the issue to node data being too large.  That does not seem to be the cause here.

Here are the details:

When I do a `nomad node-status` I get:
```
error fetching node stats (HINT: ensure Client.Advertise.HTTP is set): Get https://internal-cluster-0df.stag.awse.traitify.com:4646/v1/client/stats?region=global: dial tcp 10.1.200.206:4646: i/o timeout
ID      = d6988f10
Name    = internal-cluster-0df.stag.awse
Class   = <none>
DC      = awse
Drain   = true
Status  = ready
Drivers = exec

Allocated Resources
CPU         Memory       Disk        IOPS
0/2500 MHz  0 B/3.7 GiB  0 B/16 GiB  0/0

Allocation Resource Utilization
CPU         Memory
0/2500 MHz  0 B/3.7 GiB

error fetching node stats (HINT: ensure Client.Advertise.HTTP is set): actual resource usage not present

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created At
4b585ab6  d6988f10  app         24       stop     lost      10/25/17 14:48:28 EDT
```
Notice it shows a `status` of `ready`, but under allocations it shows `lost`.   When I do an `alloc-status` on that allocation I get:

```
ID                  = 4b585ab6
Eval ID             = a52b271b
Name                = gambit-stag.app[1]
Node ID             = d6988f10
Job ID              = gambit-stag
Job Version         = 24
Client Status       = lost
Client Description  = <none>
Desired Status      = stop
Desired Description = alloc is lost since its node is down
Created At          = 10/25/17 14:48:28 EDT
Deployment ID       = 3b1dc798
Deployment Health   = healthy

Couldn't retrieve stats (HINT: ensure Client.Advertise.HTTP is set): Get https://internal-cluster-0df.stag.awse.traitify.com:4646/v1/client/allocation/4b585ab6-f984-c164-a852-2fd037b719c9/stats?region=global: dial tcp 10.1.200.206:4646: i/o timeout
...
```

Notice that it tells us `alloc is lost since its node is down`

Thanks!

**Comment by dadgar** [comment]
@dansteen Could you provide all your server logs? Would you mind doing `curl -XPUT http://127.0.0.1:4646/v1/system/gc` before collecting the logs?

**Comment by dansteen** [comment]
Ok.  I ran the gc and gathered some logs.   We have 3 nomad servers in our cluster, so I have included logs from each one.  

One other thing that I noticed is that we seem to have an extra server listed in `nomad operator raft list-peers`:

```
Node              ID                 Address            State     Voter
nomad-0ea.global  10.1.99.123:4647   10.1.99.123:4647   follower  true
nomad-02f.global  10.1.200.13:4647   10.1.200.13:4647   follower  true
nomad-0dc.global  10.1.200.16:4647   10.1.200.16:4647   leader    true
(unknown)         10.1.200.164:4647  10.1.200.164:4647  follower  true
```
compared to the output of `nomad server-members`
```                                                                                
Name              Address      Port  Status  Leader  Protocol  Build  Datacenter  Region
nomad-02f.global  10.1.200.13  4648  alive   false   2         0.6.3  awse        global
nomad-0dc.global  10.1.200.16  4648  alive   true    2         0.6.3  awse        global
nomad-0ea.global  10.1.99.123  4648  alive   false   2         0.6.3  awse        global
```
I don't know where that came from, or what box it is since it doesn't seem to actually exist at this point.  Could that be related to the problem?

[nomad1.log](https://github.com/hashicorp/nomad/files/1423171/nomad1.log)
[nomad2.log](https://github.com/hashicorp/nomad/files/1423168/nomad2.log)
[nomad3.log](https://github.com/hashicorp/nomad/files/1423166/nomad3.log)

**Comment by dadgar** [comment]
@dansteen Ah I should have asked for you to up the log level to debug first. Would you mind doing that and then letting it run like that for ~20ish minutes, GC and then send those? You can bump the log level in the config and just SIGHUP the servers.

**Comment by dadgar** [comment]
I would also do a `nomad operator raft remove-peer` on the incorrect node

**Comment by dansteen** [comment]
@dadgar sorry about that, I should have known.  Anyway, here are the fancy new logs:
[nomad3.log](https://github.com/hashicorp/nomad/files/1423544/nomad3.log)
[nomad2.log](https://github.com/hashicorp/nomad/files/1423545/nomad2.log)
[nomad1.log](https://github.com/hashicorp/nomad/files/1423546/nomad1.log)

**Comment by dadgar** [comment]
@dansteen Can you show me the metric `nomad.heartbeat.active` and the output of `curl 127.0.0.1:4646/v1/nodes`.

You can get the heartbeat metric either from your metrics sink or if you aren't exporting them if you send SIGUSR1 on the leader node it will output the metrics to the STDERR

**Comment by dansteen** [comment]
Unfortunately (or fortunately?) it looks like it finally figured out that those nodes were down.  Here is the output of  curling the nodes:

```[{"ID":"05072c00-b269-2fef-6631-a06c43c4fe87","Datacenter":"awse","Name":"woofound-008.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1158424,"ModifyIndex":1263436},{"ID":"0c01f3c6-56fc-38a6-973a-3e48ec42a56b","Datacenter":"awse","Name":"core-0fa.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":540563,"ModifyIndex":1302914},{"ID":"0c913dd4-a9c4-a532-096b-120404d177f6","Datacenter":"awse","Name":"admin-interface-005.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":498909,"ModifyIndex":1300507},{"ID":"0dab9782-b1da-713f-899a-f8776f76d4a4","Datacenter":"awse","Name":"deck-validator-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222365,"ModifyIndex":1331444},{"ID":"1007da5a-26de-997b-4fd0-d4b08de17d69","Datacenter":"awse","Name":"deck-validator-0d1.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":805972,"ModifyIndex":1260691},{"ID":"1171c72f-294c-9e1a-2734-9c725168951d","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1282706,"ModifyIndex":1331445},{"ID":"16913d8d-e996-b9f8-d94c-52843bfddd2b","Datacenter":"awse","Name":"admin-interface-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222578,"ModifyIndex":1331446},{"ID":"1bc9eee6-c6e7-8994-2f04-fb1aaaee0260","Datacenter":"awse","Name":"orgs-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222341,"ModifyIndex":1331447},{"ID":"1fe66cb1-91d3-2196-6431-08f1845ecf75","Datacenter":"awse","Name":"api-047.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1057062,"ModifyIndex":1057065},{"ID":"27aa5e74-745c-1aed-92c5-425983f541f8","Datacenter":"awse","Name":"woofound-0e5.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":803843,"ModifyIndex":1263492},{"ID":"27c5a00b-4c75-ad16-7ea1-62612d22fc3c","Datacenter":"awse","Name":"utility-debian-jessie-ec2","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222382,"ModifyIndex":1331448},{"ID":"2e753b69-cd43-a41c-08ac-22e477df3623","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1278760,"ModifyIndex":1331449},{"ID":"2f908c13-36ca-b6cf-7489-bcbc8068ee6d","Datacenter":"awse","Name":"internal-cluster-034.stag.awse","NodeClass":"","Version":"0.6.3","Drain":true,"Status":"down","StatusDescription":"","CreateIndex":1222651,"ModifyIndex":1331450},{"ID":"310718d4-a82c-0abc-0c4d-b29e0fc9c942","Datacenter":"awse","Name":"deck-validator-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222567,"ModifyIndex":1331451},{"ID":"31ff8691-2f15-4172-967f-1fe4340ef0ae","Datacenter":"awse","Name":"api-cluster-0a4.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1115675,"ModifyIndex":1166664},{"ID":"356871a4-8894-2b3f-b7a5-ac5e17db41d7","Datacenter":"awse","Name":"fileserve-09a.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":803311,"ModifyIndex":1299258},{"ID":"392d0b8f-6c43-6b7b-29e5-b4f0b3d5bda1","Datacenter":"awse","Name":"deck-validator-085.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":805999,"ModifyIndex":1260696},{"ID":"3fc8b7eb-f7b5-3391-6b20-2c44f9afc8c0","Datacenter":"awse","Name":"fileserve-044.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":803300,"ModifyIndex":1258895},{"ID":"421e8917-7363-9f99-2c1b-c29c64d2455a","Datacenter":"awse","Name":"utility-02f.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":499584,"ModifyIndex":1287801},{"ID":"46ece8ff-46ef-d1d9-2aa9-68437563d029","Datacenter":"awse","Name":"utility-004.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":438963,"ModifyIndex":1263526},{"ID":"48a53867-0d75-2b1a-acaa-d906ff126e2b","Datacenter":"awse","Name":"images-02d.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":518631,"ModifyIndex":1302839},{"ID":"49d1ec09-029c-d97e-a1b3-e20f808d2360","Datacenter":"awse","Name":"admin-interface-055.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":498819,"ModifyIndex":1286915},{"ID":"567a8ee7-e5b7-c8c7-909d-d3a473f83fda","Datacenter":"awse","Name":"api-cluster-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1223131,"ModifyIndex":1331452},{"ID":"58034cd5-51fe-b681-dd7e-d99adae98058","Datacenter":"awse","Name":"api-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222557,"ModifyIndex":1331453},{"ID":"5ad2de90-e151-08ec-bb30-599867278f21","Datacenter":"awse","Name":"billing-0f2.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":518388,"ModifyIndex":1302460},{"ID":"5cd6aca6-f38b-495b-d388-424403ed60c9","Datacenter":"awse","Name":"billing-087.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":518732,"ModifyIndex":1302875},{"ID":"5dd8cfc9-578e-455e-b282-2739cd64e9e5","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1242252,"ModifyIndex":1242253},{"ID":"624984b6-552c-0338-3103-53a2106295fa","Datacenter":"awse","Name":"internal-cluster-0ba.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1289560,"ModifyIndex":1289561},{"ID":"643f7262-09e9-ce8a-b331-4c26d70d6e4a","Datacenter":"awse","Name":"orgs-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222553,"ModifyIndex":1331454},{"ID":"7afd5aec-7e0d-ee60-c12e-a6d18e457bf2","Datacenter":"awse","Name":"internal-cluster-035.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1289537,"ModifyIndex":1289700},{"ID":"7e7d2d78-a169-df1d-14fb-bc9ad5d3433e","Datacenter":"awse","Name":"orgs-0fc.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":519100,"ModifyIndex":1303731},{"ID":"8b9c4d87-7bb7-a296-72cb-7e9bd85824d4","Datacenter":"awse","Name":"orgs-0c8.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":518580,"ModifyIndex":1303015},{"ID":"8fdd3a35-5517-2a21-801d-bf1032b5716d","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222561,"ModifyIndex":1331455},{"ID":"9c7726f2-156c-d455-0773-c24b6ad96eca","Datacenter":"awse","Name":"api-051.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1057087,"ModifyIndex":1057089},{"ID":"9cf10e88-6e45-4a39-9d58-0e9fe6bee086","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1243151,"ModifyIndex":1331456},{"ID":"9e52273b-f641-d0e1-2748-558343be8e8a","Datacenter":"awse","Name":"api-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222349,"ModifyIndex":1331457},{"ID":"a3eaf6ef-085b-48b6-cdd3-272e37bc34e1","Datacenter":"awse","Name":"api-cluster-046.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1115773,"ModifyIndex":1166623},{"ID":"a424bb84-27f5-3e37-6b8b-75f1bc7a67ac","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1242985,"ModifyIndex":1331458},{"ID":"a778eec8-ce55-f73a-4c37-2a69d655172e","Datacenter":"awse","Name":"api-cluster-087.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1115717,"ModifyIndex":1166715},{"ID":"add73f90-53bd-0542-762e-3a0384825da6","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1281952,"ModifyIndex":1331459},{"ID":"b7aa8f0d-b39c-e4fa-36bc-1d54c1e5126f","Datacenter":"awse","Name":"fileserve-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222544,"ModifyIndex":1331460},{"ID":"c1c19ed2-52ea-cc7a-5ce5-c7ea3d526f6e","Datacenter":"awse","Name":"images-0d1.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":518421,"ModifyIndex":1302391},{"ID":"c27dfdd0-f4a4-ed0a-d35e-78d7a245981b","Datacenter":"awse","Name":"admin-interface-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222359,"ModifyIndex":1331461},{"ID":"d295309f-55e9-2e6a-699e-0f2992c53003","Datacenter":"awse","Name":"utility-06c.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":499562,"ModifyIndex":1287551},{"ID":"d66284a6-bb69-889d-d893-2dcaae8d6f4c","Datacenter":"awse","Name":"billing-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222356,"ModifyIndex":1331462},{"ID":"d6988f10-37e1-0e33-5e9b-632fb9c2b114","Datacenter":"awse","Name":"internal-cluster-0df.stag.awse","NodeClass":"","Version":"0.6.3","Drain":true,"Status":"down","StatusDescription":"","CreateIndex":1222673,"ModifyIndex":1331463},{"ID":"df0e8cf3-3a83-a87f-efb8-bf9dea876f6c","Datacenter":"awse","Name":"api-cluster-051.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":1115756,"ModifyIndex":1166658},{"ID":"e964e768-364e-83cd-89db-25dbb00bc658","Datacenter":"awse","Name":"utility-debian-jessie-ec2","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222604,"ModifyIndex":1331464},{"ID":"ec253e5b-2dff-c3d5-853e-4dbbbcb6303d","Datacenter":"awse","Name":"core-0af.stag.awse","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"ready","StatusDescription":"","CreateIndex":100561,"ModifyIndex":1189511},{"ID":"eeb98acf-9e2b-c3c9-3825-9637370cb765","Datacenter":"awse","Name":"images-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222601,"ModifyIndex":1331465},{"ID":"f14a9929-4fcf-ca57-a927-4c839b5a9c01","Datacenter":"awse","Name":"woofound-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222338,"ModifyIndex":1331466},{"ID":"f5e333f4-0c37-e12c-afd0-000a4d0ffc02","Datacenter":"awse","Name":"api-cluster-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222387,"ModifyIndex":1331467},{"ID":"f838c291-5f25-8f4b-d4ce-31522f45a601","Datacenter":"awse","Name":"billing-test-kitchen","NodeClass":"","Version":"0.6.3","Drain":false,"Status":"down","StatusDescription":"","CreateIndex":1222565,"ModifyIndex":1331443}]```

Here are graphs of the `nomad.heartbeat.active` metric.  I hadn't set `disable_hostname = true` yet, so the metric is divided across my three boxes.   That's annoying, but it brings to light that it seems like my active nomad node is changing back and fourth fairly frequently.  Is that normal?

<img width="961" alt="screen shot 2017-10-28 at 11 01 56 pm" src="https://user-images.githubusercontent.com/64940/32140324-140b6d12-bc34-11e7-8aeb-9a03713074e6.png">

**Comment by dadgar** [comment]
@dansteen Ah! Your leadership flapping explains this issue. You are loosing leadership roughly every minute:

```
7772:Oct 27 17:28:29 nomad-02f nomad[24645]:     2017/10/27 17:28:29.077011 [INFO] nomad: cluster leadership lost
8131:Oct 27 17:29:34 nomad-02f nomad[24645]:     2017/10/27 17:29:34.796362 [INFO] nomad: cluster leadership lost
8483:Oct 27 17:31:08 nomad-02f nomad[24645]:     2017/10/27 17:31:08.749761 [INFO] nomad: cluster leadership lost
8795:Oct 27 17:32:12 nomad-02f nomad[24645]:     2017/10/27 17:32:12.135644 [INFO] nomad: cluster leadership lost
9783:Oct 27 17:36:50 nomad-02f nomad[24645]:     2017/10/27 17:36:50.811047 [INFO] nomad: cluster leadership lost
10149:Oct 27 17:37:55 nomad-02f nomad[24645]:     2017/10/27 17:37:55.877377 [INFO] nomad: cluster leadership lost
```
Only the leader will mark a node as down based on the heartbeat, and when there is a transition, a 5 minute grace period is applied before marking a node as down. This is done to ensure that all the clients in the cluster learn about the new leader so they don't get marked as down needlessly.

Since you didn't have a leader for the 5 minutes + the timeout, those nodes didn't get marked as down. Based on the metrics you showed, as soon as there was a leader for a longer amount of time, the nodes were marked as down.

Looking at your logs, you are having contact times around ~750ms between servers. You need to reduce that significantly: https://www.nomadproject.io/guides/cluster/requirements.html#network-topology

I am going to close this issue now that we know what is happening. I will be looking into potentially changing the grace period based on cluster size since 5m may be a bit too conservative on smaller clusters.

**Comment by dansteen** [comment]
Nice!  Where in the logs do you see that we have >750ms?   From what I can see we are sub 1ms:

```
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=1 ttl=64 time=0.503 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=2 ttl=64 time=0.490 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=3 ttl=64 time=0.443 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=4 ttl=64 time=0.499 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=5 ttl=64 time=0.502 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=6 ttl=64 time=0.456 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=7 ttl=64 time=0.503 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=8 ttl=64 time=0.431 ms
```
```
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=1 ttl=64 time=0.503 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=2 ttl=64 time=0.490 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=3 ttl=64 time=0.443 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=4 ttl=64 time=0.499 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=5 ttl=64 time=0.502 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=6 ttl=64 time=0.456 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=7 ttl=64 time=0.503 ms
64 bytes from nomad-0dc.stag.awse.node.awse.consul (10.1.200.16): icmp_seq=8 ttl=64 time=0.431 ms
```

As a note, these servers are all in different Availability Zones in the same DataCenter in AWS.

**Comment by dadgar** [comment]
@dansteen Hmm usually AZs have a good network latency between them. May have been a ephemeral issue. You can see the results of grepping `contact.*in `:  https://gist.github.com/dadgar/623840e44ed09c741264a7bbad391310

You should monitor the metric `nomad.raft.leader.lastContact`. For more telemetry details check out: https://www.nomadproject.io/docs/agent/telemetry.html

**Comment by dansteen** [comment]
Thanks @dadgar here is a graph of `nomad.raft.leader.lastContact`:

<img width="494" alt="screen shot 2017-10-30 at 4 57 58 pm" src="https://user-images.githubusercontent.com/64940/32195393-872b329a-bd93-11e7-9b32-0b075ba182bb.png">

I'm not sure I believe that we had latency of 15 seconds between the two boxes, but it certainly illustrates your point!   If we see this again I'll start debugging from there.   Thanks for all your help with this.
