### ISSUE TITLE
Singularity support

### ISSUE THREAD

**Issue by benepo** [hashicorp/nomad#3463]
Please consider adding support for Singularity: http://singularity.lbl.gov/install-linux

Singularity is a more secure alternative to Docker and popular in HPC/supercomputer environments.

**Comment by chelseakomlo** [comment]
Thanks for the suggestion. We are planning to move to a driver plugin architecture and won't be adding any more first class drivers in the near future. After we enable pluggable drivers, this is a feature someone could develop and manage externally.

**Comment by vin047** [comment]
@chelseakomlo is there an issue/pr that we can track to be notified about updates regarding support for custom drivers?

**Comment by dadgar** [comment]
@vin047 https://github.com/hashicorp/nomad/issues/468
