### ISSUE TITLE
Publish job summaries as metrics

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3465]
Nomad is being offered as a service to users who want to be notified if the number of allocations they are running is not same as the desired state.

This would be easier to do if Nomad published job summary as a metric and allowed users to write rules in our internal monitoring system service. We don't want every user to write blocking queries against the job summary or the allocations API to keep track of the number of running allocations.

cc/ @dadgar

**Comment by diptanu** [comment]
I can work on this by the way since we need this for operational purposes.

**Comment by chelseakomlo** [comment]
This sounds like a great addition, and something that would be helpful in general.
