### ISSUE TITLE
Support wrapped Vault token at nomad startup

### ISSUE THREAD

**Issue by flyhard** [hashicorp/nomad#3473]
I have been trying to get Nomad to start when I provide a wrapped token to it via environment variable. It appears that this doesn't work at the moment.

Even if I am running vault on a secured machine, I'd like to not show the token that the server uses for anyone with /proc access.

I suggest that this needs to be put into the application.

**Comment by dadgar** [comment]
@flyhard Can you put it in the config file and have that file be in a folder such that only the Nomad user has access to it?
