### ISSUE TITLE
Nomad running in docker - files in /secrets not visible to tasks

### ISSUE THREAD

**Issue by hamann** [hashicorp/nomad#3481]
We're running nomad inside a docker container, mount a named volume `nomad` from host into nomad container and set nomad's data dir with
 `data_dir = "/var/lib/docker/volumes/nomad/_data"`

Extract from `docker inspect nomad`

```sh
{
    "Type": "volume",
    "Name": "nomad",
    "Source": "/var/lib/docker/volumes/nomad/_data",
    "Destination": "/var/lib/docker/volumes/nomad/_data",
    "Driver": "local",
    "Mode": "rw",
    "RW": true,
    "Propagation": ""
}
```

This works so far, e.g. task logs are visibile inside nomad container and also on host at the same paths.

Now we added vault integration to nomad and expected to see a `vault_token` file in task's `/secrets` directory. But because nomad uses a tmpfs for secrets, which is then created inside the nomad container, that tmpfs isn't visible on host and so that file doesn't exist in the task, it's a different mount.

```sh
docker exec nomad mount | grep secrets | grep a6d21b56-d073-3e50-c371-48f0bdd583bc |grep phoenix
tmpfs on /var/lib/docker/volumes/nomad/_data/alloc/a6d21b56-d073-3e50-c371-48f0bdd583bc/phoenix/secrets type tmpfs (rw,seclabel,noexec,relatime,size=1024k)

docker exec -i nomad cat /var/lib/docker/volumes/nomad/_data/alloc/a6d21b56-d073-3e50-c371-48f0bdd583bc/phoenix/secrets/foo
hello_from_nomad

echo hello_from_host | sudo tee /var/lib/docker/volumes/nomad/_data/alloc/a6d21b56-d073-3e50-c371-48f0bdd583bc/phoenix/secrets/foo

docker exec -i nomad cat /var/lib/docker/volumes/nomad/_data/alloc/a6d21b56-d073-3e50-c371-48f0bdd583bc/phoenix/secrets/foo
hello_from_nomad

sudo cat /var/lib/docker/volumes/nomad/_data/alloc/a6d21b56-d073-3e50-c371-48f0bdd583bc/phoenix/secrets/foo
hello_from_host

docker exec phoenix-a6d21b56-d073-3e50-c371-48f0bdd583bc cat /secrets/foo
hello_from_host
```

Is it possible to not use a `tmpfs` for secrets or is there maybe another solution?

**Comment by dadgar** [comment]
Hey @hamann,

We recommend not running Nomad clients in a Docker container. It is not currently something we are testing against and as such it isn't exactly supported.

**Comment by hamann** [comment]
Alright, thanks. We're using CoreOS and it's easier there to put/deploy everything in containers and to populate exec/raw-exec environments with tools installed in the nomad image instead of hosting/compile them somehow on CoreOS.

**Comment by giacomocariello** [comment]
+1

**Comment by ZZZXie** [comment]
It's been 5 years.. but I have a CI testing that relies on running Nomad in Docker. and needs to have nomad in docker to deploy a new job in docker. This empty secrets folder issue still exists. Any updates on this? or if there is any workaround?
