### ISSUE TITLE
Support for docker load/docker import.

### ISSUE THREAD

**Issue by ghost** [hashicorp/nomad#349]
It would be helpful to have the ability to source docker images/containers from tarballs pulled via http alongside a docker registry (as most private docker registries are still relatively primitive and not all code is appropriate for docker hub).

Using docker load on an image tarball would probably be the most straightforward solution though also being able to do docker import on a container tarball would be helpful if you wanted to ship a artifact without all of the intermediate read-only file system layers.

**Comment by dadgar** [comment]
Yeah that sounds worthwhile. I think we wouldn't want to support `docker load` as that is source locally but `docker import` would be useful. We would be happy to take a PR for this if you are interested.

**Comment by dadgar** [comment]
Not sure we will support this for the time being unless something pressing comes up as we support auth for private docker registries and it seems like that is becoming an accepted solution. AWS ECS
