### ISSUE TITLE
GC memory leak / crash, 0.6.3+

### ISSUE THREAD

**Issue by discobean** [hashicorp/nomad#3506]
Running 0.6.3 ran a manual GC after some time (1 week?), and 2 server agents in the cluster failed and lost quorum.

During the GC CPU spiked on the servers until they were no longer accessible.

I tried upgrading to 0.7.0 and starting with the same state, but the server agents crashed after using up all memory once more. 

Attached is a dump of the logs that ends with `fatal error: runtime: out of memory` from the process, stacktrace is included.

The resolution was to terminate masters and rebuild/restore jobs from backup.

[nomad.dmp.txt](https://github.com/hashicorp/nomad/files/1444686/nomad.dmp.txt)

**Comment by dadgar** [comment]
@discobean Do you have any monitoring on the node you can share? Can you share the Nomad processes memory over time?

**Comment by discobean** [comment]
Unfortunately instances were terminated so I lost all of this information :(

**Comment by dadgar** [comment]
@discobean How much memory does that node have?

**Comment by dadgar** [comment]
@discobean bumping this ^

**Comment by dadgar** [comment]
@discobean I am going to close this until there is more information. I did an audit through the code path of the panic and the transaction being performed is limited already. I think you may have just been running on a machine with low resources.

**Comment by discobean** [comment]
Just had a similar issue with #3586 will update there.
