### ISSUE TITLE
Support for uniform allocation placements across DCs

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3507]
Once we land #3499, we will need a way for Nomad to not bin-pack by default for allocations requesting GPUs. Running all the GPUs hot on certain machines in the DC will result in uneven cooling and cause thermal imbalance.

cc/ @dadgar

**Comment by dropje86** [comment]
@diptanu this PR is still open https://github.com/hashicorp/nomad/pull/2168
I guess that could solve it and is a general feature which would be nice.

**Comment by tgross** [comment]
Closed by the spread constraint and the spread scheduler.
