### ISSUE TITLE
Template source relative to job

### ISSUE THREAD

**Issue by ericc-ecobee** [hashicorp/nomad#3519]
I want to pass some config to my task, but the template stanza only reads from the host's filesystem, not my local filesystem. I understand that the artifact stanza delivers files to the host's filesystem, but I do not want to create a http server (or similar) just to deliver these configs.

It would be great if nomad can support templates from files residing on the local filesystem.

A possible work around is to wrap the nomad job in a script that inlines these configs, but that work around is pretty nasty.

Nomad version: 0.6.3

**Comment by dadgar** [comment]
Hey @ericc-ecobee,

This will not be something we will be supporting. If you would like to do that I suggest you use some templating tools to generate the job file itself. You can even use Consul Template to generate the job file and then run that.
