### ISSUE TITLE
Add support for wrapped tokens

### ISSUE THREAD

**Issue by rynmrtn** [hashicorp/nomad#3522]
Nomad, via the `vault` stanza, supports the retrieval of a Vault Token and the introduction of this secret into a scheduled job. At present, it only supports unwrapped tokens. If a token were intercepted, it would allow an actor to make requests to obtain secrets within our system.

Vault has support for [wrapped tokens](https://www.vaultproject.io/docs/concepts/response-wrapping.html). This methodology allows the process performing secret introduction to only have access to a token with a _limited lifetime_ while also providing _cover_ and _malfeasance detection_.

I think this is an important security feature that should be included within Nomad.

**Comment by dadgar** [comment]
Hey I am glad you think it is important too 😄 All tokens transmitted to clients use wrapped tokens. You can see a deep dive into how we have implemented this here: https://www.youtube.com/watch?v=4gAYyAA6h9E
