### ISSUE TITLE
[ui] [improvement] Configurable page-size for Jobs and Clients

### ISSUE THREAD

**Issue by ElliotG** [hashicorp/nomad#3523]
### Nomad version
0.7.0

### Issue
The Job UI defaults pagination to 10 items. It would be ideal to make this configurable (i.e. the typical: display 10, 25, 50, 100) size drop down. This is also similar for the client workflow (top 8).

**Comment by blockmar** [comment]
At least make the page size larger, like 25 or 50. I much prefer scrolling over paging

https://github.com/hashicorp/nomad/blob/master/ui/app/controllers/jobs/index.js#L22

**Comment by derzufall** [comment]
+1 for configurable page sizes! A get-param would even suffice for our purposes.
