### ISSUE TITLE
Stats not available in nomad ui deployment view

### ISSUE THREAD

**Issue by commarla** [hashicorp/nomad#3527]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
Debian Jessie

### Issue
On the page `http://nomad/ui/jobs/my-service/deployments` the stats are not available because of a Security Content policy violation.

This header is responsible. We can't load a content from a different address than the nomad server itself : https://github.com/hashicorp/nomad/blob/52598bff7e4a715d5037a5ab4077454671650e54/command/agent/http.go#L253

Is this header relevant?

### Reproduction steps
Just open the url and open the browser console
Chrome 61 and Firefox 58

### Browser JS console

> Content Security Policy: The page’s settings blocked the loading of a resource at http://10.32.25.105:4646/v1/client/allocation/b0d428e6-dd34-333f-e7ab-ae2a2172d127/stats (“connect-src http://nomad”)

**Comment by DingoEatingFuzz** [comment]
Great find! That header is only used in prod, so it slipped through the cracks in local testing and ui acceptance tests.

The header is indeed relevant and was borrowed from Vault, which appropriately locks down everything.

The important part is `connect-src 'self'` which more or less says the web page should not allow websockets, fetch, or XHRs from any origin other than its own. 

The other half of CORS should still be a-okay:
https://github.com/hashicorp/nomad/blob/master/command/agent/http.go#L41-L45

I'll have a PR once I test this end to end.
