### ISSUE TITLE
[Bug] validate fails to catch underscores

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/nomad#3528]
### Nomad version
0.7.0

### Operating system and Environment details
Windows 10, Ubuntu 16.4

### Issue
if you create a job file and include underscores in the job, group or task, the file will still pass a "nomad validate".  When you push the job, however, the deploy will fail citing illegal characters in the name (only use alphanumeric and -).

validate should be updated to catch this error.

**Comment by schmichael** [comment]
I edited the `example.nomad` job file created by `nomad init` to have underscores and dashes in job, group, and task names without issue:

```
$ nomad status example_number_one
ID            = example_number_one
Name          = example_number_one
Submit Date   = 11/09/17 17:02:06 PST
Type          = service
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
cache       0       0         0        0       1         0
cache_ok    0       0         1        0       0         0

Latest Deployment
ID          = de4cf8d2
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy
cache_ok    1        1       1        0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
52637ee5  4fe2f7ad  cache_ok    1        run      running   1m29s ago  1m14s ago
a480c7fe  4fe2f7ad  cache       0        stop     complete  4m11s ago  1m28s ago
```

Closing for now but please reopen if you can include a reproducer.
