### ISSUE TITLE
[question] Task names in nomad job status

### ISSUE THREAD

**Issue by durbz** [hashicorp/nomad#3547]
I've been testing cluster builds with nomad and have a question regarding showing job statuses via the cli. I've tested the reporting and statuses quite extensively, still not finding what I'm looking for.  I want to the ability to show task names in 'nomad status jobname', or have a method to show a full list of task names with status across a nomad cluster, rather than them grouped. I've been migrating from a compose/swarm cluster, so basically looking for an equivalent, or something similar to 'DOCKER_COMPOSE ps'. 

To note, all the tasks are docker container based.

Thank you!

**Comment by dadgar** [comment]
Hey @durbz,

Its an interesting idea but not something we will be pursuing. Nomad logically groups things into jobs and exposes their allocations for introspection. We will not be adding a command to list all tasks.

It should be fairly easy to use our API pkg to build this for yourself using the rest of our commands as an example! Sorry I couldn't be more helpful.
