### ISSUE TITLE
Please provide an option to restart tasks that are not starting / unhealthy allocations

### ISSUE THREAD

**Issue by mildred** [hashicorp/nomad#3548]
My problem at hand is that I have a job that did not start in time:

```
Recent Events:
Time                   Type             Description
11/13/17 22:19:59 UTC  Started          Task started by client
11/13/17 22:15:24 UTC  Alloc Unhealthy  Task not running by deadline
11/13/17 22:10:24 UTC  Driver           Downloading image wordpress:latest
11/13/17 22:10:24 UTC  Task Setup       Building Task Directory
11/13/17 22:10:24 UTC  Received         Task received by client
```

The [update stanza](https://www.nomadproject.io/docs/job-specification/update.html) for this job looks like:

```hcl
  update {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "5m"
    auto_revert      = false
    canary           = 0
    stagger          = "10s"
  }
```

Here, the job obviously hit the `healthy_deadline` of 5m. The job has no health check configured.

What I would like nomad to do is detect that the task did not start and reschedule the task elsewhere. I believe that this could be done using the [check_restart stanza](https://www.nomadproject.io/docs/job-specification/check_restart.html) except that the check_restart works only when there is associated health checks.

The [restart stanza](https://www.nomadproject.io/docs/job-specification/restart.html) is also featuring an auto_revert option that reverts to the previous job version if a deployment failed. Having the ability to retry the update completely a specified number of times could be helpful as well when auto_revert is false.

In any case, I'd like nomad to retry harder to start the tasks.

**Comment by dadgar** [comment]
@mildred Are you suggesting that when an allocation is detected as unhealthy during a deployment you would like Nomad to kill that allocation and attempt a restart elsewhere?

**Comment by dadgar** [comment]
So the issue I see with regards to what you posted is that `healthy_deadline` begins as the application is downloading artifacts. This can cause a timeout like you hit. I think the update stanza needs to have a `start_deadline` and a `healthy_deadline` to decouple this issue. The `start_deadline` can be defaulted to a much longer duration than the `healthy_deadline`.

**Comment by mildred** [comment]
> @mildred Are you suggesting that when an allocation is detected as unhealthy during a deployment you would like Nomad to kill that allocation and attempt a restart elsewhere?

Either that or when the deployment as a whole is considered failed, retry it (possibly moving allocations elsewhere).

> So the issue I see with regards to what you posted is that healthy_deadline begins as the application is downloading artifacts. This can cause a timeout like you hit. I think the update stanza needs to have a start_deadline and a healthy_deadline to decouple this issue. The start_deadline can be defaulted to a much longer duration than the healthy_deadline.

This can be a solution to avoid having the deployment as failed, yes. But will it really work? When a job is restarted after an update, you might very well have to download artifacts again. If you updated the executable code, you most probably will need to download the code again. So the restart might not be that different from the initial startup.

In the use case I have, I am using the stock wordpress image from the docker hub, and am running it on EC2 instances. Generally, the time spent to download the image is much shorter. Here, the problem might be that the nomad node running the allocation is possibly having an issue. Retrying the allocation seems to be a good option there. (note: I still haven't found what the problem was and I do not have access to the nomad client logs at the moment. But the problem I have is separate from this Github issue)
