### ISSUE TITLE
[ui] [bug] timezone mismatch in allocation display

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/nomad#3552]
### Nomad version
0.7.0

### Issue

On the allocation page, `/ui/allocations/<UUID>`, the times are listed in the local computers time, but printed with the string `UTC` after them.  Logs being displayed in the local timezone sounds ok to me, but it should probably say that :).

**Comment by backspace** [comment]
Thanks for letting us know about this! I believe it was fixed in a034708 and included in 0.7.1.
