### ISSUE TITLE
Env variables when submitting job in docker do funny things

### ISSUE THREAD

**Issue by discobean** [hashicorp/nomad#3553]
Today a dev submitted a job to nomad via the API, and they had environment variables like so:

```
          "Env": {
            "AUTH_TOKEN_PROVIDER_URI": "https://stage-auth.domain.com/v1/yyy",
            "REQUESTS_PER_SECOND": 1,
            "MAX_NUMBER_OF_SECONDS_TO_SEND_REQUESTS": 1,
            "TARGET_URI": "https://mobile-adapter-api-stage.domain.com/v1/xxx",
            "AUTH_TOKEN": "0",
            "HEADERS": "Pragma:no-cache"
          },
```

There were 2 tasks in the job definition, I noticed that the second task disappeared, along with other parts of the job.

The fix was to not use integers in the JSON when submitting to the API - It turns out that having integers in the Env variables, does weird indescribable things.

**Comment by dadgar** [comment]
Can you give a reproducing job and steps. The job shouldn't even be accepted by Nomad. I just ran a job doing what you described and got: 

```
curl -XPUT -d @job.json http://127.0.0.1:4646/v1/jobs
json: cannot unmarshal number into Go value of type string
```

Job: https://gist.github.com/dadgar/fc5e54e19b1d9d2d910b508139a0ab57

I am going to close this until we get reproduction steps.
