### ISSUE TITLE
API: Allow retrieving job spec by version.

### ISSUE THREAD

**Issue by rayward** [hashicorp/nomad#3573]
The API allows the current job spec to be read at `/v1/job/:job_id`. The API also allows _all_ versions of the job spec to be retrieved at `/v1/job/:job_id/versions`, however this could potentially contain hundreds of versions resulting in a very large response.

It would be preferable if I could query for a specific version like so `/v1/job/:job_id?version=:version`.

**Comment by dadgar** [comment]
For what it is worth there will only be 10 versions at max

**Comment by mikenomitch** [comment]
Hi, since there will only be 10 versions max, I think querying for everything and then filtering after the request should solve this issue for most/all use cases. Going to close this out as I don't think the payoff is that great compared to other stuff we could work on.
