### ISSUE TITLE
artifact downloads an empty folder

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/nomad#3579]
Nomad 0.7.0

Attempting to use the artifact stanza to download all files in a specific sub-folder of a git repo.  downloading and trying to run go-getter directly seems to succeed:

```
go-getter git::https://myurl.io/myorg/project.git//files /apps/myapp
```
this results in all the desired files being copied to the appropriate location.  It should be known,  I did download the latest go-getter and compile in order to test it out.  However this being placed in my task in nomad:

```
artifact {
  source = "git::https://myurl.io/myorg/project.git//files"
  destination = "/apps/myapp"
}
```
This ends up creating the target folder, but it's completely empty of any content.  It should be noted I can duplicate this behavior if I omit "git::" using go-getter as it will not correctly detect that the source is a git repo, so I'm suspicious of that variable not passing through nomad properly.

Any tips on logs I can review to make sure I'm not missing something or can we confirm this is a bug?

**Comment by chelseakomlo** [comment]
Hi, thanks for the bug report. Logs here would be helpful, you can either send the logs from the client that this job has run on, or you can set up a agent in dev node to test this: https://www.nomadproject.io/intro/getting-started/running.html#starting-the-agent.
 
Is this repository private? See our documentation for how to fetch from a private repo: https://www.nomadproject.io/docs/job-specification/artifact.html#download-using-git

**Comment by Justin-DynamicD** [comment]
I'm going to review starting things in dev mode to get some better testing but to answer your 2nd question:

The repo itself is public, but it _is_ a "private" GitHub Enterprise server (as in self-hosted with no internet access).   Ill read through both links and perform some tests.

**Comment by Justin-DynamicD** [comment]
I'm having issues running nomad and getting any logs output.  As soon a I add -dev to my command, nomad starts but I'm completely unable to connect to the UI or submit a job.  Looks like this is a bigger dive than anticipated

**Comment by Justin-DynamicD** [comment]
So I finally got nomad running in "dev" mode, but I don't see any logs that reflect artifact copying at all.

As the debug info scrolls by on the screen, I don't see any copy step being performed at all.  I'm running in a VM so screen capture is a bit rough, but there's no mention of "artifact" or "wget" or "download" or ... anything.  It looks like the empty directory is from the docker driver simply creating the directory as it's missing and the artifact is getting completely skipped.

Perhaps my placement is bad?  It belongs in the task, correct?

**Comment by Justin-DynamicD** [comment]
Update:  I decided to do a simple find . -iname for the files and they are found in what appears to be a relative directory?

they exist in "./opt/nomad/data/alloc/<processid>/<task-name>/<actual path/file specified>"

I thought leading with "/" made it an absolute path?  Looks like I need o play with the syntax more...

**Comment by Justin-DynamicD** [comment]
Final thoughts:  it appears that regardless of syntax, Nomad _always_ uses the relative path for downloading an artifact, but when mounting a volume you can use either relative or absolute.  This feels inconsistent to me if it's intended, but I'm not certain if it is.

**Comment by chelseakomlo** [comment]
Thanks for the investigation and final update! That is a good point, we will discuss internally about the user experience of this. 

Let us know if there is anything else we can help with.

**Comment by rms1000watt** [comment]
Would you guys be able to run input validation on `artifact.destination` where if the string starts with a `/` then fail validation?

For example `/apps/myapp` would fail in @Justin-DynamicD original artifact. 

From a user experience perspective, the docker config in the nomad task only works when the volume mount is relative: 
```
apps/myapp:/etc/myapp
```

So, it would be misleading to new users if the `artifact.destination` has an absolute path but the docker driver `config.volume` mount only worked with the relative path.
