### ISSUE TITLE
raw_exec user.blacklist is not enforced unless the user is specified in the job spec

### ISSUE THREAD

**Issue by latitude37s** [hashicorp/nomad#3582]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core) 
nomad runs as root

### Issue
The exec driver runs tasks like this:
```golang
	execCmd := &executor.ExecCommand{
		Cmd:            command,
		Args:           driverConfig.Args,
		FSIsolation:    true,
		ResourceLimits: true,
		User:           getExecutorUser(task),
	}
```
Whereas the raw_exec driver runs tasks like this:
```golang
	execCmd := &executor.ExecCommand{
		Cmd:  command,
		Args: driverConfig.Args,
		User: task.User,
	}
```

getExecutorUser ensures that if the user is not set in the job specification, DefaultUnpriviledgedUser runs the job, which is set to "nobody".  However for raw_exec does not do the same. If the user is not set, this means the job runs as the same user that Nomad is running as. In our case, we run Nomad as root, and we blacklist root. However simply by omitting the "user" from the job spec file, it is possible for Nomad users to run jobs as root. This completely circumvents the user.blcklist. I suggest using getExecutorUser(task) for both exec and raw_exec.

### Reproduction steps
Using the following client config:
```HCL
client {
  options = {
    "driver.raw_exec.enable" = "1"
    "driver.whitelist" = "raw_exec"
    "user.checked_drivers" = "raw_exec"
    "user.blacklist" = "root"
  }
}
```

And a very simple job spec. e.g.
```HCL
  task "sleep" {
    driver = "raw_exec"
    user = "root"

    config {
      command = "/usr/bin/sleep"
      args    = ["60"]
    }
  }
```

Versus:
```HCL
  task "sleep" {
    driver = "raw_exec"

    config {
      command = "/usr/bin/sleep"
      args    = ["60"]
    }
  }
```

If we specify user = "root" the task is not permitted to run, as expected. However, if we omit the user, the task is allowed to run as root.

**Comment by latitude37s** [comment]
So if I understand correctly, when we hit this piece of code, the r.task.User is empty, which means that we don't match against anything in the blacklist.

```golang
	// Validate the user.
	unallowedUsers := r.config.ReadStringListToMapDefault("user.blacklist", config.DefaultUserBlacklist)
	checkDrivers := r.config.ReadStringListToMapDefault("user.checked_drivers", config.DefaultUserCheckedDrivers)
	if _, driverMatch := checkDrivers[r.task.Driver]; driverMatch {
		if _, unallowed := unallowedUsers[r.task.User]; unallowed {
			mErr.Errors = append(mErr.Errors, fmt.Errorf("running as user %q is disallowed", r.task.User))
		}
	}
```

Then when we go to run the task it will skip the runAs part and run as the same user as nomad.

```golang
	// setting the user of the process
	if command.User != "" {
		e.logger.Printf("[DEBUG] executor: running command as %s", command.User)
		if err := e.runAs(command.User); err != nil {
			return nil, err
		}
	}
```

**Comment by latitude37s** [comment]
A workaround is to add the empty user to the blacklist. i.e.
"user.blacklist" = ",root"

The message / reason is then:
running as user "" is disallowed

**Comment by chelseakomlo** [comment]
Good catch, thanks for letting us know about this, and for the detailed analysis. We will discuss this internally and look at a fix.
