### ISSUE TITLE
execute command inside allocation / job

### ISSUE THREAD

**Issue by alxark** [hashicorp/nomad#3588]
Hello. Currently there is no method to run command (for example execute tests) on allocation in cluster. When i want to run tests inside container i need to find host where it is located, run ssh to connect, find container name and execute command. I think it will be easier to run something like:

```
nomad execute somejob/groupname/taskname "/bin/tests.sh"
```

or 
```
nomad execute allocation/taskname "/bin/tests.sh"
```
to run tests. Also i think there should be some kind of option to specify if this task allow any executions( for example you might want to prevent external access for some tasks).

Also if there will be any interactive mode via API you will be able to implement online container access (something like javascript console).

**Comment by chelseakomlo** [comment]
Hi, thanks for the feature request. We have this feature planned in Nomad's future roadmap.

**Comment by pchernik** [comment]
Any updates on when this feature might be planned / implemented? This is one area in which Nomad lags behind Kubernetes....

**Comment by schmichael** [comment]
While it won't be in 0.9.0, [code is already being written](https://github.com/hashicorp/nomad/commits/f-nomad-exec) and is already in a working state! So without promising a specific timeline, it's safe to say we hope to deliver this feature soon.

**Comment by pchernik** [comment]
Thank you!

**Comment by adison88** [comment]
is this implemented?

**Comment by tgross** [comment]
Yes! This was implemented as [`nomad alloc exec`](https://nomadproject.io/docs/commands/alloc/exec/). Thanks for pointing out this issue was left open @adison88!
