### ISSUE TITLE
[feature] job lifetime limit

### ISSUE THREAD

**Issue by alxark** [hashicorp/nomad#3594]
Hello. I would like to specify job lifetime limit. This feature will be useful for testing environments, when i don't want to track started jobs after successful merge and want them to die after some timeout ( for example 1 week after last modification time). Currently i would like to use this feature with KVM driver to create fresh VM's with small nomad cluster inside it.

**Comment by chelseakomlo** [comment]
Hi, thanks for the feature request. Have you looked at the `kill_timeout` specification? See here for docs: https://www.nomadproject.io/docs/operating-a-job/update-strategies/handling-signals.html

**Comment by alxark** [comment]
It's not the same. kill_timeout is used to stop tasks, but i think there should be job lifetime. After specified lifetime this job should be stopped and cleared from cluster.

**Comment by shantanugadgil** [comment]
HI @alxark 
I think what you are looking for is a "wall time" limit for a job. (Probably similar to classic HPC schedulers).

There have been some issues opened in the past discussing those, though I don't remember the issue numbers off hand.

HTH,
Shantanu

**Comment by alxark** [comment]
It would be great if someone can post links here, because i didn't found them.

**Comment by schmichael** [comment]
@alxark Sorry about that. I think this is the original one to follow for updates: https://github.com/hashicorp/nomad/issues/1782

Closing this one as a duplicate.
