### ISSUE TITLE
Port 0 registered in consul with address_mode="driver"

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#3599]
I'm setting address_mode="driver", and this seems to work as far as registering the correct IP with consul, but what's going on with the port?

I've been going through the documentation regarding ports but when it comes to address_mode=driver it is unclear.

Is there anyway to register a port with Consul using driver address_mode?

**Comment by chelseakomlo** [comment]
Hi, thanks for letting us know about this issue. What specific drivers are enabled on the Nomad client? See here for more information about address_mode: https://www.nomadproject.io/docs/job-specification/service.html#address_mode

If you wouldn't mind posting the version of Nomad you are using and any relevant logs, those would be helpful as well.

**Comment by perbly** [comment]
I can answer for Rickard (same company)

We use address_mode = docker
Nomad version 0.7.0

With the following hcl config:
`
        service {
          name = "ibiza-service"
          port = "svc"
          address_mode = "driver"
        }
      driver = "docker"
      config {
        port_map {
          svc = 8080
        }
      }
      network_mode = "macvlan"
      resources {
        cpu    = "200"
        memory = "768"
        network {
          mbits = 32
          port "svc" {}
        }
      }
`

nomad alloc-status xxxx shows this output

`
Task "ibiza-service" is "running"
Task Resources
CPU             Memory                 Disk         IOPS  Addresses
2/200 MHz  486 MiB/768 MiB  300 MiB  0        svc: dockerhostip:22174
`
And in consul the container is registred like this:

`containerip:8080`

--







Without any port information config like this:
`
        service {
          name = "ibiza-service"
          address_mode = "driver"
        }
      driver = "docker"
      config {
      }
      network_mode = "macvlan"
      resources {
        cpu    = "200"
        memory = "768"
        network {
          mbits = 32
        }
      }
`

nomad alloc-status xxxx shows this output (addresses is empty):

`
Task "ibiza-service" is "running"
Task Resources
CPU              Memory                 Disk         IOPS  Addresses
2/200 MHz  486 MiB/768 MiB  300 MiB  0         
`
And in consul the container is registred like this:
`containerip:0`







Regards
Per Bly
SRE TUI-Nordic

**Comment by rickardrosen** [comment]
@chelseakomlo as Per states above, if we just use driver address mode, nomad registers the service with port 0.

Adding a dynamic port mapping to the nomad job, will register the port with consul, but also allocate this port on the host interface.

**Comment by schmichael** [comment]
This is another aspect of #3380, and I'll be working on addressing both before our upcoming 0.7.1 release.

**Comment by schmichael** [comment]
This should be fixed in 0.7.1! Sorry for the delayed update. Please reopen if not.
