### ISSUE TITLE
Syslog server missing error checking on too long output lines (>64kb)

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/nomad#3605]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
Ubuntu 14.04.5 LTS

### Issue
https://github.com/hashicorp/nomad/blob/master/client/driver/logging/syslog_server.go#L75
```go
func (s *SyslogServer) read(connection net.Conn) {
	defer connection.Close()
	scanner := bufio.NewScanner(bufio.NewReader(connection))

	for {
		select {
		case <-s.doneCh:
			return
		default:
		}
		if scanner.Scan() {
			b := scanner.Bytes()
			msg := s.parser.Parse(b)
			s.messages <- msg
		} else {
			return
		}
	}
}
```
Function read calls scanner.Scan() which, from the docs
```
// Scan advances the Scanner to the next token, which will then be
// available through the Bytes or Text method. It returns false when the
// scan stops, either by reaching the end of the input or an error.
```
but the Err() method is never called to check the error, causing Nomad to silently fail and splitting the output in two lines. Possible fix:
```go
if scanner.Scan() {
			b := scanner.Bytes()
			msg := s.parser.Parse(b)
			s.messages <- msg
		} else {
			if err := scanner.Err(); err != nil && err != io.EOF {
			    s.logger.Printf("[ERR] logcollector.server: %v", err)
                        }
			return
		}
```

### Reproduction steps
Log a line longer than 64K.

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

### Job file (if appropriate)
N/A

**Comment by chelseakomlo** [comment]
Thanks for submitting this issue and ideas for a fix. We will discuss this as a team and look at a fix after we finish our current release.

**Comment by notnoop** [comment]
Thank you so much for reporting this bug and sorry for the slow response.  Nomad 0.9 moved away from using syslog server to using docker api directly for collecting container logs.  The new approach handles long lines properly.   Closing this ticket as it's no longer relevant.
