### ISSUE TITLE
[question] Populating consul k/v store from job specification

### ISSUE THREAD

**Issue by jackjacek** [hashicorp/nomad#3609]
I would like to insert runtime variables related to job into consul as key/value pairs. IE store key `task_name/port/label` with value corresponding to `${NOMAD_PORT_label}`. 

Is it possible, or is there any tooling available to achieve that?

**Comment by schmichael** [comment]
Right now Nomad can only populate service (and associated health checks) in Consul. We don't have any current plans for adding generic k/v support, so you'll have to do this from your application (or a wrapper script). Hope that helps!
