### ISSUE TITLE
Typo in metrics names

### ISSUE THREAD

**Issue by jens-solarisbank** [hashicorp/nomad#3610]
### Nomad version
Current master branch

### Issue
Several metric names have typos:
```
check_regisrations
check_deregisrations
service_regisrations
service_deregisrations
```
Those should probably be named _regis_t_rations

### Reproduction steps
```
curl localhost:4646/v1/metrics?format=prometheus |grep regisrations
```

**Comment by chelseakomlo** [comment]
Closing due to merge of #3611
