### ISSUE TITLE
[New driver] Add support for Singularity as a Nomad Driver

### ISSUE THREAD

**Issue by ArangoGutierrez** [hashicorp/nomad#3613]
[Singularity](http://singularity.lbl.gov/) A container platform focused on supporting "Mobility of Compute".

Mobility of Compute encapsulates the development to compute model where developers can work in an environment of their choosing and creation and when the developer needs additional compute resources, this environment can easily be copied and executed on other platforms. Additionally as the primary use case for Singularity is targeted towards computational portability, many of the barriers to entry of other container solutions do not apply to Singularity making it an ideal solution for users (both computational and non-computational) and HPC centers.

After running [Singularity-on-Nomad](https://github.com/ArangoGutierrez/Singularity-on-Nomad) with the exec driver, I set up some work to build a custom driver for nomad. Here I present a driver for singularity:
 - [Singularity-Driver](https://github.com/ArangoGutierrez/nomad/blob/master/client/driver/singularity.go)

**Comment by chelseakomlo** [comment]
Hi, thanks for your work in adding this. See related issue on adding first-class support in Nomad for more drivers in the near term: https://github.com/hashicorp/nomad/issues/3463

After we enable pluggable drivers, it will be great to see the Nomad community building drivers for alternative platforms such as Singularity. Please stay tuned!
