### ISSUE TITLE
Nomad doesn't respect Consuls "translate_wan_addrs"

### ISSUE THREAD

**Issue by perrymanuk** [hashicorp/nomad#3629]
### Nomad version
Output from `0.7.0`

### Operating system and Environment details
Debian 9
### Issue
Consul is configured to translate wan addresses, this works perfectly for the nomad nodes and for services announced directly to consul. However the same is not true for the services announced to consul by nomad.
### Reproduction steps
ping nomad-node-name.service.datacenter.consul
ping service-running-in-nomad.service.datacenter.consul

**Comment by perrymanuk** [comment]
This is also true for vault, would you like me to duplicate the issue there?

**Comment by schmichael** [comment]
@perrymanuk If you don't mind. Please drop a link from one to other as well.

**Comment by JoeOrtiz** [comment]
I see this as well from Nomad v0.8.6.
