### ISSUE TITLE
artifact source interpolation inconsistent/incomplete

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#3634]
### Nomad version

    Nomad v0.7.0

### Operating system and Environment details

macOS 10.13.1

### Issue

Interpolation of the `source` parameter in an `artifact` block is inconsistent or incomplete.  `${attr.kernel.name}` works as expected.  `${meta.custom_key}` does not expand, but `${NOMAD_META_custom_key}` does.

### Reproduction steps

1. run the below job file
1. `nomad alloc-status <alloc-id>` will contain something like the following:  
            `failed to download artifact "github.com/hashicorp/go-getter?ref=${meta.ref}": error downloading 'https://github.com/hashicorp/go-getter.git?ref=%24%7Bmeta.ref%7D': /usr/local/bin/git exited with 1: error: pathspec '${meta.ref}' did not match any file(s) known to git.`

Replacing `${meta.ref}` with `${NOMAD_META_ref}` works as intended.

### Job file

```hcl
job "tester" {
    datacenters = ["dc1"]

    type = "batch"

    group "tester" {
        task "tester" {
            driver = "raw_exec"
            config {
                command = "/bin/bash"
                args = [
                    "-c", "cd local/work && git describe --always --dirty",
                ]
            }

            meta {
                ref = "1bbfcd501e97764778020d509ed1f803652de33b"
            }

            artifact {
                mode = "dir"
                source = "github.com/hashicorp/go-getter?ref=${meta.ref}"
                destination = "local/work"
            }
        }
    }
}
```

**Comment by preetapan** [comment]
hi @blalor  - This is expected behavior according to the [docs](https://www.nomadproject.io/docs/runtime/interpolation.html). ${meta.<key>} is used to interpolate node metadata values, and ${NOMAD_META}.<key> is used to interpolate task metadata values. The `ref` attribute above is a task metadata property. 

I can see how this can be confusing because they are very similar concepts though. 

Hope this helps.

**Comment by blalor** [comment]
Hrm.  I don't find the docs themselves clarifying for this issue, but your comment does help.  I think it would be useful to call out the distinction between metadata defined at the node and metadata defined at the task in the docs.  It wasn't until reading your comment that I was aware there was a distinction. 🙂

**Comment by preetapan** [comment]
That's good feedback, we'll make a docs a bit clearer on this, thanks.
