### ISSUE TITLE
Automatic deployment promotion of  canary updates

### ISSUE THREAD

**Issue by mildred** [hashicorp/nomad#3636]
Canary updates are nice, but it would be nicer if it was possible to automatically declare the deployment successful when checks succeeds.

A similar question has been asked in https://github.com/hashicorp/nomad/issues/2873. here the person wanted to ensure that updating a job would create a new allocation before stopping the old one. This is quite a similar feature request.

Would it be possible of thinking about having this kind of feature?

Thanks :)

**Comment by jrasell** [comment]
@mildred until this feature potentially makes it into Nomad core; [Levant](https://github.com/jrasell/levant) may be of help to you.

**Comment by jvrplmlmn** [comment]
@dadgar sorry for the ping, but is this planned somewhere in the roadmap? 😄
