### ISSUE TITLE
Unable to mount volume using nomad plugins in jenkins

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#3641]
## Nomad version
Output from `nomad version`
Nomad v0.7.0
### Operating system and Environment details
Centos 7.3.161
### Issue
unable to mount host volume using nomad plugin in Jenkins.
when we are trying to integrate volume using nomad jenkins plugin it gives error
Logs.
###nomad status jenkins-ac678c481bb7b
ID            = jenkins-ac678c481bb7b
Name          = jenkins-ac678c481bb7b
Submit Date   = 12/11/17 06:48:17 UTC
Type          = batch
Priority      = 50
Datacenters   = nomad
Status        = dead (stopped)
Periodic      = false
Parameterized = false

Summary
Task Group               Queued  Starting  Running  Failed  Complete  Lost
jenkins-slave-taskgroup  0       0         0        1       0         0

Allocations
ID        Node ID   Task Group               Version  Desired  Status  Created At
188ae7b2  c39f87fd  jenkins-slave-taskgroup  0        run      failed  12/11/17 06:48:17 UTC

###nomad alloc-status a7b56a9c
 12/11/17 06:47:22 UTC  Not Restarting         Policy allows no restarts
12/11/17 06:47:22 UTC  Terminated             Exit Code: 2, Exit Message: "Docker container exited with non-zero exit code: 2"
And container won't start to build the plan via jenkins.

Adding slave template configuration.
![template](https://user-images.githubusercontent.com/15324013/33819547-124acd56-de71-11e7-9da3-ffa7f257c2eb.PNG)

**Comment by schmichael** [comment]
I believe this is a bug with [jenkinsci/nomad-plugin][https://github.com/jenkinsci/nomad-plugin], not nomad itself. This pull request may be relevant, but I'm not sure why it isn't merged: https://github.com/jenkinsci/nomad-plugin/pull/23

If you think it is a Nomad bug, please post the job file the plugin creates and reopen the issue.

```
nomad inspect jenkins-ac678c481bb7b
```
