### ISSUE TITLE
[improvement] Please provide option to tune container's pids limit

### ISSUE THREAD

**Issue by nab054371** [hashicorp/nomad#3668]
Is it possible to please include an option to include _--**pids-limit**_ option with docker driver? This is to prevent  fork bomb inside the docker container. Wuold be good to please include key security options like _**--cap-drop=ALL**_ and _**--pids-limit**_.

**Comment by chelseakomlo** [comment]
Hi, thanks for the feature request. This seems like a reasonable thing to do with all supported drivers. We will review this internally. 

Do you have an example of when this has been an issue? I'm curious about the context that led to this issue being opened.

**Comment by nab054371** [comment]
So most organizations that are serious about docker security would prescribe the inclusion of these options when running docker containers.  I have worked with several clients, where their security team has insisted on using them.

**Comment by schmichael** [comment]
Crosslinking #738 as its the first mention of caps

**Comment by tgross** [comment]
Doing some issue cleanup and this currently exists in Nomad as of https://github.com/hashicorp/nomad/pull/11526 which shipped in Nomad 1.2.4. It can be set on both the client and the task. See [`pids_limit`](https://www.nomadproject.io/docs/drivers/docker#pids_limit) docs.
