### ISSUE TITLE
Improve documentation for setting up a server cluster and keeping it healthy

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#367]
I am trying to launch a 2-server cluster.  Server 2 joins Server 1 successfully through a `server-join`.  I was hoping to query the node-status of the cluster; however, I received this error: `Error querying node status: Unexpected response code: 500 (No cluster leader)`.

After looking in the logs, I found that only 1 vote was tallied for leader and another error occurred during the election process: `2015/10/30 15:53:52 [ERR] raft: Failed to make RequestVote RPC to 172.24.93.91:4647: dial tcp 172.24.93.91:4647: getsockopt: no route to host`.

The bad part is that 172.24.93.91 doesn't exist.

```
core@ip-172-24-11-165 ~ $ nomad server-members -address=http://172.24.11.165:4646
Name                                     Addr            Port  Status  Proto  Build  DC   Region
ip-172-24-11-165.service.consul.global   172.24.11.165   4648  alive   2      0.1.2  dc1  global
ip-172-24-146-163.service.consul.global  172.24.146.163  4648  failed  2      0.1.2  dc1  global
ip-172-24-90-79.service.consul.global    172.24.90.79    4648  failed  2      0.1.2  dc1  global
ip-172-24-63-8.service.consul.global     172.24.63.8     4648  failed  2      0.1.2  dc1  global
ip-172-24-138-213.service.consul.global  172.24.138.213  4648  alive   2      0.1.2  dc1  global
```

---

We should improve our documentation for setting up and maintaining a cluster. Having a cluster in a stuck state as a result of quorum loss is very confusing and hard to fix.

@cbednarski

Closes https://github.com/hashicorp/nomad/issues/80
Related to: https://github.com/hashicorp/nomad/issues/273
Related to: https://github.com/hashicorp/nomad/issues/304

**Comment by cbednarski** [comment]
@BSick7 Thanks for the report. Membership is very sticky. Once an entry has been made into the raft log identifying a node, Nomad will try to reestablish communications with that node for quite a while (IIRC 36 hours).

- Did you at some point attempt to join 172.24.93.91 to the cluster by way of CLI command or config file?
- Did you previously have 172.24.93.91 in your cluster and removed it?
- Do any of the machines in your cluster have state on disk from an old cluster? E.g. Maybe you reused a machine that was previously part of another cluster?
- Did you copy Nomad state from one machine to another?

If you are playing around with things you will want to make sure you wipe out the nomad state on disk before forming a new cluster. If you're running a prod cluster you can use [server-force-leave](https://nomadproject.io/docs/commands/server-force-leave.html) to eject failed nodes.

**Comment by BSick7** [comment]
@cbednarski I am using terraform to provision this cluster.  The list of servers in the description are the only servers that connected.  (You can actually see 3 of them are in the failed state because terraform tore down the other servers)  There could have been a client with that IP address that I'm not aware.

I have been following the immutable infrastructure philosophy, so I do not transfer or modify state ever.

If a client node was at 172.24.93.91, would the server request a client to vote on a leader?

**Comment by cbednarski** [comment]
> If a client node was at 172.24.93.91, would the server request a client to vote on a leader?

This should only happen amongst the server nodes. The client nodes aren't part of the raft group.

**Comment by cbednarski** [comment]
> On a side note, this main server wasn't torn down. I only modified (in terraform) this secondary server peer.

My guess is that there is some stale state in your main server's raft log that is polluting the rest of the server nodes, so at some point in the past 172.24.93.91 _was_ a member of the cluster and the node that remembers it is asking it to vote, or another node that has replicated the log is asking it to vote.

Likely if you have not succeeded in forming a quorum then your main server is the defacto leader because its raft log has the highest index, and it is asking an old peer to confirm this. Since none of the new peers knows about any of this history they can't confirm the leader and thus will not replicate the log.

My guess is that you added / remove servers without quorum (so the changes in membership could not be committed to the raft log) and now your cluster is in a stuck state because it cannot elect a leader. To fix this you will have to bring back one of the old peers or wipe out the state and start over. It's infeasible to edit the raft log by hand.

If you need to recover data from the API you might be able to do so by setting the cluster size on your main server to 1 and restarting the agent.

Also note that 2 peers can form a quorum in a cluster size of 3, but 1 node cannot form a quorum in a cluster size of 2. If you want to run in a highly available configuration we recommend 3 or 5 nodes. Those clusters can tolerate the loss of 1 or 2 nodes respectively.

**Comment by BSick7** [comment]
@cbednarski Thanks for the info.  I have been struggling to form a proper server quorum.  You guys are killing it and very early in the development cycle, but I would love to see some instructions creating the recommended 3 or 5 server cluster.  We buy into the hashicorp ecosystem so anything tailored for terraform would be very helpful.

**Comment by cbednarski** [comment]
> I would love to see some instructions creating the recommended 3 or 5 server cluster. 

This is pretty complicated under the hood, but from an operator perspective it should be relatively straightforward:

1. Boot three fresh nodes, A, B, and C
2. Join node B to node A
3. Join node C to node A

These three nodes should perform leader election (I think if you watch the logs on all three you can see this happen). I've [done this with Consul](https://github.com/trydb/tryconsul) and it's pretty fun to watch. :)

Once the leader is elected you're all set! From that point forward, **you need to make sure you never lose more than one node at a time**. If you need to tolerate more losses, you'll need a larger cluster size.

If you take a look at the Deployment Table at the bottom of our [Consensus Protocol Internals](https://nomadproject.io/docs/internals/consensus.html) page you'll get an idea about how many you need.

**Comment by BSick7** [comment]
Step 3 is very helpful as it seems counter to a point made https://nomadproject.io/docs/commands/server-join.html.  

> The server-join command joins the local server to one or more Nomad servers. Joining is only required for server nodes, and only needs to succeed against one or more of the provided addresses. **Once joined, the gossip layer will handle discovery of the other server nodes in the cluster.**

**Comment by schmichael** [comment]
I'm going to close this as we have a [guide on server outages](https://www.nomadproject.io/guides/outage.html) as well as a number of related open and closed issues that cover this topic as well. Thanks for the report!
