### ISSUE TITLE
Nomad offical docker image

### ISSUE THREAD

**Issue by mnuic** [hashicorp/nomad#3676]
Hi,

Is there a chance we can get an offical hashicorp Nomad docker image on DockerHub? The same as Consul has.

Thanks

**Comment by alxark** [comment]
we have asked before and official position is  "no", because nomad uses a lot of system stuff and they can't guarantee work inside docker container.

**Comment by mnuic** [comment]
OK, I see the point. But, it's not the reason for not to have an offical image like Consul has. I mean, it's all hashicorps products.

**Comment by jippi** [comment]
if it's not a recommended/supported way to run Nomad, then it make good sense not to have.

You can just dump the nomad binary in a docker image and use it if you need it? :)

**Comment by mnuic** [comment]
Yes, I know, we are using it that way.

Anyway, thanks for the answers.

**Comment by chelseakomlo** [comment]
Thanks to everyone for the answers- yes, we don't recommend running Nomad running in a Docker container, it isn't something we officially support/test against.
