### ISSUE TITLE
CLI: Add Address and Build to node-status

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/nomad#3678]
I find that I have to do several cross references with other systems to find the IP address and nomad version number when draining and/or upgrading worker nodes.

If the node-status CLI command returned the node address and nomad version number similar to `nomad server-members`, no cross-referencing would be needed and we could simplify our internal playbooks for upgrading nodes.

**Comment by chelseakomlo** [comment]
Thanks for the feature request. We can add the IP address under `--verbose` mode- the version is already emitted under verbose.
