### ISSUE TITLE
Need way to submit job without changing the group count

### ISSUE THREAD

**Issue by potato20** [hashicorp/nomad#3688]
It would be great if we're submitting a job via `nomad run` to be able to keep the `count` of a group the same without having to re-specify it. I imagine that it would be something like you submit `-1` for `count` and it would just keep the previous `count` value.

This would be useful in cases where one would modify the count via a GUI like https://github.com/jippi/hashi-ui , but then submit jobs via the command line.

**Comment by alxark** [comment]
looks like duplicate of my #3243

**Comment by potato20** [comment]
ah yes its, thanks @alxark . good to know other people want this feature as well.
