### ISSUE TITLE
[UI] net::ERR_BLOCKED_BY_CLIENT when ui scheme differs from api scheme

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#3689]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Issue
Browser attemps to connect directly to a nomad client in order to get allocation stats (nomad-client:4646/v1/client/allocation/xxx/stats ) on some pages in UI.
But browser fails to do it in case when nomad client uses another scheme than UI.
If web UI is reachable on **http** it will fail to access nomad stats if it was configured to use **https**.
And if web UI is reachable on **https** it will fail to access nomad stats if it was configured to use **http**.

### Reproduction steps
Check values in `CPU` and `Memory` colums for any clients on https://demo.nomadproject.io/ui/clients

![nomad-ui](https://user-images.githubusercontent.com/14976219/34365890-547e2196-eaa6-11e7-90cf-e8d2590525b6.png)

**Comment by schmichael** [comment]
Thanks for the report @pznamensky! While supported, mixed environments (where some clients are HTTP and some are HTTPS) are unusual, so hopefully no end users are affected. The demo site will be upgraded to full HTTPS and future versions of Nomad will proxy most client requests through servers to further mitigate this issue.

Definitely still a bug we intend on fixing though!

**Comment by pznamensky** [comment]
Works fine in 0.8.3.
Thanks.
