### ISSUE TITLE
QUESTION: confusing documentation

### ISSUE THREAD

**Issue by k1ng87** [hashicorp/nomad#3696]
I see doc on the job spec here:
https://www.nomadproject.io/docs/job-specification/index.html

and in it, it has this:
```# This declares a job named "docs". There can be exactly one
# job declaration per job file.
job "docs" {
  # Specify this job should run in the region named "us". Regions
  # are defined by the Nomad servers' configuration.
  region = "us"

  # Spread the tasks in this job between us-west-1 and us-east-1.
  datacenters = ["us-west-1", "us-east-1"]
```

From my understanding, you shouldn't architect nomad clusters across regions, right? If so, why the `datacenters = ["us-west-1", "us-east-1"]`, am I missing something or misreading this?

**Comment by schmichael** [comment]
> From my understanding, you shouldn't architect nomad clusters across regions, right?

You shouldn't run the Nomad _servers_ in a cluster across the Internet (generally) as they require low latency (sub-10ms ideally). The Nomad client nodes in a cluster -- the nodes that actually run jobs -- have much looser latency requirements, so they may be connected over the Internet (via VPN or TLS) to the servers.

So the example you posted from the docs attempts to illustrate how a job can be eligible for running in two geographically distributed datacenters. One of those datacenters will likely have all of the servers (hopefully each server running in a distinct availability zone within that datacenter).

This documentation should explain the different network latency requirements for servers and clients:
https://www.nomadproject.io/guides/cluster/requirements.html#network-topology

This documentation should help explain regions and datacenters: https://www.nomadproject.io/docs/internals/architecture.html#high-level-overview

And finally to federate multiple regions -- each of which has its own cluster of servers -- see:
https://www.nomadproject.io/guides/cluster/federation.html

I hope that answers your question! If not feel free to reopen and/or comment!
