### ISSUE TITLE
Job Promote CLI documentation example missing -group option

### ISSUE THREAD

**Issue by aantono** [hashicorp/nomad#3699]
In the https://www.nomadproject.io/docs/commands/job/promote.html#examples, the second example showing **Promote canaries in a particular group:** has the following command
```
# Promote only the cache canaries
$ nomad job promote example
```

I believe that the intended example should be with using `-group cache` option like this:
```
# Promote only the cache canaries
$ nomad job promote -group=cache example
```

**Comment by schmichael** [comment]
Looks like you're right! See #3712
