### ISSUE TITLE
[improvement] globally set timezone for docker 

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#3700]
As I know, docker provides 2 ways to set timezone for the container:
1. docker run -v /etc/timezone:/etc/timezone:ro
2. docker run -e "TZ=timezone_here"

It's possible to do it in nomad in jobs specs. But in practice you should to it for every job.
Would be great to be able to set flag in nomad which will inherit host's timezone for all docker jobs.

**Comment by lumu-extra** [comment]
+1

**Comment by mikenomitch** [comment]
After some reflection, I'm going to close this one out. Setting a global value to inherit from in the Docker config would be a new pattern, and it'd be a lot of work to establish this pattern just for this timezone fix.

I think templating your jobs (with something like Nomad Pack or Levant) is a way to get around this issue, but the workaround as it stands isn't too bad.
