### ISSUE TITLE
Completed allocations aren't removed by the garbage collector, It causes network saturation on prod.

### ISSUE THREAD

**Issue by jdxlabs** [hashicorp/nomad#3707]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Linux 3.16.0-4-amd64 - Debian 8.10 x86_64

### Issue
Allocations aren't removed from the configuration, even if I stop the jobs.
I need to fix this problem because I work with hundreds of workers on a production environment, and the network is saturated because a lot of information is transferred between clients and servers, the leader master is the most impacted.
The cluster is still in construction, and for example, for now the leader master works with an upload rate of 10Mb/s in continue, to handle ~40 running allocations, and ~1000 completed allocations that I don't want to handle anymore.

### Reproduction steps
I suggest to reproduce this behavior on a local environment.

##### Create this file "job.hcl"
```
job "test-batch" {
  datacenters = ["dc1"]
  type = "batch"

  group "test-group" {
    count = 3
    task "test-batch-task" {
      driver = "docker"
      config {
        image = "redis"
      }
      resources {
        cpu    = 200 # MHz
        memory = 200 # MB
        network {
          mbits = 10
          port "web" {}
        }
      }
    }
  }
}
```
##### Create this config file "nomad.conf" (aggressive about garbage collection)
```
datacenter = "dc1"

client {
  enabled = true
  gc_interval = "1m"
  gc_disk_usage_threshold = 10
  gc_inode_usage_threshold = 10
  gc_max_allocs = 3
  gc_parallel_destroys = 2
}
```

##### Commands
```
consul agent -dev
nomad agent -dev -config=nomad.conf
nomad run job.hcl
nomad stop test-batch
nomad run job.hcl
```

The nb of running allocations is 3 with this command : 
```
nomad agent-info | grep alloc
```

But the nb of allocation is 6, with the completed status included :
```
curl -s -XGET http://127.0.0.1:4646/v1/allocations | python -mjson.tool | jq length
```

And the completed allocations are never removed, even if I trigger the garbage collector : 
```
curl -XPUT http://127.0.0.1:4646/v1/system/gc
```

I also tried to play with configuration (agent, job, api calls), but it doesn't help.

Thanks.

**Comment by jdxlabs** [comment]
I removed the "-purge" option when the jobs are stopped, and it actually works, the completed jobs are removed when the garbage collector is triggered.

It seems weird to me to not let the possibility to remove all the completed allocations... any reason or idea ?

I close the issue because my problem is actually solved.

Thanks to the team for this great work. 👍

**Comment by dadgar** [comment]
@jdxlabs Glad you figured it out. There are certain reasons we will not remove allocations when doing a GC and they are usually around correctness so that if the scheduler is run again it will make the correct decisions given knowledge of the older allocs for the job. This is especially true for batch jobs.
