### ISSUE TITLE
The process run by "raw_exec" always receives the "enter" signal

### ISSUE THREAD

**Issue by fanriming** [hashicorp/nomad#3708]
### Nomad version
0.7.1

### Operating system and Environment details
windows7、windows10 
### Issue
The process run by "raw_exec" always receives the "Enter" signal without any typein.
### Reproduction steps
1. Code test program like this :

```
// Demo
func test_stdin() {
	for {
		var tmpstr string
		fmt.Scanf("%s", &tmpstr)
		log.Println(tmpstr)
	}
}

func main() {
	fmt.Println("start demo!")
	test_stdin()
}
```

2. Creat job with job specification mentioned below.

### Job Specification with json

```
{
  "Stop" : false,
  "Region" : "global",
  "Namespace" : "default",
  "ID" : "demo",
  "ParentID" : "",
  "Name" : "demo",
  "Type" : "system",
  "Priority" : 50,
  "AllAtOnce" : false,
  "Datacenters" : [ "dc1" ],
  "Constraints" : null,
  "TaskGroups" : [ {
    "Name" : "demo",
    "Count" : 1,
    "Update" : null,
    "Constraints" : null,
    "RestartPolicy" : {
      "Attempts" : 2,
      "Interval" : 60000000000,
      "Delay" : 15000000000,
      "Mode" : "delay"
    },
    "Tasks" : [ {
      "Name" : "demo",
      "Driver" : "raw_exec",
      "User" : "",
      "Config" : {
        "command" : "E:\\developing\\Demo.exe",
        "args" : []
      },
      "Env" : null,
      "Services" : null,
      "Vault" : null,
      "Templates" : null,
      "Constraints" : null,
      "Resources" : {
        "CPU" : 100,
        "MemoryMB" : 10,
        "DiskMB" : 0,
        "IOPS" : 0,
        "Networks" : null
      },
      "DispatchPayload" : null,
      "Meta" : null,
      "KillTimeout" : 5000000000,
      "LogConfig" : {
        "MaxFiles" : 10,
        "MaxFileSizeMB" : 10
      },
      "Artifacts" : null,
      "Leader" : false,
      "ShutdownDelay" : 0,
      "KillSignal" : ""
    } ],
    "EphemeralDisk" : {
      "Sticky" : false,
      "SizeMB" : 300,
      "Migrate" : false
    },
    "Meta" : null
  } ],
  "Update" : {
    "Stagger" : 0,
    "MaxParallel" : 0,
    "HealthCheck" : "",
    "MinHealthyTime" : 0,
    "HealthyDeadline" : 0,
    "AutoRevert" : false,
    "Canary" : 0
  },
  "Periodic" : null,
  "ParameterizedJob" : null,
  "Payload" : null,
  "Meta" : null,
  "VaultToken" : "",
  "Status" : "running",
  "StatusDescription" : "",
  "Stable" : false,
  "Version" : 0,
  "SubmitTime" : 1514968498051228900,
  "CreateIndex" : 92,
  "ModifyIndex" : 92,
  "JobModifyIndex" : 92
}
```

**Comment by dadgar** [comment]
@fanriming Hey the process is reading from DevNull and has no stdin, so when you read you are getting an EOF.

If you modify your code to check and log the error from scanf you get:
```
start demo!
2018/01/03 10:16:50 EOF
```

Hope that helps.

**Comment by fanriming** [comment]
@dadgar Thanks for your help! 
But why does the program behave differently than it does at the front desk? I mean i don't want to get anything by scanf or os.stdin without typein just like the program run normaly, because many of our existing applications have similar problems, is there any solution? 

Looking forward to your answer. Thanks.

**Comment by dadgar** [comment]
@fanriming I am not sure what you mean by front desk. The solution is your programs need to check for EOF and stop scanning. This is normal behavior when reading from a file descriptor.

**Comment by shantanugadgil** [comment]
I assume @fanriming means "when run directly on the console" ?!

**Comment by dadgar** [comment]
The behavior is the same in Nomad as running the binary as follows on the console: `cat /dev/null | ./test`

**Comment by fanriming** [comment]
@shantanugadgil Thank you for your correction. @dadgar I seem to understand, it's like that the stdin is redirected to DevNull.
