### ISSUE TITLE
Undocumented change to minimum cpu allocation in job spec

### ISSUE THREAD

**Issue by comebackoneyear** [hashicorp/nomad#3709]
### Nomad version
Nomad v0.7.1

### Operating system and Environment details
Ubuntu 16.04

### Issue
The lower limit for cpu allocation for a job used to be 20, now it is 100
Seems to have been introduced by #3536

### Reproduction steps
Deploy a job with a Cpu allocation of less than 100

### Nomad Client logs (if appropriate)
Unexpected response code: 500 (1 error(s) occurred:
* Task group test validation failed: 1 error(s) occurred:
* Task test-beat validation failed: 1 error(s) occurred:
* 1 error(s) occurred:
* minimum CPU value is 100; got 94)

### Job file (if appropriate)
```
...
        "Resources": {
                            "CPU": 94,
...
```

**Comment by comebackoneyear** [comment]
Just found #3706 that seems to address this issue

**Comment by chelseakomlo** [comment]
Closing as #3706 has merged.
