### ISSUE TITLE
can't find service ACL.Bootstrap

### ISSUE THREAD

**Issue by zverocool** [hashicorp/nomad#3710]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.7.0

### Operating system and Environment details
RHEL7

### Issue

> [root@yyyyy server]# nomad acl bootstrap -address=http://127.0.0.1:4646
> Error bootstrapping: Unexpected response code: 500 (rpc error: rpc: can't find service ACL.Bootstrap)

> [root@yyyyy server]# nomad server-members
> Name         Address         Port  Status  Leader  Protocol  Build  Datacenter  Region
> xxxxx.DC1  172.24.103.50   4648  alive   true    2         0.6.2  EST         DC1
> xxxxx.DC1  172.24.101.175  4648  alive   false   2         0.6.2  EST         DC1
> xxxxx.DC1  172.24.101.181  4648  alive   false   2         0.6.3  EST         DC1
> yyyyy.DC1  172.24.100.157  4648  alive   false   2         0.7.0  EST         DC1

### Reproduction steps

We have an existing cluster of 0.6.x nodes. We are trying to introduce in a new 0.7.0 server, bootstrap ACL's and then roll the rest. We have done this in the same way before with no issues but today we are seeing **can't find service ACL.Bootstrap**

**Comment by dadgar** [comment]
@zverocool You will have to fully transition to the 0.7.0 servers, decommission the old 0.6.0 and then bootstrap ACLs. The RPC endpoint doesn't exist on the older  0.6.X binaries which is why you are seeing that error. Please let me know if you have any questions

**Comment by zverocool** [comment]
Thank you for the fast response dadgar, you are absolutely right. Thats how I did it before in my other environments and tests, but its been awhile and I forgot the correct procedure.
