### ISSUE TITLE
check_restart within service block is not recognized

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#3713]
### Nomad version

$ nomad version
Nomad v0.7.1

### Issue
check_restart not recognized at service block level as documented in https://www.nomadproject.io/docs/job-specification/check_restart.html

![](https://cldup.com/9gvQttIblp.png)

### Reproduction steps
Define a `check_restart` block within a `service` block. You will get the following message: 
```
* group: 'mygroup', task: 'mytask', service (0) -> invalid key: check_restart
```

**Comment by chelseakomlo** [comment]
Hi, thanks for letting us know about this issue. Do you mind including the job configuration where you see this error?

**Comment by c4milo** [comment]
@chelseakomlo hi! sure, here is an example job file that reproduces the issue: 

```hcl
job "test" {
	type = "service"
	region = "global"
	datacenters = ["dc1"]

	update {
		max_parallel     = 1
		canary           = 5
		min_healthy_time = "30s"
		healthy_deadline = "10m"
		auto_revert      = true
	}

	group "mygroup" {
		count = 2

		task "mytask" {
			driver = "exec"

			config {
				command = "/bin/sleep"
				args 	= ["1"]
			}

			resources {
				network {
					mbits = 1
					port "mytask" {}
				}
			}

			service {
				port = "mytask"

				check {
					type     = "tcp"
					port     = "mytask"
					interval = "10s"
					timeout  = "2s"
				}
				check_restart {
					limit = 3
					grace = "90s"
					ignore_warnings = false
				}
			}
		}
	}
}
```

**Comment by schmichael** [comment]
Thanks for the update @c4milo! #3718 will fix it, but since it might not make it into a release for a while #3716 is going to (temporarily) remove that feature from the documentation.

Until the next release you'll have to put the `check_restart` stanza inside the `check` stanza.

**Comment by schmichael** [comment]
Fixed but forgot to close. Sorry!
