### ISSUE TITLE
[question] Nomad retries all failed job after nomad agent restart

### ISSUE THREAD

**Issue by chandrasekarkr** [hashicorp/nomad#3714]
### Nomad version
0.6.0

### Operating system and Environment details
OSX 10.11.5 & CentOS

### Issue
When I run the following job which runs for every 30 mins ( & is designed to fail for simulation), Nomad fail/retry works as expected. However, all the failed jobs restart automatically, when the nomad agent (which is setup as service) is restarted.

For ex. if the job fails thrice between 10 - 11AM (10:00, 10:30 & 11:00) and if the nomad agent (service in my case) is restarted t 11:10, all three failed jobs re-run in parallel.

Is this an expected behaviour and if so, how can we prevent a failed job from re-running.

### Reproduction steps
Run Nomad server with nomad `agent` and submit a job with nomad run `example.nomad`.

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

### Job file (if appropriate)
```
job "test" {
  datacenters = ["dc1"]
  type = "batch"

  group "test-1" {
    count = 1
    restart {
      attempts = 3
      interval = "1h"
      delay = "15s"
      mode = "fail"
    }

    task "test-1" {
      driver = "raw_exec"
      config {
        command = "bash"
        args = ["-c", "sleep 2; nocommand"]
      }
    }
  }
}
```

**Comment by chelseakomlo** [comment]
Hi, thanks for letting us know about this issue. 

Do you mind including your full repro steps here? Running nomad in `-dev` state does not save state, so it shouldn't re-run jobs after restarting.

**Comment by chandrasekarkr** [comment]
Apologies, it is not run as `agent -dev` and run as regular agent `nomad agent -config=nomad-client.conf`

**Comment by schmichael** [comment]
Looks like there's at least 1 bug here if not 2: 

1. Nomad does not persist failure/restart history across agent restarts, so after restarting the agent your restart policy effectively starts over.
2. The agent should never start tasks that are in a terminal state (eg failed or completed).

**Comment by dadgar** [comment]
@chandrasekarkr Sorry for the mixed messaging on this ticket. This is actually expected behavior as the scheduler is replacing a failed allocation to try to finish the batch job. There is currently no way to enforce the scheduler does not create a replacement.

In Nomad 0.8 (the next version), this will be possible as we will be allowing operators to configure how the scheduler replaces failed allocations and if at all. So your job specification would say that no restarts are allowed.

I am going to close as the current behavior is expected.

**Comment by chandrasekarkr** [comment]
@dadgar Are there any solutions/workarounds to get away from this behaviour. The current problem is with the number of jobs hanging in `failed` state. During node reboots, all `failed` jobs attempt rerun in parallel.

One workaround I can think of is to stop the job manually, upon failure.

**Comment by dadgar** [comment]
@chandrasekarkr What you could do in the mean time is run the force GC via `curl -XPUT http://127.0.0.1:4646/v1/system/gc` on a cron to clear these out.

**Comment by chandrasekarkr** [comment]
@dadgar `curl -X PUT http://127.0.0.1:4646/v1/system/gc` option clears all `dead` jobs across nomad cluster. Is there any option to clear jobs based on job name/group name.
