### ISSUE TITLE
[question] how to configure 'docker' to use token or service token?

### ISSUE THREAD

**Issue by inmchfw** [hashicorp/nomad#3726]
Hi all

I am new to Nomad. I had teraform, nomad and consul working and was able to deploy public docker image. However, when I tried to use '_token' and '_json_token' to access google container registry but in both situation, I could not get nomad to do the job. Here's what I got:

`failed to initialize task "leto test" for alloc "225353c3-aa60-8470-7b56-54b4364f73de": Failed to pull `gcr.io/terraform-nomad-consul-trial/test:latest`: API error (404): {"message":"pull access denied for gcr.io/terraform-nomad-consul-trial/test, repository does not exist or may require 'docker login'"}`

Here's how I configure nomad docker job:

```
    task "test docker" {
      driver = "docker"

      config {
        image = "gcr.io/terraform-nomad-consul-trial/test:latest"

        auth {
          username = "_token"
          password = "{\"access_token\":\"ya29.c.El08BsdfdfG6GartuLCfAVzH2j_hk1s3KvIWg2Fgpbf3FQQSo-mPdfPxnMQhkz9ngvJx-gcZNpEG_emKphVLgjNsdfdfn26Sg\",\"expires_in\":2878,\"token_type\":\"Bearer\"}"
         }
      }
     ...
```

for json token, I would do the same way. username = '_json_token' and password = 'the actual json token'. What could I have better?

Thanks

**Comment by chelseakomlo** [comment]
Hi, thanks for the question. You can set set these credentials in a json file, see https://www.nomadproject.io/docs/drivers/docker.html#auth_file

Nomad supports using the GCR Docker credential helper as well, see: https://www.nomadproject.io/docs/drivers/docker.html#docker-auth-helper configuration option and https://github.com/GoogleCloudPlatform/docker-credential-gcr

See more info here: https://www.nomadproject.io/docs/drivers/docker.html#authentication

**Comment by dadgar** [comment]
@inmchfw If you want to embed the raw auth token please follow the instructions here: https://cloud.google.com/container-registry/docs/advanced-authentication#using_a_json_key_file

**Comment by inmchfw** [comment]
@chelseakomlo and @dadgar , thanks for your reply. 

I was able to install docker-credentials-gcr onto my nomad clients and configure docker to login successfully. However, I wondered how to load the client configurations so that nomad client would assume docker has logged in and can pull private images from google container registry.


```
client {
  enabled = true
  options {
     "docker.auth.config" = "/home/my_dev_account/.docker/config.json"
  }
}
```

On the client instance, I issue these commands and got data-dir is omitted.
```
$ nomad agent -config=docker-client.config
==> Must specify both the state and alloc dir if data-dir is omitted.
```

continued with data-dir='/tmp' and got these:

```
$ nomad agent -config=docker-client.config
    Loaded configuration from docker-client.config
==> Starting Nomad agent...
==> Error starting http server: failed to start HTTP listener: listen tcp 0.0.0.0:4646: bind: address already in use
    2018/01/09 11:50:29.433019 [INFO] client: using state directory /tmp/client
    2018/01/09 11:50:29.436719 [INFO] client: using alloc directory /tmp/alloc
    2018/01/09 11:50:29.449261 [INFO] fingerprint.cgroups: cgroups are available
    2018/01/09 11:50:29.450821 [INFO] fingerprint.consul: consul agent is available
    2018/01/09 11:50:29.480714 [WARN] fingerprint.network: Unable to parse Speed in output of '/sbin/ethtool ens4'
    2018/01/09 11:50:29.496494 [INFO] client: Node ID "4609f827-2d4b-141c-89ee-86dbbdb52b26"
    2018/01/09 11:50:29.496600 [INFO] agent: requesting shutdown
    2018/01/09 11:50:29.496602 [INFO] client: shutting down
    2018/01/09 11:50:29.503893 [ERR] client.consul: error discovering nomad servers: 2 error(s) occurred:
* rpc error: No path to region
* rpc error: No path to region
    2018/01/09 11:50:29.561873 [INFO] agent: shutdown complete
```

Why am I getting those things?

**Comment by dadgar** [comment]
@inmchfw You will have to set the data_dir: https://www.nomadproject.io/docs/agent/configuration/index.html#data_dir

An example: `data_dir  = "/var/lib/nomad"`
