### ISSUE TITLE
[question] periodic jobs monitoring, alerts on lack of successful completions in the last 15 minutes

### ISSUE THREAD

**Issue by gerilya** [hashicorp/nomad#3737]
I am trying to figure out the best way to monitor periodic jobs.

We use Datadog for our infra monitoring, so it would be best to have a metric showing a number of successful job runs (per job). I've checked https://www.nomadproject.io/docs/agent/telemetry.html page and found **nomad.client.allocs.complete** metric which looks like it fits the bill. Is that right?

What other options are there?

Thank you very much.

**Comment by schmichael** [comment]
`nomad.client.allocs.complete` is probably best for your use case.

There are rare cases where the metric will be incremented but your batch job was not run to completion. The only case I can think of is when draining a node with running batch tasks: the allocs will be marked as completed *and* run on a new node. Therefore they'll be double counted in that case.

Nomad v0.8 should offer the ability to give batch jobs time to complete when draining, but emitting a metric directly from your batch job's code is the only way to fully control the metric's precision.

Hope that helps!
