### ISSUE TITLE
[feature] Reload TLSConfig.CAFile on SIGHUP

### ISSUE THREAD

**Issue by SoMuchToGrok** [hashicorp/nomad#3746]
A very much appreciated feature was recently delivered to support graceful reloads of the TLS configuration. 

https://github.com/hashicorp/nomad/pull/3479/files

I think this needs to be extended to also refresh the CA file (if defined). I run very short TTLs on both server certificates and root CAs. As it's currently implemented, this is still a huge pain point for me.

I might be able to take a stab at this myself, but want to get a conversation going first. Thoughts or concerns?

Thanks!

**Comment by schmichael** [comment]
Seems reasonable to me! Hopefully as easy as giving `TLSConfig.CAFile` the same treatment as the CertFile and KeyFile fields got in that PR.

**Comment by shadowfax-chc** [comment]
I think you will also want to refresh the [`VaultConfig.TLSCaFile`](https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/vault.go#L58-L64) and [`ConsulConfig.CAFile`](https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/consul.go#L60) and then reload the vault/consul clients to use the new config, since it is likely that these would be using the same CA, or at least the CAs for vault and consul would also be short lived.

**Comment by shadowfax-chc** [comment]
It looks like #3492 would *almost* resolve this issue. The only problem is that [this function](https://github.com/hashicorp/nomad/pull/3492/files#diff-c2b91142a0ac15d7fb511420cafb2f61R735) would potentially prevent reloads when they might be desired. In my case, the TLSConfig itself does not change, but the contents of the files referenced in the TLSConfig *do* change when a new CA is issued. If this reload would happen every time a `SIGHUP` is sent, it would address the `TLSConfig.CAFile` issue (the `ConsulConfig.CAFile` would still need to be addressed).

**Comment by schmichael** [comment]
Just a heads up this feature will _not_ land in #3492 as it's already a large PR that's close to merging. We'll definitely be using what's in #3492 to add this feature though.

**Comment by SoMuchToGrok** [comment]
Sounds great @schmichael! Thanks for keeping us updated.

**Comment by SoMuchToGrok** [comment]
https://github.com/hashicorp/nomad/pull/4025

I think this might be the enhancement we're looking for?

**Comment by Xopherus** [comment]
I believe that PR does fix this issue @SoMuchToGrok. Though the fix does not reload the CA or cert on `VaultConfig` - that issue is captured in #6052

Seems like we can close this @schmichael?

**Comment by schmichael** [comment]
Yes, thanks @Xopherus! Closing.
