### ISSUE TITLE
[feature] update one group at a time

### ISSUE THREAD

**Issue by alxark** [hashicorp/nomad#3748]
Hello. I have a job file with 2 groups ( gr1 with count 3 and gr2 with count 1). Unfortunately when i'm updating to new release i might get some trouble with service (i'll loose quorum inside service). So i need to limit update and update one group at a time, for example : gr1, gr2, gr1, gr1. Is there any option to do this ?

**Comment by schmichael** [comment]
Hi @alxark!

Nomad will only update the groups with changes, so if you resubmit a job and only change `gr2` -- `gr1` will not be touched. Splitting the groups into different jobs may make this even easier to operate.

If you're not already using canaries, I'd encourage you to read about Nomad's [Update Strategies](https://www.nomadproject.io/docs/operating-a-job/update-strategies/index.html). Nomad's `update` stanza has a number of options for making deploys safer.

I hope that helps and please feel to reopen if I didn't address your issue!

**Comment by alxark** [comment]
Thank you for your reply. Well i think i should better describe my case. 
I have a galera cluster with 3 nodes as GROUP1 and 1 node as SST donor as GROUP2. This service is deployed by CI system. So when i made changes to galera project (holds Dockerfile, our configs + nomad job) it will push updates for GROUP1 and GROUP2, and nomad updates 2 group right after push. Unfortunately this might cause problems, because 2 nodes might go down. I don't want to create complex scenarios with generating 2 job files or split group updates. So is there any useful options for my case?

**Comment by schmichael** [comment]
Hm, I'm not sure I follow. I'm assuming you have a job file similar to:

```hcl
job "mysql" {
  group "group1" {
    count = 3
    # ...
  }

  group "group2" {
    count = 1
    # ...
  }
}
```

And when your CI pushes updates, multiple instances of `group1` can go down at once?

If that's the case, fixing it may be as easy as setting [`max_parallel = 1`](https://www.nomadproject.io/docs/job-specification/update.html) in an `update` stanza on `group1`.

If the issue is that you need `group2` to only be updated _after_ `group1` is successfully updated, I'm afraid you'll have to script that yourself. Nomad doesn't currently have any abilities to manage updates across multiple jobs or groups. You will need to submit the update to `group1` and then wait for it to complete before updating `group2`.

**Comment by alxark** [comment]
Thank you @schmichael , and I'm so sorry for long reply, i have missed this ticket. I have solved this problem by adding different shutdown_delay for group 1 and group 2 ( in my previous case galera donor goes down right after CI run and galera worker nodes waits for some time). But i'm faced same problem again. I'm trying to setup clickhouse database inside nomad cluster. And i made several groups for each shard so my job looks like this:

```
job "clickhouse" {
    group "shard-01" {
        count = 2
     }
     group "shard-02" {
       count = 2
    }
   group "shard-03" {
     count = 2
   }
}
```
so right after deployment i'm getting half of all nodes getting restarted and that's not cool. Maybe there should be some option in nomad? Like max_parallele_group. And i think it's better to reopen this ticket.

**Comment by schmichael** [comment]
@alxark At this time I think your best option is to put each group into a single group and use `$NOMAD_ALLOC_INDEX` to compute shard indexes.

Putting each group into an independent job and orchestrating updates with your own custom script is the most flexible solution but obviously the most complex to implement.

In the future we intend to support job dependencies which may help as well: https://github.com/hashicorp/nomad/issues/419#issuecomment-157138436
