### ISSUE TITLE
[improvement] CLI batch job run or dispatch with automated log and return code

### ISSUE THREAD

**Issue by aconte76** [hashicorp/nomad#3753]
Why is not possible to run or dispatch a parametrised batch job with log?
For example assuming a templated job 'MY_JOB' could be useful to have something like:

nomad job dispatch -meta "PARAM1="VAL1" -log MY_JOB 

possibly, for easiest shell integration run and dispatch could return internal failing taskCode.

### Nomad versions
ALL current `0.7.1` 

### Operating system and Environment details
ALL

**Comment by alxark** [comment]
need this function too. Would like to run test jobs inside cluster and need log for CI system for debug purposes.

**Comment by schmichael** [comment]
I really like this idea, but I'm not sure when it will make it on our roadmap.

In the meantime this feature could be done by an external contributor -- or it could even be a separate small application that uses Nomad's APIs:

- In Go: https://github.com/hashicorp/nomad/issues/3752
- HTTP API docs: https://www.nomadproject.io/api/index.html

Thanks for the idea!

**Comment by aconte76** [comment]
I've done it with a Java piece of software because I'm not so good with GO.
for sure I can share idea

**Comment by jrasell** [comment]
this is likely something I will add to [Levant](https://github.com/jrasell/levant) after the "batch-log" command had been introduced which has similar functionality to this.

**Comment by lgfa29** [comment]
Closing this one in favour of #11601. Even though this was opened first #11601 has more 👍 which help us gauge priority. Feel free to add more 👍 and comments there. Thank you everyone for the input!
