### ISSUE TITLE
[docs] example of default Consul integration is missing

### ISSUE THREAD

**Issue by zstyblik** [hashicorp/nomad#3758]
Hello,

it seems that example of default Consul integration is missing in [docs](https://www.nomadproject.io/docs/agent/configuration/consul.html#default). Picture is worth thousand words, so here it is:

![missing](https://user-images.githubusercontent.com/6183869/34991375-ac97617a-fac9-11e7-8808-fb1cd4552810.png)

I've tried Firefox, chromium and checked HTML source, but it seems there is nothing in the HTML indeed.

Thank you.

**Comment by dadgar** [comment]
Hey,

You can see the linked PR for the defaults. There was nothing showed because the docs were trying to show you that by default you don't need to add any extra configuration. This however is less useful than just showing the defaults.

**Comment by zstyblik** [comment]
O_o indeed. However, it's a bit confusing to show just an empty box stating "this is not a mistake". :)

PR looks alright, thank you.
