### ISSUE TITLE
revert nomad status <ID> command to allow ability to filter based on job-name prefix

### ISSUE THREAD

**Issue by olenm** [hashicorp/nomad#3763]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Issue
New version of `nomad status <ID>` returns an error and a comma-separated list of jobs when many are matched.

Please either add an option for this behavior (or the previous behavior) and/or revert to the previous behavior where calling `nomad status <ID>` would filter jobs by a static prefix and not result in an error all-the-while including the `nomad status` header in a nicely formatted list.

We have many jobs running and being able to filter via the native nomad binary far exceeds having to create our own shell wrapper-function or pipelining the output.

Thanks!

**Comment by dadgar** [comment]
`nomad status` is now used to be able to query any identifier in Nomad. It still supports prefix matching:

```
$ nomad status ex
Multiple matches found for id "ex"

Jobs:
example, examplefoo, examplefoobar
```

If you would like the old behavior use `nomad job status`

**Comment by olenm** [comment]
Oh very nice; I did not see that in the change logs so figured it was wiped out completely. 

Appreciate the fast response!

**Comment by olenm** [comment]
@dadgar: 
is there going to be some consistency to the `jobs` function (or maybe its in a roadmap I did not see?), specifically:
- `nomad job stop` does not exist
-  `nomad job inspect <bla>` also does not exist
- `nomad job status <prefix> 2>&1` has to be used for any kind of further filtering, where previously the `nomad status <prefix>` did not stderr redirection

Its great to have a general `nomad status ID` that does a magic any-resource-object lookup, but if it finds multiple resources of the same type, can we at least have the the associated pretty-print?

Fo example: if `nomad status <some-chars>` matches exactly 2 Allocations and no other type, print them out like a `nomad alloc-status <some-chars>` would match. I'm not asking for a pretty-print for multiple resource-objects matching the prefix (although that would likely be doable too depending on the approach)

**Comment by dadgar** [comment]
@olenm Yeah we need to go through all the CLI and move to subcommands to bring them in-line. Hopefully soon, it is just somewhat annoying since we need to do it in a backwards compatible way to not break everyones scripts.

There pretty print is interesting. I could imagine it for jobs but for any of the UUID based ones, the odds are pretty low of being in that situation.
