### ISSUE TITLE
Missing Deployment info

### ISSUE THREAD

**Issue by aantono** [hashicorp/nomad#3768]
### Nomad version
Output from `nomad version` - `0.7.1`

### Operating system and Environment details
Amazon Linux

### Issue
Unless a job specification has `update` stanza in it, the `Deployments` section is missing.

### Reproduction steps
Deploy any job, which does not have `update` stanza and try to access it's `deployment` via API call: `/v1/job/<jobID>/deployment`.  The response will be a `200-OK` with content of `null` text

### Job file (if appropriate)
```
job "whoami" {
  datacenters = ["dc1"]
  type        = "service"

  group "whoami" {
    count = 1

    task "whoami" {
      driver = "docker"

      config {
        image = "emilevauge/whoami"

        port_map = {
          http = 80
        }
      }

      resources {
        cpu    = 100 # Mhz
        memory = 50  # MB

        network {
          mbits = 1

          port "http" {}
        }
      }
    }
  }
}```

**Comment by dadgar** [comment]
Hey,

A deployment is an object created to manage a job transitioning between versions when there is an update stanza. Without an update stanza, no deployment will be created.

Let me know if that makes sense!
