### ISSUE TITLE
Snapshot save/restore

### ISSUE THREAD

**Issue by pmcatominey** [hashicorp/nomad#3770]
There currently doesn't seem to be a way to save and restore snapshots like there is in Consul, this leaves open the prospect of orphaned allocations in the event of all servers being lost.

**Comment by dadgar** [comment]
@pmcatominey In that case, the clients would connect to the new servers and the all their allocations would be killed. Since Nomad doesn't have the K/V store, recovering should involve just resubmitting the jobs that should be running.

**Comment by pmcatominey** [comment]
@dadgar yeah, after discussing this in Gitter I think just capturing the Jobs from the API will suffice to backup the cluster state.

This issue can be closed from my perspective.
