### ISSUE TITLE
[improvement] Stop a deployment without failing it

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/nomad#3774]
I discussed this briefly with Alex on the [mailing list](https://groups.google.com/forum/#!topic/nomad-tool/eVXuivhK41c) back in December.

My specific issue is that I have some old deployments that are still running for a critical service type job. Due to a bug at the time with nomad deployments (we think), these old jobs have a wide range of version numbers and some that are quite large. We don't have any way to reproduce it.

We have since re-deployed the job and it is stable on Nomad 0.7.1.

If I attempt to fail any of those old deployments, I believe nomad will try to roll back to a version relative to the old deployment and not what is currently running. I am also not sure what will happen if any of our new deployments fail for legitimate reasons.

I need some way to stop and GC these deployments without changing any other state of the job. I'm open to suggestions.

If there are other reasons why an operator might want to stop a deployment where it is without completing or reverting, I could see it as part of the deployment API/CLI.

```
0b949e44  job-b              2            successful  Deployment completed successfully
8dce37ce  job-a              151          running     Deployment is running
cb792f90  job-a              121          running     Deployment is running
a7dcd749  job-a              107          running     Deployment is running
c767eff9  job-a              104          running     Deployment is running
b0302308  job-a              35           running     Deployment is running
4d94cbf1  job-a              12936        running     Deployment is running
a06501d5  job-a              3384         running     Deployment is running
....
```

**Comment by alxark** [comment]
i faced this behaviour a few times and it made me a lot of pain

**Comment by dadgar** [comment]
@stevenscg @alxark There should be no more deployments being created in this state since 0.7.1, correct?

**Comment by dadgar** [comment]
@stevenscg If you run `nomad job history <job-a>` is the highest job version stable and the one you want to be running? If so you should just mark the deployments as failed and they will garbage collect.

**Comment by stevenscg** [comment]
@dadgar 0.7.1 has been great! No instances of this happening since the upgrade. 0.7.0 might have been fine as well. I can't remember at the moment.

So for `nomad job history <job>`, the jobs that are still around with running deployments no longer exist. We've since changed the job name entirely and now I get a prefix matched list:

```
$ nomad job history job-a
Prefix matched multiple jobs

ID                    Type     Priority  Status   Submit Date
job-a-foo             service  50        running  01/19/18 21:27:53 UTC
job-a-bar             service  50        running  01/19/18 21:28:39 UTC
....
```

I'd be somewhat skiddish about trying to stop those deployments for fear of it resurrecting an old job and conflicting with the new ones that are doing roughly the same work.

**Comment by dadgar** [comment]
@stevenscg You should be able to fail the deployment without any side effect. If you want to follow the code: https://github.com/hashicorp/nomad/blob/master/nomad/deploymentwatcher/deployment_watcher.go#L277-L285

What will happen is it will look for the latest stable job with that name but there won't be any so it will fail the deployment without doing a rollback. 

Please try this on one job and if it works lets close this out.

**Comment by stevenscg** [comment]
@dadgar This is what I get on Nomad 0.7.1:

```
nomad deployment fail 4d94cbf1
Error failing deployment: Unexpected response code: 500 (rpc error: deployment "4d94cbf1-3068-b280-f7d6-44d6cf61a8d9" references unknown job "job-a")
```

**Comment by dadgar** [comment]
@stevenscg I think we will have to give you a one off build to allow cancelling the deployments. 

The cancel is not really an API we would like to expose since its behavior isn't really well defined. A cancelled deployment will be replaced immediately by the next scheduler event in the case a deployment is actually doing work (which is the case for all deployments except those created by this now fixed bug)

**Comment by stevenscg** [comment]
@dadgar That sounds good. Just so I know later, I would need to run that special build on all of the servers (or at least get one of them elected as a leader), right?

One other thought I had just now was to register a no-op job by that old job name and see if I can fail those deployments.

**Comment by dadgar** [comment]
@stevenscg That is a great idea. You should try that first and report back.

**Comment by stevenscg** [comment]
@dadgar That worked like a champ. I expect these will get GC'd in a bit and I think we're good here.

**Comment by dadgar** [comment]
Woot!!!
