### ISSUE TITLE
Nomad logs API/Command - general usage issues

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#3782]
The Nomad logs command and API implementation/usage results in enforced connection to the Nomad node where the allocation resides as far as I am aware. In secure environments this poses a problem for the UI or any 3rd party tools that use server exposed APIs through a load balancer.

Is there any roadmap item for allowing the logs to be retired via the Nomad servers in something like a proxy behaviour?

### Nomad version
`Nomad 0.7.1`

### Reproduction steps

Navigate - https://demo.nomadproject.io/ui/allocations/d7c277c2-0883-bb72-3517-bd11618eafd6/mongo/logs

View the browser console and try to stream the logs and see an error such as: `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR https://54.225.12.99:4646/v1/client/allocation/d7c277c2-0883-bb72-3517-bd11618eafd6/stats`

**Comment by dadgar** [comment]
@jrasell This will be addressed in 0.8.0. If you would like to track this work, follow this branch: https://github.com/hashicorp/nomad/tree/f-tunnel.

**Comment by jrasell** [comment]
thanks @dadgar; looking forward to that. happy for you to close this if you want or keep open as a reference.

**Comment by dadgar** [comment]
Either way! I can close once the feature hits master.

**Comment by dcparker88** [comment]
Is this still a planned feature? My nomad clients won't be accessible from my team's laptops, and only nomad server is available through a load balancer. It would be great if the nomad server could load the logs directly, then show them to me, rather than my browser trying to call the nomad client directly.

**Comment by jrasell** [comment]
@dcparker88 I believe this has made it into master at least so you can test locally potentially before any release candidate.

**Comment by schmichael** [comment]
@jrasell is right! This feature was recently merged in #3892. Quite a few big 0.8 features still landing in the next couple of weeks so while testing from master should work, expect a lot of churn. RC and release of 0.8 shouldn't be too far out!

**Comment by dcparker88** [comment]
thanks 👍
