### ISSUE TITLE
[question] Unable to manage privatedocker networks on the fly

### ISSUE THREAD

**Issue by ennetech** [hashicorp/nomad#3783]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Driver
Docker

Sometimes i have to deploy group of services that are linked together (for example phpMyAdmin + mariadb), and i don't want to publicly expose unnecessary service port.

The solution is to create a network on target host with 

docker network create example-network

and then in the job specification add to the tasks config:
```
network_mode = "example-network"
network_aliases = [
  // Any alias i want
]
```

The problem is that in this situation i have to manually manage the creation/deletion of the private network, i tried to hack a solution adding this task to the job:
```
task "network" {
  driver = "exec"

  config {
    command = "dnet"
    args    = ["private"]
  }
}  
```
where dnet is composed as follow:
```
#!/usr/bin/env bash
NET_NAME=$1
at_term() {
    for i in ` docker network inspect -f '{{range .Containers}}{{.Name}} {{end}}' $NET_NAME`; do docker network disconnect -f $NET_NAME $i; done;
    docker network remove $NET_NAME
    exit 0
}
docker network create $NET_NAME
trap at_term SIGINT
sleep inf
```

but the lack of dependency execution order makes the process unreliable

Anyone have a better solution?

Thanks!

**Comment by dadgar** [comment]
Hey @ennetech,

Unfortunately without task dependencies that approach will be unreliable as you mentioned. Unfortunately this isn't well supported at the moment. The two issues to track will be:

https://github.com/hashicorp/nomad/issues/149
https://github.com/hashicorp/nomad/issues/419

Sorry I can't give you a work around in the meantime!
