### ISSUE TITLE
Automatically set VAULT_ADDR when Vault integration is used

### ISSUE THREAD

**Issue by aantono** [hashicorp/nomad#3793]
After looking at a current configuration for Nomad clients, I see that the client config block does take `address` for `vault` stanza - https://www.nomadproject.io/docs/agent/configuration/vault.html#nomad-client  Further more, the [Vault Integration](https://www.nomadproject.io/docs/vault-integration/index.html) docs say that both Nomad Server and Client share the same Vault server to 

> coordinate with Vault to derive a Vault token that has access to only the Vault policies the tasks needs. Nomad clients make the token available to the task and handle the tokens renewal. Further, Nomad's template block can retrieve secrets from Vault making it easier than ever to secure your infrastructure.

Given that the Client nodes already know the address of Vault servers from which the `VAULT_TOKEN` is being issued, I think it would be helpful to automatically expose the `VAULT_ADDR` environment variable along with `VAULT_TOKEN` to remove the boiler-plate need for configuring that env var explicitly in every nomad job file.  Architecturally it also improves transparency and makes the integration clean from the consumer's standpoint, as the job owner does not need to know anything about the underlying infrastructure networking, i.e. where is the particular Vault server cluster resides at or having to worry about explicitly needing to configure that piece of data.  It also makes the job files easier to maintain, as the same file can be truly environment agnostic and can be used in multiple data centers/regions without having to make multiple copies just to fork for different env variable values like Vault address.

I would be happy to help out with a PR once there is an agreement on the functionality, if needed.

**Comment by chelseakomlo** [comment]
Hi, thanks for this feedback. We discussed this internally and have a couple thoughts: 

First, for this specific use case, we recommend using service discovery (such as Consul). VAULT_ADDR is not universally applicable, as the Vault address used by the Nomad agent might not be usable by the container. 

However, we will in the future add the concept of supporting general operator-specified environment variables in a client configuration. What this would be is the ability for an operator to specify environment variables in a client configuration which will then be exposed to all tasks that run on that node. Hopefully this will help other cases where environment variables should be available on a per-node basis as opposed to per-job basis, as you point out.

**Comment by aantono** [comment]
@chelseakomlo thanks for the feedback.  Do you happen to ha e the timeline for the node-specific env vars support?  Currently not being able to “globally/automatically” configure VAULT_ADDR is a blocker for Nomad adoption at my company, so would be nice to know the anticipaated timeline.

**Comment by chelseakomlo** [comment]
For exec, raw_exec, and Java drivers, you can set environment variables on the client directly and these will be inherited by tasks (see https://www.nomadproject.io/docs/agent/configuration/client.html#quot-env-blacklist-quot- for the opposite use case).
