### ISSUE TITLE
Nomad keeps failing with "disk exhausted" after resizing disk

### ISSUE THREAD

**Issue by publysher** [hashicorp/nomad#3800]
### Nomad version
`Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)`

### Operating system and Environment details
`Linux worker001 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux` on an AWS t2.micro provisioned with ELB

### Issue
Because I ran out of disk space, Nomad could not complete the job evaluation - this makes sense. After increasing the disk size, Nomad still cannot complete the job evaluation due to "disk exhausted". 

Restarting Nomad will fix the problem. 

Most interesting was the output of `nomad node-status`:

```
ID      = 9df85219
[...]
Drain   = false
Status  = ready
Drivers = docker,exec
Uptime  = 2402h27m46s

Allocated Resources
CPU           Memory           Disk             IOPS
520/4800 MHz  1.9 GiB/3.9 GiB  3.8 GiB/3.9 GiB  0/0

[...]

Host Resource Utilization
CPU            Memory           Disk
4800/4800 MHz  1.1 GiB/3.9 GiB  5.7 GiB/16 GiB
```

The Host Resource utilization reports the correct availability, yet somehow this new information seemed to be unavailable to the evaluation. 

### Reproduction steps

* Fill disk
* Run new job
* Repeat above until you get an error regarding disk exhaustion:

```
==> Evaluation "a5444482" finished with status "complete" but failed to place all allocations:

    Task Group "..." (failed to place 1 allocation):

      * Class "A" filtered 1 nodes

      * Constraint "${node.class} = B" filtered 1 nodes

      * Resources exhausted on 2 nodes

      * Class "B" exhausted on 2 nodes

      * Dimension "disk" exhausted on 2 nodes

    Evaluation "b25eec10" waiting for additional capacity to place remainder
```

* Resize the disk (in my case: resize ELB, run `growpart` and `resize2fs`) such that `df` reports the correct availabilty.
* Run `nomad node-status <node-id>` to see the correct size being reported
* Check that the evaluation is still blocked
* Restart nomad
* See that the evaluation succeeds

### Nomad Server logs (if appropriate)

I failed to find any relevant logs. 

### Nomad Client logs (if appropriate)

I failed to find any relevant logs. 

### Job file (if appropriate)

Any

**Comment by shantanugadgil** [comment]
ELB? I guess you mean EBS?

**Comment by publysher** [comment]
@shantanugadgil yes, EBS, sorry. 

I've also been informed that this is a result of #3151 . Closing this and hoping this issue helps SEO :-)
