### ISSUE TITLE
Task Setup fails with mount: operation not permitted

### ISSUE THREAD

**Issue by abergmeier** [hashicorp/nomad#3801]
### Nomad version
0.7.0

### Operating system and Environment details
Ubuntu 16.04

### Issue

Running Nomad in a Docker container and trying to start a simple task leads to a fail:

    failed to build task directory for "foo-task": mount: operation not permitted

Running on a bare Ubuntu 16.04 works fine, though.

### Nomad Server logs (if appropriate)

    nomad alloc-status -verbose bb60886c

gives:

```
Recent Events:
Time                   Type           Description
01/26/18 17:00:06 CET  Setup Failure  failed to build task directory for "foo-task": mount: operation not permitted
01/26/18 17:00:06 CET  Task Setup     Building Task Directory
01/26/18 17:00:06 CET  Received       Task received by client
```

**Comment by shantanugadgil** [comment]
AFAIK running Nomad as Docker is not exactly supported as it restricts the capabilities needed to do many system level things.
FWIW, there have been many issues opened around this.

OTOH a possibly genuine use case being of CoreOS, where everything is a docker, but that's a different discussion. ☺️

**Comment by preetapan** [comment]
Like @shantanugadgil pointed out we don't recommend running nomad in docker. This is also discussed in prior issues, most recently https://github.com/hashicorp/nomad/issues/3676
