### ISSUE TITLE
Enhance node-status to show custom columns

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#3803]
As discussed in
https://github.com/hashicorp/nomad/pull/3684

... request you to consider this as a feature request to enhance the `node-status` command to
choose which columns to show.

The easiest way comes to mind is a '-o' flag like the 'ps' command or the LVM2 command lines
pvs, vgs, lvs.

### Nomad version
Output from `nomad version`
0.7.1 
### Operating system and Environment details
CentOS 7/Ubuntu 14.04/Ubuntu 16.04

Regards,
Shantanu

**Comment by lgfa29** [comment]
Closing this in favour of #15894. While not exactly the same it would be best to standardize our commands around common flags, such as `-json` and `-t`. Thanks for porposal @shantanugadgil!
