### ISSUE TITLE
[question] best practice while addressing canary deployment

### ISSUE THREAD

**Issue by yellowmegaman** [hashicorp/nomad#3804]
Hi there!

### Nomad version
Nomad v0.7.1

I'm following this guide:
https://www.nomadproject.io/docs/operating-a-job/update-strategies/blue-green-and-canary-deployments.html

I'm running deployment via nomad plan and run remotely ( `-address=remotehost` )
Everything works perfectly, but I've got a question:

What are best practices finding out deployment id?

After `run` i can grep `run` output, and get deployment id, which I'll use in `promote` procedure.
I also can query nomad API, but there are multiple id's for one service, so i assume latest one is at the top:

```
curl -sXGET http://127.0.0.1:4646/v1/deployments | jq -r '.[]'
```

I don't like grep, really. Please advise how to get id properly.

Example case:
deploy 2 redis docker containers version `3`
change version to `4`, run
verify deployment (own logic)
promote.

Thanks a bunch in advance!

**Comment by jrasell** [comment]
@yellowmegaman the [get job latest deployment](https://www.nomadproject.io/api/jobs.html#read-job-39-s-most-recent-deployment) API call may be helpful to you which will return the latest deployment ID of a given job.

**Comment by yellowmegaman** [comment]
@jrasell Thank you! This can actually make it better. ATM we're not deploying from multiple locations instantaneously, but it could be a problem in the future.

**Comment by chelseakomlo** [comment]
Hi, thanks for the question. As @jrasell recommended, getting the deployment ID from the jobid/deployment API is a good option.
