### ISSUE TITLE
Change the date format to a universal one, ISO_8601

### ISSUE THREAD

**Issue by danielmotaleite** [hashicorp/nomad#3806]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
debian stretch

### Issue
Date format is US format only, that is very confusing for everyone else and may cause bad decisions.
Date should be using locale, or even better, ISO_8601. This format causes no confusion, alllow easy sorting and everyone will understand it
https://en.wikipedia.org/wiki/ISO_8601

### Reproduction steps
```
$ nomad job history -p e | grep Date

Submit Date = 09/12/17 15:25:33 UTC
```

Is this `2017/09/12` or `2017/12/09` ? or even `2009/12/17?`
ISO would be `2017-09-12T15:25:33Z`

This makes everything clear for everyone, not just US people

**Comment by danielmotaleite** [comment]
nomad ui also have the same problem, by the way

**Comment by chelseakomlo** [comment]
Hi, thanks for opening this issue; we should move to use ISO_8601. 

We would take a PR for this, otherwise we will add this to our future backlog.
