### ISSUE TITLE
Docs use an unrelated domain for examples

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/nomad#3808]
The docs (or at least https://www.nomadproject.io/api/namespaces.html, but I'm assuming other pages) all use https://nomad.rocks as the default domain for API request examples. But if you go to nomad.rocks, it redirects to nomad.ca, which is a company that is not-HashiCorp and unrelated to (this) Nomad. Should we use https://demo.nomadproject.io instead?

**Comment by angrycub** [comment]
I'm not wed to localhost, but I thought it might be more durable in the long run.  I also think it might be more copy/paste friendly for people working examples locally.

**Comment by paddycarver** [comment]
#3809 is a solution I would've anticipated seeing or that would make more sense to me than the current state of affairs. I'd consider it a fine solution to the issue. But as I don't work on/contribute to Nomad, I'm more or less just commenting here to say "I'd be happy with this solution" :)
