### ISSUE TITLE
Add support for CPU hard limits

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3810]
Nomad currently imposes only CPU soft limits for tasks. Some workloads need users to specify hard limits so that a single task doesn't use up all the available CPU and render the machine useless.  

This should be an optional parameter so that existing behavior of using soft limits do not break.

**Comment by jippi** [comment]
Yes, 👍

**Comment by schmichael** [comment]
The current Linux implementation uses the `cpu.shares` cgroup parameter in all applicable drivers which applies a limit to the relative amount of cpu time a process can use, but allows bursting over that limit when there's idle cpu.

Using the `cpu.cfs_quota_us` cgroup parameter instead would allow setting a hard limit on the amount of CPU a process uses and can be computed to an equivalent number of `cpu.shares` to allow the scheduler to understand either parameter during scheduling. (eg if period=100ms, a limit of quota=10ms could be treated by the scheduler as the same as 10% of the node's compute)

I can think of two circumstances where the hard limit is desirable (please chime in with your use case!):
1. limit power usage on a per-application basis (cpu time being the closest approximation available for power usage -- at least until we have gpu support)
2. intolerable context switching latency when the kernel has allowed a low priority process to burst to full cpu capacity and a higher priority process needs time

So I think this feature makes sense and is mostly just plumbing through a new job spec parameter to flip between shares (current soft limit) or quotas (hard limit). Could be `cpu_hard_limit = true|false` or `cpu_ms = <quota in milliseconds>`.

Thoughts?

**Comment by diptanu** [comment]
@schmichael That's exactly what we are going to do. I am thinking of not breaking the current UX, since CPU Quota requires calculating the time interval etc we should calculate that on our own based on the total frequency available on the machine and the amount of shares user has asked for a task.

I was thinking to add a config flag in the docker driver's config since it's less work, but for the long term, wonder if it might go into the resource block? You should see a PR from @jaininshah9 soon.

And yes, the use cases you mentioned are on point. We can limit power by scaling down the base frequency for the entire machine but for (2), we need to be able to put hard limits.

**Comment by diptanu** [comment]
@schmichael The scheduler can still work with cpu shares, since we limit the total cpu shares of a machine as the total frequency available. So X shares can be translated to quotas on the client, since it knows the total shares Y of the node.

**Comment by schmichael** [comment]
@diptanu So you want to switch between hard & soft limiting on a per-client basis? Not a per-job basis?

Heterogeneous clusters (some client soft limiting, some hard) could lead to significantly different task performance based on which kind of node the task ended up on. Job operators would have to be careful to use a constraint to select the desired cpu mode.

I guess that might be best. Service class nodes could use hard limiting to meet latency SLAs while batch class nodes could use soft limiting to allow the highest possible job throughput.

I just want to make sure we cover the intended use cases properly!

**Comment by jippi** [comment]
I would really really prefer it per job level.

e.g. i want to be able to hard limit cpu for side cars to my jobs (telegraph, log forwarders etc), but let the leader task soft scale cpu. 

for smaller clusters, this mean basically doubling capacity. In our case we have: 

`balanced`, `high-cpu` and `high-memory` node classes, roughly matching the AWS families `m4`, `c4` and `r4`). We would have to double that to have `balanced-{soft|hard}` `high-cpu-{soft|hard}` and `high-memory-${soft|hard}`.

**Comment by shantanugadgil** [comment]
+1 for job level, not _exactly_ identical, but a similar use case.

**Comment by diptanu** [comment]
@schmichael I prefer to have this in the job spec. So this would be a configuration in the Task, and that should address @jippi's use case too, he can add a hard limit to his sidecar tasks but not limit the application task of the group. 

We could additionally have a client-side configuration too in the future(that should address your use case, and for @jippi's use case he would simply not enable this knob), where the operators can force hard limits on all the tasks running on a node, but I don't think we have time to implement that part right now.

**Comment by jippi** [comment]
@diptanu i think thats an excellent compromise. the nomad client thing could really just be a `meta` key that you as an operator could `constraint{}` on your self - so would mostly make for a UX experience with a client knob?

**Comment by diptanu** [comment]
Yeah, if (and when) there is a client-side configuration to hard cap all tasks running on a node it should be exposed as a meta key so that job operators can choose(or not) to place their allocation on such machines.
