### ISSUE TITLE
FileNotFoundException when running a java jar from nomad

### ISSUE THREAD

**Issue by cernerpradeep** [hashicorp/nomad#3815]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
### Operating system and Environment details
RHEL 6.8
### Issue
FileNotFoundException when jar runs from nomad
### Reproduction steps
I have a java jar, when I run it outside of nomad it works as expected. But when the same jar is run inside nomad it fails with filenotfound exception.
### Nomad Client logs (if appropriate)
Caused by: java.io.FileNotFoundException: /opt/opennms/etc/eventconf.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:113)
	at org.opennms.core.xml.JaxbUt
### Job file (if appropriate)

```
job "VertxLoadTest" {

  datacenters = ["dc1"]
  type = "service"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "SimpleConsumer" {
    count = 1

    restart {
      attempts = 1
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    task "SimpleKafka" {
      driver = "java"

      config {
        jar_path    = "tmp/vertxJars/SimpleKafka.jar"
        jvm_options = ["-Xmx512m"]
        args = ["syslog"]

      }

      artifact {
        source = "http://somerepo/vertxJars/SimpleKafka.jar"
        destination = "tmp/vertxJars/"
      }

    }

  }
  group "ParamsLoader" {
    count = 1

    restart {
      attempts = 1
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    task "Params" {
      driver = "java"

      config {
        jar_path    = "tmp/vertxJars/Params.jar"
        jvm_options = ["-Xmx512m"]
        args = ["true"]

      }

      artifact {
        source = "http://somerepo/vertxJars/Params.jar"
        destination = "tmp/vertxJars/"
      }

    }

  }
}
```

**Comment by chelseakomlo** [comment]
Hi, thanks for opening this issue. What are the permissions of the directory that is being read from? For reference, it is possible to specify the user that will run this task: https://www.nomadproject.io/docs/job-specification/task.html#user

**Comment by chelseakomlo** [comment]
Another possibility is that the file might not exist in the chroot. You can test this with the following command: 

`nomad fs <alloc> /opt/opennms/etc/eventconf.xml`

As mentioned on the Nomad mailing list, the java driver won't have access outside of the chroot environment. https://groups.google.com/forum/?#!msg/nomad-tool/g2UrA4OWbFo/4qO_igRcAQAJ

If you want access the host filesystem, you can use raw_exec. https://www.nomadproject.io/docs/drivers/raw_exec.html

Alternatively, you can use the chroot_env configuration to include necessary files. https://www.nomadproject.io/docs/agent/configuration/client.html#chroot_env

**Comment by cernerpradeep** [comment]
Thanks for response. When I changed the user to root. I get the below error
Recent Events:
Time                   Type               Description
01/31/18 04:15:21 CST  Alloc Unhealthy    Unhealthy because of failed task
01/31/18 04:15:21 CST  Failed Validation  running as user "root" is disallowed
01/31/18 04:15:21 CST  Received           Task received by client

**Comment by cernerpradeep** [comment]
I added the path in chroot_env stanza as mentioned in this https://www.nomadproject.io/docs/agent/configuration/client.html#chroot_env
@chelseakomlo Thanks so much for the help.
