### ISSUE TITLE
Network interfaces are not detected on Windows

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/nomad#382]
Nomad on Windows does not detect any network interfaces because the [network fingerprinter for Windows](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/network_windows.go) is not currently implemented.

Fortunately our [implementation for *nix](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/network_unix.go) was recently rewritten to use native go APIs that work cross platform. Yay!

*Un*fortunately the go 1.5 Windows implementation of `net.Interfaces()` has a bug that causes it to only show *some* of the interfaces on the host.

There is an open issue https://github.com/golang/go/issues/12301 and [patch](https://go-review.googlesource.com/#/c/14747/) that we may be able to include in Nomad to work around this.

Alternatively, we could parse the output from `ipconfig` and `nets`.

##### Some Possibilities

- [x] Merge the implementations for Windows and Linux network fingerprinting

  And one of:
  - [ ] Merge the CL 14747 into Nomad
  - [x] Wait for a golang release that fixes the problem

Or

- [ ] Implement an `ipconfig`/`netsh` parser

**Comment by ChrisHines** [comment]
https://github.com/golang/go/issues/12301 has been fixed in Go 1.5.2.
