### ISSUE TITLE
[question] Vault PKI cert fetch and inject on job run

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#3820]
I can see how I could dynamically setup a config file for a service in a container or drop extra files in place before a container starts via Nomad functionalities such as Consul Template and file copying but I can't see how to fetch an SSL from Vault's PKI endpoint, break up the result and write out crt and key files. Am I missing some trick? Or is this functionality not supported?

**Comment by shantanugadgil** [comment]
Why not just download crt and key separately? 🤔

**Comment by far-blue** [comment]
How do you do that?

I want to use this API call to Vault: https://www.vaultproject.io/api/secret/pki/index.html#generate-certificate

Note how the generated cert and private key are wrapped in a json response. As vault doesn't store the generated cert I can't see how I could make 2 calls to fetch each part.

**Comment by shantanugadgil** [comment]
Sorry, my bad, please ignore what I said.
I know very little about /using/ Vault, and I assumed you want to download secret stored in Vault.

**Comment by far-blue** [comment]
👍 np 😄

**Comment by Xopherus** [comment]
@far-blue here's how you would generate a pem bundle, not sure if that's an option for you. It's a bit easier because you only have to render one file with the template stanza. 

```
template {
  data = <<EOH
{{ with secret "pki/issue/foo" "common_name=foo.service.consul" "ip_sans=127.0.0.1" "format=pem" }}
{{ .Data.certificate }}
{{ .Data.issuing_ca }}
{{ .Data.private_key }}{{ end }}
EOH
  destination   = "$${NOMAD_SECRETS_DIR}/bundle.pem"
  change_mode   = "restart"
}
```

I would have to keep digging to figure out how to easily generate the cert and key separately.

**Comment by chelseakomlo** [comment]
Hi, thanks for this question. This feature would actually be in Consul Template, which unfortunately currently doesn't support this feature. See related thread: https://github.com/hashicorp/consul-template/issues/492. 

As a current workaround, you can write an init script to wrap your application that would do this work before the application is launched. 

In the future, Nomad will either support init tasks or DAGs, which would allow for precedence of actions. So stay tuned!

**Comment by far-blue** [comment]
@Xopherus thanks for that example - it's a good starting point and might work for some of my use cases where both the cert and key can be in the same pem :)

@chelseakomlo thanks for your suggestions - combining an init script with @Xopherus's suggested template might do the trick :) I'll also add my voice to the consul-template issue. 

I'd assumed it was more of a Nomad thing because of Nomad's direct integration with Vault for secrets :)
