### ISSUE TITLE
AWS network fingerprinter not right with new family

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/nomad#3827]
### Nomad version
0.7.1

### Issue
As per https://github.com/hashicorp/nomad/pull/1994/files/ba6473a5c788a52f515465673a53766fcd2000a8#diff-fa62573917c2ea35cf929a8f88b36f20, there were some regexes added for particular families of hosts to use particular fingerprinting for network speed.

These regexes don't really work correctly for the c5/m5 instances for two main reasons
* `*.9xlarge`, for example, isn't caught by the current regex, so you get the fallback of 1000Mbits which is way too low.
* The m5/c5 instances support much more bandwidth than their m4/c4 counterparts, so probably should have updated values that aren't `*.2xlarge` generic or whatever.

Not really sure what the right answer is to make this more future-proof, but at the very least, seems like the list should be updated to override for the new families.

**Comment by chelseakomlo** [comment]
Hi, thanks for reporting this issue and pointing out these cases. It would be good to think about how to make this future-proof, as you said. 

We have added this to our team's backlog, thanks again.
