### ISSUE TITLE
[UI] Don't show placement failures in UI if there currently aren't any

### ISSUE THREAD

**Issue by rkettelerij** [hashicorp/nomad#3828]
### Nomad version
Nomad v0.7.1

### Issue
Once a placement failure has occurred the 'placement failure error' will always stay visible in the UI, regardless if subsequent runs of that job succeed. Expected behaviour: The placement failure error should only be visible if a job is **currently** in a failed stage.

![screen shot 2018-02-02 at 08 36 43](https://user-images.githubusercontent.com/291572/35722202-a73ee732-07f5-11e8-864c-8c85598d3667.png)

### Reproduction steps
- Start with a clean UI (e.g. purge all existing jobs `nomad stop -purge myjob`)
- Deploy a job and cause a placement issue
- Verify the placement issue is visible in the UI
- Fix the placement issue, for example by adjusting the job and rerunning it
- Expected behaviour: the previous placement failure isn't visible in the UI
- Actual behaviour: the placement failure is still there.

**Comment by DingoEatingFuzz** [comment]
Thanks for filing this @rkettelerij! It's fixed in #3956 and will be released in 0.8.0.
