### ISSUE TITLE
nomad client `node-status` output inconsistent json

### ISSUE THREAD

**Issue by egidijus** [hashicorp/nomad#3832]
### Issue
I was trying to use some of nomad's tooling to get some statistics and metrics about cluster/node resource usage.

I was expecting to see a consistent, maybe parsable data on used/total resources.
I found that `nomad node-status` produces different data if you enable the JSON flag.

Nomad client human output for single node resources tell me what the current state is, but the same client is not able to produce useful data when json output is selected.

The nomad http api produces more useful structured data that can be parsed.

### Nomad version
* Nomad v0.7.1

### Operating system and Environment details
* CentOS Linux release 7.4
* AWS EC2 
* Job/task driver = docker

### Reproduction steps

Output is truncated:
*nomad client, node-status human output*
`nomad node-status -address=http://10.10.10.10:4646 -self | grep -A1 -i cpu`

```Allocated Resources

CPU Memory Disk IOPS

4570/10000 MHz 4.3 GiB/30 GiB 3.5 GiB/5.6 GiB 0/0



Allocation Resource Utilization

CPU Memory

154/10000 MHz 380 MiB/30 GiB



Host Resource Utilization

CPU Memory Disk

383/10000 MHz 4.5 GiB/30 GiB 2.3 GiB/8.0 GiB

```

*nomad client, node-status json output*
`nomad node-status -address=http://10.10.10.10:4646 -json -self | jq '.' | grep -A1 -i cpu`

``` "cpu.numcores": "4",

"driver.docker.version": "17.05.0-ce",

--

"cpu.arch": "amd64",

"vault.cluster_id": "dedededededededededeedededededededed",

--

"cpu.frequency": "2500",

"nomad.version": "0.7.1",

--

"cpu.totalcompute": "10000",

"os.signals": "SIGHUP,SIGTERM,SIGCHLD,SIGPIPE,SIGWINCH,SIGXFSZ,SIGIO,SIGILL,SIGKILL,SIGUSR2,SIGFPE,SIGIOT,SIGQUIT,SIGXCPU,SIGBUS,SIGINT,SIGSTOP,SIGSYS,SIGTTIN,SIGTTOU,SIGALRM,SIGSEGV,SIGTSTP,SIGABRT,SIGPROF,SIGTRAP,SIGURG,SIGUSR1,SIGCONT",

"cpu.modelname": "Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz",

"unique.hostname": "test-Nomad-10.10.10.10",

--

"CPU": 0,

"DiskMB": 0,

--

"CPU": 10000,

"DiskMB": 5785,

```

*nomad api, metrics json output*
`curl -s 10.10.10.10:4646/v1/metrics | jq '.' | grep -A1 -i cpu`

```

"Name": "nomad.client.allocated.cpu",

"Value": 4820

"Name": "nomad.client.unallocated.cpu",

"Value": 5180

```

**Comment by schmichael** [comment]
Ah, sorry for the confusion @egidijus.

The default output for a number of commands call multiple Nomad APIs to try to produce useful output. The `-json` forms call the core API and return just that data model. In this case `node-status -self -json` looks up the Node's ID and returns the output of https://www.nomadproject.io/api/nodes.html#read-node

For resource utilization you actually have to query the node directly using the Read Stats API: https://www.nomadproject.io/api/client.html

In the upcoming Nomad v0.8 release we're hoping to land a feature that will automatically route client-only APIs like `/v1/client/stats` to a specific Node from anywhere else in the cluster! That should simplify gathering stats a bit.

Feel free to reopen if I misunderstood or missed something!
