### ISSUE TITLE
Unable to delete alloc folders in nomad when nomad is corrupted

### ISSUE THREAD

**Issue by cernerpradeep** [hashicorp/nomad#3838]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
### Operating system and Environment details
RHEL 6.8
### Issue
Nomad is corrupted. On startup it asks to delete nomad/alloc folders but when we try to delete it stops with following error
Device or resource busy
rm: cannot remove Read-only file system
### Reproduction steps
Nomad is corrupted but its not allowing to delete the alloc folder

**Comment by angrycub** [comment]
You will need to manually unmount any mounted filesystems that did not get automatically unmounted since nomad crashed.  Once you unmount these folders, you should be able to delete the allocations without issue.

**Comment by schmichael** [comment]
@angrycub is correct. Running `mount | grep alloc` should show you the mounts you'll have to manually `umount`.

**Comment by cernerpradeep** [comment]
mount | grep alloc
Doesn't show anything.

**Comment by jippi** [comment]
`rm: cannot remove Read-only file system` is your local file system broken?

**Comment by cernerpradeep** [comment]
when I try to start nomad it says its corrupted.

**Comment by shantanugadgil** [comment]
What @jippi is hinting at is that the fs may an fsck?!
