### ISSUE TITLE
[improvement] nomad plan shows CPU needed vs CPU actually currently in use.

### ISSUE THREAD

**Issue by egidijus** [hashicorp/nomad#3848]
I think it might be useful to know.
When running `nomad plan` I have exhausted the CPU:
* Have I exhausted the reserved resources by the job configuration (my job is asking for more than is available across entire cluster/node).

OR 
* are the currently allocated job resources OK (job reservation is within limits of cluster), but the currently running jobs are using so much CPU that the plan fails?

This might be especially useful when using docker job driver, because docker driver does not have hard CPU limits.

**Comment by mikenomitch** [comment]
Going to close this as I haven't seen much confusion about this out in the wild. 

FWIW, when planning Nomad will only care about the allotted CPU requested by the config (not what is actually running at the time)
