### ISSUE TITLE
[question] HTTP Health Check – expect repsonse

### ISSUE THREAD

**Issue by hryamzik** [hashicorp/nomad#3857]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

As mention in [documentation](https://www.nomadproject.io/docs/job-specification/service.html#http-health-check) there's a way to define an http health check. However I didn't find a way to combine in with ES.

ES has a [health-check endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/cluster-health.html) that responds with the following `json` (some fields omitted):
```json
{
  "cluster_name" : "testcluster",
  "status" : "yellow",
}
```

1. Is there a way to check that `status` field?
2. How about rolling restarts (`max_parallel`), is there any way to proceed to next node once current one is `green`?

**Comment by atillamas** [comment]
>  Is there a way to check that status field?

You could use a script check instead where you curl -s localhost:9200/_cluster/health?pretty | grep status | grep green

> How about rolling restarts (max_parallel), is there any way to proceed to next node once current one is green?

Nomad will only continue with the rolling update when the healthcheck is green, https://www.nomadproject.io/docs/job-specification/update.html for documentation about the settings for this

**Comment by hryamzik** [comment]
Thanks @atillamas! Does it make any sense to create "feature idea" about direct json state support to avoid curl workaround?

**Comment by schmichael** [comment]
Hi @hryamzik,

@atillamas is right. A script check is the suggested way to accomplish this. Note that you can use script checks in Nomad even if you have them disabled in Consul as Nomad runs the scripts itself.

[Consul](https://www.consul.io/docs/agent/checks.html) recently added [gRPC Health Checks](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), and we intend to support that new check type soon. I would imagine Consul will add support for more standardized check types in the future, and Nomad will add support soon after.

Services that implement a custom health endpoint like Elasticsearch will probably always have to use a script check.

Hope that helps!
