### ISSUE TITLE
Possible memory leak in Nomad 0.7.1

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#3863]
### Nomad version

Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux nomad-server-i-0bfa25b1fb5e77b88 4.14.13-041413-generic #201801101001 SMP Wed Jan 10 10:02:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue

We've seen a steady increase of memory in our nomad-server instances, this happened when we switched from 0.7.0 from 0.7.1.

We haven't changed any workload / cluster size in the time since the switch, clients and servers has just been bumped from 0.7.0 to 0.7.1

Additionally we've seen CPU increase quite significantly from 0.7.0 to 0.7.1 (see below), with especially the nomad server raft leader cpu just ever-increasing in both CPU and memory.

### Implications

We had a complete cluster failure in our production environment yesterday since all our servers ran out of memory at the ~same time.

Current work-around for us is to double instance size and restart the servers once in a while to keep memory pressure down. 

### Observations

We have a different non-prod but larger cluster, running 100% same configuration (static AWS AMI) where we do not observe this behaviour. 

The only difference between the two environments is that the production cluster from pics below, is running frequent periodic jobs. I'm not sure if its related to #3862 ? 

#### Affected cluster memory usage for 2 months

_where the lines "break" is when we did the switch to 0.7.1_

![image](https://user-images.githubusercontent.com/22841/36091277-8c584530-0fe3-11e8-8735-d67f7b18af43.png)

#### Affected cluster CPU usage for 2 months

_where the lines "break" is when we did the switch to 0.7.1_

![image](https://user-images.githubusercontent.com/22841/36091506-44e6ea5c-0fe4-11e8-88ec-9dcb7f85672e.png)

### Server config file

Below is a sample nomad-server config file under 0.7.1

```json
{
  "addresses": {
    "http": "0.0.0.0",
    "rpc": "0.0.0.0",
    "serf": "0.0.0.0"
  },
  "advertise": {
    "http": "10.0.25.18:4646",
    "rpc": "10.0.25.18:4647",
    "serf": "10.0.25.18:4648"
  },
  "bind_addr": "0.0.0.0",
  "client": {
    "enabled": true,
    "max_kill_timeout": "300s",
    "meta": {
      "aws.instance.availability-zone": "us-east-1c",
      "aws.instance.family": "c4",
      "aws.instance.life-cycle": "normal",
      "aws.instance.region": "us-east-1",
      "aws.instance.region-short": "sg1",
      "aws.instance.root-device-type": "ebs",
      "aws.instance.stack-name": "production-nomad-server",
      "aws.instance.type": "c4.2xlarge"
    },
    "network_interface": "eth0",
    "node_class": "nomad-server",
    "options": {
      "docker.auth.config": "/root/.docker/config.json",
      "docker.cleanup.image.delay": "1h",
      "driver.raw_exec.enable": true
    },
    "reserved": {
      "cpu": 2000,
      "disk": 2048,
      "memory": 2048,
      "reserved_ports": "22,25,53,123,514,4646-4648,48484,49968,8200-8302,8400,8500,8600,8953"
    }
  },
  "consul": {
    "address": "127.0.0.1:8500",
    "client_auto_join": true,
    "client_service_name": "nomad-client",
    "server_auto_join": true,
    "server_service_name": "nomad"
  },
  "data_dir": "/var/lib/nomad",
  "datacenter": "us-east-1",
  "disable_update_check": true,
  "enable_syslog": true,
  "leave_on_interrupt": true,
  "leave_on_terminate": true,
  "log_level": "DEBUG",
  "name": "nomad-server-i-0bfa25b1fb5e77b88",
  "region": "production",
  "server": {
    "bootstrap_expect": 3,
    "enabled": true
  },
  "telemetry": {
    "datadog_address": "localhost:8125",
    "disable_hostname": true,
    "prometheus_metrics": true,
    "publish_allocation_metrics": true,
    "publish_node_metrics": true
  },
  "vault": {
    "address": "http://active.vault.service.consul:8200",
    "allow_unauthenticated": true,
    "create_from_role": "nomad-cluster",
    "enabled": true
  }
}
```

**Comment by preetapan** [comment]
@jippi will you be able to add enable_debug = true to the above config (at least on the leader) and then use the profiler to take a heap dump and goroutine dump? (available via /debug/pprof after enable_debug is set). That will help isolate the leak if there is any.  Would be helpful to get it on the leader and the other servers as well.

**Comment by jippi** [comment]
@preetapan will requesting `/debug/pprof` affect anything in a negative way - since this is production i want to run that knowing the impact

**Comment by preetapan** [comment]
Just adding `enable_debug` will not have any impact. Visiting /debug/pprof does initiate 30 seconds of CPU profiling. Since you would only do this once to save the results, it should not have any negative impact on production. However, leaving `enable_debug` on and slamming /debug/pprof several times a second, is not recommended. 

So to keep the impact minimal and take a conservative approach I would suggest the following steps:  

- Add the config, 
- visit the goroutine and heap links in /debug/prof and save results to a file 
- Remove the config and restart
-

**Comment by dadgar** [comment]
@jippi Can you also collect: `go tool pprof <path to nomad> http://127.0.0.1:4646/v1/debug/pprof/profile`

**Comment by jippi** [comment]
I haven't been able to reproduce the memory usage pattern since we bumped Consul to 1.0.6 

Consul fixed a lot of issues with state changing simply by reading data, causing blocking requests to unblock more frequently than they should have. I'm not sure if this has been the root cause.

Below is some core metrics for the last month, the cluster size / hardware / jobs / allocation count has been unchanged during the period - only change has been the version change in Consul from 1.0.2 to 1.0.6 

If there is a leak in nomad, my guess would be in consul-template logic, as that should have been the only thing being affected by the Consul version bump.

I also find it interesting that the Nomad eval dequeue was significantly higher during the memory leaking memory - I'm not familiar enough with Nomad to know if a eval dequeue is triggered by a consul-template unblocking or not.

![image](https://user-images.githubusercontent.com/22841/36471685-a8d88180-16ef-11e8-8d48-f64e07326451.png)

For the same time frame, number of consul raft changes went down significantly too

![image](https://user-images.githubusercontent.com/22841/36471860-45b80f34-16f0-11e8-98af-c8d848966a67.png)

A bit harder to see due to big spikes, but the number of RPC requests to Consul also halfed 

![image](https://user-images.githubusercontent.com/22841/36471890-5b68cbde-16f0-11e8-8740-3119cccaa917.png)

I still do believe there are something leaky, which is bound to the stability / consul-template re-render rate, but can't find any code / dumps to support it, only the charts above.

I'm going to close this issue as I can't reproduce the issue with Consul 1.0.6
