### ISSUE TITLE
Nomad not restarting task with failing health-check

### ISSUE THREAD

**Issue by atillamas** [hashicorp/nomad#3865]
If filing a bug please include the following:

### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
"Ubuntu 16.04.2 LTS"

### Issue
I'm running  1 instance of a service with the health check defined in nomad:
```
service {
    name = "some-service"
    tags = ["some-service"]
    port = "some_service_health_port"
    check {
        type     = "http"
        path     = "/healthcheck"
        interval = "5s"
        timeout  = "2s"
        port     = "some_service_health_port"
    }
```
nomad status on service:
```
Deployed
Task Group  Desired  Placed  Healthy  Unhealthy
service     1        1       1        0
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
ca8ec62b  d598340b  service     22       run      running  2h53m ago  2h51m ago
```

But in consul the health-check is marked as critical
```
service: "some-service" check 29e746303a88592700688f2153ef98be9c0e6b94 critical
NOTES
OUTPUT
HTTP GET http://10.0.11.251:23502/healthcheck: 500 Server Error Output: {"deadlocks":{"healthy":true},"some-service":{"healthy":true},"mysql":{"healthy":true},"supervisor":{"healthy":false,"message":"Supervisor has been inactive for too long!"}}
```
curling the endpoint from either server or client shows the same error:
```
curl -IL http://10.0.11.251:23502/healthcheck
HTTP/1.1 500 Server Error
Date: Tue, 13 Feb 2018 11:03:03 GMT
Content-Type: application/json
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 175

curl http://10.0.11.251:23502/healthcheck
{"deadlocks":{"healthy":true},"some-service":{"healthy":true},"mysql":{"healthy":true},"supervisor":{"healthy":false,"message":"Supervisor has been inactive for too long!"}}
```

**Comment by SoMuchToGrok** [comment]
What's the desired behavior - do you want the task to be killed entirely or do you want a restart attempt to be made? As far as I know, there's no way to accomplish the former (but someone please correct me if I'm wrong). 

https://www.nomadproject.io/docs/job-specification/check_restart.html

**Comment by atillamas** [comment]
@SoMuchToGrok 
Normally Nomad kills off the allocation and starts it again, this is the desired behavior and it is how it has been operating up until now.

**Comment by atillamas** [comment]
After adding the check_restart everything works as expected. I'll just close the issue.
