### ISSUE TITLE
job env changes dots to underscores

### ISSUE THREAD

**Issue by TheCase** [hashicorp/nomad#3880]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Nomad.hcl
```
job "envtest" {
  datacenters = [ "tec1" ]
  type = "service"

  group "test" {
    count = 1
    task "test" {
      driver = "docker"
      config {
        image = "nginx"
      }
      env {
        foo.bar = "foobar"
      }
      resources {
        cpu    = 100 # MHz
        memory = 100 # MB
        network { mbits = 100 }
      }
    }
  }
}
```

### Issue
dot character in environment variable name is replaced with an underscore

### Reproduction steps
inside docker container, note that dot has been replace with underscore:
```
# export
export foo_bar='foobar'
```

Use case; Elasticsearch container images can use environment variables with dots in the (ie. `discovery.zen.ping.unicast.hosts`)

Not a blocker, as I can use a template for configuration, but I would like to be able to use env values instead.

**Comment by shantanugadgil** [comment]
Possibly fixed as part of:
https://github.com/hashicorp/nomad/pull/3760

Also mentioned in the CHANGELOG.md

HTH,
Shantanu

**Comment by chelseakomlo** [comment]
Thanks for reporting this issue- as mentioned, see #3760. This fix will be included in our next release.
