### ISSUE TITLE
raw_exec causes significant CPU usage

### ISSUE THREAD

**Issue by maihde** [hashicorp/nomad#3881]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Linux - CentOS6 & Ubuntu 16.04

### Issue
When using the `raw_exec` driver the CPU usage of the executor (as reported by top) can reach 1%-7% per executor.  When looked at with finer granularity you can observe that the CPU usage spikes every five seconds due to the polling found in `executor.go`.

The amount of CPU usage is sensitive to both the total number of processes on the system and the total number of child processes under the executor.  As both of these increase the CPU increases, with the later having a greater effect than the former.

This CPU usage can be a significant amount of overhead on a system where multiple executors are running, especially when the task being managed spawns a significant number of child processes.

I understand that `exec` or `docker` would likely work around this issue, but for my particular use case I require `raw_exec`.

### Reproduction steps

1. Run nomad.
2. Launch a program with the 'raw_exec' driver; to make the issue easier to see I run a process that forks 100+ child processes.
3. Monitor CPU usage of the executor process.

### Investigation

I've started to look at improving the CPU usage based of measurements from the `perf` tool.  One source of significant CPU usage is the `process.Times()` method.  Under the hood this method calls `fillFromStat()` which does more than just extract the CPU times.  By rewriting the `process.Times()` method to only use the parts of the code relevant for the cpuTimes structure I was able to reduce the overall CPU usage of the executor considerably.

I've also attempted to reduce the extra calls `NewProcess` by storing the result in the nomad pids structure instead of calling it every time through `pidStats()`.

I'm going to keep working on this and will probably make a pull-request, but I wanted to get feedback on this issue before going much further.

**Comment by maihde** [comment]
Here are the results of some simple benchmarking using [application](https://gist.github.com/maihde/30cacbc40003f6c59f625e6c0f901cb3).

Using `32a44bd` of `github.com/shirou/gopsutil` on a system with ~700 processes running the CPU usage measured by top would be about 2.3%.  The `pprof` shows this

```
(pprof) top20 -cum
Showing nodes accounting for 160ms, 39.02% of 410ms total
Showing top 20 nodes out of 111
      flat  flat%   sum%        cum   cum%
         0     0%     0%      370ms 90.24%  main.main /home/mihde/go/src/github.com/maihde/gopsutil_benchmark/gopsutil_benchmark.go
         0     0%     0%      370ms 90.24%  runtime.main /usr/lib/go-1.9/src/runtime/proc.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).Times /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).TimesWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).fillFromStat /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).fillFromStatWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).fillFromTIDStat /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      280ms 68.29%  github.com/shirou/gopsutil/process.(*Process).fillFromTIDStatWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%      250ms 60.98%  github.com/shirou/gopsutil/process.getTerminalMap /home/mihde/go/src/github.com/shirou/gopsutil/process/process_posix.go
     110ms 26.83% 26.83%      130ms 31.71%  syscall.Syscall /usr/lib/go-1.9/src/syscall/asm_linux_amd64.s
         0     0% 26.83%       90ms 21.95%  os.(*File).Readdirnames /usr/lib/go-1.9/src/os/dir.go
         0     0% 26.83%       90ms 21.95%  os.(*File).readdirnames /usr/lib/go-1.9/src/os/dir_unix.go
         0     0% 26.83%       70ms 17.07%  golang.org/x/sys/unix.Stat /home/mihde/go/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go
         0     0% 26.83%       70ms 17.07%  io/ioutil.ReadFile /usr/lib/go-1.9/src/io/ioutil/ioutil.go
         0     0% 26.83%       60ms 14.63%  io/ioutil.readAll /usr/lib/go-1.9/src/io/ioutil/ioutil.go
      30ms  7.32% 34.15%       60ms 14.63%  runtime.mallocgc /usr/lib/go-1.9/src/runtime/malloc.go
         0     0% 34.15%       60ms 14.63%  runtime.systemstack /usr/lib/go-1.9/src/runtime/asm_amd64.s
      10ms  2.44% 36.59%       60ms 14.63%  syscall.ParseDirent /usr/lib/go-1.9/src/syscall/dirent.go
         0     0% 36.59%       50ms 12.20%  bytes.(*Buffer).ReadFrom /usr/lib/go-1.9/src/bytes/buffer.go
      10ms  2.44% 39.02%       50ms 12.20%  runtime.slicebytetostring /usr/lib/go-1.9/src/runtime/string.go
```

The `getTerminalMap()` is using a substantial amount of the CPU time (250ms), even though `process.Times()` throws that result away.  By removing the call to `getTerminalMap()` performance improves considerably.

When measured with `top` the cpu usage rarely budges about 0.7% and the total cumulative CPU time drops from 370ms to 90ms.

```
(pprof) top20 -cum
Showing nodes accounting for 50ms, 50.00% of 100ms total
Showing top 20 nodes out of 40
      flat  flat%   sum%        cum   cum%
         0     0%     0%       90ms 90.00%  main.main /home/mihde/go/src/github.com/maihde/gopsutil_benchmark/gopsutil_benchmark.go
         0     0%     0%       90ms 90.00%  runtime.main /usr/lib/go-1.9/src/runtime/proc.go
         0     0%     0%       80ms 80.00%  io/ioutil.ReadFile /usr/lib/go-1.9/src/io/ioutil/ioutil.go
         0     0%     0%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).Times /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).TimesWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).fillFromStat /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).fillFromStatWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0%     0%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).fillFromTIDStat /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
      10ms 10.00% 10.00%       50ms 50.00%  github.com/shirou/gopsutil/process.(*Process).fillFromTIDStatWithContext /home/mihde/go/src/github.com/shirou/gopsutil/process/process_linux.go
         0     0% 10.00%       40ms 40.00%  os.Open /usr/lib/go-1.9/src/os/file.go
         0     0% 10.00%       40ms 40.00%  os.OpenFile /usr/lib/go-1.9/src/os/file_unix.go
         0     0% 10.00%       40ms 40.00%  syscall.Open /usr/lib/go-1.9/src/syscall/syscall_linux.go
      40ms 40.00% 50.00%       40ms 40.00%  syscall.Syscall6 /usr/lib/go-1.9/src/syscall/asm_linux_amd64.s
         0     0% 50.00%       40ms 40.00%  syscall.openat /usr/lib/go-1.9/src/syscall/zsyscall_linux_amd64.go
         0     0% 50.00%       30ms 30.00%  bytes.(*Buffer).ReadFrom /usr/lib/go-1.9/src/bytes/buffer.go
         0     0% 50.00%       30ms 30.00%  github.com/mitchellh/go-ps.(*UnixProcess).Refresh /home/mihde/go/src/github.com/mitchellh/go-ps/process_linux.go
         0     0% 50.00%       30ms 30.00%  github.com/mitchellh/go-ps.Processes /home/mihde/go/src/github.com/mitchellh/go-ps/process.go
         0     0% 50.00%       30ms 30.00%  github.com/mitchellh/go-ps.newUnixProcess /home/mihde/go/src/github.com/mitchellh/go-ps/process_unix.go
         0     0% 50.00%       30ms 30.00%  github.com/mitchellh/go-ps.processes /home/mihde/go/src/github.com/mitchellh/go-ps/process_unix.go
         0     0% 50.00%       30ms 30.00%  io/ioutil.readAll /usr/lib/go-1.9/src/io/ioutil/ioutil.go
```

My suggestion would be to remove the `getTerminalMap()` call from `fillFromStat()` and then alter the `process.Terminal()` method to look like this:

```go
// Terminal returns a terminal which is associated with the process.
func (p *Process) Terminal() (string, error) {
        t, _, _, _, _, err := p.fillFromStat()
        termmap, err := getTerminalMap()
        terminal := ""
        if err == nil {
                terminal = termmap[t]
        } else {
                return "", err
        }
        return terminal, nil
}
```

This way the performance penalty associated with `getTerminalMap()` only occurs when the terminal is actually requested.

A smaller amount (but still significant) amount of overhead is contributed by the `go-ps.newUnixProcess()` call.  This calls the `Refresh` method which also needs to read `/proc/{pid}/stat` so there might be an opportunity to continue to optimise by changing the executor a bit....more to follow.

**Comment by chelseakomlo** [comment]
Thanks for reporting this issue- this PR should be made against gopsutil as mentioned in [this](https://github.com/shirou/gopsutil/issues/492) issue. We can update Nomad's dependency on gopsutil once that is merged in.

**Comment by maihde** [comment]
I just made a PR to gopsutil.  Thanks for the feedback!

**Comment by chelseakomlo** [comment]
Sounds great, feel free to let us know when that merges and we'll update on our end. Thanks again!

**Comment by nugend** [comment]
@chelseakomlo shirou has merged https://github.com/shirou/gopsutil/pull/493
