### ISSUE TITLE
Batch metrics

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#3894]
Hi,
Running nomad 0.7.1 with all metrics enabled and I would like to collect metrics regarding batch jobs, but there only seems to be a summary of metrics on the nomad hosts, or allocation metrics for currently running jobs.

Ideally batch jobs would publish at least run count and failed runs to a job specific metric per host.

nomad status on an executed batch job shows exactly what I would like to scrape:

```
Summary
Task Group         Queued  Starting  Running  Failed  Complete  Lost
my-batch                  0       0         0        0       1         0
```

On the job endpoint the data is available as well obviously,

Right now were thinking about querying the API and push the data to a text file for scraping by prometheus node exporter.

Perhaps these metrics could be published by nomad on the metrics endpoint?

**Comment by chelseakomlo** [comment]
Hi, thanks for the request. These should already be enabled, look for the metric name `nomad.nomad.job_summary`. Let us know if you had something else in mind; we can improve our [telemetry documentation ](https://www.nomadproject.io/docs/agent/telemetry.html)to reflect this as well.

**Comment by rickardrosen** [comment]
Couldn't find them in the docs and for some reason my eyes didn't pick them up when browsing the prometheus data.

Non the less, they are there and all is good.

Thanks!

**Comment by chelseakomlo** [comment]
Thanks! We will be sure to add these to our docs as well.
