### ISSUE TITLE
Feature request: support bhyve driver

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [hashicorp/nomad#3895]
There's working a [qemu driver](https://www.nomadproject.io/docs/drivers/qemu.html). Given that nomad aims to be platform agnostic it would be nice to have a similar driver for bhyve (The FreeBSD hypervisor).

Links to manuals:
  * [bhyve(8)](https://www.freebsd.org/cgi/man.cgi?query=bhyve&sektion=8&apropos=0&manpath=FreeBSD+11.0-RELEASE)
  * [bhyvectl(8)](https://www.freebsd.org/cgi/man.cgi?query=bhyvectl&apropos=0&sektion=8&manpath=FreeBSD+11.0-RELEASE&arch=default&format=html)

**Comment by mateuszkwiatkowski** [comment]
There's also a GSoC project about integrating QEMU with FreeBSD's libvmm. It should be tracked and this issue could be closed if it succeeded (Integrate QEMU and libvmm at https://wiki.freebsd.org/SummerOfCodeIdeas).

**Comment by chelseakomlo** [comment]
Hi, thanks for the feature request. 

We are planning to move to a plugin architecture for drivers in the near future, meaning that new drivers such as bhyve will be able to be developed and maintained externally. See this issue for more detail: https://github.com/hashicorp/nomad/issues/3463
