### ISSUE TITLE
Add allocation ids to rkt log lines

### ISSUE THREAD

**Issue by chelseakomlo** [hashicorp/nomad#3900]
In looking at rkt logs, it will be helpful to correlate specific rkt logs with an allocation.

**Comment by chelseakomlo** [comment]
Added in https://github.com/hashicorp/nomad/pull/4044

**Comment by chelseakomlo** [comment]
The UUID in #4044 is the rkt UUID, this task is still outstanding.

**Comment by tgross** [comment]
Going to close this issue. Our [rkt](https://github.com/hashicorp/nomad-driver-rkt) driver is deprecated and will receive no new features.
