### ISSUE TITLE
Not able to update the job through REST call

### ISSUE THREAD

**Issue by pk015603** [hashicorp/nomad#3904]
Am trying to create/update job details through the REST API,... 
1. First i started the nomad with normal CLI with following job configuration.
```
  job "VertxLoadTest" {
    datacenters = ["dc1"]
    type = "service"

    update {
      stagger = "10s"
      max_parallel = 1
    }

   group "SimpleConsumer" {
      count = 1
      restart {
        attempts = 1
        interval = "5m"
        delay = "25s"
        mode = "delay"
      }

      task "SimpleKafka" {
         driver = "java"
         user = "root"
        config {
          jar_path    = "tmp/vertxJars/SimpleKafka.jar"
          jvm_options = ["-Xmx512m","-Xms256m"]
          #args = ["syslogd"]

        }

        artifact {
          source = "http://x.x.x.x./vertxJars/SimpleKafka.jar"
          destination = "tmp/vertxJars/"
        }
resources {
              cpu    = 1400
              memory = 2500

              network {
              }
            }

      }
  }

        group "ParamsLoader" {
          count = 10
          restart {
            attempts = 1
            interval = "5m"
            delay = "25s"
            mode = "delay"
          }

          task "Params" {
            driver = "java"
            user = "root"
            config {
              jar_path    = "tmp/vertxJars/Params1.jar"
              jvm_options = ["-Xmx512m"]
              #args = ["true"]

            }

            artifact {
              source = "http://x.x.x.x/vertxJars/Params1.jar"
              destination = "tmp/vertxJars/"
            }

           resources {
              cpu    = 1000
              memory = 600

              network {
		mbits = 500
              }
            }

          }

          }
  }
```
2. It successfully ran.
3. I tried to scale up the number of instances of a ParamsLoader from 10 to 15.
 - First i ran the plan command with body as : http://x.x.x.x:4646/v1/job/VertxLoadTest/plan
```
       {
    "Job": {
    "ID": "VertxLoadTest",
    "EnforceIndex": true,
  "JobModifyIndex": 290737,
    "Datacenters": ["dc1"],
    "type": "service",    

        "TaskGroups": [{
          "Name": "ParamsLoader",
            "count": 15,
            "Restart": {
                "Attempts": 1,
                "Interval": "5m",
                "Delay": "25s",
                "Mode": "delay"
              },
            
            "Tasks": [{
            
                "Name": "Params",
                "Driver": "java",
                "user": "root"
               

          }]
        }]
  }
 }
```

 - It gave me an index:
```
     {
    "Annotations": {
        "DesiredTGUpdates": {
            "ParamsLoader": {
                "Ignore": 0,
                "Place": 15,
                "Migrate": 0,
                "Stop": 0,
                "InPlaceUpdate": 0,
                "DestructiveUpdate": 0,
                "Canary": 0
            }
        }
    },
    "FailedTGAllocs": null,
    "JobModifyIndex": 290745,
    "CreatedEvals": null,
    "Diff": null,
    "NextPeriodicLaunch": "0001-01-01T00:00:00Z",
    "Warnings": "",
    "Index": 290745
}
```

4. And then i ran the update command with latest index (290745) for the property 'JobModifyIndex': http://x.x.x.x:4646/v1/job/VertxLoadTest/

5. It also ran successfully. But if i looked at the log file it has the following error:
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar
Error: Unable to access jarfile tmp/vertxJars/Params.jar

Note: If i perform the same with CLI it works without any issues.
Any help will be appreciated.
Thanks!!!

_Edited: added formatting_ -- @schmichael

**Comment by schmichael** [comment]
Hi @pk015603,

Sorry you ran into this issue. I've been unable to duplicate it locally by submitting the example job with count=3 (from `nomad init`), getting its JSON, increasing its count to 5, planning, and submitting the job update with the plan's `JobModifyIndex`.

I'm a little confused by step 5. Did the updated job run correctly or not? The output of `nomad status VertxLoadTest` would be useful to see.

Can you use the `nomad fs` commands to see if the `Params.jar` artifact was correctly downloaded? Are there any more details in Nomad's internal executor log? You can see it with `nomad fs $ALLOCID $TASK_NAME/executor.out` and it sometimes contains useful debugging information when tasks fail to start.

Can you look at one of the client's logs around the time updated job would have been starting? That may contain useful debugging information as well.

**Comment by pk015603** [comment]
Hi @schmichael , Please find the log details from one of client,

2018/02/27 06:55:22.148023 [DEBUG] executor: launching command /usr/java/jdk1.8.0_152/jre/bin/java -Xmx512m -jar tmp/vertxJars/Params.jar

2018/02/27 06:55:22.148073 [DEBUG] executor: running command as root

2018/02/27 06:55:22.148685 [DEBUG] executor: running as user:group 0:0 with group membership in [0 0]

2018/02/27 06:55:38.398833 [DEBUG] executor: launching command /usr/java/jdk1.8.0_152/jre/bin/java -Xmx512m -jar tmp/vertxJars/Params.jar

2018/02/27 06:55:38.398896 [DEBUG] executor: running command as root

2018/02/27 06:55:38.399536 [DEBUG] executor: running as user:group 0:0 with group membership in [0 0]

2018/02/27 06:55:54.602713 [DEBUG] executor: launching command /usr/java/jdk1.8.0_152/jre/bin/java -Xmx512m -jar tmp/vertxJars/Params.jar

2018/02/27 06:55:54.602757 [DEBUG] executor: running command as root

2018/02/27 06:55:54.603491 [DEBUG] executor: running as user:group 0:0 with group membership in [0 0]

2018/02/27 06:56:18.760707 [DEBUG] executor: launching command /usr/java/jdk1.8.0_152/jre/bin/java -Xmx512m -jar tmp/vertxJars/Params.jar

2018/02/27 06:56:18.760756 [DEBUG] executor: running command as root

2018/02/27 06:56:18.761427 [DEBUG] executor: running as user:group 0:0 with group membership in [0 0]

**Comment by pk015603** [comment]
Hi @schmichael , i got it working there was a syntax mistake after planning i used to put the 'JobModifyIndex' inside the Job tag, i just moved it outside and it worked. But the errors it showed like unable download the jars are little misguiding.

Thanks for your time and effort.
