### ISSUE TITLE
[question] Configure unique Vault cluster per DC

### ISSUE THREAD

**Issue by artyomturkin** [hashicorp/nomad#3913]
### Nomad version
Nomad v0.7.1

#### Operating systems:
- Ubuntu 16.04 LTS
- Windows Server 2016 (some of Nomad clients)

#### Setup:
One nomad region spread across 3 DC (DC1, DC2, HQ). HQ datacenter is only used to make majority in case one of the DC1 and DC2 goes down or there is a network outage in one of them. DC1 and DC2 both have 2 Nomad servers and HQ has only one. HQ cluster does not contain nomad clients.

Each DC has its own Consul datacenter setup, linked via WAN to other DCs.

Vault clusters will be setup in DC1 and DC2. No Vault Enterprise replication will be setup (OSS version only). Secrets will be replicated manualy when required.

Nomad clients and servers should only access Vault in the same DC.

```
 DC1   ---    HQ   ---  DC2
Nomad1 ---  Nomad0 --- Nomad2
Vault1 ---         --- Vault2
```

### Questions
1. Is it possible to run Nomad in this setup? If OSS versions of Nomad and Vault can not, would it be possible with paid versions?
2. Should vault tokens (from Vault in the same DC) be provided to Nomad servers only, or should they be also provided to clients? Should Nomad0 (HQ) also get a token?

**Comment by chelseakomlo** [comment]
Thanks for the question. A couple questions beforehand: 
1. Do these DCs have reliable low-latency connections or are they significantly geographically separated?
2. Is there any specific decision for manual replication amongst Vault servers beyond staying with Vault OSS?

**Comment by ArtyomTurkin** [comment]
1. DCs are connected with fiber optics in a mesh pattern in a single city. Usual latency is below 1ms. The highest latency is about 7ms.
2.1. OSS is one of the main reasons, it would be much easier to push through the budgeting commitee. When it shows its value, then it would not be hard to convince them to get Enterprise version.
2.2. The other one is that not all secrets should be stored in both DC (HQ DC shouldn't have any secrets as there won't be any jobs there except general metrics and log collectors) and some secrets should have the same path in both DCs, but different values.

In fact we are considering to split DCs into virtual sub DCs to fulfill some of the security requirments connected with PCI-DSS (both DCs even have separate physical zones for servers in PCI-DSS zone).

**Comment by chelseakomlo** [comment]
Hi, we discussed this as a team, and here is a bit more information. 

For your first question- it is not currently possible to run Nomad with this setup. In the future, it will be possible to run Nomad with a vault cluster per DC, but this will be an enterprise feature. Currently, it is required that all Nomad client/servers within a region are able to reach the same Vault cluster. 

For the second question, yes, vault tokens need to be provided to all Nomad servers. See documentation here: https://www.nomadproject.io/docs/vault-integration/index.html#vault-configuration

Apologies we don't have this feature currently- let us know how else we can help.

**Comment by chelseakomlo** [comment]
Apologies, to clarify- using a unique Vault cluster per DC will be an OSS feature, setting this per namespace will be an enterprise feature.

**Comment by dray92** [comment]
@chelseakomlo Will OSS also have support for eventual consistency between clusters running per DC?
