### ISSUE TITLE
[question] micro services dropped from zookeeper cluster - with Nomad when load increases 

### ISSUE THREAD

**Issue by cernerpradeep** [hashicorp/nomad#3914]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
### Operating system and Environment details
RHEL 6.8
### Issue
While doing load test with Nomad we discovered an issue. 

We have vertx micro services that are managed via nomad. The micro services are clustered with zookeeper. When the load increase some of the micro services drops off but the process still continues to run so nomad doesn't have chance to restart the process. This happens only when running with nomad and not otherwise.

This happens because the allocated resources gets exhausted but this is not expected. When there is high load the processing should be slow but with nomad the member is removed. 

Is there a way to get notified or restart the process or even avoid member drop?
### Reproduction steps
NA
### Nomad Server logs (if appropriate)
NA
### Nomad Client logs (if appropriate)
NA
### Job file (if appropriate)

```
  job "VertxLoadTest" {

    datacenters = ["dc1"]
    type = "service"

    update {
      stagger = "10s"
      max_parallel = 1
    }

   group "SimpleConsumer" {
      count = 1

      restart {
        attempts = 1
        interval = "5m"
        delay = "25s"
        mode = "delay"
      }

      task "SimpleKafka" {
         driver = "java"
         user = "root"
        config {
          jar_path    = "tmp/vertxJars/SimpleKafka.jar"
          jvm_options = ["-Xmx512m","-Xms256m"]
          #args = ["syslogd"]

        }

        artifact {
          source = "http://xxx/vertxJars/SimpleKafka.jar"
          destination = "tmp/vertxJars/"
        }
resources {
              cpu    = 1400
              memory = 2500

              network {
              }
            }

      }
  }

        group "ParamsLoader" {
          count = 56

          restart {
            attempts = 1
            interval = "5m"
            delay = "25s"
            mode = "delay"
          }

          task "Params" {
            driver = "java"
            user = "root"
            config {
              jar_path    = "tmp/vertxJars/Params1.jar"
              jvm_options = ["-Xmx512m"]
              #args = ["true"]

            }

            artifact {
              source = "http://xxxx/vertxJars/Params1.jar"
              destination = "tmp/vertxJars/"
            }

           resources {
              cpu    = 1000
              memory = 600

              network {
		mbits = 500
              }
            }

          }

          }


  }
```

**Comment by dadgar** [comment]
Hey,

In the future please prefer our mailing list for questions. You should check if the tasks are being given enough CPU resources by running `nomad alloc-status <alloc-id>` and checking what the reported CPU is. You likely just need to reserve more CPU for the workers that are dropping out of Zookeeper.

This is an application level problem so I suggest you enable higher level of logging in Vertx and determine the root cause that way.

**Comment by cernerpradeep** [comment]
@dadgar Thanks for your response. But this issue happens only with nomad and not otherwise.
