### ISSUE TITLE
CPU hard limit in Nomad - Fix

### ISSUE THREAD

**Issue by jaininshah9** [hashicorp/nomad#3915]
2 weeks ago, I created a PR which allows users to pass a flag via which you can enable cpu_hard_limit. 

PR: https://github.com/hashicorp/nomad/pull/3825

At that time, the change looked good to me and it was merged into master.

We added this commit in our Nomad version we have running and found out that it is not working as expected. The CPU usage gets constraint and never uses the full capacity. 

### Reproduction steps
1. Run nomad in a multi-core (4 or 8) system and try to add a task that requires 200% CPU. Ideally, you should be able to create that, but currently, you cannot do that. 

We have identified a fix for this

### Fix:
Below is the change we need in the formula for calculating the CPUQuota to fix that issue. 
<img width="724" alt="screen shot 2018-02-27 at 12 04 06 pm" src="https://user-images.githubusercontent.com/7143248/36751894-61fa144c-1bb6-11e8-8dfc-ac4056459cf6.png">

With the fix, if we have a 16 CPU @ 2.7 GHz and want to add multiple tasks which use 100% CPU, 200%, CPU, 400% CPU and 50% CPU, we make the CPU value as below:

100% CPU - 2700
200% CPU - 5400
400 CPU - 10800
50% CPU - 1350

### Nomad version
master branch

### Operating system and Environment details
Linux - Ubuntu and Centos

Thought??

**Comment by jaininshah9** [comment]
cc: @schmichael @diptanu

**Comment by jaininshah9** [comment]
Here is the doc for cpu resources:
Ref link: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu

the cpu.cfs_period_us
> Note that the quota and period parameters operate on a CPU basis. To allow a process to fully utilize two CPUs, for example, set cpu.cfs_quota_us to 200000 and cpu.cfs_period_us to 100000.

**Comment by schmichael** [comment]
Thanks again @jaininshah9 !
