### ISSUE TITLE
[Question] How Do We Dynamically Update Job Specification Files?

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#3916]
We are using Nomad for job dispatching as part of a data processing pipeline. Our infrastructure is managed with Terraform and deployed from a continuous integration/deployment system. So, as part of initialization, we run lots of lines like `nomad run -address http://$HOST_IP:4646 workers/foo_processor.nomad`

Now, as we are making optimization tweaks to our pipeline, we need to update these files. 

What is the recommended way of going about doing this from CI/CD? We can't use a Terraform `file` provisioner since the resource is already created. The CI system cannot access the remote Nomad server, which is in a private network.

We have toyed around with the idea of running a demon on the Nomad server which watches for changes on S3-hosted `.nomad` files, but this seems awfully hacky. 

I have also discovered that we can [define Nomad jobs](https://www.terraform.io/docs/providers/nomad/r/job.html) in our Terraform description, but I don't know what the behavior is: will it kill any running jobs with that name? Will it wait for them to finish, then create the new definitions? Will it not create them at all, since it's already defined? Will it create both at the same time? This is undocumented.

So I guess my question is - what's the best practice here? I have not been able to find any documentation for this scenario, which I'm sure must be a common one.

If this is not possible, my preferred interaction would be a `--watch-for-changes` option to `nomad run` which would update jobs when the jobspec changes, and to allow for `s3://` resources in `nomad run`. Another option would be to allow us to define update behavior in the Terraform `nomad_job` class - or at least have this in the documentation.

**Comment by shantanugadgil** [comment]
Two things come to mind: (I haven't tried either, just read about them)

Terraformed (Nomad Provider) would probably work for your use case.
I believe Terraform will end up doing what would happen when you manually update the .nomad file and issue a `nomad run` on the new file.

Secondly:
https://github.com/jrasell/levant/blob/master/README.md

HTH,
Regards,
Shantanu

**Comment by Miserlou** [comment]
The problem with using the Terraform nomad provider is we use an external CD that can't access specific machines. The provider requires that you can access the address of the nomad server.

I have looked at Levant, but don't see the capability I am looking for.

Still, really just looking for a best practices answer here.

**Comment by chelseakomlo** [comment]
Hi, thanks for the question. Nomad doesn't support dynamically updating the full job specification, but the job spec does have a template stanza which may be helpful: https://www.nomadproject.io/docs/job-specification/template.html

As mentioned, Levant is a good option as well. If there is a use case that Levant doesn't capture that we should keep in mind, do let us know.

**Comment by liyuzhu1984** [comment]
https://github.com/hashicorp/consul-template
