### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by samsalisbury** [hashicorp/nomad#3930]
**Nomad version:** dev build of a17690ce6f73b51a6e7e7bdfc4b7fa6189f64bfa 
**Environment:** `vagrant up` on the same commit.

I just ran `make test-nomad` 25 times using a script (see #3929), then grepped out all the `--- FAIL:` lines from the logs. We can see that `TestJobStatusCommand_Run` failed on 14/25 test runs, and a handful of other tests failed much less frequently. This makes it difficult to trust the tests when making changes.

Turning on the race detector throws up a large quantity of data races which may or may not be relevant, but may be good to eliminate them first to see if that helps.

Here's what I grepped out of the 25 `make test-nomad` logs...
```
--- FAIL: TestAPI_OperatorAutopilotServerHealth (3.85s)
--- FAIL: TestAutopilot_RollingUpdate (2.26s)
--- FAIL: TestJobStatusCommand_Run (3.58s)
--- FAIL: TestJobStatusCommand_Run (3.62s)
--- FAIL: TestJobStatusCommand_Run (3.62s)
--- FAIL: TestPrettyTimeDiff (0.00s)
--- FAIL: TestJobStatusCommand_Run (3.59s)
--- FAIL: TestServer_HeartbeatTTL_Failover (0.05s)
--- FAIL: TestJobStatusCommand_Run (4.59s)
--- FAIL: TestJobStatusCommand_Run (3.58s)
--- FAIL: TestJobStatusCommand_Run (4.56s)
--- FAIL: TestJobStatusCommand_Run (4.61s)
--- FAIL: TestAutopilot_CleanupDeadServer (2.53s)
--- FAIL: TestJobStatusCommand_Run (4.64s)
--- FAIL: TestJobStatusCommand_Run (4.57s)
--- FAIL: TestJobStatusCommand_Run (4.56s)
--- FAIL: TestJobStatusCommand_Run (3.61s)
--- FAIL: TestJobStatusCommand_Run (3.59s)
--- FAIL: TestJobStatusCommand_Run (3.58s)
```

**Comment by chelseakomlo** [comment]
Thanks for reporting this- as a lot of our tests are integration tests, it is easy for flakiness to creep in, but we definitely appreciate reporting these and will look further into this. `TestJobStatusCommand_Run` looks particularly egregius
