### ISSUE TITLE
Nomad how to install on centos!

### ISSUE THREAD

**Issue by jiuli** [hashicorp/nomad#3934]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

**Comment by shantanugadgil** [comment]
Is there a question in there somewhere? What all have you tried so far?
Using the Nomad binary and a systemd service script, it is very easy to setup Nomad (and Consul 😉) on CentOS

**Comment by preetapan** [comment]
@jiuli Our[ releases page](https://releases.hashicorp.com/nomad/0.7.1/) has binaries for various architectures. Like @shantanugadgil points out, you can use the nomad binary and there is no special Centros installation step. Our [getting started|https://www.nomadproject.io/intro/getting-started/running.html] also has some information on starting Nomad agents.

Also please use the mailing list for questions, Github is for bugs or feature requests.

**Comment by shantanugadgil** [comment]
do let me know if these help:
https://github.com/shantanugadgil/hashistack/tree/master/scripts/systemd/
