### ISSUE TITLE
POST to /acl/bootstrap is allowed by default

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/nomad#3940]
### Nomad version
0.7.1

### Issue
When a cluster starts with acl set to true, access is denied to all api except `/ac/bootstrap`

This makes bootstrapping process insecure since anybody can access /acl/bootstrap and get management token.

It wouldn't be a problem if the initial key can be setup in the config.

**Comment by preetapan** [comment]
@roman-cnd storing a master token in a config file is another vector for leaking it to anyone that can read the config directory, and its storing a token in plain text. With our current mechanism you can only bootstrap once, if the bootstrap master token was leaked you can reset it https://www.nomadproject.io/guides/acl.html#reseting-acl-bootstrap

**Comment by roman-cnd** [comment]
The root key is stored in data/server/raft/raft.db unencrypted. There is also no need to store anything when cluster is bootstrap, automation can read a key from somewhere.

Vault unsealing workflow or even consul special keys look easier to automate and more secure. Those options look better than open API endpoint to set it up.

**Comment by preetapan** [comment]
It is an open endpoint that the operator must use right after enabling ACLS, and do so exactly once before the Nomad cluster can offer any more security guarantees. 

Even with Vault unsealing, the set of unseal keys are logged to the operator first, which again per your definition "anyone can see".  I am not sure what you mean by special Consul keys. With any option when you first install Nomad some initial set of steps must be taken to bootstrap it for ACLs.

**Comment by roman-cnd** [comment]
I meant this sort of tokens in Consul: https://www.consul.io/docs/agent/options.html#acl_master_token

We're bootstrapping clusters with automation, so if "operator must use (endpoint) right after enabling ACLS", the automation workflow becomes more complicated then necessary. 
E.g configure http with the local access only, wait for a quorum, create token, enable http access.

As an example, demo.nomadproject.io is configured with acl but I don't see how to bootstrap it initially without compromising security by having `/ac/bootstrap` accessible from Internet.

**Comment by preetapan** [comment]
> I meant this sort of tokens in Consul: https://www.consul.io/docs/agent/options.html#acl_master_token

Since Consul 0.9.1, we have added a similar bootstrap endpoint - https://www.consul.io/api/acl.html#bootstrap-acls. The old ACL token in config file mechanism exists for backward compatibility reasons. 

Our model is Trust on First Use(thanks @chelseakomlo for teaching me that term) https://en.wikipedia.org/wiki/Trust_on_first_use#Model_strengths_and_weaknesses
 which has that tradeoff of that first step where you have to restrict access till the token is created.

**Comment by roman-cnd** [comment]
These are great details, appreciate for pointing out.
I understand now the reasons behind the bootstrap design!
