### ISSUE TITLE
Nomad run in development mode fails on Windows 7 

### ISSUE THREAD

**Issue by mark-brooks-180** [hashicorp/nomad#3952]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Wndows 7 64bit

### Issue
Nomad agent fails when run in development mode.

### Reproduction steps
Simply run the agent in development mode "nomad.exe agent -dev"

### Nomad Server logs (if appropriate)
C:\temp>nomad.exe agent -dev
    No configuration files loaded
==> Starting Nomad agent...
==> Error starting agent: client setup failed: fingerprinting failed: Error while detecting network interface during fingerprinting: no network_interface given and failed to determine interface attached to default route
    2018/03/08 10:46:40 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:127.0.0.1:4647 Address:127.0.0.1:4647}]
    2018/03/08 10:46:40 [INFO] raft: Node at 127.0.0.1:4647 [Follower] entering Follower state (Leader: "")
    2018/03/08 10:46:40 [INFO] serf: EventMemberJoin: Mamba2.global 127.0.0.1
    2018/03/08 10:46:40.892669 [INFO] nomad: starting 8 scheduling worker(s) for [batch system service _core]
    2018/03/08 10:46:40.892669 [INFO] nomad: adding server Mamba2.global (Addr: 127.0.0.1:4647) (DC: dc1)
    2018/03/08 10:46:40.892669 [DEBUG] server.nomad: lost contact with Nomad quorum, falling back to Consul for server list
    2018/03/08 10:46:40.899669 [INFO] client: using state directory C:\Users\mbrooks\AppData\Local\Temp\NomadClient138187011
    2018/03/08 10:46:40.902669 [INFO] client: using alloc directory C:\Users\mbrooks\AppData\Local\Temp\NomadClient443852934
    2018/03/08 10:46:41.300692 [DEBUG] client: built-in fingerprints: [arch consul cpu host memory network nomad signal storage vault env_aws env_gce]
    2018/03/08 10:46:41.892726 [ERR] consul: error looking up Nomad servers: server.nomad: unable to query Consul datacenters: Get http://127.0.0.1:8500/v1/catalog/datacenters: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
    2018/03/08 10:46:41.892726 [WARN] consul.sync: failed to update services in Consul: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
    2018/03/08 10:46:42.301749 [DEBUG] client: fingerprinting consul every 15s
    2018/03/08 10:46:42 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/03/08 10:46:42 [INFO] raft: Node at 127.0.0.1:4647 [Candidate] entering Candidate state in term 2
    2018/03/08 10:46:42 [DEBUG] raft: Votes needed: 1
    2018/03/08 10:46:42 [DEBUG] raft: Vote granted from 127.0.0.1:4647 in term 2. Tally: 1
    2018/03/08 10:46:42 [INFO] raft: Election won. Tally: 1
    2018/03/08 10:46:42 [INFO] raft: Node at 127.0.0.1:4647 [Leader] entering Leader state
    2018/03/08 10:46:42.811779 [INFO] nomad: cluster leadership acquired
    2018/03/08 10:46:42.812779 [DEBUG] leader: reconciling job summaries at index: 0
    2018/03/08 10:46:43.372811 [DEBUG] fingerprint.cpu: frequency: 2794 MHz
    2018/03/08 10:46:43.372811 [DEBUG] fingerprint.cpu: core count: 8

**Comment by angrycub** [comment]
Nomad v0.7.1 has an issue with network interface names with a space in them.  We have fixed this for 0.8.

You can: 
* use the [`--network-interface`](https://www.nomadproject.io/docs/commands/agent.html#network-interface-lt-interface-gt-) flag on the command line to the interface name of the network with your default route,
* set the [network_interface](https://www.nomadproject.io/docs/agent/configuration/client.html#network_interface) explicitly in the configuration, or
* rename the interface to mitigate this issue.

**Comment by mark-brooks-180** [comment]
Thanks for the prompt response Charlie.
