### ISSUE TITLE
Logging by version

### ISSUE THREAD

**Issue by abergmeier** [hashicorp/nomad#3964]
If filing a bug please include the following:

### Nomad version
    Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Ubuntu 16.04.4

### Issue
I would like to log the version of the Job.

### Reproduction steps
```
logging {
    type = "splunk"
        config {
            tag = "{{.Name}}/{{.Version}}/{{.FullID}}"
```

This complains: 

> can't evaluate field Version in type *logger.Context

**Comment by dadgar** [comment]
Version doesn't look like a docker option: https://docs.docker.com/config/containers/logging/log_tags/
