### ISSUE TITLE
UI: Ability to see task's logs even if client is not accessible from internet

### ISSUE THREAD

**Issue by JacekJagiello** [hashicorp/nomad#3969]
Currently, web UI request task's logs using the IP address of a client, in which task is running on. But if a client is running in private subnet web UI tries to request it via private IP, which of course fails.
For example, if IP of a client in private network is 10.232.16.2, request for logs looks like this:
```
http://10.232.16.2.22:4646/v1/client/fs/logs/1fe767ac-...
```
Can we add some way to fetch logs from clients that are not accessible from internet? Maybe prepare endpoint in nomad server which proxies the request to a client? The same problem concerns other endpoints that communicate with nomad client, for example `/v1/client/allocation/.../stats` endpoint.

I'm happy to contribute, if we agree on some solution for this

**Comment by DingoEatingFuzz** [comment]
Hey @JacekJagiello, this is coming in 0.8 and is already in master!

- New server endpoints for proxying to clients: #3892 
- Changes to the UI to use the new endpoints, or falling back to them: #3908

**Comment by JacekJagiello** [comment]
That's great news, can't wait for the next release!
