### ISSUE TITLE
Need Assistance on Constraint Regex 

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/nomad#3973]
`[question]` 

Consider that I have the following nodes in the Node class: 

```sh
test-worker 
test-worker 
test-worker
test-worker
test-worker
test-master
test-master
test-master
```
- How would I create a regex pattern to run a system job onto the "test-worker" cluster? 

Here's what I currently have but this is not right: 

```
 constraint {
      attribute = "${node.class}"
      operator = "regexp"
      value = "^(test.+)\\-worker$"
  }
```

**Comment by schmichael** [comment]
Hi @ptarpan,

If your node classes are `test-worker` and `test-master` you do not need to use a regular expression. The following would schedule jobs only on worker nodes:

```hcl
    constraint {
        attribute = "${node.class}"
        value     = "test-worker"
    }
```

However if I understand your regexp properly it seems like you may have a number of different test work node classes. If you want to match node classes like `test1-work`, `test2-worker`, `testA-worker`, and `testB-worker` the following regular expression should work:

```hcl
    constraint {
        attribute = "${node.class}"
        operator  = "regexp"
        value     = "^test.-worker$"
    }
```

Hope that helps!

**Comment by ptarpan** [comment]
Hi @schmichael, 
Thanks for the quick response. You are absolutely right. Apologies but I actually provided an incomplete node class list. Here's the full list: 

```sh 
<sensitive>-<sensitive>-test-<sensitive>-worker
<sensitive>-test-<sensitive>-worker
staging-test-worker
staging-test-worker
staging-test-worker
production-test-worker
production-test-worker
production-test-worker
corporate-test-worker
corporate-test-worker
corporate-test-worker
<sensitive>-test-master
<sensitive>-test-master
<sensitive>-test-master
```
From the list above, I would like to use the `staging`, `production`, and `corporate` worker clusters. Here's what I have so far: 
```sh
([a-z\\-])+test-worker
```
This seems to work but I'm still confirming. Any better suggestions?

**Comment by schmichael** [comment]
That looks good to me!

Setting custom meta attributes on nodes may make constraints easier: https://www.nomadproject.io/docs/agent/configuration/client.html#meta
