### ISSUE TITLE
Nomad Agent Fails to start with BoltDB panic

### ISSUE THREAD

**Issue by latchmihay** [hashicorp/nomad#3977]
This is a weird one because we have another 5-6 servers, running on identical OS, hardware and etc. (Virtual Machines). They are running the exact same nomad version, nomad config files, same network, same cluster, and etc.

### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
RHEL7

### Issue
Nomad agent fails to restart with panic "above high water mark"

### Reproduction steps
      # cat /etc/nomad/config/default.hcl
      data_dir = "/etc/nomad/data"
      datacenter = "EST1"
      region = "DC1"
      name = "myserver009"
      enable_syslog = true
      log_level = "DEBUG"
      http_api_response_headers {
        "Access-Control-Allow-Origin" = "*"
      }
      consul {
        token   = "xxxxxxxxxxxxxx"
      }
      telemetry {
        prometheus_metrics = true
        publish_allocation_metrics = true
        publish_node_metrics       = true
      }
      acl {
        enabled = true
      }

      # cat /etc/nomad/config/client.json
      client {
        enabled = true
      }
      vault {
        enabled     = true
        address     = "https://active.vault.service.consul:8200"
      }

### Nomad Client logs (if appropriate)
      # /usr/local/bin/nomad agent   -config /etc/nomad/config/default.hcl   -config /etc/nomad/config/client.json
          Loaded configuration from /etc/nomad/config/default.hcl, /etc/nomad/config/client.json
      ==> Starting Nomad agent...
      ==> Nomad agent configuration:

                      Client: true
                   Log Level: DEBUG
                      Region: DC1 (DC: EST1)
                      Server: false
                     Version: 0.7.1

      ==> Nomad agent started! Log data will stream in below:

          2018/03/14 11:24:30.059348 [INFO] client: using state directory /etc/nomad/data/client
          2018/03/14 11:24:30.061239 [INFO] client: using alloc directory /etc/nomad/data/alloc
          2018/03/14 11:24:30.062216 [DEBUG] client: built-in fingerprints: [arch cgroup consul cpu host memory network nomad signal storage vault env_aws env_gce]
          2018/03/14 11:24:30.062378 [INFO] fingerprint.cgroups: cgroups are available
          2018/03/14 11:24:30.062602 [DEBUG] client: fingerprinting cgroup every 15s
          2018/03/14 11:24:30.063810 [INFO] fingerprint.consul: consul agent is available
          2018/03/14 11:24:30.063944 [DEBUG] client: fingerprinting consul every 15s
          2018/03/14 11:24:30.064078 [DEBUG] fingerprint.cpu: frequency: 2499 MHz
          2018/03/14 11:24:30.064097 [DEBUG] fingerprint.cpu: core count: 4
          2018/03/14 11:24:30.067359 [DEBUG] fingerprint.network: link speed for eth0 set to 1000
          2018/03/14 11:24:30.067441 [DEBUG] fingerprint.network: Detected interface eth0 with IP: 10.10.102.147
          2018/03/14 11:24:30.078474 [INFO] fingerprint.vault: Vault is available
          2018/03/14 11:24:30.078716 [DEBUG] client: fingerprinting vault every 15s
          2018/03/14 11:24:30.086168 [DEBUG] fingerprint.env_gce: Could not read value for attribute "machine-type"
          2018/03/14 11:24:30.086285 [DEBUG] client: applied fingerprints [arch cgroup consul cpu host memory network nomad signal storage vault]
          2018/03/14 11:24:30.086469 [DEBUG] driver.docker: using client connection initialized from environment
          2018/03/14 11:24:30.086774 [DEBUG] client: fingerprinting rkt every 15s
          2018/03/14 11:24:30.089013 [DEBUG] driver.exec: exec driver is enabled
          2018/03/14 11:24:30.089105 [DEBUG] client: available drivers [docker exec]
          2018/03/14 11:24:30.089264 [DEBUG] client: fingerprinting docker every 15s
          2018/03/14 11:24:30.089285 [DEBUG] client: fingerprinting exec every 15s
          2018/03/14 11:24:30.089358 [INFO] client: Node ID "0be732a6-3a48-5c78-e195-eec7a995a33f"
          2018/03/14 11:24:30.089936 [DEBUG] client: registration waiting on servers
          2018/03/14 11:24:30.090504 [DEBUG] client.consul: bootstrap contacting following Consul DCs: ["dc1"]
          2018/03/14 11:24:30.091277 [DEBUG] consul.sync: registered 0 services, 0 checks; deregistered 0 services, 0 checks
          2018/03/14 11:24:30.093633 [INFO] client.consul: discovered following Servers: 10.10.103.133:4647,10.10.101.50:4647,10.10.100.163:4647,10.10.103.206:4647,10.10.100.247:4647
          2018/03/14 11:24:30.096861 [DEBUG] client: updated allocations at index 5102914 (total 1) (pulled 1) (filtered 0)
          2018/03/14 11:24:30.096979 [DEBUG] client: allocs: (added 1) (removed 0) (updated 0) (ignore 0)
          2018/03/14 11:24:30.105510 [INFO] client: node registration complete
          2018/03/14 11:24:30.105571 [DEBUG] client: periodically checking for node changes at duration 5s
      panic: pgid (64424509449) above high water mark (154)

      goroutine 128 [running]:
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*node).spill(0xc42021d490, 0xc4201723c0, 0x24)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/node.go:375 +0x715
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc42017a3c0, 0xc420170c00, 0xc420521c80)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/bucket.go:570 +0x4d3
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc4202c0398, 0x4c5e60c, 0x20d6e60)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/bucket.go:537 +0x417
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4202c0380, 0x0, 0x0)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/tx.go:163 +0x129
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4204214a0, 0xc4202eb720, 0x0, 0x0)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/db.go:605 +0xf2
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*batch).run(0xc4201cb040)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/db.go:717 +0x11f
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*batch).(github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.run)-fm()
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/db.go:699 +0x2a
      sync.(*Once).Do(0xc4201cb050, 0xc4202eb7a8)
      	/usr/local/go/src/sync/once.go:44 +0xbe
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*batch).trigger(0xc4201cb040)
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/db.go:699 +0x4c
      github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.(*batch).(github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt.trigger)-fm()
      	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/boltdb/bolt/db.go:669 +0x2a
      created by time.goFunc
      	/usr/local/go/src/time/sleep.go:170 +0x44

**Comment by latchmihay** [comment]
Since the error is in boltdb package, i assumed it was an issue with nomad data directory. I cleaned out nomad data directory and nomad started with no problems. 

I still have the "corrupted" data directory, I can provide it if someone wants to take a deeper look at what caused the issue.

**Comment by dadgar** [comment]
@latchmihay Did you have a hard shutoff of the node? Looks like a Bolt bug: https://github.com/boltdb/bolt/issues/687

**Comment by latchmihay** [comment]
@dadgar yes, 4 nodes had hard crashes. As I mentioned above all of them are VMs, and the underneath vm storage had issues. 
3 out of the 4 started back up with no problem, the 4th one is the one reporting the boltdb errors. Hope this helps

**Comment by schmichael** [comment]
Hi @latchmihay,

While bolt should always be able to recover from hard crashes, if there were issues with underlying storage there's nothing we can do. Throwing away the corrupt database and starting that node from scratch is the correct course of action.

Hope that helps!
