### ISSUE TITLE
windows: Cannot support wireless adapters in the v0.7.1

### ISSUE THREAD

**Issue by molin0000** [hashicorp/nomad#3986]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Windows 7 Ultimate sp1
Thinkpad T450
### Issue
It reports an error:
No default interface found with matching IP.

I look up the source code in Git. And I find those code in the ifaddrs.go file. line 19.
var (
	// Centralize all regexps and regexp.Copy() where necessary.
	signRE       *regexp.Regexp = regexp.MustCompile(`^[\s]*[+-]`)
	whitespaceRE *regexp.Regexp = regexp.MustCompile(`[\s]+`)
	ifNameRE     *regexp.Regexp = regexp.MustCompile(`^Ethernet adapter ([^:]+):`)
	ipAddrRE     *regexp.Regexp = regexp.MustCompile(`^   IPv[46] Address\. \. \. \. \. \. \. \. \. \. \. : ([^\s]+)`)
)

It looks not a good Regexp of ifNameRE. My adapter name is: Wireless LAN adapter wifi.

But, it is good in the version of Nomad v0.6.3.

That's all.

**Comment by schmichael** [comment]
Thanks for the report! Added an issue to the library that detects adapters (hashicorp/go-sockaddr#20). We'll close both when it's fixed and pulled into Nomad.

**Comment by schmichael** [comment]
Can you post your full output of `ipconfig` so we're sure to test against it?

**Comment by molin0000** [comment]
Windows IP Configuration


Wireless LAN adapter wifi:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::3110:eaca:23d7:b9ac%14
   IPv4 Address. . . . . . . . . . . : 172.20.10.5
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . : 172.20.10.1

Ethernet adapter 本地连接 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Ethernet adapter VMware Network Adapter VMnet1:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::6069:41f9:ea44:7a8b%18
   IPv4 Address. . . . . . . . . . . : 192.168.249.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 

Ethernet adapter VMware Network Adapter VMnet8:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::6846:4948:d165:67d8%19
   IPv4 Address. . . . . . . . . . . : 192.168.198.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 

Tunnel adapter isatap.{EBACA806-1326-447F-96A0-465285B91CD1}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Tunnel adapter isatap.{45830FF1-D3E8-4C59-B6F7-24660FE3D3D7}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Tunnel adapter isatap.{FF9F237C-4A0A-450B-95FA-CB8E92FC4AA9}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
