### ISSUE TITLE
Consul config: configurable Consul health check names

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#3988]
In my current setup we alert based on Consul health checks and all alerts must follow a particular naming pattern in order to meet the correct alerting requirements. It would be excellent (I have checked but not found the feature detailed) if an operator could override the default 'Nomad Server *' and 'Nomad Client HTTP Check' names so that in such environments, the names can be changed to match requirement.

I would be interested in your thoughts about this feature, and I would also be happy to contribute this as I believe I understand how to implement this.

**Comment by schmichael** [comment]
Sounds good! You can probably just follow [`client_service_name`](https://www.nomadproject.io/docs/agent/configuration/consul.html#client_service_name) as an example of how to allow configuring the check names!
