### ISSUE TITLE
Nomad State Diagram

### ISSUE THREAD

**Issue by huntercatalan** [hashicorp/nomad#3991]
In order to write scheduler extensions that use nomad (for example, a DAG batch scheduler), it would be great to have a state diagram for "job", "evaluation", and "allocation". Even the possible states/transitions for a client would be useful. This diagram would clarify how state transitions work and would cover both Status and DesiredStatus (and StatusDescription if applicable).

Please excuse if this documentation is available or if there are header files where the states are apparent.

**Comment by Xopherus** [comment]
This would be extremely helpful. My team had a conversation about this after we noticed one of our allocations end up in a "lost" state.
