### ISSUE TITLE
Nomad fails to create container in job

### ISSUE THREAD

**Issue by Luke035** [hashicorp/nomad#3994]
### Nomad version
Nomad v0.7.1

### Operating system and Environment details
Nomad operating in DOCKER containers based on UBUNTU 16.04 image (1 for nomad-server and 1 for nomad-client)

### Issue
Error when launching JOB through docker driver:
[ERR] driver.docker: Failed to create container: API error (400): {"message":"stat /tmp/plugin220744405: no such file or directory"}

### Reproduction steps
Run simple hello-world docker container through nomad job:
Before run the job I also run `nomad validate` and `nomad plan` for the specific job

In my envrionment I just have 1 server and 1 client both shipped with docker version 17.12.1-ce.

For development reasons both of them are also docker container, run with the "-v /var/run/docker.sock:/var/run/docker.sock" parameter in order to avoid docker-in-docker problems (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

### Nomad Client logs (if appropriate)
    2018/03/16 15:09:23.248125 [DEBUG] client: starting task context for 'hello-task' (alloc '9f760e0f-95ac-e979-5736-193a40b42205')
    2018/03/16 15:09:23.318165 [DEBUG] client: driver event for alloc "9f760e0f-95ac-e979-5736-193a40b42205": Downloading image hello-world:latest
    2018/03/16 15:09:23.494160 [DEBUG] driver.docker: docker pull hello-world:latest succeeded
    2018/03/16 15:09:23.508059 [DEBUG] client: updated allocations at index 275 (total 6) (pulled 0) (filtered 6)
    2018/03/16 15:09:23.508139 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
    2018/03/16 15:09:23.638109 [DEBUG] client: updated allocations at index 276 (total 6) (pulled 0) (filtered 6)
    2018/03/16 15:09:23.638203 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
    2018/03/16 15:09:24.053533 [DEBUG] driver.docker: cancelling removal of image "hello-world"
    2018/03/16 15:09:24.053557 [DEBUG] driver.docker: image "hello-world" (sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7) reference count incremented: 1
2018-03-16T15:09:24.053Z [DEBUG] plugin: starting plugin: path=/usr/bin/nomad args="[/usr/bin/nomad executor {"LogFile":"/var/lib/nomad/alloc/9f760e0f-95ac-e979-5736-193a40b42205/hello-task/executor.out","LogLevel":"DEBUG"}]"
2018-03-16T15:09:24.053Z [DEBUG] plugin: waiting for RPC address: path=/usr/bin/nomad
2018-03-16T15:09:24.081Z [DEBUG] plugin.nomad: plugin address: timestamp=2018-03-16T15:09:24.081Z address=/tmp/plugin788425166 network=unix
    2018/03/16 15:09:24.083893 [DEBUG] driver.docker: Setting default logging options to syslog and unix:///tmp/plugin220744405
    2018/03/16 15:09:24.083915 [DEBUG] driver.docker: Using config for logging: {Type:syslog ConfigRaw:[] Config:map[syslog-address:unix:///tmp/plugin220744405]}
    2018/03/16 15:09:24.083920 [DEBUG] driver.docker: using 314572800 bytes memory for hello-task
    2018/03/16 15:09:24.083925 [DEBUG] driver.docker: using 100 cpu shares for hello-task
    2018/03/16 15:09:24.083934 [DEBUG] driver.docker: binding directories []string{"/var/lib/nomad/alloc/9f760e0f-95ac-e979-5736-193a40b42205/alloc:/alloc", "/var/lib/nomad/alloc/9f760e0f-95ac-e979-5736-193a40b42205/hello-task/local:/local", "/var/lib/nomad/alloc/9f760e0f-95ac-e979-5736-193a40b42205/hello-task/secrets:/secrets"} for hello-task
    2018/03/16 15:09:24.083943 [DEBUG] driver.docker: networking mode not specified; defaulting to bridge
    2018/03/16 15:09:24.083949 [DEBUG] driver.docker: No network interfaces are available
    2018/03/16 15:09:24.083960 [DEBUG] driver.docker: setting container startup command to: run -v /var/run/docker.sock:/var/run/docker.sock
    2018/03/16 15:09:24.083982 [DEBUG] driver.docker: setting container name to: hello-task-9f760e0f-95ac-e979-5736-193a40b42205
    2018/03/16 15:09:24.085332 [DEBUG] driver.docker: failed to create container "hello-task-9f760e0f-95ac-e979-5736-193a40b42205" from image "hello-world" (ID: "sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7") (attempt 1): API error (400): {"message":"stat /tmp/plugin220744405: no such file or directory"}
    2018/03/16 15:09:24.085348 [ERR] driver.docker: Failed to create container: API error (400): {"message":"stat /tmp/plugin220744405: no such file or directory"}
2018-03-16T15:09:24.086Z [DEBUG] plugin: plugin process exited: path=/usr/bin/nomad
    2018/03/16 15:09:24.086499 [WARN] client: failed to start task "hello-task" for alloc "9f760e0f-95ac-e979-5736-193a40b42205": Failed to create container: API error (400): {"message":"stat /tmp/plugin220744405: no such file or directory"}

### Job file (if appropriate)
`job "helloworld-v1" {
  datacenters = ["dc1"]
  type = "service"

  update {
    stagger = "30s"
    max_parallel = 1
  }

  group "hello-group" {
    count = 1
    task "hello-task" {
      driver = "docker"
      config {
        image = "hello-world"
        args = ["-v /var/run/docker.sock:/var/run/docker.sock"]
        command = "run"
      }
    }
  }
}`

**Comment by alxark** [comment]
using nomad inside docker container is a bad way and not supported by vendor. It looks like docker ( located on your host) tries to access /tmp/pluginXXXX file from nomad container but it will fail, because it's not found on your host machine and exists only inside nomad container.

**Comment by dadgar** [comment]
Hey @Luke035, @alxark is correct. We do not recommend running Nomad clients in a Docker container. We do not test or design for it at the moment, and therefore don't support it. Please run your Nomad Clients on the host directly.

**Comment by BrianPhiri** [comment]
Getting the same error running the nomad agent(nomad agent -dev) on my local machine(ubuntu 18.04).

**Comment by BrianPhiri** [comment]
Hey, I am getting the same error and I am running nomad from my local machine (ubuntu 18.04).

**Comment by kurtwheeler** [comment]
I too am seeing the same error, while not running Nomad inside a docker container, and I can even stat the file that supposedly doesn't exist:
```
$ stat /tmp/plugin409627175
  File: /tmp/plugin409627175
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 10301h/66305d	Inode: 19922960    Links: 1
Access: (0755/srwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-19 15:26:24.786978678 -0400
Modify: 2019-04-19 15:26:24.786978678 -0400
Change: 2019-04-19 15:26:24.786978678 -0400
 Birth: -
```
