### ISSUE TITLE
Log the config files used

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/nomad#40]
Suggested by @cbednarski in #33: It could be helpful to an operator if we had a debug-level log to show the names of the config files used when starting the agent, especially in cases where a config dir is used.

**Comment by diptanu** [comment]
@ryanuber @cbednarski I think it migiht be better if we exposed this information on an agent-debug endpoint rather than logging it, since this is something that will be logged during the startup and after a few hours/days it might be rotated out.

**Comment by ryanuber** [comment]
That's true, but I think the same could be said for just about anything we log at start time. Logging it is just the easy way to solve the general use case since that's where other startup information lives currently.

**Comment by cbednarski** [comment]
Also it's likely if there is a problem at startup (for instance if the node fails to come online) that you may only have log data.
