### ISSUE TITLE
[Feature] Docker driver "State.Health" support

### ISSUE THREAD

**Issue by muravitskiy** [hashicorp/nomad#4000]
Docker has built-in `HEALTHCHECK CMD` feature. It is also supported in [go-dockerclient](https://github.com/fsouza/go-dockerclient/blob/b4b709947ca6022744c3989d7741c069f29357e4/container.go#L146)
This feature will be useful for containers which are not listening on any ports (e.g only working with message queues). Nomad can check not only `container.State.Running` but also `container.State.Health.Status`. As such containers do not define any `service`, it is unclear should it be implicitly enabled for `task_state` check when there is `container.State.Health` block in `docker inspect` response or maybe additional configuration block needed.

**Comment by dadgar** [comment]
Hey we don't plan to integrate with docker specific health check since we support many drivers and instead rely on health checks defined in Consul: https://www.nomadproject.io/docs/job-specification/service.html#check-parameters

Hope that helps!
