### ISSUE TITLE
Feature - ability to restart or fail allocations

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#4009]
In certain situations it would be helpful to be able to restart or fail an allocation so that it can be rescheduled in the event of an issue. I am not sure if there is already a way to achieve this, but this would help during on-call situations where the operator is dealing with an issue which may not be the fault of Nomad.

**Comment by dadgar** [comment]
Duplicate of https://github.com/hashicorp/nomad/issues/698. We definitely want to bring this feature!.
