### ISSUE TITLE
Update nomad metrics to include information about Job status

### ISSUE THREAD

**Issue by sevagh** [hashicorp/nomad#4036]
Hello,

We noticed that the metrics endpoint (scraped by Prometheus) exposes Task Group Summaries per Job's TaskGroup: https://github.com/hashicorp/nomad/blob/master/api/jobs.go#L691

However there are no metrics exposed for the job status (i.e. https://github.com/hashicorp/nomad/blob/master/api/jobs.go#L691)

Is that something I should compose by some aggregation on Task Group Summaries, or could this be a useful metric to add in a PR?

**Comment by chelseakomlo** [comment]
Hi, thanks for the question. These metrics should already be enabled, look for the metric name nomad.nomad.job_summary. We will be sure to update our [telemetry documentation](https://www.nomadproject.io/docs/agent/telemetry.html) to include this metric as well.

**Comment by sevagh** [comment]
Thanks. I'll ensure I have the correct settings (https://www.nomadproject.io/docs/agent/configuration/telemetry.html) by Monday and update this ticket.

**Comment by sevagh** [comment]
I can't find it:

```
shanssian:nomad $ grep -Iirnw ./ -e '.*SetGaugeWithLabels.*job_summary.*'
./nomad/leader.go:623:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "queued"},
./nomad/leader.go:625:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "complete"},
./nomad/leader.go:627:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "failed"},
./nomad/leader.go:629:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "running"},
./nomad/leader.go:631:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "starting"},
./nomad/leader.go:633:                                          metrics.SetGaugeWithLabels([]string{"nomad", "job_summary", "lost"},
```

These are the TaskGroup summaries. I'm looking for Job Status, the higher level one:

```
shanssian:nomad $ nomad status foo
ID            = foo
Name          = foo
Submit Date   = 01/20/18 19:50:34 PST
Type          = service
Priority      = 50
Datacenters   = bar
Status        = running
```

**Comment by maxramqvist** [comment]
We'd like above metrics exposed as well. Made a separate exporter for batch and parameterized jobs, scraping the HTTP API. :octopus:

**Comment by sevagh** [comment]
So in our custom exporter code, we set the Job Status in the labels (and just set the metric value to `1.0`). That's not a good way to use Prometheus: https://github.com/prometheus/prometheus/issues/2227

The "right way" is to set float values based on the possible values of Job Status. E.g. `assume that 0.0 = dead, 1.0 = running...`

**Comment by sevagh** [comment]
It's also impossible to construct the job-level status (i.e. `[running,pending,dead]`) from the underlying Task Group stats. A batch job can have `job.Status == running` and `job.JobSummary.TaskSummary.Running == 0` if it's not active right now.

**Comment by sevagh** [comment]
Another possiblity is:

```
job_status_running{} = 1.0 if job.Status == 'running' else 0.0
job_status_failed{} = 1.0 if job.Status == 'failed' else 0.0
job_status_pending{} = 1.0 if job.Status == 'pending' else 0.0```

**Comment by sevagh** [comment]
Or `job_status{status="running|failed|pending"}`.

**Comment by sevagh** [comment]
https://github.com/hashicorp/nomad/compare/master...sevagh:feat/job-metrics

**Comment by sevagh** [comment]
Some accidental churn as I deleted my old fork of Nomad, but my pull request to implement this feature request is as of yet unmerged, and according to some other users here, I think several people are running custom Nomad exporters to expose this info (which this PR would help eliminate):

https://github.com/hashicorp/nomad/pull/4831

**Comment by pete-woods** [comment]
See #6003 for another PR to try and fix this.

**Comment by Fuco1** [comment]
The documentation at https://www.nomadproject.io/docs/telemetry/metrics.html#tagged-metrics mentions these are under `nomad.job_summary` but this is (no longer?) true.  You suggest here that they are under `nomad.nomad.job_summary`.

**Comment by pete-woods** [comment]
Those docs seem to be for the unreleased 0.10 version where my PR is merged.

**Comment by Fuco1** [comment]
Is there a way to display docs for *released* versions by default?  I find this very confusing :(
