### ISSUE TITLE
Swarm Comparison

### ISSUE THREAD

**Issue by danehans** [hashicorp/nomad#404]
Disclaimer: I am by no means promoting Swarm or Kubernetes. I am interested in Nomad and currently performing due diligence. Which brought me to the following comparison:

https://nomadproject.io/intro/vs/swarm.html

Although Swarm is focused on container abstraction, Docker Compose provides a higher-level abstraction and integrates (currently not complete) with Swarm. I think it's fair to mention something of this nature for comparison purposes.

Can you also help me understand the points made about dependencies of external systems for storage and coordination. It is my understanding that both systems use Consul for coordination and Docker can use the filesystem storage driver.

https://nomadproject.io/intro/vs/kubernetes.html states that Nomad is designed to scale better. Has Nomad completed any scale testing yet?

**Comment by dadgar** [comment]
Sorry it took so long to get to this :)

While docker compose does add additional ability to run multi-container applications, the point being made is that Nomad's job file and constraints allow higher level features such as task group anti-affinities, `distinct_host` constraints, blue/green deploys of groups of containers, etc.

Nomad is fully contained and manages all its state in a single binary. This means to deploy a Nomad cluster, no other software (distributed system) has to be deployed where as this is not the case with Swarm.

As for scale we recently completed [this benchmark](http://hashicorp.com/c1m.html) which ran a million containers on 5,000 nodes using Nomad 0.3.1
