### ISSUE TITLE
IPv4 service checks registered in consul, though IPv6 only advertisements

### ISSUE THREAD

**Issue by xaque208** [hashicorp/nomad#4042]
### Nomad version
Nomad v0.7.1

### Operating system and Environment details
FreeBSD, IPv6 only advertisement blocks to consul.

### Issue

Health checks from consul are being performed against IPv4 addresses of nomad servers, even though there is only IPv6 addresses in the nomad server configuration under the `advertisement` block.  Its unclear how the IPv4 address is getting registered with consul at all.  All hostnames in use through the entire configuration only have IPv6 records, and all IP addresses in use through the entire configuration have only IPv6 addresses.

Please provide a clear path for disabling IPv4 or tuning the health checks to be performed a specific address in the case of a dual stack nomad server.

### Reproduction steps
Create a service on a dual stack host.  Check consul health checks.

**Comment by 42wim** [comment]
Hi, you'll have to add some extra nomad config

```
consul {
  address = "[::1]:8500"
  checks_use_advertise = true
}

advertise {
  http = "[2001:db8::1]:4646" #your real ipv6 address
}
```

**Comment by dadgar** [comment]
@xaque208 Can you post your server config and share the output of the registered services in consul from the agent API, and the beginning of Nomad server logs?

**Comment by xaque208** [comment]
Here is the nomad server config I'm using.

```
bind_addr = "2001::114"
datacenter = "lab"
data_dir = "/var/tmp/nomad"
enable_syslog = true

advertise {
  rpc = "2001::114"
  http = "2001::114"
  serf = "2001::114"
}

server {
  enabled          = true
  bootstrap_expect = 2
  retry_join = [ "nom1.l.example.com", "nom2.l.example.com" ]
}

consul {
  address = "consul.service.consul:8500"
}
```

Here are the start of my logs:
```
Apr  4 08:54:20 nom2 nomad[27362]: raft: Restored from snapshot 457-353234-1522849270520
Apr  4 08:54:20 nom2 nomad[27362]: raft: Initial configuration (index=87490): [{Suffrage:Voter ID:[2001::235]:4647 Address:[2001::235]:4647} {Suffrage:Voter ID:[2001::114]:4647 Address:[2001::114]:4647}]
Apr  4 08:54:20 nom2 nomad[27362]: raft: Node at [2001::114]:4647 [Follower] entering Follower state (Leader: "")
Apr  4 08:54:20 nom2 nomad[27362]: serf: EventMemberJoin: nom2.global 2001::114
Apr  4 08:54:20 nom2 nomad[27362]: nomad: starting 16 scheduling worker(s) for [service batch system _core]
Apr  4 08:54:20 nom2 nomad[27362]: client: using state directory /var/tmp/nomad/client
Apr  4 08:54:20 nom2 nomad[27362]: serf: Attempting re-join to previously known node: nom1.global: [2001::235]:4648
Apr  4 08:54:20 nom2 nomad[27362]: nomad: adding server nom2.global (Addr: [2001::114]:4647) (DC: lab)
Apr  4 08:54:20 nom2 nomad[27362]: client: using alloc directory /var/tmp/nomad/alloc
Apr  4 08:54:20 nom2 nomad[27362]: serf: EventMemberJoin: nom1.global 2001::235
Apr  4 08:54:20 nom2 nomad[27362]: memberlist: Refuting an alive message
Apr  4 08:54:20 nom2 nomad[27362]: nomad: adding server nom1.global (Addr: [2001::235]:4647) (DC: lab)
Apr  4 08:54:20 nom2 nomad[27362]: serf: Re-joined to previously known node: nom1.global: [2001::235]:4648
Apr  4 08:54:20 nom2 nomad[27362]: server.nomad: successfully contacted 1 Nomad Servers
Apr  4 08:54:20 nom2 nomad[27362]: fingerprint.consul: consul agent is available
Apr  4 08:54:20 nom2 nomad[27362]: fingerprint.vault: Vault is available
Apr  4 08:54:22 nom2 nomad[27362]: raft: Failed to get previous log: 355427 log not found (last: 355426)
Apr  4 08:54:24 nom2 nomad[27362]: driver.raw_exec: raw exec is enabled. Only enable if needed
Apr  4 08:54:24 nom2 nomad[27362]: client: Node ID "792dae94-b65d-967f-2f4d-ff249afd583f"
Apr  4 08:54:24 nom2 nomad[27362]: agent: Joining cluster...
Apr  4 08:54:24 nom2 nomad[27362]: agent: Join completed. Synced with 2 initial agents
Apr  4 08:54:24 nom2 nomad[27362]: client: node registration complete
```

**Comment by chelseakomlo** [comment]
Hi, thanks for providing this info. Per the question above, could you also include the output of the registered services in consul from the agent API?

**Comment by xaque208** [comment]
@chelseakomlo Hi, sure, though what does that mean?  I'm just getting the hashicorp cluster up, so pretty new.

**Comment by xaque208** [comment]
Do you mean the logs for the job?

**Comment by chelseakomlo** [comment]
From the Consul agent API, can you output the services that are registered?

**Comment by xaque208** [comment]
An example task from nomad in the consul agent api looks like the following.
```
  "_nomad-task-vxniid5zefezdteb7qanrrpwapvxifse": {
    "ID": "_nomad-task-vxniid5zefezdteb7qanrrpwapvxifse",
    "Service": "otto-otto-otto",
    "Tags": [],
    "Address": "",
    "Port": 0,
    "EnableTagOverride": false,
    "CreateIndex": 0,
    "ModifyIndex": 0
  },
```

**Comment by jktr** [comment]
(nomad v0.8.3 on archlinux)

I seem to have a similar issue os OP. Checks are always forced to ipv4 on my servers with globally routable dual-stack networking even though I have configured nomad/consul with only ipv6 binds/adverts.

Fingerprinting correctly detects both IP addresses:
```
2018/04/28 11:05:28.688111 [DEBUG] fingerprint.network: Detected interface ens3 with IP: XXX.XXX.XXX.XXX
2018/04/28 11:05:28.688113 [DEBUG] fingerprint.network: Detected interface ens3 with IP: XXXX:XXXX:XXXX:XXX::1
```

Assuming `address_mode` is `host` (or `auto` if the DriverNetwork does not advertise its own addresses), the `getAddress` call used to resolve the IP address for the check in https://github.com/hashicorp/nomad/blob/4317ea795ca8ab504e12a4c4754247275c190c67/command/agent/consul/client.go#L696 always results in the _first_ address found during fingerprinting being chosen for the check's address due to https://github.com/hashicorp/nomad/blob/4317ea795ca8ab504e12a4c4754247275c190c67/command/agent/consul/client.go#L1151

Given that the ipv4 address always seems to be the first one found during fingerprinting I'd say that this is probably the source of the issue.

---
I'd appreciate it if the network address would be made configurable, possibly even with go-sockaddr templating. Maybe defaulting to one of the client agent's advertise addresses could make sense, too?

(Also note that this problem is very similar to https://github.com/hashicorp/nomad/issues/4041#issuecomment-385158025.)

**Comment by 42wim** [comment]
@jktr see my first comment and use `address_mode=driver` see 2nd example in https://www.nomadproject.io/docs/job-specification/service.html#ipv6-docker-containers 

With this config all our checks are happening over ipv6

**Comment by jktr** [comment]
@42wim Ah, I had indeed missed `checks_use_advertise` — that clears up how ipv6 checks are supposed to work for the `docker` and `rkt` drivers. However, `address_mode = driver` and `advertise_ipv6_address = true` are only available for those two, so this still doesn't seem entirely solved.
