### ISSUE TITLE
'mounts[0].volume_options': source data must be an array or slice, got map

### ISSUE THREAD

**Issue by jswager** [hashicorp/nomad#4062]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
Ubuntu 14.04, Docker 17.03.1-ce

### Issue
Using https://www.nomadproject.io/docs/drivers/docker.html#mounts to create Docker based mounts. When using this feature, the error "'mounts[0].volume_options': source data must be an array or slice, got map" is received.  Removing "volume_options" results in a running job (no proper volumes of course).

I am using the REST API, rather than the Nomad command line.  Following examples are in JSON due to the REST API.

The following Tasks configuration snippet will fail:
```
"Driver":"docker",
"Config":{
	"network_mode":"host",
	"ssl":true,
	"image":"out-particular-image",
	"mounts": [
		{
			"target": "/mnt/nfs",
			"source": "nfsvolume-volume-mount",
			"readonly": false,
			"volume_options": {
				"no_copy": false,
				"labels": {
					"foo": "bar"
				},
				"driver_config": {
					"name": "flocker",
					"options": {
						"foo": "bar"
					}
				}
			}
		}
	]
},
```
Reducing to this configuration will start the job:
```
"Driver":"docker",
"Config":{
	"network_mode":"host",
	"ssl":true,
	"image":"out-particular-image",
	"mounts": [
		{
			"target": "/mnt/nfs",
			"source": "nfsvolume-volume-mount",
			"readonly": false
		}
	]
},
```

### Reproduction steps
Using any working Docker based job, add the failing configuration and the failure should be seen.  Moving to the working configuration should at least allow the job to stop.

### Nomad Server logs (if appropriate)
From the allocations log: 
```"DriverError": "failed to initialize task \"task-generic-splat-task-noncanary-641d06ddf9eb49909485a9b516097a6a\" for alloc \"84148178-d740-7908-714f-3335fd9b815d\": 1 error(s) decoding:\n\n* 'mounts[0].volume_options': source data must be an array or slice, got map",```

**Comment by angrycub** [comment]
volume_options, labels, driver_config, and options should all be lists when submitted as json.   Foe example:

``` json
                            "mounts": [
                                {
                                    "source": "name-of-volume",
                                    "target": "/path/in/container",
                                    "volume_options": [
                                        {
                                            "labels": [
                                                {
                                                    "foo": "bar"
                                                }
                                            ],
                                            "no_copy": false,
                                            "driver_config": [
                                                {
                                                    "name": "flocker",
                                                    "options": [
                                                        {
                                                            "foo": "bar"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ],
                                    "readonly": false
                                }
                            ]
```

**Comment by jswager** [comment]
I've got to learn how to translate from HCL to JSON....

Thank you, this worked perfectly!

**Comment by angrycub** [comment]
@jswager, I will confess that frequently use the HCL version and then run `nomad inspect` to extract the properly formatted JSON when I just get _stuck_ on one of the more complicated transformations.  ![bitmoji](https://render.bitstrips.com/v2/cpanel/3fb3b537-745f-4667-a6c3-e0c397eb19ad-862c1080-b671-458f-90d6-ce54989342f5-v1.png?transparent=1&palette=1&width=246)

**Comment by phillhocking** [comment]
> @jswager, I will confess that I frequently use the HCL version and then run `nomad inspect` to extract the properly formatted JSON when I just get _stuck_ on one of the more complicated transformations. ![bitmoji](https://camo.githubusercontent.com/7f83fd9b2f8846580e1983f6a947ad72d7317ba3719b38b1d6b9580ef4578920/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f33666233623533372d373435662d343636372d613663332d6530633339376562313961642d38363263313038302d623637312d343538662d393064362d6365353439383933343266352d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

As someone brand new to HashiCorp, thank you for this comment on an issue closed almost four years ago @angrycub !
