### ISSUE TITLE
Rolling upgrade of multiple groups, one group at a time

### ISSUE THREAD

**Issue by arbrk** [hashicorp/nomad#4073]
### Nomad version
0.7.1

### Operating system and Environment details
Linux / SUSE Linux Enterprise Server 12 SP2

### Issue
I have job with 3 multiple groups and max_parallel=1 on job level.
I change version of docker image in each group and 'nomad plan' it.
All group have "forces create/destroy update" and they are updated in one time.
Can I change this behaviour?

Expected behaviour:
Multiple groups will be updated one-by-one.

Observed behaviour:
Multiple groups are updated in one time.

### Job file (if appropriate)
attach
[myservice.nomad.txt](https://github.com/hashicorp/nomad/files/1860243/myservice.nomad.txt)

**Comment by shantanugadgil** [comment]
I think your are asking for inter-group dependency within a job?
I don't think this is doable for now.

Similar issues already exist, example: https://github.com/hashicorp/nomad/issues/419

There is a concept of a "leader task", if that helps you:
https://www.nomadproject.io/docs/job-specification/task.html#leader

_For my use-case I separate my groups/tasks as separate jobs._

Regards,
Shantanu

**Comment by arbrk** [comment]
@shantanugadgil thanks for answer.
I want something like in #3748

**Comment by chelseakomlo** [comment]
Thanks for the question- we'll track this issue in #419. See the recommended workaround in #3748 in the short term.
