### ISSUE TITLE
Nomad on Windows -- unable to find docker driver

### ISSUE THREAD

**Issue by bis-sb** [hashicorp/nomad#4080]
I have Nomad installed on two Windows servers, on which docker is installed and running containers. For some reason it is unable to find the docker capability, i.e. I view the servers in the Nomad UI and it does not list `driver.docker` as one of its attributes, although it did automatically discover the Java installation. I have 3 Ubuntu servers in the cluster and they all automatically were able to find details about docker, so why is Nomad on Windows not able too? Does it require additional configuration? The configuration for all my Nomad instances is pretty similar:
```
bind_addr = "<redacted IP>"
data_dir = "/tmp/nomad"

server {
	enabled = "true"
	bootstrap_expect = "5"
}

client {
	enabled = "true"
	
    # various things I've tried to get Nomad to "discover" the docker driver
	#options = {
	#	"docker.endpoint" = "npipe:////./pipe/docker_engine"
	#	#"docker.endpoint" = "npipe:////./pipe/docker_engine_windows"
	#}	
	#network_interface = "Ethernet"	
	#network_interface = "vEthernet (HNS Internal NIC) 2"
	#network_interface = "vEthernet (DockerNAT)"
}

vault {
	enabled = "true"
	address = "<vault address>"
}
```

**Comment by angrycub** [comment]
Do you have DEBUG logging enabled?  There is a log event that is emitted if Nomad fails to connect to the Docker daemon that might be able to provide some additional information.  https://github.com/hashicorp/nomad/blob/2f245ac7fc9b916eb4af8a62a471dcd0b468a8c8/client/driver/docker.go#L481 

That error output might help you discern why the Docker fingerprinter isn't seeing your Docker instance.
