### ISSUE TITLE
Nomad Allocs CPU Telemetry Type is Wrong

### ISSUE THREAD

**Issue by hspak** [hashicorp/nomad#4121]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
AWS EC2 m5.large
Ubuntu 16.04

### Issue
The documentation [here](https://www.nomadproject.io/docs/agent/telemetry.html#allocation-metrics) states that the following metrics are percentages.
```
nomad.client.allocs.<Job>.<TaskGroup>.<AllocID>.<Task>.cpu.system
nomad.client.allocs.<Job>.<TaskGroup>.<AllocID>.<Task>.cpu.user
```
However, I see numbers spike to thousands.

### Reproduction steps
- Enable telemetry
```
telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
  prometheus_metrics         = true
}
```
- Query prometheus for `nomad_client_allocs_cpu_user` or `nomad_client_allocs_cpu_system`

**Comment by schmichael** [comment]
While our stats code is similar between many of the drivers it does differ slightly. Are you using Docker?

**Comment by hspak** [comment]
Yes I am! Sorry I left that part out.

**Comment by schmichael** [comment]
@jrasell Good call, that is likely the case.

@hspak Does the host have enough CPU capacity for a container to actually burst to >1000%? If so, the issue is the soft-limiting @jrasell mentioned. Nomad 0.8 will include the option to hard limit CPU resources if you want to prevent a container from using idle cycles.

**Comment by hspak** [comment]
@schmichael Nomad sees that the m5.large instance has 5GHz to allocate and the job I saw this behavior in was set to the default 100MHz so this makes sense.

The metric`nomad.client.allocs.<Job>.<TaskGroup>.<AllocID>.<Task>.cpu.total_percent` is also affected.

Thanks for noting the soft CPU limit for the docker driver atm. I'm going to go ahead and mark this closed.
