### ISSUE TITLE
0.8.0: Jobs w/ no deployments

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#4152]
### Nomad version
Output from `nomad version`
Nomad v0.8.0 (751b42aaa60f1bc679e5062e16db7d15f8ff9654)
### Operating system and Environment details
Amazon Linux
### Issue
API call `/v1/job/<job>/deployment` return `null` for some jobs. I don't know if this is 0.8.0 specific or a side-effect of upgrading with 0.8.0, possibly losing job history on some jobs?

We have code that depend on the API to return an object from this call, except now, some calls return `null`, causing a panic. Easy fix to check if its `null` in the code, but this was a breaking change for us. 

We didn't run into this issue going from 0.7.0 to 0.7.1, and we rotate Nomad servers frequently.

Is this expected?

### Reproduction steps
1. Scroll through jobs
2. Some jobs will have no deployments

**Comment by dadgar** [comment]
Hey @djenriquez,

Nomad 0.7.1 use to make a deployment whenever it was creating allocations for a service job with an update stanza set. Nomad 0.8 now makes a deployment when transitioning a job between versions and for the first placement of a job. 

However, regardless of that change the `/v1/job/<job>/deployment` can always return a `null` value and your code should guard against it. Times the deployment can be null:
* The job is not a service
* The job is a service job but does not define a update stanza
* The deployments for a job have garbage collected

Hope that helps! Let me know if there are any other details you need to get your integration working again!

**Comment by djenriquez** [comment]
This is perfect! We weren't sure of the behavior and this clarified it, we can definitely account for it now. Thank you very much @dadgar !
