### ISSUE TITLE
Issue with rendering template to NOMAD_SECRETS_DIR with env = true

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/nomad#4163]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

v0.7.1

### Operating system and Environment details

Clients and servers are running on ubuntu

### Issue

I would like to set up a template which will render vault secrets to a file in ${NOMAD_SECRETS_DIR} and source them so the project has them in it's env when it starts up.

### Reproduction steps

Here's an example template that would render AWS credentials from vault: 

```
    template {
      data = <<EOH
{{ with secret "aws/creds/my-service" }}
AWS_ACCESS_KEY_ID="{{ .Data.access_key }}"
AWS_SECRET_ACCESS_KEY="{{ .Data.secret_key }}" {{ end }}
EOH

      destination     = "${NOMAD_SECRETS_DIR}/env"
      env                  = true
      change_mode = "restart"
    }
```

However, when I submit the job I get the following error in the task state history (we're using [hashi-ui](https://github.com/jippi/hashi-ui))

> Template: error opening env template: open /var/lib/nomad/data/alloc/306014a2-388a-8fe9-abcf-c9abad5c3e0b/my-service/${NOMAD_SECRETS_DIR}/env: no such file or directory

![image](https://user-images.githubusercontent.com/6126813/38840494-0357de9c-41ae-11e8-8d31-93b2f8e34e81.png)

If I change the destination path to `secrets/env` the error message goes away.

```
    template {
      data = <<EOH
{{ with secret "aws/creds/my-service" }}
AWS_ACCESS_KEY_ID="{{ .Data.access_key }}"
AWS_SECRET_ACCESS_KEY="{{ .Data.secret_key }}" {{ end }}
EOH

      destination     = "secrets/env"
      env                  = true
      change_mode = "restart"
    }
```

I don't see anything of relevance in the nomad client logs or any of the server logs.

**Comment by dadgar** [comment]
@Xopherus Thanks for reporting. I was able to reproduce and hopefully we will get a fix for it soon!

**Comment by Xopherus** [comment]
Great to hear! Thanks for the quick reply @dadgar

**Comment by lzrski** [comment]
I had similar problem and by trial and error got it working with following settings:

```hcl
template {
  data = <<EOF
    important="important value"
    secret="{{with secret "secret/personal"}}{{.Data.gossip}}{{end}}"
    public="{{key "public"}}"
  EOF

  destination = "secrets/file.env"
  env = true
  change_mode = "restart"
}

config {
  image = "alpine"
  entrypoint = [ "cat" ]
  args = [
    "${NOMAD_SECRETS_DIR}/file.env"
  ]
}
```

So apparently the interpolation with `${NOMAD_SECRET_DIR}` is needed *inside* the task container (in args passed to the app), but template can just have literal path to `secrets/`.

⚠️ This seems to be security sensitive and I'm just beginning to learn Nomad and Vault. Please **apply my example with caution** and if you know better, **let me know if I am doing something wrong here*.

**Comment by Xopherus** [comment]
I upgraded to Nomad 0.9 recently and now it looks like this has been fixed! It doesn't look like it's on the changelog, but feel free to close this out! @dadgar

**Comment by k3n** [comment]
I'm still seeing this behavior on v0.10.5+ent.

**Comment by tgross** [comment]
Hi @k3n can you open a new issue with a jobspec describing what you're seeing?
