### ISSUE TITLE
`nomad logs` not working on OS X with default settings and example job

### ISSUE THREAD

**Issue by maxvt** [hashicorp/nomad#4165]
### Nomad version
Nomad v0.8.0 (751b42aaa60f1bc679e5062e16db7d15f8ff9654)

### Operating system and Environment details
macOS High Sierra 10.13.4

### Issue
No logs using the example job

`docker logs` works and shows the Redis logs. Nothing shows up in the alloc dir, and `nomad logs` returns no output. Nomad is started with `-dev`.

This is also reproduced when Nomad job state folder is configured to be the Linux-standard `/var/lib/nomad` instead of the temporary location it chooses by default.

### Reproduction steps
- Run local Nomad in dev mode.
- Create and run an example job.
- `nomad logs` for the example job produces no output.

**Comment by dadgar** [comment]
Closing as this is expected and explained by the link @angrycub posted.
