### ISSUE TITLE
[question] What does "error collecting stats from container: io: read/write on closed pipe" mean?

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#4177]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Ubuntu

### Issue
Our logs are absolutely littered with:

```
2018/04/18 20:13:58.308478 [DEBUG] driver.docker: error collecting stats from container e5bc854944bf0d0fa886b122afa944a8c79942418648e43f88835beeb03c7632: io: read/write on closed pipe
    2018/04/18 20:13:58.332421 [INFO] client: task "downloader" for alloc "538b056c-d002-e5b0-7ff6-e1347888c0f5" completed successfully
    2018/04/18 20:13:58.332456 [INFO] client: Not restarting task: downloader for alloc: 538b056c-d002-e5b0-7ff6-e1347888c0f5
    2018/04/18 20:13:58.332692 [DEBUG] driver.docker: image id "sha256:a9f4f5206dd0035f011c4fba726750e99315d83031626cf49771f52f18266d35" reference count decremented: 5
    2018/04/18 20:13:58.344448 [INFO] client.gc: marking allocation 538b056c-d002-e5b0-7ff6-e1347888c0f5 for GC
    2018/04/18 20:13:58.521827 [DEBUG] client: updated allocations at index 6800 (total 136) (pulled 1) (filtered 135)
    2018/04/18 20:13:58.523995 [DEBUG] client: updated allocations at index 6801 (total 137) (pulled 2) (filtered 135)
```

What does this mean? What's causing it? Our guess is jobs that start and stop too quickly for the stats to be picked up - but we have so many short jobs, our stats will be off if these aren't included? Should I be concerned about this message - if not, can it be filtered out? I've looked and can't find any explanation of this message other than other tickets on this issue tracker.

We are using Docker, dispatch jobs and the `awslogs` logging config.

**Comment by preetapan** [comment]
@Miserlou you can safely ignore that particular message - its because the container has already shutdown. It doesn't mean that stats were not collected for your container. 

We have some plans to make that error message here more useful in a future Nomad release. It will only log legitimate errors after that change goes out.

**Comment by Miserlou** [comment]
Where is the ticket for "We have some plans to make that error message here more useful in a future Nomad release" ?
