### ISSUE TITLE
deb/rpm packages

### ISSUE THREAD

**Issue by benmccann** [hashicorp/nomad#418]
[The docs](https://www.nomadproject.io/docs/install/index.html) say "We do not have any near term plans to provide system packages."  However, I thought I would file an issue to be able to track whether any work is done on this front. It would be much easier for us operationally as currently everything we deploy is packaged as a .deb package.

**Comment by cbednarski** [comment]
@benmccann Thanks for the suggestion. We don't have plans to do this. We don't have a good way to update these packages if they're pushed into official repos, and we also don't have the infrastructure to build / test / host these via PPA or private mirrors or similar.

We already support a fair number of OS and architecture permutations and adding distro flavors and versions to the mix would increase the number of builds significantly.
