### ISSUE TITLE
Vault secret templating

### ISSUE THREAD

**Issue by CGreenburg** [hashicorp/nomad#4182]
### Nomad version
Nomad v0.8.1 (46aa11ba851f114f5faa0876839b45fbca0c47f0)
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')

### Operating system and Environment details
MacOS 10.13.4

### Issue
Updating Nomad and Vault to the latest version breaks nomad templating. I'm unable to get secrets from vault in the template stanza. Nomad tells me the secret doesn't exist.

### Reproduction steps
1. Install the above versions
2. Put secret in vault (`vault kv put secret/foo bar=baz`)
3. Create nomad job grabbing the vault secret like so:
```
      template {
        data = <<EOH
        ENVVAR="{{with secret "secret/foo"}}{{.Data.bar}}{{end}}"
EOH
        destination = "secrets/file.env"
        env         = true
      }
```

**Comment by dadgar** [comment]
Hey @CGreenburg,

@jrasell answer is correct. To give a little more color, Vault 0.10 has two different versions of the K/V backend. Depending on which version you are using the path to secret data will vary. You can pick which version k/v is mounted, but the dev server by default mounts version 2, which may be what you are experiencing. Here is a link to the Vault docs: https://www.vaultproject.io/api/secret/kv/index.html

Thanks,
Alex

**Comment by CGreenburg** [comment]
I've finally been able to test @jrasell's solution, and it didn't work. However the following did:

```
      template {
        data = <<EOH
        ENVVAR="{{with secret "secret/data/foo"}}{{.Data.data.bar}}{{end}}"
EOH
        destination = "secrets/file.env"
        env         = true
      }
```

After reading through the documentation, having the extra "data" portion in the path seems to make a little sense.. it'll take a little time to get used to though. Thanks for your help.
