### ISSUE TITLE
Configurable labels for metrics

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/nomad#4186]
Hi,

There are configurable options to include hostname in the metrics id (`disable_hostname`)

Is it possible to make labeling of metrics a configurable option?
This way workers can send metrics with the same name which makes it very easy to aggregate them in logging/monitoring systems like cloudwatch. Right now cloudwatch can't deal with aggregation of different metrics. This also allows saving some $$ in cases when metrics priced for one. 

Thanks!

**Comment by dadgar** [comment]
Is what you are looking for just disabling tagged metrics? If so you can set this to true: https://www.nomadproject.io/docs/agent/configuration/telemetry.html#backwards_compatible_metrics

**Comment by scalp42** [comment]
@dadgar would it be possible to revisit sending tags with StatsD as Graphite supports tags? see https://graphite.readthedocs.io/en/latest/tags.html
