### ISSUE TITLE
Percentage based `MaxParallel` deployments

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#4197]
Often in highly dynamic environments, we are unaware of how many of a particular job is running. Because of this, defining a static `MaxParallel` can be either annoying or troublesome for continuous deployment environments.

If the count is low, too many jobs may be taken down at one point in time, causing availability issues. If the count is too high, too few jobs may be rotated in, causing a lengthy deployment. I believe it is very useful to define a percentage based `MaxParallel` because that is not dependent on the count active and can lead to more predictable behaviors during deployments.

Also, deployments should allow an overage of jobs such that a deployment has the ability to over-allocate before reaching the desired count. This would be made possible with percentage based deployments if a "Max Healthy" configuration was defined at a percentage higher than 100%.

This has proven very useful in ECS, and I believe will have a good place here as well: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/update-service.html

**Comment by jippi** [comment]
+1 on this - i've ended up doing this in our own internal deployment tool

```
func processUpdateStanza(group *nomad.TaskGroup, defaultUpdate *nomad.UpdateStrategy, environment string) error {
	if group.Update == nil {
		group.Update = defaultUpdate
	}

	meta := group.Meta

	// no meta config, no changes
	if len(meta) == 0 {
		return nil
	}

	parallelRaw, configured := meta[fmt.Sprintf("update.%s.max_parallel", environment)]
	if !configured {
		return nil
	}

	// percent of the group size
	if strings.HasSuffix(parallelRaw, "%") {
		parallelPercent, err := strconv.Atoi(strings.TrimSuffix(parallelRaw, "%"))
		if err != nil {
			return err
		}

		if parallelPercent > 100 {
			return fmt.Errorf("percent must be between 0 and 100")
		}

		parallel := ((float64(*group.Count) * float64(parallelPercent)) / float64(100))
		group.Update.MaxParallel = helpers.IntToPtr(int(parallel))
		return nil
	}

	// assume it's a plan number
	parallel, err := strconv.Atoi(parallelRaw)
	if err != nil {
		return err
	}

	group.Update.MaxParallel = helpers.IntToPtr(parallel)
	return nil
}

```

**Comment by dadgar** [comment]
Closing in favor of https://github.com/hashicorp/nomad/issues/2810
