### ISSUE TITLE
periodic doesn't run bash script

### ISSUE THREAD

**Issue by vicsoulz** [hashicorp/nomad#4198]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.8.1 

### Operating system and Environment details
MAC OS
### Issue
periodic doesn't run bash script

> job file
```
job "test" {
  datacenters = ["dc1"]

  type = "batch"

  periodic {
    cron             = "*/1 * * * * *"
    prohibit_overlap = true
  }

  task "run-test" {
    driver = "raw_exec"
    config {
      command = "/bin/bash"
      args = ["touch","text.txt"]
    }
  }
}
```
> client file
```
bind_addr = "0.0.0.0"

log_level = "DEBUG"

data_dir = "/xxx/data/client1"

name = "client1"

client {
    enabled = true
    options {
        "driver.raw_exec.enable" = "1"
    }
    servers = ["127.0.0.1:4647"]
}

ports {
    http = 5657
}
```
job status is dead,but no file were created

**Comment by shantanugadgil** [comment]
hi @vicsoulz the syntax of the command and args doesn't seem to be correct.

The final form of the cmd would look like:
/bin/bash touch text.txt

it should either be:
/usr/bin/touch
text.txt

or
/bin/bash
-c 
touch text.txt

HTH,
Shantanu
