### ISSUE TITLE
Docker image with sha256 doesn't work

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#4211]
### Nomad version

`0.7.1`

### Issue

```
config {
  image = "x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6
}
```

fails with the following error in Nomad

```
failed to initialize task "server" for alloc "9fddd7ed-beba-584f-3905-e445f7d3b906": Failed to pull `x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6`: API error (404): {"message":"manifest for x.dkr.ecr.x.amazonaws.com/app/x:latest not found"}
```

while `docker run` works fine with the same value

```
docker run --rm -it x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6 bash
```

### Expected outcome

Like `docker run` Nomad should support format `${registry}/${image}@sha256:${sha256_value}`

Currently nomad only supports `${registry}/${image}:${some_tag}@sha256:${sha256_value}`

The `${some_tag}` should be optional :)

**Comment by chelseakomlo** [comment]
Thanks for reporting this. The second format you posted is the same as the first (at first glance), did you mean to post something else? 

`x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6`

`x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6`

**Comment by jippi** [comment]
@chelseakomlo no, its the same, i've updated it to put emphasis on being `docker run` where the format works - but is rejected by nomad :)

**Comment by chelseakomlo** [comment]
Understood, thanks for confirming.
