### ISSUE TITLE
When does Nomad forget Job Versions

### ISSUE THREAD

**Issue by abergmeier** [hashicorp/nomad#4242]
If filing a bug please include the following:

### Nomad version
0.7.1

### Operating system and Environment details
Ubuntu 16.04.2

### Issue
For some Jobs, Nomad "forgets" previous Versions while for others they seem to persist. Under what circumstances does Nomad forget Job Versions.
Optimally I would of course love for Nomad to never forget Versions.

### Reproduction steps
Just happens. No idea how to provoke that.

**Comment by schmichael** [comment]
Nomad only keeps the last 6 versions of a job as all versions of all jobs must fit in memory: https://github.com/hashicorp/nomad/blob/v0.8.3/nomad/structs/structs.go#L1894-L1896

Making the limit globally configurable wouldn't be difficult, so feel free to open a feature request for that.

Persisting them on disk so memory constraints are no longer an issue is something we'd like to do but unfortunately there's no timeline on that.

**Comment by shantanugadgil** [comment]
@schmichael when you folks do consider persisting more jobs, do see if you could make it configurable by time as well, e.g. "2d" etc.

I think folks coming from an HPC scheduler world would find that as their need :)
