### ISSUE TITLE
Feature Request: canaries are marked somehow

### ISSUE THREAD

**Issue by jolexa** [hashicorp/nomad#4243]
Hello,

I would like to formally request a feature. In our case, when we are using canaries, we would like to have some sort of marker on the canary instances so we can distinguish them in a log aggregation tool easier before promotion. With this, we can then develop some automation to check for errors in the canary instance and either promote or fail

Some possible ideas that we can work with:
- `CANARY=true` env var
- job name is automatically appended to with some marker and removed when promoted

**Comment by angrycub** [comment]
Coming soon via #4200!  🎉

**Comment by angrycub** [comment]
Sorry, I noticed the finer point about environment.  Was so excited about the upcoming feature I might have missed some nuances.

**Comment by jolexa** [comment]
> Sorry, I noticed the finer point about environment. Was so excited about the upcoming feature I might have missed some nuances.

I didn't think about tags in consul, that should work for our purposes too (as I understand it)

**Comment by jolexa** [comment]
@preetapan / @angrycub I do believe that we want to access such information from _outside_ the task (via some API) so let's truly close this! Thanks!
