### ISSUE TITLE
nomad kicking out allocation when there is sufficient resource

### ISSUE THREAD

**Issue by hbasappa** [hashicorp/nomad#4244]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
centos 7 
### Issue
We have a bunch of system and service jobs running on all nodes. While reloading one node, we are seeing that all service jobs are moving to node2.  During this time, nomad is stopping a system job on node 2 when there is sufficient resources on other nodes.

When node 1 comes back up and if we do restart of nomad on node 2 then the sys container is starting.

### Nomad Server logs (if appropriate)

nomad alloc-status aee404cc
ID                  = aee404cc
Eval ID             = a6c059ac
Name                = jobname11-PetSysService.sysdb11[0]
Node ID             = 9c8b93e7
Job ID              = jobname11-PetSysService
Job Version         = 0
Client Status       = complete
Client Description  = <none>
Desired Status      = stop
Desired Description = alloc not needed due to job update
Created             = 1h57m ago
Modified            = 1h2m ago

Task "syscontainer11" is "dead"
Task Resources
CPU       Memory   Disk     IOPS  Addresses
1000 MHz  2.0 GiB  300 MiB  0     sysport11: 10.0.0.2:10011

Task Events:
Started At     = 05/02/18 15:46:36 UTC
Finished At    = 05/02/18 16:41:40 UTC
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                   Type        Description
05/02/18 16:41:39 UTC  Killed      Task successfully killed
05/02/18 16:41:39 UTC  Killing     Sent interrupt. Waiting 5s before force killing
05/02/18 15:46:36 UTC  Started     Task started by client
05/02/18 15:46:34 UTC  Task Setup  Building Task Directory
05/02/18 15:46:34 UTC  Received    Task received by client

### Nomad Client logs (if appropriate)

2018-05-02T15:46:34.301Z [DEBUG] plugin: waiting for RPC address: path=/usr/bin/nomad
2018-05-02T15:46:34.317Z [DEBUG] plugin.nomad: plugin address: timestamp=2018-05-02T15:46:34.317Z address=/tmp/plugin635413541 network=unix
    2018/05/02 15:46:34.731883 [INFO] driver.docker: created container 9844e9cc7638d36f2027c0f4481bab6e8747fdd96f396933084e7b63b23e9b45
2018-05-02T15:46:34.788Z [DEBUG] plugin: starting plugin: path=/usr/bin/nomad args="[/usr/bin/nomad executor {"LogFile":"/data2/third-party/nomad/data/alloc/aee404cc-6d51-2715-c878-d27ce6cbab6c/syscontainer11/executor.out","LogLevel":"INFO"}]"
    2018/05/02 16:06:20 [INFO] serf: EventMemberUpdate: node1
    2018/05/02 16:06:31.773898 [INFO] driver.docker: stopped container cfdc338f1e4dc1032be81957f0aa1be6ade6fe56994672939e1a09f2cf074a76
2018-05-02T16:06:31.777Z [DEBUG] plugin: plugin process exited: path=/usr/bin/nomad
    2018/05/02 16:06:32.877535 [INFO] client.gc: marking allocation 43d7d1e5-d60d-5a88-e45f-01a00a7c30fa for GC
2018-05-02T16:06:32.892Z [DEBUG] plugin: starting plugin: path=/usr/bin/nomad args="[/usr/bin/nomad executor {"LogFile":"/data2/third-party/nomad/data/alloc/d748e19c-f317-ed6a-5035-208337c7d415/es/executor.out","LogLevel":"INFO"}]"
2018-05-02T16:06:32.892Z [DEBUG] plugin: waiting for RPC address: path=/usr/bin/nomad
2018-05-02T16:06:32.908Z [DEBUG] plugin.nomad: plugin address: timestamp=2018-05-02T16:06:32.908Z address=/tmp/plugin135848928 network=unix
    2018/05/02 16:06:33.422005 [INFO] driver.docker: created container 8fe0e6cf7173681ea3ba127b4e13f366500c1a7fe987560dfee2cc0378179430
    2018/05/02 16:06:33.539164 [INFO] driver.docker: started container 8fe0e6cf7173681ea3ba127b4e13f366500c1a7fe987560dfee2cc0378179430
    2018/05/02 16:06:33.550859 [WARN] client: error fetching stats of task es: stats collection hasn't started yet
    2018/05/02 16:36:13.964192 [INFO] client.gc: garbage collecting allocation 60d14c35-0884-938d-1131-a74481aa46c5 due to forced collection
    2018/05/02 16:41:39.626202 [INFO] driver.docker: stopped container fd3078f1ad881f345c51009ecf7bb10bf3e4c1dcb6cee2431ff6cab4ce52df3a
2018-05-02T16:41:39.629Z [DEBUG] plugin: plugin process exited: path=/usr/bin/nomad
    2018/05/02 16:41:40.254434 [INFO] client.gc: marking allocation aee404cc-6d51-2715-c878-d27ce6cbab6c for GC

node2:> nomad node-status  9c8b93e7
ID      = 9c8b93e7
Name    = node2
Class   = <none>
DC      = dc1
Drain   = false
Status  = ready
Drivers = docker,exec
Uptime  = 4h7m26s

Allocated Resources
CPU              Memory         Disk             IOPS
20000/20000 MHz  40 GiB/62 GiB  5.9 GiB/169 GiB  0/0

node3:> nomad node-status 0cceb2c4
ID      = 0cceb2c4
Name    = node3
Class   = <none>
DC      = dc1
Drain   = false
Status  = ready
Drivers = docker,exec
Uptime  = 4h4m58s

Allocated Resources
CPU              Memory         Disk             IOPS
14000/20000 MHz  28 GiB/63 GiB  4.1 GiB/169 GiB  0/0

### Job file (if appropriate)

{
    "Job": {
        "AllAtOnce": false,
        "Constraints": null,
        "CreateIndex": 1485,
        "Datacenters": [
            "dc1"
        ],
        "ID": "jobname11-PetSysService",
        "JobModifyIndex": 1485,
        "Meta": null,
        "ModifyIndex": 1485,
        "Name": "jobname11-PetSysService",
        "Namespace": "default",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 1,
        "Region": "global",
        "Stable": false,
        "Status": "running",
        "StatusDescription": "",
        "Stop": false,
        "SubmitTime": 1525279415266646572,
        "TaskGroups": [
            {
                "Constraints": null,
                "Count": 1,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "Meta": null,
                "Name": "sysdb11",
                "RestartPolicy": {
                    "Attempts": 10,
                    "Delay": 25000000000,
                    "Interval": 300000000000,
                    "Mode": "delay"
                },
                "Tasks": [
                    {
                        "Artifacts": null,
                        "Config": {
                            "image": "redis:3.2",
                            "network_mode": "host",
                            "volumes": [
                            ],
                            "args": [
                                "--port 10011"
                            ],
                            "command": ""
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "docker",
                        "Env": null,
                        "KillSignal": "",
                        "KillTimeout": 5000000000,
                        "Leader": false,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "syscontainer11",
                        "Resources": {
                            "CPU": 1000,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 2048,
                            "Networks": [
                                {
                                    "CIDR": "",
                                    "Device": "",
                                    "DynamicPorts": null,
                                    "IP": "",
                                    "MBits": 10,
                                    "ReservedPorts": [
                                        {
                                            "Label": "sysport11",
                                            "Value": 10011
                                            }
                                    ]
                                }
                            ]
                        },
                        "Services": [
                            {
                                "AddressMode": "host",
                                "CheckRestart": null,
                                "Checks": null,
                                "Id": "",
                                "Name": "redissys11",
                                "PortLabel": "sysport11",
                                "Tags": null
                            }
                        ],
                        "ShutdownDelay": 0,
                        "Templates": null,
                        "User": "",
                        "Vault": null
                    }
                ],
                "Update": null
            }
        ],
        "Type": "system",
        "Update": {
            "AutoRevert": false,
            "Canary": 0,
            "HealthCheck": "",
            "HealthyDeadline": 0,
            "MaxParallel": 0,
            "MinHealthyTime": 0,
            "Stagger": 0
        },
        "VaultToken": "",
        "Version": 0
    }
}

**Comment by schmichael** [comment]
How long is node 1 down? If `nomad node status` reports node 1 as `lost` all of its allocations will be rescheduled elsewhere. The leader server will also log when clients miss their heartbeats and become `lost`. You can tune the amount of time before a node is considered `lost` with the "heartbeat" related server settings: https://www.nomadproject.io/docs/agent/configuration/server.html#heartbeat_grace

System - or any other - allocations should never be stopped to make room for other allocations, so I'm not sure what's going on there.

Can you look up the evaluation ID listed on that allocation using the API? https://www.nomadproject.io/api/evaluations.html#read-evaluation

It may provide more details as to why it was stopped.
