### ISSUE TITLE
Feature request: support initiating shutdown via http calls instead of kill_signal

### ISSUE THREAD

**Issue by yaroot** [hashicorp/nomad#4253]
In some framework or runtime, it's much easier to deal with graceful shutdown via http calls than signals, apache aurora supports it[1].

Usually this doesn't matter because one can use ShutdownDelay to stop the instance for serving request, how it's killed usually does not matter, but in some case it does help.

[1] http://aurora.apache.org/documentation/0.8.0/user-guide/#http-health-checking-and-graceful-shutdown

**Comment by preetapan** [comment]
@yaroot thanks for the suggestion

For some clarity, Aurora is a framework on top of Mesos, so its API and architectural decisions are based on the fact that the scheduler is another layer/framework on top of resource offers from Mesos. Nomad's  
architecture is much simpler where direct access to the client node running the task is needed if the operator wants to kill the task by sending a signal. 

All that being said, this is an interesting idea Do you mind sharing more details about your use case?

**Comment by yaroot** [comment]
Aurora uses its own agent to manage the task lifecycle, it will do a SIGTERM if the task does not respond to the abort/quit http calls. The agent is launched by mesos agent and running locally alongside the task, no remote calls, it's not a architecture problem.

I don't have any particular use case right now, just some thoughts from previous job.

**Comment by dadgar** [comment]
Hm, this seems like a bit of scope bloat. This can be accomplished by having another task in the group dial the HTTP endpoint when it has received the signal.
