### ISSUE TITLE
cpu.frequency and cpu.totalcompute are incorrect

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#4258]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
```
~ $ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
~ $ uname -r
4.14.33-3.el7.x86_64
```
### Issue
Nomad calculates wrong value of cpu.totalcompute and observes wrong value of cpu.frequency.
For instance for server with  2x Intel Xeon E5-2620v4 2.1Ghz CPU nomad reports:
```
cpu.numcores | 32
cpu.frequency | 3000
cpu.modelname | Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
cpu.totalcompute | 96000
```
Though according dmidecode and CPU specs cpu.frequency should be 2100MHz:
```
~ $ sudo dmidecode -t 4 | grep 'Current\ Speed'
        Current Speed: 2100 MHz
        Current Speed: 2100 MHz
```

Issue looks related with https://github.com/hashicorp/nomad/issues/4233

**Comment by dvusboy** [comment]
Are you expecting 32 x 2100 for `cpu.totalcompute`? The problem with that is power management via frequency scaling of the CPUs. This is why Nomad uses the value of `/sys/devices/system/cpu/cpu*/cpuinfo_max_freq` to set `cpu.frequency`. That determines the maximum resource available, regardless the current frequency of the CPU cores. #4233 refers to the situation when `cpuinfo_max_freq` is not reported on some VM situations. The proposal there is to use `dmidecode` to get the value. Although, I must say, I've also seen discrepancy between the `Max Speed` reported by `dmidecode`, and the `cpuinfo_max_freq`. For example, I'm seeing:

```
# cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
3000000
# dmidecode -t processor | fgrep 'Max Speed'
	Max Speed: 4000 MHz
```

**Comment by pznamensky** [comment]
Got it.
Indeed, the point of truth is `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`.
@dvusboy thanks.
