### ISSUE TITLE
NOMAD_ALLOC_INDEX inconsistent

### ISSUE THREAD

**Issue by cognitiaclaeves** [hashicorp/nomad#4264]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
( Nodes are 0.8.3+ent )

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)

### Issue
NOMAD_ALLOC_INDEX appears to be inconsistent, if the count of the tasks > the original count of the tasks at first deployment.

### Reproduction steps
Create a job that prints NOMAD_ALLOC_INDEX. Deploy a single instance of the job. In my case, it was a task that included a python tornado server with a /status endpoint that printed the hostname from the socket, and the environment variables NOMAD_ALLOC_INDEX, NOMAD_JOB_NAME, and NOMAD_TASK_NAME.

After seeing that the first instance was healthy, I then changed the count to 3 on the task and redeployed the same HCL. Two more instances were added, as expected. But Two of the instances had the same NOMAD_ALLOC_INDEX.

We use NOMAD_ALLOC_INDEX in order to get visualizations and statistics in a way that doesn't grow without bound. Matching allocation indexes will potentially mask visibility / reporting of issues.

Here is the output from accessing the job, after changing the count to 3 for the task:

```
$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **76d075093bae** [Nomad AllocIndex **1** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]

$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **548b8fb5e58f** [Nomad AllocIndex **0** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]

$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **4d870d14ae7d** [Nomad AllocIndex **0** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]
```

Note that two hosts have the same alloc index, above.

I hypothesized that completely stopping the job and restarting with the final intended count of the task would result in each task having a unique allocation index.

After completely stopping the job (I did not purge it), and redeploying the count of three, the allocation indexes were as expected:

```
$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **0937fa3bc416** [Nomad AllocIndex **2** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]

$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **9c354cf98868** [Nomad AllocIndex **1** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]

$ curl http://fabio-foo-lb.service.austin-staging.q2consul-stage/foo/bar/wedge/status
Red Two standing by.<br/><br/>Hostname: **92a32e2d461e** [Nomad AllocIndex **0** of rfa-dev-q2w-login-wedge-austin-staging/rfa-dev-q2w-login-wedge]
```

I further hypothesize that if I were to promote double the number of instances currently running that the number of hosts with duplicate allocation indexes may double as well.

If this behavior is intended, is there another way to get a unique number to the running job (instead of a completely unique identifier for each task?)

**Comment by dadgar** [comment]
@cognitiaclaeves Can you share the job? Does it have canaries? Do you have a job spec you could share that reproduces this?

**Comment by dadgar** [comment]
@cognitiaclaeves Further there is no guarantee that the index will be unique. We attempt to make this value unique from 0 to count-1 but when you have canaries on the task group then there are reused indexes since you have multiple job versions running at the same time.

You can get a unique number by using a pairing function where the inputs are the job version and the alloc index

**Comment by cognitiaclaeves** [comment]
@dadgar , No I don't think I can share the job. It will take time to work up an example that I can share. ... Don't suppose you happen to know of an example job that would be easy to change into a job that prints those env variables? I could then restructure that job to match the same behavior I'm seeing.

Judging from your description of the pairing function, you seem to be describing a situation where a deployment hasn't been promoted. The issue I'm seeing is after fully promoting a deployment. ... So there should be only one version, right? And the allocation indexes should all be unique? The job did have a single canary. I would expect a duplicate allocation index for any canaries. And I would expect that after the deployment was promoted, that the indexes would all again be unique.

Using a pairing function like you describe would cause the same issues we had before we settled on the allocation index: we really do need something that re-uses itself when the job is restarted, but is unique within the context of the job.

**Comment by dadgar** [comment]
@cognitiaclaeves Yes your description is correct and I understand your concern with the pairing function. The index should be unique post promotion and if it isn't that is a bug. You should be able to just use a command such as:

```
driver = "raw_exec"
config {
  command = "bash"
  args = ["-c", "env && sleep 10000"]
}
```

And then you can have an update block that creates canaries.

**Comment by wlonkly** [comment]
I'm currently experiencing the situation where the index is not unique within a job version, post-promotion. (This has happened a couple times for us, but this is the first time it was brought to my attention.) One of our developers says that it started miscounting after a failed deployment where nobody manually promoted the new job.

<img width="1188" alt="screen shot 2019-01-11 at 10 34 34 am" src="https://user-images.githubusercontent.com/1545955/51043372-84da1400-158c-11e9-8f4f-7f92a40785b9.png">

Nomad version is 0.8.4 running on Ubuntu 16.04. 

We also use `NOMAD_ALLOC_INDEX` as a dimension in our monitoring/metrics, so having duplicate indexes definitely gets in our way.  I can't tell if this is exactly the issue that the original reporter encountered or not, but figured I'd start here rather than in a new bug. I'm going to spend a little time seeing if I can reproduce it with a simpler job. 

Job file is behind the cut here: (we use `levant` so there's some extra templating in there, but I think the important parts are legibile):
<details>

```
job "bff-mobile-[[ .short_environment ]]" {
  type = "service"

  datacenters = [
    [[ range $datacenter := .datacenters -]]
      "[[- $datacenter ]]",
    [[ end -]]
  ]

  meta {
    pd_owner = "Mobile Core"
    SPLUNK_INDEX = "bff-mobile"
  }

  update {
    max_parallel  = 1
    health_check  = "checks"
    min_healthy_time = "30s"
    healthy_deadline = "2m"
    auto_revert      = true
    stagger          = "30s"
    canary           = 1
  }

  migrate {
    max_parallel  = 1
    health_check  = "checks"
    min_healthy_time = "30s"
    healthy_deadline = "2m"
  }

  group "[[ .environment ]]" {
    count = [[ .count ]]

    task "bff-app" {
      driver = "docker"

      config {
        image = "pagerduty-docker.jfrog.io/bff-mobile:[[ .DEPLOY_SUB___VERSION ]]"

        port_map {
          http = 8080
        }
      }

      service {
        name = "bff-mobile"
        tags = ["[[ .environment ]]"]
        port = "http"

        check {
          type = "http"
          port = "http"
          protocol = "http"
          path = "/health"
          interval = "5s"
          timeout = "2s"

          check_restart {
            limit = 2
            grace = "30s"
          }
        }
      }

      vault {
        policies = ["bff-mobile"]
      }

      template {
        data = <<EOH
          {{- with $id := secret (printf "secret/bff-authentication/shared/%s/hmac/active_key_id" (env "VAULT_ENV")) }}
          {{- range $idkey, $idvalue := $id.Data }}
            ACTIVE_HMAC_KEY_ID={{ $idvalue }}
          {{- with $s := secret (printf "secret/bff-authentication/shared/%s/hmac/keys" (env "VAULT_ENV")) }}
          {{- range $k, $v := $s.Data }}
          {{- if eq $idvalue $k }}
            HMAC_KEY={{ $v }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
        EOH
        destination = "local/bff-mobile.env"
        env = true
        change_mode = "restart"
      }

      resources {
        cpu = 8000
        memory = 1024
        network {
          port "http" {}
        }
      }

      env {
        PD_ENV = "[[ .environment ]]"
        VAULT_ENV = "[[ .environment ]]"
        LOCAL_HOSTNAME = "${attr.driver.docker.bridge_ip}"
      }

      meta {
        SPLUNK_SOURCETYPE = "log4j"
      }
    }

    task "bff-nginx" {
      driver = "docker"

      config {
        image = "pagerduty-docker.jfrog.io/nginx:1.15.2"

        args = [
          "-c", "/local/nginx.conf",
          "-g", "daemon off;"
        ]

        command = "nginx"

        port_map {
          proxy = 80
          authservice = 5315
        }
      }

      env {
        SHORT_ENV = "[[ .short_environment ]]"
        PD_DOMAIN = "[[ .pd_domain ]]"
        MESOS_TAG = "[[ .mesos_tag ]]"
        ENVIRONMENT = "[[ .environment ]]"
      }

      artifact {
        source = "https://_:[[.DEPLOY_SUB___GITHUB_OAUTH_TOKEN]]@raw.githubusercontent.com/PagerDuty/bff-mobile/[[.DEPLOY_SUB___VERSION]]/infra/app-config/templates/nginx.conf"
        destination = "local/"
      }

      artifact {
        source = "https://_:[[.DEPLOY_SUB___GITHUB_OAUTH_TOKEN]]@raw.githubusercontent.com/PagerDuty/bff-mobile/[[.DEPLOY_SUB___VERSION]]/infra/app-config/templates/global_log_formats.conf"
        destination = "local/"
      }

      artifact {
        source = "https://_:[[.DEPLOY_SUB___GITHUB_OAUTH_TOKEN]]@raw.githubusercontent.com/PagerDuty/bff-mobile/[[.DEPLOY_SUB___VERSION]]/infra/app-config/templates/upstream_services.conf.tpl"
        destination = "local/"
      }

      template {
        source = "local/upstream_services.conf.tpl"
        destination = "local/upstream_services.conf"
        change_mode = "signal"
        change_signal = "SIGHUP"
      }

      resources {
        cpu = 4000
        network {
          port "proxy" {}
          port "authservice" {}
        }
      }

      meta {
        SPLUNK_SOURCETYPE = "nginx_access"
      }
    }

    restart {
      interval = "10m"
      attempts = 1
      delay = "3s"
      mode = "fail"
    }

    constraint {
      # this constraint forces all task groups to run on separate hosts
      operator = "distinct_hosts"
      value = "true"
    }
  }
}
```
</details>

**Comment by wlonkly** [comment]
Hah, I was able to reproduce it. In the case I was able to reproduce, it looks like it happens when a new canary allocation fails to start, and then the deployment is failed.

Test job file:
```
job "indexlogger" {
  region = "global"
  datacenters = ["nomad-sandbox"]

  update {
    max_parallel = 3
    health_check = "task_states"
    canary = 1
    auto_revert = true
    healthy_deadline = "1m"
    progress_deadline = "2m"
  }

  group "infra" {
    count = 3
    task "indexlogger" {
      driver = "docker"

      config {
        image = "busybox"
        command = "sh"
        args = ["-c", "echo $NOMAD_ALLOC_INDEX; sleep 86401"]
      }

      resources {
        cpu = 100
        memory = 32
      }
    }
  }
}
```

Transcript of reproduction steps:
```
$ nomad run indexlogger
==> Monitoring evaluation "59ddefc0"
    Evaluation triggered by job "indexlogger"
    Evaluation within deployment: "e247f02c"
    Allocation "1c78d5cc" created: node "740de4f3", group "infra"
    Allocation "354e3080" created: node "beba0998", group "infra"
    Allocation "b96c922b" created: node "153d1f69", group "infra"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "59ddefc0" finished with status "complete"
$ nomad status indexlogger  | awk '/run.*running/ {print $1}' | while read ALLOC; do echo $ALLOC $(nomad logs $ALLOC); done
354e3080 1
b96c922b 2
1c78d5cc 0

# now update indexlogger.nomad to have a command that fails, eg 'command = "honk"'

$ nomad run indexlogger.nomad
==> Monitoring evaluation "fb80c84a"
    Evaluation triggered by job "indexlogger"
    Evaluation within deployment: "f2c02e4c"
    Allocation "94e7cc29" created: node "153d1f69", group "infra"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "fb80c84a" finished with status "complete"

$ nomad deployment list
ID        Job ID       Job Version  Status      Description
f2c02e4c  indexlogger  13           running     Deployment is running but requires promotion
[...]

$ nomad deployment fail f2c02e4c
Deployment "f2c02e4c-300e-372b-5b73-2e43437dbf5d" failed. Auto-reverted to job version 12.

==> Monitoring evaluation "b1187b04"
    Evaluation triggered by job "indexlogger"
    Evaluation within deployment: "f2c02e4c"
    Allocation "24a27405" created: node "153d1f69", group "infra"
    Allocation "1c78d5cc" modified: node "740de4f3", group "infra"
    Allocation "354e3080" modified: node "beba0998", group "infra"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "b1187b04" finished with status "complete"


$ nomad status indexlogger  | awk '/run.*running/ {print $1}' | while read ALLOC; do echo $ALLOC $(nomad logs $ALLOC); done
24a27405 0
1c78d5cc 0
354e3080 1
```

**Comment by wlonkly** [comment]
(One thing I think is relevant in that example is that allocations `1c78d5cc` and `354e3080` were never stopped, they just had their job version updated when the canary deployment was failed.)
