### ISSUE TITLE
set_contains constraint value not interpolating 

### ISSUE THREAD

**Issue by daledude** [hashicorp/nomad#4270]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
Ubuntu 16.04

### Issue
I have 2 nomad clients with meta.environment set. Using a variable inside of a set_contains constraint value doesn't work.

### Reproduction steps
With this nomad job:
```
job "job" {
  datacenters = ["la"]
  type = "service"
  meta {
    required_environment = "staging"
  }
  constraint {
    attribute = "${meta.environments}"
    operator  = "set_contains"
    value     = "${NOMAD_META_required_environment}"
  }

  group "job-group" {
    count = 1
    task "job-task" {
      driver = "raw_exec"

      env {
        CONTAINER_ENVIRONMENT = "${NOMAD_META_required_environment}"
      }
      config {
        command = "uptime"
      }
    }
  }
}
```
The plan receives this issue:
```
+ Job: "job"
+ Task Group: "job-group" (1 create)
  + Task: "job-task" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "job-group" (failed to place 1 allocation):
    * Constraint "${meta.environments} set_contains ${NOMAD_META_required_environment}" filtered 2 nodes
```

If I hard code the constraint value then it will schedule the tasks.
```
job "job" {
  datacenters = ["la"]
  type = "service"
  meta {
    required_environment = "staging"
  }
  constraint {
    attribute = "${meta.environments}"
    operator  = "set_contains"
    value     = "${NOMAD_META_required_environment}"
  }

  group "job-group" {
    count = 1
    task "job-task" {
      driver = "raw_exec"

      env {
        CONTAINER_ENVIRONMENT = "${NOMAD_META_required_environment}"
      }
      config {
        command = "uptime"
      }
    }
  }
}
```

```
+ Job: "job"
+ Task Group: "job-group" (1 create)
  + Task: "job-task" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.
```

**Comment by dadgar** [comment]
Hey interpolation is only supported on the client and not server thus limiting where it may be used in the job specification and at this time constraints are not supported. Closing in favor of https://github.com/hashicorp/nomad/issues/1185 as it tracks the need for full job interpolation.

**Comment by daledude** [comment]
Hey I am using the client. And the documentation for constraints specifically states:
```
value (string: "") - Specifies the value to compare the attribute against using the specified operation. This can be a literal value, another attribute, or any Nomad interpolated values.
```

**Comment by daledude** [comment]
Documenting still wrong or nomad still broken.
