### ISSUE TITLE
jobs with update blocks don't get fully re-scheduled

### ISSUE THREAD

**Issue by macb** [hashicorp/nomad#428]
If we have a job like:

```
job "repeater" {
  datacenters = ["tor1"]
  update {
    stagger = "1s"
    max_parallel = 5
  }

  group "repeater" {
    count = 50

    task "repeater" {
      driver = "docker"

      config {
        image = "macb/repeater"
      }

      resources {
        cpu = 20
        memory = 10
        network {
          dynamic_ports = ["9000"]
        }
      }
    }
  }
}
```

and 5 clients on which it is running. If we trigger an evaluation (run the job again, kill a node, or set a node) to drain, only `max_parallel` will ever be rescheduled. It's possible to trigger another `max_parallel` worth of allocations to be set by triggering another evaluation. This does not seem to be the desired behavior as it should be up to the scheduler to continually allocate up to `count` in increments of `max_parallel` every `stagger` duration.

**Comment by dadgar** [comment]
Closing as it is working properly now
