### ISSUE TITLE
Nomad allocating in-use ports conflicting with dynamic port range

### ISSUE THREAD

**Issue by urjitbhatia** [hashicorp/nomad#4285]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
```
Linux ip-10-1-6-191 4.4.0-1047-aws #56-Ubuntu SMP Sat Jan 6 19:39:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
### Issue
For high network utilization applications, nomad's dynamic port range collides with in-use ports. In my case, the port nomad is using to connect to consul agent falls within the dynamic nomad port range:

```
sudo lsof -i :24772
COMMAND  PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
nomad   6764 root   13u  IPv4 407612646      0t0  TCP localhost:24772->localhost:8500 (ESTABLISHED)
consul  7154 root   19u  IPv4 407604174      0t0  TCP localhost:8500->localhost:24772 (ESTABLISHED)
```
At the same time, my tasks are trying to assign this port because it's in Nomad's dynamic range causing the task to fail at startup.
```
 Error: listen EADDRINUSE :::24772 
```

### Reproduction steps
Run a large number of tasks with dynamic port allocations.

**Comment by shantanugadgil** [comment]
Hi,

Check the "Ports Used" section at


https://www.nomadproject.io/guides/cluster/requirements.html

HTH

**Comment by preetapan** [comment]
@urjitbhatia This is a known issue with how port assignments are handed out from the scheduler, and our mitigation is that apps that fail to start due to a port conflict should get [rescheduled](https://www.nomadproject.io/docs/job-specification/reschedule.html). Do your tasks have a reschedule policy ? By default all service jobs have rescheduling enabled.

**Comment by urjitbhatia** [comment]
@shantanugadgil Thanks, I overlooked that - fixed my ephemeral port problem colliding with non-nomad assigned ports.

However, my deployments are also failing because nomad keeps assigning ports it has assigned to other tasks.

@preetapan I am using the default reschedule policy. However, as the docs for rescheduling say:
```
The update stanza controls rolling updates and canary deployments. A task group's reschedule stanza does not take affect during a deployment. For example, if a new version of the job is rolled out and the deployment failed due to a failing allocation, Nomad will not reschedule it.
```

```
ubuntu@ip-10-1-0-254:~$ nomad  deployment status -verbose 5b5ea084
ID          = 5b5ea084-0393-ba6e-e117-4a72a00ee283
Job ID      = api-nomad
Job Version = 208
Status      = failed
Description = Failed due to unhealthy allocations

Deployed
Task Group              Desired  Placed  Healthy  Unhealthy
api-nomad-prod-hostnet  80       63      62       1
```

I am using the `docker` driver with `network_mode` = `host` with dynamic ports if that helps narrow this down.
The errors I see from my application is: ```{ Error: listen EADDRINUSE :::31390 }```

When I run `lsof`, it turns out that a previous running task is currently using that port (dynamically assigned by nomad).

Is there a config option I am missing here?

Task def snippet:
```
task "api_runner_hostnet" {
      env {
        MAIN_PORT = "${NOMAD_HOST_PORT_http}"
        HAPROXY_STATUS_PORT = "${NOMAD_HOST_PORT_haproxy_check_tcp}"
        HAPROXY_AGENT_PORT = "${NOMAD_HOST_PORT_haproxy_check_agent}"
      }

      driver = "docker"
      config {
        image = "<foo>"
        network_mode = "host"
        sysctl { net.core.somaxconn = "5000" }
        hostname = "nomadapi-${attr.unique.hostname}-${NOMAD_TASK_NAME}"
      resources {
        cpu    = 3600 # 3600 MHz
        memory = 2048 # 2GB
        network {
          port "http" {}
          port "haproxy_check_tcp" {}
          port "haproxy_check_agent" {}
        }
      }
}
```
Update stanza:
```
update {
    max_parallel = 6
    min_healthy_time = "15s"
    healthy_deadline = "2m"
    auto_revert = false
    canary = 0
  }
```

**Comment by dadgar** [comment]
@urjitbhatia Can you share the two allocations that have conflicting ports and share the lsof output? This is easily reproducible for you? Could you share an example job/config that does this?

**Comment by urjitbhatia** [comment]
For anyone who finds themselves in the same problem in the future:

Make sure your applications aren't using the same ephemeral ports that nomad tries to use. So far, nomad does not skip over used ports and your allocations will fail.

`sysctl -w net.ipv4.ip_local_port_range="35000 65535"`  (Currently, nomad uses port range [20000-32000](https://www.nomadproject.io/guides/cluster/requirements.html#ports-used))

**Comment by shishir-a412ed** [comment]
We are facing similar issues in our infrastructure, and I was wondering if [`this`](https://github.com/hashicorp/nomad/issues/4285#issuecomment-388577184) was ever considered for a feature request.

```
My understanding was that if a port in the nomad's dynamic port range (20000-30000) is busy, it will just try a different one. Is that something that is in the pipeline? Or a feature worth thinking about?
```

Right now, `nomad` tries to launch the allocation and the container fails with the below error:

![error](https://user-images.githubusercontent.com/4207652/106082701-02b7dc00-60d0-11eb-994d-a82a1c14a002.png)

This goes into a loop, and then the scheduler tries to reassign the allocation to a different node/port.

Would be nice, if `nomad` can detect that the dynamic port is **already in use** and assign a new **unused** one rather than failing and trying.
