### ISSUE TITLE
Optional consul service tags when registering nomad services

### ISSUE THREAD

**Issue by nickwales** [hashicorp/nomad#4297]
Vault lets us supply optional tags in the configuration as per the link below, I can't currently see that as an option in the Nomad docs. Would it be possible to add?

https://www.vaultproject.io/docs/configuration/storage/consul.html#service_tags

**Comment by angrycub** [comment]
Hey @nickwales.  Have you checked out the [tags attribute](https://www.nomadproject.io/docs/job-specification/service.html#tags) of the service stanza of the job specification?  Sounds like what you are looking for.

**Comment by nickwales** [comment]
Thanks for responding, this is actually for the `nomad` and `nomad-client` services rather than the tasks on the nomad agents. 

I just amended the title to hopefully make that distinction as discernible as possible!

**Comment by nickwales** [comment]
#5172
