### ISSUE TITLE
Feature Request: Support consul service meta in service stanza

### ISSUE THREAD

**Issue by 42wim** [hashicorp/nomad#4300]
Would be nice to have the service stanza support the consul service meta data  (See https://github.com/hashicorp/consul/pull/3881).

The use case is the same as in the original consul PR

**Comment by adragoset** [comment]
Any ETA on this? Pretty important when you start doing things like updating loadbalancers off of consul service records. Currently there is no way to pass messages from the deployment job to those types of services without querying the nomad api in addition to the consul api.

**Comment by chenjpu** [comment]
Is there any plan or progress?

**Comment by nickethier** [comment]
Thanks @jeromegn for knocking this out! :raised_hands:
