### ISSUE TITLE
POST /v1/jobs returning incorrect JobModifyIndex

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#4301]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Issue
We are creating a deployment process using the HTTP API and have found that the best parameter to link between a `POST` to `/v1/jobs` and `/v1/deployments` is the `JobModifyIndex`. However, when the task is going from a stopped/dead status to a running one, the `JobModifyIndex` returned from the `POST` to `/v1/jobs` does not match the `JobModifyIndex` in `/v1/deployments`, `/v1/jobs` is off by -1. It does, however, match the `Index` field returned by the `POST` to `/v1/jobs`.

However, when the job is running and deployed to, the `JobModifyIndex` matches perfectly.

Should these be off like this? What logic is used such that I can rely on the response of `POST` `/v1/jobs` to find the proper deployment?

Response from `POST` `/v1/jobs`:
```
{
  'EvalCreateIndex': 786499, 
  'EvalID': '7429debb-f4d9-91a3-ba56-64baed7c7da1', 
  'Index': 786499, 
  'JobModifyIndex': 786498, 
  'KnownLeader': False, 
  'LastContact': 0, 
  'Warnings': ''
}
```

Deployment found in `/v1/deployments` during the deployment:
```
{
  CreateIndex: 786500,
  ID: "8532e848-d68c-3d8d-0872-887da79b8640",
  JobCreateIndex: 235,
  JobID: "<REDACTED>",
  JobModifyIndex: 786499,
  JobVersion: 21,
  ModifyIndex: 786500,
  Namespace: "default",
  Status: "running",
  StatusDescription: "Deployment is running",
  TaskGroups: {
    enroute-completion: {
      AutoRevert: false,
      DesiredCanaries: 0,
      DesiredTotal: 1,
      HealthyAllocs: 0,
      PlacedAllocs: 1,
      PlacedCanaries: null,
      Promoted: false,
      UnhealthyAllocs: 0
    }
  }
},
```

Deployment found in `/v1/deployments` after the deployment:
```
{
  CreateIndex: 786500,
  ID: "8532e848-d68c-3d8d-0872-887da79b8640",
  JobCreateIndex: 235,
  JobID: "<REDACTED>",
  JobModifyIndex: 786499,
  JobVersion: 21,
  ModifyIndex: 786508,
  Namespace: "default",
  Status: "successful",
  StatusDescription: "Deployment completed successfully",
  TaskGroups: {
    enroute-completion: {
      AutoRevert: false,
      DesiredCanaries: 0,
      DesiredTotal: 1,
      HealthyAllocs: 1,
      PlacedAllocs: 1,
      PlacedCanaries: null,
      Promoted: false,
      UnhealthyAllocs: 0
    }
  }
}
```

### Reproduction steps
1. Stop a job
2. Deploy a job through `/v1/jobs`, take note of `JobModifyIndex`
3. Call `GET` `/v1/deployments`, search for the deployment that matches the `JobModifyIndex`, you won't find it.

**Comment by dadgar** [comment]
@djenriquez Hey so the field was being populated with the correct value but the naming is quite confusing.

So when you do a PUT on `/v1/jobs`, the response is `JobModifyIndex = job.JobModifyIndex`
The deployment is created and `JobModifyIndex = job.ModifyIndex`

I have added a new field to the deployment that is set as follows, `JobSpecModifyIndex = job.JobModifyIndex`. So you will be able to use that to correlate.
