### ISSUE TITLE
systemd unit file kills executors when nomad agent is stopped

### ISSUE THREAD

**Issue by ramSeraph** [hashicorp/nomad#4302]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
`uname -a`

Linux \<hostname\> 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`systemd --version`

systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Issue

 restarting nomad agent on the host restarts the jobs on the host when nomad is running under systemd

### Reproduction steps

`systemctl stop nomad` stops the running executors on the host

then if i do a `systemctl start nomad`,  the reattachment attempt kills the existing containers as the corresponding executors are dead

**Comment by ramSeraph** [comment]
adding `KillMode=process` to the systemd unit file below fixes the problem 

https://github.com/hashicorp/nomad/blob/master/dist/systemd/nomad.service

documentation reference: https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=

**Comment by preetapan** [comment]
@ramSeraph Could you submit a PR for changing that sample config file? - this default makes sense

**Comment by insanejudge** [comment]
I considered doing the same (we're running `Killmode=process`) but this should have been addressed by https://github.com/hashicorp/nomad/pull/3572 , which places executors in their own process group.

**Comment by ramSeraph** [comment]
@insanejudge thanks for the PR. I was offline and didn't see the response

**Comment by onlyjob** [comment]
FYI, https://github.com/hashicorp/nomad/pull/4305#issuecomment-412978568
