### ISSUE TITLE
Unstable health examination

### ISSUE THREAD

**Issue by judeo66** [hashicorp/nomad#4304]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details

Host Name:                 WIN-LEIV48G6F0A
OS Name:                   Microsoft Hyper-V Server 2016
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                03612-029-0000043-76066
Original Install Date:     14/05/2018, 10:35:34
System Boot Time:          16/05/2018, 08:23:51
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3600 Mhz
BIOS Version:              American Megatrends Inc. 090006 , 28/04/2016
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             pt-br;Portuguese (Brazil)
Input Locale:              pt-br;Portuguese (Brazil)
Time Zone:                 (UTC-03:00) Brasilia
Total Physical Memory:     4.096 MB
Available Physical Memory: 3.154 MB
Virtual Memory: Max Size:  5.504 MB
Virtual Memory: Available: 4.514 MB
Virtual Memory: In Use:    990 MB

### Issue

When I run my job all my containers go up but Health Check fails even if I can access all the containers and have the expected result.
Could you check my file and the writing form of my jobfile and let me know if something is wrong?

The container used is a simple Whoami for Windows Containers, when port 8080 of the container is accessed something like "I'm running ebbb1a1d043a running on windows / amd64" should be displayed displaying the id of the container running Whoami.

-None of the machines suffers from a lack of resources

### Reproduction steps

1 - Start the nomad and consul as follows:

Command used to initialize Nomad

./nomad.exe agent -server -bind 140.0.220.156 -consul address = http: //140.0.220.156:8500 -data-dir = c: / nomadteste4 -log-level debug -bootstrap-expect 1

Command used to initialize Consul

. \ consul.exe agent -server -ui -data-dir c: / consul3 -bind 140.0.220.156 -advertise 140.0.220.156 -client 140.0.220.156 -bootstrap-expect 1 -enable-script-checks

2 - Execute the Job shown in the below in the section job file

3 - Check the Health Check in the Consul sometimes, if the behavior is the same as in my environment, the health check will alternate between Health and Unhealth and sometimes the service will no longer be displayed in the Consul

### Job file (if appropriate)

job "GitHubExample" {
 
  datacenters = ["dc1"]

  type = "service"

  update {
   
    max_parallel = 1

   
    min_healthy_time = "10s"

    healthy_deadline = "3m"

    auto_revert = false

    canary = 0
  }

  migrate {
   
    max_parallel = 1

   
    health_check = "checks"

    min_healthy_time = "30s"

    
    healthy_deadline = "5m"
  }

  
  group "WebServices" {
    
    count = 20

    restart {
    
      attempts = 2
      interval = "30m"

     
      delay = "15s"

    
      mode = "fail"
    }

    
    ephemeral_disk {
      size = 300
    }

   
    task "tomcat" {
      driver = "docker"
      config {
        image = "stefanscherer/whoami"
        port_map {
          http = 8080
        }
      }

     
      resources {
        cpu    = 200 # 500 MHz
        memory = 256 # 256MB
        network {
          mbits = 10
          port "http" {}
        }
      }

    
      service {
        name = "Whoami-Nomad"
        tags = ["global", "webservice","urlprefix-/nomadteste"]
        port = "http"
        check {
          name     = "alive"
          type     = "http"
		  method   = "GET"
		  path	   =  "/"
          interval = "10s"
          timeout  = "4s"
        }
      }

    }
  }
}

Image displayed after job deploy:

![image](https://user-images.githubusercontent.com/15389215/40133273-a4f04108-5915-11e8-9c3e-c33ee92aee0d.png)

States that the service keeps alternating in the consul:

![image](https://user-images.githubusercontent.com/15389215/40133357-dc58847a-5915-11e8-8672-b7cd9423490c.png)

![image](https://user-images.githubusercontent.com/15389215/40133379-ecb04aec-5915-11e8-806e-2764e442795c.png)

**Comment by viniciusxyz** [comment]
Same here!

**Comment by viniciusxyz** [comment]
Nomad console out

 TCP connection from=140.0.220.156:56867
    2018/05/16 14:56:32.864780 [DEBUG] http: Request GET /v1/job/GitHubExample?index=105 (5m9.3370871s)
    2018/05/16 14:56:33.235990 [DEBUG] http: Request GET /v1/allocation/f6196d2a-9cde-05f2-aabe-6c48c982eb51?index=97 (5m18.0595379s)
    2018/05/16 14:56:33.707591 [DEBUG] http: Request GET /v1/job/GitHubExample/allocations?index=105 (5m10.1757004s)
    2018/05/16 14:56:41.673415 [DEBUG] http: Request GET /v1/agent/health?type=server (0s)
    2018/05/16 14:56:42 [DEBUG] memberlist: TCP connection from=140.0.220.156:56886
    2018/05/16 14:56:51.676192 [DEBUG] http: Request GET /v1/agent/health?type=server (0s)
    2018/05/16 14:56:52 [DEBUG] memberlist: TCP connection from=140.0.220.156:56911
    2018/05/16 14:57:01.678395 [DEBUG] http: Request GET /

**Comment by viniciusxyz** [comment]
Hello

This problem is probably occurring because you are pointing the Nomad-Client directly to the Consul-master instead of pointing to your consult-client and they are pointing to the master.

Try to follow the documentation always keeping the structure of not pointing anything to the Consul Server other than your Consul Clients or your followers servers

**Comment by judeo66** [comment]
This is the problem, thank you.
