### ISSUE TITLE
[Feature request] Display resource utilisation charts in web-ui.

### ISSUE THREAD

**Issue by rkettelerij** [hashicorp/nomad#4332]
Currently the `nomad node-status` command prints information about resource utilisation. E.g:

```
Allocated Resources
CPU            Memory           Disk            IOPS
4000/4798 MHz  3.4 GiB/3.9 GiB  10 GiB/14 GiB  0/0

Allocation Resource Utilization
CPU          Memory
23/4798 MHz  571 MiB/3.9 GiB

Host Resource Utilization
CPU          Memory           Disk
95/4798 MHz  1.1 GiB/3.9 GiB  3.7 GiB/19 GiB
```

It would be great to also show this information with some nice charts in the web ui.

**Comment by rkettelerij** [comment]
Oh doh never noticed the bars besides the allocations. 

<img width="293" alt="screen shot 2018-05-25 at 00 01 23" src="https://user-images.githubusercontent.com/291572/40515897-f16a49f8-5fae-11e8-944c-a9048c65e996.png">

So this is already in Nomad. Great! Closing this one.

**Comment by MorphBonehunter** [comment]
@rkettelerij / @dadgar  would you mind to reopen this issue as your original request is still valid (or did i miss something).
The Ressource usage is only per allocation, but on the client page the isn't anything that shows the metrics which are shown ob the cli.
It would be nice if the allocation summaries ("Allocated Resources" and "Allocation Resource Utilization") and the host summary "Host Resource Utilization" could be shown in the UI.

**Comment by rkettelerij** [comment]
@MorphBonehunter I belief something like that is already in the works: https://github.com/hashicorp/nomad/pull/4704

**Comment by MorphBonehunter** [comment]
Ok, thanks for that, i will keep an eye on the whole #4727
