### ISSUE TITLE
Suppress Consul Sync Messages

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#4345]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
Ubuntu

### Issue

I have many tens of thousands of log messages like this:

```2018/05/28 23:27:20.557180 [ERR] consul.sync: still unable to update services in Consul after 11210 failures; latest error: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused```

We don't use Consul. I don't want Nomad to create these messages in my logs.

### Reproduction steps
Run nomad on a large cluster without Consul. Look at your logs.

### Nomad Server logs (if appropriate)
```2018/05/28 21:02:10.706512 [ERR] consul.sync: still unable to update services in Consul after 10810 failures; latest error: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused```
Every few seconds.

### Nomad Client logs (if appropriate)
```2018/05/28 21:02:10.706512 [ERR] consul.sync: still unable to update services in Consul after 10810 failures; latest error: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused```
Every few seconds.

With hundreds of clients, this becomes a constant stream of garbage I don't want about a service I don't use.

**Comment by jippi** [comment]
do this help?

```
consul {
  auto_advertise      = false
  server_auto_join    = false
  client_auto_join    = false
}
```

**Comment by dadgar** [comment]
@Miserlou @jippi's suggestion will unblock you if you continue to use 0.7.1 but this does not occur on 0.8.3
