### ISSUE TITLE
Eligibility not restored after `node-drain -disable`

### ISSUE THREAD

**Issue by glimberg** [hashicorp/nomad#4356]
Related to https://github.com/hashicorp/nomad/issues/4347

Server/client nodes were running Nomad v0.8.1 (Linux)

Node drain enable/disable calls were executed via Nomad v0.7.x (Windows).

According to the docs, node eligibility should be disabled when `node-drain -enable` is set on a node, and eligibility should be enabled when `node-drain -disable` is set on a node.

In this case, eligibility was not enabled when `node-drain -disable` was called on a node, leaving it out of the pool of available client nodes.

**Comment by preetapan** [comment]
I was unable to reproduce in Nomad 0.8.1

```
$ nomad node drain -enable 7d5
Are you sure you want to enable drain mode for node "7d5fc08a-af80-be93-50c1-e077a8c36cb7"? [y/N] y
2018-05-30T20:38:31Z: Ctrl-C to stop monitoring: will not cancel the node drain
2018-05-30T20:38:31Z: Node "7d5fc08a-af80-be93-50c1-e077a8c36cb7" drain strategy set
2018-05-30T20:38:31Z: All allocations on node "7d5fc08a-af80-be93-50c1-e077a8c36cb7" have stopped.
2018-05-30T20:38:31Z: Node "7d5fc08a-af80-be93-50c1-e077a8c36cb7" drain complete
$ nomad node status   
ID        DC   Name   Class   Drain  Eligibility  Status
7d5fc08a  dc1  linux  <none>  false  ineligible   ready
$ nomad node drain -disable 7d5
Are you sure you want to disable drain mode for node "7d5fc08a-af80-be93-50c1-e077a8c36cb7"? [y/N] y
Node "7d5fc08a-af80-be93-50c1-e077a8c36cb7" drain strategy unset
$ nomad node status   
ID        DC   Name   Class   Drain  Eligibility  Status
7d5fc08a  dc1  linux  <none>  false  eligible     ready
```

However, our master branch did have exactly this bug and PR #4352 fixed it. @glimberg can you re-confirm your nomad version and steps to reproduce?

**Comment by glimberg** [comment]
@preetapan This occurred when calling node drain from an older version of the client that knows nothing about eligibility (0.7.x).  The servers were running 0.8.1, however.

**Comment by preetapan** [comment]
@glimberg now I see that you put that in the original description, missed that before. Thanks for clarifying
