### ISSUE TITLE
Very Slow to start a batch job in some pc.

### ISSUE THREAD

**Issue by molin0000** [hashicorp/nomad#4361]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.8.3 and Nomad v0.7.0 both have this mistake.

### Operating system and Environment details
Windows 7 sp1 64bit 

### Issue
When I run a batch job, it cost very long time at the starting state.
After 1~5minute in starting state the job started to turn a running state.
In some pc, it's work good. But some pc it works error.

### Reproduction steps
nomad agent -dev
nomad run xxx.job

### Nomad Server logs (if appropriate)
[log_slow.txt](https://github.com/hashicorp/nomad/files/2062983/log_slow.txt)

**Comment by preetapan** [comment]
This seems related to issue #4362 and seems related to system encoding since the logs say "invalid query". I am going to close this one out and leave  #4362 open

**Comment by molin0000** [comment]
Loaded configuration from server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                Client: true
             Log Level: DEBUG
                Region: global (DC: dc1)
                Server: true
               Version: 0.7.0

==> Nomad agent started! Log data will stream in below:

    2018/06/01 18:19:23 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.21.21:4647 Address:192.168.21.21:4647}]
    2018/06/01 18:19:23 [INFO] raft: Node at 192.168.21.21:4647 [Follower] entering Follower state (Leader: "")
    2018/06/01 18:19:23 [INFO] serf: EventMemberJoin: Raco1-1.global 192.168.21.21
    2018/06/01 18:19:23.739400 [INFO] nomad: starting 8 scheduling worker(s) for [service batch system _core]
    2018/06/01 18:19:23.739400 [INFO] nomad: adding server Raco1-1.global (Addr: 192.168.21.21:4647) (DC: dc1)
    2018/06/01 18:19:23.740400 [DEBUG] server.nomad: lost contact with Nomad quorum, falling back to Consul for server list
    2018/06/01 18:19:23.745400 [INFO] client: using state directory D:\tools\nomad_server\server\client
    2018/06/01 18:19:23.748400 [INFO] client: using alloc directory D:\tools\nomad_server\server\alloc
    2018/06/01 18:19:23.917400 [DEBUG] client: built-in fingerprints: [arch consul cpu host memory network nomad signal storage vault env_aws env_gce]
    2018/06/01 18:19:24.741400 [ERR] consul: error looking up Nomad servers: server.nomad: unable to query Consul datacenters: Get http://127.0.0.1:8500/v1/catalog/datacenters: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
    2018/06/01 18:19:24.742400 [WARN] consul.sync: failed to update services in Consul: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
    2018/06/01 18:19:24 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/06/01 18:19:24 [INFO] raft: Node at 192.168.21.21:4647 [Candidate] entering Candidate state in term 2
    2018/06/01 18:19:24.917400 [DEBUG] client: fingerprinting consul every 15s
    2018/06/01 18:19:24 [DEBUG] raft: Votes needed: 1
    2018/06/01 18:19:24 [DEBUG] raft: Vote granted from 192.168.21.21:4647 in term 2. Tally: 1
    2018/06/01 18:19:24 [INFO] raft: Election won. Tally: 1
    2018/06/01 18:19:24 [INFO] raft: Node at 192.168.21.21:4647 [Leader] entering Leader state
    2018/06/01 18:19:24.917400 [INFO] nomad: cluster leadership acquired
    2018/06/01 18:19:24.924400 [DEBUG] leader: reconciling job summaries at index: 0
    2018/06/01 18:19:24.968400 [DEBUG] fingerprint.cpu: frequency: 2001 MHz
    2018/06/01 18:19:24.968400 [DEBUG] fingerprint.cpu: core count: 8
    2018/06/01 18:19:26.180400 [WARN] fingerprint.network: Error calling powershell.exe (Get-NetAdapter -IncludeHidden | Where name -eq '本地连接' | Select -ExpandProperty LinkSpeed): exit status 1
    2018/06/01 18:19:26.180400 [DEBUG] fingerprint.network: link speed could not be detected and no speed specified by user. Defaulting to 1000
    2018/06/01 18:19:26.181400 [DEBUG] fingerprint.network: Detected interface 本地连接 with IP: 192.168.21.21
    2018/06/01 18:19:26.181400 [DEBUG] client: fingerprinting vault every 15s
    2018/06/01 18:19:28.181400 [DEBUG] fingerprint.env_gce: Could not read value for attribute "machine-type"
    2018/06/01 18:19:28.181400 [DEBUG] fingerprint.env_gce: Error querying GCE Metadata URL, skipping
    2018/06/01 18:19:30.181400 [DEBUG] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
    2018/06/01 18:19:30.181400 [DEBUG] client: applied fingerprints [arch cpu host memory network nomad signal storage]
    2018/06/01 18:19:30.183400 [DEBUG] driver.docker: using client connection initialized from environment
    2018/06/01 18:19:30.185400 [DEBUG] driver.docker: could not connect to docker daemon at npipe:////./pipe/docker_engine: Get http://unix.sock/version: open //./pipe/docker_engine: The system cannot find the file specified.
    2018/06/01 18:19:30.185400 [WARN] driver.raw_exec: raw exec is enabled. Only enable if needed
    2018/06/01 18:19:30.185400 [DEBUG] client: fingerprinting docker every 15s
    2018/06/01 18:19:30.185400 [DEBUG] client: fingerprinting exec every 15s
    2018/06/01 18:19:30.416400 [DEBUG] client: available drivers [raw_exec java]
    2018/06/01 18:19:30.417400 [INFO] client: Node ID "f28cc748-bc99-1663-e67f-d7c28092d6b2"
    2018/06/01 18:19:30.419400 [DEBUG] client: updated allocations at index 1 (total 0) (pulled 0) (filtered 0)
    2018/06/01 18:19:30.419400 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)
    2018/06/01 18:19:30.429400 [INFO] client: node registration complete
    2018/06/01 18:19:30.429400 [DEBUG] client: periodically checking for node changes at duration 5s
    2018/06/01 18:19:30.978400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:19:30.978400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:19:31.072400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:19:32.790400 [DEBUG] http: Request /v1/status/leader (0s)
    2018/06/01 18:19:32.816400 [DEBUG] http: Request /v1/nodes (0s)
    2018/06/01 18:19:32.819400 [DEBUG] http: Request /v1/agent/members (2ms)
    2018/06/01 18:19:32.878400 [DEBUG] http: Request /v1/node/f28cc748-bc99-1663-e67f-d7c28092d6b2/allocations (0s)
    2018/06/01 18:19:32.884400 [DEBUG] http: Request /v1/node/f28cc748-bc99-1663-e67f-d7c28092d6b2 (1ms)
    2018/06/01 18:19:33.909400 [DEBUG] http: Request /v1/nodes (1ms)
    2018/06/01 18:19:33.910400 [DEBUG] http: Request /v1/agent/members (0s)
    2018/06/01 18:19:35.046400 [DEBUG] http: Request /v1/nodes (1ms)
    2018/06/01 18:19:35.046400 [DEBUG] http: Request /v1/agent/members (0s)
    2018/06/01 18:19:35.081400 [DEBUG] http: Request /v1/node/f28cc748-bc99-1663-e67f-d7c28092d6b2 (1ms)
    2018/06/01 18:19:35.094400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:19:36.964400 [DEBUG] client: state updated to ready
    2018/06/01 18:19:37.461400 [DEBUG] http: Request /v1/nodes (0s)
    2018/06/01 18:19:37.462400 [DEBUG] http: Request /v1/agent/members (1ms)
    2018/06/01 18:19:38.110400 [DEBUG] http: Request /v1/nodes (1ms)
    2018/06/01 18:19:38.110400 [DEBUG] http: Request /v1/agent/members (0s)
    2018/06/01 18:19:38.139400 [DEBUG] http: Request /v1/node/f28cc748-bc99-1663-e67f-d7c28092d6b2 (1ms)
    2018/06/01 18:19:40.618400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:19:50.382400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:19:53.669400 [DEBUG] http: Request /v1/jobs (14ms)
    2018/06/01 18:19:53.669400 [DEBUG] worker: dequeued evaluation ce876ec6-e6e1-c253-d8b2-06d4c5790d26
    2018/06/01 18:19:53.670400 [DEBUG] http: Request /v1/evaluation/ce876ec6-e6e1-c253-d8b2-06d4c5790d26 (0s)
    2018/06/01 18:19:53.671400 [DEBUG] sched: <Eval "ce876ec6-e6e1-c253-d8b2-06d4c5790d26" JobID: "42484-201806011819SAR_PRO" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "GROUPNAME": (place 1) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)
    2018/06/01 18:19:53.672400 [DEBUG] http: Request /v1/evaluation/ce876ec6-e6e1-c253-d8b2-06d4c5790d26/allocations (0s)
    2018/06/01 18:19:53.677400 [DEBUG] worker: submitted plan for evaluation ce876ec6-e6e1-c253-d8b2-06d4c5790d26
    2018/06/01 18:19:53.677400 [DEBUG] sched: <Eval "ce876ec6-e6e1-c253-d8b2-06d4c5790d26" JobID: "42484-201806011819SAR_PRO" Namespace: "default">: setting status to complete
    2018/06/01 18:19:53.677400 [DEBUG] client: updated allocations at index 9 (total 1) (pulled 1) (filtered 0)
    2018/06/01 18:19:53.677400 [DEBUG] client: allocs: (added 1) (removed 0) (updated 0) (ignore 0)
    2018/06/01 18:19:53.680400 [DEBUG] worker: updated evaluation <Eval "ce876ec6-e6e1-c253-d8b2-06d4c5790d26" JobID: "42484-201806011819SAR_PRO" Namespace: "default">
    2018/06/01 18:19:53.680400 [DEBUG] worker: ack for evaluation ce876ec6-e6e1-c253-d8b2-06d4c5790d26
    2018/06/01 18:19:54.673400 [DEBUG] http: Request /v1/evaluation/ce876ec6-e6e1-c253-d8b2-06d4c5790d26 (0s)
    2018/06/01 18:19:54.674400 [DEBUG] http: Request /v1/evaluation/ce876ec6-e6e1-c253-d8b2-06d4c5790d26/allocations (0s)
    2018/06/01 18:19:57.605400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:19:57.708400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:19:57.708400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:19:58.152400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:19:58.762400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:19:58.762400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:19:58.832400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:19:58.944400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:19:58.944400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:19:59.539400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:19:59.540400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:19:59.579400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:19:59.644400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:19:59.644400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:00.177400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:00.177400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:00.220400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:00.299400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:00.299400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:00.701400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:00.701400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:00.738400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:00.804400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:00.805400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:01.288400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:01.288400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:01.326400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:01.392400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:01.393400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:01.867400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:01.868400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:01.905400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:01.971400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:01.972400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:02.429400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:02.429400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:02.470400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:02.546400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:02.547400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:02.697400 [DEBUG] client: starting task runners for alloc '330da8ad-c3f6-84e2-ea24-3f9fb5ebf1cb'
    2018/06/01 18:20:02.698400 [DEBUG] client: starting task context for 'TASKNAME' (alloc '330da8ad-c3f6-84e2-ea24-3f9fb5ebf1cb')
    2018/06/01 18:20:02.871400 [DEBUG] client: updated allocations at index 11 (total 1) (pulled 0) (filtered 1)
    2018/06/01 18:20:02.871400 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 1)
    2018/06/01 18:20:03.047400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:03.048400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:03.085400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:03.152400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:03.152400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:03.630400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:03.630400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:03.669400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:03.732400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:03.732400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:04.181400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:04.181400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:04.218400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:04.285400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:04.286400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:04.755400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:04.756400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:04.801400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:04.868400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:04.868400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:05.399400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:05.399400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:05.437400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:05.504400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:05.505400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:05.903400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:05.903400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:05.940400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:06.003400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:06.003400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:06.590400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:06.591400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:06.628400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:06.695400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:06.695400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:07.138400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:07.138400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:07.181400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:07.253400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:07.253400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:07.807400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:07.807400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:07.845400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:07.912400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:07.912400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:08.431400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:08.431400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:08.470400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:08.535400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:08.537400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:08.993400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:08.993400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:09.033400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:09.096400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:09.097400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:09.621400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:20:09.633400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:09.633400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:09.670400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:09.739400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:09.739400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:10.207400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:10.208400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:10.246400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:10.309400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:10.310400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:10.801400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:10.801400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:10.839400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:10.904400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:10.905400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:11.371400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:11.371400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:11.412400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:11.476400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:11.476400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:11.956400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:11.956400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:11.998400 [DEBUG] driver.raw_exec: started process with pid: 3980
    2018/06/01 18:20:11.999400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:12.070400 [DEBUG] client: updated allocations at index 12 (total 1) (pulled 0) (filtered 1)
    2018/06/01 18:20:12.070400 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 1)
    2018/06/01 18:20:12.072400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:12.072400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:13.018400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:13.018400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:13.058400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:13.129400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:13.130400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:13.540400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:13.540400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:13.582400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:13.684400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:13.687400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:14.169400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:14.169400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:14.212400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:14.289400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:14.290400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:14.706400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:14.706400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:14.775400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:14.853400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:14.855400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:15.288400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:15.288400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:15.338400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:15.412400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:15.415400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:15.886400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:15.886400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:15.942400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:16.056400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:16.068400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (12ms)
    2018/06/01 18:20:16.367400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:16.368400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:16.406400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:16.471400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:16.472400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:16.999400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:16.999400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:17.037400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:17.104400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:17.105400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:17.531400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:17.531400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:17.571400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:17.644400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:17.644400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:18.122400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:18.122400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:18.165400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:18.231400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:18.231400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:18.603400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:18.604400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:18.642400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:18.706400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:18.706400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:19.199400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:19.199400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:19.236400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:19.308400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:19.308400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:19.741400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:19.742400 [DEBUG] http: Request /v1/namespaces (1ms)
    2018/06/01 18:20:19.779400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:19.843400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (0s)
    2018/06/01 18:20:19.843400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:20.308400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:20.308400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:20.345400 [DEBUG] http: Request /v1/jobs (0s)
    2018/06/01 18:20:20.416400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:20.416400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (0s)
    2018/06/01 18:20:20.822400 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/06/01 18:20:20.822400 [DEBUG] http: Request /v1/namespaces (0s)
    2018/06/01 18:20:20.862400 [DEBUG] http: Request /v1/jobs (1ms)
    2018/06/01 18:20:20.951400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO/summary (1ms)
    2018/06/01 18:20:20.951400 [DEBUG] http: Request /v1/job/42484-201806011819SAR_PRO (1ms)
    2018/06/01 18:20:24.895400 [WARN] client: error fetching host resource usage stats: 发生意外。 (Invalid query )
    2018/06/01 18:20:30.400400 [ERR] client: error garbage collecting allocation: 发生意外。 (Invalid query )
    2018/06/01 18:20:35.543400 [ERR] driver.raw_exec: error killing user process: OpenProcess: The parameter is incorrect.
    2018/06/01 18:20:35.543400 [ERR] driver.raw_exec: error killing executor: connection is shut down
