### ISSUE TITLE
unable to run mysql with args on windows

### ISSUE THREAD

**Issue by GavinPalmer1984** [hashicorp/nomad#4363]
### Nomad version
`0.8.3`

### Operating system and Environment details
windows server 2008 on AWS with mysql 5.6 installed and available on the path env variable

### Issue
I created a question on stackoverflow and asked for help on gitter.  It was recommended that I log an issue. https://stackoverflow.com/questions/50644172/how-should-i-run-a-mysql-command-with-nomad-and-arguments

### Reproduction steps
see stackoverflow or:
- use nomad dev server in one cmd console
- in another cmd console:
    - nomad job start path-to-nomad-job-files/gavin-setup-job.nomad

### Job file (if appropriate)
```
job "gavin-setup" {

    datacenters = ["dc1"]

    group "gavin-setup-group" {

        task "setup" {
            driver = "exec"
            config = {
                command = "mysql"
                args = [
                    "-hlocalhost",
                    "-ugavin",
                    "-pgavin_secret",
                    "gavin_database",
                    "<",
                    "C:\\gavin\\config\\create.sql"
                ]
            }
        }

    }

}
```

**Comment by dadgar** [comment]
@GavinPalmer1984 Hey Gavin,

So the best place for questions like this is the mailing list but we will definitely help you out! So since you are on Windows you will need to change the driver to `raw_exec` as windows doesn't support exec.

When you run your job you probably see a placement failure saying missing drivers, and that is because your windows machines do not have the exec driver.

Once you get an allocation running you can look at logs using `nomad logs <alloc-id>` and `nomad logs -stderr <alloc-id>`.

Feel free to ask more questions here as you continue to work on this!

**Comment by GavinPalmer1984** [comment]
@dadgar - Thank you! - that `nomad logs -stderr <alloc-id>` comment helped me a lot.  I was able to use the "exec" driver.  So maybe my version has that capability?  I tested a job with one task like this:

```
job "gavin-setup" {

    datacenters = ["dc1"]

    group "gavin-setup-group" {

        task "create_db" {
            driver = "exec"
            config = {
                command = "C:/Program Files (x86)/MySQL/MySQL Server 5.6/bin/mysql.exe"
                args = [
                    "-uroot",
                    "-pgavin_secret",
                    "-e",
                    "create database if not exists gavin_db;"
                ]
            }
        }

    }

}

```

It appears that tasks are NOT run synchronously and I am curious how I could accomplish something like this:

```
job "gavin-setup" {

    datacenters = ["dc1"]

    group "gavin-setup-group" {

        task "step_1_drop_db" {
            driver = "exec"
            config = {
                command = "C:/Program Files (x86)/MySQL/MySQL Server 5.6/bin/mysql.exe"
                args = [
                    "-uroot",
                    "-pgavin_secret",
                    "-e",
                    "drop database gavin_db;"
                ]
            }
        }
        task "step_2_create_db" {
            driver = "exec"
            config = {
                command = "C:/Program Files (x86)/MySQL/MySQL Server 5.6/bin/mysql.exe"
                args = [
                    "-uroot",
                    "-pgavin_secret",
                    "-e",
                    "create database gavin_db;"
                ]
            }
        }
        task "step_3_init_db" {
            driver = "exec"
            config = {
                command = "C:/Program Files (x86)/MySQL/MySQL Server 5.6/bin/mysql.exe"
                args = [
                    "-uroot",
                    "-pgavin_secret",
                    "gavin_db",
                    "<",
                    "c:/gavin/init_db.sql"
                ]
            }
        }

    }

}

```

**Comment by GavinPalmer1984** [comment]
With my example above - I can imagine a few ways to accomplish the goal without requiring nomad to do synchronous behavior or use a `depends_on` kind of feature.  But I still want to know if that functionality is available and how to use  it.  Thanks!
