### ISSUE TITLE
Incompatiby of basic node drain command for v0.8.3 and v0.7.1 

### ISSUE THREAD

**Issue by constiDisch** [hashicorp/nomad#4364]
### Nomad version
Nomad version server: `0.7.1`
Nomad version client in docker :  `0.7.1`
Nomad version on client system for starting jobs: v0.8.3

### Operating system and Environment details
ubuntu16:04
### Issue
Incompatibility for toggling the drain mode in very basic setting: It seems to be not possible to enter drain-mode using version v0.8.3, when server/client runs with v0.7.1. Of course a simple solution is down/upgrading one of the versions.
### Reproduction steps
nomad_v07 node-drain -disable -self
works fine
nomad_v08 node drain -disable -self
Output: Error updating drain specification: Unexpected response code: 400 (missing enable value)

**Comment by shantanugadgil** [comment]
I don't think having a higher version of the client os supported.
I always upgrade my servers first, and try to keep all agents on the exact same version.

If you have a higher server, there has been in a recent fix to handle such a situation (dont have the issue id handy)

HTH

**Comment by preetapan** [comment]
@constiDisch we recommend upgrading servers first and then upgrading clients. Usually servers have backwards compatibility built in when the requestor is a older version client. See our upgrade guide for more information https://www.nomadproject.io/docs/upgrade/index.html#upgrade-process. We don't promise backwards compatibility in the other direction.
