### ISSUE TITLE
How to stop/purge one task of a job

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#4367]
- I use nomad create mysql cluster
- a job with distinct_host
- one master , one rdonly, one replica, and i want to delete a replica 
- count =2 decrease to count=1 ,how can i know  which task will be destroy

Can I control which task can be destroy?

**Comment by jippi** [comment]
you cannot control it, but nomad usually kill the allocation with highest alloc index

**Comment by linuxgood1230** [comment]
If i have a task/alloc failed, I set count=2 to count=1, It will destroy failed alloc first.

**Comment by linuxgood1230** [comment]
thanks 
this maybe best. I will design by this
best way to do this is to have a group for each alloc, then you can scale up/down

**Comment by dadgar** [comment]
@linuxgood1230 That is one option. That will work for quite a few allocs but you do not want hundreds of groups in a job! In a future release, you will be able to kill/restart individual allocations.
