### ISSUE TITLE
[question] Raw_exec driver restricting resources 

### ISSUE THREAD

**Issue by cernerpradeep** [hashicorp/nomad#4371]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
### Operating system and Environment details
RHEL 6.8
### Issue
In the nomad documentation it is mentioned that https://www.nomadproject.io/docs/drivers/raw_exec.html resource allocation is not restricted. But when we actually used this driver for deploying java jars the resources are restricted. We expected it run like as if it was started on command line instead through nomad.
### Job file (if appropriate)
job "RawExecDistMEF" {

   datacenters = ["dc1"]
   type = "service"

   update {
     stagger = "10s"
     max_parallel = 1
   }

    group "KafkaConsumer" {
       count = 1
       #user = "root"

       restart {
         attempts = 1
         interval = "5m"
         delay = "25s"
         mode = "delay"
       }

       task "kafka" {
          driver = "raw_exec"

            config {
               command = "/usr/bin/java"
               args    = ["-jar", "/opt/opennms/vertxJars/KafkaConsumer.jar"]
           }
     }

   }

group "Syslogd" {
      count = 1
      #user = "root"

      restart {
        attempts = 1
        interval = "5m"
        delay = "25s"
        mode = "delay"
      }

      task "SyslogVerticle" {
         driver = "raw_exec"

           config {
              command = "/usr/bin/java"
              args    = ["-jar", "/opt/opennms/vertxJars/SyslogLoader.jar","true"]
          }
    }

  }

group "KafkaProducer" {
     count = 1
     #user = "root"

     restart {
       attempts = 1
       interval = "5m"
       delay = "25s"
       mode = "delay"
     }

     task "kafkaProducer" {
        driver = "raw_exec"

          config {
             command = "/usr/bin/java"
             args    = ["-jar", "/opt/opennms/vertxJars/KafkaProducer.jar", "true"]
         }
   }

  }
}

<img width="930" alt="screen shot 2018-06-05 at 2 20 15 pm" src="https://user-images.githubusercontent.com/14312836/40965841-7ae597ac-68cc-11e8-8fab-baa13812d455.png">

**Comment by chelseakomlo** [comment]
Thanks for reporting this issue. Can you include logs from the client and [job status](https://www.nomadproject.io/docs/commands/job/status.html) that seem to indicate that resources are being restricted?

**Comment by dadgar** [comment]
Hey I am going to close this until it can be demonstrated resources are being restricted. There are no provisions for this to occur.

**Comment by cernerpradeep** [comment]
@chelseakomlo 
[root@monetfbkf02 ~/nomad]# ./nomad alloc-status 46a82636
ID                  = 46a82636
Eval ID             = d037a8ad
Name                = RawExecDistMEF.Syslogd[0]
Node ID             = dabf6fcd
Job ID              = RawExecDistMEF
Job Version         = 2
Client Status       = running
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 20h38m ago
Modified            = 20h37m ago
Deployment ID       = b198afe9
Deployment Health   = healthy

Task "SyslogVerticle" is "running"
Task Resources
CPU         Memory           Disk     IOPS  Addresses
24/100 MHz  993 MiB/300 MiB  300 MiB  0

Task Events:
Started At     = 06/05/18 09:23:23 UTC
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                   Type        Description
06/05/18 04:23:23 CDT  Started     Task started by client
06/05/18 04:23:23 CDT  Task Setup  Building Task Directory
06/05/18 04:23:23 CDT  Received    Task received by client


Here is the info. You can see that cpu is 24/100MHZ. Doesn't it mean that its 24 out of 100MHZ, so 100MHZ is the reserved limit.

**Comment by dadgar** [comment]
100MHz is the reserved amount but since you are using raw exec it can exceed that value since nothing is limiting it to 100.

**Comment by shantanugadgil** [comment]
Hi @dadgar,
Would it be possible to add the information to the output of 'alloc status', about the limits being hard or soft.

It becomes mental overhead for the operator/user to cross check with the job file.

For my use case I have "multiple docker containers on a single machine".

Regards,
Shantanu

**Comment by cernerpradeep** [comment]
@dadgar Yes you are correct.But when it reached the limit and resources didn't exceed.

**Comment by cernerpradeep** [comment]
@dadgar @chelseakomlo 
Thanks so much for your time. Actually I was misled by the limit that was displayed. I increased load rapidly and it was able to use more resources that reserved.
