### ISSUE TITLE
[feature] "parameterized" driver 

### ISSUE THREAD

**Issue by sirkjohannsen** [hashicorp/nomad#4391]
Hi nomad devs :) 

We have the use-case (and I think others might as well) to trigger a parameterized job periodically with a different payload. 
The benefits: 
* the parameterized job has all the config defined in its job definition 
* the periodic job can stay slim and just passes a different payload to the existing parameterized job 

We currently solve it by doing a curl in a periodic job to the local nomad api that triggers the parameterized job. 
Task definition (in json):

```
....
        "Tasks": [
          {
            "Name": "complete",
            "Driver": "raw_exec",
            "Config": {
              "command": "/usr/bin/curl",
              "args": [
                "-s",
                "-X",
                "POST",
                "http://${attr.unique.network.ip-address}:4646/v1/job/myparameterizedjob/dispatch",
                "-d",
                "{\"Meta\": {\"SOME_ARGUMENT\": \"somevalue\"}}"
              ]
            },
...
```
which is of course not ideal but works ;) 
Would it be possible to implement this functionality into nomad by a "parameterized" driver maybe ? 
Where one could pass the jobname, payload and/or metadata to trigger an existing job ?

**Comment by dadgar** [comment]
Hey @sirkjohannsen,

It is an interesting idea but not something we would create. For now you can use the API as you are doing. In Nomad 0.9 we will be working on custom drivers, and you could implement this yourself if you'd like.
