### ISSUE TITLE
[feature request] Implement TableSorter like functionality for Nomad GUI

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#4401]
### Nomad version
Nomad v0.8.4-rc1 (c17e0fc9dc5fd288935ab2b68fb441b4d25ac189+CHANGES)

### Operating system and Environment details
CentOS 7.5+

### Issue
How about if the Nomad GUI was able to behave like "TableSorter" with filters for the clients' page.
I personally feel the need for a pinned filter (on top) of the client list when I want to search for connected/disconnected clients.

Example: https://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html

I don't fancy the dropdowns much, simple filter test boxes are OK with me.

What this would let the operator do is search within the clients and make for a much nicer user experience.

That said, I am not sure if this can be done within the current Nomad GUI framework, but just putting the idea out there.

Other than that, keep up the good work with all the GUI enhancements otherwise!!!

Cheers and Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil What are the filters you'd like

**Comment by shantanugadgil** [comment]
@dadgar anything that is currently part of `nomad node status -verbose` would be good to have.

**Comment by shantanugadgil** [comment]
hi @dadgar any updates on when/if this is planned? 🥇

**Comment by DingoEatingFuzz** [comment]
@shantanugadgil, I think eventually the Nomad UI will be able to do most things that jquery plugin can do. It won't look the same but the feature set will be roughly matched.

- [x] **Search:** this is already supported. It isn't per-field, but the search input does matching across appropriate fields in the dataset
- [x] **Sort:** columns that make sense to sort by can already be clicked to sort. This is also persisted in the URL for sharing.
- [ ] **Filtering:** this is still on the TODO list. Although search and sort can go a long way, it's not quite the same as, say "show me all the nodes that are currently ineligible for scheduling". We have already talked about how to implement this and what it will look like and it is definitely planned!

**Comment by backspace** [comment]
Filtering of clients and jobs was added as [part of 0.9.2](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#092-june-5-2019), have you gotten a chance to try it out, @shantanugadgil? I think that covers your requests, thanks for the suggestions!

**Comment by shantanugadgil** [comment]
My original use case is no longer very relevant (0.9.x added resiliency to restarts), though I have seen the GUI updates. I'll reply again if the existing features are inadequate. (I think the current features should suffice)
