### ISSUE TITLE
Ability to create a shorter token name

### ISSUE THREAD

**Issue by tbartelmess** [hashicorp/nomad#4411]
Amazon IAM usernames are limited in length, vault tokens are usually quite long. AWS IAM only allows 64 characters.

We are seeing a lot of warnings form Vault, with messages "the calling token display name/IAM policy name were truncated to fit into IAM username length limits", which is coming from here: https://github.com/hashicorp/vault/blob/3ba9486ba933283cba18a7d7f298947e892eaba9/builtin/logical/aws/secret_access_keys.go#L56

It would be good if we can generate the token names based on the allocation name or a short id of some kind.

**Comment by jippi** [comment]
wondering what it has to do with nomad? :)

**Comment by dadgar** [comment]
I am going to close this. Feel free to clarify your request more.

The ACL token is composed of three parts:
1. Token Accessor ID: This is a standard UUID and we will not shorten this.
2. Token Secret ID: This is a standard UUID and we will not shorten this.
3. Token Name: This is user definable and has a max length of 256. So it can be set as desired.
