### ISSUE TITLE
[feature request] Ability to stop particular allocation by id in task group

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#4419]
It will be cool. But here may be some problems in this approach:

1). consistency `NOMAD_ALLOC_ID`  env variables
2). count in task group also must be decreased, and generally speaking when taskgroup have only 1 allocation, this means factually stop

**Comment by tgross** [comment]
Doing a bit of issue cleanup. This was shipped back in 0.9 as [`nomad alloc stop`](https://www.nomadproject.io/docs/commands/alloc/stop)
