### ISSUE TITLE
[question] How to set a timeout value for a batch job?

### ISSUE THREAD

**Issue by molin0000** [hashicorp/nomad#4423]
How to set a timeout value for a batch job?

I want to limit the job max run time , how can I set the batch job's timeout value?

**Comment by shantanugadgil** [comment]
For now, there is no way to do that directly in Nomad.

What the folks usually recommend is using timeout and minor scripting to achieve the same.

HTH,
Shantanu

**Comment by molin0000** [comment]
@shantanugadgil How to use a timeout minor scripting?   For example? Thank you!

**Comment by preetapan** [comment]
@molin0000 We currently don't have support for killing batch jobs based on a timeout, like @shantanugadgil mentions. 

To do this yourself you have two options:

- Have the batch job stop and exit itself based on a timer
- Monitor the batch job using nomad's [allocation api](https://www.nomadproject.io/api/jobs.html#list-job-allocations) and if it has been running longer than your timeout period, stop it using the [API](https://www.nomadproject.io/api/jobs.html#stop-a-job) again

**Comment by dadgar** [comment]
Closed in favor of https://github.com/hashicorp/nomad/issues/1782

**Comment by onlyjob** [comment]
Coreutils' [timeout(1)](https://manpages.debian.org/buster/coreutils/timeout.1.en.html) command could be handy.
