### ISSUE TITLE
Prometheus can't scrape metrics from nomad leader when raft peers have ipv6 address

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#4429]
### Nomad version
Nomad v0.8.3

### Issue
Prometheus returns error: "invalid metric name" when scrape metrics from nomad leader and raft peers have ipv6 address

Example metrics name:
"nomad_raft_replication_appendEntries_logs_[xxxx:xxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx]:4647"

**Comment by alexiri** [comment]
@TheSpbra1n why did you close this issue? I'm having the same problem with ipv6 addresses in the metrics. Did you solve it somehow?

**Comment by TheSpbra1n** [comment]
Not actual, after upgrade raft protocol to v3 ( https://www.nomadproject.io/docs/configuration/server.html#raft_protocol )

**Comment by alexiri** [comment]
You're right, switching to raft protocol 3 solves this. Thanks!
