### ISSUE TITLE
Stale mode is not working with Remove Raft Peer

### ISSUE THREAD

**Issue by yuremboo** [hashicorp/nomad#4430]
We are using Operator API to automate outage recovering. Currently we faced with the problem of removal dead node in case no cluster leader. By the documentation we used [stale parameter](https://www.nomadproject.io/api/operator.html#stale): 
`curl -X DELETE 'http://127.0.0.1:4646/v1/operator/raft/peer?address=192.168.33.4&stale'`
The output is code 400 "No cluster leader". With others endpoints in Operator API stale param works fine.
Thanks.

**Comment by jippi** [comment]
tried `stale=1` ?

**Comment by yuremboo** [comment]
Tried, result is the same for both

**Comment by preetapan** [comment]
@yuremboo this is expected behavior. Making changes to the raft configuration requires a leader and quorum. The documentation is incorrect and we will update it today.

doing a `GET` to read the configuration should work when stale=true
