### ISSUE TITLE
Change health status for allocation when stopping

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#4436]
When deployments are running and allocations are stopping, there currently no easy way, using Consul, to drain connections to those allocations since they report `Healthy` like all other allocations. Having a way to identify through Consul that an allocation is stopping is ideal. I believe making it as "WARN" would be great.

Open for other ideas as well.

**Comment by preetapan** [comment]
@djenriquez when the tasks in an allocation are being stopped, they first cleanup by deregistering themselves from Consul https://github.com/hashicorp/nomad/blob/4e352f3814feb2f4f1c918b0dd2a09cb05c3ad36/client/allocrunner/taskrunner/task_runner.go#L1223 and then if your task has a [ShutDownDelay](https://www.nomadproject.io/api/json-jobs.html#shutdowndelay) that gives it extra time for inflight requests to complete.  This should meet your use case. 
Feel free to reopen with more details on your use case if `ShutDownDelay` doesn't solve what you need

**Comment by djenriquez** [comment]
Hey @preetapan Thanks for clarifying. I did verify this was the case, interestingly, our application doesn't behave that way, but thats our problem now 😉.
