### ISSUE TITLE
Windows: timeout during CPU fingerprinting

### ISSUE THREAD

**Issue by capone212** [hashicorp/nomad#4439]
### Nomad version
v0.8.3

### Operating system and Environment details
Windows

### Nomad Client logs (if appropriate)
```
==> Starting Nomad agent...
==> Error starting agent: client setup failed 2: fingerprinting failed: cannot detect cpu total compute. CPU compute must be set manually using the client config option "cpu_total_compute"
    2018/06/20 21:50:25.899751 [WARN] fingerprint.cpu: 1 error(s) occurred:
* Unable to obtain CPU information: <nil>
 2018/06/20 21:50:25.899751 [DEBUG] fingerprint.cpu: core count: 24
```

### Issue
Nomad client crashes at start after CPU fingerprinting failes. I have enhanced  logging and able to obtain proper error message:
```

2018/06/20 13:35:13 [WARN] fingerprint.cpu: 1 error(s) occurred:
* Unable to obtain CPU information: initErr:<nil> error:context deadline exceeded

```

We see this problem on small set of windows boxes. On those boxes request to WMI take a lot of time (17 seconds). It clearly depend on environment, can't say any specific reason for this behavior. 

I am attaching my patch which solved the issue for us. I am not opening pull request because the fix was done in external library.

[0001-increased-timeout-during-CPU-fingerprinting.patch.txt](https://github.com/hashicorp/nomad/files/2122954/0001-increased-timeout-during-CPU-fingerprinting.patch.txt)

**Comment by angrycub** [comment]
I experienced the same situation in 0.8.3 and resolved it with 0.8.4 because of https://github.com/hashicorp/nomad/pull/4265 for the log line and https://github.com/hashicorp/nomad/pull/4268 to extend the timeout for queries to 10 seconds.

It is interesting that you are seeing 17 second WMI queries, this will cause the newly extended timeout to still fail for you.  However, you could use the same technique used in #4268  and extend that timeout constant.  This would at least keep your modified code to the Nomad project.

**Comment by capone212** [comment]
Nice! Thanks for info.
I glanced changes and noticed this
cpuInfoTimeout = 10 * time.Second

10 seconds is too short for our case, clearly.

**Comment by sichkarmg** [comment]
this is time in seconds of execution cpuInfo.exe.
we make a test at 4 servers

`server1 | 16,4854817 | server2 | 16,6513576 | server3 | 16,6954994 | server4 | 16,7710169
server1 | 16,5614402 | server2 | 16,6765325 | server3 | 16,8458999 | server4 | 19,7886261
server1 | 16,552988 | server2 | 19,8700942 | server3 | 16,9373356 | server4 | 16,5826111
server1 | 16,4926388 | server2 | 16,8146097 | server3 | 17,0761553 | server4 | 16,5704299
server1 | 16,6032117 | server2 | 16,7367053 | server3 | 16,8137941 | server4 | 16,6422335
server1 | 16,4805015 | server2 | 16,6655336 | server3 | 20,1129079 | server4 | 19,8154056
server1 | 16,478773 | server2 | 16,6799758 | server3 | 17,4328294 | server4 | 16,6131672
server1 | 16,4731886 | server2 | 19,9734538 | server3 | 16,7082287 | server4 | 16,7729867
server1 | 16,6492901 | server2 | 19,8583623 | server3 | 16,6718831 | server4 | 16,648594
server1 | 16,4990013 | server2 | 16,654229 | server3 | 16,7171704 | server4 | 16,6905682
server1 | 16,4794345 | server2 | 16,677466 | server3 | 19,9731451 | server4 | 16,5710989
server1 | 16,4844758 | server2 | 16,6822428 | server3 | 19,9318865 | server4 | 20,0729409
server1 | 16,4724944 | server2 | 16,6769901 | server3 | 20,101162 | server4 | 16,6273733
server1 | 16,4967004 | server2 | 16,6562146 | server3 | 16,7146488 | server4 | 16,5932446
server1 | 16,4825374 | server2 | 16,6884024 | server3 | 16,7191455 | server4 | 16,6469576
server1 | 16,6420985 | server2 | 16,6892392 | server3 | 16,8116272 | server4 | 16,6200657
server1 | 16,5030532 | server2 | 16,7066194 | server3 | 16,7954851 | server4 | 19,8974235
server1 | 16,5068955 | server2 | 20,777593 | server3 | 16,6935614 | server4 | 17,8654949
server1 | 16,4785448 | server2 | 16,6874377 | server3 | 19,9003591 | server4 | 16,5895778
server1 | 16,504945 | server2 | 16,7349946 | server3 | 16,954795 | server4 | 16,7486083
server1 | 16,5834596 | server2 | 16,6608948 | server3 | 16,8118151 | server4 | 16,6313678
server1 | 16,4935135 | server2 | 19,9031621 | server3 | 16,8636957 | server4 | 19,8713032
server1 | 16,5411488 | server2 | 20,358991 | server3 | 33,9048027 | server4 | 16,5752059
server1 | 16,6218552 | server2 | 16,6522954 | server3 | 21,0636149 | server4 | 17,0416627
server1 | 16,4809904 | server2 | 38,0749896 | server3 | 19,9450854 | server4 | 16,6247914
server1 | 16,5091036 | server2 | 19,8974509 | server3 | 16,7748172 | server4 | 16,5716234
server1 | 16,5616786 | server2 | 16,6700697 | server3 | 16,7132704 | server4 | 16,8623443`

**Comment by capone212** [comment]
cpuinfo is simple test tool:

```

import (
        "github.com/hashicorp/nomad/helper/stats"
        "log"
)

func main() {
        if err := stats.Init(); err != nil {
                log.Printf("[WARN] fingerprint.cpu: %v", err)
        }

        log.Printf("CPUModelName %v", stats.CPUModelName())
        log.Printf("CPUMHzPerCore %v", stats.CPUMHzPerCore())
        log.Printf("CPUNumCores %v", stats.CPUNumCores())
        log.Printf("TotalTicksAvailable %v", stats.TotalTicksAvailable())
}
```

**Comment by sichkarmg** [comment]
Hello,

Below are testing results on real windows 2012 R2 servers in production environment. Numbers are seconds of execution. Tests were repeated 20 times for each of four servers.
`
server1 | 16,49
server1 | 16,56
server1 | 16,55
server1 | 16,49
server1 | 16,60
server1 | 16,48
server1 | 16,48
server1 | 16,47
server1 | 16,65
server1 | 16,50
server1 | 16,48
server1 | 16,48
server1 | 16,47
server1 | 16,50
server1 | 16,48
server1 | 16,64
server1 | 16,50
server1 | 16,51
server1 | 16,48
server1 | 16,50
server1 | 16,58
server1 | 16,49
server1 | 16,54
server1 | 16,62
server1 | 16,48
server1 | 16,51
server1 | 16,56
server2 | 16,65
server2 | 16,68
server2 | 19,87
server2 | 16,81
server2 | 16,74
server2 | 16,67
server2 | 16,68
server2 | 19,97
server2 | 19,86
server2 | 16,65
server2 | 16,68
server2 | 16,68
server2 | 16,68
server2 | 16,66
server2 | 16,69
server2 | 16,69
server2 | 16,71
server2 | 20,78
server2 | 16,69
server2 | 16,73
server2 | 16,66
server2 | 19,90
server2 | 20,36
server2 | 16,65
server2 | 38,07
server2 | 19,90
server2 | 16,67
server3 | 16,70
server3 | 16,85
server3 | 16,94
server3 | 17,08
server3 | 16,81
server3 | 20,11
server3 | 17,43
server3 | 16,71
server3 | 16,67
server3 | 16,72
server3 | 19,97
server3 | 19,93
server3 | 20,10
server3 | 16,71
server3 | 16,72
server3 | 16,81
server3 | 16,80
server3 | 16,69
server3 | 19,90
server3 | 16,95
server3 | 16,81
server3 | 16,86
server3 | 33,90
server3 | 21,06
server3 | 19,95
server3 | 16,77
server3 | 16,71
server4 | 16,77
server4 | 19,79
server4 | 16,58
server4 | 16,57
server4 | 16,64
server4 | 19,82
server4 | 16,61
server4 | 16,77
server4 | 16,65
server4 | 16,69
server4 | 16,57
server4 | 20,07
server4 | 16,63
server4 | 16,59
server4 | 16,65
server4 | 16,62
server4 | 19,90
server4 | 17,87
server4 | 16,59
server4 | 16,75
server4 | 16,63
server4 | 19,87
server4 | 16,58
server4 | 17,04
server4 | 16,62
server4 | 16,57
server4 | 16,86

`
