### ISSUE TITLE
[question] Rescheduling job on another node after outage recovery

### ISSUE THREAD

**Issue by treanz** [hashicorp/nomad#4443]
`[question]`
### Nomad version
`0.8.4`

### Operating system and Environment details
`CentOS Linux release 7.4.1708 (Core)`

### Question
I have 2-machines setup. Nomad run in server+client mode on each host (2 servers and 2 clients) connected via consul. And there are two jobs, running on second host, with reschedule params. To run them on the first node **after network failure** i create **peers.json** file in raft directory (outage recovery), and restart nomad. Nomad continue to "observe" running jobs on second host for about 5 minutes, and only after this delay my jobs are rescheduled on first host and second node status changes from **ready** to **down**.
> node-02  is unreachable from  node-01, but node-02 status is ready
```
ID        DC    Name           Class   Drain  Eligibility  Status  Running Allocs
ba0d56c7  dc1  node-01  <none>  false  eligible     ready   0
ac1dd9fa  dc2  node-02  <none>  false  eligible     ready   2

```

At this time status of one of allocations produces next message: `nomad alloc status 603d7994`
```
ID                  = 603d7994
...
Client Status       = running
Desired Status      = run
...

Couldn't retrieve stats: Unexpected response code: 404 (No path to node)

Task "taskname" is "running"
```
Can i reduce/configure delay between networking disconnect and rescheduling  somehow? 

### Reproduction steps

1. Start job on second node
2. Disable networking
3. Create file peers.json on first node
4. Restart nomad on the first node
5. Wait 5 minutes :)

### Job file (if appropriate)
```
job "jobname" {
 ....
  datacenters = [    "dc1",    "dc2"]

  group "groupname" {
    count = 1

    restart {
      attempts = 3
      delay = "15s"
      mode = "fail"
    }

    reschedule {
      delay = "15s"
      delay_function = "exponential"
      max_delay = "120s"
      unlimited = true
    }

    task "taskname" {
      driver = "docker"
      ...
     }

      service {
        name = "servicename"
        port = "db"
        check {
          name = "alive"
          type = "tcp"
          interval = "10s"
          timeout = "2s"
        }
      }
```

**Comment by rkettelerij** [comment]
Do note that from a reliability perspective a 2 node setup isn't recommended. With 2 nodes you can't tolerate the loss of one node. The recommended deployment is either 3 or 5 servers. See https://www.nomadproject.io/docs/internals/consensus.html

**Comment by dantoml** [comment]
Nomad allows some minimal configuration of node heartbeats via the `"min_heartbeat_ttl"`, `"heartbeat_grace"`, and `"max_heartbeats_per_second"` configuration options in the [Server configuration](https://www.nomadproject.io/docs/configuration/server.html).

However, I would be incredibly wary of running a 2 node deployment as the failure of either node is a critical failure to your deployment, and would prevent jobs from being rescheduled until a cluster is revived.
