### ISSUE TITLE
Network dependency not satisfied properly

### ISSUE THREAD

**Issue by FlorinAsavoaie** [hashicorp/nomad#4447]
If filing a bug please include the following:

### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
- Ubuntu 16.04.2 LTS
- IPVLAN Network Driver for Docker
- Docker 17.12.0-ce

### Issue
When using a "container:XXX" network mode, the task using this network doesn't get restarted when the container of which network it uses restarts.

### Reproduction steps
Create a job, with a group, and 2 tasks. First task has whatever network_mode, second task has "container:Task1-${NOMAD_ALLOC_ID}" as network. Restart the first task. Second task will not restart in order to satisfy the network dependency, it will remain on the original network of the first task.

**Comment by FlorinAsavoaie** [comment]
The issue is definitely still there.

**Comment by djenriquez** [comment]
@FlorinAsavoaie, one possible mitigation for this is to set the container with the dependent network as [leader](https://www.nomadproject.io/docs/job-specification/task.html#leader) in the config. If this container dies, the task associated with it will die as well. The bigger problem though is having proper dependency management (ever have the case where the dependent service starts before the independent one?), which is highlighted in https://github.com/hashicorp/nomad/issues/419. Rumors are this will be available at 0.10.0, hopefully the rumors are true.
