### ISSUE TITLE
[Fingerprint] suppport consul-kv as fingerpirnt config source

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#4448]
1. Too many fingerprints, we do not add a go file to support
use consul-kv config it.

**Comment by chelseakomlo** [comment]
Do you mind clarifying this comment? Is the request to add Consul-KV as a configuration option for Nomad to fingerprint, as opposed to fingerprinting by default?

**Comment by linuxgood1230** [comment]
Now, It is very hard work to define user own schedule strategy.
Like database , we can not use bin-pack. database not just a  process, we want locate new database in lower number mysql master instance.

**Comment by linuxgood1230** [comment]
Like https://github.com/hashicorp/nomad/issues/4300
