### ISSUE TITLE
[Schedule] schedule is core function, can user define their owner

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#4450]
1. may you define the Algorithm and logic. like bin-pack, spread out
Least Recently Used.
2. we define data , the tag key value to schedule
3. we define schedule tag sort, like sort , disk, ram, cpu, (mysql_master, mysql_slave, mysql_iops...user defined key value)
4. the data define in the consul-kv

**Comment by linuxgood1230** [comment]
Also: https://github.com/hashicorp/nomad/issues/2985

**Comment by dantoml** [comment]
Nomad doesn't support overriding the scheduler implementation, but we do now however support affinities and spread, alongside constraints based on node metadata and attributes.

I would recommend filing issues for specific scheduler features that you would like to be supported as part of core.

Thanks!
