### ISSUE TITLE
sloppy vendoring of "hashicorp/yamux"; commit does not exist

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4455]
[hashicorp/yamux/](https://github.com/hashicorp/yamux) is vendored by unknown commit:

 https://github.com/hashicorp/nomad/blob/master/vendor/vendor.json#L191

The problem is that commit 2658be1 is missing from [yamux history](https://github.com/hashicorp/yamux/commits/master).

**Comment by chelseakomlo** [comment]
Thanks for letting us know about this issue- indeed, we try to be careful with issues like this (we've had similar problems with our own dependencies). 

We'll investigate and if needed upgrade to the latest version of yamux to fix this issue.

**Comment by onlyjob** [comment]
keepalive

**Comment by endocrimes** [comment]
@onlyjob It looks like this issue has been resolved as we now vendor yamux at [7221087c3d281fda5f794e28c2ea4c6e4d5c4558](https://github.com/hashicorp/yamux/commit/7221087c3d281fda5f794e28c2ea4c6e4d5c4558). Sorry for missing resolving this.
