### ISSUE TITLE
[0.8.4] Nomad UI Hanging on Allocation Viewing

### ISSUE THREAD

**Issue by gwellington** [hashicorp/nomad#4464]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
0.8.4

### Operating system and Environment details
Ubuntu 16.04.4 LTS

### Issue
In the Nomad UI, when you click on a job or client to view allocations, the UI hangs attempting to load allocations instead of loading the actual allocations.   

I was able to still use the CLI to run `nomad status` to view the jobs and view their underlying allocations through `nomad status <job name>`

### Reproduction steps
I haven't been able to reproduce this again, but it seems like it's related to the below error.  There was a periodic job launch that was still in the allocations list, but the parent job had aged out -- presumably due to errors or something else.  

The issue occurred during a re-roll of our Nomad stack (replacing 1 of 3 Nomad servers, 1 at a time)

### Nomad Server logs (if appropriate)
Some errors that we were seeing:
2018/07/03 01:02:19.225652 [ERR] http: Request /v1/job/<job name>, error: job not found"}}
2018-07-03T01:00:08.537Z [DEBUG] plugin.nomad: 2018/07/03 01:00:08 [ERR] plugin: plugin server: accept unix /tmp/plugin431595384: use of closed network connection

**Comment by nickethier** [comment]
Hi @gwellington 

Sorry you're experiencing this issues. I've got a few questions for you to try and get to the bottom of this:
 * What browser and version were you using when you experienced this?
 * You mentioned that you experienced this while "re-roll"ing nomad servers. What does this mean exactly? Were you upgrading them? If so from what version?

**Comment by vipul-hk** [comment]
The ui lists the jobs correctly but hangs trying to load job details.
Console log shows the following error message. I started getting this behaviour after running the following periodic task.

CLI works fine and I can see that the periodic task is running correctly.

<img width="1680" alt="screen shot 2018-10-01 at 4 01 56 am" src="https://user-images.githubusercontent.com/6162849/46262074-e7078f80-c52e-11e8-9102-44d112cf3e9e.png">

**Task snippet**
{
  ...
  type = "batch"

  periodic {
    // Launch every 1 minute
    cron = "*/1 * * * * *"

    // Do not allow overlapping runs.
    prohibit_overlap = true
  }

    task "cron" {
      driver = "docker"
      config {
        auth {
            username = ""
            password = ""
        }
        image = ""
        command = "/bin/bash"
        args = ["-c", "pipenv run ./manage.py update_device"]
      }
  ...
{

**Comment by DingoEatingFuzz** [comment]
Hi @vipul-hk, what URL are you trying to load? Is that `/jobs/:job_id/allocations`? 

That error message suggests that there is something fishy with an API response. Which isn't to say the API response is bugged, but it may be in a shape the UI isn't expecting but should support.
