### ISSUE TITLE
Documentation on Network resources outdated

### ISSUE THREAD

**Issue by carlosdp** [hashicorp/nomad#447]
I think this happened around 87f49c4f , but it looks like Nomad wants networks to look like this now:

```
...
network {
  port "http" {
    dynamic = 80
  }
}
```

The documentation hasn't been updated, I only figured it out by looking at the tests.

Edit: in master, not 1.2 clearly

**Comment by cbednarski** [comment]
@carlosdp Thanks! We're working on the docs now. Can you link to the pages that you noticed are out of date?

**Comment by carlosdp** [comment]
The only one I had noticed was the main Job Spec page https://github.com/hashicorp/nomad/blob/master/website/source/docs/jobspec/index.html.md , but looks like @diptanu fixed it today in 8917fd8

**Comment by dadgar** [comment]
Thanks @carlosdp! Going to close this since it is resolved now.
