### ISSUE TITLE
[question] Setting update stanza parameters globally

### ISSUE THREAD

**Issue by ppiastucki** [hashicorp/nomad#4478]
Hi,

Is it possible to configure healthy_deadline and other update stanza parameters globally for all jobs? 
I know it can be configured on a per-job basis but I am looking to change the default values (5 minutes  in case of healthy_deadline) to something else and ensure the new default value is automatically inherited by any jobs that do not overwrite it.

**Comment by dantoml** [comment]
👋 It's currently not possible to do that in a first class way, but would potentially be solvable with future implementation of Admission Controllers (#4735). Thanks for reporting this!
