### ISSUE TITLE
[question] Custom route for Nomad UI

### ISSUE THREAD

**Issue by mgkanani** [hashicorp/nomad#4479]
Hi,

Is there any configuration for Nomad-UI to have different endpoint(e.g.` /nomad-ui`) instead of `/`? I could not find any such configuration in documentation. It really helps in grouping all the nomad related requests when Nomad-ui is behind the proxy.

Thanks,
Mahendra

**Comment by dantoml** [comment]
There's currently no way to remount the UI under a different endpoint as part of Nomad itself.

Many proxies should be able to manage rewriting /nomad to / on the nomad port however?

**Comment by mgkanani** [comment]
With nomad-ui, there are more than one pattern i.e. /nomad, /ui, and /v1. Going-frwd, new routes may be added or can change. In those cases, proxy's configuration again has to be changed.
Usually, not just nomad-ui but other applications can share same proxy-server which can leads to added complexity. If nomad provides the custom-route then proxy's configuration updates are not required.

**Comment by Fuco1** [comment]
Can we revive this?  Similar feature landed for consul https://github.com/hashicorp/consul/issues/1930 and it makes the life of many people much easier.

**Comment by Fuco1** [comment]
@MGasztold The trick is in forwarding the api calls.  Nomad frontend or something adds a referer header which you can (ab)use for this.  My config is something like this:

```
[http.routers]
  [http.routers.nomad]
    rule = "PathPrefix(`/nomad`) || PathPrefix(`/v1/client/fs/cat`) || HeadersRegexp(`referer`, `https://mydomain.com/nomad/.*`)"
    priority = 1999
    service = "nomad"
```

This is for traefik 2+.

The `/v1/client/fs/cat` is for "file system access" from the UI.

**Comment by MGasztold** [comment]
@Fuco1  Hello, thank you for you answer. After I applied your router to my setup I get redirected to https://mydomain.com and there is nothing :(

**Comment by Fuco1** [comment]
@MGasztold Actually I have `/ui` instead of `/nomad`.  I copied this setup from consul where I do use a subpath.  I think for nomad you would need to use some rewriting on that, but since the api calls can't be hosted elsewhere, that's where the referer trick comes in play.  I basically just gave up trying to redirect nomad.
