### ISSUE TITLE
Interpreted variables in environment variables

### ISSUE THREAD

**Issue by bluk** [hashicorp/nomad#448]
The Constraint section in the [Job Specification](https://www.nomadproject.io/docs/jobspec/index.html) has a table with interpreted variables such as `$node.id` and `$meta.<key>`. I assume the interpreted variables are meant for just constraints but I want to use them in other parts of the config.

For my use case, I've added some host machine unique metadata to the Nomad client's [meta](https://www.nomadproject.io/docs/agent/config.html#meta) configuration and want to pass that onto a task.

I tried using them in in a task's `env` section like:
```
env {
  MY_ENV_NAME = "$node.id"
}
```

However, the value is set to the literal string `$node.id` (so not interpreted). 

Is there some way to do this? Thanks!

**Comment by cbednarski** [comment]
@bluk Thanks for opening an issue. This is currently supported only in a limited capacity. We'd like to expand this in a future release.

To design and implement this correctly can you describe your use case? For example, I know one use-case is to configure docker container networking via `container:<id-of-container-with-networking>`.

**Comment by bluk** [comment]
@cbednarski Actually I'm trying to use the Nomad's client meta (used `$node.id` as a simpler example). Sorry for the misleading example.

I am putting a unique UUID for Vault to use in Nomad's client meta configuration. Then I was hoping to use `$meta.uuid` to have the variable interpreted by Nomad when the task was run. When a Docker container is run, it would be passed the UUID as an environment variable, and I could use the [Auth Backend: App ID](https://vaultproject.io/docs/auth/app-id.html) to lookup some credentials.

**Comment by cbednarski** [comment]
@bluk I see. So to clarify, you want to pass a value based on which _node_ the job is placed on?

Thanks for highlighting that use case! I think we can improve this. What I would recommend for now is putting a file on the filesystem on that machine, which you can read in your exec or mount into a container.

**Comment by bluk** [comment]
@cbednarski Yes, exactly! :)

Forgive my ignorance, but how do you mount an arbitrary filesystem into your container via Nomad? I didn't see any way to do that in the documentation.

**Comment by cbednarski** [comment]
@bluk Ah that's a good question. We don't actually support this yet. Sorry to mislead you about this!

**Comment by macb** [comment]
For the new `system` type it would be nice to gather some information for common application configuration, such as `hostname` or `ip`. This would be equally useful as `args` for the fork/exec drivers.
