### ISSUE TITLE
[question] Is there a way to avoid network binding at all on nomad clients?

### ISSUE THREAD

**Issue by sumerman** [hashicorp/nomad#4482]
It is advised to run a nomad client as a root. Therefore allowing it to listen on any network interface, even a loopback doesn't sit right with me. Furthermore, from the architecture documentation, it doesn't seem necessary. I was unable to find a way to disable undesired behavior in the documentation. Did I miss something?

**Comment by preetapan** [comment]
@sumerman Nomad clients are recommended to run as root for certain drivers to work, particularly the exec driver which does chroot and creates cgroups. 

You don't have to make nomad listen on all interfaces, the configuration for client agents support restricting bind/rpc/serf addresses as appropriate. https://www.nomadproject.io/docs/agent/configuration/index.html#addresses

**Comment by sumerman** [comment]
Thank you for the answer. Is it feasible to add an option that'd completely prevent it from listening on any network interfaces? Or is there a part of functionality requires nomad-clients to accept connections?

**Comment by preetapan** [comment]
Clients need to listen on the specified http port for [client end points](https://www.nomadproject.io/api/client.html) to get allocation stats, read log files etc which is required to provide visibility into a specific running task.

**Comment by sumerman** [comment]
It also states:

>Since Nomad 0.8.0, both a client and server can handle client endpoints. This is particularly useful for when a direct connection to a client is not possible due to the network configuration. For high volume access to the client endpoints, particularly endpoints streaming file contents, direct access to the node should be preferred as it avoids adding additional load to the servers.

I read this as: "it's nice if a client can listen on HTTP, but not required." In other words, if I send a PR, will it be at least considered?

**Comment by preetapan** [comment]
@sumerman Since Nomad 0.8.0 it is no longer necessary for clients to bind to the RPC or HTTP port for allocation stats to work, however there's more work outstanding around making config validation work when the ports are not specified, as well as handling ephemeral disk migration which still uses the HTTP port. I opened #4482 to track this.
