### ISSUE TITLE
[ Feature/Question ] Ability to reload config meta variables on SIGHUP to nomad agent

### ISSUE THREAD

**Issue by ramSeraph** [hashicorp/nomad#4483]
It would be nice to have nomad agent reload meta variables in the client config on SIGHUP.

currently, this requires a nomad agent restart.. though this hasn't caused any problems yet.. this seems a bit extreme.. reload would be nicer if possible. 

Alternatively, I would like a confirmation that restarting the nomad agents often( quite a few together in a span of minutes, maybe once a day ) is not a dangerous operation.

**Comment by linuxgood1230** [comment]
I think meta need store in consul-kv as fingerprint.
Reload client, a lot work.

**Comment by ramSeraph** [comment]
@linuxgood1230 consul-kv as fingerprint and ability to set constraints on jobs based on the consul-kv values would be ideal for me.. because the data for the current meta variables of the nomad agent is coming from consul-kv.. but this would mean some convention about which consul kv values are for which node.. ( i am guessing setting up that convention and making it generic would require careful thought )

This feature is useful when you have a fixed set of bare metal hosts and you would like to change roles of the hosts to add/remove them from the various job pools..

**Comment by preetapan** [comment]
@ramSeraph this is as designed  - since meta data can affect scheduling the idea is that operators that change node metadata also shutdown and restart the client so that any existing allocs can be migrated elsewhere.
