### ISSUE TITLE
Nomad does not try to restart a system job that failed due to the template renderer

### ISSUE THREAD

**Issue by SergeyYakubov** [hashicorp/nomad#4484]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
### Operating system and Environment details
CentOS Linux release 7.5.1804 (Core) 
### Issue

After a node reboot Nomad tries to start a system job that is supposed to run on this node. But apparently a filesystem where the template is located is not mounted yet and the job fails.

07/09/18 10:36:11 | Setup Failure | failed to build task's template manager: failed to read template: open /bldocuments/support/asapo/config/nomad_jobs/nginx.conf.tpl: no such file or directory
-- | -- | --

 The expected behavior would be to try to restart the job according to the restart policy but it never happens.

### Job file (if appropriate)
job "nginx" {
  datacenters = ["dc1"]
  type = "system"
  group "nginx" {
    count = 1
    restart {
      attempts = 2
      interval = "3m"
      delay = "15s"
      mode = "delay"
    }
    task "nginx" {
      driver = "docker"
      config {
        network_mode = "host"
        image = "nginx:1.14"
        volumes = ["local/nginx.conf:/etc/nginx/nginx.conf"]
      }
      resources {
        cpu    = 500
        memory = 256
        network {
          mbits = 10
          port "nginx" {
          static = 8400
          }
        }
      }
      service {
        port = "nginx"
        name = "nginx"
        check {
          name     = "alive"
          type     = "http"
	      path     = "/nginx-health"
          timeout  = "2s"
	      interval = "10s"
        }
        check_restart {
          limit = 2
          grace = "15s"
          ignore_warnings = false
        }
      }
      template {
         source        = "/bldocuments/support/asapo/config/nomad_jobs/nginx.conf.tpl"
         destination   = "local/nginx.conf"
         change_mode   = "restart"
      }
   }
  }
}

**Comment by preetapan** [comment]
Hi @SergeyYakubov - Task setup failures are considered irrecoverable and so the restart policy doesn't take effect. This is working as designed because if Nomad fails in the task set up stage (wrong executable path/missing file system etc, its not useful to keep restarting). 

However your use case with a system job, and using a network mounted filesystem that may not be available when the task runs is interesting. We'll discuss this internally and give you an update.

**Comment by preetapan** [comment]
@SergeyYakubov discussed this internally and while we can special case system jobs to always restart, it introduces unnecessary work in cases where a required precondition is not present (like a filesystem or external resource missing). 

As a workaround, in your environment, you could enforce that any filesystems needed by jobs are mounted on nomad client nodes first prior to running nomad jobs on them, 

We have future work planned in #4267 for improving the system job scheduler, that will also address this by causing a reschedule for any failed system jobs.
