### ISSUE TITLE
[feature request] exec driver with syslog forwarding

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#4494]
### Nomad version
0.8.4

### Operating system and Environment details
CentOS 7.5+

### Issue
How about if the "exec" driver was able to forward the stdout/stderr of the process to a central syslog server?

Do you think the request makes sense?

This came to mind while comparing 'exec' with 'docker' (docker+syslog combination)

Cheers and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
I have been thinking about this a bit ...

After discovering the "logger" cmd based forwarding to a central server ... I thought of another way ...

Use the **docker** driver configured with syslog forwarding to a central server, then mount all the *needed* directories** from the base machine into the docker.

Use the **artifact** stanza to download relevant binaries (inside the docker) and execute it.

The round-about hack will allow to tap into the "syslog" block of the docker and not have to fiddle with the logger cmd.

Thoughts?

**Comment by schmichael** [comment]
Sorry this never got a response! We hope to implement logging plugins similar to what @jozef-slezak outlined in #5490. #1469 seems to be the earliest mention of logging plugins, so I'm consolidating the discussion there.
