### ISSUE TITLE
[feature request] check_reschedule stanza

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/nomad#4499]
It is great to have ability to reschedule job (to other node), if check is unsuccessful.

Use case: some node is failing by some reason, nomad continue normally working on this node, but jobs - not. And their health checks fails.

As example, this may be external network problem. But internal network is working. And if job migrates to other node in this case - it begin to work normally.

check_restart stanza is excellent, but it only restart job on the same node.

If you liked this idea, I can try to do PR with this functional.

**Comment by dadgar** [comment]
Hey @kak-tus,

If you have your restart stanza mode to "fail" which is the default, and use check_restart you get this behavior.

**Comment by wapclick** [comment]
Thank you. I've tried this, but job was not rescheduled. I will try again.

**Comment by kak-tus** [comment]
Thank you. I've tried this, but job was not rescheduled. I will try again.
