### ISSUE TITLE
Can't resolve relative path for local artifacts when provisioning docker tasks

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/nomad#4500]
### Nomad version
`0.8.4`

### Operating system and Environment details
macOS with Docker for Mac

### Issue
Receiving message _"failed to download artifact "../": relative paths require a module with a pwd"_

### Reproduction steps

I sent this to my API:

```json
{
    "Job": {
        "ID": "local-development",
        "Name": "local-development",
        "Type": "service",
        "Datacenters": [
        	"local"
    	],
        "TaskGroups": [{
            "Name": "infrastructure",
            "Tasks": [{
                "Name": "proxy",
                "Driver": "docker",
                "Config": {
                    "image": "nginx:alpine",
                    "port_map": [{
                        "proxy": 80
                    }],
                    "volumes": [
                        "./resources/nginx.conf:/etc/nginx/nginx.conf",
                        "./resources/nginx.default.conf:/etc/nginx/conf.d/default.conf"
                    ]
                },
                "Services": [{
                    "Id": "proxy",
                    "Name": "proxy",
                    "Tags": [
                        "proxy",
                        "local"
                    ],
                    "PortLabel": "proxy"
                }],
                "Resources": {
                    "Networks": [{
                        "DynamicPorts": [{
                            "Label": "proxy",
                            "Value": 80
                        }]
                    }]
                },
                "Artifacts": [
                	{
                		"GetterMode": "dir",
        		         "GetterSource": "../"
                	}
            	]
            }],
            "RestartPolicy": {
                "Interval": 5000000000,
                "Attempts": 1,
                "Delay": 0,
                "Mode": "delay"
            }
        }]
    }
}
```

**Comment by atrauzzi** [comment]
That doesn't seem to work. The files have to be on the machine before I can reference them.  It's also not clear what my PWD or sucker context is when the commands run on the machine.

I know the path based on where I'm running the command, but it must be relative because it is inside of a repository that could be checked out anywhere on someone's hard drive.

**Comment by Dirrk** [comment]
@atrauzzi 
> That doesn't seem to work. The files have to "sent" to the machine before I can reference them. It's also not clear what my PWD or docker context is when the commands run on the machine.

> I know the path based on where I'm running the command, but it must be relative because it is inside of a repository that could be checked out anywhere on someone's hard drive.

I think you are misunderstanding how the artifact stanza works.  The artifact stanza defines an artifact that the nomad client will download/fetch before starting the nomad tasks.  This means that you must provide a remote artifact location (s3/http/git...) that the nomad client can retrieve said artifact from.   What it appears that you are assuming is that, when you run `nomad run` that it will fetch the local artifact and provide that to the task when needed.  However, you should assume that NOTHING except for the job file is to be stored locally.  

A potential solution could be for you to upload the nginx.conf to a website that you control or to an s3 bucket and have the nomad job reference that config in the artifact stanza.  But be sure that if it is s3 that the nomad client has access to that s3 bucket.

**Comment by atrauzzi** [comment]
What's the difference between local filesystem and S3 in this case then?  Sure, the only thing is the job. But if the machine the job is running on has files and I know where to find them...??

**Comment by Dirrk** [comment]
@atrauzzi I personally would use the full path and mount a volume as I originally suggested. But as it stands it doesn't appear to support what you are trying to do.  Hopefully that helps.

**Comment by atrauzzi** [comment]
Gotcha, thanks!
