### ISSUE TITLE
too many many bugs

### ISSUE THREAD

**Issue by lxy9805287** [hashicorp/nomad#4508]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `0.8.4`

### Operating system and Environment details
centos 6.5 x64

**Comment by hexfusion** [comment]
@lxy9805287 could you please elaborate on the issue, I don't see any details of a single bug let alone many.
