### ISSUE TITLE
failed to allocate all place holder

### ISSUE THREAD

**Issue by Anand231985** [hashicorp/nomad#4556]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

### Nomad Server logs (if appropriate)
==> Evaluation "319a92a8" finished with status "complete" but failed to place all allocations:
    Task Group "web-app" (failed to place 2 allocations):
      * Class "aj" filtered 1 nodes
      * Class "common" filtered 1 nodes
      * Constraint "distinct_hosts" filtered 1 nodes
      * Constraint "computed class ineligible" filtered 1 nodes
      * Resources exhausted on 3 nodes
      * Class "common" exhausted on 3 nodes
      * Dimension "network: reserved port collision" exhausted on 3 nodes
    Evaluation "0d3bb6e4" waiting for additional capacity to place remainder
[Pipeline] echo
[ERROR][29:20] Nomad run failed with exit code [2]
### Job file (if appropriate)
I have few dead jobs on the server. Is there a way to release them.

**Comment by Anand231985** [comment]
I have few dead jobs on the server. Is there a way to release them.

**Comment by chelseakomlo** [comment]
Have you tried GCing these jobs? https://www.nomadproject.io/api/system.html#force-gc

Do you mind outputting the status of the jobs which are dead but haven't been removed from the Nomad client? https://www.nomadproject.io/docs/commands/job/status.html

**Comment by Anand231985** [comment]
Yes. I tried but it didn't help.
