### ISSUE TITLE
Specify Layer 4 Protocol for Port Allocation

### ISSUE THREAD

**Issue by cpg1111** [hashicorp/nomad#4561]
### Nomad version
`Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)`

### Operating system and Environment details
From `uname -a`: `Linux <redacted hostname> 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Issue
I will preface this with the fact I'm not entirely sure this is the best place for a feature request, but...

Currently, _to the best of my knowledge_, there is no way to specify if a port within the network stanza of a Job is TCP, UDP or both, and instead opens ports for both TCP and UDP.  In certain cases, it'd be useful to be able to specify which protocol the port is for, particularly for static ports where there maybe another process listening on the same port number but a different protocol than the job you are trying to get nomad to schedule.  I can't speak for qemu, but I know docke and rkt have this ability.  I can also see this having benefits for non-isolated host networking.

### Reproduction steps
Schedule a job that only uses tcp or udp on a fixed port, while another process is listening on the other protocol with the same port number.

**Comment by chelseakomlo** [comment]
Thank you for the feature request- after discussing this as a team, we are going to close this as it isn't clear what the intended use case of adding this feature would be. Furthermore, adding this feature would also add more complexity for operators when writing a jobspec and also add more complexity to scheduling decisions/operations. 

Feel free to add use cases to this ticket and we can continue to think about it, but for the short term we will err on the side of operator/scheduling simplicity. If you have questions about workarounds for this issue, feel free to ask here as well.

**Comment by cpg1111** [comment]
I'm sorry, I tried presenting a use case, but it must not have been clear.  The particular use case I was trying to convey involves having two jobs, these jobs need to be on a specific reserved port due to requirements of a protocol, lets use DNS for example, this is a protocol that is both over TCP and UDP, now if one job handles all TCP traffic and another job handles all UDP traffic, but need port 53 (resolv.conf doesn't support ports and public DNS servers need to be on 53), so currently this would result in only one of the two jobs having this port per host that they are scheduled on.  This isn't ideal.

As to added complexity, I beg to argue that.  A default of both would make no difference from current behavior, and operators would only need to specify when they would require this ability.  I do recognize additional complexity in the scheduler, however these are separate resources, and currently one of these two resources (port x on tcp, and port x on udp) can be wasted.  This is a feature of the IP stack that in using nomad, I would then lose.

After doing some digging, it seems all drivers for nomad support specifying TCP or UDP. And from looking at nomad's source, I see a reasonable implementation path and I'd be happy to submit a PR for this, time permitting.
