### ISSUE TITLE
Unable to disable update checking

### ISSUE THREAD

**Issue by arnobroekhof** [hashicorp/nomad#4562]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Operating system and Environment details
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

### Issue
Unable to disable update checking 

### Reproduction steps
put the following setting into the nomad configuration file:

```
disable_update_check = true
```

### Nomad Server logs
```
==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/nomad?arch=amd64&os=linux&signature=&version=0.8.4: dial tcp 23.23.145.13:443: connect: no route to host
```

### Nomad Client logs
```
==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/nomad?arch=amd64&os=linux&signature=&version=0.8.4: dial tcp 23.23.145.13:443: connect: no route to host
```

**Comment by chelseakomlo** [comment]
Thanks for reporting this issue- we reproduced the issue and will be adding a fix for this in our upcoming release.

**Comment by shantanugadgil** [comment]
@chelseakomlo Is 0.8.5 happening anytime soon? 😄  OR do we have to wait for 0.9.0 ?!? 😢
