### ISSUE TITLE
Enterprise only Error SPAM

### ISSUE THREAD

**Issue by RenEvo** [hashicorp/nomad#4567]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
```
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
```

### Operating system and Environment details

Windows

### Issue

Error Log Spam for enterprise only:

```
    2018/08/08 21:21:31.214586 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/08/08 21:21:31.325613 [ERR] http: Request /v1/namespace/default, error: Nomad Enterprise only endpoint
```

### Reproduction steps

Start single node nomad server, navigate UI

### Nomad Server logs (if appropriate)

```
    2018/08/08 21:21:31.214586 [ERR] http: Request /v1/namespaces, error: Nomad Enterprise only endpoint
    2018/08/08 21:21:31.325613 [ERR] http: Request /v1/namespace/default, error: Nomad Enterprise only endpoint
```

**Comment by dadgar** [comment]
Hey we will likely fix this in 0.9.1

**Comment by analytically** [comment]
Still the case in 0.11.3.

**Comment by fogg4444** [comment]
Still the case in v0.12.0

**Comment by savichev** [comment]
Still the case in v0.12.7 (6147cb578794cb2d0c35d68fe1791728a09bb081)

**Comment by tgross** [comment]
We've "fixed" this bug by moving namespaces into OSS in Nomad 1.0.0! ref https://github.com/hashicorp/nomad/issues/9135

**Comment by martialblog** [comment]
@tgross and we love you for that! 

Cheers
