### ISSUE TITLE
Add nomad driver for Facebook eXecutable ARchives (XAR)

### ISSUE THREAD

**Issue by sboisson** [hashicorp/nomad#4569]
Facebook has developed and deployed XARs, or eXecutable ARchives, a system for distributing self-contained executables that encapsulate both data and code dependencies.

https://code.fb.com/data-infrastructure/xars-a-more-efficient-open-source-system-for-self-contained-executables/

A XAR is a simple combination of a few primitives:

- A four-kilobyte preamble that is a shebang pointing to a helper executable (`#!/usr/bin/env xarexec_fuse`)
- A helper, `xarexec_fuse`, that knows how to read the XAR file, mount it if necessary, and execute the Python (or Lua or …) script inside
- A FUSE filesystem, `squashfuse_ll`, that is responsible for making the squashfs file look like a normal directory of files (and, by using FUSE, XARs don’t require root to run and can run on OS X).
- (optional) Since squashfs supports Zstandard compression (another Facebook open source offering), we can achieve far better compression ratios and faster decompression speed than zlib-based zip files can.

https://github.com/facebookincubator/xar

**Comment by chelseakomlo** [comment]
Thanks for opening this request- Nomad 0.9 will add support for pluggable externally-maintained drivers, so this is something that can be externally written and used by the community in later Nomad releases.
