### ISSUE TITLE
Provide vault tokens to nomad to use for docker-credential helper

### ISSUE THREAD

**Issue by Jeff-Hanson** [hashicorp/nomad#4576]
If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad 0.8.4

### Operating system and Environment details
Any

### Issue
Currently there is no way to provide a vault token that can be used by a docker-credential helper. The credential helper would use the vault token to retrieve private docker repo credentials to be used by nomad to satisfy a job with a docker image. One such possibility is to pass the token to the credential helper process via environment variable.

Based on mail list discussion [topic](https://groups.google.com/d/topic/nomad-tool/_AwfwuUbjPE/discussion) 

### Reproduction steps
Run my [fork](https://github.com/Jeff-Hanson/docker-credential-vault) of the docker-credential-vault project, make it available in the nomad client path. Configure the client docker.auth.helper to be "vault". Run a nomad job needing access to the private docker repo. The helper will fail 

### Job file (if appropriate)
Job file should include 
client {
    options  {
        "docker.auth.helper" = "vault"
    }
}

**Comment by donparapidos** [comment]
This would be great, any plans on implementing it?

**Comment by tgross** [comment]
See also https://github.com/hashicorp/nomad/issues/9740
