### ISSUE TITLE
secrets/vault_token created with execute permissions

### ISSUE THREAD

**Issue by dbresson** [hashicorp/nomad#4578]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
Ubuntu

### Issue
When using the vault integration, a file is dropped in secrets/vault_token. For no good reason I can imagine, this file is mode 0755.

### Reproduction steps
Use the vault integration and check the permissions of secrets/vault_token.

**Comment by schmichael** [comment]
This is a bug! It has been fixed in the client refactor feature branch that will land for v0.9: https://github.com/hashicorp/nomad/blob/r-arv2/client/allocrunnerv2/taskrunner/vault_hook.go#L338
