### ISSUE TITLE
Please provide bash-completion(s)

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4585]

**Comment by chelseakomlo** [comment]
Nomad provides CLI autocompletion: see https://www.nomadproject.io/docs/commands/index.html#autocomplete

Please re-open this ticket if this isn't what you had in mind or if there are other use cases that aren't captured.

**Comment by onlyjob** [comment]
This is odd and unusual way to install autocompletion... Is there a way to get it on build-time for distro-friendly installation?

**Comment by onlyjob** [comment]
This is a very confusing feature... When `nomad -autocomplete-install` runs as `root` it is completely silent and no new files appear neither in `/etc/bash_completion.d` nor in `/usr/share/bash-completion/completions`.   

When run as user it throws an error:
~~~~
Error executing CLI: 1 error occurred:

* open /home/user/.config/fish/completions/nomad.fish: no such file or directory
~~~~

Apparently it injects `complete -C /usr/bin/nomad nomad` into `.bashrc` which is a wrong way to install completion.

P.S. I can't re-open this issue... Could you do it for me please?
