### ISSUE TITLE
Nomad migration/drain issue

### ISSUE THREAD

**Issue by xmackex** [hashicorp/nomad#4589]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Operating system and Environment details
CentOS Linux release 7.5.1804 (Core)

### Issue

I've faced an issue with node draining and `migration` stanza.

It seems that Nomad does not respect `min_healthy_time` option.

Here are details:
- 2 nomad jobs with `count = 2`
    ```hcl
    job "job-1/2" {
      region      = "us"
      datacenters = ["us-west-1"]

      type = "service"

      update {
        max_parallel     = 1
        min_healthy_time = "15s"
        healthy_deadline = "1m"
        auto_revert      = true
        canary           = 2
        stagger          = "30s"
      }

      // reschedule {
      //   delay          = "10s"
      //   delay_function = "constant"
      //   unlimited      = true
      // }

      migrate {
        max_parallel     = 1
        health_check     = "checks"
        min_healthy_time = "90s"
        healthy_deadline = "15m"
      }

      group "main" {
        count = 2
    ```

- 2 nomad client nodes, all allocations are on node `A`
- nomad drain node A
    ```
    $ nomad node drain -yes -enable e1070221
    2018-08-17T01:41:58+08:00: Ctrl-C to stop monitoring: will not cancel the node drain
    2018-08-17T01:41:58+08:00: Node "e1070221-311a-a368-34b1-27f9fcfd85a6" drain strategy set
    2018-08-17T01:42:02+08:00: Alloc "9719300c-b318-ffaa-86c0-799f6d422f87" marked for migration
    2018-08-17T01:43:10+08:00: Alloc "03ecfe09-4ca6-262f-d67c-920a01b74026" status running -> complete
    2018-08-17T01:43:10+08:00: Alloc "44620e64-8c08-17af-625d-1cafb2807e0b" status running -> complete
    2018-08-17T01:43:10+08:00: Alloc "9719300c-b318-ffaa-86c0-799f6d422f87" status running -> complete
    2018-08-17T01:44:49+08:00: Node "e1070221-311a-a368-34b1-27f9fcfd85a6" has marked all allocations for migration
    2018-08-17T01:44:50+08:00: Alloc "3b67e705-9a6f-4648-0c5d-614ed25eb023" marked for migration
    2018-08-17T01:44:52+08:00: Alloc "3b67e705-9a6f-4648-0c5d-614ed25eb023" draining
    2018-08-17T01:45:58+08:00: Alloc "3b67e705-9a6f-4648-0c5d-614ed25eb023" status running -> complete
    2018-08-17T01:45:58+08:00: All allocations on node "e1070221-311a-a368-34b1-27f9fcfd85a6" have stopped.
    ```

Here are some details on first 3 allocations:
```
03ecfe09	08/17 01:43:08	job-A.main[0]	 complete	job-A / main	168	
44620e64	08/17 01:43:08	job-B.main[0]	 complete	job-B / main	320	
9719300c	08/17 01:43:09	job-B.main[1]	 complete	job-B / main	320	
```

So 3 allocaions of 4 are transitioned to state `complete` instead of executing migration one by one. As a result we got all backend dissapeared from the balancer during migration.

I've tried to set lower `max_parallel`, raised `count`, and when `count > 3`, we have one allocation aliva during migration, but several of them are migrated ated at the same time. Jobs have almost identical config. 

So I wonder am I missing something in config, misunderstood migration/drain process or there is a possible bug?

**Comment by dadgar** [comment]
@xmackex Hey it looks like some of those allocations are from separate jobs? There is no coordination between jobs. Would you mind giving the output of curling the /v1/job/<job-name>/allocations endpoint. Also if you have server logs that are in debug mode, those would be great to see as well.

**Comment by dadgar** [comment]
@xmackex Can you post a set of reproduction steps with the jobs you use.

**Comment by dadgar** [comment]
Looking at the logs you gave it looks well behaved:
```

2018/08/16 19:09:47.875099 [DEBUG] sched: <Eval "c067459d-3948-ee10-e702-32edc6d5a038" JobID: "job-A" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 1)
Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 1) (ignore 1) (canary 0)


2018/08/16 19:12:36.035231 [DEBUG] sched: <Eval "8c398cd1-3667-0845-b48f-a87d8a54e084" JobID: "job-B" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 1)
Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 1) (ignore 1) (canary 0)


2018/08/16 19:12:39.437827 [DEBUG] sched: <Eval "c1a17545-b91e-70d0-5bf0-789ac8eb62d9" JobID: "job-B" Namespace: "default">: Total changes: (place 0) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 2) (canary 0)
```
We can see that it took 3 minutes to migrate two which is right about your 90 second healthy time

**Comment by dadgar** [comment]
@xmackex I would clear out the cluster of those jobs, set the debug level of the servers to trace and start over. If you share the allocs, server logs and the output that is incorrect that would be the most useful.

**Comment by xmackex** [comment]
@dadgar sorry for late reply

I cleared all cluster jobs, created 2 new jobs which use plain nginx image.
Unfortunately I see same issue. Issue happened with job-B.
```
Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.956842 [DEBUG] sched: <Eval "17d1dd23-f6e6-c9c1-4eaf-841525a94f43" JobID: "job-A" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 1)
Aug 17 05:08:31 nomad-server nomad[28927]: Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 1) (ignore 1) (canary 0)
Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.960318 [DEBUG] sched: <Eval "17d1dd23-f6e6-c9c1-4eaf-841525a94f43" JobID: "job-A" Namespace: "default">: setting status to complete
Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.962506 [DEBUG] worker: updated evaluation <Eval "17d1dd23-f6e6-c9c1-4eaf-841525a94f43" JobID: "job-A" Namespace: "default">

Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.963224 [DEBUG] sched: <Eval "c5c21f6d-1cd1-f8bc-5a75-37504ce5f53c" JobID: "job-B" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 1)
Aug 17 05:08:31 nomad-server nomad[28927]: Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 1) (ignore 1) (canary 0)
Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.970417 [DEBUG] sched: <Eval "c5c21f6d-1cd1-f8bc-5a75-37504ce5f53c" JobID: "job-B" Namespace: "default">: setting status to complete
Aug 17 05:08:31 nomad-server nomad[28927]: 2018/08/17 05:08:31.972298 [DEBUG] worker: updated evaluation <Eval "c5c21f6d-1cd1-f8bc-5a75-37504ce5f53c" JobID: "job-B" Namespace: "default">

Aug 17 05:08:32 nomad-server nomad[28927]: 2018/08/17 05:08:32.963051 [DEBUG] sched: <Eval "f8fa2441-ff69-cafd-9f8b-6b1d0b9e3734" JobID: "job-B" Namespace: "default">: Total changes: (place 1) (destructive 0) (inplace 0) (stop 1)
Aug 17 05:08:32 nomad-server nomad[28927]: Desired Changes for "main": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 1) (ignore 1) (canary 0)
Aug 17 05:08:32 nomad-server nomad[28927]: 2018/08/17 05:08:32.965938 [DEBUG] sched: <Eval "f8fa2441-ff69-cafd-9f8b-6b1d0b9e3734" JobID: "job-B" Namespace: "default">: setting status to complete
Aug 17 05:08:32 nomad-server nomad[28927]: 2018/08/17 05:08:32.968280 [DEBUG] worker: updated evaluation <Eval "f8fa2441-ff69-cafd-9f8b-6b1d0b9e3734" JobID: "job-B" Namespace: "default">
```

As I understand from the log second evaluations of `job-B` migration started in 1 second after first one, despite `min_healthy_time`

[jobs.zip](https://github.com/hashicorp/nomad/files/2296097/jobs.zip)
[nomad_debug.log](https://github.com/hashicorp/nomad/files/2296084/nomad_debug.log)

**Comment by xmackex** [comment]
@dadgar 
same setup, 2 nodes, 2 jobs, count=2
I set default migrate policy for all jobs.

And the main issue that I face is that 2 allocations of the same job (but random if reproduce several times) are migrated at one time

Allocations:
```
4d0b78da  57111bff  job-A-group    1        run      running   4m1s ago    2m30s ago
80490e04  57111bff  job-A-group    1        run      running   4m2s ago    2m29s ago
686e5822  57111bff  job-B-group     2        run      running   2m30s ago   1m10s ago
5dff6172  57111bff  job-B-group     2        run      running   4m2s ago    2m31s ago
```

Drain monitor:
```
2018-08-21T17:59:24Z: Monitoring node "57111bff-16aa-fb66-ea13-cd488008ff06": Ctrl-C to detach monitoring
2018-08-21T17:59:25Z: Alloc "4d0b78da-43a2-d2aa-a61b-713399a291d9" marked for migration
2018-08-21T17:59:25Z: Alloc "5dff6172-b526-d1b9-fb32-7b6bba769eaa" marked for migration
2018-08-21T17:59:25Z: Alloc "4d0b78da-43a2-d2aa-a61b-713399a291d9" draining
2018-08-21T17:59:25Z: Alloc "5dff6172-b526-d1b9-fb32-7b6bba769eaa" draining
2018-08-21T17:59:26Z: Alloc "80490e04-9fe6-9f93-32c8-1774244cc4a9" marked for migration
2018-08-21T17:59:26Z: Alloc "80490e04-9fe6-9f93-32c8-1774244cc4a9" draining
2018-08-21T18:00:33Z: Alloc "4d0b78da-43a2-d2aa-a61b-713399a291d9" status running -> complete
2018-08-21T18:00:33Z: Alloc "5dff6172-b526-d1b9-fb32-7b6bba769eaa" status running -> complete
2018-08-21T18:00:34Z: Alloc "80490e04-9fe6-9f93-32c8-1774244cc4a9" status running -> complete
2018-08-21T18:00:49Z: Node "57111bff-16aa-fb66-ea13-cd488008ff06" has marked all allocations for migration
2018-08-21T18:00:49Z: Alloc "686e5822-e86e-a913-bfa2-1d97ac69261e" marked for migration
2018-08-21T18:00:49Z: Alloc "686e5822-e86e-a913-bfa2-1d97ac69261e" draining
2018-08-21T18:01:58Z: Alloc "686e5822-e86e-a913-bfa2-1d97ac69261e" status running -> complete
2018-08-21T18:01:58Z: All allocations on node "57111bff-16aa-fb66-ea13-cd488008ff06" have stopped.
```

As I can see here allocations that belong to same job became `status running -> complete` despite default `min_healthy_time`
```
2018-08-21T18:00:33Z: Alloc "4d0b78da-43a2-d2aa-a61b-713399a291d9" status running -> complete
2018-08-21T18:00:34Z: Alloc "80490e04-9fe6-9f93-32c8-1774244cc4a9" status running -> complete
```

Same behaviour I can see with
```
  migrate {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "90s"
    healthy_deadline = "15m"
  }
```

**Comment by schmichael** [comment]
Hi @xmackex, I'm going to take a crack at this one. I have a 2 client 1 server v0.8.4 cluster (with Consul 1.2.2) and have tried to reproduce your job as closely as possible: https://gist.github.com/schmichael/911b288f6e2af3a970771874ae960b48

However when draining a node with both allocs on it, it appears to properly honor the 90s min healthy time:


```
...
2018-08-22T00:36:58Z: Node "2259224e-e2d1-9f19-a859-4afcb780dd08" drain strategy set
2018-08-22T00:36:59Z: Alloc "567f9c6e-7472-a50e-f871-bd85bdbba2c3" marked for migration
2018-08-22T00:36:59Z: Alloc "567f9c6e-7472-a50e-f871-bd85bdbba2c3" draining
2018-08-22T00:38:04Z: Alloc "567f9c6e-7472-a50e-f871-bd85bdbba2c3" status running -> complete
<< ~90s wait >>
2018-08-22T00:39:36Z: Alloc "fc97b9c5-56e6-0944-f284-7cd8c0519a55" marked for migration
...
```

I'm just running 3 Vagrant VMs in a pretty standard configuration. Can you think of any particular difference in my environment that I may have missed that could be related?

Is this consistently a problem or should I just retry a few times (I've tried a couple)?

Would you be able to test with a version that has additional logging? (client and server would probably need to updated)

Sorry you've reliably hit this bug! I'd love to get to the bottom of it!

**Comment by xmackex** [comment]
Hi @schmichael 
Here is what I have:

* Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
* Consul v1.2.2
All servers are on AWS

Nomad:

* 1 server
* 2 clients:
    * `770642f0  us-west-1  client-1  dev    false  eligible     ready   0`
    * `04b803d2  us-west-1  client-2  dev    true   ineligible   ready   1`

How do I reproduce:

1. Restart nomad server (debug log)
2. `export NODE='04b803d2' && nomad node drain -yes -no-deadline -detach -enable ${NODE} && nomad node drain -monitor ${NODE} && sleep 5 && nomad node drain -yes  -disable ${NODE}`
3. Wait till it it drained and few mins more (issue don't happen)
4. `export NODE='770642f0' && nomad node drain -yes -no-deadline -detach -enable ${NODE} && nomad node drain -monitor ${NODE} && sleep 5 && nomad node drain -yes  -disable ${NODE}`
5. Wait till it it drained and few mins more (issue don't happen) 
6. `export NODE='04b803d2' && nomad node drain -yes -no-deadline -detach -enable ${NODE} && nomad node drain -monitor ${NODE} && sleep 5 && nomad node drain -yes  -disable ${NODE}`
7. Issue happens

Note, issue is nnot reproduced on step 2 and 4. It is reproduced on step 6
So after placing all allocs on the node and draining it for second time issue happens

I've attached allocations before drain, jobs, drain monitor output, server log (log level TRACE)
[out.zip](https://github.com/hashicorp/nomad/files/2308857/out.zip)

**Comment by xmackex** [comment]
@schmichael could you please share your vagrant files so I could try reproduce issue on that env?

**Comment by schmichael** [comment]
@xmackex I used `nomad-server01` and `nomad-client0{1,2}` from the root Vagrant file. It's sadly a bit of a pain to setup.

Also I want to assure you I have forgotten about this issue! Hoping to get back to it next week.
