### ISSUE TITLE
[question] Deploy AspNetCore on Windows

### ISSUE THREAD

**Issue by carl-thomas** [hashicorp/nomad#4610]
I am trying to deploy an AspNetCore website/api on Windows using Nomad. My job runs and downloads the artifact .zip, unpacks it and copies it to the `/local` directory. Then my `raw_exec` command runs to run the app. In the command line I would usually run `dotnet MyApplication.dll` in the root of the directory where my application sits. 

However when I run this using the `raw_exec` it fails with `Exit Code: 2147516545` which means nothing to me. I cannot find any logs either to tell me what has happened.

My job spec...
```
job "job1" {
	datacenters = ["dc1"]
	type = "service"
	group "sample" {
		count = 1
		task "api" {
			driver = "raw_exec"
			artifact {
				source = "https://example.com/Archive.zip"
			}
			config {
				command = "dotnet"
				args = ["./MyApplication.dll"]
			}
		}
	}
}
```

Has anyone deployed a AspNetCore application or know how to run this command.

Thanks

**Comment by dadgar** [comment]
@carl-thomas Can you paste the output of `nomad logs -stderr <alloc-id>` and `nomad logs <alloc-id>` and `nomad alloc status <alloc-id>`?

**Comment by carl-thomas** [comment]
Any ideas anyone?

**Comment by shantanugadgil** [comment]
Just my thoughts: the error seems to indicate that the dotnet.exe could not get the MyApplication.dll in the "current" directory.

Would it be possible to wrap the startup cmd in a batch script which emit variables and such like the "environment" and the output of the current directory.

**Comment by carl-thomas** [comment]
I now have this working. I used 
```
config {
    command = "dotnet"
    args = ["local/MyApplication.dll"]
}
```

**Comment by shoryavj** [comment]
try args = ["c", "local/MyApplication.dll"]
