### ISSUE TITLE
rkt: support for "--working-dir" option

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4624]
Please add support for rkt's `--working-dir` option.

See #4583 for discussion why not use generic `rkt_options` instead.

**Comment by cricket007** [comment]
#6478

**Comment by schmichael** [comment]
Closing since rkt has been deprecated in Nomad and by upstream. If you still want to maintain rkt support in Nomad please file issues in the new repository: https://github.com/hashicorp/nomad-driver-rkt
