### ISSUE TITLE
rkt: support for "--user" option

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4625]
Please implement support for rkt's `--user` option.

See #4583 for discussion why not use generic `rkt_options` instead.

**Comment by schmichael** [comment]
[`user`](https://www.nomadproject.io/docs/job-specification/task.html#user) is supported by all drivers (except QEMU). The rkt driver also supports setting the group, but it was undocumented. I've opened a PR for fixing the docs: #4627

**Comment by onlyjob** [comment]
Thanks.
