### ISSUE TITLE
Nomad for a rails application

### ISSUE THREAD

**Issue by vikramjadon921995** [hashicorp/nomad#4626]
**I have the following requirements:**
1. I have a rails application with some API endpoints
2. I want to start a task (rake task) on a separate server everytime an API is called. So that multiple tasks are running parallely in separate server.
3. All these tasks return data to main server.
4. I am using AWS 

How can I use nomad for above mentioned requirements ?
Do I have to use docker ?

**Comment by tantra35** [comment]
You may read folow blog post https://www.hashicorp.com/blog/replacing-queues-with-nomad-dispatch

but i think that nomad not well suited for this case, and it is best use for this 2 queue. One for dispatch task to workers and sencond which will be handled by server, where workers will send they response

**Comment by preetapan** [comment]
Closing this as its not a feature request/bug. Feel free to continue the discussion on our mailing list.
