### ISSUE TITLE
Volume Driver NFS

### ISSUE THREAD

**Issue by elasti-ronenc** [hashicorp/nomad#4630]
[question]
Is there is a way to use nfs persistence volume  and add volume_driver = nfs ?
[https://www.nomadproject.io/docs/drivers/docker.html#mounts](url)

**Comment by minhdanh** [comment]
@preetapan Hi, nomad 0.9 is already out for a while but persistence volume still not supported yet, right? When can I expect this to be available?

**Comment by endocrimes** [comment]
@minhdanh We're in the process of designing and implementing support for the Container Storage Interface, which provides a few different options for NFS. - I'd watch #5378 for more info. We're also shipping support for Host Volumes, that may give you ways to expose NFS mounts to users in some cases already.

**Comment by minhdanh** [comment]
@endocrimes Thank you. I'm so excited CSI is to be supported by Nomad.
