### ISSUE TITLE
job name tagging in telemetry should be less specific for periodic jobs (should not include `/periodic-1235...` info)

### ISSUE THREAD

**Issue by margueritepd** [hashicorp/nomad#4646]
### Nomad version
0.8.4

### Operating system and Environment details
Ubuntu 16.04

### Issue
I'm trying to use Nomad telemetry, eg `nomad.client.allocs.running`, in datadog. I would like to monitor that my periodic job successfully runs on an ongoing basis. According to the docs, this metric is tagged with the job-name, which should in theory allow me to filter the metric by the name of my job and see job runs over time. However, in practice, the job tag includes the periodic run ID (for lack of a better term) (eg `job:my-periodic-job/periodic-123456789`). In datadog, I am not able to add a wildcard after the `/`. This very specific tagging makes it impossible to view runs for this job over time.

Additionally, according to [datadog best practice](https://docs.datadoghq.com/tagging/#tags-best-practices), tags shouldn't originate from unbounded sources such as epoch timestamp. I'm keeping my fingers crossed that I don't get a stern email from them in the future!

### Reproduction steps
Run a periodic job that runs every minute, observe the `job` tag of the statsd metrics emitted for `nomad.client.allocs.running`.

**Comment by Miserlou** [comment]
Related: https://github.com/hashicorp/nomad/issues/4422

**Comment by burdandrei** [comment]
sorted here: https://github.com/hashicorp/nomad/pull/4392

**Comment by endocrimes** [comment]
Looks like this was fixed in #4392, closing now
