### ISSUE TITLE
Nomad client configuration with driver "raw_exec" is not working

### ISSUE THREAD

**Issue by suyash1983** [hashicorp/nomad#465]
I am using Nomad (v-0.2.0) and with following client configuration I found this issue:
```
==> Error loading configuration from nomad.d/client1.hcl: At 12:8: expected: IDENT | STRING | ASSIGN | LBRACE got: PERIOD
```

Here is my client configuration file:
```
$ cat nomad.d/client.hcl 
log_level = "DEBUG"
data_dir = "/tmp/client1"
datacenter = "dcxenon"

# Enable raw_exec driver
options = {
	driver.raw_exec.enable = "1"
}

client {
	enabled = true
	servers = ["127.0.0.1:4647"]
}

ports {
	http = 5656
}
```

**Comment by cbednarski** [comment]
@suyash1983 Thanks for opening an issue. Can you try adding quotes around `driver.raw_exec.enable` to look like `"driver.raw_exec.enable"`?

Also, the offset 12:8 seems off. Did you remove any lines from your config when you posted it? If not we may need to fix the offset.

**Comment by dadgar** [comment]
Hey @suyash1983 You need to put the options inside the client block as the options only apply to the client! Hope you enjoy Nomad 0.2

**Comment by suyash1983** [comment]
As per @dadgar suggestion, I moved option to client block and then restart the client agent but It doesn't work.

Then as suggested by @cbednarski, quote the ``driver.raw_exec.enable`` as ``"driver.raw_exec.enable"`` then finally It works.

I was configuring my client agent as per following documents. Please update it.
- Driver Document hosted by [github](https://github.com/hashicorp/nomad/blob/master/website/source/docs/drivers/raw_exec.html.md)
- Driver Document by [nomadproject](https://nomadproject.io/docs/drivers/raw_exec.html#driver_raw_exec)

**Comment by barthoda** [comment]
Thanks, this seems to work to enable raw_exec.
