### ISSUE TITLE
set Consul service meta from Nomad service definition

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#4652]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Operating system and Environment details
CentOS 7.5+, Ubuntu 14.04.5+

### Issue
Using these as reference:
https://www.consul.io/docs/agent/services.html
https://www.nomadproject.io/docs/job-specification/service.html

How can I set the Consul service metadata ("meta") from Nomad's service definition?
As I can gather it doesn't seem to be doable for now.

My final use case is to propagate info like the AWS region, availability zone, machine type, etc. into the service definition. 
A Consul Template based job (running on a separate machine) will then use this information to do some other things.

Regards,
Shantanu

**Comment by jeteon** [comment]
What would be nice is if the _job_, _group_ and _task_ level meta would be merged and then sent to Consul when setting up the service entry. From the Consul end of things it looks like the API already supports setting the meta key: 
https://github.com/hashicorp/consul/blob/eddcf228ea1a0b90030db3c820d469ff5b8106a9/api/agent.go#L119-L134.

so it could be added here: 
https://github.com/hashicorp/nomad/blob/07bfc856cf765f7720edbe0e4d6b46aa588dd1cf/command/agent/consul/client.go#L563-L569.

I would expect that the `meta` keys are already aggregated on the task but I'm not yet sure. Technically, it doesn't seem too difficult to implement this. There's probably a design issue I'm overlooking though.

**Comment by chenjpu** [comment]
Is there any plan or progress?

**Comment by shoenig** [comment]
Looks like this was implemented in https://github.com/hashicorp/nomad/pull/6193 
(with a similar request in https://github.com/hashicorp/nomad/issues/4300)

> What would be nice is if the job, group and task level meta would be merged and then sent to Consul when setting up the service entry.

@jeteon Although I don't think there's any _technical_ reason this couldn't be implemented, it would at this point be a significant backwards incompatible change. Instead, you might be able to realize a similar effect by making use of HCL2 features.

**Comment by shantanugadgil** [comment]
Sorry for the delay, I had been trying to remember why I had originally opened that request. 🤭 

Thanks, this seems to work as expected ... when I specify the following `meta` block inside the `service` stanza.

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {

    task "sleep" {
      driver = "raw_exec"

      config {
        command = "/bin/sleep"
        args = ["600"]
      }

      service {
        meta {
          region = "${node.region}"
          dc     = "${node.datacenter}"
        }
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}

```
