### ISSUE TITLE
make release not working on master

### ISSUE THREAD

**Issue by hbasappa** [hashicorp/nomad#4664]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

### Operating system and Environment details
on Vagrant supplied in nomad folder
### Issue

vagrant@linux:/opt/gopath/src/github.com/hashicorp/nomad$ make release
==> Cleaning build artifacts...
==> Building pkg/linux_386/nomad with tags ui release...
# github.com/hashicorp/nomad/command/agent
command/agent/bindata_assetfs.go:29:2: imported and not used: "io/ioutil"
command/agent/bindata_assetfs.go:31:2: imported and not used: "path/filepath"
command/agent/bindata_assetfs.go:32:2: imported and not used: "strings"
command/agent/bindata_assetfs.go:35:2: imported and not used: "github.com/hashicorp/nomad/vendor/github.com/elazarl/go-bindata-assetfs" as assetfs
command/agent/http.go:197:102: undefined: assetFS
GNUmakefile:71: recipe for target 'pkg/linux_386/nomad' failed
make: *** [pkg/linux_386/nomad] Error 2

### Reproduction steps
git clone nomad master and make release

**Comment by joshuaclausen** [comment]
I get the same thing from the vagrant vm.  Still looking for a workaround, but figured I'd post.
Windows 10
vagrant installed
cloned latest from master branch

vagrant up
vagrant ssh
make release

vagrant@linux:/opt/gopath/src/github.com/hashicorp/nomad$ make release
==> Cleaning build artifacts...
==> Building pkg/linux_386/nomad with tags ui release...
# github.com/hashicorp/nomad/command/agent
command/agent/bindata_assetfs.go:29:2: imported and not used: "io/ioutil"
command/agent/bindata_assetfs.go:31:2: imported and not used: "path/filepath"
command/agent/bindata_assetfs.go:32:2: imported and not used: "strings"
command/agent/bindata_assetfs.go:35:2: imported and not used: "github.com/hashicorp/nomad/vendor/github.com/elazarl/go-bindata-assetfs" as assetfs
command/agent/http.go:198:102: undefined: assetFS
GNUmakefile:71: recipe for target 'pkg/linux_386/nomad' failed
make: *** [pkg/linux_386/nomad] Error 2

**Comment by joshuaclausen** [comment]
It's related to building the UI, though that may be obvious if you've already explored this.  I'm able to build the non-UI nomad client binaries, at least for Windows.

**Comment by dhv** [comment]
Was able to get it to build by restoring the command/agent/bindata_assetfs.go file from a previous commit: 

git checkout dbee1d7d051619e90a809c23cf7e55750900742a -- command/agent/bindata_assetfs.go

**Comment by dantoml** [comment]
Closing this because `master` now builds successfully - Sorry for the flux during the 0.9 dev cycle folks!
