### ISSUE TITLE
Seems that after leader fail, some agents may forgot about servers except leader, what leads this nodes to miss they heartbeats

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#4666]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Issue
We see this situation time to time, when one of nomad servers hung due hardware failure or network connectivity problems. At last time was follow situation due aws fail, one of nomad servers hung, and exactly this server was leader:

```
2018/09/06 10:40:03 [WARN] raft: Rejecting vote request from 172.29.4.194:4647 since we have a leader: 172.29.20.70:4647
2018/09/06 10:40:03 [WARN] raft: Heartbeat timeout from "172.29.20.70:4647" reached, starting election
```

By this logs lines we conclude that node with ip `172.29.20.70`, was leader, while aws autoscale begin shutdown failed node, and bring up new(this process took about 5-7 minutes), the remaining two elect new leader, but 2 nomad agents forgot about remaining server and still communicate only with failed leader, only after 15-20 seconds those agents see server list and begin send heartbeats to proper RPC server, but this time was enough for the nomad server(new leader) conclude that this agents miss they hearbeats TTL and begin reallocate all allocation placed on that agents. Follow logs demonstrate situation:

```
2018-09-06T10:41:00.460+0300 [DEBUG] plugin.nomad: 2018/09/06 10:41:00 [ERR] plugin: plugin server: accept unix /tmp/plugin320636499: use of closed network connection
2018/09/06 10:41:00 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin185990052: write: broken pipe
2018-09-06T10:41:00.461+0300 [DEBUG] plugin: plugin process exited: path=/opt/nomad/nomad_0.8.4/nomad
2018-09-06T10:41:00.459+0300 [DEBUG] plugin: plugin process exited: path=/opt/nomad/nomad_0.8.4/nomad
2018-09-06T10:41:00.459+0300 [DEBUG] plugin.nomad: 2018/09/06 10:41:00 [ERR] plugin: plugin server: accept unix /tmp/plugin622419670: use of closed network connection
2018/09/06 10:41:00.433332 [WARN] client: heartbeat missed (request took 15.898862ms). Heartbeat TTL was 13.446301173s and heartbeated after 26.197845989s
2018/09/06 10:41:00.416017 [ERR] client: heartbeating failed. Retrying in 1.473438241s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414357 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414170 [ERR] nomad: "Alloc.GetAllocs" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414207 [ERR] client: failed to query updated allocations: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414226 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414242 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.409838 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: dial tcp 172.29.20.70:4647: i/o timeout
2018/09/06 10:40:50.410347 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.409804 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: dial tcp 172.29.20.70:4647: i/o timeout
2018/09/06 10:40:50.410172 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.410185 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.410380 [ERR] client: heartbeating failed. Retrying in 1.847214154s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:34.229367 [WARN] client: failed to resolve token, using expired cached value: rpc error: EOF
2018/09/06 10:40:34.228986 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: EOF
2018/09/06 10:40:34 [ERR] yamux: keepalive failed: i/o deadline reached
2018/09/06 10:40:34.229006 [ERR] client: heartbeating failed. Retrying in 1.398842761s: failed to update status: rpc error: EOF
2018/09/06 10:40:34.229353 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: EOF
```

As you can see no any server rotation was made after each failed RPC(so we conclude that agent forgot about all server except `172.29.20.70`), as it must be done due code https://github.com/hashicorp/nomad/blob/master/client/rpc.go#L76

For now we think that potential reason could be due absolute setting new server list  in follow code https://github.com/hashicorp/nomad/blob/master/client/client.go#L1509

Our hypothesis is. Before fully hung, leader forget about another servers and provide this info to some nomad clients(this agents not lucky, and they made RPC request to this faulty server), after that nomad server fully hung and stop processing RPC requests, so unlucky clients have not any chance to communicate with healthy servers. But it is strange that consul discovery doesn't helps, and also strange that distance betwen follow erro records

```
2018/09/06 10:40:34.228986 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: EOF
``` 

and 

```
2018/09/06 10:40:50.410380 [ERR] client: heartbeating failed. Retrying in 1.847214154s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
```

is more than 15 seconds, but in theory this distance should be very small

**Comment by dadgar** [comment]
Can you share the server logs for `172.29.20.70` around the issue and more of the client logs.
Also can you share the client's config

**Comment by tantra35** [comment]
Here only this logs from `172.29.20.70` for that day

```
    2018/09/06 09:31:31 [INFO] raft: Snapshot to 535205 complete
    2018/09/06 09:31:28 [INFO] raft: Compacting logs from 516773 to 524965
    2018/09/06 09:31:28 [INFO] snapshot: reaping snapshot /var/lib/nomad/server/raft/snapshots/421-518807-1536043917836
    2018/09/06 09:31:28 [INFO] snapshot: Creating new snapshot at /var/lib/nomad/server/raft/snapshots/422-535205-1536215488580.tmp
    2018/09/06 09:31:28 [INFO] raft: Starting snapshot up to 535205
    2018/09/06 09:05:45 [ERR] yamux: keepalive failed: session shutdown
```

and absolutely silence at moment of crash. May be logs from server doesn't reach collector, but this is all we have, aws forcedly terminate that server and it volume is lost 

our client config is separate by files:

client.hcl
```
region = "atf01"
datacenter = "test"
data_dir = "/var/lib/nomad/"
bind_addr = "0.0.0.0" # the default
disable_update_check = true

enable_syslog = false
log_level = "WARN"

leave_on_terminate = false

client
{
  enabled = true
  max_kill_timeout = "10m"
  node_class = "dockerworker"

  options = {
    "docker.auth.config" = "/root/.docker/config.json"
    "driver.raw_exec.enable" = true
  }

  reserved
  {
    cpu = 100
    memory = 256
  }
}
```

acl.hcl
```
acl
{
  enabled = true
}
```

vault.hcl
```
vault {
  enabled = true
  address = "https://vault.service.consul:8200"
}
```

consul.hcl
```
consul
{
  token = "xxxxxxx-xxxxx-xxx-xxx-xxxxxxxxxxxx"
}
```

advertise.hcl
```
advertise
{
        http = "172.29.0.29"
        rpc = "172.29.0.29"
        serf = "172.29.0.29"
}
```

replicator.hcl
```
client
{
  meta
  {
    "replicator_worker_pool" = "dockerworker-t2"
  }
}
```

**Comment by tantra35** [comment]
@dadgar this situation may be reproduced if you hung nomad server by debugger in our case this is 100% reproducible (we do `dlv attach <nomad server pid>`) and it not depend what to hung leader or not

**Comment by tantra35** [comment]
I think that a reason of this is lock held by `consulDiscoveryImpl` which may hold it to very long time if some communication with nomad server hung

**Comment by tantra35** [comment]
@dadgar The problem was more complex than simply remove hearbeatLock from consulDiscovery, so we make PR to solve this https://github.com/hashicorp/nomad/pull/4678

The key idias is:

1. Prevent to triggerDiscovery if we have health servers(new server list must be geted in this case only from heartbeats)

2. Change logic of Setservers in Manager(client/servers/manager.go), it only changes servers is they list really changes, in other case client forgot about health of servers

After this changes we can't reproduce this issue on test stand

**Comment by AlexanderZagaevskiy** [comment]
It seems that we also have the issue. Probably it's been starting since we upgraded Nomad to v0.8.4. Due to the issue we have constantly restarting tasks on random clients when one of the server is shut-downed.
Is there any activity to fix it? It's a very serious problem for us.

**Comment by tantra35** [comment]
@AlexanderZagaevskiy as workaround you may increase `heartbeat_grace` parameter for example to 1m

**Comment by AlexanderZagaevskiy** [comment]
@tantra35 Our cluster is very demanding on fast fault detection, thus the solution with `heartbeat_grace` is not fit for us. Moreover PR #4688  didn't help.

Nevertheless, сlose look at the issue and @tantra35 's PR allowed to fix it.
Main problems are:
1. There is a bug with omitted datacenter of servers discovered via Consul. ( PR #4997 )
2. Yamux's sessions are kept alive longer than default heartbeat TTL (30s vs 10s). This causes to protracted RPC calls to failed server so that client missed his heartbeat check.
3. Servers list is shuffled after each successful node update and discovery via Consul. Hence client might call to the failed server more than once in a row and miss heartbeat check.

As a temporary solution, we decreased keep alive interval for yamux sessions, got servers list shuffled only for incoming list that differed from already known one and turned autorebalancing of nomad servers on.

**Comment by tantra35** [comment]
@AlexanderZagaevskiy i agree with your timing settings for yamux, but why you have so often times of non responsive servers? Do you have any telemetry?

**Comment by AlexanderZagaevskiy** [comment]
Our QA engineers just checked fault tolerance feature and turned servers off or unplugged network on purpose. One of test cases.
