### ISSUE TITLE
[feature request] capability to limit task count to '1'

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#4674]
### Nomad version
0.8.5

### Operating system and Environment details
CentOS 7.5+, Ubuntu 14.04+

### Issue
Somewhat related to https://github.com/hashicorp/nomad/issues/4334

I have a distributed (multi AWS region) monolithic app and want to use Nomad to launch all its components.
The app has grown over time and the new "features" of this app are services (horizontally scalable), but there are some components which are not true `services` and cannot have more that one of its instance running (they have unique identity).

For now, I create separate Nomad jobs for all the individual "monolithic" components.
(My execution driver is `docker`)

My use case is to be able to specify a **hard limit of 1** on these older components so that the operator cannot accidentally bump-up the task count.
(using Hashi-UI)

FWIW: I know I can indulge in tactics like creating specific "node class" machines and appropriate `cpu` and/or `memory` requirements to limit the number of launches, but I want to avoid this.

Hope you folks consider this.

Thanks and Regards,
Shantanu

**Comment by dadgar** [comment]
Hey Shantanu,

This is a something that can be accomplished in Nomad enterprise today either by using namespaces/quota or by using sentinel. This type of governance is something that will exist in the enterprise offering.

If that is something that is not an option to you I would consider using ACLs to limit the number of people who can change jobs. Thanks for your understanding!
