### ISSUE TITLE
[question] Edit nomad cron job schedule time

### ISSUE THREAD

**Issue by sashichotu4321** [hashicorp/nomad#4676]
[question] - Is it possible to edit an existing batch job cron using java?

**Comment by dadgar** [comment]
Yes, you can resubmit the job with an update cron specification. It will be applied for the next run.

**Comment by sashichotu4321** [comment]
Thanks Alex, I am actually a newbie, using this for first time, can you please help me in understanding, how to update the cron specification using java.
