### ISSUE TITLE
Custom drivers as external binaries

### ISSUE THREAD

**Issue by davidpelaez** [hashicorp/nomad#468]
I don't know how the custom drivers were originally designed. However in the spirit of unix philosophy of having a tool that does one thing very well we could have binaries as drivers. Ideally those binaries would be in a well known folder either as links of the files themselves and they would reply to several command passed as first argument and extra data comming from standard input. This would enable an interaction pattern for highly customized drivers to enrich cluster control.

The use case I'm thinking of is related to security, consider a `secured-docker` binary that is a docker socket middleware filtering execution requests to only run images that have been audited by a static code analysis tool. This could also enable transparent additions to append business needs into the custom driver like service discovery autoregister of the job process or notifications and hooks for chatops. 

My greatest interest is in the ability to enrich execution control with a very simple patterns. Please let me know if it's unclear what I suggest.

**Comment by dadgar** [comment]
Your suggestion was great and it is something we recognize. We plan on adding plugins for drivers similar to how Terraform implements them in a future release of Nomad.

**Comment by kaskavalci** [comment]
Hello @dadgar do you have a roadmap for releasing plugin for drivers?

**Comment by dadgar** [comment]
Hey @kaskavalci it is not something we are actively working on at the moment

**Comment by bfgoodrich** [comment]
Any news on development of this feature at all?

**Comment by dadgar** [comment]
Hey no development news but still on the roadmap

**Comment by capone212** [comment]
Interested on this a lot.

**Comment by vin047** [comment]
Thanks @dadgar for linking me here - looking forward to this feature. Any ETA?

**Comment by dadgar** [comment]
@vin047 It is planned for 0.9

**Comment by ketzacoatl** [comment]
@dadgar would this provide/allow for generic binaries/executables as drivers, or only binaries built with golang?

**Comment by dantoml** [comment]
0.9 beta is now available with support for custom external plugins for both drivers and devices. You can find the documentation for this https://www.nomadproject.io/docs/drivers/external/index.html, and an example implementation here: https://github.com/hashicorp/nomad-driver-lxc.

Thank you for your interest - We're excited to see what you build!
