### ISSUE TITLE
Per agent/node environment variables for all tasks scheduled on those nodes

### ISSUE THREAD

**Issue by markpapadakis** [hashicorp/nomad#4680]
Greetings,

We have those use cases where it would be very beneficial if we could specify a set of environment variables specific to agents/nodes, and for each new task scheduled on those agents/nodes, those node-specific environment variables would be set, in addition to whatever env.variables are configured in the job spec file.

For example, we have a cluster of application servers, and, say, 10 different nodes that can run those tasks. We may allocate on 1 or 5, or 10 at any given time, but whenever an application server allocation is created on a node, it needs to know its `application server id` which is specific to every node. Yes, we could just check the local hostname/IP4 Address or access it from some configuration file or whatever, but it would be more elegant if we could just be able to specify extra env.variables in the configuration of the nomad agent running on every one of those 10 nodes, each containing e.g `APPSERVER_NODE_ID`. 

This would also help with another use case where we use [TANK](https://github.com/markpapadakis) and we want applications consuming from a TANK topic to only to consume from specific partitions, again, specific to which node is running the application. We have other such use cases, but those should serve to illustrate what we are looking to accomplish.

I suppose this may be a bit of an unusual use-case, but if it could be considered for upcoming releases, that’d be great.

**Comment by jrasell** [comment]
@markpapadakis would using Nomad client meta values on nodes be what you're looking for - https://www.nomadproject.io/docs/configuration/client.html#meta

Within each job you can then consume these via the ${meta.<key>} interpolation method - https://www.nomadproject.io/docs/runtime/interpolation.html#node-variables-

**Comment by markpapadakis** [comment]
Thank you.  That seems perfect.
