### ISSUE TITLE
Fails to start a task with systemd.unified_cgroup_hierarchy=1 (cgroup2)

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4683]
Nomad v0.8.4 (client) fails to start a task with unified cgroup hierarchy:

    mountpoint for cgroup not found

~~~~
# grep cgroup /proc/mounts
cgroup /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
~~~~

Debian amd64 "testing" / systemd 237 / Linux 4.17.8 booted with `systemd.unified_cgroup_hierarchy=1`

P.S. Task is on _rkt_ which I can start manually. Unlike Docker, _rkt_ works with cgroupv2.

**Comment by jboero** [comment]
Yes this is an issue with both Docker and Nomad.  Fedora 31+ and newer Ubuntu affected.  Kernels 5.x

**Comment by tgross** [comment]
Unfortunately this is a long-standing problem with upstream Docker (ref https://github.com/opencontainers/runc/issues/2209). It looks like we put the `driver/rkt` tag on this issue which was backwards -- the `rkt` driver is deprecated and the issue impacts the `docker`, `exec`, and `java` task drivers. I'm going to re-tag this issue and move it onto our roadmap so we don't lose track of it again.

**Comment by m1keil** [comment]
I believe this is no longer an issue with Docker 20.10 and up.

**Comment by tgross** [comment]
We can definitely close this out, as we've upgraded the docker client quite a while back now and have done the work to make sure cgroups v2 works.
