### ISSUE TITLE
Unable to contact nomad agent  [Error querying job: Get http://127.0.0.1:4646/v1/jobs?prefix=nginx: dial tcp 127.0.0.1:4646: connect: connection refused]

### ISSUE THREAD

**Issue by nattvasan** [hashicorp/nomad#4690]
`[question]` I'm running nomad server agent with '-bind' parameter but still i'm getting error trying to get status of the job

### Nomad version
Nomad v0.8.5 

### Consul version
Consul v0.8.5

### Operating system and Environment details
Ubuntu 16.04.5 LTS \n \l

### Nomad Server logs (if appropriate)

:/etc/nomad.d# nomad job status nginx
Error querying job: Get http://127.0.0.1:4646/v1/jobs?prefix=nginx: dial tcp 127.0.0.1:4646: connect: connection refused

:/etc/nomad.d# nomad status
Error querying jobs: Get http://127.0.0.1:4646/v1/jobs: dial tcp 127.0.0.1:4646: connect: connection refused

However, the nomad node status is working 

:/etc/nomad.d# nomad node-status -address=http://xx.xx.xx.xx:4646
ID        DC   Name               Class   Drain  Eligibility  Status
647f61f9  dc1  xxxxx  <none>  false  eligible     ready

:/etc/nomad.d#  nomad server members -address=http://xx.xx.xx.xx:4646
Name    Address         Port  Status  Leader  Protocol  Build  Datacenter  Region
xxxxx1   xx.xx.xx.xx   4648  alive   true    2         0.8.5  dc1         global
xxxxx2 xx.xx.xx.xx  4648  alive   false   2         0.8.5  dc1         global

:/etc/nomad.d# nomad status -address=http://xx.xx.xx.xx:4646
ID     Type     Priority  Status  Submit Date
nginx  service  50        dead    2018-09-17T14:17:40Z

### Nomad configuration file

log_level = "DEBUG"
bind_addr= "xx.xx.xx.xx"
data_dir = "/var/nomad"
server {
  enabled = true
 bootstrap_expect = 2
server_join {
    retry_join = ["xx.xx.xx.xx:4648"]
  }
}

advertise{
  http = "xx.xx.xx.xx:4646"
  rpc = "xx.xx.xx.xx:4647"
  serf = "xx.xx.xx.xx:4648"
}
consul {
  address = "xx.xx.xx.xx:8500"

  server_service_name = "nomad"
  client_service_name = "nomad-client"
  auto_advertise = true
  server_auto_join = true
  client_auto_join = true
}

### Nomad agent command 

 nomad agent  -config=/etc/nomad.d/config.hcl -bind=xx.xx.xx.xx

**Comment by angrycub** [comment]
This would be expected behavior.  You can use the NOMAD_ADDR environment variable to avoid having to pass it with every command run.
