### ISSUE TITLE
Allocate same cgroup parent for all containers started by nomad client wrt docker

### ISSUE THREAD

**Issue by hbasappa** [hashicorp/nomad#4696]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
0.8.4

### Operating system and Environment details
centos 7

### Issue
docker support cgroupParent which can be used to potentassign same cgroupParent to all containers started by nomad client.Nomad does not support it.

https://github.com/hashicorp/nomad/pull/4662 is one way to address this.

**Comment by preetapan** [comment]
LEaving this issue open, see my comment in https://github.com/hashicorp/nomad/pull/4662. we'll take an updated PR against the docker driver plugin after the ongoing work on that is merged.

**Comment by joebeeson** [comment]
#4844 has been merged

**Comment by fredwangwang** [comment]
@preetapan is there any plan to add this feature? IMO nomad has the [reserved](https://www.nomadproject.io/docs/configuration/client#reserved-parameters) config, but it is not very useful. It only limits how much are reserved from being scheduled but not at all how much can be used post scheduling. Schedule a cpu hog with 10 Mhz CPU allocated (w/o hard limit) can easily take down all system level services (logging, ssh, etc) on the target node.

Assigning all nomad scheduled tasks to a constraint cgroup can be hugely beneficial to prevent nomad hosted job jeopardize the host stability.

**Comment by shoenig** [comment]
Setting a cgroup parent (as well as reserved.cores) has been possible since Nomad v1.1
