### ISSUE TITLE
Checking for Downloaded Image Takes A Long Time // Docker Context Size

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#4697]
We have to run about 3,000,000 dispatch jobs.

```
2018-09-19T16:29:45Z  Started         Task started by client
2018-09-19T16:29:31Z  Driver          Downloading image wkurt/dr_downloaders:latest
```

We're finding that the startup overhead for each job is a minimum of 15 seconds, because of this `Downloading image wkurt/dr_downloaders:latest` step. The image isn't actually being downloaded except for the first time, since the image is already in the local registry. So, this is 15 seconds being spent checking the existence of something we know is there, which means an overhead (3,000,000 x 15 seconds) = **1.4269406393 years** of compute time spent on this step.

I assume that under the hood, this is the result of creating a context and sending it to Docker. Locally, I'd mitigate this with a `dockerignore` file, but I have no idea how to do this, if it's possible at all, with Nomad.

Is there any chance that we can address this issue and save ourselves **literally a year of time**?

**Comment by nickethier** [comment]
Hello!

This latency is likely coming from docker checking the remote repository for the image. There is special handling around the `latest` tag. Nomad will always attempt to force pull the image if the image tag is `latest`. If you use any other tag Nomad will only pull the image if it's not present (or if you configure it to force pull in the job spec). 

Could you try to use a different image tag and see if we can't shave a few months off that :smiley:

**Comment by Miserlou** [comment]
This appears to mostly solve that facet of the problem, however, there is still a massive overhead in between time received and time started, ex:

```
Time                  Type        Description
2018-09-19T19:44:46Z  Terminated  Exit Code: 0
2018-09-19T19:41:51Z  Started     Task started by client
2018-09-19T19:40:48Z  Task Setup  Building Task Directory
2018-09-19T19:40:48Z  Received    Task received by client
```

This `Task Setup  Building Task Directory` appears to take about 45 second every single time across thousands of jobs, regardless of whether or not the image needs to be re-downloaded.

I don't know what this Building Task Directory step is doing, but a 45 second overhead is obviously unacceptable for our use case. 

What is happening here, and how can we reduce the time this needs to take? (Is this a resource-blocked allocation, and if so how can I tell if so and what the resource blocking is? The machine looks like it still has plenty of spare resources available.)

I'm just going to randomly choose some to show how long it takes in the real world:

```
2018-09-19T19:34:17Z  Started     Task started by client
2018-09-19T19:33:01Z  Task Setup  Building Task Directory
2018-09-19T19:33:01Z  Received    Task received by client
```
01:16

```
2018-09-19T19:34:07Z  Started     Task started by client
2018-09-19T19:32:59Z  Task Setup  Building Task Directory
2018-09-19T19:32:59Z  Received    Task received by client
```
01:08

```
2018-09-19T19:50:53Z  Started     Task started by client
2018-09-19T19:46:44Z  Task Setup  Building Task Directory
2018-09-19T19:46:44Z  Received    Task received by client
```
04:09

etc, growing over time.

**Comment by nickethier** [comment]
Hey @Miserlou 

Would you have a job spec you could share?

There are numerous things that happen between building the task dir and starting the task. Such as writing dispatch payload, fetching artifacts if configure, rendering templates etc. Also debug logs from a client thats experiencing this could be helpful.

**Comment by nickethier** [comment]
Sorry @Miserlou I realized I commented on the wrong issue of yours yesterday.

The logs help look at the timing inside the driver. If I understand your environment you have many jobs being started concurrently on a given client. I suspect this is contention in the docker daemon. I did some local testing to try and simulate this (hard to get the same results on my local machine vs your prod environment).

I dispatched a single job with the docker driver and found the time between building the task dir and starting the task (we'll call this setup latency) is near instant, less than a second. If I dispatch a few hundred of these jobs however that latency jumps to ~30s, at the same time the CPU load on the docker daemon spiked. I then did the same test with the raw exec driver and found no significant difference in in setup latency between a single dispatch and a few hundred concurrent dispatches.

I think the debug logs would really help shed some light as to whats going on here.

**Comment by Fuco1** [comment]
It's 2022 and we are seeing the same thing.  Server version 1.2.6, client 1.2.3.  Our setup has 430 clients each with 16 CPUs, so this is about 7k tasks running concurrently.  The total number of tasks is 15k.  It is a batch job with count = 15000.

The Task setup takes about a minute consistently across the clients/tasks.  

At some points it becomes so bad that the cluster is only using about 10% of the CPU capacity overall.

Are there some pointers to code so we can see what exactly happens?  We have some consul templates for example, some vault access etc.  But both vault and consul processes have plenty spare processing power.
