### ISSUE TITLE
Increase lineScanLimit in log rotation logic

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#4699]
This is a follow-up on #1048 and #4282

We have some applications that are logging quite long lines of JSON (up to 25KB) - and we see our files being split across files mid-line, which causes all kind of bad error and unreadable logs in Graylog.

I would like to have [lineScanLimit](https://github.com/hashicorp/nomad/pull/4282/files#diff-2589ff362b7178dc7ba8776ee549a4f8R29) increased from 16K to 25K - if it doesn't affect performance in any significant way.

I'll submit the change if its okay with the Nomad team

**Comment by preetapan** [comment]
@jippi we would take a PR for this for the 0.9 release if you want to get this in!

**Comment by jippi** [comment]
@preetapan thanks! I'll get it wrapped up today

**Comment by jippi** [comment]
PR open in https://github.com/hashicorp/nomad/pull/4765
