### ISSUE TITLE
Support docker run arg --tempfs

### ISSUE THREAD

**Issue by samart** [hashicorp/nomad#4714]
Please add support for the tempfs option in docker.  we are looking to use this as part of our secure container strategy.

@rcgenova

**Comment by onlyjob** [comment]
Could it be done by configuring Nomad clients to put `alloc` dir to _tmpfs_?

Arguably using _tmpfs_ is not too secure as it allows to overuse host's RAM.
How do you address that concern?

Besides _rkt_ is much more secure than Docker...

**Comment by samart** [comment]
You just need to pass the arg to docker engine.  Nomad has nothing to do except pass the arg, and should not care about this otherwise.  Just like it doesn’t care about most other docker engine Args it passes

**Comment by rcgenova** [comment]
@samart This will be in Nomad 0.9.

**Comment by jahentao** [comment]
It seems cannot pass `--env` args to noamd docker dirver

**Comment by schmichael** [comment]
This was added in Nomad 0.9:

- 1.0.1+ parameter - https://www.nomadproject.io/docs/drivers/docker#mount 
- 0.9.0-1.0.0 parameter - https://www.nomadproject.io/docs/drivers/docker#mounts
