### ISSUE TITLE
[question] How to have self-healing Nomad/Consul cluster

### ISSUE THREAD

**Issue by dbabits** [hashicorp/nomad#4733]
Nomad can restart failed tasks.
But is there a way for Nomad to restart a failed Nomad agent?
I know each member of a Consul cluster gets a message when one of agents fails, I assume so does Nomad.
I would like one of them to ssh to a host where and agent failed and restart it.
To avoid all agents racing to do this they should probably try and obtain a lock, and one would win and do it.
All in all, that sounds like a lot of code to write and a pretty generic requirement.
I wonder if Nomad or Consul cluster have that self-healing functionality.
Or, what do people suggest, how to monitor/restart failed agents?
Thank you.

**Comment by shantanugadgil** [comment]
I have Nomad and Consul configured as system services under 'systemd'

Some suggest to run Consul itself as a system service (host network mode)

My systemd jobs are configured in a sort of "always restart" mode (with a delay of 10 seconds between restarts, if it ever exits)

The only failure I have ever observed of startup itself is when Nomad's data directory becomes corrupt (the usual task bucket error)
(deleting the nomad data directory solves that problem)

**Comment by dbabits** [comment]
Thank you. I dont have syatemd though, no root access.

**Comment by dadgar** [comment]
@dbabits As @shantanugadgil suggested you should restart Nomad using systemd, upstart. This is a very common practice. 

If Nomad itself exits, you need something other than Nomad to detect and restart this as Nomad itself is no longer running.

**Comment by dbabits** [comment]
yes, but another Nomad or Consul or Serf is running, on another host.
And they get a message of hard exit of their peer(Serf does for sure, I
checked).
Could one of them not ssh to the host and restart the failed brother?

Why depend on external systems like systemd
