### ISSUE TITLE
Add a "go home" page to 404 page in Nomad UI

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#4737]
### Nomad version
Output from `nomad version`

Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details

```
vagrant@nomad:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

### Issue

It would be nice if Nomad had a "go home" link on it's 404 pages when it cannot find an allocation. I come up against this frequently when restarting my VM from scratch.

![https://cl.ly/9729433ea603/Image%202018-09-30%20at%201.46.07%20PM.png](https://cl.ly/9729433ea603/Image%202018-09-30%20at%201.46.07%20PM.png)

### Reproduction steps

1. Create an allocation via a deployment of any job
2. Save the link to the allocation in the ui
3. Clear out your nomad instance
4. Try to browse to the allocation again

**Comment by josegonzalez** [comment]
Thanks for that, @DingoEatingFuzz :) Small ui enhancements always make users happier :)

**Comment by DingoEatingFuzz** [comment]
I agree!
