### ISSUE TITLE
Small dispatch jobs with low priority prevent large high priority dispatch jobs from running

### ISSUE THREAD

**Issue by kurtwheeler** [hashicorp/nomad#4746]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details

Ubuntu 16.04 within AWS ecosystem

### Issue

Using Nomad as a job queue as suggested in this blog post: https://www.hashicorp.com/blog/replacing-queues-with-nomad-dispatch doesn't handle jobs of various sizes very well. Specifically, a queue with a lot of small, low priority dispatch jobs and any number of large, high priority dispatch jobs will only run small, low priority dispatch jobs until all of the small jobs finish and free up enough resources to finally handle a big job.

The issue comes down to how Nomad chooses to schedule a dispatch job. I've taken a quick look at the code and it seems that first Nomad decides how much space it has free on a node and filters out the jobs that won't fit. Then it ranks them by priority and chooses based off of that. I think this order should be reversed. First the priority should be considered AND THEN the space should be considered. If there's not space for the highest priority job then it should continue to wait, rather than filling what space is available with a small but lower priority job.

### Reproduction steps
Create two parameterized jobs, one with high priority and a high RAM requirement and another with low priority and a low RAM requirement. Queue up enough small jobs to saturate the cluster's RAM resources and then queue a large number of both jobs. What will happen is that as each small job finishes, it will be replaced by another small job until there are no more small jobs.

**Comment by dadgar** [comment]
Hey,

Nomad currently uses priority to decide the order in which jobs get access to the scheduler. It doesn't prevent low priority jobs from accessing resources if there are queued high priority jobs. This is not the approach Nomad will be taking to solve the problem. Instead we will be using pre-emption such that when the high priority job is examined by the scheduler, it will be able to evict low priority jobs from the cluster and run the higher priority job. This feature will be coming out in the 0.9.X time frame!

I will be closing this issue in favor of: https://github.com/hashicorp/nomad/issues/4306

**Comment by kurtwheeler** [comment]
Is there any chance that the behavior I described could be provided as an alternative via configuration? I can see the advantages of the pre-emption method for more persistent workloads, but for a batch based queue workload it seems to make much more sense to queue the work intelligently rather than interrupting jobs which may be close to completion.
