### ISSUE TITLE
dispatched job returned IDs but never "recorded" in server

### ISSUE THREAD

**Issue by nhi-vanye** [hashicorp/nomad#4751]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
0.8.3

### Operating system and Environment details

Linux (CoreOS)
Windows2016

### Issue

After calling `thisApp.scheduler.job.dispatch_job( "startir", meta=params )` dispatch job details are printed from our application 

```
        run = thisApp.scheduler.job.dispatch_job( "startir", meta=params )

        logging.info( 'Dispatch startir job DispatchedJobID={} EvalId={} JobCreateIndex={} Index={} {}'.format( run['DispatchedJobID'],run['EvalID'], run['JobCreateIndex'], run['Index'], str( params ) ) )
```

```
2018-09-28T05:05:57.117 INFO Dispatch startir job DispatchedJobID=startir/dispatch-1538111157-d337f6b6 EvalId=af3a66a3-88df-0f47-82eb-0ea7b4367747 JobCreateIndex=30791 Index=30792 XXX
```

But the job is never shown in the output of `nomad status` nor is it executed.

```
startir                           batch/parameterized  50        running  2018-09-24T17:34:54Z
stopir                           batch/parameterized  50        running  2018-09-24T17:34:54Z
```

### Reproduction steps

This is repeatable at a customer site, but other parameterized jobs targeted for the same agent node are executed before and afterwards in time - but this failure stalls the pipeline

No issues for the entire pipeline (~20jobs) on our own systems - this is job 4 in the pipeline

Not sure where to look for more info - nomad is a bit of a blackbox for us.

### Nomad Server logs (if appropriate)

Don't have them yet - trying into to obtain from customer.

**Comment by nhi-vanye** [comment]
Should have mentioned this is using Python SDK

**Comment by dadgar** [comment]
@nhi-vanye When you say repeatable you can easily trigger this behavior? Can you provide the logs and the output of `curl http://<nomad>/v1/jobs` and `curl http://<nomad>/v1/evaluations`

**Comment by nhi-vanye** [comment]
By repeatable - this job is scheduled on a regular basis (every hour) - From our application logs from the customer this is doing the same thing every dispatch cycle. I haven't been able to trigger the issue on our dev/test environment.

I don't have direct access to the customer system at this point (trying to get it) - I did previously capture the output from `nomad status` at the console - a snippet is included above for this parameterized job and the one alphabetically after it (I would have expected to see a job called `startir/dispatch-1538111157-d337f6b6` between the two

**Comment by nhi-vanye** [comment]
Hi @dadgar,

I've now got logs from the customer - including the results of /jobs and /evaluations.

Is there a good way to share them ? The full logs do include customer internal details/product details that I would want to redact before sharing them publicly.
