### ISSUE TITLE
HTTP nodes API - cannot unmarshal string into Go struct

### ISSUE THREAD

**Issue by psiwczak** [hashicorp/nomad#4760]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
0.8.4

### Operating system and Environment details
Ubuntu 18.04
### Issue
Trying to follow the guide on using Nomad HTTP API to drain a particular node:
https://www.nomadproject.io/api/nodes.html#drain-node

I receive the following error in response:
"json: cannot unmarshal string into Go struct field DrainSpec.Deadline of type time.Duration"

### Reproduction steps
Run the node drain curl example from documentation:
https://www.nomadproject.io/api/nodes.html#drain-node

**Comment by dadgar** [comment]
@psiwczak Hey thanks for reporting. I have fixed the example and it will hit the website next time we push: a027e5cbd4406d05d4e2ff68a73208edea06a5ee

The deadline field should be an integer not a string!
