### ISSUE TITLE
Nomad docker pull image issue

### ISSUE THREAD

**Issue by nattvasan** [hashicorp/nomad#4766]
I'm using ECR repository to pull images. 

### Nomad version
Nomad v0.8.5

### Operating system and Environment details
Redhat - Linux [Not using EC2 - I am using standalone VM]

### Issue
I'm using ECR repository to pull images. Unable to succeed.

### Reproduction steps

**Task config file:** 

config {
                                image = "xxx.dkr.ecr.us-west-2.amazonaws.com/xxx/xxx:latest"
                                auth {
                                    username = "user"
                                    password = password"
                                  }

**Nomad client file:**

 options {
        "docker.cleanup.image" = "false"
        "docker.auth.helper" = "ecr"
        "docker.auth.config" = "/root/.docker/config.json"
        "docker.privileged.enabled" = "true"
    }

**Docker config.json file:**

{
     "auths": {
          "xxxxxx01..vap.rr.com": {
               "auth": "xxxxxxxxxx",
               "email": null
          }
     }
     "credHelpers": {
      "xxxxxx.dkr.ecr.us-west-2.amazonaws.com": "ecr-login"
  },
  "credsStore": "secretservice"
}

### Nomad Server logs (if appropriate)

2018-10-08T18:30:55Z  Driver Failure  failed to initialize task "xxx" for alloc "ae6bc380-ba84-f1be-4eee-1019c50ffaff": Failed to pull `xxxxxx01..vap.rr.com/xxx/xxx:latest`: unauthorized: authentication required
2018-10-08T18:30:54Z  Driver          Downloading image xxxxxx01..vap.rr.com/xxx/xxx:latest

**Comment by dadgar** [comment]
@nattvasan You are using all three methods of authentication (user/pass, docker config file and the helper.

Do you expect your user/name password to work to pull that image? That gets first preference, followed by the config and then the auth.helper.

**Comment by dadgar** [comment]
@nattvasan Likely not as the username/password is only valid for 12 hours (https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) that is why it is recommended to use the credential helper (https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/)

So I would remove the auth from the job spec and also remove `"docker.auth.helper" = "ecr"` from the nomad config.

**Comment by nattvasan** [comment]
@dadgar I did the same what you suggested! Used docker.auth.config to pull images and it Worked like Charm !!! Thanks for the help ! Cheers!

**Comment by nattvasan** [comment]
@dadgar 
>>Likely not as the username/password is only valid for 12 hours
(https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) that is why it is recommended to use the credential helper (https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/)

As per your comment to use 'docker-credential-ecr-login', I used and installed it successfully. But Nomad is still failing to pull.

Logs:

Recent Events:
Time                  Type             Description
2018-10-11T10:18:19Z  Alloc Unhealthy  Unhealthy because of failed task
2018-10-11T10:18:19Z  Not Restarting   Error was unrecoverable
2018-10-11T10:18:19Z  Driver Failure   failed to initialize task "xxxx" for alloc "44395b24-95c3-7598-8758-e0ed2363a2e1": Failed to find docker auth for repo "xxxx.dkr.ecr.xxxx.amazonaws.com/xxx/xxxxx": exec: "docker-credential-ecr-login": executable file not found in $PATH

**My docker config file:**


{
    "credsStore": "ecr-login"
}

**Client config:**

    options {
        "docker.cleanup.image" = "false"
        "docker.auth.helper" = "ecr-login"
        #"docker.auth.config" = "/root/.docker/config.json"
        "docker.privileged.enabled" = "true"

    }
}

Please advise on the error.

Thank you.

**Comment by nattvasan** [comment]
Any update @dadgar , my setup in Nomad-consul is stalled due to this ECR pull issue

**Comment by nattvasan** [comment]
> @nattvasan Likely not as the username/password is only valid for 12 hours (https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) that is why it is recommended to use the credential helper (https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/)
> 
> So I would remove the auth from the job spec and also remove `"docker.auth.helper" = "ecr"` from the nomad config.

So Do I need to run that docker-credential-ecr-login script in my client machine as well ? Please confirm

@dadgar

**Comment by nattvasan** [comment]
Fixed the issue, completely !!!!!! Woohoo ! Nomad you beauty ! Thanks @dadgar

**Comment by dadgar** [comment]
@nattvasan Nice glad you figured it out! Would you mind saying what the fix was? May help others if the search 👍

**Comment by nattvasan** [comment]
@dadgar I was completely out of mind to configure the docker-aws-credentials on Master servers instead of Client machine... My bad! Lately i figured out and fixed the issue
