### ISSUE TITLE
Nomad will not run as a service in Windows

### ISSUE THREAD

**Issue by hvanvoorhis-ISP** [hashicorp/nomad#4774]
We need nomad to run as a service so we can select "Allow service to interact with desktop" as we are using some d3d(GPU) APIs. If we run with task manger we cant do this (to my knowledge) without having a foreground cmd window.  

When we try to run nomad as a windows service it gets timeout error 1053. 

### Nomad version
0.8.5

### Operating system and Environment details
Windows Server 2012 R2
### Issue
Cant run nomad as a windows service as you can with Consul
### Reproduction steps
sc config "Nomad" binPath="c:\nomad\nomad.exe agent -config=c:\nomad\nomad.hcl"

**Comment by angrycub** [comment]
Nomad does not currently provide the interface necessary to be added as a Windows service.  You can use NSSM or srvany  as a compatibility layer between the Nomad executable and the Windows Service Manager.
