### ISSUE TITLE
Nomad should pass  job, alloc and task ids as docker labels

### ISSUE THREAD

**Issue by samart** [hashicorp/nomad#4781]
It woudl be very useful if nomad passed jobId, alloc Id, and taskid as docker labels on container.create().

This will allow us to correlate - via monitoring tools, (Sysdig/Prometheus/etc) and security tooling - running containers with nomad Runtime metadata.  Its very common for these tools to pull in docker labels as means for identification and other categorization purposes.

@rcgenova

**Comment by jippi** [comment]
[You can just pass them in](https://www.nomadproject.io/docs/drivers/docker.html#labels)

```hcl
job "demo" {
  group "demo" {
    task "demo" {
      config {
        labels {
          key = value
        }
    }
  }  
}
```

**Comment by samart** [comment]
Where would the values come from at runtime?   Are there variables i can use to set them?   (Let me look..)

**Comment by jippi** [comment]
you can reference any [environment](https://www.nomadproject.io/docs/runtime/environment.html) key using [interpolation](https://www.nomadproject.io/docs/runtime/interpolation.html)

**Comment by drarnold** [comment]
Hey @jippi ,

I was going to be using Docker Labels for our containers to autodiscover haproxy and would be putting it into the Nomad Definition.  I am curious how to handle each of the keys:
https://docs.datadoghq.com/integrations/haproxy/#containerized

**Comment by kshpytsya** [comment]
Absence of this feature prevents me from effectively using [cAdvisor](https://github.com/google/cadvisor) (with Prometheus), as we have same task names in different nomad jobs. I am even considering implementing an augmenting proxy that would rewrite Prometheus metrics obtained from cAdvisor adding Nomad job and group name based on the allocation id, which is included as a suffix in the `name` label (querying local Nomad agent to get allocation info). But of course, it would be much better to just have it properly implemented in Nomad itself. Modifying job descriptions as suggested in https://github.com/hashicorp/nomad/issues/4781#issuecomment-429646094 is highly impractical in our case.

**Comment by m1keil** [comment]
@kshpytsya you can expose these via cadvisor's `--docker_env_metadata_whitelist=""`

**Comment by sofixa** [comment]
Any news on this? It would be a very useful feature for log shipping agents ( like promtail) which can only read Docker labels.

**Comment by sofixa** [comment]
FYI i've created a PR adding those labels #9885

**Comment by tgross** [comment]
Forgot to close this one out when https://github.com/hashicorp/nomad/pull/9885 was merged. Marked for 1.1.0
