### ISSUE TITLE
Health check fails after x minutes when running two clients

### ISSUE THREAD

**Issue by nadilas** [hashicorp/nomad#4782]
### Nomad version

`0.8.6`

### Operating system and Environment details

Windows Server 2012

### Issue

Running 3 servers and one client instance is working fine. Consul registered services are discoverable and the system is up and running. 
As soon as a second client is started, the allocations are doubled up and consul starts failing the services, which leads to nomad restarting the services. 
The issue is that the health checks are failed after 3-5 x interval. One of the services is registered with 30s interval and 5s timeout as health check. This service will show up critical at first, then it goes to passing. After a few minutes the health check fails and the service is restarted. After shutting down the second nomad client, the situation normalizes and all services return to a healthy state. 
Both clients run on the same server.

**Comment by preetapan** [comment]
@nadilas can you post a job spec file as well? 

Also, the initial status of the check can be set https://www.nomadproject.io/docs/job-specification/service.html#initial_status

**Comment by nadilas** [comment]
@preetapan I can, but I don't think it makes any difference. There is not one specific job which gets restarted, over the course of a 15 minutes run, all scheduled jobs get interrupted and rescheduled.

Initial status is not the problem, as the services do come up as healthy, but after a few seconds, minutes they fail. Whether it's the consul side or the nomad side, I cannot begin to speculate. Fact is the two nomad clients run on the same server instance.

Here's an example job:
```
job "zipkin" {
  datacenters = [
    "dc1"]
  type = "service"

  group "zipkin" {
    count = 1
	ephemeral_disk {
		size = "110"
	}
    restart {
      attempts = 3
      delay    = "10s"
      interval = "10m"
      mode     = "fail"
    }

    task "zipkin" {
      driver = "java"

      artifact {
        source = "http://.../zipkin-server-2.7.1-exec.jar"
        options {
          checksum = "md5:6265CA25C7CC0068FA5C45FFC1C32332"
        }
      }

      config {
        jar_path = "local/zipkin-server-2.7.1-exec.jar"
      }

      resources {
        memory = 150
        network {
          mbits = 1
          port "http" {
            static = 9411
          }
        }
      }

      service {
        name = "zipkin"
        port = "http"
        tags = [
        "global",
        "trace",
        "server"]
        check {
          name = "alive-zipkin"
          type     = "tcp"
          port     = "http"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

**Comment by dantoml** [comment]
@nadilas Could you try running nomad clients on independent servers? - Multiple clients talking to the same consul agent can lead to some unfortunate behaviour in some cases, where they both try to write over each other.
