### ISSUE TITLE
Welcome Screen Bug

### ISSUE THREAD

**Issue by jontowles** [hashicorp/nomad#4798]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
1.1.4

### Operating system and Environment details
MacOS High Sierra and Mojave

### Issue
Welcome screen comes back after every reboot even when using the DontShowWelcome key

**Comment by DingoEatingFuzz** [comment]
Hey @jontowles, Nomad has no welcome screen (in the UI or otherwise), plus there is no version 1.1.4.

I'm gonna close this, but please feel free to clarify your issue!
