### ISSUE TITLE
Failure to lookup Vault periodic token 

### ISSUE THREAD

**Issue by aedades** [hashicorp/nomad#4806]
### Nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details
Linux ip-10-7-19-134 4.9.91-40.57.amzn1.x86_64 #1 SMP Tue Apr 3 17:32:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Issue
An allocation using a template to set vault secrets fails with permission errors (to `auth/token/lookup-self`), though we're using a root token.

Nomad config:
```
# Server:
  "vault": {
    "enabled": true,
    "address": "<vault address>",
    "token": "<root token>"
  },

# Client:
  "vault": {
    "enabled": true,
    "address": "<vault address>"
  },
```

Logs from hashi-ui:
```
vault: server error deriving vault token: Nomad Server failed to establish connections to Vault: failed to lookup Vault periodic token: Error making API request. URL: POST https://<vault endpoint>/v1/auth/token/lookup Code: 403. Errors: * permission denied
```

### Reproduction steps
We have a development environment where an allocation using a template succeeds, while the failure is occurring in a production environment.  Both environments run the same versions of nomad with the above configuration and point to the same vault (0.11.1).

### Nomad Client logs (if appropriate)
```
    2018/10/18 21:37:21.495980 [ERR] client.vault: failed to derive token for allocation "b4e1d738-f817-880a-21a0-27118ab8e7b5" and tasks [<task name>]: Nomad Server failed to establish connections to Vault: failed to lookup Vault periodic token: Error making API request.
URL: POST https://<vault endpoint>/v1/auth/token/lookup
URL: POST https://<vault endpoint>/v1/auth/token/lookup
    2018/10/18 21:37:21.496021 [DEBUG] client: killing task <task name> for alloc "b4e1d738-f817-880a-21a0-27118ab8e7b5": vault: server error deriving vault token: Nomad Server failed to establish connections to Vault: failed to lookup Vault periodic token: Error making API request.
```

**Comment by dadgar** [comment]
@aedades The error is saying that the Nomad server is not able to verify its own Vault token. Either its token is expired or invalid. I would do a `vault token lookup` on the token you have given your Vault server and ensure it is valid.

**Comment by dadgar** [comment]
Also I may be misreading what you said, and if so feel free to ignore, but as a best practice you should to have your QA and production environments be talking to the same Vault.

**Comment by aedades** [comment]
Hello @dadgar , hmm the token actually is valid:
```
$ vault token lookup <token>
Key                 Value
---                 -----
accessor            <accessor>
creation_time       1509387216
creation_ttl        0s
display_name        token-Nomad
entity_id           n/a
expire_time         <nil>
explicit_max_ttl    0s
id                  <id>
issue_time          2017-10-30T18:13:36.47176917Z
meta                <nil>
num_uses            0
orphan              true
path                auth/token/create
policies            [root]
renewable           false
ttl                 0s
```

**Comment by dadgar** [comment]
@aedades Are you configuring Nomad to talk to Vault via consul dns? Do you have multiple instances of Vault? The line of questioning is, is Nomad talking to a different Vault instance than you think.

Further you should look at the logs outputted by Nomad at startup. It should emit why some information about why it thinks the token is invalid.

**Comment by aedades** [comment]
@dadgar Not ideal, but we only have the one vault cluster to connect to.

Prior to the above errors, we do see nomad successfully connect to vault:
```
    2018/10/18 21:38:14.523420 [DEBUG] client.fingerprint_manager: built-in fingerprints: [arch cgroup consul cpu host memory network nomad signal storage vault env_aws env_gce]
    2018/10/18 21:38:14.641701 [INFO] fingerprint.vault: Vault is available
    2018/10/18 21:38:14.641925 [DEBUG] client.fingerprint_manager: fingerprinting vault every 15s
    2018/10/18 21:38:14.648084 [DEBUG] client.fingerprint_manager: detected fingerprints [arch cgroup cpu host network nomad signal storage vault env_aws]
```

**Comment by aedades** [comment]
@dadgar Thanks for the support, deriving a new root token for nomad worked:
```
# prior to restart with new token
    2018/10/19 17:32:44.013577 [ERR] client.vault: failed to derive token for allocation "eaf9111b-3fda-19a5-a646-a2ebc26f3228" and tasks [<task name>]: Nomad Server failed to establish connections to Vault: failed to lookup Vault periodic token: Error making API request.
URL: POST https://<vault endpoint>/v1/auth/token/lookup
URL: POST https://<vault endpoint>/v1/auth/token/lookup
    2018/10/19 17:32:44.013612 [DEBUG] client: killing task <task name> for alloc "eaf9111b-3fda-19a5-a646-a2ebc26f3228": vault: server error deriving vault token: Nomad Server failed to establish connections to Vault: failed to lookup Vault periodic token: Error making API request.
URL: POST https://<vault endpoint>/v1/auth/token/lookup

# after restart
    2018/10/19 18:06:40.662988 [DEBUG] (runner) final config: <config json>
    2018/10/19 18:06:40.663539 [DEBUG] (watcher) adding vault.read(<secret path>)
    2018/10/19 18:06:40.745431 [WARN] (view) vault.read(<secret path>): no secret exists at <secret path> (retry attempt 1 after "250ms")
```
Ignoring the failure because the secret doesn't exist yet, deriving the token succeeded.  Is it expected that using the same token for different nomad clusters would not work?  (I'm sure this practice is frowned upon, we will be moving to different tokens using the token role based integration in the future.)

**Comment by dadgar** [comment]
@aedades There is nothing stopping that from working. It definitely is not a best practice though. I am not sure what caused your issue but it was likely an issue with the token. The error that is being generated is when Nomad tries to confirm the token is valid with Vault and we retry periodically: https://github.com/hashicorp/nomad/blob/master/nomad/vault.go#L412-L438

So for some reason, the token didn't allow looking up itself:https://github.com/hashicorp/nomad/blob/v0.8.6/nomad/vault.go#L591-L596

I am going to close this out and I am glad you got it figured out!
