### ISSUE TITLE
 How to connect 2 services on different machines?

### ISSUE THREAD

**Issue by viniciusxyz** [hashicorp/nomad#4812]
How can I connect 2 services running on different machines? I have several applications connected to a database and I need the execution of each part of this set can be done in a distributed and independent way, how can I do this without depending on the DNS of the consul? (I prefer not to DNS because it is not 100% stable in Windows we had several problems with it)

I am using Consul 1.3.0 and Nomad 0.8.6 in Windows environment

**Comment by dadgar** [comment]
@viniciusxyz Most people will use DNS. You have two other options. 

1. Use the template stanza to render a config that has the addresses of the services you would like to talk to and then read that when setting up your app. You can also render to env vars:
https://www.nomadproject.io/docs/job-specification/template.html
https://github.com/hashicorp/consul-template

2. Use the Nomad API to read the allocations for that job and determine the addresses they were assigned:
https://www.nomadproject.io/api/jobs.html#list-job-allocations
https://www.nomadproject.io/api/allocations.html#read-allocation

Hope that helps, but highly recommend using DNS.
