### ISSUE TITLE
Doc errror or bug? boolean in env stanza

### ISSUE THREAD

**Issue by sportebois** [hashicorp/nomad#4820]
I would be happy to try to contribute and help trying to submit a fix PR, but I don't know which assumption is true:
- option A: the observed behavior is the expected one, but the documentation is misleading
- option B: the documentation correctly describes the expected result, and the value gets incorrectly cast to an integer at some point

### Nomad version
Output from `nomad version`

`Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)`

### Operating system and Environment details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch

$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

### Issue

After reading the [coercion part of the env stanza doc](https://www.nomadproject.io/docs/job-specification/env.html#coercion), I assumed that the values were stored as string, and therefore the samples provided were synonyms:

```hcl
env {
  key = "true"
  key = true

  "key" = true
 #...
}
```

Preceded with
> these values will be stored as their string representation. No type information is preserved.

But it appears that, at least with this version, `true` without quote is cast to an integerm and I get `1` in my environment variable.

I'm not sure if this is the expected behavior (in such case it doesn't match the documentation) or a bug

### Reproduction steps

Use the unquoted `true`value in the `env` stanza and read the value in the running task. 
According to the docs, I'd expect this value to be stored and exposed as string. But the string  `1` is read in the environment variable produced.

`true` gives `"1"` in the runtime env var, whereas `"true"` is kept as a string and provided as-is to the runtime. 

e.g. 
```
env {
  TRUTHY_BOOL   = true  # will be 1
  TRUTHY_STRING = "true"  # is correct
}
```

### Nomad Client logs

```
$ nomad logs  86cb1d3a docker | grep TRUTHY
TRUTHY_BOOL=1
TRUTHY_STRING=true

$ nomad logs  86cb1d3a exec | grep TRUTHY  
TRUTHY_BOOL=1
TRUTHY_STRING=true

```

### Job file 

Here's a sample job (with both docker and exec drivers, I was curious to see if it could make a difference)
```hcl
job "repro-env-bool-parsing" {
  datacenters = ["us-east-1a", "us-east-1b", "us-east-1c"]
  type        = "batch"

  group "repro-env-bool-parsing" {
    task "docker" {
      driver = "docker"

      config {
        image = "busybox"
        args  = ["sh", "-c", "env"]
      }

      env {
        TRUTHY_BOOL   = true
        TRUTHY_STRING = "true"
      }

      resources {
        cpu    = 20
        memory = 10

        network {
          mbits = 1
        }
      }
    }

    task "exec" {
      driver = "exec"

      config {
        command = "env"
      }

      env {
        TRUTHY_BOOL   = true
        TRUTHY_STRING = "true"
      }

      resources {
        cpu    = 20
        memory = 10

        network {
          mbits = 1
        }
      }
    }
  }
}

```

**Comment by preetapan** [comment]
@sportebois this is a documentation being somewhat misleading. We use [mapstructure|https://github.com/mitchellh/mapstructure] which handles turning `true` to "1", the string representation of a boolean. Feel free to submit a PR to correct the doc.

**Comment by sportebois** [comment]
Perfect, I assumed so but hadn't found the time (traveling...) so far to dive into the code to double check this. 
I'm going to open a PR to try to make this less misleading for future readers later today (or at least later this week). Thanks for the feedback!

**Comment by sportebois** [comment]
Closing this, since both concerns were addressed:
- @preetapan clarified the origin of the confusion (thanks a lot!)
- hopefully, #4882 will make this less misleading in the future
