### ISSUE TITLE
[feature?] Nomad for orchestrating service daemons like httpd, ntpd on a linux machine

### ISSUE THREAD

**Issue by techduderavi** [hashicorp/nomad#4824]
**Nomad Version**
0.8.6

**Operating System**
Ubuntu 16.04

**Issue**

Does nomad offer ability to orchestrate services on a linux machine like httpd, ntpd. I can see that exec/raw driver can be used to run binaries. Assuming this can be implemented using exe/raw binaries what is a proper way of doing this. How are you handling services on Linux with Nomad and  monitor/orchestrate for failure and recovery using Nomad. There are obviously other products to accomplish this, but has anyone used Nomad in a to address this type of scenarios? If you did, please post an example configuration.

**Comment by preetapan** [comment]
@techduderavi you can use Nomad system jobs for this https://www.nomadproject.io/docs/schedulers.html#system

In the future, please ask questions in our google groups mailing list - https://groups.google.com/forum/#!forum/nomad-tool, it helps keep github issues for bug reporting only, and you can also search previous posts for system jobs.

**Comment by techduderavi** [comment]
@preetapan Thank you and agreed 👍 !
