### ISSUE TITLE
syslog: Long stdout lines support

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#4834]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Issue
nomad writes docker's stdout/stderr to a file by 16kb chanks at a line.
It causes wrong order in a case when logs are aggregated from several servers.
And the worse thing: it breaks our JSON-formatted logs

### Reproduction steps
- add nomad job with docker
- log long line (>16k symbols) to stdout from the container
- the line will be divided into chunks and written to `alloc/uid/alloc/logs/task.stdout.0`

### Expected results
Lines are written to a log file as it is. Or at least line sizes can be configured in client's config.

**Comment by jippi** [comment]
might be fixed in #4699
