### ISSUE TITLE
[question]actual_cpu units

### ISSUE THREAD

**Issue by jessica-ritter** [hashicorp/nomad#4840]
Nomad Version 
Operating System Ubuntu 16.04
Issue
Looked through the [API Allocations](docs(https://www.nomadproject.io/api/allocations.html),) as well as the metrics docs and other API docs, could not find unit mention for CPU in sample responses. Can only see CPU units listed (https://www.nomadproject.io/guides/operating-a-job/resource-utilization.html) to my knowledge. Currently I am working on providing over/under allocated resource stats by allocation but in order to give accurate information the unit is quite necessary. Would love to see this listed in documentation of the sample responses.

**Comment by preetapan** [comment]
@jessica-ritter the unit is Mhz and mentioned here https://www.nomadproject.io/docs/job-specification/resources.html#resources-parameters 

Will accept a doc update PR from you if you want to add it to more places, can see how this is hard to find.

**Comment by jessica-ritter** [comment]
Hi Preetapan, 

Thanks so much for responding. I think perhaps these links might help me explain a bit more. I noticed that here:
```{
  "ResourceUsage": {
    "CpuStats": {
      "Measured": [
        "Throttled Periods",
        "Throttled Time",
        "Percent"
      ],
      "Percent": 0.14159538847117795,
      "SystemMode": 0,
      "ThrottledPeriods": 0,
      "ThrottledTime": 0,
      "TotalTicks": 3.256693934837093,
      "UserMode": 0
    },``` 
percentage is mentioned but percentage of what? Here is the direct link to the doc: https://www.nomadproject.io/api/client.html#read-allocation-statistics

As this will help me correctly pull statistics of cpu usage for our teams services.
Thanks!
