### ISSUE TITLE
[Feature] add date and time into job's log lines

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#4849]
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Issue
Currently job's log lines are written to alloc/logs/task.stdout(stderr) as is it.
But the problem is that we're losing information about the time when a log line was written.
There're only two options to save date at the moment:
- use custom logger for docker jobs
- modify applications in order to add time in log lines

And at least for us, it would be extremely helpful if nomad will prepend log lines with time and date.

**Comment by preetapan** [comment]
@pznamensky Thanks for reporting this. The upcoming 0.9 release introduces a plugin architecture for logging, and we are planning to build on top of that to support logging plugins (#1469). That will enable operators being able to use a custom plugin that adds timestamps/supports different ways of formatting the log output etc.
