### ISSUE TITLE
LXC CPU metrics are wrongly calculated

### ISSUE THREAD

**Issue by ThomasObenaus** [hashicorp/nomad#4853]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
AWS Amazon Linux 2

### Issue
It seams that the nomad_client_allocs_cpu_xx metrics are not calculated correctly.
When I compare the metrics:
`nomad_client_allocs_cpu_total_percent`, `nomad_client_allocs_cpu_user` and `nomad_client_allocs_cpu_system` the first one looks fine (reaching 100% at max) the last two are exceeding 30000% which is a bit weird from my perspective.

Looking at the implementation [in lxc.go](https://github.com/hashicorp/nomad/blob/master/client/driver/lxc.go#L493) all three user, system and total are treated the same. All are assumed to be CPU times and are based on that assumption put into the method Percent() which then calculates the percentage based on cpu time.
*But* looking at the [lxc-driver implementation](https://github.com/lxc/go-lxc/blob/v2/container.go#L1126) the user and system stat is no cpu time but the cpu cycles scaled by USER_HZ instead.

This leads to the result that these metrics are misleading or/and hard to understand.

**Comment by ThomasObenaus** [comment]
Hey @dadgar do you have an update regarding this issue? Am I just wrong/ did not understood how these metrics are meant or is this a bug?

**Comment by atillamas** [comment]
On nomad 0.8.6 i'm seeing nomad_client_allocs_cpu_total_percent with values way above 100. On a system with 16 cores it tops out just under 1600, matching the output of `docker stats`, i guess it should be divded by the number of cores to be correct?
