### ISSUE TITLE
RPM with systemd integration?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/nomad#4902]
Awesome to see HashiCorp providing an open source, distributed scheduler! Could we get RPM's uploaded, preferably with systemd integration, to make nomad servers easier to setup?

**Comment by shantanugadgil** [comment]
The .service files are already part of the source tree.
I see the value of having OS packages, but the alternative os just as easy.

I used to use FPM to create a HashiPack (Consul and Nomad) but soon realized that just a bunch of quick commands suffice;

wget/s3 cp from a known source
create the config file and service file
start the services.

Using an image based deployment, this just meant packing everything besides the config inside the image and generating the config on machine creation (userdata and such)

**Comment by preetapan** [comment]
@rkettelerij thanks for jumping on the reply to this one. 

@mcandre At this time we do not intend to provide RPMs due to the reasons linked in that comment above^
