### ISSUE TITLE
runing multiple instances (count) allocate same dynamic port

### ISSUE THREAD

**Issue by sielaq** [hashicorp/nomad#492]
Hi there,

try nomad init example with `count = 2` 
(where no example was running before) 
you will see error like this:
```
failed to create endpoint smooth-128e27d4-919d-e019-f953-e226113172e0 on network bridge: Bind for 127.0.0.1:47006 failed: port is already allocated
```

Same if you want to scale up (from 1 to 4) it will spawn only one new container, and 2 gonna be failed.
seems like it allocate dynamic port for every instances.

**Comment by sielaq** [comment]
definitely in v0.2.0, I'm trying now against master...

**Comment by sielaq** [comment]
and the same in master

**Comment by dadgar** [comment]
@sielaq: Thanks for reporting. Confirmed it as a bug and we are working on a fix now

**Comment by ashmckenzie** [comment]
Can confirm a nomad binary built from master solves this problem :+1:
