### ISSUE TITLE
[feature] add Amazon's Firecracker as a task driver

### ISSUE THREAD

**Issue by rushmorem** [hashicorp/nomad#4923]
https://firecracker-microvm.github.io:

> Firecracker is an open source virtualization technology that is purpose-built for creating and managing secure, multi-tenant containers and functions-based services

I've just discovered this gem from Amazon. I think having first class support for it in Nomad would be awesome!

**Comment by yuriy-yarosh** [comment]
I'm working on it.

**Comment by yuriy-yarosh** [comment]
Finished firecracker client for golang, it took more time to get a linux box with KVM :dango: than actually implementing it.

@dadgar what do you think about adding direct containerd support for nomad ? 
Docker driver by design became a bit obsolete...

**Comment by c4milo** [comment]
@yuriy-yarosh, that's a great idea. A lot of drivers will be abstracted out by containerd and Nomad's code would simplify as a result.

**Comment by bithavoc** [comment]
what's the official report for the driver @yuriy-yarosh, I found https://github.com/bitsnap/nomad-firecracker but no code.

**Comment by yuriy-yarosh** [comment]
@bithavoc I've finished it, but have been quite displeased with the firecracker design and some lack of features, so after a bit of tinkering I'm not considering firecracker a viable solution.
I had started my own firecracker-ish KVM runner, but have no free time and resources to finish it right now - priorities had shifted a bit.

Surely, I could publish this driver, but it's not something I could recommend people to use.

**Comment by pires** [comment]
@yuri-yarosh can you please share what you came up with?

And maybe your thoughts on what parts of the design displease you, what features you're lacking, and so on. A _blog_ post would be sweet 🙏 

Last but not least, where did you find that Firecracker will be redesigned and rewritten?

**Comment by yuriy-yarosh** [comment]
> @yuri-yarosh can you please share what you came up with?

Will do, but not not right now.

> A _blog_ post would be sweet 🙏

No one will pay me for that one, and I'm not a person who'll blindly contribute to a flawed product, so why bother ?

My current engagements are much more meaningful and at least can shake up the market a bit.

> maybe your thoughts on what parts of the design displease you

 * Absence of proper kernel build toolchain
 * Inconsistent API's
 * Security issues
 * Overall Immaturity which contradicts with existing PR material

> where did you find that Firecracker will be redesigned and rewritten?

Well, it's a no brainer if you'll search through and review the [existing codebase](https://github.com/firecracker-microvm/firecracker/search?q=refactor&type=Issues).

I'd say that it's worth waiting few months 'till things settle down a bit, because right now Firecracker is too WIP.

**Comment by yuriy-yarosh** [comment]
Yup, it looks like Firecracker became something decent, at last.
So, it's time to release the driver...

**Comment by cneira** [comment]
I just created a task driver for firecracker [firecracker-task-driver](https://github.com/cneira/firecracker-task-driver), I'll submit it to the community drivers next week. Let me know if more features are needed, my use case is pretty simple at this point.

**Comment by tgross** [comment]
We've got that driver in our [community driver](https://www.nomadproject.io/docs/drivers/external/firecracker-task-driver) docs. Going to close out this issue. Thanks!
