### ISSUE TITLE
Nomad failed to kill raw exec task.

### ISSUE THREAD

**Issue by Laboltus** [hashicorp/nomad#4935]
### Nomad version
Nomad v0.8.4

### Operating system and Environment details
Ububntu 16.04

### Issue
We launch java application with raw exec driver. Most of the time all works ok but sometimes the app hangs and can't be killed with SIGTERM. I can kill it with SIGKILL manually, but nomad can't.

### Nomad Client logs (if appropriate)
Nov 29 11:22:34 ip-172-31-2-79 nomad[1633]:     2018/11/29 11:22:34.570860 [ERR] client: failed to kill task 'backend-task' for alloc "d851de8b-02be-4d95-d009-a9ef02d48382"
. Retrying in 5s: executor Exit failed: 1 error(s) occurred:
Nov 29 11:22:34 ip-172-31-2-79 nomad[1633]: * 1 error(s) occurred:
Nov 29 11:22:34 ip-172-31-2-79 nomad[1633]: * failed to delete the cgroup directories: Failed to remove paths: map[freezer:/sys/fs/cgroup/freezer/nomad/f00a3551-37c6-3dc1-6c10-bcd0c
389cb35]
Nov 29 11:22:44 ip-172-31-2-79 nomad[1633]:     2018/11/29 11:22:44.738784 [ERR] client: failed to kill task 'backend-task' for alloc "d851de8b-02be-4d95-d009-a9ef02d48382"
. Retrying in 20s: executor Exit failed: 1 error(s) occurred:
Nov 29 11:22:44 ip-172-31-2-79 nomad[1633]: * 1 error(s) occurred:
Nov 29 11:22:44 ip-172-31-2-79 nomad[1633]: * failed to delete the cgroup directories: Failed to remove paths: map[freezer:/sys/fs/cgroup/freezer/nomad/f00a3551-37c6-3dc1-6c10-bcd0c
389cb35]
Nov 29 11:23:09 ip-172-31-2-79 nomad[1633]:     2018/11/29 11:23:09.910790 [ERR] client: failed to kill task 'backend-task' for alloc "d851de8b-02be-4d95-d009-a9ef02d48382"
. Retrying in 1m20s: executor Exit failed: 1 error(s) occurred:
Nov 29 11:23:09 ip-172-31-2-79 nomad[1633]: * 1 error(s) occurred:
Nov 29 11:23:09 ip-172-31-2-79 nomad[1633]: * failed to delete the cgroup directories: Failed to remove paths: map[freezer:/sys/fs/cgroup/freezer/nomad/f00a3551-37c6-3dc1-6c10-bcd0c
389cb35]
Nov 29 11:24:35 ip-172-31-2-79 nomad[1633]:     2018/11/29 11:24:35.082575 [ERR] client: failed to kill task 'backend-task' for alloc "d851de8b-02be-4d95-d009-a9ef02d48382"
. Retrying in 2m0s: executor Exit failed: 1 error(s) occurred:
Nov 29 11:24:35 ip-172-31-2-79 nomad[1633]: * 1 error(s) occurred:
Nov 29 11:24:35 ip-172-31-2-79 nomad[1633]: * failed to delete the cgroup directories: Failed to remove paths: map[freezer:/sys/fs/cgroup/freezer/nomad/f00a3551-37c6-3dc1-6c10-bcd0c
389cb35]

**Comment by preetapan** [comment]
Source of the error is from this vendored library which we use when calling shutdown on the executor - https://github.com/hashicorp/nomad/blob/e9f3f2cfee9d729a8642344c4fa4ea70b2d49468/vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go#L394 

@Laboltus when this happens in your environment, does the directory mentioned in the error e.g `/sys/fs/cgroup/freezer/nomad/f00a3551-37c6-3dc1-6c10-bcd0c
389cb35` still exist on the file system?

**Comment by Laboltus** [comment]
Just got this error again and checked. Yes, the directory is exist until I do something like killall -9 java.
