### ISSUE TITLE
Conflict between docker network_mode and static port

### ISSUE THREAD

**Issue by ibayer** [hashicorp/nomad#4954]
Access to host loopback interface is needed from inside docker container in order to connect co-located docker container.

An example usecase would be to connecting pgadmin running in one container to postgres running in a second container.

It would be great to have working example for such at setup as similar situations come up frequently. 

Is **nomad consul connect** a better way to achieve this? Sadly the promised example is still missing from the docs:

_The example uses raw_exec for now just to show how it can be used locally but the Docker driver or any other driver could easily be used. The example will be updated to use the official Consul Docker image following release._  [0] 

### Nomad version
`consul --version Consul v1.4.0`
`nomad --version Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)`

### Operating system and Environment details
Ubuntu 18.04 server

### Issue

Using `network_mode = "host"` in the docker driver config causes the static ip
mapping to disappear.

### Reproduction steps

example job:

```
job "postgresql" {
  datacenters = ["dc1"]
  type = "service"
  group "postgres-group" {
    task "pgadmin" {
      env {
        PGADMIN_DEFAULT_EMAIL = "admin@domain.io"
        PGADMIN_DEFAULT_PASSWORD = "admin"
      }

      driver = "docker"
      config {
        image = "dpage/pgadmin4:3.5"
        port_map {
          http = 80
        }
        #network_mode = "host"
        volumes = [
        "/srv/pgadmin:/root/.pgadmin"
        ]
      }
      resources {
        network {
          port "http" {
            static = 5050
          }
        }
      }
      service {
        #name = "postgres"
        name = "pgadmin"
        address_mode = "driver"
        port = "http"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```
```
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                     NAMES
c54147a5777a        ab946f265e07        "/entrypoint.sh"    5 seconds ago       Up 3 seconds        443/tcp, 127.0.0.1:5050->80/tcp, 127.0.0.1:5050->80/udp   pgadmin-4e659a4f-cc2f-f435-f692-1857f6ceaa39
```

with `network_mode = "host"` commented 

```
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
72d83e43a55d        ab946f265e07        "/entrypoint.sh"    13 minutes ago      Up 13 minutes                           pgadmin-2561f455-2d0e-10d3-74c7-595ade79e14a
```
port mapping `443/tcp, 127.0.0.1:5050->80/tcp, 127.0.0.1:5050->80/udp` disappears. 

[0] https://www.consul.io/docs/connect/platform/nomad.html#accepting-connect-for-an-existing-service

https://github.com/hashicorp/nomad/issues/103

**Comment by ibayer** [comment]
https://github.com/hashicorp/nomad/issues/783#issuecomment-181365246 _You could also simplify the thing by using static ports + either exec driver or docker driver in host network mode to get the direct access to the underlying host network_ 

also make be belief what I'm trying here should work.

**Comment by ibayer** [comment]
Okay, this actually works but the ports are exposed on the host IP which is the expected docker behavior
for `network_mode = "host"` but a bad idea in general.

**Comment by preetapan** [comment]
@ibayer We have support for network namespaces slated for the next major release (after the upcoming 0.9 release) to allow containers sharing the same task group to be able to see each other.

**Comment by ibayer** [comment]
Glad to hear!
 I made this work but I had to jump through way too many hoops for such a standard problem.
