### ISSUE TITLE
Guard cross-region joining

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/nomad#496]
It would be helpful if we could guard against cross-region joining, where a client configured for "region1" attempts to join servers in "region2". We currently allow it, but Nomad internally can't support regions without datacenters so the logs will just fill up with warnings.

**Comment by dadgar** [comment]
When the client registers it sends its config.Region. The nomad server will then do forwarding of the RPC based on this. If the region doesn't exist an error is returned. So this base is covered.
