### ISSUE TITLE
[ui] Definition lists in web UI can be out of sync

### ISSUE THREAD

**Issue by PeteBoucher** [hashicorp/nomad#4968]
### Nomad version
1.0.0

### Operating system and Environment details
host: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-1013-aws x86_64)
client: Mac OSX 10.14.1 Mojave,
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Firefox 61.0.2 (64-bit)

### Issue
On the job->service page, definition lists (like Meta Properties) become out of sync (title: value out of alignment) of one or more values is empty. See screenshot:
![image](https://user-images.githubusercontent.com/1378853/49582622-ef78ae00-f955-11e8-8928-445f78bd604f.png)

### Reproduction steps
Leave one of your properties empty and execute a job. Navigate to job > info and observe the issue (in Firefox or Chrome)

In the HTML source below, note the `dd` tag for JVM_OPTIONS is empty, causing the alignment issue.
```
<dl class="dl-horizontal dl-tooltip">
  <dt class="wide">BRANCH</dt><dd style="overflow: auto;">develop</dd>
  <dt class="wide">JVMS_SERVER</dt><dd style="overflow: auto;">glowroot01-TST01</dd>
  <dt class="wide">JVM_OPTIONS</dt><dd style="overflow: auto;"></dd>
  <dt class="wide">LOGS_SERVER</dt><dd style="overflow: auto;">logs01-TST01</dd>
  <dt class="wide">LOGS_TAG</dt><dd style="overflow: auto;">epgpaymep-tag</dd>
  <dt class="wide">SERVICE_NAME</dt><dd style="overflow: auto;">epgpay-mep</dd>
  <dt class="wide">SERVICE_PORT</dt><dd style="overflow: auto;">8091</dd>
  <dt class="wide">SERVICE_VERSION</dt><dd style="overflow: auto;">1.19.0-EARC88-SNAPSHOT</dd>
</dl>
```

**Comment by preetapan** [comment]
@PeteBoucher This doesn't look like the Nomad UI, and we are still on version 0.8.6 not 1.0.0. Are you perhaps using the community maintained [hashi-ui](https://github.com/jippi/hashi-ui/)?
