### ISSUE TITLE
Nomad jobs are being restarted despite that feature being disabled

### ISSUE THREAD

**Issue by kurtwheeler** [hashicorp/nomad#4979]
### Nomad version

Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details

We are running this within AWS using an ubuntu AMI:
```
ubuntu-16.04-docker-17.12.0-ce-201802201241 (ami-dd08efa0)
```

### Issue

Related : https://github.com/hashicorp/nomad/issues/4700

@dadgar closed that issue without confirming it was resolved. It's not clear to me if it was in fact resolved at that time and a new feature has subsequently caused the issue to return or if it just made the issue rare enough that I didn't notice until I had run hundreds of thousands of jobs.

However, unless I once again need to add settings to my configuration files to turn off an even newer feature, that wasn't the only cause of my jobs being retried.

**I don't want Nomad to retry my jobs.** Ever. I have disabled restarts and reschedules. How can I make Nomad not retry, restart, reschedule, requeue, or whatever other verbs might be used to cause a Nomad job which has already been started to become started once again?

### Reproduction steps

I wish I knew.

### Nomad Server logs (if appropriate)

```
ubuntu@ip-10-0-136-10:~$ nomad status SALMON_5_12288/dispatch-1544386103-02b60e7f
ID            = SALMON_5_12288/dispatch-1544386103-02b60e7f
Name          = SALMON_5_12288/dispatch-1544386103-02b60e7f
Submit Date   = 2018-12-09T20:08:23Z
Type          = batch
Priority      = 50
Datacenters   = dc1
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
jobs        0       0         0        0       1         1

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created     Modified
3bf6e4a3  0d1dca79  jobs        0        run      complete  2m8s ago    1m41s ago
0ded02f7  0fbac6e4  jobs        0        stop     lost      19h40m ago  18h40m ago


ubuntu@ip-10-0-136-10:~$ nomad status 0ded02f7
ID                  = 0ded02f7
Eval ID             = 5fafadb0
Name                = SALMON_5_12288/dispatch-1544386103-02b60e7f.jobs[0]
Node ID             = 0fbac6e4
Job ID              = SALMON_5_12288/dispatch-1544386103-02b60e7f
Job Version         = 0
Client Status       = lost
Client Description  = <none>
Desired Status      = stop
Desired Description = alloc is lost since its node is down
Created             = 19h41m ago
Modified            = 18h41m ago

Couldn't retrieve stats: Unexpected response code: 404 (No path to node)

Task "salmon" is "running"
Task Resources
CPU       Memory  Disk    IOPS  Addresses
1024 MHz  12 GiB  10 MiB  0     

Task Events:
Started At     = 2018-12-10T00:06:01Ztemplated
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2018-12-10T00:06:01Z  Started     Task started by client
2018-12-10T00:05:59Z  Task Setup  Building Task Directory
2018-12-10T00:05:59Z  Received    Task received by client
```

### Job file (if appropriate)

This file gets templated with the appropriate environment files to become the job spec:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/nomad-job-specs/salmon.nomad.tpl

**Comment by preetapan** [comment]
@kurtwheeler the alloc status description states `Desired Description = alloc is lost since its node is down` - looks like Nomad restarted it on another node because it was unable to reach the client node that your job was running on. This is a design decision made for correctness - because nomad servers can't reach that node, it restarts it on another node. This isn't something that can be disabled. 

If you look in the nomad client's logs on `0fbac6e4` you'll be able to see what happened - perhaps a networking issue? We provide some configurability if you want slower true failure detection to prevent false positives for temporary network issues. See https://www.nomadproject.io/docs/configuration/server.html#heartbeat_grace
