### ISSUE TITLE
[question] What does the resource stanza imply? constraints or requirements?

### ISSUE THREAD

**Issue by yifeikong** [hashicorp/nomad#4988]
docs says
> Memory
> 
> This example specifies the task requires 2 GB of RAM to operate. 2 GB is the equivalent of 2000 MB:
> 
> resources {
>   memory = 2000
> }
> 

which one is correct per this config:

1. at least 2000MB will be reserved for the task
2. the task is constraint to a maximum of 2000MB memory, if it uses more than 2000MB, it will be killed.

**Comment by nickethier** [comment]
Hi @yifeikong 

For the given config Nomad will reserve 2000MB for the task assuming it has room to place it. Depending on the driver used it will also isolate this memory, such that if it uses over 2000MB it will be killed. The exception here is when the `raw_exec` driver is used. 

Feel free to reopen if this doesn't answer your question.

**Comment by yifeikong** [comment]
Thanks for your answer. So it's both of them, maybe this could be two separate configs?

```
resources {
    memoryMin = 100
    memoryMax = 2000
}
```

100 MB is required to start the task, and the task will be killed if it ever reaches the 2000MB limit.
