### ISSUE TITLE
Specifying consul service names without job/group/task names

### ISSUE THREAD

**Issue by Nomon** [hashicorp/nomad#499]
I am running docker registry via nomad, with 0.1.0 I had gliderlabs/registrator running on all the nomad client nodes and registering any containers to consul based on their SERVICE_NAME env variables.

So the registry had SERVICE_NAME=registry and all the registry servers were thus available at registry.service.consul. Now after updating to nomad 0.2.0 and replacing the registrator container with the service {} block in the task, if naming the service "registry" it will be available in the dns as docker-registry-servers-registry-registry.service.consul instead of registry.service.consul.

I tried to work around this by adding an external service alias "registry" to the jodocker-registry-servers-registry-registry.service.consul to create an CNAME for it but apparently consul does not know to recurse the .consul names to itself from external service definition (even with --recursor 127.0.0.1:8600) so resolving registry.service.consul will not work ( https://github.com/hashicorp/consul/issues/1228 ).

What is the correct way to get the docker registry container running at registry.service.consul using the service {} block along with consul, or is the correct way to re-tag all the images in the registry as "docker-registry-servers-registry-registry.service.consul:5000" instead and start using the job-group-task-name.service.consul names in all discovery.

Here is the jobspec template I am currently using with terraform to deploy the registry job
```hcl
job "docker-registry" {
  type = "service"
  datacenters = ["us-west-staging"]
  update {
    stagger = "30s"
    max_parallel = 1
  }
  group "servers" {
    count = 2
    task "registry" {
      service {
        name = "registry"
        port = "http"
        check {
          type = "http"
          path = "/v2/"
          interval = "10s"
          timeout = "2s"
        }
      }
      driver = "docker"
      env {
        REGISTRY_STORAGE = "s3"
        REGISTRY_STORAGE_S3_ACCESSKEY = "${access_key}"
        REGISTRY_STORAGE_S3_SECRETKEY = "${secret_key}"
        REGISTRY_STORAGE_S3_REGION = "${region}"
        REGISTRY_STORAGE_S3_BUCKET = "${bucket}"
        REGISTRY_STORAGE_S3_ROOTDIRECTORY = "${directory}"
        REGISTRY_HTTP_ADDR = ":5000"
        REGISTRY_HTTP_SECRET = "${http_secret}"
        SERVICE_NAME = "registry"
        SERVICE_5000_CHECK_HTTP= "/v2/"
        SERVICE_5000_NAME = "registry"
      }
      config {
        image = "registry:2"
      }
      resources {
          cpu = 500
          memory = 512
          network {
              mbits = 1
              port "http" {
                static = 5000
              }
          }
       }
    }
  }
}
```

**Comment by diptanu** [comment]
@Nomon Hi Nomon, this is a valid use case and users will be able to override the prefix of the names generated by the service block soon.

**Comment by poll0rz** [comment]
+1 thanks!
