### ISSUE TITLE
Old alloc is still running

### ISSUE THREAD

**Issue by urjitbhatia** [hashicorp/nomad#4996]
### Nomad version
`Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)`

### Operating system and Environment details
- `Linux ip-10-1-2-96 4.4.0-1073-aws #83-Ubuntu SMP Sat Nov 17 00:26:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- We use replicator to scale up/down (which creates a lot of deployments trying to scale up approaching peak traffic)
- Job runs using docker driver

### Issue
We have 2 problems perhaps related to each other.

1. There are old allocations from many deployments ago which are still running - this means that we end up running stale code in production which is pretty bad for us.

2. New deployments randomly failed on usually 1 sometimes 2 stuck allocations. For example, for a count of 100, 99 get allocated and then the deployment gets stuck. Restart the nomad agent on the client node usually fixes the problem but it is frustrating to go hunt for these nodes and restart the agents all the time.

### Reproduction steps
-Run a lot of deployments with large number of containers being added or removed (replicator scaling to approach peak traffic - maybe that causes this problem to happen more often?)
- Running between 150 to 400 containers for this job

Alloc that should be long dead:
```
ID                   = 2f4ac4d8
Eval ID              = 19b57607
Name                 = api-runner
Node ID              = fc906fec
Job ID               = api-nomad
Job Version          = 12002
Client Status        = running
Client Description   = <none>
Desired Status       = run
Desired Description  = <none>
Created              = 13h46m ago
Modified             = 13h1m ago
Deployment ID        = 3ec857a6
Deployment Health    = healthy
Replacement Alloc ID = 4bad4698

Task "api_runner_hostnet" is "running"
Task Resources
CPU            Memory           Disk     IOPS  Addresses
1498/3000 MHz  1.1 GiB/2.5 GiB  300 MiB  0     http: 10.1.2.96:30624
                                               haproxy_check_tcp: 10.1.2.96:23554
                                               haproxy_check_agent: 10.1.2.96:26655
                                               consul_check: 10.1.2.96:30884

Task Events:
Started At     = 2018-12-12T16:36:42Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2018-12-12T16:36:42Z  Started     Task started by client
2018-12-12T16:36:42Z  Task Setup  Building Task Directory
2018-12-12T16:36:42Z  Received    Task received by client
```

Job status showing 2 really old allocations still running
```
22998282  fc906fec  api-nomad-prod-hostnet  12312    run      running   19m46s ago  19m12s ago
75bc83cc  f6b0b65c  api-nomad-prod-hostnet  12308    run      running   6h24m ago   6h23m ago
2f4ac4d8  fc906fec  api-nomad-prod-hostnet  12002    run      running   13h48m ago  13h3m ago
```

**Comment by tzahimizrahi** [comment]
Hi, Any update with this bug?

**Comment by preetapan** [comment]
@tzahimizrahi or @urjitbhatia - would you be able to provide client logs from the node where these old allocs were running the next time this happens? We are not seeing this sort of issue under normal loads/deploying jobs with new versions so having logs should help us investigate further

**Comment by tzahimizrahi** [comment]
@preetapan take a look at this one https://github.com/hashicorp/nomad/issues/5363
Sounds similar

**Comment by tzahimizrahi** [comment]
@preetapan I believe the referenced issue contain the necessary details. Let me know if additional information is required
