### ISSUE TITLE
Nomad vs. AWS ECS page

### ISSUE THREAD

**Issue by xied75** [hashicorp/nomad#500]
Dear Team,

For this page: https://www.nomadproject.io/intro/vs/ecs.html
The first three paragraphs can be shortened as it just repeating one fact, that ECS is AWS & Docker only, which is clear enough for people to get it. There is no reason to repeat it.

Also the 2nd paragraph mentioned about AWS severs are closed source, this can be more clear as the first several reads I did makes me think that you are talking about the Amazon Linux, which is very confusing. I guess you really want to say the Server Component for Orchestration the ECS Deployment, is that correct?

As usual Hashicop users are first line combat forces, there really is no need to have too much marketing words. Just my 2 pence. :)

**Comment by dadgar** [comment]
Thanks for the feedback @xied75. We are target a broad audience with our documentation who may not be familiar with ECS so we prefer to error on the side of being verbose but clear.
