### ISSUE TITLE
RPC failed to server: rpc error: rpc error: node lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0073 's'

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#5000]
### Operating system and Environment details
Linux, latest release Nomad.

### Issue

```
    2018/12/13 20:45:42.624140 [ERR] nomad: "Node.List" RPC failed to server [[my ip]]:4647: rpc error: rpc error: node lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0073 's'
    2018/12/13 20:45:42.624285 [ERR] http: Request /v1/nodes?prefix=self, error: rpc error: rpc error: node lookup failed: index error: Invalid UUID: encoding/hex: invalid byte: U+0073 's'
```

This appears to have killed the client entirely, it still responds but there are no new allocations although there is pending work and other clients are behaving better.

**Comment by dadgar** [comment]
This error is driven by the user's request. Nomad will never generate a node list HTTP request itself. I am going to close this issue but feel free to open another if you discover an issue regarding that node.

**Comment by Miserlou** [comment]
This is a bug in Nomad.

**Comment by dadgar** [comment]
@Miserlou What is the bug? As I explained the input to the prefix command on the node endpoint must be a valid UUID prefix. That is also what the response error is indicating: `Invalid UUID`.

The request: `/v1/nodes?prefix=self` is invalid, since `s` is not a valid hex character in a UUID.

**Comment by tanin47** [comment]
> So in the case of jobs, if you have the following job IDs registered: ["api-foo", "api-bar", "database"], the /v1/jobs?prefix=api would return the first two.

I just encountered this problem. There might be a confusion around the given example here and the example in the doc (https://www.nomadproject.io/api/jobs.html)

The prefix is meant to be a prefix of a job ID, which looks like this: `0d33e55d-052d-e0b1-efa6-c60a96492c0f`; `/v1/nodes?prefix=0d33e55d` is a valid request.

`prefix=api` and the example `curl https://localhost:4646/v1/jobs?prefix=team` would throw the `Invalid UUID` exception. Changing the example in the doc might be good to avoid confusion.
