### ISSUE TITLE
Nomad does not show resource utilization for Windows containers

### ISSUE THREAD

**Issue by vyacheslav-skvortsov** [hashicorp/nomad#5006]
Nomad does not show resource utilization for Windows containers:
![image](https://user-images.githubusercontent.com/29980836/50002010-63930180-ffa7-11e8-9655-09d0daaac2eb.png)

**nomad node status**
Allocated Resources
CPU            Memory           Disk            IOPS
512/10400 MHz  1.0 GiB/8.0 GiB  300 MiB/75 GiB  0/0

Allocation Resource Utilization
CPU          Memory
0/10400 MHz  0 B/8.0 GiB

Host Resource Utilization
CPU             Memory           Disk
2736/10400 MHz  1.4 GiB/8.0 GiB  25 GiB/100 GiB

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created   Modified
37643b85  857b1d7b  cpu-test    10       run      running  1m6s ago  59s ago

**docker stats**
  CPU %               PRIV WORKING SET    NET I/O             BLOCK I/O
  20.62%              121.2MiB            150kB / 50.1kB      44.3MB / 16.1MB

### Nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details
Windows Server 2016 1803

**Comment by schmichael** [comment]
We're tracking this in Support runtime resource usage metrics in Docker for Windows #2897.
