### ISSUE TITLE
Split nomad cluster into two clusters

### ISSUE THREAD

**Issue by sduggisetty** [hashicorp/nomad#5010]
We are using nomad & consul in our projects and we have two environments(Dev & Test). Each environment has different cluster. Both are isolated clusters. We newly introduced puppet manage these nomad & consul and unfortunately when puppet pushed some configuration, Dev & Test became once cluster.

DEV got merged with Test cluster. Now overall works like a single cluster. Because of this whenever we do dev deployment it is going into Test servers, Test deployments are going into Dev servers too.

Could someone please help me how can i separate them again? 

Even though config.json file shows different IP address in retry_join, all servers getting into one cluster. I tried restarting linux server, Nomad & consul couple of time it is not working.

I tried nomad force-leave command also, still whenever we restart the nomad again it is combining with same cluster. 

I believe these clusters are being managed by consul. How can i separate them back. Kindly help.

**Comment by jippi** [comment]
Two ways to break it up

1) kill raft on all instances and have them rediscover the isolated clusters
2) put down firewall rules between the clusters, and cleanup raft, and wait for nomad to GC the other cluster away ~72h

**Comment by sduggisetty** [comment]
> Two ways to break it up
> 
> 1. kill raft on all instances and have them rediscover the isolated clusters
> 2. put down firewall rules between the clusters, and cleanup raft, and wait for nomad to GC the other cluster away ~72h

Hi Jippi,

I have followed the second option and it worked fine. Thanks a lot.

What i have done is, i stopped all DEV servers so that the TEST cluster deleted the DEV servers infrom from that cluster.
Then i deleted the data dirs of nomad & consul in all DEV servers and started them back again.

Thank you very much.
