### ISSUE TITLE
[Question] 0.8.7 Release Schedule

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#5014]
Very quick question - can we expect to see an 0.8.7 this week? We need the `tmpfs` support that's in `-rc1` right now for some of our work, and we'd love to be able to plan for whether or not we'll be able to use the functionality in the next release over the Christmas break next week.

Thanks!

**Comment by preetapan** [comment]
@Miserlou the current plan is to release 0.8.7 early January, to make sure we have engineers available to look at any further bug reports/issues after the release.
