### ISSUE TITLE
nomad.service differs from the one proposed in the documentation

### ISSUE THREAD

**Issue by frafra** [hashicorp/nomad#5019]
https://github.com/hashicorp/nomad/blob/master/dist/systemd/nomad.service
https://www.nomadproject.io/guides/operations/deployment-guide.html#configure-systemd

Which file is uptodate/suggested? It looks like the one in the guide has a safer setup.

**Comment by preetapan** [comment]
@frafra the canonical example is in https://github.com/hashicorp/nomad/blob/master/dist/systemd/nomad.service
