### ISSUE TITLE
[feature]: Enable specifying user/group permissions in the template stanza

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/nomad#5020]
It would be great to have `user` and `group` parameters to the `template` stanza. This would allow us to trim down the `perms` of templates handling secrets to just the user/group of the user running in the container.

Use case: We have few jobs running the `docker` driver and we are injecting a few config files using the `template` stanza with secrets from Vault. Right now we have to set `perms = 444` in order to allow the task to read the rendered template. From a security standpoint, this is not optimal since 444 allows anyone to read the file. So, being able to specify an `user`/`group` combination in the template stanza would make things simpler since Nomad always create the templates with user and group = root.

Having to do manual steps on a docker `entrypoint` script to achieve that is ugly IMO.

This is related to #2091

**Comment by danlsgiga** [comment]
@preetapan not really! The template is created with user / group set to root and I run my container using nobody / nobody (best practices heh!). Setting perms = 400 (Tried that and didn't work) will make the file readable by root only.

**Comment by peimanja** [comment]
Any update on this issue?

**Comment by tgross** [comment]
Hi @peimanja. Sorry we don't have an update on this. I've made sure to put it onto our backlog for discussion though.

**Comment by AbhilashBalaji** [comment]
Hey , I would like to work on this issue , could someone give me any idea on where to start from ?

**Comment by AbhilashBalaji** [comment]
Would adding extra checks [here](https://github.com/hashicorp/nomad/blob/940817aeb52e740ef5d35f1be925f2c61b8ecd0f/client/allocrunner/taskrunner/template/template.go#L584) make a feasible solution

**Comment by mr-karan** [comment]
+1. Trying to deploy `gitea` and it mounts the config file as a `root` user. But `gitea` is started with a non root user, effectively unable to read the file.

**Comment by MagicRB** [comment]
I'm trying to run HydraCI in a Nix built container, but HydraCI requires the pgpass file to be 600 or less, which means I have to change it's owner from root:root

**Comment by virtualshuric** [comment]
Another case for setting templated files ownership is running RabbitMQ containers as non-root user:

1. RMQ requires, that Erlang cookie has permission of 0600 (or 0400). 
2. When running RMQ image as root user, entrypoint script simply chowns cookie-file to non-privileged `rabbitmq` user. 
3. When running RMQ as non-root - it either can't read cookie-file (because of `root:root` owner and 0600 permissions), either RMQ fails to start because permission set don't match (e.g. when cookie file permissions are 0644).

**Comment by keslerm** [comment]
Ran into needing this a bunch already and it makes things really troublesome to get going sometimes.

**Comment by 3nprob** [comment]
Support for setting `uid` and `guid` just got merged to consul-template, expected for next release: https://github.com/hashicorp/consul-template/pull/1531

**Comment by jrasell** [comment]
Hi @3nprob and others. I have raised that internally and any updates will be posted as follow up comments.

**Comment by timurkhisamov** [comment]
Any update on this issue?

**Comment by danlsgiga** [comment]
And, here it is: https://github.com/hashicorp/consul-template/blob/master/CHANGELOG.md#v0280-mar-04-2022

**Comment by 3nprob** [comment]
@jrasell Got any news for us now that the prerequisites are in place with 1.3? :)
