### ISSUE TITLE
Nomad destroys old allocations before creating new during a deployment

### ISSUE THREAD

**Issue by braxton9460** [hashicorp/nomad#5033]
### Nomad version
`Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)`

### Operating system and Environment details 
**OS**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Docker Version**
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
The entire environment is hosted in AWS vpc hosted across 3 AZ's.
A majority of the applications I am working with are docker containers running nodejs. Not all are node, but all are docker containers.

### Issue
During a deployment or migration (forced by something like draining a node), nomad always seems to destroy an existing container before creating a new one. Which seems to be the opposite of what this says should happen as part of a rolling deployment (which I believe I am setup for.. or at least have tried to be): https://www.hashicorp.com/blog/building-resilient-infrastructure-with-nomad-job-lifecycle
Perhaps I am just doing something wrong, but I have tried a number of configurations and tried submitting jobs from the api and cli both to see if it were to be some issue in the submission method.

### Reproduction steps
* Run a job
* make a change (i.e. change the container version)
* run the job again (to push the changes)

It starts a deployment, incrementing the version and such as expected, however, it stops the (max_parallel) number of containers before starting the new ones. Vs. what I would expect and what that job lifecycle blog article says should happen is nomad would start the deployment after the change, start (max_parallel) number of new containers, wait for them to be healthy and in service, then tear the old (max_parallel) number of containers down, then continue on to the next set until all containers have been replaced.

### Job file (if appropriate)
```
job "api" {
  datacenters = ["dev"]
  type = "service"
  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "2m"
    progress_deadline = "10m"
    auto_revert = true
  }
  migrate {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "5m"
  }
  group "api" {
    count = 1
    constraint {
      operator  = "distinct_hosts"
      value     = "true"
    }
    restart {
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "fail"
    }
    reschedule {
      attempts       = 2
      interval       = "30m"
      delay          = "30s"
      delay_function = "exponential"
      max_delay      = "120s"
      unlimited      = false
    }
    ephemeral_disk {
      size = 300
    }
    task "api" {
      driver = "docker"
      config {
        image = "{MYIMAGEPATH}:v47"
        port_map {
          api_pl = 3017
        }
        hostname = "${attr.unique.hostname}"
        extra_hosts = ["dockerhost.internal:172.17.0.1"]
      }
      resources {
        cpu    = 500
        memory = 1024
        network {
          mbits = 10
          port "api_pl" {}
        }
      }
      service {
        name = "api"
        tags = ["myapi"]
        port = "api_pl"
        check {
          name     = "alive-status"
          type     = "http"
          path 	   = "/status"
          interval = "10s"
          timeout  = "2s"
        }
        check_restart {
          grace           = "30s"
          ignore_warnings = "false"
          limit           = "3"
        }
      }
      env {
        NODE_ENV = "DEV"
        AWS_ACCESS_KEY_ID = "notprovided"
        AWS_SECRET_ACCESS_KEY = "notprovided"
        BUCKET_NAME = "notprovided"
        BUCKET_REGION = "notprovided"
      }
    }
  }
}
```

**Comment by preetapan** [comment]
@braxton9460 based on your update stanza above, Nomad works as designed.  Your current settings in the update stanza above achieve parallel upgrades (https://www.nomadproject.io/docs/job-specification/update.html#parallel-upgrades-based-on-checks)  - i.e max_parallel new allocations are started on the new version while stopping the same number on the old version. 

If you want old allocations to remain untouched while bringing up new allocations, sounds like you need a blue/green strategy with canaries - https://www.nomadproject.io/docs/job-specification/update.html#blue-green-upgrades. If you set `canary` and `max-parallel` equal to the number of instances it should bring up new instances first and the old will not be stopped until the deployment is manually promoted. 

I can see how the diagrams and the wording in this blog post are somewhat confusing - https://www.hashicorp.com/blog/building-resilient-infrastructure-with-nomad-job-lifecycle. Its intended meaning that upto `max_parallel` allocations of the old version will be stopped at the same time as the new allocations are created, and the _next_ set of allocations on the old version are not stopped until the new allocations created become healthy. We can edit the wording to make this clearer.

**Comment by cheeseprocedure** [comment]
My team has run into the same issue. If I understand correctly, the diagram in the "Rolling and serial updates" section of the blog post above describes a behaviour that isn't currently possible (that is: create v2 allocation, wait for v2 allocation to become healthy *then* tear down v1 allocation, repeat for next allocation). If so, +1 to updating the diagram/wording.

(We'll investigate working around this with the ``canary``/``max_parallel`` parameters - thank you!)
