### ISSUE TITLE
Task not stopped properly from docker in client machine

### ISSUE THREAD

**Issue by Suresh-Nakkeran** [hashicorp/nomad#5039]
A docker service job is submitted, it is allocated and started running in a client machine. when we submit update request for that job, the old container is not stopped properly and tried to start new container for that job and failed with 'port is already allocated' error.

**Nomad version**
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

**Docker version**
Docker version 17.03.2-ce, build f5ec1e2

**Nomad log from client machine**
2018-12-19T04:54:35.462Z [DEBUG] plugin: starting plugin: path=<nomad-path> args="[<nomad-path> executor {"LogFile":"<nomad-path>/datadir/alloc/dd8367b4-eec0-a031-b2f3-572e12fda797/task/executor.out","LogLevel":"INFO"}]"
2018-12-19T04:54:35.467Z [DEBUG] plugin: waiting for RPC address: path=<nomad-path>
2018-12-19T04:54:35.684Z [DEBUG] plugin.nomad: plugin address: timestamp=2018-12-19T04:54:35.683Z network=unix address=/tmp/plugin205769223
2018/12/19 04:54:35.729253 [INFO] driver.docker: created container 22cef8c82d7b1d2af80fc59a2eb44411cc1229cea2f5b976565ed92c42063c06
2018/12/19 04:54:36.546462 [INFO] driver.docker: started container 22cef8c82d7b1d2af80fc59a2eb44411cc1229cea2f5b976565ed92c42063c06
.
.
2018/12/19 05:30:02.408170 [INFO] driver.docker: stopped container 22cef8c82d7b1d2af80fc59a2eb44411cc1229cea2f5b976565ed92c42063c06
.
2018/12/19 05:30:43.164576 [ERR] driver.docker: failed to start container 3c01b1273585f81fc04bdfc41044682bb7d8412d66cda412f6e7d678c9f13e48: API error (500): {"message":"driver failed programming external connectivity on endpoint task-3ed4f0f0-2592-9636-92ae-35134f827b8d (ddc5991a4ee38e4fc5064859add4cecadc4da8cddc0623dd4dee08adc188048e): Bind for 10.10.1.197:3000 failed: port is already allocated"}

**Comment by preetapan** [comment]
@Suresh-Nakkeran can you share your job spec file to help us reproduce this?

**Comment by Suresh-Nakkeran** [comment]
@preetapan, the jobs are deployed in a dev environment and we are frequently updating whenever we make code changes (lets take ~10-20 update per day). we are facing this issue once or twice in a week.

my job spec,

job "<job-name>" {
  datacenters = ["dc1"]
  type = "service"
  constraint {
    operator  = "distinct_hosts"
    value     = "true"
  }
  update {
    max_parallel = 1
    health_check = "task_states"
    auto_revert  = false
  }
  priority = 95
  group "<job-name>" {       # same job name used as group name
    count = 2
    task "<job-name>" {      # same job name used as task name
      driver = "docker"
      env {
	# list of env variables
      }
      config {
        image = "<image-name>"   # from private repo
        auth {
          username = "<user-name>"
          password = "<password>"
        }
        port_map {
          port1   = 12020
        }
      resources {
        cpu = 500   # MHz
        memory = 220 # MB
        network {
          mbits = 5
          port "port1" {
            static = 12020
          }
        }
      }
      service {
        tags = ["<job-name>"]
        name = "<job-name>"
        port = "port1"
      }
    }
  }
}
