### ISSUE TITLE
[Question] How to correctly use "force_pull" parameter?

### ISSUE THREAD

**Issue by mattiacolleoni** [hashicorp/nomad#5040]
Hi,
I'm using Nomad v0.8.4.
I'm using in pre-production environment images tagged as "rc-latest". This tag is overwritten every new deploy.
Despite my nomad configuration file has the "docker_pull" parameter set as true, when I execute
`nomad plan` or `nomad run` all is ignored. The only way that works is to stop and re-run the plan.
Is there any type of option in those commands that forces image pull?
Many thanks,

Mattia

**Comment by jippi** [comment]
you need to stop/start the job - or modify a meta key or similar to force a change.

from nomads point of view, changes are only detected from the job spec, not the underlying docker image. `force_pull=true` is only used when starting a container - it will not be used to detect changes in the underlying docker image.

my workaround is to use something like [levant](https://github.com/jrasell/levant) which will insert a timestamp or similar into `job { meta {} }` to trigger such a change

**Comment by mattiacolleoni** [comment]
Many thanks @jippi !
