### ISSUE TITLE
SCDF streams not getting deployed through nomad 0.8.6 in RHEL6

### ISSUE THREAD

**Issue by aravind4444** [hashicorp/nomad#5050]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version 
v0.8.6
### Operating system and Environment details
RHEL6

### Issue: 
We are trying to setup Spring cloud dataflow server through nomad and deploy the streams. The scdf server is configured to deploy through nomad java driver. After SCDF server is up, we are trying to create and deploy streams where the scdf passes the deployment commands to nomad which is failing with below error

ID            = ticktok-test-log
Name          = ticktok-test-log
Submit Date   = 2018-12-23T08:02:25+01:00
Type          = service
Priority      = 50
Datacenters   = dc2
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group          Queued  Starting  Running  Failed  Complete  Lost
ticktok-test-log-0  1       0         0        0       0         0

Placement Failure
Task Group "ticktok-test-log-0":
  * Constraint "missing drivers" filtered 1 nodes
 

### Reproduction steps : 
Setup nomad 0.8.6 and deploy scdf [spring-cloud-dataflow-server-1-2-3-oracle-nomad-1.0.0.jar] through nomad with java driver. The start ticktok stream in RHEL6

### Nomad client logs (if appropriate) 
ID            = ticktok-test-log
Name          = ticktok-test-log
Submit Date   = 2018-12-23T08:02:25+01:00
Type          = service
Priority      = 50
Datacenters   = dc2
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group          Queued  Starting  Running  Failed  Complete  Lost
ticktok-test-log-0  1       0         0        0       0         0

Placement Failure
Task Group "ticktok-test-log-0":
  * Constraint "missing drivers" filtered 1 nodes

### Job file (if appropriate)
There is no job file for the streams.

**Comment by aravind4444** [comment]
Hi - It would be great if someone pick this up as priority?

**Comment by shantanugadgil** [comment]
Hi, is the missing driver seen otherwise as well?
Missing driver would indicate Nomad not detecting java as a viable driver on the system.

BTW, can you post a minimal job file of the original job to give a hint as to what is being attempted here.

**Comment by aravind4444** [comment]
For clarity, We are able to start scdf servers with java driver and it comes up without any issues. The issue is while deploying the streams from scdf server where it fails. The same setup works fine in vagrant box with CentOS binary equivalent to RHEL6.

Please note: nomad is running as root user as per the requirements for java driver. The allocations are running as nobody user.

sample scdf deployment file: Adter deployment, login to the scdf console and create ticktok stream with source as trigger and sink as log and deploy the stream.

After stream deployment, if you check nomad status on the trigger and log jobs, you will get above missing driver error :(

==================
`job "dataflow-scdf-java" {
    region = "dc2"
    datacenters = [
        "dc2"]
    priority = 40

    # Restrict our job to only linux.
    constraint {
        attribute = "linux"
        value = "linux"
    }

    group "v1" {
        count = 1

        task "SpringDataflowServerJava" {
            driver = "java"

            config {
                jar_path="local/spring-cloud-dataflow-server-1-2-3-oracle-nomad-1.0.0.jar"
                jvm_options = [
                    "-Xmx512m",
                    "-Xms256m"]
            }
            env {
                PATH="$PATH;/usr/java/jdk1.8.0_181-amd64/jre/bin/java"
                JAVA_OPTS = "-Xmx256m"
                spring.cloud.config.server.bootstrap = "false"
                spring.cloud.dataflow.features.application-groups-enabled = "true"
                health.config.enabled = "false"
                spring.cloud.dataflow.rdbms.initialize.enable="false"
                spring.jpa.generate-ddl="false"
                spring.batch.initializer.enabled="false"
                spring.cloud.task.initialize.enable="false"
                spring.datasource.url = "<<our_Dev/test DB>>"
                spring.datasource.driverClassName = "oracle.jdbc.driver.OracleDriver"
                spring.datasource.username = "<<DB_USER>>"
                spring.datasource.password = "<<DB_PWD>>"
                spring.datasource.testOnBorrow = "true"
                spring.datasource.validationQuery = "SELECT 1"
                spring.redis.host = "localhost"
                spring.redis.port = "6379"
                spring.rabbitmq.host = "localhost"
                spring.rabbitmq.port = "5672"
                maven.resolvePom = "false"
                maven.remote-repositories.spring.url = "http://repo.spring.io/libs-snapshot"
                spring.cloud.deployer.nomad.region = "dc2"
                spring.cloud.deployer.nomad.datacenters = "dc2"
                spring.cloud.deployer.nomad.nomadHost = "localhost"
                spring.cloud.deployer.nomad.deployerHost = "${NOMAD_IP_http}"
                spring.cloud.deployer.nomad.checkHttpPath = "/management/health"
                spring.cloud.deployer.nomad.checkInterval = "60000"
                spring.cloud.deployer.nomad.javaOpts = "-Xms256m,-Xmx512m"
            }
      artifact {
        source = "http://10.224.70.49/micro-service-jars/spring-cloud-dataflow-server-1-2-3-oracle-nomad-1.0.0.jar"
      }


            service {
                name = "SpringDataflowServerJava"
                port = "http"
                check {
                    name = "Data Flow Server HTTP Check"
                    type = "http"
                    interval = "200s"
                    timeout = "200s"
                    path = "/management/health"
                    protocol = "http"
                }
            }

            resources {
                memory = 256
                network {
                    port "http" {
                        static = 9393
                    }
                }
            }
        }
    }
}`

**Comment by aravind4444** [comment]
any update on this? solving this issue will help us a greater extent...

**Comment by shantanugadgil** [comment]
I can imagine two more possibilities ...
Nomad is unable to find 'java'  in $PATH.
(that should be fixable by setting the path correctly before Nomad is started)

Second could be due to it being RHEL6 (i am only speculating) missing some packages, cgroup, etc.

I have never used the java driver, so only guessing here.

If the PATH before starting Nomad doesn't work,  would it be possible to try this with a RHEL7 (CentOS7)

HTH,
Shantanu Gadgil

**Comment by aravind4444** [comment]
Thanks for looking at this.

if nomad was not able to find the java path then it has to fail in starting scdf server itself. Here that is not the case. scdf is coming up without any issues through java driver. The problem is when the streams are deployed in scdf UI, it passes the job to nomad and tries to deploy it on the nomad cluster where it fails with missing driver issue.

Can see the cgroups are loaded in the nomad during startup which is good. what other packages that could be missing? Can we get some expert view on this?

we also understand that the issue is on the RHEL6 but not on centOS and mac. So need someone to help us in getting this resolved asap.

**Comment by shantanugadgil** [comment]
Hi, I have never used the `java` driver myself, so I'll let someone from HashiCorp answer this one. ;)

BTW, the PATH separator should be `:` not `;`

Also, the `constraint` seems to be incorrect ... shouldn't the "attribute" field be `kernel`, or something ?

**Comment by aravind4444** [comment]
Hi - corrected above and triggered the stream deployment. still the same error :(

**Comment by shantanugadgil** [comment]
At this point I wonder what the jobs logs say;
normal and with `-stderr`

**Comment by aravind4444** [comment]
After setting up nomad and scdf in RHEL7, i started seeing below error in the logs while running the job.

 2019/01/03 12:46:07.297941 [TRACE] client: alloc b0a1f72a-8169-7b02-09a3-cb316dab037e task SpringDataflowServer could not detect a driver IP

Any help on this?

**Comment by aravind4444** [comment]
@dadgar - Please can you help us in resolving the issue stated in the initial issue request?
we have tried setting up the scdf in RHEL6 and as well as RHEL7 but both resulted with below error
Placement Failure
Task Group "ticktok-log-0":
  * Constraint "missing drivers" filtered 1 nodes

Have posted the config in the initial request and any help will be more helpful....

**Comment by aravind4444** [comment]
We managed to fix the issue by ourselves and so closing this ticket.

For others benefit, the issue was due to the way we import the app jars into scdf. We were referring the jar from one of our local repo. the jars were manually downloaded and uploaded to local repo. Once we started importing the app jars from maven repo all started working as expected.
