### ISSUE TITLE
[question] Can I restart a job when a Vault record changes?

### ISSUE THREAD

**Issue by pashinin** [hashicorp/nomad#5052]
I have a service (Nomad job) that gets some secrets from Vault (like SSL certs):

```
template {
  data = <<EOH
{{ with secret ".../certs/supersecret" }}
{{ .Data.key }}
{{ end }}
EOH
   destination = "secrets/cert.key"
}
```

Now let's say certificates are automatically updated. As I understand Nomad will not do anything (and it's ok maybe) and my service will use old secrets. But I want to restart a job if Vault data (that my service relies on) changes. Can I do that?

Or do I need to manually restart jobs when secrets change?

**Comment by burdandrei** [comment]
You got 2 options:

- signal your app to reload the certs
- restart the app

**Comment by ketzacoatl** [comment]
@pashinin, you would want https://www.nomadproject.io/docs/job-specification/template.html#change_mode and the other parameters, no?

I could be wrong, but the way I understood it:
* use a template with consul/vault kv/etc referenced
* nomad runs consul-template alongside your task
* consul-template watches the referenced keys
* consul-template HUPs your task when those keys change

**Comment by pashinin** [comment]
@ketzacoatl, I didn't expect this. So Nomad always watches for key changes and re-renders templates (if keys change) and restart tasks? I thought Nomad only gets keys when starting a task and does not continue to watch them (used Vault keys) for changes.

**Comment by preetapan** [comment]
@pashinin, like @ketzacoatl points out, Nomad client agents (via consul-template) watch for changes, and when configured with the `change_mode` like described above, will send a signal to your task. You'll still need to make sure the task responds to that signal and reloads the generated template file
