### ISSUE TITLE
存在安全隐患 - possibility security risks

### ISSUE THREAD

**Issue by adra2n** [hashicorp/nomad#5145]
启动Nomad的server模式的时候默认是没有token保护的，任何client只要知道server的地址，若是4647没有做acl保护的任何，就可以直接加入到里面，然后通过上传job可以是其他的client执行命令，导致安全问题

**Comment by preetapan** [comment]
@adra2n I did a [google translate of your comment](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%E5%90%AF%E5%8A%A8Nomad%E7%9A%84server%E6%A8%A1%E5%BC%8F%E7%9A%84%E6%97%B6%E5%80%99%E9%BB%98%E8%AE%A4%E6%98%AF%E6%B2%A1%E6%9C%89token%E4%BF%9D%E6%8A%A4%E7%9A%84%EF%BC%8C%E4%BB%BB%E4%BD%95client%E5%8F%AA%E8%A6%81%E7%9F%A5%E9%81%93server%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%8C%E8%8B%A5%E6%98%AF4647%E6%B2%A1%E6%9C%89%E5%81%9Aacl%E4%BF%9D%E6%8A%A4%E7%9A%84%E4%BB%BB%E4%BD%95%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E5%8A%A0%E5%85%A5%E5%88%B0%E9%87%8C%E9%9D%A2%EF%BC%8C%E7%84%B6%E5%90%8E%E9%80%9A%E8%BF%87%E4%B8%8A%E4%BC%A0job%E5%8F%AF%E4%BB%A5%E6%98%AF%E5%85%B6%E4%BB%96%E7%9A%84client%E6%89%A7%E8%A1%8C%E5%91%BD%E4%BB%A4%EF%BC%8C%E5%AF%BC%E8%87%B4%E5%AE%89%E5%85%A8%E9%97%AE%E9%A2%98). To answer your question around security, see our TLS guide here - https://www.nomadproject.io/guides/security/securing-nomad.html. In production environments the cluster can be secured to prevent unauthorized clients from masquerading as Nomad agents. 

Also, please use the [mailing list ](https://groups.google.com/forum/#!forum/nomad-tool) for questions in the future.
