### ISSUE TITLE
Bogus port numbers in docker on 0.9-dev

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad#5160]
### Nomad version
Nomad v0.9.0-dev (fc7455c10494c80be512e55d65a9bdda17c30800+CHANGES)

I am not aware of any changes that were intentionally applied, I build inside a clean docker container with the following commands:

```
git clone -b $NOMADV https://github.com/hashicorp/nomad.git
cd nomad || exit 1
make bootstrap
make dev-ui
cd ../ || exit 1
```
NOMADV was set to 'master' for this build.

### Operating system and Environment details
Alpine Linux 3.8, Virt flavor running in Amazon EC2

### Issue
Port numbers do not match between docker and nomad.

### Reproduction steps
Install docker and nomad in an alpine machine, attempt to launch a docker container.  I've been using 
crccheck/hello-world, but any container that exposes at least one dynamic port should be fine.  After debugging with @angrycub today it seems this is likely a problem with docker in 0.9.

**Comment by schmichael** [comment]
Can you provide your job file or more details? When I run the example.nomad job generated by `nomad init` and run it against master (428cec9682f68abc089cfec1901f9bee97054966), alloc status shows:

```
Task "redis" is "running"
Task Resources
CPU        Memory           Disk     Addresses
6/500 MHz  948 KiB/256 MiB  300 MiB  db: 127.0.0.1:23151
```

And docker ps shows the same port:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
de7124fcddd7        redis:3.2           "docker-entrypoint.s…"   15 seconds ago      Up 14 seconds       127.0.0.1:23151->6379/tcp, 127.0.0.1:23151->6379/udp   1eaf6c42-47d0-fb38-43f9-95c2d77f0b81_redis_6f167667
```

I'm able to connect to the port as expected.

**Comment by the-maldridge** [comment]
Sure, here's a version with some of our internal config stripped out:

```
job "static_helloworld" {
  datacenters = ["US-EAST-1"]
  type = "service"
  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    progress_deadline = "10m"
    auto_revert = false
    canary = 0
  }
  group "helloworld" {
    count = 5
    restart {
      # The number of attempts to run the job within the specified interval.
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "delay"
    }
    task "whale" {
      driver = "docker"
      config {
        image = "crccheck/hello-world:latest"
        port_map {
          http = 8000
        }
      }
      resources {
        cpu    = 20
        memory = 10
        network {
          mbits = 1
          port "http" {}
        }
      }
      service {
        name = "helloworld"
        tags = [
          "traefik.enable=true",
          "traefik.frontend.entryPoints=https",
          "traefik.frontend.rule=Host: g2.site.tld",
        ]
        port = "http"
        check {
          name     = "alive"
          type     = "http"
          path = "/"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

**Comment by schmichael** [comment]
Tested that and the ports line up. I find it very easy to believe you hit a bug from a December build! Tons of fixes since then. Thanks for testing! I'm going to close for now, but please feel free to reopen if it fails on a new build. Things are getting pretty stable!

**Comment by the-maldridge** [comment]
Sure no worries.  I need to get this particular cluster QA'd soon so I'll just revert my local Go to 1.10, but when I get a moment I'll re-roll a test cluster with a current build.
