### ISSUE TITLE
system scheduler: error when performing plan/run with disabled nodes

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#5169]
### Nomad version
Output from `Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)`

### Operating system and Environment details
OS: `ubuntu-18.04`

### Issue
When attempting to plan/run a Nomad system job (which includes constraints) on a node pool which includes administratively disabled nodes, the call will fail with the following error:

```
Unexpected response code: 500 (rpc error: could not find node \"f5dd4bad-ddec-796d-6ab5-d11d80324ad5\")
``` 

The plan/run will succeed once the node is enabled in the cluster.

### Reproduction steps
Disable a node client node and then attempt to deploy a system job, potentially with constraints as I am not sure if this is a key part of this issue.

### Job file (if appropriate)

```
job "example" {
  datacenters = ["dc1"]
  type        = "system"

  group "example" {
    constraint {
      operator  = "="
      attribute = "${meta.role}"
      value     = "specificrole"
    }
...
```

**Comment by dadgar** [comment]
@jrasell what do you mean disable? Drain the node or mark it as in-eligible?

**Comment by jrasell** [comment]
@dadgar when the node has been marked as in-eligible.

**Comment by jorgemarey** [comment]
HI!,

This happend to me again on nomad 0.9.5

I was able to reproduce it by doint the following:

```
nomad agent -dev

nomad run example.nomad // change job to be system
nomad node eligibility -disable <node-id>
vi example.nomad //change the container version for example)
nomad plan example.nomad
Error during plan: Unexpected response code: 500 (could not find node "<node-id>")
```

I'm not able to perform an update to a system job if the cluster has one single node in ineligible status.

**Comment by dpn** [comment]
Yep, still seeing this as well on 0.9.5.

**Comment by perrymanuk** [comment]
We also ran into this issue

**Comment by codyja** [comment]
We're seeing this on 0.9.5 too. Can this be reopened?
