### ISSUE TITLE
Running multiple Nomad Client Containers on Single Node

### ISSUE THREAD

**Issue by sivarajendranaidu** [hashicorp/nomad#5185]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Ubuntu 18.04 

### Issue
Creating three Nomad Client Ubuntu Containers in Ubuntu 18.04 HOST Node and trying to connect to Nomad Sever in AWS.

Both HOST Node and AWS Node is accessible with public IP.
Please find the sever config as follows:
```
addresses {
    rpc  = "172.31.27.168"
    serf = "172.31.27.168"
}
advertise {
    http = "172.31.27.168:4646"
    rpc  = "172.31.27.168:4647"
    serf = "172.31.27.168:4648"
}

bind_addr = "0.0.0.0"
data_dir  = "/var/lib/nomad"
log_level = "DEBUG"

server {
    enabled = true
    bootstrap_expect = 1
}
```

### Reproduction steps
Tried the following options
**Docker Bridge**
Please docker run command for client docker
`docker run -itd --privileged -p 50000:4646 -p 50001:4647 -p 50002:4648 --user root -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name nomad_client_2 nomad`

Client Configuration as follows:
```
addresses {
    rpc  = "Public IP"
    http = "Public IP"
}

advertise {
    http = "Public IP:50000"
    rpc  = "Public IP:50001"
}

data_dir  = "/var/lib/nomad"
bind_addr = "0.0.0.0"
log_level = "DEBUG"

client {
    enabled = true
    servers = [
      "ec2-13-232-236-138.ap-south-1.compute.amazonaws.com"
    ]
    options {
        "driver.raw_exec.enable" = "1"
    }
}
```

I tried to do the port mapping so that I can have multiple container mapped to different PORTs. But is not working 

### Nomad Server logs (if appropriate)
root@ip-172-31-27-168:/home/siva# systemctl stop nomad.service
root@ip-172-31-27-168:/home/siva# /usr/bin/nomad agent -network-interface enp4s0 -config=/etc/nomad/server.hcl
==> WARNING: Bootstrap mode enabled! Potentially unsafe operation.
==> Loaded configuration from /etc/nomad/server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 172.31.27.168:4646; RPC: 172.31.27.168:4647; Serf: 172.31.27.168:4648
            Bind Addrs: HTTP: 0.0.0.0:4646; RPC: 172.31.27.168:4647; Serf: 172.31.27.168:4648
                Client: false
             Log Level: DEBUG
                Region: global (DC: dc1)
                Server: true
               Version: 0.8.7

==> Nomad agent started! Log data will stream in below:

    2019/01/14 16:16:55 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:172.31.27.168:4647 Address:172.31.27.168:4647}]
    2019/01/14 16:16:55 [INFO] raft: Node at 172.31.27.168:4647 [Follower] entering Follower state (Leader: "")
    2019/01/14 16:16:55 [INFO] serf: EventMemberJoin: ip-172-31-27-168.global 172.31.27.168
    2019/01/14 16:16:55.376854 [INFO] nomad: starting 2 scheduling worker(s) for [service batch system _core]
    2019/01/14 16:16:55 [WARN] serf: Failed to re-join any previously known node
    2019/01/14 16:16:55.377543 [INFO] nomad: adding server ip-172-31-27-168.global (Addr: 172.31.27.168:4647) (DC: dc1)
    2019/01/14 16:16:57 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2019/01/14 16:16:57 [INFO] raft: Node at 172.31.27.168:4647 [Candidate] entering Candidate state in term 5
    2019/01/14 16:16:57 [DEBUG] raft: Votes needed: 1
    2019/01/14 16:16:57 [DEBUG] raft: Vote granted from 172.31.27.168:4647 in term 5. Tally: 1
    2019/01/14 16:16:57 [INFO] raft: Election won. Tally: 1
    2019/01/14 16:16:57 [INFO] raft: Node at 172.31.27.168:4647 [Leader] entering Leader state
    2019/01/14 16:16:57.162596 [INFO] nomad: cluster leadership acquired
    2019/01/14 16:16:57.171622 [DEBUG] leader: reconciling job summaries at index: 625

### Nomad Client logs (if appropriate)
root@676278f66de1:/home/siva# /usr/bin/nomad agent -config /etc/nomad/client.hcl
==> Loaded configuration from /etc/nomad/client.hcl
==> Starting Nomad agent...
==> Error starting http server: failed to start HTTP listener: listen tcp 69.84.129.70:4646: bind: cannot assign requested address
    2019/01/14 16:17:38.379633 [INFO] client: using state directory /var/lib/nomad/client
    2019/01/14 16:17:38.379677 [INFO] client: using alloc directory /var/lib/nomad/alloc
    2019/01/14 16:17:38.399618 [DEBUG] client.fingerprint_manager: built-in fingerprints: [arch cgroup consul cpu host memory network nomad signal storage vault env_aws env_gce]
    2019/01/14 16:17:38.399739 [INFO] fingerprint.cgroups: cgroups are available
    2019/01/14 16:17:38.399815 [DEBUG] client.fingerprint_manager: fingerprinting cgroup every 15s
    2019/01/14 16:17:38.399881 [DEBUG] client.fingerprint_manager: fingerprinting consul every 15s
    2019/01/14 16:17:38.400541 [DEBUG] fingerprint.cpu: frequency: 4600 MHz
    2019/01/14 16:17:38.400545 [DEBUG] fingerprint.cpu: core count: 12
    2019/01/14 16:17:38.402101 [DEBUG] fingerprint.network: link speed for eth0 set to 10000
    2019/01/14 16:17:38.402135 [DEBUG] fingerprint.network: Detected interface eth0 with IP: 172.17.0.2
    2019/01/14 16:17:38.402912 [DEBUG] client.fingerprint_manager: fingerprinting vault every 15s
    2019/01/14 16:17:40.403019 [DEBUG] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
    2019/01/14 16:17:41.482455 [DEBUG] fingerprint.env_gce: Could not read value for attribute "machine-type"
    2019/01/14 16:17:41.482468 [DEBUG] fingerprint.env_gce: Error querying GCE Metadata URL, skipping
    2019/01/14 16:17:41.482490 [DEBUG] client.fingerprint_manager: detected fingerprints [arch cgroup cpu host network nomad signal storage]
    2019/01/14 16:17:41.482517 [DEBUG] driver.docker: using client connection initialized from environment
    2019/01/14 16:17:41.482541 [DEBUG] driver.docker: using client connection initialized from environment
    2019/01/14 16:17:41.485767 [DEBUG] driver.docker: bridge_ip could not be discovered
    2019/01/14 16:17:41.485859 [DEBUG] driver.exec: exec driver is enabled
    2019/01/14 16:17:41.485918 [WARN] driver.raw_exec: raw exec is enabled. Only enable if needed
    2019/01/14 16:17:41.485984 [DEBUG] client.fingerprint_manager: fingerprinting driver docker every 15s
    2019/01/14 16:17:41.486000 [DEBUG] client.fingerprint_manager: health checking driver docker every 1m0s
    2019/01/14 16:17:41.486013 [DEBUG] client.fingerprint_manager: fingerprinting driver exec every 15s
    2019/01/14 16:17:41.486349 [DEBUG] client.fingerprint_manager: detected drivers [docker exec raw_exec]
    2019/01/14 16:17:41.486434 [DEBUG] client.fingerprint_manager: fingerprinting driver rkt every 15s
    2019/01/14 16:17:42.128770 [INFO] client: Node ID "bd5febe0-488d-d2fa-f271-f9a06a22efd3"
    2019/01/14 16:17:42.128931 [INFO] agent: requesting shutdown
    2019/01/14 16:17:42.128946 [INFO] client: shutting down
    2019/01/14 16:17:42.129218 [ERR] nomad: "Node.Register" RPC failed to server 13.232.236.138:4647: rpc error: stream closed
    2019/01/14 16:17:42.129991 [ERR] client: registration failure: rpc error: stream closed
    2019/01/14 16:17:42.129848 [INFO] agent: shutdown complete
### Job file (if appropriate)

Tried with docker HOST mode where in it works for only one container ; while I run the second container it prompts that 4646 port is already binded and can't listen.

Please provide your inputs.

**Comment by sudhakar1983** [comment]
This setup is similar to what ECS offer. ie deploy multiple containers in a single EC2 for effective utilization.
Is this possible in Nomad ?

**Comment by dvusboy** [comment]
@sudhakar1983 That doesn't make any sense. The point of using Nomad is to drive that utilization. You shouldn't have to use that kind of scheme to achieve what you want.

**Comment by sudhakar1983** [comment]
@dvusboy Running multiple containers (in different ports obviously)single node is supported by both ECS and Kubernetes.
Just why this is not supported in Nomad

**Comment by dantoml** [comment]
👋 @sudhakar1983,

I think there's a little bit of a misunderstanding of how a Nomad Client works here. A single client process can handle running _many_ allocations on a single node, and nomad will schedule against it until it runs out of schedulable resources (e.g cpu/ram/disk/ports). So if you run a single nomad client on each machine, it should achieve what you're trying to do.

What you're currently trying to do is more analogous to running multiple `ecs-agent`'s or `kubelet`'s on a single node (which is mostly unsupported), and doing so can cause issues around scheduling dynamic ports for your actual tasks, and lots of other issues around resource contention and potential over scheduling.
I'm going to close this issue because we don't really support running multiple copies of nomad on a single node, but feel free to ask any more questions here or on the mailing list.
