### ISSUE TITLE
Template stanza: querying service fails when tag includes equals sign

### ISSUE THREAD

**Issue by eigengrau** [hashicorp/nomad#5188]
### Nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details
Ubuntu 16.04.5 LTS

### Issue
Since Traefik proxy uses K/V-structured service tags for run-time configuration and also supports using these in template expressions, I am registering some Nomad-scheduled services with tags of the form `customer=foocorp`. However, when trying to query for these tagged services inside Nomad template stanzas, task allocation will error out. IIRC, the docs mandated that service names must be valid hostnames, whereas no special requirements were imposed on tags.

### Reproduction steps

```
{{ $mysql := printf "customer=%v.%v" (env "NOMAD_META_customer_short") "mysql" }}
{{ with service $mysql }}
…
```
### Nomad Server logs (if appropriate)

```
Template: (dynamic): execute: template: :5:19: executing "" at <service $mysql>: error calling service: health.service: invalid format: "customer=acme.mysql"
```

**Comment by dantoml** [comment]
@eigengrau 👋 - I just did some digging and it looks like this is a limitation of [consultemplate](https://github.com/hashicorp/consul-template). In the `service` stanza, they validate the input against this [regex](https://github.com/hashicorp/consul-template/blob/d3b6838a3ad8c82b60b5416c733595d6db4f7ea1/dependency/catalog_service.go#L18), which requires tags to be of the format [`((?P<tag>[[:word:]\.\-\_]+)\.)?`](https://github.com/hashicorp/consul-template/blob/d3b6838a3ad8c82b60b5416c733595d6db4f7ea1/dependency/dependency.go#L21).

You could potentially add a second tag of `customer-acme` as a workaround for this?

**Comment by dantoml** [comment]
Closing this because of the above consul-template regex, and because this issue is inactive. We hope to support consul service `meta` in an upcoming release of Nomad however, which adds a key/value interface to the service definition.
