### ISSUE TITLE
the nomad auto clustering with consul not work

### ISSUE THREAD

**Issue by hackrole** [hashicorp/nomad#5218]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.6.0
### Operating system and Environment details
ubuntu 14.04 in vagrant
### Issue
the nomad auto clustering with ip 10.0.2.15 in the vargrant hosts.
but this ip was not connected between each other.
I have private ip 192.168.33.[10-12]setted, but it doesnot use it.
And I search the nomad consul config doc, it has no way to set this
### Reproduction steps
if you nomad cluster has multi ip, then there was no way to make cosul auto-clustering work

**Comment by preetapan** [comment]
@hackrole based on the information you shared above, it sounds like you need to change Nomad configs to expose a different advertise address https://www.nomadproject.io/docs/configuration/index.html#advertise so that Nomad registers to consul with that address.
