### ISSUE TITLE
device plugin not worked?

### ISSUE THREAD

**Issue by cavanwang** [hashicorp/nomad#5219]
### Nomad version
Nomad v0.9.0-dev(I git cloned from master branch)

### Operating system and Environment details
ubuntu16.04

### Issue
I am a newbie for using nomad-plugin(I know how to use nomad).

 I want to learn about using device plugin(mainly for using nvidia gpu)  by refering `https://github.com/hashicorp/nomad/tree/master/plugins/device/cmd/example`.

But I cannot guess this page said "The configuration should be passed via an HCL file that begins with a top level config stanza" is which place?  is it at nomad job file  or start nomad command's config file?

### Reproduction steps

case1:
1.  `cd plugins/device/cmd/example/cmd/`
2. `go build -buildmode=plugin`
3.  `cp cmd.so /tmp/nomad/plugins`
4. ensure nomad config:
```
{
        "datacenter": "dc1",
    "data_dir": "/tmp/nomad",
    "client": {
        "enabled": true,
        "options": {
    	    "driver.raw_exec.enable": "1"
   	}
    }
}
5. `sudo /home/cavan/gopath/chesscloud/bin/nomad agent -client -server -bootstrap-expect=1 -config ./nomad.config -log-level=DEBUG`

But the nomad error:
```
Error starting agent: failed to create plugin loader: failed to initialize plugin loader: failed to fingerprint plugins: 1 error(s) occurred:

* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

### Nomad Server logs (if appropriate)
not needed
### Nomad Client logs (if appropriate)
   not needed
### Job file (if appropriate)
not rur job file

**Comment by preetapan** [comment]
@cavanwang we are still working on documentation for device plugins, should have better examples/documentation for you sometime next week.

**Comment by cavanwang** [comment]
Thanks, expected~

**Comment by dantoml** [comment]
Hey @cavanwang - We now have beta documentation for configuring GPU devices! - Thanks for trying out 0.9 so early.

https://www.nomadproject.io/docs/devices/nvidia.html
