### ISSUE TITLE
[question] Using volume_driver "pxd" in combination with normal path mounts

### ISSUE THREAD

**Issue by mwantia** [hashicorp/nomad#5220]
Hello Everyone,

right now im trying to implement persistant storage for my docker containers via Portworx (https://portworx.com/portworx-hashicorp-nomad/).

Currently everything works great: I have Portworx set up for all my clients which are running nomad version 0.8.6 in combination with docker 18.09.0 and ubuntu server 18.04.
Im able to map a new volume via the task configuration: "name=mysqlvol,size=10,repl=3/:/var/lib/mysql" (as example) and i can use the volume under every given client.

The problem im facing right know is in order for the task to implement persistant storage i need to change the volume driver to "pxd". Unfortunately im unable to bind any configurationfiles to my jobs afterwards. For example "local/config.yaml:/etc/config/config.yaml" results in an error that the string value is not recognised and the job fails.

Is it possible to combine both options or is there some kind of different implementation/configuration i need to use?
Unfortunately the documentation between Portworx and Nomad is pretty vague so i couldnt find anything specific after googling the problem im facing

Best regards

**Comment by TheRevenantStar** [comment]
Try using the mounts config, you can set a drive on a case-by-case basis.
https://www.nomadproject.io/docs/drivers/docker.html#mounts
```
mounts = [
    {
      target = "/path/in/container"
      source = "name-of-volume"
      readonly = false
      volume_options {
        no_copy = false
        labels {
          foo = "bar"
        }
        driver_config {
          name = "pxd"
          options = {
            foo = "bar"
          }
        }
      }
    }
  ]
```

**Comment by dantoml** [comment]
@mwantia 👋 - I'm currently working on the design for nomad volume plugins, which should solve this issue in a uniform way across drivers (and will support various plugins, alongside host mounts).

In the mean time, @TheRevenantStar's suggestion of using the `mounts` configuration should serve as a workaround - please let us know if you run into any issues with getting those set up.
