### ISSUE TITLE
[Enhancement] Add telemetry for vault token renewal

### ISSUE THREAD

**Issue by mlehner616** [hashicorp/nomad#5222]
Related to GH-4817. Would it be possible to get a few metrics related to vault token renewal?

I'm mostly interested in:
- Seconds since last successful renewal
- Seconds until next renewal attempt
- Seconds until expiration
- Num of Renewal failures
- Num of Renewal attempts or successes

**Comment by jippi** [comment]
This would be hugely useful for us as well :)

**Comment by camerondavison** [comment]
I just got hit by this because 1 node did not have a valid vault token and when it became the master everything that needed vault started failing. Is there a good way to monitor this besides producing telemetry. I think this could be the easiest way to monitor it.
