### ISSUE TITLE
[question] Nomad client unable to join cluster after upgrade to consul 1.4.1

### ISSUE THREAD

**Issue by adragoset** [hashicorp/nomad#5246]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad 0.8.7
Consul 1.4.1
### Operating system and Environment details
Centos7

### Issue
Im seeing sporadic failures in my server logs after upgrading Consul to 1.4.1 from 1.2.1 and nomad from 0.8.4 to 0.8.7. 

consul.sync: failed to update services in Consul: error querying Consul checks: time: invalid duration

Additionally my upgrade nomad client cannot join the server ring. 

Here is my consul config on the client and servers

{
    "consul": {
        "address": "127.0.0.1:8501",
        "ssl": true,
        "verify_ssl": true,
        "token": "{{nomad_acl_id.ID}}",
        "ca_file": "/nomad/config/ssl/cluster-ca.pem",
        "cert_file": "/nomad/config/ssl/nomad-client.pem",
        "key_file": "/nomad/config/ssl/nomad-client-key.pem"
    }
}

### Reproduction steps
upgrade consul to 1.2.1

### Nomad Server logs (if appropriate)

Im seeing these failure lines from consul sync in my logs on my server agents 
[WARN] consul.sync: failed to update services in Consul: error querying Consul checks: time: invalid duration

### Nomad Client logs (if appropriate)

On my nomad clients im seeing
2019/01/26 00:21:08.596864 [ERR] client.consul: error discovering nomad servers: no Nomad Servers advertising service "nomad" in Consul datacenters: ["laitram-dl"]
    2019/01/26 00:21:13.075459 [WARN] manager: No servers available
    2019/01/26 00:21:13.075670 [ERR] client: failed to update allocations: no servers

**Comment by pearkes** [comment]
Hey @adragoset unfortunately this is a known issue with Consul. See https://github.com/hashicorp/consul/issues/5270 for more information. There is a 1.4.2 release planned to correct this behavior.

We recommend Consul 1.4.0 or Consul 1.3.1. Please refer to the Consul changelog for issues fixed in 1.4.1 that were present in 1.4.0 to determine if you should instead use 1.3.1.

**Comment by preetapan** [comment]
@adragoset we discovered this issue yesterday and its noted in the Changelog https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#141-january-23-2019. There will be a new release of Consul that fixes this next week. Until then we recommend that you downgrade to Consul 1.4.0

**Comment by adragoset** [comment]
Ok thanks ill perform a downgrade to 1.4.0 until a fix is release.

**Comment by sandromehic** [comment]
I just encountered the same problem and an update to 1.4.2 consul version fixed the issue.
