### ISSUE TITLE
[question] envoy deploy pattern?

### ISSUE THREAD

**Issue by jcomeaux** [hashicorp/nomad#5288]
In the Connect notes on the consul site, there's a blurb about Nomad + envoy:

> Using the Envoy Connect integration with Nomad is not currently possible following this guide. This guide relies on some features of the built-in proxy that are not possible via Envoy.

Okay, not possible with that guide, but can any one suggest a pattern that would work?  Just looking for simple pointers as I'm trying to work up a model and running into problems.

Thanks so much!

**Comment by schmichael** [comment]
Unfortunately Nomad 0.9 will not have first class Consul Connect support. Please subscribe to #4451 to be notified when that feature lands. Work has begun on it.

It is possible to use Connect with Nomad right now, but it's quite involved and has serious caveats: https://github.com/hashicorp/nomad-guides/tree/master/application-deployment/consul-connect-with-nomad

Sorry there's such a lag between Connect's release and Nomad's official support! We're working on it!
