### ISSUE TITLE
Rescheduling group header line repeated for each task group

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/nomad#5291]
### Nomad version
Nomad v0.9.0-beta2 (29a5d242e69d2db5a36cf58d975f15c279f49a7e)

### Operating system and Environment details
CentOS 7.6 1810 VM
Consul v1.4.2

### Issue
When a job fails and enters the reschedule cycle, 2 copies of the section header are present when viewing the job status via cli as shown. When the job has only 1 task group, the section header is _not_ repeated.

```
Future Rescheduling Attempts
Task Group         Eval ID   Eval Time
Task Group         Eval ID   Eval Time
xxxxx-api-nginx    01f1a134  3m40s from now
xxxxx-api-php-fpm  dc5c4eaa  3m40s from now
```

**Comment by schmichael** [comment]
Fixed. Thanks @stevenscg!
