### ISSUE TITLE
No default interface found with matching IP

### ISSUE THREAD

**Issue by mnachury** [hashicorp/nomad#5298]
### Nomad version
v0.8.7, v0.9.0-beta2

### Operating system and Environment details
Windows 10
![image](https://user-images.githubusercontent.com/23231193/52232992-f2c3e380-288b-11e9-8e74-a23056c97664.png)
All other network interface are disabeld
### Issue
![image](https://user-images.githubusercontent.com/23231193/52233128-48988b80-288c-11e9-90d8-210fb4d29d47.png)

### Reproduction steps
nomad.exe agent -dev

Might have to do with the default gateway? 
Was able to reproduce on other windows with the same gateway, did not occur on any Linux.

### Workaround
Specifying the interface in the settings, not suited for production

**Comment by angrycub** [comment]
@mnachury I think that your localized output could be causing your issue.  hashicorp/go-sockaddr uses ipconfig output to make this mapping; however, the current implementation uses string matching against the output.  I think the part that is causing this is https://github.com/hashicorp/go-sockaddr/blob/3aed17b5ee41761cc2b04f2a94c7107d428967e5/ifaddrs.go#L20 which is used to find the address for the default interface (https://github.com/hashicorp/go-sockaddr/blob/3aed17b5ee41761cc2b04f2a94c7107d428967e5/ifaddrs.go#L1274).  I've created an issues on the underlying library's repository.
