### ISSUE TITLE
Docker driver fails with nomad 0.9.0-beta2 when including a logging stanza

### ISSUE THREAD

**Issue by jsipprell** [hashicorp/nomad#5299]
### Nomad version
0.9.0-beta2 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Linux 3.10.0 x86_64 GNU/Linux

docker-ce-18.06.1

### Issue
When running a job that includes a logging stanza, the allocation fails w/ the following error:

`driver start failed: failed to decode driver config: [pos 378]: readContainerLen: Unrecognized descriptor byte: hex: 82, decimal: 130`

This issue does **not** occur w/ 0.8.7.

### Reproduction steps
Include the following stanza in a task's docker config:

```
logging {
  type = "syslog"
  config {
    tag = "sometag"
  }
}
```

**Comment by shantanugadgil** [comment]
Check: https://github.com/hashicorp/nomad/pull/5297

Maybe a duplicate???

**Comment by jsipprell** [comment]
My apologies,  you're correct, this is a duplicate.

**Comment by schmichael** [comment]
Thanks for testing @jsipprell!
