### ISSUE TITLE
Migrated allocations do not reliably have NextAllocation/PreviousAllocation set

### ISSUE THREAD

**Issue by c2nes** [hashicorp/nomad#5302]
### Nomad version

`Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)`

### Operating system and Environment details

Ubuntu 16.04, Docker 17.05

### Issue

When draining a node, migrated allocations are not reliably updated to have NextAllocation and PreviousAllocation populated on the old and new allocations respectively. I can't see any obvious pattern in the allocations which do and do not get updated correctly. In the most recent case the node had 8 allocations marked for migration, but only 5 had NextAllocation populated. All 8 allocations were otherwise successfully rescheduled on other nodes. The issue does not seem to be specific to certain jobs either. Sometimes a job will have an allocation migrated and NextAllocation populated correctly. Other times the same job can have an allocation migrated and not have NextAllocation populated.

**Comment by preetapan** [comment]
@c2nes the next time this happens could you give us json dumps of the allocations and nodes?
