### ISSUE TITLE
Nomad Job Logs Should Support Widescreen Format

### ISSUE THREAD

**Issue by cpumanaz** [hashicorp/nomad#5303]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Windows 10
Google Chrome

### Issue
Logs (stdout,stderr) should be expandable or expand out to the right edge of browser windows. Most monitors in the last 10 years have been sold in a wide-screen format, and Nomad should not wrap logs unnecessarily.

Feature Request:  Please allow for an adjustable or wider log output pane to prevent scrolling of logs and wasted space. Please see the attached image as an example of wasted space.

![image](https://user-images.githubusercontent.com/13242617/52368286-ac998c00-2a13-11e9-9ef3-8219754b307f.png)

### Reproduction steps
Open Nomad task Logs on a wide-screen monitor, observe wasted space.

**Comment by jacekjagiello** [comment]
@cpumanaz @dantoml This looks like a good first-time contribution issue. I would like to tackle this, can I start working on this?

Also, I have a few questions
- It looks like not only logs view is shrunk this way - should this change be global? I.e. other views should also be not be limited, and take the whole available width?
- If this problem only concerns large screens, maybe we should apply media-query that will make full-width logs only after the window become larger than defined constant?

**Comment by cpumanaz** [comment]
@jacekjagiello @dantoml 

Are there any current rules that could be applied for a buffer?  That the log window could have a minimum size which is the current size and will expand as the window gets larger than what is required for the minimum size.

Size: 0 –> X  (current size).
Size: X –> n (available size - buffer)

**Comment by dantoml** [comment]
Hey @jacekjagiello, I'm personally not too familiar with the Nomad UI codebase, @DingoEatingFuzz should be able to provide some pointers here though.

**Comment by DingoEatingFuzz** [comment]
Hi @jacekjagiello, this is a great idea and I'd love a contribution here.

> It looks like not only logs view is shrunk this way - should this change be global? I.e. other views should also be not be limited, and take the whole available width?

Views intentionally have a max-width set to avoid a lot of horizontal eye-scanning (especially with tables and the like that normally fit just fine within 1200px). I think the log view is an exception to this rule.

> If this problem only concerns large screens, maybe we should apply media-query that will make full-width logs only after the window become larger than defined constant?

I think we can avoid a media-query here by just making that particular page wider. I imagine it would look something like adding an `is-full-width` or `is-fluid` helper in [`core/section.scss`](https://github.com/hashicorp/nomad/blob/master/ui/app/styles/core/section.scss) and then adding that helper in the log viewer page template at [`allocations/allocation/task/logs.hbs`](https://github.com/hashicorp/nomad/blob/master/ui/app/templates/allocations/allocation/task/logs.hbs).

Thank you for digging into this!

**Comment by jacekjagiello** [comment]
@DingoEatingFuzz Thanks, I'll do PR within a few days

**Comment by cpumanaz** [comment]
@jacekjagiello How are things going with the wide-screen format?

**Comment by jacekjagiello** [comment]
@cpumanaz PR is open :relaxed:
