### ISSUE TITLE
Support Using Multiple Vaults

### ISSUE THREAD

**Issue by samart** [hashicorp/nomad#5311]
It would be useful for nomad to be able to fail over with no operator action to a secondary vault (or a list of vaults) if it has issues with the first one.

This would reduce the possibility of a vault issue taking down a nomad cluster.   

Currently, the only way to have HA is to have a Vault DR standby, but that requires a manual promotion and an extra vault cluster to manage and run.  And If not promoted in time, jobs would stop or not be able to restart.

**Comment by BrotherLavarius** [comment]
This a little bain of my existence, can we have this please?

**Comment by tgross** [comment]
The plan is to implement this via https://github.com/hashicorp/nomad/issues/15617

**Comment by tgross** [comment]
Shipped in [Nomad Enterprise 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1)
