### ISSUE TITLE
docs: job->device Stanza exists typo

### ISSUE THREAD

**Issue by cavanwang** [hashicorp/nomad#5315]
### Nomad version

Nomad v0.9.0-beta2

### Issue

I referred the docs of 'https://www.nomadproject.io/docs/job-specification/device.html'. It show an example with `constraint`: 
```
 constraint {
            attribute = "${driver.attr.memory}"
            operator  = ">="
            value     = "2 GiB"
          }
```

The `driver.attr` should be `device.attr`.

**Comment by shantanugadgil** [comment]
Hi @cavanwang ,

just in case if you want to make a pull request; the file is here:
https://github.com/hashicorp/nomad/blob/master/website/source/docs/job-specification/device.html.md

HTH,
Shantanu
