### ISSUE TITLE
Unable to detect java driver for openj9 jvm

### ISSUE THREAD

**Issue by chenjpu** [hashicorp/nomad#5316]
### Nomad version
Nomad v0.9.0-beta2

### Operating system and Environment details
 OS: centos 7.6 
JAVA:
   java -version

   openjdk version "1.8.0_192"
   OpenJDK Runtime Environment (build 1.8.0_192-b12_openj9)
   Eclipse OpenJ9 VM (build openj9-0.11.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 
   20181107_95 (JIT enabled, AOT enabled)
   OpenJ9   - 090ff9dcd
   OMR      - ea548a66
  JCL      - b5a3affe73 based on jdk8u192-b12)
### Issue
java driver Detected No

**Comment by shantanugadgil** [comment]
hi, could you give some details as to how you have captured the above output and how Nomad is being started? which user? etc.

Nomad not detecting JAVA usually indicates that the Nomad process could not find "java" in its PATH (when nomad started up)

**Comment by chenjpu** [comment]
1.Nomad start use systemd and root user
2.run `java -version` on my node ,output
   ```
    openjdk version "1.8.0_192"
    OpenJDK Runtime Environment (build 1.8.0_192-b12_openj9)
    Eclipse OpenJ9 VM (build openj9-0.11.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References
    20181107_95 (JIT enabled, AOT enabled)
    OpenJ9 - 090ff9dcd
    OMR - ea548a66
    JCL - b5a3affe73 based on jdk8u192-b12)
```

i found [parseJavaVersionOutput](https://github.com/hashicorp/nomad/blob/master/drivers/java/utils.go#L36) check length is 3,but on  my node `java -version` output lines length is 7

**Comment by chenjpu** [comment]
@shantanugadgil 
it's ok in nomad version 0.8.7, after update to 0.9.0-beta2 can not detect java driver

**Comment by notnoop** [comment]
Thanks for reporting this bug.  This definitely is a regression - looks like v0.8 nomad marked java as detected if `java -version` has zero exit code even if the output format isn't expected, unlike 0.9.0-beta2.  We should fix this.

**Comment by notnoop** [comment]
@chenjpu Thank you so much for reporting the bug.  We merged a fix that should be out in the next beta/rc release.  Would love it if you can test drive and send us any feedback.  Thanks!
