### ISSUE TITLE
Failed to elect leader in kubernetes

### ISSUE THREAD

**Issue by chngtrn** [hashicorp/nomad#5330]
I'm running nomad server in Kubernetes as statefulsets with 3 replicas and using consul. My config is below. It works great the first time ever it starts. However, if two of the 3 pods went down nomad is unable to promote a leader. For some reasons it kept the IPs of the old pods and kept on trying to elect those as leader. Why is it that nomad kept on trying to talk to the dead pods IP instead of using the new pods IP?

The only way to get nomad to work again with having a leader is to delete the statefulsets, delete the persistent volume claims, and start the statefulsets again.

Any help is greatly appreciated. Thanks.

server.hcl
```
    data_dir  = "/nomad/data"
    bind_addr = "0.0.0.0"
    region = "region1"
    datacenter = "dc1"
    leave_on_interrupt = true
    leave_on_terminate = true

    server {
      enabled = true
      bootstrap_expect = 2
      rejoin_after_leave = true
    }

    consul {
      address = "consul.consul.svc.cluster.local:8500"
      client_auto_join = true
      server_auto_join = true
    }
```
Tried it with leave_on_* and rejoin_after_leave set to false but same issue.

Rejoin error
```
    2019/02/16 03:24:51.129247 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51.192278 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51.265157 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51.308773 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51.426307 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51.461387 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2019/02/16 03:24:51 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:51 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:51 [WARN] raft: Election timeout reached, restarting election
    2019/02/16 03:24:51 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 39                                                                                                       
    2019/02/16 03:24:51 [INFO] raft: Node at 10.1.1.114:4647 [Follower] entering Follower state (Leader: "")                                                                                                       
    2019/02/16 03:24:52 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2019/02/16 03:24:52 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 41                                                                                                       
    2019/02/16 03:24:53 [WARN] raft: Election timeout reached, restarting election
    2019/02/16 03:24:53 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 42                                                                                                       
    2019/02/16 03:24:54 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:54 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:54 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:55 [WARN] raft: Election timeout reached, restarting election
    2019/02/16 03:24:55 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 43                                                                                                       
    2019/02/16 03:24:56 [WARN] raft: Election timeout reached, restarting election
    2019/02/16 03:24:56 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 44                                                                                                       
    2019/02/16 03:24:57 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:57 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.1.1.111:4647 10.1.1.111:4647}: dial tcp 10.1.1.111:4647: getsockopt: no route to host                                              
    2019/02/16 03:24:57 [WARN] raft: Election timeout reached, restarting election
    2019/02/16 03:24:57 [INFO] raft: Node at 10.1.1.114:4647 [Candidate] entering Candidate state in term 45                                                         
```
As you can see the lines with "no route to host" it's using the IPs of the dead pods. The newly created pods by Kubernetes no longer have those IPs.

**Comment by shantanugadgil** [comment]
Hi,
I have less knowledge of Kubernetes indepth specifics, but could Consul's auto join help here?

https://www.consul.io/docs/agent/cloud-auto-join.html

Thought: as long as the Consul servers can correctly detect the changed server peers, Nomad should be able to join up correctly.

Disclaimer: I could be completely wrong as well ! :O 

I will leave it to some K8S expert to comment as well.

**Comment by chngtrn** [comment]
Thanks @shantanugadgil but I think that link is about how consul instances joining each other in the cluster. My issue is with nomad instances trying to join the cluster using consul for auto discovery.

**Comment by shantanugadgil** [comment]
Right, thats correct, Nomad doesn't seem to have the k8s provider yet.

What I was thinking was that the Nomad servers would be doing an auto bootstrapping using Consul and maybe that could have helped
Ref:
https://www.nomadproject.io/guides/operations/cluster/automatic.html

**Comment by chngtrn** [comment]
As I mentioned above. I have both consul and nomad installed on same k8s cluster and upon first starting nomad it works fine. The problem only happen when 2 out of 3 nomad servers leaves the cluster that made nomad going into a cluster join loop I described above.

**Comment by notnoop** [comment]
@chngtrn Thanks for reaching out.  This is the expected behavior when a majority of the servers become unavailable, as Nomad requires a quorum to operate.  With a cluster of 3 pods, you can only tolerate a single pod failure; and cluster becomes inoperable if two are down - check the [Consensus Protocol table](https://www.nomadproject.io/docs/internals/consensus.html#deployment-table) for info about the and quorum, failure tolerance.

To give an intuition, the single remaining server cannot distinguish between the other two servers being truly down, or simply that it got disconnected from them and they are operating just fine, in which case, the disconnected server shouldn't attempt leadership or perform any actions and violating consistency guarantees.  When the cluster is inoperable, all actions are prohibited, including adding new servers.

>       bootstrap_expect = 2

I would discourage this option.  You should set the value for the expected number of servers you expect; generally 3 or 5.  Setting the expected bootstrap to less the number of servers you expect, risks getting the cluster inoperable while mid bootstraping.

**Comment by chngtrn** [comment]
@notnoop Thanks for the clarification. One question is are the data stored in nomad of any importance? Can they be deleted without needing a backup? I'm trying to find the best solution to our problem.

Thanks,

**Comment by notnoop** [comment]
I would recommend reading the [Outage Recovery](https://www.nomadproject.io/guides/operations/outage.html) doc.

The data stored in nomad is significant, as they contain all the jobs/services and their state.  Losing the data would require recreation of the cluster and resubmitting all the jobs.  However, traditional backup storage isn't well suited for Nomad; e.g. restoring yesterdays jobs wouldn't be useful in many contexts.

Thus we recommend building enough failure tolerance in your servers setup to avoid complete outages; and in case of complete outages, attempting to use the persistent data rather than use backups.

**Comment by chngtrn** [comment]
Thanks @notnoop.
