### ISSUE TITLE
Nomad client won't leave cluster

### ISSUE THREAD

**Issue by chngtrn** [hashicorp/nomad#5333]
UPDATE: This happens even if not running as container in docker or k8s. I've setup 3 boxes as VMs and the behavior is the same.

### Nomad version
0.8.3

### Operating system and Environment details
Container in Kubernetes
Container URL: https://hub.docker.com/r/djenriquez/nomad/dockerfile

### Issue
Nomad clients would stay in the cluster even though the pod is gone.

### Client config.hcl
```
data_dir  = "/nomad/data"
bind_addr = "0.0.0.0"
region = "region1"
datacenter = "dc1"
leave_on_interrupt = true
leave_on_terminate = true

client {
  enabled = true
}

consul {
  address = "consul.consul.svc.cluster.local:8500"
  checks_use_advertise = true
}
```

### Kubernetes pod listing
```
$ kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
nomad-client-5886cd57f-d6jj2   1/1     Running   0          12m
nomad-client-5886cd57f-dj7xg   1/1     Running   0          12m
```

### Client node status output
```
$ nomad node status
ID        DC   Name                          Class   Drain  Eligibility  Status
b2d7849e  tr1  nomad-client-5886cd57f-d6jj2  <none>  false  eligible     ready
9b059b77  tr1  nomad-client-5886cd57f-dj7xg  <none>  false  eligible     ready
bad6f18e  tr1  nomad-client-5886cd57f-dp99c  <none>  false  eligible     ready
f084a5fc  tr1  nomad-client-5886cd57f-8g588  <none>  false  eligible     ready
```

As you can see from the k8s pod listing that the there are only two pods running but in the node status list there are 4. The bottom two are gone but nomad doesn't release it.

I went through all the configuration in the documentation but nothing seems to work. Please give me some advice. 

Thanks,

**Comment by shantanugadgil** [comment]
Hi, any specific reason you are using an older version and not the latest GA (0.8.7) ?

**Comment by chngtrn** [comment]
@shantanugadgil The container is built with that version. The author hasn't built with the newest version. I'll give the GC setting a try. Thanks.

**Comment by preetapan** [comment]
@chngtrn Theres a small hearbeat period (typically 30 seconds) after which a killed client node should transition from `ready` to `lost`. If you are not seeing that, perhaps the process is still running. Could you confirm that the nomad client process actually died?

**Comment by chngtrn** [comment]
Please close this issue as it’s not relevant to me anymore. Thanks for choking on.
