### ISSUE TITLE
port advertise in driver exec

### ISSUE THREAD

**Issue by FlankMiao** [hashicorp/nomad#5340]
### Nomad version
0.9.0-beta

### Operating system and Environment details
centos 7.6.1810
### Issue

job port advertise in driver "exec".
can not  advertise the port in a job with driver "exec", like in driver "docker" [port_map].
my job listen on port: 8080, and nomad allocate a port, such as 26473.
It,s ok to access "ip:8080/ping", but "ip:16473/ping" is unaccessable, also the health check.
So can I map port 8080 and 26473?
I didn’t find it in the doc

**Comment by schmichael** [comment]
Hi @FlankMiao,

The `exec` driver uses the host network, so there is no `port_map` stanza like Docker. Your task is able to listen on any port, but you may get port conflicts if you use some port other than the one Nomad assigns.

Use the `${NOMAD_PORT_<label>}` interpolation variable in your task configuration to listen on the port Nomad has assigned:

```hcl
      driver = "exec"
      config {
        command = "/usr/bin/socat"
        args    = ["-v", "pipe", "tcp-listen:${NOMAD_PORT_echo1},reuseaddr,fork"]
      }
```

If you want Nomad to assign a static port and a dynamic port to the task then use a resource stanza like:

```hcl
      resources {
        cpu    = 1000
        memory = 256
        network {
          mbits = 10
          port "echo1" {
            static = 9999
          }
         port "echo2" {}
        }
      }
```

https://www.nomadproject.io/guides/operating-a-job/configuring-tasks.html contains a full example.

I hope this helps! Please feel free to reopen

**Comment by FlankMiao** [comment]
@schmichael  thanks a lot. :)
