### ISSUE TITLE
HTTP API set artifact use absolute path

### ISSUE THREAD

**Issue by upccup** [hashicorp/nomad#5361]
hi guys:

now the definition of TaskArtifact nomad HTTP API is
```
type TaskArtifact struct {
	GetterSource  *string           `mapstructure:"source"`
	GetterOptions map[string]string `mapstructure:"options"`
	GetterMode    *string           `mapstructure:"mode"`
	RelativeDest  *string           `mapstructure:"destination"`
}
```
the destination field is **RelativeDest**.

How can id set to use absolute destination.

**Comment by cgbaker** [comment]
hi @upccup , officially, we only support using relative paths. the [documentation](https://www.nomadproject.io/docs/job-specification/artifact.html) on this could be clearer, and there are some unsupported driver-specific approaches that allow absolute paths. however, in general, and with a view towards compatibility in the future, only paths relative to the root of the task's directory are supported.
