### ISSUE TITLE
[question] Error submitting job: Put http://127.0.0.1:4646/v1/jobs: dial tcp 127.0.0.1:4646: connect: connection refused

### ISSUE THREAD

**Issue by zhangslob** [hashicorp/nomad#5374]
I read the [getting-started](https://www.nomadproject.io/intro/getting-started/jobs.html#running-a-job), and command  `nomad job run example.nomad`, it comes out:
```bash
Error submitting job: Put http://127.0.0.1:4646/v1/jobs: dial tcp 127.0.0.1:4646: connect: connection refused
```
I have run `nomad job init`,  and `example.nomad` exists

My nomad version is 0.8.6, I've try 0.8.7 but failed!
```bash
➜  tmp nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b)
```

**Comment by preetapan** [comment]
@zhangslob are you running the nomad agent? https://www.nomadproject.io/intro/getting-started/running.html#starting-the-agent

**Comment by zhangslob** [comment]
@preetapan Thx, i'm so stupid
