### ISSUE TITLE
Container Storage Interface Support

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#5378]
## Summary
Introduce support for using [Container Storage Interface](http://github.com/container-storage-interface/spec) plugins in Nomad to allow operators to provide persistent storage to jobs.  This will allow people to run stateful services in Nomad across various task drivers and environments.

**Comment by minhdanh** [comment]
Hi @endocrimes,
What is the status of this issue?

**Comment by endocrimes** [comment]
@minhdanh We're actively working on designing support for this now :)

**Comment by miglia6** [comment]
do you have a release plan for this plugin ?

**Comment by cricket007** [comment]
https://www.hashicorp.com/blog/announcing-hashicorp-nomad-0-11-beta/

**Comment by tgross** [comment]
Thanks @cricket007! Looks like we forgot to close this one!
