### ISSUE TITLE
NOMAD_HOSTNAME env var

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#538]
Hi,
I think it is useful to have this NOMAD_HOSTNAME env var imported into the Docker containers.
Use case example: a log shipper or a message broker so you can attach the name of the host where the container is running into a "hostname" field.

What do you think? can you make it possible guys? :)
Thank you.

**Comment by diptanu** [comment]
@poll0rz We have decided to do this in a generic way

So using the env block you will be able to reference Environment Variables that the Nomad client knows about - 

```
env {
   NOMAD_HOST=$HOSTNAME
}
```

So if the Host name environment variable was set in the environment of the Nomad client an user can inject it in his job.

That way you can inject any arbitrary environment variable without Nomad core changing. This is also useful in AWS, where you might want to inject the Region, Zone, Ec2 instance id etc.

**Comment by diptanu** [comment]
#448 should be fixed with this

**Comment by poll0rz** [comment]
hellyeah, this way we can pass a lot of useful info to the task, not only the hostname.
really niiiice approach, thank you!!!
