### ISSUE TITLE
Nomad validate configuration command

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#5385]
### Nomad version
Output from `0.8.7`:

```
$ nomad validate
This command takes one argument: <path>
For additional help try 'nomad job validate -help'

$ nomad job validate -help
Usage: nomad job validate [options] <path>
Alias: nomad validate

  Checks if a given HCL job file has a valid specification. This can be used to
  check for any syntax errors or validation problems with a job.

  If the supplied path is "-", the jobfile is read from stdin. Otherwise
  it is read from the file at the supplied path or downloaded and
  read from URL specified.
```

### Issue

With consul I use `consul validate` a whole lot for when we build Packer images, and it has saves me some headaches when I didn't write a valid configuration file.

https://www.consul.io/docs/commands/validate.html

I wonder why no such thing seem to exist for Nomad. 

I would like to be able to run `nomad validate /etc/nomad.d/` to verify everything looks correct when I am baking our images.

**Comment by preetapan** [comment]
@kaspergrubbe Thanks for the suggestion.

The more common case is job file validation, so rather than use that `nomad validate` alias for config file validation would be done as `nomad config validate`

We will track this in our backlog; however, competing priorities means we are unlikely to get to it very soon. If you would like to work with us in writing a PR for this let us know, we can provide guidance here on how to go about it.

**Comment by gabrieltz** [comment]
I'm sorry to bother you again, but it would really help to have an option to validate the agent and server config before restarting it after some major editing. It would also prevent all those mini heart-attacks when restarting a service doesn't go as planned :)

Thank you

**Comment by maxadamo** [comment]
Job validation is perhaps less important because wrong jobs won't bring the whole agent down.

**Comment by nergdron** [comment]
maybe not, but it will bring down a CI/CD pipeline pretty quick. ideally we'd have a way to do both, but I'd definitely prefer config over job validation if we have to choose.

**Comment by jrasell** [comment]
@nergdron the Nomad CLI already contains a [nomad job validate](https://www.nomadproject.io/docs/commands/job/validate) command which I believe will solve your use case for parsing and validating job specification within CI/CD pipelines.

**Comment by nergdron** [comment]
@jrasell yep, I'm aware. but like I stated, I'm far more interested in what this ticket is about, a command to validate nomad's daemon config.

**Comment by maxadamo** [comment]
I see now that `nomad config validate ...` is available, and perhaps the ticket can be closed. 
It must be noted that this validator doesn't detect all the possible issues that could prevent the host from starting up.

**Comment by nergdron** [comment]
this is great news. I would think this is sufficient to close this ticket as well, and then deficiencies in that validation can be handled as new bugs to that functionality.
