### ISSUE TITLE
NOMAD_MAPPED_PORT_name env var

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#539]
Hi,
When allocating a dynamic port with:
```
port_map {
    db = 6379
}
```
Inside the Docker container provisioned, there is an env var available `NOMAD_PORT_db=6379`. This is OK in services like Redis, but in some applications (see Kafka or Akka clusters) there are some fine-grained configurations like "advertised port". This must match the dynamic port that was allocated/mapped in the host where the container is running on. This may be the result, inside the container:
```
NOMAD_PORT_db=6379
NOMAD_MAPPED_PORT_db=58246
```

Could you please make this possible?
Thank you.

**Comment by poll0rz** [comment]
btw, if anyone is having the same problem, 2 easy workarounds while the issue is evaluated:
- using `network_mode="host"`
- allocating a `static` port

**Comment by diptanu** [comment]
@poll0rz Yes we should definitely do this.

**Comment by diptanu** [comment]
I think we should do this for exec based drivers too.

**Comment by poll0rz** [comment]
@diptanu great, thank you!

**Comment by dadgar** [comment]
This exists in Nomad 0.3 and up.
