### ISSUE TITLE
Cannot enable `raw_exec` plugin with new syntax

### ISSUE THREAD

**Issue by danbst** [hashicorp/nomad#5390]
### Nomad version
Output from `nomad version`

Nomad v0.8.7

### Operating system and Environment details
Ubuntu 18.04.2

### Issue
Cannot enable `raw_exec` using recommended method (https://www.nomadproject.io/docs/drivers/raw_exec.html). Tried HCL and JSON syntax (latter is preferred)

As a workaround, I'm using "deprecated" method.

### Reproduction steps
```
# cat /root/nomad-agent-plugins.hcl
plugin "raw_exec" {
  config {
    enable = true
  }
}
# nomad agent -config /root/nomad-agent-plugins.hcl
==> Error loading configuration from /root/nomad-agent-plugins.hcl: Error loading /root/nomad-agent-plugins.hcl: error parsing 'config': 1 error(s) occurred:

* config: invalid key: plugin
```

**Comment by angrycub** [comment]
You will need to use the legacy syntax for enabling raw_exec in 0.8.7.  The "deprecated" note indicates that the pre-0.9 version of the configuration will work for  v0.9.0, but will be removed in future versions in favor of the plugin stanza. 

For versions before 0.9.0, you should continue using the legacy configuration.

I will see if we can clarify that further in the documentation.

**Comment by danbst** [comment]
yeah, a note in docs which version is change effective at would be awesome!
