### ISSUE TITLE
[question] Use nvidia runtime in a job

### ISSUE THREAD

**Issue by ilyaiqoqo** [hashicorp/nomad#5398]
I am trying to use nvidia runtime for nomad task but i havn't figured how to specify it in the job stanza.
The work around we are using right now is to add `"default-runtime": "nvidia",` to `/etc/docker/daemon.json`.

i wonder if there is a nomad way of specifying the runtime per task?

**Comment by cgbaker** [comment]
Which version of Nomad are you using? There is support for Nvidia GPUs using the device plugin capability in 0.9.0: https://www.nomadproject.io/docs/devices/nvidia.html

**Comment by ilyaiqoqo** [comment]
i use 0.9.0-beta3

**Comment by ilyaiqoqo** [comment]
actually i think the plugin isn't `nvidia-gpu` isn't enabled.
```plugin "nvidia-gpu" {
  config {
    ignored_gpu_ids = ["GPU-fef8089b", "GPU-ac81e44d"]
    fingerprint_period = "1m"
  }
}```

**Comment by ilyaiqoqo** [comment]
I found the problem in my setup, NVM thank for your time

**Comment by maaft** [comment]
Could you please share your solution?
