### ISSUE TITLE
chroot_env and files (not directories)

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5414]
Are bind-mounting files supported in the Exec driver with `chroot_env`?

Nomad version: 0.9-beta2 + local patches

Use-case: I'm trying to get `/etc/resolve.conf` populated from somewhere in the Exec runC containers -- currently I end up with 0-byte entries for things like `/etc/hosts` and `/etc/resolve.conf` in the containers.

**Comment by prologic** [comment]
This *might* be somewhat related to #5351 (*UNIX domain sockets are files too*).

**Comment by prologic** [comment]
To answer my own question; No this is not supported according to the [source code](https://github.com/hashicorp/nomad/blob/master/client/allocdir/task_dir.go#L187-L193)

Can we add this? Would you accept a PR that does?

**Comment by dantoml** [comment]
Hey!

We currently handle single files earlier in the `embedDirs` function here: https://github.com/hashicorp/nomad/blob/master/client/allocdir/task_dir.go#L159-L172, which gets either hardlinked or copied here: https://github.com/hashicorp/nomad/blob/master/client/allocdir/fs_unix.go#L84-L99.

Could you share some more information about your environment so that we can try to reproduce this?

**Comment by prologic** [comment]
I will create and post a reproducer tomorrow. Thanks  for pointing me to the code! (*I  missed this*)

**Comment by prologic** [comment]
I apologise; I have re-checked and re-confirmed. This is my mistake and it was a bug on our end.

Our Artefact(s) had a 0-byte `/etc/resolv.conf` and our packaging tool had a bug/typo where I wasn't correctly excluding `etc/resolv.conf` when creating our tarballs for Nomad's Artefact via go-getter to consume and populate the allocation.

This resulted in a 0-byte `/etc/resolv.conf` in the Exec allocation chroot despite *trying* to bind mount a `/etc/resolv.conf` from the host.

One thing I have noticed however in my testing/validation; is that bind mounted files/dirs from the host into the container/chroot seem to be read/write. is this intentional? Is there any way to bind mount read/only?

**Comment by dantoml** [comment]
No problem @prologic - those are always 'interesting' to find, glad you managed to figure it out.

With `chroot_env` we mount resources with the same permissions they have on the host, but #5377  will allow for creating host mounts with different permissions models (outside of chroot_env).
