### ISSUE TITLE
Docker gelf logging driver causes infinite loop of error logs in 0.9-beta3

### ISSUE THREAD

**Issue by ed-alertedh** [hashicorp/nomad#5418]
### Nomad version
Nomad v0.9.0-beta3 (2f55f78)

### Operating system and Environment details
Ubuntu 16.04.5 LTS (amd64)
Docker version 18.09.3, build 774a1f4

### Issue
The new logging code tries to pull logs out of the docker container indefinitely but does not account for the fact that note all docker logging drivers suppport this operation, as per https://docs.docker.com/engine/api/v1.23/ :
```
GET CONTAINER LOGS
GET /containers/(id or name)/logs

Get stdout and stderr logs from the container id

Note: This endpoint works only for containers with the json-file or journald logging drivers."
```
The result is that our syslog fills up with error messages. We have not enabled syslog in our client config so this may be an additional bug. 

Offending line of code is here: https://github.com/hashicorp/nomad/blob/2b54e2e0a9e3570270e116bb1fbbf502b527bd42/drivers/docker/docklog/docker_logger.go#L98

### Reproduction steps
Run a job with the docker driver and gelf logging.

Our client config template looks like this, unsure what is enabling syslog in this, perhaps the debug flag?
```
# /etc/nomad.d/nomad_config.hcl
data_dir  = "/opt/nomad/data"
client {
  node_class       = "{{ node_class }}"
  enabled          = true

  options {
    docker.privileged.enabled = "{{ enable_privileged_docker }}"
  }

  meta {
  }
}
consul {
  server_service_name = "nomad"
  server_auto_join = true
  client_service_name = "nomad-client"
  client_auto_join = true
  auto_advertise = true
  address = "127.0.0.1:8500"
}
region     = "{{ region }}"
datacenter = "{{ datacenter }}"
log_level  = "DEBUG"
enable_debug = true
vault {
  enabled     = true
  address     = "https://vault.service.consul:8200"
  tls_skip_verify = true
  #ca_path     = "/etc/certs/ca"
  #cert_file   = "/var/certs/nomad.crt"
  #key_file    = "/var/certs/nomad.key"
}
```

### Nomad Client logs (if appropriate)
These two lines are repeated indefinitely in syslog:
```
Mar 14 00:17:11 ip-10-142-11-122 nomad[1168]:     2019-03-14T00:17:11.123Z [ERROR] client.driver_mgr.docker.docker_logger.nomad: Log streaming ended with error: driver=docker @module=docker_logger error="API error (501): configured logging driver does not support reading" timestamp=2019-03-14T00:17:11.123Z
Mar 14 00:17:11 ip-10-142-11-122 dockerd[1209]: time="2019-03-14T00:17:11.125237979Z" level=error msg="Handler for GET /containers/49707372ef7d2663aca0bd3b0df2531133d75bbb39dbb3cfee07f69c8a13e5da/logs returned error: configured logging driver does not support reading"
```

### Job file (if appropriate)
This is the logging stanza we are using for most of our containers.
```
logging {
                    type = "gelf"
                    config {
                        gelf-address="udp://gelf.logstash.service.consul:12201"
                        mode="non-blocking"
                        max-buffer-size="4m"
                        tag="frontend-nginx"
                    }
                }
```

**Comment by cgbaker** [comment]
thanks, @ed-alertedh ... i just happened to run into this today while testing the docker `awslogs` logging driver. i've verified this and will file an internal issue for remediation.
