### ISSUE TITLE
TLS handshake error from <host>:<port>: tls: no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by xbglowx** [hashicorp/nomad#5432]
### Nomad version
```
nomad --version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)
```

### Operating system and Environment details
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

### Issue
AWS ELB heathcheck fails since TLS handshake can't be completed, even if all available cipher suite options on the ELB are selected. 

A tcpdump [nomad.pcap.txt](https://github.com/hashicorp/nomad/files/2975507/nomad.pcap.txt)
 from one of the listeners (Nomad master) shows that the ELB supports cipher suites that overlap with Nomad but a handshake failure still occurs:

   * ![Screen Shot 2019-03-17 at 10 56 15 AM](https://user-images.githubusercontent.com/1020898/54495688-58e85100-48a3-11e9-9c74-7c36bd88387b.png)
   * https://www.nomadproject.io/docs/configuration/tls.html#tls_cipher_suites

The last known version of Nomad where this worked was 0.8.3.

### Reproduction steps
Configure AWS ELB with Nomad masters as listeners on port 4646 using HTTPS and healthcheck with ping target of `HTTPS:4646/v1/status/leader`

### Nomad Server logs (if appropriate)
```
Mar 17 17:45:21 ip-10-137-8-224 nomad[763]:     2019/03/17 17:45:21.151054 http: TLS handshake error from 10.137.2.9:51658: tls: no cipher suite supported by both client and server
```

`10.137.2.9` is an ELB IP.

**Comment by xbglowx** [comment]
`even if all available cipher suite options on the ELB are selected.`

Just realized that my changes to `ELB security policy` had no affect on the heathcheck between the ELB and Nomad master: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies

**Comment by notnoop** [comment]
Thank you @xbglowx for reporting this - I'll investigate this one this week and report back with any findings!

**Comment by xbglowx** [comment]
Hi @notnoop,

I just did a Nomad config change by adding one of the ELB cipher suites (`tls_cipher_suites = "TLS_RSA_WITH_AES_256_GCM_SHA384"`) and it worked. I guess I quickly thought that there was overlap of the ELB defaults and Nomad defaults, since names look so similar.

How did the default list of Nomad cipher suites come about after 0.8.3 release?

**Comment by notnoop** [comment]
Great!  I'm glad you are unblocked.  You identified the right workaround.

The issue is that in Nomad 0.8.4, we restricted the default tls cipher suites to ones reommended by Mozilla modern server-side tls cipher suites[1] by default [2].

Upon inspection, the AWS ELB client currently supports only 29 ciphers that don't overlap with our chosen modern cipher selection.

The suggested solution for now is to specify any of the ELB supported ones in `tls_cipher_suites` setting.  We'll evaluate the cipher suites and add some sensible cipher suite in a future release.

For information, the cipher suites used by ELB client are:
```
Cipher Suites (29 suites):
  TLS_RSA_WITH_AES_256_GCM_SHA384
  TLS_RSA_WITH_AES_256_CBC_SHA256
  TLS_RSA_WITH_AES_256_CBC_SHA
  TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
  TLS_RSA_WITH_AES_128_GCM_SHA256
  TLS_RSA_WITH_AES_128_CBC_SHA256
  TLS_RSA_WITH_AES_128_CBC_SHA
  TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
  TLS_RSA_WITH_RC4_128_SHA
  TLS_RSA_WITH_3DES_EDE_CBC_SHA
  TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
  TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
  TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
  TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
  TLS_DHE_RSA_WITH_AES_256_CBC_SHA
  TLS_DHE_DSS_WITH_AES_256_CBC_SHA
  TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
  TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA
  TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
  TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
  TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
  TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
  TLS_DHE_RSA_WITH_AES_128_CBC_SHA
  TLS_DHE_DSS_WITH_AES_128_CBC_SHA
  TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
  TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA
  TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
  TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
  TLS_EMPTY_RENEGOTIATION_INFO_SCSV
```

[1] https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
[2] https://github.com/hashicorp/nomad/blob/v0.8.4/helper/tlsutil/config.go#L44-L56

**Comment by xbglowx** [comment]
@notnoop  how does one add more than just one cipher suite to the nomad config (`tls_cipher_suites`). The [docs](https://www.nomadproject.io/docs/configuration/tls.html#tls_cipher_suites) say it should take a list of strings, but when I try that, I get an error?

Config: 

```
tls_cipher_suites = ["TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_256_CBC_SHA256"]
```

Error:

```
Mar 19 17:44:12 ip-10-137-8-224 nomad[32725]: ==> Error loading configuration from /etc/nomad/nomad.d: Error loading /etc/nomad/nomad.d/tls.hcl: error parsing 'config': tls -> 1 error(s) decoding:
Mar 19 17:44:12 ip-10-137-8-224 nomad[32725]: * 'tls_cipher_suites' expected type 'string', got unconvertible type '[]interface {}'
```

**Comment by xbglowx** [comment]
The recommended servier-side cipher suites from Mozilla mentions:

```
For services that don't need backward compatibility, the parameters below provide a higher level of security
```

I got a feeling that Nomad should not use this list exclusively just yet, since it needs to be backward compatible for older clients, i.e. ELBs.

**Comment by notnoop** [comment]
@xbglowx you can use a comma separated string, like:

```
tls_cipher_suites = "TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256"
```

https://github.com/hashicorp/nomad/pull/5441 fixes this doc discrepancy, sorry about that!

**Comment by xbglowx** [comment]
@notnoop thanks for fixing the docs.
