### ISSUE TITLE
[question] Rolling Deploys and -1 vs +1 on scale

### ISSUE THREAD

**Issue by giuseppe7** [hashicorp/nomad#5440]
My apologies if this is not the preferred location for question. Could you provide the reasoning as to why the rolling deploys would diminish capacity by N instead of increase capacity by N?  If I were to run a small cluster of `foo` with 5 instances, doing the rolling deploy with max_parallel of 1 would still leave me diminished by 20% at first, where both tear down (which is quick) happens before start up (which is slow) occurs. Wouldn't it be safer to start with 5 + 1new?

**Comment by pznamensky** [comment]
It leads to another problem in cases when you're deploying tasks which can't start because of failed code in container or similar. In this case, after several deploys, it would be no running instances at all.
I'm voting for increasing capacity at deploy.

**Comment by notnoop** [comment]
Good question.  Rolling deploys is currently designed to roll out services without requiring additional cluster capacity.

We recommend using canaries when upgrading new code to be inspected, and canaries use surge capacity in addition to the main, and when promoting them, you should have the expected number of services running at all times, and we intend to improve that flow with automatic canary promotion as part of #3636.  This approach should give your desired behavior.
