### ISSUE TITLE
Go11Modules go.mod?

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5444]
How are you guys managing dependencies? I see a `vendor/` directory but nothing managing it? Would you accept a PR that adds a `go.mod` and `go.sum` based off of what's currently in `vendor/`?

**Comment by notnoop** [comment]
Thanks @prologic for the offer.  As you have figured out already, we are currently using [govendor](https://github.com/kardianos/govendor).

We intend to switch to using `go mod` after releasing 0.9, and there is an ongoing effort to adopt go modules across the HashiCorp organization.  Our initial research pointed to few trade-offs in setting nomad repo as a single module; e.g. needing to have `/api` package as a separate module, and potentially extracting plugins/drivers potentially from repo.  Simple conversion of `vendor/` into go mod wouldn't be an acceptable solution at this time.

Keep an eye for adoption of go mod after 0.9.0 ships.

**Comment by Xuanwo** [comment]
@notnoop It's going to release 0.10 for now, and go 1.13 with modules enabled by default released. Is there any roadmap for nomad to migrate to go mod? I'm developing a nomad plugin and vendor troubled me a lot.

**Comment by notnoop** [comment]
@Xuanwo Thanks for reaching out.  We do plan to ease developing plugins with go mod against nomad as it's go mod is the way to go now.  We are researching what's involved and will figure out what to do.

**Comment by ThomasObenaus** [comment]
Hi @notnoop,
I'd like to move to go mod with my project, but at the moment I'm kind of blocked since nomad does not support go mod currently.
Do you have an update about the progress for the migration of nomad to go modules?

**Comment by schmichael** [comment]
Reopening as we're actively working on switching to Go modules.

**Comment by notnoop** [comment]
Closing this issue now as we are using go mod for 1.12.
