### ISSUE TITLE
Creating release binaries?

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5447]
I'm trying to cross-compile a fairly recent version of master (*actually [this branch](https://github.com/prologic/nomad/tree/update_go-getter) which I have #5446 up for*) using the `prerelease` and `release` targets in your [GNUMakefile](/GNUMakefile) as per documentation.

This doesn't work however:

```#!bash
james@Jamess-MacBook-Pro
Wed Mar 20 15:27:27
~/go/src/github.com/hashicorp/nomad
 (update_go-getter) 2
$ make prerelease && make release
==> Linting source code...
client/allocrunner/taskrunner/task_runner_test.go:713:27:warning: unnecessary conversion (unconvert)
command/agent/config_test.go:987:35:warning: unnecessary conversion (unconvert)
command/agent/config_test.go:946:35:warning: unnecessary conversion (unconvert)
command/agent/config_test.go:926:35:warning: unnecessary conversion (unconvert)
command/agent/config_test.go:905:35:warning: unnecessary conversion (unconvert)
command/agent/config_test.go:965:35:warning: unnecessary conversion (unconvert)
drivers/shared/executor/executor_test.go:230:35:warning: unnecessary conversion (unconvert)
drivers/shared/executor/executor_test.go:144:36:warning: unnecessary conversion (unconvert)
nomad/autopilot_test.go:222:29:warning: unnecessary conversion (unconvert)
nomad/stats_fetcher_test.go:71:34:warning: unnecessary conversion (unconvert)
nomad/stats_fetcher_test.go:72:48:warning: unnecessary conversion (unconvert)
scheduler/generic_sched_test.go:625:22:warning: unnecessary conversion (unconvert)
make: *** [check] Error 1
```

What am I doing wrong? Is this failing because of the linter warnings? Have we merged code that doesn't pass the linter checks in the `prerelease` target?

**Comment by notnoop** [comment]
That's odd and it doesn't match our "Linting source code" experience in CI: e.g. https://travis-ci.org/hashicorp/nomad/jobs/508879932 .  It's curious that all warnings are related to test files and I wonder if there is a configuration difference in there.

I'll look into this when I get a chance.
