### ISSUE TITLE
ECR Repo Issue: Credentials not found in native keychain

### ISSUE THREAD

**Issue by cudacoder** [hashicorp/nomad#5453]
### Nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details
Ubuntu 16.04.6 LTS

### Issue
Nomad seems to acknowledge the `config.json` file, but the error is nothing like any of the others that were reported, please see Nomad Client error below.
Manual pull in server works as expected:
`docker pull <XYZ>.dkr.ecr.eu-west-1.amazonaws.com/wp-app:latest`

### Reproduction steps
Docker config (`/etc/docker/config.json`):
```
{
    "credHelpers": {
        "<XYZ>.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login"
    }
}
```
Configure the Nomad client to use a helper:
```
client {
  enabled   = true
  options   = {
    "docker.auth.config"     = "/etc/docker/config.json"
  }
```

### Nomad Client logs
```
failed to initialize task "wp-app" for alloc "515a4b00...": Failed to find docker auth for repo "<XYZ>.dkr.ecr.eu-west-1.amazonaws.com/wp-app": docker-credential-ecr-login with input "<XYZ>.dkr.ecr.eu-west-1.amazonaws.com/wp-app" failed with stderr: credentials not found in native keychain
```

### Job file
```
job "wp-app" {
  type = "service"
  datacenters = [
    "dc1"
  ]
  group "web" {
    task "wp" {
      driver = "docker"
      config {
        image = "<XYZ>.dkr.ecr.eu-west-1.amazonaws.com/wp-app:latest"
        port_map
        {
          http = 80
        }
      }
      resources {
        network {
          port "http"
          {
            static = "80"
          }
        }
      }
    }
  }
}
```

**Comment by notnoop** [comment]
The error seems to indicate that `docker-credential-ecr-login` is failing to retrieve credentials.  Seeing that it works when testing interactively but not with Nomad, I'd ask to confirm that the AWS profile and credentials is set for the user launching nomad and/or nomad process is started with AWS environment variables set.

**Comment by cudacoder** [comment]
Thanks for the reply @notnoop , as a workaround I have started the Nomad service with the following environment variables (`/etc/systemd/system/nomad.service`):
```
[Service]
Environment=AWS_ACCESS_KEY_ID=<secret>
Environment=AWS_SECRET_ACCESS_KEY=<secret>
Environment=AWS_DEFAULT_REGION=eu-west-1
User=vagrant
Restart=on-failure
ExecStart=/usr/bin/nomad agent -config="/etc/nomad.d/"
ExecReload=/bin/kill -HUP
```

Now, this of course works, I was just hoping I could accomplish the same *without* writing them as environment variables, and instead use the default `~/.aws/credentials` file that the AWS CLI uses, is that possible in any way?
