### ISSUE TITLE
[question] Using environment variables from another group

### ISSUE THREAD

**Issue by john-lay** [hashicorp/nomad#5455]
I have a job with a number of groups and would like to reference a `NOMAD_ADDR...` from another group.

The variable that I think should contain the information I want, is not bound.

I have read the [documentation](https://www.nomadproject.io/docs/runtime/environment.html) for runtime environment variables, and I thought you could use `NOMAD_ADDR_<task>_<label>` to reference ports within the same task group, and `NOMAD_ADDR_<label>` to reference ports anywhere else in the job. 

But I believe this assumption may be incorrect and `NOMAD_ADDR_<label>` only allows you to reference ports within the same task.

Here's a cut down example of my HCL. 

```
job "myjob" {
  group "db" {
    task "postgresql" {
      config {
        image = "bitnami/postgresql:11.1.0"
        network_mode = "bridge"
        port_map {
          psqlport = 5432
        }
      }

      resources {
        network {
          mbits = 100
          port "psqlport" {}
        }
      }
    }
  }

  group "service" {

    task "foo" {
      driver = "java"

      config {
        jvm_options = [
          "-Ddb.url=jdbc:postgresql://${NOMAD_ADDR_psqlport}/database?user=xxx&password=xxx"
        ]
      }
    }
  }
}
```

The variable `NOMAD_ADDR_psqlport` should be interpreted as the host and port of the _postgresql_ task in the _db_ group, but it doesn't.

### Nomad version
0.8.7

### Operating system and Environment details
uname -a
Linux odin 5.0.1-arch1-1-ARCH 1 SMP PREEMPT Sun Mar 10 10:55:53 UTC 2019 x86_64 GNU/Linux

**Comment by notnoop** [comment]
`NOMAD_ADDR_<label>` for a task is defined only for that tasks' ports, not any other task or task group.  For your case, I'd suggest service discovery patterns using consul and consul template.  You can check out [consul service registration](https://www.nomadproject.io/docs/job-specification/service.html) and consul templates support details in https://www.nomadproject.io/docs/job-specification/template.html and https://www.consul.io/docs/guides/consul-template.html#use-case-discover-all-services .

We intend to provide a smoother story with consul connect, tracked in https://github.com/hashicorp/nomad/issues/4451 .

**Comment by bruno-unna** [comment]
Interestingly, [Nomad's official documentation](https://www.nomadproject.io/docs/runtime/environment.html) describes two environmental entries, similar to each other:

Variable | Description
-----------|-----------------
NOMAD_ADDR_<label> | Host IP:Port pair for the given port label.
NOMAD_ADDR_<task>_<label> | Host IP:Port pair for the given port label and task for tasks in the same task group. 

If the second entry is for tasks in the same task group, I'd assume the first one is for tasks *not* in the same task group. Where am I wrong?

**Comment by notnoop** [comment]
I see - thanks for raising.  For a given task, `NOMAD_ADDR_<label>` reports the host address for the given label of that said running task; not any other task in the task group or otherwise.  Meaning a for a task named `nginx` and label `http`, `NOMAD_ADDR_http` should be the same as `NOMAD_ADDR_nginx_http`.  We'll update the docs to clarify.

**Comment by bruno-unna** [comment]
I think I get it now. Thanks for the clarification.

**Comment by john-lay** [comment]
Thank you to @notnoop for the suggestion of using `consul templates` and to @bruno-unna for helping with the solution. 

We had to expose our postgresql task as a service to make consul aware of it, and as suggested move our configuration to a template. The scala/java framework we are using allows us to pass a configuration file as a parameter, so we did just that and referenced our template file.

For anyone who stumbles across this question our final solution with consul templates looks a bit like this:

```
job "myjob" {
  group "db" {
    task "postgresql" {
      config {
        image = "bitnami/postgresql:11.1.0"
        network_mode = "bridge"
        port_map {
          postgresql = 5432
        }
      }

      resources {
        network {
          mbits = 100
          port "postgresql" {}
        }
      }

      service {
          name = "postgresql"
          port = "postgresql"
      }
    }
  }

  group "service" {

    task "foo" {
      driver = "java"

      config {
        jvm_options = [
          "-Dconfig.file=local/local.conf"
        ]
      }

      template {
        destination = "local/local.conf"
        data = <<EOH
db.default.url = "jdbc:postgresql://{{ range service "postgresql" }}{{ .Address }}:{{ .Port }}{{ end }}/database?user=xxx&password=xxx"
EOH
        change_mode = "restart"
      }
    }
  }
}
```

**Comment by tsujp** [comment]
@bruno-unna @schmichael 

Do you know of a way to use `NOMAD_ADDR_<task>_<label>` without specifying the `label` or what the default value of `label` is?
