### ISSUE TITLE
[question] Send a different kill signal to the Docker container according to the event that triggers it

### ISSUE THREAD

**Issue by luismiguelospinaglobant** [hashicorp/nomad#5458]
Multiple events can trigger a Nomad Batch Job to be terminated (shut down) such as:
- User Canceling the Job
- Nomad Moving the allocation to a new node
- Nomad node itself going down

Is it possible to send a different signal according to the event that triggered it to my Docker container (Running a JAR Application) so i can react according to the signal that Nomad Sent?

**Comment by notnoop** [comment]
Nope - it's not possible currently.

It's worth noting that processes may die unexpectedly without being able to handle the signal (e.g. by SIGKILL, node crash to a kernel bug, etc); so I would be hesitant to rely on signals for cleanup or additional work.
