### ISSUE TITLE
Device maturity support in containers

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5463]
We would like to utilise the Device Manager support in Nomad along with Exec driver-based tasks. Our use-case is to deploy Task(s) that connect to a HSM (*Hardware Security Module*).

Some questions:

* The example device plugin looks fairly straight forward; and poking around the codebase it seems that the responsibility of the "device manager plugin" is to manage allocations/reservations of the device. Is this right?
* On further poking around it looks like at the end of the day; the common task_runner code "bind mounts" the device inot the container(s). Is this also correct?

And lastly; what is the maturity level of the device plugin support in general? We are considering writing a device plugin to support (*at least*) our particular vendor of HSM(s) we are using and using the Exec driver.

**Comment by prologic** [comment]
Also on licensing... What licensing requirements are we bound by if we author a device driver plugin? Are we subject to the same licensing terms of Nomad itself? -- I would*assume* not since the plugins are completely external to Nomad and invoked over an external API (*gRPC+Protobuf*). Thanks!

**Comment by schmichael** [comment]
This is very exciting! HSMs were one of the devices we were hoping would be supported by device plugins. Unfortunately the `How to write X plugins` documentation isn't complete yet, but [you can view the WIP _driver_ docs.](https://github.com/hashicorp/nomad/commit/42edf2d2133dd58ecb8c1f2a85cddee26e8a1b96)

Your initial analysis is basically correct: device plugins provide 2 core functions:

1. Reporting resources available to the Nomad servers/scheduler.
2. Exposing lists of mounts and devices for drivers to consume.

We take pride in trying to minimize backward incompatibilities in Nomad releases and the plugin APIs are no different. We intend on maintaining backward compatibility as much as possible. Hopefully our plugin API is like our HTTP API: [the last backward incompatible HTTP API change I can find was in Nomad 0.2.0](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#020-november-18-2015) -- *which was in 2015!*

> Also on licensing...

If you do not use any Nomad source code, you are correct: the MPL does not apply. Not using HashiCorp code would require doing a cleanroom implementation of [go-plugin](https://github.com/hashicorp/go-plugin) and many Nomad structs.

Using go-plugin and Nomad structs would make plugin writing far easier but would be subject to the terms of the [MPL](https://www.mozilla.org/en-US/MPL/). You are *not* bound by the [CLA](https://www.hashicorp.com/cla) unless you wanted your plugin to be distributed with Nomad.

I am not a lawyer, but hopefully the MPL is permissive enough that reusing our code is an option for you!

_I'm going to treat this issue as a question and close it for now. Proper device plugin docs should be coming soon. Feel free to open an issue for them if you want to be notified as soon as the PR happens!_

Feel free to reopen or file new issues if you have further questions.

**Comment by prologic** [comment]
Thank you!

**Comment by prologic** [comment]
Sorry one more question!

Q: Do we still need a Device Driver Plugin if we use the `raw_exec` Execution driver? Or is that only required if using the `exec` and `docker` Exec drivers?

**Comment by schmichael** [comment]
Good question!

> Q: Do we still need a Device Driver Plugin if we use the raw_exec Execution driver?

Probably not, but you may need to carefully configure the device and Nomad agent. If the device is accessible by any user on the node, then all `raw_exec` jobs will be able to access it (for better or worse depending on your use case).

If the device is only accessible by root, the Nomad agent will need to run as root and you will need to remove root from the [`user.blacklist`](https://www.nomadproject.io/docs/configuration/client.html#quot-user-blacklist-quot-) client configuration parameter.

If the device is accessible by a non-root user then `raw_exec` jobs will have to set that user in their [`user` stanza](https://www.nomadproject.io/docs/job-specification/task.html#user).

Right now the only way to restrict which jobs can run as which users is to [create Sentinel policies in Nomad Enterprise.](https://www.nomadproject.io/docs/enterprise/sentinel/index.html)

**Comment by prologic** [comment]
> Probably not, but you may need to carefully configure the device and Nomad agent. If the device is accessible by any user on the node, then all `raw_exec` jobs will be able to access it (for better or worse depending on your use case).

The reason I ask for clarification here is because when I dug into the codebase I noticed that the `raw_exec` driver also uses the "github.com/hashicorp/nomad/drivers/shared/executor" package which also looks up devices from device driver plugins and calls things like `.Reserve()`, etc.

**Comment by schmichael** [comment]
Reserve is called by the TaskRunner (driver independent code) and raw_exec only uses the environment variables set from its return value.

(This is a learning experience for me as well as I didn't personally write the device plugin code!)

**Comment by prologic** [comment]
Just wanted to provide a quick update here.

We have ultimately decided not to write the device driver plugin for HSM(s) for the following reasons:

* Engineering bandwidth constraints and business priorities
* Unclear (*to us*) licensing of the plugin code (if written).

On the subject: We're actually not sure given the comment above by  @schmichael whether we can use any of Hashicorp's Go libraries at all. There are countless projects on Github that use the `hashicorp/raft`, `hashicorp/consul` and various other awesome libraries. So we have conflicting views on the terms of the MPL licensing. My understanding from reading the MPL in more detail and as stated [here](https://www.mozilla.org/en-US/MPL/2.0/FAQ/):

> **Q8: I want to distribute (outside my organization) executable programs or libraries that I have compiled from someone else's unchanged MPL-licensed source code, either standalone or part of a larger work. What do I have to do?**
> 
> You must inform the recipients where they can get the source for the MPLed code in the executable program or library you are distributing (i.e., you must comply with Section 3.2). You may distribute any executables you create under a license of your choosing, as long as that license does not interfere with the recipients' rights to the source under the terms of the MPL.

If I'm reading this correctly and the rest of the license; we *are* able to:

* Distribute executable / binaries that include MPL **unmodified** licensed libraries linked against.
* We are free to license the source code of the executable / binary of our choosing.
* We have to inform recipients of the executable / binary where to obtain copies of the **unmodified**MPL licensed libraries being used.

I have *seen* examples of this in many commercially available products where they will typically list OSS libraries/components used and where to obtain them (*presumably unmodified*).

Shouldn't a Nomad Device Plugin that is ultimately a binary with a gRPC protocol also be covered by the same conditions?

I'm no expert on the subject of Software Licensing myself but the comment above originally has me concerned about even using `hashicorp/consul` published Go libraries to communicate with the Consul API service(s) in our applications.

**Comment by schmichael** [comment]
> I have seen examples of this in many commercially available products where they will typically list OSS libraries/components used and where to obtain them (presumably unmodified).

Yeah, proprietary software that includes open source code often contains a way to show the licenses of the software used as well as a link to where the source may be obtained. This appears to be the common path taken to fulfill the terms of common open source licenses (Apache, MPL, MIT, etc). For example Valve Steam has this:

![image](https://user-images.githubusercontent.com/113362/56237108-118ae700-6040-11e9-8b6d-aaa771f356d2.png)

And Google Chrome has:

![image](https://user-images.githubusercontent.com/113362/56237183-341d0000-6040-11e9-8e9d-2fb7941b3316.png)

Both are proprietary binaries containing open source code.

> Shouldn't a Nomad Device Plugin that is ultimately a binary with a gRPC protocol also be covered by the same conditions?

If you implement the GRPC layer yourself without using any code (structs or packages) from Nomad, Nomad's licensing terms _do not apply to you._

If you use Nomad code like the [Singularity task driver plugin](https://github.com/sylabs/nomad-driver-singularity), then you need to fulfill the conditions of the MPL. Proprietary plugins can fulfill those conditions similar to how Steam and Chrome do it.

That being said I am not a lawyer and this is not legal advice. :sweat_smile: While HashiCorp tries to use permissive licensing to make it as easy as possible for third parties to use our code as they please, we cannot offer legal guidance or assurances outside what is specified in the license itself. Luckily as you've found Mozilla has some great resources explaining their licensing!
