### ISSUE TITLE
[question] [feature request] AWS auth for Vault integration

### ISSUE THREAD

**Issue by jimcroft** [hashicorp/nomad#5465]
Hi!

I've been kicking the tyres with Nomad and Vault and have vault configured such that AWS auth is working on my nomad cluster servers (ie. `vault login -method=aws` works as expected returning a token, policies, and metadata).

Looking at Nomads Vault integration doc it looks like I need to wire a static VAULT_TOKEN into the Nomad server config or environment. Is that the case? Can I omit the token and have Nomad use the AWS auth method instead?

**Comment by schmichael** [comment]
As of Nomad 0.9.0 you must still manually configure your Vault token. In the future we will likely use the [Vault Agent](https://github.com/hashicorp/nomad/issues/5465) for this functionality, but we do not have it on the roadmap yet.

**Comment by djenriquez** [comment]
@jimcroft, not sure if you have a solution, figured I can share:

Though theres no direct feature that allows the functionality, you can get around this by calling the `vault login -method=aws` manually to generate the token that contain the required [policies](https://www.nomadproject.io/docs/vault-integration/index.html#required-vault-policies), then inject it into the Nomad config.

So something like this:
```
VAULT_TOKEN=$(vault write -field=token auth/aws/login \
  role="$ROLE" \
  pkcs7="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7)" \
  nonce="$INSTANCE_ID")

NOMAD_VAULT_TOKEN="$(vault token create -field token -policy nomad-server -period 72h -orphan)"
```

Then you can inject `NOMAD_VAULT_TOKEN` in the Nomad config via sed or some templating engine. The Nomad server will then use that rendered nomad config. It will also do all the magic of renewing the token before it expires.

**Comment by jimcroft** [comment]
Nice workaround, thanks @djenriquez
