### ISSUE TITLE
[question] Nomad Portworx Integration

### ISSUE THREAD

**Issue by pam9999** [hashicorp/nomad#5470]
Hi,
I'm trying to use portworx-dev to prototype statefull containers with Nomad. I'm unable to run my Nomad job with a Exhaust failure :

### Nomad failure trace

```
Task Group "mysql-server" (failed to place 1 allocation):
      * Resources exhausted on 2 nodes
      * Dimension "disk" exhausted on 2 nodes
    Evaluation "74f5ad59" waiting for additional capacity to place remainder
```

px-dev seems to run without any problem and there is enough place for my allocation :

### `pxctl status`

```
Status: PX is operational
License: PX-Developer
Node ID: bfec3b7e-22f6-419e-914d-0c67ad61337a
        IP: 10.3.9.206
        Local Storage Pool: 1 pool
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE  USED    STATUS  ZONE    REGION
        0       HIGH            raid0           20 GiB  2.2 GiB Online  default default
        Local Storage Devices: 1 device
        Device  Path            Media Type              Size            Last-Scan
        0:1     /dev/sdc        STORAGE_MEDIUM_MAGNETIC 20 GiB          22 Mar 19 14:46 CET
        total                   -                       20 GiB
Cluster Summary
        Cluster ID: PLATINES_STORAGE
        Cluster UUID: 41c6dc0e-f97f-4450-8038-64c9af14b871
        Scheduler: none
        Nodes: 2 node(s) with storage (2 online)
        IP              ID                                      StorageNode     Used    Capacity        Status  StorageStatus     Version         Kernel                          OS
        10.3.9.206      bfec3b7e-22f6-419e-914d-0c67ad61337a    Yes             2.2 GiB 20 GiB          Online  Up (This node)    1.3.4.0-7895900 3.10.0-862.14.4.el7.x86_64      Red Hat Enterprise Linux Server 7.5 (Maipo)
        10.3.9.238      4d838316-beb5-4279-84a9-c0ce4b6b7a14    Yes             2.2 GiB 20 GiB          Online  Up1.3.4.0-7895900 3.10.0-862.14.4.el7.x86_64      Red Hat Enterprise Linux Server 7.5 (Maipo)
Global Storage Pool
        Total Used      :  4.5 GiB
        Total Capacity  :  40 GiB
```

### Volume status ###

`pxctl volume inspect mysql`
```
Volume  :  442369538733499588
        Name                     :  mysql
        Size                     :  10 GiB
        Format                   :  ext4
        HA                       :  2
        IO Priority              :  LOW
        Creation time            :  Mar 26 15:35:24 UTC 2019
        Shared                   :  no
        Status                   :  up
        State                    :  detached
        Reads                    :  0
        Reads MS                 :  0
        Bytes Read               :  0
        Writes                   :  0
        Writes MS                :  0
        Bytes Written            :  0
        IOs in progress          :  0
        Bytes used               :  131 MiB
        Replica sets on nodes:
                Set  0
                  Node           :  10.3.9.206 (Pool 0)
                  Node           :  10.3.9.238 (Pool 0)
        Replication Status       :  Detached
```

### Nomad version

Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details

Here is the docker config of my job file 
```
config {
        image = "rhscl/mariadb-101-rhel7:latest"

        port_map {
          db = 3306
        }


        volumes = [
          "name=mysql:/var/lib/mysql/data"
        ]
        volume_driver = "pxd"
      }
```

Can you confirm that Nomad is compatible with portworx-dev ? 
For my prototype, I use 2 nodes only.
Many thanks !
Patrick

**Comment by dantoml** [comment]
@pam9999 Could you possibly share the output of `nomad node-status <node-id>` for the nodes?

**Comment by pam9999** [comment]
### Node 1 ###
ID            = d52003df
Name          = vm368a671197.qual.henix.asip.hst.fluxus.net
Class         = <none>
DC            = henix_qualif1
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 98h26m2s
Driver Status = docker,exec,raw_exec

Node Events
Time                       Subsystem  Message
2019-03-22T15:05:21+01:00  Cluster    Node registered

Allocated Resources
CPU           Memory           Disk             IOPS
500/4788 MHz  2.0 GiB/3.7 GiB  200 MiB/294 MiB  0/0

Allocation Resource Utilization
CPU         Memory
2/4788 MHz  792 MiB/3.7 GiB

Host Resource Utilization
CPU           Memory           Disk
118/4788 MHz  2.0 GiB/3.7 GiB  2.5 GiB/3.4 GiB

Allocations
ID        Node ID   Task Group    Version  Desired  Status   Created    Modified
0dcfc766  d52003df  apps-servers  66       run      running  1h15m ago  1h13m ago
### Node 2 ###
ID            = 91c61633
Name          = vm368a671191.qual.henix.asip.hst.fluxus.net
Class         = <none>
DC            = henix_qualif1
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 100h54m31s
Driver Status = docker,exec,raw_exec

Node Events
Time                       Subsystem  Message
2019-03-22T14:34:21+01:00  Cluster    Node registered

Allocated Resources
CPU         Memory       Disk         IOPS
0/4788 MHz  0 B/3.7 GiB  0 B/294 MiB  0/0

Allocation Resource Utilization
CPU         Memory
0/4788 MHz  0 B/3.7 GiB

Host Resource Utilization
CPU          Memory           Disk
24/4788 MHz  1.2 GiB/3.7 GiB  1.8 GiB/8.4 GiB

Allocations
No allocations placed

**Comment by dantoml** [comment]
@pam9999 Nomad requires a few hundred mb of disk in the client data dir for things like log management / artifacts / etc, and it looks like neither host has enough available storage in the data dir for this? (both have 294mb of available disk for jobs)

**Comment by pam9999** [comment]
Thanks a lot, actually, it was an issue related to a new provisionned node. A Redhat upgrade changes docker storage configuration from device-mapper to overlay2 and our installation process was not updated.
