### ISSUE TITLE
JSON Plugin config in 0.9-rc1 non functional

### ISSUE THREAD

**Issue by benagricola** [hashicorp/nomad#5484]
Not sure if this is a question or a bug 🙂 

### Nomad version
`Nomad v0.9.0-rc1 (7c00ab4f3f37cfd1e258b38fd2ad99e7bc23e4c3)`

### Issue
Cannot enable docker privileged containers, or raw_exec using JSON configuration. Based on the example HCL configs, AIUI I should be able to do the following:

`/etc/nomad.d/plugins.json`:

```
{
    "plugin": {
        "docker": {
            "config": {
                "allow_privileged": true
            }
        },
        "raw_exec": {
            "config": {
                "enabled": true
            }
        }
    }
}
```

Based on the `configSpec` defined in both plugins this looks correct, but errors on start:

```
 error parsing 'config': plugin-> invalid keys in plugin config 1: 1 error(s) occurred
  * invalid key: allow_privileged 
```

Removing the contents of the config block (leaving it an empty object) and I get `error parsing 'config': plugin-> plugin config 1 doesn't incude a name key` instead.

I've also tried making `plugin` a list of objects, and various other formats, and none of them work - I'm lost.

Is this supposed to work? If so, what is the correct JSON format? I can't find any tests which use a JSON config to set those settings so there's nothing to go off here except trying to read the code.

We currently use JSON configs with a 0.8.7 cluster and I'm trying to get ahead of the curve prepping our deployment setup to handle 0.9 properly.

**Comment by preetapan** [comment]
@benagricola Thanks for the report, this turned out to be an edge case in json parsing that only affects the plugin configuration. We will fix this for the final release.
