### ISSUE TITLE
[feature] logmon plugin (syslog forwarding)

### ISSUE THREAD

**Issue by jozef-slezak** [hashicorp/nomad#5490]
I would like to propose a feature request. Possibility to replace existing logmon functionality with custom one by configuring plugin (0.9  supports pluggable drivers). 

Idea - alternative 1: nomad logmon is allready aj plugin. We could just add path to logging plugin (alternative to logmon) and implment same GRPC api as logmon does.

Idea - alternative 2: pull request with syslog logger decorator (simmilar to what exists in the agent syslog config option)

Use case: forwarding to syslogs (simmilar use case to
https://github.com/hashicorp/nomad/issues/4494)

**Comment by schmichael** [comment]
This is a great idea that we hope to implement! It won't be in the 0.9 series unfortunately.

#1469 seems to be the first "logging plugin", so I'm going to start pointing issues there.
