### ISSUE TITLE
During a rolling restart, all services go unhealthy until next check, at each stagger interval

### ISSUE THREAD

**Issue by dontrebootme** [hashicorp/nomad#550]
Watching consul when rolling 100 containers, I see all my services go back to unhealthy during each interval.

Steps to reproduce:
Spin up a new service with more than max_parallel count. (max_parallel = 5, task count = 100).
Perform rolling update
Monitor consul

**Comment by dadgar** [comment]
Hey I just tried this myself, only the tasks that were updated during the interval were marked unhealthy in Consul, the rest remained healthy until the next interval.

**Comment by dontrebootme** [comment]
@dadgar how would you recommend me to provide more information? Is there specific debug information or consul queries I can make to show what I'm seeing?

**Comment by dontrebootme** [comment]
Here's a string of images of what I see during a rolling update of 50 containers. You should be able to recreate this from my [nomad-intro](https://github.com/dontrebootme/nomad-intro/blob/master/SYSADVENT.md) repo. Set the microbot to 50 instances, do a nomad run, then bump v1 image to v2, and do a nomad run. 

![screen shot 2015-12-09 at 3 28 56 pm](https://cloud.githubusercontent.com/assets/1504683/11702254/2596ad22-9e8a-11e5-9f5c-24559aa29ac7.png)
![screen shot 2015-12-09 at 3 29 16 pm](https://cloud.githubusercontent.com/assets/1504683/11702256/2b15fd8e-9e8a-11e5-90a1-9da634fdc74a.png)
![screen shot 2015-12-09 at 3 29 22 pm](https://cloud.githubusercontent.com/assets/1504683/11702261/3027df9a-9e8a-11e5-99fd-9906e6a985c6.png)
![screen shot 2015-12-09 at 3 29 35 pm](https://cloud.githubusercontent.com/assets/1504683/11702263/34ee32ae-9e8a-11e5-8811-f98c52198cc2.png)
![screen shot 2015-12-09 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/1504683/11702267/3a93ee06-9e8a-11e5-8a90-b5b83b3c9610.png)
![screen shot 2015-12-09 at 3 30 10 pm](https://cloud.githubusercontent.com/assets/1504683/11702268/3f2728f2-9e8a-11e5-8f94-d8169637df92.png)
![screen shot 2015-12-09 at 3 30 52 pm](https://cloud.githubusercontent.com/assets/1504683/11702271/4593adb4-9e8a-11e5-900d-2c16f063a2e1.png)
![screen shot 2015-12-09 at 3 31 13 pm](https://cloud.githubusercontent.com/assets/1504683/11702272/499aaafc-9e8a-11e5-8b4a-79158f79094b.png)

**Comment by dadgar** [comment]
Yeah this looks fine. It is a bit confusing because there are two checks associated with each service. But what is happening is that Nomad is taking down and starting 5 tasks every 10 seconds (from the jobs restart policy). 

This causes the health checks associated with the restarted tasks to be marked as unhealthy. They will eventually flip back to healthy when Consul checks them. However, Nomad continues to restart 5 tasks every 10 seconds. So that is why you are seeing failing go up and then down through the rolling update.

**Comment by dontrebootme** [comment]
So why is it affecting the cadvisor check when that isnt part of the rolling update? At some times the entire service disappears completely.

**Comment by diptanu** [comment]
Yeah cadvisor shouldn't dissapear. Is cadvisor being controlled by Nomad as a system job?

**Comment by dadgar** [comment]
@diptanu: It looks like it is based on the job config.

**Comment by dontrebootme** [comment]
cadavisor is a system job, yes. Definition also available in the repo I linked above. When the rolling update isnt running the cadvisor checks do not fail, only during the rolling update.

**Comment by cbednarski** [comment]
Also it looks like the replaced instances are being killed before the new one is available. We should overload so we're running _at least_ `count` at all times so we don't cause a drop in capacity while the update is rolling.

**Comment by dontrebootme** [comment]
@cbednarski coming from mesos/marathon environments, they have a way that you can configure this. See rolling restarts on this page: https://mesosphere.github.io/marathon/docs/deployments.html.

For instance:
``` 
   "upgradeStrategy": {
        "minimumHealthCapacity": 0.5,
        "maximumOverCapacity": 0.2
    }
```

**Comment by cbednarski** [comment]
@dontrebootme Thanks for the link. A caveat here is if you have a system job (e.g. once-per-host) with a static IP we have to tear down to replace, so some temporary outage is unavoidable (ideally short, though).

**Comment by dontrebootme** [comment]
@cbednarski in this issue, I'm rolling updating the microbot service job and not the cadvisor system job

**Comment by cbednarski** [comment]
@dontrebootme Thanks for clarifying!

It also occurs to me we can use a pid swap technique for system jobs, though we don't do this currently.

**Comment by cbednarski** [comment]
To make it easier to debug you may want to change the log level from `INFO` to `DEBUG`. I was able to repro this using the demo repo and the following commands:

```
sed -i -e 's/INFO/DEBUG/g' nomad/nomad-server.json
sed -i -e 's/INFO/DEBUG/g' nomad/nomad-client.json
sed -i -e 's/INFO/DEBUG/g' consul/consul-server.json
sed -i -e 's/INFO/DEBUG/g' consul/consul-client.json
vagrant up
vagrant ssh nomad
cd /vagrant
nomad run cadvisor.nomad
nomad run microbot.nomad
nomad stop microbot
```

You can repeat the last two commands (`run` and `stop`) to trigger this again. You can view the logs via:

```
vagrant ssh consul
sudo tail -f /var/log/upstart/consul.log

vagrant ssh nomad
sudo tail -f /var/log/upstart/nomad.log
```

etc.

**Comment by diptanu** [comment]
Ok I can repro the flapping of the cadvisor service during rolling deploy, working on a fix.

**Comment by diptanu** [comment]
@dontrebootme So finally figured out what the problem was. A fix is going to land in master very soon.

**Comment by dadgar** [comment]
Hey the problem should be fixed by PR #561. Let us know if it still not working for you (you will have to build from master)

**Comment by dontrebootme** [comment]
I'm having issues building this to test. Both the vagrant dev environment fails and the local environment experiences:
```
➜  nomad (master) ✔ make test
--> Installing build dependencies
--> Building nomad
# github.com/hashicorp/nomad/jobspec
../hashicorp/nomad/jobspec/parse.go:289: undefined: mapstructure.StringToTimeDurationHookFunc
../hashicorp/nomad/jobspec/parse.go:544: undefined: mapstructure.StringToTimeDurationHookFunc
../hashicorp/nomad/jobspec/parse.go:668: undefined: mapstructure.StringToTimeDurationHookFunc
# github.com/hashicorp/nomad/nomad
../hashicorp/nomad/nomad/pool.go:132: undefined: tlsutil.DCWrapper
make: *** [test] Error 1
```

**Comment by diptanu** [comment]
@dontrebootme Can you please update your dependencies and try once?
