### ISSUE TITLE
Should each check in nomad result in two checks in Consul?

### ISSUE THREAD

**Issue by dontrebootme** [hashicorp/nomad#551]
When I spin up 50 service tasks in nomad, I see 100 services in Consul. It appears that every nomad service results in the service check itself and the serf health check. Is this expected?

<img width="555" alt="screen shot 2015-12-09 at 10 56 55 am" src="https://cloud.githubusercontent.com/assets/1504683/11695368/a02110ae-9e63-11e5-94cd-a30d80b22edd.png">
<img width="605" alt="screen shot 2015-12-09 at 10 56 59 am" src="https://cloud.githubusercontent.com/assets/1504683/11695369/a0268f48-9e63-11e5-8e76-fddb485d7bd1.png">

**Comment by diptanu** [comment]
@dontrebootme Did you mean with 50 services you're seeing 100 checks in the UI?

So I was trying to reproduce it, if I curl /v1/agent/checks on the Consul agent, I am seeing the proper number of checks. Can you please confirm? Not sure how the UI works.

**Comment by dontrebootme** [comment]
Yes 50 checks becomes 100 services



—

**Comment by ryanuber** [comment]
Hi @dontrebootme,

I can see how this is a little confusing in the UI, but let me try to clarify what you are seeing. Each instance of `microbot-web-microbot` has 1 check associated with it, probably checking the health of the running service somehow. However, there are actually 2 checks which affect the overall "availability" of each instance, meaning whether or not Consul views the result as "healthy". Each node-level check will affect the health status of every service on the node, including "serfHealth". So, if serfHealth OR the individual `microbot-web-microbot` health check fail, then the service instance will be considered not healthy. The UI seems to be counting the same serfHealth for each instance of your custom service. It isn't that there are actually 2x the number of checks running. This does seem misleading so I'm going to open an issue for the Consul UI. I'll link it back here.

**Comment by ryanuber** [comment]
I've opened hashicorp/consul#1484 to track this and get it fixed.
Thanks for taking the time to report this @dontrebootme !

**Comment by mohnishbasha** [comment]
@dontrebootme 

Could you share your nomad checks for both nomad server and client.
Looks like when I am adding check for nomad client - the port 4647 is not open for connections.
i.e. when i do telnet localhost 4647 on nomad agent i get the connection refused.
However, when i do the same on nomad server the telnet gets connected, hence the check is passing on server but fails on client.
