### ISSUE TITLE
[Question]: State of Prometheus support for metrics (including Allocs, Jobs, etc)

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5522]
Question:

What is the status of support for Prometheus metrics in Nomad right now? I've been playing around with this for a total of ~5mins and I've observed a few things so far:

* The `/v1/metrics` endpoint only seems to export internal metrics related to the Nomad agent itself, nothing about Jobs, Allocs, etc. The `?format=prometheus` works; but right now this endpoint isn't that useful unless you only care about monitoring Nomad itself.

There is this [nomad-exporter](https://github.com/Nomon/nomad-exporter) I found that was last committed to in Aug 2017 and seems to be more complete in terms of what it exports. Things like Task RSS, Task CPU and lots of other useful things. -- Problem is I'm not sure if its being maintained or not as it has several PRs that are stale and hasn't been committed to in over 18months.

Am I just missing a configuration?

Furthermore; you have 404's in your documentation on the website related to Prometheus integrations: This page contains a link that 404s:

* https://www.nomadproject.io/guides/operations/monitoring/nomad-metrics.html

> For Grafana, follow Grafana's Getting Started guide to set up a running Grafana instance. Then, import the sample Nomad Dashboard for an **example Grafana dashboard**. This dashboard requires a Prometheus data source to be configured, see the README.md for more information.

**Comment by pznamensky** [comment]
I guess you're scraping metrics from a Nomad server and indeed there are not tasks related metrics here.
Tasks related metrics are available on Nomad agents on `/v1/metrics?format=prometheus`.

**Comment by cgbaker** [comment]
As far as that guide is concerned, we removed links to it because the telemetry docs are being rewritten. When we removed it from the listing, it stopped being subject to our dead link testing. The new locations for those dead links is here: 
https://github.com/hashicorp/nomad/tree/master/integrations/grafana_dashboards
