### ISSUE TITLE
Add metrics for allocated cpu(memory) for each task.

### ISSUE THREAD

**Issue by vyacheslav-skvortsov** [hashicorp/nomad#5526]
### Nomad version
Nomad v0.9.0-rc1 (7c00ab4f3f37cfd1e258b38fd2ad99e7bc23e4c3)

### Operating system and Environment details
Windows Server 2019
### Issue
Can you add metrics for allocated memory/cpu for each job/task? It needs to calculate percentage of available resources. For example: nomad_client_allocated_memory{job="test-job", task="task-1"} 1000

**Comment by schmichael** [comment]
Hi @vyacheslav-skvortsov,

Does #5492 address your needs?

Closing in favor of #4280

**Comment by vyacheslav-skvortsov** [comment]
Hi @schmichael.
Thank you for the reply!
