### ISSUE TITLE
Docker auth not compatible with official AWS ECR login helper

### ISSUE THREAD

**Issue by mdierolf** [hashicorp/nomad#5527]
### Nomad version
Nomad v0.8.7

### Operating system and Environment details
Debian Buster

### Issue
When using the official Amazon [ECR Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper), Nomad is not able to log into an ECR repository, because Nomad does not set the HOME=/root environment variable in the shell which activates the login helper

### Reproduction steps
- Install Debian Buster
- Install packages from official APT tree: amazon-ecr-credential-helper, nomad
- Add this to nomad config:
`
"docker.auth.config" = "/root/.docker/config.json"
`
- Add this to /root/.docker/config.json
`
{
        "credsStore": "ecr-login"
}
`
- Start job with docker tasks that references a private image
- Job hangs for 30 seconds waiting on ECR helper
- Allocation fails: failed to initialize task "xxx" for alloc "474568cd-77cf-944a-9b47-c297bbcde13f": Failed to find docker auth for repo "xxxx.dkr.ecr.us-east-1.amazonaws.com/xxx": docker-credential-ecr-login with input "xxx.dkr.ecr.us-east-1.amazonaws.com/xxx" failed with stderr: credentials not found in native keychain

### How to confirm the problem
Create a login helper wrapper around ECR login:

```
#!/bin/sh
env > /tmp/ecrinfo

export HOME=/root
/usr/bin/docker-credential-ecr-login $@

```

Login now succeeds, and you can confirm that the HOME= variable is missing by looking in /tmp/ecrinfo

### How to fix it
The ECR login helper expects HOME to be set before being invoked, as it stores the users credentials in ${HOME}/.ecr/cache.json

Nomad should set the HOME= environment variable before invoking the login helper

**Comment by cgbaker** [comment]
Can you update the systemd unit to include HOME=/root?

**Comment by mdierolf** [comment]
Looking over the systemd config for nomad, I was able to add HOME=/root to /etc/default/nomad, and it now works.

Is this a bug with nomad, systemd, ecr-login, or simply expected behavior? 

It looks like HOME is typically set by [login](http://man7.org/linux/man-pages/man1/login.1.html), but systemd doesn't set it since it isn't a login shell. Which seems correct because system service shouldn't be putting data in /root.

I'm thinking the ecr-login helper should probably query /etc for aws credentials and store its cache in /var when HOME= isn't set.

**Comment by Dirrk** [comment]
@mdierolf what version of ecr-login are you using? `docker-credential-ecr-login-v`

**Comment by mdierolf** [comment]
> @mdierolf what version of ecr-login are you using? `docker-credential-ecr-login -v`

0.6.0

**Comment by cgbaker** [comment]
@mdierolf : Here is another discussion with some configuration that doesn't rely on $HOME and/or anything relative to the Nomad running user: 
https://github.com/hashicorp/nomad/issues/3526#issuecomment-374890827

**Comment by mdierolf** [comment]
> @mdierolf : Here is another discussion with some configuration that doesn't rely on $HOME and/or anything relative to the Nomad running user:
> [#3526 (comment)](https://github.com/hashicorp/nomad/issues/3526#issuecomment-374890827)

Unfortunately that method wouldn't work for us, since our servers are bare metal, not on AWS, so I don't have access to IAM credentials over http. I think updating the /etc/default/nomad file is the best workaround for now.
