### ISSUE TITLE
[question] Preferred way to use privileged ports with "exec" driver?

### ISSUE THREAD

**Issue by radcool** [hashicorp/nomad#5528]
Hi,

Let's say I want to run Fabio as a Nomad _system_ job using the _exec_ driver and have it listen on port 80; considering that the default user used by the _exec_ driver is `nobody` and that it cannot bind to ports < 1024 by default, what is considered the best practice to achieve this (unless binding to privileged ports in Nomad services is frowned upon)?

I managed to achieve this by installing the Fabio binary locally on all Nomad clients and `setcap 'cap_net_bind_service=+ep' fabio`, but I'm not sure if this is considered best practice.

Moreover, I've been in the habit of downloading the binaries to run for jobs using the `artifact` stanza; however, I did not find any documentation relating to setting capabilities in the _exec_ driver.

1. Is indeed not possible to bind to privileged ports with the _exec_ driver and downloaded artifacts?

2. If it's not currently possible to do so, is it something that would eventually make sense for me to look into in adding terms of functionality to the _exec_ driver?

Thanks!

**Comment by cgbaker** [comment]
Typically, workloads using the `exec` driver do not bind to privileged ports. When using the `exec` driver, web servers (like Fabio) not using `root` are usually run on static high ports (e.g., 9999), with "hardware" load-balancers directing traffic from 80 to the static port on the Nomad client nodes.

Other options are:
1. Using the docker driver with a static port will allow for a port-mapping to the host port 80. Obviously, this requires that you have the docker task driver available.
2. iptables rules to redirect 80 to a static high port (e.g., Fabio's 9999) on each Nomad client node.

Going forward, the upcoming network namespacing work that we are doing will support this use case. Therefore, we aren't currently considering expanding the exec driver with a `set_cap`-like ability.

**Comment by radcool** [comment]
> Typically, workloads using the exec driver do not bind to privileged ports.

OK.

> When using the `exec` driver, web servers (like Fabio) not using `root` are usually run on static high ports (e.g., 9999), with "hardware" load-balancers directing traffic from 80 to the static port on the Nomad client nodes.

Right now I'm only hosting low-traffic, "internal" micro web sites on Nomad so I did not feel I needed actual load balancing; I simply wanted the redundancy afforded by Consul returning multiple IPs via DNS. That's why a "hardware" load balancer is not in the mix.

> 1. Using the docker driver with a static port will allow for a port-mapping to the host port 80. Obviously, this requires that you have the docker task driver available.

Yeah, that was once possibility I'd pondered but I was trying to avoid running Docker unless there was an actual benefit to doing so.

> 2. iptables rules to redirect 80 to a static high port (e.g., Fabio's 9999) on each Nomad client node.

That had crossed my mind too. I was just afraid the redirect might impose a little performance penalty (although truth be told, if I'm only running low-traffic stuff it shouldn't really matter anyway).

> Going forward, the upcoming network namespacing work that we are doing will support this use case. 

Will this be part of Nomad Namespaces and offered on the Enterprise version only or be something completely unrelated?

Thanks.

**Comment by cgbaker** [comment]
> > Going forward, the upcoming network namespacing work that we are doing will support this use case.

> Will this be part of Nomad Namespaces and offered on the Enterprise version only or be something completely unrelated?

No, I'm referring to Linux namespaces here; this will not be an Enterprise-only feature.

**Comment by radcool** [comment]
> No, I'm referring to Linux namespaces here; this will not be an Enterprise-only feature.

OK. Thanks Chris.

I think if I do decide I'd really much rather download the Fabio binary for a job via `artifact` instead of installing it directly on each Nomad client I'll go ahead and use option 2 (iptables).

Thanks again.

**Comment by dmartin-isp** [comment]
I believe you could create a raw_exec job that pipes between port 80 and 9999.  That would limit your raw_exec exposure and you'd still have a unified control plane of Nomad instead of having to custom iptables your nodes.
