### ISSUE TITLE
[question] Template registry secret

### ISSUE THREAD

**Issue by albttx** [hashicorp/nomad#5530]
### Nomad version
`Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)`

### Question 

I have some variable in a file, i tried in yaml format and env format (`KEY=value`)

Using the following job: 
```
job "job-example" {
  datacenters = ["dc1"]

  group "default" {
    task "example" {
      driver = "docker"

      config {
        image = "registry.gitlab.com/xxx/xxx"
        auth {
          username = "user"
          password = "${REGISTRY_SECRET}"
        }
      }

      env {
        HOST = "${NOMAD_IP_http}"
        PORT = "${NOMAD_PORT_http}"
      }

      template {
        data = <<EOL
          REGISTRY_SECRET = "{{key "REGISTRY_SECRET"}}"
        EOL

        destination = "secret.yml"
        # destination = "secret.env"
        env         = true
      }

      resources {
        network {
          port "http" {}
        }
      }
    }
  }
}
```

This create a `Failed to pull` issue because of incorect password

I tried using `'{{key "REGISTRY_SECRET"}}'` as someone mention in [gitter](https://gitter.im/hashicorp-nomad/Lobby)

How can i make this work ? 

I know vault would be the best, but for now, i just need something that simple

**Comment by cgbaker** [comment]
I achieved this using an almost identical copy of your job spec and nomad-0.8.7:
```
job "example" {
  datacenters = ["dc1"]
  group "cache" {
    task "redis" {
      driver = "docker"
      config {
        image = "cgbaker/private-repo:redis"
        auth {
          username = "cgbaker"
          password = "${REGISTRY_SECRET}"
        }
      }
      template {
        data = <<EOL
          REGISTRY_SECRET = "{{key "REGISTRY_SECRET"}}"
        EOL
        destination = "secret.yml"
        env         = true
      }
    }
  }
}
```

You can see the allocation initially fails because I intentionally put a bad password in Consul, then succeeds after I update Consul with my correct docker hub password: 
```
2019-04-09T12:35:53Z  Started         Task started by client
2019-04-09T12:35:48Z  Driver          Downloading image cgbaker/private-repo:redis
2019-04-09T12:35:30Z  Restarting      Task restarting in 18.153478751s
2019-04-09T12:35:30Z  Driver Failure  failed to initialize task "redis" for alloc "c3110985-02a8-9047-7b17-3f40a98a90da": Failed to pull `cgbaker/private-repo:redis`: API error (500): {"message":"Get https://registry-1.docker.io/v2/cgbaker/private-repo/manifests/redis: unauthorized: incorrect username or password"}
2019-04-09T12:35:29Z  Driver          Downloading image cgbaker/private-repo:redis
2019-04-09T12:35:29Z  Task Setup      Building Task Directory
2019-04-09T12:35:29Z  Received        Task received by client
```

Are you sure that your credentials are correct?

**Comment by albttx** [comment]
Oh ! i thought i could parse from a local file without using consul. (is that possible by the way ?)

**Comment by cgbaker** [comment]
No, there is currently no interpolation performed from local files ("local" here meaning the on the job submitter's machine using the Nomad CLI). We're tracking issues related to such a capability in #1185.

Was that the source of the problem?

**Comment by albttx** [comment]
It was, thank you for your help 👍 and sorry for the misunderstanding
