### ISSUE TITLE
[feature] - add namespace label to nomad.client.allocs.*

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#5554]
Using namespaces it's suddenly possible to have multiple jobs with the same jobname running.

In our case, the Telemetry data is made available to service owners & developers but without some unique identifier we can no longer route those events correctly :(

I would like to propose adding the namespace as an additional label to all nomad.client.allocs.* metrics in order to make ☝️ possible. 

Example : `nomad.client.allocs.<Namespace>.<Job>.<TaskGroup>.<AllocID>.<Task>.metric`

**Comment by cgbaker** [comment]
Agreed. I'll take this to the team, this should be pretty easy to get in.

**Comment by henrikjohansen** [comment]
@cgbaker Any updates on this?

**Comment by cgbaker** [comment]
@henrikjohansen , we didn't get it in for the upcoming 0.9.2, but we have put it on the list for 0.9.3. apologies for the delay on this.

**Comment by cgbaker** [comment]
@henrikjohansen , merged, will be part of upcoming 0.9.4.
