### ISSUE TITLE
[feature] - add a 'nomad acl token list' subcommand

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#5555]
There seems to be no way to list all existing ACL tokens using the CLI (even though there seems to be an [API endpoint](https://www.nomadproject.io/api/acl-tokens.html#list-tokens) for it.

This is inconvenient and slightly confusing since there is a subcommand to list all existing ACL policies ...

**Comment by cgbaker** [comment]
Good point. I'll check this out, I can't think of a reason why this is absent.

**Comment by cgbaker** [comment]
This will ship in the upcoming 0.9.1

**Comment by henrikjohansen** [comment]
@cgbaker This did not make it into v0.9.1 ... and I cannot see any mentioning of it in the v0.9.2 changelog ... will this make it into v0.9.3 then ?

**Comment by cgbaker** [comment]
Hi @henrikjohansen, it is in v0.9.2: 
https://github.com/hashicorp/nomad/pull/5557

https://www.nomadproject.io/docs/commands/acl/token-list.html

My apologies, I forgot to add it to the changelog.
