### ISSUE TITLE
[question]/[bug]? Consul Agent Default ACL token not used by Nomad Client

### ISSUE THREAD

**Issue by sgtang** [hashicorp/nomad#5563]
EDIT: Our issue is resolved if we set a static token in all three places (Nomad config as well as the default + agent token), so we'll just do that for now. Just wondering whether the docs are correct that Nomad should use the default if the Nomad token isn't set.

Believe it is this issue: https://github.com/hashicorp/consul/issues/4372

### Nomad version
Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"

### Issue
EDIT: This seems to only come up when we're rotating Consul ACL tokens with short TTLs using `consul acl set-agent-token`. Seems like jobs keep trying to use old Consul ACL tokens even after the default token for the agent is set to a new token.

Nomad seems to ignore the default Consul ACL token set on the local Consul agent; Nomad can only communicate with Consul when "token" is explicitly set under the `consul` stanza in Nomad configuration. Our Nomad jobs (run in Docker containers) also seem to ignore the default Consul token, which means they cannot read from the KV store or retrieve addresses and ports of services from Consul. 

The Nomad documentation for the `token` field says:

`
Specifies the token used to provide a per-request ACL token. This option overrides the Consul Agent's default token. If the token is not set here or on the Consul agent, it will default to Consul's anonymous policy, which may or may not allow writes.`

This seems to imply that setting the default Consul ACL token should be used if the token is not set in the Nomad config. Are the docs incorrect/is this the intended behavior?

### Reproduction steps
On the Nomad client (with Consul agent):
`consul acl set-agent-token -token 'management-token' default 'management-token'`
`consul acl set-agent-token -token 'management-token' agent 'management-token'
`

Check errors in consul logs:
```
Apr 14 18:47:21 nomad-client-0 consul[25397]:     2019/04/14 18:47:21 [ERR] consul: "Catalog.Register" RPC failed to server 10.13.16.17:8300: rpc error making call: rpc error making cal
Apr 14 18:47:21 nomad-client-0 consul[25397]:     2019/04/14 18:47:21 [WARN] agent: Syncing service "_nomad-task-x7pxq36a6nx35si6wdcf7czfjy6d7azb" failed. rpc error making call: rpc err
Apr 14 18:47:21 nomad-client-0 consul[25397]:     2019/04/14 18:47:21 [ERR] agent: failed to sync changes: rpc error making call: rpc error making call: ACL not found
Apr 14 18:47:21 nomad-client-0 consul[25397]: consul: "Catalog.Register" RPC failed to server 10.13.16.17:8300: rpc error making call: rpc error making call: ACL not found
Apr 14 18:47:21 nomad-client-0 consul[25397]: agent: Syncing service "_nomad-task-x7pxq36a6nx35si6wdcf7czfjy6d7azb" failed. rpc error making call: rpc error making call: ACL not found
Apr 14 18:47:21 nomad-client-0 consul[25397]: agent: failed to sync changes: rpc error making call: rpc error making call: ACL not found
```

### Nomad config
```
consul {
    # The address to the Consul agent.
    address = "localhost:8500"
    # The service name to register the server and client with Consul.
    server_service_name = "nomad-servers"
    client_service_name = "nomad-clients"
    # Enables automatically registering the services.
    auto_advertise = true

    # Enabling the server and client to bootstrap using Consul.
    server_auto_join = true
    client_auto_join = true
}
```

**Comment by danlsgiga** [comment]
I'm facing the very same issue after I integrated Vault to generate on the fly Consul ACL tokens. In our case, we update the `acl_default_token` via the cli command: `consul acl set-agent-token default xxxx`. But after Vault rotates the Consul ACL and we inject a the new Consul ACL token via the method above, Nomad calls starts to fail with the same errors and we start to see duplicate entries in Consul for the Catalog since Nomad was unable to deregister the previous task allocation health checks in Consul

```
[ERR] consul: "Catalog.Deregister" RPC failed to server 1.2.3.4:8300: rpc error making call: rpc error making call: ACL not found
```

Restarting the consul agent seems to solve the issue until our out-of-band process generate new Consul ACL tokens via Vault.

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Consul tokens in the Nomad agent configuration for purposes of giving workload access to Consul KV. Nomad will use workload identities to sign into Consul for purposes of getting Consul tokens for those workloads.
