### ISSUE TITLE
[feature] Environment variable for docker networking

### ISSUE THREAD

**Issue by DhashS** [hashicorp/nomad#5564]
Nomad supports the range of `NOMAD_HOST` environment variables, which can be useful in service discovery assuming the container is allowed to accept connections on behalf of the host.

In my setup, I have `network_mode = "weave"` to assign every container a unique, routable IP. Services register with the `service` stanza, and configuration is pulled down from consul via the `template` stanza.

When the container is looking for an IP address to bind to, it'd be useful to have the `NOMAD_CONTAINER` set of variables to denote it's internal docker network (the 172. ip address), and any others in the `NetworkSettings.Networks` key in `docker inspect`, with environment variables like `NOMAD_CONTAINER_<network_name>`

**Comment by dantoml** [comment]
@DhashS An upcoming release of Nomad will support doing network namespaces via the CNI, which will make this much easier to achieve. That specific solution however, would be complicated by the existence of commands like `docker network connect` that can invalidate the state we'd provide via `env`.

It should be possible for you to introspect the `ethwe` network in your docker-entrypoint before support for CNI ships however?

**Comment by DhashS** [comment]
Thanks! Inspecting `ethwe` does the job!
