### ISSUE TITLE
Nomad 0.9.0 Client deadlocks when starting after reboot

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#5566]
Originally reported by @vkiranananda here: https://github.com/hashicorp/nomad/issues/2560#issuecomment-482808629

### Nomad version
```Nomad v0.9.0 (18dd59056ee1d7b2df51256fe900a98460d3d6b9)```

### Operating system and Environment details

dev vagrant box

### Issue

When a node (the actual VM or server) is reboot Nomad deadlocks on startup trying to restore Docker tasks.

### Reproduction steps

On the dev vagrant box with Nomad 0.9.0 installed with [this config file.](https://gist.github.com/schmichael/579e22c5bd64cd9a3b05e81c3a0964e9)

Terminal 1:
```
curl https://gist.githubusercontent.com/schmichael/579e22c5bd64cd9a3b05e81c3a0964e9/raw/f3bb5ed8a2aeebc1aeccf24e86f508472418592e/devagent.hcl > devagent.hcl
sudo nomad agent -config devagent.hcl
```

Terminal 2:
```
nomad init 
nomad run example.nomad
# wait for job to be running
^D # logout of vagrant box
vagrant halt
vagrant up
vagrant ssh
sudo nomad agent -config devagent.hcl
# deadlocks
```

### Job file (if appropriate)

Example job (w/o service stanza)

### Nomad Client logs (if appropriate)

Full logs + goroutine dump here: https://gist.github.com/schmichael/b0f663b293c9f2c47e2790c4f9f8fb70

**Comment by schmichael** [comment]
Killing the docker_logger unblocks the client and causes it to start a new alloc. Task events from original alloc:
```
2019-04-15T22:33:46Z  Killing           Sent interrupt
2019-04-15T22:33:46Z  Restarting        Task restarting in 15.954383114s
2019-04-15T22:33:46Z  Task hook failed  logmon: Reattachment process not found
```

**Comment by MorphBonehunter** [comment]
maybe this is related to #5561 ?

**Comment by schmichael** [comment]
@MorphBonehunter Oh interesting! Yes! The only difference is that you kill all Nomad processes but the container is still running. I actually like your repro much better.

Going to close #5561 just because we've already started referencing this issue in PRs and internal comms. Sorry for missing yours and thanks for commenting. Fix is landing soon.
