### ISSUE TITLE
Template: restart all tasks if fail

### ISSUE THREAD

**Issue by vkiranananda** [hashicorp/nomad#5567]
Hello!
I have config 

```
      template {
        data        = "{{ range ls \"fedsp/apache2/sites-enabled\" }} {{ .Value }} \n\n {{ end }}"
        destination   = "sites-enabled/sites.conf"
      }

```

replicas
    count = 2

if I change key in the consul and it have error my tasks restart all and my task is fail...

**Comment by dantoml** [comment]
Hey @vkiranananda,

Consul template changes are made fairly quickly to all tasks when changes get made, if you wish to do a rolling deploy of configuration changes, you may want to skip using consul template and have the configuration in your job file to allow for use of nomads deployment tooling.

**Comment by vkiranananda** [comment]
thank you @dantoml.
How can I put my configs on nodes where running my task?

And I try it

```
      template {
        data        = "{{ range ls \"fedsp/apache2/sites-enabled\" }} {{ .Value }} \n\n {{ end }}"
        destination   = "my-configs/sites.conf"
        change_mode   = "signal"
        change_signal = "SIGUSR1"
      }
```
If my config gives error then apache terminated...

**Comment by schmichael** [comment]
You should use deployments if you want automated rollbacks of bad configurations: https://www.nomadproject.io/guides/operating-a-job/update-strategies/index.html

This requires either bundling your config file in a Docker image or downloading it as an artifact:

```hcl
      artifact {
        source      = "http://somewhere.internal/sites-v20190416.conf"
        destination = "my-configs/sites.conf"
      }
```

You could put `consul-template` and an HTTP server in a task group to create and host versioned config files generated from Consul, as well as POST the new job to Nomad. Unfortunately it's quite a bit of extra work versus your template approach.

**Comment by vkiranananda** [comment]
Thank you @schmichael . I put my configs in image :)
