### ISSUE TITLE
[Question]: Nomad hardening and SELinux

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5571]
Hi,

I could not find any guides from [Nomad Docs](https://www.nomadproject.io/docs/index.html) or [Hashicorp Learn](https://learn.hashicorp.com/)  on hardening a Nomad environment.

Our specific use-case here is in a packaged product where our services are run and scheduled via Nomad. Our intended target user however has no physical, software or network based access to the Machine, OS or Nomad.

My questions therefore are:

* Does the use of SELinux make sense here in conjunction with Nomad and the security benefits already obtained through process level isolation, private private networking and the OS and Nomad itself inaccessible to the outside?
* If SELinux still makes sense (*e.g: setting up file permission policies on allocation directories*) -- What guidelines exist for this?

Thanks!

cheers
James

/cc @johnzhanghua

**Comment by hvindin** [comment]
Just from my experience running nomad in an environment I am which SElinux is a mandatory security control -

There are a few things that don't play 100% nice, especially with the docker driver.

As an example, we have noticed that artifacts don't seem to work without creating some local context rules under nomad data directory. At the same time, if you do recontext stuff there you need to be a bit careful as setting the context to something that a container can read will likely break nomads ability to read stdout and stderr.

Admittedly this might also just be an overflow effect if some of the other selinux stuff we have going on in our environment, I haven't actually tested out a totally vanilla install with SElinux to see how it goes.
