### ISSUE TITLE
Cannot launch VPN container in privileged mode

### ISSUE THREAD

**Issue by AssenDimitrov** [hashicorp/nomad#5588]
### Nomad version
0.9.0

### Operating system and Environment details
Nomad server and client are running on Ubuntu 16.04

### Issue
Cannot launch L2TP server container in privileged mode.
The output from the Nomad UI is  "Docker privileged mode is disabled on this Nomad agent"
When I go to Nomad UI, select a client and click "Details" on docker service, I can see that Privileged mode is set to True.

### Reproduction steps
Just try to deploy the below mentioned container.

### Job file (if appropriate)

===== Job 

```
   task "l2tp" {
    driver = "docker"
    config {
        image = "teddysun/l2tp:alpine"
        privileged = true
        volumes = [
          "/lib/modules:/lib/modules"
        ]
        args = [
          "-p","500:500",
          "-p","4500:4500"
        ]
    }
   env {
        "VPN_IPSEC_PSK" = "test"
        "VPN_USER" = "test"
        "VPN_PASSWORD" = "test!"
        "VPN_PUBLIC_IP" = "0.0.0.0"
    }

  }
```

===== Client Config

```
data_dir ="/var/lib/nomad/data"
datacenter = "hatchery-deployment"
client {
  options {
        "docker.privileged.enabled" = "true"
        "driver.raw_exec.enable"    = "1"
}
  enabled = true
  servers = ["192.168.10.1:4647"]
}
consul {
  address = "localhost:8500"
}

```

### Nomad Client logs (if appropriate)

```
   2019/04/19 16:17:50.145694 [ERR] driver.docker: failed to start container adbb02dab61ad0af4bdd203f8a0b6dec30a68c481556291fe9c913145b3162e5: API error (400): {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"-p\\\": executable file not found in $PATH\": unknown"}
2019-04-19T16:17:50.146+0300 [DEBUG] plugin.nomad: 2019/04/19 16:17:50 [ERR] plugin: plugin server: accept unix /tmp/plugin457787945: use of closed network connection
2019-04-19T16:17:50.148+0300 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/nomad
    2019/04/19 16:17:50.148889 [WARN] client: failed to start task "l2tp" for alloc "61bf754a-4295-a76a-58a3-2105aa6a419c": Failed to start container adbb02dab61ad0af4bdd203f8a0b6dec30a68c481556291fe9c913145b3162e5: API error (400): {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"-p\\\": executable file not found in $PATH\": unknown"}
    2019/04/19 16:17:50.161643 [INFO] client: Not restarting task: l2tp for alloc: 61bf754a-4295-a76a-58a3-2105aa6a419c
    2019/04/19 16:17:50.162315 [INFO] client.gc: marking allocation 61bf754a-4295-a76a-58a3-2105aa6a419c for GC
    2019/04/19 16:17:55.351432 [INFO] client: node registration complete
```

### Nomad Server logs (if appropriate)

`failed to start task "l2tp" for alloc "8a2f56df-e542-af09-068e-0182ec5e8463": Failed to create container configuration for image "teddysun/l2tp:alpine" ("sha256:86f17d62df9c9dd4e40f5c0e1743b860752fb45d70c54cd5290bf76c5ed24537"): Docker privileged mode is disabled on this Nomad agent`

**Comment by preetapan** [comment]
@AssenDimitrov  - your hcl looks incorrect to me, it should be: 

```
client {
  options {
    docker.privileged.enabled = "true"
    ...
  }
}
```

Can you try that and let us know if that fixed it.

**Comment by notnoop** [comment]
@AssenDimitrov I see conflicting reasons from the logs: one log line reports:

```
    2019/04/19 16:17:50.148889 [WARN] client: failed to start task "l2tp" for alloc "61bf754a-4295-a76a-58a3-2105aa6a419c": Failed to start container adbb02dab61ad0af4bdd203f8a0b6dec30a68c481556291fe9c913145b3162e5: API error (400): {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"-p\\\": executable file not found in $PATH\": unknown"}
```

So it looks like `-p` of args was interpreted to be an executable.  Can you try passing the `command` explicitly?

As for the privileged log line, I would have expected the log message to appear in the nomad client not the nomad server and it's referencing a different container id!  Do you configure nomad server to run tasks too?  If so, it's possible that task was rescheduled to server, and if the nomad server isn't configured with privileged flag in its config.
