### ISSUE TITLE
[Question]: Updated API Docs?

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5595]
* Q: Are the [API Docs](https://www.nomadproject.io/api/) up-to-date?

> If not can we get them updated please? :)

**Comment by dantoml** [comment]
@prologic They are usually updated alongside changes to the API or soon-afterwards (e.g before a feature is released). However, if you spot anything that appears to be out of date or missing then please file an issue and we're more than happy to update them.

Thanks!

**Comment by prologic** [comment]
The one thing I found so far that is undocumented is the use of `WaitIndex`.
