### ISSUE TITLE
[Question]: Parameterized job array params

### ISSUE THREAD

**Issue by amfern** [hashicorp/nomad#5596]
I want to dispatch job with different artifacts count each time, is it possible to substitute artifacts with array param?

**Comment by preetapan** [comment]
@amfern artifacts in our API are already an array https://github.com/hashicorp/nomad/blob/5ea4382af7c836ccbc8bbcd763691aad0cccd2e2/api/tasks.go#L688 

Could you describe your use case some more? If you are asking about being able to dispatch the same job with different parameters try using the [payload field] (https://www.nomadproject.io/docs/commands/job/dispatch.html#usage) field which is sent to your dispatched instance.

**Comment by amfern** [comment]
I want to dispatch job with variable artifacts for example,  first dispatch with one artifact but the second dispatch with 3 artifacts

**Comment by preetapan** [comment]
@amfern we currently do not support that. This is not a commonly requested use case. For now, your work around is to create all the artifacts the job needs in the job spec, such that they are available to the dispatched instance under `local`. You can then use the `meta` or the `payload` in the dispatched instance as a way inside the dispatched instance to decide which of those artifacts to actually use at run time.

I am going to close this ticket as this is not something we intend to do right now. We can consider reopening if there is more community demand.
