### ISSUE TITLE
Coloring of console output

### ISSUE THREAD

**Issue by Telavian** [hashicorp/nomad#5603]
Currently Stdout/Stderr is displayed as plain text in the Nomad UI however depending on the application the text can be displayed with color.
Color of course makes certain things vastly easier to see.
This of course would be a low priority however it would be helpful in certain cases.

Using this file for testing the console prints several colors.
The raw file may need to be downloaded depending on how your browser displays things.
In addition that file is attached in a txt file format.

[win10colors.txt](https://github.com/hashicorp/nomad/files/3109911/win10colors.txt)

https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011

**Comment by preetapan** [comment]
@Telavian is this windows specific?

**Comment by Telavian** [comment]
I honestly have never used nomad on a non-windows machine.
However I don't think this is windows specific unless of course it already
works in other environments.

The file I attached is probably windows specific however I could come up
with the same thing for linux if needed.

**Comment by preetapan** [comment]
Nevermind, I thought this was about the CLI, now I see that its the UI that you were talking about.

**Comment by Telavian** [comment]
I don't know Go and the chances of me learning it are close to 0.
However if there is some non go work needed then I would be interested.

**Comment by DingoEatingFuzz** [comment]
Hey @Telavian, @notnoop and I did some digging into this and learned that Nomad does send ansi color codes in the API when present, but the UI wasn't doing anything to render them. 

Independently, @Mongey opened a PR to add support for rendering ansi-coded log output as HTML in the UI.

So if you test against master, you should be able to get colored logs in the UI now with one caveat: if you weren't previously seeing the ansi color coding characters in the log, then you will not see colors now. This means that your application is not logging colored output for one reason or another. The easiest way to tell if the way you have packaged and run your application is suppressing colored logs is by using the `nomad alloc logs` command.

Please feel free to reopen this issue if you think there is something deeper or windows-specific going on here.

**Comment by Telavian** [comment]
Thank you that was much quicker than I thought.
I guess it makes it a lot easier that the codes were sent already.
