### ISSUE TITLE
nomad server in two region report error

### ISSUE THREAD

**Issue by JohnMicl** [hashicorp/nomad#5605]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `Nomad v0.9.0 (18dd59056ee1d7b2df51256fe900a98460d3d6b9)`

### Operating system and Environment details
CentOS 7

### Issue
When I want to join two nomad servers in two different regions, it reports error in log.
I want to know how to solve it.
### Reproduction steps
Start two nomad servers in two different nodes, and run command
nomad server join node1 (on node2)
### Job file (if appropriate)
server1 in node 1
```
region = "region1"
datacenter = "dc-01"
log_level = "DEBUG"
data_dir = "/tmp/server1"
advertise {
  http = "10.100.100.221:4646"
  rpc = "10.100.100.221:4647"
  serf = "10.100.100.221:4648"
}
server{
  bootstrap_expect = 1
  enabled = true
}
```
server2 in node2
```
region = "region2"
datacenter = "dc-01"
log_level = "DEBUG"
data_dir = "/tmp/server1"
advertise {
  http = "10.100.100.220:4646"
  rpc = "10.100.100.220:4647"
  serf = "10.100.100.220:4648"
}
server{
  enabled = true
  bootstrap_expect = 1 
}
```
### Nomad Client logs (if appropriate)

If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

### Nomad Server logs (if appropriate)
```
Apr 24 17:35:59 node2 nomad[6435]: 2019-04-24T17:35:59.467+0800 [ERROR] nomad: skipping adding Raft peer because an existing peer is in bootstrap mode and only one server should be in bootstrap mode: existing_peer=node1.region1 joining_peer=node2.region2
```

**Comment by preetapan** [comment]
@JohnMicl if you have two servers, change `bootstrap_expect = 1` to `bootstrap_expect = 2`. 

We don't recommending running with even number of servers, you should run with 3 or 5. see https://www.nomadproject.io/docs/internals/consensus.html#deployment-table for more information.
