### ISSUE TITLE
Multi-region Federation reports an error in logs

### ISSUE THREAD

**Issue by JohnMicl** [hashicorp/nomad#5610]
### Nomad version
Output from `Nomad v0.9.0 (18dd59056ee1d7b2df51256fe900a98460d3d6b9)`

### Operating system and Environment details
OS: CentOS 7
### Issue
I have a singel server(eg. server A) cluster in region A, a single server(eg. serverB) cluster in region B, both with bootstrap = 1. 
When I want to **make a multi-region federation**, I run the command in 
serverB ` nomad server join serverA_IP`, it also works , and I can use the command `nomad server members` to see both servers in any region.
The problem is, when I saw the nomad logs, it reported an error:
`[ERROR] nomad: skipping adding Raft peer because an existing peer is in bootstrap mode and only one server should be in bootstrap mode: existing_peer=nodeA.regionA joining_peer=nodeB.regionB`
I want to known why it outputs an error, two servers are all leaders in their own region.
When I use consul to make **a multi-region federation**, it also reports the same error
### Reproduction steps
1. start a server in regionA
```
region = "regionA"
datacenter = "dc-01"
log_level = "DEBUG"
data_dir = "/tmp/server1"
advertise {
  http = "10.100.100.221:4646"
  rpc = "10.100.100.221:4647"
  serf = "10.100.100.221:4648"
}
server{
  bootstrap_expect = 1
  enabled = true
}
```
2. start a server in regionB
```
region = "regionB"
datacenter = "dc-01"
log_level = "DEBUG"
data_dir = "/tmp/server1"
advertise {
  http = "10.100.100.220:4646"
  rpc = "10.100.100.220:4647"
  serf = "10.100.100.220:4648"
}
server{
  enabled = true
  bootstrap_expect = 1 
}
```
3. run command `nomad server join 10.100.100.220:4648` in serverA
serverA join serverB OR serverB join serverA ,it doesn't matter.

### Nomad Server logs (if appropriate)
`[ERROR] nomad: skipping adding Raft peer because an existing peer is in bootstrap mode and only one server should be in bootstrap mode: existing_peer=nodeA.regionA joining_peer=nodeB.regionB`

**Comment by angrycub** [comment]
@JohnMicl Running with `bootstrap_exepct=1` will provide the same behavior as running with `-bootstrap` flag set.  That is to say, your cluster will always be in bootstrap mode.  Once the clusters are bootstrapped, you can remove that configuration element from your config and the join should behave as expected.

The bootstrap_expect configuration element doesn't control the quorum or the node counts as could be thought but only specifies how many nodes have to be heard from to enter bootstrap mode.  Once the nodes are bootstrapped, this configuration element is essentially unused in all cases _except for when it equals 1_.

If you are using single node clusters, you can forgo the configuration element entirely by running nomad one time with the `-bootstrap` flag and then exiting nomad once the node has elected itself the leader. 

I'm going to mark this issue as closed, but let me know if there is anything I can clarify.
