### ISSUE TITLE
Upgrade Nomad server and/or client

### ISSUE THREAD

**Issue by agarwalpradeep123** [hashicorp/nomad#562]
This is a question.

If I have a current version of Nomad server and client running in my cluster. Now if newer version of nomad is available, what are steps to be used to upgrade to this version.

I could not find upgrade related things in Nomad documentation.

**Comment by c4milo** [comment]
@agarwalpradeep123 you just download the new version, replace the binary and restart the service.

**Comment by agarwalpradeep123** [comment]
I would like to know exact steps or in which order I should execute them.

Consider I have Nomad cluster with 5 nomad servers and many nomad clients. So we need upgrade all of them one by one. So what would be the steps? And is there any impact on cluster of the upgrade?

**Comment by diptanu** [comment]
@agarwalpradeep123 I would suggest first updating the Nomad servers, one by one. And waiting for the leader election to finish once you have replaced all the Nomad servers.

Once that is done, you can start replacing the clients one by one. Make sure the node you have upgraded is healthy before moving on to the next one.

**Comment by agarwalpradeep123** [comment]
Does that mean new Nomad servers can work with old Nomad clients?
Is it also possible that new Nomad clients can work with old Nomad servers?

**Comment by diptanu** [comment]
@agarwalpradeep123 Yes, but we won't be able to support clients talking to very old servers or vice-versa. And if the upgrade process breaks, we will mention it on our changelogs.

**Comment by dadgar** [comment]
There is now documentation here: https://www.nomadproject.io/docs/upgrade/index.html
