### ISSUE TITLE
Allow nomad clients and servers to self-update the cluster

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#564]
Inspired by #562.

It would be really cool if nomad can self-update all the clients and servers in a cluster through a command.

I think this is something that's quite feasible for nomad because:

- Unlike other systems like mesos, nomad consists of just 1 binary, so self-updating should be very simple.
- All the information that needs to be used to roll out the updates are in nomad or consul.
- Nomad can automatically drain the tasks running on each node before update and use the staggered update logic for updating tasks here.
- There are a few libraries for handling this: https://github.com/sanbornm/go-selfupdate and https://github.com/inconshreveable/go-update

Because nomad knows about regions and datacenters, we can ask the updater to just update a certain region or datacenter. For example, a new version of nomad can be deployed in the staging environment first for testing.

**Comment by pires** [comment]
Can two different versions of `nomad` coexist?

**Comment by F21** [comment]
I believe if they are patch versions, things should be fine if they only co-exist for a few moments during upgrade. For protocol changes, the strategy used by consul should suffice: https://www.consul.io/docs/upgrading.html

**Comment by pires** [comment]
@F21 is this flag available for `nomad` or is it something to implement in the future?

**Comment by F21** [comment]
@pires It's only currently available through the configuration: https://www.nomadproject.io/docs/agent/config.html#protocol_version

But it would be useful as a flag and it wouldn't be difficult to implement. I will open a new issue for that.

**Comment by pires** [comment]
@F21 thank you, this just made my day.

**Comment by dadgar** [comment]
For now and the foreseeable future this will be an operator driven event.
