### ISSUE TITLE
Need bin file for FreeBSD

### ISSUE THREAD

**Issue by slpcat** [hashicorp/nomad#5671]
https://www.nomadproject.io/downloads.html
need bin file for FreeBSD just like consul does

**Comment by perrymanuk** [comment]
there is an actively maintained port for fbsd that you can use:
https://www.freshports.org/sysutils/nomad/

**Comment by nvx** [comment]
It looks like the FreeBSD port is often out of date by months at a time (as of writing it was last updated in October 2019). FreeBSD ports exist for eg Consul, yet there is a binary on the Consul download page as well.

Kinda curious why Nomad doesn't also build FreeBSD binaries as well as it would be pretty handy to have the official up to date builds.

**Comment by kitotik** [comment]
+1 on a FreeBSD binary release.

**Comment by tgross** [comment]
@kitotik this is going to be a wontfix, at least for now. Although we do ship FreeBSD binaries for Consul, Nomad has a lot more operating system-specific functionality (and requires CGO) and we don't have the testing coverage of FreeBSD to ensure that the binaries can be properly supported if we ship them.
