### ISSUE TITLE
[question] website: add link to learn.hashicorp.com/nomad

### ISSUE THREAD

**Issue by jweissig** [hashicorp/nomad#5689]
On the current version of the website https://www.nomadproject.io/ there is no link in the header back to https://learn.hashicorp.com/nomad/ like on other hashicorp products (vault, terraform, etc). This is a missed opportunity as learning site has some good labs, a UI demo, etc.

Is this a good idea? Should I submit a PR for it?

**Comment by Omar-Khawaja** [comment]
Hey Justin,

We're currently working on updating and transitioning some Nomad content to Learn and will link out to it soon!
