### ISSUE TITLE
[ui] left panel hide hover notifications

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#5705]
Running Nomad 0.9.1

<img width="789" alt="Screen Shot 2019-05-14 at 11 06 55" src="https://user-images.githubusercontent.com/1475276/57721219-8568e100-7638-11e9-8489-da1b0e3f4dca.png">

**Comment by backspace** [comment]
Hey! Thanks for letting us know about this, @scalp42. I tried it locally against `master` and it wasn’t happening; it turns out to have been fixed in dca386c. So you should see it when the next release comes out.

I’ll close this issue, but do let us know if you run into any other problems.

**Comment by backspace** [comment]
Here’s a GIF of it on `master`, by the way:

![allocation-tooltips](https://user-images.githubusercontent.com/43280/57724827-43986480-7651-11e9-96d5-afcd3030b71e.gif)

**Comment by scalp42** [comment]
@backspace thanks for the update much appreciated. Looking forward to next release then ❤️
