### ISSUE TITLE
cleanup falled&completed task  status

### ISSUE THREAD

**Issue by upccup** [hashicorp/nomad#5708]
now in nomd UI i can see so much failed status. how can is cleanup it? 

![image](https://user-images.githubusercontent.com/13341880/57746295-21f7b580-7703-11e9-8467-1657860c1e43.png)

**Comment by atillamas** [comment]
You can Force GC and Reconcile summary as described here: https://www.nomadproject.io/api/system.html
or you could use https://github.com/jippi/hashi-ui where you get a nice interface for Nomad

**Comment by upccup** [comment]
> You can Force GC and Reconcile summary as described here: https://www.nomadproject.io/api/system.html
> or you could use https://github.com/jippi/hashi-ui where you get a nice interface for Nomad

use 

/v1/system/reconcile/summaries  is effectived. thx
