### ISSUE TITLE
instaling on GCE

### ISSUE THREAD

**Issue by joeblew99** [hashicorp/nomad#571]
Newbies question i guess :)

I use CoreOS on GCE, but i am wondering how to deploy nomad to all Core OS servers ?
I presume that Terraform is used ?

**Comment by pires** [comment]
@joeblew99 you can use whatever you want.

I use `systemd` units to write/read to/from `etcd` cluster (all your machines should be able to access or be part of it, but I leave those details to yourself), and download and run  Consul and Nomad. Any system with `systemd` should work seamlessly.

**Comment by joeblew99** [comment]
For say 200 servers :)
And new ones being brought up and down.
Can't manually do it

**Comment by pires** [comment]
You have instance templates, instance groups and auto-scaling.

**Comment by KFishner** [comment]
hey @joeblew99 here's an example for using Terraform (on AWS), but it's the same logic for GCE:
https://github.com/hashicorp/atlas-examples/blob/master/nomad-cluster/aws-beginner-nomad-cluster/terraform/instances.tf

As you can see, Nomad is installed using the `remote-exec` provisioner:
https://github.com/hashicorp/atlas-examples/blob/master/nomad-cluster/aws-beginner-nomad-cluster/terraform/instances.tf#L62-L64

We're also working on a thorough example for deploying both Nomad and Consul that should be done this week:
https://github.com/hashicorp/atlas-examples/blob/f-nomad-0.2/nomad-cluster/aws-beginner-nomad-cluster/terraform/instances.tf

Hope that helps give some direction!
