### ISSUE TITLE
Driver exec sometimes fails to SIGKILL a task if the SIGINT is ignored

### ISSUE THREAD

**Issue by verminity** [hashicorp/nomad#5736]
### Nomad version
Nomad v0. 9.1

### Operating system and Environment details
OS: RedHat Enterprise Linux 7.3

### Issue
Driver exec sometimes fails to SIGKILL a task if the SIGINT is ignored

### Reproduction steps
I have created a simple test job made up of the following two scripts which for simplicity I have put in the /usr/bin directory of my test server:

 trap.sh:
```
#!/bin/bash
trap "echo sigint" SIGINT
trap "echo sigterm" SIGTERM

/usr/bin/trap_sleep.sh
```
trap_sleep.sh:
```
#!/bin/bash
while :
do
    sleep 60
done
```
And am running the job with the following JSON payload:
```
{
  "Job": {
    "Constraints": [],
    "Datacenters": [
      "dc1"
    ],
    "ID": "sigtest",
    "Name": "sigtest",
    "Priority": 50,
    "TaskGroups": [
      {
        "Count": 5,
        "EphemeralDisk": {
          "Migrate": false,
          "SizeMB": 500,
          "Sticky": false
        },
        "Name": "group",
        "Update": {
          "HealthyDeadline": 900000000000,
          "MaxParallel": 1,
          "MinHealthyTime": 10000000000,
          "ProgressDeadline": 0
        },
        "Tasks": [
          {
            "Artifacts": [],
            "Config": {
              "command": "/usr/bin/trap.sh",
              "args": []
            },
            "Driver": "exec",
            "Env": {
              "Redeploy": "1"
            },
            "Leader": true,
            "Name": "sigtest",
            "Resources": {
              "CPU": 200,
              "Devices": null,
              "DiskMB": 0,
              "IOPS": 0,
              "MemoryMB": 75,
              "Networks": []
            },
            "Services": []
          }
        ]
      }
    ],
    "Type": "service",
    "Update": {
      "MaxParallel": 1
    }
  }
}
```
I then try to redeploy the job by increasing the value of the Redeploy env variable and resubmitting.

When Nomad needs to stop the running allocations the script traps the default SIGINT signal and I expect Nomad to force the kill with a SIGKILL five seconds later.

Most of the time this works, but occasionally the SIGKILL is never sent. For example this log file is from an allocation that was never killed:
```
2019-05-20T16:25:21.476+0100 [DEBUG] client.driver_mgr.exec.executor: using plugin: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 driver=exec task_name=sigtest version=2
2019-05-21T10:00:10.408+0100 [DEBUG] client.alloc_migrator: waiting for previous alloc to terminate: alloc_id=56043f29-ac4a-8d31-dfce-4e55f3dfd04a previous_alloc=06db34f1-a57e-9004-27eb-942f9bf9e479
2019-05-21T10:00:30.406+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=5s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:00:55.410+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=20s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:01:35.414+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=1m20s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:03:15.418+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=2m0s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:05:35.423+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=2m0s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:07:35.423+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task. Resources may have been leaked: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
```
By running strace against the trap.sh process I can see that the SIGINT is being sent correctly so Nomad is certainly still capable of sending signals:
```
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=72333, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=72333, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1,
```
This is not perfectly reproducible but appears to happen fairly consistently if the allocation has been running for at least twelve hours to a day. If the job is redeployed quickly then the SIGKILL correctly gets sent after five seconds.
```
wait4(-1, 0x7ffea53306c0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=18014, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffea53306c0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
+++ killed by SIGKILL +++
```

**Comment by tommyvicananza** [comment]
We experienced similar issues (I think) what we did as workaround was to add "exec" in bash script, I guess in your case would be something like:
`
#!/bin/bash
trap "echo sigint" SIGINT
trap "echo sigterm" SIGTERM

exec /usr/bin/trap_sleep.sh
`

**Comment by verminity** [comment]
> We experienced similar issues (I think) what we did as workaround was to add "exec" in bash script, I guess in your case would be something like:
> 
> ```
> #!/bin/bash
> trap "echo sigint" SIGINT
> trap "echo sigterm" SIGTERM
> 
> exec /usr/bin/trap_sleep.sh
> ```

Thanks. We've actually done exactly that for the case that caused us to notice this, but I still want to understand the unlying reason for the inconsistent Nomad behaviour as there are a number of situations under which a service might fail to stop on a SIGINT. Even something simple like the missing exec in the example script can be hard to fix because to deploy a fixed version each bugged allocation needs to be killed manually.

**Comment by cgbaker** [comment]
I tried to reproduce this issue, using the job spec and the example scripts. I have not been able to reproduce it as of yet. I tried with some long-running (12+ hour) allocations. I also tried restarting the Nomad client and server, to see if that is related.

I will investigate the code and see if there are any potential causes. In the meantime, any additional information that other folks have would be appreciated.

**Comment by verminity** [comment]
Thanks for investigating. I have managed to compile from source locally and have added some additional logging into the executor_linux Shutdown method to see if I can see what is going on.

It will be a little while before I can feedback as I still can't reproduce the issue without waiting hours, but let me know if you think there is any addional code I can add to help debug this.

**Comment by cgbaker** [comment]
That's great, @verminity. More information about what is happening in that method, esp as regards the return point and any errors, would definitely be helpful in figuring out where the problem is. Please let us know when/if you're able to find anything.

**Comment by verminity** [comment]
Ok, so I still can’t reliably reproduce the issue, but I have a better understanding of what the issue is.

Looking at the code for executor_linux.go I noticed that the SIGINT is sent to the root process, but that SIGKILL is sent to everything in the cgroup:

```
// Signal initial container processes only during graceful
// shutdown; hence `false` arg.
err = l.container.Signal(sig, false)
```

```
// Force kill all container processes after grace period,
// hence `true` argument.
if err := l.container.Signal(os.Kill, true); err != nil {
```

This led me to wonder if the cgroups were becoming corrupt in some way so I started tracking them. This is what /proc/<allocation executor pid>/cgroup looks like after a new allocation is started:

```
11:freezer:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
10:pids:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
9:cpuset:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
8:memory:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
7:devices:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
6:hugetlb:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
5:perf_event:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
4:cpuacct,cpu:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
3:blkio:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
2:net_prio,net_cls:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
1:name=systemd:/system.slice/centrify-sshd.service/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
```

And this is what the same file looked like the following day:

```
11:freezer:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
10:pids:/
9:cpuset:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
8:memory:/
7:devices:/system.slice/centrify-sshd.service
6:hugetlb:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
5:perf_event:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
4:cpuacct,cpu:/
3:blkio:/
2:net_prio,net_cls:/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
1:name=systemd:/system.slice/centrify-sshd.service/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7
```

Somewhere along the line it appears that parts of the cgroup have been removed and the process has moved back up the hierarchy to the root.

Without digging too much into the code of the runc library I am going to assume that this corruption of the cgroups is stopping the SIGKILL from being sent to all child processes.

I’m still trying to figure out the underlying cause of this but it does not seem to happen on Nomad 0.8.5. The most notable difference I can find is that on 0.8.5 the cgroups get allocated to a nomad slice at the root of the systemd tree:

`1:name=systemd:/nomad/3a92dec0-1c90-1f07-aae3-ccd42bfd04c1`

Whereas 0.9.1 creates the cgroups below the service that starts Nomad in the system slice:

`1:name=systemd:/system.slice/centrify-sshd.service/nomad/f01533e5-0749-f081-5cc9-b3c8d7d042c7`
(Note that we don’t actually run Nomad directly as a systemd service and in this example it was started via an ssh terminal so has ended up belonging to that service)

My current guess is that there is some kind of automated cleanup of the system slice and it is incorrectly removing some parts of the Nomad allocation cgroups but I’m having difficulty proving or forcing it to happen.

**Comment by verminity** [comment]
I have figured out how to reproduce the issue and have managed to replicate it on a fresh Azure RHEL VM so I don't think it is being caused by any additional software we may have installed.

The problem is that if Nomad creates cgroups under system.slice then systemd will remove those cgroups as something I assume is a cleanup process. One way I have found to trigger this is to run the `localectl` command which internally causes systemd to start and stop a service.

(In fact this is what was causing my initial "leave the job running for twelve hours or so" confusion. Our servers are running puppet to keep them consistent and puppet was using localectl to ensure the locale was set correctly) 

To reproduce you can do the following:

1. Install and run Nomad as a systemd service using the unit file from the repo (dist/systemd/nomad.service)
2. Start a job with the exec driver
3. Check `systemctl status` and note that the cgroup for the allocation has been created under the nomad.service which is under the system.slice
4. `cat /proc/executor-pid/cgroup` to confirm that the cgroup is fully populated
5. Run `localectl`
6. `cat /proc/executor-pid/cgroup` to confirm that the cgroup has been deleted

You can repeat this process but this time run Nomad through bash instead of systemd. Now the allocation cgroups will be created under the user.slice and will not be deleted.

I have managed to mitigate this by changing the unit file to call a script that contains the following:

`systemd-run --scope --slice=nomad.slice /usr/local/bin/nomad agent -config /etc/nomad.d`

This causes systemd to run the Nomad exe in its own slice directly below the root. Now the cgroups are created in that slice and are not affected by the cleanup.

Fair warning that I have not done any testing on the impact that doing this has on systemd's ability to manage the Nomad service as our real-world setup is a bit more complicated.
