### ISSUE TITLE
Stopping or removing job which is not in running state

### ISSUE THREAD

**Issue by agarwalpradeep123** [hashicorp/nomad#574]
I am using docker driver. I have scheduled a job with following restart policy,
                restart {
			interval = "5m"
			attempts = 0
			delay = "25s"
		}

As you can see I do not want to restart this job as its one time job which might have finished or might have some erroneous code which caused docker container to fail to start.

Now if I run "nomad stop <job>" command then it does not remove stopped container and its corresponding image from Nomad client node.

**Comment by diptanu** [comment]
@agarwalpradeep123 Can you please share your job definition? I think you're using the ```service``` scheduler for your job, in which case Nomad will always restart your job no matter what.

Please use the ```batch``` scheduler and use the following restart policy 

```
restart {
   attempts = 0
   delay = "25s"
}
```

**Comment by agarwalpradeep123** [comment]
I tried with batch scheduler as well, but it also did not remove docker container and docker image.

My job definition is,
job "example" {
	datacenters = ["dc1"]
	type = "batch"
	update {
		stagger = "10s"
		max_parallel = 1
	}
	group "app" {
		restart {
			attempts = 0
			delay = "25s"
		}

		task "app" {
			driver = "docker"

			config {
				image = "test1"
				port_map {
					endpoint = 8080
				}
			}

			service {
				name = "bwapp"
				port = "endpoint"
				check {
					name = "alive"
					type = "http"
					interval = "10s"
					path = "/_ping"
					timeout = "2s"
				}
			}

			resources {
				cpu = 500 # 500 Mhz
				memory = 256 # 256MB
				network {
					mbits = 10
					port "endpoint" {}
				}
			}
		}
	}
}

**Comment by diptanu** [comment]
@agarwalpradeep123 But I hope the task was not restarted with the batch scheduler? Nomad removes images, containers and alloc dirs of containers when the Alloc is GCed which might be a little while later.

cc/ @dadgar

**Comment by dadgar** [comment]
@agarwalpradeep123: Can you configure the client to have debug level logging and post those when you do a nomad stop. The docker driver should log why it couldn't delete the image. Often it is because it is being used by other docker containers.

**Comment by dadgar** [comment]
@agarwalpradeep123: There is a new restart policy in which you can set `on_success` to false to make sure it doesn't restart.
