### ISSUE TITLE
[question] What is the ETA for incorporating the restart allocation feature in the official Nomad UI?

### ISSUE THREAD

**Issue by bhope** [hashicorp/nomad#5744]
Hello,

I see that there was a PR - https://github.com/hashicorp/nomad/pull/5502 for the above feature for api. Can we have an ETA on the UI version of this feature?

- Prathamesh

**Comment by DingoEatingFuzz** [comment]
I just merged the UI piece! #5734 It will land in 0.9.2 😄

**Comment by bhope** [comment]
Great, thanks! :D
