### ISSUE TITLE
add task group scaling controls to UI

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/nomad#5756]
When using the Nomad UI, we find ourselves wanting to adjust the `Count` parameter of a Task Group pretty often. It would be nice to have some controls around this common JobSpec edit pattern similar to what [jippi/hashi-ui](https://github.com/jippi/hashi-ui) has:

<img width="325" alt="Hashi-UI Task Group count controls" src="https://user-images.githubusercontent.com/222027/58270774-90b6bd80-7d58-11e9-984e-69c039810a44.png">

In essence; the buttons there are a short-hand for modifying the Job Definition Task Group Count parameters.
- Up Arrow ⬆️ Increases the Task Group Count by 1
- Down Arrow ⬇️  Decreases the Task Group Count by 1
- Circular Arrow 🔄 Sets the Task Group Count to 0, then back to whatever it was previous (effectively re-starting all allocations)
- Stop 🔲Sets the Task Group Count to 0

With the introduction of `nomad alloc restart`; maybe the restart process could take advantage of that instead of using job submission as a proxy for it?

**Comment by scalp42** [comment]
I think one of the challenges with this approach is that you tend to run into job drift where the job spec (say for example, stored in Github) differs from the server side.

I believe you can specify an index with `nomad plan` to prevent some issues but still.

**Comment by justenwalker** [comment]
@scalp42 That is not really a challenge of this approach in specific. A UI enhancement such as the one proposed here is not fundamentally different than the already existing Edit Job Definition that exists currently. 

If one of your requirements is that your Job Spec be checked into source control and be identical to the one deployed in your nomad cluster; then editing the Job Spec in *any* way will break that requirement. In such an environment, you'd likely need to make your anonymous ACL policy read only to prevent job submissions except through approved channels; Otherwise, anyone with access to the Nomad API/UI could change jobs on a whim.

**Comment by endocrimes** [comment]
👋  - There are plans to support job scaling in the future that will allow for scaling without encountering job drift, but they're unlikely to come in the short-term. I'll keep this issue open for when we release that feature however.

**Comment by scalp42** [comment]
@endocrimes any chance you could share the details regarding job drift?

**Comment by endocrimes** [comment]
@scalp42 It's unclear exactly what form the api will take right now, but it'll likely come after we support HCL2 so we can support some type of scaling variable or similar.

**Comment by TheRevenantStar** [comment]
I might be chiming in at the wrong time here but...
To prevent drift (at least when it comes to scaling) why not just have nomad throw a warning and require confirmation when the jobsec and server counts differ? Personally, I like to keep the spec and runtime scales different to prevent anyone from blasting the server with a large number of allocs by accident.

**Comment by tgross** [comment]
With the Scaling API we do expose the recent scaling events, but we don't expose a +1/-1 button, which is totally feasible now. I'm going to rename this issue for clarity.

<img width="485" alt="Screen Shot 2022-07-25 at 3 47 51 PM" src="https://user-images.githubusercontent.com/1409219/180862148-e6af5d2d-85e6-4595-92a7-ca727530f8b6.png">

**Comment by tgross** [comment]
Rolling back to this it looks like this actually _is_ exposed already on the task group row when a job has `scaling { enabled = true }`. This was added in https://github.com/hashicorp/nomad/pull/8207

![scaling](https://github.com/hashicorp/nomad/assets/1409219/e4ef47f2-540b-4b0a-8b61-7b246db36e40)
