### ISSUE TITLE
Template will not load envs with key containing a '/'

### ISSUE THREAD

**Issue by sstent** [hashicorp/nomad#5757]
A template that pulls a tree of consul k/v's renders fine, but the job fails if I try to load them into the env. 

```
      template {
      data = <<EOF
      {{ range tree (printf "%s" (env "prod")) }}
      {{ .Key }}="{{ .Value }}"{{ end }}
      EOF
      destination = "/secrets/consul.env"
      env = true
            }
```

It works fine if only have one layer of KVs, but if any of them are in a sub dir of consul, then it appears that the '/'  causes a failure in nomad/go-envparse

**Comment by preetapan** [comment]
@sstent Based on a quick glance at the source code, you need to escape the slash  - https://github.com/hashicorp/go-envparse/blob/master/envparse.go#L219

**Comment by sstent** [comment]
@preetapan since the / in key in question is being generated by consul (i.e. it's the pseudo path to a value) it's not clear how one might escape it?

I would expect the environment loading in nomad to support the same keys as envconsul in this case.

Example:

In consul i have;

Toplevel/sublevel/key = value

**Comment by sstent** [comment]
@preetapan If I'm reading that code correctly - it looks like only the value supports escaping and the key only supports [A-Za-z][A-Za-z0-9_]. 

Unfortuntely this means that the template method in nomad probably doesn't offer a 1:1 replacement for envconsul (we're trying to get away from envconsul, as injecting the vars this way makes troubleshooting alot easier)

```
	key, value := bytes.TrimSpace(parts[0]), bytes.TrimSpace(parts[1])

	// Ensure key is of the form [A-Za-z][A-Za-z0-9_]? with an optional
	// leading 'export ', but only trim leading export if there's another
	// key name.
	if len(key) > len(exportPrefix) {
		key = bytes.TrimPrefix(key, exportPrefix)
	}
	if len(key) == 0 {
		return nil, nil, ErrEmptyKey
	}
	if key[0] < 'A' {
		return nil, nil, fmt.Errorf("key must start with [A-Za-z_] but found %q", key[0])
	}
	if key[0] > 'Z' && key[0] < 'a' && key[0] != '_' {
		return nil, nil, fmt.Errorf("key must start with [A-Za-z_] but found %q", key[0])
	}
	if key[0] > 'z' {
		return nil, nil, fmt.Errorf("key must start with [A-Za-z_] but found %q", key[0])
	}

	for _, v := range key[1:] {
		switch {
		case v == '_':
		case v == '.':
		case v >= 'A' && v <= 'Z':
		case v >= 'a' && v <= 'z':
		case v >= '0' && v <= '9':
		default:
			return nil, nil, fmt.Errorf("key characters must be [A-Za-z0-9_.] but found %q", v)
		}
	}
```

**Comment by sstent** [comment]
https://github.com/hashicorp/go-envparse/issues/3#issue-448227813
