### ISSUE TITLE
Can't get contraints to work

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#5758]
We have a bunch of Nomad servers (referred as `nomad-i*`) and Nomad clients (referred as `nomad-compute-i*`).

Nomad servers have a meta attribute set to `nomad-server` and Nomad clients have a meta attribute set to `nomad-compute`:

<img width="577" alt="Screen Shot 2019-05-23 at 22 21 22" src="https://user-images.githubusercontent.com/1475276/58304443-211cee80-7da9-11e9-98c0-ff8c10ee8dfc.png">

We enabled the Nomad servers to be clients as well for the exercise.

Assuming the following job:

```hcl
job "web" {
  meta {
    date = "Thu May 23 21:58:32 PDT 2019"
  }
  datacenters = ["prod-usw2-prod1"]
  type = "service"

  constraint {
    attribute = "${meta.role}"
    value     = "nomad-compute"
  }

  group "web_group" {
    count = 10

    task "httpbin_task" {
      driver = "docker"

      config {
        image = "simonkowallik/httpbin:latest"
        port_map {
          web = 80
        }
      }

      resources {
        cpu    = 100 # 500 MHz
        memory = 50 # 256MB
        network {
          port "web" {}
        }
      }

      service {
        name = "web"

        port = "web"
        check {
          name     = "http /get check for ${NOMAD_JOB_NAME}"
          type     = "http"
          path     = "/get"
          interval = "5s"
          timeout  = "2s"
        }
      }
    }
  }
}

```

When trying to run this simple job, we unfortunately end up seeing the container deployed on the Nomad servers.

I'm not sure if we're missing something.

Thanks in advance!

**Comment by scalp42** [comment]
So it doesn't work without stopping the job where we would like to see the tasks migrated to satisfy the constraints. Is there a way to force the re-evaluation to pick the constraints?

**Comment by preetapan** [comment]
@scalp42 if your nomad clients run on the same host as nomad servers and have the label `nomad-compute` it will place them there. In general we don't recommend running nomad servers and clients on the same node because servers consume additional disk/CPU resources

**Comment by scalp42** [comment]
So in our scenario, the nomad clients running on nomad servers, do not have the meta attributr `nomad-compute`.

**Comment by preetapan** [comment]
@scalp42 currently to force a reevaluation you need to make a trivial change to the job spec (e.g increase the memory limit in the resource stanza by 1mb). 

Can you share your client config stanza. Nomad should respect the constraint set at schedule time.

**Comment by scalp42** [comment]
```
root@nomad-compute-i-0d39590bdec4cf169 [prod-usw2-prod1] ~ # cat /etc/nomad/client.json{
  "client": {
    "enabled": true,
    "max_kill_timeout": "30s",
    "meta": {
      "chef_role": "nomad-compute",
      "role": "nomad-compute"
    },
    "no_host_uuid": false,
    "node_class": "compute",
    "server_join": {
      "retry_join": [
        "provider=aws tag_key=Name tag_value=prod1-nomad-server region=us-west-2 addr_type=private_v4"
      ]
    }
  }
}
```

**Comment by scalp42** [comment]
Unfortunately, I'm very sorry but we can't reproduce it. I'm going to close the issue @preetapan, thank you so much for jumping on this!
