### ISSUE TITLE
Adding count parameter to task definition

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/nomad#577]
Count parameter within groups helps us to run multiple instances of the task on multiple node. It would be nice to run the multiple instances of the same task within a machine, by adding a count parameter to the task as well. It is mainly for development purposes where each developer can setup a cluster on their machine, without requiring a real cluster.

To my understanding, in order to run multiple instances of the same process on the same machine, we need to write multiple task definitions within a same group - like copy & paste. Is there any other way for that?

**Comment by diptanu** [comment]
@kaskavalci So the count parameter is on the task group. A task group when placed on a node is called an Allocation. Nomad can run multiple Allocations on a single node, and each allocation has a unique id. So you can run multiple instances of the same task on a machine as long as resources are available.

Does that makes sense?

**Comment by kaskavalci** [comment]
Oh, didn't know that. I thought allocations should be on separate nodes at all times. Thanks for the reply.
