### ISSUE TITLE
FreeBSD build fails due to docker/pkg/mount undefined

### ISSUE THREAD

**Issue by sarcasticadmin** [hashicorp/nomad#5771]
### Nomad version
Building against HEAD on `master` sha: `781c94b0b7f114aab12e1d7ae5d598323f907fbb`

### Operating system and Environment details

Using the vagrant freebsd box defined in this repo:

```
$ uname -a
FreeBSD freebsd 11.2-STABLE FreeBSD 11.2-STABLE #0 r345116: Thu Mar 14 02:26:11 UTC 2019     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

### Issue

Building nomad for freebsd fails do to an undefined error in the `docker/pkg/mount` module that nomad currently depends on. This error was fixed upstream in docker: https://github.com/moby/moby/pull/39203

I'd like to discuss how to approach resolving this issue since updating the docker module(s) deps could have a large effect on nomad and doesnt seem like a good solution for such a small fix.

Adding for reference the last time the docker modules for nomad were updated: https://github.com/hashicorp/nomad/pull/5046

### Reproduction steps

Spin up the `freebsd` vagrant box:

```
$ vagrant up freebsd
```

SSH into it:

```
$ vagrant ssh freebsd
```

Attempt to build the `nomad` binary:

```
$ gmake pkg/freebsd_amd64/nomad
==> Building pkg/freebsd_amd64/nomad...
# github.com/hashicorp/nomad/vendor/github.com/docker/docker/pkg/mount
vendor/github.com/docker/docker/pkg/mount/mountinfo_freebsd.go:40:24: undefined: p
gmake: *** [GNUmakefile:64: pkg/freebsd_amd64/nomad] Error 2
```

Build fails due to a bad reference from docker

### Workaround

Apply the following patch for `vendor/github/docker` from https://github.com/moby/moby/pull/39203 and the build succeeds:

Create `0001-Correct-copy-paste-mistage-in-pkg-mount-mountinfo_fr.patch`:

```
From 6205fcf60d2db865c4f0211577a84f0fd7a9f0b9 Mon Sep 17 00:00:00 2001
From: Stig Larsson <stig@larsson.dev>
Date: Sat, 11 May 2019 14:04:02 +0000
Subject: [PATCH] Correct copy paste mistage in pkg/mount/mountinfo_freebsd.go
 that caused compile errors.

Signed-off-by: Stig Larsson <stig@larsson.dev>
---
 pkg/mount/mountinfo_freebsd.go | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/pkg/mount/mountinfo_freebsd.go b/pkg/mount/mountinfo_freebsd.go
index 36c89dc1..7d218b7c 100644
--- a/pkg/mount/mountinfo_freebsd.go
+++ b/pkg/mount/mountinfo_freebsd.go
@@ -13,8 +13,8 @@ import (
 	"unsafe"
 )
 
-// Parse /proc/self/mountinfo because comparing Dev and ino does not work from
-// bind mounts.
+
+//parseMountTable returns information about mounted filesystems
 func parseMountTable(filter FilterFunc) ([]*Info, error) {
 	var rawEntries *C.struct_statfs
 
@@ -37,7 +37,7 @@ func parseMountTable(filter FilterFunc) ([]*Info, error) {
 
 		if filter != nil {
 			// filter out entries we're not interested in
-			skip, stop = filter(p)
+			skip, stop = filter(&mountinfo)
 			if skip {
 				continue
 			}
-- 
2.20.1
```

Place `0001-Correct-copy-paste-mistage-in-pkg-mount-mountinfo_fr.patch` in the root of the nomad repo and `patch`:

```
$ patch -d vendor/github.com/docker/docker < 0001-Correct-copy-paste-mistage-in-pkg-mount-mountinfo_fr.patch
```

Get back on the vagrant freebsd box (the nomad repo is already mounted into vagrant box) and rebuild:

```
$ vagrant ssh freebsd
$ gmake pkg/freebsd_amd64/nomad
```

Test the binary:

```
$ pkg/freebsd_amd64/nomad -v
Nomad v0.9.2-dev (781c94b0b7f114aab12e1d7ae5d598323f907fbb+CHANGES)
```

**Comment by csawyerYumaed** [comment]
Thanks for including the full patch, it builds fine now.  please merge.

**Comment by sarcasticadmin** [comment]
@csawyerYumaed the patch included here was already merged into the upstream Docker (Moby) project, but the current docker dependencies in `vendor/vendor.json` for Nomad are referencing commit https://github.com/moby/moby/commit/baab736a364959f10a5ef86f0cd8a8e44bdcc576 from Nov 2018.

My patch cant be merged "as-is" since anything in `vendor/` is actually referencing other repo trees.

Its probably best to wait until the Docker dependencies in Nomad get bumped to something at or past 6205fcf60d2db865c4f0211577a84f0fd7a9f0b9 (the commit for the above patch). In the meantime there might have to be workaround(s) during the build process. The ports tree already has this: https://svnweb.freebsd.org/ports/head/sysutils/nomad/files/patch-vendor_github.com_docker_docker_pkg_mount_mountinfo__freebsd.go?view=log&pathrev=505353 but anyone looking to build directly from source needs to apply this patch before hand.

I just wanted to raise the visibility for anyone else who runs into a similar scenario.

**Comment by tgross** [comment]
Doing some issue cleanup; looks like this has been closed for a while now and smoke-tested as part of #6500.
