### ISSUE TITLE
nomad regiser only one instance in consul

### ISSUE THREAD

**Issue by sielaq** [hashicorp/nomad#578]
Hi,

I have just compiled newest nomad(master) and consul(master).
I took example generated from nomad, and set count=2.
Nomad creates two instances, two docker containers are running (so far so good),
but then register in consul only the latest one.

**Comment by c4milo** [comment]
@sielaq would you please share your job definition?

**Comment by diptanu** [comment]
@c4milo @sielaq This is indeed a bug on master, introduced because Service IDs are generated on the server side now. Nomad 0.2.1 should still have the right behavior.

A fix will be landing in the master soon.

**Comment by diptanu** [comment]
This was fixed by #583 and released with 0.2.3-rc1
