### ISSUE TITLE
Sample Nomad Dashboard 404 ?

### ISSUE THREAD

**Issue by lemon-li** [hashicorp/nomad#5799]
Hello, I can't visit [dashboard URL](https://github.com/hashicorp/nomad/tree/master/integrations/grafana/sample_dashboard.json).
Is there a perfect nomad dashboard recommendation?

**Comment by jrasell** [comment]
The correct URL is - https://github.com/hashicorp/nomad/blob/master/integrations/grafana_dashboards/sample_grafana_dashboard.json
