### ISSUE TITLE
Unique IDs for failed / restarted tasks

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/nomad#581]
Jobs allocation IDs are unique per allocation but I couldn't see a way to get unique IDs for the tasks that are running. We need to know if a task failed / restarted and have unique IDs for each one. 

I saw that PR https://github.com/hashicorp/nomad/pull/422 adding count number to the task name for uniqueness but I see it was deleted. How can we accomplish this in the current version?

**Comment by dadgar** [comment]
If you look at the allocation endpoint you will see a TaskStates map: https://www.nomadproject.io/docs/http/alloc.html

This can also be seen by running `nomad alloc-status [alloc]`. Inside this there is the most recent states for a task. This should be the information you need.

**Comment by kaskavalci** [comment]
I guess Time field in the TaskStates map is the unique identifier, right? Unfortunately I can't try right now and will do tomorrow.

**Comment by kaskavalci** [comment]
`TastStates` didn't show up any information but I see that `ClientDescription` is updated with a new entry at each restart of the task. I think that can be used to track instances of the task. Wouldn't it be better if there would be some sort of ID tag within the task and updated at each restart? That way, it is easier to track. 

I think currently the only way to track is to get `ClientDescription`, parse it and get the latest entry, compare the time with. Does that guarantee to provide uniqueness? Thanks.

**Comment by dadgar** [comment]
@kaskavalci: Can you provide some details on how you were trying to get `TaskStates`. It should always exist when there is an alloc. Through restarts we append to the task states so it should have the same effect and you get more information this way (timestamp and reason why the task restarted)

**Comment by kaskavalci** [comment]
When I query the client with v1/alloc/ID, I get this result:
`"ClientDescription":"{\"server\":{\"State\":\"running\",\"Events\":[{\"Type\":\"Started\",\"Time\":1450381661352967536,\"DriverError\":\"\",\"ExitCode\":0,\"Signal\":0,\"Message\":\"\",\"KillError\":\"\"}]}}",
"TaskStates":{
   "server":{
      "State":"pending",
      "Events":null
   }
},`

So all information seems to be in ClientDescription. I'm still using 0.2.1, will switch to 2.3-rc1 but couldn't deploy it to the cluster yet. I'll post an update when I do.

**Comment by dadgar** [comment]
@kaskavalci: Yeah please report back because that would be a bug. And I can't report it on 0.2.3-rc1. When I query I get something like this (I killed the container just so you could see some more info):

```
"ClientDescription": "{\"redis\":{\"State\":\"running\",\"Events\":[{\"Type\":\"Started\",\"Time\":1450387033419834088,\"DriverError\":\"\",\"ExitCode\":0,\"Signal\":0,\"Message\":\"\",\"KillError\":\"\"},{\"Type\":\"Terminated\",\"Time\":1450387062696785668,\"DriverError\":\"\",\"ExitCode\":137,\"Signal\":0,\"Message\":\"Docker container exited with non-zero exit code: 137\",\"KillError\":\"\"},{\"Type\":\"Started\",\"Time\":1450387093628179554,\"DriverError\":\"\",\"ExitCode\":0,\"Signal\":0,\"Message\":\"\",\"KillError\":\"\"}]}}",
  "TaskStates": {
    "redis": {
      "Events": [
        {
          "KillError": "",
          "Message": "",
          "Signal": 0,
          "ExitCode": 0,
          "DriverError": "",
          "Time": 1450387033419834000,
          "Type": "Started"
        },
        {
          "KillError": "",
          "Message": "Docker container exited with non-zero exit code: 137",
          "Signal": 0,
          "ExitCode": 137,
          "DriverError": "",
          "Time": 1450387062696785700,
          "Type": "Terminated"
        },
        {
          "KillError": "",
          "Message": "",
          "Signal": 0,
          "ExitCode": 0,
          "DriverError": "",
          "Time": 1450387093628179500,
          "Type": "Started"
        }
      ],
      "State": "running"
    }
  }
```

**Comment by kaskavalci** [comment]
Seems like it's a copy of Events under ClientDescription? Idea is to use Time field on the latest Event, right?

**Comment by dadgar** [comment]
Yeah for now. But there is no API guarantee of the ClientDescription so it can and probably will change. So you would just check if there are multiple start events and then you would know it restarted. Keep in mind this is the last 10 events and you can use time to keep track of them

**Comment by kaskavalci** [comment]
Just confirmed, TaskStates are filled with Events field with version 0.2.3. However, it seems like it's just a copy of ClientDescription, isn't it? Good to know that TaskStates will remain like this. Thanks.

**Comment by dadgar** [comment]
@kaskavalci: Yep TaskStates will stay like this as it is part of the API. ClientDescription is just a string and can change.
