### ISSUE TITLE
Nomad 0.9.2 memory / IO resource utilization

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/nomad#5813]
### Nomad version
Nomad v0.9.2

### Operating system and Environment details
Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Issue
Nomad v0.9.2 is causing filebeat to use a huge amount of memory and cause EBS volume burst credits to halt.

### Reproduction steps
Run the job below in a Nomad client running on v0.9.2 and get some traffic going on for some time. 

### Job file (if appropriate)

This is just one of the jobs we have running but pretty much any job with a filebeat sidecar was affected.

```hcl
job "fabio-private" {
  region = "us-east-1"
  datacenters = ["us-east-1"]
  type = "service"

  update {
    max_parallel = 1
    min_healthy_time = "30s"
    healthy_deadline = "2m"
    auto_revert = true
  }

  group "fabio-private" {
    count = "2"

    restart {
      attempts = 3
      interval = "2m"
      delay = "25s"
      mode = "delay"
    }

    task "filebeat" {
      driver = "exec"
      config {
        command = "local/filebeat-${VERSION}-linux-x86_64/filebeat"
        args = [
          "-c", "/local/filebeat.yml",
          "--path.data", "/alloc/data/filebeat",
          "--path.logs", "/alloc/logs/filebeat",
        ]
      }

      shutdown_delay = "30s"

      env {
        "VERSION" = "6.2.3"
      }

      artifact {
        source = "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${VERSION}-linux-x86_64.tar.gz"
        destination = "local"
      }

      template {
        data = <<TEMPLATE
filebeat:
  prospectors:
    -
      paths:
        - /alloc/logs/*.stderr.*
      input_type: log
      scan_frequency: 1s
      fields_under_root: true
      fields:
        app: {[ env "NOMAD_JOB_NAME" ]}
        stack: proxy
      multiline:
        pattern: '^[[:digit:]]{4}/[[:digit:]]{2}/[[:digit:]]{2}'
        negate: true
        match: after
    -
      paths:
        - /alloc/logs/*.stdout.*
      input_type: log
      scan_frequency: 1s
      fields_under_root: true
      fields:
        app: {[ env "NOMAD_JOB_NAME" ]}
        stack: proxy

output:
  logstash:
    hosts:
      - "logstash.service.consul:5044"

logging.to_syslog: false
logging.to_files: false


TEMPLATE

        left_delimiter = "{["
        right_delimiter = "]}"
        destination = "local/filebeat.yml"
      }
    }

    task "fabio-private" {
      driver = "exec"
      config {
        command = "/local/fabio"
        args = [
          "-cfg", "${NOMAD_SECRETS_DIR}/fabio.properties"
        ]
      }

      env {
        "VERSION" = "1.5.10"        
        "BUILD_VERSION" = "go1.11.1"        
      }

      artifact {
        source = "https://github.com/fabiolb/fabio/releases/download/v${VERSION}/fabio-${VERSION}-${BUILD_VERSION}-linux_amd64"
        destination = "local/fabio"
        mode = "file"
      }
      
      service {
        name = "fabio-private-ui"
        port = "ui"
        tags = ["i-urlprefix-fabio-private-mydomain/"]
        check {
          name = "Fabio"
          type = "tcp"
          interval = "15s"
          timeout = "5s"
          check_restart {
            limit = 3
            grace = "120s"
          }
        }
      }

      resources {
        cpu = 1000
        memory = 512
        network {
          port "http" {
            static = 9999
          }
          port "ui" {
            static = 9998
          }
        }
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
Since we had to rollback from `v.0.9.2` to `v0.8.7` we didn't get a chance to get any logs related to this issue, but we can confirm that rolling back fixed the high utilization of Memory and IO in the nodes running filebeat as a sidecar.

Note: We had a fairly bad surprise to discover that going back from v0.9.x to v0.8.x is not possible due to schema changes in the raftdb. We could not find anything in the CHANGELOGs regarding the schema changes.

### Nomad Server logs (if appropriate)
Same as above but we've checked Nomad logs either on client and server but nothing special was being thrown.

> Note: I know there was a lot of changes in the logging subsystems in Nomad but I could not find anything that could case this impact in a filebeat sidecar.

Sorry for the poor report but this is all the info we got.

**Comment by danlsgiga** [comment]
I'm wondering if `"--path.logs", "/alloc/logs/filebeat",` may explain it!

**Comment by notnoop** [comment]
Thanks @danlsgiga for reporting this issue.  This is somewhat odd, considering Nomad shouldn't change memory behavior of the workload.  I'll do some basic research this week and follow up with any questions.

As for downgrading nomad, I'm very sorry this happened to you.  We've clarified the language in https://github.com/hashicorp/nomad/pull/5815/files .

**Comment by danlsgiga** [comment]
Agree... I found it very odd as well since our previous experience with upgrades has been smooth. Sorry for not having much info about it.

I like how the overall state of Nomad can be somehow stored offline via the jobs file. We were able to rollback quickly after rebuilding the servers and clients and resubmitting the jobs. So, kudos for that!

**Comment by danlsgiga** [comment]
For anyone in the future possibly facing this issue. It seems starting with Nomad 0.9.x the `/alloc/logs` folder is allowing filebeat to create the harvesters control files (unix FIFO). When that happens and someone is using `/alloc/logs/*` in the prospector path, filebeat will try to read its own harvesters FIFO files and that cause a memory leak in the process. The fix / workaround for that is to set `exclude_files: ['\.fifo$']` to the prospect config.

For reference: https://github.com/elastic/beats/issues/12988

**Comment by danlsgiga** [comment]
Closing, since the root cause is in filebeat, not Nomad.
