### ISSUE TITLE
Registering stale services with Consul

### ISSUE THREAD

**Issue by ccakes** [hashicorp/nomad#5824]
### Nomad version
Nomad v0.9.2 (028326684b9da489e0371247a223ef3ae4755d87)
(seen on 0.9.0+)

### Operating system and Environment details
Amazon Linux 2

### Issue
Nomad is registering services with Consul for old allocations

I have a 3-node Nomad server cluster with 2 Nomad agents, all on separate machines. One of the Nomad agents regularly registers services for previous allocations, resulting in a list of registered services failing health checks.

I've tried using the Consul HTTP API to manually deregister the services but they keep coming back.

Nomad:
[Screenshot 2019-06-12 at 17 01 52](https://user-images.githubusercontent.com/103831/59363085-e4ec0680-8d34-11e9-943a-bd3add5a406b.png)

Consul:
[Screenshot 2019-06-12 at 17 02 06](https://user-images.githubusercontent.com/103831/59363092-e7e6f700-8d34-11e9-8722-dcbc4f864b91.png)

### Reproduction steps
Unsure, doesn't seem to happen consistently but has only started since I upgraded from 0.8.6 to 0.9.0 (and then on to 0.9.2)

---

Let me know what logs/jobspec etc would be helpful and I can share.

**Comment by endocrimes** [comment]
@ccakes Hey! - This _might_ be related to #5770, which I have a fix in flight for here: #5821 - If you could try running clients on 0.9.3 (coming imminently), that would be really useful.

It would also be helpful if you could share jobspecs for any jobs you've experienced this for. Thanks!

**Comment by mayuresh82** [comment]
We are hitting this in 0.9.1 as well. 
@endocrimes  so is the fix in 0.9.3 as you suggest ?

**Comment by robloxrob** [comment]
I believe that should be fixed on #5821 as suggested above.

**Comment by ccakes** [comment]
Thanks @endocrimes! Will update now and report back 👍

**Comment by ccakes** [comment]
Apologies for forgetting to reply, for anyone else that finds this can confirm upgrading resolved the issue
