### ISSUE TITLE
Task Driver config, meta, and env should support change_mode

### ISSUE THREAD

**Issue by Smithx10** [hashicorp/nomad#5826]
Some configuration update scenarios in a task driver do not require a restart / or reprovision.  For example, this attr in my scenario https://github.com/Smithx10/nomad-driver-triton/blob/master/plugin/plugin.go#L102 does not require a reprovision and could take place immediatley.   Currently if a user makes a change to that object nomad has no way to signal the running task to apply the appropriate action.   Also,  my task driver can take advantage of new meta and env keys without restart but currently applying change there also requires a restart.  

Perhaps HCL could be extended so that every hclspec.attr has a change mode field or something that nomad can look to when a change is applied to a task?  (Just brainstorming)

**Comment by mikenomitch** [comment]
Hey @Smithx10 this isn't an inherently bad idea, but I think this doesn't apply to the majority of cases, and we want to nudge people toward immuatable & replaceable workloads. This would also just open up a can of worms in terms of implementation, so realistically I don't think we're going to get to this any time soon. Will close this issue out to reflect that.
