### ISSUE TITLE
[question] nomad and vault integration failing

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#5867]
Hi all,

Sorry for raising an issue for this but I'm totally stuck and would really appreciate a pointer or two.

I have a working, production nomad cluster and I have a working (not yet production) vault cluster. I've followed the documentation on integrating them, I've created a role for nomad server, generated a role-based token, provided server and client config etc.

In the nomad server logs I can see token refreshes so I think it is safe to say the servers can find and talk to vault.

When I plan a job with a vault stanza I don't get an error about vault version numbers and no agents meeting constraints (like I did before I corrected a client config error) so I'd like to believe the clients can talk to the vault servers.

However, when I try and run the job I successfully planned I get:
`Error submitting job: Unexpected response code: 500 (rpc error: Vault not enabled and Vault policies requested)`

Can someone possibly give me some hints as to what I can check or test next to resolve this?

Thanks!

**Comment by angrycub** [comment]
Depending on version, there is some information in the output of `nomad agent-info` about the vault client for the server. 

```
vault
  token_expire_time = 2019-06-22T22:43:28Z
  token_ttl = 33h45m18s
  tracked_for_revoked = 0
```

 You should also check for vault fingerprints in the output of `nomad node status -verbose -self`  For example:

```
vault.accessible              = true
vault.cluster_id              = 68f9ae66-47a5-89be-ea7f-3cfbb39fb1c4
vault.cluster_name            = vault_dc1
vault.version                 = 1.1.0
```

Typically though, that error only appears in cases where the configuration for any node in the cluster is missing the `enabled=true` in the vault stanza.

**Comment by far-blue** [comment]
@angrycub Thanks for responding! I can see vault info in the output from `nomad node status -verbose -self`. This would suggest the clients are able to talk to vault. As I said, the nomad server logs are showing entries for renewing the token so I must assume they are happy talking to vault as well.

I've traced the rpc error to the lead nomad server by turning on debug log output on a client but can't think how to debug further without restarting the server instances with a debug log level :(

**Comment by angrycub** [comment]
The cluster leader is the node that derives the tokens requested for the jobs, that would be the first place to look for Vault errors.  As you said, you would certainly get more feedback by changing the log level to debug.  

Performing a rolling restart of the server nodes should be essentially benign as long as the cluster is monitored to ensure proper leadership transitions.

**Comment by far-blue** [comment]
Yeah, I think I'm going to have to resort to enabling debug logging on the servers. It's a shame a reload doesn't update log levels :(

Rolling restarts aren't scary, just time consuming. And as I know of no way to force a particular server node to become leader I have to change log level on all nodes until I get a leader with debug logging. And then I need another rolling update to turn debug logging back off again.

I guess I know what I'm doing this evening ;)

**Comment by far-blue** [comment]
Hah, the irony. Despite vault details apparently reloading on a server reload (and the token renewing working), it looks like I did need to restart the servers. Restarting them to set debug level logging fixed the issue!

Thanks for time and suggestions @angrycub :)
