### ISSUE TITLE
Why is there no task real-time traffic in nomad's monitoring data?

### ISSUE THREAD

**Issue by WormOn** [hashicorp/nomad#5877]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`

### Issue
Why is there no task real-time traffic in nomad's monitoring data?
### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by preetapan** [comment]
@WormOn We expose metrics on clients and servers, listed in the telemetry guide here - https://www.nomadproject.io/docs/telemetry/overview.html 

Task real time traffic is opaque to Nomad and something that should be monitored by something else in your stack (the application itself, or your load balancer).
