### ISSUE TITLE
Alloc index is repeated

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#5879]
Hi, I think this is related to #4264 

We're experiencing that also.
- Servers are v0.9.3 and nodes v0.8.4

I think this has something to do with the canary count.

We have: 
- A group with count of 7 and we see the following alloc indexes (canary = 2): 0, 1, 0, 1, 2, 3, 4
- Another group with a count of 4 that has the following indexes (canary = 1): 0, 0, 1, 2

Maybe the allocations scheduled after the job is promoted (once the canaries are verified) start again in 0?

Thanks!

**Comment by preetapan** [comment]
hi @jorgemarey the indexes are not guaranteed to be unique, especially [when there are canaries](https://github.com/hashicorp/nomad/issues/4264#issuecomment-387467224). The scheduler makes a best attempt to use indexes from 0 to n-1, but any failed deployment may end up reusing an older index. We would suggest not building any logic that relies around these index values being unique.

Could you post a job spec and detailed reproduction steps - would still be interested in addressing this if its possible to do so.

**Comment by jorgemarey** [comment]
Hi @preetapan. Understood, we will change our logic so as not to assume that the index values are unique. In any case, I managed to reproduce it. The problem appears when incrementing the count at the same time that a change is made (which implies a new deployment -> new canary)

The hcl is the following:

```
job "test" {
  region      = "global"
  datacenters = ["dc1"]

  group "test" {
    count = 4

    update {
        canary = 1
    }

    task "test" {
      driver = "exec"

      config {
        command = "tail"
        args    = ["-f", "/dev/null"]
      }

      resources {
        cpu    = 100
        memory = 100

        network {
          mbits = 10
        }
      }
    }
  }
}
```

```
$ nomad agent -dev
$ nomad run test.hcl
```

Now we change the count to 5 and the memory to 102 to force a new deployment and run it. At this point a new allocation with index 0 will be placed. 

Later, when we promote the deployment and all allocations are reescheduled the index 0 is duplicated.

I hope this helps.

Thanks!

**Comment by jorgemarey** [comment]
Hi. I managed to reproduce this behaviour on both 0.9.5 and 0.10.0-beta1.

**Comment by tgross** [comment]
This was brought up again in #6829. For a work-around to this, if you need a unique number for interpolating a value in your application, you can get this by combining the job version and the alloc index (which together should be unique).

Having the index be unique within a given deployment is useful on its own, so I'm inclined to improve [the documentation around what these values mean](https://www.nomadproject.io/docs/runtime/environment.html) rather than change the behavior.
