### ISSUE TITLE
Nomad cannot read environmental variables (AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=myprofile) for amazon-ecr-credential-helper to work with an assumed role

### ISSUE THREAD

**Issue by ronaldegmar** [hashicorp/nomad#5884]
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

### Issue
**I'm able to do the docker pull as described here (https://github.com/awslabs/amazon-ecr-credential-helper/issues/34):**
  
`AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=XXXXX docker pull`

However, I cannot make nomad to work with it. 

This is the error:

failed to initialize task "launchExperiment" for alloc "fa65f458-c338-5d3b-a77c-e27078221b8a": Failed to find docker auth for repo "XXXXXXX.dkr.ecr.YYYYY.amazonaws.com/ZZZZ": docker-credential-ecr-login with input "https://XXXXXXXX.dkr.ecr.YYYYY.amazonaws.com/ZZZZZZ" failed with stderr: credentials not found in native keychain

### Reproduction steps
Below are the configuration files. Nomad cannot retrieve the credentials for another's aws account ECR. EC2 instance has the appropriate IAM Instance Profile. All works good when doing docker pull in the command line.

### Nomad client configuration
/etc/nomad.d/nomad-client.hcl
      
      log_level = "DEBUG"

      # Setup data dir
      data_dir = "/var/nomad/data"

      # Give the agent a unique name. Defaults to hostname
      name = "experiment-0",

      # Enable the client
      client {
        enabled = true

        # servers = ["XXXXXXXXX:4647"]
        options = {
          "docker.auth.config" = "/home/ubuntu/.docker/config.json"
          "driver.raw_exec.enable" = "1"
        }
        servers = ["nomad-server.node.consul"]
      }

      vault {
        enabled     = true
        address     = "https://XXXXXXXXXX:8200"
      }

      # This terraform module depends on module-id "XXXXXXXXXX"

      # Modify our port to avoid a collision with server1
      #ports {
      #  http = 5656
      #}

### Nomad Systemd service
I tried to set up the env vars here without luck
/etc/systemd/system/nomad.service

```
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/

[Service]
Environment=AWS_SDK_LOAD_CONFIG=true
Environment=AWS_PROFILE=XXXXXXXXXXX
KillMode=process
KillSignal=SIGINT
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d/nomad-client.hcl
ExecReload=/bin/kill -HUP $MAINPID
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```
### Docker Systemd service
I tried to set up the env variables here too. No luck either
/etc/systemd/system/docker.service.d/ecr-credential-helper.conf

```
[Service]
Environment="AWS_SDK_LOAD_CONFIG=true" "AWS_PROFILE=XXXXXX"
```

### Docker config
docker/config.json
```
     {
	    "credsStore": "ecr-login"
      }
```

### aws config
.aws/config
```
[profile ZZZZZZZ]
role_arn = arn:aws:iam::XXXXXXXXX:role/YYYYYYY
credential_source = Ec2InstanceMetadata
```

### Profile Configuration
/etc/profile.d/abashscript.sh
This didn't work either. It only works in the command line but not with nomad.
```
export AWS_SDK_LOAD_CONFIG=true
export AWS_PROFILE=ZZZZZZZ
```

### Nomad job
```
job "experiment" {

  datacenters = ["dc1"]
  region  = "global"

  group "experiment" {

    count = 1

    restart {
      attempts = 3
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    update {
      max_parallel = 1
      canary           = 1
      min_healthy_time = "30s"
      healthy_deadline = "5m"
      health_check     = "checks"
    }

    vault {
      policies = ["XXXXXXX"]
      change_mode   = "signal"
      change_signal = "SIGHUP"
      env = "true"
    }

    task "launchExperiment" {

      constraint {
        attribute = "${node.unique.name}"
        operator  = "regexp"
        value = "experiment-[[:digit:]]"
      }

      env {
        version = "YYY"
        AWS_SDK_LOAD_CONFIG = "true"
        AWS_PROFILE = "XXXXXXX"
      }

      driver = "docker"

      config {
        image = "XXXXXXXXX.dkr.ecr.YYYYY.amazonaws.com/ZZZZZZ:experiment-${version}"
        hostname = "XXXXXXXXXXXXXXX"
        args = [
          "AWS_SDK_LOAD_CONFIG=${AWS_SDK_LOAD_CONFIG}",
          "AWS_PROFILE=${AWS_PROFILE}",
        ]
      }

      service {
        name = "XXXXXXXXX"
        port = "web"
        check {
          name = "YYYYYYY"
          type = "http"
          protocol = "http"
          path     = "/"
//          path     = "/landing"
          interval = "5s"
          timeout = "2s"
        }
      }

      resources {
        cpu    = 1000 # MHz
        memory = 1024 # MB

        network {
          mbits = 50

          port "web" {
            static = 80
          }
        }
      }


    }

  }


}
```

**Comment by CarlosDomingues** [comment]
For anyone coming from Google, I was able to get Nomad + ECR + Assume Role working with Nomad 0.9.3. Here is the relevant configuration:

* `/etc/nomad.d/` is my `nomad` user `$HOME`. Change accordingly.
* Other variables are self-explanatory, I guess.
* `docker-credential-ecr-login` must be installed on `/usr/local/bin/` 
* `/etc/systemd/system/nomad.service`:

```hcl
[... stuff ..]
[Service]
User=nomad
Group=nomad
Environment=AWS_SDK_LOAD_CONFIG=true
Environment=AWS_PROFILE=${AWS_PROFILE_NAME}
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d/nomad.hcl -config /etc/nomad.d/client.hcl
[... more stuff ..]
```

* `client.hcl`:

```hcl
client {
  enabled = true
  options = {
    "docker.auth.config" = "/etc/nomad.d/.docker/config.json"
    "docker.auth.helper" = "ecr-login"
  }
}
```
* `/etc/nomad.d/.aws/config`:
```hcl
[profile ${AWS_PROFILE_NAME}]
region=${AWS_REGION}
role_arn=${AWS_ROLE_ARN}
credential_source=Ec2InstanceMetadata
```
* `/etc/nomad.d/.docker/config.json`:

```hcl
{
  "credHelpers": {
    "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com": "ecr-login"
  }
}
```
* IAM Policy (configured on AWS) :

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "ec2:DescribeVpcs",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeInstanceStatus",
                "ec2:DescribeInstances",
                "ec2:DescribeTags",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken",
                "ecr:ListTagsForResource",
                "ecr:ListImages",
                "ecr:BatchGetImage",
                "ecr:DescribeImages",
                "ecr:DescribeRepositories",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetRepositoryPolicy",
                "ecr:GetLifecyclePolicy",
                "sts:AssumeRole"
            ],
            "Resource": "*"
        }
    ]
}
```

A quick sanity check:

- [ ] Ensure your `nomad` user can run `docker-credential-ecr-login`: `sudo -H -u nomad bash -c 'docker-credential-ecr-login'`
- [ ] Run `sudo -H -u nomad bash -c 'aws ec2 describe-tags --profile $(cat ~/.aws/config | grep profile | cut -d " " -f3 | sed "s#]##")'` to ensure your instance profile is set correctly both on AWS side and for the `nomad`user.
- [ ] Run:
```hcl
sudo -H -u nomad bash -c 'eval $(aws ecr get-login --profile $(cat ~/.aws/config | grep profile | cut -d " " -f3 | sed "s#]##") --no-include-email | sed "s|https://||")'
sudo -H -u nomad bash -c 'docker pull <your-image-on-ecr>'
```
To ensure your instance profile can access ECR.

- [ ] Make sure you're using your instance profile name, not role id, for the `${AWS_PROFILE_NAME}` bits.

Good luck!

**Comment by fideloper** [comment]
I know this is a little older but I'm not clear: 

Do I **need** to use a AWS `profile` to get an **assumed role** to work with Nomad for pulling ECR images? The credentials helper seems to work fine when calling the command (or even `docker pull ...`) directly, but Nomad keeps giving the `no basic auth credentials` error no matter what combination of things I try.

To be clear, this is a role assigned to the instance profile on the server. There's only one role, and I'm not doing any extra STS work to assume other roles.

> Sidenote: It looks like a not-yet-released version of ecr credentials helper has `AWS_SDK_LOAD_CONFIG=true` as an updated default
