### ISSUE TITLE
[question]  cannot interpolate environment variables in `env` stanza.

### ISSUE THREAD

**Issue by jahentao** [hashicorp/nomad#5886]
### Nomad version
Output from `nomad version`

`Nomad v0.9.2 (028326684b9da489e0371247a223ef3ae4755d87)`

### Operating system and Environment details

CentOS7.6

### Issue

I found it cannot interpolate [environment variables](https://www.nomadproject.io/docs/runtime/interpolation.html#environment-variables-) in `env` stanza. 

For example, I have defined a `NOMAD_IP_db` in a task, and another task need it(the running container's IP), and retrive it in the `env` stanza.

### Reproduction steps

define two task in a job, one expose a port, and another use the environment variable in `env` stanza.

### Job file (if appropriate)

the main part extracted as below:
```hcl
    # task: db 
    task "postgresql" {
      env {
        POSTGRES_PASSWORD="root123"
      }
      constraint {
        attribute = "${attr.unique.hostname}"
        value     = "node1"
      }
      driver = "docker"
      config {
        image = "xxxx-db:v1.0"
        port_map {
          db = 5432 
        }
      }
      resources {
        network {
          port "db" {
            static = 5432 
          }
        }
      }
      service {
        name = "harbor-postgresql"
        tags = ["urlprefix-/postgresql"]
      }
    }

    # task: core 
    task "core" {
      env {
        DATABASE_TYPE="postgresql"
        POSTGRESQL_HOST="${env["NOMAD_IP_db_port"]}"
        POSTGRESQL_PORT=5432
        POSTGRESQL_USERNAME="postgres"
        POSTGRESQL_PASSWORD="root123"
      }
      constraint {
        attribute = "${attr.unique.hostname}"
        value     = "node1"
      } 
      driver = "docker"
      config {
        image = "xxxxx-core:v1.0"
        port_map {
          core= 8080 
        }
      }
      resources {
        network {
          port "core" {}
        }
      }
      service {
        name = "harbor-core"
        tags = ["urlprefix-/core"]
      }
```

### Nomad logs (if appropriate)
whatever method, i tried to retrive  `NOMAD_IP_db` in `env` stanza, I could not get it.

- retrive it like `POSTGRESQL_HOST="${env["NOMAD_IP_db"]}"`
the log will be:
```
core[4641]: 2019-06-26T08:49:27Z      [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://${env["NOMAD_IP_db"]}:5432, retry after 2 seconds :dial tcp: address ${env["NOMAD_IP_db    "]}:5432: unexpected '[' in address
```

- retrive it like `POSTGRESQL_HOST="${NOMAD_IP_db}"`
the log will be:
```
core[4641]: 2019-06-26T08:54:12Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://${NOMAD_IP_db}:5432, retry after 2 seconds :dial tcp: lookup ${NOMAD_IP_db}: no such host
```

**Comment by jahentao** [comment]
And it cannot interpolate environment variables in `network` stanza, like:
```hcl
meta {
    LB_PORT=8080
}

...
port "lb" {
    static = "${NOMAD_META_LB_PORT}"
}
```

**Comment by kneufeld** [comment]
You're mixing templates and `env` a bit.

You don't need `env` when _not_ in a consul-template. So do this

```
POSTGRESQL_HOST="${NOMAD_IP_db}"
```

The other thing you can do if you need something more complex is to use a template stanza with `env = true`.

```
task "core" {
  template {
    data = <<EOF
POSTGRESQL_HOST="{{ env "NOMAD_IP_db" }}"
EOF

    destination = "local/nomad.env"
    env = true
  }
}
```

**Comment by tgross** [comment]
Hi @jahentao! Sorry it took a while to get back to you here. It looks like @kneufeld has the question answered, so I'm going to close this. Thanks @kneufeld !
