### ISSUE TITLE
Access control on job registration

### ISSUE THREAD

**Issue by calvn** [hashicorp/nomad#589]
Is there a best practice/recommendation for implementing access control on running jobs? Consul, for example, has ACLs to control who can register KVs and services. We can use Consul's ACLs to restrict service registration from Nomad jobs, but those jobs would still run on the Nomad clients (just not easily accessible without service discovery).

If ACLs or something similar is outside the scope of Nomad, what is the recommended way to control who can run jobs and how many jobs or resources as user can request? Thanks in advance!

**Comment by dadgar** [comment]
This is something that we will be tackling in Nomad 0.4. For now there is no ACL policies or enforcement in Nomad.

**Comment by cleung2010** [comment]
Cool to know that this is on the roadmap, thanks for the quick response!

**Comment by doherty** [comment]
I take it this didn't make it into 0.4.0, which was released recently. Is this still on the near-term roadmap?

**Comment by diptanu** [comment]
@doherty Yes, this is very much on the roadmap.

**Comment by kyhavlov** [comment]
Any chance this will go into an 0.4.x release soon? I'm looking into using nomad for deploying apps and this would be a really useful feature, even in very basic form.

**Comment by dadgar** [comment]
@kyhavlov It will not be in a 0.4.x release

**Comment by kyhavlov** [comment]
Just to lay out the things I'd be looking for in an ACL system for Nomad:

- Tokens used for authentication, similar to Consul with management and client type tokens for administrating ACL policies (and the ability to set policies on the default/anonymous token)
- Policies on tokens to limit tasks deployed by the token on cpu/memory/disk/network usage, on a per-region/datacenter basis.

And that's pretty much it. Non-management tokens should probably be prohibited from affecting tasks run by other tokens, and management tokens get access to all tasks.

Does that align with what you guys were already planning for an ACL system in the future? I'd be interested in helping make it happen if that's the case.

**Comment by vrenjith** [comment]
Is this feature planned in any release?

**Comment by dadgar** [comment]
It will most likely be in Nomad 0.7.

Thanks,
Alex Dadgar

**Comment by jhmartin** [comment]
Without ACL's it looks like a single subverted nomad 'agent' node effectively subverts the entire cluster, that makes for a very difficult security story.

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/casbin/casbin). It is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

So please consider using casbin when nomad implements access control security. Also let me know if there's any question, and I can always provide help in the code :)

**Comment by mkuzmin** [comment]
related issue: #227

**Comment by dadgar** [comment]
Hey all! This has landed in Nomad 0.7! https://www.nomadproject.io/guides/acl.html
