### ISSUE TITLE
BUG in the Nomad signup URL on the HashiConfEU blog entry

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#5897]
This is not really a Nomad bug, but I think it warrants a bug report here as only the Nomad signup page is affected at https://www.hashicorp.com/blog/what-to-expect-at-hashiconf-eu-training-day
The links under `Signup for Nomad 101` is wrong, it contains an extra dot.

Regards,
Shantanu Gadgil

Tagging some usual suspects! :smiley: 

@preetapan @schmichael @topfunky @armon @mitchellh @dadgar

**Comment by endocrimes** [comment]
Hey @shantanugadgil,

Thanks for spotting this! - I've forwarded this along to our events team so they can update the blog post. I hope you have a good time at HashiConf :tada:

**Comment by shantanugadgil** [comment]
> Hey @shantanugadgil,
> 
> Thanks for spotting this! - I've forwarded this along to our events team so they can update the blog post. I hope you have a good time at HashiConf

Ahhh! I wish I was visiting, but no, I am not! :slightly_smiling_face: 

_BTW, the link is still not fixed!_
