### ISSUE TITLE
[v0.9.3] - Jobs are not preempting lower priority jobs

### ISSUE THREAD

**Issue by zonnie** [hashicorp/nomad#5898]
### Nomad version
```
Nomad v0.9.3
```

### Operating system and Environment details
Linux Ubuntu 4.4.0-146-generic #172~14.04.1-Ubuntu SMP Fri Apr 5 16:51:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Issue
I have 2 services, one which should preempt the other.
`worker-a` has a priority of `1` -> memory limit: `200MB`
`worker-b` has a priority of `100` -> memory limit: `250MB`

`worker-a` allocations (has 40):
```
root@ubuntu:~# nomad job status worker-a
ID            = worker-a
Name          = worker-a
Submit Date   = 2019-06-27T10:46:21Z
Type          = service
Priority      = 1
Datacenters   = dc-1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group             Queued  Starting  Running  Failed  Complete  Lost
worker-a  0       0        40       0       40        1

Allocations
ID        Node ID   Task Group             Version  Desired  Status    Created     Modified
c8a8a435  e15363c7  worker-a  				2        run      running   28m30s ago  28m16s ago
...
95f6676c  abd38cc6  worker-a    		    2        run      running   28m30s ago  27m36s ago
```

`worker-b` allocations:
```
root@ubuntu:~# gc-nomad job status worker-b
ID            = worker-b
Name          = worker-b
Submit Date   = 2019-06-27T10:52:25Z
Type          = service
Priority      = 100
Datacenters   = dc-1
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group           Queued  Starting  Running  Failed  Complete  Lost
worker-b             1       0         0        0       8         0

Placement Failure
Task Group "worker-b":
  * Constraint "${meta.manager} == true" filtered 2 nodes
  * Resources exhausted on 1 nodes
  * Dimension "memory" exhausted on 1 nodes

Allocations
ID        Node ID   Task Group           Version  Desired  Status    Created    Modified
4832743c  abd38cc6  worker-b             15       stop     complete  2h59m ago  33m28s ago
```

Looking in `curl -s http://localhost:4646/v1/job/worker-a/allocations?pretty  | grep Preempt` for `PreemptedAllocations` - all are `null` - no preemption happened :(

The machines stats according to Nomad:
```
    "Memory": {
        "Available": 8362135552,
        "Free": 807493632,
        "Total": 16837578752,
        "Used": 8475443200
    },
```
Used `curl -s "http://localhost:4646/v1/client/stats?node_id=abd38cc6-dc4b-6483-714f-84e05708c66c`.

- My Nomad client has a 500MB reservation

### Reproduction steps
- Create 2 jobs, A with priority 1, B with priority 100
- Fill the node with job A instances
- Try running job B -> should preempt instances of job A

### Job file (if appropriate)
None

### Nomad Client logs (if appropriate)
Nothing seems related

### Nomad Server logs (if appropriate)
Nothing seems related

**Comment by angrycub** [comment]
Only System jobs are preempt-able in Nomad open source.  Batch and Service jobs preemption is a Nomad Enterprise feature.  This is highlighted in the CHANGELOG and the [operator-Scheduler Config API documentation](https://www.nomadproject.io/api/operator.html#schedulerconfig)
