### ISSUE TITLE
Allow passing Consul ACL token in job specification

### ISSUE THREAD

**Issue by calvn** [hashicorp/nomad#590]
Consul configuration can be provided in the client configuration, but it would be great if these can also be passed in at the job level.

These settings are already are under "Client Options Map" in https://nomadproject.io/docs/agent/config.html. The [docs](https://nomadproject.io/docs/jobspec/servicediscovery.html) for service discovery, more specifically the consul settings, are listed under `jobspec/` which made me think that those parameters could be set on the job declaration file.

One reason for this request is to extend control of service registration to the owners of the services instead of the client that is running the job, such that they are allowed to register services with Consul ACL tokens that they own which contains specific policies on where they can register services (by that I mean with prefixes).

**Comment by diptanu** [comment]
@cleung2010 Yeah we are currently figuring out the list of options that we want end users of Nomad to be able to configure on a per job basis vs the list of options that Nomad operators would be able to configure.

cc/ @ryanuber

**Comment by ryanuber** [comment]
I think this makes sense for the ACL token to be configurable at the job level. As for the other connection-level settings, I think it would be best if we left those as a global configuration only, since it would open up the possibility for some very confusing interactions with Consul. I'm going to modify the ticket name to reflect this. Thanks @cleung2010!

**Comment by c4milo** [comment]
I'm looking forward to this. Being able to restrict jobs to specific paths in Consul would be very useful in multitenant environments.

**Comment by c4milo** [comment]
Any update on this?

**Comment by chrisvanmeer** [comment]
I would also like to see this feature.  
Any news on the timeline?

**Comment by mikenomitch** [comment]
We've been discussing our Consul integration a bit internally, and we think that shifting to identity-based auth with Consul is the correct direction in the long term.

This would allow you to interact with Consul without manually managing ACL tokens per Job/Service.

This is still a ways off unfortunately, but given that we'll invest our time in that, I don't think we'll get to any major ACL-based upgrades to the intergation, so I'm going to close this out. I'll provide more info on the upcoming solution once we flesh it out more!
