### ISSUE TITLE
Nomad server failover vs. task restart - Consul DNS

### ISSUE THREAD

**Issue by jozef-slezak** [hashicorp/nomad#5908]
Some of our jobs/tasks (running nomad clients on different machines then nomad servers) are being restarted when restarted nomad server appears again in the cluster. I would expect defensive behavior. Please, minimize restarts or correct me if I am wrong.
Is this behavior related also to https://github.com/hashicorp/nomad/pull/5669?

### Nomad version
0.9.1

### Operating system and Environment details
CentOS Linux

### Issue
Unexpected job restarts when nomad server comes back again (3node cluster).

### Reproduction steps
1. Start 3-node cluster
2. Submit job
3. Reboot one Nomad server (sudo reboot)
4. Check that some of the allocations of same job/task were restarted

### Job file (if appropriate)
Tested with both service and system jobs

**Comment by angrycub** [comment]
You might be encountering https://github.com/hashicorp/nomad/pull/5654.  This fix included in Nomad 0.9.2, I would encourage you to test this in the current version of Nomad and see if your issue is resolved.

Hope this helps!

**Comment by jozef-slezak** [comment]
Thank you for your reply. We are upgrading to 0.9.3 in our test environment at the moment.

**Comment by tantra35** [comment]
@jozef-slezak Can you confirm that 0.9.3 fix your issue?

**Comment by jozef-slezak** [comment]
Hello, it definitely helped but we observed two more issues that we are going to workaround:
1. missing consul dns service after cluster restart (workaround: reschedule by configuring script check nslookup + check_restart)
2. nomad sometimes after failover does not reschedule job - we see in the gui old placement (workaround: health check tcp port + check_restart)

I can create new issues and attache logs.
We will retest failovers many times during the day. I will post test results here.
