### ISSUE TITLE
Dead service after Nomad cluster restart

### ISSUE THREAD

**Issue by jozef-slezak** [hashicorp/nomad#5919]
We are restarting nomad cluster (3 nomad servers and tens of nomad clients all physical machines). Same test scenario https://github.com/hashicorp/nomad/issues/5917, https://github.com/hashicorp/nomad/issues/5908 but a different bug report.

Please check if this is related to https://github.com/hashicorp/nomad/pull/5669

### Nomad version
0.9.3

### Operating system and Environment details
Linux CentOS

### Issue
Service is not running after Nomad cluster restart.

### Reproduction steps
Restart all nomad servers and clients (sudo reboot).
Check Nomad console - sometimes we see DEAD services that was running before restart.

![image](https://user-images.githubusercontent.com/16844103/60656528-dd111500-9e4f-11e9-90c8-5f2b63cd2f8a.png)

**Comment by jozef-slezak** [comment]
I was able to reproduce this behavior also in a small three-node cluster in AWS.

**Comment by jozef-slezak** [comment]
I am attaching nomad config used in a small three-node cluster in AWS.
```
addresses = {
  http = "0.0.0.0"
}
advertise = {
  http = "172.31.34.128"
  rpc = "172.31.34.128"
  serf = "172.31.34.128"
}
bind_addr = "172.31.34.128"
client = {
  enabled = true
  network_interface = "eth0"
  options = {
    driver.raw_exec.enable = 1
    driver.raw_exec.no_cgroups = 1
  }
}
data_dir = "/var/lib/innovatrics/nomad"
datacenter = "dc1"
disable_update_check = true
log_level = "INFO"
consul {
  server_auto_join    = false
}
server = {
  bootstrap_expect = 3
  enabled = true
  encrypt = "xxx"
  server_join {
    retry_join = [ "172.31.39.40", "172.31.36.243" ]
    retry_max = 0 # infinite
    retry_interval = "3s"
  }
}

```

```
addresses = {
  http = "0.0.0.0"
}
advertise = {
  http = "172.31.39.40"
  rpc = "172.31.39.40"
  serf = "172.31.39.40"
}
bind_addr = "172.31.39.40"
client = {
  enabled = true
  network_interface = "eth0"
  options = {
    driver.raw_exec.enable = 1
    driver.raw_exec.no_cgroups = 1
  }
}
data_dir = "/var/lib/innovatrics/nomad"
datacenter = "dc1"
disable_update_check = true
log_level = "INFO"
consul {
  server_auto_join    = false
}
server = {
  bootstrap_expect = 3
  enabled = true
  encrypt = "xxx"
  server_join {
    retry_join = [ "172.31.34.128", "172.31.36.243" ]
    retry_max = 0 # infinite
    retry_interval = "3s"
  }
}
```

```
addresses = {
  http = "0.0.0.0"
}
advertise = {
  http = "172.31.36.243"
  rpc = "172.31.36.243"
  serf = "172.31.36.243"
}
bind_addr = "172.31.36.243"
client = {
  enabled = true
  network_interface = "eth0"
  options = {
    driver.raw_exec.enable = 1
    driver.raw_exec.no_cgroups = 1
  }
}
data_dir = "/var/lib/innovatrics/nomad"
datacenter = "dc1"
disable_update_check = true
log_level = "INFO"
consul {
  server_auto_join    = false
}
server = {
  bootstrap_expect = 3
  enabled = true
  encrypt = "xxx"

  server_join {
    retry_join = [ "172.31.34.128", "172.31.39.40" ]
    retry_max = 0 # infinite
    retry_interval = "3s"
  }
}
```

**Comment by jozef-slezak** [comment]
Attaching few more screenshots. Could a driver bug cause that job is not rescheduled?

![image](https://user-images.githubusercontent.com/16844103/60737366-cdcabe00-9f5a-11e9-9b7e-dc0397634c3a.png)

![image](https://user-images.githubusercontent.com/16844103/60737426-079bc480-9f5b-11e9-9c28-71563f391600.png)

**Comment by preetapan** [comment]
@jozef-slezak What does the output of `nomad job status -evals` for that job which is in this state look like?

**Comment by jozef-slezak** [comment]
```
ID                 Type     Priority  Status   Submit Date
id1              service  50        running  2019-07-03T13:42:51+02:00
activemq    service  50        running  2019-07-03T13:42:54+02:00
id3              service  50        running  2019-07-03T13:43:00+02:00
id4              service  50        running  2019-07-03T13:43:04+02:00
id5              service  50        pending  2019-07-03T13:43:08+02:00
id6              service  50        dead     2019-07-03T13:43:20+02:00
```

**Comment by jozef-slezak** [comment]
Could you please run the same test as @cgbaker did in https://github.com/hashicorp/nomad/issues/5917.

Repeat restarting the 3node cluster until you reproduce this behavior (DEAD job after restart).
* stop all nomad nodes (system stop nomad)
* wait for stopping
* start all nomad nodes (system start nomad)
* wait for starting and then check job status

**Comment by cgbaker** [comment]
I wasn't able to reproduce this with separate servers and clients. I did see some trouble that may be resolved in #5906. I will try to repro with that build.

**Comment by jozef-slezak** [comment]
@cgbaker, this issue is hard to reproduce. I believe it is related to "Error was unrecoverable" (see the screenshots above).

**Comment by jozef-slezak** [comment]
Today, I was able to simulate this buggy behavior on a single node (just by using sudo systemctl stop nomad and sudo systemctl start nomad). 

```
> nomad job status -evals id6
ID            = id1
Name          = id1
Submit Date   = 2019-04-23T11:01:40+02:00
Type          = service
Priority      = 50
Datacenters   = dc1
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
id6    1       0         0        0       0         0

Evaluations
ID  Priority  Triggered By  Status  Placement Failures

Allocations
No allocations placed


> free
              total        used        free      shared  buff/cache   available
Mem:        5895704     2205248     2666648       21780     1023808     3413816
Swap:       5435388           0     5435388
```

**Comment by cgbaker** [comment]
I tried to reproduce this using `2f55f78b21a5e55ab122f2c1e1ed1ec21fde9566` and with `KillMode=process` in the systemd unit, but I was unable to. @jozef-slezak , do you have `KillMode=process` configured?

**Comment by cgbaker** [comment]
@jozef-slezak : I attempted to repro this on a single node (client+server) with the latest Nomad `0eae387a96d6482cece2a8aa51f4aa8d8616549` (specifically, a Nomad including #5906. I repeatedly stopped and started the Nomad agent using `systemctl stop/start`, but no new allocations were ever created and the associated docker task was never interrupted.

**Comment by jozef-slezak** [comment]
Thanks for your cooperation. Tomorrow I will check the killmode. We are using raw exec instead of docker driver. This issue is about dead (not event started) process (not interrupted). Probably I should submit some test script and try with latest nomad.

**Comment by jozef-slezak** [comment]
We have KillMode=control-group. @cgbaker, what is you opinion, please? Please compare ```sudo systemctl stop nomad``` to ```sudo reboot```.

**Comment by cgbaker** [comment]
I will do more testing with either `reboot` or with `restart`/`KillMode=process`. For the record, we recommend configuring Nomad's systemd unit with `KillMode=process`.
