### ISSUE TITLE
kill_timeout doesn't apply to already running allocations when initial job update this parameter

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#5930]
### Nomad version
0.9.3

### Issue
To reproduce required create simple job difinition with single task in it, which ignore any signals(so we can emulate task stuck in terminating state) and define `kill_timeout`(https://www.nomadproject.io/docs/job-specification/task.html#kill_timeout, on client configuration we extend `max_kill_timeout` to 10m) for example to 10s, and launch it(`nomad run <job spec>`)

```
task sometasck 
{
   kill_timeout = "10s"
}
``` 

Then we update this job spec and change kill_timeout to `1m`. After we execute `nomad run <job spec>` nomad told to us, that he, modify allocation  

After modify job state we made `nomad alloc stop <allocatin id in modified job>` to reschedule allocation, and we expect that only after `1m` allocation will be killed, but this is not happened task will be killed after `10s` as was declared in initial job spec, then on rescheduled allocation we do the same(`nomad alloc stop <rescheduled allocatin id in modified job>`) and found that in this case `kill_timeout` will be applied and task will die only after 1m(which was expected)

**Comment by cgbaker** [comment]
This is operating as designed. The allocation is immutable; any changes to the job spec will be applied only to new evaluations.

**Comment by tantra35** [comment]
@cgbaker sorry, but why in this case `shutdown_delay` (https://www.nomadproject.io/docs/job-specification/task.html#shutdown_delay) will applied to already launched allocations, this fact confused us. Also in our opinion, if we changing job state(and we change it), this must lead to generate new evaluation in situations of immutable allocations. Also its very strange why declare additionally service(consul) in job spec, doesnt; lead to recreate allocations but simply create new service, what looks as logically

**Comment by cgbaker** [comment]
@tantra35: in my testing, an updated `shutdown_delay` does not apply to already launched allocations. 

```
ID        Node ID   Task Group  Version  Desired  Status    Created     Modified
452a3ad2  69e01651  group       7        run      pending   2m3s ago    2m3s ago
fbd1d71f  69e01651  group       6        stop     running   12m16s ago  2m3s ago

$ http localhost:4646/v1/allocation/fbd1d71f-2cf5-451e-1a79-a133ee6e40e9 | jq '.Job.TaskGroups[0].Tasks[0].ShutdownDelay'
120000000000

$ http localhost:4646/v1/allocation/452a3ad2-68be-add6-76bb-fb02878a1b9f | jq '.Job.TaskGroups[0].Tasks[0].ShutdownDelay'
0
```
Alloc fbd (with `ShutdownDelay = 120s`) ran for two minutes after being deregistered from Consul, before being killed and starting alloc 452 (with `ShutdownDelay = 0s`).
