### ISSUE TITLE
when nomad alloc stop invoked in allocation status doesn't show "Waiting %v before force killing"

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#5931]
### Nomad version
0.9.3

if we do `nomad alloc stop` the in stoped allocation status will be shown only "Sent interrupt" in one of events, but we expect that phrase must be more complex and must be looks like this "Sent interrupt. Waiting %v before force killing"

we think that this is happening because neither one in this fragments event doens't fill event struct

https://github.com/hashicorp/nomad/blob/master/client/allocrunner/alloc_runner.go#L502
https://github.com/hashicorp/nomad/blob/master/client/allocrunner/taskrunner/lifecycle.go#L71

**Comment by preetapan** [comment]
@tantra35 Thanks for reporting, #5943 fixes it.
