### ISSUE TITLE
job `args` and ` command` error executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by Liberxue** [hashicorp/nomad#5932]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
```zsh
Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)
```
### Operating system and Environment details
```zsh
Linux 10-0-1-206 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
### Job file (if appropriate)
```hcl
# This declares a job named "docs". There can be exactly one
# job declaration per job file.
job "test" {
  # Specify this job should run in the region named "us". Regions
  # are defined by the Nomad servers' configuration.
  region = "cn-bj2"
  # Spread the tasks in this job between us-west-1 and us-east-1.
  datacenters = ["cn-bj2"]
  # Run this job as a "service" type. Each job type has different
  # properties. See the documentation below for more examples.
  type = "service"
  # Specify this job to have rolling updates, two-at-a-time, with
  # 30 second intervals.
  update {
    stagger      = "30s"
    max_parallel = 2
  }
  # A group defines a series of tasks that should be co-located
  # on the same client (host). All tasks within a group will be
  # placed on the same host.
  group "namesrvGroup" {
    # Specify the number of these tasks we want.
    count = 2
    restart {
      attempts = 3
      delay    = "30s"
    }
    # Create an individual task (unit of work). This particular
    # task utilizes a Docker container to front a web application.
    task "namesrvTask" {
      # Specify the driver to be "docker". Nomad supports
      # multiple drivers.
      driver = "docker"
        env { 
            JAVA_OPT="-server -Xms1g -Xmx1g -Xmn512m"
        }
      # Configuration is specific to each driver.
      config {
        image = "hello-world"
        args    = ["echo abcd"]
        command= "echo eee"
      }
      # The service block tells Nomad how to register this service
      # with Consul for service discovery and monitoring.
      service {
        # This tells Consul to monitor the service on the port
        # labelled "http". Since Nomad allocates high dynamic port
        # numbers, we use labels to refer to them.
        port = "tcp"
      }
      # Specify the maximum resources required to run the task,
      # include CPU, memory, and bandwidth.
      resources {
        # cpu    = 500 # MHz
        # memory = 2048 # MB

        network {
          mbits = 100
          # This requests a dynamic port named "http". This will
          # be something like "46283", but we refer to it via the
          # label "http".
          port "tcp" {}
          # This requests a static port on 443 on the host. This
          # will restrict this task to running once per host, since
          # there is only one port 443 on each host.
          # port "https" {
          #   static = 8081
          # }
        }
      }
    }
  }
}

```
![image](https://user-images.githubusercontent.com/5831248/60758265-e6fd6880-a047-11e9-9a1a-9d12cd2c6fad.png)

* if jobs->config ->command == docker api cmd;docker cmd is strings

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tantra35** [comment]
@Liberxue

```
        args    = ["echo abcd"]
        command= "echo eee"
```

means that you actually invoke `"echo eee" echo abcd` where binary of command is `echo eee` , which looks like mistake

**Comment by Liberxue** [comment]
Just command  and args using ``echo`` is correct,
but a space can cause an exception.
So calling ``./shell.sh`` is also correct
but ``sh shell.sh`` is wrong, and does not give ``shell.sh ``external value. @tantra35

**Comment by tantra35** [comment]
@Liberxue, sorry, maybe I don't fully understend what you mean, but in last case what you describe 

 task declaration must looks like this:

```
        args    = ["./shell.sh"]
        command= "/bin/sh"
```

**Comment by Liberxue** [comment]
Why can't I use the ``cmd``  command scheme of the Docker API, but modify one myself?

**Comment by preetapan** [comment]
@Liberxue you have to use the documented options that are described here - https://www.nomadproject.io/docs/drivers/docker.html#command 

`command` is the command that runs when starting the container, and `args` are the arguments to the command.
