### ISSUE TITLE
Plugin API, TaskStats not called after RecoverTask after plugin restart

### ISSUE THREAD

**Issue by towe75** [hashicorp/nomad#5936]
### Nomad version

Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)

### Operating system and Environment details

Ubuntu 18.04

### Issue

I am working on a driver plugin and i miss stats if the plugin dies and restarts.

My plugin reports stats fine when a task is initially started. So i can see in the logs that "TaskStats" is called and i can watch metrics in the nomad web-ui.

Now, if i kill the plugin process (not nomad itself!) in order to simulate a crash, i can see that "RecoverTask" is invoked. The callback is handled well and i am able to control the task just fine.

"TaskStats", however, is not called after recovery and thus the plugin does not stream stats into nomad resulting in a stuck graph in the UI.

**Comment by preetapan** [comment]
Thanks for reporting this, I was able to reproduce this with the existing LXC driver

**Comment by towe75** [comment]
Thanks for checking!
Killing a plugin process is actually a nice shortcut for updating a plugin while working on the code base. It's much quicker compared to restarting a nomad agent. Automatic task recovery ensures a consistent in-memory state as well.
