### ISSUE TITLE
-XX:+UseContainerSupport worked well but -XX:MaxRAMPercentage will use physical RAM rather than nomad job resource limit in Java driver.

### ISSUE THREAD

**Issue by liukch** [hashicorp/nomad#5940]
### Nomad version
Nomad v0.9.0 (18dd59056ee1d7b2df51256fe900a98460d3d6b9)

### Operating system and Environment details
Ubuntu 18.04, OpenJDK 11

### Issue
I use jvm_options: -XX:+UseContainerSupport to config jvm heap size, it worked;
But I use jvm_options: -XX:MaxRAMPercentage / -XX:InitialRAMPercentage to specify the initial and maximum size of the Java heap as a percentage of the total memory available to the VM. java heap will use the percentage of the **Physical RAM**, rather than the nomad job resource limit.

### Reproduction steps
Use java driver and config like this:
```
config {
        jar_path = "local/XXX.jar"
        jvm_options = [
          "-enableassertions",
          "-XshowSettings:vm",
          "-XX:+UseContainerSupport",
          "-XX:InitialRAMPercentage=80",
          "-XX:MaxRAMPercentage=80",
          "-XX:+FlightRecorder",
          "-Djava.rmi.server.hostname=127.0.0.1",
          "-Dcom.sun.management.config.file=/local/management.properties",
          "-Xlog:gc",
        ]
        args = [
          "foo"
        ]
      }
```
And I use levant to deploy it.

**Comment by liukch** [comment]
I think you might see [HERE](https://www.eclipse.org/openj9/docs/xxusecontainersupport/) to get more information about jvm options: -XX:+UseContainerSupport  and  -XX:MaxRAMPercentage/-XX:InitialRAMPercentage

**Comment by rkettelerij** [comment]
See also https://github.com/hashicorp/nomad/issues/5376. Nomad doesn't mount the correct cgroups. Which is rather unfortunate, since this severely limits the usability of the java driver (my workaround is currently to explicitly specify Xms/Xmx....)

**Comment by liukch** [comment]
@rkettelerij  I see, thx.
