### ISSUE TITLE
Under hardenedBSD(freebsd downstream) nomad does not run.

### ISSUE THREAD

**Issue by peacetara** [hashicorp/nomad#5950]
## Issue

Under HardenedBSD(which is a downstream fork of FreeBSD), the memory system is hardened and the 32bit compat code is taken out.  This means that the gopsutil fingerprinting under nomad fails:
```
2019-07-11T11:00:18.218-0700 [WARN ] client.fingerprint_mgr.memory: error reading memory information: error="cannot allocate memory"
```

which happens on this call (kdump output):
```
83482 nomad    SCTL  "vfs.bufspace"
83482 nomad    RET   __sysctl -1 errno 12 Cannot allocate memory
```
This call fails because go expects a uint32, but it's actually a uint64 in size.

## Solutions

upsteam gopsutil properly uses a uint64 [here](https://github.com/shirou/gopsutil/blob/6a8ab0308ed6ddb7a871c5bb14ed4a5f3d79ac55/mem/mem.go#L53)

but gopsutil is vendored with an older version that uses uint32 [here](https://github.com/hashicorp/nomad/blob/c031f666c9cf7709d7f826255ac1b904673fe920/vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go#L44).

It looks like there was some work recently in #5201 to upgrade gopsutil.  I'd like you to perhaps re-apply that patch and upgrade your vendored gopsutil.

Alternatively, one can apply this patch:

```
diff --git a/vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go b/vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go
index e691227db..fcb4c3668 100644
--- a/vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go
+++ b/vendor/github.com/shirou/gopsutil/mem/mem_freebsd.go
@@ -41,7 +41,7 @@ func VirtualMemoryWithContext(ctx context.Context) (*VirtualMemoryStat, error) {
        if err != nil {
                return nil, err
        }
-       buffers, err := unix.SysctlUint32("vfs.bufspace")
+       buffers, err := unix.SysctlUint64("vfs.bufspace")
        if err != nil {
                return nil, err
        }
```

Which fixes the problem.  I understand HardenedBSD is not officially supported, and so maybe you don't care much, except uint32 is apparently even wrong under FreeBSD. It currently works under FreeBSD because of compat code to let a uint32 work.  That compat code will probably go away at some point :)

Anyways, for the adventurous among us, one can change the call like in the diff above in the meantime. if you want your HardenedBSD and Nomad to co-exist.

thanks to lattera & newnix in #HardenedBSD for their help.

Thanks for your time and consideration.

**Comment by preetapan** [comment]
@peacetara Thanks for the report. Given the surface area of usage of gopsutil we would do a vendor upgrade in a major release, will consider this ticket then.

**Comment by tgross** [comment]
ref https://github.com/hashicorp/nomad/issues/6957

**Comment by schmichael** [comment]
@peacetara Can you test Nomad 0.11.0-rc1 or later and confirm that this works? https://releases.hashicorp.com/nomad/

Closing for now because it ought to have fixed your issue, but please reopen if not!
