### ISSUE TITLE
alloc dir setup fails when user "nobody" doesn't exist

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#5963]
### Nomad version

`Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)`

### Operating system and Environment details

QNAP QTS version 4.3.6.0993.  It's a little … weird.  It's running Linux 4.2.8, but is decidedly non-standard in some ways.  Like `admin` has uid 0 (`root` doesn't exist), and the `nobody` user doesn't exist.  Otherwise, Nomad starts successfully as `admin`.

### Issue

Unable to start a job.  Allocation is pending, and the only indication of an error is the Nomad log:
```json
{
  "@level": "error",
  "@message": "prerun failed",
  "@module": "client.alloc_runner",
  "@timestamp": "2019-07-15T21:34:15.032874-04:00",
  "alloc_id": "212ac0bb-19df-847a-aa04-89f90de3af88",
  "error": "pre-run hook \"alloc_dir\" failed: user: unknown user nobody"
}
```

I think the `nobody` user should be configurable when setting up the alloc dir.

### Reproduction steps

1. get a QNAP NAS (or get access to mine)
2. `nomad agent -dev`
3. `nomad job run example.nomad` 👇

### Job file (if appropriate)

```hcl
job "test" {
  datacenters = ["dc1"]

  group "test" {
    ephemeral_disk {
      size = 10
    }

    task "test" {
      driver = "exec"
      user = "root"
      config {
        command = "/bin/bash"
        args = ["-c", "while :; do sleep 10; done"]
      }

      logs {
        max_files = 1
        max_file_size = 1
      }
      

      resources {
        cpu    = 500
        memory = 256
        network {
          mbits = 10
        }
      }
    }
  }
}
```

**Comment by angrycub** [comment]
@blalor you might try specifying the [`user`](https://www.nomadproject.io/docs/job-specification/task.html#user) in your job configuration to get around the missing nobody user.

Hopefully that unblocks you.

**Comment by blalor** [comment]
I worked around it by creating a `nobody` user.  I suspect it's this hard-coded bit that's the issue, however: https://github.com/hashicorp/nomad/blob/22fd62753510a4a41c1b8f1d117ea1a90b48df06/client/allocdir/fs_unix.go#L42
