### ISSUE TITLE
[question] How to avoid stale job after nomad client failed

### ISSUE THREAD

**Issue by RobinDong** [hashicorp/nomad#5964]
**Question**

After I started up one nomad server and two nomad clients(client1 and client2), I run the redis just following the guide
`nomad job init`
`nomad job run example.nomad`
The redis server has been launched, and attached to client1.
But after I kill client1 (for experiment), nomad launched another redis server and attached it to client2.
Now, by using `docker ps`, I found that there are two redis servers running. 

My question is: Is there any solution for nomad to run only one instance of a job ? If I just want to run one, and only one job (such as bank-transaction-processing job) in nomad, in whatever situation, could I do it by using exsited mechanism of nomad?

**Comment by angrycub** [comment]
Nomad doesn't provide run-once semantics and is designed to optimize for availability.  When the client is down, the work running on that client is in an indeterminate state. Nomad will consider that work lost after the heartbeat interval and start replacement instances of the work on healthy nodes.  

Currently, to make a guarantee like this, you would need to use an external synchronization scheme, for example, Zookeeper or a [Consul semaphore](https://learn.hashicorp.com/consul/developer-configuration/semaphore).

**Comment by RobinDong** [comment]
Thank you for your answer @angrycub 
I think I should use Zookeeper to implement run-once semantics afterwards.
