### ISSUE TITLE
Constraint "distinct_property" -> "Failed to place all allocations"

### ISSUE THREAD

**Issue by jozef-slezak** [hashicorp/nomad#5965]
### Nomad version
./nomad version
Nomad v0.9.4-dev (596b5aaf7ed572e60727942e69a118122b247692)

### Operating system and Environment details
Centos7

### Issue
Applying constraint on top of running jobs causes "Failed to place all allocations" but I would expect to reschedule allocations to fulfill the constraint. We saw this behavior on 0.9.1, 0.9.3, 0.9.4-dev.

### Reproduction steps
1. Run Count=39 of the same job on three node cluster
2. Stop one node
3. Wait until cluster detects ```nomad server members``` failed node
4. Check that jobs are rescheduled
5. Modify HCL (same count) - add constraint (max 13 jobs per node)
```
constraint {
operator = "distinct_property"
attribute = "${attr.unique.network.ip-address}"
value = "10"
}
```
6. Nomad plan/run says "Failed to place all allocations" but I would expect that it reschedules jobs to fulfill the constraint. The workaround is to stop the job (which you do not really want to do in production)

````
./nomad plan dummyapp.hcl
+/- Job: "dummyapp"
+ Constraint {
  + LTarget: "${attr.unique.network.ip-address}"
  + Operand: "distinct_property"
  + RTarget: "13"
  }
  Task Group: "dummyapp" (39 create/destroy update)
    Task: "dummyapp"

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "dummyapp" (failed to place 25 allocations):
    * Constraint "distinct_property: ${attr.unique.network.ip-address}=172.31.1.163 used by 13 allocs" filtered 1 nodes
    * Constraint "distinct_property: ${attr.unique.network.ip-address}=172.31.1.32 used by 13 allocs" filtered 1 nodes
    * Constraint "distinct_property: ${attr.unique.network.ip-address}=172.31.1.106 used by 13 allocs" filtered 1 nod
```


### Job file (if appropriate)
Before
```
job "dummyapp" {
  datacenters = ["dc1"]
  priority = 80

  group "dummyapp" {
    count = 39
    task "dummyapp" {
      driver = "raw_exec"

      config {
        command = "/home/centos/dummyapp",
        args = ["${NOMAD_PORT_WEB}"]
      }

      resources {
        cpu    = 20
        memory = 32
        network {
                port "WEB" {}
        }
      }
    }
  }
}
````

After applying constraint:

```
job "dummyapp" {
  datacenters = ["dc1"]
  priority = 80

  constraint {
    operator = "distinct_property"
    attribute = "${attr.unique.network.ip-address}"
    value = "13"
  }

  group "dummyapp" {
    count = 39
    task "dummyapp" {
      driver = "raw_exec"

      config {
        command = "/home/centos/dummyapp",
        args = ["${NOMAD_PORT_WEB}"]
      }

      resources {
        cpu    = 20
        memory = 32
        network {
                port "WEB" {}
        }
      }
    }
  }
}
```

**Comment by langmartin** [comment]
We're planning improvements to several categories of rescheduling in the next release or two, and fixing this behavior will be part of those efforts.

**Comment by shantanugadgil** [comment]
Since 0.9.6 and now 0.10.0 GA, is this still occurring?

**Comment by jozef-slezak** [comment]
I will check it out, thank you.
