### ISSUE TITLE
[UI] add brackets to links with IPv6 addresses

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#5966]
### Nomad version
Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)

### Issue
When a service registered on IPv6 interface nomad doesn't add bracket to the link
![Screenshot_20190716_193638](https://user-images.githubusercontent.com/14976219/61313169-9a155100-a802-11e9-8ba6-af8185f0496d.png)

Wrong: `http://2000:a:b:c::d:80`
Correct: `http://[2000:a:b:c::d]:80`

### Reproduction steps
Create a job with service which register on IPv6 address.
View links in UI.

**Comment by backspace** [comment]
Thanks for letting us know about this! I have a [PR for this](https://github.com/hashicorp/nomad/pull/5992), which you can try out [here](https://deploy-preview-5992--nomad-ui.netlify.com/ui/allocations/4dda8e19-a4a8-4843-bf30-bc824092c617) against a mock API.

**Comment by pznamensky** [comment]
Good news! Thank you!

**Comment by backspace** [comment]
I ended up using [a different approach](https://github.com/hashicorp/nomad/pull/6007), but it’s now merged, and should be released as part of version 0.9.5. 😀

**Comment by pznamensky** [comment]
Thanks!
