### ISSUE TITLE
Nomad consuming 10-25% CPU whilst doing nothing (ubuntu specific??)

### ISSUE THREAD

**Issue by endeavour** [hashicorp/nomad#5971]
### Nomad version
Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)

### Operating system and Environment details
Kubuntu 19.04 desktop
Linux 5.0.0-050000rc6-generic #201902102330 SMP Sun Feb 10 23:32:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Issue
Nomad consumes 10-25% CPU whilst seemingly doing nothing

### Reproduction steps
Run ```nomad agent -dev```, wait a minute or two for things to settle down then check ```top```. Nomad is consuming a lot of CPU for seemingly no reason.

I have tested this on two Ubuntu 19.04 machines and I see the same behaviour. I do not see the same behaviour on a Gentoo box.

**Comment by langmartin** [comment]
Is the nomad agent logging anything to explain what it's doing? Do you see the same CPU usage with 0.9.4-rc1?
