### ISSUE TITLE
[feature] Are there plans to opensorce namespaces support?

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#5988]
At now days nomad opensource doesn't have namespace support (https://www.nomadproject.io/api/namespaces.html), which puts nomad at a disadvantage compared to kubernetes. So it would be logical to opensource this by hashicorp, if no such plans will it be a violation if we opensource our implementation of namespace support as aditional patch to nomad opensource

**Comment by schmichael** [comment]
Good question and one we get a lot privately as well.

Right now we have no plans to open source namespaces and will not accept any community contributed versions as that would risk differing from the enterprise implementation.

While HashiCorp tries to migrate enterprise features to open source over time, we strive to include features in the enterprise versions of our products that meet organizational scaling needs. If we're critical to your line of business, we'd love to engage with you as a customer.

We've gotten similar asks in Consul and Vault as well, please see our responses there for additional clarification

https://github.com/hashicorp/consul/pull/5020#issuecomment-459502310

**Comment by schmichael** [comment]
For the record namespaces were open sourced in [Nomad v1.0.0](https://github.com/hashicorp/nomad/blob/v1.0.0/CHANGELOG.md) (December 2020)!
