### ISSUE TITLE
log flooding when using retry_join

### ISSUE THREAD

**Issue by yikaus** [hashicorp/nomad#599]
Nomd v.0.2.2

When applied below configuration to manually join a cluster  , the log file get flooded until other nodes are available

\# Enable the server
server {
    enabled = true
    bootstrap_expect = 3
    retry_join = ["192.169.0.20","192.168.0.21"]
}

However it showing retrying in 30s , but actually not  having any delay

   2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s
    2015/12/17 22:11:27 [WARN] agent: Join failed: dial tcp 192.168.0.20:4648: getsockopt: connection refused, retrying in 30s

**Comment by cbednarski** [comment]
Thanks for the report! Can you show the command you used to invoke Nomad? The serf consensus is much more aggressive than 30s delay so I suspect that one of your CLI flags was not parsed correctly.

**Comment by yikaus** [comment]
I am not using special command , see below

nomad agent -config /etc/nomad.d/server.hcl

server.hcl 

>bind_addr = "192.168.0.22"
>log_level = "DEBUG"
>data_dir = "/tmp/nomad"
>server {
>    enabled = true
>   bootstrap_expect = 3
>   retry_join = ["192.169.0.20","192.168.0.21"]
>}

**Comment by c4milo** [comment]
I've seen this too myself before

**Comment by diptanu** [comment]
I am trying to reproduce this now.

**Comment by yikaus** [comment]
Cool , wait for next release .

**Comment by diptanu** [comment]
@yikaus We just released 0.2.3 which had this fix!

**Comment by yikaus** [comment]
Just tried new release , it is fixed . Thanks
