### ISSUE TITLE
API: EOF error when calling Nodes().gcAlloc()

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#5994]
Nomad version v0.9.3 running locally (OSX) in dev mode.

To reproduce you can run Nomad locally in dev mode; run an example job and then stop the job . Once stopped the following code snippet can be used to observe the bug:

```
package main

import (
	"fmt"

	"github.com/hashicorp/nomad/api"
)

func main() {
	nomadClient, _ := api.NewClient(api.DefaultConfig())
	allocs, _, _ := nomadClient.Allocations().List(nil)
	fmt.Println(nomadClient.Nodes().GcAlloc(allocs[0].ID, nil))
}
```

The output:
```
EOF
```

The nomad server indicates a successful call:
```
2019-07-23T17:09:32.079+0200 [DEBUG] client.gc: alloc garbage collected: alloc_id=15935192-1b82-4d8e-1224-414010954153
2019-07-23T17:09:32.079+0200 [DEBUG] http: request complete: method=GET path=/v1/client/allocation/15935192-1b82-4d8e-1224-414010954153/gc duration=199.500448ms
```

Related to #5506 and #5970

**Comment by preetapan** [comment]
Thanks @jrasell - looking at this and #5970 we may need to add empty struct handling to a number of places in the API in a more standard way..
