### ISSUE TITLE
How to access Consul tags or provide custom meta tags in Nomad.

### ISSUE THREAD

**Issue by manish-panwar** [hashicorp/nomad#5995]
### Nomad version
v0.9.3

### Issue
Our objective is to deploy specific services (e.g. Zookeeper, Kafka) only on specific designated nodes. All of nodes have Consul and Nomad client. We started with assigning specific tags in Consul client config(e.g. "kafka_node=true"), and then we were thinking that we will use those tag value to define a Constraint/Affinity in Nomad job. We can't find anything in Nomad documentation on how to access Consul tags in Nomad job, or how to define custom meta for a given Nomad Client node (we are assuming that we can access Nomad Client meta-data using below sample):

> constraint {
        attribute = "${meta.my__custom_tag_name}"
        operator  = "="
        value     = "kafka"
      }

**Comment by angrycub** [comment]
@manish-panwar, If I understand your question correctly, It is possible to set [client metadata](https://www.nomadproject.io/docs/configuration/client.html#meta) in the Nomad configuration; this  [example](https://www.nomadproject.io/docs/configuration/client.html#custom-metadata-network-speed-and-node-class) might prove to be helpful as well. Once set, this metadata can then be used with constraints as you demonstrated.

Does this help unbind you?

**Comment by manish-panwar** [comment]
@angrycub - It worked! Thanks a lot! We tried using meta tag with Affinity and seem to not work, but yes, Constraint worked fine.
