### ISSUE TITLE
Doc: nomad variable sentence has gramatical error

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6018]
The variable interpolation docs have a sentence that doesn't make sense. 

https://www.nomadproject.io/docs/runtime/interpolation.html

```
# Environment variables are interpreted and can contain both runtime and
# node attributes. There environment variables are passed into the task.
```

What is meant by the phrase: 
>There environment variables are passed into the task.

Should that be?
>The environment variables are passed into the task.
or
>Their environment variables are passed into the task.

**Comment by preetapan** [comment]
Thanks @spuder , fixed in https://github.com/hashicorp/nomad/commit/e76bb99915a4a6b9586df152bc5131462e8ca1e4
