### ISSUE TITLE
[ui] [performance] Jobs overview UI slow and/or scales poorly

### ISSUE THREAD

**Issue by valorl** [hashicorp/nomad#6019]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
`Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)`

### Operating system and Environment details
- Ubuntu 16.04 on GCP
- 3 servers (`n1-standard-4`) co-located with Consul
- Running around 200 periodic jobs at `*/1 * * * * *` (simple `echo Hello World` to test scheduler performance)
### Issue
Running this many jobs, the default (Jobs overview) page of Nomad UI is very slow. I am assuming the browser is not able to handle this many data at once. This makes the page basically unusable, with the browser not even being able to render scrolling and hover animations etc.

### Reproduction steps

1. Deploy 200 periodic jobs with an `echo Hello World` container with `*/1 * * * * *` as schedule
2. Open the Nomad UI on the "Jobs" page.
3. The page should be extremely laggy. 

### Additional info
When inspecting with Chrome Dev Tools. I can see that the constant polling of `v1/jobs` returns all of the jobs including the periodic runs (currently it's around 8000 objects for me). These requests take anywhere from 0.5s to (occasionally) 13s. 

I assume propagating this huge array throughout the SPA is what's causing the poor FPS. Perhaps the pagination should be server-side, or at least the request should not include all of the children for every job ?

**Comment by alexboboc** [comment]
I’ve encountering this on 1.0.0 as well.
