### ISSUE TITLE
Let user know when an allocation failed due to inexistent datacenter.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#605]
I was trying to schedule a job in a datacenter not recognized by my Nomad clients, so naturally the allocation failed but the message it is not very clear specifying the it failed because the job was trying to be scheduled on an inexistent datacenter. 

```
$ nomad run -address http://192.168.50.4:4646 docker-registry/registry.nomad ==> Monitoring evaluation "c4023228-971b-a22c-a81c-beb064fec6e7"
    Evaluation triggered by job "docker"
    Scheduling error for group "api" (failed to find a node for placement)
    Allocation "564c0e0a-0aaf-a164-51a1-22db90581ef4" status "failed" (0/0 nodes filtered)
      * No nodes were eligible for evaluation
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "c4023228-971b-a22c-a81c-beb064fec6e7" finished with status "complete"
```

**Comment by dadgar** [comment]
Are there any other cases you run into a lack of information? This is definitely a case but most should have information about why the node was filtered!

**Comment by c4milo** [comment]
Let's leave this issue for notifying when a datacenter was not found. If I run into a new case I will report it in a separate issue.

**Comment by c4milo** [comment]
nice! thanks @dadgar! :dancer:
