### ISSUE TITLE
Nomad 0.9.3 multiple panics

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#6063]
### Nomad version
Output from `nomad version`

### Operating system and Environment details

Ubuntu 18.04

### Issue

I saw the symptom live: the deployment (1 container) was in progress in the UI, reporting the one container unhealthy but Consul service checks were passing.

### Reproduction steps

Apparently, the container was unhealthy during the deployment and one of our engineers clicked restart during the deployment itself. Might not be related.

### Job file (if appropriate)

https://gist.github.com/scalp42/4c3cec1149be1612f82e385ea3433f0e

### Nomad Client logs (if appropriate)

https://gist.github.com/scalp42/70ca6217e96982dd574c188f3829c93c

### Nomad Server logs (if appropriate)

Could not find anything on servers.

**Comment by endocrimes** [comment]
@scalp42 Thanks for reporting - If I'm reading the logs correctly, it look like the panic occured while somebody was trying to `nomad alloc exec` a command while it was starting up?

**Comment by scalp42** [comment]
Hi @endocrimes, I'm asking the engineer, trying to gather as much info as I can.

**Comment by scalp42** [comment]
Per the engineer, they didn't 🤷‍♂
