### ISSUE TITLE
Unable to see any metrics related to Nomad when Consul or Vault are running on the same host

### ISSUE THREAD

**Issue by svudutala** [hashicorp/nomad#6072]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.9.1 

### Operating system and Environment details
CentOS 

### Issue
No telemetry exposed from any of the agents (consul/vault/nomad) when running on a single host.

### Reproduction steps
Using stats_address on consul/vault/nomad with ports 8125,8126, 8127 respectively.
```
Nomad telemetry.hcl:
telemetry {
  publish_allocation_metrics = true
 publish_node_metrics       = true
 statsd_address= "localhost:8127"
}
```

Using dogstatsd_addr and 127.0.0.1 (instead of localhost) as per workaround suggested here https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/nomad-tool/tad1_8nmC3k/lxTUu2dKEwAJ

```
Consul.json
{
"telemetry": {
        "dogstatsd_addr" : "127.0.0.1:8125",
        "disable_hostname": true
    }
}

```
```
Nomad telemetry.hcl

telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
  datadog_address= "127.0.0.1:8127"
  collection_interval = "10s"
  disable_hostname = true
}

```
```
Vault telemetry.hcl

{
"telemetry": {
        "dogstatsd_addr": "127.0.0.1:8126",
        "disable_hostname": true
    }
}

```

No metrics reported on local UDP port with netcat
`netcat -ulp 8125`
`netcat -ulp 8126`
`netcat -ulp 8127`

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by manish-panwar** [comment]
@svudutala - I have validated that it works with latest version of Vault, Noamd and Consul. Maybe you can close this issue.
