### ISSUE TITLE
batch jobs causes error message in stats_hook

### ISSUE THREAD

**Issue by 42wim** [hashicorp/nomad#6073]
### Nomad version
0.9.4

### Issue
Batch jobs causes ERROR message in stats_hook (even when they exit clean)

Aug 05 17:13:18 q-cloud nomad[125584]: 2019-08-05T17:13:18.444+0200 **[ERROR]** client.alloc_runner.task_runner.task_hook.stats_hook: failed to start stats collection for task with unrecoverable error: alloc_id=58b67839-0704-081e-b05c-3e39898d8461 task=batch-job error="container stopped"
Aug 05 17:13:18 q-cloud nomad[125584]: 2019-08-05T17:13:18.470+0200 [INFO ] client.alloc_runner.task_runner: not restarting task: alloc_id=58b67839-0704-081e-b05c-3e39898d8461 task=batch-job reason="Restart unnecessary as task terminated successfully"

**Comment by 42wim** [comment]
same on 0.9.5

**Comment by msvbhat** [comment]
I'm seeing same error messages in 0.9.5. From what I can tell, it looks like a harmless message and may be it should not be logged as error?

**Comment by tgross** [comment]
It looks like this happens for all tasks, but it's just a lot more noticeable for batch jobs because they terminate as part of their regular operation. I agree with you @msvbhat that this is most likely over-zealous logging.

**Comment by erhlee-bird** [comment]
Confirming that this still happens.

- Nomad version: v0.10.2
- Parameterized Batch Jobs
- Docker Driver

**Comment by tgross** [comment]
Thanks @erhlee-bird. It definitely is a case where we're logging something that doesn't really need to be logged, especially as `ERROR` because it's going to happy literally every time an alloc stops. I've marked this issue for cleanup, but happy to take a PR if you have time to contribute too!

**Comment by tgross** [comment]
I still want to fix this error message and haven't gotten around to it. I think adding the `enhancement` label will get stalebot to chill.

**Comment by tgross** [comment]
Sorry about the delay on such a trivial item. Will ship in 0.11.3.
