### ISSUE TITLE
Unable to detect openjdk java verion.

### ISSUE THREAD

**Issue by Magicloud** [hashicorp/nomad#6081]
### Nomad version
v0.9.4

### Operating system and Environment details
CentOS 7

### Issue
I cannot use `driver.java.version` constraint since it cannot get valid nodes.

### Reproduction steps
Use following driver and contraint.
```
      driver = "java"
      constraint {
        attribute = "${driver.java.version}"
        operator  = ">="
        value     = "11.0.0"
      }
```
Without the contraint (comment the whole object), task running fine. With the contraint, I got
```
Constraint "${driver.java.version} >= 11.0.0" filtered 1 nodes
```
While java version is:
```
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```

**Comment by tgross** [comment]
Hello @Magicloud, thanks for your report!
I was able to partially reproduce what you’re seeing as follows:

```
$ docker run -it centos:7 /bin/bash
[root@b08656f9475b /]# yum install java-11-openjdk curl unzip
[root@b08656f9475b /]# curl -o nomad.zip https://releases.hashicorp.com/nomad/0.9.4/nomad_0.9.4_linux_amd64.zip
[root@b08656f9475b /]# unzip nomad.zip
[root@b08656f9475b /]# ./nomad agent -dev
```

and then submit the following job:

```hcl
job "example" {
  datacenters = ["dc1"]

  type = "service"
  constraint {
    attribute = "${driver.java.version}"
    operator  = ">="
    value     = "11.0.0"
  }

  group "example" {
    task "example" {
      driver = "java"
      config {
        jar_path    = "local/hello.jar"
        jvm_options = ["-Xmx2048m", "-Xms256m"]
      }
    }
  }
}
```

which returned the following:
```
[root@b08656f9475b /]# ./nomad job run ./java.nomad
==> Monitoring evaluation "cda32b2b"
    Evaluation triggered by job "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "cda32b2b" finished with status "complete" but failed to place all allocations:
    Task Group "example" (failed to place 1 allocation):
      * Constraint "${driver.java.version} > 11.0.0" filtered 1 nodes
    Evaluation "5a36988b" waiting for additional capacity to place remainder
```

when I do `java --version` I get:
```
[root@b08656f9475b /]# java --version
openjdk 11.0.4 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```

It looks like this version of the JDK doesn’t include `"` around the version and that’s throwing off the regex we use to parse the version; if I put this string into our unit tests for the java version parsing, I see the version doesn’t come back as `11.0.4` as I’d expect. But that version string isn’t _quite_ what you’re showing in your report. Can you confirm whether you ran that `java --version` command on the client?

**Comment by Magicloud** [comment]
Yes, my bad. I pasted java version strings from wrong term. The CentOS one is like yours, no quotes.

**Comment by chriswhite199** [comment]
I have a similar issue to this - java driver is not detecting for the following:

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

Client in the UI shows java detected: No.

Is there any debug logging i can enable to help diagnose?
