### ISSUE TITLE
Consul Connect Native support

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6083]
Implement support for Consul Connect Native services: https://www.consul.io/docs/connect/native.html

A little struct plumbing work we need to ensure the CONSUL_TOKEN is exposed to the native task when Consul ACLs are enabled.

Also need to give the namespaced native service access to the host Consul API.

**Comment by idrennanvmware** [comment]
Wanted to check in on this issue as it's in the critical path for us on a production nomad deployment.   We have windows and Linux machines that we need to use the native connect client so we cannot commit to envoy

Does this still look like it can make the 0.10.3 milestone?
