### ISSUE TITLE
Unable to execute "nomad alloc logs..." with ACL token that has "write" policy

### ISSUE THREAD

**Issue by blairnangle** [hashicorp/nomad#6086]
I am using Vault for secrets management to generate short-lived Nomad ACL tokens with which my deployment agent can authenticate against Nomad:
```bash
vault read -field=secret_id nomad/creds/deployment-agent
```

My ACL policy is:
```hcl
namespace "default" {
  policy = "write"
}
```
I am using my deployment agent to submit Nomad jobs for deployment:
```bash
nomad job run {{ temp_directory.path }}/{{ service_name }}.nomad
```
Both of the above steps work as expected. However, when I try to get the logs of a failed Nomad deployment using
```bash
nomad alloc logs -token {{ nomad_token.stdout }} -job {{ service_name }} {{ task_name }}
```
I am getting
```bash
"Error reading file: Unexpected response code: 403 (Permission denied)"
```
According to the Nomad [documentation](https://www.nomadproject.io/guides/security/acl.html#namespace-rules), the `"write"` policy includes the `"read-logs"` capability, so I don't understand why I am unable to get the logs using the same token with which I am able to submit a job.

#### Notes
* I was unable to get the logs after updating the policy to explicitly include the "read-logs" capability (as well as the "write" policy)
* I was able to get the logs using the root/bootstrap ACL token

**Comment by blairnangle** [comment]
I found that adding a `"read"` policy for `node` in my ACL policy did the trick:
```hcl
namespace "default" {
  policy = "write"
}

node {
  policy = "read"
}
```

**Comment by langmartin** [comment]
Here is another report of the same issue, with some context that explains why `read` is required: https://github.com/hashicorp/nomad/issues/5754

**Comment by blairnangle** [comment]
Thank you, @langmartin. That explains the issue I was having.
