### ISSUE TITLE
nomad job failover not working once it failed over before

### ISSUE THREAD

**Issue by yikaus** [hashicorp/nomad#609]
Nomd v0.2.3
Not sure if this can be replicated easily for other people  , here is the steps I did to demo this issue 

##### Nomad Setup 

3 servers & 3 client running on 3 vagrant machine (docker1,2,3) . 1 server and 1 client per machine .

given docker2 /etc/nomad as example, other two machines are similar except IP 
>datacenter = "dc1"
>bind_addr = "192.168.0.21"
>log_level = "INFO"
>data_dir = "/tmp/nomad"
>server {
>   enabled = true
>    bootstrap_expect = 3
>    retry_join = ["192.169.0.20","192.168.0.22"]
>}
>client {
>	enabled = true
>	servers = ["192.168.0.20", "192.168.0.21", "192.168.0.22"]
>}

$ nomad node-status
>ID  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DC &nbsp;Name &nbsp;&nbsp;    Class &nbsp;&nbsp;   Drain &nbsp;&nbsp; Status
...-9c43bd112dd1 dc1  docker2  `<none>`  false  ready
...-6dff84b97c74 &nbsp;&nbsp;dc1  docker3  `<none>`  false  ready
...-87a20b4ec832 &nbsp;dc1  docker1  `<none>`  false  ready

##### Run job
 I am using example job definition generated by nomad init , only change count to 3 .   After nomad-run  the scheduler works as expected . redis docker instance run 1 instance on each hosts . 

$nomad status example
>ID &nbsp;&nbsp;EvalID &nbsp;&nbsp;  NodeID &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;   group&nbsp;&nbsp;   Desired Status
... &nbsp;...115c1&nbsp;&nbsp;...-6dff84b97c74&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-87a20b4ec832&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-9c43bd112dd1&nbsp;cache &nbsp;&nbsp;run     running

##### Break one host 
eg. shutdown docker2 to test the failover

$ nomad node-status
>ID  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DC &nbsp;Name &nbsp;&nbsp;    Class &nbsp;&nbsp;   Drain &nbsp;&nbsp; Status
>...-9c43bd112dd1 dc1  docker2  `<none>`  false  down
>...-6dff84b97c74 &nbsp;&nbsp;dc1  docker3  `<none>`  false  ready
>...-87a20b4ec832 &nbsp;dc1  docker1  `<none>`  false  ready

$ nomad status example
>ID &nbsp;&nbsp;EvalID &nbsp;&nbsp;  NodeID &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;   group&nbsp;&nbsp;   Desired Status
... &nbsp;...`b2c23`&nbsp;&nbsp;...-6dff84b97c74&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-6dff84b97c74&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-87a20b4ec832&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-9c43bd112dd1&nbsp;cache &nbsp;&nbsp;stop     running

job instance moved to docker3 from docker2  . So now I got two docker instance (evalID 115c1& b2c23) running on docker3 (6dff84b97c74) perfect

##### Break docker3 , here comes problem

Bring back docker2 and shutdown docker3 

$ nomad node-status
>ID  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DC &nbsp;Name &nbsp;&nbsp;    Class &nbsp;&nbsp;   Drain &nbsp;&nbsp; Status
>...-dc4d0aa93d28 &nbsp;dc1  docker2  `<none>`  false  ready
>...-9c43bd112dd1 dc1  docker2  `<none>`  false  down
>...-6dff84b97c74 &nbsp;&nbsp;dc1  docker3  `<none>`  false  down
>...-87a20b4ec832 &nbsp;dc1  docker1  `<none>`  false  ready

$ nomad status example
>ID &nbsp;&nbsp;EvalID &nbsp;&nbsp;  NodeID &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;   group&nbsp;&nbsp;   Desired Status
... &nbsp;...`e897f`&nbsp;&nbsp;...-dc4d0aa93d28&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...`b2c23`&nbsp;&nbsp;...-6dff84b97c74&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-6dff84b97c74&nbsp;cache &nbsp;&nbsp;stop     running
... &nbsp;...115c1&nbsp;&nbsp;...-87a20b4ec832&nbsp;cache &nbsp;&nbsp;run     running
... &nbsp;...115c1&nbsp;&nbsp;...-9c43bd112dd1&nbsp;cache &nbsp;&nbsp;stop     running

From the job status we can see one job in docker3 failover to new docker2 , one doesn't .The job able to failover is the job original assigned to docker3 (evalID 115c1) , the job once failover to docker3 (evalID b2c23 ) not able to failover again , and it still shows run on docker3 . 

Another issue is  Desired and Status get confused to me ,  as Status always shows running only Desired changed . 

I hope my description is clear to this issue . From my end I can confirm this is not intermittent issue and noting much I can digest from nomad log particularly for this issue . 

Any thoughts ?

Kevin

**Comment by diptanu** [comment]
@yikaus Can you please post your job configuration so that we can reproduce the issue? Also I am wondering if the host docker2 had enough capacity to allow the failover from host docker3?

**Comment by yikaus** [comment]
@diptanu pretty sure got sufficient resource , as I change memory down to 256mb , see below . and also with insufficient resource , it will show something failed in nomad status , not like the above . 


job "example" {
	region = "au"

	datacenters = ["dc1"]

	# Service type jobs optimize for long-lived services. This is
	# the default but we can change to batch for short-lived tasks.
	type = "service"

	# Priority controls our access to resources and scheduling priority.
	# This can be 1 to 100, inclusively, and defaults to 50.
	# priority = 50

	# Restrict our job to only linux. We can specify multiple
	# constraints as needed.
	constraint {
		attribute = "$attr.kernel.name"
		value = "linux"
	}

	# Configure the job to do rolling updates
	update {
		# Stagger updates every 10 seconds
		stagger = "10s"

		# Update a single task at a time
		max_parallel = 1
	}

	# Create a 'cache' group. Each task in the group will be
	# scheduled onto the same machine.
	group "cache" {
		# Control the number of instances of this groups.
		# Defaults to 1
		count = 3

		# Restart Policy - This block defines the restart policy for TaskGroups,
		# the attempts value defines the number of restarts Nomad will do if Tasks
		# in this TaskGroup fails in a rolling window of interval duration
		# The delay value makes Nomad wait for that duration to restart after a Task
		# fails or crashes.
		restart {
			interval = "5m"
			attempts = 10
			delay = "25s"
		}

		# Define a task to run
		task "redis" {
			# Use Docker to run the task.
			driver = "docker"

			# Configure Docker driver with the image
			config {
				image = "redis:latest"
				port_map {
					db = 6379
				}
			}

			service {
				name = "${TASKGROUP}-redis"
				tags = ["global", "cache"]
				port = "db"
				check {
					name = "alive"
					type = "tcp"
					interval = "10s"
					timeout = "2s"
				}
			}

			# We must specify the resources required for
			# this task to ensure it runs on a machine with
			# enough capacity.
			resources {
				cpu = 500 # 500 Mhz
				memory = 256 # 256MB
				network {
					mbits = 10
					port "db" {
					}
				}
			}
		}
	}
}

**Comment by dadgar** [comment]
Confirmed it was broken in 0.2.3 and confirmed that it works in Nomad 0.3.1. The reason it was broken in 0.2.3 was the update block was broken and the second node had two tasks on it so that would cause max_parallel = 1 updates to happen and the follow up eval never occurred.
