### ISSUE TITLE
Support mounting volumes into executor context / task alloc dir

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/nomad#61]
When running a task we would like to share data between other tasks in a task group. Also, if using something like ceph or EBS we would like to support mounting a volume into the executor's context (chroot, cgroup, etc.) so it can write persistent data.

Probably depends on #60, so mounts are mounted into a tasks's environment and have some level of isolation from other tasks on the system.

**Comment by zrml** [comment]
@cbednarski: you would like to share some data or do you mean host dirs & files sharing? (I'm translating task = container right now)
In the use cases I have in mind, container in DB1 with -v /DB1:DB1
must not share anything with container DB2.

**Comment by cbednarski** [comment]
@zrml We want to support something like this:

```
/alloc/data
/task1/data
/task1/shared -> /alloc/data
/task2/data
/task2/shared -> /alloc/data
```

This way tasks in a task group can share data amongst themselves. I think there is already some work for this in the exec chroot implementation -- I probably have the directories wrong. @dadgar might be able to share some more details.

**Comment by zrml** [comment]
not a bad idea... I think I see where you are going (shared volumes vs private). OK Cool.
thanks guys.
Keep it coming :)

**Comment by ketzacoatl** [comment]
I see this similar to http://kubernetes.io/v1.0/docs/user-guide/volumes.html, and an equivalent to http://kubernetes.io/v1.0/docs/user-guide/volumes.html#awselasticblockstore would push this over the top!

**Comment by trong** [comment]
Very important thing. I would like to run cadvisor as a system type task, but:
```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

**Comment by ketzacoatl** [comment]
@trong what happens when you do this as a direct / raw_exec?

**Comment by trong** [comment]
@ketzacoatl could you explain your question?

It is possible to use raw_exec driver as workaround, in general - not. I think that for docker container we must use Nomad docker driver.

**Comment by ketzacoatl** [comment]
Have you tested this? Why could you not use the `raw_exec` driver?

**Comment by trong** [comment]
> Have you tested this?

Yes, I can start cadvisor through raw_exec driver.

> Why could you not use the raw_exec driver?

For example - how to stop docker container correctly with raw_exec?

**Comment by Ashald** [comment]
Are there any chances to get such functionality with `exec` driver?

**Comment by dadgar** [comment]
Hey this will come at some point. We just want to wait till we have volumes so that there is a consistent syntax.

**Comment by schmichael** [comment]
Closing this is favor of #150 for persistent volumes and #2115 which I think are a superset of this issue.
