### ISSUE TITLE
Resources exhausted

### ISSUE THREAD

**Issue by atrusch** [hashicorp/nomad#6153]
### Nomad version
Nomad v0.9.3 (c5e8b66c3789e4e7f9a83b4e188e9a937eea43ce)

### Operating system and Environment details
CentOS 7

### Issue
I have 2 client node. If I want to run 2 jobs (NodeRouter and RabbitMQ) with a group count = 2 and a static port the second job send a warning.

```
$nomad job plan target/deploy/NodeRouter.job

+ Job: "NodeRouter-dev"
+ Task Group: "NodeRouter-group-dev" (2 create)
  + Task: "NodeRouter-dev" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "NodeRouter-group-dev" (failed to place 1 allocation):
    * Resources exhausted on 2 nodes
    * Dimension "disk" exhausted on 1 nodes
    * Dimension "network: reserved port collision" exhausted on 1 nodes

Job Modify Index: 0
To submit the job with version verification run:

```

I have the same problem if I don't fixe the port and add a constraint distinct_hosts.
Only the first job can be deployed on the 2 nodes.

If I start with NodeRouter, the RabbitMQ job have the same warning message.

### Job example
```
job "NodeRouter-dev"
{
  datacenters = ["PA4"]
  type = "service"

  constraint {
    attribute = "${meta.dev-node}"
    operator  = "="
    value     = "true"
  }

  group "NodeRouter-group-dev" {
    count = 2

    update {
      max_parallel = 1
    }

    migrate {
      max_parallel = 1
    }

    task "NodeRouter-dev" {
      driver = "docker"

      env {
        DS_ENV="dev"
        CONSUL="${NOMAD_IP_noderouter}"
        VERSION="190819_1130"
      }

      config {
        image = "xxx.com:5000/repository/docker/noderouter:dev-1.0.0-SNAPSHOT"
        port_map = {
            noderouter = 3000
        }
        volumes = [ "/var/log/NodeRouter:/var/log/NodeRouter" ]
        force_pull = "true"
      }

      service {
        name = "NodeRouter-dev"
        tags = ["ws-dev","port-10010"]
        port = "noderouter"
        address_mode = "host"
      }

      resources {
        cpu = 100
        memory = 80
        network {
          port "noderouter" {
            static=3030
          }
        }
      }
    }
  }
}
```

**Comment by cgbaker** [comment]
Have you tried to resolve the issue with the exhaustion of disk resources?

**Comment by atrusch** [comment]
Thanks a lot, it was a disk space calculation problem.

I added space on / and now I can deploy.

But the used space is not the good one :
````
Allocated Resources
CPU            Memory           Disk
1400/4998 MHz  1.5 GiB/7.6 GiB  1.2 GiB/5.7 GiB
````

and the real space (all my docker are on other device):
````
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/centos-root     6.0G  326M  5.7G   6% /
````


One nice feature would be to be able to specify the mount point on each agent for each driver.

**Comment by cgbaker** [comment]
The amount that is display (`1.2 GiB`) is for the default ephemeral disk associated with each task group: https://www.nomadproject.io/docs/job-specification/ephemeral_disk.html

The default size is 300 MiB; 300 * group_count (2) * num_apps (2) is 1.2 GiB. This is space that is allocated for logs.

I'm going to close this issue. Feel free to open additional issue with other feature requests.
