### ISSUE TITLE
[question] gc not triggered

### ISSUE THREAD

**Issue by maxio89** [hashicorp/nomad#6160]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
`Nomad v0.9.4 (a81aa846a45fb8248551b12616287cb57c418cd6)
`
### Operating system and Environment details
Ubuntu 16.04

### Issue
I try to use alloc dir as temporary storage that disappears when job is completed, but with no luck.

My server and client configurations look like this:

```
client {
  enabled = true
  gc_interval = "1m"
}

```
```
server {
  enabled          = true
  bootstrap_expect = 2
  job_gc_threshold = "1m"
  node_gc_threshold = "1m"
  eval_gc_threshold = "1m"
  deployment_gc_threshold  = "1m"
}
```

In server logs I cannot find any info about gc. In client logs I can see only something like this:
```
2019-08-20T14:28:47.163Z [DEBUG] client: updated allocations: index=51022 total=1 pulled=0 filtered=1
    2019-08-20T14:28:47.164Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2019-08-20T14:28:47.164Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
```

Job is stopped:

```
nomad alloc status -verbose 7e77177c-3604-7c0a-32ae-ec27aea15684
ID                  = 7e77177c-3604-7c0a-32ae-ec27aea15684
Eval ID             = 04122051-a475-27bb-edfb-186ba0e35e8c
Name                = azure-file-integration.azure-file-integration[0]
Node ID             = 89f2716b-38f3-1572-c9a7-928360647af6
Node Name           = 198.19.1.45_client
Job ID              = azure-file-integration
Job Version         = 824638070816
Client Status       = complete
Client Description  = All tasks have completed
Desired Status      = stop
Desired Description = alloc not needed due to job update
Created             = 2019-08-20T13:53:17Z
Modified            = 2019-08-20T14:18:24Z
Deployment ID       = f72b7ba3-702e-e2dd-9c3f-28f09c41825e
Deployment Health   = healthy
Evaluated Nodes     = 2
Filtered Nodes      = 0
Exhausted Nodes     = 0
Allocation Time     = 80.938µs
Failures            = 0

Task "azure-file-integration" is "dead"
Task Resources
CPU      Memory   Disk     Addresses
500 MHz  1.0 GiB  300 MiB  api: 198.19.1.45:8080

Task Events:
Started At     = 2019-08-20T13:53:41Z
Finished At    = 2019-08-20T13:56:28Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2019-08-20T13:56:28Z  Killed      Task successfully killed
2019-08-20T13:56:28Z  Terminated  Exit Code: 130, Exit Message: "Docker container exited with non-zero exit code: 130"
2019-08-20T13:56:28Z  Killing     Sent interrupt. Waiting 5s before force killing
2019-08-20T13:53:41Z  Started     Task started by client
2019-08-20T13:53:17Z  Driver      Downloading image
2019-08-20T13:53:17Z  Task Setup  Building Task Directory
2019-08-20T13:53:17Z  Received    Task received by client

Placement Metrics
Node                                  binpack  job-anti-affinity  node-reschedule-penalty  node-affinity  final score
0dacd12a-27fd-2de3-29a7-459e0297c799  0.057    0                  0                        0              0.057
89f2716b-38f3-1572-c9a7-928360647af6  0.057    0                  0                        0              0.057
```

```nomad job status -verbose azure-file-integration
ID            = azure-file-integration
Name          = azure-file-integration
Submit Date   = 2019-08-20T14:22:24Z
Type          = service
Priority      = 100
Datacenters   = phd-ecp
Status        = dead (stopped)
Periodic      = false
Parameterized = false

Summary
Task Group              Queued  Starting  Running  Failed  Complete  Lost
azure-file-integration  0       0         0        0       2         0

Evaluations
ID                                    Priority  Triggered By        Status    Placement Failures
8b137269-5a27-b549-1f0b-904f8f84f180  50        job-deregister      complete  false
54ba91f0-159a-ff1f-277a-34de38dd0e65  100       deployment-watcher  complete  false
61282872-d38c-50aa-877f-d95b933d9f58  100       job-register        complete  false
7190a9da-96bf-5b8c-d6ab-4d31c0bb13b9  50        job-deregister      complete  false
5205dec9-e5e4-9c18-7460-44eec3e959cb  100       node-update         complete  false
04122051-a475-27bb-edfb-186ba0e35e8c  100       job-register        complete  false

Latest Deployment
ID          = 29ea741c-65f8-1da1-64cc-bad8f305fc26
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group              Desired  Placed  Healthy  Unhealthy  Progress Deadline
azure-file-integration  1        1       1        0          2019-08-20T14:33:01Z

Allocations
ID                                    Eval ID                               Node ID                               Node Name           Task Group              Version  Desired  Status    Created               Modified
52193aed-50cb-13f0-3161-e16de9f2316c  61282872-d38c-50aa-877f-d95b933d9f58  87b13836-d1e1-5228-536b-be71d7baf10c  198.19.1.51_client  azure-file-integration  3        stop     complete  2019-08-20T14:22:25Z  2019-08-20T14:32:48Z
7e77177c-3604-7c0a-32ae-ec27aea15684  04122051-a475-27bb-edfb-186ba0e35e8c  89f2716b-38f3-1572-c9a7-928360647af6  198.19.1.45_client  azure-file-integration  0        stop     complete  2019-08-20T13:53:17Z  2019-08-20T14:18:24Z
```

But still I can see file in 
`/nomad/client-data/alloc/7e77177c-3604-7c0a-32ae-ec27aea15684/alloc/data/foo`
until I manually call: `/v1/system/gc`

Why is that?

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by cgbaker** [comment]
The garbage collector runs on the schedule, as well as when allocations are started and when they change state. However, allocations are only deleted when the usage exceeds one of the thresholds: 
- disk usage
- inode usage
- maximum number of allocs on this client
The configuration parameters for these are in the client config documentation: https://www.nomadproject.io/docs/configuration/client.html

If you insist on deleting those directories as soon as the job is complete, you could set `gc_max_allocs` to a very low number. This means that allocation directories (including logs) will not be available for long for any allocation on the client.

**Comment by qqzeng** [comment]
> The garbage collector runs on the schedule, as well as when allocations are started and when they change state. However, allocations are only deleted when the usage exceeds one of the thresholds:
> 
> * disk usage
> * inode usage
> * maximum number of allocs on this client
>   The configuration parameters for these are in the client config documentation: https://www.nomadproject.io/docs/configuration/client.html
> 
> If you insist on deleting those directories as soon as the job is complete, you could set `gc_max_allocs` to a very low number. This means that allocation directories (including logs) will not be available for long for any allocation on the client.

Thank you for your reply. I also have a question. We see that nomad's gc includes both server and client, and gc in server includes gc of job, evualation, deployment, etc. I found that although I set it in the server configuration file, the server's gc result was not what I expected. More precisely, here is my configuration about gc in server side:
`
job_gc_threshold="1m"
node_gc_threshold="24h"
job_gc_interval="1m"
eval_gc_threshold="1m"
deployment_gc_threshold="1m"
`
But in fact, I found the result of gc was not what I expected. (After more than 12 hours have passed since jobs I created, they still have not been garbaged collected.) So, would you please briefly explain the job gc strategy in detail? 

BTW, the document of description and explanation about gc is too simple, and I briefly browsed the source code, but I still can't understand the specific strategy of gc in server side.

Looking forward to your reply
