### ISSUE TITLE
any way to expose NOMAD_ADDR variable to other task groups?

### ISSUE THREAD

**Issue by ilackarms** [hashicorp/nomad#6163]
I don't understand how i can independently scale tasks with Nomad,

but simultaneously leverage `NOMAD_ADDR` for service discovery (since it's only exposed within the task group, which can only be scaled as a whole unit)

**Comment by cgbaker** [comment]
as you noted, variables `NOMAD_ADDR_{label}` is only exposed inside the task group for talking to colocated services. for a general service discovery, we support using Consul: 
https://www.nomadproject.io/guides/integrations/consul-integration/index.html
