### ISSUE TITLE
[Feature] Add node.region to built in node variables

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6164]
Nomad 0.9.x has the following node variables

https://www.nomadproject.io/docs/runtime/interpolation.html#node-variables-

| |
|---|
|node.unique.id|
|node.datacenter|
|node.unique.name|
|node.class|
|attr.\<property>|
|meta.\<key>|

Make `node.region` available as a node variable for consistency.

**Comment by cgbaker** [comment]
`node.region` is available for interpolation. Also, the `NOMAD_REGION` environment variable is automatically available to all tasks. This is an oversight in the documentation.

**Comment by spuder** [comment]
Thanks for the fast reply. Let's reopen the issue and turn this into a documentation bug so it can get fixed.
