### ISSUE TITLE
Support randomized `local_bind_port` in `upstreams` stanza

### ISSUE THREAD

**Issue by nickethier** [hashicorp/nomad#6170]
Alternatively users should be able to omit `local_bind_port` in the proxy config and a random port will be selected by the Nomad client. The port should be guaranteed to not conflict with any ports in the group’s network.

**Comment by blake** [comment]
I'm just noting that #7135 seems to be a duplicate of this issue. No action needed.

**Comment by tgross** [comment]
https://github.com/hashicorp/nomad/issues/7135 is more recent but has slightly more context. I'll close this issue as a dupe.
