### ISSUE TITLE
Release notifications at GitHub don't work

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#6173]
Hi,
GitHub can notify about new releases. But it doesn't work for nomad.
It could be an issue on my side, but I got notifications from lots of other projects, so I guess something is disabled on your side.
Did you disable notifications or I should check everything on my side again?

![image](https://user-images.githubusercontent.com/14976219/63427966-0d703b00-c41f-11e9-8210-6b5c045f91e0.png)

**Comment by jippi** [comment]
Nomad doesn't publish releases, only git tags - so that is why

**Comment by cgbaker** [comment]
To expand on this, our release script pushes tags and GitHub creates placeholder releases, which is what you see on the releases page for our repo. Some discussion on this is here:
https://stackoverflow.com/questions/28496319/github-a-tag-but-not-a-release/28500451#28500451

I'll update here with more info later on whether/how we want to address this.

**Comment by cgbaker** [comment]
@pznamensky , we've added GitHub releases to our release guideline. You should have received a notification for v0.9.4, and you should receive notifications going forward for releases.

**Comment by pznamensky** [comment]
Thank you! :+1:
