### ISSUE TITLE
Nomad panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#6223]
### Nomad version
Nomad v0.9.4

### Operating system and Environment details
Ubuntu 18.04

### Issue

Nomad agent restarted with a segfault during an alloc exec I believe.

### Nomad Client logs (if appropriate)

https://gist.github.com/scalp42/12de6e17fd6b45bb148b63cd40247f8a

**Comment by preetapan** [comment]
This was fixed in https://github.com/hashicorp/nomad/pull/6065/commits/488cd7e24eb73bb398fd75979d5206b4a3a3b9a0 but we missed including it in the patch release 0.9.5. I've tracked this internally to make sure we patch it a future patch release in the 0.9 series.

**Comment by scalp42** [comment]
Thank you very much @preetapan for the feedback, much appreciated.


cc @evandam

**Comment by schmichael** [comment]
This was fixed in Nomad v0.9.6, so for not closing this issue!

**Comment by schmichael** [comment]
Sorry for the confusion, this was fixed in v0.10.0 but was *not* backported.
