### ISSUE TITLE
[question] run batch job when template changes

### ISSUE THREAD

**Issue by aclowkey** [hashicorp/nomad#6225]
I want my one-time batch job to run everytime a template is changed.
I'm not sure if this is possible, any idea?

**Comment by tgross** [comment]
Hi @aclowkey! Sorry it took a while to get back to you on this. The component that watches templates need to have a running job to monitor it, but a batch job runs to completion.

What I've done in the past when I wanted something like this is to write a `service` job who's only purpose is to submit a `batch` job to Nomad via the API when it starts. Then you could have the loop forever but get restarted when the template changes. This would cause it to restart the batch job.

```hcl
job "batch-trigger" {

  group "trigger" {
    task "trigger" {
      driver = "docker"

      config {
        image = "<image>"
        command = "/usr/local/bin/trigger.sh"
      }

      template {
        source        = "/path/to/template.tpl"
        destination   = "/path/to/something/local.conf"
        change_mode   = "restart"
      }
}
```

The `trigger.sh` script would need to have access to the Nomad API, so I would recommend using Nomad's [ACL](https://www.nomadproject.io/guides/security/acl.html) feature here to restrict it to submitting jobs.

**Comment by aclowkey** [comment]
OK, I get the workaround idea. Thanks for your reply.
