### ISSUE TITLE
Unable to Curl service DNS name - Connection Refused 

### ISSUE THREAD

**Issue by BenStuart** [hashicorp/nomad#6243]
Windows Business 
Maj  Min   Build    Rev
10     0      18362  0

Nomad Version:
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)

Consul Version:
v.1.5.3

If I may just post this here too, I suspect it may be a nomad issue as much as a consul one.

https://github.com/hashicorp/consul/issues/6426

**Comment by tgross** [comment]
This issue was duplicated to https://github.com/hashicorp/consul/issues/6426, where it was recently closed. Closing this as well.
