### ISSUE TITLE
Docker driver will not take advertised address for consul service registration

### ISSUE THREAD

**Issue by harlequin** [hashicorp/nomad#6244]
### Nomad version
Nomad v0.9.4 (a81aa846a45fb8248551b12616287cb57c418cd6)

### Operating system and Environment details
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

### Issue

I have created a machine in Openstack with a floating IP which is accessible from the outside.

My machine have the ens3 interface with 192.168.2.27 
The floating IP with 10.50.18.9 does not have an interface inside the machine.

Nomad config has as advertise address the 10.50.18.9 which is working very well.
Consul and Nomad will working flawlessly inside our multi cloud environment.

But when I start a Docker Image the Advertise Address is 192.168.2.27:PORT, which is not accessible.

I can see that some services in consul are registered with only " : PORT_NUMBER" but docker will registered with "ENS3_INTERFACE : PORT_NUMBER".

Is there any setting which I can modify the service registration from nomad to consul with the correct "floating" ip or even leave it empty?

**Comment by nickethier** [comment]
Hey @harlequin sorry your having trouble with this. Unfortunately Nomad cannot advertise an address that it can't fingerprint today. It only knows what IP is bound to `ens3` in your case and there is no way to tell it about a vip or floating IP that sends traffic to it.

I'm going to close this for now as this has also been raised in #646. Please check back there for updates or feel free to reopen this issue if you feel it is different than I've described and we can discuss.

Thanks!
