### ISSUE TITLE
[question] Nomad agent with multiple interfaces/IPs

### ISSUE THREAD

**Issue by ccakes** [hashicorp/nomad#6245]
### Nomad version
Nomad v0.9.3 

### Operating system and Environment details
Debian 10

### Issue
I'm looking at using Nomad to manage tasks running on a small fleet of physical servers

I have an existing Nomad setup in multi-DC AWS setup which works great however on the set of physicals, they all have multiple interfaces and I need to be able to register services with the IP of a specific interface. I've dug through the docs, mailing list and GH issues and can't find anyway to do this.

Am I missing something, or if it's not possible is it a feature request that you'd consider?

**Comment by a-vorobiev** [comment]
Suppose that [advertise](https://www.nomadproject.io/docs/configuration/index.html#advertise) setting will help in you case. Mind that it supports [go-sockaddr/template](https://godoc.org/github.com/hashicorp/go-sockaddr/template) format, so you may use for instance `{{ GetInterfaceIP "en0" }}`.

**Comment by ccakes** [comment]
Thanks for the response - sorry I should have been more specific.

Say I have a host with IP addresses like this

```
root@host:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.0.0.1/32 brd 10.0.0.1 scope global lo:1
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
6: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 192.168.166.93/29 brd 192.168.166.95 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.166.94/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.245.2/32 scope global eth0
       valid_lft forever preferred_lft forever
8: eth1@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 192.168.66.77/29 brd 192.168.66.79 scope global eth1
       valid_lft forever preferred_lft forever
    inet 192.168.66.78/32 scope global eth1
       valid_lft forever preferred_lft forever
```

I'd then like to be able to configure a Nomad task with a service like so:

<details>
<summary>Nomad job</summary>

```hcl
group "exec" {
  count = 2

  constraint {
    operator = "distinct_hosts"
    value    = "true"
  }

  task "gobgpd" {
    driver = "exec"

    artifact {
      source = "https://github.com/osrg/gobgp/releases/download/v2.6.0/gobgp_2.6.0_linux_amd64.tar.gz"
    }

    artifact {
      source      = "https://config.src/gobgpd/gobgpd.toml"
      destination = "local/gobgpd.toml"
      mode        = "file"
    }

    config {
      command = "local/gobgpd"

      args = [
        "--config-file", "local/gobgpd.toml",
        "--log-plain",
        "--pprof-disable",
        "--api-hosts", "${NOMAD_ADDR_grpc}",
      ]
    }

    service {
      name = "gobgpd-grpc"
      port = "grpc"

      check {
        type     = "tcp"
        port     = "grpc"
        interval = "30s"
        timeout  = "2s"
      }
    }

    service {
      name = "gobgpd-bgp"
      port = "bgp"

      address = "${NOMAD_ADDR_bgp}"

      check {
        type     = "tcp"
        port     = "bgp"
        interval = "30s"
        timeout  = "2s"
      }
    }

    resources {
      memory = 512

      network {
        port "bgp" {
            static = "179"
            address = "lo:1"
        }
        port "grpc" {}
      }
    }
  }
}
```

</details>

Specifically the `resources {}` section - the ability to specify in some way the IP address to advertise (and thus I could use in the config with` ${NOMAD_ADDR_bgp}`. go-sockaddr syntax would be fine

Any thoughts about supporting this type of use case?

**Comment by tgross** [comment]
Hi @ccakes you'll want to use the [`network_interface`](https://www.nomadproject.io/docs/configuration/client.html#network_interface) configuration for this.

**Comment by ccakes** [comment]
Thanks for the response @tgross. By adding that to the `client` stanza of the agent config wouldn't that impact all services on the host? The use case I'm going for is being able to specify on a per-task basis which interface (or preferably IP) to use

**Comment by tgross** [comment]
Correct, that client configuration would impact all Nomad jobs on the host. Per-task assignment to interfaces or IPs isn't supported currently. But as part of our Connect integration work we did some ground work to use CNI plugins, so there might be a path to doing this in the future. Let's keep this issue open as an enhancement request!

**Comment by adam-weiss-tfs** [comment]
Per-task assignment to interfaces is the one feature that's missing for me to adopt Nomad. I'm definitely looking forward to this feature

**Comment by tgross** [comment]
We shipped [`host_network`](https://www.nomadproject.io/docs/job-specification/network#host-networks) configuration in 0.12.0 that can close this out.
