### ISSUE TITLE
[question] docker config image field doesn't support string interpolation

### ISSUE THREAD

**Issue by destag** [hashicorp/nomad#6247]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
`Nomad v0.9.4 (a81aa846a45fb8248551b12616287cb57c418cd6)`

### Operating system and Environment details
`4.19.66-1-MANJARO x86_64 GNU/Linux`

### Issue
I cannot use string interpolation in parameterized batch job docker config. Is there any workaround or plan to implement this feature?

### Reproduction steps
```bash
nomad job run job.nomad
nomad job dispatch -meta LOADER_VERSION=latest loader
```

### Job file (if appropriate)
```hcl
job "loader" {
  datacenters = ["dc1"]

  type = "batch"

  priority = 50

  parameterized {
    payload       = "forbidden"
    meta_required = [
      "LOADER_VERSION",
    ]
  }

  group "loader" {
    count = 1

    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 0
      mode     = "fail"
    }

    ephemeral_disk {
      size = 300
    }

    task "loader" {
      driver = "docker"

      config {
        image = "destag/loader:${LOADER_VERSION}"
      }

      env {
        MAX_RETRIES = 1
      }

      resources {
        cpu    = 500
        memory = 1024
        network {
          mbits = 10
        }
      }

      logs {
        max_files     = 10
        max_file_size = 10
      }
    }
  }
}

```

### Nomad Server logs (if appropriate)

```
    2019-09-03T15:59:26.557+0200 [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=5dceac94-c1ce-32d7-fbd6-5bf1113cb3c0 task=loader error="2 error(s) occurred:

* failed to parse config: 
* Unknown variable: There is no variable named "LOADER_VERSION"."
```

**Comment by kneufeld** [comment]
I agree, I opened #6366 as a solution to this problem.

**Comment by kneufeld** [comment]
Although in this case you probably want `${meta.LOADER_VERSION}`

**Comment by nickethier** [comment]
@destag You will need to prefix the variable with `NOMAD_META_` when interpolating it. See: https://www.nomadproject.io/docs/runtime/environment.html#meta
