### ISSUE TITLE
Support local_bind_address for Conusl Connect upstreams

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6248]
Support `local_bind_address` for Consul Connect upstreams:

```hcl
             upstreams {
               destination_name = "count-api"
               local_bind_port = 8080
               local_bind_address = "0.0.0.0"
             }
```

Since IPs may vary by host, _I think_ `0.0.0.0` and `127.0.0.1` are the only two options that make sense. We may just want to bind to `0.0.0.0` in network namespaces by default.

**Comment by t0nyhays** [comment]
+1 for this issue

**Comment by djenriquez** [comment]
@schmichael can you explain the need for this feature? This implies that there will be other sources that would be allowed access into the upstream apart from the tasks running in the network namespace. Which would mean needing to open up the `local_bind_port` from the network stanza.

**Comment by schmichael** [comment]
@djenriquez Indeed, allowing binding upstreams to `0.0.0.0` inside the network namespace would allow _explicitly configured_ port forwarding to give external access to the upstream and effectively masquerade as the service.

You could use this to implement an "ingress" style jobs which use Envoy to proxy untrusted external traffic to Connect-enabled services. For example if there was an `api` service using Connect, an `ingress` service could set a `local_bind_address = "0.0.0.0"; local_bind_port = 1234` and port forward `1234` from the host interface to the upstream listener inside Envoy's network namespace.

The `ingress` job would be run as a system job on nodes that an ALB or similar load balancer points to, thus allowing external traffic to proxy from non-Connect load balancers, through the `ingress` service, to the Connect-enabled `api` service.

I'm not even sure `local_bind_address` is sufficient to make that use case work. Even if it is _possible,_ it doesn't seem optimal. There's got to be a better way to do ingress right? :sweat_smile: 

It's a topic of active discussion internally but any feedback is welcome (either on this wacky "ingress" use case _or other `local_bind_address` use cases_).

**Comment by fredrikhgrelland** [comment]
> There's got to be a better way to do ingress right?
https://www.consul.io/docs/agent/config-entries/ingress-gateway
With Consul 1.8 both ingress end termination is possible. Are you planning on implementing this in nomad directly? It would be a killer feature. Currently trying to figure out how to enable this feature in 11.2
