### ISSUE TITLE
Pass in task number as environment variable into tasks

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#625]
Some software like kafka or zookeeper requires that each instance has an id configured.

For example, in kafka, the first broker would have an id of 1, the second an id of 2 and so on.

It would reduce a lot of work if nomad can pass this id as an environment variable such as `NOMAD_COUNT_ID` into the task. For example, if the job spec has a count of 3 for a certain task, it should pass `1` as`NOMAD_COUNT_ID` to the first task, `2` to the second one and `3` to the last one.

This prevents tasks having to use some outside source of truth to coordinate their ids.

**Comment by Supernomad** [comment]
I definitely need to plus one this, as I just spent the last hour or so trying to figure out how to pass in the count to a task definition.

My particular use case:
I have an elasticsearch container which mounts a glusterfs volume to store its data, and this volume will be persisted so that the same data can be used across container restarts. The volumes name is associated with the particular container designated by the count identifier, i.e. elasticlogging<task number>.

**Comment by diptanu** [comment]
Marking this as a core feature since this would involve changes on the scheduler side to assign a number on the alloc that it creates in response to evals.

**Comment by diptanu** [comment]
@Supernomad There is another way to do this, use consul locks. But locks are never a good idea in big clusters.

@slackpad @armon Do you guys have any thoughts if this could be solved by Consul?

**Comment by Supernomad** [comment]
@diptanu I have been looking into doing something like this, and for now would be a solid way forward. However I agree that once the cluster size grows, the locks are going to become a major bottle neck.

Thank you for the quick response. Nomad is shaping up amazingly well. By all means let me know if you need any testing done.

**Comment by carlsverre** [comment]
:+1: This feature or something similar would be extremely helpful.  My use case is that I have a group of tasks defined in a job, and I want each task to claim 1/Nth of a space of work.  Fairly classical distributed computing problem.  Right now I am doing it by copying the task definition N times and modifying the args to specify the task number manually.  An automated way would be great.

**Comment by dadgar** [comment]
#869 will fix this as it will pass in the alloc name which includes a count. Looks like:
` "NOMAD_ALLOC_NAME=example.cache[1]"`
