### ISSUE TITLE
[question] Does device plugin provide the abailty to do cleanup?

### ISSUE THREAD

**Issue by Xuanwo** [hashicorp/nomad#6258]
## Nomad version
```
Nomad v0.9.5
```

---

## Question

Currently, device plugin has following actions:

```
// DevicePlugin is the API exposed by device plugins
service DevicePlugin {
  // Fingerprint allows the device plugin to return a set of   
  // detected devices and provide a mechanism to update the state of
  // the device.
  rpc Fingerprint(FingerprintRequest) returns (stream FingerprintResponse) {}

  // Reserve is called by the client before starting an allocation
  // that requires access to the plugin’s devices. The plugin can use
  // this to run any setup steps and provides the mounting details to 
  // the Nomad client
  rpc Reserve(ReserveRequest) returns (ReserveResponse) {}

  // Stats returns a stream of device statistics.
  rpc Stats(StatsRequest) returns (stream StatsResponse) {}
}
```

And I could do init job at `Reserve`, but how can I do some cleanup job?

## Description of Requirement

I tried to do CI with nomad, and need to create loop device for test (`mknod` && `losetup`) and destroy them after test finished.

May we could add a `Cleanup` here? So we can have a `loop device` manager which create loop device for job in `Reserve` and destory them after job finished in `Cleanup`?

**Comment by notnoop** [comment]
We don't support this pattern in the interface as you point you.  I suspect you can have your main  pass a signal on receiving termination signals to the constructor, or have class install a listener.  Will double check the logic in our plugin wrapper code and report back.

**Comment by tgross** [comment]
Looks like this question has been answered.
