### ISSUE TITLE
distinct_hosts documentation is a bit confusing

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#626]
![](https://cldup.com/uKRbLxWh4s.png)

I'm having a difficult time understanding how distinct_hosts will work when placed within task groups and at the job level. I would appreciate if the docs can elaborate a bit further.

**Comment by dadgar** [comment]
Yeah, spent quite a bit of time trying to come up with the best way to document that one. It honestly might just need a diagram as it is hard to explain.

**Comment by let4be** [comment]
Can't understand it either, clarification would be much welcome

**Comment by dadgar** [comment]
We can reopen if the new documentation still is not clear
