### ISSUE TITLE
Cpu hard limits do not work ( Nomad v0.9.5  )

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#6261]
### Nomad version
Output from `nomad version`
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)

### Operating system and Environment details
Codename:	xenial
Docker:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)

### Issue
After upgrade from 0.8 to 0.9.5 cpu hard limits do not work 

### Reproduction steps
Config:
```
name = "localhost"
bind_addr = "::"
datacenter = "dc1"
data_dir = "/var/lib/nomad"
disable_update_check = "true"
log_level = "TRACE"
options {
    "docker.auth.config" = "/root/.docker/config.json"
}
client {
  enabled = "true"

  node_class = "testnomad"
  network_interface = "eth0"
  servers = ["localhost"]
}
telemetry {
  publish_allocation_metrics = "true"
}
server {
  enabled = "true"
}
```

### Job file (if appropriate)

```
# job name
job "job1" {
  datacenters = ["dc1"]
  type = "service"

  group "group1" {
    count = 1
    task "task1" {
      kill_signal = "SIGTERM"
      driver = "docker"
      config {
        cpu_hard_limit = "true"
        image        = "registry/init:md5"
      }
      resources {
        memory = 256
        cpu = 1000
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

In logs, after "nomad run":
> [DEBUG] client.driver_mgr.docker: configured resources: driver=docker task_name=task1 memory=268435456 cpu_shares=1000 cpu_quota=0 cpu_period=0

Metrics:

> nomad_client_allocs_cpu_throttled_periods{...} 0
> nomad_client_allocs_cpu_throttled_time{...} 0
> nomad_client_allocs_cpu_total_ticks{...} 2937.804931640625

**Comment by hvindin** [comment]
We have noticed the same behavior with nomad 0.9.5+ent on Redhat 7.6 Hosts with both docker-ee 18.09 and docker-ee 19.03

It's extremely visible if a single service is being hit with a lot of load it easily exceeds its CPU allocation.

**Comment by pznamensky** [comment]
The same behavior with CentOS 7.7, nomad 0.9.4 and docker ce 18.03.

**Comment by cwalsh** [comment]
Setting cpu_cfs_period=100000 alongside cpu_hard_limits=true fixed this for me. Without this change I saw similar issues to TheSpbra1n.

**Comment by elliebirbeck** [comment]
also having this problem on nomad 0.10.0 with docker v18.03.0-ce on ubuntu 16.04

**Comment by nickethier** [comment]
Hey folks thanks for reporting this! In 0.9 we allowed users to specify the cpu_cfs_period, but it looks like I forgot to set the default for that field to what the value was pre 0.9 (100000). I opened a PR to fix this. Setting the cpu_cfs_period manually will workaround this issue. Apologies for the oversight.
