### ISSUE TITLE
Nomad 0.9.5: -detach does not match documentation

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#6305]
### Nomad version
Nomad v0.9.5

### Operating system and Environment details
OSX, Nomad cluster on Linux

### Issue
Documentation at https://www.nomadproject.io/docs/commands/job/run.html says:

```
-detach: Return immediately instead of monitoring. A new evaluation ID will be output, which can be used to examine the evaluation using the eval status command
```

```
Schedule the job contained in job1.nomad and return immediately:

$ nomad job run -detach job1.nomad
4947e728
```

However, I get the following output:

```
$ nomad job run -detach file.nomad.hcl
Job registration successful
Evaluation ID: eb1cdfcd-7509-69eb-4fe7-9d2637c5fbc0
```

I expected:

```
$ nomad job run -detach file.nomad.hcl
eb1cdfcd-7509-69eb-4fe7-9d2637c5fbc0
```

This means that I will have to parse stdout with a regex (or worse), instead of just taking the output of the command and script with that.

**Comment by preetapan** [comment]
We'll fix the docs, in general the CLI is meant to be human friendly rather than machine friendly. Our [job register](https://www.nomadproject.io/api/jobs.html#sample-response-10) end point returns a parseable response with the eval ID.

**Comment by kaspergrubbe** [comment]
@preetapan Couldn't `-detach` or something else be a way to get a machine readable answer back from Nomad? 

I understand that the CLI tool needs to be human friendly, but since the Nomad API is marked as unstable (and not very well documented) you are stuck between a rock and a hard place trying to integrate with Nomad programmatically, if you choose the API-path for an example https://www.nomadproject.io/api/jobs.html is mostly just sample responses, where you have to use your detective skills to understand and parse the JSON.

**Comment by notnoop** [comment]
Closing this one and also addressing the API change shortly.  The API is meant to be pretty stable and we take breaking changes very seriously (generally avoid it and document it in CHANGELOG and upgrade guides when we do).  The warning wording in https://www.nomadproject.io/api-docs/index#version-prefix is just not accurate and we'll update it.
