### ISSUE TITLE
5000+ batch jobs with Docker driver

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#6306]
Hi guys,

is recommended to use Nomad to run 5000+ allocated jobs per time? running/pending jobs is normal.

Is a lot of forecast jobs using massive CPU's inside a Docker container, the Nomad agents is HPC's with a lot of CPU (more then 64).

The jobs is, up Docker, run code, send output to Kafka and down. The running time per job is 4-6 minutes.

Have any benchmark?

Now I'm using DC/OS with Mesos and Metronome but have a lot of bugs, is not stable and infra is very complex.

In installation what is a warning points?

Thx a lot.

**Comment by tantra35** [comment]
We use nomad in such case. Sometimes we have 10k pending batch jobs. At this time nomad server eat many memory and CPU (we handle this load on m5.large aws instances), but work perfectly

**Comment by kcwong-verseon** [comment]
Let's not mix up "jobs" and "tasks", as they are loaded terms in Nomad. It is important to remember that Nomad servers and agents keep track of allocations, and each allocation object contains [a pointer to the entire job spec](https://github.com/hashicorp/nomad/blob/master/api/allocations.go#L356). So, if the a job contains a large number of distinct task-groups (not by way of a large `count`), you can expect significant memory bloat, especially at the servers. I was advised to chop up a large job into smaller ones in order to alleviate the memory pressure, and that worked very well.

**Comment by jonatasfreitasv** [comment]
@tantra35 thx for report.

@kcwong-verseon this is a big question, about jobs and tasks.

Is recommended to create a one job with a lot of tasks or a lot of jobs?

**Comment by kcwong-verseon** [comment]
> Is recommended to create a one job with a lot of tasks or a lot of jobs with one task?

You have to strike a balance, but one big job with lots of task-groups that ends up with a lot of allocations is generally not a good thing. Too many jobs (like the other extreme of 1 task/1 task-group/1 job) also get burdensome as you can imagine what `nomad job status` would look like.

**Comment by jonatasfreitasv** [comment]
@kcwong-verseon 

I have event-driven / distributed system, its hard to control this and group jobs.

Every distributed event/message is a one task / Docker container running ml codes.

**Comment by kcwong-verseon** [comment]
@jonatasfreitasv 

* My primary thesis is pointing out the memory footprint of the `Allocation struct` in Nomad, that is references the corresponding `Job struct`. Depending on how well Nomad manages (and I have not review the code well enough to say) to reuse the same `Job struct` for all its allocations, large job spec can lead to memory consumption problems.

**Comment by jonatasfreitasv** [comment]
@kcwong-verseon 

I'm test two scenarios:
- 5000 tasks in 1 job, system crash.
- 5000 jobs, all system ok.

I'm go to production with this configuration.

**Comment by amfern** [comment]
We have similar use case, we ended up using parametrized batch job, but the memory footprint wasn't much lower then having same amount of batch jobs.
Having a lot of tasks in single job doesn't work at all, it just eats all memory and crashes nomad

**Comment by jonatasfreitasv** [comment]
@amfern Thx a lot for you report.

But, what is parametrized batch job?

**Comment by amfern** [comment]
@jonatasfreitasv This explains parametrized batch job pretty well https://www.hashicorp.com/blog/replacing-queues-with-nomad-dispatch

**Comment by jonatasfreitasv** [comment]
Thx!

@amfern Some minutes after run a lot of jobs (more then 20k), my Nomad Agents enter in stuck state, when I opened top/htop in machines I view dockerd consume all cores and disk io, 
did you go through it?

**Comment by jonatasfreitasv** [comment]
About last message, this bug is fixed in version 0.9.6.
