### ISSUE TITLE
All groups getting restarted if constraint is present in job 

### ISSUE THREAD

**Issue by deepeshj** [hashicorp/nomad#6308]
Hi Guys,
We have 1000+ groups with raw_exec task within a JOB.  We are limiting 100 process per system. 

> job "channel" {
>   datacenters=["dc1"]
>   type = "service"
>   constraint {
>   	distinct_property = "${attr.unique.hostname}"
>   	value     = "100"
>   }
>   group "channel-1" {
>     count = 1
>     task "save" {
>       driver = "raw_exec"
>       config {
>         command = "/usr/bin/ffmpeg"
>         args = [...]
>       }
>     }
>   }
>   group "channel-2" {
>     count = 1
>     task "save" {
>       driver = "raw_exec"
>       config {
>         command = "/usr/bin/ffmpeg"
>         args = [...]
>       }
>     }
>   }
> 

After the allocation if we try to update a single group we get (1 create/destroy update) for 1 and  (1 in-place update)  for all group

> +/- Task Group: "channel-1" (1 create/destroy update)
>   +/- Task: "save" (forces create/destroy update)
>     +/- Config {
> ...
> Task Group: "channel-2" (1 in-place update)
>       Task: "stream-save"
> ...

But if we try to update a single group after failed process and group is moved to different node, we get (1 create/destroy update) for majority groups. 

> +/- Task Group: "channel-1" (1 create/destroy update)
>   +/- Task: "stream-save" (forces create/destroy update)
>     +/- Config {
> ...
>  Task Group: "channel-2" (1 create/destroy update)
>       Task: "stream-save"

Expected Results:
Since we have modified only 1 group only that process has to be scheduled and allocated. It should not affect the other group in the job.

**Comment by tgross** [comment]
Hello @deepeshj and thanks for reporting this issue!

Just for clarification, the example job you've provided here only has 2 task groups but the real job has 100 task groups? And when you update a single task group, many of the task groups are being updated?

A couple things I've noticed about the job spec you've provided:
- There's a constraint in use here but I don't think it will have the effect you intend. That constraint will make sure no more than 100 of a particular task group will land on a given host. But you only have a `count` of 1 for each task group, so this constraint has no effect.
- This is a service job but it's running ffmpeg. I'm wondering if a `batch` job might be better suited to that kind of workload?

Also, can you provide the version of Nomad you're using and any logs you feel comfortable sharing?
