### ISSUE TITLE
Request for better examples of production environ (I know there are others open)

### ISSUE THREAD

**Issue by erich-comsIO** [hashicorp/nomad#631]
I hope you guys will take this as the constructive criticism it's meant to be - I am a very enthusiastic supporter but feel I'm struggling more than I should have to with the learning curve.

To be blunt - the getting started guide really isn't. It appears to be written as an IQ test by someone with something of a fixation on economy of logical expression. In short, I spent hours yesterday chasing my tail over something that finally became obvious when I found a code snippit buried in an unrelated article pointing out the simple error I was making; just the simplest walkthrough configuring a working cluster would have made it all abundantly clear.

Basically, showing people how to start up a local dev environment for software that is explicitly designed to be distributed, while offering no practical examples of a real production system, is really pretty unhelpful and borders on infuriating as a matter of practical learning experience. I'm a really autodidactic person who spends almost all of my time absorbing new ideas, but most of us can not invest so many hours learning through osmosis.

My advice, based on a few decades of experience, is to engage a collaborator or employee who is not as intimately engaged with the internals, so to say, to focus on documentation. This is a classic problem - engineers documenting their own products almost always fail. It's practically axiomatic. This is especially true of small teams made up of exceptionally bright people.

Anyway - I'm back to another exciting day of learning the Hashicorp way - and it's really exciting stuff - terrific work guys - the tools are really inspiring - thank you, and I promise to contribute effort towards practical examples once I get a solid grasp myself!

Oh, and Merry Christmas Everyone!

**Comment by diptanu** [comment]
@erich-comsIO Thanks for your feedback. We are working on an example of Nomad running across multiple VMs in a clustered environment with some jobs running on it. It should land sometime soon.

**Comment by erich-comsIO** [comment]
Great news! Just more direct pointers to things like: https://github.com/hashicorp/atlas-examples/blob/master/nomad-cluster/aws-beginner-nomad-cluster/terraform/instances.tf <https://github.com/hashicorp/atlas-examples/blob/master/nomad-cluster/aws-beginner-nomad-cluster/terraform/instances.tf> would be killer. That is very clarifying. Should have spent more time looking for such yesterday and just got ahead of myself.

Thanks much for the reply.

**Comment by marenzo** [comment]
+1

**Comment by throrin19** [comment]
+1 for examples in standard linux production cloud and for azure. Not only AWS
