### ISSUE TITLE
bug - service not not added to new nodes

### ISSUE THREAD

**Issue by OferE** [hashicorp/nomad#6312]
### Nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Ubuntu 18
4.15.0-1041-aws #43-Ubuntu SMP Thu Jun 6 13:39:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Issue
We are starting a service with count = 10 with 3 nodes. We start the service after the nodes are up. Few hours later we add another node (like autoscale) but nomad is not scheduling this service on this new node.

### Reproduction steps
Just do what i wrote.

### Job file (if appropriate)
```
job "glances" {
  datacenters = ["dc1"]
  type = "service"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "glances" {
    count=11
    constraint {
      attribute = "${node.class}"
      value     = "com.driversfarm"
    }
    constraint {
       operator  = "distinct_hosts"
       value     = "true"
    }
 
    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    task "glances" {
      driver = "raw_exec"
      kill_timeout = "120s"
      config {
         command = "/opt/nomad_docker_run.sh"
         args = ["--network=host",
                 "-e TERM=xterm",
                 "--pid host",
                 "-v /tmp/prems/:/tmp/prems/",
                 "-v /var/run/docker.sock:/var/run/docker.sock:ro",
                 <our-own-aws-id>.amazonaws.com/glances:initial",
                 "glances -w"]
      }

      resources {
        network {
           # dummy mbits to avoid failure check
           mbits = 10
           port glances {static = 61208}
        }
      }

      service {
          name = "glances"
          port = "glances"
          tags = ["${NOMAD_ALLOC_INDEX}"]
          check {
              name     = "alive"
              type     = "tcp"
              interval = "20s"
              timeout  = "2s"
          }
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
nothing interesting there,

### Nomad Server logs (if appropriate)
Nothing interesting there

**Comment by tgross** [comment]
@OferE this is working as expected. Nomad won't re-schedule the workload across the new nodes unless you ask for a reschedule. Alternately, if you want to make sure you have an instance of a job running on every node, you might consider using the `system` scheduler rather than `service`.
