### ISSUE TITLE
0.10.0-beta1: UI Logs button seem unclickable

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#6320]
### Nomad version
0.10.0-beta1 (Server + Clients)

### Operating system and Environment details
Amazon Linux 2

### Issue
Nomad UI buttons in the Logs for allocations no longer seem clickable. I was looking for logs for a test job I was running and found the logs UI non-operational. I'm unable to click to `stderr` where my logs are, nor do the `Head`, `Tail`, `(Pause Button)` seem to do anything like they did in 0.9.3.

### Reproduction steps
Navigate in the UI to the logs for an allocation, try to get logs to appear.

**Comment by notnoop** [comment]
Thanks @djenriquez for catching this!  I took a stab at a fix but will consul our ui engineers for guidance.

**Comment by Gurpartap** [comment]
It's the same for Stop and Restart buttons on `http://localhost:4646/ui/allocations/{id}`. Refreshing the page doesn't help.
