### ISSUE TITLE
When upgrading from raft protocol 2 to 3, last server's ID remains in the old format

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6344]
I did a manual upgrade test moving a 3 server cluster from raft protocol 2 to 3, with the scripts in https://github.com/hashicorp/nomad/tree/master/e2e/upgrades#upgrade-tests. Nomad 0.9.5 defaults to raft protocol 2, and Nomad 0.10.0 defaults to raft protocol 3. 

The upgrades were done by stopping one server at a time, updating the binary and restarting the stopped server. At the end of the upgrade, the last server to upgrade (server3) was not showing a UUID as its ID. 

This could be an interaction between autopilot and our leadership transition handling code, worth investigating. It causes UX weirdness in the CLI but no functionality difference, I did confirm that server3 was running raft protocol 3. 

output of `nomad operator raft list-peers`
```
Node            ID                                    Address              State     Voter  RaftProtocol
server3.global  192.168.29.185:6647                   192.168.29.185:6647  follower  true   3
server1.global  0dae4198-8a86-862c-2fd6-c20d5ef6f993  192.168.29.185:4647  leader    true   3
server2.global  84bd5dd6-4991-9e7a-4d94-91b1fcf0926c  192.168.29.185:5647  follower  true   3
```

**Comment by langmartin** [comment]
There are a couple of intertwined issues:

1. the raft version is stored in a tag on the serf update. When a server is restarted, the tags update but only a `memberJoin` message is sent to the old raft leader. This message uses the old node id, so it's filtered out as a duplicate and the raft version change isn't visible to the cluster leader until the serf `pushPull` timeout kicks in (1 minute)

2. when the server shows in `list-peers`, the reported raft version is taken directly from it's serf tags. It's not until the server id is updated that the peer has actually been added to the raft membership.

3. If all the followers are upgraded but not yet re-added to the raft configuration and the leader is upgraded, the cluster will lose leadership and can't be recovered without manual intervention.

The protocol upgrade seems to require enough care that we'll hold off changing the default until we can improve the reliability of the upgrade.
