### ISSUE TITLE
linux/exec: binary needs /usr/share/zoneinfo

### ISSUE THREAD

**Issue by kennethzfeng** [hashicorp/nomad#636]
Hi,

I am running both the nomad server and client (v0.2.3) on a CentOS 6 box.  Also, I am using the exec driver to run a go binary that requires timezone data.  For CentOS 6, that's in ```/usr/share/zoneinfo```.  However, the chroot environment doesn't provide that.  So, I added an extra line to ```chrootEnv``` (https://github.com/kennethzfeng/nomad/commit/b03d94da1e668d29aecafc58642c4c9e0b3b94c1)

```go
time.LoadLocation("America/New_York")
```

```
I1228 13:38:06.962698 main.go:52] unknown time zone America/New_York
```

Although it fixed the issue on my machine, I am not sure if this is the best way to fix it generically.  Any ideas?

**Comment by diptanu** [comment]
We can add that path to the chrootenv if it's something which is standard across most distros - Debian, RHEL and CoreOS.

**Comment by diptanu** [comment]
Oh I see, you added /usr/share to the chroot env. It might be ok, send us the PR?

**Comment by kennethzfeng** [comment]
@diptanu, See #637

**Comment by diptanu** [comment]
@kennethzfeng Merged.
