### ISSUE TITLE
Support running as a Windows Service

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#6372]
Currently, Nomad supports running on Windows, but does not natively support running as a Windows Service, requiring tools like NSSM to be executable. Adding native support is valuable for many Nomad users and also to facilitate integration with our E2E suite.

The current blockers for native support are:
- [x] Support file logging in Nomad
- [x] Support some signal handling machinery (@angrycub to add more info)

**Comment by angrycub** [comment]
I have current work on Service Control Manager wiring in https://github.com/hashicorp/nomad/pull/6220.  This is a lift-and-shift from Consul's implementation.

**Comment by lmayorga1980** [comment]
@endocrimes can you share your nomad client service hcl file? I am having some issues on windows.


```
PS C:\nomad> Get-eventlog application -after (get-date).addhours(-1)

   Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
     463 Oct 01 16:12  Warning     nssm                   2147484682 Service Nomad ran for less than 1500 millisecon...
     462 Oct 01 16:12  Information nssm                   1073742838 Service Nomad action for exit code 1 is Restart...
     461 Oct 01 16:12  Information nssm                   1073742851 Killing PID 2692 in process tree of PID 2692 be...
     460 Oct 01 16:12  Information nssm                   1073742847 Killing process tree of process 2692 for servic...
     459 Oct 01 16:12  Information nssm                   1073742837 Program C:\nomad\nomad.exe for service Nomad ex...
     458 Oct 01 16:12  Information nssm                   1073742832 Started C:\nomad\nomad.exe agent "-config C:\no...
     457 Oct 01 16:11  Warning     nssm                   2147484682 Service Nomad ran for less than 1500 millisecon...
     456 Oct 01 16:11  Information nssm                   1073742838 Service Nomad action for exit code 1 is Restart...
     455 Oct 01 16:11  Information nssm                   1073742851 Killing PID 3484 in process tree of PID 3484 be...
     454 Oct 01 16:11  Information nssm                   1073742847 Killing process tree of process 3484 for servic...
     453 Oct 01 16:11  Information nssm                   1073742837 Program C:\nomad\nomad.exe for service Nomad ex...
     452 Oct 01 16:11  Information nssm                   1073742832 Started C:\nomad\nomad.exe agent "-config C:\no...
     451 Oct 01 16:11  Warning     nssm                   2147484682 Service Nomad ran for less than 1500 millisecon...
     450 Oct 01 16:11  Information nssm                   1073742838 Service Nomad action for exit code 1 is Restart...
     449 Oct 01 16:11  Information nssm                   1073742851 Killing PID 3932 in process tree of PID 3932 be...
     448 Oct 01 16:11  Information nssm                   1073742847 Killing process tree of process 3932 for servic...
     447 Oct 01 16:11  Information nssm                   1073742837 Program C:\nomad\nomad.exe for service Nomad ex...
```

**windows.hcl**
```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "C:\\nomad\\data_dir"

# Give the agent a unique name. Defaults to hostname
name = "{{ansible_hostname}}"

# Enable the client
client {
    enabled = true

    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
    servers = ["{{nomad_server}}:4647"]

  options = {
    "driver.raw_exec.enable" = "1"
  }
}

# Modify our port to avoid a collision with server1
ports {
    http = 5656
}
```

**Comment by endocrimes** [comment]
@lmayorga1980 I don't personally have an NSSM setup to hand, @angrycub might though

**Comment by lmayorga1980** [comment]
Having a standard config for windows under the docs would be nice.

**Comment by angrycub** [comment]
As we bring native service integration to Nomad, we will definitely improve the documentation around Windows and Windows configurations.

Because Nomad logs to stdout and stderr, you would need to redirect those in order to inspect the logging.  This is another improvement planned as part of this work effort.  However, in the meantime, you can add redirection to your NSSM configuration via the GUI or with the following commands:

```
nssm set Nomad AppStdout C:\Nomad\logs\nomad.log
nssm set Nomad AppStderr C:\Nomad\logs\nomad.log
```
<img width="379" alt="Screen Shot 2019-10-01 at 3 48 22 PM" src="https://user-images.githubusercontent.com/464492/65995183-f6335d00-e462-11e9-9488-2892a55ba928.png">

Set the paths and service name to appropriate values for your environment.  Once set, restart your nomad service.  You should then be able to inspect the logs for any specific errors.

**Comment by lmayorga1980** [comment]
I will definitely try that approach. Seems like the agent works from cmd.exe manually but the service process is killed for some reason.

**Comment by lmayorga1980** [comment]
@angrycub ,

Thank you 👍 , sharing my sample configuration for nomad on windows.

**windows.hcl**
```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "C:\\nomad\\data_dir"

# Give the agent a unique name. Defaults to hostname
name = "{{ansible_hostname}}"

# Enable the client
client {
    enabled = true

    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
    servers = ["{{nomad_server}}:4647"]

  options = {
    "driver.raw_exec.enable" = "1"
  }
}

# Modify our port to avoid a collision with server1
ports {
    http = 5656
}

```

**ansible definition**
```
    - name: Install the Nomad service with a list of parameters
      win_nssm:
        name: Nomad
        display_name: Hashicorp Nomad
        application: C:\nomad\nomad.exe
        stderr_file: c:\nomad\logs\stderr.log
        stdout_file: c:\nomad\logs\stdout.log
        arguments:
          - agent
          - -config=C:\nomad\config\windows.hcl
```

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/6220

**Comment by lmayorga1980** [comment]
@endocrimes 👍

**Comment by basickarl** [comment]
Seriously guys: https://nomadproject.io/guides/install/windows-service/ That should be updated. I tried doing what it said there and it just did not work. Will be implementing my own NSSM wrapper for Nomad.

**Comment by tgross** [comment]
Hi @basickarl that's the approach we use for our Windows e2e test suite, so if you're running into problems I'd suggest opening a new GitHub issue explaining the problems you're having in more detail.

**Comment by angrycub** [comment]
It's also important to note that the Service Control Manager integration was added in 0.10.2. 

> agent: Added support for running under Windows Service Manager [GH-6220]

Versions before that will need to use NSSM to wrap the service.
