### ISSUE TITLE
Integers not being parsed when interpolated in job spec

### ISSUE THREAD

**Issue by alexboboc** [hashicorp/nomad#6374]
# Nomad version
`Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)`

### Operating system and Environment details
Ubuntu 18.04.

### Issue
I tried to set a `NOMAD_META_TASK_PRIORITY` to use in a parametrized job. When reading said variable, I get the following:

```
error parsing 'job': 1 error(s) decoding: * cannot parse 'Priority' as int: strconv.ParseInt: parsing "${NOMAD_META_TASK_PRIORITY}": invalid syntax
``` 

According to #1063., this should have been fixed a couple of years ago.

### Reproduction steps

Set a simple parametrized job, and make sure it contains the following fields:

```
job "my-job" {
    parametrized {
        meta_required = ["TASK_PRIORITY"]
    }
    priority = "${NOMAD_META_TASK_PRIORITY}"
    ...
}
```

This will trigger the above error.

**Comment by nickethier** [comment]
`priority` is currently one of the few fields that can't be interpolated. I created #6381 to track a different approach to this problem and am closing this issue in favor of it. Subscribe to it for updates.

Thanks for reporting this!
