### ISSUE TITLE
Nomad 0.10.0-beta missing NOMAD_PORT with task group network{}

### ISSUE THREAD

**Issue by dmwilcox** [hashicorp/nomad#6375]
### Nomad version
Nomad v0.10.0-beta1 (7df4da75f7bfcf05fb63f57b49fc7e3facf3aa7b)

### Operating system and Environment details
ubuntu-18.04

### Issue
Cannot get task group dynamic network ports by NOMAD_PORT_$label variable.

### Reproduction steps
```
    network {
      mode = "bridge"
      port "monitoring" {
        to = 19000
      }
      port "srv" {}
    }
```
and in a task attempt to interpolate using a port label (static or dynamic):
```
      env {
        "SERVICE_PORT" = "${NOMAD_PORT_srv}"
        "MON_PORT" = "${NOMAD_PORT_monitoring}"
      }
```
and add 'env' or similar to your docker entrypoint file to dump the available environment.  All of the usual networking environment variables are missing -- and the requested ones in the job template fail to interpolate.

**Comment by schmichael** [comment]
The complicating factor here is that group networks introduced a new concept: Ports with an internal and external component. This is similar to driver networks when using Docker but still distinct in that I could see both the internal (`to`) and external (`static` or dynamically allocated) ports being useful:

1. Internal is useful to avoid repeating yourself when defining the port your app should listen to.
2. External is useful for advertising a service when Consul is not in use and/or not applicable.

I'd like to ship _something_ in 0.10.0, but I doubt it will be comprehensive.

I think an initial implementation could be exposing group network ports to all tasks as:
```
NOMAD_PORT_<label> = <"To" if defined, otherwise external port>
```

This ignores internal/external IP addressing entirely which is unfortunately more complicated to handle.

In the future I think exposing all of the IP and port information _for interpolation_ only is the right choice. This would allow operators to choose which fields (internal vs external) to expose via `env` or `template` stanzas without polluting our default environment further. We'd keep existing env vars for backward compat, but the list is getting so large we'd like to only add new default env vars rarely.

I think #6272 is only tangentially related, but I wanted to at least crosslink the issues.

**Comment by schmichael** [comment]
I forgot `NOMAD_HOST_PORT_...` in my previous comment, so our current plan is to implement:

```
NOMAD_PORT_<label> = <"To" if defined, otherwise external port>
NOMAD_HOST_PORT_<label> = <external/host port>
```

This should make at least the port variables work the same for group networks as existing task networks.

While we won't have time to implement it for 0.10.0, I'm curious if you could use the external/host or internal/namespace IP as well?

As we move away from stuffing everything in environment variables, it gives us a lot more flexibility to hierarchically organize variables for interpolation like the existing `node` variables: https://www.nomadproject.io/docs/runtime/interpolation.html#node-variables-
