### ISSUE TITLE
Feature request: Support destination_type="prepared_query" for Connect Upstreams

### ISSUE THREAD

**Issue by dmwilcox** [hashicorp/nomad#6376]
It appears that Nomad consul definitions for specifying upstreams is limited to simple service names.  To enable fail over, version routing and other uses -- it'd be great to add support for creating prepared queries as upstreams.

If there isn't bandwidth to work on this soon I'm happy to take an initial pass at adding it.  Thanks!

**Comment by dmwilcox** [comment]
Simple struct with no concept of upstream types shown here:
https://github.com/hashicorp/nomad/blob/9a0f8a44b6331d327ac1dc68cb463dcf98368dfc/api/services.go#L174

**Comment by lgfa29** [comment]
I bumped into this issue while looking for something else, but `destination_type` support has been implemented in https://github.com/hashicorp/nomad/pull/18430 so I think we can close this issue.

Thanks for the report @dmwilcox!
