### ISSUE TITLE
HTTP checks not working for java driver

### ISSUE THREAD

**Issue by tk512** [hashicorp/nomad#6378]
### Nomad version
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)
(Also running Consul v1.6.1)

### Operating system and Environment details
Ubuntu Linux LTS 18.04, 64-bit.  Running on 1x Consul, 1x Nomad server and 3x Consul clients and 3x Nomad clients across 4 VM's in total.

### Issue
I've been testing with a fat jar file that runs an HTTP server, and deploying this using the java driver on Nomad.  It works fine, and is deployed across all Nomad workers.  However I cannot get http checks to work.

I have confirmed that script check works, and that everything relating to this service actually works.  I am also able to use the http check with non-java drivers, so I suspect something is wrong with the java driver in Nomad.

### Reproduction steps
Run the job file below with any kind of fat Jar file that listens on a port provided by the property "server.port".   If the API endpoint /heartbeat returns 200 OK, then this check should work.

I run Consul along with Nomad, so Consul is actually doing the check here. It is not doing any HTTP requests at all. I have confirmed that via tcpdump.

### Job file (if appropriate)
```job "my-service" {
  region      = "global"
  datacenters = ["my-dc"]
  type        = "service"

  update {
    max_parallel     = 1
    min_healthy_time = "30s"
    healthy_deadline = "5m"
    auto_revert      = false
    canary           = 3
    health_check     = "checks"
  }

  group "app" {
    count = 3

    task "my-service" {
      driver = "java"

      config {
        jar_path    = "local/my-service-fat.jar"
        jvm_options = ["-Dserver.port=${NOMAD_PORT_http}"]
      }

      artifact {
        source = "https://my-url/my-service-fat.jar"
      }

      service {
        port = "http"


        # This triggers no http requests at all in due to using the java driver. The same check works if I use the docker driver and others.
        check {
          name     = "heartbeat"
          type     = "http"
          path     = "/heartbeat"
          method   = "GET"
          interval = "15s"
          timeout  = "3s"
        }

#        Disabled:  This is the only solution that works currently:
#        check {
#          type     = "script"
#          name     = "check test"
#          command  = "/usr/local/bin/check_test"
#          args     = ["some", "vars"]
#          interval = "30s"
#          timeout  = "5s"
        }
      }

      env {}

      resources {
        cpu    = 500 # MHz
        memory = 512 # MB

        network {
          mbits = 100
          port  "http"{}
        }
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
Everything on nomad looks fine, except that the check eventually ends up as marking the deployment unhealthy.  As mentioned earlier in this bug report, doing a script check works fine, and it's able to execute a script.  So for now, I am using that to determine whether the service is healthy.

### Nomad Server logs (if appropriate)
When running the http check above, I see the following in the Consul monitor run in DEBUG mode.
```
2019/09/25 09:49:39 [WARN] agent: Check "_nomad-check-69201912c1f31a50c3a401beeea165acb2778a16" is now critical
2019/09/25 09:49:44 [WARN] agent: Check "_nomad-check-69201912c1f31a50c3a401beeea165acb2778a16" is now critical
2019/09/25 09:49:49 [WARN] agent: Check "_nomad-check-69201912c1f31a50c3a401beeea165acb2778a16" is now critical
2019/09/25 09:49:54 [WARN] agent: Check "_nomad-check-69201912c1f31a50c3a401beeea165acb2778a16" is now critical
```

When running the script check, it outputs this:
```
2019/09/25 10:06:50 [DEBUG] agent: Check "_nomad-check-930bffdb76abf09bc9ce3a90fcf5018944b2c808" is passing
```

**Comment by nickethier** [comment]
Thanks for reporting this. Would you be able to post a dump of the consul checks when this job is running? You can get this by querying the local agent: `curl localhost:8500/v1/agent/checks`.

**Comment by tk512** [comment]
Thanks Nick. This pushed me in the right direction! 

**Solution**
It appears it's not the fault of Nomad or Consul.  The output of the endpoint gave me:

```
"_nomad-check-52ff59e4c4a2f072e5c9b419f61c07c3a9515124": {
        "Node": "xxx",
        "CheckID": "_nomad-check-52ff59e4c4a2f072e5c9b419f61c07c3a9515124",
        "Name": "heartbeat",
        "Status": "critical",
        "Notes": "",
        "Output": "HTTP GET http://xxx:31329/3ec84978-b8aa-4d03-864e-3c50afebb93a/1/heartbeat: 415 Unsupported Media Type Output: ",
        "ServiceID": "_nomad-task-ca82c52e-827e-8276-dc6c-2793a567a7d3-xxx-http",
        "ServiceName": "xxx",
        "ServiceTags": [
            "urlprefix-/3ec84978-b8aa-4d03-864e-3c50afebb93a",
            "xxx"
        ],
        "Definition": {},
        "CreateIndex": 0,
        "ModifyIndex": 0
    },
```

So it seems like the 'http' check doesn't behave like curl is i.e. passing the Accept header. I was using curl as a means of troubleshooting so that led me down the wrong path. 

(I didn't know about where to troubleshoot the check output).

Solution for me was adding this inside of the check block:
```
header {
                      "Accept" = ["*/*"]
                }
```

The endpoint now gives:
```
...
        "Output": "HTTP GET http://xxx:31329/3ec84978-b8aa-4d03-864e-3c50afebb93a/1/heartbeat: 200 OK Output: \"Health is OK: 2019-09-25T15:18:41.131\"",
...
```
I suppose this own't be an issue with most other REST API's, but this particular API required the header.   Feature suggestion would perhaps to add this to the default behavior in Consul ?
