### ISSUE TITLE
nomad restart all containers task in the same during update consul's key for template

### ISSUE THREAD

**Issue by f4rx** [hashicorp/nomad#6392]
```bash
consul -v
Consul v1.6.1

nomad -v
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)
```

```hcl
job "redis" {
  # ...
  datacenters = ["dc1"]

  group "redis-server" {
    count = 6

    update {
      max_parallel = 1
      min_healthy_time = "10s"
      healthy_deadline = "10m"
      progress_deadline = "11m"
    }

    task "server" {
      driver = "docker"

      config {
        image = "redis:5.0.1"
      }

      template {
        data = <<EOH
---
node_dc:     {{ env "node.datacenter" }}
service_key: {{ key "apps/my-app/config/var1" }}
EOH

        destination   = "local/redis.conf"
        change_mode   = "signal"
        change_signal = "SIGINT"
      }

```

Full config is located on page https://gist.github.com/f4rx/ff7819cd8a7f17070e945e68fb89625f

If I change data block or env section, nomad will restart containers one by one. However, if i change key in consul *apps/my-app/config/var1*, nomad will restart my 6 redis containers  in the same time. I guess this is unexpected behavior.

**Comment by tantra35** [comment]
@f4rx Do you play with splay parameter https://www.nomadproject.io/docs/job-specification/template.html#splay, and sent it for example to 1 minute?

**Comment by tgross** [comment]
Hi @f4rx! I think @tantra35's suggestion is probably what you want for this situation. An update of the template values is handled by `splay`, whereas the `update` stanza you have is used to control updates of the overall job. Let us know if this helps!
