### ISSUE TITLE
Service discovery (de)register loop on Nomad clients

### ISSUE THREAD

**Issue by iverberk** [hashicorp/nomad#640]
**Problem description**
I'm seeing odd behaviour from the service discovery mechanism in Nomad. When running with multiple Nomad clients they start deregistering each others jobs.

**Environment**
I'm running three Nomad clients in different virtual machines. They are talking to a Nomad cluster of three, also in different virtual machines. There is also a Consul cluster running on the same virtual machines as where the Nomad servers are running. The complete setup can be rebuilt locally with this [gist](https://gist.github.com/iverberk/ed09736308c11346ee09). Follow the steps in the commands and you should arrive at the same situation as what I am using.

**Expected behaviour**
I would expect Nomad clients to recognize that the service is in fact a Nomad service, but belongs to a different client and that they should not deregister it.

I want to rule out that it is a problem with the way I have setup things. If it is indeed a bug I will be happy to help investigate what the problem could be, otherwise I'm very curious why my setup is wrong.

**Comment by diptanu** [comment]
@iverberk Thanks for posting the links to your scripts, makes it so much easy to debug!

The problem with the setup is that all the Nomad clients are pointing to the same consul agent(which is one of the consul server I guess). So the Nomad clients are deregistering the tasks that they don't know of.

We expect the Consul agent to be installed alongside Nomad clients on all nodes. So you will have a few consul servers in your cluster and every compute nodes will have a Consul agent running which will join the cluster formed by the consul servers. All the interactions of the Nomad client should happen with the local agent and not the consul servers.

Does this makes sense?

**Comment by iverberk** [comment]
Makes total sense, thanks for explaining! I will close the issue.

**Comment by dadgar** [comment]
@diptanu: It might be interesting to have the prefix be based on the Nomad Clients name. That way multiple Nomad clients could use the same consul client?

**Comment by diptanu** [comment]
@dadgar Yeah that would work too.
