### ISSUE TITLE
Blocking queries with X-Nomad-Index: 0 return immediately 

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#6403]
### Nomad version
`Nomad v0.9.5`

### Operating system and Environment details
macOS 10.14.6

### Issue
On a fresh Nomad cluster where no state iterations have occurred and therefore meta indexes are all at 0; blocking queries return immediately rather than block until there is an update or the timeout occurs.

### Reproduction steps
Start the Nomad cluster and prepare the test job.
```
$ nomad agent -dev
$ nomad init -short
```

Attempt to block on allocations, to wait for an update but see it return straight away:
```
$ curl -v 'localhost:4646/v1/allocations?wait=300000ms&index=0'
```

Run the nomad job to generate state updates:
```
$ nomad run example.nomad
```

Run the previous query to grab the new index, and then attempt to block on that index:
```
$ curl -v 'localhost:4646/v1/allocations?wait=300000ms&index=0'
$ curl -v 'localhost:4646/v1/allocations?wait=300000ms&index=<new_index>'
```

The second query should therefore successfully block as expected. The question/problem here is when using a fresh cluster with endpoint indexes on 0, I believe the query should block until there is an update, otherwise, the index needs to be set to 1 which seems hacky.

### Nomad Server logs
Below is an example showing blocking on index 0 returning very quickly.
```
2019-09-30T12:40:19.845+0200 [DEBUG] http: request complete: method=GET path=/v1/allocations?wait=300000ms duration=125.348µs
2019-09-30T12:40:19.846+0200 [DEBUG] http: request complete: method=GET path=/v1/allocations?wait=300000ms duration=140.585µs
2019-09-30T12:40:19.847+0200 [DEBUG] http: request complete: method=GET path=/v1/allocations?wait=300000ms duration=105.148µs
```

**Comment by preetapan** [comment]
@jrasell this is as expected, the index comes from our raft library and the initial commit index is 1. 
 I've added some clarification to our docs in this PR #6404
