### ISSUE TITLE
Nomad UI - Why are logs piped directly from agents? 

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6409]
## Setup

- 3 nomad servers behind an nginx loadbalancer. (192.0.2.1 - 192.0.2.3)
- n+1 nomad worker agents behind a firewall (192.0.2.100 - 192.0.2.255)

## Problem
Nomad UI attempts to redirect the users browser directly to the worker agents on port 4646 when viewing logs.

## Expected result
It should be possible to put the nomad ui behind a load balancer and not give humans direct access to port 4646 on the nomad servers or nomad worker agents.

## Explanation
When navigating to `https://nomad.example.com:443/ui/allocations/<allocId>/<jobname>/logs`, the logs do not load. In the development console I see the following error:

>LOG FETCH: Couldn't connect to //192.0.2.100:4646/v1/client/fs/logs/\<allocid>?follow=true&offset=5000&origin=end&task=\<taskid>&type=stdout

192.0.2.100 is the ip address of the nomad workers. I don't want to give developers direct access to the worker agents on port 4646. 

![Screenshot 2019-10-01 11 11 55](https://user-images.githubusercontent.com/242382/65984256-99bd4700-e43c-11e9-8b38-f95f9011c313.png)

How can I show the logs in the nomad UI, without opening port 4646 to the world? 
Is this a design flaw in nomad ui ? Or do I have it misconfigured.

**Comment by DingoEatingFuzz** [comment]
Hi @spuder, this isn't a design flaw or a misconfiguration. The web ui optimistically attempts to connect directly to a client node first to avoid routing log traffic through the server node. 

In the event that this doesn't work (which is common, as you point out) the web ui will automatically fall back and connect through the server node (or the proxy, whatever the relative path `/v1/client/fs/logs` resolves to).

That all said, logs _should_ still load, but things can get weird when proxying. Did you see [Henry Vindin's response to your mailing list question?](https://groups.google.com/d/msg/nomad-tool/iPZzIplGbow/ytBj18ITBgAJ).

As a debugging suggestion, I'd try navigating directly to the logs API endpoint that is being requested. Both via your proxy and also directly using the nomad server's host, just to see where in the [nomad server] -> [proxy] -> [web ui] chain things break down. When working as expected, hitting the API endpoint directly will stream logs in the browser, it just won't look very nice 😛 

Hope this helps!

**Comment by spuder** [comment]
Thank you for the response. 
After more consideration, I assume this error, is actually just a warning. 

I do get logs in the nomad gui some of the time. Its just not reliable, and sometimes requires multiple refreshes of the page. 

I do have `proxy_buffering = off` in my nginx configs.

I suspect there is more buffering that I need to turn off in nginx

https://serverfault.com/a/818090/169180


For reference, here is the api call for anyone else trying to get logs through the api
```
http://nomad.example.com:4646/v1/client/fs/logs/555-5555-5555?task=app&plain=true&type=stdout
```

**Comment by pySilver** [comment]
Having same issue here. Well at least successful load should cancel the UI error saying:

```
Cannot fetch logs
The logs for this task are inaccessible. Check the condition of the node the allocation is on.
```
