### ISSUE TITLE
Doc: Clarify volume mount `read_only` default state

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6411]
As discussed in https://github.com/hashicorp/nomad/issues/6406  it's not clear what the default value for `read_only` is on volumes. 

### Ideas for improvement

1. Include `read_only` in nomad agent and job volume configurations, even if it is the default value.

e.g

```
      volume_mount {
        volume      = "mysql"
        destination = "/var/lib/mysql"
      }
```
should be

```
      volume_mount {
        volume      = "mysql"
        destination = "/var/lib/mysql"
        read_only = false
      }
```

2. State in the documentation what the default value for `read_only` is

3. Give clearer warning in nomad gui when `read_only` on job definition doesn't match the nomad agent configuration.  

### Documentation links
https://www.nomadproject.io/guides/stateful-workloads/host-volumes.html

https://github.com/hashicorp/nomad/search?q=volume_mount&unscoped_q=volume_mount

**Comment by endocrimes** [comment]
@spuder the default is in the expanded docs for each field so I'm not actually sure where else it makes sense to include this. Gonna cc @angrycub for more tho.

**Comment by angrycub** [comment]
I am going to bring concrete read-only values into the Stateful Workload - Host Volumes guide to help clarify this per @spuder's suggestion and make a nod to the defaults of false.  Should have a PR up soon.

**Comment by tgross** [comment]
It looks like #6435 was merged. Does that cover what we wanted to do for this PR?

**Comment by spuder** [comment]
Yes thank you
