### ISSUE TITLE
Constraints based on external services/availability

### ISSUE THREAD

**Issue by r0p0s3c** [hashicorp/nomad#643]
Hi, 

I'm trying to understand how I would create a task/job definition that schedules a task on a node only if some dynamic/external constraint is met. The specific example I am thinking of is "only spin up/schedule a reverse proxy container on this host if some external service/check indicates reachability from some source network to this host". The ideal solution would be allowing constraints based on the value of an arbitrary key/value in consul (e.g. set by an external service checker/monitor), but it may be that the constraint documentation of the jobspec is not clear/detailed enough and that something similar to this already exists (or this can be done some other way that I have not seen).

Any ideas would be appreciated

**Comment by dadgar** [comment]
Hey,

We have no plans currently to allow constraints based on consul key/value data. It creates a dependency that we don't want. The Nomad Servers will then have to watch consul and in the worst case, the dependency will never be met so the server has unbounded waits on jobs. A possibility is to have a job running that is watching consul as you need and then submitting a job to Nomad.
