### ISSUE TITLE
[question] How to Long Poll job status

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6436]
I have a batch job that runs for x number of seconds. I'd like to poll the job, and perform an action based if it succeeded or failed.

The nomad cli has a `job status` command. 

```
nomad job status -short db-migrate | grep 'Status' | awk '{print $3}'
```

The API has a summary api endpoint
```
curl https://nomad.example.com/v1/job/db-migrate/summary| jq
```

However none of them have a long poll option I can find. 

The best I have found is to write a bash script that will query the status of a job every second. 

```
#/bin/bash

status=""
job=$1

if [[ $# -eq 0 ]]; then 
  echo "Usage watch.sh <jobname>"
fi

while [[ $status != "dead" ]]; do
    status=$(nomad job status -short ${job} | grep 'Status' | awk '{print $3}')
    if [[ $status == "dead" ]]; then
        echo "job complete"
        exit 0
    else
        echo "${status}"
    fi
    sleep 1;
done

```

Is there a built in way to watch a job? Ideally I'm looking for something like `nomad job status foobar -watch 1s -terminate-on success,failure`

**Comment by cgbaker** [comment]
hey @spuder , the CLI doesn't support this natively. there has been some interest expressed with this in the past, and folks have taken to writing tools that do this. one thing that may be helpful is [blocking queries](https://www.nomadproject.io/api/index.html#blocking-queries). These will cut down on the number of API requests necessary; for example, see https://github.com/hashicorp/nomad/issues/3029#issuecomment-366054921. 

however, blocking queries are currently not supported on endpoints such as `job status`.
