### ISSUE TITLE
CLI: Print latest allocation ID upon getting the status of any of the periodic jobs

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#644]
When testing periodic job functionality, I found myself having to tail all logs on all my servers, in order to know where the job was allocated last time it ran and determine if it failed or not based on the what I saw in the container logs. It will be very useful if the `nomad status` would print the last allocation ID of the last time the job was scheduled.

**Comment by dadgar** [comment]
Yeah I agree that the `nomad status` command on periodic jobs is lacking. I think what it will end up being is displaying the set of jobs that have been launched by this and showing the next launch time.

**Comment by c4milo** [comment]
Yes, that will be even better @dadgar
