### ISSUE TITLE
[Question] How to extract logs and job status

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#6449]
### Nomad version
0.9.6

### Operating system and Environment details
CentOS

I put job gc with a tiny time (5m), because a have a lot of allocations per hour (+5k), when I not release allocations, Nomad have a bad performance, about this, ok.

But, how I get jobs status and logs from outside nomad? Like to sent to Elasticsearch, for make history.

*Type of jobs:* Batch / Docker

What the best way? Thx a lot.

**Comment by cgbaker** [comment]
Even without the short time, the client will locally garbage collect allocations above the configured [gc_max_allocs](https://www.nomadproject.io/docs/configuration/client.html#gc_max_allocs) (default: 50). The GC parameters are configurable. However, you will need to balance these parameters against the performance of your nodes, making sure to leave enough [compute capacity for the client](https://www.nomadproject.io/docs/configuration/client.html#reserved-parameters) to do its work, in addition to the allocations running on the client.

As you said, after the allocation is garbage collected, the logs are not available anymore. You are correct; one solution is to ship the logs off the Nomad node to an external system. This is done using a log shipper: https://www.nomadproject.io/guides/operating-a-job/accessing-logs.html#log-shipper-pattern

**Comment by jonatasfreitasv** [comment]
Ok!!! Thx a lot!!!
