### ISSUE TITLE
0.10.0-beta1: exec and raw_exec configs are inconsistent

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6452]
On nomad 0.10.x-beta1 the raw_exec driver is enabled in the config.json like so: 

https://www.nomadproject.io/docs/drivers/raw_exec.html#client-requirements

```
{
  "client": {
    "enabled": true,
    "options": {
      "driver.whitelist": "raw_exec"
    }
  },
  "plugin": {
    "raw_exec": {
      "config": {
        "enabled": true
      }
    }
  }
...
}
```

It's not clear in the documentation how to enable the 'exec' driver. 

https://www.nomadproject.io/docs/drivers/exec.html#client-requirements

I've tried using 0.8 syntax and 0.9 syntax with no luck

0.9 syntax
```
{
  "client": {
    "enabled": true,
    "options": {
      "driver.whitelist": "exec"
    }
  },
  "plugin": {
    "exec": {
      "config": {
        "enabled": true
      }
    }
  }
...
}
```

# Expected behavior

Enabling `exec` should be consistent with enabling `raw_exec`. Or at the very least the documentation should provide a clearer example.

**Comment by endocrimes** [comment]
@spuder `exec` is enabled by default if the client is running as `root` and has access to cgroups https://www.nomadproject.io/docs/drivers/exec.html#client-requirements. `raw_exec` requires explicit enabling as it runs uncontained processes on your host.

**Comment by spuder** [comment]
Thank you. I understand now why the `exec` driver is not showing up. The service is running as a 'nomad' user, not root. 

```
nomad      706  0.3  0.8 445784 54012 ?        Ssl  11:54   0:00 /usr/local/bin/nomad agent -config /etc/nomad
```
