### ISSUE TITLE
terraform/aws apply fails with `configuration is not supported`

### ISSUE THREAD

**Issue by dotanrs** [hashicorp/nomad#6462]
I tried to create a nomad cluster in AWS to learn how to use it.
I ran `terraform apply` with the given terraform code, and got the following error:

**`Error:Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.`**

I didn't debug it to much (I'm just going to create instances manually for now), but thought you should know.

I think it's an awesome idea to have a pre-made terraform script for people to quickly bootstrap nomad to learn how to use it, but it's important that the script works :)

**Comment by cgbaker** [comment]
hi @dotanrs , that looks like an error message from EC2. It could mean any number of things, e.g., that the selected instance type is not compatible with the default VPC. I would look at the default VPC and the instance type in `terraform.tfvars` and verify that those are compatible.

**Comment by dotanrs** [comment]
yup, you're right. It was the instance type.
Thanks!
