### ISSUE TITLE
JSON example in Job Specification page

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/nomad#647]
https://www.nomadproject.io/docs/jobspec/ says that there is support for JSON as well as HCL, but there is no example of a job spec file in JSON format. Adding one with the same config as the one in "HCL Syntax" would be extremely helpful to see the mappings from HCL to JSON and vice-versa.

**Comment by cleung2010** [comment]
I can extrapolate the mappings by looking at other Hashicorp projects (e.g. https://www.terraform.io/docs/configuration/syntax.html) or projects that uses Hashicorp tools and have JSON config files, but the syntax can be confusing for people unfamiliar with the toolchain and HCL.

**Comment by kaskavalci** [comment]
What I've done is that I run my hcl syntax job on Nomad and retrieved json version of it via `v1\job\jobid` http call. There are some redundant (which I haven't found them on Job Spec webpage) which I deleted. 

However when I tried to submit my hcl syntax job file over HTTP, I get the following error:

```invalid character 'j' looking for beginning of value```

Doesn't Nomad suppose to support HCL and JSON?

**Comment by cleung2010** [comment]
The HTTP API only supports JSON. If you do it via the CLI then it would also accept HCL.

**Comment by kaskavalci** [comment]
I assume they use [hcl](https://github.com/hashicorp/hcl) library to parse json, that way both HCL and JSON can be supported. Now I have to convert all my HCL configurations to JSON just to use them via HTTP API.

**Comment by sheldonkwok** [comment]
The http api for nomad seems to accept a json schema that's different from simply transforming the hcl into json. The lack of documentation on it makes it difficult to use. I had to run the cli and hcl with the options I wanted and then use the http api get to see how the schema should look.

**Comment by snufalufagus** [comment]
+1 for a JSON examples jobs i.e.. $ nomad init json. 

I have wasted too much time trying to get a working json example to submit properly, when this could be documented in about 5 minutes by the hashicorp team. It would be helpful if the API documentation included example curl commands as well. 

Better documentation and examples = more hashicorp customers

**Comment by diptanu** [comment]
Fixed via #925
