### ISSUE TITLE
0.10.0-rc1 `host_volume` does not affect container scheduling decision

### ISSUE THREAD

**Issue by rbjorklin** [hashicorp/nomad#6470]
### Nomad version
```bash
> nomad version
Nomad v0.10.0-rc1 (c49bf41779d2ee462f46e2f58328e58c51970a83)
```
### Operating system and Environment details
```bash
> uname -a
Linux example1 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue
Declaring a `host_volume` block in a nomad client config does not make a docker container schedule to that node even when a `volume` block exists in the group and `volume_mounts` exists in the task.

### Reproduction steps
Follow the steps in the official guide: [Stateful Workloads with Nomad Host Volumes](https://www.nomadproject.io/guides/stateful-workloads/host-volumes.html)

**Comment by endocrimes** [comment]
@rbjorklin Could you add a little bit more detail here? Did you get scheduled on an incorrect node, or did the job not get scheduled at all? Could you also share your configuration and the output from `nomad run`?

Thanks!

**Comment by rbjorklin** [comment]
The job got scheduled on an incorrect node without the `host_volume` declared.
```bash
> nomad job run nexus.hcl
==> Monitoring evaluation "5b8ee5a6"
    Evaluation triggered by job "nexus"
    Allocation "179a2d63" created: node "3d63040f", group "nexus"
    Evaluation within deployment: "3f586539"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "5b8ee5a6" finished with status "complete"
```

The `host_volume` is only declared on `nbg11` but as you can see below the job has been scheduled on all nodes after I have stopped it and then started it again.
```bash
> nomad job status nexus
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created     Modified
5f3170da  1a590e57  nexus       4        run      pending   9s ago      9s ago
179a2d63  3d63040f  nexus       2        stop     complete  2m11s ago   18s ago
ba8332ec  24e69ffe  nexus       0        stop     complete  10h14m ago  4m13s ago
```
```bash
>  nomad node status
ID        DC    Name   Class   Drain  Eligibility  Status
1a590e57  nbg1  nbg12  <none>  false  eligible     ready
3d63040f  nbg1  nbg11  <none>  false  eligible     ready
24e69ffe  nbg1  nbg13  <none>  false  eligible     ready
```

```hcl
client {
    enabled = true
    node_class = ""
    no_host_uuid = false
    max_kill_timeout = "30s"
    network_speed = 0
    cpu_total_compute = 0
    gc_interval = "1m"
    gc_disk_usage_threshold = 80
    gc_inode_usage_threshold = 70
    gc_parallel_destroys = 2
    reserved {
        cpu = 0
        memory = 0
        disk = 0
    }
    host_volume "nexus" {
        path = "/opt/nexus"
        read_only = false
    }
}
```
Job:
```hcl
job "nexus" {
  datacenters = ["nbg1"]
  type = "service"
  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    progress_deadline = "10m"
    auto_revert = false
    canary = 0
  }
  migrate {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "5m"
  }
  group "nexus" {
    count = 1
    restart {
      attempts = 3
      interval = "2m"
      delay = "30s"
      mode = "fail"
    }
    ephemeral_disk {
      size    = "5000"
      sticky  = true
      migrate = true
    }
    volume "data" {
      type      = "host"
      source    = "nexus"
      read_only = false
    }
    task "nexus" {
      driver = "docker"
      volume_mount {
        volume      = "data"
        destination = "/nexus-data"
        read_only = false
      }
      config {
        image = "sonatype/nexus3:latest"
        port_map {
          http = 8081
        }
      }
      resources {
        cpu    = 500
        memory = 1000
        network {
          port "http" {}
        }
      }
      service {
        name = "nexus"
        tags = ["nomad", "global", "nexus", "http", "expose", "healthMode=http", "healthMethod=GET", "healthPath=/service/rest/v1/status"]
        port = "http"
        check {
          name     = "alive"
          type     = "http"
          path     = "/service/rest/v1/status"
          interval = "30s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

**Comment by endocrimes** [comment]
@rbjorklin Hmm - I'm unfortunately unable to reproduce this - Could you provide the output of `nomad node status` for each node, and their relevant client configurations? Thanks!

**Comment by rbjorklin** [comment]
Oh, I just noticed that it says `Host Volumes: <none>` in the output. What would cause this?
You can find my configuration [here](https://pastebin.com/n68dkMYh).

```bash
[root@nbg11 ~]# nomad version
Nomad v0.10.0-rc1 (c49bf41779d2ee462f46e2f58328e58c51970a83)

[root@nbg11 ~]# nomad node status
ID        DC    Name   Class   Drain  Eligibility  Status
1a590e57  nbg1  nbg12  <none>  false  eligible     ready
3d63040f  nbg1  nbg11  <none>  false  eligible     ready
24e69ffe  nbg1  nbg13  <none>  false  eligible     ready

[root@nbg11 ~]# nomad node status 3d63040f
ID            = 3d63040f
Name          = nbg11
Class         = <none>
DC            = nbg1
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 138h23m44s
Host Volumes  = <none>
Driver Status = docker,exec,raw_exec
```

**Comment by endocrimes** [comment]
@rbjorklin What version of Nomad are the Servers running? (and could you share all of the clients configs please?)

**Comment by rbjorklin** [comment]
All the threes servers are running 0.10.0-rc1. I've attached the configuration from the other two nodes. Note that the first server's configuration was in `.json` because I started experimenting with that on the Ansible role I'm using. These two are in `.hcl`.
[nbg12.zip](https://github.com/hashicorp/nomad/files/3725290/nbg12.zip)
[nbg13.zip](https://github.com/hashicorp/nomad/files/3725291/nbg13.zip)

**Comment by preetapan** [comment]
@rbjorklin I attempted to run a single client with the json config you provided [in this comment](https://github.com/hashicorp/nomad/issues/6470#issuecomment-541333856) I am able to see host volume information correctly in the CLI.

At this point a couple of us have tried to reproduce this issue and are not able to, Could you check your configs again, perhaps something else in your environment is overriding your client configuration so the file you gave to ansible isn't the one that's actually being used?

**Comment by shantanugadgil** [comment]
hi @rbjorklin was the cluster a fresh setup? or upgraded from something like 0.10-beta1 ?

**Comment by rbjorklin** [comment]
My setup is in a publicly accessible demo environment so if you just provide your public ssh-keys I would gladly provide you access to my problematic setup.

@shantanugadgil I upgraded from 0.9.5.

**Comment by endocrimes** [comment]
@rbjorklin if the cluster isn't sensitive then adding github.com/endocrimes.keys and github.com/preetapan.keys would be great! - thank you!

**Comment by rbjorklin** [comment]
@endocrimes Alright I've added your keys to:
* `nbg11.rbjorklin.com`
* `nbg12.rbjorklin.com`
* `nbg13.rbjorklin.com`

Log in as root and feel free to install any software you need to debug. I'll be nuking these instances once this is over.

**Comment by endocrimes** [comment]
@rbjorklin It appears that two of the nodes agents are running nomad 0.9.5 ([`nbg13.global`](http://nbg12.rbjorklin.com:4646/ui/servers/nbg13.global), and [`ngb12.global`](http://nbg12.rbjorklin.com:4646/ui/servers/nbg12.global).

To use nomad 0.10 features, all _servers_ must be running nomad 0.10, but this is really not a well defined error, I'm sorry for that.

**Comment by rbjorklin** [comment]
Oh! Terribly sorry about that! Closing!
