### ISSUE TITLE
Get Started Faster

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6474]
# Issue

Right now if you're new to Nomad and would like to do a walkthrough the fastest path is:

![image](https://user-images.githubusercontent.com/113362/66660354-ed2c5380-ebf9-11e9-9eac-581dbcfa9334.png)

1. nomadproject.io
2. Big Get Started button
...

So far so good! However, the text of [that page](https://www.nomadproject.io/intro/index.html) is purely a description of Nomad. If you make it to the bottom it guides you to use cases and users. At no point does it guide you to a hands-on walkthrough.

![image](https://user-images.githubusercontent.com/113362/66660395-fcab9c80-ebf9-11e9-8eae-1e108de24d1b.png)

However, if you peek over at the side-bar there's _another_ Getting Started link that takes you to a different page than the homepage's Get Started button!

![image](https://user-images.githubusercontent.com/113362/66660446-151bb700-ebfa-11e9-8c93-b8764cb58a3d.png)

That's a walkthrough!

# Suggested Fix

1. Drop a link, preferably toward the top, of [Get Started (Intro)](https://www.nomadproject.io/intro/index.html) to point to the Getting Started Guide
2. Rename Get Started button and/or Getting Started guide to make it clear they're distinct resources.

**Comment by tgross** [comment]
At this point (following the big Learn update), that first link leads to https://learn.hashicorp.com/nomad, which has the **Getting Started** tutorial above the fold. I think this is safe to close.
