### ISSUE TITLE
0.10.0-beta1: unable to parse peers.json file

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6475]
I have a 0.10.0-beta1 test cluster with 3 nomad servers that lost the leader due to ip address changes. 

Following the recovery instructions here says it should be possible to recover by creating a peers.json file

https://www.nomadproject.io/guides/operations/outage.html

I have created `/opt/nomad/server/raft/peers.json` as shown in the documentation

```
[
	"192.0.2.0:4647",
	"192.0.2.1:4647",
	"192.0.2.2:4647"
]
```

Yet when I start nomad, I get this error: 
```
Oct 11 15:54:00 nomad1 nomad[14355]: ==> Error starting agent: server setup failed: Failed to start Raft: recovery failed to parse peers.json: json: cannot unmarshal string into Go value of type raft.configEntry
```

```
Oct 11 15:54:00 nomad1 nomad[14355]: ==> Error starting agent: server setup failed: Failed to start Raft: recovery failed to parse peers.json: json: cannot unmarshal string into Go value of type raft.configEntry
Oct 11 15:54:00 nomad1 nomad[14355]:     2019-10-11T15:54:00.781Z [WARN ] agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/nomad/plugins
Oct 11 15:54:00 nomad1 nomad[14355]:     2019-10-11T15:54:00.790Z [INFO ] agent: detected plugin: name=rkt type=driver plugin_version=0.1.0
Oct 11 15:54:00 nomad1 nomad[14355]:     2019-10-11T15:54:00.790Z [INFO ] agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
Oct 11 15:54:00nomad1 nomad[14355]:     2019-10-11T15:54:00.790Z [INFO ] agent: detected plugin: name=exec type=driver plugin_version=0.1.0
......
nomad: failed to start Raft: error="recovery failed to parse peers.json: json: cannot unmarshal string into Go value of type raft.configEntry"
```

Why does nomad think this is not valid json?

**Comment by angrycub** [comment]
You will need to use the peers.json format for Raft Protocol v3 (https://www.nomadproject.io/guides/operations/outage.html#peers-json-format-changes-in-raft-protocol-3) for clusters created in Nomad v0.10.0-beta1

**Comment by spuder** [comment]
After more research, it appears I'm encountering this error because I'm using raft version 3. 

There is improvement to be made in the guide for recovery. 

 - [ ] 1. Replace cyptic error "Failed to start Raft: recovery failed to parse peers.json: json: " with a friendlier error. Something like 

"Detected peers.json for raft version 2, but using raft version 3, Please update peers.json with version 3 syntax"

- [ ] 2. Document how to tell if using raft version 2 or raft version 3. Currently the documentation leads the reader down the version 2 path where they will hit errors. 


![Screenshot 2019-10-11 09 59 35](https://user-images.githubusercontent.com/242382/66666453-e1e32300-ec0d-11e9-835f-4d980ac1ba31.png)

**Comment by shantanugadgil** [comment]
FWIW, when I replaced my Nomad binary on my test Nomad server and restarted the server process, it caused an outage. Normally upgrading by replacing the binary **just works**.
Previous version: beta1
New version: rc1

As I don't have the `raft_protocol` explicitly set in the `server` config, I think it caused a change in the "default" value used of the raft_version made it lose cluster leadership.

**Comment by cgbaker** [comment]
yeah, we upgraded the default raft protocol version to `3` in the `beta`, before finding some issues like these and deciding we would keep it at `2` for `0.10.0`. sorry about that, @shantanugadgil .

**Comment by spuder** [comment]
The associated merge request for the documentation is ready.
