### ISSUE TITLE
Deprecate rkt

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6478]
Rkt plan:
1. Mark it as deprecated on the web site (0.10) - _done_
2. Move it to an external plugin (0.11)
3. Move rkt issues to external plugin repo (0.11)
4. Support external plugin through 0.11.x

## Background

CNCF archived it: https://www.cncf.io/blog/2019/08/16/cncf-archives-the-rkt-project/

**Comment by tgross** [comment]
Settle down there, stalebot 😀

**Comment by schmichael** [comment]
Closed by https://github.com/hashicorp/nomad/pull/7236
