### ISSUE TITLE
update gopsutil

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6483]
The library we used for stats collection has changed how windows stats collection works: 
https://github.com/shirou/gopsutil/pull/611

This will affect this code:
https://github.com/hashicorp/nomad/blob/master/client/stats/cpu_windows.go#L12

This issue captures updating gopsutil, as well as testing windows specific changes.

**Comment by onlyjob** [comment]
Note that [shirou/gopsutil](https://github.com/shirou/gopsutil/releases) 2.19.05 introduced breaking change https://github.com/shirou/gopsutil/commit/cae8efcffa765c9534442328d385bdd883faf5df as per https://github.com/shirou/gopsutil/issues/676 that causes the following FTBFS in Nomad:

~~~~
src/github.com/hashicorp/nomad/client/structs/structs.go 
codecgen error: error running 'go run codecgen-main-102.generated.go': exit status 2, console: # github.com/hashicorp/nomad/client/stats 
../stats/host.go:278:70: times.Stolen undefined (type "github.com/shirou/gopsutil/cpu".TimesStat has no field or method Stolen) 

src/github.com/hashicorp/nomad/client/structs/structs.go:3: running "codecgen": exit status 1 
~~~~

The patch for Nomad is trivial but please review it nevertheless:

~~~~
--- a/client/stats/host.go
+++ b/client/stats/host.go
@@ -274,9 +274,9 @@
        currentUser := times.User
        currentSystem := times.System
        currentTotal := times.Total()
        currentBusy := times.User + times.System + times.Nice + times.Iowait + times.Irq +
-               times.Softirq + times.Steal + times.Guest + times.GuestNice + times.Stolen
+               times.Softirq + times.Steal + times.Guest + times.GuestNice

        deltaTotal := currentTotal - h.prevTotal
        idle = ((currentIdle - h.prevIdle) / deltaTotal) * 100
        user = ((currentUser - h.prevUser) / deltaTotal) * 100
~~~~

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/7347
