### ISSUE TITLE
Upgrade to MacOS Catalina makes nomad unusable

### ISSUE THREAD

**Issue by jimmywan** [hashicorp/nomad#6484]
![Screen Shot 2019-10-11 at 15 10 49](https://user-images.githubusercontent.com/10406673/66682606-38b32180-ec3b-11e9-9e2c-129fda7a523f.png)

# Nomad version
0.9.0

### Operating system and Environment details
MacOS Catalina 

### Reproduction steps
Use nomad

**Comment by cgbaker** [comment]
see https://github.com/hashicorp/terraform/issues/23033

**Comment by preetapan** [comment]
Hey @jimmywan! Nice to see a former co-worker here. 

I wanted to add that if you are trying to run nomad on MacOs there are a few other hurdles that have to do with Java fingerprinting and log collection. Won;t go into the gory details now, but we recommending using [Vagrant](https://www.nomadproject.io/intro/getting-started/install.html#vagrant-setup-optional-) for MacOs users to get a sandboxed enviroment that runs Nomad.

**Comment by jbayer** [comment]
[Here is a sequence of steps](https://github.com/hashicorp/terraform/issues/23033#issuecomment-542302933) that will enable running the existing Nomad binaries on Catalina via a user-override until we notarize the Nomad macOS binaries.
