### ISSUE TITLE
[Question] How to disable retry/reschedule in batch job?

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#6485]
### Nomad version
0.9.6

### Operating system and Environment details
CentOS

I'm try to put this but not work:
```
     "reschedule": {
                "attempts": 0,
                "unlimited": false
              },
```

**Comment by erhlee-bird** [comment]
I've been able to keep my batch jobs from both retrying and rescheduling by doing the following.
Adding a restart stanza and a reschedule stanza.

```
job "echo-dispatch" {
  datacenters = ["dc1"]
  type = "batch"
  priority = 1

  parameterized {
    payload = "forbidden"
    meta_required = ["message"]
    meta_optional = []
  }

  group "echo" {
    task "echo" {
      driver = "exec"
      config {
        command = "echo"
        args = ["${NOMAD_META_message}"]
      }
    }
    restart {
      attempts = 0
      mode = "fail"
    }
  }
  reschedule {
    attempts = 0
  }
}
```

**Comment by preetapan** [comment]
@jonatasfreitasv the reschedule/restart stanzas provided by @erhlee-bird above are the right way to disable rescheduling and local restarts. Closing this since the question has been answered

**Comment by kaspergrubbe** [comment]
I just want to add to this (for anyone that might be googling) that the official docs says the following about disabling rescheduling:

```hcl
job "docs" {
  group "example" {
    reschedule {
      attempts  = 0
      unlimited = false
    }
  }
}
```

From: https://www.nomadproject.io/docs/job-specification/reschedule#disabling-rescheduling

**Comment by doprdele** [comment]
@kaspergrubbe I was googling just this, thank you
