### ISSUE TITLE
qemu driver with KVM accelerator fails with "Could not access KVM kernel module: Permission denied"

### ISSUE THREAD

**Issue by pka** [hashicorp/nomad#650]
Job spec:
```
driver = "qemu"
config {
      artifact_source = "file:///tmp/debian8.img"
      accelerator = "kvm"
}
```
Job stderr:
```
Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied
```
Direct execution of same qemu-system-x86_64 command works.

**Comment by diptanu** [comment]
@pka What user is the Nomad client running as?

**Comment by pka** [comment]
Nomad client is running as root.

**Comment by dadgar** [comment]
Should be fixed by #656.

**Comment by vhosakot** [comment]
I was able to resolve the `failed to initialize KVM: Permission denied` error after doing the following:

```
rmmod kvm_intel
rmmod kvm
modprobe kvm
modprobe kvm_intel
```

The above commands reload the `kvm_intel` and `kvm` kernel modules.

**Comment by Zelda00** [comment]
to fix this issue you need to adduser to kvm to work fine ,give permission to solve it.

sudo adduser "youaccount" kvm

https://ccdtt.com/solved-could-not-access-kvm-kernel-module-permission-denied/
