### ISSUE TITLE
Test with Consul Connect + ACL + TLS

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6502]
An E2E that mimics production environments as closely as possible would be ideal. This would include:

* 2 jobs/services
  * stretch goal is having one of them be Connect Native
* Consul configured with ACLs and mTLS
  * stretch goal Nomad configured with ACLs and mTLS (shouldn't be related but would be nice to implement for completeness)

Test sidecar task overrides and job updates to ensure there aren't any unexpected interactions with Consul token handling.

**Comment by tgross** [comment]
Reports of problems with these in #6594 and #6711

**Comment by saez0pub** [comment]
please don't auto close this issue

**Comment by spuder** [comment]
No close

**Comment by tgross** [comment]
We've had this done for quite a while now and never closed this out. It's running E2E on nightly.
