### ISSUE TITLE
task `user` should set the user for the docker driver

### ISSUE THREAD

**Issue by langmartin** [hashicorp/nomad#6519]
Docker supports setting the user for a contained task on the command line, but nomad does not use the task `user` key to do so.

**Comment by notnoop** [comment]
Looks like docker honors task `user` setting[1], judged by my testing of nomad 0.10.0.  The code handles it in https://github.com/hashicorp/nomad/blob/v0.10.0/drivers/docker/driver.go#L666-L674 - but we lack tests around it.

[1] https://www.nomadproject.io/docs/job-specification/task.html#user
