### ISSUE TITLE
Still uses "github.com/hashicorp/net-rpc-msgpackrpc"

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#6521]
See https://github.com/hashicorp/net-rpc-msgpackrpc/issues/1#issuecomment-24591071 for details.

Wouldn't it be better to use [github.com/ugorji/go](https://github.com/ugorji/go) instead?

**Comment by jefferai** [comment]
Linking to https://github.com/hashicorp/consul/issues/6664 as the same answer applies.
