### ISSUE TITLE
Docs: Differing code examples on volume stranza

### ISSUE THREAD

**Issue by gabriel-v** [hashicorp/nomad#6535]
The [documentation page on `volume` ](https://www.nomadproject.io/docs/job-specification/volume.html) gives the following snippet:

```
job "docs" {
  group "example" {
    volume "certs" {
      type      = "host"
      source    = "ca-certificates"
      read_only = true
    }
  }
}

```

The [page on  `volume_mount`](https://www.nomadproject.io/docs/job-specification/volume_mount.html) shows this example:

```
job "docs" {
  group "example" {
    volume "certs" {
      type = "host"
      read_only = true

      config {
        source = "ca-certificates"
      }
    }

    task "example" {
      volume_mount {
        volume      = "certs"
        destination = "/etc/ssl/certs"
      }
    }
  }
}
```

Are both examples (`volume > config > source` and `volume > source`) valid?

**Comment by langmartin** [comment]
Good catch, the `volume > config` syntax is incorrect. I'll update the docs, thanks!
