### ISSUE TITLE
[BUG] cannot allocate memory

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#6538]
### Nomad version
0.9.6

### Operating system and Environment details
CentOS

Client disk and memory is ok, have a lot of space.

```
Failed to start container 4fcdcf0af1d3c1b3da89f1196ee25901454c36f53d8b819c252e52f184fff191: API error (500): OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/memory/docker/4fcdcf0af1d3c1b3da89f1196ee25901454c36f53d8b819c252e52f184fff191: cannot allocate memory\"": unknown
```

**Comment by angrycub** [comment]
Does your job supply enough [memory](https://www.nomadproject.io/docs/job-specification/resources.html#memory) in the `resource` stanza for your application to start?  The default of 300mb allocated for the allocation might not be adequate?

**Comment by jonatasfreitasv** [comment]
Is this error about the container trying to use more memory than was allocated in resources?

**Comment by langmartin** [comment]
The error may be about allocation, the cgroup errors collapse a few different error conditions.

**Comment by shantanugadgil** [comment]
> this machine have 178 Cores and 3T RAM

Envy!!! 😮 😀

**Comment by tgross** [comment]
@jonatasfreitasv it looks like from your last reply that this is resolved from your perspective and not a Nomad issue? I'm going to close this issue but feel free to re-open if I've closed it in error.
