### ISSUE TITLE
non port mapped, routable containers dont show in consul

### ISSUE THREAD

**Issue by MansM** [hashicorp/nomad#654]
In a setup I am building I run 2 kind of servers
nomadserverX:
nomad server
consul server

dockerserverX
nomad client
consul client
docker engine running in bridge mode on br0 using ip range 10.50.2X.0/24

A lot of attempts later I havent got nomad to report the ip and service to consul. The moment I add a portmap (which I dont want). it shows up. Not sure if this is a bug or just pebcak

**Comment by diptanu** [comment]
@MansM So the purpose of the consul integration is to register services with Consul exposed by Tasks which are running a process listening on a port on a network interface.

So a service definition needs to have a port associated with the Task. Ports can be either static or dynamic. 

Does this makes sense? Happy to explain more if you can share your job definition.

**Comment by MansM** [comment]
job "haproxy" {
  datacenters = ["dc1"]
  constraint {
    attribute = "$attr.kernel.name"
    value = "linux"
  }

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "loadbalancers" {
    count = 2

    restart {
      interval = "5m"
      attempts = 10
      delay = "25s"
    }

    task "haproxy" {
      driver = "docker"
      config {
        image = "dockerreg:5000/haproxy"
      }

      service {
        name = "loadbalancer"
        tags = ["haproxy"]
        port = "80"
        check {
         name = "alive"
         type = "tcp"
         interval = "10s"
         timeout = "2s"
        }
      }
      resources {
        cpu = 500 # 500 Mhz
        memory = 128 # 256MB
        network {
          mbits = 10
          
        }
      }
    }
  }
}

when I added a static port, nomad refused, mentioning it was already taken (which is not true as every container has a routable ip)

**Comment by diptanu** [comment]
@MansM The definition is not correct 

You have to request nomad for port in the resources block like this -

```
port "http" {
 static=80
}
```

And in the service block refer to the port with it's name. I would suggest looking at the example.nomad and modifying that to begin with. The example.nomad can be generated by running ```nomad init```

**Comment by diptanu** [comment]
Closing this issue, please feel free to open it if you think the DSL or docs needs any improvements.

**Comment by MansM** [comment]
As I mentioned before: static will result in nomad refusing to schedule.

root@nomadserver1:/vagrant# nomad run haproxy.nomad
==> Monitoring evaluation "6329a653-b01b-bb41-96b6-680a51f66a48"
    Evaluation triggered by job "haproxy"
    Allocation "1b6886bc-3f1c-97ba-00db-9387775f1a95" created: node "e19b15b7-1d20-7a35-d00b-c864c85e7a22", group "loadbalancers"
    Scheduling error for group "loadbalancers" (failed to find a node for placement)
    Allocation "5fae72b0-2406-5a09-72cf-81ce58946c65" status "failed" (0/1 nodes filtered)
      * Resources exhausted on 1 nodes
      * Dimension "network: reserved port collision" exhausted on 1 nodes
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "6329a653-b01b-bb41-96b6-680a51f66a48" finished with status "complete"


job "haproxy" {
  datacenters = ["dc1"]
  constraint {
    attribute = "$attr.kernel.name"
    value = "linux"
  }

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "loadbalancers" {
    count = 2

    restart {
      interval = "5m"
      attempts = 10
      delay = "25s"
    }

    task "haproxy" {
      driver = "docker"
      config {
        image = "dockerreg:5000/haproxy"
      }

      service {
        name = "loadbalancer"
        tags = ["haproxy"]
        port = "http"
        check {
         name = "alive"
         type = "tcp"
         interval = "10s"
         timeout = "2s"
        }
      }
      resources {
        cpu = 500 # 500 Mhz
        memory = 128 # 256MB
        network {
          mbits = 10
          port "http" {
           static=80
          }
          
        }
      }
    }
  }
}

**Comment by diptanu** [comment]
@MansM From the logs looks like the network device that Nomad detected on that machine has another process bound to port 80. Are you trying to make your container use some virtual IP addresses connected to the docker bridge?

**Comment by MansM** [comment]
Every docker container gets an (routable) ip address in the range 10.50.21.0/24 
br0:
auto br0
        iface br0 inet static
        address 10.50.21.2
        netmask 255.255.255.0
        bridge_ports eth2
        bridge_stp off
        bridge_fd 0

**Comment by MansM** [comment]
Actually I dont want to use portforwarding at all. I rather have consul check using the containers routable ip.
