### ISSUE TITLE
[Question]: How to debug a job stuck in queued state?

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#6549]
This probably isn't a bug or such; Hoping someone can point me in the right direction.

I have a job that a completed evaluation; but no active allocations and its status reported "` Queued".

```#!sh
[root@localhost ~]# nomad status myjob
ID            = myjob
Name          = myjob
Submit Date   = 2019-10-25T00:36:19Z
Type          = system
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
services    1       0         0        0       0         0

Allocations
No allocations placed
```

How do I debug this? Why is it queued? I can't find any information in the UI or via the CLI about where the cluster is out of resources; or why this job would be in a queued state. I didn't notice anything in the system logs with `journalctl -f` either.

**Comment by prologic** [comment]
The only hint I can find is where I go inspect the node status itself via the CLI:

```#!sh
[root@localhost ~]# nomad node status 75e9b67f
ID            = 75e9b67f
Name          = localhost
Class         = <none>
DC            = dc1
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 1h29m23s
Driver Status = docker

Node Events
Time                  Subsystem  Message
2019-10-24T23:30:57Z  Cluster    Node registered

Allocated Resources
CPU            Memory           Disk
2720/6372 MHz  9.3 GiB/9.6 GiB  5.6 GiB/38 GiB

Allocation Resource Utilization
CPU           Memory
543/6372 MHz  2.7 GiB/9.6 GiB

Host Resource Utilization
CPU           Memory           Disk
614/6372 MHz  3.9 GiB/9.6 GiB  21 GiB/50 GiB

Allocations
ID        Node ID   Task Group     Version  Desired  Status   Created    Modified
...
```
Where I notice:

```
Allocated Resources
CPU            Memory           Disk
2720/6372 MHz  9.3 GiB/9.6 GiB  5.6 GiB/38 GiB
```

But this information doesn't seem to be surfaced in the Job itself or anywhere I can find in the UI?

**Comment by dekimsey** [comment]
FWIW, Elasticsearch has exposes an [explain API for shard allocation](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-allocation-explain.html). I think a similar behavior in Nomad would be quite helpful. I've run into this exact same situation with my own jobs on occasion.

**Comment by prologic** [comment]
I _think_ at the very least we should try to surface more information in the UI about possible reasons the job might be in a "queued" state. Currently I don't believe this is surfaced anywhere except via the CLI by querying the node's state.

**Comment by tgross** [comment]
Hi @prologic! It looks like there's definitely some missing information there about why the job might still be queued. What I'd be interested to see in scenarios like this are the evaluations for the job via `nomad job status -evals $job`. I suspect there's a clue there as to what we're not exposing about queued jobs.
