### ISSUE TITLE
Nomad drain -enable -self confused by not running in client mode

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/nomad#6581]
### Nomad version

`Nomad v0.10.0 (25ee121d951939504376c70bf8d7950c1ddb6a82)`

### Operating system and Environment details

`Linux 4.14.146-120.181.amzn2.x86_64 #1 SMP Fri Oct 18 17:01:06 UTC 2019`

### Issue

Unable to drain self and prefer not having to `nomad node status` grep the node name because it node name gets reused after re-provisioning.

```
$ sudo NOMAD_TOKEN= nomad node drain -enable -yes -self
Nomad not running in client mode
```

My service is running as root
```
root      2424     1  0 Oct28 ?        00:00:28 /usr/local/bin/nomad agent -config /etc/nomad.d -bind x.x.x.x. -dc xxx -node xxx -region xxx
```

And verified client mode is enabled in /etc/nomad.d/client.hcl
```
client {
  disable_remote_exec           = true
  enabled                       = true
```

**Comment by notnoop** [comment]
@vvitayau Thanks for reporting this.  This seems like a bug indeed, and we'd like to reproduce it.

Mind if you provide all of your config (with sensitive bits redacted), the content of `nomad node status -self -verbose`, the response body of `http://localhost:4646/v1/agent/self` on the node? The client logs would be great.

Also, I'd suggest reconsidering using `sudo` in `nomad node ...` commands.  `sudo` stomps some environment variables (e.g. `NOMAD_ADDR` and credentials environment) that may make it harder to debug an issue.  Not sure if it's relevant here.

**Comment by vvitayau** [comment]
Interesting and thank you for the input, 
that helped isolated the issue down to how NOMAD_ADDR
 is configured to the nomad server rather than to its own IP.

```
$  NOMAD_TOKEN= nomad node status -self
Nomad not running in client mode

$ sudo cat /etc/environment 
NOMAD_ADDR=http://nomad.service.consul:4646

# works fine to resolve which are the main nomad server
$ dig nomad.service.consul

$  NOMAD_ADDR=http://nomad.service.consul:4646 NOMAD_TOKEN= nomad node status -self
Nomad not running in client mode

# I've got nomad bind to the local IPv4 so 127.0.0.1 is expected failure
$  NOMAD_ADDR=http://localhost:4646 NOMAD_TOKEN= nomad node status -self
Error querying agent info: failed querying self endpoint: Get http://localhost:4646/v1/agent/self: dial tcp [::1]:4646: connect: connection refused

# whereas it works better using its own IP address
NOMAD_ADDR=http://a.b.c.d:4646 NOMAD_TOKEN= nomad node status -self
```
