### ISSUE TITLE
Updating task with service stanza does not register service

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#6597]
### Nomad version
Nomad v0.10.0 (25ee121d951939504376c70bf8d7950c1ddb6a82)

### Issue
When updating a Nomad job to add a service stanza to a task, the service should be registered in Consul. This does not happen.

Logs (below) indicate that the group services update hook has incorrect expectations, probably related to the group-level networking support for 0.10.0: 
https://github.com/hashicorp/nomad/blob/d0d18b2a85b7851aa20e6b429ec20282edf57caa/command/agent/consul/client.go#L808-L810

### Reproduction steps
0. `[consul,nomad] agent -dev`
1. Create a job of type `service`, with no `service` stanzas on the task.
2. Update the job, adding a `service` stanza to the task. 
3. Note that the job was not registered in consul.

### Job file (if appropriate)
```hcl
job "example" {
  datacenters = ["dc1"]
  type = "service"
  group "cache" {
    task "redis" {
      driver = "docker"
      config {
        image = "redis:3.2"
        port_map {
          db = 6379
        }
      }
      resources {
        network {
          port  "db"  {}
        }
      }
      service {
        name = "redis-cache"
        port = "db"
      }
    }
  }
}

```

### Nomad Client logs (if appropriate)
```
* update hook "group_services" failed: unable to register a group service without a group network"
```

**Comment by cgbaker** [comment]
i'm having trouble reproducing this now, going to close and investigate more.

**Comment by liuzhen** [comment]
Also has same problem here, restarting the task (through UI) would register it as expected.
