### ISSUE TITLE
Docker auth from docker config

### ISSUE THREAD

**Issue by jbardin** [hashicorp/nomad#660]
I know secrets management is forthcoming, but it would also be nice if nomad could get docker auth from the default docker config files. 

The client could just attempt to call [NewAuthConfigurationsFromDockerCfg](https://godoc.org/github.com/fsouza/go-dockerclient#NewAuthConfigurationsFromDockerCfg). 

I'm trying to get nomad to pull images from an [AWS ECR](https://aws.amazon.com/ecr/), which requires obtaining a new auth password from the API every 12 hours. The CLI command `aws ecr get-login` returns a `docker login` command to be eval'ed in the shell, which in turn is written to `~/.docker/config.json`.

**Comment by jaygorrell** [comment]
Why was this closed? ECR doesn't behave like a standard private registry as the referenced PRs deal with.
