### ISSUE TITLE
Long logs doesn't fit into screen 

### ISSUE THREAD

**Issue by VBelozyorov** [hashicorp/nomad#6600]
I'm sorry for not following full bugreport procedure, but it will be short report. Somebody who knows codebase better, easily can check if this issue correct for current version or not.

So, we have log viewer in web interface:
![image](https://user-images.githubusercontent.com/860208/67956917-e21b8080-fc05-11e9-8e53-0607bccf93f1.png)
Some log strings was pretty long and control buttons (`Head`, `Tail`) are leaked outside of the screen

I'm going to quick fix it with custom CSS: `max-width: 83vw;` for `pre.cli-window` element:

![image](https://user-images.githubusercontent.com/860208/67957533-d3819900-fc06-11e9-8390-86da112bf24b.png)

P.S. Browser is Firefox 69.0.3

**Comment by DingoEatingFuzz** [comment]
This has since been fixed. Verified in 0.11.x and 0.12.0.
