### ISSUE TITLE
Connect with custom docker network ?

### ISSUE THREAD

**Issue by err0r500** [hashicorp/nomad#6601]
# Nomad version
Nomad v0.10.0 (25ee121d951939504376c70bf8d7950c1ddb6a82)

### Operating system and Environment details
Ubuntu/bionic64 running on Vagrant

### Reproduction steps

given a docker network created like so 
```
 sudo docker network create monitoring --subnet=172.18.0.1/24
```
### Job file (if appropriate)
this job is unreachable (I receive a `503` code) via Consul Connect

```
job "echo" {
  datacenters = ["dc1"]
  type = "system"

  group "echo" {
    network {
      mode = "bridge"
    }

    service {
      name = "echo"
      port = "5678"
      connect {
        sidecar_service {}
      }
    }

    task "echo" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo"
        args = ["--text", "\"hello\""]
        ipv4_address = "172.18.0.2"
        network_mode = "monitoring"
      }
    }
  }
}
```

but works fine if I remove the `ipv4_address` and `network_mode` fields.

## Details
Every health check pass on Consul and the job ups without any problem on Nomad

**Comment by nickethier** [comment]
Hey @err0r500 

Nomad's shared alloc networking (essentially `mode = "bridge"`) sets the docker networking mode. By setting the network_mode field you're overriding the network namespace for that task and it will no longer be shared with the connect sidecar.

In the next major release we plan to support CNI network modes to allow for custom network configuration for the alloc network.

Today this is not a supported configuration however. Apologies for the confusion.
