### ISSUE TITLE
Invert/negate set_contains constraint

### ISSUE THREAD

**Issue by otto-dev** [hashicorp/nomad#6610]
It would be great if it was possible to negate the `set_contains` constraint, i.e. `set_contains_not`.

For example: I have one `server` and many `workers`. The servers are tagged in the metadata. Now I want to run a job on all nodes NOT tagged as `server`, i.e. on all worker instances, like so:

```
constraint {
  attribute = "..."
  operator  = "set_contains_not"
  value     = "server"
}
```

Currently such an operator does not exist, even though most other operators can be inverted. In some cases this ability would make maintenance easier, for example, in regard to roles you have to maintain which roles are the inverse of other roles, and which roles are unrelated to other roles. Having an operator `set_contains_not` would solve this

**Comment by tgross** [comment]
Hi @otto-dev and thanks for opening this issue!

For the specific example you have here where's there's one specific value you don't want, could you use the `!=` operator like this?

```hcl
constraint {
  attribute = "..."
  operator = "!="
  value = "server"
}
```

**Comment by otto-dev** [comment]
Yeah from the top of my head I think I could make that work by transforming the list of roles `["a", "b"]` into a map of `{"a": true, "b": true}`. Thanks

**Comment by tgross** [comment]
Great! Glad that can work for you.
