### ISSUE TITLE
Allow passing of docker arguments via docker driver

### ISSUE THREAD

**Issue by otto-dev** [hashicorp/nomad#6611]
You can pass [`args`](https://www.nomadproject.io/docs/drivers/docker.html#args) to the process running inside the docker container, but you can't pass any arguments to `docker` itself, except what is abstracted away in the configuration.

But not every command line argument of docker is abstracted away in the configuration. Sometimes it is necessary to make use of features that do not have a configuration parameter.

One example of this is `--user UID` if I want to run the docker container as a specific user. I think this is currently not possible. Please let me know if I'm missing something.

If there isn't anything speaking against this, then I think this is a fairly basic request. It's nice if there is a configuration parameter, but fundamentally it should be possible to fall back on manual command-line arguments, so you are not boxed in by the parameters that have been implemented so far. Otherwise using the `docker` driver comes at a significant cost.

**Comment by nickethier** [comment]
Hi @otto-dev 
Nomad doesn’t use the docker cli. It instead talks directly to dockers api. Setting the user can be done directly in the task block of your job spec. See the docs here: https://www.nomadproject.io/docs/job-specification/task.html#user

**Comment by otto-dev** [comment]
Fantastic, and makes sense, thanks

**Comment by jalbertcruz** [comment]
What about the `--cgroup-parent` option?, is there any way of using it?

**Comment by tgross** [comment]
Hi @jalbertcruz! That's not a currently supported option in the Docker task driver's `config`. But you can set the value for all containers on a given node using the same flag passed to `dockerd`'s configuration.

**Comment by jalbertcruz** [comment]
Hi @tgross, yes, I know but I am trying to sell Nomad to my boss and a winning point would be to be able to use different cgroups in the same host.

**Comment by tgross** [comment]
Yup, understood. Can you open a new issue asking for that option to be added?

**Comment by analytically** [comment]
Same goes for --oom-score-adj
