### ISSUE TITLE
Log streaming for rkt driver

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#664]
Work for streaming logs is currently in progress in - https://github.com/hashicorp/nomad/tree/f-task-log-streaming

We haven't implemented any log streaming for the rkt driver. What would be the ideal way to retreive logs from rkt containers? Since rkt is so coupled with systemd, I would imagine we would use journald?

cc/ @achanda

**Comment by achanda** [comment]
`rkt` sends logs to stdout and stderr by default. In the case `rkt` is running under `systemd`, it also sends the logs to `journald`. So, for reading a `rkt` pod's logs, we should read the calling process' logs. 

https://github.com/coreos/rkt/blob/019f36a85c908c721570d67f317dbe5a47930547/Documentation/commands.md

**Comment by diptanu** [comment]
@achanda How is the stdout and stderr configured with rkt? Are they being controlled by the driver?

**Comment by achanda** [comment]
@diptanu the driver does have a reference to the calling process. It should be able to access the process' stdout and stderr using the handle. However, I noticed that all the other drivers have moved to `github.com/hashicorp/nomad/client/driver/executor` for executing binaries. I will work on moving `rkt`. Once that is complete, the call to get logs from it should look like
```
func (h *execHandle) Logs(w io.Writer, follow bool, stdout bool, stderr bool, lines int64) error {
    return h.cmd.Logs(w, follow, stdout, stderr, lines)
}
```
I can get this to work once #678 is merged

**Comment by diptanu** [comment]
@achanda rkt shouldn't use executor, executor is for drivers which needs Nomad to provide isolation. Drivers like Docker, rkt, etc provides isolation themselves so they don't need the executor.

**Comment by achanda** [comment]
@diptanu do you think executor can be used without setting any resource limits? The other way to implement this would be to use the rkt api service once https://github.com/coreos/rkt/issues/1970 is resolved. Currently, it is targeted for next release.

**Comment by dadgar** [comment]
This isn't relevant anymore as that PR has been closed, and rkt is using the executor.
