### ISSUE TITLE
[api]: MonitorDrain closes channel due to blocking query timeouts, not drain timeout

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/nomad#6645]
### Nomad version
0.8.6

### Operating system and Environment details

Ubuntu 16

### Issue

[api.MonitorDrain](https://godoc.org/github.com/hashicorp/nomad/api#Nodes.MonitorDrain) closes the returned channel before the drain has been completed. I believe this behavior is unexpected given the existing documentation:

> The channel will be closed when all allocations on the draining node have stopped or the context is canceled.

### Reproduction steps

1. Trigger a drain using the [Golang API](https://godoc.org/github.com/hashicorp/nomad/api#Nodes.MonitorDrain):

```go
meta, err := nomadAPI.Nodes().UpdateDrain(node.ID, conf, false, nil)
if err != nil {
    return errors.Wrap(err, "could not drain node")
}

eventChan := nomadAPI.Nodes().MonitorDrain(ctx, node.ID, meta.LastIndex, true)
for evt := range eventChan {
    log.Printf("[DEBUG] monitoring drain: %s", evt.String())
}
```

2. If any jobs are still running (these are usually batch jobs), the last log you will see before the channel is closed will be something like:

```
Error monitoring node: Get https://nomad.service.consul/v1/node/b69e4a1e-5725-3d09-7725-cfca132ceadc?index=129339844&stale=: EOF
```

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Hi @Xopherus and thanks for opening this issue!  It looks like this may be a docstring error. If I look at [`api/nodes.go#L196-L199`](https://github.com/hashicorp/nomad/blob/c078bb6379c4ac03276d8b9fa7a9dbb57c194d5a/api/nodes.go#L196-L199) we can see that this should probably read:

> The channel will be closed when all allocations on the draining node have stopped, when an error occurs, or the context is canceled.

It looks like the behavior is correct -- at this point we're not going to get any more information about the node or its allocations, so we should give up. So we need to update the docstring here. If you want to open a PR I'd be happy to review it and get it merged. Otherwise, I'll make that fix shortly.

**Comment by Xopherus** [comment]
Thanks for the reply @tgross. I get that from an API perspective it makes sense to close the channel on an error, but from an operator perspective it is a little odd that `MonitorDrain` will inevitably close with an error if there is ANY batch job which runs for longer than the default blocking query timeout (which is 60s I believe?). 

Fortunately I was able to get around this by simply calling MonitorDrain again and again until the drain timeout is reached. I assume that the cli command for draining probably does something similar?

I'd be happy to put in a fix to the docs if that helps take it off your plate.

**Comment by tgross** [comment]
Thanks @Xopherus. I checked on the CLI, and the CLI sets a one hour drain deadline by default but pulls on the `MonitorDrain` channel without retries.

**Comment by Xopherus** [comment]
Interesting. If I have a batch job which is running during a drain, if the monitor gets to a spot where there's no new activity it just waits for up to a minute before exiting with that error. I guess that the drain CLI command may also exit with the same error under the same conditions? 

Again, it's not necessarily a problem for that function itself to return an error - but I would think the CLI command *would not* want to exit in that situation. If you were relying on that call to block until the drain is complete / timed out. I think I would rather Nomad forcefully kill any stragglers before AWS does, for example.

**Comment by tgross** [comment]
Just so that I'm understanding correctly, based on the behavior you're seeing with the API, you're expecting that in the node drain below to exit with an error after 5 minutes (the default blocking query timeout), rather than succeeding after 10 minutes as it does here?

```
▶ nomad node drain -deadline 10m -enable ddca0ede
Are you sure you want to enable drain mode for node "ddca0ede-652c-6828-0794-e5a719b99fcb"? [y/N] y
2019-11-12T08:28:36-05:00: Ctrl-C to stop monitoring: will not cancel the node drain
2019-11-12T08:28:36-05:00: Node "ddca0ede-652c-6828-0794-e5a719b99fcb" drain strategy set
2019-11-12T08:38:37-05:00: Drain complete for node ddca0ede-652c-6828-0794-e5a719b99fcb
2019-11-12T08:38:37-05:00: Alloc "8cb46fa0-fec6-3957-f52d-064b1fa9c928" marked for migration
2019-11-12T08:38:37-05:00: Alloc "8cb46fa0-fec6-3957-f52d-064b1fa9c928" draining
2019-11-12T08:38:43-05:00: Alloc "8cb46fa0-fec6-3957-f52d-064b1fa9c928" status running -> complete
2019-11-12T08:38:43-05:00: All allocations on node "ddca0ede-652c-6828-0794-e5a719b99fcb" have stopped.
```

My test job was:

```hcl
job "test" {
  datacenters = ["dc1"]

  type = "batch"

  group "test" {
    task "test" {
      driver = "docker"

      config {
        image = "busybox:1"
        command = "sleep"
        args = ["36000"]
      }
    }
  }
}
```

It might help if you could provide a code snippet of how you're configuring your API client here.

**Comment by Xopherus** [comment]
Sorry for the ambiguity, let me see if I can explain what's going on. I'm using AWS lifecycle hooks in order to drain nomad clients before they are terminated by AutoScaling. Here's the code snippet I've got to facilitate the drain:

```go
// ctx.Deadline() is the lambda function timeout (15 minutes)
deadline, _ := ctx.Deadline()
conf := &api.DrainSpec{
    Deadline: time.Until(deadline.Add(-3 * time.Minute)),
}

// enable drain
meta, err := c.nomadAPI.Nodes().UpdateDrain(node.ID, conf, false, nil)
if err != nil {
    return errors.Wrap(err, "could not drain node")
}
log.Printf("[DEBUG] drain started on node %s", addr)

// confirm node is drained of allocations
for {
    eventChan := c.nomadAPI.Nodes().MonitorDrain(ctx, node.ID, meta.LastIndex, true)

    // if drain returns an error and closes the channel, continue trying
    var drainError *api.MonitorMessage

    for evt := range eventChan {
        drainError = nil

	if evt.Level == api.MonitorMsgLevelError {
	    drainError = evt
	}
	log.Printf("[DEBUG] monitoring drain: %s", evt.String())
    }

    if drainError == nil {
        return hooks.CompleteLifecycle(asgsvc, data)
    }
    log.Printf("[DEBUG] monitor closed channel with error: %s", drainError.String())
}
```

And here are the logs I'm seeing:
[nomad-drain.log](https://github.com/hashicorp/nomad/files/3837982/nomad-drain.log)

From what I can tell, draining works fine up until a point where its waiting for allocs to finish. It then gets into a cycle where MonitorDrain continually exits with an EOF error. It repeats that it hits the drain timeout, which is about 12 minutes. At that point MonitorDrain finishes due to context timeout, so no error is returned - and the code can safely exit.
