### ISSUE TITLE
fail to specify several connect stanzas per group

### ISSUE THREAD

**Issue by err0r500** [hashicorp/nomad#6646]
### Nomad version
Nomad v0.10.1 (829f9af35c77d564b3dab74454eeba9bf25e2df8)

### Operating system and Environment details
ubuntu bionic

### Issue
Fail to specify several connect stanza per group

### Reproduction steps
submit the job below (it passes the validation) and you'll receive this error :
```
failed to setup alloc: pre-run hook "group_services" failed: invalid Consul Connect configuration for service "tcp": No Connect port defined for service "tcp"
```

### Job file (if appropriate)
```
job "activemq" {
  datacenters = ["dc1"]

  group "activemq" {
    network {
      mode = "bridge"
    }

    service {
      name = "activemq-web"
      port = "8161"
      connect {
        sidecar_service {}
      }
    }

    service {
      name = "tcp"
      port = "61616"
      connect {
        sidecar_service {}
      }
    }

    service {
      name = "stomp"
      port = "61613"
      connect {
        sidecar_service {}
      }
    }

    task "activemq" {
      driver = "docker"

      config {
        image = "webcenter/activemq"
      }
    }
  }
}
```

**Comment by nickethier** [comment]
Hey @err0r500 I was able to reproduce this and should have a fix shortly. Thanks for reporting!

**Comment by sibblegp** [comment]
Hello! I pasted this directly into Nomad and the connect proxies won't start with a "Base ID" error. Running Nomad 0.10.2 and Consul 1.6.2. This is preventing us from moving forward. Would love some help. Thanks!

**Comment by kneufeld** [comment]
I just wanted to say thanks for fixing this bug, I was running `0.10.1` when I hit it and was about to lose my mind but a quick upgrade and I'm all good. I ❤️ the hashi stack.
