### ISSUE TITLE
constraints plus canary equals failed allocations

### ISSUE THREAD

**Issue by kneufeld** [hashicorp/nomad#6663]
I'm not sure if this is really a bug or I'm doing something wrong or I just have unrealistic expectations...

My situation is that I have 2 datacenters, I want to run two instances of a process (`ipmi_exporter`) in each dc for a total of four. The following works fine.

```hcl
job "ipmi-exporter" {

  datacenters = ["west", "east"]

  type = "service"

  group "ipmi-exporter" {
    count = 4

    constraint {
        distinct_property = "${node.datacenter}"
        value     = "2"
    }
```

However, if I say I want a `canary`

```hcl
    update {
      canary            = 1
      auto_promote      = true
      auto_revert       = true
      max_parallel      = 1
      min_healthy_time  = "10s"
      healthy_deadline  = "1m"
      progress_deadline = "2m"
    }
```

Then creating a canary would make 3 instances which violates my constraint so the allocation fails with

```
Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "ipmi-exporter" (failed to place 1 allocation):
    * Constraint "distinct_property: ${node.datacenter}=west used by 2 allocs" filtered 4 nodes
    * Constraint "distinct_property: ${node.datacenter}=east used by 2 allocs" filtered 3 nodes
```

which is pretty reasonable.

I'm aware of `affinity` but it doesn't allow `distinct_property` so what to do?

Running `Nomad v0.10.0`

**Comment by tgross** [comment]
Hi @kneufeld! Yeah, as you've noted having a constraint of `distinct_property` isn't a good fit for deployments with canaries. What I would recommend in this scenario is to have two task groups in the same job, with the `affinity` stanza for each DC but otherwise the same definition. Something like:

```hcl
job "ipmi-exporter" {

  datacenters = ["west", "east"]
  type = "service"

  group "ipmi-exporter-west" {
    count = 2
    constraint {
        affinity = "${node.datacenter}"
        value     = "west"
    }
    update {
        canary = 1
        /* etc */
    }
  }

  group "ipmi-exporter-east" {
    count = 2
    constraint {
        affinity = "${node.datacenter}"
        value     = "east"
    }
    update {
        canary = 1
        /* etc */
    }
  }
}
```

That should let you deploy as a single job but maintain separate sets of canaries by having the `update` stanza under the group and not the job.

**Comment by kneufeld** [comment]
Thanks for the reply, I guess I'll warm up the old copy/paste keys.

**Comment by cosmotek** [comment]
Im trying to solve for another case here. Basically we need to force Nomad to use district hosts (networking related), and we can't schedule a canary given we're already running three tasks on three hardware nodes.
