### ISSUE TITLE
Nomad node draining migration issue

### ISSUE THREAD

**Issue by noteits** [hashicorp/nomad#6667]
### Nomad version
Nomad v0.9.5

### Operating system and Environment details
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

Nomad Cluster has 3 nodes and another Cluster has 1 node. Tried on both.

## Issue
An issue with node draining and migration stanza.
Nomad does not respect min_healthy_time or max_parallel option.

### Reproduction steps
1 nomad server
2 nomad jobs with count = 2
2 nomad client nodes, all allocations are on node 1
We drain node 1.
All 4 allocations are transitioned to state complete and moved to be started on node 2 instead of executing migration one by one. 

### Job file (part of it)

  update {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "<%= @update_min_healthy_time %>"
    healthy_deadline = "<%= @nomad_interval %>"
    progress_deadline = "<%= @progress_interval %>"
    auto_revert      = false
    canary           = 0
  }
  migrate {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "<%= @update_min_healthy_time %>"
    healthy_deadline = "<%= @nomad_interval %>"
  }

### Nomad Server logs (if appropriate)
One job with count 2 migrated immediatelly.
2019-10-31T16:59:45Z: Alloc "596554ec-8b69-872b-97e4-4eb3f2deb62f" marked for migration
2019-10-31T16:59:45Z: Alloc "596554ec-8b69-872b-97e4-4eb3f2deb62f" draining
2019-10-31T16:59:45Z: Alloc "596554ec-8b69-872b-97e4-4eb3f2deb62f" status running -> complete
2019-10-31T16:59:46Z: Alloc "9e43e1d9-c317-9b03-1d7e-a13b737a2ee2" marked for migration
2019-10-31T16:59:46Z: Alloc "9e43e1d9-c317-9b03-1d7e-a13b737a2ee2" draining
2019-10-31T16:59:46Z: Alloc "9e43e1d9-c317-9b03-1d7e-a13b737a2ee2" status running -> complete

The same issue described here https://github.com/hashicorp/nomad/issues/4589
But it was closed and didn't fixed or not explained what was done.

Can someone recommend something? The same behavior is with migrate stanza and without it.

**Comment by noteits** [comment]
Hi @tgross You marked this ticket as needs_investigation. What is the next step?
Thanks.  :)

**Comment by tgross** [comment]
Hi @noteits! That just means we've identified the issue as something that needs triage and need to get someone on our team to look into it further.

**Comment by noteits** [comment]
Thank you so much! I’ll wait.

**Comment by drewbailey** [comment]
Hi @noteits I've tried running this a few times with the following job file and have been unable to reproduce this issue. Are you able to consistently get this to happen? Do you mind sharing more of the job file and the templated variables in them?

<details>
<summary>job file</summary>

```hcl
job "web" {
  datacenters = ["dc1"]
  type        = "service"

  update {
    max_parallel      = 1
    min_healthy_time  = "20s"
    healthy_deadline  = "4m"
    progress_deadline = "10m"
    auto_revert       = false
    canary            = 0
  }

  migrate {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "50s"
    healthy_deadline = "15m"
  }

  affinity {
    attribute = "${meta.tag}"
    value     = "foo"
    weight    = 100
  }

  group "group" {
    count = 2

    task "server" {
      env {
        HTTP_PORT = "${NOMAD_PORT_http}"
      }

      driver = "docker"

      config {
        image = "drewbailey/simple-server:1"
      }

      resources {
        network {
          mbits = 10
          port  "http"{}
        }
      }

      service {
        name = "demo-webapp"
        port = "http"

        check {
          type     = "http"
          path     = "/healthcheck"
          interval = "2s"
          timeout  = "2s"
        }
      }
    }
  }
}

```
</details>
