### ISSUE TITLE
Set OOMScoreAdjust=-1000

### ISSUE THREAD

**Issue by analytically** [hashicorp/nomad#6672]
The default systemd configuration for Nomad should set OOMScoreAdjust=-1000 to avoid OOMing the Nomad process.

**Comment by tgross** [comment]
Hi @analytically and thanks for submitting this! I'd be happy to get a submission from you reviewed for this if you're up to contributing it. Otherwise we'll update that unit file in the near future.

Ref https://github.com/hashicorp/nomad/blob/master/dist/systemd/nomad.service

**Comment by ianic** [comment]
When using exec driver binary started with it inherits oom_score_adj setting from the parent process (nomad).
That prevents kernel from killing that binary in the case of oom!
Kernel panics with "Out of memory and no killable processes...".

From syslog (my binary name is canary):
```
Oct 12 14:06:28 local kernel: [  396.222626] Tasks state (memory values in pages):
Oct 12 14:06:28 local kernel: [  396.222627] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Oct 12 14:06:28 local kernel: [  396.222628] [  21636] 65534 21636   178572     3712   139264        0         -1000 canary
Oct 12 14:06:28 local kernel: [  396.222629] Out of memory and no killable processes...
Oct 12 14:06:28 local kernel: [  396.223493] canary invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=-1000
```


There is a workaround to use something like:
```
      driver = "exec"
      config {
        command = "/bin/sh"
        args = [
          "-c", "/usr/bin/echo 0 >  /proc/$$/oom_score_adj; exec /bin/canary",
        ]
      }
```
to reset oom_score_adj before running binary.
But it is hacky. Plain job definition is much cleaner:
```
      driver = "exec"
      config {
         command = "/bin/canary"
      }
```
