### ISSUE TITLE
nomad sidecar documentation

### ISSUE THREAD

**Issue by kneufeld** [hashicorp/nomad#6733]
### Nomad version

Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)

### Issue

I found the documentation and the example at https://www.nomadproject.io/guides/integrations/consul-connect/index.html to be very confusing. So after figuring it out I did what I did last time (https://www.burgundywall.com/post/consul-connect) and wrote a blog post about it.

https://www.burgundywall.com/post/nomad-sidecars

Feel free to plagiarize without attribution if that helps your documentation.

**Comment by tgross** [comment]
Thanks @kneufeld !

**Comment by tgross** [comment]
Doing a little issue cleanup, and the post discussed here doesn't seem to be available anymore. We've done a lot of recent work on the Connect docs, including troubleshooting guides. I'm going to close this issue out.
