### ISSUE TITLE
make e2e metrics test clean itself up

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#6742]
The e2e tests for metrics don't get run regularly because they have side-effects and don't clean themselves up. This issue is to update the tests so that they can be run by default as part of the nightly e2e testing.

```go
var metrics = flag.Bool("metrics", false, "run metrics tests")
...

// TestMetrics runs fabio/prometheus and waits for those to succeed
// After that a series of jobs added to the input directory are executed
// Unlike other e2e tests this test does not clean up after itself.
// This test is meant for AWS environments and will not work locally
func TestMetrics(t *testing.T) {
	if !*metrics {
		t.Skip("skipping test in non-metrics mode.")
	}
```

**Comment by tgross** [comment]
Might want to look at https://github.com/hashicorp/nomad/pull/6771 for an example of what could be done to reduce test cross-contamination in metrics.

**Comment by notnoop** [comment]
We can probably get more isolation by setting a new global metrics sink through [`metrics.NewGlobal`](https://godoc.org/github.com/armon/go-metrics#NewGlobal) .  We can do it for every tests, or just for the relevant tests with assertions on metrics, as it impacts allowed test parallelism.

It seems we are stuck with using the global metrics sink.  Few vendored libraries (e.g. raft, serf, memberlist) use the global metrics sink and changing them complicates their apis and too burdensome just for the benefit of our testing story imo.

**Comment by tgross** [comment]
When I dug into this, I discovered it wasn't a question of polluting the metrics contents in E2E, but that the test had never been wired up into the E2E framework so there was no cleanup of the jobs when we were done. Done in #6842
