### ISSUE TITLE
Rolling cluster upgrade of nomad with "upgrade" command

### ISSUE THREAD

**Issue by altosys** [hashicorp/nomad#6743]
[FEATURE REQUEST]

It would be great to have an 'upgrade' command in the nomad binary to trigger a rolling upgrade of servers, clients or both present in the cluster, possibly with optional filters to target specific nodes.

This would largely deprecate the need to use a tool like ansible to upgrade nomad in clusters and since nomad could leverage the raft protocol status it would have a great way of checking the cluster state between each binary upgrade in order to keep the cluster up and healthy.

Having no idea if this is possible to do internally from the nomad binary, suggested usage could be something like this:

upgrade to latest stable version:
`nomad upgrade servers`
`nomad upgrade clients`
`nomad upgrade all`

upgrade to specific version:
`nomad upgrade servers v0.10.1`

set number of simultaneously upgraded clients in rollout
`nomad upgrade clients v0.10.1 --parallell 2`

upgrade specific datacenter
`nomad upgrade clients v0.10.1 --datacenter dc1`

upgrade specific running version
`nomad upgrade clients v0.10.1 --running v0.9.0`

upgrade specific os, metadata, etc.
`nomad upgrade clients v0.10.1 --os linux`
`nomad upgrade clients v0.10.1 --meta 'upgrademe'`
`nomad upgrade clients v0.10.1 --name node1`
`nomad upgrade clients v0.10.1 --class nodeclass`

**Comment by mikenomitch** [comment]
I think this is broadly a good idea, but I don't think this specific implementation makes sense. Having this be part of the Nomad binary itself seems kind of wrong. The responsibility for starting Nomad/versioning/etc would move into the Nomad binary, which could make it less flexible in the future, and increase the scope of what `nomad` does.

I do think being more prescriptive about how to do this, and adding/sharing tools to help with these exact workflows is a good idea though. Even so, I'll close this Issue as we won't be adding them into Nomad proper.
