### ISSUE TITLE
System API commands for cli

### ISSUE THREAD

**Issue by tommyalatalo** [hashicorp/nomad#6747]
[FEATURE REQUEST]

It would be good to be able to trigger garbage collection in a cluster manually using a command in the nomad binary. There are only two "system" api endpoints which would be convenient to have handy in the cli tool to avoid the need for curl or using a ui.

Suggested command could be something like:

`nomad system garbage-collect` 
`nomad system collect` (or "clean"?)
`nomad system gc`

`nomad system reconcile-summaries`
`nomad system reconcile`
`nomad system rs`

I guess some though needs to be put into command names that are short but descriptive, the above not being the greatest examples. In any case I imagine you would end up with a new top level command "system" with two subcommands.

**Comment by tgross** [comment]
Hi @tommyalatalo! We'll mark this as an enhancement.

**Comment by tommyalatalo** [comment]
> Hi @tommyalatalo! We'll mark this as an enhancement.

I can only agree :)
