### ISSUE TITLE
Variable Interpolation not working in group level service

### ISSUE THREAD

**Issue by liujingchen** [hashicorp/nomad#6756]
### Nomad version
Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)

### Operating system and Environment details
Ubuntu 18.04
Consul v1.6.1

### Issue
The variables in task group level service stanza are not interpolated. 

### Reproduction steps
Use this job file:
```
job "countdash" {
  datacenters = ["dc1"]

  group "api" {
    network {
      mode = "bridge"
    }

    service {
      name = "count-api"
      port = "9001"
      tags = [
	"test-${node.datacenter}", 
	"test2-${NOMAD_JOB_NAME}"
      ]

      connect {
        sidecar_service {}
      }
    }

    task "web" {
      driver = "docker"

      config {
        image = "hashicorpnomad/counter-api:v1"
      }
    }
  }
}
```
It is from [the example of Consul Connect](https://www.nomadproject.io/guides/integrations/consul-connect/index.html). The service has tags with node attributes and runtime environment variables inside.
Submit the job to Nomad, and see Consul's output of the serivce:
```
:~$ curl -s http://localhost:8500/v1/catalog/service/count-api | jq
[
  {
    "ID": "0fbd275f-5d3d-3fb4-1e8a-55797b730f91",
    "Node": "******",
    "Address": "******",
    "Datacenter": "*******",
    "TaggedAddresses": {
      "lan": "*****",
      "wan": "******"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-bb1c1d43-3552-4506-57e4-7191f476ac40-group-api-count-api-9001",
    "ServiceName": "count-api",
    "ServiceTags": [
      "test-${node.datacenter}",
      "test2-${NOMAD_JOB_NAME}"
    ],
    "ServiceAddress": "******",
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {
      "external-source": "nomad"
    },
    "ServicePort": 9001,
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "MeshGateway": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 2150558,
    "ModifyIndex": 2150558
  }
]
```
You can see in "ServiceTags", the two variables are not properly interpolated.

**Comment by tgross** [comment]
Hi @liujingchen! This is a known issue in 0.10.0-0.10.1 which we've tracked in #6272. But fortunately it's been fixed by https://github.com/hashicorp/nomad/pull/6586 and you should see this patch come out in the upcoming 0.10.2 release very soon!

**Comment by liujingchen** [comment]
Great, thanks! Looking forward to the new version!
