### ISSUE TITLE
The rkt driver is broken

### ISSUE THREAD

**Issue by achanda** [hashicorp/nomad#677]
The `rkt` driver has been broken for some time now. I saw this earlier today while working on the volume mount feature. I have fixed it and will open a PR soon enough. Also, I will work on having more test coverage on the drivers in CI.

**Comment by dadgar** [comment]
Hey, would appreciate if this issue could be filled out with what is broken so it can be fixed and tested properly so there aren't regressions.

**Comment by achanda** [comment]
There were two issues about the task and alloc directories not being created and wrong parameters in volume mount. Those are fixed here https://github.com/achanda/nomad/tree/b-rkt
The issue I am debugging now is that `Open` crashes. I noticed that when I exec the `rkt` binary, the calling process exits even when the container is running. Later, when a caller tries to find the process using it's pid, it gets back nil.

**Comment by achanda** [comment]
Closing since tests are consistently passing
