### ISSUE TITLE
question: nomad ui / https

### ISSUE THREAD

**Issue by thr27** [hashicorp/nomad#6783]
Is it possible to configure nomad to run web ui using SSL and certificate ?

I only found how to secure API with TLS

More and more web browsers enforce the usage of https (chrome and sticky HSTS rules e.g.) 

Thanks

**Comment by shantanugadgil** [comment]
for now its not possible, though, I think this would be quite a nice feature enhancement, to be able to specify the "cert" and "key" for the UI on the command line/config parameters.

I think the current method is to put the Nomad servers behind a proxy/loadbalancer like NGINX/HAProxy (which would have the auth/SSL in it)

**Comment by notnoop** [comment]
The Nomad web ui is secured with tls when the `tls.http` is enabled [1]; you don't need to do any additional steps if have secured the api.

You must ensure that the tls cert is configured with ip address and domain names that are used by users.

I'm closing this ticket, but we can re-open if you report a bug or an issue preventing you from it.


[1] https://www.nomadproject.io/docs/configuration/tls.html#http
