### ISSUE TITLE
log_file  "unexpected keys log_file"

### ISSUE THREAD

**Issue by kereza** [hashicorp/nomad#6793]
## Nomad version
[root@]# nomad -v
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)

### Operating system and Environment details
[root@]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

### Issue
Nomad does not start when the option log_file is set
https://www.nomadproject.io/docs/configuration/index.html#log_file

### Job file (if appropriate)
[root@]# cat /etc/nomad.d/config.hcl
bind_addr = "0.0.0.0"
leave_on_interrupt = "true"
datacenter = "test-1"
log_json = true
log_file = "/var/log/nomad/nomad.log"

data_dir  = "/var/lib/nomad"

acl {
  enabled = true
  token_ttl = "30s"
  policy_ttl = "60s"
}

consul {
  address = "127.0.0.1:8500"
  token   = "asas-asasasa-asasasa-asasas"
}

vault {
  enabled     = true
  cert_file   = "/etc/pki/hashicorp/wildcard.service.consul.crt"
  key_file    = "/etc/pki/hashicorp/wildcard.service.consul.key"
  address     = "https://vault.service.consul:8200"
  token       = "qwqwqwqwqwqwwqwqwqw"
  create_from_role = "nomad-cluster"
}

server {
  enabled          = true
  bootstrap_expect = 3
  encrypt = "qwqwqwqwq"
}

### Nomad Server logs (if appropriate)
Dec  3 16:26:26 ip-10-4-5-80 nomad[23911]: ==> Error loading configuration from /etc/nomad.d: Error loading /etc/nomad.d/config.hcl:  unexpected keys log_file
Dec  3 16:26:26 ip-10-4-5-80 systemd[1]: nomad.service: main process exited, code=exited, status=1/FAILURE
Dec  3 16:26:26 ip-10-4-5-80 systemd[1]: Unit nomad.service entered failed state.
Dec  3 16:26:26 ip-10-4-5-80 systemd[1]: nomad.service failed.
Dec  3 16:26:26 ip-10-4-5-80 systemd[1]: nomad.service holdoff time over, scheduling restart.
Dec  3 16:26:26 ip-10-4-5-80 systemd[1]: Stopped Nomad is a single binary that schedules

**Comment by notnoop** [comment]
I'm afraid that `log_file` is only supported starting from Nomad 0.10.2 (in RC period with final release due today).  I'm sorry that we didn't indicate minimum version and caused this confusion.  I'll raise internally the need for versioned documentations.

**Comment by shantanugadgil** [comment]
@notnoop do you mean versioned documents like Perl? How about a note which says `introduced in version: A.B.C` in front of new parameters.
That way folks visiting documentation see in a single glance what new parameters/options they are missing out on. :)

**Comment by kereza** [comment]
Got it, thanks for the info. That means we will upgrade :D.
