### ISSUE TITLE
Consul-template as Nomad job?

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#680]
Hello,

For me, it makes sense to run Hashicorp's `consul-template` daemons with Nomad (`driver=raw_exec`), because it's easier to schedule them in Nomad by selecting hosts with `constraints`, etc.

I'd like them to be registered in Consul as services (or checks?) too, so I can verify all my consul-templates are generating the final files I need. Since consul-template is just an app which doesn't listen on a tcp/udp port, is it possible to register them as a service without having a port?

If this doesn't make sense for you, any better idea to manage consul-template the easy way?

Thank you in advance guys!

**Comment by adrianlop** [comment]
Hi again,

I'm gonna close the issue, since I made it work with `cron`, so it runs `consul-template` with the `-once` and `-syslog` flags every minute. This way, I can get warns/errors from syslog and stream them to our ELK centralized logging.

Anyway, if you have a better way of doing this, please don't hesitate and share with us :)

**Comment by diptanu** [comment]
@adrianlop The only thing I would  say here is that you might want to run the consul template daemons along with the actual tasks for which the configuration they would generate. So make a task group with one of the tasks being the consul daemon and the other task being the service itself. This will assure that the consul template jobs are always guaranteed resources where your actual tasks  are running. Does that makes sense?

**Comment by adrianlop** [comment]
@diptanu it makes perfect sense! elegant solution. I'll try it out. thanks :+1:

**Comment by c4milo** [comment]
@diptanu it sort of make sense, the problem I see is that consul-template won't be able to restart any individual task as Nomad does not support that.

**Comment by makeittotop** [comment]
@adrianlop Does the solution suggested by @diptanu work for you? If you could let me know, it'd be great because I'd like to implement something exactly similar and was wondering if consul-template daemon can be run efficiently with Nomad.

**Comment by dadgar** [comment]
@makeittotop We have built in consul-template support in recent versions of Nomad. See the template block: https://www.nomadproject.io/docs/job-specification/template.html

**Comment by makeittotop** [comment]
@dadgar I gave it a go and this works awesome! Thanks. 

Also I'm currently embedding the configuration file for the binary within the template which eventually will write the config to a path relative to <task>/local (instead of it's usual standard path) before the service gets bootstrapped. Is this an accepted way or you reckon there is a better, more efficient way of going about it?

**Comment by dadgar** [comment]
@makeittotop I am not sure what you mean instead of its usual standard path but yeah that definitely seems okay! The one thing to consider is if the template is becoming very large you may want to use an artifact to download it and separate the template from the job file.
