### ISSUE TITLE
Feature request: Fingerprinting of Azure metadata

### ISSUE THREAD

**Issue by josemaia** [hashicorp/nomad#6801]
Hello,

I saw that in the past there was a (closed without integrating) PR with some metadata exposed to the agent from Azure (https://github.com/hashicorp/nomad/pull/2682/files)

Is there any possibility of this feature being added to the nomad roadmap? I'm on Azure and I would appreciate having the possibility of using some of these for constraints.

**Comment by tgross** [comment]
Hi @josemaia! It looks like that PR was closed by the author as they weren't quite ready to submit it. 

But this would be a good feature and one that's reasonably self-contained; we're currently doing cloud provider fingerprinting in [`client/fingerprint/env_aws`](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/env_aws.go) and 
[`client/fingerprint/env_gce`](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/env_gce.go). I'll make sure this gets onto the roadmap.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/8979, and will ship in 0.13.
