### ISSUE TITLE
Switch from gometalinter to golangci-lint

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6812]
https://github.com/golangci/golangci-lint

Even https://github.com/alecthomas/gometalinter itself tells us to use golangci-lint instead. We should aim for at least the same level of checks as gometalinter provides:

https://github.com/hashicorp/nomad/blob/master/GNUmakefile#L170-L192

**Comment by endocrimes** [comment]
We ran into some issues with this last time we tried, namely increased memory usage: https://github.com/hashicorp/nomad/pull/6143

**Comment by schmichael** [comment]
Ah, thanks for the link @endocrimes. No clue how I didn't find that. We were actually hoping golangci-lint would _lower_ memory usage, so that's a bit concerning.

I believe we qualify for increased resource limits, so perhaps we should just contact Circle support: https://circleci.com/docs/2.0/configuration-reference/#job_name

**Comment by shoenig** [comment]
@endocrimes your changes seem to work now https://github.com/hashicorp/nomad/pull/6814 
Maybe they fixed something since then? It does seem faster, at least ~
