### ISSUE TITLE
“template” Stanza  after source change treat as a update of job 

### ISSUE THREAD

**Issue by Sea-Flying** [hashicorp/nomad#6821]
use `template` Stanza in `task`,  when source change , the behavior of the rendered template changes, as the `change_mode` parameter defines, options are `"noop"`, `"restart"` and `"signal"`, 
but if I want the template source changes trigger a `canary` update defined in `update` Stanza, I have no idea about it.

**Comment by tgross** [comment]
Hi @Sea-Flying! You're right that the `template` stanza doesn't support deployments (and therefore the `canary` stanza). It does support the `splay` field, which can at least reduce the risk of thundering herd during restarts.
