### ISSUE TITLE
[question] Template rendering destination other then local/alloc/secrets

### ISSUE THREAD

**Issue by zonnie** [hashicorp/nomad#6822]
I'm trying to use the `template` stanza and I need the rendering destination to be something like `/etc/logrotate.d/bla` - I'm unable to do that.

On one hand it is allowed by the Nomad API and the `inspect` shows the excepted result but in reality the task's Docker container doesn't contain the expected rendered file in `/etc/logrotate.d` (it's empty).

Is it possible to achieve the above somehow ?

Some Linux mechanisms are out of my control and I need configuration files in specific location inside the container.

Thanks !

**Comment by tgross** [comment]
Hi @zonnie! As you've discovered here, the [`destination`](https://www.nomadproject.io/docs/job-specification/template.html#destination) is always relative to the task directory.

One way of working around this when using the Docker task driver is to create a symlink in the image that points to the file you expect to be created by the template.


```Dockerfile
FROM busybox:1
RUN ln -s /local/file.txt /etc/rendered.txt
```

```hcl
job "templater" {
  datacenters = ["dc1"]

  group "groupname" {

    task "taskname" {

      driver = "docker"

      config {
        image = "myrepo/myexample:latest"

        command = "sleep"
        args = ["6000"]
      }

      resources {
        cpu    = 128
        memory = 128
      }

      template {
        data = <<EOF
myexample: template
EOF
        destination = "local/file.txt"
      }
    }
  }
}
```

In use:

```sh
▶ docker exec -it 7f7 /bin/sh
/ # ls /local
file.txt
/ # ls /etc
group         hosts         mtab          passwd        resolv.conf
hostname      localtime     network       rendered.txt  shadow
/ # cat /etc/rendered.txt
myexample: template
```
