### ISSUE TITLE
nomad (client) fails to launch with configuration error when systemd

### ISSUE THREAD

**Issue by MansM** [hashicorp/nomad#684]
I made an error in my nomad client configuration: 
(not putting docker endpoint in options)
client {
  enabled = true
    docker.endpoint = "tcp://{{ ansible_eth1['ipv4'].address }}:2376"
}

Nomad agent did start but stopped without giving any notion of what being wrong:
root@dockerserver2:~# systemctl status nomad
● nomad.service - Nomad
   Loaded: loaded (/etc/systemd/system/nomad.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2016-01-14 14:20:17 UTC; 37min ago
     Docs: https://nomadproject.io/docs/
 Main PID: 5128 (nomad)
   CGroup: /system.slice/nomad.service
           └─5128 /usr/bin/nomad agent -config /etc/nomad.d

Jan 14 14:20:17 dockerserver2 systemd[1]: Started Nomad.
Jan 14 14:20:17 dockerserver2 systemd[1]: Starting Nomad...
Jan 14 14:20:17 dockerserver2 nomad[5128]: Loaded configuration from /etc/nomad.d/nomad-client.hcl
Jan 14 14:20:17 dockerserver2 nomad[5128]: ==> Starting Nomad agent...

when using upstart it launches and gives some feedback. As systemd will be the future I think its useful to have nomad launch and return an error

**Comment by jrg72** [comment]
I definitely agree; I've been bit by this as well when there's a problem with the docker backend and nomad "starts" but just hangs forever in this instance, as above.

**Comment by dantoml** [comment]
Thanks for reporting this issue. In newer versions of Nomad, this now fails due to stricter config validation with:

```
==> Error loading configuration from config.hcl: Error loading config.hcl: error parsing 'config': 1 error(s) occurred:

* client -> invalid key: docker.endpoint
```
