### ISSUE TITLE
Nomad Monitor: Support for `server` only nodes.

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#6845]
### Nomad version

`Nomad v0.10.2`

### Issue

Currently, the `nomad monitor` command only supports streaming logs from _client_ agents, and not from Nomad server's. It also provides an unhelpful error (on 0.10.2 it panics, with #6828 it will return no node found, because we only look up clients).

It would be useful to expand this in the future to also allow for the inspection of Nomad Server logs.

**Comment by endocrimes** [comment]
I missed that we already have a [`-server-id`](https://www.nomadproject.io/docs/commands/monitor.html#server-id) flag for the `nomad monitor` command that expects a server _name_, or `leader`.

**Comment by m1kc** [comment]
Ah, dammit! Can't even say how I missed it if it was there all the time.

@endocrimes Thanks bunches!

**Comment by endocrimes** [comment]
@m1kc No worries! - Hope you find it useful ^_^
