### ISSUE TITLE
Connect Proxy Kind is not interpolated

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6853]
### Nomad version
0.10.2

### Issue

When validating jobs on submission the service names are interpolated but the task kind is not.

This means if a service names uses an interpolated value such as `${JOB}` a Connect-enabled job will fail to validate with the error:

```
Connect proxy service name not found in services from task group
```

Augmenting the error message with details makes the difference of interpolation obvious:

```
Connect proxy service name ("count-${JOB}") not found in services from task group: count-countdash
```

### Job file (if appropriate)

Just add `${JOB}` to the service name in the example Connec job: https://gist.github.com/schmichael/c22e696d6dca0ed585d98ab7a7e2fe63

**Comment by roderickmarj** [comment]
why
