### ISSUE TITLE
improve vault_grace documentation

### ISSUE THREAD

**Issue by tydomitrovich** [hashicorp/nomad#6856]
### Nomad version
Nomad v0.10.0 (25ee121d951939504376c70bf8d7950c1ddb6a82)

### Issue

I found the wording around the documentation for the `vault_grace` field under the `template` stanza at https://www.nomadproject.io/docs/job-specification/template.html#vault_grace to be unnecessarily verbose and confusing. What was particularly confusing was multiple ways of phrasing "reading a secret", such as "secret renewal" and "secret re-acquisition". I have not seen this terminology used in the consul template documentation or vault documentation. I feel that the documentation for vault grace found in the consul template code is more concise and the nomad docs could be updated to something similar to the following:

> `vault_grace` is the amount of time before a lease is about to expire to force a new secret to be read. If a lease is due to expire in 15 seconds, the template will read a new secret at that time minus `vault_grace`. 

> If the `vault_grace` is set to a value that is higher than your default TTL or max TTL, the template will always read a new secret. **If secrets are being read constantly, decrease the vault_grace.** Likewise, if `vault_grace` is set to zero, the template will not read a new secret until after after the lease has expired.

> If the task defines several templates, the vault_grace will be set to the lowest value across all the templates.

**Comment by tgross** [comment]
Hi @tydomitrovich! I can definitely see how that's a bit confusing. Looks like the language was originally shared with consul-template from this commit https://github.com/hashicorp/consul-template/commit/2ad07927ef7f87f3e513becb58b3fe6d2c3cbb7d, which read:

> This is the grace period between lease renewal of periodic secrets and secret
re-acquisition. When renewing a secret, if the remaining lease is less than or
equal to the configured grace, Consul Template will request a new credential.
This prevents Vault from revoking the credential at expiration and Consul

But the `grace` flag that consul-template _was_  using has been removed in https://github.com/hashicorp/consul-template/commit/e582598b3b1266426e762b587697f59ee3e4a58d#diff-04c6e90faac2675aa89e2176d2eec7d8

Now the roughly equivalent section of consul-template's docs are for the `renew_token` flag:
> Consul Template will automatically renew the token at half the lease duration of the token.

So it looks like there's both a documentation issue and a dependency update we'll want to do for our Vault API client.

**Comment by tydomitrovich** [comment]
Hi @tgross! Thanks you for clarifying the origin of that vault_grace documentation. Though now that vault_grace is deprecated, and the nomad docs have been updated accordingly, this issue no longer seems relevant. I will go ahead and close it.
