### ISSUE TITLE
cli: inconsistent and incorrect error placement on flag not defined 

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#6857]
### Nomad version
`Nomad v0.10.2`

### Operating system and Environment details
Tested on `macOS Catalina 10.15.1`

### Issue
When passing a flag to a Nomad CLI command, which is not defined for use, the output error is inconsistency placed and is also concatenated onto the command usage output. The error will sometimes appear before the command usage, and sometimes after. Both examples are shown below.

Example 1:
```
$ nomad server members -verbose
flag provided but not defined: -verboseUsage: nomad server members [options]
```

Example 2 (output shortened):
```
$ nomad node status -detailed
...
...
  -t
    Format and display node using a Go template.flag provided but not defined: -detailed
```

### Reproduction steps
A couple of commands using incorrect flags:
`nomad node status -detailed`
`nomad server members -verbose`

**Comment by tgross** [comment]
Hi @jrasell! I've marked this as a bug. Thanks!
