### ISSUE TITLE
cpu_hard_limit not working in Nomad v0.9.5

### ISSUE THREAD

**Issue by luca-eb** [hashicorp/nomad#6859]
### Nomad version
`Nomad v0.9.5`

### Operating system and Environment details
OS
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Docker
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

### Issue
Docker driver's cpu_hard_limit is not working in Nomad v0.9.x as CPU is not being capped.
CPU is capped in our current Nomad v0.8.4 (OS and docker unchanged). 

### Reproduction steps
Activate cpu_hard_limit for a docker task and see it not being capped in your monitor.

### Job file
```
group "personalized_redis_parser" {
    count = 3

    update {
      progress_deadline = "30m"
    }

    meta {
      "build" = "{{ build }}"
      "group_modtime" = "{{ group_modtime }}"
    }

    task "personalized_redis_parser" {

      driver = "docker"

      env {
        NOMAD_NODE_ADDR = "${attr.unique.network.ip-address}"
        NOMAD_NODE_HOST = "${attr.unique.hostname}"
        PYTHONPATH = "/local"
        DJANGO_SETTINGS_MODULE = "newsletter_config"
      }

      template {
       source      = "/etc/eventbrite/soa/newsletter_config.py.ctmpl"
       destination = "local/newsletter_config.py"
       change_mode = "noop"
      }

      template {
       source      = "local/venv/configs/docker.py.ctmpl"
       destination = "local/repo_config.py"
       change_mode = "noop"
      }

      artifact {
        source = "{{ build_url }}"
        destination = "local/"
      }

      config {
        image = "{{ docker_image }}"
        volumes = ["/etc/eventbrite/keys:/etc/eventbrite/keys:ro"]
        command = "/usr/bin/python3"
        args = ["manage.py", "run_kafka_consumer", "personalized-redis-parser"]
        cpu_hard_limit = true
      }

      resources {
        memory = 300
        cpu = 500
      }
    }
  }
```

**Comment by jorgemarey** [comment]
Hi. This happened to us too. I think it's due to `cpu_cfs_period` not having a default value (so it's 0). Here:
```
	if driverConfig.CPUHardLimit {
		numCores := runtime.NumCPU()
		if driverConfig.CPUCFSPeriod < 0 || driverConfig.CPUCFSPeriod > 1000000 {
			return c, fmt.Errorf("invalid value for cpu_cfs_period")
		}
		if driverConfig.CPUCFSPeriod == 0 {
			driverConfig.CPUCFSPeriod = task.Resources.LinuxResources.CPUPeriod
		}
		hostConfig.CPUPeriod = driverConfig.CPUCFSPeriod
		hostConfig.CPUQuota = int64(task.Resources.LinuxResources.PercentTicks*float64(driverConfig.CPUCFSPeriod)) * int64(numCores)
	}
```
When no CPUCFSPeriod is specified, it gets the CPUPeriod from the task resources, but now there's no way to specify cpu period on task (that I'm aware of). 

As a workaround, if you set `cpu_cfs_period` to a value between 0 and 1000000 and set the `cpu_hard_limit` to true it should work.

**Comment by jippi** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/6737

**Comment by tgross** [comment]
Thanks for reporting this @luca-eb! As @jippi has pointed out, this was fixed in #6737 and that fix for this was released in 0.10.2.

**Comment by dcastellanos-eb** [comment]
Is there any plan to backport this change to 0.9.X?

**Comment by tgross** [comment]
We're not planning on backporting to 0.9.x (typically only critical security fixes or panicking bugs get backported). The workaround @jorgemarey posted should work, though:

> As a workaround, if you set `cpu_cfs_period` to a value between 0 and 1000000 and set the `cpu_hard_limit` to true it should work.

**Comment by luca-eb** [comment]
I can confirm that @jorgemarey fix works. thanks for the help y'all as always!
