### ISSUE TITLE
Job does not pass validation if MaxParallel set to 0

### ISSUE THREAD

**Issue by alexey-mylnikov** [hashicorp/nomad#6861]
### Issue
The [documentation](https://www.nomadproject.io/docs/job-specification/update.html#max_parallel-0) states that for forced updates you can specify parameter `max_parallel = 0` , but such job does not pass [validation](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L4001-L4003).

### Reproduction steps
- set `max_attempts = 0` in any update Stanza
- run `nomad job validate job.nomad`

### Job file
```
job "my-job" {
  region = "my-region"
  datacenters = ["my-dc"]

  constraint {
    attribute = "${attr.kernel.name}"
    value = "linux"
  }

  update {
    stagger = "10s"
    max_parallel = 0
    canary = 0
  }

  group "my-group" {
    task "my-task" {
      driver = "docker"

      config {
        image = "ubuntu:latest"
        force_pull = true
        command = "echo"
        args = ["test"]
      }
    }
  }
}
```

**Comment by endocrimes** [comment]
What version of Nomad are you running on the CLI and on the Server? With nomad 0.10.2 the above job validates successfully for me:

```
[nomad(master)] $ cat nmd-6861.nomad
job "my-job" {
  region      = "my-region"
  datacenters = ["my-dc"]

  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  update {
    stagger      = "10s"
    max_parallel = 0
    canary       = 0
  }

  group "my-group" {
    task "my-task" {
      driver = "docker"

      config {
        image      = "ubuntu:latest"
        force_pull = true
        command    = "echo"
        args       = ["test"]
      }
    }
  }
}
[nomad(master)] $ nomad job validate nmd-6861.nomad
Job validation successful
```

**Comment by alexey-mylnikov** [comment]
Both are 0.9.5. It looks like this feature has been added in future releases. Thanks for the answer.
