### ISSUE TITLE
Add a "Reallocate/Retry Now" Button in UI/Command in CLI

### ISSUE THREAD

**Issue by TheRevenantStar** [hashicorp/nomad#6866]
### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

Sometimes, when diagnosing an allocation, issues arise from factors outside Nomad's control; network connectivity, a task's SQL permissions broken, etc...
It would be nice to have a shortcut to immediately attempt to retry a job, since restarting does not work, as a CLI command or button on the UI in the task's page.

**Comment by endocrimes** [comment]
@TheRevenantStar `nomad alloc stop` or the `Stop` button in the UI will stop an allocation and reschedule it elsewhere if the allocation is still running. I'm curious to know why in-place restarts don't work in this case though?
