### ISSUE TITLE
Unhealthy Allocations without Health Checks

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#6869]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version

```
Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)
```

### Operating system and Environment details

Ubuntu 18.04

### Issue

I have a job running using the Docker driver. During a deployment, allocations were marked unhealthy, but there are no checks configured in the job file. If no checks are specified, are the driver's health checks used (i.e. container is up/down)?

All allocations also still show as "running" so I cannot identify the unhealthy allocations in the deployment to investigate further.

**Comment by tgross** [comment]
Hi @evandam! Typically when this happens, the allocation is running but some of the tasks have failed to start. If you do `nomad alloc status <allocID>` it should show you a list of events for the tasks.

**Comment by evandam** [comment]
Thanks @tgross! I'll keep an eye out for if this happens again to check an alloc status. If I recall, though, it looked like tasks were running and services were green in Consul.

I'm okay closing this for now and reopening if I find the issue again.
