### ISSUE TITLE
Nomad crash on start: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by DanielDent** [hashicorp/nomad#687]
Log attached.

[crashlog.txt](https://github.com/hashicorp/nomad/files/93661/crashlog.txt)

**Comment by DanielDent** [comment]
FWIW: I resolved the problem by removing nomad's data directory on the server. On another server in the cluster, I stopped the job which I had started immediately before having this problem.  When I re-launched nomad after these two steps, it synced with the cluster and started up properly.

I've kept the old nomad data directory around in case it is helpful for you.

**Comment by dadgar** [comment]
Can you post the job that caused this?

**Comment by dadgar** [comment]
Closing since we can't repro
