### ISSUE TITLE
allow multiple args in nomad run/stop commands

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#689]
Hi,

I think it's useful to allow `nomad run srv1.nomad srv2.nomad` and `nomad stop job1 job2` in the command line.

what do you think? thanks!

**Comment by dadgar** [comment]
Hey,

I think it is a good idea but the UX is slightly challenging since we enter the evaluation monitor after. Since it is not a high burden to run it several times I will close this.
