### ISSUE TITLE
UI: uses too many CPUs, too much memory

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#6891]
I had Nomad UI oom-killed on server with 24 CPUs because _ember_ runs few workers per core and overall they use too much memory.
Excessive memory usage could be limited if there were a way to restrict UI to use only certain number of cores. 
How can I limit _ember_ to use several CPUs maximum?

Thanks.

**Comment by DingoEatingFuzz** [comment]
I'd like to learn more about your issue.

The Nomad UI is served as static files and takes virtually zero server-side resources to run (aside from the API calls it makes).

Can you share more about your setup and how you arrived at ember using these resources? Are you running a dev build of the UI? Are you seeing `ember` in top?

**Comment by onlyjob** [comment]
I'm running standalone UI as follows (so yes, the top/master process is _ember_):

    node_modules/.bin/ember serve --port 4200 --proxy http://nomad.service.consul:4646 --environment production

Is there a better way to run a dedicated UI? Built-in UI is unavailable to me because it is only available in _vendor_ binaries.

**Comment by DingoEatingFuzz** [comment]
If that proxy address you are using is working, then you should be able to go to `http://nomad.service.consul:4646` to get the UI. 

It's common to use something like nginx to create a limited reverse proxy to avoid opening the UI up to the world or inadvertently opening the API up even to internal users.

The `ember` binary is only meant to be used as a developer tool when working on the UI itself.  The `--environment production` flag is meant to emulate production builds, which may behave slightly differently then development builds, since it does code minification and elimination.

**Comment by onlyjob** [comment]
Thanks. The URL responds with "Nomad UI is not available in this binary". As I've said, I'm not running _vendor_ build of the Nomad... I will try to re-build Nomad with `ui` tag...

I'd much like to disable minification in _ember_ so I'll try to run it without `--environment production`. Thanks.

**Comment by DingoEatingFuzz** [comment]
Ah, gotcha, sorry didn't follow what you meant by vendor binary there.

Definitely my first recommendation is to rebuild with the ui tag. 

If you are willing to roll your sleeves up and make a mess, you can also build the UI separately using [`ember build --prod`](https://cli.emberjs.com/release/basic-use/deploying/) after changing the data layer to point at a fully qualified URL.

https://github.com/hashicorp/nomad/blob/edc62acd919dabc7ae237d3726dc8823d2c82ffe/ui/app/adapters/application.js#L8-L14

Becomes

```js
export const namespace = 'v1';

export default RESTAdapter.extend({
  namespace,
  host: 'http://nomad.service.consul:4646',

  system: service(),
  token: service(),
```

But that is very much an "at your own risk" kind of thing 😛

**Comment by onlyjob** [comment]
Built-in UI consumes fraction of _ember_ resources without starting that many workers.
Let's close this issue in favour of built-in UI - I hope it'll suffice so making standalone UI with `ember build --prod` won't be necessary.

Thanks, Michael!
