### ISSUE TITLE
Consul config under nomad configuration doesn't accept timeout property in any format

### ISSUE THREAD

**Issue by vikmalik** [hashicorp/nomad#6893]
### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

### Operating system and Environment details
Ubuntu 18.04.3 LTS 

### Issue
Consul config under nomad configuration doesn't accept ```timeout``` property in any format (tried "5s" , 5, "5". It was working fine in with v0.7.0 version but after upgrade to v0.10.2 it stopped working

### Reproduction steps
Add timeout property under consul configuration in nomad config file: 
```hcl
consul {
    "server_service_name" = "nomad"
    "server_auto_join" = true
    "client_service_name" = "my-client"
    "client_auto_join" = true
    "address" = "x.x.x.x:8500"
    "timeout" = "5s"
}
```
I also found that there are no unit test for this case in [consul_test.go](https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/consul_test.go)
### Nomad Client logs (if appropriate)
- with timeout = "5s"
  ```strconv.ParseInt: parsing "5s": invalid syntax```
- with timeout = "5"
  ```consul.timeout can't parse time duration 5```

### Nomad Server logs (if appropriate)
N.A

**Comment by vikmalik** [comment]
I gave some more test run on different versions and found that it got broken post ```v0.9.1```. I was working fine with ```v0.9.1``` and started to give error post that.

**Comment by tgross** [comment]
Thanks for reporting this @vikmalik! That definitely sounds like a regression.
