### ISSUE TITLE
Consul don't delete old services

### ISSUE THREAD

**Issue by vkiranananda** [hashicorp/nomad#6894]
Hello!
I have cluster.
Inside this cluster I have nomad job and service. 

```
      service {
        name = "memcached"
        port = "memcached"
        check {
           port     = "memcached"
           type     = "tcp"
           interval = "10s"
           timeout  = "2s"
        }
      }
```
This work good. 
Today my server failed. I restored it after some hours. And looking in my consul web interface duplicate of service.

```
ServiceName
memcached
CheckID
_nomad-check-20d0a4d9841b74c9ec2f65312f6e947f8adfef63
Notes
-
Output
TCP connect 10.92.60.153:25070: Success


ServiceName
memcached
CheckID
_nomad-check-982cb0c84732615b023a57acee16f150d9efcdff
Notes
-
Output
TCP connect 10.92.60.153:21510: Success

```
This is create many problem in consul-template

```
    [
        'host' => '10.92.60.153',
        'port' => '25070',
        'weight' => 50
    ],
    [ // Duplicate
        'host' => '10.92.60.153',
        'port' => '21510',
        'weight' => 50
    ],
```

### Nomad version
Nomad v0.10.2

### Consul version
Consul v1.6.2

### Operating system and Environment details
Linux Ubuntu 18.04

**Comment by endocrimes** [comment]
@vkiranananda Hey! - Do you possibly have any Nomad Logs from the time? (Or could you elaborate on what failed on the node?)

Thanks!

**Comment by vkiranananda** [comment]
Sorry, no logs (... 

Consul showed checks as worked, but real service did't work...

For fix  it, I use:

```
curl -s http://localhost:8500/v1/catalog/service/memcached | jq '.'

cat data.json 
{
  "Datacenter": "datacenter",
  "Node": "beta",
  "ServiceID": "_nomad-task-de5d52bf-94d5-cbee-d18c-a659ad789f07-memcached-memcached-memcached"
}

curl -X PUT -H "X-Consul-Token: 4461b7d7-5609-331f-ef42-1b4ad34ddb6d"  -d @data.json 127.0.0.1:8500/v1/catalog/deregister
```

**Comment by burdandrei** [comment]
Are you using a dynamic Consul ACL? if yes, there is a known issue for this: https://github.com/hashicorp/consul/issues/4372
