### ISSUE TITLE
FTBFS: concurrent map writes

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#6896]
0.10.2 suddenly FTBFS with failure: `fatal error: concurrent map writes`.

See [full build log](https://buildd.debian.org/status/fetch.php?pkg=nomad&arch=all&ver=0.10.2%2Bdfsg1-9&stamp=1577326195&raw=0)

**Comment by notnoop** [comment]
@onlyjob What version of `cronexpress` library do you use?  We vendor against sha 675cac9[1] which has a concurrency fix https://github.com/gorhill/cronexpr/commit/675cac9b2d182dccb5ba8d5f8a0d5988df8a4394#diff-e1b1edcc6fd570c795e7087cb1030487 .

Seeing the stacktrace below, I see that the concurrency map crash occurs due to a map access in line 485 within `makeLayoutRegexp` function call.  That doesn't match the latest cronexpr implementation or the one we vendored: https://github.com/gorhill/cronexpr/blob/88b0669f7d75f171bd612b874e52b95c190218df/cronexpr_parse.go#L485

You might be using an outdated cronexpr, sha a557574, that matches stacktrace: https://github.com/gorhill/cronexpr/blob/a557574d6c024ed6e36acc8b610f5f211c91568a/cronexpr_parse.go#L485 .

```
goroutine 271 [running]:
runtime.throw(0x1f3da8c, 0x15)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72 fp=0xc0019b73a0 sp=0xc0019b7370 pc=0x434582
runtime.mapassign_faststr(0x1be2200, 0xc0001da420, 0x1f28f6d, 0xa, 0x320e940)
	/usr/lib/go-1.13/src/runtime/map_faststr.go:211 +0x417 fp=0xc0019b7408 sp=0xc0019b73a0 pc=0x418237
github.com/gorhill/cronexpr.makeLayoutRegexp(0x1f28f6d, 0xa, 0x1f333d9, 0x10, 0x0)
	/<<PKGBUILDDIR>>/_build/src/github.com/gorhill/cronexpr/cronexpr_parse.go:485 +0x116 fp=0xc0019b7468 sp=0xc0019b7408 pc=0x8ba526
github.com/gorhill/cronexpr.genericFieldParse(0xc001873ac0, 0x4, 0x1f22f33, 0x6, 0x0, 0x3b, 0x317da80, 0x3c, 0x3c, 0x1f333d9, ...)
	/<<PKGBUILDDIR>>/_build/src/github.com/gorhill/cronexpr/cronexpr_parse.go:442 +0x71b fp=0xc0019b7560 sp=0xc0019b7468 pc=0x8b9a5b
github.com/gorhill/cronexpr.genericFieldHandler(0xc001873ac0, 0x4, 0x1f22f33, 0x6, 0x0, 0x3b, 0x317da80, 0x3c, 0x3c, 0x1f333d9, ...)
	/<<PKGBUILDDIR>>/_build/src/github.com/gorhill/cronexpr/cronexpr_parse.go:267 +0x70 fp=0xc0019b76c8 sp=0xc0019b7560 pc=0x8b7fe0
github.com/gorhill/cronexpr.(*Expression).minuteFieldHandler(...)
	/<<PKGBUILDDIR>>/_build/src/github.com/gorhill/cronexpr/cronexpr_parse.go:220
github.com/gorhill/cronexpr.Parse(0xc0018734e0, 0xc, 0xd6adae2ec1a08f64, 0xab76355fe46dbd1a, 0xc0019b7848)
	/<<PKGBUILDDIR>>/_build/src/github.com/gorhill/cronexpr/cronexpr.go:100 +0x288 fp=0xc0019b77a0 sp=0xc0019b76c8 pc=0x8b4698
github.com/hashicorp/nomad/nomad/structs.(*PeriodicConfig).Next(0xc000dbfdb0, 0x10dfa3fa, 0xed5960d6c, 0x0, 0x1d62e00, 0xc00197e930, 0x1d62ee0, 0xc00197e370, 0x1)
	/<<PKGBUILDDIR>>/_build/src/github.com/hashicorp/nomad/nomad/structs/structs.go:4152 +0x35b fp=0xc0019b7858 sp=0xc0019b77a0 pc=0xc9a41b
github.com/hashicorp/nomad/nomad.(*PeriodicDispatch).Add(0xc00184f440, 0xc001798d20, 0x0, 0x0)
	/<<PKGBUILDDIR>>/_build/src/github.com/hashicorp/nomad/nomad/periodic.go:228 +0x313 fp=0xc0019b79e8 sp=0xc0019b7858 pc=0x184f913
github.com/hashicorp/nomad/nomad.(*nomadFSM).applyUpsertJob(0xc000331d50, 0xc000a9b601, 0x81a, 0xcff, 0x1, 0x0, 0x0)
	/<<PKGBUILDDIR>>/_build/src/github.com/hashicorp/nomad/nomad/fsm.go:449 +0x31e fp=0xc0019b7bf8 sp=0xc0019b79e8 pc=0x181661e
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc000331d50, 0xc0019b7dc8, 0xc00184f8c0, 0xc000a9b600)
	/<<PKGBUILDDIR>>/_build/src/github.com/hashicorp/nomad/nomad/fsm.go:199 +0x3ad fp=0xc0019b7c88 sp=0xc0019b7bf8 pc=0x181312d
github.com/hashicorp/nomad/nomad.TestFSM_DeregisterJob_NoPurge(0xc00053e300)
	/<<PKGBUILDDIR>>/_build/src/github.com/hashicorp/nomad/nomad/fsm_test.go:799 +0x28d fp=0xc0019b7f70 sp=0xc0019b7c88 pc=0x18ef77d
testing.tRunner(0xc00053e300, 0x1faa7e8)
	/usr/lib/go-1.13/src/testing/testing.go:909 +0xc9 fp=0xc0019b7fd0 sp=0xc0019b7f70 pc=0x519889
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0019b7fd8 sp=0xc0019b7fd0 pc=0x464a31
created by testing.(*T).Run
	/usr/lib/go-1.13/src/testing/testing.go:960 +0x350
```

**Comment by onlyjob** [comment]
Thanks for checking. We are using v1.0.0 of the [github.com/gorhill/cronexpr](https://github.com/gorhill/cronexpr/releases). Using the exact commit is not always possible or even wise.
I'll see if I can cherry-pick https://github.com/gorhill/cronexpr/commit/675cac9b2d182dccb5ba8d5f8a0d5988df8a4394.

Looking at the [github.com/gorhill/cronexpr](https://github.com/gorhill/cronexpr/releases) I've realised that the repository is archived and the library is no longer maintained. Is there a plan to phase it out?

**Comment by onlyjob** [comment]
Many thanks for your excellent troubleshooting, @notnoop.  
I've updated _golang-github-gorhill-cronexpr-dev_ library but its unmaintained state upstream concerns me...

**Comment by notnoop** [comment]
The library maintenance issue concerning indeed.  We intend to migrate off the library (or maintain it though unlikely) as part of https://github.com/hashicorp/nomad/issues/5410 .
