### ISSUE TITLE
Go-getter issue

### ISSUE THREAD

**Issue by Abiy** [hashicorp/nomad#6897]
nomad downloads artifacts in an allocation relative path even if I provided an absolute path 

artifact {
      source = "http://<path>/<jar with version>.jar"
      destination = "/home/app/<some>.jar"
      options {
        checksum = "md5:0c598449fb1a4447955fd49cd10b51e5"
      }
    }

**Comment by endocrimes** [comment]
@Abiy Nomad will always download artifacts relative to the root of the tasks directory, see [`artifact.destination`](https://www.nomadproject.io/docs/job-specification/artifact.html#destination).

Downloading to paths outside of the allocation root is unsupported as it opens up a wide attack surface on Nomad Clients.

Is there a reason why you need things to be downloaded to a non-alloc specific directory as part of an allocation?
