### ISSUE TITLE
Server CSI Client + Routing

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#6903]
As part of configuring CSI Volumes, Nomad Servers will have to make requests via a CSI Controller Plugin running on a Remote Client.

Because only a subset of Nomad Clients will be running an eligible plugin, we need the following:
- An API Shim to make programming against the CSI API easier
- That will look up an eligible client based on the plugin name, type, and datacenter
- Will then perform the required ClientRPC to that node (via server forwarding if necessary).

**Comment by tgross** [comment]
Closed by #7107 and #7717
