### ISSUE TITLE
CSI Client Side Controller

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#6906]
Placeholder issue for the design of Client Side Volume Management.

When an allocation that uses a CSI Volume is placed on a Nomad Client, we need to check (note these are rough incomplete notes, please double check the specification when implementing this):

### The First Time a Volume is used on the host

- If it needs a volume to be attached remotely (if the relevant NodePlugin has the Controller Required capability)
	- If it needs the remote volume attachment, we then need to retrieve the `PublishContext` from the `ControllerPublishVolume` response from the server
- If the plugin supports NODE_STAGE_UNSTAGE_VOLUME, we then need to stage the volume with the node plugin
- Run the allocation as normal
- `NodeUnstageVolume` when no longer used
- Tell the server to `ControllerUnpublishVolume`

### For every allocation that uses the volume

- Call `NodePublishVolume` from the staging or device path to an alloc specific mounts directory
- Add the alloc specific mounts dir to the tasks mounts configuration
- When the alloc terminates, call `NodeUnpublishVolume` with the alloc specific path

**Comment by tgross** [comment]
I'm going to close this placeholder issue as the work has been split out to internal tracking RFCs, #7030 #7031 #7035, etc.
