### ISSUE TITLE
Run nomad as a service (Windows)

### ISSUE THREAD

**Issue by Supernomad** [hashicorp/nomad#694]
So I have been getting Nomad up and running on my infrastructure and I am currently in the process of adding in Windows based nodes to the mix. I have however run into a slight issue with handling Nomad as a service. 

Currently I am using a scheduled task to start up nomad on boot and to check if its running, but this feels very hacky. Is there any specific way that you guys suggest we run nomad on windows? If so is there anyway some docs could be added to help handle the configuration?

**Comment by dadgar** [comment]
I think that is a fine way of doing it. Another option is to write a `nomad.bat` script and putting it in the Startup folder.

http://www.howtogeek.com/138159/how-to-enable-programs-and-custom-scripts-to-run-at-boot/
