### ISSUE TITLE
Upgrade consul-template and remove deprecated Grace field

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6946]
### Nomad version
Nomad v0.10.2

### Issue

[Nomad uses a Vault.Grace field](https://github.com/hashicorp/nomad/blob/v0.10.2/client/allocrunner/taskrunner/template/template.go#L614-L623) which has been removed from both [Vault](https://github.com/hashicorp/vault/blob/v0.5.0/CHANGELOG.md#050-february-10-2016) and [consul-template](https://github.com/hashicorp/consul-template/pull/1284).

Nomad should upgrade consul-template and remove our use of the field.

**Comment by kecorbin** [comment]
Running into issues trying to create a service mesh ingress using nginx as outlined [here](https://github.com/hashicorp/consul-template/blob/master/examples/nginx-connect-proxy.md)

The following template stanza's are failing to retrieve connect CA information as it appears they are not yet integrated into Nomad. 

```
      template {
        data = <<EOF
{{range caRoots}}{{.RootCertPEM}}{{end}}
EOF

        destination   = "local/ca.crt"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }


      template {
        data = <<EOF
{{with caLeaf "ingress"}}{{.CertPEM}}{{end}}
EOF

        destination   = "local/cert.pem"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }

      template {
        data = <<EOF
{{with caLeaf "ingress"}}{{.PrivateKeyPEM}}{{end}}
EOF

        destination   = "local/cert.key"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
```

Returns error message such as

```
Template failed: (dynamic): parse: template: :1: function "caRoots" not defined
```

**Comment by perbly** [comment]
Same issue here when trying to template connect services.

` {{- range services }}
        {{- $service:=.Name}}
        {{- range .Tags  }}
            {{- if eq . "external" }}
              {{- range connect $service }}
                {{- $service }} {{ .Name }} {{ .Address }}:{{ .Port }}
              {{ end -}
            {{end -}}
        {{end -}}
        {{end -}}`

`(dynamic):` parse: template: :5: function "connect" not defined`

Works fine with consul-template alone.
