### ISSUE TITLE
Building `dev-ui`

### ISSUE THREAD

**Issue by thoward27** [hashicorp/nomad#6947]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version 0.10.3-dev
Output from `nomad version`

### Operating system and Environment details

Archlinux docker image (`FROM archlinux:latest`)

### Issue

`make dev-ui` fails with no clear resolution:

```bash
$ make dev-ui
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
warning " > @babel/plugin-proposal-object-rest-spread@7.5.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > @ember-data/-build-infra > @babel/plugin-transform-block-scoping@7.6.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > @ember-data/-build-infra > babel-plugin-debug-macros@0.3.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
```

### Reproduction steps

```bash
git clone https://github.com/hashicorp/nomad.git
cd nomad
make bootstrap 
make dev 
make dev-ui
```

Full docker image:

```
FROM archlinux:latest

RUN pacman -Syu --noconfirm

RUN pacman -S --noconfirm \
    go \
    python2 \
    python2-pip \
    python \
    python-pip \
    git \
    make \
    gcc \
    docker \
    neovim \
    yarn

ENV PATH="/root/go/bin:${PATH}"

###################
# Setup Hashicorp.
###################
ENV HC="/root/go/src/github.com/hashicorp"
RUN mkdir -p ${HC}

## Nomad. https://www.hashicorp.com/products/nomad
RUN cd ${HC} && git clone https://github.com/hashicorp/nomad.git && cd nomad && make bootstrap && make dev && make dev-ui && nomad -v 
```

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Thanks for reporting this @thoward27. I was able to confirm the same problem with the Dockerfile you provided, and I'll let the folks who have a bit more expertise on the JS build chime in.

**Comment by thoward27** [comment]
Thanks @tgross

**Comment by thoward27** [comment]
Any update on this @tgross ?

**Comment by tgross** [comment]
Apologies, I should have pinged @DingoEatingFuzz and/or @backspace for their expertise here.

**Comment by backspace** [comment]
Hello, thanks for letting us know about this, and I’m sorry for the delay in responding. I’m a relative neophyte when it comes to the world of Docker, but I tried this myself and got the same failure. The Node version installed in the environment is v13, but we’re expecting v10, as you can see in [this file](https://github.com/hashicorp/nomad/blob/54e89a50044557e12794024d92159d7ebd8fcb49/ui/.nvmrc). Given my unfamiliarity with Docker, I’m not sure if this is a naïve suggestion, but would it be possible to [install nvm](https://github.com/nvm-sh/nvm#installing-and-updating) as part of your setup? That would respect the `.nvmrc` file. I did so in the Docker environment and then `make dev-ui` succeeded.

**Comment by DingoEatingFuzz** [comment]
Hi @thoward27, I spent a few hours on this and got a working configuration.

The tl;dr is that the Node version needs to be 10.x (as declared in the [`.nvmrc`](https://github.com/hashicorp/nomad/blob/master/ui/.nvmrc) file) and `npm` needs to be installed too.

Both of these requirements are to satisfy the [`npm rebuild node-sass`](https://github.com/hashicorp/nomad/blob/master/GNUmakefile#L364) command, which uses `node-gyp` to do native compilation.

Here is my updated Dockerfile. Installing Node using nvm feels a bit heavy handed for a docker container, but it works!

```dockerfile
FROM archlinux:latest

RUN pacman -Syu --noconfirm

RUN pacman -S --noconfirm \
    go \
    python2 \
    python2-pip \
    python \
    python-pip \
    git \
    make \
    gcc \
    docker \
    neovim \
    yarn

ENV NODE_VERSION "10.20.1"
RUN curl -sSL --fail -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash \
  && . ~/.nvm/nvm.sh \
  && nvm install 10 --latest-npm \
  && nvm alias default 10 \
  && nvm use default

ENV PATH "/root/.nvm/versions/node/v${NODE_VERSION}/bin:/root/go/bin:${PATH}"

###################
# Setup Hashicorp.
###################
ENV HC="/root/go/src/github.com/hashicorp"
RUN mkdir -p ${HC}

## Nomad. https://www.hashicorp.com/products/nomad
RUN cd ${HC} && git clone https://github.com/hashicorp/nomad.git && cd nomad && make bootstrap && make dev-ui && nomad -v
```

Also not that if you are running `make dev-ui` you don't have to run `make dev`.

I verified this all worked correctly with

```sh
$ docker run -p 3636:4646 585 nomad agent -dev -bind=0.0.0.0
```

I got to the bottom of the root issue by trying to build the UI outside the context of `make` using the `yarn start` and `yarn build` commands that can be ran in the `ui` dir.

Hope this helps!
