### ISSUE TITLE
[feature request] change log level temporarily (dynamically)

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#6959]
### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

### Operating system and Environment details
CentOS 7/8, Ubuntu 14/16/18

### Issue
This is a feature request.

How about if the operator is able to change the logging level temporarily using some command; say `nomad operator log-level DEBUG <timeout>`

This should change the agent's logging level to the new level for the specified time.
Many a time's during debugging, this can come in handy to switch the agent's log level without having to reload/restart the agent

### Reproduction steps
N/A. This is a feature request:

### Job file (if appropriate)
N/A. This is a feature request:

### Nomad Client logs (if appropriate)
N/A. This is a feature request:

Regards,
Shantanu Gadgil

**Comment by endocrimes** [comment]
[`nomad monitor`](https://www.nomadproject.io/docs/commands/monitor.html) let's you do this by streaming the logs at a provided level. I'd be curious to hear if that's enough to solve your problem?

**Comment by shantanugadgil** [comment]
🤦‍♂ this works for what I had in mind.

Though, I am not sure if it would help to capture logs from files of all the nodes, as this is streaming data to the "nomad monitor" console, right?

The original idea of switching the agent itself could still make sense over and above the `monitor` feature.
