### ISSUE TITLE
Constraint "missing drivers" issue

### ISSUE THREAD

**Issue by cmfatih** [hashicorp/nomad#696]
Hi All,

I have a dev machine that has Nomad server and client are running on it. Somehow I'm getting `missing drivers` issue. Any thoughts?

```
# Linux CentOS 6 - Kernel 3.10.93-1.el6.elrepo.x86_64

$ docker --version
Docker version 1.8.3, build f4bf5c7

$ ./nomad run example.nomad

==> Monitoring evaluation "add8b71b-89c9-b852-cffc-c0375d1d0d6f"
    Evaluation triggered by job "example"
    Scheduling error for group "cache" (failed to find a node for placement)
    Allocation "c81b4c13-6394-3078-db3d-01fa5b31b73c" status "failed" (1/1 nodes filtered)
      * Constraint "missing drivers" filtered 1 nodes
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "add8b71b-89c9-b852-cffc-c0375d1d0d6f" finished with status "complete"

$ ./nomad node-status
ID                                    DC   Name                                     Class   Drain  Status
c7a2f801-da24-0795-45e8-7117a3aa0a0d  dc1  #  <none>  false  ready
```

**Comment by cmfatih** [comment]
I was able to fix it by restarting docker daemon and nomad agent ( client )

**Comment by mongrelion** [comment]
I ran into this issue today. Happened that I didn't have Docker installed on my machine.
Perhaps the wording of the error message could be improved?

**Comment by dadgar** [comment]
@mongrelion Do you have any suggestions?

**Comment by mongrelion** [comment]
@dadgar I'm no expert in UX but I think that something like
`missing drivers (is blah service running?)` should suffice.

**Comment by dadgar** [comment]
Yeah, docker however is the only driver that requires a service to be running.

**Comment by mongrelion** [comment]
Ah, bummer. Perhaps, then, a special note on the [**Getting Started** guides] (https://www.nomadproject.io/intro/getting-started/jobs.html) or somewhere else, specifying that the host were the task is going to be ran must have Docker installed. I know this sounds kind of obvious but I have seen these sort of cases before with other schedulers that integrate with Docker and such.

**Comment by digikin** [comment]
I found that the issue is installing docker after nomad.  So if you already have nomad installed, stopping everything `ctl + c` then as root restart docker `systemctl restart docker`.  Once docker reboots turn on nomad again and the error disappears.

**Comment by lakshayarora476** [comment]
I solved this issue by giving full permissions on docker.
Added my user to docker and gave 'sudo' permissions with 'no password' to that user (in sudoers file)

**Comment by awildturtok** [comment]
Getting this error message while trying to use consul and podman.

**Comment by mooijtech** [comment]
I fixed this by running the agent via ```sudo```.

**Comment by vjanssens** [comment]
It's important to note the comment in the systemd configuration on https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul#configure-systemd:

> Nomad server should be run as the nomad user. Nomad clients
> should be run as root 

This solved it for me.

**Comment by morm** [comment]
> It's important to note the comment in the systemd configuration on https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul#configure-systemd:
> 
> > Nomad server should be run as the nomad user. Nomad clients
> > should be run as root
> 
> This solved it for me.

You saved me few days of hitting the wall with my head!

**Comment by Mandelag** [comment]
I solved this by adding `nomad` user to `docker` group and then restarted the nomad client.
