### ISSUE TITLE
Terraform- Unable to upgrade the AMI to Ubuntu 18.04

### ISSUE THREAD

**Issue by sivarajendranaidu** [hashicorp/nomad#6962]
I was able to setup Nomad Cluster in AWS by following the steps pointed [README.md](https://github.com/hashicorp/nomad/blob/master/terraform/aws/README.md)

But this shall build AMI which Ubuntu 16.04 which I would like to upgrade to Ubuntu 18.04.
Hence I tried to change the [setup.sh](https://github.com/hashicorp/nomad/blob/master/terraform/shared/scripts/setup.sh) as follows
diff --git a/terraform/aws/packer.json b/terraform/aws/packer.json
```diff
index 1c778fdc2..fa9ed5eee 100644
--- a/terraform/aws/packer.json
+++ b/terraform/aws/packer.json
@@ -2,7 +2,7 @@
   "builders": [{
     "type": "amazon-ebs",
     "region": "us-east-1",
-    "source_ami": "ami-80861296",
+    "source_ami": "ami-04b9e92b5572fa0d1",
     "instance_type": "t2.medium",
     "ssh_username": "ubuntu",
     "ami_name": "hashistack {{timestamp}}",
```

diff --git a/terraform/shared/scripts/setup.sh b/terraform/shared/scripts/setup.sh
```diff
index c3cca9c72..0ac8d81c5 100644
--- a/terraform/shared/scripts/setup.sh
+++ b/terraform/shared/scripts/setup.sh
@@ -35,10 +35,10 @@ HADOOP_VERSION=2.7.7
 sudo apt-get install -y software-properties-common
 sudo apt-get update
 sudo apt-get install -y unzip tree redis-tools jq curl tmux

 sudo apt-get install -y python-setuptools
-sudo easy_install pip
+sudo apt-get install -y python-pip
 sudo pip install numpy
```

Please find packer build logs as follows:
```
    amazon-ebs: Preparing to unpack .../132-linux-headers-4.15.0-74-generic_4.15.0-74.84_amd64.deb ...
    amazon-ebs: Unpacking linux-headers-4.15.0-74-generic (4.15.0-74.84) ...
    amazon-ebs: Selecting previously unselected package linux-headers-generic.
    amazon-ebs: Preparing to unpack .../133-linux-headers-generic_4.15.0.74.76_amd64.deb ...
    amazon-ebs: Unpacking linux-headers-generic (4.15.0.74.76) ...
    amazon-ebs: Errors were encountered while processing:
    amazon-ebs:  /tmp/apt-dpkg-install-WRIaOX/083-nvidia-440_440.33.01-0ubuntu1_amd64.deb
==> amazon-ebs: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 100.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 100.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

**Comment by tgross** [comment]
Hi @sivarajendranaidu! Thanks for reporting this. I hope you don't mind, but I've edited your post slightly to put code blocks around the diffs so it's a little easier to read. It looks like the packer build is failing when you're trying to install the CUDA drivers for Nvidia support: [setup.sh#L120](https://github.com/hashicorp/nomad/blob/3adb3cd1fec6c3aab531f5a46e0da50a713041cc/terraform/shared/scripts/setup.sh#L120). But if you look a couple lines above, you'll see that we're adding the apt repository for Nvidia's driver compatible with [`ubuntu1604`](https://github.com/hashicorp/nomad/blob/3adb3cd1fec6c3aab531f5a46e0da50a713041cc/terraform/shared/scripts/setup.sh#L118).

So if you want to upgrade the Ubuntu to bionic, you'll need to make sure you've added the right repo from Nvidia's site as well. If you get this all working, I'm sure we'd love to get a patch to make this build 18.04 compatible!
