### ISSUE TITLE
Consul should inform the private IP of the bridged network in Docker

### ISSUE THREAD

**Issue by selmison** [hashicorp/nomad#6964]
### Nomad version
Nomad v0.10.2

### Operating system and Environment details
Ubuntu 18.04.3 LTS
1 Server + 3 Nodes

### Issue
I have a `User` app that communicates directly with its exclusive `UserDB` database. Both `User` and `UserDB` are on an isolated bridged docker network, where only the `User` will be accessible externally using **Consul Connect.**

For the `User` to be able to communicate with its `UserDB`, Consul SD should inform the IP of the **bridged network**, but Consul is informing the IP of the host node.

I tried to use the option `address_mode = "driver"` in service stanza, but the behavior did not change.

Would it be possible to enable this behavior?

### Reproduction steps
$ nomad job run sockshop-user.nomad
$ sudo docker exec -it <user_container_id> sh
$ dig user-db.service.consul

When ping "user-db.service.consul" in `user` app, the name is resolved to the IP of the host node.

The right would the name be resolved to the container's private IP on the bridged network.

### Job file (if appropriate)

`
job "sockshop-user" {
  datacenters = ["dc1"]

  constraint {
    attribute = "${attr.kernel.name}"
    value = "linux"
  }

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "user" {
    count = 1

    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    network {
      mode = "bridge"
    }

    service {
      name = "user"
      tags = ["app", "user"]
      port = "80"

      connect {
        sidecar_service {}
      }
    }   

    task "user" {
      driver = "docker"

      env {
	      HATEAOS = "user.service.consul"
        MONGO_HOST = "user-db.service.consul:27017"
      }

      config {
        image = "weaveworksdemos/user:master-5e88df65"
      }

      vault {
        policies = ["sockshop-read"]
      }

      template {
        data = <<EOH
        MONGO_PASS="wo39c5h2sl4r"
        EOH
        destination = "secrets/user_db.env"
        env = true
      }

      resources {
        cpu = 100
        memory = 128
      }
    }

    task "user-db" {
      driver = "docker"

      config {
        image = "weaveworksdemos/user-db:master-5e88df65"
      }

      vault {
        policies = ["sockshop-read"]
      }

      template {
        data = <<EOH
        MONGO_PASS="wo39c5h2sl4r"
        EOH
        destination = "secrets/user_db.env"
        env = true
      }

      service {
        name = "user-db"
        tags = ["db", "user", "user-db"]
        address_mode = "driver"
      }

      resources {
        cpu = 100
        memory = 96
      }
    }
  }
}
`

**Comment by runeron** [comment]
Can't you just connect to localhost:db-port, since they are in same group and are sharing the network bridge (i.e. both tasks share internal ip)?

**Comment by selmison** [comment]
Pertfect!! This is worked!! Thank @runeron
