### ISSUE TITLE
Java Job Failing

### ISSUE THREAD

**Issue by akshatgit** [hashicorp/nomad#6965]
### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

### Operating system and Environment details
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Issue
Running hello world jar with Java driver is failing. 

### Reproduction steps
Simple hello world jar run is failing. To reproduce it, simply run any jar. 

Hello world repo:  https://github.com/macagua/example.java.helloworld

### Job file (if appropriate)
job "Hello-World" {
  datacenters = ["dc-1"]

  type = "service"

  group "java" {
    count = 1

    task "java" {
      driver = "java"

      config {
        jar_source = "http://<<File-server-URL>>/Hello-World.jar"
      }
      resources {
        cpu = 500
        memory = 256
        network {
          mbits = 10
        }
      }
    }
  }

}

### Nomad Client logs (if appropriate)
Alloc status logs:
Recent Events:
Time                  Type              Description
2020-01-21T08:54:51Z  Killing           Sent interrupt. Waiting 5s before force killing
2020-01-21T08:54:51Z  Not Restarting    Error was unrecoverable
2020-01-21T08:54:51Z  Task hook failed  task_dir: Couldn't create symlink: symlink dnd-copy /etc/nomad.d/alloc/bb00328d-59f6-868c-ac55-2bdaae4e5b39/java/etc/nomad.d/alloc/bb00328d-59f6-868c-ac55-2bdaae4e5b39/java/etc/nomad.d/alloc/4b2be441-541c-1b27-a10f-1306697fbbaf/java/etc/nomad.d/alloc/4b2be441-541c-1b27-a10f-1306697fbbaf/java/etc/nomad.d/alloc/4b2be441-541c-1b27-a10f-1306697fbbaf/java/etc/nomad.d/alloc/4b2be441-541c-1b27-a10f-1306697fbbaf/java/etc/nomad.d/alloc/4b2be441-541c-1b27-a10f-1306697fbbaf/java/usr/share/icons/Adwaita/cursors/copy: no space left on device
2020-01-21T08:51:23Z  Task Setup        Building Task Directory
2020-01-21T08:51:23Z  Received          Task received by client

###Java Version on client
akshat.s@c-1:/var/log$ java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by akshatgit** [comment]
Got the same error for exec driver:

task_dir: Couldn't create destination directory /etc/nomad.d/alloc/f3a6f528-ab22-e335-e0d0-c3084b957951/server/etc/nomad.d/alloc/5019bf52-16d8-26ec-05d5-fa5a0bed44d4/server/etc/nomad.d/alloc/9244a2d7-7f86-4859-4523-96d59f5cef06/server/etc/puppetlabs/puppet/ssl/certificate_requests: mkdir /etc/nomad.d/alloc/f3a6f528-ab22-e335-e0d0-c3084b957951/server/etc/nomad.d/alloc/5019bf52-16d8-26ec-05d5-fa5a0bed44d4/server/etc/nomad.d/alloc/9244a2d7-7f86-4859-4523-96d59f5cef06/server/etc/puppetlabs/puppet/ssl/certificate_requests: no space left on device
--

Job file:

job "python-server" {

  datacenters = ["dc-1"]

  type = "service"

  group "server" {

    count = 5

    task "server" {

      driver = "exec"

      command = "python"
      args    = ["-m","http.server"]

      config {
        port_map {
        db = 8000
        }
      }
      resources {
        cpu    = 500 # MHz
        memory = 128
        network {
          mbits = 10
          port "db" {}
        }
      }
      service {
        name = "global-python-check"
        tags = ["global" ]
        port = "db"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}

**Comment by tgross** [comment]
Hi @akshatgit! You've got an error message `no space left on device`. It looks like the disk where Nomad is trying to create the task directory is full (or has exhausted its inodes). Take a look at correcting that and seeing if that helps.

**Comment by akshatgit** [comment]
akshat.s@c-1:~$ df -i
Filesystem      Inodes  IUsed  IFree IUse% Mounted on
udev            952764    264 952500    1% /dev
tmpfs           956439    993 955446    1% /run
/dev/xvda1     1310720 754130 556590   58% /
tmpfs           956439      1 956438    1% /dev/shm
tmpfs           956439      3 956436    1% /run/lock
tmpfs           956439     15 956424    1% /sys/fs/cgroup

space and inodes are available, but the jobs are creating too many small files.

**Comment by tgross** [comment]
It's hard to tell for sure because you haven't used a code block, but is `/etc/nomad.d/alloc/f3a6f528-ab22-e335-e0d0-c3084b957951/server/etc/nomad.d/alloc/5019bf52-16d8-26ec-05d5-fa5a0bed44d4/server/etc/nomad.d/alloc/9244a2d7-7f86-4859-4523-96d59f5cef06/server/etc/puppetlabs/puppet/ssl/certificate_requests: mkdir /etc/nomad.d/alloc/f3a6f528-ab22-e335-e0d0-c3084b957951/server/etc/nomad.d/alloc/5019bf52-16d8-26ec-05d5-fa5a0bed44d4/server/etc/nomad.d/alloc/9244a2d7-7f86-4859-4523-96d59f5cef06/server/etc/puppetlabs/puppet/ssl/certificate_requests` all one directory path here? 

If so is there any chance that the node's [`data_dir` configuration](https://www.nomadproject.io/docs/configuration/index.html#data_dir) is somewhere in the directory included in the chroot? We have a warning about that in the documentation (this warning should also apply to the `exec` driver):

> WARNING: This directory must not be set to a directory that is included in the chroot if you use the exec driver.

**Comment by akshatgit** [comment]
akshat.s@c-1:~$ cat /etc/nomad.d/client.hcl
datacenter = "dc-1"
data_dir   = "/etc/nomad.d"

client {
  enabled = true
}
I missed the warning, will try it with new data_dir. 

Thanks.
