### ISSUE TITLE
setting Access-Control-Allow-Origin header on http api

### ISSUE THREAD

**Issue by MansM** [hashicorp/nomad#697]
I was creating a small ui for nomad to allow me to see the status of jobs in a webbased format.
When using jQuery I stumbled on the fact that nomad doesnt set the Access-Control-Allow-Origin header. This results in browser messages like: XMLHttpRequest cannot load http://10.0.50.11:4646/v1/jobs?pretty&_=1453414011020. Response for preflight has invalid HTTP status code 405
index.html:70 ajax error 0

I would probably be able to fix this with using a reverse proxy, but I would like to configure a setting to enable setting the header Access-Control-Allow-Origin: *

**Comment by kenvanhoeylandt** [comment]
I suggest to also add support for `Access-Control-Request-Method` and `Access-Control-Request-Headers` too.
A temporary hack could be just relaying the requested values in the `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` response.

**Comment by diptanu** [comment]
@MansM @kenvanhoeylandt You should be able to configure the API servers to set arbitrary headers via the agent configuration with this PR. Hoping that would work for you?
