### ISSUE TITLE
Windows CI Failure: Chocolatey points to a removed version of Make

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#6990]
The chocolatey package for Make points to Make version `4.2.1` which has been removed from the upstream package host (https://sourceforge.net/projects/ezwinports/files/)

I couldn't find a way to PR an updated version of the package (https://chocolatey.org/packages/make does not link to the source), so we're blocked on waiting for the upstream if we want to avoid maintaining windows packages ourselves.

**Comment by tgross** [comment]
I've sent a patch to the upstream maintainers of the Chocolaty package.

**Comment by tgross** [comment]
Looks like this has been resolved. Appveyor runs are showing that we're pulling Make 4.3, and are passing now.
