### ISSUE TITLE
CSI:  CLI/API to support showing  volume info in nomad node status

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6991]
Once volume mounting is implemented(TODO link PR), the CLI for `nomad node status` should show information about volumes on that node. 

Things to consider:
   - What information to show about volumes on that node
   - If we have fingerprinting/stats emission from used volumes, could show usage stats here

**Comment by tgross** [comment]
The design work here is related to @langmartin's work on https://github.com/hashicorp/nomad/issues/6973 so I'm going to assign it to him for now and then once that's done he can flesh out this issue with the details. (And then we can find the issue a new owner if need be.)
