### ISSUE TITLE
 CSI: plugin ACLs

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6992]
This issue covers ACLs implementations for plugins.

---

Plugin management:

* `csi-register-plugin`: a namespaced ACL required to submit a job that defines a CSI plugin
* `plugin { policy = "read" }`: list all plugins or read details about a specific plugin
  - the plugin's allocations are filtered to the namespace if the client has `read-jobs` permission
* `plugin { policy = "list" }`: list all plugins

APIs controlled by these ACLs:

* `GET /csi/plugins?type=csi`: requires `policy = "read"` or `policy = "list"` ACL
* `GET /csi/plugin/:id`: requires `policy = "read"` ACL

**Comment by tgross** [comment]
Going to close this in lieu of internal tracking issue for RFCs

**Comment by tgross** [comment]
Actually, going to use this issue as a placeholder for the implementation of the design in that RFC.

**Comment by tgross** [comment]
I've updated this task to cover the plugin ACLs only and split out the volumes ACLs to https://github.com/hashicorp/nomad/issues/7305

**Comment by langmartin** [comment]
I edited the description to reflect the non-namespace plugins

**Comment by langmartin** [comment]
Closed by #7380
