### ISSUE TITLE
Windows exec fails regardless of command passed

### ISSUE THREAD

**Issue by Supernomad** [hashicorp/nomad#700]
So I have been trying everything I can to get `raw_exec` to work through nomad for the past day.

From what I can tell there doesn't seem to be any environment being passed to the actual allocation execution, so everything fails. For instance calls to standard exe's like `powershell` or `net` do not work correctly, even when passed the fully qualified paths or when specified to run non-interactively.

The only commands I can actually get to work are built into CMD, like dir, echo, copy.However when a simple command like `echo %PATH%` is executed it just spits back `%PATH%` in the alloc logs. Showing that ENV expansion is broken at the very least.

Essentially this renders windows support completely useless.

I have attached the nomad specification and the logs from the last attempt. And I have confirmed every command works fine when executed via a local shell or remotely via winrs. This is definitely an issue with nomad either with the specification, configuration, or with the system itself.

[client.hcl.txt](https://github.com/hashicorp/nomad/files/101440/client.hcl.txt)
[spec.hcl.txt](https://github.com/hashicorp/nomad/files/101446/spec.hcl.txt)
[alloc-logs.txt](https://github.com/hashicorp/nomad/files/101448/alloc-logs.txt)

EDIT:
Forgot to add version numbers:
Nomad Version: 0.2.3
Consul Version: 0.6.0
Windows Server 2012 R2 (Fully updated as of today)

EDIT2: 
I tried running a simple C# console app that has 0 dependencies other than the .net framework (which is fully installed) and this fails as well either when called directly, wrapped in a cmd call, or wrapped in a bat file. 

This same program works flawlessly via a local shell and via winrs

EDIT3:
I have confirmed this is environment related, I did a list of all environment variables available locally and stuffed them all into a `env {}` clause in the job spec. This seems to have worked, but I feel like they should be auto-populated, for instance things like `HOMEPATH` and `PROCESSOR_ARCHITECTURE` can definitely be different from machine to machine, they just happened to line up right for me.

**Comment by dadgar** [comment]
We now populate the environment variables so this shouldn't be a problem from 0.3.2 onwards.
