### ISSUE TITLE
volume_mount host volumes not creating mount directory

### ISSUE THREAD

**Issue by tommyalatalo** [hashicorp/nomad#7000]
### Nomad version
0.10.2

### Operating system and Environment details
Linux/Docker

### Issue
When mounting a host volume into a docker container as shown below, the target directory is not created. It seems to be expected that it's already present, but this is not stated anywhere in the documentation for volume_mount.

### Reproduction steps
1. Create host volume "vol" on client(s)
2. Create job file as below
3. Mount host volume to non-existing path in container

### Expected behavior
Expected the host volume to be mounted into the specified destination "/mydir", which should have been created if it does not exist.

### Actual behavior
The directory "/mydir" is not found in the container and the host volume is seemingly not mounted at all.

### Proposed solution
If the behavior above is intended, then the docs need to be clarified on how to mount to a directory that doesn't already exist in the container.

### Job file (if appropriate)
```
    group "volgroup" {
    count = 1

    volume "vol" {
      type      = "host"
      read_only = false
      source    = "vol
    }

    task "voltask" {
      driver = "docker"

      volume_mount {
        volume      = "myvolume"
        destination = "/mydir"
        read_only   = false
      }

      config {
        image = "example:v1"
        port_map = {
          http = 80
        }
     }
```

**Comment by tgross** [comment]
Hi @tommyalatalo! Thanks for reporting this. I wasn't quite able to reproduce the behavior as I understand it. I tested with the Nomad configuration and job spec found below, and then ran the job. I used `nomad alloc exec` to check the filesystem of the resulting container and found the volumes I expected to be there (see below).

Can you provide the Nomad client configuration you're using? Even if the volumes are misconfigured, I'd hope to see some error messaging telling you what went wrong, so if you can provide an excerpt from the logs that would be helpful too.

```
▶ nomad alloc status 11f4
ID                  = 11f45d03-599d-0557-3674-f01029ad8ce1
Eval ID             = 5824afff
Name                = example.volgroup[0]
Node ID             = e3ecff02
Node Name           = testing
Job ID              = example
Job Version         = 0
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 16s ago
Modified            = 6s ago
Deployment ID       = 42f311c8
Deployment Health   = healthy

Task "voltask" is "running"
Task Resources
CPU        Memory          Disk     Addresses
0/100 MHz  28 KiB/300 MiB  300 MiB

...

▶ nomad alloc exec 11f4 /bin/sh
/ # ls /
alloc    dev      home     mydir    root     sys      usr
bin      etc      local    proc     secrets  tmp      var
/ # ls mydir
github.com    golang.org    gotest.tools
```

---

Job spec:

```hcl
job "example" {

  datacenters = ["dc1"]

  group "volgroup" {
    volume "vol" {
      type      = "host"
      read_only = true
      source    = "src"
    }

    task "voltask" {
      driver = "docker"

      volume_mount {
        volume      = "vol"
        destination = "/mydir"
        read_only   = true
      }

      config {
        image   = "busybox:1"
        command = "sleep"
        args    = ["600"]
      }
    }
  }
}
```

Nomad configuration:

```hcl
log_level = "DEBUG"

data_dir = "/var/nomad"

name = "testing"

enable_debug = true

client {
  enabled = true

  host_volume "src" {
    path      = "/opt/gopath/src"
    read_only = true
  }
}

server {
  enabled          = true
  bootstrap_expect = 1
}
```

**Comment by tommyalatalo** [comment]
I think I may have had something misconfigured in some way, because after several tries back and forth the volume ended up mounting correctly. I don't have any logs to supply now, as it started working.

**Comment by tgross** [comment]
Ok, good to hear! I'm going to close this issue but if you run into more problems feel free to re-open.
