### ISSUE TITLE
No Makefile

### ISSUE THREAD

**Issue by lwileczek-dmc** [hashicorp/nomad#7004]
### Nomad version
Output from `nomad version`
0.10.0
### Operating system and Environment details
Debian 9 
### Issue
No Makefile or bootstrap file. 

Instructions [here](https://www.nomadproject.io/guides/install/index.html#compiling-from-source) say to call
```shell
$ make boostrap
```
After cloning the repo and switching into `./nomad`.  There is no make file and thus the command cannot find the target and compile from source. Cannot install Nomad this way. 

### Reproduction steps
Provided you have a box with Go already configured, use the steps [here](https://www.nomadproject.io/guides/install/index.html#compiling-from-source) where say:

```shell
$ mkdir -p $GOPATH/src/github.com/hashicorp && cd $_
$ git clone https://github.com/hashicorp/nomad.git
$ cd nomad
$ make bootstrap
```
> make: *** No rule to make target 'bootstrap'.  Stop.

**Comment by tgross** [comment]
Hi @lwileczek-dmc! Thanks for reporting this. I just checked the build instructions from a fresh `debian:9` container and couldn't reproduce this. The `bootstrap` target should be here: https://github.com/hashicorp/nomad/blob/master/GNUmakefile#L139. Do you have a non-standard version of Make installed (like a BSD Make?) that's not finding that file?

**Comment by lwileczek-dmc** [comment]
Hello @tgross Turns out I'm a huge doofus. 

Thanks
