### ISSUE TITLE
QUESTION: Nomad as Jenkins Cloud?

### ISSUE THREAD

**Issue by nnordrum** [hashicorp/nomad#701]
Anybody seen anything or tried to use Nomad as a cloud for Jenkins? You could either do a java task or a Docker container (my preferred).

**Comment by dadgar** [comment]
I am sure it is possible, just a matter of getting the job configuration right. I am going to close this but hopefully someone from the community can comment if they have experience with this,

**Comment by diatmpravin** [comment]
Does any one tried Jenkins?

**Comment by dadgar** [comment]
@iverberk ^

**Comment by iverberk** [comment]
@diatmpravin I'm actually just in the process of finishing up a platform setup and blog post around using Jenkins with Nomad. If you like you can try it by following the instructions here: https://github.com/iverberk/nomad-ci. I Hope you find it useful. An overview blog will follow shortly, which I will add as a note here.

**Comment by diatmpravin** [comment]
@iverberk I have tried https://github.com/dontrebootme/nomad-intro.git it works for me. 
consul                    running (virtualbox)
nomad                     running (virtualbox)
docker1                   running (virtualbox)
docker2                   running (virtualbox)
docker3                   running (virtualbox)
I will wait for your blog for better understanding.  thanks for update.

**Comment by iverberk** [comment]
@diatmpravin In case you are still interested: http://www.ivoverberk.nl/scalable-ci-cd-with-nomad-and-jenkins/

**Comment by yikaus** [comment]
@iverberk I more like use nomad as embed solution just for scale jenkins slaves .see my example https://github.com/yikaus/jenkins-on-nomad
