### ISSUE TITLE
Support for .dockercfg

### ISSUE THREAD

**Issue by fatihcode** [hashicorp/nomad#702]
Is there any plan for supporting `.dockercfg` file? I would like to prevent having private Docker registry information in job definition. Basically we can let Docker daemon to use a local `.dockercfg` file to pull images from private registry.

**Comment by diptanu** [comment]
Sure we can.

**Comment by cmfatih** [comment]
It should not be so hard ( I've implemented it into `nomad-syncer` in a few hours. )

Thanks :+1:

**Comment by dadgar** [comment]
Fixed by #773
