### ISSUE TITLE
Allow nomad UI in iframes

### ISSUE THREAD

**Issue by michalgm** [hashicorp/nomad#7056]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
v0.9.7+ent

### Issue
We have built a internal web app that provides a streamlined view into the various components of our cloud architecture. The app primarily acts as glue around a series of iframes to app-specific UIs. 
We have been using the 3rd-party hashi-ui for our view into nomad jobs, but would like to switch to your much-improved native nomad ui (great work, btw!). However, currently we are unable to do this, as the ui returns a restrictive content-security-policy header that disallows it being used in an iframe: 
`content-security-policy: default-src 'none'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline' 'self'; form-action 'none'; frame-ancestors 'none'`

Is there any possibility the `frame-ancestors 'none'` could be removed from the policy? Or the policy could be made configurable?
Relevant code line: https://github.com/hashicorp/nomad/blob/dd8fbf476e2ecc6cb756c7f9db1c242fcbcbd61f/command/agent/http.go#L367

### Reproduction steps
Load nomad-ui in an iframe. It will fail to load.

**Comment by DingoEatingFuzz** [comment]
Hi @michalgm! Thank you for the issue (and the nice words!) This is definitely a use case we'd like to support, but we don't want to drop `frame-ancestors 'none'` from the currently hard-coded CSPs. Removing it means opening up room for clickjacking and phishing attacks.

We definitely want to make it configurable though! Vault [currently has an API for configuring UI headers](https://www.vaultproject.io/api-docs/system/config-ui/) that we might emulate. I think some sort of server hcl config may also be a nice path to pursue.

**Comment by ebarriosjr** [comment]
Has there been any progress on this? I can't find any option in the nomad api that works like the vault one.

**Comment by tgross** [comment]
A configurable CSP has been merged in #18085 and will ship in the next regular release of Nomad.
