### ISSUE TITLE
Documentation guide for Consul Connect with ACLs enabled

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#7057]
Write a documentation guide for Consul Connect when Consul ACLs are enabled.

Followup from #6905

**Comment by leptonyu** [comment]
Cloud you please write a simple one first?

**Comment by commarla** [comment]
I was a bit lost last week needed this doc but here are my notes :

* enable gRPC on consul clients
* add consul token in nomad config

I spent some time understanding we needed a consul token in nomad config to tell nomad to derive a SI token. https://github.com/hashicorp/nomad/blob/f5eba8d3b805029f0bb58e7f286f8890d98393e6/client/allocrunner/taskrunner/task_runner_hooks.go#L112

My token was in consul client config. I had to add one to nomad's config.

**Comment by leptonyu** [comment]
@commarla Thanks. I use master key, and it works.

Do you have some advices on how to specify the consul acl polices for nomad client?

**Comment by commarla** [comment]
@leptonyu I used this policy

```
agent_prefix "" {      
  policy = "read"    
}   
node_prefix "" {    
  policy = "write"    
}    
service_prefix "" {    
  policy = "write"  
}    
key_prefix "" {    
  policy = "read"    
}    
session_prefix "" {    
  policy = "write"    
} 
acl = "write"  
``` 
I added `acl = "write"` because the derived token should be able to create ACL for Service Identity (I think ...).

It's working and I (like you) waiting for the official documentation.

**Comment by leptonyu** [comment]
You're right. acl need to turn on 'write'.  But it's not good.

My working policy is this.
```
acl = "write"
key_prefix "nomad/" { policy = "write" }
node_prefix "" { policy = "read" }
agent_prefix "" { policy = "read" }
service_prefix "" { policy = "write" }
```

**Comment by sriyer** [comment]
> acl need to turn on 'write'. But it's not good.
agree! ... these tokens are part of nomad config and unless that is secure, any one can create a management token out of it!

**Comment by shoenig** [comment]
With massive thanks for efforts from @angrycub, we have a guide!
https://learn.hashicorp.com/nomad/consul-integration/nomad-connect-acl

**Comment by angrycub** [comment]
h/t to @spuder and @skipperza for their work with rough cuts of the guide and for all the awesome feedback.
