### ISSUE TITLE
client.driver_mgr.exec: error receiving stream from Stats executor RPC

### ISSUE THREAD

**Issue by surajthakur** [hashicorp/nomad#7061]
### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

### Operating system and Environment details
OS: Ubuntu 16.04
We have a setup of 3 node nomad server  and 3 node nomad client cluster

### Issue
We are running spark jobs in cluster mode using Nomad. I have taken the stable version of the spark-2.3.2-bin-nomad binary. Below is a snippet on how I run the job. 
When I am running an example job of spark-submit I get this error at my driver node which kills the executors and then itself and then the job fails. 

ERRORS from the driver machine:
nomad[30454]:     2020-02-04T00:52:07.649Z [ERROR] client.driver_mgr.exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=326a1109-b644-5f8e-fccc-afdc2a30c2bb driver=exec task_name=driver error="rpc error: code = Unavailable desc = transport is closing	"
nomad[30454]:     2020-02-04T00:52:07.649Z [ERROR] client.alloc_runner.task_runner.task_hook.stats_hook: failed to start stats collection for task: alloc_id=326a1109-b644-5f8e-fccc-afdc2a30c2bb task=driver error="rpc error: code = Canceled desc = grpc: the client connection is closing"

ERRORS from executor machine: 
20/02/04 05:40:56 INFO Executor: Finished task 0.0 in stage 1.0 (TID 1). 1699 bytes result sent to driver
20/02/04 05:40:57 ERROR CoarseGrainedExecutorBackend: RECEIVED SIGNAL INT
20/02/04 05:40:57 INFO DiskBlockManager: Shutdown hook called
20/02/04 05:40:57 INFO ShutdownHookManager: Shutdown hook called

The executor send the results but driver is not able to collect back the results due to the RPC issue.

Could anyone help with this issue?

### Job file (if appropriate)
spark-submit --class org.apache.spark.examples.JavaSparkPi --master nomad --deploy-mode cluster --conf spark.executor.instances=1 --conf spark.nomad.executor.cpu="3000" --conf spark.nomad.driver.cpu="3000" --conf spark.nomad.dockerImage=rcgenova/spark --conf spark.nomad.cluster.monitorUntil=complete --conf spark.nomad.sparkDistribution=https://github.com/hashicorp/nomad-spark/releases/download/v2.3.2-nomad-0.8.6-20191029/spark-2.3.2-bin-nomad-0.8.6-20191029.tgz https://github.com/hashicorp/nomad-spark/releases/download/v2.3.2-nomad-0.8.6-20191029/spark-examples_2.11-2.4.0.jar 100

**Comment by cgbaker** [comment]
@surajthakur , can you provide the stderr and stdout from the driver allocation?

**Comment by cgbaker** [comment]
also, the output of `nomad status <spark-job>`?

**Comment by surajthakur** [comment]
I have run my job using the following command: 

spark-submit --class org.apache.spark.examples.JavaSparkPi --master nomad --deploy-mode cluster --conf spark.executor.instances=1 --conf spark.nomad.executor.cpu="3000" --conf spark.nomad.driver.cpu="3000" --conf spark.nomad.cluster.monitorUntil=complete --conf spark.nomad.sparkDistribution=https://github.com/hashicorp/nomad-spark/releases/download/v2.3.2-nomad-0.8.6-20191029/spark-2.3.2-bin-nomad-0.8.6-20191029.tgz https://github.com/hashicorp/nomad-spark/releases/download/v2.3.2-nomad-0.8.6-20191029/spark-examples_2.11-2.4.0.jar 100

I am using spark-2.3.2-bin-nomad provided in nomad spark repo as stable and its example jar

Output of nomad status <spark-job>

ubuntu@nomad-server-staging-1:~$ nomad job status org.apache.spark.examples.JavaSparkPi-2020-02-06T23:20:43.041Z
ID            = org.apache.spark.examples.JavaSparkPi-2020-02-06T23:20:43.041Z
Name          = org.apache.spark.examples.JavaSparkPi
Submit Date   = 2020-02-06T23:23:38Z
Type          = batch
Priority      = 40
Datacenters   = dc1
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
driver      0       0         0        0       1         0
executor    0       0         0        0       1         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
fe1b8409  6e039cac  executor    1        stop     complete  2m1s ago   32s ago
ddcaf5ab  fe378900  driver      2        run      complete  3m27s ago  32s ago
ubuntu@nomad-server-staging-1:~$ 



Driver and Executor Std Errors are uploaded
[executor_stderr.txt](https://github.com/hashicorp/nomad/files/4168238/executor_stderr.txt)
[driver_stderr.txt](https://github.com/hashicorp/nomad/files/4168240/driver_stderr.txt)

**Comment by zhenik** [comment]
Any update on it?

**Comment by luckymike** [comment]
Hey, we'd love to see this reopened and get some guidance on what causes it. We're seeing it with raw_exec jobs on both Windows (powershell scripts) and Linux (bash). In our case, I believe all the instances are tied to periodic jobs, if that's helpful.

**Comment by tgross** [comment]
@luckymike let's open a new issue with the details specific to your situation.
