### ISSUE TITLE
Nomad documentation website is not refreshed

### ISSUE THREAD

**Issue by zhenik** [hashicorp/nomad#7081]
### Issue
Webpage with documentation is not refreshed to the latest master branch state.

#### Example of merged PR https://github.com/hashicorp/nomad/pull/6782/commits/2ac062b0d02f35c6e90aa6bc696af2708eafb2b2#diff-7afeab350c1416cc40ee43a356bd93b5R92  

```
### `port` Parameters

- `static` `(int: nil)` - Specifies the static TCP/UDP port to allocate. If omitted, a dynamic port is chosen. We **do not recommend**  using static ports, except
  for `system` or specialized jobs like load balancers.
- `to` `(string:nil)` - Applicable when using "bridge" mode to configure port
  to map to inside the task's network namespace. `-1` sets the mapped port equal to the dynamic port allocated by the scheduler. The `NOMAD_PORT_<label>` environment variable will contain the `to` value.
```

#### Example web 
![Capture1](https://user-images.githubusercontent.com/15572799/73840047-9d604080-4817-11ea-9914-504a74b02ac2.PNG)

**Comment by tgross** [comment]
Hi @zhenik! We're in the middle of a bit of a documentation website upgrade, and so we pausing pushes of docs from master to the stable website branch until that's done. (No later than the upcoming 0.11 release.)
