### ISSUE TITLE
[Feature Request] Have the UI display dispatch meta

### ISSUE THREAD

**Issue by erhlee-bird** [hashicorp/nomad#7096]
Nomad Version: 0.10.2

When viewing the UI for a dispatch job (e.g. https://{nomad_host}:4646/ui/jobs/example%2Fdispatch-1581087170-86bf33c6), it would be really helpful to see the dispatch "Meta" fields in a similar fashion to the "Payload" box.

![image](https://user-images.githubusercontent.com/633268/74041434-9d854b00-4993-11ea-94a6-557f6ac616a6.png)

**Comment by kylejmcintyre** [comment]
We just encountered this as well...big bummer since we use dispatch job heavily.
