### ISSUE TITLE
UI: Logging doesn't support emojis

### ISSUE THREAD

**Issue by Y-Tian** [hashicorp/nomad#7103]
If filing a bug please include the following:

### Nomad version
`Nomad v0.10.2`

### Operating system and Environment details
`MacOS running a Go binary`

### Issue
Nomad UI logging output doesn't support emojis. I'm running a Go binary that uses `"github.com/kyokomi/emoji"` standard Unix emojis. 

Output should be: 👨‍🍳
What I see: ð¨âð³ 

### Reproduction steps
Deploy any job that logs emojis to stdout. The emojis aren't supported.

**Comment by DingoEatingFuzz** [comment]
Fixed in #7470 and #7551 and available in Nomad 0.10.6 and 0.11.x
