### ISSUE TITLE
[question] UI: Unicode chars in logs are not supported?

### ISSUE THREAD

**Issue by MikeVL** [hashicorp/nomad#7105]
### Nomad version
Nomad v0.10.3

### Nomad Client logs
`nomad logs -stderr`
<img width="422" alt="Снимок экрана 2020-02-10 в 15 12 56" src="https://user-images.githubusercontent.com/118285/74149027-d46b9300-4c17-11ea-8008-76824ad5df61.png">

### Nomad Client logs in UI

<img width="429" alt="Снимок экрана 2020-02-10 в 15 09 10" src="https://user-images.githubusercontent.com/118285/74148786-4e4f4c80-4c17-11ea-914f-6c4bae197528.png">

**Comment by tgross** [comment]
Hi @MikeVL! That's definitely something we want to fix. I'm going to close this as a dupe of https://github.com/hashicorp/nomad/issues/7103
