### ISSUE TITLE
$node.class constraint filtering fails

### ISSUE THREAD

**Issue by jhartman86** [hashicorp/nomad#711]
Deets:
- Have two client nodes marked with class "services".
- Trying to apply a job constraint such that it only runs on nodes marked as "services".

Relevant part of job file:
```
{
... task definition:
  "test": {
    "constraint": [{
      "attribute": "$node.class",
      "value": "services"
    }],
    "driver": "docker"
  }
}
```

Its only asking for a teeny-weeny amount of resources, and gets scheduled fine without the constraint (onto the service nodes).

Is this: a) the correct constraint definition? or b) a bug?

Also, output from `$: nomad node-status` to see node classes:
```
ID                                    DC     Name      Class     Drain  Status
a5272dc9-c08a-65d0-acbf-825c234ecbfa  local  clnt2     services  false  ready
734f6357-d468-5442-ae84-b76a7ebc14ac  local  clnt1     services  false  ready
28f7a201-26fc-87c3-e13d-373438e48570  local  frontman  <none>    false  ready
```

**Comment by iverberk** [comment]
What is the actual error? Can you provide logs from the scheduler that shows why the placement failed?

**Comment by jhartman86** [comment]
@iverberk Sure thing:
Evaluation output (`$: nomad run simple.nomad`):
```
==> Monitoring evaluation "278ccb39-e2d4-9093-f48f-597a16c423fc"
    Evaluation triggered by job "simple"
    Scheduling error for group "gtest" (failed to find a node for placement)
    Allocation "a0145061-bdd7-8f38-59c0-184d89023d68" status "failed" (3/3 nodes filtered)
      * Class "services" filtered 2 nodes
      * Constraint "$node.class = services" filtered 3 nodes
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "278ccb39-e2d4-9093-f48f-597a16c423fc" finished with status "complete"
```

`$: nomad status simple`
```
ID          = simple
Name        = simple
Type        = service
Priority    = 50
Datacenters = local
Status      = <none>

==> Evaluations
ID                                    Priority  TriggeredBy   Status
278ccb39-e2d4-9093-f48f-597a16c423fc  50        job-register  complete

==> Allocations
ID                                    EvalID                                NodeID  TaskGroup  Desired  Status
a0145061-bdd7-8f38-59c0-184d89023d68  278ccb39-e2d4-9093-f48f-597a16c423fc  <none>  gtest      failed   failed
```

`$: nomad alloc-status a0145061-bdd7-8f38-59c0-184d89023d68`
```
D                = a0145061-bdd7-8f38-59c0-184d89023d68
EvalID            = 278ccb39-e2d4-9093-f48f-597a16c423fc
Name              = simple.gtest[0]
NodeID            = <none>
JobID             = simple
ClientStatus      = failed
NodesEvaluated    = 3
NodesFiltered     = 3
NodesExhausted    = 0
AllocationTime    = 12.655µs
CoalescedFailures = 2

==> Task "ttest" is "dead"
Recent Events:
Time  Type  Description

==> Status
Allocation "a0145061-bdd7-8f38-59c0-184d89023d68" status "failed" (3/3 nodes filtered)
  * Class "services" filtered 2 nodes
  * Constraint "$node.class = services" filtered 3 nodes
```

Let me know if you want anything else (and if thats even what you're looking for).

**Comment by dadgar** [comment]
Are you running off master? I just tested it and it was working for me?

**Comment by jhartman86** [comment]
@dadgar D/L'd the 0.2.3 binary. I'll do a build off master this evening and report back.

**Comment by let4be** [comment]
Same situation here on 0.2.3 - $node.class constraint fails...

**Comment by let4be** [comment]
Okay, meta data constraint saved the life :)

**Comment by jhartman86** [comment]
@let4be - Did the exact same thing, meta constraint worked a charm.

**Comment by dadgar** [comment]
0.2.3 does not have this constraint, it will come out with 0.3

**Comment by jhartman86** [comment]
@dadgar - Thanks for clarifying. Given that 0.2.3 doesn't have this constraint, but it was still documented, its obviously not ideal for all parties involved to not have clarification on whether the release one may be using supports a given feature or not. As users, we feel like we're missing something, and end up filing an issue to report what we perceive as a bug - subsequently wasting your time having to sort through these. If I can make a suggestion - it would be helpful to have docs tied to the versions. Maybe a drop down somewhere to select the release like so (obviously a rough mock up, just food for thought):

![screen shot 2016-02-02 at 10 40 38 am](https://cloud.githubusercontent.com/assets/725280/12758467/a07f7994-c999-11e5-8701-e45fbc13f13c.png)

**Comment by dadgar** [comment]
@jhartman86: Our docs are pinned to the most current release. There was a mistake in which the ability to constrain by node class was included in the docs before it was implemented. If you look at master ,the docs have diverged quite a bit from what is on nomadproject.io/docs. That is why we didn't push a quick update to the website. We will be releasing 0.3 shortly, which will rectify this and hopefully bring other features people will enjoy :)

**Comment by jhartman86** [comment]
@dadgar - Makes sense. Keep up the good work and kudos on the response time.
