### ISSUE TITLE
Feature request: host_volume subdirectory mounts

### ISSUE THREAD

**Issue by Legogris** [hashicorp/nomad#7110]
Given a host volume:
```
host_volume "dir1" {
  path = "/data"
  read_only = false
}
```
If one wants to mount `/data/subdir` in a volume mount today, one has to create a separate host_volume for that on the node.
It would be great if this could be specified directly on the job.

Seems like low-hanging fruit that would ease a lot of friction :)

**Comment by tgross** [comment]
Hi @Legogris! I'm not sure I understand the request. Can you show me an example jobspec that doesn't work today but could with this feature?

**Comment by Legogris** [comment]
Sure!
Given the host volume above and that we want to mount host directory `/data/hello` to `/hello`:
```
job "hello" {
  group "hello" {
    task "hello" {
      volume_mount {
        volume = "data"
        destination = "/hello"
      }
    }
    volume "data" {
      type      = "host"
      source    = "dir1/hello"
      read_only = true
    }
  }
}
```

I can also imagine the subpath being either:
* part of the task`volume_mount.volume`
* separate field on task  `volume_mount`
* separate field on group `volume`

Here's a scenario where this makes things a lot easier: One job writing data to a directory tree, where each root directory should also be mounted separately in a different job for reading. Or the inverse. As things are currently working, each additional subpath that should be mounted on a specific path in a task requires adding additional host volumes on clients, despite the path already included in an existing host volume.

**Comment by tgross** [comment]
Ok I understand now and could see the use case. I'm going to be working on #6709 for 0.11.1, which will touch this area of the code. So when I do I'll take look in detail to see whether there's any feasibility issues with it.

As your example shows, `source` field is currently the ID of the host volume and not a path. This is particularly important with respect to CSI, where the volume may not even exist as a path until the job is launched. So if we were to implement this, we'd definitely want to have some additional field on `volume` or `volume_mount`, rather than overloading the one we have.

**Comment by Legogris** [comment]
> Ok I understand now and could see the use case. I'm going to be working on #6709 for 0.11.1, which will touch this area of the code. So when I do I'll take look in detail to see whether there's any feasibility issues with it.
> 
> As your example shows, `source` field is currently the ID of the host volume and not a path. This is particularly important with respect to CSI, where the volume may not even exist as a path until the job is launched. So if we were to implement this, we'd definitely want to have some additional field on `volume` or `volume_mount`, rather than overloading the one we have.

That's great! Without having looked at the source or inner workings I figured that would probably be the case, so a separate field for the path within the volume definitely makes sense.

**Comment by tgross** [comment]
It looks like we have an issue open for this feature already (https://github.com/hashicorp/nomad/issues/6536) , so I'm going to close this as a duplicate just to make tracking easier. I'll link back to this discussion so that the various use cases here are covered.
