### ISSUE TITLE
CSI: create test utils/mocks for plugin/volumes

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#7123]
As I'm wrapping up #6903 I'm finding I'm writing a lot of error-prone code just to set up simple unit tests for CSI. We could use some test utils for this.

**Comment by langmartin** [comment]
-[ ] volume API tests in `api/csi_test.go`

**Comment by tgross** [comment]
This was mostly implemented by #7133. There's some refactoring to be done at some point to take advantage of this implementation on the tests, but that should cover this issue.
