### ISSUE TITLE
Docker images removal

### ISSUE THREAD

**Issue by irobert91** [hashicorp/nomad#713]
Nomad completely removes docker images on `nomad stop ...` if no other jobs are using the same image, even when the image has been pulled prior to `nomad run ...`.
Is this expected behavior?
I would like to not remove images to avoid pulling them again on the next `nomad run ...`. Is this possible? I couldn't find any related configuration options.

**Comment by MansM** [comment]
client {
  enabled = true
  options {
   docker.cleanup.image = false
  }

add this to your client config

**Comment by irobert91** [comment]
Adding `docker.cleanup.image = false` did the trick. And it's also in the [docs](https://www.nomadproject.io/docs/drivers/docker.html#docker_cleanup_image):
```hcl
client {
    enabled = true
    ...
    docker.cleanup.image = false
}
```

Thank you @MansM!
