### ISSUE TITLE
CSI: Support for `device` mode volumes

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#7139]
Currently we've only really been testing CSI for filesystem mounts and not devices.

We need to add support for mounting devices as part of shipping CSI. The "easiest" way to begin is probably "trying to run a job that requires one" repeatedly until you make it work, but the primary places to update will be:

- taskrunner/volume_hook: This will need to generate `drivers.DeviceConfig`'s for volumes where `IsDevice` is true. You'll also need to make sure these propagate to drivers correctly.
- allocrunner/csi_hook: We may need to generate different paths for volumes that desire a device attachment mode.

**Comment by tgross** [comment]
I took a quick look through some of the CSI providers in `kubernetes-sigs` and it looks like `BlockVolume` (device) support isn't yet implemented for all the storage providers . I'm wondering if it might make sense for us to ship 0.11 with support only for `MountVolume` and then add `BlockVolume` support in a point release? Do you have a better understanding of whether this should be treated as a show-stopper?

**Comment by endocrimes** [comment]
@tgross I'd personally be fine with deferring it but we should probably run that by @yishan-lin because the PRD had it as part of the success criteria so there may be some downstream communication required.

**Comment by tgross** [comment]
Doing some issue cleanup. It looks like we've resolved this with the work we did to validate VolumeCapabilities in https://github.com/hashicorp/nomad/pull/7831 and fixing the target path in https://github.com/hashicorp/nomad/pull/8505, and I've had working tests with DO volumes in `block-device` mode. Going to close this out.
