### ISSUE TITLE
Possible documentation error regarding `kill_signal`

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#7140]
Hi,

I am reading through signal handling:

> kill_signal (string) - Specifies a configurable kill signal for a task, where the default is SIGINT. Note that this is only supported for drivers sending signals (currently docker, exec, raw_exec, and java drivers).

From: https://nomadproject.io/docs/job-specification/task/#inlinecode-kill_signal

> The behavior is slightly different for Docker-based tasks. Nomad will run the docker stop command with the specified kill_timeout. The signal that docker stop sends to your container entrypoint is configurable using the STOPSIGNAL configuration directive, however please note that the default is SIGTERM.

From: https://nomadproject.io/guides/operating-a-job/update-strategies/handling-signals/

They seem to contradict each other. Does that mean:

- 1. `kill_signal` will not work for Docker-based workflows, as in the signal is ignored, and after the specified kill_timeout then `docker stop` will be sent, which will follow the `STOPSIGNAL`-directive from the Docker file.

- 2. `kill_signal` will work for Docker-based workflows, as in the signal is sent, and after the specified kill_timeout then `docker stop` will be sent, which will follow the `STOPSIGNAL`-directive from the Docker file.

**Comment by shoenig** [comment]
Thanks for reporting this @kaspergrubbe !
I think the [docker docs](https://docs.docker.com/engine/reference/commandline/stop/) for `docker stop` might clarify what is expected to happen
> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL.

The `docker stop` command issues the first signal (`SIGTERM` by default, configurable with `STOPSIGNAL`), and later if the process does not exit before `kill_timeout`, will issue `SIGKILL`.

Nomad's docs could probably be more clear about the default signal being different for docker in the `kill_signal` stanza, and reference the `docker stop` documentation in the update strategy docs for reference on what is happening "under the hood" with docker.
