### ISSUE TITLE
allow support golang context for nomad rpc

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#7142]
Now nomad doesn't allow make cancel for rpc calls, and with this we have some problems https://github.com/hashicorp/nomad/issues/4604(for example). So it will be nice if nomad will implement such functionality (i suspect that is best aproach to implement this using golang `context` concept, for exmaple we can get this context from `http Request` https://golang.org/pkg/net/http/#Request.Context), so it can minimize impact of various network problems, and perhaps allowed to localize some bugs

But this approach have some troubles:

1. IMHO is relatively hard work, due it required change many signatures of methods
2. nomad use `net/rpc` package which is frozen now, but exist a fork of this library(https://github.com/keegancsmith/rpc) which add golang `Context`(https://golang.org/pkg/context/) support, but  robustness of this fork not checked and it may contain some bugs
3. yamux library requires implement some Context functionalyty, but this is not too hard

**Comment by tgross** [comment]
Hi @tantra35 I just yesterday opened https://github.com/hashicorp/nomad/issues/7119 to discuss this. I'm going to close this issue as a dupe but let's chat about it over there!
