### ISSUE TITLE
Docker driver mount volume support / documentation

### ISSUE THREAD

**Issue by dsklopp** [hashicorp/nomad#715]
Nomad does not support (or does not document) how to mount volumes on a Docker container.  A use case here being mounting the host /var/lib/cassandra directory to my cassandra docker container.  The Docker syntax to do this is the -v switch.  For example:

docker run --name cass-master -d -v /var/lib/cassandra:/var/lib/cassandra  cassandra

Can this support please be added, or, if already present, documented.

Thank you,
-Dan

**Comment by diptanu** [comment]
@dsklopp This is coming in v0.4

**Comment by dadgar** [comment]
Closing since we have other open issues around supporting volumes

**Comment by dsklopp** [comment]
@diptanu when is v0.4 expected to be released?  I am prototyping Nomad for our Docker environment, and I need to plan accordingly.

**Comment by diptanu** [comment]
@dsklopp We are doing 0.3 in a few weeks. Tentatively Nomad 0.4 is going to be out sometime in March

**Comment by duffqiu** [comment]
does Nomad support dynamic volume according to docker's container's id or other identity?

**Comment by dadgar** [comment]
@duffqiu Please see the other open issues around volumes. They are currently not supported in Nomad

**Comment by shadabahmed** [comment]
Keeping fingers crossed for `v0.4` :smile:

**Comment by BastienM** [comment]
Any news on ```0.4``` ?
Got my cluster and jobs ready, just missing the volume for persistent data :)

**Comment by KamilLelonek** [comment]
What is the status there?

**Comment by jippi** [comment]
https://www.nomadproject.io/docs/drivers/docker.html#volumes ?

**Comment by KamilLelonek** [comment]
@jippi it mounts volumes, not devices, doesn't it?
