### ISSUE TITLE
status empty on /v1/jobs

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/nomad#716]
Why is the status (and status description) on `/v1/jobs` and `/v1/job/example` always an empty string? I was expecting `/v1/jobs` to give me an overview/summary on the status of the jobs without going into its allocations to see what happened, but it seems that there is no way to tell the status because it doesn't report anything back.

```
$ curl 'localhost:4646/v1/jobs?pretty'
[
    {
        "ID": "example",
        "Name": "example",
        "Type": "service",
        "Priority": 50,
        "Status": "",
        "StatusDescription": "",
        "CreateIndex": 5,
        "ModifyIndex": 2497
    }
]
```

**Comment by diptanu** [comment]
@cleung2010 This has been fixed on master 

/cc @dadgar
