### ISSUE TITLE
Nomad Job ip

### ISSUE THREAD

**Issue by ralph367** [hashicorp/nomad#7172]
Well I'm just new to nomad, I would like to ask a simple question, how is it possible to run a nomad job ( docker container ) but not locally.
So I'm running nomad from a server but once I run a job that starts a docker container the container is only locally how is it possible to map it to the server ip ?

thanks for your help

**Comment by tgross** [comment]
Hi @ralph367! There's not really enough information here to answer your question. Can you provide a jobspec that you're trying to run, what you expect to see, and what you're actually seeing?

**Comment by ralph367** [comment]
> Hi @ralph367! There's not really enough information here to answer your question. Can you provide a jobspec that you're trying to run, what you expect to see, and what you're actually seeing?

Okay first of all I start my nomad agent using 
`nomad agent -dev -bind=MY_SERVER_IP`

then I can connect to MY_SERVER_IP:4646 which opens nomad UI

And when I add this job file
`job "docs" {
  datacenters = ["dc1"]

  group "example" {
    task "server" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo"
        args = [
          "-listen", ":5678",
          "-text", "hello world",
        ]
      }

      resources {
        network {
          mbits = 10
          port "http" {
            static = "5678"
          }
        }
      }
    }
  }
}`

it runs perfectly but locally, so when I use docker ps -a I get this one

`09a48d9106b0        hashicorp/http-echo           "/http-echo -listen …"   16 seconds ago      Up 15 seconds            127.0.0.1:5678->5678/tcp, 127.0.0.1:5678->5678/udp   server-83e61985-cb71-971e-758f-64254e2a2c05
`

as you can see 127.0.0.1:5678, where as I want to connect to this job using MY_SERVER_IP:5678

**Comment by tgross** [comment]
There's a couple different ways you can expose the task to the external IP.
- If you want to keep the static port, you can switch the [`network_mode`](https://nomadproject.io/docs/drivers/docker/#inlinecode-network_mode-3) for the Docker config to be `host`.
- You can keep the default bridge networking and use a [dynamic port map](https://nomadproject.io/docs/job-specification/network/#dynamic-ports). If you do that, you'll probably also want to use a [`service`](https://nomadproject.io/docs/job-specification/service/) stanza to advertise the port to Consul.

(Also, I hope you don't mind @ralph367 but I edited your response slightly to fix the syntax highlighting. Use triple backticks to format a code block.)

**Comment by ralph367** [comment]
@tgross 

'''
job "docs" {
  datacenters = ["dc1"]

  group "example" {
    task "server" {
      driver = "docker"

      config {
        network_mode = "host"
        image = "hashicorp/http-echo"
        args = [
          "-listen", ":5678",
          "-text", "hello world",
        ]
      }

      resources {
        network {
          mbits = 10
          port "http" {
            static = "5678"
          }
        }
      }
    }
  }
}
'''

Yea just like you said it is working I can access my job now using the server IP thanks man

**Comment by tgross** [comment]
Great to hear!
