### ISSUE TITLE
type = "periodic" seems to trigger a segfault

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#7203]
### Nomad version
Client: Nomad `v0.10.3`
Server: Nomad `v0.10.1`

### Operating system and Environment details

Client: macOS `10.14.6`
Server: `Ubuntu 18.04.3 LTS`

### Issue

When running a job with a type non existing, it's triggering a segfault.

### Reproduction steps

```
nomad job run -verbose --address='https://xxx.example.com' ops-reaper.hcl
```

### Job file

https://gist.github.com/Y-Tian/a37959a21ac6134ab211d51f1b5d93ba

### Nomad Client logs

```
Error submitting job: Unexpected response code: 502 (<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
)
```

### Nomad Server logs

https://gist.github.com/scalp42/816cb82d2838e2edca6b0ee3966674a5

**Comment by jrasell** [comment]
Hi @scalp42, thanks for the detailed bug report. I was able to reproduce this with the examples you provided and have submitted a PR which resolves the bug.
