### ISSUE TITLE
[question] monitor alloction status

### ISSUE THREAD

**Issue by zd1990** [hashicorp/nomad#7213]
hi~how can I konw the alloction status change when it was killed or panic,like docker event command or api

**Comment by jrasell** [comment]
Hi @zd1990 and thanks for the question. If you are looking to monitor the status of an allocation, the Nomad API supports [blocking queries](https://nomadproject.io/api-docs/#blocking-queries) which can be used to monitor resources and process changes in their state. The [read allocation](https://nomadproject.io/api-docs/allocations/#read-allocation) API endpoint is specifically what would be useful in this case and provides detailed information regarding an allocation, including its current status and a list of events.

Nomad servers can also emit [job summary metrics](https://nomadproject.io/docs/telemetry/metrics/#job-summary-metrics) which would allow a more holistic view of allocation status changes within a job.

**Comment by zd1990** [comment]
Hi @jrasell,thansk for your replay,I want to monitor all the allocations status change,but the api can only monitor one allocation,has any go library can do this like that:
```
	f := filters.NewArgs()
	f.Add("event", "die")
	msgs, errs := cli.Events(ctx, types.EventsOptions{Filters: f})

	for {
		select {
		case err := <-errs:
			log.Error(err)
		case msg := <-msgs:
                        log.Info(msg)
		}
            }
```

**Comment by jrasell** [comment]
@zd1990 the Nomad API also supports blocking queries on [listing allocations](https://nomadproject.io/api-docs/allocations/#list-allocations) which includes status information for all allocations currently store within Nomad state.

[Here](https://github.com/jrasell/sherpa/blob/6baa7d27eb58c369280aee3522aa644faeabed20/pkg/watcher/job/job.go#L31) is some example code which performs blocks queries on the jobs API and then process updates as the query returns. I hope this proves useful.

**Comment by zd1990** [comment]
@jrasell  it worked!

Thank you.

**Comment by jrasell** [comment]
Excellent news @zd1990!
