### ISSUE TITLE
Question about the Telemetry address?

### ISSUE THREAD

**Issue by MattPumphrey** [hashicorp/nomad#7225]
We are working on our upgrade to Nomad 0.10.3 and we are also moving to the Datadog container agent as well.  Our goal is to be able to utilize the Consul lookup address to be able to find the closest agent as the servers will no longer have an agent on it.  How can we utilize this address in the telemetry stanza.

Currently in our stanza configs look a bit like this.
```
"consul": {
    "address": "0.0.0.0:8500",
    "token": "$TOKEN",
    "client_service_name": "nomad-client",
    "server_service_name": "nomad-server",
    "client_auto_join": true,
    "server_auto_join": true,
    "auto_advertise": true
  },
  "telemetry": {
    "datadog_address": "$PRIVATE_IP:8125", (here we want to use datadog.query.consul.)
    "publish_allocation_metrics": true,
    "publish_node_metrics": true,
    "disable_hostname": true
  },
```

Can you guys help provide some guidance on how to help provide this, as we know using the IP:port combo of a registered service within the container works but we want to be able to utilize it as part of the platform integration.

**Comment by shoenig** [comment]
Hey @MattPumphrey could you help clarify - is this question specifically about the `telemetry.datadog_address` not respecting Consul DNS (that is otherwise working), or is this about configuring Consul DNS in general? AFAIK there shouldn't be anything special with regard to using a prepared service query for the `datadog_address`.

**Comment by MattPumphrey** [comment]
This is something that I need to figure out, I am going to resolve this until I can dig deeper into it.
