### ISSUE TITLE
Question: boot an unhealthy or no-longer-existing client?

### ISSUE THREAD

**Issue by jhartman86** [hashicorp/nomad#723]
Forgive me if there is a documented way to do this, but wondering how you can boot/remove an unhealthy client node from the cluster. Had a node lock up (screenshot below, its clnt2), took it down and auto-rejoined the cluster, but now `$: nomad node-status` is remembering the unavailable clnt2, while creating a new entry for clnt2 again, but in a healthy state. So two "clnt2" nodes are appearing, one up and one down, although they're the same node - which I believe is not a desirable state.

I tried node-drain from a server node against the unhealthy one, hence why the clnt2 node marked as down is set to drain true. Ultimately, it seems like nomad let "clnt2" rejoin with the same name as what it thought was previously a different node, which in fact, it isn't.

In the second screenshot, notice 5th from the bottom (node ID: a5272dc9-c08a-65d0-acbf-825c234ecbfa) shows the the job as still running on the dead node.

![screen shot 2016-01-29 at 3 23 13 pm](https://cloud.githubusercontent.com/assets/725280/12689779/3d2c91c4-c69c-11e5-8d5a-bec9f80bb876.png)

![screen shot 2016-01-29 at 3 24 17 pm](https://cloud.githubusercontent.com/assets/725280/12689813/6902b97c-c69c-11e5-8cbe-bd434607b900.png)

**Comment by dadgar** [comment]
Hey, node name is just a human identifier for the node. Node ID is how nomad indexes nodes and you can see the two client2's have different IDs. Nomad will also run a GC for Nodes and failed allocations so they will be cleared from the system once the GC runs. Let me know if you have any other questions

**Comment by jhartman86** [comment]
@dadgar Right - node name as a human identifier makes sense. I guess the issue I was trying to highlight is that client2 failed, then rejoined, but instead of being recognized as client2 again, it become recognized as a new client2 - when its really the same node. And the "dead" client2 is just hanging round. Is node GC part of the 2.3 release?

**Comment by dadgar** [comment]
Hmm did you by chance remove the clients `data_dir`? The id is generated and persisted to disk. It is read when rebooting so that this exact thing doesn't happen!
