### ISSUE TITLE
Error submitting job: Unexpected response code: 400 (json: cannot unmarshal object into Go value of type int)

### ISSUE THREAD

**Issue by lettrung99** [hashicorp/nomad#724]
Hi,

I am trying to use the nomad api, but I am keep getting this error:

2016/01/29 21:39:54 Error submitting job: Unexpected response code: 400 (json: cannot unmarshal object into Go value of type int)

Could someone help please?

Thanks,

David

**Comment by diptanu** [comment]
@lettrung99 Can you please share the json you're posting? It's possibly happening because the json is not what the Nomad API isn't expecting.

**Comment by diptanu** [comment]
Closing this, since we have an example of the json request for submitting jobs.
