### ISSUE TITLE
Website has inconsistent claims about Nomad's size

### ISSUE THREAD

**Issue by cainejette** [hashicorp/nomad#7240]
The [Use Cases](https://nomadproject.io/use-cases/simple-container-orchestration/) page claims Nomad runs as a 35MB binary.

The [Intro](https://nomadproject.io/intro/) page claims it runs as a 75MB binary.

**Comment by jrasell** [comment]
Hi @cainejette, thanks for spotting and raising this issue. I have opened a PR to address this inconsistency.
