### ISSUE TITLE
Allocations Fail to Reschedule When Running on Ineligible Hosts

### ISSUE THREAD

**Issue by NicholasABriganti** [hashicorp/nomad#7244]
### Nomad version
Client Version: 0.8.7
Server Version: 0.8.7

### Issue
We have certain jobs in which each allocation needs to run on distinct hosts (handled by a `distinct_hosts` constraint). When trying to reschedule these allocations, we found that some had been running on nodes that had been marked `ineligible`. These allocations fail to reschedule on to other eligible hosts in the pool and instead caused blocked evaluations. From there, the allocation will actually _fail_ with 5 retries

It was expected that these allocations would move off of the ineligible host and onto a new, eligible host in the pool. The fact that the allocation instead becomes blocked and then actually fails with 5 retries seems concerning.

### Reproduction steps
1. Place some amount of `distinct_hosts` constrained allocations on hosts in a pool.
2. Mark one or more of these hosts as ineligible, but do not drain.
3. Reschedule the allocations.
4. Notice that the allocations on the ineligible host cause blocked evaluations.
5. Mark the host as eligible and notice that the allocation is then able to be rescheduled.

### Job file (if appropriate)
Relevant section:
```
  constraint {
    operator = "distinct_hosts"
  }
```
### Nomad Client logs (if appropriate)
![image](https://user-images.githubusercontent.com/5667412/75568594-92b55780-5a21-11ea-8938-7aab5aca1a26.png)
### Nomad Server logs (if appropriate)
```
Feb 26 12:31:38 nomad-server-i-003399652f3f9dc56.node.seatgeek.prod nomad[6139]:     2020-02-26T12:31:38.956Z [DEBUG] nomad: plan for node rejected: node_id=3bbebe49-9e68-2dbe-3325-7025d0cf4809 reason="node is not eligible for draining"
Feb 26 12:31:38 nomad-server-i-003399652f3f9dc56.node.seatgeek.prod nomad[6139]: worker.service_sched: reconciled current state with desired state: eval_id=9509fdbf-e48e-6f73-577a-54ec772bcadc job_id=trebek-es-facts-67 namespace=default results="Total changes: (place 0) (destructive 0) (inplace 2) (stop 0)
                                                                                 Desired Changes for "trebek-es-facts-67-data": (place 0) (inplace 1) (destructive 0) (stop 0) (migrate 0) (ignore 3) (canary 0)
                                                                                 Desired Changes for "trebek-es-facts-67-master": (place 0) (inplace 1) (destructive 0) (stop 0) (migrate 0) (ignore 2) (canary 0)
                                                                                 Desired Changes for "trebek-es-facts-67-kibana": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)"
Feb 26 12:31:38 nomad-server-i-003399652f3f9dc56.node.seatgeek.prod nomad[6139]: nomad: plan for node rejected: node_id=3bbebe49-9e68-2dbe-3325-7025d0cf4809 reason="node is not eligible for draining"
```

**Comment by jippi** [comment]
cc @jrasell @schmichael - this has caused us a number of outages recently, both on `0.8.7` _and_ `0.10.3` - the only path forward outside of making nodes eligible again is to `nomad stop -purge` and then create the job again

**Comment by jippi** [comment]
Seem to be happening with job-register too

![image](https://user-images.githubusercontent.com/22841/75900939-069a9a00-5e3e-11ea-9600-dfd2a2453066.png)

**Comment by tgross** [comment]
Hi @NicholasABriganti and @jippi! Just for clarity, when you say "3. Reschedule the allocations.", how's that being performed? Normally I would expect that a node being marked ineligible was intended to be drained (at least, that's what the ineligible flag was designed for), so there may be a workflow we didn't anticipate here.
