### ISSUE TITLE
Allow arbitrary parameters to internal docker run command

### ISSUE THREAD

**Issue by maticmeznar** [hashicorp/nomad#725]
High now, Docker support in Nomad is basic. It doesn't support setting log drivers, log options, nor security features like capabilities, all of which are used in serious production environments. It would be great if Nomad supported specifying arbitrary parameters to docker run command (or whatever it uses internally), so all those features could be used by users. This would allow Nomad users to add Docker parameters like --read-only --cap-drop=ALL --log-driver=fluentd ...

**Comment by dadgar** [comment]
Hey could you please open issues for features that you feel are missing. We will not allow arbitrary parameters to docker but we would like uses to be able to add import docker configurations. You can see we support quite a few already:

https://github.com/hashicorp/nomad/blob/master/client/driver/docker.go#L40
