### ISSUE TITLE
[0.10.4][Windows2019Core] Tasks Queued but Nomad Client have enough resources

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/nomad#7262]
Nomad version: `0.10.4`
Nomad Server Cluster #: `3`
Nomad Client Nodes: `4`
Nomad Client Node Os: `Windows Server 2019 Core`
Nomad Server Os: `Ubuntu 16.04`

**Windows 2019 Core Details**
```
os
os.name	Microsoft Windows Server 2019 Standard
os.signals	SIGALRM,SIGHUP,SIGINT,SIGKILL,SIGQUIT,SIGSEGV,SIGABRT,SIGFPE,SIGILL,SIGPIPE,SIGTERM,SIGTRAP,SIGBUS
os.version	10.0.17763 Build 17763
cpu
cpu.arch	amd64
cpu.numcores	4
cpu.frequency	2100
cpu.modelname	Intel Xeon Processor (Skylake, IBRS)
cpu.totalcompute	8400
kernel
kernel.name	windows
consul
consul.server	false
consul.version	1.6.4
consul.revision	a13102a08
consul.datacenter	dc1
driver
driver.docker
driver.docker.os_type	windows
driver.docker.version	19.03.5
driver.docker.runtimes	
driver.docker.volumes
driver.docker.volumes.enabled	true
driver.raw_exec	1
nomad
nomad.version	0.10.4
nomad.revision	f750636ca68e17dcd2445c1ab9c5a34f9ac69345
nomad.advertise
unique
unique.hostname	docker-core-win-01
unique.consul
unique.consul.name	docker-core-win-01
unique.storage
unique.storage.volume	C:
unique.storage.bytesfree	53360222208
unique.storage.bytestotal	85321576448
unique.network
unique.platform
unique.platform.aws
unique.platform.aws.instance-id	i-005ff80f
memory
memory.totalbytes	17651175424
```
**Deployment Scenario**

The current status of workload is the following:

* `2` Nomad Client Nodes are reporting `15` Tasks Allocated
* `2` Nomad Client Nodes are reporting `10` Tasks Allocated

At this point, a job with `10` tasks is executed(basically an update of an existing job - increase tasks by `9` )

![iHRX6f4A](https://user-images.githubusercontent.com/3172378/75824676-f0bfa300-5d71-11ea-8db9-e4e826699aac.png)

It is complaining that there are not enough CPU/Network resources but clearly did not pick the nodes that have less resource utilization(**win01/win02** nodes)

![Oq_dUuOg](https://user-images.githubusercontent.com/3172378/75824844-3ed4a680-5d72-11ea-9471-b7c3a2561cf4.png)

The following is the image before executing the job. But clearly it should have chosen the least utilized nodes.

![yYKEsKfQ](https://user-images.githubusercontent.com/3172378/75825028-9410b800-5d72-11ea-839c-0c90871a6faf.png)

**Questions**

* Is there a way to utilize the resources in a uniform way across the existing nomad cluster and if so, which configuration is needed to accomplish that?
* Is there a way to see the proposed plan details as which node was chosen?

**Comment by tgross** [comment]
Hi @lmayorga1980! 

> It is complaining that there are not enough CPU/Network resources but clearly did not pick the nodes that have less resource utilization(win01/win02 nodes)

Nomad uses a bin-packing algorithm for scheduling by default, so it will not automatically schedule to nodes that have less resource utilization (unless it doesn't have enough on the packed nodes). So I suspect that Nomad may not think there's enough resources on any of the nodes. Would you be willing to share your job spec? We also updated the library we use for fingerprinting nodes in the upcoming 0.11.0-rc, which might help get more accurate metrics from Windows.

> Is there a way to utilize the resources in a uniform way across the existing nomad cluster and if so, which configuration is needed to accomplish that?

You may want to look at the [`spread`](https://nomadproject.io/docs/job-specification/spread/#even-spread-across-data-center) block in the job spec.

> Is there a way to see the proposed plan details as which node was chosen?

The `nomad plan -verbose :jobspec` might give you some more details. But the plan shows the diffs that Nomad will attempt, and not the placement metrics which get used once the plan is finalized for running. (You can get those for placed allocs at `nomad alloc status -verbose :alloc_id`) It does seem like we _should_ be able to expose more of that information though.
