### ISSUE TITLE
Capacity and Scalability limits?

### ISSUE THREAD

**Issue by nixoz** [hashicorp/nomad#727]
Dear guys,
first of all - thanks a lot for your great work and tools.

Recently we are considering the nomad as a resource manager (or container orchestration tool, whatever). But, we little bit worried about the scalability limits, if here so...

Do you have thoughts what will happen if we will put nomad to 100-150DCs with 5 to 10K nodes overall?
We know Federation is implemented with Surf which is based on SWIM....but you know we never can be sure without tests =)

Actually we worried about the bandwidth/cpu problems...
Any suggestions?

Thank you so much!

**Comment by dadgar** [comment]
Hey,

A closer of that size is definitely within the design goals of the project and thus any issue you run into at that size will receive support from us. We highly suggest minimizing latency between your Nomad servers. Latency between the negatively impacts Raft performance and can lead to degraded cluster performance. If you would like to discuss this more feel free to email any member of the team.

- Alex

**Comment by nixoz** [comment]
Thank you for the comment!
I'm need to talk more on that topic defo.

Thank you!

Best,
S.
