### ISSUE TITLE
Job > Task Group > Service assumes iptables exists on the machine

### ISSUE THREAD

**Issue by daneharrigan** [hashicorp/nomad#7270]
I was trying out Nomad on Mac OS (Mojave 10.14.6). It works as intended, scheduling images with Docker. My jobs failed to run when I added the [Task Group service stanza](https://nomadproject.io/docs/job-specification/service/#service-stanza) because Nomad assumed `iptables` existed in my `$PATH`.

It looks like OSX has something similar to `iptables` called `ipfw`, but that got me thinking in local dev should I be modifying my iptables or should changes like that be scoped to a VM?

### Versions

```
% nomad -v
Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)
% consul -v
Consul v1.7.0
% docker -v
Docker version 19.03.5, build 633a0ea
```

**Comment by notnoop** [comment]
I'm afraid that the Task Group service support requires Consul Connect which is only supported by running as root in a Linux - https://nomadproject.io/guides/integrations/consul-connect/ .  I'm afraid we don't support darwin yet or inside a container.

My understanding is that when setup with consul connect, nomad would create new iptables chains with a user chain for user customizations; but nomad is assumed to own these chains, much like how docker reserves some iptables chains for its operations.

**Comment by daneharrigan** [comment]
@notnoop thanks for responding. I'm fine with closing the issue.
