### ISSUE TITLE
Allow shutdown_delay to execute regardless of service registration

### ISSUE THREAD

**Issue by drewbailey** [hashicorp/nomad#7271]
##  Issue
Currently a task's shutdown_delay as well as the task group's shutdown delay will only run if there are registered services for the task or group.

This implementation detail isn't called out anywhere in the documentation and the way that its configured, by setting shutdown_delay outside of the service block makes it unclear that shutdown_delay is dependent on a service.

Original report: #7251

**Comment by djenriquez** [comment]
@drewbailey -- Just to clarify, if we use network namespaces, and subsequently group level service definitions, then _only_ the group level `shutdown_delay` will go into effect. The task's `shutdown_delay` will be ignored since there is no service defined at that level.

Is this a true statement?

**Comment by drewbailey** [comment]
Hey @djenriquez, that is correct. Currently a task needs to have a service defined in order for a task `shutdown_delay` to be evaluated or even created [here](https://github.com/hashicorp/nomad/blob/master/client/allocrunner/taskrunner/task_runner_hooks.go#L105). The service hooks preKilling method is what invokes [shutdown_delay](https://github.com/hashicorp/nomad/blob/master/client/allocrunner/taskrunner/service_hook.go#L134)

**Comment by djenriquez** [comment]
Understood, thank you for the very prompt response!
