### ISSUE TITLE
[Question] Is it possible to update a job without restarting not modified tasks?

### ISSUE THREAD

**Issue by Muntaner** [hashicorp/nomad#7276]
As the title states, I would like to know if it is possible to update a job, adding a new task to an existing group, without restarting the tasks which were already defined before the update process took place.

In my scenario, the already defined tasks **are not involved in the update process**, so I wouldn't need to restart them when editing the job. After performing the _plan_ operation, I execute the _update_ one (linked with the _index_update_ parameter), the job restarts correctly but the old tasks (without any modification) get restarted aswell which can led to undesired downtime.

**Comment by jrasell** [comment]
Hi @Muntaner and thanks for the question. A task group is a set of tasks that must be run together and also means a task group is the unit of scheduling with the end state being that a task group will run all on the same client machine. Nomad is unable to perform the kind of update you are proposing as adding a new task requires the re-scheduling of the entire group.

If the new task is logically separate from the existing tasks, it could be an option to place the new task in a separate group, which would not cause a destructive update of the original group. If they are logically collated and you wish to avoid downtime while adding the additional task, it could be worth considering submitting the new jobspec under a new jobID, and then performing the appropriate routing changes before stopping the old job.

**Comment by Muntaner** [comment]
Thanks a lot for the answer and the clarification, @jrasell !
