### ISSUE TITLE
s3 artifact Instance Role

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/nomad#7277]
### Nomad version
0.10.x

### Operating system and Environment details
windows

### Issue
have nomad use AWS IAM Instance Role instead of hardcoding aws_access_key_id
```json
artifact {
  options {
    aws_access_key_id     = "<id>"
    aws_access_key_secret = "<secret>"
    aws_access_token      = "<token>"
  }
}
```

**Comment by jrasell** [comment]
Hi @FernandoMiguel and thanks for the issue. Nomad uses the [go-getter](https://github.com/hashicorp/go-getter) library when dealing with artifacts, and the S3 protocol does indeed support [using iam instance profiles](https://github.com/hashicorp/go-getter#using-iam-instance-profiles-with-s3). Are you receiving a particular error when attempting to use this functionality that could help pin-point any issues you're having?

**Comment by FernandoMiguel** [comment]
hi @jrasell 
we have a windows nomad client that is trying to pull an artifact from a cross account s3 bucket.

a craft curl with instance role creds works from the instance, but nomad fails to pull the artifact when no access key is added to the options block.

**Comment by FernandoMiguel** [comment]
I wonder if it is the default region causing issues, instead of using the instance region

> region (optional - defaults to us-east-1) - Region identifier to use.

**Comment by jrasell** [comment]
@FernandoMiguel I have been taking a look into the go-getter source for the S3 protocol, I think you're right in pointing out the region being the param which is causing a potential issue. Are you able to provide a redacted version of the artifact URL you are using within the config?

**Comment by FernandoMiguel** [comment]
```json
artifact {
	source = "s3::https://REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip"
	options {
	  region = "eu-west-1"
	}
  }
```

nomad errors out with
`  failed to download artifact "s3::https://REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip": URL is not a valid S3 URL	`

**Comment by FernandoMiguel** [comment]
@jrasell ^

**Comment by FernandoMiguel** [comment]
also, related
how do i set `GetterMode`? i don't see it in the docs, only in https://github.com/hashicorp/nomad/issues/2678

**Comment by FernandoMiguel** [comment]
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::1234567890:root",
                    "arn:aws:iam::0987654321:root"
                ]
            },
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl"
            ],
            "Resource": "arn:aws:s3:::REDACTED/*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::1234567890:root",
                    "arn:aws:iam::0987654321:root"
                ]
            },
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::REDACTED"
        }
    ]
}
```
this is the bucket policy and equivalent instance iam role policy

**Comment by 02strich** [comment]
Can you try to use `REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip` as source?

This aligns with the test case at https://github.com/hashicorp/nomad/blob/master/client/allocrunner/taskrunner/getter/getter_test.go#L338

**Comment by FernandoMiguel** [comment]
well... that works @02strich

**Comment by jrasell** [comment]
good morning @FernandoMiguel, as @02strich pointed out it seems as the S3 URL you first used was not passing validation checks as detailed by the error message `failed to download artifact "s3::https://REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip": URL is not a valid S3 URL`.

The getter mode is configurable by using the `mode` artifact stanza parameter - https://nomadproject.io/docs/job-specification/artifact/#inlinecode-destination-2

**Comment by FernandoMiguel** [comment]
```
          “Artifacts”: [
            {
              “GetterSource”: “https://REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip”,
              “GetterOptions”: {
                “region”: “eu-west-1"
              },
              “GetterMode”: “file”,
              “RelativeDest”: “local/REDACTED.zip”
            }
failed to download artifact “https://REDACTED.s3-eu-west-1.amazonaws.com/REDACTED.zip”: expected a single file: C:\Windows\TEMP\getter549838548\archive
```

@jrasell i can open a diff issue to track mode issue.

as of the moment, our initial permission issue seems fixed.

**Comment by 02strich** [comment]
interesting, I assume the zip file contains multiple files? If that is the case can you append to your url `?archive=false` to disable automatic archive extraction?
