### ISSUE TITLE
[FEATURE]: Add custom DNS options for the exec driver

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/nomad#7283]
Right now the `exec` driver does not provide a way to specify custom DNS servers for the task.

Just like the `docker` driver has the `--dns-*` options, it would be great to be able to provide custom DNS settings for `exec` task drivers.

I thought on setting `"/opt/custom_resolv.conf" = "/etc/resolv.conf"` in the `chroot_env` settings for the nomad clients but I'm not 100% sure it works.

**Comment by notnoop** [comment]
Thanks @danlsgiga Sorry for taking forever to get back.

This is related to https://github.com/hashicorp/nomad/issues/7283 and we may address these together.

**Comment by danlsgiga** [comment]
> This is related to #7283 and we may address these together.

Maybe there's a typo here... 7283 is this issue! :)

**Comment by notnoop** [comment]
🤦‍♂ Oops.  Sorry. I meant https://github.com/hashicorp/nomad/issues/7393

**Comment by danlsgiga** [comment]
Closing this in favour of #7393
