### ISSUE TITLE
[question] Can binaries with mock driver enabled be publicly released?

### ISSUE THREAD

**Issue by OneCricketeer** [hashicorp/nomad#7293]
### Environment details

Unit testing (Java) 

### Issue
  
In order to use the Nomad mock driver within Junit tests (and I assume other languages), it appears that the nomad binary needs compiled from source with some flags enabled. 

### Question

Rather than make us do that, could you please build and release those artifacts as well? 

Discussion: https://github.com/hashicorp/nomad-java-sdk/issues/39

**Comment by notnoop** [comment]
Thanks for reaching out.  It'd be nice indeed to have a non-official debug build available - though as Chris pointed out, unlikely for us to work on it soon.

Our CI builds do generate dev binaries for every master push to be used for testing, e.g. https://circleci.com/gh/hashicorp/nomad/48556#artifacts/containers/0 - We use these for our e2e testing.  Would using these help in your scenario?

**Comment by cricket007** [comment]
Thanks for the response. Hope you're staying healthy out there 

> unlikely for us to work on it soon

No rush, really. We're currently just mocking out the API calls with Java libraries, and I wanted to know what options are out there for actual integration tests. 

Another avenue that's available would be to use the Testcontainers project to spin up all of Vault, Consul, Nomad via a Docker Compose, which I think would  work great for my current use case, but Consul is mostly solved with the embedded one I linked in the other issue (though, would like to also know if there's a more official way to test that out) and we're just focused on programmatic Nomad deployments in the JVM for the time being
