### ISSUE TITLE
CSI: plugin deregistration on plugin job GC

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#7306]
Plugins are implicitly registered by the creation of a job. But when the last job for a plugin is stopped, the plugin is still registered and there's no way to remove it. We should implement a `nomad plugin deregister` CLI command (and the API to support it).

- return an error if the plugin has any allocations that are still running it
- require `submit-privileged-task` ACL (see #6992)

**Comment by tgross** [comment]
Alternately, we could GC a plugin that has no plugin allocs whenever we GC the plugin jobs. @langmartin what do you think of that approach?

**Comment by langmartin** [comment]
I think GC is the right approach, and it's anticipated in `deleteNodeCSIPlugins` (from just the plugin side).

**Comment by tgross** [comment]
Ok, updated the issue title to match.
