### ISSUE TITLE
[question] Queue Was Not Utilized by the Parameterize Jobs with Reserved CPU Exhausted

### ISSUE THREAD

**Issue by vwxyzjn** [hashicorp/nomad#7307]
### Nomad version
Output from `nomad version`
`Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)`

### Operating system and Environment details
![image](https://user-images.githubusercontent.com/5555347/76327941-088eae00-62c1-11ea-80f9-e96b3a38785b.png)

### Issue
I was trying to run machine learning tasks by using the parameterized jobs by nomad. By default, pytorch used up all of the cpu resources even for a single run. The job is using the docker driver, and using the `cpu_hard_limit = true` helps a lot. Instead of having 1200% of the reserved CPU used, only 400% was used, as show in the following screenshots. I have a couple questions.
![image](https://user-images.githubusercontent.com/5555347/76328821-27417480-62c2-11ea-8d92-1b8b9a3a6a93.png)
![image](https://user-images.githubusercontent.com/5555347/76328836-2e688280-62c2-11ea-8a04-c654a6a19aa5.png)

1. How could I configure such that only about 100% of the reserved CPU is used? If i had set the `cpu_cfs_period` to a lower number, does that mean the `cpu_hard_limit` well be enforced more regularly?
2. For some reasons, even the clans are already overworked (reserved CPU exhausted), if I dispatch another job, the job will be executed instead of being queued. Why is this the case?
3. I set up a `cpu_total_compute` for the clients, would it be in a case that the jobs won't be queued until all of the resources (instead of `cpu_total_compute`) in the clients are exhausted?
```
client {
  enabled = true
  servers = ["drexel.costa.sh:4647"]
  cpu_total_compute = 20000
  memory_total_mb = 58000
}
```
Any help would be greatly appreciated.

### Reproduction steps
```python
import nomad
n = nomad.Nomad(
    host="xxxxxx"
)
for i in range(500):
    n.job.dispatch_job("cleanrl_job", meta={
        "command": 'python ppo2_continuous_action.py --gym-id HumanoidFlagrunBulletEnv-v0 --total-timesteps 2000000  --norm-adv --anneal-lr --norm-returns --norm-obs --kl --gae --clip-vloss --no-cuda --capture-video --seed 4'
    })

### Expected Results
The reserved CPU  should not exceed 105%, and if the current reserved cpu usage is more than 105%, and then the future dispatched jobs should be queued instead of being run right away.

```
### Job file (if appropriate)
```
job "cleanrl_job" {
  type        = "batch"
  datacenters = ["dc1"]
  meta {
    command = ""
  }
  parameterized {
    meta_optional = ["command", "wandb"]
  }
  group "cleanrl_group" {
    task "cleanrl_task" {
      driver = "docker"
      config {
        image = "vwxyzjn/cleanrl_nomad:1.4-cuda10.1-cudnn7-runtime"
        command = "${NOMAD_META_COMMAND}"
        cpu_hard_limit = true
      }
      env {
        WANDB = "${NOMAD_META_WANDB}"
      }
      resources {
        cpu = 1000
        memory = 1000
      }
    }
    restart {
      attempts = 0
      mode = "fail"
    }
  }
  reschedule {
    attempts = 0
  }
}
```
### Nomad Client logs (if appropriate)
I don't know what logs will be useful for this. Except the resources over usage, everything else looks normal.

### Nomad Server logs (if appropriate)
I don't know what logs will be useful for this. Except the resources over usage, everything else looks normal.

**Comment by vwxyzjn** [comment]
I actually tried to to run more experiments, and finally some jobs are queued per the screen shot below. I think my second and the third questions having answered. 

My first question, however, still remains. Namely, how could I configure such that only about *100%* of the reserved CPU is used? If i had set the `cpu_cfs_period` to a lower number, does that mean the `cpu_hard_limit` well be enforced more regularly?


![image](https://user-images.githubusercontent.com/5555347/76332427-bea8c680-62c6-11ea-9f4f-87221cb84369.png)

**Comment by tgross** [comment]
> Namely, how could I configure such that only about 100% of the reserved CPU is used?

Just for my clarification, using the configuration you've described above, you're seeing 20 concurrent jobs being executed? So the question is only about bursting over the configured capacity? I'm wondering if there's a fingerprinting issue with the host. You may want to double-check that the fingerprint matches the `cpu_total_compute` you've configured. Unset the value in the config file, run the agent, and then run a `nomad node status -verbose` and look for `cpu.totalcompute`.

> If i had set the `cpu_cfs_period` to a lower number, does that mean the `cpu_hard_limit` well be enforced more regularly?

That's my understanding.
