### ISSUE TITLE
Environment variables and docker driver

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#732]
afaik there is no way to read environment variables inside docker container, am I wrong?

At task level we have an env option, would be nice if we could use it from within the docker container
https://www.nomadproject.io/docs/jobspec/index.html

P.S. probably it could be a good idea to allow passing any custom options to the docker driver (i.e. -e for setting environment variables)

**Comment by dadgar** [comment]
The environment variables you specify are available in the docker container. You can see this by running `docker inspect <container-id>` or by starting a shell in it.
