### ISSUE TITLE
Documentation: add example for client.options (setting docker.privileged.enabled to true)

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#733]
I'm trying to enable Nomad running privileged docker containers, and so far I cannot make it work
Could you please provide an example how to properly set this and similar docker.* options?

**Comment by let4be** [comment]
I solved it with

client {
  options {
    docker.privileged.enabled = "true"
  }
}

This was not trivial... and would be really nice to have in documention

What was not obvious:
- docker.privileged.enabled can be used as key
- true should be specified as string instead of boolean(i.e. quotes)

**Comment by shantanugadgil** [comment]
Apologies to comment on such an old issue, but finding the page was really not that easy for me either.
https://www.nomadproject.io/docs/drivers/docker.html#client-configuration

* I nearly had opened a new issue myself about the privileged docker 😬 

Would it be possible to somehow view/download/render entire docs as one page HTML, so a search can be done more efficiently? A separate link for the "single page HTML" would be fine too!

Thanks and Regards,
Shantanu
