### ISSUE TITLE
CLI feature: ability to view queued allocations and corresponding jobs

### ISSUE THREAD

**Issue by lovwal** [hashicorp/nomad#7336]
### Nomad version
v0.9.3

### Issue
We ran into an interesting issue where a job was scheduled for more memory than was available in any node in the cluster. This caused subsequent scheduled allocations to not be placed:
```
$ nomad eval status -verbose 963dbee3
ID                 = 963dbee3-dbf1-5109-7311-d56e0c940546
Status             = complete
Status Description = complete
Type               = service
TriggeredBy        = job-register
Job ID             = job
Priority           = 50
Placement Failures = true
Previous Eval      = <none>
Next Eval          = <none>
Blocked Eval       = f9079e22-80b3-595c-e43a-af145ddfdac2

Failed Placements
Task Group "job" (failed to place 1 allocation):
  * Resources exhausted on x nodes
  * Dimension "memory" exhausted on x nodes

Evaluation "f9079e22-80b3-595c-e43a-af145ddfdac2" waiting for additional capacity to place remainder
$ nomad eval status -verbose f9079e22
ID                 = f9079e22-80b3-595c-e43a-af145ddfdac2
Status             = blocked
Status Description = created to place remaining allocations
Type               = service
TriggeredBy        = queued-allocs
Priority           = 50
Placement Failures = N/A - In Progress
Previous Eval      = 963dbee3-dbf1-5109-7311-d56e0c940546
Next Eval          = <none>
Blocked Eval       = <none>
```
The evaluation is in this case blocked because there is resource exhaustion for an allocation ahead in the queue. Herein lies the problem, there is no obvious way from what I have found so far to find out what is in the queue and what was actually blocking. Hence, it would be helpful to be able to obtain the queue from a CLI command which shows what allocations and job is in the queue.

### Reproduction steps
Schedule a job which requires more resources than available in the cluster. Then schedule a second job which the cluster has enough resources to support. The allocation from the second job will most likely not be placed.

**Comment by notnoop** [comment]
Thanks @lovwal for reaching out.  I'm afraid, I'm unable to reproduce this issue (at least with 0.10.4 binary).  Mind if you provide more specific steps as well as logs of the server, as well as description of your cluster?
