### ISSUE TITLE
Documentation: $nomad.ip (and probably others)

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#734]
Docker driver mentions $nomad.ip interpretable variable(args)
https://www.nomadproject.io/docs/drivers/docker.html

but there are no more references to it anywhere in the docs
https://www.nomadproject.io/docs/jobspec/#interpreted_vars

**Comment by pires** [comment]
I can confirm `$nomad.ip` doesn't work or at least I haven't figured out how it works from reading the available documentation. Thank you @let4be for opening the issue, I totally forgot about it.

**Comment by dadgar** [comment]
Yep will document before Nomad 0.3
