### ISSUE TITLE
NOMAD_PORT environmental variable is missing

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/nomad#737]
Hello,

I'm on the latest commit (9e7e214) and I noticed NOMAD_PORT environmental variable is missing when I start a process. Here is an example job file I used:

```
job "test" {
  datacenters = ["dc1"]
  constraint {
    attribute = "$attr.kernel.name"
    value = "linux"
  }

  group "test" {
    count = 1

    task "test" {
      driver = "raw_exec"
      env {
        TEST_VAR = "TEST"
      }
      config {
        command= "printenv"
      }

      resources {
        network {
            port "http" {}
        }
      }
    }
  }
}
```

Here is the output:
```
TEST_VAR=TEST
NOMAD_ADDR_http=127.0.0.1:43376
NOMAD_ADDR_http=127.0.0.1:43376
NOMAD_ALLOC_DIR=/tmp/NomadClient350214069/415a7f4b-c7de-c8c4-a35c-ebadbe3e78cc/alloc
NOMAD_TASK_DIR=/tmp/NomadClient350214069/415a7f4b-c7de-c8c4-a35c-ebadbe3e78cc/test/local
TEST_VAR=TEST
```

NOMAD_ADDR has the port information but I need the port itself to give the program as an argument. I see on the changelog it says
`client: Environment variable containing address for each allocated port [GH-704]`

Does it mean that port information will be removed from Nomad?

**Comment by dadgar** [comment]
Yes the port variable has been removed. You can still parse the port from the addr

**Comment by kaskavalci** [comment]
Hi Alex,

Thanks for your response. Our applicants require ports to be given as an argument. How can we parse the port inside the job file?

IMHO port information is valuable. It is a huge backward incompatibility. Does it really cause that much of trouble to remove it altogether?

**Comment by dadgar** [comment]
@kaskavalci: We removed it and $NOMAD_IP because they don't capture the reality that individual ports may be on different interfaces/IPs.

**Comment by diptanu** [comment]
@kaskavalci You should be able to get the ```ip:port``` information allocated to your job via the NOMAD_ADDR_<port_name> env var. Hope this would work for you?

**Comment by kaskavalci** [comment]
@dadgar and @diptanu thanks for your replies. 

That makes sense then. However, I need to somehow split the ip and port variables and feed to the program within the job file. How do you suggest to do that? 

IMHO, you can have two variables, NOMAD_ADDR_IP_var NOMAD_ADDR_PORT_var. That way there will be no need to split and users who need the full IP form can easily concatenate.

**Comment by dadgar** [comment]
Yeah that is a good idea

**Comment by dadgar** [comment]
We will be keeping it how it is for now. If you can not modify your application to accept the IP:Port pair, you can wrap it in a script that parses it out.
