### ISSUE TITLE
Upgrade default Envoy image

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#7374]
Investigate what Envoy version to upgrade to in Nomad v0.12:

https://www.consul.io/docs/connect/proxies/envoy.html#supported-versions

We will have to note these changes in the Upgrade specific guide as existing Connect-enabled jobs will need restarting to take advantage of the Envoy version bump. Forgetting that step could cause users to prematurely upgrade their Consul clusters to a version of Consul incompatible with running Envoys.

**Comment by shoenig** [comment]
Needs the TBD API described in https://github.com/hashicorp/nomad/issues/8585

**Comment by shoenig** [comment]
Addressed by https://github.com/hashicorp/nomad/pull/8945
