### ISSUE TITLE
API/command to initiate graceful change in leadership

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#7376]
Hello,

Maybe I am misunderstanding the internals, so please tell me this makes no sense if that is the case. Or if there is an existing thing I should instead that would accomplish the same. thank you :)

Let's say you have 5 servers running in production, 1 of them is the active leader. You need to roll out an update to those servers. There are consistent scheduling events and changes going onto the log during the maintenance, so the update must be as graceful as possible. You iterate on the list of servers, taking one down at a time, bringing up a replacement, and waiting for that replacement to join the cluster and for quorum numbers to balance with those changes.

One method would pull each server indiscriminately, such that at any point, you could be taking down the active leader. While one of the other servers will pick up and take over, depending on load, there are likely to be significant delays and failures associated with the transition (for new scheduling events, not running allocations). This method is also more than likely to result in multiple transitions, and does not do anything to limit that to one transition. When this transition happens, the operator has no idea what scheduling event they may be interfering with.

Another method has the operator identify the active leader ahead of time, rolling all other nodes first. If the active leader changes, it may end up on a new node, or an old one. Either way, we'd leave an active leader on an old node until it is the last to roll.

In either case, it would be ideal if the operator could tell nomad: "I'd like to take the active leader offline for maintenance, can you please transition the active leader to a different server at some point in the next few operations, kthxbye".

The active leader would then not be "ripped out" while doing its work, more than is necessary (eg some other hardware failure or whatever). The cluster would have an opportunity to put it's work on hold for a moment, and transition gracefully without losing active requests.

**Comment by ketzacoatl** [comment]
@notnoop / @tgross / @jrasell / @lgfa29 / @shoenig 

Later this month, we'll have sat with this issue for a year.

Just yesterday I had to decommission an instance on AWS (AWS would kill the instance for me if I didn't), and it just happened to be the active leader running in production (YAY!). I could have really used this functionality (or a reasonable work-around) to carry out that maintenance.

Overall, the transition to a new leader happened and the cluster stayed healthy, but allocations were missed and the transition was not fully graceful. Part of the problem was that, as an operator, I didn't have a clear/obvious path for making the transition. If there were an obvious-to-use command for this situation, the operator could complete the transition with confidence and without taking down the cluster (worst case, but still a risk).

What's the point of running a 5-node production cluster when I cannot tell it to transition to another node? "Just rip it out" is not a good response. It works "ok" at small scale, but when hundreds or thousands of jobs are running, batch jobs are firing every minute (and the team is considering using parametized batch jobs which in production could fire at any second), a graceful transition would save the operator a _lot_ of stress and reduce the risk of making an error. In this case, the system was in the perfect condition for a graceful, operator-initiated leadership transfer, but I had to rip out the active leader anyway.

The experience reminded me how important this issue is for those of us operating at scale.

If I were writing a set of requirements, it'd look like:
* Operators must have a way to instruct the Nomad cluster to transition out the active leader.
* When an operator gives the instruction, the cluster must end up electing a new leader, and should block the old active leader (it must not become the active leader again).
* During the transition, no cluster/server functions should fail, active work should be completed, new tasks should be queued and then resumed.
* Clients deploying jobs, updating tasks, querying health, etc, should not fail.
* There should be protections against running the transition too often, eg if you ran it repeatedly, the cluster should not break. The command should refuse to run when it's not safe.
* The "instruction" should be available to operators via the API as well as the cli.

If we need to discuss / noodle thru the details, let's do it! I'm happy to discuss and share experience/feedback or bounce ideas around.

**Comment by tgross** [comment]
Hi @ketzacoatl. For starters, I want to apologize for letting this issue linger without comment for so long. We've been working on some changes to our issue triage process to make sure things don't fall through the cracks, but I realize that's too little too late for this issue.

Before I get into the challenges around the idea of a command to change leadership, I want to address the specific scenario you have here. If you're simply replacing the servers one-by-one as part of an upgrade (as is often the case for deployments on AWS), then you can:

* Add the new server.
* `nomad server members` to verify the server has joined.
* `sudo systemctl stop nomad` on the server leaving the cluster (or whatever the equivalent might be for your distro).
* `nomad server members` (to another server) to verify the server is recognized as having left.
* [`nomad server force-leave`](https://www.nomadproject.io/docs/commands/server/force-leave) if it has not.
* Terminate the old server.
* Repeat until cluster is fully replaced.

There shouldn't be any need to force a leader election in this case, even on a busy cluster. If you're following that process and maintaining quorum the whole time, there shouldn't be any acknowledged writes lost. It's worth checking your [`autopilot`](https://www.nomadproject.io/docs/configuration/autopilot) configuration as well to make sure the values there are in line with how quickly you want to roll the cluster.

Now, as far as the idea of a command or API that initiates a graceful change in [raft](https://raft.github.io/) leadership, forcing the server to step down would be pretty easy, but the important part which is "and then it stays that way" is a bit more challenging. Fortunately that's already been baked into HashiCorp's raft library: what we'd want to do there is "transfer leadership", which our raft library gives us via the [`Raft.LeadershipTransfer`](https://pkg.go.dev/github.com/hashicorp/raft#Raft.LeadershipTransfer) method. The docs for this method are:

> LeadershipTransfer will transfer leadership to a server in the cluster. This can only be called from the leader, or it will fail. The leader will stop accepting client requests, make sure the target server is up to date and starts the transfer with a TimeoutNow message. This message has the same effect as if the election timeout on the on the target server fires. Since it is unlikely that another server is starting an election, it is very likely that the target server is able to win the election. Note that raft protocol version 3 is not sufficient to use LeadershipTransfer. A recent version of that library has to be used that includes this feature. Using transfer leadership is safe however in a cluster where not every node has the latest version. If a follower cannot be promoted, it will fail gracefully.

But right now we don't have raft protocol v3 as the default for Nomad, as it makes safe upgrades from v2 versions of Nomad challenging (see https://github.com/hashicorp/nomad/issues/7208 for details). So getting that work done is likely to be a prerequisite for this feature.

**Comment by ketzacoatl** [comment]
> For starters, I want to apologize for letting this issue linger without comment for so long. We've been working on some changes to our issue triage process to make sure things don't fall through the cracks, but I realize that's too little too late for this issue.

I appreciate the acknowledgement on that. At the same time, I understand the balancing act you play, and this is a complicated topic, easier to let sit than scope and tackle.

> Before I get into the challenges around the idea of a command to change leadership, I want to address the specific scenario you have here. If you're simply replacing the servers one-by-one as part of an upgrade (as is often the case for deployments on AWS)

This recent scenario I described in my last comment was slightly different: I had a single server to tear down and replace, and that server happened to be the active leader. 

Regardless of that, yes, the process you describe is generally what I do for rolling out changes to the leaders/servers. I do roll them in a way to avoid the active leader when/where possible (eg roll the others first), but at some point the active leader has to be hit. I say "has to be hit" for the reason you describe: it'll keep winning the leader election until something external intervenes. That would be like: a) load on the active leader, enough for it to slow down and lose an upcoming election, b) some network interference, c) active leader is stopped.

> There shouldn't be any need to force a leader election in this case, even on a busy cluster. If you're following that process and maintaining quorum the whole time, there shouldn't be any acknowledged writes lost. It's worth checking your autopilot configuration as well to make sure the values there are in line with how quickly you want to roll the cluster.

On a busy cluster, even with writes being confirmed, I believe there are issues when you forcefully stop the active nomad leader while it is busy doing work. For example, it may have some "work" to do (evaluation, or allocation placement, or interacting with vault, etc), that it is actively in the middle of when you pull the plug. That work is at best interrupted, and lost at worst. Maybe I am misunderstanding how the internals work?

> Now, as far as the idea of a command or API that initiates a graceful change in raft leadership, forcing the server to step down would be pretty easy, but the important part which is "and then it stays that way" is a bit more challenging. Fortunately that's already been baked into HashiCorp's raft library: what we'd want to do there is "transfer leadership", which our raft library gives us via the Raft.LeadershipTransfer method. The docs for this method are:

> But right now we don't have raft protocol v3 as the default for Nomad, as it makes safe upgrades from v2 versions of Nomad challenging (see #7208 for details). So getting that work done is likely to be a prerequisite for this feature.

That makes sense, thanks for sharing. It would be great to see this in a 1.1 or 1.2 release!

**Comment by ketzacoatl** [comment]
> `nomad server members` (to another server) to verify the server is recognized as having left.

This reminds me, we have to "pause" during this rolling update. It would be amazing to have an API we could query which would tell us when it's safe to continue with the rolling update. ATM we just "wait a few minutes" and it would be much safer to do that verification programmatically.

**Comment by tgross** [comment]
Cross-referencing https://github.com/hashicorp/nomad/issues/8470

**Comment by ketzacoatl** [comment]
> This reminds me, we have to "pause" during this rolling update. It would be amazing to have an API we could query which would tell us when it's safe to continue with the rolling update. ATM we just "wait a few minutes" and it would be much safer to do that verification programmatically.

@tgross, I don't see an existing issue for this topic, should I write this up for discussion as a feature request in a new issue?

**Comment by tgross** [comment]
Can't hurt to split that out. Thanks! Some of that is definitely a documentation issue; the upgrade docs are missing a "here's what you should be looking for" for sure.

**Comment by Oloremo** [comment]
Any updates on this? 

We're trying to monitor for Nomad Lost Nodes and during leader restart we get false positives due to leader restart.
Leader graceful shutdown should help here as well.
