### ISSUE TITLE
artifact auto track source context change

### ISSUE THREAD

**Issue by hubugui** [hashicorp/nomad#7377]
### Nomad version
v0.10.3

### Operating system and Environment details
Windows

### Question

artifact stanza is nice feature, I can download it before start task. 

now I have a a usual feature that restart task when artifact file content change, I can not find way in Nomad document.

Please everyone help， Thanks!

**Comment by chenjpu** [comment]
You can stop job and start it again. Alternatively, you can stop alloc, the scheduler will reschedule it

**Comment by hubugui** [comment]
Thanks!

This is a way, need config file generator call Nomad server to restart task, I feel that Nomad job configure support auto track change is better way, avoid application layer service access Nomad API.

Is there any other way?

**Comment by chenjpu** [comment]
And you might need CI/CD to implement this feature

**Comment by tgross** [comment]
Hi @hubugui! Typically the way you'll want to implement this sort of thing is to submit a new version of the job with the checksum for the new artifact updated in the artifact stanza.

**Comment by hubugui** [comment]
@tgross  @chenjpu 

Thanks for your suggest! Now I will test Terraform how to submit new version of the job.
