### ISSUE TITLE
Binary not statically compiled

### ISSUE THREAD

**Issue by ryansch** [hashicorp/nomad#740]
I'm not sure if this is a target for nomad but I'm unable to run the 0.2.3 binary on a busybox container as it requires libpthread.so.

**Comment by c4milo** [comment]
It requires glibc @ryansch

**Comment by c4milo** [comment]
... and it is mainly a Go constrain.

**Comment by dadgar** [comment]
Yep this is known. Thanks!

**Comment by ryansch** [comment]
Thanks for the quick feedback!
