### ISSUE TITLE
      * Dimension "bandwidth exceeded" exhausted on 1 nodes

### ISSUE THREAD

**Issue by aep** [hashicorp/nomad#7405]
### Nomad version

Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)

### Operating system and Environment details

archlinux.

### Issue

there appears to be no way to set network_speed or at least ignore it if the interface is not the public interface (which i need to set, otherwise nomad announced the wrong address internally to consul)

unclear if network_speed is ignored because nomad node-status --verbose does not show any network resources, so there is no way to know why it is exhausted either, since no jobs require any network resources

### Reproduction steps

client {
   network_interface = "wireguard"
   network_speed = 1000
}

launch any job without network resource constrains

###logs

    2020-03-20T23:21:38.091+0100 [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/cluster/speed
    2020-03-20T23:21:38.091+0100 [DEBUG] client.fingerprint_mgr.network: setting link speed to user configured speed: mbits=1000
    2020-03-20T23:21:38.091+0100 [DEBUG] client.fingerprint_mgr.network: detected interface IP: interface=cluster IP=172.22.1.1

so apparently not ignored. still cant launch anything, even tho no jobs require network resources

**Comment by aep** [comment]
i dont understand why, but rebooting the server (rather than the client where this is failing) made the problem go away

**Comment by notnoop** [comment]
Hi @aep Thanks for reporting the bug and sorry for the slowness.  This seems very similar to https://github.com/hashicorp/nomad/issues/7232 that I'm investigating this week.

**Comment by aep** [comment]
FWIW, i can't reproduce it. I think this might happen when you start without network_interface, then change it later. possibly the old value is cached somewhere.
