### ISSUE TITLE
Support binding to unix sockets for interfaces.

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#741]
I would love to see a similar feature like the one in consul where we can bind an interface to a unix socket:

> Both rpc and http support binding to Unix domain sockets. A socket can be specified in the form unix:///path/to/socket. A new domain socket will be created at the given path. If the specified file path already exists, Consul will attempt to clear the file and create the domain socket in its place. 

We can then mount the socket into a docker container as a file, etc.

**Comment by dadgar** [comment]
Can you clarify why you want this

**Comment by F21** [comment]
I am building a UI to control nomad and it will be deployed as a docker container to run on top of nomad. I can then mount the socket file into the docker container to control nomad rather than having to deal with ip addresses to access the api.

**Comment by dadgar** [comment]
Can you talk to Nomad currently via your container. This is not really a high priority task for us right now
