### ISSUE TITLE
Nomad consul connect: consul_si_token: Unexpected response code: 403 (Permission denied)

### ISSUE THREAD

**Issue by perbly** [hashicorp/nomad#7447]
Hi, not sure if this is a consul or nomad issue. But i can´t really find any documentation how to proceed. 

Trying to run a nomad job with consul connect (not native).
ACL is enabled in consul but nomad 0.10.4 should support this.

Regards.
P

### Nomad version
`Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)`
### Consul Version
`Consul v1.7.1`

### Consul Client logs
```
Mar 24 09:17:39 nomad-client consul[12233]:     2020-03-24T09:17:39.746Z [ERROR] agent.proxycfg: watch error: id=service-http-checks:_nomad-task-8880ae9e-bca1-9de8-18ea-10f8b4f7a4aa-group-whoami-whoami-80 error="invalid type for service checks response: cache.FetchResult, want: []structs.CheckType"
```

### Nomad Client logs
```
Mar 24 09:17:39 nomad-client  nomad[21612]:     2020-03-24T09:17:39.571Z [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=8880ae9e-bca1-9de8-18ea-10f8b4f7a4aa task=connect-proxy-whoami error="prestart hook "consul_si_token" failed: Unexpected response code: 403 (Permission denied)
```

nomadServer has the following consul acl policy
```
service "nomad-client" {
  policy = "write"
}
key_prefix "services/nomad-client/" {
  policy = "write"
}
key_prefix "services/" {
  policy = "read"
}
node_prefix "nomad-client" {
  policy = "write"
}
agent_prefix "nomad-client" {
  policy = "write"
}
service_prefix "" {
  policy = "write"  
}
node_prefix "" {
  policy = "read"
}
```

Attaching job specification:

[job.txt](https://github.com/hashicorp/nomad/files/4374392/job.txt)

**Comment by angrycub** [comment]
I believe that you will need to add `acl = "write"` to your Nomad server policy.  This will allow the Nomad servers to build the service integration tokens.  There is a guide in the pipeline that will demonstrate this, but it's still in the editing stages.

**Comment by perbly** [comment]
Thanks @angrycub  that worked.
