### ISSUE TITLE
UI: deduplicate job-loading in exec job route

### ISSUE THREAD

**Issue by backspace** [hashicorp/nomad#7458]
The [code](https://github.com/hashicorp/nomad/blob/03d9a3b7f410aabb23fe94eef20bf6e771620eed/ui/app/routes/exec.js) is copied from the job route.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/commit/5ad55b8dbffcc833db6c79f57f8c50bb5d645bbc
