### ISSUE TITLE
[learn] ACL guide needs to be updated with new Scaling capabilities

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#7498]
The learn guide at https://learn.hashicorp.com/nomad/acls/create_policy is missing the new dispositions and capabilities supporting the scaling APIs in 0.11-beta1.

**Comment by tgross** [comment]
@cgbaker just because the work will likely be done by two different people and I want to make sure we're tracking CSI project tasks, I've split out the CSI portion of this to https://github.com/hashicorp/nomad/issues/7507

**Comment by tgross** [comment]
@cgbaker looking at this it looks like it's a minimal addition and it's obvious from the code what it needs to be... I'll just put it in the same PR.
