### ISSUE TITLE
[question] - nomad-autoscaler is still private?

### ISSUE THREAD

**Issue by fredrikhgrelland** [hashicorp/nomad#7500]
Eager to try our the autoscaling in 0.11-beta1 I was looking into the docs for information on how to get access to it. https://github.com/hashicorp/nomad/blame/master/website/pages/docs/job-specification/scaling.mdx#L13 has a link, but github 404s it, so I presume it is private. If that was intended, when will it be available?
Thanks

**Comment by cgbaker** [comment]
release is tomorrow! look for a blog post and switching the repo to public.

**Comment by fredrikhgrelland** [comment]
Thank you! I’ll wait for it
