### ISSUE TITLE
[question] How to run a nomad job when consul ACL's are enabled?

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#7519]
I am attempting to setup Nomad 0.10.4 at my company. I want to leverage consul-connect since we have policies that certain types of workloads must segmented from each other. 

I have successfully run jobs with consul connect with ACL's disabled. 
Nomad 0.10.4 introduced the ability to run workloads in nomad when ACL's are enabled. However there is no documentation that I can find showing how to do that. 

The forums teased that documentation would be coming soon. 

>Consul Connect ACL Support: Nomad can now manage Consul Connect enabled services with Consul ACLs enabled. A full guide will be published prior to the final release.

https://discuss.hashicorp.com/t/nomad-0-10-4-rc1-released/5917

**Comment by notnoop** [comment]
Thanks for reaching out.  I'm afraid the guide isn't out yet.  You can see a draft of it in https://github.com/hashicorp/learn/blob/nomad/cv/nomad-consul-acl/pages/nomad/consul-integration/nomad-connect-acl.mdx .

Closing this issue, as publishing the guide is tracked in https://github.com/hashicorp/nomad/issues/7057 .

**Comment by angrycub** [comment]
@spuder  We're close.  I realize that you will not be able to see it in learn because that's not open.   I have the content temporarily in a gist [here](https://gist.github.com/angrycub/58bf6ca5528281d728f0c292d1d8bc12, which I will replace with a link to the learn guide as soon as it gets published.
