### ISSUE TITLE
HTTP interface to get all servers within a region

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#752]
`v1/agent/servers` reflects the servers being set in the client configuration. It does not reflect the actual known servers within a region at this very instant.

`v1/agent/members` shows all the known servers within a region at this very instant, but does not work on client nodes.

I would love to have some way to be able to get a list of current known servers within a region (with the region switch-able using `?region=someregion` from any node in the cluster. The main use case for this is to be able to implement a dashboard that will show all the nodes (servers + clients) in the cluster.

**Comment by dadgar** [comment]
`/v1/status/peers?region=<region>`: https://www.nomadproject.io/docs/http/status.html
