### ISSUE TITLE
[question] Dispatching parametrized job with multiple unknown numbers of arguments

### ISSUE THREAD

**Issue by fwkz** [hashicorp/nomad#7535]
It looks to me that there is no way of dispatching a parametrized job with multiple unknown numbers of arguments. Given the following job definition: 
```
job "remover" {
  # ...

  type = "batch"

  parameterized {
    payload       = "forbidden"
    meta_required = ["FILES_TO_REMOVE"]
  }

  group "remover" {
    # ...

    task "remover" {
      driver = "exec"

      config {
        command = "rm"
        # `rm` is accepting multiple arguments
        args = ["${NOMAD_META_FILES_TO_REMOVE}"]
      }
    }
  }
}
```
Dispatching such job with `FILES_TO_REMOVE="foo bar baz"`, `rm` is going to be called as `rm "foo bar baz"` which obviously is wrong.

Is there any _good_ way of dispatching such a job? If not is it something that we'd like to pursue and place a fix or at least come to an agreement of potential solution?

**Comment by notnoop** [comment]
You can pass the input as a encoded string and parse it in the command.

For example, you can pass the files as a json array, and use `jq` and `xargs` to run them, something like:

```hcl
command = "/bin/sh"
args = ["-c", "echo "$${NOMAD_META_FILES_TO_REMOVE}" | jq -r '.[]' | xargs -I rm"]
```

Also, if your files don't have spaces, you can also rely on shell expansion:

```
command = "/bin/sh"
args = ["-c", "rm $${NOMAD_META_FILES_TO_REMOVE}"]
```

In the case above, without quoting the variable, shell will do variable expansion before passing them to `rm`.

I haven't tested these snippets, so you may need to do some tweaks first.
