### ISSUE TITLE
[question] A reliable way to get job status of a finished job after garbage collection

### ISSUE THREAD

**Issue by denisovlev** [hashicorp/nomad#7538]
Is there a reliable way to get a job status (success/failure) of a finished job?

For example in 3 days after the job was finished, job status command does not return this information because the job was garbage collected.

1. Can nomad keep the history of the status of the finished jobs?
2. Is there a way to set garbage collector to keep jobs for example for 30 days?

**Comment by tgross** [comment]
Hi @denisovlev! You can change the job GC interval with the server's [`job_gc_interval`](https://nomadproject.io/docs/configuration/server/#job_gc_interval) field.

However, Nomad's keeps the entire state store in memory (backed to disk, of course!), and this includes all task events. Increasing the GC interval to such a large number would increase the memory used, but also increase the amount of time it takes for new servers to join the cluster. I'm not sure I'd recommend increasing the GC interval by that much, but if you do we'd love to hear back about what kind of impact that had on the cluster.

All that being said, when I've had this same problem as an operator running large batch workloads, I typically made sure the output of batch workloads was being recorded elsewhere. Either logs or metrics, or in the case I had, a database. That way you can record a lot more than pass/fail and do richer analysis of the workloads.

**Comment by notnoop** [comment]
Want to call out you can use some nomad streaming tools that help with replicating job status to external systems.  You can use [`nomad-firehose`](https://github.com/seatgeek/nomad-firehose) and [`nomad-watcher`](https://github.com/blalor/nomad-watcher) (with some extra scripting) to propagate job status to an external database for further query or analysis.
