### ISSUE TITLE
Resource usage apis

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#758]
We are in the midst of building a dashboard and a monitoring system for nomad.

One of the things that would be really useful is to be able to see the resources available, allocated and being used on each node.
- While it's possible to interrogate each node and get the amount of cpu, memory and disk available, it would be nice to have an endpoint we can easily query to get the total available resources for each region and datacenter.
- In order to determine what resources are reserved for tasks on each machine, we currently need to query all allocations and merge the data together. It would be nice if we can query a node and the response will tell us which tasks are allocated and running on that node and how much resources each task have reserved.
- There currently isn't any api endpoint to tell us the actual resource utilization of a task. A task might reserve 500MB of memory, but might only use 200MB at the moment. It would be really cool to be able to see this on a node level as well as a job and allocation level.

**Comment by diptanu** [comment]
@F21 We have this on our roadmap to provide APIs to inform the actual resource usage of tasks.

**Comment by kaskavalci** [comment]
Hi @diptanu do you have a milestone for this enhancement? Which resources (cpu, network, disk util, memory, etc) do you plan to include in the task? Lastly will you provide host utilization as well?

Thanks.

**Comment by hgontijo** [comment]
I noticed that the node api `/v1/node/<id>` has the following data structure:
```json
    "Reserved": {
        "CPU": 0,
        "MemoryMB": 0,
        "DiskMB": 0,
        "IOPS": 0,
        "Networks": null
    },
```
... and it's never populated. @diptanu is this supposed to be populated with the Node resource reservation?

**Comment by dadgar** [comment]
This has actually been fixed a long time ago! 

Host: https://www.nomadproject.io/docs/http/client-stats.html
Allocation: https://www.nomadproject.io/docs/http/client-allocation-stats.html

**Comment by dadgar** [comment]
@hgontijo That is populated if you set reserved resources on the clienthttps://www.nomadproject.io/docs/agent/configuration/client.html#reserved

**Comment by hgontijo** [comment]
@dadgar thanks for clarifying that a Node [Reserved](https://www.nomadproject.io/docs/agent/configuration/client.html#reserved) (exposed on /v1/node/node_id) means the amount of resource set from receiving tasks.

Now, let's say I'd like to know the amount of resources reserved or required (not real usage) by all tasks across the Nomad cluster. Is that a single API to give to provide this data? Currently I'm getting this data by querying all allocations across the cluster.

**Comment by dadgar** [comment]
Currently you will have to aggregate the results. So you are doing it right!

Thanks,
Alex Dadgar
