### ISSUE TITLE
Suggestion: Minor fix dist/systemd README.md 

### ISSUE THREAD

**Issue by y4roslav** [hashicorp/nomad#7598]
File: https://github.com/hashicorp/nomad/blob/master/dist/README.md 

> Place one of these under /etc/nomad depending on the node's role. You should use server.hcl to configure a node as a server (which is responsible for scheduling) or client.hcl to configure a node as a client (which is responsible for running workloads)

But according to SystemD file https://github.com/hashicorp/nomad/blob/df7839fe02f532f4f3dbd79c9d81e1514940cdcd/dist/systemd/nomad.service#L15 it should be `/etc/nomad.d/`folder 

I think `nomad.d` folder is a more appropriate naming here. 

Case: 
I'm using two servers to build Nomad sandbox where one of those machines behaves like the server and client at the same time. As a result, having two separate configs under `/etc/nomad.d/server.hcl` and `/etc/nomad.d/client.hcl` totally has a sense for me. As a result, two services with a different path can be created. 
[Example](https://learn.hashicorp.com/nomad/getting-started/cluster)

 PS That "issue" is too minor to open PR

**Comment by tgross** [comment]
Opened https://github.com/hashicorp/nomad/pull/7648
