### ISSUE TITLE
Make static builds of nomad.

### ISSUE THREAD

**Issue by yongtang** [hashicorp/nomad#761]
We tried to embed nomad binary into an Alpine Linux container. However, the nomad binary downloaded from https://releases.hashicorp.com seems to have glib dependencies:
```
$ ldd nomad
	linux-vdso.so.1 =>  (0x00007ffeac690000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c88f7c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c88d78000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c889b3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0c8919a000)
```

That means it will not run in baseline Alpine Linux.

I am wondering if released binary could be changed to static build, i.e., with flag of
```
CGO_ENABLED=0 
```
That will save some space when deploy nomad inside a container.

As a comparison, the Consul binary I downloaded from https://releases.hashicorp.com seems to be a static build:
```
$ ldd consul
	not a dynamic executable
```

**Comment by dadgar** [comment]
This is known. We require cgo in order to properly look up users. So unfortunately we need this.
