### ISSUE TITLE
Dispatch documentation and API documentation differs about the maximum size of payload

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#7614]
This page (https://nomadproject.io/docs/commands/job/dispatch/) says:

> The payload has a size limit of 16KiB.

Whereas the API documentation for Dispatch (https://nomadproject.io/api-docs/jobs/#payload) says:

> Payload (string: "") - Specifies a base64 encoded string containing the payload. This is limited to 15 KB.

There are two different formats KiB/KB, and two different numbers 16 KiB and 15 KB.

**Comment by tgross** [comment]
Thanks for this report @kaspergrubbe!

**Comment by kaspergrubbe** [comment]
Yes this is still a problem.

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/9396 and will get shipped to the website on the next update.

**Comment by kaspergrubbe** [comment]
Brilliant, thank you!
