### ISSUE TITLE
System scheduler and constraints

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#762]
What constraints are guaranteed to work with system type jobs?
I would like to launch job on particular set of hosts(meta constraint || node class constraint) but I want to abstract from such details as number of nodes, new starting nodes(I.e. I want to launch it on each and every node of particular class within one datacenter/within several datacenters)

Currently I'm thinking about using hacks like - schedule on every available node with all resources set to 1 and check condition manually in shell script on this node, if it does not match - execute sleep 9999*
Is there a better way to do the job?

**Comment by dadgar** [comment]
Out of curiosity why does adding those constraints and setting the DC on the job not work?

**Comment by let4be** [comment]
Never mind, this seems to be documented and work properly
Sorry
