### ISSUE TITLE
[CSI] "raw_exec" task driver not supported 

### ISSUE THREAD

**Issue by chenjpu** [hashicorp/nomad#7623]
### Nomad version
v0.11.0-beta2

### Operating system and Environment details
centos7
### Issue
```
# nomad plugin status
Container Storage Interface
No CSI plugins
```
### Job file (if appropriate)
```
job "plugin-hostpath" {
  datacenters = ["dc1"]
	namespace   = "default"
  type = "system"

  group "nodes" {
    task "plugin" {
      driver = "raw_exec"
      config {
        command = "hostpathplugin"
        args = [
          "--endpoint=unix://csi/csi.sock",
          "--nodeid=CSINode",
          "--v=5",
        ]
      }
      csi_plugin {
        id        = "csi-hostpath"
	type      = "monolith"
	mount_dir = "/csi"
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @chenjpu and thanks for this report!

CSI plugins that run mount operations (ex. `node` and monolith` plugins) need to run with privileges to perform `mount` on the host. Currently `raw_exec` and `exec` drivers don't have the equivalent of `privileged=true` like we have with the Docker driver. So this is a documentation miss, but it's also an area we want to improve in the future.

In the meantime, try using the Docker task driver for CSI plugins.

**Comment by chenjpu** [comment]
thanks for reply, i am currently started by docker driver.

**Comment by tgross** [comment]
I've opened https://github.com/hashicorp/nomad/pull/7642 with some clarifications to the docs.
