### ISSUE TITLE
No documentation on how to use host volume policies via JSON

### ISSUE THREAD

**Issue by josemaia** [hashicorp/nomad#7634]
Currently, my team is writing all Nomad ACL policies in JSON. As we recently started using host volumes, we noticed our Jenkins instance became unable to deploy stateful jobs, as it is getting a Permission Denied 403 error (note - it would be nice to have a more detailed error message here, instead of me having to go into the source code to figure it out!)

On the [documentation page](https://learn.hashicorp.com/nomad/acls/policies/), there is an example of creating ACL policies in JSON that includes most stuff, but it does not have host volumes. How would I create a policy such as the below in JSON format, considering "*" is not a valid name for a key in JSON? Is this supported, or should I move to using HCL instead?
```
host_volume "*" {
  policy = "write"
}
```

**Comment by tgross** [comment]
Hi @josemaia! The docs are definitely lacking a bit here, but I gave this a try myself and it looks like a direct conversion of that policy to JSON works.

Here's the JSON policy file I wrote:

```json
{
  "host_volume": {
    "*": {
      "policy": "write"
    }
  }
}
```

 I'm pretty sure `"*"` is just fine as a key in JSON in the general case, as `jq . < ops.policy.json` parses it just fine. Or maybe our JSON parser and the one `jq` uses is less strict? In any case, the results:

```sh
▶ nomad acl policy apply -description "Ops Policy" ops ./bin/ops.policy.json
Successfully wrote "other" ACL policy!

▶ nomad acl policy info ops
Name        = ops
Description = Ops Policy
Rules       = {
  "host_volume": {
    "*": {
      "policy": "write"
    }
  }
}
CreateIndex = 27
ModifyIndex = 27
```

**Comment by josemaia** [comment]
I just tried it in my browser and it worked, so I must've been doing something wrong. Nevertheless I converted my stuff to hcl-inside-json, because we're using HCL in Vault's ACLs so it's more consistent that way. Thank you!

**Comment by tgross** [comment]
Glad to hear!
