### ISSUE TITLE
Routing to parameterized/dispatched jobs should support plain IDs without encoding the /

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#7664]
When browsing our dispatched jobs in the Nomad the address goes to (Notice the `%2F` which is hex for `/`):

> https://supersecretnomadcluster.com/ui/jobs/billetto-staging-console%2Fdispatch-1586389906-f1660fdf

Browsing to it works fine:

<img width="759" alt="screenie_1586390063_710669" src="https://user-images.githubusercontent.com/334273/78844273-36206180-79fd-11ea-9f64-970608b663ad.png">

However, when I replace the `%2F` with a `/` then the routing no longer works:

<img width="1004" alt="screenie_1586390349_046902" src="https://user-images.githubusercontent.com/334273/78844329-58b27a80-79fd-11ea-9928-89fbce84ef0b.png">

This is not a problem, unless you are writing scripts that depends on the jobnames, for an example the `$NOMAD_ADDR/v1/evaluation/$EVALUATION_ID/allocations` endpoint will give you an output of:

```json
    "ID": "billetto-staging-console/dispatch-1586389230-2349af0a",
    "JobModifyIndex": 314214,
    "Meta": {
      "CONTAINER_OWNER": "Kasper Grubbe",
      "SLEEP_TTL": "4h"
    },
    "ModifyIndex": 314214,
    "Name": "billetto-staging-console/dispatch-1586389230-2349af0a",
    "Namespace": "default",
    "ParameterizedJob": {
      "MetaOptional": null,
      "MetaRequired": [
        "SLEEP_TTL",
        "CONTAINER_OWNER"
      ],
      "Payload": "forbidden"
    },
    "ParentID": "billetto-staging-console",
```

But if I have to link consumers to that JobID I would have to replace the `/` with `%2F` in order for the link to work.

**Comment by DingoEatingFuzz** [comment]
Hi @kaspergrubbe. 

You are expected to url-encode job names when scripting. `/` is a reserved character used for routing within the UI.

**Comment by kaspergrubbe** [comment]
Thanks for answering me. I understand the technical reason for it, but I still feel like it is a bug that should be improved.

> You are expected to url-encode job names when scripting

Only some  places, the same isn't the case for the API, as this is accepted:

```
curl -X DELETE $NOMAD_ADDR/v1/job/billetto-staging-console/dispatch-1586390702-62d6cd30
```

**Comment by DingoEatingFuzz** [comment]
I agree it would nice. Unfortunately this isn't a simple inconsistency since the API and the UI use completely different routers and the UI one is much more opinionated.

**Comment by mikenomitch** [comment]
Going to close this out as it would take a non-trivial amount of engineering to get our frontend router to work with this, but the payoff is quite low.

Sorry, you'll have to stick with the encoding for the foreseeable future!
