### ISSUE TITLE
Consul will support envoy 1.14.4 with Consul 1.8

### ISSUE THREAD

**Issue by i0rek** [hashicorp/nomad#7665]
See hashicorp/consul#7624.

There is also another releated issue: https://github.com/hashicorp/nomad/issues/7111

**Comment by jrasell** [comment]
thanks for thinking of us @i0rek :D

**Comment by i0rek** [comment]
New versions are out, Consul will support 1.14.2: https://github.com/hashicorp/consul/pull/8057.

**Comment by i0rek** [comment]
New versions are out, consul will support 1.14.3: hashicorp/consul#8216.
