### ISSUE TITLE
Feature request: allow to specify resources for task group rather than specific task

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#767]
Tasks within task group are guaranteed to be scheduled on the same node
It could  be useful toaccount && limit task resource consumption(mem, cpu, probably iops) for the whole co-scheduled task group
What do you think?

**Comment by dadgar** [comment]
Hey, the resource isolation primitives happens at a per task level (cgroups, chroot, docker resources, etc). So this is not something we can support

**Comment by ranjib** [comment]
@let4be fwiw it might be possible to put the whole nomad client process under a dedicated cgroup and spawn containers inside that, this wont allow per task group resource control, but it will allow a global cgroup limit on all tasks running via nomad (i.e. you can protect your control plane). Something like nomad running as systemd service, with cgroup enforced by systemd resource control directives. and the nomad client is spawning lxc container (or if rkt supports unprivileged containers one day) as nomad user.. each having their own cgroup limit.  This is in also helpful with things that cant be enforced via chroup, but can be enforced via user quota etc.

**Comment by let4be** [comment]
My usage pattern currently relies on spawning a lot of t2.nano and t2.micro
ec2 instances for isolation purposes but this comes with overhead -  having
linux running on each node
(saas service, each user is being delegated with ec2 instance)

With proper per-group resource limits I could schedule task groups within
bigger instances, saving some resources(i.e having less instances of bigger
size - less os/nomad running), it could allow more efficient resource usage
while providing good enough resource isolation

Afaik such thing should be technically possible to implement using cgroup
if make all tasks within the group start from the same parent. Am I wrong
on this one?

**Comment by ranjib** [comment]
yes. but different task driver implementations enforces cgroups differently. Like docker driver will offload cgroup enforcement to docker, which internally put them under its own cgroup. For nomad to implement this universally, all task driver have to expose a group like abstraction (or at least provide something that can be used to implement groups.

**Comment by ranjib** [comment]
https://github.com/docker/docker/issues/12849

**Comment by ranjib** [comment]
correcting myself : I think one might be able to implement something like this using the parent_cgroup stuff in docker https://github.com/docker/docker/pull/11428
