### ISSUE TITLE
Nomad showing ACL secret when you navigate to ACL Token section on GUI

### ISSUE THREAD

**Issue by manish-panwar** [hashicorp/nomad#7686]
### Nomad version

0.10.5

### Operating system and Environment details

PhotonOS

### Issue
Nomad showing ACL secret when you navigate to ACL Token section on GUI

### Reproduction steps

1. Enable ACL in Nomad setup
2. Navigate to `ACL Token` section on top right no the GUI
3. Set ACL token and verify that now you are able to access resources on Nomad GUI
4. Navigate again to ACL token page by clicking on top right and you will be able to see the token that was enter previously.

**Comment by tgross** [comment]
Doing a little issue cleanup and this has been fixed for a while now. Currently this looks like the following:

![acl](https://github.com/hashicorp/nomad/assets/1409219/68079717-291d-4247-94e7-74777dae4458)
