### ISSUE TITLE
[Doc] Nomad + Consul Connect with ACLs is now documented

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#7694]
The documentation on this page says consul-connect enabled jobs are not supported when running with ACL's enabled. The documentation was pushed last week so this limitation can be removed. 

> Consul ACLs are not yet supported (#6701).

https://nomadproject.io/docs/integrations/consul-connect/

![Screenshot 2020-04-11 19 44 52](https://user-images.githubusercontent.com/242382/79058570-ee801c80-7c2c-11ea-8c99-341164a1e804.png)

It would probably be good to add a paragraph to this page linking to the Learn page where consul connect enabled jobs are listed. 

https://learn.hashicorp.com/nomad/consul-integration/nomad-connect-acl

https://github.com/hashicorp/nomad/issues/7057

**Comment by shoenig** [comment]
Thanks @spuder , great suggestions!
