### ISSUE TITLE
Namespace ACL policy to allow force launching existing periodic jobs but deny modification

### ISSUE THREAD

**Issue by jdebbink** [hashicorp/nomad#7703]
### Nomad version
0.10.4

### Issue
There is no namespace ACL policy that allows a periodic job to be launched without also giving permission to change and delete jobs.

This policy allows parameterized jobs to be launched but not periodic:
```
namespace "default" {
  policy = "read"
  capabilities = ["dispatch-job", "read-logs"]
}
```
This policy allows periodic jobs to be launched but it also gives permission to modify/stop/delete jobs, which is far more permission than we want to grant to just launch a job that already exists.
```
namespace "default" {
  policy = "read"
  capabilities = ["submit-job", "read-logs"]
}
```
### Use Case
In production we want to allow teams to launch periodic/batch jobs that already exist but not be able to modify them in any way.

**Comment by notnoop** [comment]
Thanks for the suggestion @jdebbink .  That does seem like a reasonable use case indeed!
