### ISSUE TITLE
Documentation: Broken link to port requirements

### ISSUE THREAD

**Issue by sbrl** [hashicorp/nomad#7707]
### Nomad version
n/a

### Operating system and Environment details
Rapsberry Pi 4 with UFW (Uncomplicated Firewall) and Docker, but n/a
### Issue
When visiting the website, I am unable to find a list of ports that Nomad uses. Consul, on the other hand, presents such a list [here]().

Additionally, I found that [this documentation page](https://learn.hashicorp.com/nomad/operating-nomad/federation) has a link to a supposed port list, but it appears to be broken for me - and instead takes me to the main documentation page.

### Reproduction steps
1. Visit [this page in the official documentation](https://learn.hashicorp.com/nomad/operating-nomad/federation)
2. Click the "Nomad Port Requirements" link (it goes to [here](https://www.nomadproject.io/guides/install/production/requirements.html#ports-used) for me)
3. Notice that it doesn't take you to the port requirements - instead it takes you to the main documentation homepage.

### Job file (if appropriate)
n/a
### Nomad Client logs (if appropriate)
n/a

### Nomad Server logs (if appropriate)
n/a

**Comment by spuder** [comment]
The page link for nomad ports used to be here: https://www.nomadproject.io/guides/install/production/requirements.html

For reference the nomad servers and agents need these ports:
tcp => 4646 (nomad http) 4647 (nomad rpc)

Nomad servers need these ports for federation
tcp/udp => 4648 (nomad serf wan)

**Comment by tgross** [comment]
I've just double-checked this and the link correctly points to https://www.nomadproject.io/docs/install/production/requirements.html#ports-used now.
