### ISSUE TITLE
ignored_gpu_ids are ignored by nomad client.

### ISSUE THREAD

**Issue by maaft** [hashicorp/nomad#7711]
On a server where I have 8 GPUs available, I want to limit nomad to use only 4 of them.
Therefore, I added the UUIDs of 4 GPUs to `ignored_gpu_ids` as per  https://nomadproject.io/docs/devices/nvidia/.

```
plugin "nvidia-gpu" {
  ignored_gpu_ids = ["GPU-fef8089b", "GPU-ac81e44d"]
  fingerprint_period = "1m"
}
```

Unfortunately, nomad still allocates GPUs which I have specified to be ignored.

Is this expected and do I misunderstand the purpose of the above config?

If so, how can I deny nomad access to certain GPUs?

**Comment by tgross** [comment]
> Unfortunately, nomad still allocates GPUs which I have specified to be ignored.

In #7649 you and I discussed the issue of privileged containers and their access to `/dev` (I've closed that as I suppose you've gotten your answer there.) What's the specific behavior you're expecting vs what you're seeing here?

**Comment by maaft** [comment]
Hi @tgross ! This issue is completely unrelated to #7649 .

I expect that my nomad client don't schedule jobs on GPUs which I specified to be ignored.

**Comment by maaft** [comment]
On a side-note: I don't feel really comfortable asking these things on your github issue board as I think that it should be for confirmed issues only.

Is there anything planned like a forum for questions or similar?

**Comment by maaft** [comment]
Do you have an idea regarding my issue? @tgross ?

**Comment by tgross** [comment]
> I expect that my nomad client doesn't schedule jobs on GPUs which I have specified to be ignored.

So suppose you have:
- client A, which has GPU-X
- client B, which has GPU-Y (same device model as X)

And the clients have the configuration:

```
plugin "nvidia-gpu" {
  ignored_gpu_ids = ["GPU-X"]
  fingerprint_period = "1m"
}
```

And your job has this resource configuration:

```
resources {
  device "nvidia/gpu" {
    count = 1
  }
}
```

Sometimes the job is getting scheduled on Client A? If so, that's definitely a bug we need to fix. But I feel like I'm maybe getting the situation wrong? Can you explain it with a similar example if so?

> Is there anything planned like a forum for questions or similar?

https://discuss.hashicorp.com/c/nomad is the official forum, where you can chat with other users and HashiCorp engineers who pop in.

**Comment by maaft** [comment]
My client has this configuration:
```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "/nomad/client"

# Enable the client
client {
    enabled = true
    servers = ["X.X.X.X:4647"]
}


# Modify our port to avoid a collision with server1
ports {
    http = 5656
}

plugin "nvidia-gpu" {
  ignored_gpu_ids = ["GPU-ab0ab381", "GPU-927e390f"]
  fingerprint_period = "1m"
}
```
Here is my job description:
```
job "${CI_PROJECT_NAME}-live" {
  datacenters = ["dc1"]
  group "group" {
    count = "${COUNT}"

    update {
      max_parallel     = 1
      auto_revert = true
    }

    restart {
      attempts = 3
      delay    = "30s"
    }
    task "task" {
      driver = "docker"
      resources {
        cpu    = 12000
        memory = 32000
        device "nvidia/gpu" {
          count = 1
        }
      }
      config {
        image   = "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
        auth {
          password = "XXXXX"
          username = "XXXX"
        }
        force_pull = true
        network_mode = "host"
        pid_mode = "host"
        ipc_mode = "host"
        volumes = [
          "XXXXX",
          "XXXX"
        ]
      } # config
    } # task run
  } # group
} # job
```
in my job description.

But still all GPUs are used by nomad on that machine (8 GPUs available - 8 docker containers started).

So I guess, it's indeed a bug. How can I help to solve it?

**Comment by maaft** [comment]
Any news on this? :)

**Comment by bmenn** [comment]
@maaft I believe I encountered the same problem as you and found the solution. In your client configuration, change
```
plugin "nvidia-gpu" {
  ignored_gpu_ids = ["GPU-ab0ab381", "GPU-927e390f"]
  fingerprint_period = "1m"
}
```
to
```
plugin "nvidia-gpu" {
  config {
    ignored_gpu_ids = ["GPU-ab0ab381", "GPU-927e390f"]
    fingerprint_period = "1m"
  }
}
```
This follows the plugin configuration on https://www.nomadproject.io/docs/configuration/plugin/. This is different from the example provided on the NVIDIA device plugin page (which matches what you have).

@tgross Is this (the NVIDIA device plugin page) just old documentation that needs a small update? If so, I could make a quick PR for that update.

**Comment by tgross** [comment]
Apologies for not circling back to this.

> @tgross Is this (the NVIDIA device plugin page) just old documentation that needs a small update? If so, I could make a quick PR for that update.

It looks like that could be it... that would match the other plugins that have internal config values.

**Comment by bmenn** [comment]
I think we might be ok to close this now that #8233 has been merged.

**Comment by marcown** [comment]
@bmenn 

It seems that this issue is not fixed, I started a nomad client with 

```
plugin "nvidia-gpu" {
  config {
    enabled = true
    ignored_gpu_ids = ["GPU-b958ce21","GPU-c77cfb4b"]
    fingerprint_period = "1m"
  }
}


```

but it still uses all GPUs (I have machines with 8 GPUs)


and nomad node status <client-with-8-gpus> outputs


Device Resource Utilization
nvidia/gpu/GeForce RTX 2080 Ti[GPU-61124b24-7a6a-81e4-5374-924c6d9ec9c6]  8 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-85bba190-fa32-aa9a-7b66-60d266b27e4d]  5 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-96d571b5-1ae2-8848-0aa7-d4c312e140e1]  8 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-99fc5c78-45ab-6993-6e7a-0ae9aad0b776]  8 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-9a07011c-4033-7faf-d25f-c0a4ea9d4a02]  5 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-ad561429-9178-776b-1478-601c7d424cb1]  8 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-b958ce21-a8c6-c9ec-28ea-d5df58bc4c39]  8 / 11019 MiB
nvidia/gpu/GeForce RTX 2080 Ti[GPU-c77cfb4b-49ad-ed86-dada-7180ac7a1b1c]  8 / 11019 MiB


--> lists all GPUs
