### ISSUE TITLE
nomad ui <node-id> goes to the wrong URL

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#7739]
`nomad ui fd6c` navigates to `http://127.0.0.1:4646/ui/nodes/fd6c6a11-55a7-bf02-d0b0-de56000f53a9`

The correct URL to navigate to is `/clients/` not `/nodes/`:

http://127.0.0.1:4646/ui/clients/fd6c6a11-55a7-bf02-d0b0-de56000f53a9

**Comment by sashaaKr** [comment]
@schmichael I would like to take this one, if it is ok.

**Comment by schmichael** [comment]
Thanks @sashaaKr ! Sounds great.

**Comment by sashaaKr** [comment]
@schmichael I’m wonder is there any particular reason why no tests for `ui` command? I managed to fix issue, it’s basically one line change, and I’m thinking of adding tests.

**Comment by schmichael** [comment]
I'm afraid we have not yet setup the test machinery to cross the Go->Javascript boundary within a test.  Fully testing the integration of `nomad ui ...` with the UI itself requires executing both the Go CLI as well as the UI's Javascript. Testing the integration with the Go CLI and the UI requires opening a browser and making assertions about the page requested. In the future we hope to add these types of tests to our [e2e suite](https://github.com/hashicorp/nomad/tree/master/e2e#readme).

**Comment by sashaaKr** [comment]
@schmichael OMG, I was sure that I already submitted PR,
so, it is better later than never :)
fix is one liner.

**Comment by notnoop** [comment]
@sashaaKr Thank you again for the fix - closed by https://github.com/hashicorp/nomad/pull/8514 .
