### ISSUE TITLE
WIndows raw_exec driver, kill_signal configuration

### ISSUE THREAD

**Issue by atomovski** [hashicorp/nomad#7747]
Hi,

First some context, I'm evaluating Nomad to be used as a deployment tool for a range of Windows based services. As a first baby step, I've started with this task stanza

```
task "Example.Console.App" {
      driver = "raw_exec"

      config {
        command = "C:\\Example.Console.App\\Example.AppHost.exe"
      }

      kill_timeout = "30s"
    }
```

The example app is using http://topshelf-project.com/ as a wrapper, long story short we currently run our apps as Windows services. Everything works great except when I try to stop the tasks (when scaling down) at this point I see the following message in the logs: `2020-04-19 06:16:41.813Z ERROR [23] Hosts.ConsoleRunHost - Control+Break detected, terminating service (not cleanly, use Control+C to exit cleanly)` few google searches and I ended up using `kill_signal` to try and get the driver to send a Control+C signal to the app, that didn't work, after looking at the source code I figured that the signal is actually hardcoded here: https://github.com/hashicorp/nomad/blob/v0.11.0/drivers/shared/executor/executor_windows.go#L53 

Is this intentional for the windows driver? The Linux driver seems to be configurable, to get feature parity wouldn't it make sense to enable the same behavior for the Windows one? 

I suppose the signals will be different and would need to follow something similar to what syscall supports:
```
    CTRL_C_EVENT        = 0
    CTRL_BREAK_EVENT    = 1
    CTRL_CLOSE_EVENT    = 2
    CTRL_LOGOFF_EVENT   = 5
    CTRL_SHUTDOWN_EVENT = 6
```

Happy to have a crack at opening a PR for this if it's something that the team/community simply hasn't gotten around to doing.

**Comment by tgross** [comment]
Hi @atomovski. Thanks for reporting this! My understanding is that `CTRL_C_EVENT`/`SIGINT` won't work for process groups, which risks having processes leak, and that's why we did it that way. You'll note that the Docker daemon doesn't use `SIGINT` either for that reason (ref https://github.com/hashicorp/nomad/blob/v0.11.0/drivers/docker/driver.go#L1241-L1247).

However, it definitely seems like a missing feature that `kill_signal` doesn't work for Windows for those rare cases when someone is using some kind of signal interception that will make this safe to do. So we'd love to accept a PR for implementing it!

**Comment by atomovski** [comment]
@tgross thanks for the quick reply, that makes perfect sense, I suppose our case is a bit different.
In any case, I'll give the PR a go over the next weekend.

**Comment by atomovski** [comment]
@tgross a bit of an update on this issue. Finally, I got around to getting my nomad dev environment setup and all that so I was able to do a more in-depth analysis. 

First of all, you're absolutely right CTRL_C_EVENT does not work for process groups, here's the link to the [documentation](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent) but the important line is this one: _This signal cannot be generated for process groups. If dwProcessGroupId is nonzero, this function will succeed, but the CTRL+C signal will not be received by processes within the specified process group._

Now I did test this by simply commenting out the `e.childCmd.SysProcAttr.CreationFlags = syscall.CREATE_NEW_PROCESS_GROUP` in the executor, in this case, the signal is properly propagated to the process, but there is the obvious risk of having process leaks. 

So at this point, I'm at a bit of a loss what do to here. In my humble opinion there are two potential approaches:
1. A complicated implementation where when starting the job/process we would check the `kill_signal` specified and if it's `SIGINT` we would start the process without the process group flag. 
2. We leave this as is and improve the documentation to call out the Windows limitation. 

So before going further down the rabbit hole I thought I'd check in with you guys and see what's your preferred approach. I'm happy to try and implement option 1 from above if that helps with the decision or maybe you can think of an alternative or point me to someone from the team/community that can think of something better. Thanks!

**Comment by tgross** [comment]
I don't think we should start the process without the process group flag, because that's the sort of thing that fails almost silently until the user realizes they've got a bunch of leaked processes running and don't know why. The documentation could definitely use some improvement though!

**Comment by AbhinJames** [comment]
Hi,

**Comment by AbhinJames** [comment]
Hi,

**Comment by AbhinJames** [comment]
Hi,

Do we know if this issue has been resolved or not? 

Thanks
