### ISSUE TITLE
Nomad attempting to allocate job even if host does not have the resources

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#7755]
### Nomad version
Nomad Version 0.10.2

### Operating system and Environment details
PhotonOs 3

### Issue
We have a scenario where we have 2 of 3 hosts attempting to schedule a job that there are not enough resources on the host to run.

* Nomad UI reports +-4 4 gig of reserved memory available (see screenshot)
<img width="579" alt="Screen Shot 2020-04-20 at 10 05 25 AM" src="https://user-images.githubusercontent.com/46198537/79761589-a7aaba80-82ef-11ea-9b65-6515a39765cb.png">

* "top" command reports 49% of memory used but does not list processes that match up to that number (see screenshot but we are following up with the Photon team on this)
<img width="1789" alt="Screen Shot 2020-04-20 at 10 05 52 AM" src="https://user-images.githubusercontent.com/46198537/79761601-abd6d800-82ef-11ea-92b6-3d83d367d09e.png">

* "free -m" reports the same metrics as Nomad UI for memory/cpu usage (see screenshot)
<img width="594" alt="Screen Shot 2020-04-20 at 10 06 10 AM" src="https://user-images.githubusercontent.com/46198537/79761615-b09b8c00-82ef-11ea-9927-1026c08ceccc.png">

Nomad is able to schedule the job on the host even though there are not enough resources for the allocation.   This in turn causes the JVM to fail (as expected).

<img width="1114" alt="Screen Shot 2020-04-20 at 10 14 42 AM" src="https://user-images.githubusercontent.com/46198537/79761685-c4df8900-82ef-11ea-9049-b5e295d52475.png">

# Job File
The nomad job file snipped (cannot include the entire file) requests resources for the task as 

resources {
        cpu    = 2048 # Mhz
        memory = 6144 # Mb

        network {
          port "kafka_public" {
            static = 9092
          }

          port "kafka_inside" {
            static = 9094
          }

          port "kafka_jolokia_http_port" {
            static = 8778
          }

          port "kafka_jolokia_jmx_port" {
            static = 9999
          }
        }
      }

Inside of this task there is a JVM heap setting that is 5024 (less than the requested resources).

**Comment by tgross** [comment]
@idrennanvmware can you provide the results of `nomad alloc status -verbose :alloc_id`? It'd be helpful to see what the scheduler is reporting as its decision-making process here.

> Inside of this task there is a JVM heap setting that is 5024 (less than the requested resources).

Keep in mind that the requested resources needs to cover the JVM heap and whatever kernel memory is required for the container's process group. That doesn't seem to be the issue here as this seems to be a scheduling issue, but just a heads up.

**Comment by idrennanvmware** [comment]
@tgross I apologize but we ran out of time (it was a production cluster) and needed to restart the VMs.   After that the job got stuck in a half on half off state and wouldn't get past "pending (stopping)" in the nomad CLI.   Overnight it rectified itself and is running.   If we see this again we can run the commands you suggested (apologies again but we weren't sure what to run that would provide useful information)

**Comment by idrennanvmware** [comment]
@tgross  we are having this issue again.  Here is the results from the node for the commands you requested

From the machine that the alloc was attempted on (and failed)
/usr/local/bin/nomad alloc status -verbose 6da882b8-8eb7-5c82-7436-55ae585f6abc

ID                     = 6da882b8-8eb7-5c82-7436-55ae585f6abc
Eval ID                = adb93f37-ebce-257f-aa22-770823b38f6e
Name                   = kafka-cluster.kafka-group[1]
Node ID                = c44c7c28-fe94-b937-e474-409965f55800
Node Name              = XXXX
Job ID                 = kafka-cluster
Job Version            = 2
Client Status          = failed
Client Description     = Failed tasks
Desired Status         = run
Desired Description    = <none>
Created                = 2020-04-27T15:30:27Z
Modified               = 2020-04-27T15:31:12Z
Reschedule Eligibility = 55m42s from now
Evaluated Nodes        = 31
Filtered Nodes         = 30
Exhausted Nodes        = 0
Allocation Time        = 426.63µs
Failures               = 0

Task "kafka-logging-task" is "dead"
Task Resources
CPU        Memory          Disk     Addresses
0/100 MHz  22 MiB/100 MiB  300 MiB

Task Events:
Started At     = 2020-04-27T15:30:28Z
Finished At    = 2020-04-27T15:31:07Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type                 Description
2020-04-27T15:31:07Z  Killed               Task successfully killed
2020-04-27T15:31:07Z  Terminated           Exit Code: 0
2020-04-27T15:31:06Z  Killing              Sent interrupt. Waiting 5s before force killing
2020-04-27T15:31:06Z  Sibling Task Failed  Task's sibling "kafka-task" failed
2020-04-27T15:30:28Z  Started              Task started by client
2020-04-27T15:30:27Z  Task Setup           Building Task Directory
2020-04-27T15:30:27Z  Received             Task received by client

Task "kafka-task" is "dead"
Task Resources
CPU         Memory           Disk     Addresses
0/2048 MHz  584 KiB/6.0 GiB  300 MiB  kafka_public: XX:9092
                                                                        kafka_inside: XX:9094
                                                                        kafka_jolokia_http_port: XX:8778
                                                                        kafka_jolokia_jmx_port: XX:9999

Task Events:
Started At     = 2020-04-27T15:31:05Z
Finished At    = 2020-04-27T15:31:06Z
Total Restarts = 2
Last Restart   = 2020-04-27T15:30:47Z

Recent Events:
Time                  Type            Description
2020-04-27T15:31:06Z  Killing         Sent interrupt. Waiting 5s before force killing
2020-04-27T15:31:06Z  Not Restarting  Exceeded allowed attempts 2 in interval 30m0s and mode is "fail"
2020-04-27T15:31:06Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2020-04-27T15:31:05Z  Started         Task started by client
2020-04-27T15:30:47Z  Restarting      Task restarting in 18.183484724s
2020-04-27T15:30:47Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2020-04-27T15:30:46Z  Started         Task started by client
2020-04-27T15:30:29Z  Restarting      Task restarting in 16.251411953s
2020-04-27T15:30:29Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2020-04-27T15:30:28Z  Started         Task started by client

Task "kafka-telegraf-task" is "dead"
Task Resources
CPU       Memory         Disk     Addresses
6/64 MHz  15 MiB/64 MiB  300 MiB

Task Events:
Started At     = 2020-04-27T15:30:28Z
Finished At    = 2020-04-27T15:31:12Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type                 Description
2020-04-27T15:31:12Z  Killed               Task successfully killed
2020-04-27T15:31:11Z  Terminated           Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"
2020-04-27T15:31:06Z  Killing              Sent interrupt. Waiting 5s before force killing
2020-04-27T15:31:06Z  Sibling Task Failed  Task's sibling "kafka-task" failed
2020-04-27T15:30:28Z  Started              Task started by client
2020-04-27T15:30:27Z  Task Setup           Building Task Directory
2020-04-27T15:30:27Z  Received             Task received by client

Placement Metrics
  * Constraint "missing drivers": 10 nodes excluded by filter
  * Constraint "distinct_hosts": 2 nodes excluded by filter
  * Constraint "${meta.kafka_server_linux} = true": 18 nodes excluded by filter
Node                                  binpack  job-anti-affinity  node-affinity  node-reschedule-penalty  final score
c44c7c28-fe94-b937-e474-409965f55800  0.884    0                  0              -1                       -0.0579




================
node status -verbose c44c7c28-fe94-b937-e474-409965f55800

ID              = c44c7c28-fe94-b937-e474-409965f55800
Name            = XX
Class           = <none>
DC              = XX
Drain           = false
Eligibility     = eligible
Status          = ready
CSI Controllers = <none>
CSI Drivers     = <none>
Uptime          = 159h58m16s

Host Volumes
Name  ReadOnly  Source

CSI Volumes

Drivers
Driver    Detected  Healthy  Message  Time
docker    true      true     Healthy  2020-04-23T23:07:04Z
exec      true      true     Healthy  2020-04-23T23:07:04Z
java      false     false    <none>   2020-04-23T23:07:04Z
qemu      false     false    <none>   2020-04-23T23:07:04Z
raw_exec  true      true     Healthy  2020-04-23T23:07:04Z

Node Events
Time                  Subsystem  Message                         Details
2020-04-26T04:55:53Z  Cluster    Node reregistered by heartbeat  <none>
2020-04-26T04:55:42Z  Cluster    Node heartbeat missed           <none>
2020-04-26T04:55:15Z  Cluster    Node reregistered by heartbeat  <none>
2020-04-26T04:55:12Z  Cluster    Node heartbeat missed           <none>
2020-04-20T23:42:49Z  Cluster    Node registered                 <none>

Allocated Resources
CPU           Memory           Disk
876/5600 MHz  804 MiB/7.8 GiB  900 MiB/182 GiB

Allocation Resource Utilization
CPU          Memory
35/5600 MHz  114 MiB/7.8 GiB

Host Resource Utilization
CPU           Memory           Disk
278/5600 MHz  4.8 GiB/7.8 GiB  5.4 GiB/197 GiB

Allocations
ID                                    Eval ID                               Node ID                               Task Group                   Version  Desired  Status   Created               Modified
6da882b8-8eb7-5c82-7436-55ae585f6abc  adb93f37-ebce-257f-aa22-770823b38f6e  c44c7c28-fe94-b937-e474-409965f55800  kafka-group                  2        run      failed   2020-04-27T15:30:27Z  2020-04-27T15:31:12Z
d7c340fe-2ddb-8b98-727c-7205c8d6434e  c9b460a2-4acc-a3f5-050f-045c00a0e7b5  c44c7c28-fe94-b937-e474-409965f55800  kafka-group                  2        stop     failed   2020-04-27T14:29:40Z  2020-04-27T15:30:27Z
ec1fd198-34f0-faaa-9c57-f4aab33b5661  4ee73f86-1312-070c-2f96-9f84c519954b  c44c7c28-fe94-b937-e474-409965f55800  control-plane-logging-group  4        run      running  2020-04-26T04:55:53Z  2020-04-26T04:57:16Z
0a4cf7cb-61e8-8443-a2a3-c39f231322b9  6c268900-09bd-d42b-26ba-cc6f96d3c5da  c44c7c28-fe94-b937-e474-409965f55800  fabio-linux                  13       run      running  2020-04-26T04:55:53Z  2020-04-27T00:47:28Z
d1f327af-53ed-a707-88f5-70ca119e0675  355b29c4-30b6-de57-1d5c-221291bd81ec  c44c7c28-fe94-b937-e474-409965f55800  telegraf-statsd              8        run      running  2020-04-26T04:55:53Z  2020-04-26T04:57:16Z

Attributes
consul.datacenter             = XX
consul.revision               = 9ea1a204d
consul.server                 = false
consul.version                = 1.7.2
cpu.arch                      = amd64
cpu.frequency                 = 2800
cpu.modelname                 = Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
cpu.numcores                  = 2
cpu.totalcompute              = 5600
driver.docker                 = 1
driver.docker.bridge_ip       = 172.17.0.1
driver.docker.os_type         = linux
driver.docker.runtimes        = runc
driver.docker.version         = 18.09.9
driver.docker.volumes.enabled = true
driver.exec                   = 1
driver.raw_exec               = 1
kernel.name                   = linux
kernel.version                = 4.19.97-1.ph3
memory.totalbytes             = 8339865600
nomad.advertise.address       = XX:4646
nomad.revision                = b43457070037800fcc8442c8ff095ff4005dab33
nomad.version                 = 0.11.1
os.name                       = photon
os.signals                    = SIGIO,SIGKILL,SIGSYS,SIGTTIN,SIGURG,SIGALRM,SIGCHLD,SIGCONT,SIGPROF,SIGUSR2,SIGXFSZ,SIGINT,SIGXCPU,SIGQUIT,SIGTERM,SIGTTOU,SIGBUS,SIGIOT,SIGUSR1,SIGABRT,SIGILL,SIGTRAP,SIGWINCH,SIGFPE,SIGHUP,SIGPIPE,SIGSEGV,SIGSTOP,SIGTSTP
os.version                    = 3.0
unique.cgroup.mountpoint      = /sys/fs/cgroup
unique.consul.name            = XX
unique.hostname               = XX
unique.network.ip-address     = XX
unique.storage.bytesfree      = 195788570624
unique.storage.bytestotal     = 211234803712
unique.storage.volume         = /dev/sda3
vault.accessible              = true
vault.cluster_id              = d4185054-b5ee-1461-de5d-2a4cf748269a
vault.cluster_name            = XX
vault.version                 = 1.4.0

Meta
connect.log_level     = info
connect.sidecar_image = envoyproxy/envoy:v1.11.2@sha256:a7769160c9c1a55bb8d07a3b71ce5d64f72b1f665f10d81aa1581bc3cf850d09
kafka_server_linux    = true
linux                 = true
nomad_version         = 0.11.1

**Comment by idrennanvmware** [comment]
<img width="554" alt="Screen Shot 2020-04-27 at 11 42 09 AM" src="https://user-images.githubusercontent.com/46198537/80391797-3a150600-887c-11ea-970a-8e1cc72992d4.png">

**Comment by idrennanvmware** [comment]
An interesting side effect @tgross.   Here are the steps I did

1. reboot above machine
2. nomad job stop -purge kafka-cluster
3. Rerun the job (has a min count of 3)
4.  Nomad thinks the desired count is 2 (even though job file says 3).

I to rectify this I had to 
1. nomad job stop -purge kafka-cluster
2. Run GC on the cluster
3.  Reschedule the job (3 are desired and placed)

**Comment by idrennanvmware** [comment]
@tgross I can now confirm this is a widespread problem across multiple clusters.   We are able to manually remediate with the steps listed above (purge, GC, reschedule) but this is fast becoming an issue for us.   The common thing across the  node types kafka and zookeeper at this point, but that may just be coincidental given the resource constraints of those systems that we have

**Comment by tgross** [comment]
Hi @idrennanvmware! I took a look at the output from `node status -verbose :node_id` that you provided and I'm seeing the following interesting numbers:

```
allocation resources:            804 MiB/7.8 GiB
allocation resource utilization: 114 MiB/7.8 GiB
host resource utilization:       4.8 GiB/7.8 GiB
```

So it looks like the memory being is being used by tasks not managed by Nomad, which Nomad isn't taking into account for placements. I think there may be some documentation gaps here and I want to circle back on that, but if you set a [`reserved`](https://www.nomadproject.io/docs/configuration/client/#reserved-parameters) config for the memory being used on the host this _should_ give you a workaround in the meantime. (See also https://github.com/hashicorp/nomad/issues/6892 though for a UI bug with the reserved memory.)

**Comment by idrennanvmware** [comment]
@tgross thanks for the pointer.   Will Nomad actually pre-allocate that reserved amount then?  Or is there still a risk of these unaccounted processes consuming the requested reserved memory?

**Comment by tgross** [comment]
> Will Nomad actually pre-allocate that reserved amount then? Or is there still a risk of these unaccounted processes consuming the requested reserved memory? Also, is Nomad supposed to account for those resources in the scenario we encountered and just isn't (my understanding is yes)?

The way the reserve works is that the scheduler treat it as if that client node has _n_ less memory. Ex. assuming a client node that fingerprints as having 8GB with a 1GB reserve, the scheduler will treat it as if it were a 7GB client node for allocating tasks to it. I guess you could think of it as "pre-allocated" as you say, but it wouldn't show up in the allocated memory so that might be confusing.

In any case the `reserve` isn't protected in any way by Nomad (Nomad doesn't "own" that memory, after all), so if those unaccounted processes eat that memory they can intrude into the space that Nomad is assuming it has to work with. That being said, it looks like PhotonOS has systemd, so I think you could configure the `system.slice` cgroup to constrain the memory of all the services that systemd manages, and then leave all the rest to Nomad's workloads. The Nomad workloads won't be children of `system.slice`, so that should let you partition the memory space up.
