### ISSUE TITLE
ACL usage logging

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#7759]
### Nomad version
`v0.10.4`

### Issue

When ACLs are set, there's no way to track the actions of an ACL token.

For example, you have 10 users with 10 ACL tokens: how can you find which user tried to alloc exec for example?

We tried enabling debug level but we can't find the information in client or server logs.

**Comment by notnoop** [comment]
Hi @scalp42!  This is not supported in our open source offering. You can add a reverse proxy that can log token headers (or a hash of it), or use a custom binary with a patch to the http endpoint logging.

Though, this functionality comes built-in with Nomad Enterprise now.  Nomad 0.11 Enterprise introduced  audit logging capabilities - you can see more details in https://www.hashicorp.com/blog/hashicorp-nomad-enterprise-audit-logging/ .
