### ISSUE TITLE
[CSI, AWS EBS] - Volume Setup Failure on t3 instances. 

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#7764]
### Nomad version
Nomad v0.11.0 (5f8fe0afc894d254e4d3baaeaee1c7a70a44fdc6)

### Operating system and Environment details
Ubuntu 18.04 on Amazon t3.small instances

### Issue
When I attempt to mount a volume into a job I receive the following error event:

```
Recent Events:
Time                  Type           Description
2020-04-21T13:53:07Z  Setup Failure  failed to setup alloc: pre-run hook "csi_hook" failed: rpc error: code = Internal desc = Failed to find device path /dev/xvdba. nvme path "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_mysql" not found
```

I would expect this path to be `/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_«amazon volume id»`

### Reproduction steps

Run a dev agent on a AWS t3 instance.  Follow the guide process on [learn](https://learn.hashicorp.com/nomad/stateful-workloads/csi-volumes)

### Job file (if appropriate)
included in the learn scenario

**Comment by angrycub** [comment]
This looks to be the same issue as #7568, and I tested and verified that #7754 solves it.

**Comment by tgross** [comment]
Thanks @angrycub! That'll go out in the upcoming 0.11.1 release.
