### ISSUE TITLE
CSI: show a useful error for on schedule / job validation for incompatible task drivers

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#7774]
Task drivers like QEMU can't support CSI, so we should show a useful error to the operator when they try to schedule a job (or validate one), rather than erroring-out at the client.

**Comment by tgross** [comment]
I tested this out a bit and it looks like QEMU doesn't support host volumes either. But because there's no checking, the jobspec will let you configure it and it just won't work (the volume isn't mounted).

So I'm wondering whether we should add a new field to the [Driver Capabilities](https://www.nomadproject.io/docs/internals/plugins/task-drivers/#capabilities-capabilities-error) struct so that we can test this as part of task driver fingerprinting.

**Comment by angrycub** [comment]
I believe that I ran into this with the java driver on macOS because it doesn't have FSIsolation as well.
