### ISSUE TITLE
Add support for `initial_management` token like in Consul

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#7777]
It would be great if it were possible to preset a token with access-id & secret-id like in consul: https://www.consul.io/docs/agent/options.html#acl_tokens This way nomad could be initialized easier via configuration management tools.

**Comment by evandam** [comment]
Agreed, having the option to create tokens with predefined values like in Consul would be a big help and keep things more consistent.

**Comment by scalp42** [comment]
Same here main use case is configuration management so we could have clusters bootstrap ACLs themselves in a much more straightforward way.

**Comment by Y-Tian** [comment]
+1 we would like to see this feature as well.

**Comment by th0m** [comment]
+1, would love to get feature parity with Consul for token management.

**Comment by notnoop** [comment]
Good suggestion!  We will mark it as an enhancement we'd consider in the roadmap.  Thanks!

**Comment by apollo13** [comment]
Copying my comment from the PR so it doesn't get lost when the PR is closed:

What do you think about altering the /acl/bootstrap endpoint (or maybe even introduce a new one) to allow the enduser to submit a token pair to it (AccessorID & SecretID) which will be used as the initial management token? This way you can safely store the token pair in a system suitable for your automation (for example an ansible vault) but you would not leak it onto the machines.

**Comment by apollo13** [comment]
Looks like this would be fixed by #12520
