### ISSUE TITLE
[bug] Running field of TaskGroupScaleStatus doesn't get populated

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#7789]
### Nomad version
`Nomad v0.11.2-dev`

Currently the [Running field](https://github.com/hashicorp/nomad/blob/1b446bd3efe8be6164ba72e401de7b626cbad59d/nomad/structs/structs.go#L1258) of `structs.JobScaleStatus` is never populated when [hydrating the response](https://github.com/hashicorp/nomad/blob/1b446bd3efe8be6164ba72e401de7b626cbad59d/nomad/job_endpoint.go#L1823) unlike other fields. Do we need this field, and if so, what should be used to populate it? If we do not need the field it should be removed from the internal struct and API response object.

**Comment by cgbaker** [comment]
going to add on to this bug: when the job is scaled to zero, nomad does not create a deployment. therefore, the current code is reporting invalid information by using the latest deployment, which refers to a previous version of the job. this should be corrected.
