### ISSUE TITLE
Host volumes are mouted on top of templates, artifacts and dispatch payloads

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad#7796]
It's not possible to have an `artifact` or a `template` or a `dispatch_payload` inside a `host_volume` because they are resolved before the volume is mounted into the allocation, and so the target directory appears empty when the allocation starts.

This happens despite the [volume hook being executed before the artifact hook](https://github.com/hashicorp/nomad/blob/v0.11.1/client/allocrunner/taskrunner/task_runner_hooks.go#L67-L68) because the hook only registers the volumes, the actual mounting happens later on in the driver.

### Steps to reproduce
1. Create a host volume called `volume`

```hcl
client {
  enabled = true

  host_volume "volume" {
    path = "/opt/nomad-volumes/volume"
  }
}
```

2. Run this job:

```hcl
job "example" {
  datacenters = ["dc1"]
  type        = "batch"

  parameterized {
    payload = "required"
  }

  group "example" {
    volume "volume" {
      type   = "host"
      source = "volume"
    }

    task "example" {
      driver = "exec"

      config {
        command = "ls"
        args    = ["/local/volume"]
      }

      artifact {
        source      = "https://gist.githubusercontent.com/lgfa29/6cc9dde5e99c091f91827d718de7efbe/raw/ad374be84b47bc2a601849b3f5e87f1c3954cbb5/artifact.txt"
        destination = "/local/volume/artifact.txt"
      }

      dispatch_payload {
        file = "volume/config.txt"
      }

      template {
        data        = "template"
        destination = "/local/volume/template.txt"
      }

      volume_mount {
        volume      = "volume"
        destination = "/local/volume"
      }
    }
  }
}
```

3. Dispatch the job with some payload
```sh
$ cat << EOF | nomad job dispatch example -
{ "payload": "payload" }
EOF

```
4. Check alloc logs

#### Expected output
```
artifact.txt
config.txt
template.txt
```

#### Actual output
```
```

**Comment by tgross** [comment]
Adding a note from an internal discussion that this may have been the original source of https://github.com/hashicorp/nomad/issues/6709, as the jobspec might have hit this case.

**Comment by tgross** [comment]
Not strictly related but we should make sure our fix for this considers a future feature request: https://github.com/hashicorp/nomad/issues/6536

**Comment by tgross** [comment]
Some follow up on this: https://github.com/hashicorp/nomad/issues/8919 explains some of the filesystem layout prior to the volumes being mounted. This illustrates the problem with templating anywhere that isn't in one of the three typical Nomad-controlled bind-mounts (`NOMAD_ALLOC_DIR`, `NOMAD_TASK_DIR`, and `NOMAD_SECRETS_DIR`), which is that the task driver's root file system is not necessarily co-located with the "task directory" at all.

**Comment by tgross** [comment]
I've documented the existing situation in https://github.com/hashicorp/nomad/pull/9098 and https://github.com/hashicorp/nomad/pull/9195, but while writing those up I've come to realize this behavior is intentional and probably unavoidable given that task drivers have to own the mounting process. So my proposal for dealing with this issue is:

* get #9195 reviewed and merged
* look into whether we can do some validation to make sure folks don't try to mount their volumes on top of their Nomad-created bind-mounts. (We might not be able to do this during jobspec validation, but we certainly could do so on the client at absolute worst.)

**Comment by tgross** [comment]
Documented behavior is now at: https://www.nomadproject.io/docs/internals/filesystem#templates-artifacts-and-dispatch-payloads

Going to keep this one open until we have the validation done.

**Comment by tgross** [comment]
Closing in lieu of https://github.com/hashicorp/nomad/issues/9848
