### ISSUE TITLE
[UI] Too much red for healthy deploys

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#7798]
We are in the process of rolling out nomad to my company. Every time we show a developer the UI, they *think* the deploy failed because they see so much red. We need to explain that red is just the history of the job, not the current job

For example here is a job that is deploying perfectly. It has been deployed 4 times. The first 2 times had an error, but the last 2 deploys were successful. The failures appear more prominent than the success leading the user to believe half of the current deploy failed. 

![Screenshot 2020-04-23 17 19 07](https://user-images.githubusercontent.com/242382/80158931-0d64a400-8587-11ea-82e5-9acb16d34c27.png)

Ways this can be improved

1. Make the "Latest Deployment" More prominant
2. Hide all past deploys near the bottom, or better yet collapse the dialog box
3. Get rid of the green/red horizontal bar

**Comment by rkettelerij** [comment]
> We need to explain that red is just the history of the job, not the current job

Sounds familiar.

**Comment by DingoEatingFuzz** [comment]
This is useful feedback and I completely agree with the problem and the analysis.

I personally still find the status visualization useful for seeing allocations proceed through queued, starting, and running/failed states. 

It makes a lot of sense to separate which allocations are visualized (or at least how they are visualized) based on job version. And we also have to factor in batch jobs, system jobs, and the variation used for periodic and parameterized jobs.

I'll be personally noodling on some changes to this presentation but I am also very open to hearing what other people think will be helpful. At the very least, what information you find most useful to see in this context.

Thank you for starting the conversation @spuder!

**Comment by shantanugadgil** [comment]
My 0.02 ...

We run an hourly `system gc` and `system reconcile summaries` to keep things clean (sort of).

I know it doesn't solve the original problem, but could that help?

**Comment by bfqrst** [comment]
`nomad system gc` I knew, but `nomad system reconcile summaries` escaped me somehow... Thanks for sharing @shantanugadgil. I don't know if I'd fire it on a hourly schedule because I want to be in the loop about what goes "red" or "black", but it sounds like something that I would do maybe say weekly...

**Comment by shantanugadgil** [comment]
Curious why would you want to deliberately leave it for a week?
Wouldn't some sort of metric collector record state of failed jobs for long term storage?

**Comment by Lord-Y** [comment]
Things will be better in the 1.6.0 release. It will be out soon. You could already see the difference in the beta or rc

**Comment by philrenaud** [comment]
Great news, this is addressed in Nomad 1.6! The component in question has been rebuilt from the ground up; check out the [Nomad 1.6 blog post](https://www.hashicorp.com/blog/nomad-1-6-adds-node-pools-ux-updates-and-more) for an example of what it looks like now.

You'll no longer see the red/failure status of historic deployments/long-gone allocations.

**Comment by mikenomitch** [comment]
Thanks for the hard work on this @philrenaud!

The one spot we weren't able to get to yet is the Job Index page, as we needed some backend tweaks to get the right info to that page. We plan to work on this between 1.6 and 1.7 though, so that should be coming relatively soon as well.

**Comment by Lord-Y** [comment]
Yep glad to see the final version out after testing the rc/beta
