### ISSUE TITLE
Nomad UI cannot browse /alloc volume

### ISSUE THREAD

**Issue by gmichalec-pandora** [hashicorp/nomad#7799]
### Nomad version

0.11.1+ent

### Operating system and Environment details
Debian Stretch

### Issue
The nomad UI currently has no way to browse files in the shared /alloc volume. Unless I am missing it, we can browse files related to a particular task by clicking the allocation -> task -> files, but there is no UI path that will display files in the /alloc volume, as shown in the following cli command:
```$ nomad alloc fs 0ca47fd7-b6f1-88e2-1889-7429e422b0a6
Mode        Size     Modified Time              Name
drwxrwxrwx  4.0 KiB  2020-04-24T13:04:14-07:00  alloc/
drwxrwxrwx  4.0 KiB  2020-04-24T13:04:21-07:00  savagecloud-monitoring/
```
In my experience, users are more likely to make use of the /alloc shared volume than the local task directory, so being able to easily browse and view files in that path would greatly improve the UX

The nomad UI has improved by leaps and bounds - great effort guys! I believe this is the last major feature we would need to migrate our users to using nomad UI vs the 3rd party hashi-ui tool.

**Comment by DingoEatingFuzz** [comment]
Thank you for this report! This is a pretty glaring oversight that emerged from our decision to show the filesystem at the task level rather than the allocation level.

We definitely need to address this.

**Comment by gmichalec-pandora** [comment]
Thank you! I'll also add, though this is purely anecdotal, several of our users had trouble finding the logs/files UIs. It seems that the putting them at the task level was not easily discoverable - though this may be primarily due to our users being accustomed to using hashi-ui, which does roll up the logs/files at the alloc level. I can see arguments for both approaches.

**Comment by backspace** [comment]
Hey, 0.11.3 is [released](https://github.com/hashicorp/nomad/releases/tag/v0.11.3) and it includes a browser for allocation filesystems! Thanks for the feature request and let us know how it works for you. 🥳

**Comment by backspace** [comment]
No problem, thanks for the update! I‘m glad it’s suitable 😀
