### ISSUE TITLE
Consul Connect setup in nomad client - ports unexpected keys grpc

### ISSUE THREAD

**Issue by fairbairn** [hashicorp/nomad#7802]
We have been trying to test out Consul Connect and bridge mode using the instructions from..
https://www.nomadproject.io/docs/integrations/consul-connect/
and the server.hcl and client1.hcl from the vagrant/docker tutorial.

When we update the client1.hcl to the following...
```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "/tmp/client1"

# Give the agent a unique name. Defaults to hostname
name = "client1"

# Enable the client
client {
    enabled = true

    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
    servers = ["127.0.0.1:4647"]

}

ports {
    http = 5656
    grpc = 8502
}

connect {
    enabled = true
}
```
and attempt..

nomad agent -config client1.hcl

we get an error of...

*==> Error loading configuration from client1.hcl: Error loading client1.hcl: ports unexpected keys grpc*

We're using the latest versions...
```
vagrant@nomad:~$ nomad -v
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)
vagrant@nomad:~$ consul -v
Consul v1.7.2
```
and we've installed the CNI plugins.

Whare are we doing wrong?

Is this documentation outdated, and those parameters are deprecated?

**Comment by notnoop** [comment]
Hi @fairbairn .  Sorry for the confusion.

The following snippet is a consul configuration, not a Nomad one, and needed when not using `consul agent -dev`:

```hcl
ports {
  grpc = 8502
}

connect {
  enabled = true
}
```

In the nomad side, you can pass `-dev-connect` without needing additional config options when following that guide.

Hope that helps!

**Comment by fairbairn** [comment]
I think the -dev mode is confusing.

We're setting up for a production system.  We're not using dev mode.

We need clarity on what needs to be installed on the host, to support Consul Connect and bridged network mode.

We're using the Vagrant setup as a guide, but it's unclear what we really need to install at this point.  We're essentially having to piece together information.  We were hoping this was fairly accurate, and by adding the install of the cfssl plugins, it would work.

```
echo "Installing Nomad..."
NOMAD_VERSION=0.11.1
cd /tmp/
curl -sSL https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip -o nomad.zip
unzip nomad.zip
sudo install nomad /usr/bin/nomad
sudo mkdir -p /etc/nomad.d
sudo chmod a+w /etc/nomad.d

echo "Installing CNI plugins..."
curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.4/cni-plugins-linux-amd64-v0.8.4.tgz
sudo mkdir -p /opt/cni/bin
sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

echo "Installing Consul..."
CONSUL_VERSION=1.7.2
curl -sSL https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip > consul.zip
unzip /tmp/consul.zip
sudo install consul /usr/bin/consul
(
cat <<-EOF
  [Unit]
  Description=consul agent
  Requires=network-online.target
  After=network-online.target

  [Service]
  Restart=on-failure
  ExecStart=/usr/bin/consul agent -dev
  ExecReload=/bin/kill -HUP $MAINPID

  [Install]
  WantedBy=multi-user.target
EOF
) | sudo tee /etc/systemd/system/consul.service
sudo systemctl enable consul.service
sudo systemctl start consul

for bin in cfssl cfssl-certinfo cfssljson
do
  echo "Installing $bin..."
  curl -sSL https://pkg.cfssl.org/R1.2/${bin}_linux-amd64 > /tmp/${bin}
  sudo install /tmp/${bin} /usr/local/bin/${bin}
done
nomad -autocomplete-install

SCRIPT
```

Maybe you can point us to the documentation where it explains how we set up the requirements for our host machine (the client node) properly.

Thanks!
