### ISSUE TITLE
Nomad advertising wrong IP address for service

### ISSUE THREAD

**Issue by sbrl** [hashicorp/nomad#7803]
### Nomad version
Output from `Nomad v0.11.0 (5f8fe0afc894d254e4d3baaeaee1c7a70a44fdc6)`

### Operating system and Environment details
5 x Raspberry Pi 4

`uname -a`: `Linux PI_NAME 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`

### Issue
When running a job that advertises to Consul, the wrong IP address is returned. I have the following network interfaces on all nodes in the cluster:

Interface | Use
------------|--------
`lo` | loopback
`eth0` | Ethernet; the world is out here (IP range: 172.16.230.0/24)
`wgoverlay` | VPN; Containers *should* be port mapped to here (IP range: 172.31.250.0/16)
`docker0` | The docker network (IP range: `172.17.0.1/16`)

Once the steps below are run through, the a Docker registry container is correctly started.... but it forwards through to the wrong interface! Doing a `dig +short registry.service.mooncarrot.space -p 8600` yields the IP of the `eth0` interface of the host machine upon which the registry is running, not the IP of the `wgoverlay` interface - which, I might add, both Nomad _and_ Consul are using to cluster (e.g. `bind_addr` is set like this: `bind_addr = "{{ GetInterfaceIP \"wgoverlay\" }}"` - see more details below).

I want Nomad to port forward the registry to the `wgoverlay` interface. I also want it to advertise the host's IP on the **`wgoverlay`** interface, not the `eth0` interface via DNS (since I have UFW blocking incoming connections on `eth0`). I thought this would be implicit since I set the `bind_address` in the agent config, but apparently not.

### Reproduction steps
 - Get some servers
 - Setup a VPN between all servers
 - Setup Consul on all servers, specifying the bind address of the vpn interface
 - Setup Nomad (again binding to the VPN interface)
 - Run the below job file
 - See bug 

**Consul Configs:** [Client](https://ybin.me/p/8ae5922a26186206#dCFiRYBMhBc+ghDw9KJxkteAQzWAwSB+dtcfqLyPSs0=), [Server](https://ybin.me/p/c36d07e9db535fa4#VErZrzpOBGc1MC6ZYmdbxmliJA0Dr2r9izVSRaNa0f4=)

**Nomad Configs:** [Server](https://ybin.me/p/8cfa87a05f555a7a#VWXt21zzJb0kGFzu8I7I/b7l+NWLTESbGXg8icfi7Jc=), [Client](https://ybin.me/p/65b7a33dfbc60d8f#Uz1zXRAnVbG0rBXkBqRwVw1piJAco14pqrnTvK4IGUo=), [Client and Server](https://ybin.me/p/1b4f0bd4415cb2d1#xDSr9a9clRRp7QkSaNapMpkzTR33PbkgtMo96yT4ouQ=)

### Job file (if appropriate)
```hcl
job "registry" {
	datacenters = ["dc1"]
	
	group "main" {
		
		task "registry" {
			driver = "docker"
			
			config {
				image = "registry:2"
				labels { group = "registry" }
				
				volumes = [
					"/mnt/shared/registry:/var/lib/registry"
				]
				
				port_map {
					registry = 5000
				}
			}
			
			resources {
				network {
					port "registry" {}
				}
			}
			
			service {
				name = "${TASK}"
				tags = [ "infrastructure" ]
				
				address_mode = "host"
				port = "registry"
				check {
					type		= "tcp"
					port		= "registry"
					interval	= "10s"
					timeout		= "3s"
				}
				
			}
		}
	}
}
```
### Nomad Client logs (if appropriate)

 - `docker inspect {container_id}`: https://hastebin.com/ihigesuher
`docker ps`:

```
sudo docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                            NAMES
b09cbaee99ed        registry:2          "/entrypoint.sh /etc…"   54 minutes ago      Up 54 minutes       172.16.230.102:21760->5000/tcp, 172.16.230.102:21760->5000/udp   registry-9d82f547-d98f-d761-b576-07ccf30398db
```

**Comment by notnoop** [comment]
Hi @sbrl .  Thanks for reaching out.  I believe [`network_interface`](https://www.nomadproject.io/docs/configuration/client/#network_interface) config is what you are looking for.  Try having the following in your client configs:

```hcl
client {
    enabled = true
    # Note that Nomad finds other servers automagically through the consul cluster
    
    # Just a worker, nothing special going on here
    node_class = "worker"

    # use wgoverlay for network fingerprinting and forwarding
    network_interface = "wgoverlay"
}

```

Let me know if that solves your issue.

**Comment by sbrl** [comment]
Hey, that fixed it - thanks so much @notnoop! :D
