### ISSUE TITLE
Variable interpretation appears to be broken

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#781]
Tried both
`"$meta.xxx"` and `"${meta.xxx}"` syntax,
in both args and env
variables come in raw uninterpreted form

```
nomad --version
Nomad v0.2.3
```

Use case: pass nomad node meta data(client.meta) to the docker container either via env or args
I store internal LAN IP inside client.meta and want docker know this address

Could you please check?

**Comment by dadgar** [comment]
Hey this is coming with Nomad 0.3 :+1:
