### ISSUE TITLE
Exec UI failing when job.ID != job.Name

### ISSUE THREAD

**Issue by PouuleT** [hashicorp/nomad#7814]
### Nomad version 
Output from `nomad version`
```
Nomad v0.11.1
```
### Operating system and Environment details
Debian buster

### Issue
I am running a job:
ID: f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd
Name: w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

When trying to use the new Exec feature from the UI, I get on the job view:
https://server/ui/jobs/f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

When I click on "Exec", a pop up opens with this:
![nomad-not-found](https://user-images.githubusercontent.com/743683/80389868-f2a66e00-88ab-11ea-9b75-d443448fa8a9.png)
URL of the popup :
https://server/ui/exec/w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

If I manually change the URL to https://server/ui/exec/f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd , everything runs correctly, the Exec page is loaded and working

### Reproduction steps

Create a Job with an ID that is not the same as the Name ( I do it with the golang library using [this method](https://godoc.org/github.com/hashicorp/nomad/api#NewServiceJob) )
Go to the web UI, try to "Exec" in the job, you'll see that the UI is trying to load the job by its name rather than its ID

### Nomad Server logs
```
Apr 27 17:16:44 host-1 nomad[2782]:     2020-04-27T17:16:44.968+0200 [ERROR] http: request failed: method=GET path=/v1/job/w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd error="job not found" code=404
```

**Comment by backspace** [comment]
Thanks for letting us know about this, I should be able to check it out this week. 💞

**Comment by PouuleT** [comment]
I couldn't find a place in the doc explaining the difference between Name and ID, so when implementing a new Job with the api.NewServiceJob method, I thought I'd use a UUID as the ID, and something more meaningful like service_type.UUID, and everything was working fine so it was great, until now!

When digging into the code while trying to understand the issue, I noticed that in many places, job ID is substituted by job Name.

In the API for example, sometimes the variable is called jobName
https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/command/agent/job_endpoint.go#L66
While in reality it is used as an ID
https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/command/agent/job_endpoint.go#L630

In the UI, take a job_name parameter https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/ui/app/router.js#L18
And rename it to ID in order to find the object
https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/ui/app/routes/exec.js#L19

In the tests of the API, the mock Job has an ID != Name so everything is working and tested as it should be
On the UI side however, I saw that the "mock" job has the ID = Name  https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/ui/mirage/factories/job.js#L17-L19

Indeed, if you change the id to something different than the name, you'll notice that the tests for the "Exec" UI ( and some others ) will fail


So I don't know how to handle this issue, I began working on a fix for the Exec, and then I saw that the job.Name vs job.ID swap is bigger than just the Exec feature.
Is it worth trying to rename jobName to jobID ( when the name is not matching the reality ) in the whole codebase?
