### ISSUE TITLE
Nomad exec driver failure

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#782]
```* Failed to join spawn-daemon to the cgroup (&{Name:753a75af-f3f2-5c66-1f63-02e9ca446235 Parent: ScopePrefix: Resources:0xc82018fb00}): no such directory for memory.swappiness.```

similar issue was fixed for docker
https://github.com/docker/docker/issues/14219

```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.3 (jessie)
Release:        8.3
Codename:       jessie
```
running on amazon ec2.nano, 

nomad is running as root
```
nomad --version
Nomad v0.2.3
```

**Comment by dadgar** [comment]
@let4be can you try on the newest version of Nomad, we have an updated version of libcontainer

**Comment by dadgar** [comment]
Hey I am going to close since we no longer use the spawn-daemon and we have newer version of lib container. If this becomes an issue again we can re-open and get more reproduction steps.
