### ISSUE TITLE
Run earlier submitted jobs first if other requirements are equal

### ISSUE THREAD

**Issue by kcajf** [hashicorp/nomad#7826]
Currently it seems like a more recently submitted job can be scheduled ahead of an older queued job with identical resource requirements. Instead, it would be nice to have the option to tie-break jobs with the same resource requirements and numerical priority by the time they were submitted - jobs submitted earlier should run earlier.

**Comment by kcajf** [comment]
Another way to achieved this could be to increase the range over which priorities can range, from `0-100` to perhaps the full range of an Int64? This would make it possible to pass the negative current time in seconds as the priority.

**Comment by tgross** [comment]
Doing a little bit of issue cleanup. The overall architecture of Nomad scheduling as described in the [Architecture docs](https://developer.hashicorp.com/nomad/docs/concepts/architecture) and [Eval Lifecycle docs](https://github.com/hashicorp/nomad/blob/main/contributing/architecture-eval-lifecycle.md) make firm ordering constraints impossible. However, we did end up extending the maximum priority value to a user-defined maximum: https://developer.hashicorp.com/nomad/docs/configuration/server#job_max_priority
