### ISSUE TITLE
Linking tasks

### ISSUE THREAD

**Issue by mkabischev** [hashicorp/nomad#783]
Hi. In docker I can link containers using `--link` or by docker-compose. Can I do something like this with nomad? For example I have job with two tasks:
- service task (application code)
- cache task (memcache/redis server, which is required for service)

How should I configure job to make cache available in service container?

**Comment by let4be** [comment]
@mkabischev tasks within the same task group are guaranteed to be scheduled on the same host

**Comment by mkabischev** [comment]
@let4be, yes. But how can I get port of cache container into service container if cache port is dynamic?

**Comment by let4be** [comment]
@mkabischev you could utilize consul, nomad integrates with it seamlessly
see: https://www.nomadproject.io/docs/jobspec/index.html
search for `service` blocks

**Comment by mkabischev** [comment]
@let4be yeah, thx. I`ve rethinked everything :)

**Comment by let4be** [comment]
Was glad to help!

**Comment by johnnyplaydrums** [comment]
Hey checking in on this, can I pass a `--link` argument to nomad for when nomad runs the container? My use case is we have the datadog agent container running on each host and would like to link the networking of our other containers to the datadog container using `--link`. How can I pass this option to docker run via nomad?

**Comment by tsujp** [comment]
Unfortunately setting ports breaks when using IPv6, spent a good few days trying to figure out how to do this while also keeping the Docker network in-tact and nothing works.
