### ISSUE TITLE
3 nomad cluster

### ISSUE THREAD

**Issue by funkytaco** [hashicorp/nomad#784]
How can I get a 3-node cluster working with nomad?

My systemd command is:
`/usr/bin/nomad agent -config /etc/nomad `

In /etc/nomad is a file, `config.hcl`:

    bind_addr = "0.0.0.0"
    data_dir = "/var/lib/nomad"

    advertise {
      # We need to specify our host's IP because we can't
      # advertise 0.0.0.0 to other nodes in our cluster.
      rpc = "10.165.41.47:4647"
    }

    server {
      enabled = true
      bootstrap_expect = 3
      join = ["10.165.41.47","10.165.41.49", "10.165.41.51"]
    }

    client {
      enabled = false
      network_speed = 100
    }

The only line I think is wrong is the `join` command, but I can't find an HCL validator, so I gave it my best guess.

**Comment by let4be** [comment]
@funkytaco consider using retry_join and the family
see https://www.nomadproject.io/docs/agent/config.html

**Comment by funkytaco** [comment]
@let4be that seemed to work.

But can you point me to an HCL validator? There's a `nomad validate`, but it seems to only validate job syntax.

**Comment by let4be** [comment]
There is only https://github.com/hashicorp/hcl I'm aware about
There was also some 3rd-party tools to convert between yaml/json/hcl

It would be really-really nice to have online hcl validator/converter hosted somewhere on hashicorp's website ;)
@dadgar what do you think?

**Comment by funkytaco** [comment]
One more thing. Why do I get this when I enable client?

==> Error starting agent: server setup failed: Failed to start RPC layer: listen tcp 127.0.0.1:4647: bind: address already in use

**Comment by let4be** [comment]
it's a bad idea running client and server on the same node - server is typically resource hungry thing so Id suggest do the right thing from the early beginning

For example i'm running my dev nomad cluster, coexisting with consul cluster on 3 ec2 nano instances and have no problems

**Comment by dadgar** [comment]
An HCL validator could be interesting but I think it would be more useful for each command to do better validation of its own inputs. Closing this since it seems resolved? We can open if something comes up

**Comment by funkytaco** [comment]
@let4be I only have 3 bare metal servers, so I guess I'm stuck. I don't have the option of using cloud services.
