### ISSUE TITLE
Java task driver can't run from anything but root folder

### ISSUE THREAD

**Issue by rejackson73** [hashicorp/nomad#7845]
### Nomad version
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)

### Operating system and Environment details
Ubuntu 18 on AWS

### Issue
Working with the master Charlie Voiselle, we are trying to get a Minecraft demo/application running on a Nomad system using the Java driver.  What we learned is that the java application needs to be run from a directory where other files are present (in this case, eula.txt).  I'm saving eula.txt to a volume, and ideally we would run java from this volume, but currently that is not possible.  Attaching the minecraft job spec.

### Reproduction steps
simply running the attached job spec should recreate the issue

### Job file (if appropriate)
Attached

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

[minecraft.nomad.txt](https://github.com/hashicorp/nomad/files/4561353/minecraft.nomad.txt)

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Dropping the attached Nomad jobspec here to make it easier for folks to look at:

<details>

```hcl
job "minecraft" {
  datacenters = ["dc1"]
  type        = "service"

  group "minecraft" {
    volume "minecraft" {
      type   = "host"
      source = "minecraft"
    }

    // volume "efs-tests" {
    //   type      = "csi"
    //   read_only = false
    //   source    = "efs-tests"
    // }
    task "eula" {
      driver = "exec"

      volume_mount {
        volume      = "minecraft"
        destination = "/var/volume"

        // volume      = "efs-tests"
        // destination = "/csi"
        // read_only   = false
      }

      config {
        command = "mv"
        args    = ["${NOMAD_TASK_DIR}/eula.txt", "/var/volume/"]

        //   command = "mv"
        //   args    = ["local/eula.txt", "/csi/"]
      }

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      template {
        data        = "eula=true"
        destination = "local/eula.txt"
      }
    }

    task "minecraft" {
      driver = "exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "cd /var/volume && exec java -Xms1024M -Xmx2048M -jar /local/server.jar --nogui; while true; do sleep 5; done"]

        // jar_path    = "/var/volume/server.jar"
        // jvm_options = ["-Xmx1024m", "-Xms256m", "nogui"]
      }

      artifact {
        source = "https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar"

        // destination = "/var/volume/server.jar"
      }

      resources {
        cpu    = 2000
        memory = 1492
      }

      volume_mount {
        volume      = "minecraft"
        destination = "/var/volume"

        // volume      = "efs-tests"
        // destination = "/csi"
        // read_only   = false
      }
    }
  }
}
```
</details>

> What we learned is that the java application needs to be run from a directory where other files are present (in this case, eula.txt). I'm saving eula.txt to a volume, and ideally we would run java from this volume, but currently that is not possible.

So if I'm understanding correctly, the application has data in `/var/volume` and you need the `eula.txt` file to be in that same `/var/volume` directory. And the `/var/volume` directory also needs to be the working directory for the application?

I suspect there's two challenges you're running into here:
* https://github.com/hashicorp/nomad/issues/2224 there's no `workdir` configuration for `exec`, `raw_exec`, or `java` task drivers.
* https://github.com/hashicorp/nomad/issues/7796, where the volume is mounted after the template is run (this also impacts trying to run Java artifacts from volumes, as you've probably seen). We definitely see that as a bug but don't have a fix ready yet.

As a workaround for your particular case, the jobspec shows the `eula.txt` is a static text file. Could you generate this as a command in the prestart task rather than as a template?

That'd look something like this:

```hcl
job "minecraft" {
  datacenters = ["dc1"]
  type        = "service"

  group "minecraft" {
    volume "minecraft" {
      type   = "host"
      source = "minecraft"
    }

    task "eula" {
      driver = "exec"

      volume_mount {
        volume      = "minecraft"
        destination = "/var/volume"
      }

      config {
        command = "/bin/sh"
        args    = ["-c", "echo 'eula=true' > /var/volume/eula.txt"]
      }

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }
    }

    task "minecraft" {
      driver = "exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "cd /var/volume && exec java -Xms1024M -Xmx2048M -jar /local/server.jar --nogui; while true; do sleep 5; done"]
      }

      artifact {
        source = "https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar"
      }

      resources {
        cpu    = 2000
        memory = 1492
      }

      volume_mount {
        volume      = "minecraft"
        destination = "/var/volume"
      }
    }
  }
}

```

Also, I'm not sure why your Java command needs `while true; do sleep 5; done`? Does the application not foreground itself?

**Comment by angrycub** [comment]
@tgross The sleep is there to enable us to inspect the environment after the jar call fails (that should only be in an exec version we were using to test). In the case of the jar file, it seems like there are strong dependencies that they are colocated and that you run the jar from the folder where it lives. I still want to fiddle around with it a bit more, to verify all that I'd seen.  The only concrete difference was when we ran it using the exec and changed into the directory itself. 

I have a sneaking suspicion that work directories are going to become more important once we add volume mounting into the mix with more legacy jobs, but that is a hunch.

**Comment by tgross** [comment]
> I have a sneaking suspicion that work directories are going to become more important once we add volume mounting into the mix with more legacy jobs, but that is a hunch.

Agreed. The ordering bug with volumes makes it that much more obvious of a problem.

**Comment by tgross** [comment]
It looks like we identified the source bugs as #2224 and #7796, so I'm going to close this issue.
