### ISSUE TITLE
[Question] system jobs - restart only tasks that change

### ISSUE THREAD

**Issue by sparkacus** [hashicorp/nomad#7849]
I have a system job that consists of a single group and 4 tasks:
- init
- nginx
- php-fpm
- worker

The 'init' task is a pre_start lifecycle that simply spins up a container containing application (laravel) data and rsync it to the client host via a volume mount.

Once the init task completes and is dead the other tasks spin up a container that then mounts a volume from the client host containing the application data.

Each job run seems to result in all tasks within a group being restarted, even though the only tasks that change are the 'init' and 'worker' tasks e.g.:

```root@ip-10-1-89-135:/mnt/efs/fs1# nomad job plan example.nomad
+/- Job: "example-api"
+/- Task Group: "example-api" (1 create/destroy update)
  +/- Task: "init" (forces create/destroy update)
    +/- Config {
          command: "init"
      +/- image:   "example:api-257" => "example:api-258"
        }
      Task: "nginx"
      Task: "php-fpm-7.2"
  +/- Task: "worker" (forces create/destroy update)
    +/- Config {
          command: "worker"
      +/- image:   "example:api-257" => "example:api-258"
        }
```

Is there anyway I can ensure that the 'nginx' and 'php-fpm' tasks do NOT restart upon each job run?

Once the system job type supports the new update stanza options this won't really be an issue for me. I'm having to play with the job 'shutdown_delay' and update 'max_parallel/stagger' parameters to avoid downtime, but it can be problematic if pre_tasks job take a while to complete or fail thus meaning all tasks within a job are offline.

I can post a job file if required.

I must use a system job due to how I use AWS autoscaling groups. The system tasks are not bound to a static port and sits behind Traefik which makes use of Consul service discovery.

**Comment by tgross** [comment]
Hi @sparkacus!

Nomad treats the entire allocation (task group) as its unit of scheduling, so there's no way to ensure this if there's a destructive update to the job definition. So what I would recommend here is to split out the `nginx` and `php-fpm` tasks into one task group, and the `init` and `worker` tasks into their own task group.

**Comment by sparkacus** [comment]
Hi @tgross 

Thank you for clearing that up.

That's actually what I ended up doing and it works really well.

Every task in my example mounts a path from the host and because this is a system job, I can be sure that each task group within a job will coexist on the same physical host.

**Comment by tgross** [comment]
Great, glad to hear you got it working!
