### ISSUE TITLE
[question] ASP.Net workloads in IIS

### ISSUE THREAD

**Issue by tfrijsewijk** [hashicorp/nomad#7853]
Hi,

Is it possible to schedule/deploy ASP.Net workloads using Nomad? I'm talking about ASP.Net 4.x, not about ASP.Net Core.

I'm a little surprised that no one has asked/tried this before. Containerizing our applications is not an option now, with Nomad we we're hoping to first implement an orchestrator and then slowly containerize old applications.

Any suggestions are appreciated!

**Comment by tgross** [comment]
Hi @tfrijsewijk! There's a `raw_exec` driver that can run arbitrary workloads on Windows, which I know some Windows users are using.

If you specifically need a process running in the IIS context and not reverse proxied, I don't know of an IIS task driver. But I do recall recently chatting with @shishir-a412ed in https://github.com/hashicorp/nomad/issues/7786 who's working on an IIS task driver. I'm not sure if that work is open source?

**Comment by robloxrob** [comment]
We are working and close to a solution to this problem. Hopefully in a few weeks we will have some good announcements in this area. We talk about it in the Q&A portion of the recent [Virtual Nomad Day](https://www.youtube.com/watch?v=oHMQvWCAPt4).

**Comment by tfrijsewijk** [comment]
@tgross Hi! Yeah, I found the `raw_exec` driver but I find it hard to understand what the command should be. Since IIS runs as a service (one w3svc service per application pool), should the command be some sort of configuration instruction for IIS? And how does cleaning up configuration work?

@robloxrob: That would be sweet. Since running ASP.Net applications is our core business we're a bit hestitant in hacking together a solution to deploy IIS applications. What's the best way to stay on top of your release, will you be announcing it on your blog or something?

For anyone interested in what @robloxrob mentioned, I watched the whole Virtual Nomad Day recording on YouTube and here is where they started talking about the IIS task driver (It already has a name!): https://youtu.be/oHMQvWCAPt4?t=5366

**Comment by shishir-a412ed** [comment]
@tfrijsewijk I can put the link here, once we open source it.
It will be hosted under `github.com/Roblox` umbrella.

**Comment by robloxrob** [comment]
This has now been open sourced: https://github.com/Roblox/nomad-driver-iis

Thank you so much @vulfox and @shishir-a412ed 🍻

**Comment by tfrijsewijk** [comment]
This is great! Thanks for all the hard work! Can't wait to give it a go.
