### ISSUE TITLE
Failed to download artifact: Error opening a gzip reader for [...]: EOF

### ISSUE THREAD

**Issue by dradtke** [hashicorp/nomad#7854]
### Nomad version

```
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)
```

### Operating system and Environment details

openSUSE Leap 15.1 running on Linode

### Issue

I have a periodic job that uses acme.sh to renew SSL certificates, and it keeps failing due to an artifact download error.

On the surface it looks like a Github issue, but `wget https://github.com/acmesh-official/acme.sh/archive/2.8.5.tar.gz` works every time, so it appears to be more specific to how Nomad or `go-getter` is downloading it.

### Job file

Anything with this artifact block:

```hcl
artifact {
    source = "https://github.com/acmesh-official/acme.sh/archive/2.8.5.tar.gz"
}
```

### Nomad Client logs

```
Recent Events:
Time                  Type                      Description
2020-05-01T20:34:12Z  Not Restarting            Policy allows no restarts
2020-05-01T20:34:12Z  Failed Artifact Download  failed to download artifact "https://github.com/acmesh-official/acme.sh/archive/2.8.5.tar.gz": Error opening a gzip reader for /tmp/getter780748594/archive: EOF
2020-05-01T20:34:12Z  Downloading Artifacts     Client is downloading artifacts
2020-05-01T20:34:12Z  Task Setup                Building Task Directory
2020-05-01T20:34:12Z  Received                  Task received by client
```

**Comment by shoenig** [comment]
I can reproduce/fix this by switching between our vendored version of `go-getter` and master.

It seems `go-getter` made a backwards compatible change since, by removing the `Client.Umask` field so we'll need to fix that.

**Comment by dradtke** [comment]
Any idea when the incompatible version was vendored? I'm curious which Nomad version this would have first appeared in.

**Comment by dradtke** [comment]
Looks like this was introduced around version 0.10, since I had to downgrade down to 0.9.7 until this issue is fixed.

**Comment by shoenig** [comment]
Sorry about the inconvenience, @dradtke !

We've been using a fork of `go-getter` that fell behind and needed some recent updates, including a bug fix for redirect handling. The fixes should be in the next release of Nomad (0.11.3)
