### ISSUE TITLE
[enhancement] Update Java driver fingerprinting for macOS

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#7865]
On versions of macOS without Java installed, there is a stub executable that presents a warning to users that there is no longer a default JDK installed on macOS. 
<img width="532" alt="Screen Shot 2020-05-04 at 5 09 14 PM" src="https://user-images.githubusercontent.com/464492/81014200-70c5c000-8e2a-11ea-9572-182fda2e76e5.png">

 The fingerprinter runs this stub command every 30 seconds while Nomad is running because of 
https://github.com/hashicorp/nomad/blob/65f09ed11941f78db20a8ec4bbd1381dad4f83a7/drivers/java/driver.go#L29-L30
https://github.com/hashicorp/nomad/blob/65f09ed11941f78db20a8ec4bbd1381dad4f83a7/drivers/java/utils.go#L11-L27

It appears that we could fingerprint for an installed JDK (that would be seen by this stub) by looking for one or more symlinks in `/Library/Java/JavaVirtualMachines`.  This would definitely improve the getting started experience on macOS.

**Comment by vancluever** [comment]
@angrycub and I were discussing workarounds here, so I thought I'd post one here that I just applied: you can remove the `/usr/bin/java` symlink to make this go away. Not too sure if it comes back eventually though.

On modern MacOS you need to disable SIP from recovery mode and remount `/` read-write (`mount -u -w /`) before you can operate on the symlink. Of course, you can just delete it from recovery mode too.

**Comment by angrycub** [comment]
I was able to collect enough of the necessary bits to make a null.jdk that can be put in /Library/Java/JavaVirtualMachines that uses symlinks to /usr/bin/false as the target command.
Tested on macOS Catalina 10.15.4.

Unzip and then `sudo cp -R null.jdk /Library/Java/JavaVirtualMachines`

[null.jdk.zip](https://github.com/hashicorp/nomad/files/4659262/null.jdk.zip)
