### ISSUE TITLE
Should not hardcode binding with rw,z or rw,Z permisions

### ISSUE THREAD

**Issue by dmiles96** [hashicorp/nomad#788]
I need to put "alloc_dir" on an NFS mount, so I can share data between tasks (/alloc for a task group does not cut it). Since I run with SELinux on, I mount NFS using something like this:

defaults,nolock,context="system_u:object_r:svirt_sandbox_file_t:s0"

If I then run docker via the CLI and pass in a path rooted at the nfs mount, with rw permissions, it works. But, if I set "alloc_dir", in the node configuration, to a path rooted at the nfs mount, it fails. I'm not an SELinux master, but I don't think re-labeling (using rw,z/rw,Z) is allowed with an nfs mount. The mount needs to be created with the context set (which I do in fstab, using the snippet I mentioned above). So, hardcoding a z or Z won't work in all scenarios. At the least, that needs to be an option people can turn off and on.

**Comment by diptanu** [comment]
I think we want this to be configurable, since this can vary based on the use cases and environments. We will try to get this in for 0.4

**Comment by diptanu** [comment]
@dmiles96  This was made tunable via adding the `docker.volumes.selinuxlabel` in Nomad client config in the 0.4 release. Closing this, please re-open if that didn't solve your use case.
