### ISSUE TITLE
[question] Public IP in template

### ISSUE THREAD

**Issue by cgthayer** [hashicorp/nomad#7888]
There doesn't seem to be a way to get the public IP for the machine my task is running on, so I'm using a $HOST_IP_fakeport hack which I parse to use in my docker  :-(

Is there a better way?

**Comment by tgross** [comment]
There isn't a portable way to do this in a general sense, as the host could be behind NAT or in a SDN environment where the IP isn't visible anywhere on the host (ex. AWS). However, if you take a look at `nomad node -verbose :node_id`, you'll find there's a bunch of metadata that we've fingerprinted and depending on your specific environment the IP address may be included.

You'd then use that as an [interpolated variable](https://www.nomadproject.io/docs/runtime/interpolation/) like `${attr.unique.network.ip-address}` in your jobspec. For most of the cloud providers we can fingerprint the "real" public IP and get that in a provider-specific variable there as well.

**Comment by cgthayer** [comment]
Thanks @tgross 

We've been using the `${attr.unique.network.ip-address}` approach and it's been working well for our needs since we have our own on-prem / d.c.

It feels like there should be an on-node private network so that anything can more easily and directly communicate with the system jobs, but I don't know enough nomad yet to understand all the pros and cons. (I'm thinking iptables)
