### ISSUE TITLE
Improve volume_mount doc

### ISSUE THREAD

**Issue by rberlind** [hashicorp/nomad#7899]
### Issue
The Nomad volume_mount doc at https://nomadproject.io/docs/job-specification/volume_mount/#destination has this: "Specifies where the volume should be mounted inside the tasks container."

I see two issues with this:
"tasks" should obviously be "task's".
I also think "container" should be "allocation".

My reason for the second is that using host volumes is not limited to the Docker task driver, so referring to a "container' seems overly restrictive and potentially confusing.

**Comment by tgross** [comment]
Opened https://github.com/hashicorp/nomad/pull/7900 Hey @rberlind for future reference the docs are all in the `./website/pages/docs` directory and very much welcome PRs!

**Comment by rberlind** [comment]
Thanks @tgross
