### ISSUE TITLE
Consul Connect doesn't work with IPv6

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#7905]
### Nomad version
Nomad v0.10.5 (4eb2ca3f8d8786c897bb47878f1c12577011ddd3)

### Operating system and Environment details
CentOS 7.8
CNI plugins v0.8.4

### Issue
Nomad doesn't add ip6tables rules in case of using CNI plugins and Consul Connect, so forwarding works only for IPv4

### Reproduction steps
- Follow this guide: https://www.nomadproject.io/docs/integrations/consul-connect/
- Check ip6tables rules

**Comment by karelorigin** [comment]
I seem to be suffering from the exact same issue: https://discuss.hashicorp.com/t/no-assigned-ipv6-address-for-docker-containers-nomad-consul-connect/41391

**Comment by tgross** [comment]
Looks like this fell of the issue board. Re-marked for roadmapping.
