### ISSUE TITLE
Impossible to give a consul token to envoy sidecar

### ISSUE THREAD

**Issue by saez0pub** [hashicorp/nomad#7917]
### Nomad version
nomad version
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)

### Operating system and Environment details
Linux

### Issue
I have activated acls on my consul.
I have given a consul token to the consul agent on nomad with enough right to register services
I can't use the sidecar proxies because I don't have any option to setup a consul token.
I tried to redo the Nomad Consul Connect Example with just acl enabled. It gives me the same error in envoy : 
[2020-05-11 13:43:31.222][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 7, permission denied
and in consul :
[DEBUG] agent.envoy: Error handling ADS stream: error="rpc error: code = PermissionDenied desc = permission denied"

### Reproduction steps
I used this page to make sure I have something working "usually"  : https://www.nomadproject.io/docs/integrations/consul-connect/#nomad-consul-connect-example

The modifcation is intention allow all and acl activation

consul configuration :
```
cat << EOF > consul.hcl
acl = {
  enabled        = true
  default_policy = "deny"
}
ports {
  grpc = 8502
}

connect {
  enabled = true
}
EOF
```
consul startup :
```
consul agent -dev -config-file consul.hcl
consul acl bootstrap | tee token
export CONSUL_HTTP_TOKEN=$(grep SecretID: token | sed -e 's/.* //')
consul acl  set-agent-token default $CONSUL_HTTP_TOKEN
consul intention create "*" "*"
```

nomad startup :
```
export CONSUL_HTTP_TOKEN=$(grep SecretID: token | sed -e 's/.* //')
sudo nomad agent -dev-connect
```

nomad job : 
```
cat << EOF > connect.nomad
job "countdash" {
  datacenters = ["dc1"]

  group "api" {
    network {
      mode = "bridge"
    }

    service {
      name = "count-api"
      port = "9001"

      connect {
        sidecar_service {}
      }
    }

    task "web" {
      driver = "docker"

      config {
        image = "hashicorpnomad/counter-api:v1"
      }
    }
  }

  group "dashboard" {
    network {
      mode = "bridge"

      port "http" {
        static = 9002
        to     = 9002
      }
    }

    service {
      name = "count-dashboard"
      port = "9002"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "count-api"
              local_bind_port  = 8080
            }
          }
        }
      }
    }

    task "dashboard" {
      driver = "docker"

      env {
        COUNTING_SERVICE_URL = "http://${NOMAD_UPSTREAM_ADDR_count_api}"
      }

      config {
        image = "hashicorpnomad/counter-dashboard:v1"
      }
    }
  }
}
EOF

```
start your nomad job and see you have permission problems
http://127.0.0.01:9002 is not working

You have no configuration option in nomad sidecar task allowing a template to generate a consul token.

**Comment by shoenig** [comment]
Hi @saez0pub, have you read through the [Secure Nomad Jobs with Connect](https://learn.hashicorp.com/nomad/consul-integration/nomad-connect-acl) guide? 

There's a few things that need to be configured before Connect with ACLs will work. The Nomad Server will automatically generate Service Identity tokens on behalf of the Nomad Client which then injects the token into the sidecar process.

Feel free to re-open this once you have properly configured Nomad Server and Nomad Client, and still experience problems.

**Comment by saez0pub** [comment]
Hello,

Did you see that I added the consul Root token to the agent as default authentication in my exemple ?
The documentation on the consul token parameter : 
> token (string: "") - Specifies the token used to provide a per-request ACL token. This option overrides the Consul Agent's default token. If the token is not set here or on the Consul agent, it will default to Consul's anonymous policy, which may or may not allow writes.
Si Nomad would have all the necessary rights as hé is uising an unrestricted token.

From what I Can see I haven't disabled unauthenticated job submission, I can't see in documentation the link with my problem.
I will try today but you can already reopen this issue.

**Comment by saez0pub** [comment]
Ok, I see what's missing.
I need to write to disk my token, in memory configuration is not enough.
As I have immutable system disks, I have to pass with a parameter to nomad (-consul-token=xxxx).
https://www.nomadproject.io/docs/configuration/consul/#token is wrong
Nomad does not generate consul token for sidecars unless you specify explicitly a consul token.
Please update the documentation.
