### ISSUE TITLE
Job accessing CSI fails when ACL enabled

### ISSUE THREAD

**Issue by vincenthuynh** [hashicorp/nomad#7927]
### Nomad version
0.11.1

### Operating system and Environment details
Debian 9

### Reproduction steps
- Enable ACLs with the following Anonymous policy:
```
namespace "*" {
  policy       = "write"
  capabilities = ["alloc-node-exec", "csi-register-plugin", "csi-list-volume", "csi-read-volume"]
}

agent {
  policy = "write"
}

operator {
  policy = "write"
}

quota {
  policy = "write"
}

node {
  policy = "write"
}

host_volume "*" {
  policy = "write"
}
```
- Follow [CSI guide](https://learn.hashicorp.com/nomad/stateful-workloads/csi-volumes)

### Job file (if appropriate)
My setup is outlined [here](https://discuss.hashicorp.com/t/gce-persistent-disk-csi-csi-hook-failed-claim-volumes-rpc-error-permission-denied/8419)

### Nomad Client logs (if appropriate)
```
May  5 21:04:19 nmd-rpzq nomad[19194]:     2020-05-05T21:04:19.041Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: Permission denied" rpc=CSIVolume.Claim server=<nomad_server_ip>:4647
May  5 21:04:19 nmd-rpzq nomad[19194]:     2020-05-05T21:04:19.041Z [ERROR] client.alloc_runner: prerun failed: alloc_id=d1ece247-eb45-1a71-f4b0-424db8701926 error="pre-run hook "csi_hook" failed: claim volumes:
rpc error: Permission denied"
```

**Comment by tgross** [comment]
Thanks for opening this issue @vincenthuynh. We'll investigate!

**Comment by vrenjith** [comment]
+1

**Comment by tgross** [comment]
Hi @vincenthuynh and @vrenjith! I took a look at this and I think the policy is missing the ability to read plugins. If you try running `nomad plugin status` you should see an error as well. Add the following to your policy doc:

```
plugin {
  policy = "read"
}
```

I've tested this out and was able to register volume and claim it for a job. Let me know if that works for you, and if so I'll see what I can do to make the documentation more clear.

**Comment by vincenthuynh** [comment]
Hi @tgross,
The `plugin` rule worked! Thanks for the help!

**Comment by tgross** [comment]
Glad to hear!

**Comment by tgross** [comment]
I've also got the appropriate section added to the Learn guide on ACLs: https://learn.hashicorp.com/nomad/acls/policies#plugin-rules
