### ISSUE TITLE
CSI: Add ControllerJob and NodeJob to the Plugin API response

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hashicorp/nomad#7974]
It would be nice to be able to link from a CSI plugin to the jobs that power the plugin.

This is technically currently possible by doing the following:

1. Request a plugin
2. Request an allocation from the map of CSIInfo objects
3. Request the job the allocation is running on behalf of

If the plugin response also had this job information (JobID, JobNamespace, JobVersion) then we can save a step.

I'm imagining six new properties on the Plugin, but since some of these may only be applicable for CSI Plugins, I don't think I'm the best judge on API design.

```json
{
  "ID": "example",
  "Provider": "megacloud",
  "ControllerJobID": "example-controller",
  "ControllerJobNamespace": "top-secret-ops-stuff",
  "ControllerJobVersion": 1,
  "NodeJobID": "example-node",
  "NodeJobNamespace": "top-secret-ops-stuff",
  "NodeJobVersion": 2,
}
```

**Comment by DingoEatingFuzz** [comment]
The UI would use this for #7969

**Comment by tgross** [comment]
There's one hiccup with this: more than one job and version can define a node plugin or controller plugin. It definitely seems like a weird case, but there are a couple of examples where you might see this:

* You want to validate that a new version of a plugin provider works. You might run a `controller-v1` and a `controller-v2` job side-by-side.
* You're running plugins in multiple DCs, and want to deploy each plugin/DC pair as its own job to reduce your deployment blast radius.

**Comment by tgross** [comment]
It occurs to me that this is a problem with the existing API as well and frankly with the data model we have; we define plugins by fingerprinting the jobs so that updates to jobs update the plugin definition as well. So maybe my concern isn't a problem we need to worry about.

**Comment by langmartin** [comment]
This doesn't actually turn out to help the UI reduce the number of queries, so the API change is omitted.
