### ISSUE TITLE
Cannot set Docker labels for sidecar tasks

### ISSUE THREAD

**Issue by akhayyat** [hashicorp/nomad#7991]
### Nomad version
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)

### Operating system and Environment details
Debian 10.3

### Issue
Setting Docker labels for `sidecar_task` has no effect. The envoy sidecar containers do not have the configured labels. Docker labels work fine on normal tasks.

### Reproduction steps
Run a Docker job with some Docker labels defined under `service.connect.sidecar_task.config.labels`. See below for an example.

### Job file (if appropriate)
```hcl
job "echo" {
  datacenters = ["test"]
  group "echo" {
    network {
      mode = "bridge"
      port "http" {
        static = 8080
        to = 8080
      }
    }
    service {
      name = "echo"
      port = 8080
      connect {
        sidecar_service {}
        sidecar_task {
          config {
            labels {
              nomad_job = "${NOMAD_JOB_NAME}"
              nomad_group = "${NOMAD_GROUP_NAME}"
            }
          }
        }
      }
    }
    task "echo" {
      user = 65534
      driver = "docker"
      config {
        image = "hashicorp/http-echo"
        args = [
          "-listen",
          ":8080",
          "-text",
          "hello world"
        ]
      }
      resources {
        memory = 10
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
Nothing special.

**Comment by akhayyat** [comment]
So, after a while (hours), labels started to show up in the output of `docker inspect`!

Now, when I changed the labels, stopped the job, then ran it again, I still kept seeing the old labels.

Are the sidecar task custom labels cached, perhaps?

**Comment by shoenig** [comment]
Thanks for reporting @akhayyat ! At first guess, I suspect we're not properly identifying when the opaque `sidecar_task.config` block is being modified, which should trigger a destructive update for the allocation.

**Comment by tgross** [comment]
@shoenig should this issue have been closed by https://github.com/hashicorp/nomad/pull/9029 ?
