### ISSUE TITLE
Documentation misses commands (rendering issue)

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#7996]
When I go to https://www.nomadproject.io/docs/integrations/consul-connect/#consul I see a black box:
![Screenshot_2020-05-18 Consul Connect Nomad by HashiCorp](https://user-images.githubusercontent.com/81547/82192287-129de000-98f4-11ea-86c3-8f0e3dc3979f.png)

I have checked the source code:
```
<code class="language-shell-sessionconsul" metastring="agent -dev"></code>
```
and it indeed seems to miss the actual "<span>" to display.

**Comment by angrycub** [comment]
Thanks for the report! There was a find-and replace issue that caused this - fixed in https://github.com/hashicorp/nomad/pull/8005.  Please let us know if you see any text areas still exhibiting this issue.
