### ISSUE TITLE
drain not working correctly (vagrant getting started test setup)

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#800]
I followed the getting started intro using the vagrant setup (which all worked as expected) and then wanted to try the drain facility to see how a node is removed and what happens to task groups so I tried the `nomad node-drain -enable <node id>` and could see with `nomad node-status` that the command was successful. However, only 1 of the 2 docker containers was stopped and restarted on the other node. When I repeated the `node-drain -enable` command the second docker container then moved over to the other node.

I realise that this is quite an artificial environment with server and 2 agents running on one server and both agents sharing a docker daemon so is this a quirk of the environment or is this buggy behaviour?

**Comment by dadgar** [comment]
Hey this was fixed and will be in the 0.3 binary. You can download the RC to test this. I will close this unless it is not working in the release candidate.

**Comment by far-blue** [comment]
I've tested the same scenario with v0.3.0-rc1 and it appears to behave correctly :) Thanks for letting me know :)
