### ISSUE TITLE
[bug] CSI volume endpoint returns 200 OK when payload is nonsensical

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#8026]
### Nomad version
Master commit `06f0f3a41563ac2cc557d8e68546ad6003b121ca`

### Operating system and Environment details
Reproduced on MacOS

### Issue
It is possible for an operator to submit a register request to the CSI volume endpoint with a payload that is invalid and receive a 200 OK response. The register request successfully makes its ways via RPC and into raft. It misses any of Nomad's [internal validation checks](https://github.com/hashicorp/nomad/blob/06f0f3a41563ac2cc557d8e68546ad6003b121ca/nomad/csi_endpoint.go#L273-L282) because the `args.Volumes` field is nil.

I believe inline with what I have seen in other agent endpoints, the decoded object should go through some basic validation before sending via RPC. Different endpoints approach validation in different ways:
 * the operator endpoint uses a [Validate](https://github.com/hashicorp/nomad/blob/06f0f3a41563ac2cc557d8e68546ad6003b121ca/command/agent/operator_endpoint.go#L264) function
 * the job endpoint performs [inline validation](https://github.com/hashicorp/nomad/blob/06f0f3a41563ac2cc557d8e68546ad6003b121ca/command/agent/job_endpoint.go#L387-L396)

### Reproduction steps
 * run Nomad in dev mode: `nomad agent -dev`
 * using the payload below perform an API request: `curl -v --request PUT --data @payload.json http://localhost:4646/v1/volume/csi/helloworld`
* perform the curl request again and notice the `X-Nomad-Index` header integer has been incremented 

example payload:
```
{"Foo": "bar"}
```

### Nomad logs
I added a test log message to display the output of the [rafApply](https://github.com/hashicorp/nomad/blob/06f0f3a41563ac2cc557d8e68546ad6003b121ca/nomad/csi_endpoint.go#L287) function call which also shows the raft index being update on subsequent calls as detailed in the reproduction steps.

```
2020-05-20T11:50:58.625+0200 [DEBUG] nomad.csi_volume: ---------------------->: resp=<nil> index=10
2020-05-20T11:51:03.179+0200 [DEBUG] nomad.csi_volume: ---------------------->: resp=<nil> index=11
```

**Comment by tgross** [comment]
Thanks for reporting this, @jrasell. Easy enough to fix, but we should take a pass through the other endpoints to make sure we haven't dropped the ball on this elsewhere.

**Comment by jrasell** [comment]
Agreed @tgross and I have it on my list to do a quick pass when I have some more available time.
