### ISSUE TITLE
Problem in addresses configuration

### ISSUE THREAD

**Issue by LordFPL** [hashicorp/nomad#804]
Hello,

I'm trying to start nomad 0.3rc1 and my 0.2.3 config don't work : 
```
addresses { http = "127.0.0.1" }
```
I get a : 
```
Error starting agent: error resolving http addr: missing port in address 127.0.0.1:
```

And when i try to specify : 
```
addresses { http = "127.0.0.1:4646" }
```
I get : 
```
Error starting http server: failed to start HTTP listener: listen tcp: too many colons in address 127.0.0.1:4646:4646
```

Why colons are added ?

**Comment by diptanu** [comment]
@LordFPL Sorry for the regression, the fix is landing into master soon and will be part of the final 0.3 release.

**Comment by LordFPL** [comment]
Thx for this speedy fix :)
