### ISSUE TITLE
Nomad Connect Service Stanza Registers Tags For Proxy

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#8050]
### Nomad version
nomad 0.11.2

### Operating system and Environment details
Photon OS3

### Issue
When specifying a service stanza with tags, those tags are applied to the auto generated proxy and also the actual service itself.   This creates issues with fabio routing tables.   The desired result would be for the tags to only register to the actual service, not the envoy proxy

### Job file (if appropriate)
job "api-proxy" {
    datacenters = ["proxy-cluster"]
    type = "service"

    group "api-proxy" {
        count = 1
        
        network {
            mode = "bridge"
            port "http" {
                to = 9090
                static = 20345
            }
        }
        service {
            name = "api-proxy"
            port = "9090"
            tags = [ "http", "urlprefix-/" ]
            connect {
                sidecar_service {
                    proxy {
                        upstreams {
                            destination_name = "database-proxy" # This has to be the service-resolver name registered for the virtual service
                            local_bind_port = 25432
                        }
                    }
                }
            }
        }

        task "api-proxy" {
            driver = "docker"
            config {
                image = "nicholasjackson/fake-service:v0.9.0"
            }
            env {
                NAME = "api"
                MESSAGE = "ok"
                LISTEN_ADDR = "0.0.0.0:9090"
                UPSTREAM_URIS = "http://localhost:25432"
                TIMING_VARIANCE = "25"
                HTTP_CLIENT_KEEP_ALIVES = "true"
            }
            resources {
                cpu    = 100
                memory = 256
            }
        }
    }
}

Consul shows registration:
<img width="1072" alt="Screen Shot 2020-05-26 at 12 29 01 PM" src="https://user-images.githubusercontent.com/46198537/82926185-d0f0e300-9f4c-11ea-970c-7d7bccb1aab1.png">

And Fabio is this confused as to the routing
<img width="1162" alt="Screen Shot 2020-05-26 at 12 31 42 PM" src="https://user-images.githubusercontent.com/46198537/82926236-e108c280-9f4c-11ea-9391-dd212088295d.png">

**Comment by shoenig** [comment]
@idrennanvmware this is actually a behavior [coming from Consul](https://www.consul.io/docs/connect/registration/sidecar-service.html#tags) itself. 
> Defaults to the tags of the parent service

To workaround that, you can specify custom tags for the Connect `sidecar_service` in the Nomad connect config (i.e. `tags` just cannot be empty)
https://www.nomadproject.io/docs/job-specification/sidecar_service/#tags

**Comment by idrennanvmware** [comment]
Oh awesome - thank you @shoenig !
