### ISSUE TITLE
Option to spread jobs such as to keep node utilization to minimum 

### ISSUE THREAD

**Issue by israellot** [hashicorp/nomad#8110]
Migrating from Service Fabric to Nomad I've found a very different approach on job placement. 
On Service Fabric nodes are monitored and the orchestrator tries to balance jobs in such a way that nodes have a similar load in terms of CPU, RAM or any other metric the user chooses to monitor. 
Nomad will bin pack jobs, saturating nodes and leaving other nodes idle. The new spread stanza helps by allowing me to spread a job across different nodes, but there's no mechanism that works on a node level. 
I would like to ensure my nodes are balanced in terms of load, and currently that's very hard to do with nomad, specially when running a variety of jobs that have dynamic load. On a particular period of the day one job might be more cpu hot making a particular node short on cpu. Nomad could relocate other jobs on that node to less saturated ones to even the pressure.

**Comment by notnoop** [comment]
Thanks for reaching out.  Nomad 0.11.2 introduced a scheduling algorithm config to control whether a cluster binpacks or spreads allocations.  The flag operates on the region level and is cluster-wide.  You can use the [Update Scheduler Configuration api](https://www.nomadproject.io/api-docs/operator/#update-scheduler-configuration) to set it.  Hope that serves your needs!  Let us know of any feedback!

**Comment by israellot** [comment]
Thank you for the info, very helpful. But it doesn't solve a crucial problem :
When I add new nodes to the cluster, nomad does not rebalance jobs and those nodes stay idle unless I post job updates that force reevaluation. I would expect nomad to migrate allocations on such scenario.
