### ISSUE TITLE
Question: Output from Heathchecks not displayed in Consul (bug?)

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#8112]
Output from `nomad version`
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)

### Operating system and Environment details
PhotonOS3

### Issue
When registering health checks for a docker container (that has an internal script) the output is not displayed in Consul.

Using Vault as an example, the way the status of the healthcheck is returned is very helpful.   We do not see the same behavior when using healthchecks in a docker container.

check {
          type     = "script"
          name     = "Zookeeper Health Check"
          command  = "bin/bash"
          args     = ["local/zookeeper_health_check.sh"]
          interval = "15s"
          timeout  = "15s"
        }

returns blank output (see screenshot1, unlike what we would want or expect with screenshot 2)

is this a bug?
Actual
<img width="972" alt="screenshot1" src="https://user-images.githubusercontent.com/46198537/83764668-35e0c300-a648-11ea-9737-6eff7b0c681a.png">

Example of what we would expect 
<img width="1260" alt="screenshot2" src="https://user-images.githubusercontent.com/46198537/83764680-38dbb380-a648-11ea-9e82-5d6144fa702c.png">

**Comment by shoenig** [comment]
So if I create little example, 
```hcl
$ cat scriptcheck.nomad 
job "scriptcheck" {
  datacenters = ["dc1"]

  group "alpine" {
    task "alpine" {
      driver = "docker"

      service {
	check {
	  type = "script"
	  name = "script.sh"
	  command = "/bin/sh"
	  args = ["-c", "local/script.sh"]
	  interval = "5s"
	  timeout = "1s"
	}
      }

      config {
	image = "alpine"
	command = "/bin/sleep"
	args = ["10000"]
      }

      template {
  data = <<EOH
  echo "hello!"
  exit 0
  EOH

  destination = "local/script.sh"
}
      
    }
  }
}
```

We can see the output is gathered by Consul, and is available from the Agent API.

```
$ curl -s localhost:8500/v1/agent/checks | jq '.[] | select(.Name=="script.sh")'
{
  "Node": "nzxt",
  "CheckID": "_nomad-check-96863d91d585b507bb0d83462cda2d420f919460",
  "Name": "script.sh",
  "Status": "passing",
  "Notes": "",
  "Output": "hello!\n",
  "ServiceID": "_nomad-task-5be9aae7-d927-a4a1-5994-4592f7bf8f42-alpine-scriptcheck-alpine-alpine-",
  "ServiceName": "scriptcheck-alpine-alpine",
  "ServiceTags": [],
  "Type": "ttl",
  "Definition": {},
  "CreateIndex": 0,
  "ModifyIndex": 0
}
```
However, the Consul UI doesn't contain the output for me, either. 

I don't know if this is a bug or a feature, but it seems like a Consul issue, @idrennanvmware

**Comment by shoenig** [comment]
I believe this was fixed on the Consul side, in https://github.com/hashicorp/consul/issues/8161
