### ISSUE TITLE
After removing aws-ebs0 from the cluster deleting nodes fails

### ISSUE THREAD

**Issue by analytically** [hashicorp/nomad#8121]
### Nomad version
Nomad v0.11.2 (807cfebe90d56f9e5beec3e72936ebe86acc8ce3)

### Operating system and Environment details
Amazon Linux 2, c5.4xlarge

### Issue
After removing the aws-ebs0 plugin from our cluster, we're seeing the client list with ineligble nodes grow unbounded without removing nodes.

The logs have:
`nomad.fsm: DeleteNode failed: error="csi plugin delete failed: csi_plugins missing pl
ugin aws-ebs0"`

**Comment by analytically** [comment]
Similar to https://github.com/hashicorp/nomad/issues/8100

**Comment by tgross** [comment]
Hi @analytically can you clarify for me the symptom you're seeing here:

> the client list with ineligble nodes grow unbounded without removing nodes.

Nomad nodes are being marked as [ineligible](https://www.nomadproject.io/docs/commands/node/eligibility/) for placing workloads? Or do you mean you can't schedule CSI workloads on those nodes?

> Similar to #8100

That issue is about volume claim GC, which should be unrelated.

**Comment by analytically** [comment]
No this is also the volume claim GC (Nomad Nodes GC)

**Comment by tgross** [comment]
There's a difference between "volume claim GC" (which is the cleanup of claims that an allocation has on a volume) and a "node GC" (which is the cleanup of Nomad clients). 

I'm still not clear what the symptom you're seeing it: Nomad nodes are being marked as ineligible for placing workloads? Or do you mean you can't schedule CSI workloads on those nodes?

**Comment by tgross** [comment]
Some follow-up data which isn't quite the same thing but could be related. If we try to delete a job that hasn't registered its plugin, that results in the following error state:

```
2020-07-29T14:54:24.417Z [ERROR] nomad.fsm: DeleteJob failed: error="deleting job from plugin: plugin missing: aws-ebs0 <nil>"
2020-07-29T14:54:24.417Z [ERROR] nomad.fsm: deregistering job failed: error="deleting job from plugin: plugin missing: aws-ebs0 <nil>"

**Comment by tgross** [comment]
Should be fixed with https://github.com/hashicorp/nomad/pull/8619
