### ISSUE TITLE
Excplicitly set archive to true

### ISSUE THREAD

**Issue by neidiom** [hashicorp/nomad#8129]
My logic tells me if disabling automatic unarchiving, by setting the archive option to false:

````
artifact {
  source = "https://example.com/file.tar.gz"
  options {
    archive = false
  }
}
````

Then this should work

````
artifact {
  source = "https://example.com/file.tar.gz"
  options {
    archive = true
  }
}
````

but it does not.

**Comment by shoenig** [comment]
Thanks for reporting, @neidiom !

This is kind of a weak spot in our documentation. The `options` stanza merely defers to the implementation of [go-getter](https://github.com/hashicorp/go-getter#unarchiving) - which does not provide such `archive = true` functionality. If this feature were to be added to Nomad, it would have to be implemented upstream first.

OTOH, given that `go-getter` will by default automatically unarchive any archive it is capable of unarchiving, I'm not sure there's much utility in having a force option - which would likely just result in an error or corruption.
