### ISSUE TITLE
[Question] What's the best practice/possible way of using encrypted image

### ISSUE THREAD

**Issue by johnzhanghua** [hashicorp/nomad#8132]
A question of using the docker driver but with an encrypted image format. 

```
artifact {
  source = "http://path.to/redis.tar"
}
config {
  load = "redis.tar"
  image = "redis"
}
```

What is the best practice (or even possible) to make the `redis.tar` as encrypted format, but insert a `plugin` for decryption step between the `artifact` and `config` stanza .

**Comment by tgross** [comment]
@johnzhanghua as far as I know this isn't directly supported by Docker, so you'd need to decrypt the artifact before passing it as a tarball to Docker. One way you might be able to do this is to have a pre-start task that downloads and decrypts an artifact as a [prestart hook](https://www.nomadproject.io/docs/job-specification/lifecycle/#hook) into the allocation directory, and then load that tarball in the main task.

**Comment by johnzhanghua** [comment]
Thank you @tgross . Will try that.
