### ISSUE TITLE
Allow manually specifying IP address for service

### ISSUE THREAD

**Issue by Legogris** [hashicorp/nomad#8140]
We're provisioning Traefik as a Docker job with host networking, binding the proxy to a public VRRP IP and the management IP to a private VRRP, on separate interfaces.

This works all good, but the services registered in Consul get assigned to the Nomad IP, which makes service checks fail.

I see that this may be covered by the solution to #646 , but I think this is a common use-case that can have a simpler solution not requiring changes to the `client` config, by simply allowing specification of the IP address to use in the `service`or `check` stanza with an added `address` field.

**Comment by dradtke** [comment]
I've run into this issue too, but in a different way. My cluster is configured to bind to and advertise IPv6 addresses for both Nomad and Consul, but Nomad always picks the public IPv4 address when registering a service using the `exec` driver. The discrepancy can be seen pretty easily in the service details:

```json
"Address": "2600:3c04::f03c:92ff:fecc:a637",           
"TaggedAddresses": {
  "lan": "2600:3c04::f03c:92ff:fecc:a637",
  "lan_ipv6": "2600:3c04::f03c:92ff:fecc:a637",
  "wan": "2600:3c04::f03c:92ff:fecc:a637",
  "wan_ipv6": "2600:3c04::f03c:92ff:fecc:a637"
},
"ServiceAddress": "172.105.110.245",
"ServiceTaggedAddresses": {
  "lan_ipv4": {
    "Address": "172.105.110.245",
    "Port": 23037
  },
  "wan_ipv4": {
    "Address": "172.105.110.245",
    "Port": 23037
  }
}
```

The address is correctly using the advertised IPv6 address, but the service address is still picking the IPv4 address, which in this case is causing Fabio to route requests to the wrong address.

**Comment by shoenig** [comment]
Implemented in https://github.com/hashicorp/nomad/pull/12720
