### ISSUE TITLE
[question] Number of allocations per job at or near evaluation time

### ISSUE THREAD

**Issue by mishel170** [hashicorp/nomad#8146]
Hi,
Using the java API I'm trying to get the expected allocation count in order to get the number of agents the job will run on, and I can't find a solution. 

I don't have any indication when all the allocations have been placed so when I list job-specific allocations and count them it can give me numbers lower than the actual count or even 0(I assume this is because the allocations don't have enough time to be created so I query them too early)

I would appreciate it if you help me figure it out :)
Best regards,
Mishel Liberman

**Comment by mikenomitch** [comment]
Hi @mishel170, I was going through some old issues and found this one. I'm not sure if there's anything really actionable on our end regarding changes to the application code itself, and given how old this is, I'm hoping you've found a workaround in the meantime (perhaps just waiting for the allocs to be placed worked?).

I'll close this out just to reduce total Issue noise.

If you've identified any specific related fixes or bugs, please let me know and we can open this back up.
