### ISSUE TITLE
Support `PreserveCounts` in job registration API

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#8158]
As part of the scaling API work, we planned to add a ~query parameter~ payload parameter, `PreserveCounts: bool = false`, to job registration, indicating that existing task group counts should be preserved, taken precedence over any counts included in the job spec in the update payload. This allows, e.g., CD scripts to more easily update job definition without conflicting with changes to made to the count by an autoscaler.

**Comment by jippi** [comment]
Huge +1 on this - it's an annoying repetitive thing we repeat a lot in our SeatGeek tooling as well
