### ISSUE TITLE
WSL2 Docker volumes not mounted 

### ISSUE THREAD

**Issue by ad-on-is** [hashicorp/nomad#8160]
I'm using Docker for Windows with WSL2 backend. Docker and docker-compose work fine inside WSL2.

So I wanted to try out nomad and followed this tutorial: https://learn.hashicorp.com/nomad/load-balancing/nginx. 

## My problem
The problem is, that load-balancer.conf is not mounted into the container.

I'm running nomad with `nomad agent -dev` locally to test things out.

## What's happening
When I run the example as described, `/etc/nginx/conf.d` is empty. When I use absolute path instead, the job keeps in status pending and then gets cancelled.

## What I've tried so far:

Omitting the `template{}` section completely and putting the config inside `/absolute/path/to/local/load-balancer.conf`

Different variants of `volumes[]`

```
volumes = [
    "local:/etc/nginx/conf.d",
]
```
```
volumes = [
    "/absolute/path/to/local:/etc/nginx/conf.d",
]
```

How can I mount a local folder with nomad into a a container like I do with `docker -v` or `docker-compose volumes`?

**Comment by shoenig** [comment]
Hi @ad-on-is, thanks for reporting! 

If you want to mount something from the node's local file system, this should just be a matter of configuring the Nomad Client with the [host_volume](https://www.nomadproject.io/docs/configuration/client/#host_volume-stanza) stanza necessary to give Jobs access. Then in your jobspec you'll set the [volume_mount](https://www.nomadproject.io/docs/job-specification/volume_mount/) in the task group, and the [volume](https://www.nomadproject.io/docs/job-specification/volume/) in the task.
