### ISSUE TITLE
Stop button in Nomad UI does not stop the job in the selected cluster region

### ISSUE THREAD

**Issue by pirogoeth** [hashicorp/nomad#8195]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)

### Operating system and Environment details
Ubuntu 16.04.6 LTS on AWS
Nomad clusters federated between three AWS regions, `us-east-1`, `us-west-2`, `eu-central-1`

### Issue
When connected to the Nomad UI with a cluster that is not the selected cluster, stopping a job in the selected cluster stops the job in the cluster local to the UI you are accessing instead.

Request targets the Nomad API local to the UI region without setting the `region` query param.

![image](https://user-images.githubusercontent.com/472488/84962140-9d414d00-b0f5-11ea-88b2-18556302d6e9.png)

### Reproduction steps
1. Access the Nomad UI from a datacenter endpoint (ie., `http://nomad.us-east-1/ui/`)
2. Change the region selector to a remote region (ie., `eu-central-1`)
3. Pick a job out of the list of running jobs
4. Click the stop button and confirm

Now the job will be stopped in `us-east-1` but _not_ `eu-central-1`.

### Job file (if appropriate)
Stupid-simple job to test with. Deployed to each region.
```
job "sleeper" {
  datacenters = ["dc1"]
  type        = "system"
  priority    = 75

  group "app" {
    task "sleeper" {
      driver = "docker"

      config {
        image      = "alpine:latest"
        force_pull = true

        command = "/bin/sleep"

        args = [
          "3600",
        ]
      }

      resources {
        cpu    = 64
        memory = 64
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by m1keil** [comment]
We are hitting this in 0.10.2 as well.

**Comment by tgross** [comment]
This won't be backported to 0.10.2, sorry.
