### ISSUE TITLE
Confusing documentation examples regarding helpers

### ISSUE THREAD

**Issue by neidiom** [hashicorp/nomad#8196]
https://www.nomadproject.io/docs/drivers/docker/

First example is
````
plugin "docker" {
  config {
    endpoint = "unix:///var/run/docker.sock"

    auth {
      config = "/etc/docker-auth.json"
      helper = "docker-credential-aws"
    }
}
````

where docker-credential-aws is used

then we go to

````
The script's name must begin with docker-credential- and this option should include only the basename of the script, not the path.
````

where it states that it has to start with docker-credential- keywords

then we go to

````
client {
  enabled = true
}

plugin "docker" {
  config {
    auth {
      # Nomad will prepend "docker-credential-" to the helper value and call
      # that script name.
      helper = "ecr"
    }
  }
}
```` 

where it says that  Nomad will prepend "docker-credential-" to the helper value.

Am I missing something?

**Comment by shoenig** [comment]
Thanks for reporting, @neidiom !

I believe the first example is a documentation bug. Looks like the driver [always prepends](https://github.com/hashicorp/nomad/blob/v0.11.3/drivers/docker/utils.go#L148) the `docker-credential-` prefix.

Would you like to open a quick PR to fix that first example?

**Comment by tgross** [comment]
Possibly related: https://github.com/hashicorp/nomad/issues/7357

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/8913 and https://github.com/hashicorp/nomad/pull/7801
