### ISSUE TITLE
Unsupported restart mode and Missing Log Config (3rc1)

### ISSUE THREAD

**Issue by ErikEvenson** [hashicorp/nomad#820]
I'm trying out 3rc1 and one of my nomad job files (which validates) is failing with:

```
Error submitting job: Unexpected response code: 500 (1 error(s) occurred:

* Task group 1 validation failed: 2 error(s) occurred:

* Unsupported restart mode: ""
* Task 1 validation failed: 1 error(s) occurred:

* Missing Log Config)
```

Here is my job configuration:

```
job "vbez-web" {
	region = "global"
	datacenters = ["dc0"]
	type = "service"
	priority = 50

	constraint {
		attribute = "${attr.kernel.name}"
		value = "linux"
	}

	update {
		stagger = "10s"
		max_parallel = 1
	}

	group "vbez-web" {
		count = 1

		task "api" {
			driver = "docker"

			config {
				dns_servers = ["172.17.0.1", "75.75.76.76", "75.75.75.75"]
				image = "<something>"
				port_map {
					web = 8080
				}
			}

			service {
				name = "vbez-web"
				tags = ["global"]
				port = "web"

				check {
					name = "alive"
					type = "tcp"
					interval = "10s"
					timeout = "2s"
				}
			}

			resources {
				cpu = 500
				disk = 10
				memory = 256
				network {
					mbits = 10
					port "web" {
					}
				}
			}
		}
	}
}
```

**Comment by ErikEvenson** [comment]
I tried adding this to my task with no joy:

			logs {
			  max_files = 10
			  max_file_size = 100
			}

**Comment by diptanu** [comment]
@ErikEvenson I am not able to reproduce all the errors you have listed. Can you please check the version of the nomad binary by running `nomad version` please?

The only error in that job file was that you have requested for 10MB of disk space without any log configuration and the default log configuration is 10 files of 10MB each so you would have to request for  atleast 100MB of disk space.

**Comment by ErikEvenson** [comment]
@diptanu on the client node I am running:

```
$ nomad -version
Nomad v0.3.0-rc1 (5e1a3c636c56410f7a025908b70cbb8700be0a71+CHANGES)

```
I am sending the nomad command via nomad 0.2.3.

**Comment by diptanu** [comment]
@ErikEvenson Yeah so that's the problem, the job spec has some backward incompatible change. Can you please use the nomad `v0.3.0-rc1` binary to run the nomad commands too?

**Comment by ErikEvenson** [comment]
That fixed the validation problem.  My job is failing, but I suspect that is a problem with the way that the job is (or is not) using the docker config for auth.

Thanks!
