### ISSUE TITLE
Task log viewer for consul-connect enabled job switches erroneously

### ISSUE THREAD

**Issue by djmarcin** [hashicorp/nomad#8222]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.11.1 (b43457070037800fcc8442c8ff095ff4005dab33)

### Operating system and Environment details
Ubuntu 20.04

### Issue
When viewing a consul-connect enabled job, clicking into the task logs for the job will inexplicably switch to the consul-connect sidecar's logs after a period of about 10-20 seconds. 

### Reproduction steps
This seems to happen every almost every time for me.
1) Create a consul-connect enabled job
2) Click into the actual task for the job and navigate to the logs for the task
3) Click stderr logs
4) Wait 10-20s, the logs window will refresh to the consul-connect sidecar's logs.

**Comment by spuder** [comment]
I am also seeing this issue

**Comment by betaboon** [comment]
this happens to me as well. but with a somewhat broader scope:
- happens without consul-connect being enabled
- happens on overview-tab as well as logs-tab
- happens as soon as i put multiple tasks in the same group
- only happens when there is at least one task failing and being restarted

**Comment by DingoEatingFuzz** [comment]
I believe this is a duplicate of #8545 and fixed with #8833 which released in 0.12.5.

Feel free to reopen if you think this is a distinct bug.
