### ISSUE TITLE
[feature] Add native Docker GPU support (Docker v19.03+)

### ISSUE THREAD

**Issue by bmenn** [hashicorp/nomad#8234]
As of Docker v19.03, Nvidia GPUs are natively supported (assuming nvidia-container-toolkit is installed) using the `--gpus` flag. It would be nice to natively support Nvidia GPUs in Docker using this newer functionality without having to go down the route of installing nvidia-docker/nvidia-docker2 and configuring the Docker runtimes.

**Comment by trilom** [comment]
I'm having this issue.

I'm wanting to use the [nvidia-device](https://www.nomadproject.io/docs/devices/nvidia/) driver but it forces me to use this older way.

When I go down the path of setting my host up to use the `--gpus` then I am unable to accomplish passing this variable to the container, its puts a halt on my usage of cuda11 with Nvidia and Nomad.

Thanks

**Comment by shoenig** [comment]
First step we need to upgrade our import of docker to v19.03+ https://github.com/hashicorp/nomad/pull/8127

**Comment by bmenn** [comment]
Hi @shoenig,

I don't know if this interferes with the plans in #8127, but I think I might have found a simple code change to support this feature. I've created a draft PR #8361 to discuss the proposed change.

**Comment by supernovae** [comment]
Nvidia deprecated the old stuff, is there any way to get native driver support for gpu in docker 19.0.3+ ?

**Comment by shoenig** [comment]
>  It would be nice to natively support Nvidia GPUs in Docker using this newer functionality without having to go down the route of installing nvidia-docker/nvidia-docker2 

@bmenn or @supernovae are you sure `nvidia-docker2` is not required to use `--gpus` ? 

I just tried this on a fresh `p3.2xlarge` VM, and docker by itself isn't enough.

And Nvidia's own documentation [instructs you to install](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit) `nvidia-docker2` before making use of `--gpus`. 

### install docker & nvidia driver

```shell
sudo apt install docker.io
sudo apt install nvidia-driver-510-server
```

### running smi with --gpus
```shell
$ docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi 
Unable to find image 'nvidia/cuda:11.0-base' locally
11.0-base: Pulling from nvidia/cuda
54ee1f796a1e: Pull complete 
f7bfea53ad12: Pull complete 
46d371e02073: Pull complete 
b66c17bbf772: Pull complete 
3642f1a6dfb3: Pull complete 
e5ce55b8b4b9: Pull complete 
155bc0332b0a: Pull complete 
Digest: sha256:774ca3d612de15213102c2dbbba55df44dc5cf9870ca2be6c6e9c627fa63d67a
Status: Downloaded newer image for nvidia/cuda:11.0-base
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

<details><summary>docker version</summary>

```shell
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1004-aws
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 59.85GiB
 Name: ip-172-31-67-39
 ID: BEED:LRKZ:WTP5:C2TT:4NZI:PT6M:HTEZ:MAXI:CKTI:6VKZ:A4WN:VZ3X
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

Now after installing `nvidia-docker2`

```shell
$ sudo apt install nvidia-docker2
```

```shell
$ docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi 
Mon May  2 13:36:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P0    37W / 300W |      0MiB / 16384MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by shoenig** [comment]
I intend to close this via https://github.com/hashicorp/nomad/pull/12840 which updates the nomad nvidia driver docs to reference the new container runtime toolkit.

If I've just completely missed something and the instructions are wrong, please re-open and let me know!
