### ISSUE TITLE
Nomad raw_exec does not kill child process.

### ISSUE THREAD

**Issue by vyacheslav-skvortsov** [hashicorp/nomad#8235]
### Nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

### Operating system and Environment details
Windows Server 2016
### Issue
Nomad does not kill child process on Windows. In my example I run ping process under PowerShell. After that I'm stopping job. After 5s Nomad kills only powershell process and ping process lost its parent and continuos working.
1.Start job
![image](https://user-images.githubusercontent.com/29980836/85284762-63c36580-b498-11ea-86ce-4fc0e85ca500.png)
2.Stop job
![image](https://user-images.githubusercontent.com/29980836/85284895-9d946c00-b498-11ea-9478-c1a39a5ca5b5.png)

Nomad should kill all process tree.
### Reproduction steps
1.Run job
2.Stop job
### Job file (if appropriate)

```hcl
job "kill-child" {
  datacenters = ["dc1"]
  type = "service"

  group "kill-child" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      operator  = "="
      value     = "node_name"
    }
    ephemeral_disk {
      size    = "200"
    }
    task "kill-child" {
      driver = "raw_exec"
      
      config {
          command  = "powershell.exe"
          args = ["-Command", "./start.ps1"]
      }

      template {
        data = <<EOH
ping google.com -t
        EOH
        destination = "start.ps1"
      }

      resources {
        cpu = 100
        memory = 100
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @vyacheslav-skvortsov! The `raw_exec` driver starts everything in a process group which gets Ctrl-Break/`SIGTERM` (that detail is has caused some issues in https://github.com/hashicorp/nomad/issues/7747). If you run this powershell script without Nomad and then `SIGTERM` it instead of sending a `SIGINT` via Ctrl-C, does it still result in an orphaned process?

**Comment by vyacheslav-skvortsov** [comment]
Hi @tgross! Thank you for reply.
Yes, it is the same behaviour if I kill powershell process. But if I kill process tree `taskkill /PID 5556 /T /F`  it kills all processes together with ping.exe.

About this issue [#7747 ](https://github.com/hashicorp/nomad/issues/7747). This may not be enough in cases where the process freezes and cannot correctly process the signal, so I believe that Nomad needs to kill the entire process tree that was created.

**Comment by tgross** [comment]
`taskkill` sends a WM message, so it doesn't really map directly to a signal and I can't find in the documentation what it sends (it sends a signal I'm sure but I'm not sure which one). Can you verify that behavior with `SIGTERM` directly?

**Comment by vyacheslav-skvortsov** [comment]
Actually I don't know how to send `SIGTERM` on Windows host. Could you give an article with an explanation of this? :)
But I tried to investigate what signal nomad sends exactly. I wrote this code https://github.com/vyacheslav-skvortsov/catch-kill-signal to understand. 
Results:
- when I stop nomad job a console app catches `CtrlTypes.CTRL_BREAK_EVENT` 
- when I use keyboard to terminate process it catches `CtrlTypes.CTRL_C_EVENT` for Ctrl+C and `CtrlTypes.CTRL_BREAK_EVENT` for Ctrl+Break accordingly, but actually `CtrlTypes.CTRL_BREAK_EVENT` does not stop process execution and it continues working without any termination.
- `taskkill` does not send any signal to the process and just kill it.

**Comment by tgross** [comment]
> Actually I don't know how to send `SIGTERM` on Windows host. Could you give an article with an explanation of this? :)

Technically you can't and I should have been more clear. What I'm looking for is the Ctrl-Break event, which is what gets sent when a golang application fires `SIGTERM` on Windows (that's how the golang stdlib maps it under the hood).

> but actually `CtrlTypes.CTRL_BREAK_EVENT` does not stop process execution and it continues working without any termination.

Ok, I suspect there's some difference in the way the interactive process is handling control events. But it definitely looks like we're missing some piece of the process group shutdown under windows. Going to mark this as a bug for further investigation.

**Comment by AbhinJames** [comment]
Hi,

I was wondering if "Nomad raw_exec does not kill child process. #8235" has been resolved or not? 

Thanks

**Comment by fredwangwang** [comment]
Hi,
we ran into this issue as well but looks like a different cause.

Our raw_exec setup runs the binary directly without powershell:
```hcl
      config {
        command = "filebeat.exe"
        args    = ["-c", "local/filebeat.yml"]
      }
```

And when trying to drain the node sometimes it just stuck with an allocation that it cannot kill.
![image](https://user-images.githubusercontent.com/21690857/166941433-ab04c3d5-f67b-443d-a7aa-d9c81a26bfcd.png)


checking the executor log for the allocations reveals the following. Not sure what is the reason causes this...
`Error sending ctrl-break event: no process is on the other end of the pipe`

![image](https://user-images.githubusercontent.com/21690857/166940951-38761660-92a0-4480-813b-6fb56056e59c.png)

**Comment by tgross** [comment]
Fixed (finally!) by https://github.com/hashicorp/nomad/pull/24214
