### ISSUE TITLE
nomad node status down

### ISSUE THREAD

**Issue by JakobStadlhuber** [hashicorp/nomad#8240]
### Nomad version
v0.10.2

### Operating system and Environment details
debian

### Issue
One of my three server had an issue and we had to reinstall the hole OS. After reinstall the hole software stack, the problem  one node(server0) is now down.
How can i fix it and get the node ready again?

### Nomad Server logs
nomad node status:
ID        DC   Name           Class   Drain  Eligibility  Status
2fd52374  dc1  server0  <none>  false  eligible     down
0fa62548  dc1  server1  <none>  false  eligible     ready
4a5f48c6  dc1  server2  <none>  false  eligible     ready

nomad server members:
Name                  Address          Port  Status  Leader  Protocol  Build   Datacenter  Region
server0.global  192.168.123.200  4648  alive   false   2         0.10.2  dc1         global
server1.global  192.168.123.201  4648  alive   true    2         0.10.2  dc1         global
server2.global  192.168.123.202  4648  alive   false   2         0.10.2  dc1         global

**Comment by tgross** [comment]
Hi @JakobStadlhuber! It might be that the new server can't auto-join the old servers or that it needs to be joined manually. If you check the server logs, it should be reporting some hint as to what's happening.

**Comment by JakobStadlhuber** [comment]
I already tried to join it manually with nomad server join and it works but the node is down.

**Comment by JakobStadlhuber** [comment]
```
2fd52374 
ID            = 2fd52374 -b6d4-b461-5cea-9cb3603218fd
Name          = server0
Class         = <none>
DC            = dc1
Drain         = false
Eligibility   = eligible
Status        = down
Uptime        = 15m0s
Host Volumes  = <none>
Driver Status = docker,exec

Node Events
Time                  Subsystem  Message
2020-06-22T13:23:46Z  Cluster    Node heartbeat missed
2020-06-22T13:18:36Z  Cluster    Node re-registered
2020-06-22T13:18:16Z  Cluster    Node heartbeat missed
2020-06-16T14:29:11Z  Cluster    Node re-registered
2020-06-16T14:28:50Z  Cluster    Node heartbeat missed
2020-06-16T14:18:53Z  Cluster    Node registered

Allocated Resources
CPU         Memory       Disk
0/8388 MHz  0 B/3.9 GiB  0 B/12 GiB

Allocation Resource Utilization
CPU         Memory
0/8388 MHz  0 B/3.9 GiB

Host Resource Utilization
CPU          Memory           Disk
20/8388 MHz  484 MiB/3.9 GiB  3.0 GiB/16 GiB

Allocations
No allocations placed
```

**Comment by JakobStadlhuber** [comment]
nomad agent-info:
`client
  heartbeat_ttl = 0s
  last_heartbeat = 2562047h47m16.854775807s`

Is it possible that there is a problem with the heartbeat? How can i configure it?

**Comment by JakobStadlhuber** [comment]
curl --request PUT http://localhost:4646/v1/system/gc fixed it for me
