### ISSUE TITLE
[question] How do I configure heap space within Docker container?

### ISSUE THREAD

**Issue by dean-n** [hashicorp/nomad#8268]
### Nomad version
0.9.6

### Operating system and Environment details
Ubuntu 18.04

### Question
Is it possible to configure the -Xmx and -Xms for a docker nomad task?

I've tried adding the -Xmx and -Xms values to my java command in my docker-entrypoint.sh but it doesn't seem to affect the amount of memory being used (I check this via Broccoli). The jvm_options config for the Java driver looked very useful. Is there an equivalent for the docker driver?

**Comment by tgross** [comment]
Hi @dean-n!

> I've tried adding the -Xmx and -Xms values to my java command in my docker-entrypoint.sh but it doesn't seem to affect the amount of memory being used (I check this via Broccoli).

This is really more of a Docker container configuration issue, but if you provide the jobspec I might be able to give you some pointers. As a general container deployment practice, you'll want to avoid setting instance-specific values in a file like the `docker-entrypoint.sh`, because then you can't change the values if you want to change the Nomad resources too without rebuilding the container.

So for JVM options being passed to Docker you'll probably want to use the [`args`](https://www.nomadproject.io/docs/drivers/docker#args) field or set `JVM_OPTS` options as an environment variable in the [`env`](https://www.nomadproject.io/docs/job-specification/env) field.

> The jvm_options config for the Java driver looked very useful. Is there an equivalent for the docker driver?

Our `java` driver is specific to Nomad (sharing most of it internals with the `exec` driver), whereas the Docker driver is just making API calls to Docker itself. So because Docker doesn't support a `jvm_options` field, we can't support one for the Docker driver either.

**Comment by dean-n** [comment]
Hi @tgross 

Apologies, I didn't realise this wasn't a nomad problem. Thank you for offering to assist anyway, it's much appreciated 😄 

I've actually tried setting the Xmx and Xms values using the env field which didn't seem to work. With the task below, our Broccoli UI says that my task is only using 1.1Gb of memory.

Is there a way to use the args field provide a `-m` value for a docker run command?

```
-- - myhcl.hcl

task "my-task" {
  driver  =  "docker"

  config {
    image  = "docker-registry.my.domain/some-repo/y:latest"
    ...
  }

  env {
    "JVM_ARGS"="-Xms2500M -Xmx2500M "
  }

  resources {
   memory = 4096
    ...
  }
}


---  docker-entrypoint.sh

#!/bin/sh
JVM_ARGS_UNQUOTED=`echo $JVM_ARGS | sed  's|\"||g'`

SPRING_PROFILES=nomad

java  \
$JVM_ARGS_UNQUOTED\
-Dspring.profiles.active=$SPRING_PROFILES \
-Djava.security.egd=file:/somefile
-jar /app.jar


```

**Comment by tgross** [comment]
> I've actually tried setting the Xmx and Xms values using the env field which didn't seem to work. 

It's probably a good idea to check the running Docker container's command and args with `docker inspect` to make sure the container has been built to run that `docker-entrypoint.sh` script and not some other script in its `ENTRYPOINT` in the Dockerfile.

It's also worth double-checking the arguments on your host with `ps -ef | grep java` to make sure that the `java` process is getting the arguments you expect. 

You could also just bypass the entrypoint of the built container by passing the command and args directly into the Nomad job spec:

```hcl
task "my-task" {
  driver = "docker"

  config {
    image   = "docker-registry.my.domain/some-repo/y:latest"
    command = "/usr/bin/java"
    args = [
      "-Xms2500M",
      "-Xmx2500M",
      "-Dspring.profiles.active=nomad",
      "-Djava.security.egd=file:/somefile"
      "-jar", "/app.jar"
    ]
  }
}
```

> With the task below, our Broccoli UI says that my task is only using 1.1Gb of memory.

I'm not familiar with Broccoli and can't find anything about it via search for some reason. Is it possible it's not measuring the initial allocation of heap memory?

> Is there a way to use the args field provide a `-m` value for a docker run command?

The `resources` `memory` field you've set at `4096` in the Nomad job is exactly the same as the `-m` value passed Docker run. But that sets a _maximum_ amount of memory the container is allowed to use. It doesn't tell the JVM anything about how much heap to claim on startup.

**Comment by dean-n** [comment]
Thank you for your reply @tgross 

Passing the command and args directly into the job spec, didn't know you could do that! I will give it a go.

Does that mean it won't attempt to run my docker-entrypoint.sh?

A link to the Broccoli UI gitlab here if you're curious (https://github.com/data-science-platform/cluster-broccoli)

**Comment by tgross** [comment]
> Does that mean it won't attempt to run my docker-entrypoint.sh?

That script will only get run if you have an `ENTRYPOINT` directive that points to it in your Dockerfile, or if you're using the [`entrypoint`](https://www.nomadproject.io/docs/drivers/docker#entrypoint) field to point to it in Nomad (same as the Docker `--entrypoint` flag). You might find it worthwhile to review [this StackOverflow Q about `CMD` vs `ENTRYPOINT`](https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile) or [this Docker knowledge base article on entrypoint scripts](https://success.docker.com/article/use-a-script-to-initialize-stateful-container-data).

I think we've resolved the original issue, so I'm going to close this one out. Thanks for posting @dean-n!
