### ISSUE TITLE
Ensure connect native tasks work with raw_exec and share_tls

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#8276]
Nomad's Connect Native plumbing introduces a `share_tls` Nomad Client agent configuration parameter, which when set will copy the Nomad agent's TLS configuration into the `secrets` directory of the task's FS namespace. This probably does not work with the `raw_exec` task driver since there is no FS NS. Figure out a reasonable thing to do. (symlink? hardlink? copy the files _somewhere_?)

**Comment by tgross** [comment]
Doing a little issue cleanup. Connect Native is deprecated (see https://developer.hashicorp.com/consul/docs/connect/native). So we won't want to add any new features to it.
