### ISSUE TITLE
on the website make the search box in 'docs' more visible?

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#8293]
On the website at the following link, the search box is barely visible, I noticed it only a few days ago. 😲 😲 
https://www.nomadproject.io/docs

This is how I see it in Firefox:

![image](https://user-images.githubusercontent.com/2508915/85794169-c98f4600-b753-11ea-9a63-5a0554d7040a.png)

Could it be made so that it grabs more attention?  (border highlight, etc.)

BTW, for me, the search box is a very (very very) welcome addition!!! 👍  👍  

_Not sure how long it has been there!!!_

@angrycub @langmartin

**Comment by tgross** [comment]
Hi @shantanugadgil! If you think that's great, just wait till you see the upcoming improvements to search results!

I'm going to tag in @jescalan about the visibility issue.

**Comment by mwickett** [comment]
Hey all, I'll grab this one. We'll make some visibility improvements to this filter input. And as @tgross mentioned, "real" search is coming!

**Comment by rkettelerij** [comment]
TIL the Nomad webpage - which I frequently visit - has a filterbox :)

**Comment by tgross** [comment]
I don't have a commit handy where this was done, but we fixed this in the nomadproject.io redesign, where the search box is now front-and-center. Going to close this out.
