### ISSUE TITLE
Missing documentation for nomad.client.allocs.oom_killed metric

### ISSUE THREAD

**Issue by nirgilboa** [hashicorp/nomad#8297]
### Nomad version
Nomad v0.11.2 (807cfebe90d56f9e5beec3e72936ebe86acc8ce3)

### Issue
Please add details for the 'nomad.client.allocs.oom_killed' metric on the [Metrics](https://www.nomadproject.io/docs/telemetry/metrics) page

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/9694
