### ISSUE TITLE
Connect sidecar always listens on a port even if no port is defined on a service

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#8307]
### Nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

### Operating system and Environment details
Debian with docker driver enabled

### Issue
The connect sidecar always exposes a custom "listener" to accept connection even if the service has no port.

### Reproduction steps
```
nomad init -connect -short
# remove port = 9002 from count-dashboard service
nomad job run example.nomad
```

Now if you look into the nomad ui you will see the following:
![image](https://user-images.githubusercontent.com/81547/86025239-45c4aa80-ba2e-11ea-8f8a-fed46357318b.png)

There is no reason for the connect proxy to expose a port 20051 since the service it binds to (after removing the port element from above) is only used to proxy to the backend service (dashboard api).

If this is by design, feel free to close. But I think in this case we could safe a few ports and consul checks if the envoy sidecar wouldn't listen on this additional port since nothing can connect to it anyways.

Out of curiosity, when looking into consul one sees:
![image](https://user-images.githubusercontent.com/81547/86025618-b8358a80-ba2e-11ea-9d24-f2136d2b7496.png)
What is the alias check for?

**Comment by shoenig** [comment]
Thanks for reporting, @apollo13 ! This is by design from the [Consul side](https://www.consul.io/docs/connect/registration/sidecar-service#sidecar-service-registration). If nothing else, the open (w/ mTLS enabled) port serves as an endpoint for a default TCP check used by Consul to know whether the sidecar is alive as expected.

It might not be applicable to your situation, but Nomad v0.12 is introducing support for [Connect Native](https://www.consul.io/docs/connect/native) tasks, eliminating the need for a sidecar to join the Consul Connect service mesh altogether.


> What is the alias check for?

This is also a default check from the [Consul side](https://github.com/hashicorp/consul/blob/v1.7.4/agent/sidecar_service.go#L172). Basically it ensures the sidecar becomes unhealthy if the service it's representing is failing its own checks. Without it, if the service had checks defined but was failing them, Consul [DNS, etc] would still route traffic to it because of the discovery of the otherwise healthy _proxy_ instances.

Hope that helps!

**Comment by apollo13** [comment]
@shoenig Thank you for the detailed explanation. I have a follow up on to Connect Native tasks though. The connect stanza is currently only allowed in:
```
job -> group -> service -> connect
```
with a native connect, wouldn't it make sense to allow it also in `job -> task -> service`  and `job -> group -> task -> service` (obviously only if native=True)?

> If nothing else, the open (w/ mTLS enabled) port serves as an endpoint for a default TCP check used by Consul to know whether the sidecar is alive as expected.

Does this also hold true for connect native tasks? Ie. do I also need to open such a listener or can I get away by just opening mTLS powered http connections. Basically I am thinking of using the `template` stanza to fetch connect certs to secure a database connection (without having the overhead of the sidecar).

**Comment by shoenig** [comment]
We discussed the TaskGroup vs Task level placement for the `connect` stanza internally for a bit - one of the things we're trying to push forward is a better emphasis on the use of TaskGroup networking and service definitions. The idea being that the TaskGroup encapsulates an implementation provided by its Tasks, such that a Consul Service represents something provided by the Group. That abstraction might not be perfect, and we're certainly open to feedback!

> Does this also hold true for connect native tasks?

With connect native, you explicitly instantiate either a client or server (or both) from a connect native consul service object. If you only need the client of course, no extraneous port is required. We've got some example code around this that isn't public yet, that's my fault. But the gist for using it as a client would something like,

```golang
service, err := connect.NewService("<service>", consul)
client := service.HTTPClient()
client.Get("https://<upstream>.service.consul/")
```

The connect native library is slightly more fancy than using `consul-template` to fetch certs - it works by creating an `http.Client` with a custom `http.Transport` that automatically refreshes the short-lived mTLS certs before expiry. It also provides some nice features like useable Consul DNS names without actually configuring Consul DNS.

**Comment by apollo13** [comment]
> That abstraction might not be perfect, and we're certainly open to feedback!

Well, cannot comment much on that. But it would certainly be a good material for a blog post (ie where is nomad heading, how are usages etc intended). 

> such that a Consul Service represents something provided by the Group.  

interesting, in that sense I would have expected the `network` stanza on the group level default to `bridge` instead of `host` for further -- but I guess that ship has sailed :)

> The connect native library is slightly more fancy than using consul-template to fetch certs …

right, but in my case it's not a go library and even then, injecting that into something like a database adapter might be hard.  So as long as `consul-template` works that is already a massive win. Thanks for confirming it!
