### ISSUE TITLE
Job not registered in correct region using API body region

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#8323]
### Nomad version
```
Nomad v0.12.0-beta2 (5b80d4e638f1a27eee3ca245f8babb115e4c098d)
```

Update: I see there is a related issue in v0.11.3 as well; not sure why.
Update2: Okay, I conflated `args.WriteRequest.Region` with the `?region` query parameter in the http request object. This is apparently two separate bugs:
* if the region is specified as a query parameter (which is what `nomad run` does), the region is honored but incorrectly set on the Job in both 0.11.x and 0.12.0-beta2
* if the region is specified as part of the job payload, 0.11.3 will send it to the correct region and properly persist `.Region` on the job; 0.12.0-beta2, however, will submit it to the incorrect region.

This bug is filed against the latter (newer, more critical) bug.

This code also appears in job plan.

### Operating system and Environment details
Darwin, two federated, single-node clusters ("region1", "region2")

### Issue
`Job.Region` is being overwritten, allowing a job to be registered in the wrong region.

The `||` logic at https://github.com/hashicorp/nomad/blob/v0.12.0-beta2/command/agent/job_endpoint.go#L163 should potentially be an `&&`; that is, `region` should only be set to the local region if there is no/default/empty region in the job AND no/default/empty region in the query parameter.

### Reproduction steps
Run the nomad command against `region1`, with API forwarding for `region2`; the job will be registered in `region1`:
```bash
$ http localhost:4646/v1/jobs < job2.json
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 148
Content-Type: application/json
Date: Tue, 30 Jun 2020 22:20:06 GMT
Vary: Accept-Encoding
X-Nomad-Index: 11

{
    "EvalCreateIndex": 11,
    "EvalID": "3f4cf1b2-c7cf-3c92-3124-9e6917b608b2",
    "Index": 11,
    "JobModifyIndex": 10,
    "KnownLeader": false,
    "LastContact": 0,
    "Warnings": ""
}

$ nomad job inspect -region region2 job2
No job(s) with prefix or id "job2" found

$ nomad job inspect -region region1 -json job2 | jq '.Region'
"region1"
```

### Job file
Any job file should do...
```json
{
    "Region": "region2",
    "Job": {
        "Stop": null,
        "Region": null,
        "Namespace": null,
        "ID": "job2",
        "ParentID": null,
        "Name": "job2",
        "Type": null,
        "Priority": null,
        "AllAtOnce": null,
        "Datacenters": [
            "dc1"
        ],
        "Constraints": null,
        "Affinities": null,
        "TaskGroups": [
            {
                "Name": "web",
                "Count": null,
                "Constraints": null,
                "Affinities": null,
                "Tasks": [
                    {
                        "Name": "nginx",
                        "Driver": "docker",
                        "User": "",
                        "Lifecycle": null,
                        "Config": {
                            "image": "nginx"
                        },
                        "Constraints": null,
                        "Affinities": null,
                        "Env": null,
                        "Services": null,
                        "Resources": null,
                        "RestartPolicy": null,
                        "Meta": null,
                        "KillTimeout": null,
                        "LogConfig": null,
                        "Artifacts": null,
                        "Vault": null,
                        "Templates": null,
                        "DispatchPayload": null,
                        "VolumeMounts": null,
                        "Leader": false,
                        "ShutdownDelay": 0,
                        "KillSignal": "",
                        "Kind": ""
                    }
                ],
                "Spreads": null,
                "Volumes": null,
                "RestartPolicy": null,
                "ReschedulePolicy": null,
                "EphemeralDisk": null,
                "Update": null,
                "Migrate": null,
                "Networks": null,
                "Meta": null,
                "Services": null,
                "ShutdownDelay": null,
                "StopAfterClientDisconnect": null,
                "Scaling": null
            }
        ],
        "Update": null,
        "Multiregion": null,
        "Spreads": null,
        "Periodic": null,
        "ParameterizedJob": null,
        "Dispatched": false,
        "Payload": null,
        "Reschedule": null,
        "Migrate": null,
        "Meta": null,
        "ConsulToken": null,
        "VaultToken": null,
        "NomadTokenID": null,
        "Status": null,
        "StatusDescription": null,
        "Stable": null,
        "Version": null,
        "SubmitTime": null,
        "CreateIndex": null,
        "ModifyIndex": null,
        "JobModifyIndex": null
    }
}
```

**Comment by tgross** [comment]
https://github.com/hashicorp/nomad/pull/8347 should fix the 0.12.0-beta2 specific bits of this. But...

> if the region is specified as a query parameter (which is what nomad run does), the region is honored but incorrectly set on the Job in both 0.11.x and 0.12.0-beta2

I'm not sure this is actually a bug (or if it is, it's not in the flag handling). The `-region` flag determines which region we ultimately get forwarded to, and the `Job.Register` code implicitly assumes that it's upserting the job into the RPC handler's own region.
