### ISSUE TITLE
Nomad Job is GC'd contrary to GC config

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#8345]
### Nomad version
Output from `nomad version`
```
$ nomad version
Nomad v0.11.2 (807cfebe90d56f9e5beec3e72936ebe86acc8ce3)
```
### Operating system and Environment details
Amazon Linux 2

### Issue
Allocation, then subsequently job, is being GC'd too quickly.

We have an DAG orchestration system that runs against Nomad, which need to query the status of batch jobs that run. We are often seeing a case where the allocation is being marked for GC, gets GC'd in seconds, then GC's the job as well. 

This causes a problem because our system queries the job for its status a few seconds later, but the job is gone by that time. With the settings listed below, we do not expect the job to be gone for a few hours.

We have the server configured with GC settings in hours:
```
      "node_gc_threshold": "24h",
      "job_gc_threshold": "4h",
      "eval_gc_threshold": "1h",
      "deployment_gc_threshold": "1h"
```

This nomad cluster is extremely busy, running hundreds of jobs and thousands of allocations, so I'm curious if there is another configuration somewhere that is forcing the Nomad server to ignore these config values? If not, why are we seeing this behavior? 

Logs from Kibana:
<img width="1277" alt="Screen Shot 2020-07-02 at 10 42 58 AM" src="https://user-images.githubusercontent.com/4636740/86392885-06c26f00-bc51-11ea-96bc-0db281050a6b.png">

The newest log is from our system erroring out because it can no longer find the job. As you can see, it queried just a few seconds after.

**Comment by notnoop** [comment]
Hi @djenriquez !  are the job and allocations completely gone from the servers as well?  i.e. would `nomad alloc status 4c9bb2d` return "alloc not found" error in the above case?

Looking at the logs, it looks like the allocation has been GCed on the client to free up disk space.  Clients have different GC parameters, e.g. [`gc_disk_usage_threshold`](https://www.nomadproject.io/docs/configuration/client#gc_disk_usage_threshold), [`gc_max_allocs`](https://www.nomadproject.io/docs/configuration/client#gc_max_allocs).  If the alloc terminates, and free space is low and/or a lot of allocations are running on the client, then the client will GC the allocation.  I expect the job info to be still present on server info, but without the stats, logs, and file system info.

**Comment by djenriquez** [comment]
Hi @notnoop, thank you for the reply! It did not occur to me to check the client GC settings, this could very well be the cause, but I can confirm that the job also disappears. Our system queries the `/v1/job/<job_name>` API, and whatever is returned in this case no longer has the `Status` property since our application is getting a key error on that field.

If the client GCs the alloction, should the job `Status` disappear from the `/v1/job/<job_name>` response?

**Comment by qqzeng** [comment]
Hi @notnoop, thank you for your reply. I also have a question. We see that nomad's gc includes both server and client, and gc settings in server includes gc of the job, evualation, deployment, etc. I found that although I overwrote default settings in the server configuration file, the server's gc result was not what I expected. More precisely, here is my configuration about gc in server side:
```
job_gc_threshold="1m"
node_gc_threshold="24h"
job_gc_interval="1m"
eval_gc_threshold="1m"
deployment_gc_threshold="1m"
```
But in fact, I found the result of gc was not what I expected. (After more than 12 hours have passed since jobs I created, they still have not been garbaged collected.) So, would you please briefly explain the job gc strategy in detail? 

BTW, the document of description and explanation about gc is too simple, and I briefly browsed the source code, but I still can't understand the specific strategy of gc in server side.

Looking forward to your reply.

**Comment by notnoop** [comment]
I'll mark this as a documentation enhancement.  It's unclear what might be affecting your experience.

Worth noting that Nomad only GC jobs that are dead and aren't expected to restart again (without manual intervention).  If a job lasts for days (e.g. service jobs, super long batch job), it will not be GCed.  Only after the job completes or stopped manually, will Nomad GC it.  [`jobIsGCable`](https://github.com/hashicorp/nomad/blob/v0.12.1/nomad/state/schema.go#L242-L275) function clarifies which jobs are GCable, and [`jobGC`](https://github.com/hashicorp/nomad/blob/v0.12.1/nomad/core_sched.go#L90-L124) performs the threshold check.  Also, to clarify, GC is mostly meant as an internal process that prevents Nomad from ever growing memory usage - its only user visible affect should be that completed jobs eventually get removed from API results.

If your experience doesn't match above, please submit logs along with (`nomad job status --verbose` and `nomad job status --json`).  Also, attempt to run `nomad system gc`, and see if it updates the job.

**Comment by tgross** [comment]
Documentation issue consolidated with https://github.com/hashicorp/nomad/issues/8130
