### ISSUE TITLE
Both Region and Multi Region Blocks exist after initial nomad run

### ISSUE THREAD

**Issue by GuyBarros** [hashicorp/nomad#8354]
### Nomad version
Nomad v0.12.0-beta2+ent (8ec1a37c717f662b50e9cf60c8c0721c88acfdfb)

### Operating system and Environment details
ubuntu 16:04 AMD64

### Issue

Plan Error

Job can't have both multiregion and region blocks

### Reproduction steps
* deploy a multi region job via Nomad CLI
* open the nomad web ui to that job definition and change the count
    * the above error appears 

### Job file (if appropriate)
```hcl
job "nginx" {
   multiregion {
     region  "eu-west-2" {
    datacenters = ["EU-guystack"]
    count = 5
    }
    region  "eu-central-1" {
  datacenters = ["DE-guystack"]
  count = 5 
    }
  }
  type = "service"

  group "withvault" {
    vault {
      policies = ["superuser"]
    }

    task "nginx-pki" {
      driver = "docker"

      config {
        image = "nginx"
        port_map {
          http = 80
        }
        port_map {
          https = 443
        }
        volumes = [
          "custom/default.conf:/etc/nginx/conf.d/default.conf",
          "secret/cert.key:/etc/nginx/ssl/nginx.key",
        ]
      }

      template {
        data = <<EOH
          server {
            listen 80;
            listen 443 ssl;

            server_name nginx.service.consul;
            # note this is slightly wonky using the same file for
            # both the cert and key
            ssl_certificate /etc/nginx/ssl/nginx.key;
            ssl_certificate_key /etc/nginx/ssl/nginx.key;

            location / {
              root /local/data/;
            }
          }
        EOH

        destination = "custom/default.conf"
      }

      template {
        data = <<EOH
{{ with secret "pki/issue/consul-service" "common_name=nginx.service.consul" "ttl=30m" }}
{{ .Data.certificate }}
{{ .Data.private_key }}
{{ end }}
      EOH

        destination = "secret/cert.key"
      }

      template {
        data = <<EOH
            <h2> Hello World </h2>
            <br />
            <br />
           
             from {{ env "node.unique.name" }}
            <br />
            <br />
           
            <br />
	          <br />
            {{ with secret "pki/issue/consul-service" "common_name=nginx.service.consul" "ttl=90m" }}
            {{ .Data.certificate }}
            <br />
            <br />
            {{ .Data.private_key }}
            {{ end }}
        EOH

        destination = "local/data/nginx-pki/index.html"
      }

      resources {
        cpu    = 100 # 100 MHz
        memory = 128 # 128 MB
        network {
          mbits = 10
          port "http" {
            
          }
          port "https" {
            
          }
        }
      }

      service {
        name = "nginx-pki"
        port = "http"
        tags = [
          "global",
          "urlprefix-/nginx-pki"
          ]
        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }

  }
}

```

**Comment by tgross** [comment]
The region-local version of the job is stored in each region _after_ interpolation, and the UI (very reasonably! 😁 ) expects that the jobspec it gets via the API is valid to hand back. Having the interpolated region in the jobspec is used by the registration step as a sentinel to prevent a registration-loop, so we can't simply remove that check with the current design either.

But I'm not wild about forcing the UI to manipulate the jobspec to remove the region in this case, as that seems out-of-scope for its behavior. I'll want to confer with @DingoEatingFuzz about this.

**Comment by DingoEatingFuzz** [comment]
I have two thoughts here.

1. The UI can totally manipulate the job spec if that's what we deem is the best option. No point in taking it off the table.
2. The UI is just presenting what comes back from the `GET /v1/job/:id` endpoint.

I'm less concerned about making the UI jump through an extra hoop and more concerned about expecting all consumers of the API to jump through this hoop.

I don't know how common it is to make job changes via fetching, editing, and resubmitting through the API—certainly the happy path is job definitions are managed outside of Nomad's internal state—but it's not hard to imagine people writing tools between end users and Nomad itself that does these types of transformations.

**Comment by tgross** [comment]
> I don't know how common it is to make job changes via fetching, editing, and resubmitting through the API—certainly the happy path is job definitions are managed outside of Nomad's internal state—but it's not hard to imagine people writing tools between end users and Nomad itself that does these types of transformations.

Hm, that does sound like the sort of thing I'd expect the autoscaler to be doing. I'll check with @jrasell about that.

**Comment by tgross** [comment]
Having had a little time to think about this, I'm coming around to the idea that we should fix this on the "write" side, rather than on the "read" side.

Which is to say, we should adjust [`ApiJobToStructJob`](https://github.com/hashicorp/nomad/blob/v0.12.3/command/agent/job_endpoint.go#L837-L852) in the agent so that when we convert between the HTTP API's struct and Nomad's internal struct, we strip out the single region information. Because the deploymentwatcher uses the Nomad RPC and not the HTTP API, we don't have to worry about redesigning the mechanism to prevent re-registration loops, and we don't impose any sort of burden on every API consumer.

**Comment by tgross** [comment]
I've opened https://github.com/hashicorp/nomad/pull/8685 with the fix described above but need to do some manual testing of it with an enterprise build before it's ready to be reviewed.

**Comment by tgross** [comment]
Manual testing shows this works to solve the error, but introduces a new one because of the `count` interpolation. So we will need to "de-interpolate" the MRD block before sending it down the wire for the HTTP API.
