### ISSUE TITLE
Health checks for Consul Connect-enabled services without a health endpoint not possible?

### ISSUE THREAD

**Issue by shannonmcin** [hashicorp/nomad#8357]
### Nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

### Operating system and Environment details
Ubuntu 18.04 on AMD64
Consul v1.8.0

### Issue
We have a service in nomad that is Consul Connect-enabled, but the task it should health check does not provide a health HTTP endpoint. The recommended method of adding health checks to Consul Connect-enabled services seems to be an HTTP check with `expose = true`, as shown in the example jobspec posted [here](https://github.com/hashicorp/nomad/issues/7709#issuecomment-613137299) is not viable due to the lack of a health endpoint, and tcp checks are not allowed with Consul Connect-enabled services, so we expect a script health check to pass. However, a Consul Connect-enabled service with a script health check never goes healthy.

### Job file (if appropriate)
Here, "ls" is the command because it definitely should work and exit with code 0. Our minimal job file is as follows:
```
job "ubuntu" {
  datacenters = ["dc1"]
  group "ubuntu" {
    task "ubuntu" {
      config {
        image = "ubuntu:latest"
        command = "bash"
        tty = true
      }
      driver = "docker"
    }

    network {
      mode = "bridge"
      mbits = 10

      port "health" {
        to = -1
      }
    }

    service {
      name = "test-service"
      port = 8080
      address_mode = "auto"
      connect {
        sidecar_service {
        }
      }
     
      check {
        name = "test-service-health"
        type = "script"
        command = "ls"
        interval = "5s"
        timeout = "3s"
      }
    }
  }
}
```

We would like to adopt Consul Connect, but the lack of a way to health check makes that much less viable. What is the recommended way to health check Consul Connect-enabled services that do not have a health HTTP endpoint? Should script health checks work with Consul Connect-enabled services? Are there plans to enable tcp health checks?

cc @DhashS

**Comment by apollo13** [comment]
Script checks to check tasks do work (even with connect):
```
job "infra.redis" {
  datacenters = ["dc1"]

  group "redis" {

    network {
      mode = "bridge"
    }

    service {
      name = "redis"
      port = "6379"

      check {
        type = "script"
        name = "redis"
        task = "redis"
        command = "/bin/sh"
        args = ["-c", "[ \"$(redis-cli ping)\" = 'PONG' ] && exit 0; exit 1"]
        interval = "60s"
        timeout  = "5s"
      }

      connect {
        sidecar_service {}
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:5-alpine"
        command = "redis-server"
        args = ["--bind", "127.0.0.1"]
      }
    }

  }
}
```

I can only guess what your jobfile is missing, but maybe the `task` inside the check so nomad knows which task to execute against.

**Comment by shannonmcin** [comment]
@apollo13 Adding the `task` inside the `check` stanza was what I was missing; adding it caused the check to pass. Thank you!

**Comment by apollo13** [comment]
@shannonmcin maybe open a new ticket that nomad should/could error out if script checks are used in a group and no task argument is set.

**Comment by Allan-Nava** [comment]
Any example to transform this hcl to json:

```
check {
    type     = "http"
    port     = "lb"
    path     = "/health"
    interval = "5s"
    timeout  = "2s"
  }
```
