### ISSUE TITLE
Question - Nomad Connect Filter Chains

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#8359]
Is there any documentation showing how to extend the default sidecar to append filter chains?  

We are moving to Mesh and need to start applying items like https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/kafka_broker_filter
and
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter

Right now - the documentation https://www.nomadproject.io/docs/job-specification/sidecar_service#proxy doesn't really have anything actionable.   Is there any documentation that we can refer to around adding filter chains to our sidecars?

Thanks
Ian

**Comment by shoenig** [comment]
Sorry I missed this, @idrennanvmware ! If I understand correctly, you'll want to use the [proxy.config](https://www.nomadproject.io/docs/job-specification/proxy#proxy-parameters) stanza to pass in an opaque JSON blob of envoy configuration as described in [Escape-Hatch Overrides](https://www.consul.io/docs/connect/proxies/envoy#escape-hatch-overrides), and that should enable you to specify a complete Listener to use.

**Comment by tgross** [comment]
Doing some issue cleanup and it looks like this question was answered.
