### ISSUE TITLE
[ui] CSI Volume Listing has invalid Allocation Count

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#8362]
### Nomad version
Nomad 0.12.0-beta2

### Issue
The `# Allocs` column in the CSI Volume Listing page (`/ui/csi/volumes`) is not correct:
<img width="732" alt="Screen Shot 2020-07-05 at 3 54 46 PM" src="https://user-images.githubusercontent.com/1675087/86542097-f1ab4180-bed7-11ea-9465-9aab4f86ae12.png">
It is always zero. The network trace suggests this is being populated from `GET /v1/volumes`, which does not include the necessary `allocations` array in the list stub entries.

### Reproduction steps
Create a CSI volume and use it from an allocation (reach out to me for a reproduction environment).

**Comment by backspace** [comment]
The UI is expecting `GET /v1/volumes` to have `ReadAllocs` and `WriteAllocs` which it then concatenates into the synthetic `allocations` computed property on a volume model, does the endpoint return those?

<img width="751" alt="image" src="https://user-images.githubusercontent.com/43280/86601030-7349b080-bf66-11ea-9f40-0a8da7f273e1.png">

I have yet to use any of this with true volumes vs a mocked API but if the response does include the allocations it seems like it shouldn’t be too difficult to correct this.
