### ISSUE TITLE
[Docs] GCP Specific Documentation

### ISSUE THREAD

**Issue by garydevenay** [hashicorp/nomad#8367]
At the moment it seems that the documentation only covers Azure and AWS specific production nomad builds.

It would be great to get an insight in to some of the specific nuances of GCP and how we can get set up and running with a production grade Nomad/Consul/Vault cluster.

**Comment by galeep** [comment]
Thanks @garydevenay! There's some prior art here for Nomad+TF and getting started on GCP; I suspect linking that on the docs along with the other environments would be a good first step, but I'd also like to see full-fledged docs for this.

**Comment by garydevenay** [comment]
@galeep Do you have those links handy? Happy to make a start on this with a pull request as I go through my implementation.

**Comment by rossrochford** [comment]
Hi @garydevenay I've started maintaining a pre-configured Consul/Nomad cluster for GCP. I'm not affiliated with Hashicorp and it's very much a work in progress but you may find it useful: https://github.com/rossrochford/gcp-hashi-cluster

**Comment by garydevenay** [comment]
Thanks @rossrochford - I'll take a look at this!

**Comment by picatz** [comment]
👋 Hello @garydevenay! I've also been working on a Terraform module for Nomad clusters on GCP available [here](https://github.com/picatz/terraform-google-nomad). It handles configuring gossip encryption, mTLS certificate generation, enabling ACLs, and a few other pieces like deploying a load balancer. I hope that it, along with @rossrochford's awesome work, can help get you started until we create official documentation!
