### ISSUE TITLE
add task driver capabilities block to task driver docs

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#8402]
Task drivers have a [`Capabilities` function](https://www.nomadproject.io/docs/internals/plugins/task-drivers#capabilities-capabilities-error) that returns what capabilities they implement. Adding the contents of this block to the docs for each task driver as a table (or similar) would be a nice improvement to the docs so that folks don't have to go rummaging around in the source code to find that info.

**Comment by kobayashi** [comment]
I like this idea. Do I have change to do this?

**Comment by tgross** [comment]
Hi @kobayashi! Sure, feel free to open a PR!

**Comment by tgross** [comment]
Closed by #8476
