### ISSUE TITLE
Nomad UI Client view Allocation Create/Modified labels are backwards

### ISSUE THREAD

**Issue by gmichalec-pandora** [hashicorp/nomad#8408]
### Nomad version
0.11.3

### Operating system and Environment details
Debian Stretch

### Issue
When viewing a client in the nomad UI, the allocation table has columns for 'Created' and 'Modified'. These column labels are switched for the data in the columns - i.e. the data in the 'Created' column actually corresponds to the alloc ModifyTime attribute, and vice-versa.

### Reproduction steps
Nomad UI -> Click 'Clients' in sidebar -> click a client -> compare data in allocations table with API results.

![image](https://user-images.githubusercontent.com/39168929/87084109-8b2d6880-c1e2-11ea-820d-28b2dd2a4064.png)
Here you can see the create time is after the modify time, which does not make sense.

**Comment by backspace** [comment]
Thanks for the bug report! This will be fixed in the next release.
