### ISSUE TITLE
Constraint "computed class ineligible"

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#8411]
Hi folks,

We're running `Nomad 0.11.3`.

We have 3 compute node classes:
- 5 compute nodes
- 3 compute-shared nodes
- 1 compute-ops node

When we're running a job with the following "valid" constraints:

```hcl
constraint {
  attribute = "${meta.chef_role}"
  operator  = "="
  value     = "nomad-compute-ops"
}
```

It works as expected and <b>showing the right number of nodes filtered (8 here)</b>:

<details>
  <summary><b>nomad job run prod-ops-hashi-ui.hcl</b></summary>

```
==> Monitoring evaluation "74696baa"
    Evaluation triggered by job "prod-ops-hashi-ui"
    Evaluation within deployment: "d4f20357"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "74696baa" finished with status "complete"
```
</details>

<details>
  <summary><b>nomad alloc status -verbose edb17131</b></summary>

```
ID                  = edb17131-41c7-44e1-1d17-c10332d8e195
Eval ID             = 98069566-e4b8-f8c6-620e-7e8b3ecd4a50
Name                = prod-ops-hashi-ui.web[0]
Node ID             = 60a1079f-bd2c-cf8b-e72b-efbe55717310
Node Name           = nomad-compute-ops-i-0ea50bdc7c4896bab
Job ID              = prod-ops-hashi-ui
Job Version         = 18
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 2020-07-09T15:35:53-07:00
Modified            = 2020-07-09T15:36:13-07:00
Deployment ID       = d4f20357-80fb-cef1-1d68-b96f3de12f4b
Deployment Health   = healthy
Evaluated Nodes     = 9
Filtered Nodes      = 8
Exhausted Nodes     = 0
Allocation Time     = 90.12µs
Failures            = 0

Task "prod-ops-hashi-ui" is "running"
Task Resources
CPU       Memory           Disk     Addresses
0/20 MHz  4.5 MiB/500 MiB  300 MiB  http: 10.82.43.205:24458

Task Events:
Started At     = 2020-07-09T22:35:58Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type        Description
2020-07-09T15:35:58-07:00  Started     Task started by client
2020-07-09T15:35:54-07:00  Driver      Downloading image
2020-07-09T15:35:54-07:00  Task Setup  Building Task Directory
2020-07-09T15:35:53-07:00  Received    Task received by client

Placement Metrics
  * Class "compute-shared": 3 nodes excluded by filter
  * Class "compute": 5 nodes excluded by filter
  * Constraint "${meta.chef_role} = nomad-compute-ops": 8 nodes excluded by filter
Node                                  binpack  job-anti-affinity  node-affinity  node-reschedule-penalty  final score
60a1079f-bd2c-cf8b-e72b-efbe55717310  0.478    0                  0              -1                       -0.261
```

</details>

Now if we put in an invalid constraint:

```hcl
constraint {
  attribute = "${CONSTRAINT_THAT_DOES_NOT_EXIST.meta.chef_role}"
  operator  = "="
  value     = "nomad-compute-ops"
}
```

When inspecting the allocation, the number of nodes filtered <b>does not make sense as it's still showing 8 nodes</b> and <b>mentions a "class ineligible"</b>:

```
nomad job run prod-ops-hashi-ui.hcl
==> Monitoring evaluation "7f05f8eb"
    Evaluation triggered by job "prod-ops-hashi-ui"
    Evaluation within deployment: "98d0065c"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "7f05f8eb" finished with status "complete" but failed to place all allocations:
    Task Group "web" (failed to place 1 allocation):
      * Class "compute-shared": 3 nodes excluded by filter
      * Class "compute": 5 nodes excluded by filter
      * Class "compute-ops": 1 nodes excluded by filter
      * Constraint "${CONSTRAINT_THAT_DOES_NOT_EXIST.meta.chef_role} = nomad-compute-ops": 8 nodes excluded by filter
      * Constraint "computed class ineligible": 1 nodes excluded by filter
    Evaluation "768527a5" waiting for additional capacity to place remainder
```

1. Why are 8 nodes filtered by this constraint and not 9? It seems like all nodes should be filtered out the same way.
1. Why is it showing "computed class ineligible" for the remaining node?

Thanks in advance!

**Comment by tgross** [comment]
Hi @evandam! When you added the new invalid constraint, did you remove the previous constraints as well?

Keep in mind here that Nomad does a bunch of optimizations to make sure it doesn't have to evaluate every node in the cluster, because that gets very expensive as cluster sizes go up. So if the scheduler examines a constraint and can discard the node without evaluating other constraints, it's going to optimize for not doing the extra work.

`nomad eval status -verbose 768527a5` may have more details. If at least 1 allocation was placed, you'd also be able to check out the `-verbose` status of the job/alloc to get the placement metrics (currently we don't expose these in `eval status` but I think it'd be great if we could). And if you can provide all the constraints for the jobspec, I might be able to walk you through the scheduler scenario that results in this.

**Comment by scalp42** [comment]
@tgross only one constraint at a time meaning that yes it was removed.

There are no other constraints.

**Comment by scalp42** [comment]
@tgross why did you close this issue? It's still happening.

**Comment by tgross** [comment]
Sorry about that @scalp42. I'd asked for more details [back in July](https://github.com/hashicorp/nomad/issues/8411#issuecomment-656659174) and didn't get a response back. We can reopen if you have those details.
