### ISSUE TITLE
Exec in to container (from UI) always goes to the last allocation

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#8422]
### Nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

### Operating system and Environment details
PhotonOS3

### Issue
When using the UI in Nomad 0.11.3, in a job with 3 groups (with a count of 3), when "exec" in to the container it always goes to the last one.

### Reproduction steps
Create a job with a group with a count of > 1.   Place a unique environment variable in each one via the job template.   Use the UI to exec in to to the container - the variables are always the "last" one.  See screenshots.  Whats interesting is that the EXEC window used to show 3 options to log in (one for each instance of the group).   Now it always shows 1, which I assume is the last one (see the nav bar on the final screenshot).  Note I was on the client with the IP 192.168.50.92 but the exec took me to the container on 192.168.50.93

<img width="738" alt="Screen Shot 2020-07-12 at 1 21 36 PM" src="https://user-images.githubusercontent.com/46198537/87252650-c29a5000-c442-11ea-88de-68e6354af963.png">
<img width="956" alt="Screen Shot 2020-07-12 at 1 21 50 PM" src="https://user-images.githubusercontent.com/46198537/87252651-c4fcaa00-c442-11ea-992c-a1a6fc54c194.png">
<img width="998" alt="Screen Shot 2020-07-12 at 1 21 59 PM" src="https://user-images.githubusercontent.com/46198537/87252653-c6c66d80-c442-11ea-824c-eccf86887c82.png">
<img width="971" alt="Screen Shot 2020-07-12 at 1 22 25 PM" src="https://user-images.githubusercontent.com/46198537/87252654-c7f79a80-c442-11ea-971f-9ded9ee74569.png">

**Comment by rkettelerij** [comment]
Good catch. This is weird indeed. To clarify: It no only happens when you click the Exec button on the job page. When you select a concrete allocation (you're on the allocation page) and use the "Exec" button you always end up in the last allocation (not the selected allocation).

**Comment by idrennanvmware** [comment]
@rkettelerij - I just checked and it seems to be the same regardless of which level I exec from 

Job
Group
Task

all always go to the same container

**Comment by rkettelerij** [comment]
@idrennanvmware Indeed

**Comment by backspace** [comment]
Thanks for letting us know about this and the thorough report!
