### ISSUE TITLE
Connect jobs failing in 12.0

### ISSUE THREAD

**Issue by t0nyhays** [hashicorp/nomad#8423]
When I upgraded my cluster to 12.0, all of my Connect jobs began to fail.  I started messing around with syntax of the job definition, but couldn't get it to work.

####  Nomad Version

Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

#### OS
Centos 7 and Ubunto 20.04

### Issue
After upgrade to nomad 12.0, allocations fail because of a "missing network" constraint.

### Reproduction Steps

To take any environmental variables out of the mix, I followed the steps outlined on (https://www.nomadproject.io/docs/integrations/consul-connect) exactly.  The only difference between the two runs was the version of the nomad binary running in -dev-connect

#### "nomad job plan connect.nomad"   -   Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

+ Job: "countdash"
+ Task Group: "api" (1 create)
  + Task: "connect-proxy-count-api" (forces create)
  + Task: "web" (forces create)

+ Task Group: "dashboard" (1 create)
  + Task: "connect-proxy-count-dashboard" (forces create)
  + Task: "dashboard" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 connect.nomad  -  

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

#### "nomad job plan connect.nomad" - Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

+ Job: "countdash"
+ Task Group: "api" (1 create)
  + Task: "connect-proxy-count-api" (forces create)
  + Task: "web" (forces create)

+ Task Group: "dashboard" (1 create)
  + Task: "connect-proxy-count-dashboard" (forces create)
  + Task: "dashboard" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "api" (failed to place 1 allocation):
    * Constraint "missing network": 1 nodes excluded by filter

  Task Group "dashboard" (failed to place 1 allocation):
    * Constraint "missing network": 1 nodes excluded by filter

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 connect.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.

**Comment by nickethier** [comment]
Hey @t0nyhays I think I fixed this in #8407 sorry for the issue. We should be cutting a big fix release soon.

**Comment by spuder** [comment]
I am also seeing this issue `Constraint missing network filtered 2 nodes`

**Comment by shoenig** [comment]
I believe it should also be possible to workaround this by manually configuring `network_interface` on the Nomad Client. Before, Nomad leaned hard on the simple network model for the Connect integration. With multi-interface networking in Nomad v0.12+ we missed an edge case here where we don't detect an interface with multiple default routes as usable by default (hence the scheduling error).

**Comment by spuder** [comment]
I'm running 0.12 on the nomad servers, but still running 0.11 on the clients/agents. I tried adding the following to the client/agent config with no change in behavior. I suspect that running different versions on the servers as the agents makes the work around not valid. 

```
"client": {
  "network_interface": "ens3"
}
```

**Comment by t0nyhays** [comment]
I pushed out 12 to all servers(3) and all clients(10).  Added `"client": { "network_interface": "bond0"` to all clients.  Job w/o connect stanza worked fine.  Job with connect stanza failed:
`'network: no addresses availale for "" network':10`.  That is a typo in the error message, not a copy paste thing.

**Comment by t0nyhays** [comment]
2nd workaround test:
On a single node I added:
`"client":{"enabled":true,"host_network":[{"public":[{"cidr":"10.224.190.0/23","reserved_ports":"22,80"}]}],"meta":[{"rack":"D1","workload":"generic"}],"network_interface":"bond0"}`

Restarted nomad.

Added host_network to job description:

`network {
      mode = "bridge"
      port "grafana" {
        to = 3000
        host_network = "public"
      }`

Nomad job plan failed again, this time with:
`{'NodesEvaluated': 10, 'NodesFiltered': 9, 'NodesAvailable': {'sim': 0, 'dc1': 0, 'stage': 0, 'prod': 10}, 'ClassFiltered': None, 'ConstraintFiltered': {'missing host network "public" for port "grafana"': 9}, 'NodesExhausted': 1, 'ClassExhausted': None, 'DimensionExhausted': {'network: no addresses availale for "" network': 1}`

Does this help at all?  I will probably set back to 11.3 unless you can think of another potential fix, other than the bug fix roll.

**Comment by spuder** [comment]
Is there an ETA for when this will be released? 0.12 is completely unusable and the work arounds aren't viable.

**Comment by shoenig** [comment]
Yeah sorry we don't have an ETA for rolling out the fix - it might be sooner than later since we're coordinating around the recent Go security fix but nothing exact. Definitely hold off for now if you can. 

In the mean time I'm trying to incorporate this condition in some tests to make sure we don't run into something like this again. 

@t0nyhays do you mind sharing the output of
`curl -s "localhost:4646/v1/node/<nodeID>" |  jq '.NodeResources | {Networks, NodeNetworks}'` (with Nomad 0.12)? Feel free to redact IP addresses, but label them as `public` or `private` - so we can make sure there isn't something else funny going on.

**Comment by t0nyhays** [comment]
@shoenig Sorry but I set my cluster back to 0.11.3 and have a deadline to stand up some new services.  I will potentially have some time next week to get you the output.  Thanks for working on this one!

**Comment by chrisboulton** [comment]
@shoenig If it's helpful, we just slammed into this and here's the output of the above - right now we don't have any of the workarounds that @t0nyhays attempted in place (should that be specifically what you're looking for).

```
{
  "Networks": [
    {
      "Mode": "host",
      "Device": "ens4",
      "CIDR": "private/32",
      "IP": "private",
      "MBits": 1000,
      "ReservedPorts": null,
      "DynamicPorts": null
    }
  ],
  "NodeNetworks": null
}
```

**Comment by jharley** [comment]
I am now getting a warning (not failure) when doing plans, the jobs do get scheduled and run:

```
$ nomad plan myservice.nomad
[ ... ]
Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "myservice" (failed to place 1 allocation):
    * Resources exhausted on 2 nodes
    * Dimension "network: no addresses available for \"\" network" exhausted on 2 nodes
```

Nomad 0.12.3, CNI plugins 0.8.6, Ubuntu 20.04, Docker 19.03.12

**Comment by spuder** [comment]
We just tried to upgrade to nomad 0.12.4 again but had to roll back to 0.11 because of this issue. All nomad connect jobs fail with error: 

```
Get "http://10.46.24.2:22489/actuator/health": dial tcp 10.46.24.2:22489: connect: connection refused
```

Its not obvious that there is a problem until jobs are resubmitted, or we reboot a nomad worker agent.

**Comment by CarelvanHeerden** [comment]
Getting the same as @jharley, using Nomad 0.12.4, on Ubuntu 18.04.

**Comment by nickethier** [comment]
Hey folks, this issue turned a bit into a dumping group for connect issues. From my read of the history it looks like #8407 should have solved the original issue that @t0nyhays posted about the "no addresses available" error. 

Thanks @chrisboulton for excellent write up and continuing updates. It looks like you're experiencing an issue now where the bridge kernel module is loaded just in time for use which breaks Nomad's fingerprinting of the bridge network (since it checks the currently loaded modules).

**Comment by ibayer** [comment]
I'm exactly in the same situation as described in https://github.com/hashicorp/nomad/issues/8423#issuecomment-695110189
by @spuder .

> Updated to nomad 0.12.5 and consul 1.8.4, problem persists

I'm on the same versions.

**Comment by apollo13** [comment]
@chrisboulton & @nickethier  Rgearding
> The first issue, with bridging being unavailable for our Connect tasks is/was caused by the bridge kernel module being unavailable at Nomad startup time, and changes to the fingerprinting code here.

I think we are running into similar things. Seems to be a race condition. After a crash of our whole cluster, one job had one allocation blocked due to "missing network". Draining that node and stopping nomad, docker and restarting them allowed a reschedule. Is there a ticket for this already?

**Comment by apollo13** [comment]
Also weirdly enough:
```
Nov 03 08:44:32 nomad03 dockerd[500]: time="2020-11-03T08:44:32.688453474+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Nov 03 08:44:32 nomad03 dockerd[500]: time="2020-11-03T08:44:32.760807915+01:00" level=info msg="Loading containers: done."
Nov 03 08:44:32 nomad03 dockerd[500]: time="2020-11-03T08:44:32.949868942+01:00" level=info msg="Docker daemon" commit=4484c46d9d graphdriver(s)=overlay2 version=19.03.13
Nov 03 08:44:32 nomad03 dockerd[500]: time="2020-11-03T08:44:32.963466533+01:00" level=info msg="Daemon has completed initialization"
Nov 03 08:44:32 nomad03 dockerd[500]: time="2020-11-03T08:44:32.995203542+01:00" level=info msg="API listen on /var/run/docker.sock"
Nov 03 08:44:32 nomad03 systemd[1]: Started Docker Application Container Engine.

....

Nov 03 08:44:33 nomad03 nomad[499]:     2020-11-03T08:44:25.905+0100 [WARN]  client.fingerprint_mgr: failed to detect bridge kernel module, bridge network mode disabled: error="could not detect kernel module bridge, could not detect kerne
```

As you can see, timing wise the bridge should probably already been have loaded (docker already started successfully and logged as much)

**Comment by jorgemarey** [comment]
Hi @shoenig, just found out about this when upgrading our cluster 0.12.X (from 0.11.3).

When the servers are in 0.12.X and the clients remain in 0.11.3 we're getting this error when trying to deploy connect jobs:
```
    * Constraint "missing network": 3 nodes excluded by filter
```

Seems that they cant find any node able to run the jobs.
Following up on this I saw that old nodes doesn't have bridge information on the NodeResources but new nodes (0.12.X) does have.

```
# 0.11 node
➜  nomad ✗ curl -k -X GET -H "X-Nomad-Token: ${NOMAD_TOKEN}" "${NOMAD_ADDR}/v1/node/af81f181-c3dc-9187-0992-128e9ea70a59" | jq '.NodeResources | {Networks, NodeNetworks}'
{
  "Networks": [
    {
      "Mode": "",
      "Device": "eth0",
      "CIDR": "10.10.37.109/32",
      "IP": "10.10.37.109",
      "MBits": 1000,
      "DNS": null,
      "ReservedPorts": null,
      "DynamicPorts": null
    }
  ],
  "NodeNetworks": [
    {
      "Mode": "",
      "Device": "eth0",
      "MacAddress": "",
      "Speed": 1000,
      "Addresses": [
        {
          "Family": "",
          "Alias": "default",
          "Address": "10.10.37.109",
          "ReservedPorts": "",
          "Gateway": ""
        }
      ]
    }
  ]
}
# 0.12 node
➜  nomad ✗ curl -k -X GET -H "X-Nomad-Token: ${NOMAD_TOKEN}" "${NOMAD_ADDR}/v1/node/e33d252c-bacd-f8f5-0f3d-fcaa9efe4f17" | jq '.NodeResources | {Networks, NodeNetworks}'
{
  "Networks": [
    {
      "Mode": "bridge",
      "Device": "",
      "CIDR": "",
      "IP": "",
      "MBits": 0,
      "DNS": null,
      "ReservedPorts": null,
      "DynamicPorts": null
    },
    {
      "Mode": "host",
      "Device": "eth0",
      "CIDR": "100.88.66.99/32",
      "IP": "100.88.66.99",
      "MBits": 1000,
      "DNS": null,
      "ReservedPorts": null,
      "DynamicPorts": null
    },
    {
      "Mode": "host",
      "Device": "eth0",
      "CIDR": "100.88.66.99/32",
      "IP": "100.88.66.99",
      "MBits": 1000,
      "DNS": null,
      "ReservedPorts": null,
      "DynamicPorts": null
    }
  ],
  "NodeNetworks": [
    {
      "Mode": "bridge",
      "Device": "",
      "MacAddress": "",
      "Speed": 0,
      "Addresses": null
    },
    {
      "Mode": "host",
      "Device": "eth0",
      "MacAddress": "",
      "Speed": 1000,
      "Addresses": [
        {
          "Family": "",
          "Alias": "default",
          "Address": "100.88.66.99",
          "ReservedPorts": "",
          "Gateway": ""
        }
      ]
    },
    {
      "Mode": "host",
      "Device": "eth0",
      "MacAddress": "",
      "Speed": 1000,
      "Addresses": [
        {
          "Family": "",
          "Alias": "default",
          "Address": "100.88.66.99",
          "ReservedPorts": "",
          "Gateway": ""
        }
      ]
    }
  ]
}
```

I saw in the code that between 0.11 and 0.12 this file: https://github.com/hashicorp/nomad/blob/master/client/fingerprint/bridge_linux.go is added adding the brigde information to the NodeResources and in the scheduler a new NetworkChecker was added to verify client networks.

https://github.com/hashicorp/nomad/blob/2fce235f761ac964c1f91d7f78f7507dd23989da/scheduler/feasible.go#L319-L327

It seems that, with this changes, while using nodes in 0.11 we can't run new connect jobs, and I guess that allocations running won't be able to reeschedule to other nodes if something fails.

Is there anything we can do to sort this out? Should we upgrade the nodes first (we add new instances with the new version)? 
I thought about modifying the code and add the following to the NetworkChecker (to allow the previous behaviour). But I don't know if this has any other implications.

```
 func (c *NetworkChecker) Feasible(option *structs.Node) bool {
        if !c.hasNetwork(option) {
-               c.ctx.Metrics().FilterNode(option, "missing network")
-               return false
+               cstr, _ := version.NewConstraint("<= 0.11")
+               nodeVersion, _ := version.NewVersion(option.Attributes["nomad.version"])
+               if !cstr.Check(nodeVersion) {
+                       c.ctx.Metrics().FilterNode(option, "missing network")
+                       return false
+               }
        }
 
        if c.ports != nil {
```

**Comment by shoenig** [comment]
The `-beta3` that went out yesterday contains #9299 which should fix the fingerprinting issue. Can you give that a try, @jorgemarey ?

**Comment by ibayer** [comment]
@shoenig 
I just tested with `v0.12.8` and the issue still persists (I can't test beta).

**Comment by jorgemarey** [comment]
> The `-beta3` that went out yesterday contains #9299 which should fix the fingerprinting issue. Can you give that a try, @jorgemarey ? 
> 

Hi @shoenig. I saw that PR, but that, for what I could see fixes the fingerprint on the client side. My problem is that when using a server in 0.12 with clients on 0.11 job with connect can't be deployed because those nodes don't expose the bridge in the NodeResources and the server is checking that the node has the bridge Network.

This should be fixed on the server side making it compatible during the upgrade process.

I don't know if I'm explaining my problem correctly.

**Comment by shoenig** [comment]
Ahh sorry I understand now @jorgemarey , thanks. I'll reopen this and look into it.

**Comment by jorgemarey** [comment]
> Ahh sorry I understand now @jorgemarey , thanks. I'll reopen this and look into it. 

Thanks @shoenig. My connect jobs works fine on 0.12.8 clients with the bridge module loaded previous to nomad start. 

For me the only problem is during the upgrade from 0.11 to 0.12. As we first upgrade the servers and then the clients. 

I was able to make it work by applying the diff in my previous comment (https://github.com/hashicorp/nomad/issues/8423#issuecomment-726678139) and deploy the servers in 0.12 with that patch. With that, even with the servers on 0.12 and clients in 0.11 the connect jobs where scheduled correctly.

**Comment by ibayer** [comment]
It's still not clear to me if `v0.12.8` contains the fix.
Is there an easy why to check this?
