### ISSUE TITLE
resource stanzas are completely are ignored when using json format?

### ISSUE THREAD

**Issue by arianvp** [hashicorp/nomad#8424]
### Nomad version
```
Nomad v0.11.3
```

### Operating system and Environment details
NixOS 20.03

### Issue
When using JSON instead of HCL, Nomad seems to ignore the `resource` stanza completely

### Reproduction steps
`nomad run reproducer.json`

#### Expected behaviour
Nomad should reject the job because the `resource` stanza is invalid; and if not
at least see the `resource.network.port.postgres = {}` and set `NOMAD_PORT_postgres` 

#### Actual behaviour
Nomad accepts the job, and `NOMAD_PORT_postgres` is not set. Seems like the parser
completely ignores the `resource` stanza when using `json`

### Job file (if appropriate)

```
{
  "job": {
    "webshop": {
      "datacenters": [
        "dc1"
      ],
      "group": {
        "database": {
          "count": 1,
          "task": {
            "main": {
              "config": {
                "command": "env",
                "image": "alpine"
              },
              "driver": "exec",
              "resources": {
                "lol": {},
                "resources do not work": {},
                "network": {
                  "this is ignored": {},
                  "port": {
                    "postgres": {}
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by arianvp** [comment]
Something extremely buggy is going on here.
As soon as you add the `cpu` field to the `json` blob, it **does** start parsing the other fields....

```
{
  "job": {
    "webshop": {
      "datacenters": [
        "dc1"
      ],
      "group": {
        "database": {
          "count": 1,
          "task": {
            "main": {
              "config": {
                "command": "env",
                "image": "alpine"
              },
              "driver": "docker",
              "resources": {
                "lol": {},
                "cpu": 0,
                "resources do not work": {},
                "network": {
                  "this is ignored": {},
                  "port": {
                    "postgres": {}
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

```
nomad run repro.json 
Error getting job struct: Error parsing job file from repro.json: error parsing 'job': 2 errors occurred:
	* group: 'database', task: 'main', resources -> resources -> invalid key: lol
	* group: 'database', task: 'main', resources -> resources -> invalid key: resources do not work

```

**Comment by arianvp** [comment]
The `cpu` field does get parsed; However the `network` section still seems to be ignored.

No `NOMAD_PORT_postgres` environment variable present, but the job does correctly set `NOMAD_CPU_LIMIT=20`


```
{
  "job": {
    "webshop": {
      "datacenters": [
        "dc1"
      ],
      "group": {
        "database": {
          "count": 1,
          "task": {
            "main": {
              "config": {
                "command": "env",
                "image": "alpine"
              },
              "driver": "docker",
              "resources": {
                "cpu": 20,
                "network": {
                  "port": {
                    "postgres": {}
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

This leads to this output. Note No `NOMAD_PORT_postgres` present
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=546241676b38
NOMAD_ALLOC_DIR=/alloc
NOMAD_ALLOC_ID=d982c747-a34b-428d-95d2-0cc9c2f61273
NOMAD_ALLOC_INDEX=0
NOMAD_ALLOC_NAME=webshop.database[0]
NOMAD_CPU_LIMIT=20
NOMAD_DC=dc1
NOMAD_GROUP_NAME=database
NOMAD_JOB_NAME=webshop
NOMAD_MEMORY_LIMIT=300
NOMAD_NAMESPACE=default
NOMAD_REGION=global
NOMAD_SECRETS_DIR=/secrets
NOMAD_TASK_DIR=/local
NOMAD_TASK_NAME=main
HOME=/root
```

**Comment by shoenig** [comment]
Thanks for reporting, @arianvp ! I suspect this is an artifact of the dual support we provide for both `HCL` and `JSON` formats - something along the lines of erroneously assuming a nil stanza if none of its fields are set before being passed along for validation. There's a good chance this and other bugs in this area will be fixed in the upcoming [HCLv2](https://github.com/hashicorp/nomad/issues/7220) conversion.

**Comment by arianvp** [comment]
But not having entire features work in the JSON format seems like a really bad regression. 

Isn't this something we should fix even before migrating to a new config format backend?

**Comment by arianvp** [comment]
Ah i see what you mean with the nil stanza remark now. I'll see what happens if I set the `port` to something else than `{}`

**Comment by arianvp** [comment]
@shoenig is there any workaround for this?   Is there a way to trick nomad into  not thinking `{} == null` ?  I tried setting a bogus `k/v` but that doesn't work as nomad rejects unknown values. 

  Given "empty map" is used as a semantic value a lot in many places in nomad, im a bit puzzled  nobody else is running into this.   Am I really the only one using the (documented) `json` support?

**Comment by arianvp** [comment]
@shoenig I tried working around by doing:

```json
              "resources": {
                "network": {
                  "port": {
                    "http": {
                      "to": "-1"
                    }
                  }
                }
              },
```

(because `to` is a valid value for the `port` stanza)

but the stanza is still ignored by nomad! No port is being allocated. So I think your running theory is not correct

**Comment by arianvp** [comment]
I was able to get it to work by _explicitly_ setting the `mode` of the `network` stanza


```
              "resources": {
                "network": {
                  "mode": "host",
                  "port": {
                    "http": {
                    }
                  }
                }
              },
```

This works fine!

so it seems the `network` stanza is ignored If and only if `mode` is not present.  I guess that's the actual bug

**Comment by arianvp** [comment]
I see task based network resources have actually been deprecated.. i'll see if the bug persists when you define these at the `group` level

**Comment by tgross** [comment]
Doing a bit of issue cleanup and I can confirm this is no longer an issue. The networking was all moved out of the `Resources` task block to the group's `Networks` block. As a demonstration, here's a job using a group network:

<details><summary>jobspec</summary>

```hcl
job "httpd" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    service {
      port = "www"
    }

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}
```

</details>

After submitting, I can see the `Networks` block on the group:

```
$ nomad job inspect httpd | jq '.Job.TaskGroups[0].Networks'
[
  {
    "CIDR": "",
    "DNS": null,
    "Device": "",
    "DynamicPorts": [
      {
        "HostNetwork": "default",
        "Label": "www",
        "To": 8001,
        "Value": 0
      }
    ],
    "Hostname": "",
    "IP": "",
    "MBits": 0,
    "Mode": "bridge",
    "ReservedPorts": null
  }
]
```

Now I'll dump the JSON to a file, edit it to change the port label, and resubmit via the HTTP API:

```
$ nomad job inspect httpd | jq . > /tmp/job.json

$ sed -i '' 's~www~web~g' /tmp/job.json

$ cat /tmp/job.json | nomad operator api -X POST '/v1/job/httpd'
{"EvalCreateIndex":25,"EvalID":"0275d0b0-9e37-4e8f-a89b-a93762cdbe1a","Index":25,"JobModifyIndex":25,"KnownLeader":false,"LastContact":0,"NextToken":"","Warnings":""}%
```

Now if I inspect the job I can see the `Networks` block has been updated as expected:

```
$ nomad job inspect httpd | jq '.Job.TaskGroups[0].Networks'
[
  {
    "CIDR": "",
    "DNS": null,
    "Device": "",
    "DynamicPorts": [
      {
        "HostNetwork": "default",
        "Label": "web",
        "To": 8001,
        "Value": 0
      }
    ],
    "Hostname": "",
    "IP": "",
    "MBits": 0,
    "Mode": "bridge",
    "ReservedPorts": null
  }
]
```
