### ISSUE TITLE
Placement options for network stanza are incomplete

### ISSUE THREAD

**Issue by rberlind** [hashicorp/nomad#8428]
The placement options for the network stanza of the Nomad job specification file are incomplete at the top of https://www.nomadproject.io/docs/job-specification/network.

It currently only shows the task group level which was added in Nomad 0.10.  But it can also be used under the resources stanza of a task as actually shown in the document.

Compare https://www.nomadproject.io/docs/job-specification/device to see how device ls listed under job -> group -> task -> resources -> device

So, network should also be listing  job -> group -> task -> resources -> network.

**Comment by nickethier** [comment]
Hey @rberlind 

I removed these recently. We're deprecating the usage of the network stanza inside a task resources stanza. Tasks should be updated to use the group network stanza. If you have any issues or find any example that still reference this usage let me know. Thanks!

**Comment by rberlind** [comment]
OK, @nickethier :  Note that https://www.nomadproject.io/docs/drivers/docker#allocating-ports and dproject.io/docs/drivers/docker#using-the-port-map will need updating.

Also, does this change have any impact on Nomad Enterprise resource quotas?  Currently, those include CPU, Memory, and Network.  But if we are moving network out of resources, that raises the question whether we will still consider network a "resource" that can be limited with resource quotas.

For instance, running `nomad quota status dev` where "dev" is a resource quota will return something like this:
```
Name        = dev
    Description = dev quota
    Limits      = 1
    Quota Limits
    Region  CPU Usage  Memory Usage  Network Usage
    global  0 / 2300   0 / 4100      - / inf
```

Note in this case I had not included a quota for network since my HCL for the dev resource quota was this:
```
name = "dev"
description = "dev quota"

limit {
    region = "global"
    region_limit {
        cpu = 2300
        memory = 4100
    }
}
```
