### ISSUE TITLE
Prometheus format is not returning some metrics, like total_blocked 

### ISSUE THREAD

**Issue by cdwiegand** [hashicorp/nomad#8438]
### Nomad version
Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

### Operating system and Environment details
Ubuntu Linux 18.04 (Bionic) x64

### Issue
When I access /v1/metrics?format=prometheus it appears to be missing some stats that just /v1/metrics returns, such as total blocked allocations (nomad.broker.total_blocked and nomad.client.allocations.running in particular, documented at https://www.nomadproject.io/docs/telemetry), which would be very valuable in a prometheus + grafana monitoring solution.

**Comment by notnoop** [comment]
Thanks @cdwiegand for reaching out.  You may need to enable Prometheus detection as it's not enabled by default.  You can use the [`prometheus_metrics`](https://www.nomadproject.io/docs/configuration/telemetry#prometheus) in your agent configuration, by adding the following:

```hcl
telemetry {
  prometheus_metrics = true
}
```

I have confirmed that the metrics weren't available without this flag.  Closing it for now but please re-open if that's not the case.
