### ISSUE TITLE
Unexplained failure to elect a leader with 2 nodes

### ISSUE THREAD

**Issue by davidr912** [hashicorp/nomad#8447]
### Nomad version
0.12.0

### Operating system and Environment details
Ubuntu 18.04/Bionic

### Issue
* `bootstrap_expect` is 2 on both servers
* ACL disabled
* TLS enabled but `verify_https_client` and `verify_server_hostname` are false
* Both servers expose 4646 - 4648/TCP and 4648/UDP on their public IP addresses (and these ports are reachable on both ends)
* Both servers set to use `advertise` of their public IP for `rpc` `serf` and `http`
* [This setup is insecure as it stands but I'm trying to root out the cause of the problem]

For some reason the result is always that the logs of both servers acknowledge each other's existence, but a leader is never elected

The log seems to drop straight from serf member join back to "no known peers, aborting election"

This is the log for **europe** acknowledging server **singapore** has been added

The logs on both sides are almost identical except singapore is in DC production

```
==> Loaded configuration from /etc/nomad.d/nomad.hcl, /etc/nomad.d/server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:
       Advertise Addrs: HTTP: 52.47.48.220:4646; RPC: 52.47.48.220:4647; Serf: 52.47.48.220:4648
            Bind Addrs: HTTP: 0.0.0.0:4646; RPC: 0.0.0.0:4647; Serf: 0.0.0.0:4648
                Client: false
             Log Level: DEBUG
                Region: europe (DC: staging)
                Server: true
               Version: 0.12.0
==> Nomad agent started! Log data will stream in below:
13:35:52.755Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/nomad/plugins
13:35:52.756Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/opt/nomad/plugins
13:35:52.756Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
13:35:52.756Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
13:35:52.756Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
13:35:52.756Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
13:35:52.756Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
13:35:52.756Z [INFO]  agent: detected plugin: name=nvidia-gpu type=device plugin_version=0.1.0
13:35:52.772Z [INFO]  nomad.raft: initial configuration: index=0 servers=[]
13:35:52.772Z [INFO]  nomad.raft: entering follower state: follower="Node at 52.47.48.220:4647 [Follower]" leader=
13:35:52.773Z [WARN]  nomad: memberlist: Binding to public address without encryption!
13:35:52.773Z [INFO]  nomad: serf: EventMemberJoin: ip-172-16-10-12.europe 52.47.48.220
13:35:52.773Z [INFO]  nomad: starting scheduling worker(s): num_workers=2 schedulers=[service, batch, system, _core]
13:35:52.774Z [INFO]  nomad: serf: Attempting re-join to previously known node: ip-172-16-10-94.singapore: 18.138.167.5:4648
13:35:52.775Z [DEBUG] nomad: lost contact with Nomad quorum, falling back to Consul for server list
13:35:52.775Z [ERROR] nomad: error looking up Nomad servers in Consul: error="server.nomad: unable to query Consul datacenters: Get "http://127.0.0.1:8500/v1/catalog/datac
13:35:52.775Z [INFO]  nomad: adding server: server="ip-172-16-10-12.europe (Addr: 52.47.48.220:4647) (DC: staging)"
13:35:52.939Z [DEBUG] nomad: memberlist: Initiating push/pull sync with: 18.138.167.5:4648
13:35:53.104Z [INFO]  nomad: serf: EventMemberJoin: ip-172-16-10-94.singapore 18.138.167.5
13:35:53.104Z [INFO]  nomad: serf: Re-joined to previously known node: ip-172-16-10-94.singapore: 18.138.167.5:4648
13:35:53.104Z [INFO]  nomad: adding server: server="ip-172-16-10-94.singapore (Addr: 18.138.167.5:4647) (DC: production)"
13:35:54.149Z [WARN]  nomad.raft: no known peers, aborting election
13:36:01.775Z [DEBUG] nomad: lost contact with Nomad quorum, falling back to Consul for server list
13:36:02.997Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:03.142Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:08.137Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:08.504Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:13.243Z [DEBUG] http: request complete: method=GET path=/v1/agent/monitor?log_json=false&log_level=trace&node_id=&server_id= duration=17.997417174s
13:36:13.614Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:13.830Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:19.940Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:20.320Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:30.213Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
13:36:30.514Z [ERROR] worker: failed to dequeue evaluation: error="No cluster leader"
```

```

Name                       Address       Port  Status  Leader  Protocol  Build   Datacenter  Region
ip-172-16-10-12.europe     52.47.48.220  4648  alive   false   2         0.12.0  staging     europe
ip-172-16-10-94.singapore  18.138.167.5  4648  alive   false   2         0.12.0  production  singapore

Error determining leaders: 2 errors occurred:
        * Region "singapore": Unexpected response code: 500 (No cluster leader)
        * Region "europe": Unexpected response code: 500 (rpc error: No cluster leader)
```

**Comment by notnoop** [comment]
Hi @davidr912 !  Thanks for reaching out!  `bootstrap_expect` indicates how many servers are expected in each region.  In Nomad architecture, each region acts independently and must form a self sufficient cluster, with an option to federate them so each server can route requests to servers in other regions.  In your setup, you'd want `bootstrap_expect=1`.  You can view the [Nomad Internal Architecture](https://www.nomadproject.io/docs/internals/architecture#high-level-overview) for more info.

Also in a production setting, we recommend running with 3 or 5 servers in each region, for [failure tolerance](https://www.nomadproject.io/docs/internals/consensus#deployment_table).  With `bootstrap_expect` of 2, if the connection between them drop or a server goes down, the cluster will be inoperable.

**Comment by davidr912** [comment]
> in each region. In Nomad architecture, each region acts independently and must form a self sufficient cluster, with an option to federate them so each server can route requests to servers in other regions. 

Ahhh, that makes a lot of sense! I would say that maybe the docs could be a little more explicit about saying this is per region - at least [here](https://www.nomadproject.io/docs/configuration/server#bootstrap_expect) it doesn't make that clear

Just to check too :

* Since its per region, does that mean it is actually correct that they will nominate themselves both as leaders? (I had expect 1 at some point but thought the servers were ignoring each other due to immediately electing themselves leader)

* Is port 4646 actually required at all for server to server communication? I've seen quite a few conflicting things about this, but the diagram here implies that only 4647 and 4648 should be required for this to work:

<img src="https://www.nomadproject.io/img/nomad_fault_tolerance.png"/>

> Also in a production setting, we recommend running with 3 or 5 servers in each region, for failure tolerance. 

Understood - planning to have 2+ in each region, this was just the starting point for ensuring WAN comms worked

**Comment by notnoop** [comment]
Thanks - it will make sense to update the `bootstrap_expect` doc - thanks for raising it.

> Since its per region, does that mean it is actually correct that they will nominate themselves both as leaders? (I had expect 1 at some point but thought the servers were ignoring each other due to immediately electing themselves leader)

Correct.  Each region is independent and a single leader is established in each region to coordinate the workloads in that region.  Servers don't need to coordinate across regions and merely forward RPC requests as needed in OSS - Nomad Enterprise offer more sophisticated support, like [multi-region deployments](https://www.hashicorp.com/blog/hashicorp-nomad-multi-cluster-deployment/).

> Is port 4646 actually required at all for server to server communication? I've seen quite a few conflicting things about this, but the diagram here implies that only 4647 and 4648 should be required for this to work:

Generally all internal communications go through 4647/4648 - with 4646 serving the API consumed by CLI and API consumers/tools.

The only exception I'm aware if in the handling of [ephemeral disk with `migrate=true`](https://www.nomadproject.io/docs/job-specification/ephemeral_disk#ephemeral_disk-parameters) - if an alloc with ephemeral disk with migrate=true fails and is rescheduled, the client running the new alloc will use 4646 to fetch the alloc dir from the failed client.  This is done for best-effort cases, so if the port isn't available, the alloc will run on new client without the data.

Please let us know the docs with conflicting info and we'll update them as well.  Hope that helps!
