### ISSUE TITLE
LogConfig log storage error message needs improvement

### ISSUE THREAD

**Issue by matthewvalimaki** [hashicorp/nomad#845]
Nomad version `0.3.0-rc2` with LogConfig MaxFiles = 1, MaxFileSizeMB = 10 produces
```log storage (10 MB) exceeds requested disk capacity (10 MB)```, the code in question is [here](https://github.com/hashicorp/nomad/blob/6f49b9e68c1d9bde37ff9819e589c0e76b7a0d70/nomad/structs/structs.go#L1821). The error message does not make sense.

Couple solutions
- Change the operator from `<=` to `<`
- Add additional error messages to clarify that log storage cannot equal to requested disk capacity

**Comment by dadgar** [comment]
9d6604f6930557a9b02d35eb892a651c098fe502 clarifies the message
