### ISSUE TITLE
Deregister creates an unnecessary Eval if job doesn't exist

### ISSUE THREAD

**Issue by notnoop** [hashicorp/nomad#8464]
When deregistering a job, Nomad explicitly creates an Evaluation if the job doesn't exist.  It's unclear why this is the case, and it seems a bit wasteful.

The behavior was introduced without much context in https://github.com/hashicorp/nomad/pull/981, and is masked as an improvement in the [changelog](https://github.com/hashicorp/nomad/blob/v0.3.2/CHANGELOG.md#032-april-22-2016).

It's unclear what the benefit of the behavior is.  We speculate that it is bandaid around an deregistering atomicity bug, or to ensure idempotency of deregistration (e.g. re-deregister job should always succeed).

This lead to a discussion in https://github.com/hashicorp/nomad/pull/8435#discussion_r454482906 as it complicated the handling of atomic job deregistration logic.

Investigate further and act accordingly.

**Comment by tgross** [comment]
Doing a little bit of old issue cleanup. This was fixed as a side note of https://github.com/hashicorp/nomad/pull/16287, which was released in Nomad 1.5.1
