### ISSUE TITLE
Volumes and host path

### ISSUE THREAD

**Issue by vkiranananda** [hashicorp/nomad#8471]
Hello!

I have problems with mount host path.

### Nomad version

Nomad v0.12.0 

I Have docker volumes 

         volumes = [                                                                                                                       
            "/srv:/srv",                                                                                                                   
             "/mnt/common/:/mnt/common/",                                                                                                    
             "consul:/srv/consul",                                                                                                           
         ]  
### Nomad Server logs (if appropriate)

error="volumes are not enabled; cannot mount host paths: "/srv:/srv""

how can i solve this problem?

**Comment by notnoop** [comment]
Hi @vkiranananda Very sorry for this frustrating experience.  Nomad 0.12.0 disables Docker tasks access to the host filesystem, by default. Prior to Nomad 0.12, Docker tasks may mount and then manipulate any host file and may pose a security risk.

Operators now must explicitly allow tasks to access host filesystem. Host Volumes provide a fine tune access to individual paths.

To restore pre-0.12.0 behavior, you can enable Docker volume to allow binding host paths, by adding the following to the nomad client config file:

```hcl
plugin "docker" {
  config {
    volumes {
      enabled = true
    }
  }
}
```

This is noted in the 0.12.0 upgrade guide: https://www.nomadproject.io/docs/configuration/client#host_volume-stanza .

**Comment by vkiranananda** [comment]
Thank you!

I made it.

config:
  host_volume "srv" {
    path      = "/srv"
    read_only = false
  }

job:
    volume "srv" {                                                                                                                         
      type      = "host"                                                                                                                   
      read_only = false                                                                                                                    
      source    = "srv"                                                                                                                    
    }

task: 
      volume_mount {                                                                                                                       
        volume      = "srv"                                                                                                                
        destination = "/srv"                                                                                                               
        read_only   = false                                                                                                                
      }  

Is this ok?
