### ISSUE TITLE
system job need not support scaling stanza

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#8481]
### Nomad version
Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

### Operating system and Environment details
CentOS 7/8

### Issue
If the job type is `system`, it need not allow the `scaling` stanza ...

### Reproduction steps
Use the example job, and then add the `scaling` stanza as below.

### Job file (if appropriate)

```hcl
job "system_multiple" {
  type = "system"

  datacenters = ["dc1"]

  group "cache" {
    count = 1

    scaling {
      enabled = true
      min = 1
      max = 5
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

Tagging:
@cgbaker

**Comment by jrasell** [comment]
thanks for writing this up @shantanugadgil!
