### ISSUE TITLE
Is it possible to advertise the EIP of an AWS instance to the client instead of local instances network

### ISSUE THREAD

**Issue by dmildh** [hashicorp/nomad#8490]
Hello everyone,  is it somehow possible to advertise an ec2 based nomad server's EIP to the client?  The server is not aware of the public EIP.  The client is able to establish connectivity but then it flips it to a private IP the server is bound to as seen in the message below.  

client.server_mgr: new server list: new_servers=[172.31.1.230:4647] old_servers=[52.24.243.146:4647]

Is there a server config that allows me to advertise the new server list using the reachable ec2 EIP 52.24.243.146?  I have the client and server on two networks to simulate running a client on premise and the server on AWS.

**Comment by tgross** [comment]
Hi @dmildh! This gets a bit into AWS-implementation details, but the EIP isn't visible to the usual set of OS tools. We can fingerprint it in Nomad via the AWS metadata but by the point we're doing fingerprinting Nomad has already started. 

Fortunately AWS exposes this information in their [instance metadata API](
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). So assuming you're using something like systemd to start Nomad, you can write a [`ExecStartPre`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=) hook to pull the IP via `curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/public-ipv4` and then write that into the Nomad config file's [`advertise`](https://www.nomadproject.io/docs/configuration#advertise) field before starting Nomad.

**Comment by dmildh** [comment]
Thank you.  That did the trick!
