### ISSUE TITLE
[csi] Support for Plugins written in not-Go

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/nomad#8492]
Filling this so it gets tracked, although an upstream release (of grpc-go) is not ready yet that I know of.

### Summary

Due to a bug in grpc-go, go grpc clients that communicate over a unix domain socket currently can not communicate with strict server implementations due to an empty authority header.

This should only affect nomad through CSI plugin support, as iirc no other grpc communication goes through a UDS.

See the following issue (and linked GRPC issues): https://github.com/kubernetes/kubernetes/issues/93320

**Comment by tgross** [comment]
Thanks for the heads up, @endocrimes! I'll be keeping an eye on https://github.com/grpc/grpc-go/releases

**Comment by tgross** [comment]
The grpc fix was released as https://github.com/grpc/grpc-go/releases/tag/v1.31.0

**Comment by tgross** [comment]
Closed by the gRPC library update in https://github.com/hashicorp/nomad/pull/11481
