### ISSUE TITLE
Support Consul failures_before_critical and success_before_passing in check stanza

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#8506]
Hi folks,

It'd be great if Nomad could support new Consul 1.7.x features that were merged (https://github.com/hashicorp/consul/pull/5739).

See also https://www.consul.io/docs/agent/checks.html#success-failures-before-passing-critical

Thanks 🙏

**Comment by shoenig** [comment]
Thanks for reporting, @scalp42 !

We've already got an issue tracking this in #6913. Before Nomad can use these features, there's a fix that recently got merged into Consul in https://github.com/hashicorp/consul/pull/7949 that still needs to go out in an official Consul release. We'll track in that first Nomad ticket when the feature becomes available via Nomad.
