### ISSUE TITLE
"docker service update --image <image:tag> <service_name>" equivalent 

### ISSUE THREAD

**Issue by aduzsardi** [hashicorp/nomad#8541]
Hi, 
I searched the issues but i could not find this asked before.
What would the the nomad equivalent to docker swarm's  `docker service update` command ?

Thank you

**Comment by notnoop** [comment]
Hi @aduzsardi !  Thanks for reaching out.  There is no equivalent command - you can resubmit the job with updated image tag.

**Comment by aduzsardi** [comment]
Okay, thank you
