### ISSUE TITLE
resource stanza completed ignored during first plan

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#8544]
### Nomad version
Nomad v0.12.1 (14a6893a250fc5f652eee4c7b52d8f95c3185aef)

### Operating system and Environment details
CentOS 7/8 Ubuntu 16/18

### Issue
The `resource` stanza seems to be ignored during the first plan (i.e. before the job is submitted)

### Reproduction steps
Use the example job file below, notice the large amount of memory requested; there is no machine in the network with that much memory.

Running `nomad plan` should catch this and show the usual "memory exhausted ..." message.

### Job file (if appropriate)

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    count = 1

    scaling {
      enabled = true
      min = 1
      max = 1
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 512
        memory = 2560000

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

Output of  `nomad plan` ... 😖 

```
nomad plan example.nomad
+ Job: "example"
+ Task Group: "cache"
  + Task: "redis" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 example.nomad

```

Of course, `nomad run` makes the job go into 'Pending' state...

**Comment by shantanugadgil** [comment]
@cgbaker @jrasell @schmichael @eveld

**Comment by jrasell** [comment]
Hi @shantanugadgil, thanks for raising this with the reproduction steps.

Running this locally I managed to find that the regression occurred as part of the 0.11.0 release. In the 0.10.5 release the plan warns as expected (shown below).

```
Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "cache" (failed to place 1 allocation):
    * Resources exhausted on 1 nodes
    * Dimension "memory" exhausted on 1 nodes
```
