### ISSUE TITLE
[ui] Logs from other tasks in same group interleaved in logs view

### ISSUE THREAD

**Issue by Legogris** [hashicorp/nomad#8545]
### Nomad version
`Nomad v0.12.1 (14a6893a250fc5f652eee4c7b52d8f95c3185aef)`

### Issue
When viewing the logs for a task, intermittently the logs will be replaced by those of a different task in the same group.

### Reproduction steps
1. Schedule job with one task group containing two different tasks using driver `docker`. No specific configuration for logging in either client or job spec.
2. Enter log view in Web UI

**Comment by rkettelerij** [comment]
I haven't yet tried to reproduce this bug. But if it's correct (I assume so) then is sounds like a serious regression. The 0.11.x line doesn't show this behaviour, of that I'm sure. /cc @backspace @DingoEatingFuzz

**Comment by DingoEatingFuzz** [comment]
I haven't tried to reproduce this yet either, but I'm also not sure how this could be a UI issue. I'm surprised by software every day, so I'm not saying it _isn't_ a UI bug, but I'd be curious to see if anyone can reproduce it via the CLI or API.

**Comment by Legogris** [comment]
I guess "interleaved" was a not a great choice of words; the UI kind of "blinks" when it happens and there's only ever one tasks' is visible at any point in time.

I have not confirmed the causality but it seems to mostly or only happen when tasks/containers restart or get rescheduled.

I have not yet observed this in the cli.

**Comment by rkettelerij** [comment]
I was under the impression that logs would get mixed together, all of the time. Great to hear that's not the case.

@Legogris Perhaps an animated gif that demonstrates the issue would help clarify things?

**Comment by DingoEatingFuzz** [comment]
> I'm surprised by software every day, so I'm not saying it isn't a UI bug

So to my mild surprise, it was a UI bug. PR open: #8833
