### ISSUE TITLE
Global search navigates to wrong job url when job name contains spaces

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/nomad#8548]
### Nomad version
Nomad v0.12.1

### Issue

When using the global search to find a job whose name contains a space, clicking on the result leads to a 404 page. The url includes `%20` where the spaces are. By contrast, when looking at the jobs list and clicking on an entry for the same job, the url contains `-` in place of the spaces. Looks like the global search results do not calculate the destination URLs in the same way that the server does/expects.

### Reproduction steps

* Create a job with a space in the name
* Search for part of that job name in the global search
* Click the search result
* Get taken to a 404

**Comment by backspace** [comment]
Thanks for letting us know about this, @optiz0r. There being a space is a red herring, the true problem is that it was navigating based on the job name instead of the “plain id”! 😱 I’ve opened a PR with a fix.
