### ISSUE TITLE
ceph-csi pool parameter not passed correctly

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad#8550]
### Nomad version
11.3

### Operating system and Environment details
os: `ubuntu bionic`
ceph-csi: `quay.io/cephcsi/cephcsi:v2.1.2-amd64`

### Issue
csi volume container parameter `pool` apparently not passed to ceph-csi node during volume mount. recieving `missing required parameter pool`

Potentially problem related to `NodeStageVolume` in CSI spec.

A quick inspection looks like `NodeStageVolume` (mounts the volume to a staging path on the node.)
https://github.com/ceph/ceph-csi/blob/47d5b60af8d48574ff6d11ca37dbff5a6f56815b/internal/rbd/nodeserver.go#L116
is calling `genVolFromVolumeOptions` on line 171
https://github.com/ceph/ceph-csi/blob/47d5b60af8d48574ff6d11ca37dbff5a6f56815b/internal/rbd/nodeserver.go#L171
Then inside that function, we are hitting our `missing required parameter pool` error here:
https://github.com/ceph/ceph-csi/blob/be9e7cf956c378227ff43e0194410468919766b7/internal/rbd/rbd_util.go#L694

### Job file

csi-test-job.hcl
```
job "csi-test" {

    update {
        max_parallel = 3
        stagger = "30s"
    }

    region = "${region}"
    datacenters = ["${datacenter}"]
    type = "service"

    group "group" {

        count = 1
        volume "group_csi_volume" {
            type = "csi"
            read_only = false
            source = "csi-test-0"
        }

        task "task" {

            driver = "docker"

            resources {
                cpu    = 500
                memory = 1024
                network {
                    mbits = 1
                }
            }

           volume_mount {
              volume      = "group_csi_volume"
             destination = "/mnt/foo"
             read_only   = false
            }

            config {
                image = "alpine/latest"
                command = "sleep"
                args = [ "infinity" ]
            }
        }
    }
}
```

using the terraform nomad_volume provider (had tried using just raw hcl upload to nomad cli, no change)
ceph-csi-volume.tf
```
data "nomad_plugin" "ceph-csi" {
  plugin_id        = "ceph-csi"
  wait_for_healthy = true
}
resource "nomad_volume" "csi_volume" {
  type            = "csi"
  plugin_id       = data.nomad_plugin.ceph-csi.plugin_id
  volume_id       = "..."
  name            = "..."
  external_id     = "..."
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
  parameters = {
    # String representing a Ceph cluster
    clusterID = "..."
    # Ceph pool into which the RBD image shall be created
    pool = var.pool
  }
  secrets = {
    userID = "..."
    userKey = "..."
  }
  context = {}
}
```

ceph-csi-plugin-controller-job.hcl
```
...
    group "ceph-csi" {
        count = 1

        task "plugin" {

            driver = "docker"

            resources {
                cpu    = 200
                memory = 500

                network {
                    mbits = 1
                    port "metrics" {}
                }
            }

            # /etc/ceph-csi-config/config.json
            template {
                data = <<CONFG
[
    {
        "clusterID": "ceph",
        "monitors": [
            "..."
        ]
    }
]
CONFG
                destination   = "new/config.json"
                change_mode   = "restart"
            }

            config {
                image = "quay.io/cephcsi/cephcsi:v2.1.2-amd64"

                args = [
                    "--type=rbd",
                    "--controllerserver=true",
                    "--drivername=rbd.csi.ceph.com",
                    "--logtostderr",
                    "--endpoint=unix://csi/csi.sock",
                    "--metricsport=$${NOMAD_PORT_metrics}",
                    "--nodeid=..."
                ]

                # all CSI node plugins will need to run as privileged tasks
                # so they can mount volumes to the host. controller plugins
                # do not need to be privileged.
                privileged = true

                volumes = [
                    "new/config.json:/etc/ceph-csi-config/config.json",
                ]
            }

            service {
                name = "ceph-csi"
                port = "metrics"
                tags = [ "prometheus" ]
            }

            csi_plugin {
                id        = "ceph-csi"
                type      = "controller"
                mount_dir = "/csi" 
            }
        }
    }
```

ceph-csi-node.hcl
```
...
type= "system"

   group "ceph" {

        task "plugin" {

            driver = "docker"

            resources {
                cpu    = 200
                memory = 500

                network {
                    mbits = 1
                    port "metrics" {}
                }
            }

            # /etc/ceph-csi-config/config.json
            template {
                data = <<CONFG
[
    {
        "clusterID": "ceph",
        "monitors": [
            "..."
        ]
    }
]
CONFG
                destination   = "new/config.json"
                change_mode   = "restart"
            }

            config {
                image = "quay.io/cephcsi/cephcsi:v2.1.2-amd64"

                args = [
                    "--type=rbd",
                    # Name of the driver
                    "--drivername=rbd.csi.ceph.com",
                    "--logtostderr",
                    "--nodeserver=true",
                    "--endpoint=unix://csi/csi.sock",
                    # Unique ID distinguishing this instance of Ceph CSI among other instances, 
                    # when sharing Ceph clusters across CSI instances for provisioning
                    "--instanceid=...",
                    # This node's ID
                    "--nodeid=...", 
                    # TCP port for liveness metrics requests (/metrics)
                    "--metricsport=$${NOMAD_PORT_metrics}",
                ]

                # all CSI node plugins will need to run as privileged tasks
                # so they can mount volumes to the host. controller plugins
                # do not need to be privileged.
                privileged = true

                volumes = [
                    "new/config.json:/etc/ceph-csi-config/config.json",
                ]
                mounts = [
                    {
                        type = "tmpfs"
                        target = "/tmp/csi/keys"
                        readonly = false
                        tmpfs_options {
                            size = 1000000 # size in bytes
                        }
                    },
                ]
            }

            service {
                name = "ceph-csi"
                port = "metrics"
                tags = [ "prometheus" ]
            }

            csi_plugin {
                id        = "ceph-csi"
                type      = "node"
                mount_dir = "/csi" 
            }
        }
    }
```

### Nomad Client logs
from ceph-csi node container:
```E0728 04:47:20.003465       1 utils.go:163] ID: 23 Req-ID: csi-test-0 GRPC error: rpc error: code = Internal desc = missing required parameter pool```

###
split off from **https://github.com/hashicorp/nomad/issues/8212**
this specific error first mentioned here **https://github.com/hashicorp/nomad/issues/7668#issuecomment-629852292**

**Comment by ryanmickler** [comment]
@tgross -> I tried to include enough spec to get a complete picture. let me know if more required.

**Comment by tgross** [comment]
Thanks @ryanmickler. I'll take a look into this later in the week.

**Comment by ryanmickler** [comment]
I believe i've found the problem.

Here **https://github.com/hashicorp/nomad/blob/8f98ff2da6303c4a8809e322a7d028a60b8d6c0d/api/csi.go#L95** we can see both the `parameters` and `context` maps are part of the structure. in the hcl, I am passing in `pool` as a parameter.

Here **https://github.com/hashicorp/nomad/blob/1cb9e75ec2c05ff40aaee8bada43675d77c07163/client/pluginmanager/csimanager/volume.go#L171** only the `context` map is passed through to `NodeStageVolumeRequest`, and the parameters block is ignored. 

(Its not clear to me what should be a parameter, and what should be in `context`)

As in the bug you fixed here: **https://github.com/hashicorp/nomad/pull/8239/commits/901664f4d72716405974d5e53235166a893aecd6**, context wasnt passed properly into node stage. So i guess the following should work in nomad 11.4,

```
data "nomad_plugin" "ceph-csi" {
  plugin_id        = "ceph-csi"
  wait_for_healthy = true
}
resource "nomad_volume" "csi_volume" {
  type            = "csi"
  plugin_id       = data.nomad_plugin.ceph-csi.plugin_id
  volume_id       = "..."
  name            = "..."
  external_id     = "..."
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
  parameters = {}
  secrets = {
    userID = "..."
    userKey = "..."
  }
  context = {
     # String representing a Ceph cluster
    clusterID = "..."
    # Ceph pool into which the RBD image shall be created
    pool = var.pool
  }
}
```

**Comment by ryanmickler** [comment]
Update: well, pushing to Nomad 0.12.1 and passing `pool` in the `context` map seems to get past the original error i was having. 

Now the issues I'm having are related to how strictly `external_id` needs to be specifically formatted for the `ceph-csi` driver. I'll raise these in a new issue if its related to nomad.

I'd be happy to close this, but there's probably some amount of documentation to preserve here as others are likely to hit this error.

**Comment by tgross** [comment]
> Update: well, pushing to Nomad 0.12.1 and passing pool in the context map seems to get past the original error i was having.

Darn, I didn't dig into this more quickly because I would have caught the version where we'd fixed that. Sorry about that.

> I'd be happy to close this, but there's probably some amount of documentation to preserve here as others are likely to hit this error.

Yeah, we don't currently have a great way of documenting the details of what each CSI plugin expects for inputs, and I'd worry about getting stale with what the upstream projects are doing as well. There's clearly some Nomad-specific documentation bits to be had that don't quite belong in Nomad docs but not anywhere else either.

There's an [`integrations/`](https://github.com/hashicorp/nomad/tree/master/integrations) directory that seems like it might be a good fit for example volume specs, or maybe the [`demos/`](https://github.com/hashicorp/nomad/tree/master/demos) directory. We're having a bit of an internal discussion about that. 

I'm going to close this issue for now but rest assured we're tracking a discussion about what we can do around documentation improvements.

**Comment by rigrassm** [comment]
@tgross I love the idea of having an Examples directory containing CSI deployment specs. If this could be something that could be contributed by the public I would be happy to send over the Openstack spec we have along with any others we may use.

**Comment by ryanmickler** [comment]
@rigrassm do you mean using the Cinder CSI plugin **https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md#csi-cinder-driver**

**Comment by rigrassm** [comment]
@ryanmickler yup, that's the one. It's currently broken until 0.12.2 is released but I've tested it with the patch that fixes it and it works great.

**Comment by ryanmickler** [comment]
Perhaps we could get started on a branch where we put our example configs together?

**Comment by rigrassm** [comment]
Sure, I would happy to contribute to that!

I have one created for the Cinder CSI Driver already and did some work getting the iscsi CSI driver working which I suspect will work after the 0.12.2 release.

I'd like to hear from @tgross about the internal discussion re: the structure and location of these examples so that we can get this going as smoothly as possible. It's a good amount of work reverse engineering these CSI drivers to be deployed on Nomad (or any orchestrator not named K8's lol) so having documented examples of their configs coming in from the community would be fantastic.

**Comment by ryanmickler** [comment]
Absolutely. Let wait for feedback.

PS. I also use nomad on openstack, but ive been needing to use CephFS, which I dont think cinder can support.

**Comment by tgross** [comment]
Thanks folks! I've opened https://github.com/hashicorp/nomad/pull/8651 to add a directory at `./demo/csi/` to collect these.

**Comment by rigrassm** [comment]
@tgross Awesome, appreciate it! 

@ryanmickler I Just opened #8662 adding an example for the Cinder CSI driver if you wanted to take a look at it.

**Comment by ryanmickler** [comment]
Great, i just added **https://github.com/hashicorp/nomad/pull/8664**

This should get people started.
