### ISSUE TITLE
isolate Vault entironment variables used for Nomad

### ISSUE THREAD

**Issue by drewbailey** [hashicorp/nomad#8582]
Nomad currently uses `VAULT_TOKEN` and `VAULT_NAMESPACE` when configuring Nomad servers. `VAULT_TOKEN` is also used during job submission. These environment variables are canonical to Vault, which uses them by default if they are set.

This potentially causes issues with users who interact with Vault directly. One use case is where a user is already using the Vault CLI and has an operator token for VAULT_TOKEN, and wants to use a different vault token for Nomad.

Proposal:
* Allow for `NOMAD_VAULT_TOKEN` and `NOMAD_VAULT_NAMESPACE` as default values
* Fallback to `VAULT_TOKEN` and `VAULT_NAMESPACE` if the Nomad specific ones are not set
* Outline a deprecation policy for `VAULT_TOKEN` and `VAULT_NAMESPACE`

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Vault tokens in the Nomad agent configuration. Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. Using Vault tokens in the Nomad configuration will be removed entirely in Nomad 1.9.
