### ISSUE TITLE
Consul will support envoy 1.15.0 with Consul 1.9

### ISSUE THREAD

**Issue by rboyer** [hashicorp/nomad#8585]
See https://github.com/hashicorp/consul/pull/8424

As discussed elsewhere, we'll also add a TBD API endpoint that nomad can use to get the supported envoy version range for a given agent that will likely make this easier going forward.

**Comment by shoenig** [comment]
Should be addressed by https://github.com/hashicorp/nomad/pull/8945, however we'll want to make sure https://github.com/orgs/hashicorp/projects/62#card-45960173 is not still a problem before release.
