### ISSUE TITLE
non-Docker CSI controller job

### ISSUE THREAD

**Issue by dinesh** [hashicorp/nomad#8587]
Is it possible to create CSI controller/plugin job via `exec` like `docker` driver?

I don't have a docker driver available in my cluster.

**Comment by langmartin** [comment]
Hi @dinesh, the tldr answer is no, you'll need to have at least some docker drivers available. In CSI, the term "plugin" is overloaded, there are both controller and node plugins. The controller plugins do not need any special privileges and can be run as exec jobs, they're responsible for communicating with the storage provider on behalf of the entire cluster, and are usually just API translators. The node plugins are responsible for creating devices and mounting them on the nodes, and require privileges to do so. See the first note here: https://www.nomadproject.io/docs/job-specification/csi_plugin#csi_plugin-parameters. Of the default task drivers, only docker can both mount drives and have `CAP_SYS_ADMIN`.

**Comment by dinesh** [comment]
@langmartin I even tried `rawexec` to make it work (with root) with a system job and it (node plugin) got started but didn't show up in UI. I guess it's due to the csi socket location ( `:data_dir/plugins/csi/:plugin/csi.sock` not being present).

**Comment by tgross** [comment]
@dinesh the `raw_exec` driver doesn't allow mounting (see https://www.nomadproject.io/docs/drivers/raw_exec#capabilities), which we need to mount a directory to the task.
