### ISSUE TITLE
Need documentation about different events that trigger evaluations 

### ISSUE THREAD

**Issue by abhip** [hashicorp/nomad#8588]
The results returned when we call evaluation API (When I call evaluation API (https://www.nomadproject.io/api-docs/evaluations) contain a field called "TriggeredBy" which contain various values such as deployment-watcher, job-register and node-update . Some of these values are self -explanatory but others are not. 

I did not find any documentation about these fields in the website or any comment in the code explaining about them. 

Here is where they defined in the code - https://github.com/hashicorp/nomad/blob/940817aeb52e740ef5d35f1be925f2c61b8ecd0f/nomad/structs/structs.go#L9377

It would be very helpful if documentation is provided about them

**Comment by tgross** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/14750
