### ISSUE TITLE
nomad fs fails when client uses bind_addr 0.0.0.0

### ISSUE THREAD

**Issue by ProbablyRusty** [hashicorp/nomad#860]
If I bind a client to all interfaces:

```
bind_addr = "0.0.0.0"
```

then `nomad fs` commands don't work, because nomad tries to reach the node at 0.0.0.0.

```
$ nomad fs ls 697ec61e-8e4a-fed4-7a2f-3068a41fc50a
Error listing alloc dir: Get http://0.0.0.0:4646/v1/client/fs/ls/697ec61e-8e4a-fed4-7a2f-3068a41fc50a?path=%2F: dial tcp 0.0.0.0:4646: getsockopt: connection refused
```

Is this expected behavior? ie: is it not possible to bind nomad to all interfaces on a client and still use this functionality?

**Comment by grubernaut** [comment]
In the client configuration you should also specify the HTTP port to bind to, otherwise `nomad fs` won't be able to read from the nomad client. 

Ex:

```
bind_addr = "0.0.0.0"

advertise {
  http  = "<Local_IP>:4646"
}
```

**Comment by consultantRR** [comment]
Interesting.

Here is the documentation currently on https://www.nomadproject.io/docs/agent/config.html:

```
advertise: Controls the advertise address for individual network services. This can be used to advertise a different address to the peers of a server node to support more complex network configurations such as NAT. This configuration is optional, and defaults to the bind address of the specific network service if it is not provided. This configuration is only applicable on server nodes. The value is a map of IP addresses and ports and supports the following keys: 

rpc: The address to advertise for the RPC interface. This address should be reachable by all of the agents in the cluster. For example: advertise { rpc = "1.2.3.4:4647" }
serf: The address advertised for the gossip layer. This address must be reachable from all server nodes. It is not required that clients can reach this address.
```

From the above, I take a away two points:

(1) it seemed to me like this was only for server nodes
(2) I don't see `http` as a supported key (only `rpc` and `serf`)

**Comment by grubernaut** [comment]
@consultantRR which Nomad version are you currently running?

**Comment by consultantRR** [comment]
0.3.0

**Comment by grubernaut** [comment]
https://www.nomadproject.io/docs/agent/config.html#http show's the correct documentation for me for 0.3.0, being:

```
The address the HTTP server is bound to. This is the most common bind address to change. Applies to both clients and servers.
```

**Comment by grubernaut** [comment]
Ah sorry, that link was for `addresses` not `advertise`

**Comment by consultantRR** [comment]
Right. I haven't tested your suggestion yet. So I don't personally know yet if this is a documentation issue, or a technical one. But what you suggested does make sense, so if it is indeed supported in 0.3.0, then I think this is simply a documentation issue.

**Comment by grubernaut** [comment]
I'm not sure of the exact commit that added this in, but I believe this to be a documentation issue. 

Pinging @diptanu for confirmation

**Comment by diptanu** [comment]
@consultantRR Yeah, I think this is a documentation issue. I will update the docs.

And also you can bind to `0.0.0.0` and then you can use either ```advertise``` or ```addresses``` to advertise the client IP addr that Nomad cli would use to list dirs, read files, etc.

The difference between ```addresses``` and ```advertise``` is that the former would actually tell Nomad client to bind to that IP, whereas the later would just tell the server that this is what the external tools should hit for accessing the API. Also addresses take only the IP address and advertise takes IP:port.

**Comment by consultantRR** [comment]
@diptanu Since this issue is still open, and I believe the docs are still incorrect, can you confirm the following:

Are you saying it is possible (and supported) to specify an `http` advertisement in a _client_ config?

ie:

```
advertise {
  http = "lsnomad-node-foo.node.qantas-loyalty-sydney.soa.ebi:4646"
}

**Comment by grubernaut** [comment]
@consultantRR yes that is correct. In a nomad-client's config file you should specify,

```
advertise {
  http = "<ip_address>:<port>
}
```

**Comment by mlafeldt** [comment]
I'm still trying to understand why `nomad fs` does not honor the `NOMAD_ADDR` environment variable.

In our setup, Nomad clients are running behind an ELB with SSL termination enabled.

Unfortunately, this won't work:

```
$ export NOMAD_ADDR=https://nomad.example.net
$ nomad fs -job reports/periodic-1468420020
Get http://0.0.0.0:8080/v1/client/fs/stat/17b1932c-ccc2-ecf9-99aa-5919b75979b3?path=%2F: dial tcp 0.0.0.0:8080: getsockopt: connection refused
```

While a direct HTTP request to the actual endpoint works fine:

```
$ curl -s https://nomad.example.net/v1/client/fs/stat/17b1932c-ccc2-ecf9-99aa-5919b75979b3?path=%2F | jq .
{
  "FileMode": "drwxr-xr-x",
  "IsDir": true,
  "ModTime": "2016-07-13T14:27:00Z",
  "Name": "17b1932c-ccc2-ecf9-99aa-5919b75979b3",
  "Size": 4096
}
```

AFAIK, `nomad fs` is the only command with this issue.

**Comment by dadgar** [comment]
Hey @mlafeldt,

The `NOMAD_ADDR` is used to connect to the local Nomad Agent. However, the `nomad fs` command works by connecting to the agent, determining the node the allocation is on and using that Node's Advertise address to connect to it.

- Alex Dadgar

**Comment by mlafeldt** [comment]
@dadgar Ah, thanks for the clarification.

So a client knows about the result of all jobs, but it does require direct access to the node that executed the job to get filesystem information?

This essentially means that we cannot operate client nodes behind a load balancer as the nodes themselves are private. Not sure, but forwarding filesystem-related requests to the right client node might be a useful feature (similar to how servers forward requests to the leader)?

**Comment by mlafeldt** [comment]
@dadgar FWIW, we solved the problem by running the command-line tool from a bastion host that has direct access to all client nodes. Unfortunately, this still doesn't allow other web services to get the stdout/stderr of jobs by talking to the Nomad API via our ELB. However, we can live with that for now.

**Comment by dadgar** [comment]
Hey I am going to close this since the client will auto advertise HTTP now.
