### ISSUE TITLE
node-drain using name

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#863]
Hi,

Upgrading our Nomad cluster to 0.3, I encountered a problem with the node-drain command.
In the example of the documentation it seems that you can specify a node using its name (`$ nomad node-drain -enable node1`), but when I run the command, it doesn't work. It only accepts UUID:
`Error toggling drain mode: Unexpected response code: 500 (rpc error: rpc error: node lookup failed: index error: UUID must be 36 characters)`

I think it is useful that you can drain a node specifying the name (I'm using Ansible to automate this upgrade, and since the nomad client name is the same as the hostname, it would be really easy to achieve this).

It would be useful too, to launch the command with a `myself` param or similar, so only that node where you launched the command gets drained. This way you don't have to write the UUID or the name, and simplifies the automation of rolling upgrades using a CM like Ansible/puppet etc.

What do you think?
Thank you guys!

**Comment by adrianlop** [comment]
btw, if someone is having the same problem, or this issue gets closed because you consider that is not neccesary, workaround here:

`nomad node-status | grep "$(hostname)" | awk '{print $1}' | xargs nomad node-drain -enable`

**Comment by adrianlop** [comment]
Yeah, I saw it here:
https://github.com/hashicorp/nomad/blob/master/website/source/docs/commands/node-drain.html.md.erb#L45

Also, here it says node ID or prefix: I understood node0* by prefix, I tried it but no good result neither:
https://github.com/hashicorp/nomad/blob/master/website/source/docs/commands/node-drain.html.md.erb#L24-L26

I see now that if 2 nodes have these 2 UUIDS:
- aaf19802-fb8e-af71-905c-c91a79e83a0c
- aa60512c-6c13-40d3-0ae2-c7ae2a6463cd

`nomad node-drain -disable aa` will list you both. So the prefix is for UUIDs too.

So it's no problem, if you think this is not a valuable enhancement you can close it!
the workaround I posted 2 comments ago, works like a charm.

@diptanu @dadgar thank you both  for your help!

**Comment by trenton42** [comment]
There was one small piece in @adrianlop 's original issue that I don't want to be overlooked: a `nomad node-drain self` command would really be wonderful.

**Comment by dadgar** [comment]
@trenton42 https://github.com/hashicorp/nomad/issues/926

**Comment by trenton42** [comment]
@dadgar Thanks!
