### ISSUE TITLE
Interpret variables in all driver fields 

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/nomad#865]
Hi,

I'm trying give the containers the same name as the host they're running on, but it seems that the var value isn't replaced:

```
/opt/docker # hostname
${node.name}
```

I've tried with ${attr.hostname} and also ${attr.unique.consul.name} because I saw them with `nomad node-status UUID`, but they didn't work neither.
I've also tried removing {}, same problem.

They way I'm trying to config this, is:

```
[...]

task "test" {

            driver = "docker"

            config {
                hostname = "${attr.hostname}"
                image = "xxx/test:latest"
                port_map {
                    http = 10000
                }
            }

[...]
```

Can you help please?

**Comment by diptanu** [comment]
@adrianlop You want all the containers on a machine to have the same name? Docker containers needs to have unique names on a machine.

Also, in Nomad container names are a combination of allocation ids and task names. So on a monitoring system, you can identify metrics coming from an application running on containers via the allocation ids.

Does this help?

**Comment by adrianlop** [comment]
@diptanu thanks for the fast answer!
I understand that the container name has to be unique, but what I want is the hostname inside the container, not the name of the container. this can be the same. in fact, I want this because it's easier to identify them in a metrics dashboard (I'm collecting them via cAdvisor, then visualizing on Grafana).
example:
you can do this (and this is what I want):
```
$ docker run --hostname diptanu --name redis1 -d redis
$ docker run --hostname diptanu --name redis2 -d redis
```
I think you're referring to `--name`, but I meant `--hostname`

what do you think?

**Comment by adrianlop** [comment]
@dadgar thank you - unfortunately, it doesn't work neither :(
```
/opt/docker # hostname
${node.unique.name}
```
can you help, please?

**Comment by dadgar** [comment]
Ahh I didn't read carefully enough. We only replace variables in the argument section. Not all config fields.

**Comment by adrianlop** [comment]
oh ok I see. could you please add this feature?

**Comment by Supernomad** [comment]
I just ran into this issue as well, so definitely a +1, but out of curiosity why is that the case, just because it is or is there a low level reason?

**Comment by dadgar** [comment]
@Supernomad not really a technical reason it wasn't done, honestly just didn't think people would want it. There is some difficulty of interpreting vars as ints or booleans. We probably won't support that in any first cut.

**Comment by Supernomad** [comment]
@dadgar Thank you for the explanation, and I completely understand their are priorities and only so much research can be done on use cases. Love that the feature is on your guys radar.

**Comment by LordFPL** [comment]
Hi,

I discover this "issue" and have a use case : 
* I launch 2 tomcat (count = 2)
* Consul is correctly configured, and i have a load balance on http://tomcat.service.consul dns alias
* Devs want to upgrade/test only one instance via tomcat manager... but with load balance, impossible to reach always the same task...

I was thinking about using tags and add in nomad job tags = ["${NOMAD_ALLOC_INDEX}"] to have access with http://0.tomcat.service.consul/manager and http://1.tomcat.service.consul/manager.
I found this solution pretty cool... but not possible actually due to this issue...

I'm doing something wrong ? Or this use case can add a higher priority to this issue ?

Thanks in advance for any comment :)

**Comment by dadgar** [comment]
@LordFPL you are not doing anything wrong, it is just not supported as of this time. You can just have two task groups both running tomcat and mark one with a tag dev and one prod for now?

We will probably doing a large revamp of the interpretation system for 0.4 that will hopefully solve all these use cases.

**Comment by LordFPL** [comment]
@dadgar Actually, nomad is not in prod on our server, we are launching services manually. So, it's not a problem to wait 0.4 :)

**Comment by ketzacoatl** [comment]
There is some overlap here with #1063, so updating here to link the two together.

**Comment by LordFPL** [comment]
For information, it seem to be ok in 0.4.1 :)
Many thx ! :)

**Comment by dadgar** [comment]
In Nomad 0.9.0 all the fields in the driver config will be interpreted.
