### ISSUE TITLE
Reserved CPU prevents any job from running

### ISSUE THREAD

**Issue by scalp42** [hashicorp/nomad#8689]
Hi folks,

We have an issue when trying to reserve any amount of CPU using `Nomad v0.12.2 (ee69b3379aeced67e14943b86c4f621451e64e84)`.

The setup in on a simple VM with 1 gig of memory.

<details>
  <summary markdown="span">We have a simple job with the minimum CPU allowed:</summary>

```hcl
job "httpbin" {
  datacenters = ["kitchen"]

  group "httpbin" {
    task "httpbin" {
      driver = "docker"

      config {
        image = "kennethreitz/httpbin"
        port_map {
          http = 80
        }
      }

      resources {
        cpu    = 20
        memory = 256
        network {
          mbits = 10
          port "http" {}
        }
      }

      service {
        name = "httpbin"
        port = "http"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "1s"
          timeout  = "1s"
        }
      }
    }
  }
}
```
</details>

<details>
  <summary markdown="span">The Nomad client has reserved CPU set to 100% of the VM:</summary>

```json
root@default-ubuntu-1804:~# cat /etc/nomad/client.json
{
  "client": {
    "disable_remote_exec": false,
    "enabled": true,
    "max_kill_timeout": "30s",
    "meta": {
      "chef_role": null,
      "role": null
    },
    "network_interface": "eth1",
    "no_host_uuid": true,
    "reserved": {
      "memory": 985,
      "cpu": 2592
    },
    "server_join": {
      "retry_join": [

      ]
    }
  }
}
```
</details>

Client in Nomad UI:

![Screen Shot 2020-08-18 at 18 35 38](https://user-images.githubusercontent.com/1475276/90582043-a72d0e00-e181-11ea-8e4f-af49d37c4d1b.png)

However when trying to run the job results in a failed (pending) allocation:

```
       ---- Begin output of nomad job run -token=5870c097-8c59-4305-a00d-bc585d42e098 /root/httpbin.hcl ----
       STDOUT: ==> Monitoring evaluation "e6446d31"
           Evaluation triggered by job "httpbin"
           Evaluation within deployment: "909a73ca"
           Evaluation status changed: "pending" -> "complete"
       ==> Evaluation "e6446d31" finished with status "complete" but failed to place all allocations:
           Task Group "httpbin" (failed to place 1 allocation):
             * Resources exhausted on 1 nodes
             * Dimension "cpu" exhausted on 1 nodes
           Evaluation "b023413b" waiting for additional capacity to place remainder
       STDERR:
       ---- End output of nomad job run -token=5870c097-8c59-4305-a00d-bc585d42e098 /root/httpbin.hcl ----
       Ran nomad job run -token=5870c097-8c59-4305-a00d-bc585d42e098 /root/httpbin.hcl returned 2
```

I believe it's a bug unless we're missing something. I can't tell if it's due to the newer version of Nomad or not as we just added the test case.

Thanks folks!

**Comment by jrasell** [comment]
Hi @scalp42 and thanks for the detail in this issue. What is the behaviour you are expecting to see? From what I understand you are reserving all the CPU on the client; reserving as detailed in the documentation `specifies that Nomad should reserve a portion of the node's resources from receiving tasks`. In this case you are reserving all the CPU which means CPU is exhausted as the output of a job run indicates.

**Comment by scalp42** [comment]
@jrasell looks like we got the terminology backwards.

We replaced it with the following as it's still more clear to us:

```ruby
# NOTE: https://www.nomadproject.io/docs/configuration/client#reserved-parameters
# NOTE: allowed memory percentage from the host to be used by Nomad to schedule tasks
default['nomad']['config']['allowed_percentage']['memory'] = '90'
```

Thanks! Closing.
