### ISSUE TITLE
Add an option to disable client Vault token renewal

### ISSUE THREAD

**Issue by roman-vynar** [hashicorp/nomad#8690]
For Vault integration, Nomad requires that the client tokens are renewable according to the role spec like that:
```
nomad_cluster_role = {
    "allowed_policies": allowed_policies,
    "no_default_policy": True,
    "token_explicit_max_ttl": 0,  # required
    "name": "nomad-cluster",
    "orphan": True,
    "token_period": 60,
    "renewable": True  # required
}
```

However, all our application services that we deploy with Nomad read secrets from Vault during the startup, keep in memory and Vault token issued by Nomad is no longer needed. In our case we use env var VAULT_TOKEN set by Nomad into a task docker container.

Moreover, from security perspective it's not good to keep an env var VAULT_TOKEN or something like that persistent.
That's why we have set token_period=60 and patched Nomad with an easy fix to skip token renewal by doing nothing:
https://github.com/Quiq/nomad/commit/6571064d8b01f9b10e828fdd481225a1752f7a18

It works perfectly for us, a server vault token is renewed ok, a client vault token expires after 60s, it is enough time for application to read secrets.. Of course, we account that a task allocation restart is not possible because of expired vault token but it's ok for us and we do re-scheduling instead when a new alloc is created with a new vault token issued.

Thanks!

**Comment by tgross** [comment]
Hi @roman-vynar! This is an interesting use case but I think it needs a bit more consideration.

**Comment by mriddell-foundry** [comment]
Hi @tgross. Is there any updates on this sort of feature?

My team has a use case where we have some long running batch data processing tasks which require a secret (api key) to retrieve the initial set of data then processes that data for x amount of time afterwards.

The secret is only required for about 10 minutes during the fetching of the data but not during the processing itself which can take some time.
I feel this could be an adequate use case for this feature but was curious if there was any movement on this item.

Thanks!

**Comment by tgross** [comment]
Hi @mriddell-foundry! We've got an open issue for a refresh of our Vault integration in https://github.com/hashicorp/nomad/issues/15617 and this might fall under there. That refresh is (very roughly) scheduled for the 1.7 release, which means it's not coming until late in the year at the earliest.

**Comment by tgross** [comment]
Making a note here that starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've got a new workflow where Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. 

But we didn't implement this feature to disable renewal, which is something we can probably implement now either based on the `vault` block or the Vault auth configuration itself (ex. if the auth config uses batch tokens). I'll surface this for roadmapping.

**Comment by tgross** [comment]
Done in #19691, which will ship in the next release of Nomad 1.7.x

**Comment by roman-vynar** [comment]
Thanks Tim!
