### ISSUE TITLE
Use IP returned from CNI to register service in Consul

### ISSUE THREAD

**Issue by daledude** [hashicorp/nomad#8698]
This is a feature request unless I'm missing something.

It seems nomad does not use the IP address returned from CNI to register the task in Consul. It would be very useful to us if CNI was used to it's full intended purpose.

https://github.com/hashicorp/nomad/blob/20947a5a4f9277c29d6e162022ad016b79d5bb8f/client/allocrunner/networking_cni.go#L92

**Comment by yishan-lin** [comment]
We're working on this at the moment - stay tuned!
