### ISSUE TITLE
Clarify behavior of env = "true" for template change modes

### ISSUE THREAD

**Issue by tommyalatalo** [hashicorp/nomad#8703]
We found an unintuitive behavior with templates and the `env = true` settings while testing container restarts this past week.
In our task the `change_mode` was set to `noop`, and so we set an environment variable to some templated IP addresses for a peer list which keeps changing periodically and is needed by the task, and then restarted the container. To our surprise the environment variable did not update the list of peers on container restart, instead the value that was set on the first start of the container was reused or "sticky". Not until a reschedule of the container did we get an update of the environment variable.

This was a bit confusing as we always see the file written to disk (`local/env` in our case) update constantly.
What we were expecting was for the environment variable to be updated at restart when the template is rendered during the container startup.

We realize that this is quite possibly an intended behavior of the `noop` change mode, but in that case this would be nice to clarify in the documentations that the environment variable is set **only once** during the first start of the container and never again even through container restarts.

**Comment by tgross** [comment]
Hi @tommyalatalo! Yeah that looks like an area we could clarify better in the docs. Thanks for reporting it!

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/9394 and will ship with the next website push.
