### ISSUE TITLE
Autoscale Job Support

### ISSUE THREAD

**Issue by brendanfoxen** [hashicorp/nomad#871]
Hi

Will the ability to autoscale a job such as an Nginx container based on a given metric such as CPU utilisation  be supported? Is it on the roadmap?

Thanks

Brendan

**Comment by dadgar** [comment]
Hey Brendan,

This is something that is on the roadmap and will most likely come in the form of an integration between Atlas and Nomad.

**Comment by brendanfoxen** [comment]
Hey Alex, that for the reply. That's great to hear
