### ISSUE TITLE
Docs: details of an in-place restart of an allocation are unclear

### ISSUE THREAD

**Issue by sbrl** [hashicorp/nomad#8712]
I've previously posted this on the Hashicorp discussion forum, but received no reply. Link: <https://discuss.hashicorp.com/t/what-are-the-implications-of-an-in-place-restart/12721>.

### Nomad version
```
Nomad v0.12.1 (14a6893a250fc5f652eee4c7b52d8f95c3185aef)
```

### Operating system and Environment details
```
$ uname -a
Linux SERVER_NAME 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

### Issue

What are the implications of an in-place restart with respect to a reallocation?

Does an in-place-restart re-pull the docker image from the registry, or does one have to reallocate in order to get Nomad to re-pull the Docker container to fetch an updated version thereof?

I've looked at [the documentation](https://www.nomadproject.io/docs/commands/alloc/restart) about `nomad alloc restart`,  but it doesn't appear to give any details about whether it causes a re-pull from the docker registry or not.

**Context:** I'm trying to setup a system that automatically checks my [minideb](https://github.com/bitnami/minideb/) containers for updates with apt, and rebuilds the containers if necessary. Rebuilding the container is nice, but it's not very useful if I can't programmatically get Nomad to re-pull docker containers from my local private registry by restarting the allocation in-place.

**Comment by sbrl** [comment]
Ah, I see. Thanks! I wasn't aware of that setting. How do you mean update the label of a container? Is that as in the config file:

```hcl
# .....
task "testing" {
config {
  labels {
    foo = "bar"
    zip = "zap"
  }
}
}
# .....
```

...and then resubmit the job file with `nomad run`? Or via some other means? Ideally, I need a way to do it automatically via my CI system that updates my docker containers.

**Comment by tgross** [comment]
> How do you mean update the label of a container?

Apologies, I was using the wrong term -- I should have said "tag", as in the Docker image naming format `<registry>/<repo>:<tag>`. So updating `myorg/myapp:v1` to `myorg/myapp:v2`.

**Comment by sbrl** [comment]
Ah, I see. That's really quite impractical for my use-case though, as then I would have to push a new tag for every minor update to the container - even if the upstream software has not published a new version. Furthermore, in that case if I understand Docker registries correctly, I would need to somehow manage the old versions of the image that I've pushed and delete them to save disk space.

All in all, that solution adds a lot of additional complexity I'd rather avoid.

**Comment by tgross** [comment]
Circling back to this one to wrap it up, the other way this can be done is to bump a flag in the `meta` stanza, which forces an re-deployment of the job. That avoids having to push changes to the image registry, and moves the responsibility to whatever is executing the deployment.

**Comment by sbrl** [comment]
Thanks for the update! I'll take a look at that. Updating the nomad job file automatically sounds like it'll add additional complexity, but I'll see what I can do.

Thanks again!
