### ISSUE TITLE
View current node resource allocations

### ISSUE THREAD

**Issue by grubernaut** [hashicorp/nomad#872]
When submitting a nomad job, it's difficult to tell how many resources you currently have allocated per node.

If you submit a job to nomad and all of your nomad-clients are already reserving a maximum amount of resource capability, it's difficult to debug which nomad-client would be over-subscribed. 

```
Submitting example.job: ==> Monitoring evaluation "9468a3d6"
    Evaluation triggered by job "example"
    Scheduling error for group "example" (failed to find a node for placement)
    Allocation "8e4f0520" status "failed" (2/3 nodes filtered)
      * Class "linux-64bit" filtered 2 nodes
      * Constraint "missing drivers" filtered 2 nodes
      * Resources exhausted on 1 nodes
      * Class "linux-64bit" exhausted on 1 nodes
      * Dimension "cpu exhausted" exhausted on 1 nodes
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "9468a3d6" finished with status "complete"
```

It'd be helpful to have a command that would list the current nomad node's resource allocation, matched up with their actual resource capabilities.

**Comment by adrianlop** [comment]
+1
