### ISSUE TITLE
Feature request: Keep-alive setting for remote exec UI

### ISSUE THREAD

**Issue by jfcantu** [hashicorp/nomad#8727]
Hey folks,

Simple (hopefully?) feature request for the Nomad remote exec web UI:

We run our Nomad cluster behind an AWS application load balancer that serves the UI and API. The ALB has a connection idle timeout, which by default is 60 seconds. So, basically, if you open a remote `exec` session, it will only stay open as long as there's either input or output from the session - otherwise, it terminates after the timeout expires.

It would be helpful for Nomad to have a "keep-alive" function for `exec` sessions to prevent issues like this.

**Comment by backspace** [comment]
Thanks for the suggestion, @jfcantu. It does seem simple enough to implement in the UI, though I’m wondering if it should have CLI support as well, then both consumers could use the same flag. I’ll ask around about this.
