### ISSUE TITLE
docker driver log behavior

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/nomad#873]
In Nomad 0.3.0, for Docker jobs,

I see that Nomad spins its own localhost syslog listener, and diverts container logs to this listener.

So, if I do a `docker inspect` on one of these containers, I see:

```
        "LogConfig": {
            "Type": "syslog",
            "Config": {
                "syslog-address": "tcp://127.0.0.1:14001"
            }
        }
```

I also see that these logs then get diverted to:

`/var/lib/nomad/alloc/{ALLOCATION_ID}/alloc/logs`

Problem is, I have previously (prior to Nomad 0.3.0), been aggregating container logs to a single logfile on the node and then collecting that log into AWS CloudWatch logs (using the `awslogs` agent on node).

As an example, a `docker inspect` on one of these pre-Nomad 0.3.0 containers would show:

```
        "LogConfig": {
            "Type": "syslog",
            "Config": {
                "tag": "{{.ImageName}}|{{.Name}}|{{.ID}}"
            }
        }
```

(the tag format has been defined by me as a default in `/etc/sysconfig/docker` as follows: `OPTIONS='--log-driver=syslog --log-opt tag={{.ImageName}}|{{.Name}}|{{.ID}}'`)

Anyway, this is now problematic, because Nomad 0.3.0 seems to override this default in all cases, and consequently, log aggregation is not happening.

So, I guess I have a few questions:

(1) Can this Nomad behavior be overridden?
(2) Can the behavior of what Nomad does with logs that _do_ get delivered to this new "Nomad syslog service" be configured or customized in any way? (ie: to write them to a central location, not divided by allocation, or something similar?)
(3) What is the intended workflow for this current default behavior in Nomad 0.3.0? (ie: What is the expected use case of logs being divided by allocation and written locally on the node?)
(4) I assume that this local syslog diversion in Nomad 0.3.0 is the foundation for a greatly enhanced log handling feature set in future Nomad versions. Is there a roadmap on that?

Much thanks in advance for any clarifications or insight.

**Comment by pshima** [comment]
Hi @consultantRR,

I'll leave the specific questions on direction for the other Nomad folks but wanted to comment on how you may get this working in your configuration with these changes in Nomad 0.3.

We use this container that runs side by side in a task group with our tasks: https://hub.docker.com/r/pshima/nomad-logging-cloudwatch/

This container takes a few environment variables, picks up the nomad logs and ships them out to cloudwatch logs.  The container itself basically just runs a setup command for cloudwatch logs and ship them: https://gist.github.com/pshima/fcef801475a033e5ec6a

Then in our nomad job spec we configure this container inside the task group for where we want to collect logs.
```
    task "nomad-logging" {
      driver = "docker"

      config {
        image = "pshima/nomad-logging-cloudwatch:latest"
        command = "/root/runner.sh"
      }

      env {
        NOMAD_TASK_NAME = "my-service"
        AWS_REGION = "us-west-2"
        ENVIRONMENT = "prod"
      }

      resources {
        cpu = 250
        memory = 256
        network {
          mbits = 10
        }
      }
    }
```

Does that differ a lot from your current configuration and/or achieve the same logging goals?

**Comment by diptanu** [comment]
@consultantRR These are great questions!

We are indeed going to add support for pushing logs to remote syslog endpoints and not just the local syslog agent. The reason why we had to do this was we wanted to do log rotation and make the logs get written to the allocation directory instead of the host file system for the purposes of accounting of disk space and with Nomad 0.3 you also have `nomad fs` suite of commands which will allow you to look at the log files written in your allocation directory.

Also, in the future versions of Nomad we will introduce the `nomad logs` command which will allow users to stream log lines without running `nomad fs cat` on the latest rotated log file.

Regarding your question about writing logs in allocation directory vs the local node, in a multi-tenant environment writing logs on the node makes accounting for disk space and resource usage impossible. So writing log lines to files to individual allocation directories and accounting for their resource usage makes fair share of the resources possible.

Does this make sense?

**Comment by c4milo** [comment]
Instead of storing logs locally and creating a local syslog endpoint, I would have preferred streaming logs to a configurable remote syslog endpoint, right off the bat. Although, I must confess I don't fully understand yet the need for storing logs locally.

**Comment by consultantRR** [comment]
Thanks @diptanu,

It does make sense.

But it does leave me (and, I believe, others) with the question of how do I aggregate and archive logs from my entire job, across multiple nodes, when that doesn't currently seem to be possible as of Nomad 0.3.0, and additionally, Nomad seemingly overrides the ability to do this in a homegrown/custom way.

Don't get me wrong: `nomad fs` and future `nomad logs` will be useful. But for different reasons than the common (I think) use case I describe.

Not to mention, nodes will come and go. (Autoscaling, rip and replacement, etc.) To me, part of the great appeal of Nomad is that the individual nodes are less precious. They are simply additional providers of resources on which the Nomad cluster can place allocations. For that reason, among others, it's absolutely critical, IMO, that logs from the applications themselves can optionally persist elsewhere, beyond the lifespan of the node on which they were staged at the time.

**Comment by diptanu** [comment]
@consultantRR Did you get a chance to look at the solution @pshima proposed? You can basically run your cloud watch log agent as a task in every task group of the job and that can ship the logs written in the alloc/logs dir to cloud watch and that's how you can aggregate logs from all the modes in a cluster.

**Comment by consultantRR** [comment]
Much thanks, @pshima. Would it be possible for you to share a Dockerfile for this `nomad-logging-cloudwatch` image?

**Comment by pshima** [comment]
Hi @consultantRR,

Here is a Dockerfile you can use to build it: https://gist.github.com/pshima/b43543b5388e365b04b8

The contents of runner.sh are https://gist.github.com/pshima/fcef801475a033e5ec6a

We are actually building with packer instead of a Dockerfile at the moment but that should work.

**Comment by consultantRR** [comment]
Thanks @pshima,

One question, are you using the gist you post above as your `runner.sh` for Nomad 0.3.0, or for an earlier version? I ask because, at a glance, it seems the log path you use in that Gist isn't what Nomad 0.3.0 is doing in terms of log paths.

ie:

`/var/lib/nomad/alloc/{ALLOCATION_ID}/alloc/logs`

instead of (from your Gist):

`/alloc/logs/$NOMAD_TASK_NAME.stdout*`

No?

**Comment by pshima** [comment]
We are using that with Nomad 0.3.0.  From inside the task group, the logs can be retrieved from /alloc/logs/.

That is a good point though - it is probably better to use $NOMAD_ALLOC_DIR/logs/ for that bit.

**Comment by diptanu** [comment]
@c4milo So sometimes people might not want log forwarding at all. For example, I have run services where cluster sizes span 5k nodes on AWS. Log forwarding in these kinds of situations turn out to be very expensive, so it's useful to treat log files as ephemeral and having on-demand access during outages or diagnostic sessions are enough.

Nomad will do the remote log forwarding fairly soon and that would be an option in the ```logs``` block in the Job config. Does this make sense?

**Comment by c4milo** [comment]
@diptanu, it makes sense, thanks for clarifying.

**Comment by diptanu** [comment]
@consultantRR Closing this issue. Please feel free to open a new issue if you want to track progress on the remote log forwarding.
