### ISSUE TITLE
Incorrect calculation used memory from docker

### ISSUE THREAD

**Issue by mbrezovsky** [hashicorp/nomad#8731]
### Nomad version
Nomad v0.11.1

### Operating system and Environment details
Ubuntu 18.04

### Issue
Nomad client incorrectly calculate memory utilization. The node has defined memory limit [memory_total_mb](https://www.nomadproject.io/docs/configuration/client#memory_total_mb). But nomad calculate memory utilization resources from all nomad jobs (docker driver) + from docker containers not managed by nomad. 

E.g. The node has reserved 30 GB and 90GB total memory utilization from stats, so it has 300% utilization of resources. I can't start no job, it fails with error `resources exhausted on 1 nodes`.

![Screenshot from 2020-08-25 08-33-02](https://user-images.githubusercontent.com/2352150/91135497-54d27c80-e6ae-11ea-8d47-805786c5a83e.png)

### Reproduction steps

1. Set `memory_total_mb` for client node
2. Run nomad job with docker driver
3. Run docker container outside of nomad
4. Check memory utilization on client node

### Client node config

```
bind_addr = "{{ GetInterfaceIP \"vlan1714\" }}"

advertise {
  http = "{{ GetInterfaceIP \"vlan1714\" }}"
}

datacenter = "xyz"

data_dir = "/opt/nomad"

log_level     = "INFO"
enable_syslog = false
enable_debug  = false

leave_on_terminate = true

client {
  enabled = true

  memory_total_mb = 24576

  servers = [
    "192.168.223.206", "192.168.223.205", "192.168.223.204"
  ]

  meta {
  }

  reserved {
    reserved_ports = "22,25,80,443,8080,8500-8600"
  }
}

consul {
  address = "127.0.0.1:8500"

  auto_advertise       = true
  checks_use_advertise = true
  client_service_name  = "nomad-client"
  client_auto_join     = true
}

disable_anonymous_signature = true
disable_update_check        = true
```

**Comment by tgross** [comment]
Hi @mbrezovsky! The [`memory_total_mb`](https://www.nomadproject.io/docs/configuration/client#memory_total_mb) only overrides what the client fingerprints as the total amount of memory on the host.

You may want to look into setting [`reserved-parameters`](https://www.nomadproject.io/docs/configuration/client#reserved-parameters) to reserve a slice of memory that Nomad can't use, but there's nothing Nomad can to do prevent workloads that it doesn't control from using as much memory as they want.

**Comment by mbrezovsky** [comment]
@tgross I understand Nomad can't control containers and theirs resource utilization outside of Nomad. But this issue is about wrong interpretation memory usage. If Nomad has reserved 30GB and his jobs consume 10GB, so remaining memory should be 20GB. I will try reserved memory.

**Comment by tgross** [comment]
Doing some issue clean up. We never heard back on this one but if you encounter related problems please feel free to re-open or open a new issue.
