### ISSUE TITLE
Add a button to cancel a deployment when using canaries

### ISSUE THREAD

**Issue by israellot** [hashicorp/nomad#8744]
It would be useful to have a button to cancel a deployment and remove canaries besides the button that promotes the canaries. 
This would make the UI a bit more complete in terms of operation of a deployment that uses canaries.

**Comment by DingoEatingFuzz** [comment]
Hi @israellot, will #9831 fulfill what you had in mind?

**Comment by israellot** [comment]
Yes @DingoEatingFuzz , I believe that would cover it well. Thanks for the ping on this issue
