### ISSUE TITLE
web UI hangs at spinner upon job selection

### ISSUE THREAD

**Issue by rsk0** [hashicorp/nomad#8781]
### Nomad version
0.11.4+ent

### Operating system and Environment details
macOS 10.15.5 (19F101)

### Issue
clicking job in web UI jobs list results in endless spinner

### Reproduction steps
1. In Firefox 80.0 or Chrome 85.0.4183.83, navigate to jobs list.  https://nomad.example.com/ui/jobs
2. Enter a search string or don't
3. click on a job name
The page's main panel now is just the trippy tic-tac-toe board spinner.
The location in the URL bar does not update.  Continues to not update.
Spinner continues to do its thing.
Never (in 10m at least) updates the location to the job, nor does the job details page come up.

You can click on a job name to bring it up in another tab -- that works.

**Comment by rsk0** [comment]
Oh, wait wait... If you watch the spinner for a while, there's some kind of flickering that happens in the panel, like a ghost, maybe of the job details page, trying to break through from another dimension, but never (in 10m) succeeding.

**Comment by DingoEatingFuzz** [comment]
Looks like you have run into https://github.com/hashicorp/nomad/issues/5946.

If you read through that issue you'll find a workaround related to purging orphaned child jobs.

This bug was also fixed in 0.12.1.

I'll leave this open in case that isn't actually the issue you're having.

**Comment by rsk0** [comment]
I couldn't tell, is that issue about non-periodic jobs as well? Service and system jobs are also not displaying.  Oh, looks like it might be about _parameterized_ jobs...?
Anyway, someone just purged a periodic job that was showing errors and now detail pages are coming up.  Looks like it might have been related.

**Comment by DingoEatingFuzz** [comment]
It affects all jobs in the UI but the root case is from periodic or parameterized jobs. Glad you got it sorted out!
