### ISSUE TITLE
The network stanza is not documented in resources

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/nomad#8785]
The output of `nomad job init -short` is:

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

with a `network` stanza in `job > group > task > resources` but it is not documented at https://www.nomadproject.io/docs/job-specification/resources.

**Comment by remilapeyre** [comment]
Also in the documentation for the `network` stanza the `mbits` attribute is not documented.

**Comment by remilapeyre** [comment]
`volume_mount` is also not in https://www.nomadproject.io/docs/job-specification/task, and I think it's missing `restart` too but I've not tried to use it in a task yet.

**Comment by notnoop** [comment]
Hi @remilapeyre !  Very sorry for the confusion here.  We will update the sample docs.

FWIW, `network` under `task > resources` as well as mbits are being deprecated - but our documentation is a bit confusing there.  We will clarify that.  Thanks for raising.

**Comment by Legogris** [comment]
@notnoop I can't find if there's a repo for learn.hashicorp.com (or a proper place to report that) but I noticed there's a good amount of guides and examples there explicitly relying on now deprecated (but without runtime warnings or errors to that end) behavior or configuration.

**Comment by shantanugadgil** [comment]
given that the `network` inside `resources` is being deprecated, what would be the right way to be able to allocate a single job to any node?

Assuming that I can force set the `network_speed` of all my worker nodes to say `1000`, what can I use to be able to block an entire machine?

Previously I used to do it using `mbits =999` so no other job could get the machine as "free"

**Comment by nickethier** [comment]
This was fixed in #8911 

@shantanugadgil that is an interesting unintended use of that! I think its also another example that it was not a useful resource from a networking perspective :sweat_smile: 

This usecase is being planned and is currently tracked in #2299

**Comment by shantanugadgil** [comment]
@nickethier I am confused ... I don't want jobs to land up on any specific node(s).
If I do want specific nodes, I can already achieve it via `contraints` or `meta` tags.

All I wanted to do using the `network` "mbits = 999" thing was to schedule (and allocate)  1-and-only-1 job (i.e. task) onto any node.

**Comment by shantanugadgil** [comment]
There was another _ugly_ hack which I had discovered, which was to use a `static` port for the task, which would cause any other job/task trying to come onto the same node to fail, and eventually go elsewhere (or fail).
