### ISSUE TITLE
Freezes on crons with leading zeros in month number.

### ISSUE THREAD

**Issue by tkukushkin** [hashicorp/nomad#8800]
### Nomad version

All versions from 0.11.2 affected.

### Issue

After #7894 cronexpr freezes forever on crons with leading zeros in number of month. 

These are consequences of such behaviour:

- no new job could be deployed in cluster;
- no cron jobs are running;
- `nomad agent-info | grep fsm_pending` infinitely grows.

### Reproduction steps

Create periodic job with leading zero in number of month, for example: `10 15 21 04 * *` or run [this code](https://play.golang.org/p/kiZeKXlIP7h)

**Comment by jrasell** [comment]
Hi @tkukushkin and thanks for the report. I have been able to reproduce this locally on 0.12.3 so will label accordingly.

**Comment by notnoop** [comment]
Thanks @tkukushkin for reporting the issue!  I'm very sorry that you hit this condition and that the cluster broke :(.  I have merged a fix and we plan to cut 0.12.4 in the next few days.

**Comment by tkukushkin** [comment]
Thanks for fast fix.
