### ISSUE TITLE
Zero Downtime Rolling Deployment using Health Checks

### ISSUE THREAD

**Issue by robsonpeixoto** [hashicorp/nomad#883]
I'd like to know if the nomad use the [check](https://www.nomadproject.io/docs/jobspec/servicediscovery.html#check ) to grantee a zero downtime upgrade.

**Comment by dadgar** [comment]
It currently does not but it is something on our roadmap!

**Comment by c4milo** [comment]
?

**Comment by robsonpeixoto** [comment]
Good question @c4milo

**Comment by skozin** [comment]
Yup, I'm also interested why this was closed. Was this removed from the Nomad roadmap?

**Comment by dadgar** [comment]
Was closed as it was a question but can rename and reopen

**Comment by skozin** [comment]
@dadgar, makes sense, thanks! :)

**Comment by igrayson** [comment]
We're eagerly awaiting this feature, so we can give nomad a try in production. For now, I don't believe we can risk the availability loss of using a deployment tool that doesn't integrate health checks to stop bad deployments (or the cost of building additional tooling to add that safety).

**Comment by igrayson** [comment]
Hi team,

Does this have any scheduling that we can learn about? Unless there's some recommended way to achieve zero-downtime deployments using nomad, this issue prevents us from considering nomad as a deployment tool.

**Comment by diptanu** [comment]
@igrayson We might start working on it soon!

**Comment by igrayson** [comment]
@diptanu Thanks!

I'm still a little confused. The current [nomad docs](https://www.nomadproject.io/docs/jobops/index.html) themselves make reference to "zero downtime" deployments.

Is there any recommended approach to achieving zero downtime deployments, using nomad?

**Comment by dadgar** [comment]
Hey,

Automated zero-down time deploys require using health checks but the
covered blue/green section in the docs allows zero down time deploys:
https://www.nomadproject.io/docs/jobops/updating.html

Thanks,
Alex

**Comment by dadgar** [comment]
Closing in favor of #317
