### ISSUE TITLE
[Question] Docker tasks stuck in "Building Task Directory" for minutes

### ISSUE THREAD

**Issue by dpn** [hashicorp/nomad#8835]
### Nomad version
```
/ # nomad version
Nomad v0.10.5 (4eb2ca3f8d8786c897bb47878f1c12577011ddd3)
```

(We're in the process of releasing v0.11.4 to our production DCs, so we will be able to verify this behavior with that version likely sometime next week, v0.12.x is still in validation in our staging DCs at the moment)

### Operating system and Environment details

Cilent / Servers: RHEL 7.6, 3.10.0-1127.18.2.el7.x86_64, client nodes are 32 thread, 128G ram

### Issue

The behavior that we're seeing is that the "building task directory" step is taking a _really_ long time, up to 2+ minutes to complete (see example below). I've been doing some reading and it appears long setup times aren't surprising for java and exec task drivers as Nomad is building out a chroot for these tasks, but in this case we're using the Docker driver which, from what I've read, shouldn't see this same behavior.

Some further reading from a _really_ old thread (couple years old) seemed to suggest that Nomad GC cycles can block this step. Currently we're running default GC configuration, so part of me is wondering if due to the high number of jobs we're constantly running, we're also constantly getting GCs causing this step to block. So I've been considering twisting these knobs a bit to see if this improves the situation.

Our development team is dispatching approximately 15 jobs a second against a client pool of 6 of the previously described nodes and as you can see from the log below, they execute quite quickly and then exit.

We've considered increasing the amount of work each of these jobs do so that there's less setup overhead, but I guess I'd like to get your expert opinion as to wether we're "holding it wrong" or if we should be expecting better performance of this step or possibly look elsewhere.

We're also considering running a test by tossing the alloc directory into a tmpfs to rule out IOPS as our limiting factor here. But any guidance or ideas around this situation would be much appreciated.

Example:
```
Recent Events:
Time                  Type        Description
2020-09-05T22:16:09Z  Killing     Sent interrupt. Waiting 5s before force killing
2020-09-05T22:16:09Z  Terminated  Exit Code: 0
2020-09-05T22:16:03Z  Started     Task started by client
2020-09-05T22:15:56Z  Driver      Downloading image
2020-09-05T22:13:57Z  Task Setup  Building Task Directory
2020-09-05T22:13:57Z  Received    Task received by client
```

**Comment by tgross** [comment]
Hi @dpn, sorry to hear about that! 

The first thing I'd want to investigate here is to make sure that the time is really from building the task directory. You're right in thinking that task event is emitted from the client agent right before the task directory gets created. But between that point and time and the driver downloading the image, we have a series of other hooks that run in order (ref [`task_runner_hooks.go#L63-L69`](https://github.com/hashicorp/nomad/blob/v0.10.5/client/allocrunner/taskrunner/task_runner_hooks.go#L63-L69)). The ones that jumps out at me a bit for your workload are the artifact and dispatch hooks.

The client log (at debug level) will give you a fairly fine-grained view of what hooks are firing on the client for each allocation and how long they're taking, and also when the client GC cycles are firing to see whether that's even a factor. If you can post a log I'd be happy to help you debug from there.

Thanks for posting this issue!

**Comment by dpn** [comment]
Thanks for the push in the right direction @tgross! We're coming up on the end of the quarter so I'm buried under unrelated things at the moment, but will follow up with your suggestions when I'm able to.

**Comment by tgross** [comment]
Just circling back on this and I think this is safe to close. If you end up getting a chance to investigate again, please feel free to re-open!

**Comment by dpn** [comment]
Thanks @tgross. Apologies for the delay on our end the team experiencing this is moving to a different solution so the priority around this dropped.
