### ISSUE TITLE
docker tasks occasionally failing to start due to adding existing iptables chains

### ISSUE THREAD

**Issue by Legogris** [hashicorp/nomad#8838]
### Nomad version
0.12.3

### Operating system and Environment details
Debian 11, docker 19.03.12.

### Issue

Occasionally when a nomad client comes online, it fails starting a Docker job when using group-level networking and service.

This can be seen in the console:

```
failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: failed to create top-level DNAT chain: running [/usr/sbin/iptables -t nat -N CNI-HOSTPORT-DNAT --wait]: exit status 4: iptables v1.8.5 (nf_tables): CHAIN_USER_ADD failed (File exists): chain CNI-HOSTPORT-DNAT
```

The allocation subsequentally gets marked as dead (while other allocations in the same job are healthy) and are not retried.

This can happen even when ensuring that the docker daemon has had amble time to initialize, e.g.  not right after after startup or other service restarts.

Looks like it could be a race condition?

**Comment by tgross** [comment]
Hi @Legogris! I know we've seen race conditions in iptables setup with CNI previously, and have sent patches upstream for that. But it's possible there's still lurking issues there or something we're missing at the client. Which version of CNI do you have installed?

**Comment by Legogris** [comment]
I haven't had this happen again lately. CNI 0.8.5.

**Comment by Legogris** [comment]
@tgross Different error this time - is this the same issue or want me to open  new ticket?

```
failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: failed to allocate for range 0: 172.26.64.250 has been allocated to 9f06620e-72a8-8339-1744-660528f94672, duplicate allocation is not allowed
```

**Comment by tgross** [comment]
Thanks @Legogris and sorry to hear that. This error looks like it's being handled better when it's bubbling up from the CNI library [here](https://github.com/hashicorp/nomad/blob/v0.12.5/client/allocrunner/networking_cni.go#L99) but it's still a CNI issue for us to figure out.

**Comment by Legogris** [comment]
New one: `Failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: unable to create chain CNI-HOSTPORT-SETMARK: running [/usr/sbin/iptables -t nat -N CNI-HOSTPORT-SETMARK --wait]: exit status 4: iptables v1.8.6 (nf_tables): CHAIN_USER_ADD failed (File exists): chain CNI-HOSTPORT-SETMARK`

**Comment by tgross** [comment]
I want to go back to what you said here, @Legogris:

> Occasionally when a nomad client comes online, it fails starting a Docker job when using group-level networking and service.

Do you mean this is happening specifically when you have a client that's been running tasks and has been restarted? Do you have a jobspec that reproduces the behavior at all regularly?

**Comment by Legogris** [comment]
@tgross It usually happens within the first X minutes of an existing nomad client process starting. It can happen both with existing and newly submitted jobs and I haven't seen anything particular about which jobs it happens to jobs (apart from that the tasks are docker and use bridge networking with ports and services declared at group-level).

Stopping the job, doing a gc, and then resubmitting it tends to resolve it.

If/when it happens again I can nab the jobspec for a failing one.
