### ISSUE TITLE
Adding prune capabilties to nomad force-leave option

### ISSUE THREAD

**Issue by mishoops** [hashicorp/nomad#8840]
Is there a plan to implement consule style "-prune" option in Nomad to remove left nodes immieditaly from the cluster when running nomad server force-leave ?

**Comment by tgross** [comment]
Hi @mishoops! I don't think it was on our roadmap but it seems like a reasonable behavior to implement. Do you have a particular use case you're concerned about that isn't covered by periodic node GC?

(ref [Consul `forcre-leave`](https://www.consul.io/docs/commands/force-leave#prune) vs [Nomad `server force-leave`](https://www.nomadproject.io/docs/commands/server/force-leave))

**Comment by mishoops** [comment]
Hi @tgross , thank you for quick reply. We might have a little bit edge use case, we are scaling nomad dynamically and communication between nodes takes place over VPN which provides dynamic IPs, thus upon restart of connection or vpn server, IPs get scrambled, thus rendering nomad cluster unsable, we then need to wait day or so for the system remove left nodes before we can spin up new region, otherwise new nodes might get IP address of old nomad nodes and join wrong cluster/dc.

**Comment by tgross** [comment]
Implemented in #18463, which will ship in the next regular release of Nomad.
