### ISSUE TITLE
Variable interpolation in artifact source

### ISSUE THREAD

**Issue by orcuny** [hashicorp/nomad#8854]
Hi,

### Nomad version
0.11.4

### Operating system and Environment details
Environment: Linux amd

### Issue
I'm trying to run the same job file in different environments. So, I need to get variables from Consul KV. As far as I see, meta variables are processed in artifact source successfully but env variables are not processed.

### Reproduction steps
Given job file has 1 meta named NEXUS_URL and 1 env named NEXUS_URL.
If artifact source is given as "${NOMAD_META_NEXUS_URL}" to read meta, artifact can be downloaded.
If artifact source is given as "${NEXUS_URL}" to read env, artifact can not be downloaded but fails with error.

### Job file (if appropriate)

```hcl
job "job" {
datacenters = ["dc1"]

type = "service"

constraint {
attribute = "${node.class}"
value = "service"
}

constraint {
operator = "distinct_hosts"
value = "true"
}

priority = "100"

group "group" {
count = "1"

ephemeral_disk {
  size = "2048"
}

task "task" {
  driver = "raw_exec"

  config {
    command = "java"
    args = [
      "-Xms512m",
      "-Xmx1024m",
      "-Dspring.profiles.active=${TARGET_PLATFORM}",
      "-Dserver.port=${NOMAD_PORT_http}",
      "-jar",
      "local/job.jar"
    ]
  }

  artifact {
    source = "${NEXUS_URL}"
    options {
      group = "com.dc1.job"
      name = "job-app"
      maven.baseVersion = "${NOMAD_META_APP_VERSION}"
      maven.classifier = "spring-boot"
      maven.extension = "jar"
      sort = "version"
    }
    mode = "file"
    destination = "local/job.jar"
  }

  service {
    name = "job"
	tags = ["urlprefix-/job-app proto=https tlsskipverify=true"]
    port = "http"

    check {
      type = "http"
      protocol = "https"
      path = "/job-app/actuator/health"
      interval = "10s"
      timeout = "5s"
      tls_skip_verify = true

      check_restart {
        limit = "3"
        grace = "2m"
        ignore_warnings = false
      }
    }
  }

  resources {
    cpu = "1024"
    memory = "1024"

    network {
      mbits = "10"
      port "http" {}
    }
  }

  template {
    change_mode = "restart"
    destination = "local/env"
    env = true
    data = <<EOH
TARGET_PLATFORM="{{ key "target_platform" }}"
NEXUS_URL="https://downloader:download1@fabio.service.dc1.consul/nexus/service/rest/v1/search/assets/download"
EOH
}

  meta {
    APP_VERSION = "0.0.1-SNAPSHOT"
    NEXUS_URL = "https://downloader:download1@fabio.service.dc1.consul/nexus/service/rest/v1/search/assets/download"
  }
}
}
}
```
### Nomad Server logs (if appropriate)
Failed Artifact Download | failed to download artifact "${NEXUS_URL}": relative paths require a module with a pwd

**Comment by tgross** [comment]
Hi @orcuny! This behavior could probably be better documented, but it's also what I'd expect to see. The environment from the `template` stanza isn't available for interpolation in the jobspec.

The reason is that the values from the template environment can change after the job is received, so if we re-interpolated the jobspec we'd need to create a new version of the job. (That is, we can't just restart because the `change_mode = "restart"` might have been what was re-interpolated!)

**Comment by orcuny** [comment]
Hi @tgross. Thanks for the quick and well-described response.

I see, that kind of a workaround will not work. So, any recommendations about how to parameterize artifact source for different environments? Or should I have different jobspecs for different environments?

**Comment by tgross** [comment]
We do have some work in progress to rework our HCL parsing, so we're hoping to be able to pick up use cases like this when we do that.

In the meantime, you can run different job specs, or use a tool like [`levant`](https://github.com/hashicorp/levant) to templatize the jobspec before submitting them. Or if the "different environments" are actually different Nomad nodes, you could use the [client `meta`](https://www.nomadproject.io/docs/configuration/client#meta) configuration to set the environment on a per-client basis .

**Comment by orcuny** [comment]
Yes, client meta did the trick. Next, I'll have a look at levant.

Thanks for your time and guidance.

**Comment by gthieleb** [comment]
Hi there, i am looking for a similar solution.

In my case I defined the artifact URL by using consul template (using the env template) in and make it possible for testers in our test environment to adapt the version of the artifact for their own needs.

```      
template {
        data = <<EOH
JOB_ARTIFACT_URL = "{{ key "my/consul/keys/artifact_base_url" }}/{{ key "my/consul/keys/artifact_file" }}"
EOH
        env = true
        destination = "local/env"
}
```


```
      artifact {
        source = "$${JOB_ARTIFACT_URL}"
        destination = "local"
      }
```

This fails with the following message:

```
Nov 08, '21 12:51:21 +0100 | Failed Artifact Download | failed to download artifact "${JOB_ARTIFACT_URL}": relative paths require a module with a pwd
```

Is there some progress to support nomad variables in the artifact url parameter?
