### ISSUE TITLE
Use os.ErrDeadlineExceeded in tests

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#8859]
[As of Go 1.15](https://golang.org/doc/go1.15#net) we can now check an error against [os.ErrDeadlineExceeded ](https://golang.org/pkg/os/#ErrDeadlineExceeded) instead of this helper func: https://github.com/hashicorp/nomad/blob/v0.12.3/testutil/net.go

That helper func should be removed.

**Comment by loadstar81** [comment]
i've started work on this one 🎉

**Comment by roccoblues** [comment]
@loadstar81 are still working on this? If not, I have a patch ready I would submit.

**Comment by loadstar81** [comment]
> @loadstar81 are still working on this? If not, I have a patch ready I would submit.

@roccoblues nope, it fell off the list :/ 

go for it!
