### ISSUE TITLE
Clarify behavior of distinct_hosts

### ISSUE THREAD

**Issue by jsalts** [hashicorp/nomad#8888]
We have preflight deployment job using distinct_hosts where we scan for a count of all eligible nodes and set that as count. We noticed a case where we ended up with multiple instances being run on a single client, and skipping an eligible client. Could you clarify what distinct_hosts does and if it's possible to guarantee that a job runs on all eligible nodes?

```
job "preflight" {

  datacenters = [...]
  type = "batch"

  constraint = [
    {
    operator = "distinct_hosts"
    value = "true"
    }
  ]

  group "preflight" {
    count = ${groupCount}

    restart {
      attempts = 0
      mode = "fail"
    }

    reschedule {
      attempts = 0
    }

    task "preflight" {
      driver = "raw_exec"
      kill_timeout = "60s"

      meta {
        version = "${project.version}"
        buildNumber = "${project.buildNumber}"
      }

      config {
        command = "/usr/lib/jvm/java-11/bin/java"
        .....
      }
    }
  }
}

```

**Comment by tgross** [comment]
Hi @jsalts!

> We noticed a case where we ended up with multiple instances being run on a single client, and skipping an eligible client. Could you clarify what distinct_hosts does and if it's possible to guarantee that a job runs on all eligible nodes?

You've got it right, but keep in mind that a constraint is weighted with every other constraint and the resources available in the cluster. To diagnose the decision-making process, you can take a look at `nomad alloc status -verbose :id` for one of the "mis-scheduled" allocations, you'll see the weightings that Nomad has applied for each factor.

The closest you can come to guaranteeing exactly-one-alloc-per-host (assuming resource availability on the hosts) is with a `system` job, which you'll note isn't currently available for `batch` workloads (yet!). In the meantime, you might want to look at the [`spread`](https://www.nomadproject.io/docs/job-specification/spread) stanza as well.

**Comment by jsalts** [comment]
With a count of 4 and 4 eligible nodes, I understand that there could be resource constraints on one node that could cause the scheduler to avoid that node. I don't understand why distinct_hosts doesn't fail the deployment if it can't place jobs on distinct hosts? distinct_hosts seems more like a _suggestion_ than a _constraint_. I could try the spread stanza over the datacenter as well, but we're looking for something to fail if a constraint can't be satisfied.

**Comment by tgross** [comment]
Apologies for the delayed follow-up on this. 

>  Placing duplicate instances on a host seems like it would violate the constraint. distinct_hosts seems more like a suggestion than a constraint if it doesn't cause a failure in this case. I could try the spread stanza over the datacenter as well, but we're looking for something to fail if a constraint can't be satisfied.

In retrospect you're totally right and that would be a bug based on what the docs say. Unfortunately I wasn't able to reproduce this problem, so I'm wondering if there's some other issue at work here. 

Using the following jobspec against the current version of Nomad:

```hcl
variable "version" {
  type = string
  default = "1.0"
}

variable "buildNumber" {
  type = string
}

job "preflight" {
  datacenters = ["dc1"]
  type        = "batch"

  constraint {
    operator = "distinct_hosts"
    value    = "true"
  }

  group "preflight" {
    count = 2

    task "preflight" {
      driver       = "raw_exec"
      kill_timeout = "60s"

      meta {
        version     = var.version
        buildNumber = var.buildNumber
      }

      config {
        command = "/bin/sh"
        args    = ["-c", "echo ok; sleep 1"]
      }
    }
  }
}
```

I can do the following and see that each allocation lands on a separate host:

```sh
for i in {1..10}; do
  nomad job run -var buildNumber=$i ./example.nomad
done
```

I tried a few different cluster sizes and found the same issue.

**Comment by tgross** [comment]
Without being able to reproduce, I'm going to close this one out. Feel free to reopen if you have additional information we can use to debug.
