### ISSUE TITLE
Problems with new Multi Interface Networking Feature with same ports to different interfaces.

### ISSUE THREAD

**Issue by hongkongkiwi** [hashicorp/nomad#8891]
### Nomad version
Nomad v0.12.4

### Operating system and Environment details
Linux edge0 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Issue
I would expect the following configuration to work, however Nomad complains of a collision. This is actually not true, but nomad gets confused as previously without multi interface networking this would have collided.

**Nomad Job**
```
    network {
      mbits = 10
      mode = "bridge"
      port "http" {
        static = 80
        host_network = "public"
      }
      port "https" {
        static = 443
        host_network = "public"
      }
      port "http" {
        static = 80
        host_network = "localhost"
      }
      port "https" {
        static = 443
        host_network = "localhost"
      }
    }
```

**Nomad Config**
```
{
....
  "client": {
    "enabled": true,
    "host_network": {
      "private": {
        "interface": "eth1",
      },
      "public": {
        "interface": "eth0",
      },
      "localhost": {
        "interface": "lo"
      }
    }
....
}
```

When attempting the above job, which I would expect to work however it shows:
`error parsing 'job': group: network, ports -> found a port label collision: http`

**Comment by fwkz** [comment]
I got a slightly different problem but I feel like it might be related. I want to bind ports on separate interfaces to the same port inside docker container. Such a thing is not hard to do it manually.
```
docker run -p 192.168.10.10:1111:5000 -p 192.168.11.10:2222:5000 some_docker_image
```
Unfortunately, I can't get the same behavior using nomad.
```
# nomad-client.hcl
host_network "users" {
  cidr            = "192.168.10.0/24"
  reserved_ports  = "0-1023,49152-65535"
}
```

```
# nomad-job.hcl
group "foo" {
  network {
    port "internal" {
      to = 5000
    }
    port "users" {
      to = 5000
      host_network = "public
    }
  }
}
```
Port `5000` is bound only to port `internal` on default interface, port `users` on  `host_network` `users` is ignored.

**Comment by nickethier** [comment]
Hey @hongkongkiwi I'm having a hard time trying to understand the usecase for why the port labels need to share the same name. For example if you were to define a service with `port="http"` it would be ambiguous as to which address Nomad should register with Consul.

**Comment by nickethier** [comment]
@fwkz that issue is being tracked in #8284
