### ISSUE TITLE
Unclear documentation on variable interpolation

### ISSUE THREAD

**Issue by r0p0s3c** [hashicorp/nomad#891]
Hi,

running nomad 0.3.0, with a task using the docker driver, I have the following in the task definition:

```
env {
  test="${nomad.id}"
}
```

Yet this does not appear to be interpolated, as in the target process/task:

```
$ echo $test
${nomad.id}
```

My reading of #653 suggested this should work, so curious what I am missing?

**Comment by dadgar** [comment]
https://www.nomadproject.io/docs/jobspec/interpreted.html

Please let us know how it can be improved. $nomad.id has changed to ${nomad.unique.id} in 0.3

**Comment by r0p0s3c** [comment]
Thanks for the updated syntax/variable name. My original testing was around interpolation of metadata values. I see now that they are handled differently than nomad variables, and additional testing has clarified that metadata variables (seem to) need to be set at the task level to be available/interpolated into the task's environment. For example:

```
job "example" {
...
    group "example" {
...
         task "example" {
...
                        env {
                                "TASKVAR" = "${NOMAD_META_TASKVAR}"
                                "GROUPVAR" = "${NOMAD_META_GROUPVAR}"
                                "JOBVAR" = "${NOMAD_META_JOBVAR}"
                        }
                        meta {
                                 "taskvar" = "1"
                        }

                }
                meta {
                                "groupvar" = "1"
                }

        }
        meta {
                                "jobvar" = "1"
        }
...

# echo $GROUPVAR $JOBVAR $TASKVAR
${NOMAD_META_GROUPVAR} ${NOMAD_META_JOBVAR} 1

```

The documentation was not clear (at least to me) on the above behavior, so perhaps if this could be made explicit it'd be helpful

**Comment by dadgar** [comment]
Going to close this as the docs have changed significantly but happily take more specific issues or PRs to clarify further!
