### ISSUE TITLE
Connect and Envoy L7 http headers

### ISSUE THREAD

**Issue by rickardrosen** [hashicorp/nomad#8914]
### Nomad version
Nomad v0.12.4 (8efaee4ba5e9727ab323aaba2ac91c2d7b572d84)
Consul v1.8.4

### Issue
I'm trying to configure envoy for L7 management using `connect.sidecar_service.proxy.config` and setting `protocol = http` enables L7 mode and the http manager.

This gives me the following headers added to a request:

- x-forwarded-proto
- x-request-id
- x-envoy-expected-rq-timeout-ms

According to Envoy doc the following could be available:

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#id5

Is there any way to configure this or is this a feature request?

**Comment by shoenig** [comment]
I'm not really familiar with Envoy config - seems like this might get activated if we pass in `--service-node` when launching Envoy? Does the `user_agent` option have to be set like in `x-envoy-downstream-service-cluster`?

**Comment by rickardrosen** [comment]
I'm reading the envoy documentation right now and there are some things to consider regarding header sanitation the http manager performs.

The envoy_bootstrap.json contains appropriate configuration for service node and cluster, so I don't think we need to pass in any additional commands.

It could be the case that envoy considers these "intra-mesh" requests as local and strips the headers?

**Comment by rickardrosen** [comment]
According to [this](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-downstream-service-cluster) document we should be able to see the `x-envoy-downstream-service-cluster` header:

> Internal services often want to know which service is calling them. This header is cleaned from external requests, but for internal requests will contain the service cluster of the caller.

**Comment by rickardrosen** [comment]
I'll move this to the consul tracker as it is more of an consul connect feature request

**Comment by tamsky** [comment]
/cc @rickardrosen 

If known, please share a link to where this issue was moved.
Thanks!
