### ISSUE TITLE
Nomad should choose the default pause container based on system architecture

### ISSUE THREAD

**Issue by shannonmcin** [hashicorp/nomad#8926]
### Nomad version
Nomad v0.12.4 (8efaee4ba5e9727ab323aaba2ac91c2d7b572d84)

### Operating system and Environment details
Ubuntu 20.04 on ARM64
Consul v1.8.4

### Issue
Nomad should choose the default ["pause" container](https://www.nomadproject.io/docs/drivers/docker.html#infra_image) based on system architecture, instead of always defaulting to the AMD64 image. 

When deploying a job with a Consul Connect-enabled service on Nomad on an ARM64 system without specifying the `infra_image`, Nomad pulls the AMD64 pause container. This causes the pause container to exit with the error `exec user process caused "exec format error"`, which causes the envoy container to exit with the error `Failed to start container ***(envoy container id)***: API error (409): cannot join network of a non running container: ***(pause container id)***`, which prevents Consul Connect from working (and any sibling tasks from running).

### Reproduction steps
Run any job with a Consul-Connect enabled service on Nomad installed on an ARM64 machine, with the `infra_image` not specified in the Nomad agent config. For example, the example [countdash job](https://www.nomadproject.io/docs/integrations/consul-connect#run-the-connect-enabled-services).

**Comment by shoenig** [comment]
Thanks for reporting @shannonmcin, this is something we'll want to get working properly.
