### ISSUE TITLE
[question] Nomad v0.12.5 parse error with multiple consul connect upstreams (proxy -> invalid key: upstream)

### ISSUE THREAD

**Issue by xaviermerino** [hashicorp/nomad#8930]
### Nomad version
`Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)`

### Operating System and Environment Details
```
vagrant@client-1:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
### Issue
I wanted to run `qperf` between two nodes and use consul connect to communicate.
I'm having trouble understanding why my job file has a parsing error.  I believe it is valid `hcl`. I've tried `hcl2json` to see if I could catch a syntax error, but it appeared as if it was correct. 

The documentation points out this example when using only one upstream. 
```hcl
  service {
      name = "count-dashboard"
      port = "9002"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "count-api"
              local_bind_port  = 8080
            }
          }
        }
      }
    }
```

I needed multiple upstreams so I ended up changing it to something like this as suggested by [this](https://discuss.hashicorp.com/t/several-consul-connect-upstreams/3739) discussion.

```hcl
service {
  connect {
    sidecar_service {
      proxy {
        upstream {
          destination_name = "qperf"
          local_bind_port = 19765 
        }
        upstream {
          destination_name = "qperf-socket"
          local_bind_port = 19766 
        }
      }
    }
  }
}
```

But this causes Nomad to reject the job by pointing out that `proxy -> invalid key: upstream`. 
Does someone know how this would work?

```
Parse Error
error parsing 'job': group: 'qperf-client', service (0): '', sidecar_service, proxy, 2 errors occurred: * proxy -> invalid key: upstream * proxy -> invalid key: upstream
```
### Reproduction steps
Try running the job attached below. 

### Job file (if appropriate)
[qperf-connect.nomad.txt](https://github.com/hashicorp/nomad/files/5249069/qperf-connect.nomad.txt)

**Comment by shoenig** [comment]
Hi @xaviermerino the job definition with the parse error is using `upstream`, but the name of the field is `upstreams` (whether there is one or multiple). Can you try changing that and see if it works?

**Comment by xaviermerino** [comment]
Thanks @shoenig for the help. Indeed! It need to be `upstreams`. 
Maybe you could clarify some things for me. After making that change, it complained that the group needs to have a network. I thought that the network was by default `bridge` in docker for all OSs but Windows. But I went ahead and added the network stanza to both groups. And it then complained that `dns_servers` was not allowed in the network mode. Would that mean that I would have to add them to the `dns` section of the `group->network` stanza? I got it to work, but I'm just confused. 

Thanks! I'm attaching a copy of the job. 
[qperf-connect.nomad.txt](https://github.com/hashicorp/nomad/files/5263611/qperf-connect.nomad.txt)



```hcl
job "qperf-connect" {
  datacenters = ["dc1"]
  type = "batch"

  constraint {
      distinct_hosts = true
  }

  group "qperf-server" {

    # Had to add this to work
    network {
      mode = "bridge"
    }

    service {
      name = "qperf"
      port = 19765
      connect {
          sidecar_service {}
      }
    }

    service {
      name = "qperf-socket"
      port = 19766
      connect {
          sidecar_service {}
      }
    }

    task "qperf-server" {
      driver = "docker"

      config {
        image = "xridge/qperf"
        # Had to remove this to work
        # dns_servers = ["${attr.unique.network.ip-address}"]
      }

    } # End task
  } # End group

# Continues...
```
