### ISSUE TITLE
Nomad Cluster Upgrade Issue

### ISSUE THREAD

**Issue by akshatgit** [hashicorp/nomad#8936]
I am planning to upgrade my cluster from 0.11.3 to 0.12.5, but I have a doubt regarding `mbits and Task Network Resource deprecation`. Currently all jobs have the network block inside Task block.
My doubt is how would old clients and jobs would react to this deprecation? What will be the affect to running jobs?
We also use docker volume inside jobs. How would old clients react to the change in 0.12.5? 

I plan to do an in-place cluster upgrade, starting with servers and then upgrade clients.

**Comment by shoenig** [comment]
Hi @akshatgit I believe your questions should be answered the version specific upgrade docs for 0.12:

https://www.nomadproject.io/docs/upgrade/upgrade-specific#mbits-and-task-network-resource-deprecation
https://www.nomadproject.io/docs/upgrade/upgrade-specific#docker-access-host-filesystem

To clarify: `mbits` is no longer used for scheduling decisions. Tasks will still work with `network` blocks defined, but Nomad will soon emit warnings about the use of deprecated syntax. Docker volumes are now disabled by default, but the previous behavior can be re-enabled as described in the upgrade docs. 

Let us know if something is still not clear!

**Comment by akshatgit** [comment]
> Tasks will still work with network blocks defined, but Nomad will soon emit warnings about the use of deprecated syntax.

So if I have configured to use a static port 5050 on a job, it will work but there will be warnings for it. Is this right? Also, I think it would be relatively easy to move if there is tool or a button on UI to port the job config to latest version. 

> Docker volumes are now disabled by default, but the previous behavior can be re-enabled as described in the upgrade docs.

Should I add the following config to old clients before I upgrade the servers to keep the default behavior or the default behavior will work with old clients but I need to add this config while upgrading clients?
```
plugin "docker" {
  config {
    volumes {
      enabled = true
    }
  }
}
```

**Comment by akshatgit** [comment]
Forgot to tag @shoenig 😅

**Comment by kaspergrubbe** [comment]
@shoenig Where will Nomad emit warnings?

> Tasks will still work with network blocks defined, but Nomad will soon emit warnings about the use of deprecated syntax. 

Is it on `nomad plan` or `nomad validate`?

**Comment by tgross** [comment]
Just to wrap this one up...

> Should I add the following config to old clients before I upgrade the servers to keep the default behavior or the default behavior will work with old clients but I need to add this config while upgrading clients?

Unfortunately we can't catch this in validation at the server. But that works out here; you only need to add the new config to the clients that you upgrade. Clients on the existing behavior won't enforce it.
