### ISSUE TITLE
Expose CPU usage metrics in MHz

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad#8938]
The CPU usage metrics currently exposed by Nomad are either in percentage, nanoseconds or number of ticks, but the jobspec resource limit for CPU is expected to be provided in MHz.

This creates a problem because it's hard to reason whether current CPU limit values are appropriate given the need to manually translate the output metrics into the expected input unit.

**Comment by cgbaker** [comment]
After investigating this, the TotalTicks metric is equivalent.
