### ISSUE TITLE
NOMAD_ALLOC_ID not available in docker container with nomad 0.3.0

### ISSUE THREAD

**Issue by sethcleveland** [hashicorp/nomad#894]
I'm trying to use this variable with the docker driver inside an env block. 

ex)
```
task "container" {
  driver = "docker"
  env {
    A_UNIQUE_UUID = "${NOMAD_ALLOC_ID}"
  }
```

After running a task like that, I logged into the container and ran "env". I see this in the list A_UNIQUE_UUID="${NOMAD_ALLOC_ID}". I also don't see NOMAD_ALLOC_ID in the env listing. I've been trying to track this down in the code (https://github.com/hashicorp/nomad/blob/652bd72c5f0e0ccc3b08b05bd008492888808c56/client/driver/driver.go#L165, https://github.com/hashicorp/nomad/blob/master/client/driver/env/env.go#L149). To the best of my understanding, that variable should be available. Am I mistaken...

**Comment by dadgar** [comment]
Hey this was added after 0.3.0 and will be in 0.3.1. Are you building off master or using the pre-compiled binary?

**Comment by sethcleveland** [comment]
Pre-compiled binary.

**Comment by sethcleveland** [comment]
Nice. Looking forward to using it with 0.3.1.
