### ISSUE TITLE
CSI Volume Stanza Variable Interpretation

### ISSUE THREAD

**Issue by hongkongkiwi** [hashicorp/nomad#8941]
Is it possible to use variable interpretation in the volume stanza? e.g.
```
    volume "data_mount" {
      type      = "csi"
      read_only = false
      source    = "${meta.service_name}${meta.server_number}"
    }
```

This will allow me to scale my nodes as long as I have pre-created the appropriate volumes.

Unfortunately this doesn't seem to work, is this supposed to work? or must it be static?

**Comment by hongkongkiwi** [comment]
I just found this issue which matches my use-case #7877

**Comment by tgross** [comment]
Yeah sorry about that @hongkongkiwi. Not yet, but keep an eye on that issue. I'm going to close this issue as a duplicate.
