### ISSUE TITLE
Provide a unique integer index id interpretation based on group count

### ISSUE THREAD

**Issue by sethcleveland** [hashicorp/nomad#895]
In the job specification, it'd be very nice to have an integer offset of the allocation in reference to the total group count. This will help people using kafka topic and partitions. Topics are strings and Partitions are integers. The only solution I have for this right now is to enumerate the task and assign each KAFKA_PARTITION a unique id manually. A little cumbersome, but doable. 

ex)
```
    group "containers" {
        count = 5
        task "kafka-consumers" {
            driver = "docker"
            env {
                   KAFKA_TOPIC="some_topic_name"
                   KAFKA_PARTITION="${ALLOCATION_OFFSET}"
            }
```

**Comment by diptanu** [comment]
Hey, this is a good idea! We will tackle this in 0.3.1

**Comment by sethcleveland** [comment]
Great :-). Moment by moment 0.3.1 becomes more awesome!

**Comment by robsonpeixoto** [comment]
:+1:
