### ISSUE TITLE
Unable to pass Nomad [Server/Client] HTTP Check (in Consul) when behind a corporate proxy

### ISSUE THREAD

**Issue by bfqrst** [hashicorp/nomad#8950]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)

### Operating system and Environment details
Linux mgmt-nomad-8lQ 5.4.0-1025-aws #25-Ubuntu SMP Fri Sep 11 14:47:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

### Issue
When http is bound to the primary IP address no matter what env vars are passed to the process, the check always hits the corporate proxy. This does not happen, when bound to 127.0.0.1. 

- tried to pass NO_PROXY to the command like so: NO_PROXY=172.18.131.13 nomad agent -config /opt/hsy/nomad/config
- tried to pass the env vars in systemd:
Environment=NO_PROXY=172.18.131.13
Environment=no_proxy=172.18.131.13

When you actually curl the endpoint, the output is fine!

Here's my systemd file with some additional ExecStartPre and Post work for debugging:

```
[Unit]
Description="HashiCorp Nomad - A workload orchestration solution"
Documentation=https://nomadproject.io/docs/
Requires=network-online.target
After=network-online.target


[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
Environment=NO_PROXY=172.18.131.13
Environment=no_proxy=172.18.131.13
User=nomad
Group=nomad
ExecReload=/bin/kill -HUP $MAINPID
ExecStartPre=/bin/bash -c 'env'
ExecStartPost=/bin/bash -c 'sleep 15 && curl -v http://172.18.131.13:4646/v1/agent/health?type=server'
ExecStart=/usr/local/bin/nomad agent -config /opt/hsy/nomad/config
TimeoutStartSec=600
KillMode=process
KillSignal=SIGINT
LimitNOFILE=65536
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
StartLimitBurst=3
StartLimitInterval=10
TasksMax=infinity
OOMScoreAdjust=-1000

[Install]
WantedBy=multi-user.target
```

### Nomad Server logs (if appropriate)
```
Sep 23 10:30:44 mgmt-nomad-8lQ systemd[1]: Starting "HashiCorp Nomad - A workload orchestration solution"...
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: PWD=/
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: LOGNAME=nomad
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: HOME=/home/nomad
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: LANG=C.UTF-8
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: INVOCATION_ID=a3dfedee87144582a963e9cf27016429
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: USER=nomad
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: SHLVL=0
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: JOURNAL_STREAM=9:27280
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Sep 23 10:30:44 mgmt-nomad-8lQ bash[1520]: _=/usr/bin/env
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]: WARNING: keyring exists but -encrypt given, using keyring
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]: ==> Loaded configuration from /opt/hsy/nomad/config/config.hcl
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]: ==> Starting Nomad agent...
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]: ==> Nomad agent configuration:
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:        Advertise Addrs: HTTP: 172.18.131.13:4646; RPC: 172.18.131.13:4647; Serf: 172.18.131.13:4648
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:             Bind Addrs: HTTP: 172.18.131.13:4646; RPC: 172.18.131.13:4647; Serf: 172.18.131.13:4648
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:                 Client: false
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:              Log Level: INFO
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:                 Region: europe (DC: aws15-mgmt)
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:                 Server: true
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:                Version: 0.12.5
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]: ==> Nomad agent started! Log data will stream in below:
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.242+0200 [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/hsy>
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.243+0200 [INFO]  agent: detected plugin: name=nvidia-gpu type=device plugin_version=0.1.0
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.280+0200 [INFO]  nomad.raft: initial configuration: index=5731 servers="[{Suffrage:Voter ID:172.18.131.135:4647 Add>
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.280+0200 [INFO]  nomad.raft: entering follower state: follower="Node at 172.18.131.13:4647 [Follower]" leader=
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.280+0200 [INFO]  nomad: serf: Ignoring previous leave in snapshot
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.283+0200 [INFO]  nomad: serf: EventMemberJoin: mgmt-nomad-8lQ.europe 172.18.131.13
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.283+0200 [INFO]  nomad: starting scheduling worker(s): num_workers=2 schedulers=[batch, system, service, _core]
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.285+0200 [INFO]  nomad: serf: Attempting re-join to previously known node: mgmt-nomad-F5i.europe: 172.18.131.135:46>
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.285+0200 [INFO]  nomad: adding server: server="mgmt-nomad-8lQ.europe (Addr: 172.18.131.13:4647) (DC: aws15-mgmt)"
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [INFO]  nomad: serf: EventMemberJoin: mgmt-nomad-F5i.europe 172.18.131.135
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [INFO]  nomad: serf: EventMemberJoin: mgmt-nomad-pag.europe 172.18.131.77
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [WARN]  nomad: memberlist: Refuting a dead message (from: mgmt-nomad-8lQ.europe)
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [INFO]  nomad: serf: Re-joined to previously known node: mgmt-nomad-F5i.europe: 172.18.131.135:4648
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [INFO]  nomad: adding server: server="mgmt-nomad-F5i.europe (Addr: 172.18.131.135:4647) (DC: aws15-mgmt)"
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.287+0200 [INFO]  nomad: adding server: server="mgmt-nomad-pag.europe (Addr: 172.18.131.77:4647) (DC: aws15-mgmt)"
Sep 23 10:30:44 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:44.298+0200 [INFO]  nomad: successfully contacted Nomad servers: num_servers=2
Sep 23 10:30:45 mgmt-nomad-8lQ nomad[1521]:     2020-09-23T10:30:45.866+0200 [WARN]  nomad.raft: failed to get previous log: previous-index=5739 last-index=5731 error="log not found"
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: *   Trying 172.18.131.13:4646...
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: * TCP_NODELAY set
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]:                                  Dload  Upload   Total   Spent    Left  Speed
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: [138B blob data]
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: > GET /v1/agent/health?type=server HTTP/1.1
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: > Host: 172.18.131.13:4646
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: > User-Agent: curl/7.68.0
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: > Accept: */*
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: >
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: * Mark bundle as not supporting multiuse
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: < HTTP/1.1 200 OK
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: < Content-Type: application/json
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: < Vary: Accept-Encoding
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: < Date: Wed, 23 Sep 2020 08:30:59 GMT
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: < Content-Length: 37
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: <
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: { [37 bytes data]
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: [79B blob data]
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: * Connection #0 to host 172.18.131.13 left intact
Sep 23 10:30:59 mgmt-nomad-8lQ bash[1522]: {"server":{"message":"ok","ok":true}}
Sep 23 10:30:59 mgmt-nomad-8lQ systemd[1]: Started "HashiCorp Nomad - A workload orchestration solution".
```

**Comment by tgross** [comment]
Hi @bfqrst! I'm a little confused as to what you're showing... you're reporting an issue with Consul health checks of Nomad, but then showing us a bash script running `curl` in the same unit file as Nomad itself.

(Mind you, if that really is the problem, that's an issue with your systemd config and `curl`... I _think_ you can solve that by passing `--noproxy` to `curl` but that's really out of scope for an issue here.)

A Consul HTTP health check is emitted from Consul, so any proxy configuration you need to do would be on the Consul systemd unit file, not on the Nomad one.

A few questions that might help clarify what you're seeing:
* Does Consul show that Nomad has Nomad successfully registered itself with Consul?
* Does Consul show the Nomad agent service at the correct IP?
* Does Consul show that the Nomad health check passes?
* If not, what does Consul's health check show? (The error message it gets.)

**Comment by bfqrst** [comment]
Hey @tgross,

thanks for the getting back to me! So let me try to clarify:

1. I have a Consul server cluster running (as far as I can tell, being okay)...
2. Every other node in the fleet receives the Consul binary with the client configuration...
3. In this scenario I'm opting for the AWS cloud auto disovery
4. Client nodes are popping up in the Consul UI, registering their Serf Health status (also being green)
5. At this point I'm inclined to say that the Consul server <-> client status is healthy. I might be wrong though...
6. Now I'm deploying 3 Nomad server
7. Here I'm not going for the cloud autodiscovery, since every Nomad server is a Consul client, helping Nomad bootstrapping the configured min size. Nomad server are successfully bootstrapping the cluster.
8. What I now see in the Consul UI is this 
<img width="337" alt="grafik" src="https://user-images.githubusercontent.com/7373518/94018480-f386f180-fdb0-11ea-8317-618cdc7936c6.png">
9. Serf and RPC checks are passing, the HTTP check returns the default inhouse 403 McAfee page...

`HTTP GET http://172.18.131.13:4646/v1/agent/health?type=server: 403 AuthorizedOnly Output: <!DOCTYPE html PUBLIC `
10. When I change the bound http address to 127.0.0.1 this very http check passes, like so:
<img width="337" alt="grafik" src="https://user-images.githubusercontent.com/7373518/94019432-149c1200-fdb2-11ea-9570-ac048b82e5a2.png">
<img width="1338" alt="grafik" src="https://user-images.githubusercontent.com/7373518/94019501-2aa9d280-fdb2-11ea-92c6-9cb97fad0c2a.png">

Those env and curl lines where strictly for debugging purposes and are otherwise not part on the systemd config. I somehow thought those might be helpful. Does this help you?

**Comment by tgross** [comment]
Thanks, that's very helpful context!

Ok, so:

> 8. What I now see in the Consul UI is this

That IP address is the [`advertise` address](https://www.nomadproject.io/docs/configuration#advertise), which defaults to the [`bind_addr`](https://www.nomadproject.io/docs/configuration#bind_addr). If you're using Consul autodiscovery, you'll definitely want that address to be the private IP on the LAN, so that Nomad servers can send packets to each other. So that looks right to me.

Given that Nomad is registering ok with Consul, that suggests to me that you've got the no-proxy configured correctly on the Nomad end. But...

> 9. Serf and RPC checks are passing, the HTTP check returns the default inhouse 403 McAfee page...
HTTP GET http://172.18.131.13:4646/v1/agent/health?type=server: 403 AuthorizedOnly Output: <!DOCTYPE html PUBLIC
> 10. When I change the bound http address to 127.0.0.1 this very http check passes, like so:

The HTTP check is being emitted from Consul, not from Nomad. Which means any no-proxy configuration needs to be set on the Consul agent as well. (I'm guessing that the proxy doesn't break non-HTTP traffic and that's why serf and rpc checks are fine?)

**Comment by bfqrst** [comment]
> The HTTP check is being emitted from Consul, not from Nomad. Which means any no-proxy configuration needs to be set on the Consul agent as well. (I'm guessing that the proxy doesn't break non-HTTP traffic and that's why serf and rpc checks are fine?)

And that solved it @tgross, thanks so much. Now that I think about it, it kinda makes sense too! 

Would that also make sense to include some sort of hint in the docs for situations where corporate proxies are involved?
In any case, thanks for the help. Please feel free to close the issue.

Cheers
Ralph

**Comment by tgross** [comment]
Not sure if that documentation note should live in the Consul or Nomad docs, but yeah we'll figure out something for that. Glad to hear you got things sorted!
