### ISSUE TITLE
qemu driver config documentation incorrect

### ISSUE THREAD

**Issue by colindunn** [hashicorp/nomad#8960]
### Nomad version
```
# nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)
```

### Operating system and Environment details
Ubuntu 20.04

### Issue
According to https://www.nomadproject.io/docs/drivers/qemu#image_paths the config for the qemu driver should be in the form of the following:
```
plugin "qemu" {
  config {
    image_paths = ["/data/images"]
  }
}
```

But if I set that value in the config, nomad fails to load with the following error:
```
Sep 24 09:28:27 node12 nomad[1099]: #011* plugin "qemu" (driver): failed to parse config:  Invalid label: No argument or block type is named "image_paths".
```

If I set the config to the following, nomad is able to start:
```
plugin "qemu" {
  image_paths = ["/data/images"]
}
```

### Reproduction steps
As noted above in the issue description

### Job file (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

### Nomad Server logs (if appropriate)
```
Sep 24 09:28:27 node12 nomad[1099]: #011* plugin "qemu" (driver): failed to parse config:  Invalid label: No argument or block type is named "image_paths".
```

**Comment by tgross** [comment]
Hi @colindunn!

I just checked the code history and I don't think the `image_paths` configuration is valid at all in Nomad 0.11.3. That was introduced in 0.12.0 by https://github.com/hashicorp/nomad/pull/8261. I suspect that in the case you have where it's "working" it's slipping by the configuration parser but the value isn't being handled at all. If you were to try to run a QEMU task with an image outside the `image_paths` list it will probably work, showing that the field isn't being used.

(That also means we have a bug in our configuration parsing that `image_paths` is allowed in a place it shouldn't be, but it's not one we're likely to fix in a backported version of Nomad.)

**Comment by tgross** [comment]
I've opened https://github.com/hashicorp/nomad/issues/9001 about the overly-generous config parser.
