### ISSUE TITLE
Metric label `node_scheduling_availability` does not update with changes.

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#8965]
### Nomad version

Nomad v0.12.5

### Issue

The `node_scheduling_eligibility` label on the Nomad client metrics does not update as the eligibility status is changed.

### Reproduction steps

Create a telemetry.nomad file with the basic configuration

```bash
telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
}
```

Run a dev agent with the telemetry configuration

```bash
nomad agent -dev -config=telemetry.nomad
```

Watch a metric with the label

```bash
watch "curl -s http://localhost:4646/v1/metrics | jq '.Gauges[] | select(.Name==\"nomad.client.uptime\")'"
```

Note that it appears enabled.  Set the eligibility to disabled

```bash
nomad node eligibility -self -disable
```

Watch for a stat update, observe that enabled doesn't change.

**Comment by tgross** [comment]
cc @pete-woods as this may be silently impacting dashboards in your org.

**Comment by parberge** [comment]
We have observed the same thing running with version `v1.0.4`. Happy to provide more information if required.

**Comment by gmichalec-pandora** [comment]
Just an update that this is still present on the latest `v1.1.0-beta1`: 
```
gmichalec@gmichalec:~$ curl -s http://dc6-docker5:4646/v1/nodes | jq -r '.[] | select(.Name=="dc6-docker5") | .SchedulingEligibility'
ineligible
gmichalec@gmichalec:~$ curl -s http://dc6-docker5:4646/v1/metrics | jq -r '.Gauges[] | select(.Name == "nomad.client.uptime") | select(.Labels.host == "dc6-docker5") | .Labels.node_scheduling_eligibility'
eligible
```

**Comment by usovamaria** [comment]
The problem is still reproducing also using `nomad node status -self`. The node drain status is not updated after drain:
```
root@<host>:<dir># nomad node status -self -short -json 2>/dev/null | jq .Drain
false
root@<host>: <dir># nomad node drain -self -enable -deadline 120s -detach
root@<host>:<dir># nomad node status -self -short -json 2>/dev/null | jq .Drain
false
```

**Comment by resmo** [comment]
We see this in `v1.2.6`
