### ISSUE TITLE
Multiple Networks For Docker using network_mode

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/nomad#899]
As per the document we can specify the overlay network for docker driver using the keyword `network_mode`. I am not quite clear if we can define multiple overlay networks here. Any hints?
(for example the app needs connect to multiple networks, while the db needs to connect only to the backend network)

**Comment by diptanu** [comment]
@vrenjith So what the docs meant is that you could choose the docker networking mode to use `host`, or `bridge` or any other overlay network manager or plugin by specifying that in the `network_mode`

I think what you are asking though is a little different - You want Nomad to allocate ports for you on different network interfaces on a host? If the answer to that is yes, we will address that in Nomad 0.4 hopefully.

**Comment by vrenjith** [comment]
Not exactly. Actually, I am trying to compare the docker-compose
functionality where we can define a container to connect to multiple
overlay networks.

On Fri, Mar 11, 2016 at 7:53 AM, Diptanu Choudhury <notifications@github.com
> wrote:

> @vrenjith <https://github.com/vrenjith> So what the docs meant is that
> you could choose the docker networking mode to use host, or bridge or any
> other overlay network manager or plugin by specifying that in the
> network_mode
>
> I think what you are asking though is a little different - You want Nomad
> to allocate ports for you on different network interfaces on a host? If the
> answer to that is yes, we will address that in Nomad 0.4 hopefully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/nomad/issues/899#issuecomment-195148142>.
>



-- 
Regards,
Renjith

**Comment by vingrad** [comment]
ERROR: 'network_mode' and 'networks' cannot be combined
Do you have a solution now?

**Comment by dadgar** [comment]
Hey,

Nomad currently does not supported this. Closing as there are others regarding multiple networks / docker.

**Comment by FlorinAsavoaie** [comment]
Would be useful to specify what are those "others" before closing. It is a normal practice to require multiple networks in a container when running on micro-segmentated networks.

**Comment by FlorinAsavoaie** [comment]
So... Could anyone share those "others"? 3 months later I'm still unable to find any...

**Comment by FlorinAsavoaie** [comment]
@dadgar

**Comment by hsmade** [comment]
There aren't it seems...

**Comment by FlorinAsavoaie** [comment]
@diptanu

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I really hope this will soon be part of Nomad. It's currently the main deal breaker for me as I can not seriously run container without proper network isolation...

**Comment by Mayeu** [comment]
I hope this will soon be part of Nomad. It is the main deal breaker on our side to adopt Nomad. I can realistically run containers in production without good network isolation.

**Comment by PacoDu** [comment]
Same here, I can't find a proper network isolation setup to run consul + nomad with docker driver and benefit from consul connect proxies. The only solution is to use `network_mode = host` but this removes docker network isolation and then any docker running from nomad can potentially access a service proxy on the loopback interface without any ACL verification from consul. 

I'm wondering if using `network_mode = host`, based on the fact that any program running on the host is trusted and uses consul proxy and intentions, can be considered a secure and "good" practice based on the trusted multi tenancy model ? (https://www.consul.io/docs/connect/security.html#prevent-non-connect-traffic-to-services)

**Comment by FlorinAsavoaie** [comment]
FYI, you can run multiple containers on the same network namespace, using network="container:containername", aka. the sidecar pattern. They would look just like the containers of a K8s POD that share a network namespace.

**Comment by akamac** [comment]
+1 for ability to attach containers to multiple networks

**Comment by FlorinAsavoaie** [comment]
Activity :)

**Comment by alieksanov** [comment]
+1

**Comment by alieksanov** [comment]
Activity!

**Comment by sully90h** [comment]
+1

**Comment by stephenliberty** [comment]
Given that this has been open for.. going on four years, I don't see much hope of it happening. But I'm voting for it anyway. Specific use case is as follows. We've a handful of "public" network components that are organized on a frontend type network. Then another handful that are 'backend' only. Some 'frontend' containers need to be able to talk to backend containers, so they're connected to both networks. Without the ability to connect to multiple networks or some post-task script to manually connect them, this is a no-go via Nomad

**Comment by tgross** [comment]
We've implemented this feature as of [0.12.0](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#0120-july-9-2020) with the multi-interface networking. You can configure multiple [`host_network`](https://www.nomadproject.io/docs/configuration/client#host_network-stanza) blocks in the client configuration and assign a port to be assigned to a particular [`host_network`](https://www.nomadproject.io/docs/job-specification/network#host-networks). I'm going to close this issue; if there are further expansions on this feature that we want we can open a new issue.
