### ISSUE TITLE
Add Resources, ReservedResources, and Reserved to the /v1/nodes endpoint conditionally

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hashicorp/nomad#8995]
To support the topology visualization, we'll need a nodes endpoint that returns all nodes and their resources/reservation information.

Currently, the topo viz reloads every node individually to get this information but that's not sustainable.

I imagine we'll want to put this behind a query param. Maybe `?resources=true` to match `?all` for `/job/:id/allocations` and `?diffs` for `/job/:id/versions`.

https://github.com/hashicorp/nomad/blob/235f938e87afbdc73037c1868a17668c06a8cf94/nomad/structs/structs.go#L1753-L1767

**Comment by tgross** [comment]
@DingoEatingFuzz @schmichael doing some pre-release issue cleanup: should this have been closed when https://github.com/hashicorp/nomad/issues/9017 was closed?

**Comment by schmichael** [comment]
Ack, yup. Thanks Tim! Closing.
