### ISSUE TITLE
API Support for Topology Visualization

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hashicorp/nomad#9017]
It might be better to have this place to talk generally about the requirements of the topology visualization.

The API goals are to make as few requests as possible and download as many unneeded bits as possible. I guess these are always the goals of an API, but I digress.

Currently the topology visualization does this:

1. Fetch `/v1/nodes` to get all nodes
2. For each node, fetch `/v1/node/:id` to get the resources data (see #8995)
3. For each node, fetch `/v1/node/:id/allocations` to get allocations including resources data

This results in 2n + 1 requests.

This is what I would like to do:

1. Fetch `/v1/nodes?resources=true`
2. Fetch `/v1/allocations?resources=true`

This would be just the two requests.

If I'm dreaming big, there is still a lot of information here I'm not sure I need, such as task events and node events, but this is a good starting point.

**Comment by schmichael** [comment]
These fields?

- [`Node.NodeResources`](https://github.com/hashicorp/nomad/blob/v0.12.5/nomad/structs/structs.go#L1738-L1739)
- [`NodeReservedResources`](https://github.com/hashicorp/nomad/blob/v0.12.5/nomad/structs/structs.go#L1741-L1743)

(Node.Resources and Node.Reserved are deprecated as of 0.9 although that could be made more clear.)

- [`Allocation.AllocatedResources`](https://github.com/hashicorp/nomad/blob/v0.12.5/nomad/structs/structs.go#L8557-L8558)

(`Allocation.{Resources,SharedResources,TaskResources}` are all deprecated although that could be made more clear.)

Sample `Allocation.AllocatedResources` JSON:
```json
{
  "Tasks": {
    "redis": {
      "Cpu": {
        "CpuShares": 100
      },
      "Memory": {
        "MemoryMB": 300
      },
      "Networks": null,
      "Devices": null
    }
  },
  "TaskLifecycles": {
    "redis": null
  },
  "Shared": {
    "Networks": null,
    "DiskMB": 300,
    "Ports": null
  }
}
```

**Comment by DingoEatingFuzz** [comment]
Good to know!

The UI currently uses `Node.Resources`, `Node.Reserved`, and `Allocation.AllocationResources`. Looks like we should update to use `Node.NodeResources` and `Node.ReservedResources`.

It's totally understandable if you don't want to drag the deprecated fields into this new endpoint variant so I can update what we're using as part of this.

**Comment by schmichael** [comment]
Does #9055 seem to meet your needs?

I fear `/v1/allocations?resources=true` may be quite expensive for users with large clusters. Some future improvements that might help:

- `?terminal=false` - only return `DesiredStatus=running` allocations. Same logic could be applied to Nodes.
- `?task_states=false` - strip task states from the response as they're often the largest part of the response.

In addition or alternatively you may want to continue doing `n + 1` requests: `/v1/nodes?resources=true` + 1 `node/allocs` request per node.

You could limit the `n` requests to just the first "page" of node results (and perhaps prefetch another page or two). Obviously this limits visualizations and sorting to Node data which might be a nonstarter.

**Comment by DingoEatingFuzz** [comment]
This meets my needs! I just updated my data fetching and verified it all.

I agree about the massiveness of the allocations payload, and both of those additional toggles would help--especially task states which can be quite large and (at least for the topo viz) I'm not even looking at.

This new `n + 1` approach is interesting. It definitely makes sense to progressively download things in some manner, but I still get squeamish thinking about doing this for any cluster where `n` is > 100. That's a lot of requests in rapid succession.

The other other approach, if we don't want to pollute the public API with combinatorial bells and whistles, is to make this an "internal" "ui" endpoint. There's precedence for this in [Vault](https://www.vaultproject.io/api-docs/system/internal-ui-mounts) and [Consul](https://github.com/hashicorp/consul/blob/master/agent/http_register.go#L97-L103) already.

I don't like the UI getting VIP treatment, but it might be nice as a stop-gap while we figure out some API configurations we actually want to support long term.

**Comment by schmichael** [comment]
Altering projection (the fields like task_states) is pretty easy on top of what I've built, so I'll add that.

Altering selection (which objects like terminal=false) is a new thing altogether, so I'm going to skip it for now. Feel free to open up a new issue if you think it's worth going down that path.
