### ISSUE TITLE
Default cni_config_dir doesn't appear to be honored.

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#9028]
### Nomad version
Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)

### Operating system and Environment details
centos 7

### Issue
Documentation says that /opt/cni/config is default configuration path; however if it is not explicitly set, the fingerprinter returns `client.fingerprint_mgr: CNI config dir is not set or does not exist, skipping: cni_config_dir=`

I do see that there is a default being set in https://github.com/hashicorp/nomad/blob/311886b664752cf617d6012c017cd68749335374/client/config/config.go#L333 

So I'm not sure why we aren't seeing the expected default.

**Comment by grumpy-programmer** [comment]
I confirm that. Today I have to define `cni_path` & `cni_config_dir` in client config:
```
client {
  cni_path = "/opt/cni/bin"
  cni_config_dir = "/opt/cni/config"
}
```
Default values are overriten in agent `convertClientConfig` function:
https://github.com/hashicorp/nomad/blob/311886b664752cf617d6012c017cd68749335374/command/agent/agent.go#L642
