### ISSUE TITLE
[Question] How to start a stopped job via API

### ISSUE THREAD

**Issue by carlosrbcunha** [hashicorp/nomad#9056]
### Nomad version
Nomad v0.12.4 (8efaee4ba5e9727ab323aaba2ac91c2d7b572d84)
### Operating system and Environment details
Ubuntu 18.04.5 LTS
### Issue
After stop a job how can I restart it via API the same way we can start the job from the UI

**Comment by tgross** [comment]
Hi @carlosrbcunha! If you watch the web UI in your browser's developer tools, you'll see that when you hit Start on the job, it does:

* [Read Job](https://www.nomadproject.io/api-docs/jobs#read-job): `HTTP GET /v1/job/example` to fetch the job definition from the server
* [Create Job](https://www.nomadproject.io/api-docs/jobs#create-job): `HTTP POST /v1/job/example` to run the job again

**Comment by carlosrbcunha** [comment]
Thanks for the help. 
That approach solved the problem. I had just to alter the job payload to get it started and in the format needed.

Thanks Tim.
