### ISSUE TITLE
Docker driver fails to verify certificates from private registry

### ISSUE THREAD

**Issue by readmodifywrite** [hashicorp/nomad#9062]
Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)

Linux Mint 20

The docker driver fails to verify the certificate chain when pulling an image from a private registry.  The registry's root certificate is correctly installed in the OS root certificate store, so it looks like Nomad is ignoring this and using some other (apparently undocumented) CA store.

Providing the registry certificates and key to the tls stanza in the docker plugin config also fails to verify.

**Comment by tgross** [comment]
Hi @readmodifywrite! Sorry to hear you're having trouble. The docker driver is making API calls to `dockerd` on the host to run containers which should be delegating the pulling of the image as well. Can you confirm that `docker` itself can pull images from this registry without Nomad?

**Comment by readmodifywrite** [comment]
Ah - that was it.  Docker daemon needed a restart to pick up the new certificates.  I mistakenly thought the Nomad driver had it's own client instead of delegating to the host Docker.

I do wish the SSL option was still there ;-)

Thanks!
