### ISSUE TITLE
Failed to run `curl` in an `exec` driver

### ISSUE THREAD

**Issue by slawdan** [hashicorp/nomad#908]
### Nomad version
`Nomad v0.3.1-dev`

### Operating system and Environment details

`Linux  2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

`CentOS release 6.5 (Final)`

### Issue

Run a `curl` in a shell script using `exec` driver will failed, cause `/usr/lib64` not included after `chroot`.

As on CentOS, a lot of `so` files are placed in `/usr/lib64` but it didn't be included into the `chroot` directories. -_- This problem affect all the system commands which use any `so` file in `/usr/lib64`. As  Ubuntu has no `/usr/lib64` directory, so could you make a compatible change for CentOS?

### Reproduction steps

1. Write a shell script named `1.sh` with the follow content:
    ```bash
    curl "http://google.com/" 1>>/stdout 2>>/stderr
    ```

2. Place `1.sh` to a web server, eg `http://remoteserver/1.sh`
3. Create a nomad job using `exec` driver:

    ```
                task "mytask" {
                        driver = "exec"

                        config {
                                artifact_source = "http://remoteserver/1.sh"
                                command = "/bin/sh"
                                args = ["./1.sh"]
                        }
                }
    ```
4. Check the nomad client alloc directory, got two files: an empty `stdout`, and a non-empty`stderr`, which the content is:

    ```
    curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
    ```
    while `libcurl.so.4` exists at `/usr/lib64/libcurl.so.4` of system.

**Comment by diptanu** [comment]
@slawdan Thanks for reporting! We will look into this shortly.

**Comment by dadgar** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/1009
