### ISSUE TITLE
Slow Allocation Start With Lots of Static Ports

### ISSUE THREAD

**Issue by herter4171** [hashicorp/nomad#9110]
### Nomad version
Nomad v0.12.3 (2db8abd9620dd41cb7bfe399551ba0f7824b3f61)

### Operating system and Environment details
Amazon Linux 2 cluster attempting to run STAR-CCM+ in CentOS containers across multiple nodes.

### Issue
I wish there was a way to specify port ranges in Nomad.  Anyway, I need to have lots of ports open for MPI, like thousands.  For some reason, adding a thousand ports for MPI makes the allocations sit for like 5 minutes even when the image is already downloaded.  I can't be the first person to try something like this, so am I doing something wrong?  What's the best way to handle jobs with lots of ports like this?

### Reproduction steps
Run a job with a thousand or so static ports allocated.

### Job file (if appropriate)
I've just included my network stanza with the full port list abridged.
```
        network {
          mode = "host"

          port "ssh" {
            static = 2122
          }
          port "server" {
            static = 47827
          }
          port "mpi_2123" {
            static = 2123
          }
          port "mpi_2124" {
            static = 2124
          }
[...]
          port "mpi_3123" {
            static = 3123
          }
          
        }

```
### Nomad Client logs (if appropriate)
Nothing interesting from the logs.  The allocations hung at "creating task directory" for about 5 minutes, then eventually started running.

**Comment by tgross** [comment]
Hi @herter4171! Sorry you're running into this... the specific behavior for network isolation is mostly controlled by the task driver. Can you provide the rest of the jobspec? (redacted as neccessary)

Drivers like `docker` are going to be setting up iptables rules for static ports (and I'm not sure how efficiently `dockerd` batches those changes up). Whereas the `exec` driver doesn't, and if you're using the `host` mode with `exec` you could even leave the `static` port assignments off entirely as long as you didn't need Consul service discovery.

**Comment by herter4171** [comment]
Hey @tgross, thanks for taking the time here.

The remaining portion of my job file is below, and I'm currently using the `docker` driver.  Compute nodes are in an auto-scaling group and currently agnostic to the user-space, since that's not in the AMI.  All nodes have an EFS partition mounted to `/shared`, and users run their jobs somewhere in `/shared/$USER`.

Leaving off the ports sounds great, and I think I see a path forward with `exec`.  Some users will have export controlled content in their folders, so how can I use `exec` and run a tight ship with existing permissions and UIDs/GIDs?  Also, just so I'm clear, there's nothing I can do with the `docker` driver and networking to have things wide open between allocations in the same job, right?

```
job "star-test-2" {

  # Required!  Default is dc1
  datacenters = ["dc1"]

  type = "batch"

  group "star-runs" {
    count = 2

    task "frontend" {
    
      driver = "docker"

      config {
        image = "harbor.kairospower.com/star/star-15:vnc"
        tty = true

        work_dir = "/home/dev/run"
        command = "./run.sh"

        volumes = [
            "/shared/ec2-user/star_test:/home/dev/run",
            "/shared/ec2-user/star_ssh:/home/dev/.ssh"
        ]

        auth {
            username="devops"
            password="EkE-NsD-D5x-svu"
            server_address="harbor.kairospower.com"
        }


      }

      env {
          # Set this equal to count above!
          "NODE_CT" = "2"
      }

      resources {
        cpu    = 140000 # MHz
        memory = 90000 # MB
```

**Comment by tgross** [comment]
> Also, just so I'm clear, there's nothing I can do with the docker driver and networking to have things wide open between allocations in the same job, right?

Actually, I was wrong there... I'd checked with the `network` stanza set to `mode = host`, but if you're using Docker you can use the `network_mode = "host"` config. That should completely bypass setting up all the various ports you need.

Here's an example of two allocations on the same host (using the `$NOMAD_ALLOC_INDEX` as part of the port number to avoid port collisions):

```hcl
job "example" {
  datacenters = ["dc1"]

  group "group" {

    count = 2

    task "task" {
      driver = "docker"

      config {
        image   = "python:3.9.0-alpine"
        command = "python"
        args    = ["-m", "http.server", "800${NOMAD_ALLOC_INDEX}"]
        network_mode = "host"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

If I run that, I can `nomad alloc exec` to get a shell into one of the allocations and curl the other one no problem:

```
$ nomad job run ./example.nomad
==> Monitoring evaluation "c0e4aae5"
    Evaluation triggered by job "example"
    Allocation "28622af4" created: node "cb5e56d0", group "group"
    Allocation "55f0ec57" created: node "cb5e56d0", group "group"
    Evaluation within deployment: "4467c6ab"
    Allocation "55f0ec57" status changed: "pending" -> "running" (Tasks are running)
    Allocation "28622af4" status changed: "pending" -> "running" (Tasks are running)
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "c0e4aae5" finished with status "complete"
$ nomad alloc exec 55f0ec5 /bin/sh

/ # echo $NOMAD_ALLOC_INDEX
1

/ # apk add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/3) Installing nghttp2-libs (1.41.0-r0)
(2/3) Installing libcurl (7.69.1-r1)
(3/3) Installing curl (7.69.1-r1)
Executing busybox-1.31.1-r16.trigger
OK: 12 MiB in 38 packages

/ # curl -I localhost:8000
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.9.0
Date: Fri, 16 Oct 2020 18:06:01 GMT
Content-type: text/html; charset=utf-8
Content-Length: 1030
```

**Comment by herter4171** [comment]
Wow, `network_mode = "host"` was exactly what I was looking for!  This makes my week.  I saw it in the docs, but it wasn't clear to me that `host` meant you didn't have to specify each and every port.  Feel free to close this if you'd like.

**Comment by tgross** [comment]
Glad to hear that'll work for you! I'm going to close this, but if you find that you're having more trouble with this setup please feel free to reopen.
