### ISSUE TITLE
Handling special character(â/U01/MAS/conf/â)

### ISSUE THREAD

**Issue by Zycusgautam** [hashicorp/nomad#9111]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.10.5

### Operating system and Environment details
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

### Issue
NOMAD job is unable to start the server ; we are able to start the server using ./start.sh command. 

### Nomad Client logs (if appropriate)
NOMAD error Log shows #
mkdir: cannot create directory  â/U01/MAS/conf/â: File exists
base64: invalid input
I don't know how to handle these special characters in my start.sh file.
snippet of start.sh file is below :
function create_property_file()
{
        mkdir /U01/MAS/conf/
     
}

Please guide me how i can handle the special character 
Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Hi @Zycusgautam. Thanks for opening an issue and sorry to hear you're having trouble. Can you provide the configuration file you're using for the server? If the configuration file includes non-ASCII characters, is it `utf-8` encoded?

I don't see any special characters in your `start.sh` script. Is this `start.sh` script something you've created or have you taken it from somewhere else?

**Comment by Zycusgautam** [comment]
Hi Tim,

     thanks a lot for your quick response.
     configuration file / .hcl file for the product is as below

       job "MAS" {
  region = "global"
  datacenters = ["QC"]
  type = "service"
  group "MAS" {

    update {
        max_parallel     = 1
        min_healthy_time = "3m"
        healthy_deadline = "9m"
        progress_deadline = "20m"
      }

      constraint {
        attribute = "${meta.release_version}"
        value = "RELEASE_VERSION"
      }
      constraint {
        attribute = "${meta.node_type}"
        value = "service_node"
      }

      constraint {
        attribute = "${meta.product}"
        value = "MAS"
      }

      count = 2
      task "MAS_tomcat" {


      driver = "raw_exec"
      config {
        command = "su"
        args = ["-c", "/U01/MAS/bin/start.sh", "-", "webtech"]
      }
      service {
        name = "MAS"
        port = "integration"
        tags = []
        check {
          type = "http"
          path = "/getMASStatus"
          interval = "10s"
          timeout = "12s"
        }
      }
      resources {
        network {
          port "integration" {
            static = 28081
          }
        }
      }
    }
  }
}

 Regarding to start.sh, product team created and they are using the same file for a long time.
regards
gautam

________________________________

**Comment by Zycusgautam** [comment]
our start.j2 file is as below
=========
#!/bin/bash
JAVA_HOME={{ jdk_path }} 
SCRIPT_PATH=/U01/{{ product }}/bin
MAS_LOGS_DIR={{ log_location }}/mas
MAS_CONF_DIR=/U01/{{ product }}/conf
function create_property_file()
{
  IP="{{ consul_host }}"
    PORT="{{ consul_port }}"
    ENV="{{ setup_env }}"
    PRO_NAME="{{ product }}"
    DATA=`curl "http://$IP:$PORT/v1/kv/$ENV/$PRO_NAME/$1/?recurse"|python -c '

import json,sys
obj=json.load(sys.stdin)
for cvbd in obj:
 wery = cvbd["Key"].split("/")
 if not (cvbd["Value"] is None) : print wery[len(wery)-1]+","+cvbd["Value"]
 else : print wery[len(wery)-1]+","+" "  '`
        mkdir /U01/MAS/conf/
		
		
        while IFS="," read f1 f2
        do
         KEY="$f1"
         if [ "$f2" != "null" ]
         then
                 VALUE=`echo "$f2"| base64 --decode`
                 echo "$KEY=$VALUE" >> /U01/{{ product }}/conf/$1.properties
         else
                 echo "$KEY=" >> /U01/{{ product }}/conf/$1.properties
         fi
        done <<< "$DATA"
}

function process_pid(){
        PID=`ps -ef | grep '{{ jar_location }}/{{ product }}.jar' | grep -v grep | awk '{ print $2 }'`

}

function create_bootstrap_file()
{
    echo "spring.cloud.consul.config.failFast=false" >> /U01/{{ product }}/conf/bootstrap.properties
  	echo "spring.cloud.consul.config.prefix={{ consul_prefix }}" >> /U01/{{ product }}/conf/bootstrap.properties
  	echo "spring.cloud.consul.host={{ consul_host }}" >> /U01/{{ product }}/conf/bootstrap.properties
  	echo "spring.cloud.consul.port={{ consul_port }}" >> /U01/{{ product }}/conf/bootstrap.properties
	echo "spring.cloud.consul.config.watch.enabled=false" >> /U01/{{ product }}/conf/bootstrap.properties

}
export MAS_LOGS_DIR="{{ log_location }}/mas"
export MAS_CONF_DIR="/U01/MAS/conf"

rm -rf /U01/{{ product }}/conf/*
create_bootstrap_file
create_property_file "application"
create_property_file "mongo"
create_property_file "swagger"
create_property_file "tenant-settings"
create_property_file "tms"
create_property_file "iRequest_messages_en"
create_property_file "iAnalyze_messages_en"
create_property_file "iAnalyze_messages_hi"
create_property_file "messages_hi"
create_property_file "messages_en"

# Kill existing process if exists
process_pid
kill -9 $PID
#Start Server
$JAVA_HOME/bin/java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -Dfile.encoding={{ MAS_FILE_ENC }}-Xms{{ MAS_JAVA_HEAP }} -Xmx{{ MAS_JAVA_HEAP }} -Duser.timezone={{ MAS_TIMEZONE }} -jar {{ jar_location }}/{{ product }}.jar --spring.config.location=/U01/{{ product }}/conf/application.properties,/U01/{{ product }}/conf/mongo.properties,/U01/{{ product }}/conf/swagger.properties,/U01/{{ product }}/conf/tenant-settings.properties,/U01/{{ product }}/conf/tms.properties,/U01/{{ product }}/conf/bootstrap.properties &

echo 'process started'
echo 'Sleeping for 10s'
sleep 10s

#echo  `ps -ef | grep mas  | grep -v grep | awk '{print $2}'` > $SCRIPT_PATH/MAS.pid
#ps -ef | grep '/U01/MAS/apps/mas/MAS.jar' | grep -v grep | awk '{ print $2 }' > /U01/MAS/bin/test/MAS.pid
process_pid
echo $PID > $SCRIPT_PATH/MAS.pid
#echo $PID > /U01/{{ product }}/data/mas/pid

processCount=`ps -ef | grep {{ jar_location }}/{{ product }}.jar | grep -v grep | wc -l`
if [[ $processCount == '1' ]]; then
  echo "MAS Started Successfully" > $SCRIPT_PATH/{{ product }}.log
  echo "MAS Started Successfully"
fi

**Comment by tgross** [comment]
Hi @Zycusgautam I've edited your replies just to add syntax highlighting. I think I misunderstood the original post; so the problem is that the job won't start without this start script? But what was the original command and args you were passing to `raw_exec` without it?

**Comment by notnoop** [comment]
This failure line seems to indicate that the issue is that the directory already exists:
```
mkdir: cannot create directory â��/U01/MAS/conf/â��: File exists
```

Given that you are using raw_exec, it's possible that the directory is present due to an earlier run (that failed to clean) or happened in out-of-band scenario.  I'd suggest using `-p` (e.g. `mkdir -p /U01/MAS/conf/`) to avoid having mkdir fail if the directory is already present.

In your start.j2 also that the line `rm -rf /U01/{{ product }}/conf/*` is there and deletes the files inside conf but leaves the directory alone.  You may consider changing it to be `rm -rf /U01/MAS/conf` as it will be created with the mkdir line above.  Though it's unclear to me whether `{{ product }}` is always `MAS` in this context.

**Comment by tgross** [comment]
Also, I noticed you're running `su` for your script, presumably in order to bypass the user restriction for `raw_exec`. I'm fairly certain this won't work. You should be seeing an error in the allocation logs like: `su: must be run from a terminal`

```hcl
driver = "raw_exec"
config {
  command = "su"
  args = ["-c", "/U01/MAS/bin/start.sh", "-", "webtech"]
}
```

**Comment by tgross** [comment]
@Zycusgautam the bash script you have here is probably going to give you issues in properly starting/stopping your application. All the pid file management you're doing here isn't necessary when running foregrounded in Nomad; we'll handle that for you.

I would recommend taking all the templating your doing to write the properties files and move that into a [`template`](https://www.nomadproject.io/docs/job-specification/template) stanza. Then you can just invoke `java` directly from Nomad as the `command`.

**Comment by tgross** [comment]
Going to close this as resolved.
