### ISSUE TITLE
[question] Scaling down the number of instances of a task

### ISSUE THREAD

**Issue by izogain** [hashicorp/nomad#912]
Hi,
I was wondering how nomad is handling scaling down the number of running tasks. For my use case, i have statefull docker containers running and each one can handle a limited number of users. when the traffic goes down, some containers are idle. Is there a way to hint nomad on which task/container should be terminated first when scaling down the job ?
For example, if i have 5 containers running with 2 of them idle, changing the count to 3 would save resource.
Thx.

**Comment by dadgar** [comment]
Hey there is currently no way to tell Nomad which instances you would like to teardown.

**Comment by izogain** [comment]
Alright, thanks.
