### ISSUE TITLE
Extend the filesystem API to allow introspection into containers.

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#914]

**Comment by achanda** [comment]
Can you expand a bit on this? The equivalent of `docker inspect` is `cat-manifest` in `rkt`.

**Comment by dadgar** [comment]
So when you do `nomad fs ls <alloc_id> <task_name>` you get the filesystem. It would be cool if we did an `nsester` or `docker exec <id> ls <path>` and got the results. This way with a uniform Nomad API you could navigate task's filesystems and inspect their content

**Comment by ketzacoatl** [comment]
@mikenomitch Can you clarify, is this closed as "Won't Fix" or closed as "Completed"?
