### ISSUE TITLE
docs: -no-color option for nomad alloc logs is ambiguous

### ISSUE THREAD

**Issue by v-byte-cpu** [hashicorp/nomad#9182]
If filing a bug please include the following:

### Nomad version
Output from `nomad version`:

```
Nomad v0.12.6 (a8ea7c5f421297db434b45046fca7a9deef6df85)
```

### Operating system and Environment details

Linux binaries (server and client)

### Issue

`nomad alloc logs -no-color` prints TTY color sequences. The same behavior with `NOMAD_CLI_NO_COLOR` env variable. 

### Reproduction steps

Run `nomad alloc logs -no-color <alloc_ID>`

**Comment by tgross** [comment]
Hi @v-byte-cpu, I think the documentation there is a little confusing. The `-no-color` option applies to all Nomad commands and can suppress the color output from Nomad. (We don't use much color, mostly for `nomad plan` and errors from status commands).

But the `nomad alloc logs` output is the output from your application, so if your application is sending color output in its logs, you'll need to suppress that at the application itself.

**Comment by v-byte-cpu** [comment]
Hi @tgross, thank you for clarification, I will investigate it. Right now I simply want to redirect small part of application logs to file without color codes (just to send some logs to another person), and as you mentioned I must suppress color output at the application level now or to pipe nomad output through sed, awk etc. to filter these color sequences. So it would be nice if `nomad` cli could filter terminal color control sequences from application output (as possible option).

**Comment by v-byte-cpu** [comment]
@tgross Yes, my application sends colorized logs

**Comment by tgross** [comment]
Ok, I'm going to retitle this issue so that we circle back to make the documentation more clear. I'm not sure how feasible it is to have an option to do filtering of the log contents, but we can take a look and open an enhancement request for that if so.
