### ISSUE TITLE
file creation gets rejected - Nomad v0.12.6

### ISSUE THREAD

**Issue by anastazya** [hashicorp/nomad#9222]
I tried to create a simple HTML file to share between 2 tasks in the same group and i get this  : 

	Task hook failed	template: template destination path escapes alloc directory

This is my file setup : 

     template {
        data = <<EOH
        <html>
        <head>
        <meta http-equiv="refresh" content="2"/>
        </head>

        <b> Nomad Template example (Consul value) and Nginx + Haproxy </b>
        <br />
        <br />
        {{ if keyExists "features/demo" }}
        Consul Key Value: <b> {{ key "features/demo" }} </b>
        {{ else }}
        Good morning.
        {{ end }}
        <br />
        <br />
        <b>Node Environment Information: </b> <br />
        node_id:     {{ env "node.unique.id" }} <br/>
        datacenter:  {{ env "NOMAD_DC" }} <br/>
        <b>You landed on : </b> <br/>
        node_ip:     {{ env "NOMAD_IP_http" }} <br/>
        node_port:   {{ env "NOMAD_PORT_http" }} 

        </body>
        </html>
        EOH
        destination = "../alloc/data/index.html"
      }

I have no clue what i did wrong. 

☝️ 

Same - even after this thread and knowing what to look for I couldn't find this documented _anywhere_...

```
        destination = "../alloc/app.conf"
```
Using that in your template stanza causes `/alloc/app.conf` to exist inside the Docker container for all tasks within a group. This isn't really very intuitive and given that Nomad (mostly) isolates the host filesystem with Docker, I didn't even consider trying `../` because I assumed it'd be rejected on eval.

Voting to get this fixed to be consisted with the other task drivers or at least documented under the Docker driver

_Originally posted by @ccakes in https://github.com/hashicorp/nomad/issues/2948#issuecomment-664337570_

**Comment by tgross** [comment]
@anastazya that issue #2948 is quite old. I have some documentation improvements in review in https://github.com/hashicorp/nomad/pull/9195. But #2948 predates the security protections we put in place in 0.9.6 (and that we further fixed in the recent 0.12.7). Writing outside the allocation directory is not permitted by default. You'll need to set the client configuration [`disable_file_sandbox`](https://www.nomadproject.io/docs/configuration/client#disable_file_sandbox) to `true` in order to do this.

**Comment by anastazya** [comment]
> @anastazya that issue #2948 is quite old. I have some documentation improvements in review in #9195. But #2948 predates the security protections we put in place in 0.9.6 (and that we further fixed in the recent 0.12.7). Writing outside the task working directory is not permitted by default. You'll need to set the client configuration [`disable_file_sandbox`](https://www.nomadproject.io/docs/configuration/client#disable_file_sandbox) to `true` in order to do this.

**Comment by anastazya** [comment]
To maybe help other folk banging their heads about a similar issue as mine, this is how it should look in a client.hcl config ( it works ).

client {
  enabled = true
  network_interface = "ens18"
  template {
      "disable_file_sandbox" = true
      }  
  meta {
    "node_type" = "{{ nomad_node_type }}"
  }
}

I'm running nomad on ubuntu 20.04 LTS VM's.

**Comment by tgross** [comment]
Glad to hear you've got that working 👍
