### ISSUE TITLE
Template source doesn't accept absolute file path

### ISSUE THREAD

**Issue by aholyoake-bc** [hashicorp/nomad#9236]
### Nomad version
0.12.7
### Operating system and Environment details
Debian 10, amd64

### Issue
We have recently upgraded from 0.10 to 0.12.7 and have seen a change in behaviour regarding using a template source from the local file system outside of the allocation directory.

We see the error:
```template: template source path escapes alloc directory```

Following the documentation changes that were made following this bug:
https://github.com/hashicorp/nomad/issues/1896

i.e.adding this to the client config https://www.nomadproject.io/docs/job-specification/template#client-configuration doesn't make any difference

### Sample Job File
```
job "test-template" {
    datacenters = ["europe-west1"]
    type = "batch"

    group "test-template" {
        count = 1

        constraint {
            attribute = "${node.unique.name}"
            value     = "unique-host-name"
        }

        restart {
            attempts = 0
            delay    = 15000000000
            interval = 100000000000
            mode     = "fail"
        }

        task "test-template" {
            driver = "raw_exec"

            config {
                command = "/usr/bin/tail"

                args = [
                    "-f",
"/dev/null"
                ]
            }

            template {
                source = "/path/to/environment.template"
                destination = "environment.env"
                env = true
            }

            resources {
                cpu    = 100
                memory = 10
            }
        }
    }
}
```

**Comment by tgross** [comment]
Hi @aholyoake-bc! You're running into the security patch from [0.12.6](https://www.nomadproject.io/docs/upgrade/upgrade-specific#artifact-and-template-paths). If you want to set the `template.source` outside the task working directory, you'll need to specifically opt-in to disabling the file sandbox via [`disable_file_sandbox`](https://www.nomadproject.io/docs/configuration/client#template-parameters) in the Nomad client config.

**Comment by tgross** [comment]
Doc fix for that `template.allow_host_source` is https://github.com/hashicorp/nomad/pull/9237

**Comment by aholyoake-bc** [comment]
Super, thanks for the quick reply!
