### ISSUE TITLE
Server memory usage from v0.11.3 to v0.12.3 has increased signficantly

### ISSUE THREAD

**Issue by hvindin** [hashicorp/nomad#9261]
### Nomad version
Nomad v0.12.3 (2db8abd9620dd41cb7bfe399551ba0f7824b3f61)

### Operating system and Environment details
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"

### Issue
We have recently upgraded from nomad v0.11.3 to v0.12.3 and we have noticed some strange behaviour that is leading to scheduled jobs being unexpectedly being rescheduled and leader elections occuring for seemingly no reason, while investigating one thing which stood out as immediately being "definitely really weird"was the memory usage on the servers.

The amount of memory being consumed by the one nomad server at any given time has increased from around 200MB on v0.11.3 to around 2-5GB on v0.12.3.

And I do mean literally just one server, not a specific one, just at any given time one server of the cluster members, all of the other servers are still always at around the 200MB mark, and the specific server which is the one using a ton of memory has never been observed to be the cluster leader, it's always just "one random server", I'm not sure if this issue doesn't impact the cluster leader, or if we just haven't observed it, but my first guess would have been that the server burning through resources would probably be most likely the cluster leader. But it turns out - not so.

The clusters are configured almost identically. the job files are largely identical, some minor changes have been made to the contents of the jobs (ie. some of the orchestrated workloads have been updated since we moved to v0.12.3 so the job files reflect newer versions of things), the only change in the server configuration was to add:
```json
{
  "log_file": "/var/log/nomad/",
  "log_rotate_bytes": 2097152
}
```

I honestly don't know where to begin looking to try and dig out why so much memory is suddenly being consumed, but the configuration for the two clusters is below and I'm more than happy to provide any details that are relevant.

#### Nomad v0.11.3 configuration (Note: all servers in this cluster are using ~230MB of RAM)
![image](https://user-images.githubusercontent.com/2695865/98119822-3fc16780-1f01-11eb-8c84-af82a7b4007f.png)
```json
{
  "name": "fqdn.hostname.com.au",
  "region": "global",
  "datacenter": "dc2",
  "disable_update_check": true,
  "bind_addr": "10.102.0.1",
  "advertise": {
    "http": "10.102.0.1:4646",
    "rpc": "10.102.0.1:4647",
    "serf": "10.102.0.1:4648"
  },
  "ports": {
    "http": 4646,
    "rpc": 4647,
    "serf": 4648
  },
  "limits": {
    "http_max_conns_per_client": 1000,
    "https_handshake_timeout": "30s"
  },
  "data_dir": "/opt/nomad/data",
  "enable_syslog": false,
  "log_level": "INFO",
  "leave_on_interrupt": false,
  "leave_on_terminate": true,
  "consul": {
    "address": "10.102.0.1:8501",
    "ssl": true,
    "auto_advertise": true,
    "server_auto_join": true,
    "client_auto_join": true,
    "verify_ssl": false,
    "ca_file": "/etc/ssl/local/consul/ca-root.pem",
    "cert_file": "/etc/ssl/local/consul/server.dc2.prod.pem",
    "key_file": "/etc/ssl/local/consul/server.dc2.prod.key",
    "client_service_name": "nomad-client",
    "server_service_name": "nomad",
    "token":"<token>"
  },
  "tls": {
    "http": true,
    "rpc": true,
    "ca_file": "/etc/ssl/local/nomad/ca-root.pem",
    "cert_file": "/etc/ssl/local/nomad/server.global.nomad.pem",
    "key_file": "/etc/ssl/local/nomad/server.global.nomad.key",
    "verify_https_client": true,
    "verify_server_hostname": true
  },
  "acl": {
    "enabled": true,
    "token_ttl": "600s",
    "policy_ttl": "1200s"
  },
  "server": {
    "enabled": true,
    "default_scheduler_config": [{ "scheduler_algorithm": "spread" }],
    "bootstrap_expect": 3,
    "encrypt": "<token>",
    "rejoin_after_leave": false,
    "job_gc_threshold": "10m",
    "deployment_gc_threshold": "5m",
    "eval_gc_threshold": "10m",
    "node_gc_threshold": "10m",
    "heartbeat_grace": "30s",
    "min_heartbeat_ttl": "20s"
  },
  "http_api_response_headers": [
    {
      "X-Accel-Buffering": "no"
    }
  ],
}
```

#### Nomad v0.12.3 configuration (Note: at any given time ONE of the servers will be using 4-5GB of memory)
![image](https://user-images.githubusercontent.com/2695865/98120718-6cc24a00-1f02-11eb-83a2-ce39ca16562c.png)
```json
{
  "name": "fqdn.hostname.com.au",
  "region": "global",
  "datacenter": "dc1",
  "disable_update_check": true,
  "bind_addr": "10.41.0.1",
  "advertise": {
    "http": "10.41.0.1:4646",
    "rpc": "10.41.0.1:4647",
    "serf": "10.41.0.1:4648"
  },
  "ports": {
    "http": 4646,
    "rpc": 4647,
    "serf": 4648
  },
  "limits": {
    "http_max_conns_per_client": 1000,
    "https_handshake_timeout": "30s"
  },
  "data_dir": "/opt/nomad/data",
  "enable_syslog": false,
  "log_level": "INFO",
  "log_file": "/var/log/nomad/",
  "log_rotate_bytes": 2097152,
  "leave_on_interrupt": false,
  "leave_on_terminate": true,
  "consul": {
    "address": "10.41.0.1:8501",
    "ssl": true,
    "auto_advertise": true,
    "server_auto_join": true,
    "client_auto_join": true,
    "verify_ssl": false,
    "ca_file": "/etc/ssl/local/consul/ca-root.pem",
    "cert_file": "/etc/ssl/local/consul/server.dc1.prod.pem",
    "key_file": "/etc/ssl/local/consul/server.dc1.prod.key",
    "client_service_name": "nomad-client",
    "server_service_name": "nomad",
    "token":"<token>"
  },
  "tls": {
    "http": true,
    "rpc": true,
    "ca_file": "/etc/ssl/local/nomad/ca-root.pem",
    "cert_file": "/etc/ssl/local/nomad/server.global.nomad.pem",
    "key_file": "/etc/ssl/local/nomad/server.global.nomad.key",
    "verify_https_client": true,
    "verify_server_hostname": true
  },
  "acl": {
    "enabled": true,
    "token_ttl": "600s",
    "policy_ttl": "1200s"
  },
  "server": {
    "enabled": true,
    "default_scheduler_config": [{ "scheduler_algorithm": "spread" }],
    "bootstrap_expect": 3,
    "encrypt": "<token>",
    "rejoin_after_leave": false,
    "job_gc_threshold": "10m",
    "deployment_gc_threshold": "5m",
    "eval_gc_threshold": "10m",
    "node_gc_threshold": "10m",
    "heartbeat_grace": "30s",
    "min_heartbeat_ttl": "20s"
  },
  "http_api_response_headers": [
    {
      "X-Accel-Buffering": "no"
    }
  ],
}
```

Almost the exact same behaviour is observable in our test environments where looking at the memory usage across nomad servers shows 1 outlier server:
![image](https://user-images.githubusercontent.com/2695865/98121530-831cd580-1f03-11eb-8a5f-3a675344eb77.png)

The systemd service file which we are using to run the nomad server has not changed during the upgrade, it is as below:

```
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target consul.service
After=network-online.target consul.service

[Service]
KillMode=process
KillSignal=SIGINT
ExecStart=/opt/nomad/bin/nomad agent -config /opt/nomad/nomad.d/config.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=2
StartLimitInterval=0
LimitNOFILE=65536
TasksMax=infinity

[Install]
WantedBy=multi-user.target
``

**Comment by tgross** [comment]
Hi @hvindin! Sorry to hear you're having issues.

I definitely agree that the first assumption I'd make here was that the high memory usage was on the leader. The leader runs a whole bunch of expensive tasks (although we definitely shouldn't be _that_ much larger than the followers). And the in-memory copy of the state store should be identical across all the server nodes. But given that's not the case this is going to be a little more tricky...

Some things I'd want to look at here: 
* Is Nomad getting OOM'd with the high memory usage? If some process was causing a memory leak on all the machines, they could be getting the problem at different times. So the server you're observing is just the one in the worst shape at that moment. The numbers you're showing don't especially make me think that, but it'd be good to eliminate it. 
* Is Nomad chewing through a particularly large deployment? If a scheduling job on one server had pathological memory usage in 0.12.x, I could see it being possible that the work isn't getting finished (especially if we OOM), causing it to keep happening until the eval gets rejected.
* If you can turn `enable_debug = true`, taking a heap profile using the `/debug/pprof/heap` endpoint of the misbehaving server would probably narrow the issue down. You could take the resulting heap, load it into `go tool pprof` and use the `web` output to get a SVG that'd be reasonably human-readable.
* But given the size of the heap involved it might be worth checking that it hasn't run away with goroutines and take a goroutine profile first (via `/debug/pprof/goroutine?debug=2`)

**Comment by tgross** [comment]
Without more feedback on this one I'm afraid we'll have to close it. We do have some ongoing resource-utilization experiments which might help reduce overhead.
