### ISSUE TITLE
nomad operator debug doesn't capture CSI volume claims

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#9262]
The `nomad operator debug` command sends a [`/v1/volumes?type=csi`](https://github.com/hashicorp/nomad/blob/v1.0.0-beta2/api/csi.go#L20-L29) query, but that returns a [`CSIVolumeListStub`](https://github.com/hashicorp/nomad/blob/v1.0.0-beta2/api/csi.go#L168-L189) which contains no information about volume claims. As this is the most relevant piece of data on volumes, we should try to get the claims listed in the stub.

**Comment by davemay99** [comment]
@tgross I added initial support for looping over CSI plugins and volumes in #9346.  Is there any additional data you think should be captured?

**Comment by tgross** [comment]
No, that looks like all we'd need!
