### ISSUE TITLE
Cannot kill nomad with ctrl-c

### ISSUE THREAD

**Issue by i0rek** [hashicorp/nomad#9263]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version

```
$ nomad version
Nomad v0.12.7 (6147cb578794cb2d0c35d68fe1791728a09bb081)
```

### Operating system and Environment details

```
macos 10.15.7
```

### Issue

Cannot kill running nomad with ctrl-c.

### Nomad Client logs (if appropriate)

Uploading the output of `ctrl-\` because the log has 17k lines: [trace.log](https://github.com/hashicorp/nomad/files/5490561/trace.log).

**Comment by shoenig** [comment]
Hi @i0rek, was was Nomad running in `-dev` mode at the time? If so, Nomad will issue a signal to each running task waiting for shutdown (or timeout) before stopping the client.

**Comment by i0rek** [comment]
@shoenig yes, nomad was running in dev mode!

**Comment by tgross** [comment]
It looks from the stack trace that Nomad was indeed blocking on a task kill. Going to close this but let's re-open if there's new information to be had.

**Comment by azr** [comment]
Hello there, this often happens for me, looks like it's a not-enough RAM issue to kill things fast enough, not sure.
Here's a crash log after running `ctrl-\` in case: [trace.log](https://github.com/hashicorp/nomad/files/6457885/trace.log)
