### ISSUE TITLE
[1.0.0-beta2]: Missing Topology Data

### ISSUE THREAD

**Issue by tcdev0** [hashicorp/nomad#9276]
### Nomad version

Nomad v1.0.0-beta2
Consul v1.8.5

### Operating system and Environment details

Ubuntu 18.04

### Issue

Topology only shows Data for Jobs running within the default namespace. 

### Reproduction steps

Deploy a nomad job in a different namespace than default.

```
job "traefik-int-1" {

  datacenters = ["lb"]
  namespace = "lb"
  type = "service"
...
```
![nomad-02](https://user-images.githubusercontent.com/822498/98262333-c750ba00-1f85-11eb-8aa2-416e83313d4f.png)

No data is shown for Job (Empty Client). 

![nomad_01](https://user-images.githubusercontent.com/822498/98262313-c0c24280-1f85-11eb-82e1-ff17ffae1c52.png)

**Comment by DingoEatingFuzz** [comment]
Thank you for taking the time to report this! It was fixed in https://github.com/hashicorp/nomad/pull/9223 and will go out in the next beta.
