### ISSUE TITLE
Consider pod or image manifest generation for rkt containers

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#928]
* https://github.com/appc/spec/blob/master/spec/pods.md
* https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema

Generating a manifest should make for simpler code, less coupling to rkt, and open the door to other App Container Executors.  Mount points, environment variables, the exec command, and memory and cpu isolators can all be specified in the manifest.

**Comment by ranjib** [comment]
is this relevant to nomad? image manifest should be generated by the image builder (acbuild or docker or nut etc)

**Comment by blalor** [comment]
Yes it is.  Instead of building up a complex set of command-line arguments (which tightly couple nomad to the rkt binary's interface), nomad can generate an image manifest with a dependency on the image the user wishes to run, in addition to the other things I mentioned above.

**Comment by achanda** [comment]
While I agree that building the CLI and exec'ing `rkt` is ugly, I don't think generating a manifest is the right way. Nomad needs to provide an uniform interface for all the drivers, this might be a challenge with generating manifests. For drivers like `exec` and `java`, the idea of a manifest becomes invalid.

**Comment by blalor** [comment]
I’m not following the logic there.  I’m suggesting that the driver (rkt.go) generate an image manifest and use that when invoking `rkt run`.  I’m not proposing any change to Nomad’s config DSL.  That hopefully makes implementing another ACE simpler in the future.

**Comment by dadgar** [comment]
For the time being using the CLI has been working. If we run into something that is not possible with it we will reconsider this. Thanks!
