### ISSUE TITLE
Garbage Collector not Respecting Namespace

### ISSUE THREAD

**Issue by herter4171** [hashicorp/nomad#9295]
### Nomad version
Nomad v1.0.0-beta2 (3acb12bb809712ab2e63f0adc4a6422c2ade27da)

### Operating system and Environment details
* Amazon Linux 2
* EC2 autoscaling group

### Issue
I've been testing namespaces out, and I have one named `bob`.  When I have dead jobs in the default namespace and in `bob`, running the following removes all of the dead jobs, instead of just from the namespace specified in my command.
```
nomad system gc -namespace="bob"
```

### Reproduction steps
1. Create dead jobs in multiple namespaces
1. Run `nomad system gc -namespace=` with one specified

At least on my platform, this removes all dead jobs, instead of the desired target namespace.

**Comment by tgross** [comment]
Hi @herter4171! Sorry about that!

This looks like both a documentation bug (inasmuch as we dropped a bunch of default flags into the docs for the command), and a bug in `nomad system gc`. That command intentionally doesn't respect namespaces -- if you have ACLs enabled it requires a management token, not a namespaced token.

**Comment by herter4171** [comment]
Okay, the reason I want to run `gc` on a per-namespace basis is that we have a small number of users running all `batch` jobs in their respective namespaces, and when users are iterating a lot, they aren't able to rerun jobs with the same name.  I also believe the `service` type is out of the question, because we need the containers to exit gracefully.  I'm also hesitant to set the `gc` interval really small, because people may want to view logs.

Just so I'm clear, there's never going to be a way to constrain `gc` to operate on a specific namespace using a management token?

**Comment by tgross** [comment]
> Just so I'm clear, there's never going to be a way to constrain `gc` to operate on a specific namespace using a management token?

I wouldn't say "never" but definitely not on the roadmap. 

But for the use case you've just described, you can use `nomad job stop -purge :jobid`.

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  type = "batch"

  group "worker" {

    task "worker" {
      driver = "docker"

      config {
        image = "busybox:1"
        command = "/bin/sh"
        args = ["-c", "echo 'this looks like work'; sleep 10"]
      }

      resources {
        cpu    = 256
        memory = 128
      }
    }
  }
}

```

</details>



```sh
# run the job
$ nomad job run ./example.nomad
==> Monitoring evaluation "50aa151e"
    Evaluation triggered by job "example"
    Allocation "b05e974d" created: node "daaa9fef", group "worker"
==> Monitoring evaluation "50aa151e"
    Allocation "b05e974d" status changed: "pending" -> "running" (Tasks are running)
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "50aa151e" finished with status "complete"

# check that it's running...
$ nomad job status example
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
b05e974d  daaa9fef  worker      0        run      running  6s ago   5s ago

# wait 10 sec...
$ nomad job status example
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
b05e974d  daaa9fef  worker      0        run      complete  12s ago  1s ago

# run it again... nothing to do, so it doesn't run again!
$ nomad job run ./example.nomad
==> Monitoring evaluation "54654842"
    Evaluation triggered by job "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "54654842" finished with status "complete"

# no new allocs!
$ nomad job status example
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
b05e974d  daaa9fef  worker      0        run      complete  28s ago  17s ago

# force just that job to GC
$ nomad job stop -purge example
==> Monitoring evaluation "8fed28c9"
    Evaluation triggered by job "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "8fed28c9" finished with status "complete"

# now it's gone!
$ nomad job status example
No job(s) with prefix or id "example" found

# run it again, and it works!
$ nomad job run ./example.nomad
==> Monitoring evaluation "e2c433b7"
    Evaluation triggered by job "example"
    Allocation "2f24c775" created: node "daaa9fef", group "worker"
==> Monitoring evaluation "e2c433b7"
    Allocation "2f24c775" status changed: "pending" -> "running" (Tasks are running)
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "e2c433b7" finished with status "complete"
```

**Comment by herter4171** [comment]
Wow, that's perfect.  Thanks.  I'm all set.

**Comment by tgross** [comment]
Cool. I'm going to keep this issue open so we can fix the docs.

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/9400 and that'll go out the next time we push to the website
