### ISSUE TITLE
pass Headers in Nomad Artifacts stanza

### ISSUE THREAD

**Issue by Settler** [hashicorp/nomad#9306]
Hello.
Is there any possibility to specify Headers in Artifacts stanza? I'm searching way to add `Authorization` header to allow Nomad to download artifacts from our secured backend server.

I saw this issue in go-getter repository https://github.com/hashicorp/go-getter/issues/71. So they added this possibility, but Nomad, as I understand, still doesn't allow that in Artifacts.

**Comment by tgross** [comment]
Hi @Settler! It looks like that was implemented in go-getter as an option on [`HttpGetter`](https://github.com/hashicorp/go-getter#headers). But there's not currently a way to get those headers added from a Nomad option. That seems like a reasonable thing to do though, so I'll mark this as an enhancement for future work.
