### ISSUE TITLE
Dispatch parameterized jobs from UI [feature request]

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/nomad#9313]
### Feature

It would be useful to dispatch simple parameterized jobs from the ui, rather than having to use the cli/api to do this. Currently I have various housekeeping jobs which operate on a single parameter, which is typically a single word. It would be very quick and easy to open the webui, find the job, click a dispatch button, enter the meta parameter and hit go. The cli alternative requires a lot of typing, and wrangling of tokens from vault, managing env vars etc. As the nomad administrator, I have the tools and info readily to hand, ops teammates do not always have this setup, or do it often enough that the commands to do so are in muscle memory. The ethos for the UI appears to be "make life easier" and this would fit well with that.

### Possible implementation

i can imagine a very simple UI which simply renders text inputs for the defined meta parameters (with indication as to which ones are required) and a textarea/file upload widget for the payload data.

### Use cases

Example operations which would become much easier to operate via UI:
- A batch job which clones the production database to a staging/dev environment taking the target environment as a meta parameter
- A user onboarding batch job which takes a username and a role as meta parameters and registers them in some system

**Comment by DingoEatingFuzz** [comment]
This is an excellent idea and one that I have given some backburner thought to as well. Here's a wireframe from some prior noodling:

![image](https://user-images.githubusercontent.com/174740/98741522-aad7c780-2361-11eb-9de9-600c9ca4be49.png)

**Comment by pznamensky** [comment]
@DingoEatingFuzz looks really awesome!
