### ISSUE TITLE
Nomad default bridge subnet wrong

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#9316]
The docs suggest ( https://www.nomadproject.io/docs/configuration/client#bridge_network_subnet  ) suggest a /23 subnet, the code and actual bridge configuration seems to disagree: https://github.com/hashicorp/nomad/blob/86882dffc0c7370c2217aea3da7b232f9a8c6e3c/client/allocrunner/networking_bridge_linux.go#L24 and actually creates a /20 subnet.

**Comment by shoenig** [comment]
Thanks for pointing that out @apollo13 , we'll get the docs fixed up!
