### ISSUE TITLE
system job fails to update service tags

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#9358]
### Nomad version
0.12.5

### Operating system and Environment details
Linux + Consul 1.8.3

### Issue

Normally redeploy a job with an updated service tags will trigger the service registration update as well. 
However, that doesn't seem to be the case right now for `system` type jobs.

### Reproduction steps

1. Deploy the job file below
2. Change the tags
  ```diff
  - tags = ["http", "example-v1"]
  + tags = ["http", "example-v2"] 
  ```
3. Redeploy the job file
4. The service registration in Consul is not updated.

### Job file (if appropriate)

```
job "example-job-system" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "system"

  group "example-service-api-group" {
    count = 1

    network {
      mode = "bridge"
    }

    service {
      name = "example-system-service"
      port = "8082"
      tags = ["http", "example-v1"]
    }

    task "example-fake" {
      driver = "docker"

      config {
        image = "nicholasjackson/fake-service:v0.12.0"
      }

      env {
        LISTEN_ADDR = "0.0.0.0:8080"
      }
    }
  }
}

```

**Comment by fredwangwang** [comment]
verified also adding the `check` does not trigger service registration update neither.

**Comment by drewbailey** [comment]
Thank you for reporting @fredwangwang, I was able to reproduce this in 0.12.9 and tested in 1.0.1 and believe the issue has been fixed.

Here is the error that was blocking the consul sync operation.
```
   * update hook "group_services" failed: unable to get address for service "example-system-service": invalid port "8082": port label not found
"
```

Could you please confirm you are no longer running into this issue?

**Comment by fredwangwang** [comment]
Hi @drewbailey I dont have a 1.0.1 setup right now but if you verified its been fixed, happy to close it.
Btw, could you point me to the code change that fixes the issue? Curious to know :)
