### ISSUE TITLE
Allocated Ports are duplicated on Alloc info

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#9367]
# Nomad version
Nomad v1.0.0-beta3 (fcb32ef7ba037b2b83e7a0fd1c53c7410a2990db)

### Issue
the ports listed under `AllocatedResources` contain a growing list of duplicated allocations

### Reproduction steps
1. create a job with a static port resource (I used the [traefik job](https://learn.hashicorp.com/tutorials/nomad/load-balancing-traefik?in=nomad/load-balancing))
2. note that on every query to the allocation, the `AllocatedResources` includes an increasing number of copies of the port reservations: 
```
$ nomad alloc status -json 44302903  | jq '.AllocatedResources.Shared.Ports | length'
56

$ nomad alloc status -json 44302903  | jq '.AllocatedResources.Shared.Ports | length'
58
```

I suspect that the issue is that the allocGet endpoint is calling canonicalize on the in-mem structs object: 
https://github.com/hashicorp/nomad/blob/974039ba8bf67a129c6cf854ecd89ad20035eb04/command/agent/alloc_endpoint.go#L130

**Comment by cgbaker** [comment]
still an issue on 0.12.8
also, PR #9368 potentially does a double-copy (I missed that there is a potential alloc copy in there if the job payload is decoded)

**Comment by tgross** [comment]
@cgbaker should this have been closed by https://github.com/hashicorp/nomad/issues/9367 or is this something we need to get fixed before 1.0-rc?

**Comment by tgross** [comment]
Checked with current `master`:

```
$ nomad job run ./traefik.nomad
Job Warnings:
1 warning(s):

* Group "traefik" has warnings: 1 error occurred:
        * 1 error occurred:
        * Task "traefik": task network resources have been deprecated as of Nomad 0.12.0. Please configure networking via group network block.





==> Monitoring evaluation "75abe09a"
    Evaluation triggered by job "traefik"
    Allocation "a223dff5" created: node "ae49493f", group "traefik"
==> Monitoring evaluation "75abe09a"
    Evaluation within deployment: "5371c3e0"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "75abe09a" finished with status "complete"

$ nomad alloc status -json a223dff5 | jq '.AllocatedResources.Shared.Ports | length'
2
$ nomad alloc status -json a223dff5 | jq '.AllocatedResources.Shared.Ports | length'
2
```

Looks like we're good?

**Comment by tgross** [comment]
Verified with RC1.
