### ISSUE TITLE
Update HCL Examples containing Quoted keys

### ISSUE THREAD

**Issue by varrix** [hashicorp/nomad#9370]
### Issue
In the example seen [here](https://www.nomadproject.io/docs/job-specification#example) I believe there's a typo on the following section:
```
...
      env {
          "DB_HOST" = "db01.example.com"
          "DB_USER" = "web"
          "DB_PASS" = "loremipsum"
      }
...
```

I'm still relatively new to nomad and the hcl syntax in general. I may be incorrect, although I don't believe the syntax supports keys being quoted. Please let me know if I'm wrong here- and if I am, I'd love to know the intended use of quoted keys.

**Comment by notnoop** [comment]
Hi @varrix - Very sharp eye! Thanks for raising it.  Quoted keys have been supported in HCL 1 and Nomad so far.  However, the upcoming Nomad 1.0 will require unquoted keys, as it adopts HCL 2.0 and become inline with other Terraform and Packer.  We will update the example.  Thanks!

**Comment by varrix** [comment]
Ah okay then I may have found a few examples in the docs that do this as well. Would you like me to rename the issue to track all these for future reference when it is to be changed?

Although if I understand correctly HCL allows(or perhaps mandates) map declarations to have quoted keys. I just want to make sure I understand what can and can't be quoted.

**Comment by Amier3** [comment]
As far as I can tell, this is fixed.
