### ISSUE TITLE
[question] rejoin_after_leave for server only?

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/nomad#938]
Wondering if the documentation is correct here.

It seems that `leave_on_interrupt` and `leave_on_terminate` are supported for both client and server, but according to the current documentation `rejoin_after_leave` is only supported for server.

Is this correct?

If so, is it not possible to have a client rejoin, or is client rejoining the default?

**Comment by dadgar** [comment]
The documentation is correct. The client rejoining is the default behavior!
