### ISSUE TITLE
Document the network_speed unit

### ISSUE THREAD

**Issue by rgl** [hashicorp/nomad#9385]
Can you please document the unit that is used https://www.nomadproject.io/docs/configuration/client#network_speed?

I can alternatively submit a PR when you tell me what is the unit :-)

### Nomad version

Nomad v1.0.0-beta3 (fcb32ef7ba037b2b83e7a0fd1c53c7410a2990db)

**Comment by tgross** [comment]
Hi @rgl! That's in `mbits`. But just a heads up that the jobspec field that consumes that value has been deprecated but not yet entirely removed (see https://github.com/hashicorp/nomad/issues/8681)

**Comment by rgl** [comment]
Does that mean it no longer has any effect?

**Comment by nh2** [comment]
`network_speed` is still used in the tutorial's default config:

https://www.nomadproject.io/docs/configuration

```
client {
  enabled       = true
  network_speed = 10
}
```

But it's not documented anywhere what unit that is.

@tgross Is it only removed from the jobspec, or should it also be removed from the agent config?

**Comment by tgross** [comment]
We removed it from the docs in https://github.com/hashicorp/nomad/pull/9685 but missed the example. I'll remove that. Thanks!
