### ISSUE TITLE
Rotating Nomad Servers sometimes causes missed Client heartbeats

### ISSUE THREAD

**Issue by cullenmcdermott** [hashicorp/nomad#9390]
### Nomad version
0.12.7 Enterprise

### Operating system and Environment details
Ubuntu 18.04 in AWS

### Issue

We've noticed some issues sometimes when we roll our Nomad Servers where a client will seemingly miss a heartbeat to a server and because the heartbeat is missed the servers will revoke the client's secrets. The client will begin returning 403s in the logs when trying to render out job templates, eventually this causes the node to be recycled because we have ELB health checks setup on the host so if Traefik is not running it will fail the health check.

I'm only able to replicate this maybe 10-20% of the time. I tested this about 5 times the other day and was only able to trigger it once.

#### Timeline
- 10:21 am - Increase Nomad Server ASG from 3 to 6
- 10:22 am - New nomad servers are up and in the quorum
- 10:29 am - Decrease Nomad Server ASG size from 6 to
- 10:34 am - AWS begins shutting down 3 instances, it picks the 3 newer instances. No leader election was triggered since leader was on one of the older nodes.
- 10:35:27.461 - Client with ID ending in `decc` logs "Error performing RPC to server", "rpc error: failed to get conn: dial tcp 10.0.70.237:4647: i/o timeout"
- 10:35:27.461 - `decc` logs "error heartbeating. retrying" and "failed to update status: rpc error: failed to get conn: dial tcp 10.0.70.237:4647: i/o timeout"
- 10:35:27.470 - `decc` logs "discovered following servers" and returns the following correct list of servers:
```
{"Addr":{"Zone":"","IP":"10.0.69.137","Port":4647}}
{"Addr":{"Zone":"","IP":"10.0.67.105","Port":4647}}
{"Addr":{"Zone":"","IP":"10.0.72.37","Port":4647}}
```
- 10:35:27.491 - `decc` logs "missed heartbeat"
- 10:36 am - AWS finishes terminating 3 instances
- 10:35:39 to 10:49:01 - `decc` logs 403s and permission denied trying to render static KVs from Vault until it is terminated by AWS

#### Other notes:
Servers that were terminated:
    - i-0fea428c180f93208 - 10.0.64.202
    - i-03acf07184dbc4047 - 10.0.72.17
    - i-0cb45b1bafdbe404d - 10.0.70.237 ← This is what the client tried to heartbeat to

Would increasing the heartbeat_grace help here? We are using the defaults currently.
- My understanding with heartbeat_grace is that its extra time on top of the min_heartbeat_ttl so if heartbeat_grace is 10s and min_heartbeat_ttl is 10s, a client has 20 seconds to heartbeat?

I see "serf: Shutdown without a leave" in the logs. Is there a more graceful way for us to have servers leave as they are shutting down? Right now we don't do anything special when shutting down/terminating servers.

Let me know if logs would help, I'm happy to get them from from our logging system.

**Comment by tgross** [comment]
> Would increasing the heartbeat_grace help here? We are using the defaults currently.
> My understanding with heartbeat_grace is that its extra time on top of the min_heartbeat_ttl so if heartbeat_grace is 10s and min_heartbeat_ttl is 10s, a client has 20 seconds to heartbeat?

Yes, that should help. But getting the servers to shutdown gracefully so that they deregister from Consul (which the client is using to find the new list when it gets a failure) should also have a big impact here for you. 

> I see "serf: Shutdown without a leave" in the logs. Is there a more graceful way for us to have servers leave as they are shutting down? Right now we don't do anything special when shutting down/terminating servers.

The [`nomad server force-leave`](https://www.nomadproject.io/docs/commands/server/force-leave) command will help you here, as will [Autopilot](https://learn.hashicorp.com/tutorials/nomad/autopilot). Generally speaking we recommend that you cycle out Nomad servers one at a time and then wait for the new memberlist to settle before terminating the next one. See the [upgrade guide](https://www.nomadproject.io/docs/upgrade#3-remove-the-old-versions-from-servers) for some specific recommendations.

**Comment by cullenmcdermott** [comment]
Thanks for the response! I think I know how to fix this on our side.
