### ISSUE TITLE
Document all possible job statuses

### ISSUE THREAD

**Issue by chrismikehogan** [hashicorp/nomad#9398]
### Nomad version
0.10.2

### Operating system and Environment details
N/A

### Issue
We are building APIs that interface with the Nomad HTTP API. Many enumerated fields like Job.Status are not documented, so we have been left to infer possible values from our own set of running jobs. This is error prone.

The allocations API docs outline all of the possible values for several fields, such as TaskStates.State, and TaskStates.Events.Type.

Can the same level of detail to be added to Job.Status?

### Reproduction steps
1. Forget what the possible values for Job.Status are. 
2. Read Nomad docs.

### Job file (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

**Comment by tgross** [comment]
Hi @chrismikehogan! The HTTP API in generally is under-documented so we need to invest some time in improving that situation. This is a good example for why.

> 1. Forget what the possible values for Job.Status are.

😆
