### ISSUE TITLE
[question]template stanza: env and change_mode signal

### ISSUE THREAD

**Issue by briantenazas** [hashicorp/nomad#9417]
Hi! 

I have nomad tasks that use env vars in the template for configuration but I'm also trying to send signals to the tasks for graceful restarts. The documentation on the template stanza https://www.nomadproject.io/docs/job-specification/template says:

``
env (bool: false) - Specifies the template should be read back in as environment variables for the task. (See below) Note that if noop mode is used for the change_mode, the task will not be restarted and the environment variables wwon't be changed in the task. If you set env = true, then the change_mode should be one of restart or signal.
``

However, I get an error when trying to deploy via Levant. 

``
Template 1 validation failed: 1 error occurred:\n\t* cannot use signals with env var templates\n\n\n\n\n\n\n\n)"
``

When looking at the code, it looks like there is a check to see if env vars are set here: https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L7266-L7267

Which is correct? Thanks!

**Comment by apollo13** [comment]
Given that the env vars are set as part of the container config, they cannot be refreshed without tearing down and restarting the container. So I guess the docs are wrong and the code is correct.

**Comment by tgross** [comment]
Hi @briantenazas! That's definitely a documentation bug. (Which is super unfortunate because I _just_ clarified that in https://github.com/hashicorp/nomad/commit/1392246e4e843ad58fa1c1755b8bbfee85d097b3 a few days ago but missed the signal behavior.) Will fix.
