### ISSUE TITLE
Error message Constraint "missing drivers" could convey more information

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#9437]
### Nomad version
Nomad v1.0.0-beta3 (fcb32ef7ba037b2b83e7a0fd1c53c7410a2990db)

### Operating system and Environment details
CentOS 7/8

### Issue
Typo in the job files leads to confusing (sort of) error messages. I think the error message can be improved to mention the name of "driver".
Here, if it were to emit something like `Constraint "missing drivers" for "row_exec" etc. etc.` the error could possibly be noticed much quicker?!

### Reproduction steps
Using the following job file, if you try a `plan` it doesn't mention which driver is "missing". ("row_exec" which is clearly a typo)

A `nomad plan` of the job file shows the following:

```bash
$ nomad plan package_update.nomad
+ Job: "package-update"
+ Task Group: "centos" (1 create)
  + Task: "yum" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "centos" (failed to place 1 allocation):
    * Class "nomad-server": 1 nodes excluded by filter
    * Class "aaaaaaa": 3 nodes excluded by filter
    * Class "bbbbbbb": 6 nodes excluded by filter
    * Class "ccccccc": 2 nodes excluded by filter
    * Class "ddddddd": 1 nodes excluded by filter
    * Constraint "missing drivers": 13 nodes excluded by filter

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 package_update.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.

```

### Job file (if appropriate)

Notice the typo; `row_exec` instead of the correct `raw_exec`

```hcl
job "package-update" {
  datacenters = ["dc1"]

  type = "batch"

  group "centos" {

    task "yum" {
      driver = "row_exec"

      config {
        command = "/bin/yum"
        args    = ["upgrade", "-y", "vim"]
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

**Comment by tgross** [comment]
Looks like that's coming from how we count the metrics for [`hasDrivers`](https://github.com/hashicorp/nomad/blob/v1.0.0-beta2/scheduler/feasible.go#L415-L465) in the feasibility step of the scheduler. We have some precedent for this sort of thing with CSI volumes, where the check returns more detailed error messages instead of just a bool. I don't think there's any particular reason we couldn't do something like this for drivers too.

**Comment by shantanugadgil** [comment]
Closing due to age,

Confirming that the error message is just as minimal with version 1.9.1.

I _still_ feel that the message could mention the driver name somewhere (which could make the typo more obvious)

```
+ Job: "package-update"
+ Task Group: "centos" (1 create)
  + Task: "yum" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "centos" (failed to place 1 allocation):
    * Constraint "missing drivers": 1 nodes excluded by filter

```
