### ISSUE TITLE
Output of /v1/metrics

### ISSUE THREAD

**Issue by treforroberts** [hashicorp/nomad#9440]
$ nomad version
Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)

from  http://{ClientNode}:4646/v1/metrics
nomad.client.allocs.cpu.allocated 

[Documented](https://www.nomadproject.io/docs/operations/metrics) as Percentage, output is MHz

**Comment by jrasell** [comment]
Hi @treforroberts and thanks for raising this issue. The documentation issue has been fixed within https://github.com/hashicorp/nomad/pull/9427 and will be available once the website is updated with the latest release.
