### ISSUE TITLE
Unexpected port exposure?

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#9456]
### Nomad version
Nomad v0.12.9 (45c139e53f2407a44b1290385b5818b46ea3a62c)

### Operating system and Environment details
**Ubuntu Bionic** | **Consul 1.8.6** | **cni-plugins 0.8.4**

### Issue
As far as I understand from [the network stanza described in the docs](https://www.nomadproject.io/docs/job-specification/network#to) Nomad should only perform a port mapping when the `to` field is configured with either a static port, or with `-1` to map the dynamic port into the task's network. This is not what is currently happening with `mode = "bridge"`, see the following example job:
```hcl
job "test" {
  datacenters = ["zone1"]
  group "test" {
    network {
      mode = "bridge"
      port "notexposed" {}
      port "exposed" {
          to = -1
      }
    }
    task "test" {
      driver = "docker"
      config {
        image = "alpine"
        command = "nc"
        args = ["-p", "${NOMAD_PORT_notexposed}", "-lk", "-e", "/bin/cat"]
      }
      resources {
        cpu    = 100
        memory = 64
      }
    }
  }
}
```
When I run this I can still access the service directly on the node port:
```
ygersie@nomad001:~$ nomad status 6fe19368 | grep exposed
*notexposed  yes      10.41.40.183:20621
*exposed     yes      10.41.40.183:21154 -> 21154

ygersie@nomad001:~$ date | nc 10.41.40.183 20621
Fri Nov 27 01:50:53 CET 2020
^C
```
As you can see I can access the "notexposed" port label directly.

Looking at the nomad client (different node) which runs this container this is indeed configured:
```
root@worker001:~# iptables -t nat -L -n | grep 'DNAT.*20621'
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:20621 to:172.26.64.45:20621
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:20621 to:172.26.64.45:20621
```

Am I misunderstanding how this is supposed to work or is this a bug?

**Comment by Oloremo** [comment]
Interested in this as well. Any updates?

**Comment by tgross** [comment]
It looks like this was a stale documentation issue. See https://github.com/hashicorp/nomad/issues/6958#issuecomment-869927378 for more details. I've opened https://github.com/hashicorp/nomad/pull/10828 to fix the docs.
