### ISSUE TITLE
NOMAD API fast parallel requests for DRAIN

### ISSUE THREAD

**Issue by kereza** [hashicorp/nomad#9461]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.11.7 

### Operating system and Environment details
CentOS Linux release 7.9.2009 (Core)

### Issue
Nomad API and NOMAD DRAIN ( downtime with jobs with COUNT => 2)

### Reproduction steps
2 Parallel request to NOMAD API for NOMAD DRAIN on two different NOMAD clients. Those two different NOMAD clients - hosts Jobs (docker containers) with COUNT => 2. Health check for the jobs are configure correctly !

### Nomad Client logs (if appropriate)
I am searching for assistance here and maybe exchange some ideas :slight_smile: . Maybe someone esle already have this problem etc.

The idea is have NOMAD cluster in AWS on EC2 instances (auto scaling groups). We have a cluster of 3 Servers and 3 Clients (workers). When we want to upgrade Nomad (or patch the Linux machines). We replace the Workers in the Auto Scaling Group. Like:

    Bring 3 NEW Nomad EC2 instances with the NEW Nomad version
    Now we have 6 Nomad Clients
    Drain the OLD Nomad CLients from the jobs (note that we have jobs with COUNT => 2, and we DO NOT WANT to have downtime) . By default the Nomad migrate stanza is doing drain ONE by ONE - works for us.
    Terminate the OLD Nomad clients
    We now have a cluster of 3 Nomad clients with the new version of Nomad

That implementation works well, but we want to make AUTOMATIC Drain of the workers with AWS Lambda (Auto Scaling Group triggering event and Lambda executing DRAIN on all the terminates Nomad Clients)

We manage to create the Lambda function and Python script there and it also works well. Here is the problem:

    The 3 OLD Nomad clients terminates at the SAME TIME
    They send event to Lambda at the same time
    I guess 3 parallel executions of Lambda happen
    API call is made to NOMAD API for DRAIN
    The problems as it seems is that - the NOMAD API receive those request at the same time and it starts DRAINING the Jobs (count => 2) at the same time and we have down time !!
    NOTE that our job health checks are correct (this works with delayed execution, as you will see down what I wrote)

I tested the executions of the python code from local compute and started the functions with delay of 1-2 seconds - and we DO NOT not down time - it works as expected. Is the NOMAD API problem ? It can not handle such parallel requests ?

I tried putting python SLEEP in the function - that does not help as all the funtion sleep at the same time and call NOMAD API at the same time !

Anybody we same/similar problem ? Any suggestions

Kind Regards

**Comment by kereza** [comment]
OK, I think I found something that works for me:

    Just use RANDOM in the python function and delay the function with the RANDOM time in seconds :slight_smile:

I am not the best programmer out there and could not came with this solution on my own !

**Comment by tgross** [comment]
Hi @kereza! I think we need a bit more information about this:

> The problems as it seems is that - the NOMAD API receive those request at the same time and it starts DRAINING the Jobs (count => 2) at the same time and we have down time !!

If you drain multiple nodes concurrently, Nomad is going to do what you've asked and have to find a new node to place the allocations that were on that node. If you have only 3 nodes with jobs on them all your allocations will be on those nodes and so I would definitely expect to see downtime if you drained all 3 at once -- it takes a non-zero amount of time to schedule and place the allocations to the new nodes.

The best way to solve this:
* [Disable node eligibility](https://www.nomadproject.io/docs/commands/node/eligibility) on all 3 of the old nodes with `nomad node eligibility -disable :nodeid`. This will prevent the drain of an old node from placing the allocation on one of the other nodes you're about to drain.
* Then drain the nodes one at a time, making sure you wait until the allocations have been placed on a new node before draining the next node.

**Comment by kereza** [comment]
Hello @tgross  and thank for the comment,

Note that I mentioned:

_Bring 3 NEW Nomad EC2 instances with the NEW Nomad version
Now we have 6 Nomad Clients (WORKERS)_

That means that we have a cluster of 6 CLIENTS and I do the drain on 3 (old ones) in parallel. When DRAIN is started on those old 3 CLIENTS - eligibility is disabled with the DRAIN command. So as expected - the jobs start moving from the OLD 3 Clients to the NEW 3 Clients.

The problem is that the jobs (which have COUNT=> 2 and good health checks) start DRAINING at the same time ! That get us to a down time. The expected behavior is to MOVE the jobs one by one and make sure that they are healthy. 

As mentioned above - I start the DRAIN scripts parallel (for every Client) at the same time. Seems to me that Nomad does not realize that and start moving all at the same time. I overcame this by placing a DELAY in calling each DRAIN script command by 1 second and there is no down time than. 

Regards

**Comment by tgross** [comment]
> The problem is that the jobs (which have COUNT=> 2 and good health checks) start DRAINING at the same time ! That get us to a down time. The expected behavior is to MOVE the jobs one by one and make sure that they are healthy.

I think this is where the confusion is... a node drain moves _allocations_ on the node, not _jobs_. When you drain all your nodes in parallel, Nomad is migrating the allocations off those nodes. There's no coordination between the nodes expected.

You've got the right workaround though, so I'm going to close this issue. Thanks!
