### ISSUE TITLE
Global Search on UI to Search Group/Job names and Allocation Ids

### ISSUE THREAD

**Issue by nileshcs** [hashicorp/nomad#9465]
### Nomad version
0.12.7

### Operating system and Environment details
Linux

### Issue
**Feature Request**
* Current Status: The global search option at the top in the UI searches for job names
* Enhancement Request: Also search across (1) group names, (2) task names, and (3) allocation ids
* Search for allocation ids is helpful, as we deploy batch jobs and also a new service for every Pull Request, creating many allocations. We use Consul UI and associated tags to find the allocation id. Right now there is no easy way to search for a given allocation.

I did discuss this with @yishan-lin

![image](https://user-images.githubusercontent.com/5154875/100553231-b4ff2e80-325a-11eb-8bb1-c5ea60b51a3a.png)

**Comment by tgross** [comment]
This has shipped in Nomad 1.1.0-beta
