### ISSUE TITLE
[feature] configuring resources for gateway stanza

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#9474]
### Nomad version
v0.12.5

Hi! We are trying to use the gateway stanza to streamline the process of deploying the ingress gateway. However, we noticed that there is (seems?) no easy way to configure the resources for the gateway task: https://github.com/hashicorp/nomad/blob/ec7bf9de21bfe3623ff04b009f26aaf488bae2b1/nomad/job_endpoint_hook_connect.go#L337 Recourse is hardcoded to use the defaults resources.

To set the resources we could manually create the whole task section to override, but curious if there is any plan to add like `sidecar_task` or something to simplify the resource definition for gateway task?

**Comment by shoenig** [comment]
Thanks for reporting, @fredwangwang - indeed our gateway support is still pretty MVP and isn't yet configurable in the same way connect sidecar proxies are. Improving this story is on our near term road map.

**Comment by hammad13060** [comment]
@shoenig I'd like to work on this. Can you assign this issue to me? Thanks.
