### ISSUE TITLE
Document running client as root

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#948]
Nomad documentation and [.service](../blob/master/dist/systemd/nomad.service) file suggest running daemon as _root_.
Is this a recommended practice for Nomad for some reason?

For services that do not drop privileges the usual installation practice is to create user then invoke daemon under dedicated user rather than as _root_ to minimise security risks of system being compromised through privileged service.

Is there any particular reason to run Nomad with root credentials?

**Comment by dadgar** [comment]
Hey,

The Nomad Servers do not need to be root but the clients do as they are using OS isolation mechanisms that require root privilege. You can always create a nomad user that has root privileges and run nomad under that too.

**Comment by onlyjob** [comment]
Thanks. If not too much troubles it would be nice to mention that in documentation. :)
