### ISSUE TITLE
applyUpsertJob causes duplicate job events in event stream

### ISSUE THREAD

**Issue by drewbailey** [hashicorp/nomad#9507]
When testing the event stream, we noticed when registering a job, multiple `JobRegister` events are added to the event stream.

This seems related to #8435. The logic in the state store to set the job status specifically empties out the current value if the index used to update the status is equal to the jobs create status.

https://github.com/hashicorp/nomad/blob/e64d5286647fdc190b2c03ead6c407f2ae09096c/nomad/state/state_store.go#L4429-L4432
This causes a second insertion into the jobs table with an identical value to what was inserted previously in the job register step.

branch with test: https://github.com/hashicorp/nomad/compare/drew/job-status

**Comment by tgross** [comment]
@drewbailey should this be closed by https://github.com/hashicorp/nomad/pull/9768?

**Comment by drewbailey** [comment]
Yep, thanks!
