### ISSUE TITLE
All batch jobs fail with -- Task exceeded restart policy, in nomad alloc-status

### ISSUE THREAD

**Issue by sethcleveland** [hashicorp/nomad#951]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
0.3.1

### Operating system and Environment details
CentOS Linux release 7.2.1511 (Core)

3 nomad servers, 3 docker servers running nomad clients. All 6 servers run consul agents.

### Issue
Every batch job fails for "Task exceeded restart policy" in the nomad alloc-status.

```
./nomad alloc-status f64e5e3a
ID              = f64e5e3a
Eval ID         = c6fde4ea
Name            = example.example[0]
Node ID         = 4a1aeaef
Job ID          = example
Client Status   = failed
Evaluated Nodes = 2
Filtered Nodes  = 0
Exhausted Nodes = 0
Allocation Time = 114.97µs
Failures        = 0

==> Task "example" is "dead"
Recent Events:
Time                   Type               Description
21/03/16 11:31:41 CDT  Restarts Exceeded  Task exceeded restart policy
21/03/16 11:31:41 CDT  Driver Failure     error starting process via the plugin: binary "/var/nomad/alloc/f64e5e3a-430d-57c4-ee8c-a8bdd040adc1/example/docker" does not exist
21/03/16 11:31:41 CDT  Received           Task received by client

==> Status
Allocation "f64e5e3a" status "failed" (0/2 nodes filtered)
  * Score "4a1aeaef-d32e-bf42-e22a-4dc37d6d9bfc.binpack" = 1.999789
  * Score "b60069ed-f462-3835-d70c-f3cbaf93c4d7.binpack" = 0.134053

==> Task Resources
Task: "example"
CPU  Memory MB  Disk MB  IOPS  Addresses
100  10         300      0
```

### Reproduction steps
We've run a lot of other service and batch jobs prior to these steps. They are hard to document and explain.

nomad run example.nomad
nomad status example
nomad alloc-status $alloc_id

### Job file if appropriate
```
job "example" {
    region = "global"
    datacenters = ["devstk"]
    type = "batch"
    group "example" {
        restart {
            attempts = 1
            interval = "1s"
            delay = "1s"
            mode = "delay"
        }
        task "example" {
            driver = "raw_exec"
            config {
                command = "docker"
                args = ["images"]
            }
            resources {
                network {
                    mbits = 100
                }
            }
        }
    }
}```

**Comment by dadgar** [comment]
Hey this is not a bug. In Nomad 0.3.1 your path needs to be absolute to the binary. You can see it is saying that it is trying to fork/exec "/var/nomad/alloc/f64e5e3a-430d-57c4-ee8c-a8bdd040adc1/example/docker" which does not exist. Please change your `command` to be the full path to docker. Nomad 0.3.2 (or master) will bring back the old behavior,

**Comment by sethcleveland** [comment]
Thanks!
