### ISSUE TITLE
Docs: Update enterprise sections to use enterprise badge

### ISSUE THREAD

**Issue by drewbailey** [hashicorp/nomad#9529]
We have a recently introduce enterprise badge for docs

#### New
![image](https://user-images.githubusercontent.com/2614075/101193274-56ef9400-362a-11eb-9372-814a5483f839.png)

#### Old
![image](https://user-images.githubusercontent.com/2614075/101193401-869e9c00-362a-11eb-8490-f97ddb8b4bdf.png)

Update old warning banners with new badge

**Comment by gunadhya** [comment]
Hi @drewbailey, I'd like to work on this issue.
