### ISSUE TITLE
Trying to read logs from other nodes in the cluster

### ISSUE THREAD

**Issue by carlsverre** [hashicorp/nomad#953]
### Nomad version
Nomad v0.3.1

### Operating system and Environment details
```
ip-10-0-1-22 /home/admin $ cat /etc/debian_version
8.3
ip-10-0-1-22 /home/admin $ uname -a
Linux ip-10-0-1-22 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
```

### Issue
According to the blog post on Nomad 0.3.x (https://www.hashicorp.com/blog/nomad-0.3.html) I should be able to read alloc logs from any machine in my nomad cluster.  I see the following behavior instead:

On any of my Nomad servers I get this error:

```
ip-10-0-3-0 /home/admin $ nomad fs ls 2e3dae75
Error listing alloc dir: node is not running a Nomad Client
```

On any of my Nomad clients (other than the one the alloc is on) I see:
```
ip-10-0-1-22 /home/admin $ nomad fs ls 2e3dae75
Error listing alloc dir: alloc not found
```

On the Nomad client running the task:
```
ip-10-0-1-21 /home/admin $ nomad fs ls 2e3dae75
Mode        Size    Modfied Time           Name
drwxr-xr-x  4.1 kB  21/03/16 19:22:59 UTC  alloc/
drwxr-xr-x  4.1 kB  21/03/16 19:22:59 UTC  server/
```

**Comment by carlsverre** [comment]
Some notes:

* I am using the docker driver
* I have two nomad clients and three nomad servers
* all machines are the same version of debian, and are otherwise barebones (just nomad, consul, docker basically)

**Comment by diptanu** [comment]
@carlsverre Sorry for the late response on this. I think this is happening because all your nodes http addresses are reporting 127.0.0.1. Can you please share with us what Nomad returns if you do a http `GET` request on the API `/v1/node/<nod-id>` and replace `<node-id>` there with the node id of a Nomad client?

I think you just need to set the `advertise` block in your Nomad config on the nomad clients so that they report the right addresses of the http endpoints of Nomad clients.

**Comment by carlsverre** [comment]
Here is what nomad returns when I check the API for one of my nomad clients:

```
ip-10-0-3-181 /home/admin $ curl localhost:4646/v1/node/c34d0c22-7a85-e010-17c5-5cba23112f56 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2008  100  2008    0     0   215k      0 --:--:-- --:--:-- --:--:--  217k
{
  "ID": "c34d0c22-7a85-e010-17c5-5cba23112f56",
  "Datacenter": "us-east-1",
  "Name": "runner-10-0-0-206",
  "HTTPAddr": "0.0.0.0:4646",
  "Attributes": {
    "arch": "amd64",
    "consul.datacenter": "us-east-1",
    "consul.revision": "26a0ef8c41aa2252ab4cf0844fc6470c8e1d8256",
    "consul.server": "false",
    "consul.version": "0.6.4",
    "cpu.frequency": "2893.380000",
    "cpu.modelname": "Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz",
    "cpu.numcores": "8",
    "cpu.totalcompute": "23147.040000",
    "driver.docker": "1",
    "driver.docker.version": "1.10.3",
    "hostname": "ip-10-0-0-206",
    "kernel.name": "linux",
    "kernel.version": "3.16.0-4-amd64",
    "memory.totalbytes": "15804608512",
    "os.name": "debian",
    "os.version": "8.3",
    "platform.aws.instance-type": "c4.2xlarge",
    "platform.aws.placement.availability-zone": "us-east-1e",
    "unique.cgroup.mountpoint": "/sys/fs/cgroup",
    "unique.consul.name": "runner-10-0-0-206",
    "unique.network.ip-address": "10.0.0.206",
    "unique.platform.aws.ami-id": "ami-b12729db",
    "unique.platform.aws.hostname": "ip-10-0-0-206.ec2.internal",
    "unique.platform.aws.instance-id": "i-deb5b827",
    "unique.platform.aws.local-hostname": "ip-10-0-0-206.ec2.internal",
    "unique.platform.aws.local-ipv4": "10.0.0.206",
    "unique.platform.aws.public-hostname": "ec2-52-3-248-19.compute-1.amazonaws.com",
    "unique.platform.aws.public-ipv4": "52.3.248.19",
    "unique.storage.bytesfree": "257919262720",
    "unique.storage.bytestotal": "270429831168",
    "unique.storage.volume": "/dev/xvda2"
  },
  "Resources": {
    "CPU": 23147,
    "MemoryMB": 15072,
    "DiskMB": 245970,
    "IOPS": 0,
    "Networks": [
      {
        "Device": "eth0",
        "CIDR": "10.0.0.206/32",
        "IP": "10.0.0.206",
        "MBits": 760,
        "ReservedPorts": null,
        "DynamicPorts": null
      },
      {
        "Device": "eth0",
        "CIDR": "10.0.0.206/32",
        "IP": "10.0.0.206",
        "MBits": 10000,
        "ReservedPorts": null,
        "DynamicPorts": null
      }
    ]
  },
  "Reserved": {
    "CPU": 0,
    "MemoryMB": 0,
    "DiskMB": 0,
    "IOPS": 0,
    "Networks": null
  },
  "Links": {
    "aws.ec2": "us-east-1e.i-deb5b827",
    "consul": "us-east-1.runner-10-0-0-206"
  },
  "Meta": {},
  "NodeClass": "c4.2xlarge",
  "ComputedClass": "v1:10810399064826004786",
  "Drain": false,
  "Status": "ready",
  "StatusDescription": "",
  "CreateIndex": 27,
  "ModifyIndex": 40
}
```

**Comment by diptanu** [comment]
@carlsverre So the `HTTPAddr` is set to `0.0.0.0:4646` which is why the Nomad cli isn't able to figure out the HTTP Address of the node when it tries to hit it from a remote server and ends up hitting the Nomad agent running on the same node. 

If you set the `advertise` block in your Nomad config this will work, you can get more details about the `advertise` block here - https://www.nomadproject.io/docs/agent/config.html

**Comment by carlsverre** [comment]
According to that documentation the advertise block is "[snip] is only applicable on server nodes".

I set it anyways on one of my clients and I still get this error when trying to run `fs ls`:

```ip-10-0-3-181 /home/admin $ nomad fs ls 73bc0694
Error listing alloc dir: node is not running a Nomad Client```

**Comment by diptanu** [comment]
@carlsverre Sorry, we need to update the documentation. On the client node the advertise block overrides the http address that the client advertises to the server.

Can you please share with us your nomad client config? Also can you share what the json blob of the node says in which you have set the advertise block?

**Comment by carlsverre** [comment]
I just added this to my nomad client and it worked:

```
advertise {
    http = "10.0.0.206:4646"
}
```

I think you just need to add the "http" key to your documentation and remove the "only applicable to server nodes" line.

**Comment by diptanu** [comment]
@carlsverre Yes, I am doing it now. Sorry for the confusion.

**Comment by carlsverre** [comment]
Thanks!

**Comment by ketzacoatl** [comment]
Currently the docs say:

> advertise: Controls the advertise address for individual network services. This can be used to advertise a different address to the peers of a server node to support more complex network configurations such as NAT. This configuration is optional, and defaults to the bind address of the specific network service if it is not provided. This configuration is only applicable on server nodes. The value is a map of IP addresses and ports and supports the following keys:
>
>    rpc: The address to advertise for the RPC interface. This address should be reachable by all of the agents in the cluster. For example: advertise { rpc = "1.2.3.4:4647" }
>    serf: The address advertised for the gossip layer. This address must be reachable from all server nodes. It is not required that clients can reach this address.

What's confusing to me is that it seems publishing the HTTP address is required, but this doc makes it sound like it's optional.
