### ISSUE TITLE
NoMad Mac sigkill

### ISSUE THREAD

**Issue by tsinghzf** [hashicorp/nomad#9530]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from Nomad Version 1.2.2

### Issue
Nomad randomly has started through SIGKILL across multiple devices and has stopped working. 

### Reproduction steps
I reinstalled the OS, and the issue persists. I then upgraded from Mojave to Catalina, and the issue persisted. I wiped and reinstalled Catalina OS and the issue persisted.
### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.
(com.apple.mdworker.shared.01000000-0400-0000-0000-000000000000[94024]): Service exited due to SIGKILL | sent by mds[96]
Dec  4 15:01:00 TSingh-mbp com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0C000000-0300-0000-0000-000000000000[94025]): Service exited due to SIGKILL | sent by mds[96]
Dec  4 15:01:01 TSingh-mbp com.apple.xpc.launchd[1] (com.apple.mdworker.shared.05000000-0300-0000-0000-000000000000[94026]): Service exited due to SIGKILL | sent by mds[96]
Dec  4 15:01:04 TSingh-mbp com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0F000000-0300-0000-0000-000000000000[94028]): Service exited due to SIGKILL | sent by mds[96]
Dec  4 15:01:10 TSingh-mbp com.apple.xpc.launchd[1] (com.trusourcelabs.NoMAD[94103]): Service exited due to SIGILL | sent by exc handler[94103]
Dec  4 15:01:10 TSingh-mbp com.apple.xpc.launchd[1] (com.trusourcelabs.NoMAD): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Hi @tsinghzf! This is the issue tracker for HashiCorp's https://www.nomadproject.io/, not https://nomad.menu/, which is written by a different company altogether (Jamf). I think you'll want to take a look at https://www.jamf.com/support/nomad/ for support for NoMAD.
