### ISSUE TITLE
nomad server fails to start when parsing CNI config file

### ISSUE THREAD

**Issue by x3nb63** [hashicorp/nomad#9534]
### Nomad version
Nomad v0.12.8

### Operating system and Environment details
Arch Linux

### Issue

I am setting up CNI plugins and get always stopped by parse errors on the json config files. Tried writing my own files, then copied internet finds and finally I am down to copying [this sample from Nomad doc](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12):

```
{
    "cniVersion": "0.4.0",
    "name": "mynet",
    "plugins": [
        {
            "type": "macvlan",
            "master": "enp1s0f1",
            "ipam": {
                "type": "dhcp"
            }
        },
        {
            "type": "portmap",
            "capabilities": {
                "portMappings": true
            },
            "snat": true
        }
    ]
}
```
into `cni_config_dir`.

When its there, Nomad does not start with:

```
Dec 05 20:05:02 myhost nomad[1022275]: ==> Loaded configuration from /etc/nomad/server.conf                                                                                            
Dec 05 20:05:02 myhost nomad[1022275]: ==> Starting Nomad agent...                                                                                                                     
Dec 05 20:05:02 myhost nomad[1022275]: ==> Error starting agent: client setup failed: fingerprinting failed: failed to load CNI config file /etc/cni/mynet.conf: error parsing configuration: missing 'type'
...
Dec 05 20:05:02 myhost systemd[1]: nomad-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 20:05:02 myhost systemd[1]: nomad-server.service: Failed with result 'exit-code'.
```

I can see a type field there and its valid json, as `json_reformat` tells me.

Is there any json example thats known to work with this nomad version? Is message just misleading? Or really a parsing error?

### Reproduction steps

1. place above json as `mynet.json` in `cni_config_dir`
2. start nomad server service

**Comment by shoenig** [comment]
Hi @x3nb63 , the name of the file needs to end in `.conflist` rather than `.json`. The use of `.conflist` tells Nomad to parse a list of configurations, whereas `.json` is used to parse just one. 

I notice our [documentation](https://www.nomadproject.io/docs/configuration/client#cni_config_dir) doesn't explicitly point that out, I'll fix that. (We're just following the k8s convention).
