### ISSUE TITLE
Ingress Gateway fails after nomad agent restarts from a long stop.

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#9558]
### Nomad version
0.12.5

### Operating system and Environment details

Linux

### Issue
In a nomad cluster, given the nomad client on a particular node is stopped for some extended period of time, nomad servers will mark any allocations running on that node as lost (which including ingress gateway).
When the client on that node is started again, nomad would stop any previously lost allocations and creating new ones and things recovers from there, except ingress gateway.

Nomad would stop the previously lost Ingress gateway allocation and creating a new one as well, however the new one will not start successfully:
![image](https://user-images.githubusercontent.com/21690857/101436425-5b86a780-38cb-11eb-803a-17aa2832b470.png)
With log message:
```
client.alloc_runner.task_runner.task_hook.envoy_bootstrap: error creating bootstrap configuration for Connect proxy sidecar: alloc_id=b14e4c7e-91b9-0963-cf8f-a2fda9b6524d task=connect-ingress-ingress error="exit status 1" stderr="==> Cannot lookup the ingress-gateway's proxy ID because multiple are registered with the agent
```

Looking at Consul there are indeed two entries for the ingress gateway on that particular node, one for the new allocation and one for the previously lost allocation:
![image](https://user-images.githubusercontent.com/21690857/101436647-cd5ef100-38cb-11eb-8911-3baa0dc1cbcb.png)

What's interesting is this weird state can be recovered by restarting the nomad client on that node again once this happens.

### Reproduction steps

1. have a nomad cluster with consul connect
1. deploy ingress gateway on all nodes (or constraint on one particular node A)
1. stop nomad agent on node A, and wait until node server mark the allocations on that node as lost
1. start nomad agent on node A
1. see the above issue
1. (quickly restart the nomad agent on node A to recover from the state)

### Job file (if appropriate)

https://www.nomadproject.io/docs/job-specification/gateway

### Nomad logs
See in [issue](#issue)

**Comment by tgross** [comment]
Hi @fredwangwang and thanks for opening this issue! This sort of problem with exclusive access to resources on lost clients is why we added the [`stop_after_client_disconnect`](https://www.nomadproject.io/docs/job-specification/group#stop_after_client_disconnect) option. If you add that to the group, it'll cause it to be stopped when the client is lost rather than left running, and when the client is ready to come back it'll have dropped access to those resources and should be able to start the new allocation.

**Comment by fredwangwang** [comment]
Hi @tgross, thanks for replying! Haven't have time to try the option just yet, but some more context here.

We tried the same **Reproduction steps** for a regular Mesh connected job, and that job is able to recover just fine. And in consul there are no duplicate registration entries neither. So for some reason this issue is only happening to ingress gateway as far as I can tell.

I will try the option and let you know the result.

**Comment by fredwangwang** [comment]
Hi @tgross, just tried `stop_after_client_disconnect`, and doesn't look like it helps. The ingress still ended in a crash loop afterwards.
![image](https://user-images.githubusercontent.com/21690857/101934138-63c83680-3b9a-11eb-8dd6-be5b684650ad.png)
A couple reasons possible for why it didn't help:
1. the test I was doing is shutdown the nomad agent on the node, I _think_ this option only helps when the nomad agent is still running but experiencing network issues.
1. again this seems like only specific to ingress gateway, other connect jobs would recover just fine.

**Comment by tgross** [comment]
Sorry to hear that but thanks for the update @fredwangwang. I've marked this as a bug for investigation.

**Comment by fredwangwang** [comment]
closing this ticket, tried to reproduce this issue with newer version of consul/nomad, looks like the issue no longer exists
