### ISSUE TITLE
Adopt raft-autopilot library

### ISSUE THREAD

**Issue by notnoop** [hashicorp/nomad#9570]
Nomad currently directly imports Consul's private autopilot package (`github.com/hashicorp/consul/agent/consul/autopilot`). Last month, Consul extracted autopilot to be its own module to ease adoption in other products: https://github.com/hashicorp/raft-autopilot 

Let's move off our direct dependency on the internal repo in preference to the new module.

**Comment by tgross** [comment]
Note to implementor: probably worth doing https://github.com/hashicorp/nomad/issues/13219 at the same time.

**Comment by shoenig** [comment]
Took a brief look into making the switch; looks like it's going to be a bit more complicated than just renaming imports. In addition to `raft-autopilot` there is also `raft-autopilot-enterprise`, and the features referenced by Nomad in the old Consul autopilot library have been split up between the two.

Still very much want to make this happen - without it Nomad is forced to import consul v1.7 :disappointed:
