### ISSUE TITLE
how to use nomad to submit job to spark

### ISSUE THREAD

**Issue by liuq4360** [hashicorp/nomad#958]
i try to use nomad to submit job to spark, my jar is no hdfs, i use nomad's java diver to submit job, but when the job is submit  i get the following,
nomad run -address=http://bigdata-computing-01-001:4646 java.nomad 
Job registration successful
Approximate next launch time: 2016-03-22 11:49:00 +0800 CST
but i can see anything java pid in the nomad client nodes.
i want to know is there some demo about submit jobs to spark?

**Comment by dadgar** [comment]
Sorry we haven't tried using Spark on Nomad yet so I am not able to help you. I suggest emailing the mailing list to see if a community member has run Spark on Nomad.
