### ISSUE TITLE
Namespaces NOT working at all in the "free" nomad version

### ISSUE THREAD

**Issue by anastazya** [hashicorp/nomad#9605]
this is the message i get : 

" Error looking up namespace: Unexpected response code: 501 (Nomad Enterprise only endpoint) "

This is the Nomad version i run :

" Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43) "

**Comment by cgbaker** [comment]
hi @anastazya , can you provide the output from the following:
```
nomad server members
```

**Comment by anastazya** [comment]
Name                   Address     Port  Status  Leader  Protocol  Build   Datacenter  Region
nomad-consul10.CH      10.0.7.100  4648  alive   false   2         0.12.9  home     RO
nomad-consul11.CH      10.0.7.101  4648  alive   true    2         0.12.9  home      RO
nomad-consul12.CH      10.0.7.102  4648  alive   false   2         0.12.9  home      RO

**Comment by anastazya** [comment]
I'm being stupid, the Nomad service did not restart on update ( maybe a provisioning flaw on my side ). The point is that after a manual restart, the correct version is shown, and namespaces work. 

Name               Address     Port  Status  Leader  Protocol  Build  Datacenter  Region
nomad-consul10.CH  10.0.7.100  4648  alive   false   2         1.0.0  zurich      CH
nomad-consul11.CH  10.0.7.101  4648  alive   true    2         1.0.0  zurich      CH
nomad-consul12.CH  10.0.7.102  4648  alive   false   2         1.0.0  zurich      CH
