### ISSUE TITLE
env block doesn't work with variables containing special characters using HCL2

### ISSUE THREAD

**Issue by exFalso** [hashicorp/nomad#9606]
### Nomad version
v1.0.0
### Operating system and Environment details
Arch Linux, NixOS
### Issue

```
task "elasticsearch" {
  driver = "docker"
  config {
   ...
  }
  env {
    "network.host" = "0.0.0.0"
  }
}
```
gives:
```
Invalid argument name; Argument names must not be quoted.
```
```
task "elasticsearch" {
  driver = "docker"
  config {
   ...
  }
  env = {
    "network.host" = "0.0.0.0"
  }
}
```
also doesn't work, gives
```
Unsupported argument; An argument named "env" is not expected here. Did you mean to define a block of type "env"?
```

In fact, the example given in the documentation here https://www.nomadproject.io/docs/job-specification/env
```
env {
  "key" = "1.4"
}
```
also doesn't work. So it seems currently there is no way to specify environment variables with special characters in them!

### Reproduction steps
See above

**Comment by dvusboy** [comment]
I don't know about "key", but you cannot have "network.host" as a variable name. You should stick to normal shell variable naming convention.

**Comment by exFalso** [comment]
Well by definition there is no restriction on environment name characters besides `=` and NUL: https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

But also, the choice is not up to me: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file

**Comment by exFalso** [comment]
Just noting that this is a blocker for us wrt upgrading (and I imagine it will be for other users as well) and we reverted to 0.12 until fixed

**Comment by mahermali** [comment]
I had the same issue with elastic search variables taking the form w1.w2
What i have done to run the job:
nomad job run -hcl1 job.nomad

**Comment by Cybernisk** [comment]
Nomad version: 1.0.1
OS: CentOS 7

Same issue with Elastic Search
```
      env {
          "discovery.type" = "single-node"          
      }
```
or 
```
      env {
          discovery.type = "single-node"          
      }
```
or 
```
      env = {
          "discovery.type" = "single-node"          
      }

```
Nothing works with the same messages as in the first comment by @exFalso

**Comment by eihli** [comment]
> Just noting that this is a blocker for us wrt upgrading (and I imagine it will be for other users as well) and we reverted to 0.12 until fixed

Can you still upgrade and use the `-hcl1` argument with `nomad run`? 

This is the error message I'm getting.

```
Error getting job struct: Failed to parse using HCL 2. Use the HCL 1 parser with `nomad run -hcl1`, or address the following issues:
sample.hcl:16,9-12: Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```

So I'm simply using `nomad run -hcl1` with Nomad version 1.0.1.

If anyone wants to take this further than I did in terms of shipping a fix, here's what I see so far.

HCL2 uses a Ragel state machine to scan tokens.

https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/generate.go
https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/unicode2ragel.rb

That ruby script creates this file: https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/unicode_derived.rl

The "Identifier" tokens (the tokens that make up the thing to the left of the `=` sign) are made up of `ID_Start` and `ID_Continue` tokens from the http://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p1949r3.html#identifiers which is from the "Unicode Standard Annex 31. (Some standards body that defined a standard for C++ identifiers?)

So HCL2 identifiers are being treated like C++ identifiers. Should they be? Can that ruby script be modified to just add the unicode `FULL STOP` character at the end of the `ID_Continue` list?

**Comment by exFalso** [comment]
I think the "right" solution to this is to not have `env` as a block, but rather as a map allowing
```
env = {
  "something" = "bla"
}
```
This way there's no need to change the hcl syntax, but it is a breaking config change.

> Can you still upgrade and use the -hcl1 argument with nomad run?

Yeah could do that thanks, just need to change some deployment code

**Comment by sofixa** [comment]
@exFalso that just results in:

```
Error getting job struct: Error parsing job file from worker.nomad:
worker.nomad:113,7-10: Unsupported argument; An argument named "env" is not expected here. Did you mean to define a block of type "env"?
```

**Comment by exFalso** [comment]
Yes, what I meant is the "right" fix from the nomad team imho would be to define `env` as a map rather than a block (basically we would stop getting that error). Defining it as a block means that the keys are subject to identifier parsing restrictions.

**Comment by colindunn** [comment]
In the meantime I'm using this because it's not many of my jobs that have an issue:

```hcl
      template {
        destination = "local/env"
        env         = true
        data        = <<-EOH
        discovery.type="single-node"
        EOH
      }
```
