### ISSUE TITLE
artifact.destination does not support interpolation 

### ISSUE THREAD

**Issue by valenvb** [hashicorp/nomad#9609]
### Nomad version
`Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43)`

### Operating system and Environment details
CentOS 7

### Issue
Attempting to use `${NOMAD_SECRETS_DIR}`, `${NOMAD_TASK_DIR}`, or `${NOMAD_ALLOC_DIR}` in `artifact.destination` results in the literal value in `local/` (i.e. `local/${NOMAD_SECRETS_DIR}/file` ). These do work in `template.destination`.

### Reproduction steps
Deploy a job with a stanza as below

### Job file (if appropriate)
```
...
 artifact {
        source      = "https://url/to/my/file"
        destination = "${NOMAD_SECRETS_DIR}/file"
        mode = "file"
}
...
```

Seems like perhaps the fix applied to `template` (mentioned [here](https://www.nomadproject.io/docs/upgrade/upgrade-specific#artifact-and-template-paths)) didn't get applied to `artifact`?

**Comment by tgross** [comment]
Hi @valenvb! Fortunately (or maybe unfortunately?) this isn't a regression but an existing limitation of the artifact block. See the docs: https://www.nomadproject.io/docs/job-specification/artifact#destination

> destination (string: "local/") - Specifies the directory path to download the artifact, relative to the root of the task's working directory. If omitted, the default value is to place the artifact in local/. The destination is treated as a directory unless mode is set to file. Source files will be downloaded into that directory path. For more details on how the destination interacts with task drivers, see the Filesystem internals documentation. Interpolation is not yet supported.

**Comment by valenvb** [comment]
Ah, missed that one in my search for a dupe, sorry about that. Might is suggest updating the documentation here: https://www.nomadproject.io/docs/upgrade/upgrade-specific#artifact-and-template-paths (in the *Warning* section ) to indicate that this was implemented in `template` but _not_ in `artifact`? This docs discrepancy is what misled me to believing it was now supported.
