### ISSUE TITLE
Injecting extra variables for template stanzas

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad#9616]
### Nomad version

Nomad v0.11.3

### Operating system and Environment details

Ubuntu 18.04

### Feature Request

It would be great to be able to inject a set of variables into a specific template stanza. This would enable end-users to use the same template but vary the output based on an extra set of variables.

Our use case is running nginx inside of Nomad, where the templates differ very little for various domains other than the domain it covers and a few knobs we turn on/off (auth, proxy settings, etc.). If we could modify those knobs within the job stanza itself, that would make it much easier for us to include all the config we need within a single template and then modify what that template generates within individual template stanzas.

**Comment by cgbaker** [comment]
hi @josegonzalez , can you give a specific example of something that you're unable to do today? it seems like `Meta` should be able to handle a good number of cases. and the new HCL2 support in Nomad 1.0.0 can do even more, directly in the jobspec parsing.

**Comment by josegonzalez** [comment]
I have a single nginx template.

```
server {
  listen {{ env "PORT" }};
  server_name {{ env "DOMAIN" }};

  location / {
    proxy_pass http://{{ env "UPSTREAM" }};
  }
}
```

Currently, we need to duplicate this template, hardcode the DOMAIN/UPSTREAM, and specify the specific template source in a `template` stanza for each server_name we want to listen to. Rather than have 10 of these, each with a new template:

```
      template {
        destination   = "/local/nginx/sites-enabled/example.com.conf"
        source        = "example.com.ctmpl"
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
```

I'd like to use the same template and add an `injected_env` key or something that would contain other variables to inject into the specific `template` stanza. This would allow me to use the same template file N times vs respecifying a whole template each time.

**Comment by cgbaker** [comment]
One approach for this may be HCL2 [dynamic blocks](https://www.nomadproject.io/docs/job-specification/hcl2/expressions#dynamic-blocks):
```hcl
locals {
  sites = [{
    domain = "example.com",
    port = "80",
    upstream = "example_com_upstream",
  },{
    domain = "test.org",
    port = "8080",
    upstream = "test_org_upstream",
  }]
}
job "nginx" {
  type = "service"
  task "nginx" {
    dynamic "template" {
      for_each = local.sites
      content {
        change_mode = "signal"
        change_signal = "SIGHUP"
        destination = "/local/nginx/sites-enabled/${template.value.domain}.conf}"
        source = <<EOF
server {
  listen ${template.value.port};
  server_name ${template.value.domain};

  location / {
    proxy_pass http://${template.value.upstream};
  }
}
EOF
      }
    }
  }
}
```

The result is the following templates in the rendered JSON:
```json
[
  {
    "SourcePath": "server {\n  listen 80;\n  server_name example.com;\n\n  location / {\n    proxy_pass http://example_com_upstream;\n  }\n}\n",
    "DestPath": "/local/nginx/sites-enabled/example.com.conf}",
    "EmbeddedTmpl": null,
    "ChangeMode": "signal",
    "ChangeSignal": "SIGHUP",
    "Splay": 5000000000,
    "Perms": "0644",
    "LeftDelim": null,
    "RightDelim": null,
    "Envvars": null,
    "VaultGrace": null
  },
  {
    "SourcePath": "server {\n  listen 8080;\n  server_name test.org;\n\n  location / {\n    proxy_pass http://test_org_upstream;\n  }\n}\n",
    "DestPath": "/local/nginx/sites-enabled/test.org.conf}",
    "EmbeddedTmpl": null,
    "ChangeMode": "signal",
    "ChangeSignal": "SIGHUP",
    "Splay": 5000000000,
    "Perms": "0644",
    "LeftDelim": null,
    "RightDelim": null,
    "Envvars": null,
    "VaultGrace": null
  }
]
```

Note, this does all of the interpolation at submit time using HCL2; if you want to include some consul-template interpolation at runtime on the client, the [heredoc](https://www.nomadproject.io/docs/job-specification/hcl2/expressions#string-literals) can include consul-template expressions using `$${`.

**Comment by angrycub** [comment]
So I'm reading this from a slightly different angle and hearing that you want to use a constant template artifact fetched from a URL and given job values have it render differently. 

You can use the `env` stanza to supply them to the task scope before the template runs. For example:
```hcl
job ... {
  group ... {
    task ... {
      env {
        PORT     = 12345 
        DOMAIN   = "foo.com"
        UPSTREAM = "10.10.10.10:8080"
      }
    }
  }
}
```

<details><summary> :mag: Here's a runnable example job</summary>

```hcl
job "env-template.nomad" {
  datacenters = ["dc1"]

  group "test" {
    task "test" {
      driver = "docker"

      config {
        image   = "alpine:latest"
        command = "sh"
        args    = [
          "-c",
          "cat /local/template.out; while true; do sleep 300; done"
        ]
      }

      artifact {
        source      = "https://gist.githubusercontent.com/angrycub/74bf941c238fcc19a8b252d26bb40f77/raw/544f41e7607dbf692793a733087933fdcd6482c7/basic-nginx.ctmpl"
        destination = "local/basic-nginx.ctmpl"
        mode        = "file"
      }

      template {
        source = "local/basic-nginx.ctmpl"
        destination = "local/template.out"
      }

      env {
        PORT     = 12345 
        DOMAIN   = "foo.com"
        UPSTREAM = "10.10.10.10:8080"
      }
    }
  }
}
```
This job templates a file into a known place on an alpine container, `cat`s it out and then goes into a sleep loop.
Fetching  the logs for a running allocation will show the env values in place. 
Stop the job when you're done. 

</details>

**Comment by josegonzalez** [comment]
Specifying variables within an env stanza does not help at all. We invoke the same template file 100 times, each with a slightly different permutation of config. The `env` stanza is global to the task, and not per-template.

**Comment by josegonzalez** [comment]
The method suggested by @cgbaker is close enough that it works for me. Thanks @cgbaker for the idea, it is much appreciated.
