### ISSUE TITLE
HCL2 variables not parsed from environment

### ISSUE THREAD

**Issue by valenvb** [hashicorp/nomad#9622]
### Nomad version

`Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43)`

### Operating system and Environment details
Ubuntu 18.04, tested in `zsh` `5.4.2`  and `bash` `4.4.20`

### Issue
Using environment variables to define HCL2 variables (as described in [the docs](https://www.nomadproject.io/docs/job-specification/hcl2/variables#environment-variables)) does not work.

Running a job results in the following output:
```
$ nomad run test.nomad 
Error getting job struct: Error parsing job file from test.nomad:
<nil>: Unset variable "text"; A used variable must be set or have a default value; see https://packer.io/docs/configuration/from-1.5/syntax for details.
```

### Reproduction steps
1. Create a jobspec as below. 
2. set environment variable as described in [the docs](https://www.nomadproject.io/docs/job-specification/hcl2/variables#environment-variables) `$ export NOMAD_VAR_text="hello"`
3. Run job: `$ nomad run test.nomad`

inline-ing the variable also does not work: `$ NOMAD_VAR_text=hello nomad run test.nomad`

### Job file (if appropriate)

```
variable "text" {
  type  = string
}

job "repro" {
  datacenters = ["dc1"]
  type = "batch"
  group "repro" {

    task "a" {
      driver = "docker"
      config {
        image = "alpine:3"
        command = "echo"
        args = [ var.text ]
      }
    }
  }
}
```

**Comment by notnoop** [comment]
Thanks @valenvb .  That was a 🤦 bug.  I've fixed the issue for 1.0.1, and removed the environment variables docs.  I'm very sorry we didn't catch this earlier, but aiming to have a release out very soon.
