### ISSUE TITLE
Nomad UI Problem After Updating to v1.0.0

### ISSUE THREAD

**Issue by mahermali** [hashicorp/nomad#9628]
### Nomad version
Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43)

### Operating system and Environment details
Red Hat Enterprise Linux Server release 7.7 (Maipo)

### Issue
After upadting to Nomad latest version, we can't access Jobs Tab anymore
![Screenshot from 2020-12-14 10-11-52](https://user-images.githubusercontent.com/1131067/102098161-db919d80-3df4-11eb-8ef7-685cdb369f39.png)

### Reproduction steps
Perform update to nomad 1.0.0

Is it related to including the namespaces in the opensource project?
We can still see the job from the command line. with nomad job status

**Comment by mahermali** [comment]
It turned out some cluster nodes are not updated to V1.0.0 which caused this issue,
Thanks

**Comment by tgross** [comment]
Thanks for the update @mahermali! (Also, _whew_ 😁 )
