### ISSUE TITLE
[Feature Request] Show Allocation Index Under Job Status?

### ISSUE THREAD

**Issue by herter4171** [hashicorp/nomad#9642]
Hello,

I have a user running a single job with O(10) allocations using the Docker driver and networking in host mode.  It's an MPI application, so all non-zero allocations essentially do a `tail -f /dev/null`, and allocation zero runs the show via `mpiexec`.  My reason for writing is that it can be tricky to track down allocation zero with so many of them floating around.  Would it be possible to have `nomad job status` have a column like `Index` under the `Allocations` section?

Thanks.

**Comment by tgross** [comment]
@herter4171 it might be possible to do this, but I'm a little concerned about this:

> and allocation zero runs the show via `mpiexec`.

It looks like you're using the allocation index as a lock, which you can only really do within a single version of the job. Take a look at the [runtime environment docs](https://www.nomadproject.io/docs/runtime/environment):

> Allocation index; useful to distinguish instances of task groups. From 0 to (count - 1). The index is unique within a given version of a job, but canaries or failed tasks in a deployment may reuse the index.

**Comment by herter4171** [comment]
@tgross, yeah, that's basically our use.  These are monolith jobs with one allocation per Nomad client, and all communication happens within the job.  Is there a more suited approach than using the allocation index?  We have to call `mpiexec` once  some way or another.

**Comment by tgross** [comment]
I'm not super-familiar with `mpiexec`, but does it require that exactly one instance of it is running? If so, it looks like you've got another case of this request https://github.com/hashicorp/nomad/issues/6367, where coordinating a lock across jobs would be helpful. We've provided some suggestions there for workarounds in the meanwhile.

Another way you can do this is to have the jobs try to obtain a lock via Consul (or Zookeeper, or whatever) as part of their startup. Whichever wins the lock runs your `mpiexec`, and when that allocation stops it drops the lock. You'll want to make sure you have a TTL on that to account for failed tasks.

**Comment by herter4171** [comment]
Yep, that's the idea.  Honestly, I hate to sound immune to good advice, but we haven't had any issue using the allocation index to get a lock of sorts.  Although I am using Consul to provide the service mesh, I'll admit that it's a bit of a black box.  Our images for this use case have the `pip3` package `python-consul` (and `python-nomad` in case it matters).  Is there a route through there to have an alloc grab a lock?  I'm just a bit out of my depth for the moment, and the docs for the `consul lock` don't seem to relate.

**Comment by tgross** [comment]
> Honestly, I hate to sound immune to good advice, but we haven't had any issue using the allocation index to get a lock of sorts.

That's totally fair! It may be that the update strategy you have makes it unlikely that you run into any problems there.

> Our images for this use case have the `pip3` package `python-consul` (and `python-nomad` in case it matters). Is there a route through there to have an alloc grab a lock?

Should be doable. At a previous employer I worked up a pattern for this using `python-consul` to obtain the lock for a database primary in [autopilotpattern/mysql](https://github.com/autopilotpattern/mysql). To be honest, the MySQL bits of that repo are actually kind of buggy 😊 but the locking logic is pretty solid.

* Create a [Consul session](https://www.consul.io/docs/dynamic-app-config/sessions) with a unique ID for the job (can just be the job ID): [discovery.py#L78-L82](https://github.com/autopilotpattern/mysql/blob/master/bin/manager/discovery.py#L78-L82)
* Have every instance attempt to obtain the lock [discovery.py#L92-L94](https://github.com/autopilotpattern/mysql/blob/master/bin/manager/discovery.py#L92-L94)
* Whichever instance won the lock periodically renews the session [discovery.py#L85-L89](https://github.com/autopilotpattern/mysql/blob/master/bin/manager/discovery.py#L85-L89)

I'd love for us to have a Learn Guide around processes like that... I'll see if I can convince the folks in charge of that if they'll let me contribute one 😀

**Comment by lgfa29** [comment]
Closing this one if favour of #15894. With a `-json` output for `nomad job status` you will be able to pick-and-choose with values are relevant to you. Thank you for the proposal @herter4171!
