### ISSUE TITLE
[Feature Request] Docker image checksum verification

### ISSUE THREAD

**Issue by bert2002** [hashicorp/nomad#9644]
Hi,
is it possible to verify the integrity of a container in Nomad? I could not find any option (only artifact has it) and propose that in the configuration we could provide the checksum of the manifest file to make sure that we pull exactly the image that we want. This prevents that we deploy a different container which could have overwritten the original container. 

Example:
```
group "application" {

  task "app" {
    driver = "docker"

    config {
      image = "app:1.2.3"
      checksum = "sha256:8ab423efe33030d80b4fc5580efbc7e710d540fdf8e68c2286aa99f64684ba4a"
    }
  }
}
```
Nomad would download the image and verify the checksum from the configuration and the image itself. If it does not match it will fail.

I think this will improve the security of the deployments.

bert

**Comment by tgross** [comment]
Hi @bert2002! The image name should accept a checksum like: `app:1.2.3@sha256:8ab423efe33030d80b4fc5580efbc7e710d540fdf8e68c2286aa99f64684ba4a`. It looks like there may be a bug around extraneous re-downloads for that: https://github.com/hashicorp/nomad/issues/9619 but that still needs verification.

**Comment by bert2002** [comment]
Hi @tgross, you are right. This is working correctly. I am not sure abour #9619, but for me it always downloads the image (even when it is not latest). I need to pre download the image into the registry if I dont want it to be downloaded all the time when I restart it, but I guess thats another issue.

I will close this as working from your suggestions.
