### ISSUE TITLE
Topology broken in 1.0.1

### ISSUE THREAD

**Issue by analytically** [hashicorp/nomad#9658]
After upgrading to Nomad 1.0.1 from 1.0.0, the Topology endpoint stopped working.

![image](https://user-images.githubusercontent.com/254434/102475742-0704ca00-4039-11eb-8fe7-550c3fc5b125.png)

Error in the console:
![image](https://user-images.githubusercontent.com/254434/102475789-16841300-4039-11eb-83a8-11f4d1200eec.png)

**Comment by analytically** [comment]
@DingoEatingFuzz

**Comment by tgross** [comment]
Same symptoms as: https://github.com/hashicorp/nomad/issues/9617

**Comment by DingoEatingFuzz** [comment]
Yeah, there's not much to be done about an allocation with no node, but the UI can at least handle that condition gracefully. Thanks for the report and for the triage.
