### ISSUE TITLE
volumes are not enabled; cannot mount host paths error on deployment

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#9666]
### Nomad version
Nomad 1.0.1

### Operating system and Environment details
PhotonOS

### Issue
After upgrading from Nomad 0.12.x and prior, we are now starting to see this message in our pipeline.  
Failed to create container configuration for image "<redacted>@sha256:b48176655371c24aa63cab729f561a6fba8b2c3ed08c1d7283c2e841f39c2d1e" ("sha256:3f56d7f81ea694a4a923a74ed9ff5cd113f382d9c380d4572dc4b1dbaf6769c9"): volumes are not enabled; cannot mount host paths: "/var/run/docker.sock:/var/run/docker.sock:ro"

Not sure if we missed a breaking change in the changelog but here's the relevant section of our job that seems to be causing this.

```HCL
task "postgres-logging-task" {
      driver = "docker"

      env {
        IP_ADDRESS         = "${attr.unique.network.ip-address}"
        HOSTNAME           = "${attr.unique.hostname}"
        matchContainerName = "postgres-task-${NOMAD_ALLOC_ID}|postgres-telegraf-task-${NOMAD_ALLOC_ID}"
        excludeLines       = "['.*incomplete startup packet.*', '.*INFO: no action.*','.*INFO: does not have lock.*','.*INFO: Lock owner:.*','.*INFO: not proceeding with the restart:.*','.*WARNING: Connection pool is full, discarding connection:.*','.*database.*does not exist.*']"
      }

      config {
        image = "redacted@sha256:b48176655371c24aa63cab729f561a6fba8b2c3ed08c1d7283c2e841f39c2d1e"
        cpu_hard_limit = true
        volumes = [
          "/var/run/docker.sock:/var/run/docker.sock:ro",
          "/var/lib/docker/containers:/var/lib/docker/containers"
        ]
      }
      resources {
        cpu    = "64"    # Mhz
        memory = "32" # Mb
      }
    }
  ```

**Comment by idrennanvmware** [comment]
Little more digging - if a container/allocation was running prior this does not surface, but I restarted a different allocation with the same logging task and then it showed the same host volume mount error

**Comment by 42wim** [comment]
See https://www.nomadproject.io/docs/upgrade/upgrade-specific#docker-volume-mounts

**Comment by idrennanvmware** [comment]
Rats.....we missed this one.  Ty
