### ISSUE TITLE
Group network ports are registered as address port 0 in Consul?

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#9704]
### Nomad version
Nomad v1.0.1+ent (1eceba91daaa478a1a06334647f04ae8871c0f7c)

### Issue
Jobs using the new group level network and service stanzas are registered with port `0` in Consul.

### Reproduction steps
When I run the jobfile below the "redis-example" service is registered in Consul with **service address** 
`1.2.3.4:0` which breaks stuff like fabiolb and probably others.

The **service check** in Consul however is registered as  `1.2.3.4:29374` and thus works correctly.

The Allocation page for this job in the Nomad UI also shows the correct information under the _Host Address_ and _Mapped Ports_ fields. 

The CLI also yields the correct result ;
```
...
Allocation Addresses
Label   Dynamic  Address
*redis  yes      1.2.3.4:29374 -> 6379
...
```

### Job file (if appropriate)

```
job "example" {
  datacenters = ["dc1"]
            
  group "cache" {

   # define network options
    network {
      dns {
        servers = ["10.10.10.10"]
      }

      port "redis" {
        to  = 6379
      }
    }

     # define and register service & healthcheck
     service {
       name = "redis-example"
       check {
         name     = "redis"
         port     = "redis"
         type     = "tcp"
         interval = "10s"
         timeout  = "2s"
       }
     }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
        ports = ["redis"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}

```

**Comment by apollo13** [comment]
Shouldn't you specify "port = redis" on the service so the service knows which port to announce? (then you can also drop the port from the check I think)

**Comment by henrikjohansen** [comment]
@apollo13 This does indeed solve the issue :+1: Not sure why I have overlooked this. :man_shrugging:
