### ISSUE TITLE
Nomad agent panic

### ISSUE THREAD

**Issue by liemle3893** [hashicorp/nomad#9708]
### Nomad version
Output from `nomad version`
Nomad v0.11.7 (ad839926a7b4b763d7ca2f3a2bdc04079e8891aa)

### Issue
Nomad agent panic

### Reproduction steps
Cannot reproduce ATM. Some agents got panic some does not.

### Nomad Client logs (if appropriate)

```
panic: interface conversion: interface {} is nil, not time.Time
goroutine 987239 [running]:
github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus.(*PrometheusSink).Collect.func2(0x2844e60, 0xc001dc0320, 0x2e949a0, 0xc005c58500, 0x1)
github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus/prometheus.go:86 +0x1d4
sync.(*Map).Range(0xc00022a868, 0xc000d15e90)
sync/map.go:333 +0x1c5
github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus.(*PrometheusSink).Collect(0xc00022a840, 0xc003e0c1e0)
github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus/prometheus.go:84 +0x154
github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x19d
created by github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus/registry.go:526 +0xe36
```

The log show that it's panic at [this](https://github.com/hashicorp/nomad/blob/69d49c17ae51ec6f11df243b068d7739168591e3/vendor/github.com/armon/go-metrics/prometheus/prometheus.go#L84) line.

This issue was fixed due to https://github.com/armon/go-metrics/tree/v0.3.4

This may occur on newer version (0.11.8).

Work around: Use our build with updated version of armon/go-metrics.

**Comment by jrasell** [comment]
Hi @liemle3893. The go-metrics dependancy was update within #8637 and released as part of v0.12.2 which resolves the issue you are seeing as it includes the fixed version of the lib you mention. I would therefore suggest upgrading to use a Nomad version which includes this fix if possible.
