### ISSUE TITLE
Deprecated Docker port_map syntax

### ISSUE THREAD

**Issue by ccakes** [hashicorp/nomad#9710]
### Nomad version
1.0.1

### Issue
This isn't a bug, more a documentation issue.

https://www.nomadproject.io/docs/drivers/docker#deprecated-port_map-syntax

This isn't mentioned at all in the changelog as a breaking change which it is. After upgrading (in my case from 0.11.x -> 1.0.1) existing tasks continued running fine but then upgrading those tasks resulted in an error like this

```
Failed to create container configuration for image "ccakes/nomad-pgsql-patroni:13.1-1.gis" ("sha256:6da0272abfabfc9344f7e6f7bccb8d88d3e50459bf9f72cfa5adbf0b41e0f0e4"): 'port_map' cannot map group network ports, use 'ports' instead
```

While I probably should have checked the docs, the changelog does contain sections for explicitly calling out breaking changes so it'd be nice to have it listed there as well 😉 

### Reproduction steps
Run up a job with Docker that exposes ports on 0.11.x then upgrade to 1.0.x

**Comment by kaspergrubbe** [comment]
I was just hit by this (again, because I am forgetful) it would be nice if it was mentioned in the docs, also, are there any way to discover this mistake early by running `nomad job plan`?

**Comment by tgross** [comment]
Updated in the docs, which will get published the next time we push to stable website.
