### ISSUE TITLE
E2E: TestExecBasicResponses failing on nightly

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#9723]
```
=== RUN   TestE2E/Nomad_exec
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_basic
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_streaming
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_stty_check
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_stdin_passing
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_children_processes
      exec.go:99:
            Error Trace:  exec.go:99
            Error:        Not equal:
                          expected: "from main\nfrom background\n"
                          actual  : "from main\n"
  
                          Diff:
                          --- Expected
                          +++ Actual
                          @@ -1,3 +1,2 @@
                           from main
                          -from background
  
            Test:         TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/notty:_children_processes
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/tty:_basic
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/tty:_streaming
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/tty:_stty_check
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/tty:_stdin_passing
  === RUN   TestE2E/Nomad_exec/*nomadexec.NomadExecE2ETest_(docker)/TestExecBasicResponses/tty:_children_processes
```

First failed build is [build-1309](https://ci.hashicorp.engineering/buildConfiguration/Nomad_E2eTestRunner/222962) which is very strange because that only includes https://github.com/hashicorp/nomad/commit/7a5ac679d24b262d63038e42a6ded25bf740adba and https://github.com/hashicorp/nomad/commit/b4f7e113daae5ae4cadd2fecd83680407f9234b5 which are docs changes! Unfortunately there were a few builds before that where the exec flaked-out with EOF, so that makes it harder to narrow down where the bug was introduced.

**Comment by tgross** [comment]
This is no longer failing on nightly, but it's not super clear to me what changed that fixes it. I'm inclined to close this but I suspect there's a timing bug in the test cases in the [`exec_testing.go`](https://github.com/hashicorp/nomad/blob/master/plugins/drivers/testutils/exec_testing.go) file that this E2E test pulls in. @krishicks I know you were looking at this so I'll leave it up to you as to whether we should just close this and re-open if we see it again.

**Comment by krishicks** [comment]
:+1: on closing it for now, but let's jump on it next time to see if we can figure it out while it's still failing.

**Comment by tgross** [comment]
Oops, forgot to follow-up and close this 😀
