### ISSUE TITLE
Ability to set proxy resource configurations at a cluster or global level

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#9749]
This is a feature request for the Nomad team to consider (or tell us why its a bad idea) :)

**Scenario**
As we move more and more services to mesh we are seeing a significant increase in the amount of resources required to run the various tasks. Often, our tasks are 128 CPU or less but due to the envoy defaults of 250 for just the sidecar this stacks up quickly and we're needing more resources to run the sidecar than the main task itself.

Very often, at least in our scenarios, these tasks need far less resources than the default and while we can customize them at the job level the impact is that we have to ask every service team to reduce their resources (and this can be a large number of teams and changes from the default .

if we had the ability to set this at a cluster level we could start with a lower default for all sidecars for connect.   We would still want to be able to override the default at the job level, of course, but this would be as teams needed more resources vs the inverse that we have today with over-provisioning.

Thanks for the consideration!
Ian

**Comment by tgross** [comment]
@idrennanvmware I hear your pain on this for sure. But is this different from https://github.com/hashicorp/nomad/issues/9161 or more just a special case of that?

**Comment by idrennanvmware** [comment]
I went back and read through that and you're right I think it's just a special case of it - I can add this use case to that ticket and close this one 👍

**Comment by tgross** [comment]
Cool, thanks! Closing as dupe.
