### ISSUE TITLE
demo/vagrant sharing consul server across nomad agents, against the doc

### ISSUE THREAD

**Issue by chulkilee** [hashicorp/nomad#9756]
Based on the changes of #4288 - 1) all nomad agents (server and client) "should" talk to consul (client) agent, not client server and 2) it is required not to share consul agents across nomad agents.

https://www.nomadproject.io/docs/configuration/consul

> An important requirement is that each Nomad agent talks to a unique Consul agent. Nomad agents should be configured to talk to Consul agents and not Consul servers. If you are observing flapping services, you may have multiple Nomad agents talking to the same Consul agent. As such avoid configuring Nomad to talk to Consul via DNS such as consul.service.consul

However, the examples in demo uses consul dev cluster (which runs client *and* server in one agent) - and all nomad agents (server1, client1, client2) talk to the dev consul.

If talking to consul (client) agent, not directly to consul server, is a *recommendation* not hard requirement (per best practice of using consul) - then the nomad doc should clarify that.

If sharing a consule agent across any types of nomad agents is ...

- acceptable (e.g. could be bad for performance, but it's not breaking any features anymore) => then update the doc
- not acceptable (e.g. it may result in flipping services) => fix Vagrant demo to launch multiple consul agents locally

**Comment by tgross** [comment]
Hi @chulkilee! Looks like that demo is stale. Thanks for pointing it out!

**Comment by chulkilee** [comment]
> An important requirement is that each Nomad agent talks to a unique Consul agent. Nomad agents should be configured to talk to Consul agents and not Consul servers. If you are observing flapping services, you may have multiple Nomad agents talking to the same Consul agent. As such avoid configuring Nomad to talk to Consul via DNS such as consul.service.consul

Is it actually correct? #4288 does not have any background information 😢  I don't know how nomad-consul works in details.. but here are my guess:

- A nomad agent MUST NOT switch a consul agent it is talking to, since otherwise different consul agents try to register the same service. (This is by the design of consul) I don't think sharing a consul agent by multiple nomad agent is a problem.
- A nomad agent only needs to consume Consul API - which is served by both consul server and consul client (Note: there is no "pure" consul server since consul server also serves APIs of consul clients) It is "better" to use local consul client agent instead of talking to remote consul server... but talking to "consul client" is not the hard requirement. 

If my guess is correct, then we should fix the doc, not vagrant.

Any thoughts?

**Comment by tgross** [comment]
@chulkilee the design constraint here really comes from Consul: any registration of a service (including Nomad itself) should be made to the Consul agent running on that host, otherwise Consul will return incorrect values on the [Agent API](https://www.consul.io/api-docs/agent), which will result in flapping services. The documentation is correct.

**Comment by tgross** [comment]
Actually, the more I'm thinking of it the more I'm thinking this is a non-issue for the demo environment. That's intended to provide a demo, not a production environment. @chulkilee if you have a specific thing in mind that's not working in the demo environment because of this Consul topology, we can fix that. But otherwise I'm inclined to just close this as a wontfix: production and demos just aren't the same.

**Comment by chulkilee** [comment]
@tgross then demo vagrant is okay! :)

However the description of the requirement seems incorrect since it mentions unique consul client agents, not local consul agent (technically consul server at the same host is okay) which is actual requirement.

> An important requirement is that each Nomad agent talks to a unique Consul agent. Nomad agents should be configured to talk to Consul agents and not Consul servers.

Probably it should be something like this:

> By the design of Consul, each Nomad agent must talk to its local Consul agent, not a remote Consul agent.

Feel free to close this issue - if the above suggestion makes sense please make that change or I can make a PR. Thanks!

**Comment by tgross** [comment]
_Technically_ that's not a requirement; you could have the Consul agent on a separate machine entirely so long as no other Nomad agent is talking to it. But that's an impractical configuration though and no one would ever do that. So if you want to make a PR, I'd change it to:

> An important requirement is that each Nomad agent talks to a unique Consul agent (typically on the same host). Nomad agents should be configured to talk to Consul agents and not Consul servers.
