### ISSUE TITLE
Updating service in consul is not working

### ISSUE THREAD

**Issue by SeaLife** [hashicorp/nomad#9763]
Hey guys,

my nomad cluster is not updating the service in consul correctly. 

I found a similar issue here: #9358. 

The problem is probably, that the labels for my ports are not found, but as far as i know, i created my nomad job file correctly:

```hcl
job "traefik" {
  datacenters = [ "dc1" ]

  type = "system"

  group "container" {
    count = 1

    update {
      max_parallel = 1
      min_healthy_time = "30s"
      healthy_deadline = "5m"

      auto_revert = true
    }

    network {
      port "http" {
        to = 80
        static = 80
      }
    }

    restart {
      attempts = 5
      delay = "15s"
    }

    task "container" {
      driver = "docker"

      service {
        name = "traefik"
        port = "http"

        tags = [ "traefik.enabled=true" ]

        meta {
          type = "lb"
        }
      }

      config {
        image = "traefik"

        ports = ["http"]
      }

      env {
        TRAEFIK_API = "true"
        TRAEFIK_API_INSECURE = "true"

        TRAEFIK_ENTRYPOINTS_HTTP    = ":80"
        TRAEFIK_ENTRYPOINTS_TRAEFIK = ":8080"

        TRAEFIK_PROVIDERS_CONSULCATALOG = "true"
        TRAEFIK_PROVIDERS_CONSULCATALOG_ENDPOINT_ADDRESS = "${attr.unique.network.ip-address}:8500"
      }

      resources {
        cpu    = 200
        memory = 64
      }

    }
  }
}
```

Log output:
```
2021-01-09T12:54:06.418Z [ERROR] client.alloc_runner.task_runner: update hook failed: alloc_id=b0456987-b8d1-0d38-f3e8-15c6d99f32ea task=container name=consul_services error="unable to get address for service "traefik": invalid port "http": port label not found"
```

I've defined the port with the label "http" and im using this label in the service stanza, but still, its not working 🤔 

Version Outputs:
```
root@raspberrypi4:~/jobs# consul -v
Consul v1.9.1
Revision ca5c38943
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

```
root@raspberrypi4:~/jobs# nomad -v
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)
```

Regards
SeaLife

**Comment by tgross** [comment]
Hi @SeaLife! I suspect this is another case of https://github.com/hashicorp/nomad/issues/9360 and https://github.com/hashicorp/nomad/issues/9735, which was fixed in https://github.com/hashicorp/nomad/pull/9736. I'm going to tag in my colleague @drewbailey who authored that PR to verify that. If so, the fix for this will ship in Nomad 1.0.2

**Comment by drewbailey** [comment]
Hey @SeaLife, @tgross is correct, this was fixed in #9736. 

In the mean time, you can temporarily avoid the problem by including something like an environment variable change to force the scheduler to not update the allocations in place.

**Comment by SeaLife** [comment]
Hey! Thanks for helping me out! :)
Is there a due-date for 1.0.2 or a nightly-build or something like that i can use?

Regards
SeaLife

**Comment by tgross** [comment]
We don't have a Nomad 1.0.2 date set. We don't currently ship nightly builds (although I think it's been discussed) but with a golang 1.15 environment set up you can build via:

```
make deps
make generate-all
make dev
```

and get the same build we use in our nightly E2E testing.
