### ISSUE TITLE
Weird node sizing in nomad topology view

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#9769]
On 1.0.1 I see the following in the nomad topology:
![image](https://user-images.githubusercontent.com/81547/104214029-42779600-5437-11eb-8581-c585618d0d2b.png)

Is there a reason why the client nomad03 is smaller than the others?

Also I do not see the blue lines after clicking on an allocation:
![image](https://user-images.githubusercontent.com/81547/104214309-8b2f4f00-5437-11eb-8d6f-29400af74dc7.png)

Interestingly enough they do show up after hitting F12 to open developer tools:
![image](https://user-images.githubusercontent.com/81547/104214356-9bdfc500-5437-11eb-9efe-dac16403f8c0.png)

I am running on Firefox 84.0.2 and  Chromium 87.0.4280.88 on Fedora 33 which both show the same behavior.

**Comment by backspace** [comment]
Regarding the heights, I believe it’s because they are scaled to reflect the relative memory capacity of the nodes. You can see [here](https://github.com/hashicorp/nomad/blob/master/ui/app/components/topo-viz.js#L137-L139) where the scale is configured with the memory of the nodes. The memory on your nodes is quite similar but the difference between `nomad03` and the other two is visually significant because they’re at opposite ends of the domain.

For the lines, is there anything in the Javascript console when you open it up after clicking? Does it show in both Firefox and Chromium when the developer tools are open?

**Comment by apollo13** [comment]
> other two is visually significant because they’re at opposite ends of the domain.

Ah, makes sense

> For the lines, is there anything in the Javascript console when you open it up after clicking? 

Nope

> Does it show in both Firefox and Chromium when the developer tools are open?

It doesn't show when the tools are open, but rather when toggling them (or switching between fullscreen or not).

That said, there seems to be some very very strong caching going on; even though all my member servers report 1.0.1 I have to refresh the UI all the time to get the topology. Ie if I close the nomad tab and open a new one it doesn't show the version in the lower left corner (or the topology button).

When opening a new tab:
![Screenshot from 2021-01-11 18-46-38](https://user-images.githubusercontent.com/81547/104218690-650cad80-543d-11eb-9565-6a42675db424.png)
and after reload with ctrl+r:
![Screenshot from 2021-01-11 18-47-21](https://user-images.githubusercontent.com/81547/104218754-79e94100-543d-11eb-8f2c-c90bc55b72c4.png)
now topology shows again, close that tab again and reopen it:
![Screenshot from 2021-01-11 18-48-48](https://user-images.githubusercontent.com/81547/104218895-af8e2a00-543d-11eb-8fd9-e0f3ee8acc4e.png)
again no topology…

I usually understand caching, but I have no idea what is going on here.

**Comment by apollo13** [comment]
I realize that I am seeing different js files here, but why? why I even cleared the cache in the browser, what else could be keeping such a strong handle on the cache?

**Comment by apollo13** [comment]
I managed to fix the caching issue by removing all history in firefox; but it sounds as if nomad should have some kind of cache busters.

**Comment by apollo13** [comment]
@backspace I made you a small screencast: https://apolloner.eu/~apollo13/.tmp/nomad.webm

**Comment by backspace** [comment]
hmm, I can’t explain why the lines show sometimes and not others, maybe @DingoEatingFuzz, who wrote this feature, would have an idea? 🤞

Regarding caching, the Javascript assets are fingerprinted in the filenames, which is meant to bust the cache when the UI is updated. Is it possible the aggressive caching is happening via whatever’s serving the `index.html` file that links to the assets? This kind of thing can be difficult to diagnose without reproduction 😳

**Comment by apollo13** [comment]
> Is it possible the aggressive caching is happening via whatever’s serving the index.html file that links to the assets?

Probably, though I am serving directly via nomad (granted a haproxy is in between, but that one does not touch cache headers, I'll try to come up with a reproducer)

**Comment by DingoEatingFuzz** [comment]
Regarding lines not showing up sometimes: the UI will intentionally not show lines among allocations if that job+task-group represents a large enough percentage of the cluster. 

However, it doesn't look like in your example that is happening. It's also interesting that the lines show up when you open the dev tools. I suspect this isn't related to the devtools but a window.resize event that opening the devtools triggers.

I'll look into this, thanks for that report!

**Comment by apollo13** [comment]
> I suspect this isn't related to the devtools but a window.resize event that opening the devtools triggers.

Jupp, resizing window as well as switching to full screen all make those lines appear.
