### ISSUE TITLE
Scan compressed module names in modules.dep

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#9776]
https://github.com/hashicorp/nomad/pull/9299#issuecomment-758274664

Looks like CentOS boxes lists compressed module names in `modules.dep`, which are missed by the current regexp. 

@apollo13

> would it be possible to include (\.xz)? in the regex in https://github.com/hashicorp/nomad/pull/9299/files#diff-25979a0adb76fadc59ae57997b3d3e70ac415168d760bd3e6d95b8db1cca7cc6R19 ?

**Comment by apollo13** [comment]
Ok, #9779 for your reviewing pleasure. Let's see if the tests work out well :)
