### ISSUE TITLE
[question] Nomad simple networking between tasks

### ISSUE THREAD

**Issue by anjapadu** [hashicorp/nomad#9777]
Hello, I'm starting to do some tests with nomad and I could use a bit on help on the easiest way to add networking to a group task. Basically my questions are: 

`Which is the easiest way to add internal networking between tasks?`
and
`Shouldn't the tasks on the same group have default access to each other? Or there is something I'm doing wrong?`

I have this configuration:
```terraform
    job "job" {
        datacenters = [ "dc1" ]
        type = "service"
        group "group" {
          count = 1
            task "db" {
                kill_timeout = "120s"
                driver = "docker"
                config {
                    image = "dbimage"
                    port_map {
                      db = 3306
                    }
                }
                env {
                    MYSQL_DATABASE = "db"
                    MYSQL_ROOT_PASSWORD = "pass"
                }
                
                service {
                    name = "db"
                    port = "db"
                }
                resources {
                    memory = 256
                    network {
                        mode = "host"
                        port "db" {}
                    }
                }
            }
            task "app1" {
                driver = "docker"
                kill_timeout = "120s"
                config {
                    image = "app1"
                    port_map {
                      app1 = 5000
                    }
                }
                service {
                    name = "app1"
                    port = "app1"
                }
                resources {
                    memory = 128
                    network {
                        mode = "host"
                        port "app1" {}
                    }
                }
            }
            task "app2" {
                driver = "docker"
                kill_timeout = "120s"
                config {
                    image = "app2:image"
                    port_map {
                      app2 = 4000
                    }
                }
                env {
                    .....
                }
                service {
                    name = "app2"
                    port = "app2"
                }
                resources {
                    memory = 256
                    network {
                        mode = "host"
                        port "app2" {}
                    }
                }
            }
        }
    }
```
and I would like that my app1 and app2 could talk internally to each other and to the db. I have read about the the nomad ADDRESS variables that are passed to each container and I tried to reach connectivity but I get connection refused.
Is the only way to accomplish this behaviour with `connect` ? Or there is a simpler way? Appreciate the help :)

**Comment by tgross** [comment]
@anjapadu the networking configuration you're using here is being specified at the task level (which is deprecated). If you want communication between tasks in the same group, you generally should be specifying it at the group level. That being said, with `host` networking you don't have any isolation whatsoever for the network.

My guess from the context here is that this is for a development environment where you want the tasks to communicate but you also want to be able to reach them from the host? In which case, you probably want something more like the following. Note that the networking configuration is at the top. I've also left off the `service` blocks because they don't really do anything if all the tasks are in the same group:

```hcl
job "job" {
  datacenters = ["dc1"]
  type        = "service"

  group "group" {

    count = 1

    network {
      mode = "host"
      port "db" {
        static = 3306
        to     = 3306
      }
      port "app1" {
        static = 5000
        to     = 5000
      }
      port "app2" {
        static = 4000
        to     = 4000
      }
    }

    task "db" {
      kill_timeout = "120s"
      driver       = "docker"
      config {
        image = "dbimage"
        ports = ["db"]
      }
      env {
        MYSQL_DATABASE      = "db"
        MYSQL_ROOT_PASSWORD = "pass"
      }
      resources {
        memory = 256
      }
    }

    task "app1" {
      driver       = "docker"
      kill_timeout = "120s"
      config {
        image = "app1"
        ports = ["app1"]
      }
      resources {
        memory = 128
      }
    }

    task "app2" {
      driver       = "docker"
      kill_timeout = "120s"
      config {
        image = "app2:image"
        ports = ["app2"]
      }
      env {}
      resources {
        memory = 256
      }
    }
  }
}
```

If you want to share more context about what you're trying to do, we'd be happy to provide more explanation.

**Comment by anjapadu** [comment]
Hey @tgross, thank you for the response. I will set a bit more of context. 
Im currently doing some exploration on nomad because we want to migrate from ECS our sandbox cluster.

The job template I shared is a basic template for a sandbox where all tasks needs to be able to communicate to each other and some of those also need to be able to communicate externally. We planning on have tens of thousands of sandbox running dynamically. 

That being said, I just tried the configuration you kindly shared with me and for some reason I still can't confirm connectivity between tasks, neither with dynamic ports or static ports.
 
![image](https://user-images.githubusercontent.com/16998699/104484245-12470900-5597-11eb-95bf-e2510eeda2e5.png)

![image](https://user-images.githubusercontent.com/16998699/104484568-6b16a180-5597-11eb-9349-d43a473a4850.png)

Could be this a bug or I'm still missing something?

**Comment by tgross** [comment]
> The job template I shared is a basic template for a sandbox where all tasks needs to be able to communicate to each other and some of those also need to be able to communicate externally (with the user using the sandbox). We planning on have tens of thousands of sandbox (jobs) running dynamically.

Ok, in which case you definitely don't want `host` networking, because then you'll run into port collisions. You'll want to use `bridge` networking and then use Consul for service discovery and between tasks in different allocations. You'll most likely want to run the apps and the database as separate jobs as well.

For tasks within the same allocation, they'll all share the same namespace and can communicate on whatever port they're bound on.


> That being said, I just tried the configuration you kindly shared with me and for some reason I still can't confirm connectivity between tasks, neither with dynamic ports or static ports.

Ah, I forgot to add the `network_mode = "host"` config to the `task.config` block. That should solve it, but again you really don't want host networking for this use case. (Also, just FYI it's a lot easier from an accessibility standpoint if you can post text instead of screenshots of text.)

**Comment by anjapadu** [comment]
Thank you @tgross for the guidance. I wasn't able to make it work at the beginning because I was using -dev environment. After set up nomad + vagrant and start nomad as production environment the job template worked as expected. (Is this a bug or an expected behaviour? ) 

Also, and just FYI the db is a piece of the sandbox so if there is 1000 sandboxes there will be 1000 db's, one in each job.
I'm also using dynamic ports and just getting the result mapped port at the end via the API so I suppose I shouldn't encounter any port collision. Will be checking if consul is worth anyway and do some more testing with it to :) 

Thank you for the help!!

**Comment by tgross** [comment]
Glad to hear it. I'm going to close this issue, but please feel free to open a new issue or a Discussion conversation if you need more guidance.
