### ISSUE TITLE
UI consistency issues with namespaces selector.

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#9814]
The UI namespace switcher displays a "special" name for the `default` namespace:
https://github.com/hashicorp/nomad/blob/69b19679e82ec885c9ecc8063a674cec3fe3e5a7/ui/app/templates/components/gutter-menu.hbs#L40-L44

Since the actual name is simply `default` I also have my namespaces created in lowercase:
```
nomad namespace list
Name     Description
default  Default shared namespace
infra    Infrastructure
storage  CSI storage
```

This makes for a kinda weird display in the UI. I'd like to ask to either show the description for all namespaces (probably not the best idea) or remove the special handling of the default namespace during display.

I realize that this all might seem stupid given the other issues that are open, but I think a consistent display is worthwhile in the long run.

**Comment by DingoEatingFuzz** [comment]
I too appreciate consistency!

The special casing of the default namespace was actually just a clever hack to make it known that the dropdown is even for namespaces. I opened #9876 with a fix for this.

**Comment by apollo13** [comment]
Looks great!
