### ISSUE TITLE
Nomad job runtime variables ? 

### ISSUE THREAD

**Issue by anastazya** [hashicorp/nomad#9842]
I'm trying to set a variable for a nomad job, but the documentation is unclear as to where to place the 'variable' block.

 variable "IMAGE_VER" {
   type    = list(string)
   default = ["latest"]
 }

No matter what i try i only get : "Unsupported block type; Blocks of type "variable" are not expected here. "

Documentation i'm using is here : https://www.nomadproject.io/docs/job-specification/hcl2/variables

Nomad v1.0.2

What i run : nomad run -var="IMAGE_VER=latest" job.nomad

**Comment by jrasell** [comment]
Hi @anastazya and thanks for the question.

The variable declaration can be placed in the same file as the job specification. The following example is a slightly modified version of the `nomad init --short`:

```hcl
variable "image" {
 type    = string
 default = "redis:latest"
}

job "example" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = var.image
        ports = ["db"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

The job can then be deployed using the default value via `nomad job run example.nomad` or deployed using a custom variable setting such as `nomad job run -var="image=redis:3.2" example.nomad`. I hope this helps.

I'll take a look through the currently available documentation to see if there is any way to improve it so there is less confusion in the future.

**Comment by anastazya** [comment]
"Unsupported block type; Blocks of type "variable" are not expected here."

The job runs just fine without the variable block, once i add i receive this error.

**Comment by jrasell** [comment]
@anastazya could you please share the job specification (redacted as needed) you are attempting to use and the commands you're attempting to use?

**Comment by anastazya** [comment]
variable "image" {
 type    = string
 default = "latest"
}

job "dev-redis" {
  datacenters = ["dc1"]
  type        = "service"

	update {
		stagger = "10s"
		max_parallel = 1
	}

	group "dev" {
      count = 1

	  network {
		 port "db" {
         static = 6379
	  }
	}

	  service {
		name = "dev-redis"
		tags = ["dev-redis"]
		port = "db"
		
        check {
		  name = "alive"
		  type = "tcp"
		  interval = "10s"
		  timeout = "2s"
	  }
	}
    
		restart {
			attempts = 2
			interval = "1m"
			delay = "10s"
			mode = "fail"
		}

		task "dev-redis" {
			driver = "docker"
			env {
			pass   = "password"
		   }

			config {
				image = "redis:${image}"
                network_mode = "host"
			}

			resources {
				cpu    = 500
				memory = 256
			}
		}
	}
}

**Comment by jrasell** [comment]
Hi @anastazya, as detailed in the [Nomad hcl2 documentation](https://www.nomadproject.io/docs/job-specification/hcl2/variables#using-input-variable-values), accessing input variables uses the format `var.<NAME>`. As you are attempting to format the config image string, the config.image parameter should look like `image = format("redis:%s", var.image)`. I have tested this locally with your exact job spec and can confirm this works as expected.

**Comment by anastazya** [comment]
> image = format("redis:%s", var.image)

Thank you for your help, i'm testing that now. I confirm Nomad v1.0.2 both on local and remote servers ( they are all  updated daily and simultaneously ).
