### ISSUE TITLE
unrecognized RPC byte error

### ISSUE THREAD

**Issue by bvanhou** [hashicorp/nomad#9859]
Needing assistance from Hashicorp identifying customer issue

### Nomad version
Version: 0.11.3

### Operating system and Environment details
CircleCI Enterprise Server Environment Hosted on AWS

### Issue
Nomad service cannot communicate due to an "RPC" error

### Reproduction steps
Unable to establish exact reproduction steps, we believe it is due to some kind of network configuration issue. However, error occurs on customer environment inconsistently. 
Need help identifying more information around the Nomad service error to help determine where the error is coming from.

### Nomad Client logs (if appropriate)
```
    21/01/07 13:18:04.488163 [DEBUG] worker: dequeued evaluation 2674b1cc-5ea0-d2ec-289d-cc8d51708de3
    2021/01/07 13:18:04.488212 [DEBUG] sched.core: eval GC: scanning before index 247 (1h0m0s)
    2021/01/07 13:18:04.488306 [DEBUG] worker: ack for evaluation 2674b1cc-5ea0-d2ec-289d-cc8d51708de3
    2021/01/07 13:18:04.488179 [DEBUG] worker: dequeued evaluation 47069481-eba0-9003-138b-dd9c2ced2ca1
    2021/01/07 13:18:04.488353 [DEBUG] sched.core: node GC: scanning before index 0 (24h0m0s)
    2021/01/07 13:18:04.488374 [DEBUG] worker: ack for evaluation 47069481-eba0-9003-138b-dd9c2ced2ca1
    2021/01/07 13:18:04.488378 [DEBUG] worker: dequeued evaluation fed69c1a-f645-9f98-61bd-a53e4c0847d1
    2021/01/07 13:18:04.488414 [DEBUG] sched.core: job GC: scanning before index 247 (5s)
    2021/01/07 13:18:04.488543 [DEBUG] worker: ack for evaluation fed69c1a-f645-9f98-61bd-a53e4c0847d1
    2021/01/07 13:18:31.974851 [ERR] nomad.rpc: unrecognized RPC byte: 6
    2021/01/07 13:18:32.704564 [ERR] nomad.rpc: unrecognized RPC byte: 6
    2021/01/07 13:18:37.144130 [DEBUG] http: Request /v1/jobs (471.895µs)
    2021/01/07 13:18:52.026579 [ERR] nomad.rpc: unrecognized RPC byte: 6
    2021/01/07 13:19:08.848535 [ERR] nomad.rpc: unrecognized RPC byte: 6
    2021/01/07 13:19:16.252901 [ERR] nomad.rpc: unrecognized RPC byte: 6
    2021/01/07 13:19:32.546781 [ERR] nomad.rpc: unrecognized RPC byte: 6

```

**Comment by tgross** [comment]
The error message is coming from the [RPC connection handler](https://github.com/hashicorp/nomad/blob/v0.11.0/nomad/rpc.go#L327). But that RPC byte was introduced in c0e01d8a9e85103c535187c7f1712d7e96be700e, which shipped in Nomad 0.8.

Are all members of the cluster on a recent version of Nomad? Can you provide the output of `nomad server members`?

**Comment by bvanhou** [comment]
@tgross This is what the customer sent back. FYI, I'm a DCE with CircleCI. Just wanted to clarify

```
ubuntu@ip-x-x-x-x:~$ nomad version
Nomad v0.6.0-dev (4933d8cd92290a14a1ce9e91ecad)
```

```
nomad server-members
Name                 Address      Port  Status  Leader  Protocol  Build     Datacenter  Region
580c---dc.global  172.x.x.x  4648  alive   true    2         0.6.0dev  us-east-1   global
```

**Comment by tgross** [comment]
Ok, @bvanhou so that RPC byte 6 was added in Nomad 0.8. So error message suggests that they have a client host on Nomad 0.8 or higher, which is going to cause capability issues. Getting them onto a recent and supported version of Nomad for the entire cluster is probably the best bet here.

**Comment by bvanhou** [comment]
Trying it out, ill let you know the result.

**Comment by bvanhou** [comment]
Thank you! @tgross that worked

**Comment by tgross** [comment]
Glad to hear!
