### ISSUE TITLE
[Feature Request] Add option to validate agent/server config file(s)

### ISSUE THREAD

**Issue by gabrieltz** [hashicorp/nomad#9865]
It would be nice to have an option to validate a newly edited config file, it could also be used in the systemd unit file
to prevent the agent from not restarting in case of an error or typo.
Something like this:
```
ExecStartPre=/usr/local/bin/nomad agent -config=/etc/nomad.d/server.hcl -validate-config
ExecReload=/usr/local/bin/nomad agent -config=/etc/nomad.d/server.hcl -validate-config
ExecReload=/bin/kill -HUP $MAINPID
```

Thank you

**Comment by tgross** [comment]
Hi @gabrieltz! This is a great idea and we're already tracking that in https://github.com/hashicorp/nomad/issues/5385. I'm going to close this issue as a dupe but if you give a 👍 on that issue it'll help push for getting it onto the roadmap. Thanks!
