### ISSUE TITLE
e2e: TestNamespacesFiltering failing

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#9866]
The e2e test `TestNamespacesFiltering` has been failing on a regular occurrence of late and should be investigated and fixed. I do not know currently whether it is a flakey test or an outright failing test.

**Comment by notnoop** [comment]
The test got deflaked in https://github.com/hashicorp/nomad/commit/60bb50c432f016b93c8600a7268fe4433fd983cd .
