### ISSUE TITLE
Cannot use HCL2 variable for datacenters name

### ISSUE THREAD

**Issue by bert2002** [hashicorp/nomad#9882]
### Nomad version
```
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)
```
### Job file (if appropriate)

```
job "workload" {

  datacenters = [ var.datacenters ]
  type = "service"

}
```

### Nomad Client logs (if appropriate)
```
nomad job plan -var="datacenters:test" example.nomad
Error getting job struct: Error parsing job file from example.nomad:
example.nomad:3,22-34: Unsupported attribute; This object does not have an attribute named "datacenters".
example.nomad:3,17-18: Unsuitable value type; Unsuitable value: value must be known
```

Hi,
I am trying to set the datacenter via a variable name and it does not accept it. Either via an external vars file or in the command line directly.

Hope this will be supported soon :)

bert2002

**Comment by bert2002** [comment]
Was my problem defining the variable :)

**Comment by notnoop** [comment]
I'm glad you sorted it out.  I agree that the error message should be improved here, with a hint to ensure that variables are declared.  I'll investigate and see how we can improve the error message.  Thanks for raising it!
