### ISSUE TITLE
Different tags registered to Consul Connect sidecar when moving service stanza between task/group level

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#9898]
### Nomad version
`Nomad v1.0.2 (4c1d4fc6a5823ebc8c3e748daec7b4fda3f11037)`

### Operating system and Environment details
Ubuntu 18.04

### Issue

When the service stanza using Consul Connect is defined at the group level, the tags set on the service are propagated to the sidecar. When the service stanza is moved to the task level, the tags are not included on the sidecar.

On a similar note, is there a way to override the tags in the group level from the task level? For example, we use `fabio-` as a tag to register routes in Fabio, but the sidecar proxy inherits the tags and is added to the Fabio route table, **but** the sidecar proxy cannot be accessed anyway, so we'd like to be able to remove it.

### Reproduction steps

Deploy both jobs, comparing tags set on the sidecar proxy.

With Fabio, the sidecar proxy will be registered to Fabio as well when defined at the group level, but not the task level.

### Job file (if appropriate)

**countdash-group-level.hcl**:

```hcl
job "countdash-group-level" {
  datacenters = ["kitchen"]

  meta {
    uuid = "0E08C448-81D5-4E2C-AF09-852AA6E96225"
  }

  group "api" {
    count = 1

    network {
      mode = "bridge"
      port "http" {}
    }

    service {
      name = "count-api"
      port = "http"

      connect {
        sidecar_service {}

        sidecar_task {
          resources {
            cpu    = 20
            memory = 50
          }
        }
      }

      check {
        type     = "http"
        name     = "api-health"
        path     = "/health"
        interval = "10s"
        timeout  = "3s"
      }
    }

    task "web" {
      driver = "docker"

      config {
        image = "hashicorpnomad/counter-api:v3"
      }

      env {
        PORT = "${NOMAD_PORT_http}"
      }

      resources {
        cpu = 20
        memory = 50
      }
    }
  }

  group "dashboard" {
    network {
      mode = "bridge"

      port "http" {
        to = 9002
      }
    }

    service {
      name = "count-dashboard"
      port = "http"
      task = "dashboard"

      tags = [
        "fabio-/${NOMAD_JOB_NAME} strip=/${NOMAD_JOB_NAME}"
      ]

      check {
        type     = "http"
        name     = "dashboard-health"
        path     = "/"
        interval = "10s"
        timeout  = "3s"
      }

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "count-api"
              local_bind_port  = 8080
            }
          }
        }

        sidecar_task {
          resources {
            cpu    = 20
            memory = 50
          }
        }
      }
    }

    task "dashboard" {
      driver = "docker"

      env {
        COUNTING_SERVICE_URL = "http://localhost:8080"
      }

      config {
        image = "hashicorpnomad/counter-dashboard:v3"
      }

      resources {
        cpu = 20
        memory = 50
      }
    }
  }
}

```

**countdash-task-level.hcl**:

```hcl
job "countdash-task-level" {
  datacenters = ["kitchen"]

  meta {
    uuid = "0E08C448-81D5-4E2C-AF09-852AA6E96225"
  }

  group "api" {
    count = 1

    network {
      mode = "bridge"
      port "http" {}
    }

    service {
      name = "count-api"
      port = "http"

      connect {
        sidecar_service {}

        sidecar_task {
          resources {
            cpu    = 20
            memory = 50
          }
        }
      }

      check {
        type     = "http"
        name     = "api-health"
        path     = "/health"
        interval = "10s"
        timeout  = "3s"
      }
    }

    task "web" {
      driver = "docker"

      config {
        image = "hashicorpnomad/counter-api:v3"
      }

      env {
        PORT = "${NOMAD_PORT_http}"
      }

      resources {
        cpu = 20
        memory = 50
      }
    }
  }

  group "dashboard" {
    network {
      mode = "bridge"

      port "http" {
        to = 9002
      }
    }

    task "dashboard" {
      driver = "docker"

      env {
        COUNTING_SERVICE_URL = "http://localhost:8080"
      }

      config {
        image = "hashicorpnomad/counter-dashboard:v3"
      }

      resources {
        cpu = 20
        memory = 50
      }

      service {
        name = "count-dashboard"
        port = "http"
        task = "dashboard"

        tags = [
          "fabio-/${NOMAD_JOB_NAME} strip=/${NOMAD_JOB_NAME}"
        ]

        check {
          type     = "http"
          name     = "dashboard-health"
          path     = "/"
          interval = "10s"
          timeout  = "3s"
        }

        connect {
          sidecar_service {
            proxy {
              upstreams {
                destination_name = "count-api"
                local_bind_port  = 8080
              }
            }
          }

          sidecar_task {
            resources {
              cpu    = 20
              memory = 50
            }
          }
        }
      }
    }
  }
}

```

**Comment by shoenig** [comment]
> When the service stanza is moved to the task level, the tags are not included on the sidecar.

Task level `service` stanzas using `connect` aren't supported - there was validation for this that accidentally got removed in Nomad 1.0 (part of HCL2 migration) and is being added back in the next bugfix release (tentatively 1.0.4). 

https://github.com/hashicorp/nomad/issues/9450

The tag inheritance behavior for sidecar proxies is actually a feature of Consul - one that has caused a lot of confusion for Nomad use cases (like fabio!) 

https://github.com/hashicorp/consul/issues/9643

> is there a way to override the tags in the group level from the task level 

If I understand correctly you want to stop the inheritance behavior, right? Which can be done by setting the [sidecar_service.tags](https://www.nomadproject.io/docs/job-specification/sidecar_service#tags) to some non-default value.

**Comment by evandam** [comment]
Thanks for the quick response @shoenig!

For setting `sidecar_service.tags`, I'm not able to set it to `null` or `[]` to have the sidecar tags be empty, instead I need to do something like `tags = ["dummy"]`. Is it possible to clear tags rather than doing it this way?

**Comment by tgross** [comment]
Doing a bit of issue cleanup. Sorry the open question got left so long here @evandam. It doesn't look like there's a way to clear the tags without setting a dummy value, as `[]` is the default that get overridden and there's not a way for us to tell the difference between that default and "unset" in a backwards compatible way. 

I'm going to close this question out as I think the original issue has been answered at this point. Thanks!

**Comment by shuiyunwudi** [comment]
I encounter the same problem as Blogger said. I use fabio+consul, beacause of the sidecar inherit tags of parent service, when invoke service on consul, There will be a 50% probability that sidecar will be called. I have no idea why design like that.or there are any way to use a different tags for the sidecar?
