### ISSUE TITLE
[question] clarification of usage for NOMAD_ALLOC_DIR 

### ISSUE THREAD

**Issue by cberescu** [hashicorp/nomad#9901]
### Nomad version
Nomad v1.0.2

### Operating system and Environment details
Ubuntu 18 
### Issue

Trying to use the shared folder "Alloc" on multiple tasks in a group using docker driver. I either receive that volumes are not enabled or  that  "artifact destination path escapes the alloc directory"

### Job file (if appropriate)

In this case i receive this error : `volumes are not enabled; cannot mount host paths: "/alloc/data/repo:/app/"`

```
artifact {
			source      = "git::some address"
			destination = "${NOMAD_ALLOC_DIR}/data/repo"
}
```

Also tried this one in witch case i  receive the  `"artifact destination path escapes the alloc directory"`
```
artifact {
			source      = "git::some address"
			destination = "..${NOMAD_ALLOC_DIR}/data/repo"
}
```
From the docs i understand that the alloc folder is shared by all tasks and they have access to it. 

So the question, do i need to enable volumes? Am i missing some kind of configuration. Am i not using it right ?

**Comment by cgbaker** [comment]
The second approach (`..${NOMAD_ALLOC_DIR}`) will not work, but the first should. In fact, we have explicit tests of this syntax: 
https://github.com/hashicorp/nomad/blob/v1.0.2/e2e/consultemplate/input/template_shared_alloc.nomad

I tried to reproduce this error by configuring docker with `volumes.enabled = false`, but I was unable to get the error message. My job spec was the following:
```hcl
job "gitter" {
  type = "batch"
  datacenters = ["dc1"]
  task "gitter" {
    driver = "docker"
    config {
      image = "alpine"
      command = "find"
      args = ["${NOMAD_ALLOC_DIR}/data/repo"]
    }
    artifact {
      source = "git::https://github.com/hashicorp/go-getter"
      destination = "${NOMAD_ALLOC_DIR}/data/repo"
    }
  }
}
```

I believe that the error message that you reported corresponds to the `volumes` [task config parameter](https://www.nomadproject.io/docs/drivers/docker#volumes). Does you job spec have a volume bind, and do you mind sharing the job spec?

**Comment by cberescu** [comment]
Ok, actually yes, the problem on the first issue is with the volume mounting for docker. Do i need volumes enabled to do that? Aren't nomad volumes different than docker driver volumes ?  
```
job "profiles" {
  datacenters = ["dc1"]
  type = "service"	
  group "profiles" {
    count = 2
	network {
		port "phpcgi" {
			to = 9000
		}
  }
	task "profiles-php" {
		driver = "docker"
		artifact {
			source      = "git::https://github.com/hashicorp/go-getter"
			destination = "${NOMAD_ALLOC_DIR}/data/repo"
		}
	
		config {
			image        = "oberonamsterdam/php:7.1-fpm"
			ports = ["phpcgi"]
			volumes = [
			  "${NOMAD_ALLOC_DIR}/data/repo:/app/"
			]
		}
		resources {
			cpu    = 500
			memory = 256
		}
	}
  }
}

```
 and i am receiving this : 


```
Failed to create container configuration for image "oberonamsterdam/php:7.1-fpm" ("sha256:f8c738963a5067b5ad1a52b03b093a3fd1492d6d476423b1cb877d466164925f"): volumes are not enabled; cannot mount host paths: "/alloc/data/repo:/app/"

```

**Comment by tgross** [comment]
> Ok, actually yes, the problem on the first issue is with the volume mounting for docker. Do i need volumes enabled to do that? Aren't nomad volumes different than docker driver volumes ?

The task `config` block is the configuration for that specific task driver. So in this case you're using the `docker` task driver so the `volumes` within that configuration are indeed Docker volumes. The source for the Docker `volumes` block is always one from the host, so trying to mount the artifact via a volume won't work at all. However, you should be able to do this with a `mount` block which gives you more fine-grained control over the source:

```hcl
job "profiles" {
  datacenters = ["dc1"]
  type        = "service"
  group "profiles" {
    count = 2
    network {
      port "phpcgi" {
        to = 9000
      }
    }
    task "profiles-php" {
      driver = "docker"
      artifact {
        source      = "git::https://github.com/hashicorp/go-getter"
        destination = "${NOMAD_ALLOC_DIR}/data/repo"
      }

      config {
        image = "oberonamsterdam/php:7.1-fpm"
        ports = ["phpcgi"]
        mount {
          type     = "bind"
          source   = "alloc"
          target   = "/app/"
          readonly = true
        }
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}

```

**Comment by cberescu** [comment]
I have 2 more questions :

1. can i mount the same  folder in 2 different tasks from the same group. 

In the docker drive documents we have this : 



> volume  - (Optional) A list of host_path:container_path strings to bind host paths to container paths. Mounting host paths outside of the allocation working directory is prevented by default and limits volumes to directories that exist inside the allocation working directory. You can allow mounting host paths outside of the allocation working directory on individual clients by setting the docker.volumes.enabled option to true in the client's configuration.


2. Does that not mean that i can mount any folder as long as it is in the allocation working  dirrectory , be it either alloc, local, secret ?

**Comment by tgross** [comment]
> 1. can i mount the same folder in 2 different tasks from the same group.

If the directory is visible to both tasks, yes. So for example directories within a task's container image don't exist within the allocation working directory (they'll be somewhere in `/var/lib/docker` rather than e.g. `/var/nomad/`), so there's no way to mount those between tasks without having `docker.volumes.enabled = true` and then finding the real place on disk for their absolute paths.

> 2. Does that not mean that i can mount any folder as long as it is in the allocation working dirrectory , be it either alloc, local, secret ?

It does, but `$NOMAD_ALLOC_DIR` in the use you've described is `/alloc`. And because Docker `volumes` blocks consider that path to be _on the host_, that's not in the allocation working directory.

**Comment by cberescu** [comment]
I think the docs are a little ambiguous , at least for me when it says `Mounting host paths outside of the allocation working directory is prevented by default and limits volumes to directories that exist inside the allocation working directory.`  What i read here i can mount whatever in the allocation working directory but need the docker.volumes.enabled = true if i want to mount something outside it. 

Anyway thanks for all the help @tgross . I was in the end able to mount it and will write the details bellow in case someone else gets stuck at it. 

Added in the client the fallowing config : 

```
plugin "docker" {
  config {
    volumes {
      enabled = true
    }
}
}
```
And this  in the config section of task
```
mount {
	type     = "bind"
	source   = "..${NOMAD_ALLOC_DIR}/data/repo"
	target   = "/app/"
	readonly = true
}
```

**Comment by tgross** [comment]
Glad to hear it!
