### ISSUE TITLE
Bug when using mount in the docker drive with ${NOMAD_ALLOC_DIR} in artifact stanza

### ISSUE THREAD

**Issue by cberescu** [hashicorp/nomad#9904]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

### Nomad version
Nomad v1.0.2

### Operating system and Environment details
Ubuntu 18.04
### Issue

When having this king of configuration : 

```
job "profiles" {
  datacenters = ["dc1"]
  type = "service"	
  group "profiles" {
    count = 2
	
	network {
		port "phpcgi" {
			to = 9000
		}
  }
	task "profiles-php" {
		driver = "docker"
		artifact {
			source      = "git::<somegit>"
			destination = "${NOMAD_ALLOC_DIR}/data/repo"
		}
			config {
			image        = "oberonamsterdam/php:7.1-fpm"
			ports = ["phpcgi"]
			mount {
			  type     = "bind"
			  source   = "..${NOMAD_ALLOC_DIR}/data/repo"
			  target   = "/app/"
			  readonly = true
			}
		}
		resources {
			cpu    = 500
			memory = 256
		}
	}
  }
}
```

The `${NOMAD_ALLOC_DIR}` in the artifact is not replaced anymore and a directory is created under the `local/` named `"${NOMAD_ALLOC_DIR}"` 

If i remove the mount from the docker drive config, the ${NOMAD_ALLOC_DIR} is correctly used and the artifact is deployed at the correct location. 

My config looks like this : 
```
# Full configuration options can be found at https://www.nomadproject.io/docs/configuration
datacenter = "dc1"
data_dir = "/opt/nomad/data"
bind_addr = "something"

client {
  enabled = true
  servers = ["somethingelse"]
}


plugin "docker" {
  config {
    volumes {
      enabled = true
    }
}
}
```

### Reproduction steps
Using the provided configuration should do the trick.

**Comment by tgross** [comment]
Hello again @cberescu!

Ok, so let's use a jobspec using a similar artifact and mount block, that we can both run without any special setup:

```hcl
job "profiles" {
  datacenters = ["dc1"]
  group "profiles" {

    task "profiles-php" {
      driver = "docker"
      artifact {
        source      = "http://example.com"
        destination = "${NOMAD_ALLOC_DIR}/data/repo"
      }
      config {
        image = "busybox:1"
        command = "/bin/sh"
        args = ["-c", "sleep 600"]
        mount {
          type     = "bind"
          source   = "..${NOMAD_ALLOC_DIR}/data/repo"
          target   = "/app/"
          readonly = true
        }
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

If we run this we see the directory has been created:

```
$ nomad job run ./example.nomad
==> Monitoring evaluation "5ac5eae1"
    Evaluation triggered by job "profiles"
==> Monitoring evaluation "5ac5eae1"
    Evaluation within deployment: "1740f024"
    Allocation "412f0065" created: node "f9bb32e4", group "profiles"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "5ac5eae1" finished with status "complete"

$ nomad alloc exec 412 /bin/sh
/ # ls -lah /alloc/data/repo
-rw-r--r--    1 root     root        1.2K Jan 27 15:34 /alloc/data/repo
```

The Docker bind mount is there, just where we'd expect it:

```
$ docker inspect 429  | jq '.[].Mounts'
[
  {
    "Type": "bind",
    "Source": "/var/nomad/alloc/412f0065-6739-1e7c-202d-cc9cb75bc8ae/alloc",
    "Destination": "/alloc",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "/var/nomad/alloc/412f0065-6739-1e7c-202d-cc9cb75bc8ae/profiles-php/local",
    "Destination": "/local",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "/var/nomad/alloc/412f0065-6739-1e7c-202d-cc9cb75bc8ae/profiles-php/secrets",
    "Destination": "/secrets",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "/var/nomad/alloc/412f0065-6739-1e7c-202d-cc9cb75bc8ae/alloc/data/repo",
    "Destination": "/app",
    "Mode": "",
    "RW": false,
    "Propagation": "rprivate"
  }
]
```

So what gives, where's our artifact?

```
/ # head /app
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
```

So why don't we see it at `/alloc/data/role` as well? That's weird... let's check the docs for artifact [`destination`]https://www.nomadproject.io/docs/job-specification/artifact#destination):

> destination (string: "local/") - Specifies the directory path to download the artifact, relative to the root of the task's working directory. If omitted, the default value is to place the artifact in local/. The destination is treated as a directory unless mode is set to file. Source files will be downloaded into that directory path. For more details on how the destination interacts with task drivers, see the Filesystem internals documentation. Interpolation is not yet supported.

Two important items of note that the docs tell us:
* Interpolation is not supported.
* The destination is relative to the _task working directory._

And if we chase down that [Filesystem Internals](https://www.nomadproject.io/docs/internals/filesystem#templates-artifacts-and-dispatch-payloads) documentation, we know the bind mount is created _after_ the artifact has been downloaded, the confusing behavior is because of the order of operations and that Docker is creating all its bind-mounts in the same step.

Ok, so let's try this modified job, that takes those two rules into account:

```hcl
job "profiles" {
  datacenters = ["dc1"]
  group "profiles" {

    task "profiles-php" {
      driver = "docker"
      artifact {
        source      = "http://example.com"
        destination = "../alloc/data/repo/index.html"
      }
      config {
        image = "busybox:1"
        command = "/bin/sh"
        args = ["-c", "sleep 600"]
        mount {
          type     = "bind"
          source   = "..${NOMAD_ALLOC_DIR}/data/repo"
          target   = "/app/"
          readonly = true
        }
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

```
$ nomad alloc exec 2e3 /bin/sh
/ # head /alloc/data/repo/index.html
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
```

And this is also visible in the target location:

```
/ # head /app/index.html
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
```

**Comment by cberescu** [comment]
Hi again @tgross ,

When i tried your example i got 
```
failed to download artifact "http://example.com": artifact destination path escapes the alloc directory
```
When i tried again it worked fine. It seems sometimes it works sometimes it does not.

**Comment by tgross** [comment]
> It seems the issue with the path escapes the alloc directory happens only on some nodes. The config is the same on all nodes.. so maybe it is something from the system ?

Unfortunately it looks like we don't expose the `docker.volumes.enabled` field as a node attribute for `nomad node status -verbose`, but I would definitely double-check that you've restarted (not merely reloaded) the nodes where the allocation is being placed and you're getting that error message. And that those nodes are on the same version of Nomad as your servers and not an earlier version (there were some recent changes to artifact block behavior).

**Comment by cberescu** [comment]
You were right about the version , on some nodes there was the 1.0.1 version and from there was all the trouble. Now everything works! 

Thanks again for all your help @tgross !
