### ISSUE TITLE
Nomad does not wait until allocations become healthy.

### ISSUE THREAD

**Issue by Laboltus** [hashicorp/nomad#9915]
### Nomad version
0.11.3

### Operating system and Environment details
Ubuntu 18.04.3 LTS
### Issue
During rolling update, Nomad does not wait until "max_parallel" allocations become healthy and restarts the next set of allocations right after "min_healthy_time" passed. I have found similar issue in  #7320 but it's marked as fixed in 0.11.0.
### Reproduction steps
Run a rolling update with application, which become healthy after some time (~60 sec in my case) and check when the next allocations will be restarted after the previous. In my case the interval is exactly "min_healthy_time" (30 sec in my case).

**Comment by Laboltus** [comment]
I have checked release notes for all next nomad releases and found nothing about this issue.

**Comment by tgross** [comment]
Hi @Laboltus! I wasn't able to reproduce this on 0.11.0, a newer 0.11.x, or the current 1.0.3-dev. Here's the job spec I'm using

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  update {
    max_parallel      = 2
    health_check      = "checks"
    min_healthy_time  = "10s"
    healthy_deadline  = "5m"
    progress_deadline = "10m"
  }

  group "group" {
    count = 5
    task "www" {

      driver = "docker"

      service {
        port = "www"
        check {
          type     = "http"
          path = "/index.html"
          interval = "10s"
          timeout  = "2s"
        }
      }

      template {
        data = "<html>ok</html>"
        destination = "local/index.html"
      }

      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["-c", "sleep 20; httpd -v -f -p 8000 -h local"]

        port_map {
          www = 8000
        }
      }

      resources {
        cpu    = 255
        memory = 128

        network {
          mbits = 1
          port "www" {}
        }
      }
    }
  }
}
```

</details>

The important elements of this job is that each allocation takes 20s before it starts replying to health checks, we have a max_parallel 2, and the minimum healthy time is set to 10s. 

I ran this job and waited a bit more than 30s for all 5 allocations to be marked healthy and the deployment to be marked successful. Then I incremented the `resources.cpu` by 1, and re-run. I see two allocations stopped and replaced immediately. We're in this state for about 30s (20s to become healthy + 10s min healthy time):

```
$ nomad job status
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
4c3faea1  80864ae3  group       1        run      running   33s ago    27s ago
6fa8cff8  80864ae3  group       1        run      running   33s ago    27s ago
0f5b47f7  80864ae3  group       0        run      running   2m34s ago  1m57s ago
237505c0  80864ae3  group       0        run      running   2m34s ago  2m3s ago
72582fff  80864ae3  group       0        run      running   2m34s ago  2m ago
97695270  80864ae3  group       0        stop     complete  2m34s ago  28s ago
bad85c6b  80864ae3  group       0        stop     complete  2m34s ago  28s ago
```

And after that we see the second batch rolling through:

```
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
44775bb0  80864ae3  group       1        run      pending   3s ago     3s ago
3e7b32d1  80864ae3  group       1        run      running   12s ago    6s ago
4c3faea1  80864ae3  group       1        run      running   49s ago    13s ago
6fa8cff8  80864ae3  group       1        run      running   49s ago    4s ago
0f5b47f7  80864ae3  group       0        stop     running   2m50s ago  2s ago
237505c0  80864ae3  group       0        stop     complete  2m50s ago  6s ago
72582fff  80864ae3  group       0        run      running   2m50s ago  2m16s ago
97695270  80864ae3  group       0        stop     complete  2m50s ago  44s ago
bad85c6b  80864ae3  group       0        stop     complete  2m50s ago  44s ago
```

Can you provide a minimum jobspec that demonstrates what you're seeing?

**Comment by Laboltus** [comment]
Hi @tgross!
Here is slightly modified version of your job:
<details>
<summary>jobspec</summary>
job "example" {
  datacenters = ["dc1"]
  type = "system"

  update {
    max_parallel      = 2
    health_check      = "checks"
    min_healthy_time  = "10s"
    healthy_deadline  = "5m"
    progress_deadline = "10m"
  }

  group "group" {
    constraint {
      operator  = "distinct_hosts"
      value     = "true"
    }

    constraint {
      attribute    = "${meta.role}"
      regexp = ".+backend"
    }

    task "www" {

      driver = "raw_exec"

      service {
        port = "www"
        check {
          type     = "tcp"
          interval = "1s"
          timeout  = "1s"
        }
      }

      config {
        command = "/bin/sh"
        args    = ["-c", "sleep 60; nc -l -p 9000"]
      }

      resources {
        cpu    = 255
        memory = 128

        network {
          mbits = 1
          port "www" {}
        }
      }
    }
  }
}
</details>

Main differences are:
* type = "system"
* driver = "raw_exec"
* the app becomes available in 60 sec
with this specs the job starts 12 allocations on my cluster, so with "max_parallel = 2" and 60+10 sec per "set" the update should take al least 7 min but in fact it takes 2m35.213s.
<details>
<summary>Output:</summary>
```
$ time nomad run jobs/test.raw_exec-driver.nomad 
Job Warnings:
1 warning(s):

* Group "group" has warnings: 1 error occurred:
	* Update max parallel count is greater than task group count (2 > 1). A destructive change would result in the simultaneous replacement of all allocations.



==> Monitoring evaluation "2b0f1279"
    Evaluation triggered by job "example"
    Allocation "7685ef84" created: node "93590df9", group "group"
    Allocation "eda17057" created: node "16611e66", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "2b0f1279" finished with status "complete"
==> Monitoring evaluation "7c497e52"
    Evaluation triggered by job "example"
    Allocation "6bb2e711" created: node "78fb2981", group "group"
    Allocation "dca40fcd" created: node "0ad2f77e", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "7c497e52" finished with status "complete"
==> Monitoring next evaluation "4fdec201" in 30s
==> Monitoring evaluation "4fdec201"
    Evaluation triggered by job "example"
    Allocation "07decc20" created: node "85564ee7", group "group"
    Allocation "c6ce9992" created: node "eeed96d8", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "4fdec201" finished with status "complete"
==> Monitoring next evaluation "571a15f3" in 30s
==> Monitoring evaluation "571a15f3"
    Evaluation triggered by job "example"
    Allocation "84aa4dea" created: node "2bb127e8", group "group"
    Allocation "d40e869a" created: node "713a3b27", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "571a15f3" finished with status "complete"
==> Monitoring next evaluation "55884d9b" in 30s
==> Monitoring evaluation "55884d9b"
    Evaluation triggered by job "example"
    Allocation "07eb33ed" created: node "b078cecb", group "group"
    Allocation "f55c0b5f" created: node "bc1328e6", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "55884d9b" finished with status "complete"
==> Monitoring next evaluation "f28e351d" in 30s
==> Monitoring evaluation "f28e351d"
    Evaluation triggered by job "example"
    Allocation "08904177" created: node "acb8b6a8", group "group"
    Allocation "a89240c2" created: node "0e1ca292", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "f28e351d" finished with status "complete"

real	2m35.213s
user	0m0.176s
sys	0m0.164s

```
</details>

**Comment by tgross** [comment]
Ah, I see. Unfortunately most of the features of deployments aren't supported for `system` jobs.

From the [`update`](https://www.nomadproject.io/docs/job-specification/update) docs:
> For system jobs, only max_parallel and stagger are enforced. The job is updated at a rate of max_parallel, waiting stagger duration before the next set of updates. The system scheduler will be updated to support the new update stanza in a future release.

**Comment by Laboltus** [comment]
Thanks a lot for pointing out the doc. Do you have any ETA for the updated system scheduler ? This is important for dynamic cloud environment.

**Comment by tgross** [comment]
Unfortunately there's no ETA on that. You can keep an eye on https://github.com/hashicorp/nomad/issues/4740 but as you can see that's been an open request for a while. Our product team does keep an eye on "reactions" so 👍 'ing can't hurt to move that along.

As a workaround, which I realize isn't ideal:
* Pad the `min_healthy_time` such that you know the application will be live.
* Use a service health check for routing, so that you know you're not sending traffic to a task that Nomad has deployed but isn't yet ready (this is a good idea in any event).

**Comment by tgross** [comment]
Going to close this issue out. Keep watch on #4740, but if you've got additional questions about the workarounds, feel free to open a new issue.
