### ISSUE TITLE
network bandwidth limits should be removed from quotas

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#9920]
The quota API [docs](https://www.nomadproject.io/api-docs/quotas) and the [quota example docs](https://learn.hashicorp.com/tutorials/nomad/quotas) still advocate the ability to limit network bandwidth usage.

Likewise the CLI also still exposes a **Network Usage** column : 

```
$ nomad quota status default-quota    
Name        = default-quota
Description = Limit the shared default namespace
Limits      = 1

Quota Limits
Region  CPU Usage  Memory Usage  Network Usage
global  0 / 2500   0 / 4096      0 / inf
```

However, the ability to express bandwidth usage is not available in the new group level network stanza and the usage of **network {}**  in the resource stanza is deprecated.

**Comment by tgross** [comment]
Thanks @henrikjohansen! We already have a PR open in the ENT repo and our docs to do that, it's been waiting on some other work to complete.

**Comment by tgross** [comment]
That PR and https://github.com/hashicorp/nomad/pull/9940 have been merged. That will land on the website documentation with the 1.0.4 release.

**Comment by henrikjohansen** [comment]
@tgross FYI - the CLI `quota` command still lists ***Network Usage*** in Nomad v1.3.5+ent : 

```
$ nomad quota status default-quota
Name        = default-quota
Description = Limit the shared default namespace
Limits      = 1

Quota Limits
Region  CPU Usage  Memory Usage  Memory Max Usage  Network Usage
global  0 / 2500   0 / 4096      0 / inf           0 / inf
```

**Comment by tgross** [comment]
Thanks @henrikjohansen. Fixed in https://github.com/hashicorp/nomad/pull/14468
