### ISSUE TITLE
Node drain metadata

### ISSUE THREAD

**Issue by nickethier** [hashicorp/nomad#9928]
When a node is drained in Nomad there is no way to tell who triggered the drain or why. This becomes more of a need as tools like the [Nomad Autoscaler](https://github.com/hashicorp/nomad-autoscaler) become more widely used.

One possible solution is to allow an option field or fields to be submitted with the [node drain api](https://www.nomadproject.io/api-docs/nodes#drain-node) call that are then shown in the node events.

**Comment by schmichael** [comment]
While it's tempting to add a generic `emit a node event` hook, I think a purpose built field for this is ideal so the UX is familiar:

```
git commit -m "We all know how to write commit messages"

nomad node drain -self -m "So let's add them to drains"
```

Not saying `-m` is the right option name, but I think that UX might be useful especially as more drains are orchestrated by code instead of humans.
