### ISSUE TITLE
Add a "latest" folder for Nomad releases

### ISSUE THREAD

**Issue by spack971** [hashicorp/nomad#9934]
Hi,

I'm saying that for Nomad because this is where I need it so far, but this is actually true for all Hashicorp packages.

Could you add a "_latest_" or better, a "_nomad_latest_" folder in the [releases](https://releases.hashicorp.com/nomad/) pointing to the latest version available?

This is useful when using a configuration manager like Ansible for example (or any other automation) to just download the latest package available without worrying about the actual version.

**Comment by notnoop** [comment]
Thanks @spack971 for the suggestions.  We'd consider it.

To shed some context, there is a lot of resistance to adding mutable references.  While we strive for backward compatibility, we do make some incompatible changes (e.g. search for BACKWARDS INCOMPATIBILITIES in the [Changelog](https://github.com/hashicorp/nomad/blob/v1.0.3/CHANGELOG.md)).  Specially in production environments, the pattern of relying on ever-moving reference automatically can lead to unexpected behavior changes or, worse, outages.

I agree that in development environment, it's nice to simply use the latest, and use it as a canary for identifying impacting breaking changes or regressions.

**Comment by jrasell** [comment]
A "trick" we use in the nomad-autoscaler Vagrant images is to [query checkpoint to get the latest version](https://github.com/hashicorp/nomad-autoscaler/blob/0ec36392cc90818e9aeb2f1853b75e1051bda8ff/demo/vagrant/horizontal-app-scaling/Vagrantfile#L46) for installation. This could prove handy in the meantime for functionality similar to "latest".

**Comment by Amier3** [comment]
Closing this out as the previous explanations still hold true for why we wouldn't implement something like this. I hope the work-arounds provided here work for your use case or for the various use cases of anyone who may see this issue in the future!
