### ISSUE TITLE
feature request: show allocatable cpu in ui

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#9938]
### Nomad version
1.0.1

### Operating system and Environment details
linux

### Issue
when setting the [reserved](https://www.nomadproject.io/docs/configuration/client#reserved-parameters) cpu in the client configuration, nomad ui still shows the total cpu resource of the host instead of the actual allocatable cpu resource, which is confusing as at the first glance it is not able to identify why is the cpu dimension exhausted since it looks like there are a lot available.

In this case I am reserve 3Ghz cpu.

Client view:
![image](https://user-images.githubusercontent.com/21690857/106525175-d372e780-64a0-11eb-81e7-8d1bb8dec002.png)

Topology view:
![image](https://user-images.githubusercontent.com/21690857/106525450-3795ab80-64a1-11eb-981a-2e3b5493ffee.png)

`nomad node status <node-id>` is able to show the correct reading:
```
Allocated Resources
CPU         Memory       Disk
0/2184 MHz  0 B/1.9 GiB  0 B/17 GiB

Allocation Resource Utilization
CPU         Memory
0/2184 MHz  0 B/1.9 GiB
```

**Comment by backspace** [comment]
Hey, thanks for opening this! Would you consider it related to #8694?

**Comment by fredwangwang** [comment]
@backspace Thanks for pointing me to that! That does look like the same, my bad didn't search throughly on the issues. Feel free to close this issue
