### ISSUE TITLE
Allow expressing scheduling references besides constraints

### ISSUE THREAD

**Issue by israellot** [hashicorp/nomad#9949]
Would be interesting to have an option to express placement preferences on top of constraints. 

I have a scenario where I'm running a cluster with reserved VMs and spot VMs. 
Spot VMs will have higher specs and I would like jobs to be scheduled on spot VMs preferentially, but I don't want to constrain them to spot VMs since I need the fallback in case they go down. 
( simplified scenario to make a point )

**Comment by nickethier** [comment]
Hey @israellot 

This is supported through the use of [affinities](https://www.nomadproject.io/docs/job-specification/affinity). For your spot example you can have your spot instances have a special [client meta](https://www.nomadproject.io/docs/configuration/client#meta) attribute then prefer jobs be scheduled on clients that have said attribute.

Feel free to reopen this issue if this doesn't solve your use case. Thanks!
