### ISSUE TITLE
[feature request] Support input variables for `/v1/jobs/parse` HTTP API

### ISSUE THREAD

**Issue by tgxworld** [hashicorp/nomad#9953]
For reporting security vulnerabilities [please refer to the website.](https://www.nomadproject.io/security.html)

If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Operating system and Environment details
n/a
### Issue
Currently `nomad run` supports the `-var` and `-var-file` option which allows the use of [input variables](https://www.nomadproject.io/docs/job-specification/hcl2/variables#input-variables) in Nomad job files. However, it doesn't seem like the Nomad HTTP API supports this just yet. Was wondering if there are any plans to add support for input variables via the [parse job] API(https://www.nomadproject.io/api-docs/jobs#parse-job)? Will a PR be welcomed to add support for a `var` parameter to the endpoint below?

https://github.com/hashicorp/nomad/blob/4e0e33e7c0bfbf48b4729d3b02950b9ced7edb06/command/agent/job_endpoint.go#L681-L684

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Hi @tgxworld! The variable interpolation for HCL2 is done entirely within the command line client, and not server-side. By the time the HTTP API is seeing it, the variable interpolation has already been done. This is how we can do things like `-var-file` which are grabbing a file from, say, your laptop's disk and not somewhere on the cluster.

I don't think we want to implement this on the HTTP API. What would be a use case that wouldn't be better supported by interpolating in the client that's using the HTTP API itself?

**Comment by tgxworld** [comment]
Hi @tgross, thank you for the explanation. We were interacting directly with Nomad’s HTTP API as the Nomad binary is not available in our build container which we are running. Are input variables only supported when submitting jobs via Nomad CLI?

**Comment by tgross** [comment]
> Are input variables only supported when submitting jobs via Nomad CLI?

That's right.

**Comment by tgxworld** [comment]
O ok :) That clear things up for me. We’ll just make the Nomad binary available in our build container as we’ll like to rely on input variables in our Nomad job file. Thank you for taking the time to explain this to me 👍
