### ISSUE TITLE
ignore license-related raft entries in Nomad OSS

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#9958]
When Nomad Enterprise servers start, they either immediately create a temporary license raft entry or get a raft entry for the license from their peers. If a Nomad OSS server is joined to a cluster where these raft entries have been written, it will panic on startup. The [`fsm.Apply`](https://github.com/hashicorp/nomad/blob/v1.0.3/nomad/fsm.go#L193-L316) method will encounter an unknown raft message type and panic as expected. (See https://github.com/hashicorp/nomad/issues/9774 for an example.)

Normally this is the right thing to do, because an unknown message type that was accepted could be replicated around the cluster, corrupting state as it goes. But we may want to consider ignoring the messages for licenses. We have an existing facility in `fsm.Apply` to do so, but we typically avoid using it because reasoning about raft's behavior quickly gets "off the edge of the map". In the case of licenses it seems relatively safe; if the ENT cluster has other ENT-only raft messages (ex. quotas), we'll panic anyways. This issue is to discuss whether this can be done safely.

**Comment by tgross** [comment]
Licensing has been removed from raft in Nomad 1.1.0 and beyond. We've kept the raft entries so that we don't panic newer ENT clusters, but by the time we'd get around to fixing this those earlier versions of the license raft entries will be out of support. Going to close this as wontfix.

**Comment by EtienneBruines** [comment]
As this issue is closed, is this `note` still valid? https://www.nomadproject.io/docs/enterprise#nomad-enterprise

**Comment by tgross** [comment]
Yes, at least until 0.12.0 is entirely out of support.
