### ISSUE TITLE
Nomad creates copy of existing job when trying to move it between namespaces

### ISSUE THREAD

**Issue by zhelezovartem** [hashicorp/nomad#9965]
### Nomad version
Nomad v1.0.2 (4c1d4fc6a5823ebc8c3e748daec7b4fda3f11037)

### Operating system and Environment details
Ubuntu 18.04.5 LTS

### Issue
I tried to update existing job to move it from "default" to another (let say "project1") namespace. Instead of moving my job to another namespace Nomad created copy of existing job. So as a result I have 2 identical jobs - one in "default" namespace, second in "project1" namespace.

### Reproduction steps
1. Create Nomad job config job.nomad to run it in "default" namespace.
2. Deploy job `nomad job run job.nomad`
3. Modify job.nomad file to run it in "project1" namespace (add `namespace = "project1"`)
4. Run `nomad job run job.nomad`
5. Got 2 identical jobs - one in "default" namespace, second in "project1" namespace.

**Comment by tgross** [comment]
Hi @zhelezovartem! This behavior is probably not well-documented but is what's expected. A job is uniquely identified per-namespace. Imagine a slightly different scenario and you can see why:

* UserA has an ACL token with `submit-job` to `namespace-a`.
* UserB has an ACL token with `submit-job` to `namespace-b`.
* UserA submits a job named "example" to `namespace-a`.
* UserB submits a job named "example" to `namespace-b`.

We would not want to "move" UserA's job to `namespace-b` in that case! Each namespace, including the `default` namespace, is intentionally separate. What's probably not well-documented is that the `default` namespace doesn't mean "no namespace", but it means "in the namespace named `default`".

**Comment by zhelezovartem** [comment]
Oh, great thanks for explanation! So if I need to transfer job from one namespace to another I should run `nomad job stop -purge ...` before running it in another namespace.

**Comment by tgross** [comment]
Yup, that's right!
