### ISSUE TITLE
Exec button in Nomad UI not working from allocation page.

### ISSUE THREAD

**Issue by zhelezovartem** [hashicorp/nomad#9966]
### Nomad version
Nomad v1.0.2 (4c1d4fc6a5823ebc8c3e748daec7b4fda3f11037)

### Operating system and Environment details
Ubuntu 18.04.5 LTS

### Issue
I have ACL-enabled Nomad cluster. Nomad job run in non-default namespace. I go to Nomad UI and authenticate myself with management token. I choose my job, then choose one of running allocations and try to push `Exec` button on the allocation page. As a result, I got this error:
```
Not Found
What you're looking for couldn't be found. It either doesn't exist or you are not authorized to see it.
```
At the same time, if I try to push `Exec` button from the job page, it works as expected.

**Comment by cgbaker** [comment]
Thanks for the report, @zhelezovartem, I have most recently seen this behavior as well. Based on the queries from the browser, it appears that the UI is neglecting to pass the `?namespace` parameter. We'll look into this further.

**Comment by zhelezovartem** [comment]
Great, thanks!

**Comment by backspace** [comment]
Thanks again, @zhelezovartem, and for the correct diagnosis, @cgbaker. The URL generator was looking for the namespace in the query parameters of the existing URL, but allocation (and task) routes don’t have a namespace query parameter. I’ve opened #9968 to extract the namespace (and region) from the job instead.
