### ISSUE TITLE
Docs: weird apostrophe

### ISSUE THREAD

**Issue by alexiri** [hashicorp/nomad#9978]
Sorry for the trivial bug, but what's with this weird upside-down apostrophe?

![Screenshot_2021-02-05_11-49-29](https://user-images.githubusercontent.com/5055697/107025236-6a91b500-67a9-11eb-9e16-329e33fb5fa5.png)

It's all over the place in the docs, this particular example is from https://www.nomadproject.io/docs/runtime/interpolation.

**Comment by tgross** [comment]
Hi @alexiri... uh, yeah that's weird, right? 😀 

I took a look at [envvars.mdx](https://github.com/hashicorp/nomad/blob/master/website/content/partials/envvars.mdx) where that's coming from and it's encoded like so:

`<td>Task&lsquo;s name</td>`

There's actually two issues with that file: the weirdly-encoded quote and that it's still using hand-rolled tables instead the nice table markdown that we get with our newer docs rendering pipeline.
