### ISSUE TITLE
[question] Does Nomad Team considering switch from Docker engine to CRI?

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/nomad#9984]
Basically the same thing as [k8s team planning right now](https://kubernetes.io/blog/2020/12/02/dockershim-faq/).

it would be very cool to see [containerd plugin](https://www.nomadproject.io/docs/drivers/external/containerd) adopted as Hashicorp one.

**Comment by tgross** [comment]
HI @Oloremo! It's definitely something we've considered, but it's not on the near-term roadmap. We want to do a refresh of our `exec` driver, which currently uses libcontainer directly. But folks will still want the higher-level abstraction and richer configuration options of something like containerd or podman (as well as having third-party tooling that talks to those APIs). So lots of design work to do there.

I will note that the containerd plugin is designed by a third-party who have designed it for their particular use. So if you decide to use it, make sure it's fitting your use case.
